### ISSUE TITLE
Create new window on startup if none exist

### ISSUE THREAD

**Issue by danielcompton** [alacritty/alacritty#1034]
On closing Alacritty on macOS by quitting/force quitting it, the next time it its run, no window is created. The only way I've found to fix this is by deleting `~/Library/Saved\ Application\ State/io.alacritty.savedState`. It looks like the window not being shown is saved before shutdown, and a new window isn't created on startup.

This is similar to #909 and #958, but I haven't seen this exact problem mentioned so I thought I'd raise it here.

> Which operating system does the issue occur on?

macOS 10.13

**Comment by jadijadi** [comment]
Was checking the issues and saw this one. At the moment this works fine for me. Tried various ways to kill/close/quit Alacritty but it opens normally. MacOS Sonoma 14.3.1.

Decided to comment so we will be able to close this if no more complains on this 2018 issue. 

@danielcompton are you still have your 10.13 Mac? is the issue still happening?
