### ISSUE TITLE
Trouble inputting Chinese characters (macOS)

### ISSUE THREAD

**Issue by rlue** [alacritty/alacritty#1040]
When inputting Chinese text, a user has to enter multiple keystrokes and then select a candidate character (optionally, from an on-screen menu). In alacritty (on macOS), the keystrokes return literal characters to the screen, and the candidate characters never appear.

Not sure if this is related to #209, _Hangs whenever I try to input a diacritic (macOS)._

![kapture 2018-01-19 at 10 50 03](https://user-images.githubusercontent.com/12194123/35132498-910c2582-fd06-11e7-9748-7d14f21d1b9c.gif)

**Comment by francesca64** [comment]
Could you try out this branch? https://github.com/francesca64/alacritty/tree/macos-kb

(Relevant winit PR: tomaka/winit#518)

**Comment by rlue** [comment]
Unfortunately, this doesn't work for me. When I switch to my Chinese input method (Zhuyin), I can start typing in Chinese, but:

1. the syllabic characters (ㄋㄧˇ etc.) I press don't appear on the screen,
2. but the candidate character window _does_ appear **if** I invoke it (_e.g.,_ with down arrow), and
3. final character selections appear as a full-width (2-byte) underscore in Alacritty, but copy to the clipboard as the actual Chinese characters.

[This video should illustrate the problem](https://youtu.be/AtuTkrp7-PY).

---

**rustc** 1.26.0 (a77568041 2018-05-07)
**Mac OS** 10.11.6 El Capitan

**Comment by francesca64** [comment]
Thanks for the detailed info! It seems that this handles some input methods better than others.

Unfortunately, I'm leaving further refinement to future PRs. I can't say when this will be fully functional, but it should be easier for other people to improve macOS keyboard handling now.

**Comment by BurningLutz** [comment]
@rlue I encountered the same problem that Chinese characters are shown as full-width undersocres inside tmux in Alacritty of macos-kb branch, but if I set LANG manually to something like 'zh_CN.UTF-8' and then enter tmux, those Chinese characters are shown as expected.

Can you give it a try?

**Comment by hungte** [comment]
On my Mac (10.13), I see same problem when using the built-in Zhuyin IME from Mac. However, everything works perfectly if I switch to Open Vanilla, a famous open source IME on Mac.

**Comment by silenceleaf** [comment]
It will be great if Alacritty can define more than one fonts (like VS code)

**Comment by nixpulvis** [comment]
@silenceleaf you would be interested in #957.

**Comment by cgxxv** [comment]
Please check out this. I don't know if this can be fixed by configuration or sth else.

https://user-images.githubusercontent.com/6456505/162604953-0c4a44bd-7a88-4852-a748-2a53f21c969d.mov

**Comment by y2-Whyto** [comment]
> Please check out this. I don't know if this can be fixed by configuration or sth else. The terminal and item2 is ok, while alacritty is not.
> 
>  Screen.Recording.2022-04-10.at.14.00.23.mov

Totally the same issue. Alacritty seems to monitor every keystroke in its window regardless of IMEs (on macOS) (I use Chinese Pinyin as well)... Hope this bug could be fixed asap🙏🙏

**Comment by gzm55** [comment]
met the same trouble, +1 for this issue, plz

**Comment by chrisduerr** [comment]
@gzm55 Could you test the latest master? There have been some recent IME changes but I'm not sure how they affect macOS.

**Comment by gzm55** [comment]
> @gzm55 Could you test the latest master? There have been some recent IME changes but I'm not sure how they affect macOS.

test [Alacritty Version 0.11.0 Release Candidate 1](https://github.com/alacritty/alacritty/releases/tag/v0.11.0-rc1)?

**Comment by gzm55** [comment]
> > @gzm55 Could you test the latest master? There have been some recent IME changes but I'm not sure how they affect macOS.
> 
> test [Alacritty Version 0.11.0 Release Candidate 1](https://github.com/alacritty/alacritty/releases/tag/v0.11.0-rc1)?

@chrisduerr , i just confirmed that, the bug shown in the video from @cgxxv is fixed in 0.11.0 RC1.

**Comment by chrisduerr** [comment]
This might sound somewhat outlandish, but the entire point of ***release*** candidates is to prepare for another stable release.
