### ISSUE TITLE
Cache FreeType metrics

### ISSUE THREAD

**Issue by jwilm** [alacritty/alacritty#1045]
They are currently recomputed every time [`ft::Rasterizer::full_metrics`] is called. This seems like an easy performance improvement.

This is follow-up work to #1029.

[`ft::Rasterizer::full_metrics`]: https://github.com/jwilm/alacritty/blob/59b561b440060e7b0d13160fb69519d127e6c687/font/src/ft/mod.rs#L161

**Comment by rkanati** [comment]
This should probably be profiled. I agree it's kind of lame, but it's mostly just plumbing through stuff that FreeType _already_ has in-memory anyways.

**Comment by chrisduerr** [comment]
The font metrics have been cached for a while now.
