### ISSUE TITLE
Alt-Shift does not send ESC for many symbols on repeated presses 

### ISSUE THREAD

**Issue by shicks** [alacritty/alacritty#1054]
Which operating system does the issue occur on?
linux

If on linux, are you using X11 or Wayland?
X11

Repro steps:
1. Build alacritty at head (59b561b) and launch with `--config-file /dev/null`.
2. Run `showkey -a`
3. For the following keys, press Alt-Shift-<key> twice and Shift-Alt-<key> twice

Affected keys: `!<>?{}|#$%^&*()_+~` (at least)

What happens:
When alt is pressed first, the first time the symbol key is pressed it sends the ESC prefix correctly.  Subsequent keystrokes send just the symbol with no ESC.  When shift is pressed first, the ESC is *never* sent.

What should happen:
Every keypress should send ESC as a prefix, regardless of the order of alt and shift.

*EDIT: added more affected keys (`_`).*

**Comment by ionrock** [comment]
I'm also running linux / x11 and think I might have hit the same issue. 

When running Emacs, the keybinding `M->` goes to the end of the file buffer. That keybinding is "alt + shift + .", but it only works if I press the keys in that order. If I press "shift + alt + ." it will insert a ">" symbol.

**Comment by shicks** [comment]
That's exactly where I run into it, primarily. In a few weeks I might be able to build an older version and see if I can figure out when this behavior was introduced. Or hopefully somebody else might find it first.

**Comment by shicks** [comment]
Sadly, bisecting points to ae533e6 (Update glutin to v0.10) as the culprit.  So I don't know if it's a bug in glutin or in how alacritty uses glutin, but it seems to be out of my depth to troubleshoot any further.

Are there really no other emacs users out there running into this?

Could this possibly be related to tomaka/glutin#979?  All three keys that bug mentions are affected.

**Comment by shicks** [comment]
Indeed, I added some debugging to event.rs and found that the `KeyboardInput` has a `virtual_keycode` of `None` in all the broken cases.  So `process_key` is not setting `last_modifiers` and `received_count` like it needs to in order to send the ESC correctly in `received_char`.  I can fix it with the following:

```diff
diff --git a/src/input.rs b/src/input.rs
index bc172bc..d5ff036 100644
--- a/src/input.rs
+++ b/src/input.rs
@@ -490,8 +490,15 @@ impl<'a, A: ActionContext + 'a> Processor<'a, A> {
                     *self.ctx.suppress_chars() = true;
                 }
             },
-            (_, ElementState::Released) => *self.ctx.suppress_chars() = false,
-            _ => ()
+            (None, ElementState::Pressed) => {
+                if mods.shift {
+                    *self.ctx.last_modifiers() = *mods;
+                    *self.ctx.received_count() = 0;
+                    *self.ctx.suppress_chars() = false;
+                }
+            },
+            (_, ElementState::Released) => *self.ctx.suppress_chars() = false
+            // _ => ()
```

Though I suspect that will probably break something else.  I'll give it a try for a while and see if anything else is wonky.

**Comment by shicks** [comment]
I've been running with this patch for a few days and haven't noticed anything odd.

However, I've also noticed another seemingly-related bug: keybindings to these shifted symbols with other modifier keys are also being ignored, and obviously this fix isn't going to handle that.  For instance, I bind `{key: Comma, mods: Control|Shift, chars: "\x1b[36~<"}`, but pressing C-S-< just sends <, rather than triggering my binding.

Presumably the same thing is happening here: the `KeyboardInput` event sees the modifiers, but the `virtual_keycode` is `None`, so the binding is not found in `process_key`.  Then `received_char` finally finds out the keycode (more or less) but is no longer interested in looking for bindings.

A more general hack could be to push off a lot of the keybinding logic to `received_char`, though it wouldn't be possible to do it everywhere, since no all keyboard inputs lead to actual characters.  Really, glutin needs to be fixed.  I assume we depend on some fix that was introduced in 0.10 that prevents rolling back to an earlier version?

**Comment by shicks** [comment]
It seems to be possible to do a secondary keybinding check in `received_char`.  I'm not happy with this workaround, but it does seem to get the job done:

```diff
diff --git a/src/input.rs b/src/input.rs
index 21c4847..457d151 100644
--- a/src/input.rs
+++ b/src/input.rs
@@ -496,40 +496,91 @@ impl<'a, A: ActionContext + 'a> Processor<'a, A> {
         key: Option<VirtualKeyCode>,
         mods: &ModifiersState,
     ) {
-        match (key, state) {
-            (Some(key), ElementState::Pressed) => {
-                *self.ctx.last_modifiers() = *mods;
-                *self.ctx.received_count() = 0;
-                *self.ctx.suppress_chars() = false;
-
-                if self.process_key_bindings(mods, key) {
-                    *self.ctx.suppress_chars() = true;
-                }
-            },
-            (_, ElementState::Released) => *self.ctx.suppress_chars() = false,
-            _ => ()
+        *self.ctx.last_modifiers() = *mods;
+        *self.ctx.suppress_chars() = false;
+        if state == ElementState::Pressed {
+            *self.ctx.received_count() = 0;
+
+            match key {
+                Some(key) => {
+                    if self.process_key_bindings(mods, key) {
+                        *self.ctx.suppress_chars() = true;
+                    }
+                },
+                _ => (),
+            }
         }
     }
     /// Process a received character
     pub fn received_char(&mut self, c: char) {
-        if !*self.ctx.suppress_chars() {
-            self.ctx.clear_selection();
+        if *self.ctx.suppress_chars() {
+            return
+        }
-            let utf8_len = c.len_utf8();
-            if *self.ctx.received_count() == 0 && self.ctx.last_modifiers().alt && utf8_len == 1 {
-                self.ctx.write_to_pty(b"\x1b".to_vec());
-            }
+        match (self.ctx.last_modifiers().shift, self.unshifted_key_code(c)) {
+            (true, Some(key)) => {
+                let mods = *self.ctx.last_modifiers();
+                if self.process_key_bindings(&mods, key) {
+                    *self.ctx.suppress_chars() = true
+                }
+            },
+            _ => (),
+        }
+        if *self.ctx.suppress_chars() {
+            return
+        }
-            let mut bytes = Vec::with_capacity(utf8_len);
-            unsafe {
-                bytes.set_len(utf8_len);
-                c.encode_utf8(&mut bytes[..]);
-            }
+        self.ctx.clear_selection();
-            self.ctx.write_to_pty(bytes);
+        let utf8_len = c.len_utf8();
+        if *self.ctx.received_count() == 0 && self.ctx.last_modifiers().alt && utf8_len == 1 {
+            self.ctx.write_to_pty(b"\x1b".to_vec());
+        }
-            *self.ctx.received_count() += 1;
+        let mut bytes = Vec::with_capacity(utf8_len);
+        unsafe {
+            bytes.set_len(utf8_len);
+            c.encode_utf8(&mut bytes[..]);
+        }
+
+        self.ctx.write_to_pty(bytes);
+
+        *self.ctx.received_count() += 1;
+    }
+
+    fn unshifted_key_code(&self, c: char) -> Option<VirtualKeyCode> {
+        match c {
+            // NOTE: both C-~ and C-^ seem to send ^^=\x1e
+            '~' => Some(VirtualKeyCode::Grave),
+            '!' => Some(VirtualKeyCode::Key1),
+            '@' => Some(VirtualKeyCode::Key2),
+            '\0' => Some(VirtualKeyCode::Key2),
+            '#' => Some(VirtualKeyCode::Key3),
+            '$' => Some(VirtualKeyCode::Key4),
+            '%' => Some(VirtualKeyCode::Key5),
+            '^' => Some(VirtualKeyCode::Key6),
+            '\x1e' => Some(VirtualKeyCode::Key6),
+            '&' => Some(VirtualKeyCode::Key7),
+            '*' => Some(VirtualKeyCode::Key8),
+            '(' => Some(VirtualKeyCode::Key9),
+            ')' => Some(VirtualKeyCode::Key0),
+            '_' => Some(VirtualKeyCode::Subtract),
+            '\x1f' => Some(VirtualKeyCode::Subtract),
+            '+' => Some(VirtualKeyCode::Equals),
+            '{' => Some(VirtualKeyCode::LBracket),
+            '\x1b' => Some(VirtualKeyCode::LBracket),
+            '}' => Some(VirtualKeyCode::RBracket),
+            '\x1d' => Some(VirtualKeyCode::RBracket),
+            '|' => Some(VirtualKeyCode::Backslash),
+            '\x1c' => Some(VirtualKeyCode::Backslash),
+            ':' => Some(VirtualKeyCode::Semicolon),
+            '"' => Some(VirtualKeyCode::Apostrophe),
+            '<' => Some(VirtualKeyCode::Comma),
+            '>' => Some(VirtualKeyCode::Period),
+            '?' => Some(VirtualKeyCode::Slash),
+            _ => None,
         }
     }
```

**Comment by dnkl** [comment]
I'm also seeing this. Noticed it in Emacs too (M-> ...)

**Comment by traviscross** [comment]
To summarize the current situation, this issue appears to be related to winit issue https://github.com/tomaka/winit/issues/600.  This is being tracked on glutin as https://github.com/tomaka/glutin/issues/979.  Our own issue https://github.com/jwilm/alacritty/issues/1010 is due to the same underlying cause.

**Comment by jwilm** [comment]
Thanks @traviscross for providing all the issue linkage!

**Comment by kchibisov** [comment]
I think this is long fixed.
