### ISSUE TITLE
Strange background opacity behavior on X11 Linux + NVIDIA

### ISSUE THREAD

**Issue by 13k** [alacritty/alacritty#1059]
OS: `Linux 4.14.13-300.fc27.x86_64 #1 SMP Thu Jan 11 04:00:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
Distro: Fedora 27
OpenGL info: https://gist.github.com/13k/58ec3d41dfcc038aaf48862028e50e77
alacritty version: git b82622e9948d1c90fc628739c7f328816214fb33

---

Background is completely transparent, regardless of `background_opacity`'s value.

Screenshot:

![selection_007](https://user-images.githubusercontent.com/4762/35474876-98db1acc-037b-11e8-8ba9-7f805c20bca2.png)

**Comment by chrisduerr** [comment]
Try running it with `env WAYLAND_DISPLAY= alacritty`.

**Comment by 13k** [comment]
Issue still occurring. I don't think wayland is an issue, since it's not enabled for me (for some reason, it's still disabled even using GNOME/mutter 3.26+ and latest nvidia drivers):

```
$ echo $WAYLAND_DISPLAY

```

```
$ loginctl
   SESSION        UID USER             SEAT             TTY             
        c2         42 gdm              seat0            /dev/tty1       
         3       1000 k                seat0            /dev/tty2       

2 sessions listed.
$ loginctl show-session c2 -p Type
Type=x11
$ loginctl show-session 3 -p Type
Type=x11
```

**Comment by chrisduerr** [comment]
Actually looking at the screenshot, it looks like not only the background, but the complete window is transparent. This would indicate to me that your compositor is doing something odd, not alacritty itself.

But just to make sure you can try to disable alacritty's transparency support by changing this line to `false`:
https://github.com/jwilm/alacritty/blob/master/src/window.rs#L200

**Comment by 13k** [comment]
You're right, the whole window is transparent. Turning off transparency did make the window to render correctly:

![selection_011](https://user-images.githubusercontent.com/4762/35514934-f362e5fa-04ee-11e8-8c59-94d134160a76.png)

It does looks like an issue with the compositor, but Tilix renders correctly with transparency enabled:

![selection_012](https://user-images.githubusercontent.com/4762/35515020-35982818-04ef-11e8-829a-4be74740bdf6.png)

So I investigated a little more and it seems it's related to glutin/winit. Building alacritty @ 20aa45c, before the upgrade to glutin from 0.11 to 0.12, transparency works as expected.

**Comment by 13k** [comment]
So I tested glutin in an [isolated example](https://gist.github.com/13k/62655ae9dd4e8ae0fb1bc7bd375bc96d) [*] (modified version of [glutin's window example](https://github.com/tomaka/glutin/blob/e5f37ae495a550704e57dc2480a134a9b4a07f52/examples/window.rs)) and it seems the issue is caused by the window visibility = false followed by window show:

`./target/debug/glutin-transparency-example`

![selection_013](https://user-images.githubusercontent.com/4762/35522764-565ed7d0-0504-11e8-9dbb-d19cde0cdd58.png)

`./target/debug/glutin-transparency-example yes`

![selection_014](https://user-images.githubusercontent.com/4762/35522773-5db499b6-0504-11e8-85c0-4ed0c5d49a55.png)

[*]: pardon my rust, it's the first time I ever wrote anything in it

**Comment by oliveiraev** [comment]
Hello!

Sorry if necrobumping, but this is the open issue closest to mine.

My issue is that transparency settings aren't honored under dGPU with hybrid PRIME settings

### System

OS: ![image](https://user-images.githubusercontent.com/320460/88727140-63586300-d105-11ea-9341-92e36dbf4393.png)

Version: 
```
➜ ~ alacritty --version
alacritty 0.6.0-dev (b7faa9f)
```

Linux/BSD: X11; Cinnamon with composition
```
➜ ~ cinnamon --version
Cinnamon 4.6.6
```

When running via iGPU, things went well... 
![image](https://user-images.githubusercontent.com/320460/88728133-6a807080-d107-11ea-9873-52f3112e5991.png)


But, when running via dGPU (`__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia alacritty`), I cant use transparency...
![image](https://user-images.githubusercontent.com/320460/88728087-53418300-d107-11ea-80c2-be401b99b0d1.png)

**Comment by tunix** [comment]
I have the exact same issue with @oliveiraev using Ubuntu 20.10 with nVidia 455.38 driver on X11.

**Comment by 13k** [comment]
It looks like it's an issue with NVIDIA's FXAA implementation.

As I commented [here](https://github.com/alacritty/alacritty/issues/2287#issuecomment-515757169), disabling FXAA seems to fix the issue and is a viable workaround.

I tested on both Windows (per comment above) and Linux (same hardware).

**Comment by chrisduerr** [comment]
As stated by @13k this is an issue with having FXAA enabled with the Nvidia drivers. So it should be disabled for Alacritty to make everything work correctly.
