### ISSUE TITLE
Move ANSI parser into vte crate

### ISSUE THREAD

**Issue by jwilm** [alacritty/alacritty#1063]
There's some demand to reuse the higher level parser from Alacritty, and the development of that module has slowed significantly. It's probably at a good point where it can be moved into an external crate.

**Comment by nixpulvis** [comment]
Sounds like this boils down to moving the `ansi` module directly over. The only internal dependencies of this module are:

```rust
use crate::index::{Column, Line};
use crate::term::color::Rgb;
```

so this should be pretty easy.

**Comment by nw0** [comment]
I'm willing to try doing this. Do I understand that `Column`, `Line`, and `Rgb` should be moved over? They seem fairly integral to the `Handler` trait.
