### ISSUE TITLE
Can't type russian characters

### ISSUE THREAD

**Issue by bikbah** [alacritty/alacritty#1064]
Cannot reopen #793, so opening new issue.

macOS High Sierra 10.13.2

Cannot type any cyrillic letters 
```
-->Hello
bash: Hello: command not found
-->
-->:\237\321\320\320\320\321

-->locale
LANG="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_CTYPE="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_ALL=
```

`en_US.UTF-8` did not solve problem

**Update**:
Terminal.app (iTerm2 as well):
```
-->:~ $ locale
LANG="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_CTYPE="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_ALL=
```

Alacritty:
```
-->locale
LANG="en_RU.UTF-8"
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

setting `ru_RU.UTF-8` env variables in `~/.bashrc` (which shows `locale` output as in Terminal.app) doesn`t help

**Comment by francesca64** [comment]
Could you try out this branch? https://github.com/francesca64/alacritty/tree/macos-kb

(Relevant winit PR: tomaka/winit#518)

**Comment by pryg-skok** [comment]
It seems the problem persists on macos-kb
No matter which locale used:

```
~ $ locale
LANG="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_CTYPE="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_ALL="ru_RU.UTF-8"
```


```
~ $ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"```

**Comment by francesca64** [comment]
Hm, it works for me using the Russian input method, even on master. Locale also doesn't seem to matter. Since you're getting the right bytes, this looks like it probably isn't a problem with winit.

**Comment by nikolaevigor** [comment]
Experiencing same issue.
Also, when viewing files I see russian chars like this:
![screenshot at oct 05 21-46-32](https://user-images.githubusercontent.com/3702281/46554200-3b708d80-c8e8-11e8-864b-094f58b19b8a.png)

**Comment by starkovv** [comment]
+1

**Comment by pryg-skok** [comment]
Any progress here? The problem still here on 0.3.3 release :(

**Comment by kchibisov** [comment]
@pryg-skok try adding LC_ALL: "ru_RU.UTF-8" to `env` section in `alacritty.yml`.

**Comment by pryg-skok** [comment]
> @pryg-skok try adding LC_ALL: "ru_RU.UTF-8" to `env` section in `alacritty.yml`.

It's worked! Finally :) Thanks!
I think the issue can be resolved

**Comment by kchibisov** [comment]
This is likely a locale issue and is tracked now there #2566. The locale should be set in `alacritty.yml` and not in shell to make it work, like it was initially attempted here.
