### ISSUE TITLE
background transparency goes away when I enter vim

### ISSUE THREAD

**Issue by llimllib** [alacritty/alacritty#1082]
Which operating system does the issue occur on? Mac OS X 10.13.3, alacritty `2466f81`

To reproduce:

1. Set up base16 colors in your terminal: https://github.com/chriskempson/base16-shell
2. Load up a base16 color scheme in vim: https://github.com/chriskempson/base16-vim/blob/master/colors/base16-twilight.vim is the particular one I use
3. notice that your vim background is no longer transparent. If you quit and return to the shell, the transparency returns
  a. in iterm2, with the same vimrc and bashrc, vim remains transparent

**Comment by jwilm** [comment]
What happens if you change

```viml
let s:gui00        = "1e1e1e"
let g:base16_gui00 = "1e1e1e"
```

to be

```viml
let s:gui00        = ""
let g:base16_gui00 = ""
```

**Comment by llimllib** [comment]
No change, unfortunately

**Comment by severen** [comment]
I'm also running into this issue with the Ayu theme on Neovim. Using `03f9e0c`.

**Comment by maximbaz** [comment]
I believe this was caused by https://github.com/jwilm/alacritty/pull/847, however that was a good fix for powerline icons. 

Also, adding `hi! Normal ctermbg=NONE guibg=NONE` after `colorscheme ...` seems to fix the issue for me.

**Comment by laanwj** [comment]
Would be somewhat nice if it was possible to make other background colors transparent as well, say, a green background becomes a transparent green background. I don't know of any terminal that does this, though.

**Comment by kchibisov** [comment]
Your vim colorscheme could set background color to be a specific value(e.g. truecolor or indexed color) in which case alacritty **should** draw it without opacity. To make opacity work in vim, you should use set background in vim to `None`.

Not sure how it helps but something like this could work for arbitrary themes.
```
hi! Normal ctermbg=NONE guibg=NONE
hi! NonText ctermbg=NONE guibg=NONE guifg=NONE ctermfg=NONE
```

**Comment by bjce** [comment]
I have neovim `nvim 0.4.3` and `alacritty 0.7.2 (5ac8060)`

I tried (sequentially) the following lines after `colorscheme` in the `.vimrc` without success: 
```
hi Normal guibg=NONE ctermbg=NONE
hi Normal ctermbg=NONE guibg=NONE
hi! NonText ctermbg=NONE guibg=NONE guifg=NONE ctermfg=NONE
```

I'm also sourcing the `.vimrc` in `vim ~/.config/nvim/init.vim` with the following lines
```
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
" call plug#begin(g:plugged_home)
"     " other plugins...
"     " --------- adding the following three plugins for Latex ---------
"     Plug 'lervag/vimtex'
"     Plug 'Konfekt/FastFold'
"     Plug 'matze/vim-tex-fold'
"     " other plugins...
" call plug#end()
source ~/.vimrc
```
