### ISSUE TITLE
When Capslock is remapped to Ctrl it must be pressed twice to register

### ISSUE THREAD

**Issue by kamranjon** [alacritty/alacritty#1088]
Manjarro Linux, X11

I have my Control C and Control V mappings defined in Alacritty.yml and they work correctly with the Ctrl key - but when using the CapsLock key which is remapped to the Ctrl key it requires that the CapsLock be pressed twice sequentially before it will copy or paste or do anything requiring Ctrl.

**Comment by chrisduerr** [comment]
This might have something to do with the way capslock works. Because it's not a hold-down but a toggle key. If you check with `showkey -a` does the key get reported in the same way as normal Control + C?

**Comment by kamranjon** [comment]
So Control + C doesn't actually show up with showkey -a but I did Control + A and had the same thing where I had to press Capslock twice to register, but the results from both using Ctrl + A and Capslock + A are here:
`^A        1 0001 0x01
^A        1 0001 0x01`

**Comment by synul** [comment]
@kamranjon Were you able to resolve the issue? I'm having the same problem on Manjaro, Caps Lock remapped with `setxkbmap -option caps:ctrl_modifier`.

**Comment by chrisduerr** [comment]
@synul Could you share your `alacritty --print-events` output when pressing remapped caps?

**Comment by synul** [comment]
Sure, I have the exact same output as the the other commenter:
```
^A   1 0001 0x01
^A   1 0001 0x01
```
Not sure if this makes any sense but when I was first trying the remapped key, I wanted to use Caps + d to close a tmux pane. Since it didn't work I kept pushing d because I thought it maybe didn't register the first time. If I keep Caps pressed and press d thre times it will eventually work. The ouput from that (with a instead of d) is:
```
å   195 0303 0xc3
    165 0245 0xa5
^A  1 0001 0x01
```

**Comment by chrisduerr** [comment]
@synul I am looking for the stdout of running `alacritty --print-events`, not the `showkey` output.

**Comment by synul** [comment]
Oh, right, didn't see that. Here's a gist:
https://gist.github.com/synul/06fc8c096b0da7f7b9cd6e75057e2cdd

**Comment by chrisduerr** [comment]
It's difficult to judge with such a big log without direct association to the events, but it looks like the first press activates the `Compose` key? Do you have a compose key setup?

**Comment by synul** [comment]
Actually, I had to re-install my OS and switched to Ubuntu. Unfortunately I don't remember if I had set up a compose key, but it is working as expected now!
In any case, thanks so much for the support!

**Comment by chrisduerr** [comment]
@kamranjon Can you still repro this?
