### ISSUE TITLE
Alt+PgUp, Alt+PgDown, Alt+Home, Alt+End, Alt+Ins, and Alt+Del don't work in alacritty.

### ISSUE THREAD

**Issue by crocket** [alacritty/alacritty#1139]
Which operating system does the issue occur on? Gentoo Linux
If on linux, are you using X11 or Wayland? X11

weechat uses Alt+PgUp and Alt+PgDown for scrolling a few line up and down.
Because alacritty doesn't support Alt+NavigationKeyCluster, I ended up mapping Shift+PgUp and Shift+PgDown to scrolling in weechat.

Alt+Left, Alt+Up, Alt+Down, and Alt+Right seem to output suspicious control codes that I don't understand, yet.

**Comment by alfunx** [comment]
Take a look at the [last section of the default configuration](https://github.com/jwilm/alacritty/blob/master/alacritty.yml#L247). Just add an entry for `Alt+PgUp` etc. and put the correct escape sequence there (described in the comment there).

**Comment by crocket** [comment]
Why does it require configuration?

**Comment by crocket** [comment]
Shall I update terminfo file, too?

suckless st's config.h says I have to update terminfo file if I change keyboard bindings.

**Comment by kchibisov** [comment]
The mentioned bindings were added there #2785
