### ISSUE TITLE
BELL does not sound/flash on macOS

### ISSUE THREAD

**Issue by rlue** [alacritty/alacritty#1170]
Forgive me if this is a naive problem; I've [just read on SO that](https://stackoverflow.com/a/3456167/4865822)

> ASCII character 7 is the BELL character, and it's represented in C as \a. Some terminals will produce a beep when this character is output on the terminal; nowadays, many don't. (I'm looking at you, Ubuntu.)

Nevertheless, `printf "\a"` produces the system bell in Terminal.app and iTerm, while alacritty does not. Below is a summary of what works and when:

|                  | system bell | visual bell (when muted) |
| ---------------- | :---------: | :----------------------: |
| **Terminal.app** | ✔           | ✔                        |
| **iTerm 2**      | ✔           | ✗                        |
| **Alacritty**    | ✗           | ✗                        |

**Comment by jwilm** [comment]
Sounds like this is specifically talking about the system bell? We have a built-in bell that you can enable via config.

**Comment by rlue** [comment]
Whoops! I'd totally forgotten about that.

It appears that in alacritty, the visual bell flashes regardless of the system mute status. The behavior in Terminal.app is to only flash the visual bell when the system sound is muted, and otherwise to play the alert sound specified under System Preferences > Sound.

It would be nice to see that behavior in alacritty as well, but it's far from crucial.

**Comment by kchibisov** [comment]
You can bind command to run on bell, thus you can make it produce sound.
