### ISSUE TITLE
text compositing or subpixel rendering issue

### ISSUE THREAD

**Issue by insunaa** [alacritty/alacritty#118]
Some characters look weird, as if they were overlapping (and if they actually overlap, brightness is increased).

This is how it looks on my machine (Ubuntu Mono font)
x offset: 0.9
y offset: -10.0
dpi: 91.79

![compositing_issue2](https://cloud.githubusercontent.com/assets/3718129/21736870/30e193ce-d474-11e6-9723-a4bf5f84c915.png)

Edit: I have also tested this with a ridiculously high offset, but these characters still look weird.

**Comment by dannydulai** [comment]
I'm also seeing this on the horizontal pane dividers on tmux/macos/menlo font

**Comment by polyzen** [comment]
Related to #2?

**Comment by d3rrial** [comment]
@polyzen I don't know. It's not fuzzy as described in that issue. It's just not matching up the beginning and end of a character. You can see the same effect (but much more faintly) on the vertical line in the picture above.

**Comment by hot-leaf-juice** [comment]
I'm seeing something that looks very similar, though in my case I seem to have some weirdly located subpixels on almost every character.

![screen shot 2017-01-18 at 16 35 45](https://cloud.githubusercontent.com/assets/11499545/22073613/a7145586-dd9d-11e6-84ab-73ca0b4543a1.png)

![screen shot 2017-01-18 at 16 35 05](https://cloud.githubusercontent.com/assets/11499545/22073621/ace6f946-dd9d-11e6-94ca-9f1d29a97d13.png)

Note in particular the bottom of the `c`, `e`, `u`, `b`, `o`, etc

![screen shot 2017-01-18 at 16 48 22](https://cloud.githubusercontent.com/assets/11499545/22073699/e2c9f0b8-dd9d-11e6-9a6d-475b0d491af0.png)

I don't have the same weird subpixels in any other application.

**Comment by emilhoeiriis** [comment]
Ditching `xf86-video-intel` worked for me. 
If this issue is not going to be resolved now perhaps solutions could be added to docs.

**Comment by bluz71** [comment]
Is this an issue with pursuing anymore?

Most folks encountered this due to use of font-provided box drawing (e.g tmux dividers).

However, Alacritty now (by default) does native box drawing which completely avoids this issue.

Worth closing?

**Comment by chrisduerr** [comment]
Yep, thanks for letting me know. This is as resolved.
