### ISSUE TITLE
Pywal doesn't work with Alacritty

### ISSUE THREAD

**Issue by FranciscoJRSantos** [alacritty/alacritty#1206]
## Specs
**OS**: OSX High Sierra
**Pywal**: Version 1.3.3
**Alacritty**: 0.1.0 (Or so Spotlight says)

## Problem 
Pywal's command `cat sequences` does nothing, even though `printf "%b" "\033]11;#ff0000\007"` does change the background to red. Running `wal -i <file>` does nothing within Alacritty.
Already discussed this problem here [https://github.com/dylanaraps/pywal/issues/37](url) with pywal's creator and some other helpful fellas, who actually confirmed that it was indeed an error that was occuring.

**Comment by chrisduerr** [comment]
Maybe an issue with the locale? Don't know much about macos but there have been a few issues with that. You could try https://github.com/jwilm/alacritty/pull/1087, maybe @sodiumjoe has an idea if this is locale related or not.

**Comment by sodiumjoe** [comment]
It doesn't appear to be locale-related, since the `printf` works fine. I can reproduce the issue, but I don't really know anything about pywal or how alacritty sets colors.

**Comment by chrisduerr** [comment]
Yeah that's a good point, maybe an unsupported escape sequence.

**Comment by FranciscoJRSantos** [comment]
![screenshot](https://user-images.githubusercontent.com/25421850/38178933-9c5bc2f2-3614-11e8-9bd1-c10a8dbe6760.jpg)
I've just installed Alacritty on a manjaro machine I've got at home and those two lines on the left terminal are relative to the error Alacritty throws when reading the colorscheme generated by Pywal. Does this help in any way? This could maybe be related to the error that exists in OSX

**Comment by FranciscoJRSantos** [comment]
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/25421850/38193730-5c65c90c-366b-11e8-8632-b63270ab8dd8.png">

When running Alacritty from iTerm2, that happens. Does this help in any way?

**Comment by kchibisov** [comment]
I think it should work now.
