### ISSUE TITLE
Make it possible to specify window instance and class with command line options

### ISSUE THREAD

**Issue by crocket** [alacritty/alacritty#1238]
I compiled alacritty from the git commit 7f2b398ad2084bdaaa266e8da770a213f0a9a2eb

The available command line options are

```
$ alacritty --help
alacritty 0.1.0
Joe Wilm <joe@jwilm.com>
GPU-accelerated terminal emulator

USAGE:
    alacritty [FLAGS] [OPTIONS]

FLAGS:
    -h, --help                     Prints help information
        --live-config-reload       Enable automatic config reloading
        --no-live-config-reload    Disable automatic config reloading
        --print-events
    -q                             Reduces the level of verbosity (the min level is -qq)
        --ref-test                 Generates ref test
    -v                             Increases the level of verbosity (the max level is -vvv)
    -V, --version                  Prints version information

OPTIONS:
    -e, --command <command>...                     Command and args to execute (must be last argument)
        --config-file <config-file>
            Specify alternative configuration file [default: $XDG_CONFIG_HOME/alacritty/alacritty.yml]

    -d, --dimensions <columns> <lines>
            Defines the window dimensions. Falls back to size specified by window manager if set to 0x0 [default: 80x24]

    -t, --title <title>                            Defines the window title [default: Alacritty]
        --working-directory <working-directory>    Start the shell in the specified working directory
```

I can set title, but not instance. The following are st command line options.

```
$ st -h
usage: st [-aiv] [-c class] [-f font] [-g geometry] [-n name] [-o file]
          [-T title] [-t title] [-w windowid] [[-e] command [args ...]]
       st [-aiv] [-c class] [-f font] [-g geometry] [-n name] [-o file]
          [-T title] [-t title] [-w windowid] -l line [stty_args ...]
```

I can set window instance with `-n` and window class with `-c`. My i3 config finds windows by their classes and instance names.

**Comment by chrisduerr** [comment]
Using the following should work:
```
for_window [class="testing"] floating enable
alacritty --title "testing"
```

Make sure you reload the i3 config with `i3-msg reload` before trying to start alacritty.

**Comment by velrest** [comment]
Sorry for bumping such an old issue but i have exactly the same problem. `xprop` shows me that the alacritty window has actually the class `floatingTerminal` but for some reason my i3 rule does not work. Does anyone know more about this?
```
bindsym $mod+Return exec alacritty
bindsym $mod+Shift+Return exec "alacritty --class=floatingTerminal"
for_window [class="^floatingTerminal$"] floating enable
```

**Comment by crocket** [comment]
* Try removing quotes around `^floatingTerminal$`
* Try removing `$`

**Comment by velrest** [comment]
Sadly always the same result. The window is created in stacked / tabbed layout.
I tried the variations:
* `for_window [class="^floatingTerminal"] floating enable`
* `for_window [class="floatingTerminal$"] floating enable`
* `for_window [class=floatingTerminal] floating enable`

`xprop` output to verify class:
`WM_CLASS(STRING) = "floatingTerminal", "Alacritty"`

**Comment by kchibisov** [comment]
you can always try passing `--class floatingTerminal,floatingTerminal`

**Comment by velrest** [comment]
@kchibisov okay thath worked.
But now im very confused. What is the difference and why is this working?

**Comment by velrest** [comment]
Was the problem that in `WM_CLASS(STRING) = "floatingTerminal", "Alacritty"` the second class was `Alacritty`?

**Comment by velrest** [comment]
@kchibisov Ah okay thanks a lot for you help!
