### ISSUE TITLE
Blink in rtv after every movement

### ISSUE THREAD

**Issue by kirillbobyrev** [alacritty/alacritty#1286]
> Which operating system does the issue occur on?

Arch Linux

> If on Linux, are you using X11 or Wayland?

X11

I'm not really sure what causes the problem, but whenever I open [rtv](https://github.com/michael-lazar/rtv) I have unpleasant experience of the terminal blinking once each time I press down the `[hjkl]` (movement) button. This doesn't happen in urxvt and the only alike thing I have encountered in Alacritty so far was blinking on the resize. I'm not really sure whether it's somehow connected, but I guess this might be some bug.

I'm using `alacritty-git 0.1.0.755.g6debc4f-1` and `rtv 1.21.0-1` from AUR.

**Comment by chrisduerr** [comment]
You could test if the issue is the same as the resize one by running #1279 with opacity set to `1.0`.

**Comment by jwilm** [comment]
This is probably a bug in rtv. Applications which don’t write out a full update in a single write() call sometimes exhibit blinking.

**Comment by chrisduerr** [comment]
As jwilm has already stated, this is an RTV bug. Though for applications that need to do a lot of writing the synchronized updates proposal might help with this (see #598).

**Comment by kirillbobyrev** [comment]
Oh, sorry for not answering, I somehow missed your answer, @chrisduerr.

Thank you very much for checking and letting me know. I didn't use rtv much so I didn't encounter it again but I should've definitely just checked what you proposed.

Thanks for your answers again!
