### ISSUE TITLE
dragging\ file\ into\ terminal\ escape\ path

### ISSUE THREAD

**Issue by ghost** [alacritty/alacritty#1335]
https://github.com/jwilm/alacritty/pull/1304#issuecomment-392601639

spaces in the path are not escaped automatically which is a big pain, kitty does not escape them either but Mac terminal does and it makes it much easier/ faster to use

**Comment by apexo** [comment]
This only makes sense when a shell is running. When a text editor (e.g. vim) is running, the current behaviour seems appropriate. However it seems kind of hard to distinguish the two cases (esp. when using tmux), so it's probably more of a question of which use case is more common … I guess the shell …

**Comment by monouser7dig** [comment]
> When a text editor (e.g. vim) is running, the current behaviour seems appropriate.

**Comment by nixpulvis** [comment]
I might be in favor of two different action (with two keybindings) for normal and escaped paste.

**Comment by jedahan** [comment]
is there some way to trigger bracketed paste mode in tmux for this?

**Comment by chrisduerr** [comment]
@zsmestad I appreciate the thought that went into this, however I don't think most of your arguments are super relevant for alacritty.

We've already built in pastejacking prevention, so there's no need for a warning dialog, the code will not automatically be executed (try it yourself with the website example).

Both escaping different patterns of text and an advanced paste dialog seems out of scope, I don't think this is of use for enough users to really provide a great value. Imo pasting files was worth implementing because it's just so incredibly simple with winit, if it would require a lot of work, it wouldn't be worth it.

But those are just my thoughts on the matter.

**Comment by NickeZ** [comment]
@chrisduerr On my machine (ubuntu 18.04) it prints "evil", i.e. the attack works...

**Comment by chrisduerr** [comment]
Oh yeah, apparently `bash` isn't capable of handling this. It works just fine in `zsh`. The only thing alacritty escapes is actual escape sequences right now, I'm sure this could be extended, but that would probably harm zsh users.

**Comment by monouser7dig** [comment]
so after I added this to my config (Mac) and removed the duplicates at the top (maybe Alacritty could warn about duplicates some day)
```
  - { key: Left,     mods: Alt,     chars: "\x1bb"                       }
  - { key: Right,    mods: Alt,     chars: "\x1bf"                       }
```
I can jump by word left and right, if I could now drag a file that would be perfect 😆 just a setting to always escape them would go all the way for me personally and I'd still just say for most others as well...

**Comment by chrisduerr** [comment]
I don't think always escaping is the way to go. Imho if you want to escape a path you can just enter `"`, drag the file and then type `"` again to complete it. That way the path is automatically escaped, but you can still have the path itself when trying to drag it into an editor for example.

It's way easier to add escapes than to remove them, so I'd personally rather not escape them at all and let the user handle that.

**Comment by chrisduerr** [comment]
Closing as wontfix, since it seems pretty much 50/50 on what is better depending on user's behavior. And there's no point to break Alacritty's current behavior for 50% of the users of this feature just to satisfy the other 50%.

**Comment by bukepo** [comment]
@chrisduerr  is it possible to provide a option for users? 50/50 on what is better doesn't mean the request is invalid, right?

**Comment by kroko** [comment]
Migrating from _iTerm_. Same as OP -> stumbled on _Alacritty_'s different behaviour than macOS default _Terminal_ as well as _iTerm_.

Here is patch https://gist.github.com/kroko/3a4e34a61798905bc8cb93c5fe9306b2 that turns

```sh
/path/with space and special-\()[]{}!?,;*|#$%&<>='`"-chars
```
to

```
/path/with\ space\ and\ special-\\\(\)\[\]\{\}\!\?\,\;\*\|\#\$\%\&\<\>\=\'\`\"-chars
```

After applying Alacritty behaves same as `Terminal.app` and `iTerm.app`.

@chrisduerr, first thank you for the the monstrous effort and great app, secondly

> Closing as wontfix

.. maybe opportunity to reconsider -> a config flag for turning this behaviour on/off 😄 🙇

**Comment by chrisduerr** [comment]
I don't think there's sufficient interest for an upstream config option.

**Comment by nixpulvis** [comment]
IIRC the current functionality is the best default since it's usually possible in a shell to simply start a qoute, drag-and-drop, then close the quote.

I did notice that there seems to be an extra space at the end of my file when I just tested this (I don't drag-and-drop files very often). Perhaps that's a small bug?

**Comment by kroko** [comment]
> I did notice that there seems to be an extra space at the end of my file when I just tested this (I don't drag-and-drop files very often). Perhaps that's a small bug?

it is [added intentionally](https://github.com/alacritty/alacritty/blob/48c088a50c977dfaf2a5a7052a5ddd39071e6063/alacritty/src/event.rs#L1796)

**Comment by nixpulvis** [comment]
Whelp, no idea why that's desired, but I'll leave it alone since I don't really use this I guess.
