### ISSUE TITLE
crazy long vtebench time on macbook 

### ISSUE THREAD

**Issue by ghost** [alacritty/alacritty#1348]
https://github.com/jwilm/alacritty/issues/1316#issuecomment-394123226

MacBook Pro 13 Touch, i7, Iris Pro 550 integrated graphics

**Comment by monouser7dig** [comment]
> Try changing this line to false:

used `cargo run --release`
```
> time cat out.vte
real    0m21,354s
user    0m0,007s
sys     0m0,974s
```

**Comment by chrisduerr** [comment]
Hmm yeah that didn't really change anything either. Maybe someone else has an idea.

**Comment by chrisduerr** [comment]
Since the author of this issue is gone and there has never been anyone able to reproduce it, there's not much point in keeping it open.
