### ISSUE TITLE
Suppress Extra Characters from Last Command

### ISSUE THREAD

**Issue by nixpulvis** [alacritty/alacritty#1377]
Which operating system does the issue occur on?
Linux

If on linux, are you using X11 or Wayland?
X11

It would be nice to suppress extra characters from being put into the input buffer for my shell after a previous command that printed a bunch of garbage. To see this issue, run something like `cat $(which ls)` to dump a bunch of garbage. Then notice how there is some of that garbage in the next input to the shell (i.e. pressing return would execute the garbage).

**Comment by chrisduerr** [comment]
I think this is a shell issue and not a terminal emulator problem. Or does this behave differently in another terminal? The example you've provided doesn't put anything in the next line for me.

**Comment by nixpulvis** [comment]
I've confirmed this happens in both `fish` and `bash`, and not at all in Termite. So this seems like a bug in Alacritty to me. I'm honestly kinda surprised there isn't an issue for this already, because I believe I've been seeing this for a while now.

Something I overlooked at first is that it's all the same character in the output:

```
[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c[?6c
```

Looking back on some older issues, seems like a recurrence of #72, but I'm not sure why yet.

**Comment by jwilm** [comment]
This looks like a terminal report bug

**Comment by nixpulvis** [comment]
Just for reference:

> http://www.kermitproject.org/vttest.html Section 6

**Comment by verdug0** [comment]
Another behaviour in the case of running `cat /dev/urandom` is that the font size reset to default.

**Comment by kchibisov** [comment]
The terminal responce rework multiple times a while ago. As well as C1 was removed. Should be fixed.
