### ISSUE TITLE
Is it possible to change how many characters can be selected for copy/paste?

### ISSUE THREAD

**Issue by knorwood** [alacritty/alacritty#1410]
When selecting text with my mouse, I'm able to select as many characters as I want, but only some actually get copied/pasted. It seems like I can only copy/paste ~766 characters. Is this configurable?

Which operating system does the issue occur on?
Mac OSX

**Comment by chrisduerr** [comment]
I don't think this is an Alacritty limitation and on Linux I'm able to copy 1000+ lines without any problem.

So there's no way to configure this in Alacritty, but potentially there's a macOS clipboard size limitation?

**Comment by jwilm** [comment]
Using OSC paste sequence will limit to ~1024 bytes. This is a hardcoded buffer size in `vte` crate.

**Comment by SCdF** [comment]
I could swear that this used to work. Did an underlying technology change cause this or am I just mistaken and it never worked?

**Comment by kchibisov** [comment]
Was fixed in 12e211d82a1bdef4ffe70c74ee62bc56edfa7590
