### ISSUE TITLE
In (n)vim, the cursor block only covers first half of wide character

### ISSUE THREAD

**Issue by yuanyelele** [alacritty/alacritty#1433]
neovim+alacritty
![1](https://user-images.githubusercontent.com/52266/42740518-4bfd6184-88db-11e8-9c5a-312b3092eea5.png)

neovim+termite
![2](https://user-images.githubusercontent.com/52266/42675331-217bd8d2-86a6-11e8-8978-46c18a309287.png)

**Comment by chrisduerr** [comment]
Hi, thanks for opening this issue. Something slightly related might be #697 where this was originally brought up.

Does this occur even without any vim configuration? Try running it using `vim -Nu NONE`, or `nvim -u`. Also just to clarify: Based on what I've said in #697 I'd assume (n)vim is the only place where this issue occurs, right?

**Comment by yuanyelele** [comment]
Adding `highlight Normal ctermbg=NONE` after `colorscheme` fixes the issue.
So this might be related to #1082 or #847?

**Comment by lo48576** [comment]
In neovim-0.3.1, `set cursorline` seems cause this problem.
With `set nocursorline`, the block cursor extends to double width as I expected in my environment.

**Comment by kchibisov** [comment]
This should work since 0.4.0 or maybe even earlier.
