### ISSUE TITLE
bring 24-bit (aka truecolor) support up to date

### ISSUE THREAD

**Issue by dnkl** [alacritty/alacritty#1485]
Alacritty implements 24-bit colors through a semicolon-separated escape sequence (38;2;...). However, the preferred escape sequence is now colon-separated, with an optional color space argument prefixing the rgb arguments.

This is perhaps best described in the comment for the parse_extended_colors() function in xterm-333/charproc.c:

Note that xterm actually supports *three* variants: semicolor-separated, colon-separated, and a mixed version. It's unclear to me why it supports the third variant.

> Some background -
> 
> Todd Larason provided the initial changes to support 256-colors in July 1999.
> I pointed out that the description of SGR 38/48 in ECMA-48 was vague, and
> was unsure if there would be some standard using those codes.  His response
> was that this was documented (it turns out, in equally vague terms) in ITU
> T.416
> 
> Discussing this with Todd Larason in mid-1999, my point was that given the
> high cost of obtaining ITU T.416 (ISO-8613-6), the standard was not going
> to be effective (more than $100 then, more than $200 in 2012)
> 
> We overlooked the detail about ":" as a subparameter delimiter (documented
> in 5.4.t2 in ECMA-48).  Some discussion in KDE in mid-2006 led Lars Doelle
> to discuss the issue with me.  Lars' initial concern dealt with the fact
> that a sequence such as
>  CSI 38 ; 5 ; 1 m
> violated the principle that SGR parameters could be used in any order.
> Further discussion (see KDE #107487) resolved that the standard expected
> that the sequence would look like
>  CSI 38 ; 5 : 1 m
> which still violates that principle, since the "5:1" parameter has to
> follow the "38" to be useful.
> 
> This function accepts either format (per request by Paul Leonerd Evans).
> It also accepts
>  CSI 38 : 5 : 1 m
> according to Lars' original assumption.  While implementing that, I added
> support for Konsole's interpretation of "CSI 38 : 2" as a 24-bit RGB value.
> ISO-8613-6 documents that as "direct color".
> 
> At the time in 2012, no one noticed (or commented) regarding ISO-8613-6's
> quirk in the description of direct color:  it mentions a color space
> identifier parameter which should follow the "2" (as parameter 1).  In the
> same section, ISO-8613-6 mentions a parameter 6 which can be ignored, as
> well as parameters 7 and 8.  Like parameter 1, parameters 7 and 8 are not
> defined clearly in the standard, and a close reading indicates they are
> optional, saying they "may be used".  This implementation ignores parameters
> 6 (and above), and provides for the color space identifier by checking the
> number of parameters:
>  3 after "2" (no color space identifier)
>  4 or more after "2" (color space identifier)
> 
> By the way - all of the parameters are decimal integers, and missing
> parameters represent a default value.  ISO-8613-6 is clear about that.

Furthermore, as of ncurses 6.1, the correct way to tell applications that the terminal supports 24-bit colors is by setting the terminfo setaf/setab capabilities. The Tc option is, as far as I can tell, obsolete. It is not used at all in any terminfo entries in ncurses 6.1.

The terminfo database provided with ncurses 6.1 defines a couple of "features" related to this: *xterm+direct*, *xterm+direct2* and *xterm+indirect*.

*indirect* corresponds to the escape sequence implemented by alacritty today, i.e. semicolon-separated.

*direct2* corresponds to the colon-separated version *without* the color space argument, and *direct* corresponds to the colon-separated version *with* the (optional) color space argument.

One can "use" these features to get the correct setaf/setab capabilities.

The alacritty.info file could/should be updated to use one of these definitions. As a first step, use the indirect version, and switch to the direct one if/when the colon-separated escape sequence is implemented.

FYI, I find the current alacritty.info to be a bit weird, in that it uses xterm-256color in the alacritty definition. If I set TERM to a non-256color entry, it's because _I don't want_ 256 colors...

I've been using the following replacement for some time now, with success. 24-bit support works in both vim and emacs.

```
alacritty| alacritty,
	use=xterm,

alacritty-256color| alacritty with 256 colors,
	use=xterm+256color, use=alacritty,

alacritty-direct| alacritty with direct-color indexing,
	use=xterm+indirect, use=alacritty,
```

**Comment by dnkl** [comment]
> The terminfo database provided with ncurses 6.1 defines a couple of "features" related to this: xterm+direct, xterm+direct2 and xterm+indirect.
Note the **+** instead of **-**. This convention is used to indicate a "feature" rather than a complete terminfo entry (like _xterm-direct_).

**Comment by dnkl** [comment]
Some more info can be found in the terminfo sources: http://www.invisible-island.net/ncurses/terminfo.src.html#tic-xterm_direct2

> # Emacs 26.1 and later support direct color mode in terminals, using a
> # combination of user-defined capabilities and ncurses-dependent function
> # calls.  We will not include that here.
> #
> # Here is a first revision, which (disregarding the reuse of colors 1-7 which
> # is of interest only to the numerically illiterate), is compatible with other
> # terminal descriptions written for curses.  It relies upon the extended range
> # for numeric capabilities provided in ncurses 6.1:
> xterm+direct2|xterm with direct-color indexing,

and

> # That in turn had a problem: in the original patch submitted for KDE konsole
> # in 2006, the submitter and the developer alike overlooked a "color space
> # identifier" parameter.  This version provides for that parameter:
> xterm+direct|xterm with direct-color indexing,

and

> # Meanwhile, in KDE #107487, the patch submitter and the developer both saw
> # that xterm's original implementation should have used colons for the
> # subparameter separators, but chose not to correct this in konsole.  As of
> # late 2017, konsole still accepts only the nonstandard semicolon delimiters.
> xterm+indirect|xterm with direct-color indexing (old),

**Comment by jwilm** [comment]
Wow, thank you for the incredibly detailed report here. The suggestions here sound like the right path forward (including terminfo changes). I think we can safely skip the mixed version of true color parsing, though.

**Comment by dnkl** [comment]
I noted that the current alacritty.info sets **rtim** and **sitm**. Other than that, it is identical to xterm. I have no idea which is more correct; keep them, or remove them.

I removed them in my replacement alacritty.info and haven't noticed any issues. But that doesn't mean it's the correct thing to do :)

If they aren't needed, then alacritty (and alacritty-256color) would be identical to xterm and xterm-256color. In this case, alacritty.info could be completely removed **after** the colon-separated 24-bit escape sequence has been implemented, since then you could use xterm-direct (but there is no xterm-indirect, hence the requirement of alacritty-direct for now).

**Comment by dnkl** [comment]
So, **sitm** is _enter italic mode_ and **ritm** is _leave italic mode_. I assume they are set to what they are because that's how urxvt does it?

I've read e.g. https://github.com/jwilm/alacritty/issues/1455 that brings up the xterm vs urxvt differences, and would just like to add that the terminfo is also affected by this; if alacritty aims to be urxvt compatible, the default TERM value should be urxvt, not xterm (or, the alacritty terminfo entry should be based on the urxvt one, not xterm).

**Comment by nixpulvis** [comment]
I wasn't aware of alacritty trying to always be urxvt compatible. See [this](https://github.com/jwilm/alacritty/pull/1351#issuecomment-395231088) comment I made on an unrelated issue.

**Comment by dnkl** [comment]
@nixpulvis I'm not sure what alacritty tries to be, and I hope it didn't sound like I was saying it is trying to be urxvt compatible.

I was merely trying to understand why alacritty.info was based off of xterm, but then defined ritm/sitm explicitly. Since I had seen urxvt being mentioned as _one_ terminal whose behavior alacritty's was compared to, I suggested that might be the reason.

What I _did_ do was check how urxvt defined it's ritm/sitm, and found that they matched alacritty's. Hence the above conclusion/suggestion.

What I **should** have done, was to _also_ check the xterm terminfo entry. If I had done that, I would have seen that it **also** sets ritm/sitm to the exact same values. Hence the explicit ritm/sitm in alacritty.info is unnecessary.

**Comment by jwilm** [comment]
> Hence the explicit ritm/sitm in alacritty.info is unnecessary.

Part of why we include them is that some older xterm.info entries don't include them. For instance, Ubuntu 14.04 didn't but 16.04 does.

**Comment by dnkl** [comment]
@jwilm ah, and that brings up backward compatibility; ncurses 6.1 is relatively new, and I guess some distros will take their time to get it. Making it difficult (maybe) to update alacritty.info to use e.g. xterm-indirect.

**Comment by jwilm** [comment]
@dnkl what do you think about having a complete terminfo definition for Alacritty that doesn't rely on system xterm terminfo entries?

**Comment by dnkl** [comment]
@jwilm I think that's a good idea. Even if you try to be xterm compatible, there's always going to be cases when you aren't. Using your own terminfo allows you to more easily compensate for that. 

Long answer:

Relying on the system's xterm terminfo entries means you don't really know what you're getting. A new ncurses release may bring in changes that are in conflict with alacritty's implementation, and you would probably not notice it.

Also, by using your own terminfo, you can more precisely describe alacritty. You could, in theory, make xterm incompatible changes and, assuming you update the terminfo data, still work. At least with well behaving applications.

You could probably connect the terminfo description to at least some of the key bindings and the escape sequences they generate. I.e. generate either one of them from the other.

Looking at other projects, there appear to be different views on what's "correct".

The konsole maintainer has stated (https://bugs.kde.org/show_bug.cgi?id=145977) that he prefers users to set `TERM=xterm(-256color)`, because he wants konsole to be 100% xterm compatible, and if something doesn't work the same way, it's a konsole bug.

Both st and urxvt on the other hand, have their own (complete) terminfo definitions.

I think the advantages of **not** relying on (unknown) system definitions outweigh any potential downsides. At least initially, I would model the definition after xterm's; split it up into the same "features" and combine them into the final `alacritty` definition in the same way xterm's terminfo is done.

That way, it's fairly easy to pull in "upstream" changes from new ncurses releases, should it be necessary (I'm thinking for example bug fixes to terminfo definitions).

**Comment by dnkl** [comment]
@chrisduerr I could try to clone the xterm definitions from ncurses 6.1.

Basically, create the terminfo I mentioned in the issue description, but standalone. Then we can take it from there.

Perhaps this (creating a custom/standalone terminfo) should be tracked separately?

**Comment by chrisduerr** [comment]
Yeah that's probably a good idea!

**Comment by dnkl** [comment]
Unless someone else has already started working on this, I might take a stab at it after finishing #1491.

I've never done anything in rust before, but this looks like a fairly easy thing to implement.

**Comment by chrisduerr** [comment]
@dnkl If you have any questions, feel free to ask either on github or in the #alacritty IRC on freenode! Always happy to help out.

**Comment by jwilm** [comment]
I agree that `vte` needs to be updated. Route b) seems preferable right now. This distinction will hopefully go away at some point when most of `ansi.rs` moves into the `vte` crate.

**Comment by starkovv** [comment]
When I run vim it says:
```
vim ~/.tmux.conf

E558: Terminal entry not found in terminfo
'tmux-256color' not known. Available builtin terminals are:
    builtin_amiga
    builtin_beos-ansi
    builtin_ansi
    builtin_pcansi
    builtin_win32
    builtin_vt320
    builtin_vt52
    builtin_xterm
    builtin_iris-ansi
    builtin_debug
    builtin_dumb
defaulting to 'ansi'
```

**Comment by jwilm** [comment]
@starkovv you're missing a terminfo definition for tmux-256color. This is not related to Alacritty.

**Comment by starkovv** [comment]
OK. I fixed that issue about 'tmux-256color'.

Could you guide me what diagnosis information should I collect to make this issue with true color to be able to resolve?

**Comment by starkovv** [comment]
@jwilm could you show me direction to further research on the subject? Thanks.

**Comment by chrisduerr** [comment]
@starkovv With the `alacritty-direct` terminfo file, Alacritty already provides full truecolor support.

This issue is just about an alternative way to specify the truecolor format, which would require changes to the `ansi.rs` file.
