### ISSUE TITLE
influx shell flashes constantly

### ISSUE THREAD

**Issue by jwilm** [alacritty/alacritty#1490]
For whatever reason, this application causes frequent draws with partial state. Every key stroke seems to clear the current line, draw, and then draw the line including the new character. `influx` should do a better job at batching writes, but this is also on us to do a better job about giving a grace period before drawing.

**Comment by pwnorbitals** [comment]
Interesting, is this still the case on latest releases @jwilm ?

**Comment by chrisduerr** [comment]
This is actually a duplicate of https://github.com/alacritty/alacritty/issues/598.
