### ISSUE TITLE
Add support for audio bell

### ISSUE THREAD

**Issue by Yavor-Ivanov** [alacritty/alacritty#1528]
Which operating system does the issue occur on?
macOS High Sierra v10.13.6

I don't get any audio notification for the terminal bell. The config file has options for `visual_bell`, but that's of no help when I'm looking at other fullscreen windows.

For the time being, I've worked around the problem using tmux:
```tmux
# Some hacks for OSX Alacritty audio bell
set -g monitor-bell on
set -g bell-action other
set-hook -g alert-bell 'run-shell "afplay /System/Library/Sounds/Funk.aiff"'
```

Does Alacritty not provide an audio bell? If not, is the feature planned or out of scope?

**Comment by chrisduerr** [comment]
Currently Alacritty does not provide any audio bell and it's not planned to add this in the near future. 

Judging if this is within scope or not is always tough since it might change based on demand (see scrollback which was initially not planned). However there already are a few issues which are related to this issue (see #1170 and #1072). Especially with #1072 I can see Alacritty supporting it in the future.

**Comment by Yavor-Ivanov** [comment]
Thanks for the swift reply! I can live with notifications via tmux, just wanted to make sure I'm not missing anything :-)

**Comment by jwilm** [comment]
I like @Celti's suggestion

**Comment by HendrikPetertje** [comment]
I've included the bit of code from the top (playing a sound, even emiting a shell script to light up a small led-light on my desk just to test if an error was raised in tmux). while in iterm the sound sounds and the led on my desk flashes on. Alacritty seems to not even trigger the alert-bell hook in tmux. 
This is on a mac Mojavee, using the latest version of tmux

**Comment by vktec** [comment]
Interestingly, I came across this issue while using alacritty on Windows and wondering how to *disable* the audible bell. It's the default notification sound, and I was guessing it was generated by alacritty, but reading this it seems like it's probably coming from elsewhere. I'm using WSL bash. Any suggestions?

**Comment by vktec** [comment]
Hmm... looks like the bell signal isn't even getting through to alacritty, since visual bell isn't working. It's probably being intercepted by WSL.

**Comment by mqudsi** [comment]
I definitely don't get any audible bell under WSL.

**Comment by vityafx** [comment]
I am not sure this is the rightmost place to ask this, but I want to know if it is possible now to bind a sound to be played whenever user input is requested (for example, whenever a bunch of long-running commands finish and so the user is indicated of that)? Or should it be a shell's feature instead?

**Comment by kchibisov** [comment]
Your shell can send `\a` after command is done (you can set it yourself in shell, it should provide hooks) and if you setup bell command in alacritty you'll get audio bell. if you want audio only in that particular case you can may do that entirely in shell.

**Comment by vityafx** [comment]
> Your shell can send `\a` after command is done (you can set it yourself in shell, it should provide hooks) and if you setup bell command in alacritty you'll get audio bell. if you want audio only in that particular case you can may do that entirely in shell.

Thanks, I'll try :)

**Comment by francescoferraioli** [comment]
This worked for me on MacOS:
```
bell:
  command:
    program: osascript
    args: ["-e", "beep"]
```

**Comment by NovaViper** [comment]
What bell program do we use for ArchLinux? I can't find the `xkbbell` package that @Celti mentions is no longer there and I can't find any other bell program that I can use. The bell works on every other terminal but this one so I'm just confused.

**Comment by Celti** [comment]
On Arch, `xkbbell` is currently in `xorg-xkbutils`.

**Comment by NovaViper** [comment]
Thanks, man! It worked perfectly 👍🏾

**Comment by NovaViper** [comment]
Thanks! Got it working now

**Comment by strafe** [comment]
@francescoferraioli is this solution still working for you?

```toml
[bell]
command = { program = "osascript", args = ["-e", "bell"] }
```
is not working for me currently.

**Comment by francescoferraioli** [comment]
> @francescoferraioli is this solution still working for you?
> 
> 
> 
> ```toml
> 
> [bell]
> 
> command = { program = "osascript", args = ["-e", "bell"] }
> 
> ```
> 
> is not working for me currently.

Sorry, I've changed company since then and am no longer using a Mac so I'm not sure if it still works or not.

**Comment by strafe** [comment]
> It should be `beep` rather than `bell` (tested on MacOS Ventura 13.4):

Good spot, thank you! Not sure how I missed that but it's definitely working as expected now 🙂

**Comment by aptdnfapt** [comment]
```
[bell]
command = { program = "paplay", args = ["/usr/share/sounds/freedesktop/stereo/dialog-information.oga"] }
```
