### ISSUE TITLE
The geometry of the terminal does not match the dimensions configuration

### ISSUE THREAD

**Issue by gnuvince** [alacritty/alacritty#1546]
In Alacritty v0.2.0, with a clean `alacritty.yml`, when I open a terminal window, instead of being 80x24 as configured, it opens with a geometry of 47x14 instead.

```
~$ rg 'columns:|lines:' .config/alacritty/alacritty.yml
22:    columns: 80
23:    lines: 24
~$ tput lines
14
~$ tput cols
47
``` 

Which operating system does the issue occur on?

Debian unstable

If on linux, are you using X11 or Wayland?

X11.  Here is my Xft configuration (in `.Xdefaults`):
```
Xft.autohint: 0
Xft.antialias: 1
Xft.hinting: true
Xft.hintstyle: hintslight
Xft.dpi: 96
Xft.rgba: rgb
Xft.lcdfilter: lcddefault
```

**Comment by chrisduerr** [comment]
Does the #1403 PR solve this issue? There have been a few changes with DPI recently so current master doesn't do everything 100% correctly.

The glutin update PR should solve all these issues though.

**Comment by gnuvince** [comment]
It appears to, yes.

**Comment by chrisduerr** [comment]
I thought we already had another issue about this, but it doesn't look like there's anything explicitly just talking about window dimensions.

So using this to track the problem, it should be automatically resolved once the PR hits master!

**Comment by ohazi** [comment]
Same issue? https://github.com/jwilm/alacritty/issues/952
