### ISSUE TITLE
FreeBSD 11.2/X11/Rust-1.27.1: Mouse Wheel scrolled down by 1 unit, but tmux recived 2

### ISSUE THREAD

**Issue by NeoChen1024** [alacritty/alacritty#1558]
Before scroll down:
![1537278974](https://user-images.githubusercontent.com/25676597/45692585-bb2ef600-bb8d-11e8-85a3-287002804771.png)
After scroll down:
![1537278978](https://user-images.githubusercontent.com/25676597/45692606-c550f480-bb8d-11e8-9001-8f7a363ef9fd.png)
Build with:
        nice -n 20 cargo  build --release -j 4 -vv
Executable:
[alacritty.gz](https://github.com/jwilm/alacritty/files/2392961/alacritty.gz)

**Comment by chrisduerr** [comment]
Do you have faux scrolling disabled? With tmux that can lead to some unexpected behavior.

**Comment by NeoChen1024** [comment]
No, I disabled it, but still happend

**Comment by chrisduerr** [comment]
By default scrolling is setup to scroll three lines at a time. Have you changed that?
https://github.com/jwilm/alacritty/blob/master/alacritty.yml#L43

**Comment by NeoChen1024** [comment]
Already disabled that (set to 0)

**Comment by chrisduerr** [comment]
If you want to disable scrolling, you should make use of the `scrolling.history` setting, instead of setting the number of lines to scroll to 0.

Could you provide a log with `alacritty --print-events`? This should show how many keys are actually received by Alacritty.

**Comment by NeoChen1024** [comment]
Config:
[alacritty.yml.gz](https://github.com/jwilm/alacritty/files/2431504/alacritty.yml.gz)

**Comment by chrisduerr** [comment]
Huh, if you look at that log, you can see that there's actually 6 `MouseWheel` events. So from Alacritty's perspective, it's doing everything right.

Now there's two options. Either Alacritty is doing everything right because your system is sending multiple scroll events, or there's a bug in Alacritty's window library `winit`.

Which one of these it is should be pretty simple to test by using a different terminal emulator like urxvt to check if it has the same issue. If it does not, please let me know and I'll open an issue upstream about this.

**Comment by NeoChen1024** [comment]
I am using urxvt for daily usage, but on urxvt it's working without problem, so there may be a bug in winit

**Comment by chrisduerr** [comment]
Would you mind testing it with the #1403 PR, so we don't have to report an issue which has already been resolved?

**Comment by NeoChen1024** [comment]
Of course, as soon as I get home, I will do this

**Comment by chrisduerr** [comment]
Please see https://github.com/jwilm/alacritty/issues/929 for similar issue.

I'd recommend first cleaning all cargo caches and then maybe trying stable (or if you're using stable, nightly).

**Comment by chrisduerr** [comment]
Since there has been no responses since 2018 and the configuration options in question have been reworked. I'd assume that nobody has run into this issue anymore.
