### ISSUE TITLE
Failed to open input method

### ISSUE THREAD

**Issue by skariel** [alacritty/alacritty#1574]
Which operating system does the issue occur on? Ubuntu 18.04

If on linux, are you using X11 or Wayland? X11

the error:

```
RUST_BACKTRACE=1 alacritty
thread 'main' panicked at 'Failed to open input method: PotentialInputMethods {
    xmodifiers: None,
    fallbacks: [
        PotentialInputMethod {
            name: "@im=local",
            successful: Some(
                false
            )
        },
        PotentialInputMethod {
            name: "@im=",
            successful: Some(
                false
            )
        }
    ],
    _xim_servers: Err(
        GetPropertyError(
            TypeMismatch(
                0
            )
        )
    )
}', /home/skariel/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.15.1/src/platform/linux/x11/mod.rs:90:17
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: __libc_start_main
  10: <unknown>

```

**Comment by chrisduerr** [comment]
Probably best to report this upstream with winit/glutin. I don't think there's anything Alacritty can do about this.

However would you mind giving the #1403 PR a shot first? It's a big glutin/winit version jump, so it's possible that this resolves the issue.

**Comment by francesca64** [comment]
This looks like it could be the same as tomaka/winit#636

**Comment by chrisduerr** [comment]
Thanks for keeping use updated. Looks like that might be related.

**Comment by konstantinfickel** [comment]
At my setup this error was caused by setting `/etc/locale.conf` to an invalid language that was activated inside `/etc/locale.gen` on Arch.
After fixing this, it works fine.

**Comment by korayal** [comment]
I started getting this error right after some package upgrades a few days ago. At the same time I lost my DPI scaling in the environment. So I suspect that it's related. I have Ubuntu LTS 18.04.1 on X11. Btw, I have another computer with the same OS but different graphics card, and I don't have this error there right now.

**Comment by AregevDev** [comment]
Having the same issue on LM19 tara, any fix?

**Comment by happysmash27** [comment]
Having the same issue on Gentoo Linux as well; any fix?

**Comment by happysmash27** [comment]
Hmm, it seems I need to change my locale to C for it to work...

**Comment by happysmash27** [comment]
Okay, it seems that it specifically doesn't like my language `eo.utf8`, but works fine on simply `eo`.

**Comment by saks** [comment]
I'm also running Ubuntu 18.04 on X11 and having the same issue.
Later I found that my `/etc/default/locale` was:
```
LANG="en_HK.UTF-8"
LANGUAGE="en_HK:en"
```
After changing to:
```
LANG="en_CA.UTF-8"
LANGUAGE="en_CA:en"
```
problem was fixed.

**Comment by pdrd** [comment]
Noticed the same behavior on manjaro 18.0.4 with x11 and actual 0.3.3 alacritty installed via manjaro repositories.

Fixed it by moving the binary file to a different path `/opt/alacritty/alacritty` and creating a shell script under `/usr/bin/alacritty`, which simply sets the language without the `.UTF-8`-ending, as suggested by @happysmash27 :

```bash
#!/bin/bash

LANG=en_dk /opt/alacritty/alacritty $@
```
*$@ expands to the script arguments*

My quick test to verify a still utf-8 compatible terminal was to create a `utf8.txt` file with some utf-8-only chars:

```text
äöüß!"'§$%&/()=?°^,.-;:_<>€ƒ†…‡ˆ‰Š‹Œ•—™¶Ø
```

Running `cat utf8.txt` correctly displayed all chars in alacritty and everything else seems to work normally.

After launching alacritty it is possible to export the original LANG value with `.UTF-8`-ending, to ensure compatibility with other programs, f.e. by modifying the `.bashrc`.
