### ISSUE TITLE
Use a vte parser to filter escapes in bracketed-paste mode

### ISSUE THREAD

**Issue by jwilm** [alacritty/alacritty#1575]
This is follow-up from #1243

**Comment by chrisduerr** [comment]
Considering how brackted paste mode works, this shouldn't be necessary. Our only job is to filter the bracketed paste end escape and replacing `\x1b` is a perfectly fine choice for that. We do not need to filter out every escape or hide the escapes inside the pasted text. In fact it's probably better when we do not hide them so the user can identify the issue and prevent malicious text from entering their clipboard in the future.
