### ISSUE TITLE
Seemingly unrelated logs dumped in Vim

### ISSUE THREAD

**Issue by MrYakobo** [alacritty/alacritty#1594]
This has occurred for some times now. Whilst editing a file in Vim, there are messages from Firefox's Gecko_IOThread appearing. See image below

![](https://user-images.githubusercontent.com/11942597/46136311-98fd3e00-c247-11e8-9ebb-15636ffd97cd.png)

Arch Linux

X11

**Comment by chrisduerr** [comment]
Are you starting Firefox from the same terminal emulator you're using for vim?

**Comment by MrYakobo** [comment]
No

**Comment by jwilm** [comment]
It seems like Firefox must be running as a backgrounded job. Can you share the output of `jobs`?

**Comment by MrYakobo** [comment]
```
$ jobs
jobs: There are no jobs
```

**Comment by jwilm** [comment]
It comes to mind that there could be externalities affecting the output of `jobs`. I would ask that you confirm:

1. `jobs` was run in a terminal experiencing the issue
2. `jobs` was run immediately after experiencing the issue and without manipulating other windows such as closing Firefox window or tab.

**Comment by MrYakobo** [comment]
Ok, will try that when it appears again. :+1:

**Comment by MrYakobo** [comment]
Yo. I've not seen this issue since I posted it. Perhaps it's fixed now.
