### ISSUE TITLE
Feature request: undercurl support

### ISSUE THREAD

**Issue by petobens** [alacritty/alacritty#1628]
As per this [comment](https://github.com/jwilm/alacritty/pull/1078#issuecomment-426444304).

**Comment by nixpulvis** [comment]
I believe this is the relevant spec: https://sw.kovidgoyal.net/kitty/protocol-extensions.html#colored-and-styled-underlines

**Comment by bluz71** [comment]
Hello Alacritty team,

I thought it might be handy to expand this item with some pertinent details.

Proper *undercurl* support actually involves two feature enhancements; those being: rendering actual undercurls, and secondly colouring underlines & undercurls separately from the character they sit beneath.

kitty I believe was the first terminal to get the ball rolling, with the relevant spec listed by @nixpulvis above.

- GNOME Terminal, and other [VTE](https://gitlab.gnome.org/GNOME/vte)-based terminals, added support for coloured undercurls a couple years back via [bug 721761](https://bugzilla.gnome.org/show_bug.cgi?id=721761).

- Vim added support for undercurls [here](https://github.com/vim/vim/issues/1306).

- Neovim added support for undercurls [here](https://github.com/neovim/neovim/pull/9052).

- [tmux](https://github.com/tmux/tmux) staged the introduction of undercurls, first via just undercurls in version 3.0 and then coloured undercurls & underlines in 3.1. tmux [#1492](https://github.com/tmux/tmux/issues/1492) is the relevant issue. Note, plain undercurls require `set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'` in `tmux.conf` and coloured underlines & undercurls also require `set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'`.

- [mintty](https://github.com/mintty/mintty) it appears also supports coloured undercurls which they note in their [text attributes and rendering](https://github.com/mintty/mintty/wiki/Tips#text-attributes-and-rendering) documentation; [this discussion](https://github.com/kovidgoyal/kitty/issues/226#issuecomment-381665023) may also be of interest.

- Lastly, iTerm2 is currently working on undercurls and coloured undercurls. Not released yet, and only non-coloured undercurls are working in the beta-release as noted in their issue [#6382](https://gitlab.com/gnachman/iterm2/-/issues/6382). As noted in that issue, the terminfos provided on Mac are not as up-to-date as on Linux, so users on Mac likely need to fiddle terminfo databases.

Is it worth the effort?

Yes, I believe so. I would not classify this as urgent (it isn't). But it sure would be nice to have. Alacritty has already implemented a first very important step, that being to render underlines itself. The next logical steps, once time and man-power permits, is to extend that to undercurls and then coloured underlines & undercurls.

Here is an example of coloured undercurls running in GNOME Terminal + tmux + Neovim doing spell check highlighting via undercurls:

![undercurl](https://user-images.githubusercontent.com/11382509/88470712-33f9f880-cf43-11ea-9bc8-553ccd446614.png)

Best regards.

**Comment by martsa1** [comment]
I just stumbled into this missing feature, is there any kind of ETA on this?

**Comment by kchibisov** [comment]
I'm not sure about ETA, but I'd probably work on this one soon™.
