### ISSUE TITLE
support DefaultDepth 30

### ISSUE THREAD

**Issue by 257** [alacritty/alacritty#1641]
Which operating system does the issue occur on?
linux

If on linux, are you using X11 or Wayland?
X11

**Comment by jwilm** [comment]
Please provide some background on this feature request. What is DefaultDepth 30? What is expected vs actual behavior today?

**Comment by 257** [comment]
https://us.download.nvidia.com/XFree86/Linux-x86/173.14.12/README/chapter-28.html

**Comment by 257** [comment]
it's an xorg.conf setting to enable 30bits colour. this is what i get with DefaultDepth set to 30
```
Alacritty encountered an unrecoverable error:

        Error creating GL context; Couldn't find any pixel format that matches the criterias.
```

**Comment by 257** [comment]
please reopen.

**Comment by 257** [comment]
any test script? i see ```examples/``` directory there, not sure how to use it.

**Comment by chrisduerr** [comment]
You can run examples by simply using `cargo run --example <example_name>`. Any of these examples should probably do, but I'd recommend just running `cargo run --example window`.

**Comment by 257** [comment]
https://gist.github.com/0fdc04c10de2e8b29f013a6fea631011

**Comment by kchibisov** [comment]
We support 10bit.
