### ISSUE TITLE
Support for SGRs 51, 52, and 53

### ISSUE THREAD

**Issue by moonheart08** [alacritty/alacritty#1647]
51, 52, and 53, referred to as Framed, Encircled, and Overlined, are less commonly used ANSI SGR codes, but implementing them would be a potentially useful thing for allowing users to enhance their experience.

**Comment by chrisduerr** [comment]
This is mentioned here:
http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-048.pdf (page 76 or `- 62 -`)

However, it does not look like this is supported in XTerm. Are you aware of any terminal emulator which already supports this? Or an application which makes use of it? To evaluate the priority of this issue that would probably help put it into perspective a bit.

**Comment by moonheart08** [comment]
Priority is very low. Nothing I know of uses it, however I personally wish to use this feature should I find a terminal emulator that supports it. May try and do this myself, but no promises.

**Comment by chrisduerr** [comment]
While I think that Encircled would be quite difficult to add (there's no functionality to render curves), the PR for proper underline support (#1078) does introduce a function to render horizontal lines.

I'd expect that Overlined would be super simple after that PR is landed and Framed could probably be supported with a bit of additional effort.

It does however seem unlikely that this is going to be added in the near future unless you want to take a look at it yourself. However I'm happy to help you if you want to take a stab at it yourself. As mentioned earlier waiting for #1078 to land would probably make sense though.

**Comment by chrisduerr** [comment]
I don't think adding this provides any value unless it's commonly supported and used. So if people aren't using this anymore, I'd say good riddance.
