### ISSUE TITLE
Support for modifier + click bindings

### ISSUE THREAD

**Issue by jussi-kalliokoski** [alacritty/alacritty#1654]
It would be cool to have a way to write mouse bindings the same way as key bindings, for example to rewrite cmd + clicks to be sent to be sent as `<mouse_click_escape_codes>gD` for cmd+click go to definition in vim.

**Comment by chrisduerr** [comment]
I'm not quite sure what you mean by this, would you mind going into more detail?

It is already possible to specify modifiers for click bindings.

**Comment by jussi-kalliokoski** [comment]
> I'm not quite sure what you mean by this, would you mind going into more detail?

Sure!

> It is already possible to specify modifiers for click bindings.

Yes! But unless I'm missing something, support for what I'm proposing is missing. So:

Some applications like vim and tmux have support for basic mouse actions, such as clicking on a tab to activate it. However, afaict the xterm mouse bindings don't enable you to discern mouse actions with modifiers. It would be great if for example you could cmd+click **on a variable** in vim and jump to the definition of that variable, like you can do in editors like vscode. So, what I'm proposing is the support for being able to define something like this (not with this syntax in particular, but I hope you get the gist):

```
- { mouse: Left, mods: Command, chars: "<mouse_action>gD" }
```

So that when you click on the screen, the application will first receive the escape codes for that row:col being clicked, followed by the `gD` keys being pressed.

**Comment by chrisduerr** [comment]
I'm pretty sure that it's already possible to get modifiers with mouse events from inside the application, it's just not part of the `xterm-256color` terminfo file.

IIRC the `kakoune` editor supports this, I'm not sure if our current `alacritty` terminfo has the required terminfo definitions, but it would probably be possible to add them.

**Comment by chrisduerr** [comment]
I'm not sure if an issue like that is present. I'd propose using this issue if there is none.

However I'd first have to investigate the behavior of kakoune myself again, to make sure that this doesn't work already.

**Comment by chrisduerr** [comment]
Here are some relevant issues/PRs discussing this already:
https://github.com/jwilm/alacritty/issues/1145
https://github.com/jwilm/alacritty/pull/1057

**Comment by kchibisov** [comment]
@chrisduerr could you recheck whether this issue is still relevant.

**Comment by chrisduerr** [comment]
It's not, this doesn't make much sense and should just be implemented by the application.
