### ISSUE TITLE
Alacritty does not report desired window (re)size

### ISSUE THREAD

**Issue by mitchellwrosen** [alacritty/alacritty#1702]
Hello! Using a tiling window manager, I've found that my "fixed column" layout does not work properly. I did enough printf-debugging, comparing to `urxvt`, to discover that some X11 calls involving [size hints](https://tronche.com/gui/x/xlib/ICC/client-to-window-manager/wm-normal-hints.html) are not returning any useful information in alacritty.

Does this make sense? Please let me know if I've provided enough information, I'm happy to keep drilling.

> Which operating system does the issue occur on?

Arch linux

> If on linux, are you using X11 or Wayland?

X11

**Comment by chrisduerr** [comment]
Which window manager are you using specifically? In general Alacritty should work just fine with tiling window managers.

**Comment by mitchellwrosen** [comment]
I'm using xmonad. It does work, but _not_ for the fixed column layout, which queries the application for how wide a "column" should be (which, for a terminal, depends on the font size).

**Comment by chrisduerr** [comment]
The problem I see with this is that Alacritty doesn't actually take care of the window itself, so it's required that the library we use makes setting this possible.

It sounds like an extremely specific thing though, so that might take some time before someone can take a look at it. I'm also not certain how exactly this works in xmonad, does each Application get the size it requests or is this a minimum size requirement?

**Comment by mitchellwrosen** [comment]
I'm not exactly sure myself, here is the relevant code from [xmonad-contrib](https://hackage.haskell.org/package/xmonad-contrib-0.15/docs/XMonad-Layout-FixedColumn.html):

```haskell
-- | Determine the width of @w@ given that we would like it to be @n@
--   columns wide, using @inc@ as a resize increment for windows that
--   don't have one
widthCols :: Int -> Int -> Window -> X Int
widthCols inc n w = withDisplay $ \d -> io $ do
    sh <- getWMNormalHints d w
    bw <- fmap (fromIntegral . wa_border_width) $ getWindowAttributes d w
    let widthHint f = f sh >>= return . fromIntegral . fst
        oneCol      = fromMaybe inc $ widthHint sh_resize_inc
        base        = fromMaybe 0 $ widthHint sh_base_size
    return $ 2 * bw + base + n * oneCol
```

So we call `getWMNormalHints`, which returns a `SizeHints`:

```haskell
data SizeHints = SizeHints
                   { sh_min_size     :: Maybe (Dimension, Dimension)
                   , sh_max_size     :: Maybe (Dimension, Dimension)
                   , sh_resize_inc   :: Maybe (Dimension, Dimension)
                   , sh_aspect       :: Maybe ((Dimension, Dimension), (Dimension, Dimension))
                   , sh_base_size    :: Maybe (Dimension, Dimension)
                   , sh_win_gravity  :: Maybe (BitGravity)
                   }
```

with `sh_resize_inc` and `sh_base_size` fields.

**Comment by mitchellwrosen** [comment]
Here's the hints I get when opening an `alacritty` terminal:

```
SizeHints {
  sh_min_size = Nothing, 
  sh_max_size = Nothing, 
  sh_resize_inc = Nothing, 
  sh_aspect = Nothing, 
  sh_base_size = Nothing, 
  sh_win_gravity = Nothing
}
```

and `urxvt`:

```
SizeHints {
  sh_min_size = Just (20,32), 
  sh_max_size = Nothing, 
  sh_resize_inc = Just (12,24), 
  sh_aspect = Nothing, 
  sh_base_size = Just (8,8), 
  sh_win_gravity = Just 1
}
```

**Comment by intrntbrn** [comment]
I've wrote a small script to work around this issue: [resize-increment.c](https://gist.github.com/intrntbrn/99bccdc6b06b47b8b44c12908b13b6ac). It will manually set the `WM_NORMAL_HINTS` X property, so your wm can resize accordingly. 

All you have to do is to call it for every `alacritty` instance with your desired cell size, e.g.: 
`resize-increment 123456 6 12` where 123456 is X window ID of your alacritty instance .

It works properly in `awesomewm`: 
```
client.connect_signal("request::tag", function(c)
    if c.class == "Alacritty" then
        awful.spawn.with_shell("~/.bin/resize-increment " .. c.window .. " 6 12")
    end
end)
```

**Comment by kchibisov** [comment]
increments are supported for a while.
