### ISSUE TITLE
Unable to load Info.plist exceptions (eGPUOverrides)

### ISSUE THREAD

**Issue by lucazz** [alacritty/alacritty#1752]
Which operating system does the issue occur on?
macOS Mojave 10.14.1 (18B75)

Heya everyone, first of: What an awesome piece of software Alacritty is!

I'm having a little bit of a weird problem while trying to run it on a fresh macOS install
When I open the app, it closes before it draws anything on the screen with the following error msg:

```
default	22:42:57.406584 -0300	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Applications/Alacritty.app/Contents/, NSFilePath=/Applications/Alacritty.app/Contents/PlugIns, NSUnderlyingError=0x7f956e237390 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
default	22:42:57.438087 -0300	loginwindow	-[PersistentAppsSupport applicationReady:] | App: Alacritty, ready, updating active tracking timer
default	22:42:57.438291 -0300	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : Alacritty
default	22:42:57.487968 -0300	launchservicesd	CHECKIN:0x0-0x76076 2990 io.alacritty
default	22:42:57.493095 -0300	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : Alacritty
default	22:42:57.502320 -0300	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier io.alacritty, type: 0: 0x7f8cadf3c540 at /Applications/Alacritty.app
default	22:42:57.594445 -0300	alacritty	Current system appearance, (HLTB: 2), (SLS: 1)
default	22:42:57.600177 -0300	alacritty	Post-registration system appearance: (HLTB: 2)
error	22:42:57.614061 -0300	alacritty	Unable to load Info.plist exceptions (eGPUOverrides)
default	22:42:57.631465 -0300	alacritty	NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 0
-appearance: (null)
-effectiveAppearance: <NSCompositeAppearance: 0x600001744a00
 (
    "<NSDarkAquaAppearance: 0x60000215c9c0>",
    "<NSDarkAquaAppearance: 0x60000215c040>",
    "<NSSystemAppearance: 0x60000215c440>"
)>
default	22:42:57.794216 -0300	loginwindow	-[PersistentAppsSupport applicationQuit:] | for app:Alacritty, _appTrackingState = 2
default	22:42:57.794243 -0300	loginwindow	-[PersistentAppsSupport applicationQuit:] | App: Alacritty, quit, updating active tracking timer
```

I'm building Alacritty by checking out the master branch and using the `Make app` command;
But the issue persists even if I try and use a binary that was sitting on my old Mac or if I download it via the releases section. 

What am I missing here? 

Cheers!

**Comment by chrisduerr** [comment]
I don't think I've seen this error before. Is there anything special about your setup, or is this just a normal stock macOS laptop? Something like an external GPU connected?

Also I'm not sure to which extend graphical drivers and APIs are preinstalled on macOS, but making sure that everything is properly working and up to date is probably a good idea.

**Comment by lucazz** [comment]
Just a plain MacBookPro14,1 w/ an Intel Iris Plus Graphics 640 1536 MB
```
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro14,1
  Processor Name:	Intel Core i7
  Processor Speed:	2.5 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Memory:	16 GB
```

**Comment by lucazz** [comment]
No eGPU's
I do have an OWC 13 Port Thunderbolt 3 Dock and two 4K displays, but this happens regardless of whether I'm plugged in or not.

**Comment by jwilm** [comment]
Some more info here: https://forum.openframeworks.cc/t/unable-to-load-info-plist-exceptions-egpuoverrides/30553

Sounds like a Mojave bug.

**Comment by jlastofka** [comment]
I get the same kind of plist eGPU error, and I'm finding a lot of talk about it on the web but it all looks like different circumstances. In my case the program (Cocoa app) runs and the buttons and text fields work, but I'm trying to download a simple text webpage and it fails. My code's copy/pasted from a program I have doing the same operation in a console app. The console app works fine and gets the page. Trying it in a cocoa app makes the download attempt fail after three automatic tries at the system (not my code) level. Something about calling the function from the view controller?? I'll paste my error messages below in case someone sees a clue.  2015 Mac Mini, all software up to date as of 21 Nov 2018

2018-11-21 17:07:32.168651-0800 Deer Springs Rain Report 2[76162:15880792] [default] Unable to load Info.plist exceptions (eGPUOverrides)

https://www.wrh.noaa.gov/sgx/data/hydro/LAXRRMSAN

2018-11-21 17:07:37.033874-0800 Deer Springs Rain Report 2[76162:15880836] dnssd_clientstub ConnectToServer: connect()-> No of tries: 1

2018-11-21 17:07:38.038993-0800 Deer Springs Rain Report 2[76162:15880836] dnssd_clientstub ConnectToServer: connect()-> No of tries: 2

2018-11-21 17:07:39.043310-0800 Deer Springs Rain Report 2[76162:15880836] dnssd_clientstub ConnectToServer: connect()-> No of tries: 3

2018-11-21 17:07:40.047814-0800 Deer Springs Rain Report 2[76162:15880836] dnssd_clientstub ConnectToServer: connect() failed path:/var/run/mDNSResponder Socket:12 Err:-1 Errno:1 Operation not permitted

2018-11-21 17:07:40.048101-0800 Deer Springs Rain Report 2[76162:15880836] [] nw_resolver_create_dns_service_locked [C1] DNSServiceCreateDelegateConnection failed: ServiceNotRunning(-65563)

2018-11-21 17:07:40.048431-0800 Deer Springs Rain Report 2[76162:15880836] TIC TCP Conn Failed [1:0x60000370b300]: 10:-72000 Err(-65563)

2018-11-21 17:07:40.048936-0800 Deer Springs Rain Report 2[76162:15880824] Task <72A01401-7DCC-425E-B7ED-D56DDD799D0D>.<0> HTTP load failed (error code: -1003 [10:-72000])

2018-11-21 17:07:40.049037-0800 Deer Springs Rain Report 2[76162:15880824] NSURLConnection finished with error - code -1003

**Comment by jlastofka** [comment]
As a further test, I tried this in Xcode 9 also, with the same result. I saw a lot of people thinking the plist eGPU error problem was related to Xcode 9 and OSMojave. I get the same error with Xcode 9.

**Comment by jzajpt** [comment]
I have been getting the plist eGPU error too under non-admin account on OSX. On my main admin account, everything works fine.

**Comment by JamesVorder** [comment]
I'm encountering this same issue after packaging a Tkinter app using py2app. The app works when I run it with python directly, but I get `Unable to load Info.plist exceptions (eGPUOverrides)` after packaging and running the `.app` file. Has anyone found a good workaround?

**Comment by lucazz** [comment]
Weirdly enough, got a new company laptop, plain Mojave install and this issue never manifested itself. Sad part is, since I can't reproduce this issue, can't follow up on this thread. :-(

**Comment by JamesVorder** [comment]
I'm not sure that I posted in the right thread... But FWIW, I worked around the issue of building a python app for Mojave by using [this template](https://github.com/beeware/Python-macOS-template).
