### ISSUE TITLE
Possibility to “Italicize” and “Boldify” Regular typefaces?

### ISSUE THREAD

**Issue by gipert** [alacritty/alacritty#1754]
Probably this is more kind of a question than a real issue, but anyways.

I want to use the Meslo font patched by Nerd Font (the one by Powerline looks uglier to me), but unfortunately the bold and italic typefaces aren’t available yet. Other terminal emulators didn’t ask me for bold and italic types in the past, so I assume that they had some kind of internal way to create them automatically from the regular one (not really an expert about this stuff, sorry).

So, as I cannot currently provide a bold and italic version of Meslo Nerd Font to Alacritty, is there a way to make it behave just like the other emulators?

Running on Linux with X11

**Comment by chrisduerr** [comment]
They might automatically use a different font which supports bold weight. Alacritty can do that too by specifying a different bold font.

**Comment by gipert** [comment]
Well, Meslo Nerd Font is the only Meslo font installed in my system, and I would have noticed if `st`, my previous emulator, had chosen a different typeface for the italic and bold weights... but I can check that, of course
