### ISSUE TITLE
Gnome+Wayland mixed DPI monitor switching weirdness

### ISSUE THREAD

**Issue by ndreas** [alacritty/alacritty#1801]
Which operating system does the issue occur on?
Linux, Gnome more specfially

If on linux, are you using X11 or Wayland?
Wayland

I run a laptop with a HiDPI internal screen and an extern regular DPI screen at work and I regularly switch between only using the external screen and only using the laptop. There's a strange bug in Alacritty when I use the switch monitor shortcut (Super+P) to switch from the "Built-in Only" (laptop) to "External only" mode. Any Alacritty window started on the HiDPI screen becomes blurry, and whenever I start another window it just resizes smaller and smaller. I have a log from `alacritty -vvv` that shows the resizing at the end:

[alacritty.log](https://github.com/jwilm/alacritty/files/2584979/alacritty.log)

Additionally, if I start an Alacritty window on the regular DPI screen and switch to only the HiDPI screen, text becomes blurry.

I have no problem dragging windows between the screens when both are active, no resize issue and crisp fonts. Seems like it only happens when disabling one monitor and enabling another at the same time.

**Comment by chrisduerr** [comment]
Usually the resize debug output should print the new dimensions. There's only one code path where this isn't the case. This is what it should look like:

```
Term::resize
num_cols, num_lines = 130, 32
width: 1326, height: 696
```

Taking a look at the latest master, the only way to skip this output without producing any other message is hitting this branch:
https://github.com/jwilm/alacritty/blob/master/src/term/mod.rs#L1140-L1145

Looking at what it does, it seems like Alacritty is receiving a resize event, but the size of the new window is 0. Could you provide the output of `alacritty --print-events`? This should show exactly which events are sent to Alacritty.

**Comment by ndreas** [comment]
Here's the log: [alacritty-events.log](https://github.com/jwilm/alacritty/files/2585119/alacritty-events.log)

Under XWayland I get something else. Going from regular to high, the window becomes very small with a small font (I suspect it doesn't pick up the change in DPI automatically). I also got huge fonts when I switched back to the regular, but that seems to be intermittent since I tried it again to get logs and it had regular font size when returning to regular DPI.

[alacritty-xwayland.log](https://github.com/jwilm/alacritty/files/2585138/alacritty-xwayland.log)

**Comment by ndreas** [comment]
I can do some spelunking in the code myself and see if I can discern what the problem is. I know it's impossible to test without being able to reproduce it. I guess it could be some weirdness Gnome does as well.

**Comment by ndreas** [comment]
I think this is an issue with Gnome's compositor. winit only updates DPI whenever a surface receives the `enter` and `leave` events, and Gnome doesn't seem to send those events when enabling/disabling outputs. I looked at the Wayland debug output from a GTK app, and it also doesn't receive the events.

The reason I reported it here is that I have only seen this in Alacritty. Termite and Gnome Terminal works fine, so I guess GTK use some other events to redraw whenever the screens change. I don't know if it's appropriate to look at handling this in Alacritty or if it should be considered a compositor bug.

**Comment by johnae** [comment]
I'm on sway (basically the latest commit as of today) - sway is an i3-compatible wayland compositor. I also get blurry text in alacritty. Also if I don't set WINIT_HIDPI_FACTOR=1.0 I get a ridiculously large font.
Other applications that are blurry are the X11-ones, but as far as I understand it, alacritty is supposed to be wayland native now (on alacritty 0.2.3). And yeah - my screen is a HIDPI screen.

**Comment by ndreas** [comment]
Alacritty is Wayland native, yes. That's why I'm concerned about this issue
since I really want to use it.

The fact that Sway has blurry XWayland apps is a consequence of XWayland
not supporting DPI switching on the fly, and for apps like Chrome and
Firefox that handle Hidpi themselves, Sway refuses to respect this and
always scales the app 2x making fonts blurry. Gnome on Wayland is the only
environment handling mixed DPI reasonably well on Linux.

Den tors 15 nov. 2018 21:38 skrev John Axel Eriksson <
notifications@github.com>:

**Comment by chrisduerr** [comment]
Are you both using WINIT_HIDPI_FACTOR=1? It seems like that could create blurry fonts because you're manually overriding the DPI factor.

**Comment by ndreas** [comment]
I'm not using `WINIT_HIDPI_FACTOR=1`. As stated, if I have both screens active, I can drag the window between the screens without problem. It's only when I switch from laptop to external that the window bugs out, and I think that's because Mutter doesn't send the `enter` and `leave` events for `wl_surface`.

**Comment by johnae** [comment]
I'm using `WINIT_HIDPI_FACTOR=1`, otherwise the scaling is completely off.

**Comment by chrisduerr** [comment]
Thanks for clarifying, hard to remember how all the events are called on the different platforms. I guess Wayland uses focus and focus lost for what I've talked about.

If `enter` and `leave` are not sent properly, I can definitely see that causing issues.

**Comment by ndreas** [comment]
Ok so this is definitely Gnome having problems, I just installed the latest Firefox Nightly with Wayland support, and it suffers from blurry fonts when switching from external monitor to internal, but dragging between the screens when active works just fine.

Feel free to close this if you don't want to implement some workaround in Alacritty. It's a great piece of software!

**Comment by johnae** [comment]
@ndreas Are you sure Firefox is a good example as they wayland status of it is kind of alpha. I have the issue with blurry fonts even without moving between screens. Other wayland native software (like termite for example) works just fine. Even really well, in my case on Sway. The Epiphany browser works really well too on Sway - Epiphany is wayland native.

**Comment by ndreas** [comment]
Both Termite and Epiphany are GTK apps and I suspect GTK does some check outside of the `enter` and `leave` events to see if a rescale is needed or not. I use Gnome Terminal and it also doesn't have this problem.

**Comment by ndreas** [comment]
So I looked at what GTK is doing and besides updating the scaling on `wl_surface enter/leave` events, it also does it on `wl_output geometry/mode/done/scale` events.

I actually think it's a good idea to do this, especially if the scaling of a `wl_output` changes. Now, if the scaling is changed from 2x to 1x, Alacritty (winit actually) is not aware of it and won't update the scaling/DPI. Alacritty won't get an `wl_surface enter/leave` at all, the surface stays on the same output.

Anyways, this stems from winit, so I think this feature should be added there. I'm going to take a look at implementing this myself and try to get a PR into winit.

**Comment by chrisduerr** [comment]
Thanks for looking into this. I'm surprised winit doesn't handle scale events already.

**Comment by NickeZ** [comment]
> I'm using WINIT_HIDPI_FACTOR=1, otherwise the scaling is completely off.

Your monitor is probably reporting the wrong physical size. I think you can check what size is being reported with xrandr. Then you can override it with your xorg.conf file. I'm pretty sure alacritty is doing the right thing here.

**Comment by johnae** [comment]
@NickeZ As I'm using a wayland compositor and alacritty, afaik, is supposed to be wayland native I'm not sure how X11 factors into the equation. However, I am running xwayland, but I was under the impression that wayland native apps shouldn't be using that.
I can ofc run xrandr since I am using xwayland for certain applications (like Firefox which unfortunately isn't wayland native yet), in that case xrandr reports:
```
Screen 0: minimum 320 x 200, current 3840 x 2160, maximum 8192 x 8192
XWAYLAND0 connected 3840x2160+0+0 (normal left inverted right x axis y axis) 294mm x 165mm
   3840x2160     59.98*+
```

It also is the case that I don't have any scaling problems with any other application I use (apart from X11 ones being blurry, but that is a known problem on at least some wayland compositors). So it's somewhat difficult for me to see how the only application exhibiting problems on my setup is the one doing the right thing.

**Comment by NickeZ** [comment]
What font size do you have and how large are the characters in mm on your screen? 6-8pt is reasonable sizes for me for example, so if you have 12 it might seem very large.

**Comment by johnae** [comment]
![ss](https://user-images.githubusercontent.com/28332/48672895-13598880-eb3c-11e8-973a-44a9fb5f7e3b.jpg)

Left is termite, font set to "Source Code Pro 14, right is alacritty font set to "Source Code Pro" and size to "14.0".

**Comment by chrisduerr** [comment]
@johnae Could you share the output of `alacritty -v`? Without `WINIT_HIDPI_FACTOR=1` set.

If I had to take a guess, the DPR is probably something like 3x or 4x.

**Comment by johnae** [comment]
Sure (and yeah, seems to be 3.5):

```
Welcome to Alacritty.
Configuration loaded from /home/john/.config/alacritty/alacritty.yml
device_pixel_ratio: 3.5
width: 3584, height: 2688
Initializing glyph cache
Finished initializing glyph cache in 0.027380166
width: 3134, height: 1982
Cell Size: (39 x 82)
Padding: (7 x 7)
PTY Dimensions: Line(24) x Column(80)
Initialisation complete
Font size changed: Size(28) [DPR: 3.5]
width: 3134, height: 1982
width: 640, height: 1059
[unhandled osc_dispatch]: [['7',],['f','i','l','e',':','/','/','c','e','r','e','s','/','h','o','m','e','/','j','o','h','n',],] at line 754
```

**Comment by chrisduerr** [comment]
3.5 seem insanely high to me. I can't imagine that's right. Based on your `xrandr` output I am pretty certain that your monitor's physical size isn't reported correctly with `xrandr`. So you'll need to fix this within X.Org to resolve that problem.

I'm not sure how things work in Wayland, but that should solve it for X.Org.

**Comment by johnae** [comment]
The intention is to use alacritty on Wayland,, not x11 as I'm on a Wayland
compositor (sway). Are you saying it looks as if alacritty is running on
xwayland and not wayland-native?

Den sön 18 nov. 2018 22:04Christian Duerr <notifications@github.com> skrev:

**Comment by chrisduerr** [comment]
I'm saying that XWayland will obviously not work when the dimensions reported are incorrect. I'm also saying that when the dimensions reported are incorrect in X.Org, it's possible that the reported DPI is also incorrect on Wayland.

**Comment by johnae** [comment]
Thanks for your input. I still find it odd that no other application exhibits this behavior. Neither those running on xwayland or Wayland native ones.
When compiling alacritty, is there anything I need to do to build it with Wayland support?

**Comment by chrisduerr** [comment]
Other XWayland applications probably do not scale by DPI at all. At least with GTK and QT that's the case by default unless you've set it up yourself (which most X.Org users haven't).

Alacritty decides between Wayland and X.Org at runtime, so it's not necessary to make use of any compile-time flags.

**Comment by johnae** [comment]
Trying to explicitly run alacritty on wayland ends in a panic:

```
env DISPLAY= alacritty -vvv
Welcome to Alacritty.
Configuration loaded from /home/john/.config/alacritty/alacritty.yml
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoWaylandLib X11 status: XOpenDisplayFailed', /build/alacritty-0.2.3-vendor/winit/src/platform/linux/mod.rs:437:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
WAYLAND_DISPLAY=wayland-0 in the above scenario btw - I'm running sway: https://github.com/swaywm/sway

**Comment by NickeZ** [comment]
@johnae is the physical dimensions of your screen 29.4cm x 16.5cm? Otherwise your screen is reporting the wrong size and there is nothing any software can do to calculate the correct dpr. Most other applications do not correctly calculate dpr yet, but i assume it is just a matter of time time before everything will get big on your display.

**Comment by johnae** [comment]
@NickeZ Yeah that's the size of my screen. I'm on a Dell XPS 13 (HIDPI).

**Comment by chrisduerr** [comment]
@ndreas That's not correct actually. Alacritty will get non-breaking winit updates even if glutin is not updated. So unless it's a major version bump, it can be included with a simple `cargo update` immediately.

**Comment by ndreas** [comment]
@chrisduerr Cool, I did not consider that. The more you know :) Anyways, I'm running a self compiled version now as the daily driver.

**Comment by ssendev** [comment]
On sway the same can be observerd by running
```
swaymsg output HDMI-A-1 scale 1
alacritty &
swaymsg output HDMI-A-1 scale 2
alacritty
```
which looks like this
![screenshot](https://user-images.githubusercontent.com/450793/65388969-28510a80-dd51-11e9-9a69-b282dad845e8.png)

so if alacritty is started before a HIDPI screen is present it's blurry after a screen is set to hidpi mode but when alacritty is started after a hidpi screen is present it's sharp.

**Comment by kchibisov** [comment]
Upstream bug https://github.com/Smithay/client-toolkit/issues/81

**Comment by goto-engineering** [comment]
I'm still getting this on Alacritty 0.5. It looks like the `client-toolkit` bug mentioned should work now, it's closed. Alacritty seems to have locked `client-toolkit` at 0.6, the current version is 0.11.

Any reason that couldn't be updated? Would probably fix this bug for free.
