### ISSUE TITLE
Add a Vulkan Renderer

### ISSUE THREAD

**Issue by LizziAS** [alacritty/alacritty#183]
https://forum.manjaro.org/t/alacritty-a-gpu-accelerated-terminal-emulator/15234

and as Tids says:  Why not vulkan?

**Comment by CarwynNelson** [comment]
I don't think there is any real reason to use Vulkan for this sort of application. It already runs at a very high frame rate that the extra work to get Vulkan working wouldn't really provide any real benefit.

**Comment by jwilm** [comment]
I'm hoping to have a Vulkan renderer at some point, but OpenGL made sense as an initial target since it's supported everywhere Alacritty cares about.

**Comment by atopia** [comment]
I don't use a Mac myself but maybe [MoltenVK](https://github.com/KhronosGroup/MoltenVK) can be used to support Vulkan on OS X?

**Comment by chrisduerr** [comment]
I think that what @CarwynNelson said is probably accurate, it's very possible that Vulkan would provide no benefit in performance while being a lot of work to get going and working everywhere.

However I'd love to be surprised by this, but I don't think there's any kind of priority on testing this out (which is why this has the "P - low" tag).

If there is a vulkan renderer in the future though it would be nice to use something like MoltenVK (or whatever is available when that happens).

**Comment by Avi-D-coder** [comment]
OpenGL is being [deprecated on macOS](https://developer.apple.com/macos/whats-new/#deprecationofopenglandopencl).

**Comment by chrisduerr** [comment]
I've read the same thing @Avi-D-coder. For now that probably doesn't change much, because I don't expect MacOS to drop OpenGL in under a year. However it would probably still be a good idea to have a long-term plan on how to fix this.

**Comment by cramertj** [comment]
@jwilm 
> OpenGL made sense as an initial target since it's supported everywhere Alacritty cares about.

We'd love to use alacritty on Fuchsia, but we don't have support for OpenGL. If you can provide mentoring instructions, I'm sure there are folks at Google who would be interested in helping to add support!

**Comment by chrisduerr** [comment]
I can't speak for jwilm but I think any help would be greatly appreciated!

If it is desired to support multiple different render backends without having to implement everything over and over again it could also pay off to look into something like gfx-rs.

**Comment by luisdavim** [comment]
Have you looked into these?

- https://github.com/MaikKlein/ash
- https://github.com/vulkano-rs/vulkano

**Comment by luisdavim** [comment]
I've done some reading around gfx-rs and https://github.com/gfx-rs/wgpu seems very interesting and promising.

**Comment by kchibisov** [comment]
I feel like changing `Vulkan` to `OpenGL` won't gain much for us, however using `gfx-rs` makes the most sense for us, if we want to support macOS via `Metal` or provide an option to pick `OpenGL/Vulkan` on Linux/Windows. So, while `Vulkan` is nice, I don't see any point in changing our rendering to anything other than `gfx-rs`.

**Comment by unmellow** [comment]
@kchibisov what about [WebGPU?](https://github.com/gfx-rs/wgpu) It has a rust library built on gfx-rs that you can use

**Comment by chrisduerr** [comment]
The biggest problem with both `gfx-rs` and `wgpu` is that both lack good OpenGL support. Which will likely always be our primary focus. So an API that doesn't properly support this is not very useful to us.

**Comment by leontepe** [comment]
> The biggest problem with both `gfx-rs` and `wgpu` is that both lack good OpenGL support. Which will likely always be our primary focus. So an API that doesn't properly support this is not very useful to us.

Why does Alacritty need OpenGL support so badly? Wouldn't it be more performant (and modern) to use wgpu, since it abstracts away the 3 major graphics APIs (Vulkan, Metal, DX) anyway? It also provides first class Rust support, apparently.

**Comment by kchibisov** [comment]
>Why does Alacritty need OpenGL support so badly? Wouldn't it be more performant (and modern) to use wgpu, since it abstracts away the 3 major graphics APIs (Vulkan, Metal, DirectX) anyway? It also provides first class Rust support, apparently.

Alacritty was written with OpenGL before wgpu existed iirc.

**Comment by chrisduerr** [comment]
> Why does Alacritty need OpenGL support so badly? Wouldn't it be more performant (and modern) to use wgpu, since it abstracts away the 3 major graphics APIs (Vulkan, Metal, DirectX) anyway?

Why do you think that abstractions would make things *more* performant? It's usually the opposite way around.

OpenGL is the best target because "newer" APIs are useless to Alacritty and OpenGL has **much** better compatibility with old hardware. Basically no reason not to use OpenGL really.

**Comment by klebs6** [comment]
i run neovim on tmux on alacritty and am wondering about 3d rendering within this setup -- i'd like to build or find some way to edit and view wireframe meshes/3d objects, rotate/zoom/interact with vim keys, as well as view audio signal spectrums, manipulate audio samples, etc without leaving the alacritty instance or relying on the host windowing system.

what do you folks think of this use case? is there a fluid way to perform these operations or is it something which has yet to be unearthed?

**Comment by chrisduerr** [comment]
> what do you folks think of this use case? is there a fluid way to perform these operations or is it something which has yet to be unearthed?

It's completely inappropriate for a terminal emulator.

**Comment by klebs6** [comment]
it may be completely inappropriate for your terminal emulator, but not for mine

**Comment by chrisduerr** [comment]
Well, Alacritty is mine. :wink: 

Of course I won't come after you if you decide to implement it yourself in your own fork. That's what forking is for after all.

**Comment by klebs6** [comment]
fair enough in all respects.  it is a wonderful piece of software which is why i use it -- the fastest component out there by my count.

i read this thread about integrating vulkan, other gpu layers and considered that you folks may understand deeply what i might need to do to achieve this sort of function, even though it is not the common use case.

it is useful to me even though it is perhaps not useful to you

**Comment by nixpulvis** [comment]
> Well, Alacritty is mine. 😉

Alacritty is also my terminal. Just saying.

**Comment by chrisduerr** [comment]
Closing because this is a non-goal. If someone ever bothers to write a Vulkan renderer feel free to send a patch, but currently we already have two different OpenGL renderers and that strikes a very good balance between GPU support and performance. Writing a Vulkan renderer would neither improve performance nor support much.

**Comment by sgon00** [comment]
FYI: [cosmic-term](https://github.com/pop-os/cosmic-term) is alacritty + vulkan.

**Comment by AethanFoot** [comment]
They currently massively outperform alacritty on vtebench which makes it an interesting watch to see how this changes further into development

**Comment by chrisduerr** [comment]
> They currently massively outperform alacritty on vtebench which makes it an interesting watch to see how this changes further into development

This means absolutely nothing. The things you should be comparing are render times, not vtebench. Vtebench only benchmarks the parser which is identical in both. In fact a significantly slower terminal would often perform **better** than a faster one, since it has to interrupt the parser less.
