### ISSUE TITLE
Support TTC fonts

### ISSUE THREAD

**Issue by yejingchen** [alacritty/alacritty#1849]
Which operating system does the issue occur on?
Windows 10 Professional 1809 17763.134
Alacritty-v0.2.3.exe downloaded from release page.

When set font family to `Sarasa Term SC` ([a Chinese programming font](https://github.com/be5invis/Sarasa-Gothic), version 0.7, TTC format), alacritty panicked with the following backtrace:

```
thread 'main' panicked at 'Index map format unsupported: 41545', C:\Users\travis\.cargo\registry\src\github.com-1ecc6299db9ec823\stb_truetype-0.2.4\src\lib.rs:583:18
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: winpty_spawn_config_new
  11: BaseThreadInitThunk
  12: RtlUserThreadStart
```

Setting font to Consolas and Source Code Pro seems fine. Is there anything I can do to provide more information?
Also, this problem doesn't seem to exist on Arch Linux and Mac OS.

**Comment by yejingchen** [comment]
Sorry for the delayed reply. I replaced the TTC (actually it's OTC) font with the TTF version and alacritty launches correctly, so I suspect rusttype doesn't support OTC format as they wrote in their README..

Maybe I will wait for the switch to fontkit then.

**Comment by zacps** [comment]
Actually fontkit should fix this. It has some issues but it's mostly just calling the DirectWrite API so it should support all fonts that Windows does.

**Comment by kchibisov** [comment]
Since we're using Direct write right now that should be fixed. If you still have issues let us know.
