### ISSUE TITLE
Alacritty slows on Dell monitor

### ISSUE THREAD

**Issue by huyvohcmc** [alacritty/alacritty#1854]
OS: MacOS 10.14.1
Monitor: [Dell U2518D](https://www.dell.com/en-uk/shop/dell-ultrasharp-25-monitor-u2518d/apd/210-amrx/monitors-monitor-accessories)
Config: [alacritty.yml](https://github.com/huyvohcmc/dotfiles/blob/master/alacritty/alacritty.yml)
Alacritty is built from source (master branch) with `rustup 1.14.0` and `cargo 1.30.0`

When opening Alacritty full-screen on my Dell monitor for about 2 - 3 hours, scrolling in **nvim** become super slow. The slowness only happens in the external monitor and never in Macbook main's desktop or in iTerm2. If I close that window and open a new window full-screen in the monitor, the slowness disappear but will come back after a random amount of time. Note that my monitor works perfectly fine with other applications.

**Comment by chrisduerr** [comment]
Is there any change in CPU/memory consumption? If there is a leak, that could cause problems.

**Comment by huyvohcmc** [comment]
@chrisduerr I wish there was. It still scrolls pretty ok with CPU and memory > 80% but very slow after a random wake up or if I leave it there for a while.

**Comment by chrisduerr** [comment]
Does this issue still exist in the latest Alacritty version?

**Comment by huyvohcmc** [comment]
No, not anymore.
