### ISSUE TITLE
Consider removing auto_scroll

### ISSUE THREAD

**Issue by chrisduerr** [alacritty/alacritty#1873]
The auto_scroll option adds the ability to jump to the bottom of the terminal whenever new content is written to it. This functionality is useful, however there are some issues with the implementation.

I've tested removing this code and the `trace!` in the input method and it turns out this improves Alacritty's performance by 3.39% in the alt-screen-random-write benchmark on my machine. This is with the option disabled (so default).

Now this is an extremely minor performance difference (<5%), however since Alacritty's priority is performance, I think it's worth discussing if this feature is relevant enough to introduce any kind of regression for users who have it disabled.

I'd be curious to know if there is anyone actively using this setting in their Alacritty configuration file or if it's just mostly unnecessary. This is not much of a call to action, since Alacritty's fine the way it is right now. However I think it's worth keeping track of potential performance hazards.

**Comment by chrisduerr** [comment]
Note that there's another feature which seems pretty simple, but has a significant impact on performance.

The escape sequence `echo -e "test\e[b"` requires the previous character to be stored in between calls to the `input` method in `src/term/mod.rs`. Because of that, every time a character is written to the terminal emulator, it's stored in a temporary buffer. Removing this increases performance by 5-10%.

I feel like it might be possible to support this command by looking at the cursor and reading the character of the previous column on demand, however I can see some issues with that implementation that might cause problems.

**Comment by jakeydoodle123** [comment]
**Only about auto-scroll:** 
Are you talking about removing the option to have auto scrolling to remove auto scrolling all together? 

If you are talking about removing it all together I think that isn't a great idea. Though the objective is high performance, there are a lot of tasks where you pretty much need autoscrolling (compiling, updating, etc.) and I think that is an important trade-off especially for such a negligible boost.

**Comment by nixpulvis** [comment]
I agree with the sentiment that we shouldn't be removing features altogether for performance if we can have them disabled and not costing anything. That said if we need to move things to compile time features to speed things up while we figure out better fixes, I'm all for that.

**Comment by chrisduerr** [comment]
This is not about removing the automatic scrolling when a command is running. This option is disabled by default, so unless you've manually enabled it, you likely never noticed it.

What it does is that when you're not at the bottom of the screen, but new output is printed, Alacritty will automatically scroll to the bottom. If the viewport is already scrolled all the way down, this has no effect (other than the performance impact).

> if we can have them disabled and not costing anything

That's the whole idea, checking at runtime is too expensive since the method is called so much.

> move things to compile time features

I'd be very careful with having to maintain a set of compile-time features which is rarely ever used but still needs to be considered. Unless it's a big thing (let's say scrollback for example), where both versions are likely to be used by many users, this would just create a big maintenance burden.

**Comment by jakeydoodle123** [comment]
Oh! that makes much more sense! That seems like a small option that would have become a feature in xterm or something because someone in the last 30 years needed it. Nowadays it isn't really a useful option so we might as well remove it, especially if you've already done most of the grunt work to make it work.

**Comment by nixpulvis** [comment]
I guess I'm just trying to appeal to everyone too hard. I personally don't feel like cargo feautures are too hard to maintain, but in this case I'm all for just ripping it out, I don't see it as that hard to hit a keybind or scroll to the bottom manually.

**Comment by chrisduerr** [comment]
I'd probably go for a deprecation warning with a link to this issue in a future release. Like that we could get some more information of users who might not be following the issue tracker actively. This isn't a massive deal, but if nobody wants it, there's simply no point why the people that do not want it should take a performance hit.

**Comment by Jomik** [comment]
I always found it super annoying that I would get pulled back to the beginning of the terminal due to this sort of feature (in other terminals, since it is disabled in my `alacritty.yml`).
Since your screen already follows the output automatically if you are scrolled all the way down, I think it makes a lot of sense that scrolling will stop the automatic behavior.
I'd definitely vote for it so that we can get more performance :+1:

**Comment by DX94-Quas** [comment]
I do not think it should be removed, but instead, a flag should be passed when compiling, if it bothers you too much.
Sometimes I work with a lot of output and is nice to rely on it taking me to the beginning.

**Comment by chrisduerr** [comment]
@DX94-Quas Do you have the option manually disabled? Just because there has been confusion about what exactly is meant here. This is specifically about the `auto_scroll` option.

A compile-time option would definitely be possible.

**Comment by kchibisov** [comment]
+1 here, let's remove thing from input.

**Comment by kchibisov** [comment]
Oh, in case someone wants to get to the beginning we have `ScrollToBottom` action, so just use it when you want, instead when some text output decides it for you.

**Comment by chrisduerr** [comment]
> Oh, in case someone wants to get to the beginning we have ScrollToBottom action, so just use it when you want, instead when some text output decides it for you.

Pressing any text key should also do it. That's what I usually do, just hammer random keys.

**Comment by ideologysec** [comment]
I'm very late to this party, but this is an option that I had *enabled* in Alacritty and never saw a deprecation warning. Can't say I'm all that happy, but I'm not asking for a revert - if it was all that important I'd recompile. :)

**Comment by chrisduerr** [comment]
@ideologysec Out of curiosity, what kind of things did you use it for?

**Comment by f0x52** [comment]
just came across this because I tried enabling auto_scroll because it seemed exactly what I want. Seems in `0.7.2` the deprecation warning is gone.
Usecase: I run node procesess with `nodemon` to auto-restart during development, often times scroll up to look at something, then change something in the code and then it'd be nice to autoscroll down to the latest output that just came in.

**Comment by chrisduerr** [comment]
Just press any key to get back to the bottom and resume auto-scrolling.

**Comment by f0x52** [comment]
works i guess but not ideal, as I have to focus and do something to the window, instead of it happening automatically, auto_scroll really seemed like the perfect option here

**Comment by chrisduerr** [comment]
Well it's a trivial patch if you're interested in it.

**Comment by f0x52** [comment]
ah looking at the pullrequest that removed it that does seem quite simple to add, will do that, thanks!
