### ISSUE TITLE
An utility to update the config file automatically?

### ISSUE THREAD

**Issue by YaLTeR** [alacritty/alacritty#1883]
I was testing some alacritty command line flags today and found out that some config options were moved around or deprecated. Alacritty helpfully printed the warnings to the terminal. So I had to move a bunch config settings around to comply with the changes (like `cursor_style` to `cursor.style`) and I thought that it would be convenient if there was an utility (`alacritty --fix`?) that applied those updates automatically, as well as removing any deprecated settings (warning the user in the process of course).

**Comment by chrisduerr** [comment]
I believe something like this has been discussed on IRC before and while it brings great value to the user, the technical implementation seems troublesome.

An easy and clean way would be to deserialize the configuration file, scrap/migrate old settings and serialize it again. However with this approach the new configuration file would be pretty much unreadable and all comments would have been stripped.

The alternative would be to try and fix each issue specifically, it would require almost writing a full custom yaml parser though and would likely be a huge mess. Even with an extremely simple change like `cursor_style` to `cursor.style`, there are a lot of different things that have to be considered (is it a comment? Is it plain text that should be pasted with a key binding?).

When thinking about how easy it is for the user to resolve this versus how difficult and messy it would be to implement a `--fix` solution ourselves, I feel like this feature isn't worth the hassle and the better solution would be to just keep it simple.

There's also something to be said about Alacritty changing the user's configuration file. However if it's done explicitly (with a `--fix` flag for example), I don't think that's much of a problem. It has been proposed to do this automatically at startup though, which is a complete no-go for me.

**Comment by kchibisov** [comment]
Such utility was added as a part of toml migration, this utility could be used to migrate toml to toml fields as well if needed.
