### ISSUE TITLE
Screen not cleared properly with Ctrl L

### ISSUE THREAD

**Issue by iKlsR** [alacritty/alacritty#1967]
***Windows 10 v0.2.3***. My yml is the default sans

    shell:
        program: C:/Program Files/Git/bin/bash.exe

When I press `Ctrl + L`, my cursor jumps back to the top of the screen as it would normally, however the screen isn't cleared properly and a weird insert type editing starts. I remedy this atm with `reset`.

![](https://i.imgur.com/gyx0MCE.png)

Notice that I'm typing as usual but the contents before the clear are still there, just being overwritten/cleared as I go along.

This only seems to happen when the screen is filled in some manner, either by opening a long file or some process with verbose output etc.

**Comment by chrisduerr** [comment]
Does running `clear` manually provide different results? It has been a while since I've run Alacritty on Windows, but I'm pretty certain this wasn't an issue with Windows 7.

**Comment by iKlsR** [comment]
No, clear does the same thing roughly. In one case I saw this as output

    S
    *
    Y
    *
    N
    *
    C
    *
    0
    0
    0
    0
    0
    0
    1

**Comment by cem** [comment]
Happens to me with ConPTY as well, although I can't be sure if ConPTY is enabled. I downloaded the released version with ConPTY support and enabled the relevant switch in the config.

**Comment by cem** [comment]
@chrisduerr It seems you're right, -v prints "Using Winpty agent".

**Comment by iKlsR** [comment]
Also happening with `powershell` now, tho not as frequently.

**Comment by nickcorona** [comment]
Happens using bash.

**Comment by JDTX** [comment]
This is an issue with WinPTY, I cannot replicate it using ConPTY.

However, I was able to work around this problem on WinPTY by setting my term to "cygwin" in the alacritty.yml file. 
```
env:
  TERM: cygwin
```

CTRL+L & `clear` works as expected with cygwin as the term.

**Comment by JohnDowson** [comment]
> ```
> env:
>   TERM: cygwin
> ```
This works, but limits terminal to 8 colours. I'll have to stick to mintty for now.

**Comment by siler** [comment]
> Also happening with `powershell` now, tho not as frequently.

Alacritty: 0.4.1 (ConPTY)
Win 10: 10.0.18362 Build 18362

It reliably occurs for me when:
1. Running Alacritty with powershell
2. Execute `alacritty --help` (or `--print-events`)

The cursor appears to advance but when something is typed it bounces back to where where it was before `alacritty` was executed, and a clear (`^L`) only clears to the point the cursor returned to. Typing `clear` clears the whole screen.

**Comment by chrisduerr** [comment]
WinPTY support has been removed.

**Comment by iKlsR** [comment]
Thanks for the update, will take another look.
