### ISSUE TITLE
screen is just black

### ISSUE THREAD

**Issue by dimbleby** [alacritty/alacritty#2016]
Windows 10 home edition, Alacritty-v0.2.5.exe.  I've also tried with 0.2.4 and get the same results.

I suppose this is something environmental - I mean you'd have noticed if this thing just didn't work on Windows! - but I've no idea what.

When I run Alacritty, I just get a black screen, and a cursor.  Typing gives the impression that I might be getting black text on a black background, the cursor looks as though it's moving the right amount.

**Comment by chrisduerr** [comment]
Might be a font rendering issue maybe?

Try running Alacritty from a different terminal like the cmd.exe, does it produce any output? Errors should be written to stderr if anything went wrong.

I'd assume you're using the default config, right?

**Comment by dimbleby** [comment]
Same output whether starting from cmd.exe or from file explorer.  No errors visible.

**Comment by chrisduerr** [comment]
Which GPU do you have? Might been an issue with OpenGL shader support.

**Comment by dimbleby** [comment]
ATI Radeon HD 3600

**Comment by dimbleby** [comment]
that glutin example works fine (I see a pink background and a many-hued triangle)

**Comment by chrisduerr** [comment]
It looks like a font is actually found and the glyph cache is filled properly. Testing the ConPTY backend by enabling the `enable_experimental_conpty_backend` might be another thing that could be tested, but I'm pretty sure this has to be related to rendering and OpenGL.

**Comment by dimbleby** [comment]
I set `enable_experimental_conpty_backend: true` in the config - and it made no difference at all that I can see.  

(I also set `enable_experimental_conpty_backend: foo` and got an warning about that, so I'm pretty sure I'm changing the right file).

**Comment by chrisduerr** [comment]
The output of `alacritty -v` should change from printing `[INFO] Using Winpty agent` to `[INFO] Using Conpty agent`. Unless your Windows 10 install is not up to date, in which case you should probably update first.

**Comment by dimbleby** [comment]
ack, I do see that change - but the alacritty window remains black.

**Comment by dimbleby** [comment]
Just noting that I don't see this problem on my Windows PC at work (the problem persists at home, though).  

Well, it was always near-certain that this must be something environmental; but I guess it's reassuring to have that confirmed.

**Comment by smdsbz** [comment]
Same issue here, only my cursor won't even move when I type 🤣  
`.\alacritty.exe -vvv` only responds on resizing the window.  
Task Manager says Alacritty is running on __GPU 0__, i.e. UHD 630 integrated graphics in my case (instead of the dedicate GTX1050m), dunno if this helps...

**Comment by chrisduerr** [comment]
@smdsbz Can you force it to run on the dedicated GPU?

**Comment by smdsbz** [comment]
> @smdsbz Can you force it to run on the dedicated GPU?

Unfortunately, no luck, it just stays blank like it's dead (but it __does__ respond to config changes like `render_time` on the fly, which gets displayed properly and fluctuates on mouse over).

One thing worth noticing is that it initially starts with GPU 1, then after few seconds, it falls back to GPU 0. I've tried both starting it with the _Run with graphics processor_ option in the right-click menu, and changing the default config in the nVidia panel, behaves the same.

Looks like it fails to communicate with the shell to me.

**Comment by chrisduerr** [comment]
Could you test a different shell? Like powershell, cmd and maybe bash?

**Comment by dimbleby** [comment]
Activity on this thread prompted me to have another go with the latest version - 0.3.0 RC 3 - and with that I get this interesting-looking error message:

```
C:\downloads\alacritty>Created log file at "C:\\Users\\Standard\\AppData\\Local\\Temp\\Alacritty-9508.log"
[2019-04-05 19:29] [ERROR] Alacritty encountered an unrecoverable error:

        There was an error initializing the shaders: Failed compiling shader at C:\Users\travis\build\jwilm\alacritty/res/text.v.glsl: Vertex shader failed to compile with the following errors:
ERROR: 0:48: error(#162) Wrong operand types no operation ':' exists that takes a left-hand operand of type 'const float' and a right operand of type 'const int' (or there is no acceptable conversion)
ERROR: 0:49: error(#162) Wrong operand types no operation ':' exists that takes a left-hand operand of type 'const float' and a right operand of type 'const int' (or there is no acceptable conversion)
ERROR: error(#273) 2 compilation errors.  No code generated
```

Does that help?

(I suspect that @smdsbz and I are seeing different issues.)

**Comment by dimbleby** [comment]
Hmm, the code in my latest failure looks new since I opened this, so I imagine we now have three problems cluttering this single issue.  Sorry about that.

**Comment by chrisduerr** [comment]
That kinda looks like your GPU doesn't support the OpenGL shader version Alacritty is using. Could you share the output of `glxinfo`?

**Comment by dimbleby** [comment]
Is that even a thing on Windows?  Google suggests not.

I mean it does look as though the code is mixing floats and ints - presumably my version of whatever-it-is is unusually fussy in caring about this.

**Comment by chrisduerr** [comment]
Oh my bad, I thought this was on Linux for a second. You could try editing the shaders and surrounding the integers with `float(var)` I think that's the GLSL way of casting. Maybe that changes things.

**Comment by dimbleby** [comment]
I'm afraid I don't care about this enough to go to the effort of recompiling the project.  But I imagine that fixing [these lines](https://github.com/jwilm/alacritty/blob/f0dbfc9b9c6514bc60e271bb74c2970e645d998f/res/text.v.glsl#L48-L49) so that they consistently use floating point numbers ought to be uncontroversial.

(Having said which, I suspect it'll only get me back to the black screen!)

**Comment by chrisduerr** [comment]
I'd suspect this just hints at the underlying issue that there is an issue with your GPU supporting the version of OpenGL that Alacritty requires.

**Comment by dimbleby** [comment]
According to [glview](http://realtech-vr.com/admin/glview) I have version 3.3.

**Comment by chrisduerr** [comment]
That should be sufficient. So I'm not sure if that can be it.

**Comment by smdsbz** [comment]
> Could you test a different shell? Like powershell, cmd and maybe bash?

__This is just straight up stupid! `shell: program: bash` did the trick for me!__

Just can't imagine powershell isn't in PATH :rofl: , but there __really__ should be a debug output for shell program not found btw...

**Comment by chrisduerr** [comment]
Alacritty will not actually start when the shell doesn't exist on Linux and macOS.

It's news to me that this isn't the case on Windows, but I was able to confirm it myself so that's likely the problem at hand.

ConPTY does also crash, however not with any useful error message. So I'll try to fix this on both backends.

**Comment by dimbleby** [comment]
#2261 does not close the issue that was originally described here.

**Comment by chrisduerr** [comment]
It should for ConPTY. There's nothing we can do about the shell not being present, that's a configuration issue of the system.

**Comment by dimbleby** [comment]
Yes, but none of that is relevant to the issue I described - the #2261 addresses the *different* issue that @smdsbz added to this report.

**Comment by cup** [comment]
https://github.com/jwilm/alacritty/issues/2344

**Comment by cup** [comment]
https://github.com/jwilm/alacritty/pull/3080

**Comment by chrisduerr** [comment]
I checked the GPU and it's telling me the latest driver supports only OpenGL 3.2 on Windows. Thus making it insufficient to run Alacritty.

If you can verify that your GPU supports OpenGL 3.3+, please let me know.
