### ISSUE TITLE
Support Operating System Commands for querying text parameter escapes

### ISSUE THREAD

**Issue by TaDaa** [alacritty/alacritty#2039]
Might just be a question -- I am looking for a means to query the background and foreground colors in Alacritty but I have not found a successful way to do it.  I have tried Alacritty both in MacOS Mojave and Ubuntu 18.04

My expectation was that `\033]11;?\033\\` and `\033]10;?\033\\` would print the background and foreground colors respectively, but neither seem to work on Alacritty -- are these ANSI codes not supported currently?

**Comment by chrisduerr** [comment]
This is currently not available in Alacritty.

Documentation about this escape can be found here:
https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Operating-System-Commands

**Comment by chrisduerr** [comment]
I'm not sure when this happened, but this is now implemented in Alacritty.
