### ISSUE TITLE
Click on https URLs wrongly opens File Explorer in Windows

### ISSUE THREAD

**Issue by atoav** [alacritty/alacritty#2084]
I use Windows 10 x64 with the lates 0.2.7 release build.

Since 0.2.3 I regularily have the issue that a click on URLs starting with `https` sometimes will open the File Explorer instead of the Webbrowser. It might also have to do with tmux. Simple http URLs work, as long as they are on a single line (otherwise they get trimmed to the first linebreak) – when adressing this #1906 should be considered as well.

Since this clearly isn't intended behaviour I decided to post this as an issue.

This is relevant for  #1970

**Comment by chrisduerr** [comment]
Is there an alternative to using `explorer` to open URLs on Windows? I'm not familiar with Windows' CLI tools.

It seems like `start "https://example.com"` could work? Can you confirm?

**Comment by atoav** [comment]
`start "https://example.com"` actually seems to open another cmd window with `https://example.com` as a title. This [site here explains](https://dwheeler.com/essays/open-files-urls.html) that opening urls with `start` could potentially be a security issue.  

Interestingly enough, the suggested alternative `explorer "https://example.com"` seems to work just fine – instead of opening Internet Explorer or Edge it luckily uses the systems default browser instead (so Firefox in my case).  

I suspect the issue I had is linked to [tmux](https://github.com/tmux/tmux), I especially had it happening when using the [irssi](https://irssi.org/) irc client

**Comment by chrisduerr** [comment]
That sounds like Alacritty is doing everything right. You could run `alacritty -vvv` to check which command exactly is executed to make sure the URL is detected properly though.

**Comment by mqudsi** [comment]
I wrote and use `open` for this: https://github.com/neosmart/open

It is a "micro" executable without any dependencies even on the Visual Studio CRT (which is a dependency of alacritty, though), and handles all uris and filetypes natively (via the shell32.dll interop). It also contains simple path translation to support opening relative paths from within a WSL session (e.g. `open ./foo/bar.txt`) that wouldn't normally launch under Windows proper.

I just realized the repository was missing a `LICENSE` file; I'll add one shortly, but it is MIT Licensed. I'll also upload a release right now. If I get a chance, I'll also authenticode sign it.

It's coded with workarounds that will let an x86 binary function natively under both x64 and x86 without any filesystem redirection too, so if there were interest in bundling it (for example, neovim bundles copy-and-paste helper binaries), it would be just the one 4kb binary.

**Comment by kthompson** [comment]
Typically the ShellExecute api call is used to open a browser link something like:

`LONG r = ShellExecute(NULL, "open", "http://www.microsoft.com", NULL, NULL, SW_SHOWNORMAL);`


See: https://docs.microsoft.com/en-us/windows/win32/shell/launch

**Comment by kthompson** [comment]
So I did some more digging and this may not be an issue specifically with windows as when I have a link such as `https://google.com` this opens correctly but the urls which i commonly enounter that have an issue are of the format: `https://bitbucket.org/company/project/pull-requests/new?source=feature/do-some-story-specs&t=1`

**Comment by chrisduerr** [comment]
> So I did some more digging and this may not be an issue specifically with windows

What do you mean by this? On which other platform would this create any issues? Certainly not Linux and I don't think macOS struggles either.

**Comment by kthompson** [comment]
I had a coworker that uses OSX try it but he appears to be using an old version so its probably not relevant. More specifically though I meant it may have something to do with the format of the link as some links work and some do not.

The alacritty log does show: 
`[2019-09-05 09:00] [DEBUG] Launched explorer with args ["https://bitbucket.org/company/project/pull-requests/new?source=feature/do-some-story-specs&t=1"]`

Which again opens my documents folder.

If i manually run `explorer "https://bitbucket.org/company/project/pull-requests/new?source=feature/do-some-story-specs&t=1"` this does properly open the link.

For the log entry:

`[2019-09-05 09:05] [DEBUG] Launched explorer with args ["https://google.com"]`

My browser does open google.com

**Comment by chrisduerr** [comment]
> If i manually run explorer "https://bitbucket.org/company/project/pull-requests/new?source=feature/do-some-story-specs&t=1" this does properly open the link.

That's kinda interesting, the `explorer` might be reading shell environment variables or similar maybe. It's Windows so I'd expect things to be at least a little bit messy and confusing, so this wouldn't surprise me.

**Comment by maroider** [comment]
It seems like this happens once you introduce a `=` in the URL.
I've thrown together a quick fix [here](https://github.com/maroider/alacritty/commit/72c7d945627fc9a33a2b7cd31c842f300f17f66f). I'll submit a PR once I'm reasonably certain that `explorer.exe` can't be made to work with URLs which contain `=`.

**Comment by meatcar** [comment]
As per [this stackoverflow answer](https://superuser.com/questions/1552619/how-do-i-pass-a-url-containing-an-equals-sign-to-explorer-exe), escaping the URL properly `explorer.exe """https://google.com/search?q=search"""` opens up the url in a browser. Tracing the issue further, looks like we use `std::process::Command` to execute the command, which has an active issue at https://github.com/rust-lang/rust/issues/29494 about improper argument escaping in Windows.

Maybe someone with stronger rust skills can try to use Win32 `CreateProcess` instead, until `std::process::Command` is fixed?
