### ISSUE TITLE
Take advantage of winit's new Wayland theming capability

### ISSUE THREAD

**Issue by JMurph2015** [alacritty/alacritty#2092]
In tomaka/winit#775, support for theming the title bar was added for Wayland for better UI integration.  Can Alacritty expose support for this through the config file (even if in some limited way)?  That would be awesome!

**Comment by chrisduerr** [comment]
https://github.com/jwilm/alacritty/pull/2047.

**Comment by MarioRicalde** [comment]
@chrisduerr Shouldn't this issue be closed as a duplicate?

**Comment by JMurph2015** [comment]
Usually pull requests aren't considered duplicates of issues.

**Comment by chrisduerr** [comment]
Yeah, this is the tracking issue for the PR. The PR might be closed or disappear for some other reason, but this issue is used to track the feature itself, not just one implementation process.
