### ISSUE TITLE
Automate Benchmarks & Run in CI

### ISSUE THREAD

**Issue by tbillington** [alacritty/alacritty#221]
Is it possible to include a shell script to run benchmarks against other terminals that could be automated at CI time to catch speed regressions?

**Comment by jwilm** [comment]
Yep, would love to have something like that.

**Comment by theduke** [comment]
OpenGL testing on Travis et al is a bit problematic.

You might be able to set somethig up with Xvfb + OSMesa or something like that.

**Comment by chrisduerr** [comment]
Looking at the performance difference on that page, I don't think this would improve anything.

I don't think anything that doesn't just ignore all render calls will be able to process Alacritty's output without GPU acceleration.

**Comment by zacps** [comment]
Is there any reason why just ignoring all render calls wouldn't work? The benchmarks shouldn't need the actual rendering to be verified.

**Comment by chrisduerr** [comment]
In theory there should not be any problem with that. However I'm not certain that there wouldn't be any complications.

**Comment by chrisduerr** [comment]
See https://github.com/alacritty/termbenchbot.

A follow up for more features can be found here: https://github.com/alacritty/alacritty/issues/4247.
