### ISSUE TITLE
Writting in last column inserts a newline (unlike xterm/rxvt)

### ISSUE THREAD

**Issue by Ferk** [alacritty/alacritty#2233]
To reproduce it, execute this in bash (`bash --norc` if custom prompt is obstructing):

    echo -ne "\e[s\e[$LINES;$((COLUMNS-3))fTEST\e[u"

This should make the word "TEST" appear in the bottom right, exactly in the corner border.
However, in alacritty it will also insert a newline, which does not happen in xterm or rxvt.

I'm using something like this as a pre-prompt hook in my bashrc to add prompt information to the right side, but this change of behavior in alacritty adds additional spaces to the prompt, and I guess it could potentially also mess up ncurses interfaces if they write characters in that space too.

**Comment by chrisduerr** [comment]
Ncurses is likely not affected by this, however this does seem to be inconsistent with other terminal emulators.

As a sidenode, this doesn't work at all in Termite, which doesn't insert a newline but it also immediately overwrites the `TEST` again.

**Comment by Ferk** [comment]
Hmm... I tested it in termite just now and it does not overwrite the `TEST`, maybe some other hook is writing there in your configuration.

**Comment by chrisduerr** [comment]
Yeah, I accidentally tested Zsh on Termite not Bash. Everything working as intended.

**Comment by Ferk** [comment]
That makes sense, zsh has `RPROMPT`, I'm basically replicating that feature in bash with my hook.
Probably unrelated but interestingly zsh's `RPROMPT` is not writing in the last column of the terminal, but in the one before it.

**Comment by hyperfekt** [comment]
I have a [script](https://github.com/hyperfekt/git-stagelight/blob/master/pre-commit) that truncates output to exactly terminal width which also triggers this bug.

**Comment by chrisduerr** [comment]
I just re-tested this due to mention in #3304 and it seems like it's fixed.

Let me know if you can still reproduce this problem.
