### ISSUE TITLE
Test BSD on CI

### ISSUE THREAD

**Issue by chrisduerr** [alacritty/alacritty#2248]
As issues like https://github.com/jwilm/alacritty/issues/2244 indicate, testing on Linux and macOS is not sufficient to make sure that BSD works properly.

While BSD is very likely to be a minor platform compared to Linux/macOS, I still think that Alacritty could significantly improve the level of support without raising the effort much.

Part of this is to ensure that the latest version of Alacritty at least builds on OpenBSD or FreeBSD as a simple sanity-check. Unfortunately travis does not support BSD natively but I'd propose to add a docker-based FreeBSD build to the standard CI process which at least tests that all tests succeed on the stable Rust platform.

**Comment by chrisduerr** [comment]
Based on some research it seems like support for BSD on the popular CI platforms like Travis is very limited. The only online CI service I found which provides BSD support seems to be [cirrus](https://cirrus-ci.org/guide/FreeBSD).

One alternative would be to setup a custom build environment just for BSD, though this would likely be a lot of effort for a poorly integrated version.

**Comment by johnae** [comment]
Don't know if you'd be interested in https://builds.sr.ht/ which does support FreeBSD among others. I actually haven't used it myself but the people behind https://github.com/swaywm/sway are also behind sr.ht.

**Comment by chrisduerr** [comment]
I wasn't aware that sr.ht also supports BSD. Based on that info alone I'd say it's probably the most promising platform I've seen so far.

However there's quite a barrier of entry for it, since it requires monthly payments. For projects that are completely on sourcehut that might not be a problem but just for testing out the CI process might not be worth it especially since I'm not sure how well Rust would be supported.

I'm surprised to see that there's github integration though. I was about to note that as another potential point of trouble but then saw on the sway github repo that it seems to be just working like travis or similar.

So while I'm not going to rush into setting up sourcehut to run all of Alacritty's CI at this point, I'll definitely keep it in mind. It seems like one of the better options available for BSD CI, so thanks for bringing it up.

**Comment by ddevault** [comment]
Hey, I'd be happy to give alacritty free builds on sourcehut.

**Comment by chrisduerr** [comment]
@ddevault That's a very nice offer and I'd love to take you up on that. At least for the period of setting everything up and testing the platform out, it would help a lot not to pay out of pocket for something that might not even pan out right in the end.

However, sourcehut is hardly asking for much (starting with $2/month) and also has development and hosting/electricity to pay for. So if we should decide to go with sourcehut for the future of at least BSD builds, I'd like to pay for the services we use rather than taking advantage of having reasonable popularity (which would be unfair to other, smaller projects imo). Chances are Alacritty would also be able to come up with at least the minimum price of sourcehut by taking donations itself, though I'd have to look into that and it would probably take a bit of effort to setup.

**Comment by ddevault** [comment]
I use Alacritty as my daily driver, this would be an easy way to thank you for it :)

**Comment by chrisduerr** [comment]
That's lovely to hear and does make for an exchange I'd be very happy about.

Since payment is currently optional as far as I can tell, it should also be possible to just try things out and see how it goes. So I think this is definitely the way forward for automatic BSD builds, especially since I'm not aware of any reasonable alternative. I'll have a play around with it this weekend to see how things pan out.

Thanks for the support @ddevault.

**Comment by ddevault** [comment]
No problem. I just upgraded you to a lifetime free account on sr.ht, enjoy!
