### ISSUE TITLE
Windows character codes not working correctly

### ISSUE THREAD

**Issue by hamptokr** [alacritty/alacritty#2284]
Which operating system does the issue occur on?
**Windows 10 Pro**

Character codes on Windows don't seem to be processed properly. For example here is the result of `rustup update` right after installing Alacritty with chocolately.

![image](https://user-images.githubusercontent.com/22182349/55816791-222be200-5ac1-11e9-89c2-66fb1fe6aff7.png)

**Comment by chrisduerr** [comment]
Is this with ConPTY or WinPTY?

**Comment by hamptokr** [comment]
> 
> 
> Is this with ConPTY or WinPTY?

In the location Alacritty was installed there is a `winpty-agent.exe` so I would assume WinPTY?

**Comment by chrisduerr** [comment]
When starting Alacritty from a terminal using the `-v` option it should print if it is ConPTY or WinPTY during startup.

**Comment by MarkusAmshove** [comment]
I have the same problem.

It says

```
[2019-04-09 20:17] [INFO] Welcome to Alacritty
[2019-04-09 20:17] [INFO] Configuration loaded from "C:\\Users\\Markus\\AppData\\Roaming\\alacritty\\alacritty.yml"
[2019-04-09 20:17] [INFO] Device pixel ratio: 1.5
[2019-04-09 20:17] [INFO] Width: 1536, Height: 1152
[2019-04-09 20:17] [INFO] Initializing glyph cache...
[2019-04-09 20:17] [INFO] ... finished initializing glyph cache in 0.0262316s
[2019-04-09 20:17] [INFO] Width: 1536, Height: 1152
[2019-04-09 20:17] [INFO] Cell Size: (12 x 25)
[2019-04-09 20:17] [INFO] Padding: (3 x 3)
[2019-04-09 20:17] [INFO] PTY Dimensions: Line(45) x Column(127)
[2019-04-09 20:17] [INFO] Using Winpty agent
[2019-04-09 20:17] [INFO] Initialisation complete
[2019-04-09 20:17] [INFO] Font size changed to Size(22) with DPR of 1.5
[2019-04-09 20:17] [INFO] Width: 1536, Height: 1152
```

**Comment by chrisduerr** [comment]
Could you try enabling ConPTY by setting the `enable_experimental_conpty_backend` setting in the config? Assuming that you've got Windows 10 1809 is installed.

**Comment by MarkusAmshove** [comment]
![grafik](https://user-images.githubusercontent.com/2401875/55825062-7c4e9680-5b05-11e9-9882-1d1ccd6e0c66.png)

Now it kinda works :-) The colors seem fine

**Comment by chrisduerr** [comment]
That looks good to me. I'd expect the remaining issues to be due to resizing while the update bar was moving? There's noting Alacritty can do about that unfortunately.

Color support on WinPTY is broken which is not Alacritty's fault, there's a different issue for that I believe though I'm not sure if we closed that or not (since there's nothing Alacritty can do).

**Comment by MarkusAmshove** [comment]
Still awesome progress, was curious how it works on Windows because I saw today that it has a Windows build.
Linux is working line a charm for me for months already :-)

**Comment by hamptokr** [comment]
> 
> 
> Could you try enabling ConPTY by setting the `enable_experimental_conpty_backend` setting in the config? Assuming that you've got Windows 10 1809 is installed.

That worked!

**Comment by kirawi** [comment]
Still happens with conpty?
![Capture](https://user-images.githubusercontent.com/67773714/93023637-4ba64280-f5be-11ea-94cf-7fb623b9cadc.PNG)

**Comment by kirawi** [comment]
Update? This is still happening.

**Comment by chrisduerr** [comment]
This issue is about a Windows WinPTY bug, so nothing related to Alacritty.

**Comment by kirawi** [comment]
It still occurs on conpty.
