### ISSUE TITLE
Set WM_WINDOW_ROLE via flag or env var.

### ISSUE THREAD

**Issue by remexre** [alacritty/alacritty#231]
Would it be possible to get a flag similar to `gnome-terminal`'s (and I assume others') `--role` flag?

**Comment by frebib** [comment]
Termite has this too and I use it to set them floating. For some reason I can't seem to invoke the same behaviour by setting the window class :(

**Comment by chrisduerr** [comment]
> Termite has this too and I use it to set them floating

I imagine you want to use that to set them floating for something like i3? Window title/class work great for that.

**Comment by frebib** [comment]
I'm currently doing this, but i3 is not playing ball
```
for_window [class="Alacritty-float"] floating enable
bindsym $mod+Ctrl+Return        exec i3-sensible-terminal --class Alacritty-float
```

I'm probably missing a trick though, so please point and laugh, then correct me :)

**Comment by chrisduerr** [comment]
Have you tried it with the title instead of class? That's usually a bit more foolproof since there can be multiple classes.

**Comment by frebib** [comment]
I haven't but that doesn't seem scalable seeing as various programs can change the window title. Is there a better option?

**Comment by chrisduerr** [comment]
You might get away with matching a substring of the path, I haven't looked into this with i3 but it's definitely set so it might be possible. I'm not sure how i3 deals with multiple set classes.

I wouldn't expect this to be a good solution for you, but if you're not showing the title in i3 anyways, you can disable dynamic titles for Alacritty and it will always stay the same.

**Comment by frebib** [comment]
I had some time to play with this today. This seems to work:
```
for_window [class="floating-term" instance="termite"] floating enable
for_window [class="Alacritty" instance="floating-term"] floating enable
```
and launching the terminals as such:
```
termite --class floating-term
alacritty --class floating-term
```

It seems that Termite & Alacritty do the opposite thing in respect to `class` and `classname`- I'm not sure which is more "correct"?

Sorry for hijacking your issue @remexre, but in case that this is helpful, enjoy :)

**Comment by chrisduerr** [comment]
Alacritty can freely set class and instance, that should be sufficient for the goals stated in this issue.
