### ISSUE TITLE
Crashes on launch after today's update

### ISSUE THREAD

**Issue by taigrr** [alacritty/alacritty#2386]
### Which operating system does the issue occur on?
Archlinux
### If on linux, are you using X11 or Wayland?
X11

### Issue

Launching after updating today crashes (version 0.3.2)

Sorry, I had to fall back to xterm to get the debug.
![image](https://user-images.githubusercontent.com/8261498/56929734-46129000-6a8f-11e9-8001-966f9df6af35.png)

**Comment by taigrr** [comment]
For now I've downgraded to  the package released on 12-Feb-2019 08:21 from the Archive.
sudo pacman -U https://archive.archlinux.org/repos/week/community/os/x86_64/alacritty-0.2.9-1-x86_64.pkg.tar.xz

**Comment by chrisduerr** [comment]
Could you provide some more information about the system you're using? Like the GPU you're running?

Do you have the default X11 installed or is it compiled without things like compositing support?

I'd also be interested in knowing if this works when building from the latest master, that might have resolved the issue already.

**Comment by taigrr** [comment]
Additional details:
 - Dell Inspiron, Coffee Lake i7 and NVIDIA GeForce MX150.
 - Default X11

I updated to 0.3.2-1 today, still does not work.

Cloned Github master and ran make install.
Build successful, running crashes.

Log file:
 ```
[2019-05-02 10:45] [WARN] Config window.start_maximized is deprecated; please use window.startup_mode instead
```

Rust backtrace debug output:
```
Created log file at "/tmp/Alacritty-14432.log"
[2019-05-02 10:48] [WARN] Config window.start_maximized is deprecated; please use window.startup_mode instead
thread 'main' panicked at 'Failed to call XMapRaised: XError { description: "BadDrawable (invalid Pixmap or Window parameter)", error_code: 9, request_code: 149, minor_code: 4 }', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:70
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:215
             at src/libstd/panicking.rs:478
   3: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   4: rust_begin_unwind
             at src/libstd/panicking.rs:312
   5: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   6: core::result::unwrap_failed
             at /build/rust/src/rustc-1.34.0-src/src/libcore/macros.rs:17
   7: alacritty_terminal::display::Display::new
             at /build/rust/src/rustc-1.34.0-src/src/libcore/result.rs:825
   8: alacritty::main
             at alacritty/src/main.rs:138
             at alacritty/src/main.rs:106
   9: std::rt::lang_start::{{closure}}
             at /build/rust/src/rustc-1.34.0-src/src/libstd/rt.rs:64
  10: main
  11: __libc_start_main
  12: _start

```

**Comment by chrisduerr** [comment]
Which distro are you using? That might give some hints to what might be missing here.

Bad drawable would usually indicate to me that you have a different color depths set or you've disabled compositing/tranparency. Have you done anything like that? Maybe through the nvidia settings?

**Comment by taigrr** [comment]
As I mentioned in the initial issue, I am running archlinux.

I have not disabled transparency or anything such as that. No changes to nvidia settings.

Using binary search, I built each release of alacritty until I found the breaking version.

0.3.0-rc3 works, 0.3.1 does not, so v0.3.1 introduces the breaking change.

**Comment by chrisduerr** [comment]
Could you bisect the exact commit? It's likely the glutin update if I had to take a guess.

**Comment by taigrr** [comment]
That is my guess as well, looking into similar issues online. I'll get back to you on that, hopefully today.

**Comment by taigrr** [comment]
Ok, finished the git bisect. It appears to be the following:
```
5174f9b27488902e7862aeb470aa0f0375c95e46 is the first bad commit
commit 5174f9b27488902e7862aeb470aa0f0375c95e46
Author: Christian Duerr <chrisduerr@users.noreply.github.com>
Date:   Sun Apr 14 15:37:58 2019 +0000

    Fix duplicate resize events

    If a resize event is identical to the current size, it is no longer
    propagated but the resize is discarded immediately.

    To further prevent resizes when not necessary, the list of monitors is
    enumerated and the DPR of the first display is assumed to be the target
    DPR.

    This allows spawning a window with dimensions when the config has
    columns and lines specified and the window only needs to be resized if
    the estimated DPR is not correct.

    Fixes #1825.
    Fixes #204.

:100644 100644 7624faf9812be49ca421fb3a4418adaa18d760e5 74a975015831cc620c28947085d4653fa1df15c9 M      CHANGELOG.md
:040000 040000 21609b484468513bbce2e887d8c715a88e3b1950 45178bed1712ed2ea89eabbcf3f9fca657c7cdd9 M      font
:040000 040000 4c364c491a5b4a21018cd8cfdb31c22215a2d0a2 33146666172da1be2adfe868988683797c48c400 M      src
```

**Comment by taigrr** [comment]
Ok, hang on. It's just that before this commit, the resizes don't work, and now they do. 

Before, I was trying to get the resizes to work, and they were ignored, so I set them to ridiculous values to make sure i wasn't going crazy. Now, they are actually trying to apply. 

Set my window resolution to sane defaults and now it's working. Sorry about that.

**Comment by Xuanwo** [comment]
I do think it's a bug.
This bug can be reproduced by set

```yaml
  dimensions:
    columns: 1000
    lines: 1000
```

**Comment by taigrr** [comment]
@Xuanwo yes, that's what I had that crashed it. I'm not sure I would classify it as a bug, though, since it's more PIBKAC, 


Maybe we can prevent canvas from becoming impossibly large and instead issue a warning to the user that the config is incorrect. But I don't think we should expect the terminal to conform to that config. Reopening in case someone thinks it's worth adding a warning.

**Comment by chrisduerr** [comment]
This is a tough one and I'm unsure if we can reliably fix it. In theory it should be possible to create an Alacritty window bigger than all existing monitors and creating one with the dimensions 1000x1000 works just fine for me. Though obviously at a certain size things just aren't going to work out anymore (100000x100000 lead to zsh killing Alacritty for example).

In a way this is just user-error, but it would be good if we could protect the user from himself here. But even if no drawable can be created, we need to be aware that the process of spawning a giant window itself might crash for other reasons.

**Comment by ChoppinBlockParty** [comment]
I have the same issue with release 0.4.0 Ubuntu x86_64. Can't start the terminal at all.

**Comment by kchibisov** [comment]
@ChoppinBlockParty could you launch alacritty from other terminal and post a backtrace?
```
env RUST_BACKTRACE=full alacritty
```

**Comment by chrisduerr** [comment]
If you read up on this issue, it's actually about a configuration issue @ChoppinBlockParty. So if you should indeed have this problem, you can easily fix it yourself.

Otherwise please open a separate one.

**Comment by chrisduerr** [comment]
Since this is a user error which is difficult for Alacritty to really "fix" and it doesn't actually crash for me on i3 anymore, I think there's no need for action here.
