### ISSUE TITLE
URL highlight needs to be cleared when content changes

### ISSUE THREAD

**Issue by chrisduerr** [alacritty/alacritty#2388]
If a URL is hovered above, but the content below it changes, the URL highlight needs to be removed.

This is a problem in applications like weechat (using ncurses) which autonomously change their content. I was not able to reproduce this in the terminal with just the shell running.

**Comment by CrackedP0t** [comment]
I was looking at this, and it seems like the best option might be to update the highlight whenever the terminal's content changes; not just when the mouse moves. For example, just in a regular shell:

1. Type in a URL
2. Move your mouse over it; it'll highlight
3. Delete the last character; it'll un-highlight
4. If you don't move your mouse, but click, it will still send you to the URL with the last character deleted.

This is pretty weird and unintuitive behavior. Updating the URL every frame when the terminal's dirty and the mouse is over the window seems best, as well as when the mouse moves - it might be a tiny performance drop, but probably not significant.

**Comment by CrackedP0t** [comment]
Does [this PR](https://github.com/jwilm/alacritty/pull/2413) fix this?

**Comment by chrisduerr** [comment]
Fixed in the latest master.
