### ISSUE TITLE
`#<something from history>` entered on click

### ISSUE THREAD

**Issue by OJFord** [alacritty/alacritty#2407]
```
$ alacritty --version
alacritty 0.2.9
$ uname -s
Darwin
```

Sometimes I accidentally click within alacritty window, and when I do I get something from my history, preceded by a `#` literal.

For example, after verifying that this occurred in `bash` as well as my usual `fish`, clicking resulted in:
```
1$ bash
bash-5.0$ exit
2$ #/bin/bash
3$
```
where I clicked at the prompt I've numbered `2` here, and not at `3`.

In case it's the fault of my own bindings, my `alacritty.yml` contains:
key_bindings:
```
  - { key: I, mods: Control, command: {program: fish, args: ["--command=alacritty-invert-colours"]} }
  - { key: K, mods: Control, action: ScrollPageUp }
  - { key: J, mods: Control, action: ScrollPageDown }
  - { key: Key3, mods: Alt, chars: "#" }
```

This seems related to #1291, in which the first click should be ignored on macOS because "it's really easy to cause some accidental selection" - except that not only is my first click _not_ ignored, but it's every click, no matter how careful; I'm definitely not selecting anything or even clicking on anything but the blank space next to my prompt (or _between_ prompts in the case of `fish`, but since I don't have a right-hand prompt in `bash`, it's not related to that).

It's not always perfectly from history either, for example:
```
1$ which env
[...]
2$ #enav
3$
```

**Comment by chrisduerr** [comment]
Which mouse button are you clicking? Do you use middle mouse to paste selection?

**Comment by OJFord** [comment]
Left, actually a trackpad tap. I've never knowingly configured it, nor plugged in an actual mouse, so I can't be sure but I'd assume MMB behaves as default on macOS.

**Comment by chrisduerr** [comment]
Is this still an issue?

**Comment by OJFord** [comment]
I don't think so; I mostly don't use macOS - but what I have noticed setting one up again recently was that _without_ that:
```
  - { key: Key3, mods: Alt, chars: "#" }
```

line above, type any (string of) character and Alt+3 will inject `#` before it, and carriage return. Without any characters, it will repeat the last one (it is _not_ on the clipboard), and Alt+3 will then again (with the characters now there) inject `#` and CR.

That is, type:
```
$ qwerty
```
then Alt+3:
```
$ #qwerty
$
```
then Alt+3 again:
```
$ #qwerty
$ qwerty
```
then Alt+3 again:
```
$ #qwerty
$ #qwerty
$
```


🤷🏻‍♂️ ! Doesn't affect me on Linux though, and anyone using macOS for a length of time would want that key binding anyway presumably, so not really an issue, just a curiosity.
