### ISSUE TITLE
alacritty applies window.dimensions before dpi scaling

### ISSUE THREAD

**Issue by aherrmann** [alacritty/alacritty#2431]
alacritty applies the default window dimensions as configured in `~/.config/alacritty/alacritty.yml` before rescaling according to DPI. E.g. in my case due to DPI alacritty rescales by a factor two. So, I have to configure
```
window:
  dimensions:
    columns: 160
    lines: 48
```
To achieve the expected effect of `80x24` dimensions.

Alacritty version 0.2.1

Which operating system does the issue occur on?
openSUSE Tumbleweed 20190508

If on linux, are you using X11 or Wayland?
X11

**Comment by chrisduerr** [comment]
> Alacritty version 0.2.1

Could you please update your Alacritty version to at least the latest release (even better the latest git if you're reporting a bug)?

This is definitely not the case when I'm testing things. Dimensions are correctly scaled by DPI.

**Comment by pwnorbitals** [comment]
Can we confirm this issue is stale and can be closed ?

**Comment by chrisduerr** [comment]
Yes, I cannot reproduce this and there hasn't been any answer for centuries. Thanks for updating, this should not be an issue.
