### ISSUE TITLE
Mouse cursor rendered in low-res on a HiDPI Wayland output

### ISSUE THREAD

**Issue by dnkl** [alacritty/alacritty#2445]
> Which operating system does the issue occur on?

Linux

> If on linux, are you using X11 or Wayland?

Wayland, Sway git master roughly equivalent to 1.1rc2.

On a HiDPI output, with scaling set to 2, the mouse cursor set by Alacritty is a low-res one. I.e. it is probably rendered to a surface that has **not** had its buffer scale set. This means the compositor (Sway in this case) will scale it.

See the difference below. When the cursor is hovering over the title bar, it is rendered by Sway itself, in high-res. When it's hovering over the window content, it is rendered in low-res.

![high-res](https://user-images.githubusercontent.com/14031526/57793492-bbde5300-7741-11e9-8f65-9da7ddee2f5a.png)
![low-res](https://user-images.githubusercontent.com/14031526/57793499-be40ad00-7741-11e9-8d77-d7a3e773fbcd.png)

I realize it's likely this isn't a bug in Alacritty per sé, but in one of its (wayland) dependencies.

**Comment by chrisduerr** [comment]
Can you reproduce this with the examples from https://github.com/rust-windowing/glutin? The simple `window` example should do the job.

I'd assume that this is an issue that needs to be handled upstream in winit.

**Comment by dnkl** [comment]
It reproduces with the `window` example. Is winit the correct upstream project to report this to?

**Comment by chrisduerr** [comment]
> Is winit the correct upstream project to report this to?

Yes, I'd appreciate it if you would report it there and link the issue.

Otherwise I can also open an issue upstream, though I can't help much with reproducing or answering potential questions.

**Comment by dnkl** [comment]
It was already reported

* https://github.com/rust-windowing/winit/issues/727
* https://github.com/Smithay/client-toolkit/issues/47

**Comment by chrisduerr** [comment]
Oh yeah searching the issue trackers is a great idea! Thanks for the links.

**Comment by illiliti** [comment]
>     * [rust-windowing/winit#727](https://github.com/rust-windowing/winit/issues/727)
> 
>     * [Smithay/client-toolkit#47](https://github.com/Smithay/client-toolkit/issues/47)

These bugs have been fixed
