### ISSUE TITLE
Feature Request: Hints for Regex

### ISSUE THREAD

**Issue by shibumi** [alacritty/alacritty#2536]
Hi,
I stumbled upon tmux-fingers. A really nice tmux plugin, that has a hint flag feature for several types of regexes. I thought about this a lot and I think it would be really cool if such features would be inside of alacritty: https://github.com/Morantron/tmux-fingers

What I would like to have is:
I type [ctrl]+[shift]+[space] [x] and i get hints for:

File paths
git SHAs
numbers ( 4+ digits )
hex numbers
IP addresses
kubernetes resources
UUIDs
URLs

then I can type a flag number in the terminal and i will copy the matched string

**Comment by chrisduerr** [comment]
Absolutely love this and it has actually been planned and discussed for URLs at least for a way.

Somewhat related is https://github.com/jwilm/alacritty/issues/262 I guess.

In general I think Alacritty would do extremely well with a way to open URLs with the keyboard and select stuff with the keyboard, as an i3 user that would be incredibly helpful to me. Having the URL detection flexible enough to handle other stuff (like just regexes) too would be a nice extra benefit.

**Comment by shibumi** [comment]
Smal addition to the Feature-Request: Would be nice to support Wayland (just switched to sway.. seems like it's the year of the wayland desktop)

**Comment by d-vb** [comment]
Are there any updates on this one? This would be really cool.

**Comment by rodolf0** [comment]
I built something related to this in https://github.com/jwilm/alacritty/pull/3126 it doesn't have keyboard navigation but it does recognize bits of text by matching regexes and allowing to click on them.

**Comment by pwnorbitals** [comment]
Have we seen any progress on this issue recently ?

**Comment by shibumi** [comment]
@chrisduerr  Thanks for your work :heart:
