### ISSUE TITLE
tmux lines seperating panes not showing up

### ISSUE THREAD

**Issue by jembishop** [alacritty/alacritty#2538]
Which operating system does the issue occur on?
WSL Ubuntu
If on linux, are you using X11 or Wayland?

Hi on Conemu and the default command prompt I can see the lines separating the panes in tmux but in Alacritty I cannot.

Conemu 
![image](https://user-images.githubusercontent.com/40360024/59471669-a6894100-8e33-11e9-9fab-77f280799499.png)
Alacritty
![image](https://user-images.githubusercontent.com/40360024/59471707-ca4c8700-8e33-11e9-9704-e90a5b2b052c.png)

Any idea how to fix this?

**Comment by chrisduerr** [comment]
Which version of Alacritty are you using? Could you test the 0.3.3 RC1?

**Comment by jembishop** [comment]
Unfortunately when i do `alacritty.exe --version` (or `alacritty.exe -v`) there is no output. This is another issue I have had after updating windows from 1803 to 1903, (however this pane line problem existed then before).  
![image](https://user-images.githubusercontent.com/40360024/59472114-514e2f00-8e35-11e9-8ad4-ecfe29ddedc8.png)
I downloaded it a couple days ago so probably the latest version. Don't know if there is a way to check

**Comment by chrisduerr** [comment]
I'd advise to just download the latest version here (portable will be fine for testing):
https://github.com/jwilm/alacritty/releases/tag/v0.3.3-rc1

The version command should definitely print the latest version, do any of the other commands work? I'm not very familiar with the Windows build, but at least in the standard shell that should work.

Also have you tested any of the other shells/backends?

**Comment by jembishop** [comment]
I have downloaded and ran the latest for windows (Alacritty-v0.3.3-rc1-windows-portable.zip).
I still get both of the errors I described.
The `alacritty.exe -v` opens a new session it just doesn't print the logs. The `--version` and `--help` flags do not work either. 

![image](https://user-images.githubusercontent.com/40360024/59472893-f5d17080-8e37-11e9-85f9-cf1c3ee6b6d7.png)

![image](https://user-images.githubusercontent.com/40360024/59472952-244f4b80-8e38-11e9-8e7f-a85d9ee959b4.png)
 I have tried using bash and I get the same results as I do in fish (what I was using previously).

**Comment by casonadams** [comment]
Maybe you could highlight the invisible text and see if anything appears, or copy and paste it in a text editor?

**Comment by chrisduerr** [comment]
Might also be interesting to see if ConPTY/WinPTY makes any difference. The legacy WinPTY backend just doesn't support a lot of stuff.

**Comment by jembishop** [comment]
Interestingly when I select the screen and paste it into notepad the characters do show up. 

![image](https://user-images.githubusercontent.com/40360024/59556468-cd25b400-8fba-11e9-8ad6-179f2e4f8075.png)

I have upgraded to windows 1903 specifically to use ConPTY, it is difficult to confirm it is using it though due to the issue with `alacritty --version` showing no output.

**Comment by chrisduerr** [comment]
Could you try running `alacritty.exe -v` from the default powershell? So skipping the whole Ubuntu WSL thing? I'd assume that might be why you're not seeing the output.

**Comment by jembishop** [comment]
So looks like not printing out unicode in allacrity is the issue...

Conemu:
![image](https://user-images.githubusercontent.com/40360024/59556569-64d7d200-8fbc-11e9-8c7e-8dfbdab47d8e.png)

Alacritty:
![image](https://user-images.githubusercontent.com/40360024/59556576-76b97500-8fbc-11e9-8e0e-b08252a6d8b3.png)

@chrisduerr  This does not work in powershell also.
![image](https://user-images.githubusercontent.com/40360024/59556583-8a64db80-8fbc-11e9-93de-40ca2cc875b2.png)

**Comment by jembishop** [comment]
Changing the font back from Inconsolata for Powerline to monospace solved the \U2500 characters not being rendered. I'm not sure why though this is the font on my other terminal emulators and that seems to work fine. Also the powerline prompt works fine and thats unicode, so I don't know whats up with that.

**Comment by davidhewitt** [comment]
I wonder if #3127 will resolve this. @jembishop ?
