### ISSUE TITLE
Inconsistent locale when running from command line vs from dock

### ISSUE THREAD

**Issue by RichoDemus** [alacritty/alacritty#2566]
Which operating system does the issue occur on?
Macos, Alacritty version 0.3.3, Swedish keyboard

I installed Alacritty via homebrew

If I start alacritty via the Icon in the dock/ Applications folder then the åäö characters doesn't work, å and ä does nothing and ö prints `(arg: 6)`

however, if I open Alacritty by running `/Applications/Alacritty.app/Contents/MacOS/alacritty` in iTerm2, then those characters works just fine

is env/dotfiles loaded differently or something?

**Comment by kchibisov** [comment]
> is env/dotfiles loaded differently or something?

@RichoDemus You can actually compare them by typing `env`, seems like locale problem. Also, could you share your `shell` section from `alacritty.yml`? On macOS your `shell` should have arg `--login` to work properly. It has this flag by default, but if you've changed it somehow, it can break things.

**Comment by RichoDemus** [comment]
Thanks 2 things:
I can definitely see env differences, it seems like when I launch it from iterm it enherits some stuff from there (I see a bunch of iterm things) but also things like `LC_CTYPE=UTF-8` is missing when it doesn't work and `SHLVL=2` is 1 when it doesn't work and 2 when it works

I did however try to just type `export SHLVL=2` and `export LC_CTYPE=UTF-8` but that didn't fix it

I'm not entirely familiar with how the config works, 
I've copy-pasted the alacritty.yml file from the repo into `~/.config/alacritty/alacritty.yml` is that then the only file that config is read from or are there multiple? (and they kinda override each other)

anyway, the whole shell section is commented out there, so I guess the `--login` thing should apply then

**Comment by kchibisov** [comment]
@RichoDemus `SHLVL` indicate how much shells you are in. So if you open terminal, then `echo $SHLVL` then `bash` and then `echo $SHLVL` the variables would be different ( `n` and `n + 1`). So, setting this one manually is probably a bad idea.

`alacritty` can use only the one config at the time. However, you should ensure, that config in `~/.config/alacritty/alacritty.yml` is actually in use. You can do this by launching `/Applications/Alacritty.app/Contents/MacOS/alacritty --print-events` from `iterm` and searching for line `[INFO] Configuration loaded from` ( one of the first lines).

How did you changed `LC_CTYPE`, just typing export or you've set in your shell configuration? You should probably set `LC_CTYPE` in your `SHELL` configuration file.

**Comment by chrisduerr** [comment]
Using `alacritty -v` instead of `--print-events` should usually be a better choice here since it produces a lot less output.

Generally this really does seem like a login shell issue, so it might be a good idea to uncomment the shell section in the used config and adding the `--login` parameter manually.

**Comment by RichoDemus** [comment]
Thanks for the responses!
`SHLVL`: noted, thanks
`-v`: I tried starting with the -v flag and it loads the correct conf. however, I added the flag when I started it from the command-line (and thats where åäö behaves properly) I don't know how I would add a flag when starting it by clicking the icon
`--login `: I tried uncommeting that but there's no difference.

**Comment by chrisduerr** [comment]
I'd assume that more than just `LC_CTYPE` is different, right? Could you compare the `locale` output on the two different Alacritty instances?

**Comment by RichoDemus** [comment]
They're both
```
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**Comment by chrisduerr** [comment]
That looks like a really odd locale. I'd expect all of them to be `en_US.UTF-8` or similar (depending on your system language).

Other macOS locale issues seem to indicate the same thing. Do you have any weird language setup in your OS?

**Comment by RichoDemus** [comment]
I'm not very good with locales, but I don't think I have a weird language setup. I have a macbook pro with a built in swedish keyboard, all buttons work exactly as expected in all other programs like browsers, iTerm2, intellij, including alacritty when run from the command-line

**Comment by chrisduerr** [comment]
I'd like to backtrack a few steps to the original issue of being able to launch just fine from a different terminal, but not from the application menu.

Clearly there needs to be some difference in environment, otherwise this wouldn't happen. The most likely to be at fault for this is still the locale. If other stuff in the environment variables is different, please let me know.

So the question really is about why the locale isn't set with the login shell and why changing the locale doesn't make things work.

Instead of `export`ing the locale, I think it might be worth a try to set it in the `env` section of the Alacritty config. That way it should be set for the Alacritty process and the shell both. Otherwise it would just be set for the shell. I think both mirroring the iterm locale and setting everything to `sv_SE.UTF-8` should be worth a shot.

**Comment by RichoDemus** [comment]
There are some differences but I don't think they're related, the one that works has the following extras:
```
TERM_PROGRAM=iTerm.app
TERM_PROGRAM_VERSION=3.1.6
TERM_SESSION_ID=w0t2p0:FEBB2B01-AD10-4CB7-9A16-E9661B15D728
ITERM_PROFILE=Default
COLORFGBG=7;0
ITERM_SESSION_ID=w0t2p0:FEBB2B01-AD10-4CB7-9A16-E9661B15D728
```
I believe those are things inherited by iterm

Alright! after adding
```
env:
  LC_ALL: "sv_SE.UTF-8"
```
to my alacritty yml it now works properly! 💯 
Thank you so much for you help and patience!

setting it to `"C"` has the same faulty behaviour as before

I am fine with that solution, but why could it be that I need to set it in my yml and not just in my bash profile?

**Comment by chrisduerr** [comment]
> I am fine with that solution, but why could it be that I need to set it in my yml and not just in my bash profile?

That almost seems like your systems language/locale is a bit messed up. I'd assume the problem is not with the shell rendering incorrect characters, but rather with Alacritty being unable to understand your keycodes.

You could try changing your OS language settings and changing them back to what they were then, in hope that this would update it.

**Comment by RichoDemus** [comment]
Changing locale back and forth did nothing

But I was reminded that I actually have a weird setup (sorry, didn't cross my mind)
I have a swedish keyboard with swedish keyboard mappings.
but my OS is in english and all my programs are in english (including `man` and `git` and stuff, so something with `locale` is english), so I guess my locale is a bit of a hybrid

**Comment by chrisduerr** [comment]
I'm not sure if there's anything Alacritty can do when your locale isn't set appropriately. Though I'm not sure where iTerm is getting its locale from.

**Comment by RichoDemus** [comment]
how do you mean appropriately?
I do think that having a different language for the keyboard and the OS/apps is a valid use case, this is the first time I've run into problems

or are you more referring to that it seems like macos isn't reporting it to alacritty properly?

**Comment by chrisduerr** [comment]
> or are you more referring to that it seems like macos isn't reporting it to alacritty properly?

I am. It seems like iTerm has additional locale settings set, where Alacritty does not. However Alacritty does spawn a login shell and should read the same environment that other macOS applications do. So the question is why iTerm gets that info and Alacritty doesn't.

I'd say this is odd for macOS to do, in general I've never seen any locale issue on systems other than macOS. But I can't guarantee you that this is a macOS issue.

**Comment by RichoDemus** [comment]
Ok, let me know if there's anything I can do to help troubleshoot it, otherwise you can close this :)
and thanks again

**Comment by chrisduerr** [comment]
I've reported the issue upstream at https://github.com/rust-windowing/winit/issues/943, maybe they have an idea at what could be going on.

**Comment by tofagerl** [comment]
I'm seeing the same problem with slight differences. 
I use a font with extra powerline characters, so that's how I noticed it, but can't see Scandinavian characters either. (I'm Norwegian)
However, I have the exact same environment settings in both iTerm2 and Alacritty, and when launching Alacritty from Alfred and from iTerm2. They're en_US.UTF-8 as they should be. 
I have this new variable though: when I launch my shell with Tmux configured to automatically launch, it fails to show the extended characters, but when I comment that out, everything is fine. I can then manually launch tmux, and everything is fine.
This also happens when I set tmux as my `shell program` in alacritty.yml

**Comment by kchibisov** [comment]
@tofagerl You should pass `--login` flag to your shell (`alacritty` doing this by default).
This is how your shell section in `alacritty.yml` should look like.
```
shell:
  program: /usr/local/bin/tmux
  args:
    - --login
```

**Comment by tofagerl** [comment]
@kchibisov I do. However, in my config.fish script I have this part:
```
if status is-interactive
and not set -q TMUX
    exec tmux attach
end
```
Of course, this is commented out. Earlier, I used tmux directly from shell, like that, but with attach as my arg, since tmux isn't a shell and `--login` is an invalid parameter.

**Comment by kchibisov** [comment]
@tofagerl Oh, I forget that tmux uses `-l` for login shell and don't have `--login` as all shells I know. Passing `-l` instead of `--login` should work

**Comment by tofagerl** [comment]
@kchibisov I completely agree - it should work. However, it doesn't.

**Comment by kchibisov** [comment]
@tofagerl Read update in my previous comment.

**Comment by tofagerl** [comment]
Actually the default-command is `set-option -g default-command "tmux rename-window fish; reattach-to-user-namespace -l fish --login"`
Let me sum up:
* Shell in alacritty settings: Blank | autotmux: off -> All chars work
* Shell in alacritty settings: tmux -l | autotmux: off -> Nope
* Shell in alacritty settings: Blank | autotmux: on -> Nope
* Shell in alacritty settings: tmux -l | autotmux: on -> ... I'm afraid to try ;)

**Comment by chrisduerr** [comment]
Just fyi, another thing you can try is to just set the shell in Alacritty to `fish` and then set the arguments to `[--login, -c, tmux]`. That should first spawn a login shell and then execute tmux inside of it.

That should definitely do the job if login shells work for you. But it seems like this is a separate issue, so it's probably best not to clutter this thread too much with it. If you need more help, feel free to open a separate issue.

**Comment by kchibisov** [comment]
You can try this as a last resort
```
shell:
  program: /usr/local/bin/fish
  args:
    - --login
    - -c
    - /usr/local/bin/tmux
```

**Comment by tofagerl** [comment]
That did work... It's slower, but that shouldn't matter much. I'll try to juggle these three config files around to make the default faster though. 
Plus now tmux doesn't autostart in iterm2 (oh noes!)

**Comment by bmikaili** [comment]
Ultra off topic @tofagerl, but would you mind sharing your Applescript to launch Alacritty? I've been trying to set it up but couldn't properly.

**Comment by Strayer** [comment]
I have the same issue (see https://github.com/jwilm/alacritty/issues/2837). After reading this I noticed that my setup is actually a bit comparable. My macOS is set to german, but with an US keyboard layout. For now I also resorted to setting `LC_CTYPE: en_US.UTF-8` in alacritty.yml.

I do have german and english in my preferred languages in "Sprache & Region" (Language & Locale?) in system settings, but I didn't set this up manually. Maybe macOS did it when I added the US keyboard. A coworkers german MacBook with no US keyboard only has german in that list, but his Terminal.app also shows de_DE.UTF-8 in all values except LC_ALL.

<img width="762" alt="grafik" src="https://user-images.githubusercontent.com/310624/66041668-ab751c00-e51a-11e9-88f8-0ee25daa7ad8.png">

**Comment by benknoble** [comment]
@Strayer did you ever have any resolution besides setting `LANG` or `LC_*` in your config? I have my mac setup in French, and when I open Terminal.app the locale is correctly set, but this is not true in Alacritty.

**Comment by Strayer** [comment]
No, I still have LC_CTYPE in my alacritty.yml:

```yaml
env:
  # https://github.com/jwilm/alacritty/issues/2566
  LC_CTYPE: en_US.UTF-8
```

**Comment by kchibisov** [comment]
This is likely a bug in our locale setting on macOS, so one could try to understand what is going on in https://github.com/alacritty/alacritty/blob/master/alacritty_terminal/src/locale.rs , I don't have macOS, so can't help here.
