### ISSUE TITLE
Buggy Characters in terminal Win

### ISSUE THREAD

**Issue by MattixNow** [alacritty/alacritty#2575]
Windows
Got some buggy character, example with zsh
![image](https://user-images.githubusercontent.com/32040951/59963514-1498cc80-94f4-11e9-8084-757929d3e64d.png)

**Comment by chrisduerr** [comment]
These indicate that there's a missing glyph. Do you have a font installed to display that glyph on your system?

**Comment by davidhewitt** [comment]
Potentially solved by #3127

**Comment by chrisduerr** [comment]
That was my assumption too, thanks for the bump @davidhewitt. Going to close this for now, since there hasn't been a response in months.
