### ISSUE TITLE
Modal keyboard controls

### ISSUE THREAD

**Issue by frysztak** [alacritty/alacritty#262]
Do you have plans to implement Termite-like selection mode?

**Comment by jwilm** [comment]
Can you elaborate a bit?

We now support the following selection modes

* Cell-by-cell as cursor moves
* Semantic selection (i.e. words) on double-click *and* as cursor is moved after double-click.
* Line select on triple-click and as cursor is moved after triple-click

Is there something beyond that we should support?

**Comment by sebastian-frysztak** [comment]
In Termite once you press Ctrl+Shift+Space you enter selection mode. You move the cursor around using hjkl, enter visual mode (using v) to select text, scroll using Ctrl+B, Ctrl+F and so on. Pretty much just like Vim. It might be the same thing as cell-by-cell selection, I'll have to try. How do I test it?

**Comment by jwilm** [comment]
Oh, we don't have anything like that. However, I have already been considering such a feature, so expect to see it added at some point in the future.

**Comment by jwilm** [comment]
Changed the title to _Modal keyboard controls_. The feature is basically as described--enter "normal" mode with some hot key, v to enter "visual" mode, keybindings for scrolling, selection manipulation, etc.

**Comment by norcalli** [comment]
Now that we have scrollback, if this feature was added, it would be a killer feature for alacritty. Although I'm wondering if it's something that could be abstracted away and implemented on a higher level if alacritty was extracted into a library or if this needs to be baked in. I'm not a terminal dev, just an avid fan, so that's where my knowledge ends.

**Comment by ngortheone** [comment]
Hi @jwilm @chrisduerr 
Alacritty is awesome and I use it every day both at home and work!

Just curious - is this feature on a roadmap? 
I use i3wm and currently if I want to scroll-back and copy something using keyboard i have to use tmux. This is not super convenient as tmux as I either need to start tmux manually for individual terminal instance or do automatic tmux enter on shell login. The latter creates a mess of a nested tmux layouts inside i3 layouts...

And are there any workaround? Are there users with i3 and what do they use for scroll-select-copy?

**Comment by chrisduerr** [comment]
It's definitely planned, though since this is a pretty 'advanced' feature I can't make any guarantees that it will land anytime soon.

I'm interested in this myself, however I also want this done right and there are other features which might have priority for now.

**Comment by EgZvor** [comment]
>  I'm wondering if it's something that could be abstracted away

Urxvt has this functionality implemented as a plugin https://github.com/muennich/urxvt-perls/blob/master/keyboard-select which suggests, I guess, that the answer is yes?

I also want to add as an urxvt user (on the edge of switching) that this feature is very much desirable.

**Comment by waynr** [comment]
I was just considering filing a similar issue, glad I searched first :)

I am interested in taking this issue on, although I understand @chrisduerr that you expressed some anxiety about doing it right so a relatively green Rustacean like myself might not be the most suitable person. I'd be happy to work on it with your direction though!

**Comment by vi** [comment]
I triggered this feature by mistake multiple time and only now found out that I need Ctrl+Shift+Space to turn if off (was restarting Alacritty and recommenting to Tmux instead).

Shall Alacirtty show some message like "Selection mode activated. Press Ctrl+Shift+Space to leave it" so that users who accidentally pressed Ctrl+Shift+Space instead of e.g. Ctrl+Shift+V know what to search for?

**Comment by nixpulvis** [comment]
@vi #4630 addressed this issue for me. Are you running a version of Alacritty with this feature?

**Comment by vi** [comment]
Now running `alacritty 0.5.0 (a6681e3)`.

**Comment by adworacz** [comment]
Looks like commit @nixpulvis referenced was attached to the 0.7.0 release. So you’ll need to update @vi to get what you want.

**Comment by Nate-Wilkins** [comment]
Is there a way to add additional shortcuts when in "keyboard motion mode"?
