### ISSUE TITLE
Blurred alacritty.ico in Large Icon Task Switcher on Linux

### ISSUE THREAD

**Issue by xuzhao9** [alacritty/alacritty#2651]
Hello! I am an Alacritty fan on KDE and using the Large Icon task switcher. Everything works great except that Alacritty icon is blurred icon under this scheme. See the screenshot here: https://ibb.co/z4S7wwV
After some exploration, I found replacing the extra/windows/alacritty.ico fixes this problem. I can provide the new ico file at: 
https://user.fm/files/v2-86512d5494230eebac9323053bfe8dba/alacritty.ico

I can also submit a pull request, if you want.

Which operating system does the issue occur on?
openSUSE Tumbleweed 20190708

If on linux, are you using X11 or Wayland?
X11

**Comment by kchibisov** [comment]
@xuzhao9 How does `KDE` pickup icons for task switche? Does it uses `NET_WM_ICON` or it just query them from `/usr/share/pixmaps` ? I guess the first one, since you've mentioned `extra/windows/alacritty.ico`, which is used for `NET_WM_ICON`, but I remember that it uses `/usr/share/pixmaps` over `NET_WM_ICON` in some places, so just wondering what you've changed here.

**Comment by xuzhao9** [comment]
@kchibisov Yes, it uses the NET_WM_ICON. /usr/share/pixmaps/Alacritty.svg is the vector one therefore should not be blurred, however it is not being used.

**Comment by chrisduerr** [comment]
Since the .ico is primarily for the standard Windows icon, it's probably a good idea to check how it looks on Windows. As far as I remember, there were some good reasons for building the ico the way it has been built, however it's possible that just increasing the resolution would still work fine on Windows.

**Comment by kchibisov** [comment]
@xuzhao9 Yes, seems like that, unfortunately we can't use `svg` for `NET_WM_ICON`, since our dependency doesn't support loading them (`KDE`/`Qt` had some problems with `Alacritty.svg` though).

**Comment by kchibisov** [comment]
@chrisduerr As far as I've [understood](https://docs.microsoft.com/en-us/windows/win32/uxguide/vis-icons) we can use icon with `256x256` for windows (The maximum size for `ico`). It will downscale it to appropriate size.

@xuzhao9 How did you build this icon though? Upscale?

**Comment by chrisduerr** [comment]
Well we do provide the SVGs, so rendering them to a specific size as a PNG shouldn't be too difficult and that's what I've done to create the icons myself. I think the icon might contain multiple images at multiple sizes though, or at least some dynamic properties. However I'm unsure how well Windows supports this. Ideally we'd want to use the image with scanlines for 256x256 size icons, however it wouldn't look good when scaled to a smaller size.

**Comment by xuzhao9** [comment]
@kchibisov I built this icon from the svg file with imagemagick.

**Comment by kchibisov** [comment]
> Well we do provide the SVGs, so rendering them to a specific size as a PNG shouldn't be too difficult and that's what I've done to create the icons myself. 

Yes, I've also thought about this myself. I've  asked @xuzhao9 , since the corners of his new image are choppy. On a page I've linked there is a section `Size requirements`, windows supports sets of icons. So we can include `16x16`, `32x32`, `48x48`, and `256x256` ( as advertised ), I wonder how `linux` would behave though.

>  @kchibisov I built this icon from the svg file with imagemagick.

Hm, maybe some tuning required here.

**Comment by chrisduerr** [comment]
I remember that there was some kind of issue with the combination of imagemagick and Icon sets on Windows. I just don't remember what exactly was the problem, but the dynamic sizing did not work properly iirc.

**Comment by kchibisov** [comment]
>  I just don't remember what exactly was the problem, but the dynamic sizing did not work properly iirc.

That's sad. So, maybe creating the icon set on windows directly ( with some tools from microsoft or something like that)  and after that testing on linux + X11? 

-- A little bit off
@chrisduerr , Do you know if it's possible to run `alacritty` inside windows vm ( virtual box ) or native environment required here?

**Comment by chrisduerr** [comment]
I have not been able to run Windows on my proxmox VM yet, because of missing OpenGL functionality/drivers. However on Linux things worked just fine even virtualized. I haven't looked into this a lot and I'd welcome potential solutions for myself, but I would be surprised if it just works out of the box for you.

**Comment by kchibisov** [comment]
@xuzhao9 Do you want to research on this, generating icon sets, improving your new icon a bit, just asking since you've mentioned that you can send a `PR`? I'll try ( in case of `alacritty`s launching success on windows under vm) to take a look on a windows things here, since I need to setup a vm for my work needs anyway. But even if I fail with vm, I guess some windows folks can test it.

--
@chrisduerr I'll let you know somewhere in case of success. We are both using `amdgpu` driver and running `Arch` as far as I remember/understand.

**Comment by chrisduerr** [comment]
> We are both using amdgpu driver and running Arch as far as I remember/understand.

The proxmox VM I'm using doesn't actually have any GPU, which is why I was so surprised about it working on Linux. But you might still run into similar issues with Windows.

**Comment by xuzhao9** [comment]
After some research I found that in Windows the common practice is to set the icon to be a 256x256 .ico in the .rc file. For example, both [mpv](https://github.com/mpv-player/mpv/blob/802f594a857c703ac88e946d14b69cd3b6eb6006/osdep/mpv.rc) and [telegram](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/Resources/winrc/Telegram.rc) do this. And for X11, a 256x256 .ico file will be sufficient because X11 will downscale automatically, although mpv sets [four different sizes](https://github.com/mpv-player/mpv/blob/fcb320fd3fd3b1fc5549c009f23fc831bd37a495/video/out/x11_common.c) in X11, which I think is an overkill.
If you all agree with my proposal, I will explore how to generate a high-quality 256x256 .ico file with the .svg.

**Comment by kchibisov** [comment]
> Ideally we'd want to use the image with scanlines for 256x256 size icons, however it wouldn't look good when scaled to a smaller size.

@xuzhao9 We have a special "variant" for big icons `extra/logo/alacritty-term+scanlines.svg`, you can see it on `alacritty`s page on github. So, setting it for `256x256` and using `extra/logo/alacritty-term.svg` for something smaller.

However I'm a little bit skeptic about `scanlines` variant, I've tried it on my system (4k 27 inch ips display + 2x scale under wayland) and everything smaller then `168x168` was blurry, and I think on displays with worse matrices/lower resolutions it may look not as `good` as `alacritty-term.svg`. So, I'm fine with the solution you're proposing here.

**Comment by xuzhao9** [comment]
@kchibisov I have regenerated the icons and you may download it at: https://user.fm/files/v2-eb0097bcc2d0c10b12190122ca79b417/alacritty-icons.tar.gz .
Unfortunately, I don't have any windows machine, nor do I familar with windows app development. I tried to find how to enable multi-sized icons support in the .rc file but I have no luck. I can help with the X11 platform and submit a PR.

**Comment by kchibisov** [comment]
@xuzhao9 I can test on windows in a vm. Unfortunately I can't run alacritty in it (OpenGL 3.3 is not working under vitrtualbox), but to test an icon, we don't need fully functional alacritty, everything can be done with `winit` window example, so I'll test it when we agree on a solution.

> However I'm a little bit skeptic about scanlines variant, I've tried it on my system (4k 27 inch ips display + 2x scale under wayland) and everything smaller then 168x168 was blurry, and I think on displays with worse matrices/lower resolutions it may look not as good as alacritty-term.svg. So, I'm fine with the solution you're proposing here.

@chrisduerr What do you think about using `alacritty-term.svg` for all sizes ( just providing `256x256` version)?

**Comment by chrisduerr** [comment]
> @chrisduerr What do you think about using alacritty-term.svg for all sizes ( just providing 256x256 version)?

Assuming that this works properly, I'd be fine with that in scenarios where we cannot use an SVG.

However in general I'm against this. Whenever possible we want to provide the correct icons, some platforms just aren't very good at icons apparently.

**Comment by nixpulvis** [comment]
@xuzhao9 I've downloaded and tested out the icons you've generated in a browser, and they are looking pretty nice :tada: In fact, I had noticed that the README.md's icon is a little blurry so I've opened #2707 to address this with the 256 pixel version from your download. You can see it for yourself here: https://github.com/nixpulvis/alacritty/tree/crispy-readme-icon.

However, I'd really like a way to generate these ourselves. If you used a script, would you be able to open a PR to add it to `scripts/`? Ideally we'd have a single source logo (SVG?) that we compile automatically to all the other formats.

**Comment by xuzhao9** [comment]
@nixpulvis The PR looks good to me. I can certainly submit a PR adding the scripts. However, I made the .ico files from the .svg files with the ImageMagick tool (i.e. the `convert` command line tool). I am not sure whether we should add this dependency into the build toolchain.

**Comment by kchibisov** [comment]
I've decided to play with imagemagick a bit. Does this [icon](https://www.dropbox.com/s/2qsdtwbe2gn77uh/out.ico?dl=0) look better? I can create the same one for no scanlines version.

And once again, what do we want for our `alacritty/extra/windows/alacritty.ico`? Scanlines for 256x256 and `alacritty-term` for smaller ones or just one big `alacritty-term`. However the first one is valid in case I'll make it work under windows.

**Comment by chrisduerr** [comment]
> And once again, what do we want for our alacritty/extra/windows/alacritty.ico? Scanlines for 256x256 and alacritty-term for smaller ones or just one big alacritty-term. However the first one is valid in case I'll make it work under windows.

Yea my main concern with having scanlines in the big .ico is that some platform (Windows) might use the big icon to render smaller images. Since we use the .ico on Linux too, it might also be used in Window titles or stuff like that.

**Comment by michaelfresco** [comment]
BUMP:
I'm also running KDE. (I'm trying to switch away from MacOS). And this is still an issue in 2020. (alacritty 0.0.40, kde 5.12.19, ubuntu 18.04)

**Comment by kchibisov** [comment]
>And this is still an issue in 2020. 

Thank you for reminding us what year it is right now, keep us updated.

Generally if you want something to be solved, you should send patches yourself (this is how it works), rather than "bumping" issues. This issue is not that hard if you have a bit of time to play with `ico` formats and we can always provide help here.

**Comment by michaelfresco** [comment]
> Yea my main concern with having scanlines in the big .ico is that some platform (Windows) might use the big icon to render smaller images. Since we use the .ico on Linux too, it might also be used in Window titles or stuff like that.

I took the  `/extra/logo/compat/alacritty-term.svg` (the one without scanlines) and converted it to a 256x256 ico.

This is the result:

![before_after_icon_change](https://i.imgur.com/IwnI8XN.png)

The script I used to generate the icon file I put in a gist. 
https://gist.github.com/michaelfresco/1f7501b190f1a0bee7d598ceee9cb066

Please find a [PR here](https://github.com/alacritty/alacritty/pull/3213).
