### ISSUE TITLE
Odd behavior in fish shell when moving text to the end column.

### ISSUE THREAD

**Issue by kchibisov** [alacritty/alacritty#2687]
Which operating system does the issue occur on?
Arch Linux

If on linux, are you using X11 or Wayland?
Wayland

Version?
`alacritty 0.3.3 (72dfa47)`

if you'll move some text to the end column - 1 by pressing space chars and then hit space one again, the last char will be doubled 
(adding more space chars results in super odd situation).

This issue isn't presented in other terminal emulators and **the most important part** of it, that I can't reproduce it, when `alacritty` is built in release mode.

Some explaining pictures:

Before:
![Screenshot_Tue 30 Jul 2019 06:01:55 PM MSK](https://user-images.githubusercontent.com/27620401/62149601-c5b93080-b304-11e9-952a-325326c2c2d5.png)

After:
![Screenshot_Tue 30 Jul 2019 06:02:07 PM MSK](https://user-images.githubusercontent.com/27620401/62149602-c5b93080-b304-11e9-8728-0dc3235f1b54.png)

After more spaces:
![Screenshot_Tue 30 Jul 2019 07:24:33 PM MSK](https://user-images.githubusercontent.com/27620401/62149605-c5b93080-b304-11e9-89a4-9890587be3aa.png)

**Comment by chrisduerr** [comment]
Is there any way to reproduce this without pressing space and moving existing text to the right?

**Comment by kchibisov** [comment]
I don't think so, it's random even in debug mode. Probably this issue can only be reproduced on my system. This is also doesn't happen with default fish shell config, but since this issue doesn't appear on release build, fish shell seems unrelated here. I'll investigate on what's going on here. 

At first look it = seems like we don't have a lock for something and in debug mode the code path, that should be finished after something, starts finishing before.

**Comment by kchibisov** [comment]
Closing since can't repro.
