### ISSUE TITLE
Alacritty: Runtime Error panicked at 'called `Result::unwrap()` 

### ISSUE THREAD

**Issue by cmschireson** [alacritty/alacritty#2720]
Running alacritty on windows and running into this issue:

---------------------------
Alacritty: Runtime Error
---------------------------
panicked at 'called `Result::unwrap()` on an `Err` value: Err { ptr: winpty_error_s { _unused: [] }, code: 5, message: "ConnectNamedPipe failed: Windows error 232" }', src\libcore\result.rs:997:5

No clue where to begin.  I didn't have a problem until today.

**Comment by chrisduerr** [comment]
Did you change your configuration file or upgrade the Alacritty version?

Windows error 232 means pipe closed and I feel like it could be a problem with not being able to connect to the shell.

Do you have this problem with both conpty and winpty?

**Comment by cmschireson** [comment]
I upgraded it after it failed to see if that would fix the problem but it didn't

**Comment by edyu** [comment]
Similar problem:
---------------------------
Alacritty: Runtime Error
---------------------------
panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', src\libcore\result.rs:997:5

Press Ctrl-C to Copy
---------------------------
OK   
---------------------------

**Comment by chrisduerr** [comment]
@edyu That's a separate file, make sure you've got all the required files installed. Feel free to open a separate issue.

**Comment by GarkGarcia** [comment]
Just had the exact same issue. Reinstalling Alacritty did the trick. Also, the issue came up when I was uninstalling an IDE, so maybe something wimpty related got deleted by the IDE uninstaller?

**Comment by chrisduerr** [comment]
To do anything about this we need the backtrace with debug annotations (which you can get by running `cargo run`).

I also need to know if this problem exists with the ConPTY, or only with WinPTY. The backend can be configured in the config and it's printed in `alacritty -v`.
