### ISSUE TITLE
Alacritty:The icons in ranger don't show correct

### ISSUE THREAD

**Issue by XDID** [alacritty/alacritty#2721]
<img width="211" alt="截屏2019-08-1510 15 00" src="https://user-images.githubusercontent.com/51253594/63068375-8b2ad700-bf45-11e9-8d8a-200fd409dad1.png">

**Comment by kchibisov** [comment]
What's your OS, `alacritty --version` output and output of `locale`. How it should look like (screenshot from other up should work, just for the reference)?

**Comment by chrisduerr** [comment]
If you're still running into this issue, please make sure your locale is correct. Otherwise I'd assume it resolved itself since there has been no response.

**Comment by ovitente** [comment]
**Alacritty ver:** v0.4.1
**OS:** Mac OS Mojave (latest updates)
**locale output under alacritty:** 
```
det@B-503:~  locale
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**locale output under Iterm2:** 
```
det@B-503:~  locale
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

default look
<img width="322" alt="image" src="https://user-images.githubusercontent.com/10868371/74281100-7da0af00-4d26-11ea-9a35-f029078b1bdd.png">

After exporting `export LC_CTYPE="UTF-8"`
<img width="330" alt="image" src="https://user-images.githubusercontent.com/10868371/74281152-98732380-4d26-11ea-8e3d-f6819ee76a64.png">

**Comment by ovitente** [comment]
@chrisduerr 
There is an issue in this solution, that Ranger does not show any moving animation while pressing arrow keys or `hjkl`, but it changes dir after `Enter`. So you don't see a cursor on the selected item.
This bug is only in default alacritty mode (locale).

**Comment by kchibisov** [comment]
>How to repeat:

>    Open Alacritty on mac in SimpleFullScreen mode
    Cmd+Tab to any other fullscreen window, i.e. browser (Firefox)
    Cmd+Tab back to alacritty
    Ranger does not react to moving keypresses


@ovitente you've describe this bug #3188

**Comment by kchibisov** [comment]
The original bug here is a duplicate of #2566
