### ISSUE TITLE
can not use fcitx input in alacritty  with swaywm

### ISSUE THREAD

**Issue by alvin998179** [alacritty/alacritty#2734]
Which operating system does the issue occur on?
archlinux,Wayland
If on linux, are you using X11 or Wayland?

**Comment by alvin998179** [comment]
can use fcitx in google chrome and  sublime-text in same condition.

**Comment by kchibisov** [comment]
The input method support is not implemented in our dependencies on Wayland atm. You can run alacritty on Xwayland to make things work `env WINIT_UNIX_BACKEND=x11 alacritty`.

**Comment by alvin998179** [comment]
WAYLAND_DISPLAY= alacritty work too. But opacity=0.7 can not work. Thank you!

**Comment by yutakatay** [comment]
I want to use sway without x11 apps. `WAYLAND_DISPLAY= alacritty` or `WINIT_UNIX_BACKEND=x11 alacritty` use X11 because wl-clipboard is not working.

**Comment by tinywrkb** [comment]
I'm just dropping these here:

### Protocols

* [input-method-unstable-v2](https://github.com/swaywm/wlroots/blob/master/protocol/input-method-unstable-v2.xml)
* [input-method-unstable-v1](https://github.com/wayland-project/wayland-protocols/tree/master/unstable/input-method)
* [text-input-unstable](https://github.com/wayland-project/wayland-protocols/tree/master/unstable/text-input)

Note that I didn't read the protocols.

### Fcitx5

Fcitx5 seems to support `text-input-v3` and `input-method-unstable-v2`, but [its developer also wants](https://github.com/fcitx/fcitx5/issues/82) the following implemented and he used the word `useless` to call the current state. IDK what to about that.

* [Lack of ability of identifying different client in input-method-unstable-v2.xml](https://github.com/swaywm/wlroots/issues/2352)
* [Implement input method keyboard grab](https://github.com/swaywm/sway/pull/4932)

Fcitx5 packages are already available on Arch Linux.

### IBus

[IBus supports input-method-unstable-v1](https://github.com/ibus/ibus/tree/master/client/wayland) but sway only supports input-method-unstable-v2.  
There's an open bug report for [supporting input-method-unstable-v2 in IBus](https://github.com/ibus/ibus/issues/2182).

**Comment by LaserEyess** [comment]
This was marked as fixed but it is clearly not. `WAYLAND_DISPLAY= alacritty` and `alacritty` have two different behaviors. The IME is still only working in Xwayland.

**Comment by tinywrkb** [comment]
@LaserEyess you need [these changes](https://github.com/swaywm/sway/pull/4932) for getting this work in Sway but last time I checked, even with this, the candidate box wasn't displayed.

**Comment by kchibisov** [comment]
Ofc, because fcitx doesn't implement candidate box for wayland iirc. It works the same as X11 version on GNOME, which has support for Wayland IME the way things like ibus want from them.
