### ISSUE TITLE
Arrow keys don't work in interactive mercurial commit when run via WSL

### ISSUE THREAD

**Issue by vlovich** [alacritty/alacritty#2739]
Which operating system does the issue occur on?
Windows 10 17763 w/ WSL

Steps:
Run alacritty
run bash.exe
Go into a mercurial directory that has changes & run hg.exe commit -i

Expected:
Arrows work as they do in cmd.exe.

Actual:
If bash.exe is anywhere in the process history (e.g. bash.exe > cmd.exe > hg.exe, or cmd.exe bash.exe > cmd.exe > hg.exe, or bash.exe > hg.exe) arrow keys don't work.

To be fair the same problem appears with cmd.exe by itself.

**Comment by chrisduerr** [comment]
Are you running WinPTY or ConPTY?

**Comment by vlovich** [comment]
It doesn't matter. Both don't work. Attached my current config file but I've tried with WinPTY & ConPTY.

[alacritty.zip](https://github.com/jwilm/alacritty/files/3704286/alacritty.zip)

**Comment by chrisduerr** [comment]
This sounds like a shell issue and not related to Alacritty at all.

Does this work in powershell? cmd.exe is very outdated so I'd recommend replacing all instances of that with powershell (though even the default powershell is outdated).

**Comment by vlovich** [comment]
Yes this reproduced in powershell. In powershell it's even worse as the highlighting doesn't even appear so it's hard to see what is actually happening. This is trivially reproducible.

**Comment by chrisduerr** [comment]
This seems like it should be an issue with mercurial, if running bash anywhere in the process history screws it up this badly.

I can recommend some workarounds which might fix it for you, like running `TERM= hg`, `Term=xterm-256color hg` or `TERM=cygwin h`, just as suggestions to try and help out, but I don't think there's any way Alacritty can fix this, when the same thing happens in cmd.exe.

So this is likely something you'll have to take to either Mercurial or Windows devs I'd assume.

**Comment by chrisduerr** [comment]
Since this likely isn't an Alacritty issue and there has been no reply, I'm closing this.
