### ISSUE TITLE
SimpleFullscreen on MacOS does not get resized when Alacritty moves across screens

### ISSUE THREAD

**Issue by mirosval** [alacritty/alacritty#2741]
Which operating system does the issue occur on? macOS

When I connect/disconnect an external screen, Alacritty retains previous resolution. I think the window should be re-positioned to cover the full screen again when this happens. 

Currently I work around this by restarting Alacritty.

**Comment by kchibisov** [comment]
Are you aware of how other applications with SimpleFullcreen behave under the same conditions?

> Currently I work around this by restarting Alacritty.

FYI you can always add `ToggleSimpleFullscreen` bind to `alacritty.yml` to avoid restarts.

**Comment by mirosval** [comment]
Thanks, I added that like so:

```
  - { key: F,        mods: Command, action: ToggleSimpleFullscreen   }
```

and it works pretty well! I think it would be still cool to run that when the screen changes automatically, but this is already good enough for me.

**Comment by kchibisov** [comment]
> I think it would be still cool to run that when the screen changes automatically

I've just recommended a better work around here.

Do you now any app that behaves like you've described in simple fullscreen mode? I think following what other macOS apps are doing here is a good idea.

**Comment by chrisduerr** [comment]
I'm also curious if the whole window (including title bar and border around it) stay the old size, or if it's only the content of the window which doesn't get resized.

If the whole window stays the previous size, this will likely have to be addressed in winit.

**Comment by mirosval** [comment]
@kchibisov I think all the other apps I use don't use the simple fullscreen mode, maybe with the exception of iTerm2, that can be configured to run fullscreen and borderless.

@chrisduerr The whole window (I have no borders showing) stays the previous resolution, including the content in it, there seem to be no issues around pixel density, its always sharp.

**Comment by chrisduerr** [comment]
@mirosval If you have the Rust toolchain installed, could you try running the fullscreen example from https://github.com/rust-windowing/glutin?

You can run it using `cargo run --example fullscreen`.

To enable simple fullscreen, please apply the following patch before running it:

```diff
diff --git a/glutin_examples/examples/fullscreen.rs b/glutin_examples/examples/fullscreen.rs
index e5ab6e5..136cf72 100644
--- a/glutin_examples/examples/fullscreen.rs
+++ b/glutin_examples/examples/fullscreen.rs
@@ -6,6 +6,7 @@ use glutin::event::{
 use glutin::event_loop::{ControlFlow, EventLoop};
 use glutin::monitor::{MonitorHandle, VideoMode};
 use glutin::window::{Fullscreen, WindowBuilder};
+use glutin::platform::macos::WindowExtMacOS;
 use std::io::{stdin, stdout, Write};
 
 fn main() {
@@ -20,20 +21,11 @@ fn main() {
     stdin().read_line(&mut num).unwrap();
     let num = num.trim().parse().ok().expect("Please enter a number");
 
-    let fullscreen = Some(match num {
-        1 => Fullscreen::Exclusive(prompt_for_video_mode(&prompt_for_monitor(
-            &el,
-        ))),
-        2 => Fullscreen::Borderless(prompt_for_monitor(&el)),
-        _ => panic!("Please enter a valid number"),
-    });
-
     let mut is_maximized = false;
     let mut decorations = true;
 
     let wb = WindowBuilder::new()
-        .with_title("Hello world!")
-        .with_fullscreen(fullscreen.clone());
+        .with_title("Hello world!");
     let windowed_context = glutin::ContextBuilder::new()
         .build_windowed(wb, &el)
         .unwrap();
@@ -42,6 +34,8 @@ fn main() {
 
     let gl = support::load(&windowed_context.context());
 
+    windowed_context.window().set_simple_fullscreen(true);
+
     el.run(move |event, _, control_flow| {
         *control_flow = ControlFlow::Wait;
 
@@ -67,12 +61,10 @@ fn main() {
                         *control_flow = ControlFlow::Exit
                     }
                     (VirtualKeyCode::F, ElementState::Pressed) => {
-                        if windowed_context.window().fullscreen().is_some() {
-                            windowed_context.window().set_fullscreen(None);
+                        if windowed_context.window().simple_fullscreen().is_some() {
+                            windowed_context.window().set_simple_fullscreen(true);
                         } else {
-                            windowed_context
-                                .window()
-                                .set_fullscreen(fullscreen.clone());
+                            windowed_context.window().set_simple_fullscreen(false);
                         }
                     }
                     (VirtualKeyCode::S, ElementState::Pressed) => {
```

I'm not certain that this compiles because I currently don't have a macOS machine around. But I think it should. Please let me know if it doesn't.

**Comment by mirosval** [comment]
Ok so here's what I did:

1. Checked out master glutin
2. Applied patch
3. Fixed some compilation errors
4. Started example with (2) borderless
5. Changed screen resolution
6. Got the following: https://imgur.com/a/H37ayCn

So it would appear the issue is already not handled by glutin.

**Comment by chrisduerr** [comment]
Thanks, sorry for the compilation errors. Looks like this needs to be reported upstream.

**Comment by chrisduerr** [comment]
Created an upstream issue: https://github.com/rust-windowing/winit/issues/1118
