### ISSUE TITLE
Don't hide cursor on modifiers press

### ISSUE THREAD

**Issue by kchibisov** [alacritty/alacritty#2761]
We generally want to avoid hiding cursor on modifiers press, since most of the time, it's continuation of mouse interaction like pressing URL modifier when mouse cursor is already over URL or pressing shift in mouse mode apps.

**Comment by chrisduerr** [comment]
Generally I do think this does make some sense, however it's tough to say which modifier is actually a modifier change. Pressing lshift after rshift does not actually change modifier state for example, so we would make some assumptions here.

Generally I think it should be fine not to hide the cursor whenever a key is pressed that does not send any characters though.
