### ISSUE TITLE
Alacritty isn't properly recognized as default terminal

### ISSUE THREAD

**Issue by wight554** [alacritty/alacritty#2765]
Which operating system does the issue occur on?
Arch Linux with Xfce4
If on linux, are you using X11 or Wayland?
X11

Setting alacritty as default terminal in preferred applications has several issues
1) Alacritty is not recognized as executable when u browse /usr/bin/ (in screenshot below u can see it's missing)
![image](https://user-images.githubusercontent.com/26501410/63940436-1fcb2400-ca72-11e9-8664-0bc265c1a7b6.png)
2) When u add command manually app icon doesn't appear unlike other terminal emulator (eg kitty)
![image](https://user-images.githubusercontent.com/26501410/63940518-5012c280-ca72-11e9-9372-1f1ee06bfda1.png)
3) Using '!' (aka Run command in terminal) to run command in Whisker Menu's search fails with error below
![image](https://user-images.githubusercontent.com/26501410/63940597-85b7ab80-ca72-11e9-94b4-86a12aac8f5b.png)

Possibly there are more issues, these were main ones I've noticed
Terminal shortcut (crtl+alt+t) works just fine FYI

**Comment by wight554** [comment]
3rd issue can be fixed by  changing `alacritty "%s"` to `alacritty -e "%s"`
Found out that either kitty or alacritty are recognized as shared library in file manager but kitty still can be choosed in select application menu as executable

**Comment by chrisduerr** [comment]
If Alacritty is executable, but the filemanager doesn't recognize it as an executable, that's up to the filemanager. As long as the executable bit is set and executing works, there's nothing else Alacritty can do.

In general these errors all seem like incorrect assumptions or missing features in whatever DE you're using. So I don't think there's anything Alacritty can do about it.

Which DE is this?

**Comment by wight554** [comment]
DE is XFCE4
Missing icon is likely lack of icon of size that menu requires
Wonder how DE specific terminal handles shortcuts for such menus

**Comment by chrisduerr** [comment]
>  Missing icon is likely lack of icon of size that menu requires

Alacritty provides the icon as SVG. SVGs can't be the incorrect size.

As far as I know, these are not an issue with any other DE. So if other DEs can do it, I'm confident XFCE should be able to do it too.

**Comment by ManuelBarrioLinares** [comment]
> `alacritty -e "%s"`

Thanks, this fixed changind the default Manjaro XFCE4 terminal to alacritty.

**Comment by eskoONE** [comment]
> > `alacritty -e "%s"`
> 
> Thanks, this fixed changind the default Manjaro XFCE4 terminal to alacritty.

didnt work for me, manjaro xfce 20.01.

i stumbled upon something else though. when setting preferred terminal emulator to alacritty on xfce, the icon isnt set unless i set it to Alacritty with a capital "a", which in return wont start the emulator if started with terminal emulator shortcut, because it doesnt recognize it as an applicatoin that it can run. 

it works when its a small "a" but some applications relying on starting commands through the preferred emulator wont work.

im not sure if this helps in any way, but thought it might help track down the issue.

**Comment by chrisduerr** [comment]
@eskoONE Which version? This should have been fixed in 0.4.2. I'd assume you might be talking about [this](https://github.com/alacritty/alacritty/pull/3425).
