### ISSUE TITLE
Font rendering issue with fractional size

### ISSUE THREAD

**Issue by cynecx** [alacritty/alacritty#2780]
System:

```
alacritty@db63c3155 (master)
Linux 5.2.11-arch1-1-ARCH
rustc 1.39.0-nightly (c6e9c76c5 2019-09-04)
freetype2 2.10.1-1
Gnome 3.32 on X11
Font: monospace = Hack Regular
```

This issue happens with font `size: 9.5` on `Hack Regular`:

Alacritty:

![Screenshot from 2019-09-05 23-32-05](https://user-images.githubusercontent.com/5961244/64382211-618d3900-d035-11e9-99d1-a5e81601c2a7.png)

Two nits:
1) the `i` in `.../dev/alacritty` seems weird because of the `fused` dot above the i.
2) the letters `b, l, d, ...` is one pixel shorter compared to gnome-terminal.

gnome-terminal:

![Screenshot from 2019-09-05 23-34-56](https://user-images.githubusercontent.com/5961244/64382344-c9438400-d035-11e9-901f-ac1840304092.png)

EDIT: it seems somehow that the overall height is "wrong"? this might explain the fused dot in the letter i.

**Comment by chrisduerr** [comment]
> it seems somehow that the overall height is "wrong"

You can change the glyph height in the terminal, however I don't think that's causing the differences.

If you switch it to `9` or `10`, does it look the same way as gnome terminal then?

**Comment by cynecx** [comment]
Alacritty (size=9):

![Screenshot from 2019-09-06 00-02-17](https://user-images.githubusercontent.com/5961244/64386500-98fde480-d039-11e9-9377-0621e699f15d.png)

Looks more sharp. Seems that the height is the same as with gnome-terminal, however the letters seem "cramped" together.

Alacritty (size=10) looks significantly larger so I've uploaded an image for that.

I am wondering how is it that size 9.5 has "smaller" font than with size 9?

**Comment by chrisduerr** [comment]
Well it's possible that gnome just doesn't do the fractional sizing and that Hack has troubles rendering at that specific size.

Spacing between grome and Alacritty might be slightly different depending on how Gnome's text layout works (I think it supports proportional fonts?), so it's perfectly normal that there might be differences. If you dislike the way that Alacritty spaces the glyphs, you can change that in the `font` config though.

**Comment by cynecx** [comment]
Well, It's not just gnome. It's chromium, vscode, and everything else xD. They all render the "same". alacritty with 9.5 size actually matches the other but the issue is really just that letter like "b, l, i" are one pixel short in height.

But yeah, I will stick with 9.0 for now with offset.x = 1, that seems to reduce spacing between the letters.

**Comment by chrisduerr** [comment]
Chromium, vscode are all the same. I think on Linux it even uses the same stuff to render text as gnome (pango). So of course it looks the same there. Also all these programs do proportional text layout.

**Comment by cynecx** [comment]
Re-opening this issue because I may have found a fix yesterday. PR will come up shortly.
