### ISSUE TITLE
Key repeat cancelled by previous key's release event

### ISSUE THREAD

**Issue by jayache80** [alacritty/alacritty#2788]
Which operating system does the issue occur on?
macOS 10.14.6

If on linux, are you using X11 or Wayland?
N/A

I just started using alacritty for the first time, alacritty 0.3.3 with the default config, and I noticed behavior that I find undesirable in `vim` detailed below.

When holding down `j` to move the cursor down through the document, then holding down `k` to move the cursor up without having released `j`, then later release `j`, the action of moving the cursor up (by holding `k`) will be cancelled by the event of releasing `j`.

The same behavior would be observed if you swap `j` and `k`, that is, start moving the cursor up by holding `k`, then start moving the cursor down by holding `j` but without releasing `k`, and watch the downward movement be cancelled when `k` is eventually released.

Is there a setting somewhere I missed? Granted, this is a nitpick, but my fingers like to "overlap" when moving cursors, scrolling, etc., and I don't notice this issue in any other terminal emulator I use.

An interesting clue, perhaps, is this: I do notice this happening in the horizontal variety by holding `l` to move the cursor right, then holding `h` to move left, and finally releasing `l` cancels `h`'s leftward movement, but *the opposite is not true: starting by moving the cursor left by holding `h`, then holding `l` to go right, and finally releasing `h` does **not** cancel `l`'s rightward movement as in the above cases.*

Another datapoint: this "previous repeated key's release cancelling the current repeated key's action" also happens in the same combination cases mentioned above on the regular input on `bash`, and the same `j/k` cases in `less` as well.

**Comment by kchibisov** [comment]
Would you mind trying this PR #2438? I can't repro it on linux btw and the behavior seems like a bug in our dependencies.

**Comment by jayache80** [comment]
Thanks for the response. I did a build of the latest on chrisduerr:evlp2
```
$ ./alacritty --version
alacritty 0.3.3 (c13b294)
```
and I noticed that the same behavior is present. I also had the opportunity to hop onto another mac, also running Mojave 10.14.6 and installed the standard alacrity 0.3.3 (via homebrew) and saw the same behavior.

**Comment by chrisduerr** [comment]
This is the case with all applications on all platforms. It's completely unrelated to Alacritty, this is just how key repetition works.

You can test this in Firefox or the macOS terminal, you'll see it has the same behavior.

**Comment by jayache80** [comment]
> This is the case with all applications on all platforms

Huh? Literally all other boxes that let you type stuff do not exhibit this "previous repeated key release cancelling the next repeated key action" behavior. It's jarring.

This is not the behavior of:
Terminal.app
iTerm2.app
Hyper
LXterminal (on LXDE environment)
Windows Command Prompt

Those are just the terminals I had handy. This is definitely a bug.

While it may not be a big issue to some, it's the difference between me, and likely others, of using this terminal emulator.

**Comment by jayache80** [comment]
![terminal vs alacritty](https://user-images.githubusercontent.com/15721514/64510530-3c980080-d297-11e9-89ed-e9a13c56fa85.gif)

**Comment by chrisduerr** [comment]
Oh, my bad. I think I've misunderstood your issue.

You don't want `j` to start again after typing `k`, but you want `k` to keep going if you release `j`, right?

I thought you were talking about something different. However, I can not reproduce this on the latest version of #2438.

**Comment by chrisduerr** [comment]
Could you provide some more information about the hardware you're running? I can't reproduce this on any of my machines, including a 2018 MBP.

**Comment by jayache80** [comment]
> but you want `k` to keep going if you release `j`, right?

Correct

> Could you provide some more information about the hardware you're running?

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro14,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  Boot ROM Version:	198.71.1.0.0
  SMC Version (system):	2.45f0

  System Version:	macOS 10.14.6 (18G87)
  Kernel Version:	Darwin 18.7.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
  Computer Name:	
  User Name:
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
  Time since boot:	10:18

```
$ otool -L target/release/osx/Alacritty.app/Contents/MacOS/alacritty
target/release/osx/Alacritty.app/Contents/MacOS/alacritty:
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 946.0.0)
	/System/Library/Frameworks/CoreText.framework/Versions/A/CoreText (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1671.60.107)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1575.17.0)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1265.9.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1575.17.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
	/System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo (compatibility version 1.2.0, current version 1.5.0)
	/System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore (compatibility version 1.2.0, current version 1.11.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 50.1.0)
```

Any specific diagnostic information I can provide?

**Comment by chrisduerr** [comment]
Which shell are you running? Maybe that's related.

I'd be curious if anyone else can repro this.

**Comment by jayache80** [comment]
```
$ echo $0
-bash
```
```
$ bash --version
GNU bash, version 5.0.7(1)-release (x86_64-apple-darwin17.7.0)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
```

Same behavior in `zsh` and `ksh`. Saw the same behavior on 3 different MacBook Pro's.

**Comment by chrisduerr** [comment]
Do you use the US keyboard layout?

**Comment by jayache80** [comment]
Yes
![Screen Shot 2019-09-09 at 12 56 23 PM](https://user-images.githubusercontent.com/15721514/64562198-49513e80-d301-11e9-9f6d-2a2f1860b3a8.png)

**Comment by chrisduerr** [comment]
Hmm, strange. Would be very interesting if anyone else could repro this just to have a bit more insights into what might be relevant to run into this.

**Comment by baileyn** [comment]
I've successfully reproduced this on MacBook Pro 2018 running Catalina.

It seems that sometimes it'll continue repeating the key but other times releasing the previous key causes it to stop. Notice how going from j->k stops the repetition but from k->l doesn't. Through further testing, I can't get any combination of letters to get the 'l' to stop repeating. It seems like only a select few characters are affected.

![display](https://user-images.githubusercontent.com/6194343/64916552-3ef1d300-d74d-11e9-8cca-4d523a6c0d61.gif)

**Comment by marcomayer** [comment]
I have the same issue trying out alacritty coming from iterm2. Wondering why this doesn't get more attention, no alacritty users who're using vim? ;)

**Comment by kchibisov** [comment]
@marcomayer This issue is specific to macOS, however `alacritty` users are also on Wayland,X11 and Windows. I can say for sure that this behavior is not a thing on Wayland and X11 at least. I also feel like this can be reproduced by some part of macOS users, while the others are fine here or don't matter this behavior. I personally don't remember this behavior in `alacritty`, when I've tried macOS last time.

**Comment by chrisduerr** [comment]
Yes, as mentioned I cannot repro on my macbook at all for example. So even if this had a higher priority and we wouldn't have BSD/Linux/Windows too, I need to be able to reproduce to fix this.

**Comment by jayache80** [comment]
I’m almost certain the problem is upstream in macOS winit. Did you see my comment on https://github.com/rust-windowing/winit/issues/1267 ?

**Comment by chrisduerr** [comment]
@jayache80 Yeah, I saw that when you wrote it, thanks. Most keyboard input issues are related to winit, though that doesn't help much until we can reproduce and verify it.

**Comment by marcomayer** [comment]
> Yes, as mentioned I cannot repro on my macbook at all for example. So even if this had a higher priority and we wouldn't have BSD/Linux/Windows too, I need to be able to reproduce to fix this.

I see, thanks for responding. Maybe it's related to the keyboard settings on MacOS, I've set both "Key Repeat" and "Delay until Repeat" to the max (right). Then simply go to Alacritty press and hold "h" for example and after a few seconds stop pressing "h" and start pressing and holding "l". If that works, stop holding "l" and now switch to "h" again. Etc...but I can imagine this to be a tough one to fix.

**Comment by jayache80** [comment]
I built the master branch of alacritty using a winit patch of https://github.com/rust-windowing/winit/pull/1489 and it fixed this issue for me.

**Comment by jayache80** [comment]
This issue would be resolved by https://github.com/rust-windowing/winit/pull/1449

**Comment by jayache80** [comment]
I reopened rust-windowing/winit#1488 which would fix this bug. I had closed it because rust-windowing/winit#1449 would also fix it, but that's addressing lots of other stuff and has yet to come into fruition.

**Comment by jayache80** [comment]
Ok, rust-windowing/winit#1489 got merged. So now we just have to wait until a new winit release, and alacritty's dependencies get updated to use that release.

**Comment by jayache80** [comment]
I'm happy to report that the alacritty master branch contains 4c6a763850a5dec0fa34d15e356dcba19875690a which happened to update the winit dependency to 0.26.0 (which contains the fix that resolves this issue). If you don't mind, I'm closing this now.
