### ISSUE TITLE
Support custom URL matching

### ISSUE THREAD

**Issue by schroederc** [alacritty/alacritty#2792]
It'd be nice to support full configuration of the URL matching like urxvt-matcher for custom user URLs with a different scheme (https://github.com/chrisduerr/rfind_url/blob/master/src/lib.rs#L53) or possibly without a scheme at all.

**Comment by chrisduerr** [comment]
What for?

**Comment by schroederc** [comment]
Links in our documentation/code are often shortened to not include a URL scheme, but there are common hostnames that can be matched against to find URLs that should be linked.  One example is the `b/` prefix for issues: https://github.com/bazelbuild/bazel/blob/master/scripts/bootstrap/compile.sh#L398.  Obviously not all users will want to match `b/\d+` as a URL, but at least thousands of engineers would if they were using Alacritty.

**Comment by chrisduerr** [comment]
Parsing arbitrary regexes would be far worse for performance than what we do right now, which is why this is not supported. It's also questionable how nested URLs would be parsed reliably in reverse without even further performance penalties.

I'm not sure if there's an acceptable compromise as a middle ground here. It seems like double-clicking with semantic expansion should already work pretty well. Alternatively in the future we plan to allow selection using the keyboard, that would likely make working with these 'URLs' easier too.

**Comment by ianks** [comment]
I would love to have this to open files from the terminal, similar to VScode. For example, if a test fails and shows a stack track, having the ability to click it and open with $EDITOR would be incredible.

**Comment by ddevault** [comment]
I would also like to be able to make use of other URLs, such as gemini://, irc://, mailto:, file:, etc.

**Comment by kchibisov** [comment]
>I would also like to be able to make use of other URLs, such as gemini://, irc://, mailto:, file:, etc.

For the urls you've mentioned only `irc` is lacking. The currently supported urls as of the version `0.5.0` are `http, https, ftp, file, mailto, news, gemini, git, gopher, ssh`.

**Comment by ddevault** [comment]
Hm, a whitelist doesn't seem great.

**Comment by kchibisov** [comment]
>Hm, a whitelist doesn't seem great.

Yeah, we want eventually move to a more general solution for matching random things in a terminal outside of urls. We already have some infrastructure internally due to recent regex buffer search, just need to wire urls detection into the same infra instead of using hand written automata.

**Comment by chrisduerr** [comment]
Currently the plan for this issue from my side is to support arbitrary regexes and then do post processing for things like parenthesis. That's probably going to be slightly less efficient than the current parser, but with the correct post processing heuristics it will hopefully give equal matching results while allowing anything to be detected as a URL. But it should allow recognizing basically everything as "URLs" and would also make it possible to do a bunch more stuff than just URL opening with separate launchers for each regex.

**Comment by ianks** [comment]
> Currently the plan for this issue from my side is to support arbitrary regexes and then do post processing for things like parenthesis. That's probably going to be slightly less efficient than the current parser, but with the correct post processing heuristics it will hopefully give equal matching results while allowing anything to be detected as a URL. But it should allow recognizing basically everything as "URLs" and would also make it possible to do a bunch more stuff than just URL opening with separate launchers for each regex.

Awesome! If the processing could happen asynchronously, performance shouldn’t be too much of a concern anyway. Thanks for this!

**Comment by chrisduerr** [comment]
> Awesome! If the processing could happen asynchronously

It can't. We need to update things immediately. Updating URL highlights multiple frames late is not an option, that's slow.

**Comment by sitch** [comment]
For opening files, one idea would be to set an alacrity specific PATH variable as I imagine most users code out of a single high level folder?.  This could spawn an async fsevents handler to maintain a file system trie.  That way you'd get amortized O(1) evals allowing high performance sync processing.

I'd be happy to run a background daemon for this

However, this might just be something better done on the user side with hints...

**Comment by chrisduerr** [comment]
> as I imagine most users code out of a single high level folder?

That would **really** surprise me. In fact I'm not aware of anyone that does so.

I also see absolutely no point in anything you're suggesting.

**Comment by sitch** [comment]
Preface: My sole interest in click to open file is for working in active development folders

> > as I imagine most users code out of a single high level folder?
> 
> That would **really** surprise me. In fact I'm not aware of anyone that does so.

Placing repos you're actively developing in random folders all over the file system vs common paths like `/opt`, `$HOME` or `/usr/local` -- **that** seems surprising.  But even still you could just append them to this `ALACRITTY_FILE_WATCH_PATH`

Also, I just suggested this as one way to get constant time eval performance. This is how some IDE's like vscode handle managing the fs tree.  

> I also see absolutely no point in anything you're suggesting.

Seems like you don't appreciate ideas being shared here -- Guess I'll stay out of this repo :wave:

**Comment by chrisduerr** [comment]
There's no need to "manage the fs tree". It seems like you're severely misunderstanding what this issue is about.

**Comment by MyIsaak** [comment]
> I would love to have this to open files from the terminal, similar to VScode. For example, if a test fails and shows a stack track, having the ability to click it and open with $EDITOR would be incredible.

Is this still going on? Or am I missing configuration to enable this feature. I would love to contribute to this if that's okay with the maintainer.

**Comment by kchibisov** [comment]
See

https://github.com/alacritty/alacritty/blob/1df32309fe69d4e8113813a3e9049a7039650f44/alacritty.yml#L506

**Comment by MyIsaak** [comment]
Thanks! Almost suits my needs except for 2 issues (please correct me if I'm wrong):
1. Commands aren't executed from the working directory (instead relative to the alacrity program).
2. Commands don't log to `stdout` instead to `/dev/null` (makes it hard to debug my configured regex hints).

**Comment by kchibisov** [comment]
I think master has the first issue resolved.

**Comment by MyIsaak** [comment]
I got some sort of setup working with relative paths for `.rs` files. But I can't open vim as a command without opening a new window (probably because it's spawned as a child process). I had some idea of reopening alacritty with with `--embed <window-id>` flag, but without any success (don't know why because I don't get any feedback to stdout).
