### ISSUE TITLE
Edges of display are cut off when using Windows 10 (Dell XPS 15 9550 with 4k 15" display at 200% zoom)

### ISSUE THREAD

**Issue by alexschneider** [alacritty/alacritty#2801]
I just installed alacritty through scoop and the image below is what I see:

![image](https://user-images.githubusercontent.com/5846376/64925343-e994e080-d7a3-11e9-8ea4-850cb8831cd2.png)

**Comment by chrisduerr** [comment]
Does this work correctly at 100% zoom? And does #2438 fix this issue?

**Comment by alexschneider** [comment]
I tried changing to 100% zoom and the app still looks the same. Not sure if #2438 fixes this - are there any binaries I can try out to test?

**Comment by chrisduerr** [comment]
> are there any binaries I can try out to test?

There are not, you'd have to compile it from source to test.

**Comment by chrisduerr** [comment]
The latest version is available now, including these changes. Could you re-test?
