### ISSUE TITLE
Linux: Color for current folder not changable

### ISSUE THREAD

**Issue by matu3ba** [alacritty/alacritty#2828]
# System
Linux 4.19 LTS, Rust stable 1.37.0 , X11 X.Org version: 1.20.5

# Summary
On changing normal or bright color white, I do expect a change of the color mapping in the shell. Like the current folder should be not white anymore.

# Behavior
No color change.

# Expectation
The color should change not being white.

# Extra
Do you only support the color schemes noted in the wiki? None of them has a whitish-grey background.

Reproduce with:
colors:
    primary:
      background: "0xFFFFFF" ##<----------
      foreground: "0x000000"
    normal:
      black:      "0x000000"
      red:        "0x660000"
      green:      "0x006600"
      yellow:     "0x666600"
      blue:       "0x000080"
      magenta:    "0x660066"
      cyan:       "0x005f66"
      white:      "0x808080" ##<----------
    bright:
      black:      "0x333333"
      red:        "0x990000"
      green:      "0x00A600"
      yellow:     "0x999900"
      blue:       "0x0000B2"
      magenta:    "0xB200B2"
      cyan:       "0x00A6B2"
      white:      "0x999999" ##<----------

![ChangingWhiteNotPossible](https://user-images.githubusercontent.com/13089667/65726700-f8d63100-e0b5-11e9-9a49-c97f174f0a3d.png)

**Comment by chrisduerr** [comment]
The text is rendered in the `foreground` color. Which in your case is `0x000000`, making it black. As far as I can tell, all the options are set the way you've specified them in the config.

> Do you only support the color schemes noted in the wiki?

No, we support whatever colorscheme you want to use, the ones in the config are just the ones people have made wiki entries for.

**Comment by matu3ba** [comment]
Yes, the text is correct, but left of the cursor the current folder is in crystal white, although I did configure white "darker" via white: "0x808080" ##<----------.
I am not exactly sure how the mapping of colors is done, since it is not documented in the wiki.

**Comment by kchibisov** [comment]
@matu3ba fyi we have this interesting [behavior](https://github.com/jwilm/alacritty/blob/87cf14a4b79146240b74ab473faf542b72e5e939/alacritty.yml#L192) by default. if your current fold is *bold* and *white* it'll be drawn in brightwhite and not white. maybe that's the case why you can't.

Normal (Standard) colors - (0-7), bright (high intensity) is (8-15), for 256 color mode.
For 8 bit mode: normal (30–37), bright (90–97) maybe not super precise, but should be enough for basic understanding.

more information about colors in terminal https://misc.flogisoft.com/bash/tip_colors_and_formatting

**Comment by kchibisov** [comment]
If the color of `folder` isn't changeable it's likely set by `LS_COLORS` somewhere to a be an index color or something else. You can `echo $LS_COLORS` to take a look on it. Feel free to ask here, if you still have problems.

**Comment by chrisduerr** [comment]
Also important to know that if your distro uses `dircolors`, that it is buggy. You should use `LS_COLORS` instead.
