### ISSUE TITLE
Crashes system during build 274/275

### ISSUE THREAD

**Issue by j3st3r-LulzSec** [alacritty/alacritty#2835]
Which operating system does the issue occur on? linux / debian

If on linux, are you using X11 or Wayland?
X11
When building on very last step 274 out of 275 whole laptop freezes up can't complete the build

**Comment by chrisduerr** [comment]
How much RAM does your system have? Rust takes quite a bit of resources.

**Comment by kchibisov** [comment]
As it was indirectly noted, that you're running out of memory during build. If you still have problems with building, feel free to ask here, generally you can just temporary create a swap file.
