### ISSUE TITLE
alacritty doesn't close unless it is visible on sway

### ISSUE THREAD

**Issue by VichoReyes** [alacritty/alacritty#2851]
Which operating system does the issue occur on? sway on Arch Linux

If on linux, are you using X11 or Wayland? Wayland

How to reproduce: Run a command like "sleep 3 && exit" and then either:
- switch to another workspace
- open another window using a tabbed layout

You'll see alacritty doesn't close itself after 3 seconds, like it should, until it is visible again.

**Comment by kchibisov** [comment]
I can repro on #2438 + sway.

**Comment by for-coursera** [comment]
If I understand this correctly, I can repro this on 3475e44 on macOS 10.11, by just switching to another application. As you may see on this gif, Alacritty's window closes only when I move cursor back to it: https://i.imgur.com/dKx5XP5.gif

**Comment by kchibisov** [comment]
@for-coursera I think its a different one, would you mind trying to repro on `v0.3.3`?

**Comment by for-coursera** [comment]
You mean downloading 0.3.3 release (cc3e4d3), and not the latest master, which I did test it on?

**Comment by kchibisov** [comment]
yep, since I think it's a recent regression in your case.

**Comment by for-coursera** [comment]
@kchibisov You are right indeed, it closes just fine in 0.3.3 release. Hope this will be brought back :)

**Comment by Tacklebox** [comment]
@kchibisov I think it is the same regression on sway

On sway version 1.2 (Sep 26 2019, Arch Linux) and alacritty 0.3.3 it works correctly.

If I sleep && exit, switch to another workspace and wait. the workspace I left alacritty on disappears (alacritty was the only thing open in it) after the sleep elapses.

**Comment by kchibisov** [comment]
@Tacklebox I can repro this issue on `v0.3.3` and the original one was also spotted on master. sway version 1.2-d19f4f7b (Oct 16 2019, branch 'master'). So, I'm not sure that it's a regression, if it was the same one, then I should be able to repro it on Windows/X11, however I can't.

**Comment by kchibisov** [comment]
Upstream bug https://github.com/rust-windowing/glutin/issues/1231.

@for-coursera Please, open a separate issue for macOS, since this bug is a Wayland specific one.
