### ISSUE TITLE
Disable stencil/depth buffers

### ISSUE THREAD

**Issue by chrisduerr** [alacritty/alacritty#2881]
Currently Alacritty initializes both the depth and stencil buffer, which leads to additional video memory usage.

This has been disabled in 3475e449870b382cda4ea6d48f980577cd8c929e, however some X11 setups had issues with this and it lead to Windows getting initialized with garbage on newer amdgpu Systems.

Because of this the commit has been reverted in https://github.com/jwilm/alacritty/pull/2882.

Some additional info can be found in https://github.com/jwilm/alacritty/pull/2875.

**Comment by kchibisov** [comment]
Should probably retest it with the latest glutin, by simply requesting 0 for both. However I think it could cause issues on windows or there might be no format without them...
