### ISSUE TITLE
DPI/scaling cannot be changed dynamically/without restart.

### ISSUE THREAD

**Issue by frebib** [alacritty/alacritty#2886]
Running latest HEAD at time of writing, X11 on Linux.

I work a lot both docked and undocked, and depending on where I am I adjust the DPI of my display to suit. Using `xsettingsd` and my [handy DPI script](https://gist.github.com/frebib/0703227f47358e867e09f02c872425ff/raw) for adjusting X11 DPI on the fly, I can get on just fine. Many (GTK-based) applications, including other vte based terminal emulators, implement the xsettings protocol and change their DPI when asked to.

I can't seem to work out how to get Alacritty to change the scale/dpi without restarting each terminal instance. I'd like to be able to replicate the same "change dpi at will" functionality as I can with most other windows.

**Comment by chrisduerr** [comment]
Reported upstream in https://github.com/rust-windowing/winit/issues/1228.

**Comment by iasd893jkd** [comment]
Similar boat here. Ubuntu 22.04, X. I opened up an Alacritty terminal when running high dpi mode (laptop screen only) then I plugged in my monitor which lowers the resolution on both the laptop and the monitor, and now the fonts are huge. The mouse cursor when hovering the terminal is also huge. 

It seems that Wezterm the fonts auto adjust in this situation somehow. Wezterm is also hit by the cursor issue though. I didn't reallize the cursor was still an issue when I started writing this message. I wonder if Wezterm is manually adjusting font size?

I don't know if Alacritty and Wezterm can actually be compared here, I just mention it because they both use Rust.

**Comment by jfly** [comment]
For the record, https://github.com/rust-windowing/winit/commit/266219f27f9c72a5512a4a053dba70b6ba607084 just landed in [winit 0.29.4](https://github.com/rust-windowing/winit/commits/v0.29.4), which I believe is supposed to fix this. Alacritty recently updated to winit 0.29.4 in https://github.com/alacritty/alacritty/commit/3bb4fb78b4e433c6176fa4422134e38fecc9ede3. However, I tried building the latest version of Alacritty master (54889fc4ff117f59efb392955a18b414fee570c7 at time of writing), and I do not see alacritty responding to x11 dpi change events via xsettingsd.

I haven't dug into this at all. @kchibisov, your name shows up on both commits. Do you have any insight here? Happy to debug further if you can point me in a useful direction.

**Comment by kchibisov** [comment]
>I haven't dug into this at all. @kchibisov, your name shows up on both commits. Do you have any insight here? Happy to debug further if you can point me in a useful direction.

I just acked the X11 code, since I don't use it particular. But I guess this was all about window property, not X settings one. Maybe I'm wrong. You could try `x11trace` stuff.

**Comment by jfly** [comment]
For the record, the upstream issue [just got reopened](https://github.com/rust-windowing/winit/issues/1228#event-11329398978), so hopefully we'll see a fix over there.

**Comment by jfly** [comment]
For anyone following this issue: the upstream winit issue [just got re-reopened](https://github.com/rust-windowing/winit/issues/1228), hopefully we'll see a fix over there. @kchibisov, it would be nice to reopen this one as well just for bookkeeping.

**Comment by frebib** [comment]
I just tested https://github.com/rust-windowing/winit/pull/3423 and it works great 🎉 
Once winit is bumped again, this can be closed for good

**Comment by frebib** [comment]
This can be closed. Fixed as of 37349c4566a1431b5becbb649dec536ecbe18e71

**Comment by asch** [comment]
Dynamic scaling stopped working with 0.15.1. Any idea what could went wrong?

**Comment by kchibisov** [comment]
nothing really changed, unless you're not on X11 for whatever reason.
