### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by jeunggu** [alacritty/alacritty#2913]
debian version 10.1

error: enum variants on type aliases are experimental
  --> /home/redbird/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-deb-1.22.0/src/compress.rs:17:13
   |
17 |             Self::Gz(data) => &data,
   |             ^^^^^^^^^^^^^^

error: enum variants on type aliases are experimental
  --> /home/redbird/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-deb-1.22.0/src/compress.rs:18:13
   |
18 |             Self::Xz(data) => &data,
   |             ^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

error: failed to compile `cargo-deb v1.22.0`, intermediate artifacts can be found at `/tmp/cargo-installNY8NKS`

Caused by:
  Could not compile `cargo-deb`.

**Comment by chrisduerr** [comment]
Which version of Rust are you using? This sounds like your Rust version is too old.

**Comment by chrisduerr** [comment]
Likely an issue with outdated Rust version. Let me know if that does not fix it for you.
