### ISSUE TITLE
Synchronize updates with terminal clients

### ISSUE THREAD

**Issue by jasin** [alacritty/alacritty#2919]
Which operating system does the issue occur on? Windows 10

Simply put when I am running tmux in split pane and I have a large file open during scroll as I hit the bottom or top and the text starts to scroll I get weird line redraws in the opposite pane. 
Sometimes this is just flickering, sometimes weird text gets deposited in the opposite pane of nvim.

I've tested this over ssh, locally, with tmux, screen using vim , nvim. The only common denominator is alacritty. I can confirm that using the default term that comes with WSL does NOT have the issue. 

env $TERM = xterm-256color in alacritty and tmux. changing the tmux term doesn't fix the issue. tmux-256color actually breaks alacritty, but thats not relevant here. 

If and when I figure out how to cap a screen video I will post it here.

**Comment by kchibisov** [comment]
Could you try `alacritty` terminfo? Also set terminfo to `tmux-256color` in tmux
`set -g default-terminal tmux-256color`.

**Comment by jasin** [comment]
how would I go about using alacritty terminfo on windows?

using tmux-256color inside of tmux actually breaks alacritty worse.
Text becomes yellow and backspace does not seem to work. If I could get $TERM set to alacritty that might help, but I've been unable to at this point.

I should also add that using WinPTY or ConPTY doesn't matter.

**Comment by kchibisov** [comment]
Is that correct that your terminfo outsize tmux is `xterm-256color` and inside it it's `tmux-256color`, does this break alacritty, right?

**Comment by jasin** [comment]
Line 209 is a prime example of what happens. lines get redrawn, they usually flicker but sometimes that leave this type of artifact.

https://ibb.co/b67Lz2J

outside of tmux
```
jasin@minecraft:~ » echo $TERM
alacritty
```
inside tmux
```
jasin@minecraft:~ » echo $TERM
tmux-256color
```
I found the terminfo files and added them. 

my .tmux.conf
```
jasin@minecraft:~ » cat .tmux.conf
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",alacritty:Tc"
```

**Comment by kchibisov** [comment]
What's your tmux version?

**Comment by kchibisov** [comment]
Does your issue sounds related to https://github.com/jwilm/alacritty/issues/2632 ?

**Comment by jasin** [comment]
it may be loosely related. My issue is more than just one character and only happens when scrolling in nvim/vim or another cli app like less

locally tmux -V 2.6
over ssh tmux -V 2.8

I will see what tmux 3 when I can get it installed

**Comment by jasin** [comment]
I installed tmux 3 rc5 and the problem persist

**Comment by kchibisov** [comment]
what's your `tabspace` value?

**Comment by jasin** [comment]
tabspaces for what? nvim?
How does that affect less?
```
set expandtab 
set autoindent  
set softtabstop=4 
set shiftwidth=4 
set tabstop=4
```

**Comment by jasin** [comment]
in alacritty.yml
```
# Spaces per Tab (changes require restart)
#
# This setting defines the width of a tab in cells.
#
# Some applications, like Emacs, rely on knowing about the width of a tab.
# To prevent unexpected behavior in these applications, it's also required to
# change the `it` value in terminfo when altering this setting.
tabspaces: 4
```

**Comment by kchibisov** [comment]
fyi if you're changing tabspace value you should also update all your terminfo, so stick it back to default otherwise.

**Comment by chrisduerr** [comment]
Yeah, using `tabspaces: 4` **will** break things if you don't know what you're doing. Especially in ncurses applications.

Involvement of unicode characters could also create troubles, can you share a screenshot of the issue?

**Comment by jasin** [comment]
screen shot is linked up above. I've changed the tabspaces value back and commented it out for good measure, restarted alacritty. Still present

**Comment by chrisduerr** [comment]
Thanks, didn't see that.

Which Alacritty version are you running? Would it be possible to test the latest master if you're running 0.3.3?

**Comment by jasin** [comment]
here is a sample video, while changing out to alacritty terminfo and tmux-256color terminfo has helped (don't get artifacts), the same thing happens. I don't think scrolling in one pain should affect the other pane.

https://vimeo.com/368903390

**Comment by kchibisov** [comment]
Just for understanding. We don't know anything about tmux panes, etc. Tmux is a terminal emulator itself. We just draw characters etc here. The glitch your seeing is probably because we're drawing too fast ( I have some flickers in `htop` sometime, which doesn't appear in debug more for e.g.).

**Comment by jasin** [comment]
I know its using ConPTY because I have true color support.

I still think its a bug, wsl.exe(default term) does not exhibit the behavior using the exact same setup. But if that's where you want to leave this report, that's fine

**Comment by kchibisov** [comment]
@jasin wsl.exe probably is just slower to render things, but I'm fine with keeping it around.

**Comment by chrisduerr** [comment]
That does look like an issue with redrawing faster than the application expects. Trying the latest master might help though, but I wouldn't be surprised if it doesn't.

In your video this is just about intermediate flickering, does this actually persist? Your screenshot looks like that was a still frame. If it persists while the output isn't updating anymore, it definitely wouldn't be an issue with redrawing too quickly.

**Comment by dnkl** [comment]
Jumping in here... I've been working on a terminal emulator on my own (sorry Alacritty!) and had this exact problem. But let's rephrase it a bit; its the clients that are "drawing" too slow. At least that was my conclusion.

I had flickering everywhere; less, emacs, vim and so on. What we perceive as a single operation (for example: scroll up) are often multiple operations (set scrolling region, scroll up, reset scroll region, redraw X number lines, for example). These are often **not** written in a single `write()` call. So, we may end up reading parts of that operation, resulting in flicker when we get the last data from the client and re-render in the next frame(s). Key here is that the last parts of that "operation" is coming "soon".

I came up with this workaround:

Delay rendering after receiving input from the client (yes, this is in the opposite direction of https://github.com/jwilm/alacritty/issues/673).

To handle various clients behaving slightly differently, and to prevent rendering from being delayed indefinitely, I added a **mininum** and **maximum** delay. The mininum delay is small (currently 1ms), but could be smaller) and is **reset** each time we receive client input. The maximum (currently 16ms - ~1 frame assuming 60Hz) delay is only reset when we actually render. Thus, rendering is delayed for **at least** 1ms and can be delayed further if we receive more client input before that. But only up to one frame.

This is obviously a compromise between input latency and "smooth" rendering (for lack of a better word), but the solution above works well enough for me at least.

Anyway, sorry if this is just noise.

**Comment by chrisduerr** [comment]
> I had flickering everywhere; less, emacs, vim and so on. What we perceive as a single operation (for example: scroll up) are often multiple operations (set scrolling region, scroll up, reset scroll region, redraw X number lines, for example). These are often not written in a single write() call. So, we may end up reading parts of that operation, resulting in flicker when we get the last data from the client and re-render in the next frame(s). Key here is that the last parts of that "operation" is coming "soon".

That is correct and an issue that exists on both sides. We've previously written with the `write!` macro for example, which can split up the data and we had to switch to `write_all` to prevent neovim from incorrectly interpreting partial escapes.

I've never encountered these problems myself though, so it might depend a bit on the system used. I don't think adding latency is a great solution to this, though I can see why it might be the easiest fix.

**Comment by kchibisov** [comment]
I agree with @chrisduerr here, adding latency is not an option. even dynamic latency is not an options and could incorrectly "improve throughput" by running your vte parse more than needed, instead of drawing as fast as you can. The only option to solve this problem is to developed some kind of synchronization mechanism between clients and terminals in most terminals emulators and try make clients to use it.

This thing is already proposed in https://gitlab.freedesktop.org/terminal-wg/specifications/merge_requests/2 , which could be supported by alacritty, in case it'll be accepted to help with this issue.

**Comment by chrisduerr** [comment]
I don't think we have any other issue for this, so let's use this one to track the development and implementation of the protocol.

**Comment by chrisduerr** [comment]
Closing in favor of the older #598.
