### ISSUE TITLE
Alacritty sluggish, input delay

### ISSUE THREAD

**Issue by rislah** [alacritty/alacritty#2982]
Which operating system does the issue occur on?
Linux
If on linux, are you using X11 or Wayland?
X11

Alacritty makes bold claims of being the fastest terminal emulator in existence, however I don't feel it. Testing on neovim the typing is sluggish as if it has input delay, scrolling the window with C-u/C-d is choppy. Not a satisfying feeling. Vim same story, both tested with default configurations.

Alacritty has default configuration.

Monitor is 75hz, gpu AMD RX480, keyboard repeat rate 190 50. I don't know how to debug it.

In comparsion with st, alacritty is far from fastest terminal emulator on my system, atleast from the input delay side

**Comment by kchibisov** [comment]
Could you try the latest master?
