### ISSUE TITLE
Missing dependency for Clear Linux install instructions

### ISSUE THREAD

**Issue by a-lakhani** [alacritty/alacritty#2990]
Which operating system does the issue occur on?

Clear Linux

If on linux, are you using X11 or Wayland?

X11

Clear Linux users run into Fontconfig errors on startup unless we [sudo swupd bundle-add devpkg-fontconfig](https://github.com/jwilm/alacritty/issues/2675#issuecomment-515274325) and [modify our FONTCONFIG_PATH](https://github.com/clearlinux/distribution/issues/639#issuecomment-495972657) since the default location for `fonts/fonts.conf` is under `/usr/share/defaults/`, not `/etc/`.

The devpkg-fontconfig bundle includes devpkg-freetype and devpkg-expat, so the swupd command in INSTALL.md should read:

`sudo swupd bundle-add devpkg-fontconfig devpkg-libxcb`

as well as include the instruction to create a `/etc/profile` containing `FONTCONFIG_PATH=/usr/share/defaults/fonts'

before building alacritty.

I had the same fontconfig errors mentioned in the referenced issues, and the above fixed my build on Clear Linux as well.

**Comment by kchibisov** [comment]
@a-lakhani does Clear Linux not provide this `FONTCONFIG_PATH` env variable by default. It seems strange that it's in unusual location by default and don't have this EXPORT.

Could you send a PR and fill this gap of our missing dependencies on Clear Linux, thx?

**Comment by chrisduerr** [comment]
Waiting on https://github.com/trimental/andrew/issues/3.

**Comment by kchibisov** [comment]
Since andrew is no longer used closing this.
