### ISSUE TITLE
alacritty isn't starting

### ISSUE THREAD

**Issue by itsjzt** [alacritty/alacritty#2995]
![image](https://user-images.githubusercontent.com/22629916/69150806-66736c00-0aff-11ea-8f49-d3553c6eafd2.png)

Which operating system does the issue occur?
Windows 10 home Single Language (1809)

One thing to notice is that 
- the same version of alacritty 0.33 was working fine before 
- then I changed settings and it crashed
- I uninstalled it, removed alacritty.yml
- now whenever I install alacritty it shows the above error

**Comment by chrisduerr** [comment]
Could you try the 0.4.0 release candidate?

https://github.com/jwilm/alacritty/releases/tag/v0.4.0-rc2

**Comment by edyu** [comment]
Not exactly same problem but it also crashes for me on Windows 10 using the v0.4.0-rc2

---------------------------
Alacritty: Runtime Error
---------------------------
panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', src\libcore\result.rs:1165:5

Press Ctrl-C to Copy
---------------------------
OK   
---------------------------

**Comment by chrisduerr** [comment]
@edyu That is a different issue. As I've told you on a different issue where you posted this comment too, please ensure all the required files are installed. Enabling ConPTY will probably help, but that is unrelated to this issue.

**Comment by edyu** [comment]
@chrisduerr got it. I'll remove the comment. I was debating whether to start a new issue or not when I posted it earlier. Thanks.

**Comment by itsjzt** [comment]
OK, @chrisduerr I tried 0.4.0 and it is giving me the same errors 
![image](https://user-images.githubusercontent.com/22629916/69345315-f26bcc00-0c96-11ea-9e7e-2fdbf2a73eab.png)

**Comment by chrisduerr** [comment]
It surprises me that this shows a path linking to an AMD driver directory. So my assumption would be that there might be an issue with the drivers.

Do you have the latest drivers for your GPU installed? And which GPU are you running specifically, does it support modern OpenGL features?

**Comment by kchibisov** [comment]
This file is a part of intel driver if I've searched it correctly (amd64 == x86_64, so there's nothing related to AMD GPU). However I guess there's something off with this driver thing.

**Comment by itsjzt** [comment]
I will update the windows and its drivers and try this again.

**Comment by chrisduerr** [comment]
Assuming the update fixed things.
