### ISSUE TITLE
Control + / (Slash) unconditional triggers the system alert sound on macOS

### ISSUE THREAD

**Issue by nkgm** [alacritty/alacritty#3014]
Reproduced on macOS 10.11

I can map the keyboard shortcut just fine and it works as expected, but it will always (mapped or not) unconditionally trigger the system alert sound. Please note this is not some BELL character created by the shell as this would only cause the Alacritty window to flash. 

Also reported [Here](https://github.com/jwilm/alacritty/issues/62#issuecomment-497679262).

**Comment by chrisduerr** [comment]
Alacritty itself doesn't even have the ability to trigger the system alert sound, so this must be triggered by what you're running inside of Alacritty.

Have you tried different terminals/shells?

**Comment by nkgm** [comment]
> Have you tried different terminals/shells?

Yep, doesn't happen with `iTerm`. 

Alacritty is using the visual bell (verified by `printf "\a"`) so, unless I'm missing something, it would be impossible for the system alert sound to be triggered by zsh running inside of Alacritty.

Btw my mapping is:
```
  - { key: Slash, mods: Control, chars: "\x1f" }
```
which is `^_`, also verified by prepending `^V`, and also examining the bytes with `cat -e` and `xxd`:
```
# 16 <Control + Slash> keystrokes coming up

$ xxd
^_^_^_^_^_^_^_^_^_^_^_^_^_^_^_^_
00000000: 1f1f 1f1f 1f1f 1f1f 1f1f 1f1f 1f1f 1f1f  ................

#############
# +16 beeps #
#############
```

Both `Control + Slash` and `Control + Minus` produce *identical bytes*, but for some reason `Control + Slash` triggers the system alert sound while `Control + Minus` is completely silent.

**Comment by chrisduerr** [comment]
> Yep, doesn't happen with iTerm.

Have you tried a different shell too? iTerm uses zsh by default now, so if you're launching bash, that would explain the differences.

Launching Alacritty from iTerm might also help troubleshoot this, just to check the environment matches up.

**Comment by bartol** [comment]
Any updates? I have same issue.

**Comment by windwp** [comment]
+1
I already disable bell in bash but it stiil make system alert sound

**Comment by alexrenda** [comment]
I chased this down to winit, and this hack seems to remove the beep without changing any other functionality: https://github.com/alexrenda/winit/commit/7b1d49ed3d43140df0216c5ae64bde3d42b82c6a (I'd imagine there's a more principled fix based on https://christiantietze.de/posts/2016/11/nsresponder-finding-beep/ and https://stackoverflow.com/questions/13519647/silence-cocoa-error-beep, but I don't enough experience with Cocoa to know the right way to fix this).

**Comment by chrisduerr** [comment]
Is this still an issue with the latest macOS version?

**Comment by antonk52** [comment]
The issue is still present for `alacritty 0.7.2 (5ac8060)`

**Comment by chrisduerr** [comment]
Have you tried 11?

**Comment by antonk52** [comment]
I don't have macos 11 at hand. Sorry

**Comment by alexrenda** [comment]
I can confirm that the issue is present (and that the patch above fixes it) on macOS 11

**Comment by kirikaza** [comment]
BTW, the similar issue is present in standard macOS' Terminal.app too: Ctrl+/ just beeps without any effect (e.g. no "undo" action in Emacs). And `sed -l n` doesn't catch it too.

Alternative terminal kitty also beeps but with effect (and `sed -n l` in kitty sees `^_`).

**Comment by IzhakJakov** [comment]
> Is this still an issue with the latest macOS version?

Yes I am using MacOS Monterey v12.2.1 and Alacritty v0.10.1

**Comment by wassimk** [comment]
I found this issue when looking to remove the beep for `control-/` in v0.10.1.
```
  - { key: Slash,  mods: Control, chars: "\x1f" }
```

**Comment by antonk52** [comment]
> I found this issue when looking to remove the beep for `control-/` in v0.10.1.
> 
> ```
>   - { key: Slash,  mods: Control, chars: "\x1f" }
> ```

Interesting, I still get the beep but the actions that are mapped to ctrl+/ now work also. 

I am on alacritty 0.10.1 (2844606) and macOS 12.3.1

**Comment by dmackca** [comment]
> Alacritty itself doesn't even have the ability to trigger the system alert sound, so this must be triggered by what you're running inside of Alacritty.

I think it's actually coming from _outside_ of Alacritty. I bound `ctrl`+`/` to a shortcut in my code editor and it works, but I hear the bell sound every time I press it. It doesn't happen in every window (not Chrome, for instance), but it does happen if I focus the empty desktop and press that key combination. Is it the same for you? Is this a shortcut key in the OS? I'd like to change or disable it, if that's the case.

I can't find any trace of it in the keyboard settings or the Mac OS docs...

**Comment by IzhakJakov** [comment]
Found this answer [over here](https://apple.stackexchange.com/questions/24261/how-do-i-send-c-that-is-control-slash-to-the-terminal):
> `Ctrl-/` sends `0x1f` which is equivalent of `Ctrl-_` since the days of VT102. There are many VT100 emulators but they are actually VT102 emulators. iTerm2 works because it's following this behavior.
> 
> Only emulators that strictly conform to VT100 specification can't send `Ctrl-/`. I believe the Terminal app is one of them.
> 
> VT100 masks 2 most significant bits of 7 bit ASCII when the control key is pressed. `/` is `0x2f`, `o` is `0x6f`. When the 2 bits are masked they are both `0x0f`. VT100 can send `Ctrl-o` but not `Ctrl-/`.

**Comment by IzhakJakov** [comment]
Found this answer by @knoguchi [over here](https://apple.stackexchange.com/questions/24261/how-do-i-send-c-that-is-control-slash-to-the-terminal):
> `Ctrl-/` sends `0x1f` which is equivalent of `Ctrl-_` since the days of VT102. There are many VT100 emulators but they are actually VT102 emulators. iTerm2 works because it's following this behavior.
> 
> Only emulators that strictly conform to VT100 specification can't send `Ctrl-/`. I believe the Terminal app is one of them.
> 
> VT100 masks 2 most significant bits of 7 bit ASCII when the control key is pressed. `/` is `0x2f`, `o` is `0x6f`. When the 2 bits are masked they are both `0x0f`. VT100 can send `Ctrl-o` but not `Ctrl-/`.

**Comment by vinioliveira** [comment]
Is anyone else having this issue again? The following code used to work but since I upgraded to 0.11.0 it works only until I hit `Slash` with no modifiers. 

```
  - { key: Slash,  mods: Control, chars: "\x1f" }
 ```

**Comment by mike-lloyd03** [comment]
I have recently started having this problem again and the keybind to `\x1f` no longer works. I upgraded to 0.12.0 and the problem is gone.

**Comment by mike-lloyd03** [comment]
Actually no, the problem is still there. Looks like it's intermittent but I'm getting the system error sound and neovim isn't recognizing my keybinding.

**Comment by hermesjpappas** [comment]
Bumping this in hopes someone will see it. Trying to bind the same commenting action as on VSCode to terminal-run-(neo)vim but the annoying beep persists, despite the keystroke now working.

**Comment by rockyzhang24** [comment]
A feasible workaround to avoid the alert sound when `ctrl-/` is pressed:

1. Create a file `~/Library/KeyBindings/DefaultKeyBinding.dict` if it doesn't exist yet
2. Add the snippet below into `DefaultKeyBinding.dict`
```
{
    "^/" = "noop:";
}
```

It should take effect immediately. If not, reboot your device. 
Ref: https://youtrack.jetbrains.com/issue/IDEA-163077/Control-Slash-Ctrl-on-OS-X-macOS-producing-audible-alert

It works on my side with macOS 13.4.1 and alacritty 0.12.2. Hope it is helpful.

**Comment by juniorsaldanha** [comment]
To anyone that have issue with Contro-/ on Alacritty and it's trying to configure a keybinding to it on TOML file. Check it out this link: https://github.com/alacritty/alacritty/issues/7608#issuecomment-1975006973

**Comment by nixpulvis** [comment]
Interesting, I tried this configuration, and it's still causing the system bell to ring.

```toml
[[keyboard.bindings]]
key = "Slash"
mods = "Control"
chars = "foo"
```

**Comment by kchibisov** [comment]
Because it happens before it can even reach alacritty.

**Comment by nixpulvis** [comment]
> Because it happens before it can even reach alacritty.

I was worried that was the case.
