### ISSUE TITLE
Support plink from PuTTY and ANSI control chars

### ISSUE THREAD

**Issue by szepeviktor** [alacritty/alacritty#3063]
### System

OS: Windows 10
Version: `alacritty 0.4.0 (b115b90)`
Windows: WinPTY

![kép](https://user-images.githubusercontent.com/952007/70022463-95c0b900-1594-11ea-9358-4c35d5c4abad.png)

Should it be possible to run plink inside alacritty?
I see ANSI sequences.

**Comment by chrisduerr** [comment]
Can you try setting [this](https://github.com/jwilm/alacritty/blob/fa6ceacfa4158c568c55dff85621788ff1df4099/alacritty.yml#L349) option to `true`?

**Comment by szepeviktor** [comment]
Thank you.
I'm trying to get ConPTY on my Windows PC.

**Comment by chrisduerr** [comment]
If you're using Windows 10, it should be sufficient to update to the latest version available. That will give you ConPTY support.

**Comment by kchibisov** [comment]
winpty is dropped so closing.
