### ISSUE TITLE
Implement "Send Device Attributes",  Secondary and Tertiary DA

### ISSUE THREAD

**Issue by dnkl** [alacritty/alacritty#3100]
Implement `CSI > Ps c` and `CSI = Ps c`:

> ```
> CSI > Ps c
> Send Device Attributes (Secondary DA).
>             Ps = 0  or omitted ⇒  request the terminal's identification
>           code.  The response depends on the decTerminalID resource set-
>           ting.  It should apply only to VT220 and up, but xterm extends
>           this to VT100.
>             ⇒  CSI  > Pp ; Pv ; Pc c
>           where Pp denotes the terminal type
>             Pp = 0  ⇒  "VT100".
>             Pp = 1  ⇒  "VT220".
>             Pp = 2  ⇒  "VT240".
>             Pp = 1 8  ⇒  "VT330".
>             Pp = 1 9  ⇒  "VT340".
>             Pp = 2 4  ⇒  "VT320".
>             Pp = 4 1  ⇒  "VT420".
>             Pp = 6 1  ⇒  "VT510".
>             Pp = 6 4  ⇒  "VT520".
>             Pp = 6 5  ⇒  "VT525".
> 
>           and Pv is the firmware version (for xterm, this was originally
>           the XFree86 patch number, starting with 95).  In a DEC termi-
>           nal, Pc indicates the ROM cartridge registration number and is
>           always zero.
> ```

> ```
> CSI = Ps c
> Send Device Attributes (Tertiary DA).
>             Ps = 0  ⇒  report Terminal Unit ID (default), VT400.  XTerm
>           uses zeros for the site code and serial number in its DECRPTUI
>           response.
> ```
Broken out from https://github.com/jwilm/alacritty/issues/3091#issuecomment-565549380
@AmaiKinono

**Comment by dnkl** [comment]
The format of the reply for the tertiary DA is: https://vt100.net/docs/vt510-rm/DECRPTUI.html (this piece of information is missing in the XTerm control sequences document...)

**Comment by chrisduerr** [comment]
Supporting the tertiary DA seems pointless, though the secondary is widely supported. This should be fixed with #4011.
