### ISSUE TITLE
High wakeup count on idle 

### ISSUE THREAD

**Issue by dnkl** [alacritty/alacritty#3108]
Alacritty 0.4.0 on Wayland/Sway

Using Powertop, I see Alacritty having a steady ~19-20 wakeups/s. This is on a **completely idle** prompt, with the default (no file) config.

There's no measurable CPU usage, just the high wakeup count. This does however cause battery drain.

Just for reference, XTerm shows 0 wakeups/s in the same setup.

Not very high-priority I suppose :)

**Comment by chrisduerr** [comment]
Have you looked into what might be causing these wakeups? Waking up to redraw would be much more power hungry than waking up for checking if the config file changed for example (I'd assume it's something like the latter).

**Comment by kchibisov** [comment]
@dnkl Are there exactly ~20 wakeups btw? Since our clipboard sleeps for 50ms on avarage then wake up and dispatches pending events. Are you fine with testing the patch that disable our clipboard on Wayland, I can send you one in case you're fine with retesting things?

**Comment by dnkl** [comment]
@kchibisov more like "exatly" 19,4. Close enough I'd say ;)

Yeah, sure, I can test a patch

**Comment by kchibisov** [comment]
It should completely disable our clipboard.

```diff
diff --git a/alacritty/src/main.rs b/alacritty/src/main.rs
index 64e0b9c..7cf7b51 100644
--- a/alacritty/src/main.rs
+++ b/alacritty/src/main.rs
@@ -146,7 +146,7 @@ fn run(window_event_loop: GlutinEventLoop<Event>, config: Config) -> Result<(),

     // Create new native clipboard
     #[cfg(not(any(target_os = "macos", windows)))]
-    let clipboard = Clipboard::new(display.window.wayland_display());
+    let clipboard = Clipboard::new_nop();
     #[cfg(any(target_os = "macos", windows))]
     let clipboard = Clipboard::new();
```

**Comment by dnkl** [comment]
That was it. I don't see any wakeups with this patch.

**Comment by kchibisov** [comment]
Well, our clipboard lives in its own crate, because upstream windowing library decided not to include clipboard things in it, so we can't block forever and should wake up sometimes to dispatch pending events to not block paste from alacritty, etc, etc.

>Alacritty having a steady ~19-20 wakeups/s

Thx for this info, otherwise it will be harder for me to guess.

The relevant code in our clipboard is right here https://github.com/Smithay/smithay-clipboard/blob/e28a54171f8b0df4b0a5240d349540993bd5ac5e/src/threaded.rs#L501 , however I don't think that we can do something about it.

**Comment by dnkl** [comment]
My limited rust knowledge is showing here, but is there no way to `select(3)`  or `poll(3)` instead? That'd be the normal way to handle things like this.

**Comment by kchibisov** [comment]
@dnkl I don't know Wayland that much, but the only thing we have in clipboard is a wl_display, that's it. So I'll try to take a look on how can we handle and improve things, however it's more QoI then a big issue for now, as far as I can see.

**Comment by dnkl** [comment]
In the C API, you have `wl_display_get_fd()`. You can then `select()` on that FD (with `POLLIN`) When `select` indicates you have data to read, you can call `wl_display_dispatch()` to trigger all the Wayland registered listener callbacks.

Not sure how much of this maps to the rust bindings though.

**Comment by dnkl** [comment]
Of course, if you're _also_ listening for events from alacritty, then you'd have to throw that into the `select()` too, somehow.

I'm guessing there are nice rust wrappers for all this though...

**Comment by kchibisov** [comment]
@dnkl The current rust "interface" is implemented in channels, so it's a little bit more work, but thanks for your help. I'll take a look on it when I'll have time for this task (probably during upcoming holidays).

**Comment by dnkl** [comment]
I'm always up for brainstorming :)
