### ISSUE TITLE
Cannot close / not responding on close when python is still running

### ISSUE THREAD

**Issue by jerryc05** [alacritty/alacritty#3111]
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

OS: Windows
Version: alacritty 0.4.0
Windows: ConPTY

### Logs
Execute `python`, and then close alacritty. The window freezes.

**Comment by chrisduerr** [comment]
Could you try this with the latest master? There were some recent changes introduced by @davidhewitt  that might have resolved this!

**Comment by davidhewitt** [comment]
This issue can probably now be closed.

**Comment by kchibisov** [comment]
Ok, I'll close it for now.
