### ISSUE TITLE
Possible behavioral change?

### ISSUE THREAD

**Issue by UnixRonin** [alacritty/alacritty#3138]
### System
OS: Gentoo Linux
Version: alacritty 0.4.0
Linux/BSD: X11/fvwm2

### Logs

Crashes: none
Font/Terminal size: 
babylon5:alaric:~:2 $ alacritty -vv
Created log file at "/tmp/Alacritty-7431.log"
[2019-12-31 14:01] [INFO] Welcome to Alacritty
[2019-12-31 14:01] [INFO] Configuration loaded from "/home/alaric/.config/alacritty/alacritty.yml"
[2019-12-31 14:01] [DEBUG] Estimated DPR: 1
[2019-12-31 14:01] [DEBUG] Estimated Cell Size: 8 x 17
[2019-12-31 14:01] [DEBUG] Estimated Dimensions: Some((756.0, 1568.0))
[2019-12-31 14:01] [INFO] Device pixel ratio: 1
[2019-12-31 14:01] [INFO] Initializing glyph cache...
[2019-12-31 14:01] [INFO] ... finished initializing glyph cache in 0.01898943s
[2019-12-31 14:01] [INFO] Estimated DPR correctly, skipping resize
[2019-12-31 14:01] [INFO] Cell Size: 8 x 17
[2019-12-31 14:01] [INFO] Padding: 2 x 2
[2019-12-31 14:01] [INFO] Width: 756, Height: 1568
[2019-12-31 14:01] [INFO] PTY Dimensions: Line(92) x Column(94)
[2019-12-31 14:01] [INFO] Initialisation complete
[2019-12-31 14:01] [DEBUG] Term::resize dimensions unchanged
[2019-12-31 14:01] [INFO] Width: 756, Height: 1568

Keyboard and bindings: `alacritty --print-events`
(This yields an unstoppable flood.)

Requesting advice/assistance:

I have a cli Perl/ncurses application in which I've never found a good way to implement scrolling control, but alacritty's own scrolling Just Works.  ...Until now, that is.  It APPEARS that what has now happened is that the mouse wheel USED to send ScrollPageUp/ScrollPageDown events, which alacritty correctly handled, but now sends Up and Down key events to my application instead.

I'm attempting to isolate what has caused this behavioral change — Perl?  Alacritty?  nVidia-drivers?  Is there a recent default-configuration change in alacritty which might cause this?  I see how key and mouse-button bindings are set in alacritty.yml, but not any way to set mousewheel bindings.  Is there a way I can get alacritty to print ALL bindings and exit, so that I can verify all of the bindings?  Is there a syntax for explicitly setting mousewheel bindings in the .yml file?

Any help/tips appreciated.

**Comment by chrisduerr** [comment]
I'm not sure which version you upgraded from, but that sounds like you're in the alt screen, where scrolling uses alternate scrolling by just sending up/down keys. You can temporarily disable that by holding shift and scrolling, but in the alt screen Alacritty's scrollback isn't available anyways.

**Comment by UnixRonin** [comment]
That seems to match the symptoms.  Thanks.
I hadn't yet tried reverting to the previous version because I'd have to do so manually, the alacritty-0.3.3 ebuild having already been expired out of the portage tree.  But I was fairly sure it wasn't a **regression** as such anyway, because scrolling still works in other applications.

The next question, then, perhaps, is how do I get out of — or better, disable for this application — the "alt screen"?

**Comment by chrisduerr** [comment]
I mean it depends on the application you use, but you need to send the `\e[?1049l` escape to leave the alternate screen.

If you just want to disable alt scrolling though, there's an escape just for that too, which is `\e[?1007l`.

**Comment by UnixRonin** [comment]
Well, the alternate-screen theory appears to be correct.  If I have my application emit ESC[?1007l immediately as it starts up, mousewheel no longer gives me input history.  (Of course, it doesn't give me scroll either.)  Emitting ESC[?1049l does indeed appear to switch me out of alternate mode, which restores the prior scroll functionality, but has peculiar side effects on display until a screen redraw command is issued.  Possibly I can add an automatic redraw immediately after logging in.  And I probably need to do this only if the parent **terminal** (possibly with intervening screen or tmux) is alacritty.  Unless I add a command-line switch to do that, which might be simpler.

What's making me scratch my head is why it would have just now started behaving this way (the change is since the last reboot, as close as I can figure).

**Comment by UnixRonin** [comment]
argh.  screen is also playing a part in this.  That complicates matters.

**Comment by UnixRonin** [comment]
Well the good news is I figured out how to make my application get out of the alternate-screen mode.

The bad news is, both screen and tmux are still apparently breaking mousewheel-scroll.  Even with the alt-screen escape.  I have more sleuthing to do...

**Comment by chrisduerr** [comment]
Let us know if you can identify a problem in Alacritty.
