### ISSUE TITLE
RFE: right click shouldn't clear selected text

### ISSUE THREAD

**Issue by james-lawrence** [alacritty/alacritty#3144]
given conversations in other issues (#1539, #839) it seems right click isn't supported, which is fine.
however right click does cause text selections to be deselected. which is annoying as old habits die hard.

### System

OS: Linux
Version: 0.4.0
Linux/BSD: Wayland, sway, gnome

**Comment by kchibisov** [comment]
>given conversations in other issues (#1539, #839) it seems right click isn't supported, which is fine.

Right **is** supported in alt-screen apps. However I feel like you're talking about some "menu" on right click which is not supported and unlikely will.

I'm not against the idea of not resetting selection on a right click, but I'm not sure how we should add it. I mean that it's a user preference and we can in theory add a config option for it, but on the other hand if the majority of terminal emulators don't reset selection on a right click we should do the same thing here.

**Comment by chrisduerr** [comment]
It seems like VTE (Termite) does nothing on right click and both Kitty and URxvt extend the selection.

So as far as I'm concerned, not resetting the selection on right click should be fine. Though the reasoning for it 'old habits die hard', is not one I support. It would rather be for consistency with other terminals.

**Comment by kchibisov** [comment]
>It seems like VTE (Termite) does nothing on right click and both Kitty and URxvt extend the selection.

Knowing that we're going to extend selection with `Shift` + `Click` in a future like Firefox, etc, everything seems fine here for now.

**Comment by chrisduerr** [comment]
URxvt does both I think, so that might be an option too if your rightclick is not used anyways.

Kitty does it just on rightclick and doesn't do anything useful on shift as far as I can tell.

**Comment by nixpulvis** [comment]
I'd be all for supporting this as part of #2361. There's been some discussion about it already. I think I'm still a fan of using <kbd>shift</kbd>, but this could also be a default option.

**Comment by james-lawrence** [comment]
@chrisduerr `old habits die hard` can be rephrased as unexpected/abnormal/incorrect behavior. every terminal I've personally used right click has never cleared the selection.

- terminator, right click shows a context menu closing without selecting an option maintains selection.
- urxvt, right click adjusts the selection to the click location.
- termite, right click literally does nothing. selection is maintained.

**Comment by kchibisov** [comment]
@james-lawrence The key thing here, that your initial argument on why we should change the behavior was poor, however it was discovered that all terminals we're aware of are not resetting selection on right click. So not resetting selection on right click makes sense with such argument.

As you can see by tags on your issue we already agreed that we're fine with merging the patch which makes right click not touching selection.

**Comment by chrisduerr** [comment]
> I'd be all for supporting this as part of #2361. There's been some discussion about it already. I think I'm still a fan of using shift, but this could also be a default option.

I'm also in favor of using `shift`. For me the question would mainly be about supporting right-click too or not. But I think for now, just having one of them should be good, then we have right-click for whatever magic we might think up in the future.

**Comment by nixpulvis** [comment]
@chrisduerr I'd love to support an `Action` for this is the bindings section of the config. That way users coming from urxvt (for example) can configure things to be more similar to the way they were. It's a sensible action.

**Comment by chrisduerr** [comment]
I'm not sure how easy it is to hook this up to an action and I'd definitely prefer just getting the feature in. But if it's just a couple of extra lines, I don't see why not.

**Comment by nixpulvis** [comment]
If the action comes in a followup PR, that's totally fine. I too would like to see #2361 finished, I'd make great use of this feature.
