### ISSUE TITLE
Windows msi installer (and possible build) doesn't support aarch64 windows.

### ISSUE THREAD

**Issue by harrisonmetz** [alacritty/alacritty#3147]
Running the windows installer on a aarch64 windows returns immediately saying it does not support the processor architecture. Rust has a target for aarch64-pc-windows-msvc so it should be possible to compile for that.

**Comment by chrisduerr** [comment]
The msi installer is pre-compiled, so it won't work on multiple architectures.

Our CI just runs on one target, which is not aarch64, so if you use a different architecture, you'll have to compile it yourself.

**Comment by kchibisov** [comment]
@harrisonmetz Are you asking us to provide AArch64 msi installer for the releases? I don't think that AArch64 on Windows is a popular platform, and knowing that Alacritty requires OpenGL 3.3 to run, things could just not work most of the time, since in the current state AArch64 based machines are using low powered GPUs most of the time IIRC, so having one more binary that will unlikely work isn't sound good.

You can still try to compile it and run yourself as was already stated.

**Comment by harrisonmetz** [comment]
As a quick update, I can't get it to compile for aarch64 windows. I'm having an error in the rust-datetime library (because that is using too old of a version of winapi-rs). I've made a pull request https://github.com/rust-datetime/datetime/pull/28 but unfortunately it wasn't passing travis CI to begin with (I think it was using too old a version of rust). Hopefully when the maintain pulls it I can try again compiling alacritty and report what breaks next. Thankss.

**Comment by chrisduerr** [comment]
Alacritty does not depend on this library.

**Comment by harrisonmetz** [comment]
My bad, it does not depend on that. But it does depend on other libraries which, in tern, use the old kernel32-sys crate:
```
│   ├── mio v0.6.21
│   │   ├── cfg-if v0.1.10 (*)
│   │   ├── iovec v0.1.4
│   │   ├── kernel32-sys v0.2.2
```
It looks like mio 0.7 uses the newer version of winapi (which has the kernel stuff built in). However, that version looks like it is not released. I think this problem will fix itself after mio release 0.7 and alacritty updates to it.

**Comment by chrisduerr** [comment]
@kchibisov question is still outstanding. If this issue is about supporting Alacritty to build on aarch64, the description and title should be updated. If it is about providing an installer for aarch64, I don't see why we would.

**Comment by chrisduerr** [comment]
Alacritty does not provide an aarch64 installer. If someone needs help with compiling on aarch64, please open a separate issue.
