### ISSUE TITLE
Provide `Trigger` mechanism to call user scripts

### ISSUE THREAD

**Issue by kchibisov** [alacritty/alacritty#3182]
The idea is very similar to our `Action` for key/mouse bindings, however it'll be limited to only launch user defined programs and in some cases maybe pass arguments to them.

Example of `alacritty.yml` on how it could look

```yaml
# - `trigger`: A triggers on which you can run arbitrary commands
#
#   - Focused
#   - Unfocused
#   - Bell

triggers:
- { trigger: Focused, command: { program: "focused", args: ["true"] }}
- { trigger: Unfocused, command: { program: "focused", args: ["false"] }}
- { trigger: Bell, command: { program: "loud_beep" }}
```

The implementation should be done mostly in `alacritty` crate, however we should also develop a mechanism to forward certain "terminal events" from `alacritty_terminal` to `alacritty`, e.g. `BELL`. Such mechanism should simplify handling of curtain parts like existing visual bell, since timing handling should be done solely in `alacritty` crate.

The proposed solution should be more flexible than adding a random "command" to some existed config structures and easily extensible in a future. It also doesn't affect performance, since it doesn't call back into `alacritty` and just launches programs like our key bindings with `command`.

Should provide more generic solution for #2298 and #1982

**Comment by kchibisov** [comment]
The trigger name was used historically, however we can use `Hook`/`hooks`. I'm interested to hear other suggestions here.

**Comment by nixpulvis** [comment]
Just scanning through the list of events we deal with, would it be useful to expose the user event `Urgent` as well?

Overall I think this is starting to crystallize a feature I've been wanting for some time for the bell, in an elegant way. I think if we want to come up with clear meaning for "trigger" and "hook" I'd say it should be like this:

- A trigger is something a user, well triggers. So this is appropriate terminology for the set of keys/modifiers for key/mouse bindings
- A hook is something that "hooks" into an existing event of some kind, making it appropriate here I believe

I think I'd call the top-level key in the config `hooks`, and have the elements be `{ event: Bell, program: { ... }}`.

**Comment by kchibisov** [comment]
Oh, an important note. My proposal was written in a bit generic way, however we already have a way to send events from alacritty_terminal into alacritty, as well as idea of User events, so the resulted implementation should be purely done in `alacritty` crate, well, maybe a bit of renames in `alacritty_terminal` for e.g. `Urgent` event should be called `Bell`, since it's a bit better name.

**Comment by kchibisov** [comment]
@nixpulvis `Urgent` is a `Bell` in a current state of the alacritty_terminal, so we don't need to expose it, we should just rename `Urgent` to `Bell`.

**Comment by chrisduerr** [comment]
Just to expand on this, I think it makes sense to allow everything that is used in a keybinding action here.

So it should be possible to use predefined actions like `Paste` and writing characters like `\x0c`.

One thing we should consider is parameters. Currently we already have a method for launching URLs, however that requires direct interaction with the launched command by passing a parameter to it.

**Comment by kchibisov** [comment]
I'm not sure that using Actions like Paste makes sense for Focused/Unfocused tbh, and passing arguments to it doesn't make sense, however some triggers could be useful only with additional parameters, in case you decide to add a UrlClick into in addition to already proposed Focused, etc.

**Comment by kchibisov** [comment]
We've added a way to run commands on bell, and for things like focus change we're not sure who should do that work, in general compositor can do such thing, since I don't really want to overly complicate configuration for a niche feature.
