### ISSUE TITLE
Alacritty reverts the font change after moving across the monitors

### ISSUE THREAD

**Issue by kchibisov** [alacritty/alacritty#3183]
I'm not sure that it's a desired behavior, however I feel like if a user changed font size from `X` to `Y` on a monitor `1` and then moved a window from a monitor `1` to a monitor `2` we should speculate with the updated font size and not with the default one. So the font size on a monitor `2` should be `Y * scale_factor` and not `X * scale_factor`.

In addition to this the next update after moving alacritty from `1` to `2` will be based on `Y` and not `X`, so it seems like a bug to me.

**Comment by chrisduerr** [comment]
You're absolutely correct. The new font size should just be the rescaled version of the current font size, not of the config.
