### ISSUE TITLE
Properly inform compositors of damaged regions

### ISSUE THREAD

**Issue by nagisa** [alacritty/alacritty#3186]
### System

OS: Linux
Version: alacritty 0.4.0
Linux/BSD: sway

### Logs

N/A

---

alacritty currently appears to be damaging the whole window even when there are little or no changes to the contents. This is important for [energy efficiency](https://mozillagfx.wordpress.com/2019/10/22/dramatically-reduced-power-usage-in-firefox-70-on-macos-with-core-animation/).

See also https://emersion.fr/blog/2019/intro-to-damage-tracking/ for motivation and explanation and https://bugzilla.mozilla.org/show_bug.cgi?id=1484812 for a related firefox issue.

**Comment by chrisduerr** [comment]
See https://github.com/alacritty/alacritty/pull/2724.
