### ISSUE TITLE
Properly inform compositors of opaque regions

### ISSUE THREAD

**Issue by nagisa** [alacritty/alacritty#3187]
### System

OS: Linux
Version: alacritty 0.4.0
Linux/BSD: wayland

### Logs

N/A

---

For efficiency reasons alacritty should inform compositors about opaque portions of the window when alacritty is not set to use partial transparency. This allows compositors to avoid composition for the areas of the screen that are opaque.

On wayland this can be achieved with `wl_surface::set_opaque_region` protocol call.

**Comment by nagisa** [comment]
That being said, it may very well be that alacritty is already setting the opaque region and I just missed it. I do not have a sure-fire way to confirm it.

**Comment by chrisduerr** [comment]
This kind of stuff is usually handled by winit. In this case it might even set the window region to be fully opaque if it is started as non-transparent, however all Alacritty windows are always started as transparent to allow changing opacity at runtime (through config reload).

So to work around this, we'd likely have to obtain the winit Wayland surface and do this ourselves.
