### ISSUE TITLE
Comment in default config about scrolling is incorrect

### ISSUE THREAD

**Issue by kchibisov** [alacritty/alacritty#3189]
The default configuration file says the following:
```
# Number of lines the viewport will move for every line scrolled when
# scrollback is enabled (history > 0).
#multiplier: 3

```

As you can see it's a number of `lines`, while it's accurate when you're using a mouse, on a `touchpad` you just changing the speed of accumulating events, and you'll still be able to scroll **exactly** by one line, even having `multiplier: 5`, while on mouse it's impossible.

So I see two possible solutions here: make touchpad to match a mouse behavior, so you should accumulate scrolling as always, but multiply afterwards, or we should update a comment in default configuration file. To say, that it's a multiplier for scrolling events, and remove the parts about lines.

**Comment by chrisduerr** [comment]
I don't see how this is incorrect. Even with touchpads, we scroll by 3 lines for every line scrolled. It's just that we can scroll by 0.X lines.

On desktop with a mouse, it's always a single line, so that makes things more abrupt, but it's still true for both.

This is just saying it's a 1:3 relationship by default. If the 1 changes, the 3 would obviously be affected too.

**Comment by kchibisov** [comment]
>I don't see how this is incorrect. Even with touchpads, we scroll by 3 lines for every line scrolled. It's just that we can scroll by 0.X lines.
>
>On desktop with a mouse, it's always a single line, so that makes things more abrupt, but it's still true for both.
>
>This is just saying it's a 1:3 relationship by default. If the 1 changes, the 3 would obviously be affected too.

Then we should update our config, since half of a line doesn't make sense to me in a context of a terminal emulator.

cc @nixpulvis

**Comment by chrisduerr** [comment]
> Then we should update our config, since half of a line doesn't make sense to me in a context of a terminal emulator.

What do you mean? We don't scroll by half a line and we never claim we do?

**Comment by kchibisov** [comment]
>Even with touchpads, we scroll by 3 lines for every line scrolled. It's just that we can scroll by 0.X lines.

I've probably misunderstood your comment here, since you're likely saying that we `can`, but we `don't`.

So I guess we should just say, that it's a acceleration for mouse scrolling events to make it clear.

**Comment by chrisduerr** [comment]
Oh, I mean that we get the events that the user scrolled by `0.X` and we can multiply it by our modifier to have finer scrolling than with mice on the same modifier.
