### ISSUE TITLE
Win 7 crashes on start (Entry Point Not Found)

### ISSUE THREAD

**Issue by yrendykurniawan** [alacritty/alacritty#3192]
After building from source, starting from this commit c34ec12
Alacritty crashes on start, using 1 older commit(dd1413e) works normally.

### System

OS: Windows 7 x64
Version: alacritty 0.4.2-dev (c34ec12 )
Windows: WinPTY

### Logs

Running cargo run --release:
```
error: process didn't exit successfully: `target\release\alacritty.exe` (exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND)

```
Clicking the exe pop up this error message:
![csrss_2020-01-12_17-36-31](https://user-images.githubusercontent.com/29836494/72217548-1abecb00-3562-11ea-9321-8b17873b5970.png)

Checking msdn API docs it seems `AdjustWindowRectExForDpi` only supported for Windows 10
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-adjustwindowrectexfordpi

**Comment by kchibisov** [comment]
it's likely related to https://github.com/rust-windowing/winit/issues/1386

**Comment by chrisduerr** [comment]
It seems like this is also a Problem with Windows 8.1 which is still officially supported, but Windows 7 support ends in two days (Jan 14. 2020). So while this issue might be fixed for Windows 8 support, updates that break Windows 7 support will not be declined or fixed in the future, so updating is strongly recommended.

**Comment by SubhumanPotato** [comment]
@chrisduerr Seeing as 33% of steam users run Windows 7 (https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam), I think it'd be a mistake to forsake Windows 7 support.

**Comment by chrisduerr** [comment]
> @chrisduerr Seeing as 33% of steam users run Windows 7 (https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam), I think it'd be a mistake to forsake Windows 7 support.

Windows 7 is not a supported Operating System anymore. People need to move on with their lives. It doesn't matter the slightest how many machines might be (mis-)reporting themselves as Windows 7 on Steam. Alacritty is not a Steam game.

**Comment by kchibisov** [comment]
since winpty is dropped there's no point in keeping this issue around.
