### ISSUE TITLE
MacOs: Nothing happend after launching Alacritty(Configured Already)

### ISSUE THREAD

**Issue by cellardoorver** [alacritty/alacritty#3195]

**Comment by chrisduerr** [comment]
How did you install Alacritty and how are you launching it?

**Comment by cellardoorver** [comment]
@chrisduerr I tried to add something error in file cd `~/.config/alacritty/alacritty.yml` and then launch Alacritty. `[Error] See log at...` and `Unable to load config...` were the next thing i see. Then i deleted the error line that i was adding before and hit Save. Alacritty run exactly what i expected. But after exit and launch again, nothing happend.

**Comment by chrisduerr** [comment]
Have you tried completely removing the configuration file? And do you get any error when trying to run Alacritty from another terminal?

**Comment by cellardoorver** [comment]
> Have you tried completely removing the configuration file? And do you get any error when trying to run Alacritty from another terminal?

i haven't tried it yet. How do i run Alacritty from another terminal?

**Comment by chrisduerr** [comment]
Depends on your installation method. Assuming you've copied it to `/Applications`, there should be an Alacritty executable somewhere in `/Applications/Alacritty.app/Contents/alacritty`.

**Comment by cellardoorver** [comment]
> Depends on your installation method. Assuming you've copied it to `/Applications`, there should be an Alacritty executable somewhere in `/Applications/Alacritty.app/Contents/alacritty`.

Oh, i found the problem, i fixed it. Thanks so much @chrisduerr

**Comment by cellardoorver** [comment]
@chrisduerr how do i config key binding for Open new tab in Alacritty.

**Comment by chrisduerr** [comment]
Key bindings should be live reloaded.

If the problem is fixed, does that mean this issue is resolved for you?

**Comment by cellardoorver** [comment]
> Key bindings should be live reloaded.
> 
> If the problem is fixed, does that mean this issue is resolved for you?

Yes

**Comment by kchibisov** [comment]
>how do i config key bindings for Open new tab in Alacritty.

We don't support tabs, use tmux if you need them.

**Comment by cellardoorver** [comment]
> > how do i config key bindings for Open new tab in Alacritty.
> 
> We don't support tabs, use tmux if you need them.

Yes, i will. Thanks
