### ISSUE TITLE
Powershell starts up with extra stuff prepended to the current directory name

### ISSUE THREAD

**Issue by Ryan1729** [alacritty/alacritty#3198]
After updating to the latest version, when Alacritty starts, either from the `Open Alacritty Here` context menu, or when running it from a previous Alacritty instance, the path has `Microsoft.PowerShell.Core\FileSystem::\\?\` prepended to. For example, if I open Alacritty in `C:\home` my prompt says `PS Microsoft.PowerShell.Core\FileSystem::\\?\C:\home>`. Other than the long prompt, everything seems to work properly. If I run `cd C:\home` then the prompt appears how I would expect it to on startup: `PS C:\home>`. Oddly enough, if I start a powershell 6 terminal, then run `alacritty.exe` inside there, the resulting instance of Alacritty does not have this long prompt. It does print `Cannot load PSReadline module.  Console is running without PSReadline.` above the prompt only in that case though.

### System

OS: Windows 10
Version: alacritty 0.4.1 (4d9253b)
Windows: ConPTY

**Comment by chrisduerr** [comment]
Have you confirmed that downgrading to a previous version fixes this problem? Or could this just be an unfortunate collision of multiple updates at the same time?

**Comment by enizor** [comment]
After upgrading Alacritty I got the same problem (on `cmd.exe`).

The commit that broke this is f632919134414e31ffd3ae9b5732d673deb0adf5.
My guess is that [this remark](https://github.com/alacritty/alacritty/pull/3117#discussion_r360699960) is mistaken and you have to hope that the process can handle the UNC path.

Using again `dunce::canonicalize` in `alacritty_terminal/src/tty/windows/winpty.rs` (on latest master) fixes the issue on my end.

I do not know what causes the PSReadline module error though.

**Comment by chrisduerr** [comment]
That sounds like a very good guess @enizor, thanks!

@davidhewitt could you look into this? I'm not sure if we actually want to add `dunce` as a depedency, but if that should be the problem, we could potentially un-UNC things ourselves.

**Comment by davidhewitt** [comment]
I guess that `CreateProcessW` (which is what we give the UNC path to) is forwarding it on unmodified, which upsets cmd.exe. Alas. The documentation for `CreateProcessW` stated UNC paths were fine (as far as that API was concerned).

> we could potentially un-UNC things ourselves.

I'll make a patch this evening to do exactly this.

**Comment by chrisduerr** [comment]
> I'll make a patch this evening to do exactly this.

I'd imagine we're talking about a controlled environment here, where we don't receive a UNC path from Windows. So including `dunce` just for that seems very overkill and it'll likely cover a ton of edge cases we don't care about. However if it turns out not to be worth it to copy their code 1:1 ourselves, please let me know and we can rethink our strategy.

Thanks a lot for your quick reply!

**Comment by Ryan1729** [comment]
Sounds like the cause has probably been found, but I can confirm that if I uninstall 0.4.1, then install 0.4.0 then the prompt does not have the extra stuff, and then if I re-install 0.4.1 then the extra stuff reappears.
