### ISSUE TITLE
Support Windows font fallback

### ISSUE THREAD

**Issue by damnskippy** [alacritty/alacritty#3215]
OS: Windows
Version: 0.4.1 (4d9253b)
Windows: ConPTY

When using the recently released JetBrains Mono font (https://www.jetbrains.com/lp/mono/) on alacritty, seeing a strange issue where some of the UTF-8 characters are not displayed at all with alacritty.   Other terminals (mintty for example) are able to display this correctly.  First noticed when tmux did not display the borders of the panes.

Tested it with this demo test file: https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-demo.txt
Below is a cat of the file in alacritty - notice how only some of the characters are getting printed, and none of the box drawing characters are printed.
![alacritty](https://user-images.githubusercontent.com/5184519/72550239-45f63280-3860-11ea-94c1-8d1cd9234e05.png)

Same in mintty for comparison:
![mintty](https://user-images.githubusercontent.com/5184519/72550825-915d1080-3861-11ea-9442-613505497a4f.png)

Curious to know if it's just me or if others see this as well.
Thank you.

**Comment by cole-h** [comment]
I'm not completely certain, but I believe this should be solved by https://github.com/alacritty/alacritty/pull/3127, seeing as you're on Windows.

On Linux/Wayland, this is what I see:
![image](https://user-images.githubusercontent.com/28582702/72554285-34f0f580-384f-11ea-8faf-f49302622a48.png)

**Comment by chrisduerr** [comment]
It seems like we do not have an issue for this yet, so we can use this to track the feature implemented in the PR.

If you have any feedback on the PR, please feel free to comment on it.
