### ISSUE TITLE
Unable to delete some characters and auto-completed char sequences on macOS (render or font bug?)

### ISSUE THREAD

**Issue by Dentrax** [alacritty/alacritty#3219]
### System

OS: `macOS`
Version: `0.4.1`
Config: default
Plugins: `fzf, oh-my-zsh, antigen`
Installed via: `brew cask install alacritty`
Antigen Bundles:
```
source /usr/local/share/antigen/antigen.zsh

antigen use prezto

antigen bundles <<EOB
    hlissner/zsh-autopair
    rupa/z
    Tarrasch/zsh-bd
    b4b4r07/enhancd
    amstrad/oh-my-matrix
    sindresorhus/pretty-time-zsh
    ael-code/zsh-colored-man-pages
    MichaelAquilina/zsh-autoswitch-virtualenv
    zsh-users/zsh-autosuggestions
    zsh-users/zsh-syntax-highlighting
    zsh-users/zsh-histrory-substring-search
EOB

antigen apply
```

Somehow, _iTerm_ doesn't have this problem. I couldn't delete the characters in almost every command. I'm using `zsh` with some _antigen bundles_ and _fzf_. All configs are default.

Reproduce types:
1. Press <kbd>⌥</kbd> + _any char_ (`t` _for example_)
 - It's not possible to delete it anymore.
 - Alacritty:
<img width="194" alt="Screen Shot 2020-01-17 at 22 12 58" src="https://user-images.githubusercontent.com/16493751/72639403-9069d300-3976-11ea-81fb-dff15770325a.png">
 - iTerm:
<img width="182" alt="Screen Shot 2020-01-17 at 22 13 38" src="https://user-images.githubusercontent.com/16493751/72639426-a081b280-3976-11ea-9a8c-8ccf2b512e9e.png">

2. Type a command that you wrote before (`bat ...` _for example_)
 - Type `ba`:
<img width="170" alt="Screen Shot 2020-01-17 at 22 16 42" src="https://user-images.githubusercontent.com/16493751/72639634-12f29280-3977-11ea-86ef-8a8afabeaabb.png">
 - Press <kbd>TAB</kbd>:
<img width="486" alt="Screen Shot 2020-01-17 at 22 17 08" src="https://user-images.githubusercontent.com/16493751/72639677-2aca1680-3977-11ea-919b-8e6900217e09.png">
 - Press and hold <kbd>BACKSPACE</kbd>

 - Stucked and unable to delete `ba`

 - It's not possible to delete it anymore.
<img width="55" alt="Screen Shot 2020-01-17 at 22 18 28" src="https://user-images.githubusercontent.com/16493751/72639765-6a90fe00-3977-11ea-861b-7715c867bfb7.png">
 - Plus, if i add `bat .zsh/antigen.zsh -p` command just after undeletable _ba_ command, it works well even it seems to be like `babat .zsh/antigen.zsh -p` on terminal. _(render bug?)_

  - Expected bahaviour when press <kbd>TAB</kbd>: _(in iTerm)_
<img width="463" alt="Screen Shot 2020-01-17 at 22 20 22" src="https://user-images.githubusercontent.com/16493751/72639840-91e7cb00-3977-11ea-8ba7-22969a2b128c.png">

 - As you see, `ba` is not duplicated, it's actually the how it's supposed to be.

Is that font/render/encoding bug?

**P.S:** `bat` is just for the example. _Sorry for bad explanation._ :)

**Comment by chrisduerr** [comment]
I'd assume removing the `>` from your prompt fixes this issue?

**Comment by kchibisov** [comment]
In addition, could you provide us with `locale` output?

**Comment by chrisduerr** [comment]
There are two basically identical issues: #2178 and #2026.

As @kchibisov has correctly, inquired, this is likely about the `locale` in your terminal environment. As such, running it from iTerm should fix the issue.

The current issue for tracking this is #2566, which should have some useful things you can try out. The main thing is usually to make sure to pass `--login` to your shell, instead of starting your shell without it.

So instead of this:

```yml
shell:
  program: zsh
```

You'd want to use something more like this:

```yml
shell:
  program: zsh
  args:
    - --login
```

If it turns out that starting from iTerm does not work, please let me know and I'll re-open this issue. Otherwise please keep further discussion in #2566, so that all information is available centrally over there.
