### ISSUE TITLE
How to open vim buffer via key bindings

### ISSUE THREAD

**Issue by n0ibe** [alacritty/alacritty#3222]
2973 # System

OS: macOS
Version: alacritty 0.4.1 (4d9253b)

I'm trying to assign the `cmd + ,` key combination to open a vim buffer with my alacritty config file. This is what I have in my config file

    - { key: Comma, mods: Super, command: { program: "/usr/local/bin/nvim", args: ["/Users/noibe/.config/alacritty/alacritty.yml"] }}

which doesn't work. If I change the program from `nvim` to `open` it opens the file in my graphical text editor (TextEdit), so I suspect that the command is being run in a subshell and not in an interactive one.

How can I modify it so that the buffer is open in the current shell?

**Comment by chrisduerr** [comment]
> How can I modify it so that the buffer is open in the current shell?

You can't.

Alacritty is a terminal emulator, not a shell. If you want to start something inside of your current shell, that's a shell thing, not a terminal emulator thing. So Alacritty's keybindings are not the correct place for this.
