### ISSUE TITLE
w3m images (ranger) not working with alacritty and Wayland

### ISSUE THREAD

**Issue by harrisonthorne** [alacritty/alacritty#3227]
### System

OS: Linux

Version: `0.4.1`

Wayland, Sway

### Notes

Reference [this issue I posted before on ranger's issue tracker](https://github.com/ranger/ranger/issues/1476), which has all the same information I would post here, except for the updated alacritty version (0.4.1) and Linux version (5.4.11-arch1-1).

Note that image previews work in xterm, but not alacritty. Is there possibly a workaround?

Thanks :)

**Comment by chrisduerr** [comment]
XTerm doesn't run in Wayland, but in XWayland. So that would obviously make it different.

Does this work in any Wayland terminal? I don't think it does.

**Comment by harrisonthorne** [comment]
It doesn't seem to work in other Wayland terminals (termite, havoc)

**Comment by cole-h** [comment]
The only Wayland terminal to support drawing images in e.g. ranger is Kitty (AFAIK), which has built its own protocol for doing so.

**Comment by chrisduerr** [comment]
Yeah, w3m has always been a huge hack and I don't think Wayland has ever had any intention of supporting that. So there's nothing that can be done here, other than not using Wayland.
