### ISSUE TITLE
dark title bar on Linux (wayland) not working

### ISSUE THREAD

**Issue by jalberto** [alacritty/alacritty#3230]
even using 'gtk_theme_variant: dark' the title bar always remains white.

### System

OS: Linux
Version: 0.4.1
Linux/BSD: Wayland, Gnome

**Comment by chrisduerr** [comment]
The theme variant is only used for X11. Due to the brilliant design of Wayland, such a thing isn't possible anymore.

You'll have to wait for https://github.com/alacritty/alacritty/issues/2092 and then your theme will be set based on your colorscheme.

**Comment by kchibisov** [comment]
>Due to the brilliant design of Wayland, such a thing isn't possible anymore.

this is a GNOME thing, and not a Wayland thing in general. KDE/wlroots based clients has server side decorations, so all windows can look nice.

**Comment by fal3n-4ngel** [comment]
You could modify the Desktop Entry (The desktop shortcut) to force it to use the xwayland path & decorate the window correctly.
You can find it in the .local/share folder or wherever your os stores the desktop entry
NB : I use Arch , hope it works for others too


Alacritty.desktop
```
[Desktop Entry]
Type=Application
TryExec=alacritty
Exec=env WINIT_UNIX_BACKEND=x11 alacritty
Icon=Alacritty
Terminal=false
Categories=System;TerminalEmulator;

Name=Alacritty
GenericName=Terminal
Comment=A fast, cross-platform, OpenGL terminal emulator
StartupWMClass=Alacritty
Actions=New;

X-Desktop-File-Install-Version=0.26

[Desktop Action New]
Name=New Terminal
Exec=alacritty
```
