### ISSUE TITLE
ISO-8859-1 encoded characters not showing up in the output

### ISSUE THREAD

**Issue by BrandtM** [alacritty/alacritty#3242]
### System

OS: Linux
Version: 0.4.1
Arch Linux, KDE + i3

### Behaviour in Konsole with encoding set to UTF-8  

```
$ php -a  
Interactive shell

php > echo chr(196);
�
```  

Performing the above PHP command with encoding set to ISO-8859-1 yields the following:  

```  
php > echo chr(196);
Ä
```  

### Behaviour in alacritty  

```
php > echo chr(196);

php >
```  

I was troubleshooting an encoding error and found out that I was mislead by alacritty swallowing some characters that Konsole doesn't hide.

**Comment by kchibisov** [comment]
Also, what's your `locale` output in alacritty?

**Comment by BrandtM** [comment]
@kchibisov so I've just replicated it with python and the python output is fine:  
```
>>> chr(196)
'Ä'
```  

I've looked at the documentation and PHP's `chr` generates a single-byte ISO-8859 character, whereas python appears to produce a Unicode character.  
From the python docs:  
> Return the string representing a character whose Unicode code point is the integer i.  

`locale` outputs the following:  
```
$ locale                                                                                                                                                                                                                        130 ↵
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by kchibisov** [comment]
What's your output for `echo -e "\xc4"`?

**Comment by kchibisov** [comment]
locale seems fine, so you should tell me what to do with php to repro your issue.

**Comment by BrandtM** [comment]
```  
$ echo -e "\xc4"

```  
With Konsole I get:  
```
$ echo -e "\xc4"                                                                                                                                                                                                                                                                    
�
```

> tell me what to do with php to repro your issue  
 
Haven't you reproduced it already in https://github.com/alacritty/alacritty/issues/3242#issuecomment-577229848?  

Your output was:  
```
php -a
Interactive shell

php > echo chr(196);
�
```  
Which is already different from my output:  
```
$ php -a
Interactive shell

php > echo chr(196);

php >
```  

I really don't know what else could be causing this.

**Comment by kchibisov** [comment]
I was thinking that you want this in alacritty.
```
php > echo chr(196);
Ä
```

What's your font in alacritty? Is it correct that selection everything from alacritty also don't show this character later(just checking)?

**Comment by kchibisov** [comment]
Oh, btw are you inside tmux/screen or running things without it? Like I can repro your issue with `tmux` in xterm/alacritty.

**Comment by BrandtM** [comment]
> Is it correct that selection everything from alacritty also don't show this character later  

Correct, I copied the selection into the issue here and there was nothing that was shown after selecting it.  

> are you inside tmux/screen or running things without it?  

Yes I was using tmux the entire time. Without tmux I get this:  

```
$ php -a
Interactive shell

php > echo chr(196);
�
 php >
```  
Slightly better but still not an Ä.  

> What's your font in alacritty?  

Not exactly sure how to figure this out. In my alacritty.yml the font family is commented out. 
My /etc/vconsole.conf says `FONT=ter-118n`

**Comment by kchibisov** [comment]
With tmux is a correct behavior for your UTF-8 thing, xterm is doing the same here. How did you change encoding in konsole?

**Comment by kchibisov** [comment]
This is font for vconsole(tty thing) not for alacritty. I'd assume that you're using default "monospace" font of your system here.

**Comment by BrandtM** [comment]
> How did you change encoding in konsole?  

It was a menu which allows one to change the encoding on the fly.

**Comment by kchibisov** [comment]
well, I guess this is an answer, since default konsole is outputting the same output as an alacritty as far as I can see.

The thing that controls encoding is `LC_CTYPE`, as far as I can see we're not following it closely, so by setting `env LC_CTYPE=en_US.ISO-8859-1 alacritty` we should probably use a different encoding for characters and print a proper character. However I'm not sure whether following some ancient things make sense tbh.

cc @chrisduerr .

**Comment by BrandtM** [comment]
> However I'm not sure whether following some ancient things make sense tbh.  

Honestly because tmux contributes like 80% to this bug (I just checked Konsole + tmux and it's broken to) I'd be in favor of closing this issue.

**Comment by kchibisov** [comment]
Well, let's just at least discuss it, however I'm also in favor of closing it.

**Comment by kchibisov** [comment]
After some discussion on IRC we decided to close this issue, since it's not something desired and users should use UTF-8 encoding for most things this days. Some terminals doesn't even accept en_US.ISO-8859-1 as locale and just crash, etc.
