### ISSUE TITLE
Failure to detect full URL containing unclosed single quote

### ISSUE THREAD

**Issue by ifreund** [alacritty/alacritty#3247]
### Reproduction Steps

Here an example link to display this bug:
```
echo "https://example.rs/alacritty's_thing.html"
```
The URL mouseover highlight ends at the single quote and when clicking on it only the URL up to that point is opened in the browser. 

Closing the single quote does fix things as can be seen by adding one to the end of the link:
```
echo "https://example.rs/alacritty's_thing.html'"
```

### System

OS: Linux
Version: 0.4.1
Linux/BSD: Wayland (sway)

**Comment by chrisduerr** [comment]
This should be fixed in https://github.com/alacritty/urlocator/pull/1.

**Comment by chrisduerr** [comment]
I'll release a new urlocator version once a new Alacritty release is planned, since I don't think this change is significant enough to warrant an immediate release.

If you wish to make use of it already until then, you'll have to build against the git version of urlocator.

**Comment by ifreund** [comment]
Perfect, thank you for the very quick response!
