### ISSUE TITLE
panicked at 'Unable to spawn shell: The system cannot find the file specified. (os error 2)', alacritty_terminal\src\tty\windows\conpty.rs:250:5

### ISSUE THREAD

**Issue by michelepagot** [alacritty/alacritty#3249]
panicked when starting with verbosity

### System

OS: Windows10
Version: > alacritty 0.4.1 (4d9253b) from https://github.com/alacritty/alacritty/releases/download/v0.4.1/Alacritty-v0.4.1-windows-portable.zip

> Created log file at "C:\Users\MEMEME~1\AppData\Local\Temp\Alacritty-13968.log"
[2020-01-25 22:10] [INFO] Welcome to Alacritty
[2020-01-25 22:10] [INFO] Device pixel ratio: 1.5
[2020-01-25 22:10] [INFO] Initializing glyph cache...
[2020-01-25 22:10] [INFO] ... finished initializing glyph cache in 0.0507749s
[2020-01-25 22:10] [INFO] Cell Size: 12 x 25
[2020-01-25 22:10] [INFO] Padding: 0 x 0
[2020-01-25 22:10] [INFO] Width: 1418, Height: 725
[2020-01-25 22:10] [INFO] PTY Dimensions: Line(29) x Column(118)
panicked at 'Unable to spawn shell: The system cannot find the file specified. (os error 2)', alacritty_terminal\src\tty\windows\conpty.rs:250:5

**Comment by kchibisov** [comment]
well, it can't find shell on your system (ConPTY thing). Could you try  setting this to true https://github.com/alacritty/alacritty/blob/f48204eee20ddb0a3b23c10d27e3c75fbcd3f7f3/alacritty.yml#L345

**Comment by sachTom** [comment]
Ended up here, with the same problem.
Setting the variable to TRUE give this:

---------------------------
Alacritty: Runtime Error
---------------------------
panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: SpawnCreateProcessFailed, message: "CreateProcess failed (error code 2)" }', src\libcore\result.rs:1165:5

**Comment by kchibisov** [comment]
@sachTom Could you try v0.4.0?

**Comment by sachTom** [comment]
So, now the console starts but it's blank and it can't take any input.
(same with winpty_backend on false or true)
Got some logs btw:

[2020-01-29 17:07] [INFO] Welcome to Alacritty
[2020-01-29 17:07] [INFO] Configuration loaded from "C:\Users\Tom\AppData\Roaming\alacritty\alacritty.yml"
[2020-01-29 17:07] [INFO] Device pixel ratio: 1.1666666666666667
[2020-01-29 17:07] [INFO] Initializing glyph cache...
[2020-01-29 17:07] [INFO] ... finished initializing glyph cache in 0.0164029s
[2020-01-29 17:07] [INFO] Cell Size: 9 x 20
[2020-01-29 17:07] [INFO] Padding: 0 x 0
[2020-01-29 17:07] [INFO] Width: 1902, Height: 976
[2020-01-29 17:07] [INFO] PTY Dimensions: Line(48) x Column(211)
[2020-01-29 17:07] [INFO] Using Winpty agent
[2020-01-29 17:07] [INFO] Initialisation complete

**Comment by kchibisov** [comment]
I mean it's likely something odd is going on and you can't start WinPTY or ConPTY in general. I guess you've took binaries from our release page, right?

**Comment by sachTom** [comment]
yep, I got the binaries from the release page and no prompt or nothing similar

**Comment by kchibisov** [comment]
Could you set a shell to cmd.exe in alacritty?

**Comment by sachTom** [comment]
Sorry for the delay, not sure about what u're asking... I cannot type anything in alacritty

**Comment by kchibisov** [comment]
I'm asking to use `cmd.exe` here as `shell` https://github.com/alacritty/alacritty/blob/871a22eaf4b8fce71fb616ca909a0f2b46802716/alacritty.yml#L327

**Comment by sachTom** [comment]
Oh yeah ok, thought it was that. Same result btw.

**Comment by chrisduerr** [comment]
@sachTom Which exact Windows 10 version are you running?

**Comment by cup** [comment]
This worked for me. First create this or similar:

~~~
C:\Users\Steven\AppData\Roaming\alacritty\alacritty.yml
~~~

https://github.com/alacritty/alacritty#windows-1

with this content:

~~~
shell:
   program: cmd
~~~

You can use other shells in place of `cmd`.

**Comment by kchibisov** [comment]
Yeah, we're calling powershell by default IIRC, so maybe changing it to cmd(cmd.exe) as default could be better. However it was stated that this wasn't working for some folks here.

**Comment by Tarnadas** [comment]
I have the same problem and can confirm that downgrading to 0.4.0 fixed the conPTY problem. I'm using Debian WSL shell.

**Comment by chrisduerr** [comment]
Has anyone tried to reproduce this on the latest master? There have been some changes to this since 0.4.1.

**Comment by SirJson** [comment]
Just stumbled upon that issue, switching the default shell from pwsh to cmd fixed it.
Maybe it couldn't find pwsh because I'm using PowerShell 7.0.0-rc.2?

**Comment by Tarnadas** [comment]
I just testet to run the latest master under Windows and it's working fine. Then I tried to reproduce this bug by checking out tags/v0.4.1 and it worked as well...
Apparently the bug is gone for me, even when I use the released version on Github.

I normally run under Linux and I haven't made any changes to my Windows partition except there was a Windows Update recently, which rather seems unrelated to the problem, but for the sake of completion, I will list them here:
https://support.microsoft.com/en-us/help/4494174/kb4494174-intel-microcode-updates
https://support.microsoft.com/en-us/help/4538156/kb4538156-cumulative-update-for-net-framework

relevant systeminfo output:
```
Betriebssystemname:                            Microsoft Windows 10 Pro
Betriebssystemversion:                         10.0.17763 Nicht zutreffend Build 17763
Betriebssystemhersteller:                      Microsoft Corporation
Systemhersteller:                              Dell Inc.
Systemmodell:                                  Precision 5520
Systemtyp:                                     x64-based PC
Prozessor(en):                                 1 Prozessor(en) installiert.
                                               [01]: Intel64 Family 6 Model 158 Stepping 9 GenuineIntel ~3001 MHz
```

**Comment by chrisduerr** [comment]
Would be good to have @michelepagot check this again. Doesn't make much sense to try and identify/reproduce/fix this if it isn't even certain if this bug still exists.

**Comment by bradking** [comment]
I just encountered this issue using [`Alacritty-v0.6.0-portable.exe`](https://github.com/alacritty/alacritty/releases/download/v0.6.0/Alacritty-v0.6.0-portable.exe) from the releases page.

The problem occurs when the [`default_shell`](https://github.com/alacritty/alacritty/blob/v0.6.0/alacritty_terminal/src/tty/windows/mod.rs#L186), `powershell`, is not in the `PATH`.

Workarounds include:

*   Add `C:\Windows\system32\WindowsPowerShell\v1.0` to the `PATH`.
*   Or, create `%APPDATA%\alacritty\alacritty.yml` with content:

    ````yml
    shell:
      program: C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe
    ````

    to use powershell, or switch to `cmd`:

    ````yml
    shell:
      program: cmd
    ````

**Comment by chrisduerr** [comment]
Powershell should be part of the PATH by default on Windows. So if it is not, people have probably messed up their system configuration. In that case I recommend unmessing it up.

**Comment by Jarmos-san** [comment]
Not necessarily. Do note, Windows PowerShell is different from PowerShell Core (_which is cross-platform_). And PowerShell Core mightn't be available on `PATH`.
> Powershell should be part of the PATH by default on Windows.

For people stumbling across this thread you need to update your Alacritty config file as @bradking [stated (comment)](https://github.com/alacritty/alacritty/issues/3249#issuecomment-734037185).

While configuring as such:

```yaml
shell:
  program: $ENV:PROGRAMFILES\PowerShell\7\pwsh.exe
```

would've been convenient like it does while configuring Windows Terminal, for Alacritty, it doesn't. So you've to configure it as such:

```yaml
shell:
  program: C:\\Program Files\\PowerShell\\7\\pwsh.exe
```

And that's assuming you've installed PowerShell Core to it's default location.

**Comment by cod1r** [comment]
For some reason, I run into the same issue but then once I start the windows terminal, it fixes the issue. weird...

**Comment by jm-alan** [comment]
I've been having this issue for a while now, though it briefly went away with a Windows update, then another update brought it back again.
I have my alacritty.yml configured as follows:
```yml
shell:
  program: C:\Windows\System32\wsl.exe
  args:
    - -d
    - Ubuntu
```
Near-identical to the above, this error goes away if I launch `wsl.exe` through some other means first, like Windows Terminal or simply running `wsl` from the Run prompt
For some reason, Alacritty seems to struggle to cold-start wsl, but can launch a new tty instance if wsl is already running.

**Comment by AJHissh** [comment]
To anyone reading this using windows, make sure your PowerShell is added to Path.

C:\Windows\system32\WindowsPowerShell\v1.0 - add this to your Path.

**Comment by Night3y3** [comment]
Hey after that latest update i.e. [alacritty 0.13.0 (78fa4d6)](https://github.com/alacritty/alacritty/releases/tag/v0.13.0)

It is using `%APPDATA%\alacritty\alacritty.toml`

This is the alacritty.toml file I am using
[toml-to-txt.txt](https://github.com/alacritty/alacritty/files/13835260/toml-to-txt.txt)

My PowerShell is added to Path
Yet I am receiving this error
`panicked at alacritty_terminal\src\tty\windows\conpty.rs:235:5:
Unable to spawn shell: The system cannot find the file specified. (os error 2)`

Please kindly help

**Comment by maxhaice2** [comment]
> Hey after that latest update i.e. [alacritty 0.13.0 (78fa4d6)](https://github.com/alacritty/alacritty/releases/tag/v0.13.0)
> 
> It is using `%APPDATA%\alacritty\alacritty.toml`
> 
> This is the alacritty.toml file I am using [toml-to-txt.txt](https://github.com/alacritty/alacritty/files/13835260/toml-to-txt.txt)
> 
> My PowerShell is added to Path Yet I am receiving this error `panicked at alacritty_terminal\src\tty\windows\conpty.rs:235:5: Unable to spawn shell: The system cannot find the file specified. (os error 2)`
> 
> Please kindly help

Seems like the path is wrong, you should be able to fix specifying the clear path like
`shell:
  program: C:\\Program Files\\PowerShell\\7\\pwsh.exe`
