### ISSUE TITLE
bad mac installation - no yml

### ISSUE THREAD

**Issue by flowcharterappowner** [alacritty/alacritty#3250]
High Sierra.
I did the brew cask install.
No alacritty dir found in ~/.config !
Coped the one from your github repo, and changed to larger point size. Nope !
You can only have one window at any time ?

**Comment by kchibisov** [comment]
We're not creating random non-temporary dirs/files on your system. If you want to add your config, you should do it manually.

Add binding for this action to get more windows https://github.com/alacritty/alacritty/blob/f48204eee20ddb0a3b23c10d27e3c75fbcd3f7f3/alacritty.yml#L488
