### ISSUE TITLE
Blurry box-drawing characters

### ISSUE THREAD

**Issue by noscript** [alacritty/alacritty#3262]
All the box characters have some sort of bloom around, while in gnome-terminal everything is pixel perfect.

### System
OS: Linux
Version: alacritty 0.4.2-dev (871a22e)
Linux: X11, Openbox, compton
Font: Consolas

To reproduce
```sh
$ cat <<EOF
┌─┬┐  ╔═╦╗  ╓─╥╖  ╒═╤╕
│ ││  ║ ║║  ║ ║║  │ ││
├─┼┤  ╠═╬╣  ╟─╫╢  ╞═╪╡
└─┴┘  ╚═╩╝  ╙─╨╜  ╘═╧╛
┌───────────────────┐
│  ╔═══╗ Some Text  │▒
│  ╚═╦═╝ in the box │▒
╞═╤══╩══╤═══════════╡▒
│ ├──┬──┤           │▒
│ └──┴──┘           │▒
└───────────────────┘▒
 ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
EOF
```

Alacritty:
![alacritty](https://user-images.githubusercontent.com/717109/73380542-eae72580-42cc-11ea-8c87-fd7e4f27a08f.png)

Gnome-terminal:
![gnome-terminal](https://user-images.githubusercontent.com/717109/73380559-f0447000-42cc-11ea-89d8-cecbf18c3cd9.png)

**Comment by kchibisov** [comment]
Alacritty is using your font to do this and not drawing lines by itself, just looking at a screenshot you can see how different the thing on a bottom is. In alacritty it's the one from your font, and I'd assume gnome-terminal drawn it by itself.

I'm curios whether changing font in gnome-terminal could actually change the line drawing chars. For example by using `DejaVu Sans Mono`. You can try compare it to alacritty, I guess.

**Comment by chrisduerr** [comment]
Alacritty has no desire to replace glyphs with our own versions. If you don't like the way the glyphs look, you should probably pick a different font. We strive to render the fonts in use as well as possible.

If you're bothered by the overlapping of lines causing problems, that's a bug we plan to fix though and it is tracked in https://github.com/alacritty/alacritty/issues/118.

**Comment by astier** [comment]
I tried different fonts like DejaVu Sans Mono, Hack Nerd Font, etc. but none could solve this issue. Does anybody know which fonts fix this?
