### ISSUE TITLE
License in .deb file shows Proprietary

### ISSUE THREAD

**Issue by aeons** [alacritty/alacritty#3286]
I just installed v0.4.1 from the .deb file downloaded from the releases page, and the license field shows proprietary.

![image](https://user-images.githubusercontent.com/1432894/73644082-f9d72a80-4674-11ea-83b3-ca0825da50bb.png)

**Comment by kchibisov** [comment]
Could you show where are you looking at this and with what tool? As far as I can see it should use or [LICENSE file](https://github.com/alacritty/alacritty/blob/master/LICENSE-APACHE) from repo, we set it [there](https://github.com/alacritty/alacritty/blob/74039bde1249ad77fe8d2d85ec6eb1f363f5c511/alacritty/Cargo.toml#L60).

**Comment by aeons** [comment]
The screenshot is from the Ubuntu Software application, which is the default for .deb files on Ubuntu.

Yeah, I dug a bit around as well, and thought everything looked peachy.

The license file is picked up and installed at `/usr/share/doc/alacritty/copyright`, so maybe it's the license field that's not parsed correctly?

I could find other Apache licensed things in the same app.
![image](https://user-images.githubusercontent.com/1432894/73724182-103fbd80-472b-11ea-8f0a-790264f0f233.png)

**Comment by aeons** [comment]
It might be a bug in Software Center: https://bugs.launchpad.net/ubuntu/+source/software-center/+bug/435183

**Comment by aeons** [comment]
I just tried downloading the VS Code .deb file and that shows as proprietary as well, so it's not something we can fix here, I think.
They had an issue about is as well: https://github.com/Microsoft/vscode/issues/3321

**Comment by chrisduerr** [comment]
> I just tried downloading the VS Code .deb file and that shows as proprietary as well, so it's not something we can fix here, I think.

Important to note that some VS Code distributions are indeed distributed with non-free licenses. So probably not the best example because it depends on what kind of VS Code you're talking about.
