### ISSUE TITLE
Error creating GL context

### ISSUE THREAD

**Issue by OnurKader** [alacritty/alacritty#3287]
I update my system, libgl as well, every two days.
And after the last update Alacritty fails to launch. Other terminals like Terminator or ST or other windows launch fine
### System

OS: Linux/Ubuntu 19.10
Version: alacritty 0.4.1
Linux: X11, i3-gaps with compton

### Config
https://pastebin.com/8iMBhe4N

### Logs
Crashes: Can't open window, no GL context found
Output of alacritty -vvv
```
Created log file at "/tmp/Alacritty-27915.log"
[2020-02-03 12:48] [INFO] Welcome to Alacritty
[2020-02-03 12:48] [INFO] Configuration loaded from "/home/beronthecolossus/.config/alacritty/alacritty.yml"
[2020-02-03 12:48] [DEBUG] Estimated DPR: 1
[2020-02-03 12:48] [DEBUG] Estimated Cell Size: 10 x 19
[2020-02-03 12:48] [DEBUG] Estimated Dimensions: None
Alacritty encountered an unrecoverable error:
	Error creating GL context; Received multiple errors. Errors: `[OsError("Could not create EGL display object"), OsError("Couldn\'t find any available vsync extension")]`
```
Font/Terminal size: Can't gather from the terminal, but main font is Noto Emoji Nerd Font with a size of 12.0
Keyboard and bindings: Can't get

glxinfo: https://pastebin.com/LbM5mNWt

Latest lines from my apt history:
```
Setting up mesa-vulkan-drivers:amd64 (20.1~git2002030730.a4e627~oibaf~e)
Setting up mesa-vulkan-drivers:i386 (20.1~git2002030730.a4e627~oibaf~e)
Setting up mesa-vdpau-drivers:amd64 (20.1~git2002030730.a4e627~oibaf~e)
Setting up libgles2-mesa-dev:amd64 (20.1~git2002030730.a4e627~oibaf~e)
Setting up libgbm1:amd64 (20.1~git2002030730.a4e627~oibaf~e)
Setting up libxatracker2:amd64 (20.1~git2002030730.a4e627~oibaf~e)
Setting up libegl1-mesa:amd64 (20.1~git2002030730.a4e627~oibaf~e)
Setting up libglapi-mesa:amd64 (20.1~git2002030730.a4e627~oibaf~e)
Setting up libglapi-mesa:i386 (20.1~git2002030730.a4e627~oibaf~e)
Setting up libgl1-mesa-dev:amd64 (20.1~git2002030730.a4e627~oibaf~e)
Setting up mesa-common-dev:amd64 (20.1~git2002030730.a4e627~oibaf~e)
Setting up libosmesa6:amd64 (20.1~git2002030730.a4e627~oibaf~e)
Setting up libosmesa6:i386 (20.1~git2002030730.a4e627~oibaf~e)
Setting up libegl1-mesa-dev:amd64 (20.1~git2002030730.a4e627~oibaf~e)
Setting up libgl1-mesa-dri:amd64 (20.1~git2002030730.a4e627~oibaf~e)
Setting up libgl1-mesa-dri:i386 (20.1~git2002030730.a4e627~oibaf~e)
Setting up libegl-mesa0:amd64 (20.1~git2002030730.a4e627~oibaf~e)
Setting up libglx-mesa0:amd64 (20.1~git2002030730.a4e627~oibaf~e)
Setting up libglx-mesa0:i386 (20.1~git2002030730.a4e627~oibaf~e)
Setting up libgl1-mesa-glx:amd64 (20.1~git2002030730.a4e627~oibaf~e)
Setting up libgl1-mesa-glx:i386 (20.1~git2002030730.a4e627~oibaf~e)
```

**Comment by kchibisov** [comment]
Ehm, Are you running it in a virtual machine? It seems like your OpenGL version is 3.1, but we're requiring 3.3 to run. Maybe some update broke your GL version or something like that.

**Comment by OnurKader** [comment]
Hmm I'm not using a VM. I'll try to update to a newer version of OpenGL, I might not be able to do it today. But I'll reply with the results. 

Thanks for the quick reply, have a nice day!

**Comment by kchibisov** [comment]
I mean if you look at `glxinfo` you're running llvmpipe as your video driver or something like that.

**Comment by OnurKader** [comment]
Yes, I remember the vendor and the renderer being different. Most likely Mesa. I think something went very wrong in some update. This looks like it's entirely on my end, need to mess with the OpenGL installation.

There weren't any OpenGL related issues recently, so I think I am going to close this issue.
Thank you very much for your time!

**Comment by NickeZ** [comment]
I fixed this issue by reverting the oibaf ppa

```
sudo ppa-purge ppa:oibaf/graphics-drivers
```

**Comment by aathif394** [comment]
Could you please give the output of `glxinfo`
