### ISSUE TITLE
hide_when_typing hides mouse cursor forever

### ISSUE THREAD

**Issue by virus-found** [alacritty/alacritty#3291]
### System
OS: Void Linux
Version: `alacritty 0.4.2-dev (74039bd)`
Wayland, sway

```
# If this is `true`, the cursor is temporarily hidden when typing.
hide_when_typing: true
```
If this is set, then on any key press the mouse cursor is hidden **forever**, but not **temporarily**, as stated in the description.
Though switching workspaces in sway brings the mouse cursor back, until the next key press.

Somewhat related to #2761

**Comment by kchibisov** [comment]
I can't repro and this option works for me as expected on sway + Wayland on the latest master. I feel like your cursor theme is messed up, so when we're hiding your cursor it hides for ever, since we can't set a proper theme. How is your cursor looks like in terminal? Is it Select text thing or a Left pointer?

**Comment by kchibisov** [comment]
The issue you've linked isn't related.

**Comment by chrisduerr** [comment]
@virus-found Just to verify, you are talking about the mouse cursor, right?

**Comment by virus-found** [comment]
> I can't repro and this option works for me as expected on sway + Wayland on the latest master. I feel like your cursor theme is messed up, so when we're hiding your cursor it hides it forever, since we can't set a proper theme.

I wonder what can be done here, as I've never customized any cursor themes. 
Btw my distro is Void Linux.

> How is your cursor looks like in terminal? Is it Select text thing or a Left pointer?

When it's visible - it's a Left pointer.

> @virus-found Just to verify, you are talking about the mouse cursor, right?

Yes, exactly.

**Comment by kchibisov** [comment]
Well, the default cursor in alacritty is `Text` When it's visible - it's a Left pointer.


>I wonder what can be done here, as I've never customized any cursor themes.

You don't need to customize it, you should just set it.

You likely should do something like that in `~/.icons/default/index.theme`
```ini
[icon theme] 
Inherits=Adwaita
```

not sure what themes do you have, but `Adwaita` is a common one on tons of distros.

**Comment by virus-found** [comment]
This solved it, thanks.
The mouse cursor in alacritty now looks like "select text thingie", which is quite by me.

This solution should be added to FAQ or wiki, if you ask me.

**Comment by kchibisov** [comment]
We're using libwayland-cursor.so for cursor theming as well as many apps on Wayland, so you should make it find cursor theme. Not sure about GTK here though.
