### ISSUE TITLE
loose powerline fonts display

### ISSUE THREAD

**Issue by jeremie-H** [alacritty/alacritty#3294]
Hi,

I've just update the alacritty source, (from **12e211d** to **b72903e**) and loose my powerline fonts display.

As you can see in the screen capture  
> version 12e211d
![screen_before](https://user-images.githubusercontent.com/11060749/73837255-6555ff00-4811-11ea-8f69-45dd961df9e8.png)

> version b72903e
![screen_after](https://user-images.githubusercontent.com/11060749/73837253-64bd6880-4811-11ea-9da9-63aaa2bff420.png)

The changes i've made : 
```shell
rustup update stable
cargo install cargo-deb
cargo deb --install -p alacritty
```

### System

OS: Linux Ubuntu 19.10
Version: `alacritty 0.4.2-dev (b72903e)`
Linux: X11, Gnome

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: 
`alacritty -vv`
```
Created log file at "/tmp/Alacritty-18983.log"
[2020-02-05 12:19] [INFO] Welcome to Alacritty
[2020-02-05 12:19] [INFO] Configuration loaded from "/home/xxxxx/.config/alacritty/alacritty.yml"
[2020-02-05 12:19] [DEBUG] Estimated DPR: 1
[2020-02-05 12:19] [DEBUG] Estimated Cell Size: 9 x 18
[2020-02-05 12:19] [DEBUG] Estimated Dimensions: None
[2020-02-05 12:19] [INFO] Device pixel ratio: 1
[2020-02-05 12:19] [INFO] Initializing glyph cache...
[2020-02-05 12:19] [INFO] ... finished initializing glyph cache in 0.019446486s
[2020-02-05 12:19] [INFO] Cell Size: 9 x 18
[2020-02-05 12:19] [INFO] Padding: 0 x 0
[2020-02-05 12:19] [INFO] Width: 800, Height: 600
[2020-02-05 12:19] [INFO] PTY Dimensions: Line(33) x Column(88)
[2020-02-05 12:19] [INFO] Initialisation complete
[2020-02-05 12:19] [DEBUG] Term::resize dimensions unchanged
[2020-02-05 12:19] [INFO] Width: 800, Height: 600
[2020-02-05 12:19] [INFO] Goodbye
Deleted log file at "/tmp/Alacritty-18983.log"
```
Keyboard and bindings: `alacritty --print-events`

**Comment by kchibisov** [comment]
use `fc-match -s "MY_FONT:style=Regular` to debug it. The fallback was changed recently to be faster and that you can actually control it. Old one was impossible to control. Basically with these powerline symbols you're getting Fontconfig file, which you should enable (if you're talking about package from your distro).

`ln -s /etc/fonts/conf.avail/10-powerline-symbols.conf /etc/fonts/conf.d/`

also, make sure you can actually see a font with your powerline symbols in `fc-match -s "MY_FONT:style=Regular` as it was stated.

**Comment by jeremie-H** [comment]
thks @kchibisov ,

in my alacritty.xml, i've got the following configuration
```yaml
font:
  normal:
    family: JetBrainsMono
    style: regular
```

here my result from cmd : `fc-match -s "JetBrainsMono:style=Regular`

```
JetBrainsMono-Regular.ttf: "JetBrains Mono" "Regular"
DejaVuSans.ttf: "DejaVu Sans" "Book"
DejaVuSans-Bold.ttf: "DejaVu Sans" "Bold"
DejaVuSans-Oblique.ttf: "DejaVu Sans" "Oblique"
DejaVuSans-BoldOblique.ttf: "DejaVu Sans" "Bold Oblique"
n019003l.pfb: "Nimbus Sans L" "Regular"
Loma.ttf: "Loma" "Regular"
Waree.ttf: "Waree" "Regular"
Umpush-Bold.ttf: "Umpush" "Bold"
Laksaman.ttf: "Laksaman" "Regular"
NotoSansCJK-Regular.ttc: "Noto Sans CJK JP" "Regular"
DroidSansFallbackFull.ttf: "Droid Sans Fallback" "Regular"
KhmerOS.ttf: "Khmer OS" "Regular"
MuktiNarrow.ttf: "Mukti Narrow" "Regular"
padmaa-Medium-0.5.ttf: "padmaa" "regular"
padmaa.ttf: "padmaa" "Normal"
padmaa-Bold.1.1.ttf: "padmaa-Bold.1.1" "Bold.1.1"
Lohit-Bengali.ttf: "Lohit Bengali" "Regular"
Lohit-Gujarati.ttf: "Lohit Gujarati" "Regular"
Lohit-Tamil.ttf: "Lohit Tamil" "Regular"
Meera-Regular.ttf: "Meera" "Regular"
Lohit-Kannada.ttf: "Lohit Kannada" "Regular"
Lohit-Telugu.ttf: "Lohit Telugu" "Regular"
lklug.ttf: "LKLUG" "Regular"
FreeSans.ttf: "FreeSans" "Regular"
FreeMono.ttf: "FreeMono" "Regular"
FreeSerif.ttf: "FreeSerif" "Regular"
opens___.ttf: "OpenSymbol" "Regular"
Rachana-Regular.ttf: "Rachana" "Regular"
Norasi.ttf: "Norasi" "Regular"
KacstOne.ttf: "KacstOne" "Regular"
Purisa.ttf: "Purisa" "Regular"
Padauk-Regular.ttf: "Padauk" "Regular"
Hack-Regular.ttf: "Hack" "Regular"
Hack Regular Nerd Font Complete Mono.ttf: "Hack Nerd Font Mono" "Regular"
Lohit-Devanagari.ttf: "Lohit Devanagari" "Regular"
DejaVuMathTeXGyre.ttf: "DejaVu Math TeX Gyre" "Regular"
MesloLGS NF Regular.ttf: "MesloLGS NF" "Regular"
Inconsolata Regular Nerd Font Complete Mono.otf: "Inconsolata Nerd Font Mono" "Regular"
LiberationMono-Regular.ttf: "Liberation Mono" "Regular"
TibetanMachineUni.ttf: "Tibetan Machine Uni" "Regular"
Manjari-Regular.otf: "Manjari" "Regular"
AbyssinicaSIL-R.ttf: "Abyssinica SIL" "Regular"
Pothana2000.ttf: "Pothana2000" "Regular"
chandas1-2.ttf: "Chandas" "Regular"
Pagul.ttf: "Pagul" "Regular"
mry_KacstQurn.ttf: "mry_KacstQurn" "Regular"
Phetsarath_OT.ttf: "Phetsarath OT" "Phetsarath OT"
Ubuntu-R.ttf: "Ubuntu" "Regular"
Samyak-Devanagari.ttf: "Samyak Devanagari" "Regular"
DejaVuSerif.ttf: "DejaVu Serif" "Book"
Rekha.ttf: "Rekha" "Medium"
utkal.ttf: "ori1Uni" "Medium"
NotoColorEmoji.ttf: "Noto Color Emoji" "Regular"
```
I don't like hard link to make like that.  
It's working well with gnome-terminal, and any other apps without this kind of trick.  
In addition, it was perfect before the upgrade.

**Comment by kchibisov** [comment]
>I don't like hard link to make like that.

It is a symbolic link.

>It's working well with gnome-terminal, and any other apps without this kind of trick.

It wasn't a powerline symbols anyway.

>In addition, it was perfect before the upgrade.

pure luck that it was working before.

>If i try to make link, it was already link to another file :

You'll likely need to add your font there, since it covers only portion of a common fonts.

**Comment by jeremie-H** [comment]
I use this font :
> https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/JetBrainsMono/Regular/complete

I download it and put in my `~/.local/share/fonts` directory, then execute
`fc-cache -f -v`

I wont erase an existing link in my clean installation with yours. It's dirty from my mind.

> pure luck that it was working before.
well, i don't consider IT science like _luck_ ;-) i prefer understand **why** before to make any weird changes.  

Meanwhile, i'll go back to gnome-terminal,
if needed, i can get more logs

**Comment by kchibisov** [comment]
This is an explanation on why it was pure luck before.

```
Previous implementation was querying Fontconfig using `charset` in a pattern,
which was leading to unpredictable fallbacks in some cases, since Fontconfig
was picking the font with the most coverage for a given charset, regardless of
user configuration. Moreover all fallback was based on font_match which is
extremely slow for such performance sensitive task as a fallback, so alacritty
had a hard times on vtebench's unicode-random-write.

The new approach is to use some internal fallback list from font_sort
and iterate over it to get a proper fallback font, since it matches the
following example query from `fc-match`:

`fc-match -s "monospace:pixelsize=X:style=Y"

That being said it's more intuitive for users to setup their system Fontconfig
fallback, and also most applications are doing similar things. Moreover the new
implementation uses internal caches over Fontconfig API when possible and
performs font matches only once during load of requested font with font_sort,
which leads to dramatically improved performance on already mentioned
vtebench's unicode-random-write.

```

>well, i don't consider IT science like luck ;-) i prefer understand why before to make any weird changes.

Fontconfig decided for you what to use here, your Fontconfig rules wasn't working at all before. It's not my dirty link, it's a thing provided by a package and it how Fontconfig configuration works and worked for years. All fontconfig rules are in `/etc/fonts/conf.avail` and all used rules are in `/etc/fonts/cond.d`. You can apply them to change fpnt rendering fallbacks, preferences.

The file I've linked you is speculating with fallback for powerline symbols, if you're ignorant on how such fallback works, then it's up to you.  You can just open it with your editor and take a look on what it's doing. If you don't like changing things globaly, I'd recommend you to make all configuration in `~/.config/fontconfig/` and use `fc-conflist` to check that your file is in use. And refer on to user documentation on how it works.

GNOME terminal is drawing those characters(it's already doing something like that for other characters, like "line drawing" ones) for you likely without even using font + it uses pango.

**Comment by chrisduerr** [comment]
If multiple fonts provide the same glyph, there's no way to get the result that you want without telling fontconfig how the fallback should be performed.

We're happy to help you with this to figure out which rules are necessary and which fonts could be causing trouble, but things won't just magically work. In general the new font fallback is a lot more sane and should make troubleshooting easier than ever before.

**Comment by jeremie-H** [comment]
Ok, thanks for your explanation @kchibisov. I'll try with the local configuration like you propose in  `~/.config/fontconfig/`.

**Comment by jeremie-H** [comment]
Well, i've tried anything, but doesn't understand, it still doesnt work...
Some of other font works, but JetBrainsMono still doesn't work
in alacritty.xml i've got :
```yml
    #family: MesloLGM Nerd Font Mono
    family: JetBrainsMono
```
if i activate `MesloLGM Nerd Font Mono`, it's work well. 
I've tried to make the link as suggered by @kchibisov , but still the same issue.
I've tried to play with `~/.config/fontconfig/` still doesnt' work, so I'm giving up. If it isn't simple, i simply change the tool, sorry guys.
Good luck

**Comment by jeremie-H** [comment]
Well, i've tried anything wihtout any solutions. so I finish by changing the wanted font :(
