### ISSUE TITLE
How can I configure alacritty to work with MSYS2?

### ISSUE THREAD

**Issue by unphased** [alacritty/alacritty#3301]
I'm hoping I can use alacritty on windows locally, now that it works great for ssh to other hosts!

Usually I interchangeably use the terminal that comes with MSYS2 (which is mintty i believe), and the Git Bash that comes with Git for Windows. Both are fine, but do not offer the kind of configuration that I have come to rely on with Alacritty, which unifies my key bindings, across Linux and macOS. Given that alacritty is such a core part of my workflow, it would be really stupendous to be able to use it all the time on windows as well (whether that is with WSL or not -- I actually have not been interested in WSL1 but WSL2 I expect I'll take advantage of!). 

Anyone tried this or know how to hook it up? When starting alacritty on windows I seem to just get a powershell prompt, and although powershell is cool, it's really different from bash, and I'm not productive in it. 

It may be as simple as digging around to see where the MSYS2 bash program is and I should be able to just go launch alacritty with it and be off to the races. 

### System

OS: Windows
Windows: ConPTY (see `alacritty -v` output)

[2020-02-06 12:04] [INFO] Welcome to Alacritty
[2020-02-06 12:04] [INFO] Device pixel ratio: 1
[2020-02-06 12:04] [INFO] Initializing glyph cache...
[2020-02-06 12:04] [INFO] ... finished initializing glyph cache in 0.0008747s
[2020-02-06 12:04] [INFO] Cell Size: 8 x 17
[2020-02-06 12:04] [INFO] Padding: 0 x 0
[2020-02-06 12:04] [INFO] Width: 2517, Height: 1020
[2020-02-06 12:04] [INFO] PTY Dimensions: Line(60) x Column(314)
[2020-02-06 12:04] [INFO] Using ConPTY backend
[2020-02-06 12:04] [INFO] Initialisation complete

**Comment by kchibisov** [comment]
I know that you can run git bash or wsl1 in it. For wsl just type wsl.exe and you're good to go, similar to bash.

**Comment by chrisduerr** [comment]
Yeah, just set your `shell` in the Alacritty config to the `bash.exe` in git bash and you're good to go. That worked last time I used Windows.

**Comment by unphased** [comment]
great, looks like git bash should be easier to get going than MSYS2. I found the MSYS2 bash and it works but I think the environment is a bit messed up. Having alacritty on windows is super awesome. I love this project so much.

**Comment by unphased** [comment]
I don't have git bash installed since i had been using git via MSYS2 on this machine so far. I got the bash shell running fine in it (even fixed problems after i `tic`'d my terminfos) but zsh behaves strangely when ssh-ing to my work machine, which doesnt happen without my alacritty configuration. So there's some basic stuff that I think I should be able to work out. pretty sweet.

**Comment by chrisduerr** [comment]
Just fyi, if you're using Alacritty's terminfo you probably need to copy it to the servers you ssh into, or alias ssh to `TERM=xterm-256color ssh`.

**Comment by unphased** [comment]
I'm seeing some interesting behavior, which feels very close to being understood: 

If I spawn alacritty from windows explorer, running MSYS2 bash from it results in a messed up bash (some commands seem to be failing and my $PS1 doesnt render properly at all), but sshing to linux sees zsh and tmux working beautifully. 

If i spawn alacritty from MSYS2 bash, running bash from alacritty loads great (i think it's just $PATH honestly), and sshing to the linux sees zsh having weird extra output ending characters and tmux is totally garbled. 

So there's just some kind of msys2 incompat going on, but otherwise I already have workarounds, and my personal alacritty configuration works fine. I'll eventually figure out how to configure things to be totally smooth. I'm also hoping that with WSL2 I will no longer need to use MSYS2.

**Comment by jmatsushita** [comment]
This snippet worked for me

```
shell:
  program: C:\Program Files\Git\bin\bash.exe
  args:
  - --login
```

**Comment by jmatsushita** [comment]
And for msys2:
```
shell:
  program: C:\tools\msys64\usr\bin\bash.exe
  args:
  - --login
```

**Comment by SHJordan** [comment]
> program: C:\Program Files\Git\bin\bash.exe
>   args:
>   - --login

how would i set it to start on ~(%USERPROFILE%) directory tho?

**Comment by cindrmon** [comment]
> shell:
>   program: C:\Program Files\Git\bin\bash.exe
>   args:
>   - --login

```
working_directory: C:\Users\<username>
```

i don't really know if environment variables ever work when putting them in the config files for windows, but that's how you do it for me so far..

**Comment by Myrdden** [comment]
How do you set the path to inherit with this method?

**Comment by FunctionDJ** [comment]
I'd also like to start alacritty in the user folder by default but not override it for when it's started at a specific location

**Comment by Myrdden** [comment]
@SHJordan @FunctionDJ Not sure if this is the *best* solution, but, with
```yml
shell:
  program: C:\MSYS\usr\bin\bash.exe
  args:
    - --login
```
The easiest way I could find to get everything to work smoothly was simply to symlink MSYS's `/usr/home/[user]` directory to the Windows user directory with a cmd.exe instance in Administrator mode, and then running `mklink /J "C:\MSYS\usr\home\[user]" "C:\Users\[user]"` (Which will also make it so `~` in paths will lead you to the Windows home folder, and then I just have `PATH` being set in `.bash_profile` which I have to manually sync with the Window's PATH env variable every once and a while. I'm sure there's probably a way to automatically get bash to inherit PATH from Windows but I'm too lazy to figure it out.

**Comment by EJammy** [comment]
For msys2, the solution here did not work well for me. MSYS2 provides a cmd script for launching.

This is what I do:
```
shell:
  program: C:/msys64/msys2_shell.cmd
  args:
    - -defterm
    - -here
    - -use-full-path
    - -no-start
    - -mingw64
```
see: https://www.msys2.org/docs/terminals/

**Comment by DanOpcode** [comment]
With the TOML config format for Alacritty I made it work with this config:

```toml
[terminal]
shell = { program = "C:\\Program Files\\Git\\bin\\bash.exe" }
```
