### ISSUE TITLE
Error when launch alacritty

### ISSUE THREAD

**Issue by Cyberdr3am** [alacritty/alacritty#3302]
System OS: Linux
Version: `alacritty --version` 0.4.1
Linux/BSD: Graphics:
  Device-1: Intel 82G33/G31 Express Integrated Graphics driver: i915 v: kernel 
  Display: x11 server: X.Org 1.20.7 driver: intel resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa DRI Intel G33 v: 1.4 Mesa 19.3.2

Logs Crashes:  There was an error initializing the shaders: ( spam therminal when try to open it )

When i try to open alacritty from other terminal i have got the error "  There was an error initializing the shaders: " again and again. I must stop the command because this error never stop.

I look other issues but don't found how to solve this problem

**Comment by kchibisov** [comment]
The infinite error thing was fixed a while ago on master.

It seems like your GPU doesn't have OpenGL 3.3(the minimum version we require) support so it's failing to start. 

issue about adding support for older devices is #128
