### ISSUE TITLE
Block selection containing end of line behaving incorrectly

### ISSUE THREAD

**Issue by chrisduerr** [alacritty/alacritty#3304]
If a block selection includes the end of a line, not only the block selection but also the newline characters from the end of the line are inserted.

Additionally, when the selection goes from the start of the line to the end of the line and a line wraps around, the line is not copied correctly but instead broken across multiple lines.

It should be fairly simple to fix this, by only appending the block selection's newline when it does not end on the last column.

**Comment by kabindrashrsth** [comment]
Could you explain the steps to replicate this problem? When I tried to copy a block of text, the text copied correctly and was not broken across multiple lines.

**Comment by chrisduerr** [comment]
If you start a block selection in the first column and end it in the last column, it will add the newline twice.

Following steps should show the issue:
 - `ls -lah`
 - block select entire output, from first to last column (inclusive)
 - paste into editor
 - notice there are extra newlines between each row

**Comment by prometheanfire** [comment]
I've had this issue when copying ssh pubkeys around, semi-related is #3145 and #2233
