### ISSUE TITLE
can't find config file on windows!

### ISSUE THREAD

**Issue by catalin560** [alacritty/alacritty#3309]
`%APPDATA%\alacritty\alacritty.yml` is not a valid path...

**Comment by kchibisov** [comment]
You should put it there yourself. We're not creating a config and other random permanent files for you, it's expected.

**Comment by catalin560** [comment]
where can I find the docs for configuring the terminal?

**Comment by kchibisov** [comment]
everything is mentioned there https://github.com/alacritty/alacritty#configuration

**Comment by catalin560** [comment]
is there a way to integrate it withing vscode and not open a separate instance?

**Comment by kchibisov** [comment]
likely no, vscode uses its own terminal IIRC. So you can't integrate anything into it, I guess. But I'm not an expert here. However if you can open any terminal in vscode or let's say Firefox(random browser), you can likely open alacritty too.

Just to make it clear, we're not cmd.exe,pwsh.exe, etc. We're actually a terminal emulator, not a shell, like cmd.exe and friends.

**Comment by catalin560** [comment]
shame... cmder seems to have a working solution for this https://github.com/cmderdev/cmder/wiki/Seamless-VS-Code-Integration

also I still can't get alacritty to see my config... what is `%APPDATA%` supposed to stand for?
chocolatey installed it in c/tools/alacritty so I assume that the config should be in c/ProgramData/alacritty ??? if so it doesn't work for me

**Comment by kchibisov** [comment]
IIRC you can run alacritty in ConEmu, so in theory if cmder is a conemu fork, you can run alacritty in it, but I'm not an expert here.

The location should be `C:\Users\YOUR_USERNAME\AppData\Roaming\alacritty\alacritty.yml` IIRC.

**Comment by chrisduerr** [comment]
%APPDATA% is how Windows specifies environment variables. So it's not necessarily the location @kchibisov pointed out, though that is most likely. You should check the %APPDATA% environment yourself.

**Comment by desmap** [comment]
> The location should be C:\Users\YOUR_USERNAME\AppData\Roaming\alacritty\alacritty.yml IIRC.

This should be in the README, currently there's a wrong path for Windows user. No deal-breaker but this wastes your users' time.

**Comment by kchibisov** [comment]
>This should be in the README, currently there's a wrong path for Windows user. No deal-breaker but this wastes your users' time.

The path in readme isn't wrong, it's correct, since it's using environment variable, and should auto expand. The path in readme is exactly the same we're using internally, when we're searching for config.

**Comment by johnnovak** [comment]
> 
> 
> > This should be in the README, currently there's a wrong path for Windows user. No deal-breaker but this wastes your users' time.
> 
> The path in readme isn't wrong, it's correct, since it's using environment variable, and should auto expand. The path in readme is exactly the same we're using internally, when we're searching for config.

While technically it is correct, it can be misleading (I was mislead by it initially too). It would be helpful to new users to mention it to parenthesis something like this: "(%APPDATA% usually expands to C:\Users\<your_user_name>\AppData\Roaming)"

**Comment by johnnovak** [comment]
Another note, the Windows installer doesn't create the default `C:\Users\<your_user_name>\AppData\Roaming\alacritty\alacritty.yml` config file. The installer could easily create this directory and copy the default all commented-out config into it, but it doesn't... which is quite user friendly, you need to figure this out yourself because the README doesn't say anything about the provided default config template.

**Comment by macsunmood** [comment]
Hi.
why not make the support for having config file in the same directory as the main executable, for better portability?

**Comment by kchibisov** [comment]
Executable is always installed in the place where you need extra privileges to operate. If you want a different place for a config file, you can pass `--config-file` args on the command like which you can set on windows a an application settings.

**Comment by bhaskar10h** [comment]
> is there a way to integrate it within vscode and not open a separate instance?

yes, you can configure by opening vscode directly
or
use this:

1. cd %APPDATA%/roaming/alacritty 

2. code .

the file will open on vscode

**Comment by CaioSantos** [comment]
> > > This should be in the README, currently there's a wrong path for Windows user. No deal-breaker but this wastes your users' time.
> > 
> > 
> > The path in readme isn't wrong, it's correct, since it's using environment variable, and should auto expand. The path in readme is exactly the same we're using internally, when we're searching for config.
> 
> While technically it is correct, it can be misleading (I was mislead by it initially too). It would be helpful to new users to mention it to parenthesis something like this: `(%APPDATA% usually expands to C:\Users\<your_user_name>\AppData\Roaming)`
> 
> More often than not, there is a big difference between "technically correct" (but terse), and useful/helpful documentation 😉

yup, you're absolutely right! Just fell victim to that one newbie trap and wasted almost a whole 10 minutes trying to figure that out. A bit of a rough welcome and it could've been prevented by simply not hiding required knowledge from newcomers in the implicitness of the statement. Thanks for clarifying things @kchibisov and @johnnovak !

**Comment by mayannaoliveira** [comment]
Hello everyone, 
Please, I had the same doubt but using Windows 10 (PowerShell) and Alacritty-v0.15.1, I didn't find any Alacritty file in `%APPDATA%\alacritty\alacritty.toml` or `%APPDATA%\alacritty\alacritty.yml` so I did:
1. Access the path :open_file_folder: ` C:\Users\machine\AppData\Roaming\`.
2. Create a folder called  :file_folder: `alacritty` so will be like :open_file_folder:  `C:\Users\machine\AppData\Roaming\alacritty`.
3. Create a :spiral_notepad: `alacritty.yml` in :open_file_folder: ` C:\Users\machine\AppData\Roaming\alacritty`.
4. Insert the follow code in :spiral_notepad: `alacritty.yml`.

```yml
# Alacritty 
# Font family
font:
  normal:
    family: "JetBrainsMono Nerd Font"
    style: Regular

  bold:
    family: "JetBrainsMono Nerd Font"
    style: Bold

  italic:
    family: "JetBrainsMono Nerd Font"
    style: Italic

  bold_italic:
    family: "JetBrainsMono Nerd Font"
    style: Bold Italic

  size: 12.0

# Offset
  offset:
    x: 0
    y: 0

# Glyph offset
  glyph_offset:
    x: 0
    y: 0
```
I have [Oh My Posh](https://ohmyposh.dev/) installed so to install a [Nerd Font](https://www.nerdfonts.com/) I just insert a terminal command `oh-my-posh font install`. 
Alacritty is an amazing terminal with a portable version.
Thank you :smile: :heart_decoration:

**Comment by 573** [comment]
> # Alacritty 
> # Font family
> font:
>   normal:
>     family: "JetBrainsMono Nerd Font"
>     style: Regular
> 
>   bold:
>     family: "JetBrainsMono Nerd Font"
>     style: Bold
> 
>   italic:
>     family: "JetBrainsMono Nerd Font"
>     style: Italic
> 
>   bold_italic:
>     family: "JetBrainsMono Nerd Font"
>     style: Bold Italic
> 
>   size: 12.0
> 
> # Offset
>   offset:
>     x: 0
>     y: 0
> 
> # Glyph offset
>   glyph_offset:
>     x: 0
>     y: 0

<details><summary>TOML users</summary>
<p>

```
# Alacritty 
# Font family
# see https://sourcegraph.com/github.com/Athena-OS/athena/-/blob/packages/archive/arch/athena-tweak-tool/athena-tweak-tool/data/arco/alacritty/alacritty.toml?L28-31
[font.normal]
family = "UbuntuMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "UbuntuMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "UbuntuMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "UbuntuMono Nerd Font Mono"
style = "Bold Italic"

[font]
size = 12.0

# Offset
[font.offset]
x = 0
y = 0

# Glyph offset
[font.glyph_offset]
x = 0
y = 0
```

</p>
</details>
