### ISSUE TITLE
Multi-Monitor: Ignores focus, always opens on same screen.

### ISSUE THREAD

**Issue by gpp-games** [alacritty/alacritty#3311]
Every program I run via a shortcut, opens on the screen where my pointer is.
I want Alacritty to behave the same, but it doesn't. It always opens on the same screen/monitor.

OS: Linux ( 5.5.2-arch1-1 ) 
Version: 0.4.1 ( Alacritty )
Linux/BSD: X11, XFCE

**Comment by chrisduerr** [comment]
Can you reproduce this with an empty Alacritty configuration?

**Comment by nixpulvis** [comment]
I installed XFCE to play around with this a little bit. The default program launcher available with <kbd>Alt + F2</kbd> works in either of my two monitors, and Alacritty properly opens on the screen where my cursor was (and where the dialog was too).

Maybe there's a problem with your shortcut. Could you provide a bit more information about your setutp?

**Comment by mairacanal** [comment]
I'm having this same problem with GNOME.

OS: Pop!_OS 20.04 LTS
Version: 0.8.0 (Alacritty)
Linux/BSD: X11, GNOME 3.36.8
