### ISSUE TITLE
A different font for Non-ASCII text

### ISSUE THREAD

**Issue by xiaolongGitHub1498** [alacritty/alacritty#3318]
Hi, can you add a font option for Non-ASCII text

when i use a beautiful font like Input Mono, but it can't show nerdTree icon

in iterm2, it has this option

![image](https://user-images.githubusercontent.com/26108004/74157855-fa168d80-4c53-11ea-98bf-f1860398cc1d.png)

**Comment by chrisduerr** [comment]
This should be covered by the #957 issue, which proposes to make a lot of font options directly configurable in Alacritty. This includes defining character ranges for these glyphs.

**Comment by glepnir** [comment]
same question here.  i saw the #957   , i want to know  this question solved now?

**Comment by xiaolongGitHub1498** [comment]
@glepnir nerdfont patch font

**Comment by jrock2004** [comment]
@xiaolongGitHub1498 did you ever find a solution for this? Seems like the only way to fix this is to use a font that supports the characters or was there a solution put in place?

**Comment by BTBMan** [comment]
@jrock2004 Use nerdfont to patch what fonts you need.
