### ISSUE TITLE
font ignored on laptop screen

### ISSUE THREAD

**Issue by anntnzrb** [alacritty/alacritty#3319]
### System

OS: Linux (Void)
Version: `alacritty 0.4.1`
Linux: `X11` ; `xcompmgr` as compositor & `i3` as WM

## Issue

my setup is a laptop and a monitor i use as my primary display (my laptop screen as extended secondary screen), i don't have any issues with my main monitor, the thing is that whenever i drag an alacritty window from the this external monitor to my laptop's screen, the font becomes huge.

at the beginning i thought this was cool as my laptop screen is 15' and (somehow thought) this was cleverly adjusted to compensate the dimensions difference... (allowed me to see better as the font was bigger on this smaller display). yesterday for the first time (with alacritty) i used my laptop without the monitor... and there was just no way to resize the font.

short words: the font is respected only when my main monitor is hooked, i tried deleting my `.Xresources` and `.alacritty.yml` config files without luck.

i'm attaching both configuration files mentioned above and also my `$ xrandr` output:

[alacritty.yml](https://hastebin.com/yemicuzuvu.shell)
[.Xresources](https://hastebin.com/uzelawoxaq.makefile)
[xrandr](https://hastebin.com/kawucedune.css)

**Comment by kchibisov** [comment]
This isn't a bitmap font, right? I'd assume `Control + +` and `Control + -` (font change won't working)? Also make sure you're actually using the right config with `alacritty -v`? I don't see anything wrong in ranr output tbh. Also, if your font is a bitmap one, there's a change you can't resize it.

**Comment by anntnzrb** [comment]
> This isn't a bitmap font, right?

i wouldn't be able to tell, i'm attaching the [**output**](https://hastebin.com/hamirufiji.makefile) of `$ fc-list | grep Overpass`

> I'd assume `Control + +` and `Control + -` (font change won't working)?

my keybindings are working fine, `+`, `-`, and `0` are doing their job but they're still bigger (still when i drag back to monitor gets "fixed")
i'm also attaching two images...
![pic-selected-200210-2128-44](https://user-images.githubusercontent.com/51257127/74207225-b66c5580-4c4c-11ea-9388-8648aa1aeec5.png)
![pic-selected-200210-2129-18](https://user-images.githubusercontent.com/51257127/74207226-b8361900-4c4c-11ea-9b08-10a9c153db0a.png)

*first picture is my external monitor and second one is on my laptop's screen (didn't resize or anything, literally just dragged the window)*

> Also make sure you're actually using the right config with `alacritty -v`?

`$ alacritty -v`[**output**](https://hastebin.com/vigoyuqava.cs)

**Comment by kchibisov** [comment]
Could you try to launch alacritty with `WINIT_HIDPI_FACTOR=1 alacritty` ?

**Comment by anntnzrb** [comment]
> Could you try to launch alacritty with `WINIT_HIDPI_FACTOR=1 alacritty` ?

just tried, works as it should be, no more resizing.

i also edited the post above in case you missed it, anyhow what you just posted seems to have worked, is it possible to set this as an option in the `.yml` file?

**Comment by kchibisov** [comment]
if you don't like automatic DPI scaling like alacritty doing by default, the result is that your font should have identical size in millimeters across your monitors, however some monitors could report odd values.

There are 2 options to avoid automatic DPI scaling based on randr metrics:
	- Add this variable to a env section in `alacritty.yml`, so it should be `WINIT_HIDPI_FACTOR: "1"`
	- Set `Xft.dpi: 96` in `.Xresources`.

I've noticed that you have Xft.dpi in Xresources, but I feel like we're failing to pick up it, anyway, could you try to set it like `Xft.dpi` instead of `Xft*dpi`.


Note: most X11 doesn't do DPI scaling, so it's hard to use them with mixed DPI setups.

**Comment by anntnzrb** [comment]
> There are 2 options to avoid automatic DPI scaling based on randr metrics:
> - Add this variable to a env section in `alacritty.yml`, so it should be `WINIT_HIDPI_FACTOR: "1"` in `env` section.

that did the trick. appreciate the support 🤝
