### ISSUE TITLE
Alacritty opening shell in external window?

### ISSUE THREAD

**Issue by t-a-y-NY** [alacritty/alacritty#3321]
Alacritty is opening shells externally, e.g., opening Cygwin or Clink in their own native windows, not inside of Alacritty.

This is the relevant section of the .yml config file:

`# Shell`
`#`
`# You can set `shell.program` to the path of your favorite shell, e.g. `/bin/fish`.`
`# Entries in `shell.args` are passed unmodified as arguments to the shell.`
`#`
`# Default:`
`#   - (macOS) /bin/bash --login`
`#   - (Linux) user login shell`
`#   - (Windows) powershell`
`shell:`
`  program: C:\{location}\clink\0.4.9\clink.bat`
`#  args:`
`# - --login`

### System

OS: Windows 10

It's opening clink.bat as though I were clicking shortcut for clink.bat outside of Alacritty.

**Comment by chrisduerr** [comment]
As far as I know, when executing bats on Windows a shell is spawned by default. If you do not wish to do that, you'll have to provide a shell yourself.

I'm not sure what `clink.bat` does, but does it bootstrap an interactive shell? You might be able to do something like using `cmd` as program and then `["\c", "C:\{location}\clink\0.4.9\clink.bat"]` as parameters.

**Comment by t-a-y-NY** [comment]
It launches its own shell. Also, this doesn't only happen with `clink.bat`, it also happens with Cygwin, which is launched with `mintty.exe`. When I set the location for Cygwin as the shell for Alacritty, and open Alacritty, Alacritty launches and then immediately opens up a Cygwin window, rather than running Cygwin inside of Alacritty as a shell.

Also, I'm not sure I can run clink as a parameter for cmd.

**Comment by chrisduerr** [comment]
Alacritty has no control over how the application is launched. It is up to the application to decide if it should launch a new window or not. So you'll have to tell the program that will execute the bat file that it should not do so in a new window, but in the current command line.

**Comment by t-a-y-NY** [comment]
Okay I understand now. 

When I ran `bash.exe` instead of `mintty.exe`, Alacritty ran it internally as desired. I guess this is just a problem with clink. I have no clue how to run clink inside of a terminal without binding it to `cmd.exe`.

**Comment by badrelmers** [comment]
clink work fine , this is how i use it , i have a batch file in the path called cmdd.bat, it contain
```batch
@echo off
ver | findstr /i "5\.1\."  > nul && (set "_os=xp")
if "%_os%" == "xp" (
    cmd /k %~dp0_batchrc\_batchrc_winXP.bat
) else (
    cmd /k %~dp0_batchrc\_batchrc_win7.bat
)
```
in _batchrc_win7.bat i have
```batch
call "%~dp0clink_win7\clink\clink.bat" inject --profile "%~dp0clink_win7\clink_profile"
```

then in alacritty.yml i do
```yaml
shell:
 program: cmd
 args:
   - /C cmdd
```

<img width="865" height="557" alt="Image" src="https://github.com/user-attachments/assets/96a6d7a5-c797-4a02-bd80-ff714b75afde" />

maybe you can run it directly using _batchrc_win7.bat, but this is how i configure it several years ago
