### ISSUE TITLE
macOS: VIM ctrl-^ stopped working

### ISSUE THREAD

**Issue by DivineGod** [alacritty/alacritty#3323]
I'm on master and noticed `CTRL-^` had stopped switching buffers.

I tried commit `6832b86` and noticed it worked fine. Commit `db9e8d4` is not working.

Steps to repro:

1. open 2 or more files in vim
2. make sure both files are loaded
3. Try to switch between buffers with [C-^]

Expected result is that the buffer changes, however, since `db9e8d4` nothing happens.

This happens regardless of using tmux or not.

Pressing the key-combination in the prompt just prints `6`

### System

OS: macOS
Version: master since `db9e8d4`

**Comment by kchibisov** [comment]
Could you provide `alacritty --print-events` log?

**Comment by DivineGod** [comment]
[events.log master](https://github.com/alacritty/alacritty/files/4183876/events.log)
[events.log 6832b86](https://github.com/alacritty/alacritty/files/4183882/events_6832b86.log)

**Comment by chrisduerr** [comment]
@DivineGod What happens when you press just <kbd>ctrl</kbd>+<kbd>6</kbd> without shift? I'd assume that exhibits the exact same problem sending `6` in the terminal again?

**Comment by chrisduerr** [comment]
Reported upstream in https://github.com/rust-windowing/winit/issues/1453.

**Comment by DivineGod** [comment]
> @DivineGod What happens when you press just ctrl+6 without shift? I'd assume that exhibits the exact same problem sending `6` in the terminal again?

Yes, it prints `6` in the terminal :)

**Comment by rafi** [comment]
For the meantime, you could use `:h CTRL-6` and set Alacritty:
```yaml
key_bindings:
- { key: Key6, mods: Control, chars: "\x1e" }
```

**Comment by DivineGod** [comment]
fixed by: https://github.com/alacritty/alacritty/pull/3445

**Comment by CodingPapi** [comment]
@DivineGod Reporduced again on Macos Big sur 11.4 with Alacritty 0.10.1
