### ISSUE TITLE
Powershell starts up with extra stuff prepended to the path

### ISSUE THREAD

**Issue by raphtlw** [alacritty/alacritty#3325]
### System

OS: Windows
Version: 0.4.1
Windows: ConPTY

### Logs

Font/Terminal size: Device pixel ratio: 1.5, Width: 1122, Height: 642

### What happens
When I open the terminal in a directory, it has this word prepended to the path: `Microsoft.PowerShell.Core\FileSystem::\\?`

**Comment by chrisduerr** [comment]
Duplicate of https://github.com/alacritty/alacritty/issues/3198.
