### ISSUE TITLE
callback font not working on macos

### ISSUE THREAD

**Issue by xiaolongGitHub1498** [alacritty/alacritty#3326]
Hi,
Here is my .config/fontconfig/fonts.conf

![image](https://user-images.githubusercontent.com/26108004/74244316-2d245400-4d1c-11ea-8115-b7b73c379bd8.png)
Config works!
![image](https://user-images.githubusercontent.com/26108004/74244903-1f230300-4d1d-11ea-8364-d52b84f3fced.png)

Here is my alacritty.yml

![image](https://user-images.githubusercontent.com/26108004/74244458-66f55a80-4d1c-11ea-8250-e44d32a34bba.png)

This is what i expect is（show icon with FuraCode Nerd Font）

![image](https://user-images.githubusercontent.com/26108004/74245138-8345c700-4d1d-11ea-94c9-631ef96aa1fa.png)

But it's not working

![image](https://user-images.githubusercontent.com/26108004/74245212-9ce70e80-4d1d-11ea-9f7c-7f179ae97cde.png)

**Comment by chrisduerr** [comment]
You're talking about fontconfig, but also macOS, however fontconfig is a Linux/BSD thing. Could you clarify? On macOS only the native core backend is supported.

**Comment by xiaolongGitHub1498** [comment]
@chrisduerr I see this #2812 It works, 
but if not, how can i use callback font on macos

**Comment by chrisduerr** [comment]
Fallback on macOS should work automatically using the system fonts if you have them installed globally.

If you're having trouble executing Alacritty directly, could you try starting Alacritty from iTerm to see if that helps with the problem?

**Comment by xiaolongGitHub1498** [comment]
@chrisduerr it also no working,
 I'd like to ask:
I want `Input Mono` to my main font, and `FuraCode Nerd Font` to show icon,
How can I set on MacOS

**Comment by chrisduerr** [comment]
> I want Input Mono to my main font, and FuraCode Nerd Font to show icon,
How can I set on MacOS

You can't, Alacritty relies solely on what core text provides. So if you want to tweak anything you'd have to look into core text.

To set the exact fallback order, there's the font config RFC: #957.
