### ISSUE TITLE
Bug: Printing Characters on Screen

### ISSUE THREAD

**Issue by rudolfschmidt** [alacritty/alacritty#3332]
### System
```
Linux rs.com 5.5.2-arch1-1 #1 SMP PREEMPT Tue, 04 Feb 2020 18:56:18 +0000 x86_64 GNU/Linux
alacritty 0.4.1
#1 SMP PREEMPT Tue, 04 Feb 2020 18:56:18 +0000
```

When I switch my windows with alt+left or alt+right he prints characters on the screen.

**Comment by chrisduerr** [comment]
This has been fixed on the latest master. See #3204.

**Comment by rudolfschmidt** [comment]
thanks for the reply, hope the release will come soon because in arch it's still the package with the bug.
