### ISSUE TITLE
Very Slow Window Rearranging After Closing Alacritty

### ISSUE THREAD

**Issue by yanzhang0219** [alacritty/alacritty#3333]
I use [yabai](https://github.com/koekeishiya/yabai), a tiling window manager on macOS. I opened a couple of windows of Alacritty and when I closed the one by one, sometimes rearranging took like 3 seconds or more. 

Please take a look at this issue https://github.com/koekeishiya/yabai/issues/368

Thank you very much. 

### System

OS: macOS 10.15.3
Version: alacritty 0.4.1 (4d9253b)

**Comment by chrisduerr** [comment]
I use yabai every day at work and have never run into this issue before. Is this with an empty configuration file too?

**Comment by yanzhang0219** [comment]
@chrisduerr Yes, with an empty configuration. Any ideas or suggestions? Thanks a lot.

**Comment by kchibisov** [comment]
Are you using integrated graphics?

**Comment by yanzhang0219** [comment]
@kchibisov Hi, my laptop is MacBook pro 15'' retina late 2013 which has NVIDIA GeForce GT 750M 2 GB graphics along with a integrated graphics Intel Iris Pro 1536 MB, and also my laptop drives two external monitors, one is 24'' (1920 x 1200) and the other is 27'' (3840 x 2160). Thanks.

**Comment by chrisduerr** [comment]
@yanzhang0219 Could you try the latest master? And which yabai version are you running?

I'm personally running yabai 2.2.2 on macOS catalina without any problems.

**Comment by yanzhang0219** [comment]
@chrisduerr I am running 2.2.3 which is the latest version. I am not sure whether it is due to the obsolete hardware of my laptop which is late 2013. Just now, in yabai, I enabled the window border and then when I closed an Alacritty window, that window was destroyed, but other windows were not rearranged and the border of that destroyed window was still there for around 3-5 seconds.

**Comment by chrisduerr** [comment]
Could you open Alacritty from CLI with the `-vvv --print-events` logs and post everything that appears after the window was closed? Or immediately when it is closed.

**Comment by yanzhang0219** [comment]
@chrisduerr Okay. What I did is: I opened Alacritty by `alacritty -vvv --print-events > log.txt`, and then when Alacritty was open, I closed it by CMD-w. I attached the output below. Thank you.

[log.txt](https://github.com/alacritty/alacritty/files/4200470/log.txt)

**Comment by chrisduerr** [comment]
@yanzhang0219 Could you provide the log with the following patch applied: https://github.com/alacritty/alacritty/pull/3337. Unfortunately it's not very useful if just the minutes are printed.

**Comment by yanzhang0219** [comment]
@chrisduerr Sure. But a stupid question.. How can I apply that patch, just update my Alacritty via `brew upgrade` ?

**Comment by chrisduerr** [comment]
You'll have to recompile from source, following the instructions in the INSTALL.md.

**Comment by yanzhang0219** [comment]
@chrisduerr Okay I will try to do that. Thank you.

**Comment by yanzhang0219** [comment]
@chrisduerr Hello. I deleted Alacritty installed via brew, and then I clone the source code and manually installed Alacritty by running `make app`. 
Then I opened one Alacritty window, and in it, I run `alacritty -vvv --print-events > log.txt` as you suggested. I attached the output log.txt below. 

[log.txt](https://github.com/alacritty/alacritty/files/4206498/log.txt)

Is it helpful? Thanks a lot!

**Comment by chrisduerr** [comment]
It is, thanks!

Looking at your output, you've pressed the <kbd>super</kbd>+<kbd>w</kbd> key at `11:37:36.458720000` and then the last statement executed inside Alacritty happened at `11:37:36.460355000`.

So looking at this output, it seems like shutdown took exactly 1.635ms, which seems very quick.

So there are two different things that could be happening, either the events are massively delayed, or macOS OpenGL drivers are doing something strange. I strongly suspect the latter, but could you check if the `Goodbye` message is printed to stdout as soon as you tell Alacritty to shut down?

Also could you try a few different methods to shut down? Like Ctrl+D or pressing the close button in the window decorations.

And just to test every available options, changing the [window decorations](https://github.com/alacritty/alacritty/blob/cbec5e415b721e5d5a8359ebed247ac39eb99721/alacritty.yml#L43-L52) option might be worth testing. I personally have mine set to `none`, since I use `yabai` to close things anyways, so maybe that's why it works for me?

**Comment by yanzhang0219** [comment]
@chrisduerr Thank you!!
I opened Alacritty. Then in this window (window1), I use `alacritty` command to open a new instance (window2). In window1, the cursor is flashing and hanging there. Then after I use `command-w` to close window2, nothing output in window1 (no such `Goodbye` message) and just the prompt come back. 

Then I tried the same procedure but quit window2 by `Ctrl-d` or clicking its closing button, similarly nothing output in window1. 

HOWEVER, a good news here!!! After installing Alacritty by building manually instead of using homebrew, it seems that this window rearranging issue and that resizing issue (#3328) disappear, or at least getting much better. 

Just now, I rebooted my laptop, and then tried to reproduce these two issues. I opened many Alacritty windows and closed them one by one, the window rearranging was faster and acceptable. When I resized one window, it seemed no sluggish issue there. So magic! I will continue keeping my eye on the performance of my Alacritty and leave the feedback here. 

I have no ideas about why these two issues are suddenly relieved automatically. Is the homebrew version far behind? What's your opinion? 

What's more, I am new to yabai and still learning how to configure and use it. Could you please share your yabai config (yabairc, skhdrc) and Alacritty config on macOS? I want to use them as great references (my email: yanzhang0219@gmail.com). Really appreciate it!!

**Comment by chrisduerr** [comment]
> I opened Alacritty. Then in this window (window1), I use alacritty command to open a new instance (window2). In window1, the cursor is flashing and hanging there. Then after I use command-w to close window2, nothing output in window1 (no such Goodbye message) and just the prompt come back.

Note that you'd have to run Alacritty with the options `--print-events -vvv` to get the `Goodbye` message. Usually we don't log anything.

**Comment by chrisduerr** [comment]
Also, these are my configs @yanzhang0219:

<details>
<summary>Alacritty</summary>

```
window:
  decorations: none
  dynamic_padding: true
  padding:
    x: 3
    y: 3

shell:
  program: zsh
  args:
    - --login

font:
  size: 13

colors:
  primary:
    background: '0x1b1b1b'
    foreground: '0x9e9e9e'

  normal:
    black:   '0x1b1b1b'
    red:     '0xac4142'
    green:   '0x90a959'
    yellow:  '0xf4bf75'
    blue:    '0x6a9fb5'
    magenta: '0xaa759f'
    cyan:    '0x75b5aa'
    white:   '0x616161'

  bright:
    black:   '0x262626'
    red:     '0x752a2a'
    green:   '0x5d742a'
    yellow:  '0x754e2a'
    blue:    '0x2a4e74'
    magenta: '0x703664'
    cyan:    '0x297366'
    white:   '0x9e9e9e'

cursor:
  style: Underline

alt_send_esc: false

key_bindings:
  - { key: W, mods: Command, action: None }
  - { key: Q, mods: Command, action: Quit }
```

</details>

<details>
<summary>SKHD</summary>

```
# open terminal
cmd - return : open -na /Applications/Alacritty.app

# close focused window
# TODO
# cmd - q : yabai -m window --close

# focus window
cmd - h : yabai -m window --focus west || yabai -m display --focus next
cmd - j : yabai -m window --focus south
cmd - k : yabai -m window --focus north
cmd - l : yabai -m window --focus east || yabai -m display --focus prev

# move window
shift + cmd - h : yabai -m window --swap west || yabai -m window --display next
shift + cmd - j : yabai -m window --swap south
shift + cmd - k : yabai -m window --swap north
shift + cmd - l : yabai -m window --swap east || yabai -m window --display prev

# switch workspaces
cmd - 1 : yabai -m space --focus $((2 + ($(yabai -m query --spaces | jq '.[] | select(.focused == 1) | .display') - 1) * 5))
cmd - 2 : yabai -m space --focus $((3 + ($(yabai -m query --spaces | jq '.[] | select(.focused == 1) | .display') - 1) * 5))
cmd - 3 : yabai -m space --focus $((4 + ($(yabai -m query --spaces | jq '.[] | select(.focused == 1) | .display') - 1) * 5))
cmd - 4 : yabai -m space --focus $((5 + ($(yabai -m query --spaces | jq '.[] | select(.focused == 1) | .display') - 1) * 5))
cmd - 5 : yabai -m space --focus $((6 + ($(yabai -m query --spaces | jq '.[] | select(.focused == 1) | .display') - 1) * 5))

# send window to desktop
cmd + shift - 1 : yabai -m window --space $((2 + ($(yabai -m query --spaces | jq '.[] | select(.focused == 1) | .display') - 1) * 5))
cmd + shift - 2 : yabai -m window --space $((3 + ($(yabai -m query --spaces | jq '.[] | select(.focused == 1) | .display') - 1) * 5))
cmd + shift - 3 : yabai -m window --space $((4 + ($(yabai -m query --spaces | jq '.[] | select(.focused == 1) | .display') - 1) * 5))
cmd + shift - 4 : yabai -m window --space $((5 + ($(yabai -m query --spaces | jq '.[] | select(.focused == 1) | .display') - 1) * 5))
cmd + shift - 5 : yabai -m window --space $((6 + ($(yabai -m query --spaces | jq '.[] | select(.focused == 1) | .display') - 1) * 5))

# toggle window fullscreen
cmd + ctrl - f : Yabai -m window --toggle native-fullscreen

# float / unfloat window and center on screen
cmd + shift - space : yabai -m window --toggle float

# open launchpad
cmd - space : open -na /System/Applications/Launchpad.app &
```

</details>

<details>
<summary>Yabai</summary>

```
# Tile on all spaces
yabai -m config layout bsp

# Gaps
yabai -m config top_padding 10
yabai -m config right_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config window_gap 10

# Render floating windows on top
yabai -m config window_topmost on

# Move mouse with focus
yabai -m config mouse_follows_focus on

# Modifier for mouse controls
yabai -m config mouse_modifier cmd
```

</details>

**Comment by yanzhang0219** [comment]
> Note that you'd have to run Alacritty with the options `--print-events -vvv` to get the `Goodbye` message. Usually we don't log anything.

Okay. I got `Goodbye` message. Once I press `command-x` to close a window of Alacritty, the output is below: 

![Screen Shot 2020-02-14 at 3 26 53 PM](https://user-images.githubusercontent.com/11582667/74576151-9388bc80-4f3e-11ea-80f2-5a2a76ced2b1.png)

> Is it good enough to consider this issue resolved then? On my system with the latest Alacritty master I don't feel like there's any issues at least.

Yes, I think we can temporarily consider this issue is resolved. But I will continue watching and updating if it gets worse in the future. 

Thank you @chrisduerr so much for your help!!!!
