### ISSUE TITLE
White title bar instead of following gnome theme

### ISSUE THREAD

**Issue by thewhiteh4t** [alacritty/alacritty#3335]
### System

OS: Ubuntu 18.04
Version: 0.4.1
Linux/BSD: Gnome 3.28.4

### Expected
Alacritty uses gnome theme like other terminal

### Current
White title bar

![Screenshot from 2020-02-13 15-18-51](https://user-images.githubusercontent.com/36354846/74423005-8f449c80-4e75-11ea-81b8-445002bb637d.png)

**Comment by kchibisov** [comment]
Gnome uses client-side decorations on Wayland, it means that every app should do it on its own. Alacritty isn't a GTK app, so there's no way for us to draw the same thing as the rest of your apps, without manually parsing GTK themes and draw them ourselves, which is no an option. If you don't like GNOME decision to use client-side-decorations over server-side one(they don't bother to support it), complain to them and not to us.

**Comment by thewhiteh4t** [comment]
@kchibisov okay I see but I am not able to understand this : 
I am using ubuntu and I installed `Vanilla Gnome` in it, after doing this I can see multiple options for DE in logout screen : `ubuntu / ubuntu wayland / gnome` 
now theme works if I choose ubuntu, I have not tried ubuntu wayland yet and DE in ubuntu is also gnome so what is the difference between ubuntu DE which comes with gnome and vanilla gnome?

**Comment by thewhiteh4t** [comment]
both are using same version of gnome 3.28.4, what am I missing in vanilla gnome?

**Comment by kchibisov** [comment]
I can’t say anything about ubuntu + GNOME combination. But if you type “env” in terminal and notice WAYLAND_DISPLAY variable, you’re on Wayland.

Also, this title bar is only on our Wayland backend and drawn by our wayland backend.

**Comment by thewhiteh4t** [comment]
@kchibisov thanks a lot! `vanilla gnome` uses wayland by default , I disabled it in `/etc/gdm3/custom.conf` and I got what I wanted
