### ISSUE TITLE
enable building without X11 for Wayland-only systems

### ISSUE THREAD

**Issue by trilean** [alacritty/alacritty#3340]
Hi,

I wanted to build Alacritty on a Gentoo box that doesn't have any X11 libs installed. This failes because some X libs are linked to.

I tried to brute-force my way around this by removing all X-related dependencies and code. Unfortunately I'm stuck at
https://github.com/alacritty/alacritty/blob/988a846c52f381bdd2d211d9dbb4b9bf0f9105e5/alacritty/src/main.rs#L169
because there's no waylandish version of this implemented.

Any help in getting this awesome terminal running on Wayland-only is very much appreciated :wink: 
Thanks!

**Comment by kchibisov** [comment]
you can take a look on upstream issue right there https://github.com/rust-windowing/winit/issues/774 .

**Comment by kchibisov** [comment]
Actually I feel like there's no need to disable something in winit. It seems like we can achieve just inside alacritty.

**Comment by kchibisov** [comment]
If someone is interested in testing the build it'll be nice to check #3436. Instructions are on the PR.

**Comment by nixpulvis** [comment]
Not directly related to this fix... But FWIW, I left a comment on https://github.com/rust-lang/cargo/issues/5015#issuecomment-597989961, and opened a thread [Rust Internals - Features and Workspaces, Request for Meta Issue](https://internals.rust-lang.org/t/features-and-workspaces-request-for-meta-issue/11964).
