### ISSUE TITLE
Opening window with program already running

### ISSUE THREAD

**Issue by n0ibe** [alacritty/alacritty#3345]
### System

OS: macOS 10.15.3
Version: alacritty 0.4.1 (4d9253b)

Is there a way to open alacritty with a program already running? I use [skhd](https://github.com/koekeishiya/skhd) to open alacritty, and I have the combination `cmd - return` mapped to `open -na /Applications/Alacritty.app`.

This just opens a new terminal instance with my `zsh` shell running, so I was wondering how I could create an skhd mapping to open a terminal with my file manager, [lf](https://github.com/gokcehan/lf), already running, instead of having to open a new terminal window first and then type `lf ~/Documents`.

**Comment by cole-h** [comment]
Try adding `-e lf` to the end of your invocation of Alacritty.

`open -na /Applications/Alacritty.app -e lf` should work, I think. (Disclaimer: I haven't used macOS)

**Comment by chrisduerr** [comment]
You'll probably have to execute the Alacritty executable directly to pass arguments to it. I don't know if that's possible with the `.app` package.

So it would be `/Applications/Alacritty.app/Contents/MacOS/alacritty` or something like that.

**Comment by n0ibe** [comment]
`/Applications/Alacritty.app/Contents/MacOS/alacritty --command lf` seems to work, but when I exit `ls` the terminal window closes too, which is a bit annoying but better then nothing I guess

**Comment by kchibisov** [comment]
>/Applications/Alacritty.app/Contents/MacOS/alacritty --command lf seems to work, but when I exit ls the terminal window closes too, which is a bit annoying but better then nothing I guess

This is how it works in most terminals. If don't want your window to be closed you should spawn it with shell. Something like
`alacritty --command bash -c "lf"`, if you want to keep output until explicit exit you should use `--hold` flag, but it just prevent salacritty from closing, when child process dies, but you won't be able to do anything with such window.
