### ISSUE TITLE
True color works unexpected in tmux after I update latest ncurses.

### ISSUE THREAD

**Issue by kevinhwang91** [alacritty/alacritty#3347]
## System

OS: Linux
Version: `alacritty --version` output
`alacritty 0.4.1`
Linux/BSD: X11, Gnome

After I upgrade `6.2-1` ncurses,  the problem shows below.
My version of tmux is `3.0_a-1`
![image](https://user-images.githubusercontent.com/17562139/74642637-50348500-51ae-11ea-88fb-5ebb85588164.png)

Using alacritty without tmux or using tmux inside gnome-terminal works fine.

**Comment by kchibisov** [comment]
Could you provide `echo $TERM` outside of tmux, `echo $TERM` inside of tmux, and your `.tmux.con`?

**Comment by kevinhwang91** [comment]
I have deleted `.tmux.conf` and tried again, the same result.

Without tmux `echo $TERM`,  output `xterm-256color`. Inside tmux output `screen`.

**Comment by kchibisov** [comment]
Try adding this to your `.tmux.conf`.

```
set -g default-terminal tmux-256color
set -ga terminal-overrides ",xterm-256color:RGB"
```

**Comment by kevinhwang91** [comment]
Wow, it works fine. This is the configuration that caused the issue.
```tmux
set -g default-terminal 'tmux-256color'
set -ga terminal-overrides ',*256col*:Tc'
```
Could you explain why doesn't work after updating ncurses?

**Comment by kevinhwang91** [comment]
If you are using ArchLinux, I think you can reproduce the issue.

**Comment by kchibisov** [comment]
https://github.com/tmux/tmux/wiki/FAQ#how-do-i-use-rgb-colour

**Comment by kchibisov** [comment]
As you can see, this is not an issue and even a recommended options to use `.tmux.conf`, since you're not using our official terminfo, I can't say match what you had in the past. ncurses provides terminfo, files, so I guess after update they changed a bit. IIRC Arch had old ncurses for a long time, so can't say more here.

**Comment by kevinhwang91** [comment]
solve by adding
```
env:
  TERM: xterm-256color
``` 
in alacritty.yml.

**Comment by kchibisov** [comment]
you said that your term was already `xterm-256color` how it solves anything?

**Comment by kchibisov** [comment]
I feel like you're setting `TERM` in your shell init scripts tbh. Like after udpate `alacritty` start using its terminfo, since our terminfo is in ncurses, however you were overriding it somewhere. Anyway, the most common way to get `truecolor` in tmux is by adding these 2 lines in `.tmux.conf`.

**Comment by kevinhwang91** [comment]
> I feel like you're setting `TERM` in your shell init scripts tbh. Like after udpate `alacritty` start using its terminfo, since our terminfo is in ncurses, however you were overriding it somewhere. Anyway, the most common way to get `truecolor` in tmux is by adding these 2 lines in `.tmux.conf`.

I think I have known the reason. I had said that the output is `xterm-256color` and add those 2 lines in `.tmux.conf` works fine. And then I found that I already downgrade the ncurses, so the message makes us misunderstanding.
The reason is that after updating the ncurse, with default config of alacritty, it will output `alacritty` instead of `xterm-256color` outside tmux.

**Comment by kevinhwang91** [comment]
I'm so sorry for my mistake to waste our time.
