### ISSUE TITLE
Alacritty doesn't start under xmonad sometimes

### ISSUE THREAD

**Issue by kurnevsky** [alacritty/alacritty#3348]
Sometimes alacritty doesn't start under xmonad windows manager - it just stuck and doesn't create window. I don't know how to reproduce it reliably - it just happens after some time during work. `xmonad --restart` restarts xmonad without restarting X11 and fixes it (old stuck processes don't get unstuck, only new launches work). `alacritty -vvv` and `alacritty --print-events` don't print anything in such cases.

### System

OS: Arch Linux
Version: alacritty 0.4.1
Linux/BSD: X11, Xmonad

**Comment by kchibisov** [comment]
if it doesn't print anything than it stuck very early on init stage, which is very strange. Could you attach to/run such process with `gdb`(`sudo gdb -p <ALACRITTY_PID>`) and figure out where it stucks(`bt full`, etc)? Also, you should compile it with debug symbols before doing it, our default release build has them, but distro packages strip debug symbols most of the time.

**Comment by kurnevsky** [comment]
ok, will do that next time it stops working. Also few more observations: when it stuck `alacritty --version` still works; `kitty` doesn't have this issue, so it's probably not opengl-related.

**Comment by kchibisov** [comment]
>kitty doesn't have this issue, so it's probably not opengl-related

Different apps use different APIs, but if it stuck without **any** output on `alacritty -vvv`, then it’s likely not OpenGL related.

**Comment by chrisduerr** [comment]
You can also try running with `RUST_LOG=trace alacritty -vvv`, which logs even more than our highest default log level.

**Comment by kurnevsky** [comment]
Managed to reproduce it with repeatedly restarting both alacritty and xmonad. `RUST_LOG=trace alacritty -vvv` doesn't print anything either...

**Comment by kurnevsky** [comment]
Here is backtrace from gdb:
[bt_full.txt](https://github.com/alacritty/alacritty/files/4215099/bt_full.txt)

**Comment by chrisduerr** [comment]
That looks like querying Xmonad for the wm name window property is failing.

Is there anything you actively do that you could see causing this kind of bug? Or does it just happen after an arbitrary amount of time?

If so, can you say how long it takes on average? Also is it relatively constant in time, or does it change a lot? And does it depend on when Xmonod is started, or when Alacritty is first launched?

**Comment by kurnevsky** [comment]
> Is there anything you actively do that you could see causing this kind of bug? Or does it just happen after an arbitrary amount of time?

I managed to reliable reproduce it - just restart xmonad when alacritty window is focused. I think this happened for me without xmonad restarts just after arbitrary amount of time but not really sure about it.

**Comment by chrisduerr** [comment]
That sounds very tough to repro. Do you have a Rust toolchain installed?

It would be interesting to see if you can execute one of the examples of https://github.com/rust-windowing/winit when Alacritty isn't able to launch anymore. I'd assume that also wouldn't work.

You can run an example using `cargo run --example window`.

**Comment by kurnevsky** [comment]
> That sounds very tough to repro. Do you have a Rust toolchain installed?

Yes, if anyone wants to dig into this I can help to test it.

> I'd assume that also wouldn't work.

Yes, it doesn't. And the same behavior as with alacritty - if I restart `xmonad` with focused example window it stops working.

**Comment by chrisduerr** [comment]
I've reported the issue upstream: https://github.com/rust-windowing/winit/issues/1474.

**Comment by chrisduerr** [comment]
Fixed in the latest master.
