### ISSUE TITLE
Env colors not respected depending on way Ubuntu terminal is opened. 

### ISSUE THREAD

**Issue by la-la-lasagna** [alacritty/alacritty#3353]
Hello I am on Ubuntu 16.04 and have set the env to TERM: xterm-256color.

In the normal gnome terminal I have a certain profile color theme and prompt style.  I have the same color theme defined in alacritty's yml file.  I have alacritty as my 'default' terminal so Ctrl-Alt-t opens it, as does right clicking and selecting 'open terminal'.  If I open alacrity with the latter option then it uses the color theme and prompt color used by the gnome terminal, but if I use the former method then the prompt colors are significantly darker. It could be possible that the theme in the yml is just a darker version of the theme I have in my gnome terminal, and that based on how alacritty is opened it uses a different source to select its theme?  I know for a fact that my bashrc is being sourced either way.  Any ideas off the top of your head?

Thanks

**Comment by kchibisov** [comment]
>If I open alacrity with the latter option then it uses the color theme and prompt color used by the gnome terminal

If you do `reset` after doing it does it become darker?

>It could be possible that the theme in the yml is just a darker version of the theme I have in my gnome terminal, and that based on how alacritty is opened it uses a different source to select its theme?

We're just reading `alacritty.yml` no more, no less. The only thing I could see is that you're overriding colors from shell in some cases.

**Comment by la-la-lasagna** [comment]
When I installed alacritty I made it my default terminal using:

sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/local/bin/alacritty 50

This apparently does not update the type of terminal that right-click opens: thus, my right click was opening gnome terminal (imagine that!).

Thanks for your quick reply anyway!
