### ISSUE TITLE
Incorrect color rendering using tmux

### ISSUE THREAD

**Issue by kyazdani42** [alacritty/alacritty#3354]
### System

OS: Linux
Version: 0.4.1
Linux: X11, picom, i3

### Issue

Since the last update of alacritty to 0.4.1 (on arch linux), certain colors are not rendering correctly when using tmux with `TERM=tmux-256color`.

This occurs only on program output, like vim, fzf or pastel. Try to render `#292d3e` for instance. It should render a dark blue but renders a brownish color instead.

**Comment by kchibisov** [comment]
Could you provide `echo $TERM` outside tmux, `echo $TERM` inside tmux and `.tmux.conf`.

**Comment by kyazdani42** [comment]
outside tmux: `TERM=alacritty`
inside tmux: `TERM=screen-256color`
tmux.conf:
```
set-option -g history-limit 100000

set-option -g default-shell /usr/bin/zsh

# only this line might not be enough
set -g default-terminal "screen-256color"
# Needs this line also to overrides the default color
set-option -ga terminal-overrides ",xterm-256color:Tc"

unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -g status-right ''
set -g status-right-length 0

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

set -g mode-keys vi
# Avoid ESC delay
set -sg escape-time 0

# need this: https://superuser.com/questions/210125/scroll-shell-output-with-mouse-in-tmux
setw -g mouse on
# shortcut for moving tmux buffer to clipboard
# useful if you've selected with the mouse
bind-key -nr C-y run "tmux show-buffer | xclip -in -selection clipboard &> /dev/null"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# pane border colors
set -g pane-border-style "bg=default fg=#232635"
set -g pane-active-border-style "bg=default fg=#232635"

# color for background of bar and foreground, default takes term colors
set -g status-bg default
set -g status-fg default

# messages
set -g message-style "fg=#89DDFF bg=#292d3e"
set -g message-command-style "fg=#89DDFF bg=#292d3e"

# status
set -g window-status-style "fg=#959dcb bg=#292d3e"
set -g window-status-current-style "fg=#89ddff,bold bg=#292d3e"
set -g mode-style "bg=#959dcb fg=#292d3e"

```

**Comment by kchibisov** [comment]
You’re overriding `xterm-256color` in `.tmux.conf`, but your `TERM` is `alacritty`, so override `alacritty`, or explicitly use `xterm-256color` in alacritty.yml.

**Comment by kyazdani42** [comment]
hum yeah sorry for that i didn't realize the terminfo changed in alacritty, thanks for your time

**Comment by kchibisov** [comment]
Arch finally updated its ncurses and now it has our terminfo ( it was a separate package before). By default we pick up our terminfo and fallback to `xterm-256color` if it’s missing.

**Comment by iamtvk** [comment]
> hum yeah sorry for that i didn't realize the terminfo changed in alacritty, thanks for your time

How to override TERM=alacritty in tmux config ?
I tried `"set -g default-terminal "alacritty"`
But tmux is ignoring it

**Comment by Sveske-Juice** [comment]
> How to override TERM=alacritty in tmux config ? I tried `"set -g default-terminal "alacritty"` But tmux is ignoring it

Something like this:
```
set-option -ga terminal-overrides ",alacritty:Tc"
set -g default-terminal "alacritty"
```
Remember to source the config file when you edit it:
`tmux source /path/to/conf`

**Comment by blueray453** [comment]
I did not have to change anything in `alacritty.yml`.

Thanks to @Sveske-Juice ,  Just `set-option -ga terminal-overrides ",alacritty:Tc"` worked. Just wanted to mention that, I have `set-option -g default-terminal "tmux-256color"`, did not need to change this.

**Comment by jj-attaq** [comment]
@Sveske-Juice 's solution worked for me too on macOS. 
Cheers!

**Comment by iysheng** [comment]
> You’re overriding `xterm-256color` in `.tmux.conf`, but your `TERM` is `alacritty`, so override `alacritty`, or explicitly use `xterm-256color` in alacritty.yml.

this helped me with same issue, tks.

**Comment by laughing-nerd** [comment]
> > How to override TERM=alacritty in tmux config ? I tried `"set -g default-terminal "alacritty"` But tmux is ignoring it
> 
> Something like this:
> 
> ```
> set-option -ga terminal-overrides ",alacritty:Tc"
> set -g default-terminal "alacritty"
> ```
> 
> Remember to source the config file when you edit it: `tmux source /path/to/conf`

Thanks a lot :D

**Comment by derletzteritter** [comment]
> > How to override TERM=alacritty in tmux config ? I tried `"set -g default-terminal "alacritty"` But tmux is ignoring it
> 
> Something like this:
> 
> ```
> set-option -ga terminal-overrides ",alacritty:Tc"
> set -g default-terminal "alacritty"
> ```
> 
> Remember to source the config file when you edit it: `tmux source /path/to/conf`

_Just_ setting this makes my backspace create spaces and then stops working lol

**Comment by Telmo-Sousa** [comment]
> > > > How to override TERM=alacritty in tmux config ? I tried `"set -g default-terminal "alacritty"` But tmux is ignoring it
> > > 
> > > 
> > > Something like this:
> > > ```
> > > set-option -ga terminal-overrides ",alacritty:Tc"
> > > set -g default-terminal "alacritty"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Remember to source the config file when you edit it: `tmux source /path/to/conf`
> > 
> > 
> > _Just_ setting this makes my backspace create spaces and then stops working lol Any idea what's going on there?
> 
> Alright, fixed it with just setting:
> 
> ```
> set -g default-terminal "screen-256color"
> set -as terminal-features ",xterm-256color:RGB"
> ```
> 
> I'm on MacOS btw

thanks! it worked perfectly on macos.
for reference on linux i have it like this:
(both using alacritty as terminals)
`set -ga terminal-overrides ",${TERM}:Tc"`

**Comment by Koxepis** [comment]
> Alright, fixed it with just setting:
> 
> ```
> set -g default-terminal "screen-256color"
> set -as terminal-features ",xterm-256color:RGB"
> ```
> 
> I'm on MacOS btw

Great it works, but now I have this background instead of some of the highlights, tried with different color scheme and they have all the same issue
![image](https://github.com/user-attachments/assets/b5121df7-110e-4c9e-ba4a-289373d8767f)
