### ISSUE TITLE
Bitmap font rendering issue after 2672770

### ISSUE THREAD

**Issue by bitraid** [alacritty/alacritty#3355]
### System

OS: Linux
Version: 2672770 regression
Compositor: sway version 1.4-31a83bd4

The following screenshots are with a config that only sets the font to terminus (`terminus-font-otb` on ArchLinux), dispaying character ❯ (U+276F):
From 15cc07c:
![good1](https://user-images.githubusercontent.com/4866740/74759810-0ae18780-5282-11ea-84ce-75bc30fafefe.png)
From 2672770:
![bad1](https://user-images.githubusercontent.com/4866740/74759848-1af96700-5282-11ea-9c28-d601dd606208.png)
Logs are identical.

**Comment by kchibisov** [comment]
Could you compare to v0.4.1?

**Comment by bitraid** [comment]
I have, it works ok.

**Comment by bitraid** [comment]
2672770 (larger font):
![bad2](https://user-images.githubusercontent.com/4866740/74761804-58abbf00-5285-11ea-9322-f4287b06c1db.png)


0.4.1:
![good2](https://user-images.githubusercontent.com/4866740/74761744-3fa30e00-5285-11ea-96d6-dbd638d243f9.png)

**Comment by kchibisov** [comment]
Could you test #3336 ?

**Comment by bitraid** [comment]
It doesn't seem to make a difference.

**Comment by ngortheone** [comment]
I have upgraded to 0.4.2-dev and now fonts look ugly
![DeepinScreenshot_select-area_20200218154454](https://user-images.githubusercontent.com/18271144/74788102-cfa67f00-52a8-11ea-8449-52d80fa743e6.png)

Left  - Before (0.4.1)
Right - After (0.4.2-dev)

If this is a different issue or can be fixed with a setting - please point me in the right direction!

**Comment by kchibisov** [comment]
It seems like metrics on your screen shot are strange. Could you share your config?

**Comment by kchibisov** [comment]
@ngortheone it'll be also nice if you can do a bisect.

**Comment by kchibisov** [comment]
Could you test  #3359 ?

**Comment by kchibisov** [comment]
Also, the glyph `❯` isn't from Terminus font, it's from some scalable fallback font, so it's not a bitmap font rendering issue.

**Comment by bitraid** [comment]
> Could you test #3359 ?

Yes, it's fixed!

>Also, the glyph ❯ isn't from Terminus font, it's from some scalable fallback font, so it's not a bitmap font rendering issue.

Oh, i see. That explains why everything else looked normal.

**Comment by kchibisov** [comment]
@ngortheone if you still has issues with the latest master, let me know.
