### ISSUE TITLE
Nano/vim in SSH session respond with "Error opening terminal: alacritty." and other weird things.

### ISSUE THREAD

**Issue by mielouk** [alacritty/alacritty#3360]
When I log into another machine (router/laptop) and want to open nano (or vi for that matter) the response is 

`Error opening terminal: alacritty.`

While it works in other terminals. Another weird issue: When I log into my laptop, the input gets mangled.

![2020-02-19-213309_grim](https://user-images.githubusercontent.com/3057062/74873539-b14f8a80-535f-11ea-87df-72bcd4a41831.png)
This is after typing nan

![2020-02-19-213543_grim](https://user-images.githubusercontent.com/3057062/74873597-cc21ff00-535f-11ea-90e1-09f12474d606.png)
This after nano and enter

TERM=alacritty is set

### System

OS: Linux/
Version: `0.4.1`
Linux: Arch, Wayland, sway

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: 

`Created log file at "/tmp/Alacritty-659416.log"
[2020-02-19 21:27] [INFO] Welcome to Alacritty
[2020-02-19 21:27] [INFO] Configuration loaded from "/home/nackt/.config/alacritty/alacritty.yml"
[2020-02-19 21:27] [DEBUG] Estimated DPR: 1
[2020-02-19 21:27] [DEBUG] Estimated Cell Size: 8 x 15
[2020-02-19 21:27] [DEBUG] Estimated Dimensions: None
[2020-02-19 21:27] [INFO] Device pixel ratio: 1
[2020-02-19 21:27] [INFO] Initializing glyph cache...
[2020-02-19 21:27] [INFO] ... finished initializing glyph cache in 0.0757497s
[2020-02-19 21:27] [INFO] Cell Size: 8 x 15
[2020-02-19 21:27] [INFO] Padding: 0 x 0
[2020-02-19 21:27] [INFO] Width: 800, Height: 600
[2020-02-19 21:27] [INFO] PTY Dimensions: Line(40) x Column(100)
[2020-02-19 21:27] [INFO] Initialisation complete
[2020-02-19 21:27] [DEBUG] New num_cols is 239 and num_lines is 25
[2020-02-19 21:27] [INFO] Width: 1916, Height: 389`

Keyboard and bindings: `alacritty --print-events` https://8n1.org/16805/9da5 The log gets deleted automatically.

**Comment by kchibisov** [comment]
Your remote server doesn't have `alacritty` terminfo, so that's why you're seeing this error. So you should install `alacritty` terminfo on a remote server or use a different `terminfo` either in config or per connection with `env TERM=xterm-256color ssh` could work.

**Comment by mielouk** [comment]
Well, it worked before in alacritty and does so in other terminals. What's the point in installing this on all machines? On my router I'm quite sure that I won't be able to install alacritty on.

**Comment by kchibisov** [comment]
>Well, it worked before in alacritty and does so in other terminals. 

Arch updated `ncurses`, `ncurses` ships our `terminfo` now, you didn't specified `terminfo` in `alacritty.yml`, after Arch update, we've picked up `alacritty` `terminfo`, since we're doing it by default or fallback to `xterm-256color`(your worked before).

 >On my router I'm quite sure that I won't be able to install alacritty on.

You don't need `alacritty` aka terminal emulator, you need `alacritty` aka terminfo file. You can install one for user if you want,  read https://github.com/alacritty/alacritty/blob/master/INSTALL.md#terminfo (you can do that without `sudo`, just for user).

>does so in other terminals

This is a terminfo thing, so depends on what you're using. to check what other terminals are using use `echo $TERM`.

>What's the point in installing this on all machines?

To have a proper terminfo, like `xterm-256color` is a terminfo, so you have it on all machines you connect to, since it worked before, your router likely had it, etc, etc.

**Comment by mielouk** [comment]
ok, thx. I'll give it a try.

**Comment by mnlx** [comment]
@kchibisov txs

This worked for me

```sh
TERM=xterm-256color ssh
```

**Comment by lorenzznerol** [comment]
And if you are already on that ssh server or anywhere where you do not need to further ssh somewhere, use the above command just without `ssh` at the end.

**Comment by quansho** [comment]
Just write the line 
TERM=xterm-256color 
in ~/.bashrc file

**Comment by Valetra** [comment]
@quansho thank you very much!

To clarify important moment:
This manipulation must be performed on your local machine, and not on the server to change the terminal used from Alacritty to xTerm

(I 'm writing because I tried to make changes in the file .bashrc on the server)
