### ISSUE TITLE
Secure Keyboard Entry on MacOS

### ISSUE THREAD

**Issue by aiguofer** [alacritty/alacritty#3364]
### System

OS: macOS
Version: 0.4.1

I'm using Alacritty and [skhd](https://github.com/koekeishiya/skhd) and every once in a while skhd stops working. When I try to re-start it manually I see the following error:

```
skhd: successfully created pid-file..
skhd: secure keyboard entry is enabled by (56914) 'alacritty'! abort..
```

From my understanding, terminals have a way to enable "secure keyboard entry" to prevent apps from seeing what is being typed (see [here](https://support.apple.com/guide/terminal/use-secure-keyboard-entry-trml109/mac)). I'm not sure what exactly is setting this (seems kind of random), but after it's set the only thing I've found to get `skhd` to work again is restarting my computer.

Is there some setting in Alacritty for this, or a way to permanently disable it?

Thanks

**Comment by chrisduerr** [comment]
As far as I know, we don't set anything like that explicitly ourselves. I'm also running skhd myself and have never run into this issue.

I also find the purpose of this misleading and it seems like something that would easily give users a false sense of security, so I don't think it would make sense to enable it even if I would know how.

Which macOS version are you using?

**Comment by adipurnama** [comment]
Hi @aiguofer ,

I also came across this issue a couple of weeks ago. In my case, it happened when I've just updated `alacritty`, `skhd` or `yabai` via homebrew.

Check your mac `System Preferences -> Security & Privacy` menu. Allow / tick checkbox permission for `skhd` & `alacritty` (if any) on `Accessibility or Input Monitoring`.

**Comment by OJFord** [comment]
I also use alacritty, skhd, and yabai; but none of them even requests 'Input Monitoring' permission. They are all enabled in 'Accessibility' of course, but I haven't encountered this issue.

**Comment by aiguofer** [comment]
Hmm strange.. I'm on latest MacOS, 10.15.3. 

However, today I noticed that the error will display whichever terminal application I'm using to try to start `skhd` so it might not be an alacritty issue but a skhd issue.. I'll check there.

**Comment by chrisduerr** [comment]
As suggested in https://github.com/koekeishiya/skhd/issues/48, this is likely an issue that is caused by some other application setting the secure keyboard entry mode.

I can assure you that Alacritty is not setting it itself, so you'll have to look at what other applications you have running on your system.

**Comment by nixpulvis** [comment]
FWIW, I had never heard of this setting before, so I found a decent explanation (and reference to the documentation) here: https://security.stackexchange.com/questions/47749/how-secure-is-secure-keyboard-entry-in-mac-os-xs-terminal.

It's interesting to me that having this setting enabled would change the way unrelated apps work even if the program is in the background. Makes sense, but still...

**Comment by koekeishiya** [comment]
For what it's worth, documentation for the affected Apple API used by skhd is here: 

Overview
Event taps make it possible to monitor and filter input events from several points within the system, prior to their delivery to a foreground application. Event taps complement and extend the capabilities of the Carbon event monitor mechanism, which allows an application to observe input events delivered to other processes (see the function GetEventMonitorTarget()).

Event taps are designed to serve as a Section 508 enabling technology. For example, consider a software system to assist a person with language impairments, designed to perform keyboard filtering with spoken review. Such a system could use an event tap to monitor all keystrokes, perform dictionary checks and matches, and recite the assembled word back to the user on detection of a word break in the input stream. If acceptable to the user, as indicated by an additional input keystroke or other gesture, the events would be posted into the system for delivery to the foreground application.

Introduced in OS X version 10.4, event taps provide functionality similar to the Win32 functions SetWinEventHook when used to establish an out-of-context event hook, and SendInput. Quartz Event Services also includes an older set of event-related functions declared in the file CGRemoteOperation.h. These functions are still supported, but they are not recommended for new development.

Source: https://developer.apple.com/documentation/coregraphics/quartz_event_services

**Comment by jeffpeck10x** [comment]
Ran into this recently:
```
skhd: secure keyboard entry is enabled by (92111) 'alacritty'! abort..
```

I noticed that I had the MacOS `Terminal` app open (for some reason). I quit it, and `skhd` worked. 🤷 

It looks like there is a "Secure Keyboard Entry" option in the Terminal app, so that makes sense, I suppose.
