### ISSUE TITLE
Don’t allow setting HollowBlock and hidden cursors in config

### ISSUE THREAD

**Issue by kchibisov** [alacritty/alacritty#3367]
We shouldn’t allow both mentioned cursors in a config file, since they are only for internal usage and was leaked due to serde tbh. Also you can’t use Hollow cursor, since there’s no way to restore it.

**Comment by chrisduerr** [comment]
> Also you can’t use Hollow cursor, since there’s no way to restore it.

That's not entirely true, you can use `echo -e "\e[0 q"` to restore it regardless of what your current cursor is.

**Comment by kchibisov** [comment]
Oh, with reset sure, but you should do it manually most of the time, I guess.

**Comment by kurddt** [comment]
Hi I would be interested to have a HollowBlock cursor by default. I reverted #3410 and everything seems to work fine, I probably miss something but what is the reason this has been removed ?

**Comment by chrisduerr** [comment]
Because the hollow block cursor makes no sense as a normal terminal cursor.
