### ISSUE TITLE
SimpleFullscreen should fall back to Fullscreen on Linux

### ISSUE THREAD

**Issue by koterpillar** [alacritty/alacritty#3370]
I'd like to share my Alacritty configuration file between a Linux and a macOS machines. Furthermore, on macOS, I want the `SimpleFullscreen` startup behavior. However, if I set that in the config, on Linux machine I get:

```
[2020-02-23 09:29] [ERROR] Problem with config: unknown variant `SimpleFullscreen`, expected one of `Windowed`, `Maximized`, `Fullscreen`; using default value
```

I expect the value to be converted to `Fullscreen` when `SimpleFullscreen` isn't available.

### System

OS: Linux and macOS
Version: 0.4.1
Linux: Wayland, Gnome

**Comment by chrisduerr** [comment]
The `SimpleFullscreen` option is not supported outside of macOS, as stated in the configuration file.

Converting between options when there is no direct equivalent on the other platforms is just going to lead to problems, instead a proper configuration file with options that are supported by the specific platform should be used.

If you use `git` to manage your dotfiles, as many people do, it should be trivial to just make a minor change in a separate branch for the different operating systems.

**Comment by nixpulvis** [comment]
I'm sympathetic to this issue, but a proper solution to cross platform config a would be better (either internally to Alacritty or externally as @chrisduerr mentions). There are other kinds of platform specific configurations, most notably, keybindings. I personally run a branch per machine for my dotfiles, and this strategy has been working very well for me.

**Comment by chrisduerr** [comment]
https://github.com/alacritty/alacritty/issues/779 would probably be more interesting as a solution.
