### ISSUE TITLE
Interpret integers for color configurations

### ISSUE THREAD

**Issue by FichteFoll** [alacritty/alacritty#3381]
Currently, colors must be provided as strings as verify their formatting, which means instead of writing `background: 0x0a0a0a` you have to write `background: '0x0a0a0a'`, since YAML automatically parses hexadecimal numbers starting with `0x`. However, I believe this to be unnecessary as interpreting an integer number `0x0a0a0a` as an RGB24 color is absolutely trivial.

Is there any particular reason for why this hasn't been done or was it just deemed unnecessary? Based on the error log, there is specific error checking code for this.
Maybe a limitation of the yaml parser library and its integration?

**Comment by chrisduerr** [comment]
> Is there any particular reason for why this hasn't been done or was it just deemed unnecessary? 

Why would we support this? It would just make things more complicated and require additional code, just so we can handle something that isn't really necessary?

We already support two different formats, that should be enough.

**Comment by kchibisov** [comment]
We're leaving for a long time with '0xffffff' and '#ffffff' ( I use the later one for example), so there's unlikely a chance old users start using new syntax, I'm not sure that a lot of users are using '#ffffff' form. Adding one more similar option doesn't make any sense to me.

**Comment by nixpulvis** [comment]
See #3383

**Comment by nixpulvis** [comment]
I'm torn on this issue.

It's yet another case of simplicity of configuration vs simplicity of code, and a trade-off must be made. I would personally accept a patch that implemented this cleanly, but I'm not sure others would agree.

If I had things my way, the format `0x0a0a0a` would be numeric (not requiring quotes), and the format `#0a0a0a` would be a string.

**Comment by kchibisov** [comment]
I mean it doesn't make sense to have one more format, you can't use `0x0a0a0a` format instead of `'0x0a0a0a'` format since mostly all config files are using the later one, so you'll break tons of configs.

**Comment by nixpulvis** [comment]
@kchibisov we can deprecate things, breaking configs shouldn't completely block all improvements to the config. Users shouldn't expect the config file to be stable until we say it is.

**Comment by kchibisov** [comment]
I don't see any issue in having surrounding `'` tbh, since we still continue to ban `0x0` things. And string makes more sense for color than arbitrary num in a config. I'd argue to just keep '#rrggbb' format though.

**Comment by nixpulvis** [comment]
> I don't see any issue in having surrounding ' tbh

`less` is `more` :)

**Comment by chrisduerr** [comment]
> less is more :)

Exactly, which is why we shouldn't try to support even one more format.

My suggestion is to just decide on one format and leave the other undocumented. As far as I can tell, there's no advantage to having `0x` format. So while we can keep it, I'd suggest removing every mention of it.

**Comment by FichteFoll** [comment]
My main concern for this report was how YAML interprets types and that you need to enquote `0x`-notated numbers to have them interpreted as strings, which may not be obvious to users not used to the format and cause them to unnecessarily run into this error scenario. While I like this about YAML, as it is true to the coders intentions in many cases (I would argue this is one of these cases, too), it's something that applications need to consider and potentially work around to make the experience for the user smoother.

While still requiring quotation, endorsing the hash notation instead of `0x` (#3392) is easier for users, since they can see that `#` opens a line comment in probably every editor and that they are doing something wrong, whereas this wouldn't be the case with `0x`. I didn't even know this format was accepted. It is *clearly* distinct from an integer number and thus wouldn't accidentally be considered to be one.

**Comment by nixpulvis** [comment]
@FichteFoll thanks for opening this issue, I'm glad we reached a good solution that simplifies things.
