### ISSUE TITLE
Add config option to restrict use of certain OSCs

### ISSUE THREAD

**Issue by kchibisov** [alacritty/alacritty#3386]
Some `OSC`s could be not desirable for some users. As an example `OSC 7` or `OSC 50` are a bit strange, but one could make use of them. Also some folks could decide to disable `OSC 52`. The motivation for banning some of them is security (`OSC 52`) or annoyance (`OSC 7`).

**Comment by nixpulvis** [comment]
For posterity @kchibisov, can you link some issues about why `OSC 52` is a security issue, and how `OSC 7` is annoying? I think I personally understand the former, but not necessarily the latter.

**Comment by kchibisov** [comment]
I'm not saying that `OSC 52` is security issue myself, but literally every script in your terminal could read clipboard and some terminal apps are disabling it by default(xterm,tmux). As for `OSC 7`, just imagine some script or shell will change your directory and you open a new window. I always want for all windows to have the same working directory and if something will arbitrary change it, I'll get annoyed. It's also strange in a context of `ssh`, so I just don't want to have `OSC 7`.

I don't mind `OSC 52`, but I don't want  `OSC 7`.

**Comment by kchibisov** [comment]
Also, this is just an example of some `OSC`, there're tons of them and some of them are really strange, like the one that could resize a window.

**Comment by kchibisov** [comment]
The issue is inspired by this `xterm` thing https://invisible-island.net/xterm/manpage/xterm.html#VT100-Widget-Resources:allowWindowOps.

**Comment by egmontkob** [comment]
For OCS 52, see https://bugzilla.gnome.org/show_bug.cgi?id=795774

**Comment by chrisduerr** [comment]
I don't see much issue with any of the points raised in that issue.

Though allowing users to opt-out would still be nice of course. But I don't see any reason why it would be made opt-in.
