### ISSUE TITLE
One emoji is rendered huge

### ISSUE THREAD

**Issue by virus-found** [alacritty/alacritty#3387]
### System

OS: Void Linux
Version: alacritty 0.4.2-dev (50c1fd0)
Linux/BSD: Wayland, Sway

This text:
```
👋lobby
🎵music
🎮games
📣announcements
🏰members-chat
💬chat
🏹ig_battlegrounds
🐎mount-and-blade
```
looks like this (note the bow emoji being huge):
![2020-02-27-130741](https://user-images.githubusercontent.com/102547/75434628-ec0a8180-5962-11ea-9cb6-8d923dfacd3e.png)

The alacritty config: https://0x0.st/ibPH.yml 
Yesterdays alacritty master didn't have this issue.

**Comment by kchibisov** [comment]
Could you bisect? I can’t repro this issue.

**Comment by kchibisov** [comment]
It seems like you've disabled scaling of bitmap fonts, however our workaround for this case were broken a while ago.

**Comment by virus-found** [comment]
Thanks, that fixed it.
Btw I've never changed scaling of bitmap fonts. (I presume it's done in fontconfig?) I use default font settings from the distro.

**Comment by kchibisov** [comment]
It’s done by `/etc/fonts/conf.avail/10-scale-bitmap-fonts.conf` IIRC. You can check `fc-conflist` to check whether it’s enabled for you.
