### ISSUE TITLE
Decouple gui-related bits out of 'alacritty_terminal'

### ISSUE THREAD

**Issue by kchibisov** [alacritty/alacritty#3393]
Even after splitting Alacritty into 2 parts (`alacritty` and `alacritty_terminal`) we still have some bits that are make sense only for gui apps, like dependency to `font` and `copypasta`. Font dependency is purely config related and `copypasta`  could be replaced by creating a clipboard trait in `alacritty_terminal` and implementing it in `alacritty`. Ideally we should move our config related bits out of `alacritty_terminal` into `alacritty`, however I'm not sure how much of it we should move out.

There's also one part with `RenderableCell`'s which should likely be moved somehow out of `term/mod.rs`, but I don't have a good idea on how to do that.

**Comment by chrisduerr** [comment]
> Ideally we should move our config related bits out of alacritty_terminal into alacritty, however I'm not sure how much of it we should move out.

We already do have that setup. Our bindings are fully outside of `alacritty_terminal` for example.

The current config in `alacritty_terminal` should be completely about terminal specific configuration, without anything GUI related.

> There's also one part with RenderableCell's which should likely be moved somehow out of term/mod.rs, but I don't have a good idea on how to do that.

Why do you say that? No matter what you use to render the terminal, it still has to be rendered, right? Even if that 'rendering' just means to print characters to stdout.

I also disagree **strongly** with the priority of this issue, so I'm curious what has motivated you to set this to *high*.

**Comment by kchibisov** [comment]
>We already do have that setup. Our bindings are fully outside of alacritty_terminal for example.

I know, but we don't have everything moved. Visual bell, font, window shouldn't be a part of `alacritty_terminal`. Not sure about visual bell though.

>The current config in alacritty_terminal should be completely about terminal specific configuration, without anything GUI related.

We still have font crate as a dependency in alacritty_terminal, font configuration is also done inside of it. Look at https://github.com/alacritty/alacritty/blob/master/alacritty_terminal/src/config/font.rs .

>I also disagree strongly with the priority of this issue, so I'm curious what has motivated you to set this to high.

I just don't want to continue adding gui related things to `alacritty_terminal`, my main concern is these 2 dependencies (`copypasta` and `font` crate). For example our font crate is linking to native libs indirectly, so using `alacritty_terminal` downstream could be hard for `tmux` like apps, since they don't even need something like that, same applies for copypasta to some point.

>Why do you say that? No matter what you use to render the terminal, it still has to be rendered, right? Even if that 'rendering' just means to print characters to stdout.

I was curios whether it's possible to let downstream implement a trait to get RenderableCells in a way they want them. So shaping glyphs with `harfbuzz/allsorts` could be done outside of `alacritty_terminal`, which should avoid linking to some native libs, have strange dependencies in our terminal crate.

>I also disagree strongly with the priority of this issue, so I'm curious what has motivated you to set this to high.

Because it's easy to do this thing earlier than later. Maybe `high` is a wrong priority, but we shouldn't keep this issue around for a long time, since decoupling could become harder if we continue to work on ligatures, etc.

**Comment by chrisduerr** [comment]
> I know, but we don't have everything moved. Visual bell, font, window shouldn't be a part of alacritty_terminal. Not sure about visual bell though.

Sure, there certainly are some things that could still be refactored out.

> I just don't want to continue adding gui related things to alacritty_terminal, my main concern is these 2 dependencies (copypasta and font crate). For example our font crate is linking to native libs indirectly, so using alacritty_terminal downstream could be hard for tmux like apps, since they don't even need something like that, same applies for copypasta to some point.

This doesn't really justify the priority? There is no downstream application using Alacritty's terminal at the moment, so why is it a high priority to fix that? Chances are these remaining issues could be easily resolved by someone actually trying to implement such a thing, especially because you will **always** need an actual test application to really figure out what should be extracted and what needs to stay.

Even if we "finish" our extraction work as far as we can tell, I'm sure that if someone would actually try to make use of it, they'll quickly figure out some issues with things that we removed which they'd like back inside of it, or things they cannot implement in their specific application but it is required by us.

> I was curios whether it's possible to let downstream implement a trait to get RenderableCells in a way they want them. So shaping glyphs with harfbuzz/allsorts could be done outside of alacritty_terminal, which should avoid linking to some native libs, have strange dependencies in our terminal crate.

But a renderable cell does not contain any of this information. It's literally just a `char`, or an array of `char`s when there's zero width characters attached. Shaping is already done outside of `alacritty_terminal`, we do that when adding cells to the render batch in our `display.rs` loop.

> Because it's easy to do this thing earlier than later. Maybe high is a wrong priority, but we shouldn't keep this issue around for a long time, since decoupling could become harder if we continue to work on ligatures, etc.

It's already `later`. It's far too late to do things earlier already. I see absolutely no reason why we shouldn't keep this issue around for a long time. If we consider this for future PR's that's plenty already. If it's easier right now to put things into `alacritty_terminal`, that's perfectly fine. As long as there's no good usecase for `alacritty_terminal`, there's no reason why we would make this a high priority to extract things.

**Comment by kchibisov** [comment]
>It's already later. It's far too late to do things earlier already. I see absolutely no reason why we shouldn't keep this issue around for a long time. If we consider this for future PR's that's plenty already. If it's easier right now to put things into alacritty_terminal, that's perfectly fine. As long as there's no good usecase for alacritty_terminal, there's no reason why we would make this a high priority to extract things.

I agree, but I just don't want to see `font` and `copypasta` as deps. It's pretty straightforward to ditch them now, so it could save us time later.

>But a renderable cell does not contain any of this information. It's literally just a char, or an array of chars when there's zero width characters attached. Shaping is already done outside of alacritty_terminal, we do that when adding cells to the render batch in our display.rs loop.

That's actually true, but as I said, I wasn't sure about ditching it, so we can keep them around.

I agree that priority isn't high wasn't that good, but I just personally don't want to keep it around for a while, so I'll likely start slowly ditching the thing.

**Comment by chrisduerr** [comment]
> I agree that priority isn't high wasn't that good, but I just personally don't want to keep it around for a while, so I'll likely start slowly ditching the thing.

PRs are certainly welcome to separate things as well as possible, but I don't think we need to make sure this is 'finished' anytime soon.

**Comment by dzhang-b** [comment]
Can `alacritty_terminal` be used as a stand alone terminal emulator layer in other rust application? 
For example, I have a need to write a TUI application that supports opening other TUI application inside. (similar to tmux/screen)

**Comment by kchibisov** [comment]
yeah, it can, but it's a bit hard right now due to its design in some cases. However we're all for improving that and allowing tmux like applications to be implemented without much issues. The problem now is certain aspects are very GUI oriented and not TUI, but it'll be changed.

**Comment by dzhang-b** [comment]
I was reading the `alacritty_terminal` code. I see that alacrity handles printable characters in `vte` state machine. How does `alacritty` handle `Ctrl-A`, `Ctrl-E`, `Ctrl-K`, `Ctrl-U` these terminal shortcuts? It seems like they did not go through pty_read functions. Are they handled outside the `alarcrity_terminal`?

**Comment by kchibisov** [comment]
Those keys are coming from your system, when you press `Ctrl + A`, your system sends `\u{1}`.

**Comment by dzhang-b** [comment]
Yes. So input `Ctrl-A`, `write_to_pty`  invokes `notify` function that only sends one byte `{1}`. And then is another thread named `PTY reader` receive the input?  how the input is processed further?

Thanks in advance!
