### ISSUE TITLE
Paste multiple lines in nano

### ISSUE THREAD

**Issue by mamutal91** [alacritty/alacritty#3394]
Hello everyone,
I'm having trouble paste things with more than one line. This only happens with alacritty + nano.
Whenever I lap, he leaves everything in a single line.
Thanks everyone, follow the logs and gif of the problem

![gif](https://i.imgur.com/vE2P8Go.gif)

### System

OS: ArchLinux
Version: `alacritty 0.4.1`
Linux: X11, compton and WM

### Logs

Font/Terminal size: https://del.dog/uvyjamecky.txt
Keyboard and bindings: https://del.dog/grinihamog.txt

**Comment by chrisduerr** [comment]
Does this only happen in nano? If so, that would suggest to me that it's a nano, problem.

It would also be good to know how you're copying things. Are you certain the source actually contains linewraps?

**Comment by kchibisov** [comment]
Can't repro this issue with `nano` for me everything seems fine on both Wayland and X11.

**Comment by mamutal91** [comment]
> Does this only happen in nano? If so, that would suggest to me that it's a nano, problem.
Yes, only with nano. alacritty + vim works. However, termite + nano works too.

> It would also be good to know how you're copying things. Are you certain the source actually contains linewraps?
Yes

**Comment by mamutal91** [comment]
> Can't repro this issue with `nano` for me everything seems fine on both Wayland and X11.

There may be something wrong, or missing, in my system. I need to find out

**Comment by kchibisov** [comment]
Well, could you launch `env TERM=xterm-256color nano` and retest?

**Comment by mamutal91** [comment]
> env TERM=xterm-256color nano
>
Yes
![img](https://i.imgur.com/ARw7dYL.png)

**Comment by chrisduerr** [comment]
>> It would also be good to know how you're copying things. Are you certain the source actually contains linewraps?

> Yes

This does not answer my questions about the source of the selection. Where does it actually come from?

**Comment by mamutal91** [comment]
> > > It would also be good to know how you're copying things. Are you certain the source actually contains linewraps?
> 
> > Yes
> 
> This does not answer my questions about the source of the selection. Where does it actually come from?

I do not speak fluent English, I may not be able to understand your question.

But if it’s about where I’m copying from, it’s from any source. My Atom editor scripts, internet browser codes, any source.

I'm persisting because I don't want to change the terminal or the editor.

**Comment by kchibisov** [comment]
Ok, could you test whether it happens with our block selection?

So you just open new alacritty window, do `ls -lah`, press `Ctrl`, select some text, so it'll be on multiple lines, open nano, and paste text into it?

**Comment by mamutal91** [comment]
> ls -lah

![img](https://i.imgur.com/684OPqe.gif)

This?

**Comment by kchibisov** [comment]
Could you retest with `alacritty --config-file /dev/null`?

**Comment by mamutal91** [comment]
> alacritty --config-file /dev/null

![img](https://pasteboard.co/IWIpX9O.gif)

**Comment by kchibisov** [comment]
It's a `nano` bug(feature), which requires the use of `\r` for new lines instead of `\n`, read http://savannah.gnu.org/bugs/?49176 . Mostly all terminal emulators has/had this issue at some point and add/declined to add workaround around broken editors like `nano`.

I can't say why mine works though, since I don't have `\r` in a text.
