### ISSUE TITLE
alacritty.yml on macOS does not take effect

### ISSUE THREAD

**Issue by liuchengxu** [alacritty/alacritty#3397]
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

OS: macOS
Version: alacritty 0.4.2-dev (2365425)
Linux/BSD: N/A
Windows: N/A

### Logs

Crashes: STDERR, STDOUT
No crash.

Font/Terminal size: `alacritty -vv`

[Alacritty-45929.log](https://github.com/alacritty/alacritty/files/4266533/Alacritty-45929.log)

Keyboard and bindings: `alacritty --print-events`

[Alacritty-45798.log](https://github.com/alacritty/alacritty/files/4266529/Alacritty-45798.log)

-------

I randomly change the default size to 50 based on https://github.com/alacritty/alacritty/blob/master/alacritty.yml, but nothing changed, actually it looks like my alacritty.yml is ignored even though the log sees it. I run into this after I reinstalled my whole compute, let me know if I can provide more info.

```diff
diff --git a/alacritty.yml b/alacritty.yml
index b65b4f0..4257fd2 100644
--- a/alacritty.yml
+++ b/alacritty.yml
@@ -145,7 +145,7 @@
     #style: Bold Italic

   # Point size
-  #size: 11.0
+  #size: 50.0

   # Offset is the extra space around each character. `offset.y` can be thought of
   # as modifying the line spacing, and `offset.x` as modifying the letter spacing
```

**Comment by kchibisov** [comment]
You should uncomment the field, it's a YAML file and `#` is for commenting things out.

**Comment by liuchengxu** [comment]
@kchibisov Thanks for the pointer, that was a typo in the last comment :(. 

I cloned alacritty to `~/src/github.com/alacritty/alacritty` and compiled it locally. In case of the typo again, I did a symlink for the config file. But the result is still the same. I don't see it taking effect.

```bash
$ ln -s ~/src/github.com/alacritty/alacritty/alacritty.yml ~/.config/alacritty/alacritty.yml
$ ls -l ~/.config/alacritty/alacritty.yml
lrwxr-xr-x  1 xuliucheng  staff  66 Feb 28 19:26 /Users/xuliucheng/.config/alacritty/alacritty.yml -> /Users/xuliucheng/src/github.com/alacritty/alacritty/alacritty.yml
$ git diff
```
```diff
diff --git a/alacritty.yml b/alacritty.yml
index b65b4f0..2263194 100644
--- a/alacritty.yml
+++ b/alacritty.yml
@@ -145,7 +145,7 @@
     #style: Bold Italic
 
   # Point size
-  #size: 11.0
+  size: 50.0
 
   # Offset is the extra space around each character. `offset.y` can be thought of
   # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
```

**Comment by kchibisov** [comment]
You should un-comment  a top level `font` section, since it's `font.size` and not just `size`.

**Comment by liuchengxu** [comment]
@kchibisov Thanks! That did the trick.
