### ISSUE TITLE
zsh vi-mode: issue in Visual mode

### ISSUE THREAD

**Issue by yanzhang0219** [alacritty/alacritty#3400]
macOS version: 10.15.3
Alacritty version: 0.4.2-dev (43f89a6)

I am using vi-mode in zsh (add `bindkey -v` in zshrc). 

First I type something:
<img width="123" alt="image" src="https://user-images.githubusercontent.com/11582667/75603064-ba3b0d00-5a7f-11ea-8ee4-862fb40f6290.png">

Then I press `ESC` to enter Normal mode:
<img width="123" alt="image" src="https://user-images.githubusercontent.com/11582667/75603070-cd4ddd00-5a7f-11ea-8a46-fbf005303b1a.png">

And then I press `v` to enter Visual mode:
<img width="123" alt="image" src="https://user-images.githubusercontent.com/11582667/75603076-da6acc00-5a7f-11ea-8eba-6532be72cb16.png">
See, the cursor disappears. In the correct way, the cursor should be on the last character which also means a selection of the last character. The Correct form should be (tested in kitty terminal and iTerm2):
<img width="123" alt="image" src="https://user-images.githubusercontent.com/11582667/75603084-07b77a00-5a80-11ea-8d04-670be0a40544.png">

Next, I make a selection, say selecting the last three characters by move the cursor left two times:
<img width="123" alt="image" src="https://user-images.githubusercontent.com/11582667/75603140-a04dfa00-5a80-11ea-9a2a-e2da2b0dc2f5.png">
Actually the last three "c"s should be highlighted but just two here. 
The correct form should be (tested in kitty terminal and iTerm2):
<img width="123" alt="image" src="https://user-images.githubusercontent.com/11582667/75603156-ca072100-5a80-11ea-936b-4abbd49e1215.png">

At last, I press `d` to delete what I have selected:
<img width="123" alt="image" src="https://user-images.githubusercontent.com/11582667/75603163-e0ad7800-5a80-11ea-8812-c6fe541282b0.png">
So, the last three "c"s are deleted, which means before this deletion, the last three "c"s were selected indeed, even though only two are highlighted. 

Thank you.

Best regards,

**Comment by kchibisov** [comment]
Could you provide `alacritty -vvv` output during your repro?

**Comment by kchibisov** [comment]
Oh, wait. could you set cursor color in config to a fixed value?

**Comment by yanzhang0219** [comment]
Hi, 

It is fixed by setting the cursor color explicitly. Thank you. But I am still confused that why I can see the cursor without entering Visual mode?
<img width="123" alt="image" src="https://user-images.githubusercontent.com/11582667/75603642-32f09800-5a85-11ea-8705-68e0e6748151.png">
Normally and by default, the cursor is like this. 

Thanks.

**Comment by kchibisov** [comment]
>I can see the cursor on Normal mode but it gets invisible in Visual mode.

Because visual mode likely select the color and it's done by your shell. Look at the zsh selection color, it's identical to a cursor, so inverting the cursor over it results in invisible cursor, since zsh selection seems also inverted.

**Comment by yanzhang0219** [comment]
I see. Thanks a lot. I will close this.
