### ISSUE TITLE
No colors in vim

### ISSUE THREAD

**Issue by doums** [alacritty/alacritty#3402]
OS: ArchLinux, X11, XFCE4 & (compositor picom -> active campton fork)
Alacritty version: 0.4.1

Hi,

Recently I noticed that my color scheme does not work anymore in vim.
Now I have no color at all !
If I add this to my `.vimrc` it fix the problem but I think is not a good solution:
```
if &term == "alacritty"        
  let &term = "xterm-256color"
endif
```

If you need the to look at the colorscheme, here is its code -> https://github.com/doums/darcula/blob/master/colors/darcula.vim

**Comment by kchibisov** [comment]
It seems like vim hard codes `terminfo` to understand whether it has colors or no? Like if this is what fixes vim this is a vim problem that it can't work with terminfos different to xterm-256color.

**Comment by kchibisov** [comment]
Trying adding this to your vimrc.

```
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48:2;%lu;%lu;%lum"
```

**Comment by potuz** [comment]
> Trying adding this to your vimrc.
> 
> ```
> let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
> let &t_8b = "\<Esc>[48:2;%lu;%lu;%lum"
> ```

Sorry for commenting on a closed issue but this is the closest I found. These commands restore highlighting, but folded environments that would normally render with inverted text on termite are not rendered inverted in alacritty. Do you know how to fix this?

**Comment by madjxatw** [comment]
> Trying adding this to your vimrc.
> 
> ```
> let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
> let &t_8b = "\<Esc>[48:2;%lu;%lu;%lum"
> ```

It brings back the highlighting, but the colors are not correct.

**Comment by lmisea** [comment]
Hi, I wanted to contribute that this problem can be solved using the workaround described in: https://sw.kovidgoyal.net/kitty/faq/
It has a great explanation, but long story short, just add this to your _.vimrc_ file before setting the _colorscheme_:
```
" Mouse support
set mouse=a
set ttymouse=sgr
set balloonevalterm
" Styled and colored underline support
let &t_AU = "\e[58:5:%dm"
let &t_8u = "\e[58:2:%lu:%lu:%lum"
let &t_Us = "\e[4:2m"
let &t_Cs = "\e[4:3m"
let &t_ds = "\e[4:4m"
let &t_Ds = "\e[4:5m"
let &t_Ce = "\e[4:0m"
" Strikethrough
let &t_Ts = "\e[9m"
let &t_Te = "\e[29m"
" Truecolor support
let &t_8f = "\e[38:2:%lu:%lu:%lum"
let &t_8b = "\e[48:2:%lu:%lu:%lum"
let &t_RF = "\e]10;?\e\\"
let &t_RB = "\e]11;?\e\\"
" Bracketed paste
let &t_BE = "\e[?2004h"
let &t_BD = "\e[?2004l"
let &t_PS = "\e[200~"
let &t_PE = "\e[201~"
" Cursor control
let &t_RC = "\e[?12$p"
let &t_SH = "\e[%d q"
let &t_RS = "\eP$q q\e\\"
let &t_SI = "\e[5 q"
let &t_SR = "\e[3 q"
let &t_EI = "\e[1 q"
let &t_VS = "\e[?12l"
" Focus tracking
let &t_fe = "\e[?1004h"
let &t_fd = "\e[?1004l"
execute "set <FocusGained>=\<Esc>[I"
execute "set <FocusLost>=\<Esc>[O"
" Window title
let &t_ST = "\e[22;2t"
let &t_RT = "\e[23;2t"

" vim hardcodes background color erase even if the terminfo file does
" not contain bce. This causes incorrect background rendering when
" using a color theme with a background color in terminals such as
" kitty that do not support background color erase.
let &t_ut=''
```

Again, for better explanations, visit the link at the top of my comment.
It worked for me. Hope it helps.
