### ISSUE TITLE
Rework default bright colors

### ISSUE THREAD

**Issue by chrisduerr** [alacritty/alacritty#3404]
The default bright colors are often indistinguishable from the normal colors. This impacts the functionality of the default configuration file, which should achieve to provide sensible defaults that are usable out of the box for most people.

Since colors are highly subjective, I'd propose that the best approach to take is to imitate the current behavior of the dim colors, by taking the normal colors and changing their brightness by a fixed amount.

By default we use a factor of `0.66` for the dim colors, so a good place to start would probably be to use `1.34`. If that doesn't provide sufficient contrast, increasing that factor would be an option. Using completely different colors however wouldn't be ideal, since that is likely too subjective to get any consensus.

**Comment by Aelnor** [comment]
Hello,

I'd like to take this one. 
If something goes wrong and there's no news from me after a week, feel free to reassign.
