### ISSUE TITLE
Transparency of Vim

### ISSUE THREAD

**Issue by yanzhang0219** [alacritty/alacritty#3418]
Through searching the previous issues about the disappearance of transparency when entering vim, so far I know that the solution is adding "hi Normal guibg=NONE ctermbg=NONE" in the vimrc. **I am wondering whether there is a more decent solution for that?** 

If we make vim transparent via "hi Normal guibg=NONE ctermbg=NONE", we have to make sure that the color scheme of the terminal should the same with the color scheme of vim so that vim will use the background-color of the terminal. The drawback of setting "hi Normal guibg=NONE ctermbg=NONE" is that if we want to use a different color scheme in the terminal, say dracula for the termianl and gruvbox for vim, then when we enter vim, the background of vim will be dracula, which is not desirable. 

In other terminal emulators, for example iTerm2 or kitty, I do not have to set "hi Normal guibg=NONE ctermbg=NONE" in vimrc to get the transparency. So I can use a different color scheme in the terminal, that is, if I set dracula for iTerm2 and gruvbox for vim, then when I enter vim, the background color is still gruvbox and meanwhile the transparency is valid as well. 

Thank you!!!

**Comment by kchibisov** [comment]
>In other terminal emulators, for example  kitty,

This isn't true afaics for me and it behaves the exact same way as alacritty.

>I do not have to set "hi Normal guibg=NONE ctermbg=NONE" in vimrc to get the transparency. So I can use a different color scheme in the terminal, that is, if I set dracula for iTerm2 and gruvbox for vim, then when I enter vim, the background color is still gruvbox and meanwhile the transparency is valid as well.

Are you sure that truecolor is in use in both terminal emulators you've mentioned, vim restricts truecolor by default and could fallback to something different? In theory you can just change background color of a terminal each time you open your vim with escape sequence(IIRC vim also can do that).

Anyway, we won't implement transparency for arbitrary cell backgrounds, since it'll break things in the end and is a hack that doesn't make any sense.

**Comment by yanzhang0219** [comment]
Thanks. 

> Are you sure that truecolor is in use in both terminal emulators you've mentioned

Yes. Both use the same vimrc where I set truecolor by `set termguicolors`. And I attached a screenshot of iTerm2. I set the terminal color to Solarized Dark (tell from the title bar) and vim color Gruvbox, and I do not set "hi Normal guibg=NONE ctermbg=NONE" in my vimrc. You can see that the transparency is still there.

<img width="951" alt="Screen Shot 2020-03-04 at 12 52 20 AM" src="https://user-images.githubusercontent.com/11582667/75862020-16b96780-5db3-11ea-9083-5bbc66bfd00a.png">

Thank you.

**Comment by kchibisov** [comment]
It seems like iterm2 sets opacity for the entire content, which is strange, but understandable. As you can see all elements are transparent(look at cursor line), which isn't true if you try it in alacritty.

**Comment by stevensonmt** [comment]
I just uncovered the same issue after upgrading. If I `set termguicolors` then I have a transparent background but no colors. If I do not `set termguicolors` then I have the selected colorscheme but an opaque background. Alacritty is configured to have a transparent background, which works as expected. Is there a technical reason that vim behaves inconsistently with other terminal apps?
