### ISSUE TITLE
macOS troubleshooting fyi

### ISSUE THREAD

**Issue by jstrong-tios** [alacritty/alacritty#3422]
# System

OS: macOS
Version: alacritty 0.4.2-dev (33cabfc)

I had some trouble fixing the hidden window problem on macOS because there were two alacritty binaries in my /Applications folder. I'm not sure if I did something wrong or the installation instructions changed between versions, I've been running master for six months or so, updating once in a while. It was tricky to diagnose because it's not obvious how to check which version of alacritty you are currently "in" if you click the icon to launch it. For people who are upgrading to fix the hidden window bug, this is just an fyi to aid in potential troubleshooting. I think the "stale" binary was in /Applications/Contents -- again that may have just been my mistake to have put it there, no idea.

Thanks for your work on this great program!

**Comment by kchibisov** [comment]
closing, since it's not an issue?

**Comment by kchibisov** [comment]
Also, we haven't changed anything in our installation process on macOS for a long time IIRC, so likely it was some issue on your end.

**Comment by jstrong-tios** [comment]
definitely free to close - just trying to be helpful as I saw there were several dup issues about the hidden window thing. thanks!
