### ISSUE TITLE
Confirm exit prompt?

### ISSUE THREAD

**Issue by dan-cooke** [alacritty/alacritty#3426]
Is it possible we could have a prompt to confirm if the user actually wanted to exit the terminal?

Just completely screwed my shell because i accidentally quit Alacritty with CMD + W during a docker build instead of my chrome tab.

Now some of my homebrew packages have their permissions screwed.

**Comment by nixpulvis** [comment]
I could see this being a nice feature. I'd go so far as to say it should be enabled by default on macOS and Windows. If my memory serves, Terminal.app will only prompt you if a program is running. I'm not 100% sure how that all works off hand. As for Linux, I personally am pretty happy with the current behavior, since my WM makes it pretty easy to know what I'm about to quit.

**Comment by dan-cooke** [comment]
I would agree with you that it should be default behaviour. ITerm2 has a similar prompt when you have an active command running.

**Comment by chrisduerr** [comment]
> I could see this being a nice feature. I'd go so far as to say it should be enabled by default on macOS and Windows.

I **strongly** disagree.

> Just completely screwed my shell because i accidentally quit Alacritty with CMD + W during a docker build instead of my chrome tab.
>
> Now some of my homebrew packages have their permissions screwed.

If you use shitty software that doesn't properly handle getting killed unexpectedly, there's nothing Alacritty can do against that. There are a lot of different ways you can shoot down processes while they're in the middle of doing their thing and at no point should they leave your system in a state that isn't trivial to recover from.

If you see yourself constantly closing your terminals accidentally, just unmap the binding? If you want a binding that just quits Alacritty if nothing is running, there's always Ctrl+D.

**Comment by nixpulvis** [comment]
@chrisduerr just because we use Linux shouldn't mean we don't respect some conventions from other environments when useful. Sadly there exists a lot of software (including scripts being developed) which aren't built to handle being killed properly. 

Why **strongly** disagree? It seems like a perfectly reasonable feature to me, although I wouldn't expect anyone to rush to implement it. Or are you just against it being a default?

**Comment by chrisduerr** [comment]
> @chrisduerr just because we use Linux shouldn't mean we don't respect some conventions from other environments when useful.

I use macOS at work. And asking user to confirm before closing the terminal is not useful at all.

> Sadly there exists a lot of software (including scripts being developed) which aren't built to handle being killed properly.

And that's not our job to fix.

> Why strongly disagree? It seems like a perfectly reasonable feature to me, although I wouldn't expect anyone to rush to implement it. Or are you just against it being a default?

I'm strongly against it being default on any platform, yeah. I'm just slightly against the issue in general because it serves no purpose and is difficult to properly separate from the more useful `--hold` flag.

**Comment by nixpulvis** [comment]
> And asking user to confirm before closing the terminal is not useful at all.

You should try out Terminal.app with and without `yes` running to see how it performs. If my memory serves, it should only prompt you when it's running. I've found this very useful in the past personally.

**Comment by chrisduerr** [comment]
> You should try out Terminal.app with and without yes running to see how it performs. If my memory serves, it should only prompt you when it's running. I've found this very useful in the past personally.

I've tried it the other day for the `who` issue and was immediately annoyed that it didn't close immediately, even with nothing running at all. So that's not true.

**Comment by kchibisov** [comment]
I agree with @chrisduerr here. I hate when some app asks me to confirm exit. If you really don't want to lose something and keep things then around use `tmux`/`screen`, but software should be capable to exit gracefully in general.

**Comment by chmanie** [comment]
@chrisduerr and @kchibisov I see all your points but somehow I accidentally closed alacritty a couple of times now (it is even worse, sometimes macOS seems to hang onto the cmd key and I just have to press "w" (word in vim) to shut everything down. This is extremely frustrating and I currently can't see a way to prevent this right now. Does anyone have a workaround without adding this feature? Disabling cmd+w (and/or cmd+q) would be totally acceptable for me if that is just for alacritty.

**Comment by kchibisov** [comment]
you're likely describing #3188 , which should be fixed on `v0.4.2`. Anyway, you can unbind `Cmd + q`/`Cmd + w` by using `None` in `key_bindings:` section.

```yaml
   - { key: Q,      mods: Command,            action: None             }
   - { key: W,      mods: Command,            action: None             }
```

**Comment by chmanie** [comment]
Oh, wow, cool, thanks! I didn't even know this was an issue (and that it is already solved!).
Thanks for the key bindings as well, I'll apply those changes

**Comment by chrisduerr** [comment]
If closing a terminal is the end of the world, users should probably make use of tools like session managers.

Having some confirmation to make sure the user is actually trying to close the window after explicitly requesting to do so makes little sense to me. So I don't think it's worth it to waste implementation time on adding this behind a configuration option.

**Comment by MattyRad** [comment]
I wasn't aware of Ctrl+D, that's a good tip. If anyone prefers Ctrl+W over Ctrl+D, you can add `stty eof ^W` (or whatever `stty -a` says your eof/eot is mapped to) in your `.(ba/z)shrc`.

> Disclaimer: I've only tested this on linux/zsh, ymmv

**Comment by elcste** [comment]
@MattyRad 

You can also set Ctrl+W to send the same thing at Ctrl+D everywhere in Alacritty with

```
  - { key: W, mods: Control,                      chars: "\x04"            }
```

**Comment by Quicksilver151** [comment]
wait
alacritty doesnt have a confirm exit?
why????
i was just bout to switch from konsole to alacritty
:/

**Comment by utkarshgupta137** [comment]
> you're likely describing #3188 , which should be fixed on `v0.4.2`. Anyway, you can unbind `Cmd + q`/`Cmd + w` by using `None` in `key_bindings:` section.
> 
> ```yaml
>    - { key: Q,      mods: Command,            action: None             }
>    - { key: W,      mods: Command,            action: None             }
> ```

In addition to this, I had to remove it in System Settings as well: https://superuser.com/questions/222440/how-to-disable-command-q-for-terminal-on-osx

**Comment by blueray453** [comment]
> you're likely describing #3188 , which should be fixed on `v0.4.2`. Anyway, you can unbind `Cmd + q`/`Cmd + w` by using `None` in `key_bindings:` section.
> 
> ```yaml
>    - { key: Q,      mods: Command,            action: None             }
>    - { key: W,      mods: Command,            action: None             }
> ```

If there was an action that would ask whether I want to close then I might add it to the keybinding.

 ```yaml
    - { key: W,      mods: Command,            action: PromptToCloseWindow             }
 ```

There is a solution though using tmux. https://github.com/alacritty/alacritty/issues/6886#issuecomment-1523327197

**Comment by blueray453** [comment]
fun exercise.

Dependencies: zenity and xdotool

Set the following is `alacritty.yml`:

    - { key: W,      mods: Command,            action: None             }

**For Fish Shell:**

Make an autoload function like bellow:

```
function _ctrl_w
    set -l current_window (xdotool getactivewindow)
    zenity --warning --text="Do you want to close the window?"
    if test $status -eq 0
        xdotool windowkill $current_window
    end
end
```
Bind it to <kbd>ctrl+w</kbd> using `bind \cw _ctrl_w`

If you want to use rofi instead of zenity then the function will look like:

```
function _ctrl_w
    set -l dmenu_list OK
    set -l selection (printf '%s\n' $dmenu_list | rofi -dmenu -p "Do you want to close the current window")
    if test $status -eq 0
        xdotool windowkill (xdotool getactivewindow)
    end
end
```

**For ZSH Shell:**

Make an zle like bellow:

```
_ctrl-w() {
    current_window=$(xdotool getactivewindow)
    zenity --warning --text="Do you want to close the window?"
    if [ $? -eq 0 ]; then
        xdotool windowkill $current_window
    fi
}

zle -N _ctrl-w
bindkey '^W' _ctrl-w
```
ZSH one is not tested by hopefully will work.

**Comment by saikyun** [comment]
Thank you chris for the Ctrl+D suggestion, I think that's a very clean solution. I agree that software asking you to confirm is annoying, so separating "close disregarding everything" and "close only if nothing is running" is perfect. :D
