### ISSUE TITLE
[possible feature request?] Jump between prompts

### ISSUE THREAD

**Issue by SRGOM** [alacritty/alacritty#3428]
Not sure if it's even possible but I find a feature on Twitter that changed my life (in my dreams..) https://mobile.twitter.com/mdiep/status/1235946058745671683

Jump between prompts. You can even select apparently. Please click the link- a video explains better....

**Comment by chrisduerr** [comment]
Alacritty has no interest to implement non-standard hacks that require direct shell integration to function.

If someone wants to use this, they should first look to standardize the escape and then Alacritty can implement it. Until there is a standard way to do this, Alacritty cannot implement it.

**Comment by SRGOM** [comment]
Thank you. I'd rather not have a feature than further mess up features. 

Which makes me wonder- is vim mode and search coming? I could do a search for prompt specific emoji...

Chris i also want to thank you for doing all this work for free. Alacritty is an absolute game changer for productivity. (The only downside being that I now misspell alacrity in real life)

**Comment by chrisduerr** [comment]
> Which makes me wonder- is vim mode and search coming? I could do a search for prompt specific emoji...

Yes: https://github.com/alacritty/alacritty/pull/3315.
