### ISSUE TITLE
Text scrambling in prompt

### ISSUE THREAD

**Issue by Cygnusfear** [alacritty/alacritty#3433]
### System

OS: macOS
Version: alacritty 0.4.0 (b115b90)

### Issue 
Alacritty has a tendency to scramble text in the prompt. Often occurs when pasting in text. I can also reproduce this by using tab to autocomplete. It also occurs in ZSH (I'm using Fish).

<img width="441" alt="Screenshot 2020-03-08 at 22 05 03" src="https://user-images.githubusercontent.com/2925132/76171220-1b9e6280-6189-11ea-9b8d-6d6a89471d33.png">
<img width="288" alt="Screenshot 2020-03-08 at 22 05 07" src="https://user-images.githubusercontent.com/2925132/76171221-1d682600-6189-11ea-82a8-6c623f332fbe.png">
<img width="391" alt="Screenshot 2020-03-08 at 21 59 08" src="https://user-images.githubusercontent.com/2925132/76171223-222cda00-6189-11ea-8fd1-f504ef40a3ad.png">

**Comment by kchibisov** [comment]
what's the `tabspaces` value in your config?

**Comment by Cygnusfear** [comment]
`#tabspaces: 8` 👀

**Comment by chrisduerr** [comment]
If you set your prompt to not contain the `>`, does that fix it? I'd assume it does?

**Comment by kchibisov** [comment]
what's your `locale`?

**Comment by Cygnusfear** [comment]
>If you set your prompt to not contain the >, does that fix it? I'd assume it does?
<img width="138" alt="Screenshot 2020-03-08 at 22 31 34" src="https://user-images.githubusercontent.com/2925132/76171511-97e67500-618c-11ea-933b-38d6156322d3.png"> alas no
 
>what's your locale?
`LANG=""
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=`

Yeah, that was buggered! Fixed it by exporting the correct locale (used this as reference: https://stackoverflow.com/a/8161863)

Cheers and thanks for the amazing terminal 🥇
