### ISSUE TITLE
Alacritty window seems misplaced and with curious sizing/prompt placement on latest Gnome

### ISSUE THREAD

**Issue by Porkepix** [alacritty/alacritty#3434]
### System

OS: Linux - ArchLinux
Version: `alacritty 0.4.2-dev (64a31156)` (latest master as of the writing of this issue)
Linux/BSD: Wayland, Gnome (latest release)

### Issue
Since latest Gnome release - and few latest alacritty commits, but I would bet on an issue triggered by latest Gnome updates - the window, that was opened maximized as requested by the configuration file, now let an invisible strip at the bottom of the screen, as visible on joined screenshot
![Screenshot from 2020-03-09 11-24-58](https://user-images.githubusercontent.com/709500/76204554-e3366d00-61f8-11ea-9048-8a7c080d662d.png)

Looking like this, it lets just think the window is incorrectly sized, but the bottom border user can grab to resize the window is at the middle of this empty/invisible space, which means part of it belong to alacritty's window, although invisible.

When taking a screenshot of only alacritty's window (alt + PrntScreen), we can also see that although the prompt looks close to the window titlebar, there's a hidden terminal space going from the prompt to the top of the screen, with a height of both titlebar + Gnome's top bar cumulated. See the following screenshot. On top of that, trying to click to resize on the bottom… fill the invisible space directly and makes the windows really maximized, preventing user from doing any resize.
![Screenshot from 2020-03-09 10-58-32](https://user-images.githubusercontent.com/709500/76204868-77a0cf80-61f9-11ea-9cb2-180e4269b17a.png)

These issues seems quite close to the issue I reported back then in #3146.

Last problem, which might be unrelated and need another issue although I'm unsure about that: titlebar's buttons are not highlighted anymore only if cursor comes from above (the Gnome bar). If coming from the terminal space, it's correctly highlighted.

### Logs

Font/Terminal size: `alacritty -vv`
```
[2020-03-09 11:23:19.216733247] [INFO] Welcome to Alacritty
[2020-03-09 11:23:19.216834993] [INFO] Configuration loaded from "/home/clement/.config/alacritty/alacritty.yml"
[2020-03-09 11:23:19.238343384] [DEBUG] Estimated DPR: 1
[2020-03-09 11:23:19.238590302] [DEBUG] Estimated Cell Size: 6 x 12
[2020-03-09 11:23:19.238765398] [DEBUG] Estimated Dimensions: None
[2020-03-09 11:23:19.313642039] [INFO] Device pixel ratio: 1
[2020-03-09 11:23:19.320596677] [INFO] Initializing glyph cache...
[2020-03-09 11:23:19.376868782] [INFO] ... finished initializing glyph cache in 0.056238897s
[2020-03-09 11:23:19.376930357] [INFO] Cell Size: 6 x 12
[2020-03-09 11:23:19.376948730] [INFO] Padding: 0 x 0
[2020-03-09 11:23:19.376971151] [INFO] Width: 800, Height: 600
[2020-03-09 11:23:19.379008001] [INFO] PTY Dimensions: Line(50) x Column(133)
[2020-03-09 11:23:19.380795863] [INFO] Initialisation complete
[2020-03-09 11:23:19.408330093] [DEBUG] New num_cols is 320 and num_lines is 85
[2020-03-09 11:23:19.411838635] [INFO] Width: 1920, Height: 1023
[2020-03-09 11:23:19.549431858] [DEBUG] New num_cols is 320 and num_lines is 82
[2020-03-09 11:23:19.549695709] [INFO] Width: 1920, Height: 993
[2020-03-09 11:23:21.634762627] [INFO] Goodbye
```

**Comment by kchibisov** [comment]
We haven't changed anything related to Wayland for a while. It seems like a GNOME bug to me tbh. GNOME 3.34.4 seems to work fine for me with alacritty. Old issue also wasn't our bug tbh, since GNOME relied on some strange behavior and can't work with our decorations setup properly.

**Comment by Porkepix** [comment]
I see you added the "needs repro" tag; what kind of additional information would you need?
Is there some other software you know about that manage decorations the same way as Alacritty to do similar tests?

**Comment by kchibisov** [comment]
I'm not aware of any, but alacritty is doing valid things with its decorations(and we haven't changed them for a long long time). And there's nothing we can fix, it should be fixed in GNOME, changing how our decorations work isn't really an option.

**Comment by dnkl** [comment]
I have written a Wayland client that I believe uses the same technique to implement CSDs. It behaves in exactly the same way (unoccupied space at the bottom), when configured to start maximized.

I didn't check how it behaves under older GNOME releases.

From a brief look at the series of 'configure' events that happens, I'd say @kchibisov is right - this is a GNOME bug.

That said, it might be interesting to see how it behaves under Weston?

**Comment by dnkl** [comment]
> That said, it might be interesting to see how it behaves under Weston?

I just tested my client; it works under Weston.

**Comment by kchibisov** [comment]
alacritty also seems to work fine on weston afaics.

**Comment by kchibisov** [comment]
>I have written a Wayland client that I believe uses the same technique to implement CSDs. It behaves in exactly the same way (unoccupied space at the bottom), when configured to start maximized.

Oh, @dnkl do you update `set_geometry` after each resize even for the exact same size? GNOME speculates on it so you should call it quite often to make thing work :p .

Anyway I'll close this issue and encourage to bring it to GNOME somehow. using some simple testing client should be better for GNOME folks to debug things.

**Comment by dnkl** [comment]
> Oh, @dnkl do you update set_geometry after each resize even for the exact same size? GNOME speculates on it so you should call it quite often to make thing work :p .

I only call it only when the size has changed. Thanks for the tip! Why am I not surprised... :roll_eyes:

**Comment by kchibisov** [comment]
Yeah, I've already have a workaround and a comment for it in winit https://github.com/rust-windowing/winit/blob/e85a80dd65945bebc22c19736b92713ffc20c06d/src/platform_impl/linux/wayland/event_loop.rs#L728
