### ISSUE TITLE
Feature request: Configurable application icon

### ISSUE THREAD

**Issue by myelsukov** [alacritty/alacritty#3439]
I am a heavy command line user. I often have several different applications running in several terminal windows. For the ease of navigation I would like those windows to have different icons.
Many terminal emulators provide command line options/configuration parameters for that.
For example:
xfce4-terminal: `--icon=<icon file name>`
urxvt: `-icon <icon file name>`, etc.

Right now I have to use [xseticon](http://www.leonerd.org.uk/code/xseticon/) command line utility to set different icons to the different Alacritty windows.

Could you please consider adding command line option and/or configuration parameter allowing to change Alacritty application icon?

**Comment by kchibisov** [comment]
I wonder whether using `--class` with an icon name of a desktop file could solve your issue?

Does `alacritty --class htop` works, assuming you have `htop`?

**Comment by myelsukov** [comment]
a) My Windows Manager does not support `.desktop` files :) 
b) In any case I am starting my terminal windows from shell, not from menu/desktop/file manager

**Comment by chrisduerr** [comment]
I'm honestly not very fond of the idea, it seems like a very niche usecase that doesn't really provide much benefit.

Supporting the escape to set icon would also be an option, but I don't feel like anyone would actually use that either.

**Comment by kchibisov** [comment]
Hm, macOS argument makes sense. I'm not opposed to such option, since we already have a way to parse/load images. So it should be pretty simple to add this for macOS/Linux.

**Comment by myelsukov** [comment]
> ... it seems like a very niche usecase ...

While this may be true, but major terminal emulators: `xterm`, `urxvt`, `xfce4-terminal`, etc. provide this feature.

> ... that doesn't really provide much benefit ...

I personally have very different opinion ;)

**Comment by chrisduerr** [comment]
I'd like to go into a bit more detail of what would have to be done if we wanted to support changing the title at runtime.

If we support things as a CLI option, we also need to support it as a configuration option unless there's a good reason why it would only be supported from CLI. I don't think there's any good enough argument for the icon, so we'd have to allow configuration in the config too.

If configuration is possible in the configuration file, we have to add the ability to live update the icon with a config reload. So we need to implement the functionality to swap the icon while Alacritty is running.

If we support the option to swap out the icon live while Alacritty is running, we should also support the escape sequence which was introduced to control that. This allows saving/loading of the icon to a stack similar to the title and freely setting the icon to whatever value one might desire.

So there's a bit more to it than just adding a CLI flag. If we want to support this, we need to do it right and have proper handling for all these scenarios.

**Comment by myelsukov** [comment]
@chrisduerr All the cases mentioned by you look like calling `setIcon(iconPath)` method in different places. I wish I had Rust experience... May be it's time to learn it :)

> If we support the option to swap out the icon live while Alacritty is running, we should also support the escape sequence which was introduced to control that.

I do not see this as a requirement. :)

**Comment by myelsukov** [comment]
After some research I realized that Mac OS windows do not have icons, hence this feature can not be implemented. Given that I already can change icons of the windows dynamically in X11, I can close this issue unless somebody tells me that Mac OS implementation is also possible :)

**Comment by kchibisov** [comment]
how so, you can set icon on macOS, but it won't be in titlebar.

**Comment by myelsukov** [comment]
Mac OS icons are part of the application package, not part of the executable.
To change an icon, the icon file needs to be replaced in the `.app` directory.
The winit Window::set_window_icon() is a no-op.:
```
    pub fn set_window_icon(&self, _icon: Option<Icon>) {
        // macOS doesn't have window icons. Though, there is
        // `setRepresentedFilename`, but that's semantically distinct and should
        // only be used when the window is in some way representing a specific
        // file/directory. For instance, Terminal.app uses this for the CWD.
        // Anyway, that should eventually be implemented as
        // `WindowBuilderExt::with_represented_file` or something, and doesn't
        // have anything to do with `set_window_icon`.
        // https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/WinPanel/Tasks/SettingWindowTitle.html
    }
```

**Comment by kchibisov** [comment]
Oh, I completely forget that this thing was originally from Windows in alacritty codebase and not from macOS. Like historically one platform had with_window_icon, but I thought that it was macOS, since I was adding it on X11 back then. Turns our it was windows, so yeah, it won't work on macOS.

**Comment by kchibisov** [comment]
So this thing is only possible on X11 and Windows. On Wayland you don't have such thing in general and compositors are relying on `app_id`, on macOS it's also not a thing.

**Comment by myelsukov** [comment]
X11 is ugly but very powerful :)

**Comment by kchibisov** [comment]
I mean some X11 wms are relying on `class`(GNOME/KDE/Awesome) here, so it's the same as on Wayland. The only difference is dynamic icon change, which isn't possibile on Wayland at all. For example if I want to use neovim icon, I just launch `alacritty --class nvim` and get `neovim` icon, instead of our alacritty's.

**Comment by myelsukov** [comment]
I use [JWM](https://github.com/joewing/jwm) and this trick does not work for me.
The class is `htop` but the icon stays the same.
In any case, xseticon is more flexible. I can even generate icons on the fly using  ImageMagic :)

```
> xprop
WM_HINTS(WM_HINTS):
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_SHADE, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_MOVE, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_STICK, _NET_WM_ACTION_BELOW, _NET_WM_ACTION_ABOVE
_NET_FRAME_EXTENTS(CARDINAL) = 4, 4, 21, 4
_NET_WM_STATE(ATOM) = _NET_WM_STATE_FOCUSED
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_DESKTOP(CARDINAL) = 1
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING
_NET_WM_ICON(CARDINAL) =
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified size: 3380 by 1820
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
WM_CLIENT_MACHINE(STRING) = "Lenovo"
_NET_WM_PID(CARDINAL) = 31885
WM_CLASS(STRING) = "htop", "Alacritty"
XdndAware(ATOM) = BITMAP
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x1, 0x0, 0x0
_NET_WM_NAME(UTF8_STRING) = "[me@mybox] ~"
WM_NAME(STRING) = "[me@mybox] ~"
```

**Comment by chrisduerr** [comment]
Since there are third party tools for X11 and neither Wayland nor macOS support this, it probably makes sense to not introduce this complexity in Alacritty when it will not work on half the platforms Alacritty runs on.

It's also questionable if it would work on Windows, with its history of swallowing all our escape sequences.

**Comment by BatmanAoD** [comment]
Is there some way to at least provide a way for the `--class` argument to have an effect on Windows? I don't know how Windows determines what icon to use, but as far as I can tell, currently the `--class` argument does nothing on Windows.

**Comment by chrisduerr** [comment]
On Windows everything is baked in during compile-time. So that's where you'd have to change it.

**Comment by BatmanAoD** [comment]
It appears to be loaded and set dynamically, though: https://github.com/alacritty/alacritty/blob/81ce93574f62d4b117fdd79af65391f30316a457/alacritty/src/window.rs#L308

Surely the icon _could_ be loaded from elsewhere?

**Comment by chrisduerr** [comment]
It's from the resource file. Which you can adjust before installation.

**Comment by BatmanAoD** [comment]
So I would need to have three different installations for three different shells? That might be an acceptable solution, but what I'd like to know is, can the `icon` be constructed from some other source?

**Comment by BatmanAoD** [comment]
....with a code change, I mean, not with the existing code.

**Comment by BatmanAoD** [comment]
It looks like `glutin` does indeed provide a method to load an icon from a path: https://docs.rs/glutin/0.24.0/x86_64-pc-windows-msvc/glutin/platform/windows/trait.IconExtWindows.html#tymethod.from_path

Would you be open to a PR introducing a way to override the icon embedded in the resource file with one from a file path? If so, would you prefer this behavior to be configured via the `-class` option (since that otherwise won't do anything on Windows) or via a new configuration option?

**Comment by chrisduerr** [comment]
> Would you be open to a PR introducing a way to override the icon embedded in the resource file with one from a file path?

No.

There are also different types of icons, some of which can only be configured in the rc file.

**Comment by ifohancroft** [comment]
I would also like to request the ability to set the icon on Alacritty start, using something like --icon <icon name>. I just moved to Alacritty from Termite but not having this feature is a deal breaker for me.

**Comment by FinallyFinancialFreedom** [comment]
I browse all the posts above, Can I make a conclusion that in `alacritty 0.8.0 (a1b13e6)`, there isn't a way to specify a icon when i start alacritty from terminal? 
I have tried --class, and i get this.
![image](https://user-images.githubusercontent.com/2133400/120141304-d2638400-c20e-11eb-88d7-4294d094698b.png)

**Comment by nPHYN1T3** [comment]
This sucks this is another term that won't add such a useful feature. I have custom color coded icons for ssh sessions to certain machines and my WM matches the icon colors for easy visual identification. Plus it's just nice to be able to assign icons to tasks. The lame way would be xseticon against the window class but my panels (and alt tab) like to "forget" what xseticon assigns after a while. With the unwillingness to add such useful bits how long until we can't choose a color theme? I mean so I can add / change color themes but not icon? Seems a tad contradictory.

**Comment by Jimmy-Z** [comment]
I would also like this feature, but for a different and simpler reason: I don't like the default icon.
