### ISSUE TITLE
can't clear output, only in `ssh` sessions

### ISSUE THREAD

**Issue by ExpandingMan** [alacritty/alacritty#3443]
### System

OS: Manjaro Linux (ssh into Ubuntu 18.04)
Version: 0.4.1
Linux/BSD: X11 i3

I'm experiencing an extremely bizarre bug in which I can't clear output, only in `ssh` sessions.  For example, if I start typing and then hit backspace or `ctrl+u`, spaces will appear, but no text is ever cleared.  If I open nvim and exit, the entire screen remains.  I have checked and this problem *only* occurs in alacritty, not other terminals, and only since 0.4.1.  Any ideas?

**Comment by kchibisov** [comment]
could you try `env TERM=xterm-256color ssh remote@host`

**Comment by ExpandingMan** [comment]
That works, thanks!  How can I fix this permanently?

**Comment by ExpandingMan** [comment]
Btw, I just tried it on alacritty 0.4.0 for the hell of it and I get the same behavior.  It seems to be something else in my manjaro update that caused this, it seems unlikely that it's an alacritty issue.

A brief explanation so I could understand this in the future would be appreciated.  Thanks again!

**Comment by kchibisov** [comment]
Your remote server doesn't have `alacritty` terminfo, manjaro has `alacritty` terminfo, we pickup our `terminfo` on manjaro. you should likely do an `alias ssh='TERM=xterm256 color ssh`.

**Comment by ExpandingMan** [comment]
Got it, thanks for your help.
