### ISSUE TITLE
thread 'main' panicked at 'not yet implemented', /builddir/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.22.0-alpha5/src/api/egl/mod.rs:1180:35

### ISSUE THREAD

**Issue by blubber** [alacritty/alacritty#3451]
### System

OS: Fedora Linux 31 SilverBlue
Version: 0.4.1
Linux/BSD: xorg using nvidia binary drivers

### Logs
```$ RUST_BACKTRACE=full alacritty
xkbcommon: ERROR: Key "<CAPS>" added to modifier map for multiple modifiers; Using Control, ignoring Lock
thread 'main' panicked at 'not yet implemented', /builddir/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.22.0-alpha5/src/api/egl/mod.rs:1180:35
stack backtrace:
   0:     0x55bdefd2619c - <unknown>
   1:     0x55bdefbe73cc - <unknown>
   2:     0x55bdefd25866 - <unknown>
   3:     0x55bdefd2541e - <unknown>
   4:     0x55bdefd24bc3 - <unknown>
   5:     0x55bdefa25064 - <unknown>
   6:     0x55bdefb03437 - <unknown>
   7:     0x55bdefb3c59d - <unknown>
   8:     0x55bdefb3917a - <unknown>
   9:     0x55bdefac96d2 - <unknown>
  10:     0x55bdefa00a67 - <unknown>
  11:     0x55bdefb510c3 - <unknown>
  12:     0x55bdef9fb95e - <unknown>
  13:     0x7fee354731a3 - __libc_start_main
  14:     0x55bdef9b722e - <unknown>
  15:                0x0 - <unknown>
```

I'm no Rust expert, but this doesn't look like a particularly helpful stacktrace.

This is running with the default (no) configuration. It crashes immediately on startup, but `--version` works ok.

**Comment by chrisduerr** [comment]
Which GPU are you running? Seems like it might not support OpenGL?

**Comment by blubber** [comment]
It's an nVidia GTX670 which definitely supports opengl.

**Comment by blubber** [comment]
Interesting, because you asked about the GPU I tried to open `nvidia-settings`, which refused to start. Googling the error it threw lead me to the suggestion that the nvidia driver doesn't support Wayland. I thought I was using xorg because of this, however, apparently due to some update my intall reverted back to it's default behavior, which is to use Wayland.

I'm now using Xorg again, and Alacritty works fine.
