### ISSUE TITLE
Enhancement/Feature Request: xterm-alacritty as TERM variable

### ISSUE THREAD

**Issue by CobaltSpace** [alacritty/alacritty#3453]
Many programs don't display the same way when `TERM`=`alacritty`.  They act as though they are piping in to something or are being called by another program.  But they do understand `xterm` and `xterm-[whatever]`.  So my suggestion is to change `TERM` to be `xterm-alacritty`, or have that as an option.

### System

OS: Arch Linux
Version: 0.4.1
Linux/BSD: X11, picomp and bspwm

**Comment by kchibisov** [comment]
we're not xterm, so fix the programs, and don't workaround the more important issue.

**Comment by kchibisov** [comment]
Note, if you want your terminfo to do be called like that, you're free to change its name during compilation, but then you should manually set it in your config.

**Comment by craigbarnes** [comment]
From the `terminfo(5)` man page (emphasis mine):

> The particular piece of hardware making up the terminal should have a root name, thus “hp2621”. This name should **not** contain hyphens. Modes that the hardware can be in, or user preferences, should be indicated by appending a hyphen and a mode suffix.  Thus, a vt100 in 132-column mode would be vt100-w.

Some apps actually use this naming convention to to detect the terminal root name and additional modes. Putting a hyphen in the root name goes directly against this decades-old convention. The fact that `kitty` and `termite` both do it is incredibly dumb.

Forgive me for ranting, but I hope people take note of this before more terminals repeat the same mistake.
