### ISSUE TITLE
SSH to Raspberry PI, unknown terminal

### ISSUE THREAD

**Issue by peperami97** [alacritty/alacritty#3454]
Hi

Using alacritty on Manjaro, when I connect to my raspberry pi running raspian I get an unknown terminal error when connecting via ssh. 

If I use a different terminal to do the same thing it works fine.

Ben

**Comment by chrisduerr** [comment]
The terminfo you use on your main machine doesn't exist on the raspberry pi.

This likely means that you should install the `alacritty` terminfo on it, since your terminfo on your main machine is hopefully `alacritty`.
