### ISSUE TITLE
WindowEvent missing virtual keycode on Linux

### ISSUE THREAD

**Issue by wild-endeavor** [alacritty/alacritty#3460]
I have the following mapping in my config:

```
  - { key: Minus,      mods: Control|Shift, chars: "hi"    }
```

The "hi" text is meant to represent something else, but just using that as an easy placeholder.  tmux is not running.

Just upgraded but the same thing happened in 0.4.1.  On my Mac, when I hit Ctrl+Shift+-, it prints "hi" as expected.  On my linux box (details below), nothing happens.  A `print-events` log is attached.  I basically just launched alacritty, hit Ctrl+Shift+- and then Alt+F4.  It looks like the character that's received is `\u{1f}` for some reason.

Based on the log output, I then tried changing the config to use the word `Subtract` instead of `Minus` but still nothing happens.

I feel like this is just something I'm doing wrong, not a bug or anything, but I have no idea what it is.  

Thank you!

### System

OS: Linux - Ubuntu 19.10
Version: `alacritty --version` output
  `alacritty 0.4.2-rc1`
Linux/BSD: X11/Wayland (default Gnome installation that comes with ubuntu)

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`
[output.txt](https://github.com/alacritty/alacritty/files/4333216/output.txt)

**Comment by kchibisov** [comment]
Could you provide `alacritty --print-events` while you're reproducing this issue and not `strace` mixed output, thanks.

**Comment by wild-endeavor** [comment]
Yes, of course.  How do I do that?  The command I'm running right now is `alacritty --print-events | tee output.txt`.

**Comment by kchibisov** [comment]
Just do `alacritty --print-events > out.txt` and the txt file here, don't forget to repro your issue during it.

**Comment by wild-endeavor** [comment]
[out.txt](https://github.com/alacritty/alacritty/files/4333326/out.txt)
Done.

**Comment by kchibisov** [comment]
Seems like `Shift + Minus` doesn't work, however `Control + Minus` works. The problem is that we don't get a virtual key code from https://github.com/rust-windowing/winit , so bindings is failing. This issue is true for both X11 and Wayland AFAICS.  The `\u{1f}` is a correct value btw, so the problem is virtual key code. I'd recommend to bind by scancode on Linux for now(12 in your case).

```
- { key: 12,     mods: Control|Shift, chars "hi"           }
```

**Comment by kchibisov** [comment]
This is likely related to rust-windowing/winit#1443 , but I'm not sure, since we have Wayland here.

cc @chrisduerr .

**Comment by wild-endeavor** [comment]
Just to be sure, I tried again with an almost empty config.  The only thing in the file is.
```
key_bindings:
  - { key: Backslash,  mods: Control|Shift, chars: "\x00|"    }
  - { key: Minus,      mods: Control|Shift, chars: "hi"    }
```
and still had the same problem.  Also, I don't know if this helps at all, but pressing Ctrl+Shift+-
```
$ showkey -a

Press any keys - Ctrl-D will terminate this program

^_ 	 31 0037 0x1f
```
though I assume that's pretty normal.

**Comment by kchibisov** [comment]
As I said, `Control + Shift + Minus` doesn't have virtual key code, so the only option is to bind by scancode, as I said before. I can repro this bug on my system with both backends.

**Comment by chrisduerr** [comment]
Yeah, this is identical to the X11 winit issue. The `DeviceEvent` contains a key but the `WindowEvent` does not.

**Comment by wild-endeavor** [comment]
Oh sorry, sorry. Didn't see that.  Thank you!!
