### ISSUE TITLE
Clipboard not working on vim

### ISSUE THREAD

**Issue by doragasu** [alacritty/alacritty#3468]
OS: ArchLinux, Wayland (sway WM)
Version: 0.4.1

Issue:
When I run vim under e.g. `urxvt`, I can yank text using `"+y` or `"*y` to then paste the text on other application using `[CTRL]+V` or middle mouse button respectively. But this does not work on Alacritty, the previous contents of the clipboard are not replaced by vim commands above.

Maybe this is not an Alacritty issue but a Wayland issue, but I cannot find how to solve this problem.

**Comment by kchibisov** [comment]
are you sure that your vim is using `OSC 52` escape sequence to set a clipboard contents?

**Comment by kchibisov** [comment]
Oh, vim doesn't have `OSC 52` at all, so alacritty can't do anything here and you need special tools to make it work on wayland, like https://github.com/bugaevc/wl-clipboard or https://github.com/YaLTeR/wl-clipboard-rs

**Comment by doragasu** [comment]
That's unfortunate, it does not seem wl-clipboard or wl-clipboard-rs will be helpful inside vim.
Maybe it's time to switch to Neovim. Thanks a lot for the prompt response, since this is not an Alacritty issue, I'm closing this.

**Comment by kchibisov** [comment]
Can't you setup clipboard provider inside vim? `wl-clipboard` should work the way `xclip` works, maybe you can just define your clipboard with it.

**Comment by doragasu** [comment]
Thanks for suggestion. Y have tried:

`:'<,'>w !wl-copy`

But it copies a whole line instead of selected text. Then I have tried yanking text (with `y`) and then ran command:

`:call system('wl-copy', @0)`

And that did the trick! Now I have just to remap the command.

Thanks!!!
