### ISSUE TITLE
alacritty makes lots of prompts when resizing and using zsh

### ISSUE THREAD

**Issue by smhsketch** [alacritty/alacritty#3469]
### System

OS: Linux
Version: 0.4.1
Arch linux, X11, i3wm, picom compositor

Alacritty, when paired with zsh, causes lots of new prompts to be made whenever the window is resized. 

This is what my terminal looks like after I adjust the size a few times.

![Kazam_screenshot_00005](https://user-images.githubusercontent.com/38465129/76778090-3ff4d300-6777-11ea-9fca-7a3b6b9ac4f4.png)

**Comment by chrisduerr** [comment]
That's simply a side-effect of how resizing works in a terminal, since applications themselves do not have any knowledge of reflow and thus the prompt redraws itself, causing duplicates to appear.

I'm not aware of any terminal emulator that supports reflow where this doesn't happen. However, without a prompt at the right side of your screen it is much less likely to happen, since this only happens when the window size is smaller than the prompt.

**Comment by nixpulvis** [comment]
@chrisduerr kitty doesn't seem to have this issue. Termite doesn't seem to have this issue (although it has a slightly less bad different issue). And if my memory serves me, neither Terminal.app, nor iTerm.app had this issue.

When I brought this up, frankly I got irritated trying to argue about it with you, and I was unsuccessful finding the issue myself, so that's where I stand here.

Sorry I can't be more helpful at the moment.

**Comment by smhsketch** [comment]
To test this, I just opened a workspace and ran alacritty, xterm, kitty, and urxvt all at once, all running zsh. When I resized them, the only terminal that had this issue with multiple prompts was alacritty. Seems to be an issue with alacritty...

**Comment by chrisduerr** [comment]
> kitty doesn't seem to have this issue

It does.

> Termite doesn't seem to have this issue

It does.

> And if my memory serves me, neither Terminal.app, nor iTerm.app had this issue.

I've not tested any of those two applications, but I'd be very surprised if they didn't have this issue in some way shape or form.

I've tested all major terminal emulators on Linux when developing this feature and all of them had the same issue.

**Comment by nixpulvis** [comment]
@chrisduerr how can you so confidently state this, when the evidence is so clearly against you? I worry only about effecting your mood here, but am commenting because I'm genuinely confused. A better version of myself would have already tracked down the problem, but alas.

**Comment by cole-h** [comment]
I just did some testing of my own. While that may not have been the case in the past, `kitty` no longer exhibits this issue. See the following sequences of pictures. Hardly scientific, but I believe exemplifies the issue at hand.

### `kitty`

1. ![image](https://user-images.githubusercontent.com/28582702/76801417-df738f00-6792-11ea-9c36-43144f923a19.png)
2. ![image](https://user-images.githubusercontent.com/28582702/76801458-f74b1300-6792-11ea-9f9e-a73141a03074.png)
3. ![image](https://user-images.githubusercontent.com/28582702/76801478-ff0ab780-6792-11ea-8723-3f4c276c984f.png)

### `alacritty`

1. ![image](https://user-images.githubusercontent.com/28582702/76801529-177ad200-6793-11ea-9041-33fa91751c7d.png)
2. ![image](https://user-images.githubusercontent.com/28582702/76801535-1a75c280-6793-11ea-8749-36b6122cf7b9.png)
3. ![image](https://user-images.githubusercontent.com/28582702/76801547-1f3a7680-6793-11ea-8e8a-4e222651a676.png)

**Comment by kchibisov** [comment]
It seems like kitty is delaying resize for a bit,  like for 2 seconds, however I can still break it.

![picture](https://user-images.githubusercontent.com/27620401/76802243-54bd7f00-67e8-11ea-91e6-565578d2733a.png)

**Comment by kchibisov** [comment]
And this is urxvt
![picture](https://user-images.githubusercontent.com/27620401/76802311-7dde0f80-67e8-11ea-8afb-ad794a354a5b.png)

**Comment by nixpulvis** [comment]
@chrisduerr the way we currently behave surely cannot be the most graceful thing we can imagine tho? Shouldn't we have an open issue to track a reasonable solution to this problem?

@kchibisov I'm curious how you managed that... honestly. In my limited testing it never happens.

**Comment by chrisduerr** [comment]
> the way we currently behave surely cannot be the most graceful thing we can imagine tho?

It's exactly how we should behave as far as I'm concerned, it's the only reliable solution that makes sense with how terminal emulators work. You can disable reflow, but you can't (easily) just change how terminals work.

**Comment by kchibisov** [comment]
@nixpulvis Just speculate that terminal delays your resize and do some stupid resizes, so it'll blow up.

**Comment by nixpulvis** [comment]
OK, I'll try and give this more thought...

**Comment by smhsketch** [comment]
I was able to stop the problem from happening by removing the timestamp on the side, but i'd still like to know why only alacritty has this problem when the right prompt is on

**Comment by kchibisov** [comment]
Prompt is trying to redraw, we're trying to reflow the prompt, so we reflow it and prompt duplicate itself. The solution is not to reflow prompt, but we don't have any information about what to reflow and what don't. Some terminal develop heuristics for that, but they are not reliable and could break user content, so the only thing if shell could inform us somehow, but there's no escape for that. Not reflowing at all isn't an option.
