### ISSUE TITLE
Option to use integrated GPU only

### ISSUE THREAD

**Issue by zllovesuki** [alacritty/alacritty#3473]
Is it possible to tweak the settings/source code somehow so alacritty will only use the integrated GPU on dual-GPU MacBook?

### System

OS: macOS
Version: alacritty 0.4.1 (4d9253b)

**Comment by chrisduerr** [comment]
I believe this should already be possible by editing the `Info.plist` manifest on macOS.

**Comment by zllovesuki** [comment]
🤔IIRC deleting `NSSupportsAutomaticGraphicsSwitching` would be the one to force discrete GPU?

**Comment by chrisduerr** [comment]
I don't really use macOS, so you'll have to try it yourself. `NSHighResolutionCapable` might be worth testing too.

**Comment by nixpulvis** [comment]
I'd be somewhat curious what the correct default for our shipped version of Alacritty should be. Does the integrated GPU actually perform much worse for Alacritty's somewhat simple needs? Would the power savings be worth it for macOS users?

It is of course possible to build/edit your own `Info.plist`, I'm just throwing this out there.

**Comment by chrisduerr** [comment]
> I'd be somewhat curious what the correct default for our shipped version of Alacritty should be. 

We're already following that. We rely on what macOS usually does and use the dedicated GPU when on power.

> Does the integrated GPU actually perform much worse for Alacritty's somewhat simple needs?

Yes it does.

**Comment by nixpulvis** [comment]
> We rely on what macOS usually does and use the dedicated GPU when on power.

Is that actually true? I thought that it would try and be smart about only using it for applications that "need" it. From this [documentation achive](https://developer.apple.com/library/archive/qa/qa1734/_index.html), it seems like any OpenGL application will trigger the switch:

> By default, once your application creates an OpenGL context (by either calling OpenGL directly or an API that relies on OpenGL such as Core Animation, Core Image, etc), the MacBook Pro automatically switches to the higher-end discrete GPU for performance concerns and won't switch back until the application quits.

Furthermore, to be sure we're not triggering the dedicated GPU it sounds like it may require a [little bit of digging](https://supermegaultragroovy.com/2016/12/10/auto-graphics-switching). I'm sure we're open to patches (if needed) to ensure the dGPU isn't triggered, however I think setting `plist` values is the users responsibility. We're not going to add a `--no-dedicated-gpu``flag for example.

**Comment by chrisduerr** [comment]
> Is that actually true? I thought that it would try and be smart about only using it for applications that "need" it. From this documentation achive, it seems like any OpenGL application will trigger the switch

Yes exactly. Switches to dedicated GPU when Alacritty runs on power.

> Furthermore, to be sure we're not triggering the dedicated GPU

We want to trigger the dedicated GPU.

> I'm sure we're open to patches (if needed) to ensure the dGPU isn't triggered,

We are **NOT**.

> I think setting plist values is the users responsibility

Exactly, so everything's working as it should. If you want to disable things using the Info.plist should work. And there's always the option to disable hardware acceleration in `window.rs`, which will disable it for good.

So everything seems to be working already, I don't see any further reason for action.

**Comment by nixpulvis** [comment]
@chrisduerr what if the user would prefer to save battery over the performance of the dGPU? I'm not sure without testing on a Mac, but it really sounds like an OpenGL application even on battery would trigger the dGPU.

If that understanding is correct, I'm confused by your stance here. Though I am hopeful that simply setting the variable in the Info.plist will suffice.

**Comment by chrisduerr** [comment]
> what if the user would prefer to save battery over the performance of the dGPU

If a user prefers saving battery over performance, they should use a terminal emulator optimized for battery, not performance?

> it really sounds like an OpenGL application even on battery would trigger the dGPU

Based on my macOS experience, it does not.

**Comment by nixpulvis** [comment]
FWIW, there seems to be a tool (no idea if it still works) that can force your mac to always use the iGPU. https://gfx.io/

Otherwise, we should already use the iGPU when you're on battery, as long as your macOS settings allow for graphics card switching.
