### ISSUE TITLE
#3315 breaks arrow key navigation in Neovim

### ISSUE THREAD

**Issue by DarkDefender** [alacritty/alacritty#3476]
With #3315 merged, navigation inside of Neovim with arrow keys is broken.

What happens is that the key press seems to trigger twice.
So if I hit up arrow, the cursor will jump up to rows instead of one and so on.
This happens in drop down prompts and other UI elements as well if navigated with the arrow keys.

If I rollback to the commit before #3315 (64db7d3), everything works fine again.

### System

OS: Gentoo Linux
Version: alacritty 0.5.0-dev (1a8cd17)
WM: Sway (Wayland)

**Comment by matthiaskrgr** [comment]
Got the same here where I can't navigate the cmdline properly, I don't think this is related to neovim :)
→ and ← always skip a character for me.

**Comment by kchibisov** [comment]
Can someone try `alacritty --config-file /dev/null`?

**Comment by matthiaskrgr** [comment]
Could not observe the ←→ behaviour with `alacritty --config-file /dev/null`

**Comment by kchibisov** [comment]
I feel like we broke config serialization a bit. I feel like you have bindings for arrow keys, etc right in the config.

**Comment by matthiaskrgr** [comment]
In case it helps; this is part of my config
````
  - { key: End,                     chars: "\x1b[F",   mode: ~AppCursor  }
  - { key: PageUp,   mods: Shift,   chars: "\x1b[5;2~"                   }
  - { key: PageUp,   mods: Control, chars: "\x1b[5;5~"                   }
  - { key: PageUp,                  chars: "\x1b[5~"                     }
  - { key: PageDown, mods: Shift,   chars: "\x1b[6;2~"                   }
  - { key: PageDown, mods: Control, chars: "\x1b[6;5~"                   }
  - { key: PageDown,                chars: "\x1b[6~"                     }
  - { key: Tab,      mods: Shift,   chars: "\x1b[Z"                      }
  - { key: Back,                    chars: "\x7f"                        }
  - { key: Back,     mods: Alt,     chars: "\x1b\x7f"                    }
  - { key: Insert,                  chars: "\x1b[2~"                     }
  - { key: Delete,                  chars: "\x1b[3~"                     }
  - { key: Left,     mods: Shift,   chars: "\x1b[1;2D"                   }
  - { key: Left,     mods: Control, chars: "\x1b[1;5D"                   }
  - { key: Left,     mods: Alt,     chars: "\x1b[1;3D"                   }
  - { key: Left,                    chars: "\x1b[D",   mode: ~AppCursor  }
  - { key: Left,                    chars: "\x1bOD",   mode: AppCursor   }
  - { key: Right,    mods: Shift,   chars: "\x1b[1;2C"                   }
  - { key: Right,    mods: Control, chars: "\x1b[1;5C"                   }
  - { key: Right,    mods: Alt,     chars: "\x1b[1;3C"                   }
  - { key: Right,                   chars: "\x1b[C",   mode: ~AppCursor  }
  - { key: Right,                   chars: "\x1bOC",   mode: AppCursor   }
  - { key: Up,       mods: Shift,   chars: "\x1b[1;2A"                   }
  - { key: Up,       mods: Control, chars: "\x1b[1;5A"                   }
  - { key: Up,       mods: Alt,     chars: "\x1b[1;3A"                   }
  - { key: Up,                      chars: "\x1b[A",   mode: ~AppCursor  }
  - { key: Up,                      chars: "\x1bOA",   mode: AppCursor   }
  - { key: Down,     mods: Shift,   chars: "\x1b[1;2B"                   }
  - { key: Down,     mods: Control, chars: "\x1b[1;5B"                   }
  - { key: Down,     mods: Alt,     chars: "\x1b[1;3B"                   }
  - { key: Down,                    chars: "\x1b[B",   mode: ~AppCursor  }
  - { key: Down,                    chars: "\x1bOB",   mode: AppCursor   }
  - { key: F1,                      chars: "\x1bOP"                      }
  - { key: F2,                      chars: "\x1bOQ"                      }
````
I don't recall ever having edited that part though.

**Comment by kchibisov** [comment]
Yeah, it's a problem with binding replacing, since I doubt anyone tested it with bindings from `v0.3.3`, but it seems like you're ending up with 2 bindings for alt-screen for arrow key, somehow.

**Comment by nixpulvis** [comment]
As a workaround, adding `|~Vi` to `mode` for the `Right`, `Left`, `Up`, and `Down` bindings in your config should solve your problem.

**Comment by kchibisov** [comment]
This actually works as expected tbqh. So the only thing we can do is to relax our rules even more and not consider `modes` during config update state.

Anyway, I'd just recommend to sync your bindings with current default ones.

**Comment by unphased** [comment]
Could someone explain more specifically what changed that necessitates this change to our keybinding configuration? It's going to be a bit annoying to now have to synchronize the alacritty version upgrade with this config file change.

**Comment by kchibisov** [comment]
We added one more mode and changed all default bindings modes to reflect that, we're working to create some solution so really old bindings configuration could still kind of work https://github.com/alacritty/alacritty/pull/3479.

**Comment by chrisduerr** [comment]
I'd strongly recommend removing configuration options you have not set yourself from your configuration file. Every option has a default value, so this is perfectly safe to do.

Doing so, will prevent things like this from ever affecting you, unless we explicitly decide to change an existing option you have manually set yourself.

There probably will be a fix for this specific issue before the 0.5.0 release, but that doesn't change that removing default bindings is a good idea anyways.

**Comment by tuxiqae** [comment]
Also appears in htop

**Comment by kchibisov** [comment]
For everyone pinging that issue. This is not really an issue that we broke a config file from a `v0.3.3` version, you **don't need custom bindings to make arrow keys working**, all bindings are builtin inside of alacritty for a long time already, so you should only define the ones you actually created yourself or fix old bindings by fixing their mode properly (by adding `mode: ~Vi` to them), instead of bumping this "issue" with your very old bindings.

**Comment by tuxiqae** [comment]
I might have misunderstood you, but what if I never changed my keybindings?

**Comment by kchibisov** [comment]
Well, than it's time to change them if you want this issue fixed(just look at our default config), as I said, we're working on some fix to remove builtin bindings more aggressively, which will break some new bindings in this particular case, since we have arrow keys now mapped in addition in `Vi` mode. just remove all your bindings if you've never changed them and it'll work just fine.

Note, there's no guarantee that we won't break bindings before `v1.0.0`, it wasn't even a break, since our logic works as expected. And you're expected to have 2 mappings with old bindings now, because they differ from new builtin ones.

**Comment by nixpulvis** [comment]
FWIW, once we've landed on the exact behavior that's changing in 0.5 we should make it clear what (if any) steps are needed to update existing configurations in the CHANGELOG.

That said, most people will be happiest by simply deleting their old default bindings, as mentioned above.

**Comment by ishanjain28** [comment]
I have this problem outside of vim/neovim. 

I use zsh shell. If I press _any_ arrow key, It is reacted to, twice. So, Pressing left/right jumps 2 steps back/forward and pressing up/down steps by 2 entries in zsh history. 

Alacritty version, alacritty-git 0.5.0.1500.g1a8cd172-1(from AUR).

As a temporary fix, I have reverted back to 0.4.2 and this fixes the problem for me. I'll just upgrade later at some point when this is fixed. 

Please let me know if any one here needs more information. I'd love to help. :)

**Comment by kchibisov** [comment]
Just remove bindings from config and it should be fixed.

**Comment by ishanjain28** [comment]
> Just remove bindings from config and it should be fixed.

Yess, Thank you sooo much! 

I removed entries like, 

    - { key: Down,                    chars: "\x1b[B",   mode: ~AppCursor  }
    - { key: Down,                    chars: "\x1bOB",   mode: AppCursor   }
 

and now it works fine. :)

**Comment by aslatter** [comment]
I'm also seeing this - as a workaround I've reverted back to 64db7d3da, which is fine for now.

Do you have any tips on which keybinds are likely to be broken, or what I should be looking for in my config?

Most of what's in my config is what Alacritty created for me, but I don't really remember what is the default and what I added in, so any tips would be appreciated.

**Comment by chrisduerr** [comment]
@aslatter:

> I'd strongly recommend removing configuration options you have not set yourself from your configuration file. Every option has a default value, so this is perfectly safe to do.

As soon as you remove all the keyboard configuration options you have not added yourself, everything will work. There's no need to revert back to anything.

**Comment by aslatter** [comment]
Well I don't really remember if I've customized that part of the config or not - I'll delete the whole section and see if I'm missing anything down the line.

Thanks for the help!
