### ISSUE TITLE
Windows: can the upcoming release pick up the mouse support from conpty?

### ISSUE THREAD

**Issue by damnskippy** [alacritty/alacritty#3477]
Looks like conpty now finally supports mouse input:
https://devblogs.microsoft.com/commandline/windows-terminal-preview-v0-10-release/

Can the upcoming release of Alacritty pick up this new version of conpty with the mouse support?
Thanks.

**Comment by kchibisov** [comment]
it'll be done automatically with windows update.

**Comment by kchibisov** [comment]
For more https://github.com/alacritty/alacritty/issues/1663#issuecomment-600224264 and it's a duplicate of #1663 to some point.
