### ISSUE TITLE
[question] Can I achieve same ui as with iterm2 + powerlevel10k ?

### ISSUE THREAD

**Issue by alex-popov-tech** [alacritty/alacritty#3480]
### System

OS: macOS
Version: 0.4.1 (from homebrew)

### Question

Hello guys! My use case is pretty simple - I'm using iTerm2 + tmux + nvim, and it works pretty slow...Well, I've always felt that, but when tried alacritty with nvim it worked way, way faster and smoother, so I felt in love with alacritty.

I tried to search through issuer, some articles and random people dotfiles, and did not find the answer.

Here is my iTerm2 config - https://github.com/alex-popov-tech/.dotfiles/blob/master/terminal/profile.json#L9-L11
Here is tmux config - https://github.com/alex-popov-tech/.dotfiles/tree/master/tmux
Here is how I install fonts - https://github.com/alex-popov-tech/.dotfiles/blob/master/install.sh#L160
Here how it looks like - https://share.getcloudapp.com/wbumvnjq
Here how alacritty looks like - https://share.getcloudapp.com/7KuRjYdG
I use default alacritty, no config file in `$HOME/.config/alacritty`

The question is - can I achieve same ui with alacritty? (it's font-related question i think? )

**Comment by kchibisov** [comment]
we don't have a concept of non-ascii font, but you should get glyphs from font fallback. it seems like you have bad `locale`, etc. So what's the output of `locale` on your system? You can set font in `alacritty.yml`. More advance font configuration is proposed #957

**Comment by alex-popov-tech** [comment]
hello @kchibisov , thanks for quick response!
here is output of `locale`:
```
locale                  
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

Not sure what should help me in #957 , can you please add some details? I'm not very confident in these things :)

**Comment by kchibisov** [comment]
you'll be able to set fonts per unicode ranges. Can you change your font in a alacritty.yml to a `Nerd` font you have in `fonts` section and retest?

**Comment by alex-popov-tech** [comment]
alacritty.yml:
```
font:
  normal:
    family: "Nerd"
```
no changes @kchibisov

**Comment by kchibisov** [comment]
I mean you should put its name. You can get it in Font Book app.So it should be something like.
```
font:
  normal:
    family: "Hack Nerd Font Complete" # This is likely a wrong name, so find out it yourself.
```

**Comment by alex-popov-tech** [comment]
it works now, thanks @kchibisov !
Is it possible to have glyphs from `nerd tree` and letters from `JetBrains Mono` ( as i have now in iterm ) ?

**Comment by alex-popov-tech** [comment]
so solutions wat to download already patched font from here https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/JetBrainsMono
and create a config:
```
font:
  normal:
    family: "JetBrainsMono Nerd Font"
  size: 16
```
closing, @kchibisov thanks again!
