### ISSUE TITLE
Unexpected behavior in Alacritty when opening using i3 hotkey

### ISSUE THREAD

**Issue by Harjuu** [alacritty/alacritty#3484]
When opening Alacritty using an i3 hotkey (bindsym $mod+Return exec alacritty) it opens in some mode where I can't type normally. Most keys don't do anything at all. When pressing j/k it seems to cycle through previous commands. I haven't been able to figure out how to exit it but somehow it returns to normal if I open another terminal and then switch back to the original one.

Alacritty works as normal when launching it using the alacritty command. 

### System

OS: Arch Linux
Version: 0.4.1
Linux/BSD: X11, Compton, i3

**Comment by kchibisov** [comment]
Could you try v0.4.2-rc2 or master?

**Comment by Harjuu** [comment]
> Could you try v0.4.2-rc2 or master?

I just tried with 0.5.0-dev and I'm having the same issue there.

**Comment by cole-h** [comment]
This sounds like you have `vi` mode enabled in your shell. Maybe some section of your config that en/disables this is not running when started via a hotkey (maybe conditional based on some env vars?), but is when you run as a normal command. I'd look into that. Maybe check if your shell is set in your `alacritty.yml` with some weird flags set or something.

**Comment by Harjuu** [comment]
> This sounds like you have `vi` mode enabled in your shell. Maybe some section of your config that en/disables this is not running when started via a hotkey (maybe conditional based on some env vars?), but is when you run as a normal command. I'd look into that. Maybe check if your shell is set in your `alacritty.yml` with some weird flags set or something.

I don't think it is `vi` mode, as I can't press `i` to start typing or anything like that. So far the only way I've found to get it working is by opening another terminal and then switching back to the first one, then the first one works as normal.

I've also tried this with bspwm, and it still behaves the same. If I launch alacritty using a binding in shkxd it behaves just like in i3.

**Comment by Harjuu** [comment]
So now I've found that if I press any modifier key, alt`/`ctrl`/`shift` it starts working normally. I've also tried switching to back to bash instead of zsh but the problem persists.

**Comment by kchibisov** [comment]
Duplicate #3466
