### ISSUE TITLE
working_directory doesn't support "~"

### ISSUE THREAD

**Issue by NetOperatorWibby** [alacritty/alacritty#3486]
### System

OS: macOS
Version: v0.4.2-rc2

### Issue

I want to set `working_directory` to `~/MyCode` but it doesn't work. If I use `/Users/Me/MyCode` it works but I feel that Alacritty should know that `~` is a shortcut for `/Users/Me`. Also, this makes it difficult to create reusable configurations.

**Comment by kchibisov** [comment]
`~` is expanded by your shell and we can't do much here, unless we try to expanded by ourself.

**Comment by chrisduerr** [comment]
Alacritty is not a shell and I have no interest in changing that.

**Comment by NetOperatorWibby** [comment]
Ah okay. Welp.
