### ISSUE TITLE
Show errors in a GUI

### ISSUE THREAD

**Issue by victorb** [alacritty/alacritty#3488]
This is a feature request that might be out-of-scope but figured I open it anyways. Not sure how feasible it is either, you'll be the judge of that!

Basically, I did an upgrade that force me to restart the computer before it can open new GL contexts. This is not the issue in itself.

The issue is that I only see this issue if I try to run alacritty via another terminal. If I try to run alacritty via a application launcher or keyboard shortcut (I use super + Enter to launch alacritty), I don't see the error at all.

So my suggestion is to use something that can draw messages even if GL contexts can't be opened (for example, I can still open xterm and many other applications while my computer is in this state), so I can see the error message somehow, without resorting to launching another terminal to get the error message.

Work around for now is to have my WM catching errors from launching and display them via the general error handler awesomewm has. But would be awesome to have this out-of-the-box.

**Comment by chrisduerr** [comment]
We already show errors in a UI. But we have no control over what other depedencies might log independently. Mesa or whatever is used here likely just writes an error to stderr itself, so we never get notified about it.

Everything we log as `error` or `warn`, will be visible to the user.
