### ISSUE TITLE
Question: How to unbind xyz

### ISSUE THREAD

**Issue by Shooooooooo** [alacritty/alacritty#3489]
I am running linux and wanted to unbind default keys for IncreaseFontSize/DecreaseFontSize.
Thus I have set, for example, action for `Ctrl - =` to be `ReceiveChar`.
However, the behavior is not what I expected. If I hit `Ctrl - =`, instead of passing these 2 keys to the underline TTY program, it only passes the equal character but not the control key.
Maybe I have missed something, but is there any way of unbind and pass both key presses?

Thanks!

**Comment by kchibisov** [comment]
`Ctrl + =` and `=` is the same thing for a terminal. You've unbinded everything correctly, so you should likely create your own binding for it, but as I said, there's not standard chars for `Ctrl + -`/`Ctrl + =`. Other terminals don't have them either, and this is the reason behind using `Ctrl + -`/`Ctrl + =` for font size change. You can verify in other terminals with `showkey -a`.

**Comment by Shooooooooo** [comment]
This is interesting. You are correct about `showkey -a` behavior.
However, my emacs in terminal does able to capure `Ctrl - =` with XTerm, but not with Alacritty.
Procedure to reproduce:
1. Start Emacs.
2. M-x describe-key
3. press `C - =`
3. It shows the correct function which binds to `C - =`.

I wonder if it's a limitation by showkey?

**Comment by kchibisov** [comment]
Hm, emacs has builtin terminal, right? Could you try `showkey -a` in it?

**Comment by kchibisov** [comment]
Anyway, your emacs issue is tracked  there https://github.com/alacritty/alacritty/issues/3101

**Comment by Shooooooooo** [comment]
I've tried it with [emacs-libvterm](https://github.com/akermu/emacs-libvterm)
Unbinded `C - =`
Rebind `C - =` to `vterm--self-insert` so that the input will be passed directly to underline terminal. here is the output for `=` and `C - =`

`=        61 0075 0x3d`

`^[[61;5u         27 0033 0x1b
         91 0133 0x5b
         54 0066 0x36
         49 0061 0x31
         59 0073 0x3b
         53 0065 0x35
        117 0165 0x75`

**Comment by Shooooooooo** [comment]
Thanks for the pointer.
