### ISSUE TITLE
Cannot bind the Delete button to its actual action

### ISSUE THREAD

**Issue by nikolaof** [alacritty/alacritty#3494]
Hi all.
I'm dealing with a problem while trying to make some of the keys of my keyboard to work.
So after reading wiki's [page](https://github.com/alacritty/alacritty/wiki/Keyboard-mappings) about mappings I did the following in order to make the delete button to work as expected.

Runing `alacritty --print-events` and pressing delete I got :

```
46:[2020-03-19 23:28] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(77594626))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 111, state: Pressed, virtual_keycode: Some(Delete), modifiers: (empty) }, is_synthetic: false } }
47:[2020-03-19 23:28] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(77594626))), event: ReceivedCharacter('\u{7f}') }
```
So based on these results I add the following line under the `keybindings:`
`- { key: Delete,                  chars: "\x7f",     }`

I saved the file and then tried to delete a string. What actually is happening when pressing the delete is to remove a character from the left of the cursor and not from the right as it is expected. Am I missing something?

**Comment by kchibisov** [comment]
We already have `Delete` binded, so you shouldn't add it.

However `Delete` is
```yaml
- { key: Delete,                  chars: "\x1b[3~"     }
```

**Comment by nikolaof** [comment]
I know that you have a binding for the Delete but in my system when I press on it, it does something weird.

It toggles (upper/lower) the case of the letters on the right side of the cursor for some reason. That's why I tried what I described.

**Comment by kchibisov** [comment]
Are you using zsh?

**Comment by nikolaof** [comment]
Yes

**Comment by kchibisov** [comment]
zsh doesn't have a lot of bindings by default, so add to your zsh config.

```
bindkey "^[[3~" delete-char
```

**Comment by nikolaof** [comment]
Oh! thanks very much.
