### ISSUE TITLE
Can`t change window decoration.

### ISSUE THREAD

**Issue by limpid-kzonix** [alacritty/alacritty#3495]
OS: Linux, 5.3.0-42-generic, Ubuntu 18.04.4 LTS x86_64
Version: 0.4.1
Linux/BSD: X11, GNOME 3.28.4, Wayland

Can`t find the way hot to restore the window decoration to default (GTK)

![image](https://user-images.githubusercontent.com/8176996/77164162-5c1aac00-6ab8-11ea-8110-d6962763aeb9.png)

![image](https://user-images.githubusercontent.com/8176996/77164318-a0a64780-6ab8-11ea-832c-9b6bd737bbe1.png)

Even with `none` config, the annoying 'Windows'-style window decoration appears.

**Comment by limpid-kzonix** [comment]
Is there a way how to arrange window buttons (close, maximize, minimize)  to the left side?

**Comment by limpid-kzonix** [comment]
Add it occurs only on Wayland, with X11 everything works fine.

**Comment by kchibisov** [comment]
you're on Wayland and using client side decorations. We don't have an option to change them and won't provide any.

**Comment by kchibisov** [comment]
`none` should work to disable decorations though.

**Comment by limpid-kzonix** [comment]
It does not depend on allacrity configuration (decorations: full or none). In wayland session the  'Windows'-style window decoration appears. And you say that this one is a default wayland windows decoration. Am I correct? And there is no way how to change it on wayland?

**Comment by kchibisov** [comment]
>And you say that this one is client side window decoration that can`t be changed in case of Wayland. Am I correct?

This is correct, GNOME decide to not support Server side decorations on Wayland, so each client should render something.

>It does not depend on allacrity configuration (decorations: full or none).

`none` should hide them at least, works on v0.4.1 on my fedora system in vm.

But yeah, nothing we can do about them on GNOME.
