### ISSUE TITLE
Garbage left over in buffer after resizing window

### ISSUE THREAD

**Issue by Xyene** [alacritty/alacritty#3499]
Alacritty's behaviour when resizing the terminal window is a bit odd (doesn't match other terminal emulators I've tried). I'm not sure if this is a bug, or working as intended.

To reproduce on latest master:

* Open a small window, and generate a screen-full of data (e.g. `ls -al /usr/bin`).
![image](https://user-images.githubusercontent.com/1403503/77237296-58148a00-6b9d-11ea-8490-cc74feb52641.png)

* Open something like `vim`, then resize the terminal to be a bit bigger.
![image](https://user-images.githubusercontent.com/1403503/77237301-69f62d00-6b9d-11ea-8a74-57f8d6ca1665.png)

* Quit `vim`.
![image](https://user-images.githubusercontent.com/1403503/77237305-75e1ef00-6b9d-11ea-99f0-7725aedf87b8.png)

At this point, there is now a bunch of garbage output from the original command _below_ the current prompt, and a <kbd>Ctrl</kbd>+<kbd>L</kbd> is necessary to make the terminal usable again. Not a huge deal, but a papercut nonetheless.

**Comment by chrisduerr** [comment]
What platform are you on? What terminfo do you use? What's your ncurses version? Which Alacritty version is this? Can you reproduce this with other shells?

Please provide some more information, otherwise there's no way to help.

**Comment by Xyene** [comment]
@chrisduerr sorry about that, I could reproduce it on every setup I tried so I assumed it was configuration-independent. I can reproduce this on:

* GNOME shell (X11, default Debian Buster version)
* GNOME shell (Wayland, default Debian Buster version)
* sway (Wayland, master)

My colleague mentioned that he's seen this same behaviour on the Windows build from the _Releases_ tab, but I can't verify this myself (I've asked them to try again, and will update when they do).

I mentioned in the first post that this was on Alacritty master, but I could've been more clear.

I have the default `ncurses` version that ships with Debian Buster, which appears to be `6.1+20181013-2`.

`nano` also functions as a reproduction instead of `vim`. For reference, the same steps on other terminals I've tried produce the below results:

* `uxterm`
![image](https://user-images.githubusercontent.com/1403503/77240545-899d4d80-6bbd-11ea-9fa7-41979316e767.png)

* `kitty*
![image](https://user-images.githubusercontent.com/1403503/77240550-9fab0e00-6bbd-11ea-9429-adc57bb59c61.png)

* `gnome-terminal`
![image](https://user-images.githubusercontent.com/1403503/77240556-b6e9fb80-6bbd-11ea-98e7-78519a7bcf40.png)

The exact mechanism by which these shells deal with the resize vary, but all three are immediately usable after exiting `vim`.

**Comment by Xyene** [comment]
Since the number of commits was not too large and I had a bit of free time, I bisected what I suspect is the cause:

```
$ git bisect good
4cc6421daa4ff5976ab43c67110a7a80a36541e5 is the first bad commit
commit 4cc6421daa4ff5976ab43c67110a7a80a36541e5
Author: Kirill Chibisov <contact@kchibisov.com>
Date:   Sun Jan 26 16:49:58 2020 +0300

    Fix incorrect grid.len() and grid.history_size()

:040000 040000 f56a98cbf1dee4baccfd523ae44ccc9c13a5ec2b 457a412ef387e1396f711f9693dc6f176dde5f06 M	alacritty_terminal
```

This change appears to have been introduced in https://github.com/alacritty/alacritty/pull/3115. The issue is not present in its parent commit, f48204eee20ddb0a3b23c10d27e3c75fbcd3f7f3.
