### ISSUE TITLE
[Feature] Set title while alacritty is already running

### ISSUE THREAD

**Issue by danielakhterov** [alacritty/alacritty#3506]
I know you can do `alacritty --title blah`, but that would require me restart my alacritty session. It would be nice to change the title to something while already in an alacritty terminal although I don't know how that would/should be done. I used to use a script I found to change the title using `xdotool` and `wmctrl`, but that doesn't seem to work with alacritty if `dynamic: false`.

The script if anyone is interested 
```bash
FOCUSED=$(wmctrl -lp | grep "$(xprop -root | grep _NET_ACTIVE_WINDOW | head -1 | awk '{print $5}' | sed 's/,//' | sed 's/^0x/0x0/')")
FPID=$(echo "$FOCUSED" | awk '{print $3}')
FNME=$(echo "$FOCUSED" | cut -f -4  -d ' ' --complement)
xdotool search -all --pid "$FPID" --name "$FNME" set_window -name "$*"
```

**Comment by chrisduerr** [comment]
`echo -e "\e]2;New Title\x9c"` should set your title.

**Comment by danielakhterov** [comment]
That didn't seem to work. Ran it in fish v3.1.0, and bash 4.4.23(1)-release.

**Comment by chrisduerr** [comment]
Are you running tmux?

**Comment by danielakhterov** [comment]
No, I'm i3, alacritty, fish.

**Comment by chrisduerr** [comment]
> I used to use a script I found to change the title using xdotool and wmctrl, but that doesn't seem to work with alacritty if dynamic: false.

Oh, nevermind. The title cannot be changed for one specific instance if you have dynamic title changes disabled.

**Comment by danielakhterov** [comment]
Is there a way to prevent the title from changing on a per command basis that isn't `dynamic: false`? It's just harder to tell which window is which terminal if the title is always `fish /usr/bin/nvim blah`. Ultimately I'd like it to just print out `blah` in this case.

**Comment by chrisduerr** [comment]
The only way to change the title without dynamic title activated, is by changing the title in the configuration file without the command line option specified.

If you want to live change the title of an Alacritty instance you can use the `--config-file` option to specify the title in that configuration file and then change it in there.

**Comment by chrisduerr** [comment]
> Is there a way to prevent the title from changing on a per command basis that isn't dynamic: false?

There are ways, but none of them are really great solutions.

**Comment by chrisduerr** [comment]
Since the configuration  file can already be used to update this live and dynamic title changes are supported, I don't see what else Alacritty would do to allow changing the window title.

Inherited configuration files might make it a bit easier to use separate config files for separate purposes, but that's already tracked in #779.

**Comment by hemachandsai** [comment]
> echo -e "\e]2;New Title\x9c"

Depending on the shell some times we would have to remove the terminating hex character: \x9c, otherwise the title is set to blank
