### ISSUE TITLE
Support official fedora install

### ISSUE THREAD

**Issue by kaushalyap** [alacritty/alacritty#3511]
[Currently we have enable a repo to install alacritty in Fedora](https://github.com/alacritty/alacritty#fedora), please allow us to install alacritty without enabling any other repos in Fedora

**Comment by chrisduerr** [comment]
That's up to Fedora, not Alacritty.

**Comment by kaushalyap** [comment]
@chrisduerr Please read https://docs.fedoraproject.org/en-US/modularity/making-modules/
rust libs like `exa, bat, fd-find, ripgrep, tokei, hyperfine `have already done it.

**Comment by chrisduerr** [comment]
Packaging is not done upstream by Alacritty. If you wish to have an application packaged that should be done by package maintainers from the distribution.

That's how it has always worked and there is no other way for us to maintain packages across a large section of distros and operating systems.
