### ISSUE TITLE
MacOS + Bash: cursor does not correctly move to the beginning of the line on `ctrl-a`

### ISSUE THREAD

**Issue by iamFIREcracker** [alacritty/alacritty#3512]
### System

OS: macOS
Version: I don't have `alacritty` as a standalone command so `alacritty --version` would fail... the following however should do just fine:

````
> cat /Applications/Alacritty.app/Contents/Info.plist | grep VersionString -A1
  <key>CFBundleShortVersionString</key>
  <string>0.4.2-rc4</string>
````
### Steps to reproduce

1. Open a new instance

```
> open -n /Applications/Alacritty.app --args --config-file /dev/null
```

The new instance is opened, and the configured prompt is printed:

````
matteolandi at hairstyle.local in /Users/matteolandi
> █
````

2. Press `up-arrow` to access the last executed command:

```
matteolandi at hairstyle.local in /Users/matteolandi
> open -n /Applications/Alacritty.app --args --config-file /dev/null█
```

3. Press `ctrl+a` to get to the beginning of the line

### Expected behavior

The cursor moves indeed at the beginning of the line

```
matteolandi at hairstyle.local in /Users/matteolandi
> █pen -n /Applications/Alacritty.app --args --config-file /dev/null
```

### Actual behavior

The cursor stops somewhere in the middle of the line

```
matteolandi at hairstyle.local in /Users/matteolandi
> open -n█/Applications/Alacritty.app --args --config-file /dev/null
```

Note 1: if I now press `ctr-e` (to get to the end of the line), the cursor get past the current end of the line:

```
matteolandi at hairstyle.local in /Users/matteolandi
> open -n /Applications/Alacritty.app --args --config-file /dev/null       █
```

Note2: if I hit `ctrl+c` (to reset the prompt), press `up-arrow` again, and start hammering `left-arrow`, it eventually gets to the beginning of the line:

```
matteolandi at hairstyle.local in /Users/matteolandi
> open -n /Applications/Alacritty.app --args --config-file /dev/null       ^C

matteolandi at hairstyle.local in /Users/matteolandi
130 > █pen -n /Applications/Alacritty.app --args --config-file /dev/null
```

And if I know press `ctrl+e` (again, to get to the end of the line), the cursor does actually move to the end of the line:

```
matteolandi at hairstyle.local in /Users/matteolandi
130 > open -n /Applications/Alacritty.app --args --config-file /dev/null█
```

PS. all looks OK when executing these very same steps with `terminal.app`.

Updated:
- Added additional step which includes pressing `ctrl+e`

**Comment by chrisduerr** [comment]
What do you get when pressing ctrl+v and then pressing ctrl+a?

**Comment by iamFIREcracker** [comment]
It prints `^A`:

```
matteolandi at hairstyle.local in /Users/matteolandi
> open -n /Applications/Alacritty.app --args --config-file /dev/null^A█

**Comment by kchibisov** [comment]
Could you share `locale` output from alacritty?

**Comment by iamFIREcracker** [comment]
Here you go:

```
matteolandi at hairstyle.local in /Users/matteolandi
> locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```
Same from `terminal.app`, FWIW

**Comment by chrisduerr** [comment]
> It prints ^A

Sounds like it's your shell. Please make sure you're running the same shells in both. If you're running zsh in Alacritty, it will print ^A unless you bind it yourself. So give it a shot in bash and it will probably work.

**Comment by iamFIREcracker** [comment]
All the experiments I did, I was doing them with the same shell (Bash in my case), and I don't think I have any special bindings.  However, I tried disabling my _custom_ prompt and now `ctrl+a` is correctly moving to the beginning of the line.

Let me dig a little bit deeper into why this is happening (wrong escape codes? multi-line prompt?) and then I will get back to you with my findings.

**Comment by iamFIREcracker** [comment]
Alright, I was able to reproduce the error with this minimal `.bashrc` file:

```
unset PROMPT_COMMAND
GREEN="\e[32m"
export PS1="${GREEN}${USER}> "
```

When I remove/empty `$GREEN`, it all works fine (i.e. `ctrl+a` takes the cursor to the beginning of the prompt).

Interestingly enough this minimal example also breaks `terminal.app`, so at this point I really suspect not a problem with Alacritty, but with my environment (and `readline`):

```
> brew info readline
readline: stable 8.0.4 (bottled) [keg-only]
Library for command-line editing
https://tiswww.case.edu/php/chet/readline/rltop.html
/usr/local/Cellar/readline/8.0.4 (48 files, 1.5MB)
  Poured from bottle on 2020-03-07 at 20:02:52
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/readline.rb
==> Caveats
readline is keg-only, which means it was not symlinked into /usr/local,
because macOS provides the BSD libedit library, which shadows libreadline.
In order to prevent conflicts when programs look for libreadline we are
defaulting this GNU Readline installation to keg-only.

For compilers to find readline you may need to set:
  export LDFLAGS="-L/usr/local/opt/readline/lib"
  export CPPFLAGS="-I/usr/local/opt/readline/include"

For pkg-config to find readline you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/readline/lib/pkgconfig"

==> Analytics
install: 629,640 (30 days), 1,352,791 (90 days), 5,407,249 (365 days)
install-on-request: 66,551 (30 days), 127,320 (90 days), 531,237 (365 days)
build-error: 0 (30 days)
```

**Comment by njdoyle** [comment]
You need to wrap non-printing escapes in Bash PS1s with `\[` and `\]` so that Bash can properly do prompt length calculations.

**Comment by iamFIREcracker** [comment]
I removed all the styles from my actual prompt line (not from the whole prompt, just the command line) and now everything works as expected.

Thanks everybody!

**Comment by jgroeneveld** [comment]
Just an FYI for all people that might land here.
I had serious troubles on Mac and ZSH with alacritty because when i moved left over commands that had multiple lines and then started deleting/inserting the cursor would jump (visually) all over the place and I would be unable to understand whats happening.

Just setting the locale solved it. `export LANG=de_DE.UTF-8`

No idea why, never had any issues with other terminals.

**Comment by scotstan** [comment]
In case you're seeing this ~Aug 1 as I found it this issue, thinking I had the same problem.

Work around № 1:

With alacrity 5.0 and zsh, I disabled zsh-syntax-highlighting plugin. That fixed readline style cursor manipulation for me. 

Work around № 2:
Upgrade your zsh-syntax-highlighting (current version for me at the time is 0.8.0-alpha)

**Comment by guiyumin** [comment]
> In case you're seeing this ~Aug 1 as I found it this issue, thinking I had the same problem.
> 
> Work around № 1:
> 
> With alacrity 5.0 and zsh, I disabled zsh-syntax-highlighting plugin. That fixed readline style cursor manipulation for me.
> 
> Work around № 2: Upgrade your zsh-syntax-highlighting (current version for me at the time is 0.8.0-alpha)

but we need zsh-syntax-highlighting plugin, don't we ?
