### ISSUE TITLE
Set title right before drawing, instead of doing right away.

### ISSUE THREAD

**Issue by kchibisov** [alacritty/alacritty#3513]
It should reduce potential flood on Wayland(could lead to compositor killing your app) and could also improve performance in some case, since you reduce redundant calls to winit, since user won't see this title anyway.

**Comment by chrisduerr** [comment]
Could you go into a bit more detail here? Why would we synchronize the title change with redraws, when it is completely unrelated?

**Comment by kchibisov** [comment]
I mean not exactly with redraw, but after we processed polled events, so it should be like done similar to this. 

https://github.com/alacritty/alacritty/blob/637c775a9997525dc56b2356b8171fd00ef5f0d2/alacritty/src/event.rs#L463

**Comment by kchibisov** [comment]
It was decided that DoS with title update is fine, so closing for now.
