### ISSUE TITLE
Changes to my alacritty.yml file not applying to Alacritty itself

### ISSUE THREAD

**Issue by geerizzle** [alacritty/alacritty#3516]
OS: Arch Linux x86_64
Version: alacritty 0.4.1
Linux/BSD: X11, running AwesomeWM 

So I`ve just downloaded alacritty and started to edit it`s configuration file. But when I saved the changes, alacritty didn`t apply any of them. I didn`t get any error outputs when i would save the file. My alacritty.yml file is located in `/home/$USER/.config/alacritty/alacritty.yml`

**Comment by kchibisov** [comment]
if you started alacritty without config, then placed config and chagned it, live reload won't work. Could you retest it.

**Comment by geerizzle** [comment]
That fixed it, thanks for your feedback.
