### ISSUE TITLE
[Wayland] Plasma + Wayland Decoration/Title Bar Has Gap Between Window Unless Maximized/Resized or Moved

### ISSUE THREAD

**Issue by CarbonChauvinist** [alacritty/alacritty#3517]
On Wayland+Plasma using iHD driver and iris Mesa driver when first opening alacritty there's a gap between the decoration/title bar and the window contents. See [image](https://i.imgur.com/KX3g0TA.png) for reference. 

This gap will remain until either the window is moved (click on title bar and drag window around) or the window is maximized and then resized (double click on title bar to maximize, double click on title bar again to resize to original window size).

I've confirmed this happens even with a brand new plasma user created and logged on with defaults of both plasma and alacritty. I've also confirmed the issue is NOT present when starting Plasma with X11 instead. I've also confirmed the issue is not present if run within Sway for instance.

### System

OS: Linux lap 5.5.11-arch1-1 #1 SMP PREEMPT Sun, 22 Mar 2020 16:33:15 +0000 x86_64 GNU/Linux
Version: alacritty 0.4.1
Linux/BSD: Wayland (Plasma)

Version
=======
KWin version: 5.18.3
Qt Version: 5.14.1
Qt compile version: 5.14.1
XCB compile version: 1.14

Operation Mode: Xwayland

Build Options
=============
KWIN_BUILD_DECORATIONS: yes
KWIN_BUILD_TABBOX: yes
KWIN_BUILD_ACTIVITIES: yes
HAVE_DRM: yes
HAVE_GBM: yes
HAVE_EGL_STREAMS: yes
HAVE_X11_XCB: yes
HAVE_EPOXY_GLX: yes
HAVE_WAYLAND_EGL: yes

X11
===
Vendor: The X.Org Foundation
Vendor Release: 12007000
Protocol Version/Revision: 11/0
SHAPE: yes; Version: 0x11
RANDR: yes; Version: 0x14
DAMAGE: yes; Version: 0x11
Composite: yes; Version: 0x4
RENDER: yes; Version: 0xb
XFIXES: yes; Version: 0x50
SYNC: yes; Version: 0x31
GLX: yes; Version: 0x0

Decoration
==========
Plugin: org.kde.breeze
Theme: 
Plugin recommends border size: None
Blur: 0
onAllDesktopsAvailable: false
alphaChannelSupported: true
closeOnDoubleClickOnMenu: false
decorationButtonsLeft: 0, 2
decorationButtonsRight: 6, 3, 4, 5
borderSize: 0
gridUnit: 10
font: Fira Sans,10,-1,5,50,0,0,0,0,0,Regular
smallSpacing: 2
largeSpacing: 10

Platform
==========
Name: DRM
Active: true
Atomic Mode Setting: true
Using EGL Streams: false

...

Screen 0:
---------
Name: 1203MLQ156M eDP-1-unknown
Geometry: 0,0,1920x1080
Scale: 1
Refresh Rate: 59.934

Compositing
===========
Compositing is active
Compositing Type: OpenGL
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 530 (Skylake GT2)
OpenGL version string: 4.6 (Core Profile) Mesa 19.3.4
OpenGL platform interface: EGL
OpenGL shading language version string: 4.60
Driver: Intel
GPU class: Unknown
OpenGL version: 4.6
GLSL version: 4.60
Mesa version: 19.3.4
Linux kernel version: 5.5.11
Direct rendering: Requires strict binding: no
GLSL shaders:  yes
Texture NPOT support:  yes
Virtual Machine:  no
OpenGL 2 Shaders are used
Painting blocks for vertical retrace:  no

### Logs
alacritty -vv
Created log file at "/tmp/Alacritty-131637.log"
[2020-03-25 10:42] [INFO] Welcome to Alacritty
[2020-03-25 10:42] [INFO] Configuration loaded from "/home/ghost/.config/alacritty/alacritty.yml"
[2020-03-25 10:42] [DEBUG] Estimated DPR: 1
[2020-03-25 10:42] [DEBUG] Estimated Cell Size: 10 x 19
[2020-03-25 10:42] [DEBUG] Estimated Dimensions: Some((1400.0, 570.0))
[2020-03-25 10:42] [INFO] Device pixel ratio: 1
[2020-03-25 10:42] [INFO] Initializing glyph cache...
[2020-03-25 10:42] [INFO] ... finished initializing glyph cache in 0.025834673s
[2020-03-25 10:42] [INFO] Estimated DPR correctly, skipping resize
[2020-03-25 10:42] [INFO] Cell Size: 10 x 19
[2020-03-25 10:42] [INFO] Padding: 0 x 0
[2020-03-25 10:42] [INFO] Width: 1400, Height: 570
[2020-03-25 10:42] [INFO] PTY Dimensions: Line(30) x Column(140)
[2020-03-25 10:42] [INFO] Initialisation complete
[2020-03-25 10:42] [DEBUG] Term::resize dimensions unchanged
[2020-03-25 10:42] [INFO] Width: 1400, Height: 572
[2020-03-25 10:43] [INFO] Goodbye
Deleted log file at "/tmp/Alacritty-131637.log"

**Comment by kchibisov** [comment]
Seems like plasma bug, since those are server side decorations.

**Comment by CarbonChauvinist** [comment]
Thanks will follow up there, it's strange because it only happens to alacritty on my box (at least that's the only application I've found/or use thus far)

**Comment by dnkl** [comment]
@kchibisov I recognize this from my own client. While I do believe it is a KDE bug, I was still able to make it work.

I'm afraid I don't remember exactly what I did to "fix" it. One of the things I remember having to do for KDE specifically was to **always** do a surface commit after ack:ing a configure event.

If that's not it, I _might_ be able to dig through my git history for what it was I did.

**Comment by dnkl** [comment]
Now I remember. Having instantiated, but not yet mapped sub-surfaces causes this behavior in KDE. You can either position the sub-surfaces so that they are completely encompassed by the parent surface, or you can instantiate them on-demand, just before mapping them.

**Comment by kchibisov** [comment]
Ugh, don't want to workaround this KDE bug tbh, unless they prove that they're right. Like we already have some amount of GNOME workarounds upstream, and I'm already tired of adding them. Maintaining them also doesn't make any sense.

**Comment by dnkl** [comment]
@kchibisov I feel you... Though I have to say that in this particular case, the code turned out better, in my opinion - in retro-respect it seems kind of stupid to instantiate e.g. the CSD sub-surfaces when in SSD mode :)

**Comment by dnkl** [comment]
> Ugh, don't want to workaround this KDE bug tbh, unless they prove that they're right.

This is **clearly** a KDE bug. The surfaces aren't mapped and if I remember correctly, they don't even have to be positioned outside the parent surface - just having them at `(0,0)` is enough (not _100%_ sure about that though...) KDE has **no** reason to add that empty space.

**Comment by kchibisov** [comment]
The problem is that you can trigger your decorations mode on the fly, so you'll need them at some point anyways. I can't do anything directly in alacritty, so it should be done in https://github.com/smithay/client-toolkit. Also code could look better for you, but it's subjective, setting up in them in a `frame` 'constructor' is nicer than doing it on demand If I remember SCTK correctly, since you should plumb a lot of stuff together, to which you won't have access later.

**Comment by dnkl** [comment]
@kchibisov Right, of course. I didn't mean to imply that alacritty, or its dependencies, should implement it.

Just that _I_ choose to implement it because I don't see it as a workaround in _my_ project, but as code improvement. I wouldn't have implemented it either if I had seen it as just a workaround.

**Comment by chrisduerr** [comment]
I don't see any reason to fix a KDE bug in all clients, rather than fixing it once in KDE.

If you want to add a workaround @kchibisov, feel free. But it seems like you agree that there's nothing Alacritty should do.
