### ISSUE TITLE
Modifier stuck after SpawnNewInstance

### ISSUE THREAD

**Issue by dotNomad** [alacritty/alacritty#3519]
On 0.4.1 I've noticed my modifier key is "stuck" after I do a SpawnNewInstance on macOS.

I'm using `- { key: N, mods: Command,  action: SpawnNewInstance }` and after using `Command+N` if I return to the original terminal the Command key is stuck. Meaning if I press only `N` another instance is created again. If I do a `Control+C` it returns to normal.

### System
OS: macOS
Version: 0.4.1

**Comment by cole-h** [comment]
Duplicate of https://github.com/alacritty/alacritty/issues/3188. This has been fixed for the next release (which should be soon-ish, considering we're in the release candidate phase).

**Comment by dotNomad** [comment]
@cole-h Darn didn't catch that in my searches. Thanks I'll go ahead and close this.
