### ISSUE TITLE
Frequent crashes on MacOS

### ISSUE THREAD

**Issue by burningTyger** [alacritty/alacritty#3533]
Alacritty constantly crashes after a while when used on MacOS Catalina. Don't know about earlier versions because I just started with Catalina. I use tmux and suspect it's connected. The crash is not directly reproducible but usually I have some scroll actions in tmux like ctrl-a and page up. Then some keys are not recognized and upon pressing q alacritty closes. It looks like alacritty switches modes to some underlying keyboard navigation because some keys don't type but return esc codes and thus q quits.

### System
macOS Catalina
v0.4.2 via homebrew

Which logs should I get and how?

Thank you very much for a great terminal software. It's highly appreciated!

**Comment by chrisduerr** [comment]
Are you certain you're running 0.4.2 and not 0.4.1? It sounds like https://github.com/alacritty/alacritty/issues/3188.

The cask for brew just got updated 4 hours ago, so if this is with 0.4.2 it sounds like it is quite easy to reproduce? Would you mind starting from CLI and checking if there is some output in stderr?

**Comment by burningTyger** [comment]
You're right. I updated my brew but forgot to run the upgrade for casks. It's on 0.4.1 still. Let me quickly upgrade and get back to you. Sounds very much like #3188. Forgot to mention the part where I switch windows.

**Comment by chrisduerr** [comment]
Closing as duplicate for now. Let me know if that doesn't fix it.
