### ISSUE TITLE
Transparency does not work unless set to 0 

### ISSUE THREAD

**Issue by nonetrix** [alacritty/alacritty#3539]
when I set transparency only 0 works when I go to 1 or higher it doesn't add transparency I'll put my dot files below feel free to roast them

Linux kubuntu 19.10 [kubuntu back ports installed]

alacritty 0.4.1

KDE 5.18.3 x11 

background_opacity: 30
colors:
  # Default colors
  primary:
    background: '0x1b182c'
    foreground: '0xcbe3e7'

  # Normal colors
  normal:
    black:   '0x100e23'
    red:     '0xff8080'
    green:   '0x95ffa4'
    yellow:  '0xffe9aa'
    blue:    '0x91ddff'
    magenta: '0xc991e1'
    cyan:    '0xaaffe4'
    white:   '0xcbe3e7'

  # Bright colors
  bright:
    black:   '0x565575'
    red:     '0xff5458'
    green:   '0x62d196'
    yellow:  '0xffb378'
    blue:    '0x65b2ff'
    magenta: '0x906cff'
    cyan:    '0x63f2f1'
    white:   '0xa6b3cc'
# font
font:
 size: 8

**Comment by cole-h** [comment]
From the [config](https://github.com/alacritty/alacritty/blob/master/alacritty.yml#L285):

```yaml
# Background opacity
#
# Window opacity as a floating point number from `0.0` to `1.0`.
# The value `0.0` is completely transparent and `1.0` is opaque.
```

If you want 30% opacity, try `0.3`.
