### ISSUE TITLE
Ability to increase terminal's width beyond window's width

### ISSUE THREAD

**Issue by Al-Caveman** [alacritty/alacritty#3542]
### Current behaviour
Currently, number of columns is only determined by window's width, and there is no way to increase the columns beyond window's limits.  

So, an alacritty terminal has as many columns that can fit the window, and any line longer than this, the line would get wrapped.

This is a fine behaviour in most cases.  But, it is a bad behaviour in some cases.  Here is an example:

1. Window can fit 200 text columns.
1. Alacritty automatically put 200 columns.
1. Application prints several very long lines.
1. You wish to compare those long lines by order.  E.g. first word in 1st line against first word in 2nd line, 2nd word against 2nd word, ...., 50th word against 50th word.  
1. Alacritty will wrap those long lines, causing extreme difficulty in comparing words by order across the wrapped lines.
1. Your monitor is not wide enough to use full screen to solve this problem for you.
1. So you end up somehow piping that long-lined text into an external app for convenient reading.

The problem with this approach is this:

* You will do extra work to have other windows open only to get those lines unwraped in.
* You will in most cases lose line colors (e.g. vim won't show those colors, unless you load a special vim syntax file).

So the current workflow is needlessly complex.

### Desired behaviour (feature request)
To keep the implementation simple and efficient, I propose a simple feature, that if added, it will solve all those problems, and should work neatly in vi mode as well.

Requested features:

* Add a way to manually set the number of columns, independent of window's width.  This way, I could for example set my columns number, to a large number, such as 500 or 1000 characters, irrespective of the window's width, which will eventually give me to unwrap all my lines.  It will work like `:set nowrap` in vim, but with upper bound for performance (maximum number of columns).
* Add ability to scroll horizontally by keyboard (without a scroll bar).  E.g. some command bindings to scroll the columns.

These features will extremely neatly complement the vi mode too.  E.g. with `:set termwidth 1000` you could effectively get the same effect as `:set nowrap` in vim, and browse around (e.g. scroll horizontally).

Huge usability benefits:

* Not needing to copy/pipe and start other apps.
* Integrates neatly with the vi mode..
* Not losing colors that are already rendered in Alacritty.
* Not affecting performance, since this simply increases number of columns whenever user asks for it.  It simply allows the user to decouple two concepts:
  * Window's width.
  * Quantity of columns.

### System
OS: **Linux**/BSD/macOS/Windows
Version: alacritty 0.4.2

And thanks for making Alacritty.  It's easily my best terminal by far.

**Comment by chrisduerr** [comment]
As discussed on IRC, there is no desire to add this.

**Comment by nixpulvis** [comment]
@Al-Caveman it sounds like you want to pipe you commands into `less -S`.
