### ISSUE TITLE
Is it possible to make alacritty default terminal on win10 ? 

### ISSUE THREAD

**Issue by Remonli** [alacritty/alacritty#3554]
Compare with Windows original terminal, alacritty is really fast and beautiful . So Is it possible 
to make alacritty default terminal on win10 ? 

I mean when you click powershell on "win+x", instead origin powershell, we can open alacritty
terminal.

Image File Execution Option does not suceed, as alacritty still need to run powershell , is there 
any other way?

I'm not sure if these question is suitable here but thank you anyway if someone  could answer it.

**Comment by chrisduerr** [comment]
> Image File Execution Option does not suceed, as alacritty still need to run powershell , is there
any other way?

What exactly do you mean by this?

Fundamentally when you open powershell, you'll always get powershell. I don't think there's any way around that and I doubt Microsoft has any plans to change that. But I don't ever use Windows, so I could be wrong.

This question seems mostly unrelated to Alacritty itself though, since I don't see what we would do ourselves to change anything here? We already try our best to offer a variety of options like launching through the right click menu.

**Comment by Remonli** [comment]
Image File Execution Options is a debug func of windows, with it , when you try to run a.exe , b.exe 
will run instead.

Alacritty is only terminal , powershell.exe still runs when we open a alacritty window, that's why IFEO
does not work in this case.

I'm asking for help if any one knows any other way to make alacritty default on windows.

**Comment by chrisduerr** [comment]
The problem is that powershell is both a terminal and a shell, that's why you can't simply do that.

Why do you want to start powershell just to run Alacritty though? It seems much easier to me to just start Alacritty?

**Comment by chrisduerr** [comment]
https://conemu.github.io/en/DefaultTerminal.html

This might have some interesting information that could lead you to a solution, but if you're looking for an official way, there is none.

If you want to look into that and find out how to do it, feel free to share your solution.

**Comment by HanslettTheDev** [comment]
Nobody is even answering the question asked by the OP
Sighs

**Comment by kchibisov** [comment]
The link answers it pretty clearly that it's not possible to do so, because it's integrated into windows stuff and the only way to achieve that is with hacks.

Only on Win 11 there's some cumbersome official way to achieve so, but not on any version before.

**Comment by Remonli** [comment]
Any details info of this ? I'm using latest windows11 24H2 26100.268.

> Only on Win 11 there's some cumbersome official way to achieve so, but not on any version before.

**Comment by j4james** [comment]
@kchibisov Just FYI, it's not only available on Windows 11. The default terminal functionality was added to Windows 10 in June 2023 (see https://github.com/microsoft/terminal/discussions/15505).

**Comment by Remonli** [comment]
@j4james  Looks like that only means windows terminal,not alacritty.

**Comment by j4james** [comment]
@Remonli Alacritty still needs to implement the COM interfaces that are required to make that work (that is tracked in issue #6036). I was just pointing out that it should work on Windows 10 as well as Windows 11, if Alacritty were ever to implement the functionality. kchibisov seemed to think it was a Windows 11 only feature.

**Comment by kchibisov** [comment]
I mean, they added it in 2023, so it's a _newish_ windows 10 feature...
