### ISSUE TITLE
Normal colors are picked for black background, instead of bright colors.

### ISSUE THREAD

**Issue by doragasu** [alacritty/alacritty#3556]
### System
OS: ArchLinux
Version: 0.4.2
Linux/BSD: sway (wayland)

I am using xterm colors, but with a brighter blue (dodger blue), with black background:

```# XTerm's default colors, but with DodgerBlue on the bright colors
colors:
   # Default colors
   primary:
     background: '0x000000'
     foreground: '0xffffff'

   # Normal colors
   normal:
     black:   '0x000000'
     red:     '0xcd0000'
     green:   '0x00cd00'
     yellow:  '0xcdcd00'
     blue:    '0x0000ee'
     magenta: '0xcd00cd'
     cyan:    '0x00cdcd'
     white:   '0xe5e5e5'

   # Bright colors
   bright:
     black:   '0x7f7f7f'
     red:     '0xff0000'
     green:   '0x00ff00'
     yellow:  '0xffff00'
     blue:    '0x1e90ff'
     magenta: '0xff00ff'
     cyan:    '0x00ffff'
     white:   '0xffffff'
```
Alacritty 0.4.1 picked the bright colors and everything was great. But recently it was updated to 0.4.2 and it is picking dark colors. I have confirmed this by downgrading to 0.4.1.

Is this intentional, or is there a bug here?

**Comment by kchibisov** [comment]
>Is this intentional, or is there a bug here?

You're not using bright colors, you're using bold normal colors, please read CHANGELOG for v0.4.2 and notice that you have `draw_bold_text_with_bright_colors: false` now, if you want bright use bright, not bold bright, if you want bold as bright use this setting set to `true`, like it was by default on v0.4.1.

**Comment by doragasu** [comment]
Thanks, and sorry for the noise.
