### ISSUE TITLE
provide a -list-keys command to show all keybindings

### ISSUE THREAD

**Issue by itagent** [alacritty/alacritty#3557]
I create a cheat sheet program, and I was wondering if it's possible to provide a command which lists all bound keys like `tmux list-keys` or `bindkey` in zsh including all default keybindings as well as the configured ones?

e.g. `alacritty --list-keys'

**Comment by chrisduerr** [comment]
Like `cat ~/.config/alacritty/alacritty.yml`? I don't see why we would need a separate command for that?

**Comment by itagent** [comment]
ok there are no additional keybindings. understood.

**Comment by nixpulvis** [comment]
It may be worth mentioning that some packages include our default `alacritty.yml` (for example in `/usr/share/doc/alacritty/example/alacritty.yml` on Arch). However, this file may be out of date or inaccurate depending on the exact version of Alacritty running.

The defaults + the user configuration gives the current mapping.

**Comment by YarekTyshchenko** [comment]
Shift+Control+U isn't listed anywhere. Is there a way to get all possible "actions" that can be bound with keybinds?

**Comment by zazaian** [comment]
> Like `cat ~/.config/alacritty/alacritty.yml`? I don't see why we would need a separate command for that?

@chrisduerr it would be helpful to easily understand what is already bound to existing keys in order to determine additional keybindings can be created non-destructively. Tmux, for example, has the list-keys command, which just prints out all of the keybindings that are active in the current session.

**Comment by zazaian** [comment]
@chrisduerr I think that's a fine solution. One quick word on the https://alacritty.org/config-alacritty-bindings.html page - the bindings might be easier to read if the columns are organized in accordance with how it would be executed on the keyboard. So something like `mods -> key -> mode -> action` or even `mode -> mods -> key -> action` may feel more intuitive to users who aren't already familiar with the bindings.
