### ISSUE TITLE
"bold" font did not take effect, why ?

### ISSUE THREAD

**Issue by colben** [alacritty/alacritty#3558]
### System

OS: Arch Linux with gtx 1050 ti
Version: alacritty 0.5.0-dev (13eb50de)
Linux: X11, Gnome 3.36

### Logs

Font/Terminal size:
```
Created log file at "/tmp/Alacritty-8308.log"
[2020-04-04 23:16:14.342636704] [INFO] Welcome to Alacritty
[2020-04-04 23:16:14.342828508] [INFO] Configuration loaded from "~/.config/alacritty/alacritty.yml"
[2020-04-04 23:16:14.366776135] [DEBUG] Estimated DPR: 1
[2020-04-04 23:16:14.366833435] [DEBUG] Estimated Cell Size: 11 x 26
[2020-04-04 23:16:14.366850935] [DEBUG] Estimated Dimensions: None
[2020-04-04 23:16:14.453452235] [INFO] Device pixel ratio: 1
[2020-04-04 23:16:14.454835565] [INFO] Initializing glyph cache...
[2020-04-04 23:16:14.461368559] [INFO] ... finished initializing glyph cache in 0.006517647s
[2020-04-04 23:16:14.461386448] [INFO] Cell Size: 11 x 26
[2020-04-04 23:16:14.461392790] [INFO] Padding: 0 x 0
[2020-04-04 23:16:14.461400547] [INFO] Width: 800, Height: 600
[2020-04-04 23:16:14.461777014] [INFO] PTY Dimensions: Line(23) x Column(72)
[2020-04-04 23:16:14.465132276] [INFO] Initialisation complete
[2020-04-04 23:16:14.465539720] [DEBUG] Term::resize dimensions unchanged
[2020-04-04 23:16:14.465607364] [INFO] Width: 800, Height: 600
[2020-04-04 23:16:34.068406974] [INFO] Goodbye
Deleted log file at "/tmp/Alacritty-8308.log"
```

### Config
~/.config/alacritty/alacritty.yml
```
env:
  TERM: xterm-256color

scrolling:
  history: 10000

font:
  normal:
    family: YaHei Consolas Hybrid
    style: Regular
  bold:
    family: YaHei Consolas Hybrid
    style: Bold
  italic:
    family: YaHei Consolas Hybrid
    style: Italic
  bold_italic:
    family: YaHei Consolas Hybrid
    style: Bold Italic
  size: 15.0

draw_bold_text_with_bright_colors: true

background_opacity: 1.0

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

key_bindings:
  - { key: F11, action: ToggleFullscreen }

colors:
  primary:
    background: '0x222222'
    foreground: '0xffffff'
    
    normal:
      black: '0x2e3436'
      red: '0xcc0000'
      green: '0x4e9a06'
      yellow: '0xc4a000'
      blue: '0x3465a4'
      magenta: '0x75507b'
      cyan: '0x06989a'
      white: '0xd3d7cf'

    bright:
      black: '0x555753'
      red: '0xef2929'
      green: '0x8ae234'
      yellow: '0xfce94f'
      blue: '0x729fcf'
      magenta: '0xad7fa8'
      cyan: '0x34e2e2'
      white: '0xeeeeec'
```

### Issue

"Bold", "Italic" and "Bold Italic" did not take effect in alacritty, why ?

**Comment by kchibisov** [comment]
What's your issue? You're not using any bold styles though.

**Comment by colben** [comment]
> What's your issue? You're not using any bold styles though.

I just did not finish describing my issue, here is "bold" configuration:
```
  bold:
    family: YaHei Consolas Hybrid
    style: Italic
```

**Comment by kchibisov** [comment]
Could you provide a screenshot from this 
```
echo -e "\e[0mhello\e[1mhello\e[0;3mhello\e[0;1;3mhello\e[0m"
```
and output from `fc-match -s "YaHei Consolas Hybrid:style=Bold"`?

**Comment by colben** [comment]
> Could you provide a screenshot from this
> 
> ```
> echo -e "\e[0mhello\e[1mhello\e[0;3mhello\e[0;1;3mhello\e[0m"
> ```
> 
> and output from `fc-match -s "YaHei Consolas Hybrid:style=Bold"`?

![2020-04-04_23-41](https://user-images.githubusercontent.com/7829126/78454920-c002be80-76cd-11ea-99c9-06965d8e724d.png)

**Comment by kchibisov** [comment]
You don't have bold font, nor italic and bold italic, for your font, so install them.

**Comment by colben** [comment]
> You don't have bold font, nor italic and bold italic, for your font, so install them.

The bold style of font "YaHei Consolas Hybrid" does not exist indeed, but gnome-terminal still can apply it, here is its screenshot:
![2020-04-05_06-15](https://user-images.githubusercontent.com/7829126/78462504-57cfcf00-7705-11ea-95ad-be113e949960.png)
In addition, gnome-tweak-tool spread out the bold and italic style of font "YaHei Consolas Hybird" :
![2020-04-05_06-25](https://user-images.githubusercontent.com/7829126/78462585-34595400-7706-11ea-8a73-44bbbc12087c.png)
"YaHei Consolas Hybrid" should not work at all with bold style, is there any thing can explain the behaviour of gnome-terminal ?
