### ISSUE TITLE
[Regression] Huge cursor is rendered under Crostini/ChromeOS

### ISSUE THREAD

**Issue by ava1ar** [alacritty/alacritty#3563]
### System

OS: Linux
Version: 0.4.2
Linux/BSD: Wayland

Since version 0.4.2 Alacritty renders huge cursor inside the application. Looks like it is related to some changes in cursor size calculations in 0.4.2. Issue is not reproducible in 0.4.1, so this is new version regression.

Attaching the screenshot. Will provide more details on request if needed.

![Screen](https://user-images.githubusercontent.com/6657308/78522405-5b159a00-779b-11ea-9d3f-c288e2598403.jpg)

**Comment by kchibisov** [comment]
Cursor is controlled by `XCURSOR_SIZE` env variable.

**Comment by ava1ar** [comment]
Looks like `env XCURSOR_SIZE=24 alacritty` works fine and fixes the issue. Interesting, that by default value is set to 48, but I didn't see other apps render huge cursor. Looks like apps are usually ignores the value? Looks like alacritty was ignoring it as well.
I think we can close the issue, don't think app can do something else here. Thanks!

**Comment by kchibisov** [comment]
>Looks like alacritty was ignoring it as well.

We were asked to stop ignoring it, since it's something common to control your cursor size on Wayland.
