### ISSUE TITLE
setab and setaf definitions in alacritty-direct produce incorrect output for 256-color values.

### ISSUE THREAD

**Issue by tmccombs** [alacritty/alacritty#3564]
### System

OS: Linux
Version: 0.4.2
Linux: Wayland

### Description
The terminfo entries for setaf and setab  assume that if the color value is greater than 7, it is a 24-bit color, and therefore produce blue values for any value that should be using 256color values. In particular the %F and %K prompt escapes in zsh  use these terminfo entries to generate the escape codes. This means that code (such as prompt themes) that is supposed to use 256color values, end up always being blue.
 
Zsh output with `TERM=alacrity-direct`
```
$ print  -P "%K{238}a%k" | tr '\033' E  
E[48;2;0;0;238maE[49m
```

Zsh output with `TERM=alacritty`
```
$ print -P "%K{238}a%k" | tr '\033' 'E' 
'E[48;5;238maE[49m
```

If I create a new terminfo file that is the same as alacritty-direct, but replace setaf and setab with the values used in the `alacritty` terminfo file, I get the same result as using just the `alacritty` terminfo file.

**Comment by chrisduerr** [comment]
I believe `alacritty-direct` should be have identical to `xterm-direct` when it comes to this?

If I remember correctly, we just took xterm's direct definition and rebased it on top of the `alacritty` terminfo.

**Comment by dnkl** [comment]
> I believe alacritty-direct should be have identical to xterm-direct when it comes to this?

@chrisduerr this is correct. Alacritty's `setaf` and `setab` definitions are identical to `xterm-256color` and `xterm-direct`.

@tmccombs my understanding is that the only assumption you can make about `setaf`/`setab` is for color index `0-7`. For example `tput setaf 238` prints `E[3238m` if `TERM=xterm`.

If you want to use any other color value than `0-7` you need to check the terminfo. For example `xterm-256color` has `colors#0x100` (i.e. 256).

For 24-bit colors, you should look for the `RGB` flag. Both `xterm-direct` and `alacritty-direct` has it.

**Comment by tmccombs** [comment]
> For 24-bit colors, you should look for the RGB flag. Both xterm-direct and alacritty-direct has it.

So all applications that use colors need to be aware of 24-bit color? This breaks existing applications which assume that if the colors attributes is 256 or greater it can use 8bit colors (such as zsh).

I guess this is more an issue with terminfo though.

**Comment by dnkl** [comment]
> So all applications that use colors need to be aware of 24-bit color? This breaks existing applications which assume that if the colors attributes is 256 or greater it can use 8bit colors (such as zsh).

As far as I understand, yes, that's correct. It probably would make more sense to check if `colors` is exactly 256 (for 8-bit colors). I'm not aware of any terminal that supports > 256 that isn't truecolor.

I personally use a 256-color terminfo by default, and explicitly set it to a `direct` variant when needed.

The problem is that if you construct a terminfo such that the first 256 entries map to the 256-color palette, you wouldn't be able to use any pure blue colors; you'd have to give either red or green at least the value 1.

With the current variant, you only loose the first 8 values of blue, not **all** of them.

**Comment by tmccombs** [comment]
the application has to do more than just check though. If it has an 8bit color and the terminal reports it wants a 24bit color, the application then has to lookup the corresponding 24bit color. 

Ideally I think there would be different capabilities, since the terminal does support both 8 bit and 24 bit colors, but it's probably too late for that.

Anyway, I don't think this is an issue with alacritty so I'll close it.
