### ISSUE TITLE
Cannot use Alacritty portable on Win10 with MSYS2

### ISSUE THREAD

**Issue by urbster1** [alacritty/alacritty#3566]
I'm trying to use alacritty with MSYS2 using the msys2_shell.cmd script, replacing mintty with alacritty and this worked fine on a Win7 x64 machine (although alacritty was installed with the .msi installer) but is not working on a Win10 x64 machine and fails with the following error.

### System

OS: Windows
Version:  alacritty 0.4.2 (f68de37)
Windows: WinPTY

### Logs

```
[2020-04-06 10:35:36.774246800] [INFO] Welcome to Alacritty
[2020-04-06 10:35:36.803135100] [INFO] No configuration file found
[2020-04-06 10:35:37.099343400] [INFO] Device pixel ratio: 1
[2020-04-06 10:35:37.162174800] [INFO] Initializing glyph cache...
[2020-04-06 10:35:37.204062600] [INFO] ... finished initializing glyph cache in 0.041202068s
[2020-04-06 10:35:37.205060400] [INFO] Cell Size: 8 x 17
[2020-04-06 10:35:37.205060400] [INFO] Padding: 0 x 0
[2020-04-06 10:35:37.206058200] [INFO] Width: 1024, Height: 768
[2020-04-06 10:35:37.304794300] [INFO] PTY Dimensions: Line(45) x Column(128)
[2020-04-06 10:35:37.305795600] [INFO] Using WinPTY backend
panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: SpawnCreateProcessFailed, message: "CreateProcess failed (error code 2)" }', C:\Users\travis\build\alacritty\alacritty\alacritty_terminal\src\tty\windows\winpty.rs:69:5
panicked at 'buffering RedrawRequested event', <::std::macros::panic macros>:2:4
thread panicked while processing panic. aborting.
```

Trying to run `alacritty -e ".\usr\bin\bash.exe --login -i"` does bring up alacritty with a bash prompt but running any command fails with `Segmentation fault` for an unknown reason.

However using it to run Powershell by default works without issue.

**Comment by urbster1** [comment]
It appears maybe I was too hasty in saying this works in Win7 x64 - running the same batch file now throws
```panicked at 'assertion failed: hr == 0', C:\Users\travis\.cargo\registry\src\github.com-1ecc6299db9ec823\dwrote-0.9.0\src\font_collection.rs:57:13```

**Comment by chrisduerr** [comment]
Does ConPTY work?

**Comment by urbster1** [comment]
No, ConPTY doesn't seem to be found at all on this machine - alacritty only
seems to be able to use winpty.

**Comment by chrisduerr** [comment]
Which version of Windows do you run? It sounds severely outdated.

**Comment by urbster1** [comment]
Windows 10 Pro Version 1803
Let me know if more information is needed.

**Comment by chrisduerr** [comment]
Windows 10 Pro 1803 went EOL November 12, 2019. Please update your system.

**Comment by urbster1** [comment]
This machine is managed by system administrators, I don't have permissions
to update it. That's why I'm using the portable version.

**Comment by chrisduerr** [comment]
> This machine is managed by system administrators

Not very competent ones apparently, assuming it's actually Windows 10 Pro and not Enterprise.

Do you have the winpty executable in the same directory as Alacritty?

**Comment by urbster1** [comment]
They are not competent at all unfortunately. The winpty-agent executable is
in the same directory as alacritty, yes.

**Comment by chrisduerr** [comment]
Oh, looking at your issue again it seems like it cannot execute the default shell, which should be just `powershell.exe`.

So that's why it's starting when using the `-e` command option. What happens when you run `alacritty -e cmd`, does that produce a working shell?

**Comment by urbster1** [comment]
Yes, I get a command prompt in alacritty with -e cmd.

**Comment by chrisduerr** [comment]
Sounds like things are working fine then?

**Comment by urbster1** [comment]
They work fine with cmd but not with the MSYS bash.

**Comment by chrisduerr** [comment]
@urbster1 What happens when you start bash from cmd?

**Comment by urbster1** [comment]
The bash prompt opens in the command prompt but every command fails with `Segmentation fault`.

**Comment by urbster1** [comment]
I'm wondering if the Segfault issue is related to this one: https://github.com/git-for-windows/git/issues/1291

**Comment by chrisduerr** [comment]
Have you tried running bash in its own terminal, does that work?

**Comment by urbster1** [comment]
bash works in mintty and in conemu, those are the terminals that work.

**Comment by chrisduerr** [comment]
So it doesn't work in cmd, powershell or by executing bash for Windows directly?

**Comment by urbster1** [comment]
that's correct

**Comment by chrisduerr** [comment]
Then this isn't an Alacritty issue.

I'd probably assume that this is a git for windows/msys2 problem. Though reporting it to them likely isn't going to be super successful either since I'd assume this is fixed by a Windows update. So that's really the only thing I can recommend.

**Comment by urbster1** [comment]
ok! Thanks for your help!
