### ISSUE TITLE
There may be a terminal that is transparent but darker

### ISSUE THREAD

**Issue by zdmgmail** [alacritty/alacritty#3567]
I use alacritty in i3wm

when I open two or more terminal , may be a term more darker, may be not 

![2](https://user-images.githubusercontent.com/50515839/78615349-db272700-78a3-11ea-9cdc-c6f7930a23a0.png)

if a terminal more darker , I close it then reopen it, may be recover

![1](https://user-images.githubusercontent.com/50515839/78615363-e4b08f00-78a3-11ea-8f78-fff196b78b6a.png)

```
~ » alacritty --version                                                                                                                                               zdm@ar
alacritty 0.4.2
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~ » i3 --version                                                                                                                                                      zdm@ar
i3 version 4.18 (2020-02-18) © 2009 Michael Stapelberg and contributors
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~ » uname -a                                                                                                                                                          zdm@ar
Linux ar 5.5.13-arch2-1 #1 SMP PREEMPT Mon, 30 Mar 2020 20:42:41 +0000 x86_64 GNU/Linux
```

Another example
![3](https://user-images.githubusercontent.com/50515839/78615512-54267e80-78a4-11ea-81c0-698218e92267.png)
![4](https://user-images.githubusercontent.com/50515839/78615520-5a1c5f80-78a4-11ea-8c4b-61ed33d9cf34.png)

**Comment by zdmgmail** [comment]
I hope they always have the same transparency, is there any way ?

**Comment by kchibisov** [comment]
Seems like your compositor bug. We just set a fixed alpha for a background, which you specify in your config, everything else is done in compositor.

**Comment by chrisduerr** [comment]
@zdmgmail Which compositor are you running and what configuration do you use?

**Comment by zdmgmail** [comment]
> @zdmgmail Which compositor are you running and what configuration do you use?

In i3 config, 
exec --no-startup-id xcompmgr -c

**Comment by chrisduerr** [comment]
Could you try out something like picom/compton, just because it's known to work?

**Comment by zdmgmail** [comment]
> Could you try out something like picom/compton, just because it's known to work?

Ok, thanks

**Comment by zdmgmail** [comment]
ggg
