### ISSUE TITLE
Padding settings are ignored

### ISSUE THREAD

**Issue by NightH4nter** [alacritty/alacritty#3568]
OS: ArchLinux;
Alacritty version: 0.4.2;
X11, i3-gaps, picom.

Alacritty windows looks exactly the same with different padding settings both with and without dynamic padding. Is that an issue with tiling window managers? 
Padding 100, dynamic padding off:
![2020-04-07-103953_1440x900_scrot](https://user-images.githubusercontent.com/31319604/78637791-251c0700-78bc-11ea-9870-1c350b0da93b.png)
Padding 0, dynamic padding off:
![2020-04-07-104119_1440x900_scrot](https://user-images.githubusercontent.com/31319604/78637882-54cb0f00-78bc-11ea-972a-1fc14f09fde0.png)
Padding 100, dynamic padding on:
![2020-04-07-104301_1440x900_scrot](https://user-images.githubusercontent.com/31319604/78638070-af646b00-78bc-11ea-936a-46b73a08b3c2.png)
Padding 0, dynamic padding on:
![2020-04-07-104246_1440x900_scrot](https://user-images.githubusercontent.com/31319604/78638091-b9866980-78bc-11ea-80f7-f723722e2668.png)
Note: I **did** restart Alacritty every time I changed settings.

**Comment by siiptuo** [comment]
These settings should be nested inside of `window`. Change line `#window:` to `window:` and don't remove the indentation:

    window:
      padding:
        x: 4
        y: 4
      dynamic_padding: true

**Comment by NightH4nter** [comment]
> These settings should be nested inside of `window`. Change line `#window:` to `window:` and don't remove the indentation:
> 
> ```
> window:
>   padding:
>     x: 4
>     y: 4
>   dynamic_padding: true
> ```
> 
> Related to #3467.

It worked, thanks.
