### ISSUE TITLE
Command execution(-e) fails with whitespace

### ISSUE THREAD

**Issue by bahua** [alacritty/alacritty#3580]
When a command to execute has whitespace in it-- like for example if the command has arguments --then alacritty fails with a error, saying the string that includes the whitespace is not a file. Trying single and double ticks doesn't make any difference. How am I supposed to execute commands with alacritty's "-e" option if they have whitespace in them?

### System

OS: Arch Linux x86_64
Version: alacritty 0.4.2
Linux/BSD: X11 with bspwm

### Logs

Crashes: 
[2020-04-12 13:56:51.206123407] [ERROR] Failed to spawn command 'ps -ef; read': No such file or directory (os error 2)
Font/Terminal size: Fira Mono Medium size: 11.0(default)

**Comment by kchibisov** [comment]
alacritty -e bash -c 'ps -ef; read'.
