### ISSUE TITLE
tmux weird character showing 

### ISSUE THREAD

**Issue by w93163red** [alacritty/alacritty#3581]
Please see the following pic.
![image](https://user-images.githubusercontent.com/7308728/79083926-16d84b80-7cff-11ea-8705-9d1ae0d78b15.png)

### System

OS: macOS
Version: 0.4.2

**Comment by kchibisov** [comment]
could you try to run `tmux -u`?

**Comment by w93163red** [comment]
> could you try to run `tmux -u`?

It is the same:
![image](https://user-images.githubusercontent.com/7308728/79089384-fb2b7000-7d13-11ea-8e11-6124ce0b2648.png)

**Comment by kchibisov** [comment]
Could you try run tmux with `LC_ALL=en_US.UTF-8`?

**Comment by w93163red** [comment]
After I ran `tmux kill-server` the issue is gone.
