### ISSUE TITLE
Reflow not wrapping cursor correctly

### ISSUE THREAD

**Issue by chrisduerr** [alacritty/alacritty#3584]
When the grid width is changed and content reflows, the cursor should reflow with the content. This is necessary to make sure that writes will be correct when occuring during a resize.

Repro:
 * Run `echo -n "[LONG LINE]" && sleep 10 && echo -n "xxx"`
 * Shrink terminal to wrap the long line, before sleep is done
   -> The `xxx` is written at the wrong location, it should be right after `[LONG LINE]`

**Comment by kchibisov** [comment]
yeah, seems like cursor position is indeed broken. Just reflowing during the following command results in 'spaces' between output, however it should be contiguous line.
```
for i in `seq 0 10000`; do echo -ne "1234567890"; sleep 0.1 ; done
```
