### ISSUE TITLE
Alacritty 256 color issue on xfce DE

### ISSUE THREAD

**Issue by shubham-cpp** [alacritty/alacritty#3585]
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

OS: Linux/BSD/macOS/Windows
Version: `alacritty --version` output
Linux/BSD: X11/Wayland, DE or Compositor and WM
Windows: WinPTY/ConPTY (see `alacritty -v` output)

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

Alacritty is on using 16-bit colors instead of 256

**Comment by chrisduerr** [comment]
How exactly are you testing this? Could you provide more information please?

**Comment by shubham-cpp** [comment]
Dont worry solved it. Thank for the reply though
