### ISSUE TITLE
Cannot use ctrl + / in alacritty

### ISSUE THREAD

**Issue by w93163red** [alacritty/alacritty#3586]
Cannot use ctrl + / in alacrity. Is there any way to enable it? I use ctrl+/ to comment/uncomment out the code in Vim.

in my vimrc, I set the following value to toggle comment which mapped to ctrl + /:
```
nmap <C-_>   <Plug>NERDCommenterToggle
vmap <C-_>   <Plug>NERDCommenterToggle<CR>gv
```
Could I set the keymapping on the alacritty setting file to match it?
### System

OS: macOS
Version: 0.4.2

**Comment by chrisduerr** [comment]
What do you get when pressing <kbd>ctrl</kbd>+<kbd>v</kbd> -> <kbd>ctrl</kbd>+<kbd>/</kbd>?

**Comment by w93163red** [comment]
> What do you get when pressing ctrl+v -> ctrl+/?

You mean on Vim? `ctrl`+`v` -> visual-block
ctrl+/  -> nothing

**Comment by chrisduerr** [comment]
No, I mean in your shell.

**Comment by w93163red** [comment]
On my shell? ctrl+v gets nothing.

**Comment by chrisduerr** [comment]
Not ctrl+v, <kbd>ctrl</kbd>+<kbd>v</kbd> -> <kbd>ctrl</kbd>+<kbd>/</kbd>

**Comment by w93163red** [comment]
Just /

**Comment by chrisduerr** [comment]
Can you reproduce this with an empty configuration file?

I'll have to test this myself on macOs, but it should report `^_`, not `/`.

**Comment by w93163red** [comment]
> Can you reproduce this with an empty configuration file?
> 
> I'll have to test this myself on macOs, but it should report `^_`, not `/`.

On my mac, it shows nothing

**Comment by chrisduerr** [comment]
> On my mac, it shows nothing

But you just said:

> Just /

So what does that refer to?

**Comment by w93163red** [comment]
When I have the configuration file, it shows `/`.
When I remove the configuration file, it shows nothing.

**Comment by w93163red** [comment]
ctrl+v -> ctrl+/

means ctrl+v then ctrl+/ ?

**Comment by chrisduerr** [comment]
> ctrl+v -> ctrl+/
>
> means ctrl+v then ctrl+/ ?

Correct. This is usually how you get a shell to print the raw character it receives. So <kbd>esc</kbd> would for example receive `^[`, since that's the control character for escape which is used in all escape sequences.

So <kbd>ctrl</kbd>+<kbd>/</kbd> should show `^_`, since that's the default raw value for that key.

**Comment by w93163red** [comment]
Is it related to zsh?

Christian Duerr <notifications@github.com> 于2020年4月13日周一 下午8:25写道：

**Comment by w93163red** [comment]
It works for esc key. Not for ctrl + /.
I used zsh.

**Comment by kchibisov** [comment]
Do `showkey -a` and type your binding.

**Comment by kchibisov** [comment]
nvm, I forgot that macOS doesn't have  `showkey`. I've tested macOS and it seems like we're not getting `ReceivedCharacter` events, when pressing `Ctrl + /`. You can add this binding yourself for now.

```
- { key: Slash,   mods: Control,       chars: "\x1f"                 }
```

**Comment by w93163red** [comment]
> nvm, I forgot that macOS doesn't have `showkey`. I've tested macOS and it seems like we're not getting `ReceivedCharacter` events, when pressing `Ctrl + /`. You can add this binding yourself for now.
> 
> ```
> - { key: Slash,   mods: Control,       chars: "\x1f"                 }
> ```

![image](https://user-images.githubusercontent.com/7308728/79181687-f8e01900-7dda-11ea-9801-b94c8da9ae64.png)

**Comment by kchibisov** [comment]
How did you add it? you should add it in `key_bindings` section. If you have any problems share your bindings section.

**Comment by w93163red** [comment]
My bad. I just realized that I did not uncomment out the key_binding section

**Comment by kchibisov** [comment]
it was likely a duplicate of #1359

**Comment by lroolle** [comment]
> > nvm, I forgot that macOS doesn't have `showkey`. I've tested macOS and it seems like we're not getting `ReceivedCharacter` events, when pressing `Ctrl + /`. You can add this binding yourself for now.
> > ```
> > - { key: Slash,   mods: Control,       chars: "\x1f"                 }
> > ```
> 
> ![image](https://user-images.githubusercontent.com/7308728/79181687-f8e01900-7dda-11ea-9801-b94c8da9ae64.png)

Work for me!

**Comment by wusitee** [comment]
THX, it just works on windows.

**Comment by Lengdrich** [comment]
> nvm, I forgot that macOS doesn't have `showkey`. I've tested macOS and it seems like we're not getting `ReceivedCharacter` events, when pressing `Ctrl + /`. You can add this binding yourself for now.
> 
> ```
> - { key: Slash,   mods: Control,       chars: "\x1f"                 }
> ```

in `alacritty.toml` file can use:
```toml
[keyboard]
bindings = [
  { key = "Slash", mods = "Control", chars = "\u001f" }
]
```
