### ISSUE TITLE
panicked at 'buffering RedrawRequested event'

### ISSUE THREAD

**Issue by Ryan1729** [alacritty/alacritty#3590]
Immediately at startup an error alert sound is triggered. The interior of the `alacritty` window is pure white and the whole program crashes after a second or two, printing this message if ran from another terminal:
```
panicked at 'buffering RedrawRequested event', <::std::macros::panic macros>:2:4
panicked at 'buffering RedrawRequested event', <::std::macros::panic macros>:2:4
thread panicked while processing panic. aborting.
```

Rampant speculation on my part, but possibly an upstream problem like in [this issue](https://github.com/alacritty/alacritty/issues/3177)?

### System

OS: Windows 10 Pro 1909
Version: alacritty 0.4.2 (f68de37)
Windows: WinPTY

### Logs
`alacritty -vvv` outputs the following:
```
Created log file at "C:\Users\Ryan\AppData\Local\Temp\Alacritty-6876.log"
[2020-04-14 01:20:29.519560500] [INFO] Welcome to Alacritty
[2020-04-14 01:20:29.520565700] [INFO] Configuration loaded from "C:\Users\Ryan\AppData\Roaming\alacritty\alacritty.yml"
[2020-04-14 01:20:29.523548800] [DEBUG] Estimated DPR: 1
[2020-04-14 01:20:29.523548800] [DEBUG] Estimated Cell Size: 8 x 17
[2020-04-14 01:20:29.523548800] [DEBUG] Estimated Dimensions: None
[2020-04-14 01:20:29.872355600] [INFO] Device pixel ratio: 1
[2020-04-14 01:20:29.878352300] [INFO] Initializing glyph cache...
[2020-04-14 01:20:29.879716400] [INFO] ... finished initializing glyph cache in 0.0011997s
[2020-04-14 01:20:29.880133300] [INFO] Cell Size: 8 x 17
[2020-04-14 01:20:29.884660500] [INFO] Padding: 0 x 0
[2020-04-14 01:20:29.885668600] [INFO] Width: 1024, Height: 768
panicked at 'buffering RedrawRequested event', <::std::macros::panic macros>:2:4
panicked at 'buffering RedrawRequested event', <::std::macros::panic macros>:2:4
thread panicked while processing panic. aborting.
```

**Comment by Ryan1729** [comment]
This also happens with `alacritty 0.4.2-rc1 (4883c41)` but not with `alacritty 0.4.1 (4d9253b)`.

**Comment by chrisduerr** [comment]
A panic during a panic sounds like an extremely severe issue.

You're not running out of memory or anything, right? Could you provide some more information about your system's hardware (memory/GPU/CPU/GPU driver/...)?

**Comment by Ryan1729** [comment]
If I close all other applications, giving me plenty of memory then the crash still happens, and if I run the Task Manager at the same time, the memory graph does not rapidly spike when the crash happens.

I have two monitors, one of which is driven by a NVIDIA GeForce GTX 960 and the other one is driven by the internal graphics card, an Intel(R) HD Graphics 4600. I've now tried changing the primary monitor, so when I start Alacritty it uses the other monitor initially, and it still crashes with the same message.

According to the windows device manager, the NVIDIA card is using driver version 26.21.14.3200 and the Intel GPU is using driver version 20.19.15.4624. But the NVIDIA control panel says the driver version is 432.00. The device manager also lists 4 CPU cores that all say "Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz"

**Comment by chrisduerr** [comment]
@Ryan1729 Does it work when you disconnect one of those monitors, so you're not using two GPUs at the same time?

I've also gone ahead and reported this upstream, since it cannot be fixed in Alacritty directly:

https://github.com/rust-windowing/winit/issues/1535

**Comment by Ryan1729** [comment]
I have just now tried disconnecting the each monitor in turn.
I was able to reproduce the panic with either of the monitors disconnected.

**Comment by zerols** [comment]
> I have just now tried disconnecting the each monitor in turn.
> I was able to reproduce the panic with either of the monitors disconnected.

i see the same , how did you solve

**Comment by r00ster91** [comment]
I have the same issue with ConPTY.

**Comment by bernastoc** [comment]
I'm seeing this crash on my desktop (discrete Nvidia GPU), but not on my laptop (thinkpad carbon gen7, intel integrated GPU). I'm only using one display in each case.

**Comment by chrisduerr** [comment]
This has been fixed on the latest master.

**Comment by Ryan1729** [comment]
I just got around to checking this and I can confirm that 0.4.3 rc1 does not have this issue on my setup. Great!
