### ISSUE TITLE
Alacritty can not show current path in window title when folder contain some characters

### ISSUE THREAD

**Issue by Kzinux** [alacritty/alacritty#3591]
1. Open alacritty and mkdir a folder named "本".
2. Change path to new folder 本.
3. Titlebar doesn't show current path, instead  it shows 未命名窗口(unamed window).
![1](https://user-images.githubusercontent.com/7030257/79199317-689be580-7e67-11ea-962e-d20737638139.png)
Alacritty can show path in window title when folder name changes to other Chinese character like "成".
![2](https://user-images.githubusercontent.com/7030257/79199846-232be800-7e68-11ea-8173-b3682e0d8744.png)
"本" and "成" are Chinese characters, and they are all in common use. 
And i tried xterm, it can show both two path correctly.

### System

OS: archlinux
Version: 0.4.2
Linux/BSD: X11, Openbox

**Comment by chrisduerr** [comment]
If you run `echo -e "\e]2;本\x9c" && sleep infinity`, does that work?

**Comment by Kzinux** [comment]
> If you run `echo -e "\e]2;本\x9c" && sleep infinity`, does that work?

Alacritty screenshot after run this command.
![3](https://user-images.githubusercontent.com/7030257/79283472-8bbba900-7eea-11ea-8de0-0dfede1ff362.png)

**Comment by chrisduerr** [comment]
Okay, so that means it's either a limitation in your window manager, or one set by winit.

I'd assume running `alacritty --title "本"` also doesn't work then?

Could you test if it is possible to set your window title to this character in another application?

**Comment by Kzinux** [comment]
After i run `alacritty --title "本"` in alacritty, it open another alacritty window with title 本.
![4](https://user-images.githubusercontent.com/7030257/79284358-fa9a0180-7eec-11ea-8a32-ec1275026252.png)
Other application like xterm and firefox can show 本 in window title.
![5](https://user-images.githubusercontent.com/7030257/79284467-51074000-7eed-11ea-8c4e-a541c457575c.png)

**Comment by chrisduerr** [comment]
> After i run alacritty --title "本" in alacritty, it open another alacritty window with title 本.

Huh, that's kinda interesting. There might be some difference between setting and updating the title.

Just to make absolutely sure if this is in Alacritty or one of its depedencies, could you run the following command to start Alacritty (without --title):

```
alacritty -vvv | grep "Setting title to"
```

That should log all attempts to change the title to stdout. I'm curious if it contains the correct title.

**Comment by Kzinux** [comment]
Screenshot after running `alacritty -vvv | grep "Setting title to"` in alacritty
![7](https://user-images.githubusercontent.com/7030257/79286362-eb1db700-7ef2-11ea-9bd6-016075271cd1.png)
.

**Comment by chrisduerr** [comment]
Great bug, thanks for finding that!

Turns out this unicode symbol actually contains the String Terminator byte (`\x9c`), which Alacritty interpreted as a terminator for the OSC escape sequence.

Since the C1 String Terminator is not used by any application I'm aware of, I've removed support for terminating OSCs using it, fixing this bug: https://github.com/alacritty/vte/pull/53.

**Comment by Kzinux** [comment]
I am happy that I could help.
Thank you for your work.
