### ISSUE TITLE
Is there a way to specify fallback font on Linux?

### ISSUE THREAD

**Issue by karambaq** [alacritty/alacritty#3593]
I'm using font that doesn't support Cyrillic symbols, on the gnome-terminal it uses a fallback font that I specified in fontconfig, in alacritty don't.

```
$ fc-match -s 'Operator Mono:style=Book:pixelsize=12'
Operator Mono Book Regular.otf: "Operator Mono" "Book"
CascadiaPL.ttf: "Cascadia Code PL" "Regular"
LiberationSans-Regular.ttf: "Liberation Sans" "Regular"
LiberationSans-Regular.ttf: "Liberation Sans" "Regular"
DejaVuSans.ttf: "DejaVu Sans" "Book"
DejaVuSans-Bold.ttf: "DejaVu Sans" "Bold"
```

Screenshot: 
![image](https://user-images.githubusercontent.com/14233969/79336008-a6624200-7f2b-11ea-9886-88c44f90ce57.png)

How can I fix it?

**Comment by karambaq** [comment]
@kchibisov 
```
$ alacritty --version
alacritty 0.4.1```

**Comment by kchibisov** [comment]
Try `v0.4.2` it should be fixed on it.

**Comment by karambaq** [comment]
@kchibisov Thanks, it works now.
