### ISSUE TITLE
Question: how match terminal colors?

### ISSUE THREAD

**Issue by zer09** [alacritty/alacritty#3594]
Hello just started alacritty now after watching `distrotube` video. I just got single concern about how to match the colors of my directory listing like on my gnome terminal. It was just a default color with a dark background.

![Screenshot from 2020-04-15 21-01-14](https://user-images.githubusercontent.com/780780/79341820-f4446d80-7f5e-11ea-9949-0e479dbb91f8.png)

The gnome terminal colors is just a little bit on darker side, I like that I can easily distinguish the directory from the files.

### System

OS: Pop-OS
Version: alacritty 0.4.1
Linux/BSD: X11 GNOME 3.34.2

**Comment by kchibisov** [comment]
Try toggling
```
draw_bold_text_with_bright_colors: false
```

**Comment by zer09** [comment]
@kchibisov sorry to bother, but setting `draw_bold_text_with_bright_colors` to `false` or `true` renders the same result.

**Comment by chrisduerr** [comment]
@zer09 If you just use the default colorscheme in both terminal emulators, the colors will be different. There's no standard for default terminal colorscheme.

**Comment by kchibisov** [comment]
Have you configured the same colors in both terminals? I've just looked at your picture and had a feeling that one is just a bright version of the other, because of this setting, since all characters in alacritty were bold.

**Comment by zer09** [comment]
> Have you configured the same colors in both terminals? I've just looked at your picture and had a feeling that one is just a bright version of the other, because of this setting, since all characters in alacritty were bold.

No, but I did try to uncomment the colors section on the config, but I observe there is no changes to the rendered colors.

**Comment by kchibisov** [comment]
Those colors are defaults we're using, you should define your own to match your gnome.

**Comment by zer09** [comment]
@kchibisov Thanks! I got it working, I did copy the color palette gnome terminal preference. and set to `normal colors` and `bright colors`. BTW last question what `Dim colors` do? I mean when or where they are applied? Because there is no dim colors on gnome terminal setting.

**Comment by kchibisov** [comment]
when app requested a dim color. e.g. `echo -e "\e[31;2mRED`, 31 - red, and 2 - dim.
