### ISSUE TITLE
Add keybindings for switching windows decorations on or off.

### ISSUE THREAD

**Issue by ghuls** [alacritty/alacritty#3596]
It would be nice to be able to specify keybindings for switching windows decoration on or off.

In my alacritty config file I have `decorations: none` which is fine by default as I use gnomesome tiling window manager Gnome extension, were I can easily create new terminals with `Command+Return`. But once in a while I want to have a floating alacritty terminal window that I can resize. As far as I can tell there is no command line option or keybinding to launch/change an existing alacritty terminal window with `decorations: full` for that instance.

I have an ugly workaround to reenable window decorations by running `enable_decorations` in that terminal.

```
disable_decorations () {
    xprop \
        -id $(xdotool getactivewindow) \
        -f _MOTIF_WM_HINTS 32c \
        -set _MOTIF_WM_HINTS "0x2, 0x0, 0x0, 0x0, 0x0"
}

enable_decorations () {
    xprop \
        -id $(xdotool getactivewindow) \
        -f _MOTIF_WM_HINTS 32c \
        -set _MOTIF_WM_HINTS "0x2, 0x0, 0x1, 0x0, 0x0"
}
```

### System

OS: Linux
Version: alacritty 0.5.0-dev (ab2db49)
Linux/BSD: X11, Gnome with gnomesome tiling window manager extension

**Comment by chrisduerr** [comment]
> But once in a while I want to have a floating alacritty terminal window that I can resize.

This sounds like the only reason why you want this to exist, is because your window manager doesn't actually seem to support the way you're using it? At least I don't see why you wouldn't be able to resize a window without decorations.

**Comment by kchibisov** [comment]
I'm not sure that we need such things, I feel like it should be done on wm level and not in alacritty.

**Comment by pejaham** [comment]
The default Gnome gdm keybinding to resize a window is ALT-F8. After hitting the shortcut you can resize the window either with the cursor keys or the mouse - holding SHIFT increases the increments. You can also move a window by SUPER-Dragging (not just on the title bar). Just tried both methods with Alacritty.
