### ISSUE TITLE
Question: How to disable font antialias in config?

### ISSUE THREAD

**Issue by miguelmota** [alacritty/alacritty#3598]
On left side is konsole (looks vivid), on right is alacrity (looks blurry) using same font. Can someone point me on an example of how to disable font antialiasing in config file? thanks

![Screenshot from 2020-04-16 13-11-45](https://user-images.githubusercontent.com/168240/79502011-dc62fd00-7fe3-11ea-9022-df82302e8423.png)

**Comment by chrisduerr** [comment]
Alacritty does not allow setting font rendering properties in Alacritty. Instead it relies on your system configuration.

If you want to change the way Alacritty renders text, you should change your system configuration.

See #957 for the corresponding "feature request".

**Comment by miguelmota** [comment]
If anyone is wondering how to turn off antialiases in Arch linux, edit or create the file `/etc/fonts/local.conf` and have the following rules:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
   <match target="pattern">
      <test qual="any" name="family">
         <string>Source Code Pro</string>
      </test>
      <edit name="antialias" mode="assign">
         <bool>false</bool>
      </edit>
   </match>
</fontconfig>
```

Just make sure to change the font name to the font you're using in alacritty.
