### ISSUE TITLE
[Windows] Setting 'decorations: none' disables ability to move window

### ISSUE THREAD

**Issue by jammehcow** [alacritty/alacritty#3603]
### System

OS: Windows 10
Version: `alacritty 0.4.2 (f68de37)`
Windows: ConPTY

### Logs

Crashes: None
Font/Terminal size: 1220x700 / Line(40) x Column(150)
Keyboard and bindings: default

### Description

When changing the `decorations` option in the config to `decorations: none` the window cannot be moved around the screen. This means you cannot drag any part of the window to move it, nor Shift + Right Click on the taskbar icon and use the move functionality.

**Comment by jammehcow** [comment]
Seems to have been a one-off. Closing.

**Comment by Sezaan** [comment]
Hey, what is the solution for this??

**Comment by n1ghtmare** [comment]
I'm having the same issue, is there any solution? Can we re-open this?

**Comment by brymer-meneses** [comment]
I'm also having the same issue.

**Comment by jammehcow** [comment]
The original issue was the built-in Windows move function not working. Turned out to be an issue in Win 10 at the time and was resolved in a later update.

If you're on Windows 10:
 - Right click on the app icon in the task bar
 - Click "move"
 - Use the arrow keys to move it

As for *nix it depends on your DE. 

Will not re-open, hope this helps :)
