### ISSUE TITLE
how to make alacritty part autocomplete the file name like cmder on windows? 

### ISSUE THREAD

**Issue by woshichuanqilz** [alacritty/alacritty#3604]
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

OS: Windows
Version: alacritty 0.4.2 (f68de37)

### 
When I use `cmder` is this situation: 
3 files in current folder names: 
> demo_1.py demo_2.py demo_3.py

Then I type `de` in cmder 
then type `tab` to trigger the autocomplete, 
then I get `demo_` which is convenient for me then I just type the number(1, 2, 3) I want to find the certain file. 

But the same case in alacritty 
I type `de` in alacritty then `tab` I get the full first file `demo_1.py` which seems inconvenient. So anyway to use this cmder feature in alacritty?

**Comment by chrisduerr** [comment]
This has nothing to do with the terminal emulator, this is a shell problem.
