### ISSUE TITLE
Weird behavior on remote systems

### ISSUE THREAD

**Issue by O2-AC** [alacritty/alacritty#3606]
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

OS: Linux
Version: 0.4.2
Linux/BSD: X11 and i3

When ssh'ing into a remote server the terminal behaves unpredictable. Backspace and arrow keys don't work anymore. In fact, pressing backspace leads to the curser moving to the right rather than to the left. On my local system everything works smoothly.
The remote system is running Ubuntu 19.04 with all current updates.

**Comment by chrisduerr** [comment]
You probably haven't installed Alacritty's terminfo on your remote system.

So either you have to install it, or you have to change your terminfo for ssh using `TERM=xterm-256color ssh` for example.

**Comment by jc9361** [comment]
I notcied this today also... only on 1 of my machines does this happen and only with alacritty, I will look into @chrisduerr 's suggestion.... glad this wasn't only me.

**Comment by jc9361** [comment]
@chrisduerr 's suggestion worked for me... man I love this term.

**Comment by chrisduerr** [comment]
Closing, since this is pretty common issue making it unlikely that it would be anything else.

Let me know if this doesn't fix it for you @O2-AC.

**Comment by rsniezek** [comment]
If anyone ever stumbles upon this, even after years of being closed, know that you can override the remote TERM variable in your .ssh/config for a given host with a simple
`SetEnv TERM=xterm-256color`
line within a given Host section. This way you override the TERM only for the hosts that actually need it.
