### ISSUE TITLE
Feature Request: Set background to image

### ISSUE THREAD

**Issue by sinistersnare** [alacritty/alacritty#3609]
Hi, I would like to use something like [Pokemon-Terminal](https://github.com/LazoCoder/Pokemon-Terminal) with Alacritty. 

Is there any way to set the background of Alacritty to an image, not merely a color? And if so, is there some way that it can be done programatically, dynamically? What kind of work is required to make this happen? Is it within the scope of Alacritty to add this feature?

Thanks!

**Comment by cole-h** [comment]
Duplicate of https://github.com/alacritty/alacritty/issues/565.

**Comment by sinistersnare** [comment]
Oops i guess i just searched on open issues. Thanks!
