### ISSUE TITLE
Backspace key turn into space when pressed

### ISSUE THREAD

**Issue by onthecouch** [alacritty/alacritty#3611]
when I want to delete the line, instead delete the char with backspace its turn into space.

using zsh as a shell

**Comment by chrisduerr** [comment]
Which terminfo are you using and which version of that do you have installed?

**Comment by atchim** [comment]
It happaned with me when I changed env.TERM to 'alacritty'. When I commented back env it worked properly. My config is like this:
``` config
# env:
    # TERM: alacritty
```

**Comment by kchibisov** [comment]
Then you likely don't have alacritty `TERM` installed on your system, if our terminfo isn't presented, we're using `xterm-256color`.

**Comment by onthecouch** [comment]
> It happaned with me when I changed env.TERM to 'alacritty'. When I commented back env it worked properly. My config is like this:
> 
> ```
> # env:
>     # TERM: alacritty
> ```

ahh yeah, that solved thank you. sorry for the late reply

**Comment by mediumroast221** [comment]
Thanks a lot. Uncomment your env and alacritty!! Thank you again!

**Comment by riz-ahmed** [comment]
this problem persists still on my mac M1. Any solutions or workarounds for this problem?

**Comment by vodrazka** [comment]
On macs it works when added:
```
env:
  TERM: xterm-256color
```
