### ISSUE TITLE
Special characters cause Fish's autocompletion to delete previous characters

### ISSUE THREAD

**Issue by niilz** [alacritty/alacritty#3612]
If the ```echo``` command is used to simply print a paragraph character (§) or some umlaut (ä, ö, ü), than the next time ```echo``` is typed, fish's autocompletion deletes characters to the left, while the special character gets printed multiple times to the right (in gray, since the characters appears as autocompletion option).
This even deletes parts of the prompt.

![alacritty_fish_character_bug](https://user-images.githubusercontent.com/38286937/79687924-d91d7a80-824a-11ea-857b-40347a66c531.gif)

I wonder whether this behavior is related to #1606

### System

OS: macOS - Catalina (10.15)
alacritty - version:  0.4.2
Shell: Fish (3.1.0)

**Comment by chrisduerr** [comment]
What's the output of `locale` for you? And this has nothing to do with #1606.

**Comment by niilz** [comment]
The output of ```locale``` is:

LANG=""
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=

**Comment by niilz** [comment]
Should I edit the original Issue post, to delete the reference to #1606?

Von: Christian Duerr <notifications@github.com>
Antworten an: alacritty/alacritty <reply@reply.github.com>
Datum: Sonntag, 19. April 2020 um 15:23
An: alacritty/alacritty <alacritty@noreply.github.com>
Cc: niilz <niilz@outlook.de>, Author <author@noreply.github.com>
Betreff: Re: [alacritty/alacritty] Special characters cause Fish's autocompletion to delete previous characters (#3612)


What's the output of locale for you? And this has nothing to do with #1606<https://github.com/alacritty/alacritty/issues/1606>.

**Comment by chrisduerr** [comment]
Does [this PR](https://github.com/alacritty/alacritty/pull/3608) fix it?

**Comment by niilz** [comment]
I'm very sorry, but I don't know how to test that. I've tried to follow the ["How-to-Test-a-Pull-Request" tutorial](https://github.com/TeamPorcupine/ProjectPorcupine/wiki/How-to-Test-a-Pull-Request) and typed the following command to do so ```git fetch upstream pull/3608/head:feat/fallback-lcctype-to-utf8``` (Also tried just "fallback-lcctype-to-utf8" without "feat/") but I'm either typing something wrong or have no rights on that branch.

**Comment by chrisduerr** [comment]
Oh, no worries. There should be simpler ways to test this if you're having trouble testing this.

You can try adding the following to your Alacritty configuration file:

```
env:
  LC_ALL: "UTF-8"
```

It might also be worth to test `LC_CTYPE` if `LC_ALL` doesn't work or trying to change it from just `UTF-8` to `en_US.UTF-8`.

I appreciate the effort to try and figure it out though. If you want to give it another shot, this is usually what I do to test Pull Requests:

 * Acquire clone the author's fork of Alacritty

````
git clone https://github.com/casperstorm/alacritty
cd alacritty
```

 * Check out the correct branch

```
git checkout feat/fallback-lcctype-to-utf8
```

 * Run the code

```
cargo run
```

This will obviously require a Rust toolchain to be installed. Which you can find documentation for online.

**Comment by niilz** [comment]
Of course I am testing it. Since you are going through all the trouble of helping and maintaining, it's the least I can do, when I already start an issue, I think.

Many thanks for your help.
Although ```LC_ALL: "UTF-8"``` and ```LC_TYPE: "UTF-8"``` did not work for me,
**setting  ```LC_ALL: "en_US.UTF-8"```  made the entire, unexpected behavior go away!**

(Little side note: This worked, even though all the keyboard and language settings on my system are in german)

Since this was clearly the solution, I am closing the issue. 

Also thanks for the git-checkout-test-flow described in your last comment.

**Comment by chrisduerr** [comment]
Setting it to `de_DE.UTF-8` might also work and provide better results for you.

**Comment by niilz** [comment]
Yes, ```de_DE.UTF-8``` also works perfectly and makes indeed more sense for my setup! Thanks for that tip.

**Comment by casperstorm** [comment]
> Many thanks for your help.  Although LC_ALL: "UTF-8" and LC_TYPE: "UTF-8" did not work for me

Can you try with just `LC_CTYPE` to see if that works as well. Set it to `UTF-8`.

**Comment by niilz** [comment]
I am so sorry. That does work indeed as well. My mistake was, that I had tried to set ```"UTF-8"``` on an env-variable of ```LC_TYPE``` instead of ```LC_CTYPE```.
Now with ```LC_CTYPE: "UTF-8"``` everything works fine.
