### ISSUE TITLE
[Windows] Keybindings with negative modes don't work.

### ISSUE THREAD

**Issue by unDeadHerbs** [alacritty/alacritty#3613]
Uncommenting the two [below lines](https://github.com/alacritty/alacritty/blob/master/alacritty.yml#L554) from the example config results in the below error.

### System
OS: Windows 10 Education
Version: alacritty 0.4.2 (f68de37)
Windows: ConPTY

### Logs
```[2020-04-19 09:24:26.284261500] [ERROR] Unknown mode "~Vi"```

### Config
```
key_bindings:
  - { key: L,         mods: Control, mode: ~Vi,  chars: "\x0c"          }
```

**Comment by kchibisov** [comment]
Use config(from release page) and modes for your version, this mode is part of master, not `v0.4.2`.
