### ISSUE TITLE
Wrap does not work correctly

### ISSUE THREAD

**Issue by pavel-the-best** [alacritty/alacritty#3614]
I've tried to enter some long command. It seems, that wrap at first rewrites current line and only then starts filling next. This completely messes up long command navigation.
Steps to reproduce and how does it look like:
1 (just prompt):
```[user@host] $```
2 (start typing characters):
```[user@host] $ aaaaaaaaaaaaaaaaaaaaa```
3 (reached wrap pseudo-margin, change symbol to b):
```bbbbb@host] $ aaaaaaaaaaaaaaaaaaaaa```
4 (passed  pseudo-margin):
```bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb``` (note, that it's longer than in 3 step)
5 (reached window border):
```bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb```
```bbb```
Well done, you have messed up command navigation (for example, home button returns to something, that's rendered at offset, but is actually beginning of the command)
Excuse me for my English.

### System

OS: Linux
5.6.2-gentoo x86_64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz GNU/Linux
Version: 0.4.2
Wayland, Sway
Font & size: Iosevka 18.0

**Comment by kchibisov** [comment]
We don't control wrap in your shell and has nothing to do with it. Some shells are wrapping by itself, some shells don't wrap and just write content relying on terminal to wrapl. I can't repro your issue by just following your steps in bash without any config, Also, `Home/End` navigation on a prompt is done by shell, not by us, so if shell places cursor in a wrong position, it's likely up to shell. I also don't see how different character matters here, we don't introspect characters you're sending to us.

Are you sure that changing the character matter?

**Comment by pavel-the-best** [comment]
Thank you, changing my shell helped.
No, I've changed the character to help you understand better.
