### ISSUE TITLE
'❯' character can't be displayed on Windows 10

### ISSUE THREAD

**Issue by BatmanAoD** [alacritty/alacritty#3620]
I am trying to use Starship with FiraCode, and while most special characters (such as the Starship/Powerline icon for it) display correctly, '❯' is just a blank space. If I copy the character from another terminal (such as the Windows Terminal preview) and paste it into a shell in Alacritty, I get a `b` and some spaces.

The behavior is the same regardless of whether I'm running Git Bash or a WSL (2) shell. In both cases, the `locale` variables are set to either `C.UTF-8` or `en_US.UTF-8`.

I have verified that the Windows Terminal preview can display the character, so it doesn't seem to be an issue with ConPTY.

### System

OS: Windows 10, version 2004 (preview build slow ring)
Version: 0.4.2 (f68de37)
Windows: ConPTY (tried WinPTY as well)

**Comment by chrisduerr** [comment]
Font fallback has just landed 4 days ago, would you mind giving this a try?

https://github.com/alacritty/alacritty/commit/840cb1b93a68389fab63e5a8f94cdaa2d607d1c3

I'd assume that this would fix the problem.

**Comment by BatmanAoD** [comment]
That works! Unfortunately, it now makes the prompt unusably slow; it takes about 10 seconds after completing a command to show the prompt again.

**Comment by chrisduerr** [comment]
> it takes about 10 seconds after completing a command to show the prompt again.

Have you setup a custom git prompt or something like that? Please make sure that your prompt command can run in a reasonable timeframe. But that's not an Alacritty issue if it's just the prompt and nothing else.

**Comment by BatmanAoD** [comment]
As I mentioned, I'm using Starship; I haven't changed the default settings. I just tested, and it's the `starship_precmd` itself that takes multiple seconds. I agree that seems like something that shouldn't be impacted by Alacritty, but I haven't seen the issue with any other terminal emulator (extraterm, the released 0.4.2 version of Alacritty, Windows Terminal preview, or the built-in Windows terminal).

**Comment by chrisduerr** [comment]
If the `starship_precmd` is taking a long time, there's nothing a terminal emulator can do about it.

It might just be related to the directory you're in, or various other factors. Slowdowns like that are commonly seen with poorly implemented prompts and big git repos for example.

**Comment by BatmanAoD** [comment]
@chrisduerr Ah, okay, I have managed to reproduce the issue now in other emulators, so it's not related to an Alacritty change post-0.4.2 after all. (The problem seems to be related to running a WSL shell in a native Windows repository with cargo and git metadata.)
