### ISSUE TITLE
Add man page to deb generated by cargo-deb

### ISSUE THREAD

**Issue by stevenengler** [alacritty/alacritty#3628]
Hi, I think it would be useful to add Alacritty's man page to the deb generated with `cargo deb -p alacritty`. The deb already includes the shell completions so adding the man page doesn't seem like it would be difficult, but I have no experience with the Rust build process.

**Comment by chrisduerr** [comment]
We've already discussed removing the prebuilt Linux binaries before, so I don't think there's much point in adding more to them.

I've created #3630 to put that plan into action.

**Comment by stevenengler** [comment]
Oh that's disappointing. I can maybe understand not wanting to publish a deb, but why remove the ability to build a deb for people building from source? Is this discussion somewhere you can link to?

**Comment by chrisduerr** [comment]
> I can maybe understand not wanting to publish a deb, but why remove the ability to build a deb for people building from source?

That's a good point. Fundamentally the problem is just that the deb we build will never work on more than a hand full of systems. So it's pointless and a waste of effort on our end. Alacritty's responsible for the code, not its distribution. That should be left up to distros and their maintainers.

So at that point the question is mostly what benefit we gain by providing a deb build for people that compile Alacritty from source. Unless you have a good argument while we should provide prebuilt debs.

Providing the ability to build a deb is a bit annoying, since it requires a lot of integration from Alacritty. At the same time all the changes done by the deb can also be done by the user themselves. I'd assume the main reason behind a deb would be to make it easier to remove it? I'm not completely opposed to keeping `cargo-deb` installation method around, but I'm not actually sure how many people use it.

**Comment by stevenengler** [comment]
> That's a good point. Fundamentally the problem is just that the deb we build will never work on more than a hand full of systems. So it's pointless and a waste of effort on our end. Alacritty's responsible for the code, not its distribution. That should be left up to distros and their maintainers.

That's fair, but I wouldn't necessarily say it's pointless to support Debian and Ubuntu (which the pre-built deb works fine on from my testing), which are more than a handful of systems. I'd love to see Alacritty in the Debian stable repos, but in the meantime we need to install it manually.

> So at that point the question is mostly what benefit we gain by providing a deb build for people that compile Alacritty from source. Unless you have a good argument while we should provide prebuilt debs.

I'm not too concerned about pre-built debs since I build Alacritty manually anyways. I think generally the more accessible you make the project, the wider the user base will grow. But that's not a concern for some projects so I have no opinions about this.

> Providing the ability to build a deb is a bit annoying, since it requires a lot of integration from Alacritty. At the same time all the changes done by the deb can also be done by the user themselves. I'd assume the main reason behind a deb would be to make it easier to remove it? I'm not completely opposed to keeping cargo-deb installation method around, but I'm not actually sure how many people use it.

Does it really require a lot of integration from Alacritty? I won't question your judgement for a project I know little about, but it looks like the functionality of building debs only requires about 17 lines in the `Cargo.toml`. As for why do I like debs? They simplify package management. I'm long past the days of spending a lot of time doing sysadmin on my own computer, so if installing and maintaining/upgrading a package becomes a chore, I'm less inclined to use it.

Anyways, those are my thoughts :)

**Comment by chrisduerr** [comment]
> That's fair, but I wouldn't necessarily say it's pointless to support Debian and Ubuntu (which the pre-built deb works fine on from my testing), which are more than a handful of systems. I'd love to see Alacritty in the Debian stable repos, but in the meantime we need to install it manually.

The prebuilt binary will not work on all Debian/Ubuntu systems.

> I'm not too concerned about pre-built debs since I build Alacritty manually anyways. I think generally the more accessible you make the project, the wider the user base will grow. But that's not a concern for some projects so I have no opinions about this.

I don't really think it's the job of an application to provide anything more than the source code. It's simply not feasible to explicitly try and support every platform and system out there with packages, that's specifically what distros and their package maintainers are for. If those maintainers don't want to add a package, your problem's kinda with them, not the application.

> Does it really require a lot of integration from Alacritty? I won't question your judgement for a project I know little about, but it looks like the functionality of building debs only requires about 17 lines in the Cargo.toml.

18 lines in the `Cargo.toml`, a file that has absolutely nothing to do with packaging. That's almost 1/4th of the entire file for a distro specific thing. We support at least 4 platforms (BSD/Linux/macOS/Windows), of which some have multiple different distributions. If we would put this kind of workaround for every single one of them (which they equally deserve, there's nothing making Ubuntu special here), our `Cargo.toml` would probably be 90% stuff that shouldn't be in it in the first place.

This also adds two scripts to our repo, though those are rather irrelevant.

Additionally, we now have a dependency on the `cargo-deb` tool. That means that we need to make sure that tool works with Alacritty and there's no security issues present. Thankfully I consider the maintainer trustworthy, but there are still maintenance problems. The latest version only works with Rust 1.42+ for example, while we guarantee support for 1.39+ (effectively breaking our version guarantee, but there's no good way for us to change that).

> As for why do I like debs? They simplify package management. I'm long past the days of spending a lot of time doing sysadmin on my own computer, so if installing and maintaining/upgrading a package becomes a chore, I'm less inclined to use it.

That's a fair point and is about what I would expect. Installing a package from source and updating/removing it is simply more messy than using a package that integrates with the package manager. After all that's what package managers are for. Unfortunately `apt` isn't great at that, so it makes it very difficult for users to maintain their own versions of a package.

Have you tried the PPA for Alacritty? I'm curious what the reasons are to use the deb over the PPA, are there compatibility problems with your system?

**Comment by stevenengler** [comment]
> The prebuilt binary will not work on all Debian/Ubuntu systems.

That's true, but it works on at least Ubuntu 18.04, 20.04, and Debian 9, 10 (the ones I'm set up to test).

> I don't really think it's the job of an application to provide anything more than the source code. It's simply not feasible to explicitly try and support every platform and system out there with packages, that's specifically what distros and their package maintainers are for. If those maintainers don't want to add a package, your problem's kinda with them, not the application.

Sure I'd agree that's true for a hobby project.

> Additionally, we now have a dependency on the cargo-deb tool. That means that we need to make sure that tool works with Alacritty and there's no security issues present. Thankfully I consider the maintainer trustworthy, but there are still maintenance problems.

When I built Alacritty the other day it had I think over 100 dependencies (direct and indirect). I think Rust packages like Alacritty have already gone the npm route of using too many independently-developed small packages to feasibly audit, all of which introduce possibilities for supply chain attacks. While I agree about the security problems of adding dependencies, Alacritty already has a lot of them.

> Have you tried the PPA for Alacritty? I'm curious what the reasons are to use the deb over the PPA, are there compatibility problems with your system?

I don't use PPAs unless I know the maintainer. Don't want random repositories having root privileges :)

**Comment by chrisduerr** [comment]
> Sure I'd agree that's true for a hobby project.

It's not true for any project. Things work much, much better when you stick to the problems you're actually setup to solve rather than trying to mess with distro packaging when you've got no horse in that race.

> When I built Alacritty the other day it had I think over 100 dependencies (direct and indirect). I think Rust packages like Alacritty have already gone the npm route of using too many independently-developed small packages to feasibly audit, all of which introduce possibilities for supply chain attacks. While I agree about the security problems of adding dependencies, Alacritty already has a lot of them.

Alacritty has 234 unique dependencies. But that's the exact reason why it's important to be careful. And every single dependency removed from that makes it a little easier to keep things under control. Saying adding new dependencies doesn't matter because there already are so many is not an argument that makes a lot of sense to me.

> I don't use PPAs unless I know the maintainer. Don't want random repositories having root privileges :)

The maintainer of the PPA is the same maintainer of the cargo-deb package. So you kinda have to trust him no matter what.

**Comment by JMurph2015** [comment]
For what it's worth over the past 3 years or so I've just come back to this commit and patched those 17 lines forward at least 3 times.  I need to be able to build from source (yes I build cargo-deb from source as well) and so the PPA is a no go.  Removing this is just putting hassle and jank between the user and a working install.
