### ISSUE TITLE
Crashes after upgrading to Ubuntu 20.04 (libGL error: failed to load driver)

### ISSUE THREAD

**Issue by fsouza** [alacritty/alacritty#3632]
### System

Upgraded from 19.10 to 20.04, after restart can't start Alacritty.

OS: Linux
Version: `alacritty 0.5.0-dev (f48c43f)`
Linux/BSD: Running with X11 (tried with Wayland too and got the same behavior)

### Logs

Output of `alacritty -vv`:

```
％ ./target/debug/alacritty -vv
Created log file at "/tmp/Alacritty-54888.log"
[2020-04-23 16:58:35.642166443] [INFO] Welcome to Alacritty
[2020-04-23 16:58:35.642444873] [INFO] Configuration loaded from "/home/fsouza/.config/alacritty.yml"
[2020-04-23 16:58:35.657868377] [DEBUG] Estimated DPR: 1
[2020-04-23 16:58:35.657986689] [DEBUG] Estimated Cell Size: 10 x 20
[2020-04-23 16:58:35.658032022] [DEBUG] Estimated Dimensions: None
libGL error: MESA-LOADER: failed to open iris (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast
libEGL warning: MESA-LOADER: failed to open iris (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)

libEGL warning: MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)

libEGL warning: MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)

libEGL warning: MESA-LOADER: failed to open iris (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)

libEGL warning: MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)

libEGL warning: MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)

[2020-04-23 16:58:35.769967659] [ERROR] Alacritty encountered an unrecoverable error:

        Error creating GL context; Received multiple errors. Errors: `[OsError("eglInitialize failed"), OsError("GL context creation failed")]`
```

After a quick search, I found #2219 and https://github.com/alacritty/alacritty/issues/2219#issuecomment-476853980, and running `cargo run --example window` on glutin exhibits the same behavior.

**Comment by chrisduerr** [comment]
Which GPU and driver do you use?

**Comment by chrisduerr** [comment]
> Also, make sure that you've updated all mesa related libs properly.

This and a full restart should be performed.

**Comment by fsouza** [comment]
I had restarted and upgraded all system libraries, but @kchibisov comments on the libraries helped me figure out: I use linuxbrew and the stuff on linuxbrew may need to get recompiled or something like that. Will keep digging on that x)

When I remove linuxbrew from the equation, everything works fine. Will close this, thanks for the very fast responses! :grin: :tada:

**Comment by aravindsd** [comment]
I hope installing Mesa graphics library should solve the issue

http://ubuntuhandbook.org/index.php/2019/12/install-mesa-19-3-ubuntu-18-04-19-10/

**Comment by ayushkamadji** [comment]
I use `MESA_LOADER_DRIVER_OVERRIDE=i965` in environment as mentioned in arch wiki [here](https://wiki.archlinux.org/title/intel_graphics) and it works
