### ISSUE TITLE
On opening Neovim in a new window in i3, only about half of the window is filled

### ISSUE THREAD

**Issue by maxigaz** [alacritty/alacritty#3634]
### System

OS: Manjaro Linux
Alacritty version: `alacritty --version` 0.4.2
Neovim version: 0.4.3
X11, i3wm with picom

### Logs

Font/Terminal size: `alacritty -vv` [Alacritty-21216.log](https://github.com/alacritty/alacritty/files/4528563/Alacritty-21216.log)

### Steps to reproduce

1. Open an Alacritty window in i3 on an empty workspace, with default tiling mode.
2. Run `alacritty -vv -e nvim -u NORC lorem.txt`. (Attached here: [lorem.txt](https://github.com/alacritty/alacritty/files/4528566/lorem.txt))
3. About 50% of the time, only a part of the second window is actually filled vertically.

![nvim-alacritty-bug 2020-04-24_12-58](https://user-images.githubusercontent.com/10419911/80208069-b8c93380-862f-11ea-81a4-fbb5b4ff09d4.png)

Another thing to notice is that if I jump to the last character by pressing `$`, the cursor position is also wrong (not on any visible character), and the number `445` is displayed under the status line.

As a workaround, resize the window or run `alacritty -e alacritty-nvim.sh` instead, where the content of `alacritty-nvim.sh` is the following:

```bash
#!/usr/bin/env bash
sleep 0.02
nvim $1
```

This issue happens with Alacritty and Neovim only. The combinations Alacritty + Vim and Kitty + Neovim work fine in this respect.

**Comment by kchibisov** [comment]
it's a neovim bug https://github.com/neovim/neovim/issues/11330

**Comment by kchibisov** [comment]
we have an issue to add a flag to try prevent it in alacritty  here #2817
