### ISSUE TITLE
Clarification on hex vs. unicode escape sequences in configuration

### ISSUE THREAD

**Issue by cideM** [alacritty/alacritty#3640]
The [keyboard mappings Wiki page](https://github.com/alacritty/alacritty/wiki/Keyboard-mappings) explicitly mentions support for 

> can be any text string and supports hexadecimal escapes:

which is echoed on the odd blog post about integrating tmux with alacritty ([post](https://posts.michaelks.org/simulating-macos-terminal-bindings-in-alacritty/) [post](https://arslan.io/2018/02/05/gpu-accelerated-terminal-alacritty/))

While learning the Dhall configuration language I ran into some [issues](https://discourse.dhall-lang.org/t/how-to-write-hexadecimal-strings/221/4) there with regards to hex strings and ultimately ended up achieving the same behavior as outlined in those posts with unicode escape sequences.

For example the below seem to be equivalent (opens a split on the right in tmux with my config)
```
    - { key: Backslash, mods: Control, chars: "\x60\x7c" } # Control+\: split right
    - { key: Backslash, mods: Control, chars: "\u0060\u007c" } # Control+\: split right
```

I'm wondering about two things:
- Should unicode also be mentioned on that wiki page?
- Am I missing some edge cases where the unicode sequences won't work?

**Comment by chrisduerr** [comment]
> Should unicode also be mentioned on that wiki page?

Sure, feel free to add it if you want to.

> Am I missing some edge cases where the unicode sequences won't work?

No, it's just not documented. There's no problem with using it.

**Comment by cideM** [comment]
@chrisduerr 

I edited the Wiki page https://github.com/alacritty/alacritty/wiki/Keyboard-mappings
https://github.com/alacritty/alacritty/wiki/Keyboard-mappings/_compare/ffad55e16e6d426698d6ae194df1afa2bc9b2970...eb00736ad14902023642faf96de708160394c05b

**Comment by chrisduerr** [comment]
Looks great, thanks for your contribution!

**Comment by briandipalma** [comment]
For anyone who comes across this issue like I did and can't get Ctrl+\ to work with the above values it's hex value `1c`; from http://jkorpela.fi/chars/c0.html

```
- { key: Backslash,   mods: Control,       chars: "\x1c"      } # CTRL+\ required for Mac OS X
```
