### ISSUE TITLE
When multi-line pasting in tmux new lines are stripped

### ISSUE THREAD

**Issue by chrischen** [alacritty/alacritty#3642]
### System

OS: macOS Catalina
Version: 0.4.2

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
I get this when starting tmux.
```
[2020-04-25 23:50:12.603261000] [DEBUG] [unhandled osc_dispatch]: [['1','3','3',],['A',],] at line 759
[2020-04-25 23:50:12.603339000] [DEBUG] [unhandled osc_dispatch]: [['1','3','3',],['B',],] at line 759
[2020-04-25 23:50:12.653321000] [DEBUG] [unhandled osc_dispatch]: [['1','3','3',],['C',],[],] at line 759
```
Keyboard and bindings: `alacritty --print-events`

Copy a multi line text such as this one
```
This should be line 1
This should be line 2
  Line 3
```

Open Alacritty, then run tmux, and then paste. Everything goes in one line.

### What happens

<img width="406" alt="image" src="https://user-images.githubusercontent.com/109630/80297861-b9a3b780-874c-11ea-8e16-70fd32a83b4d.png">
Everything is on one line. Pasting is also slow (with long blocks of text you can see it pasting vs instantly appearing).

### What is expected

Pasted text on multiple lines
This is output from iTerm2 running zsh + tmux:
<img width="348" alt="image" src="https://user-images.githubusercontent.com/109630/80297881-eb1c8300-874c-11ea-84b4-80a8ecc9f66c.png">

Out put in alacritty without tmux:
<img width="378" alt="image" src="https://user-images.githubusercontent.com/109630/80297891-04253400-874d-11ea-9c68-1ebe82ed567a.png">

Not sure if this is a tmux bug or alacritty, but this problem doesn't exist with Terminal.app nor iTerm2.

**Comment by chrisduerr** [comment]
> Not sure if this is a tmux bug or alacritty

Have you tried pasting without tmux running? Seems like that would be the natural first step.

Also, where are you copying from?

**Comment by chrischen** [comment]
Yes, I have done that and it works fine outside of tmux. The third screenshot in my post shows that working.

I am copying and pasting any text selection that has new lines. It doesn't matter if it's \n or \r\n (I tested both). For example, you can try it with the sample multi-line text in this issue.

**Comment by chrisduerr** [comment]
If it works outside of tmux, it's probably not an Alacritty problem.

**Comment by chrischen** [comment]
This problem happens with alacritty's default bracketed paste.

New lines are gone in the bracketed paste in TMUX:
<img width="437" alt="image" src="https://user-images.githubusercontent.com/109630/80928883-57127300-8d6d-11ea-83ec-41e1f90fa90c.png">

Just letting you guys know, because problem doesn't happen in iTerm2 or Kitty in tmux.

**Comment by chrisduerr** [comment]
@chrischen Are you saying it happens when in bracketed paste mode without `tmux` running? Because it does not for me on Linux/macOS at least.

**Comment by jonhoo** [comment]
For what it's worth, I observe exactly the same thing, and it only happens with Alacritty + tmux. Interestingly enough I've only ever observed it when using Alacritty on macOS and where the remote machine is running a fairly old version of Linux (Amazon Linux 2 specifically, though with an up-to-date built-from-source version of tmux). On my Linux box, this has never been a problem, though there I also never ssh into old versions of Linux, so hard to say which of the two is the culprit.

**Comment by chrisduerr** [comment]
@jonhoo "ssh into old version of Linux" sounds like outdated terminfo tbh.

**Comment by jonhoo** [comment]
I _think_ I have manually installed newer terminfos on the hosts in question, but will pull a new one from ncurses and see if the problem disappears :+1:

**Comment by juanlu-sanz** [comment]
Hi! 

I am having this exact same issue, alacritty on MacOS Monterey + tmux 3.3a.

Same tmux in iTerm works fine and pastes multiline text just fine, but on Alacritty + tmux it does not work as intended and removes all newline characters.

Not SSH-ing into anything.

@jonhoo or anyone else, did you manage to find a solution?

Thanks! :D
