### ISSUE TITLE
Alacritty takes a long time to “register” to the WM/DE

### ISSUE THREAD

**Issue by johanfleury** [alacritty/alacritty#3644]
So, I have this weird behavior on GNOME where Alacritty takes a long time to “register” to the DE (I don’t know if that’s the correct word): when I start Alacritty from GNOME (by typing `alacritty` in the search bar then enter or by clicking on the Alacritty icon in the dash pannel), the window appears and I can use it instantly, but it is not present in alt-tab (as if the window was kind of “not registered” to the window manager or DE).

If I start Alacritty (with the same parameters as in the `.desktop` files) from another terminal (either another Alacritty instance or GNOME Terminal), then it seems to work as expected.

### System

OS: Debian GNU/Linux
Version: `alacritty 0.4.2 (f68de37)`
Linux/BSD: Gnome 3.36 / Wayland

### Logs

```
$ alacritty -vv --title Terminal -e tmux new-session
Created log file at "/tmp/Alacritty-14955.log"
[2020-04-26 12:15:22.343471786] [INFO] Welcome to Alacritty
[2020-04-26 12:15:22.343565032] [INFO] Configuration loaded from "/home/jfleury/.config/alacritty/alacritty.yml"
[2020-04-26 12:15:22.352504770] [DEBUG] Estimated DPR: 1
[2020-04-26 12:15:22.352546730] [DEBUG] Estimated Cell Size: 9 x 18
[2020-04-26 12:15:22.352559474] [DEBUG] Estimated Dimensions: None
[2020-04-26 12:15:22.448378281] [INFO] Device pixel ratio: 1
[2020-04-26 12:15:22.452209787] [INFO] Initializing glyph cache...
[2020-04-26 12:15:22.465234946] [INFO] ... finished initializing glyph cache in 0.012991078s
[2020-04-26 12:15:22.465268013] [INFO] Cell Size: 9 x 18
[2020-04-26 12:15:22.465274612] [INFO] Padding: 2 x 2
[2020-04-26 12:15:22.465282332] [INFO] Width: 800, Height: 600
[2020-04-26 12:15:22.466096909] [INFO] PTY Dimensions: Line(33) x Column(88)
[2020-04-26 12:15:22.467603799] [INFO] Initialisation complete
[2020-04-26 12:15:22.467667262] [DEBUG] New num_cols is 284 and num_lines is 58
[2020-04-26 12:15:22.468923002] [INFO] Width: 2560, Height: 1053
[2020-04-26 12:15:26.933961197] [INFO] Goodbye
Deleted log file at "/tmp/Alacritty-14955.log"
```

### Configuration

```
# .config/alacritty/alacritty.yml
live_config_reload: true

window:
  title: Terminal

  class:
    instance: Terminal
    general: Terminal

  startup_mode: Maximized
  decorations: none

  padding:
    x: 2
    y: 2

  dynamic_padding: false

cursor:
  style: Block
  unfocused_hollow: true

font:
  normal:
    family: DejaVu Sans Mono
    style: Book

  bold:
    family: DejaVu Sans Mono
    style: Bold

  italic:
    family: DejaVu Sans Mono
    style: Italic

  size: 11

  offset:
    y: 1

colors:
  primary:
    background: "0x262626"
    foreground: "0xdab997"

  cursor:
    text: "0x262626"
    cursor: "0xdab997"

  normal:
    black:   "0x262626"
    red:     "0xd75f5f"
    green:   "0xafaf00"
    yellow:  "0xffaf00"
    blue:    "0x83adad"
    magenta: "0xd485ad"
    cyan:    "0x85ad85"
    white:   "0xdab997"

  bright:
    black:   "0x8a8a8a"
    red:     "0xd75f5f"
    green:   "0xafaf00"
    yellow:  "0xffaf00"
    blue:    "0x83adad"
    magenta: "0xd485ad"
    cyan:    "0x85ad85"
    white:   "0xebdbb2"

  indexed_colors:
    - index: 16
      color: "0xff8700"
    - index: 17
      color: "0xd65d0e"
    - index: 18
      color: "0x3a3a3a"
    - index: 19
      color: "0x4e4e4e"
    - index: 20
      color: "0x949494"
    - index: 21
      color: "0xd5c4a1"

mouse:
  url:
    modifiers: Control

selection:
  save_to_clipboard: false
```

**Comment by kchibisov** [comment]
Could you try commenting out your entire config and retest?

**Comment by johanfleury** [comment]
Yep, sorry, I should’ve done that before posting.

I did some more tests and the issue seems to only be present then `window.class.instance` is set.

**Comment by kchibisov** [comment]
Are you running alacritty on Wayland natively or via XWayland?

**Comment by kchibisov** [comment]
also, do you have a desktop file `Terminal.desktop` somewhere?

**Comment by johanfleury** [comment]
Natively:

```
$ xlsclients  # I ran this within alacritty
host  gsd-xsettings
host  ibus-x11
host  gnome-shell
host  signal-desktop
host  firefox
host  /usr/lib/firefox/firefox
host  /usr/lib/firefox/firefox
host  /usr/lib/firefox/firefox
host  /usr/lib/firefox/firefox
host  /usr/lib/firefox/firefox
host  /usr/lib/firefox/firefox
host  /usr/lib/firefox/firefox
host  /usr/lib/firefox/firefox
host  /usr/lib/firefox/firefox
```

And yes I have a specific desktop file (but the issue is present even if I use the official desktop file):

```
# ~/.local/share/applications/terminal.desktop
[Desktop Entry]
Type=Application
Name=Terminal
Icon=Alacritty
Categories=Utility;TerminalEmulator;
StartupNotify=true
StartupWMClass=Alacritty
TryExec=alacritty
Exec=alacritty --title Terminal -e tmux new-session
Terminal=false

Actions=New;

[Desktop Action New]
Name=New Terminal
Exec=alacritty --title Terminal -e tmux new-session
```

Well, I think I found the issue, the `StartupWMClass` field in the desktop file is different from the class set in Alacritty’s configuration.

The issue is not present if I set both to `Alacritty`, but it is if I set both to `Terminal`.

**Comment by kchibisov** [comment]
> ~/.local/share/applications/terminal.desktop

Could you rename it to ~/.local/share/applications/Terminal.desktop and retest(also update desktop file db after that)?

**Comment by johanfleury** [comment]
I just did and it doesn’t work either.

So just so we’re on the same page, here are all the tests I did:

| Desktop file       | `StartupWMClass` | `window.class.instance` | Status             |
| ------------------ | ---------------- | ----------------------- | ------------------ |
| Alacritty.desktop  | Alacritty        | Not set                 | :heavy_check_mark: |
| Alacritty.desktop  | Alacritty        | Alacritty               | :heavy_check_mark: |
| Alacritty.desktop  | Alacritty        | Terminal                | :heavy_check_mark: |
|                    |                  |                         |                    |
| Terminal.desktop   | Alacritty        | Not set                 | :heavy_check_mark: |
| Terminal.desktop   | Alacritty        | Alacritty               | :heavy_check_mark: |
| Terminal.desktop   | Alacritty        | Terminal                | :x:                |
|                    |                  |                         |                    |
| Terminal.desktop   | Terminal         | Not Set                 | :heavy_check_mark: |
| Terminal.desktop   | Terminal         | Alacritty               | :heavy_check_mark: |
| Terminal.desktop   | Terminal         | Terminal                | :x:                |

The main difference I see between my desktop file and the official one is `StartupNotify`, but I tried without it and the behavior is the same.

To be honest, this desktop file is kind of a merge between an old desktop file I created when I was using URxvt and the official Alacritty’s desktop file. Now that I know what settings work I can just set everything to the default value (I don’t really care), but if you this this is an issue that must be corrected, I’ll be happy to do more tests with you.

**Comment by chrisduerr** [comment]
> the issue is present even if I use the official desktop file

> Well, I think I found the issue, the StartupWMClass field in the desktop file is different from the class set in Alacritty’s configuration.
>
> The issue is not present if I set both to Alacritty, but it is if I set both to Terminal

Which one of these is true? The official desktop file has Alacritty as class.

**Comment by johanfleury** [comment]
@chrisduerr my first statement (“the issue is present even if I use the official desktop file”) is wrong, see the table I made in my previous comment.

> The issue is not present if I set both to Alacritty, but it is if I set both to Terminal

This is still true with my custom desktop file.

**Comment by chrisduerr** [comment]
Then everything is working as intended as far as I can tell.
