### ISSUE TITLE
Remove Shift-Backspace binding

### ISSUE THREAD

**Issue by davidmogar** [alacritty/alacritty#3652]
By default, the binding `Shift-Backspace` deletes the previous word. This is not the case for other terminals or when you do the same in any input. There, only the previous character is removed.

I added the following lines to my `alacritty.yml`:
```yaml
key_bindings:
     - { key: Back, mods: Shift, action: None }
```
This is not a solution as it doesn't delete any character, but at least I don't delete words by mistake. How could I change it so `Shift-Backspace` has the same behavior as `Backspace`?

# System

OS: Linux
Version: alacritty 0.4.2
Linux: X11, picom, bspwm

**Comment by chrisduerr** [comment]
> This is not the case for other terminals or when you do the same in any input.

That probably depends on which terminal you're testing. Alacritty correctly sends ^H for shift backspace and ^? for backspace at least on all machines I've ever tested.

> How could I change it so Shift-Backspace has the same behavior as Backspace?

You could bind it to send the same thing backspace sends? The config should document that sufficiently.

**Comment by davidmogar** [comment]
Thanks for your answer @chrisduerr.

> That probably depends on which terminal you're testing. Alacritty correctly sends ^H for shift backspace and ^? for backspace at least on all machines I've ever tested.
What "correctly sends ^H" means? You mean that the expected behavior should be to delete the previous word? And what defines the expected behavior? That is not the default for other terminals, browsers, text edition tools... I'm not saying that Alacritty is doing it wrongly. Probably there's some standard that is not being correctly followed, but I'm not used to this behavior and I would to modify it.

> You could bind it to send the same thing backspace sends? The config should document that sufficiently.
What config is that? The default `alacritty.yml` file? I'm failing to see there any mention to that shortcut.

**Comment by kchibisov** [comment]
>What "correctly sends ^H" means? You mean that the expected behavior should be to delete the previous word? And what defines the expected behavior? That is not the default for other terminals, browsers, text edition tools... I'm not saying that Alacritty is doing it wrongly. Probably there's some standard that is not being correctly followed, but I'm not used to this behavior and I would to modify it.  

No, it means that alacritty should send this character on `Shift + Backspace`, you can type `showkey -a` and test it yourself. What your shell does on `^H` is up to your shell, mine just deletes one char. `Backspace` is just `^?`.

**Comment by dnkl** [comment]
Which terminals send ^H for Shift+backspace and ^? for backspace?

I tested xterm, urxvt, kitty and qterminal - all of them sends the same sequence for backspace and shift+backspace (which in at least xterms case can be configured to be either ^H or ^?)

**Comment by kchibisov** [comment]
I'm also not aware of terminal that sends different sequence for `Shift + Backspace`, VTE just sends `^?` for both.

**Comment by dnkl** [comment]
@davidmogar try

```yml
- { key: Back,   mods: Shift,   chars: "\x7f" }
```

**Comment by chrisduerr** [comment]
> Which terminals send ^H for Shift+backspace and ^? for backspace?

I probably confused our Shift+Backspace with our Alt+Backspace handling. I think the only reason why we send something different on Shift+Backspace is because we explicitly remap Backspace. For Shift+Backspace we just forward winit's character.

**Comment by kchibisov** [comment]
I'm in favor of sending the same character as normal backspace.

**Comment by davidmogar** [comment]
> @davidmogar try
> 
> ```yaml
> - { key: Back,   mods: Shift,   chars: "\x7f" }
> ```
Thanks @dnkl. This is indeed the solution to my problem.

> No, it means that alacritty should send this character on `Shift + Backspace`, you can type `showkey -a` and test it yourself. What your shell does on `^H` is up to your shell, mine just deletes one char. `Backspace` is just `^?`.

Without the change, this is what I get for `Backspace` and `Shift-Backspace` when running `showkey -a`:
```
^? 	127 0177 0x7f
^H 	  8 0010 0x08
```

**Comment by egmontkob** [comment]
Every once in a while I type short uppercase text by holding down Shift. I very rarely encounter some software where I cannot simply type a Space, or erase using Backspace while doing this, causing some headache.

I think it's a generic usability expectation that Shift is ignored when pressing Space or Backspace in all kinds of software that handle text (not just terminals).

Ctrl, Alt, Shift+Ctrl etc. are free to alter the behavior.

**Comment by chrisduerr** [comment]
@egmontkob Generally you're right, but in this case it's a bit more complicated. Since our windowing backend actually sends us the 'incorrect' backspace ^H. So backspace is just a special case here.

I'd assume that's probably also the case why XTerm *always* sends ^H by default. So the problem's just about getting consistent behavior while changing things. But of course you're absolutely right that it shouldn't be the way it is.

**Comment by Aelnor** [comment]
I'd like to take this one.
Are we fixing config only or the `default_key_bindings()` as well?

**Comment by chrisduerr** [comment]
In the default config, only bindings that bind to actions are documented. Since all character bindings would be a bit too much.

**Comment by Aelnor** [comment]
Should be closed now I believe
