### ISSUE TITLE
nerdfont tmux neovim not show any icons on macos

### ISSUE THREAD

**Issue by boonkerz** [alacritty/alacritty#3656]
With Tmux no Icons are shown if i use the alacritty.app?

![image](https://user-images.githubusercontent.com/277321/80635551-4fe12180-8a5c-11ea-8deb-32f5c491746d.png)

without tmux and alacritty.app:
![image](https://user-images.githubusercontent.com/277321/80635631-6dae8680-8a5c-11ea-8d99-0c4abbba6981.png)

with alacritty.app -> tmux -> alacritty -vv -> tmux it works also:

![image](https://user-images.githubusercontent.com/277321/80637499-63da5280-8a5f-11ea-9190-f53921cdea0e.png)

**Comment by chrisduerr** [comment]
Does it work when  you add the following to your config?

```
env:
  LANG: "en_US.UTF-8"
```

**Comment by boonkerz** [comment]
thx hit helped :)

**Comment by coderprem** [comment]
> Does it work when you add the following to your config?
> 
> ```
> env:
>   LANG: "en_US.UTF-8"
> ```

where to add this line
