### ISSUE TITLE
Alacritty incorrectly displays vim-lightline

### ISSUE THREAD

**Issue by brainplot** [alacritty/alacritty#3663]
Hi, I hope this doesn't come off as overly pedantic but I've noticed that Alacritty displays `vim-lightline` slightly incorrectly compared to how Gnome Terminal displays it.
<hr>
Here's how Gnome Terminal displays it:

<p align="center">
<img src="https://user-images.githubusercontent.com/28014843/80778419-b3587580-8b68-11ea-837a-99e24d65b1ee.png" />
<img src="https://user-images.githubusercontent.com/28014843/80778421-b6536600-8b68-11ea-939d-899a8e0ca540.png" />
</p>

The green region is equally spaced around the word `NORMAL` and also around the indicator for column and row on the right hand side.
<hr>
Here's how Alacritty displays it:

<p align="center">
<img src="https://user-images.githubusercontent.com/28014843/80778599-442f5100-8b69-11ea-92b2-67d9d232d40f.png" />
<img src="https://user-images.githubusercontent.com/28014843/80778607-48f40500-8b69-11ea-9080-afc48536a93b.png" />
</p>

Looks like Alacritty is missing a couple of pixels from the top region, across the entire lightline.
<hr>

I've been using Gnome Terminal for a while now and I was looking into switching to Alacritty. That was one of the things that immediately stood out to me when I opened nvim. I should mention that both terminal emulators have the same font and the same size (`Hack 13`)

I think it's even more noticeable at normal distance than zoomed in:
![Screenshot from 2020-05-01 05-13-14](https://user-images.githubusercontent.com/28014843/80778986-8ad17b00-8b6a-11ea-8879-2df196307812.png)
![Screenshot from 2020-05-01 05-13-32](https://user-images.githubusercontent.com/28014843/80778985-8ad17b00-8b6a-11ea-888e-5a3a33300742.png)

### System

OS: Arch Linux
Version: alacritty 0.4.2
Linux/BSD: Gnome under X11

**Comment by chrisduerr** [comment]
What's the DPR of your monitor? Alacritty's font size is in points while I believe gnome's is in pixels. So a font size of 13 in both might not be the same.

**Comment by brainplot** [comment]
They look the exact same size to me:

![Screenshot from 2020-05-01 06-49-19](https://user-images.githubusercontent.com/28014843/80782839-fe2db980-8b77-11ea-972a-33894c038106.png)

Here's the output of `alacritty -v`:
```
Created log file at "/tmp/Alacritty-90389.log"
[2020-05-01 06:49:38.477990150] [INFO] Welcome to Alacritty
[2020-05-01 06:49:38.478052188] [INFO] Configuration loaded from "/home/gian/.config/alacritty/alacritty.yml"
[2020-05-01 06:49:38.553150428] [INFO] Device pixel ratio: 1
[2020-05-01 06:49:38.553903685] [INFO] Initializing glyph cache...
[2020-05-01 06:49:38.574218425] [INFO] ... finished initializing glyph cache in 0.020302283s
[2020-05-01 06:49:38.574298688] [INFO] Estimated DPR correctly, skipping resize
[2020-05-01 06:49:38.574305620] [INFO] Cell Size: 10 x 20
[2020-05-01 06:49:38.574310447] [INFO] Padding: 0 x 0
[2020-05-01 06:49:38.574317241] [INFO] Width: 1200, Height: 720
[2020-05-01 06:49:38.574665693] [INFO] PTY Dimensions: Line(36) x Column(120)
[2020-05-01 06:49:38.581834477] [INFO] Initialisation complete
[2020-05-01 06:49:38.582383645] [INFO] Width: 1200, Height: 720
[2020-05-01 06:49:40.400864869] [INFO] Goodbye
Deleted log file at "/tmp/Alacritty-90389.log"
```

**Comment by kchibisov** [comment]
That could be some edge rounding issue, but or because cairo + pango is just different here, since last time I've checked in the past, all other freetype based terminals(which are using it directly) had the same issue. if you don't like the offset of the glyphs in the line, use https://github.com/alacritty/alacritty/blob/7901b454ee04c7873e611986ed2dbe5c3d6331eb/alacritty.yml#L30 setting.

**Comment by brainplot** [comment]
Not sure I understand. How is the window position going to affect this? That's what the setting is about.

P.S. I misclicked and closed the issue by mistake. Sorry about that.

**Comment by kchibisov** [comment]
Ups, wrong `x`, `y` setting. This one https://github.com/alacritty/alacritty/blob/7901b454ee04c7873e611986ed2dbe5c3d6331eb/alacritty.yml#L152

**Comment by brainplot** [comment]
I can confirm that setting `y` to `-1` fixes it. It's centred now. Thank you for your help, @kchibisov.
<p align="center">
<img src="https://user-images.githubusercontent.com/28014843/80972429-656c9780-8e1e-11ea-81ba-100575128d80.png">
</p>

**Comment by chrisduerr** [comment]
Would be interesting to log the metrics and recompute them by hand. Though I'm fairly certain it should be correct on Linux.
