### ISSUE TITLE
Random GPU hangs when using Alacritty

### ISSUE THREAD

**Issue by tamirzb** [alacritty/alacritty#3667]
I am getting random GPU hangs when using alacritty. What happens is that I'm getting weird flashes on the screen and basically everything is stuck. The only way I found so far to continue from this state (other than a reboot) is to switch to a TTY and kill X.
Unfortunately I don't have a good way to reproduce these hangs, it honestly feels like they happen randomly once in a while when I'm using alacritty (they never happen when I'm using other programs that use the GPU). I know the lack of reproducibility probably makes this a hard to solve bug (sorry!) so I don't really expect a solution any time soon, but still thought it's better to report than not to.

### System

Arch Linux, X11, i3-gaps, picom
Kernel version: `5.6.8-arch1-1`
Alacritty version: Originally I had these issues in `0.4.2`, but then I updated to a dev version (`0.5.0-dev (f48c43f4)`) to check this and they still persist

### Logs

Here's what I get in `dmesg`:
```
i915 0000:00:02.0: Resetting rcs0 for preemption time out
i915 0000:00:02.0: alacritty[41123] context reset due to GPU hang
i915 0000:00:02.0: GPU HANG: ecode 11:1:84df7cfd, in alacritty [41123]
GPU hangs can indicate a bug anywhere in the entire gfx stack, including userspace.
Please file a _new_ bug report at https://gitlab.freedesktop.org/drm/intel/issues/new.
Please see https://gitlab.freedesktop.org/drm/intel/-/wikis/How-to-file-i915-bugs for details.
drm/i915 developers can then reassign to the right component if it's not a kernel issue.
The GPU crash dump is required to analyze GPU hangs, so please always attach it.
GPU crash dump saved to /sys/class/drm/card0/error
```
Here is the [GPU crash dump](https://github.com/alacritty/alacritty/files/4565379/error.txt) from `/sys/class/drm/card0/error`.

**Comment by kchibisov** [comment]
It says to report bug to https://gitlab.freedesktop.org/drm/intel/issues/new , if some OpenGL calls are hanging your GPU I doubt its our problem, however I've seen similar issues from intel GPUs recently, but in a bit more soft form.

**Comment by chrisduerr** [comment]
Since the `dmesg` states pretty clearly that the intel drm devs should be contacted, I'm going to close this issue in favor of contacting them first.

If it turns out that Alacritty does have a play in this, please let us know and I can re-open.
