### ISSUE TITLE
Allow changing inversed cursor to a fixed colored cursor

### ISSUE THREAD

**Issue by kchibisov** [alacritty/alacritty#3672]
Right now there's no way to set fixed colored cursor with escape sequence from inverted cursor, so it should be supported.

**Comment by jeffwindsor** [comment]
I would like to try to fix this, do I need to be assigned?

**Comment by jeffwindsor** [comment]
@kchibisov what are your acceptance criteria for this feature?

I see we have the ability to set a cursor color in the yaml file, and inverse is the default if no color is set.  Is the idea for this feature that we want to create `action` that toggles the cursor color between inverse and the value set in `colors: cursor: cursor`?

**Comment by kchibisov** [comment]
Oh, I forgot to mention that it should be via escape sequence. So this thing should set inverted cursor to the one with `#000000` background.

`echo -e "\033P\033]12;#000000\007\033\\"`

**Comment by jeffwindsor** [comment]
I am completely new to the code base, do you mind pointing me to a good starting place or similar example in the current code base (if any).

**Comment by kchibisov** [comment]
Starting point is right here and goes just by navigating those methods https://github.com/alacritty/alacritty/blob/a425fe6bfe734bb80dce334d6f1c53e0bd41c0db/alacritty_terminal/src/ansi.rs#L803

**Comment by jeffwindsor** [comment]
@kchibisov thanks.  I read through the code and have a little better understanding.  Do you mind helping me out by writing me a test for this change?

**Comment by kchibisov** [comment]
Ehm, the good test is commenting out cursor colors in config and running `echo -e "\033P\033]12;#000000\007\033\\"` it should change it to black background in the end, right now it just ignores it **if** cursor is inverted. So, this escape will work if you have fixed colors for a cursor in alacritty.yml, I'm not sure what test I can create better than this one. You should also go back to inverted cursor once you type `reset` after that escape sequence.

**Comment by jeffwindsor** [comment]
Sorry I meant the structure of the automated test, I saw a high level test using multiple files for such changes and wanted to understand that better.  But I am perfectly ok doing manual testing.

**Comment by jeffwindsor** [comment]
debugging the `echo -e "\033P\033]12;#000000\007\033\\"` example for both the cursor color set and non set in the yaml, revealed that in both examples the colors[foreground_index] is set to `#000000` and the color_changed flag for that index.  So my guess is that when we draw the cursor the the invariant example reads from a somewhere besides the colors[foreground_index].  
I looked around, but was unable to find where that drawing of the cursor occurs.  So I hate to ask one more favor but could you point me to where that occurs, and let me know if the invariant not using the foreground index was intentional or the whole issue.

**Comment by chrisduerr** [comment]
Pretty sure it's done in the `next` function in `term/mod.rs`. Somewhere around the place at least because that's where grid is converted to renderable cells.

**Comment by chrisduerr** [comment]
Since this was a requirement for search, I've implemented it myself in that branch.
