### ISSUE TITLE
`dynamic_offset` font setting to compliment `offset`?

### ISSUE THREAD

**Issue by jesseleite** [alacritty/alacritty#3673]
Alacritty's window padding settings are amazing, especially with the `dynamic_padding: true` setting allow for equal `padding` around both sides of the terminal window!

It'd be really cool to have a `dynamic_offset: true` font setting to compliment `offset` in the same way, which would render equal padding around both sides of the character (rather than just above or to right of the character)...

**Hyper** (notice how it renders the cursor above and below the character equally):
![image](https://user-images.githubusercontent.com/5187394/80893546-45fc3000-8ca1-11ea-8020-429060c263bd.png)

**Alacritty** (notice how it renders the offset above the character only):
![image](https://user-images.githubusercontent.com/5187394/80893565-7774fb80-8ca1-11ea-898e-c7d19fe56997.png)

Thoughts? 🙏

### System

OS: macOS
Version: alacritty 0.4.2 (f68de37)

**Comment by chrisduerr** [comment]
Why can't you use `glyph_offset` for that?

**Comment by jesseleite** [comment]
Ah, totally can!  Thanks!
