### ISSUE TITLE
ram usages on startup

### ISSUE THREAD

**Issue by kolokd** [alacritty/alacritty#3679]
on fedora 32 gnome at start up it takes 18.1 M RAM. On the other hand st  takes 1.4 M.
Is the RAM usage of alacritty is ok?

**Comment by chrisduerr** [comment]
> Is the RAM usage of alacritty is ok?

It is. The RAM usage you're reporting is in line with what should be expected.

**Comment by mobop** [comment]
but how can st use such lower memory at startup? why alacritty's memory usage is must higher?

**Comment by kchibisov** [comment]
Due to OpenGL etc, alacritty is using just a bit more ram than glxgears on my system for example.
