### ISSUE TITLE
It is not reading the alacritty.yml

### ISSUE THREAD

**Issue by adriantrejo** [alacritty/alacritty#3682]
I have tried many ways to change the config file but it has no effects on the terminal. I am putting the file in "~/.config/alacritty" route and entering with VIM editor putting this config file:

https://gitlab.com/dwt1/dotfiles/-/blob/master/.config/alacritty/alacritty.yml

But it has no effects on the terminal. Running the command alacritty --config-file ~/.config/alacritty/alacritty.yml give me this error: 

libEGL warning: DRI2: failed to authenticate

OS: Linux (Ubuntu LTS 20.04) Regolith
Version: last version

**Comment by chrisduerr** [comment]
What are you trying to change? How do you know that the config file isn't loading?

**Comment by adriantrejo** [comment]
> What are you trying to change? How do you know that the config file isn't loading?

I am just trying to change the background and foreground, thats why I think its not loading.

**Comment by chrisduerr** [comment]
Are all parent keys present or are some of them still commented out?

**Comment by adriantrejo** [comment]
> Are all parent keys present or are some of them still commented out?

The configuration file is exactly as the one I posted it. This is the file:

https://gitlab.com/dwt1/dotfiles/-/blob/master/.config/alacritty/alacritty.yml

Maybe I can send a log or something if you help me where it is.

**Comment by kchibisov** [comment]
>Running the command alacritty --config-file ~/.config/alacritty/alacritty.yml give me this error

Does it start at least?

**Comment by adriantrejo** [comment]
> alacritty --config-file ~/.config/alacritty/alacritty.yml

It put this error in the terminal and starts another terminal:

"libEGL warning: DRI2: failed to authenticate"

**Comment by kchibisov** [comment]
But is it using your colors, etc?

**Comment by adriantrejo** [comment]
> But is it using your colors, etc in that case?

No, its using the same colors, even if I change in the background and foreground hexadecimal values. It is the same colors that the ones before editing the file.

**Comment by kchibisov** [comment]
The config file you've linked is correct and works just fine. Also, what color it's using as a background, black (0x00000)?

**Comment by kchibisov** [comment]
Also, does this thing change the background to pink?

`echo -e "\e]11;#ff00ff"`

**Comment by adriantrejo** [comment]
> Also, does this thing change the background to pink?
> 
> `echo -e "\e]11;#ff00ff"`
> 
> You can type `reset` to revert it.

Yes, it is black. Your command changes the background to pink yes.

**Comment by kchibisov** [comment]
Does `reset` resets it back to black or to some other color?

**Comment by adriantrejo** [comment]
To black color

**Comment by adriantrejo** [comment]
Now it is solved, the problem was that when I create the .yml file and then editing with sublime text was different. Because I have multiple yml files. I put xdg-open . in the route ~/.config/alacritty and then editing the text file. Thanks to all!!
