### ISSUE TITLE
Emoji not displaying right

### ISSUE THREAD

**Issue by RemiDesgrange** [alacritty/alacritty#3686]
Hi, tried to found similar issue but didn't found anything related. Sorry if it's a duplicate.

### System

OS: Linux (arch linux)
Version: 0.4.2 (from archlinux repo)
Linux/BSD: Wayland

### Logs

```
[INFO] Welcome to Alacritty
[INFO] Configuration loaded from "/home/remi/.config/alacritty/alacritty.yml"
[DEBUG] Estimated DPR: 1
[DEBUG] Estimated Cell Size: 9 x 19
[DEBUG] Estimated Dimensions: None
[INFO] Device pixel ratio: 1
[INFO] Initializing glyph cache...
[INFO] ... finished initializing glyph cache in 0.053962629s
[INFO] Cell Size: 9 x 19
[INFO] Padding: 0 x 0
[INFO] Width: 800, Height: 600
[INFO] PTY Dimensions: Line(31) x Column(88)
[INFO] Initialisation complete
[DEBUG] unknown device status query: 1337
[DEBUG] New num_cols is 88 and num_lines is 30
[INFO] Width: 800, Height: 570
```

I installed `noto-font-emoji` from arch linux repo. No specific config in `~/.local/share/fontconfig` (non actually)

in gnome terminal:
![image](https://user-images.githubusercontent.com/13271765/81060731-5693ec80-8ed3-11ea-9832-da34f6c6e3d2.png)

in alacritty

![image](https://user-images.githubusercontent.com/13271765/81060752-627fae80-8ed3-11ea-8c9c-31888c2ccfe4.png)

Note that the `splashing_sweat_symbol` is not displaying great because of [another issue](https://github.com/alacritty/alacritty/issues/1864) But I don't think this is related.

Oh, and even if emoji support have some hiccups, alacritty is a great term emulator, thanks for this :heart:

**Comment by kchibisov** [comment]
fix your font fallback on a system. `fc-match -s FONT_YOURE_USING_IN_ALACRITTY` should show you the fallback list alacritty is using.

**Comment by RemiDesgrange** [comment]
Fixed it. Thanks for the help.

**Comment by WhyNotHugo** [comment]
@RemiDesgrange Can you share a bit about how your fixed it?

**Comment by polyzen** [comment]
I had issues with using an `/etc/fonts/conf.d/10-fonts.conf`, but with @kchibisov's help, wound up using a [`.config/fontconfig/fonts.conf`](https://github.com/polyzen/dotfiles/commit/156d4d0f2e96156fff4ed15bb74a942459bc1f89).

**Comment by RemiDesgrange** [comment]
https://blog.desgran.ge/post/emoji-on-linux/ I wrote it to not forget it :sweat_smile:
