### ISSUE TITLE
Support of special unicode characters

### ISSUE THREAD

**Issue by phaazon** [alacritty/alacritty#3690]
I’ve been using termite (VTE application) for a while, and switching to `alacritty` made me realize `alacritty` doesn’t support non-standard unicode codes. For instance,  (a gear-like icon) is supported by VTE terminals (and I tried with VS Code as well), but not with `alacritty`.

Comparison between `termite` (first image) and `alacritty` (second image):

![img_050620_142344](https://user-images.githubusercontent.com/506592/81177709-67ae2d80-8fa7-11ea-960c-99653e9078bb.png)

![img_050620_142246](https://user-images.githubusercontent.com/506592/81177750-7694e000-8fa7-11ea-8f72-d8cc654438fa.png)

### System

OS: Archlinux 5.6.8-arch1-1
Version: alacritty 0.4.2
i3 + compton

### Logs

```
[2020-05-06 14:38:35.172649662] [DEBUG] Estimated DPR: 1.125
[2020-05-06 14:38:35.172690057] [DEBUG] Estimated Cell Size: 11 x 24
[2020-05-06 14:38:35.172700437] [DEBUG] Estimated Dimensions: None
[2020-05-06 14:38:35.304927484] [INFO] Device pixel ratio: 1.125
[2020-05-06 14:38:35.308684513] [INFO] Initializing glyph cache...
[2020-05-06 14:38:35.342238904] [INFO] ... finished initializing glyph cache in 0.033529524s
[2020-05-06 14:38:35.342273198] [INFO] Cell Size: 11 x 24
[2020-05-06 14:38:35.342285752] [INFO] Padding: 2 x 2
[2020-05-06 14:38:35.342306671] [INFO] Width: 800, Height: 600
[2020-05-06 14:38:35.343013008] [INFO] PTY Dimensions: Line(24) x Column(72)
[2020-05-06 14:38:35.360281242] [INFO] Initialisation complete
[2020-05-06 14:38:35.360894695] [DEBUG] New num_cols is 74 and num_lines is 57
[2020-05-06 14:38:35.371979521] [INFO] Width: 828, Height: 1378
```

**Comment by kchibisov** [comment]
Could you test it outside of your editor, gear emoji works fine for me. It seems like it was stripped by it or taken from a different font.

**Comment by phaazon** [comment]
In this case it’s `neovim` but I tested it in `alacritty` directly by pasting the emoji, and I get the same behavior.
![img_050620_171501](https://user-images.githubusercontent.com/506592/81194715-45270f00-8fbd-11ea-9247-27c43c5f3973.png)

**Comment by kchibisov** [comment]
yeah, it seems like you're just getting it from some other font than in app you've tested, since for me it's being picked from `Noto Color Emoji`. I guess you should either change font fallback rules to prefer fonts you want or use a font, which has those symbols natively.

**Comment by phaazon** [comment]
[fc.txt](https://github.com/alacritty/alacritty/files/4588305/fc.txt)

I get these. :/

**Comment by chrisduerr** [comment]
@phaazon Which font is this gear icon from? Font Awesome?

**Comment by phaazon** [comment]
I don’t recall exactly where I took it, but yeah, it’s likely from Nerd Font actually.

**Comment by chrisduerr** [comment]
Font Awesome uses the private use area. If it's from Nerd Font, that might be conflicting.

**Comment by thelmuxkriovar** [comment]
you can't expect alacritty to support every character in the PUA (mostly because... well, there are bound to be inconsistencies), you could just use the normal unicode gear character ⚙ U+2699, that will fix your issue

**Comment by phaazon** [comment]
So… I don’t get what you mean, because this is from a vim plugin everybody uses, and VTE terminals support it.

**Comment by chrisduerr** [comment]
If your font fallback falls back to a different glyph because that font has priority for your system, then that's what Alacritty is going to use.

Alacritty does not know where the glyph is coming from, private use area or not. We delegate all of that to your system configuration of freetype/fontconfig.

Comparing it to VTE is problematic since it makes things even more complicated, not only does it use freetype/fontconfig, but also its own config **and** it also provides some glyphs on its own. So comparing to that is often not really useful. Most of the time it's just a matter of reordering the global fallback list.

**Comment by phaazon** [comment]
:thinking: I compared to that because it’s what I use on a daily basis, but if you look up you’ll also see that VS Code displays that correctly, so it’s not linked to VTE only. I compared it to VTE because VTE terminals are pretty solid and mature software (i.e. `termite`), so _maybe_ there’s something `alacritty` is missing here?

**Comment by chrisduerr** [comment]
>  compared to that because it’s what I use on a daily basis, but if you look up you’ll also see that VS Code displays that correctly

VSCode, which runs a browser, likely also renders their own custom glyphsets. Which Alacritty will not do.

Try uninstalling the fonts you don't need that might use the custom use area and see if that works for you. Or check the fallback list for fontconfig. We only use what fontconfig gives us and retrieve the first glyph available.

**Comment by phaazon** [comment]
So, the glyphs are okay if I use DejaVu Sans Mono, but won’t display correctly with JetBrains Mono. I’ll try to investigate a bit more but I don’t really understand what’s happening — JetBrains Mono has those glyphs for the wrong thing? Why does it work in `termite` with JetBrains Mono then? Argh I don’t understand. :laughing:

**Comment by chrisduerr** [comment]
Very small differences in font loading can make big changes to the fallback list. But our fallback matches `fc-match -s "Font Name:style=Style"`, so that should be sufficient for testing.

There's also a lot of things applications implement to work around issues that should be fixed in a different place.

**Comment by phaazon** [comment]
Yeah, I was able to fix the problem by patching JetBrains Mono… so I guess in the case of `termite`, they have a way to fallback to a proper font while `alacritty` fallbacks to something different.

**Comment by phaazon** [comment]
Duh? It’s not a _bug_, but it’s inconvenient `alacritty` doesn’t behave like all the other editors out there.

**Comment by chrisduerr** [comment]
Alacritty uses your system font configuration. Only because all your other applications might be using GTK, doesn't mean Alacritty should. As far as I can tell, everything is working exactly like it should.
