### ISSUE TITLE
.yml file not found after installing via brew cask

### ISSUE THREAD

**Issue by dr3apap** [alacritty/alacritty#3691]
os:macOS
Version:0.4.2

Log message =>  make: *** No rule to make target `/Users/<username>/Downloads/vifm-0.10.1/Makefile.am', needed by `/Users/<username>/Downloads/vifm-0.10.1/Makefile.in'.  Stop.

I installed through brew cask, when I tried to setup the manual page, shell completions, and terminfo definitions.I got the above error. I don't know what vifm has to do with the setup, vifm is a file manager app I have  on my system.  even though the terminal is working I can't perform any settings and configuration because the  .yml file needed for the  configuration is missing. I'm not sure if this isa bug or a OS compatibility issue I can't seem to locate any binary files that point to alacritty no dotfiles.

For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

OS: Linux/BSD/macOS/Windows
Version: `alacritty --version` output
Linux/BSD: X11/Wayland, DE or Compositor and WM
Windows: WinPTY/ConPTY (see `alacritty -v` output)

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by chrisduerr** [comment]
There is none, you need to create it. Sounds to me like `vifm` is completely unrelated and was installed separately.
