### ISSUE TITLE
Passing multiple command when using the -e flag

### ISSUE THREAD

**Issue by n0ibe** [alacritty/alacritty#3692]
OS: macOS
Version: alacritty 0.4.2 (f68de37)

How can I pass multiple commands when launching alacritty with the `-e` option? If I simply type

    $ /Applications/Alacritty.app/Contents/MacOS/alacritty -e command1 && command2

then `command1` is passed to alacritty but `command2` is executed by the shell. I tried wrapping the commands in single and double quotation marks, but nothing worked.

**Comment by cole-h** [comment]
You probably want to forward those commands to a shell, like `alacritty -e "bash -c 'command1 && command2'"`.

**Comment by n0ibe** [comment]
Doesn't seem to work. This

    $ alacritty -e "bash -c 'echo \"this is\" && echo \"a test\"'"

gives the error

    Created log file at "/var/folders/gq/vqbg5g255cqf7x_yn8v3tlyc0000gn/T/Alacritty-4469.log"
    [2020-05-06 21:32:10.405456000] [ERROR] Failed to spawn command 'bash -c 'echo "this 
    is" && echo "a test"'': No such file or directory (os error 2)

**Comment by cole-h** [comment]
Try removing the outer double-quotes, sorry. Otherwise, it'll parse all that's inside the quotes as a single command.

**Comment by chrisduerr** [comment]
Can't quote the entire thing because then that's assumed to be your executable. What @cole-h said works and is the only thing supported in Alacritty.

**Comment by nyngwang** [comment]
> alacritty -e bash -c 'echo "this is" && echo "a test" && sleep 30'

@cole-h: If I made this an executable script, how to pass arguments to it? For example:

```
alacritty -e zsh -c 'echo "this is ${1}" && echo "a test {2}" && sleep 30'
```

But it doesn't receive the two arguments I passed to it.
