### ISSUE TITLE
Add function to hide other windows in macOS

### ISSUE THREAD

**Issue by nathan-cummings-ukaea** [alacritty/alacritty#3697]
In line with the minimalistic ethos - would it be possible to include the command-option-H feature for macOS that hides all windows except the active one? I often use this and it would be great to be able to hide everything else when I'm working in a terminal window.

**Comment by kchibisov** [comment]
It's a job of your system, not alacritty. We're not a window manager. Alacritty doesn't have multi window, so each window is a separate app.  We can't hide your browser, file manager, etc.

**Comment by nathan-cummings-ukaea** [comment]
It's a feature that the system exposes, the same as the hide feature that you have already included. If you don't want to implement it sure but there isn't any other way to have this behaviour on a Mac that I can find.

**Comment by kchibisov** [comment]
Could you post a link to apple docs directly?

**Comment by nathan-cummings-ukaea** [comment]
Sorry, took me a bit since I've never even looked at the apple docs before let alone developed something for Mac, bu this looks like the thing I mean:

https://developer.apple.com/documentation/appkit/nsapplication/1428746-hideotherapplications

**Comment by kchibisov** [comment]
Are you aware of other applications using it? Is it something common and expected on macOS?

**Comment by nathan-cummings-ukaea** [comment]
Yeah all the other apps I use on Mac have it (browsers, outlook, slack, zoom, Skype, blahblahblah...).
Here's a link for reference:
https://osxdaily.com/2018/02/05/hide-all-other-windows-apps-except-active-mac/

**Comment by kchibisov** [comment]
Ok, if it's taht common thing and macOS for whatever reason exposes this API on application level(not a shortcut in a compositor), maybe we should add it.

**Comment by kchibisov** [comment]
I'm not sure where it should be added tbqh, it's either should be, I guess it should be in `winit`.

**Comment by chrisduerr** [comment]
Yeah, should probably be added to `winit`. Also would probably be fairly easy.

**Comment by ryandesign** [comment]
This is covered by #3245 isn't it?

**Comment by chrisduerr** [comment]
As far as I understand it, this would be about adding an action, not only a menu item.

**Comment by nathan-cummings-ukaea** [comment]
> As far as I understand it, this would be about adding an action, not only a menu item.

Exactly this, whether the menu is populated at some point is a separate issue. It would just be really good to have the key binding.

**Comment by ryandesign** [comment]
I'm unfamiliar with Alacritty or its terminology or development methodology, but #3245 is about the fact that Alacritty lacks the standard macOS application menu that all macOS applications should have. Once that standard menu is added, it would contain the standard Hide Alacritty and Hide Others menu items with their standard macOS keyboard shortcuts which would perform those standard macOS actions when chosen. Wouldn't that take care of this request?

**Comment by nathan-cummings-ukaea** [comment]
The menu item being present would not (I believe) automatically give you the functionality. Right now I can use cmd-H to hide Alacritty but I can't use cmd-opt-H to hide others.

**Comment by ryandesign** [comment]
Right. Not automatic. Alacritty would have to call `hideOtherApplications:` when the Hide Others menu item is chosen. macOS, I believe, will handle selecting the menu item for you if the assigned keyboard equivalent is pressed. My point was that this is one of the necessary tasks for resolving #3245.

**Comment by nathan-cummings-ukaea** [comment]
As far as I understand, you could implement menu items as outlined in #3245 but not necessarily include the 'hide others' functionality. So depending on how many menu items are filled, #3245 could be closed without this issue being addressed.

**Comment by ryandesign** [comment]
The Hide [application name], Hide Others and Show All menu items have been part of the Macintosh look and feel since 1991. Implementing them isn't optional. In System 7 thru Mac OS 9, the OS populated the application menu automatically when the application initialized the menu bar. I'm not sure why Apple changed it in Mac OS X to require the application to be involved in the process, but they did, so that's what applications have to do now. If you create a new application in Xcode, all of this is handled automatically, but if Alacritty wasn't made using the Xcode application template then Alacritty gets to reimplement that functionality. #3245 already exists to cover the fact that Alacritty should implement the standard applications menu so I didn't think a separate ticket was needed for this sub-task of that issue, but if the developers want to track it separately that's up to them.

**Comment by nathan-cummings-ukaea** [comment]
Ah that makes it clearer, thank you. The reason why I raised this issue separately was because I was concerned that the menu items could be included in a limited sense without also including the hide others feature. I just don’t want it to be missed.

In a purely selfish sense I use the key bindings rather than the menu, so if we had the ‘hide others’ binding I wouldn’t even mind if there was still no menu.

**Comment by freamon** [comment]
Hi. As others have surmised, this is a straight-forward enough thing to implement, but it requires a minor change in Winit.  If my PR for that project is accepted, I'll be able to add the keybinding so this issue can be fixed.

**Comment by chrisduerr** [comment]
@freamon I think @casperstorm is also working on this. His work goes into a bit more detail IIRC with a more involved PR that also supports the menu entries and automatically implements this using the macOS menu actions.

That said, both of those could probably exist independently in winit, but what @casperstorm is working on is the thing we need in Alacritty. So it might be good to mention that in the PR and maybe have both things working before anything gets merged.

**Comment by casperstorm** [comment]
Correct @kchibisov , I am working on an patch which will add a menubar to MacOS. This is currently missing, which is the reason we don’t have the expected bindings by default. 

Your addition is nice, @freamon but by adding the menubar it will not be needed since it will handle that binding, along a number of other default bindings such as hide self, hide others, etc. I haven’t pushed anything yet but will keep you in the loop then we can maybe make a collaboration on it.

**Comment by freamon** [comment]
Sounds cool.  I read that native menu bars are outside of Winit's scope, so is the intention to add this functionality directly to Alacritty, and invoke the calls via `objc::runtime::Class`? Is there an argument in favour of preferring Winit's API for this kind of stuff (in terms of not duplicating code and abstracting unsafe code)?

**Comment by freamon** [comment]
Hi @nathan-cummings-ukaea.  I won't pursue this further as the authors wish to solve this in a more expansive way, but until then, if you want a temporary version of Alacritty that'll hide other windows with the keyboard shortcut, there's one [here](https://github.com/freamon/alacritty)

**Comment by kamkudla** [comment]
Is there an update to this? I'm taking quite a productivity/flow hit without this standard macOS feature.
