### ISSUE TITLE
cursor doesn't change from block to beam in insert mode

### ISSUE THREAD

**Issue by hsheikhali** [alacritty/alacritty#3701]
When I enter tmux the cursor does not change from block to beam when I change modes. I've tried everything not sure why this is happening ?

### System

OS: macOS
Version: alacritty 0.4.2

**Comment by kchibisov** [comment]
Where it should be changed, are you sure that tmux is setup the way to allow changing cursor? Does it occur outside of the tmux?

**Comment by hsheikhali** [comment]
The issue doesn't occur outside of tmux just inside tmux. not sure why

**Comment by hsheikhali** [comment]
I ended up fixing it anyway.
