### ISSUE TITLE
Export colors to $LS_COLORS, zstyle and others to maintain consistency

### ISSUE THREAD

**Issue by SoptikHa2** [alacritty/alacritty#3705]
Alacritty doesn't set things like `$LS_COLORS` or `zstyle` with color scheme, which causes inconsistency.

`$LS_COLORS` is used by `ls` to determine how to colorize it's output, and `zstyle` is used by `zsh` to, apart from other, colorize autocompletions. There are probably other places where this should be set that I'm not aware of.

When both are left to it's default, the colors differ which doesn't look nice. When I write `ls <tab>`, I see files in my folder colored one way, and when I confirm the command (`ls <enter>`), everything is suddenly printed with another color.

See screenshot. At top: terminator which sets it, at bottom: alacritty. First command is executed `ls`, the second is requesting tab completion for `cat`.

Example of `$LS_COLORS`  as Terminator sets it. Alacritty leaves it empty.
```
rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
```

Diff between terminator and alacritty zstyles:
```diff
9c9
<         :completion:* 'rs=0' 'di=01;34' 'ln=01;36' 'mh=00' 'pi=40;33' 'so=01;35' 'do=01;35' 'bd=40;33;01' 'cd=40;33;01' 'or=40;31;01' 'mi=00' 'su=37;41' 'sg=30;43' 'ca=30;41' 'tw=30;42' 'ow=34;42' 'st=37;44' 'ex=01;32' '*.tar=01;31' '*.tgz=01;31' '*.arc=01;31' '*.arj=01;31' '*.taz=01;31' '*.lha=01;31' '*.lz4=01;31' '*.lzh=01;31' '*.lzma=01;31' '*.tlz=01;31' '*.txz=01;31' '*.tzo=01;31' '*.t7z=01;31' '*.zip=01;31' '*.z=01;31' '*.dz=01;31' '*.gz=01;31' '*.lrz=01;31' '*.lz=01;31' '*.lzo=01;31' '*.xz=01;31' '*.zst=01;31' '*.tzst=01;31' '*.bz2=01;31' '*.bz=01;31' '*.tbz=01;31' '*.tbz2=01;31' '*.tz=01;31' '*.deb=01;31' '*.rpm=01;31' '*.jar=01;31' '*.war=01;31' '*.ear=01;31' '*.sar=01;31' '*.rar=01;31' '*.alz=01;31' '*.ace=01;31' '*.zoo=01;31' '*.cpio=01;31' '*.7z=01;31' '*.rz=01;31' '*.cab=01;31' '*.wim=01;31' '*.swm=01;31' '*.dwm=01;31' '*.esd=01;31' '*.jpg=01;35' '*.jpeg=01;35' '*.mjpg=01;35' '*.mjpeg=01;35' '*.gif=01;35' '*.bmp=01;35' '*.pbm=01;35' '*.pgm=01;35' '*.ppm=01;35' '*.tga=01;35' '*.xbm=01;35' '*.xpm=01;35' '*.tif=01;35' '*.tiff=01;35' '*.png=01;35' '*.svg=01;35' '*.svgz=01;35' '*.mng=01;35' '*.pcx=01;35' '*.mov=01;35' '*.mpg=01;35' '*.mpeg=01;35' '*.m2v=01;35' '*.mkv=01;35' '*.webm=01;35' '*.webp=01;35' '*.ogm=01;35' '*.mp4=01;35' '*.m4v=01;35' '*.mp4v=01;35' '*.vob=01;35' '*.qt=01;35' '*.nuv=01;35' '*.wmv=01;35' '*.asf=01;35' '*.rm=01;35' '*.rmvb=01;35' '*.flc=01;35' '*.avi=01;35' '*.fli=01;35' '*.flv=01;35' '*.gl=01;35' '*.dl=01;35' '*.xcf=01;35' '*.xwd=01;35' '*.yuv=01;35' '*.cgm=01;35' '*.emf=01;35' '*.ogv=01;35' '*.ogx=01;35' '*.aac=00;36' '*.au=00;36' '*.flac=00;36' '*.m4a=00;36' '*.mid=00;36' '*.midi=00;36' '*.mka=00;36' '*.mp3=00;36' '*.mpc=00;36' '*.ogg=00;36' '*.ra=00;36' '*.wav=00;36' '*.oga=00;36' '*.opus=00;36' '*.spx=00;36' '*.xspf=00;36' ''
---
>         :completion:* ''
```

![image](https://user-images.githubusercontent.com/24734779/81488493-dfef4a00-9258-11ea-9e6e-0b9262ee31d8.png)

**Comment by chrisduerr** [comment]
> Alacritty doesn't set things like $LS_COLORS or zstyle with color scheme, which causes inconsistency.

Because it shouldn't. That's up to your system/user config, not Alacritty.

**Comment by SoptikHa2** [comment]
For anyone searching for this: it turns out both variables get filled out automagically when TERM is set to `xterm-256color`, but for some reason it doesn't for `alacritty`. Term envvar can be changed in config.

**Comment by chrisduerr** [comment]
TERM should not be changed to `xterm-256color`, instead the system configuration should be changed to properly set these variables.

**Comment by SoptikHa2** [comment]
Do you know how it's named what I'm looking for? I am not asking for anyone to solve problem with my configuration, but I don't know what to actually search for. I didn't ever dig into this area, so I don't even know what I don't know. Name of the thing that handles this would help me a lot.

**Comment by chrisduerr** [comment]
Probably something in `/etc` like `/etc/bash.bashrc`.

**Comment by kchibisov** [comment]
Or look for `dircolors` in case insensitive form.

**Comment by dnkl** [comment]
> That's the thing doing export LS_COLORS usually, and it checks terminfo by name, with is stupid

@SoptikHa2 @kchibisov I have this in my `/etc/zsh/zshrc` for that exact reason:

```sh
eval $(env TERM=xterm256-color dircolors)
```

Another option is to generate a "dircolors" file and manually adding 'alacritty*' to it, and then explicitly loading that one instead of using the precompiled database.

**Comment by chrisduerr** [comment]
You can also just export the variable, instead of running dircolors every time.

**Comment by crodjer** [comment]
Building on @dnkl's suggestion, made it more `alacritty` specific.

```sh
function colorize_ls() {
    if [ -z "$LS_COLORS" -a -n "$(command -v dircolors)" -a "$TERM" = "alacritty" ]; then
        eval $(env TERM=alacritty-color dircolors)
    fi
}
```
