### ISSUE TITLE
Pane and window line rendering when using font `offset` and `glyph_offset`

### ISSUE THREAD

**Issue by jesseleite** [alacritty/alacritty#3706]
For context, I'm using font `offset` and `glyph_offset` settings to create a nice global line-height effect.  I absolutely love how Alacritty handles this, but if I have one complaint, it's how pane and window lines (ie. in Tmux, in Vim, in various Vim plugins, etc) render when using these offset settings:

![image](https://user-images.githubusercontent.com/5187394/81488867-ef609a00-923c-11ea-9b24-217a5be38f4e.png)

Furthermore, I'm not using any horizontal `x` offset settings (just `y`), but horizontal lines seem to have some sort of bleed/anti-aliasing artifact thing going on (very faint, so I blew this example up a bit):

![Screen Shot 2020-05-09 at 9 39 39 PM](https://user-images.githubusercontent.com/5187394/81488957-fc31bd80-923d-11ea-8d19-30383fd43edb.jpg)

I was thinking it'd be pretty cool to have an opt-in setting that could replace the glyphs used for drawing pane dividers, box-style windows, etc. with custom Alacritty glyphs that would span full width/height of each character cell, regardless of the user's `offset` and `glyph_offset` settings.

Thoughts?

**Comment by chrisduerr** [comment]
> Furthermore, I'm not using any horizontal x offset settings (just y), but horizontal lines seem to have some sort of bleed/anti-aliasing artifact thing going on (very faint, so I blew this example up a bit):

See #118.

> I was thinking it'd be pretty cool to have an opt-in setting that could replace the glyphs used for drawing pane dividers, box-style windows, etc. with custom Alacritty glyphs that would span full width/height of each character cell, regardless of the user's offset and glyph_offset settings.

There is no desire to add this, however there is a plan to make things like `glyph_offset` and `offset` font specific (see #957).
