### ISSUE TITLE
Don't double-fork subprocesses to preserve parent process association

### ISSUE THREAD

**Issue by Deewiant** [alacritty/alacritty#3711]
While trying to work around #3710 (together with #3709) using `xdotool` to set focus back to Alacritty, I ran into the fact that the subprocess's parent PID is 1. This is due to the double-fork done here:

https://github.com/alacritty/alacritty/blob/2c2104a51776ac826dde35f54423657f2d5150fb/alacritty_terminal/src/util.rs#L58-L63

Unfortunately this means that I don't know the PID with which to find the calling Alacritty instance and thus can't find the right X window ID (which would be in its environment) to pass to `xdotool`.

I understand that this simplifies subprocess management and was originally done in #976 as a fix for zombies, but it causes papercuts like this. It would be nice to do the PID management properly and call `waitpid` directly in Alacritty as needed. (For example, `st` does it on `SIGCHLD` and additionally "in the background" e.g. when scrolling, which seems to work well enough in practice.)

**Comment by chrisduerr** [comment]
Calling waitpid in Alacritty is not an option and we should definitely make sure zombies are reaped.

It seems to me like the problem's mostly with what you're trying to do and how you're doing it, rather than how Alacritty handles it. Relying on the process hierarchy to determine processor IDs seems extremely hacky.

What exactly are you trying to achieve?

**Comment by Deewiant** [comment]
Why isn't calling waitpid an option?

Basically, what I wanted was to find the Alacritty instance that started a configured `command`. In my case I wanted to use that in a call to `xdotool windowfocus` to work around #3710, but I imagine there are other conceivable use cases. Using the parent PID for this doesn't seem very hacky to me. The immediate daemonizing of all subprocesses wasn't something I expected.

**Comment by chrisduerr** [comment]
> Why isn't calling waitpid an option?

Because that would require Alacritty to wait for the process? And waiting for every process executed by users that might do anything isn't really what Alacritty should be spending its time and threads on. The ini reaper is much better at that, since it's pretty much its job just to reap whatever.

**Comment by Deewiant** [comment]
Using the `WNOHANG` option, `waitpid` is non-blocking and just checks for process completion, so no actual "waiting" is necessary. Then it's just a matter of finding the time to do that check.

(One could argue that the extra fork is also not something to spend time on, but let's not go there at least without data.)

And sure, as I said I understand the attractiveness and comparative simplicity of deferring to init.

**Comment by chrisduerr** [comment]
> Using the WNOHANG option, waitpid is non-blocking and just checks for process completion, so no actual "waiting" is necessary. Then it's just a matter of finding the time to do that check.

That isn't really much better, it just changes it from blocking to non-blocking. You still have to dedicate resources to continuously check it.

I'd rather support other options than removing the double fork. I think setting an environment variable for Alacritty's PID would be an option, though I'm not sure if there's any actual usecases that aren't mostly abusive.

**Comment by Deewiant** [comment]
It doesn't have to be _continuous_, just frequent enough to not leave lots of zombies around. `st` mostly does it in response to some user-initiated actions, at a glance. But I see your point.

The environment variable would be an alternative for this particular problem, yes. You might be right about the use cases though.

**Comment by chrisduerr** [comment]
I don't see any reason to change this the way things are right now. From Alacritty's perspective I don't see any advantages of having to supervise its subprocesses.
