### ISSUE TITLE
Render issues ? 

### ISSUE THREAD

**Issue by yugioh** [alacritty/alacritty#3712]
## System

OS: Windows (WSL - Ubuntu 18.04)
Version: "Latest package from releases"

Terminal Doesn't render properly, If i copy paste the contents the arrow show there but not in the terminal. Is this a known bug ?

<img width="450" alt="1" src="https://user-images.githubusercontent.com/22428691/81508816-10e88100-9324-11ea-94af-8a8a16e0fb27.PNG">
<img width="345" alt="2" src="https://user-images.githubusercontent.com/22428691/81508821-134adb00-9324-11ea-83ac-531d7d11fc75.PNG">

after pasting the copied contents from #2

<img width="311" alt="3" src="https://user-images.githubusercontent.com/22428691/81508822-147c0800-9324-11ea-85d5-22bc1346f26e.PNG">

**Comment by kchibisov** [comment]
It's fixed on master.
