### ISSUE TITLE
Font Rendering issues

### ISSUE THREAD

**Issue by pianocomposer321** [alacritty/alacritty#3713]
This picture shows it all:

![image](https://user-images.githubusercontent.com/54072354/81509813-e6220c80-92d2-11ea-9079-a58ff7bcf70b.png)

I'm on windows 10, alacritty 0.4.2 (f68de37).

**Comment by kchibisov** [comment]
Do you have OpenGL 3.3. support, it seems like blending function failed.

**Comment by pianocomposer321** [comment]
I don't know, how do I check?

**Comment by chrisduerr** [comment]
You can check using `glxinfo` or just lookup the information about your GPU.

**Comment by kchibisov** [comment]
>You can check using glxinfo or just lookup the information about your GPU.

It's Windows, it doesn't have glx, neither glxinfo. I guess you should check your driver vendor.

**Comment by pianocomposer321** [comment]
I have an Intell HD graphics 3000 GPU. I think I remember having issues with it not working over OpenGL 3.1. Is there any way to make alacritty work with OpenGL 3.1?

**Comment by chrisduerr** [comment]
@pianocomposer321 Yes, though they require recompilation and patching.

See #128.
