### ISSUE TITLE
Mouse button clicks are not seen by tmux (wsl+ubuntu)

### ISSUE THREAD

**Issue by ShrykeWindgrace** [alacritty/alacritty#3717]
Hi!

Thanks for your work, I enjoy using alacritty very much=)

I have a following setup: win10+wsl1+ubuntu (both 18 and 20, issue is present in both of them) + tmux.

If I run my `wsl`  from within `alacritty` (either via `shell: program: wsl ~` or running `wsl ~` in the default powershell), then the tmux option `set -g mouse on` does not seem to have effect - in particular, mouse clicks do not select panes. Other mouse-related functionality seems to be off, too.

On the other hand, if I run the same scenario, but launch `wsl` from whatever host (emulator? my terminology is off here, I'm sure) backing powershell/cmd/bash, mouse-releated features work.

Is it a misconfiguration on my side and there is an alacritty option that I forgot to turn on? Or is it a limitation that can not be overcome? Or even an explicit decision?

I understand that I have quite a few layers where things could go wrong, but to me it seems for now that this issue is alacritty-related.

### System

OS: Windows (win10, winver 1809)
Version: `alacritty 0.4.2 (f68de37)`

Windows backend: ConPTY (per `alacritty -vv`)

WSL1, `Ubuntu-18.04` and `Ubuntu-20.04`

tmux -V: 3.0a/3.1b

**Comment by kchibisov** [comment]
It depends on Windows version you're using. See https://github.com/alacritty/alacritty/issues/1663

**Comment by ShrykeWindgrace** [comment]
@kchibisov got it, thanks!
