### ISSUE TITLE
Consider option to print default alacritty.yml

### ISSUE THREAD

**Issue by noahp** [alacritty/alacritty#3724]
The default config file generation was removed in #2818 in favor of pointing users to the `alacritty.yml` file published on the github release page (and I think intended to be bundled in system package manger distributions, eg https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/alacritty#n36 ).

Would it be desirable to add an option eg `--generate-config`, that prints out the default `alacritty.yml` to stdout?

**Comment by chrisduerr** [comment]
No, the configuration file reference should be shipped by distributors to document the available options, however it should not be encouraged to just dump the entire default config into the user config directory.

Instead, the config file should be selectively used with only options necessary for changes, to prevent things from breaking in future updates. So adding a flag would not only be unnecessary for about 99.9% of the time Alacritty is used, it might also be actively harmful.

**Comment by noahp** [comment]
Thanks for the response!
