### ISSUE TITLE
Does not generate alacritty.yaml file

### ISSUE THREAD

**Issue by glepnir** [alacritty/alacritty#3728]
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

OS: mac os 
Version: alacritty 0.4.2 (f68de37)
Linux/BSD: X11/Wayland, DE or Compositor and WM
Windows: WinPTY/ConPTY (see `alacritty -v` output)

### Problem

Seems like the  alacritty doesn't generate `.config/alacritty/alacritty.yaml` file now.

**Comment by kchibisov** [comment]
We don't generate config, right.
