### ISSUE TITLE
Neovim display

### ISSUE THREAD

**Issue by griglab** [alacritty/alacritty#3733]
Hi, all.
Why neovim in alacritty has empty space after command line?
The gnome-terminal has the same problem, but kitty doesn't...
On image: alacritty, gnome-terminal, kitty.

![terminals](https://user-images.githubusercontent.com/64154656/82128816-ab364200-97c6-11ea-881b-509fc5192213.png)

OS: Ubuntu 20.04
Version: alacritty 0.4.1
Linux/BSD: Wayland, DE Gnome, WM Mutter

![alacritty_vv](https://user-images.githubusercontent.com/64154656/82128831-da4cb380-97c6-11ea-8f61-9030c8047ab5.png)

**Comment by kchibisov** [comment]
It's called padding, and is common for all terminals, kitty included, it's purely based on your fontsize, and other metrics.
