### ISSUE TITLE
Background opacity not working

### ISSUE THREAD

**Issue by geerizzle** [alacritty/alacritty#3739]
OS: Arch Linux
Shell: Bash
WM: spectrwm on X11

So when i try to apply the background opacity to my terminal, the background just gets darker, but not transparent. The value of 0 just sets the background color to black.

**Comment by chrisduerr** [comment]
Are you running a compositor?

**Comment by geerizzle** [comment]
@chrisduerr No, should I install one to enable the option?

**Comment by geerizzle** [comment]
No need for any more help, I installed and set picom up without any problems and got the opacity working without any bugs. Thanks for pointing the possible error out @chrisduerr.
