### ISSUE TITLE
Natural text editing not working in alacritty

### ISSUE THREAD

**Issue by mrprofessor** [alacritty/alacritty#3743]
### System

OS: macOS
Version: `alacritty 0.4.2 (f68de37)`

### Issue

Can't figure out how to enable natural text editing
e.g. (
cmd + delete = deletes the whole line
cmd + right arrow = Goes to the end of the line 
) etc.

**Comment by chrisduerr** [comment]
What about that is natural text editing exactly? Command bindings aren't forwarded to applications running inside the terminal and they shouldn't be.

**Comment by mrprofessor** [comment]
@chrisduerr 
Recently I moved from iTerm2 to alacritty. I was looking for a solution to the following problem.

https://apple.stackexchange.com/questions/136928/using-alt-cmd-right-left-arrow-in-iterm

`Command bindings aren't forwarded to applications running inside the terminal and they shouldn't be.` Iterm2 does it quite successfully So was wondering if Alacritty supports anything like that.

![image](https://user-images.githubusercontent.com/11652364/82240586-47438300-9958-11ea-98dc-0e0fb8f0ceb2.png)

**Comment by kchibisov** [comment]
Yeah, add those bindings yourself in alacritty.yml.
