### ISSUE TITLE
How to display block character nicely?

### ISSUE THREAD

**Issue by zer09** [alacritty/alacritty#3744]
How to make block character to display nicely? This is the result on Kitty and Gnome terminal

![Screenshot from 2020-05-18 20-59-37](https://user-images.githubusercontent.com/780780/82215901-a8fcf080-994a-11ea-9171-993fae80db9c.png)

And this is the result in Alacritty

![Screenshot from 2020-05-18 17-50-12](https://user-images.githubusercontent.com/780780/82214304-325ef380-9948-11ea-89c2-e3b06e6e2e3a.png)

I was able to achieved result in the first picture in Alacritty by setting the `font.offset.y: -4` but the overall text become to close together, that will overlap the highlights.

I was unable to find the solution in google, my google-fu is not working :smile: 

### System

OS: Pop OS 19.10
Version: alacritty 0.4.1
Linux/BSD: GNOME 3.34.2

### Logs

Crashes: None
Font/Terminal size: SFMono Nerd Font light, size: 13
Keyboard and bindings: None

**Comment by chrisduerr** [comment]
The solution is to use a font that has the correct line height for those characters. Ideally box drawing characters should be part of every monospace font meant to be used in a terminal.

Better support for changing the font sizes and offsets of individual fonts should be offered by #957.

An issue tracking the resolution of properly sized box drawing characters overlaying incorrectly can be found here: #118.

There is no desire to have these built into Alacritty, which is what other terminal emulators like Kitty do.
