### ISSUE TITLE
Alt + arrow-keys writes ;3D ;3C etc instead of jumping by words

### ISSUE THREAD

**Issue by ns-cweber** [alacritty/alacritty#3745]
Alt + arrow-keys write `;3D`, `;3C`, etc to the screen (with bash). This doesn't happen in other emulators, so I think it's an issue with alacritty. When I use bash in tmux, it writes `3D`, `3C` (same as without tmux, except without the semicolon prefix).

### System

OS: macOS
Version: alacritty 0.4.2

**Comment by kchibisov** [comment]
Yeah, it's correct and it what it should send. If you do `cat` it should send `^[[1;3D` and `^[[1;3C` for those keys.

Spec https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-PC-Style-Function-Keys

**Comment by the-emmons** [comment]
For those that haven't run into this before using bash, the fix is to assign the control sequences to a specific action in the `~/.inputrc` file with something like the following:
```"\e[1;3C": forward-word```
```"\e[1;3D": backward-word```
