### ISSUE TITLE
Inconsistent behavior when switching alacritty between displays on OSX

### ISSUE THREAD

**Issue by felippemr** [alacritty/alacritty#3752]
Hey folks, I updated alacritty yesterday and started experiencing an odd issue:

If I use the main MBP display(MBP 2019 with retina):
<img width="853" alt="Screen Shot 2020-05-20 at 1 34 16 PM" src="https://user-images.githubusercontent.com/2388162/82495092-731d5080-9a9f-11ea-9528-76f187c4003b.png">

If I use my secondary monitor(HP 27er):
![Screen Shot 2020-05-20 at 1 34 06 PM](https://user-images.githubusercontent.com/2388162/82495190-97792d00-9a9f-11ea-8e9c-22cb529592bc.png)

The font in the latter is significantly different. I totally understand that the quality would not be the same since the retina is a way better monitor than my secondary, but I don't experience the same with other apps.

### System

OS: OSX 10.15.4(Catalina)
Version: `0.1.0`

**Comment by kchibisov** [comment]
>Version: 0.1.0

Are you sure that that's your alacritty version? In that case, please update to the latest one.

**Comment by felippemr** [comment]
```
 ~  Projects  alacritty  master  $  git l -n 1
ab1f173 2020-05-17 (HEAD -> master, base_origin/master) Add subpixel anti-aliasing support on macOS 10.14+ [GitHub]
```

I am on the latest commit and built the project yesterday.

**Comment by felippemr** [comment]
hmmm, my alacritty binary was created in 2018.... weird.

**Comment by kchibisov** [comment]
I'm just saying that the latest version on master is `alacritty 0.5.0-dev (ab1f173)`, which you can get by `alacritty --version`.

**Comment by felippemr** [comment]
Ok, I looked at https://github.com/alacritty/alacritty/commit/ab1f173ccd20001aafe2f5b3268423861b0ecdfe and changed my config to set `use_thin_strokes` to `false`. It is perfect now!

**Comment by felippemr** [comment]
@kchibisov FIY.
```
 ~  Projects  alacritty  master  $  alacritty --version
alacritty 0.1.0
```

**Comment by kchibisov** [comment]
Could you try `cargo run -- --version`?

**Comment by felippemr** [comment]
```
     Running `target/debug/alacritty --version`
alacritty 0.5.0-dev (ab1f173)

```

**Comment by felippemr** [comment]
I am going to close this since my issue has been solved. Thanks!

**Comment by kchibisov** [comment]
I guess you have a very old version of alacritty somewhere on the system in a path, however you're using the correct one globally, because you likely install application file in `/Applications`, so I guess you should remove it from `.cargo/bin/alacritty`???.
