### ISSUE TITLE
Remove the default padding at the bottom

### ISSUE THREAD

**Issue by mrprofessor** [alacritty/alacritty#3755]
I have set the padding to `0` but I still see the bottom padding. Is there any way to remove this.

It kinda looks ugly if my vim and alacritty colorschemes are different.

### System

OS: macOS
Version: `alacritty 0.4.2 (f68de37)`

![image](https://user-images.githubusercontent.com/11652364/82525974-5a20a800-9b50-11ea-9544-6b5345c6bf12.png)

![image](https://user-images.githubusercontent.com/11652364/82526309-50e40b00-9b51-11ea-8e93-9310b9f5c8e0.png)

**Comment by kchibisov** [comment]
Thos is how terminal works, you can't display half of the cell. Try dynamic padding or resize a terminal.

**Comment by alekspickle** [comment]
So it's just the way it works on the small monitors like laptops? dynamic padding did a bit better by splitting this leftover to both bottom and top, but it's not perfect.

**Comment by chrisduerr** [comment]
> So it's just the way it works on the small monitors like laptops?

Yes, that's how it works on any output.

**Comment by benmanbenman** [comment]
> **UPD** In my case I fixed it by setting size +0.5 in `alacritty.yml` btw
Where did you set it?

**Comment by alekspickle** [comment]
@benmanbenman experiment with text size in alacritty config
