### ISSUE TITLE
Rebinding Terminate, kill and Background commands

### ISSUE THREAD

**Issue by FelixMo42** [alacritty/alacritty#3757]
I was wondering if there was any way to add bindings to terminate a process.

I was looking at #1919 and it said that I could rebind the Terminate actions, but I tried that and It doesn't appear to work.

Is there any way to do it? If not, are there any plans to add the functionality?

**Comment by kchibisov** [comment]
By default it's done by ctrl+c, there's no action to 'terminate the program', and ctrl + c isn't binded directly either. Also, ctrl + c doesn't mean to terminal the program, it's usually sends SIGINT. To rebind them, just send the same characters which ctrl + c is sending. For ctrl + c the character is `\x03`.

**Comment by renatofrota** [comment]
For those interested:

```
key_bindings:
  - { key: V,         mods: Control,       action: Paste            }
  - { key: C,         mods: Control,       action: Copy             }
  - { key: C,         mods: Control|Shift, chars: "\x03"            }
```

I think Control|Short could be set `chars: "\x03"` automatically when Control+C is set to `action: Copy` (it's default in several terminal emulators).

**Comment by santiyounger** [comment]
> key_bindings:
>   - { key: V,         mods: Control,       action: Paste            }
>   - { key: C,         mods: Control,       action: Copy             }
>   - { key: C,         mods: Control|Shift, chars: "\x03"            }

Thanks for this it worked perfectly!

**Comment by Chiradeep-Banik** [comment]
Not Working for me @renatofrota 
```
    { key = "C", mods = "Control", action = "Copy" },
    { key = "V", mods = "Control", action = "Paste" },
    { key = "C", mods = "Control|Shift", chars = "\x03"},
```

for me it is just prniting the chars

**Comment by renatofrota** [comment]
@Chiradeep-Banik apparently you are adding quotes wrongly

**Comment by Chiradeep-Banik** [comment]
@renatofrota I used the same quotes for chars as mentioned above....

**Comment by probablySophie** [comment]
@Chiradeep-Banik 

If you're still having that issue, I think it _may_ be `TOML` vs `YAML` thing.
I managed to get it working with:

`{ key = "C", mods = "Control|Shift", chars = "\u0003" }, # Rebind cancel`

Obviously changing the key & mods as you desire
