### ISSUE TITLE
Multiple files dragging.

### ISSUE THREAD

**Issue by mysliwy112** [alacritty/alacritty#3767]
Dropping multiple files into terminal, doesn't generate spaces between filenames, rendering this function kinda useless.

https://github.com/alacritty/alacritty/issues/1335#issuecomment-397305237
In this usage case it would probably be more useful to use quotation marks for names, because inserting them between multiple names would be time-taking and misleading.

**Comment by chrisduerr** [comment]
Could you share the output of `alacritty --print-events | grep `Dropped`?

**Comment by mysliwy112** [comment]
Eh I should probably add this too:

OS: Windows 7
Backend: WinPTY
Alacritty: 0.4.2

Log:
```
[2020-05-26 09:39:57.818004000] [INFO] glutin event: WindowEvent { window_id: WindowId(WindowId(0xa03c0)), event: DroppedFile("E:\\a - b.txt") }
[2020-05-26 09:39:57.819004000] [INFO] glutin event: WindowEvent { window_id: WindowId(WindowId(0xa03c0)), event: DroppedFile("E:\\b - c.txt") }
[2020-05-26 09:39:57.819004000] [INFO] glutin event: WindowEvent { window_id: WindowId(WindowId(0xa03c0)), event: DroppedFile("E:\\a.txt") }
```

Using bash for this one, but problem works identical with cmd and powershell.
Alacritty window:
`$ E:\a - b.txtE:\b - c.txtE:\a.txt`

**Comment by chrisduerr** [comment]
This isn't windows specific. Fundamentally the problem is just that every file dropped is completely separate. So we don't get an event that three files were dropped but three events that one file was dropped.

So we can't just easily add a space between these, unless we want to add a space after every dropped file. Though I think that might make some sense? What do you think @kchibisov?

**Comment by kchibisov** [comment]
>So we can't just easily add a space between these, unless we want to add a space after every dropped file. Though I think that might make some sense? What do you think @kchibisov?

we can. we also can record a timestamp and try to insert space before dragged file, if one more event appeared to soon.

**Comment by chrisduerr** [comment]
Making it timing based makes little sense, if anything it should be based on input being received between two files. Though an upper limit might be useful.

**Comment by kchibisov** [comment]
I feel like simply adding space in the end should work just fine tbqh.

**Comment by chrisduerr** [comment]
Yeah, I agree. Would be trivial to fix too if it's not desired by simply backspacing once.
