### ISSUE TITLE
Utf-8 error when deleting Russian letters when they are submitted for input

### ISSUE THREAD

**Issue by Tomarchelone** [alacritty/alacritty#3769]
I give an input that contains russian characters to my python program. All works fine until I delete a russian character with `Backspace`. Python then raises an UTF-8 error. Default Mint terminal does this with no errors.

**How to reproduce:** create a python script containing this one line:
`input()`
run it and then type a russian letter (for example `Б`), then delete it via `Backspace` and hit `Enter`

It outputs something like

`Traceback (most recent call last):
  File "test.py", line 1, in <module>
    input()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 0: unexpected end of data`

### System

OS: Linux Mint 19.3
Version: 0.4.2
X11

**Comment by chrisduerr** [comment]
I've looked a bit at python and it might require actually checking the python executable rather than the libraries it uses. Alacritty itself seems to pass the correct things though and there's no modes set that could cause any issues.

This also seems to happen in tmux though, but no other terminal I've tested shows this behavior.

**Comment by kchibisov** [comment]
Note, tmux was tested in `vte` terminal, which doesn't show this behavior on its own.

**Comment by kchibisov** [comment]
Can you try executing `stty iutf8` before your script?

**Comment by Tomarchelone** [comment]
> I've looked a bit at python and it might require actually checking the python executable rather than the libraries it uses.

This utf-8 error also arises when using Rust instead of Python

> Can you try executing `stty iutf8` before your script? You can just type it in terminal, I guess.

Did it, the error is still there

**Comment by kchibisov** [comment]
>Did it, the error is still there

could you type `stty` after that and show me the output?

**Comment by Tomarchelone** [comment]
> could you type `stty` after that and show me the output of it? There's no way it doesn't fixes the issue, since it's exactly encoding thing.

`speed 38400 baud; line = 0;
-brkint -imaxbel`

**Comment by kchibisov** [comment]
Seems like you're doing it wrong?

After doing `stty iutf8`, the output of `stty` should be like.
```
speed 38400 baud; line = 0;
-brkint -imaxbel iutf8
```

**Comment by Tomarchelone** [comment]
> Seems like you're doing it wrong?

![Снимок экрана от 2020-05-27 01-29-18](https://user-images.githubusercontent.com/29727534/82956577-c1f44a00-9fb9-11ea-9d80-1adaa7c56a47.png)

**Comment by kchibisov** [comment]
Interesting, so yeah, that's why it's not working, could you try #3770 ? I'm not entirely sure why `stty` is no-op for you, but anyway.

I'll assume your other terminal has it in output by default, so if you type `stty` in it, it should show `iutf8`.

**Comment by dnkl** [comment]
Zsh, for example, can "freeze" the terminal settings (with `ttyctl -f`). Any changes to the terminal attributes after that are non-persistent.

https://wiki.archlinux.org/index.php/Zsh#The_ttyctl_command

**Comment by kchibisov** [comment]
>Zsh, for example, can "freeze" the terminal settings (with ttyctl -f). Any changes to the terminal attributes after that are non-persistent.

Oh, if it's zsh then yes, that could be the case, but it shouldn't do that by default, unless you have tons of configs. Though, I have no idea what shell is being used here, and default zsh comes with plain config.

I'd recommend to try `alacritty -e bash` then or mentioned PR.
