### ISSUE TITLE
Issue with rendering nerd fonts

### ISSUE THREAD

**Issue by sherubthakur** [alacritty/alacritty#3772]
### System
OS:
  System Version:	macOS 10.15.4 (19E287)
  Kernel Version:	Darwin 19.4.0

Alacritty Version: alacritty 0.4.2 (f68de37)

### Logs

Crashes: No crash
Output of`alacritty -vv`:
```
Created log file at "/var/folders/wc/gxbg86ws4mn6b7j2lntjfjw40000gp/T/Alacritty-96289.log"
[2020-05-27 06:00:35.996631000] [INFO] Welcome to Alacritty
[2020-05-27 06:00:35.998127000] [INFO] Configuration loaded from "/Users/sherub/.config/alacritty/alacritty.yml"
[2020-05-27 06:00:36.056800000] [DEBUG] Estimated DPR: 2
[2020-05-27 06:00:36.057335000] [DEBUG] Estimated Cell Size: 16 x 33
[2020-05-27 06:00:36.057385000] [DEBUG] Estimated Dimensions: Some((1288, 800))
[2020-05-27 06:00:36.127936000] [INFO] Device pixel ratio: 2
[2020-05-27 06:00:36.131927000] [INFO] Initializing glyph cache...
[2020-05-27 06:00:36.173883000] [INFO] ... finished initializing glyph cache in 0.041786217s
[2020-05-27 06:00:36.175506000] [INFO] Estimated DPR correctly, skipping resize
[2020-05-27 06:00:36.175571000] [INFO] Cell Size: 16 x 33
[2020-05-27 06:00:36.175619000] [INFO] Padding: 4 x 4
[2020-05-27 06:00:36.175676000] [INFO] Width: 1288, Height: 800
[2020-05-27 06:00:36.175915000] [INFO] PTY Dimensions: Line(24) x Column(80)
[2020-05-27 06:00:36.180265000] [INFO] Initialisation complete
[2020-05-27 06:00:40.321596000] [DEBUG] New num_cols is 179 and num_lines is 54
[2020-05-27 06:00:40.323597000] [INFO] Width: 2880, Height: 1800
```
Output of `alacritty --print-events`
NOTE: This is prints a lot of stuff out.

## Other potentially relevant info
I only have 2 user fonts as shown by Font Book
<img width="898" alt="Screenshot 2020-05-27 at 6 05 56 AM" src="https://user-images.githubusercontent.com/10345612/82963321-2fb36c80-9fe0-11ea-887a-183299841e87.png">

I am using this font in iterm and google chrome where all the symbols are visible.

Image showing comparison of what iterm renders and what alacritty renders
<img width="1343" alt="Screenshot 2020-05-27 at 5 42 36 AM" src="https://user-images.githubusercontent.com/10345612/82963392-66898280-9fe0-11ea-9464-00431f4bebe0.png">
- Font in iterm was selected using the dropdown.

### Relevant section of alacritty config.
```yml
# Font configuration (changes require restart)
font:
  # Normal (roman) font face
  normal:
    family: Hack Nerd Font Mono
    style: Regular

  # Bold font face
  bold:
    family: Hack Nerd Font Mono
    style: Bold

  # Italic font face
  italic:
    family: Hack Nerd Font Mono
    style: Italic

  # Bold italic font face
  bold_italic:
    family: Hack Nerd Font Mono
    style: Bold Italic

  # Point size
  size: 14.0
```

### Output of `fc-list | grep Hack`
```
/Users/sherub/Library/Fonts/Hack Bold Nerd Font Complete Mono.ttf: Hack Nerd Font Mono:style=Bold
/Users/sherub/Library/Fonts/Hack Regular Nerd Font Complete Mono.ttf: Hack Nerd Font Mono:style=Regular
/Users/sherub/Library/Fonts/Hack Italic Nerd Font Complete.ttf: Hack Nerd Font:style=Italic
/Users/sherub/Library/Fonts/Hack Bold Nerd Font Complete.ttf: Hack Nerd Font:style=Bold
/Users/sherub/Library/Fonts/Hack Italic Nerd Font Complete Mono.ttf: Hack Nerd Font Mono:style=Italic
/Users/sherub/Library/Fonts/Hack Bold Italic Nerd Font Complete Mono.ttf: Hack Nerd Font Mono:style=Bold Italic
/Users/sherub/Library/Fonts/Hack Bold Italic Nerd Font Complete.ttf: Hack Nerd Font:style=Bold Italic
/Users/sherub/Library/Fonts/Hack Regular Nerd Font Complete.ttf: Hack Nerd Font:style=Regular
```

NOTE:
I tried to go through all the font issues with MacOS tag but nothing there helped me. :(

**Comment by kchibisov** [comment]
try latest pre release https://github.com/alacritty/alacritty/releases

**Comment by sherubthakur** [comment]
@kchibisov Everything works in the latest release candidate. i.e. v0.4.3-rc1. Probably worthwhile to add this info to the readme? As a lot of folks will end up facing this issue. Kudos on such a speedy reply. And most importantly awesome job with it. I am moving over to alacritty from iterm.

**Comment by kchibisov** [comment]
it's added, it's a locale problem and you're using tmux.

**Comment by kchibisov** [comment]
To overcome this problem without latest rc just set it in config or use `tmux -u`.

**Comment by sherubthakur** [comment]
@kchibisov I tried running it without tmux too. It did not work there too. Unsure what you mean by locale problem.

**Comment by kchibisov** [comment]
try `LC_ALL=C tmux` (kill tmux server before doing ), you'll see the same problem even on a new release.

**Comment by thanhnguyen2187** [comment]
I am having the same problem even though my Alacritty's version is 0.6.0-dev installed using `apt install alacritty` on Pop OS. Can you elaborate on the locale problem?
![image](https://user-images.githubusercontent.com/27758849/98114813-6323ec80-1ed8-11eb-98bb-454132cfd12f.png)

**Comment by dessalines** [comment]
This is still an issue.

**Comment by Tony-Sol** [comment]
*passerby tip*
using
```yaml
family: JetBrainsMono Nerd Font
```
instead of
```yaml
family: JetBrains Mono Nerd Font
```
works for me with brew-installed nerd font
