### ISSUE TITLE
Alacritty uses 100% CPU in idle state if left on its own for several days

### ISSUE THREAD

**Issue by SoptikHa2** [alacritty/alacritty#3775]
OS: Linux
Version: `alacritty 0.4.2`
X11, `picom vgit-e553e`, `i3-gaps i3 version 4.18.1 (2020-04-23)`

I left alacritty run for quite a some time, and after a while, I discovered an unpleasant surprise. Each alacritty instance was maxed at 100% cpu usage.
![image](https://user-images.githubusercontent.com/24734779/82998202-f63a2b80-9ff6-11ea-9fc5-ef1192d01713.png)

Restarting alacritty helped and everything returned to it's normal state. I know this is extremely low-priority bug and hard to debug, but I put this here just in case someone finds something interesting linked to this.

**Comment by kchibisov** [comment]
Could you show the usage by threads pls, it could actually help? Also, enable thread names pls and a tree view in htop.

**Comment by kchibisov** [comment]
So it should look like

![picture](https://user-images.githubusercontent.com/27620401/82998956-0bbc4f00-a011-11ea-93b5-66e92d56b6cd.png)

**Comment by SoptikHa2** [comment]
I unfortunately already closed it, but I'll get back to this in few days. I'll also enable log, which should help a bit as well.

**Comment by kchibisov** [comment]
Yeah, enable persistent logging for those things. Log has pid in the end, so shouldn't be that hard to find a proper one.

**Comment by kchibisov** [comment]
Also, make sure to have binary with debug symbols, backtrace from a thread with `100%` CPU usage will be very helpful.

**Comment by SoptikHa2** [comment]
Ok, my system version is stripped so I'll compile my own.

> backtrace from a thread with `100%` CPU usage will be very helpful

how do I get relevant info from it afterwards?

**Comment by kchibisov** [comment]
To attach:

`sudo gdb -p PID`.

To list threads in gdb
```
info threads 
```

Then `thread NUMBER`. and then `bt full` in this thread.

**Comment by chrisduerr** [comment]
@SoptikHa2 Could you also share your configuration file please?

**Comment by SoptikHa2** [comment]
Sure, this is the version that was used when I had the problem: [alacritty.yml](https://github.com/SoptikHa2/archlinux-dotfiles/blob/2e65fd8ec01d4f5ff23a00d95d8e430aa85af7c4/alacritty.yml)

Currently I'm running test both with the config file linked above and no config file at all (`/dev/null`).

**Comment by SoptikHa2** [comment]
I found the trigger! It's not being left alone for days, it's X crashing. (Btw I can confirm this happens in latest master I built, which was 88d87cfa86b4c4c14851a1901a6dbe59752044ad)

Sometimes when [Caprine](https://github.com/sindresorhus/caprine) (electron application) stays turned on for days, it starts eating literally gigabytes of RAM. So I kill it once in a few days if this happens. I kill it with i3 keybinding that executes `kill`:
```
# kill focused window
bindsym $mod+Shift+q kill
```

This crashes X once in a while for some reason I'm yet to find (or something like that - I'm pushed back into real terminal). When I log back in, all the applications seem to be running in the background - including alacritty. 

Once this happens, alacritty (and picom, other apps seems fine) starts using 100% CPU. This happens in all alacritty instances, regardless of used config.

Backtrace (alacritty with `/dev/null` config file):
[gist](https://gist.github.com/SoptikHa2/ab7eff5f5cac4b66199d229422cd2562)

I'm attaching htop screenshot - is this enough? I'm not sure if I set it up properly. I'll not kill alacritty this time until tomorrow morning (about 6 hours), so if you need more info, just ask. Unfortunately I'll need to use my laptop outside, so I won't be able to keep alacritty running at 100% CPU usage because of battery. If I figure out if there is a way to freeze alacritty I'll keep it alive as long as needed.

**Comment by kchibisov** [comment]
>and picom

Both are opengl apps, so could you try `glxgears` as well? the stack trace is in nvidia driver and I feel like some threads are hidden from us for whatever reason, anyway, are you using proprietary nvidia driver or nouveau?

**Comment by SoptikHa2** [comment]
I'll try it, but it might take a while to reproduce xorg segfault, it doesn't work all the time.

I'm using proprietary drivers.

**Comment by chrisduerr** [comment]
This seems to be a problem with your system, not Alacritty. If X is killed, Alacritty should shut down correctly and it does for me. If your system has stability problems, those should be addressed, instead of trying to make Alacritty somehow work around that.

If there are still problems without crashing, please let me know and we can look into it again. But for now it seems like the solution is to fix your system.

**Comment by SoptikHa2** [comment]
Alacritty does indeed shut down if X is killed. However, if X segfaults, no apps shutdown at all. At this point, alacritty and picom are the only ones to start hogging all my CPU. Therefore alacritty is incorrectly handling this situation.

I have personally no interest in getting this fixed. As the issue is very rare to manifest, it's trivial to work around, and even if it was fixed, it won't change anything (the workaround - killing alacritty and starting it again - would be needed anyway). But I strongly disagree with the claim that this is not a problem with alacritty. It should not drain all my CPU in any case. So while the potential fix would be probably very difficult to implement and would bring no improvement at all, this is a bug within alacrity (and picom).

**Comment by kchibisov** [comment]
I mean the problem is somehow related to OpenGL apps, I feel like `glxgears` will also show this problem.
