### ISSUE TITLE
Sequential lag in input/output rendering when a compositor is enabled

### ISSUE THREAD

**Issue by pvonmoradi** [alacritty/alacritty#3779]
When I enable a compositor like compton v7 or [picom](https://github.com/yshui/picom) or [a fork of it](https://github.com/ibhagwan/picom), switch to a workspace without any windows and run alacritty, its window shows up but shows erratic behavior. For example at startup, it doesn't print out the PS1, on hitting key "l", it prints PS1 but doesn't print "l", on hitting "s", it prints "l", on "enter" it prints the output of "ls", but again doesn't render the next prompt and PS1. It somehow is one step behind in rendering the interactions. 
I've only catched this error on spawning alacritty on a workspace which has no other windows. Otherwise it seems to be working fine.

### System
OS: Linux Xubuntu 18.04, laptop, intel iGPU 5500 (i7-5600U)
Version: alacritty 0.4.3-rc1 (also exists in 0.4.2)
Linux/BSD: i3-gaps

**Comment by kchibisov** [comment]
And ofc you can't repro that without a compositor?

**Comment by pvonmoradi** [comment]
@kchibisov Yes, can't be reproduced without a compositor.

**Comment by chrisduerr** [comment]
Which mesa version are you running?

**Comment by pvonmoradi** [comment]
@chrisduerr OpenGL version string: 3.0 Mesa 19.2.8
$ glxinfo | rg mesa
```
    GLX_INTEL_swap_event, GLX_MESA_copy_sub_buffer, GLX_OML_swap_method, 
client glx vendor string: Mesa Project and SGI
    GLX_INTEL_swap_event, GLX_MESA_copy_sub_buffer, 
    GLX_MESA_multithread_makecurrent, GLX_MESA_query_renderer, 
    GLX_MESA_swap_control, GLX_OML_swap_method, GLX_OML_sync_control, 
    GLX_EXT_visual_rating, GLX_INTEL_swap_event, GLX_MESA_copy_sub_buffer, 
    GLX_MESA_query_renderer, GLX_MESA_swap_control, GLX_OML_swap_method, 
Extended renderer info (GLX_MESA_query_renderer):
    Device: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2)  (0x1616)
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.2.8
    GL_KHR_robustness, GL_MESA_framebuffer_flip_y, GL_MESA_pack_invert, 
    GL_MESA_shader_integer_functions, GL_MESA_texture_signed_rgba, 
OpenGL version string: 3.0 Mesa 19.2.8
    GL_KHR_robustness, GL_MESA_pack_invert, GL_MESA_shader_integer_functions, 
    GL_MESA_texture_signed_rgba, GL_MESA_window_pos, GL_NV_blend_square, 
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 19.2.8
    GL_MESA_framebuffer_flip_y, GL_MESA_shader_integer_functions, 
```

**Comment by pvonmoradi** [comment]
Some updates:
If I choose xrender backend instead of glx, the problem doesn't show up. Also changing these options seem to affect the issue:  
```
# Other
# backend = "xrender";
backend = "glx";
mark-wmwin-focused = true;
mark-ovredir-focused = true;
# use-ewmh-active-win = true;
detect-rounded-corners = true;
detect-client-opacity = true;
refresh-rate = 0;
vsync = true;
# sw-opti = true;
```

**Comment by chrisduerr** [comment]
@pvonmoradi Does it work with any other application, especially OpenGL?

Sounds like it might just be a driver support/picom issue.

**Comment by pvonmoradi** [comment]
@chrisduerr Xfce4-terminal works fine in either case. I haven't been able to catch similar behavior in gVim, VLC, FF.

**Comment by kchibisov** [comment]
Non of them are OpenGL applications though.

**Comment by pvonmoradi** [comment]
@kchibisov I clone/built/tested [these](https://github.com/Immediate-Mode-UI/Nuklear/tree/master/demo/x11_opengl2) [apps](https://github.com/Immediate-Mode-UI/Nuklear/tree/master/demo/x11_opengl3). Are they OpenGL?

**Comment by kchibisov** [comment]
yeah, you can also test some `mesa demos` like glxgears.

**Comment by GreeMPeace** [comment]
Hey
Just wanted to let you guys know that I am having a similar issue. I am currently testing out some new software tools on my soon-to-be replaced Ubuntu installation. I get this problem whenever I maximize a window (doesn't matter if it is on an empty workspace or not). I have found no other cause yet, resizing, pinning left, upper, lower, or right half of the monitor all no problem. 

Specs:
OS: Ubuntu 16.04
CPU: Intel(R) Core(TM) i7-7700HQ
GPU: Intel(R) HD Graphics 630 (Kaby Lake GT2) & NVIDIA GeForce GTX 1050 Mobile
WM/Compositor: Compiz 0.9.12.3
OpenGL version string: 3.0 Mesa 18.0.5
alacritty 0.5.0-dev (2b2b2bf)

I also ran glxgears for a bit at it seemed to produce 60 FPS no matter if it was a small window or maximized.
Maybe this helps fixing it

**Comment by Janiczek** [comment]
I'm also seeing this issue.

**Comment by twidxuga** [comment]
+1 on this issue using Picom on I3 window manager. I reproduced this issue with  --print-events (attached) while pressing 'l' (scancode 38) repeatedly. The last two 'l' input events are an example of this problem: I pressed 'l' and the character didn't appear until I pressed it again, by which time two 'l' characters were shown.  

[alacritty.print-events.log](https://github.com/alacritty/alacritty/files/4946668/alacritty.print-events.log)

**Comment by ondt** [comment]
Looks like [Kitty](https://github.com/kovidgoyal/kitty) has similar issues. It refreshes the window content on every other keypress.

OS: Ubuntu 20.04
WM: bspwm
Compositor: compton v7
OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.0.8
Alacritty version: 0.4.3, 0.6.0-dev
Kitty version: 0.15.0

**Comment by starcraft66** [comment]
I'm having this exact problem using i3 + picom compositor and alacritty on NixOS.
OS: NixOS 20.03
Terminal: alacritty: 0.4.3
Compositor: picom: v7.5
Window Manager: i3 version 4.17.1 (2019-01-27) © 2009 Michael Stapelberg and contributors

**Comment by ondt** [comment]
> Looks like [Kitty](https://github.com/kovidgoyal/kitty) has similar issues. It refreshes the window content on every other keypress. It happens only occasionally though (both alacritty and kitty).
> 
> OS: Ubuntu 20.04
> WM: bspwm
> Compositor: compton v7
> OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.0.8
> Alacritty version: 0.4.3, 0.6.0-dev
> Kitty version: 0.15.0

The issue is gone when using `modesetting` driver instead of `xf86-video-intel`.

**Comment by awused** [comment]
I can sometimes reproduce this bug with picom and largely the same hardware and configuration as the other reporters. One setting that hasn't been mentioned is `use-damage` which I have set to `false`.

If I switch my picom config to `use-damage  = true` I don't reproduce these exact symptoms but I get a different bug instead. Instead of being stuck on the previous frame it rapidly flickers between the current and previous frame, swapping every time the screen refreshes. I've never reproduced either bug the with the other `use-damage` setting so I believe these are two symptoms of the same root cause.

**Comment by awused** [comment]
I got fed up  enough with this and did some digging. There's a setting for picom `xrender-sync-fence` that seems to fix the issue. I used to use this setting in the past but it was removed from picom for a brief period, so I removed it from my config. This was before I started using Alacritty, and none of my other applications trigger this bug, so I never made the connection.

**Comment by kchibisov** [comment]
I don't think this issue is relevant anymore given that we don't use any sort of vsync on X11 anymore. Troubleshooting drivers is not alacritty's priority.
