### ISSUE TITLE
Show title of current directory, and key binding to command

### ISSUE THREAD

**Issue by rod-stuchi** [alacritty/alacritty#3780]
Would be a nice feature to change the title according to the name of the directory you are in.

![image](https://user-images.githubusercontent.com/19471811/83098568-6f7e6080-a081-11ea-9380-4be79bbc0df2.png)

Configurable:
- full path
- only directory name

About key binding to command, in `konsole` there is an option to *Clean Scrollback and Reset* something like `/usr/bin/clear` would be useful binding a key to this.

**Comment by kchibisov** [comment]
>Would be a nice feature to change the title according to the name of the directory you are in.

It's a shell job.

>About key binding to command, in konsole there is an option to Clean Scrollback and Reset something like /usr/bin/clear would be useful binding a key to this

https://github.com/alacritty/alacritty/blob/2b2b2bfd2a525001f2ce15d64392c930b6321ab2/alacritty.yml#L460

**Comment by rod-stuchi** [comment]
Hi @kchibisov , thanks

I'm using alacritty 0.4.2

`clearHistory` is working, but I need to do **CTRL+l** before, and **CTRL+Shift+k** after.
There is a away to execute both with one key-binding?

**Comment by kchibisov** [comment]
>clearHistory is working, but I need to do CTRL+l before, and CTRL+Shift+k after.
There is a away to execute both with one key-binding?

You can do something like that, but the problem is timing related, I'd say, so you'll still have some history even after that(the current visible screen).

```yaml
-  { key: K,        mods: Control|Shift, chars: "\x0c"                        }
-  { key: K,        mods: Control|Shift, action: ClearHistory                 }
```

@chrisduerr  , do you have an idea how to achieve pure `clear` behavior without some hacks?

**Comment by chrisduerr** [comment]
> @chrisduerr , do you have an idea how to achieve pure clear behavior without some hacks?

You can't, you'd have to write to the PTY not the input side. I'm also not sure if I'd recommend force-clearing the terminal, since running applications might end up in a strange state. Even worse if it does what `clear` does and it moves the cursor position.

**Comment by rod-stuchi** [comment]
@kchibisov worked, but I had to execute the key-binding twice.

**Comment by rod-stuchi** [comment]
And this (on zsh) works for me, changing the window title.
Thanks for point the path.

```
precmd() {
    [[ $TERM == "alacritty" ]] && print "\033]0;:> $(pwd)"
}
```
