### ISSUE TITLE
Emojis are supersized

### ISSUE THREAD

**Issue by itshaydendev** [alacritty/alacritty#3791]
![Screenshot](https://i.imgur.com/s8Gmrnc.png)

### System

**OS:** Arch Linux
**Version:** `alacritty 0.4.2`
**Linux/BSD:** X11, bspwm, picom

#### Font/terminal size
```
[2020-05-29 22:40:39.212303764] [INFO] Welcome to Alacritty
[2020-05-29 22:40:39.212418296] [INFO] Configuration loaded from "/home/hayden/.config/alacritty/alacritty.yml"
[2020-05-29 22:40:39.218661505] [DEBUG] Estimated DPR: 1.25
[2020-05-29 22:40:39.218706537] [DEBUG] Estimated Cell Size: 9 x 18
[2020-05-29 22:40:39.218726145] [DEBUG] Estimated Dimensions: None
[2020-05-29 22:40:39.246376405] [INFO] Device pixel ratio: 1.25
[2020-05-29 22:40:39.251964445] [INFO] Initializing glyph cache...
[2020-05-29 22:40:39.261390156] [INFO] ... finished initializing glyph cache in 0.009395137s
[2020-05-29 22:40:39.261434261] [INFO] Cell Size: 9 x 18
[2020-05-29 22:40:39.261444654] [INFO] Padding: 17 x 21
[2020-05-29 22:40:39.261460569] [INFO] Width: 800, Height: 600
[2020-05-29 22:40:39.262769134] [INFO] PTY Dimensions: Line(31) x Column(85)
[2020-05-29 22:40:39.271050456] [INFO] Initialisation complete
[2020-05-29 22:40:39.271556959] [DEBUG] New num_cols is 54 and num_lines is 13
[2020-05-29 22:40:39.271680898] [INFO] Width: 524, Height: 272
```

**Comment by chrisduerr** [comment]
Which font is this? And do you have any fontconfig setup, it looks like fontconfig might report an incorrect scaling factor to Alacritty.

**Comment by kchibisov** [comment]
In particular, do you set yourself a `pixelsize` somewhere for `Noto Color Emoji` in /etc/fonts/conf.d or some local configuration?

**Comment by itshaydendev** [comment]
@kchibisov I don't think I have a pixelsize set.

@chrisduerr That's the Nerd Fonts patched JetBrains Mono.

**Comment by kchibisov** [comment]
>I don't think I have a pixelsize set.

You don't think or you've grepped `pixelsize` for in your font files in `/etc/fonts/conf.d` and `$HOME/fontconfig/`

>That's the Nerd Fonts patched JetBrains Mono.

This is not jetbrains mono tbw.

**Comment by itshaydendev** [comment]
No, you're right, that was SF Mono. Though I've just set it to JBM and it's still an issue

Also, again you're right, because I have a pixelsize of 18

**Comment by kchibisov** [comment]
>Also, again you're right, because I have a pixelsize of 18

Well, you've asked for it, so depending on where it is you can likely remove or disable this font file.

**Comment by itshaydendev** [comment]
Do you want to see my FC file? I've commented out the pixelsize thing and it's still an issue

**Comment by kchibisov** [comment]
Try `fc-cache -f` and then try `fc-match -v "Noto Color Emoji:pixelsizefixupfactor"` and post the output of this command.

**Comment by itshaydendev** [comment]
```
Pattern has 41 elts (size 48)
	family: "Noto Color Emoji"(s)
	familylang: "en"(s)
	style: "Regular"(s)
	stylelang: "en"(s)
	fullname: "Noto Color Emoji"(s)
	fullnamelang: "en"(s)
	slant: 0(i)(s)
	weight: 80(f)(s)
	width: 100(f)(s)
	size: 17.28(f)(w)
	pixelsize: 18(f)(s)
	spacing: 100(i)(w)
	foundry: "GOOG"(w)
	antialias: False(w)
	hintstyle: 1(i)(w)
	hinting: True(s)
	verticallayout: False(s)
	autohint: False(s)
	globaladvance: True(s)
	file: "/usr/share/fonts/noto/NotoColorEmoji.ttf"(w)
	index: 0(i)(w)
	outline: False(w)
	scalable: True(w)
	dpi: 75(f)(s)
	scale: 1(f)(s)
	matrix: [0.694444 0; 0 0.694444](w)
	charset: 
	0000: 00000000 03ff0409 00000000 00000000 00000000 00004200 00000000 00000000
	0020: 00002000 10000000 00000200 00000000 00000000 00000000 00000000 00000008
	0021: 00000000 02000004 00000000 00000000 03f00000 00000600 00000000 00000000
	0023: 0c000000 00000100 00000000 00000000 00000000 00000000 00008000 070ffe00
	0024: 00000000 00000000 00000000 00000000 00000000 00000000 00000004 00000000
	0025: 00000000 00000000 00000000 00000000 00000000 00400c00 00000001 78000000
	0026: 2132401f 0700c44d 800fff05 c8000169 1afc0000 60030c03 001ac130 27bf0600
	0027: 2054bf24 00180102 00b85090 00000018 00e00000 80010002 00000000 00000000
	0029: 00000000 00300000 00000000 00000000 00000000 00000000 00000000 00000000
	002b: 180000e0 00000000 00210000 00000000 00000000 00000000 00000000 00000000
	0030: 00000000 20010000 00000000 00000000 00000000 00000000 00000000 00000000
	0032: 00000000 00000000 00000000 00000000 02800000 00000000 00000000 00000000
	01f0: 00000010 00000000 00000000 00000000 00000000 00000000 00008000 00000000
	01f1: 00000000 00000000 00000000 c0030000 07fe4000 00000000 00000000 ffffffc0
	01f2: 04000006 07fc8000 00030000 00000000 00000000 00000000 00000000 00000000
	01f3: ffffffff fffffff3 ffffffff ffffffff cecfffff ffffffff ffffffff ffb9ffff
	01f4: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff bfffffff
	01f5: ffffffff 3fffffff ffff7e00 07f980ff 00613c80 10060130 700e001c fc08810a
	01f6: ffffffff ffffffff 0000ffff 00000000 ffffffff ffffffff 0027f83f 07f91a3f
	01f7: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000fff
	01f9: ffffe000 f7ffffff ffffffbf fc7bffff ffffffff ffffc7e7 ffffe7ff ffffffff
	01fa: 00000000 00000000 00000000 070f0000 003f0007 00000000 00000000 00000000
	0e00: 00000000 03ff0000 00000000 87fffffe 00000000 00000000 00000000 00000000
	0fe4: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00007fe0
	0fe8: 00000000 00ffd000 00000000 00000000 00000000 00000000 00000000 00000000
(w)
	lang: und-zsye(s)
	fontversion: 132252(i)(s)
	capability: "otlayout:DFLT"(w)
	fontformat: "TrueType"(w)
	embeddedbitmap: True(s)
	decorative: False(s)
	namelang: "en"(s)
	prgname: "fc-match"(s)
	postscriptname: "NotoColorEmoji"(w)
	color: DontCare(s)
	symbol: False(s)
	variable: False(s)
	fonthashint: False(w)
	pixelsizefixupfactor: 0.694444(f)(w)
```

**Comment by kchibisov** [comment]
Yeah, `pixelsize 18` is still applied as you can see. Read the `pixelsize` string in this output. So the actual pixelsize of your font is `108` IIRC(on my system it like that), and you ask to fixup this value by `pixelsizefixupfactor: 0.694444(f)(w)`, which we're doing ofc, but it'll be a bit big font.

**Comment by itshaydendev** [comment]
What do I need to do? I specifically have that part of my fontconfig commented out

**Comment by itshaydendev** [comment]
```xml
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
  <match target="scan">
    <test name="family">
      <string>Noto Color Emoji</string>
    </test>
    <edit name="scalable" mode="assign">
      <bool>true</bool>
    </edit>
    <!-- <edit name="pixelsize" mode="assign">
      <double>18</double>
    </edit> -->
  </match>
  <match>
    <test name="family"><string>sans-serif</string></test>
    <edit name="family" mode="prepend" binding="weak">
      <string>Noto Color Emoji</string>
    </edit>
  </match>
  <alias binding="weak">
    <family>sans-serif</family>
    <prefer>
      <family>emoji</family>
    </prefer>
  </alias>

  <alias binding="weak">
    <family>serif</family>
    <prefer>
      <family>emoji</family>
    </prefer>
  </alias>

  <match>
    <test name="family"><string>serif</string></test>
    <edit name="family" mode="prepend" binding="weak">
      <string>Noto Color Emoji</string>
    </edit>
  </match>

  <match>
    <test name="family"><string>Apple Color Emoji</string></test>
    <edit name="family" mode="prepend" binding="strong">
      <string>Noto Color Emoji</string>
    </edit>
  </match>

  <alias>
    <family>sans-serif</family>
    <prefer><family>Inter</family></prefer>
  </alias>

  <alias>
    <family>serif</family>
    <prefer><family></family></prefer>
  </alias>

  <alias>
    <family>monospace</family>
    <prefer><family>JetBrains Mono</family></prefer>
  </alias>

</fontconfig>
```

**Comment by kchibisov** [comment]
I'm not sure maybe it's still cached somewhere, maybe removing `.cache/fontcofig` will solve this.

**Comment by itshaydendev** [comment]
Just tried that, no dice. Emojis are still huge

**Comment by kchibisov** [comment]
Well, you see the issue and you see the broken output from fontconfig tools. So  I guess you can just try different way to fix it via `fc-match -v "Noto Color Emoji:pixelsizefixupfactor"` and checking that `pixelsize` isn't `18`, while you're hard codding it to `18`, which is wrong, you'll see what you've asked for.

try temporary removing the font file entirely, I guess. and run `fc-cache -svf` after such things.

**Comment by itshaydendev** [comment]
`pixelsize` is still `18` after completely moving the file.

**Comment by itshaydendev** [comment]
`pixelsize` is still `18` after completely moving the file.

**Comment by kchibisov** [comment]
>pixelsize is still 18 after completely moving the file.

This has nothing to do with alacritty at this point. I'd recommend to check things in `/etc/fonts`.

**Comment by itshaydendev** [comment]
It does have to do with Alacritty, as I've not had this issue in any other terminals

**Comment by kchibisov** [comment]
>It does have to do with Alacritty, as I've not had this issue in any other terminals

Why, you see pixelsize 18, and fixup factor 0.69. 108 * 0.69 = 74, so you're asking for emoji of size 74. You're getting emoji of size 74. We just trust what the user specified and use scaling you've asked for such fonts. If you want for us to guess how to scale fonts, remove `/etc/fonts/conf.d/10-scale-bitmap-fonts.conf`

**Comment by itshaydendev** [comment]
I've removed it, and the emojis are sized correctly.

However, I maintain a dotfiles repo, I'd like this to be easy to replicate without needing sudo perms, so is there a way I can do that with my local fontconfig?

**Comment by kchibisov** [comment]
Fix pixelsize 18 issue. The file you're removed made us guess sizes and scale things correctly, which is not our problem, once you've fixed `pixelsize 18` report bringing back this file from `/etc/fonts/conf.avail` should fix it and everything will work as it was desired.

**Comment by chrisduerr** [comment]
You can also try running `fc-cache --really-force` to make sure all caches are cleared and rescanned. Once this setting is removed and all settings are properly reloaded, you should not run into this problem anymore.
