### ISSUE TITLE
Some emojis are black and white, but only on alacritty

### ISSUE THREAD

**Issue by WhyNotHugo** [alacritty/alacritty#3795]
### System

OS: ArchLinux
Version: `alacritty 0.4.2` 
Linux/BSD: Wayland, [swaywm](https://github.com/swaywm/sway/)

### Logs

```
➜ alacritty -vv
Created log file at "/tmp/Alacritty-582003.log"
[2020-05-30 13:37:41.800192190] [INFO] Welcome to Alacritty
[2020-05-30 13:37:41.801028167] [INFO] Configuration loaded from "/home/hugo/.config/alacritty/alacritty.yml"
[2020-05-30 13:37:41.838186369] [DEBUG] Estimated DPR: 2
[2020-05-30 13:37:41.838211099] [DEBUG] Estimated Cell Size: 21 x 45
[2020-05-30 13:37:41.838218614] [DEBUG] Estimated Dimensions: None
[2020-05-30 13:37:42.037117728] [INFO] Device pixel ratio: 1
[2020-05-30 13:37:42.054368906] [INFO] Initializing glyph cache...
[2020-05-30 13:37:42.095334623] [INFO] ... finished initializing glyph cache in 0.040938558s
[2020-05-30 13:37:42.095365785] [INFO] Cell Size: 10 x 22
[2020-05-30 13:37:42.095377498] [INFO] Padding: 0 x 0
[2020-05-30 13:37:42.095386531] [INFO] Width: 800, Height: 600
[2020-05-30 13:37:42.096457399] [INFO] PTY Dimensions: Line(27) x Column(80)
[2020-05-30 13:37:42.099181785] [INFO] Initialisation complete
[2020-05-30 13:37:42.110100902] [DEBUG] New num_cols is 114 and num_lines is 10
[2020-05-30 13:37:42.110302734] [INFO] Width: 1145, Height: 226
[2020-05-30 13:37:42.272553200] [INFO] Font size changed to Size(28) with DPR of 2
[2020-05-30 13:37:42.287492892] [DEBUG] New num_cols is 109 and num_lines is 10
[2020-05-30 13:37:42.287531702] [INFO] Width: 2290, Height: 452
[2020-05-30 13:37:53.682984147] [INFO] Goodbye
```

Font-related settings:
```ini
# Font configuration
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas
    family: "OperatorMono Nerd Font"
    # The `style` can be specified to pick a specific face.
    style: "Medium"

  # Bold font face
  bold:
    # Font family
    #
    # If the bold family is not specified, it will fall back to the
    # value specified for the normal font.
    family: "OperatorMono Nerd Font" # should be "Menlo" or something on macOS.

    # The `style` can be specified to pick a specific face.
    style: "Bold"

  # Italic font face
  italic:
    # Font family
    #
    # If the italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: "OperatorMono Nerd Font" # should be "Menlo" or something on macOS.
    # The `style` can be specified to pick a specific face.
    style: "Medium Italic"

  # Point size
  size: 14.0

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the right,
  # increasing `y` moves the glyph upwards.
  glyph_offset:
    x: 0
    y: 0
```

Some emojis are rendered as black and white outlines, but other (most of them) are rendered fine in full colour:

![emoji](https://user-images.githubusercontent.com/730811/83327329-36edab00-a26a-11ea-9cc6-771c0865ee36.png)

I'm relucatant to think it's a fontconfig issue, since other applications (firefox, l3afpad) render all emojis in full colour.

I'm using twemoji, with this [config file](https://aur.archlinux.org/cgit/aur.git/tree/75-twemoji.conf?h=ttf-twemoji).

I've gone through similar issues, but none seem to be the same problem, either slightly different symptoms, macOS-specific, or missing fallbacks.

Oh, fallbacks:
```
➜ fc-match -s "OperatorMono Nerd Font"
Operator Mono Bold Nerd Font Complete.otf: "OperatorMono Nerd Font" "Bold"
DejaVuSans.ttf: "DejaVu Sans" "Book"
DejaVuSans-Bold.ttf: "DejaVu Sans" "Bold"
DejaVuSans-Oblique.ttf: "DejaVu Sans" "Oblique"
DejaVuSans-BoldOblique.ttf: "DejaVu Sans" "Bold Oblique"
Arial.TTF: "Arial" "Regular"
NotoSans-Regular.ttf: "Noto Sans" "Regular"
twemoji.ttf: "Twemoji" "Regular"
<all other fonts are listed below this>
```

**Comment by kchibisov** [comment]
Fix your fallback, we don't prefer emoji fonts over other fonts in your fallback. Those glyphs are from DejaVu font, so just make your `Twemoji` font before it and it should work. Consult default guides for font config setups.

**Comment by WhyNotHugo** [comment]
I **do** have rules to prefer this font above others (including DejaVu).
This rule seems to be respected on all other applications.

```
    <match target="scan">
        <test name="family" compare="contains">
            <string>DejaVu</string>
        </test>
        <edit name="charset" mode="assign" binding="same">
            <minus>
                <name>charset</name>
                <charset>
                    <range>
                        <int>0x1f600</int>
                        <int>0x1f640</int>
                    </range>
                </charset>
            </minus>
        </edit>
    </match>
    <match target="scan">
        <test name="family" compare="contains">
            <string>Arial</string>
        </test>
        <edit name="charset" mode="assign" binding="same">
            <minus>
                <name>charset</name>
                <charset>
                    <range>
                        <int>0x1f600</int>
                        <int>0x1f640</int>
                    </range>
                </charset>
            </minus>
        </edit>
    </match>
    <match target="scan">
        <test name="family" compare="contains">
            <string>Noto</string>
        </test>
        <edit name="charset" mode="assign" binding="same">
            <minus>
                <name>charset</name>
                <charset>
                    <range>
                        <int>0x1f600</int>
                        <int>0x1f640</int>
                    </range>
                </charset>
            </minus>
        </edit>
    </match>
    <match target="scan">
        <test name="family" compare="contains">
            <string>Operator</string>
        </test>
        <edit name="charset" mode="assign" binding="same">
            <minus>
                <name>charset</name>
                <charset>
                    <range>
                        <int>0x1f600</int>
                        <int>0x1f640</int>
                    </range>
                </charset>
            </minus>
        </edit>
    </match>
```

> Consult default guides for font config setups.

Do you have a good reference on this topic? So far, all that I've learnt has been through other issues reported here.

**Comment by WhyNotHugo** [comment]
Assuming it's a configuration issue, there's a lack of documentation of how such configuration works for alacritty.. Still seems like this would be the right place to ask... right?

**Comment by kchibisov** [comment]
You've literally ran `fc-match -s` and showed me that they are not respected.

>there's a lack of documentation of how such configuration works for alacritty

It's in general, not for alacritty. Some apps just hardcode emojis.

>Still seems like this would be the right place to ask... right?

You can always search the web for how to setup fallbacks with fontconfig. There're plenty of guides. Also some wiki's about fontconfig telling how to do so.

Try something from https://github.com/alacritty/alacritty/issues/153#issuecomment-630636358

**Comment by WhyNotHugo** [comment]
> You've literally ran fc-match -s and showed me that they are not respected.

`fc-match -s` shows the precedence of fonts, but my config is just overriding at a per-glyph level.

I managed to fix it though!

This snippet is probably as versatile as it gets: `twemoji` will always be used for emoji, regardless of anything else (this also works if `DejaVu` **is** your default font).

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">

<fontconfig>
    <match target="scan">
        <test name="family"><string>Noto Color Emoji</string></test>
        <edit name="charset" mode="assign">
            <minus>
            <name>charset</name>
                <charset><range>
                    <int>0x0000</int>
                    <int>0x00FF</int>
                </range></charset>
            </minus>
        </edit>
    </match>
    <match>
        <edit name="family" mode="append" binding="weak">
            <string>Twemoji</string>
        </edit>
    </match>
</fontconfig>
```

For the record `fc-match` won't list it first (Font fallback order != per-glyph preference). Changing the order would be impossible if your **primary** font had undesired emojis (as `DejaVu` does).

```console
$ fc-match -s "OperatorMono Nerd Font" | head -n 8
Operator Mono Bold Nerd Font Complete.otf: "OperatorMono Nerd Font" "Bold"
DejaVuSans.ttf: "DejaVu Sans" "Book"
DejaVuSans-Bold.ttf: "DejaVu Sans" "Bold"
DejaVuSans-Oblique.ttf: "DejaVu Sans" "Oblique"
DejaVuSans-BoldOblique.ttf: "DejaVu Sans" "Bold Oblique"
Arial.TTF: "Arial" "Regular"
NotoSans-Regular.ttf: "Noto Sans" "Regular"
twemoji.ttf: "Twemoji" "Regular"
```

I hope this helps others seeking help in future! :slightly_smiling_face:

**Comment by WhyNotHugo** [comment]
Looks like some two-character emoji as not rendered, right, e.g.: 🇳🇱 is Rendered as:

![2020-05-30T14:13:16,817670149+02:00](https://user-images.githubusercontent.com/730811/83327899-f5133380-a26e-11ea-85d5-4d3e20ebcb4c.png)

Is this an alacritty issue, or also fontconfig?

**Comment by kchibisov** [comment]
>Looks like some two-character emoji as not rendered

We don't combine them yet.

>For the record fc-match won't list it first

If you remove chars from font charset it'll also work since those fonts won't have those chars during fallback and those will be ignored.

**Comment by WhyNotHugo** [comment]
> If you remove chars from font charset it'll also work since those fonts won't have those chars during fallback and those will be ignored.

That's right. I'm not sure if there's anything "dirty" about this approach, but it should work for pretty much all the usual (and many unusual) scenarios.

> We don't combine them yet.

These are technically ligatures, right? I guess then that #50 tracks this, so I've nothing further to add.

Thanks!

**Comment by kchibisov** [comment]
>These are technically ligatures, right? 

They are combined via ZWJ and ligatures won't solve it IIRC, but I guess maybe it'll be solved somehow, in anyway : - ). Let's just track it in #50 for now.

>That's right. I'm not sure if there's anything "dirty" about this approach, but it should work for pretty much all the usual (and many unusual) scenarios.

Yeah, it's fine to do so.

**Comment by chrisduerr** [comment]
>  These are technically ligatures, right?

These are not the same and solving one will not solve the other. There is currently no plan to combine characters, since it is not supported by any terminal specification.
