### ISSUE TITLE
Macos: urls are not clickable in a tmux session

### ISSUE THREAD

**Issue by DrGo** [alacritty/alacritty#3798]
not sure if this is alacrity or tumx issue; cannot test in iterm2 or terminal as both do not seem to support clickable urls. urls are clickable when tmux is not running.

### System
OS: Macos Catalina 10.15.5
Version: alacritty 0.4.3-rc1 (04114e7)

**Comment by chrisduerr** [comment]
Try holding shift.

**Comment by DrGo** [comment]
works. thanks!
but that does not work outside tmux session. right?

**Comment by chrisduerr** [comment]
Not unless you configure it to work.
