### ISSUE TITLE
Less pager scrolling with Windows

### ISSUE THREAD

**Issue by nu8** [alacritty/alacritty#3800]
I downloaded this:

<https://github.com/alacritty/alacritty/releases/download/v0.4.3-rc1/Alacritty-v0.4.3-rc1-windows-portable.zip>

Then set config like this:

~~~
shell:
   program: C:\msys64\usr\bin\sh.exe
~~~

but if I do something like `git diff`, once the `less` pager starts, I am just
stuck with the first window of text. If I press Down Arrow, nothing happens.

**Comment by chrisduerr** [comment]
Does `j` work? What `TERM` do you have set and are you using ConPTY or WinPTY (should be printed to stdout when running `alacritty -v`).

**Comment by nu8** [comment]
> Does `j` work?

Yes

> What `TERM` do you have set

~~~
xterm-256color
~~~

> and are you using ConPTY or WinPTY (should be printed to stdout when running
> `alacritty -v`).

~~~
[2020-05-31 22:08:55.076452200] [INFO] Using WinPTY backend
~~~

**Comment by chrisduerr** [comment]
Which Windows version are you running?

**Comment by nu8** [comment]
Windows 7

**Comment by chrisduerr** [comment]
Windows 7 is EOL. If you update to Windows 10, you'll have ConPTY available and that will likely fix this problem.
