### ISSUE TITLE
[macOS] subpixel/thinstroke make texts look weird

### ISSUE THREAD

**Issue by danglduy** [alacritty/alacritty#3804]
On macOS texts look weird with thin stroke on non-retina screen with system sub pixel. 
I compared the same texts/same font on iterm2.
### System

OS: macOS 10.15.5
Version: v0.4.2
Font: Iosevka 3.1.1 - A condensed font - but look not condensed on Alacritty.

### Settings
- Thin stroke
- `defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO`

### Screenshot
Above is Alacritty, below is iterm2
![Screen Shot 2020-06-01 at 23 00 23](https://user-images.githubusercontent.com/38782010/83428186-23099b00-a45c-11ea-9b09-82e50bfc4343.png)

**Comment by kchibisov** [comment]
You should reboot after `write -g` thing. However you can try `v0.4.3` version.

**Comment by danglduy** [comment]
Hi. Thank you for your reply. I checked again with v0.4.3. The version above is 0.4.2.

However texts look so different now.
![Screen Shot 2020-06-01 at 23 14 53](https://user-images.githubusercontent.com/38782010/83429120-c4452100-a45d-11ea-82f8-9b00f88e13b9.png)

**Comment by kchibisov** [comment]
Yeah, now thin_stroke works, afaics. before it was disabled.

**Comment by danglduy** [comment]
Ok then I disabled thin_stroke and the texts look not very good now... 
![Screen Shot 2020-06-01 at 23 35 08](https://user-images.githubusercontent.com/38782010/83430836-8e556c00-a460-11ea-8298-07fb7bc27c54.png)

In v0.4.2 if I disable thin_stroke the texts does look very fuzzy, so I guess thin_stroke in 0.4.2 does take effect?

**Comment by chrisduerr** [comment]
> In v0.4.2 if I disable thin_stroke the texts does look very fuzzy, so I guess thin_stroke in 0.4.2 does take effect?

Yes, but please make sure you always restart between testing.

Sounds like everything's working now though?

**Comment by danglduy** [comment]
> Sounds like everything's working now though?
As you can see on 0.4.3 with whatever the `thin_stroke` option value is, the texts do not look as good as iterm2.

**Comment by luisdavim** [comment]
same thing here, I've just updated to the latest version available on homebrew and font rendering looks awful...

**Comment by kchibisov** [comment]
>same thing here, I've just updated to the latest version available on homebrew and font rendering looks awful...

Disable thin stroke in a config. We just make it work, nothing else was changed.

**Comment by luisdavim** [comment]
I did disable thin stroke, it was unusable with it on. But still font rendering looks worst than it did before the update.

**Comment by kchibisov** [comment]
But the last release was fixing things on other platforms, it didn't even touched macOS in any major way? Could you give a screenshot something the difference between v0.4.2 and v0.4.3 with disabled thin stroke?

**Comment by luisdavim** [comment]
![image](https://user-images.githubusercontent.com/173006/83509137-e2913800-a4c2-11ea-9e37-5309e4b9508a.png)
and with thin strokes:
![image](https://user-images.githubusercontent.com/173006/83509414-4e73a080-a4c3-11ea-88a3-307f80085c1f.png)
and the latest version:
![image](https://user-images.githubusercontent.com/173006/83509269-11a7a980-a4c3-11ea-8154-1d1af81909ed.png)

**Comment by chrisduerr** [comment]
These look all identical to me?

**Comment by arooni** [comment]
commenting to follow the issue.  on 0.4.3 fonts look scratchy and weird to me as compared to iterm and i've tried messing with use_thin_strokes and different font weights and it still doesn't look that good :(.

**Comment by chrisduerr** [comment]
Please make sure you restart Alacritty after changing any of these settings. There is **nothing** Alacritty has changed since the last release compared to `use_thin_strokes: false`. The only difference is that the default has been changed.

Just to get on topic of the original bug again, @danglduy this is not a regression, correct? This problem occurs with any Alacritty version?

If someone is experiencing a *regression*, it has nothing to do with this issue. So please adjust your configuration file appropriately and open a separate issue if you are not able to figure it out.

**Comment by danglduy** [comment]
There are two issues of the two versions of Alacritty I tested:
- With version 0.4.2 (the original post screenshot):
  - `thin_stroke` on: font looks weird because as I can see that `iosevka` - a condensed font - look not condensed. I compared with iTerm2. However the texts look **acceptable**.
  - `thin_stroke` off: texts look worse, fuzzy text. So the `thin_stroke` setting worked when I tested.

- Then I updated the program to version 0.4.3 and the issue is worse. 

  - With `thin_stroke` on, the text looks **very thin**. I ***guess*** the program ignores `CGFontRenderingFontSmoothingDisabled` and disables sub-pixel antialias.
  - With `thin_stroke` off, the texts look very bad, fuzzy.

I turned on sub-pixel antialias by using `defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO`.

I always restart the program after changing settings.

I will make more screenshots if you guys need.

**Comment by danglduy** [comment]
> So it sounds like your only problem with 0.4.2 is that the glyph spacing isn't to your liking, is that correct?

That’s basically what I meant. Bold texts look smaller than regular texts as you can see.

> The whole point of `thin_strokes` is that it should set `CGFontRenderingFontSmoothingDisabled ` otherwise it does nothing.

I think `CGFontRenderingFontSmoothingDisabled` should be respect. Disable font smoothing make texts very bad on non-retina screen. Even in the default config said enable font smoothing and set thin stroke.

**Comment by kchibisov** [comment]
This commit made it work, it was never working before. Right now this setting sets `CGFontRenderingFontSmoothingDisabled` by itself, previously thin stroke was a no-op without  `CGFontRenderingFontSmoothingDisabled`. So it's respect just the way of setting it is different now and follows iterm (that's how subpixel/smoothing) setting works in it.

>Even in the default config said enable font smoothing and set thin stroke.

I don't see anything like that in it. Font smooting is being disabled only for thin stroke, otherwise it's used by default. 
https://github.com/alacritty/alacritty/blob/e6475c6753503da42446ec50fd2b797d5b89fe79/alacritty.yml#L157

**Comment by chrisduerr** [comment]
> > So it sounds like your only problem with 0.4.2 is that the glyph spacing isn't to your liking, is that correct?

> That’s basically what I meant.

Sounds like #3809 and the associated PR should fix this then. You can adjust the glyph spacing in the configuration file.
