### ISSUE TITLE
Package broken

### ISSUE THREAD

**Issue by Awerito** [alacritty/alacritty#3807]
# System

OS: Pop_OS!
Version: 0.4.3
Linux/BSD: Gnome

### Logs

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  alacritty
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 0 B/1,738 kB of archives.
After this operation, 6,253 kB of additional disk space will be used.
(Reading database ... 495409 files and directories currently installed.)
Preparing to unpack .../alacritty_0.4.3~1591030599~20.04~a0f0835_amd64.deb ...
Unpacking alacritty (0.4.3~1591030599~20.04~a0f0835) ...
dpkg: error processing archive /var/cache/apt/archives/alacritty_0.4.3~1591030599~20.04~a0f0835_amd64.deb (--unpack):
 trying to overwrite '/usr/share/terminfo/a/alacritty', which is also in package ncurses-term 6.2-0ubuntu2
Errors were encountered while processing:
 /var/cache/apt/archives/alacritty_0.4.3~1591030599~20.04~a0f0835_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by kchibisov** [comment]
it's not broken, it's just not compatible with your system. But Pop os should have alacritty in official repo, so that's not a big deal.

The packaging was entirely removed from alacritty so it won't be a problem for future releases.

**Comment by Kenryoj** [comment]
Also on Pop using two systems configured with the same install script(mostly flatpaks and some installed with apt like steam). On my laptop alacritty installed fine, desktop failed. removing and installing again on laptop gave same result as desktop? This is using alacritty in the repo.

**Comment by kchibisov** [comment]
I mean you can use pop repo directly, no need for package from us. If the package from pop repo fails, it's not our problem.

**Comment by runiq** [comment]
> The packaging was entirely removed from alacritty so it won't be a problem for future releases, because there won't be any package.

Is there a PR/issue for that I can read up on? Feels weird that I can download binaries for all platforms except Linux :)

**Comment by kchibisov** [comment]
>Is there a PR/issue for that I can read up on? Feels weird that I can download binaries for all platforms except Linux :)

Linux != Ubuntu/Debian. There are countless number of distributions, and you know BSD. We don't have a static binary, so that's why there's no point in providing binary for just one specific distro.

The other platforms are just limited in way they work, they don't have package managers, and except developers to ship their software.

**Comment by runiq** [comment]
True, I hadn't even noticed they were built for Ubuntu only. Sorry for prying, and thanks for working on Alacritty!
