### ISSUE TITLE
Regression in font rendering in 0.4.3 vs 0.4.2

### ISSUE THREAD

**Issue by harryjsmith** [alacritty/alacritty#3809]
### System:

OS: macOS 10.14.6

### Settings:

- `use_thin_strokes: false`
- `defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO`

There is already some discussion of this in the comments of #3804, but I'm opening a separate issue specifically for this issue.

With `use_thin_strokes: false` set, font rendering appears to be worse in 0.4.3 than it was in 0.4.2:

0.4.2:
<img width="627" alt="image" src="https://user-images.githubusercontent.com/33180538/83656290-4137de00-a5b7-11ea-92ee-6015f5d0df41.png">

0.4.3:
<img width="632" alt="image" src="https://user-images.githubusercontent.com/33180538/83656339-501e9080-a5b7-11ea-83d1-f3f742b1e667.png">

The change is quite subtle, but it definitely looks less smooth in 0.4.3. For what it's worth, this (0.4.3) looks similar to other font rendering on my system when `defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO` is not set (i.e. without subpixel anti-aliasing).

**Comment by chrisduerr** [comment]
Could you bisect the issue? And please make sure Alacritty is restarted after disabling font smoothing in the config.

An educated guess would tell me that https://github.com/alacritty/alacritty/commit/77f2d6e853f1ad54e6dc844a811b78daeb463e76 is the only thing that could have possibly changed this. So that's probably a good place to check.

**Comment by thornjad** [comment]
Using the font Victor Mono Light on my machine (macOS 10.15.3) makes for a more dramatic difference:

0.4.2: 
![Screen Shot 2020-06-03 at 13 10 19](https://user-images.githubusercontent.com/17414927/83672271-98c85080-a59b-11ea-8964-003569a5d65d.png)


0.4.3: 
![Screen Shot 2020-06-03 at 13 05 04](https://user-images.githubusercontent.com/17414927/83672194-8221f980-a59b-11ea-9a93-a6e7f978ed15.png)

I can do some bisecting starting with 77f2d6e853f1ad54e6dc844a811b78daeb463e76 real quick

**Comment by thornjad** [comment]
Looks like a good guess, the regression first appears in 77f2d6e853f1ad54e6dc844a811b78daeb463e76. Font looks fine in its parent

**Comment by chrisduerr** [comment]
That would break emoji support on macOS unfortunately. We need to look for a different solution than just reverting it.

**Comment by thornjad** [comment]
Oh yes I see that was the point of the PR it was in. It does look _better_ than the screenshots in #1864, but not perfect: 
![image](https://user-images.githubusercontent.com/17414927/83676460-50f7f800-a5a0-11ea-9c67-8a0e1027e9ef.png)

**Comment by chrisduerr** [comment]
Yeah, the transparent parts of an emoji will just always be black without this change.

**Comment by chrisduerr** [comment]
Note that it might be easy to work around this by checking if the glyph is colored and setting the opacity of the fill color based on that.

The `self.is_colored()` function should be available and is used later in the method anyways, so extracting that into a variable and checking it might just work out.

Are you interested in trying to make this work @thornjad?

**Comment by thornjad** [comment]
I'm interested in trying it out! I'm pretty busy for a few hours but will take a stab at it tonight

**Comment by poupas** [comment]
FWIW, I think fonts look significantly better in 0.4.3 than they did in 0.4.2. If you revert to the old behaviour, it would be great to have a setting that kept the current rendering method :)

**Comment by chrisduerr** [comment]
> FWIW, with use_thin_strokes: true, I think fonts look significantly better in 0.4.3 than they did in 0.4.2. If you revert to the old behaviour, it would be great to have a setting that kept the current rendering method :)

The goal is to have both. Obviously `use_thin_strokes` should still be working, while the little bug that affects all rendering methods should be resolved.

So the rendering should be identical to setting `defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO` with `use_thin_strokes: true` on 0.4.2.

**Comment by thornjad** [comment]
So switching the background alpha based on `self.is_colored()` does appear to get everything we want for emoji transparency, plus text renders nicely!

**Comment by thornjad** [comment]
Do you know of anything else I should check/test (besides tests and rustfmt) around this fix before opening a PR?

**Comment by chrisduerr** [comment]
Nope, should be all good.
