### ISSUE TITLE
Default window background changed in master (Windows)

### ISSUE THREAD

**Issue by davidhewitt** [alacritty/alacritty#3814]
Windows OS. Not sure if this affects other systems.

Since 9a0eac0 the default window background on two different Windows systems I'm running has changed from black to a muted grey:

Before:

![image](https://user-images.githubusercontent.com/1939362/83728017-d67db580-a63d-11ea-9a90-958594c20a81.png)

After:

![image](https://user-images.githubusercontent.com/1939362/83728091-f2815700-a63d-11ea-9457-4320765b6ce1.png)

From the PR that introduced that commit, I can't see any suggestion that this change was intentional? 

cc @Aelnor

**Comment by kchibisov** [comment]
It was intentional. I hate it as well. whatever.

**Comment by davidhewitt** [comment]
Urgh, yes I should have read deeper - looked at the wrong screenshots in the PR and had incorrectly concluded the background colour had not changed. Reading the code it's clear this is intentional. Sorry for wasting your time!
