### ISSUE TITLE
Previous content doesn't properly resize

### ISSUE THREAD

**Issue by adamtabrams** [alacritty/alacritty#3815]
Resizing an alacritty window (particularly when shrinking it horizontally) makes many contents of the window unreadable. Here are some screenshots of this:

Before resize (alacritty is the top terminal, others are for comparison):
<img width="908" alt="Screen Shot 2020-06-04 at 10 56 38 AM" src="https://user-images.githubusercontent.com/39201397/83779923-26667780-a652-11ea-83f2-edce25747415.png">

After resize (alacritty is the top terminal, others are for comparison):
<img width="659" alt="Screen Shot 2020-06-04 at 10 57 04 AM" src="https://user-images.githubusercontent.com/39201397/83779942-2b2b2b80-a652-11ea-9eb4-1e11356041ee.png">

### System

OS: macOS
Version: 0.4.2
Shell: zsh 5.8
Prompt settings:
```
autoload -Uz promptinit
promptinit
PROMPT='%F{blue}>%f '
RPROMPT='%F{yellow}%3~%f'
```

**Comment by chrisduerr** [comment]
This is due to your shell redrawing itself and running a right prompt. It's how things are supposed to work, even though the result might not be the most desirable.

**Comment by adamtabrams** [comment]
@chrisduerr Then why is it handled differently in other terminals?

**Comment by adamtabrams** [comment]
@chrisduerr I just did the same test using a shell without a right prompt, and the problem didn't occur. But alacritty is still handling the right prompt very undesirably while other terminals aren't. It seems that a better name for this issue would be: "mishandling right prompt when resizing window"

**Comment by chrisduerr** [comment]
It's not. Every other terminal I've tested has this problem, it's just less obvious in some cases.

**Comment by adamtabrams** [comment]
@chrisduerr You can see in the screenshots that I included above than iTerm2 and terminal.app both seem to handle this better than alacritty. The problem is especially obvious when even more resizing is done. Here's a screenshot with a bit more resizing that the ones above:

![image](https://user-images.githubusercontent.com/39201397/83809367-eddb9380-a67b-11ea-8fa3-bf8fc7bfd440.png)

> Every other terminal I've tested has this problem, it's just less obvious in some cases.

The top one in this screenshot it alacritty, and all three terminals went through the exact same resizing. At the very least, is this something that can be made "less obvious"?

**Comment by novcn** [comment]
I'm also encountering the same issue and haven't experienced it using kitty or urxvt. 

Since I use a tiling window manager my terminal windows are resized frequently, if I am to switch to alacritty I'll have to get in the habit of `clear`ing every time I resize a window or no longer using a right-aligned prompt. 

If this really is not a bug, I think it should be clear that it's at least undesirable behavior and the issue should be re-opened.
