### ISSUE TITLE
Alacritty.yml not recognized

### ISSUE THREAD

**Issue by emma1710** [alacritty/alacritty#3816]
I tried all the possible directories but the config file is still not recognized:
~/alacritty.yml
~/.config/alacritty.yml
~/config/alacritty/alacritty.yml

Any idea how to fix this?

### System

OS: macOS Catalina
Version: `0.4.3 (c723247)

**Comment by chrisduerr** [comment]
Try running `alacritty -v`, that should tell you where the configuration file is loaded from.

Also make sure the file is actually correct. Especially since whitespace is relevant in yaml.

**Comment by emma1710** [comment]
Thank you @chrisduerr . The file in ~/config/alacritty/alacritty.yml was loaded but nothing changed  on Alacritty's look. Also I noticed that right after installed, alacritty also didn't display colors, maybe something is wrong with my env, but I can't pinpoint the issue.
Add the below to .bash_profile somehow works to make alacritty display color (without config file) on my work MB but doesn't work my personal one.
```
source "`brew --prefix`/etc/grc.bashrc"
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
alias ls='ls -GFh'
```

**Comment by chrisduerr** [comment]
Try using `echo -e "\e[31mRED"`, chances are that will work. Sounds like you're just having problems with your system setup unrelated to Alacritty.

**Comment by diploidal** [comment]
I'm currently having the same problem although I'm on Ubuntu 20.04 LTS.
`alacritty -v` outputs:
```
[2020-06-23 14:06] [INFO] Welcome to Alacritty
[2020-06-23 14:06] [INFO] Device pixel ratio: 1
[2020-06-23 14:06] [INFO] Initializing glyph cache...
[2020-06-23 14:06] [INFO] ... finished initializing glyph cache in 0.011502107s
[2020-06-23 14:06] [INFO] Cell Size: 9 x 17
[2020-06-23 14:06] [INFO] Padding: 0 x 0
[2020-06-23 14:06] [INFO] Width: 800, Height: 600
[2020-06-23 14:06] [INFO] PTY Dimensions: Line(35) x Column(88)
[2020-06-23 14:06] [INFO] Initialisation complete
[2020-06-23 14:06] [INFO] Width: 800, Height: 600
[2020-06-23 14:06] [INFO] Goodbye
```
I'm trying to locate the log file but it looks like it cannot be found anywhere. 
While trying to use any config in `./config/alacritty/alacritty.yml` - when `yml` file is there the whole thing doesn't want to start at all. 

Only changing LSColors within `.bashrc` file does something. :disappointed:

**Comment by chrisduerr** [comment]
> I'm trying to locate the log file but it looks like it cannot be found anywhere.

Because you have to create it yourself.

**Comment by kchibisov** [comment]
The default path is in `$HOME/.config/alacritty/alacritty.yml`, not in `$HOME/config/alacritty/alacritty.yml`. The file in mentioned locates doesn't get read, unless you run with `alacritty --config-file YOUR_CUSTOM_PATH`.

**Comment by diploidal** [comment]
Thanks for the instructions !

I've spent about an hour investigating it and `alacritty.yml` config file is not created by default. I took the default config file from here: 
[https://github.com/alacritty/alacritty/releases/download/v0.4.3/alacritty.yml](https://github.com/alacritty/alacritty/releases/download/v0.4.3/alacritty.yml) and copied it into `%HOME/.alacritty.yml` and everything woks perfectly ! :smiley: 

I'm at Ubuntu 20.04 (as well as older versions), same thing can apply to POP!_Os. 

Thanks for the help.

**Comment by kchibisov** [comment]
>I've spent about an hour investigating it and alacritty.yml config file is not created by default.

Ofc it's not. it's stated right here https://github.com/alacritty/alacritty/#configuration that it's not created by default and you should grab one from release page.

**Comment by nixpulvis** [comment]
@emma1710 can you confirm that `alacritty --config-file YOUR_CUSTOM_PATH` works at least? If so, I'm guessing you have misplaced the config file, please double check your paths.

**Comment by ReagentX** [comment]
I have my `.alacritty.yaml` in $HOME, but Alacritty does not detect it. Using `alacritty --config-file .alacritty.yaml` works, but it does not find the file on its own:

    ~                                                                                                                  took 0.14s ─╮
    ❯ echo $HOME                                                                                                                  ─╯
    /Users/chris
    ~                                                                                                                  took 0.14s ─╮
    ❯ pwd                                                                                                                         ─╯
    /Users/chris
    ~                                                                                                                  took 0.13s ─╮
    ❯ ls -al | grep alacritty                                                                                                     ─╯
    48 -rw-r--r--@    1 chris  staff    22K Aug  2 21:36 .alacritty.yaml
    ~                                                                                                                  took 0.14s ─╮
    ❯ alacritty -v                                                                                                                ─╯
    Created log file at "/var/folders/41/39__8bps2b7cncsp6kkp4x8c0000gn/T/Alacritty-6800.log"
    [2020-08-02 21:51:08.946665000] [INFO] Welcome to Alacritty
    [2020-08-02 21:51:08.946888000] [INFO] No configuration file found
    [2020-08-02 21:51:09.783101000] [INFO] Device pixel ratio: 2
    [2020-08-02 21:51:09.788721000] [INFO] Initializing glyph cache...
    [2020-08-02 21:51:09.894584000] [INFO] ... finished initializing glyph cache in 0.105678778s
    [2020-08-02 21:51:09.894681000] [INFO] Cell Size: 13 x 26
    [2020-08-02 21:51:09.894718000] [INFO] Padding: 0 x 0
    [2020-08-02 21:51:09.894754000] [INFO] Width: 1600, Height: 1200
    [2020-08-02 21:51:09.898486000] [INFO] PTY dimensions: Line(46) x Column(123)
    [2020-08-02 21:51:09.916750000] [INFO] Initialisation complete
    [2020-08-02 21:51:11.861317000] [INFO] Goodbye
    Deleted log file at "/var/folders/41/39__8bps2b7cncsp6kkp4x8c0000gn/T/Alacritty-6800.log"
    ~                                                                                                                  took 3.15s ─╮
    ❯                                                                                                                  ─╯

**Comment by chrisduerr** [comment]
@ReagentX Remove the `a` in `yaml`. See our documentation for which files are loaded.

**Comment by ReagentX** [comment]
Thanks, I could have stared at this for hours and not seen that.

**Comment by chrisduerr** [comment]
Closing this issue since the author seems MIA and it's very likely an issue on his end.

**Comment by tjatjagithub** [comment]
> > I've spent about an hour investigating it and alacritty.yml config file is not created by default.
> 
> Ofc it's not. it's stated right here https://github.com/alacritty/alacritty/#configuration that it's not created by default and you should grab one from release page.

Now, it better should, as most other Apps too!
Esp. as it does not even offer a Preferences tab, just creating a default config file would reduce many headaches ;-)
Don't you think?

**Comment by nixpulvis** [comment]
@tjatjagithub 

Why would you want a massive block of potentially changing defaults statically set by installation? I completely agree about making finding information about the configuration as easy as possible. I recommend simply cloning/forking alacritty and maintaining the source on your system.

**Comment by tjatjagithub** [comment]
> @tjatjagithub
> 
> Why would you want a massive block of potentially changing defaults statically set by installation? I completely agree about making finding information about the configuration as easy as possible. I recommend simply cloning/forking alacritty and maintaining the source on your system.

Because nearly all application of the whole world and any imaginable operating systems do the same?
Install the default config file to the default configuration and be finished.
For a new release, just add the new default as additional file so that users can benefit from changes too.
Super easy and super normal.
