### ISSUE TITLE
Let Alacritty opens a terminal app and stay open after app quits

### ISSUE THREAD

**Issue by rudolfschmidt** [alacritty/alacritty#3818]
OS: Linux
Version: alacritty 0.4.3
Linux/BSD: i3
Windows: WinPTY

I want to create a shortcut to open ranger and stay within the terminal after I quit ranger.

In addition, I use that script to make ranger remember the last dir I was in, so after I quit ranger my terminal automatically cd to rangers last directory

```
#!/usr/bin/env bash
lastdir=$HOME/.config/ranger/lastdir
/usr/bin/ranger --choosedir=$lastdir
cd "$(<$lastdir)"
```

Unfortunately, I cannot make alacritty stay open. When I use --hold he just let the window open, but no shell is inside. 

Does anyone know how to make it work?

**Comment by chrisduerr** [comment]
alacritty -e bash -c "ranger && exec bash"
