### ISSUE TITLE
Ghost flashing cursor when using fzf.vim

### ISSUE THREAD

**Issue by yanzhang0219** [alacritty/alacritty#3819]
OS: macOS 10.15.5
Version: alacritty 0.5.0-dev (f99220f)

Hi,

I am using [fzf.vim](https://github.com/junegunn/fzf.vim) in neovim. When I start fzf by `:Files` and then move the cursor up and down, there are two abnormal flashing things (GIF attached below). One is a flashing cursor on the right-hand side (i.e., the preview part) of the fzf window. Another flashing is the number column (on the leftmost, like the line number) of the fzf window.

I tested other terminal emulators such as kitty and iTerm2, but both work well and do not show this issue. 

Thank you very much.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11582667/83828714-3011ce80-a696-11ea-87fa-d97f8f264408.gif)

**Comment by chrisduerr** [comment]
See #598.
