### ISSUE TITLE
Padding color is gradient

### ISSUE THREAD

**Issue by xnegra80** [alacritty/alacritty#3832]
I am using qtile as my wm and I set my focused border and unfocused border color to purple and grey respectively. But only for alacritty, I get a gradient of white blending with the color that I set. Is there an option for border color in the yml?

The only settings that I think would be related to this issue is this:

```
window:
  padding:
    x: 10
    y: 10
```

**Comment by chrisduerr** [comment]
Alacritty has nothing to do with your WM's border color. Could you share a screenshot of what you're experiencing?

**Comment by xnegra80** [comment]
![2020-06-08-123953_1920x1200_scrot](https://user-images.githubusercontent.com/22794866/83993139-2b466680-a985-11ea-9022-15fa0b231a4a.png)

Here you go.
As you see there is a white to purple gradient. Is this to do with picom?

**Comment by chrisduerr** [comment]
That's your wallpaper. You have a transparent window with a transparent border on a background that is dark, of course that is going to make it darker.
