### ISSUE TITLE
OS specific override for font config

### ISSUE THREAD

**Issue by houqp** [alacritty/alacritty#3833]
I use alacritty with both Linux and OSX. Is there anyway to set OS specific font setting so I can share a single config across operating systems?

**Comment by chrisduerr** [comment]
No there is not and it is not planned to support something like that.

I'd strongly recommend just managing the config through git and making different branches for different operating systems, that should make things pretty simple.

**Comment by clux** [comment]
One workaround for people that want this:

- create a symlink `~/.config/alacritty/os.toml` pointing to either `~/.config/alacritty/macos.toml` or `~/.config/alacritty/linux.toml`
- add `import = ["~/.config/alacritty/os.toml"]` to `~/.config/alacritty/alacritty.toml`

and this works as alacritty will at least follow the symlink on the include.
to automate it you need some provisioning thing create the link depending on your os.

i [have](https://github.com/clux/dotfiles/blob/492e39a32998d26fd185c9c61160931f30b4d4b3/justfile#L19-L20) a `justfile` recipe to setup the link with `ln -sf $PWD/config/alacritty/{{os()}}.toml config/alacritty/os.toml` in my dotfiles.
