### ISSUE TITLE
vim color 0 uses background color instead of normal black

### ISSUE THREAD

**Issue by lukas-we** [alacritty/alacritty#3836]
I use the solarized dark theme with alacritty and vim, but some elements are not correctly colored.
With `set colorcolumn=80` the column is not highlighted. As defined by the solarized theme, the column should use terminal color 0 (normal black), but instead the primary background color is used. The highlighted column therefore has the same color as the normal background and is not highlighted at all.

If I change the color of the highlighted column via `highlight ColorColumn ctermbg=1`, the column is colored correctly for any of the remaining 15 terminal colors.

### Color settings

```
# Colors (Solarized Dark)
colors:
  # Default colors
  primary:
    background: '#002b36' # base03
    foreground: '#839496' # base0

  # Cursor colors
  cursor:
    text:   '#002b36' # base03
    cursor: '#839496' # base0

  # Normal colors
  normal:
    black:   '#073642' # base02
    red:     '#dc322f' # red
    green:   '#859900' # green
    yellow:  '#b58900' # yellow
    blue:    '#268bd2' # blue
    magenta: '#d33682' # magenta
    cyan:    '#2aa198' # cyan
    white:   '#eee8d5' # base2

  # Bright colors
  bright:
    black:   '#002b36' # base01
    red:     '#cb4b16' # orange
    green:   '#586e75' # base01
    yellow:  '#657b83' # base00
    blue:    '#839496' # base0
    magenta: '#6c71c4' # violet
    cyan:    '#93a1a1' # base1
    white:   '#fdf6e3' # base3
```

### System

OS: Windows
Version: alacritty 0.4.3 (c723247)
Windows: WinPTY and ConPTY

**Comment by kchibisov** [comment]
Does that work `printf "\e[40mblack\n"` or `printf "\e[48;5;0mhello\n"` it should print black color.

**Comment by lukas-we** [comment]
No, that does not work either. However, if I try to change the text color (not the background color) using `printf "\e[30mblack\n"` or `printf "\e[38;5;0mhello\n"`, that does work.

**Comment by chrisduerr** [comment]
Which Windows version is this? Have you verified that both ConPTY and WinPTY are actually used using `alacritty -v`?

**Comment by lukas-we** [comment]
My version of Windows is 10.0.18363 Build 18363.

Yes, I have it verified for both WinPTY and ConPTY. When I set `winpty_backend: true` in the configuration, `alacritty.exe -v` prints:
> [2020-06-09 16:24:22.902403700] [INFO] Using WinPTY backend

If I use `winpty_backend: false`, it says:
> [2020-06-09 16:27:20.206282400] [INFO] Using ConPTY backend

In either case color 0 is neither used in vim nor used with `printf "\e[40mblack\n"` or `printf "\e[48;5;0mhello\n"`.

**Comment by chrisduerr** [comment]
It's probably that Windows is changing the escape sequence to use the background color instead of black, which wouldn't be surprising with how broken their WinPTY and ConPTY are. Though I'd like to verify that just to make sure.

Could you run Alacritty using `alacritty --ref-test`, then run `printf "\e[41mred\e[40mblack\n"`? This should output a couple of files in your working directory, I'm only interested in the `alacritty.recording`.

**Comment by lukas-we** [comment]
Here is the `alacritty.recording` file. (I compressed it, so Github would allow me to upload the it.)

[alacritty.recording.gz](https://github.com/alacritty/alacritty/files/4753011/alacritty.recording.gz)

> It's probably that Windows is changing the escape sequence to use the background color instead of black, which wouldn't be surprising with how broken their WinPTY and ConPTY are. Though I'd like to verify that just to make sure.

In that case, other terminal emulators should be affected, too, shouldn't they? I checked now with Windows Terminal and indeed it does exhibit the same behavior.

**Comment by kchibisov** [comment]
>I checked now with Windows Terminal and indeed it does exhibit the same behavior.

That's how it goes on Windows and we basically just ensuring again and again that windows is broken, since if that was a real our bug other platforms would be broken as well, since they share the code. However sometimes Windows Terminal embeds ConPty which has fixes already, so in that case we can differ. So there's nothing we can do about such issues.
