### ISSUE TITLE
[FR] Portable config mode

### ISSUE THREAD

**Issue by Kein** [alacritty/alacritty#3838]
### System
OS: Windows

From the readme:

```
On Windows, the config file should be located at:
%APPDATA%\alacritty\alacritty.yml
```

This makes it impossible to use in portable mode. **alacritty** being hard-limited to %APPDATA% prevents being able to just copy the app folder and use it elsewhere with the same configuration setup. This feature request does not require massive changes, just add extra location to check for config which is approot/working dir

**Comment by kchibisov** [comment]
You can pass `--config-file YOUR_CONFIG` to it. I guess you can even setup default command line arguments for it.
