### ISSUE TITLE
[feature request] Smooth Cursor Animation

### ISSUE THREAD

**Issue by mrillusi0n** [alacritty/alacritty#3844]
Though it would be cool to have a setting that enables the cursor to move smoothly, something as below.

![ezgif-6-be08e43a2de3](https://user-images.githubusercontent.com/37063502/84480978-03bc0a80-acb3-11ea-8be8-563f46c1d4d9.gif)

**Comment by kchibisov** [comment]
Doesn't make any sense for terminal emulator, since a cursor is primary used to write contents on screen as well, so you have no distinction between cursor for editing and cursor for writing and so any cursor movement animations  won't play nice and just unnecessary complexity.

**Comment by anarki1** [comment]
> Doesn't make any sense for terminal emulator, since a cursor is primary used to write contents on screen as well, so you have no distinction between cursor for editing and cursor for writing and so any cursor movement animations won't play nice and just unnecessary complexity.

I literally do not care, we just the OPTION for a smooth cursor

**Comment by chrisduerr** [comment]
> I literally do not care

Then do it yourself lol.

**Comment by JohnWickey** [comment]
> Then do it yourself lol.
I would love to, but I don't know how.  
Do you think that he would come on here for a feature request because he knows how to?

**Comment by chrisduerr** [comment]
Feel free to write this patch and drop a link to it/your fork in the comments. But this will not be upstreamed.

**Comment by fynnfluegge** [comment]
Hey @afritfr this might help you
https://github.com/echasnovski/mini.animate

**Comment by afritfr** [comment]
@fynnfluegge Thanks i'll try it.

**Comment by nnra6864** [comment]
I don't know why majority of devs straight up refuse to look at this.
There's a fork [alacritty-smooth-cursor](https://github.com/GregTheMadMonk/alacritty-smooth-cursor) that implements this feature almost flawlessly.
Keyword being almost.
Running it on wayland is quite problematic, there's either a lot of lag or limitations of running it under X11(broken clipboard, weird resizing issues etc.).
I would like all the people opposing this feature to just use it for a single day and then open a regular terminal and move the cursor around.

**Comment by Trowee** [comment]
It would be realy nice to see that. It would look much better!

**Comment by ElSamhaa** [comment]
I would love to see smoother cursor animation at least similar to what Corsh has. It just feels better.

**Comment by nnra6864** [comment]
> I would love to see smoother cursor animation at least similar to what Corsh has. It just feels better.

Would you mind linking Corsh?
I couldn't find anything on it.

**Comment by ElSamhaa** [comment]
Hi @nnra6864, I meant Crosh https://www.chromium.org/chromium-os/developer-library/reference/device/crosh/
sorry for the typo :)

**Comment by chardskarth** [comment]
> It is possible to reopen this? I would like to take a look a it.
> 
> To me this is not like a fancy gadget but rather a very useful feature, since you won't loose the focus of the eye on the cursor even when jumping around superfast (e.g. in vim).
> 
> Neovide provides these kind of cursor animations and it is very helpful in some constellations.
> 
> I would like to implement this feature once reopened.

I'm here exactly because of neovim. Successfully got what I'm looking for from this fork. Awesome!

**Comment by tylxm** [comment]
Kitty merged the neovide like animation, https://github.com/kovidgoyal/kitty/pull/7970

**Comment by nnra6864** [comment]
> Kitty merged the neovide like animation, [kovidgoyal/kitty#7970](https://github.com/kovidgoyal/kitty/pull/7970)

This is such an excellent implementation, I recommend the following settings for a Neovide like experience:
```
cursor_trail 1
cursor_trail_start_threshold 0
```

**Comment by Faetu** [comment]
> > Kitty merged the neovide like animation, [kovidgoyal/kitty#7970](https://github.com/kovidgoyal/kitty/pull/7970)
> 
> This is such an excellent implementation, I recommend the following settings for a Neovide like experience:
> 
> ```
> cursor_shape block
> cursor_trail 1
> cursor_trail_start_threshold 0
> shell_integration no-cursor
> ```

Nice! thx.
Now I can throw away alacritty (toxic devs) and enjoy kitty.

**Comment by azabroflovski** [comment]
Why not? Neovide gives a cool experience, I like it, too bad, I'm switching to kitty (they added such animation)

**Comment by alacine** [comment]
I agree that smooth cursor animations don't add much functional value for most individual use cases, and they're mainly aesthetic. However, I do think there are certain scenarios where they can be genuinely helpful.

For example, during team presentations or screen sharing sessions, when someone is demonstrating command-line workflows using tools like tmux or editing with vim, it can be hard for viewers to follow what’s happening—especially if the presenter is working quickly. A smooth cursor animation provides a clear visual cue of where the cursor is moving, which can help viewers track the presenter’s actions more easily and stay in sync with the flow of the demonstration.

So while it's not essential for everyone, it could be a useful optional feature in collaborative or teaching contexts.

**Comment by shadowe1ite** [comment]
I just switched from Kitty to Alacritty. I didn’t expect the devs to be this rude.
Everyone is slowly starting to implement this feature Kitty already has it, and WezTerm even has a pull request.
It’s stupid to ignore user requests like this

**Comment by nnra6864** [comment]
> I just switched from Kitty to Alacritty. I didn’t expect the devs to be this rude. Everyone is slowly starting to implement this feature Kitty already has it, and WezTerm even has a pull request. It’s stupid to ignore user requests like this

Just use ghostty or kitty, faster and better anyways.

**Comment by shadowe1ite** [comment]
> > I just switched from Kitty to Alacritty. I didn’t expect the devs to be this rude. Everyone is slowly starting to implement this feature Kitty already has it, and WezTerm even has a pull request. It’s stupid to ignore user requests like this
> 
> Just use ghostty or kitty, faster and better anyways.

Kitty is slow, I will try ghostty thanks

**Comment by nnra6864** [comment]
> Kitty is slow, I will try ghostty thanks

Ghostty is pretty good when it comes to speed, although you should really use the single instance feature as it's literally 10x faster.
On top of that, you can make your bind launch ghostty with `+new-window` flag to make it as fast as foot, e.g. in hyprland:
`bind = $mainMod, Q, exec, ghostty +new-window`
