### ISSUE TITLE
windows 0.4.3 - cursor blinks on the top left

### ISSUE THREAD

**Issue by cakruege** [alacritty/alacritty#3845]
OS: Windows
Version: alacritty --version
Linux/BSD: X11/Wayland, DE or Compositor and WM
Windows: ConPTY 

If I repeatedly type any key on my keyboard for example "a"
writing
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

On the top left of the screen a cursor flashes up, every time an "a" is printed.

Location is x=1,y=0, if x=0,y=0 is top,left

**Comment by chrisduerr** [comment]
Sounds like whatever program/shell you're running, it's just redrawing the entire screen for every character and moving the cursor around a bunch for that.

The only fix for that would be supporting #598, though that also requires application support. Other than that we're just doing what the program tells us to do.
