### ISSUE TITLE
Slower redraw with bigger window

### ISSUE THREAD

**Issue by danieltrautmann** [alacritty/alacritty#3851]
After having a great start with Alacritty, I realized today, that the redraw time increases significantly when the window is bigger. It works "okay" on my Retina display, but when I've tried to use it today on my 4K screen in the office, I've noticed this slow down.
I'm using a 15 inch MacBook Pro from 2015.

I made two Gifs that shows this issue with the `render_timer` turned on.

**Small**

![small_window](https://user-images.githubusercontent.com/4022138/84696090-3c2a4580-af4c-11ea-8608-362fb33b8c85.gif)

**Full Screen**

![full_screen](https://user-images.githubusercontent.com/4022138/84696127-4a786180-af4c-11ea-862d-b6327074fc52.gif)

### System

OS: macOS (10.15.5)
Version: alacritty 0.4.3 (c723247)

### Logs

The last line shows the full screen size.

```
> alacritty -vv
Created log file at "/var/folders/2r/xknybh5n1yjcz3kg_7pk44c00000gn/T/Alacritty-46241.log"
[2020-06-15 20:57:43.565647000] [DEBUG] Using environment locale: en_US.UTF-8
[2020-06-15 20:57:43.565883000] [INFO] Welcome to Alacritty
[2020-06-15 20:57:43.565914000] [INFO] Configuration loaded from "/Users/danieltrautmann/.config/alacritty/alacritty.yml"
[2020-06-15 20:57:43.608875000] [DEBUG] Estimated DPR: 2
[2020-06-15 20:57:43.608957000] [DEBUG] Estimated Cell Size: 15 x 40
[2020-06-15 20:57:43.608986000] [DEBUG] Estimated Dimensions: None
[2020-06-15 20:57:43.673661000] [INFO] Device pixel ratio: 2
[2020-06-15 20:57:43.677113000] [INFO] Initializing glyph cache...
[2020-06-15 20:57:43.720220000] [INFO] ... finished initializing glyph cache in 0.043018491s
[2020-06-15 20:57:43.720329000] [INFO] Cell Size: 15 x 40
[2020-06-15 20:57:43.720360000] [INFO] Padding: 10 x 10
[2020-06-15 20:57:43.720387000] [INFO] Width: 1600, Height: 1200
[2020-06-15 20:57:43.720523000] [INFO] PTY Dimensions: Line(29) x Column(105)
[2020-06-15 20:57:43.724023000] [INFO] Initialisation complete
[2020-06-15 20:58:15.895569000] [DEBUG] New num_cols is 190 and num_lines is 42
[2020-06-15 20:58:15.905335000] [INFO] Width: 2880, Height: 1710
```

**Comment by kchibisov** [comment]
Do you have dGPU or integrated GPU? Maybe the amount of VRAM we're using is not something macOS likes? Like we had problems with only macOS in the past regardless rendering, but it's hard to tell who's fault here, since apple OpenGL is borken most of the time...

**Comment by danieltrautmann** [comment]
I'm not so sure whether it's integrated or not. It is `Intel Iris Pro 1536 MB`, so I guess it is integrated.

**Comment by kchibisov** [comment]
yeah, it's integrated GPU. I don't have any idea how to profile GPU on macOS, but I'd assume macOS is just doing something odd or doesn't like the amount of VRAM we're trying to use(even though it has enough).

**Comment by chrisduerr** [comment]
Even at 10ms that seems relatively slow. How did you install Alacritty?

**Comment by danieltrautmann** [comment]
I installed it via `brew`, which was mentioned in the readme.

**Comment by danieltrautmann** [comment]
I tried to find out more about GPU profiling on macOS and saw that Apple deprecated OpenGL in macOS 10.14.

```
Important: OpenGL was deprecated in macOS 10.14. To create high-performance code on GPUs, use the Metal framework instead.
```

Not sure if its worth digging deeper into this.

**Comment by chrisduerr** [comment]
The render time goes up to ~10ms when I see that correctly, which is absolutely awful but the gif seems like it's far slower than that. With 10ms we should still have 6ms to process everything on a 60Hz monitor.

You can try this patch to log the times between rendering, those might be interesting to look at too: https://paste.rs/3Lp.diff

**Comment by danieltrautmann** [comment]
Okay I will try that as soon as possible.

**Comment by danieltrautmann** [comment]
I applied the patch and compiled it, but I can't run the App on my Mac. Starting it from the command line tells me this:

```
The application cannot be opened because it has an incorrect executable format.
```

Indeed the format is different from the one I've installed via Brew.

```
> file target/release/osx/Alacritty.app/Contents/MacOS/alacritty
target/release/osx/Alacritty.app/Contents/MacOS/alacritty: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=ef6709718ef08d5397120d62e9d762768f1d05a4, with debug_info, not stripped
```

```
> file /Applications/Alacritty.app/Contents/MacOS/alacritty
/Applications/Alacritty.app/Contents/MacOS/alacritty: Mach-O 64-bit executable x86_64
```

I've compiled it on a Linux remote machine, since there was no instruction how to compile it on macOS. Was that a mistake? If so, how can I compile it on macOS?

**Comment by kchibisov** [comment]
ofc it won't work, you should compile it on macOS. The instructions are the same for macOS, there's no difference, except that you don't need to install anything. Just do a build and it should be good.

**Comment by danieltrautmann** [comment]
Sorry, my bad. I'm not a Rust developer and it seems I'm spoiled by Go's cross-compiling feature.

Anyway. After compiling it, it seems that the issue is gone. Here is a Gif again.

![2020-06-17 09 28 28](https://user-images.githubusercontent.com/4022138/84868655-544db200-b07d-11ea-9e4b-e40e3b223e45.gif)

**Comment by chrisduerr** [comment]
Are you using a laptop on battery power? Can you try plugging it into the wall?

**Comment by danieltrautmann** [comment]
Yes I did. Don't see much difference with the MacBook plugged in. Seems slightly faster.

![2020-06-17 09 47 00](https://user-images.githubusercontent.com/4022138/84870534-b8717580-b07f-11ea-8adc-7aabfeff1a58.gif)

**Comment by chrisduerr** [comment]
> Anyway. After compiling it, it seems that the issue is gone. Here is a Gif again.

I'd assume you're just running the executable directly to test?

Is it broken again when you `make app` and execute that?

**Comment by kchibisov** [comment]
The gif feels slow to me, and knowing that render_timer is now capturing a different value it feels like the issue is the same? Anyway, what is your display scale factor on macOS, is it some fractional scale factor(aka 150% value, etc)?

**Comment by kchibisov** [comment]
Also, revert the patch before doing `make app` or rerun without this patch, since it'll start showing correct time for rendering.

**Comment by danieltrautmann** [comment]
Yes I did run the executable directly. Running the Mac App doesn't make any difference.

The scale factor seems to be 2 or 200%. The display has a native resolution of 2880 x 1800 and the macOS display settings are telling me that it will look like 1440 x 900.

After reverting the patch, the behavior is the same. Redrawing time doesn't go higher than 4500 usec.

All of that was done on the most recent commit in the master branch.

**Comment by kchibisov** [comment]
Hm, but your original issue was on 4k screen? Anyway, do you have the issue with the build you're running or not?

**Comment by danieltrautmann** [comment]
Well, I did notice this on a 4K screen in the first place and then started experimenting with the window sizes. All Gifs, and debugging was done on the Mac Retina display.

Connecting or disconnecting the 4K screen didn't change anything.

I don't have any issue with the compiled version now.

**Comment by kchibisov** [comment]
So it's not our bug then? brew versions are not maintained by us. Maybe something changed regardless perf on master, but I don't remember that we've touched anything related to that.
