### ISSUE TITLE
Content of Alacritty window is not centered

### ISSUE THREAD

**Issue by DavidHusicka** [alacritty/alacritty#3858]
Content of Alacritty window is not centered and results in empty space on bottom and left of the window.
![Screenshot from 2020-06-16 14-47-37](https://user-images.githubusercontent.com/25853767/84877717-253d3d80-b089-11ea-88ee-74774dabedb0.png)

This part from my config file might be helpful when solving the issue:
```yml
  padding:
    x: 0
    y: 0
```

### System

OS: GNU/Linux
Version: alacritty 0.4.3
Linux/BSD: X11, i3wm

**Comment by chrisduerr** [comment]
Because a terminal is a fixed size grid. Use dynamic padding if you want to spread out the extra padding evenly.

**Comment by DavidHusicka** [comment]
I don't want to fill these gaps. I just think that these gaps should be same size on all sides. Sorry if I wrote it in such a way it was misunderstood and sounded like I want to get rid of them.

**Comment by kchibisov** [comment]
It was said that you can use `dynamic_padding` setting in a config to solve your 'issue'.

**Comment by DavidHusicka** [comment]
I'm sorry, I just glanced over the response. Thank you.
