### ISSUE TITLE
Prompt and Cursor Issue

### ISSUE THREAD

**Issue by SreejeshSaya** [alacritty/alacritty#3864]
I had installed Alacritty yesterday on my machine and faced this issue today. I can't really explain what's going on but I hope the gif helps. It's looks like some rendering issue.

![2020-06-18-11-02-04](https://user-images.githubusercontent.com/40210225/84982214-d7413c00-b153-11ea-8e64-e5766eb06be0.gif)

### System

OS: Linux - Ubuntu 18.04.4
Version: alacritty 0.4.1
Linux/BSD: X11, Gnome
GPU: Nvidia GTX 1060 (Driver Version 440.82)

## Logs
Terminal Size: 800x600

**Comment by kchibisov** [comment]
Could you try 0.4.3 version?

**Comment by SreejeshSaya** [comment]
I shall install the 0.4.3 version and see if the problem persists

**Comment by chrisduerr** [comment]
I'm not quite sure what I'm seeing here? There's a lot going on in that gif. Could you maybe be a little more concrete on what your issue is?

**Comment by SreejeshSaya** [comment]
While going through my command history, it removes my current prompt line and tries to overwrite the previous/above line as observed in the gif. This problem does not exist on the default gnome-terminal on my machine. 
I guess an explanation for this issue would be that it's overwriting the previous/above line (something that should not happen) while going through bash_history. 
I have cleared the bash history and I will observe if this problem appears again. If it doesn't, I will close this issue or else I will post an update. 
Is this helpful?
Hope it is understood now. It's my first issue on GitHub, sorry if I haven't followed certain guidelines. :)

**Comment by chrisduerr** [comment]
What's your `TERM` and does it work when setting it to `xterm-256color`?

**Comment by SreejeshSaya** [comment]
My TERM is xterm-256color. It's already set in the configuration file.
I haven't seen this issue again after clearing the bash_history. I will observe for another two days. If it doesn't, I'll close this issue.
I really hope it doesn't appear again, since I'm really enjoying alacritty.

**Comment by chrisduerr** [comment]
> My TERM is xterm-256color. It's already set in the configuration file.

The only supported TERM values are `alacritty` and `alacritty-direct`. Please make sure to test these before reporting an issue (though I don't think that's the problem here).

So it seems like the issue is only related to a shell binding that jumps to the beginning of the line? That seems like something that would be more related to the shell itself than Alacritty. Can you reliably reproduce this in Alacritty, while it works in other terminals?

If it works in other terminals, you can test if Alacritty is sending a different escape by checking the output of `showkey -a`.

**Comment by SreejeshSaya** [comment]
I have found the issue. It is not an alacritty problem. I guess it is because of my custom prompt styling. As @chrisduerr suggested, I did try it on the default gnome-terminal and the problem appeared there too. The problem disappeared when I set the prompt style back to the default setting. 
Thank you @chrisduerr for your help.
