### ISSUE TITLE
Cant run built binary

### ISSUE THREAD

**Issue by refaelsh** [alacritty/alacritty#3867]
I am trying to build Alacritty from source. It builds fine.
But when I run the built binary, I get this error:
```
[nix-shell:~/repos/alacritty]$ ./target/debug/alacritty
Alacritty encountered an unrecoverable error:

	Error creating GL context; Received multiple errors. Errors: `[NotSupported("lacking either libGL or libEGL so could not fallback to other"), NotSupported("both libGL and libEGL are not present")]`


[nix-shell:~/repos/alacritty]$
```

I am running NixOS stable in VM.
Please help :-)

**Comment by kchibisov** [comment]
refer to original nix build for alacritty in the nixpkgs repo. You should patchelf binaries on nix, nothing we can help you with, since it's purely a nixos thing.

**Comment by refaelsh** [comment]
Oh, now I understand its not an issue in Alacritty. Thanks :-)
Could please clarify what you mean by the word `patchelf`?

**Comment by kchibisov** [comment]
https://github.com/NixOS/patchelf

**Comment by kchibisov** [comment]
Alacritty is using dlopen to open dynamic libraries, so you have to modify rpath.  Just follow https://github.com/NixOS/nixpkgs/blob/a9b1845d608e49b7c2f0a55e14b6bb5bce4b8677/pkgs/applications/misc/alacritty/default.nix#L113

**Comment by refaelsh** [comment]
Understood. Thank you very much. I will go and read the links.

**Comment by kiranajij** [comment]
I did not understand the fix, can you pls elaborate

**Comment by refaelsh** [comment]
Since NixOS is a very special distro, it does not have anything in `/usr/bin`, and everything is using sim-links, the standard library path is also non-existant. Thereofre, the built binary needs its `rpath` changed.

**Comment by refaelsh** [comment]
> 
> 
> I did not understand the fix, can you pls elaborate

Since NixOS is a very special distro, it does not have anything in `/usr/bin`, and everything is using sim-links, the standard library path is also non-existant. Thereofre, the built binary needs its `rpath` changed.
