### ISSUE TITLE
Escape sequence for switching/restoring buffer not working?

### ISSUE THREAD

**Issue by mi-lad** [alacritty/alacritty#3869]
### System
OS: Linux
Version: alacritty 0.5.0-dev (840cb1b9)
Linux/BSD: X11 i3

I'm working on a terminal gui program (imagine something htop) which switches to a new buffer and restores the old one by sending the following escape sequences at the beginning and end of program:

```
ESC = "\x1b"
SWITCH_TO_ALTERNATE_BUFFER = ESC+"7"+ESC+"[?47h"
RESTORE_NORMAL_BUFFER = ESC+"[?47l"+ESC+"8"
```
These do not seem to work in alacritty as the terminal buffer is not restored at the end of the program. They do however work in some of the other terminals I tried (e.g. `st` and `xterm`).

**Comment by chrisduerr** [comment]
You should use the `\e[1049h` and `\e[1049l` escapes to enter and leave the alternate screen buffer, or ideally just rely on the `smcup` and `rmcup` terminfo capabilities.

How did you get the idea to use private mode 47?

**Comment by mi-lad** [comment]
This is part of the `urwid` library: `https://github.com/urwid/urwid/blob/master/urwid/escape.py#L412-L413`

I'll raise an issue in their repo.

**Comment by chrisduerr** [comment]
A library meant as anything but a hack just hardcoding escape sequences like that with no regard for terminfo sounds **very** strange to me.

**Comment by mi-lad** [comment]
I got the impression that they've gone this route because they've faced issues with terminfo over ssh.

So am I right in thinking that the only thing they'd have to do is changing `47` to `1049` like below?

```
ESC = "\x1b"
SWITCH_TO_ALTERNATE_BUFFER = ESC+"7"+ESC+"[?1049h"
RESTORE_NORMAL_BUFFER = ESC+"[?1049l"+ESC+"8"
```

**Comment by chrisduerr** [comment]
> I got the impression that they've gone this route because they've faced issues with terminfo over ssh.
>
> So am I right in thinking that the only thing they'd have to do is changing 47 to 1049 like below?

No, the right thing to do is query terminfo. On a remote machine the terminfo files required should also be present, that's how it's supposed to work. There is no 'terminfo over ssh' problem that applications have to be concerned with.
