### ISSUE TITLE
SpawnNewInstance spawns two new instances

### ISSUE THREAD

**Issue by Keno** [alacritty/alacritty#3870]
I have the following alacritty.yml:

```
key_bindings:
  - { key: V,        mods: Super, action: Paste             }
  - { key: C,        mods: Super, action: Copy              }
  - { key: N,        mods: Super, action: SpawnNewInstance  }
```

now, when I hit Super+N, I get two new alacritty instances, rather than just one.

### System

OS: Linux (Ubuntu 20.04)
Version: alacritty 0.4.1
Linux/BSD: X11, gdm3
Windows: WinPTY/ConPTY (see `alacritty -v` output)

### Logs

Keyboard and bindings: [alacritty --print-events](https://gist.github.com/Keno/e6fa7b2f8a3870a370644a8725e410bb)

**Comment by kchibisov** [comment]
Try latest version. In general, I feel like GNOME already provides with `Super + N` hotkey to open new instance.

**Comment by Keno** [comment]
Seems to be fixed in a master build. Thanks.
