### ISSUE TITLE
opacity-rule does not work with alacritty

### ISSUE THREAD

**Issue by PPHyperion** [alacritty/alacritty#3872]
When I edit the active-opacity, the opacity of alacritty is set as defined. The inactive instance of alacritty is always 1.
I defined the opacity in picom.conf like this:

`opacity-rule = [
   "50:class_g = 'alacritty' && focused",
   "50:class_g = 'alacritty' && !focused",
   "50:class_g = 'firefox' && focused",
   "50:class_g = 'firefox' && !focused",
];`

The opacity only works with firefox.
In the alacritty config I have nothing regarding opacity.

### System

OS: Arch Linux
Version: 0.4.3
Linux/BSD: X11, Picom, bspwm

**Comment by chrisduerr** [comment]
> In the alacritty config I have nothing regarding opacity.

If you want Alacritty to be transparent, maybe you should set it to be transparent in the config?

**Comment by kchibisov** [comment]
The class is `Alacritty`, not `alacritty`.
