### ISSUE TITLE
Device pixel ratio problem

### ISSUE THREAD

**Issue by XueqiLi** [alacritty/alacritty#3876]
OS: Arch
Alacritty ver: 0.4.3
I am using X11 starts with xinit
WM: i3
Only one display.

The output of ` alacritty -vvv` shows a `Estimated DPR: 1.66666667` and a `Device pixel ratio: 1.66666667` (more 6s then I typed). (and I can see my fonts size is quite large)

I did not have this problem before, since I set `WINIT_HIDPI_FACTOR=1.0 ` in my `.xinitrc`. But now I have this problem after update.  `WINIT_HIDPI_FACTOR=1.0` is still in my `.xinitrc` now.

After some search, I tried to add `WINIT_HIDPI_FACTOR: 1.0` or `WINIT_HIDPI_FACTOR: "1"` in `env:` section of Alacritty conf file. This does not solve the problem. I also try to add `WINIT_HIDPI_FACTOR=1.0` in `.zshrc` (even though it is already in `.xinitrc`), this does not solve the problem.

I also tried to run `WINIT_HIDPI_FACTOR=1 alacritty`. This does not give the right DPR (and I can see my fonts size is still large). `WINIT_HIDPI_FACTOR=1 alacritty -vvv` still give a 1.6 as Estimated DPR and Device pixel ratio.

**Comment by chrisduerr** [comment]
The variable was changed to `WINIT_X11_SCALE_FACTOR=1`.
