### ISSUE TITLE
Characters overlap

### ISSUE THREAD

**Issue by maojiahui** [alacritty/alacritty#3881]
OS:manjaro
alacritty ver:0.4.3-1

It seems strange that if offer: X defaults to 0, the characters will overlap.
If offset:x=5 , each character is wider, but it looks strange. I don't know how to center each character. They all look aligned to the right
![default](https://user-images.githubusercontent.com/21058038/85503842-2e945000-b61d-11ea-88a1-97899153c10c.png)
![right](https://user-images.githubusercontent.com/21058038/85503849-33590400-b61d-11ea-80ea-fbe0b86ef21f.png)

By the way, there is another point.

No matter how my font is set, it doesn't work. I don't know what's wrong with my configuration file. Should I set the absolute path

**Comment by kchibisov** [comment]
The font is named `JetBrains Mono`. Use `fc-list : family` to list all font families available. The overlapping is due to use of sans-serif font, since fontconfig failed to find a proper font.

**Comment by maojiahui** [comment]
Thank you so much!
I've been Googling for a long time, hahaha
