### ISSUE TITLE
Parameter -e removes 256-color support for "alacritty -e nvim +terminal"

### ISSUE THREAD

**Issue by kllp** [alacritty/alacritty#3885]
Run alacritty. Then in alacritty run "nvim +terminal"
The colors in nvim's terminal show correctly
Run "alacritty -e nvim +terminal"
Some colors are wrong (blueish)
I used the script "colortest" for testing. You can find it here:
https://github.com/chriskempson/base16-shell#troubleshooting

Why does "-e" effect the colors?
It should behave the same.

### System
OS: Linux
Version: 0.4.3 and 0.5.0-dev (6c8966f4) I tested both.
Linux/BSD: X11

**Comment by chrisduerr** [comment]
The `-e` command has no effect on anything. It just skips all your shell setup.

I'd recommend comparing environment variables, is there any difference in your setup? It's likely just a problem with your system, it works perfectly fine for me.

**Comment by kllp** [comment]
The environment variables are identical in both cases, except WINDOWID und SHLVL but that shouldn't be a problem.
I recognized that with a default bash setup it always shows wrong colors.
With a default fish setup it doesn't work with -e.
Probably I should try to get the bash setup working first.
What are the minimal color related settings I need?
I suppose it shouldn't work out of the box with the latest versions of alacritty bash and nvim

**Comment by chrisduerr** [comment]
>  What are the minimal color related settings I need?

None, it works out of the box. This sounds like a problem with your shell config.

If you have any Alacritty specific questions, please let me know. But it doesn't sound like there's anything wrong with Alacritty here.

**Comment by kllp** [comment]
Alright, instead of using the base16 colortest script I should've used https://github.com/eikenb/terminal-colors to verify things
Base16 is not working correctly for me so I got to find a working theme
