### ISSUE TITLE
Unexpected behaviour with Tmux in Alacritty

### ISSUE THREAD

**Issue by rfwatson** [alacritty/alacritty#3887]
Hello!

If I follow the following steps:

1. Open two Alacritty terminals in separate windows
1. In terminal 1:
  `tmux new -s session1`
2. In terminal 2:
  `tmux new -s session2`
  `:set status-bg blue`

**Expected behaviour**:
The tmux status bar colour changes only in terminal 2

**Actual behaviour**:
The tmux status bar colour changes in terminal 1 and terminal 2

Is this expected? I'm opening an issue here because I don't see this behaviour in tmux with identical configuration in other terminal emulators.

Thanks :pray: 

### System

OS: Arch Linux/xfce4
Version: `alacritty 0.5.0-dev (6c8966f)`
Linux/BSD: X11

### Logs

```
[2020-06-26 13:23:37.721954674] [INFO] Cell Size: 7 x 15
[2020-06-26 13:23:37.721959768] [INFO] Padding: 0 x 0
[2020-06-26 13:23:37.721966143] [INFO] Width: 800, Height: 600
[2020-06-26 13:23:37.722500049] [INFO] PTY dimensions: Line(40) x Column(114)
```

**Comment by chrisduerr** [comment]
Probably, Alacritty has nothing to do with tmux. So it's synchronizing these changes itself and explicitly asking Alacritty to change in all instances. So yeah, chances are tmux just wants to maintain a consistent look.

**Comment by rfwatson** [comment]
Thanks.

I dug a bit deeper and it turns out that this behaviour actually changed in recent versions of Tmux. In case it helps anybody else: https://unix.stackexchange.com/a/566600
