### ISSUE TITLE
xterm argument compatibility for FvwmConsole

### ISSUE THREAD

**Issue by mz2212** [alacritty/alacritty#3888]
Alacritty right now can't be used in place of `xterm` in some cases, notably `FvwmConsole`.
For alacritty to work with `FvwmConsole` it needs to implement `-name` and `-title`.

I've got a pretty good idea as to how to implement these, and I can get a pull request submitted if that's ok.

Another possible solution could be to ignore unknown flags/arguments, because a majority of `xterm`'s arguments are primarily for asthetics. I personally think this is the better route, though I don't know how to implement it.

**Comment by kchibisov** [comment]
The arguments are `--title` and `--class`. I'm not sure that we should preserve argument name compatibility, knowing that vte also differs here.

**Comment by chrisduerr** [comment]
> I'm not sure that we should preserve argument name compatibility

I am sure. We shouldn't.

**Comment by mz2212** [comment]
Fair enough.
Thanks for getting back to me so quickly.
