### ISSUE TITLE
UX: Nothing appears when creating GL context fails.

### ISSUE THREAD

**Issue by dyc3** [alacritty/alacritty#3890]
## Current Behavior

If something happens that prevents GPU accelerated applications from using the GPU, Alacritty will fail without providing any visual indicator to the user that something went wrong.

## Expected Behavior

At bare minimum, I expected to see an error box pop up saying that something went wrong.

Ideally, I expected to see an error box pop up with the unrecoverable error in a selectable text box (so the user can copy the error), and possibly an option to start in a "no-gpu mode" so I wouldn't potentially be left in a situation with no terminal.

### System

OS: Linux - Ubuntu 18.04
Version: alacritty 0.4.3
Linux/BSD: X11, i3-gaps, compton

### Logs

STDERR/STDOUT

```
Created log file at "/tmp/Alacritty-1595.log"
[2020-06-27 09:32:57.023993713] [INFO] Welcome to Alacritty
[2020-06-27 09:32:57.024087333] [INFO] Configuration loaded from "/home/carson/.config/alacritty/alacritty.yml"
[2020-06-27 09:32:57.035379895] [DEBUG] Estimated DPR: 1.1666666666666667
[2020-06-27 09:32:57.035399235] [DEBUG] Estimated Cell Size: 9 x 18
[2020-06-27 09:32:57.035404175] [DEBUG] Estimated Dimensions: None
Alacritty encountered an unrecoverable error:

	Error creating GL context; Received multiple errors. Errors: `[OsError("eglInitialize failed"), OsError("GL context creation failed")]`
```

**Comment by chrisduerr** [comment]
I'm not sure what you mean? Your nice error text that you can copy is right there in stderr? There is no "no-gpu" mode. Alacritty is *a GPU accelerated terminal emulator*, that's the point. Though your driver might still provide software emulation capabilities (like mesa usually does for example).

**Comment by dyc3** [comment]
I have alacritty set as my default terminal emulator, with a keybind to open a new terminal. When alacritty is started like this, stderr/stdout is not shown. It may not be obvious to users (especially novices) to open a different terminal emulator to run alacritty and see the output.

I am very aware there is no "no-gpu" mode, I was throwing out ideas for an _ideal, perfect world scenario_, because, imo, a terminal should be extremely reliable. What do you mean by software emulation?

**Comment by chrisduerr** [comment]
If Alacritty cannot open for some reason, it cannot open. Checking STDERR when you cannot start an application should always be the first thing to do, which makes the problem very clear. And if OpenGL is not sufficiently supported, there's nothing we can do about that. So I don't see any reason to change anything here.
