### ISSUE TITLE
The icon in GNOME Shell Top Panel is displayed incorrectly

### ISSUE THREAD

**Issue by stamkostas** [alacritty/alacritty#3899]
### System
Version: `0.4.3` & `0.5.0-dev (8a39346)`
OS: `ubuntu-20.04`, `gnome-shell-3.36.2`, `X11`

### Issue
Alacritty's GNOME Shell's Top Panel icon is "stretched" (as in wrong aspect ratio):

![alacritty-icon-issue](https://user-images.githubusercontent.com/741630/85957830-ff6d3e00-b990-11ea-85d1-e349c6e6f840.png)

AFAIK, for this area an app should define a [symbolic icon](https://developer.gnome.org/hig/stable/icons-and-artwork.html.en) that looks great when displayed in that small area...

**Comment by kchibisov** [comment]
Our icon is actually svg already, so if GNOME is having problems with it, it's likely its fault?

**Comment by kchibisov** [comment]
Also, if you did a self install, make sure to put icon in `/usr/share/pixmaps/Alacritty.svg` (from `./extra/logo/?alacritty-term.svg`). I guess it's using `_NET_WM_ICON` here?

**Comment by stamkostas** [comment]
>Also, if you did a self install [...]

That is correct, I did self install and that is the cause of the issue. When I installed using the PPA it shows great :-) Apologies for the false alarm...

**Comment by kchibisov** [comment]
yeah, if you do self install just perform https://github.com/alacritty/alacritty/blob/master/INSTALL.md#desktop-entry as well and you should be good.
