### ISSUE TITLE
terminal capability "cm" required causes viewing and editing issues

### ISSUE THREAD

**Issue by c-torre** [alacritty/alacritty#3901]
File viewing/editing with terminal programs in remote machine causes several issues as described below. The desired behavior is the normal behavior of respective programs. This issue is not present with `st`, `xterm` or `gnome-terminal`. The issue may be related to both Alacritty and the cluster, or just to one of them.

I `ssh` from my Manjaro machine to a CentOS cluster using local Alacritty. Upon login to remote cluster, the following is displayed:

```
tput: unknown terminal "alacritty"
```

Despite the warning, `ls`, `cd`, and other common coreutils work and do not prompt further warnings.
However, I attemped to edit/view a file with `vim`/`less` through `ssh` in the cluster, and the following is displayed:

### Vim

```
E437: terminal capability "cm" required
Press ENTER or type command to continue"analysis.job" 
```

![alacritty-remote-vim-error](https://user-images.githubusercontent.com/48769508/85982093-c656bd00-b9d4-11ea-955a-ded05fda36c0.png)

Where keys have no effect and pressing "j" just added numbers after "All" (one per keypress) as seen indicated by an arrow at the bottom of the screenshot.

### Less

```
WARNING: terminal is not fully functional
test.job  (press RETURN)
```

`less` pressing enter makes it work as it is not as interactive as `vim`, thus the file is displayed after the warnings.

### System

System information will be listed as (local) -- (remote)

OS: Manjaro GNU/Linux -- CentOS GNU/Linux
Terminal: Alacritty -- N/A (defaults to xterm)
Version: 0.4.3 -- N/A
Display server: Wayland -- None/terminal

Note: Alacritty has no issues at all when used in my local machine.

**Comment by enizor** [comment]
Probably the same as #3606 

> You probably haven't installed Alacritty's terminfo on your remote system.
> So either you have to install it, or you have to change your terminfo for ssh using `TERM=xterm-256color ssh` for example.

**Comment by c-torre** [comment]
I uncommented and modified the following line in alacritty.yml from default value to:

```
TERM: xterm-256color
```

and later to:

```
TERM: st-256color
```

For both configurations, the issue was solved.
However, the .yml file also says:

```
# This value is used to set the `$TERM` environment variable for
# each instance of Alacritty. If it is not present, alacritty will
# check the local terminfo database and use `alacritty` if it is
# available, otherwise `xterm-256color` is used.
```

Wouldn't this mean that the fact that it didn't fall back to "xterm-256color" is a bug? I'm not sure here

**Comment by kchibisov** [comment]
It means that its presented on your host, we can't do anything about remotes, etc. So, it's not a bug. If your host doesn't have `alacritty` terminfo, it'll use `xterm-256color` here, but since it's using `alacritty`, means that it's presented on host (try `infocmp alacritty` on host system, it should output something).

**Comment by PortionLK** [comment]
Are you issuing the command within a screen session? If you exit the session then this issue will not occur.

**Comment by maya-doshi** [comment]
Is there anyway to fix this without installing anything on the remote computer (like a compatibility mode), I need to remote into university computers and cannot install anything onto them.

**Comment by AptRoApt** [comment]
You can fix it by cloning the repo, changing directory and executing this command:
```bash
sudo tic -xe alacritty,alacritty-direct extra/alacritty.info
```
