### ISSUE TITLE
Weird font rendering on macOS

### ISSUE THREAD

**Issue by 097115** [alacritty/alacritty#3903]
### System

OS: macOS 10.11
Version: alacritty 0.4.3 (c723247)

### Screenshots

`use_thin_strokes: true`:

  - font family: "SF Mono" size: 12: https://i.imgur.com/mqFMDW0.png
  - font family: "SF Mono" size: 18: https://i.imgur.com/4driyBe.png
  - font family: "SF Mono" size: 12, alacritty 0.4.2 (f68de37) : https://i.imgur.com/3q9PGi0.png

`use_thin_strokes: false`:
  - font family: "SF Mono" size: 12: https://i.imgur.com/d0vtXWj.png

(Also, tested with a few other fonts, same results.)

**Comment by kchibisov** [comment]
fixed on master.
