### ISSUE TITLE
alacritty did weird things in ssh

### ISSUE THREAD

**Issue by 66RING** [alacritty/alacritty#3905]
### System

OS: Arch linux
Version: alacritty 0.5.0-dev (8a39346b)
Linux/BSD: X11 bspwm

I don't know how to describe it. It did typed `clear`, but it display weird. And log `'alacritty': unknown terminal type.` for `clear` command.

![2020-07-01_11-20](https://user-images.githubusercontent.com/49358576/86199915-f3020480-bb8d-11ea-9df1-d46ba1474683.png)

all this work well on st(simple/suckless terminal)

**Comment by kchibisov** [comment]
it says that terminfo is not installed on a remote server. before connecting, try specifying terminfo that could be on remote or install `alacritty` terminfo on remote server.

`TERM=xterm-256color ssh` could temporary do the trick.

**Comment by lifecycletest** [comment]
I ran into the same issue.  You need to either set the "global" TERM variable with:

  `export TERM='xterm-256color'`

before calling ssh, or preferably insert that command in your server's .bashrc file.
