### ISSUE TITLE
Alacritty doesn't start in PopOS

### ISSUE THREAD

**Issue by gabriel19913** [alacritty/alacritty#3913]
Alacritty was running ok until yesterday. However today it doesn't start.

### System

OS: PopOs 20.04
Version: alacritty 0.4.3

### Logs
Created log file at "/tmp/Alacritty-42579.log"
[2020-07-03 08:35:57.810231526] [INFO] Welcome to Alacritty
[2020-07-03 08:35:57.880949806] [INFO] Configuration loaded from "/home/gabriel/.config/alacritty/alacritty.yml"
Alacritty encountered an unrecoverable error:

	Error creating GL context; Received multiple errors. Errors: `[OsError("eglInitialize failed"), OsError("GL context creation failed")]`

**Comment by kchibisov** [comment]
seems like your system update issue then? I'd assume that you've updated drivers or some other stuff.

**Comment by gabriel19913** [comment]
Well, it looks like it was something like this. Today it is running normally, and I did nothing.
