### ISSUE TITLE
Build error on armv7l, font package.

### ISSUE THREAD

**Issue by fuzebox1** [alacritty/alacritty#3915]
I am trying to compile alacritty master (tried -ligatures and -git) (0.5.0) on my Raspberry pi 4 running Arch arm. The package availiable in the community repo is 0.4.3-1 and will not run with OpenGL driver enabled. (GLSL 3.30 not supported, see currently open issue by someone else).
I tried compiling the latest version of fonts but got the same error. I have an issue on the author of font github as well. But as you are using an old package for alacritty i tought id make one here.
I've tried current master as well as the AUR packages. Obviously they all use the same font package...

See build errors below.

### System

OS: Arch Linux arm/aarch64
Version: master
Linux: X11 DWM and Xfce4

### Logs

Compile time error in included package "font".
src/ft/mod.rs:339:26-38: error E0308: Mismatched types.
Compiler help message: "you can convert an `i64` to `i32` and panic if the converted value wouldn't fit.
rustc --explain E0308

**Comment by kchibisov** [comment]
could you provide more verbose log from master, there's no conversion on line 339 on master at all.

**Comment by fuzebox1** [comment]
I'm sorry, it's line 367!
The Matrix { xx, xy, yx, yy } line.

**Comment by kchibisov** [comment]
I wonder why it was triggered on AArch64, are you sure that is not ARM, btw? In anyway, this is the only error, right? I'll take a look later.

**Comment by fuzebox1** [comment]
It's the only error in the whole build up until font, there are a few packages left though.
The pi4 is armv7l, or what do you mean?

**Comment by kchibisov** [comment]
ah, so it's a 32bit target in the end, not 64bit. otherwise it wouldn't make any sense.

**Comment by kchibisov** [comment]
Could you try #3917.

**Comment by fuzebox1** [comment]
Cloned your fork.
Sorry to say it did'nt work.

```
  Compiling font v0.1.0 (/home/fuze/code/gits/alacritty/font)
error[E0308]: mismatched types
   --> font/src/ft/mod.rs:339:26
    |
339 |                 Matrix { xx, xy, yx, yy }
    |                          ^^ expected `i32`, found `i64`
    |
help: you can convert an `i64` to `i32` and panic if the converted value wouldn't fit
    |
339 |                 Matrix { xx: xx.try_into().unwrap(), xy, yx, yy }
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^


```

**Comment by chrisduerr** [comment]
@fuzebox1 Could you try https://github.com/alacritty/alacritty/pull/3918?

**Comment by kchibisov** [comment]
Are you sure that you've cloned a proper thing? Could you try compiling current latest master.

**Comment by fuzebox1** [comment]
In my haste i may have cloned wrong. I cloned master before you reopened this and fonts/src appears to be working. Doing full compile atm.

```
   Compiling font v0.1.0 (/home/fuze/code/gits/alacritty/font)
    Finished release [optimized + debuginfo] target(s) in 1m 37s
 fuze@archpi  ~/code/gits/alacritty    font                            1.6m  Sat 17:31:54

```
