### ISSUE TITLE
Failed to re-attach to a screen session

### ISSUE THREAD

**Issue by fengwang** [alacritty/alacritty#3924]
### System

OS: Linux
Version:  0.4.3
Linux/BSD: X11

### Problem

1. Login to a remote machine using `ssh`
2. re-attach to a screen session using `screen -r`
3. got error message `'alacritty': unknown terminal type.`
4. got another error message when executing `clear`:  `'alacritty': unknown terminal type.`

P.S.: Other terminals, such as `konsole` and `deepin terminal`, work well with this remote machine with `ssh` login.

**Comment by enizor** [comment]
You need to install alacritty's terminfo on the remote machine as well, or SSH with a similar terminfo `TERM=xterm-256color ssh`
