### ISSUE TITLE
Weird copy behavior when closing terminal

### ISSUE THREAD

**Issue by papey** [alacritty/alacritty#3925]
### System

OS: Linux (ArchLinux)
Version: `alacritty 0.4.3`
Graphic Environment: X11 + AwesomeWM

### Description

When using the copy function (`Ctrl + Shift + c` by default) :

Copy some text from terminal A, paste to terminal B (or any other application) : everything works
Copy some text from terminal A, close terminal A, paste to terminal B (or any other application) : nothing is pasted

Reading the documentation i try something with 

```
# clipboard
selection:
  save_to_clipboard: true
```

Thanks for the awesome software.

**Comment by kchibisov** [comment]
This is how X11 works, when you close an application the selection from that application is lost. Use clipboard managers for that.
