### ISSUE TITLE
No key repetition on hold

### ISSUE THREAD

**Issue by DilsMatchanov** [alacritty/alacritty#3928]
When I press a key and then immediately press and hold another no key repetition happens.

For example in vim when I press `k` and then press and hold `j` no scrolling happens.

### System

OS: macOS
Version: `alacritty 0.4.3 (c723247)`

**Comment by chrisduerr** [comment]
Is this the case outside of vim too? I cannot reproduce.

**Comment by DilsMatchanov** [comment]
@chrisduerr yes outside too, let me find a way show you this. I will try to send a gif

**Comment by DilsMatchanov** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/26854816/86907307-3fb98280-c12e-11ea-9775-3ee72d0e99e6.gif)

@chrisduerr didn't find a way to display the keys that I was pressing but hope you trust my words )

**Comment by chrisduerr** [comment]
Could you provide more information about your install? Which version are you running, what hardware do you have, are you using any third party input tools and what keyboard layout are you using?

**Comment by DilsMatchanov** [comment]
MacBook Pro (13-inch, 2020, Two Thunderbolt 3 ports)
1.4 GHz Quad-Core Intel Core i5
8 GB 2133 MHz LPDDR3
Intel Iris Plus Graphics 645 1536 MB

Using a default english qwerty keyboard layout

Keyboard settings:
![Screen Shot 2020-07-08 at 16 09 42](https://user-images.githubusercontent.com/26854816/86911923-7fd03380-c135-11ea-97ba-0e4e2a4d3855.png)

**Comment by DilsMatchanov** [comment]
No I didn't install any third party input tools

**Comment by DilsMatchanov** [comment]
alacritty 0.4.3 (c723247) installed by `brew cask install alacritty`

**Comment by chrisduerr** [comment]
Has this worked in previous versions of Alacritty and does changing the repetition rate or delay make any difference?

**Comment by DilsMatchanov** [comment]
I didn't try previous versions and no, changing the repetition rate or delay doesn't make any change

**Comment by chrisduerr** [comment]
Could you run Alacritty with `alacritty --print-events`? You should find the executable at Alacritty.app/Contents/MacOS/alacritty.

It would be interesting to see if that outputs anything while holding that key.

**Comment by chrisduerr** [comment]
Also are you letting go of the first key? That might make this a duplicate of #2788.

**Comment by DilsMatchanov** [comment]
oh yeah, sorry I didn't find that before.

duplicate of #2788
