### ISSUE TITLE
Copy & Paste?

### ISSUE THREAD

**Issue by k0nsl** [alacritty/alacritty#3929]
Hi,

I am running Alacritty `0.4.1` on Ubuntu `18.04.4` and I am wondering if there is a way to enable copy & paste functionality, or if this is something which is currently unavailable (e.g, a non-feature).

Thanks in advance.

Faithfully,
-k0nsl

**Comment by kchibisov** [comment]
`Ctrl + Shift + C`/`Ctrl + shift + V` should always work. MIddle mouse paste could be not implemented on your system. Also, are you on `Wayland` or `X11`? Try `env | grep -i xdg_session_type`.

**Comment by k0nsl** [comment]
Thank you, @kchibisov. Your answer does in fact work fine on my system (`X11`); the middle mouse button is working as well. It was just selection with the mouse and then `right click button` which did not work, something I've grown used to.

However, the method you gave in your answer will work just fine for me. 👍

Faithfully,
-k0nsl
