### ISSUE TITLE
Alert user when specified font cannot be found

### ISSUE THREAD

**Issue by KongBorup** [alacritty/alacritty#3942]
When an unknown font is specified, the Alacritty window will not open, and it doesn't create any error boxes. For example, when this is in my `alacritty.yml`:
```yml
font:
  normal:
    family: Fira Code
    style: Regular
  size: 11.0
```
and I don't have Fira Code installed, Alacritty will simply not open. Running Alacritty from the command line with the `-v` flag reveals why:
```
PS C:\Program Files\Alacritty> .\alacritty.exe -v
PS C:\Program Files\Alacritty> Created log file at "C:\Users\private\AppData\Local\Temp\Alacritty-17208.log"
[2020-07-06 12:39:07.895761700] [INFO] Welcome to Alacritty
[2020-07-06 12:39:07.896759300] [INFO] Configuration loaded from "C:\Users\private\AppData\Roaming\alacritty\alacritty.yml"
Alacritty encountered an unrecoverable error:

        Couldn't find a font with name Fira Code and style Regular
        Please check the font config in your alacritty.yml.
```
It works fine once Fira Code is installed, but in the case where you copy over a config file to a new computer (where an uninstalled font is specified in the config), it can be difficult to diagnose why Alacritty doesn't open - I for example didn't know what the issue was until I found out that I could run the executable with the `-v` flag. It's very confusing if nothing happens when Alacritty is run (without flags).

It would be helpful to new users if Alacritty either
 - produced an error window specifying the issue or
 - reverted to the default font and showed the error in the bottom like it does with other errors.

### System
OS: Windows
Version: `alacritty 0.4.3 (c723247)`
Windows: ConPTY

**Comment by chrisduerr** [comment]
> I for example didn't know what the issue was until I found out that I could run the executable with the -v flag.

Are you sure that is the case? Errors are logged regardless of command line flags and as you can see, the unrecoverable error also doesn't have a logging level in front of it, so it wouldn't make sense that it only becomes visible with `-v`.

**Comment by chrisduerr** [comment]
Regardless of logging, we should make our best attempt to at least startup though. So I think it would be a worthwhile change to try again if the default font does not manage to load successfully.

**Comment by chrisduerr** [comment]
Could you check if https://github.com/alacritty/alacritty/pull/3945 fixes this problem for you? It should fallback to the default font and print an error if it could not be loaded.

**Comment by KongBorup** [comment]
Apologies for the late reply. I have built and run #3945, and it seems to work just fine as per the screenshot:
![image](https://user-images.githubusercontent.com/16561050/87208901-6e8f4e80-c310-11ea-9ac6-1389f10cd01d.png)
I think this is a very neat addition that should make the issue much clearer to the user! Thanks for the impressively quick reply and fix. :)
