### ISSUE TITLE
Font Size inconsistency across two displays

### ISSUE THREAD

**Issue by pradyungn** [alacritty/alacritty#3948]
I use Arch Linux on a 14 inch Thinkpad. When working at home, I have the thinkpad connected to an external monitor, a 24 inch display. Both are 1080p. While the font scaling is fine on the external display, whenever I start up alacritty using the laptop as my selected display, the font is humungous. Attached are two pictures with both font sizes side by side. Note that I don't have any DPI settings set.

Dragging the terminal from the external to built in monitor, and vice versa does nothing - it keeps the font size consistent. I'm not sure what the problem's source is - I never had this issue while using Kitty.

![2020-07-10_13-27](https://user-images.githubusercontent.com/19643050/87200436-66ec8d00-c2b1-11ea-9630-2dec75510c2e.png)

**Comment by chrisduerr** [comment]
> Dragging the terminal from the external to built in monitor, and vice versa does nothing - it keeps the font size consistent

What do you mean by that? Does the font get smaller when it is moved and then bigger again when it is moved back?

This really just sounds like DPI scaling, which Kitty just doesn't do by default on X.

**Comment by pradyungn** [comment]
Never mind i figured it out - ended up using the WINIT_X11 option.
