### ISSUE TITLE
Kali

### ISSUE THREAD

**Issue by avelli-mark** [alacritty/alacritty#3950]
Hi All, Just joined and am very new at this. I have been trying to install Alacritty on Kali linux but have had no luck at all. If i could get a little help that would be great.
Thanks all.

**Comment by kchibisov** [comment]
IIRC Kali is debian based, so follow instructions in `INSTALL.md` and likely the ones for debian could help you to install proper packages https://github.com/alacritty/alacritty/blob/master/INSTALL.md#debianubuntu .
