### ISSUE TITLE
cannot use normally with ssh: syntax highlight disabled, cannot use screen, vim launched with error

### ISSUE THREAD

**Issue by shrubbroom** [alacritty/alacritty#3956]
### System

OS: Arch Linux
Version: 0.4.3
Linux: X11 + Xfce4 + i3wm + picom

### Logs

Crashes: not crashed

When the ssh is used inside alacritty(ssh to a remote host), the syntax hightlight is disabled in the remote host. When the vim is launched in remote host, the following warning is reported
```
E558: Terminal entry not found in terminfo
'alacritty' not known. Available builtin terminals are:
    builtin_gui
    builtin_amiga
    builtin_beos-ansi
    builtin_ansi
    builtin_pcansi
    builtin_win32
    builtin_vt320
    builtin_vt52
    builtin_xterm
    builtin_iris-ansi
    builtin_debug
    builtin_dumb
defaulting to 'ansi'
```

screen cannot be entered normally,
```
There is no screen to be resumed matching my-screen-session
```

Tab compltion for commands also cannot be invoked.

**Comment by chrisduerr** [comment]
> E558: Terminal entry not found in terminfo

You need to install Alacritty's terminfo.

**Comment by jeremies** [comment]
But if you are not in the sudo group of the ssh machine you connect to, you cannot fix error E558: Terminal entry not found in terminfo. I think that this should be fixed without touching the remote machine.

![image](https://github.com/user-attachments/assets/aa116b2e-d52b-4729-953b-b92c6da6d3d2)
