### ISSUE TITLE
HiDPI/LoDPI offset parity broken after upgrading 0.4.2 -> 0.4.3

### ISSUE THREAD

**Issue by abdl-dev** [alacritty/alacritty#3958]
OS: Linux, X11
Version: 0.4.3

I have a mirrored config for my two machines. One is 1920×1080 and the other is 3840 × 2160 (rendered at 200% scaling). 
Before, on Alacritty 0.4.2, I had
```
font:
   offset:
      x: 0
      y: -3
```
in my config and **it would produce 87 rows and 271 columns (full-screen) on BOTH machines**—_exactly the same_. 

However, in Alacritty 0.4.3, this behavior is broken, and the same config renders differently on the HiDPI machine. Now, in 0.4.3, to achieve 87 rows and 271 columns on my HiDPI machine, I need a separate config:
```
font:
   offset:
      x: -1
      y: -5
```

For some reason, both the vertical _and_ horizontal rendering is different now and no longer match across different (integer-multiplier) resolutions. Thus, LoDPI/HiDPI rendering parity is now broken and now you need two separate configs to have them look identical.

**Comment by chrisduerr** [comment]
Are you saying the space between glyphs has changed and not the fontsize? That seems unlikely to me.

**Comment by abdl-dev** [comment]
> Are you saying the space between glyphs has changed and not the fontsize? That seems unlikely to me.

Yes, exactly. I've tested this through and it definitely the spacing and not the font size. As unlikely as it seems, the two screens look identical if I use two different offset configs. Furthermore, I can use the SAME config if I force my HiDPI machine to render at 1920x1080—producing the same number of rows and columns.

**Comment by chrisduerr** [comment]
> As unlikely as it seems, the two screens look identical if I use two different offset configs.

Could you share a screenshot of that?

Also could you share the Alacritty configuration you're currently using?

If the font offsets have changed, the change in monitors shouldn't be relevant though, right? You should be able to reproduce different rendering by just opening a 0.4.2 right next to a 0.4.3 Alacritty?

**Comment by abdl-dev** [comment]
Yes, I can provide clear screenshots and my config file later this evening, when I am back at home. 

> If the font offsets have changed, the change in monitors shouldn't be relevant though, right? You should be able to reproduce different rendering by just opening a 0.4.2 right next to a 0.4.3 Alacritty?

I am not sure what you mean. The issue with the font offsets seem to be a newly introduced HiDPI issue, so the choice of resolution (and thus change in monitor) would definitely matter, no? 

To clarify, on my 1920x1080 machine, my old config functions perfectly and appears the same on 0.4.3 as it did on 0.4.2. However, on my 3840x2160 machine, my old config displays differently on 0.4.3 than it did on 0.4.2. 

And yes, if I test 0.4.2 alongside 0.4.3 on the same HiDPI machine with the same config, they produce different rendering! 

I originally tested this via a Live USB of the same release, but if you would like me to test/sandbox the two Alacritty versions in a different way, I would be happy to look into that as well.

**Comment by abdl-dev** [comment]
Sorry, I didn't get a chance to collect screenshots until today. I tried to mirror the setups exactly so the screenshots are easy to compare. Let me know if you need anything else. 

- All screenshots are on Alacritty 0.4.3
- The terminal dimensions are shown in the TOP RIGHT 
- Both machines are running Ubuntu 20.04 with latest updates
- Both machines have NVIDIA 440.100 drivers installed
- LoDPI 1920x1080 screenshots are with 100% scaling (via gnome 3.36 display settings)
- HiDPI 3840x2160 screenshots are with 200% scaling (via gnome 3.36 display settings)

This is the `font.offset.x: 0` `font.offset.y: -3` config on 1920x1080:
![old-config-lodpi](https://user-images.githubusercontent.com/1343016/87602452-013f3d00-c6c5-11ea-9caf-6a245335ce39.png)

This is the `font.offset.x: 0` `font.offset.y: -3` config on 3840x2160: 
![old-config-hidpi](https://user-images.githubusercontent.com/1343016/87602451-013f3d00-c6c5-11ea-948d-32a00722622b.png)

This is the `font.offset.x: -1` `font.offset.y: -5` config on 1920x1080:
![new-config-lodpi](https://user-images.githubusercontent.com/1343016/87602450-00a6a680-c6c5-11ea-98c3-2cc6b041b57b.png)

This is the `font.offset.x: -1` `font.offset.y: -5` config on 3840x2160: 
![new-config-hidpi](https://user-images.githubusercontent.com/1343016/87602449-00a6a680-c6c5-11ea-92d4-8005a0b6d0b4.png)

As you can see, on Alacritty 0.4.3, `font.offset.x: 0` `font.offset.y: -3` on 1920x1080 is exactly equivalent to `font.offset.x: -1` `font.offset.y: -5` on 3840x2160. The same config no longer has functional parity between LoDPI/HiDPI.

**Comment by chrisduerr** [comment]
What's the output of `alacritty -v` on the different machines with the different Alacritty versions? Mainly the `Device pixel ratio` line.

**Comment by abdl-dev** [comment]
I maximize the window after it launches, I don't have it set to launch full screen. 
Both machines are using `font.offset.x: 0` `font.offset.y: -3` for this test.

On 1920x1080 machine:
```
Created log file at "/tmp/Alacritty-17478.log"
[2020-07-15 19:14:51.321105799] [INFO] Welcome to Alacritty
[2020-07-15 19:14:51.321301067] [INFO] Configuration loaded from "/home/abdl-dev/.config/alacritty/alacritty.yml"
[2020-07-15 19:14:51.405364781] [INFO] Device pixel ratio: 1
[2020-07-15 19:14:51.406354754] [INFO] Initializing glyph cache...
[2020-07-15 19:14:51.420012391] [INFO] ... finished initializing glyph cache in 0.013633394s
[2020-07-15 19:14:51.433547078] [INFO] Estimated DPR correctly, skipping resize
[2020-07-15 19:14:51.433579695] [INFO] Cell Size: 7 x 12
[2020-07-15 19:14:51.433589624] [INFO] Padding: 10 x 10
[2020-07-15 19:14:51.433605370] [INFO] Width: 860, Height: 500
[2020-07-15 19:14:51.449801121] [INFO] PTY Dimensions: Line(40) x Column(120)
[2020-07-15 19:14:51.452822979] [INFO] Initialisation complete
[2020-07-15 19:14:51.550608112] [INFO] Width: 860, Height: 500
[2020-07-15 19:14:55.119913092] [INFO] Width: 1920, Height: 1080
```
On 3840x2160 machine:
```
Created log file at "/tmp/Alacritty-3534.log"
[2020-07-15 19:16:45.132975394] [INFO] Welcome to Alacritty
[2020-07-15 19:16:45.133074221] [INFO] Configuration loaded from "/home/abdl-dev/.config/alacritty/alacritty.yml"
[2020-07-15 19:16:45.271984620] [INFO] Device pixel ratio: 2
[2020-07-15 19:16:45.314198654] [INFO] Initializing glyph cache...
[2020-07-15 19:16:45.326572914] [INFO] ... finished initializing glyph cache in 0.01234429s
[2020-07-15 19:16:45.326700720] [INFO] Estimated DPR correctly, skipping resize
[2020-07-15 19:16:45.326716629] [INFO] Cell Size: 15 x 26
[2020-07-15 19:16:45.326722992] [INFO] Padding: 20 x 20
[2020-07-15 19:16:45.326732609] [INFO] Width: 1840, Height: 1080
[2020-07-15 19:16:45.327590583] [INFO] PTY Dimensions: Line(40) x Column(120)
[2020-07-15 19:16:45.330902738] [INFO] Initialisation complete
[2020-07-15 19:16:45.331409217] [INFO] Width: 1840, Height: 1080
[2020-07-15 19:16:49.206023422] [INFO] Width: 3840, Height: 2160
```

**Comment by chrisduerr** [comment]
The font offset isn't scaled by DPI, while  your DPI is different on the different monitors. That might be the problem?

Though I don't see how that would be any different on previous versions of Alacritty, unless the `Device pixel ratio` output is different?

**Comment by abdl-dev** [comment]
No, the `device pixel ratio` is the same on Alacritty 0.4.2 as well. Oh, well. Thank you for taking the time to look into it!

I'll just maintain two different configs now. Since you maintain the project, I am wondering, is there anyway to do conditional blocks inside the `alacritty.yml` so that it uses a a different offset based on the `hostname`?

**Comment by chrisduerr** [comment]
> is there anyway to do conditional blocks inside the alacritty.yml so that it uses a a different offset based on the hostname?

No, I recommend using git branches for that. That's why I do with macOS/Linux and it works like a charm.

> No, the device pixel ratio is the same on Alacritty 0.4.2 as well.

That strikes me as very odd, but it's not something I can reproduce, which makes troubleshooting this difficult unfortunately.

In the following screenshot you can see a comparison of running with a DPI of 10 and a font size of 1 versus running a DPI of 1 and a font size of 10. In both cases the X and Y glyph offset are 10:

![tmp](https://user-images.githubusercontent.com/8886672/87674969-4a939900-c766-11ea-9987-80bf95b27e6d.png)

As you can see in the top two terminals, the padding is scaled by a factor of 10x both for version 0.4.2 and version 0.4.3, however the glyph offset is 10 regardless of the DPI. This behavior is identical for 0.4.2 and 0.4.3, thus I cannot see how a change in either version would result in a different offset.

The configuration file for the DPR 10 is the following:

```
window:
  dynamic_padding: true
  padding:
    x: 3
    y: 3

font:
  offset:
    x: 10
    y: 10
  size: 1.0
```

While the configuration file for running with a DPR of 1 is this:

```
window:
  dynamic_padding: true
  padding:
    x: 3
    y: 3

font:
  offset:
    x: 10
    y: 10
  size: 10.0
```

Feel free to perform this test yourself, but I cannot reproduce what you're describing.

**Comment by kchibisov** [comment]
I'll just add that nothing in alacritty was chagned in font handling from `v0.4.2` to `v0.4.3` on Linux/BSD. Just purely nothing.

You can also bisect the commit that broke things for you on https://github.com/alacritty/alacritty/tree/v0.4.3 branch, since the amount of changes between `v0.4.2` and `v0.4.3` is very low, and those were purely bugfixes.
