### ISSUE TITLE
'alacritty': unknown terminal type

### ISSUE THREAD

**Issue by zrsharp** [alacritty/alacritty#3962]
### System

OS: Arch Linux, Debian
Version: 0.4.3
X11,

### Problem
'alacritty': unknown terminal type.
When I  use ssh to connect the remote host(Debian) and exec 'clear', there is an error:  '"'alacritty': unknown terminal type.".
Then I copied the terminfo to the remote host,  but this still doesn't work.

**Comment by chrisduerr** [comment]
You need to install the `alacritty` terminfo on your remote machine.

**Comment by JaafarMehrez** [comment]
you can start a Tmux session then connect to your remote machine

**Comment by surister** [comment]
Run 
`curl -sSL https://raw.githubusercontent.com/alacritty/alacritty/master/extra/alacritty.info | tic -x -`
In the host machine (The one you connected through ssh)

**Comment by YanzhaoW** [comment]
> Run `curl -sSL https://raw.githubusercontent.com/alacritty/alacritty/master/extra/alacritty.info | tic -x -` In the host machine (The one you connected through ssh)

now the colors of all the files and folders turn into white. How can I undo what you suggest?

**Comment by maxboone** [comment]
You can also, as a workaround:
`alias ssh='TERM=xterm-256color ssh'`

**Comment by cyqsimon** [comment]
It's rather odd that on some OSes the symptoms of missing terminfo are much worse than on others.
On my CentOS 7 box it's merely the colors that are missing; on my RHEL 8 box not even backspace works properly.

The oneliner from @surister fixes the issue properly. Thank you.

**Comment by sporqist** [comment]
@maxboone 's answer helped me.

My fish shell complained at first, telling me this:
```
- (line 1): The function “ssh” calls itself immediately, which would result in an infinite loop.
function ssh  --description 'alias ssh=TERM=xterm-256color ssh';  TERM=xterm-256color ssh $argv; end
                                                                                      ^
in function 'ssh' with arguments 'my-server'
```

I resolved this by getting the actual path of ssh and executing that:
```bash
alias ssh="TERM=xterm-256color $(which ssh)"
```

**Comment by GrantBirki** [comment]
```bash
alias ssh="TERM=xterm-256color $(which ssh)"
```

Worked perfectly, thanks! :star:

**Comment by AnkushMalaker** [comment]
Can someone explain why this happens and if an actual solution is found? Seems like this issue was prematurely closed as the fixes offered in above thread are workarounds instead of actual solutions. Or perhaps point me towards where I can find the solution if it was fixed elsewhere. 
The solution offered by @surister works occasionally and doesn't seem to persist on my machine after closing terminal.
CC @chrisduerr

**Comment by maxboone** [comment]
> Can someone explain why this happens and if an actual solution is found? Seems like this issue was prematurely closed as the fixes offered in above thread are workarounds instead of actual solutions. Or perhaps point me towards where I can find the solution if it was fixed elsewhere. The solution offered by @surister works occasionally and doesn't seem to persist on my machine after closing terminal. CC @chrisduerr

There's not much to explain to why this isn't solved. It's not a bug, the alacritty terminal identifies itself as alacritty and rightfully so.

So systems that don't know it will tell you that the terminal is unknown. You can either (1) override the identification of the terminal with a more widely installed terminfo like xterm or (2) install the terminfo on the machine.

It's more a packaging request than a "bug".

**Comment by JMans15** [comment]
If you want to set TERM only for one host you can add `SetEnv TERM=xterm-256color` under said host in ~/.ssh/config
I like this solution because it doesn't affect anything else than what we want it to

**Comment by robbie-cahill** [comment]
I just put this in my `.zshrc` (use `.bashrc` for bash) file
```
export TERM=xterm-256color
```

works for me

**Comment by NiceGuyIT** [comment]
I was getting this when using `sudo` on openSUSE because `/etc/profile` was using `tset`. Every sudo command generated an error `tset: unknown terminal type alacritty` and prompted for the terminal type. Apparently the `tset` flavor on openSUSE does not look in `$HOME/.terminfo/`. I had to install the `alacritty` TERMINFO to `/usr/share/terminfo`.

**Comment by bmihelac** [comment]
> If you want to set TERM only for one host you can add `SetEnv TERM=xterm-256color` under said host in ~/.ssh/config I like this solution because it doesn't affect anything else than what we want it to

To set TERM for all hosts add following lines in `~/.ssh/config `:

```
Host *
SetEnv TERM=xterm-256color
```

**Comment by AtharvShirgurkar** [comment]
Installing ncurses-term on debian solves the problem permanently.
