### ISSUE TITLE
G Sync Support

### ISSUE THREAD

**Issue by brian6932** [alacritty/alacritty#3963]
### System

OS: Windows
Version:  0.4.3 (c723247)
Windows: ConPTY

G Sync support, proper G Sync support would be nice, at the moment when using G Sync the window lags quite a bit, this is not too uncommon with some hw accelerated programs

**Comment by chrisduerr** [comment]
What benefit would Alacritty gain from supporting GSync? And what kind of lag are you experiencing?

**Comment by brian6932** [comment]
I mean it would just be easier for people to not have to go into their control panel and turn it off, there are some hw accelerated programs that stutter when G Sync is enabled it's a very common issue

**Comment by chrisduerr** [comment]
How is it stuttering? And that seems like a GSync problem.

**Comment by brian6932** [comment]
It's a very common issue with program incompatibility with G Sync it's a little hard to describe, but the frame rates don't sync up and result in a laggy unresponsive experience, an example of a program that has this issue would be Handbrake

**Comment by chrisduerr** [comment]
If GSync creates problems with applications, that kinda sounds like GSync's fault.

There are some plans to revise vblank synchronization a bit, you can check out #3972 as the tracking issue for that. It is possible that this would help with the problem, but I wouldn't put too much hope into it.

Besides that, I don't think there's any interest in doing anything GSync specific. If using it causes troubles with applications that don't explicitly support it, you probably shouldn't have it enabled except for applications that explicitly support it.

**Comment by NotAFile** [comment]
VRR tech only works if you are rendering at a lower framerate than what your monitor outputs. With alacritty hitting 1000+ fps on my shitty iGPU laptop, VRR will probably never make sense for alacritty.

**Comment by jackinloadup** [comment]
Would supporting VRR help save energy and/or reduce latency?
