### ISSUE TITLE
OSC52 doesnt work properly in a mosh session

### ISSUE THREAD

**Issue by RonanMacF** [alacritty/alacritty#3964]
### System

OS: Linux/Fedora 18
Version: alacritty 0.4.3 (c723247)

### Description
I have done all the following using no config file `alacritty --config-file /dev/null`. Using the test command `printf "\033]52;c;$(printf "%s" "test" | base64)\a"` I tried to see if `test` was replacing my keyboard contents. This works on my local machine and through SSH to the same host, it only fails when using mosh.

**Comment by chrisduerr** [comment]
Because mosh probably filters it out as a security measure. This is not an Alacritty problem and is probably considered a feature in mosh.
