### ISSUE TITLE
Terrible slow using X11 with Docker Desktop

### ISSUE THREAD

**Issue by mkrusemark** [alacritty/alacritty#3965]
It's a little bit a special setup:
Running Alacritty in i3 inside a docker image from docker Desktop.
Output is terrible slow and really unusable :-(

I love it and want to use it on my Windows laptop as well.

### System

OS: WSL/Linux
Version: 0.5.0-dev
Linux/BSD: X11 running with Cygwin

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: 1000x1615
Keyboard and bindings: `alacritty --print-events`

**Comment by chrisduerr** [comment]
>  Running Alacritty in i3 inside a docker image from docker Desktop.

Why would you do this? It seems like that's just asking for terrible performance.

**Comment by ideologysec** [comment]
there's so many better ways to do this. Even experimental GUI support in WSL2, for heckin sakes.

**Comment by chrisduerr** [comment]
Closing since there hasn't been any response in a while. A significant performance hit is what I would expect when running stuff in environments that weren't built for doing what you're doing.
