### ISSUE TITLE
alacritty -e zsh -c doesn't  source .zshrc

### ISSUE THREAD

**Issue by Zeioth** [alacritty/alacritty#3969]
The next command doesn't enable the env vars I have in my .zshrc

    alacritty -e zsh -c vim

If I manually source the file it works fine

    source ~/.zshrc
    vim

Also If I run 

    alacritty -e zsh -c "source ~/.zshrc && vim"

It works well
    

### System

OS: Linux
Version: 0.4.3
Linux/BSD: X11/Wayland, I3WM

**Comment by chrisduerr** [comment]
I think this is intended behavior of `zsh -c`. Either way, it's not an Alacritty issue since we have nothing to do with zsh sourcing its rc files.

**Comment by renxzen** [comment]
If anyone has with this problem, you can force the shell to be interactive and source `~/.zshrc` with the `-i` param. eg.:

`alacritty -e zsh -ic vim`

more info [here](https://zsh.sourceforge.io/Doc/Release/Invocation.html#Invocation)
