### ISSUE TITLE
"No space left on device"

### ISSUE THREAD

**Issue by alexyuriev** [alacritty/alacritty#3978]
Getting a notification message code 28, no space left on device. Space is available, processes with the same uid/gid are successfully creating/writing files on every file system accessible to alacritty.

### System

OS: Linux, Debian 10, kernel 5.5.0
Version: 0.4.1

### Logs

$ RUST_BACKTRACE=1 alacritty 
thread 'config watcher' panicked at 'watch alacritty.yml dir: Io(Os { code: 28, kind: Other, message: "No space left on device" })', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  15: core::result::Result<T,E>::expect
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/result.rs:960
  16: alacritty::config::monitor::Monitor::new::{{closure}}
             at alacritty/src/config/monitor.rs:36
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by chrisduerr** [comment]
>  Version: 0.4.1

Could you please try the latest available stable version, or even better the master branch?

I'd assume that your `/tmp` might be full if nothing else is running into space limits. That usually has a separate limit that can be quite restrictive.

**Comment by alexyuriev** [comment]
/tmp is fine:

$ echo "going to do a test " > /tmp/testfile; alacritty &
[1] 6567
thread 'config watcher' panicked at 'watch alacritty.yml dir: Io(Os { code: 28, kind: Other, message: "No space left on device" })', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

 Wed 15 Jul 2020 04:45:28 PM EDT  alex@wrks-2 
 ~ 
$ ls -l /tmp/testfile 
-rw-r--r-- 1 alex alex 20 Jul 15 16:45 /tmp/testfile

 Wed 15 Jul 2020 04:45:39 PM EDT  alex@wrks-2 
 ~ 
$ 

Going to try a master shortly.

**Comment by chrisduerr** [comment]
`echo` certainly isn't the correct way to test free disk space. You should check with `df -h`.

**Comment by alexyuriev** [comment]
echo is certainly a correct way to test if a process can create a new file. That's a basic unix shell redirect.

/tmp has 2.7GB free and I have created 8000 files in it.

**Comment by kchibisov** [comment]
I'd recommend to try running under `strace` and see where it breaks.

**Comment by alexyuriev** [comment]
@kchibisov Any thoughts on what I might be looking for? I'm not seeing any obvious calls that returned error no 28.

**Comment by kchibisov** [comment]
You can post it here, also try `alacritty --no-live-config-reload`.
