### ISSUE TITLE
Add better visual feedback for active Vi mode

### ISSUE THREAD

**Issue by chrisduerr** [alacritty/alacritty#3984]
Currently the active Vi mode is very hard to identify, since the vi mode cursor are the only changes the user can make to identify it.

Users that do not want to change the cursor, should still have a clear and distinctive way to identify that the vi mode is active, to prevent accidentally getting trapped and confused by entering a mode without having the ability to identify it.

**Comment by KongBorup** [comment]
I think it would be optimal to do it in a way that doesn't obstruct the terminal in any way - e.g. leave it out of the terminal content area.

An easy solution could be to update the window title as such:

![image](https://user-images.githubusercontent.com/16561050/87850582-a0e11300-c8f1-11ea-85e9-c62a7c2a61b7.png)

Another way could be to imitate the style of errors and display the info in the bottom, but I don't think this is a good idea as it reduces the size of the usable terminal.

![image](https://user-images.githubusercontent.com/16561050/87850663-47c5af00-c8f2-11ea-8f12-a46d761f81e5.png)

**Comment by kchibisov** [comment]
The thing is that title bar isn't presented on all platforms and not presented in fullscreen, so it's not really a solution.

**Comment by KongBorup** [comment]
I just realised that too - besides cross-platform compatability, many people also disable window decorations altogether, which would hide that message.

Maybe it would better to take inspiration from Vi itself and show a line in the bottom of the terminal where `-- INSERT --` is usually shown. This could also be used for the new search functionality's I/O like in standard Vi.

**Comment by chrisduerr** [comment]
I've got a few proposals that might be viable solutions, if you have any preferences please let me know @kchibisov / @nixpulvis : 
 - 1px colored border around the terminal, obstructing content if there is no padding available/configured
 - Short, text-based overlay; to prevent obstruction it should move from right/left or top/bottom when the vi cursor is moved to its location
 - Bar with text indicator, shrinking the terminal height permanently; in theory this would allow starting search without having to resize in vi mode
 - Alternative background color

**Comment by kchibisov** [comment]
>Short, text-based overlay; to prevent obstruction it should move from right/left or top/bottom when the vi cursor is moved to its location

I do like that approach more, since you can have some sort of scrollback position information in it. In general, such overlay should be timer based and appear only under certain circumstances.

>1px colored border around the terminal, obstructing content if there is no padding available/configured

Not sure that I like it, and 1px isn't something that noticeable on high density or poor quality panels. Even if you make it larger, I don't like the esthetics of that approach.

>Alternative background color

Nah, I'm not sure that it'll work in alt-screen with truecolored applications, since they just render random colors over background. So you should just write your random color for all visible background cells, which sounds not fun.

>Bar with text indicator, shrinking the terminal height permanently; in theory this would allow starting search without having to resize in vi mode

Not entirely bad, but not that I really like it either. Especially knowing that we have infra infrastructure to do that in place.

So, it'll either be a timer based overlay that hides/shows under certain heuristics or stays permanently, but jumps around, or permanent search bar at the bottom. We already have all the code in place to just use both solution though, so it's just a matter of preference.

I do prefer overlay a bit more, since you can always hide it without shifting things around.

**Comment by chrisduerr** [comment]
> In general, such overlay should be timer based

Having an overlay go away after a certain amount of time would completely defeat the purpose of using it as a better visual feedback for vi mode.

**Comment by kchibisov** [comment]
>Having an overlay go away after a certain amount of time would completely defeat the purpose of using it as a better visual feedback for vi mode.

I mean the opposite, that it'll show after certain amount of time or under certain action, like focus loss, etc. I do think that if you've entered and started actively moving you can likely hide it, though you should show it for a bit just after enter into Vi mode. On the other side I do feel like it'll just be extra complex without much benefit compared to overlay that moves around.

**Comment by chrisduerr** [comment]
> I do feel like it'll just be extra complex without much benefit compared to overlay that moves around.

Yeah, it makes some sense that it wouldn't be needed when moving around, but just moving it around/hiding it based on location is probably easier. That said, with our current schedulers neither would be very difficult I think.

**Comment by nixpulvis** [comment]
> Bar with text indicator, shrinking the terminal height permanently; in theory this would allow starting search without having to resize in vi mode

I think something like this was what I was thinking back when Vi mode was first being designed. Now that we have search mode as well, we could reuse that part of the screen. It's currently on the bottom (where you'd generally expect it), which is fine, but does require scrolling text. If we put the status on the top, the text could remain in place. Just a thought, since I think I'm in favor of it's current position.

**Comment by chrisduerr** [comment]
> If we put the status on the top, the text could remain in place

That is not correct. Text will have to be moved around either way.

**Comment by bluz71** [comment]
Hello Alacritty team,

I am a new Alacritty user, but a very long-time terminal and Vim user (actually Neovim nowadays). So take my opinion with a grain of salt ;)

The current ability to configure the cursor in Vi mode is a good interim solution. However, this issue will definitely improve usability. So I do welcome this enhancement.

These four choice were provided by @chrisduerr:

> * 1px colored border around the terminal, obstructing content if there is no padding available/configured

I do not favour this aesthetically; whilst I also note that some Linux window managers highlight the border of the active window. So on some systems it may look unpleasant to have the border highlighted by the window manager **and** have Alacritty highlight the inner border whilst in Vi mode.

> * Short, text-based overlay; to prevent obstruction it should move from right/left or top/bottom when the vi cursor is moved to its location

**Yes**, I like this a lot. tmux uses such a scheme (top-left corner) when one is in copy-mode. And, too an extent Vim also does something similar in the command area when in `--insert--`.

> * Bar with text indicator, shrinking the terminal height permanently; in theory this would allow starting search without having to resize in vi mode

This loses quite a bit of screen real-estate for an information indicator. Not in favour of this.

> * Alternative background color

Like the above bar option, this one also seems too heavy handed.

Short text overlay is my strong preference. Ideally, for me, I'd like it in a fixed location, not auto-placed and potentially hard to find. Lower right corner, one line up would be my ideal (taking into account Zsh users with right-hand side prompts).

My 2cents, best regards.

**Comment by nixpulvis** [comment]
`tmux` already has a status bar and uses the overlay as a faux-scroll indicator. I'm not a huge fan of it, but it makes sense. This is my `tmux` in scroll mode for example.
![screenshot-2020-07-29T15:10:47Z](https://user-images.githubusercontent.com/715947/88818297-8b3ed980-d18c-11ea-831b-187fe7b0c2a8.png)

Here's how things are now:

1. I enter vi-mode with the default <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Space</kbd>
![screenshot-2020-07-29T15:12:06Z](https://user-images.githubusercontent.com/715947/88818559-d6f18300-d18c-11ea-92b6-67c0f31b61a7.png)
2. I enter search with <kbd>/</kbd>
![screenshot-2020-07-29T15:12:19Z](https://user-images.githubusercontent.com/715947/88818621-e670cc00-d18c-11ea-9858-2cafd19e23bd.png)
3. I exit search with either <kbd>Enter</kbd> to keep the selection, or <kbd>Esc</kbd> to clear the selection
![screenshot-2020-07-29T15:17:47Z](https://user-images.githubusercontent.com/715947/88818827-2637b380-d18d-11ea-81e7-2bf9b4470752.png
4. I exit vi-mode with <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Space</kbd> once again (sadly I still haven't been able to convince people that <kbd>Esc</kbd> should return you to the default mode)

Meanwhile `vim` always consumes a full row for this, even in insert mode.

1. "Normal" mode
![screenshot-2020-07-29T15:19:57Z](https://user-images.githubusercontent.com/715947/88819118-8e869500-d18d-11ea-90e1-4cc4cddc80f4.png)
2. Insert mode
![screenshot-2020-07-29T15:20:09Z](https://user-images.githubusercontent.com/715947/88819144-95ada300-d18d-11ea-97bb-3b4a70d6aed6.png)
3. Searching
![screenshot-2020-07-29T15:20:17Z](https://user-images.githubusercontent.com/715947/88819150-9b0aed80-d18d-11ea-8340-332d41a457e6.png)

I propose we follow `vim` here, but obviously don't leave the bar up when we're in our "normal" mode a.k.a. not in vi-mode. This way we A) don't have to deal with overlapping indication text with terminal data, B) we have a unified place for search and vi-mode status, and C) opens the door for future vi-mode functionality down the road.

**Comment by chrisduerr** [comment]
> NOTE: a small bug may be that the cursor doesn't shift back down with the text here

That's because you're in the alt screen. Without tmux it should work just fine. ;)

> I exit vi-mode with Ctrl + Shift + Space once again (sadly I still haven't been able to convince people that Esc should return you to the default mode)

If it's just about brevity, I'd recommend <kbd>i</kbd>?

> Meanwhile vim always consumes a full row for this, even in insert mode.

Yes, but that's highly undesirable for a terminal emulator (even though technically there have been terminals in the past, see the 'statusline' capability).

> I propose we follow vim here, but obviously don't leave the bar up when we're in our "normal" (a.k.a. not vi) mode.

I find this difference significant enough to question the entire suggestion. If we do not *always* do the same thing as vi mode, I'm not sure if we're "follow vim" by doing it in this case. If there are places where you hide your bar, you probably have good reason to strive to hide it as much as possible in general.

> opens the door for future vi-mode functionality down the road.

I'd be curious what you have in mind here.

**Comment by nixpulvis** [comment]
> I find this difference significant enough to question the entire suggestion. If we do not always do the same thing as vi mode, I'm not sure if we're "follow vim" by doing it in this case. If there are places where you hide your bar, you probably have good reason to strive to hide it as much as possible in general.

Well it's `ViMode`, so when you're in vi-mode, you have an Ex bar, like vi. Otherwise you're in "alacritty-mode" (the normal mode) which is a terminal window as you're already familiar. That's how I figure anyway.

-----

> I'd be curious what you have in mind here.

Let's see... today we have:

- Indication of Vi Mode itself
- Search

Then we could have:

- A scroll indicator, much like the percentage you can see in the screenshots above of my `vim` configuration. In fact, this would be useful outside of vi-mode too.

- Commands like `:-<n>` to jump back some number of lines.

- Search could be extended allow for search in region, like vi. Meaning I could make a visual selection of a portion of the buffer, and search inside it.

- A `!` command which calls a command with the selection as an optional argument. I'm not sure how this would work exactly.... but it may be possible. A madman could even imagine not running a shell at all, but this is clearly not something most people want, and we shouldn't go out of our way necessarily to try and make this possible.

- Clipboards could be wired up to native registers like vim, which could allow for better integrations with applications that make use of the multiple clipboards. Having registers in general would be like having many clipboards internally to use.

- Multiple buffers, and buffer switching within a single alacritty instance. This might be an interesting first take on multi-window/tab support which has been a much desired, and somewhat unfortunate issue (platforms are all very different in this regard).

- Bookmarks and highlighting would be fun, but almost certainly not features we want.

These are mostly pie in the sky ideas, but generally speaking, I feel like a `ViMode` would serve well to have an Ex bar to interact with.

**Comment by chrisduerr** [comment]
> A scroll indicator

I see no reason why this would only be available in vi mode if we have one. Always adding a bar is an absolute no-go.

> Commands like :-<n>

I do not expect vi commands and multi-stroke vi bindings to ever be a thing.

> Search could be extended allow for search in region, like vi.

Regardless of the viability of this feature, it is unrelated to the bar.

> A ! command which calls a command with the selection as an optional argument.

I do not expect our vi mode to ever support commands like this.

> Clipboards could be wired up to native registers like vim, which could allow for better integrations with applications that make use of the multiple clipboards.

Native registers would definitely be too complex for Alacritty. We do not manage clipboard data we just store and retrieve it. Though accessing primary selection would be an option. But if that was possible, you'd want it as a separate binding, so people can rebind it, not implement it as fixed functionality with a command bar.

> Multiple buffers, and buffer switching within a single alacritty instance. This might be an interesting first take on multi-window/tab support which has been a much desired, and somewhat unfortunate issue (platforms are all very different in this regard).

I have zero interest in supporting multiple tabs in Alacritty.

> These are mostly pie in the sky ideas, but generally speaking

I'd like to note that I'm aware you weren't suggesting any of these as concrete ideas of what should be implemented. My goal is just to point out that none of these features are likely to require an additional bar in the vi mode anytime soon. Since we should design our UX around our current features, I don't think those are a great argument because of that.

As far as I'm concerned, adding a bar that is always visible in vi mode will serve no purpose other than indicating that vi mode is active. And I find it **really** tough to argue for the presence of a bar that takes up an entire terminal column, shifting around all the content whenever it is brought up, when there's absolutely no value in the content it provides other than being a visual indicator.

**Comment by bluz71** [comment]
A Vim like status bar would necessitate moving the existing terminal content up (or down) a line. I would find such movements unattractive.

After playing with Vi mode I think setting a hard Vi mode cursor color that is very different to the normal cursor color achieves a good level of alerting. In my case, a dark theme user, my normal cursor is light gray and for Vi mode I use a middle blue cursor. The more distinct the better I find. Works very well.

Status lines, bars, window outlines or changing the background seem obnoxious (for me). An elegant tmux style short overlay maybe with scroll counters (or not) would be ideal; but I already said that before.

I do realise the style choices are highly personal. I suggest the Alacritty team do as tmux has done, make a choice and that's it.

After playing with Vi mode I can confirm that I can now never go back to GNOME Terminal or iTerm2. What an excellent addition Vi mode is. Great work Alacritty team.

**Comment by nixpulvis** [comment]
I suppose an overlay in a mode where scrolling is very natural is not the worst thing in the world. I personally still like the bar, but I wouldn't be upset with an overlay either. I was mostly going off the fact we have a search bar as part of vi-mode already, and keeping like things together is a good idea IMO.

> A Vim like status bar would necessitate moving the existing terminal content up (or down) a line. I would find such movements unattractive.

Not to harp too much on this one point but, I still feel like it's perfectly possible (although I'm not really advocating for this) to put the bar at the top line of the terminal, and push what was there up into history. This would not cause *all* existing content to move, just the one replaced line.

-----

So the question is, if we go with an overlay, what exactly do we put in the overlay? Making it look exactly like tmux would be potentially confusing. Making it configurable may be an option, but frankly I wouldn't want this to be that complex. A label like "Vi Mode" would feel really strange to me. So I'm not sure what this should look like personally.

**Comment by chrisduerr** [comment]
> Not to harp too much on this one point but, I still feel like it's perfectly possible (although I'm not really advocating for this) to put the bar at the top line of the terminal, and push what was there up into history. This would not cause all existing content to move, just the one replaced line.

That is not true, see alternate screen buffer. If you change the number of lines in a terminal, content **will** move around. And if it's about the primary screen buffer, then top/bottom doesn't matter (see current behavior with search).

**Comment by mitar** [comment]
I would vote for a simple 1px border all around the terminal area. I already use 4px padding so using 1px of that for such indicator would work great for me. Not sure how much people care about 0px padding, but maybe always having 1px padding would be OK for people and then we have space for such border for everyone.

**Comment by bechampion** [comment]
It would be nice some cursor color change at the very least

**Comment by chrisduerr** [comment]
> It would be nice some cursor color change at the very least

This is already possible.
