### ISSUE TITLE
Foreground and background is inverted when resizing window inside Vim

### ISSUE THREAD

**Issue by KongBorup** [alacritty/alacritty#3989]
If i open a file in (Neo)Vim and resize the window, the foreground color and background color is inverted. When Vim is exited, the issue persists. I should note that the issue doesn't occur when resizing the window outside of Vim.

I've tested the same procedure in standard PowerShell and the Command Prompt, but they both work as expected, so I believe it's a problem with Alacritty.

### System
OS: Windows
Version: alacritty 0.4.3 (c723247)
Windows: ConPTY

### Example
Opening a file in Vim:
![image](https://user-images.githubusercontent.com/16561050/87758941-bd0b8400-c80d-11ea-9a93-e71f86ff39dc.png)

Resizing the window results in:
![image](https://user-images.githubusercontent.com/16561050/87758491-d52ed380-c80c-11ea-84ed-d1d26b547eb8.png)

Exiting vim - the issue persists:
![image](https://user-images.githubusercontent.com/16561050/87758554-f2fc3880-c80c-11ea-92e6-a9aa9f5775e6.png)

**Comment by kchibisov** [comment]
Seems like a windows ConPty bug, could you try WinPty?

**Comment by KongBorup** [comment]
I switched to winpty, and the color inversion is indeed fixed. Although, the syntax highlight is now different - could you make me wiser as to why?

![image](https://user-images.githubusercontent.com/16561050/87760623-4f148c00-c810-11ea-9c06-1c349ec58807.png)

**Comment by kchibisov** [comment]
Just random Windows things. WinPTY is a bit limited in terms of colors by design. ConPTY seems just broken for you, anyway, we can't do anything about that, since those are just pipes that we read. However those pipes are 'smart' and try to do things they shouldn't leading to such issues.
