### ISSUE TITLE
Question about linux binaries

### ISSUE THREAD

**Issue by vaskark** [alacritty/alacritty#3992]
Will the official releases for Alacritty have linux binaries to download? I'm on Ubuntu and was relying on those to install. I notice the latest RC has them listed as removed.

Thanks!

**Comment by chrisduerr** [comment]
> Will the official releases for Alacritty have linux binaries to download?

No they will not. We encourage everyone to rely on the packages available for distribution, since we do not have the infrastructure to maintain builds for all the different distributions and versions.

The best choice you have are likely the PPAs made available here:
https://launchpad.net/~mmstick76/+archive/ubuntu/alacritty

**Comment by cole-h** [comment]
See also https://github.com/alacritty/alacritty/issues/3628, where some related discussion occurred.

**Comment by vaskark** [comment]
Thank you for the prompt responses. That PPA should be fine for me.

**Comment by c02y** [comment]
> since we do not have the infrastructure to maintain builds for all the different distributions and versions.

> > Will the official releases for Alacritty have linux binaries to download?
> 
> No they will not. We encourage everyone to rely on the packages available for distribution, since we do not have the infrastructure to maintain builds for all the different distributions and versions.
> 
> The best choice you have are likely the PPAs made available here:
> https://launchpad.net/~mmstick76/+archive/ubuntu/alacritty

Build an appimage is a good idea.

**Comment by chrisduerr** [comment]
> Building an appimage is a good idea.

It is not and will never be provided by Alacritty directly. Though if you want to build one yourself, you're free to do so of course.
