### ISSUE TITLE
Extending word/line selection unselects some from the beginning

### ISSUE THREAD

**Issue by jbeich** [alacritty/alacritty#3995]
When extending selection some part of it from the beginning ends up unseleceted. Appears to only affect word (double click) and line (tripple click) selection.

### Steps to reproduce:
1. Type `echo foo bar qux`
2. Left double click on `foo` to select it
3. Right click on `r` from `bar`
4. Selection becomes `o bar`, losing `fo` from the beginning

### System

OS: FreeBSD
Version: alacritty 0.5.0-rc1
Linux/BSD: Sway 1.5 (Wayland)

**Comment by kchibisov** [comment]
you should double/triple click with rmb respectively.
