### ISSUE TITLE
Alacritty should set the `COLORFGBG` env variable

### ISSUE THREAD

**Issue by luisdavim** [alacritty/alacritty#3996]
Some cli tools use the `COLORFGBG` to detect a dark background, I think alacritty should set it.

**Comment by chrisduerr** [comment]
If you want to know the background color, you should use the escape to query for it. Setting some random variable is not reliable nor standardized.

**Comment by luisdavim** [comment]
A lot of terminal emulators set this variable.

**Comment by chrisduerr** [comment]
> A lot of terminal emulators set this variable.

Source needed.

**Comment by luisdavim** [comment]
Konsole and iTerm do it for sure, I can do some research and get a list...

**Comment by chrisduerr** [comment]
I can tell you that out of XTerm, Termite, VTE, Alacritty and Kitty and URxvt, URxvt is the only one that does it. So I really don't see any reason to do it and there are clearly better, more standardized alternatives.
