### ISSUE TITLE
Is it possible to attach custom text sequences to a key?

### ISSUE THREAD

**Issue by DanielRivasMD** [alacritty/alacritty#4001]
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

OS: Linux/BSD/macOS/Windows
Version: `alacritty --version` output
Linux/BSD: X11/Wayland, DE or Compositor and WM
Windows: WinPTY/ConPTY (see `alacritty -v` output)

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by chrisduerr** [comment]
Could you go into more detail? If you're talking about typing entire words on a single keystroke, you can look into the `chars` option of keybindings. That should be documented in our default configuration file.

**Comment by DanielRivasMD** [comment]
I would like to do something like the following:

{ Key: ;, mods: Alt, chars: " => " }

However, I get an error about not allowing ";" as a key.

**Comment by chrisduerr** [comment]
Because `;` is not a value allowed for keys. The documentation should state which values are allowed. You can also see the value of `;` by running `alacritty --print-events | grep "KeyboardInput"`.
