### ISSUE TITLE
Font isn't correctly displayed

### ISSUE THREAD

**Issue by GopherJ** [alacritty/alacritty#4002]
I used `cargo install --git https://github.com/alacritty/alacritty` to installl alacritty and I have the following config:

![image](https://user-images.githubusercontent.com/33961674/87883781-0b857200-ca0a-11ea-9b49-a5b56d6231e3.png)

I can also see in gnome-terminal the font icon has been correctly rendered, it's not the case in alacritty as you can see

![image](https://user-images.githubusercontent.com/33961674/87883754-d547f280-ca09-11ea-9563-e95a82fdd336.png)

### System

OS: Linux
Version: alacritty 0.5.0-dev (f0cb1e7)
Linux/BSD: X11

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by GopherJ** [comment]
This is in gnome-terminal:

![image](https://user-images.githubusercontent.com/33961674/87883811-425b8800-ca0a-11ea-88f8-55eaf51e68eb.png)

**Comment by chrisduerr** [comment]
What exactly is the problem? The chinese characters instead of your custom glyphs? That's likely just a font fallback issue of your system, you should fix that in fontconfig.

**Comment by GopherJ** [comment]
@chrisduerr HI thanks for your reply. I want the same display effect as shown in the second screenshot. I can have icons displayed correctly in gnome-terminal but not in alacritty.

**Comment by chrisduerr** [comment]
You can check for Alacritty's font fallback by running `fc-match -s "Hack"`, which should print your font fallback order. If that's not correct, then you need to adjust it in fontconfig. There should be plenty instructions for than online, since that's not related to Alacritty at all.

**Comment by GopherJ** [comment]
@chrisduerr Sorry I changed to `Fira` later while talking...

Just tested:

```
➜  Downloads fc-match "Fira Code"
FiraCode-Regular.ttf: "Fira Code" "Regular"
```

I believe this means everything is ok? but still the icon hasn't been correctly rendered

**Comment by chrisduerr** [comment]
The important part isn't the first font, because these glyphs aren't part of your primary font. But instead the order of the remaining fonts which defines which font these glyphs will fallback to. You'll likely find some asian type font over whatever you use for those glyphs. Probably some nerdfont or fontawesome?

**Comment by GopherJ** [comment]
@chrisduerr I'm confused on the information, it works great in gnome terminal, why do you think it's a problem of font? I mean, alacritty and gnome terminal have the same access to these fonts

**Comment by chrisduerr** [comment]
They might have the same access to these fonts, but font fallback might be different. That's why I told you to look at the **fallback**, not at your primary font.

**Comment by GopherJ** [comment]
@chrisduerr Ok seems that I understand better.

I've got these:

 <details>
  <summary>Matches</summary>
  <p>FiraCode-Regular.ttf: "Fira Code" "Regular"
DejaVuSans.ttf: "DejaVu Sans" "Book"
DejaVuSans-Bold.ttf: "DejaVu Sans" "Bold"
DejaVuSans-Oblique.ttf: "DejaVu Sans" "Oblique"
DejaVuSans-BoldOblique.ttf: "DejaVu Sans" "Bold Oblique"
n019003l.pfb: "Nimbus Sans L" "Regular"
NimbusSans-Regular.otf: "Nimbus Sans" "Regular"
Loma.ttf: "Loma" "Regular"
Waree.ttf: "Waree" "Regular"
Umpush-Bold.ttf: "Umpush" "Bold"
Laksaman.ttf: "Laksaman" "Regular"
wqy-zenhei.ttc: "WenQuanYi Zen Hei" "Regular"
DroidSansFallbackFull.ttf: "Droid Sans Fallback" "Regular"
uming.ttc: "AR PL UMing CN" "Light"
uming.ttc: "AR PL UMing HK" "Light"
KhmerOS.ttf: "Khmer OS" "Regular"
MuktiNarrow.ttf: "Mukti Narrow" "Regular"
padmaa-Medium-0.5.ttf: "padmaa" "regular"
padmaa.ttf: "padmaa" "Normal"
Lohit-Bengali.ttf: "Lohit Bengali" "Regular"
Lohit-Gujarati.ttf: "Lohit Gujarati" "Regular"
Lohit-Tamil.ttf: "Lohit Tamil" "Regular"
Meera-Regular.ttf: "Meera" "Regular"
Lohit-Kannada.ttf: "Lohit Kannada" "Regular"
Lohit-Telugu.ttf: "Lohit Telugu" "Regular"
lklug.ttf: "LKLUG" "Regular"
wqy-microhei.ttc: "WenQuanYi Micro Hei" "Regular"
FreeSans.ttf: "FreeSans" "Regular"
FreeMono.ttf: "FreeMono" "Regular"
FreeSerif.ttf: "FreeSerif" "Regular"
opens___.ttf: "OpenSymbol" "Regular"
Rachana-Regular.ttf: "Rachana" "Regular"
KacstOne.ttf: "KacstOne" "Regular"
Purisa.ttf: "Purisa" "Regular"
Padauk-Regular.ttf: "Padauk" "Regular"
Hack-Regular.ttf: "Hack" "Regular"
MathJax_AMS-Regular.otf: "MathJax_AMS" "Regular"
MathJax_Fraktur-Regular.otf: "MathJax_Fraktur" "Regular"
MathJax_Main-Regular.otf: "MathJax_Main" "Regular"
MathJax_Size1-Regular.otf: "MathJax_Size1" "Regular"
MathJax_Size4-Regular.otf: "MathJax_Size4" "Regular"
MathJax_WinIE6-Regular.otf: "MathJax_WinIE6" "Regular"
Lohit-Devanagari.ttf: "Lohit Devanagari" "Regular"
DejaVuMathTeXGyre.ttf: "DejaVu Math TeX Gyre" "Regular"
DejaVuSansMono.ttf: "DejaVu Sans Mono" "Book"
DejaVuSerif.ttf: "DejaVu Serif" "Book"
LiberationMono-Regular.ttf: "Liberation Mono" "Regular"
Lato-Regular.ttf: "Lato" "Regular"
NotoSansCJK-Regular.ttc: "Noto Sans CJK JP" "Regular"
D050000L.otf: "D050000L" "Regular"
AbyssinicaSIL-Regular.ttf: "Abyssinica SIL" "Regular"
TibetanMachineUni.ttf: "Tibetan Machine Uni" "Regular"
Fantasque Sans Mono Regular Nerd Font Complete Mono Windows Compatible.ttf: "FantasqueSansMono NF" "Regular"
Manjari-Regular.otf: "Manjari" "Regular"
Pothana2000.ttf: "Pothana2000" "Regular"
chandas1-2.ttf: "Chandas" "Regular"
Pagul.ttf: "Pagul" "Regular"
mry_KacstQurn.ttf: "mry_KacstQurn" "Regular"
Phetsarath_OT.ttf: "Phetsarath OT" "Phetsarath OT"
Ubuntu-R.ttf: "Ubuntu" "Regular"
Symbola_hint.ttf: "Symbola" "Regular"
Samyak-Devanagari.ttf: "Samyak Devanagari" "Regular"
wqy-zenhei.ttc: "WenQuanYi Zen Hei Mono" "Regular"
Rekha.ttf: "Rekha" "Medium"
utkal.ttf: "ori1Uni" "Medium"
7x13-ISO8859-1.pcf.gz: "Fixed" "Regular"
12x13ja.pcf.gz: "Fixed" "ja"
6x13.pcf.gz: "Fixed" "SemiCondensed"
cu12.pcf.gz: "ClearlyU" "Regular"
cu-alt12.pcf.gz: "ClearlyU Alternate Glyphs" "Regular"
cu-pua12.pcf.gz: "ClearlyU PUA" "Regular"
NotoColorEmoji.ttf: "Noto Color Emoji" "Regular"
</p>
</details>

**Comment by chrisduerr** [comment]
That's a lot of fonts, which one of these contains the rust-lang logo? Also have you restarted Alacritty after switching to Fira Code?

**Comment by GopherJ** [comment]
@chrisduerr emmm...Sorry my bad, I just realized that I used different fonts in gnome terminal & alacritty.

I've used fantastique in gnome terminal for testing purpose but used `fira code` in alacritty. So `fira code` seems not working

**Comment by chrisduerr** [comment]
> Last question, is it possible to use Fira code but using Fantastique for icon? Sorry it's not regarding alacritty

You can configure these kind of things in fontconfig. Having Fira Code as primary font and Fantastique as secondary font should be sufficient.

**Comment by GopherJ** [comment]
~/.config/fontconfig/fonts.conf

```
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
    <alias>
        <family>sans-serif</family>
        <prefer>
                <family>Fira Code</family>
                <family>FantasqueSansMono Nerd Font</family>
        </prefer>
    </alias>
</fontconfig>

```

then `fc-cache -vf` worked for me
