### ISSUE TITLE
Mac: how to expand selection in upcoming 0.5 release

### ISSUE THREAD

**Issue by bluz71** [alacritty/alacritty#4004]
Hello Alacritty team,

This should be a quick query and resolution.

I see in the 0.5 release notes there will be selection expansion using the right-mouse button, not shift as noted [here](https://github.com/alacritty/alacritty/issues/1554#issuecomment-648043457).

On a Mac what will be combination to expand a selection, noting that Macbooks only have a trackpad and Mac desktop mice only have one button.

Double tap?
Ctrl + click?
Something else? Or both?

Regards.

P.S. Selection expansion is a very important feature, so I very much look forward to it's arrival. Currently I am still iTerm2 and GNOME Terminal; but that should soon change after 0.5.

**Comment by kchibisov** [comment]
>On a Mac what will be combination to expand a selection, noting that Macbooks only have a trackpad and Mac desktop mice only have one button.

>Double tap?
Ctrl + click?
Something else? Or both?

You have right click on apple mouse and touchpad. Just press with 2 fingers on touchpad or click right side( or it’s a double click, idk) of the mouse.

**Comment by bluz71** [comment]
Thanks.

Two-finger tap for trackpads.
Ctrl-click for Apple mice or trackpad.

Cheers.
