### ISSUE TITLE
No GPU, no Alacritty, right?

### ISSUE THREAD

**Issue by suntong** [alacritty/alacritty#4006]
This means that my PC doesn't have a GPU, right? 

![image](https://user-images.githubusercontent.com/422244/87994648-7f338780-cabb-11ea-8d0c-5ee55a96e967.png)

`msinfo32` shows my Displays are:

- Microsoft Basic Display Adapter
- Microsoft Remote Display Adapter

![image](https://user-images.githubusercontent.com/422244/87995012-5790ef00-cabc-11ea-87b4-6d4588f3330d.png)

That means I can't run Alacritty, right?

I think it is pretty obvious, but just want to confirm. thx!

**Comment by chrisduerr** [comment]
Your computer is going to have *some* kind of GPU. So the question is only if that GPU supports the OpenGL version required by Alacritty.

Are you running into any specific errors? It should let you know at startup when the OpenGL version is not supported.
