### ISSUE TITLE
Pasting into ssh on a linux host from windows results in double newlines

### ISSUE THREAD

**Issue by laundmo** [alacritty/alacritty#4007]
copy-pasting the following into ssh(nano in my case), line endings are doubled.
```
test
text
```

result:
```
test

text
```
### System

OS: Windows
Version: 0.4.3 (c723247)
Linux/BSD: X11/Wayland, DE or Compositor and WM
Windows: ConPTY

### Logs

[Alacritty-1280.log](https://github.com/alacritty/alacritty/files/4950511/Alacritty-1280.log)
the log is of me connecting to ssh by pressing uparrow to get to the command, then in ssh pressing uparrow again multiple times to get to a nano command, then using right-click to paste in nano.

**Comment by chrisduerr** [comment]
This is a bug in Windows.
