### ISSUE TITLE
Font Spacing seems random

### ISSUE THREAD

**Issue by Ferryistaken** [alacritty/alacritty#4008]
The font spacing seems "random". This happens with any font. Here is what I mean
![2020-07-21-095642_533x213_scrot](https://user-images.githubusercontent.com/47927670/88063841-7f259d00-cb38-11ea-8f09-59f47a51a3fe.png)

### System

OS: Arch Linux
Version: 0.6.0-dev(same issue on 0.4.3)
Linux/BSD: X11 with bspwm, picom as my compositor. Proprietary nvidia drivers(version 450.57 if that helps)

### Logs
Font/Terminal size: 
```
[2020-07-21 09:59:00.036303554] [DEBUG] Estimated DPR: 1.1666666666666667
[2020-07-21 09:59:00.036339132] [DEBUG] Estimated Cell Size: 7 x 13
[2020-07-21 09:59:00.036350131] [DEBUG] Estimated Dimensions: None
[2020-07-21 09:59:00.092647325] [INFO] Device pixel ratio: 1.1666666666666667
[2020-07-21 09:59:00.093569730] [INFO] Initializing glyph cache...
[2020-07-21 09:59:00.131584190] [INFO] ... finished initializing glyph cache in 0.03800445s
[2020-07-21 09:59:00.131604419] [INFO] Cell Size: 7 x 13
[2020-07-21 09:59:00.131607969] [INFO] Padding: 0 x 0
[2020-07-21 09:59:00.131617248] [INFO] Width: 800, Height: 600
[2020-07-21 09:59:00.138289993] [INFO] PTY Dimensions: Line(46) x Column(114)
````
Font size is 10, but this happens with all font sizes

Here Is my config file:
```
# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: Droid Sans Mono Slashed for Powerline
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: Droid Sans Mono Slashed for Powerline
    # Style can be specified to pick a specific face.
    # style: Bold

  # The italic font face
  italic:
    family: Droid Sans Mono Slashed for Powerline
    # Style can be specified to pick a specific face.
    # style: Italic

  size: 8.5

  # Offset is the extra space around each character. offset.y can be thought of
  # as modifying the linespacing, and offset.x as modifying the letter spacing.
  offset:
    x: 0
    y: 0
```

**Comment by chrisduerr** [comment]
Font spacing is quite the opposite of random. It's monospace. Every glyph has the same width.

But the font you're using is not a monospace width, which is not supported.

**Comment by Ferryistaken** [comment]
> Font spacing is quite the opposite of random. It's monospace. Every glyph has the same width.
> 
> 
> 
> But the font you're using is not a monospace width, which is not supported.

But I am using droid sans mono, which is the same as the example in the wiki

**Comment by chrisduerr** [comment]
Then make sure you have droid sans mono installed. That font is not droid sans mono.

**Comment by Ferryistaken** [comment]
![2020-07-21-102143_617x138_scrot](https://user-images.githubusercontent.com/47927670/88066644-ff013680-cb3b-11ea-8b5c-a3a089863179.png)
As you can see I already have droid sans mono installed.

**Comment by Ferryistaken** [comment]
The problem was with the bold fonts, I changed everything to inconsolata and it worked fine. Thanks for the help

**Comment by chrisduerr** [comment]
>  As you can see I already have droid sans mono installed.

But you've specified `Droid Sans Mono Slashed for Powerline`, that's a different font.

> The problem was with the bold fonts

Based on your screenshot, it's clearly not a problem only with bold fonts.
