### ISSUE TITLE
[Feature] word-based selection expansion

### ISSUE THREAD

**Issue by bluz71** [alacritty/alacritty#4014]
Hello Alacritty support,

One of the major features of the 0.5 release will be selection expansion via the right-mouse-button.

I have toyed with the release candidate and selection enhancement is a very nice addition, many thanks.

However, it is currently limited to character expansion only. Say for instance one double clicks a word, then expands the selection, the starting and end points will be character sliced depending on where the start and end clicks took place, which is a little jarring since the double click word boundary will suddenly disappear.

iTerm2 (via control-click) and GNOME Terminal (via shift-click) does character expansion if the original selection was a simply mouse drag, but they will do whole of word expansion if the original selection was a double click word selection. This proves useful in expanding a selection word-by-word-by-word, for example selecting a complete sentence.

Hopefully in future the same mechanism Alacritty already uses for double-click word selection can filter through to selection expansion allowing users word-by-word expansion in addition to the current character-by-character expansion.

Many thanks.

**Comment by kchibisov** [comment]
right click twice for word selection.

**Comment by chrisduerr** [comment]
@bluz71 Would you mind letting me know where you found out about selection expansion being implemented? Did you read the changelog? Just so we can maybe clarify this a bit.

**Comment by bluz71** [comment]
Haha, egg on my face, that's awesome.

Sorry about taking up your time unnecessarily. 

Tested, and works great.

**Comment by bluz71** [comment]
> @bluz71 Would you mind letting me know where you found out about selection expansion being implemented? Did you read the changelog? Just so we can maybe clarify this a bit.

These past few days I have been transitioning from iTerm2 (my Macbook) and GNOME Terminal (Linux desktop) to Alacritty on both. 

Selection expansion is something I use often on iTerm2 and GNOME Terminal. So when it was missing from 0.4.3 I hit Google for "_Alacritty Selection Expansion_" and came across the existing issue #1554 and pull request #3322. That lead to 0.5 Changelog and my testing today.

Foolishly I rushed too early with an issue, trying double-click expansion never crossed my mind.

Where to document double-click expansion? At a minimum the change-log, and maybe the existing issue #1554 as an extra comment.

All good.

Many thanks.

P.S. Once 0.5 lands I think I can move fully across to Alacritty on both Mac and Linux, the one minor niggle being box drawing text composition #118 issue.

**Comment by jieteki** [comment]
> right click twice for word selection.

`right click twice`, emm..  any other application use that action?   how to do that on a magic trackpad?

**Comment by bluz71** [comment]
> right click twice, emm.. any other application use that action? how to do that on a magic trackpad?

With Mac trackpads you need to do a normal single-finger double tap to select a word followed by **two-finger double tap** to extend that selection (word by word).

Cheers.
