### ISSUE TITLE
Cursor should be inverted when placed on same foreground color

### ISSUE THREAD

**Issue by anupamsr** [alacritty/alacritty#4016]
### System
OS: Linux (but probably all)
Version: alacritty 0.5.0-dev (87e5b1aa)
Linux/BSD: X11

Here is an example in urxvt: 
![image](https://user-images.githubusercontent.com/301019/88189600-dae64800-cc56-11ea-888e-11faff7b68ca.png)

The same behavior in alacritty:
![image](https://user-images.githubusercontent.com/301019/88189949-4c25fb00-cc57-11ea-9918-cb2aea4f404f.png)

I think usability is greatly improved with this behavior.

**Comment by anupamsr** [comment]
This will probably fix https://github.com/alacritty/alacritty/issues/3471 too.

**Comment by chrisduerr** [comment]
> This will probably fix #3471 too.

Not at all, this has nothing to do with #3471.

I'm also not entirely certain what you mean by this. The cursor in Alacritty is inverted by default, do you have a static cursor color configured?

**Comment by anupamsr** [comment]
@chrisduerr Okay. I am most probably wrong about how #3471 might be fixed.

Yes, true the cursors are by default inverted for all the colors. This problem occurs when the cursor color is static - and it will occur of any color you set because any then the cursor might get lost in any application that unknowingly sets the background color to something similar. IMHO inverting cursor color when background is same, is pretty idiomatic.

**Comment by kchibisov** [comment]
>Okay. I am most probably wrong about how #3471 might be fixed.

You can't fixed #3471 just by switching colors, it's a rendering ordering issues, since underline is being drawn after the cursor, and so will entirely cover the cursor in some cases.

**Comment by chrisduerr** [comment]
@anupamsr Let me know what you think about the behavior of #4031, I've never used this myself but I think this should be working pretty well now.

**Comment by anupamsr** [comment]
Thanks @chrisduerr . It is still slightly confusing? :)
![image](https://user-images.githubusercontent.com/301019/88451038-591e3680-ce71-11ea-9a4b-7d5ae462ffa5.png)
... but extremely works up to expectation of a reasonable person. Thanks :+1: I think this solves the issue raised.

Addendum: It seems rxvt-unicode is using some other kind of logic. I would try to study their code and check the logic (within the bounds of the license, which I think should be fine). For example, in my case the cursor color is # ffa500 (orange) while the background color is # ffaf00. Both distinct but hardly noticeable. rxvt-unicode is still makes inverts cursor fg and sets bg to black.

**Comment by kchibisov** [comment]
>Addendum: It seems rxvt-unicode is using some other kind of logic. I would try to study their code and check the logic (within the bounds of the license, which I think should be fine). For example, in my case the cursor color is # ffa500 (orange) while the background color is # ffaf00. Both distinct but hardly noticeable. rxvt-unicode is still inverts cursor fg and sets bg to black.

You may want to try latest version of #4031 and see if it fixes your other issue.

**Comment by anupamsr** [comment]
thanks
