### ISSUE TITLE
Limit the maximum length of the title

### ISSUE THREAD

**Issue by B4dM4n** [alacritty/alacritty#4017]
When trying to set a long window title either with ANSI escape codes or on the command line, `alacritty` closes with a panic.

```shell
echo -ne "\033]0;$(cat /dev/urandom | base32 -w0 | head -c4084)\007"
```

Not that I want to use such long titles, but this happened to me because I configured zsh to set the window title to the currently running command.

I found a similiar issue for `kitty`, which was [solved](https://github.com/kovidgoyal/kitty/commit/2e3037ce3a3f937067d9d50417aafae19a93dd88) by limiting the title that will be send to the window manager to 2048 bytes.

### System

OS: Linux
Version: `alacritty 0.4.3`
Linux/BSD: swaywm + Wayland

### Logs

```log
%  RUST_BACKTRACE=full alacritty -vv -t "$(cat /dev/urandom | base32 -w0 | head -c4084)"
Created log file at "/tmp/Alacritty-5536.log"
[2020-07-22 16:54:34.181188941] [INFO] Welcome to Alacritty
[2020-07-22 16:54:34.181230079] [INFO] Configuration loaded from "/home/fabian/.config/alacritty/alacritty.yml"
[2020-07-22 16:54:34.186595223] [DEBUG] Estimated DPR: 1
[2020-07-22 16:54:34.186607216] [DEBUG] Estimated Cell Size: 7 x 14
[2020-07-22 16:54:34.186610352] [DEBUG] Estimated Dimensions: None
Data too big for buffer (4100 > 4096).
Error sending request: Argument list too long
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 7, kind: Other, message: "Argument list too long" }', /build/alacritty-0.4.3-vendor.tar.gz/winit/src/platform_impl/linux/wayland/window.rs:211:9
stack backtrace:
   0:     0x56406655652b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc3ed59e15898561a
   1:     0x56406641e08c - core::fmt::write::h428e4eb5a0da7698
   2:     0x564066567476 - std::io::Write::write_fmt::h8c39360e9b251047
   3:     0x564066563365 - std::panicking::default_hook::{{closure}}::hc97e67db26a8a7dc
   4:     0x564066562f8d - std::panicking::rust_panic_with_hook::h8bdb24e0f7f3dd4a
   5:     0x564066563568 - rust_begin_unwind
   6:     0x56406641ced0 - core::panicking::panic_fmt::hb0b1db116d16da1c
   7:     0x56406641de02 - core::result::unwrap_failed::h3816b470142c1abe
   8:     0x564066275429 - winit::platform_impl::platform::wayland::window::Window::new::hb65c42ec37515f38
   9:     0x56406631e4bd - alacritty::window::create_gl_window::h0bcad77bbf7ebdd9
  10:     0x56406631aff9 - alacritty::window::Window::new::h4e121b77542de08c
  11:     0x5640662eef9d - alacritty::display::Display::new::h066fbc9580c48bb8
  12:     0x5640663a3a2b - alacritty::main::ha656ce4ba794a794
  13:     0x564066556a53 - std::sys_common::backtrace::__rust_begin_short_backtrace::h35a307366ec5c577
  14:     0x56406639eef2 - main
  15:     0x7f0a5d2fbc7d - __libc_start_main
  16:     0x5640662131da - _start
  17:                0x0 - <unknown>
```

**Comment by kchibisov** [comment]
it's libwayland limitation, nothing alacritty can't do about other than shrink the title for you.

**Comment by kchibisov** [comment]
I'm not closing this issue to track title shrinking. One more thing is flood with title events, that could also crash or deadlock, due to libwayland again.

**Comment by chrisduerr** [comment]
Generally I wouldn't be opposed to just limit it on all platforms. I think that would probably be the easiest solution.

**Comment by kchibisov** [comment]
>Generally an implementation in winit might make sense?

it's not true on all platforms, and so I've proposed such change in sctk https://github.com/Smithay/client-toolkit/issues/110. So we can avoid limiting very long titles.

However I do belive that there's no value in very long titles, since you won't see them any way. And that's the thing I've suggested in the past to limit them to 1024 chars in alacritty_terminal, when managing the title stack, though the idea was rejected. But I was coming from the exact same crash, and so we have an issue in sctk due to that.

There're other ways to crash due to libwayland-client though, like spamming with title udpates.

**Comment by chrisduerr** [comment]
> I've suggested in the past to limit them to 1024 chars in alacritty_terminal

Yeah, I still don't think that's the right choice. Either SCTK or winit should be better. I agree that having titles longer than 1024 probably doesn't make a ton of sense on any platform.

**Comment by MekhiT** [comment]
Hello I would like to contribute a solution. When you say winit, are you referring to alacritty/src/window.rs?

**Comment by kchibisov** [comment]
We mean https://github.com/rust-windowing/winit . But I don't really like to put it in winit on all platforms, I'd rather put it somewhere else, on a platforms where it breaks things, like Wayland, and so added it to either it directly or smithay-client-toolkit library, which it's using.

**Comment by kchibisov** [comment]
I've assigned myself, since the original issue is fixed upstream and title is limited right now on Wayland. if we want to do something like that in alacritty as well. Let me know, since I don't really see a reason for it.
