### ISSUE TITLE
Glyphs not aligned

### ISSUE THREAD

**Issue by leonnardo** [alacritty/alacritty#4021]
### System
OS: macOS 10.15.5
Version: 0.5.0-RC2

I'm using zsh + p10k theme
My config file is [here](https://github.com/leonnardo/dotfiles/blob/master/alacritty/alacritty.yml)

![image](https://user-images.githubusercontent.com/1310109/88306918-b1263300-cce1-11ea-8ed1-2f8b1a4e6b2f.png)

As the image shows, glyphs are not aligned.
Already tried to change `glyph_offset` but no success.

**Comment by chrisduerr** [comment]
The problem is likely that these glyphs are not part of your primary font, so the smaller symbols from the other font don't line up with the line height from your primary font.

The font configuration rfc #957 proposes a more granular control of the offsets based on font.
