### ISSUE TITLE
Some key bind not work in tmux.

### ISSUE THREAD

**Issue by 66RING** [alacritty/alacritty#4022]
OS: arch linux
Version: alacritty 0.5.0-dev (8a39346b)
Linux/BSD: bspwm

---

Hello, some key bind not work in tmux, even use a `~Alt` mode.

It work well if I not use tmux.

```
key_bindings:
  - { key: I, mods: Alt,         action: ScrollLineUp,   mode: ~Alt }
```

This seems to be not tmux bugs. The same keys work well in ST.

**Comment by kchibisov** [comment]
Scroll in alt screen applications like tmux and vim is handles by them, since we don’t have any history.

Also for tmux you need `Alt` and not `~Alt`.
