### ISSUE TITLE
Nerd font icons not showing on Windows

### ISSUE THREAD

**Issue by raphtlw** [alacritty/alacritty#4024]
### Issue

After installing the [starship](https://starship.rs) prompt and the fira code nerd fonts, the prompt indicator isn't showing in Alacritty and the fira code nerd font icons are not showing in vim too.

### System

OS: Windows
Version: alacritty 0.4.3 (c723247)
Windows: ConPTY

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: 10

**Comment by kchibisov** [comment]
Should be fixed in latest rc's.
