### ISSUE TITLE
Font clips at the top for certain font sizes.

### ISSUE THREAD

**Issue by mrillusi0n** [alacritty/alacritty#4026]
### System

OS: macOS
Version: alacritty 0.5.0-dev (058b036)

Clipping happens at size 18 (Inconsolata).

![image](https://user-images.githubusercontent.com/37063502/88393813-f464cc80-cddb-11ea-88a8-cbc3b8adac16.png)

Unclips when I increase the font size with a keybinding, so I assume it's 19.

![image](https://user-images.githubusercontent.com/37063502/88393929-25450180-cddc-11ea-9943-d816d7dd2389.png)

**Comment by chrisduerr** [comment]
This is likely a problem with your font, we don't perform any clippings and receive the metrics directly from the font itself. So I don't think there's anything we can do here.

**Comment by mrillusi0n** [comment]
I don't face the same issue with other terminals with the same config.

**Comment by chrisduerr** [comment]
Increasing the font size with a keybinding puts it at 19.5. Have you tested that exact size in other terminals?

**Comment by mrillusi0n** [comment]
My assumption of it getting to 19 was wrong, that explains. And no, I've never tried a floating point number for the font size on a terminal (manually). Thank you very much.
