### ISSUE TITLE
Alacritty doesn't support the resize window CSI sequence

### ISSUE THREAD

**Issue by foldfelis** [alacritty/alacritty#4035]
### System

OS: Linux (EndeavorOS)
Version: alacritty 0.4.3
Linux/BSD: Xfce4

### Alacritty doesn't support the resize window CSI sequence

According to the [XTerm documentation](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h4-Functions-using-CSI-_-ordered-by-the-final-character-lparen-s-rparen:CSI-Ps;Ps;Ps-t:Ps-=-8;height;width.2519), the CSI sequences listed bellow should resize Alacritty into given size.

* `echo -n "\e[8;20;80t"` should set form size to height=20, width=80
* `echo -n "\e[8;30t"` should set form size to height=30
* `echo -n "\e[8;;90t"` should set form size to width=90
* `echo -n "\e[8;0;0t"` for xterm, the form will be maximized

**Comment by kchibisov** [comment]
I'm not sure that we're interested in supporting them tbqh. You have window manager to perform those tasks. We shouldn't support everything what xterm supports and that's exactly the case.

**Comment by foldfelis** [comment]
Sure, I understand. Please regard this issue as a proposal. Recently, I'm working on a project [Terming](https://github.com/foldfelis/Terming.jl) (a library for controlling terminals/TTY in pure Julia, similar to [Termion](https://github.com/redox-os/termion)) and tested via Alacritty. In my opinion, it might be useful if Alacritty support those sequence like such.

**Comment by kchibisov** [comment]
I'd like to point out that terminal can't guarantee that it'll resize anyway, since window manager could prevent it from doing so. Resize should be initiated via your window manager or cooperative to it. You can't just blindly force a resize. So those escape sequences are completely useless.

For example in tiling window manager, all of them will be a no-op.

**Comment by foldfelis** [comment]
I see, please feel free to close this issue.

**Comment by chrisduerr** [comment]
I have no interest in supporting this in Alacritty and I've never seen a good usecase for this.
