### ISSUE TITLE
Won't install on Ubuntu

### ISSUE THREAD

**Issue by ThatOneCalculator** [alacritty/alacritty#4039]
OS: Ubuntu 20.04.1 LTS

I've tried everything to install it. No matter what I do (apt, snap, build from source) I get this error when running `alacritty`:

```
error: found a virtual manifest at `/home/kainoa/alacritty/Cargo.toml` instead of a package manifest
```

**Comment by chrisduerr** [comment]
How are you trying to run it? I doubt that you get that error when trying to directly execute the binary, since it's a `cargo` error.

**Comment by ThatOneCalculator** [comment]
I'm just doing everything in the build instructions

**Comment by ThatOneCalculator** [comment]
Also, going to `/target/releases` and ./alacritty gives
```
[2020-07-26 18:55:00.657867714] [WARN] Config visual_bell has been deprecated; please use bell instead
[2020-07-26 18:55:00.805236260] [ERROR] Failed to spawn command '/usr/local/homebrew/bin/fish': No such file or directory (os error 2)
```.
I don't use fish or homebrew

**Comment by ThatOneCalculator** [comment]
Ok so turns out im really dumb and I just had to fix this
