### ISSUE TITLE
Build errors on Ubuntu 20.04 and (unreleased) 20.10

### ISSUE THREAD

**Issue by aslatter** [alacritty/alacritty#4049]
Hi Alacritty -

I'm currently running Alacritty on Ubuntu 20.04, using my own nightly builds pushed out to an Ubuntu PPA. This means my build needs to succeed on the Ubuntu 20.04 build-VMs provided by the Ubuntu PPA infrastructure, which is now failing.

I had working builds with 7a4b4a6, and now have failing builds with 6c4e45f (I have not bisected to see at what point in between things stopped working).

### System

OS: Linux
Version: (unable to build)
Linux/BSD: N/A
Windows: N/A

### Logs

PPA build log for commit 6c4e45f on Ubuntu 20.04: https://launchpadlibrarian.net/490576152/buildlog_ubuntu-focal-amd64.alacritty_0.4.3+1-20200729T020714-6c4e45f_BUILDING.txt.gz

Possibly relevant section of the log:

```
   Compiling alacritty_terminal v0.10.1-dev (/<<BUILDDIR>>/alacritty-0.4.3+1-20200729T020714/alacritty_terminal)
error: attributes are not yet allowed on `if` expressions
   --> alacritty_terminal/src/event_loop.rs:357:29
    |
357 | ...                   #[cfg(unix)]
    |                       ^^^^^^^^^^^^

error: aborting due to previous error
```

I'm guessing it's because the version of Rust on Ubuntu 20.04/20.10 is too old?

PPAs are source-only uploads, so I don't have much of an ability to pick my Rust version.

I can always switch to Alacritty 0.5.0 and stop daily-driving nightly builds if you don't want to support versions of Rust as old as 1.41.

(The build is also failing in the under-dev Ubuntu 20.10. I don't know what version of Rust they will release with, but they currently package 1.41. Debian Testing looks like it currently has 1.43.)

**Comment by kchibisov** [comment]
We intentionally switched to the `1.43.0` for the next `0.6.0` development, since the current stable is 1.45.0, and so `1.43.0` will likely reach downstream by the time we start releasing 0.6.0.

**Comment by kchibisov** [comment]
And as you can see by the commit message of  6c4e45f it explicitly states that minimum rust version is `1.43.0`.

**Comment by aslatter** [comment]
Your support policy is your business, and supporting old toolchains is not fun.

I just wanted to make sure you knew which platforms you were making unsupportable by that move.

Thanks for taking a look!

**Comment by kchibisov** [comment]
I knew that Unbuntu will break, but it's only master that won't be supported there for some time, before the next release it will be supported again. I guess Ubuntu can update rust to 1.43.0 in like ~2-3 month?

Especially knowing that debian testing has 1.43.0 already.

**Comment by aslatter** [comment]
I'm not sure what the Ubuntu policy is for freezing versions in their dev-cycle, so I don't know what their plans are for the October release (currently the October release is on rust 1.41).

Some folks will stick on the Ubuntu LTS release for the next 1.5 years, but this sort of thing is the cost of LTS, I guess.

**Comment by aslatter** [comment]
If anyone else runs in to the same issue my work-around was to set up my PPA to use mozilla's PPA for a newer version of Rust during my build.
