### ISSUE TITLE
High CPU usage with Cava

### ISSUE THREAD

**Issue by Ferryistaken** [alacritty/alacritty#4060]
I don't really know if this is an "issue", or if it's just how alacritty works and it would be too hard to change anything about it, I am mentioning it because I would really like to switch to alacritty but the high cpu usage is really a deal breaker(not with cava, I used it because it shows the difference the most)

### System

OS: Arch Linux
Version: 0.5.0
Linux/BSD: X11 with bspwm

![2020-08-01-093252_1933x617_scrot](https://user-images.githubusercontent.com/47927670/89102810-8707fb80-d3da-11ea-8446-53f5d26403fc.png)
This are alacritty(on the left) and Termite(on the right), again I am using cava becaues it shows this difference the most, but alacritty generally has higher cpu usage. They are running with the same cava config

Top output:
![2020-08-01-093300_809x132_scrot](https://user-images.githubusercontent.com/47927670/89102817-a1da7000-d3da-11ea-945b-cee902f21779.png)

Will this be fixable in the future? Or is it just something with alacritty's design that cannot be changed?

**Comment by kchibisov** [comment]
Could you please show threads here? Also, what GPU is that?

**Comment by chrisduerr** [comment]
That just sounds like cava is poorly optimized? Alacritty will take whatever CPU is necessary to process the data received as quickly as possible. If there's no data coming in, it shouldn't use a lot of memory.

Also which CPU do you have?

**Comment by Ferryistaken** [comment]
> Also, what GPU is that?
> Also which CPU do you have?

I have a 2080 Super from MSI(with proprietary nvidia drivers) and a ryzen 9 3900x. But  I still care about not wasting resources.

here is the tree view:
![2020-08-01-095737_632x48_scrot](https://user-images.githubusercontent.com/47927670/89103131-87ee5c80-d3dd-11ea-8e5c-a1365f733b5a.png)
![2020-08-01-095745_639x48_scrot](https://user-images.githubusercontent.com/47927670/89103133-891f8980-d3dd-11ea-81bd-3dfed69e3ae4.png)

Here are alacritty's threads:
![2020-08-01-095600_361x154_scrot](https://user-images.githubusercontent.com/47927670/89103142-98063c00-d3dd-11ea-999d-2b93347e2a87.png)

And termite's:
![2020-08-01-095806_351x94_scrot](https://user-images.githubusercontent.com/47927670/89103148-a0f70d80-d3dd-11ea-837b-4fe0e6de5f65.png)

**Comment by chrisduerr** [comment]
> But I still care about not wasting resources.

Alacritty will render as quickly as the application instructs it to. If cava says it should render a lot, it will.

Though I've personally never used cava, so I can't tell you what it does itself. But generally I don't see any issue here.

**Comment by Ferryistaken** [comment]
seems a bit wrong to just say "there's no issue", maybe it's not a _bug_, but surely it's an issue, you know that your program could potentially use 10x less resources, but you disregard it saying that there is no issue? Why would you do that? It's clearly either alacritty doing something strange, or termite "optimizing" the way it renders the screen in some way. The fact that alacritty uses the gpu, but still uses 10x the cpu usage should maybe make you think that there is something wrong with it, but maybe your ego is too big to accept it?

**Comment by chrisduerr** [comment]
> It's clearly either alacritty doing something strange, or termite "optimizing" the way it renders the screen in some way.

A lot of terminal emulators intentionally slow down to reduce the resource usage. I'm saying there is no issue because there is no issue. The resource usage is directly related to the update frequency of Alacritty and the relationship is not outstandingly worrying. If you would like a terminal emulator that slows down rendering to prevent your CPU from being properly utilized, then Alacritty is probably not the right choice.

**Comment by kchibisov** [comment]
I've asked to show usage per thread in alacritty. Which looks like the following. Also show the custom thread names, so will know what threads are using the CPU exactly. If it's pty_reader thread -> nothing we can do about it, if it's some other thread it's strange that it happens, also can you ensure that you have vsync working on your system? Maybe it's not blocking and tries to draw a lot?

![picture](https://user-images.githubusercontent.com/27620401/89103692-59dc3d00-d41c-11ea-93a4-8fa52a3687f2.png)

**Comment by Ferryistaken** [comment]
![2020-08-01-104851_622x249_scrot](https://user-images.githubusercontent.com/47927670/89104086-a146d700-d3e4-11ea-8ba2-52f4ff2f0816.png)
It does seem to be PTY reader, I do have Vsync enabled

**Comment by kchibisov** [comment]
it seems like cava just writes a lot then? Though 33% usage in alacritty is also suspicious, since it shouldn't be that big. Could you compile alacritty with debug symbols(is done by default when doing release build), and do `perf record alacritty` and post this recording somewhere?

**Comment by kchibisov** [comment]
>A lot of terminal emulators intentionally slow down to reduce the resource usage.

That's what most vte terminals are doing for me, and render in like ~25fps, which is unusable on 144Hz monitor. But there could be multiple sources of high CPU usage, if the usage is not in PTY reader thread, like winit is acting weirdly and generating too much events, etc, or vsync being not working for whatever reason and we draw in 1000fps as we can on some systems(only on nvidia binary drivers such thing could happen though, that's why I've asked here about that in particular).

**Comment by Ferryistaken** [comment]
I cloned the repo from branch master and ran `cargo build --release` if that's what you meant, I then ran `perf record <path to the compiled program>`, do you need the perf.data file?

**Comment by kchibisov** [comment]
yeah, you run that and run cava for a while, then update perf.data.

**Comment by Ferryistaken** [comment]
I ran it for about 20 seconds. [Here](https://www.mediafire.com/file/ebb9yhl4xf3vwsm/file) is the perf.data file

**Comment by kchibisov** [comment]
Actually, can you just post `perf report -n --stdio` here? I forgot that perf isn't that sharable.

**Comment by Ferryistaken** [comment]
Sure, [here](https://www.mediafire.com/file/oewx8qlkavjmilm/file) it is

**Comment by kchibisov** [comment]
Hm, so I guess it's portable, but it just sounds like nothing is even using CPU here, `[vdso]` thing is a bit weird, since it's a virtual syscal. Pty reader here is barely on a list, so it's not really stressing the things.

You may try to play with perf even more, but I'm not even sure how to troubleshot that issue.

**Comment by Ferryistaken** [comment]
thanks for the help

**Comment by chrisduerr** [comment]
That doesn't look like a particularly useful `perf` backtrace. You should probably call it using `perf record --call-graph dwarf` an then try to look at both `perf report --no-children` and `perf report`. Usuall the `--no-children` one contains the important information.

But yeah, I doubt that will give you any new revelation.
