### ISSUE TITLE
Keybinding Specific Search

### ISSUE THREAD

**Issue by adam-kerrigan** [alacritty/alacritty#4073]
Is it possible to keybind a specific search/keybind specific keystrokes? I've tried passing through characters with a chained keybinding but this pastes the text on the screen rather than into the search box. I wouldn't be sure how to send the return key this way either.

key_bindings:
  - { key: C, mods: Control|Shift,           action: ToggleViMode }
  - { key: C, mods: Control|Shift, mode: Vi, action: SearchBackward}
  - { key: C, mods: Control|Shift, mode: Vi, chars: '[0-9]: \\[.\*:.*\\\] \\$' }

I wanted to be able to copy the output of the last command by selecting between PS1's or copy the most recent occurrence of https.

### System

OS: macOS
Version: alacritty 0.5.0 (a6681e3)

**Comment by chrisduerr** [comment]
You mean for doing stuff like searching for `https://.*` immediately for example?

It's not possible right now, but I've considered this myself as an option to make opening URLs easier.

**Comment by kerrigoon** [comment]
I think both of these options would be good but personally I'd prefer the first as you could pass movements to Vi mode. So then for the https example you could do something like:
1) Toggle Vi mode
2) Search for https
3) Turn on semantic selection
4) pass 'E' to Vi mode
5) open/copy link
and you wouldn't have to worry about the ending of the url, if it was the last thing on the line or whether it wrapped around to the next line

**Comment by chrisduerr** [comment]
You don't and shouldn't pass `E` to vi mode, that's just a binding you can bind yourself. So this usecase would work with both solutions anyways.

**Comment by kerrigoon** [comment]
I've tried to have a fiddle with this and got something working using an extra field in the bindings enum. However I have an issue that I can't find where to turn off the highlighting without calling cancel_search, and cancel_search looses the position of the cursor in normal mode. Do you know how this is done?

**Comment by chrisduerr** [comment]
> cancel_search looses the position of the cursor in normal mode. Do you know how this is done

You cannot change the position of the cursor in normal mode through Alacritty. That is not possible and that's good the way it is.

**Comment by kerrigoon** [comment]
Sorry not the cursor the but the selection of the search. This is in both modes I just mentioned normal because the highlighting isn't an issue in Vi mode as it disappears on exit.

**Comment by nixpulvis** [comment]
Perhaps I should open a new issue, but on the topic of search related keybindings; I feel we need to support the `Paste` action while the searchbar is active. I know search isn't a proper "mode" at the moment, so maybe this is somehow special cased. I think ideally `Search` would be a mode, since it takes control of the keyboard, and I'd have default bindings for paste which are consistent with my other default bindings.

**Comment by chrisduerr** [comment]
@nixpulvis Feel free to open an issue, I've also ran into that while implementing search to test fullwidth characters. Though I would phrase it more generally since allowing a paste action would likely mean we should look for a way to support rebinding everything in search mode.

**Comment by nixpulvis** [comment]
I've opened #4176 to track this request.

**Comment by chrisduerr** [comment]
> This also sounds related to my concern mentioned in #4165 (comment).

I don't see how this is related.
