### ISSUE TITLE
Linux pre-compiled binaries files in 0.5 release

### ISSUE THREAD

**Issue by johnnyasantoss** [alacritty/alacritty#4074]
In the previous major release there was a `.deb` file in the assets section to download and install (without having to compile it myself).
Will there be something similar for the 0.5.0 release? Should I wait it to be published on Ubuntu's official repos?

**Comment by kchibisov** [comment]
There won't be.

**Comment by cole-h** [comment]
See: https://github.com/alacritty/alacritty/pull/3630.

TL;DR: Alacritty should not be (and now is not) in charge of distributing packages for various Linux distributions. You'll have to wait for it to appear in Ubuntu's official repos, or use the PPA (https://github.com/alacritty/alacritty/issues/3863 and https://github.com/alacritty/alacritty/pull/3983).

**Comment by johnnyasantoss** [comment]
Thanks @cole-h!

**Comment by fugkco** [comment]
@cole-h assuming alacritty is statically linked, could we at least get a simple binary? Not packaged. I'd very much like to simply do `curl github.com/... -o ~/.local/bin/alacrity`. Personally preferred that in the first place over packaged binaries but it was never provided.

**Comment by chrisduerr** [comment]
Alacritty links dynamically against various system libraries.
