### ISSUE TITLE
Support pinning Alacritty to Gnome Dock by adding it as a Favorite 

### ISSUE THREAD

**Issue by thedataking** [alacritty/alacritty#4081]
Maybe this is not an alacritty issue. If so, apologies, feel free to close. My distro provides old versions of alacritty through `apt` and `snap`. I built alacritty from sources instead but I've noticed that I am unable to add alacritty as a favorite to the gnome dock just like any other UI application. I don't know if this can be fixed from the alacritty sources or whether I just have to wait for the package maintainers to ship a more recent version. Appreciate all the hard work by the way. Cheers! 

### System

OS: Linux (Ubuntu 20.04 LTS)
Version: alacritty 0.5.0
Linux/BSD: Wayland

**Comment by chrisduerr** [comment]
Did you install the desktop file?
