### ISSUE TITLE
Alacritty not recognising custom font-faces

### ISSUE THREAD

**Issue by helderburato** [alacritty/alacritty#4083]
### System

OS: macOS
Version: `alacritty 0.5.0 (a6681e3)`

## Description

After upgrade to the new version fonts from Alacritty the font `Hack` has broken in the terminal.

## Font config

I use the following configuration in my `alacritty.yml`:
```yaml
# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  # Style can be specified to pick a specific face.
  normal:
    family: Hack
    style: Regular

  # The bold font face
  bold:
    family: Hack
    style: Bold

  # The italic font face
  italic:
    family: Hack
    style: "Bold Italic"

  # Point size of the font
  size: 13.0
```

### Logs

Font/Terminal size:
```
[2020-08-05 09:45:24.100416000] [DEBUG] Using environment locale: en_US.UTF-8
[2020-08-05 09:45:24.100604000] [INFO] Welcome to Alacritty
[2020-08-05 09:45:24.100631000] [INFO] Configuration loaded from "/Users/helderburato/.alacritty.yml"
[2020-08-05 09:45:24.144881000] [DEBUG] Estimated DPR: 1
[2020-08-05 09:45:24.144961000] [DEBUG] Estimated Cell Size: 7 x 15
[2020-08-05 09:45:24.144992000] [DEBUG] Estimated Dimensions: None
[2020-08-05 09:45:24.214413000] [INFO] Device pixel ratio: 1
[2020-08-05 09:45:24.217806000] [INFO] Initializing glyph cache...
[2020-08-05 09:45:24.247804000] [INFO] ... finished initializing glyph cache in 0.029895194s
[2020-08-05 09:45:24.247889000] [INFO] Cell Size: 7 x 15
[2020-08-05 09:45:24.247912000] [INFO] Padding: 2 x 2
[2020-08-05 09:45:24.247933000] [INFO] Width: 800, Height: 600
[2020-08-05 09:45:24.250255000] [INFO] PTY dimensions: Line(39) x Column(113)
[2020-08-05 09:45:24.253395000] [INFO] Initialisation complete
[2020-08-05 09:45:25.082032000] [DEBUG] [unhandled osc_dispatch]: [['1',],['~',],] at line 785
```

**Comment by chrisduerr** [comment]
Please clarify your issue. "the font Hack has broken" doesn't tell me anything about the problem.

**Comment by helderburato** [comment]
> Please clarify your issue. "the font Hack has broken" doesn't tell me anything about the problem.

Hey!
Sorry if I didn't tell much about it, I'll try to be more clear, all the custom fonts I load after this upgrade isn't loading anymore.

**Comment by chrisduerr** [comment]
What do you mean by fonts "aren't loading anymore"?

**Comment by helderburato** [comment]
> What do you mean by fonts "aren't loading anymore"?

I set the properties, but the font just don't load.

**Comment by chrisduerr** [comment]
How do you determine that the font "just doesn't load"? Is it loading a different font? Is it not rendering any font at all? Is it loading the font but doing so incorrectly? Please be specific on what you're experiencing and what you'd be expecting instead.

**Comment by helderburato** [comment]
It's loading the default font from system and doesn't loading the custom fonts I tried to load, make sense?

**Comment by chrisduerr** [comment]
Can you share the file `/Users/helderburato/.alacritty.yml`?

**Comment by helderburato** [comment]
> Can you share the file `/Users/helderburato/.alacritty.yml`?

Yep!
[helderburato/.alacritty.yml](https://github.com/helderburato/dotfiles/blob/master/alacritty/.alacritty.yml)

**Comment by chrisduerr** [comment]
Can you try removing [this line](https://github.com/helderburato/dotfiles/blob/master/alacritty/.alacritty.yml#L149)?

**Comment by helderburato** [comment]
> Can you try removing [this line](https://github.com/helderburato/dotfiles/blob/master/alacritty/.alacritty.yml#L149)?

I tried but it doesn't worked.

**Comment by chrisduerr** [comment]
> If you test from the Google Fonts - Open Sans you'll note it's very different from the original font.

That's the proportional font, not the monospace one.

Fira Code renders a proportional one, meaning you don't have Fira Code installed.

Make sure you have the Hack font installed, if you do it should work just fine.

**Comment by helderburato** [comment]
> > If you test from the Google Fonts - Open Sans you'll note it's very different from the original font.
> 
> That's the proportional font, not the monospace one.
> 
> Fira Code renders a proportional one, meaning you don't have Fira Code installed.
> 
> Make sure you have the Hack font installed, if you do it should work just fine.

I have all of the tested fonts installed, I use in Emacs and another softwares and works fine.

**Comment by chrisduerr** [comment]
Can you check what the font and its variations are called macos' font book?

**Comment by helderburato** [comment]
> Can you check what the font and its variations are called macos' font book?
> 
> Also you said this broke after an update, can you bisect which specific commit broke this?

I fucked up bro!

The problem was in the following config:
```yaml
  # Thin stroke font rendering (macOS only)
  #
  # Thin strokes are suitable for retina displays, but for non-retina you
  # probably want this set to false.
  #
  # macOS >= 10.14.x:
  #
  # If the font quality on non-retina display looks bad then set
  # `use_thin_strokes` to `true` and enable font smoothing by running the
  # following command:
  #   `defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO`
  #
  # This is a global setting and will require a log out or restart to take
  # effect.
  use_thin_strokes: false # <<<<< It was set to "true"
```

I changed from `use_thin_strokes: true` to `false` and it worked fine.

**Comment by bhavuksharma2202** [comment]
### System

OS: Linux
Version: `alacritty 0.7.2
Linux/BSD: arch linux with DWM

i am trying to add icons to my tags but after pasting the icon from font-awesome cheatsheat some weird characters shows up instead of that particular icon. To be honest i don't know how to add multiple fonts in alacritty but i defined another one in bold style which i think was a mistake as things got broken after that 
I simply want to know how to add support for font awesome so that alacritty will start rendering those fonts
here is my config file in txt
[alacritty.txt](https://github.com/alacritty/alacritty/files/6108121/alacritty.txt)

**Comment by nixpulvis** [comment]
@bhavuksharma2202 you probably need to configure your system's fonts properly would be my guess.

https://wiki.archlinux.org/index.php/font_configuration
