### ISSUE TITLE
Input to launched GUI windows going to STDIN

### ISSUE THREAD

**Issue by aThorp96** [alacritty/alacritty#4084]
### System

OS: MacOS 10.14.6
Version: alacritty 0.4.2 (f68de37)

### Logs
None relevant in any of the suggested locations

Sometimes, after launching a GUI window, from withing the terminal, and selecting a text field on the new window, input to the window goes instead to STDIN. When this happens, it happens in every tmux pane, and when I close tmux as well. It doesn't always happen, and closing Alacritty has fixed it in the past. I couldn't find any logs around the event, but if there is a place where they may show up I can provide better insight into this issue.

**Comment by chrisduerr** [comment]
I'm not sure what you're talking about. Input to the window should go to STDIN?

**Comment by aThorp96** [comment]
Sorry, I mean launching another application from the shell. I updated the issue to be clearer, but my issue is I open Alacritty-> run `some-command-that-launches-a-gui` -> try to enter text into the GUI -> text goes to Alacritty instead

**Comment by chrisduerr** [comment]
Sounds like you still have the terminal focused instead of Alacritty? Also please make sure to update to the latest stable Alacritty version.

**Comment by aThorp96** [comment]
I'll update and check if the problem happens again. It does behave exactly as if I don't focus the new GUI window, but I've clicked and interacted with the GUI window

**Comment by aThorp96** [comment]
Can confirm this is still happening. It occurred when launching Chromium as well as a chat application

**Comment by chrisduerr** [comment]
Could you please try 0.5.0?

**Comment by aThorp96** [comment]
@chrisduerr I am
``` $ alacritty --version
alacritty 0.5.0 (a6681e3)```

**Comment by chrisduerr** [comment]
How reliably can you reproduce this? And does Alacritty show the hollow block cursor when it happens?

**Comment by aThorp96** [comment]
[Sprig](https://git.sr.ht/~whereswaldon/sprig/refs/v0.0.9), does this consistently, but I have experienced this in other applications as well.

**Comment by aThorp96** [comment]
The cursor remains a block while I click and interact with Sprig. However, if I focus on another window, Sprig still seems to remain in focus, Alacritty's cursor becomes hollow, etc. If I try and switch focus back to Sprig, text input still goes to my last focused window, which still appears to be focused. It seems like being able to assume focus is the real issue here. No matter which window I select, the Sprig window still seems to be focused, but only receives mouse events. Again, I've experienced this with other apps, but Sprig is the only one that is consistent, though it does work from Terminal. 

To reproduce this, I suggest:
1. Download Sprig and run the binary
2. Select some text field in the app and begin typing
3. Click on a browser window to focus on it
4. Begin typing into the browser's URL bar
5. Select a Sprig text field and try and give it input again

**Comment by chrisduerr** [comment]
Sounds like this is a sprig issue, not an Alacritty issue?

**Comment by aThorp96** [comment]
> Sounds like this is a sprig issue, not an Alacritty issue?

That was my initial assumption, until I experienced the same issue in PinEntry Mac. When I launch Sprig using Terminal, there is no issue as well. It seems to me like this is an edge case that sometimes appears, but Sprig always triggers.

**Comment by chrisduerr** [comment]
Are you launching it with the `open` command?

**Comment by aThorp96** [comment]
> Are you launching it with the `open` command?

I was not, however that does do the trick! Running `open $(which sprig)` does makes the application behave as expected. For a `.app` that makes sense, but I wonder how that's different from launching a binary

**Comment by chrisduerr** [comment]
Yeah, macOS really doesn't like applications launching by itself and that's by design afaik. So just launching with `open` should be the recommended way of dealing with that, preferably with a manifest in place.

**Comment by kchibisov** [comment]
I'd also mention  that it's shell's job to launch things, so I'm not sure what alacrirtty can do about it anyway, since the only thing we do is to spam your shell and render things.

**Comment by aThorp96** [comment]
> Yeah, macOS really doesn't like applications launching by itself and that's by design afaik. So just launching with `open` should be the recommended way of dealing with that, preferably with a manifest in place.

Fair enough

**Comment by mbarneyjr** [comment]
For anyone that hit this problem like me, I was using tmux3.3a, but after upgrading to tmux3.4 the problem is no longer present
