### ISSUE TITLE
Exit search using control-c (or control-g) by default

### ISSUE THREAD

**Issue by jonathanslenders** [alacritty/alacritty#4089]
Would it be possible to add control-c and/or control-g as a default key binding to exit the search?

The reason I'm asking is because it was not obvious to me that I had to press escape until I read the docs. This happened a couple of times, and each time I was convinced it should have been an Alacritty bug that made the terminal hang somehow. Users are used to having control-c available for cancelling stuff.
So, for me not really an issue anymore, but it will help new users.

Thanks!

**Comment by chrisduerr** [comment]
This would be in line with Vim, which also supports ctrl+c to cancel the search.

Given that we don't support binding things freely for search, I think this would be a good idea.

**Comment by jonathanslenders** [comment]
Thank you!
