### ISSUE TITLE
zsh: command not found: alacritty

### ISSUE THREAD

**Issue by huyvohcmc** [alacritty/alacritty#4092]
### System

OS: macOS 10.15.6
Version: can't print `alacritty --version` output

### What

Run `alacritty --version` in alacritty and zsh results with `zsh: command not found: alacritty`. I built the app from source (0.5) and did install the manual page as well as shell completions. I use zinit btw.

**Comment by chrisduerr** [comment]
You need to fix your $PATH. This has nothing to do with Alacritty.

**Comment by Exr0n** [comment]
Where is the `alacritty` binary?

**Comment by chrisduerr** [comment]
You can find the Alacritty binary in /Applications/Alacritty.app/Contents/MacOS/alacritty, or something along those lines. I saw that a recent brew update even symlinks it in /usr/share/local/bin I think, which is probably helpful. But generally the executables for app bundles are always somewhere within the bundle.

**Comment by huyvohcmc** [comment]
@Exr0n it's ` /Applications/Alacritty.app/Contents/MacOS/alacritty`
