### ISSUE TITLE
Border is transparent with WS_BORDER

### ISSUE THREAD

**Issue by TimUntersberger** [alacritty/alacritty#4094]
### System

OS: Windows
Version: alacritty 0.4.3 (c723247)
Windows: ConPTY

### Reproduce

1. Start Alacritty
2. Remove `WS_CAPTION` and `WS_THICKFRAME`
3. Add `WS_BORDER` to the window style

### Actual

The border is transparent (open the image in a new tab and zoom in to see it clearly)

![Capture](https://user-images.githubusercontent.com/32014449/89640647-53344680-d8b0-11ea-8f1e-89e1e7badae9.PNG)

### Expected

The border is not transparent or there should be a setting to change the border style.

Example (Windows Terminal)

![Capture2](https://user-images.githubusercontent.com/32014449/89640733-7bbc4080-d8b0-11ea-996d-30fdd47fc6b3.PNG)

### Description

The problem with alacritty having a transparent border for me is that when using a tiling window manager that adds `WS_BORDER` this sticks out a lot. It is possible to not add the border but then you have the following situation:

![Capture3](https://user-images.githubusercontent.com/32014449/89641207-7c090b80-d8b1-11ea-902d-9b0d252d7886.PNG)

and it could look like this with `WS_BORDER`

![Capture4](https://user-images.githubusercontent.com/32014449/89641227-862b0a00-d8b1-11ea-8b0e-189d254aefa4.PNG)

**Comment by chrisduerr** [comment]
> Remove WS_CAPTION and WS_THICKFRAME
> Add WS_BORDER to the window style

These are not Alacritty options? What do you mean by that?

**Comment by TimUntersberger** [comment]
> These are not Alacritty options? What do you mean by that?

These are [Window Styles](https://docs.microsoft.com/en-us/windows/win32/winmsg/window-styles).

This question is specificially for Windows. I can add this to my issue if you want me to.

**Comment by chrisduerr** [comment]
> After the window has been created, these styles cannot be modified, except as noted.

Sounds like you're trying to do something that is not supported?

**Comment by TimUntersberger** [comment]
I am trying to see whether this is currently possible, and if not whether I can do anything to add this.

**Comment by TimUntersberger** [comment]
I narrowed it down to the `transparent` flag.
The border appears when `transparent` is set to false.

Code
```rust
   WindowBuilder::new()
            .with_title(title)
            .with_visible(false)
            .with_decorations(window_config.decorations != Decorations::None)
            .with_transparent(true)
            .with_maximized(window_config.startup_mode == StartupMode::Maximized)
            .with_window_icon(icon.ok())
```

Is there a reason why the window has a transparent background? 
Is changing the default acceptable or would a new configuration option be needed?

**Comment by chrisduerr** [comment]
> Could we set this flag to false if the user has background_opacity set to 1.0?

No, there's no point. That just disables transparency completely it's not a fix for any problem.

**Comment by TimUntersberger** [comment]
> That just disables transparency completely

Isn't `background_opacity` when set to`1.0` not transparent? This shouldn't affect anything else or am I missing something?

**Comment by chrisduerr** [comment]
You can change background opacity at any time during program execution. So the program needs to be initialized as transparent.

If Windows 10 always has transparent borders when the window is initialized as transparent, that's a Windows bug and not an Alacritty bug. The `with_transparent` is **not** the cause of the issue no matter what.

**Comment by TimUntersberger** [comment]
>The with_transparent is not the cause of the issue no matter what

As per the documentation of glutin **it is**.

> Sets whether the background of the window should be transparent.

And it is possible to change this at runtime, but then we would need Windows specific code so I don't think that this is worth it. 

I will just use a different emulator.

**Comment by chrisduerr** [comment]
> As per the documentation of glutin it is.

That is not accurate.
