### ISSUE TITLE
Use last search string for new searches

### ISSUE THREAD

**Issue by chrisduerr** [alacritty/alacritty#4095]
With viless search it might be useful if the search text is automatically filled with the last search string by default. This is what Firefox does by default and it's generally a good idea if you want to just repeat the last search.

Firefox automatically selects the whole search text, this makes it possible to immediately type over the existing text. We have Ctrl+U to remove the entire line and start typing from nothing, but it would also be possible to clear the search text once the user starts typing. But I think the latter would be very confusing and thus pretty bad UX.

While I think for viless search this would be a great option, I'm not sure if it should be done for vi search. It might be useful to somehow access the last search pattern, but autofilling it would seem  counterintuitive  to me as a vi user.

One problem with this is that it might immediately move the viewport when starting search, potentially confusing the user. A potential solution would be to just enter the text, without jumping to any search match. So the user would have to press <kbd>Enter</kbd> once to start search.

**Comment by nixpulvis** [comment]
Firefox seems to use the **current selection** to populate a <kbd>Control</kbd>+<kbd>f</kbd>, in addition to the last search string. I'm more interesting in the former than the latter TBH. It's great idea, since it would help me with some common use cases of search, especially since #4176 isn't implemented yet.

I'm of the opinion that vi-less search and vi search acting differently is a mistake. Especially since we don't format the vi search like a `sed` pattern, thus triggering that semantic understanding. It says `Search:      `, which I expect to work the same everywhere. Filling this with the current selection would not surprise me.

On a slightly related note, the fact that today, the selections and search matches are a bit conflated, has led to a couple other confusing interactions. For example https://github.com/alacritty/alacritty/issues/4165#issuecomment-680247978.

**Comment by chrisduerr** [comment]
> Firefox seems to use the current selection to populate a Control+f, in addition to the last search string.

I wouldn't mind, but seems like a separate feature? Though it would make quite a significant difference since searching for `test.*ing` might automatically select `testing` once leaving search, but if you immediately search again you'd probably rather continue searching for `test.*ing` rather than `testing`. So I could see how this will just get rid of information that was previously present.

> I'm of the opinion that vi-less search and vi search acting differently is a mistake.

I do not and I don't see how this is related? Are you saying that you would fill both? That would be very unexpected for most vi users.

> On a slightly related note, the fact that today, the selections and search matches are a bit conflated, has led to a couple other confusing interactions. For example #4165 (comment).

That was part of the plan, yes. This is by design.

**Comment by nixpulvis** [comment]
> I do not and I don't see how this is related? Are you saying that you would fill both? That would be very unexpected for most vi users.

IDK, vi users expect to simply see `/` or `?` as the prefix to their search I believe. Additionally, vi users would expect selection and search highlighting to be separate concepts. For example in my theme, they are colored differently.

**Comment by chrisduerr** [comment]
> Yes I am saying I would expect this to work in vi-mode as well. I think vi users expect to simply see / or ? as the prefix to their search.

That's a good point and something I wouldn't mind changing, especially because it's much shorter anyways. However I think if we provide "previous search regex" functionality in vi mode, it should not be filled by default and instead be added by pressing "up"/^P. I would be fine with doing the same thing in viless search, but I'm not very confident people are going to find that. But of course we can document that and it's usually better to provide features more useful to people that know about them, rather than making them as easy to find as possible.

> vi users would expect selection and search highlighting to be separate concepts. For example in my theme, they are colored differently.

Which is also the case for search in vi mode. ;)
