### ISSUE TITLE
Write output to a log file

### ISSUE THREAD

**Issue by VersBinarii** [alacritty/alacritty#4096]
Hello there,
Is there a way to write the output from the terminal to the log file natively in alacrity?
Feature such as this is available in iTerm for example. If its not currently possible would such functionality be desirable?
I would be happy to have a go at it if it was something that fits into the alacritty feature set.

**Comment by chrisduerr** [comment]
I'm not sure what you mean? All of Alacritty's stdout can be written to a log file.

**Comment by VersBinarii** [comment]
I'm talking about storing all of the commands and all of its output being stored in a file i specify.

Do you mind pointing me to documentation on how to do so?

**Comment by chrisduerr** [comment]
You mean something like https://github.com/alacritty/alacritty/issues/1615 / https://github.com/alacritty/alacritty/pull/3709?

**Comment by VersBinarii** [comment]
If i understand correctly the issues you linked describe functionality where a selected text can be send to external program.
I'm talking about much simpler (i believe) functionality where all of the visible output is simply stored in a file. This file then contains historical records of all of the output of the session.

**Comment by chrisduerr** [comment]
> If i understand correctly the issues you linked describe functionality where a selected text can be send to external program.

No.

>  I'm talking about much simpler (i believe) functionality where all of the visible output is simply stored in a file. This file then contains historical records of all of the output of the session.

That's what those issues are about.
