### ISSUE TITLE
Toggle color scheemes

### ISSUE THREAD

**Issue by basillicus** [alacritty/alacritty#4099]
I'm wondering would it be possible to have different alacritty terminals using different color scheems each at the same time?  If i change the color scheeme in alacritty.yml all opened terminals change to the one set in the alacritty.yml. 

I find useful to have different colour schemes to quikcly identify which machine I'm working on. 

Would it be possible to set a key binding  to toggle among different color schemes that only affects to the current terminal?

This is what I would like to achieve ( I can easily do it with konsole)
![konsole_profiles](https://user-images.githubusercontent.com/40249511/89732765-e902d980-da48-11ea-9287-bbbfcf0fd03e.png)

But , to my knowledge, with alacritty this is the only thing I can achieve
![alacritty](https://user-images.githubusercontent.com/40249511/89732761-e4d6bc00-da48-11ea-8171-2273ac48f799.png)

Many thanks.

**Comment by chrisduerr** [comment]
No and I don't see a reason why this should be supported. You can have different configuration files for different terminal emulators though. You can also change some terminal properties like the background color with escape sequences.

**Comment by kchibisov** [comment]
just fyi, the escape sequences you might be interested in.

```sh
printf "\e]11;#ff00ff\e\\" # change background color
printf "\e]10;#ff00ff\e\\" # change foreground color
```

**Comment by basillicus** [comment]
> You can also change some terminal properties like the background color with escape sequences.
Thanks.That will do the job. 

I did not know what escape sequences mean. Thank you @kchibisov for the examples. I will create the corresponding aliases to quickly change the background color.
