### ISSUE TITLE
Incorrect subpixel rendering for BGR layout

### ISSUE THREAD

**Issue by DorianRudolph** [alacritty/alacritty#4100]
The BGR subpixel layout is rendered the same as RGB.

The below screenshot shows (correct) BGR on the left and RGB on the right. You probably need to zoom in to see the difference. Black on white text in BGR must have a blue fringe on the left and a red one on the right.
 
![subpixel](https://user-images.githubusercontent.com/10325838/89736503-21ff7600-da6a-11ea-9fc3-e3a2666606db.png)

### System

OS: Linux
Version: alacritty 0.6.0-dev (5762522)
Compositor: Sway

**Comment by kchibisov** [comment]
Was fixed in 269f00051ea85e423a078e9b952ea526230e5338 with the bump of crossfont to `v0.1.1`.
