### ISSUE TITLE
macOS menu bar cannot be accessed in full screen mode

### ISSUE THREAD

**Issue by knpwrs** [alacritty/alacritty#4105]
When Alacritty is running in full screen mode you cannot access the menu bar. To reproduce, simply click the green `+` button to enter full screen mode, and attempt to access the system menu bar. It does not appear.

This was also reported by @monokrome on #1252.

### System

OS: macOS
Version: alacritty 0.5.0 (a6681e3)

**Comment by chrisduerr** [comment]
This was already reported upstream in https://github.com/rust-windowing/winit/issues/1195, though I don't think we have an Alacritty issue for it yet.

**Comment by supermacro** [comment]
Is there a way to exit full screen without the menu bar present?

**Comment by kchibisov** [comment]
The default macOS binding is `Ctrl + Command + F`.

**Comment by RCPhysics** [comment]
Has this been addressed for Alacritty yet?  I've been playing around with options settings, but I haven't found a way to fix it yet.

**Comment by konradmalik** [comment]
This issue also impacts me, and I found a recently opened promising PR on the upstream side: https://github.com/rust-windowing/winit/pull/2046.
Just something to keep track of.

**Comment by ayroblu** [comment]
Merged upstream in https://github.com/rust-windowing/winit/pull/2053

Can't wait till this lands in alacritty!

**Comment by Rahulsharma0810** [comment]
Same issue in fullscreen mode.
