### ISSUE TITLE
`│` character is rendered as italic in some places(!)

### ISSUE THREAD

**Issue by MunifTanjim** [alacritty/alacritty#4106]
This is a bit strange issue to report.

`│` is displayed as italic (some places) in vim. But if I copied those and pasted in the editor, then it's displayed as expected.

**Problematic character:**

```
│
```

**Screenshot**

![image](https://user-images.githubusercontent.com/8050659/89811809-03c87180-db61-11ea-8aa6-0b4811a20707.png)

Left is **Alacritty**, Right is **Gnome Terminal**

This was not an issue on Alacritty v0.4.x

### System

OS: Linux
Version: `alacritty --version` alacritty 0.6.0-dev
Linux/BSD: X11, Ubuntu (default Gnome)

**Comment by kchibisov** [comment]
If you do `echo -e "\e[3m│"` in gnome and then in alacritty will it be italic in alacritty, and straight in gnome-terminal?

**Comment by MunifTanjim** [comment]
> If you do echo -e "\e[3m│" in gnome and then in alacritty will it be italic in alacritty, and regular in gnome-terminal?

Yes 🤔

**Comment by kchibisov** [comment]
gnome-terminal ignores your font at all here and draws a custom line IIRC, we don't do that and use your font, and your font happen to have the italic version of the char as well, so vim asks for italics and gets italics, so not our problem.

IIRC jetbrains mono(I bet it's that font) updated that particular chars to not be italic even in italic variant at some point IIRC, so try updating font.

**Comment by chrisduerr** [comment]
> your font happen to have the italic version of the char as well

Note this isn't necessarily the case, since we support italics for fonts that do not provide an italic version.

**Comment by MunifTanjim** [comment]
If anybody stumbles upon this, here's what I did to fix the issue for: [`coc-explorer`](https://github.com/weirongxu/coc-explorer) and [`fzf.vim`](https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim) with [`gruvbox`](https://github.com/gruvbox-community/gruvbox) color scheme:

Add the following in `vimrc` file:

```
let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.6, 'highlight': 'BoxChar' } }

augroup override_highlight
    autocmd!
    autocmd ColorScheme gruvbox highlight link BoxChar GruvboxGray
          \ | highlight link CocExplorerIndentLine BoxChar
augroup END
```
