### ISSUE TITLE
Keybinding doesn't work (Shift + Key4)

### ISSUE THREAD

**Issue by vaskark** [alacritty/alacritty#4111]
### Problem

Keybinding doesn't work:

`  #- { key: Key4,   mods: Shift,         mode: Vi, action: Last                    }`

What happens:

Nothing.

What should happen:

In Vi-Mode, `Shift+4` should take you to the end of the line.

### System

OS: Ubuntu 20.04.1
Version: alacritty 0.6.0-dev
Linux/BSD: X11, Compositor (picom git) and WM (berry git)

### Logs

Crashes: None.
Font/Terminal size: [link](https://justpaste.it/8i9qh)
Keyboard and bindings: [link](https://justpaste.it/2wrbs)

Thanks. Hopefully I've supplied everything correctly.

**Comment by chrisduerr** [comment]
Your keyboard input log unfortunately doesn't include you pressing Shift+4, but if it did you could easily tell what you should bind things to.

If you look at `alacritty --print-events | grep "WindowEvent.*KeyboardInput"`, it will print exactly what Alacritty receives. I'd assume for you the `virtual_keycode` is probably `None`, which means you'll have to map it to the scancode. For that you can just use `key: scancode`.

**Comment by vaskark** [comment]
Thanks for responding. Yeah, I figured I didn’t send enough info or forgot something. My apologies.

I followed your advice, and came up with `scancode = 5`. So my config now reads:

`- { key: 5,   mods: Shift,   mode: Vi, action: Last }`

Works fine now.
Many thanks.

**Comment by sierratango88** [comment]
I have faced the same issue on two separate systems using different keyboards (Logitech and Toshiba laptop keyboard) running Arch and Alacritty 0.5.0.

They both produce `scancode: 5` and `virtual_keycode: None`.

Remapping the key to the scan code does fix it but I wonder if this is a common enough issue amongst most keyboards to warrant some changes made to the default bindings.

**Comment by chrisduerr** [comment]
Scancodes are not consistent, you cannot fix this with the default bindings.

**Comment by nikitabobko** [comment]
I'm curious why does this problem happen at all? Alacritty is a GUI app, and it should be able accurately receive KeyEvents. Alacritty is not some sort of CLI app which are limited to escape sequences. This issue looks like a bug in Alacritty for me.

when I press `Shift + 4` `alacritty --print-events` output looks like:
```
[7.001653955s] [INFO ] [alacritty] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(13))), event: Key(KeyboardInput { scancode: 5, state: Released, virtual_keycode: Some(Key4), modifiers: SHIFT }) }
```
so Alacritty is able to recognize `Shift + 4` why does it fail to apply the mapping from config then?

My Alacritty version: `0.10.0-2`
