### ISSUE TITLE
Crashes on login when no display servers are running

### ISSUE THREAD

**Issue by waynevanson** [alacritty/alacritty#4114]
Running void linux from base with no desktop environment. 
I don't have a display manager at the moment, which means my display server (X11) is not running at login.

This causes the error below to happen.

![20200812_135516.jpg](https://user-images.githubusercontent.com/29592214/89973562-fb2c8400-dca3-11ea-8479-8536e8416b99.jpg)

I'll type up the contents of the image soon, just on my phone.

More details coming soon.

**Comment by kchibisov** [comment]
You can't run alacritty on tty. You need a display server like Xorg to be running or some Wayland compositor.

**Comment by waynevanson** [comment]
Yes, I understand. However, this is a little different. This may be a bug because alacritty causes the error on login, when there is no xserver running before logging in.

I should be able to login with tty1, start x server with `startx` and then run `alacritty` without any problems, right?
When I try to log in, I get the error and then get directed back to the login screen.

Error:
```sh
thread 'main' panicked at
'Failed to initialize any backend! Wayland status: XdgRuntimeDirNotSet X11 status: XOpenDisplayFailed',
/builddir/rustc-1.44.1-src/src/libstd/macros.rs:13.23
# rust backtrace debug tip
```

How to produce:

**Setup Environment**

1. Install voidlinux with the base image (no desktop environment) to a machine.
2. Reboot and login as the user.
3. Follow through with some post-installation steps.
`-S` means sync repository, `-y` means yes, `-u` means update any packages installed on the machine.
    1. `sudo xbps-install -Suy nonfree` to update.
    2. `sudo xbps-install -Suy xorg alacritty awesome` to install required dependencies.
    3. `sudo xbps-install -Suy` for good measure and ensure it's up to date.
4. Add the Xorg startup files (assuming they're not there):
    1. `touch ~/.Xauthority`
    2. `echo "exec awesome" > ~/.xinitrc`
5. `startx` to start the X server, and start alacritty by pressing `MOD4(SUPER) + P` and typing "alacritty". Press enter.

Now the environment is setup and we know that alacritty and xserver works,  we can now reproduce the bug.
Note that we DO NOT have a greeter/display manager running when logging in, therefore xserver is not running.

**Bug Reproduction**

1. Turn on computer.
2. Confirm you're in `tty1` and that no greeter is running. It should ask you to log in in tty1.
3. Attempt to log in with correct credentials.
4. Confirm an error is received and that we've been redirected back to the log in section via tty1.

As mentioned, I should be able to login. 

`uname -a`
```sh
Linux void_thinkpad 5.7.15_1 #1 SMP Wed Aug 12 10:14:05 UTC 2020 x86_64 GNU/Linux
```

**Comment by chrisduerr** [comment]
You need a window manager, this is not a bug.
