### ISSUE TITLE
Window Title Length

### ISSUE THREAD

**Issue by Fukumasuta** [alacritty/alacritty#4117]
I just cannot find the way to set the windows title length.
When i have a long path, only few last characters are displayed, like below :
instead of "/lab/php/cakephp/cakeblog/config/schema", the window title are displaying : "..config/schema"

I don't know if this is a bug or a lack of feature but i would be happy to set this length.

### System

OS: Linux (GNU/Gentoo)
Version: 0.4.3
Linux/BSD: X11/Compton and I3-gasp WM

**Comment by kchibisov** [comment]
The title is handled by your window manager, we have no control how it'll show it. I'd assume if title doesn't fit, i3 shrinks it, but alacritty doen't do anything with titles and just set them as they were requested via escape sequences or in config.
