### ISSUE TITLE
`prettier -w alacritty.yml` collapses commented indents

### ISSUE THREAD

**Issue by waynevanson** [alacritty/alacritty#4119]
In the current `alacritty.yml` file, the comments are indented away from the start of line.
On `prettier` formatting this file, the indentation is lost, even on the loosest formatting settings.

The file will load if everything is commented out. But when the lines are commented back in after formatting, it results errors. I would expect that it would parse the file correctly. 

current:
```yml
#window:
  # Window dimensions (changes require restart)
  #
  # Specified in number of columns/lines, not pixels.
  # If both are `0`, this setting is ignored.
  #dimensions:
  #  columns: 0
  #  lines: 0

  # Window position (changes require restart)
  #
  # Specified in number of pixels.
  # If the position is not set, the window manager will handle the placement.
  #position:
  #  x: 0
  #  y: 0
```

Proposed solution:

```yml
# window:
# # Window dimensions (changes require restart)
# #
# # Specified in number of columns/lines, not pixels.
# # If both are `0`, this setting is ignored.
#   dimensions:
#    columns: 0
#    lines: 0
# 
# # Window position (changes require restart)
# #
# # Specified in number of pixels.
# # If the position is not set, the window manager will handle the placement.
#   position:
#    x: 0
#    y: 0
```

Note that:
- Property descriptions are commented out twice, so that commenting in a similar section including descriptions keeps the descriptions commented out.
- Property description comments are aligned to the start of the property name when the property is commented out.
- Indentation starts at the start of line, not at it's indented position.

What are your thoughts?

### System

OS: Linux
Version: `alacritty 0.5.0`
Linux: X11

### Logs

Crashes: 
[2020-08-13 19:23:46.734470996] [ERROR] Problem with config: invalid type: unit value, expected struct WindowConfig; using default value
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by chrisduerr** [comment]
> What are your thoughts?

That this is a prettier problem.

**Comment by nixpulvis** [comment]
I agree that we shouldn't be forced to work around other tools styles. That said, I am sympathetic, since my editor's uncomment functionality doesn't handle this quite right either. The issue is that nested comment characters are messy.

Perhaps the best case would be to have tools aware of the difference between `# This is a proper comment` and `#code: true`. Where the space after the comment character(s) matters. But for now, this is just our style.

**Comment by chrisduerr** [comment]
> since my editors' uncomment functionality doesn't handle this quite right either

Which editor do you use? It works just fine in neovim.

**Comment by nixpulvis** [comment]
@chrisduerr I still just use Vim 8.2.

As things are configured now, my commenting works pretty well, but not in these cases, starting with:

```yaml
# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
#env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  #TERM: alacritty
```
Un-commenting this whole block with `gc` yeilds an invalid config:

```yaml
 Any items in the `env` entry below will be added as
 environment variables. Some entries may override variables
 set by alacritty itself.
env:
   TERM variable
  
   This value is used to set the `$TERM` environment variable for
   each instance of Alacritty. If it is not present, alacritty will
   check the local terminfo database and use `alacritty` if it is
   available, otherwise `xterm-256color` is used.
  TERM: alacritty
```

I understand that I am expected to un-comment the code specifically here, but this is part of the difference in opinion on the matter. The "issue" is that the un-commented text in spaced a character in, where it should be aligned with everything else.

**Comment by chrisduerr** [comment]
> this is part of the difference in opinion on the matter

I don't see how this is a "difference in opinion". It's literally just doing what you're telling it to do.

**Comment by nixpulvis** [comment]
Well let's compare what I posted above to the "proposed solution". If I start with the configuration segment (copy and pasted, w/ fixed indentations):

```yaml
# window:
#   # Window dimensions (changes require restart)
#   #
#   # Specified in number of columns/lines, not pixels.
#   # If both are `0`, this setting is ignored.
#   dimensions:
#     columns: 0
#     lines: 0
# 
# # Window position (changes require restart)
# #
# # Specified in number of pixels.
# # If the position is not set, the window manager will handle the placement.
#   position:
#     x: 0
#     y: 0
```

And un-comment this block with Atom's comment feature:

```yaml
window:
  # Window dimensions (changes require restart)
  #
  # Specified in number of columns/lines, not pixels.
  # If both are `0`, this setting is ignored.
  dimensions:
    columns: 0
    lines: 0

# Window position (changes require restart)
#
# Specified in number of pixels.
# If the position is not set, the window manager will handle the placement.
  position:
    x: 0
    y: 0
```

**Comment by chrisduerr** [comment]
And then the number of lines you're forced to uncomment suddenly increases significantly. That's no improvement.

**Comment by nixpulvis** [comment]
Well it is an improvement in this respect, at least for me, since all I have to do now is start a visual selection at the top, and move down to the end, and then un-comment. Whereas, otherwise I need to select each region of code individually.

This said, I'm not arguing one way or another on this topic, since the way we have it now presents a cleaner and shorter template configuration file. Editors _could_ be configured to handle this kind of commenting, so I see no reason we should be forced to change anything. I'm just providing my observations on the topic.

**Comment by waynevanson** [comment]
It might be safe to say that the comment style below (as mentioned above) is most likely to be elegantly handled:

```yaml
# window:
# # Window position (changes require restart)
# #
# # Specified in number of pixels.
# # If the position is not set, the window manager will handle the placement.
#   position:
#     x: 0
#     y: 0
```

I'll add a gist with this style in 24 hours for those who may want to use it.

@chrisduerr Does this change affect cause issues in your editor of choice?

If there's more traction on this issue, I'd happily send in a PR to help out :)

**Comment by kchibisov** [comment]
I don't see why we should change anything about comments in a file. And pretty clear what to uncomment or what you shouldn't. If your editor is having troubles with yaml file, you're free to update the file yourself if your editor is facing problems.

**Comment by nixpulvis** [comment]
> I'll add a gist with this style in 24 hours for those who may want to use it.

@waynevanson I appreciate your enthusiasm, however I wouldn't recommend people to base their config file on a 3rd party gist (which is more likely to be outdated) just because they don't like the comment style. Of course, there's nothing stopping people from doing this.

**Comment by nixpulvis** [comment]
FWIW, my personal config file doesn't contain all of the comments or default options, since we don't require all settings to be present. I don't use the packaged versions of Alacritty either, but perhaps moving our template config to /etc or something would be a good idea for people.

Regardless, this shouldn't be a big deal.

**Comment by waynevanson** [comment]
>  but perhaps moving our template config to /etc or something would be a good idea for people.

This is a good idea. Downloading the config it from the releases felt a little odd.

**Comment by chrisduerr** [comment]
Fyi Archlinux already gets this right by putting it at `usr/share/doc/alacritty/example/alacritty.yml`. Just a question of maintainers doing their best to provide all the necessary files for the application.
