### ISSUE TITLE
Switching out font library: Pathfinder

### ISSUE THREAD

**Issue by aktau** [alacritty/alacritty#412]
Hi! I just saw this (http://pcwalton.github.io/blog/2017/02/14/pathfinder/) on Hacker News and thought you might be interested, since Alacritty focuses on performance. Reading some of the issues on purported bad performance when comparing to xterm/Gnome Terminal/..., I'm always wondering how much of that is due to the font rendering, my gut feeling says a lot. Of course, switching out the font rendering library just to see if this is true may be too much effort, I don't know (not a rustacean myself).

**Comment by jwilm** [comment]
Thanks for filing the issue to discuss Pathfinder! This library will likely not make a difference for rendering western text because glyph cache hit rates are near 100%. With CJK text, Pathfinder will be necessary for optimal performance.

> Reading some of the issues on purported bad performance when comparing to xterm/Gnome Terminal/..., I'm always wondering how much of that is due to the font rendering, my gut feeling says a lot.

Not true. The glyph cache hit rate is nearly 100% which means a minuscule amount of time is spent on glyph rasterization. The major performance issue when compared with other terminals is due to #125 in all known cases. There's actually a fix for that pending in #410.

**Comment by OJFord** [comment]
> This library will likely not make a difference for rendering western text because glyph cache hit rates are near 100%. With CJK text, Pathfinder will be necessary for optimal performance.

I'm asking only out of interest; not in any way a suggestion, since I know almost nothing about font rasterisation - but what about 'pictorial glyphs', for want of a better term, used e.g. in a dynamic prompt or hip/modern tool stdout?

**Comment by jwilm** [comment]
> what about 'pictorial glyphs', for want of a better term, used e.g. in a dynamic prompt

Assuming you mean glyphs like the powerline arrow or icon glyphs from font awesome, they would have a very high hit rate in the glyph cache and not benefit much from Pathfinder.

**Comment by OJFord** [comment]
That's the sort of thing I mean, but by 'dynamic' I meant, for example, friending on the state of the present git repository. I suppose though it just contributes to the misses, and not significantly.

**Comment by aktau** [comment]
Thanks for commenting @jwilm! It's comforting to know the cause of the slowness has been identified in #410 (and hopefully Mesa can be fixed as well). Apologies for implying font rasterising was the slow part, I clearly wasn't thinking of the glyph cache.

Another thing though: reading the Pathfinder article it seems like they store glyphs in a non-standard way, might this save on memory? I'm asking because there are reports of Alacritty using quite a bit more memory than other terminals. The first thought I had when reading those reports were:

1. Alacritty is one of the few terminal emulators that directly uses the GPU, it's possible that it's keeping process-local copies of the glyph cache and (perhaps separate) render buffer. I remember when I was writing a simple OpenGL glyph renderer in C, I only figured pretty late in the game that I could release the client-side backing store after I filled an OpenGL buffer with the `glBuffer*/glMap*` functions.
2. Alacritty doesn't have scrollback (yet), which I note is one of the bigger memory hogs in other terminals, which would be another indication that it's something about the way Alacritty renders that causes the higher memory usage.

Of course, for others terminal emulators, this memory usage will be partly hidden in things like Quartz, X.org, ... (not for Wayland though).

Anyway, it might be useful to study the way Pathfinder stores glyphs and excepts them (or returns them?) for rendering. It may be more efficient from a memory perspective. [*]

[*]: I didn't really get from the article whether all the described actions only involve rasterizing, or also rendering to the screen (or any framebuffer), I presume that the format for the "cache" and that for the screen is different.

**Comment by jwilm** [comment]
> Apologies for implying font rasterising was the slow part, I clearly wasn't thinking of the glyph cache.

No worries, I just want to make sure information on the issue tracker is generally accurate.

> reading the Pathfinder article it seems like they store glyphs in a non-standard way, might this save on memory?

Pathfinder rasterizes glyphs directly to a texture atlas and returns bounding boxes of glyphs within that texture as the rasterization result. Alacritty ends up using a texture atlas as well, but we have an intermediate step where it's rendered to a non-GPU buffer. This can be seen in [`load_and_cache_glyph()`](https://github.com/jwilm/alacritty/blob/908ea5543a40b772d2336e2ce981aae61dc6b2d7/src/renderer/mod.rs#L253-L261).

> I only figured pretty late in the game that I could release the client-side backing store after I filled an OpenGL buffer with the glBuffer*/glMap* functions

Alacritty drops the buffer immediately as seen in the above link.

> I'm asking because there are reports of Alacritty using quite a bit more memory than other terminals.

I haven't done any profiling in this area, but I can think of a few places where lots of memory is used:

1. The two character grids. Each cell is like 4 bytes, and a large screen might have up to 40,000 cells.
2. The Renderer allocates a buffer large enough for the display list to contain every cell. This is another 40,000 elements, and each element is many bytes (this would be a good thing to optimize both for memory usage and upload time to the GPU).
3. OpenGL itself; I'm not sure if memory used here is considered to be part of the RSS, but that would certainly explain a big difference between other terminals and Alacritty. There's not much we can do if this is the case. We might be able to see how much other terminals are cheating by comparing memory usage on X11 versus Wayland.

**Comment by aktau** [comment]
> 2. The Renderer allocates a buffer large enough for the display list to contain every cell. This is another 40,000 elements, and each element is many bytes (this would be a good thing to optimize both for memory usage and upload time to the GPU).

I don't think you're using the ancient OpenGL concept of "display list", so what does display list in alacritty refer to? Something between:

```
// Step 0: update/create texture atlas

// Step 1. transform character grid into "display list"? Is that what it is?
(character grid : UTF8) ---generates--->  (display list : struct with tex coords, colors??) 

// Step 2. Upload display list to GPU?
// upload as Shader storage buffer? Texture data buffer? Uniform buffer? Or as vertext/texture/color arrays ? 

// Step 3. GL draw single quad + shader or vertex/texture/color + quad for every character?
```

Or did I get the process entirely wrong? It's been a long time since I've rendered anything to anything.

Anyway, it might be possible to just keep the character grid directly on the GPU and write to it with a mapped GL buffer, then do everything in a shader. For multi-byte characters, a special slow pass could be done (two drawcalls, still no big deal).

> 3. OpenGL itself; I'm not sure if memory used here is considered to be part of the RSS, but that would certainly explain a big difference between other terminals and Alacritty. There's not much we can do if this is the case. We might be able to see how much other terminals are cheating by comparing memory usage on X11 versus Wayland.

Not sure about GPU memory, but I think that it would be accounted towards the process. In any case, often enough the driver (which runs in the process) will keep things like texture buffers around locally (depending on the hints given, and the phase of the moon).

Chrome can show (for each tab) how much regular RSS and how much GPU memory it is using on all platforms I've seen, so it must be possible to get metrics about this. Perhaps macOS Instruments OpenGL tools would be the easiest way to get a quick look.

Anyway, I think I've said enough untrue and confusing things now. I'm keeping an eye on this project since I like things that are minimal and fast, though I am sort of hoping that scrollback is included one day (it's the reason I'm not using `st(1)`). Thanks for writing the project!

**Comment by jwilm** [comment]
> Or did I get the process entirely wrong? It's been a long time since I've rendered anything to anything.

Your synopsis of how Alacritty uses and thinks about a display list is correct.

> Chrome can show (for each tab) how much regular RSS and how much GPU memory it is using on all platforms I've seen, so it must be possible to get metrics about this

Good to know this exists, thanks for the info.

> Anyway, I think I've said enough untrue and confusing things now. 

Whether or not that's the case, you've prompted a bunch of really good discussion, and I would encourage you to keep posting.

> I'm keeping an eye on this project since I like things that are minimal and fast, though I am sort of hoping that scrollback is included one day (it's the reason I'm not using st(1)).

I've started using i3 some time ago now, and scrollback is becoming more likely with every passing day.

> Thanks for writing the project!

Really glad you like it 😄

**Comment by ianks** [comment]
Pinging @pcwalton since he will have some good insights on this if he has time to share!

**Comment by casey** [comment]
One reason this might be nice to have is for #121 (dynamically changing font size), since presumably the glyph cache will need to be regenerated all at once. Since user behavior is usually to hit `ctrl +` and or `ctrl -` a few times in quick succession to get the font size right, being able to regenerate the cache quickly so that that it can redraw at the new font size without too much delay will make for a pleasing experience.

**Comment by mingwandroid** [comment]
With a signed distance fields and texture arrays (or primitive cube maps) fonts atlases can be computed once (can be slow if implemented naively) with no need to recalculate them for different zoom levels.

Is this worth considering? (I don't know that pathfinder uses SDFs though, so I am also asking from the POV of alacritty's own font renderer, and sorry to be somewhat off-topic, loving alacritty, as soon as I can search the scrollback I'm ditching iTerm2).

**Comment by pcwalton** [comment]
Pathfinder doesn't use SDFs, as (1) SDFs are not truly resolution-independent; (2) the quality of SDFs is unacceptably low for body text; (3) SDFs take an extremely long time to generate (many times slower than actually rendering the glyph on CPU, in fact); (4) Pathfinder is faster than SDF due to not having to render anything in blank areas. As for msdfgen, it fails on many glyphs of fonts used in the real world (it's a bunch of heuristics to try to detect corners and curves, which can fail).

**Comment by chrisduerr** [comment]
I think at this point it's more worthwhile to improve our own library.
