### ISSUE TITLE
Installation is non-trivial for MacOS

### ISSUE THREAD

**Issue by sunchao** [alacritty/alacritty#4136]
On the README it says:
"Alacritty can be installed by using various package managers on Linux, BSD, macOS and Windows."

However simply:
```
brew install alacritty
```

doesn't work. It is also not in the [detailed instruction page](https://github.com/alacritty/alacritty/blob/master/INSTALL.md).

**Comment by kchibisov** [comment]
you can grab the dmg from release page or use brew cask.

**Comment by sunchao** [comment]
yeah I figured later but the statement is too simple (and somewhat misleading) for normal users. I think it is better to put the instruction somewhere.

**Comment by kchibisov** [comment]
We had notes about installing brew cask in the past, however the section of installing with package manager X became too bloated, so we removed it all together, relying on people being able to use their package manager to find things out. We also do say that everything is on release page, if you're not using package manager.

So,  things are fine the way they're now.

**Comment by chrisduerr** [comment]
`brew cask install alacritty` works. Very simple if you ask me.

**Comment by sunchao** [comment]
Thanks. Yes it was pretty simple in the end. Intuitively I went for `brew install alacritty` and got confused when it didn't work. Not that familiar with homebrew though so this could be trivial for others.
