### ISSUE TITLE
Instructions to update to latest versions on ubuntu/other distros

### ISSUE THREAD

**Issue by rishabh96b** [alacritty/alacritty#4137]
Hey,
I tried to search the instructions for updating to the latest alacritty version bit couldn't find any. Can you please consider adding it to the docs or point me to the instructions if they are already available.

### System

OS: Ubuntu
Version: alacritty 0.4.1

**Comment by chrisduerr** [comment]
See the INSTALL.md file. Since Ubuntu doesn't offer an Alacritty package, you have to build it from source.

There are PPAs available for some Ubuntu systems, but they're all third party packages.
