### ISSUE TITLE
Upside-down white triangle on icon in KDE Plasma

### ISSUE THREAD

**Issue by b-ggs** [alacritty/alacritty#4141]
The icon appears to have an upside-down white triangle when viewed (or installed on) a system with KDE Plasma.

### System

OS: Linux (KDE neon, Manjaro KDE)
Version: 3a7130086a8b5fa95c46a15d5b09a220be57708c
Linux/BSD: X11, KDE Plasma 5.19.4

#### Actual appearance

KDE neon 5.19

![image_2020-08-18_09-14-16](https://user-images.githubusercontent.com/6130147/90460437-57752500-e136-11ea-821b-c03f0e7becd5.png)

KDE neon 5.19 (Live)

<img width="912" alt="Screen Shot 2020-08-18 at 9 23 47 AM" src="https://user-images.githubusercontent.com/6130147/90460481-71af0300-e136-11ea-8aa7-15496d45f996.png">

Manjaro KDE 20.0.3 (Live)

<img width="1136" alt="Screen Shot 2020-08-18 at 9 29 54 AM" src="https://user-images.githubusercontent.com/6130147/90460445-5d6b0600-e136-11ea-8222-1002b30197d9.png">

#### Expected appearance

macOS

<img width="1680" alt="Screen Shot 2020-08-18 at 9 13 56 AM" src="https://user-images.githubusercontent.com/6130147/90460465-68be3180-e136-11ea-9bc6-b4ac3371b5f9.png">

GNOME on Debian (Live)

<img width="912" alt="Screen Shot 2020-08-18 at 9 27 11 AM" src="https://user-images.githubusercontent.com/6130147/90460523-90ad9500-e136-11ea-8ea7-5e76f9968636.png">

**Comment by kchibisov** [comment]
it's a QT bug, for those systems we have a compat icons here https://github.com/alacritty/alacritty/tree/master/extra/logo/compat.
