### ISSUE TITLE
Support for setting individual color for underline (<ESC>[58...m)

### ISSUE THREAD

**Issue by sydney-severs** [alacritty/alacritty#4142]
It would be nice if alacritty learns how to set the color of the underline independently of the text color. This is in particularly useful for marking spelling mistakes in a (console) text editor and still keep other syntax highlighting intact.

According to Wikipedia [0] the (semi-standard) CSI / SGR / ANSI escape code / whatever sequence is `<ESC>[58...m`

Other terminals which support this are for example Kitty, VTE, mintty, and iTerm2.

[0] https://en.wikipedia.org/wiki/Control_Sequence_Introducer

**Comment by chrisduerr** [comment]
The biggest problem with this is that it would add an additional field to each cell, tracking the color of the underline, which would have a decent impact on memory usage (about 8%). This of course affects everyone, colored underline or not.

I don't think that should necessarily stop us from implementing it, but it would be nice to try and reduce the cell size first before implementing it. That is the main reason it isn't implemented yet. So we should try to free up some space and then it should be a simple choice to use some of that freed up space to store this additional information. The best place for that would likely be the zerowidth character storage.

**Comment by bluz71** [comment]
The recent commit [b904207b1979bb] added support for double underline whilst also doing this:

> Alacritty will now also always fallback to the normal underline in case
any of the other underlines like the undercurl are specified.

A very nice enhancement towards the goal of colored undercurls as noted in this [undercurl feature request](https://github.com/alacritty/alacritty/issues/1628).

A pathway as outlined by @chrisduerr seems to be:

- First reduce cell size

- Second use the freed up space, say in zerowidth character storage, to store color underline details separate from the character they sit beneath.

Folks like myself who want colored undercurls would instead get colored underline which are almost as good. Colored underline/undercurl is very useful for spelling and lint/diagnostic errors in terminal editors such as (Neo)vim.

I am a proponent of this development path and I hope it does eventuate.

**Comment by kchibisov** [comment]
The cell size was reduced in https://github.com/alacritty/alacritty/commit/ec42b42ce601808070462111c0c28edb0e89babb

**Comment by bluz71** [comment]
Fantastic. One step along the path. Many thanks.

**Comment by bluz71** [comment]
Bump time.

So I built @Jesse-Bakker's [colored-underline](https://github.com/Jesse-Bakker/alacritty/tree/colored-underline) branch as noted in PR #4660 and gave it a spin.

I love it, **a lot!**.

Current Alacritty:

![Default](https://user-images.githubusercontent.com/11382509/119248953-31564700-bbd8-11eb-8016-b2d3a7e86029.png)

And the colored underline branch:

![Colored](https://user-images.githubusercontent.com/11382509/119248959-3d420900-bbd8-11eb-8152-7be40a373caf.png)

Spelling errors in terminal Neovim are highlighted in red which brings IDE-type bling to the terminal. As a user this brings a another level of visual hints that are especially useful for Language Server Protocol (LSP) realtime diagnostics.

If I could add just one feature to Alacritty it would be this (daylight second).

**Comment by bluz71** [comment]
Thank you @kchibisov (and @chrisduerr); the recent merge of colored underline support is absolutely brilliant.

Looks gorgeous in practice, colored underline:

![Colored_Underline](https://user-images.githubusercontent.com/11382509/158715468-c4381954-927c-4d1b-928d-40af826f1130.png)

And better yet colored undercurl:

![Colored_Undercurl](https://user-images.githubusercontent.com/11382509/158715487-e609cde2-99de-4589-be4d-a03c6a5e80cb.png)

The dash of color for lint and spell errors is a genuine nicety.

I am so grateful :clap: 

Cheers.

**Comment by Shatur** [comment]
> Thank you @kchibisov (and @chrisduerr); the recent merge of colored underline support is absolutely brilliant.

How did you turn it on? I compiled the last master, but I don't have the colored undercurl/undercurl.

**Comment by kchibisov** [comment]
Consult neovim highlighting? I think it's `guisp` that sets it.

**Comment by Shatur** [comment]
> Consult neovim highlighting? I think it's guisp that sets it.

Doesn't work for me. I just managed it to work by setting `TERM` to `xterm-kitty`. What do you use for `TERM`?

**Comment by kchibisov** [comment]
`alacritty`.

**Comment by Shatur** [comment]
Strange, it doesn't work for me with `alacritty` (default) `TERM`. My theme sets `guisp` and I have `termguicolors` enabled.

**Comment by kchibisov** [comment]
You don't actually need `termguicolors` for that. But if it matters it used to work for me with nvim 0.5.1. Maybe your theme is checking something and disables, since mine don't. But also, default colorscheme in nvim should have spell colored with guisp iirc.

**Comment by Shatur** [comment]
> But if it matters it used to work for me with nvim 0.5.1.

Hm... I use Neovim 0.6.

> But also, default colorscheme in nvim should have spell colored with guisp iirc.

Yes, I tried `colorscheme default`, still doesn't work :(

**Comment by bfrg** [comment]
@Shatur The following works in vim, maybe it works in neovim as well:
```vim
" Enable undercurls in terminal
let &t_Cs = "\e[4:3m"
let &t_Ce = "\e[4:0m"

" Enable underline colors (ANSI), see alacritty #4660
let &t_AU = "\<esc>[58;5;%dm"

" Colorscheme
if !empty($DISPLAY) && $COLORTERM !~# '^rxvt'
    " Enable true colors, see :help xterm-true-color
    if &term =~# '^\(tmux\|screen\|st\|alacritty\)'
        let &t_8f = "\<esc>[38;2;%lu;%lu;%lum"
        let &t_8b = "\<esc>[48;2;%lu;%lu;%lum"
    endif

    " Enable underline colors (RGB), see alacritty #4660
    let &t_8u = "\<esc>[58;2;%lu;%lu;%lum"

    " Use highlight-guibg and guifg attributes in terminal
    set termguicolors
endif
```

Your colorscheme needs something similar to this:
```vim
hi SpellBad   ctermbg=NONE ctermfg=NONE guibg=NONE guifg=NONE cterm=undercurl gui=undercurl ctermul=196 guisp=Red
hi SpellCap   ctermbg=NONE ctermfg=NONE guibg=NONE guifg=NONE cterm=undercurl gui=undercurl ctermul=226 guisp=Yellow
hi SpellLocal ctermbg=NONE ctermfg=NONE guibg=NONE guifg=NONE cterm=undercurl gui=undercurl ctermul=51  guisp=Cyan
hi SpellRare  ctermbg=NONE ctermfg=NONE guibg=NONE guifg=NONE cterm=undercurl gui=undercurl ctermul=201 guisp=Magenta
```

**Comment by Shatur** [comment]
> @Shatur The following works in vim, maybe it works in neovim as well:

Tried, no effect. It strange that everything works only with `xterm-kitty` set as `TERM`.

**Comment by Shatur** [comment]
Stupid me, I had `.terminfo/alacritty` in my home directory for some reason. Removed it and started to work. Sorry for the mess.

**Comment by kchibisov** [comment]
Yeah, if you had old terminfo, it wasn't supporting styled underlines.
