### ISSUE TITLE
[Windows] How to move alacritty window when decorations is set to none?

### ISSUE THREAD

**Issue by Sezaan** [alacritty/alacritty#4144]
When `decorations: none`, how to move alacritty window? Please help, can't figure this out.

**Comment by chrisduerr** [comment]
Have you tried holding super? That's usually how it works on Linux.

**Comment by Sezaan** [comment]
> 
> 
> Have you tried holding super? That's usually how it works on Linux.

No it isn't working on windows. :(

**Comment by chrisduerr** [comment]
Summoning @cole-h and @davidhewitt since they've actually used Windows within the last decade. There's probably a way, but I don't know it myself.

**Comment by davidhewitt** [comment]
I can do it on my machine in the following way:

1. Shift + right-click on alacritty icon in the taskbar at the bottom
2. In the context menu that opens, select "Move"
3. Press any arrow key (e.g. left arrow)
4. Alacritty is now bound to the mouse cursor, so move the window with the mouse!
5. Click to finish moving.

The same context menu should _in theory_ appear with Alt + space, but that doesn't seem to work for me. (So there might be a small upstream winit bug that could be reported for that.)

**Comment by Sezaan** [comment]
> 
> 
> I can do it on my machine in the following way:
> 
>     1. Shift + right-click on alacritty icon in the taskbar at the bottom
> 
>     2. In the context menu that opens, select "Move"
> 
>     3. Press any arrow key (e.g. left arrow)
> 
>     4. Alacritty is now bound to the mouse cursor, so move the window with the mouse!
> 
>     5. Click to finish moving.
> 
> 
> The same context menu should _in theory_ appear with Alt + space, but that doesn't seem to work for me. (So there might be a small upstream winit bug that could be reported for that.)

Thanks it worked.

**Comment by ayaen** [comment]
Shift+Alt+Space works to show the context menu, and I am able to select the Move option but that does nothing when the decorations are set to None. Works when decorations are set to full. Can anyone confirm this? Latest Windows 11, latest alacritty. This is not a big deal but a bit of a deal breaker since I like to use alacritty as a small translucent window to do repl stuff on top of a pdf, and so, you know that toolbar on top is hella distracting.

**Comment by takayums** [comment]
> When `decorations: none`, how to move alacritty window? Please help, can't figure this out.

I can move the terminal by clicking Windows/Command + Shift,  then hold left click on the terminal and move it as desired

**Comment by davehorner** [comment]
I know this issue is about windows; but I wanted to note for the next mac user looking for the ability to move the window without decorations.

https://mmazzarolo.com/blog/2022-04-16-drag-window-by-clicking-anywhere-on-macos/
```
defaults write -g NSWindowShouldDragOnGesture -bool true
```
logout, log back in; cmd+ctrl+click and drag
