### ISSUE TITLE
Bump Fedora COPR repository to version 0.5.0

### ISSUE THREAD

**Issue by fdcds** [alacritty/alacritty#4145]
The last version available for Fedora is `0.4.3-1.fc31` [1]. The latest Alacritty release is 0.5.0 and the latest Fedora release is 32.

[1]: https://copr.fedorainfracloud.org/coprs/pschyska/alacritty/packages/

**Comment by kchibisov** [comment]
ping the guy who is maintaining it, packaging is not our job.
