### ISSUE TITLE
font.offset.y should add offset spacing above and below the characters, not just above

### ISSUE THREAD

**Issue by ronakg** [alacritty/alacritty#4146]
When adding a y offset for fonts, the offset is only applied above the characters. This creates an asymmetrical appearance for the fonts.

I set the `font.offset.y` to `20` to highlight the issue. Looks at the vim status line where the issue is very apparent. 

<img width="1049" alt="Screen Shot 2020-08-18 at 11 59 10 AM" src="https://user-images.githubusercontent.com/1058322/90554479-c8bed300-e14a-11ea-95cb-3e3b8141e643.png">

### System

OS: macOS
Version: alacritty 0.5.0 (a6681e3)
Font Family: Fira Code
Font Style: Retina

**Comment by chrisduerr** [comment]
No it shouldn't. That's what the `glyph_offset` is for.

**Comment by ronakg** [comment]
Thanks!
