### ISSUE TITLE
Some escapes and unicode characters cause issues with drawing

### ISSUE THREAD

**Issue by K4rakara** [alacritty/alacritty#4147]
I'm not sure quite how to describe this, but some terminal escapes and Unicode characters cause issues with drawing.

In short: when using ZSH, if some characters are used, this happens when you use tab auto-complete:
![image](https://user-images.githubusercontent.com/40474474/90565147-68448b80-e174-11ea-9f9c-9af73af2229d.png)

In this case, the offending character/escape is "`\u{0x001b}[2m`", but I've also had issues with "「" and "」", among others.

In the case of the escape character, I might be wrong, but I think what might be happening is that when ZSH uses `\u{0x001b}[1A` to put the cursor back to its intended position, whatever calculations Alacritty does to figure out where to put the cursor don't realize that `\u{0x001b}[2m` is supposed to be zero-width, and as such, the cursor is further to the right than expected.

In the case of the unicode characters, I'm not quite sure whats going on. Maybe the unicode escape character is being counted when calculating the cursors position?

I might be completely wrong, 

OS: Linux
Version: alacritty 0.5.0
X11
DE: KDE
WM: KWin

**Comment by chrisduerr** [comment]
I don't see how \e[2m would affect anything like this. Can you share a reliable example to reproduce this? I've never seen anything like that in zsh. what's your `LANG`?

**Comment by K4rakara** [comment]
My `LANG` is `en_US.UTF-8`. 

If you use `oh-my-zsh`, you could try using `agnoster++.zsh-theme` from [this](https://github.com/K4rakara/agnosterpp-zsh-theme) repo of mine, the current version should reproduce the bug.

**Comment by chrisduerr** [comment]
> If you use oh-my-zsh, you could try using agnoster++.zsh-theme from this repo of mine, the current version should reproduce the bug.

I do not. Can you reproduce this in vanilla zsh? Also please state which distro you are using, just "Linux" could mean a lot of things.

**Comment by K4rakara** [comment]
Oh, sorry-- I'm using Manjaro Linux. After thinking about this more, this is probably a `oh-my-zsh` bug, not Alacritty.

**Comment by chrisduerr** [comment]
If you can find a way to reproduce without omz, please let me know.

**Comment by K4rakara** [comment]
I'm pretty confident this is an issue with oh-my-zsh, not alacritty. sorry for the confusion.
