### ISSUE TITLE
Uhhhhhhh I Have a problem installing alacritty 

### ISSUE THREAD

**Issue by Ohio2** [alacritty/alacritty#4149]
**As i said i have a problem installing alacritty.**
OS: Linux-5.7.15-xanmod, Kubuntu 20.04.01
Version: `alacritty --version` output
Linux: X11, KDE

**Comment by Ohio2** [comment]
oh and
https://i.imgur.com/7jG8sSF.png

**Comment by nixpulvis** [comment]
1. Perhaps consider avoiding "Uhhhhhhhhh" as the opening line for your issues.
2. Please do not post screenshots of your errors, the text should be given, ideally in a codeblock (for readability).
3. More to the point; Have you followed the [`INSTALL.md`](https://github.com/alacritty/alacritty/blob/master/INSTALL.md#debianubuntu) instructions? I suspect installing `libxcb-xfixes0-dev` as mentioned there should fix this issue for you.

**Comment by Ohio2** [comment]
Sorry.

**Comment by Ohio2** [comment]
And yes.
