### ISSUE TITLE
Alacritty sometimes clears clipboard upon exit

### ISSUE THREAD

**Issue by heroin-moose** [alacritty/alacritty#4150]
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

OS: Arch Linux
Version: alacritty 0.5.0
Linux/BSD: Wayland (sway v1.5)

### Logs

On Wayland alacritty clears clipboard if program was called via -e or exec:

```sh
$ wl-copy -c
$ wl-paste
No selection
$ cat /tmp/clipboard-test.sh
#!/bin/sh

printf clipboard-test | wl-copy
$ /tmp/clipboard-test.sh
$ wl-paste
clipboard-test
$ alacritty -e /tmp/clipboard-test.sh
$ wl-paste
No selection
```

It does not happen if I do this:

```sh
$ alacritty
... run /tmp/clipboard-test.sh in a new terminal ...
... exit from a new terminal ...
$ wl-paste
clipboard-test
```

**Comment by chrisduerr** [comment]
This is working as expected. Clipboard data is not preserved on Linux unless you run a clipboard manager.

**Comment by heroin-moose** [comment]
Could you please elaborate?. What's the difference between calling something with -e and typing wl-copy in the shell?

**Comment by chrisduerr** [comment]
I'm sorry, I think I misunderstood you a bit. But still, this is a problem with wl-clipboard not with Alacritty.

You can try running wl-copy in a shell or adding some sleep statements to delay process execution, but I'd just assume that the hacky way that wl-copy works probably has an issue with the quick shutdown of Alacritty.

**Comment by heroin-moose** [comment]
I've tried:

```
#!/bin/sh

printf clipboard-test | wl-copy
sleep 5
```
Running wl-paste in a second terminal shows clipboard-test right until the terminal executing this command (alacritty -e /tmp/clipboard-test.sh) dies. After that wl-paste gives me "No selection".

**Comment by chrisduerr** [comment]
> Running wl-paste in a second terminal shows "clipboard-test" right until the terminal executing this command (alacritty -e /tmp/clipboard-test.sh) dies. After that wl-paste gives me "No selection".

And that's not the case when you run Alacritty without the -e flag? Might be an environment thing.

**Comment by heroin-moose** [comment]
The only difference is SHLVL and ALACRITTY_LOG.

**Comment by heroin-moose** [comment]
Hm... I guess I know why. It is somehow related to the forks that wl-copy is doing behind the scene. You were right, nothing to do with alacritty, sorry for the noise.

**Comment by kchibisov** [comment]
Ah, I can repro, but I don't see us clearing the clipboard contents, maybe sway decides to do that for whatever reason? I know that you can set a selection with `set_selection`, but we're not doing so. You can verify that with `WAYLAND_DEBUG=1 alacritty 2> log.txt -e sh -c "unset WAYLAND_DEBUG;  printf clipboard-test | wl-copy; sleep 5"`

You won't see any `set_selection` in a log, which is what sets the selection. It actually happens with both `wl-clipboard` and `wl-clipboard-rs`, but I'm not sure who is it at fault here.

I see in a logs that selection became nil(in a one from alacritty and wl-clipboard`), but I don't see anyone doing so.

>You can try running wl-copy in a shell or adding some sleep statements to delay process execution, but I'd just assume that the hacky way that wl-copy works probably has an issue with the quick shutdown of Alacritty.

On sway `wl-clipboard` is working without hacks due to sway supporting data control protocol.

**Comment by chrisduerr** [comment]
> On sway wl-clipboard is working without hacks due to sway supporting data control protocol.

Good point, thanks for correcting me. Though I can't say anything about how it works under the hood.

> It is somehow related to the forks that wl-copy is doing behind the scene (-e kills all spawned processes, while closing terminal does not kill the remaining wl-copy fork).

That makes sense, thanks for letting us know.

**Comment by kchibisov** [comment]
But yeah, it has little to do with alacritty, since it happens with every other Wayland terminal I have on my system.
