### ISSUE TITLE
crash after nvidia driver install

### ISSUE THREAD

**Issue by TheWithz** [alacritty/alacritty#4153]
### System
OS: 5.8.1-gentoo-x86_64 AMD Ryzen 9 3900X 12-Core Processor AuthenticAMD GNU/Linux
Nvidia driver version 450.57
Alacritty version: 0.5.0
DE/WM: X11, i3 4.18.2

### Logs
> ~ $ alacritty -vv
> Created log file at "/tmp/Alacritty-22319.log"
> [2020-08-20 10:33:42.471391898] [INFO] Welcome to Alacritty
> [2020-08-20 10:33:42.471500321] [INFO] Configuration loaded from "/home/thewithz/.config/alacritty/alacritty.yml"
> [2020-08-20 10:33:42.476712245] [DEBUG] Estimated DPR: 1
> [2020-08-20 10:33:42.476735448] [DEBUG] Estimated Cell Size: 10 x 18
> [2020-08-20 10:33:42.476747190] [DEBUG] Estimated Dimensions: None
> [2020-08-20 10:33:42.521899590] [ERROR] Alacritty encountered an unrecoverable error:
>
>        Error creating GL context; Received multiple errors. Errors: `[OsError("eglInitialize failed"), OsError("GL context creation failed")]`

**Comment by kchibisov** [comment]
I'd suggest to try rebooting.

**Comment by TheWithz** [comment]
Rebooting yields no change in behavior.

**Comment by kchibisov** [comment]
Hm, maybe driver update somehow failed, can you run any other OpenGL application, like glxgears (comming from mesa demos package most of the time), though, those are not elg, but rather glx.

**Comment by TheWithz** [comment]
`~ $ USE="egl" emerge --ask mesa-progs`
> ~ $ glxgears
> Running synchronized to the vertical refresh. The framrate should be approximately the same as the monitor refresh rate.
> 302 frames in 5.0 seconds = 60.380 FPS
> ... etc
![gears](https://user-images.githubusercontent.com/8269545/90814478-26901e00-e2f7-11ea-860b-0062f248ae5f.png)

**Comment by kchibisov** [comment]
That's a bit strange that it's started failing only for use. Do previous driver works, I'd assume that you can easily check that on gentoo(gentoo like) system.

**Comment by TheWithz** [comment]
I was using nouveau previously, but I can check a previous version of the NVIDIA drivers.

**Comment by Tiggilyboo** [comment]
Have just upgraded my NVidia proprietary drivers to 450.80.02 from 440.x, using git revision `a6681e3a088f4842d1a1391c5ea6af19934cd12d` (tag 0.5.0), and am now getting the same issue:

```bash
alacritty -vv
Created log file at "/tmp/Alacritty-30854.log"
[2020-10-15 17:39:36.968907771] [INFO] Welcome to Alacritty
[2020-10-15 17:39:36.968994110] [INFO] Configuration loaded from "/home/simon/.config/alacritty/alacritty.yml"
[2020-10-15 17:39:36.980619216] [DEBUG] Estimated DPR: 1
[2020-10-15 17:39:36.980650837] [DEBUG] Estimated Cell Size: 8 x 16
[2020-10-15 17:39:36.980660207] [DEBUG] Estimated Dimensions: None
[2020-10-15 17:39:37.044439762] [ERROR] Alacritty encountered an unrecoverable error:

	Error creating GL context; Received multiple errors. Errors: `[OsError("eglInitialize failed"), OsError("Couldn\'t find any available vsync extension")]`
```

This is on Ubuntu `uname -a`
```Linux crate 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux```

**glxinfo -B**
```
name of display: :1
display: :1  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: VMware, Inc. (0xffffffff)
    Device: llvmpipe (LLVM 10.0.0, 256 bits) (0xffffffff)
    Version: 20.0.8
    Accelerated: no
    Video memory: 7900MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 3.3
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: llvmpipe (LLVM 10.0.0, 256 bits)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 20.0.8
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.1 Mesa 20.0.8
OpenGL shading language version string: 1.40
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 20.0.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
```

**Comment by kchibisov** [comment]
I'm not sure that mesa is helpful here, and I bet you can't have mesa and nvidia drivers at the same time? Since glxinfo reports that you're using software rendering via llvmpipe.

Try rebooting after nvidia update, idk....

**Comment by TheWithz** [comment]
With nvidia driver version 455.28
and Linux kernel 5.9.1-gentoo-x86_64
Alacritty no longer crashes.
