### ISSUE TITLE
[ZSH] Line break clean the previous line

### ISSUE THREAD

**Issue by edufcarvalho** [alacritty/alacritty#4154]
### System

OS: Arch Linux;
Version: Alacritty 0.5.0;
DE: Cinnamon;
Windows: Line(33) x Column(88).

### Logs

Crashes: STDERR, STDOUT;
Font/Terminal size: [output2.txt](https://github.com/alacritty/alacritty/files/5105156/output2.txt);
Keyboard and bindings: [output.txt](https://github.com/alacritty/alacritty/files/5105144/output.txt).

### Bug description

When the command reach the line breaking point, the previous line just disappear. The problem get solved when the window is resized (the line reappears) and everything get normal again, if I continue typing while line-break a 2nd time, the problem get back.

Obs.: This behavior is not repeated in other terminals (Kitty, st, Xterm and Hyper).

#### Before line breaking:
![Screenshot from 2020-08-20 16-34-27](https://user-images.githubusercontent.com/61642210/90817239-dff4f080-e303-11ea-9369-7c4d81c2e8a4.png)

#### After line breaking/Before resizing:
![Screenshot from 2020-08-20 16-34-55](https://user-images.githubusercontent.com/61642210/90817314-031fa000-e304-11ea-9663-39aae2bcc7d7.png)

#### After resizing:
![Screenshot from 2020-08-20 16-39-46](https://user-images.githubusercontent.com/61642210/90817327-07e45400-e304-11ea-9224-a10337dd66d7.png)

**Comment by edufcarvalho** [comment]
I think this is a problem with ZSH or something, I change the shell to bash and everything worked normally

**Comment by kchibisov** [comment]
Could you set scrolling history to 0 in a config file, and do `alacritty -vvv --ref-test` and repro your issue? it should generate 4 files, 3 json files you can delete, but the alacritty.recording one should post here. Also share information about window. Also, provide an output of `-vvv`.

Also, it'll be nice if you ensure that issue is getting triggered once you've done recording in a terminal with the same dimensions if you `cat alacritty.recording`.

I can't repro that issue myself with zsh, but it'll be nice to see what it's actually trying to do.

**Comment by edufcarvalho** [comment]
I was using Starshipt (a rust cross-shell prompt), i unnactivated this and the line-break didin't do anything wrong. It's possibly a problem with it.

![Screenshot from 2020-08-20 17-10-06](https://user-images.githubusercontent.com/61642210/90820607-01f07200-e308-11ea-9ed8-ff3a89909fb9.png)

**Comment by edufcarvalho** [comment]
I repeated the command with same dimensions in Kitty and xterm and nothing wrong happens, but if I use bash, or pure ZSH (without Starship) with Alacritty, anything happens again. I think it's a compatibility problem or something between Starship and Alacritty.

**Comment by edufcarvalho** [comment]
I changed the Starship configurations and everything worked well, thanks for the support, and sorry about the bad troubleshooting.

**Comment by kchibisov** [comment]
Could you share the starship configuration and version you've been using so I can try to repro, I'm really interested on what's happened here so the line got disappeared only in alacritty?

**Comment by edufcarvalho** [comment]
Yes, the line got disappeared only in alacritty. I'm going to upload my alacritty and starship configuration files

**Comment by edufcarvalho** [comment]
[alacritty.txt](https://github.com/alacritty/alacritty/files/5105338/alacritty.txt) (TOML)
[starship.txt](https://github.com/alacritty/alacritty/files/5105347/starship.txt) (YML)
