### ISSUE TITLE
Support Path/Env Expansion in Config File(s)

### ISSUE THREAD

**Issue by nixpulvis** [alacritty/alacritty#4157]
Now that #4138 has landed, the need to write things like `~/.config/alacritty/colors.yml` (or `$HOME`) is desired. Ideally this expansion would happen for all other paths (or strings) in the config file.

Furthermore, for paths, it would be nice to allow glob imports like `~/.config/alacritty/bindings/*.yml`, which could allow easy organization of various settings from a directory. However, this feature is much less needed than simple `~` or ENV variables.

**Comment by gempir** [comment]
I think it should not work with environment values, because there are to many potential problems there and confusing behaviour to the user.

But there should be a way to reference the home directory. Using `~` would probably least confusing for users and what most would expect to work.

**Comment by EdenEast** [comment]
Paths beginning with `~` or `~/` depending on if you want to support the `~undeadleech/alacritty.yml` case should be
expanded to HOME based:

- `HOME` env variable (they might have defined something different then standard)
- Fallback to platforms define defaults: (`dirs::home_dir()`)
  - Linux:   `/home/{username}`
  - Mac:     `/Users/{username}`
  - Windows: `C:\Users\{Username}`

If a user like me that works on multiple machine and multiple platforms (linux, windows), this would allow for one
alacritty config to be in all cases. The documentation for import would explain to user the order of expansion for `~`.

**Comment by EdenEast** [comment]
Another solution to @nixpulvis problem would be to support relative paths for the import section. Paths would be relative to the file they are defined in. 

For example, you are using the default configuration location `XDG_CONFIG_HOME/alacritty`. You have broken up your configuration into categories. You directory structure might look something like this:

```
.config/alacritty ➜ tree .
.
|-- alacritty.yml
|-- config
    |-- functional.yml
    |-- input.yml
    |-- theme.yml
    `-- visual.yml
````

In your entry point of your configuration your import section would look something like this:

```yml
imports:
  - config/functional.yml
  - config/input.yml
  - config/theme.yml
  - config/visual.yml
```

As these are relative paths they are relative to the entry file that they were defined in (`~/.config/alacritity/alacritty.yml`) in this example.

@nixpulvis would this help in the mean time while Path/Env expansion is figured out. @chrisduerr your thoughts as well? Also would this be a separate issue?

**Comment by chrisduerr** [comment]
> @nixpulvis would this help in the mean time while Path/Env expansion is figured out. @chrisduerr your thoughts as well? Also would this be a separate issue?

No it would not. This is just as much work as any other solution and doesn't solve the problem that usernames and host directories might be in different places for different users.

**Comment by chrisduerr** [comment]
Also relative paths are just a poor idea in general I'd say. It always raises the question relative to what they are. The config file? The working directory? The canonicalized file path?

**Comment by gempir** [comment]
Is there something I'm missing? The Feature in 07cfe8b does not work for me. I'm on release 0.6.0 and whatever file I try to import 

like `~/test.yml` it keeps erroring with 
```
ERROR] [alacritty_config] Unable to import config "~/test.yml": Unable to locate config file
```

**Comment by gempir** [comment]
Am I missing something? I'm running `alacritty 0.6.0` (04cbf767) but can't get the feature from 07cfe8b working correctly. 

```
import:
  - ~/test.yml
```

Keeps erroring out with 

```
[ERROR] [alacritty_config] Unable to import config "~/test.yml": Unable to locate config file
```

**Comment by kchibisov** [comment]
Because it's not a part of 0.6.0 release.

**Comment by gempir** [comment]
Oh okay. I thought because the release was 11 days ago it would include something from 13 days ago. Still hard for me to understand when what is included in which release.

**Comment by ric2work** [comment]
Hi  all ,

May I follow up with u later i woke from rest 
I just done my work ..
TT 

Thanks
