### ISSUE TITLE
Import config files from home dir or relative

### ISSUE THREAD

**Issue by gempir** [alacritty/alacritty#4164]
I love the addition of importing config files in 3c3e6870dedad56b270f5b65ea57d5a6e46b1de6
Now i can finally split up OS specific configs easily. 

The issue still is I can't find a way to import from the home directory or relative.
I tried using 

- $HOME
- ~/

Is there something I'm missing or is that feature just not supported yet, since this did whole feature just came to master.

### System

OS: Ubuntu 20.04 / macOS 10.15.6
Version: alacritty 0.6.0-dev (6cfcd7c)
Linux/BSD: X11 + i3 on Ubuntu

Edit:

I found out `.config/alacritty/myfile.yml` is working. So without any prefix it always starts in the home directory. Is that always going to stay like that or should it be possible to make it absolute?

**Comment by enizor** [comment]
See #4157. For short: the implementation does not support expansion yet, and it may not be desirable.

**Comment by chrisduerr** [comment]
> I found out .config/alacritty/myfile.yml is working. So without any prefix it always starts in the home directory. Is that always going to stay like that or should it be possible to make it absolute?

This is not true, the path is simply relative to where you started Alacritty. That's not going to change, but it is not reliable either.
