### ISSUE TITLE
`clear` Command doesn't understand alacritty's terminal type during ssh session

### ISSUE THREAD

**Issue by Zakgeki** [alacritty/alacritty#4168]
I'm using `ssh` to log into my school's linux server remotely. I went to clear the terminal screen with `clear` and I get this as output. 

```
user@host:~$ clear
'alacritty': unknown terminal type.
```
I'm not sure what would cause this or even what to google to fix this. Any insight would be appreciated, thanks!

### System

OS: Linux (Guest: Manjaro, Host: Ubuntu)
Version: 0.5.0

**Comment by Zakgeki** [comment]
I should have read better, I can just modify the `term` variable to be `xterm-256color`.

**Comment by nixpulvis** [comment]
@Zakgeki you may also be able to install the `alacritty` terminfo on the remote system.
