### ISSUE TITLE
Feature request: place text in the pasteboard using escape codes

### ISSUE THREAD

**Issue by dxlr8r** [alacritty/alacritty#4173]
One of the most useful features of iTerm2 IMO: 

> 
> #### Copy to Pasteboard
> 
> You can place a string in the system's pasteboard with this sequence:
> 
> ```
> ^[]1337;Copy=:base64^G
> ```
> 
> Where base64 is the base64-encoded string to copy to the pasteboard.

This would enable the pasteboard to be accessable through one or more layers of jump hosts (ssh).

**Comment by kchibisov** [comment]
Use standard escape sequences instead of custom iterm things.

The standard escape is OSC 52

https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands

Can use it via

That's for copy.

```
printf "\033]52;;$(echo -n blabla | base64)\a"
```

**Comment by brycefisher** [comment]
I wasn't sure how to set this up myself, until I found these options:
 * https://github.com/ojroques/vim-oscyank -- vim plugin
 * https://sunaku.github.io/tmux-yank-osc52.html -- tmux solution
