### ISSUE TITLE
Building latest release on ubuntu 20.04 fails

### ISSUE THREAD

**Issue by Zomatree** [alacritty/alacritty#4180]
when trying to build the latest release on ubuntu it fails when compiling c

### System

OS: Linux
Version: 0.5.0
Linux: X11 and KDE

### Logs
https://gist.github.com/Zomatree/13da24377d1fc7b7c74428f1ab5bf51a

**Comment by kchibisov** [comment]
Install dependencies  https://github.com/alacritty/alacritty/blob/master/INSTALL.md#debianubuntu
