### ISSUE TITLE
Unable to paste into search

### ISSUE THREAD

**Issue by ajeetdsouza** [alacritty/alacritty#4181]
The Search feature (Ctrl+Shift+F) is pretty great, but I'm unable to paste into the search bar using the regular Ctrl+Shift+V shortcut.

**Comment by kchibisov** [comment]
Duplicate of #4181.

It was intentionally implemented that way, but I guess we can support at least paste into it.

**Comment by ajeetdsouza** [comment]
My bad. Thanks!

You linked back to the same issue, I think you meant https://github.com/alacritty/alacritty/issues/4176.

**Comment by kchibisov** [comment]
Yeah, that issue, thx.
