### ISSUE TITLE
Dimension issues when starting with Startx

### ISSUE THREAD

**Issue by b3nsh4** [alacritty/alacritty#4184]
used to start Alacritty with startx. Problem is , Alacritty is not filling the screen. Solved it by adding dimension flag; `startx /usr/bin/alacritty -d 150 41` . This almost fills the screen. But, 41 is somewhat less columns. What I wanted is 41.4 so that I could fill in blank screen at bottom. We cannot specify point values "41.4" as dimension, it's falling back to default square dimension. So, I believe there's not much X-server can do about this. I believe it's some trick within Alacritty to make ` "150 41.4" ` dimension.

**Comment by chrisduerr** [comment]
Why are you not running a window manager?

**Comment by kchibisov** [comment]
I feel like the thing you want is to specify window geometry in pixel size? We don't have that option and I'm not sure how it's useful tbqh, knowing that we have one to specify size in window size already( cols/lines).

**Comment by bensh4** [comment]
> I feel like the thing you want is to specify window geometry in pixel size? We don't have that option and I'm not sure how it's useful tbqh, knowing that we have one to specify size in window size already( cols/lines).

I understand you, I passed real resolution of my screen (1920 1080). But, this creates big overflow of screen. We couldn't see chars at screen if we pass 151 and any chars above 41 (bottom). For a 1920x1080 screen, 151 41.4 is the best size if starting from xinitrc

**Comment by nixpulvis** [comment]
I actually think starting alacritty directly from `startx` seems like a perfectly reasonable thing to want to do. However in my test of this, in addition to the size not fitting the screen, no inputs seemed to be processed, making the terminal unusable.

**Comment by chrisduerr** [comment]
This is not a usecase of Alacritty worthwhile to support. If you require window management I recommend running something simple like cage (the Wayland kiosk compositor).
