### ISSUE TITLE
PowerShell opens when launching alacritty

### ISSUE THREAD

**Issue by borup3** [alacritty/alacritty#4186]
I've downloaded alacritty for Windows 10 and when I launch it, it launches PowerShell, and I can't interact with alacritty. When I close PowerShell, alacritty also closes.

Uhm?

**Comment by chrisduerr** [comment]
What do you mean you can't interact with Alacritty? Powershell should open, that's the default shell on Windows.

**Comment by borup3** [comment]
This is what I mean.
![hm](https://user-images.githubusercontent.com/5133404/91774418-b87d0e00-ebb6-11ea-9736-9d5cb24af541.gif)

**Comment by chrisduerr** [comment]
Which Windows version are you on? Have you messed with your system configuration?

**Comment by borup3** [comment]
> Have you messed with your system configuration?
This made me wonder if I'd enabled the "legacy console mode" in cmd.exe and indeed I had. Interestingly, turning this off fixed the problen and alacritty now works as expected.

![oO38X3spRIWf90cC2PrBlA](https://user-images.githubusercontent.com/5133404/91781303-f7678f80-ebc7-11ea-8275-831cf5f2ebe5.png)

**Comment by chrisduerr** [comment]
Sounds like that's the problem then.

**Comment by borup3** [comment]
You might want to add that to the readme for Windows users. I had it turned off because another terminal emulator required it at one point in time.
