### ISSUE TITLE
PTY not read entirely with --hold CLI parameter

### ISSUE THREAD

**Issue by Squirreljetpack** [alacritty/alacritty#4189]
~~Running `alacritty --hold -e bash -c 'column -s, -t < weather.csv'` does not print anything. `alacritty --hold -e bash -c 'ping google.com'` works. The column command in a normal window works. But the column command doesn't seem to work when launched with `alacritty --hold -e bash -c'...`.~~

~~It used to work but recently I found it seems to have broken. Now the window is just blank.~~

When running a command at startup and passing the `--hold` option, the PTY is not always read entirely. Commands like `alacritty --hold -e echo test` often do not print the text written to the PTY. Adding a little `sleep` fixes the problem, so it's likely a problem with the PTY being dropped before it is read entirely since usually without the `--hold` option it's not important to read all of it.

**Comment by chrisduerr** [comment]
@Squirreljetpack You said it used to work, can you check where exactly this broke? The `--hold` command is fairly "new", so I'm a bit surprised it ever worked.

**Comment by nixpulvis** [comment]
I can confirm I can reproduce this issue on my Linux machine, but not on macOS. The issue is somewhat intermittent however.

**Comment by chrisduerr** [comment]
I believe the issue is due to the PTY not being drained after shutting down, which is usually not necessary since the window just closes. But that's why I'm curious if it worked previously, since that hasn't changed.

**Comment by Squirreljetpack** [comment]
I cannot recall when exactly I last tried this as it has been a while. it cannot be too long ago - definitely it was working 2 months ago I think.

**Comment by chrisduerr** [comment]
Can you try a version from 2+ months ago then?

**Comment by kchibisov** [comment]
I can reproduce this issue on `v0.4.0`, so it's broken likely from the addition of that feature. It could be worked around by adding delay before printing something like `alacritty --hold -e sh -c "sleep 1; echo hello"`. And I'd except that issue to be from the addition (or close to it), since the parser and event loop communication haven't changed for quite a long time.

**Comment by chrisduerr** [comment]
Yeah, I think there's just a bit of confusion present here. So I think this issue should just be used for a general `--hold` PTY issue. The whole regression thing should probably be ignored. The column command also seems unrelated.
