### ISSUE TITLE
Alacritty does not pick all parts of config file

### ISSUE THREAD

**Issue by adgai19** [alacritty/alacritty#4191]
Alacritty does not pick up default shell program after changing font.
### System

OS:  ubuntu 20.04
Version:  alacritty 0.6.0-dev
Linux/BSD: X11, i3 with compton

### Logs

Font/Terminal size: default- Inconsoleta, after- Fira code
Keyboard and bindings: https://pastebin.com/w2d05VFU

final config file: https://pastebin.com/Gbb2gZeW
initial config file: https://pastebin.com/AZYcK2An

**Comment by chrisduerr** [comment]
The indentation of your configuration file is completely messed up, that's why nothing is working. You need to keep the indentation unchanged from the original.
