### ISSUE TITLE
braille not rendering properly 

### ISSUE THREAD

**Issue by Titaniumtown** [alacritty/alacritty#4192]
## System
OS: Linux
Version: alacritty 0.5.0
Linux/BSD: X11, Gnome

Braille doesn't display properly in tools like ytop and bottom. 
![Screenshot from 2020-08-31 14-38-58](https://user-images.githubusercontent.com/11786225/91754646-c8392a00-eb97-11ea-9e11-be467dbb0418.png)

**Comment by kchibisov** [comment]
Looks like a braille from your font, I don't see anything wrong with it?

**Comment by Titaniumtown** [comment]
It should be a singular dot. On gnome-terminal the issue isn't there. 
![image](https://user-images.githubusercontent.com/11786225/91757206-f28ce680-eb9b-11ea-9239-4be588afa166.png)

**Comment by Titaniumtown** [comment]
Ok, so I followed https://www.reddit.com/r/archlinux/comments/gf2vgb/the_braille_fonts_dont_show_properly_anywhere/ 

> Install a font like ttf-symbola and if you have gnu-free-fonts installed, remove it

and it works. Strange the issue is only on alacritty.

**Comment by kchibisov** [comment]
Alacritty is using **your** font, gnome-terminal as well as some other terminals are **not** doing so, instead they do render their builtin artificial font when facing those glyphs, line drawing glyphs, etc, meaning that there's no way you can ever see those glyphs from any font you're using.
