### ISSUE TITLE
Feature: A way to replace Logo and Ctrl keys for all input on Linux

### ISSUE THREAD

**Issue by mitar** [alacritty/alacritty#4193]
I am trying to configure my Ubuntu 20.04 Linux Gnome shell to behave similar to how Mac behaves about keyboard shortcuts: super key should be used for all UI keyboard shortcuts (like copying to the clipboard), while ctrl should be used for the terminal emulators, for example for ctrl-c. [See this post for more information about my setup](https://unix.stackexchange.com/questions/607113/how-to-configure-the-keyboard-to-behave-like-macs). The issue I am having is that for things to work this way, I change modifier keys system-wide and would need for terminal emulators to have different modifier keys, in particular, logo and ctrl keys should be swapped. Looking around it seems this is not really possible, unless the terminal emulator itself does the swapping. I have managed to patch Gnome Terminal to behave like this by simplify swapping modifiers on the input, but for Alacritty I was unable to find a way to do so, so I am opening an issue to see if a) this is something somebody else would know how to do b) this is something others would also find useful and would be something we add to the Alacritty itself.

So what is needed is to swap Logo and Ctrl keys around for all inputs. This is easy for key presses as I can just swap them around in `modifiers_input`:

```rust
        let mut modifiers = modifiers.clone();
        if modifiers.ctrl() != modifiers.logo() {
            modifiers.toggle(ModifiersState::LOGO);
            modifiers.toggle(ModifiersState::CTRL);
        }
        *self.ctx.modifiers() = modifiers;
```

But the problem is in `received_char` because winit calls [`wt.xconn.lookup_utf8`](https://docs.rs/winit/0.22.2/src/winit/platform_impl/linux/x11/event_processor.rs.html#597) to obtain the character pressed, which in turn [modifies it to control codes if `ctrl` was pressed during that time](https://github.com/mirror/libX11/blob/fb65b67169105c82c243f265e0f993cf72efdacd/src/KeyBind.c#L867-L874). But that is the wrong `ctrl` and not swapped. So I tried to reverse this change and obtain the original character, but there is not enough information available to do that well, to my understanding. So I am stuck here.

**Comment by chrisduerr** [comment]
There is https://github.com/alacritty/alacritty/issues/62 which will solve this for macOS, since the modifiers on macOS are completely backwards and broken. However I don't expect it to make much of a difference on Linux.

It sounds to me like you've just put yourself in a bad spot by trying to make something happen that isn't supported. So you really want to fight that uphill battle, you're gonna have to do it on your own.

**Comment by kchibisov** [comment]
Well, if the goal is to add `Super + C/V` into alacritty, you're free to do that via adding bindings with super and removing the default copy ones, by using `ReceviedChar` for those. You can swap default modifiers for other keys if you don't wan to.

FYI the things like ctrl + y are still ctrl + y on macOS, so the only thing that you want to swap is some shortcuts which you already can do.

The thing is that you can't do something that simple with the rest of the apps on linux, like gtk, so using `Super + c` for copy in those is nearly impossible without source patching iirc.

**Comment by mitar** [comment]
I found a much simpler way to do this, and made a PR for a small change to enable it: https://github.com/alacritty/alacritty/pull/4195
