### ISSUE TITLE
No way to configure key shortcuts to move between search results outside of vi mode

### ISSUE THREAD

**Issue by mitar** [alacritty/alacritty#4200]
It seems that when I invoke `SearchForward` action, outside of vi mode, and I enter a regex, then:
* Invoking `SearchForward` again does not move between search results.
* I can move by pressing `enter` in forward direction, or `shift`+`enter` to move in backward direction.
* Trying to configure a key shortcut for `SearchNext` or `SearchPrevious` fails because I am trying to use it outside of vi mode.

So it seems there is no way to configure that `command-g` would be used for to go to the next search result. I have to use `enter`?

**Comment by nixpulvis** [comment]
Yep, getting the following error message with this config line: `  - { key: G, mods: Control, action: SearchNext }`.

```
[2020-09-01 22:23:20.221139645] [ERROR] [alacritty_config] Problem with config: action `SearchNext` is only available in vi mode, try adding `mode: Vi`; ignoring binding
```

**Comment by chrisduerr** [comment]
Correct, see https://github.com/alacritty/alacritty/issues/4176 for allowing to rebind these search actions.
