### ISSUE TITLE
Feature: Allowing mouse selection during search (not in Vi mode)

### ISSUE THREAD

**Issue by mitar** [alacritty/alacritty#4201]
One thing I often do when searching in a terminal emulator is to search for something and then use mouse to select the area around it and copy it out. This does not seem to be possible in Alacritty. When search results are shown, it does not seem to be possible to select and copy out parts of the shown screen.

**Comment by nixpulvis** [comment]
I also noticed this, and would consider it a bug.

**Comment by kchibisov** [comment]
it's not a bug, when you're doing search without `Vi` mode you already have selection and it's a current match. in `Vi` mode you can select, since the cursor is used as indication for current match.

**Comment by chrisduerr** [comment]
If you want to play with selection and search at the same time, you should be using vi mode. While I generally wouldn't be opposed to making this possible, approaches for doing so just aren't worth it when you can just go straight to vi mode search instead. For search without vi mode it's much nicer to just have the match selected and then get out of selection once you're where you want to be, introducing two different selections during that just seems unnecessary.

**Comment by mitar** [comment]
There is no need to have two different selections. Simply, search makes a selection. And then you can replace it with another, copy it away, and continue search, which then finds and makes the next selection.
