### ISSUE TITLE
Support single line height terminals

### ISSUE THREAD

**Issue by ii41** [alacritty/alacritty#4207]
When the following conditions are met, the last line is not shown, what's shown instead is the line above it:
1. The line number is set to be 1 via either the `window/dimensions/lines` option in the config file or the `--dimensions` command line option.
2. The position is set to be a non-default value via either the `window/position` options or the `--position` command line option.
3. More than one lines have been printed to the terminal.

You should be able to reproduce this by doing the following:
```
alacritty --dimensions 20 1 --position 1 0 -e ./a.sh
```
`./a.sh`:
```
#!/bin/sh
printf "123\n456\n789"
sleep 10
```
One would expect `789` to be shown in the terminal window, but what's actually shown is `456`.

OS: Arch Linux
Version: 0.5.0 (and 0.4.3 does not have this issue)
Linux/BSD: X11, bspwm

I think this is probably caused by this:

https://github.com/alacritty/alacritty/blob/1bf40a8cc77d9082dfb76e028e0f66af88d79958/alacritty_terminal/src/term/mod.rs#L44

For some reasons, the minimal column/line number of the internal representation of the terminal (`Term`) is set to be 2.

This minimum size is not considered when a `Term` is constructed, but only used when it's resized. Actually except for `Term<_>::resize` I don't think this limit is used anywhere. I think the reason why this problem only occurs when a non-default position is set is probably because of this: I assume setting the position will trigger an "update", and the "update" will cause the `Term` to resize, even to its original size.

I think this can be fixed simply by stop using the minimum size. I can create a PR myself for that. Is there a reason why we want the minimum terminal size to be 2?

**Comment by kchibisov** [comment]
The width must be `2`, but the height could be `1`. The width of `2` is required, since you won't be able to display 2 width chars in particular, but I'm not sure if height of `1` could break something?

**Comment by ii41** [comment]
> The width must be `2`, but the height could be `1`. The width of `2` is required, since you won't be able to display 2 width chars in particular, but I'm not sure if height of `1` could break something?

Not sure what would happen if we print a 2 width char when the width is set to be 1. I guess it's acceptable to not display the char or to display only half of it?

Since it's not documented that width/height cannot be lowed than 2, I think this is a case that should be handled better somehow.

**Comment by kchibisov** [comment]
If you print 2 wide chars it'll wrap, the point is that when you have only one cell, but you must print wide char, which takes 2 cells. In general, I'd like to limit the terminal size to 2 cells width and 1 cell height. Unless @chrisduerr knows the reason why we have 2 for height as well.

Also, we should set min inner size for a window on resize as well to reflect the fact that we require 2x1 dimensions. The check isn't done upon creation in some cases is certainly a bug.

So the solution could be to expose `MIN_HEIGHT` and `MIN_WIDTH` and also perform `set_min_inner_size` with proper sizes calculated from those variables + the user defined padding.

**Comment by ii41** [comment]
> If you print 2 wide chars it'll wrap, the point is that when you have only one cell, but you must print wide char, which takes 2 cells. In general, I'd like to limit the terminal size to 2 cells width and 1 cell height. Unless @chrisduerr knows the reason why we have 2 for height as well.
> 
> Also, we should set min inner size for a window on resize as well to reflect the fact that we require 2x1 dimensions. The check isn't done upon creation in some cases is certainly a bug.
> 
> So the solution could be to expose `MIN_HEIGHT` and `MIN_WIDTH` and also perform `set_min_inner_size` (on a winit window in alacritty in 2 cases: window creation and font change)) with proper sizes calculated from those variables + the user defined padding.

Tried printing a wide char with MIN_SIZE set to be 1. Agreed that we should have term to be at lease 2x1. Not sure whether display size should also be 2x1. I think a display with only one column and displays only half of wide chars is also acceptable, maybe better, so that when a user, for whatever reasons, sets the col number to be 1, they get what they want, instead of having to think of the existence of wide chars to realize there's a limit.

**Comment by kchibisov** [comment]
>Tried printing a wide char with MIN_SIZE set to be 1. Agreed that we should have term to be at lease 2x1. Not sure whether display size should also be 2x1. I think a display with only one column and displays only half of wide chars is also acceptable, maybe better, so that when a user, for whatever reasons, sets the col number to be 1, they get what they want, instead of having to think of the existence of wide chars to realize there's a limit.

The thing is that it'll go dsynced for normal chars, since your window is smaller than PTY size, meaning that some chars will be offscreen and you won't be able to ever look at them. So limiting the window size as well is fine and on most systems you have minimal window size larger than 2 * cell.width x 1 * cell.height tbqh.

**Comment by chrisduerr** [comment]
Why does this need to be changed? It's working exactly as intended. The minimum supported size is 2x2.

**Comment by kchibisov** [comment]
The point is that Nx1 dimensions are absolutely fine and I see a use case for that, like 'status bar' wrapped in some application that actually position you like a status bar.

So, I'm in favor to change height to 2x1.

If you don't want to change that we should still restrict dimensions to be at least 2, otherwise user can create a terminal with size of 1x1, since the check is being performed on resize of the window, which in some cases could never happen unless user initiate it.

The other minor thing is about setting min inner size, so the window will be at least to contain our min size, whether it's 2x2 or 2x1.

Does it make sense?

**Comment by ii41** [comment]
> > Tried printing a wide char with MIN_SIZE set to be 1. Agreed that we should have term to be at lease 2x1. Not sure whether display size should also be 2x1. I think a display with only one column and displays only half of wide chars is also acceptable, maybe better, so that when a user, for whatever reasons, sets the col number to be 1, they get what they want, instead of having to think of the existence of wide chars to realize there's a limit.
> 
> The thing is that it'll go dsynced for normal chars, since your window is smaller than PTY size, meaning that some chars will be offscreen and you won't be able to ever look at them. So limiting the window size as well is fine and on most systems you have minimal window size larger than 2 * cell.width x 1 * cell.height tbqh.

Makes sense.

**Comment by ii41** [comment]
> Why does this need to be changed? It's working exactly as intended. The minimum supported size is 2x2.

Actually just as @kchibisov said I've been using alacritty as a status bar. Setting the line number to be 1 has been working, and I don't remember seeing in any user-facing document that the minimum supported size is 2x2. It's quite a surprise for me.

**Comment by chrisduerr** [comment]
I don't think any of our code relies on the height being at least two, the width certainly must be at least two. Though if someone wants to change it, they should definitely verify that there aren't any edge cases with stuff like selection/line wrapping/reflow.

Generally the 2x2 limit was mostly due to the minimum 2 width requirement, so a minimum height of 1 should work fine.

**Comment by ii41** [comment]
FYI I'm working on a PR for this. Also I realized that a wide char actually only occupies one cell (the other cell is occupied by a `WIDE_CHAR_SPACER`), so we can fairly easily support 1xN in both term and display by not using this `WIDE_CHAR_SPACER`when cols is 1. When doing this only the left half of a wide char will be displayed. This already works on my machine. I'm now checking and testing for edge cases so that this doesn't break things.

**Comment by chrisduerr** [comment]
> Therefore I'm working towards supporting 1x1 so that we have one fewer surprise case.

Do not do that. We must not go below 1x2.

**Comment by ii41** [comment]
> > Therefore I'm working towards supporting 1x1 so that we have one fewer surprise case.
> 
> Do not do that. We must not go below 1x2.

Why? I don't see a reason why we shouldn't support one more case when it's easy enough.

**Comment by chrisduerr** [comment]
It's not easy enough, there is a lot of code that will be made much more complicated with 1x1 grids.

**Comment by ii41** [comment]
Thought about it a little bit more. Yeah that's true. That's a case that needs special handling in quite a few places. Okay I'll start working towards 2x1.
