### ISSUE TITLE
How to bind '{' Braceleft and '}' Braceright in vimode

### ISSUE THREAD

**Issue by ms747** [alacritty/alacritty#4210]
I tried adding the following to alacritty config but it does not work.
` - { key: LBracket, mods: Shift, mode: Vi, action: ScrollPageUp }`

But this works just fine with or without any combination of mods excluding the `Shift` mod.
` - { key: LBracket, mods: Alt, mode: Vi, action: ScrollPageUp }`

Being a vim user it is convenient to scroll using `Shift + [ ]`.

**Comment by chrisduerr** [comment]
If you check the output of `alacritty --print-events | grep "WindowEvent.*KeyboardInput"` it should show you which key you need to specify (check for `virtual_keycode`). If the `virtual_keycode` is not present, you can still just specify the `scancode` directly.

**Comment by ms747** [comment]
Thanks a lot. Works. Maybe should've read the comments.
