### ISSUE TITLE
Instantly crashes, segmentation fault

### ISSUE THREAD

**Issue by TomSchammo** [alacritty/alacritty#4213]
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

Just installed alacritty from the snap store and it instantly crashes.

### System

OS: Linux/
Version: 0.2.0
Linux/BSD: Mint Cinnamon

### Logs

Crashes: "Segmentation fault (core dumped)"
Font/Terminal size: not shown, it only says that it loaded the configuration from "~/snap/alacritty/9/alacritty/alacritty.yml" and then it crashes
Keyboard and bindings: not shown either, although it's all standard, just installed it, didn't change anything yet.

**Comment by kchibisov** [comment]
snap version isn't provided by us, and the alacritty version you're using is quite old.

Try some newer version from at least recent year, like 0.4.2.

**Comment by TomSchammo** [comment]
Alright, thanks, will do

**Comment by TomSchammo** [comment]
Just compiled it from source, seems to work like a charm. Thanks again!
