### ISSUE TITLE
Alacritty opens stdin, stdout, and stderr in append mode

### ISSUE THREAD

**Issue by aslatter** [alacritty/alacritty#4214]
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

OS: Linux (Ubuntu 20.04)
Version: alacritty 0.6.0-dev (built from 1bf40a8)
Linux/BSD: X11, Gnome
Windows: N/A

### Logs

I'm not sure if this is exactly a bug, but it surprised me that when I run programs in Alacritty *stdin*, *stdout*, and *stderr* are open in append-mode. This is not true for xterm and gnome-terminal.

Example program:

```c
#include <fcntl.h>
#include <stdbool.h>
#include <stdio.h>

void print_is_append(int fd);

int main() {
  print_is_append(0);
  print_is_append(1);
  print_is_append(2);
}

void print_is_append(int fd) {
  int mode = fcntl(fd, F_GETFL);
  const char *is_append = (mode > 0 && mode & O_APPEND) ? "true" : "false";
  printf("File %d is in append mode: %s\n", fd, is_append);
}
```

Invocation:

```bash
tcc -run src/demo.c
```

(or use your favorite C compiler)

Output from Alacritty:

```
File 0 is in append mode: true
File 1 is in append mode: true
File 2 is in append mode: true
```

Output in other terminal emulators I have handy (xterm, gnome-terminal, the integrated terminal in VS Code):

```
File 0 is in append mode: false
File 1 is in append mode: false
File 2 is in append mode: false
```

**Comment by chrisduerr** [comment]
What do you mean by running programs in Alacritty? Are you talking about running programs as shell, or inside of the shell?

**Comment by kchibisov** [comment]
For me those are both `false` in alacritty and in other terminals. Not sure how to repro.

**Comment by chrisduerr** [comment]
The stdout/stdin/stderr of a program running inside of the shell of Alacritty is more related to the shell anyways.

**Comment by aslatter** [comment]
I meant launching Alacritty (from the Gnome shell) and then running the example C program. I'd assumed that Alacritty was in control of the file-mode of the PTY "slave".

If I `strace -f alacritty` it looks like the PTY-child-end is initially being opened in *O_RDWR|O_NOCTTY* - I'll do a couple more tests to make sure I didn't do something silly when I was first seeing this (i.e. I may have messed up my own terminal somehow).

**Comment by aslatter** [comment]
Alacritty is doing everything fine with the PTY - I must have messed it up on my own.

Sorry for the bother!
