### ISSUE TITLE
Shift + Arrow doesn't work in Vim

### ISSUE THREAD

**Issue by unihernandez22** [alacritty/alacritty#4215]
### Description
Shift + Arrow (Up and Down) bindings doesn't work with alacritty, but yes with termite. In Vim, when I push the keyboard binding for scrolling faster, it doesn't work.

### How to reproduce
- Open a file with more lines that terminal height with Vim in alacritty
- Try to use the keybindings Shift + Up and Shift + Down for scrolling

### System
OS: ArchLinux
Version: 0.5.0
Linux: X11, picom and i3wm

**Comment by chrisduerr** [comment]
Does it work when changing your `TERM`?

**Comment by unihernandez22** [comment]
> Does it work when changing your `TERM`?

Yes, awesome. Thx.

**Comment by chrisduerr** [comment]
Yeah that's vim's fault. I'd assume it probably works fine with neovim. It's a tad terrible at handling terminals.
