### ISSUE TITLE
Can't change curosr style

### ISSUE THREAD

**Issue by Jamesdawg1977** [alacritty/alacritty#4221]
OS: Arch Linux
Version: alacritty 0.5.0
Linux/BSD: X11, Compton, and Qtile

I noticed in the config there was an option to change cursor style, and since I prefer beam cursors, tried to switch. So I uncommented 'style: Block' and replaced 'Block' with 'Beam', but nothing has changed. Even after completely rebooting, the cursor in my terminal window still won't change. I'd really appreciate any help anyone can give me!

**Comment by chrisduerr** [comment]
Your shell might be changing the cursor shape too. Try running a shell without any config right on startup. Or running `sh --noprofile --norc` and then resetting.

**Comment by Jamesdawg1977** [comment]
I tried that and it was just the normal block. Here's my config:
[alacritty.txt](https://github.com/alacritty/alacritty/files/5213327/alacritty.txt)

**Comment by Jamesdawg1977** [comment]
I tried that and it was still just a block. And this is my config:

`#cursor:
  # Cursor style
  #
  # Values for `style`:
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
style: Beam 
`

**Comment by Jamesdawg1977** [comment]
Alright I tried that, and it was still just the normal block. Here is my config:
#cursor:
  # Cursor style
  #
  # Values for `style`:
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
style: Beam

**Comment by Jamesdawg1977** [comment]
Alright I tried that, and it was just the normal block. And literally all that I have for the cursor is
style: Beam

**Comment by chrisduerr** [comment]
I mean that's not a valid config.

**Comment by Jamesdawg1977** [comment]
How should I have it? All I did was uncomment the line for it like I did with background_opacity and that works just fine.

**Comment by chrisduerr** [comment]
You need to uncomment the parent fields too. The file is hierarchical.

**Comment by Jamesdawg1977** [comment]
Alright so I uncommented all of this:
cursor:
   Cursor style
  
   Values for `style`:
     - ▇ Block
     - _ Underline
     - | Beam
style: Beam 

And now I get this error:
Problem with config: mapping values are not allowed in this context at line 340 column 22
Where line 340 is "Values for `style`:" Again I don't code at all, just minor config changes like this, so I'm sorry if this is a really stupid mistake.

**Comment by chrisduerr** [comment]
Please try the following config, just like posted here:

```yml
cursor:
  style: Beam
```

**Comment by Jamesdawg1977** [comment]
Ah it worked. Thank you so much! Again, sorry for the stupid question.
