### ISSUE TITLE
Combining Character's don't quite work.

### ISSUE THREAD

**Issue by TravisWhitaker** [alacritty/alacritty#4228]
Unicode combining sequences don't quite work. Here's an example where Terminal.app gets it right, but alacritty gets it wrong:

![terminal](https://user-images.githubusercontent.com/1310395/93032711-d18ab380-f5e7-11ea-9dff-3bb351ed5ae1.png)

![alacritty](https://user-images.githubusercontent.com/1310395/93032716-d6e7fe00-f5e7-11ea-92f0-10c4a217183a.png)

### System

Any

**Comment by kchibisov** [comment]
Well, this is a mostly font issue, hence we don't use normalization(not sure if it'll even helpful here) and we don't try to override font mertrics. So if you try something like `Fira Mono` it'll likely work correctly here(and indeed works for me).

**Comment by kchibisov** [comment]
That's a bit of explanation why https://github.com/alacritty/alacritty/issues/2620#issuecomment-583786216 .

**Comment by chrisduerr** [comment]
Yeah, this is a problem with your font, not with Alacritty.

**Comment by TravisWhitaker** [comment]
Hmm, I'm using Menlo, same as the default Terminal.app configuration, and Terminal.app is able to render this just fine...

I'm no fonts expert; is the claim that alacritty handles fonts more strictly than e.g. Terminal.app (which might even have some baked-in knowledge of Apple's proprietary fonts), so a font specification problem can lead to a rendering error like this?

**Comment by chrisduerr** [comment]
Alacritty just uses the font's glyphs and metrics as they are requested and specified in your font. Terminal.app probably modifies things after the fact, rendering a different glyph than requested.
