### ISSUE TITLE
Line Wrapped Delete Hides Character

### ISSUE THREAD

**Issue by nixpulvis** [alacritty/alacritty#4229]
Deleting the first line-wrapped character deletes the character but also appears to delete the last character from the previous line. The character is not actually deleted, and will reappear if another character is typed. A GIF's worth a thousand words:
![delete-wrapped-issue](https://user-images.githubusercontent.com/715947/93036302-8a171e00-f60d-11ea-888a-8339f71fa785.gif)

I've tested this on the current state of `master` (c77ab137f15ee16144bbbd89df8eb95b30174744).

**Comment by chrisduerr** [comment]
Could you please try in bash?

**Comment by nixpulvis** [comment]
Ugh, of course it's working in `sh`/`bash`... Why must `fish` cause me so much happiness and yet so much pain.

**Comment by nixpulvis** [comment]
This issue is happening in other terminals, so I've opened https://github.com/fish-shell/fish-shell/issues/7332. Sorry for the false alarm.
