### ISSUE TITLE
Colors not working

### ISSUE THREAD

**Issue by Bunkdo** [alacritty/alacritty#4236]
Uncommenting `colors` section then uncommenting `primary` and filling in desired hexadecimal colors works fine. Uncommenting any other part after that breaks the config, for example in Normal colors section uncommenting `normal` and filling out hexadecimal values just returns me with an error. Same goes with bright colors and selection colors.

[ERROR] Unable to load config "/home/user/.alacritty.yml": Problem with config: while parsing a block mapping, did not find expected key at line 229 column 9

It just points to a semicolon after `normal`

I'm on Xfce4 Arch.

**Comment by chrisduerr** [comment]
Please share the broken configuration file so I can tell you how to fix it.

**Comment by Bunkdo** [comment]
[config copy.txt](https://github.com/alacritty/alacritty/files/5236629/config.copy.txt)

Sorry for the wait.

**Comment by chrisduerr** [comment]
The family/style indentation is incorrect.

**Comment by Bunkdo** [comment]
I'm not familiar with managing fonts then. I simply went to `fc-list` and followed the output after the path to file.

`/usr/share/fonts/TTF/JetBrainsMono-Variable.ttf: JetBrains Mono:style=Bold`

**Comment by chrisduerr** [comment]
The *indentation* is incorrect, not the font name itself. The number of whitespace before it.

**Comment by unihernandez22** [comment]
Close this

**Comment by chrisduerr** [comment]
Good point, though a bit forward.
