### ISSUE TITLE
vim 8 won't change cursor style

### ISSUE THREAD

**Issue by urbster1** [alacritty/alacritty#4238]
### System

OS: Linux Mint 20
Version: alacritty 0.6.0-dev
Linux/BSD: X11

The following lines in .vimrc don't override cursor behavior in alacritty

```
" change cursor shape on mode change
let &t_SI = "\<esc>[5 q"  " blinking I-beam in insert mode
let &t_SR = "\<esc>[3 q"  " blinking underline in replace mode
let &t_EI = "\<esc>[ q"  " default cursor (usually blinking block) otherwise
```

**Comment by chrisduerr** [comment]
Vim might not be running these escapes in Alacritty, it's feature detection is rather lackluster. Try running it with `TERM=xterm-256color vim`. If it works outside of vim with these escapes, but it doesn't work inside, it's probably not an Alacritty bug.

**Comment by urbster1** [comment]
this isn't an alacritty bug - it works if I run the commands manually in vim. Thanks!
