### ISSUE TITLE
The --option argument won't work on the color options

### ISSUE THREAD

**Issue by cbirchinger** [alacritty/alacritty#4239]
~ $ alacritty  --option colors.primary.background='#ff00ff'
Invalid CLI config option: "colors.primary.background=#ff00ff"

I assume my syntax is correct because if i use an invalid string like 'black'
instead of '#ff00ff', i get the an error that suggests what i should do:

~ $ alacritty  --option colors.primary.background='black'
[2020-09-18 05:08:11.743439938] [ERROR] [alacritty_config] Problem with config: failed to parse rgb color black; expected hex color like #ff00ff; using default value

All other colors i've tried (like -o 'colors.normal.black=#000000') fail the same way.

Other options work fine. For example this:
~ $ alacritty  --option "font.normal.family=Monospace"

**Comment by kchibisov** [comment]
Try `alacritty  --option "colors.primary.background='#ff00ff'"`

**Comment by cbirchinger** [comment]
Yes, this works. I tried 3 different quoting methods, but of course not this one.

Closing the non-issue. If i missed some documentation, i'm sorry,  otherwise it would be smart to make
it perfectly clear, that you have to double quote options with "#".
