### ISSUE TITLE
Paste from clipboard instead of primary selection

### ISSUE THREAD

**Issue by danog** [alacritty/alacritty#4240]
Hi all!
First of all, thank you for the amazing project, loving the alacritty experience so far :)

I wanted to report a small issue I've been having with pasting text into alacritty.
When working with apps (like telegram-desktop, for example) that do not access the `zwp_primary_selection_device` protocol exposed by wl-clipboard(-rs), alacritty cannot paste text copied from those apps.

smithay-clipboard is correctly receiving data offers from both the global data device (aka CLIPBOARD) and the zwp_primary_selection_device (aka PRIMARY), but alacritty only accepts data from the PRIMARY buffer.
If an app sends offers data to the the CLIPBOARD device, but not to the PRIMARY device, alacritty cannot paste it, and instead pastes the last selection from an app which did write to CLIPBOARD.

Somewhere (probably in ansi.rs), clipboard_load defaults to `p` or `s` instead of `c`.

My proposal is to make this behavior a bit more in line with other terminals, which mostly take their input from the CLIPBOARD buffer, and not the PRIMARY buffer.

### System

OS: Linux
Version: alacritty 0.6.0-dev (5ee7ae8a)
Linux/BSD: Sway

**Comment by danog** [comment]
Just to be clear; I see that in ansi.rs, the clipboard type defaults to c, but data still gets pulled from the primary selection.

If I select some text in Firefox (which does write data to the selection buffer), and then copy some other text in Telegram (which only accesses the clipboard), when I paste in alacritty only the Firefox selection is inserted. 

This always forces me to paste text copied from Telegram into the Firefox address bar (which does pull data from the clipboard by default), select it and then paste it into alacritty.

**Comment by kchibisov** [comment]
ansi.rs has nothing to do with gui clipboard at all, that's osc 52 handling, which is not what you want to. The primary buffer is accessible via Middle mouse button or shift + insert, the clipboard buffer is accessible via `ctrl + shift + v/c` by default. I don't really understand what you're talking about here.

**Comment by kchibisov** [comment]
Also, if I select some text in telegram, and press middle button in alacritty it pastes without any issue for me, so the thing you're saying is a bit strange to me, however some old qt libs didn't have primary selection working or something like that.

**Comment by danog** [comment]
References to the middle button always make me regret I'm on a laptop :) 
Anyway, you're right, using ctrl+shift+v does take data from the clipboard buffer properly.

It's curious though, I was actually used to xterm taking data from the __clipboard__ buffer on shift+insert with the `XTerm*selectToClipboard: true` option.

It would nice to have an option in the config file to enable this behavior on alacritty like for xterm.

**Comment by danog** [comment]
Thanks!
