### ISSUE TITLE
Dim colors are incorrectly computed for light background

### ISSUE THREAD

**Issue by fd0** [alacritty/alacritty#4241]
### System

OS: Linux
Version: `0.5.0`, `0.6.0-dev (56c6ff18)`
Linux/BSD: X11, i3

I'm using a light background and noticed that text with the `dim` attribute is not rendered correctly. The text is displayed with **more** instead of **less** intensity. 

For example, using the `256test.sh` [script](https://gitlab.gnome.org/GNOME/vte/-/blob/master/perf/256test.sh)  from `libvte` yields the following first few lines on a dark background in `alacritty`:

![2020-09-19-181202_356x143_scrot](https://user-images.githubusercontent.com/123276/93672403-dd281f80-faaa-11ea-85cc-31a4b68518ab.png)

Note that the `dim` and `bold+dim` lines are **less** intense.

On a light background, the following is shown:

![2020-09-19-181237_319x139_scrot](https://user-images.githubusercontent.com/123276/93672411-efa25900-faaa-11ea-82f9-43f11d6a0680.png)

The `dim` and `bold+dim` lines are displayed in a darker color than the `normal` lines, which makes the text **more** intense, contrary to what the `dim` attribute means on dark background.

I think this is incorrect, the text should be displayed in a lighter color on light background. For the record, `libvte` does the same (and I think that's a bug there, too).

In contrast to [Xterm.js](https://github.com/xtermjs/xterm.js/), which is embedded in Visual Studio Code correctly renders dim colors (in my opinion):

![2020-09-19-181322_286x136_scrot](https://user-images.githubusercontent.com/123276/93672453-3a23d580-faab-11ea-83ba-db3382fb6536.png)

You can see that the text is rendered in a lighter color.

I dug into the code and saw that the dim colors are computed by multiplying each color with a factor of 0.66, thereby making it darker. I implemented a proper algorithm which takes the background color into account (using the same idea as Xterm.js, blend the background and the color with a 50% opacity). You can find it in the branch `fix-dim-light-background` in my fork, the commit is here: https://github.com/fd0/alacritty/commit/f7d453dde03cf9ba2f9c1a9a7e3ff8e4e1effcd1

Implementing the algorithm wasn't that hard, but I didn't manage to get the background color in all places where the dim colors are calculated.

Can somebody please help? Is this something you're willing to merge? You can just take my commit and fix the other places, that'd be great! Or just guide me a bit so I can fix them...

Thanks a lot for all your work on a memory-safe terminal emulator!

**Comment by chrisduerr** [comment]
The color factor is less intense and it is *dimmed* regardless of the background color. I don't see how this would be incorrect?

@kchibisov / @nixpulvis I'd rather keep this the way it is, let me know if anyone of you disagrees.

**Comment by fd0** [comment]
> The color factor is less intense and it is dimmed regardless of the background color. I don't see how this would be incorrect?

I'm not sure we're talking about the same thing.

Let's say we have white text on dark background. Dimming the white text by scaling it with a factor 0.66 would lead to a light grey text, which on a dark background looks less intense ("dimmed" or "faint" as the standard describes it).

If the text is black and the background is white, dimming the text color by scaling it with a factor of 0.66 does not change the color at all because `#000000 * 0.66` is still `#000000`. So users cannot see a difference between "dim" and "normal" text.

I think that's a bug, do you disagree? :)

**Comment by chrisduerr** [comment]
> I think that's a bug, do you disagree?

Yes.

**Comment by fd0** [comment]
Ok, that's unfortunate :(

**Comment by kchibisov** [comment]
I'm fine with that patch, since it's a bit less arbitrary in terms of computing the dimmed colors than just multiplying by `0.66`, since dimmed colors are the ones that are less intense, however on light background those are brighter than the original color, which is not that I'd expect either.

**Comment by chrisduerr** [comment]
> I'm fine with that patch

What patch?

> on light background those are brighter than the original color

They're not though. Brightness of a color is unrelated to the background. Brightness and contrast are two different things.

**Comment by kchibisov** [comment]
>What patch?

https://github.com/fd0/alacritty/commit/f7d453dde03cf9ba2f9c1a9a7e3ff8e4e1effcd1

**Comment by chrisduerr** [comment]
Yeah that'll make colors ***brighter*** when you dim them. Which makes no sense. At that point are you going to make bright colors dimmer too?

**Comment by fd0** [comment]
The patch implements `dim()` by rendering the color with an opacity of 0.5 on the background.

**Comment by rawtaz** [comment]
> They're not though. Brightness of a color is unrelated to the background. Brightness and contrast are two different things.

Regardless of vocabulary, it's quite clear when looking at the two example images @fd0 pasted in the initial post here, that the result is not what you'd expect and what is visually correct. Just look at it :)

Dimmin is about going towards what is considered "lighter", and what's currently happening (as shown in the images) is the opposite. This is naturally because when the background is dark, one can just lower the color intensity, but when the background is lighter, one has to go in the opposite direction to make the subject lighter/more dimmed.

**Comment by chrisduerr** [comment]
> Dimming is about going towards what is considered "lighter", and what's currently happening (as shown in the images) is the opposite. This is naturally because when the background is dark, one can just lower the color intensity, but when the background is lighter, one has to go in the opposite direction to make the subject lighter/more dimmed.

Says who? This is not correct. Only because your background is white, doesn't make a brighter color dimmer.

**Comment by rawtaz** [comment]
@chrisduerr I'm not trying to start an argument. But what matters in the end is what is shown visually, no? In this case the current algorithm simply isn't dimming the text relative to the background.

**Comment by chrisduerr** [comment]
> But what matters in the end is what is shown visually, no?

Yes, the color that is shown matters, not the contrast. The current algorithm dims the color, regardless of the background, which is the correct choice and what every other terminal emulator does.

**Comment by erikgeiser** [comment]
I agree with @fd0. In this case, the wording is ambiguous as the modifier is described as *dim* or *faint* just like the *bold* modifier that is sometimes called *bright*, so discussing the name does not help. In my opinion what matters is that developer print *dim* or *bold* for a reason and it should have a visible effect regardless of the color theme. It does not help the user, nor does it support the developers intention, if almost dimmed black text is technically rendered 2/3 darker if it looks the same in practice.

For reference iTerm2 also uses another approach that makes *dim*/*faint* text distinguishable on a light color theme.

**Comment by rawtaz** [comment]
> The current algorithm dims the color, regardless of the background

I think this is what I and the author of this issue think is not working well. Even if the current algorithm is correctly *dimming*, the problem is that other factors affect how this is shown.

Let's put it another way; How can we make the text show the same "lighter" way with a light background? Like in the Xterm.js example provided earlier?

That is what I think matters - how to make it look right, rather than which technical detail to fix it with :)

**Comment by chrisduerr** [comment]
If it looks the same in practice or not is a completely different problem that is not resolved with this nor with any other patch and depends highly on the colorscheme used.

However while the text might not be very clear, what it is supposed to do is very well de-facto standardized by all existing terminal emulators. The only thing that could make this any less clear is changing it, which is just one more reason why we shouldn't.

**Comment by kchibisov** [comment]
>However while the text might not be very clear, what it is supposed to do is very well de-facto standardized by all existing terminal emulators. The only thing that could make this any less clear is changing it, which is just one more reason why we shouldn't.

Well, if we take into account that libvte/xterm are doing the same as we do, and I bet a lot other terminals are following xterm, then there's nothing to change here.

**Comment by rawtaz** [comment]
Just because others do thing X doesn't mean it's the right thing to do. What I mean by that is that what others do shouldn't be what determines what this software does.

**Comment by chrisduerr** [comment]
> Just because others do thing X doesn't mean it's the right thing to do. What I mean by that is that what others do shouldn't be what determines what this software does, especially considering there are other examples of doing it the same way or equal way to what's suggested here.

Preexisting standards is exactly what should determine how Alacritty behaves when the definition itself isn't clear enough. Without that you're not gonna get very far when it comes to terminal emulation.

**Comment by rawtaz** [comment]
Well there's not much one can say if you want to keep a broken functionality just because of standards. Again, just look at the images. Clearly the result is not what one expects and what is visually proper. You may think what you want about that, and choose not to fix it of course. Nothing I can do about it. Regardless, the images speak for themselves. Thanks.

**Comment by chrisduerr** [comment]
> Well there's not much one can say if you want to keep a broken functionality just because of standards.

It's not broken though.

**Comment by rawtaz** [comment]
So how can we make the text show the in same "lighter" way when there's a light background, as in the Xterm.js example provided earlier?

**Comment by kchibisov** [comment]
>Clearly the result is not what one expects and what is visually proper. You may think what you want about that, and choose not to fix it of course. Nothing I can do about it. Regardless, the images speak for themselves. Thanks.

It depends what are you expecting from dim, less contrast or darker. If we think from a point of brigher, normal, and dim, then it feels like the answer is darker.

Also, just fyi, if you don't like default dim colors you can change them.

**Comment by kchibisov** [comment]
>So how can we make the text show the in same "lighter" way when there's a light background, as in the Xterm.js example provided earlier?

Define those https://github.com/alacritty/alacritty/blob/56cff184868f3bb3bb45082cac79fec296e4a48b/alacritty.yml#L258

**Comment by fd0** [comment]
Thanks for the hint! I still think it's a bug, so we disagree here. I'm setting the dim colors manually in the config now.
