### ISSUE TITLE
Some keyboard shurtcuts don't work in Midnight Commander

### ISSUE THREAD

**Issue by sulan** [alacritty/alacritty#4243]
Hi,

Ctrl-PageUp and Shift-F3/F4/F5/F6 does not seem to work correctly in Midnight Commander with Alacritty. They work correctly with urxvt (rxvt-unicode-patched in AUR) and xterm. This happens even without any config files in my home directory. 

Thanks!

### Expected behaviour:

- Ctrl-PageUp: change directory to parent
- Shift-F3: view raw
- Shift-F4: edit new file
- Shift-F5: copy here
- Shift-F6: move here / rename

### Observed behaviour:

- Ctrl-PageUp: does nothing
- Shift-F3: copy here (what Shift-F5 is supposed to do)
- Shift-F4: move here / rename (what Shift-F6 is supposed to do)
- Shift-F5: does nothing
- Shift-F6: delete (what Shift-F8 is supposed to do)

### System

- OS: Archlinux
- Version: alacritty 0.6.0-dev (56cff184)
- Linux/BSD: X11, Awesome WM
- Shell: Zsh and Bash

### Logs

Nothing really interesting is printed:

```
% alacritty --print-events -vv
[2020-09-22 13:25:46.930070290] [INFO ] [alacritty_config] No config file found; using default
Created log file at "/tmp/Alacritty-26512.log"
Deleted log file at "/tmp/Alacritty-26512.log"
```

**Comment by kchibisov** [comment]
if you do `TERM=xterm-256color` before launching `mc`  will it work?

**Comment by sulan** [comment]
Yes, that way it works, thanks! Is that mc not doing something correctly?

**Comment by kchibisov** [comment]
>Yes, that way it works, thanks! Is that mc not doing something correctly?

Yes.
