### ISSUE TITLE
Deprecate Redundent CLI Flags/Options

### ISSUE THREAD

**Issue by nixpulvis** [alacritty/alacritty#4246]
Now that #4159 is implemented, there's a question of what command line flags should be deprecated. We currently support the following redundant flags/options:

```
--persistent-logging    -> -o debug.persistent_logging
--print-events          -> -o debug.print_events
--live-config-reload    -> -o live_config_reload
--class                 -> -o window.class
-t, --title             -> -o window.title
--working-directory     -> -o working_directory
-e, --command           -> -o shell
-d, --dimensions        -> -o window.dimensions
--position              -> -o window.position
```

Without a general policy for what should or should not be deprecated in mind, I'd be tempted to leave the following flags un-deprecated:

- `--persistent-logging`
- `--print-events`
- `--class`
- `--title`
- `--working-directory`
- `--command`

Thoughts?

**Comment by chrisduerr** [comment]
I'm curious about your reasoning for each CLI option.

These are my thoughts:

| Option               | Remove | Reason                                                                                               |
| -------------------- | ------ | ---------------------------------------------------------------------------------------------------- |
| --persisting-logging | Yes    | Rarely used debug option (in case of error, it's kept automatically anyways), no need to clutter CLI |
| --print-events       | No     | I use it a lot and I'm lazy                                                                          |
| --live-config-reload | Yes    | Seems like something you'd rarely change your mind about                                             |
| --class/--title      | No     | These are relatively useful for testing and something (I think) people commonly use as CLI options   |
| --working-directory  | No     | This is a pretty essential CLI argument that should be easy to find                                  |
| --e/--command        | No     | The -e flag must be present for compatibility alone, so it's absolutely crucial                      |
| --dimensions         | Yes    | Setting dimensions seems like a rare thing to require / WM can also do this                          |
| --position           | Yes    | Setting position seems like a rare thing to require / WM can also do this                            |

These seem to mostly line up with yours, except for persistent logging.

**Comment by nixpulvis** [comment]
I'm perfectly happy to write `-o debug.persistent_logging` instead of `--persisting-logging`, and would also be OK with `-o debug.print_events` to be honest. But if you want to leave the flag for printing events, since we don use it a lot, that seems totally fine too.

Yea, seems like we pretty much agree here.

**Comment by chrisduerr** [comment]
> I'm perfectly happy to write -o debug.persistent_logging instead of --persisting-logging

That's not how boolean options work with options though.

**Comment by nixpulvis** [comment]
I guess I should have written `-o debug.persistent_logging=true`. I was thinking that it might be nice to have flags default to `true`, but I don't think it's worth the complexity.

**Comment by chrisduerr** [comment]
> I don't think it's worth the complexity.

Correct.
