### ISSUE TITLE
Message bar text shouldn't be computed based on byte length

### ISSUE THREAD

**Issue by chrisduerr** [alacritty/alacritty#4250]
There are some string length checks for the message bar which use the byte length (see [here](https://github.com/alacritty/alacritty/blob/62c300c14ce7a96373e0094763e9fd035b6b9b6d/alacritty/src/display.rs#L419)). Generally I don't think unicode and fullwidth characters have been considered much for the message bar. However since it's possible for user config to show up inside the message bar, it's possible to have these unicode symbols present here.

**Comment by alessandroasm** [comment]
Hi, I would like to help with this issue. I'll post a pull request shortly!
