### ISSUE TITLE
Add an option to respect cursor shapes setting from shells

### ISSUE THREAD

**Issue by AoHiyuki** [alacritty/alacritty#4254]
Hi. Thanks for an amazing work on this terminal.

I can't find any issues related to this. Does Alacritty have a setting to respect the cursor shape setting from other programs?
In my case, I use fish-shell. It has an option to set the cursor shapes when I enable vi_key_bindings. But that setting gets overridden by Alacritty.

### System:
OS: Void Linux
Alacritty: alacritty 0.5.0

**Comment by kchibisov** [comment]
We never override anything, if anything shell could decide to not set cursor for some arcane reason like different terminfo name. If you execute escape sequence that changes cursor shape manually it'll work. e.g. `echo -e "\e[4 q\e\\"` should change it to underline,  `echo -e "\e[1 q\e\\" to block, and  `echo -e "\e[6 q\e\\" to Beam.

**Comment by AoHiyuki** [comment]
After re-reading the function, I fought out that fish doesn't support alacritty for vi_cursor_mode. My bad for raising this issue too soon.
Thanks for the reply.
