### ISSUE TITLE
Input lag when colorscheme is not default

### ISSUE THREAD

**Issue by gfanto** [alacritty/alacritty#4255]
I use neovim but i have the same problem with vim, the problem is that I'm experiencing a significant input lag when i have some colorscheme enable in vim, in fact if i use the default colors it works pretty well, but as soon i enable some colorscheme alacritty starts to be laggy (i don't have the same problem in other terminal emulators).

Alacritty version: i build it from master so is updated to the last version, where i removed vsync because i use a faster repeat time on the keyboard and with it it's almost unusable.
Os: ubuntu 20.04

I hope someone can give some hint on how to resolve the problem, event if is some piece of code where i can try to fix myself

**Comment by kchibisov** [comment]
What version are you using `alacritty --version` (output) and how did you installed it?

**Comment by Fanto94** [comment]
Like i said i build it from the master so it's updated, anyway that's the output: `alacritty 0.6.0-dev (62c300c)`
I don't think i'ts a version fault because i notices this problem when i started using alacritty (more than a year ago)

**Comment by chrisduerr** [comment]
Please define "laggy".

**Comment by Fanto94** [comment]
To give you an example if i press down for 1 second and then i release, the screen start scrolling for at least 2 seconds and the line processed per "time unit" are not the same, for example in 10 milliseconds the screen goes down 3 lines and the next 10 just 1.
I think the key points to reproduce the proble are:
1. increase the speed rate of your keyboard
2. use a vim colorscheme with some background color
3. move in some file using keybord

I personally use neovim 0.5 with gruvbox but i got the same problem with vim and other colorschemes
To increase the "laggy" effect you can disable the vsync, in my build i just set to false the vsync variable in the file window.rs

Some more os information are:
- not using wyland
- TERM variable is set to xterm-256color

Please let me know if i can give you more information.

**Comment by chrisduerr** [comment]
> use a vim colorscheme with some background color

So this doesn't happen in vim colorschemes without a background color?

> TERM variable is set to xterm-256color

Have you tried Alacritty's terminfo?

**Comment by Fanto94** [comment]
> So this doesn't happen in vim colorschemes without a background.

Exactly, i cannot be sure 100% because i haven't tried every possible colorscheme, but this happen as soon i activate some colorscheme with a background and disappear automatically when i disable it; i notice this behaviour with every colorscheme with some backgroud color, even the simpler one like the blue colorscheme of plain vim with no configuration.

I don't know if it can help but after some googleing i came across this variable to set in vim `let &t_ut=''`, (even without knowing what it means, apologies for my ignorance) i tried it but without success.

 > Have you tried Alacritty's terminfo?

Yes, i tried now, after your message but i have the save behaviour.

I tried tmux and the result it's the same; the only thing i havent't tried if it does make sens it's tring to use vim it with an ssh connection.

**Comment by chrisduerr** [comment]
What GPU and driver are you using?

**Comment by Fanto94** [comment]
I'll give you the output of `lshw -c video`:
```
  *-display
       description: VGA compatible controller
       product: HD Graphics 620
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 02
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:153 memory:b0000000-b0ffffff memory:a0000000-afffffff ioport:3000(size=64) memory:c0000-dffff
```

**Comment by chrisduerr** [comment]
Do you have any other vim/Alacritty configuration active? What's your display resolution?

**Comment by Fanto94** [comment]
> Do you have any other vim/Alacritty configuration active?

No, nothing weird just plain alacritty (no configuration) + plain vim (no configuration) after setting a colorscheme  with some background color (ex: colorscheme blue), the terminal from superfast to scroll lines become slow.

> What's your display resolution?

1920 x 1080 - 60Hz

**Comment by chrisduerr** [comment]
1920 x 1080 with HD620 graphics shouldn't be a problem at all. Which mesa version are you using?

**Comment by Fanto94** [comment]
I hope this answers your question because i'm not very knowledgeable on this type of things
`glxinfo | grep "OpenGL version"`
OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.0.8

**Comment by chrisduerr** [comment]
Hm that doesn't seem too old. This might seem a bit odd, but could you try `LIBGL_ALWAYS_SOFTWARE=1 alacritty`? This should run it using software rendering instead of hardware, just to make sure it has nothing to do with your GPU doing weird stuff.

**Comment by Fanto94** [comment]
Yes the problem is pretty much the same, i have an erorr when i disable vsync:
`Error creating GL context; Received multiple errors. Errors: [NoAvailablePixelFormat, OsError("Couldn't find any available vsync extension")]`
but it's probably due to the fact that i just disable it by putting `let vsync = false` on this line: https://github.com/alacritty/alacritty/blob/master/alacritty/src/window.rs#L166 and there are maybe some other  checks to do

**Comment by chrisduerr** [comment]
Can you maybe share some more system information like the display server/wm/de/compositor you're using?

Also a video might be helpful, just to be absolutely clear about the issue.

**Comment by FrontMage** [comment]
Same here with AMD 3400G with vega 11 integrated graphic card.
Don't think alacritty works without vsync though.
With `glxgears` I get 1fps, but with `vblank_mode=0 glxgears` I get 1989.789fps.
My guess is that my motherboard MSI b450 does not support igd mode with the latest integrated graphic card very well.
It works with AMD 2200G with vega 8 with the same exact setup.
