### ISSUE TITLE
Neovim not resizing properly with -e

### ISSUE THREAD

**Issue by jzbor** [alacritty/alacritty#4256]
Hi,
I have a problem with nvim, when opened through the `-e` flag. Nvim does not properly resize to the bottom of the window. This does not occur when nvim is opened from the shell. It also is not consistent, sometimes it does work properly. Therefore it seems to be about the timing at startup. I use DWM in a tiled layout and simply "floating" and "unfloating" causes nvim to resize and fit the window. I tried `:redraw` and `:redraw!` in nvim, but neither of them changed anything. I attached a screenshot so that you maybe can understand the problem.

![Screenshot_2020-09-26_19-31-42](https://user-images.githubusercontent.com/48366877/94346900-4fef4880-001f-11eb-8300-5840598c2d08.png)

### System

OS: Linux (Artix)
Version: 0.5.0
Linux/BSD: DWM (X11)

**Comment by kchibisov** [comment]
See https://github.com/neovim/neovim/issues/11330 and https://github.com/alacritty/alacritty/issues/2817
