### ISSUE TITLE
Embed Alacritty in another OpenGL-based application?

### ISSUE THREAD

**Issue by brhsiao** [alacritty/alacritty#4258]
I'm building an application that is similar to Alacritty in that it uses OpenGL to render its entire enterface. 

Given this seeming compatibility, is there a straightforward path to embedding Alacritty in my application, preferably in a way I can directly call from C? I'm envisioning I would have Alacritty render to a texture, which I would then render in my own application, and then forward keystrokes from the user to Alacritty. Is this something [planned on being] supported?

**Comment by chrisduerr** [comment]
Alacritty should be fairly composable, especially if you write the rendering yourself. On X there's also the XEmbed protocol which will just work.  Generally you'll have to put in the effort to make it work though of course, it's not just magically going to plop in on its own.

**Comment by brhsiao** [comment]
> Alacritty should be fairly composable, especially if you write the rendering yourself. On X there's also the XEmbed protocol which will just work. Generally you'll have to put in the effort to make it work though of course, it's not just magically going to plop in on its own.

Got it. I assume I'd have to fork Alacritty and, like, recompile it to expose the functions that spit out the rendered image and take in keystrokes through an FFI. If I did this, would it just be a manual process to regularly merge in master from Alacritty to get all the latest changes?

**Comment by kchibisov** [comment]
I wonder what are you going to do? If the goal is to use alacritty_terminal and its rendering, but handle all the window, etc yourself you'll be more lucky with just writing your own application with alacritty_terminal directly, since it's a terminal emulator library. And so you can rewrite the rendering the way you want.

**Comment by brhsiao** [comment]
> I wonder what are you going to do? If the goal is to use alacritty_terminal and its rendering, but handle all the window, etc yourself you'll be more lucky with just writing your own application with alacritty_terminal directly, since it's a terminal emulator library. And so you can rewrite the rendering the way you want.

This is what I needed. Thanks.
