### ISSUE TITLE
Debian (buster) - Install alacritty with cargo

### ISSUE THREAD

**Issue by BigfootN** [alacritty/alacritty#4260]
Hello,

I am desperately trying to install alacritty through cargo on debian 10 (buster), without any success.

### Command launched

`cargo install alacritty`

### System

OS: Debian 10 buster
Cargo version: 1.42.1

### Logs

``` 
  Updating crates.io index
  Installing alacritty v0.5.0
  Downloaded image v0.23.10
   Compiling libc v0.2.77
   Compiling cfg-if v0.1.10
   Compiling xml-rs v0.8.3
   Compiling bitflags v1.2.1
error: Unrecognized option: 'json'

error: could not compile `cfg-if`.
warning: build failed, waiting for other jobs to finish...
error: Unrecognized option: 'json'

error: Unrecognized option: 'json'

error: Unrecognized option: 'json'

error: could not compile `bitflags`.
warning: build failed, waiting for other jobs to finish...
error: could not compile `libc`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `alacritty v0.5.0`, intermediate artifacts can be found at `/tmp/cargo-installHWspPE`
```

Thank you very much in advance for any help.

**Comment by chrisduerr** [comment]
What rustc version are you using also 1.42.1? Building on the version recommended for 0.5.0 (rustc 1.41.0) works just fine for me.

**Comment by BigfootN** [comment]
Sorry for the late response.

Indeed, my rustc version was old. I updated it, and it worked like a charm.

Thank you for your precious help.
