### ISSUE TITLE
Nvim in Alacritty is behaving weirdly when executed with alacritty -e nvim.

### ISSUE THREAD

**Issue by Filip62** [alacritty/alacritty#4261]
### Issue
I am using Tridactyl Firefox extension. It has a feature that opens a text editor of your choice where you can edit text and it will be written in a textbox on a webpage. I have set the editor command to be **`alacritty -e nvim`**. It launches as expected, but the **nvim interface looks all weird and is unusable.**

To be clear it does not have anything to do with Firefox or Tridactyl, because it also happens when I run the command in an alacritty instance instead.

![1601199257](https://user-images.githubusercontent.com/58399088/94361595-b030c980-00b5-11eb-9fea-f9ce0fd63f4b.png)

### Workaround/Fix
When I **maximize the alacritty window and then "minimize" it back to half a screen, it is all fixed.**
Or when I **change the editor command to `alacritty -e fish -c "sleep 0.04 && nvim"`, that also fixes the problem.**
Anything less than 0.04 does not fix it sometimes, 0.04 seems to be sure shot. (At least on my system.)
It seems like Alacritty is either too fast or QTile too slow or something along those lines. I mean I do not mind using the "sleep fix", but still thought I should let you and people know. 

![1601199265](https://user-images.githubusercontent.com/58399088/94361633-0a318f00-00b6-11eb-96d5-b3924c1ba27b.png)

### System

OS: Arch Linux
Version: 0.5.0
Linux: X11, Picom, QTile

**Comment by kchibisov** [comment]
See neovim/neovim#11330 and #2817
