### ISSUE TITLE
Tmux divider extends a bit too far in Alacritty

### ISSUE THREAD

**Issue by ckipp01** [alacritty/alacritty#4262]
### System

OS: macOS
Version: 0.5.0

###

With a clean system I having some odd behavior with tmux. Looking around at previous issues and through the docs I can't seem to find anything that references this. I'm not even sure that this is the correct place to submit this, but it _only_ seems to happen on Alacritty, but not with the mac Terminal or on iTerm.

However, when I start with fresh settings and I install tmux, and then split the screen, the divider when I'm on Alacritty seems to extend too far. I've included an image below to show what I mean:

<img width="344" alt="Screenshot 2020-09-27 at 14 53 01" src="https://user-images.githubusercontent.com/13974112/94365432-3575a780-00d1-11eb-8777-83a3626818a5.png">

Again, I don't have any padding set, any settings in my alacritty.yml file set, and nothing in my `.tmux.conf` apart from a new binding.

Here is how it looks in the mac Terminal and in iTerm2:

<img width="344" alt="Screenshot 2020-09-27 at 14 55 40" src="https://user-images.githubusercontent.com/13974112/94365461-8eddd680-00d1-11eb-9554-c420152167ec.png">

Any idea what could be causing this with Alacritty?

**Comment by chrisduerr** [comment]
This is working as intended, the glyph is taken directly from your font and thus your font is responsible for sizing it correctly.

It probably works in Terminal.app and iTerm2 only because they draw their own glyphs rather than using the glyphs of your font.
