### ISSUE TITLE
What is up with those little blue boxes? 

### ISSUE THREAD

**Issue by Noya-santiago** [alacritty/alacritty#4267]
Whenever I Use that particular character, that little blue line appears. I don't know how to fix it and this problem is not existing in the kitty terminal emulator. I suspect is a problem with the Unicode font that I'm using (FiraCode) and not really an issue with alacritty, but I'm not sure. By the way, when the arrow Is looking to the left, there is no blue box. 

### System

OS: Arch Linux 
Version: alacritty 0.6.0-dev (I'm using the ligatures patch)
Linux/BSD: xfce 

Blue boxes/lines: https://i.imgur.com/HQupkCF.png 
![What is up with those little blue boxes](https://user-images.githubusercontent.com/62810706/94491230-35070a80-01be-11eb-826c-bbb91d43bd65.png)

The same character but mirrored: https://i.imgur.com/4SkhqOF.png

**Comment by kchibisov** [comment]
>Version: alacritty 0.6.0-dev (I'm using the ligatures patch)

Then report bugs to your fork, and not to us.

In general it seems like subpixel AA, which is presented in master and tracked https://github.com/alacritty/alacritty/issues/2693 .
