### ISSUE TITLE
Overlay full screen app option?

### ISSUE THREAD

**Issue by 12-Seconds** [alacritty/alacritty#4268]
### System

OS: macOS
Version: 0.5.0

In macOS, normally windows cannot overlay fullscreen windows. However, it is possible. I've made a hotkey window using Hammerspoon, which allows me call it wherever I want to. I've moved to Alacritty from iTerm2, and iTerm's hotkey window can overlay fullscreen apps. Would it be possible to do this with Alacritty as well?

**Comment by chrisduerr** [comment]
We already support all maximization and fullscreen options available on macOS. If you're looking for special window management, then that should be provided by macOS not Alacritty.

**Comment by 12-Seconds** [comment]
What I mean is, could there be an option to show Alacritty over fullscreen windows?

**Comment by chrisduerr** [comment]
I'm not sure what exactly you mean by that, but that doesn't sound like it should be something done by Alacritty.

**Comment by 12-Seconds** [comment]
This is what I mean:

![gif](https://user-images.githubusercontent.com/59331191/94525680-77275f00-0245-11eb-9c87-577bfb801f8d.gif)

Could Alacritty be able to do the same?

**Comment by chrisduerr** [comment]
> Could Alacritty be able to do the same?

There is no interest in implementing platform specific window management features in Alacritty.
