### ISSUE TITLE
CentOS Install.md update

### ISSUE THREAD

**Issue by klucar** [alacritty/alacritty#4271]
To build on CentOS, in addition to the stated packages I had to `yum install cargo` This pulled in rust also. I didn't test this but I assume the same is probably true for Fedora.

UPDATE: While building I had to install:

```
yum install libxcb-devel xcb-util-devel
```

**Comment by kchibisov** [comment]
It's mentioned that to build rust you need rust (yes, cargo also considered as rust), I guess it's kind of expected. If anything other than rust is required, you're free to send patches.

**Comment by chrisduerr** [comment]
If there's additional depedencies required, feel free to just open a Pull Request and add those. That's probably easier than creating an issue.

But cargo and Rust being required is just a general thing that is already covered in the documentation .

**Comment by klucar** [comment]
I updated my original issue with some libraries. Also, the documentation
says to open an issue if you find other required libraries so that’s what I
did.

**Comment by chrisduerr** [comment]
Should be fixed with https://github.com/alacritty/alacritty/pull/4272.
