### ISSUE TITLE
Correct documentation about "saving to clipboard" and how to install the package on "Gentoo Linux"

### ISSUE THREAD

**Issue by keks24** [alacritty/alacritty#4276]
Hello,

the documentation about `saving to clipboard` is a little bit misleading, since there are two types of clipboards<sup>1</sup> in Linux:

`PRIMARY` (copy on selection) and `CLIPBOARD` (copy via keyboard or mouse).

The instruction about how to install `alacritty` on Gentoo Linux is also wrong. It should be done like the following<sup>2</sup>:
```bash
$ emerge --ask x11-terms/alacritty
```

---
Sources:
<sup>1</sup> https://specifications.freedesktop.org/clipboards-spec/clipboards-latest.txt
<sup>2</sup> https://wiki.gentoo.org/wiki/Alacritty#Emerge (I also contributed to this Wiki article.)

**Comment by chrisduerr** [comment]
There's no reason to explicitly point out which clipboard it will be stored to, especially because this is primarily for other platforms. The Gentoo instructions also are not incorrect.

**Comment by kchibisov** [comment]
>The instruction about how to install alacritty on Gentoo Linux is also wrong. It should be done like the following

The instructions on how building from **source** and so they are correct, since emerge will install build deps for alacritty that way, there's no explicit instructions on how to install from package manager, since you should be capable of doing so on your own.

**Comment by keks24** [comment]
> The Gentoo instructions also are not incorrect.

So you are saying, that this is correct?
```bash
$ man 1 emerge
--onlydeps, -o
              Only merge (or pretend to merge) the dependencies of the packages specified, not the packages themselves.
```

This only installs the dependency packages of `x11-terms/alacritty`:
```bash
$ qdepends alacritty --verbose
[...]
RDEPEND="
    media-libs/fontconfig:1.0/1.0=
    media-libs/freetype:2
    x11-libs/libxcb:0/1.12=[xkb]
    media-libs/mesa[X]
    sys-libs/zlib
    sys-libs/ncurses:0
    x11-libs/libXcursor
    x11-libs/libXi
    x11-libs/libXrandr
"
[...]
```

I got all dependencies installed, so `alacritty` will not get installed using:
```bash
$ emerge --onlydeps x11-terms/alacritty
These are the packages that would be merged, in order:

Calculating dependencies... done!

Nothing to merge; quitting.

emerge --ask --onlydeps alacritty  5.51s user 0.47s system 17% cpu 34.285 total
```

**Comment by chrisduerr** [comment]
> So you are saying, that this is correct?

Yes I am. Please make sure you read the documentation before trying to execute random commands. This command does exactly what it is supposed to do.

**Comment by keks24** [comment]
Oh yes, indeed.

I was not paying close attention to the documentation. I was expecting, when the file is called `INSTALL.md`, then it is about installing the package.

Sorry, for the inconvenience.
