### ISSUE TITLE
Background transparency doesn't work

### ISSUE THREAD

**Issue by unihernandez22** [alacritty/alacritty#4281]
Same as #2254, but I can't comment there.

I'm in a VM of Void Linux with i3 + picom

Alacritty version: 0.5.0

**Comment by unihernandez22** [comment]
With Arch + i3 + picom it works (But it isn't a VM)

In the VM I tried with tilix and the transparency works.

**Comment by unihernandez22** [comment]
I didn't see #4217

**Comment by chrisduerr** [comment]
Duplicate of https://github.com/alacritty/alacritty/issues/42172 probably the fault of running a VM. Should work just fine on bare metal.
