### ISSUE TITLE
Building for development on NixOS

### ISSUE THREAD

**Issue by backwaterred** [alacritty/alacritty#4285]
Seems that a few of the contributors to this project are using NixOS, so I wanted to get an idea of how they are building Alacritty for development. Suggestions are appreciated! I'm relatively new to NixOS.

My process works, but is tedious. I have outlined it below.

1. As per INSTALL.md I run `nix-shell -A alacritty '<nixpkgs>'` to get a shell with all build deps.

_*Note:* This only sort-of works. I had to add the unstable channel and use `nix-shell -A alacritty '<nixpkgs-unstable>'` to get the current version of Rust-Stable since the one in the packages is currently meant to build alacritty 0.4.6 against Rust 1.41._

2. Build with `cargo build`

3. Patch the binary with patchelf:

I copied part of the installPhase (shell variable) which is set when I drop into the nix-shell and use it to correctly set the rpath. I ran the below instruction to patch a recent build.
```patchelf --set-rpath \"/nix/store/z8n258fss7gi6p8n3fkq5jhbyv7lajq1-expat-2.2.8/lib:/nix/store/qfxm1a8npwv2x39ixmmq3bhs9rxwflhl-fontconfig-2.13.92-lib/lib:/nix/store/cf6bkv1xlrp0vjqrmv51zbydjris4sq6-freetype-2.10.2/lib:/nix/store/acc72d5a2jsalp9cxl0jw22mz4qgyc6f-libGL-1.3.2/lib:/nix/store/liap55k4abd2sw7jfrnaigg1f2wphd03-libX11-1.6.8/lib:/nix/store/l1n6vl802s4phy17srl49v5vzha3kjg3-libXcursor-1.2.0/lib:/nix/store/hyhh3d220q8gc04k90rh7gz3mpn4dwaw-libXi-1.7.10/lib:/nix/store/1y6riwg8hg8kjavn21baax9cdp9rgpbk-libXrandr-1.5.2/lib:/nix/store/8hy6r5igvnngl29mnqv8h23kc0rv0k1k-libXxf86vm-1.1.4/lib:/nix/store/80yrvnyxv8xs4dlxl46y844s7dcpflzx-libxcb-1.13.1/lib:/nix/store/818lgfvnfqy17qc4p4nb89gfin2a2490-libxkbcommon-0.10.0/lib:/nix/store/8y7mlv61fs48bry4ryqxab0zmmy2f1pm-wayland-1.18.0/lib\" target/debug/alacritty```

The process described above works, but isn't very friendly. I could certainly automate this with a bash script, but there has got to be a better way. I have taken a look at the nix-side of things, but I'm hoping there is something I haven't come across that makes this particular build a nicer journey.

### System

OS: Linux
Version: 0.6.0-dev
Linux/BSD: X11, i3

**Comment by kchibisov** [comment]
>The process described above works, but isn't very friendly. I could certainly automate this with a bash script, but there has got to be a better way. I have taken a look at the nix-side of things, but I'm hoping there is something I haven't come across that makes this particular build a nicer journey.

I don't use NixOS myself, but I'm not sure that you can work around `patchelf`, since we're using `dlopen` and so you should patch for runtime deps...

Ideally you can setup Makefile or something like that for you to build/run/clean things, so you'll be using it instead of cargo (or whatever methods you have on your submarine).

I'll cc @cole-h , since I know that they deal with NixOS, so maybe they know something, but that's the only contributor that I can think of when it comes to using NixOS.

**Comment by kchibisov** [comment]
Closing, since not really a bug.

**Comment by cole-h** [comment]
I personally just change the `src` attr of the Alacritty derivation to point to my git checkout, but this means there's no incremental compilation (small change -> full recompile). A Makefile would probably be the best way to handle this.
