### ISSUE TITLE
Feat. request, change font/size remotely on running instance

### ISSUE THREAD

**Issue by paum3** [alacritty/alacritty#4287]
It is possibile to change font size remotely on running alacritty process?

I know, it sounds crazy, but could it be posibile to change font/size on running instance other way than send keystrokes by magic guy - xdotool?
thank you

**Comment by chrisduerr** [comment]
Yes, you can also just change it in the configuration file.

**Comment by paum3** [comment]
on a running instance ? It will reload config ? thx
