### ISSUE TITLE
Can't change background color

### ISSUE THREAD

**Issue by hekatonkheirex** [alacritty/alacritty#4288]
Hi all, like the title says, I can't change the background color. The picture below shows Kitty from the left and Alacritty from the right. Also tried urxvt pulling from .Xresources and the colors works fine. Here's the config file: https://pastebin.com/KyLwvUDA
![screenshot_20201004_174736](https://user-images.githubusercontent.com/63484218/95028500-fc13dd80-0676-11eb-8cc5-ebd606f3a4be.png)

**Comment by chrisduerr** [comment]
Your files indentation is incorrect, please match the documentation's configuration file or things will not work.

**Comment by hekatonkheirex** [comment]
Thanks! Just dropped the schemes section and went with the default config.
