### ISSUE TITLE
Colors look weird in Vim

### ISSUE THREAD

**Issue by Morantxu** [alacritty/alacritty#4289]
Hi, I've set a custom theme from a list in the official GitHub. However, some colors look really weird on vim, and this is only solved when setting $TERM to xterm-256color. However, this doesn't seem like a good solution. Any help?

**Comment by nixpulvis** [comment]
Vim does a pretty terrible job of terminal feature detection (often just looking for the string `xterm` in `$TERM`). I used to have this issue, which I solved with `env TERM=xterm-256color vim`, however I refactored my `vim` colors to use the base16 (+ 2 indexed colors), and I'm actually a lot happier in general now. It was a little bit of work however.

I can't speak from personal experience, but perhaps NeoVim would behave better for you?

**Comment by Morantxu** [comment]
Thx  ! I installed NEOVIM, way better :)
