### ISSUE TITLE
problem in compiling.

### ISSUE THREAD

**Issue by DarkPhoenix2005** [alacritty/alacritty#4290]
i am having trouble in compiling alacritty.
plz see below for more info...
### System

OS: Linux
Version: `it is not installed b'cause of an error.`
Linux : xfce4

### Additional info
this all setup is running on termux inside proot 

termux-info
```bash 
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://dl.bintray.com/termux/termux-packages-24/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# root-repo (sources.list.d/root.list)
deb https://dl.bintray.com/grimler/termux-root-packages-24 root stable
# unstable-repo (sources.list.d/unstable.list)
deb https://dl.bintray.com/xeffyr/unstable-packages unstable main
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.14.117-perf-g3e53970 #1 SMP PREEMPT Tue Sep 15 00:27:30 CST 2020 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 9 Pro
```

and for those who say its a problem of proot, i want to say that it was working fine when i installed it on a prooted' manjaro arm on this same device.

## Error
so, i was trying to compile alacritty on ubuntu arm and i get this error 
```bash
dark-phoenix@localhost:~/Files/TEMP/alacritty$  cargo build --release
error: failed to get `vte` as a dependency of package `alacritty_terminal v0.11.0-dev (/home/dark-phoenix/Files/TEMP/alacritty/alacritty_terminal)`

Caused by:
  failed to load source for dependency `vte`

Caused by:
  Unable to update https://github.com/alacritty/vte?rev=4f44023dab081f7da74fee14bc53b10ee8f96a1e#4f44023d

Caused by:
  the given reference name 'refs/remotes/origin/.l2s.master.lock0001' is not valid; class=Reference (4)
```
i am a newbie in linux. plz help me get over it.

**Comment by chrisduerr** [comment]
Do you have internet?

**Comment by DarkPhoenix2005** [comment]
yes

**Comment by chrisduerr** [comment]
How did you get Alacritty? Did you clone it, cd in and then run `cargo build --release`?

This seems to pretty clearly be an issue with your system, not with Alacritty. So you should probably look for help in a different place. Cargo's dependency resolution fails, that has nothing to do with Alacritty but instead is due to some error in your system.

**Comment by DarkPhoenix2005** [comment]
@chrisduerr yes i have done the same as give in the install.md
