### ISSUE TITLE
Import configuration file not working?

### ISSUE THREAD

**Issue by rieje** [alacritty/alacritty#4296]
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

OS: Arch Linux
Version: 0.5.0  (a6681e3a)

I have the following in my alacritty.yml:

    import:
      - /home/rieje/.config/alacritty/theme.yml

And in `~/.config/alacritty/theme.yml`, I have the theme:

```
# Colors (Solarized Light)
colors:
  # Default colors
  primary:
    background: '#fdf6e3' # base3
    foreground: '#657b83' # base00

  # Cursor colors
  cursor:
    text:   '#fdf6e3' # base3
    cursor: '#657b83' # base00

  # Normal colors
  normal:
    black:   '#073642' # base02
    red:     '#dc322f' # red
    green:   '#859900' # green
    yellow:  '#b58900' # yellow
    blue:    '#268bd2' # blue
    magenta: '#d33682' # magenta
    cyan:    '#2aa198' # cyan
    white:   '#eee8d5' # base2

  # Bright colors
  bright:
    black:   '#002b36' # base03
    red:     '#cb4b16' # orange
    green:   '#586e75' # base01
    yellow:  '#657b83' # base00
    blue:    '#839496' # base0
    magenta: '#6c71c4' # violet
    cyan:    '#93a1a1' # base1
    white:   '#fdf6e3' # base3
```

But it's still using the default theme in alacritty.yml (Tomorrow Night), which is already commented out. If I paste the Solarized Light theme above into alacritty.yml, it will correctly use this theme.

**Comment by chrisduerr** [comment]
> Version: 0.5.0 (a6681e3)

Because it's a feature only available in the latest master.
