### ISSUE TITLE
Feature: More granular padding configurability

### ISSUE THREAD

**Issue by Stakker** [alacritty/alacritty#4297]
If you have Alacritty permanently living in one static location on your desktop without the title bar, then it would also be useful for us fussy desktop tweakers to be able to change the padding separately for each edge to get your layout just right.

I know it's not a super common use case, but I'd imagine it's probably also a fairly easy feature to implement :-)

**Comment by chrisduerr** [comment]
This is a possible solution/workaround for https://github.com/alacritty/alacritty/issues/1671.

**Comment by ike** [comment]
Would this be essentially solved by @sodiumjoe's solution in #1290?

**Comment by chrisduerr** [comment]
Yes, though the comments in #1290 still apply. The benefit of this is questionable and a usecase has not sufficiently been elaborated.

Doing it because it's a "fairly easy feature to implement", is not a good reason to add new features. Features have maintenance cost and should always come with a significant improvement to Alacritty's users. Especially with a configuration file change all changes have to immediately fight the inconvenience of the grown config size as a hurdle.

**Comment by ike** [comment]
Where do you land on the macos-specific-fix <-> padding-configurable spectrum?

**Comment by chrisduerr** [comment]
Making padding configurable by itself is not a reason. And this is not a fix for the macos issue at all.

**Comment by ike** [comment]
Gotcha -- has the macos transparent padding issue been addressed in a different way? I have read #1671 but am curious if there are other workarounds or preferred methods.

**Comment by chrisduerr** [comment]
It has not.

**Comment by Stakker** [comment]
Yeah fighting bloat & complexity is a good goal (and it aligns with Alacritty's "vision"), so I'll survive without the extra conf :-)

**Comment by ike** [comment]
So perhaps this is a `wont-implement` feature?

**Comment by jvantuyl** [comment]
One other comment on this one.  With Apple adding the "notch" into the top of MacBook screens, there's yet-another-reason-to-add-configurable padding.

While I'm all for solving concrete problems, we can't be psychic and we can't be prescient.  There are a lot of different reasons that we know and that we don't know that configurable padding would help.  Granular config of padding solves them all... categorically... forever.

**Comment by chrisduerr** [comment]
This is not a fix for titlebar height or any other nonsense Apple might come up with in the future. It's at best a hacky workaround. As such the issues should be properly solved and I will happily accept PRs doing so.

> While I'm all for solving concrete problems, we can't be psychic and we can't be prescient.

There's no need to be psychic. Terminals from 300 years ago are still being used today without any problems by many people. We don't need to implement things that have no usecase yet, speculating on what features might be useful in the future is just a really bad idea.

**Comment by jvantuyl** [comment]
Dude.  There have already been **three** use-cases proposed.

Not that it should matter so much.  Consider `window.position`.  Nobody complained we needed an exact use-case for this.  Nobody claimed that it was a poor solution to the myriad problems it solves.  It's a generic feature, with many uses, present in virtually every similar project, added without fuss... just like the proposed explicit padding setting.

Moreover, this can't easily be replicated by another project.  `tmux` can't work with this padding.  Window Managers really can't touch this either.  `alacritty` is the only place this can be implemented as far as I can tell.  Even `window.position` could've been implemented by a window manager... who else can insert padding into the window?

And this exact feature isn't even unprecedented.  You'll find people doing this with virtually every terminal in existence.  To wit:
* all X11 terminals do this, here's just [xterm](https://www.reddit.com/r/linux/comments/17jx0m/how_can_i_add_padding_to_the_terminal_application/)
* someone else doing this with [a variety of other terminals](https://discuss.getsol.us/d/5202-padding-on-terminal-apps/2) including Konsole
* [gnome-terminal](https://askubuntu.com/questions/115762/increase-padding-in-gnome-terminal)
* [a weird xterm in JavaScript for the web](https://github.com/xtermjs/xterm.js/issues/946)

There are probably a dozen more, but I figure you can operate Google as well as me.  People want this.  Everywhere.  Indeed, they even expect this.  Layout control is essentially remedial.

Moreover, you'll find most of the other maintainers to be significantly more helpful.  Heck, in the Solus discussion, `alacritty` was explicitly mentioned alongside `kitty`, and `kitty` was implicitly recommended over it.  Software is not a popularity contest, but I don't know why you'd write it if you don't want it used.

If you're dead-set against implementing this, are there other options you'd prefer?  I've heard a lot of "I don't like this." but not much "I'd tackle it this way instead."

Would it suit you better to instead add an "alignment" option?  Basically, when you've got extra padding, what do you do with it?  This seems unwieldy but it would tackle other use cases.  Could we maybe mark it as experimental and you can remove it later if it's that much of a problem ([spacebar heating](https://xkcd.com/1172/) notwithstanding)?

**Comment by Lambdaphile** [comment]
> Features have maintenance cost and should always come with a significant improvement to Alacritty's users. 

Whats the criteria of "significant improvement"? How many issues are out there about this feature request? Is Alacritty an open source tool for use by people or just a thing to rub your own ego? Can't decide if I should get angry or laugh while reading Alacritty's issue section.

**Comment by kchibisov** [comment]
>You seem focused on working around macOS issues that have very clear proper solutions. If your goal is to solve those issues, send patches to Alacritty/upstream to fix that issue. Configurable padding is not a solution to the issues you've mentioned.

This issue is indeed questionable if you try to work around content obscuring the decorations.

>Whats the criteria for "significant improvement"? How many issues are out there about this feature request? Is Alacritty an open source tool for use by people or just a thing to rub your ego? Can't decide if I should get frustrated or laugh while reading Alacritty's issue section.

I think this issue is the same as https://github.com/alacritty/alacritty/issues/6444 which is justified. Our upstream library could just say expose that information about decorations though it so we automatically offset everything.

I'll close this issue in prior to mentioned one.
