### ISSUE TITLE
alacritty not launching

### ISSUE THREAD

**Issue by nerdthatnoonelikes** [alacritty/alacritty#4298]
I had fish installed and then I uninstalled fish after uninstalling fish alacritty would no longer open.
### System

OS: Linux
Version: alacritty 0.5.0
Linux/BSD: X11/, DE: XFCE
### Logs
Created log file at "/tmp/Alacritty-20091.log"
[2020-10-08 17:04:34.977429875] [ERROR] Failed to spawn command '/bin/fish': No such file or directory (os error 2)

**Comment by chrisduerr** [comment]
If you uninstall the shell that you use in Alacritty, then of course Alacritty doesn't work anymore. Change your shell or install it again.
