### ISSUE TITLE
vim/neovim reescaling problem when resizing or maximize the window(Windows 10)

### ISSUE THREAD

**Issue by CesarB794** [alacritty/alacritty#4307]
I am having content rescaling issues when using neovim within Alacritty on Windows 10.
I use PowerShell with the PSReadLine module to use vi inside, as if it were a unix shell. And I have Install neovim using the chocolatey package manager.
I mentioned the problem to the PSReadLine developers and they told me that the problem was possibly coming from neovim with / or alacritty.
The problem only occurs in Alacritty and in Windows Terminal, in the native PowerShell console the problem does not exist.
It happens both when resizing the window, and when maximizing it.
I will attach some screenshots.
OS: Windows 10 1909.
Alacritty version: 0.5.0
Shell: Powershell 7.1
Neovim version: 0.4.3
Native PowerShell console:
![2020 10 11-07 56_01](https://user-images.githubusercontent.com/54776512/95676834-7d97ce00-0b97-11eb-89c4-8f7b34f8afb8.png)
![2020 10 11-07 56_02](https://user-images.githubusercontent.com/54776512/95676837-7ffa2800-0b97-11eb-9c0e-d7e532b856f8.png)
Alacritty:
![2020 10 03-00 55](https://user-images.githubusercontent.com/54776512/95676478-d6b23280-0b94-11eb-8c01-17f9e0c608f9.png)
![2020 10 03-01 06](https://user-images.githubusercontent.com/54776512/95676481-d9148c80-0b94-11eb-8a3a-b7b32f53b85a.png)

**Comment by chrisduerr** [comment]
As you have already figured out with the Windows Terminal, this is not an Alacritty issue. Which is why it works perfectly fine on every platform other than Windows. It's just Windows being really bad at terminals.

**Comment by CesarB794** [comment]
> As you have already figured out with the Windows Terminal, this is not an Alacritty issue. Which is why it works perfectly fine on every platform other than Windows. It's just Windows being really bad at terminals.

The problem in the end was neovim. Upgrading to beta 0.5 the problem disappeared.
In this case Windows was not to blame haha ...
Anyway, thanks for your time.

**Comment by chrisduerr** [comment]
>  In this case Windows was not to blame haha ...

Oh I wouldn't be so sure neovim didn't just add a workaround for a Windows problem. :)
