### ISSUE TITLE
Messed up keys in Midnight Commander

### ISSUE THREAD

**Issue by elundmark** [alacritty/alacritty#4308]
In Mightnight Commander on Debian, shortcut for renaming file that is `Shift+F6` in xfce4-terminal, is `Shift+F4` in alacritty. From what I can remember, __st__ also had a similar problem, but I can't be sure.

### System

OS: Linux
Version: alacritty 0.6.0-dev (56e0f5b)
Linux/BSD: Debian GNU/Linux bullseye/sid x86_64, i3wm on X11

### Logs

Font/Terminal size: https://gist.github.com/elundmark/c50d994336d6717af71df07345ddbc59
Keyboard and bindings: https://gist.github.com/elundmark/15aff609f1829fb1a40f5144753d7248

**Comment by kchibisov** [comment]
Could you try `TERM=xterm-256color mc`?

**Comment by elundmark** [comment]
> Could you try `TERM=xterm-256color mc`?

Fantastic solution, all shortcuts work now :-)

**Comment by kchibisov** [comment]
yeah, fix broken mc.

**Comment by trofi** [comment]
Worked around in https://midnight-commander.org/ticket/4149
