### ISSUE TITLE
Alacritty crashes on latest Linux kernel, wayland and gnome desktop

### ISSUE THREAD

**Issue by jirgn** [alacritty/alacritty#4312]
alacritty is crashing while starting on a linux system with latest kernel,  wayland and gnome-shell versions.
Nothing happens in the UI, I only see  a core dump in the system logs.
It looks like the latest gnome-desktop upgrade introduced this with the latest performance improvements.
https://help.gnome.org/misc/release-notes/3.38/

### System
OS: Arch Linux x86_64 
Version: alacritty 0.5.0 (a6681e3a)
WM: Mutter (Wayland 1.18.0-2)
Host: 20L80016MH ThinkPad T480s 
Kernel: 5.8.14-arch1-1 
Packages: 1286 (pacman), 2 (flatpak), 12 (snap) 
Shell: zsh 5.8 
Resolution: 2560x1440 
DE: GNOME 3.38.1 
CPU: Intel i7-8650U (8) @ 4.200GHz 
GPU: Intel UHD Graphics 620 

### Logs
```
Process 3274 (alacritty) of user 1000 dumped core.

Stack trace of thread 3274:
#0  0x00007fd1897fd615 raise (libc.so.6 + 0x3d615)
#1  0x00007fd1897e6862 abort (libc.so.6 + 0x26862)
#2  0x00005629f8643298 n/a (alacritty + 0x19d298)
#3  0x00007fd189b4bf6b n/a (libwayland-client.so + 0x9f6b)
#4  0x00007fd189b48662 n/a (libwayland-client.so + 0x6662)
#5  0x00007fd189b49ccc wl_display_dispatch_queue_pending (libwayland-client.so + 0x7ccc)
#6  0x00007fd189b4a160 wl_display_roundtrip_queue (libwayland-client.so + 0x8160)
#7  0x00005629f8837a02 n/a (alacritty + 0x391a02)
#8  0x00005629f854aa51 n/a (alacritty + 0xa4a51)
#9  0x00005629f85371a5 n/a (alacritty + 0x911a5)
#10 0x00005629f85ce32b n/a (alacritty + 0x12832b)
#11 0x00005629f88294d3 n/a (alacritty + 0x3834d3)
#12 0x00005629f85cdf58 n/a (alacritty + 0x127f58)
#13 0x00007fd1897e8152 __libc_start_main (libc.so.6 + 0x28152)
#14 0x00005629f850a0ee n/a (alacritty + 0x640ee)

**Comment by chrisduerr** [comment]
This looks like a Wayland problem, could you compile with debug symbols enabled?

**Comment by kchibisov** [comment]
Should be fixed on master.

**Comment by doronbehar** [comment]
3.38 gnome has landed in many distributions so it'd be nice to get this in a release soon :pray:.

**Comment by kchibisov** [comment]
https://github.com/alacritty/alacritty/releases/tag/v0.6.0-rc1

**Comment by doronbehar** [comment]
I meant a non-rc release., but that's a matter for the distribution to decide I guess. 0.6.0rc-1 indeed works.

**Comment by kchibisov** [comment]
I'm saying that rc process is going on right now, we can't accelerate it, if no bugs will be reported for the current rc release in e.g. week, the actual release will appear.
