### ISSUE TITLE
Crash in XRDP session

### ISSUE THREAD

**Issue by pmeiyu** [alacritty/alacritty#4314]
## System

OS: NixOS/Linux
Version: 0.5.0
Linux/BSD: XRDP, X11, i3 window manager

## Steps to reproduce the bug

- Setup XRDP server on a Linux machine.
- Connect to the machine via xfreerdp.
- Start alacritty and it will crash.

## Logs

> 
> Created log file at "/tmp/Alacritty-3721.log"
> [2020-10-14 17:13:48.785493105] [ERROR] Alacritty encountered an unrecoverable error:
> 
> 	Error creating GL context; Received multiple errors. Errors: `[OsError("Could not create EGL display object"), OsError("`glXQueryExtensionsString` found no glX extensions")]`
> 
>

**Comment by chrisduerr** [comment]
You use RDP between two Linux machines?

This seems like an RDP OpenGL problem, so nothing Alacritty can do. Chances are other applications like `glxgears` also won't start?

**Comment by pmeiyu** [comment]
> You use RDP between two Linux machines?

Yes.

> This seems like an RDP OpenGL problem, so nothing Alacritty can do. Chances are other applications like `glxgears` also won't start?

Of course there is something Alacritty can do.  Even if the environment does meet Alacritty's requirements for GPU acceleration, it should print a helpful message rather than crash.

**Comment by chrisduerr** [comment]
That is your helpful message. It can't do OpenGL and it states that pretty clearly.

**Comment by pmeiyu** [comment]
> That is your helpful message. It can't do OpenGL and it states that pretty clearly.

Well, as a programmer, I don't think that message is "pretty clear".
