### ISSUE TITLE
Fedora 33: File conflict

### ISSUE THREAD

**Issue by oscpe262** [alacritty/alacritty#4315]
File conflict with ncurses-base (dependency: dnf package manager).

### System

OS: Linux Fedora 33
Version: 0.5.0-1.fc33

### Logs
dnf install alacritty
Last metadata expiration check: 0:21:58 ago on Wed 14 Oct 2020 11:28:52 PM CEST.
Dependencies resolved.
 Package          Architecture  Version               Repository                                                Size
Installing:
 alacritty        x86_64        0.5.0-1.fc33          copr:copr.fedorainfracloud.org:pschyska:alacritty        1.9 M

Transaction Summary
Install  1 Package

Total download size: 1.9 M
Installed size: 5.9 M
Is this ok [y/N]: y 
Downloading Packages:
alacritty-0.5.0-1.fc33.x86_64.rpm                                                    8.1 MB/s | 1.9 MB     00:00    

Total                                                                                7.9 MB/s | 1.9 MB     00:00     
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction test error:
  file /usr/share/terminfo/a/alacritty from install of alacritty-0.5.0-1.fc33.x86_64 conflicts with file from package ncurses-base-6.2-3.20200222.fc33.noarch

**Comment by kchibisov** [comment]
Report it to whoever provides a package for alacritty on your system, that has nothing to do with alacritty.

cc @pschyska

**Comment by pschyska** [comment]
> Report it to whoever provides a package for alacritty on your system, that has nothing to do with alacritty.

I shall provide. On it

**Comment by pschyska** [comment]
The issue is fixed in [copr](https://copr.fedorainfracloud.org/coprs/pschyska/alacritty/). The X11 version worked on my F33 Beta installation. Wayland crashes due to #4206, which should be fixed in 0.6.0 IIUC.

**Comment by mikeslattery** [comment]
Duplicate of #4518
