### ISSUE TITLE
Feature: Differnent cursor thickness for focused and unfocused windows

### ISSUE THREAD

**Issue by matthewhughes934** [alacritty/alacritty#4320]
Example use case (my personal preference): allow a thick underline for a cursor in the active window and a very thin box in the inactive window, with thickness determined by e.g. a `cursor.unfocused_thickness` config variable

I understand this may be a rather uncommon use case, but if there is support for it I'd be happy to try implementing it.

**Comment by chrisduerr** [comment]
I personally was already skeptical of the general cursor thickness configuration, though @kchibisov convinced me otherwise. I'd definitely draw the line here and say this is too much.

@kchibisov since you were the advocate for adding a cursor thickness configuration, I'm curious about your thoughts on the matter.

**Comment by kchibisov** [comment]
>I personally was already skeptical of the general cursor thickness configuration, though @kchibisov convinced me otherwise. I'd definitely draw the line here and say this is too much.

Yeah, I agree, that's going to far. Alternatively we can use predefined HollowBlock thickness and that's it, adding configuration for unfocused thickness isn't an option.

**Comment by chrisduerr** [comment]
> Alternatively we can use predefined HollowBlock thickness and that's it

What do you mean by this?

**Comment by kchibisov** [comment]
>What do you mean by this?

I mean to use some hardcoded value for HollowBlock thickness, like 0.15.

**Comment by chrisduerr** [comment]
You mean increase the thickness of the hollow block cursor in general?

**Comment by kchibisov** [comment]
I guess the goal is not to increase, since it becomes more like block cursor, but decrease, but I don't want it extra thin, so we can use the default thickness value for Hollow Block cursor, which is 0.15.

So we not making it thicker, we just not apply thickness to it.

**Comment by kchibisov** [comment]
But I personally like applying thickness to hollow block cursor, since it's more visible, so  I don't think that we should do anything at all here.

If downstream wants to make certain cursor thinner, they can patch their sources here.

**Comment by chrisduerr** [comment]
I don't think this warrants any changes to Alacritty, being able to modify cursor thickness to your liking should already suffice for most users, going beyond that is done better by patching the source if you *really* need it.

If there are some actual problems with the thickness, that's a different matter of course, but I don't think that's the case.
