### ISSUE TITLE
Right click copy till where I clicked, not the whole selection

### ISSUE THREAD

**Issue by blueray453** [alacritty/alacritty#4324]
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System
OS: Linux Mint 20
Version: `alacritty 0.5.0`
Linux/BSD: X11, Cinnamon

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

I am using:
```
mouse_bindings:
  - { mouse: Middle, action: PasteSelection }
  - { mouse: Right, action: CopySelection }
```
I am having few Issues (At least counter-intuitive behaviour).

**Issue 1**
If I copy something from the terminal, I can not paste it outside the terminal.

**Issue 2**
Suppose I am trying to copy the line:

```
drwxrwxr-x    - blueray 17 Sep 18:42 .vscode
```
If I click and drag from the beginning of the line till the end of the line, then right click in the beginning of the line - It copies the whole line and **deselect the selection** which is an expected behaviour.

However, If I click and drag from the beginning of the line till the end of the line, then right click in the end of the line - It copies the whole line but **does not deselect the selection**.

If I click and drag from the end of the line till the beginning of the line, then right click in the end of the line - It copies the whole line and **deselect the selection** - which is also an expected behaviour.

However, If I click and drag from the end of the line till the beginning of the line, then right click in the beginning of the line - It copies the whole line but **does not deselect the selection**.

**Issue 3**

Suppose I am trying to copy the line:

```
drwxrwxr-x    - blueray 17 Sep 18:42 .vscode
```
If I click and drag from the beginning of the line till the end of the line, then right click anywhere in the middle of the selection - It copies from beginning of the line till where I right clicked (though the whole line is selected).

Again, If I click and drag from the end of the line till the beginning of the line, then right click anywhere in the middle of the selection - It copies from end of the till where I right clicked (though the whole line is selected).

I was expecting that it will copy the whole like as I selected the whole line regardless of wherever I click on the line .

**Comment by kchibisov** [comment]
>If I copy something from the terminal, I can not paste it outside the terminal.

How are you testing it? Are you pressing middle mouse button to paste? Also, if you've copied text with `Ctrl + shift + c` are you pasting with `Ctrl + V` in other applications which uses `Ctrl + V` as a shortcut?

>However, If I click and drag from the end of the line till the beginning of the line, then right click in the beginning of the line - It copies the whole line but does not deselect the selection.

That's expected, right click expands selection from start of the selection to the point you've clicked, it shouldn't deselect anything.

>If I click and drag from the beginning of the line till the end of the line, then right click in the beginning of the line - It copies the whole line and deselect the selection which is an expected behaviour.

It doesn't deselect, it makes empty selection, and thus it's not copied.

>Issue 3

>Again, If I click and drag from the end of the line till the beginning of the line, then right click anywhere in the middle of the selection - It copies from end of the till where I right clicked (though the whole line is selected).

That's expected, right click alters the selection, so

**Comment by blueray453** [comment]
> How are you testing it?

Suppose I am trying to copy the line:

`drwxrwxr-x    - blueray 17 Sep 18:42 .vscode`

I select the line. Right click. Then open vscode. Then `ctrl+v` there.

It does not pasted the line copied from the terminal.

**Comment by blueray453** [comment]
I am trying to create a log file using `alacritty --print-events`. However, It delete the log file (in `/tmp`) after I close the terminal. is there any way I can keep the log file.

**Comment by kchibisov** [comment]
>I am trying to create a log file using alacritty --print-events. However, It delete the log file (in /tmp) after I close the terminal. is there any way I can keep the log file.

Press middle mouse button, you're copying to primary selection buffer, which is on middle mouse on Linux. If you want to copy to clipboard buffer, use `Copy`, but I'd say not to bind anything on rmb, since it's used for selection expansion already...

**Comment by blueray453** [comment]
NIce, middle mouse button, in vscode works.

Is there any way I can deselect after right `CopySelection`.

And also, is there any solution I can use so that if I right click anywhere in the middle of the selection, it copy the whole line.

**Comment by kchibisov** [comment]
>And also, is there any solution I can use so that if I right click anywhere in the middle of the selection, it copy the whole line.

I don't see a point why you need right click in that equation, just selecting anything on Linux will already copy things (the transfer won't happen until you paste though), no need to do extra work. So triple clicking on Linux will already copy the entire line, without doing anything extra.

**Comment by blueray453** [comment]
Wow! Thank you very much. I am now feeling like an alacritty Pro.

**Comment by kchibisov** [comment]
>Wow! Thank you very much. I am now feeling like an alacritty Pro.

fyi, it generally works in every application on Linux + X11, just select and it's auto copied to primary selection buffer, so you can paste from it, nothing special about alacritty here.
