### ISSUE TITLE
How to keep cursor nerer changed even lost focus?

### ISSUE THREAD

**Issue by akane-sora** [alacritty/alacritty#4329]
I saw the issue https://github.com/alacritty/alacritty/issues/794
Which required the cursor to change when the windows lost focus.
However I want to CLOSE this feature since not only I don't need it, but I do have different opacity for inactive window, this behavior makes whole thing not smoothly.

Do we have any config option for this?

**Comment by chrisduerr** [comment]
https://github.com/alacritty/alacritty/blob/master/alacritty.yml#L352
