### ISSUE TITLE
Vi mode: editing the command line (feature request)

### ISSUE THREAD

**Issue by d4h0** [alacritty/alacritty#4336]
If a user enters vi mode and moves the cursor, after pressing `i` the cursor jumps back to the original cursor position (where the cursor was before entering vi mode).

It would be nice if vi mode could be used to edit the command line. Are there any plans to support this?

**Comment by chrisduerr** [comment]
No and that doesn't work either. You want vi mode in your shell.

**Comment by d4h0** [comment]
@chrisduerr: Ah, right, that makes sense. Thanks for the tip!

**Comment by chrisduerr** [comment]
Fyi, most shells like bash and zsh already do support this. The feature should be complementary and I use both myself constantly.

Though it can get a bit confusing when you have weechat vi mode, zsh vi mode and alacritty vi mode all at the same time.

**Comment by d4h0** [comment]
Thanks again, @chrisduerr!

For people who land here and are interested in this:

For Bash, add `set -o vi` to your Bash config file.
