### ISSUE TITLE
Transparency not working with Pop OS 20.10

### ISSUE THREAD

**Issue by JFitzy1321** [alacritty/alacritty#4339]
### System

OS: Pop OS 20.10
Version: alacritty 0.6.0-dev
Gnome Desktop

I just downloaded and installed Pop os 20.10 in virt-manager. After installation, I installed alacritty and started modifying alacritty.yml file. I haven't changed any other system settings, and the only other package I've installed so far is fish and gnome-tweaks.
When I modify the background_opacity settings, nothing changes. Background is still a solid black no matter what value I change it to.

And yes my spacing is correct, I've worked with yaml files before.

**Comment by kchibisov** [comment]
So is it running in a vm? It could be a vm specific issue then.

**Comment by chrisduerr** [comment]
Duplicate of #4217.

**Comment by JFitzy1321** [comment]
Problem is now present on my actual installation of Pop 20.04 after an update to alacritty package today.
![alacritty-error-pop-20-04](https://user-images.githubusercontent.com/32967490/97086273-72a15c80-15df-11eb-98ef-7bd5a1c93132.png)

**Comment by JFitzy1321** [comment]
I haven't made any changes to my actual config file, all I did was update my system this morning and now alacritty is showing errors.

**Comment by chrisduerr** [comment]
You need to fix your configuration file.

**Comment by JFitzy1321** [comment]
What changed though? There was nothing wrong with my config file on my real system until this update?

**Comment by chrisduerr** [comment]
https://github.com/alacritty/alacritty/blob/master/CHANGELOG.md

**Comment by JFitzy1321** [comment]
Issue fixed, found a rogue :  My bad
