### ISSUE TITLE
feature: keep input line at the top

### ISSUE THREAD

**Issue by basaran** [alacritty/alacritty#4340]
Hello,

Would it be possible to have an option to keep the command line always fixed to the top of the alacritty window? I understand this could rather be a bizarre and not possible to achieve request, but main benefit would be more for the neck and eye ergonomics, especially when using a window manager and keeping a narrow terminal area on a large display.

![image](https://user-images.githubusercontent.com/30809170/97071210-d6f6f880-15ac-11eb-9fa3-5ee062e15bd5.png)

**Comment by kchibisov** [comment]
>Would it be possible to have an option to keep the command line always fixed to the top of the alacritty window? I understand this could rather be a bizarre and not possible to achieve request, but main benefit would be more for the neck and eye ergonomics, especially when using a window manager and keeping a narrow terminal area on a large display.

No, it's not possible, we don't know what you're running inside, and we don't know what the prompt is. It's also not possible to do in your shell, since shell can't access scrollback, since there's no escape sequence(that exists) to do that.

In anyway, from alacritty side it's purely impossible to do, and on your screen shot you're providing a screenshot from tmux, hence another terminal emulator...

**Comment by chrisduerr** [comment]
> It's also not possible to do in your shell, since shell can't access scrollback, since there's no escape sequence(that exists) to do that.

I mean in theory you could just run `clear` in your prompt.

**Comment by kchibisov** [comment]
>I mean in theory you could just run clear in your prompt.

I mean the point is to keep the output afterward, I guess, otherwise I don't see a point of clear...

**Comment by basaran** [comment]
Thank you for the clarification. I wasn't really referring to making a whole change of flow of terminal functionalities and internals. It could be an optional ui input element area at the top, that inputs into the terminal at the bottom as usual. Anyhow, thank you again for getting back.
