### ISSUE TITLE
error: attributes are not yet allowed on if expressions

### ISSUE THREAD

**Issue by timonson** [alacritty/alacritty#4341]
### System

Debian 10.6.0
alacritty: master

### Problem

I try to build alacritty on a newly installed debian distro.

After installing debian I ran: 

```bash
apt-get --yes install cmake pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev python3 cargo git
git clone https://github.com/alacritty/alacritty
cd alacritty
cargo build --release
```

Shortly before finishing it throws the following error: 

> error: attributes are not yet allowed on 'if' expressions

![alacritty-2020-10-24](https://user-images.githubusercontent.com/54777088/97077866-72a55a80-15e7-11eb-9eae-f4d26f11ffe8.png)

**Comment by kchibisov** [comment]
The minimum supported rust version is 1.43.0.

**Comment by slaveofcode** [comment]
Got the same problem, trying to upgrade my rust to 1.50 solves this error
