### ISSUE TITLE
Alacritty not opening 

### ISSUE THREAD

**Issue by Jimmysit0** [alacritty/alacritty#4343]
OS: Linux
Version: alacritty 0.5.0
Linux/BSD: Wayland

When I try to open alacritty, it just doesn't launch, it's my first time with this experience and this is a fresh EndeavourOS install.

**Comment by kchibisov** [comment]
try building from master if you're running gnome or similar. if not provide backtrace,

**Comment by Jimmysit0** [comment]
How to provide backtrace? I'm on gnome, and I built from master already

**Comment by chrisduerr** [comment]
> I'm on gnome, and I built from master already

If you build from master, your version will not be 0.5.0.

**Comment by Jimmysit0** [comment]
Pretty sure I did, but I'll try reinstalling it, maybe I'm just confused, if the error persist, I'll come back here, if it doesn't I'll close the issue, thanks by the way

**Comment by chrisduerr** [comment]
Until `alacritty --version` reports `alacritty 0.6.0-dev`, you're not running master.

**Comment by Jimmysit0** [comment]
error: could not compile `alacritty`.

Caused by:
  process didn't exit successfully: `rustc --crate-name alacritty --edition=2018 alacritty/src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto -C debuginfo=1 --cfg 'feature="default"' --cfg 'feature="wayland"' --cfg 'feature="wayland-client"' --cfg 'feature="winpty"' --cfg 'feature="x11"' --cfg 'feature="x11-dl"' -C metadata=69b6a27817da0321 -C extra-filename=-69b6a27817da0321 --out-dir /home/jimmy/alacritty/target/release/deps -L dependency=/home/jimmy/alacritty/target/release/deps --extern alacritty_terminal=/home/jimmy/alacritty/target/release/deps/libalacritty_terminal-25a1876ad448385a.rlib --extern clap=/home/jimmy/alacritty/target/release/deps/libclap-a4260f2965bde9cc.rlib --extern copypasta=/home/jimmy/alacritty/target/release/deps/libcopypasta-5de3fa30495a65c4.rlib --extern crossfont=/home/jimmy/alacritty/target/release/deps/libcrossfont-90b9c938e676370a.rlib --extern fnv=/home/jimmy/alacritty/target/release/deps/libfnv-5c3f4aa46faf2810.rlib --extern glutin=/home/jimmy/alacritty/target/release/deps/libglutin-6f901f740a23b943.rlib --extern image=/home/jimmy/alacritty/target/release/deps/libimage-50c8922bf46ae5f1.rlib --extern libc=/home/jimmy/alacritty/target/release/deps/liblibc-1ab04d93d036e721.rlib --extern log=/home/jimmy/alacritty/target/release/deps/liblog-7bdb1fc1bd32790e.rlib --extern notify=/home/jimmy/alacritty/target/release/deps/libnotify-2fc8cf9d5a1b8d62.rlib --extern parking_lot=/home/jimmy/alacritty/target/release/deps/libparking_lot-905176e25af3df1c.rlib --extern serde=/home/jimmy/alacritty/target/release/deps/libserde-adfefa67735a78fd.rlib --extern serde_json=/home/jimmy/alacritty/target/release/deps/libserde_json-20704604d44e7b88.rlib --extern serde_yaml=/home/jimmy/alacritty/target/release/deps/libserde_yaml-cdd54d060e099b3a.rlib --extern time=/home/jimmy/alacritty/target/release/deps/libtime-ecebebe2dc076aec.rlib --extern unicode_width=/home/jimmy/alacritty/target/release/deps/libunicode_width-88c23923dffb4ea3.rlib --extern urlocator=/home/jimmy/alacritty/target/release/deps/liburlocator-0598a5c8cfda6467.rlib --extern wayland_client=/home/jimmy/alacritty/target/release/deps/libwayland_client-6e2c9dd50060c240.rlib --extern x11_dl=/home/jimmy/alacritty/target/release/deps/libx11_dl-1226a48e436aec06.rlib --extern xdg=/home/jimmy/alacritty/target/release/deps/libxdg-3bae084349fe1a30.rlib -L native=/usr/lib -L native=/usr/lib -L native=/usr/lib -L native=/usr/lib` (signal: 9, SIGKILL: kill)

**Comment by chrisduerr** [comment]
How much memory do you have available?

**Comment by Jimmysit0** [comment]
In my drive, more than 490gb

**Comment by chrisduerr** [comment]
I'm asking about system memory/RAM. Not storage capacity.

**Comment by Jimmysit0** [comment]
16gb

**Comment by chrisduerr** [comment]
Which rustc version?

**Comment by Jimmysit0** [comment]
rustc 1.47.0. Tried to install following the guide (https://github.com/alacritty/alacritty/blob/master/INSTALL.md) and it installed, but the version 0.5.0 Not sure if it shall be like that

**Comment by Jimmysit0** [comment]
And, the problem is still there, not opening.

**Comment by chrisduerr** [comment]
> Tried to install following the guide (https://github.com/alacritty/alacritty/blob/master/INSTALL.md)

Which part of that instruction did you follow? There are multiple different ways to install Alacritty documented in that file.

**Comment by Jimmysit0** [comment]
I installed the dependencies, then built with cargo build --release. Then made the desktop entry and finally I did the shell completion. Also, this was the link I cloned https://github.com/alacritty/alacritty.git

**Comment by chrisduerr** [comment]
And how did you execute it?

**Comment by Jimmysit0** [comment]
I added it to favorites, then I executed it.

**Comment by Jimmysit0** [comment]
bash: /home/jimmy/alacritty/alacritty/extra/completions/alacritty.bash: No such file or directory
hmmmmm

**Comment by chrisduerr** [comment]
You're aware that the executable is in `./target/release/alacritty`, right? That's the file you should be executing.

**Comment by Jimmysit0** [comment]
There's no ./target/release/alacritty path for me

**Comment by Jimmysit0** [comment]
I just execute Alacritty.desktop

**Comment by chrisduerr** [comment]
> There's no ./target/release/alacritty path for me

That's where the binary is output when running `cargo build --release`. Did that command never finish successfully for you?

**Comment by Jimmysit0** [comment]
It finished successfully, that's weird. I already built, but here's a screenshot to prove that the command works
![image](https://user-images.githubusercontent.com/69643443/97094230-a482e500-1618-11eb-9bcc-6668f9fae132.png)

**Comment by chrisduerr** [comment]
Which directory did you execute that from? Is there any `./target/release/alacritty` or `../target/release/alacritty`?

**Comment by Jimmysit0** [comment]
I did from /home/jimmy/alacritty/alacritty
(jimmy is my user obviously)

**Comment by chrisduerr** [comment]
Then the latter will probably work for you?

**Comment by Jimmysit0** [comment]
Not sure what do you mean, but my issue is that alacritty does not start, also, I get this when I open my terminal bash: /home/jimmy/alacritty/alacritty/extra/completions/alacritty.bash: No such file or directory

**Comment by chrisduerr** [comment]
alacritty.bash is not the Alacritty executable. You should be able to navigate your filesystem to find the `alacritty` executable in the directories I've specified.

If you're unable to do that, then chances are you're better off just waiting until a package maintainer can provide a working Alacritty version for you.

**Comment by chrisduerr** [comment]
Closing since this is likely the gnome crash that will be fixed with the next release.
