### ISSUE TITLE
Bash Prompt Decorations

### ISSUE THREAD

**Issue by bridgesense** [alacritty/alacritty#4344]
### System

OS: Fedora 32
Version: 0.5.0 (compiled from source as of Oct 23rd, 2020)
Linux/BSD: X11 DWM / Compton

### Logs
Created log file at "/tmp/Alacritty-98426.log"
[2020-10-24 11:18:56.997487751] [INFO] Welcome to Alacritty
[2020-10-24 11:18:56.997540519] [INFO] Configuration loaded from "/home/xxx/.config/alacritty/alacritty.yml"
[2020-10-24 11:18:57.011309137] [DEBUG] Estimated DPR: 1
[2020-10-24 11:18:57.011331546] [DEBUG] Estimated Cell Size: 9 x 19
[2020-10-24 11:18:57.011338456] [DEBUG] Estimated Dimensions: None
[2020-10-24 11:18:57.078403231] [INFO] Device pixel ratio: 1
[2020-10-24 11:18:57.083268185] [INFO] Initializing glyph cache...
[2020-10-24 11:18:57.106642106] [INFO] ... finished initializing glyph cache in 0.023348153s
[2020-10-24 11:18:57.106669695] [INFO] Cell Size: 9 x 19
[2020-10-24 11:18:57.106674800] [INFO] Padding: 3 x 3
[2020-10-24 11:18:57.106682478] [INFO] Width: 800, Height: 600
[2020-10-24 11:18:57.116949351] [INFO] PTY dimensions: Line(31) x Column(88)
[2020-10-24 11:18:57.121493519] [INFO] Initialisation complete
[2020-10-24 11:18:57.121841646] [DEBUG] New num_cols is 104 and num_lines is 26
[2020-10-24 11:18:57.121983582] [INFO] Width: 944, Height: 515

First off, I'm pretty happy with alacritty.  What a great idea!

Normally if there is a PS1 setting in the bashrc, the PS1 overrides PROMPT_COMMAND.  Also, when changing users in the terminal using the su command, the newly assumed user's .bashrc file overrides any settings of the first user until exited and re-assuming the previous user. 

However, when su'ing into another user, such as root, it doesn't appear that the newly assumed bash profile is being acquired and used for prompt decoration.

After assuming another user, command prompts are being shown for **both** the previous and newly assumed user.  PROMPT_COMMAND is being displayed for the previous user immediately followed by the PS1 setting showing information about the new user.

An example of the .bashrc of both users:
```
export PS1="\[\033[0;31m\]\u \[\033[0;33m\]\w\[\033[0;0m\]: "
```

An example:
```
# example prompt
~ newbie:
# after su into root, the new prompt reads:
newbie@localhost:/home/newbieroot /home/newbie:
```
After su'ing into another user the prompt is now displaying:
```
PROMPT_COMMAND (previous user) PS1 (new user)
```
Command prompt information should only be displaying the current user using that user's bash profile.

In order to work around this issue, I have to export PROMPT_COMMAND to nul.
```
export PROMPT_COMMAND=
export PS1="\[\033[0;31m\]\u \[\033[0;33m\]\w\[\033[0;0m\]: "
```

**Comment by chrisduerr** [comment]
This has nothing to do with Alacritty, but is solely up to the shell. Chances are your system is checking for `TERM` somewhere in the global configuration.

**Comment by bridgesense** [comment]
That's what someone mentioned in freenode yesterday.  Although I appreciate that, why are all the other terminals compensating for it?   I'll look into the global configuration.  Thanks.

**Comment by chrisduerr** [comment]
> Although I appreciate that, why are all the other terminals compensating for it?

They aren't.

**Comment by bridgesense** [comment]
OK, thanks for making me double check that.  I've been in st for a while and I hadn't noticed the issue (last image).  However, urxvt is displaying the same problem with the latest fedora global bashrc.  I hadn't noticed it before.  The problem doesn't show up in tmux either.

![screenshot](https://bridgesense.com/cloud/index.php/s/XtL5T6j4paHq9SS/preview)

**Comment by chrisduerr** [comment]
Because the system checks for some terminals but not for others. It's 100% a system issue and has nothing to do with Alacritty.

**Comment by bridgesense** [comment]
For prosterity, alacritty sets the TERM environment.  Although you can echo $TERM, that isn't the one alacritty is using.  Setting the envirnoment TERM to xterm-256color takes care of the issue for me.

![screenshare](https://bridgesense.com/cloud/index.php/s/8Zz5NfpzHQ3y9PK/preview)

**Comment by chrisduerr** [comment]
>  Setting the envirnoment TERM to xterm-256color takes care of the issue for me.

You should not set Alacritty's `TERM` to xterm-256color since Alacritty is not the same terminal as XTerm. This will cause incorrect terminal application behavior.

**Comment by bridgesense** [comment]
Thanks for the insight.  The config file is now set to the default: alacritty.  The issue I was experiencing was due to me having the TERM environment set in my bashrc to screen-256color.  That didn't do alacritty any favors either.  Removing that line seemed to have cleaned up the conflict as well.

**Comment by bridgesense** [comment]
> > Setting the envirnoment TERM to xterm-256color takes care of the issue for me.
> 
> You should not set Alacritty's `TERM` to xterm-256color since Alacritty is not the same terminal as XTerm. This will cause incorrect terminal application behavior.

Can you give me some references to "cause incorrect terminal application behavior" in the documentation?  I work on quite few different remote systems through Alacritty and I've noticed quite a few compatibility issues when not setting the TERM environment to xterm.   The default to Alacritty causes discovery issues.  What's wrong with using an xterm fallback?
