### ISSUE TITLE
Alacritty terminal question

### ISSUE THREAD

**Issue by grg121** [alacritty/alacritty#4350]
Hello there, 

I'm working on a research project and I need to find a way to run commands in an interactive shell recording each command introduced by the user and it's output in common log entry, even if the user log into other system through ssh, for example, or changes the running shell.

I've forked this project and I've been reading the source code looking for some kind of handler of the user input and/or read/write operations into the TTY but I'm not understanding how to do alacritty works with the system TTY.

If anyone could give me some clues about how does alacritty work with TTY read/writting and STOUT, STIND and STDERR of the process running on the terminal (if it does) I would be gratefull.Also If you have any idea on how to do what I'm looking for.

Básically I want to handle user input (when ihe/she press enter, for example, record the current row of the terminal with the command executed) and then record everything returned by the child process to the terminal and associate such output with the recorded input in a database or log file.

Best regards

**Comment by chrisduerr** [comment]
> I'm working on a research project and I need to find a way to run commands in an interactive shell recording each command introduced by the user

A terminal has no idea about what a shell is. Since it is unfamiliar with shells, it will also never be able to tell you which commands have been executed inside of it. All you can do is keylog all inputs (see input.rs received_char).

> and then record everything returned by the child process to the terminal and associate such output with the recorded input in a database or log file.

Sounds a bit like you want https://asciinema.org/.
