### ISSUE TITLE
[feature] shrink/extend selection with keyboard

### ISSUE THREAD

**Issue by Aloso** [alacritty/alacritty#4352]
To copy text, I first have to select it with my mouse. It would be nice if it was possible to select text with the keyboard (e.g. with <kbd>Shift+Left</kbd>, <kbd>Control+Shift+Left</kbd>, <kbd>Shift+Right</kbd>, <kbd>Control+Shift+Right</kbd>).

### System

OS: Manjaro Linux
Version: 0.5.0
Linux: X11, KDE

**Comment by kchibisov** [comment]
You can use Vi mode for that

https://github.com/alacritty/alacritty/blob/5a3bf69e3fd771271921f62219cdb8f920db39ee/alacritty.yml#L646

**Comment by Aloso** [comment]
@kchibisov I almost never use Vi mode, could you explain how that works? I tried it but couldn't figure out how to select text with it.

**Comment by kchibisov** [comment]
You may read binding in config, they tell how to start selection, etc. But basically, h,j,k,l to move, v to select, and y to copy.
