### ISSUE TITLE
Compilation failure on macOS when --no-default-features is passed

### ISSUE THREAD

**Issue by lexpierce** [alacritty/alacritty#4353]
Compiling on MacOS, I would not expect to need the default features of 'x11', 'wayland', and 'winpty'. But the if defined statements in `alacritty/src/window.rs` do not take that case into account, so I get the following build failure:

```
error[E0201]: duplicate definitions with name `set_urgent`:
   --> alacritty/src/window.rs:343:5
    |
334 | /     pub fn set_urgent(&self, is_urgent: bool) {
335 | |         if !is_urgent {
336 | |             return;
337 | |         }
338 | |
339 | |         self.window().request_user_attention(RequestUserAttentionType::Critical);
340 | |     }
    | |_____- previous definition of `set_urgent` here
...
343 |       pub fn set_urgent(&self, _is_urgent: bool) {}
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ duplicate definition

error: aborting due to previous error
```

However, if I leave them defined I end up with dead_code warnings on compilation:

```
warning: associated function is never used: `wayland_display`
   --> alacritty/src/window.rs:401:12
    |
401 |     pub fn wayland_display(&self) -> Option<*mut std::ffi::c_void> {
    |            ^^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default
```

which is also not ideal.

### System

OS: macOS

**Comment by chrisduerr** [comment]
Just to be clear, there's no need to remove X11/Wayland on macOS and the warning doesn't matter at all.

But of course all of this should still work without any warnings or errors, which should be solved in #4355.

Could you let me know if that works for you?

**Comment by nixpulvis** [comment]
Oh @chrisduerr beat me to it.

**Comment by chrisduerr** [comment]
@nixpulvis Just changing directory into `alacritty` should also work just fine, right?

**Comment by nixpulvis** [comment]
@chrisduerr yea, but I never generally like to stick in the workspace if I can. They're getting to the point this should work more ergonomically.
