### ISSUE TITLE
Strange behavior  with zsh-syntax-highlighting on in ZIM

### ISSUE THREAD

**Issue by ray-x** [alacritty/alacritty#4357]
Saw this with zsh+zim

Please refer to screenshot
I am using zim with zsh-syntax-highlighting module on. But had strange behavior of command auto completion. (only disable `zmodule completion` and `zmodule zsh-users/zsh-autosuggestions` does not help)

![Screen Shot 2020-10-28 at 9 08 42 am](https://user-images.githubusercontent.com/1681295/97367607-87426500-18fd-11eb-897b-c8341019af4c.png)

If I turn off `zmodule zsh-users/zsh-syntax-highlighting` in my zimrc, it behave correctly.
I did upgrade zsh-syntax-highlighting and 

### System

OS: macOS
Version: `alacritty --version` output
alacritty 0.5.0 (a6681e3)
Also reproduce in 
alacritty 0.6.0-dev (5a3bf69)

**Comment by chrisduerr** [comment]
Change the prompt to not include any non-ascii text and I'd assume it works just fine?

**Comment by ray-x** [comment]
I do not think it is my powerlevel10k prompt. If I disable powerlevel10k, the issue still exist.
It works fine in most of the case until turn on `zsh-syntax-highlighting`. Which will add color to the command auto completion.
I think lot of users may have use `zsh-syntax-highlighting`,  as a `oh-my-zsh plugin`. Not sure why it not working in my case.

**Comment by chrisduerr** [comment]
Can you reproduce this in a different terminal?

**Comment by ray-x** [comment]
No, did try `Terminal`, `iTerm2`, `kitty`.  Only alacritty has this issue so far.

**Comment by chrisduerr** [comment]
You've said that you disabled `powerlevel10k`, but you didn't say that your prompt uses just ascii characters without it. Could you confirm that please?

Also what happens when you start Alacritty from iTerm with `TERM=xterm-256color alacritty`?

**Comment by ray-x** [comment]
If I disable the theme of zim. So right now no color, no nerdfont in prompt. The issue still there.
Start from iTerm ` TERM=xterm-256color alacritty` Issue persist.
Mac version 10.15.7

The issue could be reproduce with a minium configure file
```yml
env:
  TERM: alacritty
shell:
  program: /bin/zsh
```

**Comment by chrisduerr** [comment]
> If I disable the theme of zim. So right now no color, no nerdfont in prompt. The issue still there.

That still doesn't answer my question if there's anything other than ascii in the prompt.

**Comment by ray-x** [comment]
No, nothing but ASCII.

**Comment by chrisduerr** [comment]
Can you provide a screenshot of the issue with ASCII text in the prompt?

**Comment by ray-x** [comment]
Yes, please refer to the screen shot

<img width="582" alt="Screen Shot 2020-10-28 at 3 48 05 pm" src="https://user-images.githubusercontent.com/1681295/97392094-02733d80-1935-11eb-8b23-b32a0976d488.png">

**Comment by chrisduerr** [comment]
I cannot reproduce this issue myself. Do you have anything else in the zsh configuration? Could you try an empty zsh config with no plugin manager, no OMZ, nothing other than just syntax highlighting?

**Comment by ray-x** [comment]
In fact, my minium one line zshrc can still reproduce
```zsh
source /Users/ray.xu/.zim/modules/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
```
<img width="270" alt="Screen Shot 2020-10-28 at 5 29 45 pm" src="https://user-images.githubusercontent.com/1681295/97400429-37868c80-1943-11eb-981d-8406e2067cb4.png">

**Comment by chrisduerr** [comment]
What `LANG` do you have set?

**Comment by ray-x** [comment]
my locale
```
❯ locale
LANG="en_AU.UTF-8"
LC_COLLATE="en_AU.UTF-8"
LC_CTYPE="en_AU.UTF-8"
LC_MESSAGES="en_AU.UTF-8"
LC_MONETARY="en_AU.UTF-8"
LC_NUMERIC="en_AU.UTF-8"
LC_TIME="en_AU.UTF-8"
LC_ALL=
```

**Comment by chrisduerr** [comment]
Could you try and see if `en_US.UTF-8` makes any difference?

**Comment by ray-x** [comment]
I tried:
```
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```
makes no difference.

**Comment by chrisduerr** [comment]
Then I'm not entirely sure what could be going on, since I cannot reproduce this issue myself on macOS or Linux. Testing on a different system with your config might provide some insights.

**Comment by ray-x** [comment]
If you could not reproduce this issue on your Mac. Maybe close this issue for now, and if anyone  spotted similar issue. We could reopen it. For me I could turn off the syntax highlight.

**Comment by ray-x** [comment]
Just FYI
If I change the `TERM: alacritty` to `TERM: xterm-256color` will also solve the issue.
It also could be reproduce by set `xterm-256color-italic`

In short.   `TERM: xterm-256color` or leave as default. Could not reproduce
`TERM: alacritty` or `xterm-256color-italic` could reproduce.

**Comment by chrisduerr** [comment]
>  If I change the TERM: alacritty to TERM: xterm-256color will also solve the issue.

Didn't you say earlier that it does **not** fix the problem? If setting `TERM` to `xterm-256color` fixes the problem, then it is 100% a bug with `zsh-syntax-highlighting`.

**Comment by ray-x** [comment]
Start from iterm  `TERM=xterm-256color alacritty` issue exists.
it seems the environment variable does not override alacritty.yml setup which was `alacritty`
```
echo $TERMcho $TERM
alacritty
```

**Comment by chrisduerr** [comment]
>  it seems the environment variable does not override alacritty.yml setup which was alacritty

Ah, you just didn't test with the default Alacritty configuration then. But that means this isn't our problem.

**Comment by kchibisov** [comment]
Also, when testing alacritty `TERM` variable, make sure that you've actually compiled and installed `alacritty` terminfo, in case you're forcing it, since the artifacts you're seeing looks like missing terminfo to me.
