### ISSUE TITLE
Mouse support on windows with micro editor

### ISSUE THREAD

**Issue by AndiLeni** [alacritty/alacritty#4359]
I am using micro editor on windows and expected mouse support to be working with alacritty.
Unfortunately it seems like this is not (yet) supported.
Are there any settings which should be made to enable mouse support for the emulated powershell processes?

### System
OS: Windows
Version: alacritty 0.5.0 (a6681e3)
Windows: ConPTY

**Comment by kchibisov** [comment]
Well, the mouse supported purely relies on ConPty on windows, nothing alacritty can do about it. One suggestion could be trying to update windows or conpty.
