### ISSUE TITLE
Change of title during work. 

### ISSUE THREAD

**Issue by m-kru** [alacritty/alacritty#4361]
Is there any way to change title during work?
For example pressing some shortcut would open new small window, where I would be able to enter new title.
I know there are `-t, --title <title>                              Defines the window title [default: Alacritty]` options, however they can be used only on startup.

**Comment by kchibisov** [comment]
Use escape sequences.

`printf '\e]2;New title\a'`

**Comment by m-kru** [comment]
Inside the terminal? I have tried this sequence and it does not work.

**Comment by kchibisov** [comment]
If you have dynamic title enabled it should work.

**Comment by kchibisov** [comment]
Note `--title` prevents title change all together.

**Comment by m-kru** [comment]
I have added `window.dynamic_title: true` to the `alacritty.yml`, I start without `-t` or `--title` options and still can't change the title using `printf '\e]2;New title\a'`.

**Comment by kchibisov** [comment]
Are  you on windows? Also, shell usually changes title on its own, so try adding `sleep 10` to check if that title ever get applied.

**Comment by m-kru** [comment]
Linux. It was shell, I had some clutter in my `.profile`. Thanks @kchibisov!
