### ISSUE TITLE
How do I "sponsor" alacritty development?

### ISSUE THREAD

**Issue by syscll** [alacritty/alacritty#4370]
Firstly, I'd like to say **THANKS** to everyone involved for creating such an awesome project!

I've used alacritty daily since v0.2.x, and while I could still do my job using other terminals _(I'll never forget you URxvt)_, alacritty just blows everything else out of the water.

That being said, is there a way to sponsor the project via GitHub Sponsors or something like [open collective](https://opencollective.com/)?

**Comment by chrisduerr** [comment]
While the sentiment is appreciated, there is currently no interest in allowing users to fund/sponsor the project.

The management overhead just isn't worth it for the money that projects like Alacritty usually get, that time for management/advertising is much better spent on the project itself furthering its development.

There also currently aren't any costs associated with Alacritty (like hosting for example), so we can maintain it without burning anything other than our own time.
