### ISSUE TITLE
Look in $XDG_DATA_DIRS/icons for cursor theme

### ISSUE THREAD

**Issue by edkv** [alacritty/alacritty#4371]
I have the following in `~/.local/share/icons/default/index.theme` which makes sway to use the Adwaita icon theme:

```
[icon theme]
Inherits=Adwaita
```

But this doesn't work with Alacritty. Moving that file to `~/.icons/default/index.theme` makes it work however.

According to https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#directory_layout applications should look in `~/.icons` dir for backwards compatibility, but `$XDG_DATA_DIRS/icons` is the new preferred location. I'm trying to keep my home directory clean so it would be great if Alacritty looked for icons in that dir as well.

### System

OS: Void Linux
Version: 0.5.0
WM: sway

**Comment by kchibisov** [comment]
That's how libwayland-cursor works, and it does't look into that directory. However master shouldn't use it anymore, thus this bug should be fixed on master.
