### ISSUE TITLE
Alacritty not opening [solution]

### ISSUE THREAD

**Issue by Jimmysit0** [alacritty/alacritty#4374]
A while ago, I experienced an error, and now I know the solution. The reason was, that I was using wayland, for some reason, it bugged with alacritty causing the error, after I moved to x11, everything was working, so if somebody experiences this on wayland just move to x11, seems to be an error with wayland. Hope this helps!

**Comment by kchibisov** [comment]
if you're using GNOME (Wayland) that was fixed with master. There's a pinned issue explaining that https://github.com/alacritty/alacritty/issues/4206
