### ISSUE TITLE
Support for arm64.

### ISSUE THREAD

**Issue by DarkPhoenix2005** [alacritty/alacritty#4377]
I was using alacritty from a long time on manjaro but now on ubuntu I am unable to compile it. So I am requesting to make a Deb package for arm64 available as it would be greatly helpful. And also nowadays more and more devices are comming with arm64 sonit woul also help them.

Btw I tried installing from the ppa but it's gives me a no installation candidate error and I have also tried compiling it but got some errors which I opened an issue but you said that it was a problem by my side so, it will be greatly helpful if a arm64 Deb package was available. Thank you 😊

**Comment by kchibisov** [comment]
>I was using alacritty from a long time on manjaro but now on ubuntu I am unable to compile it. So I am requesting to make a Deb package for arm64 available as it would be greatly helpful. And also nowadays more and more devices are comming with arm64 sonit woul also help them.

I use alacritty on arm64 without any problem, and cross compiling rust is similar to cross compiling any other C program tbqh.

We don't do any packing, if you want arm64 debian package, ask your distro to provide one.
