### ISSUE TITLE
Consider setting up editorconfig

### ISSUE THREAD

**Issue by kchibisov** [alacritty/alacritty#4378]
While rustfmt prevents us from spending our time on catching things like wrong indention or mixed indention, it's unclear what we're expecting for our shaders, etc, since rustfmt doesn't work on them, thus I think it'll be nice to have `.editorconfig` which could cover them, as well as rust itself. A lot of editors, like vim (required plugging though) can automatically pick them up and apply respectful settings and its syntax is pretty clear.

**Comment by chrisduerr** [comment]
I see no reason why we would require things like plugins for editor configurations. Our shaders should be simple and the style of them should be fairly consistent. That doesn't seem enough of a reason to justify adding this.

It's also generally pretty useless when it comes to actually enforcing a good style. If all we need is basic stuff like that anyways, I can enforce that manually too.

**Comment by kchibisov** [comment]
>It's also generally pretty useless when it comes to actually enforcing a good style. If all we need is basic stuff like that anyways, I can enforce that manually too.

I mean, it's quite common and integrated in a lot of things already. As well it's used  by a lot of open source projects and it's really helpful to have proper indention instead of guessing and reading trying to figure out code style.

We shouldn't require it, it'll just a bit common point to refer for values like whether tabs or spaces are used, how much spaces, line endings, etc.

For now I have no clue what we want from our shaders code, and I can't tell on PRs which are adding new shaders what style to use, since there's no formatter for them.

**Comment by chrisduerr** [comment]
If basic things like how many spaces you need or line endings confuse you, in a file that already exists, then I don't know what to tell you. It couldn't be any more obvious and if your editor doesn't pickup stuff like line endings automatically that's on the editor not a missing config file.

Just to be 100% clear, I will never use this, no matter what. But I'd still like to understand why you would like this added. Which actual formatting choices are unclear to you? Because whitespace/tabs/line endings certainly aren't a problem.

The things that editorconfig actually supports are utterly useless. It's just bloat you have to carry around with you for things that should be obvious just by looking what exists already.

**Comment by kchibisov** [comment]
>If basic things like how many spaces you need or line endings confuse you, in a file that already exists, then I don't know what to tell you. It couldn't be any more obvious and if your editor doesn't pickup stuff like line endings automatically that's on the editor not a missing config file.

It's more for convenience, since certain style we're using differs from what I'm using, and each time switching settings just for certain stuff in our repo is annoying, which `.editorconfig` those settings will load automatically, and the amount of editors that are working without any plugging are quite huge, thus it'll save time for anyone trying to hack on a project.

>Just to be 100% clear, I will never use this, no matter what. But I'd still like to understand why you would like this added. Which actual formatting choices are unclear to you? Because whitespace/tabs/line endings certainly aren't a problem.

If you work only with one project or with projects that all use the same style -> sure you don't need it. If you work with a lot of different projects, which carry their own settings and code style(sometimes strange) it saves a lot of time.

**Comment by chrisduerr** [comment]
Which style specifically is different than your defaults?

**Comment by kchibisov** [comment]
Our shaders? I don't use 4 spaces for them.
