### ISSUE TITLE
Arrow keys not working with neo keyboard layout

### ISSUE THREAD

**Issue by geier** [alacritty/alacritty#438]
Hi,
I'm using the [neo 2 keyboard layout](https://www.neo-layout.org/) and the arrow keys don't work.

Let me specify this: the "hard" arrow keys do work (those that actually have arrows printed on them), which makes me believe I have configured alacritty correctly (I'm using the default config file) but the "soft" arrow keys on neo's level 4 don't work. You get those "soft" arrow by pressing a modifier key and then  
one of the keys labeled l, i, a, or e.

The output of xev is the following:

```
KeyPress event, serial 35, synthetic NO, window 0x2c00001,
    root 0x4a7, subw 0x0, time 74992334, (290,558), root:(1973,586),
    state 0x0, keycode 108 (keysym 0xfe11, ISO_Level5_Shift), same_screen YES,
    XKeysymToKeycode returns keycode: 94
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 35, synthetic NO, window 0x2c00001,
    root 0x4a7, subw 0x0, time 74994618, (290,558), root:(1973,586),
    state 0x20, keycode 26 (keysym 0xff52, Up), same_screen YES,
    XKeysymToKeycode returns keycode: 111
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 35, synthetic NO, window 0x2c00001,
    root 0x4a7, subw 0x0, time 74994809, (290,558), root:(1973,586),
    state 0x20, keycode 26 (keysym 0xff52, Up), same_screen YES,
    XKeysymToKeycode returns keycode: 111
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 35, synthetic NO, window 0x2c00001,
    root 0x4a7, subw 0x0, time 74995597, (290,558), root:(1973,586),
    state 0x20, keycode 108 (keysym 0xfe11, ISO_Level5_Shift), same_screen YES,
    XKeysymToKeycode returns keycode: 94
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

Do I need to/can I bind the arrow keys with ISO_Level5_Shift?

**Update**: other keys on level four seem to work, e.g. backspace and delete, tab and enter.

**Comment by mmerfort** [comment]
Same here, on Arch Linux using the most recent git build.

**Comment by chrisduerr** [comment]
Is this still an issue on the latest master? If so, the output of `alacritty --print-events` would be very helpful.

**Comment by chrisduerr** [comment]
Since this has been dead since 2017, without any other users reporting this issue, I'd assume it has been resolved.

If it should still exist, please let me know and I will re-open the issue.

**Comment by FichteFoll** [comment]
I am running into this problem currently, particularly with the `ctrl+mod4+s` binding, which via neo should resolve to `ctrl+left` but gets detected by alacritty as `ctrl+s`, which then sends `\u13` to the terminal and suspends its output. A similar behavior can be observed with the f key which should map to `ctrl+right` but instead triggers a search.

I confirmed with `alacritty --print-events` that the key is recognized (scancode 100) but the resulting event is identical to the one without the mod4 key. Please see the attachments for results of the key presses as well as an `xev` log. Also note that this key binding works in several other applications, such as FireFox, Sublime Text and IntelliJ (with the "local key bindings" setting active).

[ctrl-mod4-f.txt](https://github.com/alacritty/alacritty/files/9415923/ctrl-mod4-f.txt)
[ctrl-mod4-s.txt](https://github.com/alacritty/alacritty/files/9415924/ctrl-mod4-s.txt)
[ctrl-mod4-s_xev.txt](https://github.com/alacritty/alacritty/files/9415926/ctrl-mod4-s_xev.txt)
[ctrl-s.txt](https://github.com/alacritty/alacritty/files/9415927/ctrl-s.txt)
[mod4-ctrl-s.txt](https://github.com/alacritty/alacritty/files/9415929/mod4-ctrl-s.txt)

**Comment by FichteFoll** [comment]
Ah, I should note that it works with ctrl+mod4+w (mapping to ctrl+backspace). I typed some characters first here to confirm that it does indeed delete the previously typed characters/word.
Also, all alacritty windows (and xev) are closed with super+shift+q.

[ctrl-mod4-w.txt](https://github.com/alacritty/alacritty/files/9415998/ctrl-mod4-w.txt)
