### ISSUE TITLE
Resizing in tiled mode is extremely slow

### ISSUE THREAD

**Issue by Azorlogh** [alacritty/alacritty#4381]
### System

OS: Linux 5.4.74-1-lts (Arch)
Version: 0.5.0
X11, bspwm (both with and without picom)
Screen: 1920x1080 (144hz)
GPU: Nvidia RTX 2060 (proprietary drivers)

Whenever I have more than 3 instances of alacritty in tiled mode, resizing becomes extremely slow, [see this comparison with urxvt.](https://imgur.com/a/kYFuNrT)

It happens both with and without a compositor.

**Comment by chrisduerr** [comment]
How did you install Alacritty?

**Comment by Azorlogh** [comment]
I installed it from the official arch repos, the package version shows "0.5.0-3".

**Comment by nixpulvis** [comment]
I wonder if this is the same thing making macOS resizing really sluggish as well (#969). Might be a bit of a stretch, but it looks like the same behavior at least.

**Comment by chrisduerr** [comment]
I cannot reproduce this myself on i3, seems like it might be related to bspwm?

Can you reproduce in floating mode @Azorlogh?

**Comment by Azorlogh** [comment]
Also, I have tested it on my laptop which almost has the exact same setup and it's working fine there
It has a 60hz screen, and a GT650M (with proprietary drivers)

**Comment by chrisduerr** [comment]
That shouldn't be any different with tiling/floating mode. What other applications have you tried? Could you test something that uses GPU rendering?

**Comment by Azorlogh** [comment]
(My reasoning was that in tiling mode, it has to resize more windows at once, but I don't really know how this works)
I have tried it with glslViewer and it's working fine. There is some stutter, but it doesn't "lag behind" like with alacritty.
I added the video as well.

**Comment by ryanw** [comment]
I have the same issue in alacritty 0.6.0 (04cbf767) also using bspwm and Nvidia proprietary drivers. I tried at 60hz and it was no better.

**Comment by chrisduerr** [comment]
Sounds like a window manager/compositor problem then. @Azorlogh can you confirm this is the same for other OpenGL applications?

**Comment by Azorlogh** [comment]
I do have the same problem in Kitty, however it doesn't seem to just be due to OpenGL, because I have tried it with glslViewer, as well as 5 instances of minecraft (in-game) and it's butter smooth.

**Comment by chrisduerr** [comment]
It might be due to the specific OpenGl version used. But if you can reproduce this in other applications I'd look into other avenues first. I don't think Alacritty does anything that special that would cause this troubles that coincidentally Kitty also does.

**Comment by phisch** [comment]
@chrisduerr have you read the last 2 comments? Maybe there is room for improvement of how resize events are handled. I too have a 144hz monitor and resizing 2 tiled terminals is a sluggish hell:
![1622677115](https://user-images.githubusercontent.com/1282767/120565532-99ddc900-c40d-11eb-9b8a-2ac1ad9e5939.gif)

No other application is even remotely as sluggish when resizing (not even when i have 4 JetBrains IDE's open.

This issue should definitely be re-opened and discussed some more!

**Comment by ryanw** [comment]
I've been playing with rust and opengl (glium), and encountered exactly the same performance issues in my own software when vsync is enabled. Disabling vsync and resizing is pretty smooth. Could it be as simple as that?

**Comment by ryanw** [comment]
I tested my theory, I compiled the source with vsync disabled. It now resizes smooth as butter even with lots of windows open. The change is simple, just set the 4th arg to `create_gl_window` to `false` in _alacritty/src/display/window.rs_

patch:

```
diff --git a/alacritty/src/display/window.rs b/alacritty/src/display/window.rs
index 7302c68..82ae661 100644
--- a/alacritty/src/display/window.rs
+++ b/alacritty/src/display/window.rs
@@ -186,9 +186,9 @@ impl Window {
         let is_wayland = false;
 
         let windowed_context =
-            create_gl_window(window_builder.clone(), &event_loop, false, !is_wayland, size)
+            create_gl_window(window_builder.clone(), &event_loop, false, false, size)
                 .or_else(|_| {
-                    create_gl_window(window_builder, &event_loop, true, !is_wayland, size)
+                    create_gl_window(window_builder, &event_loop, true, false, size)
                 })?;
 
         // Text cursor.
```

**Comment by phisch** [comment]
@ryanw That actually seems to be it! I ran your patch on master and the results are great!
Maybe it would be best if you create a PR? Since nobody seems to react to this closed issue.

Before:

https://user-images.githubusercontent.com/1282767/120904348-1958db80-c64c-11eb-8127-f2d5df12ef3d.mp4

With patch:

https://user-images.githubusercontent.com/1282767/120904350-1f4ebc80-c64c-11eb-81ee-1d0ebdb1eb42.mp4

@chrisduerr

**Comment by phisch** [comment]
@ryanw That actually seems to be it! I ran your patch on master and the results are great!
Maybe it would be best if you create a PR? Since nobody seems to react to this closed issue.

Before:

https://user-images.githubusercontent.com/1282767/120904348-1958db80-c64c-11eb-8127-f2d5df12ef3d.mp4

With patch:

https://user-images.githubusercontent.com/1282767/120904350-1f4ebc80-c64c-11eb-81ee-1d0ebdb1eb42.mp4

@chrisduerr

**Comment by ryanw** [comment]
I've added a PR which lets you force vsync off using the config file:

https://github.com/alacritty/alacritty/pull/5209

**Comment by nonetrix** [comment]
I am having the same issue however disabling vsync only makes it slightly better

**Comment by nonetrix** [comment]
Only terminal that is GPU accelerated that doesn't have this is wezterm

**Comment by nonetrix** [comment]
```bspc config pointer_motion_interval 40``` fixes this I guess since my mouse is 1000 polling rate it is sending a resize request 1000 times a second and that causes lag?

**Comment by gandalf3** [comment]
> Only terminal that is GPU accelerated that doesn't have this is wezterm

Kitty also seems fine for me, on bspwm with nvidia proprietary drivers.
