### ISSUE TITLE
command flag broken

### ISSUE THREAD

**Issue by AtifChy** [alacritty/alacritty#4383]
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

OS: Linux
Version: alacritty 0.6.0-dev (a4e5b1f)
Linux: X11, Picom and dwm

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: Fira Code/10
![Screenshot_20201106_104527](https://user-images.githubusercontent.com/42291930/98327990-fd8e4800-201e-11eb-825c-debff4f487f4.png)

**Comment by AtifChy** [comment]
this also happens on stable release

**Comment by chrisduerr** [comment]
This is a vim issue, it cannot handle resize on startup. You can work around this by sleeping for .1s (just any short interval) to start vim after resizing is done.

**Comment by AtifChy** [comment]
but it also happens with nano

**Comment by wfxr** [comment]
I guess it should be a bug. Tested that `kitty -e vim` works without this problem. Add `sleep 0.1` works but is annoying.

@AtifChy Could you reopen this issue?
