### ISSUE TITLE
RFE: Support for DECSET 1035 sequences

### ISSUE THREAD

**Issue by contyk** [alacritty/alacritty#4386]
`DECSET 1035` changes the behavior of certain keys, namely cursor and function keys, and the keypad. This is distinct from the normal/application mode as it affects both further.

The best description of this I've found is this document, "PC-Style Function Keys", page 15:
https://www.x.org/archive/X11R6.8.1/PDF/ctlseqs.pdf

In xterm I can toggle this mode with `printf '\033[?1035h'` / `printf '\033[?1035l'`. xterm also allows setting this via the `numLock` resource (although that can be overridden with `alwaysUseMods:true`), or through the menu via `Alt/NumLock Modifiers`. The default xterm default is `true`, which results in behavior equal to current Alacritty.

This is for the cases when you don't want the default behavior. I've not discovered any other way to enter that mode in Alacritty and the sequences don't do anything either.

My use case is issue #3720, although that wasn't the right place to discuss it. @kchibisov pointed me to #3101 on IRC; I think that's a different thing, however, as I can still apply Alt modifiers to these alternate codes in xterm.

I'm no expert on the topic but this is blocking me from switching away from xterm; I'll assist as much as I can.

**Comment by chrisduerr** [comment]
Which applications actually make use of these escape sequences?

**Comment by contyk** [comment]
I think many MUD clients do, for instance. They typically run in the application mode but use this alternate mode for keypad keys for movement. My journey began in the "Numeric keypad" section of http://flaprider.dyndns.org/~hair/tf/topics/keybindings.html; that happens to be the I personally use. It maps these to `key_nkp` bindings. It can even recognize these with the Alt modifier and I use both.

**Comment by contyk** [comment]
Without this, application mode or not, the keypad sends either numbers or the cursor key codes, none of which is useful in this case. In the app it simply inputs the numbers or moves the cursor on the input lines, it doesn't map it to the bindings.

**Comment by contyk** [comment]
Well, I've managed to configure my keybindings with the current `master` so that my app gets the right codes; it's even better than it was with xterm where I had to override the Alt+keypad bindings n the app for it to work with this mode. We discussed this at length on IRC today and every terminal behaved differently. `urxvt` did the right thing out of the box, though, in the keypad mode, without numlock on.

With the current `master` code I need to have numlock on for Alacritty to notice the `Keypad` bindings; as the `AppKeypad` isn't working so I have to abuse the `Alt` mode, but that's already covered by that other issue. Also my keypad Enter doesn't map to Alacritty's `KeypadEnter` but `KeypadEquals` instead. That could be just naming and I don't know what's actually correct.

Anyway, I have a satisfactory workaround for now and I think I could have been anyone having some use for this sequence. I'm closing this. If anyone else wants it, they can always reopen.

I'm listing my workaround if anyone finds it useful. Note this does NOT work with 0.5.0; that version does not support all these keys:

```yaml
key_bindings:
  - { key: Numpad0, mode: Alt, chars: "\eOp" }
  - { key: Numpad1, mode: Alt, chars: "\eOq" }
  - { key: Numpad2, mode: Alt, chars: "\eOr" }
  - { key: Numpad3, mode: Alt, chars: "\eOs" }
  - { key: Numpad4, mode: Alt, chars: "\eOt" }
  - { key: Numpad5, mode: Alt, chars: "\eOu" }
  - { key: Numpad6, mode: Alt, chars: "\eOv" }
  - { key: Numpad7, mode: Alt, chars: "\eOw" }
  - { key: Numpad8, mode: Alt, chars: "\eOx" }
  - { key: Numpad9, mode: Alt, chars: "\eOy" }
  - { key: NumpadDivide, mode: Alt, chars: "\eOo" }
  - { key: NumpadMultiply, mode: Alt, chars: "\eOj" }
  - { key: NumpadSubtract, mode: Alt, chars: "\eOm" }
  - { key: NumpadAdd, mode: Alt, chars: "\eOk" }
  - { key: NumpadDecimal, mode: Alt, chars: "\eOn" }
  - { key: NumpadEquals, mode: Alt, chars: "\eOM" }
  - { key: Numpad0, mods: Alt, mode: Alt, chars: "\e\eOp" }
  - { key: Numpad1, mods: Alt, mode: Alt, chars: "\e\eOq" }
  - { key: Numpad2, mods: Alt, mode: Alt, chars: "\e\eOr" }
  - { key: Numpad3, mods: Alt, mode: Alt, chars: "\e\eOs" }
  - { key: Numpad4, mods: Alt, mode: Alt, chars: "\e\eOt" }
  - { key: Numpad5, mods: Alt, mode: Alt, chars: "\e\eOu" }
  - { key: Numpad6, mods: Alt, mode: Alt, chars: "\e\eOv" }
  - { key: Numpad7, mods: Alt, mode: Alt, chars: "\e\eOw" }
  - { key: Numpad8, mods: Alt, mode: Alt, chars: "\e\eOx" }
  - { key: Numpad9, mods: Alt, mode: Alt, chars: "\e\eOy" }
  - { key: NumpadDivide, mods: Alt, mode: Alt, chars: "\e\eOo" }
  - { key: NumpadMultiply, mods: Alt, mode: Alt, chars: "\e\eOj" }
  - { key: NumpadSubtract, mods: Alt, mode: Alt, chars: "\e\eOm" }
  - { key: NumpadAdd, mods: Alt, mode: Alt, chars: "\e\eOk" }
  - { key: NumpadDecimal, mods: Alt, mode: Alt, chars: "\e\eOn" }
  - { key: NumpadEquals, mods: Alt, mode: Alt, chars: "\e\eOM" }
```
