### ISSUE TITLE
Emojis are not renderring correctly.

### ISSUE THREAD

**Issue by Pratham82** [alacritty/alacritty#4389]
The emojis are not showing as they are. I tried various versions of Nerd font. Hack Nerd font, BlexMono Nerd Font and many other. Previously it was working don't know exactly what went wrong.

### System
OS: Linux
Version: 0.5.0 (a6681e3a)
Linux: Manjaro i3 community edition, i3 WM

![2020-11-07-193418_297x88_scrot](https://user-images.githubusercontent.com/13178080/98443287-67e2dd80-2130-11eb-83d7-27169cb59b67.png)

Same emojis in kitty:
![2020-11-07-193558_258x93_scrot](https://user-images.githubusercontent.com/13178080/98443306-7df09e00-2130-11eb-8aaa-2569819d9624.png)

Thes are the fonts I'm using:
![2020-11-07-193656_282x238_scrot](https://user-images.githubusercontent.com/13178080/98443338-9f518a00-2130-11eb-8921-258e4063d15a.png)

**Comment by chrisduerr** [comment]
You've got another font in your priority list that comes before your emoji font. You need to setup things with fontconfig so your emoji font comes first, when you want to show the colored emojis.
