### ISSUE TITLE
border, shade

### ISSUE THREAD

**Issue by soloturn** [alacritty/alacritty#4392]
how could one set a border, and maybe a shade so its clearer which part of the screen belongs to which window?

**Comment by chrisduerr** [comment]
You can set a padding in the configuration file.

**Comment by kchibisov** [comment]
>how could one set a border, and maybe a shade so its clearer which part of the screen belongs to which window?

Are you on Wayland? If so we don't draw shadows, etc.

**Comment by kchibisov** [comment]
I'd make an assumption that it was for Wayland, so the upstream bug is https://github.com/Smithay/client-toolkit/issues/162

**Comment by tmpm697** [comment]
upstream merged, can we re-open this as I also want to have `shadow` border settings in `window:` decorations of alacritty's settings.

@chrisduerr @kchibisov

**Comment by Iss-in** [comment]
yeah, this feature is required in  wayland, most compositor arent drawing the shadows by themselves anymore

**Comment by tmpm697** [comment]
Yes, it is. Swaywm devs won't merge border patch. 

Firefox window under swaywm draw border itself.

**Comment by soloturn** [comment]
@chrisduerr @kchibisov mind reopening?

**Comment by chrisduerr** [comment]
I don't have much interest implementing this in Alacritty directly just for the Wayland setups that don't do it with the display server. I might be open for a PR if it is small enough but that really shouldn't be any of Alacritty's business.

**Comment by tmpm697** [comment]
I have to use patched version of swaywm to have shadow border applies to alacritty, remind you that firefox-beta draws shadow border itself.

swaywm refused to add border feature as they somehow trait it as adding complexity and unwanted feature.

I personally think display server should add it as it is general software for others to lie on.

**Comment by tmpm697** [comment]
I believe all firefox (despite of versions) windows under swaywm decorate its own light shadow and perfect round corner (I the it more than round in window 11 latest). Enforcing global shadow and corner might not the way applications wanted in first place.
