### ISSUE TITLE
Add Control + Shift + Enter to spawn new instances

### ISSUE THREAD

**Issue by alexherbo2** [alacritty/alacritty#4402]
``` yaml
key_bindings:
  - { key: Return, mods: Control|Shift, action: SpawnNewInstance }
```

**Comment by chrisduerr** [comment]
What exactly is your problem?

**Comment by alexherbo2** [comment]
I want to suggest this mapping. ^^'

macOS has some mappings to open new instances and actions other OS do not have.

It could be nice to add a few sensible mappings and unify somehow the configs with a ⌘ equivalent.

**Comment by chrisduerr** [comment]
I see no reason to ship a mapping like that by default.
