### ISSUE TITLE
Alacritty doesn't colorize some files

### ISSUE THREAD

**Issue by PouriDev** [alacritty/alacritty#4407]
I don't know why alacritty doesn't colorize some files such as `.png` files, or
some other files that are unknown
as you can see here in alacritty: 
![alacritty](https://user-images.githubusercontent.com/61497342/98840803-80b70000-245c-11eb-967a-0e742bf6bead.png)
This was `ls` output or even `tree`'s output has no color

Same thing on Konsole: 
![konsole](https://user-images.githubusercontent.com/61497342/98840860-9298a300-245c-11eb-83d0-f6763c651458.png)
Any idea ?

**Comment by PouriDev** [comment]
Also it doesn't colorize some commands like `local` it's orange in Konsole, but it's white in Alacritty , second command is something that you put between quots like ` " somet test"` this will be orange in Konsole too, but still white in alacritty

**Comment by chrisduerr** [comment]
This has nothing to do with Alacritty and is fully up to whatever applications you use to emit that text.
