### ISSUE TITLE
Unicode 13 sextant characters are rendered messily

### ISSUE THREAD

**Issue by dankamongmen** [alacritty/alacritty#4409]
I hesitate to report this as a bug against Alacritty -- it might well be a problem in the font I'm using (Hack), except I don't see this particular issue in other terminal emulators using the same font, at the same size. Please accept my apologies if this is not an Alacritty issue. Unicode 13 introduced "sextant" characters in its Legacy Computing block. Alacritty seems to render these characters less than perfectly compared to other block-style glyphs. We're using these glyphs extensively in [Notcurses](https://github.com/dankamongmen/notcurses) for our "sexblitter", which works well everywhere but Alacritty (see for instance https://github.com/dankamongmen/notcurses/issues/1099, which features several screenshots). Here's a screenshot from alacritty's current head:

https://nick-black.com/images/alacritty-blitters.png

The sextant characters can be seen on the line with `NCBLIT_3x2`. Note the uneven base, with some characters descending below others. So far as I can tell, it is the pre-Unicode13 blocks (i.e. LEFT HALF, FULL BLOCK) which descend all the way, and the sextants do not. This reflects what we see in Notcurses, where blitting performed with sextants leaves unsightly gaps.

If this is a font problem, let me know, and I'll file a bug appropriately. Thank you!

### System

OS: Linux
Version: alacritty 0.5.0 (b988eae013b)
Linux/BSD: X11, Compiz

### Logs

Font/Terminal size: 
```
[2020-11-12 09:31:27.750503466] [INFO] Welcome to Alacritty
[2020-11-12 09:31:27.750608662] [INFO] Configuration loaded from "/home/dank/.config/alacritty/alacritty.yml"
[2020-11-12 09:31:27.775692283] [DEBUG] Estimated DPR: 1.1458333333333333
[2020-11-12 09:31:27.775721482] [DEBUG] Estimated Cell Size: 9 x 18
[2020-11-12 09:31:27.775725232] [DEBUG] Estimated Dimensions: Some((720, 1404))
[2020-11-12 09:31:27.979192885] [INFO] Device pixel ratio: 1.1458333333333333
[2020-11-12 09:31:27.989693330] [INFO] Initializing glyph cache...
[2020-11-12 09:31:28.028292706] [INFO] ... finished initializing glyph cache in 0.038573057s
[2020-11-12 09:31:28.028352684] [INFO] Estimated DPR correctly, skipping resize
[2020-11-12 09:31:28.028358764] [INFO] Cell Size: 9 x 18
[2020-11-12 09:31:28.028365313] [INFO] Padding: 0 x 0
[2020-11-12 09:31:28.028375073] [INFO] Width: 720, Height: 1404
[2020-11-12 09:31:28.044086877] [INFO] PTY dimensions: Line(78) x Column(80)
[2020-11-12 09:31:28.049124722] [INFO] Initialisation complete
[2020-11-12 09:31:28.049694022] [DEBUG] Term::resize dimensions unchanged
[2020-11-12 09:31:28.049725880] [INFO] Width: 720, Height: 1404
```

**Comment by dankamongmen** [comment]
Additionally, please take a look at https://user-images.githubusercontent.com/143473/98285687-ec86fd80-1f70-11eb-9e83-8cbef97719ad.png, where some sextants are clearly being printed into the same columns as the quotation marks which follow them.

**Comment by kchibisov** [comment]
it's likely a font problem, since Hack is unlikely to have unicode 13 glyphs at all. Also, alacritty drawing such glyphs from the font, however mostly all terminals I'm aware of are drawing those glyphs themselves, thus they will look fine regardless of the font you're using.

I'm not sure if we start drawing them ourselves as well, but there's a chance that we'll do such thing...

**Comment by dankamongmen** [comment]
> it's likely a font problem, since Hack is unlikely to have unicode 13 glyphs at all. Also, alacritty drawing such glyphs from the font, however mostly all terminals I'm aware of are drawing those glyphs themselves, thus they will look fine regardless of the font you're using.
> 
> I'm not sure if we start drawing them ourselves as well, but there's a chance that we'll do such thing...

interesting. is alacritty already drawing the Quadrant characters itself? if so, if you'd like to point me at that code, i'd likely be able to pattern match up a Sextant implementation.

thanks for your quick reply!

**Comment by kchibisov** [comment]
>interesting. is alacritty already drawing the Quadrant characters itself? 

it's not drawing anything itself other than cursor, even lines are not drawn by alacritty. On the other hand other terminals are doing so.

**Comment by dankamongmen** [comment]
Closing per request of @kchibisov in https://github.com/dankamongmen/notcurses/issues/1099. See also https://github.com/alacritty/crossfont/issues/17.

**Comment by dankamongmen** [comment]
> I'm not sure if we start drawing them ourselves as well, but there's a chance that we'll do such thing...

understanding better now how a few terminals are doing things, i heartily endorse this proposal. it seems to work very well for kitty (after i fixed up a bug) and VTE-derived terminals, and how much meaningful difference can there be among fonts' implementations of block-drawing characters?
