### ISSUE TITLE
Slow Mission Control on BigSur

### ISSUE THREAD

**Issue by ViBiOh** [alacritty/alacritty#4410]
### System

OS: macOS BigSur 11.0.1
Version: alacritty 0.5.0 (a6681e3)
Device: Macbook Pro 16" i7 16GB RAM GPU 5300M

I've installed a fresh new installation of macOS Big Sur (erase disk) and when I use Mission Control *with* Alacritty, it's very slow animation.

I have no problem to switch between natives macOS applications (everything is smooth) but when I go back/from Alacritty, Mission Control become very slow in animation.

Edit: I tested it more, it happens only when using the laptop alone. If I plug an external screen, everything is smooth again. This is strange. Maybe related to GPU switching or transparency.

**Comment by chrisduerr** [comment]
If mission control is slow, this sounds like it would be an Apple issue? Probably failing with OpenGL again which wouldn't be unusual. I don't see what Alacritty has to do with Apple system software.

**Comment by ViBiOh** [comment]
> If mission control is slow, this sounds like it would be an Apple issue? Probably failing with OpenGL again which wouldn't be unusual. I don't see what Alacritty has to do with Apple system software.

Because it happens only for Alacritty, I was wondering if there is something special with it. I close the issue so.

**Comment by TonalidadeHidrica** [comment]
Further discussions and workadounds in #4474.  TL; DR: to workaround, add a line `background_opacity: 0.999` to `alacritty.yml`.
