### ISSUE TITLE
opening file with neovim change cursor style form beam to block

### ISSUE THREAD

**Issue by Meshikhah** [alacritty/alacritty#4411]
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

OS: Manjaro linux/ kde with x11
Version: 0.5.0 (a6681e3a)

opening file with neovim changing cursor style from beam to block. It doesn't happen with vim.

edit: sorry it happens in konsole too. so it is not related to alacritty.

**Comment by kchibisov** [comment]
neovim resets cursor style to block each time you leave it, setup your neovim to not do so.

**Comment by aryklein** [comment]
Disable cursor-styling by adding `set guicursor=` to your init.vim file
