### ISSUE TITLE
Resize / Reflow Issues

### ISSUE THREAD

**Issue by davidnorthetal** [alacritty/alacritty#4419]
Terminal contents of the window do not correctly resize/reflow upon resizing the window, instead the contents get jumbled up.
(first reducing its size heavily then expanding it again)

This happens independent of the shell, tested with bash/zsh.
This happens with both `alacritty` or `xterm-256color` as `$TERM`.

### System
OS: Linux
Version: alacritty 0.5.0 (a6681e3a)
Linux: X11, i3wm

( I have also observed this under Windows using msys2 )

A video showcasing this is here https://imgur.com/26pH5r7

I attached 3 screenshots showing this as well.
![alacritty-resizing-0001](https://user-images.githubusercontent.com/24317742/99148426-d91e1580-2687-11eb-8652-4dbbe0c68fcd.png)
![alacritty-resizing-0002](https://user-images.githubusercontent.com/24317742/99148427-d9b6ac00-2687-11eb-932d-2658f2116d42.png)
![alacritty-resizing-0003](https://user-images.githubusercontent.com/24317742/99148428-da4f4280-2687-11eb-9aef-f25f0188cda4.png)

**Comment by kchibisov** [comment]
This is not really our issue, it's a shell trying to reflow itself and we trying to reflow it as well, And the right prompt causes the most issues here tbqh. I know that it's present in literally every terminal I've tried, though some of them use delay before the resize, so it glitches less, however it's just a workaround, that doesn't really work...

**Comment by davidnorthetal** [comment]
Thanks for your quick response!

I'm possibly missing something here, but neither `urxvt` nor `mintty` seem to have this issue, so I'm wondering how exactly this is not a problem of alacritty when other terminal-emulators seem to not have this problem.

Is this explicitly not in the scope of alacritty?

**Comment by davidnorthetal** [comment]
On second try, I have just tried it with `urxvt` and it seems to also run into these issues eventually, but it seems more robust, I can not reproduce this on `urxvt` with just the prompt like in the example I showed above.

However once I add more output like a simple `ls`, resizing around eventually causes this issue also for `urxvt`.

**Comment by kchibisov** [comment]
Yeah, as I mentioned, it's a matter of how much workarounds you add, since you can't really fix it in a terminal.

(that's urxvt)

![picture](https://user-images.githubusercontent.com/27620401/99148769-b0ebe200-269a-11eb-9c38-6fe5ded7592e.png)

f

**Comment by davidnorthetal** [comment]
You are correct, while I can see that this is not a problem that seems to have a definite and ultimate solution, I would consider this issue fixed if I could disable reflow and recreat the same behavior as in `mintty`.

I have checked the config and it seems there is no option to disable it.

I have found the merge request in which the contributor decided against it on the grounds that he considers it a "universal benefit" and that there's no reason to disable it.

However I think this issue makes a solid case that this is not a benefit without issues and that considering these problems it might be preferrable to just do what `mintty` does and simply not re-layout the contents but "cut them off".

Does this make sense?

**Comment by davidnorthetal** [comment]
Here is a test-case that shows how the default reflow behavior under windows using the much used `git-bash` breaks immediately, even without using PS2 / right-prompt, yet works fine under `mintty`:

https://imgur.com/a/dBUMauF

@kchibisov

**Comment by chrisduerr** [comment]
I've opened https://github.com/alacritty/alacritty/issues/4424 to discuss the idea of maybe adding a configuration option to disable text reflow.

**Comment by blueray453** [comment]
Fish Shell's Astronaut Prompt Bellow. It also Happen with other fish shell prompts and also zsh prompts. 
 
![astronaut fish](https://github.com/alacritty/alacritty/assets/855297/e309a517-5784-41a0-818e-5a52ccaa7aef)
