### ISSUE TITLE
macOS icon not present if executing binary instead of opening the App

### ISSUE THREAD

**Issue by noib3** [alacritty/alacritty#4420]
### System

OS: macOS
Version: alacritty 0.5.0 (a6681e3)

If one wants to open alacritty from a terminal in macOS there are 2 options:
 1. `open -na /Applications/Alacritty.app/`
 2. `/usr/local/bin/alacritty`

The second one has the advantage that it allows flags and options, for example `alacritty --command ytop`. However, spawning a new alacritty window in this way causes the window icon to not be loaded properly, like in the following screenshot

![2020-Nov-14@15:11:42](https://user-images.githubusercontent.com/59321248/99149020-bc83dc80-268b-11eb-956f-b6beee6bc88f.png)

**Comment by chrisduerr** [comment]
Not much of a surprise, if you want a proper GUI integration you have to use the application bundle.

**Comment by noib3** [comment]
But it wasn't always like this, in the previous release (or maybe in the one before that) the icon worked even when calling the binary directly.

**Comment by chrisduerr** [comment]
Can you fix this by downgrading Alacritty? If you can then I'm happy to re-open, otherwise it might have been a change in macOS? The concrete commit which broke this would be ideal.

**Comment by noib3** [comment]
@chrisduerr I tested this a bit more and actually the icon from the binary in `/usr/local/bin/alacritty` never worked, even in the previous versions. However, what did work was using the binary in `/Applications/Alacritty.app/Contents/MacOS/alacritty`. This way the icon is shown correctly and I can still use flags and options.

I guess what's causing this is the icon path is relative to the binary file, and calling the one symlinked to `/usr/local/bin` gets the path wrong?

**Comment by chrisduerr** [comment]
Alacritty doesn't actually do any icon loading on macOS. That's all done by the system. So yeah, you just need the application bundle and the stuff in `/usr/local/bin` is just a raw executable with no other data attached.
