### ISSUE TITLE
Failed to build alacritty on fresh Mint 20 distribution

### ISSUE THREAD

**Issue by lerignoux** [alacritty/alacritty#4423]
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

OS: Linux
Version: while building on v0.5.0
Linux/BSD: X11/Wayland, DE or Compositor and WM

### Logs
`cargo build --release` and `cargo install alacritty` fail on 
```
   Compiling servo-fontconfig-sys v5.1.0
error: failed to run custom build command for `servo-fontconfig-sys v5.1.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installLpbQ5n/release/build/servo-fontconfig-sys-bcaabdcbad79feba/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=FONTCONFIG_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=FONTCONFIG_STATIC
  cargo:rerun-if-env-changed=FONTCONFIG_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at '`"pkg-config" "--libs" "--cflags" "fontconfig" "fontconfig >= 2.11.1"` did not exit successfully: exit code: 1
  --- stderr
  Package fontconfig was not found in the pkg-config search path.
  Perhaps you should add the directory containing `fontconfig.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'fontconfig' found
  Package fontconfig was not found in the pkg-config search path.
  Perhaps you should add the directory containing `fontconfig.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'fontconfig' found
  ', /home/laurent/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-fontconfig-sys-5.1.0/build.rs:34:17
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
     1: std::panicking::begin_panic_fmt
               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:429
     2: build_script_build::main
     3: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `alacritty v0.5.0`, intermediate artifacts can be found at `/tmp/cargo-installLpbQ5n`
```
Tell me if the verbose logs could be useful.

## Investigation
I checked the packages installed on my system. I ran the Debian suggested installs:
```
apt-get install cmake pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev python3
```
I also checked the packages I have installed and everything seems alright:
```
libfont-afm-perl/focal,focal,now 1.20-2 all [installed]
libfont-ttf-perl/focal,focal,now 1.06-1 all [installed]
libfontconfig1-dev/focal,now 2.13.1-2ubuntu3 amd64 [installed]
libfontconfig1/focal,now 2.13.1-2ubuntu3 amd64 [installed]
libfontembed1/focal,now 1.27.4-1 amd64 [installed]
libfontenc1/focal,now 1:1.1.4-0ubuntu1 amd64 [installed]
```

Would you have any idea how to solve/debug this issue ?

PS: it seems there is no Debian package available right ?
I'd rather avoid snaps, Is there another way to get alacritty ?

**Comment by kchibisov** [comment]
What `pkg-config --modversion --libs --cflags fontconfig` returns?

**Comment by brianwisti** [comment]
Just saw the same issue trying to build on Ubuntu 20.04, where it turns out I never define `$PKG_CONFIG_PATH` in my heavily customized shell init. Once I confirmed the location of `.pc` files on my system, setting the shell variable resulted in a clean build for me. Might check and try the same, @lerignoux?

``` shell
export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
```

**Comment by lerignoux** [comment]
> Just saw the same issue trying to build on Ubuntu 20.04, where it turns out I never define `$PKG_CONFIG_PATH` in my heavily customized shell init. Once I confirmed the location of `.pc` files on my system, setting the shell variable resulted in a clean build for me. Might check and try the same, @lerignoux?
> 
> ```shell
> export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
> ```

Yes thanks a lot this was indeed the issue and I managed to build it successfully !!

> pkg-config --modversion --libs --cflags fontconfig

the package was not found in the pkg-config path

**Comment by lerignoux** [comment]
> Just saw the same issue trying to build on Ubuntu 20.04, where it turns out I never define `$PKG_CONFIG_PATH` in my heavily customized shell init. Once I confirmed the location of `.pc` files on my system, setting the shell variable resulted in a clean build for me. Might check and try the same, @lerignoux?
> 
> ```shell
> export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
> ```

The package is not found in the pkg-config path

**Comment by nyngwang** [comment]
> Just saw the same issue trying to build on Ubuntu 20.04, where it turns out I never define `$PKG_CONFIG_PATH` in my heavily customized shell init. Once I confirmed the location of `.pc` files on my system, setting the shell variable resulted in a clean build for me. Might check and try the same, @lerignoux?
> 
> ```shell
> export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
> ```

@brianwisti You're so awesome! Thanks for your help! Respect!

**Comment by carjuan** [comment]
> Just saw the same issue trying to build on Ubuntu 20.04, where it turns out I never define `$PKG_CONFIG_PATH` in my heavily customized shell init. Once I confirmed the location of `.pc` files on my system, setting the shell variable resulted in a clean build for me. Might check and try the same, @lerignoux?
> 
> ```shell
> export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
> ```

Thank you!
