### ISSUE TITLE
decoration: none disables option to move the window at all, stuck with the same size etc

### ISSUE THREAD

**Issue by bragjo** [alacritty/alacritty#4428]
### System

OS: Linux Pop!_OS 20.04 LTS x86_64
Version: alacritty 0.6.0-dev
Linux/BSD: X11

As title says we are unable to move the Alacritty window while decorations: none is set in the alacritty.yml file.
Any fix to this? tried to google it but saw another issue opened for this and got immediately closed. Badly need this option to work!

**Comment by chrisduerr** [comment]
It disables the decorations, but you can still do whatever you want with it just fine? If it doesn't work, that's the fault of your window manager.

Are you using GNOME/X11?

**Comment by bragjo** [comment]
Yes, correct Im using x11/GNOME

Den sön 15 nov. 2020 03:40Christian Duerr <notifications@github.com> skrev:

**Comment by contyk** [comment]
Try mouse drag with various buttons while holding `Alt` or `Super`.

**Comment by jpmcb** [comment]
I'm seeing the same on the newest release of Pop!_OS:

**System info**
OS: Pop!_OS 20.10 x86_64
Kernel: 5.11.0-7612-generic
DE: GNOME 3.38.3
WM: Mutter
WM Theme: Pop

Using the mouse to drag the window with `Super` works fine, so this can be closed? Or is it expected the user can use the decorations?

**Comment by robertfalken** [comment]
I am experiencing the same issue in alacritty 0.7.2 on MacOS with the Magnet window manager. Using the mouse works just fine. But the window manager can't do anything, neither resize nor move the window.

**Comment by chrisduerr** [comment]
Closing, since this should be possible with any sensible window manager (and is to my knowledge on at least macOS/Linux/Windows/BSD).

**Comment by cratolabs** [comment]
Resize can be possible by using `Super` + `middle mouse click` and moving the mouse in the direction you want to resize.
