### ISSUE TITLE
Terminal colors gone after macOS Big Sur upgrade

### ISSUE THREAD

**Issue by johantell** [alacritty/alacritty#4430]
After upgrading to Big Sur most of my colors are all gone. 

I'm fairly unsure what could have caused this issue but after the upgrade all kinds of colors are gone and I'm guessing it's tied to Alacritty since the default terminal shows things as usual (Even Vim fails to show color highlighting.

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/1777129/99183608-5eafcd00-273d-11eb-87a2-0fd4661cb7c3.png">

### System

OS: macOS (Big Sur)
Alacritty Version:  0.5.0
Shell: ZSH

### Logs

```
$ alacritty -vv
[2020-11-15 12:14:24.238970000] [DEBUG] Using environment locale: en_US.UTF-8
[2020-11-15 12:14:24.239162000] [INFO] Welcome to Alacritty
[2020-11-15 12:14:24.239192000] [INFO] Configuration loaded from "/Users/johantell/.config/alacritty/alacritty.yml"
[2020-11-15 12:14:24.283916000] [DEBUG] Estimated DPR: 2
[2020-11-15 12:14:24.283988000] [DEBUG] Estimated Cell Size: 19 x 40
[2020-11-15 12:14:24.284015000] [DEBUG] Estimated Dimensions: Some((1528, 968))
[2020-11-15 12:14:24.330551000] [INFO] Device pixel ratio: 2
[2020-11-15 12:14:24.333539000] [INFO] Initializing glyph cache...
[2020-11-15 12:14:24.350686000] [INFO] ... finished initializing glyph cache in 0.01706203s
[2020-11-15 12:14:24.350768000] [INFO] Estimated DPR correctly, skipping resize
[2020-11-15 12:14:24.350798000] [INFO] Cell Size: 19 x 40
[2020-11-15 12:14:24.350818000] [INFO] Padding: 4 x 4
[2020-11-15 12:14:24.350838000] [INFO] Width: 1528, Height: 968
[2020-11-15 12:14:24.351497000] [INFO] PTY dimensions: Line(24) x Column(80)
```

Theme configuration:

```
ayu_dark: &ayu_dark
  primary:
    background: '#222222'
    foreground: '#B3B1AD'

  normal:
    black: '#01060E'
    red: '#EA6C73'
    green: '#91B362'
    yellow: '#F9AF4F'
    blue: '#53BDFA'
    magenta: '#FAE994'
    cyan: '#90E1C6'
    white: '#C7C7C7'

  bright:
    black: '#686868'
    red: '#F07178'
    green: '#C2D94C'
    yellow: '#FFB454'
    blue: '#59C2FF'
    magenta: '#FFEE99'
    cyan: '#95E6CB'
    white: '#FFFFFF'

colors: *ayu_dark
```

**Comment by kchibisov** [comment]
if you run without config `printf "\033[1;31m Sample Text \033[0m\n"` is also not colored?

**Comment by johantell** [comment]
Damn, now you make me feel stupid...

<img width="310" alt="image" src="https://user-images.githubusercontent.com/1777129/99183920-ce26bc00-273f-11eb-828e-bafc5bfd2e3a.png">

It worked as it should if I use the default config so I'll dig deeper into what could this could be about. Will try to post here when I find it in case someone else has the same issue. Thanks for the fast response!

**Comment by johantell** [comment]
It was a problem with my font settings (disabling the custom font solved the color issues)

**Comment by kchibisov** [comment]
Huh, what's your font?

**Comment by johantell** [comment]
My version Source Code Pro seems problematic for some reason. I have it downloaded through the brew cask. Worked with most other fonts I tried so I'll stick to Menlo for a bit :P

**Comment by chrisduerr** [comment]
You're probably talking about https://github.com/alacritty/crossfont/issues/17.

**Comment by johantell** [comment]
Could be, I'll keep a close watch, thanks @chrisduerr!

**Comment by nosami** [comment]
> My version of Source Code Pro seems problematic for some reason. I have it downloaded through the brew cask. Worked with most other fonts I tried so I'll stick to Menlo for a bit :P

I'm using Hasklig which is derived from Source Code Pro.  Switching to Menlo fixes for me too.

I should probably point out that I just updated Alacritty and my old version (sorry not sure which version it was) was working fine with this font.

**Comment by nosami** [comment]
The latest version of Source Code Pro (released 4 days ago) is working fine in Alacritty https://github.com/adobe-fonts/source-code-pro/releases/tag/2.032R-ro/1.052R-it/1.012R-VAR


Seems like lots of apps are broken https://github.com/adobe-fonts/source-code-pro/issues/250

**Comment by pokevania** [comment]
[https://superuser.com/questions/399594/color-scheme-not-applied-in-iterm2#](url)

Add these to .bash_profile (or for whatever shell you use):

# Set CLICOLOR if you want Ansi Colors in iTerm2 
export CLICOLOR=1

# Set colors to match iTerm2 Terminal Colors
export TERM=xterm-256color

**Comment by jhessin** [comment]
I was able to get it working by changing my font from `Source Code Pro` to `Source Code Pro for Powerline`.
