### ISSUE TITLE
v0.6.0-rc2 doesn't have msi installer

### ISSUE THREAD

**Issue by davidhewitt** [alacritty/alacritty#4432]
At https://github.com/alacritty/alacritty/releases I can't see the usual msi installer in the v0.6.0-rc2 (or rc1) artifacts - is this now deprecated? I couldn't see a changelog entry about it.

**Comment by kchibisov** [comment]
Yes, this is expected, the installer will be for release, msi can't handle versioning with `-rc` at the end.

**Comment by kchibisov** [comment]
As you can see on release page, none of the rc's ever had msi thing.

**Comment by davidhewitt** [comment]
Thanks, sorry for the noise!
