### ISSUE TITLE
Opening Alacritty inside Window Terminal

### ISSUE THREAD

**Issue by samodostal** [alacritty/alacritty#4433]
I'm trying to run alacritty inside Window Terminal app. I tried adding windows terminal inside settings.json of Windows Terminal:
![image](https://user-images.githubusercontent.com/44208530/99250134-7c4b6800-280b-11eb-8c98-08c9b06226a9.png)
But now when I open new Alacritty window inside Windows Terminal, Alacritty opens as an Application, instead of opening inside as one a tab.
Can anyone help me with this one?

**Comment by kchibisov** [comment]
Because we're not a shell but a terminal emulator, powershell for examle is a shell and a terminal emulator in one place.
