### ISSUE TITLE
Issue with bundled terminfo in OSX .dmg

### ISSUE THREAD

**Issue by Woodham** [alacritty/alacritty#4438]
### System

OS: macOS/
Version: 0.5.0

I happend to be reinstalling Alacritty on a new OSX system and noticed there had been a relatively recent change to add completions,manpage and terminfo the OSX bundle - https://github.com/alacritty/alacritty/pull/3441

However, after downloading and inspecting there seems to be an issue with the terminfo.

Output from `ls -la /Applications/Alacritty.app/Contents/Resources/`:

`61		alacritty.1.gz	alacritty.icns	completions`

It looks like the `61` folder contains the contents of the terminfo file, but not in a format that I can install?

`ls /Applications/Alacritty.app/Contents/Resources/61`:

`alacritty		alacritty-direct`

**Comment by chrisduerr** [comment]
> It looks like the 61 folder contains the contents of the terminfo file, but not in a format that I can install?

Why not?

**Comment by Woodham** [comment]
It's entirely possible I'm misunderstanding something but I tried the following:

```
$ sudo tic -xe alacritty,alacritty-direct /Applications/Alacritty.app/Contents/Resources/61
tic: /Applications/Alacritty.app/Contents/Resources/61 is not a file

$ sudo tic -xe alacritty,alacritty-direct /Applications/Alacritty.app/Contents/Resources/61/alacritty
"/Applications/Alacritty.app/Contents/Resources/61/alacritty", line 1, col 1: Illegal character (expected alphanumeric or @%&*!#) - '^Z'

$ sudo tic -xe alacritty,alacritty-direct /Applications/Alacritty.app/Contents/Resources/61/alacritty-direct 
"/Applications/Alacritty.app/Contents/Resources/61/alacritty-direct", line 1, col 1: Illegal character (expected alphanumeric or @%&*!#) - '^Z'
```

**Comment by chrisduerr** [comment]
The file is already prebuilt, you just need to move it to the correct place.

**Comment by Woodham** [comment]
Got it, apologies I understand what I was missing now - the correct command is `sudo cp -r /Applications/Alacritty.app/Contents/Resources/61 ~/.terminfo/`

**Comment by chrisduerr** [comment]
Correct, that's the place in your local terminfo database. Alternatively with root permissions there should also be a global database for all users.

**Comment by Woodham** [comment]
Yeah I initially tried `sudo cp /Applications/Alacritty.app/Contents/Resources/61/* /usr/share/terminfo/61/` but it seems to be protected in OSX even with root permissions. I suspect it's something to do with System Integrity Protection - https://support.apple.com/en-us/HT204899

**Comment by chrisduerr** [comment]
Ah I don't have system integrity protection, so I wouldn't know.
