### ISSUE TITLE
Error at cargo build, (noob) Need help 

### ISSUE THREAD

**Issue by manusimon** [alacritty/alacritty#4439]
Im using linux mint 20 and im getting this error :

m4s1@m4s1compu:~/Descargas/alacritty$ cargo build --release
   Compiling alacritty v0.7.0-dev (/home/m4s1/Descargas/alacritty/alacritty)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/m4s1/Descargas/alacritty/target/release/deps/alacritty-005344080a92bf29.alacritty.6a05w4hx-cgu.4.rcgu.o" "-o" "/home/m4s1/Descargas/alacritty/target/release/deps/alacritty-005344080a92bf29" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/home/m4s1/Descargas/alacritty/target/release/deps" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,--start-group" "-Wl,-Bstatic" "/tmp/rustcTqSJfJ/libbacktrace_sys-4546f4207f7495c9.rlib" "-Wl,--end-group" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-d61dbae1fa88f6f5.rlib" "-Wl,-Bdynamic" "-lfreetype" "-lfontconfig" "-lfreetype" "-lexpat" "-lfreetype" "-lxcb" "-lxcb" "-lxcb" "-lxcb" "-lxcb-render" "-lxcb-shape" "-lxcb-xfixes" "-ldl" "-ldl" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-lutil"
  = note: /usr/bin/ld: no se puede encontrar -lxcb-shape
          /usr/bin/ld: no se puede encontrar -lxcb-xfixes
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: could not compile `alacritty`.

To learn more, run the command again with --verbose.
m4s1@m4s1compu:~/Descargas/alacritty$

**Comment by kchibisov** [comment]
make sure you've installed dependencies

https://github.com/alacritty/alacritty/blob/master/INSTALL.md#debianubuntu

**Comment by manusimon** [comment]
> make sure you've installed dependencies
> 
> https://github.com/alacritty/alacritty/blob/master/INSTALL.md#debianubuntu

Yep i did install everithing
