### ISSUE TITLE
Paste Password

### ISSUE THREAD

**Issue by blueray453** [alacritty/alacritty#4450]
Suppose I am using the command

```
$ git remote add origin git@github.com:blueray453/my-new-project.git
$ git push -u origin master
```

It asks for username and password. 

I can not paste username or password here using keyboard shortcut. If i use ctrl+v, it will print ^V in the username or password field.

In gnome-terminal I can paste the copied password using mouse right click.

What can I do in case of Alacritty?

**Comment by enizor** [comment]
By default Paste uses the Control-Shift-V binding (Command-V on MacOS).
```alacritty.yml
  #- { key: V,              mods: Control|Shift,           action: Paste            }
```

Edit your configuration file if you prefer a different binding.
