### ISSUE TITLE
Differentiating Ctrl+Tab from plain Tab

### ISSUE THREAD

**Issue by K41eb** [alacritty/alacritty#4451]
Couldn't find any mention of this in the issues or the Feature.md file so I'm asking here:

### System

OS: Linux
Version: alacritty 0.5.0 (a6681e3a)
Linux/BSD: X11, bspwm
Windows: ???

### Logs

Irrelevant

### My issue

I am using vim and was skimming through the `netrw` documentation and came accross this feature:

```
SHRINKING OR EXPANDING A NETRW OR LEXPLORE WINDOW       netrw-c-tab {{{2

The <c-tab> key will toggle a netrw or :Lexplore window's width,
but only if g:netrw_usetab exists and is non-zero (and, of course,
only if your terminal supports differentiating <c-tab> from a plain
<tab>).
...
```

I tried using it and could not get Ctrl+Tab to do anything (`<c-tab>` above).
Does Alacritty support "differentiating `<c-tab>` from a plain
`<tab>`" ?

**Comment by enizor** [comment]
```[alacritty] glutin event: DeviceEvent { device_id: DeviceId(DeviceId(65607)), event: Key(KeyboardInput { scancode: 15, state: Pressed, virtual_keycode: Some(Tab), modifiers: CTRL }) }

[alacritty] glutin event: DeviceEvent { device_id: DeviceId(DeviceId(65607)), event: Key(KeyboardInput { scancode: 15, state: Released, virtual_keycode: Some(Tab), modifiers: (empty) }) }

**Comment by chrisduerr** [comment]
Does this work in any other terminal emulator for you @K41eb?

**Comment by K41eb** [comment]
I haven't tried other terminal emulators, I will try modifying my configuration now.

**Comment by K41eb** [comment]
> if you find the proper chars to send
lol

**Comment by K41eb** [comment]
How in trouble am I if `showkey -a` only displays the plain `Tab` scancode when I type `Ctrl+Tab`?

**Comment by chrisduerr** [comment]
The reason why I'm asking if this works in another terminal, is because this is the intended behavior as far as I'm aware.

**Comment by dnkl** [comment]
XTerm with `modifyOtherKeys=1`. First key is <kbd>Tab</kbd>, second one is <kbd>Ctrl</kbd>+<kbd>Tab</kbd>.

```
~% sudo showkey -a
Press any keys - Ctrl-D will terminate this program

                  9 0011 0x09
^[[27;5;9~       27 0033 0x1b
         91 0133 0x5b
         50 0062 0x32
         55 0067 0x37
         59 0073 0x3b
         53 0065 0x35
         59 0073 0x3b
         57 0071 0x39
        126 0176 0x7e
```

**Comment by chrisduerr** [comment]
@dnkl Yeah, but as far as I know that's not enabled on any terminal by default? And I'm not sure if vim enables that by itself?

**Comment by K41eb** [comment]
Using `showkey -a` in both xterm and alacritty output `Both X term and Alacritty output `9 0011 0x09` whether I type `Tab` or `Ctrl+Tab`.

**Comment by K41eb** [comment]
I suppose it has nothing to do with Alacritty then.

If that's not asking too much:

I have been reading https://wiki.archlinux.org/index.php/Keyboard_input for a while now and I stil cannot pinpoint where the problem lies.

Keyboard:
`showkey -s` gives me 4 different codes for Tab down/release (`0x0f`/`0x8f`) and Control down/release (`0x1d`/`0x9d`). So I assume nothing's wrong on the keyboard side of things.

Kernel:
I don't know what the kernel keycodes are.

X11:
`xev` Recognizes when I type Left Control (`37 Control_L`) or Tab (`23 Tab`). 

To me, a complete noob on the subject, it looks fine from keyboard to X11. But what happens between X11 and Alacritty / xterm that prevents them from understanding the `Ctrl+Tab` combination? When is this "combination" even supposed to be interpreted as such?

**Comment by dnkl** [comment]
@chrisduerr I only tested kitty,  urxvt and qterminal, but yeah, you're right; none of them enable this by default. Furthermore, none of them supports the escape sequence to enable it either. Didn't test the "big" ones (gnome-terminal, konsole), but don't expect them to be any different.

> And I'm not sure if vim enables that by itself?

Not sure either, but doubt it. The only application that I know for sure uses it is Emacs. Other seems to rely on the user enabling it in their X resources.

But at the very least, this issue is a duplicate of https://github.com/alacritty/alacritty/issues/3101, isn't it?

@K41eb XTerm needs its `modifyOtherKeys` to be set to `1`. This can either be done in `~/.Xresources`:

```
xterm*modifyOtherKeys: 1
```
(reload with `xrdb ~/.Xresources)

or, you can enable/disable it run-time, inside XTerm, with `echo -e '\e[>4;1m'` to enable, and `echo -e '\e[>4m'` to revert back to the default.

**Comment by K41eb** [comment]
@dnkl Oh my bad, it will teach me for not readig the whole thing, I get the same results as you do now.
#3101 Seem to be encompassig my problem yes.

**Comment by chrisduerr** [comment]
> But at the very least, this issue is a duplicate of #3101, isn't it?

Yeah, that's fair.

**Comment by tombh** [comment]
Just wanted to post my solution for anyone else in the same boat, as this issue comes high up in Google for me.

I'm on Wayland and just wanted Ctrl+Tab for MRU buffer switching in Neovim. I needed 2 config settings:

In `.zshrc`:
```sh
echo -e '\e[>4;1m'
```

In `alacritty.yml`:
```yaml
key_bindings:
  # ...
  - { key: Tab, mods: Control, chars: "\x1b[27;5;9~" }
```

**Comment by casonadams** [comment]
And building off of what @tombh has above
Control + Shift + Tab
Control + Tab

[Source](https://stackoverflow.com/questions/12546750/vim-keyboard-shortcut-to-move-around-tabs/43692522#43692522)

I didn't need to add anything to my `.zshrc` file.  But I am using `oh-my-zsh` so it might be there already.

in `alacritty.yml`:
```
key_bindings:
  # ...
  - {key: Tab, mods: Control, chars: "\x1b[27;5;9~"}
  - {key: Tab, mods: Control|Shift, chars: "\x1b[27;6;9~"}
```

**Comment by 5top1t** [comment]
Alacrity has moved over to toml files. Here is the config for toml
```toml
[extra]
# Add the following lines to your configuration file to set the keybindings for Tab with Control and Control+Shift:
[keyboard]
bindings = [
    { key = "Tab", mods = "Control", chars = "\x1b[27;5;9~" },
    { key = "Tab", mods = "Control|Shift", chars = "\x1b[27;6;9~" }
]
```

**Comment by phoulx** [comment]
The chars starting with `\x1b` not work for me.
I altered the chars like following and it's fine:
```
bindings = [
    { key = "Tab", mods = "Control", chars = "\u001b[27;5;9~" },
    { key = "Tab", mods = "Control|Shift", chars = "\u001b[27;6;9~" },
]
```
Besides, I config the bindings for use in tmux.

**Comment by wong-justin** [comment]
Hm, that `\u001b` update fixes the toml parsing error, but `Ctrl+Tab` is still getting eaten for me. I'm on the latest Windows release `v0.13.1`.
