### ISSUE TITLE
any plan to release binary for apple silicon?

### ISSUE THREAD

**Issue by fisheye-123** [alacritty/alacritty#4453]

**Comment by chrisduerr** [comment]
If GitHub CI switches to use ARM, Alacritty's build will be ARM. If it doesn't, it won't. Either way we're not going to go out of our way to work around this.

**Comment by johnny88** [comment]
You can also build Alacritty yourself if on apple silicon. I just tried it and it works, I had some trouble before with dependencies not compiling but now things seem to be working.
