### ISSUE TITLE
Find config files from $XDG_CONFIG_DIRS too

### ISSUE THREAD

**Issue by jluttine** [alacritty/alacritty#4457]
Alacritty read config files from the following locations:

1. `$XDG_CONFIG_HOME/alacritty/alacritty.yml`
2. `$XDG_CONFIG_HOME/alacritty.yml`
3. `$HOME/.config/alacritty/alacritty.yml`
4. `$HOME/.alacritty.yml`

It would be nice to support also system-wide defaults under `$XDG_CONFIG_DIRS`, that is, search `alacritty/alacritty.yml` under each of those config directories.

By the way, what is done if multiple config files are found? Is the first occurrence used or are they merged? The same logic could be applied here. In general, I think merging would be awesome.

A few usecases:

- Distros can specify system-wide default configs.
- In one system, each desktop environment can specify their own default config and just modify `$XDG_CONFIG_DIRS` env var in the desktop environment. (This is what I'm trying to do at the moment as a desktop environment developer.)

**Comment by kchibisov** [comment]
>By the way, what is done if multiple config files are found? Is the first occurrence used or are they merged? The same logic could be applied here. In general, I think merging would be awesome.

The first is used, if you want merging, use `import` section.

>A few usecases:

Are you aware of anyone doing so?

**Comment by jluttine** [comment]
> > A few usecases:
> 
> Are you aware of anyone doing so?

As far as I understand, it is quite common in many distros to put default configs for some of the apps under `$XDG_CONFIG_DIRS` (not too familiar with this though, so I might be wrong). Anyway, I think it would follow nicely the XDG base directory specification standard.

**Comment by chrisduerr** [comment]
Have you tested that this doesn't already work?

**Comment by jluttine** [comment]
No, I didn't test, I just read README. Yes, I can test.

**Comment by jluttine** [comment]
Oh, it actually does work already! Nice! However, I didn't quite understand why it worked as there's no reference to `XDG_CONFIG_DIRS` in the entire codebase..

Would it be useful to mention this support in README?

Anyway, seems to work, so I'll close this. Thanks! :+1:
