### ISSUE TITLE
Change instructions regarding fedora installation

### ISSUE THREAD

**Issue by Everlastinggit** [alacritty/alacritty#4458]
Alacritty is avaible in the official fedora repo so I think the instructions should be updated to redirect people to install from the official repo.

**Comment by kchibisov** [comment]
You mean, to remove the mention of  copr repo?

**Comment by Everlastinggit** [comment]
Yes.

**Comment by chrisduerr** [comment]
Feel free to send a pull request yourself, that's probably the easiest way to get things fixed quickly.
