### ISSUE TITLE
Build Fails on Raspberry Pi 4B - could not compile crossfont

### ISSUE THREAD

**Issue by media7concept** [alacritty/alacritty#4460]
Hello. I'm trying to build from source on Raspbian because it isn't in official repositories and I didn't find any other good options. When I attempt to cargo build the code, it goes smoothly until it tries to compile crossfont:
```
error: attributes are not yet allowed on `if` expressions
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/crossfont-0.1.1/build.rs:4:5
  |
4 |     #[cfg(not(any(target_os = "macos", windows)))]
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `crossfont`.
warning: build failed, waiting for other jobs to finish...
error: build failed

```

### System

OS: Raspbian Lite
Hardware: Raspberry Pi 4B 2GB RAM

**Comment by kchibisov** [comment]
The minimum supported rust version is 1.43, make sure that that's the one you're using.
