### ISSUE TITLE
Fails to start on Manjaro with Wayland

### ISSUE THREAD

**Issue by budde25** [alacritty/alacritty#4461]
I just downloaded it with pacman -Syu alacritty and ran it from my terminal.
Interestingly it failed to create a desktop file the first time I installed it. I tried reinstalling too. and it was there but clicking does nothing
The expect output would've been for it to open (and also create .desktop file)

### System

OS: Linux (Manjaro)
Version: alacritty 0.5.0 (a6681e3a) Installed from offically repositories
Linux: Wayland w/ (XWayland)

### Logs

Crashes: STDERR, STDOUT
```
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoCompositorListening X11 status: XOpenDisplayFailed', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/mod.rs:569:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Font/Terminal size: `alacritty -vv`
Fails before printing anything

Keyboard and bindings: `alacritty --print-events`
Fails before printing anything

**Comment by chrisduerr** [comment]
Are you running GNOME?

**Comment by budde25** [comment]
Sorry forgot to include that. Yes I am, version 3.38.1

**Comment by budde25** [comment]
So I just tried running it again, and its still crashing but the error is slightly different now. I haven't had issue with any other programs that I know of. A little more info is that I am running the [Surface Linux](https://github.com/linux-surface/) kernel on a SurfaceBook 2 so I wondering if its an issue with trying to communicate with the GPU which isn't always available on my system. That being said both times the GPU has been available when trying to run it.
```
❯ alacritty
[wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.
[1]    60793 abort (core dumped)  alacritty
```

**Comment by kchibisov** [comment]
that's fixed on latest master.
