### ISSUE TITLE
Character composition doesn't render correctly

### ISSUE THREAD

**Issue by shade-of-noon** [alacritty/alacritty#4462]
### System

OS: Arch Linux
Version: `alacritty 0.7.0-dev (da6f0a50)`
Compositor: Wayland, Sway
Sway Keyboard Config: [xkb-layout.txt](https://github.com/alacritty/alacritty/files/5584763/layout.txt)

### Logs

Font/Terminal size: [alacritty-vv.txt](https://github.com/alacritty/alacritty/files/5584755/alacritty-vv.txt)
Keyboard and bindings: [alacritty-print-events.txt](https://github.com/alacritty/alacritty/files/5584753/alacritty-print-events.txt)

### Description

Characters followed by stuff like U+0308 are rendered as the character followed by the diacritic mark.

- Inside Vim/Neovim, `a` followed by U+0308 instead of being rendered as `ä` it renders like:

```
aö
```

where the `o` indicates an empty space.

- In the command line (Zsh), I get this:

```
$ echo "a<0308>"
aö
```
(where the `o` again indicates empty space.)

I checked with a VTE-based terminal (xfce4-terminal) and the characters get rendered as expected:

```
$ echo "xfc<0328>e<0308>-termin<0303>al"
xfc̨ë-termiñal
```

**Comment by kchibisov** [comment]
What font is that?

**Comment by shade-of-noon** [comment]
> What font is that?

It's the font recommended by [zsh-powerlevel10k](https://github.com/romkatv/powerlevel10k/blob/master/README.md#meslo-nerd-font-patched-for-powerlevel10k).

I just checked with Inconsolata and DejaVu Sans Mono and that doesn't fix the issue. For curiosity's sake I also checked with non-monospace fonts (DejaVu Sans) and issue is not present, it seems to be something to do with monospace font rendering.

**Comment by kchibisov** [comment]
Could you try Fira Mono or Hack, since they have correct metrics for zerowidth chars.

**Comment by shade-of-noon** [comment]
Hack is rendered correctly. Nonetheless I checked with xfce4-terminal + {MesloLGS, Inconsolata, Dejavu Sans Mono}, xfce4-terminal does not have this problem with these fonts.

As an extra, xfce4-terminal does have this problem with unusual combinations like 0̈ (zero with diearesis).

**Comment by kchibisov** [comment]
It likely does unicode normalization, and alacritty doesn't. For example firefox also renders them like that for me.

![picture](https://user-images.githubusercontent.com/27620401/100002856-39bef800-2dd6-11eb-9b55-a0dd18ba010e.png)

I'm not sure if we should change anything and start doing so....

**Comment by shade-of-noon** [comment]
> I'm not sure if we should change anything and start doing so....

Is it a hard problem then?

For the record, here's a pair of screenshots show the issue:

- Vim/Neovim
![image](https://user-images.githubusercontent.com/73705427/100003724-ef6d5500-2d9c-11eb-9862-5f8c12575bfc.png)

- Command Line
![image](https://user-images.githubusercontent.com/73705427/100003628-c9e04b80-2d9c-11eb-99f2-105caee8c9a0.png)

**Comment by kchibisov** [comment]
>Is it a hard problem then?

it's not, it's a matter of trusting font or replacing sequences of unicode with normalized character, in general fonts should provide sane metrics, and that's why it works with something like Hack/Fira Mono.

So right now alacritty renders everything as it is and trusts your font metrics, however there's an option to replace the characters you're asking to draw, with the ones that are just one character with an element you're asking to draw.

In general nothing stops us from doing unicode normalization, but the question is why it should be done? Why we should replace the characters you're asking to draw with some other characters?

**Comment by shade-of-noon** [comment]
Thanks for the explanation. I've being using US (Intl with dead keys) with AltGr. and I thought the expected/standard behaviour was for `u+<AltGr>:` to produce `ü`, for example. Well, I've got no problem using Hack/Fira for the time being.

> […] however there's an option to replace the characters you're asking to draw, with the ones that are just one character with an element you're asking to draw.

Excuse my ignorance, but what's the name of this option and is it documented somewhere? I don't think I saw it on the default `alacritty.yml`.

**Comment by kchibisov** [comment]
>Excuse my ignorance, but what's the name of this option and is it documented somewhere?

I mean, as a solution to that 'problem', which is not really a problem, I think. It's called https://en.wikipedia.org/wiki/Unicode_equivalence#Normalization

**Comment by shade-of-noon** [comment]
Ah, I thought you meant that alacritty had this option available.

**Comment by chrisduerr** [comment]
This is a problem with the font, unicode normalization is just a bit of a workaround. So if you want this fixed, the best choice is to pick a font that renders things correctly.
