### ISSUE TITLE
Reset cursor blink inverval on Vi/Search <-> Normal mode transitions.

### ISSUE THREAD

**Issue by kchibisov** [alacritty/alacritty#4468]
It should provide immediate feedback where the cursor is currently located.

**Comment by chrisduerr** [comment]
I'm not sure what you mean? Is the goal to make the cursor visible when the vi mode is entered and reset the interval?

**Comment by kchibisov** [comment]
Yeah, and when you leave Vi mode, so you immediately can see the cursor, even though it could be in a 'hidden' state during switch.

**Comment by chrisduerr** [comment]
Doesn't seem super high priority, but sure.
