### ISSUE TITLE
Attempt to input Korean characters using uim freezes Alacritty

### ISSUE THREAD

**Issue by RangHo** [alacritty/alacritty#4469]
When I press a key in "Hangul input mode", Alacritty window freezes and does not respond to any key or event inputs. (At least, it does not respond to ICCCM `WM_DELETE_WINDOW`event, and the only way to close Alacritty is to force kill the process.)

### System

* OS: Arch Linux running Zen Kernel 5.8.14
* Version: `alacritty 0.5.0 (a6681e3a)` and `alacritty 0.7.0-dev (9e6e35f)`.
* Display Manager: X11 using `bspwm` window manager with `picom` compositor
* IME: `uim` + `uim-byeoru`, with [custom configuration](https://github.com/RangHo/dotfiles/blob/master/uim/.uim)

### How to reproduce

1. Run `uim-xim &` to start uim (If X session was just started, this step is unnecessary)
2. At this point, typing regular Latin alphabets should work properly
3. Change input method by pressing `Shift + Space` (at least for my configuration)
4. Type a character, then Alacritty should become unresponsive

### Logs

For Alacritty logs, I tried  typing the following in order:
1. `uim-xim &`
2. `echo "Hello"`
3. `echo "안녕"`, by pressing `d k s s u d` in order

* [Alacritty event log](https://pastebin.com/imtGt569)
* [Output of `alacritty -vvv`](https://pastebin.com/sBZNZ8v8)
* [Output of `printenv`](https://pastebin.com/ziH5xs9r)

Since it doesn't really *crash*, neither `stdout` nor `stderr` gives any useful information.

**Comment by chrisduerr** [comment]
None of the event logs keep going after Alacritty freezes up, right?

Could you maybe hook up a debugger and check where exactly Alacritty is frozen, that would probably shed some more insight on what could cause the freeze.

**Comment by RangHo** [comment]
I just attached `gdb` to the freshly built `alacritty (9e6e35f)` and ran backtrace on it.

Trying to run a couple of `fin` commands shows that the `XIfEvent()` function from `libX11.so` never returns, no matter what I do to the target alacritty window. (resizing, clicking on it, mashing keyboards...) It seems X server doesn't even update the window properly, as I see graphical artifacts as below. The blurred rectangle is supposed to be the Alacritty window that I am debugging.

![Alacritty window not being redrawn](https://user-images.githubusercontent.com/10833976/100042219-5c8cf300-2e4e-11eb-90bb-714772380db4.png)

**Comment by chrisduerr** [comment]
You've kinda only shown the irrelevant part of the backtrace, could you share the stuff above `#13`?

**Comment by RangHo** [comment]
Sorry, I forgot to paste the full backtrace output. [Here](https://pastebin.com/RrtdiW3G) is the result of GDB `bt full` command. Frame `#0`~`#3` returns rather immediately, but `XIfEvent` function never seems to return.

I currently don't have the debug build of `libX11`. Do I need to provide debug information for that library as well?

**Comment by chrisduerr** [comment]
Huh that seems strange. We seem to send a perfectly acceptable `XFilterEvent` call (which shouldn't block) and that then seems to stall?

How well does `uim-xim` work with other applications?

**Comment by RangHo** [comment]
Two applications I know that utilizes XIM are `emacs` and `rxvt-unicode`. `uim-xim` works flawlessly for both programs, though intermediate output (character is being "assembled", and has not been committed yet) looks jumbled.

While testing `uim-xim`, I discovered a new error message that reads `Critical: XCreateFontSet failed!`. Since `emacs` and `urxvt` both produced this error message, I suspect this is from `uim-xim`. However, other programs using XIM seems to kinda *ignore* this message, while `alacritty` seems to freeze right after the first message.

![image](https://user-images.githubusercontent.com/10833976/100103067-c4235c80-2ea7-11eb-95e4-a06dfef42005.png)

I tried changing alacritty font that actually includes Hangul characters, but this didn't really do anything...

**Comment by chrisduerr** [comment]
Hmmm "Critical" sounds like a critical error, but I'm not sure what might be going on. Other IMEs certainly work, so it must be something about how uim works.

Could you try testing this with https://github.com/rust-windowing/winit? You can run its examples with `cargo run --example window`. I think chances are this should be reported upstream.

**Comment by RangHo** [comment]
I've done some digging around, and I found out that it was indeed `uim` that causes this freezing. Whenever I attempt to type a character, `uim` segfaults, rendering all alacritty instances using that XIM bridge deadlocked and unusable. (There was an issue reported at uim/uim#156 already.)

> Could you try testing this with https://github.com/rust-windowing/winit?

As `emacs` and `urxvt` handles this issue pretty gracefully (and `uim` doesn't crash and burn), I think there is indeed some room left for improvement. I will test their example windows and see if it is `winit`'s fault, and submit a new issue there if necessary. Thanks!

**Comment by RangHo** [comment]
Yep, I just confirmed that this issue occurs on **any** window powered by `winit`. Well, up to upstream it goes. Might need to do some more debugging to pinpoint the actual cause, though.

Closing this issue.
