### ISSUE TITLE
Error when trying to install the .deb package (blank line in value of field 'Description')

### ISSUE THREAD

**Issue by vkaracic** [alacritty/alacritty#4480]
I ran the `cargo build --release` command and finished successfully but when I try to run:

```
sudo dpkg -i target/debian/alacritty_0.6.0_amd64.deb
```

I get this error:

```
[11:33:22] (vedran) ~/alacritty 04cbf76
λ > sudo dpkg -i target/debian/alacritty_0.6.0_amd64.deb
dpkg: error processing archive target/debian/alacritty_0.6.0_amd64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 23 package 'alacritty':
 blank line in value of field 'Description'
Errors were encountered while processing:
 target/debian/alacritty_0.6.0_amd64.deb
```

Not sure if this is a known issue or not.

### System

OS: Linux
Version: 0.6.0
Linux/BSD: X11, DE

**Comment by chrisduerr** [comment]
What deb package? Alacritty doesn't provide a .deb.

**Comment by vkaracic** [comment]
In my command history I saw that I installed alacritty with `cargo deb --install -p alacritty` before, which created the deb package. This is probably not supported anymore.
