### ISSUE TITLE
cursor_blink info

### ISSUE THREAD

**Issue by ndavidpsi** [alacritty/alacritty#4481]
### System

OS: Windows
Version: alacritty 0.6.0 (04cbf76)

Has cursor_blink been implemented?

**Comment by elianiva** [comment]
It has but it's not on 0.6 as far as I'm aware.
https://github.com/alacritty/alacritty/blob/master/CHANGELOG.md#070-dev

**Comment by chrisduerr** [comment]
No.

**Comment by elianiva** [comment]
ok, so it's my setup then. Thanks for clearing that out.

**Comment by chrisduerr** [comment]
You might have to switch the blinking mode to `Always`. Ncurses applications use the terminal escape to disable blinking usually.

**Comment by ndavidpsi** [comment]
Where can I download that version? It doesn't seem to be present in the _releases_ page

**Comment by chrisduerr** [comment]
Because it is not released yet.
