### ISSUE TITLE
Fedora 33/Parallels/Mac Fails to run alacritty, terminates very early with no errors

### ISSUE THREAD

**Issue by jsumner** [alacritty/alacritty#4483]
When running alacritty on a newly installed fedora 32 alacrity worked. Upon upgrading to fedora 33 (and updating a few other components) alacritty has stopped working and terminates very early on. I can't workout why it's crashing just that it's crashing just after printing the debug for the estimated cell size (see logfile later).

This is running in a parallels VM on MacOS (Big Sur).

I get the same behavior when running 0.5.0, 0.6.0 and building from source. When building from source all unit tests pass.

### System

OS: Linux
`uname -a`
Linux localhost.localdomain 5.9.9-200.fc33.x86_64 #1 SMP Thu Nov 19 21:25:45 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
`[dev@localhost alacritty]$ cat /etc/redhat-release`
Fedora release 33 (Thirty Three)

Running Fedora 33 under Parallels (16) on Macbook pro (Big Sur) with Parallels tools installed.

Version: `alacritty --version` output
alacritty 0.7.0-dev (26479bb)

Linux/BSD: X11/Gnome

### Logs

Crashes: STDERR, STDOUT
`[dev@localhost alacritty]$ RUST_BACKTRACE=full ./target/debug/alacritty -vvvv` 
Created log file at "/tmp/Alacritty-17865.log"
[2020-11-25 13:40:50.611859068] [INFO ] [alacritty_config] No config file found; using default
[2020-11-25 13:40:50.612519077] [INFO ] [alacritty] Welcome to Alacritty
[2020-11-25 13:40:50.612591660] [INFO ] [alacritty] Configuration files loaded from:
[2020-11-25 13:40:50.628137764] [TRACE] [crossfont] Number of fonts is 42
[2020-11-25 13:40:50.628317351] [TRACE] [crossfont] Got font path="/usr/share/fonts/dejavu-sans-mono-fonts/DejaVuSansMono.ttf", index=0
[2020-11-25 13:40:50.628475111] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2020-11-25 13:40:50.629482451] [DEBUG] [alacritty] Estimated DPR: 1
[2020-11-25 13:40:50.629551864] [DEBUG] [alacritty] Estimated window size: None
[2020-11-25 13:40:50.629589147] [DEBUG] [alacritty] Estimated cell size: 9 x 17
Terminated
[dev@localhost alacritty]$ echo $?
143

Font/Terminal size: `alacritty -vv`
Crashes before command completes.

Keyboard and bindings: `alacritty --print-events`
Crashes before command completes.

**Comment by chrisduerr** [comment]
Have you tried attaching a debugger?

**Comment by Hellseher** [comment]
Hi, It looks like the same issue with latest update of Fedora 33

```
lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 33 (Thirty Three)
Release:        33
Codename:       ThirtyThree

echo $XDG_SESSION_TYPE
wayland

dnf list --installed | grep wayland
gnome-session-wayland-session.x86_64               3.38.0-1.fc33                          @fedora                                           
libwayland-client.i686                             1.18.0-2.fc33                          @fedora                                           
libwayland-client.x86_64                           1.18.0-2.fc33                          @fedora                                           
libwayland-cursor.x86_64                           1.18.0-2.fc33                          @fedora                                           
libwayland-egl.x86_64                              1.18.0-2.fc33                          @fedora                                           
libwayland-server.i686                             1.18.0-2.fc33                          @fedora                                           
libwayland-server.x86_64                           1.18.0-2.fc33                          @fedora                                           
qt5-qtwayland.x86_64                               5.15.1-1.fc33                          @fedora                                           
wayland-devel.x86_64                               1.18.0-2.fc33                          @fedora                                           
wayland-protocols-devel.noarch                     1.20-2.fc33                            @fedora                                           
xorg-x11-server-Xwayland.x86_64                    1.20.9-1.fc33                          @updates          

alacritty --version
alacritty 0.5.0

RUST_BACKTRACE=full alacritty -vvvv
[wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.
Aborted (core dumped)
```

**Comment by kchibisov** [comment]
>Hi, It looks like the same issue with latest update of Fedora 33

Use the latest alacritty version or the one provided by fedora itself.

**Comment by jsumner** [comment]
@chrisduerr Jolly good idea.  Ran strace and it's showing that it's something around parallels (see bolded below).   Given I had to patch the parallels tools to get it to run on Fedora 33 I'm tempted to hold on more investigation until it's properly supported.  If it's still an issue then we can reopen.

@Hellseher I couldn't get wayland running on parallels - had to default back to X11. More of an indication for me that F33 isn't well supported yet by parallels and that's likely the root of my issue.

Output from strace (at the end):
fstat(9, {st_mode=S_IFREG|0644, st_size=86218, ...}) = 0
mmap(NULL, 86218, PROT_READ, MAP_PRIVATE, 9, 0) = 0x7fc004d5a000
close(9)                                = 0
openat(AT_FDCWD, "/lib64/libEGL.so.1", O_RDONLY|O_CLOEXEC) = 9
read(9, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\200<\0\0\0\0\0\0"..., 832) = 832
fstat(9, {st_mode=S_IFREG|0555, st_size=76632, ...}) = 0
mmap(NULL, 2171560, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 9, 0) = 0x7fc003f58000
mprotect(0x7fc003f69000, 2097152, PROT_NONE) = 0
mmap(0x7fc004169000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 9, 0x11000) = 0x7fc004169000
close(9)                                = 0
mprotect(0x7fc004169000, 4096, PROT_READ) = 0
munmap(0x7fc004d5a000, 86218)           = 0
mincore(0x55ef81c5f000, 4096, [1])      = 0
**readlink("/proc/self/fd/7", "/proc/driver/prl_vtg", 256) = 20
openat(AT_FDCWD, "/dev/dri/card0", O_RDWR) = -1 ENOENT (No such file or directory)**
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 8) = 0
getpid()                                = 3231
gettid()                                = 3231
tgkill(3231, 3231, SIGTERM)             = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGTERM {si_signo=SIGTERM, si_code=SI_TKILL, si_pid=3231, si_uid=1001} ---
+++ killed by SIGTERM +++
zsh: terminated  strace ./target/release/alacritty
