### ISSUE TITLE
Pointer events outside of terminal window on X11

### ISSUE THREAD

**Issue by zsugabubus** [alacritty/alacritty#4484]
I noticed that Alacritty processes consume remarkable CPU time during pointer movement because they are listening for pointer device events (possibly) on the root window.

### System

OS: Linux
Version: `alacritty 0.5.0 (a6681e3a)`
Linux/BSD: X11

### Logs

```
[INFO] glutin event: MainEventsCleared
[INFO] glutin event: RedrawEventsCleared
[INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 110000, tv_nsec: 0 }, requested_resume: None })
[INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(42))), event: Motion { axis: 0, value: -1.0 } }
[INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(42))), event: Motion { axis: 1, value: 1.0 } }
[INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(42))), event: MouseMotion { delta: (-1.0, 1.0) } }
```

**Comment by chrisduerr** [comment]
Just to be clear, when talking about `remarkable CPU time`, how much of your CPU is actually used?

**Comment by zsugabubus** [comment]
One process is around 2%. That is not too much on its own but I can open any number of additional windows that also consume this 2-2% so basically there is no upper limit. For 10 processes it means 15-20%.

**Comment by chrisduerr** [comment]
Tracking issue upstream: https://github.com/rust-windowing/winit/issues/1775.
