### ISSUE TITLE
Certain config options don't work under Wayland/Sway

### ISSUE THREAD

**Issue by angelus2014** [alacritty/alacritty#4487]
### System

OS: Linux
Version: 0.4.3
Linux/BSD: Wayland, Sway

Hello,

I've noticed that under Wayland/Sway, several config options are not being used, colors for example or the cursor style and several others. There is no error message. Is this normal behavior under Wayland/Sway?

---
With regards,

Angelo Machils

**Comment by kchibisov** [comment]
Show your config and also ensure that you've uncommented and aligned everything properly.

**Comment by angelus2014** [comment]
This is the section on the colors:

  # Default colors
  primary:
    background: '0x1c2023'
    foreground: '0xc7ccd1'

  # Normal colors
  normal:
    black:   '0x1c2023'
  #  red:     '0xc7ae95'
    red:     '0xf7eeee'
    green:   '0x95c7ae'
    yellow:  '0xaec795'
    blue:    '0xae95c7'
    magenta: '0xc795ae'
    cyan:    '0x95aec7'
    white:   '0xc7ccd1'

  # Bright colors
  bright:
    black:   '0x747c84'
  #  red:     '0xc7ae95'
    red:     '0xf7eeee'
    green:   '0x95c7ae'
    yellow:  '0xaec795'
    blue:    '0xae95c7'
    magenta: '0xc795ae'
    cyan:    '0x95aec7'
    white:   '0xf3f4f5'

**Comment by kchibisov** [comment]
It should be under `colors`.

e.g.

```yml
colors:
  primary:
    background: '#ff00ff'
```

**Comment by angelus2014** [comment]
If I do that (I already did before), but then I get an error:

[2020-11-26 10:05:23.377135685] [ERROR] Unable to load config "/home/angelo/.config/alacritty/alacritty.yml": Problem with config: did not find
expected <document start> at line 174 column 7

**Comment by kchibisov** [comment]
@angelus2014 then show your entire config on which you get an error. (Just attach a file).

**Comment by angelus2014** [comment]
Here is my config, except for the colors, it is the default one (except some tests I did when I first noticed some/several modifications weren't used). I changed the extension to txt, as I couldn't upload an .xml here.
[alacritty.yml.txt](https://github.com/alacritty/alacritty/files/5601439/alacritty.yml.txt)

**Comment by kchibisov** [comment]
Try this. You've missed some top level sections in some cases.

[alacritty.yml.txt](https://github.com/alacritty/alacritty/files/5601513/alacritty.yml.txt)

**Comment by angelus2014** [comment]
Thank you!
