### ISSUE TITLE
History command was not deleted

### ISSUE THREAD

**Issue by Yellow-King21** [alacritty/alacritty#4488]
Hi i found one issue, if i examine history with keyboard up, sometimes alacritty do not delete previous history command.
Example ... if i have two commands in history cd and ls, i push keyboard up for and terminal show "cd", next i push keyboard up and terminal show "cdls" but the command is "ls" and is valid. 

![Screenshot from 2020-11-26 11-13-50](https://user-images.githubusercontent.com/34798184/100338485-ed8fd580-2fd8-11eb-89a2-50785739a6fd.png)

### System

OS: Linux/Fedora32
alacritty 0.5.0
Linux/BSD: X11/Wayland

**Comment by chrisduerr** [comment]
Which shell?

**Comment by chrisduerr** [comment]
What's your `$TERM`?

**Comment by Yellow-King21** [comment]
xterm-256color

**Comment by chrisduerr** [comment]
Could you show a recording of this issue?

**Comment by Yellow-King21** [comment]
Okey so if you mean some video i send you zip where is record, and if you mean something else like a some of type list or output please send me example of commands.

Thank you for your help.

[2020-11-27 18-52-58.zip](https://github.com/alacritty/alacritty/files/5609131/2020-11-27.18-52-58.zip)

**Comment by chrisduerr** [comment]
Your session seems all kind of messed up. Can you reproduce this with a stock bash configuration?

**Comment by Yellow-King21** [comment]
@chrisduerr I change wayland to xorg and some issue was fixed but this problem was not fixed, i tried to my gnome-terminal and i have same issue so this is not the problem of alacritty but with my config.
I am giving my config bellow so if you could look at it it will be great if not that's okay thanks for help anyway.

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH
export PATH="$PATH:/usr/local/go/bin"

function set-title() {
  if [[ -z "$ORIG" ]]; then
    ORIG=$PS1
  fi
  TITLE="\[\e]2;$*\a\]"
  PS1=${ORIG}${TITLE}
}

export PS1='\e[38;5;222m\u -> \e[38;5;193m[\W]\e[0m: '

**Comment by chrisduerr** [comment]
I'd try changing your PS1, chances are that might be messing things up.
