### ISSUE TITLE
Escape copy-pasted file paths

### ISSUE THREAD

**Issue by WhyNotHugo** [alacritty/alacritty#4489]
### System

OS: Linux
Version: `alacritty 0.6.0 (04cbf767)`
Linux: swaywm

### Logs

When I copy a file and paste it into alacritty, I'd expect the file path to be quoted or escaped. Otherwise the pasted path is not recognised.

E.g.: `/home/hugo/path/to/a \filename\ with\ spaces`.

**Comment by chrisduerr** [comment]
I wouldn't. When I paste text into Alacritty, I would expect it to be pasted the exact same way I stored it into my clipboard.

This is very similar to #1335.

If you want to paste a file path that contains whitespace, just quote it.

**Comment by WhyNotHugo** [comment]
What about having a setting to toggle this behaviour?

**Comment by chrisduerr** [comment]
Settings are there to toggle between multiple useful things. Not to hide one thing that doesn't make sense. That would just bloat up the already massive configuration file.

Though with bracketed paste mode, your application should be fully capable of handling these things context aware. If it requires things to be escaped, it could do that.

**Comment by WhyNotHugo** [comment]
> Though with bracketed paste mode

It took me a while to find out what this is. Seems very useful and to pretty much cover my use case entirely.

But I'm not entirely sure if it's working for me. If I copy-paste multiple lines, zsh's behaviour leads me to think bracketed mode is on, but if I copy-paste a filename with spaces, it doesn't.

How can I confirm if bracketed paste mode is on for alacritty?

**Comment by chrisduerr** [comment]
Zsh enables bracketed paste mode by default.
