### ISSUE TITLE
Mouse not working on WSL v2 when alacritty is installed on Windows

### ISSUE THREAD

**Issue by cdecompilador** [alacritty/alacritty#4490]
When using TUIs like vim/neovim/emacs the scrolling and selecting with the mouse doesn't work at all, I have alacritty installed on windows and I open WSL though `wsl` command, and into it I can use the mouse while with the CMD I can, as far as I know when you enter wsl the CMD gets mouse features that in windows doesn't have. It would be great have support for this.

### System

OS: Windows(installed), WSL2(usage)
Version: 0.6.0 (04cbf76)
Windows: WinPTY

**Comment by chrisduerr** [comment]
>  Windows: WinPTY

Can you test on ConPTY please?

**Comment by cdecompilador** [comment]
Well... Now I'm not sure if im using WinPTY or ConPTY, because at the time I did the issue I used the `alacritty -v` and I just saw `PTY dimensions`, since I'm not in the insiders program I thought I'm using WinPTY but now I'm not sure, can you tell me exactly how to use ConPTY/WinPTY?

**Comment by cdecompilador** [comment]
Oh, now I enabled ConTTY and still it doesn't work

**Comment by chrisduerr** [comment]
It should print in `alacritty -v` if it is using ConPTY or WinPTY. Does it say `ConPTY` for you?

**Comment by cdecompilador** [comment]
It doesn't print it, just PTY

![image](https://user-images.githubusercontent.com/36774000/100414336-c5a47e80-3079-11eb-8736-fe0fe396af52.png)

**Comment by chrisduerr** [comment]
Where did you get your Alacritty version from? Does it print 0.5.0 with `alacritty --version`?

**Comment by cdecompilador** [comment]
No, it prints `alacritty 0.6.0 (04cbf76)`. I installed it via github releases.

**Comment by kchibisov** [comment]
Ah, so it's conpty.

**Comment by cdecompilador** [comment]
I compiled the `0.7.0-dev` and still mouse doesn't work in WSL, It says the same things than in `0.6.0` so its also using ConPTY as @k0nserv said.

**Comment by chrisduerr** [comment]
What `TERM` do you use?

**Comment by cdecompilador** [comment]
xterm-256color

**Comment by chrisduerr** [comment]
I thought Microsoft would have fixed this by now, but it still seems to be an issue: https://github.com/microsoft/terminal/issues/376

**Comment by cdecompilador** [comment]
It's weird because when you are using powershell or cmd at the moment you enter WSL you can do mouse input.

**Comment by wrigleyster** [comment]
If this worked, it seems it has broken again:
OS: Windows 10(installed), WSL2(usage)
Version: 0.12.1 (5fdfd47f)
Windows: ConPTY (or at least I think so, can't find any way to confirm it)

What works and what doesn't:
- So the buffer will scroll, and selecting from the buffer will highlight and copy the selection to the clipboard
- middle click does paste,
but
- clicks and the like are not forwarded to terminal applications that support it, so
  - vim
  - neovim
  - nano (using `nano -m`)
  - tmux

don't receive the mouse events. In plain wsl (ie. not using alacritty) they do work.

```yaml
# alacritty.yml
font:
  normal:
    family: Cousine Nerd Font Mono
    style: Regular
  size: 9.0
selection:
  save_to_clipboard: true
shell:
  program: wsl
    args:
      - --cd ~
```
