### ISSUE TITLE
alacritty 0.6.0 crash on startup (GL context error)

### ISSUE THREAD

**Issue by yvesh** [alacritty/alacritty#4491]
Since version 0.6.0 (actually started with rc1) alacritty crashes on startup on X11 / xorg. Wayland (tested with sway) is working fine.

### System

OS: Linux
Version: 0.6.0
Linux: Gentoo, X11, BSPWM, Picom (doesn't matter though, even with out compositor. Wayland works)

#### alacritty -vvv (error only):

```
[2020-11-26 23:54:39.599585399] [ERROR] [alacritty] Alacritty encountered an unrecoverable error:
Error creating GL context; Received multiple errors. Errors: `[NoAvailablePixelFormat, OsError("Couldn\'t setup vsync: expected interval `1` but got `0`")]`
```

#### glxinfo

```
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: AMD RENOIR (DRM 3.39.0, 5.9.9-gentoo, LLVM 11.0.0) (0x1636)
    Version: 20.3.0
    Accelerated: yes
    Video memory: 512MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
```

Any ideas?

**Comment by chrisduerr** [comment]
And you've confirmed that with 0.5.0 everything works properly?

**Comment by nasser666679** [comment]
> And you've confirmed that with 0.5.0 everything works properly?

**Comment by yvesh** [comment]
@chrisduerr Okay, did some debugging. It's seems to be related to vsync. Running alacritty with `vblank_mode=1 alacritty` works. Not sure if it's a regression in Mesa or Glutin.

**Comment by chrisduerr** [comment]
@yvesh That should be trivial to figure out by downgrading glutin, right? If this is a regression and downgrading Alacritty doesn't work, it can't be Alacritty but has to be Mesa (for example)?

**Comment by bastianplettner** [comment]
Downgrading mesa to 20.2.3 from 20.3.0 seems to work, looks like a problem in mesa

**Comment by chrisduerr** [comment]
@yvesh Can you verify that downgrading mesa works?

**Comment by yvesh** [comment]
@chrisduerr Yes, with Mesa 20.2.3 it runs without issues.

**Comment by kchibisov** [comment]
Then bring it to mesa?

**Comment by aakashhemadri** [comment]
@kchibisov same issue the mesa devs point back to alacritty for not being able to handle vblank_mode set to 0

**Comment by Oreolek** [comment]
Got this crash on 0.9.0
