### ISSUE TITLE
Line in some font not rendering properly in Alacritty?

### ISSUE THREAD

**Issue by brilliant116** [alacritty/alacritty#4498]
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

Version: `alacritty --version` output
`alacritty 0.5.0 (a6681e3a)`

![image](https://user-images.githubusercontent.com/57983070/100494702-076b1d00-317f-11eb-9ecd-da2c5d5dbac9.png)

### Logs

![image](https://user-images.githubusercontent.com/57983070/100494710-25d11880-317f-11eb-84ab-163800702bbd.png)

![image](https://user-images.githubusercontent.com/57983070/100494816-582f4580-3180-11eb-84e2-72acaaca2007.png)

I use the same Roboto Mono font in other terminal emulator, like Konsole, and it didn't occur the phenomenon. THe line not dispplayed properly in Alacritty.  Is it about the line height or something else?

```
~/.bashrc

PS1='\[\033[0;34m\] ┌──(\[\033[1;35m\]\u\[\033[0;34m\])──(\[\033[1;32m\]\w\[\033[0;34m\]) \n\[\033[0;34m\] └> \[\033[1;36m\]\$ \[\033[0m\]'
```

```
~/.config/alacritty/alacritty.yml

window:
  padding:
    x: 2
    y: 0


font:
  normal:
    family: Roboto Mono
    style:  Regular
  bold:
    family: Roboto Mono
    style:  auto
  italic:
    family: Roboto Mono
    style:  auto

  size: 15

  offset:
    x: 0
    y: 0
  
  glyph_offset:
    x: 0
    y: 0

cursor:
  # Cursor style
  #
  # Values for 'style':
  #   - Block
  #   - Underline
  #   - Beam
  style: Block

  # If this is `true`, the cursor will be rendered as a hollow box when the
  # window is not focused.
  unfocused_hollow: true

background_opacity: 1.0

#custom_cursor_colors: true

# Colors (One Light)
colors:
  # Default colors
  primary:
    foreground: '#282c34'
    background: '#ffffff'

  # Normal colors
  normal:
    # NOTE: Use '#131613' for the `black` color if you'd like to see
    # black text on the background.
    black:   '#282c34'
    red:     '#ff4053'
    green:   '#10a778'
    yellow:  '#d19a66'
    blue:    '#3399ff'
    magenta: '#b147d1'
    cyan:    '#00cccc'
    white:   '#abb2bf'

  # Bright colors
  bright:
    black:   '#5c6370'
    red:     '#ff4053'
    green:   '#10a778'
    yellow:  '#d19a66'
    blue:    '#3399ff'
    magenta: '#b147d1'
    cyan:    '#00cccc'
    white:   '#ffffff'

  cursor:
    # black #4a4543
    # green #00b33c
    # blue  #668cff
    cursor: '#668cff'
    text:   '#f7f7f7'
```

**Comment by patrakov** [comment]
Many other terminal emulators had this bug in the past, and solved it by not using any line-drawing characters from the font. They draw the lines by themselves instead.

**Comment by chrisduerr** [comment]
@patrakov is spot on here, this is not a font rendering problem, if anything it's a font problem.
