### ISSUE TITLE
Click (option+click, etc.) to move cursor support?

### ISSUE THREAD

**Issue by jasonhan-vassar** [alacritty/alacritty#4499]
Hi, I'm wondering if click to move cursor was ever considered for alacritty. For example, in iTerm2, option+click at a certain point in a line will bring the cursor there.

If this feature is deliberately left out or unable to be implemented, can someone please explain why? Thanks!

**Comment by chrisduerr** [comment]
This doesn't make much sense for a terminal, since the shell cannot understand mouse events. All that does in iTerm is probably send left arrow keys which is just incredibly backwards.

So no, this will not be added to Alacritty.
