### ISSUE TITLE
Shape of the cursor changes after runing nvim

### ISSUE THREAD

**Issue by Jeudine** [alacritty/alacritty#4505]
In my config. file (`alacritty.yml`) the shape of the cursor is set to `Beam`.

When I open a new terminal emulator the shape is well set.
But after runing `nvim`, the shape of the cursor changes to `Block`.

### System

OS: Linux
Version: alacritty 0.6.0
Linux/BSD: X11

**Comment by chrisduerr** [comment]
Yeah, because neovim doesn't reset the cursor shape when leaving the application. So it's working exactly as planned for neovim.
