### ISSUE TITLE
How to configure Ctrl+; for use in terminal Emacs

### ISSUE THREAD

**Issue by atanasj** [alacritty/alacritty#4507]
How do you create a keybinding to send control+;? I have run the `showkey --scancodes` and press `control+;` I get the follong codes `<CTL-K=VT>`.  I have the following to forward detele:

```yml
  - { key: Semicolon, mods: Control, chars: "<CTL-K=VT>" }
# and also tried this after using xxd -p
  - { key: Semicolon, mods: Control, chars: "^K" }
```

But not sure how to get the forward delete word to work... I've tried to use `xxd -p` at the command line, but this does not show me the hexcode. 

### System

```sh
❯ sw_vers && alacritty --version
ProductName:    Mac OS X
ProductVersion: 10.15.7
BuildVersion:   19H15
alacritty 0.6.0 (04cbf76)
```

### Logs

When I run `alacritty --print-events` I get `^[[3~`. This is the same as forward delete. How can I make it send the `Ctrl+;` key combination. I use this key combination in GUI `Emacs`, so would like to be able to send use it in terminal `Emacs` too. Also worth noting, is that this key combination does not work in any terminal emulator.

Thanks in advance.

**Comment by chrisduerr** [comment]
I'm not sure what you mean? The control should be sent automatically? Or do you want to send a different control character?

`<CTL-K=VT>` is not a valid control character, unless you just want to write that text literally. It's just a shorthand notation specific to Emacs. If you want to send specific chars in Alacritty you'll have to specify the exact escape characters.

**Comment by atanasj** [comment]
Thanks @chrisduerr. Okay, so I did a bit more digging. 

In iTerm outside `tmux` I get this:

```sh
❯ xxd -psd
^K
0b0a
```

In alacrity using tmux I get:

```sh
❯ tmux -V
tmux 3.1c

~
❯ xxd -psd
^[[3~
1b5b337e0a^C
```

Could it be a problem related to tmux?

**Comment by chrisduerr** [comment]
> Could it be a problem related to tmux?

Well, have you tried not running tmux?

**Comment by atanasj** [comment]
I don't think it's `tmux` as I get different keycodes in `alacrity` versus `iTerm` and `terminal.app` (see below):

```sh
# iterm running tmux
❯ xxd -psd
^K
0b0a^C


# alacritty running tmux
❯ xxd -psd
^[[3~
1b5b337e0a^C

```

Any thoughts why this could occur?

**Comment by chrisduerr** [comment]
> Any thoughts why this could occur?

Have you tried not running `tmux`?

**Comment by atanasj** [comment]
Yes. Same result.

**Comment by chrisduerr** [comment]
Is that with an empty config and the latest Alacritty version?

**Comment by atanasj** [comment]
Okay, so I figured it out. I had a config using `hammerspoon` which was some keys in most apps. There was an exception to `iTerm` and `Terminal.app` but not `Alacritty`. This has been added and the issue is resolved. Apologies for the wild goose chase! 😨
