### ISSUE TITLE
Ctrl+Shift+Tab not working

### ISSUE THREAD

**Issue by thales-maciel** [alacritty/alacritty#4508]
### System

OS: Linux
Version: `0.6.0-dev (44a6dba)`
Linux/BSD: X11/, picom and i3wm

### Problem
I have a mapping for Ctrl+Shift+Tab in some terminal programs. If I'm using kitty they all work, but in alacritty they don't.

I read something about escape characters in the Keyboard mappings wiki page, but It wasn't clear about how to get the hexadecimal or unicode characters I want. I believe It's assumed to be known by the users, but I lack this knowledge.

**Comment by chrisduerr** [comment]
Where exactly have you mapped them? Also what do you expect to happen with Ctrl+Shift+Tab beyond just Ctrl+Tab. Those should usually send the same characters.

**Comment by thales-maciel** [comment]
I mapped In neovim, It currently works in kitty.
I'm sorry to bother with this, I didn't know that `Those should usually send the same characters`.

**Comment by chrisduerr** [comment]
Does just pressing ctrl+tab work in Kitty? It should trigger the binding too (in both Alacritty and Kitty).

**Comment by thales-maciel** [comment]
Ctrl+Tab is working on both, but I just found out that the Ctrl+Shift+Tab in kitty was indeed sending Shift+Tab, while Alacritty isn't sending anything at all unless I map It in config (so I guess I'll do that)

**Comment by chrisduerr** [comment]
I tested it in Kitty and I'm pretty sure it's sending Ctrl+Tab and not Shift+Tab. But either way it shouldn't be a problem that Alacritty doesn't have Ctrl+Shift+Tab mapped to anything, because there's no point in using it for anything other than custom bindings (and you should be able to map it to custom stuff just fine).
