### ISSUE TITLE
Subract key binding causing warning - alacritty 0.6.0

### ISSUE THREAD

**Issue by jabedude** [alacritty/alacritty#4509]
### System

OS: Linux - Ubuntu 18.04
Version: `alacritty 0.6.0` - installed via `cargo install`
Linux/BSD: X11/KDE Plasma

### Logs

[2020-12-01 21:06:54.675416113] [ERROR] [alacritty_config] Problem with config: unknown variant `Subtract`, expected one of `Key1`, `Key2`, `Key3`, `Key4`, `Key5`, `Key6`, `Key7`, `Key8`, `Key9`, `Key0`, `A`, `B`, `C`, `D`, `E`, `F`, `G`,
`H`, `I`, `J`, `K`, `L`, `M`, `N`, `O`, `P`, `Q`, `R`, `S`, `T`, `U`, `V`, `W`, `X`, `Y`, `Z`, `Escape`, `F1`, `F2`, `F3`, `F4`, `F5`, `F6`, `F7`, `F8`, `F9`, `F10`, `F11`, `F12`, `F13`, `F14`, `F15`, `F16`, `F17`, `F18`, `F19`, `F20`, `F21`, `F22`, `F23`, `F24`, `Snapshot`, `Scroll`, `Pause`, `Insert`, `Home`, `Delete`, `End`, `PageDown`, `PageUp`, `Left`, `Up`, `Right`, `Down`, `Back`, `Return`, `Space`, `Compose`, `Caret`, `Numlock`, `Numpad0`, `Numpad1`, `Numpad2`, `Numpad3`, `Numpad4`, `Numpad5`, `Numpad6`, `Numpad7`, `Numpad8`, `Numpad9`, `NumpadAdd`, `NumpadDivide`, `NumpadDecimal`, `NumpadComma`, `NumpadEnter`, `NumpadEquals`, `NumpadMultiply`, `NumpadSubtract`, `AbntC1`, `AbntC2`, `Apostrophe`, `Apps`, `Asterisk`, `At`, `Ax`, `Backslash`, `Calculator`, `Capital`, `Colon`, `Comma`, `Convert`, `Equals`, `Grave`, `Kana`, `Kanji`, `LAlt`, `LBracket`, `LControl`, `LShift`, `LWin`, `Mail`, `MediaSelect`, `MediaStop`, `Minus`, `Mute`, `MyComputer`, `NavigateForward`, `NavigateBackward`, `NextTrack`, `NoConvert`, `OEM102`, `Period`, `PlayPause`, `Plus`, `Power`, `PrevTrack`, `RAlt`, `RBracket`, `RControl`, `RShift`, `RWin`, `Semicolon`, `Slash`, `Sleep`, `Stop`, `Sysrq`, `Tab`, `Underline`, `Unlabeled`, `VolumeDown`, `VolumeUp`, `Wake`, `WebBack`, `WebFavorites`, `WebForward`, `WebHome`, `WebRefresh`, `WebSearch`, `WebStop`, `Yen`, `Copy`, `Paste`, `Cut`; ignoring binding

I have the following entries in my key bindings in my alacritty config:
```
key_bindings:
  - { key: V,        mods: Control|Shift,    action: Paste               }
  - { key: C,        mods: Control|Shift,    action: Copy                }
  - { key: Paste,                   action: Paste                        }
  - { key: Copy,                    action: Copy                         }
  - { key: Q,        mods: Command, action: Quit                         }
  - { key: W,        mods: Command, action: Quit                         }
  - { key: Insert,   mods: Shift,   action: PasteSelection               }
  - { key: Key0,     mods: Control, action: ResetFontSize                }
  - { key: Equals,   mods: Control, action: IncreaseFontSize             }
  - { key: Subtract, mods: Control, action: DecreaseFontSize             }
```

The warning log goes away if I delete the `Subtract` key binding. Was this deprecated?

**Comment by chrisduerr** [comment]
The binding is now called `NumpadSubtract`.

**Comment by jabedude** [comment]
Thanks @chrisduerr
