### ISSUE TITLE
Question about expected behavior of font offset

### ISSUE THREAD

**Issue by mkrasnitski** [alacritty/alacritty#4510]
I've been playing around with the cava visualizer in alacritty, and found that when using colored box drawing characters combined with a font y-offset > 0, that the bars it draws become noncontiguous, and that this behavior does not occur in other terminals like urxvt. I've detailed the issue over in the cava repo [here](https://github.com/karlstav/cava/issues/393), but was wondering, is this intended behavior, or something that maybe could be overridden for specific characters?

### System

OS: Linux
Version: 0.6.0 (04cbf767)
Linux/BSD: X11, i3 + picom

**Comment by chrisduerr** [comment]
Yes, if you change the glyph metrics, all glyph metrics change. That's exactly how it's supposed to work.

**Comment by mkrasnitski** [comment]
Thanks for the quick reply and confirmation.
