### ISSUE TITLE
Right-Click to insert commands dosn't work

### ISSUE THREAD

**Issue by RainerMathey** [alacritty/alacritty#4512]
Right-Click to insert commands dosn't work;
when i right-click in Alacritty there is now menu showing up to do something.

### System

OS: Manjaro 64-bit
Version: alacritty 0.6.0 (04cbf767)

**Comment by chrisduerr** [comment]
That's exactly what's supposed to happen on right click.

**Comment by RainerMathey** [comment]
when i right-click in other terminals i can insert from clipboard
