### ISSUE TITLE
Question: Use correct font symbols

### ISSUE THREAD

**Issue by rrobertobt** [alacritty/alacritty#4514]
I use powerlevel10k as my zsh theme/prompt and the style I selected uses some special symbols, but Alacritty doesn't seem to display the correct ones. I tried on Konsole (and vte) and it does display the correct symbols it should, here are some screenshots.

Alacritty, shows "dots" blocks:
![Screenshot_20201203_202036](https://user-images.githubusercontent.com/44622828/101113725-9cb64900-35a5-11eb-9313-34f8d133e839.png)
Konsole, shows full color blocks:
![Screenshot_20201203_202116](https://user-images.githubusercontent.com/44622828/101113819-d1c29b80-35a5-11eb-8824-c248fd295e1d.png)

I'm currently using a Nerd Font

**Comment by chrisduerr** [comment]
It's the other way around actually. Alacritty displays the "correct" symbols from your font while Konsole/VTE draw these characters themselves ignoring your font completely.

There's currently no plans to do the same in Alacritty, especially not for these characters.
