### ISSUE TITLE
xterm emulation dynamic titles aren't working

### ISSUE THREAD

**Issue by rotten** [alacritty/alacritty#4516]
Using TERM=xterm, and explicitly setting `dynamic_title:  true` I am still unable to change the window title using the standard escape codes.  That feature is important to me.  Since I'm new to Alacritty, I'm not sure if I still have some other tweak I need to do to get them to work, or if this feature is actually broken in the latest release.  I don't seen an obvious open issue on it.

### System

OS: Linux - Ubuntu 20.04.1
Version: 0.6.0
Linux/BSD: X11/Gnome 3.36.3
Windows: PTY

**Comment by chrisduerr** [comment]
Do you manually set Alacritty's title using the command line flag or config option?

**Comment by rotten** [comment]
No, I left that at the default.  I'm trying to change the title like I would in an xterm, with the `[^[];new title^G` syntax.

**Comment by chrisduerr** [comment]
Which escape specifically are you using? `[^[];new title^G` is not valid.

**Comment by rotten** [comment]
This bash function works fine in xterm's, but does not work in Alacritty:
```
tf() { echo "^[];${HOSTNAME} -- ${1}^G"; tail -100f ${1}; }
```
Also setting my prompt to also update the title bar whenever it renders works fine in an xterm, but not in Alacritty:
```
export PS1='\[^[];${USER}@${HOSTNAME}:${PWD}^G${Red}\]${USER}\[${White}\]@\[${Green}\]${HOSTNAME}\[${Cyan}\] ${PWD##${PWD%/*/*/*}/}\[${Yellow}\] $ \[${White}\] '
```
The Red, White, etc, in that example, I define separately - those appear to work fine in Alacrity.

```
export Black='^[[0;30m'
export Red='^[[0;31m'
export Green='^[[0;32m'
export Yellow='^[[0;33m'
export Blue='^[[0;34m'
export Magenta='^[[0;35m'
export Cyan='^[[0;36m'
export White='^[[0;37m'
export DefaultColor='^[[0;39m'
```
```
```
echo "${Cyan}hello${White} there"
```

Note that the little `^` symbols are not really in the string, those are indicating control+characters and the "^[" is really the escape key.

I'm happy to use a different escape sequence if alacritty terminals require something else to update the window title on the fly.  I don't think setting the title is specifically defined in the termcap, but I could be wrong there - it may be an xterm thing that other terminal emulators have chosen to copy by convention.  I've just been using it for many years so I don't recall its roots.

**Comment by chrisduerr** [comment]
Try `echo -e "\e]2;new Title\e\\"`, that's the proper escape. `\e];title\a` is used to set the icon name, not the title.

**Comment by rotten** [comment]
Adding that "2" before the semicolon did the trick.   It does not appear to break the xterm title refresh either, so I can switch this for my use cases and still have backward compatibility with other terminal emulators.  Thanks for figuring that out!  That was very helpful.
