### ISSUE TITLE
Font scaling in Linux

### ISSUE THREAD

**Issue by o0-o** [alacritty/alacritty#4519]
I use Alacritty on both macOS and Linux. I am able to share my config between these two with exception of font size. On macOS I use 13.5 which is roughly equivalent to 11 in Arch (monitor is shared via kvm switch).

From what I understand, Alacritty references fontconfig for it's text rendering in Linux and ignores X11 dpi/scaling parameters. However, in my testing, I am not able to effect scaling at all. I have attempted to change both dpi and pixelsize parameters in custom fontconfig in '/etc/fonts/conf.d/` but this has no effect. I tried both restarting Alacritty and fully exiting and restarting the window manager.

Ideally, I'd like to tweak fontconfig (or something else potentially) so that Alacritty renders point-to-pixel roughly the same as macOS.

### System

OS: Arch Linux
Version: alacritty 0.6.0 (04cbf767)
X11 AwesomeWM

Attached are my alacritty.yml and 2 font conf files. In the font conf files, I tried several different values.

[alacritty-font-scaling-linux-issue.zip](https://github.com/alacritty/alacritty/files/5646634/alacritty-font-scaling-linux-issue.zip)

**Comment by kchibisov** [comment]
We take DPI from X11, try `WINIT_X11_SCALE_FACTOR=1 alacritty`.

**Comment by o0-o** [comment]
> We take DPI from X11, try `WINIT_X11_SCALE_FACTOR=1 alacritty`.

Thanks! A value of 1 doesn't solve my problem, but that parameter does scale it fractionally so .8 is looking very close.

I have not spent much time manually configuring x11. I assume setting this as an environmental variable might have adverse affects on other applications. How should I configure it persistently to only affect Alacritty?

**Comment by kchibisov** [comment]
You can set it in a config file's env section in alacritty.
