### ISSUE TITLE
[Expose API] Processor Event Loop

### ISSUE THREAD

**Issue by ShlomiRex** [alacritty/alacritty#4520]
What to expose to `alacritty_terminal` crate:

alacritty/src/event.rs:Processor

```
/// The event processor.
///
/// Stores some state from received events and dispatches actions when they are
/// triggered.
pub struct Processor<N> {
    notifier: N,
    mouse: Mouse,
    received_count: usize,
    suppress_chars: bool,
    clipboard: Clipboard,
    modifiers: ModifiersState,
    config: Config,
    message_buffer: MessageBuffer,
    display: Display,
    font_size: Size,
    event_queue: Vec<GlutinEvent<'static, Event>>,
    search_state: SearchState,
    cli_options: CLIOptions,
}
```

Reason: For one to use the terminal one must impliment event loop. I want to develop GUI for alacritty. I must develop event loop simillar to Processor. Is that really necessery? I just want to give window_id and some graphics context to alacritty and it will work that way. Then I can interact with the terminal with pty module.

Maybe i'm approaching this the wrong way.

After I created alacritty terminal and pty I want to integrate it into GUI. How would one go about doing such thing?

Then I viewed the main.rs in alacritty which impliments high level event loops. Why isn't it useable to alacritty_terminal?

**Comment by kchibisov** [comment]
alacritty depends on alacritty_terminal, not the other way around. Processor is tight to winit and gui's in general, and it's not something that could be in alacritty_terminal. Also, you could have completely different event loop compared to Processor, and also could use something other than winit, like gtk. So in general, I'd suggest to implement your own event loop or start from alacritty codebase and replace stuff you don't want to.

**Comment by ShlomiRex** [comment]
> alacritty depends on alacritty_terminal, not the other way around. Processor is tight to winit and gui's in general, and it's not something that could be in alacritty_terminal. Also, you could have completely different event loop compared to Processor, and also could use something other than winit, like gtk. So in general, I'd suggest to implement your own event loop or start from alacritty codebase and replace stuff you don't want to.

Hmmm ok. I can agree on that. I will wait for more answers.

**Comment by chrisduerr** [comment]
There's no need. If you implement a separate GUI, you'll want some way to handle events in there anyways. The abstraction of `alacritty_terminal` make sense, there's no event loops in there that you would want to expose to the outside.

So unless you have an actual concrete problem with that, I see no reason to change things. If you want to reimplement Alacritty's UI, just hook your UI rendering code up to `alacritty_terminal` just like `alacritty` is doing.
