### ISSUE TITLE
[WIP] aarch64/Apple Silicon/M1 support

### ISSUE THREAD

**Issue by Byron** [alacritty/alacritty#4530]
Currently Alacritty (latest master) doesn't compile on Apple Silicon, this ticket attempts to collect all issues and their solutions or tracking tickets.

### System

OS: macOS aarch64
Version: master

### Issues to resolve

When building, be sure to not build through `tmux` (even if it's an ARM application), as this seems to switch to INTEL toolchains somehow which often makes running build commands fail. What works for me is vanilla iTerm.

* [ ] upgrade to unreleased `winit` 0.24 via new version of `glutin` ([winit tracking ticket](https://github.com/rust-windowing/winit/issues/1789), _with patches to make it work locally_)
* [ ] Fix build errors coming from latest `glutin` version with breaking changes
* [ ] Apply the patch (see details) to build with the latest `glutin` crate (at least to match what I have locally which may not be what `glutin` ends up looking like.

With the fixes above, `alacritty` builds on Apple Silicon.

```
➜  alacritty git:(master) ✗ file /Applications/Alacritty.app/Contents/MacOS/alacritty
/Applications/Alacritty.app/Contents/MacOS/alacritty: Mach-O 64-bit executable arm64
```

Now that `alacritty` is an ARM app, there is no problems in running build commands anymore either.

<details>

This is verified to apply on  9e71002e40d5487c6fa2571a3a3c4f5c8f679334 

```diff
diff --git a/alacritty/src/event.rs b/alacritty/src/event.rs
index 8ecf6f0..0048e9f 100644
--- a/alacritty/src/event.rs
+++ b/alacritty/src/event.rs
@@ -19,7 +19,7 @@ use std::time::{Duration, Instant};
 use glutin::dpi::PhysicalSize;
 use glutin::event::{ElementState, Event as GlutinEvent, ModifiersState, MouseButton, WindowEvent};
 use glutin::event_loop::{ControlFlow, EventLoop, EventLoopProxy, EventLoopWindowTarget};
-use glutin::platform::desktop::EventLoopExtDesktop;
+use glutin::platform::desktop::EventLoopExtRunReturn;
 #[cfg(all(feature = "wayland", not(any(target_os = "macos", windows))))]
 use glutin::platform::unix::EventLoopWindowTargetExtUnix;
 use log::info;
diff --git a/alacritty/src/window.rs b/alacritty/src/window.rs
index 953fffd..093c465 100644
--- a/alacritty/src/window.rs
+++ b/alacritty/src/window.rs
@@ -27,7 +27,8 @@ use std::fmt::{self, Display, Formatter};
 use glutin::dpi::{PhysicalPosition, PhysicalSize};
 use glutin::event_loop::EventLoop;
 #[cfg(target_os = "macos")]
-use glutin::platform::macos::{RequestUserAttentionType, WindowBuilderExtMacOS, WindowExtMacOS};
+use glutin::platform::macos::{WindowBuilderExtMacOS, WindowExtMacOS};
+use glutin::window::UserAttentionType;
 #[cfg(windows)]
 use glutin::platform::windows::IconExtWindows;
 use glutin::window::{CursorIcon, Fullscreen, Window as GlutinWindow, WindowBuilder, WindowId};
@@ -339,7 +340,7 @@ impl Window {
             return;
         }
 
-        self.window().request_user_attention(RequestUserAttentionType::Critical);
+        self.window().request_user_attention(Some(UserAttentionType::Critical));
     }
 
     #[cfg(any(windows, not(any(feature = "x11", target_os = "macos"))))]
```

**Comment by bouk** [comment]
For those following this, I made a PR to build a universal release binary: https://github.com/alacritty/alacritty/pull/4683
