### ISSUE TITLE
Problem with font configuration

### ISSUE THREAD

**Issue by venqm** [alacritty/alacritty#4532]
Hi everyone, I'm on Linux,
I assume that my font configuration isn't quite works. The problem started when I changed `alacritty.yml` for the first time.
I changed the font to `Inconsolata` and got the black screen out of it. Then, I decided to change it back to monospace and
now I gained ability to output the `Hello World!` into neofetch 😅 

![2020-12-07_10-40](https://user-images.githubusercontent.com/71521628/101322754-76233700-385f-11eb-854d-414c9d892301.png)

So, how am I supposed to change the font ? 

Please, help.

**Comment by chrisduerr** [comment]
If a configuration file isn't working for you, please share it.

**Comment by venqm** [comment]
> ati

**Comment by venqm** [comment]
> If a configuration file isn't working for you, please share it.

This is my config ---> https://justpaste.it/7frn3

**Comment by chrisduerr** [comment]
It's missing the `font` key.

**Comment by venqm** [comment]
> It's missing the `font` key.

yeah I just got it, but anyways it doesn't work even with the font key

**Comment by chrisduerr** [comment]
If something isn't working, **please share the configuration file that isn't working**.

**Comment by venqm** [comment]
> If something isn't working, **please share the configuration file that isn't working**.

https://justpaste.it/474pj

**Comment by kchibisov** [comment]
```yaml
Font:
normal:  
  family: Noto Sans
  style: Regular
  size: 9.0
```

It should be
```yaml
font:
  normal:
    family: Noto Sans
    style: Regular
  size: 9.0
```
Also, Noto Sans doesn't look like a monospace font, try using `Noto Sans Mono`.

**Comment by venqm** [comment]
> ```yaml
> Font:
> normal:  
>   family: Noto Sans
>   style: Regular
>   size: 9.0
> ```
> 
> It should be
> 
> ```yaml
> font:
>   normal:
>     family: Noto Sans
>     style: Regular
>   size: 9.0
> ```
> 
> Also, Noto Sans doesn't look like a monospace font, try using `Noto Sans Mono`.

Thank you so much, you nailed it ;)
