### ISSUE TITLE
Configuration `import` behavior attempts to load not relative to $HOME

### ISSUE THREAD

**Issue by cassava** [alacritty/alacritty#4533]
The new ability to import configuration files is great and would solve a lot of my problems; unfortunately it does not entirely work as described in the repo configuration file:

```toml
# All imports must either be absolute paths starting with `/`, or paths relative
# to the user's home directory starting with `~/`.
#import:
#  - /path/to/alacritty.yml
```

First of all, it's not obvious from this description that I have to use `.config/alacritty/include.yml` instead of `~/.config/alacritty/include.yml`. The first example uses `/` which needs to be present, the second example uses `~/` which should not be present.

Secondly, when I launch alacritty from the file browser, something like this gets executed:
```sh
exo-open --working-directory "$PWD" --launch TerminalEmulator
```

Which then leads to alacritty looking for `$PWD/.config/alacritty/include.yml`, which it does not find if `$PWD != $HOME` and complaining that it cannot find it:

```
[2020-12-07 19:50:25.871197181] [ERROR] [alacritty_config] Unable to import config ".config/alacritty/theme.yml": Unable to locate config file
[2020-12-07 19:50:26.054269538] [ERROR] [alacritty] Unable to canonicalize config path ".config/alacritty/theme.yml": No such file or directory (os error 2)
```

### System

OS: Linux with X11 and picom
Version: alacritty 0.6.0 (04cbf767)

**Comment by chrisduerr** [comment]
The documentation is **very** clear on this. All paths must start with `/` or `~/`.

**Comment by kchibisov** [comment]
Also, since you're on 0.6.0, `~/` won't work, since it's not a part of `0.6.0` release, so in your case everything should start with `/`.

**Comment by cassava** [comment]
> Also, since you're on 0.6.0, `~/` won't work, since it's not a part of `0.6.0` release, so in your case everything should start with `/`.

This is good to know! I saw in the release notes that `import` was supported in 0.6.0 and checked the `alacritty.yml` file and read the configuration documentation.

Lesson learned: Check out the tagged version first then look at `alacritty.yml`.

**Comment by chrisduerr** [comment]
> Lesson learned: Check out the tagged version first then look at alacritty.yml.

The yaml is also always attached to the GitHub release for this exact reason.
