### ISSUE TITLE
Can't type '|' or '$' characters (macOS, Scandinavian keyboard layout, no numpad)

### ISSUE THREAD

**Issue by Stakker** [alacritty/alacritty#4539]
Alt+7 should produce a pipe, but instead it seems to go to beginning of line.
Alt+4 should produce a dollar sign, but instead it seems to go to end of word.

Maybe it's a case of some keybindings that I'm too dumb to be aware of, but I can't figure out what. Nothing in alacritty.yml and they work fine in Terminal in the same environment.

### System

OS: macOS
alacritty 0.6.0 (04cbf76)

**Comment by chrisduerr** [comment]
Have you tried setting `alt_send_esc: false` in the config?

**Comment by Stakker** [comment]
Ahh, that fixed it, thank you!

To me it seems that this is a weird default option, because pipe and dollar are pretty essential characters, but maybe there are reasons for it that I'm not aware of. I'll leave it for you to decide if this issue is closed or not :-)

**Comment by chrisduerr** [comment]
> To me it seems that this is a weird default option

Sending alt to the terminal is not weird at all for a terminal emulator I'd say. Otherwise it would be impossible for people to use alt in applications when running an operating system that has a reasonable alt key.
