### ISSUE TITLE
Can't find terminal definition for alacritty despite it being present.

### ISSUE THREAD

**Issue by BLucky-gh** [alacritty/alacritty#4541]
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

OS: macOS Big Sur (just updated a minute ago)
Version: alacritty 0.6.0 (04cbf76)

right after the Big Sur update alacritty's terminfo seems to not work on MacOS or something since now whenever I open alacritty I get 
``.zshrc:14: can't find terminal definition for alacritty`` as the first line of output, and I get artifacts like double letters, missing some colors and stuff as I usually do when terminal is not defined as alacritty. if I ``exec zsh`` everything seems to return to normal but programs like ``more`` still give the warning message: ``WARNING: terminal is not fully functional``

``infocmp alacritty`` does not return any errors and still shows normal output. I'm not sure if I have to report this here or on zsh's Github or on tmux or on Mac forums but I decided to ask here first.

**Comment by chrisduerr** [comment]
That doesn't really have anything to do with Alacritty. Your system is just broken because of something you did, I'd assume that neither zsh nor Alacritty have anything to do with it here. For me on Big Sur everything also works perfectly fine.

I'd recommend reinstalling the terminfo and making sure that `echo "-$TERM-"` returns a reasonable value.

**Comment by BLucky-gh** [comment]
Thanks. In that case it's probably the big sur update breaking file perms. thanks for the quick reply

**Comment by BLucky-gh** [comment]
I didn't find the specific reason but the general cause was the Big Sur update changing a lot of things in the system. I needed to format my drive for unrelated reasons and then I switched to kitty anyways so I have no idea how to fix this, though I can confirm that a factory reset *did* fix the issue.
