### ISSUE TITLE
[Docs] Add libxcb-composite0-dev for Ubuntu

### ISSUE THREAD

**Issue by sauravkhdoolia** [alacritty/alacritty#4542]
### System

OS: Ubuntu 20

I needed lxcb-shape and lxcb-xfixes, Which are not available as pkgs(they're but i dont know how to find them).

Please add "libxcb-composite0-dev" to the requirements for building Alacritty on Ubuntu.

This pkg provides lxcb-* required for installation and sorted my errors out.

**Comment by chrisduerr** [comment]
If there are missing dependencies, please feel free to send a pull request to add them. However `xfixes` is certainly available as packages which is documented in the INSTALL.md file:

https://github.com/alacritty/alacritty/blob/master/INSTALL.md#debianubuntu

So please make sure you've got all of these installed before adding any additional dependencies.

**Comment by sauravkhdoolia** [comment]
Yeah, I did see that. But it required '''lxcb-shapes''' too... I didn't have that.

So, Installing '''libxcb-composite0-dev''' provided that. 

I'll get a PR up when I can.

**Comment by driverCzn** [comment]
> Yeah, I did see that. But it required `lxcb-shapes` too... I didn't have that.
> 
> So, Installing `libxcb-composite0-dev` provided that.
> 
> I'll get a PR up when I can.

![image](https://user-images.githubusercontent.com/16717904/102879840-66be0380-4485-11eb-9517-a533ebe5e699.png)

I think install `libxcb-xfixes0-dev` is enough.
