### ISSUE TITLE
background_opasity stopped working after hibernation - manjaro KDE

### ISSUE THREAD

**Issue by SergejGorev** [alacritty/alacritty#4543]
background_opacity has strange behaviour. It doesnt make background transperent, but rather makes background darker.

### System

OS: Linux/Manjaro
Version: alacritty 0.6.0 (04cbf767)
Linux/BSD: X11, KDE

**Comment by chrisduerr** [comment]
Does rebooting fix the problem and can you reproduce it by hibernating again afterwards?

**Comment by SergejGorev** [comment]
Rebooting doesn't fix the problem. It kind of broke it permanently. I am trying to understand where and how to fix it.

**Comment by chrisduerr** [comment]
That sounds a lot like a problem with your system. Your compositor might not be running anymore, that's usually what gives applications transparency. Testing a different app might be worth a shot to see if others can still show transparency (though make sure it's not fake transparency).

**Comment by SergejGorev** [comment]
Thank you for fast reply. I tested opacity with other apps, and having same issue there too. Yea my compasitor is probably gone missing... Ok thank you again. And sorry for inconvinience.

**Comment by SergejGorev** [comment]
Just in case somebody stumbels accross the same issue. KDE/Manjaro, KDE had a bug. I had to reanable compositor in the settings menue. So it was in fact a global issue.
