### ISSUE TITLE
SSH colors and inputs like backspace don't work

### ISSUE THREAD

**Issue by StudioChew** [alacritty/alacritty#4545]
### System

OS: Linux
Version: alacritty 0.6.0 (04cbf767)
Linux/BSD: X11, i3wm, picom

Basically, when I use ssh to connect to a server, it does connect, there are no crashes or anything, *but* when I press Backspace, it gives me a space. Colors do not work. It's all black and white. When I run `tmux`, it says `open terminal failed: missing or unsuitable terminal: alacritty` and just closes. Not sure if this is an ssh problem or an alacritty problem, but everything works correctly on urxvt. I might be the only one with this issue because I don't see people complaining about it.

**Comment by chrisduerr** [comment]
You need to install the `alacritty` terminfo on the remote host. If you ssh into a machine with the local `TERM` set to `alacritty` while the remote machine doesn't have the corresponding terminfo installed, application have no way to figure out the terminal capabilities and thus raise errors.

**Comment by SpaceShaman** [comment]
I had an identical problem and it helped to set the `TERM` environment variable on the client machine from `alacritty` to `xterm-256color`
```bash
set TERM xterm-256color
```
