### ISSUE TITLE
Can't change ć to ç only in alacritty

### ISSUE THREAD

**Issue by akachida** [alacritty/alacritty#4549]
I have 2 terminals running zsh and only with alacritty the ç is not working properly, always showing ć. Any other application is working fine.
I've already changed the `/etc/environment` to use `GTK_IM_MODULE=cedilla` and `QT_IM_MODULE=cedilla` and the `/usr/share/X11/locale/en_US.UTF-8/Compose` I replaced everything that has `ć` with `ç`, and still not working.

`setxkbmap -print -query` output:
```
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
	xkb_types     { include "complete"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pc+us(intl)+us:2+inet(evdev)+level3(ralt_switch)"	};
	xkb_geometry  { include "pc(pc105)"	};
};
rules:      evdev
model:      pc105
layout:     us,us
variant:    intl,
options:    lv3:ralt_switch
```

`localectl` output:
```
   System Locale: LANG=en_US.UTF-8
       VC Keymap: us-acentos
      X11 Layout: us
     X11 Variant: intl
```

`/etc/locale.conf`
```
LANG="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

### System

OS: Manjaro 20.2 (Gnome)
Version: 0.6.0 (04cbf767)

**Comment by chrisduerr** [comment]
Is it using the correct IME for you? Because configuring it for GTK and QT is pointless when running Alacritty.

**Comment by kchibisov** [comment]
I think it's not about IME but rather a compose keys. Could you setup things via your `.XCompose` file?

**Comment by akachida** [comment]
Thanks for the reply guys. I never tought about the `.XCompose` file, so I made one with the following:
```
include "%L"

<dead_cedilla> <c> : "ç"
<Multi_key> <comma> <c> : "ç"
<Multi_key> <c> <comma> : "ç"
<Multi_key> <cedilla> <c> : "ç"
<dead_acute> <c> : "ç"
<Multi_key> <acute> <c> : "ç"
<Multi_key> <apostrophe> <c> : "ç"
<Multi_key> <c> <apostrophe> : "ç"
```
And it worked. Don't know about that, but, why changing the `/usr/share/X11/locale/en_US.UTF-8/Compose` doesn't seem to work?
The `include "%L"` was suposed to include this file as default key bindings.

**Comment by kchibisov** [comment]
idk, but I wouldn't ever suggest to edit systems configuration, since it could be more than what you could think of.

**Comment by akachida** [comment]
Yes, it is, as you can see in my thread, everything has en_US.UTF-8

**Comment by chrisduerr** [comment]
The thing is that `localectl` prints the system locale and catting `/etc/locale.conf` just prints the theoretical locale configuration, not the actual one.

So you should run `locale` in Alacritty to see what actual locale is being used.

**Comment by akachida** [comment]
Hmm I understand, but the locale.conf was supose to be the main locale configuration file right?
But anyway, I ran the `locale` command and the output was this:
```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```
It's really weird that didn't worked
