### ISSUE TITLE
Font way smaller on second screen

### ISSUE THREAD

**Issue by ivangjxyz** [alacritty/alacritty#4551]
Somehow, if I start alacritty on my second screen, the font size is very small, and that does not happen on my main screen. Both screens have the same resolution, and everything works great, except alacritty. 

The weirdest part is that... if I move that window to my main screen... suddenly it changes to normal. And the same reverse thing happens, if I bring an alacritty window to my secondary screen... it resizes to the small font. 

Using Arch Linux with KDE Plasma and Khronkite, on X.
alacritty 0.6.0 (04cbf767)

**Comment by chrisduerr** [comment]
Your font size will be scaled by DPI automatically. If you do not want that, either set your `Xft.dpi` or export `WINIT_X11_SCALE_FACTOR=1`.

**Comment by ivangjxyz** [comment]
Thanks! 
For anyone who wants a quick way to solve this, you could go to your personal `alacritty.yml` file and on the `env:` section, add: 
```
WINIT_X11_SCALE_FACTOR: '1'
```

So, if you copied [the github `alacritty.yml` file](https://github.com/alacritty/alacritty/blob/master/alacritty.yml), it could be looking something like this: 
```
env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  # TERM: alacritty
  WINIT_X11_SCALE_FACTOR: '1'
```
