### ISSUE TITLE
ncurses/curses not redrawing

### ISSUE THREAD

**Issue by maksmeshkov** [alacritty/alacritty#4560]
### System

OS: Gentoo Linux
Version: `0.6.0` compiled with X support, fresh install without any configuration
Linux: X11, i3
$TERM: alacritty
### Issue

Hi,

Ncurses interfaces don't redraw on some programs after i resize them. So i have pinned down `alacritty` (also `termite` has the same issue) to be the cause of it, as `rxvt-unicode` draws ncurses fine.

Ncurses programs that appear to work: `vim, nano, tmux, mutt?, alsamixer, top?`.
Ncurses programs that don't work: `mocp, ranger (although it uses python curses module), menuconfig, htop`.

What did not help:
Recompiled sys-libs/ncurses with unicode, threads, gpm, cxx, tinfo support

Here is the example of mocp not redrawing after I expand window (<c-r> did not work too).
![image](https://user-images.githubusercontent.com/47359245/101960093-b4ca4000-3c17-11eb-9884-71a2f1996c71.png)
and this is if I shrink window:
![image](https://user-images.githubusercontent.com/47359245/101960104-bb58b780-3c17-11eb-8553-d05344d31556.png)

same problem with ranger (:refresh did not do anything):
https://user-images.githubusercontent.com/47359245/101955755-6f097980-3c0f-11eb-9f0f-1c7da6c53687.png
https://user-images.githubusercontent.com/47359245/101955773-7a5ca500-3c0f-11eb-8e28-cd13360f76f0.png =100x

works fine with urxvt:
https://user-images.githubusercontent.com/47359245/101955834-982a0a00-3c0f-11eb-8d7f-dcf37de59aad.png
https://user-images.githubusercontent.com/47359245/101955849-9f511800-3c0f-11eb-9044-ceed26548558.png

This is how menuconfig looks when shrinked:
https://user-images.githubusercontent.com/47359245/101956354-809f5100-3c10-11eb-89ff-52fb233822fb.png

**Comment by kchibisov** [comment]
>Ncurses interfaces don't redraw on some programs after i resize them. So i have pinned down alacritty (also termite has the same issue) to be the cause of it, as rxvt-unicode draws ncurses fine.

I don't see how alacritty could do anything wrong, the only way to resize application is to send SIGWINCH to it. If applications ignore theme it's up to them, especially since you can repro with other terminal emulator, and I bet something like vte, which is the widely used, would have 'such' issues.

it could be just timing related so it 'happen' to work for you in urxvt, since I can't repro any of those issues.

**Comment by maksmeshkov** [comment]
How can this be timing related if I can never get mocp, htop, menuconfig and ranger to resize on alacritty and termite, while they work seamlessly on urxvt?

**Comment by kchibisov** [comment]
You just send sigwinch with delay instead of right away?

**Comment by kchibisov** [comment]
I mean, you can easily test it by writing simple application that handles sigwinch(without even ncurses), and you if see that sigwinch isn't coming for your resizes let us know.

**Comment by maksmeshkov** [comment]
I just tried manually sending SIGWINCH to mocp with `kill -SIGWINCH (pidof mocp)` and it still did not resize.

ok, i will try to write a SIGWINCH test

**Comment by kchibisov** [comment]
Maybe this application uses other way to resize itself? If SIGWINCH isn't triggering it then you're out of luck. Could try running `alacritty -vvv` and see for `unhandled` stuff.

**Comment by maksmeshkov** [comment]
only one unrelated unhandled trace before i unsuccessfully try to resize mocp

**Comment by kchibisov** [comment]
if you define `define` glitches it could help.

**Comment by kchibisov** [comment]
You can also add add/enable logging in mocp or add your own logging in it all over the place to understand the issue.

**Comment by tcld** [comment]
I have been seeing the same problems described above; it seems to have started within the last few weeks - between ranger, ncurses and alacritty, only alacritty got an update since then.

On top of the applications above, `weechat` doesn't properly work anymore; after switching between chat rooms a number of times the window gets messed up more and more, the redraws appear to be missing.

**Comment by kchibisov** [comment]
Well, downgrade alacritty and retest then?

**Comment by chrisduerr** [comment]
> I have been seeing the same problems described above; it seems to have started within the last few weeks - between ranger, ncurses and alacritty, only alacritty got an update since then.

Downgrading Alacritty should be a trivial endeavor. So if you can repro this with Alacritty and you think that it's due to a change from us, I'd appreciate if you could bisect it.

> On top of the applications above, weechat doesn't properly work anymore; after switching between chat rooms a number of times the window gets messed up more and more, the redraws appear to randomly leave out parts of the window.

I cannot reproduce this either.

**Comment by tcld** [comment]
At the moment I am just using the packaged alacritty from my distro. I can try checking out the code and comparing a few versions.

**Comment by tcld** [comment]
I compiled versions 0.6.0 and 0.5.0 via `cargo build --release` (I launched those from my systems alacritty - I'm assuming the issue can't propagate between them), and both are showing the problem. I also tested `urxvt` and `termite` and can confirm what was said in the original post. So alacritty doesn't appear to be at the root of this. Back to square one.

**Comment by chrisduerr** [comment]
I'm happy to help if someone has any questions, but as it has already been established this doesn't seem to be an Alacritty issue.

**Comment by tcld** [comment]
I have now tested the following terminal emulators on my system:
`kitty terminator qterminal sakura terminology xterm rxvt-unicode alacritty`

Only `urxvt` and `terminology` don't show any problems. Sadly I don't see the connection between the others. So if anybody has an idea...

**Comment by DorianGray** [comment]
In case others find this thread, the cause of this issue is that bash automatically provides the `LINES` and `COLUMNS` variables that are set to the current size of the terminal. When you spawn something like `htop`, it takes those as you wanting it to be a static size.

The solution is to do something like I've done for htop here

```
#!/bin/bash
COLUMNS=
LINES=
exec /usr/bin/htop "$@"
```

@tcld suggested I post this solution here as I posted it on the qtile-dev ml.

**Comment by maksmeshkov** [comment]
Fix: https://github.com/fish-shell/fish-shell/issues/7707

Adding these lines to config.fish fixed the issue for me.
```
set --unexport COLUMNS
set --unexport LINES
```

**Comment by MithicSpirit** [comment]
A better way to fix this is by adding 
```yaml
  LINES: ""
  COLUMNS: ""
``` 
to the `env:` section of `alacritty.yml`, as it will fix it for when you run `alacritty -e <anything>`. While I believe that this is better (I have yet to run into any issues from having this in my config), I am not sure whether this should be changed to be the default, however, as `xterm`, the "standard" terminal emulator, also sets them.

**Comment by tcld** [comment]
Since alacritty is by far not the only terminal emulator suffering from the issue, I would argue that any workaround should be happening on the shell level or above, if possible.
