### ISSUE TITLE
tmux vim colors false on equal $TERM

### ISSUE THREAD

**Issue by b3z** [alacritty/alacritty#4563]
### Issue

I want to have the same vim colors in tmux like I have in my normal terminal.

Now the first thing to look at is the TERM variable.

```sh
# plain zsh alacritty
$ echo $TERM
xterm-256color

# tmux (/-2)
$ echo $TERM
xterm-256color
```

But somehow they are the same but still showing different colors.
Any ideas?

### System

OS: macOS 11.0.1 (20B29)
Version: alacritty 0.5.0 (a6681e3)
Shell: zsh 5.8

tmux: tmux 3.1c
vim: 8.2 Included patches: 1-850

##### .tmux.conf
```sh
bind - split-window -h
bind _ split-window -v

set-option -g prefix C-a

set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g default-terminal "xterm-256color"
```

##### .zshrc
```sh
[...]

export TERM=xterm-256color
[ -n "$TMUX" ] && export TERM=xterm-256color

[...]

```

**Comment by chrisduerr** [comment]
Someone else might be able to help you, but if you have problems with tmux you should probably ask tmux people.

**Comment by b3z** [comment]
This is probably an alacritty issue since it doesn't occur in other terminals.

**Comment by chrisduerr** [comment]
If it works outside of tmux, it's probably not an Alacritty issue.

**Comment by kchibisov** [comment]
You don't set `TERM` in zsh, you set it in alacritty.yml.

**Comment by lonelykid** [comment]
Actually this is a vim and tmux issue. Not alacritty issue. You can reproduce this in any terminal by calling tmux or just setting TERM to screen-256color.
https://unix.stackexchange.com/questions/348771/why-do-vim-colors-look-different-inside-and-outside-of-tmux
Try adding ``set background=dark`` to your vim setting. I don't think this is an elegant solution though.

**Comment by b3z** [comment]
Yes I figured that out. I thought it had to do with the alacritty colors but it didn't.

**Comment by lonelykid** [comment]
There is a more consistent solution. Suppose you didn't set bg in tmux. you can let vim query bg from outer terminal. Add this to your .vimrc.
```vim
if exists("$TMUX")
    let &t_RB = "\ePtmux;\e\e]11;?\007\e\\"
endif
```
