### ISSUE TITLE
Mouse is not behaving properly in neovim

### ISSUE THREAD

**Issue by ndavidpsi** [alacritty/alacritty#4565]
### System

OS: Windows
Version: 0.7.0dev (a2727d0) 

### Behavior

I have set mouse support in Neovim as you can see in the image of my init.vim. The mouse support works fine using both Windows Terminal and cmd. While in alacritty neovim doesn't recognize the mouse. I have selected a portion of the text but the cursor doesn't change position and neovim doesn't even enter Visual Mode.

![IMG_20201212_225030](https://user-images.githubusercontent.com/73792104/101998796-5b711800-3cce-11eb-9771-26ac8730cfb5.jpg)

**Comment by kchibisov** [comment]
yeah, mouse mode isn't working, try updating Windows.

**Comment by ndavidpsi** [comment]
My Windows is updated (20H0 version). And like I said, this issue doesn't occur in other terminals. Can it be related to some alacritty settings?

**Comment by ndavidpsi** [comment]
@chrisduerr why was the issue closed?

**Comment by chrisduerr** [comment]
Because this is a known issue that has been confirmed to be a Windows bug.

**Comment by kchibisov** [comment]
No, your windows conpty version is likely outdated.

See https://github.com/alacritty/alacritty/issues/1663

**Comment by ndavidpsi** [comment]
Hm alright
