### ISSUE TITLE
custom Paste command/action question

### ISSUE THREAD

**Issue by mckelly2833** [alacritty/alacritty#4570]
Thank you for Alacritty, it is awesome.
Just a question really, I could not find any info about this anywhere else.
Q: Can I specify a custom Paste command ?
I tried using a command binding for xclip but I cannot get it to display anything.
thx,
-m

**Comment by chrisduerr** [comment]
You want to bind a command to a key and use its output for input in Alacritty?

**Comment by mckelly2833** [comment]
Yes.  Instead of Paste action, can I run my own custom wl-paste program etc.

**Comment by kchibisov** [comment]
No, and I don't see a reason for it.

**Comment by mckelly2833** [comment]
ok.
thx,
-m
