### ISSUE TITLE
Italics in manpages

### ISSUE THREAD

**Issue by jamellyf** [alacritty/alacritty#4572]
Hi, all, I think alacritty is not properly rendering italics in man pages, for example, in the image bellow the text should be italics, right?

![screenshot](https://imgur.com/a/zpb6hd3)

Typing `echo -e "\e[3m is this italics? \e[23m"` returns a beautiful italics text though. 

### System

OS: Linux(Fedora 33)
Version: 0.6.0
Linux/BSD: Gnome running on Wayland
Font : Jetbrains Mono

**Comment by kchibisov** [comment]
If you think that something in man pages should be italic, ensure that you have italics attribute in them. If your echo command works fine it means that you're not using italics in man pages in a first place.

**Comment by jamellyf** [comment]
You're right, that's my fault!
