### ISSUE TITLE
Phantom cursor in Neovim's embedded terminal on Windows

### ISSUE THREAD

**Issue by bohrshaw** [alacritty/alacritty#4573]
Ways to reproduce:

- Open Alacritty
- `wsl`
- `nvim -u NORC +term +startinsert`
- Type keys: `<C-\><C-N>i`

Result:

There's two cursors.

### System

OS: Windows 20H2
Version: alacritty 0.6.0 (04cbf76)
Linux/BSD: X11/Wayland, DE or Compositor and WM
Windows: WinPTY

**Comment by chrisduerr** [comment]
Can you maybe show a screenshot of the problem?

Also you say that you're using the WinPTY, but version 0.6.0 doesn't support WinPTY by default. Did you compile Alacritty with WinPTY support?

**Comment by bohrshaw** [comment]
I was wrong about WinPTY. I used the official Alacritty installer and it must use ConPTY.

There are two cursors after some typing in Neovim's embedded terminal:

![image](https://user-images.githubusercontent.com/1585463/102174512-9e064080-3ed8-11eb-97a9-c78e43e5bed1.png)

**Comment by kchibisov** [comment]
If you have `unfocussed_hollow: true`(should be by default) and focus other window, you'd see only one hollow cursor, right? It seems like ConPty is acting tbqh, so neovim's cursor and the one conpty is telling us desynced.

**Comment by bohrshaw** [comment]
When another window is focused, there are still two cursors:

**Comment by bohrshaw** [comment]
Same issue in: https://github.com/neovim/neovim/issues/12677

**Comment by chrisduerr** [comment]
This makes it clear though that Alacritty is only rendering a single cursor. The one you see on the right.

So the first line is not a cursor but just some inverted cell. This is either a ConPTY or Vim bug, I'd assume it's probably the ConPTY.

**Comment by bohrshaw** [comment]
After reading https://github.com/neovim/neovim/issues/14386, I think Neovim is telling the terminal to hide the cursor when entering its terminal mode. But the cursor is not hidden.
