### ISSUE TITLE
Move render_time position on the right side of the window

### ISSUE THREAD

**Issue by juarezr** [alacritty/alacritty#4574]
### Move render_time position on the right side of the window

Category: enhancement
Version: `0.7`
Linux: Ubuntu 20.04

#### Description

Currently, when enabling `render_timer` in the `debug` section of  `alacritty.yml`, the label is displayed in the penultimate line (last but one) on the left side.

But as soon as the screen is filled with text the label start obstructing the reading. As the penultimate line frequently has the result of the last command executed, this becomes quite annoying. :smiley: 

#### Example

``` bash
# ~
$ cd ~/src/github/alacritty/
# alacritty > @master 🦀 v1.48.0 
$ ls -l
total 184
drwxrwxr-x 4 juarezr juarezr   122 nov 25 22:25 alacritty/
drwxrwxr-x 4 juarezr juarezr    70 nov 25 22:25 alacritty_terminal/
-rw-rw-r-- 1 juarezr juarezr 26211 nov 25 22:25 alacritty.yml
-rw-rw-r-- 1 juarezr juarezr 61792 nov 25 22:25 Cargo.lock
-rw-rw-r-- 1 juarezr juarezr   129 nov 25 22:25 Cargo.toml
-rw-rw-r-- 1 juarezr juarezr 36938 nov 25 22:25 CHANGELOG.md
-rw-rw-r-- 1 juarezr juarezr  8070 nov 25 22:25 CONTRIBUTING.md
drwxrwxr-x 2 juarezr juarezr    70 nov 25 22:25 docs/
drwxrwxr-x 7 juarezr juarezr   119 nov 25 22:25 extra/
-rw-rw-r-- 1 juarezr juarezr  9579 nov 25 22:25 INSTALL.md
-rw-rw-r-- 1 juarezr juarezr 10843 nov 25 22:25 LICENSE-APACHE
-rw-rw-r-- 1 juarezr juarezr  2093 nov 25 22:25 Makefile
-rw-rw-r-- 1 juarezr juarezr  5527 nov 25 22:25 README.md
-rw-rw-r-- 1 juarezr juarezr   358 nov 25 22:25 rustfmt.toml
drwxrwxr-x 2 juarezr juarezr   107 nov 25 22:25 scripts/
drwxrwxr-x 3 juarezr juarezr    65 nov 25 22:32 target/
1763.196 usecs@master 🦀 v1.48.0
$
```

In this case the label `1763.196 usecs` overrides the text in the penultimate line.

#### Some Alternatives

1. Render the label on the right-bottom corner of the window. :+1: 
   - this corner is the last to be read for left-right + top-bottom languages.
   - so it's considered the least distracting position on any window.
2. Render the label on the top-left corner of the window.
   - because sometimes it's not worth a lot of effort for such as small improvement
   - this corner overrides text also but gets in the way less than bottom-left corner.
3. Render the label on the title bar.
   - overkill maybe. :angry:  
4. Any good idea about it. :smiley: 

Thanks

**Comment by chrisduerr** [comment]
This option is purely for debugging and I've never run into any problems with using it for that purpose. Having it active in an interactive shell session doesn't make much sense either way.

So I see no reason why this would be changed.
