### ISSUE TITLE
How to make keybinding Ctrl+Space work in Vim?

### ISSUE THREAD

**Issue by hrqmonteiro** [alacritty/alacritty#4575]
### System

OS: Void Linux
Version: 0.6.0
Linux/BSD: X11, AwesomeWM

How can i make the keybinding Ctrl+space work in my vim? I was searching it everywhere in the forums on vim about why it is not working, and many people pointed out the fact that maybe the terminal was the issue. And yes, i tried with urxvt and the keybind i set in vim works, only in alacritty that it is not.

I have nothing set on Ctrl+Space on `alacritty.yml` and still is preventing me from using the keys. Everytime i press Ctrl+Space it skips a line on vim, and i don't want that, i want it to do what i mapped on vim.

**Comment by chrisduerr** [comment]
What keybinding are you using in vim and what output do you get when pressing ctrl+v -> ctrl+space in your shell?

**Comment by hrqmonteiro** [comment]
> What keybinding are you using in vim and what output do you get when pressing ctrl+v -> ctrl+space in your shell?

Keybinding in vim is Ctrl+Space for autocompletion using [coc.nvim](https://github.com/neoclide/coc.nvim)

```if has('nvim')
  inoremap <silent><expr> <c-space> coc#refresh()
else
  inoremap <silent><expr> <c-@> coc#refresh()
endif
```
If i press `ctrl+v -> ctrl+space` on alacritty i get an space.

**Comment by chrisduerr** [comment]
> If i press ctrl+v -> ctrl+space nothing happens.

Have you tested this with the default Alacritty config?

**Comment by hrqmonteiro** [comment]
> > If i press ctrl+v -> ctrl+space nothing happens.
> 
> Have you tested this with the default Alacritty config?

I actually haven't changed anything on the alacritty config except for the fonts and the colors, everything else are the set on the default values.

**Comment by chrisduerr** [comment]
What does `alacritty --print-events | grep "ReceivedCharacter"` print when you press ctrl+space?

**Comment by hrqmonteiro** [comment]
> What does `alacritty --print-events | grep "ReceivedCharacter"` print when you press ctrl+space?

[2020-12-15 15:30:33.066485577] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(X(WindowId(69206018))), event: ReceivedCharacter('\u{0}') }

**Comment by chrisduerr** [comment]
Then ctrl+v -> ctrl+space should print `^@` if you're running with an empty configuration file. Please make sure to test with `--config-file /dev/null`. Also make sure you're not running with tmux or anything like that.

**Comment by hrqmonteiro** [comment]
I tried using `alacritty --config-file /dev/null --print-events | grep "ReceivedCharacter"`

And when i press ctrl+v ctrl+space it prints me a result for each one of it.

```
[2020-12-15 16:08:24.376759026] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(X(WindowId(31457282))), event: ReceivedCharacter('\u{16}') }
[2020-12-15 16:08:25.176783933] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(X(WindowId(31457282))), event: ReceivedCharacter('\u{0}') }
``` 

And this happens if i run my default configuration, too.

**Comment by chrisduerr** [comment]
What happens when you run `showkey -a` and press ctrl+space?

**Comment by hrqmonteiro** [comment]
```
Press any keys - Ctrl-D will terminate this program

^@ 	  0 0000 0x00
```

**Comment by chrisduerr** [comment]
That's exactly the key that is supposed to be received by the terminal. So things should probably be working.

Do you use neovim or vim?

**Comment by hrqmonteiro** [comment]
I am using Neovim.

**Comment by chrisduerr** [comment]
Can you run an empty neovim and Alacritty config and then execute `:nmap <c-space> :works` and press ctrl+space in normal mode?

**Comment by hrqmonteiro** [comment]
> Can you run an empty neovim and Alacritty config and then execute `:nmap <c-space> :works` and press ctrl+space in normal mode?

I just did that, but i can't see what's the point. After i did `:nmap <c-space> :works` now i am pressing <c-space> and it only shows me `:works` on the vim command line, and if i keep pressing <c-space> it keeps adding spaces in front of the :works text.

**Comment by kchibisov** [comment]
So it works as expected. And nvim reacts on c-space.

**Comment by chrisduerr** [comment]
> How can i make the keybinding Ctrl+space work in my vim?

You just did.

**Comment by hrqmonteiro** [comment]
> So it works as expected. And nvim reacts on c-space.

Well, i see, so, as a matter of opinions, any guess why this isn't working on my default vim config?

The key not showing "^@" on the print-events isn't an issue? So maybe is an issue with the `coc.nvim` plugin, you think?

**Comment by kchibisov** [comment]
Bind your C-space explicitly, idk.

**Comment by pldg** [comment]
I've the same problem. I'm on Windows 10 using WSL Ubuntu 20.04. Testing with default alacritty.yml config.

Using `alacritty.exe --print-events | grep "ReceivedCharacter"` prints out `[INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(0x40674)), event: ReceivedCharacter(' ') }` for both space and control+space.

Using `showkey -a` prints out `32 0040 0x20` for both space and control+space.

In both Windows Terminal and Command Prompt using `showkey -a` prints out `32 0040 0x20` for space and `^@ 0 0000 0x00` for control+space.

Therefor, in Vim 8.1 mapping `inoremap <silent><expr> <c-@> coc#refresh()` works in Windows Terminal and Command Prompt but do not work in Alacritty.

How can I make control+space send `^@ 0 0000 0x00` signal in Alacritty?

**Comment by hrqmonteiro** [comment]
> I've the same problem, I'm on Windows 10 using WSL Ubuntu 20.04.
> 
> Test with Alacritty v0.7.1 and default alacritty.yml config:
> 
>     * Using `alacritty.exe --print-events | grep "ReceivedCharacter"` prints out `[INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(0x40674)), event: ReceivedCharacter(' ') }` for both space and control+space.
> 
>     * Using `showkey -a` prints out `32 0040 0x20` for both space and control+space.
> 
> 
> While in both Windows Terminal and Command Prompt using `showkey -a` prints out `32 0040 0x20` for space and `^@ 0 0000 0x00` for control+space.
> 
> Therefor, in Vim 8.1 mapping `inoremap <silent><expr> <c-@> coc#refresh()` works in Windows Terminal and Command Prompt but do not work in Alacritty.
> 
> How can I make control+space send `^@ 0 0000 0x00` signal in Alacritty?

I gave up trying, it was clearly an Alacritty problem. I switched to Kitty and it's working fine all the keys.

**Comment by ch4m1gn0n** [comment]
i found a solution [here](https://github.com/alacritty/alacritty/issues/1703#issuecomment-433445979),  remap ctrl-space to \x00 in alacritty config

**Comment by nooneknowspeter** [comment]
` { key = "Space", mods = "Control", chars = "\u0000" }` worked for me
