### ISSUE TITLE
[mac] ctrl + / not work

### ISSUE THREAD

**Issue by findNextStep** [alacritty/alacritty#4584]
when use `crtl + /`it do nothing in alacritty,but show ^_ in kitty

### System

OS: macOS
Version: alacritty 0.6.0

**Comment by chrisduerr** [comment]
Empty config? What shell?

**Comment by findNextStep** [comment]
> Empty config? What shell?

in zsh and vim
here is my config https://github.com/findNextStep/mydot

**Comment by findNextStep** [comment]
my config should have nothing  effect i try`zsh -d -f -i`,is same

**Comment by chrisduerr** [comment]
What do you get when you run `alacritty --print-events | grep "ReceivedCharacter"` and press these keys?

**Comment by findNextStep** [comment]
> What do you get when you run `alacritty --print-events | grep "ReceivedCharacter"` and press these keys?

no thing show out

**Comment by chrisduerr** [comment]
Then this is a duplicate of https://github.com/alacritty/alacritty/issues/1359.
