### ISSUE TITLE
Panic in concept_frame.rs when opening Alacritty

### ISSUE THREAD

**Issue by catleeball** [alacritty/alacritty#4591]
### System

OS: Clear Linux `Linux $HOSTNAME 5.9.14-1007.native #1 SMP Fri Dec 11 05:03:15 PST 2020 x86_64 GNU/Linux`
Version: `alacritty 0.7.0-dev (116faba)` and also `alacritty 0.6.0 (04cbf76)`
Linux/BSD: Gnome on Wayland, Nouveau driver for GPU
- `gnome-shell --version` -> `GNOME Shell 3.38.2`
- nouveau version 5.9.14-1007.native SMP mod_unload ([full modinfo output](https://gist.github.com/catleeball/c01ff0773534ddcd05ced3b3ead3ea9a))
- [hardware (in a google sheet)](https://docs.google.com/spreadsheets/d/1lIlZ_OYXOURL2VhYCJr03b6iWKPYZAG_f-bMsFBaCnQ/edit?usp=sharing)

### Logs

Backtrace to stderr: https://gist.github.com/catleeball/ade1dfe5fb4997e1726bf00a92f0fefd

### Summary

Very briefly, Alacritty crashes when I try to open it when building at head or at 0.6. More details below:

### Steps to reproduce

- git clone alarcritty repo
- install deps from install.md:
  - `sudo swupd bundle-add devpkg-expat devpkg-freetype devpkg-libxcb devpkg-fontconfig`
- ensure rust stable toolchain is up-to-date
  - `rustup update`
  - `rustup show active-toolchain` -> `stable-x86_64-unknown-linux-gnu (default)`
- build alacritty from repo head
  - `RUSTFLAGS="-C target-cpu=native" cargo build --release`
- Check version of the resulting binary
  - `alacritty --version` -> `alacritty 0.7.0-dev (116faba)`
- Try to run binary, encounter panic
  - https://gist.github.com/catleeball/ade1dfe5fb4997e1726bf00a92f0fefd

### Troubleshooting

Tried checking out latest release instead of head:

- `cargo clean` after last build
- get latest release (instead of head) `git checkout v0.6.0`
- rebuild with `RUSTFLAGS="-C target-cpu=native" cargo build --release`
- Crashes again :(
  - all terminal out, including build output and panic backtrace: https://gist.github.com/catleeball/1f987e8850175efbb5f2aab78eb54939

Then I tried building v0.6.0 without the RUSTFLAGS:

- `cargo clean`
- `cargo build --release`
- crashes again. [log](https://gist.github.com/catleeball/32627c17306b582afd0349cefe273852)

Then I tried installing via cargo rather than building from the source repo:

- `cargo install alacritty`
- still crashes. [log](https://gist.github.com/catleeball/a1aa403528c2bda23ef5b3e2912e9790)

### Epilogue

I checked journalctl and didn't find anything too interesting. I haven't tried switching to Gnome on X11 yet, but I'll try that in the morning.

Please let me know if there's any info or logs that would assist you in debugging.

**Comment by chrisduerr** [comment]
Which distro do you run? This is a crash due to fontconfig in one of our dependencies, I'd assume you maybe have your fontconfig configuration in a strange location?

**Comment by catleeball** [comment]
I'm running Clear Linux on the kernel-native branch and I installed fontconfig through the package manager swupd.

- swupd definition for fontconfig package: https://github.com/clearlinux/clr-bundles/blob/master/bundles/devpkg-fontconfig

It looks like my fonts.conf is in `/usr/share/defaults/fonts/fonts.conf`. When I peeked at it in vim, Syntastic complains about line 2: `|2 error| warning: failed to load external entity "/usr/share/defaults/fonts/fonts.dtd"`. And sure enough, that file doesn't exist.

- ![Screenshot of syntastic error](https://user-images.githubusercontent.com/43632885/102654201-021d4480-4125-11eb-8363-22a202786a3c.png)
- `tree` on /usr/share/defaults/fonts: https://gist.github.com/catleeball/7df795ab0a2522c0662dfce59214034e
- contents of fonts.conf: https://gist.github.com/catleeball/90bf749640d2390329b0ff095d085c85
- contents of 42-clear.conf: https://gist.github.com/catleeball/8a2089bfa87ba73f97cb5341d630717f

I'm about to head out the door, but later I can try symlinking these configs to some of the standard directories at the top of [the font-config docs](https://www.freedesktop.org/software/fontconfig/fontconfig-user.html), or pass ./configure some paths or something.

Let me know if you have suggestions or need more info! Thanks!

**Comment by catleeball** [comment]
I haven't done a whole lot more troubleshooting than before, but I made a symlink to `/usr/share/defaults/fonts/fonts.conf` in /etc/fonts/font.config, Alacritty was able to launch.

However, putting a symlink to fonts.conf in `$HOME/.local/share/fonts.conf` or `$HOME/.local/share/fonts/fonts.conf` or `/usr/local/share/fonts.conf` doesn't work, same panic.

My `$XDG_DATA_DIRS` is set to `/home/cat/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share`, but unsetting it temporarily didn't seem to help either.

I'm curious if [this line](https://github.com/Smithay/andrew/blob/master/src/text/fontconfig.rs#L13) in the [andrew crate](https://github.com/Smithay/andrew) isn't working as the author intended, but I need to test it out. I might file a bug in the andrew repo if I can confirm it.

**Comment by catleeball** [comment]
Thank you for fixing this bug! :100:
