### ISSUE TITLE
Unable to launch Alacritty

### ISSUE THREAD

**Issue by kiranajij** [alacritty/alacritty#4599]
My alacritty not opening
### System

OS: `Linux`
Version: `alacritty 0.7.0-dev (8a7f8c9)`
Linux: `X11`
Windows: `Don't know what this means`
Distro: Linux ubuntu(18.04) 5.3.0-7648-generic

### Terminal output

Unable to launch alacritty,
```
$ alacritty
Created log file at "/tmp/Alacritty-11998.log"
[2020-12-20 17:13:30.173900315] [ERROR] [alacritty] Alacritty encountered an unrecoverable error:
                                                    
                                                    	Error creating GL context; Received multiple errors. Errors: `[OsError("Could not create EGL display object"), OsError("Couldn\'t find any available vsync extension")]`
```
This is the error I am getting. 

### alacritty log file

```
[2020-12-20 17:13:30.173900315] [ERROR] [alacritty] Alacritty encountered an unrecoverable error:
                                                    
                                                    	Error creating GL context; Received multiple errors. Errors: `[OsError("Could not create EGL display object"), OsError("Couldn\'t find any available vsync extension")]`
```

### 
Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`
^^
None of these commands work

**Comment by chrisduerr** [comment]
Does your GPU support OpenGL 3.3 or higher?

**Comment by kiranajij** [comment]
do i requied to have a GPU?

**Comment by chrisduerr** [comment]
You require to have a GPU to plug a monitor into your computer, yes.

**Comment by olivierpilotte** [comment]
Downgrade `mesa` to `20.2.3`

**Comment by chrisduerr** [comment]
Closing due to lack of communication. As @olivierpilotte has already pointed out, it's not unlikely that a mesa upgrade caused an issue.
