### ISSUE TITLE
Terminfo on remote machine

### ISSUE THREAD

**Issue by samuelstevens** [alacritty/alacritty#4601]
I'm trying to use CTRL-L to clear my terminal on a remote host. It works on my local machine.

I have set my `$TERM` to `xterm-256color` on my local machine and on the remote machine. `infocmp` shows that `xterm-256color` is in `/usr/share/terminfo` on my local machine. On the remote machine it's in `$HOME/anaconda3/share/terminfo/`. 

The suggestion of `TERM=xterm-256color ssh <host>` did not work for me.

I don't quite understand how terminfo is communicated to Alacritty, so perhaps I'm missing some connection between the anaconda directory and Alacritty, but I would expect CTRL-L to work on the remote machine.

### System

OS: macOS 10.14.6 (Mojave) & Ubuntu 20.04.1 LTS
Version: alacritty 0.6.0 (04cbf76)

**Comment by chrisduerr** [comment]
It isn't "communicated to Alacritty" at all. Ctrl+L working just depends on your shell, it's not a standard signal like Ctrl+C.

If `infocmp <terminfo>` gives you some proper output, the terminfo could be found.

**Comment by samuelstevens** [comment]
Gotcha, thanks for explaining.

(For anyone else, I was running into this issue in bash because I had `set -o vi` and CTRL+L is only sent to bash in command mode, not insert mode. [This stackoverflow](https://unix.stackexchange.com/questions/104094/is-there-any-way-to-enable-ctrll-to-clear-screen-when-set-o-vi-is-set) might help you out)
