### ISSUE TITLE
colors in alacritty

### ISSUE THREAD

**Issue by ghistes** [alacritty/alacritty#4603]
Hi,

I've compiled alacritty from source and created a new config file from scratch.
There are no color-definitions in this config file.

Somewhere in my distribution's (Debian) config-files LS_COLORS is set - I did not touch that.

Now when I run "ls" I get colored output, but while the colors look the same under st or urxvt they look different with alacritty - e.g. directories are ususally bright blue, but with alacritty they are still blue, yet is is a very dim, greyish blue.

What is going on here and how can I configure alacritty so that I get the colors I am used to?

Many thanks!

**Comment by chrisduerr** [comment]
If you don't like Alacritty's default colors, feel free to choose your own.

**Comment by ghistes** [comment]
I guess I rather go for another emulator with a more helpful community.

**Comment by 40four** [comment]
@ghistes What's happening is Alacritty's default color scheme is 'Tomorrow Night'. If you didn't already, I recommend copy and pasting the default config file for the version you compiled. You can find them in the assets in the release pages. 

To start, everything is commented out, and you can go in and un-comment things you want to change the defaults. Look for 'colors' and you will see the values for 'Tomorrow NIght'. You can change the values in place, or add new ones. My recommendation would be to make a separate file to manage your colors. I keep mine in the same spot as `alacritty.yml` and call it `color_schemes.yml`. 

The wiki has templates for a lot of common color schemes ready to go. https://github.com/alacritty/alacritty/wiki/Color-schemes. In you `color_schemes.yml`, follow the format here https://github.com/alacritty/alacritty/wiki/Color-schemes#multiple-schemes, then you can put in as many schemes as you want and switch between them easily. Load your `color_schemes.yml` at the top of your `alacritty.yml` with the `import:` option and you're good to go!
