### ISSUE TITLE
performance regression - shadow invalidation - macOS

### ISSUE THREAD

**Issue by DivineGod** [alacritty/alacritty#4604]
Latest master (https://github.com/alacritty/alacritty/commit/5725f5812ca5e8d7d992da4ac66aa454a8a9a9ad) makes alacritty extremely unusable with opacity set to anything lower than 1.0

### System

OS: macOS
Version: master (https://github.com/alacritty/alacritty/commit/5725f5812ca5e8d7d992da4ac66aa454a8a9a9ad)

### Logs

vtebenches:

[master-opacity-1.0.txt](https://github.com/alacritty/alacritty/files/5726918/master-opacity-1.0.txt)
[master-opacity-0.8.txt](https://github.com/alacritty/alacritty/files/5726919/master-opacity-0.8.txt)

Note: Running vtebench will also make the rest of the system less responsive with opacity < 1.0

I ran the benchmarks on power and noticed that only the "Intel UHD graphics 630" iGPU was used and not my dGPU AMD Radeon Pro 5500M.

**Comment by chrisduerr** [comment]
Hm that's a great point. Thanks for letting me know.

I kinda assumed something like this was the case, but I didn't see any immediate issues myself. I've got a patch that should fix this though.

**Comment by chrisduerr** [comment]
Could you test these two patches? I think the first patch might not fix the artifact problem, but it would be the nicest solution. The second patch should definitely fix this issue and the shadow problem.

```diff
diff --git a/alacritty/src/display.rs b/alacritty/src/display.rs
index fb82b9f8..3c88b15d 100644
--- a/alacritty/src/display.rs
+++ b/alacritty/src/display.rs
@@ -423,6 +423,12 @@ impl Display {
 
         info!("Padding: {} x {}", self.size_info.padding_x(), self.size_info.padding_y());
         info!("Width: {}, Height: {}", self.size_info.width(), self.size_info.height());
+
+        // Clear window shadows to prevent shadow artifacts on macOS.
+        #[cfg(target_os = "macos")]
+        if config.ui_config.background_opacity() < 1.0 {
+            self.window.invalidate_shadow();
+        }
     }
 
     /// Draw the screen.
@@ -610,12 +616,6 @@ impl Display {
         #[cfg(all(feature = "wayland", not(any(target_os = "macos", windows))))]
         self.request_frame(&self.window);
 
-        // Clear window shadows to prevent shadow artifacts on macOS.
-        #[cfg(target_os = "macos")]
-        if config.ui_config.background_opacity() < 1.0 {
-            self.window.invalidate_shadow();
-        }
-
         self.window.swap_buffers();
 
         #[cfg(all(feature = "x11", not(any(target_os = "macos", windows))))]
```

```diff
diff --git a/alacritty/src/display.rs b/alacritty/src/display.rs
index fb82b9f8..f9e8cfaf 100644
--- a/alacritty/src/display.rs
+++ b/alacritty/src/display.rs
@@ -161,6 +161,8 @@ pub struct Display {
     /// UI cursor visibility for blinking.
     pub cursor_hidden: bool,
 
+    #[cfg(target_os = "macos")]
+    invalidate_shadows: bool,
     renderer: QuadRenderer,
     glyph_cache: GlyphCache,
     meter: Meter,
@@ -423,6 +425,9 @@ impl Display {
 
         info!("Padding: {} x {}", self.size_info.padding_x(), self.size_info.padding_y());
         info!("Width: {}, Height: {}", self.size_info.width(), self.size_info.height());
+
+        #[cfg(target_os = "macos")]
+        self.invalidate_shadows = true;
     }
 
     /// Draw the screen.
@@ -612,8 +617,9 @@ impl Display {
 
         // Clear window shadows to prevent shadow artifacts on macOS.
         #[cfg(target_os = "macos")]
-        if config.ui_config.background_opacity() < 1.0 {
+        if self.invalidate_shadows && config.ui_config.background_opacity() < 1.0 {
             self.window.invalidate_shadow();
+            self.invalidate_shadows = false;
         }
 
         self.window.swap_buffers();
```

**Comment by chrisduerr** [comment]
I can test things myself, though that will likely take a bit since I don't usually run a macOS system.

**Comment by DivineGod** [comment]
As a point of note as well, if I force use of my dGPU the issue goes away and two vtebench runs are very similar.

using my `macos-expose-stutter` branch:

[fix-opacity-1.0.txt](https://github.com/alacritty/alacritty/files/5726961/fix-opacity-1.0.txt)
[fix-opacity-0.8.txt](https://github.com/alacritty/alacritty/files/5726962/fix-opacity-0.8.txt)

perf is slightly better with opacity 1.0 but it's not noticable.

Looking at activity monitor while running with my branch the AMD gpu is only showing any activity. Also the included screenshot shows activity in the two runs with the opacity 0.8 coming first.
<img width="666" alt="Screen Shot 2020-12-22 at 10 24 35" src="https://user-images.githubusercontent.com/36430/102831478-0789d000-4440-11eb-8570-3e812caf5256.png">


I'll run tests with those patches now.

**Comment by DivineGod** [comment]
Patch 1 - Opacity 0.8: [patch-1-opacity-0.8.txt](https://github.com/alacritty/alacritty/files/5727003/patch-1-opacity-0.8.txt)
Patch 1 - Opacity 1.0: [patch-1-opacity-1.0.txt](https://github.com/alacritty/alacritty/files/5727005/patch-1-opacity-1.0.txt)

Patch 2 - Doesn't compile

**Comment by DivineGod** [comment]
Patch 1 runs fine with opacity at 0.8.

I'll see what I can do to get patch 2 to compile

**Comment by chrisduerr** [comment]
@DivineGod Does patch 1 fix the artifacts problem for you?

And patch2 probably just needs some really minor tweak. I'd assume it complains about `invalidate_shadows` not being initialized in `Display::new`? You'll probably just have to add `invalidate_shadows: false,` to the initialization there.

**Comment by DivineGod** [comment]
It complained about that, and that cfg for statements is experimental. updated patch 2:

```diff
diff --git a/alacritty/src/display.rs b/alacritty/src/display.rs
index fb82b9f..ce6dbd6 100644
--- a/alacritty/src/display.rs
+++ b/alacritty/src/display.rs
@@ -161,6 +161,8 @@ pub struct Display {
     /// UI cursor visibility for blinking.
     pub cursor_hidden: bool,

+    #[cfg(target_os = "macos")]
+    invalidate_shadows: bool,
     renderer: QuadRenderer,
     glyph_cache: GlyphCache,
     meter: Meter,
@@ -302,6 +304,7 @@ impl Display {
             #[cfg(all(feature = "wayland", not(any(target_os = "macos", windows))))]
             wayland_event_queue,
             cursor_hidden: false,
+            invalidate_shadows: false,
         })
     }

@@ -423,6 +426,11 @@ impl Display {

         info!("Padding: {} x {}", self.size_info.padding_x(), self.size_info.padding_y());
         info!("Width: {}, Height: {}", self.size_info.width(), self.size_info.height());
+
+        #[cfg(target_os = "macos")]
+        if true {
+            self.invalidate_shadows = true;
+        }
     }

     /// Draw the screen.
@@ -598,7 +606,7 @@ impl Display {

                 // Compute IME position.
                 Point::new(size_info.screen_lines() + 1, Column(search_text.chars().count() - 1))
-            },
+            }
             None => cursor_point,
         };

@@ -612,8 +620,9 @@ impl Display {

         // Clear window shadows to prevent shadow artifacts on macOS.
         #[cfg(target_os = "macos")]
-        if config.ui_config.background_opacity() < 1.0 {
+        if self.invalidate_shadows && config.ui_config.background_opacity() < 1.0 {
             self.window.invalidate_shadow();
+            self.invalidate_shadows = false;
         }

         self.window.swap_buffers();```

**Comment by DivineGod** [comment]
Patch 2 does not fix the issue (but this is also the only one I distinctly noticed this with)

**Comment by DivineGod** [comment]
[patch-2-opacity-1.0.txt](https://github.com/alacritty/alacritty/files/5727060/patch-2-opacity-1.0.txt)
[patch-2-opacity-0.8.txt](https://github.com/alacritty/alacritty/files/5727061/patch-2-opacity-0.8.txt)

**Comment by DivineGod** [comment]
I’ll test if patch 1 fixes the issue a little later. Just gotta go do some holiday errands.

**Comment by chrisduerr** [comment]
Since neither patch 1 nor patch 2 fixed the issue for me, I've decided to go a separate route and just disable shadows for macOS windows completely when the window is transparent.

Please let me know if https://github.com/alacritty/alacritty/pull/4605 works for you.

**Comment by DivineGod** [comment]
> Please let me know if #4605 works for you.

Yes, after fixing the build issue it worked great. I've commented on the PR with the benchmark numbers. 

Also noted that alacritty/alacritty#4605 does fix the expose stutter when opacity is set to 0.8. With opacity set to 1.0 the animation stutters.

**Comment by chrisduerr** [comment]
> Also noted that #4605 does fix the expose stutter when opacity is set to 0.8. With opacity set to 1.0 the animation stutters.

Which animation are you talking about? I suppose we could just **always** disable shadows.

**Comment by DivineGod** [comment]
The animations mentioned in alacritty/alacritty#4474

**Comment by DivineGod** [comment]
Disabled shadows does make the window look a little strange: 
![Uploading Screen Shot 2020-12-22 at 13.48.15.png…]()

**Comment by chrisduerr** [comment]
@DivineGod There seems to be something wrong with your screenshot?

**Comment by DivineGod** [comment]
> @DivineGod There seems to be something wrong with your screenshot?

Fixed - github being a doofus.

**Comment by DivineGod** [comment]
I don't really care about shadows as I'm always in maximised mode or full screen

**Comment by chrisduerr** [comment]
> Disabled shadows does make the window look a little strange:

I'll be honest, as someone that doesn't use macOS, I don't see anything strange in that picture. But I think it probably makes sense to enable shadows for fully opaque windows, just because that's probably what most macOS users would expect.

**Comment by DivineGod** [comment]
Yeah, shadows are pretty pervasive on macos, so it's out of the ordinary to not have them

<img width="609" alt="Screen Shot 2020-12-22 at 14 05 02" src="https://user-images.githubusercontent.com/36430/102844077-c3f28e80-445e-11eb-99f7-3c03c2481b25.png">
