### ISSUE TITLE
WindTerm outperforms alacritty

### ISSUE THREAD

**Issue by c4eater** [alacritty/alacritty#4607]
### System

OS: Debian bullseye x86-64
Version: alacritty 0.7.0-dev (07cfe8b)
DE: X11 + dwm

### Issue
[WindTerm](https://github.com/kingToolbox/WindTerm) claims to have a faster rendering than alacritty and it turns out to be true (as of WindTerm 1.9) at least on my machine (HP Chromebook 14, Intel Celeron 2955U). The printout of 100Mb of urandom data (https://github.com/kingToolbox/WindTerm/blob/master/benchmark/urandom_test.sh) on my machine takes 6-7 seconds on WindTerm and 7-8 seconds on Alacritty. Hence opening an issue per alacritty guidelines.

**Comment by chrisduerr** [comment]
I appreciate the concern, but if you're reporting performance issues please make sure you understand how terminal performance and benchmarking works.

First of all that benchmark itself is rather lackluster, there's a lot more to terminals than just `cat`ing files, so if you run any kind of benchmark comparisons please provide a full comparison using Alacritty's benchmark tool: https://github.com/alacritty/vtebench.

It's important to note that a terminal emulator with an **extremely** slow renderer will do **very well** in these benchmarks. The higher the achieved framerate the more work the terminal has to do. If you want a fair comparison you have to limit the framerate to the lowest common denominator.

In the case of WindTerm, the framerate is pretty bad, so I'd assume they have a pretty slow renderer. If you limit Alacritty's framerate to what looks like about 10FPS with WindTerm I'd assume you would probably see Alacritty being a good chunk faster again. Though Alacritty's goal is **always** to provide a high performance terminal emulation experience, that includes not dropping to unusable framerates.
