### ISSUE TITLE
different padding for different programs

### ISSUE THREAD

**Issue by Trash-af** [alacritty/alacritty#4608]
i want the extra space along borders(padding) to be different for different applications

 Eg no padding for neovim but some for the terminal

  how can i achieve this?

**Comment by chrisduerr** [comment]
Alacritty has no knowledge of which application is running inside your terminal. Though you can run different configurations yourself.

**Comment by Trash-af** [comment]
@chrisduerr  even if i make multipe config files i still need some method to identify which application is running ,can you please recommed a solution?

i know it is wrong place to ask but can shell like zsh identify the running application?

**Comment by chrisduerr** [comment]
A shell can detect which applications you launch, but once an application is launched it doesn't run anymore.

My recommendation would be reevaluate why you need this and if there isn't maybe a different solution to whatever your problem is.
