### ISSUE TITLE
Cursor blinking stops when entering vim or tmux

### ISSUE THREAD

**Issue by DivineGod** [alacritty/alacritty#4609]
I noticed cursor blinking stopped working after entering and exiting vim or tmux.

Steps to reproduce:

1. Enable blinking cursor in alacritty.yml
2. restart alacritty and observe the blinking cursor
3. open `tmux`
4. observe cursor not blinking
5. exit tmux (ctrl-d)
6. cursor still not blinking

To test with vim repeat steps 3 with vim instead. Merely starting and stopping the program is enough.

Expected behaviour:

iTerm2 and Terminal.app both support blinking cursors and they will keep the cursor blinking even in vim and tmux and after exiting said programs.

### System

OS: macOS
Version: master

**Comment by DivineGod** [comment]
Also of note, it doesn't seem to pick up config changes for the file while editing the blinking setting in vim. Not sure if this is intentional or not

**Comment by chrisduerr** [comment]
Yup, that's just what ncurses does. This is what the `blinking: Always` option si for.

**Comment by laggardkernel** [comment]
Same problem. macOS, after entering tmux, cursor stops blinking. Enable `blinking: Always` doesn't solve the problem. Did you find any solution?

**Comment by nixpulvis** [comment]
@laggardkernel

> Same problem. macOS, after entering tmux, cursor stops blinking. Enable `blinking: Always` doesn't solve the problem. Did you find any solution?

This should work. Can you confirm you have set that configuration properly, and restarted a new terminal? To test in a one-off, run `alacritty -o cursor.style.blinking=Always`

**Comment by laggardkernel** [comment]
Sorry to bother you. You're right it works. Seems I misalign the `blinking: Always` line in my config. so embarrassed. Blinking worked outside tmux before is because I had a zsh plugin with ZLE hook modifying the cursor. @nixpulvis

**Comment by nixpulvis** [comment]
No bother, glad it's working for you now. YAML claims many victims :imp:

**Comment by Congee** [comment]
> alacritty -o cursor.style.blinking=Always

It is even more interesting that `alacritty -o cursor.style.blinking=Always` works for me, but setting it in the config alacritty.yml does ensure cursor blinking after entering tmux.
:thinking: 

Anyway, this is helpful, thank you!

**Comment by Congee** [comment]
Never mind, I fell into the same trap as @laggardkernel of misaligning `curosr.style.blinking` by overlooking the middle `style` line :laughing:
