### ISSUE TITLE
[Mac Big Sur] 'use_thin_strokes: true' appears to no longer work

### ISSUE THREAD

**Issue by bluz71** [alacritty/alacritty#4616]
Hello Alacritty team,

I was a very happy Alacritty on Catalina user, especially the `use_thin_strokes` feature.

I upgraded to Big Sur and Alacritty's `use_thin_strokes` feature no longer has an effect, setting it to true or false results in no difference (at least with my setup). Note, I did restart Alacritty when toggling that feature.

I have been using Alacritty 0.6.0.

Has Apple changed APIs or is there something else I need to do at my end?

I really like `use_thin_strokes`, so I am sad that it appears to be gone on Big Sur.

Best regards.

**Comment by chrisduerr** [comment]
> Has Apple changed APIs or is there something else I need to do at my end?

They've probably changed their APIs **again**. There has been some effort from Apple to remove this setting, it might just be gone now.

Could you see if https://github.com/alacritty/alacritty/issues/1635#issuecomment-476353134 works for you?

**Comment by chrisduerr** [comment]
We should set this manually on a per-application level, but that might not be working anymore.

**Comment by chrisduerr** [comment]
As reference for myself, this was our Mojave fix: https://github.com/alacritty/crossfont/blob/master/src/darwin/mod.rs#L256-L278.

**Comment by bluz71** [comment]
> Could you see if #1635 (comment) works for you?

No unfortunately.

> They've probably changed their APIs again. There has been some effort from Apple to remove this setting, it might just be gone now.

iTerm2 `thin-strokes` still works on Big Sur if that is a useful data point.

I would be interested if other Big Sur users encounter this issue. It would be nice to know if this is a Big Sur issue, or an issue just for me. At the moment I suspect all Big Sur users will encounter this.

Note, Apple absolutely nags you to upgrade, so it proves hard to resist. I now wish I hadn't.

**Comment by bluz71** [comment]
> They've probably changed their APIs **again**. There has been some effort from Apple to remove this setting, it might just be gone now.
> 
> Could you see if [#1635 (comment)](https://github.com/alacritty/alacritty/issues/1635#issuecomment-476353134) works for you?

My mind may be playing tricks on me, but this time I did the following:

```sh
defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO
```

Followed by **logging out then logging back into my account** and *I think* my alacritty fonts now look they did in Catalina. The log out then log back in part is different than what I did previously.

But to be honest, I am not 100% sure since I can't easily toggle capability on and off.

For now I am pleased again, I think my alacritty fonts look good again (less fat and chunky).

This Macrumours thread led me to do the log out log in thingy:

https://forums.macrumors.com/threads/any-way-to-disable-font-smoothing-in-big-sur.2267601/

Cheers.

**Comment by chrisduerr** [comment]
Sounds like that's the only way to fix it then.

**Comment by bluz71** [comment]
Note, the alacritty team may wish to re-evaluate `use_thin_strokes` since it doesn't work for macOS versions prior to High Sierra (10.13 / 2017) and versions later than Catalina (10.15).

At the very minimum the documentation for `use_thin_strokes` should note that it only works for High Sierra, Mojave and Catalina.

**Comment by chrisduerr** [comment]
Yeah, removing it eventually definitely seems like a good idea. Though while many people still are on Catalina and Mojave, it should be fine to keep it for now.

**Comment by bluz71** [comment]
For Alacritty on Big Sur, this is probably a better way to go (documentation wise if you so wish):

```sh
defaults write io.alacritty CGFontRenderingFontSmoothingDisabled 0
```

That will only tweak the `CGFontRenderingFontSmoothingDisabled` setting for Alacritty, not globally for everything.

Obviously, log out then log in will be required. Once set it should stick, it appears so to me.

**Comment by chrisduerr** [comment]
I'm surprised that works, since it's basically exactly what Alacritty calls internally to try and disable it.

**Comment by bluz71** [comment]
> I'm surprised that works, since it's basically exactly what Alacritty calls internally to try and disable it.

Interesting. Maybe that the internal Alacritty functionality only effects the current running process not the actual application itself?

The other possibility is that **I may be an unreliable narrator**,  I am purely basing my thoughts on observation, and it may be that my eyes are deceiving me. With most Alacritty settings there is live update feedback whilst this one appears to require a log out then log back in. I could screenshot things to gain confidence. But I actually now have a setup I like, so I don't want to jinx anything by going back. I like where I am now, I ain't touching nothing font wise.

First world problems.

**Comment by chrisduerr** [comment]
> Interesting. Maybe that the internal Alacritty functionality only effects the current running process not the actual application itself?

It changes the global setting, that's why you need to restart it to make it work.

> The other possibility is that I may be an unreliable narrator, I am purely basing my thoughts on observation, and it may be that my eyes are deceiving me. With most Alacritty settings there is live update feedback whilst this one appears to require a log out then log back in. I could screenshot things to gain confidence. But I actually now have a setup I like, so I don't want to jinx anything by going back. I like where I am now, I ain't touching nothing font wise.

Yeah, fair enough. That's why I'm not particularly concerned right now. As long as it works for you right now that should be good. If more users arrive with the same problem it might be worth revisiting this.

**Comment by bluz71** [comment]
> It changes the global setting, that's why you need to restart it to make it work.

Quite likely, I think I created this request just after upgrading, probably no reboots or log outs involved.

>  That's why I'm not particularly concerned right now. 

Yes, closing this is correct. Also this back and forth has likely provided some knowledge if other users hit the issue.

Best regards and many thanks.

**Comment by invis87** [comment]
For me 'thin_strokes' still don't work :(
```
> defaults find CGFontRenderingFontSmoothingDisabled
Found 1 keys in domain 'io.alacritty': {
    CGFontRenderingFontSmoothingDisabled = 0;
}
```
Even after Mac reboot.

Any ideas how to fix?

**Comment by invis87** [comment]
@bluz71 on forum by [you url](https://forums.macrumors.com/threads/any-way-to-disable-font-smoothing-in-big-sur.2267601) they say that Apple moved from `CGFontRenderingFontSmoothingDisabled` to `AppleFontSmoothing` with 4 values (from 0 to 3). 
I tried
```
> defaults find AppleFontSmoothing
Found 1 keys in domain 'io.alacritty': {
    AppleFontSmoothing = 0;
}
Found 1 keys in domain 'alacritty': {
    AppleFontSmoothing = 0;
}
```
and `3` too, but with no success :( 
(I reboot after changes)

**Comment by chrisduerr** [comment]
Since it's `CGFontRenderingFontSmoothingDisabled`, I'd assume that you might have to set `AppleFontSmoothing` to a non-zero value.

**Comment by invis87** [comment]
yep, but as I mention - can't find any difference when value is set to 3 or to 0

**Comment by bluz71** [comment]
After much experimentation I conclude that thin strokes does not work on Big Sur no matter what I do. I was mistaken a few posts up that I got it too work. My eyes tricked me. I am very sorry, I was an unreliable narrator.

My best workaround was to build a custom version of my preferred Iosevka font with 350 weight vs the default of 400 weight (aka regular). That gives me the thinness I want without fighting the OS. Looks excellent to me.

Use a thinner font, that's the solution I now believe.

I think Alacrity should get rid of use thin fonts since it only works for a small band of macOS versions. And it is not applicable to Linux and Windows.

**Comment by invis87** [comment]
In iTerm `use this strokes for anti-aliased text` is still present, so it is possible to do the same in Alacritty.

**Comment by invis87** [comment]
[Related code in iTerm2](https://github.com/gnachman/iTerm2/blob/master/sources/iTermGraphicsUtilities.m) - if someone knows how to do something similar...

Also I found some thin related code in Alacritty, but from 2016: [here](https://thc420.xyz/alacritty/commit/874719580ce3e12f09d01a9a53c5e64205ef5b5d.html)

**Comment by chrisduerr** [comment]
Alacritty's current thin strokes code can be found here: https://github.com/alacritty/crossfont/blob/536d5c6685902209b29d86f1de329ccc8ad99f51/src/darwin/mod.rs#L227-L242

**Comment by invis87** [comment]
I think this issue should be reopened

**Comment by bluz71** [comment]
Apple keeps changing it's font subsystem from release to release, that much is obvious.

The iTerm2 solution contains this comment:

```
// This seems to be available at least on 10.8 and later. The only reference to it is in
// WebKit. This causes text to render just a little lighter, which looks nicer.
```

Not exactly an official API. The iTerm2 author stumbled on something, tried it and liked the look (which is fine). But it is not how Apple wants folks to do things (me thinks).

After battling this issue for two weeks, which involved me going bonkers thinking something was working when it actually wasn't, I firmly believe the best solution is to use a thinner font. Fonts like [Iosevka](https://github.com/be5invis/iosevka) provide build script, hence font weight is adjustable for this particular font. So I built myself a thinner font which totally solved this issue.

Alacritty does not provide box drawing because simplicity and maintainability are desired goals.

`use_thin_fonts` seems to be a headache, firstly it is macOS only so probably should be named `mac_use_thin_fonts`, but it only works for High Sierra, Mojave and Catalina (nothing prior and currently nothing latter). Seems a platform specific burden.

I know some folks will want this, but I feel like we are battling against Apple itself.

My 2 cents.

**Comment by chrisduerr** [comment]
> Not exactly an official API. The iTerm2 author stumbled on something, tried it and liked the look (which is fine). But it is not how Apple wants folks to do things (me thinks).

This is something not uncommon to iTerm. Which is why I'd like to point out that this is not something Alacritty will get into. iTerm is a macOS terminal emulator, which is why it is fine to invest significant amounts of time tweaking it specifically for macOS, but Alacritty is not. Should there be a relatively standard process to make this work, then that's perfectly fine.

> After battling this issue for two weeks, which involved me going bonkers thinking something was working when it actually wasn't, I firmly believe the best solution is to use a thinner font.

If your goal is just to adjust the font weight, then any of this configuration is completely misguided really. This option is for subjectively improved text rendering on lower DPI displays, thinner fonts are just a side effect.

> use_thin_fonts seems to be a headache, firstly it is macOS only so probably should be named mac_use_thin_fonts, but it only works for High Sierra, Mojave and Catalina (nothing prior and currently nothing latter). Seems a platform specific burden.
>
> I know some folks will want this, but I feel like we are battling against Apple itself.

These are pretty much my thoughts on the matter too. I think eventually we'll probably just end up going the way of removing this option, since there's little benefit and macOS doesn't seem like they are particularly interested in providing this feature. With high DPI monitors, as provided by many macOS systems, it should only become less and less relevant over time. For people that did not understand the purpose of this option and used it solely to change the font's thickness, there should be plenty of other fonts out there to choose from (or they can modify the font itself).

**Comment by mcmillion** [comment]
I totally get that this is a pain to handle, especially with Apple changing stuff every major release.

Ironically enough, kitty has similar struggles but in the other direction for me (fonts look fine on low-DPI displays and terrible on Retina).

**Comment by DrGo** [comment]
I switched to Fira Code Light. I  tried Fantasque Sans Mono, Roboto, Go Mono, Iosevka, Hack and few others but  nothing  worked  as well as  Fira Code Light. I am on Big Sur 11.2.3 using 2014 Thunderbolt monitor.

**Comment by bluz71** [comment]
Nothing will get me to change from [Iosevka](https://github.com/be5invis/Iosevka). I just simply hacked the `private-build-plans.toml` build script and added a thin variant as such:

```
    [buildPlans.iosevka-custom.weights.light]
    shape = 350
    menu  = 300
    css   = 300
```

Then it is just a matter of building the font.

And in my `alacritty.yml` I have these font settings:

```
font:
  normal:
    family: Iosevka Custom
    style: Light

  bold:
    family: Iosevka Custom
    style: Light

  italic:
    family: Iosevka Custom
    style: Light Italic
```

That gets me the exact thin strokes style I like on Mac.

**Comment by dalizard** [comment]
I also tried to adjust the font weight by following all suggestions above (I am using Menlo Regular, size 13), but I was unable to get a thinner stroke. I am running macOS Big Sur 11.2.3 and alacritty 0.7.2 (5ac8060).
![Terminal Emulators](https://user-images.githubusercontent.com/148763/114991432-3c63dc00-9ea2-11eb-8eba-660f5ce2c7df.png)
Because the rest of the terminals don't exhibit this rendering behavior, I wonder what might be the actual cause of this 🤔

**Comment by ousatov-ua** [comment]
Hi there!

If anyone is interested, I "fixed" it just using Roboto Mono Nerd Fond Light. It looks really sharp without blur. For sure 'clean' Roboto Mono can be used.
Here is my config:

`# Font configuration
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas
    family: RobotoMono Nerd Font Mono

    # The `style` can be specified to pick a specific face.
    style: Light

  # Bold font face
  bold:
    # Font family
    #
    # If the bold family is not specified, it will fall back to the
    # value specified for the normal font.
    family: RobotoMono Nerd Font Mono

    # The `style` can be specified to pick a specific face.
    style: Regular

  # Italic font face
  italic:
    # Font family
    #
    # If the italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: RobotoMono Nerd Font Mono

    # The `style` can be specified to pick a specific face.
    style: Light Italic

  # Bold italic font face
  bold_italic:
    # Font family
    #
    # If the bold italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: RobotoMono Nerd Font Mono

    # The `style` can be specified to pick a specific face.
    style: Italic

  # Point size
  size: 14.0

  # Offset is the extra space around each character. `offset.y` can be thought
  # of as modifying the line spacing, and `offset.x` as modifying the letter
  # spacing.
  offset:
    x: -3
    y: 16

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the
  # right, increasing `y` moves the glyph upward.
  glyph_offset:
    x: 0
    y: 7

  # Thin stroke font rendering (macOS only)
  #
  # Thin strokes are suitable for retina displays, but for non-retina screens
  # it is recommended to set `use_thin_strokes` to `false`.
  use_thin_strokes: true
`

Roboto mono fonts:

https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/RobotoMono

**Comment by puremourning** [comment]
For anyone who is hitting this and (like me) prefers the way iTerm renders this you can get the fonts to render "thin" and look good on retina displays with this change in the crossfont repo:

```diff
ben@BeniMac2020 crossfont % git diff
diff --git a/src/darwin/mod.rs b/src/darwin/mod.rs
index aded7a7..9a0f84f 100644
--- a/src/darwin/mod.rs
+++ b/src/darwin/mod.rs
@@ -445,10 +445,13 @@ impl Font {
 
         if use_thin_strokes {
             cg_context.set_font_smoothing_style(16);
+            cg_context.set_allows_font_smoothing(false);
+            cg_context.set_should_smooth_fonts(false);
+        } else {
+            cg_context.set_allows_font_smoothing(true);
+            cg_context.set_should_smooth_fonts(true);
         }
 
-        cg_context.set_allows_font_smoothing(true);
-        cg_context.set_should_smooth_fonts(true);
         cg_context.set_allows_font_subpixel_quantization(true);
         cg_context.set_should_subpixel_quantize_fonts(true);
         cg_context.set_allows_font_subpixel_positioning(true);
```

**Comment by iloveitaly** [comment]
@puremourning is there a reason we can't submit this diff as a PR against the crossfont repo?

**Comment by puremourning** [comment]
Only that doing so requires actually fully testing it against all the probably real situations. This "works for me" as it stands, I haven't tested it on different screen types on different macOS versions.

**Comment by philip1987** [comment]
@puremourning I'd like to try out your workaround. How did you go about patching crossfont and building a modified version of alacritty?

I tried the following which didn't work:
- cloned the alacritty and crossfont repo and applied your changes to mod.rs
- In alacritty/alacritty/Cargo.toml I added:
```
[patch.crates-io]
crossfont = { path = "$HOME/Code/crossfont" }
```
- Then I built alacritty with 'make app'

Could you point me in the right direction? Alternatively, could you push your changes to your fork of Alacritty I and others that are interested could replicate your workaround?

**Comment by dangh** [comment]
@philip1987 did you try keeping `force_system_fontconfig` feature?
I only replaced `version` with `path` and compile the app with `make dmg` which I found in the this repo's github action.

**Comment by dangh** [comment]
@philip1987 patching non root package will not working.

```sh
$ cargo test --release
warning: patch for the non root package will be ignored, specify patch at the workspace root:
package:   /Users/dang/Desktop/src/alacritty/alacritty/Cargo.toml
workspace: /Users/dang/Desktop/src/alacritty/Cargo.toml
    Finished release [optimized + debuginfo] target(s) in 0.08s
     Running unittests (target/release/deps/alacritty-abf26233c9be56a7)
```

You may want to set the path in the dependencies section instead.

**Comment by puremourning** [comment]
I put this in `.cargo/config.toml` under `alacritty`:

```
paths = [ "../crossfont", "../winit" ]
```

in `../winit` I have this commit:

```
commit 43580969341fce3be1cc76ab3593f544cf370b8c (HEAD -> master, pm/master)
Author: Ben Jackson <puremourning@gmail.com>
Date:   Fri Jun 18 16:13:39 2021 +0100

    Autohide dock and menu bar, rather than make it impossible to exit fullscreen

diff --git a/src/platform_impl/macos/window_delegate.rs b/src/platform_impl/macos/window_delegate.rs
index d77c8957..f657363c 100644
--- a/src/platform_impl/macos/window_delegate.rs
+++ b/src/platform_impl/macos/window_delegate.rs
@@ -496,8 +496,8 @@ extern "C" fn window_will_use_fullscreen_presentation_options(
     // we don't, for consistency. If we do, it should be documented that the
     // user-provided options are ignored in exclusive fullscreen.
     (NSApplicationPresentationOptions::NSApplicationPresentationFullScreen
-        | NSApplicationPresentationOptions::NSApplicationPresentationHideDock
-        | NSApplicationPresentationOptions::NSApplicationPresentationHideMenuBar)
+        | NSApplicationPresentationOptions::NSApplicationPresentationAutoHideDock
+        | NSApplicationPresentationOptions::NSApplicationPresentationAutoHideMenuBar)
         .bits()
 }
```

In `../crossfont` I have this commit:

```
commit 3d0d7385d07277aa8c4b156555280523e90cba09 (HEAD -> master, pm/master)
Author: Ben Jackson <puremourning@gmail.com>
Date:   Mon Jun 14 17:21:59 2021 +0100

    Actually disable font smoothing when thin_strokes is enabled

    MacOS Big Sur changed font smoothing in some strage way, apparently
    disabling it at the OS level. Or something. It's hard to get clear
    information on this, but by _enabling_ font smoothing we end up with fat
    over-bright/high contract characters on MacOS.

    So to actually get thin fonts, enable anti-aliasing but disable font
    smoothing. This works for me(TM), and makes alacritty look like iTerm
    and Terminal.app.

diff --git a/src/darwin/mod.rs b/src/darwin/mod.rs
index aded7a7..9a0f84f 100644
--- a/src/darwin/mod.rs
+++ b/src/darwin/mod.rs
@@ -445,10 +445,13 @@ impl Font {

         if use_thin_strokes {
             cg_context.set_font_smoothing_style(16);
+            cg_context.set_allows_font_smoothing(false);
+            cg_context.set_should_smooth_fonts(false);
+        } else {
+            cg_context.set_allows_font_smoothing(true);
+            cg_context.set_should_smooth_fonts(true);
         }

-        cg_context.set_allows_font_smoothing(true);
-        cg_context.set_should_smooth_fonts(true);
         cg_context.set_allows_font_subpixel_quantization(true);
         cg_context.set_should_subpixel_quantize_fonts(true);
         cg_context.set_allows_font_subpixel_positioning(true);
```

I then just build Alacritty (I think).

**Comment by philip1987** [comment]
I have managed to get it to work, thank you @puremourning & @dangh!
I cloned @puremourning's repo's and added .cargo/config.toml as per his instructions, excellent work on his behalf!

```
git clone https://github.com/puremourning/alacritty.git
git clone https://github.com/puremourning/winit.git
git clone https://github.com/puremourning/crossfont.git
mkdir ./alacritty/.cargo && touch config.toml
echo 'paths = [ "../crossfont", "../winit" ]' >> ./alacritty/.cargo/config.toml
```

Now the "use_thin_strokes" option in alacritty.yml actually renders the font thinner.
A note: To see changes in the "use_thin_strokes" option Alacritty has to be quit and restarted.

On the left you can see the official build and on the right a build with @puremouring's tweaks applied:

![AlacrittyThinStrokes](https://user-images.githubusercontent.com/58528488/127542466-7ea3f942-6cf4-4fbb-b3cf-fdcf89832e41.jpg)

**Comment by philip1987** [comment]
I am aware that this is only a temporary and probably very fragile fix. I also doubt it will find its way to the official repo, but for now it works.
I really like the Alacritty project, but it seems MacOS is not its main focus, which is totally ok. In return we get a performant terminal with a maintainable code base. It just means that sometimes we need to find workarounds or live with some minor issues such as the very one discussed here.
Next up, I'd like to find a workaround to enable macos native background blur as referenced in #972 using [NSVisualEffectView](https://developer.apple.com/documentation/appkit/nsvisualeffectview), probably by tweaking winit a bit further...

**Comment by dahmc** [comment]
Oh I would love to have that in the official repo. It’s more and more HiDPi screens now and it looks so much better with the thin ones

**Comment by bluz71** [comment]
Thin fonts rendering, generally, is more useful for low DPI screens than high.

A couple points:

- 1) Use of a thinner font totally solves this issue. That has been and will remain the best solution.

- 2) Apple does not provide a stable API to achieve the thin fonts look. The iTerm2 implementation uses a buried-treasure discovery that Apple seems want to change from certain OS release to the next.

- 3) This is a Mac only feature that goes somewhat against the cross platform nature of Alacritty. At this point, a year after I created this request, I am of the belief that Alacritty should just remove `use_thin_strokes` completely since it doesn't work for Mac OS releases prior to High Sierra (2017) and releases later than Catalina (10.15 / 2019).

My 2cents.

**Comment by chrisduerr** [comment]
> This is a Mac only feature that goes somewhat against the cross platform nature of Alacritty. At this point, a year after I created this request, I am of the belief that Alacritty should just remove use_thin_strokes completely since it doesn't work for Mac OS releases prior to High Sierra (2017) and releases later than Catalina (10.15 / 2019).

I have to say I mostly agree with this point. In the past thin strokes used to work somewhat reliably until Apple broke it in one of their updates. Then we had to introduce a workaround to make it work every once in a while. Another update later you're lucky if it works at all.

It's really just not worth the effort anymore especially since most modern Apple devices are HiDPI and this setting was made for low DPI displays.

**Comment by chrisnc** [comment]
For anyone following this issue, you can get thin strokes on latest Alacritty and macOS now, you just need to use:

```
$ defaults write -g AppleFontSmoothing -int 0
```

The `use_thin_strokes` config field has been removed as discussed above.

If you still want smoothing (read: slightly bolder fonts) for the rest of the system, but not in Alacritty, you can do `org.alacritty` instead of `-g` in the above command. Personally I think it's much nicer on everything and would suggest people give it a try if they haven't before. (It requires a restart to take effect for the whole system, but Alacritty just needs to be relaunched for it to take effect, as it reads the default when loading fonts.)

The patches earlier in the thread are no longer necessary.
