### ISSUE TITLE
Decorations set to "none" mouse copy issue MacOS

### ISSUE THREAD

**Issue by GNOMES** [alacritty/alacritty#4629]
OS: macOS
Version: alacritty 0.6.0 (04cbf76)

Font/Terminal size: Source Code Pro, size 10
Keyboard and bindings: `alacritty --print-events`

Currently have the goal of sharing one alacritty.yml config file between my Mac and Linux machines. As such I am trying to us the "none" decoration option instead of the Mac only buttonless setting.

When using the mouse to copy text that is near the top of the terminal window, I am finding that it will sometimes trigger the resize arrows. 

Is there a way to disable sizing ability when opened maximized(not full screen)?

**Comment by chrisduerr** [comment]
Disabling the ability to resize the window seems like a very strange fix to your specific issue.

However we do have plans to maybe allow for more granular padding configuration (#4297) which could likely help with your issue.
