### ISSUE TITLE
Build against latest LLVM master

### ISSUE THREAD

**Issue by shoober420** [alacritty/alacritty#4638]
### System

OS: Obarun Linux 64bit
Version: alacritty 0.7.0-dev (1723e30d)
Linux/BSD: Wayland/Sway - wlroots

### Logs

Crashes: rustc: error while loading shared libraries: libLLVM-11.so: cannot open shared object file: No such file or directory

Please allow alacritty to be built again development builds of LLVM (git master). I have the following LLVM libs on my machine.

libLLVM-12.so
libLLVM-12git.so

Can you allow building against those libs?

**Comment by chrisduerr** [comment]
> Can you allow building against those libs?

No.
