### ISSUE TITLE
cant pass arguments on -e command

### ISSUE THREAD

**Issue by simone-sanfratello** [alacritty/alacritty#4642]
Hello,

using `-e` flag to start a new terminal running a command, it works fine

```bash
alacritty -e node
```

but trying to pass arguments, it get an error, looks like it considers arguments as part of the exec

```bash
alacritty -e "node -v"
```

> [2021-01-01 13:04:36.811940112] [ERROR] [alacritty_terminal] Failed to spawn command 'node -v': No such file or directory (os error 2)
Created log file at "/tmp/Alacritty-57937.log"

### System

OS: Ubuntu 20.04
Version: 0.6.0

**Comment by chrisduerr** [comment]
Yeah, just run `alacritty -e node -v`.
