### ISSUE TITLE
Weird 

### ISSUE THREAD

**Issue by homosacer** [alacritty/alacritty#4648]
I'm facing some wierd visual bugs when working with dart files.

##1 the cursor and line are incorrect
![image](https://user-images.githubusercontent.com/76230887/103460544-00ff3080-4d3d-11eb-9cab-27d7e6ece1ce.png)
Note that I didn't resize the window. Also, the actual selected linecursor position is  is the one directly above where the cursor is displaying

##2 When scrolling inside a split, the splits above get rekt
To reproduce:
1. Make a split
![image](https://user-images.githubusercontent.com/76230887/103460576-458acc00-4d3d-11eb-9bce-cb96526f1f9b.png)
2. Scroll down in the bottom split
![image](https://user-images.githubusercontent.com/76230887/103460589-5fc4aa00-4d3d-11eb-8f21-a8cea47e6846.png)
To exaggerate the issue, this is what happens when I scroll another 5-10 times:
![image](https://user-images.githubusercontent.com/76230887/103460598-78cd5b00-4d3d-11eb-852f-30661881df53.png)
I havent changed anything, just scrolled down.

At first I was tempted to think that this might be an issue with my Plugins rather than alacritty. But the aforementioned issue doesnt occur on Windows Terminal, Powershell or Command Prompt. Hence, I'm betting it's due to alacritty 
### System

OS: Windows
Version: alacritty 0.6.0 (04cbf76)

**Comment by chrisduerr** [comment]
Is your system up to date? You probably need to update your Windows or wait for the latest ConPTY to propagate to windows updates.

**Comment by homosacer** [comment]
It's fairly up-to date, I had done a clean install of the latest stable windows version within last month. And then also run Windows update in all its glory last week.
Also, if it were an issue with the PTY, wouldn't it have affected other terminals as well ? (Curious, I borderline don't know about PTY whatsoever)

**Comment by chrisduerr** [comment]
> Also, if it were an issue with the PTY, wouldn't it have affected other terminals as well

No, because Windows Terminal ships their own version of the PTY because they're fully aware that the version of the PTY they ship with their operating system is completely unusable.

Do you have access to a Linux machine to test this? Most Windows issues are just Windows doing its thing, so if it can be reproduced on Linux it's probably an issue with Alacritty. But I doubt it would reproduce on Linux.

**Comment by homosacer** [comment]
> Do you have access to a Linux machine to test this? Most Windows issues are just Windows doing its thing, so if it can be reproduced on Linux it's probably an issue with Alacritty. But I doubt it would reproduce on Linux.

This is a windows-specific problem. Alacritty works flawlessly on macOS and Arch.
