### ISSUE TITLE
[Documentation] Add a subsection "how to start alacritty"

### ISSUE THREAD

**Issue by rubyFeedback** [alacritty/alacritty#4649]
Hey alacritty devs,

First time user. I have no experience in rust. Using linux.
Read about it on a blog. :-)

Went to try it out.

The documentation has:

    Installation
    Configuration

Installation is easy; it worked via cargo.

But now ... how to start it?

I assume it is "alacritty". I don't know for certain though.

Could a new, short subsection been added between installation and configuration please,
how to start it? I want to start it via "xterm -e alacritty", but a documented example would
be very useful to have IMO for newcomers. (I actually want to embed this into tabble,
which you can see here: http://www.rillion.net/tabble/index.html this is why I use
xterm -e in general but I'd love to know beforehand whether that can work; not sure
if this makes sense, but I'd love to see this included into the main README.)

**Comment by chrisduerr** [comment]
You start Alacritty like every other application. If you don't know how to start applications, you should probably look into far more basic documentation that Alacritty's.
