### ISSUE TITLE
Colors defined in dialogrc not rendered correctly

### ISSUE THREAD

**Issue by xexpanderx** [alacritty/alacritty#4653]
I tried rxvt-unicode (256 color), xfce4-terminal and xterm, all these terminal renders the colors correctly in dialogrc.

However, alacritty, does not (I believe it does not render highlighting correctly).

This is how it is supposed to look like (sbopkg in Slackware as exempel running in urxvt).
![Screenshot_2021-01-03_00-29-55](https://user-images.githubusercontent.com/10048240/103486450-b0540a00-4e06-11eb-8ea8-43e7639f0f97.png)

This is how it looks in alacritty:
![Screenshot_2021-01-03_21-00-20](https://user-images.githubusercontent.com/10048240/103486473-d4afe680-4e06-11eb-97c0-642abe3d17bc.png)

**Comment by chrisduerr** [comment]
Probably just assumes that bold is bright, which should not be assumed. The application should be fixed, there's nothing wrong with Alacritty's color rendering.

**Comment by xexpanderx** [comment]
`dialog --colors --title 'Message' --msgbox "HELLO WORLD" 5 20`

That code renders a black background in alacritty, and HELLO WORLD does not show up as it should (since highlighting is not rendered correctly).
