### ISSUE TITLE
Double parentheses not rendered

### ISSUE THREAD

**Issue by theodore-s-beers** [alacritty/alacritty#4657]
### System

OS: macOS 11.1
Version: alacritty 0.6.0 (04cbf76)

### Description

This is obscure, but I noticed when running `npm doctor` in Alacritty that parts of the progress bar weren't rendered. In particular, they use ⸨ left and right ⸩ double parentheses to bracket the bar. The code points are 2e28 and 2e29, respectively. I can't get these characters to appear in Alacritty at all, with any font. In Terminal.app, with any of the same fonts (e.g. Menlo), ⸨ and ⸩ appear correctly.

I have not experienced other issues of this kind with Alacritty. All manner of exotic characters come out fine. This seems to be a rather specific problem.

To test this, one could enter the commands `printf '\xe2\xb8\xa8\n'` and `printf '\xe2\xb8\xa9\n'`. (That should work in pretty much any shell. The newlines are just to keep things tidy.)

My apologies if I've missed something obvious. Thank you, in any case, for your work on this project.

**Comment by chrisduerr** [comment]
What do you mean by "they don't appear at all"? Do they show missing glyph symbols?

**Comment by theodore-s-beers** [comment]
Sorry, let me add a couple of screenshots. In 0.6.0, I don't see anything at all where the character (here left double parenthesis) should be.

<img width="193" alt="0.6.0" src="https://user-images.githubusercontent.com/32523293/103517039-c814a800-4e71-11eb-89f7-fee2ddb446ca.png">

I also built 0.7.0-dev (08e111d) from source and tried there. It shows a gray box.

<img width="193" alt="0.7.0" src="https://user-images.githubusercontent.com/32523293/103517100-e67aa380-4e71-11eb-8edf-b526ba3bacdb.png">

I wanted to make it clear that I'm not seeing a problem with other characters from the same Unicode block.

**Comment by chrisduerr** [comment]
Yeah, everything working as intended then. That's just the missing glyph box, which shows up whenever you don't have a font for a glyph.

**Comment by theodore-s-beers** [comment]
@chrisduerr, there is a macOS preinstalled font that has glyphs for left and right double parenthesis: Geneva. I guess that's what Terminal.app is falling back to:

<img width="195" alt="Terminal" src="https://user-images.githubusercontent.com/32523293/103526855-cb179480-4e81-11eb-8a4f-64281f64e193.png">

Same with iTerm2:

<img width="195" alt="iTerm2" src="https://user-images.githubusercontent.com/32523293/103526887-d23ea280-4e81-11eb-8108-87f69841c599.png">

Is there something different about Alacritty that would explain its placement of a missing glyph box here? e.g., does it only fall back to fixed-width fonts? I found that if I actually set Geneva in `alacritty.yml`, the glyph appears:

<img width="243" alt="Geneva" src="https://user-images.githubusercontent.com/32523293/103528699-b12b8100-4e84-11eb-84de-96b17e089f84.png">

I remain confused about this, given Alacritty's ability to locate fonts for other uncommon characters.

Anyway, now that this issue is closed, I mostly wanted to round out my documentation of the behavior I'm seeing, in case someone else searches and stumbles upon it later.

**Comment by chrisduerr** [comment]
A font might be reporting that it contains the font but doesn't, or it might just not be recognized by core-text's fallback stack. Either way there's not much Alacritty can or should do about it.

**Comment by theodore-s-beers** [comment]
I'm now pretty confident the issue is that it won't render a glyph if it's found only in proportional fonts. I eventually noticed that "very limited support for proportional fonts" is acknowledged as a feature of the crossfont library. Which is fine. It's good just to have figured this out.

It's remarkably difficult to find a fixed-width font that has glyphs for the double parentheses in question. I may suggest to the people at NPM that they choose something different for the progress bar that originally sent me down this rabbit hole. Thanks again.

**Comment by chrisduerr** [comment]
> I'm now pretty confident the issue is that it won't render a glyph if it's found only in proportional fonts.

That's definitely not accurate.

**Comment by theodore-s-beers** [comment]
Ok. Thank you for your encouragement to go back to the drawing board. I ended up forking crossfont, and added the following snippet to `src/darwin/mod.rs`, just after the same is done for "Apple Symbols":

```rust
if let Some(descriptor) =
    descriptors_for_family("Geneva").into_iter().next()
{
    fallbacks.push(descriptor.to_font(size, false))
};
```

This solves my problem. Maybe something about the way Alacritty handles fallbacks/the cascade list doesn't yield quite the same coverage as the native macOS approach. But I'm past my depth to do any more than add a janky fix for myself.

**Comment by chrisduerr** [comment]
> quite the same coverage as the native macOS approach

This is the native macOS approach.

**Comment by theodore-s-beers** [comment]
Well, I must not be referring to things in the right way. Hopefully the discussion at issue #2800—which I just found is still open and apparently similar—will be more fruitful.

**Comment by chrisduerr** [comment]
Yeah, #2800 seems like a good place to track this, though I don't expect any changes in the near future. As far as I can tell our macOS font fallback is somewhat standard core-text stuff, so one would probably have to dig around a bit. And I'm personally not interested in spending that much time with macOS.
