### ISSUE TITLE
Unable to find fonts i have installed

### ISSUE THREAD

**Issue by A1ex-N** [alacritty/alacritty#4658]
When i try to set my font to BlexMono NF i get this error

**[ERROR] [alacritty] Unable to find the font BlexMono NF - Regular**

I don't have this problem with any other program, they can load the font just fine.

### System

OS: Windows
Version: alacritty 0.6.0 (04cbf76)

**Comment by chrisduerr** [comment]
Have you tried different variations of the name? Like `Blex Mono NF` or `Blex Mono`?

**Comment by A1ex-N** [comment]
> 
> 
> Have you tried different variations of the name? Like `Blex Mono NF` or `Blex Mono`?

I have, and it makes no difference, I get the same error. Also it gives me the same error when i try to load LiberationMono NF too.

**Comment by chrisduerr** [comment]
What font format does it use and how is it installed? We just use DirectWrite for loading fonts, so either you picked the wrong name or Windows can't find the font.

**Comment by A1ex-N** [comment]
I downloaded it from here: https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/IBMPlexMono/Mono/complete, opened the downloaded file and clicked "install".

The font works fine in Windows Terminal, cmd.exe, the WSL terminal, everything except alacritty. In the windows terminal i enter "BlexMono NF" for the font face and it works, so it can't be the wrong name.

**Comment by chrisduerr** [comment]
> In the windows terminal i enter "BlexMono NF" for the font face and it works, so it can't be the wrong name.

I don't see how that would be the case? It might be looking for fonts with similar names, while Alacritty doesn't.

You've restarted Alacritty after installing the font, right?

**Comment by A1ex-N** [comment]
Yes, i've had the font installed for a long time. Also i've just reinstalled the font and still getting the error.

**Comment by A1ex-N** [comment]
Oh, i just removed the "style" and now it's working. Could have sworn i've done that in the past. My bad i guess

**Comment by chrisduerr** [comment]
Oh yeah, I was going to mention that the default style is called `Book` and not `Regular` I think.
