### ISSUE TITLE
Regression: blank lines after each line when pasting from Wayland GTK applications

### ISSUE THREAD

**Issue by alxckn** [alacritty/alacritty#4661]
If I copy/paste from sublime text or gedit, I have new lines inserted in between each line.
![image](https://user-images.githubusercontent.com/11556013/102468779-41c72c00-4052-11eb-9ece-01b040b68ef5.png)
becomes
![image](https://user-images.githubusercontent.com/11556013/102468838-53a8cf00-4052-11eb-9d6d-41ae0918e4b4.png)

This problem was raised in https://github.com/alacritty/alacritty/issues/2844 previously and fixed at the time as I tried alacritty v0.4.3 and couldn't reproduce the issue.
The associated [pull request](https://github.com/alacritty/alacritty/pull/3000) fixed the problem at the time by bumping the version of smithay-clipboard to 0.3.6 to include [this fix](https://github.com/Smithay/smithay-clipboard/pull/9).

Some heavy refactoring has happened since then, notably in this [commit](https://github.com/Smithay/smithay-clipboard/commit/bb652c775b8226e55a22437476bcf45bffb5ed6c).
It may be where the regression happened, or is it a breaking change in API? Please let me know if I should open the issue on smithay-clipboard repo instead or in addition to this one.

### System

OS: Linux (Fedora 32)
Version: 0.5.0 and up
Linux/BSD: Wayland, Gnome 3.36.0

**Comment by chrisduerr** [comment]
Can you bisect which exact commit broke this?

**Comment by alxckn** [comment]
Sure thing: 0f82817c03ebb0f26f3423bbcd48e527ab138cc2 is the first bad commit

**Comment by Yuttana12wr** [comment]
@yuttana

**Comment by ratheesh** [comment]
I observe this issue even with the windows version.

**Comment by chrisduerr** [comment]
Can someone on Wayland confirm that this is still an issue?

**Comment by nixpulvis** [comment]
I'm on Wayland, and just installed `gedit` to test this. I cannot reproduce this.

**Comment by alxckn** [comment]
I can confirm this is still an issue. Tested with 0.7.1 and 0.8.0-dev (9999bd5).

**Comment by chrisduerr** [comment]
@alxckn Can you provide some more information? You're copying from `gedit` and pasting into Alacritty, right? Are you pasting in the shell, if so which one? Or an editor or something? Can you reproduce this on multiple Wayland DEs, or have you tried just one?

**Comment by alxckn** [comment]
@chrisduerr I am only using wayland with gnome on a daily basis (fedora 32). From there, I consistently reproduce this issue with gedit or sublime text, pasting into bash or zsh, but it works fine with Firefox for instance.

I just installed sway on another computer and wasn't able to reproduce the issue with that setup.

**Comment by chrisduerr** [comment]
> I just installed sway on another computer and wasn't able to reproduce the issue with that setup.

Thanks for the info, so it must be gnome specific. Can you reproduce this with weston?

**Comment by alxckn** [comment]
> Can you reproduce this with weston?

@chrisduerr No I cannot reproduce the bug with weston either

**Comment by kchibisov** [comment]
I can't repro this issue, so I guess I'd need `WAYLAND__DEBUG=1 alacritty` log from you here.

**Comment by chrisduerr** [comment]
@kchibisov Have you tested on GNOME? It cannot be reproduced on Sway.

**Comment by alxckn** [comment]
@chrisduerr, @kchibisov thanks a lot for your investigations, the bug has been fixed with the 0.7.2 release it seems, I can't reproduce the issue with both gedit and sublime text on that version.

Sorry I didn't notice earlier, I didn't think this had been fixed based on this open issue and I had gotten used to working my way around it.
