### ISSUE TITLE
Error on alacritty.plab_norm

### ISSUE THREAD

**Issue by AurevoirXavier** [alacritty/alacritty#4668]
### System

OS: Archlinux
Version: 0.6.0
Desktop: KDE

### Logs

```rust
Error on alacritty.plab_norm:
"%t;7%;%?%p4%t;5%;%?%p7%t;8%;m"

var v,
 stack = [],
 out = [];
) {out.push(";
7")};
if ((stack.push(v = params[3]),
 v)) {out.push(";
5")};
if ((stack.push(v = params[6]),
 v)) {out.push(";
8")}out.push("m");
return out.join("");
```

### Reproduce

Simply run `pm2 monit`

**Comment by chrisduerr** [comment]
If an application throws an error, please report it to the application throwing that error.

**Comment by AurevoirXavier** [comment]
> If an application throws an error, please report it to the application throwing that error.

But it works perfectly in yakuake/guake/konsole.

**Comment by chrisduerr** [comment]
It is.
