### ISSUE TITLE
make url styling optional

### ISSUE THREAD

**Issue by dicktyr** [alacritty/alacritty#4669]
please enable configuration of url styling
to simply disable it entirely or specify color/underline/...

links are easy to identify without extra decoration
and once one knows the terminal recognises them
the decoration becomes superfluous and distracting
(not to mention the consumption of system resources ;)

**Comment by chrisduerr** [comment]
I see no reason to add extra configuration options just to disable this functionality.

**Comment by dicktyr** [comment]
and I see no reason to enforce superfluous/distracting formatting
or am I missing something (I did search)?

**Comment by chrisduerr** [comment]
You're not. URLs are underlined and the cursor shape is changed, that's a simple UX thing. If you don't like it, you can compile from master with minimal patching required.

**Comment by dicktyr** [comment]
> You're not

thanks for the comfirmation

> a simple UX thing

like Apple's one-button mouse, perhaps...
fortunately, things change

similar arguments promote beveled edges and so on
and I do acknowledge their utility to be sure
but such utility is transient: a learning aid
much like training wheels on a bicycle
(i.e. it's quite reasonable that they be optional
easily removed or attached as need be)

that may not be apparent now
but I reckon it will be one day :}
