### ISSUE TITLE
macOS: Touch Bar Support

### ISSUE THREAD

**Issue by PerpetualCreativity** [alacritty/alacritty#4684]
Currently, Alacritty doesn't put anything on a MacBook Touch Bar. This means I can't access the function keys unless I press the Fn key, which is less than ideal.

As an extension of this, there could be macOS specific `key_binding`s that allows users to define their own custom Touch Bar buttons to trigger an action.

*(This is definitely not a high priority issue.)*

**Comment by chrisduerr** [comment]
I have no intention to add any code that does anything with the touchbar.

**Comment by bak1an** [comment]
@PerpetualCreativity in mac os keyboard settings (shortcuts part of it) you can set a list of apps that display F keys all the time: 
<img width="655" alt="Screenshot 2024-06-08 at 19 18 19" src="https://github.com/alacritty/alacritty/assets/242988/3c57c5c9-3b3a-4539-9f2e-ec0867f3bb6b">
