### ISSUE TITLE
It's unclear how to set dimensions and position via --option

### ISSUE THREAD

**Issue by sudo-nice** [alacritty/alacritty#4686]
iAfter the `--position` and `--dimensions` CLI arguments were [removed,] it's unclear, how to set these options via `--option` argument. The scarce `alacritty --help` example was not really helpful. E.g., to set dimensions I tried the variants:
```
alacritty --option dimensions.columns=80 --option dimensions.lines=24
alacritty --option dimensions.columns=80,dimensions.lines=24
alacritty --option dimensions='80 24'
```
Nothing of the above worked for me. Now, I'm uncertain, whether it's me being wrong with the `--option` format, or the dimensions and position functionality was broken along the way.

---
OS: Linux
Version: `alacritty 0.7.1-rc1`
Linux: X11

[removed,]: https://github.com/alacritty/alacritty/pull/4478/commits/bee5f9ffd60df4594843ee4d3f4b76c3e2d10fb8

**Comment by chrisduerr** [comment]
It's `window.dimensions.column`, not just `dimensions.column`, just like it is documented in the configuration file.

**Comment by sudo-nice** [comment]
Thank you for the reply.
Following your suggestion, I tried:
`alacritty --option window.dimensions.columns=80 --option window.dimensions.lines=24`
But it didn't work either.

**Comment by chrisduerr** [comment]
This should work just fine:

```
alacritty --option window.dimensions.columns=30 --option window.dimensions.lines=30
```

Make sure your window manager isn't messing with Alacritty's size. This size is just a suggestion to the WM, it is free to ignore it. Which WM do you use?

**Comment by sudo-nice** [comment]
Oh, it actually worked (even with your previous suggestion), my bad.

As a personal impression, I find the former style more appropriate for CLI, previously you could grasp the arguments really quickly, but now it's a mess, IMO:
```
# previously
alacritty --dimensions 90 90 --position 900 900
# now
alacritty --option window.dimensions.columns=90 --option window.dimensions.lines=90 --option window.position.x=900 --option window.position.y=900
```

Thank you for your help anyway!
