### ISSUE TITLE
Is it possible to make mouse right click behavior just like windows powershell?

### ISSUE THREAD

**Issue by xchern** [alacritty/alacritty#4690]
I think a consistent behavior can make the switching between different consoles more smooth. But I have difficulties to make the right click work as powershell, which is frequently used to copy and paste in my workflow.

The behavior in powershell is like this:
1. When some text selected, right click copys the selected text and clear the selection.
2. When no text selected, right click pastes the clipboard into terminal.
Currently, I can bind copy or paste to right click, but I've no idea how to combine these behaviors.

Another inconsistency is, when a long line displayed as multiple lines on the screen, selecting these lines and copying in alacritty gets multiple lines depending on how it is displayed. but in powershell the copy is always consistent with the actual output.

I'm not sure if these difference can be elimilated by write a proper config file? Or maybe modifying the source code is nessecery?

**Comment by chrisduerr** [comment]
You can make selections copy to the clipboard automatically and then set right click to paste. Other than that I have no intention to support this.

> Another inconsistency is, when a long line displayed as multiple lines on the screen, selecting these lines and copying in alacritty gets multiple lines depending on how it is displayed. but in powershell the copy is always consistent with the actual output.

This is because of Microsoft's terrible PTY.
