### ISSUE TITLE
tdrop failed to launch alacritty v0.7.1

### ISSUE THREAD

**Issue by eval-exec** [alacritty/alacritty#4691]
tdrop failed to  launch alacritty successfully  after upgrade alacritty from 0.6.0 to 0.7.1,
### System

OS: ArchLinux
Version:alacritty 0.7.1 (a852eb85)
Linux : X11 , Kwin, KDE plasma
```bash
❯ uname -a
Linux mufasa 5.10.6-arch1-1 #1 SMP PREEMPT Sat, 09 Jan 2021 18:22:35 +0000 x86_64 GNU/Linux
```
### Logs
```bash
❯ tdrop alacritty
error: Found argument '-d' which wasn't expected, or isn't valid in this context

USAGE:
    alacritty [FLAGS] [OPTIONS]

For more information try --help
^C
```

### reference
tdrop is "A Glorified WM-Independent Dropdown Creator" : https://github.com/noctuid/tdrop

**Comment by chrisduerr** [comment]
Alacritty doesn't have the `-d` flag anymore, that's to be expected.
