### ISSUE TITLE
GLSL 3.30 run requirement not mentioned in README.md or INSTALL.md

### ISSUE THREAD

**Issue by imabuddha** [alacritty/alacritty#4693]
As the title notes this requirement isn't mentioned anywhere. Alas, after cloning the repo, installing dependencies, & building for ~16 mins, alacritty won't run on Raspberry Pi 4: "GLSL 3.30 is not supported."

_Please_ mention this in either of the .md files so that future potential users will be aware of it before attempting to build/use it.

🙇

### System

OS: Linux, Raspberry OS 32 bit 
Version: n/a
Linux/BSD: X11, LXDE

### Logs

n/a

**Comment by chrisduerr** [comment]
That's a fair point, though on the Raspberry Pi 4 it could be possible to make Alacritty work using panfrost I think.

**Comment by imabuddha** [comment]
@chrisduerr I hadn't heard about panfrost before; perhaps I'll look into it someday. 👍️ 

Meanwhile I guess that I'll check out urxvt or st. Kitty also requires a newer version of GLSL. 🙁

**Comment by chrisduerr** [comment]
Yeah, OpenGL 3.3 was released almost 11 years ago and it's provides a lot of necessary features for many applications. So most applications that build directly against OpenGL will likely have problems running on hardware that doesn't support an 11 year old spec.

**Comment by imabuddha** [comment]
@chrisduerr Yeah, I know that it's a non-profit organization focused on providing inexpensive computing hw & resources for education but I wish that Raspberry Pi had more resources devoted to gpu drivers. It's sad that such an old standard isn't supported.

On a different note, as the many lines scrolled by while building Alacritty I didn't see even one warning. Cheers to the devs! 🎉 Most open source projects I've built in the past few months generate many. I assume this is related to it being written in Rust, which is the next language I plan to learn.
