### ISSUE TITLE
Feature request: Secure Keyboard Entry (macOS)

### ISSUE THREAD

**Issue by minamotorin** [alacritty/alacritty#4695]
### Description

Sometimes we input passwords or other sensitive data through the terminal. However, keylogger can steal a glance your input on Alacritty.app at least in macOS. Terminal.app or iTerm2.app support secure keyboard entry and keylogger cannot steal your passwords. 

You can see how our password will be stolen with using [keycastr](https://github.com/keycastr/keycastr), keystroke visualizer. If you enable secure keyboard entry on Terminal.app or iTerm2.app from leftmost application menu, keycastr will not show your input. But on Alacritty.app, all your input will be shown.

Terminal.app (without tmux) will protect your passwords even if you don't enable secure keyboard entry. But I think it is hard to implement the same feature for third-party applications. I just want to the feature which manually toggle secure keyboard entry like iTerm2.

I usually use Alacritty.app, but I use Terminal.app only when I input passwords. This is very inconvenient.

### How to solve

I know [NSSecureTextField](https://developer.apple.com/documentation/appkit/nssecuretextfield) will realize this. But I don't know the details or other things.

Otehr hint: password forms on web pages will protect your passwords too (with a legitimate browser).

**Comment by chrisduerr** [comment]
I don't see the point in implementing this. It seems mostly focused on pretending to be secure rather than actually providing a sensible security improvement.

If the operating system can't figure out how to make this kind of stuff work for all input like Wayland does, then it should allow toggling it globally at least. So I don't see why one would shove that on the application rather than doing it properly in the operating system itself.

**Comment by OJFord** [comment]
I'm confused - I found this issue while trying to learn how to _disable_ this behaviour... `skhd` 'suddenly' stopped working with:
```
$ skhd -V                                                                                                1
skhd: successfully created pid-file..
skhd: secure keyboard entry is enabled by (13441) 'alacritty'! abort..
```

I get the same result in a new term without having run anything else.
