### ISSUE TITLE
Cannot start Alacritty

### ISSUE THREAD

**Issue by cas1no** [alacritty/alacritty#4700]
When trying to start Alacritty I get the following message.

### System

OS: Windows RDP

### Logs

<img width="333" alt="Untitled" src="https://user-images.githubusercontent.com/44465831/104458374-5a2c5700-55bc-11eb-8d2e-61fdae1a6387.png">

**Comment by chrisduerr** [comment]
Which Windows 10 version are you on?

**Comment by cas1no** [comment]
> 
> 
> Which Windows 10 version are you on?

I'm not on Win10, I'm on Win Server 2012 R2 Standard.

**Comment by chrisduerr** [comment]
Then Alacritty does not support your platform.
