### ISSUE TITLE
Alacritty fails to start in 10bit color mode

### ISSUE THREAD

**Issue by pointshader** [alacritty/alacritty#4703]
I followed the following guide to enable 10bit color on my machine. 10bit color appears to working for other programs, but alacritty fails to start.

 ```
Creating a /etc/X11/xorg.conf.d/30-screensetup.conf with the following
content will give you 10-bit color:

Section "Screen"
  Identifier    "Default Screen"
  Monitor        "Configured Monitor"
  Device         "Configured Video Device"
  #               24 for 8-bit or 30 for 10-bit
  DefaultDepth    30
EndSection

And that's it. DefaultDepth 30 is the crucial line. The reason 30 enables 10-bit color is that R, G, B = 3 colors * 10 bits = 30. 
```
(Guide from https://linuxreviews.org/HOWTO_enable_10-bit_color_on_Linux)

### System

OS: Arch Linux
Version: alacritty 0.7.1 (a852eb85)
Linux/BSD: X11 & i3
Nvidia 3090 with driver 460.32.03

**Comment by chrisduerr** [comment]
How does it fail to start? What error do you get?

**Comment by pointshader** [comment]
### Error
[2021-01-14 05:05:26.680909269] [ERROR] [alacritty] Alacritty encountered an unrecoverable error:
                                                    
                                                    	Error creating GL context; Received multiple errors. Errors: `[NoAvailablePixelFormat, NoAvailablePixelFormat]`

**Comment by pointshader** [comment]
(I was rebooting to go back into 10bit mode as you were responding, @chrisduerr !
I'm not an x11 expert, but what's interesting is that it can't get a PixelFormat, yet in nvidia-smi, `X Screen 0 depth` is recognized as `30`. This is despite the fact that I can't set the gpu to 10bcc in the nvidia-smi interface, as the drop down only support depths of Auto, 6 bpc, and 8 bpc. This is using a 10bit monitor, verified hardware setup in Windows.

**Comment by chrisduerr** [comment]
Can you start other OpenGL programs like glxinfo?

**Comment by pointshader** [comment]
And for clarification, removing the conf file and rebooting resets the reported depth to `24`, and alacritty starts normally. I encountered some sluggishness with other programs running in 10bit mode, so I'll be disabling 10bit for now. So personally, no rush for this issue. But long term, I imagine more users will run into the same problem. 

Shoutouts to all the devs for making such a great terminal emulator!

**Comment by pointshader** [comment]
@chrisduerr glxgears runs just fine. Currently trying to find some image test sequences to specifically test 10bit is actually running, other than the control panel confirmation. Firefox is noticeably sluggish, though.

**Comment by pointshader** [comment]
@chrisduerr Using the gradient test in this [video](https://github.com/jursonovicst/gradient/blob/master/test_sequences/3840x2160/gradient_3840-2160_0-100_yuv444p10_x265.mp4) , confirmed 10bit color is visible, viewing in VLC.

**Comment by piotao** [comment]
Confirmed also on Debian System 11 - with 30bit the same error appars, with 24bit all works as 'normal'.

System:
Desktop: Xfce 4.16.0
Debian GNU/Linux bullseye/sid Kernel: 5.10.0-3-amd64 x86_64
Mobo: ASUSTeK model: PRIME B550-PLUS
CPU: model: AMD Ryzen 9 3900X bits: 64 type: MT MCP 12-Core
NVIDIA GA104 [GeForce RTX 3070]
Display: x11 server: X.Org 1.20.10
resolution: 1: 2160x3840~60Hz 2: 3840x2160~60Hz
OpenGL: renderer: GeForce RTX 3070/PCIe/SSE2 v: 4.6.0 NVIDIA 460.39

**Comment by josuer08** [comment]
This crash is still present up to this day (just wanted to point that out so this doesn't die, this is really frustrating)

**Comment by Connor-GH** [comment]
I am still experiencing the same thing! Same error as the other guy, too!
