### ISSUE TITLE
Error getting alacritty.yml

### ISSUE THREAD

**Issue by aehmgh** [alacritty/alacritty#4704]
I'm having the error: "libEGL warning: DRI2: failed to authenticate" while I'm trying to get alacritty.yml, it recognice the file but it doesn't follow the fields described.

Ubuntu 20.04, VirtualBox with Guest Additions installed. Anyone know how to fix this error?
![Ubuntu_Alacritty](https://user-images.githubusercontent.com/77467481/104670826-516e7a80-56bb-11eb-93c7-13969a64a755.JPG)

**Comment by chrisduerr** [comment]
What do you mean "while I'm trying to get alacritty.yml"? At which point do you actually get the error and from what?

**Comment by aehmgh** [comment]
> What do you mean "while I'm trying to get alacritty.yml"? At which point do you actually get the error and from what?

Hi! When I call alacritty it says it loaded .pym but with error: "libEGL warning: DRI2: failed to authenticate", and it doesn´t load config parameters. But it opens alacritty with original setup. I attached an image with error on it.

**Comment by chrisduerr** [comment]
Define "call alacritty". Also there should not be any `.pym` involved.

**Comment by aehmgh** [comment]
> Define "call alacritty". Also there should not be any `.pym` involved.

For example, I execute in terminal: "alacritty -v" to get verbose, and it says: "Welcome to Alacritty
Configuration files loaded from: "/home/ubuntu/.config/alacritty/alacritty.yml
libEGL warning: DRI2: failed to authenticate"

In my alacritty.yml I have configured background_opacity: 0.9, but its still original opacity when alacritty runs, so it is doesnt getting that config from file.

**Comment by chrisduerr** [comment]
> In my alacritty.yml I have configured background_opacity: 0.9, but its still original opacity when alacritty runs, so it is doesnt getting that config from file.

Because that option doesn't take effect when you're running inside a VM. Do none of the other options work?
