### ISSUE TITLE
Dynamic titles for Alacritty within Cmd-Tab switcher?

### ISSUE THREAD

**Issue by mngyuan** [alacritty/alacritty#4705]
Is there a way to have the different `alacritty` processes have different titles in the Cmd-Tab switcher? I have `dynamic_title` enabled in my `alacritty.yml` but it'd be more useful for me to be able to see which Alacritty.app I'm switching to when I press Cmd-Tab. Right now they both are simply 'Alacritty' even though in Mission Control (^↓) they have dynamic titles.

### System

OS: macOS
Version: `alacritty 0.6.0 (04cbf76)` output

**Comment by chrisduerr** [comment]
What it is showing there is probably the process name and not the window title. That's a macOS issue though and unrelated to Alacritty. The title is of course the only thing that changes with dynamic_title, anything else wouldn't make much sense.
