### ISSUE TITLE
change title bar color or modify transparent option

### ISSUE THREAD

**Issue by lonelykid** [alacritty/alacritty#4706]
## appearance enhancement
The figure shows iTerm2 when you set titlebar color to transparent. I'd like to have such an immersive titlebar. It's kinda like the transparent option in alacritty. But in iTerm2, the transparent titlebar still takes space(no button overlaps with text like in alacritty) and displays title text. I think it's better for transparent option to work this way. OR color customization of titlebar could be added to create a pseudo immersive experience.
![image](https://user-images.githubusercontent.com/2936633/104818367-22f4ba80-57f5-11eb-9a81-c9ca77693182.png)
## A side question
where can I find all default settings of alacritty? https://github.com/alacritty/alacritty/blob/master/alacritty.yml This file is all commented out and didn't cover shortcuts like ``Ctrl+A``--> start of line. I find ``Ctrl+A`` works but some other common emacs-mode shortcuts like ``Alt-d`` does not work by default.

Thanks!

For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: macos 11.1
Version: alacritty 0.7.1 (a852eb8)
Linux/BSD: X11/Wayland, DE or Compositor and WM

### Logs
Not Applicable
Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by chrisduerr** [comment]
> The figure shows iTerm2 when you set titlebar color to transparent. I'd like to have such an immersive titlebar. It's kinda like the transparent option in alacritty. But in iTerm2, the transparent titlebar still takes space(no button overlaps with text like in alacritty) and displays title text. I think it's better for transparent option to work this way. OR color customization of titlebar could be added to create a pseudo immersive experience.

Instead of putting a screenshot of what iTerm does, can you please go into detail what you actually want? Do you just want the titlebar to be the same color as your terminal background?

> where can I find all default settings of alacritty? https://github.com/alacritty/alacritty/blob/master/alacritty.yml This file is all commented out and didn't cover shortcuts like Ctrl+A--> start of line. I find Ctrl+A works but some other common emacs-mode shortcuts like Alt-d does not work by default.

Ctrl-A is a shortcut of your shell, not of Alacritty.

**Comment by lonelykid** [comment]
Sorry. I thought I have explained clearly. There are two ways to achieve the appearance in the figure.
1. Make the transparent title bar take space and displays text.
2. Make the title bar the same color with the background.
Either one is OK for me. iTerm can do both.

 ``Alt-F`` is also shortcut of shell [Bash shortcuts](https://kapeli.com/cheat_sheets/Bash_Shortcuts.docset/Contents/Resources/Documents/index). Why it's not supported by default?

**Comment by chrisduerr** [comment]
The spacing for the transparent bar is already tracked in separate issues like #4297.

Other than that I don't think there's much reason to add even more titlebar configuration options.

**Comment by lonelykid** [comment]
ok. I will check that. could you explain why shortcuts like Alt-F is not supported (it is a shell shortcut)?

**Comment by chrisduerr** [comment]
Alt+F is problematic due to macOS lack of an AltGr key and its inflation with the option key. That is tracked with #62.
