### ISSUE TITLE
no border on wayland-3.38.3

### ISSUE THREAD

**Issue by soloturn** [alacritty/alacritty#4708]
the border is not displyed on arch linux, gnome. decorations is set to "full".

### System

OS: arch Linux
Version: `alacritty --version` output
alacritty 0.8.0-dev (34435ed7)

> yay -Q | grep mutter
mutter 3.38.3-1

![image](https://user-images.githubusercontent.com/825568/104846438-ce2b6f80-58da-11eb-9226-de04e5a6670e.png)

**Comment by chrisduerr** [comment]
Yup, working as intended.

**Comment by soloturn** [comment]
@chrisduerr is there no setting to enable a visible border?
