### ISSUE TITLE
`ls` output has no color

### ISSUE THREAD

**Issue by zlj-zz** [alacritty/alacritty#4710]
When I use `ls`, its output doesn't have any color. But there are in other terminals.
When I use `sudo` to enter TMUX, it has colors; without `sudo`, there are no colors in TMUX.
Do you know what this is about? Thank you for your help.

### System

OS: macOS Big Sur 11.1
Version: 0.7.1
tmux version: 3.1c

**Comment by chrisduerr** [comment]
That's because your distro by default sets `ls` to use colors only with the `xterm-256color` terminfo or some slighty variations.

You need to either fix your system scripts or export things yourself.

**Comment by rwijtvliet** [comment]
Not wanting to reopen this issue, but could you elaborate, chris, how this is done? 

I'm on Ventura 13.5.2, alacritty 0.12.2, and bash 5.2.15 (installed with homebrew). I'm using the GNU version of the commands, installed with 
```
brew install coreutils
PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH" # also in .bashrc
```

Many thanks and enjoy the weekend!

**Comment by chrisduerr** [comment]
`dircolors`

**Comment by rwijtvliet** [comment]
```
❯ dircolors
LS_COLORS='rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=00:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.avif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:*~=00;90:*#=00;90:*.bak=00;90:*.crdownload=00;90:*.dpkg-dist=00;90:*.dpkg-new=00;90:*.dpkg-old=00;90:*.dpkg-tmp=00;90:*.old=00;90:*.orig=00;90:*.part=00;90:*.rej=00;90:*.rpmnew=00;90:*.rpmorig=00;90:*.rpmsave=00;90:*.swp=00;90:*.tmp=00;90:*.ucf-dist=00;90:*.ucf-new=00;90:*.ucf-old=00;90:';
export LS_COLORS
```

**Comment by kchibisov** [comment]
Have you tried passing `ls --color`?

**Comment by rwijtvliet** [comment]
That works!

But only somewhat. 

In alactritty on my linux machine, for example, dangling links are shown in red, which is really useful. On mac, this is not the case:

![image](https://github.com/alacritty/alacritty/assets/4106013/f05de8c8-2957-4de8-a00b-64e90f7e90eb)

**Comment by kchibisov** [comment]
Well, it's up to your `ls` config, nothing alacritty has do with all of that. Alacritty as any other terminal, just renders text (some terminals may set environment for ls, like LS_COLORS, but alacritty doesn't, because it's not its job).

The `LS_COLORS` is what sets the behavior on how `ls` should color various things, and I think you can define dangling links in it.

**Comment by rwijtvliet** [comment]
Ok, in that case - my bad. I'll investigate further; thanks for pointing me in the right direction!
