### ISSUE TITLE
Option to use scancodes in bindings by default.

### ISSUE THREAD

**Issue by vessd** [alacritty/alacritty#4713]
Is it possible to override all bindings to use scancodes? It's really annoying that I have to rebind everything for `us,ru` layout.

### System

OS: Arch Linux
Version: alacritty 0.7.1 (a852eb85)
DE: sway

**Comment by chrisduerr** [comment]
I'm not sure what you mean? Yes it is possible, just how you can override one binding.

Do you mean some way to automatically use the correct scancodes for everything magically? Then no, that's not possible. And there's also just no way to do it in general. Many of Alacritty's bindings have **nothing** to do with their location on the keyboard.

**Comment by vessd** [comment]
Yes, some kind of magic that will replace Latin letters with scancodes. Like `i3 bindsym` and [`sway bindsym --to-code`](https://github.com/swaywm/sway/pull/3058) do it.
