### ISSUE TITLE
after upgrading to alacritty@0.6, tmux-fzf-url plugin stopped working

### ISSUE THREAD

**Issue by GopherJ** [alacritty/alacritty#4715]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux
Version: alacritty 0.6.0 (04cbf767)
Linux/BSD: X11

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: 12.0
Keyboard and bindings:  Default Config

**Comment by GopherJ** [comment]
I used to be using alacritty@0.4.3 which doesn't have this issue

**Comment by GopherJ** [comment]
I tried to not use alacritty and things come back to normal

**Comment by GopherJ** [comment]
Alacritty conf: https://github.com/GopherJ/cfg/blob/master/alacritty/alacritty.yml
Tmux conf: https://github.com/GopherJ/cfg/blob/master/tmux/.tmux.conf

**Comment by chrisduerr** [comment]
Please try the latest version of Alacritty before reporting a bug. Also if you think you've run into a regression, please state exactly which version broke something for you.

**Comment by GopherJ** [comment]
@chrisduerr 
![image](https://user-images.githubusercontent.com/33961674/105033960-1a9cb980-5a59-11eb-8722-13d668340bd2.png)

as I said alacritty@0.6, please read at least title...

**Comment by chrisduerr** [comment]
The latest version is 0.7.1.

**Comment by GopherJ** [comment]
@chrisduerr Hi, I just tested the master it didn't work

**Comment by chrisduerr** [comment]
Which version, or ideally commit, introduced this regression for you?

**Comment by GopherJ** [comment]
@chrisduerr Hi, I suspect it's the git tag v0.6.0, but sadly today I didn't succeed to make tmux-fzf-url works with v0.4.3, I'll try later this afternoon

**Comment by GopherJ** [comment]
If I check bind keys with `tmux list-keys | grep fzf`, I have

```
bind-key    -T prefix       u                 run-shell -b "/home/cheng/.tmux/plugins/tmux-fzf-url/fzf-url.sh ''"
```

and if I execute directly

```
/home/cheng/.tmux/plugins/tmux-fzf-url/fzf-url.sh
```

it also works, but if I use binded key `u` it doesn't work on alacritty@0.6 but works on alacritty@0.4.3

**Comment by chrisduerr** [comment]
Could you please describe exactly what you are doing and what isn't working but worked previously?

**Comment by GopherJ** [comment]
@chrisduerr forgot it...things are crazy...

after upgrading to alacritty@0.6.0, tmux-fzf-url stopped working for one week, then I tried to downgrade to 0.4.3 it started to working and now when I upgrade to 0.6.0 it started to working again...:)

have a good day anyway! I'll see if the problem can be reproduced again
