### ISSUE TITLE
rendering issue with line drawing characters in the Ubuntu Mono font

### ISSUE THREAD

**Issue by oconnor663** [alacritty/alacritty#4716]
OS: Arch Linux, Gnome desktop, default settings (Wayland)
Version: alacritty 0.7.1 (a852eb85)

I've notived a rendering issue when I start the Kakoune text editor, which likes to display a little "Clippy" in ASCII art. Here's what it looks like under Gnome Terminal with the Ubuntu Mono font (correct):

![image](https://user-images.githubusercontent.com/860932/104970782-9f84c600-59ba-11eb-8e5d-c3a8be8157ad.png)

Here's what it looks like under Alacritty with a totally empty `alacritty.yml` (mostly correct, not sure what font):

![image](https://user-images.githubusercontent.com/860932/104970845-dce95380-59ba-11eb-8fcf-62d29beac35c.png)

And here's what it looks like if I configure the Ubuntu Mono font in Alacritty (clearly incorrect). First the config:

```
font: 
  normal: 
    family: Ubuntu Mono 
  size: 15
```

And the screenshot:

![image](https://user-images.githubusercontent.com/860932/104970878-01453000-59bb-11eb-8846-63cb8c0b46d1.png)

There the line drawing characters seem scattered all over the place. Here are the characters verbatim, if you'd like to try pasting them into a text file or something like that:

```
 ╭──╮
 │  │
 @  @
 ││ ││
 ││ ││
 │╰─╯│
 ╰───╯
```

Notably when I try some other fonts, like `Noto Sans Mono`, the rendering doesn't seem to have this issue. It could be specific to Ubuntu Mono?

**Comment by chrisduerr** [comment]
> Here's what it looks like under Gnome Terminal with the Ubuntu Mono font (correct):

Gnome terminal just renders the characters without querying your font. Alacritty will always use your font and thus if your font's line drawing characters are poor, it will look poorly.

**Comment by oconnor663** [comment]
Interesting, thanks for the explanation.
