### ISSUE TITLE
Blinking `On` setting doesn't work after exiting nvim

### ISSUE THREAD

**Issue by casonadams** [alacritty/alacritty#4720]
1. Add blinking `On` in config file
```alacritty.yml
cursor:
  style: 
    shape: Block
    unfocused_hollow: true
    blinking: On
```
2. Open nvim
3. Close nvim
4. No more cursor blink

Works if set to `Always`

### System

OS: macOS
Version: alacritty 0.7.1 (a852eb8)

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by chrisduerr** [comment]
Because vim disables blinking.
