### ISSUE TITLE
Alacritty leaves CPU-hungry cmd.exe orphans on closing

### ISSUE THREAD

**Issue by cmd410** [alacritty/alacritty#4723]
### System

OS: Windows 10
Version: alacritty 0.7.1 (a852eb8)

### Config has

```yml
shell:
  program: cmd
```

### Whats the problem

So, I found a wierd bug with `cmd.exe` as a shell in Alacritty. For some reason when I close alacritty, it doesn't kill cmd process so it just hangs there with nothing to do, but worst of all it consumes like 25% of CPU. So it can stack like 4 of these hungry guys and perfomance of the whole machine goes to almost zero until you manually kill them all with task manager.

_Very scary bug btw, when I first saw 5 cmds eating my CPU I thought some malware crawled into my pc..._

Before closing alacritty:
![before](https://user-images.githubusercontent.com/48290258/105183664-822d3480-5b3f-11eb-9fc7-6a2475d5a676.png)

After:
![baKfazAP8s](https://user-images.githubusercontent.com/48290258/105183824-b0ab0f80-5b3f-11eb-9e7e-e18920137930.png)

Though with powershell it works fine and shell process is successfully killed in the end

**Comment by chrisduerr** [comment]
If other shells work just fine, what makes you think this is an Alacritty issue?

**Comment by cmd410** [comment]
> If other shells work just fine, what makes you think this is an Alacritty issue?

Well, I tried cmd with terminus and conemu.
Conemu successfuly kills cmd, terminus doesn't, but neither of them make it use 25% CPU like alacritty does, so I just guess this abnormaly high CPU usage is alacritty specific

**Comment by chrisduerr** [comment]
If neither terminus nor Alacritty kill the subprocess, chances are that process is doing something silly to try and stay alive.

Alacritty is doing everything a sensible terminal emulator needs to do on shutdown, if you're running a shell that isn't sensible then that's on you.
