### ISSUE TITLE
No text colors is applied

### ISSUE THREAD

**Issue by CristianPessatti** [alacritty/alacritty#4724]
Using Awesome WM on Ubuntu.

My .config file is working, but the all the text is white, it was suposed to have different colors.

### System

OS: Linux Ubuntu 20.04
Version: alacritty 0.8.0-dev
Linux/BSD: Awesome WM

my .config:

![image](https://user-images.githubusercontent.com/32284997/105409635-7e68e300-5c0f-11eb-8c0d-4a767c7445b9.png)

ps: sorry if my english is terrible, not quite fluent yet.

**Comment by chrisduerr** [comment]
Please elaborate what color is white. I really doubt **everything** is only white. Is `echo -e "\e[31mTEST"` also white?

**Comment by CristianPessatti** [comment]
I'm sorry, i probably posted this in the wrong place, i got the same problem using gnome-terminal, so my mistake must be out of alacritty config

**Comment by chrisduerr** [comment]
If you have the same problem in other terminals, then you should probably look for a solution elsewhere.
