### ISSUE TITLE
Option to disable logging to file in /tmp

### ISSUE THREAD

**Issue by frebib** [alacritty/alacritty#4730]
Would we be able to have an option to disable creating these logfiles? I use systemd to invoke Alacritty so the logs are stored in the system journal anyway. It's not a huge deal, it would just be nice to turn them off. Thanks
```
frebib@frebib-PC ~> la /tmp/Alacritty-*
-rw-r--r-- 1 frebib frebib 2.2K Jan 23 22:53 /tmp/Alacritty-101135.log
-rw-r--r-- 1 frebib frebib 5.0K Jan 23 22:57 /tmp/Alacritty-102753.log
-rw-r--r-- 1 frebib frebib  27K Jan 23 23:01 /tmp/Alacritty-204949.log
-rw-r--r-- 1 frebib frebib 1.2K Jan 23 23:01 /tmp/Alacritty-218806.log
-rw-r--r-- 1 frebib frebib 1.2K Jan 23 23:04 /tmp/Alacritty-230864.log
-rw-r--r-- 1 frebib frebib 2.7K Jan 23 22:56 /tmp/Alacritty-97843.log
```

### System

OS: Linux
Version: `alacritty 0.8.0-dev (753c4ed1)`
Extra: X11, i3, picom

**Comment by chrisduerr** [comment]
These logs will only stay around if your Alacritty crashes, which indicates there's something wrong going on.

Alacritty by default doesn't create any logs and if there are logs created it deletes them after quitting. So if there are logs around it indicates that Alacritty runs into errors and crashes without shutting down cleanly, unless you explicitly opted into logging in the config/CLI options.

**Comment by frebib** [comment]
Indeed these log files are created by running terminals. I'm asking if there can be an option added to not create them in the first place. The log files are useless because the logs are already in the system journal

**Comment by chrisduerr** [comment]
Alacritty by default doesn't log anything. These log files existing at all means that there's probably something wrong. If you don't want them to appear, fix that?

**Comment by frebib** [comment]
I have INFO logs enabled. I suppose I could change that. If `WARN` or `ERROR` or other was logged, it still needn't create the file. I still want the logs, just not in these files.
```
frebib@frebib-PC ~> head -n10 /tmp/Alacritty-109366.log
[2021-01-24 11:14:10.548668594] [INFO ] [alacritty] Welcome to Alacritty
[2021-01-24 11:14:10.548744897] [INFO ] [alacritty] Configuration files loaded from:
                                                      "/home/frebib/.config/alacritty/alacritty.yml"
[2021-01-24 11:14:10.623615666] [INFO ] [alacritty] Device pixel ratio: 1
[2021-01-24 11:14:10.624507368] [INFO ] [alacritty] Initializing glyph cache...
[2021-01-24 11:14:10.643428328] [INFO ] [alacritty] ... finished initializing glyph cache in 0.018905881s
[2021-01-24 11:14:10.643465047] [INFO ] [alacritty] Estimated DPR correctly, skipping resize
[2021-01-24 11:14:10.643583028] [INFO ] [alacritty] Cell size: 7 x 15
[2021-01-24 11:14:10.643592957] [INFO ] [alacritty] Padding: 22 x 22
[2021-01-24 11:14:10.643597836] [INFO ] [alacritty] Width: 884, Height: 644
```

**Comment by chrisduerr** [comment]
You should not enable full logging unless necessary. That will obviously impact Alacritty's performance.

**Comment by frebib** [comment]
I have changed the default log level to `WARN` but regardless if Alacritty crashes it'll still create this log file, which I do not need or want, because the logs are still captured by stdout/stderr and logged into the journal. IMO this is still a reasonable ask regardless of the log level that is set
