### ISSUE TITLE
MSI file is unsigned

### ISSUE THREAD

**Issue by abhijit-hota** [alacritty/alacritty#4731]
### System
OS: Windows

Currently, it looks like the `.msi` installer isn't signed and thus, the browser is really reluctant to download it. Note the **Publisher: Unknown**
![image](https://user-images.githubusercontent.com/8116174/105638063-bdf53080-5e96-11eb-894e-cb05ff5d31e4.png)

Windows also throws a warning before installing.
![image](https://user-images.githubusercontent.com/8116174/105638036-98682700-5e96-11eb-870c-aa39ca7290f2.png)

I don't know if this is a known issue (I did search for previous issues) and cannot be resolved due to some reasons. I am unaware of the signing and building process.

I ~went through your GitHub action yml file~ did some research and found out that  you use WiX. So I'm just pasting this here if it's of any help. https://stackoverflow.com/questions/17589754/wix-installer-msi-publisher-unknown

Thank you for the project!

**Comment by chrisduerr** [comment]
Yeah, no. If you're trying to avoid code signing issues, I recommend using Linux where the signature system is actually setup to authenticate developers rather than a way to increase revenue.

**Comment by abhijit-hota** [comment]
@chrisduerr *I'm* not facing any code signing issues. Alacrity, in all terms, is legitimate software. I know that it's not harmful to my PC. The unsigned installer just makes it look a bit illegitimate. 

Just my two cents. 😄

> I recommend using Linux where the signature system is actually setup to authenticate developers rather than a way to increase revenue.

As I mentioned, I'm unaware of the signing process.
