### ISSUE TITLE
'None' key bind action should not eat up keypresses

### ISSUE THREAD

**Issue by crthpl** [alacritty/alacritty#4732]
### System

OS: Linux (Pop! OS)
Version: 0.6.0
Linux/BSD: GNOME Desktop Environment

### Issue
Whenever I use `Ctrl-Slash` (Launch/Switch Application) or `Ctrl-R` (Focus VS Code for Me) it instead enters `?` or `^R` into the terminal, respectively. I would like it if `None` would just ignore it and not eat up the key presses.
```yaml
- {key: R, mods: Control, action: None}
```

**Comment by chrisduerr** [comment]
Yes it should. Use `ReceiveChar` if you want it to still receive the characters.
