### ISSUE TITLE
Keybinding does not reach application (neovim).

### ISSUE THREAD

**Issue by agilesteel** [alacritty/alacritty#4733]
### System

OS: Windows
Version: 0.7.1

I'm running WSL2/Ubuntu20.04 and neovim inside. I bound Control+Slash in neovim to comment out a line and it works just fine in any other terminal, but alacritty doesn't pass it through to neovim.

I tried the following but it didn't help:
```yaml
key_bindings:
  - { key: Slash, mods: Control, action: None }
  - { key: Slash, mods: Control, action: ReceiveChar }
```
As a test I tried this and it worked (full screen was toggled):
```yaml
key_bindings:
  - { key: Slash, mods: Control, action: ToggleFullscreen }
```

Is there a way to disable **ALL** keybindings in alacritty? I really don't need any of them.

**Comment by chrisduerr** [comment]
> I'm running WSL2/Ubuntu20.04 and neovim inside. I bound Control+Slash in neovim to comment out a line and it works just fine in any other terminal, but alacritty doesn't pass it through to neovim.

What output do you get when pressing ^V -> ^/ in other terminals versus pressing it in Alacritty?

> Is there a way to disable ALL keybindings in alacritty? I really don't need any of them.

Oh I **highly** doubt that.

**Comment by agilesteel** [comment]
I get `^_` in windows terminal and nothing in alacritty.

**Comment by chrisduerr** [comment]
What does `alacritty --print-events | grep "ReceivedCharacter"` give you when you press that key?

**Comment by ebigram** [comment]
FWIW, this happens on my mac as well. Just checked alacritty vs. iTerm.

**Comment by agilesteel** [comment]
@chrisduerr nothing. Everything else I press gets printed, but this one doesn't reach alacritty at all :(

**Comment by chrisduerr** [comment]
Then bind it yourself. Of course `ReceiveChar` action isn't going to help you when it doesn't actually receive any characters. Just add a single binding with the `chars` value `\x1f`.

**Comment by agilesteel** [comment]
Ok that helped. Isn't this weird though that this had to be done? This wasn't necessary in any other terminal. For anyone who stumbles on this, this is what helped:
```yaml
key_bindings:
  - { key: Slash, mods: Control, chars: "\x1f" }
```

**Comment by chrisduerr** [comment]
> Isn't this weird though that this had to be done?

It shouldn't be necessary. In fact it isn't on Linux. But especially on macOS there are some outstanding keyboard handling issues. This is being worked on upstream though, it just takes time.
