### ISSUE TITLE
100% CPU usage when screen goes blank, PopOS (ubuntu)

### ISSUE THREAD

**Issue by bdols** [alacritty/alacritty#4734]
I'm seeing high CPU usage from alacritty when my laptop idles and the screen goes blank. (Fans running after a few hours of idle and I ssh in to see what's happening)
It's pretty consistent. Let me know what you need.

### System

OS: Linux/PopOS
Version: 0.71
Linux/BSD: Gnome

### Logs

Font/Terminal size: 160 cols * 70 lines and 100x40
Keyboard and bindings: I can add event output upon next incident

**Comment by chrisduerr** [comment]
What do you mean by "screen goes blank"?

**Comment by bdols** [comment]
well, that's what PopOS describes in the Power settings, my laptop is powered on, not suspended, there is no power to the display, and I can ssh in.
For power saving settings to reproduce: "Dim Screen when Inactive" is on, "Blank Screen" is set to 15 minutes. "Automatic Suspend" is off

**Comment by chrisduerr** [comment]
Okay, so your monitor is turned off? Your graphics driver might stop vsyncing, thus Alacritty starts redrawing constantly.

This is X11, not Wayland, correct?

**Comment by bdols** [comment]
yes, X11. I see that Pop OS 20.10 includes Wayland now but it's disabled

**Comment by chrisduerr** [comment]
Could you try Wayland?

**Comment by bdols** [comment]
not without opening a support ticket with System76.. I restarted gdm with wayland enabled and it wasn't usable.

**Comment by chrisduerr** [comment]
> I restarted gdm with wayland enabled and it wasn't usable.

Could you be more specific please? How was it not usable?

I'm asking you if you can reproduce the problem on Wayland, not replace your X11 system permanently.

**Comment by bdols** [comment]
there was no login prompt, Alt-F2, Alt-F3, Alt-F1 was unresponsive. had to ssh in to restart gdm with wayland disabled.

is wayland a requirement for alacritty?

**Comment by chrisduerr** [comment]
> is wayland a requirement for alacritty?

It is not, but I'm suspecting vsync problems and Wayland doesn't have vsync in Alacritty.

You can run the following diff, which will log the time it takes to wait for the vsync block:

```diff
diff --git a/alacritty/src/display/mod.rs b/alacritty/src/display/mod.rs
index 2a55402..059b16d 100644
--- a/alacritty/src/display/mod.rs
+++ b/alacritty/src/display/mod.rs
@@ -660,6 +660,7 @@ impl Display {
         #[cfg(all(feature = "wayland", not(any(target_os = "macos", windows))))]
         self.request_frame(&self.window);
 
+        let vsync_start = std::time::Instant::now();
         self.window.swap_buffers();
 
         #[cfg(all(feature = "x11", not(any(target_os = "macos", windows))))]
@@ -671,6 +672,8 @@ impl Display {
                 api.finish();
             });
         }
+
+        println!("VSYNC: {:?}", std::time::Instant::now() - vsync_start);
     }
 
     /// Update to a new configuration.
```

It's natural that this will be lower and higher, but on a 60 Hz monitor you'd usually expect it to be 10+ms regularly. If this sits at like <1ms most of the time while the screen is turned off, something's wrong with the vsync.

**Comment by bdols** [comment]
I also saw the 100% CPU when idle from firefox. System76 support had me purge the nvidia drivers and reinstall their system76-driver-nvidia package, in case my OS upgrade wasn't fully completed. Haven't seen this condition since, so far, but it's only been a few days.

**Comment by chrisduerr** [comment]
Let me know if that doesn't fix it then please.
