### ISSUE TITLE
Alacritty + Wayland title bar bug

### ISSUE THREAD

**Issue by KrutNA** [alacritty/alacritty#4739]
### System

OS: Arch Linux
Version: 0.7.1 after update, but also on 0.6.0
Linux/BSD: GNOME on Wayland

### Description

After update `xorg-xwayland` from `1.20.0.r800.ge4a9f0bb4-1` to `1.20.0.r811.gf08ab719d-1`
Got an issue with title bar. (it's not disabled in config)

How it looks now
![image](https://user-images.githubusercontent.com/31564815/105856632-a55e5500-6013-11eb-9519-c53a574ab9ef.png)

What expected (screenshot of other terminal)
![image](https://user-images.githubusercontent.com/31564815/105856273-400a6400-6013-11eb-8cab-c006a260c4b0.png)

Tested on X11, works fine. So I'm sure it's Wayland.
This issue seems only on alacritty, titlebar on other apps looks fine.

Also gnome screenshot not captures alacritty's titlebar on window screenshot (may be it will be helpful)

And alacritty doesn't create log, there is `ALACRITTY_LOG` variable, but file doesn't exists.

**Comment by chrisduerr** [comment]
Titlebar looks just like intended.

**Comment by KrutNA** [comment]
> Titlebar looks just like intended, you can thank gnome for that.

But it's fine on other applications. And was working fine with Alacritty before.

**Comment by chrisduerr** [comment]
It's fine on applications using GTK, yes. Alacritty isn't using GTK.

**Comment by r-c-f** [comment]
While trying to reproduce another bug, I encountered this on Weston as well, with weston-terminal managing titles just fine without gtk. If CSD is simply not supposed to render titles, it would be useful to document that somewhere, given the removal was never documented in any commit or changelog entry, while references to this working were documented in eg. da6f0a505e0d7da181b056c52f42b5a7f0bf29ed, with #3258 documenting that it did start working again within the past year and that the text is, in fact, supposed to be there.

**Comment by chrisduerr** [comment]
Oh @r-c-f, I didn't know that the title actually isn't working at all. I'd assume that's a font thing, is that reproducible?

**Comment by r-c-f** [comment]
Indeed, with a vanilla weston and alacritty config I get something like 
![weston-no-titles](https://user-images.githubusercontent.com/18584749/106371719-422f3400-632d-11eb-8a30-b1d00c922dde.png) with no initial title text, or text after attempting to manually set it. That screenshot was taken with Weston running as a Wayland client in sway but it also impacts standard weston on drm.

Uniformity being anathema in the age of CSD it's never going to look like any other terminal on such compositors, but I think @KrutNA was more concerned with the fact that it's also functionally broken.

**Comment by chrisduerr** [comment]
> I think @KrutNA was more concerned with the fact that it's also functionally broken.

Comparing it to GTK is somewhat misleading then, usually people just complain that GTK is a broken system.

This issue is probably already covered by https://github.com/Smithay/andrew/issues/3 though. Unfortunately the library used for rendering the text in titlebars is somewhat subpar.

**Comment by anthr76** [comment]
It's odd I reproduce this issue on my laptop though not on my desktop. I use the same configurations between both

**Comment by thornjad** [comment]
If this is indeed not an Alacritty bug, is there any solution at all? It's a bit jarring to have a single application with a radically different title bar from everything else, especially because its a different color and has no text. I'm just hiding the title bar for now, but would prefer to have it showing.

**Comment by chrisduerr** [comment]
> If this is indeed not an Alacritty bug, is there any solution at all? It's a bit jarring to have a single application with a radically different title bar from everything else, especially because its a different color and has no text. I'm just hiding the title bar for now, but would prefer to have it showing.

Complain to your DE, it's their fault.

**Comment by thornjad** [comment]
Given that Alacritty is the _only_ app which has this issue (that I've seen), it seems logical that there must be _something_ that can be done. With Ubuntu moving to Wayland by default next month, I think this issue is only going to get more attention.

**Comment by r-c-f** [comment]
@thornjad There are really two separate issues here. The lack of title text *is* a toolkit bug, and [has been fixed upstream.](https://github.com/Smithay/client-toolkit/issues/170) 

The inconsistent styling is another matter. [GNOME do not consider decoration inconsistency to be a bug, nor the solution as adopted by KDE and Sway as worthwhile](https://gitlab.gnome.org/GNOME/mutter/-/issues/217) and so you're left with the prospect of either slavishly emulating the detected desktop environment's native look, or rewriting your application to use the native toolkit for each desktop environment you want to support. A hard dependency on GTK is not going to happen in a million years, but if you can pull something a bit saner off, feel free to try to get it into https://github.com/Smithay/client-toolkit

**Comment by elshize** [comment]
FYI, this is not a solution but rather a temporary workaround, but you can execute Alacritty with `WAYLAND_DISPLAY= alacritty` (note: setting the env var to empty). At least in my case it works.

**Comment by elshize** [comment]
@chrisduerr @r-c-f would it maybe make sense to add a setting to alacritty for the fallback title bar color? I think being able to set the color for active and inactive windows + font family and size would go a long way. But I don't have a good understanding of how difficult this would be.

Is the color of the bar hardcoded or does it depend on the environment?

**Comment by nixpulvis** [comment]
> would it maybe make sense to add a setting to alacritty for the fallback title bar color? I think being able to set the color for active and inactive windows + font family and size would go a long way. But I don't have a good understanding of how difficult this would be.

This is generally the job of the window manager, however Alacritty does apply a somewhat minimal CSD on Wayland. See the [`Theme`](https://docs.rs/winit/0.24.0/winit/platform/unix/trait.Theme.html) trait of `winit` for details about what we can specify.

IIRC, there was originally no desire to allow configuration for this, however I can see the value in letting users change their own decoration colors. That would be a feature request though.

**Comment by chrisduerr** [comment]
> IIRC, there was originally no desire to allow configuration for this, however I can see the value in letting users change their own decoration colors. That would be a feature request though.

I still have no desire for this and I doubt that's going to change in the future. It's just too niche and hardly useful at all.

But the Wayland decorations already indicate active and inactive windows using different colors.

**Comment by elshize** [comment]
> I still have no desire for this and I doubt that's going to change in the future. It's just too niche and hardly useful at all.
> 
> But the Wayland decorations already indicate active and inactive windows using different colors.

I hear you. I totally understand, it's just a shame Gnome doesn't care about this usecase. Alacritty is hardly the only program in this position.

@nixpulvis thanks for pointing me to the code. For anyone who's looking for how to configure the colors:
- Text: `colors.search.bar.foreground`
- Background: `colors.search.bar.background`
- Close button on hover: `colors.normal.red`
- Maximize button on hover: `colors.normal.green`
- Minimize button on hover: `colors.normal.yellow`

So there is no sparate config for these, but the title bar color can be changed by changing the search foreground/background colors.

**Comment by gbaranski** [comment]
> > I still have no desire for this and I doubt that's going to change in the future. It's just too niche and hardly useful at all.
> > But the Wayland decorations already indicate active and inactive windows using different colors.
> 
> I hear you. I totally understand, it's just a shame Gnome doesn't care about this usecase. Alacritty is hardly the only program in this position.
> 
> @nixpulvis thanks for pointing me to the code. For anyone who's looking for how to configure the colors:
> 
>     * Text: `colors.search.bar.foreground`
> 
>     * Background: `colors.search.bar.background`
> 
>     * Close button on hover: `colors.normal.red`
> 
>     * Maximize button on hover: `colors.normal.green`
> 
>     * Minimize button on hover: `colors.normal.yellow`
> 
> 
> So there is no sparate config for these, but the title bar color can be changed by changing the search foreground/background colors.

For me setting colors don't work

**Comment by anthr76** [comment]
I think I'm giving up..

**Comment by thornjad** [comment]
I've given up as well, I've gotten too tired of the "not my problem" attitude, especially around Gnome. Luckily there are plenty of other terminal options that support Gnome on Wayland.

**Comment by elshize** [comment]
@thornjad I think it's Gnome who have not-my-problem attitude, don't they? At least that's how I feel about it. Notice that even the apps that do work around this and do try to match the gnome-style decorations, it's always off. I think Qt apps do this (at least Qutebrowser does, I'm assuming it's on Qt side but might be wrong here) but it's clear that it's rendered differently, and it shows. It's just a difficult problem, and imo not how this should work at all. If Plasma or Sway can provide decorations, I don't see why Gnome couldn't. Anyway, that's how I see it; I'm not affiliated with either project but as a user, this is how I see it.

Mind you, I would like Alacritty to just work as I would expect, but I try to be reasonable, and I understand that the devs need to be selective about what they use their (probably very limited) resources for. And I appreciate all the hard work they have put into this application that we all can use for free.

Also, as I mentioned before, you can always try using it with xwayland by running: `WAYLAND_DISPLAY= alacritty`. It worked just fine for me when I tried it. All the terminals that "support Gnome on Wayland" probably run through xwayland anyway, don't they?

**Comment by cetra3** [comment]
Just for my own posterity, you can set the env var `WINIT_UNIX_BACKEND` to `x11` to force it to use the xwayland path & decorate the window correctly.  I.e,

```
env WINIT_UNIX_BACKEND=x11 alacritty
```

**Comment by tuananh** [comment]
is there any news?

**Comment by yavko** [comment]
I think libdecor would fix the CSD issue. Even SDL uses it now.

**Comment by akvadrako** [comment]
Well the `winit` patch has been merged, so just upgrading the dependency will probably fix the issue.

**Comment by pc00per** [comment]
The **not-my-problem** attitude conflicts with alacritty's own [homepage's about](https://alacritty.org/#About) explanation
> **By integrating with other applications, rather than reimplementing their functionality**, it manages to provide a flexible set of features with high performance.

**Comment by akvadrako** [comment]
FYI this bug has been fixed for a while.

**Comment by chrisduerr** [comment]
We will also only ever be able to integrate with things that want to be integrated. If another application plays hard to get, you should reevaluate your software choice and maybe switch to something that plays along.

**Comment by fal3n-4ngel** [comment]
You could modify the Desktop Entry (The desktop shortcut) to force it to use the xwayland path & decorate the window correctly.
You can find it in the .local/share folder or wherever your os stores the desktop entry
NB : I use Arch , hope it works for others too


Alacritty.desktop
```
[Desktop Entry]
Type=Application
TryExec=alacritty
Exec=env WINIT_UNIX_BACKEND=x11 alacritty
Icon=Alacritty
Terminal=false
Categories=System;TerminalEmulator;

Name=Alacritty
GenericName=Terminal
Comment=A fast, cross-platform, OpenGL terminal emulator
StartupWMClass=Alacritty
Actions=New;

X-Desktop-File-Install-Version=0.26

[Desktop Action New]
Name=New Terminal
Exec=alacritty
```
