### ISSUE TITLE
Ctrl-K does not clear running logs or tail command

### ISSUE THREAD

**Issue by milkrun** [alacritty/alacritty#4740]
I have switched back to MacOS terminal because speed is useless when I can't clear a running log
### System

OS: macOS
Version: 0.71

**Comment by chrisduerr** [comment]
Why would it?

**Comment by nixpulvis** [comment]
@milkrun see https://github.com/alacritty/alacritty/issues/4503#issuecomment-737310244 for the legacy of this issue.

Closing as a dup.
