### ISSUE TITLE
Font characters don't display correctly with version 0.7.1

### ISSUE THREAD

**Issue by ansidev** [alacritty/alacritty#4745]
### Problem

Font characters don't display correctly with version 0.7.1

### System

OS: macOS Big Sur 11.1
Version: 0.7.1 (a852eb8)

### Logs

Alacritty 0.7.1:
![Alacritty 0.7.1](https://user-images.githubusercontent.com/6688235/106145757-804f1b00-61a8-11eb-937f-3c22923b5640.png)

macOS Terminal:
![macOS Terminal](https://user-images.githubusercontent.com/6688235/106145770-83e2a200-61a8-11eb-84ca-f3085cc54ddc.png)

Alacritty Config: [alacritty.yml.zip](https://github.com/alacritty/alacritty/files/5887529/alacritty.yml.zip)

**Comment by chrisduerr** [comment]
Make sure you have a font with those symbols in your fallback list, otherwise they won't show up.

**Comment by ansidev** [comment]
> Make sure you have a font with those symbols in your fallback list, otherwise, they won't show up.

As you seen, macOS Terminal UI is good, but Alacritty UI is not good. So you should have the answer.

**Comment by ansidev** [comment]
@chrisduerr This is an issue and it should be fixed instead of closed.

**Comment by bitraid** [comment]
> @chrisduerr This is an issue and it should be fixed instead of closed.

The issue is that you don’t follow the advice given to you. If you look closely you will see that the two applications use different fonts. **Select a font that includes these characters or set a fallback font that does**.

**Comment by ansidev** [comment]
> > @chrisduerr This is an issue and it should be fixed instead of closed.
> 
> The issue is that you don’t follow the advice given to you. If you look closely you will see that the two applications use different fonts. **Select a font that includes these characters or set a fallback font that does**.

The advice from @chrisduerr is not clear or it's my mistake. However, I solved the problem with your answer. Thank you!

**Comment by ansidev** [comment]
Now, this issue can be closed again :)
