### ISSUE TITLE
Zero-width utf-8 character rendered above the following character, not the preceding

### ISSUE THREAD

**Issue by jonatanlinden** [alacritty/alacritty#4747]
### System

OS: macOS 11.1
Version: 0.7.1

### Issue

For text that contain zero width characters, e.g., umlaut, it seems that the character is rendered on top of the following character and not on top of the preceding, which I would expect.

To reproduce: Write a test file with contents 'öi' (and where ö is not the combined glyph U+00F6 but rather 'o' followed by '¨', U+0308).

In alacritty:
`> cat test`
`oï` (actually displayed with three dots over the i)

`> hexdump test`
`0000000 6f cc 88 69 0a`
`0000005`

The same happens for other zero-width characters such as circumflex, grave accent, acute accent.

**Comment by chrisduerr** [comment]
This is a problem with your font.

**Comment by jonatanlinden** [comment]
Thank you for your quick reply. Do you know the nature of the problem? It seems other software seems to handle this problem, e.g., iTerm and emacs.

**Comment by chrisduerr** [comment]
> Do you know the nature of the problem?

Yes, the fonts define the offset in these symbols. Especially on macOS there have been a lot of issues with this offset being incorrect. IIRC it's usually negative, but it is not with some fonts. If you check a different font like Fira Code, you'll probably see this issue fixed.

**Comment by tobx** [comment]
@chrisduerr Sorry to bother you again, but I just want to mention that Fira Code does not solve that issue on macOS. I have yet to find a font that is able to display those characters correctly. What I tried so far:

- Cascadia Code,
- Fira Code,
- Fira Mono,
- Hack,
- Menlo,
- Monaco,
- PT Mono,
- SF Mono,
- Ubuntu Mono

Fira Mono (not Code) and Monaco where the only fonts that display `¨` on the same letter, but it is still not readable (e.g. `¨` on a `Ü` is too low and paints over the lines of the `U`).

As I said, if this is not planned or not top priority I will be quiet and still very thankful for this awesome terminal. I just want to mention the issues I have and that this is not happening in any other applications I know with those fonts.
