### ISSUE TITLE
Dynamic title is not working in macOS

### ISSUE THREAD

**Issue by tobx** [alacritty/alacritty#4750]
The window title is set to `Alacritty` and does not change, does not show the current directory and does not update when running programs that would change the window title in the default macOS Terminal.

I have already seen #1636, but it does not really help me. Here are some information that I came across in this issue that might be relevant:

- I am using `zsh`, but switching to `bash` does not help either.
- `dynamic_title` is set to `true`.
- I am not using the `--title` option.
- I am not setting the title in the config file (tried also without a config file).
- `echo -e "\033]0;test\007"` **does work**.
- I have not yet found a place where `PROMPT_COMMAND` is set (checked `.zshenv`, `.zprofile`, `.zshrc` and `/etc/zshrc`).

This could be interesting, but I am not sure what it tells me:

```
$ infocmp alacritty
infocmp: couldn't open terminfo file (null).
$ echo $TERM
xterm-256color
```

### System

OS: macOS Big Sur 11.1
Version: alacritty 0.7.1 (a852eb8)

**Comment by chrisduerr** [comment]
> echo -e "\033]0;test\007" does work.

Then Alacritty's dynamic title is working on macOS.

**Comment by nixpulvis** [comment]
@tobx this is the default behavior of `zsh` AFAIK. If you want the shell to update your title when you move directories, run programs, or whatever else your heart desires, that's on you to configure. I know there are some packages that do a lot of this stuff for you, but you'll have to search around to figure this out. Personally, I'd just set the title myself by adding the escape to my `$PROMPT` manually.

Just to get you started, you can set the prompt in `zsh` with:

```zsh
PROMPT="%n@%M $ "
```
For more information on prompt expansion [read this](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html).

**Comment by tobx** [comment]
@nixpulvis I see, as with other Terminals it seems there is mostly something preconfigured, I did not expect that this is something to be configured in `zsh`. Thank you.

**Comment by chrisduerr** [comment]
This literally has nothing to do with the terminal. That's your shell.

**Comment by tobx** [comment]
@chrisduerr Hm, in the macOS Terminal there are GUI settings to configure the window title. Even if I overwrite the title with `echo -e "\033]0;test\007"` macOS will still append things to the title (like adding the active process). This works independently of the shell (tried with `zsh` and `bash`).

Anyway, I managed to get it working with the zsh hook functions `precmd` and `preexec`. Although the "active process" feature of the macOS Terminal app is pretty nice, because it recognizes when a running process starts another process and updates the title.

**Comment by adept587** [comment]
add this line to .zshrc 
`preexec() { print -Pn "\e]0;$1\a" }`

it works on macOS Big Sur 11.5.2
