### ISSUE TITLE
[Feature Request] Different cursor thicknesses based on cursor shape

### ISSUE THREAD

**Issue by MithicSpirit** [alacritty/alacritty#4752]
I like to have my beam cursor a bit thicker (around .2) but that makes the hollow cursor too thick. If I set it to .15 then the hollow cursor looks fine but the line cursor is way too thin. If there was a way to set different thicknesses per cursor shape that would fix this problem.

### System

OS: Archlinux
Version: alacritty 0.7.0-dev (df24940) (using [zenixls2's ligature branch](https://github.com/zenixls2/alacritty/tree/ligature))
Linux/BSD: X11, Picom, Qtile

**Comment by chrisduerr** [comment]
Adding an option to modify the cursor thickness is already something that I only see limited value in. Why does it matter if the box cursor is a pixel too thick?

I can understand that on higher DPI systems a beam might be difficult to see if it's too thin, but I don't see why that same thickness would be a problem for the box cursor.

**Comment by MithicSpirit** [comment]
I just find it aesthetically unpleasant to have the box outline cursor be that thick, though this may be just that I'm not used to it since I come from URxvt (which has the outline cursor thinner by default).

**Comment by chrisduerr** [comment]
I don't think this very specific personal request justifies making changes to Alacritty. For the majority of people the current options are probably already more than enough, even more is likely just confusing.

Though I might be wrong and if someone else is interested in this feature, please let me know. I might be willing to reconsider if there should be significant demand.

**Comment by MithicSpirit** [comment]
Fair enough. I'll probably get used to it eventually anyways so it doesn't really matter that much.
