### ISSUE TITLE
Incorrect estimated DPR on wayland

### ISSUE THREAD

**Issue by icasdri** [alacritty/alacritty#4753]
### System

OS: Linux (kernel 5.10, systemd 247)
Version: alacritty 0.7.1 (a852eb85) (can also repro on HEAD/master 73759da)
Wayland compositor: sway 1.5.1, Mutter (`mutter --wayland`) 3.38.3, KWin (`kwin_wayland`) 5.20.5

### Description

On all three wayland compositors above (sway, Mutter from GNOME, and KWin from KDE), Alacritty estimates DPR incorrectly as 2 when it ends up being 1 (per log output). Note: my system has one monitor, and it is indeed HIDPI with scale factor 2 (e.g. `output ... scale 2` in sway config), however the actual DPR that is relevant for window sizing etc. appears to be 1.

On Mutter and KWin, the issue manifests itself in user-visible ways:

* On Mutter, Alacritty sometimes starts with too big of a window (and does not resize to the correct size) and sometimes starts at the correct size
* On KWin, Alacritty always starts with too big of a window (for a split second) before resizing to the correct size (rather jarring!)

Note: sway always resizes windows for tiling, so the issue is much less noticeable on sway

If I recompile Alacritty with `estimated_dpr = 1.` in `Display::new` (in `alacritty/src/display/mod.rs`), the user-visible effects described above go away. Curiously, the user-visible effects also go away if config option `window.dimensions` is unset (however, the estimated DPR is still incorrect per the logs).

### Logs

`alacritty -vv` output for all compositors above has
```
[INFO ] [alacritty] Welcome to Alacritty
[INFO ] [alacritty] Configuration files loaded from: ...
[DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[DEBUG] [alacritty] Estimated DPR: 2
[DEBUG] [alacritty] Estimated window size: Some(PhysicalSize { width: 1368, height: 800 })
[DEBUG] [alacritty] Estimated cell size: 17 x 33
[INFO ] [alacritty] Device pixel ratio: 1
[INFO ] [alacritty] Initializing glyph cache...
[DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Italic, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[INFO ] [alacritty] ... finished initializing glyph cache in 0.035864048s
[INFO ] [alacritty] Cell size: 8 x 16
[INFO ] [alacritty] Padding: 2 x 2
[INFO ] [alacritty] Width: 644, Height: 388
[INFO ] [alacritty] PTY dimensions: Line(24) x Column(80)
[INFO ] [alacritty] Initialisation complete
[DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Italic, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[INFO ] [alacritty] Font size changed to Size(21) with DPR of 2
[INFO ] [alacritty] Cell size: 17 x 33
[DEBUG] [alacritty_terminal] New num_cols is 75 and num_lines is 23
[INFO ] [alacritty] Padding: 4 x 4
[INFO ] [alacritty] Width: 1288, Height: 776
```
with a difference towards the end for Mutter when it stays too big of a window
```
[DEBUG] [alacritty_terminal] New num_cols is 160 and num_lines is 48
[INFO ] [alacritty] Padding: 4 x 4
[INFO ] [alacritty] Width: 2736, Height: 1600
```

**Comment by chrisduerr** [comment]
I mean there's nothing wrong with estimating the wrong DPI, that's why it's an estimation.

You probably have multiple monitors, correct? Alacritty doesn't know which monitor it will spawn on and depending on the monitor it is created on it will need to resize itself to fit your specified dimensions.

**Comment by icasdri** [comment]
Nope, my machine only has one monitor :/

I understand it is just an estimate, however the random spawning at the wrong size (Mutter) or split second resizing (KWin) is rather annoying. I'm not sure how to go about fixing it properly -- my only monitor is HIDPI with scale factor 2, so it makes sense (intuitively) to estimate DPR to be 2, but for some reason that results in way-too-big window size estimates. Initially, I thought it was a wayland compositor bug, but seeing as it's reproducible across sway, Mutter, and KWin, it's probably not.

After some further digging, I suspect DPR is not used to size windows in wayland, only surfaces. For an Alacritty window manually resized to be 24 lines x 80 columns, such that it shows `[INFO ] [alacritty] Width: 1368, Height: 800` (which matches the original estimated window size):

* Sway reports (in `swaymsg -t get_tree`)
    * `geometry` with width 1368 and height 800
    * `rect` and `window_rect` with width 684 and height 400
* KWin reports (in `qdbus org.kde.KWin /KWin org.kde.KWin.showDebugConsole`)
    * `clientSize` and `bufferGeometry` with width 684 and height 400
    * `size`, `rect`, `geometry`, and `frameGeometry` with width 684 and height 429 (extra height probably for decoration)

Perhaps the fix is to always use DPR=1 in the window size estimate on wayland?

**Comment by chrisduerr** [comment]
> After some further digging, I suspect DPR is not used to size windows in wayland

That is incorrect.

Do you have Alacritty configured to spawn at a specific number of columns and lines? I'd assume that's why you're getting the jumping around. Though in sway that probably would be ignored by the compositor.

**Comment by icasdri** [comment]
Yes. I have `window.dimensions.columns=80` and `window.dimensions.lines=24`.

The jumping around goes away if `window.dimensions` is not set (spawns at default size which seems to be estimated correctly), or if I recompile and force `estimated_dpr = 1.` (spawns at desired size estimated correctly).

**Comment by chrisduerr** [comment]
Ah okay. The simplest solution would obviously be to limit the spawned window size using your WM, rather than Alacritty. With just a single monitor that should always provide better results.

When it comes to calculating the correct DPI off the bat, this seems like a Wayland issue. Maybe @vberger has an idea why there seems to be a monitor with a DPI of 2, but once the window is spawned the DPI is 1?

**Comment by vberger** [comment]
> When it comes to calculating the correct DPI off the bat, this seems like a Wayland issue. Maybe @vberger has an idea why there seems to be a monitor with a DPI of 2, but once the window is spawned the DPI is 1?

Because winit does not do any "DPI guessing", so it tells the server that the frame is drawn with a DPR of 1, and only adjusts its DPR once the window actually exists and it thus knows from the wayland protocol what the correct DPR should be. That DPR-guessing logic should be directly handled by winit for it to work.

Clients that don't try to do any DPR guessing would thus simply draw their first frame with a DPR of 1 (and thus be rescaled by the server), and would be DPR correct from the second frame. As seen by the client, the window would not resize or flicker, just be slightly blurry for a split-second. This behavior is what is currently considered as "the norm" in the Wayland world.

This non-perfect-first-frame is a known issue of the wayland protocol, see [this issue](https://gitlab.freedesktop.org/wayland/wayland/-/issues/133).

**Comment by chrisduerr** [comment]
@vberger But shouldn't the Wayland protocol return the correct DPRs for all monitors? I understand how this would break if there was a monitor attached with a DPI of 2, that's perfectly fine and part of the considerations of this implementation. But if the only monitor attached has a DPI of 1, shouldn't winit be aware of that? I'm just curious where that 2 might be coming from.

**Comment by nixpulvis** [comment]
It seems unfortunate that Wayland doesn't simply provide the complete list of outputs and the needed info (like DPR) at the time of window initialization. Perhaps I'm missing something, but this seems like something that should be easy to specify.

Either way, if simply up-scaling for the first frame is the norm, we should have no trouble doing that.

**Comment by chrisduerr** [comment]
> It seems unfortunate that Wayland doesn't simply provide the complete list of outputs and the needed info (like DPR) at the time of window initialization. Perhaps I'm missing something, but this seems like something that should be easy to specify.

I think we have a list with all outputs. That's where Alacritty gets its DPR of 2 from. The problem is that we do not know which output the application will appear on and (currently) that Wayland always seems to render the first frame with a DPI of 1.

**Comment by nixpulvis** [comment]
heh, I just realized that was actually the issue. So a larger change to the protocol would be needed it seems. Hopefully this can be done one day though...

**Comment by vberger** [comment]
> The problem is that we do not know which output the application will appear on and (currently) that Wayland always seems to render the first frame with a DPI of 1.

Note that it is not solely a Wayland constraint. In the case of a single dpi setup, the app can predict the DPR accurately and render its first frame at the correct DPR, but it needs to actually tell the server that it is doing it. So this DPI-predicting logic would need to be done by winit to be reliable.

Technically, alacritty could bypass winit's logic and send the appropriate event itself, but doing so may cause winit's internal state to be inconsistent with the protocol state, so I'm not convinced it would be a good idea.
