### ISSUE TITLE
[MacOS] wrong focus when in fullscreen 

### ISSUE THREAD

**Issue by superlevure** [alacritty/alacritty#4755]
### System

OS: macOS 10.15.7
Version: alacritty 0.7.1 (a852eb8)

Hi, 

The bug does not occur every time and so is hard to reproduce, but this is what's happening: 

When Alacritty is in full screen mode and when the focus is on another app (and so another space), trying to get back to Alacritty via \<cmd> + \<tab> or via clicking on the dock icon sometimes does not resolve to Alacritty but to the Desktop instead, as if there was another Alacritty window/instance on the Desktop but there is not. 
A detail, when it happens the app name in the top left of the MacOS status bar is indeed Alacritty. 

Thanks for your help !

**Comment by nixpulvis** [comment]
Sounds like a duplicate of #3659.
