### ISSUE TITLE
Text not visible in SSH

### ISSUE THREAD

**Issue by husam212** [alacritty/alacritty#4760]
In `htop` for example, the percentages at top and "root" user are not visible, I'm sshing into localhost in the right (focused) window.
![screenshot-20210203-215742](https://user-images.githubusercontent.com/2039727/106802436-a3c40b00-666b-11eb-8d71-137f3e39f9f7.png)

### System

OS: ArchLinux
Version: 0.7.1 (a852eb85)
Linux/BSD: Wayland, Sway

### Config
```
background_opacity: 0.8

scrolling:
  history: 100000

colors:
  primary:
    background: '#000000'
    foreground: '#d3d0c8'
  normal:
    black:   '#000000'
    red:     '#f2777a'
    green:   '#99cc99'
    yellow:  '#ffcc66'
    blue:    '#6699cc'
    magenta: '#cc99cc'
    cyan:    '#66cccc'
    white:   '#d3d0c8'
  bright:
    black:   '#747369'
    red:     '#f2777a'
    green:   '#99cc99'
    yellow:  '#ffcc66'
    blue:    '#6699cc'
    magenta: '#cc99cc'
    cyan:    '#66cccc'
    white:   '#f2f0ec'

font:
  size: 11.5
  normal:
    family: JetBrains Mono
    style: Regular
  bold:
    family: JetBrains Mono
    style: Regular
  italic:
    family: JetBrains Mono
    style: Italic
  bold_italic:
    family: JetBrains Mono
    style: Italic

key_bindings:
  - { key: Return, mods: Control, action: SpawnNewInstance }
  - { key: Escape, mode: Vi|~Search, action: ToggleViMode }
```

**Comment by chrisduerr** [comment]
Change your Alacritty or htop colorscheme.

**Comment by husam212** [comment]
I'm using vanilla `htop`, I tried to delete Alacritty config to use all defaults, same issue.

**Comment by chrisduerr** [comment]
F2 -> Colors -> Broken Gray

**Comment by husam212** [comment]
I'm aware of that option, it fixes the issue for `htop` case.

I'm confused why this issue only happens when using Alacritty and only when SSHing, I'm not able to reproduce it with any other terminal emulator (SSHing or not), so I thought it is something related to Alacritty, I also tried using stayradiated/termcolors to apply the same colorscheme with other emulators but couldn't reproduce it.

**Comment by chrisduerr** [comment]
Might be related to `TERM` you're using on the remote machine.
