### ISSUE TITLE
starting alacritty from within a rust app

### ISSUE THREAD

**Issue by yazgoo** [alacritty/alacritty#4762]
Hi,

I am writing a [status bar in rust](https://github.com/yazgoo/umberbar) which is running in alacritty.

Basically, it spawns alacritty then call itself from within alacritty via `--command` argument with the following code:

```rust
        match std::env::current_exe() {
            Ok(cmd) => {
                let _ = Command::new("alacritty")
                    .env("within_umberbar", "true")
                    .arg("--config-file")
                    .arg(alacritty_conf_path)
                    .arg("--position")
                    .arg("0")
                    .arg("0")
                    .arg("--dimensions")
                    .arg(format!("{}", self.conf.terminal_width))
                    .arg("1")
                    .arg("--class")
                    .arg("xscreensaver")
                    .arg("--command")
                    .arg(cmd).output();
                }
            Err(e) => { print!("{}", e); }
        }
```

I've seen that there is a crate ( https://github.com/alacritty/alacritty/issues/3419 )

I was wondering if I could do something equivalent with it, which would allow to have a self contained binary.

If so, how can I do it ?

Thanks

**Comment by nixpulvis** [comment]
The code separation is split into `alacritty` which is the complete terminal application with window management, rendering, input handling, etc. and `alacritty_terminal` which implements the internal functionality of the terminal like the grid, ANSI handling, tty integration, etc.

Unless you want to wire up your own GUI you probably need both. So if the goal is to distribute a single binary then you may need to modify the whole thing. I wonder why you need to statically link everything though? Surely some users will already have alacritty installed, no?

**Comment by yazgoo** [comment]
Thanks for your answer, this is not necessary per-se.

I just wanted to know if there was an easy way to replace this `Command` call which I find not pretty :P.

Looks to me like the alternative (including all pieces) is quite complicated for now :)

**Comment by chrisduerr** [comment]
There's generally a rather low benefit in using Alacritty for this. Writing your own UI is usually the easy part and it doesn't seem like you have much need for terminal emulation capabilities. Generally that also gives you much more flexibility and room to grow.
