### ISSUE TITLE
Erase the line command key bindings seems not to work

### ISSUE THREAD

**Issue by Kreeg** [alacritty/alacritty#4764]
Hello!
My binding are 
```
- { key: Paste,                                       action: Paste          }
- { key: Copy,                                        action: Copy           }
- { key: L,         mods: Control,                    action: ClearLogNotice }
- { key: Left, mods: Alt, chars: "\e[1;5D" }
- { key: Right, mods: Alt, chars: "\e[1;5C" }
- { key: K, mods: Control, chars: "\x1b[K"} 
```

but it does nothing. If I change command to D or C - it does work.
If I delete all key bindings - Ctrl-K works. But if I delete only Ctrl-K bindings - it does not work.
Is it bug or did I do something wrong?

### System

OS: macOS
Version: 0.7.1

**Comment by chrisduerr** [comment]
I'm not sure what you're trying to do or what your problem is.

**Comment by Kreeg** [comment]
> I'm not sure what you're trying to do or what your problem is.

@chrisduerr I'm trying to bind 'Esc[K' command which clears the line after cursor. And this is not working but I suppose should

**Comment by chrisduerr** [comment]
The `chars` are sent to the stdin of the application, not to the terminal itself.

**Comment by Kreeg** [comment]
@chrisduerr
Look.
If key_bindings is completely commented, Ctrl+K works in alacritty as it should
If key_bindings is somehow filled (even with 1 line) Ctrl+K stop working

**Comment by nixpulvis** [comment]
> If key_bindings is completely commented, Ctrl+K works in alacritty as it should

I'm not sure what application you are using, but I can assure you that Alacritty doesn't handle Ctrl+K specially.

**Comment by Kreeg** [comment]
@nixpulvis hey!
As @chrisduerr mentioned, that was not an alacritty's error.
I've configured alacritty and tmux meticulously from scratch and the problem gone.
Thanks!
