### ISSUE TITLE
Unable to launch a second instance (macOS) on ARM64/M1

### ISSUE THREAD

**Issue by wulymammoth** [alacritty/alacritty#4766]
### System

OS: macOS 11.2
Version: `alacritty 0.8.0-dev (73759da)`

### Logs

```sh
$ tail /var/folders/09/kwnz0jpx15g9mjdgw728d6ph0000gn/T/Alacritty-34293.log
[2021-02-05 08:20:28.710397000] [WARN ] [alacritty] Unable to launch /Users/<redacted>/Desktop/alacritty/target/release/osx/Alacritty.app/Contents/MacOS/alacritty with args ["--working-directory", "/Users/<redacted>"]
```

I built this from source using Rust (nightly). Under normal circumstances this works fine and my old x86_64 binary has no issues launching additional instances with `cmd + n`. However, I've received the aforementioned warning when doing the same

After building, **I moved the application from the above target directory into `/Applications` where macOS apps typically reside.** However, when hitting `cmd + n` the above warning comes up and it looks like it'ss bound to the target release directory where it was originally built into. 

Just wondering if there's an easy fix for this. It's not a big deal, but would be nice to get this working :)

**Comment by chrisduerr** [comment]
ARe you using the SpawnNewInstance action?

**Comment by wulymammoth** [comment]
@chrisduerr thanks for the prompt reply. I'm going to close this. I had spawned the new build originally from the release dir, moved the application, and attempted to spawn a new instance. I quit out of Alacritty entirely, re-launched (from its new location), attempted to kick off new instances without issue! Apologies!
