### ISSUE TITLE
Opacity at 1.0 doesn't fully disable transparency

### ISSUE THREAD

**Issue by mqudsi** [alacritty/alacritty#4767]
On Windows 10, with `background_opacity: 1.0` in `alacritty.yml`, it is possible to discern that transparency is not truly disabled. On displays with sufficient static contrast and color depth and when there are starkly different colors in the background, it is "clear" that while coming very close to being truly opaque, the alacritty window remains - to an extent - translucent.

Here is a screenshot with a white window and a black window side-by-side under the alacritty window that has opacity set to 1.0:

![image](https://user-images.githubusercontent.com/606923/107069055-01a93d80-67a7-11eb-8e77-618946aa8733.png)

And here is that same screenshot but post-processed to increase the brightness and contrast:

![image](https://user-images.githubusercontent.com/606923/107069381-83996680-67a7-11eb-927e-56e1c59f9a31.png)

I'm guessing there is some sort of rounding issue happening with floating point math being performed on the background color with the opacity factoring into it, and the resulting imprecision gives it an opacity that is extremely close to - but not actually - 1.0. The other possibility is that DWM has a "maximum opacity" that a window created with transparency can have, and that the window needs to be created without enabling transparency in order to be truly opaque.

I'm guessing that `background_opacity` needs to be `Option<f32>` rather than `f32` (or `f64`, whatever the case), but I haven't poked into the code to be able to really say, so this is just a hunch.

### System

OS: Windows
Version: 0.2.4
Linux/BSD: N/A

**Comment by chrisduerr** [comment]
>  Version: 0.2.4

Update.

**Comment by mqudsi** [comment]
Sorry, I had built from git but the install step failed and I didn't notice, so I ended up launching the previously installed version.

**Comment by tpict** [comment]
I'm encountering this issue with a more recent version (`alacritty 0.7.2 (5ac8060)`) under macOS 11.2.3.
