### ISSUE TITLE
alacritty colors not working

### ISSUE THREAD

**Issue by Javi3y** [alacritty/alacritty#4769]
hey I'm trying to change my colors in alacritty
this is where i copied the config
~/.config/alacritty/alacritty.yml

I'll attach the file down below
### System

OS: Ubuntu Linux
[alacritty.txt](https://github.com/alacritty/alacritty/files/5935377/alacritty.txt)

**Comment by chrisduerr** [comment]
Is `printf "\e[31mTEST"` not colored?

**Comment by Javi3y** [comment]
> Is `printf "\e[31mTEST"` not colored?

It is
I'm not sure that these colors are the same colors i set them to be

**Comment by adrian5** [comment]
Are you using the correct color format? Unless thing changed, that's `'0xrrggbb'` not `'#rrggbb'`.

**Comment by chrisduerr** [comment]
> It is

Then there is no issue here.

> Unless things changed, that's '0xrrggbb' not '#rrggbb'.

Both work just fine.

**Comment by Javi3y** [comment]
> Are you using the correct color format? Unless things changed, that's `'0xrrggbb'` not `'#rrggbb'`.

thanks a lot that worked
