### ISSUE TITLE
Always launch with zsh under i386 architecture

### ISSUE THREAD

**Issue by crispgm** [alacritty/alacritty#4774]
I run Alacritty on M1 macOS and it basically works well. But I encounter a problem that Alacritty starts very slowly and always launch with zsh under i386 architecture.

Is anyone has the same issue and is there a workaround for this?

**Comment by nixpulvis** [comment]
@crispgm did you install an ARM version of Alacritty?

**Comment by crispgm** [comment]
> @crispgm did you install an ARM version of Alacritty?

I installed with ARM version Homebrew cask. Is there a way to manually install a true ARM Alacritty? Thanks.

**Comment by crispgm** [comment]
I have no idea but I guess [this one](https://bou.ke/blog/macbouk-air/) is possible?

**Comment by chrisduerr** [comment]
Just build it from source.

**Comment by crispgm** [comment]
Thanks, build from source works perfectly! 👍
