### ISSUE TITLE
SSH bookmark manager

### ISSUE THREAD

**Issue by d691maurya** [alacritty/alacritty#4776]
### System

OS: macOS
Version: 0.7.1
Linux/BSD: N/A

### Logs

N/A

### Description

Although may not be absolutely necessary feature, it might come in handy to have a ssh bookmark manager

**Comment by chrisduerr** [comment]
I'm not even sure what you mean by this, but Alacritty certainly isn't the right place for it.

**Comment by d691maurya** [comment]
Sorry, if it wasn't clear earlier, I meant something similar to the attached screenshot. You can get it in Mac terminal via "New Remote Connection".

Thanks for the reply.


![Screenshot 2021-02-10 at 1 14 11 PM](https://user-images.githubusercontent.com/12238760/107480596-d8bbea80-6ba2-11eb-83a2-57a94c42b0ea.png)
