### ISSUE TITLE
Auto updater

### ISSUE THREAD

**Issue by Milo123459** [alacritty/alacritty#4778]
Add an auto-updater or some way to update alacrity. It'd be so helpful.

**Comment by chrisduerr** [comment]
They're already out there. It's called a "package manager".

**Comment by Milo123459** [comment]
Which is it available on? Doesn't seem to be available on scoop.

**Comment by nixpulvis** [comment]
I'm assuming you're on Windows @Milo123459. Unfortunately I'm unaware of a package manager which has Alacritty, but I'm also not really much of a Windows user. Perhaps you can find a way to add it, or request it's addition. We don't manage the distribution of Alacritty here however. Worst case, I bet you could make a simple script to check our https://github.com/alacritty/alacritty/releases.

**Comment by Milo123459** [comment]
Alright thanks

**Comment by chrisduerr** [comment]
Chocolatey offers Alacritty iirc.
