### ISSUE TITLE
Status bar

### ISSUE THREAD

**Issue by Milo123459** [alacritty/alacritty#4779]
Hi,

Something I think that could be cool is a status bar, like VS Code, with plugins. For example, a spotify plugin that updates to whenever you play a new song, or something like that. Would be cool. Let me know of thoughts!

**Comment by nixpulvis** [comment]
This sounds like something your shell could do... if you wanted it. Personally, I don't see why I'd put the current song in every shell prompt when I have an OS status bar at the top of my window, but to each there own.
