### ISSUE TITLE
Remap command to control on Mac? 

### ISSUE THREAD

**Issue by rickalex21** [alacritty/alacritty#4782]
Is there a way to remap command key to control without changing it on a system wide level? I have been looking around for a while now but I can't seem to find the answer. This can be done in iterm2 but I'm not sure how to do it in alacritty. I've looked at other similar issues in the past but I'm not sure if this was fixed or added as a feature yet?  I'm using Mac OS Big Sur with the latest version.

Thanks.

**Comment by chrisduerr** [comment]
There is not.

**Comment by skr4n** [comment]
I use GNU readline/emacs bindings a lot for my shell and I've been looking for the same, moving from iTerm2 to Alacritty.
This workaround works for me:
```toml
[keyboard]
bindings = [
  { key = "A", mods = "Command", chars = "\u0001" },
  { key = "B", mods = "Command", chars = "\u0002" },
  { key = "E", mods = "Command", chars = "\u0005" },
  { key = "F", mods = "Command", chars = "\u0006" },
  { key = "G", mods = "Command", chars = "\u0007" },
  { key = "K", mods = "Command", chars = "\u000b" },
  { key = "L", mods = "Command", chars = "\u000c" },
  { key = "N", mods = "Command", chars = "\u000e" },
  { key = "P", mods = "Command", chars = "\u0010" },
  { key = "R", mods = "Command", chars = "\u0012" },
  { key = "W", mods = "Command", chars = "\u0017" },
  { key = "Y", mods = "Command", chars = "\u0019" },
]
```
