### ISSUE TITLE
Apple Silicon Macs: Terminfo not generated and/or stored in /usr/share/terminfo

### ISSUE THREAD

**Issue by reportaman** [alacritty/alacritty#4785]
Following the [post-build instructions](https://github.com/alacritty/alacritty/blob/master/INSTALL.md#terminfo) to install terminfo doesn't really work on Apple Silicon M1 Mac. Doing a file search under all share/ folders reveals no alacrity terminfo file there, and ``>>infocmp alacritty`` returns ``infocmp: couldn't open terminfo file (null).``

Command (run it from the alacrity build directory):
```
>> sudo tic -xe alacritty,alacritty-direct extra/alacritty.info
```
or
```
>> sudo tic -x -e alacritty,alacritty-direct extra/alacritty.info
```

Then check if all files under /usr/share/terminfo to see if you can find string "alacritty".
 
### System

OS: macOS 11.2 20D64 arm64
Host: Macmini9,1
Kernel: 20.3.0
Shell: zsh 5.8
Resolution: 2880x1620
Version: alacritty 0.8.0-dev (a5e2ccd)
DE: Aqua, WM: Quartz Compositor

**Comment by chrisduerr** [comment]
Can you run tic without sudo?

**Comment by reportaman** [comment]
Wow, it worked without sudo! I even deleted the generated alacritty terminfo under $HOME/.terminfo/<somenumber>/alacritty[-direct], and tried it again with or without sudo. Whenever I use sudo, it doesn't generate anything there or under /usr/share or under $HOME/.terminfo, and `infocmp alacritty` returns ``infocmp: couldn't open terminfo file (null).``  Without sudo this worked well, don't know what could be causing this. Isn't sudo just changing permissions...

**Comment by chrisduerr** [comment]
Are you running with a native version of Alacritty?

Either way this would be a tic issue, but there might be some problems with executing this from an x86 terminal.
