### ISSUE TITLE
Shouldn't the default shell be a login shell?

### ISSUE THREAD

**Issue by juanibiapina** [alacritty/alacritty#4786]
Like the title says, Alacritty doesn't seem to run the default shell in login mode. Should it? I'm not sure what iTerm does. Tmux does spawn login shells.

### System

OS: Linux (NixOS)
Version: alacritty 0.7.1
Linux: X11, Awesome WM

**Comment by chrisduerr** [comment]
It shouldn't, no.

**Comment by juanibiapina** [comment]
The documentation says that In the mac version it does try to use `bash --login` by default. I couldn't find that in the code, and I'm also confused why it would be different between OSX and Linux.

**Comment by juanibiapina** [comment]
These two links help understand the issues a little bit:

- https://unix.stackexchange.com/questions/324359/why-a-login-shell-over-a-non-login-shell
- https://unix.stackexchange.com/questions/38175/difference-between-login-shell-and-non-login-shell

So it looks like it is indeed different in OSX, and it shouldn't spawn a login shell in Linux.

**Comment by juanibiapina** [comment]
According to the second link:

> When you log in in graphical mode (on an X display manager), you don't get a login shell, instead you get a session manager or a window manager.

> When you start a shell in a terminal in an existing session (screen, X terminal, Emacs terminal buffer, a shell inside another, etc.), you get an interactive, non-login shell.

Which is the problem I have. By following the conventions I simply have no login shell.

I hope this helps future people.
