### ISSUE TITLE
Alacritty intialize glyph cash slow

### ISSUE THREAD

**Issue by Moggel12** [alacritty/alacritty#4787]
When trying to start alacritty, it seems that initializing the glyph cash takes around 30 seconds, meaning that alacritty takes a very long time to appear.

### System
OS: Linux (Arch)
Version: 0.7.1 (a852eb85)
Linux/BSD: X11, XMonad, Picom (ibhagwan)

### Logs
See attached file:
[test.txt](https://github.com/alacritty/alacritty/files/5965882/test.txt)

**Comment by chrisduerr** [comment]
How many fonts do you have installed?

**Comment by Moggel12** [comment]
Accoding to `fc-list | wc -l` I have 885, though I thought I installed only a few extra, other than those that come with the standard Arch ISO.

**Comment by chrisduerr** [comment]
Did you install Alacritty with your package manager?

**Comment by Moggel12** [comment]
Yes, I installed it through pacman.

**Comment by chrisduerr** [comment]
> Cell size: 5709 x 11038

Can you try `WINIT_X11_SCALE_FACTOR=1 alacritty`?

**Comment by Moggel12** [comment]
I can try that yes

**Comment by chrisduerr** [comment]
Workaround landed on master: fc87aaa4b10b9a5949fa2eae9e33ef66949b70d3.

**Comment by Moggel12** [comment]
It seems to have worked, sorry about the late answer, I needed some time to figure out whether I was just lucky or not.
