### ISSUE TITLE
alacritty massive font size

### ISSUE THREAD

**Issue by default-303** [alacritty/alacritty#4788]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Manjaro KDE Linux
Version: alacritty 0.7.1 (a852eb85)
Linux/BSD: X11/Wayland, DE or Compositor and WM

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: 
[Alacritty-3393.log](https://github.com/alacritty/alacritty/files/5966271/Alacritty-3393.log)

Keyboard and bindings : no changes made (new setup)

hey, i just installed alacritty to replace my konsole, but was let down by the massive font size, i tried to change the 'size' attribute in the config file but it clearly didnt work. 

Any fix for this ??

Thanks

**Comment by chrisduerr** [comment]
Is this fixed by running `WINIT_X11_SCALE_FACTOR=1 alacritty`?

**Comment by default-303** [comment]
thanks a lot,  typing that in a terminal emulator opens alacritty window with normal font but making a shortcut with that exact command doesnt do anything .

**Comment by chrisduerr** [comment]
You can export that environment variable in your Alacritty config.

**Comment by ben2talk** [comment]
How do we 'export that environment variable' in the config?
`export WINIT_X11_SCALE_FACTOR=1` fails.

**Comment by binaerbaum** [comment]
> How do we 'export that environment variable' in the config?
> `export WINIT_X11_SCALE_FACTOR=1` fails.

You can set it in your config file in the `env` section:
```
env:
  WINIT_X11_SCALE_FACTOR: "1"
```
