### ISSUE TITLE
set environment variable TERM_PROGRAM to "Alacritty"

### ISSUE THREAD

**Issue by reportaman** [alacritty/alacritty#4793]
Many terminal emulators set the environment variable TERM_PROGRAM to a sensible value that can be used to uniquely identify them. It works on my system with WezTerm, iTerm2, Terminal.app. It doesn't work on all terminals, but if devs of all terminals start accepting this, it can become a standard. Currently Kitty terminal emulator, and Alacritty do not set these.

### System

macOS Big Sur 11.2
Alacritty alacritty 0.8.0-dev (a5e2ccd)

**Comment by chrisduerr** [comment]
You shouldn't need to uniquely identify your terminal.

**Comment by reportaman** [comment]
@chrisduerr One needs to for applications like vim! I am using it in my ``.vimrc`` to selectively set enable option ``termguicolors`` as not all terminal emulators support true colors. That way one ``.vimrc`` file will work across OSes/devices/terminals.

**Comment by chrisduerr** [comment]
Terminal properties should not be identified by terminal name.

**Comment by reportaman** [comment]
@chrisduerr Ok, can you please point to an alternative way? I could not find this anywhere online...

**Comment by chrisduerr** [comment]
Terminal capabilities should be queried using terminfo. Though for truecolor there's also a relatively common environment variable as alternative.

**Comment by reportaman** [comment]
> You shouldn't need to uniquely identify your terminal.

There is one case where it is necessary to identify terminal. Given Alacritty does not have fallback fonts, a program that I wrote that uses Heavy Double Turned Comma Quotation Mark Ornament  https://github.com/alacritty/alacritty/issues/5980#issue-1187116293 displays tofu only in Alacritty. Even as dumb a terminal as Terminal.App is able to show it correctly. So it would be nice to be able to set an environment variable that is unique to Alacritty. Not sure if TERM_PROGRAM is the correct variable as TMUX uses it too.

**Comment by kchibisov** [comment]
>There is one case where it is necessary to identify terminal. Given Alacritty does not have fallback fonts

It does perform font fallback, if it's for some cases, it should be fixed and not worked around by some stupid hacks like checking for env variable in terminal.
