### ISSUE TITLE
Searching for .+/.* will freeze Alacritty

### ISSUE THREAD

**Issue by chrisduerr** [alacritty/alacritty#4800]
There seems to be an issue with searching for certain regexes like `.*`, which cause Alacritty to freeze.

This is likely a regression introduced in 530de00049c2afcc562d36ccdb3e6afa2fe396a5.

**Comment by nixpulvis** [comment]
@jrowlingson just to be clear.

- Your comment doesn't sound related to this issue, or is it only still freezing when you search for a regex like `.*`?
- System-wide meaning Alacritty is somehow freezing your whole DE/OS, that seems like another thing altogether?
