### ISSUE TITLE
Keyboard input delay and lag

### ISSUE THREAD

**Issue by bsucker98** [alacritty/alacritty#4801]
### System

OS: Linux
Version: 0.7.1 
Linux/BSD: X11

I recently build a new PC with GeForce GT 710  in case if that matters. Before i was using alacritty on another PC which had integrated graphics. Had no issues with alacritty on that and was noticeably faster than other terminals. Now in my new PC alacritty **often** has a significant keyboard input latency and sometimes it doesn't show up the pressed character until the next keypress. Sometimes when I type fast, It doesn't sync up with my typing speed, so i end up typing the same character twice and i have to backsapce and type back. In fact at first I even thought this is a delay in my keyboard.

I'm using the same config i used in my old PC, and it's just a simple config with almost only font family change and some keybindings. I'm not sure what should I do to provide any proof (i.e: screenshots). I was wondering perhaps this has to do with my GPU

**Comment by chrisduerr** [comment]
Did you compile it from source or install through your package manager? This sounds like your system is having some issues.

**Comment by bsucker98** [comment]
installed it through the package manager and my OS is Solus Linux. Is it like something to do with packages missing or maybe i should try by compiling from source

**Comment by chrisduerr** [comment]
Compiling from source is definitely worth a shot. Making sure that nothing is logged to stdout/stderr might also provide some insights.

**Comment by bsucker98** [comment]
Tried installing via cargo, still the same, now I'm gonna try compiling from source

**Comment by bsucker98** [comment]
Okay tried compiling from source and still having the same issue.
Does trying on another OS in a virtualbox or by live booting would work? 

>  sometimes it doesn't show up the pressed character until the next keypress.
turns out it shows the pressed character not only after the next keypress but also after a mouse click

**Comment by chrisduerr** [comment]
> Does trying on another OS in a virtualbox or by live booting would work?

It should work of course, yes.

Are you running proprietary nvidia drivers?

**Comment by bsucker98** [comment]
> It should work of course, yes.

Nice. I'll try Pop OS and will see if the issue exist on that as well

> Are you running proprietary nvidia drivers?

I guess yah. I installed the proprietary nvidia drivers provided by Solus via an app called DoFlicky (this an app by the OS)

**Comment by bsucker98** [comment]
> > It should work of course, yes.
> 
> Nice. I'll try Pop OS and will see if the issue exist on that as well
> 
> > Are you running proprietary nvidia drivers?
> 
> I guess yah. I installed the proprietary nvidia drivers provided by Solus via an app called DoFlicky (this an app provided by the OS)

**Comment by chrisduerr** [comment]
This might be an nvidia driver issue. Testing out nouveau if it works at all with that GPU might be worth a shot.

**Comment by bsucker98** [comment]
Oh! I'll try that one...

**Comment by bsucker98** [comment]
Since nouveau was already installed I just removed the proprietary drivers from the DoFlicky and when I restarted, it didn't start :( (blinking cursor on black screen )and was left with TTY terminal. Once I installed nvidia-glx-drivers worked again

So Imma try on Pop OS on a virtual box

**Comment by bsucker98** [comment]
Experienced the same delay with [Rofi](https://github.com/davatorium/rofi). It seems like it's not an issue with Alacritty, not sure if it's the same issue with Rofi tho.....
But I tried another gpu accelerated terminal and it works totally fine

**Comment by chrisduerr** [comment]
It's probably an issue somewhere in your system. Maybe try checking your system/X11 logs.

**Comment by WillyWonksters** [comment]
This issue goes away for me when I change my power profile.

I am running Pop!_OS on an HP Dev One, with integrated AMD graphics, Ryzen 5850U.

This issue arises anytime I change my power profile to 'Battery Life'.

**Comment by f0rdprefect** [comment]
> Since a couple of month I have the same problem. Now switched to kitty and no input lag at all. Arch + intel GPU

Building from source has solved that issue for me!

**Comment by liamnaddell** [comment]
Ran into this on 
```
04:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Barcelo (rev c3) (prog-if 00 [VGA controller])
	Subsystem: Lenovo Device 50b1
	Flags: bus master, fast devsel, latency 0, IRQ 41, IOMMU group 12
	Memory at 260000000 (64-bit, prefetchable) [size=256M]
	Memory at 270000000 (64-bit, prefetchable) [size=2M]
	I/O ports at 1000 [size=256]
	Memory at fd300000 (32-bit, non-prefetchable) [size=512K]
	Capabilities: <access denied>
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu
	```
Compiling from source also seemed to fix the problem for me, so +1
