### ISSUE TITLE
Rendering PowerLevel10k in Alacritty

### ISSUE THREAD

**Issue by ShivamPT4I21** [alacritty/alacritty#4802]
I am using zsh them `powerlevel10k` for my terminator and it runs fine, but the `alacrity` seems to have some problem with the rendering of `powerlevel10k` although I have installed the `Ubuntu Mono Nerd Fonts`, so now the icons are visible, but the tails of the prompt tell another story.
 
![image](https://user-images.githubusercontent.com/76120386/108177108-cdc80380-7128-11eb-946c-f547dffaa515.png)

In the image, the top one is the `alacritty` and the bottom one is `terminator`, also the basic Linux terminal gives a good response. 

Any suggestion if I should use any other zsh-theme to get a clear view or if it is possible to fix the `powerlevel10k-alacritty` itself.
### System

OS: Linux[Ubuntu 20.04]
Version: 0.8.0-dev

**Comment by chrisduerr** [comment]
Alacritty uses your font to render the glyphs, this is working as intended.
