### ISSUE TITLE
Italic doesn't display with Source Code Pro font

### ISSUE THREAD

**Issue by timsofteng** [alacritty/alacritty#4803]
Hello.
Italic font with `source code pro` doesn't display, However it works with another fonts.
It works ok in another terminal emulator's as well. Look at the screencast please.

https://user-images.githubusercontent.com/51912173/108225068-3a043080-7144-11eb-9c2f-55920e6b63e2.mp4

### System

OS: Linux
Version: 0.7.1
Linux: X11, Gnome

**Comment by chrisduerr** [comment]
Do you have a font installed with the name `Source Code Pro Italic`?

**Comment by timsofteng** [comment]
> Do you have a font installed with the name `Source Code Pro Italic`?

I have source code pro which include many styles and italic as well.

**Comment by chrisduerr** [comment]
Can you remove all fonts other than the `normal` one please?

**Comment by timsofteng** [comment]
> Can you remove all fonts other than the `normal` one please?

still doesn't work
(commented lines should be italic according to my colorscheme in vim)
![image](https://user-images.githubusercontent.com/51912173/108263532-15717e00-716f-11eb-91b5-55b743702f68.png)

**Comment by chrisduerr** [comment]
What does this command give you: `fc-match -s "Source Code Pro:style=Italic"`?

**Comment by timsofteng** [comment]
Hm. It's strange but it can't find it

`fc-match -s "Source Code Pro:style=Italic"
SourceCodePro-Regular.otf: "Source Code Pro" "Regular"
DejaVuSans.ttf: "DejaVu Sans" "Book"
DejaVuSans-Bold.ttf: "DejaVu Sans" "Bold"
DejaVuSans-Oblique.ttf: "DejaVu Sans" "Oblique"
DejaVuSans-BoldOblique.ttf: "DejaVu Sans" "Bold Oblique"
Arial_Regular.ttf: "Arial" "Обычный"
DejaVuSerif-Italic.ttf: "DejaVu Serif" "Italic"
DejaVuSansMono.ttf: "DejaVu Sans Mono" "Book"
DejaVuSerif.ttf: "DejaVu Serif" "Book"
DejaVuMathTeXGyre.ttf: "DejaVu Math TeX Gyre" "Regular"
DejaVuSansMono-Bold.ttf: "DejaVu Sans Mono" "Bold"
DejaVuSerif-Bold.ttf: "DejaVu Serif" "Bold"`

but i can see it wtih this command
`family style | grep -i "source code pro"
Source Code Pro,Source Code Pro Semibold:style=Semibold Italic,Italic
Source Code Pro:style=Bold
Source Code Pro,Source Code Pro Semibold:style=Semibold,Regular
Source Code Pro:style=Italic
Source Code Pro,Source Code Pro Light:style=Light Italic,Italic
Source Code Pro,Source Code Pro ExtraLight:style=ExtraLight Italic,Italic
Source Code Pro:style=Bold Italic
Source Code Pro,Source Code Pro Black:style=Black Italic,Italic
Source Code Pro,Source Code Pro Medium:style=Medium,Regular
Source Code Pro,Source Code Pro Black:style=Black,Regular
Source Code Pro,Source Code Pro Light:style=Light,Regular
Source Code Pro:style=Regular
Source Code Pro,Source Code Pro Medium:style=Medium Italic,Italic
Source Code Pro,Source Code Pro ExtraLight:style=ExtraLight,Regular`

**Comment by nixpulvis** [comment]
I have a separate file for the italics stored in `/usr/share/fonts/adobe-source-code-pro/SourceCodePro-It.otf`. I don't know if this helps you or not.

**Comment by chrisduerr** [comment]
Yeah as demonstrated by fontconfig, this is an issue with your system.
