### ISSUE TITLE
Question: how to reproduce Alacritty look from README

### ISSUE THREAD

**Issue by AdamJel** [alacritty/alacritty#4807]
Hello, 
thank you for this great project. I would like to ask, what configuration and/or plugins where used to get the [look of Alacritty as shown in the README](https://user-images.githubusercontent.com/8886672/103264352-5ab0d500-49a2-11eb-8961-02f7da66c855.png)? That would be those header and footer partly red lines and theme. 

Thank you

**Comment by chrisduerr** [comment]
That's just the default Alacritty configuration without any changes combined with the Fira Mono font and some vim plugins.

**Comment by Nijinsha** [comment]
Please share the  vim color scheme.
