### ISSUE TITLE
Clipboard Does Not Update On Subsequent Copy On Latest Fedora+Wayland

### ISSUE THREAD

**Issue by AdamMartinCote** [alacritty/alacritty#4810]
## Steps to reproduce
 - Install alacritty 0.7.1 from dnf on an up-to-date version of Fedora 33 + Gnome + Wayland
 - open alacritty and enter a command
 - select a word and press Crtl+Shift+C then Ctrl+Shift+V
   - result: the selected text is pasted as expected
 - select a different word and press Ctrl+Shift+C then Ctrl+Shift+V
   - result: 
     - the first selected text is still pasted, all subsequent copy fail to overwrite the clipboard
     - repeating the same step with Primary clipboard (select + middle mouse button) produce the same result (both clipboards keep their respective values)

### System
OS: Fedora 33
Version: 0.7.1
Linux/BSD: Wayland Gnome

**Comment by chrisduerr** [comment]
Fixed on master.
