### ISSUE TITLE
Incorrect Cursor Position Indicator During Search

### ISSUE THREAD

**Issue by nixpulvis** [alacritty/alacritty#4811]
With a custom binding that is admittedly strange and perhaps unwanted, the cursor position indicator will change while the grid does not.

With these bindings:

```yaml
key_bindings:
  - { key: Return, mode: Vi, action: SearchNext }
  - { key: Return, mode: Vi, action: SearchNext }
```
Enter vi-mode, then search for `.*` (for example), and press return. Notice the changing scroll indicator.

**Comment by nixpulvis** [comment]
Sounds like the solution is to disable `SearchNext` during a Search mode within a Vi mode.

**Comment by chrisduerr** [comment]
This is not an issue with the cursor position during search.

**Comment by nixpulvis** [comment]
If you want fewer "dumb" bug reports, you need to understand the value in teaching users how things work. Our UX is getting out of hand to the point I cannot understand how I expect things like this to work.

**Comment by chrisduerr** [comment]
You're the only person I've ever had complain about any of this.

**Comment by nixpulvis** [comment]
I wonder how many people are even using any of the search configurations you've added?

**Comment by chrisduerr** [comment]
If nobody needs it and everyone's fine with the default, that sounds good to me.

**Comment by nixpulvis** [comment]
I use it, and I'm not fine with the default. But in the process of trying to use it I find myself confused by the way it works.

**Comment by chrisduerr** [comment]
I mean I have no problem with restricting vi motion actions to not be usable in search mode. But that might turn out messy. We already restrict them to only be available during vi mode, so it might not be that bad.
