### ISSUE TITLE
Seaching for `.............` Causes Highlighing Problem

### ISSUE THREAD

**Issue by nixpulvis** [alacritty/alacritty#4812]
Enter Search (either vi or non-vi) and continue to enter periods (`.`). See the highlighting get very strange.

![20210218_17h03m15s_grim](https://user-images.githubusercontent.com/715947/108427473-37b8d980-720b-11eb-865b-238b13f0399f.png)

**Comment by chrisduerr** [comment]
What about this would you consider "strange"?

**Comment by nixpulvis** [comment]
> What about this would you consider "strange"?

It should be apperant.

The fact that the right side of the window gets a number of columns which aren't highlighted that grows and grows until at seemingly random times it shrinks, then grows more. I have obviously not looked into the code to see what is causing this, but I would call it highly strange behavior.

If it's any further indication, here's one where I'm just matching on `\s` spaces.

![20210218_17h10m28s_grim](https://user-images.githubusercontent.com/715947/108428250-43f16680-720c-11eb-9c8b-f7c64d2dfe6e.png)

**Comment by chrisduerr** [comment]
> The fact that the right side of the window gets a number of columns which aren't highlighted that grows and grows until at seemingly random times it shrinks, then grows more. I have obviously not looked into the code to see what is causing this, but I would call it highly strange behavior.

How is it strange that when you have a fixed number of columns and expect a match with a length of exactly N columns, that if the number of total columns isn't divisible by N you'll end up with a bunch of columns at the end that are not part of any match?

That surely doesn't surprise you?

**Comment by nixpulvis** [comment]
LOL that is very true.

**Comment by nixpulvis** [comment]
I'm in a everything is shit mood today aren't I.

**Comment by chrisduerr** [comment]
> I'm in a everything is shit mood today aren't I.

Hah, I'll take what I can get.

**Comment by nixpulvis** [comment]
That said, `vim` handles this much more gracefully, not considering "empty` cells to be part of the match, which was adding to my confusion.

**Comment by chrisduerr** [comment]
Yeah, that's a more general thing though which was tracked in a different issue. But iirc I closed that because it's not usually worth the effort.

**Comment by nixpulvis** [comment]
I might argue, but I'm officially burnt out for the day. So we'll have to see ;)

**Comment by nixpulvis** [comment]
Something really is wrong with this...

I'll have to look i to how we represent and search across lines exactly, but I suspect it boils down to treating all empty cells as either 1) not part of search, or 2) all one line.

**Comment by chrisduerr** [comment]
Why would there be anything wrong with this? I still haven't seen you demonstrate any issue whatsoever.

**Comment by nixpulvis** [comment]
Let me try to explain my possible compliant with a simple example. Given the string `nnn` I think I would expect both the first `[nn]n` and the second `n[nn]` to be matched. This helps understand the behavior of the repeated `.` case, since essentially we consume the matching string as we apply the regex, making it impossible to match the complete grid unless it's width is divisible by the number of `.`s.

For what it's worth, I think I found something of a bug in Firefox with this matching one pair of ns in the forward search (<kbd>Enter</kbd>) and the other pair of ns in the backward direction (<kbd>Shift</kbd> + <kbd>Enter</kbd>).

I can already see some performance implications of my suggested functionality, but I might have an idea of a way around some of it. I'm just not sure we agree on the ideal behavior either.

Sorry for the lack of detail in the earlier comments.

**Comment by chrisduerr** [comment]
Overlapped matches are intentionally not considered separately. This is by design.

**Comment by nixpulvis** [comment]
OK fair enough. Especially given the upcoming "hints" feature I think this makes the most sense too.

I _was_ thinking for the purposes of search highlighting alone you could avoid the serious performance penalty of substring matching everything by only restarting the search on existing matches, even only those in the viewport. But, given how hinting a key to press for an action will work, it seems possibly very confusing, and would likely require a whole set of colors to highlight the hints instead of the one we currently need.

This turns out to be a little bit harrier of an issue than I might have guessed at the start, lol.

**Comment by chrisduerr** [comment]
It wouldn't actually be difficult to do this, it's just not something that I want. I believe while implementing search I actually had this in accidentally until I fixed things up to work properly. Vim does the same by the way.

It just gets very complicated when you do things like that, because a match might be all kinds of different combinations of a word. It just doesn't make much sense to do anything other than going as greedy as possible.

**Comment by nixpulvis** [comment]
I guess if we supported a forward look-ahead (e.g. `(?= ...)`) we might be able to do what I was expecting at first, but there's really no issue.

**Comment by nixpulvis** [comment]
> Yeah, that's a more general thing though which was tracked in a different issue. But iirc I closed that because it's not usually worth the effort.

Development effort, or did you look into this already and decide it's expensive for the search algorithm for some reason?

**Comment by chrisduerr** [comment]
The feature makes no sense from a UX perspective.

**Comment by nixpulvis** [comment]
I disagree strongly. I've shown this behavior to some people and they were also confused about it. Vim does what I'm proposing, and for good reason if you ask me. There's no sense searching empty cells as if they were spaces or anything else.

**Comment by chrisduerr** [comment]
Vim does exactly what Alacritty does if you fill the entire buffer with whitespace.

**Comment by nixpulvis** [comment]
> Vim does exactly what Alacritty does if you fill the entire buffer with whitespace.

Yes, I'm aware of this fact. I'm saying that we should ideally not treat empty cells as if someone put whitespace in them.

**Comment by chrisduerr** [comment]
There's literally no difference between empty cells and whitespace in a terminal.
