### ISSUE TITLE
Alacritty unusually laggy after nvidia driver installation

### ISSUE THREAD

**Issue by zeuph** [alacritty/alacritty#4813]
Hello, please forgive me if I'm not detailed enough.

As the title says, I installed nvidia drivers and now whenever I resize any alacritty window it lags my computer. Floating windows are fine, they resize and move smoothly but do take a lot of resources on the GPU. If I have two alacritty windows open and tiling they lag to the point of  freezing my computer for a few seconds. Other windows do not.

Using Nvtop I noticed that under the CPU tab alacritty can reach up to 80%+. [Here's a picture of this happening](https://i.imgur.com/NG84hBh.png). This is only when resizing the windows it reaches these high usage %. During idle it's 0-2%. Killing picom doesn't change much.

I've tried re-installing alacritty and my system is recently updated.

### System

OS: Linux 5.10.16-arch1-1
Version: alacritty 0.7.1 (a852eb85)
Linux/BSD: X11/picom,bspwm
GPU: GeForce GTX 1080

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by chrisduerr** [comment]
If a driver update causes problems, why are you reporting it to Alacritty? Sounds like there's an issue with your driver.
