### ISSUE TITLE
Possible memory leak.

### ISSUE THREAD

**Issue by L117** [alacritty/alacritty#4815]
I'm not much familiar with `alacritty` sources, but it seems I've found a memory leak anyway.
Here buffers are created:
https://github.com/alacritty/alacritty/blob/3dafec076b7a69aaa80a66f9de9930da78d23c00/alacritty/src/renderer/mod.rs#L561-L562
Corresponding `gl::DeleteBuffers` call must exist somewhere in code, but `git grep DeleteBuffers` shows nothing.
The fact that data is uploaded with `GL_STREAM_DRAW` may cause it to stay on main, non-GPU RAM, what causes visible memory leaks if `QuadRenderer` is ever drop-ped and recreated.

**Comment by chrisduerr** [comment]
> The fact that data is uploaded with GL_STREAM_DRAW may cause it to stay on main, non-GPU RAM, what causes visible memory leaks if QuadRenderer is ever drop-ped and recreated.

But it's never dropped and recreated?

**Comment by L117** [comment]
> > The fact that data is uploaded with GL_STREAM_DRAW may cause it to stay on main, non-GPU RAM, what causes visible memory leaks if QuadRenderer is ever drop-ped and recreated.
> 
> But it's never dropped and recreated?

I don't know. You are the developer - you should know better. But even if there's no leak, `gl::DeleteBuffers` call should exist somewhere anyway, is not it? For the sake of code correctness?

**Comment by chrisduerr** [comment]
> I don't know. You are the developer

You are claiming there's a memory leak, not me. So you tell me. I don't see an issue.

**Comment by L117** [comment]
I don't claim there's a memory leak. I've only said it is *possible*.
I've compiled `Alacritty` and there's exactly one instance of `QuadRenderer` , as you said. But neither VAO, nor *BO are freed, so there's a leak. It is not a big one and it seems to be okay to let the system free it up for us when Alacritty terminates. But is there a good reason why `Drop` implementation is missing for `QuadRenderer`? Should I create a PR or it is intentional?

**Comment by chrisduerr** [comment]
If this is dear to your heart, you can create a PR. but it serves no purpose since the `QuadRenderer` will never be created more than once and freeing it during drop is not necessary.

There's no memory being leaked, the memory is used for the entire execution of the program and there is no accumulation of memory usage.

**Comment by Tandolf** [comment]
You are claiming there is a possible memory leak. Then you do some investigation and prove your thesis instead of telling an open source software "you maybe have a leak, you have to go and check".

Its not the developers job to prove you are right, its your job to prove that the developers are wrong.

**Comment by L117** [comment]
You know, it is wrong to demand anything from OSS developers. But there's nothing wrong with reporting [possible] bugs or asking questions. After all, if developer decides that report lacks information or is not worth investigating, (s)he can just close the issue with arbitrary reason.

**Comment by Tandolf** [comment]
> I don't know. You are the developer - you should know better.

it is wrong to demand a spare time OSS developer to figure out your "hunch". Make an effort, learn the codebase, prove your point. make a PR.

**Comment by L117** [comment]
> > I don't know. You are the developer - you should know better.
> 
> it is wrong to demand a spare time OSS developer to figure out your "hunch". Make an effort, learn the codebase, show that it is a memory leak. then ask the devs to solve it, or make a PR.

No, it is not a demand. Sorry if this sounded rude or offensive, this is not intentional. What I meant is "You are the developer, so you're already familiar with codebase and you probably know the answer".
And I did a PR, that adds missing cleanup calls. Even if they are not strictly needed.
