### ISSUE TITLE
`shell.program` not works

### ISSUE THREAD

**Issue by TENX-S** [alacritty/alacritty#4817]
OS: Windows 10
Version: 0.7.1

I installed powershell 7, but when the value of `shell.program` is `powershell`, it starts the powershell 5 that comes with the system which is not configured. Even I set the shell path, it still not works.

```yaml
shell:
  program: C:\\Program Files\\PowerShell\\7\\pwsh.exe
  args: --nologo
```

**Comment by chrisduerr** [comment]
What still not works?

**Comment by TENX-S** [comment]
> 
> 
> What still not works?
I hope that the shell started by alacritty is powershell 7 instead of the powershell 5 that comes with the system.

**Comment by chrisduerr** [comment]
If you set the shell to powershell 7, that's what will be launched.

**Comment by TENX-S** [comment]
> 
> 
> If you set the shell to powershell 7, that's what will be launched.

Alacritty has crashed.

**Comment by chrisduerr** [comment]
Wath what error?

**Comment by TENX-S** [comment]
> 
> 
> Wath what error?

No error, just shut down instantly

**Comment by chrisduerr** [comment]
There's nothing in stderr/out?

**Comment by TENX-S** [comment]
> 
> 
> There's nothing in stderr/out?

I install alacritty from [Alacritty-v0.7.1-installer.msi](https://github.com/alacritty/alacritty/releases/tag/v0.7.1). Launched by shortcut.

**Comment by chrisduerr** [comment]
Try launching it from another terminal.

**Comment by TENX-S** [comment]
> 
> 
> Try launching it from another terminal.

I tried to do this, but `cargo install alacritty` gave a compilation error:
```shell
error: failed to compile `alacritty v0.7.2`, intermediate artifacts can be found at `C:\Users\Ares\AppData\Local\Temp\cargo-install1lu1gC`

Caused by:
  failed to run custom build command for `alacritty v0.7.2`

Caused by:
  process didn't exit successfully: `C:\Users\Ares\AppData\Local\Temp\cargo-install1lu1gC\release\build\alacritty-257aa206380a6a14\build-script-build` (exit code: 101)
  --- stdout
  cargo:rustc-env=GIT_HASH=
  Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
  Copyright (C) Microsoft Corporation.  All rights reserved.

  fatal error RC1110: could not open ../extra/windows/windows.rc

  --- stderr
  thread 'main' panicked at 'RC.EXE failed to compile specified resource file', C:\Users\Ares\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\embed-resource-1.6.1\src\windows_msvc.rs:33:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by chrisduerr** [comment]
Probably didn't follow all the installation instructions. Though you don't need to build from source to execute it from a terminal.

**Comment by TENX-S** [comment]
> 
> 
> Probably didn't follow all the installation instructions. Though you don't need to build from source to execute it from a terminal.

So I try to launch it from another terminal, just shut down instantly again, without stderr/out.
![image](https://user-images.githubusercontent.com/40336192/108582366-c2b1e500-736d-11eb-8ec6-1c8b4a64c297.png)

**Comment by chrisduerr** [comment]
Can you execute the shell command from Alacritty with the default powershell set?

**Comment by TENX-S** [comment]
> 
> 
> Can you execute the shell command from Alacritty with the default powershell set?

Yes, alacritty works totally fine with the default powershell set.

**Comment by chrisduerr** [comment]
And you can launch powershell 7 from that using the specified executable with `--no-logo`?

**Comment by TENX-S** [comment]
> 
> 
> And you can launch powershell 7 from that using the specified executable with `--no-logo`?

Yes, that works.
![image](https://user-images.githubusercontent.com/40336192/108583711-86cf4d80-7376-11eb-8c0f-f4e08bfb8773.png)

**Comment by chrisduerr** [comment]
Could you change args to `args: ["--no-logo"]`?

**Comment by TENX-S** [comment]
> Could you change args to `args: ["--no-logo"]`?

You mean change the configuration file of alacritty like below?
```shell
shell:
  program: Powershell 7
  args: ["--no-logo"]
```

And I launch it from another terminal, still crashed, no stdout/err.

**Comment by chrisduerr** [comment]
Don't change the program, that makes no sense as an executable.

**Comment by TENX-S** [comment]
So just like below ?
```yaml
shell:
  args: ["--no-logo"]
```

![image](https://user-images.githubusercontent.com/40336192/108613966-6dd7a280-7431-11eb-94c0-6b7d8f29038e.png)

**Comment by nixpulvis** [comment]
That's an unfortunate error message, but I think what @chrisduerr meant was that you should not change the `program` from what you had in your config above.

Try this:

```yaml
shell:
  program: C:\\Program Files\\PowerShell\\7\\pwsh.exe
  args: --no-logo
```

**Comment by TENX-S** [comment]
> 
> 
> That's an unfortunate error message, but I think what @chrisduerr meant was that you should not change the `program` from what you had in your config above.
> 
> Try this:
> 
> ```yaml
> shell:
>   program: C:\\Program Files\\PowerShell\\7\\pwsh.exe
>   args: ["--no-logo"]
> ```

![crash](https://user-images.githubusercontent.com/40336192/108614857-29e89b80-7439-11eb-9cc0-b398a9b7152b.gif)

**Comment by TENX-S** [comment]
Finally, it works, just need to replace `args: ["--no-logo"]` with `args: ["--nologo"]`.
It's seems like my first attempt is very close to this solution, just missing the `[]` in args.

**Comment by nixpulvis** [comment]
What an adventure.

**Comment by chrisduerr** [comment]
@nixpulvis Remind me that next time someone has trouble with their shell and isn't getting an error message, they should probably start it with `--hold`. That will print stderr when the shell itself throws a fit.

**Comment by nixpulvis** [comment]
@chrisduerr I was thinking the same thing, but I thought I remembered it having issues and steering people away from it. It works for me, so IDK.

**Comment by sisrfeng** [comment]
This works:
```
shell:
  program: C:\\Program Files\\PowerShell\\7\\pwsh.exe
```

**Comment by Abhi-Survase** [comment]
For anyone new to Alacritty on Windows. Nothing seemed to work for me until I figured out that config in `%AppData%/Roaming/alacritty` should end with `.yml` instead of `.yaml`

Once I renamed my config to .yml Alacritty started-up fine and gave me prompt saying .yml is deprecated and prompted me to migrate to .toml using `alacrity migrate`
