### ISSUE TITLE
Alacritty not displaying (resizing) programs 

### ISSUE THREAD

**Issue by cookEbox** [alacritty/alacritty#4818]
### System

OS: Linux/
Version: alacritty 0.7.1 (a852eb85)
Linux (Arch): X11, Picom and Qtile WM

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

I have been using alacritty for the alst few weeks and I have really been happy with it. I did an update (though I don't think it included alacritty) today and alacritty no longer displays programs like calcurse, neomutt, newsboat and cmus. It seems like its not handling drawing the program in relation to the size of the terminal. When it does it get it right it does not handle being changed up/down the stack. It is handling vim fine (to my knowledge).

I also have URxvt and this is handling these programs fine (though when working I prefer alacritty). I'm wandering if there are any dependenise that alacritty uses for resizing as since the update a few popups (from other programs like firefox) appear in a weird place as well. As I said I don't think the update included alacritty.

I ran `alacritty -vv` and it opens a terminal that opens calcurse sized correctly but does not handle it being moved.
`alacritty --print-events` can be found at https://pastebin.com/6Qdu7BTU 

Any other logs or screenshots you'd like please let me know (I am still relatively new to linux).

Thanks

Nick

**Comment by chrisduerr** [comment]
Could demonstrate the issue with a recording maybe?

**Comment by cookEbox** [comment]
The video doesn't start until 15 seconds in lots of dead time but I couldn't be bothered to edit it sorry put rough time stamps.
I open cmus in alacritty and its not displayed correctly
I open cmus in urxvt it is. (38s)

I open calcurse in alacritty (45s) move it through the stack.
I open calcurse in urxvt 00:01:26 (1min26s)

https://user-images.githubusercontent.com/67757166/108572583-8a2cef80-730a-11eb-9751-442a4dc10b18.mp4

Anything else let me know, as I said previously its weird because I don't think alacritty updated but urxvt still works fine with these programs.

Thanks

**Comment by chrisduerr** [comment]
You seem to be starting the applications right at launch, could you try starting them after Alacritty was opened?

**Comment by cookEbox** [comment]
I was using hotkeys and it was working. It does handle it a little better alacritty has opened but resizing is still an issue

**Comment by chrisduerr** [comment]
How does it perform better? And how does it still cause issues?

**Comment by cookEbox** [comment]
opens at correct size but then when moved through stack the display does not change resize  properly.

https://user-images.githubusercontent.com/67757166/108573320-2efbfc80-730c-11eb-887d-41113c3c394d.mp4

**Comment by cookEbox** [comment]
As i said not sure it is your end was as much wandering if you had any thoughts what might have caused this on my end

**Comment by chrisduerr** [comment]
Are you using `TERM=alacritty`? Maybe try `TERM=xterm-256color`. Alacritty properly reports window size changes, so this is likely an issue with calcurses, which is why vim works just fine for you.

**Comment by cookEbox** [comment]
I'm using TERM=xterm-256color. It seems to be happening with all terminal based programs, calcurse just more obviously. I can't say this is problem with alacritty and not my system so unless you have any other ideas I will close this issue

**Comment by chrisduerr** [comment]
> I can't say this is problem with alacritty and not my system so unless you have any other ideas I will close this issue

Well, with some applications obviously resizing just fine, Alacritty is certainly sending the correct resize events. How those are handled is up to the application.
