### ISSUE TITLE
Add config option to not select pasted text

### ISSUE THREAD

**Issue by emanueljg** [alacritty/alacritty#4822]
When something is pasted, it is already selected. This selection disappears after moving around the pointer, but it would be nice if there was a config option to not select it in the first place. 

https://imgur.com/a/kVYRBjL This screenshot is a bit redundant, but it shows what I mean. In this picture, `#alacritty` is pasted in and therefor selected.

On the off-chance that it might be my own config's fault, here's that: https://pastebin.com/gi2SeaTB
Running alacritty 0.7.1 (a852eb85) on Arch Linux.

**Comment by chrisduerr** [comment]
Can you reproduce this with an empty configuration file?

**Comment by emanueljg** [comment]
> Can you reproduce this with an empty configuration file?

Tried it just now. Exact same result.

**Comment by chrisduerr** [comment]
This is a bash thing.
