### ISSUE TITLE
Opacity chaging key-bind

### ISSUE THREAD

**Issue by crozbo** [alacritty/alacritty#4826]
I would like to have action for increase and decrease opacity, something like font size increase and decrease. The steps can be set as default to 0.05 or 0.1 and possibly config option for setting step value. I dont' know is there any good options for default key-bind, something with + and -, will be great

**Comment by chrisduerr** [comment]
I don't see any reason to add this. Editing the configuration file should already work live.

**Comment by ImFlush** [comment]
@chrisduerr thanks for not helping, I would like to have a change opacity function too.
I dont want to edit my config file just to change my opacity.
