### ISSUE TITLE
pressing shift-F3 in alacritty sends an unprovoked "cursor position report" with line=2, col=3

### ISSUE THREAD

**Issue by a-m-joseph** [alacritty/alacritty#4830]
If you press shift-F3 in alacritty, it will send the ANSI/VT100 escape code for CPR (cursor position report) with the arguments set to line=2, col=3.  It's due to these two lines matching -- they both output the same thing.

https://github.com/alacritty/alacritty/blob/8ed72cc065255007a7f0687e3b8a540e8c6202c6/alacritty/src/config/bindings.rs#L564

https://github.com/alacritty/alacritty/blob/8ed72cc065255007a7f0687e3b8a540e8c6202c6/alacritty_terminal/src/term/mod.rs#L1213

Fundamentally, this is due to an ambiguity created when function-key codes were grafted onto the protocol.

The wikipedia page https://en.m.wikipedia.org/wiki/ANSI_escape_code includes a vague comment "This can be avoided by using the ? private modifier", but it's not clear what that means.

The xterm authors are aware of this problem: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html

>           Note: it is possible for this sequence to be sent by a
>           function key.  For example, with the default keyboard
>           configuration the shifted F1 key may send (with shift-,
>           control-, alt-modifiers)
> 
>             CSI 1 ; 2  R , or
>             CSI 1 ; 5  R , or
>             CSI 1 ; 6  R , etc.
> 
>           The second parameter encodes the modifiers; values range from
>           2 to 16.  See the section PC-Style Function Keys for the
>           codes.  The modifyFunctionKeys and modifyKeyboard resources
>           can change the form of the string sent from the modified F1
>           key.

they offer several different ways to fix it, but all are xterm-specific:

https://invisible-island.net/xterm/manpage/xterm.html#VT100-Widget-Resources:modifyFunctionKeys

It appears that this ambiguity can be avoided by issuing the DECCKM command, but alacritty doesn't support that.  This alters the way function keys are reported, avoiding the code collision:

https://vt100.net/docs/vt510-rm/DECCKM.html

https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-PC-Style-Function-Keys

**Comment by chrisduerr** [comment]
So what is the problem exactly? This works as intended.

**Comment by a-m-joseph** [comment]
The problem is that you press a key on the keyboard and alacritty tells the application "hey the mouse moved".

**Comment by chrisduerr** [comment]
> Note that the application never even asked where the cursor was. Unrequested updates from the terminal generally cause applications to get confused or stuck. Even if they don't, the cursor position being reported is simply wrong.

If an application cannot handle this, it's an issue with the application, not with Alacritty.

> The simplest solution of all would be to just ignore keypresses on function keys when any modifiers (ctrl, shift, or alt) are depressed.

Not sending anything is not a solution. By standard Alacritty sends what it is supposed to send. What the application does with it is up to the application.

If you have any concrete suggestions for missing escape sequences to implement or changes, feel free to open another issue. But opening an issue with Alacritty for behaving the way it should is not constructive.

**Comment by nixpulvis** [comment]
I was curious to look more into this. https://invisible-island.net/xterm/xterm-function-keys.html has the best reference I could find on the subject.

Having skimmed through some of this, I'm now finding it somewhat amazing that the four terminals I spot tested all do the same thing with the function keys.

I can see how having a function key send an already used escape is a problem though, but I'd have to really study the alternatives to understand if any of them would be an improvement. Not to mention that this seems like a broader discussion than for Alacritty alone. There's a small bit of discussion about it on the [terminal-wg "Feature reporting revamp" issue](https://gitlab.freedesktop.org/terminal-wg/specifications/-/issues/8)

> time to re-think how modifier + function keys or modifier + arrow keys are denoted (especially if the modifier substantially changes the escape sequence)
