### ISSUE TITLE
Editing Shell Command Using Cursor Motion in Vi Mode

### ISSUE THREAD

**Issue by guy-who-googles** [alacritty/alacritty#4837]
Feels like I might be missing something since I didn't see any issues on this. I thought one of the main advantages of having cursor motions was editing shell commands. Say I do:
`$ echo hello World|`
with the pipe denoting cursor position. I realize I want to capitalize the "H". I assumed the following actions: 

1. ToggleViMode
2. SemanticLeft
3. SemanticLeft
4. ToggleViMode

would give me the following result:
 `$ echo |hello World`
and then it's just a matter of editing. However, after toggling out of vi mode in step 4, my cursor moves back to the original position. 

Note - Let me know if there's anything noteworthy to add. This is my first issue opened. 

### System

OS: Linux  - Ubuntu 20.04 LTS
Version: 0.7.1
Linux/BSD: X11

**Comment by chrisduerr** [comment]
Alacritty is a terminal, it has nothing to do with the shell. To edit your shell prompt your shell needs a vi mode like zsh/bash do.

**Comment by guy-who-googles** [comment]
Oh shoot, didn't know that was a thing. Thanks!
