### ISSUE TITLE
App crashes when closed in GNOME Wayland

### ISSUE THREAD

**Issue by nilueps** [alacritty/alacritty#4840]
### Steps to reproduce

1. Open a terminal window
2. Click the 'X' on the Alacritty window

### Expected behavior
Alacritty closes

### Actual behavior
Alacritty closes and Problem Reporting (`gnome-abrt`) warns that `Alacritty quit unexpectedly`

### System

OS: Linux (Fedora 33, kernel 5.10.15)
Version: `0.7.1`
Linux/BSD: GNOME Wayland

### Logs

[gnome-abrt auto-generated bug report](https://retrace.fedoraproject.org/faf/reports/64896/)
Crashes: `alacritty killed by SIGSEGV`
Font/Terminal size: default configuration
Keyboard and bindings: default configuration

**Comment by chrisduerr** [comment]
Update to 0.7.2.
