### ISSUE TITLE
Alacritty errors about missing dependency on latest Windows build

### ISSUE THREAD

**Issue by ElArtista** [alacritty/alacritty#4846]
Fresh alacritty install, shows bellow dialog

### System

OS: Windows
Version: 0.7.2

### Logs

![BPNF8](https://user-images.githubusercontent.com/4622346/109281560-254f2900-7825-11eb-9e6b-c2c147eeb211.png)

**Comment by r-c-f** [comment]
Which Windows build are you using? Since https://github.com/alacritty/alacritty/commit/8ed72cc065255007a7f0687e3b8a540e8c6202c6 there is no support for anything older than the October 2018 update to Windows 10.

**Comment by r-c-f** [comment]
Even in the case that this is just an older version of Windows than is supported, it might be useful to add something to the readme installation section about the Windows version requirements as is done with OpenGL. Previously one would only encounter issues with versions of Windows Microsoft had themselves abandoned; without WinPTY, this is no longer the case.
