### ISSUE TITLE
Padding doesn't seem to do anything?

### ISSUE THREAD

**Issue by JwanKhalaf** [alacritty/alacritty#4847]
Hello everyone

I'd like to start by thanking you for this wonderful tool, I'm loving it so far!

I wanted to add some padding to the left border, so I checked the docs, and apparently `padding:` should do it, but it isn't working for me, even after I restarted my machine.

![image](https://user-images.githubusercontent.com/42877376/109287591-b02b2600-781b-11eb-8fdd-9509ce3f1777.png)

What am I doing wrong?

### System

OS: Linux Manjaro
Version: alacritty 0.7.1 (a852eb85)
Linux/BSD: LeftWM

**Comment by kchibisov** [comment]
It should be
```yml
window:
  padding:
    x: 100
    y: 100
```
