### ISSUE TITLE
Drop a app into alacritty, the space doesn't escape.

### ISSUE THREAD

**Issue by singlexyz** [alacritty/alacritty#4848]
OS: macOS
Version: 0.7.2 (5ac8060)

Drop a app to alacritty command, when then app's name include space, it doesn't escape.

<img width="648" alt="截屏2021-02-26 下午9 27 30" src="https://user-images.githubusercontent.com/4456413/109305960-76890800-7879-11eb-8aa2-d6e17bc73276.png">

It should be escape the space:
`open /Applications/GitHub\ Desktop.app`

**Comment by chrisduerr** [comment]
This is intentional. Alacritty makes no assumptions over what an application inside of Alacritty might accept as a valid path.

You can alwas use quotes before dropping the application into Alacritty.
