### ISSUE TITLE
Cursor control with mouse doesn't work in vim

### ISSUE THREAD

**Issue by lefthairynut** [alacritty/alacritty#4852]
I set `set mouse=a` in my `vimrc` but cursor doesn't move with right click. I searched through alacritty config but found nothing  related to this(including in the mouse section).

**Comment by chrisduerr** [comment]
Use `:set ttymouse=sgr`.

**Comment by lefthairynut** [comment]
after I did this, the primary clipboard doesn't work anymore(when I select text it doesn't get copied to primary clipboard i.e doesn't get pasted via mouse middle click)

**Comment by chrisduerr** [comment]
Yeah, because vim is now capturing your mouse input. You can hold shift to temporarily force override it to give control back to Alacritty.

Alternatively you could also teach vim to write to your clipboard on selection.
