### ISSUE TITLE
A problem with controlling PulseAudio from alacritty.

### ISSUE THREAD

**Issue by mcizek-2** [alacritty/alacritty#4854]
I have an oddly specific issue with alacritty when using commands involving pulseaudio. Given that it hasn't happened in any other of my terminal emulators, I am going to assume it might have to do something with alacritty.

When I try to connect to the PulseAudio server trough the command pactl, I get a "Connection failure: connection refused" error.

When I try to restart PulseAudio from alacritty I get an error D-Bus name org.PulseAudio1 already taken

Here are my specs:
### System

OS: Ubuntu 20.04
Version: 0.5.0-dev
X11 in Qtile

**Comment by chrisduerr** [comment]
That has nothing to do with the terminal.
