### ISSUE TITLE
rendering fails when being screen recorded by certain applications

### ISSUE THREAD

**Issue by Nobody4931** [alacritty/alacritty#4855]
i was trying to stream the window to some friends over discord, however the moment the stream started, the rendering of the text completely failed and became transparent boxes permanently until i restarted alacritty. i tested this again later with a different program (obs and windows 10 gamebar) but nothing happened. not too sure whats causing this

screenshot of aftereffects:
![not too sure what happened here](https://user-images.githubusercontent.com/54015946/109424592-2f526280-79b2-11eb-92e7-8f09221140e1.png)

### System

OS: Windows
Version: alacritty 0.7.1 (a852eb8)

**Comment by chrisduerr** [comment]
Can you reliably reproduce this or was this a one time thing? Also are you able to record other OpenGL applications with Discord?

**Comment by Nobody4931** [comment]
> Can you reliably reproduce this or was this a one time thing? Also are you able to record other OpenGL applications with Discord?

it happens every time when i am screen recording it with discord (the rendering fails the moment i press any key), and i have never seen this issue when recording other applications with discord before, openGL or not

**Comment by chrisduerr** [comment]
Which OpenGL applications have you tested?

**Comment by Nobody4931** [comment]
> Which OpenGL applications have you tested?

not too sure if these applications are completely openGL, but a few games, nothing like terminal emulators or the such

**Comment by chrisduerr** [comment]
Could you maybe try an actual pure OpenGL application? Otherwise that's not of much help.

**Comment by Nobody4931** [comment]
> Could you maybe try an actual pure OpenGL application? Otherwise that's not of much help.

could i get an example of which applications to try out? i'm not sure i have any pure openGL applications

**Comment by chrisduerr** [comment]
I don't know, I don't use Windows. On Linux I'd recommend `glxgears`. Worst case can write something yourself as a quick demo.

**Comment by N4tus** [comment]
I tried a pre opengl example (the hello_world example from imgui-rs, https://github.com/imgui-rs/imgui-rs/tree/master/imgui-examples) and it has the same issues when recorded by discord.

**Comment by N4tus** [comment]
you need to turn 'Use our latest technology to capture your screen' off (found under Voice & Video in the settings). With that it works.

**Comment by chrisduerr** [comment]
Sounds like a Discord bug to me.

**Comment by Jaso55555** [comment]
I ran into this issue and decided to investigate. It seems to me that discord is unbinding the texture, so what I did was remove the check for binding the texture each frame, and just bind it regardless of what's going on and this seems to fix it. I also noticed a GL_INVALID_ENUM error happening upon screen sharing, but I'm unsure how to figure out where that's occuring.

Here's what I changed:
```
diff --git a/alacritty/src/renderer/text/glsl3.rs b/alacritty/src/renderer/text/glsl3.rs
index 7c32bf9f..a38ddd25 100644
--- a/alacritty/src/renderer/text/glsl3.rs
+++ b/alacritty/src/renderer/text/glsl3.rs
@@ -230,13 +230,11 @@ impl<'a> TextRenderApi<Batch> for RenderApi<'a> {
             );
         }

-        // Bind texture if necessary.
-        if *self.active_tex != self.batch.tex() {
-            unsafe {
-                gl::BindTexture(gl::TEXTURE_2D, self.batch.tex());
-            }
-            *self.active_tex = self.batch.tex();
+        // Bind texture
+        unsafe {
+            gl::BindTexture(gl::TEXTURE_2D, self.batch.tex());
         }
+        *self.active_tex = self.batch.tex();

         unsafe {
             self.program.set_rendering_pass(RenderingPass::Background);
```

**Comment by kchibisov** [comment]
But alacritty runs in a different process compared to discord, how does this even matter? Is it on nvidia? It sounds like a disaster if the driver shares state like that meaning that you basically can't rely on any other of the GL state in your program.

**Comment by kchibisov** [comment]
You were on Windows as well, right? I got educated what could cause it, and it's basically that discord could inject their code via providing a DLL library which doesn't restore textures being bound, so it seems like it's expected that such thing broke, but obviously you can't really do things like that and at least not restore the state...

**Comment by Jaso55555** [comment]
I am on windows here with nvidia drivers (laptop 3060). Honestly no idea how or why discord is doing this, just that renderdoc doesn't seem to think there's a texture being input to the draw calls, so I made sure to bind them each time.

**Comment by kchibisov** [comment]
They inject dll to do screen recording/present overlay. We can't really protect against that unless we just do redundant calls like rebinding the texture.

You can probably check what DLLs are loaded, but I don't remember the API for that. It's not like discord will change anything to be fair.

**Comment by Jaso55555** [comment]
Did some digging, found the dll which discord injects, and I think it uses [GDI](https://learn.microsoft.com/en-us/windows/win32/gdi/windows-gdi)? The path to the dll for me is found under `%LOCALAPPDATA%\Discord\app-1.0.9018\modules\discord_hook-1\discord_hook\0eb52a70cd3fe5\DiscordHook64.dll`

**Comment by kchibisov** [comment]
Yeah, that's the reason it fails, since they need to draw their textures on top of alacritty(overlay) or get alacritty's texture for the screenshare. I'm not sure how slow the binding is actually, we could probably just always bind the texture, but it's just so windows problem (or always bind it on windows).

**Comment by Jaso55555** [comment]
I did a quick benchmark, which got some weird results. So running on a dev build both with the fix and without averaged around 90-110 us/frame, and release mode without the fix got the same results, but with the fix it actually pushed the average frame time to 85-90? While I'm not doing these tests very well (just setting renderdoc to capture the first 7 frames and looking at total frame time), this looks very odd. I would hazard a guess that the opengl drivers are applying some optimisation here but I'm honestly clueless.

**Comment by kchibisov** [comment]
I'd test myself on linux as well tbf, it could be that it's faster to bind the texture since it should be just assign in state machine, but I have no idea.

**Comment by Jaso55555** [comment]
Considering we'd only be binding one texture per frame, it's really not a lot even on low end devices although this should be tested. Is there a proper way to benchmark the frame rate? Vtwbench's readme implies it doesn't do this sort of thing.

**Comment by kchibisov** [comment]
Hm, no, not for the frame rate, since it's a bit different. We have `render_timer` though, which should cover this. But once a frame binding is absolutely fine...

It's just weird that we have to deal with the discord library injection, don't you think?

**Comment by Jaso55555** [comment]
My suspision is actually that something inside that has broken. When you screenshare, the opengl error callbacky thing catches a GL_INVALID_ENUM, so I'm wondering if discord is trying to rebind the texture, but has mis-detected it as something else other than a GL_TEXTURE_2D and is causing that error.

**Comment by kchibisov** [comment]
If you run with `-vv` logging it doesn't say more about the error? Usually it should show the error exactly?

**Comment by Jaso55555** [comment]
Here's a log from where it errors [Alacritty-15168.log](https://github.com/alacritty/alacritty/files/12703222/Alacritty-15168.log)
Is it supposed to have a stack trace?

**Comment by kchibisov** [comment]
No, it shouldn't. The debug function is being called by the video driver and what ends up in the log depending on the driver as well...

**Comment by keeb** [comment]
Is the patch the accepted solution to this problem, or is that work going on elsewhere?
