### ISSUE TITLE
Alacritty on ChromeOS shows a black frame when maximized

### ISSUE THREAD

**Issue by kalexm** [alacritty/alacritty#4856]
### System

OS: ChromeOs
Version: alacritty 0.7.2 (dc4cc7b)
Linux/BSD: X11/Wayland, sommelier

First activated Linux Beta on my Pixelbook (i5). As there is no working ppa archive for Android/ChromeOS, i installed Rust and compiled alacritty with Cargo install alacritty.
Setting the a font worked fine. Starting alacritty works from the shell
`# alacritty`
. Then it connects to the wayland/X11 of android. Works also with 
`# sommelier alacritty` 

(why Alacritty if there is a shell? because I want to use Nerd-Fonts in nvim and there is no chance in installing those in ChromeOS directly, so I installed them in the Linux container. When starting alacritty it uses the nerdfont and shows all the nerdfont icons)

it starts as a non maximized window and shows window decorations. The alacritty options for startup mode and window decoration aren't working on ChromeOS. When maximized into fullscreen, there is a "frame" that overlays the fullscreen. The size of that frame is exactly the size the window was before maximizing. When the window was already maximized the "frame" is only shown on the bottom.
![Screenshot 2021-02-28 at 18 15 27](https://user-images.githubusercontent.com/30960891/109427121-292fa680-79f1-11eb-85f2-b63731a642f9.png)
![Screenshot 2021-02-28 at 18 16 03](https://user-images.githubusercontent.com/30960891/109427125-2af96a00-79f1-11eb-9244-5fa3b6467a3e.png)

**Comment by chrisduerr** [comment]
Sounds like a graphics driver issue with ChromeOS. Do other OpenGL applications work without any issues?

**Comment by kalexm** [comment]
WebGL in Chrome runs smooth 3D is working. Which Linux App would prove that OpenGL works?

**Comment by chrisduerr** [comment]
glxgears

**Comment by kalexm** [comment]
it segfaults immediately
hmmh

**Comment by chrisduerr** [comment]
I'm not much surprised that ChromeOS creates a bunch of problems for you here. That's just kinda what you get for using it.

If you figure out how to properly get all other OpenGL applications working and Alacritty still doesn't wanna go, let me know.

**Comment by kalexm** [comment]
ah well now it ran with 52fps
![Uploading Screenshot 2021-02-28 at 19.58.11.png…]()

**Comment by kalexm** [comment]
AAahhh thank you! You helped without knowing....

sommelier -X alacritty works

itś redirecting it to X11. Wayland on ChromeOS is obviously unstable

**Comment by InternetOfTofu** [comment]
This happened because previously some guest graphics memory isn't being properly flashed to the host side when going through wayland. This should have been fixed a few months ago.
