### ISSUE TITLE
Changing config in any way results in an error

### ISSUE THREAD

**Issue by dylanhamley** [alacritty/alacritty#4858]
### System
OS: Arch Linux
Version: alacritty 0.7.2 (5ac8060b)
DE: KDE Plasma X11

### Logs
Font/Terminal size: Jetbrains Mono Regular 13pt / 95x24
Keyboard and bindings: all default

I have been having this weird issue where if I change anything in the config file it will throw an error, or just not work. I want to change my font to Jetbrains Mono Regular 13pt, with a 95x24 terminal, like I was using in Konsole, but whenever I change the fonts area in `~/.config/alacritty/alacritty.yml`, it will throw the error `[2021-02-28 14:06:45.663210729] [ERROR] [alacritty_config_derive] Unable to load config "/home/dylan/.config/alacritty/alacritty.yml": Config error: did not find expected <document start> at line 105 column 5`, which is the location of the colon in the font area. Am I doing something wrong? The base config I am using is from `/usr/share/doc/alacritty/example/alacritty.yml`. My edited config is attached as a .txt file as I can't upload a .yml.
[alacritty.txt](https://github.com/alacritty/alacritty/files/6058137/alacritty.txt)

**Comment by chrisduerr** [comment]
That's because your config is invalid. If you are not familiar with yaml, please read up on it.

If you want to use a child entry, the parent must be added too. I recommend starting with an empty config.
