### ISSUE TITLE
Different left and right mod keys

### ISSUE THREAD

**Issue by s1913388** [alacritty/alacritty#4860]
I want to ask how to set keybindings like following
  - { key: Key3, mods: LAlt, chars: "#" }
  - { key: Key3, mods: RAlt, chars: "£" }
where LALt is left alt and RAlt is right alt on keyboard.

**Comment by chrisduerr** [comment]
You can't and there's currently no plan to add this.

You can trigger something on LAlt or RAlt, but as modifiers they both are the same.

**Comment by s1913388** [comment]
On macos iterm2, it can set left option key and right option keys seperately as Normal, Meta or Esc+.
Therefore when typing on UK keyboard, we can easier use LAlt-3 as M-3 on emacs whilt RAlt-3 to type '#' char.
Is there any work around or add a new feature to alacritty?

**Comment by nela** [comment]
I am also having this 'issue' and am wondering if there are any workarounds? @chrisduerr  Can some sort of triggers be configured in order to have this functionality? If so, could you elaborate?

**Comment by 097115** [comment]
@nela , @s1913388 

You haven't found any workaround, guys?

@chrisduerr 

Still no plans to split `Alt` into `LAlt` and `RAlt`?

**Comment by chrisduerr** [comment]
Rebinding modifiers might be possible in the future, but binding to left/right modifiers specifically isn't planned at the moment.
