### ISSUE TITLE
Allow key binding to propagate

### ISSUE THREAD

**Issue by ChoppinBlockParty** [alacritty/alacritty#4863]
I have `C--` in tmux (without tmux mode) for splitting pane. However it is binding to `DecreaseFontSize`, I tried `None` and `ReceiveChar`, both did not give the desired effect. What is the way of allowing the key to propagate to the terminal application, tmux in this case?

**Comment by chrisduerr** [comment]
What exactly did you try? You probably did it wrong.

**Comment by ChoppinBlockParty** [comment]
I tried

```yaml
  - { key: Minus,          mods: Control,                         action: None }
```
and 

```yaml
  - { key: Minus,          mods: Control,                         action: ReceiveChar }
```

**Comment by chrisduerr** [comment]
Does this work in other terminals?

**Comment by ChoppinBlockParty** [comment]
I have 

```
unbind '\'
bind -n 'C-\' split-window -h -c '#{pane_current_path}'  # Split panes horizontal
unbind -
bind -n 'C-_' split-window -v -c '#{pane_current_path}'  # Split panes vertically
```
in my tmux config for a while. Works well in urxvt.

**Comment by chrisduerr** [comment]
Yeah, that's the binding for Ctrl + _, not -. Chances are if you press ctrl + shift + '-' it will work in Alacritty too.

URxvt just decides to send the same thing for `-` as it does for `_`, but that's by no means what should be expected here.

**Comment by ChoppinBlockParty** [comment]
It still does not work, even if I change '_' to '-'.(((

**Comment by chrisduerr** [comment]
You need to press shift. You cannot just press control and minus. You need to send control and underscore. Control and minus sends just minus (correctly so).

**Comment by ChoppinBlockParty** [comment]
> You need to press shift. You cannot just press control and minus. You need to send control and underscore. Control and minus sends just minus (correctly so).

Why do I need to press shift?

**Comment by chrisduerr** [comment]
You can't, unless you create a binding for control + minus that has the correct chars. So technically you can, you just need to create your own binding.

**Comment by ChoppinBlockParty** [comment]
Like this ?

```
bind -n 'C--' split-window -v -c '#{pane_current_path}'  # Split panes vertically
```

I did, did not work.

**Comment by chrisduerr** [comment]
No, inside of Alacritty. Instead of mapping it to pass through the character it receives by default, you map it to pass through the character you want.

**Comment by ChoppinBlockParty** [comment]
Oh, really. How can I do that?

**Comment by chrisduerr** [comment]
I recommend reading the documentation on the `key_bindings` section in our configuration file. If that does not work for you, please let me know and I can try to improve the documentation accordingly.

**Comment by ChoppinBlockParty** [comment]
Solved by

```
  - { key: Minus,          mods: Control,                         chars: "\x1f" }
```

what basically mean sedn `C-_` on `C--` pressed.

@chrisduerr Awesome. Thank you.
