### ISSUE TITLE
No opacity when lanched with GPU 

### ISSUE THREAD

**Issue by Magnus512** [alacritty/alacritty#4865]
### System

OS: Linux (Linux Mint - Cinnamon)
Version: 0.7.2
Linux/BSD: X11 Cinammon

Ok, so I'm launching Alacritty in Linux Mint 20.1, I have the Hybrid graphics configuration, to use my intel integrated graphics, and when I want to use the Nvidia GPU I use launch on GPU menu option....
Alacritty opacity works well when I use the normal launch, but when I launch the app with the GPU I don't have any opacity.
It looks like this...
Any idea about how to fix this?
![imagen](https://user-images.githubusercontent.com/7065012/109545818-93465b00-7a86-11eb-9a2d-c824e0516bf8.png)
When I use the default terminal I do have opacity working.
![imagen](https://user-images.githubusercontent.com/7065012/109546197-1a93ce80-7a87-11eb-8bcb-49adb3319c29.png)

**Comment by chrisduerr** [comment]
Do you run a compositor?

**Comment by Magnus512** [comment]
> Do you run a compositor?
The one integrated in Linux Mint, I have the same issue in Archlinux running with picom.

**Comment by chrisduerr** [comment]
Have you tried checking your GPU driver configuration? Chances are you've got some setting enabled there disabling transparency/compositing for windows.

If this works with one of your GPUs, it's probably not an Alacritty issue.

**Comment by Magnus512** [comment]
> Have you tried checking your GPU driver configuration? Chances are you've got some setting enabled there disabling transparency/compositing for windows.
> 
> If this works with one of your GPUs, it's probably not an Alacritty issue.

As I mention before, launching gnome terminal with Nvidia GPU gives me opacity 

![imagen](https://user-images.githubusercontent.com/7065012/109547841-1e285500-7a89-11eb-9eb6-5bbf7006554a.png)

![imagen](https://user-images.githubusercontent.com/7065012/109547751-018c1d00-7a89-11eb-9cfe-d2b50b833999.png)

**Comment by chrisduerr** [comment]
gnome-terminal doesn't render with OpenGL. So that means nothing.
