### ISSUE TITLE
Alacritty enters vi mode on escape key press

### ISSUE THREAD

**Issue by mankinskin** [alacritty/alacritty#4867]
When pressing the escape key, alacritty seems to enter a vi mode. I noticed this when pressing Esc would cause the next key press to be ignored. We first suspected this was due to bash editing-mode or `set -o vi`, but none of those are specified, and `set -o emacs` doesn't fix it. 

This also causes the cursor to change when there is text in the line, and allows for vi move commands after pressing esc (`b`, `w`, `h`, `l`).

How do I turn this off? The documentation mentions a Vi-mode, which can be toggled by `Ctrl+Shift+Spacebar` but that seems to be something else, as it disables any input I tried and shows some UI in the top right corner.

### System

OS: Manjaro Linux
Version: alacritty 0.7.2 (5ac8060b)
DM/WM: X11/i3/XFCE

**Comment by nixpulvis** [comment]
> The documentation mentions a Vi-mode, which can be toggled by `Ctrl+Shift+Spacebar` but that seems to be something else, as it disables any input I tried and shows some UI in the top right corner.

This is Alacritty's only vi-mode.

Have you tried in another shell like `sh` and been able to replicate this issue?

**Comment by mankinskin** [comment]
Oh, no. Using `fish` doesn't show this behavior. Seems to be an issue with bash after all?
