### ISSUE TITLE
Add option to respect font hints

### ISSUE THREAD

**Issue by OliverUv** [alacritty/alacritty#487]
In urxvt, I can set my fonts as follows:
```
URxvt*font: xft:Inconsolata:style=Medium:bold:pixelsize=18:antialias=true:hinting=true:hintstyle=hintfull
URxvt*boldFont: xft:robotomono:style=Medium:italic:pixelsize=18:antialias=true:hinting=true:hintstyle=hintfull
```

The hinting ensures that the font renders beautifully. I can achieve similar (or maybe the same?) results by setting the x and y offsets in alacritty, but if I ever change font size, I have to re-adjust these offsets.

I understand that this might be an enormous amount of work to ask for, but I think future users of the font library would appreciate it a lot.

**Comment by OliverUv** [comment]
Oh, how would I go about doing that?

**Comment by jwilm** [comment]
We don't actually look at fontconfig hints *yet*, but that will be the supported way to do this in the future.

**Comment by kchibisov** [comment]
We do respect Fontconfig's hinting settings.
