### ISSUE TITLE
Observed CSI query responses out of order

### ISSUE THREAD

**Issue by hzeller** [alacritty/alacritty#4872]
I like to query the background color via a `\033]11;` query. To make it possible to detect if a terminal does not support it, I also append a second just general DA1 query, so that I can see in the response immediately if I only get a response for that, so I conclude that the terminal can't answer the first and don't have to wait until I reach some timeout.

However, alacritty is answering these requests out of order: Below you see first the background color request followed by the `\033[c` DA1 query.
The response to the DA1 query arrives first and a few moments later the response to the background color arrives.

#### Actual result: responses out of sequence
```
echo -e "\e]11;?\e\\\\\e[c"
^[[?6c^[]11;rgb:1d1d/1f1f/2121^[\
```

#### Expected result: responses in sequence of query
I'd expect that the result would be in sequence of the queries:
```
^[]11;rgb:1d1d/1f1f/2121^[\^[[?6c
```

With this out-of-sequence response, my plan to use it as a detection if a specialized query is supported of course won't work as intended.

Is out-of-order response generally something that I have to expect from a terminal emulator or is this particular issue a bug in alacritty ?

### System

OS: Linux
Version: `alacritty 0.8.0-dev (a954e07)`  _compiled from head_
Linux/BSD: X11

(Context: I intend to use the double-query in http://timg.sh/ to be able to quickly detect terminals that don't have the background color query feature)

**Comment by chrisduerr** [comment]
> Is out-of-order response generally something that I have to expect from a terminal emulator or is this particular issue a bug in alacritty?

I'm not sure if there's any hard guarantee on the order of responses, but this particular instance is due to the fact that Alacritty has to delegate the color response to the UI, while being able to write the terminal identification directly to the PTY.

I'd say generally Alacritty should behave properly here, but I wouldn't make any guarantee for other terminals. Your "solution" is obviously not a proper way to query for capabilities.

**Comment by hzeller** [comment]
Is there a recommended way how to be able to determine if a query is supported by a terminal without having to time-out on a request ?

**Comment by chrisduerr** [comment]
Querying for terminal capabilities. Though chances are you'll still have to timeout for some stuff that doesn't have a capability.
