### ISSUE TITLE
Alacritty prints out aplication content after closing it

### ISSUE THREAD

**Issue by DonDon-9097** [alacritty/alacritty#4873]
After closing an application like htop or vim it's content is printed into the terminal 
Also vim can be scrolled in a loop connecting beginning and the end which makes orienting in a document harder

### System

OS: Linux
Version: 0.8.0-dev
Linux: X11
![image](https://user-images.githubusercontent.com/29581769/109999143-319a2100-7d12-11eb-80fd-08af2bfb3191.png)

**Comment by chrisduerr** [comment]
Which TERM?

**Comment by DonDon-9097** [comment]
I'm using alacritty with fish as my shell. 
I can't replicate this in other terminals with fish

**Comment by chrisduerr** [comment]
I'd like to know about your `$TERM`, not your shell.

**Comment by DonDon-9097** [comment]
I just tried, the same thing happens when I open something with bash, it the terminal's issue

**Comment by DonDon-9097** [comment]
I'd be happy to tell you but I don't know how to look this up

**Comment by nixpulvis** [comment]
`echo $TERM`

**Comment by DonDon-9097** [comment]
konsole

**Comment by chrisduerr** [comment]
Yeah, don't do that. You should use `alacritty`.

**Comment by DonDon-9097** [comment]
for other illterates, go with 
> set -gx TERM alacritty

and if it doesn't work and you are lazy like me you can add this line to .config/fish/config.fish
