### ISSUE TITLE
Config auto-update when updating alacritty

### ISSUE THREAD

**Issue by meandmymind** [alacritty/alacritty#4874]
I'm sorry if it was answered already

Is `alacritty.yml` somehow updated in-place with some kind of migrations when installing new version of alacritty? Or should I merge my old config and a new version myself?

### System

OS: Windows
Version: 0.7.1

**Comment by chrisduerr** [comment]
It is not and we have no desire to do so. I recommend using a minimal Alacritty config, which will usually introduce very few required changes.
