### ISSUE TITLE
Control+Shift+F keybinding does not work on MacOS

### ISSUE THREAD

**Issue by zhou13** [alacritty/alacritty#4875]
After I add the following key binding to my configuration on macOS, it does not work.

````
- { key: F,              mods: Control|Shift, mode: ~Search,    action: SearchForward    }
````

Other keybindings, such as `Ctrl-Shift-b`, works fine for me. I have checked with my opened app and system keyboard shortcuts. I cannot find any conflicts.

### System

OS: macOS
Version: `alacritty 0.7.2 (5ac8060)`

### Logs

https://pastebin.com/z25xYzuQ

**Comment by chrisduerr** [comment]
Have you verified there is no other application hooking these keybindings? Alacritty does not seem to be receiving any events when you'r pressing F with control and shift held.

**Comment by zhou13** [comment]
I test this shortcut in another application and it still does not work. So this is not the fault of alacrrity.
