### ISSUE TITLE
Running alacritty from .bat file with arguments

### ISSUE THREAD

**Issue by kopkaa** [alacritty/alacritty#4877]
I want to start alacritty within .bat script. Without arguments, alacritty starts normally. But when I try to add some arguments. It gives me error.

In .bat file I have:
```start alacritty.exe -e "ls"```

### System

OS: Windows
Version: `alacritty 0.5.0 (a6681e3)`

### Logs

```panicked at 'Unable to spawn shell: Systém nemůže nalézt uvedený soubor. (os error 2)', alacritty_terminal\src\tty\windows\conpty.rs:224:5  panicked at 'either event handler is re-entrant (likely), or no event handler is registered (very unlikely)', C:\Users\travis\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:235:37                                                                                                                                      thread panicked while processing panic. aborting.        ```

**Comment by chrisduerr** [comment]
Sounds like `ls` is not an executable that can be found on your system. You might have to spawn a shell first.
