### ISSUE TITLE
Resize does not keep viewport in place

### ISSUE THREAD

**Issue by chrisduerr** [alacritty/alacritty#4879]
It seems like there was a regression with resizing the viewport, where content would be incorrectly moved around when a long line was resized while inside of the scrollback history.

https://user-images.githubusercontent.com/8886672/110221220-d78c8d80-7ec2-11eb-9a8e-58885a582591.mp4

I have not yet bisected this, but I'm fairly sure this worked correctly previously without moving the viewport around.

**Comment by st3iny** [comment]
Are you sure this worked earlier? Tried to bisect the issue earlier and couldn't find a working version all the way down to v0.5.0. Nevertheless, I came up with a solution and sent a PR.
