### ISSUE TITLE
Windows10 Alacritty startup missing A and info

### ISSUE THREAD

**Issue by j4t1nd3r** [alacritty/alacritty#4883]
On Linux / Mac when loading Alacritty, it prints an A on startup and gives information on the system. This doesn't happen on Windows. Is this a missing feature or is the fact this info is missing that the install is not correct?

I installed alacritty via chocolately "choco install alacritty"

When loading alacritty on windows instead I get: 
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Windows\System32>

### System

OS: Windows10 v20H2 (OS build 19042.804)
Version: alacritty 0.7.2 (5ac8060)

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by chrisduerr** [comment]
This has nothing to do with Alacritty, but instead is about the shell you're using.
