### ISSUE TITLE
Use Alacritty with Ubuntu WSL

### ISSUE THREAD

**Issue by Matteoverzotti** [alacritty/alacritty#4884]
I have just installed Alacritty on Windows. However, I want to use the Ubuntu WSL Shell when opening. I have played with the .yml file of the config, but can't find what I'm supposed to write at `shell`.
I've tried `shell:
  program: \\wsl$\Ubuntu-20.04\usr\bin\bash` but with no success.

**Comment by SuperSandro2000** [comment]
Try 

```
shell:
shell:
  program: wsl.exe
```

**Comment by Matteoverzotti** [comment]
Thanks... don't know how I didn't think of that.

**Comment by echosonusharma** [comment]
trying this didn't work ...screen would close immediately 

`shell:
  program: wsl.exe`

but this works ...maybe its because of wsl2 or something... no indea

`shell:
  program: wsl.exe -d Ubuntu-20.04`

**Comment by cherryramatisdev** [comment]
> trying this didn't work ...screen would close immediately
> 
> ```
> shell:
>   program: wsl.exe
> ```
> 
> but this works ...maybe its because of wsl2 or something... no idea
> 
> ```
> shell:
>   program: wsl.exe -d Ubuntu-20.04
> ```

You're amazing! it works perfectly
