### ISSUE TITLE
Minimise Alacritty

### ISSUE THREAD

**Issue by Matteoverzotti** [alacritty/alacritty#4889]
OS: Windows 10
Version: alacritty 0.8.0-dev (d5dd009)

I use alacritty with no decorations, but that takes away my ability to move/minimize the application. I've tried ways like Windows + Down arrow, Alt + Space + M, but nothing works for me. Can I do something about it? I really want to work on my desktop at the same time.

**Comment by chrisduerr** [comment]
Can't you right-click the icon in the taskbar on windows to minimize applications? I'm not familiar with how Windows operates anymore.

**Comment by Matteoverzotti** [comment]
Unfortunately no, I've also tried right-clicking on the icon and the "Minimize" option is unavailable
![image](https://user-images.githubusercontent.com/58049266/110775543-b253a280-8267-11eb-8edb-fe51a3a5ea67.png)

**Comment by chrisduerr** [comment]
Huh, that's kinda funny. Anyways, the custom action you can define for Alacritty keybindings probably works? You just need to bind that to whatever you want.

**Comment by Matteoverzotti** [comment]
Binding the Minimize option to a key worked for me. Thanks!
