### ISSUE TITLE
Window shadows is missing in MacOS version

### ISSUE THREAD

**Issue by lucastrvsn** [alacritty/alacritty#4897]
### System

OS: macOS Big Sur 11.2.3 Apple Sillicon
Version: `alacritty 0.8.0-dev (3159b60)` using arm_ci branch

For comparison, this is `Terminal.app` and `alacritty`:

![Captura de Tela 2021-03-15 às 10 20 49](https://user-images.githubusercontent.com/8826449/111159855-4a0f0480-8578-11eb-8e04-ae27d0c139ba.png)

![Captura de Tela 2021-03-15 às 10 20 27](https://user-images.githubusercontent.com/8826449/111159838-45e2e700-8578-11eb-9e7c-0293512d51c6.png)

**Comment by chrisduerr** [comment]
Do you use transparency?

**Comment by lucastrvsn** [comment]
@chrisduerr Yes. Removing the `background_opacity` option from my `alacritty.yml` the shadows appears. Maybe we need some warning on the `alacritty.yml` template config file to it?

**Comment by chrisduerr** [comment]
I personally don't really think a shadow is significant enough to justify that, but if you want to send a PR yourself feel free.
