### ISSUE TITLE
Tmux promise is not without pitfalls, cursor in vim window blinks when log is printing in another Tmux window

### ISSUE THREAD

**Issue by reportaman** [alacritty/alacritty#4904]
Cursor in Vim window blinks spuriously when a log in printing in another Tmux window. Is there a way Alacritty could not let that happen? (given Alacritty project recommends offloads multiplexing on Tmux). Spurious cursor blinks don't lead to distraction-free UI. 

> As a sidenote: Kitty handles multiplexing internally (and this problem does not occur), though it doesn't work with Vim themes that set a background.

### GIF

![Screen Recording 2021-03-18 at 11 47 39 PM](https://user-images.githubusercontent.com/71736629/111742985-3b5d7180-8846-11eb-9930-668c46f6ab46.gif)

### System

OS: macOS
Version: alacritty 0.8.0-dev (a5e2ccd)
maOS DE: Aqua, WM: Quartz Compositor

**Comment by chrisduerr** [comment]
Nice observation. See also #4768.

**Comment by reportaman** [comment]
@chrisduerr Don't know what it means that you closed this? Is this fixed? I don't understand the technicality in the issue you pointed me to. If not fixed, is this something on the roadmap?

**Comment by nixpulvis** [comment]
@reportaman try updating ti the latest revision which has the linked pull request merged into it.

**Comment by reportaman** [comment]
@nixpulvis I still see the same behavior.

**Comment by nixpulvis** [comment]
@reportaman sounds like you might need to wait for (or look into) the `tmux` changes to make use of the feature.

Basically it's an optimization that allows a program like `tmux` to tell the terminal emulator to wait to draw until a batch of changes are all sent, thus coalescing all the changes into a single redraw.

**Comment by reportaman** [comment]
@nixpulvis @chrisduerr Update: This problem seems to have gone in latest Alacritty + tmux 3.2, cheers!

**Comment by tombh** [comment]
I'm seeing a potentially related issue with a realtime dashboard in `tmux`, that doesn't happen in Kitty. I can't tell exactly what the `tmux` changes are that could help with this, from what I can tell DCS is already part of `tmux`, or maybe it's not feature complete or something?

**Comment by j4james** [comment]
I believe tmux synchronization works off a `Sync` terminfo entry, so you'll need to set that to get synchronization to work. If you're using the old DCS sequences, you'd need to set it like this:

    Sync=\EP=%p1%ds\E\\

If you're using the newer mode 2026 that the terminal-wg agreed on, you'd set it like this:

    Sync-\E[?2026%?%p1%{1}%-%tl%eh

I don't really understand how these things work, but I'm just quoting what the author of tmux recommended.

**Comment by reportaman** [comment]
@j4james Can you put a complete example? When I add ``Sync=\EP=%p1%ds\E\\,`` to my terminfo file and run ``>tic``, I get the following error:

```
"alacritty.ti", line 58, col 24, terminal 'alacritty': unknown capability 'Sync'
```

And for ``Sync-\E[?2026%?%p1%{1}%-%tl%eh``, I get

```
"alacritty.ti", line 58, col 9, terminal 'alacritty': Illegal character - '-'
"alacritty.ti", line 58, col 9, terminal 'alacritty': unknown capability 'Sync'
"alacritty.ti", line 58, col 12, terminal 'alacritty': Illegal character - '['
"alacritty.ti", line 58, col 12, terminal 'alacritty': unknown capability 'E'
"alacritty.ti", line 58, col 13, terminal 'alacritty': Illegal character (expected alphanumeric or @%&*!#) - '?'
```

**Comment by tombh** [comment]
Thanks @j4james, I'll play around with that as well

@reportaman I'm really lost with all this too. But what I have found that's really interesting is this test for DCS sync capability:

`printf 'hello, \033P=1s\033\\world!'; sleep 0.5s; printf '\033P=2s\033\\'`

In raw Alacritty you see `hello, ` printed and then with a slight delay, `world!`. But in tmux (inside the same Alacritty), at least in my setup, I just see `hello, world!` all printed at the same time. Though I should note I see the exact same behaviour in Kitty, so I haven't actually found what Alacritty is doing differently. This makes me feel the problem is more likely in tmux than Alacritty. I've tried playing with the `terminal-features` setting in tmux (search for "sync" in `man tmux`), but that didn't make any difference.

I did however fix my immediate problem though by monkey patching the python code (that's generating my flickering dashboard), by wrapping its output to STDOUT with DCS codes *and* tmux passthrough sequences, you can read about that in detail here if you're interesed: https://github.com/willmcgugan/rich/discussions/1314#discussioncomment-947624

**Comment by reportaman** [comment]
@tombh Vim too has stutters/flickers in GPU accelerated terminals. I have an opened a [ticket on Vim](https://github.com/vim/vim/issues/8002), as it happens in Vim and not Neovim. The developer of Neovim has to say [this](https://github.com/neovim/neovim/issues/14225#issuecomment-809623524).

**Comment by reportaman** [comment]
@tombh https://github.com/wez/wezterm is the only terminal on my machine that displays "hello, " and "world" at the same time. Should that be a bug on WezTerm? or is it expected behavior?

**Comment by j4james** [comment]
> I get the following error:
> 
> ```
> "alacritty.ti", line 58, col 24, terminal 'alacritty': unknown capability 'Sync'
> ```

@reportaman Try using the `-x` command line option for tic. Apparently that enables support for user-defined capabilities. I'm kind of guessing here, because I haven't done this myself, but I do know it should be possible.

**Comment by reportaman** [comment]
@j4james Wonderful, the original issue that I had reported in this bug seems to have disappeared! I no longer see cursor blinking in vim window when log is printing in another Tmux window after adding ``Sync=\EP=%p1%ds\E\\,`` to ``alacritty.ti`` generated from ``>infocmp alacritty``, and then regenerating it with ``>tic -x ~/path/to/alacritty.ti``. 

> Though as a sidenote, the last time I had tested without any edit to terminfo was on March 14. Not sure if this is a result of changing the terminfo, or something else in alacritty codebase or both. Anyway thanks! :)
