### ISSUE TITLE
OSX fullscreen glitchy text and selection

### ISSUE THREAD

**Issue by t-ricci-enhancers** [alacritty/alacritty#4905]
On macOS (currently tested on Catalina 10.15.7 19H524)  when the Alacritty (v0.7.2) is in fullscreen (OS window is dragged on a new fullscreen space), the text rendering is glitchy (some lines have distorted characters, pixelized)
Also selecting some text lines (clicking and dragging the cursor with the mouse) sometimes is difficult (first column character not selected and the line below the clicked one is being selected instead).

As soon as I exit fullscreen, in windowed mode the text is rendered just fine again.

See the screenshot for the text glitch (I'm using font "JetBrains Mono" Regular and Bold at 18.0 point size) :

![Screen Shot 2021-03-19 at 11 30 52](https://user-images.githubusercontent.com/34159726/111767655-42689c00-88a7-11eb-9804-94aa341356ff.png)

### System

OS: macOS
Version: alacritty 0.7.2 (5ac8060)

**Comment by chrisduerr** [comment]
Could you please try the latest macOS version?

**Comment by t-ricci-enhancers** [comment]
Hi @chrisduerr I don't have a Big Sur machine or VM ready right now, but I'll be upgrading my machine when I'll find some free time in the weekend to do a new clean install of the OS

**Comment by reportaman** [comment]
@t-ricci-enhancers I don't see the problem on my 2020 machine running Big Sur
