### ISSUE TITLE
Problem with config: invalid value: map, expected map with a single key; using default value

### ISSUE THREAD

**Issue by thisisjunsung** [alacritty/alacritty#4906]
### System

OS: Linux Mint
Version: alacritty 0.6.0
Linux/BSD: Bspwm and picom

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: [2021-03-19 23:28:50.357089567] [ERROR] [alacritty_config] Problem with config: invalid value: map, expected map with a single key; using default 

I copied https://github.com/TorchedSammy/dotfiles/blob/master/config/alacritty/alacritty.yml to ~/.config/alacritty.yml

**Comment by chrisduerr** [comment]
> I copied https://github.com/TorchedSammy/dotfiles/blob/master/config/alacritty/alacritty.yml to ~/.config/alacritty.yml

Why? Please don't copy random configuration files you've found online and then complain when you can't make them work.

**Comment by cole-h** [comment]
That said, I'd imagine it's due to https://github.com/TorchedSammy/dotfiles/blob/6217f8fcb0dc4a80fae19d87f09a36e8b202a842/config/alacritty/alacritty.yml#L142-L147, based on a quick skim.
