### ISSUE TITLE
PasteSelection leaves pasted text inverted

### ISSUE THREAD

**Issue by tomocafe** [alacritty/alacritty#4908]
### System

OS: Linux
Version: alacritty 0.7.1
Linux/BSD: X11, Budgie 10.5.2 (Solus)

### Logs

![PasteSelectionInverted](https://user-images.githubusercontent.com/20233563/111893541-9915c900-89c0-11eb-8e90-062f604868bc.png)

#### Steps to reproduce

1. Select text by dragging left-mouse click
2. Paste selection using middle mouse (or <kbd>Shift</kbd>+<kbd>Insert</kbd>)
3. Observe the pasted text has inverted color

After pressing the middle mouse (or <kbd>Shift</kbd>+<kbd>Insert</kbd>) the primary selection is pasted, but the text is inverted, which is not expected.

I've been using Alacritty on this system for quite some time and it didn't use to behave this way, but I'm not sure exactly when it started behaving this way. I don't see anything in the recent changes or documentation referencing this behavior. Is it intentional, or a bug? If the former, is there a way to turn it off (i.e. just paste the text, but don't invert the color, which makes it look "selected".)

**Comment by chrisduerr** [comment]
Try a different shell.

**Comment by tomocafe** [comment]
This system only has bash installed. That's my login shell. It's version 5.1.4.

Do you suspect it's shell-specific? What other shell should I try? (For me, /bin/sh is just a symlink to /bin/bash.)

**Comment by chrisduerr** [comment]
It's the shell that does this, this is nothing new.

**Comment by tomocafe** [comment]
Sorry for barking up the wrong tree, you are indeed correct. This is the result of the shell (bash) changing behavior, not the terminal emulator. (I checked with urxvt and it behaves the same way.)

For the benefit of any future readers who might land on this issue from a web search:

I recompiled an older version of bash (4.4.18) and it behaves the way I was expecting. My guess is from bash 4 to bash 5, this behavior changed.

## bash 4

![bash4](https://user-images.githubusercontent.com/20233563/111939393-61268880-8a89-11eb-9685-da0e2f460f36.png)

## bash 5

![bash5](https://user-images.githubusercontent.com/20233563/111939398-64ba0f80-8a89-11eb-8651-9588aed69f64.png)

**Comment by chrisduerr** [comment]
Don't disable bracketed paste mode. That's a bad idea.
