### ISSUE TITLE
How to use V-Block (vertical columns) in Vim? ctrl+shift+v doesn't work in alarcritty

### ISSUE THREAD

**Issue by ProgrammingLife** [alacritty/alacritty#4909]
Trying to call vertical block feature in vim pressing: ctrl+shift+v but it doesn't work in alarcritty.
My ~/.alarcritty.yml now is:
```
key_bindings:
  - { key: C,      mods: Control,           action: Copy             }
  - { key: V,      mods: Control,            action: Paste            }
  - { key: V,      mods: Control|Shift,    action: none             }
```
How to remove keybinding from alarcritty?
This feature works fine in urxvt.

### System
OS: Linux Mint 19.1
Version: 0.7.2
WM: X11, i3

**Comment by chrisduerr** [comment]
It's ctrl+v, not ctrl+shift+v.

**Comment by ProgrammingLife** [comment]
@chrisduerr, How to unbind a key in alarcritty? I thought action=none does it.
