### ISSUE TITLE
Alacritty doesn't launch with custom shortcut in KDE Plasma

### ISSUE THREAD

**Issue by Dmoayad** [alacritty/alacritty#4910]
This is a potential bug, since I have seen other posts in the internet about it. When I make a shortcut in KDE Plasma for Alacritty I can not launch it when I do the short cut. at first I thought this could be a KDE issue, but I tried to install other terminal emulators such as kitty and they launch when I do the shortcut I assign for them. Other non KDE programs are launch normally as well. I have only faced this issue with Alacritty. Any thoughts?

### System

OS: Arch Linux
Version: alacritty 0.7.2 (5ac8060b)
Linux/BSD: X11 ( KDE PLASMA)

### Logs

Crashes: STDERR, STDOUT ( no errors or crashes )
Font/Terminal size: default.
Keyboard and bindings: default.

**Comment by chrisduerr** [comment]
Do you set the shortcut to just Alacritty, or are you passing parameters?

**Comment by Dmoayad** [comment]
> Do you set the shortcut to just Alacritty, or are you passing parameters?

I'm not sure exactly, but I set the shortcut via the settings shortcuts in KDE Plasma. I added Alacritty as an application and set the shortcut.

**Comment by chrisduerr** [comment]
How did you install it?

**Comment by Dmoayad** [comment]
> How did you install it?

@chrisduerr I used `sudo pacman -S alacritty`

**Comment by chrisduerr** [comment]
You should try to log the stderr of Alacritty to see why it is shutting down. You should also make sure your $PATH is set appropriately when launching through KDE.

Generally there's nothing Alacritty can do here, it's just a matter of figuring out what you're doing wrong.
