### ISSUE TITLE
Error at start, [ERROR] [alacritty_config_derive] Config error: x: invalid type: floating point `0`, expected i8

### ISSUE THREAD

**Issue by dgtlmoon** [alacritty/alacritty#4911]
Built from current source, app seems to run but I get what I think is an error, font sizes are large too, unsure if that's related

### System

OS: Linux
Version: `alacritty 0.8.0-dev (17923ef)`
Linux: Nvidia GT 710
### Logs

Crashes: STDERR, STDOUT

[Alacritty-14769.log](https://github.com/alacritty/alacritty/files/6180397/Alacritty-14769.log)

![Screenshot_2021-03-22_08-54-50](https://user-images.githubusercontent.com/275001/111957606-87314480-8aec-11eb-948e-50d05744c8ec.png)

**Comment by chrisduerr** [comment]
If you get an error because your configuration file is wrong, could you at least share your configuration file please?

**Comment by dgtlmoon** [comment]
Oops my mistake! attached, sorry

[alacritty.yml.txt](https://github.com/alacritty/alacritty/files/6181207/alacritty.yml.txt)

**Comment by dgtlmoon** [comment]
If it helps, this is a default installation config file from a fairly early alacritty version

**Comment by chrisduerr** [comment]
> If it helps, this is a default installation config file from a fairly early alacritty version

In that case you should delete it entirely and just start out with a minimal configuration file.

Your font's offsets are all the incorrect type.
