### ISSUE TITLE
Could not open a new Alacritty instance with keybindings

### ISSUE THREAD

**Issue by fishsouprecipe** [alacritty/alacritty#4912]
macOS Catalina 10.15.7 (**19H524**)
alacritty 0.7.2 (**5ac8060**)

I'd like to implement Command+Comma macOS applications' standard behavior. This keys combination opens active app preferences. 

I wrote something that I can run from terminal and its doing well **(just opening)**

open -a Alacritty -n --args -e zsh -lc 'nvim ~/.config/alacritty/alacritty.yml'

It opens a new Alacritty instance but with broken lines and columns.
[There is how it looks](https://i.imgur.com/NjkzUCj.jpg)

But it does not work from keybindings with command.
[Config](https://i.imgur.com/dSxvy1W.jpg)
[$ALACRITTY_LOG with errors](https://i.imgur.com/hyOrT3G.jpg)

p.s. I also tried it with open -a Alacritty -n ..., but I'm here and I suppose that is a bug or ...?

**Comment by chrisduerr** [comment]
This is due to neovim. It can't handle a resize during startup. Try delaying neovim's start by .1s.
