### ISSUE TITLE
Cannot pass command-key execution to terminal application neovim.

### ISSUE THREAD

**Issue by Bryce-Davidson** [alacritty/alacritty#4917]
### System

macOS `Catalina@10.15.17 `
Alacritty`@0.7.2`

### Expected Behaviour

Upon utilizing a macOS-level keyboard-shortcut such as `<D-w>` alacrity intercepts the keyboard shortcut and executes the keyboard instruction rather than the OS.

Such behaviour is available on text editors such as VSCode and other macOS desktop applications.

### Actual Behviour

Alacrity does not intercept _(or so I think)_ the OS-level keyboard shortcut and macOS executes the keyboard shortcut according to system-level key bindings.

In the `<D-w>` case, macOS closes the focused application.

### Desire

I would like to be able to create an override to the OS-level keyboard shortcuts in alacritty so that I may bind these shortcuts in programs running within alacritty such as the`neovim` text editor.

A particular example would be, being able to bind the **command key** which has specified support in the neovim documentation, yet I am unable to create the mappings within neovim because the command key is intercepted at the OS-level. 

I've started a thread over at the neovim repo for this issue to see if this is functionality I need to write into the neovim program myself or if this is something I need to change in alacritty.

**Comment by chrisduerr** [comment]
System level bindings always take priority and that is intended.

**Comment by Bryce-Davidson** [comment]
Understood. Thanks!
