### ISSUE TITLE
Open Alacritty here uninstalling Gnome-terminal in Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by Corfucinas** [alacritty/alacritty#4920]
### System

OS: Linux (Ubuntu 20.04)
Version: alacritty 0.8.0-dev (17923ef)
Linux/BSD: X11/Wayland

Customizing and breaking your Linux installation is fun unless the system forces you to replace things with other things....
Currently, purging the default `gnome-terminal` on Ubuntu will replace it with xterm, the packages purged are:

```
The following additional packages will be installed:
  gnome-terminal-data nautilus-extension-gnome-terminal
The following NEW packages will be installed:
  gnome-terminal gnome-terminal-data nautilus-extension-gnome-terminal
```

Even if we make alacrity the default terminal, we will lose the ability to "Open with/Open here",  provided by nautilus/gnome which will save us from navigating directly by opening the terminal on the file, rather than navigating to it.

I'm aware, but not sure, if the way to override this is by writing a new file in /usr/share/kde4/services/ServiceMenus/ creating this ability if it is so:

1) Is there's a template we can use? (I tried to tinker around with it, but could not get it to work)
2) If not, is there's a solution, and could it be implemented as part of the alacrity documentation?

**Comment by chrisduerr** [comment]
This is really more a question you should ask Gnome than Alacritty. I can't tell you how to use your DE.
