### ISSUE TITLE
Option to cut off glyphs that are bigger than cell size

### ISSUE THREAD

**Issue by oredaze** [alacritty/alacritty#4921]
This is sort of a feature/enhancement request.
Right now, when certain glyphs (mainly box drawing) are bigger than the cell size they stick outside and overlap with the adjacent glyphs. They sort of 'bleed' into the next/previous ones. It would be nice if anything that sits outside of the character cell is cut off. Gvim does this (but only vertically) and it looks nicer.

If it is not clear what I mean, I will provide an image.
Btw, before you give the advice to use offsets in the config - know that this is a bad idea for this particular scenario.

**Comment by chrisduerr** [comment]
We intentionally do not do this because certain glyphs are expected to leave their boundaries. I see no reason to add a way to change this behavior.
