### ISSUE TITLE
Cursor thickness is increased incorrectly on wide cells

### ISSUE THREAD

**Issue by chrisduerr** [alacritty/alacritty#4922]
When a cursor like the underline is below a wide cell, its thickness is increased (I'd assume doubled).

**Comment by stokhos** [comment]
Hi @chrisduerr I'd like to work on this issue, but how can I set wide cell on my pc?

**Comment by chrisduerr** [comment]
I noticed this by typing `echo "https://example.org/test汉字"`, just copy/pasting this and moving your cursor on top of one of the Chinese characters should be sufficient.
