### ISSUE TITLE
RFE: auto-adjust the font size to keep the width-in-characters constant

### ISSUE THREAD

**Issue by t184256** [alacritty/alacritty#4924]
I use a tiling environment (sway) and I need my terminals to be 80 character-wide.
This is hard to maintain depend on which screen the window is on and whether I'm in a split (and god help me if adjust the spit width).

So far I ended up generating several alacritty configs for different widths and re-launching it with the right config depending on the width I'm targeting right now (and re-attaching to a tmux session). This re-launching is pretty cumbersome. I found myself wondering whether I should cobble some resizer that'd somehow track different instances tracking different configs, hook into sway and rewrite the configs when the width changes. All that hassle for having the width constant - something that the terminal itself can probably handle better.

Could alacritty have some font size = auto to maintain the target width in characters constant? We already have auto padding to swallow the rounding error.

**Comment by chrisduerr** [comment]
That request seems somewhat ridiculous to me. You could certainly patch it if you wanted to, but I see no reason to add it to Alacritty.

**Comment by t184256** [comment]
Just in case somebody ends up here with a similar request, i worked around that with a wrapper. It scrapes the resized alacritty window size from the output and modifies the font size in a per-instance config file: https://github.com/t184256/alacritty-autoresizing
