### ISSUE TITLE
Help: Special keybinding for Alt on MacOS

### ISSUE THREAD

**Issue by ricbermo** [alacritty/alacritty#4925]
Hello there, thanks for taking your time to read this.
This is not a bug report. I just need some help figuring out how to change some keybindings.

I'm currently using iTerm3 on and I'm using the following setting:
 
![image](https://user-images.githubusercontent.com/2601363/112752558-3fe9fe80-8f99-11eb-9add-5fd6f28bc495.png)

It helps me switching panes when I run tmux. W/o that, I cannot switch panes by pressing alt + H/K/J/L.
How could I implement such a setting?

```bash
# Remap window navigation
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-j select-pane -D
bind -n M-k select-pane -U
```

Thanks in advance.

### System

OS: macOS
Version: `alacritty --version` output

**Comment by chrisduerr** [comment]
Alt keys are forwarded by default when you hold option on macOS. You just need to make sure your keyboard layout isn't modifying the base key.

**Comment by ricbermo** [comment]
@chrisduerr thanks for your reply, but I have no idea of what that means 😬. would you mind explaining it a little bit, if possible. TY

**Comment by carlmjohnson** [comment]
I also have this problem. When I type option-[, it just enters `“` instead of being intercepted by tmux.
