### ISSUE TITLE
How to pass `shell.args` as cli options?

### ISSUE THREAD

**Issue by x3rAx** [alacritty/alacritty#4929]
I'm on Windows and I want to make a shortcut to open WSL in Alacritty directly. So I try to run `wsl.exe ~`  by passing shell arguments to Alacritty as options:

```
alacritty -o shell.program="wsl.exe" -o shell.args[0]="~"
```

The `shell.program` option works fine but starts in the wrong directory. But as soon as I add `shell.args` I get an error. As `shell.args` is actually an array in the `yaml` file, I don't know how to pass it to `alacritty`. I already tried the following:

- `shell.args[0]="~"`
- `shell.args.0="~"`
- `shell.args=["~"]`
- `shell.args="~"`

but none of them worked. Can someone tell me how to achieve this?

### System

OS: Windows
Version: alacritty 0.7.2 (5ac8060)

### Logs

```
[2021-03-31 11:27:55.611418700] [ERROR] [alacritty_config_derive] Config error: shell: data did not match any variant of untagged enum Program
```

**Comment by chrisduerr** [comment]
Just use `alacritty -e`.

**Comment by x3rAx** [comment]
Oh wow, how did I miss that? Thanks, that solved it! Please excuse the disturbance.

**Comment by nooop3** [comment]
I still can not override the `shell.args`, `toml` can parse the `shell.args=["string",]` , but the Alacritty can not replace the `shell.args` option.
The shell also accepts the string argument:
`alacritty -o 'window.startup_mode="Windowed"' -o 'shell="/bin/zsh"'`
