### ISSUE TITLE
Developer Cannot Be Verified (MacOS)

### ISSUE THREAD

**Issue by lanmonster** [alacritty/alacritty#4932]
My system is locked down pretty tight because of work. I would like to use alacritty, but I can't get the app to open because the "Developer cannot be verified"

### System

OS: macOS
Version: 0.7.2.dmg

### Logs

N/A

![image](https://user-images.githubusercontent.com/3748720/113323242-5cf53900-92db-11eb-8e37-b210b528a5bc.png)

**Comment by chrisduerr** [comment]
You need to open Alacritty through finder with right click -> open.
