### ISSUE TITLE
Alacritty shows a smiley for U+FE0F

### ISSUE THREAD

**Issue by pinpox** [alacritty/alacritty#4937]
Hello,

The [variation selector](https://codepoints.net/U+FE0F#:~:text=U%2BFE0F%20was%20added%20to,property%3F%20from%20the%20preceding%20character.) character seems to be rendered wrong in alacritty. This is an example (my zsh prompt):

```
~ via ❄️  impure (shell)
➜
```
 Result:
![image](https://user-images.githubusercontent.com/1719781/113462059-6f788b00-941f-11eb-85bf-2ab9dda31218.png)
Right of the crystal emoji, there is a dotted smiley shown.

This is only happening on alacritty, I tried various other terminals and none of the others had this issue, so I assume it's a bug. My guess is that `fe0f` (link above) is the problem:
```
echo '<fe0f>'
```
Shows the same smiley for me:
![image](https://user-images.githubusercontent.com/1719781/113462171-e7df4c00-941f-11eb-98c2-7183f7ddda5b.png)

### System

OS: Linux/BSD
Version: alacritty 0.7.2
Linux/BSD: X11, Picom, awesomeWM

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by chrisduerr** [comment]
Alacritty doesn't do any text layout, so this is to be expected.

**Comment by pinpox** [comment]
@chrisduerr But why would it show a smiley there?

**Comment by chrisduerr** [comment]
That's probably one of your fonts incorrectly placing a smiley at that codepoint. Alacritty just forwards the codepoint to freetype.

**Comment by pinpox** [comment]
That's what I thought, but it seems to only happen on alacritty. I tried the same font on different terminals.

**Comment by chrisduerr** [comment]
Most other terminal emulators probably do text layout, never forwarding this to freetype to begin with.

**Comment by pinpox** [comment]
Thanks for the explanation, that makes sense then.
