### ISSUE TITLE
Using Super in emacs in terminal

### ISSUE THREAD

**Issue by xircon** [alacritty/alacritty#4938]
### System

OS: Linux - EndeavourOS
Version: alacritty 0.8.0-dev (3ed0430)
Linux/BSD: X11 Gnome40 (normally Plasma).

Trying to setup emacs in the terminal and have bound super+r to counsel-recentf.  This works in konsole,  but doesn't work in Alacritty (and gnome-terminal, just playing with gnome.

Completely lost on what to do,  tried all sorts of combinations in the yaml file - none of the work.

**Comment by chrisduerr** [comment]
It's not supposed to work.

**Comment by tummetott** [comment]
any updates here? still not possible to pass super key kombos like super + w to the terminal application?

**Comment by xircon** [comment]
I now use ghostty with the emacs package kkp

https://github.com/benotn/kkp

Might work in alacritty,  definitely works in kitty & ghostty (well it is kitty keyboard protocol!!).

**Comment by tummetott** [comment]
@xircon thank. it also works flawlessly in WezTerm. I really like Alacritty, but this limitation is currently a deal-breaker. Why hardcode the Super (Command) key so it never reaches the terminal application? I understand that Alacritty reserves those bindings for its own shortcuts, but it should at least be possible to disable them (for example by setting the keymap to None) and have the Super-modified sequences forwarded to the running program.

**Comment by xircon** [comment]
Vote with your feet, must try wezterm at some point.

**Comment by arichiardi** [comment]
Is this still not working? I tried alacritty on Windows and I like the simple config but not having a key mapping is a bit underwhelming...

**Comment by tummetott** [comment]
> Is this still not working? I tried alacritty on Windows and I like the simple config but not having a key mapping is a bit underwhelming...

unfortunately yes. still not working

**Comment by arichiardi** [comment]
@tummetott yeah - that's unfortunate  - do you have any recommendation for a terminal that can map the Win Cmd to Super (for non-gui emacs...) by any chance?

**Comment by tummetott** [comment]
> @tummetott yeah - that's unfortunate  - do you have any recommendation for a terminal that can map the Win Cmd to Super (for non-gui emacs...) by any chance?

I'm currently using wezterm and I quite like it!
