### ISSUE TITLE
Alacritty crashes at startup

### ISSUE THREAD

**Issue by Quentincestino** [alacritty/alacritty#4940]
My alacritty is crashing at startup, It does it since my packages update, using the community/alacritty package.

### System

OS: Linux
Version: alacritty 0.7.2 (5ac8060b)
Linux/: Arch Xorg i3

### Logs
[2021-04-04 22:21:21.350057516] [ERROR] [alacritty] Alacritty encountered an unrecoverable error:
Error creating GL context; Received multiple errors. Errors: `[OsError("eglInitialize failed"), OsError("GL context creation failed")]`

**Comment by nixpulvis** [comment]
@Quentincestino does your device support OpenGL 3.3+?

**Comment by c02y** [comment]
Did you restart your OS, this problem(both alacritty and kitty won't start) happens to me when I update my packages several days ago(Manjaro).

**Comment by Quentincestino** [comment]
> @Quentincestino does your device support OpenGL 3.3+?

I guess yes, I have a GTX 1060 with 6Gb of VRAM

**Comment by Quentincestino** [comment]
> Did you restart your OS, this problem(both alacritty and kitty won't start, but cannot remember whether it was the same error message) happens to me when I update my packages several days ago(Manjaro).

Well thanks for your message, everything is fixed but I still don't understand how did I do to break OpenGL...
