### ISSUE TITLE
Removing words using control + backspace

### ISSUE THREAD

**Issue by r00ster91** [alacritty/alacritty#4942]
Using control + arrow keys it is possible to skip over whole words and using control + delete it is possible to remove a whole word behind the cursor, however backspace + arrow keys does not remove a whole word and only removes one character. It would be nice if Alacritty had this basic feature. This is what's not possible with Alacritty currently:

https://user-images.githubusercontent.com/35064754/113521621-e8e8b880-959a-11eb-8126-1525950c8979.mp4

**Comment by chrisduerr** [comment]
That's up to your shell.
