### ISSUE TITLE
Terminanl removes static characters

### ISSUE THREAD

**Issue by J4CKVVH173** [alacritty/alacritty#4943]
I have a problem with terminal. When I use language different from English I can delete static characters.

### System

OS: Linux
Version: alacritty 0.7.1 (a852eb85)
Linux/BSD: X11

![image](https://user-images.githubusercontent.com/33596000/113522565-37ea1a00-95aa-11eb-85aa-e3fdc8138d58.png)

**Comment by westofer** [comment]
try running `TERM=xterm` and see if the problem goes away

**Comment by J4CKVVH173** [comment]
@westofer it does not help

**Comment by westofer** [comment]
@J4CKVVH173  does it only happen with bash?

**Comment by J4CKVVH173** [comment]
I solved this problem. I set [locale](https://wiki.archlinux.org/index.php/locale) and now it works correct
