### ISSUE TITLE
Automatic scrolling breaks on resize

### ISSUE THREAD

**Issue by chrisduerr** [alacritty/alacritty#4944]
Since 58cae8f2edf44e6bf0721543c61edb57bdf7d776 there has been an issue where the viewport would get locked into place when the last line is longer than the new viewport width and thus broken onto a new line.

Since the viewport is kept in place, the new line is put below the viewport increasing the display offset to 1. But since we've been following the terminal output we now suddenly won't do that anymore. To a user it might look like the terminal suddenly "froze".

I think we should add a special case where we keep everything stuck at the bottom of the viewport if we're already at the bottom, just so we keep following all new output.

@st3iny you wrote the original PR, are you interested in looking into this?

**Comment by st3iny** [comment]
Sure. I will work on a fix and send a PR later.

**Comment by st3iny** [comment]
While testing my code I noticed that sometimes a line gets deleted when growing columns. This also causes the viewport to not be rotated correctly (because one more line is missing). I didn't notice this when testing my former PR.

**Comment by chrisduerr** [comment]
I'm pretty sure I've tested deleting lines. Could you be a bit more specific in what you tested?

Also feel free to open an issue if you cannot solve it immediately, just so it doesn't get lost.

**Comment by st3iny** [comment]
> I'm pretty sure I've tested deleting lines. Could you be a bit more specific in what you tested?
> 
> Also feel free to open an issue if you cannot solve it immediately, just so it doesn't get lost.

I will open a new issue and attach a screen recording.
