### ISSUE TITLE
vim-airline themes don't work properly

### ISSUE THREAD

**Issue by gmr458** [alacritty/alacritty#4945]
I use vim-airline, when I go from normal mode to insert mode in neovim it is supposed to change the color like below.
FROM NORMAL MODE:
![normal_mode](https://user-images.githubusercontent.com/53343401/113543397-ecd10680-95ab-11eb-8118-0555a1420893.png)
TO INSERT MODE:
![insert_mode](https://user-images.githubusercontent.com/53343401/113543568-40dbeb00-95ac-11eb-8a1d-00e464a3736c.png)

But this is what happens.
FROM NORMAL MODE:
![normal_mode_2](https://user-images.githubusercontent.com/53343401/113543782-b21b9e00-95ac-11eb-900d-6394b2e59268.png)
TO INSERT MODE:
![insert_mode_2](https://user-images.githubusercontent.com/53343401/113543890-e98a4a80-95ac-11eb-84d4-b6b5d2a86f5d.png)

As you can see the problem here is:

- Colors are not displayed as they should.
- In insert mode information is hidden, specifically the name of the mode and the information that appears on the far right.

I use Alacritty version 0.7.2.
The color scheme I use in Neovim and Alacritty is Dracula although the same problem happens with Gruvbox.

**Comment by chrisduerr** [comment]
I'd assume you're expecting it to use truecolors without having that enabled in vim.

**Comment by gmr458** [comment]
@chrisduerr termguicolors

**Comment by gmr458** [comment]
@chrisduerr Thanks, it worked.
