### ISSUE TITLE
Background opacity not working on Windows 10 v1809

### ISSUE THREAD

**Issue by luisiacc** [alacritty/alacritty#4946]
Setting background_opacity doesn't work, the lower de opacity the greater the bright of the terminal, but no opacity, weird.
### System

OS: Windows 10, 1809
Version: `alacritty 0.7.2 (5ac8060`

## Config file

[alacritty.zip](https://github.com/alacritty/alacritty/files/6256655/alacritty.zip)

Opacity on 0.5:
![image](https://user-images.githubusercontent.com/31720261/113544881-1e9b9a80-95b7-11eb-9757-2e3754c193d8.png)

Opacity on 0.9:
![image](https://user-images.githubusercontent.com/31720261/113544909-2eb37a00-95b7-11eb-9b5d-b21b6d397ba8.png)

**Comment by chrisduerr** [comment]
You're on a rather old version of Windows, it might be worth updating. Generally transparency should work on Windows afaik.
