### ISSUE TITLE
how could set window dimension use -o command parameter

### ISSUE THREAD

**Issue by iysheng** [alacritty/alacritty#4952]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux
Version: `alacritty 0.8.0-dev (974392c)` 
Linux/BSD: X11 dwm

### Logs
I want to set alacritty window size when start by `-o window.dimensions=` option, But I don't know how to set thr paramter. for examlpe, i want to set the columns = 80, line = 60.Could i use the -o paramter achive this ?

**Comment by chrisduerr** [comment]
```
alacritty --option "window.dimensions={lines: 10, columns: 10}"
alacritty --option "window.dimensions.columns=10" --option "window.dimensions.lines=10"
```

**Comment by iysheng** [comment]
@chrisduerr sorry, I could not see the right window size when I use the command paramter ```alacritty --option "window.dimensions={lines: 10, columns: 10}"```.I just see the window size is also full screen. :confused:

**Comment by nixpulvis** [comment]
@iysheng I don't really know much about `dwm`, but I'm guessing you need to tell it to stop resizing the window.
