### ISSUE TITLE
Paste only pastes first byte with manual mouse selection

### ISSUE THREAD

**Issue by jamesodhunt** [alacritty/alacritty#4953]
### System

OS: Linux
Version: `alacritty --version` output: `alacritty 0.8.0-dev (cbcc129)`
Linux/BSD: Fedora 33

## Problem

Manually selecting text using the mouse and then attempting to paste it only pastes the first byte that is *selected*:

- If you select "forwards" (left to right), the first byte on the left of the selection will be pasted on middle click.
- If you select "backwards (right to left), the *last* byte on the right (aka the first byte selected) will be pasted on middle click.

Notes:

- *Double-clicking* a word and pasting with the middle mouse button works correctly.
- *Triple-clicking* an entire line and pasting with the middle mouse button works correctly.

I've run `alacritty` as follows but see no errors:

```bash
$ script -fec 'alacritty -vvv --print-events -o debug.log_level=Trace'
```

This feels similar to #4735. Random thought: I wonder if there is any way to automate copy/paste testing in a CI environment?

**Comment by chrisduerr** [comment]
Could you share a recording of this in action? Also are you on X11 or Wayland?

**Comment by jamesodhunt** [comment]
Hi @chrisduerr - sure: https://asciinema.org/a/tMNVg9O6TFtQCuTlbzEFbyZix

**Comment by jamesodhunt** [comment]
This is on Wayland.

**Comment by chrisduerr** [comment]
Is this a regression? If so, can you bisect it?

**Comment by chrisduerr** [comment]
Also could you please not use asciinema to report a terminal bug? It's rather useless for this.

**Comment by jamesodhunt** [comment]
@chrisduerr - Can you recommend a better recorder that works on Wayland? It's very easy to reproduce this bug so I'm not sure it's worth much effort getting a good recording tbh ;) I'm happy to bisect but won't be able to do this for a few days. But yes, it's a regression afaik.

**Comment by chrisduerr** [comment]
I can't recommend anything on Wayland. But obviously something that actually records the screen is required to give a useful display of what's actually going on.

If this happens on Wayland, that's likely the reason why I cannot reproduce it. A bisect in that case would probably be more useful than a recording.

**Comment by chrisduerr** [comment]
I'd assume the issue is due to Wayland DoS protection and likely comes from https://github.com/alacritty/alacritty/commit/cbcc12944006603131119b73c2ad72ebccf4562d.

**Comment by jamesodhunt** [comment]
@chrisduerr - confirmed - that top commit cbcc129 is the problem.

**Comment by chrisduerr** [comment]
@jamesodhunt Could you verify that #4979 solves your issue?

**Comment by jamesodhunt** [comment]
Hi @chrisduerr - yep, works for me! Thanks.
