### ISSUE TITLE
alacritty -e nvim get wrong size

### ISSUE THREAD

**Issue by zdmgmail** [alacritty/alacritty#4956]
use `alacritty -e nvim` , should open in proper size 

this video use alacritty, xterm, st , alacritty open in proper size, but nvim small 

https://user-images.githubusercontent.com/50515839/114025186-72ec9600-98a7-11eb-8f19-08b2908f1ec5.mp4

I use default config, tried `TERM=alacritty` `TERM=xterm-256color`

change alacrity size will make nvim size change to correct size

If open alacritty then open nvim, work ok, but  hope use `-e` to open

I don't see this happen on other program, so seems neovim problem , but this only happen on alacritty...

### System

OS: Linux/BSD/macOS/Windows

Linux ar 5.11.11-arch1-

Version: `alacritty --version` output

alacritty 0.7.2 (5ac8060b)

Linux/BSD: X11/Wayland, DE or Compositor and WM

x11 , awesomewm/i3wm

### Logs

Font/Terminal size: `alacritty -vv`

[Alacritty-12527.log](https://github.com/alacritty/alacritty/files/6278497/Alacritty-12527.log)

**Comment by chrisduerr** [comment]
You have to delay startup of vim, it's due to a vim issue.

**Comment by zdmgmail** [comment]
> You have to delay startup of vim, it's due to a vim issue.

But why work ok on other terminal...
>  Is there some vim config need for alacritty?
