### ISSUE TITLE
tmux-themepack is not rendering properly

### ISSUE THREAD

**Issue by AbhinavAchha** [alacritty/alacritty#4957]
Hi

I am facing this issue in which the [tmux-themepack](https://github.com/jimeh/tmux-themepack) is not properly working with alacritty

![Screenshot_20210408_215535](https://user-images.githubusercontent.com/68775533/114062868-a0d8d700-98b5-11eb-8675-6ce06dc7d8d1.png)

whereas in konsole it renders correctly
![Screenshot_20210408_215749](https://user-images.githubusercontent.com/68775533/114062937-b4843d80-98b5-11eb-82c5-055df84d8c99.png)

**Comment by chrisduerr** [comment]
Please be more specific.

**Comment by AbhinavAchha** [comment]
Tmux-themepack is a tmux based theme  The bottom of the terminal is the theme's design which is not rendered properly

I am currently using kubuntu 20-04 with alacritty version 0.7.2

**Comment by chrisduerr** [comment]
Define "properly".

**Comment by AbhinavAchha** [comment]
This is the proper way that is to be rendered

https://raw.githubusercontent.com/jimeh/tmux-themepack-previews/1.0.0/powerline/double/magenta-preview.png
but its not rendering in alacritty 

but its properly rendering in other terminals like Konsole

**Comment by nixpulvis** [comment]
Looks like a font issue.
