### ISSUE TITLE
Expose alacritty API for use in Rust terminals/IDEs.

### ISSUE THREAD

**Issue by DefunctLizard** [alacritty/alacritty#4961]
I'm interested in using alacritty as a backend in Rust IDEs or terminals (through QT/GTK), is exposing the API so alacritty can be used as a library in Rust applications something that the project is interested in doing?

I can submit a pull request if this sounds like something that would be accepted.

**Comment by chrisduerr** [comment]
See `alacritty_terminal` crate.
