### ISSUE TITLE
Can type `∆`(`<kdb>alt</kbd><kbd>j</kbd>`) and ˚(<kbd>alt</kbd><kbd>k</kbd>) in side Vim?

### ISSUE THREAD

**Issue by nyngwang** [alacritty/alacritty#4973]
### System

OS: macOS
Version: alacritty: 0.7.2

Vim, NeoVim, Alacritty are all installed via Homebrew and at latest version.

### Logs

If not in Vim I can type these two symbols described in the title, while inside Vim it output nothing, while I want to use them in shortcut.

**Comment by chrisduerr** [comment]
Disable `alt_send_esc`.
