### ISSUE TITLE
Can't get true color inside tmux

### ISSUE THREAD

**Issue by darioisthebest** [alacritty/alacritty#4990]
I tried to get true color inside tmux in alacritty, but I can't get that working, I tried all day and viewed all issues and tried all the possible solutions

### System

OS: Linux
Version: `alacritty 0.7.2 (5ac8060b)`
Linux: X11, picom and herbstluftwm

**Comment by chrisduerr** [comment]
This is a tmux issue. If you need support with tmux please ask them.

**Comment by darioisthebest** [comment]
Thanks, now I opened a [tmux issue](https://github.com/tmux/tmux/issues/2665)
