### ISSUE TITLE
Extra new lines inserted on copy (Windows)

### ISSUE THREAD

**Issue by andrewvaughanj** [alacritty/alacritty#4993]
Firstly, Alacritty seems *great* and so close to as-perfect-as-could-be-expected-given-I'm-on-Windows, so thanks for hard work to build it!

### High-level

After reading *a lot* of posts about the status of this with `alacritty`, I 100% understand I'm asking for something that "upstream" probably wouldn't accept as a feature. However, I am totally happy to maintain and build *my own* fork of `alacritty` if I can work out how to resolve this.

#### What's my problem?

When I copy text out of Alacritty the "soft" wrapped line-endings are transformed into "hard" CRLFs, which then mess-up on paste.

The prime example here is when you try to copy an SSH public key but the key gets broken at the width of the terminal window.

#### Steps to resolution

I tried messing with `fn copy_selection(&mut self, ty: ClipboardType)` to get what I wanted, and I was able to change the behaviour of copy, but I wasn't able to achieve the outcome I'd like.

Given when I copy out of Alacritty, I see CRLF, I'm surprised that `text.replace("\r\n", "")` doesn't work -- I can replace `"\n"` with `""` (to get totally flat output), but it seems that replacing `"\r\n"` doesn't work (it is almost like `"\r\n"` isn't in the selection *at all*).

What gives me hope that might be possible is that re-sizing the terminal *does* cause these soft-wrapped lines to re-flow (while lines with proper new lines aren't reflowed) -- if I can just work out what the control characters are here, hopefully I can "undo" the hard-wrapping in copy.

Is this possible? Can someone provide some direction on how to achieve this? If I try this in Terminus or MSYS2's shell, then copying these "wrapped" long lines does work (all three are starting a MSYS2 `zsh`).

**To be clear**: I'm not asking this to be solved for me (and I'm aware that upstream might not take this), but any direction/suggestions/being told that what I want is impossible, would be great!

### System

OS: Windows (`Microsoft Windows [Version 10.0.18363.1443]`)
Version: `alacritty 0.8.0-dev` (`28abb1f`)

#### `alacritty -vv`

```
[2021-04-21 16:12:18.750510600] [INFO ] [alacritty] Welcome to Alacritty
[2021-04-21 16:12:18.752511000] [INFO ] [alacritty] Configuration files loaded from:
                                                      "C:\\Users\\vuljaw\\AppData\\Roaming\\alacritty\\alacritty.yml"
[2021-04-21 16:12:18.754511300] [DEBUG] [alacritty] Estimated DPR: 2.25
[2021-04-21 16:12:18.754511300] [DEBUG] [alacritty] Estimated window size: Some(PhysicalSize { width: 2312, height: 4177 })
[2021-04-21 16:12:18.754511300] [DEBUG] [alacritty] Estimated cell size: 23 x 49
[2021-04-21 16:12:19.102015000] [INFO ] [alacritty] Device pixel ratio: 2.25
[2021-04-21 16:12:19.105015000] [INFO ] [alacritty] Initializing glyph cache...
[2021-04-21 16:12:19.110014600] [INFO ] [alacritty] ... finished initializing glyph cache in 0.0048526s
[2021-04-21 16:12:19.110514600] [INFO ] [alacritty] Estimated DPR correctly, skipping resize
[2021-04-21 16:12:19.110514600] [INFO ] [alacritty] Cell size: 23 x 49
[2021-04-21 16:12:19.110514600] [INFO ] [alacritty] Padding: 6 x 6
[2021-04-21 16:12:19.111015300] [INFO ] [alacritty] Width: 2312, Height: 2113
[2021-04-21 16:12:19.142014400] [INFO ] [alacritty] PTY dimensions: 42 x 100
[2021-04-21 16:12:19.145017600] [INFO ] [alacritty] Initialisation complete
[2021-04-21 16:12:19.146014900] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[2021-04-21 16:12:19.146014900] [INFO ] [alacritty] Padding: 6 x 6
[2021-04-21 16:12:19.146014900] [INFO ] [alacritty] Width: 2312, Height: 2113
```

#### `alacritty --print-events`

(I tried to get this, but I absolutely drowned, so I don't know what to share)

**Comment by nixpulvis** [comment]
I was thinking about trying to write up a proposal for a more generic Copy/Paste pipeline given some discussion between @chrisduerr and myself in IRC.

The conversation started with the topic of the newly added "hints" `Paste` action, since there could be a desire to allow pasting strings which are expansions (or transforms in general) on the actual matched data.

This deserves a more fleshed out proposal however because it should be consistent with the way `Paste` works, and perhaps even allowed in other places like our title setting (as requested by users in the past). There's also been the abandoned #4550, which may be relevant. Lots of moving pieces to consider...

I know this doesn't help your direct goal of implementing the desired functionality, but it might illuminate a path towards upstream. I'll do my best to remember this use case if/when I get around to opening the proposal.

@andrewvaughanj if you have any ideas about how this might look, feel free to chime in.

**Comment by andrewvaughanj** [comment]
Hmm, well, after posting what I wrote, I then found this:

- https://github.com/microsoft/terminal/issues/405#issuecomment-497548525

which, if it is to be believed (and I have no reason _not_ to believe it) then there's no way to achieve this as ConPTY has soft-wrapped these lines in a way that Alacritty could have no way of knowing -- they're literally identical to hard-wrapped lines.

I would guess that, on resize, ConPTY reflows the text and then just forwards that to Alacritty to display (which is why reflowing is soft-newline aware).

One idea would be to emulate this approach (which powers VS Code's terminal):

- https://github.com/xtermjs/xterm.js/blob/32d6613811e403b3693d004b86c8a664553eaa59/src/WindowsMode.ts#L11-L29

That is, if the length of the line is the width of the terminal and the last character is newline, glue it to the previous one; seems like a horrible hack, but maybe it could work for me (and it would be better than the current situation).

**Comment by chrisduerr** [comment]
The problem is with Windows, not with Alacritty. On Linux/macOS this works just fine by default.

Just ask Microsoft to fix this or avoid using an operating system that doesn't want to be used.

**Comment by andrewvaughanj** [comment]
@chrisduerr yes, I do 100% agree with you that this is a Windows issue and *not* an Alcritty issue -- this is why I asked for *help* in my original post, rather than saying "this is a bug in Alacritty"; I tried to make it clear that I understood that this was not something I was trying to get fixed in upstream, but I wanted assistance in working around it *in my own version*.

While it is easy to say "ask Microsoft to fix it", the fact that lots of other terminals (e.g., Terminus/VS Code/xterm.js; Windows Terminal, etc.) already work-arounds to support this use-case; this, to me, suggests it is a known nuance of supporting ConPTY as a backend, rather than something as a given.

I am simply interested in implementing my own "work around" to make me more productive on the shell.

> On Linux/macOS this works just fine by default.
>

Can you point me to how this works on Linux? For example, what are you given from the shell that allows Alacritty to know when/where to soft-wrap and how to unwrap it?

Does anyone know if this ever work with WinPTY?

Just to reiterate: I know this isn't a bug in Alacritty, and any pointers on how it works on "correct" platforms (== Linux or macOS) would be useful, so I can see if I can emulate it (in my own fork of) Alacritty.

Thanks!

**Comment by chrisduerr** [comment]
> Can you point me to how this works on Linux? For example, what are you given from the shell that allows Alacritty to know when/where to soft-wrap and how to unwrap it?

Linux has PTYs that aren't stupid. That helps a lot. A PTY has zero business wrapping any lines.

**Comment by andrewvaughanj** [comment]
Zero arguments about the stupidity of Windows/ConPTY; zero arguments about using a platform that wants to be used; zero arguments that this *isn't* a Alacritty issue.

**However**, we are where we are, and I'd love to "hack around" this problem to make Alacritty more usable _for me_ on Windows.

What are your thoughts on **me** implementing that something that looks like https://github.com/xtermjs/xterm.js/blob/32d6613811e403b3693d004b86c8a664553eaa59/src/WindowsMode.ts#L11-L29 in `line_to_string`? Do you think that this would be possible/would solve **my** issue?

Again, I'm not asking you to do this, I'm not asking you to integrate my changes ... I'm trying to get some help so I can solve a problem that affects me (and maybe others).

**Comment by chrisduerr** [comment]
If other terminals do it, of course you can do it too. But I'm not going to spend any time on that and it's never going to land upstream.

**Comment by andrewvaughanj** [comment]
Just to confirm: you're not able to provide *advice* if something I want to do is even reasonable?

**Comment by chrisduerr** [comment]
I do not believe this to be reasonable. Windows dumb ConPTY is enough of a burden already without having to implement crappy workaround for it.

This is about as trivial as an issue could be to resolve, I have no interest doing that work for you.

**Comment by andrewvaughanj** [comment]
I **do not** want you to do the work; I'm just hoping that you, as a maintainer for Alacritty, could tell me if my suggestions on how I could address this are reasonable (given I've never touched this code before).

I'm literally asking for _help_/_guidance_ with the full expectation that I will do the work, and that work will never be merged.

**Comment by andrewvaughanj** [comment]
Does:

```diff
diff --git a/alacritty_terminal/src/term/mod.rs b/alacritty_terminal/src/term/mod.rs
index 199fd20..8a9d3e7 100644
--- a/alacritty_terminal/src/term/mod.rs
+++ b/alacritty_terminal/src/term/mod.rs
@@ -430,7 +430,8 @@ impl<T> Term<T> {

         if cols.end >= self.columns() - 1
             && (line_length.0 == 0
-                || !self.grid[line][line_length - 1].flags.contains(Flags::WRAPLINE))
+                /* || !self.grid[line][line_length - 1].flags.contains(Flags::WRAPLINE)) */
+                || self.grid[line][cols.end].c == ' ')
         {
             text.push('\n');
         }
```

look like a feasible solution for the issue I have? I am not saying "reasonable" because we all agree it is **unreasonable** to have to fight ConPTY like this, but I would like to know if I could have implemented a better workaround.

I commented the `WRAPLINE` sub-condition because it will always true on ConPTY (which would always give the newline).

Thanks!

**Comment by andrewvaughanj** [comment]
For anyone who gets this far through this thread, *and if this issue affects you*, then please see here:

- [https://github.com/andrewvaughanj/alacritty/commit/dc24686f5b9f327b8beb5e5cb7beeac759a8660a](https://github.com/andrewvaughanj/alacritty/commit/dc24686f5b9f327b8beb5e5cb7beeac759a8660a)
- [https://github.com/andrewvaughanj/alacritty/tree/windows_copy_long_lines](https://github.com/andrewvaughanj/alacritty/tree/windows_copy_long_lines)

This change resolves the issue with copying (e.g.,) `~/.ssh/id_rsa.pub` but also copying files that do have genuine `\n` (e.g., `cat ~/.zshrc`).

**Comment by glav-git** [comment]
I think Alacritty is a great terminal emulator, I really enjoyed its minimalism and speed! It was a joy to use, except on Windows...
> Just ask Microsoft to fix this or avoid using an operating system that doesn't want to be used.

I'd much rather **avoid using an terminal emulator that doesn't want to be used** on my current operating system (event if it's "crappy", "stupid" and "dumb"), cause honestly this is just an impression that I got from this thread. I hate Windows from a bottom of my heart, they always make things difficult for no reason, and I feel you man! But "support for Windows" where I can't paste text normally without recompiling project with custom patch is just a no go for me and, I think, for a lot of people.

**Comment by vcc2233** [comment]
try use a ahk script, use `ctrl+shift+v`

```
#Requires AutoHotkey v2.0
#SingleInstance Force
#Warn  
#HotIf WinActive("ahk_exe Alacritty-v0.15.1-portable.exe")
{
    
    ;^v::PasteWithLF()
    
    
    ^+v::PasteWithLF()
    
    
    ;+Insert::PasteWithLF()
}
#HotIf
PasteWithLF() {
    
    
    originalClipboard := A_Clipboard
    
    try {
        
        currentClipboard := A_Clipboard
        
        
        if (currentClipboard !== "") {
            
            fixedClipboard := StrReplace(currentClipboard, "`r`n", "`n")
            
            
            if (fixedClipboard != currentClipboard) {
                A_Clipboard := fixedClipboard
                ToolTip("changed  (CRLF → LF)")
                SetTimer(() => ToolTip(), -1000) 
            }
            
            
            Send("^+v")
            Sleep(50) 
        }
    }
    catch as err {
        ToolTip("paste error: " err.Message)
        SetTimer(() => ToolTip(), -2000)
    }
    finally {
        
        if (originalClipboard) {
            A_Clipboard := originalClipboard
        }
    }
}

```

**Comment by HongjuneKim** [comment]
It appears that a fix for this bug has already been proposed. Given that it renders the terminal unusable on Windows it's unclear why this hasn't been fixed after such a long time. As an end user, I'm not concerned with the origin of the issue, only with the fact that other terminals on the same operating system do not exhibit this behavior. Are there any developer of this terminal who actually do some work on Windows and use their own terminal? If so, do you think this application is still usable without proper pasting support?

**Comment by aytey** [comment]
@HongjuneKim:

>  it's unclear why this hasn't been fixed after such a long time

Well, I think it is _very_ clear why it hasn't been merged: @chrisduerr doesn't want to make the Alacritty code worse/bloated/have specific behaviours/etc. just to work around a bug in Microsoft's terminal emulator support.

It is simple as that -- the Alacritty code is correct, and Windows is incorrect, therefore @chrisduerr doesn't want to work around the issue.

When I was still on Windows, I just used a patched version of Alacritty to do what I needed to do.

**Comment by HongjuneKim** [comment]
> When I was still on Windows, I just used a patched version of Alacritty to do what I needed to do.

So, do all the maintainers agree that all Windows users of this application should do this and compile their own version of the terminal from source just to properly use it?

**Comment by mntsx** [comment]
Just in case it helps anyone else: I managed to work around this by running a small PowerShell helper before pasting.

Save the following as **`wpaste.ps1`** in `%APPDATA%\alacritty`:

```ps1
# Normalize clipboard contents and paste into Alacritty via Shift+Insert

Add-Type -AssemblyName System.Windows.Forms

# Normalize line endings: CRLF -> LF, lone CR -> LF
$t = Get-Clipboard -Raw
$t = $t -replace "`r`n","`n" -replace "`r","`n"
Set-Clipboard -Value $t

# Give Alacritty a short moment to keep focus, then send Shift+Insert
Start-Sleep -Milliseconds 50
[System.Windows.Forms.SendKeys]::SendWait("+{INSERT}")
```

Then reference it in your `alacritty.toml`. For example, to make **Ctrl+Right-Click** run the script and paste:

```toml
[mouse]
hide_when_typing = true
bindings = [
  # ...
  { mouse = "Right", mods = "Control",
    command = { program = "powershell.exe",
                args = ["-NoProfile","-STA","-ExecutionPolicy","Bypass",
                        "-Command","$p = Join-Path $env:APPDATA 'alacritty\\wpaste.ps1'; & $p"] } },
]
```

And ensure that Shift+Insert is mapped to paste:

```toml
[keyboard]
bindings = [
  # ...
  { key = "Insert", mods = "Shift", action = "Paste" },
]
```

---

This way, every time you trigger the binding, the clipboard is normalized and pasted into Alacritty.


This are my system specs:

OS: Ubuntu 24.04.3 LTS
Kernel: 5.15.133.1-microsoft-standard-WSL2
Arch: x86_64
Shell: /bin/bash

**Comment by tfriedel** [comment]
@aytey thanks for your branch!
I applied it to the current version of alacritty and built a binary release:

https://github.com/tfriedel/alacritty/releases/tag/v0.16.1-windows-fixes

**Comment by shdxiang** [comment]
I fixed it with Claude—didn’t look closely, but it works fine for now.
https://github.com/shdxiang/alacritty/releases/tag/v0.18.0

**Comment by gary-ruizhang** [comment]
use autohotkey to detect clipboard change and then trim the content seems works for me now.
```
OnClipboardChange(CleanClipboard)

CleanClipboard(Type) {
    if (Type = 1) {
        OnClipboardChange(CleanClipboard, 0)
        
        A_Clipboard := RTrim(A_Clipboard, "`r`n `t")
        
        OnClipboardChange(CleanClipboard, 1)
    }
}
```
