### ISSUE TITLE
Backward search freeze bug

### ISSUE THREAD

**Issue by hissssst** [alacritty/alacritty#4994]
### Desired behaviour

When I use backward search and delete chars in input with backspace, terminal stays responsive

### Actual behaviour

When I use backward search and delete chars in input with backspace, terminal freezes
You can see in file `alacritty.log` (which is aquired with `--print-events` flag) that backspace keyboard event is received. But terminal stays frozen and uresponse, displaying the same data as before pressing backspace

It's worth to notice that my `Shift+Backspace` binging emits unusual escape sequence (you can see it in config)

### System

OS: Linux
Version: `alacritty 0.7.2 (5ac8060b)`
Linux/BSD: `sway 1.6`

### Logs

Keyboard and bindings: [alacritty.log](https://github.com/alacritty/alacritty/files/6352529/alacritty.log)
Config: [alacritty.yml.txt](https://github.com/alacritty/alacritty/files/6352535/alacritty.yml.txt)

**Comment by chrisduerr** [comment]
Could you try the latest master?

**Comment by hissssst** [comment]
@chrisduerr 
I've just cloned the repo, and ran `cargo run` аnd the issue is reproduced

**Comment by chrisduerr** [comment]
Are you starting search from vi mode? What are you searching for? Why is your shift+backspace binding releveant, when you're just pressing backspace?

**Comment by hissssst** [comment]
I don't know why `shift+backspace` is relevant, just thought that it _might be_. 

Here is the recording of the bug on main branch. Leaving backward search with ESC works, but backspace still deletes nothing

https://user-images.githubusercontent.com/37012324/115605782-784bd680-a2d2-11eb-9fb6-37fa72188c54.mp4

**Comment by chrisduerr** [comment]
Oh, so nothing is actually frozen. You're just saying that you press backspace and it doesn't do what you want it to do?

Try with an empty config please.

**Comment by hissssst** [comment]
Yes, that's true. Main branch version does not freeze, but 0.7.2 does.
Empty config with main branch works as desired

**Comment by hissssst** [comment]
@chrisduerr Why is it closed?
Even if the configuration changes the behaviour, it is still a BUG because configuration __does not state the "ignore backspace in backward search" behaviour__

**Comment by chrisduerr** [comment]
>> @chrisduerr Why is it closed?
>
>  Empty config with main branch works as desired

**Comment by hissssst** [comment]
@chrisduerr Okay, I will open another issue

**Comment by chrisduerr** [comment]
I'd strongly advise against that.
