### ISSUE TITLE
Valid configuration breaks not mentioned functionality

### ISSUE THREAD

**Issue by hissssst** [alacritty/alacritty#4996]
### Desired behaviour

Valid configuration does not break functionality of deleting chars from `Backward search` input
Invalid configuration is not accepted by `alacritty`, or accepted partly with errors mentioned

### Actual behaviour

Specified configuration is valid and accepted by `alacritty`, but it breaks functionality of deleting chars from `Backward search` input

### System

OS: Linux
Version: `alacritty 0.8.0-dev (28abb1f)`
Linux/BSD: `sway 1.6`

### Config

Config: [alacritty.yml.txt](https://github.com/alacritty/alacritty/files/6352535/alacritty.yml.txt)

**Comment by hissssst** [comment]
Related to #4994

**Comment by hissssst** [comment]
@chrisduerr Why is this issue closed? It is not resolved in any way
I can create PR to improve error detection mechanism, if you show me the code I should take a look into and the error in configuration

**Comment by hissssst** [comment]
This is actually pretty mean to close unresolved issues without any comments

FYI @jwilm

**Comment by nixpulvis** [comment]
@hissssst it's unlikely pinging people is going to change much here FYI.

I'm not sure I really understand what you are trying to do, but if you change a configuration that "breaks" backspace, then you can expect backspace to be broken. I don't know what else you would expect to happen.

**Comment by hissssst** [comment]
@nixpulvis , The problem is that I didn't change any configuration which "breaks" backspace (I've just double checked it). The only changed line which might be related to it is `backspace+shift`, but I have no idea how it can be related to this issue

Anyway, I think if there is any option which can be misconfigured to break backspace (_there is no such option_), `alacritty` should say something about just like it says about other misconfigurations

I am ready to provide any required information about it, or create the PR myself if you help me with starting point

**Comment by hissssst** [comment]
By the way, configuration is pretty much a default from `0.4.0` version with changed colorscheme, cursor, `$TERM` and `Shift+Backspace` escape code

**Comment by nixpulvis** [comment]
@hissssst perhaps if you can explain what the issue is, and provide a configuration file with the minimal changes to replicate, I could offer some assistance. I'm not going to dig through 435 lines of your config to try and infer what is going on.

I did a very quick grep through however, and I don't see anything about `Shift+Backspace`, so maybe I've just gone blind (it happens), or you have something confused.

It's recommended to not copy around the default configuration anymore, since it's no longer required. This was changed to help prevent issues that will crop up as things change moving forward. Just configure what you need.

**Comment by nixpulvis** [comment]
And by minimal, I don't just mean shorter.

**Comment by chrisduerr** [comment]
The issue is the `Back` binding. This is 100% just a problem with @hissssst and has nothing to do with Alacritty itself.

**Comment by nixpulvis** [comment]
I kinda figured, thanks.

**Comment by hissssst** [comment]
Yeah, @chrisduerr is right about binding. It is actually different escape code for `Back`. I've just tried to comment it and backward search char deletion has worked as desired. 

However, 

* Escape code for `Back` was a default from `0.4.0` version
* I still don't this that different escape code for `Back` should break backward search.

**Comment by hissssst** [comment]
This binding for `Back` is a default from https://github.com/alacritty/alacritty/blob/v0.3.0/alacritty.yml

**Comment by hissssst** [comment]
@nixpulvis @chrisduerr , I think this issue should be reopened, since this problem definetely requires either a deprecation warning or a backward search fix

**Comment by hissssst** [comment]
@nixpulvis @chrisduerr , changed the issue name and description to be more percise

**Comment by nixpulvis** [comment]
@hissssst while I can see where you are coming from, it makes sense that if you change the way the back button works it will change the way it works. What you are really asking for is separate way to configure search bindings from other bindings. This is not currently possible because search is not a proper `mode`.

I have raised this as an issue a few times before, however it's more complex than it might seem, and we never reached a better solution.

**Comment by hissssst** [comment]
@nixpulvis , thank you for this explanation. It is much better than _silently closing issues_.
However, I still think that search should work, because it is implemented in `alacritty`, therefore it knows what escape sequence is bound to `Back` button. Even if you think that this is not a proper solution, this issue can be marked as a `Feature Request` and linked to this task you mentioned about making search a proper mode

**Comment by chrisduerr** [comment]
> This is not currently possible because search is not a proper mode.

This is incorrect. I would appreciate not spreading misinformation.

**Comment by hissssst** [comment]
I am experiencing this issue with `vi` mode search too

**Comment by nixpulvis** [comment]
@chrisduerr Excuse me?

**Comment by hissssst** [comment]
@nixpulvis @chrisduerr Why is this issue still closed?
I think we need at least notification in configuration template that changing escape code for Back breaks some functionality (which actully shouldn't be broken)

**Comment by hissssst** [comment]
@chrisduerr haha, so you've fixed this issue a few years later, but had claimed that this is not a bug. Well done

**Comment by kchibisov** [comment]
If you bind `Back` for all modes it won't work in `Search`, because you bound it. You should exclude `~Search` in mode.
