### ISSUE TITLE
'gl function was not loaded' on startup

### ISSUE THREAD

**Issue by epa** [alacritty/alacritty#4998]
I installed Alacritty from Alacritty-v0.7.2-installer.msi and went to run it the first time with 'Run as administrator'.  It brought up a crash dialogue box saying

---------------------------
Alacritty: Runtime Error
---------------------------
panicked at 'gl function was not loaded', D:\a\alacritty\alacritty\target\release\build\alacritty-1f57ba95d7e851a3\out/gl_bindings.rs:11325:13

Press Ctrl-C to Copy
---------------------------
OK   
---------------------------

Versions:
Windows 10 build 1909
alacritty 0.7.2 (5ac8060)

**Comment by chrisduerr** [comment]
Does your GPU support OpenGL 3.3+?

**Comment by epa** [comment]
Hmm, it's a virtual machine over remote desktop.  So I don't know.

**Comment by epa** [comment]
(I'll check other VMs and other remote desktop connections)

**Comment by chrisduerr** [comment]
Yeah, that's just a Windows virtual machine thing.
