### ISSUE TITLE
For Windows: enable control+insert for copy and shift+insert for paste by default.

### ISSUE THREAD

**Issue by jonathanslenders** [alacritty/alacritty#4999]
Would it be possible to add enable the following key bindings on Windows by default?

- control+insert: copy
- shift+insert: paste

Motivation: these key combinations are already familiar for many windows power users and available system wide by default. Also, other terminal applications (the new windows terminal, the old cmd.exe window, PuTTy, etc...) have these key bindings enabled without any configuration.

I regularly switch back and forth between applications, and having one way to copy/paste that works everywhere without configuration would be great.

**Comment by chrisduerr** [comment]
If this really is a standard binding on Windows, I'd be fine with a PR I suppose. Though obviously only for Windows.

**Comment by jonathanslenders** [comment]
It looks like the following change does work, but it's definitely not yet correct. I don't understand why I have to comment out the insert binding in the default key bindings.

```diff
diff --git a/alacritty/src/config/bindings.rs b/alacritty/src/config/bindings.rs
index 4e7c2fc..a0c6501 100644
--- a/alacritty/src/config/bindings.rs
+++ b/alacritty/src/config/bindings.rs
@@ -612,8 +612,8 @@ pub fn default_key_bindings() -> Vec<KeyBinding> {
         if modifiers_code != 2 {
             bindings.extend(bindings!(
                 KeyBinding;
-                Insert,   mods, ~BindingMode::VI, ~BindingMode::SEARCH;
-                    Action::Esc(format!("\x1b[2;{}~", modifiers_code));
+                //Insert,   mods, ~BindingMode::VI, ~BindingMode::SEARCH;
+                //    Action::Esc(format!("\x1b[2;{}~", modifiers_code));
                 PageUp,   mods, ~BindingMode::VI, ~BindingMode::SEARCH;
                     Action::Esc(format!("\x1b[5;{}~", modifiers_code));
                 PageDown, mods, ~BindingMode::VI, ~BindingMode::SEARCH;
@@ -663,6 +663,7 @@ pub fn platform_key_bindings() -> Vec<KeyBinding> {
     let mut bindings = bindings!(
         KeyBinding;
         Return, ModifiersState::ALT; Action::ToggleFullscreen;
+        Insert, ModifiersState::CTRL; Action::Copy;
     );
     bindings.extend(common_keybindings());
     bindings
     ```

**Comment by chrisduerr** [comment]
Oh yeah, control insert isn't a great idea tbh. I was thinking about control + shift + insert.

These bindings should be forwarded to the terminal, instead of being used by Alacritty.
