### ISSUE TITLE
Font is corrupted and nothing isn't visible clearly.

### ISSUE THREAD

**Issue by billyeatcookies** [alacritty/alacritty#5000]
Font is corrupted and not visible. Using prebuilt portable binary from releases (Alacritty-v0.7.2-portable.exe).

### System

OS: Windows 10
Version: 0.7.2 portable

![image](https://user-images.githubusercontent.com/70792552/115741794-aeaa5400-a3ad-11eb-8398-fd1b2d065ef0.png)

**Comment by chrisduerr** [comment]
This usually happens when your GPU doesn't support OpenGL 3.3+. What GPU do you have?

**Comment by billyeatcookies** [comment]
Ok, got the issue ~~i should be the first to live without a gpu in this century xd~~

thank you for responding :) for reference leaving my adapter details below
![image](https://user-images.githubusercontent.com/70792552/115844720-bf0a0f80-a43d-11eb-9f19-a6781c1336d7.png)
