### ISSUE TITLE
The output of `rustup toolchain install nightly` under win10/powershell 7

### ISSUE THREAD

**Issue by BlueD** [alacritty/alacritty#5001]
Using alacritty:

![Screenshot_2](https://user-images.githubusercontent.com/398352/115826895-27f18780-a43e-11eb-99f6-218e8efa70e1.png)

and using windows terminal:

![Screenshot_3](https://user-images.githubusercontent.com/398352/115826960-3b9cee00-a43e-11eb-81ea-d64bdb0d08ea.png)

### System

OS: Linux/BSD/macOS/Windows
Version: `alacritty --version` output
Linux/BSD: X11/Wayland, DE or Compositor and WM

```
❯ alacritty --version
alacritty 0.7.2 (5ac8060)
```

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by chrisduerr** [comment]
Not an Alacritty issue.
