### ISSUE TITLE
Default Build fails with MacOS Apple Silicon

### ISSUE THREAD

**Issue by VimalMollyn** [alacritty/alacritty#5003]
Hi!

I tried building alacritty from source on my Apple Silicon equipped  mac and ran into an error message from `tic`, while trying to run `make app`.
```
tic: Sorry, -e can't be used without -I or -C
make: *** [Alacritty.app] Error 1
```

I modified the Makefile to skip the tic command and rebuilt it with no issues. 

Furthermore, `infocmp alactritty` shows:
```
#	Reconstructed via infocmp from file: /Users/paan/miniforge3/share/terminfo/61/alacritty
alacritty|alacritty terminal emulator,
	am, bce, ccc, hs, mc5i, mir, msgr, npc, xenl,
	colors#0x100, cols#80, it#8, lines#24, pairs#0x10000,
	acsc=``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
        .
        .
        Some more stuff
        .
        .
	u8=\E[?%[;0123456789]c, u9=\E[c, vpa=\E[%i%p1%dd,
```

I'm not sure if this is expected behaviour, can someone help me out?

### System

OS: macOS
Version: `alacritty --version` output:
```alacritty 0.8.0-dev (c688adc)```

**Comment by chrisduerr** [comment]
Sounds like you have a tic version installed that isn't compatible. I'd assume you're running Big Sur?

Can you share the full output of `tic --help` please?

**Comment by VimalMollyn** [comment]
Yup, I'm on Big Sur 11.2

`tic --help` seems to return an `tic: illegal option -- -` error. 
`tic -V` returns `ncurses 6.2.20200212`

Hope that helps!

**Comment by chrisduerr** [comment]
> Hope that helps!

It doesn't. That's definitely not the standard `tic` shipped with `ncurses`.

What does the manpage say?

**Comment by VimalMollyn** [comment]
Here's a screenshot of the manpage:
![image](https://user-images.githubusercontent.com/62076354/115979620-8e90b580-a5a4-11eb-925c-8845262f8bee.png)

The bottom of the manpage mentions that this is indeed not the stock SVr4 tic implementation. 

![image](https://user-images.githubusercontent.com/62076354/115979705-065ee000-a5a5-11eb-833e-48d102dfe425.png)

**Comment by erithmetic** [comment]
FWIW I was able to build it on my M1 MacBook Air:

macOS version: 11.2.2 (20D80)

```
tic -V
ncurses 5.7.20081102

uname -a
Darwin rocinante.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64

rustc --version
rustc 1.51.0 (2fd73fabe 2021-03-23)
```

**Comment by chrisduerr** [comment]
@VimalMollyn Does your version match 11.2.2? You just said 11.2, is that 11.2.0? Maybe updating will help.

Though your `tic` version seems hire, but it doesn't match the actual `ncurses` tic version which strikes me as odd.

One thing you should definitely try is executing the `tic` command manually. Just to make sure that your path isn't completely messed up.

**Comment by VimalMollyn** [comment]
I'm on MacOS 11.2, Build 20D64 (not 11.2.0 or 11.2.2). My next update is for MacOS 11.3 though. 
I did try running the tic command on it's own and I get the same error.

What's your ncurses version @chrisduerr ? I'm surprised that @erithmetic 's ncurses version is 5.7, the latest one is [6.2](https://invisible-island.net/ncurses/announce-6.2.html), which seems to have different flags.

**Comment by chrisduerr** [comment]
I'm running `6.2.20200212`, but the proper one on Linux of course. On my macOS machine I also only have 5.7 installed and I just updated macOS. So I'd probably check why you seem to have a different tic installed.

**Comment by VimalMollyn** [comment]
Alright, I've found the solution. You have to include the -C flag with tic, and it seems to work.
```Bash
@tic -C -xe alacritty,alacritty-direct -o $(APP_EXTRAS_DIR) $(TERMINFO)
```

Can one of you guys check on your systems if this flag would work on other tic versions? I can't seem to find the proper Linux man page for tic.

**Comment by chrisduerr** [comment]
That doesn't even remotely do the same thing. Please install a `tic` version which is compatible, or modify the makefile accordingly.

**Comment by VimalMollyn** [comment]
Yes, that flag seems to be forcing translation to the required format. I'm new to this project though, so I'm not sure what the intent was from the original command. Could you maybe explain what the original command (without the -C flag) is supposed to be doing and why the new command is so different? I'd love to help out!
