### ISSUE TITLE
Background opacity failure PICOM

### ISSUE THREAD

**Issue by khandaniyal** [alacritty/alacritty#5006]
I am trying to use **picom** with **alacritty** to have transparency. I am using **Arch Linux** with **Qtile**. 
My **alacritty.yml** is untouched but I uncommented the **background _opacity** and my **picom.conf** is default.

**Comment by chrisduerr** [comment]
What exactly did you set `background_opacity` to?

**Comment by khandaniyal** [comment]
> What exactly did you set `background_opacity` to?

I just fixed it. I reinstalled **Alacritty** and its is working fine. My **background_opacity = 0.9**.
