### ISSUE TITLE
Alacritty doesn't work with plasma shortcuts option

### ISSUE THREAD

**Issue by stkw0** [alacritty/alacritty#5008]
I tried to add a global shortcut to launch alacritty on plasma desktop but it didn't work. After trying a couple of things I discovered that renaming **Alacritty.desktop** to **alacritty.desktop** fixed the issue. I don't know the reason of this behavior, maybe it's a bug on plasma side, but as it's a very small change will it be worth it to rename that file¿? 

### System

OS: Linux
Version: alacritty 0.7.2
Linux/BSD: Plasma with

**Comment by chrisduerr** [comment]
Other DEs seem to do just fine, so I think this is probably something plasma should fix. At least I'm not aware of any part of the spec explicitly stating that the name cannot be different than the executable or something like that.

**Comment by nixpulvis** [comment]
This was changed in #3425 to make the class and desktop filename strings match.
