### ISSUE TITLE
Alacritty fails to launch with "Entry Point Not Found" error

### ISSUE THREAD

**Issue by huettenhain** [alacritty/alacritty#5020]
### System

OS: Windows
Version: Release Version 0.7.2

### Bug Report

Alacritty fails to launch and displays the following error:

![image](https://user-images.githubusercontent.com/11869704/116430292-ff56fc80-a846-11eb-82fa-bade0c70a8f8.png)

Unfortunately, I am unable to provide any additional logs, because the executable consistently crashes.

**Comment by nixpulvis** [comment]
@huettenhain can you provide the full version of Windows. I feel like it's not compatible, since https://docs.microsoft.com/en-us/windows/console/closepseudoconsole lists Windows 10 October 2018 Update (version 1809) as the minimum supported client.

**Comment by chrisduerr** [comment]
You need to update your operating system.
