### ISSUE TITLE
skim has some serious delays compared to iterm2

### ISSUE THREAD

**Issue by vigsterkr** [alacritty/alacritty#5021]
first of all kudos to all the work done in this project! it's an amazing tool!
i've just faced today and interesting issues when using alacritty with [skim](https://github.com/lotabout/skim):
for some reason there's a significant delay showing skim results as well as showing the previews compared to the very same environment (shell etc) when using skim via iTerm2.
i'll try to further debug what actually is happening as i really couldn't see a reason why this could happen (namely why the difference)... note currently i'm using alacritty with rosetta2. i'll try to compile an arm version of alacritty to see whether maybe this is the reason and get back to you. but thought i'll add this one here maybe somebody faced this as well.

### steps to reproduce
1. start alacritty
2. start `sk`
(right away here's a significant delay of showing results from skim)
3. move around the cursor (make sure you've allowed `--preview` for skim) and wait for the preview to pop-up. again compared to iTerm2 there's a significant delay in alacritty to show the preview of the file.

### System

OS: macOS
Version: alacritty 0.7.2 (5ac8060)

**Comment by chrisduerr** [comment]
Can you reproduce this outside of `skim`? If not, I don't see why this would be an Alacritty issue. Sounds to me like skim might just be doing something funky.

**Comment by vigsterkr** [comment]
noup

**Comment by vigsterkr** [comment]
@chrisduerr i mean sorry, i've thought about this quite a while should i fire this issue under skim, but to be honest *everything* is the same (shell etc) except using alacritty vs iTerm2, so i'm pretty sure that there's something wrong in alacritty. 

note as an additional information i've compiled alacritty locally for native arm, and the delay got halved, but it still does exists, i.e. there's still a noticeable difference in response time compare to iTerm2

**Comment by chrisduerr** [comment]
Try `TERM=xterm-256color skim`.

**Comment by vigsterkr** [comment]
@chrisduerr it's already `xterm-256color`

**Comment by chrisduerr** [comment]
Well then you should try `TERM=alacritty`.

**Comment by vigsterkr** [comment]
@chrisduerr :boom: panick from `skim` when unwrapping https://github.com/lotabout/skim/blob/master/src/lib.rs#L309-L317

```
`Result::unwrap()` on an `Err` value: IOError(Custom { kind: Other, error: TerminfoEntryNotFound })'
```

**Comment by chrisduerr** [comment]
You should install the `alacritty` terminfo, that's the only one officially supported.

**Comment by vigsterkr** [comment]
ta! done, unfortunately the behaviour is the same; in other words no difference between setting TERM to `xterm-256color` or `alacritty`. honestly i dont have any other idea just to maybe add `tracing` to skim&alacritty to check where/why things get stuck. if you have any more ideas please dont hesitate to share i'm more than happy to debug it.

again thnx for all the effort put into this project!

**Comment by chrisduerr** [comment]
How did you install Alacritty?

**Comment by vigsterkr** [comment]
first i've simply used the version available as a package in homebrew: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/alacritty.rb

but as said above since there's only x86 build available there i've just built my own version locally by checking out ~HEAD of master of this repo.

**Comment by chrisduerr** [comment]
It works just fine for me. I recommend checking your environment for differences specifically things like locale.

Unless you have evidence of the opposite, I don't think there's anything Alacritty can do about this.

**Comment by vigsterkr** [comment]
@chrisduerr lol man, this is a bit harsh to just close it like this, but it's up to you....

**Comment by vigsterkr** [comment]
@chrisduerr recommend to read a bit about in this: https://opensource.guide/

still kudos for all your efforts!

**Comment by vigsterkr** [comment]
> @chrisduerr recommend to read a bit about in this: https://opensource.guide/
> 
> still kudos for all your efforts!

quite obviously you could learn some things from it ;)

**Comment by nixpulvis** [comment]
Couldn't we all...

**Comment by nixpulvis** [comment]
@vigsterkr on a more serious note; having now also installed Skim and tested it, I can only assume that this issue was closed because there is nothing obviously wrong here. Given the lack of reproducibility, the issue report indicates nothing to make us think there's reason for further action on our end.

If you *do* end up finding something actually wrong, we would of course like to know about it, but I suspect if you were to start from a clean setup, you would not be having this issue either.

**Comment by vigsterkr** [comment]
@nixpulvis it's a very clean setup. i even deliberately dropped all my local changes to alacritty's config. i've gone through all the *possible* differences between the 2 workflows and so far i've found 0. of course there's definitely a difference, otherwise this wouldn't be happening, so i'm digging further....

i've offered all my available resources to figure out why this actually happening, because i've just tested the very same workflow with a 2 other terminal emulators namely native Terminal.app from apple and simple xterm. none of them behaves like alacritty. but since i'm very ❤️ alacritty i'll try to drill down why and where things could go wrong... but based on the fact that 3 terminal emulators are acting quite differently to alacritty it's highly likely that there's somewhere something going sideways in alacritty itself...

i do understand that having random issues like this could be annoying for you, but i presume that the aim of this project (as any other open-source project) is on the end of the day to have users. moreover, have contributors who actually might be able to help out to fix these very minuscule issues, that at first sight might not be at all important from the 'big perspective' but quite possibly have other side-effects, that on the end of the day causes not intended ('negative') user experience.

**Comment by nixpulvis** [comment]
@vigsterkr I suggest you compare against another platform as well. I'm suspicious of you macOS environment personally.

**Comment by vigsterkr** [comment]
Yeah will do although i guess it’d be good to have the app working/functioning the same amazing way over all platforms 🙃
