### ISSUE TITLE
Macos latets with Source Code Fonts issue

### ISSUE THREAD

**Issue by jvillasante** [alacritty/alacritty#5028]
Hello,

After the latest MacOS upgrade (11.3) and with the latest `Source Code Pro` fonts it looks like the font is not rendering correctly when using a light background, it does work when using a dark background.

Here's a link to my config: https://github.com/jvillasante/dotfiles/blob/master/Home/alacritty/alacritty.yml
Here's a screenshot which shows that nothing is visible, I'm running an `ls -al` command on `zsh` shell.
![Screen Shot 2021-04-30 at 8 24 26 AM](https://user-images.githubusercontent.com/1139125/116695201-41d72100-a98e-11eb-971d-511b667291e6.png)

### System

OS: MacOS
Version: `alacritty 0.7.2 (5ac8060)`

**Comment by chrisduerr** [comment]
Could you share what it looks like using the default config with just the font changed? Especially with SGR color escapes visible please.

**Comment by jvillasante** [comment]
> Should that output be colored? Please test some SGR sequences to see if output coloring is working.

Looks like it's not working correctly, I tried this script:
```
#!/bin/bash

printf "          "
for b in 0 1 2 3 4 5 6 7; do printf "  4${b}m "; done
echo
for f in "" 30 31 32 33 34 35 36 37; do
    for s in "" "1;"; do
        printf "%4sm" "${s}${f}"
        printf " \033[%sm%s\033[0m" "$s$f" "gYw "
        for b in 0 1 2 3 4 5 6 7; do
            printf " \033[4%s;%sm%s\033[0m" "$b" "$s$f" " gYw "
        done
        echo
     done
done
```

Left `iTerm` right `alacritty` with light theme:
![light](https://user-images.githubusercontent.com/1139125/116743814-774c3080-a9c7-11eb-9e7e-a1ea0de80f8e.png)

Left `iTerm` right `alacritty` with dark theme:
![dark](https://user-images.githubusercontent.com/1139125/116743856-829f5c00-a9c7-11eb-9fdc-b7579a01d89f.png)
