### ISSUE TITLE
Test `indexing_above_inner_len` fails on release

### ISSUE THREAD

**Issue by Diegovsky** [alacritty/alacritty#5041]
### System

OS: Arch Linux 
Version: master 68bb16274025984dceca95662cb748792fa1297f
Linux/BSD: Don't think it's relevant, but wayland (gnome)
Rust Info:
  - cargo 1.52.0-nightly (90691f2bf 2021-03-16) (tried with `+stable` and it also failed)
  - rustc 1.53.0-nightly (07e0e2ec2 2021-03-24)

### Logs
Crash:
`cargo test -p alacritty_terminal --lib --release indexing_above_inner_len` 
```
    Finished release [optimized + debuginfo] target(s) in 0.02s
     Running unittests (target/release/deps/alacritty_terminal-301c76baf62c5a2d)

running 1 test
test grid::storage::tests::indexing_above_inner_len ... FAILED

failures:

---- grid::storage::tests::indexing_above_inner_len stdout ----
note: test did not panic as expected

failures:
    grid::storage::tests::indexing_above_inner_len

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 111 filtered out; finished in 0.00s

error: test failed, to rerun pass '-p alacritty_terminal --lib'
```
Debug:
`cargo test -p alacritty_terminal --lib indexing_above_inner_len`
```
    Finished test [unoptimized + debuginfo] target(s) in 0.02s
     Running unittests (target/debug/deps/alacritty_terminal-9b7d0aa723bd7d26)

running 1 test
test grid::storage::tests::indexing_above_inner_len ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 111 filtered out; finished in 0.00s

```
Edit: I suppose this panic should only happen on debug (hence the use of `debug_assert`), but that makes the test fail on release.

**Comment by chrisduerr** [comment]
This has been a known issue for a while, I just haven't gotten around to fixing it yet. But since it caused our 0.8.0-rc1 release builds to fail today, I'll probably get on it later.
