### ISSUE TITLE
Is window resizing through command line and vim possible?

### ISSUE THREAD

**Issue by prizelk** [alacritty/alacritty#5049]
### System

OS: macOS
Version: `alacritty --version` output
alacritty 0.7.2 (5ac8060)

I was wondering if resizing the app window would be possible through vim or command line. 

<img width="364" alt="Screen Shot 2564-05-02 at 18 09 22" src="https://user-images.githubusercontent.com/69815889/116811073-87077880-ab71-11eb-8aac-dd96218358f5.png">
For example, I have simple vim commands that allow me to resize the window/terminal. Furthermore 
set lines=x columns=y allows me to change the terminal size when I enter vim which is very nice.
This works well in iterm and the native terminal but bugs out the alacritty's interface heavily:
<img width="1081" alt="Screen Shot 2564-05-02 at 18 25 12" src="https://user-images.githubusercontent.com/69815889/116811472-bdde8e00-ab73-11eb-8964-c294af4fee74.png">
Here I resized my vim window to be a smaller editor but alacritty fails to notice this.

Command-line resizing in Xterm and iterm is possible through "control sequences" as shown here.
https://apple.stackexchange.com/questions/33736/can-a-terminal-window-be-resized-with-a-terminal-command/52054

I use these methods a lot in my workflow because presetting to a larger or smaller terminal than necessary clutters my screen. Furthermore, I can adjust the size of my editor/splits accurately with short commands when I am on a different workflow. The current workaround is to drag resize with mouse whenever I change my workflow which is a nuisance.
I understand that this feature may not exist in alacritty but I would still appreciate any workarounds. 

Thanks!

**Comment by chrisduerr** [comment]
Escape sequences to resize the terminal are intentionally not supported and never will be in the future.

I'd recommend doing this through your window manager, though I don't know if the default macOS window manager is capable of providing that functionality by itself.
