### ISSUE TITLE
Is it possible to exit with non-zero exit code?

### ISSUE THREAD

**Issue by abstractlyZach** [alacritty/alacritty#5055]
I'm trying to get `alacritty` to exit with a non-zero exit code from a failed command. I've read through the `man` page, the `README`, and the config file, but haven't been able to find anything. Is there an option somewhere that I could use to do this?

# Expectation
Alacritty should exit with the failed command's exit code.

## Interactive terminal
expected:
```
➜ alacritty -e 'sh'

# in new terminal
➜ exit 130

# back in the original terminal
➜ echo $?
130
```

actual:
```
➜ alacritty -e 'sh'

# in new terminal
➜ exit 130

# back in the original terminal
➜ echo $?
130
```

## Non-interactive terminal
expected:
```
➜ alacritty -e 'sh' -c 'exit 1'
➜ echo $?
1
```

actual:
```
➜ alacritty -e 'sh' -c 'exit 1'
➜ echo $?
0
```

## Extra context
I confirmed that `sh` uses an exit code successfully, but I'm not really sure whose responsibility that is. Maybe it's `alacritty`'s or `zsh`'s? Or maybe the parent process's in-general?
```
➜ sh
sh-5.1$ exit 1
exit

➜ echo $?
1

➜ sh -c "exit 5"

➜ echo $?
5
```

### System

OS: Manjaro Linux
Version: `0.7.2`
Linux/BSD: Wayland/Sway

**Comment by chrisduerr** [comment]
Alacritty's exit code solely represents its ability to successfully execute the program, it does not forward the shell's exit code. This is working exactly as intended.

**Comment by abstractlyZach** [comment]
Cool, that makes sense.

Do you have any recommendations for what I could use to create this behavior? I'm thinking maybe a named pipe, but that seems like there's got to be a better way to send an exit code

**Comment by chrisduerr** [comment]
I'm not sure what you're trying to do.

**Comment by abstractlyZach** [comment]
I'm looking for a way to get an exit code from an alacritty process's shell exit code

I have 2 scripts, one which can exit non-zero and one that calls that script

```sh
# ~/bin/myscript

echo "oops failed" >&2
exit 7
```
```sh
# ~/bin/run-script-in-terminal

alacritty -e sh -c myscript
```
Then when I run the latter script, I'd like it to have a return code that matches the return code of `myscript`
```sh
➜ run-script-in-terminal

➜ echo $?
7
```
