### ISSUE TITLE
Wrong colors are displayed

### ISSUE THREAD

**Issue by sujay1844** [alacritty/alacritty#5056]
The colors specified in the `~/.config/alacritty/alacritty.yml` are not the colors displayed in the terminal.
![20210505_15h02m51s_grim](https://user-images.githubusercontent.com/68642484/117122009-fddf8400-adb2-11eb-8441-3bacb493a43e.png)

My alacritty config file: [alacritty.yml](https://github.com/sujay1844/dotfiles/blob/main/alacritty/alacritty.yml)

For example: You can clearly see that red in my config file is `#cc0000`. But if you color pick the screenshot you see it's `#cc6666` and so on.

Which setting am I missing here??

### System

OS: Arch Linux x86_64
Version: alacritty 0.7.2 (5ac8060b)
Linux/BSD: Wayland, Sway

**Comment by chrisduerr** [comment]
I recommend deleting the comments and looking at the hierarchy of your configuration file. You're defining colors in the `fonts` section.

**Comment by sujay1844** [comment]
Yep thanks got it @chrisduerr
