### ISSUE TITLE
Correlation between window resizing with +/- and font size?

### ISSUE THREAD

**Issue by GNOMES** [alacritty/alacritty#5059]
OS: Arch Linux Gnome Shell / MacOS Catalina
Version: `alacritty --version` 0.7.2
----------------

I have been playing with various monospace fonts as of late, and been tweaking font sizes and offsets like mad.

Is there an approximate correlation between between multiple Ctrl + -/+ to the next approximate size in the config's font setting? 

Example: I have been really digging Ubunto Mono as of late, and find font size 14 pretty large. If I set it to size 12, some of the characters are a bit squished. Keeping the font at 14, and shrinking the window twice (2x Ctrl + `-`) is perfect. 

Is there an easy font size to window ratio calculation, or is there a simple shrink overall window size setting I could use instead?

**Comment by chrisduerr** [comment]
The bindings increment/decrement at a step size of `0.5`. Also these bindings should not affect window size, they only alter the font size.
