### ISSUE TITLE
Unrecoverable Error

### ISSUE THREAD

**Issue by djtsorrell** [alacritty/alacritty#5061]
After an update today, I cannot open Alacritty. I get the following error:

### Logs
```
[ERROR] [alacritty] Alacritty encountered an unrecoverable error:

Error creating GL context; Received multiple errors. Errors: `[OsError("eglInitialize failed"), OsError("GL context creation failed")]`
```

Font/Terminal size: 14.0
Keyboard and bindings: 
```
- { key: V, mods: Control|Shift, action: Paste }
- { key: C, mods: Control|Shift, action: Copy }
- { key: Key0, mods: Control, action: ResetFontSize }
- { key: Equals, mods: Control, action: IncreaseFontSize }
- { key: Plus, mods: Control, action: IncreaseFontSize }
- { key: Underline, mods: Control, action: DecreaseFontSize }
- { key: Minus, mods: Control, action: DecreaseFontSize }
- { key: N, mods: Control, action: SpawnNewInstance }
```

### System

OS: Linux Pop_OS 20.04 LTS (Kernel: 5.11.0-7614-generic)
Version: alacritty 0.8.0-rc3
Linux X11, GNOME, Mutter.

**Comment by chrisduerr** [comment]
Does your GPU support OpenGl 3.3+?

**Comment by djtsorrell** [comment]
I'm not sure actually. I can tell you that the GPU is an NVIDIA GeForce GTX 1050 Mobile.
Also, I've just restarted my computer after GNOME completely froze on me. Since rebooting, Alacritty is working again. Perhaps this is just a freak glitch with GNOME.

**Comment by chrisduerr** [comment]
Your driver was likely updated. Some graphics drivers require a restart before allowing new applications to be launched.
