### ISSUE TITLE
[Feature request] man 5 alacritty entry for configuration file

### ISSUE THREAD

**Issue by kiuKisas** [alacritty/alacritty#5062]
It could be nice to have a section 5 in man regarding alacritty, to explain how configuration file works. Like we can do, for example, with sway through `man 5 sway`

**Comment by chrisduerr** [comment]
I've considered this myself before and while I generally like the idea of having everything easily digestible in a manpage, the problem with this is that it introduced duplication of work. Of course it might be possible to write a tool which automatically converts from one to another, but that's also work that first has to be performed before it's ready.

So while it might be nice to have a manpage that makes reading about the configuration format simple, getting there is probably not worth it.

**Comment by kiuKisas** [comment]
Mind if I give a try when I'll have time ? The current source of truth for the config file is here: https://github.com/alacritty/alacritty/blob/master/alacritty.yml , correct ?

**Comment by chrisduerr** [comment]
Correct, though let me be clear here: I have little faith in anyone else producing something acceptable here. So I suspect you trying to get something mediocre going is just a waste of time.

**Comment by kiuKisas** [comment]
Don't mind if you never accept such a PR, at least I would have try (If I  do). If you have some criteria in mind, you should probably tell them so everyone win some times.

**Comment by FlorianFranzen** [comment]
I would just propose that the man page refers to the default config and where it can be found.

**Comment by kchibisov** [comment]
Done in bd4906722a1a026b01f06c94c33b13ff63a7e044
