### ISSUE TITLE
Config error: history: exceeded maximum scrolling history

### ISSUE THREAD

**Issue by ifohancroft** [alacritty/alacritty#5066]
### System

OS: Linux
Version: alacritty 0.9.0-dev
Linux/BSD: X11, MATE with picom compositor

If I set Alacritty's scrollback to more lines than my bash history, I get the error Config error: history: exceeded maximum scrolling history

I shouldn't. There is a reason I set my terminal's scrollback line number to be higher than my bash history. Imagine working on something and you suddenly need a command from history you don't remember, so you execute history, then you keep working but you want to scrollback to your work before executing `history`. If your scrollback is as big as the bash history, you can't keep in the scrollback anything more except the history command's output.

**Comment by ifohancroft** [comment]
P.S. The weird thing is that I thought I had set my bash history to 10K lines and my Alacritty scrollback to 20K, but it turned out I had set the Alacritty scrollback to 22K lines. When changed to 20K, I no longer get the error. Still, even at 22K I shouldn't get this error. This shouldn't be a problem.

**Comment by mark2185** [comment]
Well that's odd, the max limit should be `100 000`. 

Can you paste the exact error you get, e.g.
```
exceeded maximum scrolling history (22000/100000)
```

**Comment by ifohancroft** [comment]
@mark2185 Thank you and sorry. I was dumb! I wanted to set 20K, so adding an extra 2, I thought I was setting it to 22K, when in-fact I was setting it to 220K because I added the extra 2, as opposed to replacing the 0 with a 2.
Also, I just re-read the error message. No idea why I thought there was a relationship between Alacritty's scrolling history and bash's history.

**Comment by correabuscar** [comment]
Why is the limit 100_000 though? I wanted 15 million.

**Comment by kchibisov** [comment]
Recompile with 15 million, and don't complain about memory usage latter.

**Comment by KaeLL** [comment]
@kchibisov anything else other than `MAX_SCROLLBACK_LINES` that should be changed for that to work? Just to make sure.

**Comment by kchibisov** [comment]
@KaeLL no.
