### ISSUE TITLE
Crash when selecting text while selecting rapid text output

### ISSUE THREAD

**Issue by bradfitz** [alacritty/alacritty#5067]
Crash while selecting moving text.

### System

OS: macOS (Big Sur 11.2.3)
Version: alacritty 0.8.0-rc3 (706f476)

### Logs

```
$ ./Alacritty.app/Contents/MacOS/alacritty 
thread 'main' panicked at 'index out of bounds: the len is 10046 but the index is 10236', /Users/runner/work/alacritty/alacritty/alacritty_terminal/src/term/mod.rs:395:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Video

I ran `find . | perl -npe 's/\w/x/g'` and selected text while it spewed. It very reliably crashes:

https://user-images.githubusercontent.com/2621/117462177-3aba9080-af03-11eb-8099-a70a725a4c32.mov

**Comment by chrisduerr** [comment]
Great find, thanks for testing the RC. I can reproduce, should probably be an easy fix.
