### ISSUE TITLE
Your github site does not make it clear where the Linux binaries are

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [alacritty/alacritty#5070]
Your README - or at least the github frontpage - says there are precompiled binaries on the releases page. Yet, that page seems to have no Linux binaries.

**Comment by chrisduerr** [comment]
> Alacritty can be installed by using various package managers on Linux, BSD, macOS and Windows.

Linux -> Package Managers

> Prebuilt binaries for macOS and Windows can also be downloaded from the GitHub releases page.

Only macOS and Windows, no mention of Linux here.

> For everyone else, the detailed instructions to install Alacritty can be found here.

Always an option if you don't use a distro which packages Alacritty already.

**Comment by LinuxOnTheDesktop** [comment]
Ah. But the README says that only after seeming to promise Linux binaries. For, near the top of the README, one reads both that the program runs on Linux and that, 'Precompiled binaries are available from the GitHub releases page.'

So: the start of the README  _misleads the reader_ into believing that Linux binaries are available.

**Comment by chrisduerr** [comment]
Well, the GitHub releases page doesn't provide any binaries and I'm confident most Linux users are competent enough to put 1 and 1 together and just try their package manager.

**Comment by LinuxOnTheDesktop** [comment]
The point is that the text misleads. Put a little more fully: some people will, reasonably, read until they seem to have been told what they need to know; and then it will turn out that they have been given a false impression.

The solution is easy. To wit: change, 'Precompiled binaries are available from the GitHub releases page' to something like, ''Precompiled binaries are available from the GitHub releases page (except for Linux - please see below).'

**Comment by chrisduerr** [comment]
Feel free to send a PR to just remove that sentence the install section is just below anyways. I personally don't think it's a big deal, I doubt a lot of people are that easily confused.
