### ISSUE TITLE
"panicked at 'Unable to spawn shell" on Windows

### ISSUE THREAD

**Issue by hrqmonteiro** [alacritty/alacritty#5072]
### System

OS: Windows
Version: `alacritty 0.7.2 (5ac8060)`

### Logs

```
---------------------------
Alacritty: Runtime Error
---------------------------
panicked at 'Unable to spawn shell: The system cannot find the file specified. (os error 2)', alacritty_terminal\src\tty\windows\conpty.rs:174:5

Press Ctrl-C to Copy
---------------------------
OK   
---------------------------
```

![image](https://user-images.githubusercontent.com/17055027/117495758-6f066f00-af4c-11eb-8c06-b7b771a8081c.png)

When i try to open i get this window error. And this only appears if i try to use a config file. If i erase the `alacritty` folder from my config folder, the error vanishes. So i have to use the default configuration to open it.

**Comment by chrisduerr** [comment]
Did you change your shell?

**Comment by chrisduerr** [comment]
Make sure the default powershell is accessible in your path please.
