### ISSUE TITLE
Alacritty renders some emoji incorrectly

### ISSUE THREAD

**Issue by codevbus** [alacritty/alacritty#5073]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Ubuntu 20.10/macOS 11.3.1
Version: Linux: `alacritty 0.8.0-dev (a5e2ccd)` | OSX `0.7.2`
Linux/BSD: X11 Gnome 3

### Logs

Font/Terminal size: Linux: Hack Nerd Font Mono 14 Fullscreen | OSX Hack Nerd Font 14 Fullscreen

### Reproduce
`$ echo  ☁️`:

results in:
![Screen Shot 2021-05-07 at 3 03 38 PM](https://user-images.githubusercontent.com/1672773/117496830-9279eb80-af45-11eb-9bb1-e76a4aef436b.png)

Some emoji seem to render as expected, while others like the cloud seem to be a limited, mono-color drawing of some kind. This occurs on multiple Alacritty versions across different OSes. I have verified the font/emoji renders correctly on iTerm2.

**Comment by chrisduerr** [comment]
Just a matter of font fallback, so working as intended.
