### ISSUE TITLE
Incorrect cursor placement after Vi/Search mode match

### ISSUE THREAD

**Issue by jxlambda** [alacritty/alacritty#5074]
### System

OS: OpenBSD
Version: 0.9.0-dev (8f4b752a)
Compositor/Window Manager/Desktop Environment: X11 running i3

### Behavior

After entering Vi/Search mode and performing a search, the cursor is placed incorrectly - a line above the match. This seems to happen due to the buffer being shifted a line up, when the search prompt occupies the last line. The cursors position accounts for the line being there.

**Comment by chrisduerr** [comment]
Can't reproduce this, there have been a couple vi mode/search fixes that might have solved it.

If you can still reproduce it, please let me know with concrete repro instructions.

**Comment by jxlambda** [comment]
Hey, @chrisduerr!

Just tried reproducing and found that this doesn't happen when running in a regular shell session, but does appear to trigger when the search is performed in a shell running in a tmux session (I didn't check with screen(1) as I don't have it configured nor installed at this time).

To reproduce:
- Start a tmux session
- Populate the shell session with some text (I used `man -c printf`, which copies the output of the formatted manual to stdout)
- Enter Vi mode and pop open the search bar
- Search for arbitrary text that can be found in the just output document
- Hit Return to close the search bar

In my particular case, I searched for the phrase `echo`, which in the printf(1) manual on OpenBSD can be found in the `SEE MORE` section. After the search bar closes, the page readjusts back to the correct height (now that the search bar isn't there) but the cursor remains on the original line.

Now... I'm not sure who's to blame for this, the terminal itself, or some wonkiness introduced by ncurses as used by `tmux`.

Hope this clarified it, and if you need any more help, feel free to shoot me a message. :)

**Comment by chrisduerr** [comment]
Not much we can do in that case, since alt-screen applications can arbitrarily redraw their screen without our knowledge.

So the content is moved away below our cursor, not the other way around. If you want to have a vi mode that keeps track of tmux's panes and scrolling and everything, that needs to be done through tmux.
