### ISSUE TITLE
Dynamic Title doesn't work unless TERM=xterm-256color

### ISSUE THREAD

**Issue by txtsd** [alacritty/alacritty#5078]
When I set `dynamic_title: true`, the title still shows as `Alacritty` instead of the command or prompt.
When I set `TERM: xterm-256color` it works as expected. I'd like to keep using `TERM: alacritty` and also have a dynamic title.
Can this be done?

### System

OS: Arch Linux
Version: alacritty 0.7.2 (5ac8060b)
Linux/BSD: X11, Openbox, no DE

**Comment by chrisduerr** [comment]
That's a problem with the application setting the title. They're probably checking your term name.

**Comment by txtsd** [comment]
It would help if you discussed it before closing the issue.

Where am I supposed to look to debug this? I run Openbox, no DE.

By application do you mean the cli program I'm running, or Alacritty itself? I should be able to see the title as the prompt as the title even when I have no cli program running.
