### ISSUE TITLE
WOW kitty is better alacritty extremely in support

### ISSUE THREAD

**Issue by silencercore** [alacritty/alacritty#5083]
Hello
I love RUST !!
and subset of rust like alacritty but 
my issues just close close close
my problem is this
![2021-05-09_00-19](https://user-images.githubusercontent.com/83878382/117551595-2dfd8000-b05c-11eb-8f00-9e86b8874860.png)
you see alacritty in top vs kitty that show DOT wrong

**Comment by chrisduerr** [comment]
Then use Kitty? And please stop spamming GitHub projects with useless bug reports.

**Comment by PalanixYT** [comment]
That's really weird of you. Text is clearly not rendered correctly and you tell people to just use kitty?

**Comment by AsafFisher** [comment]
Reopen this.
