### ISSUE TITLE
x11 embed will not work with window id

### ISSUE THREAD

**Issue by simonhughcom** [alacritty/alacritty#5090]
### System

OS: Linux
Version: 0.7.2
Using X11 BSPWM

Alacritty will embed just fine when I use `tabbed alacritty --embed`
however, due to a script I am working on I have to embed alacritty using a window id such as `alacritty --embed 0x000000` after launching tabbed, but no matter what alacritty will not embed into tabbed.

**Comment by chrisduerr** [comment]
The parameter passed to Alacritty is expected to be a decimal, not hexadecimal. Though `0x0` is somewhat suspicious.

**Comment by simonhughcom** [comment]
Thank you, can't believe I missed that. The zeros are just a placeholder I used in this PR, they are not actual numbers.
