### ISSUE TITLE
Get Konsole like selection selection colors

### ISSUE THREAD

**Issue by Deshdeepak1** [alacritty/alacritty#5092]
### System

OS: Linux
Version: 0.7.2
Linux: X11, picom and AwesomeWM

How to get konsole like selection colors?

The breeze colorscheme I got, didn't had the selection part .

Is there any way to get such colors?

![Screenshot_20210510_081339](https://user-images.githubusercontent.com/36617998/117601235-6c359500-b16b-11eb-974b-28c280671053.png)

**Comment by chrisduerr** [comment]
There is no way. This seems like some strange combination of inversion and fixed color, which I have no interest in supporting in Alacritty. It seems somewhat janky.

**Comment by Deshdeepak1** [comment]
What is the closest I can get to this?

**Comment by chrisduerr** [comment]
Either inversion or using a fixed color. Whatever you prefer.
