### ISSUE TITLE
notty

### ISSUE THREAD

**Issue by withoutboats** [alacritty/alacritty#51]
Hey @jwilm, we've talked a bit in the past about alacritty implementing the notty protocol. It seems like alacritty is really coming together, so I wanted to reach out and discuss that possibility.

From my perspective, I'm much more interested in implementing a framework on top of notty on the 'far side' of the TTY than I am interested in implementing a terminal emulator, and notty has stalled for that reason. So a collaboration with alacritty would be strongly in my interest. :-)

What follows are some notes on notty to get the conversation started.

### Basics of the notty protocol

A notty escape code is much simpler to parse than an ANSI escape code. It has these parts:

1. An initializer sequence. Currently it's `Escape, Underscore, Left Square Bracket`. Its important that it begins `Escape, Underscore` because this is a reserved space for custom messages, and correctly behaving ANSI terminals will ignore notty escape codes, rather than potentially printing garbage. The left square bracket is to reduce likelyhood of collision with terminal-specific custom commands (ideally it would someday be reserved by a standard for notty).
2. An op code. In the current protocol this is a hex encoded number, but its not particularly important. Every command has an op code assigned to it.
3. A sequence of standardized arguments that each op code takes, which have a defined binary format. This would be something like a motion ("left 2 cells", "right to edge of screen", etc) or a text style ("bold", "rgb 0xff7744").
4. A sequence of base-64'd binary data arguments (currently this is sequential but it could easily be keyed instead). Its important that these be base64'd to avoid escaping issues & also because the TTY is often set to munge `\n` into `\r\n`. A command like "draw an image" takes base64'd image data.
5. The terminating character, which is specified (by ANSI) as `U+009C`. This needs to be the terminal character to have ANSI terminals ignore this message correctly.

The exact binary representation of sections 2 - 4 are not particularly important in my opinion, we just have to pick something (currently its a mix of hex, b64, and punctuation characters).

## Subdividing the character grid

The most interesting thing from a performance perspective in notty is the ability to subdivide the screen into separate grids, so that a program like tmux isn't constantly redrawing the entire grid redundantly.

Ultimately, the result is a tree, the leaves of which are grids. Branches are one of two things:

1. A "split", with 2 children, dividing a section of the screen along a single axis horizontally or vertically.
2. A "ring", with N > 1 children, all of which fill the same space of the grid.

The result of this is that every grid will always be rectangular, and you never have to deal with irregularly shaped grids. Here's the data structures used to represent this in notty right now (a little more complex than what I showed at RustConf):

```rust
struct ScreenSection<T> {
    region: Region // 4 u32s representing the rows/columns this section takes up
    ring: Ring<Panel<T>>,
}

enum Panel<T> {
     Grid(T),
     Split { left: ScreenSection<T>, right: ScreenSection<T> },
}

// Implements a "rotate_left" "rotate_right" interface
struct Ring<T> {
    top: T,
    rest: Option<VecDeque<T>>,
}
```

### Sandboxing

One problem with developing the complexity of the terminal is that it has no way to isolate different programs from one another - they just write over each other's output. I haven't implemented it, but I'd like the terminal to be able to sandbox processes.

Every sandbox (including the 'root' sandbox that the entire terminal would be in by default) has a session key associated with it. The process can always request the session key for the active sandbox. Just prior to forking, a process can set up a new sandbox in one section of the screen. Unless you have the session key for an outer sandbox, all commands manipulating grids would interact within that sandbox.

## Other features of notty

The general thrust of notty is to put more complexity in the terminal layer, so that that logic can be re-used by different terminal applications, instead of everyone having a bespoke implementation of subdividing the screen (for example). To a certain extent, notty also extends the capabilities of the terminal to implement behavior it fundamentally couldn't before.

If you're interested in pursuing this seriously, we can work together to find a balance of features that we're both excited about.

Here are some of the features notty implements or is supposed to implement right now:

* Images & media on the grid
* Collapsible sections of the grid
* Tooltips/dropdown (intended for auto complete)
* Proper support for all input (key releases, control character key presses, mouse support, etc)
* "syntactic styles" - the ability for the controlling process to say "style this like a comment/keyword/etc," so users can have one stylesheet that is applied consistently to all their syntax highlighting.
* Auto-formating hierarchical data with collapsible sections and such (so the terminal receives e.g. a JSON blob and pretty prints it automatically).

Some of these ideas could be implemented at a higher level than the terminal though. The basic idea is to extend the terminal to be a full-featured "text environment," like what one would expect from the graphical component of a modern IDE, so that an ecosystem of "IDE components" can develop within it, like UNIX with more modern UI capabilitilies.

**Comment by jwilm** [comment]
I'll make time soon to respond to this in detail. For now, I just wanted to thank you for posting this and respond to one part of your post.

> If you're interested in pursuing this seriously, we can work together to find a balance of features that we're both excited about.

So much yes! Alacritty's focus on performant rendering and parsing is only half the battle. `notty`'s work is the real solution to crappy terminal experiences.

**Comment by tbodt** [comment]
@jwilm how's this going?

**Comment by nixpulvis** [comment]
FWIW, the ability to have the terminal be aware of different processes output would be incredibly useful to me, along with any performance improvements this might give us.

I'm not really an expert of terminals though, so I'm not sure what the downsides of this are exactly. Would this require a compatibility layer for converting ANSI into notty controls? Would there be any other major program facing changes?

**Comment by cosmojg** [comment]
@jwilm Any updates?

**Comment by Moelf** [comment]
possible we start a bountysource for this?

**Comment by chrisduerr** [comment]
Currently I don't see much benefit in adding this.

**Comment by Moelf** [comment]
it allows remote working on cluster nodes much easier. say you have an analysis script that produces a few plots in the end, you can (iTerm2) `imcat` them as a array to view them remotely (like `ls`) without either `rsync` back and have to use mouse even.

Or say you have a lot of images/pdfs you just want to look at a small grid preview to find the filename you want to rm or keep

**Comment by chrisduerr** [comment]
I don't see how that is related to this issue.

**Comment by Moelf** [comment]
this issue is pointed to by a lot of 'displaying images in terminal' requests, which is why this is relevant.

**Comment by chrisduerr** [comment]
This issue does not track support for adding image support. You should probably look at other issues like #910.

**Comment by Moelf** [comment]
while sixel can provide minimal feature, it is real clunky irl last time I tried it in some other terminal, and the real juice in this post is the following:
> A sequence of base-64'd binary data arguments.....

this is basically what iTerm2 does, and better yet:

> Images & media on the grid

which are both from OP in this issue.

**Comment by chrisduerr** [comment]
> this is basically what iTerm2 does

This is what every escape sequence does that takes payloads as argument. It's not some special notty magic.

This is about supporting a completely different terminal protocol, not about implementing one of the existing image protocols (and there are like a million different variations of those already). Trying to "start a bountysource" to implement this just to get image support makes no sense.

**Comment by CommanderGL** [comment]
any updates

**Comment by withoutboats** [comment]
Closing this issue because notty was never finished and its not something I'm ever going to work on again.
