### ISSUE TITLE
Can't move lines in visual mode in vim

### ISSUE THREAD

**Issue by CODESOLE** [alacritty/alacritty#5105]
### System

OS: Ubuntu 20.10
Version:  alacritty 0.7.2
Linux/BSD: X11/GNOME 3.38.3

My problem is when I try to move visually selected lines up or down, it does not move, for this feature I use this plugin;
https://github.com/tpope/vim-unimpaired

and in my vimrc file, I have this keybinds ALT + Up/Down arrow keys;
```console
" move line(s) of code
nmap <A-Up> [e
nmap <A-Down> ]e
vmap <A-Up> [egv
vmap <A-Down> ]egv
```

and here is gnome-terminal that works great;

![issue](https://user-images.githubusercontent.com/22984206/117813625-fb29d680-b26b-11eb-986a-4c646ddc393a.gif)

**Comment by chrisduerr** [comment]
Try with `TERM=xterm-256color`.
