### ISSUE TITLE
How to map TrueColor value to ANSI escape code in Alacritty?

### ISSUE THREAD

**Issue by winston0410** [alacritty/alacritty#5108]
Is it possible to map TrueColor value to ANSI escape code in Alacritty? I am trying to do so in order to use TrueColor value for `$LS_COLORS`, but I cannot find the documentation I need. Just a wild guess, are `colors` in `alacritty.yml` used for mapping ANSI code?

### System

OS: macOS
Version: alacritty 0.7.2 (5ac8060)

**Comment by chrisduerr** [comment]
Alacritty does not do any truecolor to ansi escape mapping. Only the opposite.
