### ISSUE TITLE
Allow specifying the font delta step size in the config

### ISSUE THREAD

**Issue by 4censord** [alacritty/alacritty#5109]
> I have a small suggestion, which is to allow specifying the font delta step size in the config, or perhaps making it `0.5` in case that's too much work, since I often work in half step differences because my monitor is HiDPI.

_Originally posted by @norcalli in https://github.com/alacritty/alacritty/issues/625#issuecomment-335960284_

I would really like this feature.
On my system, because of HiDPI, with the current `FONT_SIZE_STEP = 0.5` I need an unresonable amount of `CRTL-+` to increase the fontsize enough to show my terminal to someone else.

**Comment by 4censord** [comment]
I have already tried implementing this myself, but have hit the roadblock of not being able to include a f32 in the font config struct because it doesn't implement `std::Eq`, but my rust foo is to weak to work aroung

**Comment by chrisduerr** [comment]
I have no interest in supporting this upstream.
