### ISSUE TITLE
Performance issue with unicode

### ISSUE THREAD

**Issue by trashhalo** [alacritty/alacritty#511]
If you hook alacritty to a profiler and `cat /dev/urandom`. Asking the width of the character happens to be the most expensive operation. I think we should consider adding a cache for this because its not like unicode widths change wildly in fact they are hardcoded inside the library.

Every time we ask the width of character unicode width is doing a binary search over the vector they have for a matching character.

----
Follow up. When piping out unicode characters in the lower sets `base64 /dev/urandom` this hot spot never appears because it doesnt cause unicode-code width to do a binary search. I suspect this performance issue is low priority.

**Comment by chrisduerr** [comment]
This is probably related to the terrible performance in the unicode benchmark in vtebench.
See https://github.com/jwilm/vtebench/pull/6 for more details.

**Comment by matthiaskrgr** [comment]
I saw very poor performance when `cat` ing this file https://github.com/rust-lang/regex/blob/master/regex-syntax/src/unicode_tables/property_bool.rs
It's probably related

**Comment by kchibisov** [comment]
This issue should be dramatically improved on Linux/BSD however I've opened a new one about macOS here #3254, since it's likely has similar problems.
