### ISSUE TITLE
Allow padding to be toggled dynamically

### ISSUE THREAD

**Issue by ElArtista** [alacritty/alacritty#5112]
Can we somehow allow padding to be toggled or set dynamically?
Either from a hotkey or from an ansi escape sequence would do the job.

This would allow users to have a seamless experience when entering fullscreen mode, while preserving the padding when in window mode

**Comment by chrisduerr** [comment]
This is already possible through the live config reload.

**Comment by ElArtista** [comment]
Well, altering a program's behavior on runtime without modifying the persistent configuration is useful too
Why was this rejected without any discussion?
