### ISSUE TITLE
How can i remove this strange space on the bottom of the terminal window?

### ISSUE THREAD

**Issue by hrqmonteiro** [alacritty/alacritty#5119]
### System

OS: Void Linux
Version: `0.8.0` 
Linux: X11, AwesomeWM

If i open the terminal in a standard tiled window, if has this strange space on the very bottom of the page, and it doesn't look okay:

![2021-05-13_12-32](https://user-images.githubusercontent.com/17055027/118148781-47e5ec80-b3e7-11eb-9f28-73de0c9af720.png)
![2021-05-13_12-32_1](https://user-images.githubusercontent.com/17055027/118148791-49171980-b3e7-11eb-91c1-35ba91605e61.png)

But on a smaller window (or in a fullscreen mode), this space disappears:

![2021-05-13_12-33](https://user-images.githubusercontent.com/17055027/118148889-5fbd7080-b3e7-11eb-9ac4-be6f1268ed30.png)

And i know is an alacritty thing, not my wm setting cause i spent hours trying to figure it out. It's an alacritty thing cause if i set the background color to another one, it changes it.

Can i set this space never to appear? Even on a standard window size? It's bugging the hell out of me.

**Comment by chrisduerr** [comment]
Cells have a fixed size, so when your terminal's size isn't evenly divisible it will result in padding at the bottom. You can use `dynamic_padding` if you instead prefer this to be spread evenly.

**Comment by hrqmonteiro** [comment]
> Cells have a fixed size, so when your terminal's size isn't evenly divisible it will result in padding at the bottom. You can use `dynamic_padding` if you instead prefer this to be spread evenly.

It's still appearing, just slightly a little smaller than before

![2021-05-13_13-52](https://user-images.githubusercontent.com/17055027/118158637-6d2c2800-b3f2-11eb-81e6-29e106bd50ff.png)
