### ISSUE TITLE
Allow configuration options to be toggled/changed dynamically on the current terminal instance

### ISSUE THREAD

**Issue by ElArtista** [alacritty/alacritty#5120]
Extension of #5112:

It would be nice if we could allow users to toggle or set dynamically options of alacritty for the CURRENT instance he is interacting without modifying the alacritty and relying on the live config reload (that affects all instances). Either from a hotkey/action or from a custom ansi escape sequence would do the job.

Currently similar functionality exists for changing the font size (zooming in/out) by using ctrl + plus/minus.
Allowing some other options like padding to be changed/toggled could be useful too.

**Comment by chrisduerr** [comment]
I don't really see much benefit in overriding config options generically per-instance when for most of them it really doesn't make any sense.

**Comment by mike-lloyd03** [comment]
I know this is already marked wontfix, but being able to toggle opacity with a hotkey would be really helpful.

**Comment by reportaman** [comment]
+1 Yes it would be very helpful to toggle opacity with a hotkey!
