### ISSUE TITLE
Alacritty Colors

### ISSUE THREAD

**Issue by vshelton** [alacritty/alacritty#5122]
According to: https://github.com/alacritty/alacritty/wiki/Color-schemes, it is possible
to define multiple color schemes for alacritty.  The alacritty.yml file should reflect this
by defining all the color codes  and choosing one of the defined schemes by default.  I will generate an appropriate patch for the alacritty.yml file if you want me to.

### System

OS: Arch linux
Version: alacritty 0.9.0-dev
Linux/BSD: X11 KDE

**Comment by chrisduerr** [comment]
> I will generate an appropriate patch for the alacritty.yml file if you want me to.

I don't want you to. I have no interest in this.

**Comment by vshelton** [comment]
Thank you for your feedback (and alacritty).  Please close the Feature
Request then.

  - Vin
