### ISSUE TITLE
Dynamic Embedded configurations

### ISSUE THREAD

**Issue by AsafFisher** [alacritty/alacritty#5123]
Hello! I want to add an option to change the default configuration of the alacrity binary without the need to recompile the whole project (:

For this I have created this library:
https://github.com/AsafFisher/elfredo

It works for now only for Linux, but I plan on making it work for windows too.

Is it fine that I will make a PR that adds this feature?

**Comment by chrisduerr** [comment]
> Is it fine that I will make a PR that adds this feature?

No, that's what configuration files are for.

**Comment by AsafFisher** [comment]
Yes but if you want to change the default value you need to recompile... I don't want to recompile and I cannot put an extra file on the system. Why do I need to be dependent on a separate file that has no what so ever connection to the echo system of the app?

Configuration files are not contradicting to this feature.
