### ISSUE TITLE
Support standard geometry parameter

### ISSUE THREAD

**Issue by khaytsus** [alacritty/alacritty#5124]
I have been looking at alacritty after it being recommended to me as drawing faster in tmux, irc clients, etc, so I decided to give it a try.  I have a bunch of term windows I scatter around on my desktops and was pretty surprised that there's no geometry option in alacritty so I can't do this.  They just all wind up wherever the DE puts them.  Yes there are workarounds, but please, can you add the standard geometry parameter like almost every other X app supports?  Thank you!

### System

OS: Linux (Fedora 32) using XFCE on X11
Version: alacritty 0.7.2

**Comment by chrisduerr** [comment]
Placing the window through the `--options` parameter is already possible. Though I strongly recommend letting your WM deal with this kind of stuff.

**Comment by khaytsus** [comment]
Oh yes, this is much better than --geometry...

alacritty -o window.position.x=1000 -o window.position.y=1000 -o window.dimensions.columns=20 -o window.dimensions.lines=15

Oh well.  Works.
