### ISSUE TITLE
[WARN] See log at /tmp/Alacritty-47855.log ($ALACRATTY_LOG)

### ISSUE THREAD

**Issue by Firefox2892** [alacritty/alacritty#5125]
everytime i open alacritty theres a yellow popup at the bottom of it and it says:[WARN] See log at /tmp/Alacritty-47855.log ($ALACRATTY_LOG) Config warning: url is deprecated; use 'hints' section instead

running Pop! OS(BSPWM)

i am new to linux

**Comment by chrisduerr** [comment]
Follow the instructions.

**Comment by Firefox2892** [comment]
> Follow the instructions.
everytime i try to use vim to open the log file the log file is just empty
