### ISSUE TITLE
Pipe with -e

### ISSUE THREAD

**Issue by sourav-majumdar-math** [alacritty/alacritty#5130]
I am trying to execute `alacritty --hold -e curl --no-progress-meter wttr.in | less -r`, what happens is that two alacritty windows open one with the `curl` output and the other with a blank `less` page. What may be happening is that the entire command upto curl is piping to less? I was hoping for the behavior when I just run `curl --no-progress-meter wttr.in | less -r` which returns a `less` page with the output of `curl`. wttr.in is a weather site.

# System

OS: Ubuntu 20.04
Alacritty Version: alacritty 0.9.0-dev

**Comment by chrisduerr** [comment]
Spawn a shell, not curl directly.

**Comment by sourav-majumdar-math** [comment]
This `alacritty --hold -e curl --no-progress-meter wttr.in` doesn't cause any problems. It is only when piping to `less` that creates a problem.

**Comment by chrisduerr** [comment]
Yeah... because that requires a shell.
