### ISSUE TITLE
Control key combinations ignored in terminal programmes 

### ISSUE THREAD

**Issue by ldesousa** [alacritty/alacritty#5138]
### System

OS: Ubuntu 20.04
Version: 0.7.2
Other: i3 4.17, vim 8.1, midnight commander 4.8.

### Issue description

The following key combinations do not work (i.e. produce no effect) within a vim session: Ctrl+PgUp, Ctrl+PgDown, Ctrl+End and Ctrl+Home. Strangely, others like Ctrl+V or Ctrl+G do function. All these key combinations produce the desired effect with termite.

Also in midnight commander, navigation shortcuts like Ctrl+PgUp and Ctrl+PgDown do not function (they do with terminte). Looks like alacritty is not passing these key combinations to running programmes.

There are no error messages to report.

**Comment by chrisduerr** [comment]
This might be a vim issue, have you tried neovim? Also have you tried `TERM=xterm-256color`?

**Comment by ldesousa** [comment]
@chrisduerr As I explained above, these shortcuts function as expected within a vim session in termite. 

Ctrl shortcuts are also not functioning in midnight commander. I will update the original description.

**Comment by chrisduerr** [comment]
Please answer my questions.

**Comment by ldesousa** [comment]
I installed neovim and could verify that in that programme Ctrl shortcuts do function as expected.

Setting up the `TERM` variable has no effect either for vim or for midnight commander.

**Comment by chrisduerr** [comment]
> Setting up the TERM variable has no effect either for vim or for midnight commander.

How did you set it up?

**Comment by ldesousa** [comment]
`TERM=xterm-256color`, as you suggested earlier.

**Comment by chrisduerr** [comment]
Just that? That doesn't do anything...

**Comment by ldesousa** [comment]
@chrisduerr Then what does something? Do you want me to initiate the variable with other contents?

**Comment by chrisduerr** [comment]
You have to either do `export TERM=xterm-256color` or `TERM=xterm256color vim`.

**Comment by ldesousa** [comment]
Not sure were you are trying to get at. I already stated I set up the TERM variable as you describe. It has no effect on the problems I initially reported. The Ctrl key combinations are not functional with either `vim` or `mc`.

```
$ export TERM=xterm-256color
$ echo $TERM
xterm-256color
$ vim
```

**Comment by chrisduerr** [comment]
Closing issue since it seems to work fine in neovim and vim/midnight commander are both known to be mediocre actors at best.

**Comment by ldesousa** [comment]
This issue went away after upgrading to vim 8.2. The `modifyOtherKeys` feature allowing vim to recognise these key combinations was only recently introduced. Detail at [StackExchange](https://vi.stackexchange.com/a/31344/26408).

With midnight commander should be a similar problem.
