### ISSUE TITLE
Crash on windows wsl

### ISSUE THREAD

**Issue by PrudhviBoggavarapu** [alacritty/alacritty#5140]
Crashes on wsl 

said this 

Alacritty: Runtime Error
---------------------------
panicked at 'Unable to spawn shell: The directory name is invalid. (os error 267)', alacritty_terminal\src\tty\windows\conpty.rs:174:5

Press Ctrl-C to Copy

To stop this error in window, a regualr terminal needs to be opened then Alacritty

the config is :

background_opacity: .95

working_directory: "\\\\wsl$\\Ubuntu\\home\\karma"
title: Karma's Linux
shell:
  program: "C:\\Windows\\System32\\wsl.exe"
key_bindings:
  - { key: N, mods: Control, action: SpawnNewInstance }
  - { key: W, mods: Control, action: Quit }

**Comment by chrisduerr** [comment]
Your working directory is not valid during startup.
