### ISSUE TITLE
Cannot find relevant part of Alacritty.yml

### ISSUE THREAD

**Issue by carlca** [alacritty/alacritty#5142]
OS: macOS
Version: 0.8.0.0rc6

![Screenshot 2021-05-17 at 14 46 52](https://user-images.githubusercontent.com/260612/118499400-ccee4000-b71e-11eb-8c8e-c8e03cc79176.png)

I've just upgraded to v0.8.0.0rc6 and I'm gettng this alert when I start up. It's not serious but I would like to get rid of it. I've looked in Alacritty.yml, but the warning is slightly ambiguous about what needs to be changed.

I've succeeded in snuffing out previous alerts with commenting out relevant sections of Alacritty.yml, but not this time!

Please advise 😉

**Comment by chrisduerr** [comment]
The `url` section is deprecated, please use the `hints` section instead. Your current config probably has a `url` section and the latest config documents a `hints` section. Not sure what more there is to say.

**Comment by carlca** [comment]
I just needed it confirmed that "url is deprecated" meant that the entire section called url is deprecated. I've deleted it and all is well. Thanks!

**Comment by jackloomen** [comment]
For those of us who had launcher: None
What are we supposed to do now? The url hint is enabled by default and how do you even disable hints?

hints: None doesn't work. hints: false does either.
hints: enabled: false or None doesn't work either.

**Comment by chrisduerr** [comment]
Hints is an array, just do `hints: []`.

**Comment by jackloomen** [comment]
> Hints is an array, just do `hints: []`.

Thanks. It doesn't work with hints but works with enabled:

**Comment by chrisduerr** [comment]
Oh yeah, sorry I didn't actually look at the config file. It's indeed the enabled hints that has to be an empty array.

**Comment by carlca** [comment]
@jackloomen  Where, exactly, do I  need to put `hints: []`? I don't have an `enabled:` section.

**Comment by jackloomen** [comment]
> @jackloomen Where, exactly, do I need to put `hints: []`? I don't have an `enabled:` section.

In the config file I just added:

```
hints:
  enabled: []
```
