### ISSUE TITLE
Black rectangle in each new instance

### ISSUE THREAD

**Issue by blinry** [alacritty/alacritty#5143]
### System

OS: Arch Linux, X11 + i3
Version: 0.7.2 (5ac8060b)

### Description

When I start a new instance, *and* have an external 4K monitor attached, after about one second, it clears the top left corner, replacing it with a black region, which appears to be exactly 800x600 pixels large. After refreshing the content once, that symptom goes away and never reappears. But it happens for each instance I start.

This problem does not occur when I don't have that external monitor activated.

How can I help you debug this? :O

### Screenshot

![alacritty-bug](https://user-images.githubusercontent.com/81277/118531787-80b6f600-b746-11eb-8980-b3a75041dec4.png)

**Comment by chrisduerr** [comment]
How are you testing this? If the glyphs are on that boundary, do they get cut in half? Or does it only clear "full" glyphs?

**Comment by blinry** [comment]
Yeah, they get cut in half (that's also visible in the screenshot, if you look closely). :O

To demonstrate the behavior in the screenshot, I ran `alacritty -e vim file` on a file containing a lot of `#` characters. :) But I get the same effect when I launch `alacritty -e mutt` or just open an instance containing a shell.

**Comment by chrisduerr** [comment]
That sounds really GPU-drivery. Since Alacritty itself isn't really capable of just clearing the screen partially.

Which GPU/driver do you use?

**Comment by blinry** [comment]
Ah, good point! It's an Intel chip, using the modesetting driver:

```
$ lspci -k | grep -A3 "VGA"
00:02.0 VGA compatible controller: Intel Corporation Skylake GT2 [HD Graphics 520] (rev 07)
	Subsystem: Lenovo Device 2233
	Kernel driver in use: i915
	Kernel modules: i915
```

**Comment by chrisduerr** [comment]
Is this a recent change, or has this always been an issue?

**Comment by blinry** [comment]
Just started using Alacritty a week ago, can't tell, sorry! :)

**Comment by blinry** [comment]
Notes: 

- If I run picom with the modesetting driver, this behavior is still there.
- If I use the xf86-video-intel driver, it's not! (DRI3, I think)

**Comment by chrisduerr** [comment]
> If I use the xf86-video-intel driver, it's not! (DRI3, I think)

Sounds like I was correct and it is a driver bug then. So nothing Alacritty can do about it unfortunately.
