### ISSUE TITLE
Emojis are huge

### ISSUE THREAD

**Issue by guihkx** [alacritty/alacritty#5146]
### System

OS: Arch Linux
Version: alacritty 0.7.2 (5ac8060b)
Display server: X11
DE: GNOME Shell
Compositor/WM: mutter

### Logs
`alacritty -vv` (no config file): [alacritty-log.txt](https://gist.github.com/guihkx/a8012f9050b39290eaffeb3626bdafd6/raw/5bdd827082ecb9486cc5612172fa40dd3861e50d/alacritty-log.txt)

### Demo

**Alacritty**

![Peek 2021-05-18 01-26](https://user-images.githubusercontent.com/626206/118590201-5a11b300-b778-11eb-92be-566b124c0b2e.gif)

**GNOME Terminal**

![Peek 2021-05-18 01-27](https://user-images.githubusercontent.com/626206/118590209-5bdb7680-b778-11eb-894d-6aa21905172c.gif)

### Other

`~/.config/fontconfig/conf.d/50-noto-color-emoji.conf`:

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <match target="scan">
        <test name="family">
            <string>Noto Color Emoji</string>
        </test>
        <edit name="scalable" mode="assign">
            <bool>true</bool>
        </edit>
        <edit name="pixelsize" mode="assign">
            <double>18</double>
        </edit>
    </match>
    <match>
        <test name="family">
            <string>sans-serif</string>
        </test>
        <edit name="family" mode="prepend" binding="weak">
            <string>Noto Color Emoji</string>
        </edit>
    </match>
    <match>
        <test name="family">
            <string>serif</string>
        </test>
        <edit name="family" mode="prepend" binding="weak">
            <string>Noto Color Emoji</string>
        </edit>
    </match>
    <match>
        <test name="family">
            <string>monospace</string>
        </test>
        <edit name="family" mode="prepend" binding="weak">
            <string>Noto Color Emoji</string>
        </edit>
    </match>
    <match>
        <test name="family">
            <string>Apple Color Emoji</string>
        </test>
        <edit name="family" mode="prepend" binding="strong">
            <string>Noto Color Emoji</string>
        </edit>
    </match>
</fontconfig>
```

`emojis.txt`: [emojis.txt](https://gist.github.com/guihkx/6e09d69901be11c583b60fc1035d8a1a/raw/01ecd47824dd7d44a628c39533aa78fda9c8dca2/emojis.txt)

**Comment by chrisduerr** [comment]
You're explicitly requesting this:

```
        <edit name="pixelsize" mode="assign">
            <double>18</double>
        </edit>
```

**Comment by guihkx** [comment]
That's what I get for copying stuff off the internet without actually reading it. 🤡 

I've removed the section you mentioned from the conf file, but I still have a few emojis not showing up properly, but at this point I'm already satisfied with the outcome 😃

![Screenshot from 2021-05-18 02-24-29](https://user-images.githubusercontent.com/626206/118594669-30f52080-b780-11eb-888f-75ce0aad74c3.png)

Sorry for wasting your time!
