### ISSUE TITLE
URL Regex Does Not Detect 2 URLs on the Same Line

### ISSUE THREAD

**Issue by Rayqan** [alacritty/alacritty#5148]
For example after running the command `echo https://example.com https://test.com` alacritty will only provide the options to click example.com and test.com is not recognized as a URL.

**Comment by chrisduerr** [comment]
Which version do you run? This was a temporary issue in one of the 0.8.0 RCs but since has been resolved.

**Comment by Rayqan** [comment]
Version was indeed the problem, apologies for the erroneous issue.
