### ISSUE TITLE
Failed to open input method: PotentialInputMethods

### ISSUE THREAD

**Issue by sshaikh** [alacritty/alacritty#5153]
Seems similar to https://github.com/alacritty/alacritty/issues/1574. ~I suspect it has something to do with my remote usage.~

Checking locales:

```
> locale
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=

> cat /etc/locale.conf
LANG=en_GB.UTF-8
```

### System

OS: Arch Linux 5.12.5-arch1-1
Version: alacritty 0.7.2 (5ac8060b)
Linux/BSD: X11, i3 via xrdp

### Logs
```
RUST_BACKTRACE=full alacritty -vvv
thread 'main' panicked at 'Failed to open input method: PotentialInputMethods {
    xmodifiers: None,
    fallbacks: [
        PotentialInputMethod {
            name: "@im=local",
            successful: Some(
                false,
            ),
        },
        PotentialInputMethod {
            name: "@im=",
            successful: Some(
                false,
            ),
        },
    ],
    _xim_servers: Err(
        GetPropertyError(
            TypeMismatch(
                0,
            ),
        ),
    ),
}', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/x11/mod.rs:134:17
stack backtrace:
   0:     0x55a5e8cd66d0 - <unknown>
   1:     0x55a5e8badeac - <unknown>
   2:     0x55a5e8cd5f31 - <unknown>
   3:     0x55a5e8cd5895 - <unknown>
   4:     0x55a5e8cd4f5b - <unknown>
   5:     0x55a5e8a8c92a - <unknown>
   6:     0x55a5e8a8c8fc - <unknown>
   7:     0x55a5e89f15f1 - <unknown>
   8:     0x55a5e8a4415b - <unknown>
   9:     0x55a5e8affa67 - <unknown>
  10:     0x55a5e8b34e13 - <unknown>
  11:     0x55a5e8aa0203 - <unknown>
  12:     0x55a5e8b34a85 - <unknown>
  13:     0x7fe909f6cb25 - __libc_start_main
  14:     0x55a5e89f106e - <unknown>
  15:                0x0 - <unknown>
```

**Comment by sshaikh** [comment]
Oh and FWIW this had been working until recently, but I'm not sure what's changed.

**Comment by sshaikh** [comment]
Okay - I'm now seeing this locally too, which rules out xrdp. Will report to Arch.

**Comment by chrisduerr** [comment]
If it worked previously, I'd assume you've tested previous Alacritty versions?

**Comment by sshaikh** [comment]
I've tried the latest git, with no change in result.

I've not tried previous versions, but only since I know I've only ever had this version installed.

I'll try different versions further today.

**Comment by chrisduerr** [comment]
So you're saying system updates unrelated to Alacritty broke this for you then? I feel like xrdp is probably to blame here.

**Comment by sshaikh** [comment]
Possibly, but as per my comment above, I'm now seeing it on a local machine (ie not via rdp).

I do share configuration everywhere so it may be something there. I've already tried with no config, so one of the things I'll be trying is alacrity on a fresh machine.

**Comment by chrisduerr** [comment]
Oh, I totally missed that, thanks. You didn't recently update your system without rebooting, right? It's not much of a "solution", but definitely worth a shot.

**Comment by sshaikh** [comment]
I've rebooted a few times after first seeing this issue - I've also tried downgrading most recently upgraded packages to no avail, which led me to checking configuration.

**Comment by chrisduerr** [comment]
What keyboard layout do you use? Just normal US? Do you have any IME installed on your system?

I use X11/i3 myself, with US layout and no IME installed. That definitely shouldn't be happening on such a system.

**Comment by sshaikh** [comment]
My locale and hw keyboard are both UK layout.

I'm not sure what you mean by IME, which I presume means I don't have one!

Thinking back, I was receiving "your resolution is bogus, expect trouble" messages locally before it stopped working altogether. Could that be a clue?

**Comment by chrisduerr** [comment]
What is your resolution? Do you use anything strange like xinerama? If you use external monitors (not a laptap), it might be worth it to try another one if available.

**Comment by sshaikh** [comment]
I'm running on a single 4k monitor via HDMI and haven't done anything over the automatic set up of resolution etc. Unfortunately I don't have another hdmi monitor handy.

I'm hoping that the complaint about resolution is a red herring though (since this error is complaining about input), but who knows?

**Comment by chrisduerr** [comment]
> I'm hoping that the complaint about resolution is a red herring though (since this error is complaining about input), but who knows?

Hmm, that's what I'd like to believe too.

Just to clarify, the output of `locale` is what you get in a terminal before launching Alacritty from it, right? Just to make sure that's the exact locale being inherited. 

Could you also try `XMODIFIERS=@im=none alacritty`?

**Comment by sshaikh** [comment]
No change with `XMODIFIERS=@im=none alacritty`.

Yes, the output of `locale` is what I see when running the command in the same terminal window as `alacritty`.

FYI, still see the same issue with v0.8.0.

**Comment by chrisduerr** [comment]
It's strange, because one of these should definitely work by default on X. You say you have no IME installed, could you try installing ibus, executing it, then launch Alacritty with `XMODIFIERS=@im=ibus alacritty`? That way the `@im=ibus` method should be guaranteed to exist.

**Comment by sshaikh** [comment]
```
> XMODIFIERS=@im=ibus alacritty
thread 'main' panicked at 'Failed to open input method: PotentialInputMethods {
    xmodifiers: Some(
        PotentialInputMethod {
            name: "@im=ibus",
            successful: Some(
                false,
            ),
        },
    ),
    fallbacks: [
        PotentialInputMethod {
            name: "@im=local",
            successful: Some(
                false,
            ),
        },
        PotentialInputMethod {
            name: "@im=",
            successful: Some(
                false,
            ),
        },
    ],
    _xim_servers: Err(
        GetPropertyError(
            TypeMismatch(
                0,
            ),
        ),
    ),
}', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/x11/mod.rs:134:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by chrisduerr** [comment]
Are you confident you've installed and started ibus correctly? That seems strange.

**Comment by sshaikh** [comment]
Not confident, no :). I just followed the guidance on the Arch wiki:

https://wiki.archlinux.org/title/IBus

So `ibus-daemon -drx` followed by various combinations of `XMODIFIERS=@im=ibus GTK_IM_MODULE=ibus QT_IM_MODULE=ibus alacritty`

**Comment by chrisduerr** [comment]
I'm not sure about `ibus-daemon`, but I know that running `ibus-setup` works (gotta keep the window open iirc).

Just `XMODIFIERS` should be enough.

**Comment by sshaikh** [comment]
Okay - also tried with the ibust setup window open. No change in response.

**Comment by chrisduerr** [comment]
Any system-wide changes you've made related to keyboard/input/locale after installing? I'd assume you generated your locale as documented in the wiki?

**Comment by sshaikh** [comment]
Not that I'm aware of. I have just built a minimal system and it seems to be working with that, so it must be my usual setup that is as fault. I'll attempt to narrow it down.

**Comment by sshaikh** [comment]
Cracked it. It was of course due to user error. I had an overzealous `NoExtract` in my `pacman.conf`:

```
NoExtract = usr/share/X11/locale/* !usr/share/X11/locale/compose.dir !usr/share/X11/locale/locale* !usr/share/X11/locale/en_GB.UTF-8/*
```

Removing this and reinstalling (`pacman -Qqn | pacman -S -`) repaired my system.

That said, I've had this directive for a long time so something must have changed recently.

Thanks for the time and attention.
