### ISSUE TITLE
[feature request] resolve anchors recursively from imports

### ISSUE THREAD

**Issue by l3nn4rt** [alacritty/alacritty#5157]
I find useful to keep `~/.config/alacritty/alacritty.yml` to the bare minimum (since all options are well documented in `/usr/share/doc/alacritty/example/alacritty.yml`).
In this sense, having all color schemes defined in the main config file results in cluttering this one.

So, my current solution is to use `import` with file `~/.config/alacritty/colors.yml`, where all color schemes are defined.
But the key `colors` must be in there too, since external anchors won't be resolved recursively in the main config file.
When now I change `colors: *...`, I also have to `touch` main config file for the changes to be applied.

If anchors could be resolved recursively from imports (at least once), we could leave color schemes in a separate file, and adjust `colors` in the main config file (neat and clean, imho).

Is this feasible?

Edit: another solution is to keep color schemes in different files, and change the `import` statement in main config file to include the right one (which will also trigger config reload).

**Comment by chrisduerr** [comment]
> Is this feasible?

Not really, the configuration files are combined as parsed structures not as plain text. And I have no interest in changing that.

The yaml anchors are already way too complicated for my taste, I'd advocate for just using different files for different config schemes.
