### ISSUE TITLE
Cache less characters by default 

### ISSUE THREAD

**Issue by JAicewizard** [alacritty/alacritty#5159]
I started looking at some of the baseline memory usage, and as bad as rust memory profiling is, I managed to figure out that at least 4 MiB of baseline memory usage is just caching "common" characters:
```
        self.load_glyphs_for_font(self.font_key, loader);
        self.load_glyphs_for_font(self.bold_italic_key, loader);
        self.load_glyphs_for_font(self.italic_key, loader);
        self.load_glyphs_for_font(self.bold_italic_key, loader);
```

Not only are 2 keys loaded twice (probably just overwritten), italics and bold are also loaded by default. I don think I have ever used bold or italics in a terminal. (let alone, both at the same time).

Maybe it is also worth considering only loading A-Ba-b0-9, where currently all ascii characters above 32 are loaded.

It may also be worth being more efficient about the char cache in general. like kick characters out based on usage instead just clearing the whole cache. This is also only done while; either updating the font (but maybe its better to re-raster the existing glyphs instead of kicking everything out), or when the cursor is dirty, which I dont know what it means but I am not sure what a cursor has to do with the glyph cache.

This last part is probably not relevant for this issue specifically, but is in the same vein so making a new issue wouldnt make sense to me.

PS: I would be willing to implement a more conservative initial cache load, but restructuring the whole cache might be a bit much for a first PR.

**Comment by chrisduerr** [comment]
There's nothing going to change about this, even if this would take 4MiB. Though I'm not sure how you got to that result.

The double bold_italic_key load is an error though, that shouldn't be a thing.

**Comment by JAicewizard** [comment]
I got that result by commenting out those lines and seeing what the difference was.

Can you explain why nothing will change? This (caching less chars initially) seems like an obvious improvement with little to no negative sides.

Making a more intelligent cache  could have downsides and would take a significant amount of time but just changing what chars are cached by default doesnt at all.

**Comment by chrisduerr** [comment]
> I got that result by commenting out those lines and seeing what the difference was.

How did you check that?

> Can you explain why nothing will change? This (caching less chars initially) seems like an obvious improvement with little to no negative sides.

I've never said nothing will change. But using a bit of memory to cache common glyphs makes sense. Though your reported values seem off.

**Comment by JAicewizard** [comment]
> How did you check that?

Using `gnome-system-monitor`.

> Though your reported values seem off.

They do, dont they. I am as surprised as you are. I did modified the code to not render, to prevent any other effects to influence the cache, and those ware the results.

**Comment by chrisduerr** [comment]
Rendering shouldn't affect the memory usage. You definitely should keep that going otherwise your results are going to be way off.

**Comment by JAicewizard** [comment]
Still a bit odd that changing those lines would change memory usage that much. I didnt expect rendering to reduce the effect to an almost non-existant state. Seems like maybe the characters warnt the real problem. Maybe the act of actually calling GL already allocates that much.

Sorry for not looking more into it. For what its worth, I found most of the memory usage to be openGL related, most notable the programs. although, that was also tested using the apparently flawed method.
