### ISSUE TITLE
Gaps appearing in between characters

### ISSUE THREAD

**Issue by SmiteshP** [alacritty/alacritty#5163]
Gaps appearing in between characters when using Alacritty as shown in screenshot below. left is Alacritty and right is Termite.
[
![Screenshot from 2021-05-21 18-50-16](https://user-images.githubusercontent.com/43147494/119151016-9b51dd80-ba6c-11eb-8469-488f7ac652c8.png)
](url)

The gaps also shift around when changing font size as seen below. Observe the Manjaro logo as horizontal gaps appear and disappear, while the vertical gap stays mostly constant.

https://user-images.githubusercontent.com/43147494/119150518-267ea380-ba6c-11eb-8a9d-ab89c585847b.mp4

Below is a video of termite. (Expected behavior)

https://user-images.githubusercontent.com/43147494/119150610-3b5b3700-ba6c-11eb-960f-59c42e234a97.mp4

I tried messing around with settings in alacritty.yml but nothing seems to resolve this issue. 
Changing the **y offset** setting to fix this just squishes the text together vertically. While the gap does disappear for sufficiently large negative number, It just make the text too close together.
Changing the **y glyph_offset** moves the text up and down with respect to cursor position which doesn't help.

I tried a few other fonts too. The size of the gaps vary from font to font but the issue is present nonetheless.
The font used in above screenshots is [Input Mono](https://input.djr.com/), the gaps are most wide in this font.
Also other terminals I tested like Kitty and Gnome Terminal (with same fonts) don't have this issue.

My [alacritty.yml](https://pastebin.com/Mvj9qnCu)
OS : Linux
Alacritty version : alacritty 0.7.2 (5ac8060b)
X11, Gnome 3.38

PS : RIP Termite :(

**Comment by chrisduerr** [comment]
That's because Alacritty uses your font to render all glyphs.
