### ISSUE TITLE
Airline looking abnomral in alacritty

### ISSUE THREAD

**Issue by FrostyTheDumDum** [alacritty/alacritty#5165]
### System
OS: Linux
Version: 0.8.0
Linux/BSD: X11, Picom and BSPWM

### Info
Airline bar in Neovim looks abnormal.

![image](https://user-images.githubusercontent.com/75714323/119249496-98630400-bbb6-11eb-8937-3faca2ddd88f.png)

### Neovim init.vim
```vim
call plug#begin('~/.vim/plugged')
Plug 'morhetz/gruvbox'
Plug 'mhinz/vim-startify'
Plug 'preservim/nerdtree'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'dense-analysis/ale'
call plug#end()
let g:airline_powerline_fonts = 1
let g:airline_highlighting_cache = 1
let g:airline_extensions = ['branch', 'tabline', 'coc', 'ale']
let g:airline#extensions#ale#error_symbol = ' '
let g:airline#extensions#ale#warning_symbol = ' '
let g:airline#extensions#ale#checking_symbol = ' '
colorscheme gruvbox
```

Alacritty configuration - https://gist.github.com/FrostyTheDumDum/3a7041df26f5fd98fa5a13228a4c02fe

I have tried multiple fonts, MesloLGS NF, Source Code Pro, Fira Code. The issue remains the same

**Comment by FrostyTheDumDum** [comment]
Alacritty : Left
Kitty : Right

Note that kitty font size IS a bit smaller, but that doesn't seem to have any effect.

![image](https://user-images.githubusercontent.com/75714323/119249946-69e72800-bbba-11eb-8673-46b468ae17d2.png)

**Comment by FrostyTheDumDum** [comment]
After testing out a few fonts, this issue has been fixed and was my mistake, not of Alacrittys. I apologize.

**Comment by Mohan-cloud** [comment]
@FrostyTheDumDum  How did you fix it?

**Comment by FrostyTheDumDum** [comment]
@Mohan-cloud By changing my font, I use Iosevka now
