### ISSUE TITLE
Allow to set specific (absolute) font sizes with key bindings

### ISSUE THREAD

**Issue by talw** [alacritty/alacritty#5169]
Allot to set specific key binds to set the font size to specific values.

For example:

Key | Size
-- | --
Alt-J | 12
Alt-K | 16
Alt-L | 22
Alt-Semicolon | 32

I am using a bitmap font with about 4 different specific sizes.
Using the key bindings to increase and decrease the font size requires different amount of key strokes between those font sizes.
And since it is bitmap, not every bump increase even causes a change in the font rendering, so it's hard to get feedback how many button presses were registered. I basically remember that between size A and B I have to press 4 times and between B and C I have to press 6 times etc. and when I want to change sizes I count how many times I pressed the font increase key binding, but this is slow especially when moving from my smallest specific font size to the largest one.

With `urxvt`, I have something like the following:

```
URxvt.keysym.M-j: command:\033]710;*-terminus-medium-*-*-*-12-*-*-*-*-*-*-*
URxvt.keysym.M-k: command:\033]710;*-terminus-medium-*-*-*-16-*-*-*-*-*-*-*
URxvt.keysym.M-l: command:\033]710;*-terminus-medium-*-*-*-22-*-*-*-*-*-*-*
URxvt.keysym.M-semicolon: command:\033]710;*-terminus-medium-*-*-*-32-*-*-*-*-*-*-*
```

So alt-{J|K|L|Semicolon} map to sizes 12,16,22,32 of `terminus`

I tried to replicate this setup on Alacritty, but the closest I got is to map an invocation of a bash script on those key bindings, which  uses `sed` to change the static font size defined in `alacritty.yml` but this has the problem that all opened terminals get their size changed instead of just the current.

What do other users of bitmap fonts do? Or do they not change their font size as much?

Any suggestion is appreciated!

**Comment by chrisduerr** [comment]
I'm not going to add a feature into Alacritty to work around crappy ancient fonts that haven't figured out proper scaling yet. If you want to do this, just edit the configuration file.
