### ISSUE TITLE
Feature request: support for native Emoji & Symbols picker for MacOS

### ISSUE THREAD

**Issue by antonk52** [alacritty/alacritty#5179]
This issue is a feature request. I was not able to find a similar one or if this was discussed within other issues prior.

I would like to propose a new feature to support a native macOS emoji and symbols picker. It can be opened whenever a user is focused on any text field within any application(browser/settings/notes/slack etc). It can be opened via `Menu > Edit > Emoji & Symbols` or the default shortcut

<kbd>ctrl</kbd><kbd>cmd</kbd><kbd>space</kbd>

This is what the native picker looks like.
<img width="300" alt="Screen Shot 2021-05-26 at 15 55 52" src="https://user-images.githubusercontent.com/5817809/119663254-dff9c200-be3a-11eb-8a1e-358b2de763f4.png">

This is an OS wide feature and it is also supported by other terminals such as the default terminal app, item2 and kitty, though for kitty I believe they have a custom selection implemented. 

Are there plans for supporting this in future?

**Comment by chrisduerr** [comment]
IME is already supported on macOS and I'm pretty sure there is an IME emoji picker. I have no desire to support anything else.
