### ISSUE TITLE
Freeze, crash, and persistent window after printing large text

### ISSUE THREAD

**Issue by hjfeldy** [alacritty/alacritty#5180]
So this has only happened once, just now, but I'm submitting an issue because I recently performed a system update, and alacritty updated from 0.7.2_1  to 0.8.0_1. I have also literally never had a single bug or problem with this program, so I figure this must be from the update.

I printed a large amount of text to the console, and it resulted in a freeze. The rest of my system was running fine, and I had plenty of memory to spare. When I force quit the window, my tiling WM left an empty space on the screen where the alacritty had been, sort of like a ghost-window (by "blank space," I mean that I could see my desktop background). I got rid of the ghost window by running "pkill alacritty"

### System

OS: Linux
Version: alacritty 0.8.0
Display: X11, i3wm
Kernel: 5.11.22_1

### Logs

No logfile, but here is the python code that crashed alacritty:

from selenium import webdriver
from bs4 import BeautifulSoup

driver = webdriver.Firefox()
driver.get('https://twitter.com/elonmusk') # Lol
soup = BeautifulSoup(driver.page_source)

print(soup) # Source of crash

**Comment by chrisduerr** [comment]
Unless you are able to reproduce this or have a backtrace from the frozen program, this report is unfortunately rather useless.

Are you able to provide any useful information that could help identify this issue?

**Comment by hjfeldy** [comment]
I see your point. Sorry about that, I cannot reproduce the issue or provide a logfile. Closing.
