### ISSUE TITLE
Alacritty doesn't toggle between windowed and fullscreen via F11 in Ubuntu

### ISSUE THREAD

**Issue by wusticality** [alacritty/alacritty#5183]
Alacritty doesn't toggle between windowed and fullscreen mode via `F11` in Ubuntu. Instead, the `~` character is simply printed to the stdout. I'd expect Alacritty to work like other applications (aka, `gnome-terminal`).

### System

OS: Linux (Ubuntu 20.04)
Version: alacritty 0.8.0 (a1b13e6)

**Comment by chrisduerr** [comment]
If F11 is a WM binding, Alacritty will comply. But there's no reason why Alacritty would do this by default.

**Comment by wusticality** [comment]
Hey @chrisduerr, thanks for responding. `F11` in Ubuntu toggles between fullscreen and windowed mode in Gnome 3 (which is a window manager) for all applications, but it doesn't work for Alacritty. It seems Alacritty is interpreting `F11` as the `~` character, is there a potential workaround? Thanks again!

**Comment by chrisduerr** [comment]
There's nothing for Alacritty to interpret if the window manager would actually have that as a global binding. In that case Alacritty never receives that keypress. If Alacritty receives it, it's not a global binding.
