### ISSUE TITLE
Disable hardware acceleration

### ISSUE THREAD

**Issue by LukeMauldin** [alacritty/alacritty#5187]
## Description
I am attempting to use alacritty in a Citrix virtual desktop environment where the host system does not provide hardware accelerated graphics.  When I launch alacritty I get the error below.  Is there an option I can set in the config to fall back to software based rendered?

### System

OS: Windows
Version: 0.8

### Logs
---------------------------
Alacritty: Runtime Error
---------------------------
panicked at 'gl function was not loaded', D:\a\alacritty\alacritty\target\release\build\alacritty-588e4c7c1a5a2fb6\out/gl_bindings.rs:11325:13

**Comment by chrisduerr** [comment]
No, that kinda defeats the purpose.
