### ISSUE TITLE
How to setup config file for alacritty?

### ISSUE THREAD

**Issue by Aleksit0** [alacritty/alacritty#5189]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Windows
Version: `alacritty --0.8.0` output
Linux/BSD: X11/Wayland, DE or Compositor and WM

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

## How can I setup a config file for alacritty and use custom font family and so on?

**Comment by rYR79435** [comment]
The documentation has a section on this: https://github.com/alacritty/alacritty#configuration.

It points you to the default config included with every release: https://github.com/alacritty/alacritty/releases.
That file includes everything. Simply search for "font" and uncomment what you need.
