### ISSUE TITLE
Support changing the opacity on the fly

### ISSUE THREAD

**Issue by NetSysFire** [alacritty/alacritty#5191]
It would be great if support for changing the background opacity, e.g increasing or decreasing by a configurable amount, resetting and setting to being completely opaque would be added. [kitty features such behavior](https://sw.kovidgoyal.net/kitty/#other-keyboard-shortcuts) for example.

The current situation does not allow setting the opacity (or any other config directive except font size etc) of a single instance without custom configs, wrappers and/or other hacks. It can be useful to temporarily increase the opacity when showing someone else something on my screen or when using an application that is best used with an opaque background for readability.

It would be awesome and more convenient if proper support for it could be added.

**Comment by chrisduerr** [comment]
As stated in numerous previous issues, I have no interest in making a dedicated option to change opacity per-window.

I'm open to suggestions on how to change any option on a per-window basis, should there be a clean proposal enabling this.

**Comment by rieje** [comment]
It would nice especially for Wayland where this is the only option.
