### ISSUE TITLE
[Feature request] ReceiveChar passthrough scroll wheel

### ISSUE THREAD

**Issue by FrostKiwi** [alacritty/alacritty#5192]
### System

OS: FreeBSD
Version: alacritty 0.9.0-dev (54acabc)
WM: Sway (Wayland)

### Suggestion
It seems it is not possible to disable the binding for the Scrollwheel.
Thus I would love to suggest this feature.

### Use case
Using text editors, scroll wheel can be a great way to scroll text. In my case, I use terminal emacs and was used to scrolling emacs with scroll wheel in termite. But in alacritty it is bound by default to scrolling the history. An option to passthrough this would be an excellent addition for my workflow. Maybe someone else's too.

**Comment by chrisduerr** [comment]
If the application requests mouse mode, scrollwheel will be passed to the application.

**Comment by FrostKiwi** [comment]
> If the application requests mouse mode, scrollwheel will be passed to the application.

Indeed. That was a mistake on my part. I did not remember, that in Emacs terminal mode mouse mode has to be explicitly enabled.
