### ISSUE TITLE
ReceiveChar not honored for Shift+End and Shift+Home

### ISSUE THREAD

**Issue by FrostKiwi** [alacritty/alacritty#5193]
### System

OS: FreeBSD 13
Version: alacritty 0.9.0-dev (54acabc)
WM: Sway (Wayland)

### Issue
By default, Shift+End and Shift+Home scroll the scrollback history to the End and the Start. Defining those with ReceiveChar, stops the binding, but those combinations are not passed through to Programms running in alacritty.
In my use case this concerns Emacs terminal. Shift+End and Shift+Home are important ways to select Text, but the Shift MOD never reaches Emacs in the case of Shift+End and Shift+Home.
If I type Shift+Alt+Home, then Only Alt+Home is being received, Shift disappears.

**Comment by chrisduerr** [comment]
There is no character representing Home or End.

**Comment by FrostKiwi** [comment]
Worked around it by binding chars to an escape sequence....
