### ISSUE TITLE
Show ~ for home dir?

### ISSUE THREAD

**Issue by Aleksit0** [alacritty/alacritty#5196]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Windows
Version: `0.8.0` output
Linux/BSD: X11/Wayland, DE or Compositor and WM

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

How to show ~ for home directory?

**Comment by chrisduerr** [comment]
Sounds like you're talking about a shell issue.
