### ISSUE TITLE
Color change to red on cd command

### ISSUE THREAD

**Issue by Marculonis21** [alacritty/alacritty#5199]
### System
OS: Ubuntu 20.04
Version: latest from apt - alacritty 0.9.0-dev
I3 gaps on Ubuntu 20.04
Alacritty with ZSH

### Issue
I ran into an issue where when using ZSH and alacritty, alacritty prints out the possible cd entries (when using cd <TAB>) in red for no reason. This happens when I open alacritty directly by a shortcut. I've tried to change the colortheme and it's not a weird conflict of colors (alacritty is genuinely picking red color for it). 

Then I tried to first open gnome-terminal and from that I start alacritty and the colors get back to normal (for that session).

Any suggestions about why is that possible or how to change it. Thank you!

**Comment by chrisduerr** [comment]
System/shell config issue, not a terminal problem.
