### ISSUE TITLE
Support for OSC 9;4 for progress reporting

### ISSUE THREAD

**Issue by dancojocaru2000** [alacritty/alacritty#5201]
Windows Terminal adopted ConEmu's OSC 9;4 progress reporting escape sequence. I think it would be nice to add this in Alacritty as well.

While Windows Terminal does display the progress as a circular progress "bar" in the tab bar, the main usecase would be using system APIs to display the progress in the task bar / dock.

At the moment, conflicting use of OSC 9 comes from iTerm 2 using it for notifications and Kitty adopting it for compatibility reasons (I suggested in [kovidgoyal/kitty#3679](https://github.com/kovidgoyal/kitty/issues/3679) to also adopt this proposal and drop OSC 9 usage for notifications as Kitty also uses OSC 99 for notifications).

The way OSC 9;4 works in Windows Terminal is detailed in [microsoft/terminal#8055](https://github.com/microsoft/terminal/pull/8055). Here is how it looks like in Windows Terminal:

![Progress being displayed instead of a tab icon](https://user-images.githubusercontent.com/9626761/120375473-82c2ac80-c323-11eb-85d6-f83176331d31.png)
![Progress displayed in the task bar](https://user-images.githubusercontent.com/9626761/120375513-8e15d800-c323-11eb-9a73-f58f6d3efd59.png)

It is also to be noted that, although a conclusion wasn't reached and the last activity was 7 months ago, [terminal-wg discussed this too in issue 29](https://gitlab.freedesktop.org/terminal-wg/specifications/-/issues/29).

**Comment by Gordon01** [comment]
@chrisduerr can you please provide why this is closed as wontfix?

Progress reporting is useful and it's sad that mentioned OSC are only implemented in winterm

**Comment by Gordon01** [comment]
[systemd](https://mastodon.social/@pid_eins/113406672373007116), [ptyxis](https://blogs.gnome.org/chergert/2024/12/03/ptyxis-progress-support/), [GNOME vte](https://gitlab.gnome.org/GNOME/vte/-/issues/2845) are now support this feature.

[A bug in kitty is fixed.](https://github.com/kovidgoyal/kitty/issues/8011)

And I hope we would do it in Rust's cargo [too](https://github.com/rust-lang/cargo/pull/14615).

**Comment by marxin** [comment]
Note it's one of the features of the just released Ghostty 1.2:
https://ghostty.org/docs/install/release-notes/1-2-0#graphical-progress-bars
