### ISSUE TITLE
Gnome 40 Wayland, can't interact with CSD with my fingers

### ISSUE THREAD

**Issue by t184256** [alacritty/alacritty#5204]
GNOME 40 Wayland, can't neither drag the window by the titlebar nor close it with a finger. Mouse works fine.
I'm aware you largely don't care about Gnome users, but this issue goes slightly beyond just look-and-feel.

### System

OS: Linux, NixOS 21.05
Version: alacritty 0.8.0
Linux/BSD: Gnome 40 Wayland

**Comment by chrisduerr** [comment]
I'd assume you're talking about touchscreens? I'm not actually aware of the level of support for touchscreens with the current CSDs, it's entirely possible there is none. Unfortunately I have no device to test that on.

**Comment by t184256** [comment]
Yep, touchscreen presses. I'll try to also get a stylus and test with a stylus for completeness.

**Comment by chrisduerr** [comment]
I've added a comment to https://github.com/alacritty/alacritty/issues/3671, I think that should suffice since currently touchscreen is just not supported at all.
