### ISSUE TITLE
column setting causes empty lines with tiling WMs on startup

### ISSUE THREAD

**Issue by FrostKiwi** [alacritty/alacritty#5205]
### System

OS: FreeBSD 13
Version: alacritty 0.9.0-dev (54acabc)
Sway (Wayland)

A tiling WM forces a certain window size. If the window width is smaller than the configured column count, it causes empty lines to appear above the prompt. These can be removed with a clear command and appears only on startup.

![20210603_15h57m33s_grim](https://user-images.githubusercontent.com/60887273/120657075-773ac700-c484-11eb-9569-98f4eec15178.png)

Setting window: dimensions: columns: 2 solves the problem.

**Comment by FrostKiwi** [comment]
> Does the same thing happen without columns configured when resizing the window? Is your shell prompt custom or just a text string at the left?

The prompt is the default fish prompt, which I assume is just a simple string. Without column configured, the empty line continues to happen. When resizing, before clearing, it causes garbage to appear above the prompt. After clearing, resizing does no corruption anymore.
But again, with column set to 2, it solves the sitution.

![20210603_17h22m26s_grim](https://user-images.githubusercontent.com/60887273/120670114-642df400-c490-11eb-8321-daaa974f92e3.png)

**Comment by chrisduerr** [comment]
Try bash.

**Comment by FrostKiwi** [comment]
> Try bash.

Almost same deal. No Empty line at startup, however, there is a different kind of corruption possible regardless of shell:
If you resize and the side of the window to touch the prompt, it causes garbage, regardless of shell. The garbarge size is related to the column size, until the first clear. Kinda tough to put into words, here in video form:
Column 200, bash:

https://user-images.githubusercontent.com/60887273/120674267-38ad0880-c494-11eb-8a82-abd374802e11.mp4

Column 2, bash

https://user-images.githubusercontent.com/60887273/120674551-7e69d100-c494-11eb-8d34-74d5a8f4d174.mp4

**Comment by chrisduerr** [comment]
Yeah that's working as expected.
