### ISSUE TITLE
Background opacity not setting

### ISSUE THREAD

**Issue by AMTitan** [alacritty/alacritty#5207]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

So on line 327 I set the `background_opacity` to 0.5 but it is still not different (and yes this is the right location all the other stuff work). I have no idea if I am just dumb and if I am sorry.

### System

OS: Linux
Version: 0.8.0
Linux/BSD: X11, Compositor, Xmonad
(and I am not 100% sure on the first 2 ^ I am kinda new to Linux and yes I did start using Linux with arch I like to feel pain)

### Logs
[Alacritty-3368600.log](https://github.com/alacritty/alacritty/files/6601698/Alacritty-3368600.log)

### Alacritty.yml

https://pastebin.com/5NqE6AYV

## Image

![image](https://user-images.githubusercontent.com/29708070/120873734-51d7b700-c571-11eb-8118-fee8b0cbe367.png)

**Comment by chrisduerr** [comment]
Please remove the whitespace in front of `background_opacity`.

**Comment by AMTitan** [comment]
@chrisduerr thank you
