### ISSUE TITLE
draw_bold_text_with_bright_colors is ignored on Windows

### ISSUE THREAD

**Issue by johnnovak** [alacritty/alacritty#5208]
### System

OS: Windows 10
Version: alacritty 0.8.0 (a1b13e6)

## Issue

The config parameter `draw_bold_text_with_bright_colors ` has no effect on Windows. Bolded text is always drawn using bright colours, regardless of the setting.

I've done some double checking with the same config, on OS X the parameter works as expected.

Checked again a few times on Win10 and I'm 100% confident the parameter has no effect on Windows (it's effectively fixed to "true").

**Comment by chrisduerr** [comment]
Likely a ConPTY internal thing, so nothing Alacritty can do.

**Comment by johnnovak** [comment]
>  so nothing Alacritty can do

Correction: nothing you are willing to make work ;) You know the saying, if there is will...
