### ISSUE TITLE
weird behavior with ~ char

### ISSUE THREAD

**Issue by perrefe** [alacritty/alacritty#5210]
I've set this keybinding to correctly print the ~ character when pressing Alt+ñ in a Macbook spanish keyboard

```
key_bindings:
  - { key: Semicolon, mods: Alt, chars: "\x7e" }
```

But this causes this behavior:

https://user-images.githubusercontent.com/784261/120910085-d0a02300-c649-11eb-88eb-3f10b0dc7168.mp4

Alacritty version: 0.8.0

**Comment by chrisduerr** [comment]
This is an issue with alt on macOS being used as AltGr to modify your key presses. There's an upstream PR working on an option to disable this.
