### ISSUE TITLE
Alacritty doesn't exit fullscreen mode when goes in from maximized mode

### ISSUE THREAD

**Issue by marcosdly** [alacritty/alacritty#5212]
I added this line to set a key binding to toggle fullscreen:
`- { key, F11                                          action: ToggleFullscreen }`
When I'm in windowed mode it goes in and out the fullscreen mode whithout any problem, but when the window is maximized it goes in, but doesn't goes out the fullscreen mode. When I type the key it stutter, but don't exit the fullscreen mode.

### System
OS: Linux Manjaro
Version: alacritty 0.9.0-dev (3e867a0)
Linux: X11, GNOME 40.1.0, Mutter

**Comment by chrisduerr** [comment]
Does gnome have system bindings to achieve that? It sounds like a WM issue. Alacritty just sends a request, it has nothing to do with how that request is handled.

**Comment by marcosdly** [comment]
> Does gnome have system bindings to achieve that?
No

**Comment by chrisduerr** [comment]
Is there a different way to leave fullscreen that works, or one that doesn't?

**Comment by marcosdly** [comment]
I don't know

**Comment by chrisduerr** [comment]
Surely you're at least able to leave fullscreen through the window manager itself?

**Comment by marcosdly** [comment]
> Does gnome have system bindings to achieve that?

It actually have! I searched for a whille and found out that there is an "Toggle fullscreen mode" on Settings > Keyboard shortcuts. Just setted the key to F11 and worked just fine.

**Comment by chrisduerr** [comment]
Okay, so a key binding set in the WM works, but doing it in Alacritty doesn't? Even if the window is maximized?

Could you share a recording of the "stuttering" you see with Alacritty's binding? Does it help to press the binding multiple times?

**Comment by marcosdly** [comment]
https://www.youtube.com/watch?v=xO1JR2H4Cjk
(turn on the subtitles)

**Comment by chrisduerr** [comment]
Could you test the following patch?

```diff
diff --git a/alacritty/src/display/window.rs b/alacritty/src/display/window.rs
index 7302c687..ab21109f 100644
--- a/alacritty/src/display/window.rs
+++ b/alacritty/src/display/window.rs
@@ -389,6 +389,7 @@ impl Window {
 
     /// Toggle the window's fullscreen state.
     pub fn toggle_fullscreen(&mut self) {
+        println!("FULLSCREEN: {:?}", self.window().fullscreen().is_none());
         self.set_fullscreen(self.window().fullscreen().is_none());
     }
```

I think Alacritty might not be realizing the application is already in fullscreen mode, thus trying to set it into fullscreen again.

**Comment by marcosdly** [comment]
How do I apply that? Build alacritty again?

**Comment by chrisduerr** [comment]
Like any other patch, just `git apply` it. And yes, it requires building Alacritty.

**Comment by marcosdly** [comment]
I'm a complete noob on git, so I'm getting more confuse trying to learn how to apply this patch. Can you type the command so I can just paste it instead of we spend much more time trying to do this?

**Comment by chrisduerr** [comment]
`git apply <patchfile>` while in the repo. That diff is your patchfile.

**Comment by marcosdly** [comment]
don't work

**Comment by chrisduerr** [comment]
Well, have you installed git?

**Comment by marcosdly** [comment]
yes

**Comment by chrisduerr** [comment]
Then you're clearly doing something wrong. It shouldn't be that tough, just put the diff in a file and apply it while inside of a git repo.

**Comment by marcosdly** [comment]
I don't know that a I need to put that in a file. Now I did it, runned `git apply issue.patch` and get `error: corrupt patch at line 12`

**Comment by chrisduerr** [comment]
You need to add a newline at the end of the patch.

**Comment by marcosdly** [comment]
It worked, now I can toggle fulscreen through alacritty!

**Comment by chrisduerr** [comment]
Wait what? That patch didn't change any functionality...

Could you try the latest master without the patch please?

**Comment by marcosdly** [comment]
You mean download the repository again and rebuild? I overwrited the previous build that I was using. Could the problem be an hidden error in the building process?

**Comment by chrisduerr** [comment]
Of course you could have done something wrong, yes. But if you're on manjaro there should be a package available in the repos, why aren't you using that?

**Comment by marcosdly** [comment]
Because the version on the AUR is not up to date.

**Comment by chrisduerr** [comment]
The AUR? Alacritty should be in the official repositories. That one has the latest stable version.

**Comment by marcosdly** [comment]
In Manjaro alacritty is only available on the AUR. And now it's up to date to version 0.8. When When I searched it was on version 0.7.2.

https://imgur.com/a/bkZaNFv

**Comment by chrisduerr** [comment]
I'm not sure you understand what you're doing. Which certainly makes your distro choice questionable.

Could you try the latest version of Alacritty from the **official** community repos?

**Comment by marcosdly** [comment]
If you are saying that I don't know what I'm doing so it must be true. The point is: the problem is solved. If you think it was my mistake so don't apply the patch, if not, apply it, since it didn't change any functionality. I'm just saying.

Thanks for all.
