### ISSUE TITLE
Common zsh bug - partial fix for alacritty - Horrific mess when resizing terminal window

### ISSUE THREAD

**Issue by raven2cz** [alacritty/alacritty#5214]
Any chance to include zsh patch for alacritty?

**See**
https://github.com/romkatv/powerlevel10k
https://github.com/romkatv/zsh/tree/fix-winchanged

**Chapter**
Horrific mess when resizing terminal window

_Comment:_
It won't help if you are using Alacritty, Kitty or some other terminal that reflows text on resize but doesn't reflow saved cursor position. On such terminals the patch will have no visible effect.

**Comment by chrisduerr** [comment]
There's nothing for Alacritty to include.

**Comment by raven2cz** [comment]
Close without any advice? Thanks....
And do you have some advice how to handle this problem for alacritty?
