### ISSUE TITLE
Inputting Chinese characters with IME produces garbage

### ISSUE THREAD

**Issue by oxalica** [alacritty/alacritty#5215]
1. Using fcitx5+rime to input Chinese character.
![image](https://user-images.githubusercontent.com/14816024/120996197-b2a50080-c7b8-11eb-85dc-6f7299baa264.png)

2. Hit space to submit. It produces garbage characters.
![image](https://user-images.githubusercontent.com/14816024/120996259-bfc1ef80-c7b8-11eb-98a1-b3aed995b04d.png)

3. Copy and paste these characters works well. Also IME works well in KDE `konsole`.
![image](https://user-images.githubusercontent.com/14816024/120996499-f39d1500-c7b8-11eb-867e-b40aad2bafa0.png)

### System

OS: Linux
Version: alacritty 0.8
Linux: X11, KDE

### Logs

`alacritty -vv --print-events -o debug.persistent_logging=true`
https://gist.github.com/oxalica/fe3d51700908a65c5cfb950679ef850e

**Comment by chrisduerr** [comment]
What's your locale?

**Comment by oxalica** [comment]
> What's your locale?

At least they are all UTF-8.
```
> locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME=C
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=C
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by chrisduerr** [comment]
Can you share the `alacritty --print-events` output after the IME input is submitted to Alacritty?

**Comment by oxalica** [comment]
It's already included, after releasing `Space` [here](https://gist.github.com/oxalica/fe3d51700908a65c5cfb950679ef850e#file-alacritty-vv-print-events-log-L289-L301). (Sorry but I submitted the log where I typed `你好` (`nihk<space>` in IME), which is not the same characters as the screenshot, but still relevent.)

According to the log, alacritty received six characters `ä`, `½`, `\u{a0}`, `å`, `¥`, `½`.
Note that `你好` in UTF8 is also six bytes `e4 bd a0 e5 a5 bd`.
It seems to incorrectly use [Extended ASCII](https://en.wikipedia.org/wiki/Extended_ASCII) instead of UTF8 when decoding these UTF8 bytes. Though my locale is `en_US.UTF-8`.

**Comment by chrisduerr** [comment]
Your shell locale is `en_US.UTF-8` at least. But that doesn't necessarily mean Alacritty's is.

What happens when you launch one Alacritty instance from another? Does that change anything?

**Comment by oxalica** [comment]
> What happens when you launch one Alacritty instance from another? Does that change anything?

Still the same result.

**Comment by chrisduerr** [comment]
Have you tried a different IME? Is there any IME-specific config you have setup? You're positive you're on X11, right? Have you tried Wayland?

**Comment by oxalica** [comment]
It turns out to be an issue from fcitx side https://github.com/fcitx/fcitx5/issues/254 . Bumping `xcb-imdkit` fixes it.
Thanks for your help!
