### ISSUE TITLE
Weird artifacts on font glyphs from desktop background image with opacity=1.0

### ISSUE THREAD

**Issue by ryanberckmans** [alacritty/alacritty#5216]
### System

Version: alacritty 0.9.0-dev (3e867a0)

![image](https://user-images.githubusercontent.com/299324/121023373-d7718780-c768-11eb-87b9-65ab0ce84a71.png)

### Description

With an empty .alacritty.yml, there are weird artifacts on the font glyphs that are derived from my desktop background image.

Note that the pattern of artifacts is in the shape of my background image:

![image](https://user-images.githubusercontent.com/299324/121022397-e9065f80-c767-11eb-91c2-2a6ab91ff981.png)

I previously had some driver issues with my AMD Radeon RX 6800 XT, perhaps this is related?

**Comment by chrisduerr** [comment]
> I previously had some driver issues with my AMD Radeon RX 6800 XT, perhaps this is related?

This looks very much like a driver issue, yes. Which driver are you running?

**Comment by ryanberckmans** [comment]
Thanks for your response!

It was a driver issue. Previously, I was running `amdgpu-pro-20.45-1164792-ubuntu-20.04`. I upgraded to `amdgpu-pro-21.10-1247438-ubuntu-20.04` and now it works.

Btw, for those trying to get modern AMD gpus working with Ubuntu 21.04, [this guide](https://forum.level1techs.com/t/ubuntu-20-10-rx-6800-xt-how-to-steam-vulkan-up-and-runing-guide-wip/164137) worked for me. I'm using the "Ubuntu mainline" GUI to select my kernel version. My whole setup is now working with kernel 5.13.0-rc5.
