### ISSUE TITLE
Strange one-pixel line at the bottom of half blocks

### ISSUE THREAD

**Issue by r00ster91** [alacritty/alacritty#5217]
Just when I was making a new showcase image for [yayagram](https://github.com/r00ster91/yayagram#yayagram---play-nonogramspicross-in-your-terminal), I noticed that in Alacritty there are some strange one-pixel lines drawn at the bottom of half blocks (`'▄'` in this case) with foreground and background colors. You can see it on the showcase image in the README (top left) as well as here:

![image](https://user-images.githubusercontent.com/35064754/121190870-bfcef780-c86b-11eb-91bc-3b9035e9b292.png)

It can be reproduced with `printf "\n\e[48;5;1m\e[38;5;0m▄\e[0m\n\n"` for instance. You can also see it by simply printing the half block and going through it with your cursor (supposing you use the block cursor shape).

To compare this to other terminals, GNOME Terminal for instance does not have this problem and the half block is rendered cleanly without a displeasing line at the bottom:

![image](https://user-images.githubusercontent.com/35064754/121191040-e42ad400-c86b-11eb-9345-52d4fec494f1.png)

This is how I expect it to look (aside from color).
Depending on the text size, the way it looks varies.

See also: https://en.wikipedia.org/wiki/Block_Elements.

### System

OS: Linux
Version: alacritty 0.8.0
Linux: X11, GNOME 3.38.3 and Mutter

### Logs

Font/Terminal size: [Alacritty-18173.log](https://github.com/alacritty/alacritty/files/6616631/Alacritty-18173.log)
Keyboard and bindings: [Alacritty-18264.log](https://github.com/alacritty/alacritty/files/6616637/Alacritty-18264.log)

**Comment by chrisduerr** [comment]
Nothing strange about it. If the glyph doesn't fit the cell boundaries exactly, this is what will happen.

**Comment by r00ster91** [comment]
@chrisduerr what do you mean by a glyph not fitting the cell boundaries exactly? The letter `a` doesn't fit exactly either and there's no one-pixel line at the bottom. There must definitely be some pixel-accuracy issue with Alacritty here because wezterm and GNOME Terminal don't have this issue.

**Comment by r00ster91** [comment]
@chrisduerr Can you please respond? You haven't convinced me that this isn't another one of those issues that you prefer to instantly close & ignore because it's easier. I know that issues aren't a nice thing to have but not even responding after closing is definitely not the correct thing to do.
