### ISSUE TITLE
Open url in new window

### ISSUE THREAD

**Issue by cookEbox** [alacritty/alacritty#5219]
Changed from using the url command under mouse to hints.

Used to be
mouse:
  url:
    launcher:
      program: firefox
      args: [-new--window]

Changed to
hints:
  enabled:
    - regex: "(magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
              [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
      command: 
        program: firefox
        args: [-new--window]
      post_processing: true
      mouse:
        enabled: true

It opens firefox in a new window but does not load url. When I delete `args: [-new--window]` it opens fine but in existing window of firefox. I generally have my browser open on a different workspace and when I click on a url I like it to open on the workspace I am working.

### System

OS: Linux
Version:  alacritty 0.8.0 (a1b13e68)
Linux: X11 Picom and Xmonad

**Comment by chrisduerr** [comment]
It's `--new-window`, not `-new--window`.

**Comment by cookEbox** [comment]
Sorry my mistake
