### ISSUE TITLE
mpv up/down/left/right arrow keybindings not work when playing audio on windows 10 alacritty

### ISSUE THREAD

**Issue by flyxyz123** [alacritty/alacritty#5220]
### System

OS: windows 10 pro 21H1 19043.1023
Version: alacritty 0.8.0 (a1b13e6)

### Bug description

mpv up/down/left/right arrow keybindings not work when playing **audio** on windows 10 alacritty\
details see <https://github.com/mpv-player/mpv/issues/7944>\
in the link they say it's conpty issue\
windows terminal fixed this bug, but alacritty still has it

### Steps to reproduce

```
mpv example.mp3
```
then press left/right/up/down arrow keys\
more details see the linked issue provided above

**Comment by chrisduerr** [comment]
ConPTY issue -> Nothing Alacritty can do.
