### ISSUE TITLE
PSReadline vi-mode indicator doesn't change to block/line immediately when enter normal/insert mode on windows 10 alacritty

### ISSUE THREAD

**Issue by flyxyz123** [alacritty/alacritty#5221]
### System

OS: windows 10 pro 21H1 19043.1023
Version: alacritty 0.8.0 (a1b13e6)

### Bug description

PSReadline vi-mode indicator doesn't change to block/line immediately when enter normal/insert mode in alacritty\
details see <https://github.com/microsoft/terminal/issues/4106>\
in the link they say it's conpty issue\
windows terminal fixed this bug, but alacritty still has it

### Steps to reproduce

add this to powershell profile

```
Set-PSReadLineOption -EditMode Vi

# https://docs.microsoft.com/en-us/powershell/module/psreadline/set-psreadlineoption?view=powershell-7.1#example-6--use-vimodechangehandler-to-display-vi-mode-changes
function OnViModeChange {
    if ($args[0] -eq 'Command') {
        # Set the cursor to a block.
        Write-Host -NoNewLine "`e[2 q"
    } else {
        # Set the cursor to a line.
        Write-Host -NoNewLine "`e[6 q"
    }
}
Set-PSReadLineOption -ViModeIndicator Script -ViModeChangeHandler $Function:OnViModeChange
```

### Actual behaviour

press `ESC` in alacritty, cursor doesn't change to block immediately, I need to press another key for it to change, for examlple, press `k`\
next, press `i` in alacritty, cursor doesn't change to line immediately, I need to  press another key for it to change.\
details see the issue link provided above

### Expected behavior

press `ESC` in alacritty, cursor change to block immediately\
next, press `i` in alacritty, cursor change to line immediately\
details see the issue link provided above

### Others

there's another related bug for `ViModeIndicator = Cursor ` not working that exists both on windows terminal and alacritty, but windows terminal seems have not yet fix it\
details see <https://github.com/PowerShell/PSReadLine/issues/1233>

**Comment by chrisduerr** [comment]
ConPTY issue -> Nothing Alacritty can do.
