### ISSUE TITLE
copy and paste to browser joins all the lines

### ISSUE THREAD

**Issue by fefe17** [alacritty/alacritty#5224]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux
Version: alacritty 0.9.0-dev (3e867a05)
Linux/BSD: X11 + fvwm

I do audits. My work flow is: Log into system, collect information, copy and paste them into an shared Etherpad running in a Firefox.
When I copy and paste a multiline output (for example in this case the output of ls -l) and paste it into the Etherpad, Etherpad somehow things it's one long line instead of 10 consecutive lines.

I'm not sure if this is a bug in Alacritty. Could be Firefox, could be Etherpad. But when I mark multiple lines in a rxvt, st or xterm, and then paste them into Etherpad in Firefox, I get the correct result.

I understand this is a security measure to prevent accidentally executing a command if you paste text into a shell running in alacritty. However, I am trying to copy+paste in the other direction. From alacritty to firefox.

Interestingly, if I paste multiple lines from alacritty into an rxvt with vim running in it, I get multiple lines not one line.

Also, even more interestingly, if I paste the lines into Etherpad, I get a paste that looks right for a split second and then Etherpad reformats it to join all the lines into one huge line.

**Comment by chrisduerr** [comment]
> Interestingly, if I paste multiple lines from alacritty into an rxvt with vim running in it, I get multiple lines not one line.

Sounds like it's not Alacritty then.
