### ISSUE TITLE
how can i map <C-S> (control+S) to None for alacritty but to be able to use it in VIM?

### ISSUE THREAD

**Issue by alexzanderr** [alacritty/alacritty#5225]
the question is straight-forward.

i mapped to None Control+S in `alacritty.yml` but i cant use the keybinding in vim anymore. 

what can i do in order to use the keybiding in vim and disable it for alacritty? (not disable forever, but remap to something else than `save` because by default is see its mapped to `save`)

**Comment by chrisduerr** [comment]
Alacritty doesn't use Ctrl+S for anything. So just don't do anything with it.

**Comment by alexzanderr** [comment]
yea, my bad. i was mistaken. can you close and delete this issue?
