### ISSUE TITLE
Delete Key Does not work, instead it creates a space

### ISSUE THREAD

**Issue by alayshahh** [alacritty/alacritty#5226]
### System

OS: macOS
Version: 0.8.0

Using normal US keyboard on mac. Occurred on both touch bar and non touch bar key boards.
When I hit the delete button, the delete does not render properly, instead, it creates new spaces.

https://user-images.githubusercontent.com/47639000/121416915-59afa680-c937-11eb-830e-3732554be489.mov

**Comment by chrisduerr** [comment]
Try in bash. Which macOS version is that?

**Comment by alayshahh** [comment]
> Try in bash. Which macOS version is that?

It is macOS 11.3.1, but it has happened before on other versions as well. 
Not sure what the bug is, sometimes it occurs sometimes it does not. I checked my terminal and it always works fine.

**Comment by perrefe** [comment]
I'm having this same issue but this are my scenarios:

In my macbook with macOS 11.3.1 with zsh (5.8) and bash (3.2) works fine. 

Connected via ssh to a server with bash 4.4.12 works fine

Connected via ssh to a server with bash 5.0.3 I can reproduce this issue

**Comment by chrisduerr** [comment]
That sounds like it might be a terminfo thing.

**Comment by CrashAndSideburns** [comment]
Can confirm terminfo is the likely cause. Was having the exact same issue when I ssh-ed into my web server until I updated the terminfo.

**Comment by hareram77** [comment]
> ### System
> OS: macOS Version: 0.8.0
> 
> Using normal US keyboard on mac. Occurred on both touch bar and non touch bar key boards. When I hit the delete button, the delete does not render properly, instead, it creates new spaces.
> 
>  Screen.Recording.2021-06-09.at.3.27.46.PM.mov


edit the alacritty.yml file (located in: ~/.config/alacritty/alacritty.yml)
edit 

`TERM: Alacritty` to `TERM: xterm-256color `

and save the alacritty.yml file.

![Screenshot 2021-12-10 at 1 25 20 PM](https://user-images.githubusercontent.com/1381245/145537818-3275eea9-973f-4f3b-9b02-ed4125dd43f2.png)

**Comment by augustobmoura** [comment]
> Can confirm terminfo is the likely cause. Was having the exact same issue when I ssh-ed into my web server until I updated the terminfo.

Sorry, I don't understand a lot of how terminals work, how can I "update my terminfo"? I'm having the same issue when ssh-ing

**Comment by CrashAndSideburns** [comment]
@augustobmoura
It's right in [the docs](https://github.com/alacritty/alacritty/blob/master/INSTALL.md#terminfo).
