### ISSUE TITLE
Alacritty doesn't start if the disk is full

### ISSUE THREAD

**Issue by 1337M0nst3r** [alacritty/alacritty#5228]
It probably tries to create a file in /tmp but since the disk is full it crashes

### System
OS: Linux
Version: 0.9.0-dev (f9d83a2)
DE/WM: X11/AwesomeWM

### Logs
Here's the strace output: 
[alacritty.log](https://github.com/alacritty/alacritty/files/6633309/alacritty.log)

**Comment by chrisduerr** [comment]
Looks like a driver thing. Can you start other OpenGL applications?

**Comment by 1337M0nst3r** [comment]
I can't

**Comment by chrisduerr** [comment]
Well, Alacritty requires a functioning graphics context.
