### ISSUE TITLE
[windows] Alacritty replacing colors from config

### ISSUE THREAD

**Issue by m-lima** [alacritty/alacritty#5234]
On Windows, Alacritty seems to be replacing colors from the config file with other colors also configured there.
The first case is where "primary background" replaces the "normal black".
The second case is that "bright black" replaces the color index 243.

**Relates to:** https://github.com/alacritty/alacritty/issues/3836
The author seemed to have stumbled upon the first substitution case for the ANSI 0 black. Though the author failed to test with Powershell as a reference, instead using Windows Terminal, which in my personal opinion is not so robust yet.

#### Alacritty
The ANSI 0 black color was changed to 0xFF0000 for the purpose of demonstration, making it easier to see.
![alacritty_config](https://user-images.githubusercontent.com/13945557/121804237-a4863280-cc45-11eb-966d-3c645da021e5.png)

#### Powershell
As a reference for Windows terminal color display, I will use Powershell. Similarly to Alacritty, the ANSI 0 was also changed to 0xFF0000
![posh_config](https://user-images.githubusercontent.com/13945557/121803592-b0242a00-cc42-11eb-8874-b84fdefdf546.PNG)

### Desired outcome 1 (Powershell)
The black color ANSI 0 (which was overridden to "0xFF0000" to make it more visible) is properly used for both background and foreground
![posh_colors](https://user-images.githubusercontent.com/13945557/121803469-0e9cd880-cc42-11eb-83fe-4dbe3d7b91fe.png)

### Observed outcome 1 (Alacritty)
The black color ANSI 0 (which was overridden to "0xFF0000" to make it more visible) is ignored for the background color, and instead the primary background color is used.
![alacritty_colors](https://user-images.githubusercontent.com/13945557/121803496-4572ee80-cc42-11eb-82b0-78a82e21c58a.png)

### Desired outcome 2 (Powershell)
The color index 243 is displayed correctly, following the grayscale ramp
![posh_spectrum](https://user-images.githubusercontent.com/13945557/121804178-5bce7980-cc45-11eb-9f38-6a52b4060d70.PNG)

### Observed outcome 2 (Alacritty)
The color index 243 is actually rendering the color from the index 8 (bright black). These should be unrelated, but Alacritty is replacing one with the other.
![alacritty_spectrum](https://user-images.githubusercontent.com/13945557/121804180-5f620080-cc45-11eb-8cb1-4d096c615074.PNG)

### System

OS: Windows
Version: alacritty 0.8.0 (a1b13e6)

**Comment by chrisduerr** [comment]
It doesn't. If there's any issues with colors it's likely due to the ConPTY. So unless you can reproduce it with Linux/macOS, there's nothing Alacritty can do.
