### ISSUE TITLE
Howto change mouse shape?

### ISSUE THREAD

**Issue by tmpm697** [alacritty/alacritty#5238]
I can change `mouseshape` of `st` terminal in Xorg with:
```
static unsigned int mouseshape = <my mouse shape>
```
how can I change mouse shape with `alacritty`?

**Comment by chrisduerr** [comment]
You can't and I see no reason why you'd be able to. Unless you're talking about the terminal cursor shape?

**Comment by tmpm697** [comment]
No, it's cursor shape of mouse when you move in terminal space. 

Idk I'm from st terminal and had change mouse shape from the beginning of usage.
