### ISSUE TITLE
alacritty having two cursors in nvim terminal mode 

### ISSUE THREAD

**Issue by vellankiindeevar** [alacritty/alacritty#5239]
### System
OS: Windows ( using for wsl 2 )
Version: 0.8.0

![image](https://user-images.githubusercontent.com/81471588/122080258-c76a3f80-ce1b-11eb-9fa5-d84602fb3545.png)

**Comment by chrisduerr** [comment]
This is a known issue with Windows which has to be resolved by Microsoft.

**Comment by vellankiindeevar** [comment]
so where can i file an issue about this
