### ISSUE TITLE
alacritty shows dirty fonts 

### ISSUE THREAD

**Issue by Mangeshrex** [alacritty/alacritty#5242]
this started when i installed some fonts for rofi and then later when i opened the new terminal all the fonts were very dirty 

![Wed Jun 16 12:54:29 PM IST 2021](https://user-images.githubusercontent.com/82205152/122176402-2bcfe200-cea2-11eb-873b-d9fd96b1fec3.png)

dont know why this stuff gets in always and then when i install ttf-dejavu it again gets dirty and when i remove the font it again gets fixed but this time i didnt even install ttf-dejavu. I have tried changing all the fonts in the alacritty config.

**Comment by chrisduerr** [comment]
Just select whatever font you want to use in your config file.

**Comment by Mangeshrex** [comment]
yes but that isnt working for me i dont know why i am trying to fix this issue from yesterday but it doesnt shows any changes i removed my whole ~/.local/share/fonts folder but that didnt even fix it can you please suggest any way to make alacritty full default? so that i can again build it up with my confs
