### ISSUE TITLE
Auto input char 'd' to another window when focus out from alacritty

### ISSUE THREAD

**Issue by yayowd** [alacritty/alacritty#5243]
OS: Linux 5.10.42-1-lts
Version: alacritty 0.8.0 (a1b13e68)
Linux: Arch, Wayland, sway version 1.6

There is no more information in alacritty logs.

Detail:
When I switch the focus from alacritty to microsoft edge, it will auto input char 'd' into this bug write box, some times is Ctl + d.
When I switch the focus from other windows to microsoft edge, but it's normal.
This problem can be reproduced every time.

**Comment by chrisduerr** [comment]
Are you pressing the character `d` to switch windows? Alacritty doesn't have the capability to input characters into other applications, so you've probably got a messed up system configuration.

**Comment by yayowd** [comment]
In the default configuration of sway, I moved the cursor to activate the window without pressing any keyboard keys.

So I also think this problem is too weird. Originally, I thought it was a problem with my keyboard. After I replaced it with a new keyboard, the problem remained.

Any suggestions?

**Comment by yayowd** [comment]
After repeated testing, the problem is described as three types:
Do not do any keyboard input, only activate windows between alacritty (this) and other windows (other),
Every: Every time you activate other from this, the character 'd' will be input to other
Once: Enter the character 'd' into other only when activating other from this for the first time, and no problems will occur in the future
Normal: No problem

I found the steps to reproduce:
1. Open this and press ctrl+d to exit, reopen this, and enter the type ‘every’
2. In type ‘every’, after pressing the ctrl key, enter the type ‘once’
3. In type ‘once’, press any key(including control keys such as enter/ctrl/escape) except d  to enter the type ‘once’ again
3. In type ‘every’ or ‘once’, after pressing the d key, enter the type ‘normal’
4. In type ‘normal’, input ‘exit’ and then press Enter to exit this, reopen this, everything is ok.

So, I guess is it caused by pressing ctrl+d to exit this?
