### ISSUE TITLE
Does alacritty support ligatures and boxdrawings

### ISSUE THREAD

**Issue by ashincoder** [alacritty/alacritty#5245]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: ArchLinux
Version: 0.8.0
Linux/BSD: X11. Picom and XmonadWM
Font : `JetBrainsMono Nerd Font`

Does the git alacritty support ligatures and boxdrawings and braille characters.
I use JetBrains Mono Nerd Font. It doesn't render like kitty or my patched st does. I really prefer alacritty over kitty as it is written in rust and fast. But the only thing bothering me is the character rendering issue

**Comment by christianparpart** [comment]
Nope it doesn't support Ligatures, and most likely will never be (the main ticket was even locked and flagged as spam, lol), as it does require some more advanced (but solvable) text shaping techniques the developers are reluctant to implement as it *will* increase performance. if [braille characters](https://www.fileformat.info/info/unicode/block/braille_patterns/list.htm) such as U+281F I do think it does (it's single codepoint, it's just like any other codepoint then, even wcwidth is N/1). Boxdrawings I'm not sure I do understand correctly, but the font file comes with box drawing characters and they are no different to textual glyphs. 

> I use JetBrains Mono Nerd Font. It doesn't render like kitty or my patched st does

Screenshots :-)
p.s.: I'm also using the same font.

**Comment by ashincoder** [comment]
Actually I just installed alacritty from the aur from source and it does support braille and boxdrawings

**Comment by ashincoder** [comment]
[here](https://ibb.co/0YLgwJ3)

**Comment by ashincoder** [comment]
(https://ibb.co/HYr5Hw2)
