### ISSUE TITLE
incorrect position of blocks

### ISSUE THREAD

**Issue by ashincoder** [alacritty/alacritty#5248]
Hello I am using Arch Linux.
My version of alacritty is directly from the branch built from source.
In Alacritty my unicode block is not in right positon. The powerline in vim is not in correct position here is the Screenshot.And also the header show some line in between. Please help me.

My glyph offsets are:

``` glyph_offset:
    x: 0
    y: 0
```

[Screenshot](https://github.com/ashincoder/dotfiles/blob/master/.screenshots/alacritty.png)

**Comment by chrisduerr** [comment]
That's up to your font.

**Comment by ashincoder** [comment]
No I am using jetbrains mono nerd font

**Comment by ashincoder** [comment]
Kitty and my build of st renders it well.
