### ISSUE TITLE
alacritty crashed when adjust window tiling

### ISSUE THREAD

**Issue by lfishRhungry** [alacritty/alacritty#5253]
i can not be sure where the bug is on.
when i open tmux in alacritty, and use neovim. if tiling the window to left or right, alacritty will be closed with pressing any key after that.
i dont know whats wrong with that. this will not happen when i just using tmux or using neovim. and this will not happen when i adjust window with other policy.

and my shortcut to tiling window left or right is meta+left or meta+right.i use kde in manjaro

**Comment by chrisduerr** [comment]
Were there any unicode characters visible at the time?

**Comment by lfishRhungry** [comment]
> Were there any unicode characters visible at the time?

yes, i tried it just now. the bug happens when use neovim to edit a file with unicode characters visible in tmux.

**Comment by chrisduerr** [comment]
Fixed in latest master.
