### ISSUE TITLE
Improper rendering during `rustup update`

### ISSUE THREAD

**Issue by kirawi** [alacritty/alacritty#5254]
### System

OS: Windows
Version: 0.8.0

#5001 
#2284

This _is_ an alacritty issue because it _only_ happens on alacritty, I don't have any problems with any other terminal emulator.

**Comment by chrisduerr** [comment]
> This is an alacritty issue because it only happens on alacritty

It's not.

**Comment by kirawi** [comment]
> > This is an alacritty issue because it only happens on alacritty
> 
> It's not.

Explain?

**Comment by kirawi** [comment]
> > This is an alacritty issue because it only happens on alacritty
> 
> It's not.

I apologize for my rudeness, you were correct that it was indeed something on rustup's side. I have a PR to fix it that I'm working on that will hopefully resolve it in the future.
