### ISSUE TITLE
colour for broken symlink

### ISSUE THREAD

**Issue by boydkelly** [alacritty/alacritty#5255]
### System

OS: Linux
Version: alacritty 0.8.0
Fedora Wayland Gnome

I've tried a dozen or so colour schemes and they all work, but not  a single one displays a broken link in a different colour than a 'normal' link.   
Using gnome terminal for example with solarized light theme shows a broken symlink in red.   But in alacritty the broken link is the same colour as a working link.

Is this something that alacritty doesn't (yet) support?

**Comment by chrisduerr** [comment]
This is completely unrelated to Alacritty.

**Comment by boydkelly** [comment]
Thanks for the insight.
