### ISSUE TITLE
Alacritty issues with ANSI in some TUI programs in Windows

### ISSUE THREAD

**Issue by pablogipi** [alacritty/alacritty#5256]
Hello.
I was testing Alacritty in Windows and I found that pretty much all the my command line tools tha tuses a text UI, TUI, like broot, or gitui have issues drawing the UI.
Two examples comparing with windows CMD:
![image](https://user-images.githubusercontent.com/69514972/122549105-a6733b80-d021-11eb-9a2a-c05be51d113c.png)

![image](https://user-images.githubusercontent.com/69514972/122549176-b8ed7500-d021-11eb-85f5-509d5402834f.png)

It looks like issues drawing some ANSI characters any ideas what can cause it?
I'm using the default config file, pretty much all commented.

### System

OS: Windows 10
Version: alacritty 0.8.0 (a1b13e6)

Thanks!

**Comment by chrisduerr** [comment]
Whatever is emitting escapes, isn't doing so correctly for you. This has nothing to do with Alacritty.

**Comment by pablogipi** [comment]
Thanks chrisduerr .
Well, I'm putting the issue because these examples all works fine in  CMD, Powershell, cmder/conemu, Mintty.
Basically in al the terminals I have in Windows except in Alacritty.
Hence my question.

**Comment by chrisduerr** [comment]
Unfortunately that's par for the course with Windows.

**Comment by pablogipi** [comment]
Well after been suffering this all the time I found this: https://github.com/alacritty/alacritty/issues/4794
I don't think this is problem with _Windows_ is basically Alacritty sticking to an official API that has well known problems (ConHost) rather using an API that is also **maintained by Microsoft** and extensively used in other similar applications.
I love Alacritty, but sometimes I don't really understand the rigidness of some of the people in charge of the project.
