### ISSUE TITLE
Question concerning preview image

### ISSUE THREAD

**Issue by leontepe** [alacritty/alacritty#5262]
I was wondering what type of software was run in the preview image of Alacritty in this repo ([link](https://user-images.githubusercontent.com/8886672/103264352-5ab0d500-49a2-11eb-8961-02f7da66c855.png)). Is it Neovim? If so, which plugins? Which themes are used?

It looks pretty cool.

**Comment by chrisduerr** [comment]
Yes, that's neovim with my own theme and airline.
