### ISSUE TITLE
padding x > 255 produces error

### ISSUE THREAD

**Issue by asterandex** [alacritty/alacritty#5264]
Linux
0.7.2.
Wayland

The maximum value for padding seems to be 255. Choosing 256 and higher produces the error:
"Config error: x: invalid value: integer `256`, expected u8"
Using a higher padding can enhance the readability of text in a text editor like vim due to shorter lines.

**Comment by chrisduerr** [comment]
There's absolutely no reason why anyone would ever choose a padding even close to 255, so I see no reason to change this.

**Comment by ags799** [comment]
Ran into this myself on an ultrawide monitor. When I'm editing one buffer with no other windows open, it's common for 2/3 of the screen width to go unused.
