### ISSUE TITLE
Alacritty freezes & crashes under heavy escape-sequence-coded color output on Windows

### ISSUE THREAD

**Issue by skyline75489** [alacritty/alacritty#5266]
### System

OS: Windows 19043.1052
Version: 0.8.0 from https://github.com/alacritty/alacritty/releases/tag/v0.8.0

### Logs

I would love to provide any log if necessary.

### Steps to reproduce

Download & run this benchmark software https://github.com/cmuratori/termbench/releases/tag/V1 

Alactritty freezes then crashes:

![image](https://user-images.githubusercontent.com/4710575/122757490-4652f280-d2ca-11eb-8c21-de0d0eddcce0.png)

---

What's confusing to me is that even I use a smaller window size, it still crashes. It never made to (collecting 100%). And this always repro on my machine.

 I'm not sure if this's a driver issue or something of my configuration.

This does NOT happen on Linux. On Linux Alacritty kills in this benchmark with fantastic numbers.

**Comment by skyline75489** [comment]
Also really want to say "thanks" to all Alacritty developers for making & improving Alacritty. It's one of the best cross-platform terminals that I've used.

**Comment by chrisduerr** [comment]
What is the error saying? Is it actually crashed, then there should be a backtrace available. Or is it just frozen?

**Comment by skyline75489** [comment]
The terminal just freezes, with the output stuck. Then I tried to click the ‘X’ to close the window, the crash on the screenshot happened

**Comment by skyline75489** [comment]
Sometimes it stuck at 12%, sometimes stuck at 20%. Seems totally random. But never seen it make it to 100%.

**Comment by chrisduerr** [comment]
Can you check where it is stuck at please?

**Comment by skyline75489** [comment]
Initial debugging shows that "PTY reader" thread stuck at here `GetQueuedCompletionStatusEx`, which seems to be waiting indefinitely: 

![image](https://user-images.githubusercontent.com/4710575/123374865-65979b80-d5ba-11eb-9ffb-97052daed6ac.png)

Full stack:

![image](https://user-images.githubusercontent.com/4710575/123374959-852ec400-d5ba-11eb-9502-d2652f3aef22.png)

**Comment by chrisduerr** [comment]
The location where Alacritty is stuck would be much more useful than the location of its depedencies. Seems to be somewhere in the Windows tty module? Sounds like it is a ConPTY thing.

**Comment by skyline75489** [comment]
Yeah I think it might be ConPTY thing. Will try to dig later.

**Comment by skyline75489** [comment]
Hi @chrisduerr  turns out it's a bug in `mio-anonymouse-pipes`. The PR I linked fixed this issue. Thanks for the patient guidance :)

**Comment by chrisduerr** [comment]
That's somewhat surprising, thanks for looking into it.

**Comment by skyline75489** [comment]
The fact that Windows Terminal works fine somewhat rules out ConPTY's fault. However even with the fix, the performance on Windows is still not good, because of ConPTY slowness. But that's another issue.

@chrisduerr do you happen to know the author of `mio-anonymouse-pipes` @davidhewitt ? So that we can merge this change soon? I can also repro this bug with vtebench (running in WSL), so I think it's actually more common that I thought.

**Comment by chrisduerr** [comment]
> The fact that Windows Terminal works fine somewhat rules out ConPTY's fault.

The ConPTY version used by Windows Terminal is **significantly** different from Alacritty's version.

> @chrisduerr do you happen to know the author of mio-anonymouse-pipes @davidhewitt ?

I don't actually have much hope, but I'd like to give the PR a chance at least. Worst case the crate can be easily forked and we can move it to the Alacritty organization. IIRC there's also been the suggestion to replace this crate and iirc there should even be a code comment in the windows pty somewhere, but that would require someone who's actually interested in working on Windows.

**Comment by skyline75489** [comment]
> The ConPTY version used by Windows Terminal is significantly different from Alacritty's version.

Yea, it is. But the newer version of ConPTY bundled in Windows Terminal isn't really too fast, either 😅 . 

I am a casual contributor of the Windows Terminal project so I know a bit in this specific area. If there's anything I can help regarding ConPTY & related., I will see what I can do within my power.

**Comment by davidhewitt** [comment]
Hi folks, just checking in to say I've seen the PR and will try to get the fix out soon.

> Worst case the crate can be easily forked and we can move it to the Alacritty organization. IIRC there's also been the suggestion to replace this crate and iirc there should even be a code comment in the windows pty somewhere, but that would require someone who's actually interested in working on Windows.

@chrisduerr I'd be very happy to transfer ownership of the crate to the alacritty org, if you want that? As far as I know the crate has no dependents other than alacritty, and I was kinda hoping https://github.com/microsoft/terminal/issues/262 would eventually happen anyway so the crate could be thrown out in favor of a `NamedPipe` implementation like we used to use with winpty.

For the record I'm still a heavy user of alacritty on both Windows and Linux, just it's more than good enough for my daily driver so I haven't had urgency to push changes. Do continue to ping me any time if there's things needed from me! (These days all my OSS free time is devoted to https://github.com/PyO3/pyo3.)

> I am a casual contributor of the Windows Terminal project so I know a bit in this specific area. If there's anything I can help regarding ConPTY & related., I will see what I can do within my power.

@skyline75489 that's really cool! A long time ago I looked into implementing some of the things we wanted upstream, but large Visual Studio projects aren't my strong suit and I gave up trying to get the darn thing to build. If we had an issue tracking the things we wanted from upstream conpty perhaps we can coordinate on them together? As above not sure I'll achieve much but I'm at least somewhat familiar with the current limitations conpty puts on us.

**Comment by skyline75489** [comment]
> If we had an issue tracking the things we wanted from upstream conpty perhaps we can coordinate on them together?

Sure. I think the terminal team welcome all kinds of contributions. For example the author of ConEmu will somethings show up in the Windows Terminal repo to provide advices. And ConEmu is also a popular product that uses ConPTY. Normally you can just file an issue in the terminal [repo](https://github.com/microsoft/terminal) and people will usually respond. 

Also I want to point out that ConPTY is an OS-level thing and carries a lot of legacy win32 burdens with it, so the progress might be slower than people would expect.

**Comment by chrisduerr** [comment]
> @chrisduerr I'd be very happy to transfer ownership of the crate to the alacritty org, if you want that?

Considering that Alacritty is the only user I know of, that would make some sense. But I'd never suggest transfering stuff away unless you actually see a benefit in it yourself. As long as you're responding to PRs I have no problem with it being outside the org.

**Comment by davidhewitt** [comment]
Cool, I'll keep responsibility for the crate for now. As previously said, consider me a lurking member of the community, but I'm happy to come active if you ever ping me!

Btw, I was wondering if you plan to update to mio 0.7 at some point? I can update `mio-anonymous-pipes` whenever you need that.

Just released the 0.2 version!

**Comment by chrisduerr** [comment]
> Btw, I was wondering if you plan to update to mio 0.7 at some point?

Easier said than done unfortunately.

**Comment by davidhewitt** [comment]
Haha I figured; I'm aware it's quite a big changeset!

**Comment by skyline75489** [comment]
Thanks guys for the awesome work! Looking forward for the fix to land 😄
