### ISSUE TITLE
Error creating GL context; Received multiple errors. Errors: `[OsError("eglInitialize failed"), OsError("GL context creation failed")]`

### ISSUE THREAD

**Issue by Jimmysit0** [alacritty/alacritty#5269]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux
Version: alacritty 0.7.1 (a852eb85)
Linux/BSD: X11, bspwm

### Logs

libGL error: MESA-LOADER: failed to open iris: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/iris_dri.so) (search paths /usr/lib/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/iris_dri.so) (search paths /usr/lib/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/swrast_dri.so) (search paths /usr/lib/dri)
libGL error: failed to load driver: swrast
libEGL warning: MESA-LOADER: failed to open iris: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/iris_dri.so) (search paths /usr/lib/dri)

libEGL warning: MESA-LOADER: failed to open iris: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/iris_dri.so) (search paths /usr/lib/dri)

libEGL warning: MESA-LOADER: failed to open swrast: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/swrast_dri.so) (search paths /usr/lib/dri)

libEGL warning: MESA-LOADER: failed to open iris: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/iris_dri.so) (search paths /usr/lib/dri)

libEGL warning: MESA-LOADER: failed to open iris: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/iris_dri.so) (search paths /usr/lib/dri)

libEGL warning: MESA-LOADER: failed to open swrast: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/swrast_dri.so) (search paths /usr/lib/dri)

Created log file at "/tmp/Alacritty-167049.log"
[2021-06-22 17:01:49.517014635] [ERROR] [alacritty] Alacritty encountered an unrecoverable error:

                                                    	Error creating GL context; Received multiple errors. Errors: `[OsError("eglInitialize failed"), OsError("GL context creation failed")]

Here's /tmp/Alacritty-167049.log: [2021-06-22 17:01:49.517014635] [ERROR] [alacritty] Alacritty encountered an unrecoverable error:

                                                    	Error creating GL context; Received multiple errors. Errors: `[OsError("eglInitialize failed"), OsError("GL context creation failed")]`.

In case this is needed (because it seems to be a gcc-libs problem), my gcc-libs version is: `gcc-libs=10.2.0-6`

**Comment by Jimmysit0** [comment]
I tried updating to alacritty-0.8.0-1, but doesn't seem to work.

**Comment by chrisduerr** [comment]
Sounds like your GPU doesn't support Alacritty.

**Comment by Jimmysit0** [comment]
My GPU does support alacritty, I've been using it for some months, in different distros. I'm sure it's not a GPU problem.

**Comment by Jimmysit0** [comment]
@chrisduerr pinging you just in case.

**Comment by chrisduerr** [comment]
You might have to update your driver then. Drivers can change and that might change the OpenGL support.

**Comment by Jimmysit0** [comment]
Just did that... Didn't work. @chrisduerr

**Comment by AGhost-7** [comment]
Just ran into this today as well. Fails to run on vanilla Ubuntu.
