### ISSUE TITLE
Icon on the prompt are misplaced while using powerlevel10k

### ISSUE THREAD

**Issue by Jasylum** [alacritty/alacritty#5270]
### System

OS: Linux
Version: 
Linux/BSD: xorg/arch
Version: alacritty --version output:
`alacritty 0.8.0 (a1b13e68)`

So while using p10k in alacritty there seems to be a small glitch where the icons of the prompt are misplaced of their original position.
![2021-06-23-211641_1920x1080_scrot](https://user-images.githubusercontent.com/52153618/123126410-15f58a80-d469-11eb-9195-778135399400.png)

**Comment by chrisduerr** [comment]
This is to be expected. Powerline prompt symbols are somewhat of a hack.
