### ISSUE TITLE
Respond to XTVERSION query

### ISSUE THREAD

**Issue by dankamongmen** [alacritty/alacritty#5273]
It would be great if Alacritty responded to `XTVERSION` queries with its name and version. Something like

`\33P>|Alacritty(0.9.0-dev)\33\\`

would be delightful, but feel free to explore the creative boundaries of the escape sequence (it ought be a DSR, at least).

> CSI > Ps q
          Ps = 0  ⇒  Report xterm name and version (XTVERSION).  The
          response is a DSR sequence identifying the version: DCS > |
          text ST

some examples:

`\33P>|kitty(0.21.1)\33\\`
`\33P>|XTerm(366)\33\\`
`\33P>|contour 0.2.0-unreleased-master-96b8f89\33\\`

I use this in Notcurses to determine capabilities beyond what terminfo and other queries get us.

**Comment by dankamongmen** [comment]
looking through the source, it appears you do report the version via Secondary Device Attributes in `identify_terminal()`. unfortunately, this doesn't tell us it's alacritty, and the version number is a bit wonky:

```
[schwarzgerat](0) $ echo -e '\e[>0c'

[schwarzgerat](0) $ 0;1301;1c
```
SDA of course has a required format for its response, whereas `XTVERSION` just wants a string. so if i could get this, i'd be appreciative. i can probably write up the patch if you'd like.

**Comment by dankamongmen** [comment]
yeah let me take a swing at this.

**Comment by dankamongmen** [comment]
i think i've got it working! PR incoming. this is my first public rust, so be gentle, please =]

**Comment by dankamongmen** [comment]
```
[schwarzgerat](0) $ echo -e '\e[>0q'

[schwarzgerat](0) $ Alacritty(0.13.1-dev)
```

sweet!

**Comment by chrisduerr** [comment]
As stated in previous issues, I have no interest in supporting this.

**Comment by dankamongmen** [comment]
I couldn't find any other issues with "xtversion" in them -- perhaps some speak of it obliquely -- so for anyone reading this bug in the future, the relevant reference is probably https://gitlab.freedesktop.org/terminal-wg/specifications/-/merge_requests/8. Basically, XTVERSION would be a key into client-managed "profiles", the proliferation of which @chrisduerr would presumably like to prevent (correct me if I'm wrong).

I'm likewise all for query-driven capability discovery, but am using all half-measures I can find.

In any case, I respect your decision, and do not intend to crap up your issue tracker -- just wanted to complete the record here.

**Comment by chrisduerr** [comment]
Yeah, that's exactly the problem. Trying to identify the terminal and its exact version is the exact opposite of where I'd like terminal feature detection to go. Existing solutions already show that this will only lead to more and more abuse.

The argument is that this is useful for client applications to work around bugs in specific terminal emulator versions, at least that's why VTE asked me to support it. But those bugs should obviously be reported and fixed, not worked around.

**Comment by christianparpart** [comment]
I see `XTVERSION` not as a way to detect feature but the name and VERSION of the running terminal. And in that regard at least i do not know of anything better than this sequence. Or is there?

**Comment by j4james** [comment]
The problem is that `XTVERSION` *is* being used as a way to detect features. I came across an app recently that refuses to work with anything other than iTerm2. It's somewhat understandable, since it relies on a bunch of iTerm2 sequences, but even if another terminal implemented every single one of iTerm2's extensions, it still wouldn't work without also faking the `XTVERSION` response.

Notcurses does the same sort of thing to a lesser extent. And the more apps that start using `XTVERSION` like this, the more likely it'll just go the way of the browser `User-Agent` string, and the `TERM` variable. If your terminal is less well known, you're often better off claiming to be someone else, rather than replying accurately to these queries.

**Comment by chrisduerr** [comment]
> I see XTVERSION not as a way to detect feature but the name and VERSION of the running terminal. And in that regard at least i do not know of anything better than this sequence.

I see no reason why anyone would ever need to detect the exact name and version of a terminal emulator.

**Comment by christianparpart** [comment]
> I see no reason why anyone would ever need to detect the exact name and version of a terminal emulator.

https://github.com/dylanaraps/neofetch

**Comment by chrisduerr** [comment]
Yeah, that's not a usecase lol.

**Comment by christianparpart** [comment]
> Yeah, that's not a usecase lol.

Sorry to ask a like a little idiot here. But how can that not be a Usecase? Neofetch is displaying the terminal name and with such a VT sequence reliably print the terminal version too.

**Comment by chrisduerr** [comment]
Having an escape sequence to query the name of the terminal emulator, to display it to yourself, is rather useless. You might as well just define it in the neofetch config directly. This doesn't provide any functionality that would be necessary for a terminal emulator, neofetch by itself doesn't provide much functionality at all. So no, this is not a reason to add this.

**Comment by dankamongmen** [comment]
> Notcurses does the same sort of thing to a lesser extent. And the more apps that start using `XTVERSION` like this, the more likely it'll just go the way of the browser `User-Agent` string, and the `TERM` variable. If your terminal is less well known, you're often better off claiming to be someone else, rather than replying accurately to these queries.

to be more precise, i use terminfo and direct capability queries *far* more than `XTVERSION`. and anything that moves into such, i will happily eliminate the `XTVERSION` equivalent.

https://nick-black.com/dankwiki/index.php?title=Terminfo i'd love to see all of these become terminfo extensions.

**Comment by dankamongmen** [comment]
> to be more precise, i use terminfo and direct capability queries _far_ more than `XTVERSION`. and anything that moves into such, i will happily eliminate the `XTVERSION` equivalent.
> https://nick-black.com/dankwiki/index.php?title=Terminfo i'd love to see all of these become terminfo extensions.

indeed, in the past two weeks i've sent at least five PRs updating various terminfo sources, including one to this very repository. i <3 libterminfo. except where terminal authors don't bother to use it.

**Comment by chrisduerr** [comment]
Regardless of using it or not, you'll never get all of those extensions upstreamed to ncurses anyway.

**Comment by dankamongmen** [comment]
> Yeah, that's not a usecase lol.

i'm not asking you to revisit this or anything, but one very real one just came up: when i get a bugreport regarding alacritty, i don't get the version automatically as part of the output, and instead have to ask the submitter "and what version of alacritty were you running", and who knows if they give me the right answer. whereas with everything implementing XTVERSION, it says right up on the top line, "Notcurses 4.2.0 on ShiTTY 666.666.666" or whatever.

> Regardless of using it or not, you'll never get all of those extensions upstreamed to ncurses anyway.

i know =[

**Comment by chrisduerr** [comment]
> i'm not asking you to revisit this or anything, but one very real one just came up: when i get a bugreport regarding alacritty, i don't get the version automatically as part of the output, and instead have to ask the submitter "and what version of alacritty were you running", and who knows if they give me the right answer. whereas with everything implementing XTVERSION, it says right up on the top line, "Notcurses 4.2.0 on ShiTTY 666.666.666" or whatever.

That should be much more my problem than yours. And I personally prefer it this way.
