### ISSUE TITLE
YouCompleteMe indents text on vim

### ISSUE THREAD

**Issue by potuz** [alacritty/alacritty#5285]
### System
Arch linux 5.12.12-arch1-1 x86_64 GNU/Linux
alacritty 0.8.0 (a1b13e68)
i3, no compositor. 

### The issue
When running vim with YouCompleteMe, and typing a syntax error for example. YouCompleteMe will add `>>` characters to the first two columns that are highlighted with inverse text. After you fix the error, those characters disappear. This is the correct behavior and works fine on termite. 

When running on alacritty, the first columns are not highlighted (I can't get any of the inverse text folds to show on vim as left in [this comment](https://github.com/alacritty/alacritty/issues/3402#issuecomment-869137291) ) and the characters `>>` are added to the actual text, shifting the text by two characters. When fixing the error, text shift backs left except those lines that had the `>>` character remain shifted by two characters so that the whole indentation is destroyed. 

This is fixed by the workaround in the above issue of setting `term = xterm-256color` within vim, but is not fixed by the tip of setting `t_8f` and `t_8b` as in the third comment.

**Comment by chrisduerr** [comment]
Not an Alacritty issue.
