### ISSUE TITLE
Cursor shape does not change properly inside neovim

### ISSUE THREAD

**Issue by yofriadi** [alacritty/alacritty#5287]
Hi, I need help.
cursor shape is not properly displayed inside neovim.
changing from normal mode to insert mode is only showing whats on alacritty config `cursor.style.shape`.

*notes : only happen inside tmux

OS: Linux
Version: 0.8.0
Linux: X11, BSPWM (idk I use archcraftOS)

**Comment by chrisduerr** [comment]
If it only happens inside tmux, it's probably a tmux issue.
