### ISSUE TITLE
pixelated text when opening alacrity

### ISSUE THREAD

**Issue by lukehodges** [alacritty/alacritty#5289]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System
![image](https://user-images.githubusercontent.com/58270858/123679119-0eeec380-d83f-11eb-9006-d05650265a5b.png)
the text renders as an ultra low res pixelated format. idk if its my hardware or what
OS: Linux/BSD/macOS/Windows
Version: `alacritty --version` output
Linux/BSD: X11/Wayland, DE or Compositor and WM

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by chrisduerr** [comment]
This indicates that your GPU (driver) doesn't support the OpenGL version required by Alacritty. OpenGL 3.3+ support is required.

**Comment by lukehodges** [comment]
ty
