### ISSUE TITLE
Broken powerline style glyphs (possibly due to fontconfig update)

### ISSUE THREAD

**Issue by jayghoshter** [alacritty/alacritty#5294]
Powerline style glyphs don't work on my system on alacritty anymore after I just updated my system. Everything still works on termite and kitty.

Possibly relevant.
`upgraded fontconfig (2:2.13.93-4 -> 2:2.13.94-1)`

### System

OS: Arch Linux
Version: alacritty 0.8.0 (a1b13e68)
Linux/BSD: X11, i3, picom

### Screenshot of Issue 
![image](https://user-images.githubusercontent.com/29096953/123930290-2339da00-d97f-11eb-8ae3-9d5a5abba994.png)

### Reference in Termite
![image](https://user-images.githubusercontent.com/29096953/123930341-2e8d0580-d97f-11eb-90c5-b792b9d88334.png)

**Comment by chrisduerr** [comment]
As you've said yourself, you've just updated your system and fontconfig. Chances are your fontconfig fallbacks aren't returning the correct symbols.

**Comment by jayghoshter** [comment]
But it still works on termite and kitty.

**Comment by chrisduerr** [comment]
Different applications behave differently wrt font fallback. That is no surprise. Some applications also do not query the font for these symbols, in which case font fallback doesn't matter at all.

The Linux font fallback in Alacritty has been validated against the fallback lists of fontconfig several times, so far I'm not aware of any differences between Alacritty's fallback and the list provided by fontconfig itself.
