### ISSUE TITLE
Alacritty doesn't update existing instances when gnome text-scaling-factor is changed

### ISSUE THREAD

**Issue by justyn** [alacritty/alacritty#5303]
### System

OS: Linux
Version: 0.8.0
Linux/BSD: X11, i3, compton

### Issue

When it is started alactritty respects the current gnome text-scaling-factor.

This can be set with:

```gsettings set org.gnome.desktop.interface text-scaling-factor FACTOR```

eg:

```gsettings set org.gnome.desktop.interface text-scaling-factor 1.6```

But if the text-scaling-factor is changed then existing windows don't update.

My laptop internal screen has a much higher DPI than my external monitors. 
When I am using the laptop screen the text-scaling-factor is increased to compensate.

Most applications, including gnome-terminal and chromium based browsers, update immediately when the text-scaling-factor is changed.

Alacritty does not, and I haven't been able to work out a way to make it  refresh to respect the new value other than closing the window and opening a new one.

Would be great to see this functionality or at least a workaround.

Thanks.

**Comment by chrisduerr** [comment]
Live reload of configuration options like Xft.dpi on X11 is not supported.

**Comment by pauloromeira** [comment]
@justyn did you find any workaround?

@chrisduerr is there a command to manually reload it?

thanks!

**Comment by chrisduerr** [comment]
There is not. And it wouldn't help in this case either because Xft.dpi is obviously not coming from Alacritty's config.

**Comment by justyn** [comment]
@pauloromeira I'm afraid I didn't in alacritty - if you can use gnome-terminal on your system it works very well there.
