### ISSUE TITLE
VIM with vertical split does not move selection on scroll

### ISSUE THREAD

**Issue by itszn** [alacritty/alacritty#5306]
OS: Ubuntu 18.04.4
Alacritty Version: alacritty 0.8.0
VIM version: NVIM v0.4.4

When using vim with a vertical split, selected text will not move when the pane scrolls (using mouse). This causes the selection to reselect separate text on the screen, overwriting the selection buffer.

This only happens with a vertical split: no split or horizontal split work as expected (the selection moves with the pane)

Would it be possible to add an option to deselect on scroll? That would at least prevent the selection from being overwritten.

Before scroll:
![image](https://user-images.githubusercontent.com/1857794/124516494-9d5eca00-dd96-11eb-808f-44eac8e17ec0.png)
After scroll:
![image](https://user-images.githubusercontent.com/1857794/124516512-ab144f80-dd96-11eb-99da-4a238a4c8aa6.png)

**Comment by chrisduerr** [comment]
> Would it be possible to add an option to deselect on scroll? That would at least prevent the selection from being overwritten.

Nothing is scrolling here, so unfortunately it's not.

**Comment by itszn** [comment]
What about when the mousewheel is used?

Or potentially an option to not do the selection if the contents of the selection changes? This behavior is similar to other terminals.
