### ISSUE TITLE
Build failure on Ubuntu

### ISSUE THREAD

**Issue by Redxtorm** [alacritty/alacritty#5309]
I tried to install using the `cargo install alacritty` command on Kubuntu 20.04 but for some reason it fails to build.
Here is the terminal session

![Screenshot_20210706_235322](https://user-images.githubusercontent.com/38680006/124650140-02a9dc80-deb7-11eb-872b-d71c0d3e23f4.png)

**Comment by chrisduerr** [comment]
You're lacking depedencies.

**Comment by Redxtorm** [comment]
Thanks, I was able to manually build after reading `INSTALL.md`
