### ISSUE TITLE
Buffer selection to clipboard with vim/neovim + ALE/Syntastic

### ISSUE THREAD

**Issue by dragomang87** [alacritty/alacritty#5311]
When using vim/neovim with syntax checkers a 2-character column appears on the left of the buffer for marking lines with warnings/errors.
With `set mouse=a` the mouse should be able to select the contents of the file without the 2-character columns and yank the selection to the system clipboard so that it can be pasted into other programs with e.g. middle click. For the tests I temporarily removed my .vimrc and only set mouse=a manually.

**urxvt + vim**: mouse selects only content of the file and copies to clipboard.

**alacritty + vim**: mouse selects and copies also the content of the columns. Likely the interaction with the clipboard is correct, but the wrong selection hints at wrong interaction with alacritty.

**alacritty/urxvt + neovim**: mouse selects only content of the file but does not copy to clipboard. Likely badly configured interaction with the clipboard, but the correct selection hints at correct interaction with alacritty

**kitty + vim/neovim**: mouse selects only content of the file but does not copy to clipboard. ????? #confused

Is the wrong selection in vim an alacritty problem? a vim problem? both?

### System

OS: Arch Linux
Version: alacritty 0.8.0 (a1b13e68)
Linux/BSD: Wayland, Sway, wl-clipboard, VIM 8.2, NVIM 0.5.0

### Logs

Crashes: none
Font/Terminal size: probably irrelevant
Keyboard and bindings: probably irrelevant

**Comment by chrisduerr** [comment]
You probably didn't activate mouse mode in vim.

**Comment by dragomang87** [comment]
is mouse mode different from mouse=a?

**Comment by chrisduerr** [comment]
In vim you have to set `ttymouse=sgr` or something like that.

**Comment by dragomang87** [comment]
amazing, could not find this fix anywere, thanks
