### ISSUE TITLE
Alacritty crashes after install on Windows 7 64-bit with error dialogue

### ISSUE THREAD

**Issue by Calilasseia** [alacritty/alacritty#5312]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Windows 7 64-bit
Alacritty Version: 0.8.0

After using the msi installer to install Alacritty, and attempting to run the program, the program exits with the following error dialogue:

"The procedure entry point CreatePseudoConsole could not be located in the dynamic link library KERNEL32.dll"

![Alacritty Fail Dialogue](https://user-images.githubusercontent.com/86096083/124826123-63dfb780-df6c-11eb-84ca-899bea29847a.jpg)

**Comment by chrisduerr** [comment]
Windows 7 is not supported.
