### ISSUE TITLE
Passing multiple commands when using the -e flag  on windows

### ISSUE THREAD

**Issue by NadimJrObeid** [alacritty/alacritty#5317]
OS: Windows 10
Version: alacritty 0.8.0 (a1b13e6)

When I am passing multiple commands using -e on windows from cmd, the first command output is printed in alacritty while the second command output is printed in cmd.  Here is the command that I am running

start alacritty.exe --hold -e cmd /c  echo "this is" && echo "a test"

output in the attached image

![image](https://user-images.githubusercontent.com/42421041/125120723-8c49ec00-e0fb-11eb-9f5e-94020f2a52f9.png)

**Comment by chrisduerr** [comment]
Just escape your entire string? Not sure how this is related to Alacritty…
