### ISSUE TITLE
Alacritty doesn't work with window manager like leftwm

### ISSUE THREAD

**Issue by winston0410** [alacritty/alacritty#5318]
I tried to use alacritty with a window manager in NixOS. The window manager that I uses is `leftwm`.

Alacritty does start up correctly, but I am unable to switching workplace by clicking `command + <number>`, but when I switch to other terminal like `kitty` and `wezterm`, they works fine.

A reference of an issue that I have previously started in `leftwm` as a reference:

https://github.com/leftwm/leftwm/issues/415

### System

OS: Linux/BSD/macOS/Windows Linux, NixOS 21.05
Version: `alacritty --version` output 0.8.0
Linux/BSD: X11/Wayland, DE or Compositor and WM

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by chrisduerr** [comment]
Alacritty has nothing to do with your window management.
