### ISSUE TITLE
Frequently requires fontconfig cache refresh to render terminus bitmap font properly

### ISSUE THREAD

**Issue by FichteFoll** [alacritty/alacritty#5321]
For a couple weeks now (maybe months even?), every few days, sometimes even multiple times a day, when I open alacritty it fails to find my configured font and looks like this:

![2021-07-10_15-17-39](https://user-images.githubusercontent.com/931051/125164345-0a58d200-e192-11eb-885a-8cfa0f175ef6.png)

Running `fc-cache -f` and restarting it then makes it pick up my configured font properly.
This occurs on two systems with a very similar setup and I have not yet been able to determine what exactly triggers it, but it seems to have been very consistend after a system package update.

Here is what it should look like:

![2021-07-10_15-19-42](https://user-images.githubusercontent.com/931051/125164459-94089f80-e192-11eb-8b92-40d9ade3b06f.png)

My font configuration is as follows ([full file](https://github.com/FichteFoll/dotfiles/blob/2d1f23c5b46f95bccecb4d8fc3cc0e0986db8786/alacritty/.config/alacritty/alacritty.yml)):

```yaml
font:
  normal:
    family: xos4 Terminus
  size: 10
```

### System

OS: Arch Linux
Version: 0.8.0
Linux/BSD: X11, i3, picom, amdgpu

### Logs

Font/Terminal size: Will try to remember the next time this occurs.

**Comment by chrisduerr** [comment]
Sounds like a fontconfig problem. Your font might have been updated while starting Alacritty.

**Comment by FichteFoll** [comment]
> Your font might have been updated while starting Alacritty.

How does that happen? How can I prevent that from happening? I installed it with my system packager, which says it hasn't been updated in 4 months.

I'll try using "Terminus" for the font name, since that appears to refer to the .otb version while "xos4 Terminus" is the .pcf version.

**Comment by FichteFoll** [comment]
Hasn't occured since despite me doing a system update and a reboot, so I consider this to be the solution.
