### ISSUE TITLE
Just a question: Adding current process to window title.

### ISSUE THREAD

**Issue by cocoonkid** [alacritty/alacritty#5323]
I tried finding more information but unfortunately not that successful.

```
function set_win_title(){
    echo -ne "\033]0; $USER $HOST $PWD \007"
}
```

That works. But how would I add the currently running process? 

I also want to only add brackets when the process is done.

Like explained here: https://stackoverflow.com/questions/16973785/how-to-set-the-terminal-title-to-show-the-current-running-command-while-its-run

Thanks for your help in advance.

**Comment by chrisduerr** [comment]
That depends on your shell and has not much to do with Alacritty.
