### ISSUE TITLE
issue: coloring of padding

### ISSUE THREAD

**Issue by Soziopath** [alacritty/alacritty#5325]
i have an issue when opening neovim for example or any other terminal application.
the padding on the edges has the color of my terminal background.

i have tried the following settings in alacritty.yml:
`padding:`
`x: 0`
`y: 0`

`dynamic_padding: on`
`dynamic_padding: off`

i hope there is a way to either color the padding based on the adjacent cell or get rid of the padding entirely.

and i dont want to set the same background in my terminal and neovim.

![alacritty](https://user-images.githubusercontent.com/9363020/125197378-aac7f880-e25d-11eb-9c7a-d19dc0843efc.png)

### System

OS: Linux
Version: alacritty 0.8.0 (a1b13e68)
Manjaro i3

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by chrisduerr** [comment]
The padding will always have the color of your terminal background, that's working as intended.
