### ISSUE TITLE
Support Alacritty on iPad

### ISSUE THREAD

**Issue by mauricioklein** [alacritty/alacritty#5328]
Hey there!

Has anyone succeeded to run Alacritty on an iPad?

It might look as a super weird idea, but I run part of my personal workload on EC2 instances, so having Alacritty + Tmux on iPad would basically transform it in a super portable working station 🙂

Thanks!

**Comment by chrisduerr** [comment]
Fundamentally there's nothing stopping anyone from doing so other than potential OpenGL support issues. Not something that any work is going to go into though.
