### ISSUE TITLE
Add Option to set window Icon

### ISSUE THREAD

**Issue by tglman** [alacritty/alacritty#5332]
Hi,

Checking the code I noticed that the Icon of the window is hard coded to Alacritty one, I use Alacritty to spawn single windows of cli/tui applications like Weechat it would be useful to be able to customize the icon as well trough configuration or cli parameter, so different terminal can be spawn with different icons and be more easily recognizable 

Is any plan to do that ? or any reason to not have this capability ?

Regards

**Comment by chrisduerr** [comment]
No plan, no. Alacritty comes with the Alacritty icon.
