### ISSUE TITLE
Random Characters printed with fish shell

### ISSUE THREAD

**Issue by Antonio-Bennett** [alacritty/alacritty#5333]
Hi, so before switching to alacritty I used the Windows Terminal with fish. After switch sometimes random characters would be printed after a command. These characters shouldn't be there. I also noticed it might be because of resizing? Sometimes if it pops up in windowed mode and I maximize alacrity the characters go away. However if I set maximized as the default you will see that when I start vim it recognizes the terminal as still being in windowed mode

![image](https://user-images.githubusercontent.com/31296212/125743202-f95a57a0-878c-4c61-adb8-076185b59ed6.png)
![alacritty1](https://user-images.githubusercontent.com/31296212/125743266-ddd2e716-7603-4714-8686-625c06de8ee1.JPG)
![image](https://user-images.githubusercontent.com/31296212/125746297-55a8a37d-10e2-453c-8e92-04950d4cad36.png)

### System

OS: Windows WSL
Version: alacritty 0.8.0 (a1b13e6)
Linux/BSD: Ubuntu 20.10

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: 15 font size
Keyboard and bindings: `alacritty --print-events`

**Comment by chrisduerr** [comment]
Those look like truncated escape sequences. Likely due to ConPTY but not related to Alacritty.

**Comment by ryancerium** [comment]
@Antonio-Bennett , did you ever get anywhere with this?  I'm using Fish too, and I'm getting the same stray `l` and `h` characters that also disappear when I resize the window.  It doesn't happen when I use Bash.

I think it _might_ have something to do with the way Fish prints application output.  I'm consistently getting the `l` on the beginning of the command, i.e. before the output begins, kind of like a `\r` character moves output to the beginning of the line, then prints the `l`.  The `h` is consistently at the beginning of the last line of application output, 

```bash
$ lll  # <- this was just an 'll` command
total 0
-rw-r--r-- 1 rphelps rphelps 0 Feb  8 13:39 1
-rw-r--r-- 1 rphelps rphelps 0 Feb  8 13:39 2
-rw-r--r-- 1 rphelps rphelps 0 Feb  8 13:39 3
h # <- here's the trailing 'h'

$ lslh # <- this was just an `ls` command
1  2  3
```

**Comment by Antonio-Bennett** [comment]
@ryancerium Hey Ryan no I haven't gotten anywhere with this I kinda just deal with it unfortunately 😅
