### ISSUE TITLE
wierd loss of character input encountered, reproduce unknown

### ISSUE THREAD

**Issue by adsick** [alacritty/alacritty#5336]
this is a bug, but I'm sorry, I have no detail on how to reproduce it.

the symptom: the terminal does not type characters when I type them, Ctrl+Shift+Space works tho
the heal: Ctrl+C saved me.

### System
OS: Pop!_OS (ubuntu-like linux)
Version: 0.8, X11, Gnome desktop environment

**Comment by chrisduerr** [comment]
Sounds like you're running some sort of terminal application while doing this? Why do you think this is an Alacritty issue?

**Comment by adsick** [comment]
I was performing basic bash commands and it should not block. I just did ```echo hello >> hello.txt``` [enter]
then ```cat hello.txt```
it printed hello as expected, then prompt.
then I've switched to another application, and returned after some time - I saw the prompt and the cursor, they were normal but I was unable to type anything.

**Comment by chrisduerr** [comment]
Did the characters you entered while Alacritty was unresponsive show up after it became responsive again?

**Comment by adsick** [comment]
No, I've did a ```Ctrl+C```, and it prompted with empty input line.

**Comment by chrisduerr** [comment]
If a Ctrl+C fixed it, that sounds like a shell thing. How often does this happen?

**Comment by adsick** [comment]
at the time it happened once, but I don't think that that is a normal thing.

**Comment by chrisduerr** [comment]
Going to close this issue then until there's some evidence that this is related to Alacritty.

**Comment by chrisduerr** [comment]
Just to be clear, this sounds a lot like you just pressed Ctrl+S, which is working exactly as expected.
