### ISSUE TITLE
Build is broken on windows

### ISSUE THREAD

**Issue by tupos** [alacritty/alacritty#5338]
Hello,

It seems that 2de20378acbb04b2c1408fe715a9642eaa3010ed broke a windows build.

If I just do
```shell
cargo build --release
```

the build fails with 

```
  --- stdout
  cargo:rustc-env=GIT_HASH=e447156

  Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
  Copyright (C) Microsoft Corporation.  All rights reserved.

  fatal error RC1110: could not open ./windows/windows.rc

  --- stderr
  thread 'main' panicked at 'RC.EXE failed to compile specified resource file',
```

If I revert the line with the resource to how it was before
```rs
embed_resource::compile("../extra/windows/windows.rc");
```
the build completes without an error.

### System
OS: Windows
Version: e447156612d3239f6b0e938043038d0ce6edaebf

**Comment by chrisduerr** [comment]
Do the symlinks work on Windows? I'm not actually sure they do.

**Comment by tupos** [comment]
If you want to make a symlink on windows you need to use the `mklink` command. The standard unix symlinks do not work as far as I know. On windows I typically use this `mklink` however, I'm not sure what happens if I add the symlink to git. I can test it out today in the evening and post an update here if you are interested.

Here is a doc about `mklink` https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink

**Comment by chrisduerr** [comment]
I don't care about creating symlinks on Windows, I'm just curious if git for windows manages to handle it at all.

**Comment by a5ob7r** [comment]
By default Git for Windows disables support for symlinks because non admin user can't create symlinks. So we need to give a special priviledge to the user or to run clone a repository as admin. I believe the easiest way is to run a terminal as admin and to clone Alacritty's repository with an option which enables symlink. I can build and run Alacritty (master) in this way.

```
# Example on PowerShell

# Open a terminal as admin to clone this repository.

$ git clone -c core.symlinks=true https://github.com/alacritty/alacritty.git
$ cd  .\alacritty\
$ cargo build --release
...
$ .\target\release\alacritty.exe
```

https://github.com/git-for-windows/git/wiki/Symbolic-Links

**Comment by chrisduerr** [comment]
Probably why it works just fine in CI. I guess we could move the windows folder instead of symlinking it.

**Comment by a5ob7r** [comment]
> Probably why it works just fine in CI.

I think so too.

> Windows virtual machines are configured to run as administrators with User Account Control (UAC) disabled.

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
