### ISSUE TITLE
Unable to bind Cmd+h on macOS since e0f0cdfb

### ISSUE THREAD

**Issue by rafi** [alacritty/alacritty#5346]
On macOS, since commit e0f0cdfb Alacritty's config key-mapping for <kbd>Cmd</kbd>+<kbd>h</kbd> stopped working, and instead it hides the window.

### System

OS: macOS
Version: alacritty 0.9.0-dev (e0f0cdfb)

**Comment by chrisduerr** [comment]
What exactly do you have it mapped to?

**Comment by rafi** [comment]
@chrisduerr, I've tried different chars and nothing worked, except rolling-back to 2de20378 :)

I move tmux windows with these Alacrity's bindings:
```yaml
  - { key: H, mods: Command, chars: "\x1bh" }
  - { key: L, mods: Command, chars: "\x1bl" }
```

And in tmux config
```
bind-key -n M-h previous-window
bind-key -n M-l next-window
```

**Comment by chrisduerr** [comment]
What does `alacritty --print-events | grep "WindowEvent.*KeyboardInput"` give you when you press these keys?

Isn't command+H a standard macOS binding to hide the window?

**Comment by rafi** [comment]
cmd+H is indeed a standard macOS for hiding the current window. But until e0f0cdf this mapping worked as expected and took precedence.

```
$ /Applications/Alacritty.app/Contents/MacOS/alacritty --print-events | grep "WindowEvent.*KeyboardInput"

[2021-07-19 12:23:18.378926000] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(140474898820976)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 55, state: Pressed, virtual_keycode: Some(LWin), modifiers: LOGO }, is_synthetic: false } }
```

**Comment by chrisduerr** [comment]
I'd assume that one of our dependency has taken it on itself to bind this, which means that Alacritty doesn't have the option to override anything anymore. But I don't consider this critical given that it is a standard macOS binding, though we should probably remove our binding at that point just to clean things up.

**Comment by rafi** [comment]
Can you try and guess which dependency is it? :)

**Comment by chrisduerr** [comment]
If anything, it's `winit`. Probably the change from 0.24.0 to 0.25.0.

**Comment by rafi** [comment]
After 4.5 years it'll be hard upgrading and untrain the muscle :] Binding cmd+h with iTerm2 works if that has any value.

![Preferences 2021-07-19 20-53-04](https://user-images.githubusercontent.com/147918/126204817-da352cf7-4e5e-4fb9-b94e-78aeb33cc8f5.png)

**Comment by chrisduerr** [comment]
If you want to look into this, it shouldn't be too much trouble in theory to revert this change. Will probably just require some discussion with upstream that I do not care about.

**Comment by rafi** [comment]
Downgrading `glutin` c4e8b539 solved this. Thank you @chrisduerr

**Comment by chrisduerr** [comment]
Just to be clear: Sooner or later Glutin/Winit will be updated again. The downgrade is solely temporary and unrelated to this issue.

**Comment by dartacean** [comment]
No other way but to use the old 0.9 version of alacritty this is really killing my workflow like @rafi

**Comment by rafi** [comment]
@dartacean I found a solution: Open Keyboard / Shortcuts and remap `Hide alacritty` for `Alacritty.app`, eg.
![Keyboard 2022-03-01 19-44-20](https://user-images.githubusercontent.com/147918/156220871-26b39321-845a-4e53-969a-19e3cdd3163f.png)

**Comment by didadadida93** [comment]
> @dartacean I found a solution: Open Keyboard / Shortcuts and remap `Hide alacritty` for `Alacritty.app`, eg. ![Keyboard 2022-03-01 19-44-20](https://user-images.githubusercontent.com/147918/156220871-26b39321-845a-4e53-969a-19e3cdd3163f.png)

yep, i can confirm this work perfectly.
thanks @rafi

**Comment by dartacean** [comment]
This totally works, Ive figured it out also but i havent posted it , thanks for posting it here for others to see ;)
