### ISSUE TITLE
Error msg while opening Alacritty

### ISSUE THREAD

**Issue by slowhand99** [alacritty/alacritty#5352]
### System

OS: Arch
Version: alacritty 0.8.0 (a1b13e68)
Linux/BSD: X11 and i3

After  a system update recently, every time alacritty is opened it shows an error msg like so:

![2021-07-21-001039_3840x2160_scrotedit](https://user-images.githubusercontent.com/31034451/126378375-1338615d-9802-4ec2-844a-73eef86be837.png)

Pacman logs does not show any upgrade to alacritty during the last upgrade. The msg does not cause any problems but it is annoying nevertheless.
This is the error log in /tmp

`2021-07-21 00:07:13.936754890] [ERROR] [alacritty] Unable to watch config file: other os error
`

**Comment by chrisduerr** [comment]
You should check your config file. Does the same happen with an empty one? One of your imports might be messed up.

**Comment by slowhand99** [comment]
The thing is the message only shows up sometimes. It is not a regular thing. And as I said it does not cause any disruptions either: I can close the msg and go on with my work. I haven't done any modifications recently on the config either.

**Comment by chrisduerr** [comment]
Assuming you use a non-symlinked config with no imports, I'd make sure the filesystem is consistently available and you have no drive issues.
