### ISSUE TITLE
Assign hints from top to bottom on a visible screen

### ISSUE THREAD

**Issue by lahwaacz** [alacritty/alacritty#5354]
When you set
```
hints:
  alphabet: "123456789"
```
you'll notice that Alacritty assigns from bottom to top. For example, when there are 9 visible URLs on the screen, the bottom-most will get 1 and the top-most will get 9.

This is very counter-intuitive, because humans tend to read top to bottom. For example, when I read mails in Mutt and want to open the first or second URL via Alacritty's hints, I can't know which hints they will get, because that depends on how many URLs follow on the screen.

Is there a way to limit matching to the visible screen (since I don't care about scrollback) and to assign hints from top to bottom?

**Comment by chrisduerr** [comment]
> Is there a way to limit matching to the visible screen (since I don't care about scrollback) and to assign hints from top to bottom?

No and there's no plan to give that option.
