### ISSUE TITLE
No config live reload when changing target of symbolic link config file

### ISSUE THREAD

**Issue by timhae** [alacritty/alacritty#5355]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

First of all, thanks for your time and effort! I am using NixOS and thus would like to link my alacritty configuration from the immutable nix store into my xdg config home. I would also like to be able to change color themes by linking different config files (the builtin theme functionality does not work for me since my config files reside in the immutable nix store). Whenever I change the theme (link a different file as config with `ln -sf conf_dark.yml alacritty.yml`) I see changes in the current shell but when I open a new shell and change the theme again, changes are not reflected in that new shell. Is this a limitation of the `notify-rs` module? I saw [some](https://github.com/notify-rs/notify/issues/255) [issues](https://github.com/notify-rs/notify/issues/341) there regarding symlinks but I don't know any rust so I can not dig any deeper.. I would expect the changes from the new config file to reflect in all opened instances. Thanks!

### System

OS: Linux
Version: `0.8.0`
Linux/BSD: X11, none+xmonad, picom

**Comment by chrisduerr** [comment]
There are some scenarios where inotify will not recognize the new file. The live config reload is meant to recognize files that have been edited, it's not intended to just probe for the config on a timer.

There is no plan to change that. Though there is #5313.

**Comment by timhae** [comment]
Thanks for the quick feedback!
