### ISSUE TITLE
Alacritty and Neovim weird interactions

### ISSUE THREAD

**Issue by Pirols** [alacritty/alacritty#5357]
### System

OS: Linux artix 5.12.14-artix1-1
Version: alacritty 0.8.0 (a1b13e68)
Linux: X11, [Picom](https://github.com/yshui/picom) and [Bspwm](https://github.com/baskerville/bspwm)

### Bug

I often use [sxhkd](https://github.com/baskerville/sxhkd) to launch (through a keybinding) command like `alacritty -e nvim file`. Unfortunately the result is, most times, incorrect. More specifically the behaviors I have encountered are the following:

1. The window is rendered properly and neovim is working (Expected behavior)
2. The window is rendered partially (this is by far the most occurring behavior)
![image](https://user-images.githubusercontent.com/36996537/126525689-5c8d147c-c348-4e11-8b0a-7034d4763303.png)
3. The window is apparently rendered properly but when I start doing something (e.g. scrolling through the file) weird artifacts start to be rendered. (This seems to happen only when another file is open in the same workspace)
![image](https://user-images.githubusercontent.com/36996537/126525934-66952d61-4a85-4542-aa8b-ad342db677c7.png)

Further considerations:

* The same behaviors occur when running the same command from an alacritty instance.
* However, running `nvim file` always yields the expected result.
* When one of the 2 undesidered behaviors occur opening a new window fixes the matter.
* Running `urxvt -e nvim file` within a urxvt instance does not run into similar issues.
* Running `:redraw` within neovim doesn't fix the issue
* Running the same commands with [micro](https://github.com/zyedidia/micro) I never encountered into similar issues.

Do you have any clue on which of the programs is at fault? Is there something I can fix at configuration-level? Thanks!

**Comment by chrisduerr** [comment]
This is to be expected since neovim cannot handle resizes during startup. If you want to prevent this you need to delay the neovim start by a few milliseconds.

**Comment by Pirols** [comment]
Thanks! That solved my issue.

**Comment by sarmong** [comment]
However, other terminals handle this file

`kitty nvim`
or
`gnome-terminal -- nvim` 

both render neovim just fine. Perhaps it is something with alacritty?

**Comment by kchibisov** [comment]
No, there's a bug in neovim repo about it, it's just a matter of trying to reproduce with other terminals. For more see https://github.com/alacritty/alacritty/issues/2817.
