### ISSUE TITLE
Nerd Font icon fault

### ISSUE THREAD

**Issue by fastchaser** [alacritty/alacritty#5359]
Hi, i'm using the  latest version 0.8.0 of Alacritty, and i'v installed the Hack Nerd Font.

Now, alacritty can display font icons, but the icons seem to occupy only half of the cursor. As shown in below iamge.

![image](https://user-images.githubusercontent.com/10161242/126643424-f0c658df-2133-4653-9558-8d4d3994aea5.png)
The red box is Alacritty and the other is ubuntu default terminal.

How can I fix the problem so that Alacritty looks the same as the ubuntu default terminal display.

**Comment by fastchaser** [comment]
![image](https://user-images.githubusercontent.com/10161242/126643345-55f64c12-a29a-429b-9910-3e511e5c43eb.png)

**Comment by chrisduerr** [comment]
The way glyphs are rendered is up to your font.

**Comment by fastchaser** [comment]
I've set the font in alacritty.yml. Could there be any other questions?

**Comment by youyiqin** [comment]
I had set the font in config file,but it look like not work.
