### ISSUE TITLE
Unable to enter '@' sign on macOS

### ISSUE THREAD

**Issue by zekroTJA** [alacritty/alacritty#5361]
### System

OS: macOS (Big Sur 11.4)
Version: alacritty 0.8.0 (a1b13e6)

## Description

I can not enter the `@` sign on macOS using the `Option (⌥)` + `L` key combination.

Sidenote: I am using powerlevel10k, but in the default terminal, everything works as expected.

## Steps to reproduce

1. Open alactitty on macOS
2. Enter `Option (⌥)` + `L`

## Screenshot 

https://user-images.githubusercontent.com/16734205/126752458-f2617f39-da2f-42ae-9f88-479ede7c11d5.mov

**Comment by chrisduerr** [comment]
#458
