### ISSUE TITLE
Left/Right keys do not work with Ctrl+Shift

### ISSUE THREAD

**Issue by lahwaacz** [alacritty/alacritty#5363]
I have these key bindings in my `vimrc` file:

    nnoremap <silent> <C-S-Left> :execute 'silent! tabmove ' . (tabpagenr()-2)<CR>
    nnoremap <silent> <C-S-Right> :execute 'silent! tabmove ' . (tabpagenr()+1)<CR>

They map `Ctrl+Shift+Left` and `Ctrl+Shift+Right` for moving the current tab left and right, respectively. This used to work in Termite, but it does not work in Alacritty. When I press `Ctrl+Shift+Left`, vim shows `^[[1;6D` for a moment in the status line, for `Ctrl+Shift+Right` it is `^[[1;6C`.

### System

OS: Linux
Version: alacritty 0.8.0 (a1b13e68)
Linux/BSD: Wayland, Sway

### Config

The `key_bindings:` section in `alacritty.yml` is commented out, so this is with the default key bindings.

### Logs

`alacritty --print-events` gives this when pressing `Ctrl+Shift+Left`:

    [2021-07-24 09:11:39.234419012] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(94476080964896))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 105, state: Pressed, virtual_keycode: Some(Left), modifiers: SHIFT | CTRL }, is_synthetic: false } }

**Comment by chrisduerr** [comment]
> When I press Ctrl+Shift+Left, vim shows ^[[1;6D for a moment in the status line, for Ctrl+Shift+Right it is ^[[1;6C.

Then it's working.

**Comment by lahwaacz** [comment]
> Then it's working.

It obviously does not provide the expected behaviour. Please, provide a more useful feedback.
