### ISSUE TITLE
Can't lauch a command in a new terminal window.

### ISSUE THREAD

**Issue by SisyphusIsntHappy** [alacritty/alacritty#5369]
I'm trying to spawn a new terminal window by also giving a command to it at the same time, but alacritty is not responding to it properly.

### System
OS: Arch Linux
Version: alacritty 0.8.0 (a1b13e68)
Linux: X11, Dynamic Window Manager

### How to replicate

Input Command: 
   `alacritty -e "sudo pacman -Syu"`
Output: 
`Created log file at "/tmp/Alacritty-1354655.log"
[2021-07-25 16:55:44.530000270] [ERROR] [alacritty_terminal] Failed to spawn command 'sudo pacman -Syu': No such file or directory (os error 2)`

**Comment by chrisduerr** [comment]
You're trying to run the entire string you're passing as command. You need to separate it into multiple parameters.
