### ISSUE TITLE
Keyboard input latency issue after nvidia driver installation

### ISSUE THREAD

**Issue by robbyki** [alacritty/alacritty#5379]
Similar to https://github.com/alacritty/alacritty/issues/4801, where my problems with typing in alacritty coincides with having replaced all of my nouveau drivers with nvidia fedora 34. I've been using alacritty for a while without any issues when I was on nouveau but now experiencing terrible keyboard delay issues and also not registering some keys. Dropping back to gnome-terminal is exponentially faster and better and would like to figure this out and continue using alacritty. 

Built latest dev release from using cargo and tried `0.9` and now on `alacritty 0.10.0-dev (3c309a09)`

**Comment by chrisduerr** [comment]
I'd assume this is on X11? Unfortunately there's not much that can be done with the nvidia drivers.

**Comment by robbyki** [comment]
Ah got it. Okay. Thanks. I am on X11.

**Comment by WillyWonksters** [comment]
This issue goes away for me when I change my power profile.

I am running Pop!_OS on an HP Dev One, with integrated AMD graphics, Ryzen 5850U.

This issue arises anytime I change my power profile to 'Battery Life'.
