### ISSUE TITLE
Double cursor in Neovim embedded terminal

### ISSUE THREAD

**Issue by Acelya-9028** [alacritty/alacritty#5389]
OS: Windows :(
Version: alacritty 0.8.0 (a1b13e6)

![double-cursors](https://user-images.githubusercontent.com/45818681/127869168-a5d1174b-f03d-443a-82e4-4a25ebdf23e7.png)

As you can see, two cursors are displayed instead of one.
Does it have something to do with it? https://github.com/neovim/neovim/issues/14386#issuecomment-822964785

This problem isn't present with Powershell 7 terminal.

I bump this too: https://github.com/alacritty/alacritty/pull/4501.

I know you're not very Windows friendly, I have seen it from reading a few issues, and there are a lot of good reasons to hate Windows but it would be amazing if this problem could be solved.

I understand your [position](https://github.com/alacritty/alacritty/issues/2093#issuecomment-535450798), it's not your problem and you don't want to bloat Alacritty to fix Windows problems and substituate Windows to its responsibility but actually, it's just broken. Ok, I can patch it manually but everyone knows this is not a viable long term solution.

Thank you for Alacritty.

**Comment by chrisduerr** [comment]
It's a windows issue.
