### ISSUE TITLE
alacritty -e command -t title does not properly set title of window

### ISSUE THREAD

**Issue by IvanMalison** [alacritty/alacritty#5391]
`alacritty -e htop -t htop` does not set the title of the window in the XServer, but
`alacritty -t title -e` command DOES

Is this expected behavior? It is very surprising

### System

OS: Linux (NixOS)
Version: alacritty 0.8.0
Linux/BSD: X11, XMonad with picom as compositor

**Comment by chrisduerr** [comment]
Working as intended, see the documentation of these flags.
