### ISSUE TITLE
TMUX SCROLLBACK DOESN'T WORK

### ISSUE THREAD

**Issue by A1ex-N** [alacritty/alacritty#5393]
### System

OS: Windows (Using WSL)
Version: alacritty 0.8.0 (a1b13e6)

While using tmux in any terminal other than alacritty, i can scroll back through the history using the mouse scroll wheel. In alacritty, this feature does not work. I have no idea why

I'm opening this issue again, because the last time i opened this issue #5374 @chrisduerr said "Because windows probably" and closed the issue.
I'm really not sure how a linux elitist has maintainer status on a CROSS PLATFORM application, but i'd really like a better explanation as to why scrollback isn't working on windows.

**Comment by fir3z** [comment]
@chrisduerr I thought this application is _supposed to be_ cross-platform?
Why are you closing a **genuine** issue because OP is using Windows?

Hopefully someone else can actually **help**.

**Comment by chrisduerr** [comment]
Because it's not a genuine issue. It's due to Windows bugs. Opening new issues doesn't help, it just causes useless maintenance overhead.

**Comment by fir3z** [comment]
This does not seem to be the case? OP stated that this is only happening with Alacritty?

**Comment by AutisticKangaroo** [comment]
> 
> 
> Because it's not a genuine issue. It's due to Windows bugs. Opening new issues doesn't help, it just causes useless maintenance overhead.

It's not a windows bug, the issue is present on only alacritty and not on normal ConHost programs.  You can test this by middle clicking on the alacritty window while on windows, this feature does not work and does nothing.

**Comment by AutisticKangaroo** [comment]
Expected behavior is as such 
![image](https://user-images.githubusercontent.com/80230068/128113193-4b76d7b2-5a20-4f60-90ad-e6e70407f886.png)

Moving mouse up and down on the screen should scroll automatically, the defined behavior is that the symbol never appears and nothing happens.

**Comment by pogopaule** [comment]
Same here. Problem only exists with Alacritty, but no other terminal I tried.

**Comment by Nicolas-GUILLAUME** [comment]
I just noticed the same issue. I don't run Alacritty inside the WSL. I don't have this issue with other terms so it seems like an issue Alacritty specifically.

**Comment by Nicolas-GUILLAUME** [comment]
After getting frustrated with this, I looked for another Hardware accelerated term for Windows that actually works and discovered [WezTerm](https://wezfurlong.org/wezterm). This thing is outstanding. The Scroll works in tmux (despite the fact that "windows is just a bunch of bugs"), everything is super smooth and the configuration is easy and well documented.

**Comment by marcelo-r** [comment]
@Nicolas-GUILLAUME thanks for recommending WezTerm, tried it and can confirm scroll is working as expected, with and without using tmux.
