### ISSUE TITLE
Middle click scroll not working under windows.

### ISSUE THREAD

**Issue by AutisticKangaroo** [alacritty/alacritty#5394]
Expected behavior is as such 
![image](https://user-images.githubusercontent.com/80230068/128113193-4b76d7b2-5a20-4f60-90ad-e6e70407f886.png)

The expected behavior is that moving mouse up and down on the screen after middle clicking should scroll automatically, the defined behavior is that the symbol never appears and nothing happens when you move your mouse up and down.

This is not a windows ConsoleHost bug as it only occurs with alacritty.

_Originally posted by @AutisticKangaroo in https://github.com/alacritty/alacritty/issues/5393#issuecomment-892315043_

**Comment by chrisduerr** [comment]
Why would this be implemented, rather than just using one of the other scrolling methods?

**Comment by FireCubez** [comment]
Many people have broken scroll wheels, its very useful.

**Comment by chrisduerr** [comment]
There's plenty options to scroll without scrollwheel in Alacritty already. So that's really not a great argument.

**Comment by AutisticKangaroo** [comment]
> 
> 
> There's plenty options to scroll without scrollwheel in Alacritty already. So that's really not a great argument.

As it is expected behavior under windows, it would be good to implement as it follows [Jakob Nielsens's design principles](https://www.nngroup.com/articles/ten-usability-heuristics/) which are used every day in major organizations, if you're not willing to implement this just say and claiming "that's not a good argument or useless feature" is questioning how you managed to become a maintainer of cross platform software.

**Comment by chrisduerr** [comment]
Closing since there's no good arguments for the inclusion of this feature other than "it exists in other Windows software".
