### ISSUE TITLE
Mouse not working inside vim

### ISSUE THREAD

**Issue by j0ker70** [alacritty/alacritty#5395]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

I am using vim as my editor. In my alacritty.yml file I have set `TERM: alacritty`. But when I am inside of vim, I cannot use my mouse. But if I use `TERM: xterm-256color` it works fine. 

### System

OS: Ubuntu 20.04
Version: alacritty 0.9.0-dev (e0f0cdf)
Linux/BSD: X11, Gnome

**Comment by chrisduerr** [comment]
You need to run `:set ttymouse=sgr`, but it's a vim issue. Neovim should work just fine for example.
