### ISSUE TITLE
Unable to disown process when using the execute option `-e`

### ISSUE THREAD

**Issue by dcompoze** [alacritty/alacritty#5402]
## System

OS: Arch Linux
Version: alacritty 0.9.0 (fed349aa)
Compositor: Sway/Wayland 

## Logs

No visible errors when using verbose mode: `alacritty -vvv`.

## Issue

When launching a separate process using the `-e` flag the command correctly launches a second alacritty instance which is owned by the parent process - once the parent is closed, the child process also dies:
```sh
alacritty -e alacritty
```
In order to disown the child process and not have it depend on the parent existing, I used a command like this:
```sh
alacritty -e zsh -c 'alacritty &!'
```
This should in theory execute the zsh command `alacritty &!` and launch a second alacritty instance that is disowned by the `zsh` process. But instead the new alacritty instance simply never opens.

- I tried putting `alacritty &!` in a script instead, and running `alacritty -e custom-script` with the same result.
- I tried using a different shell `alacritty -e sh -c '(alacritty)&'` which also didn't work.
- I tried running a different application e.g. `alacritty -e zsh -c 'zathura &!'` and that also resulted in the same issue.

Note that executing `alacritty -e zsh -c 'alacritty'` without the `&!` or `&`, works as expected - it opens the second `alacritty` process and then once I close the parent process, the child also dies.

The interesting thing is that if I run:
```
alacritty -e zsh -c 'alacritty &!; sleep 5' 
```
The second alacritty window actually opens for 5 seconds and then is killed. It would seem that alacritty executes the provided command but for some reason the disown `&!` part doesn't apply (even with `nohup` as described below).

It would be great if alacritty had an option to disown the executed command which would simplify what I'm trying to achieve:
```sh
alacritty -e --disown alacritty 
```
Using `nohup` allows the child window to stay open after the parent is closed (manually):
```sh
alacritty -e zsh -c 'nohup alacritty'
```
But it also doesn't work with the disown syntax `&!` (doesn't open the child window):
```sh
alacritty -e zsh -c 'nohup alacritty &!'
```

## Use case

I have a simple script that picks a file from a list of files and launches it in a separate instance of alacritty + vim:

**edit-chosen-file.sh:**

```sh
#!/usr/bin/zsh

CHOSEN_FILE=$(ls | fzf)

alacritty -e vim $CHOSEN_FILE &!
```
And then I bind it to a key in sway:
```
bindsym Mod4+e exec alacritty -e edit-chosen-file.sh
```
Which should:
1. Launch alacritty window
2. Execute the `edit-chosen-file.sh` script inside the window
3. I pick a file from a list of files
4. The script launches a separate instance of alacritty and executes `vim $CHOSEN_FILE` inside it.
5. The first alacritty window closes
6. The second alacritty window stays open because the process was disowned with `&!`.

What it does instead:
1. Launch alacritty window
2. Execute the `edit-chosen-file.sh` script inside the window
3. I pick a file from a list of files
4. The second window doesn't open
5. The first alacritty window closes

## References

This issue seems somewhat related: https://github.com/alacritty/alacritty/issues/833

**Comment by dcompoze** [comment]
# Update

After a bunch of debugging I managed to figure out a few things:

1. The `gnome-terminal` seems to have same behaviour as alacritty in this regard.
2. When running a program from `alacritty -e zsh -c '<program> &!'` the disown syntax `&!` doesn't prevent the final program from receiving SIGHUP signals and hence the child program closes together with the parent (though I'm still not sure why `&!` works fine in the interactive shell but then launched from `alacritty -e` it doesn't work the same).
3. Running `alacritty -e zsh -c 'nohup <program> &!'` does indeed prevent the final process from receiving SIGHUP signals. However the problem is that for some reason the zsh process is killed before it manages to invoke the `nohup` command - this can be demonstrated by adding a short sleep delay: `alacritty -e zsh -c 'nohup <program> &!; sleep 0.5'` which will launch the program and then once the parent window closes it will stay open.
4. In order to solve the above issue I managed to make use of the `setsid` utility which creates a new process group at the very beginning - which prevents the parent process being killed when alacritty exits: `alacritty -e setsid zsh -c 'nohup <program> &!'`
5. Also there was an issue with the chromium browser where it would ignore the `nohup` command and still listen for SIGHUP signals. Adding the `setsid` command before launching chromium has also solved this problem `setsid chromium`.

**Comment by chrisduerr** [comment]
This is unrelated to Alacritty. All Alacritty does is launch a shell, what happens from then on out is none of our concern. It makes no sense to disown a shell.

**Comment by dcompoze** [comment]
Sounds like you haven't read the issue but that's OK - as I'm satisfied with the solution above.

**Comment by chrisduerr** [comment]
I've read the issue and there is no action necessary from Alacritty's side.

**Comment by dcompoze** [comment]
> All Alacritty does is launch a shell, what happens from then on out is none of our concern. It makes no sense to disown a shell.

In theory you can launch the shell in a separate process group such that when alacritty exits it doesn't kill the child process - which some launcher programs do. That's what I meant by disown.

**Comment by chrisduerr** [comment]
Alacritty is a terminal emulator, not a "launcher program".

**Comment by dcompoze** [comment]
Great, thanks for the help - have a good day.

**Comment by sirex** [comment]
I had the same issue with QTile window manager and Obsidian, solved it this way:

```sh
# 1. Create a wrapper script `nvim-disown.sh`:
cat > ~/.local/bin/nvim-disown.sh <<'EOF'
#!/bin/sh

alacritty -e nvim "$1" & disown
EOF
chmod ug+x ~/.local/bin/nvim-disown.sh
ls -al ~/.local/bin/nvim-disown.sh
#| -rwxr-xr-- 1 user user 30 2024-09-18 09:46 ~/.local/bin/nvim-disown.sh

# 2. Create a desktop application entry for the wrapper script:
cat > ~/.local/share/applications/nvim-alacritty-disown.desktop <<'EOF'
[Desktop Entry]
Type=Application
Name=Neovim (Alacritty)
Exec=nvim-disown.sh %U
Categories=Other;
NoDisplay=true
MimeType=text/markdown
Terminal=false
EOF

# 3. Associate file types with the desktop application entry:
cat ~/.config/mimeapps.list
#| text/markdown=nvim-alacritty-disown.desktop
```

This could probably be more generalized, to work with any command, not only with `nvim`.
