### ISSUE TITLE
set "IncreaseFontSize" "step" value

### ISSUE THREAD

**Issue by 13di31** [alacritty/alacritty#5405]
It would be nice (for me at least) if there was a setting in the config that allowed to set by how much "IncreaseFontSize" increase the font size. I find myself to have to press many times Ctrl+Plus or Ctrl+Minus to obtain the right font size. From what I can understand it seems that the font size increases by 0.5 points every time, I'd like to be able to change it in 1 or 2 points at a time.

Regards, thank you very much for your work and this amazing piece of software!
AM

**Comment by chrisduerr** [comment]
Pressing the button half as much doesn't justify complicating the config to me.

**Comment by 13di31** [comment]
Oooook, it tourns out that it was simple enough to hack in the config, really. I did this:

`key_bindings:
  - { key: Plus,      mods: Control,       action: IncreaseFontSize }
  - { key: Plus,      mods: Control,       action: IncreaseFontSize }
  - { key: Plus,      mods: Control,       action: IncreaseFontSize }
  - { key: Plus,      mods: Control,       action: IncreaseFontSize }

`
and it finally works as it should!
