### ISSUE TITLE
Cannot get transparency (black background)

### ISSUE THREAD

**Issue by Shirumipi** [alacritty/alacritty#5406]
I am using Alacritty on both Desktop and Laptop.
For the Desktop, no issue at all. Works perfectly (opacity and transparency runs fine).
My problem comes with the laptop : i have 2 WM, XFCE and i3-gaps. With xfce-terminal, i do have transparency and i can set the opacity in the alacritty.yml to fit my preference. Plus, i am using ROFI which use transparency without a problem at all.
So i still don't understand why Alacritty does not support transparency on my laptop. Opacity is working between my selected background color and black (If i set opacity to 0, i have a black background and 1 is my selected background color).

Finally, i have to say that i have to launch Alacritty like this : LIBGL_ALWAYS_SOFTWARE=1 alacritty because if run alacritty normally, i got this error: [ERROR] [alacritty] Alacritty encountered an unrecoverable error: There was an error initializing the shaders: Failed compiling shader: 0:1(10):     error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES
For this error, i tried launch XFCE tetminal like this: LIBGL_ALWAYS_SOFTWARE=1 xfce4-terminal and i do have transparency.

I searched on the Web but still, nothing relevant. 

### System

OS: Linux (Gentoo)
Version: alacritty 0.8.0
Linux : i3-gaps and  XFCE (WM), xcompmgr (compositor)
My system : Linux-5.10.52-gentoo-x86_64-Intel-R-_Core-TM-_i3_CPU_M_350_@_2.27GHz

### Logs
Font/Terminal size: [2021-08-09 23:18:10.489862647] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-08-09 23:18:10.497392349] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-08-09 23:18:10.504305278] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-08-09 23:18:10.509339787] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }

**Comment by chrisduerr** [comment]
Are you running a compositor? Also why are you running with LIBGL_ALWAYS_SOFTWARE?

**Comment by Shirumipi** [comment]
For the compositor, it's written in my post (xcompmgr).
I added the answer of your question regarding the LIBGL command. If i normally run Alacritty, it failed because it cannot render shaders due ti GLSL 3.30 not supported.

**Comment by chrisduerr** [comment]
> GLSL 3.30 not supported.

Which means that your system is not supported by Alacritty, as stated in the readme.
