### ISSUE TITLE
`Shift+Space` mapping doesn't work

### ISSUE THREAD

**Issue by whereistejas** [alacritty/alacritty#5407]
Hi,
I'm using the default config with the default alacritty. I want to bind `<S-Space>` in neovim to a particular fold command.

However, neovim never receives the `Shift+Space` from alacritty. I tested this using the following:
1. In nvim, set `:nmap <s-space> :works`
2. Go to normal mode and press `Shift+Space`, this should show `:works` in the command bar, but in my case nothing happens.

Output for `showkey -a` for `Shift+Space`:
```
Press any keys - Ctrl-D will terminate this program

  	 32 0040 0x20    <-- Shift+Space
^D 	  4 0004 0x04
```

### System

OS: Ubuntu Linux
Version: 0.9.0
Linux/BSD: X11 on i3wm

**Comment by chrisduerr** [comment]
Working as expected, shift+space does not have an alternate character sequence.

**Comment by whereistejas** [comment]
So, will I have to create the alternate sequence by mapping the keypress in the yaml config?
