### ISSUE TITLE
Mask off Alt in Alt+Shift Left drag selection ?

### ISSUE THREAD

**Issue by mckellygit** [alacritty/alacritty#5415]
Hi,

Thank you for awesome Alacritty.
This is really a question - I can select lines/rectangle/etc. with Shift Left drag or Ctrl+Shift Left drag
But it also seems Alt+Shift Left drag selects, do you think it makes sense to mask off the Alt so that Alt+Shift can be used in other programs ?  Can this be done in the yml ?  Something such as:
    - { mouse: Left,   mods: Alt|Shift, action: None }
But I haven't been able to get that to work.

OS: Ubuntu 18.04 with latest hwe/updates
Version: alacritty 0.10.0-dev (d5c66ce)
Wayland mutter GNOME Shell 3.28.4

thx,
-m

**Comment by chrisduerr** [comment]
Shift is generally always "skip mouse reporting". So no I don't think this makes much sense. Terminal applications at this point should probably just accept that shift is not a valid modifier during mouse mode. Generally the use of the mouse should be relatively limited anyway, I think dealing with just alt/control is sufficient.
