### ISSUE TITLE
Allow binding of a different action to double/triple clicking the mouse

### ISSUE THREAD

**Issue by magnus-ISU** [alacritty/alacritty#5420]
I want to be able to close the terminal with the mouse alone, but binding it to the right mouse button is very restricting and binding it to middle mouse is not feasible because it accesses the primary selection.

The configuration file contains the following lines:

    mouse:
      # Click settings
      #
      # The `double_click` and `triple_click` settings control the time
      # alacritty should wait for accepting multiple clicks as one double
      # or triple click.
      double_click: { threshold: 300 }
      triple_click: { threshold: 300 }

After looking through the code, I have realized that this is to detect when you are clicking multiple times with shift to highlight a word/line. However, I think it would be really useful to be able to use `DoubleClick` or `TripleClick` as mouse-only modifiers for keybindings.

The best implementation would wait the full delay before sending a single click (though now you are getting into dangerous territory, because this changes previous behaviour, and some people might not want that), that way you can execute a double-click without first executing a single click. However, for some use cases (triple click to close, also maybe click-to-increase-font-size, double-click-to-reset) it wouldn't matter that you 'leak' a couple extra actions beforehand too.

Either way I think it could be very useful, and depending on how double/triple clicks are already implemented, wouldn't be difficult to add.

**Comment by chrisduerr** [comment]
Don't see "click to close" as a useful feature.
