### ISSUE TITLE
Customize mouse selection configuration

### ISSUE THREAD

**Issue by vit1251** [alacritty/alacritty#5421]
Feature request for customization selection start, selection stop in configuration file on specific mouse button.

For example use copy to file action when left button selection,
use clipboard on right mouse button.

Or even disable selection on left button and use only right button selection.

**Comment by chrisduerr** [comment]
Why? I don't see much reason to provide copying behavior beyond what is done by default on Linux.

**Comment by vit1251** [comment]
Some mouse provide a more than 3 button with custom location. Some button may be better locate for example. I have mouse with 9 button.

Second reason is using selection in meetings as focus (no need to copy always in buffer).

**Comment by chrisduerr** [comment]
None of these arguments convince me to make major changes in Alacritty's config and code complexity when it comes to selections. The way it works right now is straight-forward and should be intuitive on every platform, so no need to over-complicate things.
