### ISSUE TITLE
[FEATURE REQUEST] Add key binding to exit vi mode (not just toggle it)

### ISSUE THREAD

**Issue by adam900710** [alacritty/alacritty#5424]
Awesome work, guys!

Didn't notice such an awesome terminal emulator until konsole adds some crappy features (and can't be properly disabled).

Vi mode is totally awesome, just one small thing to enhance.

Can we have a dedicated key bind to exit Vi mode?

I'm asking because just like every vi/vim user, we exit vi/vim using `:q`, with the `:` skipped, I just reach `q` trying to exit vi mode everytime, and then consider to press `shift+control+space` to toggle vi mode.

### System

OS: Linux
Version: 0.9.0 (fed349aa)
Linux/BSD: X11, KDE

**Comment by chrisduerr** [comment]
Already possible, just check the mode you're in.

**Comment by adam900710** [comment]
No, I mean to have a specific keybind to exit vi mode, other than toggling the vi mode.

**Comment by chrisduerr** [comment]
I know what you mean.

**Comment by ysxninja** [comment]
:q works,
and if you want just q, extend with keybindings.

```toml
[[keyboard.bindings]]
action = "ToggleViMode"
key = "Q"
mode = "Vi"
```
