### ISSUE TITLE
Feature Request: IncreaseFontSize and DecreaseFontSize in larger increments

### ISSUE THREAD

**Issue by alanxoc3** [alacritty/alacritty#5425]
I was using termite for a while and when you ctrl|shift|+ or ctrl+minus in that program, the font increases at a faster rate than alacritty. In alacritty if I want to go from a very small font to a very large font, it might take two to three times longer than if did the same in termite, because alacritty increases the size in very small increments. So my suggestion is to implement a configuration option like this:

```
font:
  ...
  # How large the increment is for IncreaseFontSize and DecreaseFontSize.
  # This is multiplied by the dpi fraction thing that alacritty uses.
  # This number must be an integer greater than 0. The default is 1.
  increment_multiplier: 3
  ...
```

#3541 kinda looks related, but I don't think it's the same thing.

**Comment by chrisduerr** [comment]
Just add the binding multiple times.

**Comment by alanxoc3** [comment]
Thanks. I didn't know that works.
