### ISSUE TITLE
Warning about using window_opacity is incorrect

### ISSUE THREAD

**Issue by steev** [alacritty/alacritty#5427]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux
Version: alacritty 0.10.0-dev (c24d7dfd)
Linux/BSD: Wayland/Gnome

As of commit c24d7dfd, background_opacity was changed to window_opacity, however, when you set window_opacity, Alacritty throws a warning to use window.opacity, which does not work.

**Comment by chrisduerr** [comment]
You need to set window -> opacity. `window.opacity` is just a shorthand notation that is not actually valid yaml.
