### ISSUE TITLE
Scrolling causes high resource usage, maybe by redrawing the display more than necessary 

### ISSUE THREAD

**Issue by magnus-ISU** [alacritty/alacritty#5429]
### System

OS: Linux X11 for sure, but I think all platforms
Version: alacritty 0.9.0 (fed349aa)
Linux/BSD: X11 dwm

### Description

When scrolling, alacritty uses much more of my CPU than other terminals, for example `sakura`. It nearly maxes out one core and causes temperature jumps of around 20 degrees celsius (a very unscientific and hardware-dependent benchmark, but I suspect that other machines will experience similar activity).

A potential cause is that, even when nothing on the screen changes (for example, a mouse click, or a case where it matters, scrolling after running `reset` so there is nothing to scroll, etc) alacritty will redraw the screen (I am led to believe this by putting an `eprintln!` in `alacritty/src/display/mod.rs draw()`. When I get an autoclicker to click 1000 times on the alacrity window over 5 second, for example, it uses 2 cores at 100% utilization. However, I don't think this is the only thing that can be improved since even when the screen should be redrawn, for example when scrolling normally, sakura seems to use no additional resources (over it's higher idle usage) while alacritty begins stressing my system.

This is (and will be, if merged) especially noticeable with the changes I have made to work on #775. You can checkout my work https://github.com/magnus-ISU/alacritty, I have left a debug print in there that shows how often the screen seems to be redrawn.

Replacing that print with a return (so no rendering is done) solves all issues (mouse autoclicker and scrolling) (though obviously if nothing is ever drawn to the screen, you can hardly use a terminal) so I think the solution is to avoid redrawing everything if nothing has changed.

Since alacritty is supposed to be the fastest terminal emulator, I think this is a problem. If the cause of this is that it doesn't buffer events or something (The readme says "Some terminal emulators also intentionally slow down to save resources, which might be preferred by some users." and I think there is definitely room for improvement even without doing this) but maybe some of this is intended behaviour.

I am still unsure if I want to use alacritty when it stresses my CPU harder than some AAA games.

**Comment by chrisduerr** [comment]
What framerate does Alacritty run at for you?

**Comment by magnus-ISU** [comment]
How do I check the framerate?

Unfortunately, my GPU is nvidia (an old GTX660). It might be the case that this is just driver issues, but I had assumed it wasn't due to the CPU being what was stressed (though maybe I don't understand opengl well enough) and other terminal emulators seeming to work fine.

**Comment by chrisduerr** [comment]
You'll have to figure out yourself how to measure framerate with nvidia. There are probably driver tools.

**Comment by magnus-ISU** [comment]
Running with `__GL_SHOW_GRAPHICS_OSD=1 alacritty` shows 0FPS when not doing anything, 50-60FPS when scrolling (either on an empty screen where nothing is actually changing, or when actually scrolling for real)

**Comment by chrisduerr** [comment]
How are you scrolling? With a mousewheel?

**Comment by magnus-ISU** [comment]
Yes

**Comment by magnus-ISU** [comment]
Or by calling `self.ctx.scroll(1)` repeatedly in `input.rs`, but it happens either way.

**Comment by chrisduerr** [comment]
> Or by calling self.ctx.scroll(1) repeatedly in input.rs, but it happens either way.

Please do not report any issues related to modified code.

If you're using the scrollwheel, I don't see how you'd get to 60 FPS and excessive CPU usage. Do you have a scrollwheel that does not have individual 'clicks'?

**Comment by xyproto** [comment]
When scrolling several pages up (around 10) while also selecting text with the mouse, Alacritty crashed here. It might be related to this issue?

**Comment by chrisduerr** [comment]
> It might be related to this issue?

It's not.
