### ISSUE TITLE
Make alacritty -e <command> to execute command as if from shell or at least allow passing environment variables to <command>?

### ISSUE THREAD

**Issue by rieje** [alacritty/alacritty#5432]
Alacritty's `-e` option executes command and args. It seems the first argument is always treated as the command, hence why it's not possible to do something like passing environment variables to the command like `TERM=alacritty nnn` (`alacritty -e TERM=alacritty nnn` yields the error: `Failed to spawn command 'TERM=alacritty': No such file or directory (os error 2)`.

Is it possible to make alacritty execute `TERM=alacritty nnn` as if the shell interprets it, or at least detect environment variables and execute the appropriate command (`nnn` with the environment variables passed to it)?

P.S. `TERM=alacritty` is necessary for my purposes because I want alacritty to use true colors but `nnn` does not and will never support that. I also have many environment variables I want to pass to the command as well. My script current involves a wrapper which detects whether to run `nnn` with alacritty by checking whether it was run from the terminal or from a GUI like dmenu.

**Comment by chrisduerr** [comment]
If you want a shell, spawn one.
