### ISSUE TITLE
Released .dmg does not contain Universal Binary

### ISSUE THREAD

**Issue by martinezhermes** [alacritty/alacritty#5434]
It would appear the file in the Releases download is not a universal binary.
I am not able to run Alacritty as an arm64 binary.

```
file /Applications/Alacritty.app/Contents/MacOS/alacritty
/Applications/Alacritty.app/Contents/MacOS/alacritty: Mach-O 64-bit executable x86_64
```

when forcing it:
```
arch -arm64 /Applications/Alacritty.app/Contents/MacOS/alacritty
arch: posix_spawnp: /Applications/Alacritty.app/Contents/MacOS/alacritty: Bad CPU type in executable
```
Also, _Activity Monitor_ shows Intel as architecture.

Closed issues have the universal binary situation marked as solved, how do I download such release?

**Comment by chrisduerr** [comment]
No release has been made since then.

**Comment by ryan-ph** [comment]
This still seems like an issue with the current release. Is there anyway to avoid needing Rosetta when using alacritty?

**Comment by chrisduerr** [comment]
Build it from source until 0.10.0.
