### ISSUE TITLE
Input delay under vcxsrv

### ISSUE THREAD

**Issue by piotryordanov** [alacritty/alacritty#5435]
There is a significant input delay when using Alacritty under vcxsrv.
For reference, running termite, I don't face this lag.

What do I need to do to fix it?

**Comment by chrisduerr** [comment]
If vcxsrv is having problems with OpenGL, I recommend not using vcxsrv.

**Comment by piotryordanov** [comment]
Thank you for the fast response.
I know it's unrelated to Alacritty, but do you happen to know a vcxsrv alternative that supports openGL?

Thanks!

**Comment by chrisduerr** [comment]
I do not.
