### ISSUE TITLE
Alacritty always prints recent command again

### ISSUE THREAD

**Issue by philipfeldmann** [alacritty/alacritty#5439]
I've encountered the following behavior on both macOS and manjaro:
When I enter a command, for example ls, the command will be printed again by alacritty in the next line without a newline before the output. For example
```
> ls -a
ls.  ..  hello-github.jpg
```
Note that the command is written at the start of the second line. What could be the cause of this? It doesn't happen in any other terminal emulator, for example xterm or iterm2.

### System

OS: Linux and macOS
Version: alacrittyalacritty 0.9.0 (fed349aa0)
Linux/BSD: X11

**Comment by chrisduerr** [comment]
Can you reproduce this in bash without any extra configuration?

**Comment by philipfeldmann** [comment]
Hey @chrisduerr,
this only happens in ZSH, bash seems to work fine. Also this does not happen within a tmux session either.

**Comment by chrisduerr** [comment]
Tried a different `TERM`? Like `export TERM=xterm-256color`?

Your zsh configuration is very likely just broken.

**Comment by philipfeldmann** [comment]
It works with xterm on linux as well as iterm2 on macOS. I've tried uncommenting my entire .zshrc, which at this point is pretty much only the default one you get from oh-my-zsh and the issue goes away. So this might have to do with oh-my-zsh?

**Comment by chrisduerr** [comment]
Yes, this definitely has to do with your zsh configuration. Though I'm afraid you didn't test the term change I've suggested? Either way, there's no evidence this is an Alacritty bug.

**Comment by philipfeldmann** [comment]
Oh sorry I misinterpreted that. Setting TERM as you've suggested fixed the issue.
Thanks a lot :smiley:

**Comment by chrisduerr** [comment]
That suggests some of the plugins you're running in zsh are broken.
