### ISSUE TITLE
Windows: os error 267

### ISSUE THREAD

**Issue by onthebusiness** [alacritty/alacritty#5441]
### System

OS: Windows
Version: alacritty 0.9.0 (fed349a)

### Logs

Crash log:
```
---------------------------
Alacritty: Runtime Error
---------------------------
panicked at 'Unable to spawn shell: Неверно задано имя папки. (os error 267)', alacritty_terminal\src\tty\windows\conpty.rs:175:5

Press Ctrl-C to Copy
---------------------------
ОК   
---------------------------
```

**Comment by chrisduerr** [comment]
Do you have any kind of configuration setup? Have you tried a different shell?

**Comment by onthebusiness** [comment]
@chrisduerr I have other shells working. If you are talking about the alacritty configuration, then it is the default.

**Comment by chrisduerr** [comment]
I'm afraid you don't understand. I mean a different shell, not a different terminal.

**Comment by onthebusiness** [comment]
The other terminals and shells work, but alacritty can't even start properly.

**Comment by chrisduerr** [comment]
Have you tried Alacritty, with a different shell?

**Comment by onthebusiness** [comment]
The last versions that worked for me were either `0.5.x` or `0.6.x`. Now I can't install them. I also tried installing through `cargo`, but the same result

**Comment by chrisduerr** [comment]
Also what's your Windows version?

**Comment by onthebusiness** [comment]
@chrisduerr No, I didn't.

**Comment by onthebusiness** [comment]
Microsoft Windows [Version 10.0.18362.476]

**Comment by chrisduerr** [comment]
> No, I didn't.

Then do.

**Comment by onthebusiness** [comment]
@chrisduerr 

Oh my god, sorry for taking up your time!

I tried to update the config in `~/.config/alacritty`, not the one in `%appdata%`. And it turns out I still had my old config, which had the full path to git bash.

I thought all along that the developers of alacritty just stopped supporting windows.

Thanks again for your time!
