### ISSUE TITLE
I can't use the mouse inside Vim or Neovim

### ISSUE THREAD

**Issue by gmr458** [alacritty/alacritty#5444]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

In my `alacritty.yml` file I have set `TERM: xterm-256color`, I also run `:set ttymouse=sgr` in vim and it does not work.

### System

OS: Windows
Version: alacritty 0.9.0 (fed349a)

**Comment by chrisduerr** [comment]
Because you're running Windows.

**Comment by tjohnman** [comment]
I have encountered this, too. I understand this is a Windows-specific thing, but why is it "nothing Alacritty can do"? Other terminal emulators certainly can do it, so there must be a way.

**Comment by kchibisov** [comment]
The problem is in outdated ConPty shipped with the windows. So you either go and find newer one (from e.g. windows terminal and give it to alacritty) or wait for microsoft to update their libraries given that their own programs can't work with older versions.
