### ISSUE TITLE
[mac] Hide from Dock?

### ISSUE THREAD

**Issue by 097115** [alacritty/alacritty#5446]
OS: macOS
Version: `0.9.0 (fed349a)`

On macOS, having [`LSUIElement`](https://developer.apple.com/documentation/bundleresources/information_property_list/lsuielement) in `Alacritty.app/Contents/Info.plist` set to `<string>1</string>` or `<string>true</string>` [should make](https://apple.stackexchange.com/questions/158485/tried-to-hide-a-dock-icon-but-failed) the application not to appear in Dock. 

However, Alacritty.app seems not to respect this :)

EDIT: may be [this](https://github.com/pyinstaller/pyinstaller/issues/2075) can be of some interest.

**Comment by chrisduerr** [comment]
This is not something I'm interested in explicitly supporting. So if it doesn't work, it doesn't work.

**Comment by 097115** [comment]
Well, it sure won't work if you can't program it properly.

**Comment by chrisduerr** [comment]
Feel free to do it yourself.
