### ISSUE TITLE
Cannot override Right Click ExpandSelection

### ISSUE THREAD

**Issue by snowzach** [alacritty/alacritty#5451]
### System

OS: Windows 10
Version: alacritty 0.9.0 (fed349a)

### Logs
[2021-08-24 23:17:39.316977900] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(WindowId(0x40854)), event: MouseInput { device_id: DeviceId(DeviceId(0)), state: Pressed, button: Right, modifiers: (empty) } }

I am trying to override the right button press to only PasteSelection. If I move the mouse, and then right click it pastes but also expands the selection. If I set right click to None, it still performs the expand selection.

```
mouse_bindings:
 - { mouse: Right,  action: PasteSelection }
```

It seems to me that setting the action to PasteSelection or None should no longer perform ExpandSelection also.

**Comment by chrisduerr** [comment]
This is to be expected. See the changelog for more information.
