### ISSUE TITLE
Run with command and do not close immediately

### ISSUE THREAD

**Issue by m-kru** [alacritty/alacritty#5458]
Is there any way to run alacritty with `-e` or `--command` and leave the newly created window open? By default it gets closed when commands finish.

### System

OS: 20.04.1-Ubuntu
Version: alacritty 0.8.0-dev (28abb1f)

**Comment by chrisduerr** [comment]
`--hold`

**Comment by m-kru** [comment]
My bad, I have not specified everything. I would like it to be interactive. With `--hold` I can only view the results.

**Comment by chrisduerr** [comment]
Then spawn a shell that is interactive. As long as the shell is still running, Alacritty will not close. For an interactive shell, there's no reason why you would need anything like `--hold`.

**Comment by rieje** [comment]
You mean like `alacritty --command bash -ic 'sudo pacman -Syu'? That still closes alacritty immediately after the pacman command exits.

**Comment by hzaphry** [comment]
you might want to add --hold before the -e 
Ex.
`alacritty --hold -e neofetch`

**Comment by ArijanJ** [comment]
@m-kru did you ever figure this out :grin:? 
Running `alacritty -e bash -c 'sleep 1'` doesn't drop to bash once the sleep finishes :(

**Comment by kostabekre** [comment]
You can call a shell as the command for alacritty and give the shell multiple commands, separating with `;`.
Call the shell again as the last command.

Example:
```bash
alacritty --working-directory ~/Documents/WorkVault/ -e zsh -c "nvim;zsh"
```
