### ISSUE TITLE
Setting initial title with `-t` disables changing it later from shell.

### ISSUE THREAD

**Issue by m-kru** [alacritty/alacritty#5459]
I am using following simple command to usually change the terminal title:
```bash
printf "\e]2;$*\a"
```
It works as expected.

However, when I start alacritty with `-t` flag, the title always remains the same as set with `-t`. `printf "\e]2;$*\a"` has no effect anymore. Is it desired behavior? Can it be changed? I wanted to use the `-t` flag to script sessions recreating easily, but it disables changing the title of the terminal dynamically, after the session has been started. 

### System

OS: 20.04.1-Ubuntu
Version: alacritty 0.8.0-dev (28abb1f)

**Comment by chrisduerr** [comment]
> Is it desired behavior?

Yes it is.

> Can it be changed? 

No it cannot. Though you can override it through the config with dynamic title staying active iirc.
