### ISSUE TITLE
Read config from current dir for PORTABLE

### ISSUE THREAD

**Issue by iiiypuk** [alacritty/alacritty#5463]
Make reading `alacritty.yml` from current directory for `PORTABLE` Windows version

**Comment by chrisduerr** [comment]
Just specify the CLI flag to do so.

**Comment by RoyiAvital** [comment]
Is there a documentation for the `CLI` flag to do so?

**Comment by RoyiAvital** [comment]
OK, I found it (Maybe should be part of documentation):

```cmd
Alacritty-<version> --config-file ./alacritty.yml
```

**Comment by chrisduerr** [comment]
> Maybe should be part of documentation

Ah, like the `--help` output or the manpage maybe?
