### ISSUE TITLE
Work with other libraries

### ISSUE THREAD

**Issue by shuqiangzhou** [alacritty/alacritty#5464]
I want make a Executable file that is a gui programs,the same as the vs code terminal,and I use the `native-windows-gui` library or the `iced` to make it,it's provides some controles,I studied your window rendering part,There are some overlapping functions. Can we make this part into tarit and allow other developers to implement it by themselves

for example:
```rust
alacritty::display::window
```

**Comment by chrisduerr** [comment]
No, none of Alacritty's UI will be split up further into libraries.
