### ISSUE TITLE
Occasional state where most-recent keypress is repeated indefinitely

### ISSUE THREAD

**Issue by girzel** [alacritty/alacritty#5471]
### System

OS: Arch Linux
Version: 0.9.0 (fed349aa)
Sway window manager (Wayland)

### Logs

Here's a log of "alacritty --print-events" from a short session exhibiting the behavior below.

https://ericabrahamsen.net/alacritty.log

The error: Every few days, alacritty gets "stuck" in a mode where the most recent keypress repeats indefinitely, as though I were holding the key down. If I type a command like "echo", there's a short pause, and then the "o" is repeated as though I were holding it down. If I type "echo" and hit return quickly, the command is run, and then the return is repeated. If my most-recent keypress is a Command modified key like C-k, the C-k is run correctly (killing the rest of the line), then the "k" is repeated.

Quitting alacritty doesn't fix it: the behavior continues when I start it again. I usually use tmux, but quitting tmux doesn't help, it keeps happening. Only rebooting the machine fixes the problem, until it happens again a few days later.

Hope this is helpful! Happy to help with further debugging.

**Comment by chrisduerr** [comment]
I'd assume you're running the latest version of sway available on Arch?

**Comment by girzel** [comment]
I'm running 1:1.6.1-1, the regular "sway" package. I was running "sway-git" for a while, but there didn't seem to be any real advantage, so switched back to the regular system package.

**Comment by chrisduerr** [comment]
I'd assume the issue happened with both and exists on multiple Alacritty package versions?

**Comment by girzel** [comment]
I only installed Alacritty a week or so ago, when I got the obsoletion notice from termite. I haven't tried with other versions: are there any combinations in particular you'd like me to try?

Thanks!

**Comment by chrisduerr** [comment]
> are there any combinations in particular you'd like me to try?

No, I'm pretty sure that this is unrelated to both Alacritty or Sway version. I'd just like to confirm to make sure.

**Comment by girzel** [comment]
In the meantime, if you have any tips on how I might get out of this state without rebooting the machine, that would be very welcome!

**Comment by Hakuyume** [comment]
Perhaps, the combination of fcitx5 and alacritty is not good. I'm using fcitx5. 
https://github.com/swaywm/sway/issues/6188

**Comment by girzel** [comment]
Hey hey! So am I. Sounds like we have our clue.

**Comment by chrisduerr** [comment]
Can one of you verify that without fcitx5 this issue doesn't occur anymore?

**Comment by Hakuyume** [comment]
When the key-repeat issue occurs, killing fcitx5 solves on-going key repeat.
I'm not sure about "anymore". I can not do the long-term trial since I need fcitx5 for my work.

In my another system that has sway and alacritty but no fcitx5, I have never seen the issue.

I'm wondering https://github.com/fcitx/fcitx5/issues/289 is related to out issue.
Although It seems solved, my fcitx5 does not include the patch.

**Comment by Hakuyume** [comment]
I will try latest fcitx5 that includes the patch.

**Comment by chrisduerr** [comment]
> In the meantime, if you have any tips on how I might get out of this state without rebooting the machine, that would be very welcome!
>> When the key-repeat issue occurs, killing fcitx5 solves on-going key repeat.

I guess that at least gives an answer to that question.

Thanks to the effort put in by @dnkl, it seems like the cause for this issue has at least been identified to be a problem with key repetition and IME(s) like fcitx5. So I don't think there's anything we can do here.

The best place to look for updates on this issue I'm aware of is probably this ticket:
https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/46

There might be something that can be done inside fcitx5 too, but I'm not aware of any issue on their tracker.
