### ISSUE TITLE
Change alacritty's font size based on neovim/vim guifont variable

### ISSUE THREAD

**Issue by IndianBoy42** [alacritty/alacritty#5472]
For reference the guifont variable is document [here](https://neovim.io/doc/user/options.html#'guifont'). Would it be possible to make alacritty change the font size and family based on this variable while neovim is open, and then revert back to alacritty.yml when neovim is closed? Either as a builtin feature to alacritty or as a plugin for neovim that interacts with alacritty?

**Comment by chrisduerr** [comment]
> Would it be possible to make alacritty change the font size and family based on this variable while neovim is open

No.
