### ISSUE TITLE
Most bitmap fonts won't scale

### ISSUE THREAD

**Issue by simtd** [alacritty/alacritty#5475]
### System

OS: Arch Linux
Version: 0.9.0
Linux/BSD: X11, dwm

### Logs

`alacritty -vv` provides the usual output except it has a debug message as well: `[DEBUG] [alacritty_terminal] Term::resize dimensions unchanged`

### Issue

Changing font size has no effect on most bitmap fonts (even though they have different size variants). The only font that works correctly is [Terminus](https://archlinux.org/packages/community/any/terminus-font/). 

I see that Terminus is installed in `/usr/share/fonts/misc` while the other bitmap fonts are installed in `/usr/share/fonts/local`. That's the only difference I know of.

**Comment by simtd** [comment]
Never mind. Restarting the computer fixes the issue.

**Comment by chrisduerr** [comment]
The sizes of bitmap fonts are defined by he font. If you want a freely scalable font, I recommend using one.
