### ISSUE TITLE
Alacritty 0.9.0 dmg has no universal or arm binary

### ISSUE THREAD

**Issue by jlec** [alacritty/alacritty#5477]
Latest dmg has no M1 ready binary. 

```bash
$ Applications/Alacritty.app/Contents/MacOS $ (0) file alacritty
alacritty: Mach-O 64-bit executable x86_64
```

Do I read https://github.com/alacritty/alacritty/issues/4530 correctly that we should have universal binaries available?

### System

OS: macOS - M1
Version: `alacritty 0.9.0 (fed349a)`

**Comment by chrisduerr** [comment]
> Do I read #4530 correctly that we should have universal binaries available?

Not until the next release.
