### ISSUE TITLE
pinyin input bug(china pinyin)

### ISSUE THREAD

**Issue by Elliot2636** [alacritty/alacritty#5478]
When canceling pinyin input, it will delete the input of the terminal。

Thank you very much to the developers🙏, I can’t solve this problem, I have a very short time learning rust

### System

OS: macOS
Version: Alacritty Version 0.9.0

### 
https://user-images.githubusercontent.com/45113206/132314206-9726c6af-9658-4510-b864-a418930159c8.mov

**Comment by Elliot2636** [comment]
### expect

https://user-images.githubusercontent.com/45113206/132314901-076c36c7-dced-432e-abd8-ae4b73429bf3.mov

**Comment by zzhaolei** [comment]
You can check this [issue](https://github.com/alacritty/alacritty/issues/1606)

There is a temporary solution, it is good in most cases: 
```yml
key_bindings:
  - { key: Back, action:  ReceiveChar}
```

PS: Sorry, I used the translation tool to communicate with you

**Comment by chrisduerr** [comment]
Closing as duplicate.
