### ISSUE TITLE
Cannot bind PageUp and PageDown to scroll the correct way

### ISSUE THREAD

**Issue by eternal-sorrow** [alacritty/alacritty#5481]
I'm trying to bind PageUp and PageDown keys so that they would scroll page up and down the scrollback buffer in normal mode, but send the correct escape sequences to apps like Vim or Less. I tried this:

```
  - { key: PageUp,                         mode: ~Alt,  action: ScrollPageUp,  }
  - { key: PageDown,                       mode: ~Alt,  action: ScrollPageDown }
```

But it does not work in apps like vim. Is there any correct way to do this?

### System

OS: Linux
Version: alacritty 0.9.0
Linux/BSD: Wayland, sway

### Logs

Not needed

**Comment by eternal-sorrow** [comment]
Also, the documentation is lacking on the meaning of these "modes". I can guess what does "Vi" and "Search" modes do, but others are mystery to me.

**Comment by chrisduerr** [comment]
> But it does not work in apps like vim.

Of course it doesn't, because vim's scrollback has nothing to do with Alacritty's scrollback. And you're specifically binding it to `~Alt`, while vim runs in the alternate screen buffer.

**Comment by eternal-sorrow** [comment]
> vim's scrollback has nothing to do with Alacritty's scrollback

I know this. But how do I bind it correctly? I thought `~` inverses the mode, so I bind it when `Alt` is not active. But I don't know what exactly `Alt` is though.

**Comment by eternal-sorrow** [comment]
Binding without specifying the mode has the same effect...

**Comment by chrisduerr** [comment]
Alt is the alternative screen buffer. So `~Alt` means it's bound when that is not active. So that binding will never do anything when inside vim.

**Comment by eternal-sorrow** [comment]
> So that binding will never do anything when inside vim.

That's exactly what I want to do. So that this key would pass directly to vim (or similar app) when it's started.

**Comment by eternal-sorrow** [comment]
@chrisduerr can you please tell me what I'm doing wrong?

**Comment by eternal-sorrow** [comment]
@chrisduerr, can you help me configure it?
