### ISSUE TITLE
Clicking URLs with & (ampersand) in them ignores the part after the &

### ISSUE THREAD

**Issue by Bauxitedev** [alacritty/alacritty#5482]
If you click an URL in the terminal with & (ampersand) in them, it ignores the part after the &.
This causes some URLs to be invalid.

### How to reproduce
Try entering ` echo "https://localhost?a=b&c=d"` into the terminal and then click the link.
You'll notice the browser goes to `https://localhost/?a=b` instead of the expected `https://localhost?a=b&c=d`

### System

OS: Windows 10
Version: 0.9.0
Browser: Firefox

**Comment by matthiaskrgr** [comment]
Interesting, on my machine (linux, manjaro) it opened the full and correct url `https://localhost?a=b&c=d`

In my `.config/alacritty/alacritty.yml` I have 
```
selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  ```
  and I don't recall modifying that.

**Comment by Bauxitedev** [comment]
Maybe it's a Windows-only bug? Maybe someone else on Windows 10 could try it...

**Comment by chrisduerr** [comment]
This works perfectly fine. Make sure no other application is running or the uri is broken across lines.

**Comment by Bauxitedev** [comment]
@chrisduerr The url isn't broken across multiple lines, it's a very short url as you can see in the original post. Have you actually tested this on Windows 10?

**Comment by Seadragon91** [comment]
Tested the portable version from latest github releases and can confirm that problem on Windows 10, the ampersands are missing.

**Comment by chrisduerr** [comment]
Likely due to the launcher.

**Comment by Bauxitedev** [comment]
@chrisduerr You're not being very helpful. What do you mean "launcher"? And why haven't you re-opened the issue, seeing as it has been confirmed now by @Seadragon91?

**Comment by mikaello** [comment]
This is still a problem in Windows 10 and Alacritty 0.10.1

```powershell
PS C:\Users\me > alacritty.exe --version
alacritty 0.10.1 (2844606)
```

**Comment by ada-fruit** [comment]
I'm getting this issue in `alacritty 0.14.0 (22a4475)`. Seems related to #7960?
