### ISSUE TITLE
Incorrect rendering of tmux split window

### ISSUE THREAD

**Issue by m8ram** [alacritty/alacritty#5483]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Windows
Version: `alacritty 0.9.0 (fed349a)`

No logs but hopefully the following screenshots make it clear:
* before: WSL started, opened tmux created split panes with `ctrl-b + %`
![image](https://user-images.githubusercontent.com/6831686/132873561-544dea3b-33b9-4f84-b710-064d5daf5623.png)
* Open a file in `less`
![image](https://user-images.githubusercontent.com/6831686/132873781-e8c9fadd-0e92-4c7e-8cd6-d93253c3a620.png)
* screen issues remain after closing the file
![image](https://user-images.githubusercontent.com/6831686/132873859-0d8d56d3-062a-4640-ac37-182dd87443c9.png)

In case it is relevant: a very similar issue occurs using Windows Terminal preview. [The relevant git issue is here](https://github.com/microsoft/terminal/issues/6987).

In fact I was trying alacritty in the hope of being able to use tmux split panes since this bug makes it impossible to do so in Windows Terminal Preview.

**Comment by chrisduerr** [comment]
> In case it is relevant: a very similar issue occurs using Windows Terminal preview.

That's probably because it's a Windows bug. Chances are unless you can reproduce it on Linux/macOS it's a Windows issue.
