### ISSUE TITLE
The username and path lost its color automatically presumably after I ssh'ed with my phone into the pc.

### ISSUE THREAD

**Issue by prateekamana** [alacritty/alacritty#5486]
https://imgur.com/a/R4VVJTS

### System

OS: Linux Mint
Version: 0.9.0 
Linux/BSD: Qtile

**Comment by chrisduerr** [comment]
This is most likely due to terminfo. Alacritty itself certainly has nothing to do with it.

**Comment by prateekamana** [comment]
But other terminals are working fine, how could I fix it then? I've tried doing a clean install, didn't fix it... is there a setting in config that I can maybe change?

**Comment by chrisduerr** [comment]
Either change the $TERM, or change the config.

**Comment by abhemanyus** [comment]
My $TERM is set to alacritty, yet I do not have any fancy username highlighting.

**Comment by abhemanyus** [comment]
For anyone wondering how to fix this, set the TERM variable in the env section of alacritty.yml to xterm-256color
