### ISSUE TITLE
Some Vim-shortcuts doesnt work in alacritty vim-mode 

### ISSUE THREAD

**Issue by HappyCthulhu** [alacritty/alacritty#5487]
### System

OS: Ubuntu 20.04, i3wm
Version: alacritty 0.8.0-dev (28abb1f)

### Logs

Hi! I love Vim mode alacritty. Thats main reason, why i use it. Unfortunately, it works pretty bad for me: many shortcuts doesnt work at all, like:

- Shift + $
- Shift + { / Shift+}
- Shift + ( / Shift + )
- f + *some_letter*
- t + *some_letter*

And other command. 

Please, tell me, can u fix this?

**Comment by chrisduerr** [comment]
> Please, tell me, can u fix this?

No. Some shortcuts don't work and that will never change.

**Comment by steveeJ** [comment]
@chrisduerr i can't tell whether you were being sarcastic. on a more serious note i can't imagine that all of the unimplemented shortcuts are equally difficult. i'm specifically interested about the "Shift + $" to complement the already implemented "0".
