### ISSUE TITLE
Error: linking with "cc" failed, exit status code 1

### ISSUE THREAD

**Issue by flxinxout** [alacritty/alacritty#5488]
**FIXED -> install the package libxkbcommon-dev (zypper install libxkbcommon-dev) and then re-compiled !**
Thanks to this post: #5279

Hello.

I'm trying to install Alacritty for openSUSE Leap 15.3 (KDE Plasma) with the dependencies page on github. I have a problem with the compilation at the end with the `cargo build --release` command.

Here is an image of the error: http://image.noelshack.com/fichiers/2021/37/1/1631531322-screenshot-20210913-130734.png

### System

OS: openSUSE Leap 15.3

### Logs
The error is: error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/home/flxinxout/Documents/Development/Alacritty/alacritty/target/release/deps/alacritty-d92d0dc0fe63f9b8.alacritty.6d1eef71-cgu.7.rcgu.o" "-Wl,--as-needed" "-L" "/home/flxinxout/Documents/Development/Alacritty/alacritty/target/release/deps" "-L" "/usr/lib64" "-L" "/usr/lib64" "-L" "/usr/lib64" "-L" "/usr/lib64" "-L" "/home/flxinxout/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,--start-group" "-Wl,--end-group" "-Wl,-Bstatic" "/home/flxinxout/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-dd7db1bec6909f24.rlib" "-Wl,-Bdynamic" "-lfreetype" "-lfontconfig" "-lfreetype" "-lexpat" "-lfreetype" "-lxcb" "-lxcb-render" "-lxcb-shape" "-lxcb-xfixes" "-lxkbcommon" "-ldl" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/home/flxinxout/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/flxinxout/Documents/Development/Alacritty/alacritty/target/release/deps/alacritty-d92d0dc0fe63f9b8" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs"
  = note: /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lxkbcommon
          collect2: error: ld returned 1 exit status

thank you in advanced !

**Comment by plibither8** [comment]
I'm facing this error too, Ubuntu 20.04.

**Comment by flxinxout** [comment]
> I'm facing this error too, Ubuntu 20.04.

I just did what's written on the installation page but yes there is no issues...

**Comment by chrisduerr** [comment]
Have you installed all the dependencies listed in the INSTALL.md?

**Comment by chrisduerr** [comment]
Can you try to install libxkbcommon? There's recently been a bit of a split-up with the X crates so it might be necessary to add that to the documentation.

**Comment by flxinxout** [comment]
**FIXED** -> install the package libxkbcommon-dev (zypper install libxkbcommon-dev) and then re-compiled !

Thanks to this post: https://github.com/alacritty/alacritty/pull/5279

**Comment by chrisduerr** [comment]
> FIXED -> install the package libxkbcommon-dev (zypper install libxkbcommon-dev) and then re-compiled !

Would you mind sending a PR to add this to the INSTALL.md?

**Comment by flxinxout** [comment]
> > FIXED -> install the package libxkbcommon-dev (zypper install libxkbcommon-dev) and then re-compiled !
> 
> Would you mind sending a PR to add this to the INSTALL.md?

I'm sorry I'm not English. What is a PR?

**Comment by chrisduerr** [comment]
A pull request. Updating the documentation so other people can just copy/paste the example install instructions.

**Comment by flxinxout** [comment]
> A pull request. Updating the documentation so other people can just copy/paste the example install instructions.

Okey I see. But when I click on new pull request, it asks me the branch to and the branch from. The branch to is the master right ? But which branch from I have to choose ?

**Comment by chrisduerr** [comment]
Created one myself: https://github.com/alacritty/alacritty/pull/5489
