### ISSUE TITLE
Open URL in terminal browser.

### ISSUE THREAD

**Issue by in3rsha** [alacritty/alacritty#5490]
I'm trying to get URLs to open in a terminal browser (links2) when I click on them, but they always open in Firefox. I'm running alacritty 0.10.0-dev on XFCE.

This is the configuration I've added to **alacritty.yml**:

```
mouse:
  url_launcher:
    program: /usr/bin/links2
```

I've tried using Shift+click, but URLs still open in Firefox. I'm guessing there is something in XFCE that is overriding URL clicks.

I've also tried removing the default WebBrowser line from `~/.config/xfce4/helpers.rc`, but the next time I click on a URL from inside alacritty a notification pops up asking me to choose a default browser to open URLs with.

Has anyone had any luck in setting the browser alacritty uses for URLs on XFCE?

**Comment by chrisduerr** [comment]
How exactly do you expect that to work? Do you want to open a new terminal?

**Comment by in3rsha** [comment]
I was hoping I could click the link and it would run `links2 URL` in the current terminal.

**Comment by chrisduerr** [comment]
That doesn't really work, since Alacritty can't launch any applications. You need a shell to do so and Alacritty has no knowledge about that.

So there's no non-hacky way to do this, unless you spawn a new terminal emulator.

**Comment by in3rsha** [comment]
Okay no problem, thanks for letting me know.

Thank you also for the excellent terminal emulator. It's amazing.
