### ISSUE TITLE
Decreasing startup time

### ISSUE THREAD

**Issue by inoshy** [alacritty/alacritty#5498]
At first I want to thank the devs for the effort behind this awesome project.

Alacritty has a noticable amount of delay when it starts up, compared to a terminal like foot. It takes ~150 ms to load alacritty. Is there anything I can do to reduce the startup time? Like removing some problematic dependencies? Thanks!

**Comment by chrisduerr** [comment]
The startup time mostly depends on your OpenGL driver. Thus there's not much Alacritty can do other than #5403.
