### ISSUE TITLE
UK keyboard layout: '#' and '~' key not working on Linux with x11

### ISSUE THREAD

**Issue by basile-henry** [alacritty/alacritty#55]
I've just quickly followed the dependencies for keyboard input. It looks like alacritty depends on [glutin](https://github.com/tomaka/glutin/) which for linux depends on [winit](https://github.com/tomaka/winit) and I found the following lines are commented out in the most recent version [src/api/x11/events.rs#L177](https://github.com/tomaka/winit/blob/master/src/api/x11/events.rs#L177) and [src/api/x11/events.rs#L270](https://github.com/tomaka/winit/blob/master/src/api/x11/events.rs#L270).

This seems to be relevant to my issue but I am unsure why it has been commented out. If this is the reason then the layout of my keyboard is irrelevant and most likely other linux users would have the same problem.

Having encountered the issue while using alacritty I'm submitting an issue here but should I also post an issue on winit? Or is there another reason for this issue?

**Comment by jwilm** [comment]
This problem would need to be fixed upstream in `winit` as you've suggested. Alacritty is actually on an older for of `glutin` from before the split, and so there would still be some work here to get an upstream patch.

**Comment by basile-henry** [comment]
I'll see if I can fix it tomorrow. Any particular reason you are using an older version of `glutin`? Is it changing too often?

**Comment by jwilm** [comment]
There was a couple of features needed for this project that I was having trouble getting feedback on. Specifically, keyboard modifiers needed to be parsed out of the underlying windowing system event and passed with `glutin::Event::KeyboardInput`. I also needed the received `char`(s) to be passed with the event. The latter feature was necessary for either running a key binding or printing the character. For example, you wouldn't want `Command-C` to also print a `c` when trying to copy the selection.

**Comment by jwilm** [comment]
In any case, it's on my list to try and upstream the patches and get back on the main glutin tree.

**Comment by basile-henry** [comment]
I found a fix for this issue! Here are the diffs that I am applying on top of https://github.com/jwilm/glutin/commit/af7fe340bd4a2af53ea521defcb4f377cdc588cf which is the version of glutin alacritty currently depends on:

```diff
diff --git a/src/api/x11/events.rs b/src/api/x11/events.rs
index 4754b1dc..5345af35 100644
--- a/src/api/x11/events.rs
+++ b/src/api/x11/events.rs
@@ -174,7 +174,7 @@ pub fn keycode_to_element(scancode: libc::c_uint) -> Option<VirtualKeyCode> {
         ffi::XK_space => events::VirtualKeyCode::Space,
         //ffi::XK_exclam => events::VirtualKeyCode::Exclam,
         //ffi::XK_quotedbl => events::VirtualKeyCode::Quotedbl,
-        //ffi::XK_numbersign => events::VirtualKeyCode::Numbersign,
+        ffi::XK_numbersign => events::VirtualKeyCode::Numbersign,
         //ffi::XK_dollar => events::VirtualKeyCode::Dollar,
         //ffi::XK_percent => events::VirtualKeyCode::Percent,
         //ffi::XK_ampersand => events::VirtualKeyCode::Ampersand,
@@ -267,7 +267,7 @@ pub fn keycode_to_element(scancode: libc::c_uint) -> Option<VirtualKeyCode> {
         //ffi::XK_braceleft => events::VirtualKeyCode::Braceleft,
         //ffi::XK_bar => events::VirtualKeyCode::Bar,
         //ffi::XK_braceright => events::VirtualKeyCode::Braceright,
-        //ffi::XK_asciitilde => events::VirtualKeyCode::Asciitilde,
+        ffi::XK_asciitilde => events::VirtualKeyCode::Asciitilde,
         //ffi::XK_nobreakspace => events::VirtualKeyCode::Nobreakspace,
         //ffi::XK_exclamdown => events::VirtualKeyCode::Exclamdown,
         //ffi::XK_cent => events::VirtualKeyCode::Cent,
diff --git a/src/events.rs b/src/events.rs
index 69b4710d..72188da6 100644
--- a/src/events.rs
+++ b/src/events.rs
@@ -256,6 +256,7 @@ pub enum VirtualKeyCode {
     Add,
     Apostrophe,
     Apps,
+    Asciitilde,
     At,
     Ax,
     Backslash,
@@ -287,6 +288,7 @@ pub enum VirtualKeyCode {
     NavigateBackward, // also called "Next"
     NextTrack,
     NoConvert,
+    Numbersign,
     NumpadComma,
     NumpadEnter,
     NumpadEquals,
```

This is obviously just a temporary solution waiting for proper patches upstream so I don't know if you'd want to make these changes in your version of glutin. This works for me so I just wanted to share! 😃 

It's possible other useful keys are not yet enabled but I haven't encountered them yet.

Great work with alacritty! I see it's becoming very popular, definitely deserved!

**Comment by chrisduerr** [comment]
Should be fixed by https://github.com/rust-windowing/winit/pull/1266.

**Comment by pwnorbitals** [comment]
Can we confirm this is fixed ? If so, the issue can be closed

**Comment by kchibisov** [comment]
if you  can see the mentioned PR isn't yet landed.
