### ISSUE TITLE
Drag + drop without automatic trailing space?

### ISSUE THREAD

**Issue by Jason1923** [alacritty/alacritty#5500]
Hi, does Alacritty support dragging + dropping a file without inserting a trailing space at the end? My use case is to escape paths using double quotes (since it doesn't escape automatically as per #1335). I quote, drag + drop, then I must backspace to remove the space, then unquote. It's a pretty small nitpick but it would be neat if it were configurable.

**Comment by chrisduerr** [comment]
> It's a pretty small nitpick but it would be neat if it were configurable.

This issue was discussed previously already and deemed not worth it for a configuration option.
