### ISSUE TITLE
Wrong icon rendering

### ISSUE THREAD

**Issue by helderburato** [alacritty/alacritty#5503]
I would like to know if someone has this icon rendering wrongly too, and if so, how to fix that.

<img width="797" alt="Screenshot 2021-09-21 at 18 33 48" src="https://user-images.githubusercontent.com/862575/134219729-1b52d352-40da-4c70-9592-e8eff97f064b.png">

Note: It is just a small issue, nothing blocking to me, I just trying to figure out.

### System

OS: macOS
Version: alacritty 0.9.0 (fed349a)

**Comment by chrisduerr** [comment]
If something isn't rendering, it's likely due to missing fonts.
