### ISSUE TITLE
windows bracketed-paste support ?

### ISSUE THREAD

**Issue by mckellygit** [alacritty/alacritty#5506]
Hi,

ty for Alacritty.
Had to move some work to Windows.
Just a question really, can Alacritty on Win 10 support bracketed-paste ?

thx,
-m

**Comment by chrisduerr** [comment]
Probably. Nothing in Alacritty stopping anything from emitting the escape.

**Comment by mckellygit** [comment]
@chrisduerr hi,
ok, last attempt, only since I have to use Windows sometimes, if I run -
win32yank.exe -o from the shell it outputs the clipboard properly.  So I wondered if a binding such as -
  - { key: V,   mods: Control|Shift,   command: { program: "win32yank.exe", args: [ "-o" ] } }
might just work, but it doesn't.
Is it possible to run a program from a binding and have its output go to the shell ?

thx again for alacritty,
-m

**Comment by mckellygit** [comment]
Scratch that question above, I'll keep playing around.  Take care.
