### ISSUE TITLE
Ctrl-Left and Ctrl-Right not jumping words

### ISSUE THREAD

**Issue by tomasz13nocon** [alacritty/alacritty#5508]
I'm having an issue with ctrl-left and ctrl-right.
bpierce1's solution from #1408 does not seem to work for me.
I'm using bash.

### Expected behavior
ctrl-left and ctrl-right should jump between words in normal mode, as well as when typing vim commands. This is the behavior I'm getting in termite and xterm (but for some reason not urxvt).
### Acutal behavior
With bpierce1's keybinds from #1408 Ctrl-left in normal mode works as expected, however ctrl-right doesn't do anything, and both of them aren't working when typing vim commands, they just close the command.

**Comment by chrisduerr** [comment]
What does ^V -> ^Left/Right give you?

**Comment by tomasz13nocon** [comment]
^[f
^[b

**Comment by chrisduerr** [comment]
Do you have custom keybindings? If so, please remove them.

**Comment by tomasz13nocon** [comment]
I don't have these keys bound in anything else other than alacritty, if that's what you mean.
Without the keybinds from the mentioned issue I get the default behavior of deleting 5 lines, and the output from ^V is:
^[[1;5C
^[[1;5D

**Comment by chrisduerr** [comment]
> the output from ^V is:
> ^[[1;5C
> ^[[1;5D

That's the output that is supposed to be emitted, so looks good to me.

**Comment by tomasz13nocon** [comment]
I'm sorry, I wasn't clear.
My intention is to change this default behavior so that ctrl-left jumps to previous word and ctrl-right jump to next word in vim.
This is what they do by default in termite and xterm. This is also what happens in a terminal prompt, outside of vim. Try typing a couple of words into the terminal and pressing ctrl-left to go between them to see what I mean. This is the behavior I'd like to have in vim.

So I want to somehow disable these default mapings: `[1;5C` `[1;5D`

**Comment by tomasz13nocon** [comment]
I've since found another issue which this one is a duplicate of (I'm sorry for not searching well enough):
#919 
To summarize:
On vim with $TERM set to "alacritty" (which vim reads and sets its "term" option to) Ctrl-left and right delete 5 lines instead of jumping words.
Neovim doesn't have this issue.
Current workaronds are to add one of these to vimrc:

```
map <ESC>[1;5A <C-Up>
map <ESC>[1;5B <C-Down>
map <ESC>[1;5C <C-Right>
map <ESC>[1;5D <C-Left>
imap <ESC>[1;5A <C-Up>
imap <ESC>[1;5B <C-Down>
imap <ESC>[1;5C <C-Right>
imap <ESC>[1;5D <C-Left>
```
or
```
set term=xterm-256color
```
The second one is shorter but could have some side effects.

**Comment by NiceGuyIT** [comment]
Like OP, I'm using Bash which uses [readline][] to interpret key bindings set in `/etc/inputrc` and/or `~/.inputrc`. The StackOverflow answer to [move cursor between words in bash] has this in `inputrc`. Only the firsts two are needed for Ctrl-{arrow left/right} to work. The others are for other terminal emulators.

```inputrc
# mappings for Ctrl-left-arrow and Ctrl-right-arrow for word moving
"\e[1;5C": forward-word
"\e[1;5D": backward-word
"\e[5C": forward-word
"\e[5D": backward-word
"\e\e[C": forward-word
"\e\e[D": backward-word
```

[readline]: https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Readline-Init-File
[move cursor between words in bash]: https://stackoverflow.com/questions/5029118/bash-ctrl-to-move-cursor-between-words-strings
