### ISSUE TITLE
Open WSL2 shell when opening Alacritty

### ISSUE THREAD

**Issue by wespiard** [alacritty/alacritty#5509]
When trying to open WSL2 as the default shell, I added the following to my yml config file: 
```
shell:
  program: "C:\\Windows\\System32\\wsl.exe"
```

After this, when opening Alacritty, a terminal window opens, but has no text. Then, after 5-10 seconds it closes. See attached screenshot. 

![alacritty_issue](https://user-images.githubusercontent.com/1278350/134722437-622ddf84-bf4e-402a-8106-b9d873092b79.png)

### System

OS: Windows
Version: alacritty 0.9.0 (fed349a)

### Logs

N/A, no log file generated.

**Comment by wespiard** [comment]
I got it working by adding an argument specifying the distro to run: 

```
shell:
  program: "C:\\Windows\\System32\\wsl.exe"
  args: 
    - -d Ubuntu-20.04
```

Now I just need to figure out how to set the default PWD to /home/<user> instead of /mnt/c/system32.

**Comment by chrisduerr** [comment]
This seems unrelated to Alacritty.

**Comment by wespiard** [comment]
> This seems unrelated to Alacritty.

The solution that I came up with ended up being to modify the Alacritty config as follows: 

```
shell:
  program: "C:\\Windows\\System32\\wsl.exe"
  args: 
    - -d Ubuntu-20.04

working_directory: \\wsl$\Ubuntu-20.04\home\{WSL username}
```

Note that the distro version and username will probably differ. 

If there is a cleaner solution (I'm sure there is.., I'm new to both WSL and Alacritty), then I'd be happy to be filled in so I can do it the right way.

**Comment by RichardBlair** [comment]
Thanks for sharing this, it got me started down the right path. I was able to get wsl to open to the home directly with a slightly simpler config.

```
shell:
  program: "C:\\Windows\\System32\\wsl.exe ~"
```

(Sorry to the maintainers, I know this is closed. Google brought me here pretty quick so I thought there may be some value in sharing)

**Comment by crazyoptimist** [comment]
Even simpler:

```yaml
shell:
  program: ubuntu
```

**Comment by alinademi** [comment]
> Even simpler:
> 
> ```yaml
> shell:
>   program: ubuntu
> ```

This assumes that your default distro is ubuntu. If not then @RichardBlair 's answer is the best.

**Comment by hitomi1** [comment]
> > This seems unrelated to Alacritty.
> 
> The solution that I came up with ended up being to modify the Alacritty config as follows:
> 
> ```
> shell:
>   program: "C:\\Windows\\System32\\wsl.exe"
>   args: 
>     - -d Ubuntu-20.04
> 
> working_directory: \\wsl$\Ubuntu-20.04\home\{WSL username}
> ```
> 
> Note that the distro version and username will probably differ.
> 
> If there is a cleaner solution (I'm sure there is.., I'm new to both WSL and Alacritty), then I'd be happy to be filled in so I can do it the right way.

Create an alacritty.toml (yaml is deprecated) and use this:

`[shell]
args = ["--cd ~"]
program = 'C:\Windows\System32\wsl.exe'
`
The problem with:

`shell:
  program: ubuntu`
Is that if your distro isn't Ubuntu or is another version than the default one, it doesn't recognizes the command.

**Comment by Muzammil-hasan** [comment]
This works for me:

```
[shell]
program = 'Ubuntu'
```

My entire config in toml

```
[shell]
program = 'Ubuntu'

[env]
TERM = "xterm-256color"

[window]
padding.x = 20
padding.y = 20

decorations = "none"

opacity = 0.7
blur = true

option_as_alt = "Both"

dimensions.columns = 130
dimensions.lines = 42
position.x = 250
position.y = 20

[font]
normal.family = "FiraCode Nerd Font"

[cursor]
style.blinking = "On"
```

**Comment by saquibherman** [comment]
The below configurations work for me.

import = [
    "C:/Users/40121350/AppData/Roaming/alacritty/themes/themes/coolnight.toml"
]

[shell]
program = 'C:\Program Files\WSL\wsl.exe'
args = ["--cd ~"]

[env]
TERM = "xterm-256color"

**Comment by Initsnow** [comment]
In fact, the Windows Terminal configuration file can be clearly seen
But I also found another problem. If you are using shortcut keys to open the program, you also need to enter %USERPROFILE% in the starting position to let the program start in the Windows user directory, otherwise it will start in c/Windows/system32.

**Comment by Muzammil-hasan** [comment]
> In fact, the Windows Terminal configuration file can be clearly seen But I also found another problem. If you are using shortcut keys to open the program, you also need to enter %USERPROFILE% in the starting position to let the program start in the Windows user directory, otherwise it will start in c/Windows/system32.

[Try this](https://github.com/alacritty/alacritty/issues/5509#issuecomment-2094203793)

**Comment by Slava-Ini** [comment]
Because `[shell]` is now depricated, you can do this instead:
```toml
[terminal]
shell = { program = 'C:\Program Files\WSL\wsl.exe', args = ["--cd ~"] }
```
