### ISSUE TITLE
Font Awesome icons don't work in Alacritty

### ISSUE THREAD

**Issue by amarakon** [alacritty/alacritty#5513]
### System

OS: Gentoo [GNU/Linux]
Version: 0.9.0

These font settings work just fine:
family: Fira Code
family: Fira Mono

But when I try to set the second font to fontawesome, everything looks weird and distorted:
family: Fira Code
family: Font Awesome 5 Free Solid

I'm doing this so that I can have the icons working in lsd, which is basically ls but with icons and other stuff.

**Comment by chrisduerr** [comment]
There is no "second font". There is only one font and everything else is configured through fontconfig.
