### ISSUE TITLE
How do I edit fontconfig?

### ISSUE THREAD

**Issue by amarakon** [alacritty/alacritty#5514]
I made an issue stating that Font Awesome wasn't working as a second font. Someone replied by saying "There is no "second font". There is only one font and everything else is configured through fontconfig." 
https://github.com/alacritty/alacritty/issues/5513

He then immediately closed the issue without telling me how I'm supposed to configure fontconfig. Can someone tell me how to do that?

**Comment by chrisduerr** [comment]
Not an Alacritty question.
