### ISSUE TITLE
draw_bold_text_with_bright_colors: true doesn't do anything, i3wm

### ISSUE THREAD

**Issue by qkweint** [alacritty/alacritty#5519]
OS: linux manjaro
Version: Alacritty 0.9.0
Linux/BSD: X11 compton i3wm

Adding the option draw_bold_text_with_bright_colors does no difference. this problem doesn't persist in other terminals such as gnome-terminal, I have made sure the bright and normal colors are different in a noticeable amount.
I am checking the bold color with "set_color -o; echo color" on fish shell.

**Comment by chrisduerr** [comment]
The setting works, this is an issue on your end.
