### ISSUE TITLE
macOS M1; `uname -m` returns `x86_64` after reboot but `arm64` pre reboot?!

### ISSUE THREAD

**Issue by molleweide** [alacritty/alacritty#5522]
Hi,

I am running the Alacritty terminal emulator on MacOS.
After rebooting my `M1 Macbook Air`, running `uname -m` returns `x86_64`
when it previously returned `arm64` before rebooting.
If I check the same command in the regular `Terminal.app.` it returns
`arm64` which is what it is supposed to do on M1 macs from what I understand.
Has anyone else stumbled upon this issue here? Is this an appropriate place
to ask for help on this issue? 

I have build scripts on my M1 mac that depends on `uname -m` returning `arm64`
which worked perfectly until yesterday and now after having rebooted my scripts 
don't work because they get `x86_64`.

Also I want to tell you that I am not an expert so I hope that I am not making
any stupid beginners mistake whilst reporting this. I will be digging further
to see what I could have done wrong. Please forgive me if this has nothing todo with
Alacritty and I should have gone elsewhere for help/advice.

### System

OS: macOS
Version: 0.9.0

**Comment by chrisduerr** [comment]
Likely due to things running through emulation. Alacritty can be compiled for both, so it's up to you.

**Comment by molleweide** [comment]
Allright, thanks for replying Chris.

**Comment by wireframing** [comment]
> Hi,
> 
> I am running the Alacritty terminal emulator on MacOS. After rebooting my `M1 Macbook Air`, running `uname -m` returns `x86_64` when it previously returned `arm64` before rebooting. If I check the same command in the regular `Terminal.app.` it returns `arm64` which is what it is supposed to do on M1 macs from what I understand. Has anyone else stumbled upon this issue here? Is this an appropriate place to ask for help on this issue?
> 
> I have build scripts on my M1 mac that depends on `uname -m` returning `arm64` which worked perfectly until yesterday and now after having rebooted my scripts don't work because they get `x86_64`.
> 
> Also I want to tell you that I am not an expert so I hope that I am not making any stupid beginners mistake whilst reporting this. I will be digging further to see what I could have done wrong. Please forgive me if this has nothing todo with Alacritty and I should have gone elsewhere for help/advice.
> 
> ### System
> OS: macOS Version: 0.9.0

sorry to bother in here but how can I make it run under arm64 and not x86_64?

sry very new to macOS
