### ISSUE TITLE
Jump to the previous word

### ISSUE THREAD

**Issue by brokeyourbike** [alacritty/alacritty#5523]
### System

OS: macOS
Version: alacritty 0.9.0 (fed349a)

I am curious if there is a way to go to the previous or next word without entering the vi mode. I used Alt+Left, Alt+Right in the previous terminal and thought it's a common shortcut, but apparently this is not the case.

Can you please suggest if there is a solution for this request?

**Comment by chrisduerr** [comment]
This is up to your shell.
