### ISSUE TITLE
Interrupt issue with cat

### ISSUE THREAD

**Issue by lfalkau** [alacritty/alacritty#5524]
When I interrupt a `cat /dev/random` with `ctrl-c`, it often prints a sequence of several '6c' characters after the next prompt. Sometimes the next prompt isn't printed at all and stdin seems not responding.
Note that the same issue happends with `cat /dev/random`
Note also that the issue doesn't appear when using `cat -u` instead

### System

OS: macOS Big Sur
Version: `0.9.0-rc3` (from MacOS 'get info' GUI)

### Logs

<img width="779" alt="Screenshot 2021-10-02 at 12 29 19" src="https://user-images.githubusercontent.com/86232144/135712573-16ef87f4-2e6f-47e6-a30b-aa13b857bc96.png">

**Comment by chrisduerr** [comment]
Working as expected.
