### ISSUE TITLE
Add `Control+Shift+N` to `SpawnNewInstance` for Linux and Windows

### ISSUE THREAD

**Issue by alexherbo2** [alacritty/alacritty#5532]
macOS has `Command+N` to `SpawnNewInstance`, but Linux, BSD and Windows do not have equivalent by default.

See [`alacritty.yml`] for details.

[`alacritty.yml`]: https://github.com/alacritty/alacritty/blob/master/alacritty.yml

**Comment by chrisduerr** [comment]
There is no default binding to do this on Linux/BSD DEs, so why would Alacritty offer it? The macOS binding exists because it's a standard OS binding, such a thing just doesn't exist on Linux.

I'm not sure about Windows.

**Comment by jchook** [comment]
+1 for adding `Ctrl+Shift+N` to the default keybindings

**Comment by AdrienGiboire** [comment]
I tried to add it to my configuration file and it does work anyway :sweat_smile: Do I miss something?

```
key_bindings:
  - { key: N, mods: Control|Shift, command: SpawnNewInstance }
```

**Comment by arpangreat** [comment]
> I tried to add it to my configuration file and it does work anyway :sweat_smile: Do I miss something?
> 
> ```
> key_bindings:
>   - { key: N, mods: Control|Shift, command: SpawnNewInstance }
> ```
> 
> ![image](https://user-images.githubusercontent.com/394860/154517836-0a91a3fc-ac98-4d9a-8a43-2e7750ffcddc.png)
> 

I am pretty sure about that it's a macOS only feature :)

**Comment by chrisduerr** [comment]
> I am pretty sure about that it's a macOS only feature :)

It's not, read the configuration documentation please.

Also closing since I have no plan to add a default binding for `SpawnNewInstance` to Linux at the moment.

**Comment by gpetrovic-meltin** [comment]
> I tried to add it to my configuration file and it does work anyway sweat_smile Do I miss something?
> 
> ```
> key_bindings:
>   - { key: N, mods: Control|Shift, command: SpawnNewInstance }
> ```
> 
> ![image](https://user-images.githubusercontent.com/394860/154517836-0a91a3fc-ac98-4d9a-8a43-2e7750ffcddc.png)


In case someone stumbles here, it's not `command`, but `action`.
You need this:
```
key_bindings:
  - { key: N, mods: Control|Shift, action: SpawnNewInstance }
```
