### ISSUE TITLE
It's there a way to run action without keymap?

### ISSUE THREAD

**Issue by yyangdid** [alacritty/alacritty#5540]
System: Windows10
Alacritty version: 0.9

I want remap keybind, :
```
- { key: L,         mods: Control,                   action: None}
- { key: L,         mods: Control|Alt|Shift,      action: ClearLogNotice }
```
But two  `|` not work.

So, I think send and run an Alaritty action(like `ClearLogNotice`) to Alaritty use AutoHotKey, and I'll never have to worry about key conflicts.

It's there a way to run action without keymap? or keybind an action use `modes:Control|Alt|Super|Shift` ?

**Comment by chrisduerr** [comment]
You can bind using multiple mods, but you must have a keybind. To see exactly what you should specify to bind a key you can check the KeyboardInput events in the `--print-events` output.
