### ISSUE TITLE
Smooth scrolling for halfpageup/down

### ISSUE THREAD

**Issue by txtyash** [alacritty/alacritty#5541]
I never like to use mouse/trackpad. Navigation with keyboard is terrible as the best possible options for scrolling are VI mode and halfpageup and halfpagedown. I would rather stick to halfpagedown/up but it's not smooth with any terminal and hinders vision because I have to track down the part where I was previously looking at. It's quite annoying.

A simple solution to this would be physics based scrolling for halfpageup/down like [this plugin](https://github.com/yuttie/comfortable-motion.vim).

**Comment by chrisduerr** [comment]
#2053.
