### ISSUE TITLE
Always asking me to give access permission event i already allow

### ISSUE THREAD

**Issue by hongphong177** [alacritty/alacritty#5546]
Hi,
Marcos always asking me to give access to some folders(Desktop, Document, ...) event I already checked to Full Disk Access 
it's very annoying, so if anything I can do to stop it pls help

![Screen Shot 2021-10-16 at 5 52 14 PM](https://user-images.githubusercontent.com/58673908/137584646-e94dfeea-4fae-4aa2-b658-584b7e89f320.png)

### System

OS: macOS 11.6
Version: 0.9.0

**Comment by chrisduerr** [comment]
Alacritty has nothing to do with opening or storing permission requests, that's up to macOS.

How did you install your Alacritty?

**Comment by boolanger** [comment]
I had the same issue when running alacritty as a universal binary on my M1 macbook air, built following [these instructions](https://github.com/alacritty/alacritty/pull/4727#issuecomment-937892278). The problem does not appear when running the x86 binary installed through homebrew.

**Comment by reportaman** [comment]
Use this method instead, I never got permissions issue on Apple M1 macOS using them:

https://github.com/alacritty/alacritty/blob/master/INSTALL.md#macos
```
make app
cp -r target/release/osx/Alacritty.app /Applications/
```

And the follow the post-build instructions for terminfo: https://github.com/alacritty/alacritty/blob/master/INSTALL.md#post-build
