### ISSUE TITLE
system keybindings are overridden/absorbed

### ISSUE THREAD

**Issue by benkovy** [alacritty/alacritty#5557]
In my system settings I have bound `Control+Left` and `Control+Right` to be shortcuts to switch workspaces - I am coming from mac and now using Ubuntu.

It seems all `control` key bindings are being absorbed by alacrity - which makes sense. However, is there a way to configure a keybinding to be passed through to the system/os?

### System

OS: `Linux`
Version: `alacritty 0.10.0-dev (f90dd12e)`
Linux/BSD: `Ubuntu 20.04`

**Comment by chrisduerr** [comment]
There's no way for Alacritty to "absorb" anything. It's up to your system to forward these keybindings to Alacritty first.
