### ISSUE TITLE
Allow passing arguments to `alacritty msg create-window`

### ISSUE THREAD

**Issue by chrisduerr** [alacritty/alacritty#5560]
The `alacritty msg create-window` command currently takes no parameters.

Ideally it should be possible to have the same Alacritty instance running, but spawn windows using different commands using the `-e` parameter. Passing other arguments like `--working-directory` might also make sense.

**Comment by atchim** [comment]
It may be good to have a flag that forces the terminal to "spawn" even if it couldn't create a window through IPC. This would make it easier to ensure that a command would actually launch Alacritty, no matter what.

**Comment by kchibisov** [comment]
>It may be good to have a flag that forces the terminal to "spawn" even if it couldn't create a window through IPC. This would make it easier to ensure that a command would actually launch Alacritty, no matter what.

I'm not sure why you'd need a flag for that, something like `alacritty msg create-window || alacritty` should work.

**Comment by atchim** [comment]
@kchibisov, a good reason for this is to reduce the verbosity of the command. The following configuration for [sxhkd](https://github.com/baskerville/sxhkd) exemplifies it.
```
# Command without the flag to force Alacritty to spawn...
super + space ; m
  alacritty msg create-window --class popup -e alsamixer -g || alacritty --class popup -e alsamixer -g

# Command with the flag, which in this case is `-f`...
super + space ; m
  alacritty msg create-window --class popup -f -e alsamixer -g
```

**Comment by chrisduerr** [comment]
Completely pointless to add logic to Alacritty for that to "reduce verbosity" of an absolutely trivial shell chain.

**Comment by atchim** [comment]
@chrisduerr, sorry for this pointless feature request, so...

**Comment by atchim** [comment]
When creating a new window through the `msg create-window` subcommand, the `--class` and `--title` options doesn't work as suposed, this is, the created window always has class and title properties set to "Alacritty".

**Comment by atchim** [comment]
> ... the created window always has class and title properties set to "Alacritty".

Actually, the created window inherits the properties from the "main" window.

**Comment by chrisduerr** [comment]
What made you think `--class` and `--title` could be set on a per-window basis? Trying so alone will throw you an error.

**Comment by atchim** [comment]
@chrisduerr, I think you got me wrong.

According to the output of `alacritty --help`, the user can successfully run the command below.

```sh
alacritty --class foo,bar --title baz msg create-window
```

Indeed the previous command runs successfully. The expected behavior, still according to its man page, is that the created window would have the class property set to `foo`, the instance property set to `bar` and the title set to `baz`.

However, what actually happens is that the created window inherits those properties from the "main" window, completely ignoring the properties passed throught the command line.

I've been testing this behavior via the `xprop` tool.

**Comment by chrisduerr** [comment]
Options for the new window are passed to the end of the command, not the start.

**Comment by atchim** [comment]
So the command line interface as it is seems a bit confusing. Also, would be nice to have those options available for the `create-window` socket message. It would be handy for people which use WM rules, which is my case.
