### ISSUE TITLE
CreateNewWindow command should copy working directory

### ISSUE THREAD

**Issue by chrisduerr** [alacritty/alacritty#5562]
Since the CreateNewWindow command is always associated to one specific Alacritty window, this window's working directory should be copied when spawning new windows.

**Comment by jasonhan-vassar** [comment]
Hi, since this issue has been resolved, how would I use `CreateNewWindow` to create a new window with the same working directory? I built the latest Alacritty version, but only `SpawnNewInstance` copies the working directory for me.
