### ISSUE TITLE
Launching Alacritty after upgrading to macOS Monterey gives a warning

### ISSUE THREAD

**Issue by poetaman** [alacritty/alacritty#5566]
Launching Alacritty after upgrading to macOS gives a warning that reads something like: "This app will need to be updated to work in future..." I guess it is related to OpenGL, though don't know. It happened only once so far, so I couldn't get the screenshot. Perhaps related is this: https://github.com/alacritty/alacritty/issues/183

### System

OS: macOS Monterey 12.0.1 (21A559)
Version: alacritty 0.10.0-dev (1df7dc51)

**Comment by reportaman** [comment]
@chrisduerr I just got a warning that looks exactly like the one I got for Alacritty. It seems like its for Python 2 "sunset":

<img width="259" alt="Screen Shot 2021-11-20 at 8 43 41 PM" src="https://user-images.githubusercontent.com/71736629/142749978-7391ba41-9822-4512-9f2e-5d515450d373.png">

Clicking on the ```Learn More...``` took me directly to this page:
https://www.python.org/doc/sunset-python-2/

**Comment by reportaman** [comment]
UPDATE: Nevermind, this ticket has nothing to do with Alacritty. The warning was caused by zsh setup that would call python2 (for some fancy feature) after launching Alacritty.  https://github.com/wez/wezterm/issues/1331#issuecomment-975610375

**Comment by rsslldnphy** [comment]
>> Does that mean that Alacritty will slowly die for macOS, and we macOS users should move on to other terminal applications?

> Maybe, I'm not entirely familiar with macOS' plans to phase out OpenGL. People could of course always try to contribute a metal renderer, but I doubt that's gonna happen and I'm not particularly interested in wasting my time to write one.

@chrisduerr would you accept a PR to the readme making it clear up front that there are no plans to support future versions of MacOS? I've spent bit of time today reading about Alacritty and preparing to make the switch from iTerm, it looks like a great project. However it would have been helpful to know up front that switching was not a good long term idea. It was only by chance I came across this closed issue to discover this too.

**Comment by chrisduerr** [comment]
No.

**Comment by rsslldnphy** [comment]
Apologies if I've misunderstood. I got the same warning when opening Alacritty for the first time yesterday, indicating that it would stop working in a future update (which is how I came across this issue). Is this incorrect/unexpected? It seems like a cool project and I've heard good things about it, so I'd be keen to switch.

**Comment by chrisduerr** [comment]
At this point the mythical future update that will break all OpenGL applications is just a threat. It might happen at some point but that's likely still far out.

**Comment by rsslldnphy** [comment]
> the applications out there that can be used to run OpenGL on top of Metal

The existence of these apps is also useful and reassuring information that’s new to me, as I know little to nothing about renderers or how terminal emulators work.

Potentially it could be useful to have a note in the installation section of the readme that lets people know to expect this warning and reassure them that there are workarounds when and if it happens? Happy to write it if helpful. Either way makes no odds to me as I now know what I need to know; just trying to save other people a bit of time and you from having to have this conversation again.

**Comment by chrisduerr** [comment]
As of now, it's just a warning. I don't see much reason for action because of that. Especially because the future isn't certain so I do not want to make any guarantees for anything.
