### ISSUE TITLE
Font is bold by default

### ISSUE THREAD

**Issue by cafink** [alacritty/alacritty#5568]
I am using the Courier Prime font.  Alacritty renders it noticeably thicker than other apps.  When Alacritty displays it in bold, it's thicker still, which is correct behavior but it becomes so bold that it is difficult to read.  I've found some similar issues, namely #3257, but that issue was seemingly resolved well over a year ago.

I was using an out-of-date version of Alacritty (0.5.0), but updated to the most recent one (0.9.0) hoping it would fix the issue, but it persists.  I'm using the prebuilt MacOS binaries.

Here's a screenshot of Sublime Text (top) and Alacritty (bottom) rendering the same text in this font at size 18.

![Screen Shot 2021-10-28 at 11 00 09 AM](https://user-images.githubusercontent.com/435744/139293035-cacb7fda-f7e2-47b3-81fc-82b040438e81.png)

**Comment by cafink** [comment]
It seems to happen with all fonts.  Here's Georgia, Sublime Text on top and Alacritty on bottom:

![Screen Shot 2021-10-29 at 3 13 15 PM](https://user-images.githubusercontent.com/435744/139496565-8b986e95-0e30-4ffa-8ef4-17af69f1e7a1.png)

And here's my config file (renamed from .yml to .txt so Github would let me uplaod it):

[alacritty.txt](https://github.com/alacritty/alacritty/files/7444703/alacritty.txt)

**Comment by chrisduerr** [comment]
Can you try to remove the line with `style: Regular`?

Also this certainly isn't a general issue on macOS since fonts work just fine for me, so chances are it's about your specific fonts or system. Also comparing to other applications might not give the most reliable results, especially in small screenshots like that it's difficult to put things into perspective.

**Comment by cafink** [comment]
When I remove that line, nothing changes as far as I can tell.

**Comment by chrisduerr** [comment]
Does toggling `use_thin_strokes` do anything for you? Chances are you might just be comparing thin strokes to no thin strokes rendering?

**Comment by numbcoder** [comment]
Related https://github.com/alacritty/alacritty/issues/4033

**Comment by VKondakoff** [comment]
I see this issue as well. Latest Alacritty release, macOS Monterey. `use_thin_stroke` set to `true`.

<img width="416" alt="Снимок экрана 2021-11-01 в 15 13 54" src="https://user-images.githubusercontent.com/230824/139670055-c29df915-c1fd-44d4-bc00-6d37924e0769.png">

Left: Alacritty, right: iTerm2. The same font.

**Comment by chrisduerr** [comment]
Closing in favor of tracking this in #4033. Chances are this is a thin strokes issue and not actually the bold font being picked rather than the regular one.
