### ISSUE TITLE
CSD titlebar out of window geometry until resized

### ISSUE THREAD

**Issue by ghost** [alacritty/alacritty#5569]
From spawning alacritty up to resizing the window (first configure event with concrete size?), the titlebar (with client-side decorations) is out of the window geometry, as if it were a shadow (and as such is rendered off-screen for a window at position [0,0]). When first resizing the window, the titlebar jumps to where it should be and decreases the height of the window contents.

I have patched kiwmi to log the window geometry (*not* including the compositor’s positioning, so the position is relative to the root surface) and got this:

```
geom 0x0+0+0
-- actually, i logged the geom on every commit so each line would be repeated several times
geom 560x475+0+0
-- here the resize happens, this time i managed to resize it by 0px
geom 560x475+0+-30 -- now the titlebar is positioned correctly
```

another time, with a non-zero resize:

```
geom 0x0+0+0
geom 560x475+0+0
geom 560x476+0+-30
```

### System

OS: Linux (Artix)
Version: alacritty 0.9.0 (fed349aa)
Linux/BSD: Wayland, kiwmi

### Logs

Pls let me know if you need any.

**Comment by chrisduerr** [comment]
This kinda stuff might change in the near future anyway since the Wayland libraries have gotten significant updates. So I'm not entirely sure if it's worth it to spend any time looking into that right now.

**Comment by tiosgz** [comment]
Np. Can i test with alacritty master or should i check again with a later version?

And could you please reopen the issue until it’s confirmed to be fixed? Just for the feeling of it.

**Comment by chrisduerr** [comment]
> Np. Can i test with alacritty master or should i check again with a later version?

It's not on master yet, still waiting for stuff to make its way through the dependencies.

**Comment by tiosgz** [comment]
This issue is still present with alacritty 0.10.0.
