### ISSUE TITLE
Alacritty Multi-Window Doesn't Work

### ISSUE THREAD

**Issue by amarakon** [alacritty/alacritty#5572]
The documentation says that Alacrutty suports running multiple terminal emulators from the same Alacritty instance. It says to use the "alacritty msg create-window" command. I tried that command, but it didn't work:

error: Found argument 'msg' which wasn't expected, or isn't valid in this context

USAGE:
    alacritty [FLAGS] [OPTIONS]

For more information try --help

**Comment by chrisduerr** [comment]
Documentation reflects the lastest master, not the latest release.
