### ISSUE TITLE
Clear the screen without a newline before the top-most line?

### ISSUE THREAD

**Issue by nicksergeant** [alacritty/alacritty#5573]
This is a strange question and I'm not entirely sure if it belongs with Alacritty or Zsh, but I'm wondering if someone in the Alacritty world might be able to at least point me in the right direction.

When I hit `ctrl-l` in Alacritty, the screen clears and the prompt goes to the very top of the window:

![image](https://user-images.githubusercontent.com/27332/139514661-f9e27523-f711-42b4-bbe1-835b6358f8fe.png)

I had assumed that Alacritty was just using `clear` to do this, but when I do `clear` (instead of `ctrl-l`), the screen clears but leaves a single newline before the prompt:

![image](https://user-images.githubusercontent.com/27332/139514678-4abe6a87-81db-4518-a660-b3b98b0c7b07.png)

Does anyone know why `clear` leaves this newline? Is Alacritty doing something else?

**Comment by chrisduerr** [comment]
Does this happen with a prompt that is only a single line high?

Generally `clear` does more stuff that just `ctrl-l`, but Alacritty itself has more complicated logic behind `ctrl-l`. All we do with `clear` is to just nuke everything. So if that one is causing a problem I'd assume that's a shell thing.

**Comment by nicksergeant** [comment]
@chrisduerr 

> Does this happen with a prompt that is only a single line high?

Oooh, good call. So it does _not_ happen if I use a prompt with only a single line. In that case, both `clear` and `ctrl-l` clear the screen and the prompt moves to the very top of the screen.

> Generally clear does more stuff that just ctrl-l, but Alacritty itself has more complicated logic behind ctrl-l. All we do with clear is to just nuke everything. So if that one is causing a problem I'd assume that's a shell thing.

Yeah, I wasn't entirely sure at what point of the stack I should start looking here... Alacritty, zsh, Pure prompt... or somewhere else 🤣.

**Comment by nicksergeant** [comment]
And my guess is I can tweak this via the prompt, because it's being intentionally added here:

https://github.com/sindresorhus/pure/issues/509#issuecomment-571439009

(interesting that Alacritty's `ctrl-l` does still wipe out that preceding newline, though...)

**Comment by nicksergeant** [comment]
Yeah, this is definitely happening in Pure prompt. Someone else noticed similar frustration:

https://github.com/sindresorhus/pure/issues/509#issuecomment-674548358

Going to close this one out, but thanks for responding, @chrisduerr!
