### ISSUE TITLE
Cannot find terminfo entry for 'alacritty'.

### ISSUE THREAD

**Issue by blogdemoi** [alacritty/alacritty#5576]
OS: Linux
Version: alacritty 0.9.0
Linux/BSD: X11

Hello,

When I ssh into my server and try to show a screen session with `$ screen -r` (to show a weechat session running in screen) I have this error:

> screen -r
> Cannot find terminfo entry for 'alacritty'.

What do you suggest?

Thank you.

**Comment by chrisduerr** [comment]
If the terminfo is missing, you need to install it. See the documentation for installing Alacritty.
