### ISSUE TITLE
opacity dosen't work

### ISSUE THREAD

**Issue by aliceinwire** [alacritty/alacritty#5577]
I read almost all previous issue reports about opacity and try to follow most of it without success.

I tested both alacritty 0.9.0 and alacritty HEAD

as composite I'm using picom the only change I made to the configuration is
backend = "glx";
vsync = false;

picom works fine, I can set alacritty terminal transparent with `picom-trans -w "$WINDOWID" 80`

The problem is that transparency doesn't work using alacritty with configuration 
opacity: 0.6 (on alacritty HEAD)
or
backgroud_opacity: 0.6 (on alacritty 0.9.0)

After updating to alacritty HEAD I just finally found an error:
[2021-11-01 03:28:32.617323917] [WARN ] [glutin] Glutin could not a find fb config with an alpha mask. Transparency may be broken.

still picom-trans work :/

**Comment by chrisduerr** [comment]
The glutin error sounds like a driver issue. What GPU do you use?

**Comment by aliceinwire** [comment]
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 620 (rev 02)

**Comment by chrisduerr** [comment]
Have you tried with an empty picom config?

**Comment by aliceinwire** [comment]
It worked with alacritty HEAD without picom config. Thanks

**Comment by krozmok** [comment]
The Opacity must be declared inside window attribute.
```yaml
window:
 opacity: 0.8
```

**Comment by Dhamma-valence** [comment]
I was having the exact same issue and this @krozmok fixed it!

**Comment by aliceinwire** [comment]
In my case is still a problem with alacritty 0.9.0 but works with alacritty HEAD
@krozmok the configuration is different from each version, as HEAD changed the configuration layout from 0.9.0.
