### ISSUE TITLE
When using Apple TV to AirPlay, Alacritty is invisible upon start

### ISSUE THREAD

**Issue by bigH** [alacritty/alacritty#5579]
When starting a new Alacritty session, if the new window opens on the "AirPlay" display, the macOS chrome is the only thing visible. The body of the window (which would contain terminal output) is not visible.

Moving the window back into the normal display doesn't fix the issue. I have to turn off "AirPlay" in order to open an Alacritty window, then re-start my "AirPlay" session.

### System

OS: macOS
Version: alacritty 0.9.0 (fed349a)

### Logs

N/A

**Comment by chrisduerr** [comment]
Not a setup I'm interested in supporting. Likely just another case of macOS struggling with OpenGL.
