### ISSUE TITLE
Configurable clickable URIs

### ISSUE THREAD

**Issue by dbogdanov** [alacritty/alacritty#5583]
As I understand, currently only web URLs are supported.

I am looking for being able to click on some x-callback-urls (`myapp://...`) to open them in an external app. In general it would be useful to have a configurable list of clickable URIs. Is that possible?

**Comment by chrisduerr** [comment]
Your understanding is incorrect. See configuration.

**Comment by dbogdanov** [comment]
Thank you for pointing this out, I somehow missed it as my configuration file became outdated and did not have this functionality yet.
