### ISSUE TITLE
Alacritty Release Version 0.9.0 is intel only (MAC)

### ISSUE THREAD

**Issue by HappyTobi** [alacritty/alacritty#5584]
Hi all,

think the latest release on GH was not published via the GH action because the Mac Version was x86 only, but the GH release pipeline creates a "universal" build for macOS. (all scripts work fine)

Can you please update the release dmg for mac or rerun the pipeline to fix that issue.

All Mac Users that install `alacritty` via brew now gets the x86 version. 

### System
OS: macOS
Version: `0.9.0`

Regards
Tobi

**Comment by chrisduerr** [comment]
> Can you please update the release dmg for mac or rerun the pipeline to fix that issue.

No. The official ARM builds will only be supported with the next release.

**Comment by HappyTobi** [comment]
Ok thx than I will close the issue I build the latest version local
