### ISSUE TITLE
Strange gap of alacritty visible when using vim/neovim

### ISSUE THREAD

**Issue by RakshaCode** [alacritty/alacritty#5590]
There is a weird spacing on the right and bottom part of the terminal when using vim/neovim. It is more visible when you use high contrasts and opposite themes.

### System

OS: Ubuntu 21.10 (impish)
Version: `alacritty --version` 0.8.0 (a1b13e6)
Linux: Wayland and Gnome 40.5

#### Config

The three programs (vim, alacritty and neovim) doesn't have configuration files, I have just install theme. In the image I am using neovim and I ran the command:
`:colorscheme shine`
![issue](https://user-images.githubusercontent.com/71290241/140237245-2c09432f-e403-4227-affc-14ade3fc404e.png)

This issue appeared also in termite (in case it is helpful): [https://github.com/thestinger/termite/issues/583](https://github.com/thestinger/termite/issues/583)

**Comment by chrisduerr** [comment]
It's likely because you set a different background color in vim, but your terminal's cell size doesn't match the screen size perfectly. So around each cell, colored differently than your default background, you can see the original background color.
