### ISSUE TITLE
alacritty terminal issues on Mac

### ISSUE THREAD

**Issue by muziejus** [alacritty/alacritty#5592]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: MacOS 11.6
Version: alacritty 0.9.0 (fed349a)

I disabled setting `$TERM` in my .zshenv

but if I change the `env.TERM` to "alacritty": 

<img width="325" alt="Screen Shot 2021-11-04 at 5 35 13 PM" src="https://user-images.githubusercontent.com/827683/140423434-56d08d2e-ca1f-4610-a1bb-ea9d00bb4bd6.png">

Goofy things happen. Backspace doesn't work, characters show up all over the place, and tab completion doesn't work.

If I comment those lines out, the terminal auto-sets to `xterm-256color` and "everything" works "correctly," except the colors are a little off (I'm trying to get truecolor to work).

What's maybe the problem is that I *do* have an alacritty terminal defined:

```
> infocmp alacritty
#	Reconstructed via infocmp from file: /Users/.../opt/anaconda3/share/terminfo/61/alacritty
alacritty|alacritty terminal emulator,
```

so if I do something like:

```
> infocmp alacritty > alacritty.terminfo
> sudo tic -xe alacritty,alacritty-direct alacritty.terminfo
```

it seems to work. However, the terminfo does not show up in `/usr/share/terminfo/61` (where all the a* terminals seem to be), and the terminal continues to behave poorly.

Using `tic` with `extras/alacritty.info` gives no errors, but nothing appears even in `~/.terminfo/61`, though I've already created that folder.

This is all without tmux.

**Comment by muziejus** [comment]
What seems to have worked at least regarding typing is copying the binary from `/Users/.../opt/anaconda3/share/terminfo/61/alacritty` to `~/.terminfo/61/alacritty`. But it still doesn't seem to be showing quite the right colors:

<img width="340" alt="Screen Shot 2021-11-04 at 6 13 52 PM" src="https://user-images.githubusercontent.com/827683/140427788-c2963966-9d7d-40af-8627-230bffc8fc37.png">

that's a window with neovim (on top) and the shell (on bottom)

<img width="1179" alt="Screen Shot 2021-11-04 at 6 15 35 PM" src="https://user-images.githubusercontent.com/827683/140427958-16176695-6b2b-479c-af68-95e9bdd9917f.png">

Here you can see the color set to be the background color on an html color picker w/ the actual result in alacritty.

**Comment by chrisduerr** [comment]
Issues that occur depending on `TERM` are due to buggy applications, not issues with Alacritty.
