### ISSUE TITLE
Colors too dark/saturated on Mac in shell

### ISSUE THREAD

**Issue by muziejus** [alacritty/alacritty#5593]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: MacOS 11.6
Version: alacritty 0.9.0 (fed349a)

In my previous issue (#5592), I thought the color issue I was seeing was a result of the `$TERM` setting. However, it remains the case that I am seeing the wrong colors in the shell on alacritty.

I am trying to use the Nord theme. Its basic background color is `#2e3440`.

<img width="1753" alt="Screen Shot 2021-11-04 at 10 38 28 PM" src="https://user-images.githubusercontent.com/827683/140449964-c434533e-138b-45ec-a539-e09225c3d0d3.png">

In this screenshot, it's clear that `#2e3440` is the background color in Terminal.app and iTerm2—and it's even the color used when I'm using neovim in Alacritty. But with the regular shell, the color is much darker. However, in the configuration, `colors.primary.background` is precisely set to `#2e3440` (as seen in the neovim screenshot).

I've looked for "true color" settings and haven't found anything. And, as the screenshot also shows, Alacrity shows true color bands. And yet, the colors are wrong.

The shell is zsh in each application, using the same configuration.

Thanks.

**Comment by chrisduerr** [comment]
Can you share your alacritty config?

**Comment by muziejus** [comment]
Thanks for asking. In trying to remove the comments, I noticed that I had misformatted the yaml. `colors:` was indented too much. 

I suppose my mistake was that the defaults are somewhat similar to Nord.
