### ISSUE TITLE
Alacritty window crashes when window reaches a certain size

### ISSUE THREAD

**Issue by imjonathanking** [alacritty/alacritty#5600]
I am having an issue where my Alacritty terminal will crash when the window reaches a maximum size. I built from source using the installation guide in the project's README.  All of my packages are up to date, and I have rebooted my system multiple times.

My monitor resolution is 3840x2160, and I have 200% scaling, and I have attempted to launch Alacritty without scaling, but the issue persists.

### System

OS: Ubuntu 20.04.3 LTS
Version: alacritty 0.10.0-dev (b885ec9c)
Linux/BSD: Default

### Logs
There are no logs, as the application closes once the window reaches a certain size.

I have attached a video demonstrating the issue:
[video of application sizing issue](https://youtu.be/0u0FAXA9O7c)

**Comment by chrisduerr** [comment]
That's on X11, right? Sounds a lot like https://github.com/alacritty/alacritty/issues/3500.

**Comment by imjonathanking** [comment]
@chrisduerr correct, the issue resolved when I updated my graphics drivers.

**Comment by imjonathanking** [comment]
@chrisduerr correct, the issue went away when I updated my graphics drivers
