### ISSUE TITLE
Inconsistent startup delay after recent full system upgrade

### ISSUE THREAD

**Issue by adroslice** [alacritty/alacritty#5601]
This occurs when starting via a sway keybind, via command from another instance or when using a keybind I've set to open another window from an existing terminal. The delay tends to be around 3 seconds and always occurs after the `Estimated cell size` debug output. There appear to be no errors or warnings.
The full system upgrade was the first in a little while, downgrading to an older version did not fix the issue, so it may be a dependency problem?
Please point me in the right direction if this is an issue not with alacritty, but something else.

### System

OS: Linux (Arch)
Version: alacritty 0.9.0 (fed349aa)
Linux/BSD: Wayland, Sway

### Logs

Crashes: n/A
Font/Terminal size: See log

Log for one such delayed startup (`alacritty -vvv > alacritty.log`):
[alacritty.log](https://github.com/alacritty/alacritty/files/7511674/alacritty.log)

**Comment by adroslice** [comment]
Hardware: The system in question is a ThinkPad T590.
Here's all the packages that were changed with that particular system upgrade.
[package-changes.txt](https://github.com/alacritty/alacritty/files/7513047/package-changes.txt)

**Comment by chrisduerr** [comment]
That's a big update, certainly not making things easier. I'd probably try downgrading xorg-xserver but unless you have specific input on what broke Alacritty I don't think there's any reason to suggest it's a breakage in Alacritty.

**Comment by adroslice** [comment]
Highly doubt that'd be it, since I'm running wayland, but thanks for trying to hlep regardless.
