### ISSUE TITLE
macos - inconsistent colors when open Alacritty in different ways

### ISSUE THREAD

**Issue by zhengpd** [alacritty/alacritty#5602]
I set `normal - blue` color to `#005faf` in `~/.alacritty.yml`.

When I run `alacritty` cli to open Alacritty from Terminal, the `ls` dirs blue is `#005faf` (via color picker).

When I run `open -a Alacritty` and then `ls`, the dirs blue is `#0061B5` (via color picker).

Just want to know if anyone has any idea of what's causing this. 

### System

- OS: macOS Monterey
- Version: `alacritty 0.9.0 (fed349a)`
- Shell: Terminal with `zsh 5.8 (arm-apple-darwin20.2.0)`, env `TERM=xterm-256color`

**Comment by chrisduerr** [comment]
Colors can be changed in your shellrc. There's a lot of ways you can screw over your own system, the one most likely to know what you changed is yourself.
