### ISSUE TITLE
Request: menubar and context menu

### ISSUE THREAD

**Issue by Tcll** [alacritty/alacritty#5604]
### System

OS: (Void) Linux
Version: 0.6.0
Linux/BSD: X11, xfwm4

I'd like to request a few needed features that would make it possible to switch from gnome-terminal, being the menubar and R-click context menu as shown here:
![clipboard](https://user-images.githubusercontent.com/773959/141383594-3f79c4f5-a5ce-4dae-af43-909a123c1b86.png)

NOTE: the trick for a context menu is to create a child window ;)
for clarification, to maintain customizability, the context menu should be provided as a bindable action

also, I don't expect the context menu to be based on Gtk for styling
you can draw a GL quad and apply a custom texture specified in the yml all you want, or just use `glColor4f()` for basic styling
(I'm not sure how it works internally, but you get the idea, as long as it's configurable, including the menubar)

hope this helps make alacritty more usable to make linux popular :D

**Comment by chrisduerr** [comment]
Alacritty has absolutely no goal in being as mouse-focused as gnome-terminal. Context menus don't exist and **never** will.

**Comment by Tcll** [comment]
that's a shame, this could've been a good terminal...
guess I'll build my own emulator then, OpenGL isn't that difficult
just didn't wanna bother with another project

... at least I tried /shrug
too bad you don't want linux to be usable.

**Comment by Tcll** [comment]
just figured I'd post back as to what I'm doing exactly as a result to my previous post:
![](https://ipfs.io/ipfs/QmRoTgpdtx7KYisHKQ2UcNoNK2NdtL7MpFTjK2LbLxqSxk)
context menus are stupid easy to do, and here I'm not even using bloated xcb to do them like you guys use

it's a shame Alacritty won't implement such simplistic functionality and make Linux actually usable for people who want to get away from unstable bloat like GTK

Alacritty could've been cool
but you guys have a fetish for a keyboard-only niche and don't care about the other 90% of the Linux user-base :smh:

mouse support isn't hard
stop hurting Linux for your fetish.

**Comment by JhonnyRice** [comment]
@Tcll  Yeah flexin on Void Linux 🤘

**Comment by Tcll** [comment]
@JhonnyRice sorry to burst your bubble
but I'm on Artix OpenRC now after getting fed up with Void's issues

oh and I still can't use Alacritty
imagine using xcb and ncurses
but not taking advantage of the mouse support provided

it's not like it's difficult to code
nor is it an obnoxious request to make
it's just sad the devs don't want to do their job for us users

but I already have a replacement terminal that beats Alacritty at being usable
so I'll leave my footprint in Alacritty's grave
good riddance to stuck-up selfish keyboard fetishists who aren't willing to improve their software for the betterment of Linux as a whole.

**Comment by kchibisov** [comment]
I'm not sure about what mouse issues are talking about? About a popup to press paste that has nothing to do with ncurses, then yes, I don't think adding a popup to just paste and literally nothing more worth it, it provides no functionality given that you can't use terminal with just mouse.

Regardless ncurses, you're likely talking about mouse mode, so you can click with mouse in those applications. Such mode is supported for a very long time inside alacritty (I use it for example to resize vim's windows and select/paste in it).

Besides that I'm not sure what exactly what you want here, since the only thing alacritty is missing wrt mouse support, I think a popup menu, which provides no real value.

**Comment by Tcll** [comment]
hi @kchibisov and thank you for not just telling me to F off while ignoring my feedback like the previous person who addressed me.

the request is for allowing someone to specify bind-able actions in a config file for mapping mouse buttons to events
("mouse_0" (left click), "mouse_1" (right click), "mouse_2" (middle click), ...)

such actions could be used to create a popup window allowing you to click on the desired actions (such as Copy/Paste) as specified in the config

both xcb and ncurses support these events
alacritty just needs to provide them for mapping via config specs to event functions like creating a new borderless menu-type window
which is very easy to do since xcb provides easy ability to manage as such.

**Comment by kchibisov** [comment]
Could you link to a reference page mentioning those? I'm not quite sure what you're talking about and how ncurses relates to that. I'm not asking for xcb reference, but rather for ncurses one related to popups, etc.

In general pop up windows are not supported by the windowing library we're using. However popup like window could be implemented without any actual popup (given that we must support 4 windowing systems). On the other hand you can copy and paste using mouse without any actual bindings(middle mouse + just select to copy, and we have `save_to_clipboard`, which syncs both clipboards together). Can go further and even bind mouse buttons to whatever actions you want or external commands.

I just feel like all of that menu to select just copy or paste is redundant given that you can do all of that with **mouse** without any menu already.

**Comment by Tcll** [comment]
> Could you link to a reference page mentioning those?

it's in the dependencies for Alacritty
both xcb and ncurses are required to run it

> In general pop up windows are not supported by the windowing library we're using.

XCB creates windows, "popup" is just an attribute that describes the type of window being created
I'm not sure how XCB does it specifically (I don't use it, I manage X11 directly)
but X11 (the named pipe at `/tmp/.X11-unix/X0`) does it, and XCB is just bloat around X11
so it should be capable
unless XCB is just as dysfunctional as GLFW:
![](https://jump.matthewevan.xyz/i2p/pxbcwxbhxj2wusliwhrb6ym4vcwpihztuf2tfjejrcdzqrmnjuoa.b32/_/c0ed49f2054dd460407ad72f031f789793e0efc443d76f6ff698c75d94e6cc54)

but anyways, I should be able to specify those attributes in the config on the mouse-button action to define the newly created window as a modal popup

I'll be the one defining the actual menu items as specified in the config
(you already have ncurses, so the menu window would just be a borderless Alacritty window with specified attributes styled however intended)

the goal is to leave it up to the user to customize things how they prefer :)
(the user can add the menu items they want and revert back to the actions provided by Alacritty)
though if we can avoid going overboard (eg: rofi) while providing everything needed, that would be preferred :+1:

**Comment by JhonnyRice** [comment]
@Tcll Alacritty works flawlessly on my Void machine

**Comment by mishurov** [comment]
@chrisduerr 

> Context menus don't exist and never will.

Ok. In bin it goes then.

**Comment by nixpulvis** [comment]
I'm not sure if this changes anything, but the advice from winit seems to be to use a crate like https://docs.rs/muda/latest/muda for this. We could consider adding a gtk3 feature for linux to optionally include this as well, but on macOS and Windows it shouldn't require any other external dependencies.

**Comment by chrisduerr** [comment]
> We could consider adding a gtk3 feature for linux to optionally include this as well

That's not on the table.

**Comment by nixpulvis** [comment]
I'd be curious if adding menu items for macOS would solve issues like #4230.
