### ISSUE TITLE
Request: easily obtainable linux binary

### ISSUE THREAD

**Issue by Tcll** [alacritty/alacritty#5605]
### System

OS: (Void) Linux
Version: 0.6.0
Linux/BSD: X11, xfwm4

from your releases page here:
https://github.com/alacritty/alacritty/releases/tag/v0.9.0
you can easily download:
- [Alacritty-v0.9.0-portable.exe](https://github.com/alacritty/alacritty/releases/download/v0.9.0/Alacritty-v0.9.0-portable.exe)
- [Alacritty-v0.9.0.dmg](https://github.com/alacritty/alacritty/releases/download/v0.9.0/Alacritty-v0.9.0.dmg)

but what's missing is a download for one of the following: (all of these are the same)
- Alacritty-v0.9.0-portable.elf
- Alacritty-v0.9.0-portable.elf.tar.gz
- Alacritty-v0.9.0-portable.appimage

let's work together as developers and make Linux usable again for users. :)
I'm currently stuck on 0.6.0 which I copied from another Linux installation. ;)

**Comment by chrisduerr** [comment]
> let's work together as developers and make Linux usable again for users. :)

Linux is the most usable of the bunch. Making it trivial for every distro to offer compiled binaries to their users by packaging software. That's exactly how it's supposed to work. **Not** by having developers distribute their software manually like on macOS/Windows.

**Comment by Tcll** [comment]
it's not very usable if I have to become an alacritty dev just to use your program...
guess you don't really want users using it then /shrug

ah well, I can build my own
just didn't want to trouble myself

at least I tried /shrug
too bad you don't want linux to be usable.

**Comment by fyhertz** [comment]
Hello there, thank you for this amazing terminal emulator !

Could we re-open this issue? Would it be complicated to distribute portable linux builds (for x86 and ARM) in Github releases? It would let non rust devs try it more easily :)

Incidentally, at my company we maintain a Debian repository (https://github.com/upciti/wakemeops) that automatically packages portable linux apps and hose builds would let us add alacritty in no time!

**Comment by chrisduerr** [comment]
> Would it be complicated to distribute portable linux builds (for x86 and ARM) in Github releases? 

Yes.
