### ISSUE TITLE
44wrsn2ew5s5asadrygcqsftr4twgeftvdfRTei.WxMnxckkl¬¬¬¬¬¬¬¬mnjhbgly-fwdesxghnbg

### ISSUE THREAD

**Issue by vkolgi** [alacritty/alacritty#5610]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux/BSD/macOS/Windows
Version: `alacritty --version` output
Linux/BSD: X11/Wayland, DE or Compositor and WM

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by chrisduerr** [comment]
I completely agree.

**Comment by vkolgi** [comment]
@chrisduerr I am extremely sorry. This is my kid's work. Also it's embarrassing to say the least. Closing the issue.
