### ISSUE TITLE
Can't unbind `Ctrl-D` due to identical behavior of `ReceiveChar` and `None`

### ISSUE THREAD

**Issue by dmyTRUEk** [alacritty/alacritty#5611]
### System
OS: Linux
Version: `alacritty 0.9.0 (fed349aa)`
Linux/BSD: Wayland, Sway WM

I don't want Alacritty to close on `Ctrl+D`, so i added this to config:
```
key_bindings:
  - { key: D, mods: Control, action: ReceiveChar }
```
but Alacritty still closes when I press `Ctrl+D`.

This solution is bad for me
```
key_bindings:
  - { key: D, mods: Control, action: None }
```
because i use `Ctrl+D` in NeoVim for scroll by half page down.

As I can see from [search](https://github.com/alacritty/alacritty/search?q=receivechar) on this github repo, the only place where `ReceiveChar` is used in code is [here](https://github.com/alacritty/alacritty/blob/1df7dc5171abfe1eab3e95be964f61c5876198f1/alacritty/src/input.rs#L324):
```
Action::ReceiveChar | Action::None => (),
```
so that is why they have identical behavior.

But as I can see [here](https://github.com/alacritty/alacritty/blob/b0da035e9ecabfa13438386a6ce87072b7cc3c98/alacritty.yml#L733-L736) they must have different behavior (as I understood text):
- `None` must do absolutely nothing, even eat the input.
- `ReceiveChar` must only unbind the binding, but don't eat the input (pass it further, for example in neovim)

Do `None` and `ReceiveChar` should have different behavior?
And how can I unbind `Ctrl-D` only for Alacritty, but not for NeoVim?

**Comment by chrisduerr** [comment]
You either send Ctrl+D or you don't. It's not a binding to close Alacritty, it's a binding to shut down your shell.
