### ISSUE TITLE
macbook pro notch obscures terminal in simple fullscreen mode

### ISSUE THREAD

**Issue by dannydulai** [alacritty/alacritty#5612]
I'm running alacritty 0.10.0-dev (e648aae0) on the latest macbook pro with the notch, and when entering simple fullscreen mode, the notch obscures the top of the terminal. The simple fullscreen mode is awesome, and it'd be awesome to avoid this "notch" issue.

Is there an option or some way to put some padding at the top? or even show the macos menu bar?

**Comment by chrisduerr** [comment]
There might be some way to resolve this without code changes, but I'm not an active macOS user.

As far as Alacritty is concerned I really don't care about implementing workarounds for Apple's poor hardware design.

**Comment by dannydulai** [comment]
Does that mean you will reject pull requests or just that you personally are not going to do anything to fix it? The Closing of this thread implies that you will not accept this type of change.

I didn't mean to put in a "bug fix" ticket to the core Alacritty team here. Apologies if that is what I have done. I am asking for any known workarounds and noting an issue that may not be apparent to those who know how to fix this easily because the hardware is recent.

It's also worth mentioning that while you may disagree with the notch, AppKit has had support for "safeAreaInsets" for a while now where the notch has been available, and it is also [available on MacOS](https://developer.apple.com/documentation/appkit/nsscreen/3882821-safeareainsets). Assuming that an app can safely get the full screen is no longer a safe assumption in 2021.

It's fine if you don't care about MacOS, but you, Joe, and others (including myself) have put a lot of care into Alacritty, including the MacOS support. I'd think we all want Alacritty to work great, including what is most likely to be the future of a huge number of developer-oriented laptops.

I don't mind taking a stab at this if you are willing to accept the change, but a discussion on the right way to tackle the problem would be most appreciated. Long ago, Joe helped me in the same way with a request I gave about cursor colors, which led to me issuing a pull request (that did get merged). The way I would have tackled it before his input was not the way he preferred it, and the discussion helped avoid that work.

**Comment by chrisduerr** [comment]
> The Closing of this thread implies that you will not accept this type of change.

Correct, I will not accept any Pull Requests to Alacritty to work around Apple's poor hardware design.

**Comment by dannydulai** [comment]
Ok, since you are being very opinionated on the poorness of Apple's hardware design, let's flip it.  Will you accept a change that fixes alacritty's poor design that ignores AppKit's intended use of safe area intents?

**Comment by chrisduerr** [comment]
I will not accept any patches directly related to this into Alacritty.

**Comment by dannydulai** [comment]
Ok. I understand.

I've asked the glutin team on what the proper way to handle this is over here

https://github.com/rust-windowing/winit/issues/2066

I've also found what iTerm2 does, and they've just added an exception for notched MacBooks:

https://gitlab.com/gnachman/iterm2/-/commit/f5c5f996b8f6ba318900b275b7048b5a97622444

I'll see what the glutin guys say is the right thing to do. It looks like iTerm2 just does what I asked about above (padding on top, with auto-population of padding field).

**Comment by stherold** [comment]
An alternative would be to just enable the specification of the window padding like below which would be an advantage for all platforms and also other terminlal emulators do so:

```shell
[window]
padding = { top = 10, bottom = 10, leading = 0, trailing = 0 }
```

**Comment by Blackjacx** [comment]
An alternative would be to just enable the specification of the window padding like below which would be an advantage for all platforms and also other terminlal emulators do so:

```shell
[window]
padding = { top = 10, bottom = 10, leading = 0, trailing = 0 }
```

**Comment by nixpulvis** [comment]
I’ll just add, not that I’ve found the time and energy to do it, but there **has** been discussion of supporting this. But it requires winit support for dead regions. It’s been a while since I looked at the issue over there about it. I could dig that up if it’s helpful.

chris is probably right, alacritty itself should need to think about this.

**Comment by dannydulai** [comment]
@nixpulvis, winit support: https://github.com/rust-windowing/winit/pull/3890

**Comment by nixpulvis** [comment]
@chrisduerr would you consider reopening this issue since it seems we should be able to fix this without hacks in Alacritty soon?

**Comment by boeserwolf** [comment]
@chrisduerr I really like Alacritty for its speed and we've used it for a few years now, but unfortunately, because there is no workaround for Mac users, I will have to switch to another terminal emulator (WezTerm) for ~ 140 developers in my company. And we're not happy about it.
