### ISSUE TITLE
How to specify title when creating new window?

### ISSUE THREAD

**Issue by netjune** [alacritty/alacritty#5614]
I open several terminals for ssh use everyday. And I use hammerspoon on macOS to switch between different windows or apps. It can search windows by title. So I can switch to a window with one key binding.

I want to create several windows in alacritty, each window with different fixed title. What should I do?

**Comment by chrisduerr** [comment]
See pretty much any documentation of Alacritty.

**Comment by netjune** [comment]
It seems that their is no document for this. I cant find it in this repo. Can you give me the url?

**Comment by netjune** [comment]
`dynamic_title` should be disabled, because I dont want any command to change the title after the new window is created. So I have to set the title when creating the new window.

**Comment by adonespitogo** [comment]
@netjune did you find the documentation for this?

**Comment by kchibisov** [comment]
```
~ → alacritty --help
A fast, cross-platform, OpenGL terminal emulator

Usage: alacritty [OPTIONS] [COMMAND]

Commands:
  msg      Send a message to the Alacritty socket
  migrate  Migrate the configuration file
  help     Print this message or the help of the given subcommand(s)

Options:
      --print-events
          Print all events to stdout
      --ref-test
          Generates ref test
      --embed <EMBED>
          X11 window ID to embed Alacritty within (decimal or hexadecimal with "0x" prefix)
      --config-file <CONFIG_FILE>
          Specify alternative configuration file [default: $XDG_CONFIG_HOME/alacritty/alacritty.toml]
      --socket <SOCKET>
          Path for IPC socket creation
  -q...
          Reduces the level of verbosity (the min level is -qq)
  -v...
          Increases the level of verbosity (the max level is -vvv)
  -o, --option <OPTION>...
          Override configuration file options [example: cursor.style=Beam]
      --working-directory <WORKING_DIRECTORY>
          Start the shell in the specified working directory
      --hold
          Remain open after child process exit
  -e, --command <COMMAND>...
          Command and args to execute (must be last argument)
  -T, --title <TITLE>
          Defines the window title [default: Alacritty]
      --class <general> | <general>,<instance>
          Defines window class/app_id on X11/Wayland [default: Alacritty]
  -h, --help
          Print help
  -V, --version
          Print version
```

See `-T`.

**Comment by adonespitogo** [comment]
I figured it out after some googling and finding no references to commandline options. —help is the way

**Comment by kchibisov** [comment]
I mean, it's a common sense that tools have `--help` argument to show what they do. This information is also duplicated in `man alacritty`.

**Comment by adonespitogo** [comment]
In this modern day and age, I always expect popular projects to have web documentation of some sort and be able to land to a solution for simple tasks in one google search. I know about —help being available in most commandline utilities, but usually that will be my last resort. 

For anyone looking for an answer to this, the commandline option is `—title`
