### ISSUE TITLE
My `Ctrl-,` and `Ctrl-.` were eaten

### ISSUE THREAD

**Issue by geometryolife** [alacritty/alacritty#5620]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: `Arch`
Version: `alacritty 0.9.0 (fed349aa)`

I want it to get the effect of `Ctrl-,` when I type `Ctrl-,`, not output `,`.
Similarly, I want it to get the effect of `Ctrl-.` when I type `Ctrl-.`, not output `.`.

Can you tell me where I can modify it?

**Comment by chrisduerr** [comment]
What exactly do you mean by "effect of `Ctrl-,`"?

**Comment by geometryolife** [comment]
> What exactly do you mean by "effect of `Ctrl-,`"?

On the command line, using `C-,` in Emacs does not capture the effect of `C-,`, but rather `,`.
Using `C-,` in the `X` environment works fine, and Emacs captures the `C-,` effect that the keyboard passes to it.

**Comment by chrisduerr** [comment]
Working as expected.

**Comment by geometryolife** [comment]
> Working as expected.

I tried to compile and run the latest version, but I still couldn't achieve the desired results.
I expect you to do a small test, enter the `alacritty` after entering `Ctrl,`, if it outputs `,`, indicating that it did not meet my expectations.

**Comment by swarnendubiswas** [comment]
@geometryolife Can you try the following binding in `alacritty.yml`?

`{ key: Comma, mods: Control, chars: "\x1b[27;5;44~" } # Ctrl + ,`
