### ISSUE TITLE
unknown terminal type when I try to use 'clear' command

### ISSUE THREAD

**Issue by RockatanskyV8** [alacritty/alacritty#5621]
I don't know why but it doesn't seem to happen with any other command just 'clear'

```
~ >>> clear
'alacritty': unknown terminal type.
```
I searched but I couldn't find anyone on the internet with a similar problem

### System

OS: Manjaro
Version: alacritty 0.9.0 (fed349aa)
Linux/BSD: X11(I think)

**Comment by chrisduerr** [comment]
You need to install the terminfo, see installation instructions.
