### ISSUE TITLE
Crashes inconsistently on Ctrl+D

### ISSUE THREAD

**Issue by pesader** [alacritty/alacritty#5624]
I got used to pressing Ctrl+D to close terminal windows, and I used to do it all the time on Alacritty. I recently updated it from 0.7.0 to 0.9.0, and started to have an issue with that.

Sometimes, when I press Ctrl+D intending to leave the shell and close the terminal, it crashes and never actually closes. The window stays open and frozen, like so:

![image](https://user-images.githubusercontent.com/65264536/142743908-96ce5351-8989-441b-9cb6-a49afe8163bd.png)

### System

OS: Ubuntu 20.04
Version: 0.9.0
Compositor/DE: Wayland/GNOME

### Logs

```log
[2021-11-20 14:52:01.715235381] [ERROR] [alacritty_terminal]
Error reading from PTY in event loop: Input/output error (os error 5)
```

**Comment by chrisduerr** [comment]
Can you reproduce this with the latest master?

**Comment by michael-kirovich** [comment]
Reproduced with the latest master on Ubuntu 20.04.

**Comment by pesader** [comment]
Just built the latest and cannot reproduce the bug! Seems like it's fixed up there :)

```
./alacritty --version
alacritty 0.10.0-dev (c89939b5)
```

**Comment by Munksgaard** [comment]
I've been encountering this bug for a while now too, will try the latest master.
