### ISSUE TITLE
Discord Screen-share Breaks Text Rendering

### ISSUE THREAD

**Issue by Lino5000** [alacritty/alacritty#5625]
Alacritty works fine for me in the vast majority of situations, but when trying to share an Alacritty window in a Discord call, the text rendering seems to completely break.

The only consistent way I've found to fix this is to restart Alacritty, though ending the stream and typing random characters can sometimes fix it (I can't reliably reproduce this, it just happens sometimes). 

This only affects the Alacritty window that I select to share, and seems to be triggered when the Alacritty window first gains focus after the screen share begins. It doesn't happen if I share the entire screen, nor does it affect other Alacritty windows that aren't being shared.

Before sharing screen:
![image](https://user-images.githubusercontent.com/33172520/142756031-8100916e-584c-4ff4-80b5-8856e179defd.png)

During and after sharing screen:
![image](https://user-images.githubusercontent.com/33172520/142756046-bcc8b96e-87b0-491b-b277-d3022eb597a8.png)

This may be a bug in Discord, in which case I'll report it there. I'm reporting it here first because Alacritty is the only program that seems to have this issue, though in my testing it also seems that it only happens with Discord's screen sharing (e.g. it doesn't occur with Zoom).

Also worth noting: the bug still occurs when I remove my `alacritty.yml`, so it is likely not a configuration issue.

### System

OS: Windows
Version: `alacritty 0.9.0`
I tried installing with `cargo install`, the msi installer, and using the portable version, and the issue occurred on all.

I feel like it would be relevant to give some information about my computer's graphics, but I don't know what would be useful or how to get it, so please let me know if there's any other info I can provide.

### Logs

I can't see anything being logged in either of these when the issue occurs, but I've attached them anyway.

Font/Terminal size: `alacritty -vv`
[alacrittyLog.txt](https://github.com/alacritty/alacritty/files/7575996/alacrittyLog.txt)

Keyboard and bindings: `alacritty --print-events`
[alacrittyEvents.txt](https://github.com/alacritty/alacritty/files/7576050/alacrittyEvents.txt)
This does include the mouse click event that brings the window into focus and triggers the issue, but there is nothing else that stands out nearby.

**Comment by chrisduerr** [comment]
Duplicate https://github.com/alacritty/alacritty/issues/4855.
