### ISSUE TITLE
[help] background color setting does not apply

### ISSUE THREAD

**Issue by b0ywearngtyts** [alacritty/alacritty#5628]
Hey!
I'm using alacritty 0.9.0 from Gentoo under BSPWM (no picom/...)

I'm trying to apply the Gruvbox dark hard colorscheme from aarowill/base16-alacritty* but it's not working, as we can see in the screenshot the background color is not correct.
I don't what `alacritty -vv` should output but there is nothing about color configuration.

![2021-11-22-222059_1920x1080_scrot](https://user-images.githubusercontent.com/94209903/142938084-b2474f20-62b4-4fea-ba14-b58e7c0b5c7f.png)

My config file is at the right place (~/.config/alacritty/alacritty.yml), fonts are loaded, cursor settings are working, window padding also...

*Using 0x or # color code change nothing and using the "256" version neither.

**Comment by chrisduerr** [comment]
Your shell config might set the color, I recommend checking without any shell config. The option certainly works as intended.

**Comment by b0ywearngtyts** [comment]
the pb was vim configuration : missing "set termguicolors"
