### ISSUE TITLE
not install 

### ISSUE THREAD

**Issue by estatistics** [alacritty/alacritty#5630]
In ubuntu 21.05

sudo cargo install alacritty --verbos

error[E0658]: or-patterns syntax is experimental
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.10.1/build/parse.rs:68:16
   |
68 |             Ok(XmlEv::Text(e) | XmlEv::CData(e)) => {
   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #54883 <https://github.com/rust-lang/rust/issues/54883> for more information

error[E0658]: or-patterns syntax is experimental
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.10.1/build/parse.rs:79:16
   |
79 |             Ok(XmlEv::Text(e) | XmlEv::CData(e)) => {
   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #54883 <https://github.com/rust-lang/rust/issues/54883> for more information

error[E0658]: or-patterns syntax is experimental
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.10.1/build/parse.rs:121:16
    |
121 |             Ok(XmlEv::Start(e) | XmlEv::Empty(e)) => Ok(Vec::from(e.name())),
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #54883 <https://github.com/rust-lang/rust/issues/54883> for more information

error[E0658]: or-patterns syntax is experimental
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.10.1/build/parse.rs:229:20
    |
229 |                 Ok(XmlEv::Text(_) | XmlEv::CData(_)) => {
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #54883 <https://github.com/rust-lang/rust/issues/54883> for more information

error[E0658]: or-patterns syntax is experimental
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.10.1/build/parse.rs:312:16
    |
312 |             Ok(XmlEv::Start(ref e) | XmlEv::Empty(ref e)) => {
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #54883 <https://github.com/rust-lang/rust/issues/54883> for more information

error[E0658]: or-patterns syntax is experimental
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.10.1/build/parse.rs:383:20
    |
383 |                 Ok(XmlEv::Empty(ref e) | XmlEv::Start(ref e)) => match e.name() {
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #54883 <https://github.com/rust-lang/rust/issues/54883> for more information

error: aborting due to 6 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `xcb`

Caused by:
  process didn't exit successfully: `rustc --crate-name build_script_main /root/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.10.1/build/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debug-assertions=off --cfg 'feature="render"' --cfg 'feature="shape"' --cfg 'feature="thread"' --cfg 'feature="xfixes"' -C metadata=3adf6d7a0a1487ba -C extra-filename=-3adf6d7a0a1487ba --out-dir /tmp/cargo-install0s40aF/release/build/xcb-3adf6d7a0a1487ba -L dependency=/tmp/cargo-install0s40aF/release/deps --extern libc=/tmp/cargo-install0s40aF/release/deps/liblibc-b5302d881f3eb0bb.rlib --extern quick_xml=/tmp/cargo-install0s40aF/release/deps/libquick_xml-41a01377272abda4.rlib --cap-lints allow` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `alacritty v0.9.0`, intermediate artifacts can be found at `/tmp/cargo-install0s40aF`

Caused by:
  build failed

**Comment by chrisduerr** [comment]
See install instructions.
