### ISSUE TITLE
Desktop entry doesn't show up

### ISSUE THREAD

**Issue by JuanM04** [alacritty/alacritty#5631]
### The Problem

I followed the Installation Guide a time ago including the Desktop Entry section, and it worked perfectly. A few days ago I updated all my packages (I'm using Fedora 35) and the Alacritty entry disappeared. The file itself is still there but it doesn't show up in the applications menu. I tried multiple things like creating an entry from the ground up, changing the Icon for a PNG instead of a SVG. After some testing, I fount out if I created a Desktop Entry with `Exec=alacritty` it won't appear in the applications menu.

Have anyone experienced this? Have you found an fix?

### System

OS: Fedora 35
Version: 0.9.0
Linux/BSD: X11/Wayland (GNOME 41.1)

### Disclaimer

I know maybe this isn't the place where I should be asking this, but I couldn't find anything similar elsewhere and _only_ happens with Alacritty.

**Comment by chrisduerr** [comment]
This seems like a Fedora/Gnome specific issue. I don't use Fedora, Gnome, or desktop entries for that matter. If you need support with your specific desktop environment, I recommend asking in a location dedicated to that. Following Alacritty's instructions *should* work for most compliant DEs I think.

**Comment by JuanM04** [comment]
For anyone that has this issue, you can fix it by changing `TryExec`, `Exec` (both inside `Desktop Entry` and `Desktop Action New`) to `/home/USER/.cargo/bin/alacritty`

**Comment by pashtet04** [comment]
I've got the same issue. And I am still able to launch Alacritty using bash. But it doesn't show up in Gnome applications menu.

```
[Desktop Entry]
Type=Application
TryExec=alacritty
Exec=alacritty
Icon=Alacritty
Terminal=false
Categories=System;TerminalEmulator;

Name=Alacritty
GenericName=Terminal
Comment=A fast, cross-platform, OpenGL terminal emulator
StartupWMClass=Alacritty
Actions=New;

X-Desktop-File-Install-Version=0.26

[Desktop Action New]
Name=New Terminal
Exec=alacritty
```

```
whereis alacritty
alacritty: /usr/bin/alacritty /usr/share/man/man1/alacritty.1.gz
```

**Comment by kchibisov** [comment]
Have you tried following the `INSTALL.md` instructions?

**Comment by pashtet04** [comment]
Did you mean https://github.com/alacritty/alacritty/blob/master/INSTALL.md#desktop-entry ?

I've installed Alacritty using pacman.
`alacritty` is in $PATH
desktop svg icon is present on filesystem `/usr/share/pixmaps/Alacritty.svg`
I've tried to replace and update desktop file but no luck -- `/usr/share/applications/Alacritty.desktop`

**Comment by kchibisov** [comment]
The `pacman` should install everything correctly, no need to do anything extra. Anyway, that's not alacritty issue if GNOME doesn't understand something. The desktop entry is written according to the spec.

**Comment by pashtet04** [comment]
I've found the issue
I can't understand when and why it happened, but I has _Alacritty.desktop_ file in `~/.local/share/applications` and it had wrong permissions `644`. I did change it to `755` and application began to show up in the Overview section.
