### ISSUE TITLE
macOS M1 - Full disk access keeps reverting when accessing restricted directories

### ISSUE THREAD

**Issue by lucasteligioridis** [alacritty/alacritty#5632]
I'm actually not too sure if this is an `alacritty` issue or something with Mac, but everytime I enable `alacritty` with full disk access and try access some "restricted" folders, the setting immediately reverts. Have tried searching online and can't seem to come up with anything concrete, hopefully someone might know what's going on here.

The same goes for when I add full disk access and try accessing `~/Documents` it requests access, although I have the full disk access enabled at the time.

I've had this working previously on my old MacBook Pro (Intel), so assume there might be something related to the `universal` binary (which I've built from source on latest master) or perhaps a bug within Apple on these new machines.

*Some examples I described above:*

## Full disk permissions reverting

1. Accessing a restricted directory:

<img width="584" alt="Screen Shot 2021-11-24 at 11 41 48 am" src="https://user-images.githubusercontent.com/20388321/143150655-a8ceb42e-0fda-46c3-b271-09d30d56a39f.png">

2. Enabling full disk access and re-opening:

<img width="676" alt="Screen Shot 2021-11-24 at 11 42 54 am" src="https://user-images.githubusercontent.com/20388321/143150765-b6adea91-121e-4a4b-acb5-273ef27f735a.png">

3. Accessing the same directory in step one getting the same permission denied error but then looking back on the Security settings in MacOS, the checkbox has been reverted:

<img width="679" alt="Screen Shot 2021-11-24 at 11 43 57 am" src="https://user-images.githubusercontent.com/20388321/143150920-fe848050-0403-435e-be61-2236652c2e82.png">

## Prompt for access with full disk permissions enabled

1. Full disk permissions on Alacritty have been enabled:
<img width="676" alt="Screen Shot 2021-11-24 at 11 42 54 am" src="https://user-images.githubusercontent.com/20388321/143150765-b6adea91-121e-4a4b-acb5-273ef27f735a.png">

2. Try and access `~/Documents` and still prompted with "allowing" access. Unexpected behavior since "full disk permissions" should be enabled:

<img width="392" alt="Screen Shot 2021-11-24 at 11 48 18 am" src="https://user-images.githubusercontent.com/20388321/143151375-4483c8be-cbfb-40bc-9c2d-578674019ba9.png">

Tested this same procedure with the `Terminal.app` that comes default with MacOS and the access works as this is the expected behavior. This leads me to believe something perhaps related to non-apple software or the application is not fully recognized in the Security settings somehow.

### System

OS: macOS 12.0.1 - MacBook Pro M1 Max
Version: alacritty 0.10.0-dev (8681f710)

**Comment by lucasteligioridis** [comment]
Erm, for reference, I just deleted the `Alacritty.app` from `/Applications` in finder,  then I re-installed it via `brew` and then ran this on my locally built universal binary:

```
cp -r target/release/osx/Alacritty.app /Applications/
```

Then everything is working as expected now with permissions, really strange.

Apologies as this might not have anything to do with alacritty and maybe something I did when I first installed it.

**Comment by lucasteligioridis** [comment]
To add more information I built the binary following these instructions:
https://github.com/alacritty/alacritty/pull/4727#issuecomment-937892278

And also noticed that there is now a closed issue over here:  https://github.com/alacritty/alacritty/pull/4727#issuecomment-937892278

The comment in the above issue stipulating the `make app` target is not correct:
https://github.com/alacritty/alacritty/issues/5546#issuecomment-945076728

That make target will build an `x86` binary, which is not what we want to achieve here as opposed to the universal binary. Ultimately feels like this issue I'm facing is a duplicate of the closed issue I linked above, feel free to open that one again, leave that with you.

Ultimately, if I start with a clean install following the universal binary build from source instructions, it eventually starts giving those permission errors.

**Comment by wwwdata** [comment]
I also had this issue. The post install Terminfo configuration step helped for me: https://github.com/alacritty/alacritty/blob/master/INSTALL.md#post-build

**Comment by wwwdata** [comment]
Damn it.. yesterday it worked.. sorry, now it also doesn't work for me anymore and requests access every time I access files for example in my `Documents` folder...

**Comment by chrisduerr** [comment]
> Then everything is working as expected now with permissions, really strange.

Which means it's not an Alacritty issue.

**Comment by lucasteligioridis** [comment]
@chrisduerr not sure why you closed this. There is an issue present between the arm and 86 binaries right? Or have I missed something completely, one has the issue where the other doesn't?

**Comment by chrisduerr** [comment]
> There is an issue present between the arm and 86 binaries right?

Which issue would that be?

**Comment by sharpner** [comment]
I have the same behaviour building alacritty from source with the latest master (8681f71084894db6d1e258be17db1f80bb669314)

Running `make app` will create a version that only asks for permission once, and then just works, like I would expect
Running `make app-universal` creates an application that asks for permission everytime I do something within e.g. Documents folder.

**Comment by lucasteligioridis** [comment]
> > There is an issue present between the arm and 86 binaries right?
> 
> Which issue would that be?

The fact that the `x86_64` binary is able to persist the settings of the file/folder permissions within the MacOS security settings and the `universal` binary cannot.

Many people seem to be reporting the same issue.

> Then everything is working as expected now with permissions, really strange.

When I tried this above, after more testing the thing that actually "worked" here was me using the `x86_64` binary initially to access my files and folders and have alacritty prompt with the file permissions requests dialogue box and then once that was deemed "working" then copying the `universal` binary right over the top of the install with a raw `cp` command on the terminal. 

Once the state was saved this seems to "work", but installing the `universal` binary directly from source as directed, this won't work or achieve this result. So from my position there is something perhaps not happening with the `universal` binary.

**Comment by chrisduerr** [comment]
> Once the state was saved this seems to "work", but installing the universal binary directly from source as directed, this won't work or achieve this result. So from my position there is something perhaps not happening with the universal binary.

There's nothing different about universal binary or not. The only difference is that it's compiled twice and combined with `lipo`, this is just the kinda stuff you run into when you're beta-testing for macOS.

**Comment by lucasteligioridis** [comment]
To add further, I believe the issue is around the `signing` of the application within Mac. I'm not sure about how any of the signing works within the compilation on Mac within the rust ecosystem but this seemed to "fix" the issue:
https://stackoverflow.com/a/69565112

Here are the results of the `x86_64` binary when running a signature check when installed from `brew` (which fetches from the github release page):
```
λ pkgutil --check-signature /Applications/Alacritty.app
Package "Alacritty.app":
   Status: no signature
```

Here are the results of the `universal` binary when running a signature check when built directly from source:
```
λ pkgutil --check-signature /Applications/Alacritty.app
Package "Alacritty.app":
   Status: package is invalid (checksum did not verify)
```

Seems that the `universal` binary is completing some signing of the application (when compiled perhaps?) and has an invalid signature, this is what is causing the issue.

The quick resolution directly on the terminal is to just remove this `invalid` signature, I don't believe `Alacritty` is even doing proper MacOS signatures anyway, so this is actually a weird result. This is how it's solved:
```
codesign --remove-signature /Applications/Alacritty.app
```

Now the `universal` binary is able to save it's state within MacOS correctly and everything is actually working as originally expected. I'm happy to add a PR in the installation page of alacritty to reflect this if you like (please let me know and I'll happily ship that immediately), feels like a bit of a workaround for now and I lean on you @chrisduerr if you understand more about the rust ecosystem and how that signature is being completed at compile time.

**Comment by chrisduerr** [comment]
None of the binaries are signed, universal or not. This is also unrelated to Rust.

**Comment by lucasteligioridis** [comment]
I'm really not sure what to tell you further mate, I built the package from source and have clearly showed you that there is a signature that's been added there or at least something `invalid` added according to the `pkgutil` tool.

Really not sure why you are being so dismissive of this problem, I'm only trying to help here and have provided succinct proof of an issue with the compiled `universal` binary on MacOS at least from my machine and seems to be other people too.

**Comment by sharpner** [comment]
I am unsure what would help now to proof that there is a problem with the current master, but maybe a video helps:
https://user-images.githubusercontent.com/574362/143310433-48c0a1d5-0846-4ae1-919b-a78c12c82724.mov

Even if we do not correctly guess the root cause, can we please reopen this issue and acknowledge that there is a bug?

**Comment by chrisduerr** [comment]
> Really not sure why you are being so dismissive of this problem

Because the entire Apple signing and permission process is just a massive mess that only causes trouble without any benefit. And I personally have zero interest in putting my personal time into working around Apple's poor design.

**Comment by sharpner** [comment]
Understandable, but still it's an open issue then right? 

If it would not be closed someone else might want to work on it, and @lucasteligioridis also suggested to fix it by opening up a PR. 

Not fixing the signing issue feels like dropping macOS support - and I don't think that is intended?

**Comment by chrisduerr** [comment]
> Understandable, but still it's an open issue then right?

There is nothing in the codebase that has **anything** to do with permissions other than *maybe* the app manifest. Signing or not should have nothing to do with permissions either, if so that sounds like an apple not Alacritty issue.

**Comment by lucasteligioridis** [comment]
> And I personally have zero interest in putting my personal time into working around Apple's poor design

And I have zero interest on working on a project that has zero interest in supporting something they say they do, even it means just having a conversation over an issue in a more productive / positive manner.

I've already moved over to `kitty`, seeing other issues and discussions on this project has put me off entirely.
Good luck regardless of my personal feelings and thanks for your efforts this far. 👋🏼 

For any future travelers, don't forget the quick solution to this is to remove the invalid signature:
```bash
codesign --remove-signature /Applications/Alacritty.app
```

**Comment by sharpner** [comment]
okay :( I switched to kitty as well, thanks for the tips @lucasteligioridis

**Comment by 11k** [comment]
> > And I personally have zero interest in putting my personal time into working around Apple's poor design
> 
> And I have zero interest on working on a project that has zero interest in supporting something they say they do, even it means just having a conversation over an issue in a more productive / positive manner.
> 
> I've already moved over to `kitty`, seeing other issues and discussions on this project has put me off entirely. Good luck, regardless of my personal feelings and thanks for your efforts this far. 👋🏼
> 
> For any future travelers, don't forget the quick solution to this is to remove the invalid signature:
> 
> ```shell
> codesign --remove-signature /Applications/Alacritty.app
> ```

Sincerely appreciate your effort in trying to solve the issue!

Running 
```
codesign --remove-signature /Applications/Alacritty.app
```
alone didn't solve the problem for me. I wound up in a situation where the app wouldn't open at all.
![Screen Shot 2021-11-27 at 6 43 35 PM](https://user-images.githubusercontent.com/20373896/143727460-cbbf7193-dae9-4920-9db6-bca8c22e521f.png)

However, after scrolling through the StackOverflow thread you linked, I noticed [an answer](https://stackoverflow.com/a/69614400/3659054) where someone suggested using `codesign` to resign the app, like so.
```
sudo codesign --force --deep --sign - /Applications/Alacritty.app
```
That put Alacritty back into a state where `pkgutil` said the signature was invalid, but it no longer said `checksum did not verify`
![Screen Shot 2021-11-27 at 7 13 24 PM](https://user-images.githubusercontent.com/20373896/143727497-4b4e4652-cc8a-4e3a-816f-a39cedb06c80.png)

and everything started working as expected. I was no longer being prompted for permissions when Alacritty already had Full Disk Access. To add a bit more info, my machine is a new M1 14" MBP running 12.0.1.

While I agree this issue has nothing do with Alacritty directly, it does have to do with a user having to manually compile the universal binary on their machine. Quickly closing the issue out of spite for Apple only made it more difficult for me to find the solution.

**Comment by apenney** [comment]
I appreciate everyone that tried to help in here!  I also ran into this and after discovering this closed issue and the responses from @chrisduerr I decided to finally switch over to Kitty too.

Obviously as an open source project you can do as little or as much as you like when it comes to maintainership but being actively hostile to users trying to resolve their own issues is counter productive and I wish you wouldn't keep doing it.

**Comment by nicksergeant** [comment]
I ran into this issue also. I have to imagine that any developer who cares about performance enough to use Alacritty might also be interested in the performance gains to be had with an Apple Silicon chip, so this issue might continue to get a lot of attention.

Sincerely bummed that I need to switch terminal emulators after all of these years with Alacritty. It really is an excellent excellent piece of software and I recommended it left-and-right to other developers over those years.

**Comment by nicksergeant** [comment]
Though I do want to note for future travelers that @11k's steps here did work for me:

https://github.com/alacritty/alacritty/issues/5632#issuecomment-980832715

If you're looking for a one-liner:

```
  rm -rf alacritty && \
  rm -rf /Applications/Alacritty.app && \
  git clone git@github.com:alacritty/alacritty.git && \
  cd alacritty && \
  rustup update && \
  rustup target add x86_64-apple-darwin && \
  rustup target add aarch64-apple-darwin && \
  cargo check --target=x86_64-apple-darwin && \
  cargo check --target=aarch64-apple-darwin && \
  make dmg-universal && \
  cp -r target/release/osx/Alacritty.app /Applications/Alacritty.app && \
  codesign --remove-signature /Applications/Alacritty.app && \
  sudo codesign --force --deep --sign - /Applications/Alacritty.app && \
```

**Comment by geofflangenderfer** [comment]
> Though I do want to note for future travelers that @11k's steps here did work for me:
> 
> [#5632 (comment)](https://github.com/alacritty/alacritty/issues/5632#issuecomment-980832715)
> 
> If you're looking for a one-liner:
> 
> ```
>   rm -rf /Applications/Alacritty.app && \
>   git clone git@github.com:alacritty/alacritty.git && \
>   cd alacritty && \
>   rustup update && \
>   rustup target add x86_64-apple-darwin && \
>   rustup target add aarch64-apple-darwin && \
>   cargo check --target=x86_64-apple-darwin && \
>   cargo check --target=aarch64-apple-darwin && \
>   make dmg-universal && \
>   cp -r target/release/osx/Alacritty.app /Applications/Alacritty.app && \
>   codesign --remove-signature /Applications/Alacritty.app && \
>   sudo codesign --force --deep --sign - /Applications/Alacritty.app
> ```

here's what worked for me
```
rustup update && \
rustup target add aarch64-apple-darwin && \
cargo check --target=aarch64-apple-darwin && \
make dmg && \
cp -r target/release/osx/Alacritty.app /Applications/Alacritty.app && \
sudo codesign --remove-signature /Applications/Alacritty.app && \
sudo codesign --force --deep --sign - /Applications/Alacritty.app
```

having issues with x86
```
❮   rustup target add x86_64-apple-darwin && \
  cargo check --target=x86_64-apple-darwin
info: component 'rust-std' for target 'x86_64-apple-darwin' is up to date
    Checking cfg-if v1.0.0
    Checking foreign-types-shared v0.1.1
    Checking cfg-if v0.1.10
    Checking block v0.1.6
    Checking slab v0.4.5
    Checking hashbrown v0.11.2
    Checking scopeguard v1.1.0
    Checking ryu v1.0.9
error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-apple-darwin` target may not be installed
  = help: consider downloading the target with `rustup target add x86_64-apple-darwin`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `foreign-types-shared` due to previous error
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-apple-darwin` target may not be installed
  = help: consider downloading the target with `rustup target add x86_64-apple-darwin`

error: build failed
```

**Comment by mengano-net** [comment]
> Erm, for reference, I just deleted the `Alacritty.app` from `/Applications` in finder, then I re-installed it via `brew` and then ran this on my locally built universal binary:
> 
> ```
> cp -r target/release/osx/Alacritty.app /Applications/
> ```
> 
> Then everything is working as expected now with permissions, really strange.
> 
> Apologies as this might not have anything to do with alacritty and maybe something I did when I first installed it.

this worked for me, once I re-installed with brew, I only had to allow once, then presto!

**Comment by leopepe** [comment]
> ```shell
> codesign --remove-signature /Applications/Alacritty.app
> ```

Thanks for all your work and effort. I have the same issue and I really appreciate all the investigation and effor you put on this. 
It is very sad to see a very poor support from the offcial maintainers who put ZERO effort in investigating the issue and 100% effort on being dismissive and have a very pedant behaviour with the community.
