### ISSUE TITLE
Strip trailing whitespaces in rectangular select

### ISSUE THREAD

**Issue by seirl** [alacritty/alacritty#5638]
One of the most common reasons to use rectangular select is when you're in a ncurses app with a vertical split (e.g vim, weechat, tmux...) and you want to select some part of one of the panes. If you use a normal selection, you will select the content of the other vertical panes:

![image](https://user-images.githubusercontent.com/4927883/143588260-c46d8d0c-60d4-44bb-881b-d75b62e181dc.png)

Instead, by using a rectangular select, we can select the content from a single pane:

![image](https://user-images.githubusercontent.com/4927883/143588413-67e12225-70a3-4345-8b55-d8f902ee2a3f.png)

However, doing this in Alacritty doesn't remove trailing whitespaces, so the output will be a rectangle filled with whitespaces at the end of each line. Here is the output, in my editor which shows trailing whitespaces:

![image](https://user-images.githubusercontent.com/4927883/143588542-e6d8aebd-362e-4e3e-b4f3-fae7335144e8.png)

Urxvt strips all trailing whitespaces from rectangular select. I think this would be a good idea to implement in Alacritty. The UI also indicates this by having a different selection display for the trailing whitespaces that will be stripped:

![image](https://user-images.githubusercontent.com/4927883/143588809-925ff28e-b1cc-4af1-9901-8ebdc777fb78.png)

**Comment by chrisduerr** [comment]
This issue has a surprising amount of reactions so I'd assume you're not the only person feeling this way. But currently Alacritty's behavior is based on the application's content. So if the application has whitespace there, Alacritty will copy it.

Fundamentally it's clear how this conflicts with most ncurses applications, so the suggestion to always trim seems reasonable. I'm wondering if there's any scenarios though where this could cause undesired behavior. Your URxvt image seems to copy one whitespace after each line for example if I'm reading things right?

**Comment by nitnelave** [comment]
AFAIU, the "whitespace" at the end of each line is the newline? But I'm not sure about that.

**Comment by chrisduerr** [comment]
I tested urxvt myself just to make sure and it indeed strips them completely. Also tested VTE and it behaves the same way as Alacritty, so not entirely certain if there is any consensus on what the **best** behavior is.

XTerm/Kitty don't implement block selection at all afaik, so I think that should be most popular terminals I usually try.

**Comment by seirl** [comment]
> Your URxvt image seems to copy one whitespace after each line for example if I'm reading things right?

I don't know what the UI means, but the *behavior* is to trim all the newlines.

**Comment by seirl** [comment]
> XTerm/Kitty don't implement block selection at all afaik, so I think that should be most popular terminals I usually try.

Kitty does implement block selection but has the same behavior of not trimming. I actually opened the exact same issue there: https://github.com/kovidgoyal/kitty/issues/4284

If we're worried about this breaking people's workflow, is an option a possibility to consider, or would that be configuration clutter?

**Comment by chrisduerr** [comment]
> or would that be configuration clutter?

I'm afraid it kinda would be. If there is a way this could break people's workflow, chances are the current implementation is superior. If it doesn't, there's no good reason why we shouldn't switch it for everyone. Now of course [**every** change always breaks *someone's* workflow](https://xkcd.com/1172/), but I think some edgecases can be ignored unless there's significant evidence that trimming makes certain workflows impossible.

> I actually opened the exact same issue there: kovidgoyal/kitty#4284

Can I ask about your motivation behind opening both of these issues? Especially with many of the same people reacting to both issues it seems like there's ulterior motives at play rather than just wanting a feature fixed in the terminal you use?

**Comment by seirl** [comment]
> Can I ask about your motivation behind opening both of these issues? Especially with many of the same people reacting to both issues it seems like there's ulterior motives at play rather than just wanting a feature fixed in the terminal you use?

This is my current blocker from switching from urxvt to a more modern terminal, because I use rectangular selection very often. After creating both issues, I shared them on an IRC channel and some people seemed to agree with my frustration.

**Comment by chrisduerr** [comment]
> This is my current blocker from switching from urxvt to a more modern terminal, because I use rectangular selection very often. After creating both issues, I shared them on an IRC channel and some people seemed to agree with my frustration.

Thanks for clearing that up, makes sense.

I can't come up with any great reason not to strip it, so I'm willing to test this out on an experimental-basis by just changing it to see if anyone complains. Are you interested in sending a patch yourself? It should be trivial and would be a great issue to get started on for anyone willing to contribute.

The code for copying selections can be found here:
https://github.com/alacritty/alacritty/blob/master/alacritty_terminal/src/term/mod.rs#L348-L448

**Comment by seirl** [comment]
The code looks simple enough, I can probably give it a shot. :-)
