### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by twhitbeck** [alacritty/alacritty#5639]
It's Thanksgiving holiday in the US, so I'm taking a moment to say thanks for this project. It's my daily driver and has been for years now. It works really well, I love the customizability, and for me it has all the features I need. I think it solves the use case it was originally intended to, to be a great tmux companion, and that's exactly how I use it.
It's hard to create an oss project that satisfies everyone. The people that aren't satisfied tend to be the most vocal about it. So this is my attempt to buck the trend and express my gratitude to all the maintainers and contributors, especially @jwilm and @chrisduerr. Hats off to you, my friends!

**Comment by chrisduerr** [comment]
I appreciate it, thanks.
