### ISSUE TITLE
Update to newer versions of macOS

### ISSUE THREAD

**Issue by C47F15H** [alacritty/alacritty#5641]
### System

OS: macOS
Version: `alacritty 0.9.0 (fed349a)`
Aqua

![Screenshot](https://user-images.githubusercontent.com/80169337/143733774-46f1714c-cd94-4a07-a246-8b2f8f7b7647.png)

`Learn More…`: https://python.org/doc/sunset-python-2/

(the screenshot is of another app, but the same error had come for Alacritty, which i did not take a screenshot of)

**Comment by chrisduerr** [comment]
Currently no plan to do anything about this.
