### ISSUE TITLE
the alacritty.yml configuration file isn't co-operating

### ISSUE THREAD

**Issue by algorhythm256** [alacritty/alacritty#5642]
### System
OS: Linux- Manjaro, Raspberry Pi
Version: alacritty 0.9.0 (fed349aa)

Hello there! I'm another ones of those amateur 12-year-old programmers, so do excuse me if it's a silly mistake of mine. I have PT Mono as my font installed, and it said something odd about not finding `expected document start`. I hope you can help! I have attached the zipped log and yaml file below. (I didn't build from source, I used the Add/Remove software app in Manjaro to get Alacritty).
[main.zip](https://github.com/alacritty/alacritty/files/7613498/main.zip) 
Thanks!

With :four_leaf_clover: in Singapore,
Arkin.

**Comment by chrisduerr** [comment]
Haven't looked at your config, but I recommend looking up the yaml structure online. Documents are expected to be indented with whitespace and this indentation must be hierarchical and consistent. So elements at the top of the document should not have any indentation while their children have one further level of indentation. I think making sure that's the case for your document should fix things.
