### ISSUE TITLE
Issue typing characters using option modifier on MacOS nordic ISO layout

### ISSUE THREAD

**Issue by eemax** [alacritty/alacritty#5643]
I use Mac keyboard with ISO nordic layout.
I can use terminal.app without problem typing () [] {} with a combination of shift and option modifier.

When I use Alacritty there seem to be some default keybinds/issues that mess things up when I use modifier keys.
Anyone got suggestions how to deal with this?

**Comment by chrisduerr** [comment]
This is a known issue people are working on upstream. There are also several other issues about this already, I recommend looking at some of them for updates.
