### ISSUE TITLE
key_binding with Home/End chars sequence doesn't work in zsh

### ISSUE THREAD

**Issue by amordo** [alacritty/alacritty#5645]
I map `Key1` (as demo) to send Home seq. `- { key: Key1, chars: "\x1b\x5b\x48" }` and it works in bash, fish, **not in zsh**
But zsh reacts on _fn+left_ (Home)
Trying `- { key: Key1, chars: "\x1b\x4f\x44" }` (Left seq.) works in zsh
```
zsh 5.7.1 (x86_64-apple-darwin19.0)
zsh 5.8 (x86_64-ubuntu-linux-gnu) (clean docker image, just apt install zsh)
alacritty 0.9.0 (fed349a)
```

**Comment by chrisduerr** [comment]
Alacritty has no ability to detect which applications are running inside of it. A keycode is either sent to all application or it isn't. There's (some) variation to this with modes like the application keypad, but besides that it's all up to the shell.

So check if you receive the right stuff in zsh, if you don't maybe add a `mode`. If you do, nothing Alacritty can do about it and zsh just doesn't like what you're trying to do.
