### ISSUE TITLE
Application window stuck in top left corner of screen

### ISSUE THREAD

**Issue by joseph-henry** [alacritty/alacritty#5649]
When started from a desktop shortcut the application window is stuck in the top left corner with a flickering title bar and cannot be moved. This behavior is not present if one starts alacritty via the terminal.

Is there a recommended way to make a Gnome desktop shortcut on Ubuntu?

Thanks.

### System

OS: Ubuntu 21.04
Version: `0.9.0`
Gnome

**Comment by joseph-henry** [comment]
Additionally, the window control buttons are unresponsive.

**Comment by chrisduerr** [comment]
> This behavior is not present if one starts alacritty via the terminal.

So why do you believe this is related to Alacritty? Sounds like an issue with your window manager?

**Comment by joseph-henry** [comment]
Good point. Closing. Thank you.
