### ISSUE TITLE
Error starting 'alacritty' terminated by signal SIGSEGV (Address boundary error)

### ISSUE THREAD

**Issue by motoras** [alacritty/alacritty#5654]
### Issue

Hi guys,
Suddenly I can't start my alacritty terminal. I am on a fresh Manjaro box(just installed yesterday), and it work for a day without problems. However today after I installed various programs I needed alacritty stopped working.

If  I build alacritty with cargo build than run with dbg I get:
```
Starting program: /home/user/path/alacritty/target/debug/alacritty 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff6e65640 (LWP 17511)]
Thread 1 "alacritty" received signal SIGSEGV, Segmentation fault.
0x00007ffff69b3e56 in ?? () from /usr/lib/libGLX_indirect.so.0
```
I also tried to install it with ```cargo install``` but I get the same issues.

### System

OS: Linux - Manjaro
Alacritty Version: 0.9.0

### Logs

STDOUT 
```
'alacritty' terminated by signal SIGSEGV (Address boundary error)
```
Font/Terminal size: `alacritty -vv`
```
Created log file at "/tmp/Alacritty-17430.log"
[2021-12-02 23:19:54.091446229] [INFO ] [alacritty_config_derive] No config file found; using default
[2021-12-02 23:19:54.091535301] [INFO ] [alacritty] Welcome to Alacritty
[2021-12-02 23:19:54.108501777] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-12-02 23:19:54.110948127] [DEBUG] [alacritty] Estimated DPR: 1
[2021-12-02 23:19:54.110990771] [DEBUG] [alacritty] Estimated window size: None
[2021-12-02 23:19:54.111006889] [DEBUG] [alacritty] Estimated cell size: 9 x 18
fish: Job 1, 'alacritty -vv' terminated by signal SIGSEGV (Address boundary error)
```
Keyboard and bindings: `alacritty --print-events`
```
Created log file at "/tmp/Alacritty-17472.log"
[2021-12-02 23:20:18.123492279] [INFO ] [alacritty_config_derive] No config file found; using default
[2021-12-02 23:20:18.123585125] [INFO ] [alacritty] Welcome to Alacritty
fish: Job 1, 'alacritty --print-events' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by chrisduerr** [comment]
libGLX indicates a driver issue. You said it broke after installing various programs, that sounds like an update broke it for you? What makes you believe this is an Alacritty issue? Have you tried undoing the package upgrades you've performed?

**Comment by motoras** [comment]
I did no upgrades, I just used latest manjaro version with i3 wm and then I installed  various packages I needed in my daily work(various linux tools, also packages related to development in rust and cpp) definetly nothing exotic, neither I messed up with the drivers.  Unfortunately I cant point to a specific package after which alacritty stopped working( is not like after each installed package I checked if alacritty worked) .
Regarding your other question please forgive my ignorance, but I thought that alacritty crashing at startup is probably an alacritty issue.

**Comment by chrisduerr** [comment]
>  Regarding your other question please forgive my ignorance, but I thought that alacritty crashing at startup is probably an alacritty issue.

Well you didn't change anything about Alacritty that caused this crashing behavior, right? You changed the system. So to identify the issue I'd usually first look at what part of the system changed.

Can you test master or provide a full backtrace?

**Comment by motoras** [comment]
Hi Chris,
I tried to run alacritty from debugger on vs code, and this is the stack trace I've got:
```___lldb_unnamed_symbol2232 (@___lldb_unnamed_symbol2232:67)
___lldb_unnamed_symbol2234 (@___lldb_unnamed_symbol2234:15)
___lldb_unnamed_symbol2237 (@___lldb_unnamed_symbol2237:16)
QueryExtensionsString (/home/motoras/code/rust/alacritty/target/debug/build/glutin_glx_sys-bb635cc962181200/out/glx_bindings.rs:553)
load_extensions (/home/motoras/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.26.0/src/api/glx/mod.rs:757)
new (/home/motoras/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.26.0/src/api/glx/mod.rs:108)
{closure#1} (/home/motoras/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.26.0/src/platform_impl/unix/x11.rs:319)
new_first_stage (/home/motoras/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.26.0/src/platform_impl/unix/x11.rs:371)
new_impl<alacritty::event::Event> (/home/motoras/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.26.0/src/platform_impl/unix/x11.rs:455)
{closure#0}<alacritty::event::Event> (/home/motoras/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.26.0/src/platform_impl/unix/x11.rs:430)
try_then_fallback<glutin::platform_impl::platform_impl::x11::{impl#6}::new::{closure#0}, (winit::window::Window, glutin::platform_impl::platform_impl::x11::Context)> (/home/motoras/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.26.0/src/platform_impl/unix/x11.rs:169)
new<alacritty::event::Event> (/home/motoras/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.26.0/src/platform_impl/unix/x11.rs:429)
new_windowed<alacritty::event::Event> (/home/motoras/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.26.0/src/platform_impl/unix/mod.rs:123)
build_windowed<glutin::context::NotCurrent, alacritty::event::Event> (/home/motoras/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.26.0/src/windowed.rs:341)
create_gl_window<alacritty::event::Event> (/home/motoras/code/rust/alacritty/alacritty/src/display/window.rs:137)
new<alacritty::event::Event> (/home/motoras/code/rust/alacritty/alacritty/src/display/window.rs:190)
new<alacritty::event::Event> (/home/motoras/code/rust/alacritty/alacritty/src/display/mod.rs:238)
new (/home/motoras/code/rust/alacritty/alacritty/src/window_context.rs:67)
create_window (/home/motoras/code/rust/alacritty/alacritty/src/event.rs:1199)
alacritty (/home/motoras/code/rust/alacritty/alacritty/src/main.rs:185)```

I hope it helps.

**Comment by chrisduerr** [comment]
Hm, doesn't look particularly suspicious in Alacritty's code. Have you rebooted since the update? Also can you reproduce this on a fresh install?

**Comment by motoras** [comment]
I rebooted multiple times. I can't try it on fresh install, I have no other box to install, but as I said before, when I initially installed manjaro on the box, alacritty was working.

**Comment by chrisduerr** [comment]
Did you try master?

**Comment by motoras** [comment]
After one more Manjaro update looks to work. I have no idea what went wrong or what was fixed by the update. Thanks for your time Chris.
