### ISSUE TITLE
Typing causes flashing in top-left corner of terminal

### ISSUE THREAD

**Issue by jamesWalker55** [alacritty/alacritty#5656]
When typing anything, it causes a cell on the top-left to flash repeatedly. [See this recording.](https://streamable.com/e6hx8k)

I am using Windows 10. I have tried this on the portable and installed version of Alacritty, both versions have the same flashing issue.

I have also tested Alacritty 0.9, 0.8, 0.7. The bug is present in all of these versions.

### System

OS: Windows 10 Version 1809
Version: acritty 0.9.0 (fed349a)

### Logs

Crashes: None
Font/Terminal size: [Alacritty-19720.log](https://github.com/alacritty/alacritty/files/7649889/Alacritty-19720.log)
Keyboard and bindings: [events.txt](https://github.com/alacritty/alacritty/files/7649912/events.txt)

**Comment by chrisduerr** [comment]
That's an issue with your shell, not Alacritty. It shouldn't be moving around the cursor like that.
