### ISSUE TITLE
feature request: "fake transparency"

### ISSUE THREAD

**Issue by slashdevslashurandom** [alacritty/alacritty#5660]
Before compositing was widely used, a common feature of terminal emulators was to take the "root image" (typically containing the desktop wallpaper), tint it with the background color and use that as the background in a way that made the window look transparent on an empty desktop and looked good aesthetically.

Could something like this be implemented in alacritty whenever a composite manager is not available on X11?

**Comment by chrisduerr** [comment]
> Could something like this be implemented in alacritty whenever a composite manager is not available on X11?

Never.
