### ISSUE TITLE
Question: Never blinking visual select vim mode cursor colour - disappears

### ISSUE THREAD

**Issue by ayroblu** [alacritty/alacritty#5662]
Hey! I use alacritty in vim mode, and like to select text sometimes e.g. delete, etc. I also have disabled the blinking cursor.
However, the cursor colour becomes the same as the background, i.e. indistinguishable

Here's my [alacrity config](https://github.com/ayroblu/dotfiles/blob/f80a5f887b8220903649d67e913e059db4243c57/.alacritty.yml), and below is a (relatively) minimal .zshrc with just the vim mode setup:

```zsh
bindkey -v
# So that backspace deletes more things in insert -> normal -> insert mode
bindkey -v '^?' backward-delete-char

# Remove mode switching delay.
export KEYTIMEOUT=1

# Change cursor shape for different vi modes.
function zle-keymap-select {
  if [[ ${KEYMAP} == vicmd ]] ||
     [[ $1 = 'block' ]]; then
    echo -ne '\e[1 q'
  elif [[ ${KEYMAP} == main ]] ||
       [[ ${KEYMAP} == viins ]] ||
       [[ ${KEYMAP} = '' ]] ||
       [[ $1 = 'beam' ]]; then
    echo -ne '\e[5 q'
  fi
}
zle -N zle-keymap-select

_fix_cursor() {
   echo -ne '\e[5 q'
}

precmd_functions+=(_fix_cursor)
```

What I see on macOS terminal (sorry I know the colour scheme is different, I tested and it's colour scheme independent): 
![image](https://user-images.githubusercontent.com/4915682/144745358-d8ecbf71-ff27-49da-ab8b-efb5cf7a0228.png)

And in alacritty (note this is exactly the same, so the e is selected but you can't tell):
![image](https://user-images.githubusercontent.com/4915682/144745412-76ab1d04-2e4b-45f9-8ea4-a7f9b5135444.png)

I know that some other posts have reference this [example config](https://github.com/alacritty/alacritty/blob/e9c0034f4d3ee003149fe5454942bea7ff3d98be/alacritty.yml#L194), and if I alter my config accordingly:

```yml
schemes:
  solarized_light: &solarized_light
    ...
    cursor:
      cursor: '0x073642' # black
      text: '0xeee8d5' #white

```

Then I'm forced to use this color everywhere, e.g. in vim:

Before: 
![image](https://user-images.githubusercontent.com/4915682/144746217-392aa3d2-62a7-4fb6-b7ab-13dfcfaffaa7.png)

After:
![image](https://user-images.githubusercontent.com/4915682/144746229-357ad8f9-6723-467c-9b6d-13ca1f0b1542.png)

So is there a way to change this specifically for vi mode in zsh in alacritty?

**Comment by ayroblu** [comment]
Oh maybe I just got my yml off:
```yml
schemes:
  solarized_light: &solarized_light
    color:
      cursor:
        corsor: '0x00ff00'
```

Seems to work as expected (well as much as you'd hope)

**Comment by ayroblu** [comment]
^This does have the downside of changing the colour always, which is not idea, e.g. in vim syntax highlighting, I no longer have coloured cursors which is sad 😭

**Comment by chrisduerr** [comment]
Can you test master please?

**Comment by ayroblu** [comment]
I have confirmed this on master on macOS

```sh
git clone https://github.com/alacritty/alacritty.git
cd alacritty
rustup-init
zsh
rustup override set stable
rustup update stable
make app
open target/release/osx/Alacritty.app
```

**Comment by chrisduerr** [comment]
> So is there a way to change this specifically for vi mode in zsh in alacritty?

Do I understand you correctly that in macOS terminal you don't run into this problem because it has a fixed cursor color, but in Alacritty you want it to work the same way without setting a fixed cursor color?

**Comment by ayroblu** [comment]
Ohhhhh thanks for explaining!!
I didn't realise that macOS terminal has a fixed colour cursor, but that makes sense!

Perhaps in this case it's just updating the smarts in alacritty for when it's setting the visual select block colour for the cursor to something other than exactly the same as the existing background!

**Comment by chrisduerr** [comment]
I just recommend altering your vim configuration.

There is no amazing "smart" solution here, no matter what you do you'll run into one problem or another. So the best solution is just to do nothing. It's completely up to vim to control the selection and cursor colors, so it's free to render however it would like.

**Comment by ayroblu** [comment]
Sorry, all my examples occur outside of vim? I'm not sure I follow the reasoning

**Comment by ayroblu** [comment]
Please see:
> And in alacritty (note this is exactly the same, so the e is selected but you can't tell):
> ![image](https://user-images.githubusercontent.com/4915682/145622735-86f7f6bd-e1bd-41aa-9a56-c0b42486ed9f.png)

**Comment by ayroblu** [comment]
Let me also be clear on this, vim has it's own behaviour, see: 

![image](https://user-images.githubusercontent.com/4915682/145657404-f2bf9791-b836-4fee-a214-eb96d7abefd6.png)

I am happy with vim's behaviour and have no concerns with it, I only have concerns wrt to alacritty's behaviour in selecting text

**Comment by chrisduerr** [comment]
Vim/Vim mode, same difference. This works exactly as expected, so there are no plans to change anything.
