### ISSUE TITLE
Delayed display response when typing

### ISSUE THREAD

**Issue by snowzach** [alacritty/alacritty#5664]
OS: Linux Ubuntu/PopOS 21.10
Version: alacritty 0.9.0
Linux/BSD: X11 
Displaylink 5.4.1 (Dell 3100 USB Dock)

When I have two extra USB based displays enabled, I am seeing issues with Alacritty updating it's window as I type. What is interesting is that if I enable `--print-events` mode the issue doesn't happen and it works correctly. The Alacritty window is not on either of the USB displays. Essentially the window is always one character behind what I have typed. If I wait about 3-5 seconds, it will catch up and display the last character I have typed.  Could it be that it's somehow not triggering a refresh of the display? I tried the master branch and it had the same issue. 

No other apps seem to have anything related to this issue. The default terminal works perfect as well.

**Comment by chrisduerr** [comment]
Intel drivers?

**Comment by snowzach** [comment]
Yep, Dell XPS with Nvidia and Intel running on just Intel.

**Comment by chrisduerr** [comment]
Can you confirm that this bug is gone when running on Nvidia? I believe there have been three reports of that, all with Intel driver configurations. I believe there's an issue with vsync in the intel driver.

**Comment by snowzach** [comment]
Yes, I can confirm the issue is gone with Nvidia drivers. Something to do with Intel OpenGL drivers then I take it?

**Comment by chrisduerr** [comment]
> Something to do with Intel OpenGL drivers then I take it?

Yes, Intel's vsync seems to be problematic here. Wayland sidesteps this by not using vsync for frame synchronization.
