### ISSUE TITLE
Error reading from PTY in event loop when closing Alacritty with CTRL-D

### ISSUE THREAD

**Issue by fanginoort** [alacritty/alacritty#5665]
Since a while now it happens that when I close Alacritty with CTRL-D by sending an EOF, the Terminal doesn't close but instead displays  the error:

`[ERROR] [alacritty_terminal] Error reading from PTY in event loop: Input/output error (os error 5)`

This however does not happen everytime. Sometimes it closes just fine, as it always did. It seems like it only happens (but still not everytime) when I open Alacritty via dmenu. It never happens when I open Alacritty through another Alacritty instance or xterm for example.

There is no further output or content in the log in /tmp/

### System

OS: Arch Linux
Version: alacritty 0.9.0 (fed349aa) (ArchLinux Package)
Linux/BSD: X11

**Comment by chrisduerr** [comment]
Fixed on master.
