### ISSUE TITLE
Alt-key combos work under default config

### ISSUE THREAD

**Issue by 0xc0000007b** [alacritty/alacritty#5668]
Didn't want to necrobump https://github.com/alacritty/alacritty/issues/93 but I don't understand why it was closed without standard Alt-key combos becoming part of the default config, or otherwise functional by default on macOS. This is out of the box functionality one would come to expect for any editor or terminal these days, wouldn't you agree?

### System

OS: macOS Monterey 12.1 Beta (21C5045a)
Version: alacritty 0.9.0 (fed349)

**Comment by chrisduerr** [comment]
> Didn't want to necrobump #93 but I don't understand why it was closed without standard Alt-key combos becoming part of the default config, or otherwise functional by default on macOS.

Because there's other issues this is tracked in.
