### ISSUE TITLE
Cannot bind PageUp and PageDown to scrolling

### ISSUE THREAD

**Issue by eternal-sorrow** [alacritty/alacritty#5670]
I'm trying to bind PageUp and PageDown keys so that they would scroll page up and down the scrollback buffer in normal mode, but send the correct escape sequences to apps like Vim or Less. I tried this:

```yaml
  - { key: PageUp,                       action: ScrollPageUp   }
  - { key: PageDown,                     action: ScrollPageDown }
```

But it breaks scrolling in apps like vim or less, as expected. I also tried this:

```yaml
  - { key: PageUp,                         mode: ~Alt,  action: ScrollPageUp   }
  - { key: PageDown,                       mode: ~Alt,  action: ScrollPageDown }
```
But it makes no difference. Scrolling in vim and less remains broken. I reported it already #5481, but @chrisduerr didn't help me fix it, so here I am reporting this again.

### System

OS: Linux
Version: alacritty 0.9.0
Linux/BSD: Wayland, sway

### Logs

Not needed

**Comment by chrisduerr** [comment]
> I reported it already #5481, but @chrisduerr didn't help me fix it, so here I am reporting this again.

What made you think opening another issue would do anything but waste everyone's time?

Just tell it what to send in alt mode, tell it what to send in not alt and it will work just fine.

**Comment by eternal-sorrow** [comment]
>Just tell it what to send in alt mode

I have no idea what to send, that's the problem. I tried this also:

```yaml
  - { key: PageUp,                         mode: Alt,  action: ReceiveChar }
  - { key: PageDown,                       mode: Alt,  action: ReceiveChar }
```

With no luck.

**Comment by eternal-sorrow** [comment]
>Should specify the characters you actually want to send

But what characters is it? How do I find them?

**Comment by blueray453** [comment]
The following solved my problem

```
  - { key: PageUp,                     mode: ~Alt,          action: ScrollPageUp,       }
  - { key: PageDown,                   mode: ~Alt,          action: ScrollPageDown,     }
```

**Comment by eternal-sorrow** [comment]
I don't use alacritty anymore because I couldn't solve this problem. Also I already said that those didn't work for me.
