### ISSUE TITLE
cat /dev/urandom freezes terminal

### ISSUE THREAD

**Issue by jakobnissen** [alacritty/alacritty#5675]
When running `cat /dev/urandom`, Alacritty freezes up my computer. Running it in another terminal emulator works, and it also works as expected when I run in Alacritty when insize `zellij`.

### System

Linux x86-64, using X11 on Gnome shell.
Alacritty version: 0.9.0

**Comment by chrisduerr** [comment]
Can you try the latest master? Also what do you mean by "freezes my computer"?

**Comment by jakobnissen** [comment]
I haven't tried latest master and to be honest, I can't be bothered to install all the dependencies and build it just for this bug report. If you can't reproduce it on version 0.9.0 at your end, I can give it a try.

With "freezing", I mean that the following happens:
* After typing in the command, it begins quickly printing nonsense to the screen as expected
* After a fraction of a second, it stops printing and hangs. When it hangs, both Alacritty and all other applications also freezes in the sense that their graphics stops updating. Keyboard and mouse inputs are also not registered.
* In a seeminly random manner, Alacritty (and with it, all other programs) sometimes unfreezes after a few seconds, stay unfrozen for a fraction of a second, and then re-freeze. If I manage to hit Ctrl-C during this small unfrozen window, Alacritty will stop and everything will resume to normal.

**Comment by chrisduerr** [comment]
> I can't be bothered to install all the dependencies and build it just for this bug report.

Well I can't be bothered to fix it then.

**Comment by jakobnissen** [comment]
Looks like I accidentally pissed you off. That wasn't my intention to come off so abrasive. Surely we both have an interest in fixing this: Me because I want to use a fast and stable terminal (which could be Alacritty), and you because you presumably want to develop a product that actually works.

Does it really make sense to set up such a high barrier to bug reporting that the user needs to install rustup, install rust, like 5 dependencies, recompile it from source, just to check if it still doesn't work on master? If so, don't you think you might be missing out of fixing a lot of bugs for your users?

**Comment by chrisduerr** [comment]
https://github.com/alacritty/alacritty/blob/master/CHANGELOG.md?plain=1#L32
