### ISSUE TITLE
primary selection problems

### ISSUE THREAD

**Issue by nnovikov** [alacritty/alacritty#5676]
OS: Debian GNU/Linux 11 (bullseye)
Version: alacritty 0.10.0-dev (3371851c) 
Linux/BSD: X11, i3wm

Sometimes (quite rare) the terminal spoils the data in the primary selection buffer. I use simple script for monitor primary buffer:
```while true; do xclip -o; echo; sleep 5; done```
Then I highlight the words in the terminal with a double click and switch to another terminal to insert data from the primary selection. But there is old data in the buffer after that.
For example output of my script and some commens:
```
foo # <-- select in one termnal
foo
foo
bar # <-- select in second tarmona
bar
foo # <-- switch to first terminal
foo
```

May be this is a not a problem of alacritty, but I don't have enough information for that.

**Comment by chrisduerr** [comment]
https://github.com/alacritty/alacritty/issues/3601
