### ISSUE TITLE
newlines disappear on paste

### ISSUE THREAD

**Issue by TojNALvViV** [alacritty/alacritty#5678]
When using the mouse (left click+drag) to select multiple lines of text, newlines disappear if pasting (middle click) the text into an alacritty window; i.e. multiple lines of selected text end up being pasted all on one line.

This is apparently independent of the program running in the alacritty window (tried a handful of text editors with and without tmux running), and seems to be specific to alacritty (the same set of editors, with and without tmux, result in the expected paste behaviour in xterm, gnome-terminal and rxvt-unicode). This behaviour occurs with the default alacritty.yml configuration.

### System

OS: Ubuntu 20.04.3 LTS
Version: alacritty 0.10.0-dev (d8a98f88)
Linux/BSD: X11, tiling window manager

**Comment by chrisduerr** [comment]
Can you reproduce this from bash shell to bash shell?

**Comment by TojNALvViV** [comment]
I cannot!

This seems to require a text editor to be the paste recipient.

If I run bash, with or without tmux, multi-line paste seems to work as expected.

I wonder what is going on - in particular, if tmux is running, I wonder how the text editors would even know that the terminal is different - $TERM seems to be "screen-256color" if tmux is running, regardless of the terminal in use.

**Comment by chrisduerr** [comment]
Unrelated to Alacritty then.
