### ISSUE TITLE
Font not found error even though the font clearly exists on the system.

### ISSUE THREAD

**Issue by BooleanCube** [alacritty/alacritty#5682]
Even though the font "Iosevka NF" has been installed on my PC, alacritty isn't able to detect it. I downloaded this font: `Iosevka Nerd Font Complete Mono Windows Compatible` and I installed it into my system and the name of the font is "Iosevka NF" so I put that in alacritty but it doesn't work.

![image](https://user-images.githubusercontent.com/47650058/145748222-99001e33-0fbf-48c7-949c-80e437278832.png)

### System

OS: Windows 10
Version: alacritty 0.8.0 (a1b13e6)

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size (when running `alacritty -vv`): [2021-12-12 22:33:26.869998900] [ERROR] [alacritty] font FontDesc { name: "Iosevka NF", style: Description { slant: Normal, weight: Normal } } not found

**Comment by chrisduerr** [comment]
Have you tried different font names?

**Comment by BooleanCube** [comment]
> Have you tried different font names?

Shouldn't this be the font name that I use in Alacritty?
![image](https://user-images.githubusercontent.com/47650058/145895102-dd2459c4-fea3-4d92-9051-0aff96702521.png)

Also, I have the Fira Code Nerd Font installed on my PC (from the same place) and it works perfectly fine when I do:
![image](https://user-images.githubusercontent.com/47650058/145895481-3f229a01-30ad-444f-89bc-f0223bb10bdb.png)
however, if I remove the styles it actually adds italics and bold in my code and it looks weirder so I put the styles commands there because the code looks better without which is kind of odd. Shouldn't it be the other way around?
Fira Code Nerd Font:
![image](https://user-images.githubusercontent.com/47650058/145898156-919e2939-44c7-48b5-b0d4-e35743c7074b.png)

**Comment by BooleanCube** [comment]
I suppose I can just use Fira Code's font, but I really liked this font. its whatever, ill just continue to use the old font. thx for the help anyways.

**Comment by jamesz96** [comment]
Hey @BooleanCube , 
I ran into this problem just now and found this thread: https://github.com/ryanoasis/nerd-fonts/issues/586

So it is not an issue with Alacritty.

I'm not sure if you downloaded the font from the same place, but I got it from here [patched-fonts/Iosevka/Light/complete](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Iosevka/Light/complete/Iosevka%20Term%20Light%20Nerd%20Font%20Complete%20Mono.ttf)

For me I had to change the `family` attribute from `Iosevka nerd Font Mono` to `Iosevka Term` for it to work.

**Comment by BooleanCube** [comment]
> Hey @BooleanCube , In case you still have this issue. I ran into this problem just now and found this thread: [ryanoasis/nerd-fonts#586](https://github.com/ryanoasis/nerd-fonts/issues/586) (seems to be a naming problem for these iosevka fonts)
> 
> So it is not an issue with Alacritty.
> 
> I'm not sure if you downloaded the font from the same place, but I got mine from here [patched-fonts/Iosevka/Light/complete](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Iosevka/Light/complete/Iosevka%20Term%20Light%20Nerd%20Font%20Complete%20Mono.ttf)
> 
> For me I had to change the `family` attribute from `Iosevka Nerd Font Mono` to `Iosevka Term` for it to work.

ty for the help! this worked for me...
