### ISSUE TITLE
Alacritty crashes sometimes when switching between different tty on wayland

### ISSUE THREAD

**Issue by kurnevsky** [alacritty/alacritty#5684]
Alacritty crashes sometimes when switching between different tty on wayland.

To reproduce you can run `dbus-run-session startplasma-wayland` in 2 different tty, launch alacritty there and try to switch between them. It doesn't happen consistently, but after several attempts it crashes.

### System

OS: Linux
Version: alacritty 0.9.0
Linux/BSD: Wayland, KDE

### Logs

When crash happens it writes `wl_display@1: error 0: invalid object 42`, `-vv` doesn't add much info, only `[INFO ] [alacritty] Goodbye` in the next line.

**Comment by chrisduerr** [comment]
Can you reproduce this with the window example from https://github.com/rust-windowing/winit?

**Comment by kurnevsky** [comment]
It doesn't work for me for some reason. `cargo run --example window` gives:
```
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: NoWaylandLib X11 status: LibraryOpenError(OpenError { kind: Library, detail: "opening library failed (libX11.so.6: cannot open shared object file: No such file or directory); opening library failed (libX11.so: cannot open shared object file: No such file or directory)" })', src/platform_impl/linux/mod.rs:619:9
```

**Comment by kurnevsky** [comment]
ok, figured it out - had to add wayland and libxkbcommon to LD_LIBRARY_PATH. After that it launched but didn't dray a window, just spammed terminal with messages:
```
MainEventsCleared
RedrawRequested(WindowId(Wayland(WindowId(94704189932864))))
RedrawEventsCleared
NewEvents(WaitCancelled { start: Instant { tv_sec: 261899, tv_nsec: 295204787 }, requested_resume: None })
MainEventsCleared
RedrawRequested(WindowId(Wayland(WindowId(94704189932864))))
```

**Comment by kchibisov** [comment]
Try glutin window examples from https://github.com/rust-windowing/glutin. There should be window example `cargo run --example window`.

**Comment by kurnevsky** [comment]
It panics for me:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/kurnevsky/workspace/glutin/glutin/src/api/egl/mod.rs:424:32
```

**Comment by chrisduerr** [comment]
Glutin should work just as well as Alacritty compiled from master. Does that also not work for you?

**Comment by kchibisov** [comment]
Could you provide `WAYLAND_DEBUG=1 alacritty 2> out.txt` logs? It should help a lot to see what exactly crashes it. Also make sure that you're running latest alacritty's build from master.

**Comment by kurnevsky** [comment]
> Glutin should work just as well as Alacritty compiled from master. Does that also not work for you?

I believe it won't work with just `cargo run`. I have to make nixos environment that is used to build alacritty which requires some manual work. Will try to do it later.

> Could you provide WAYLAND_DEBUG=1 alacritty 2> out.txt logs?

Sure, here are the logs (from alacritty 0.9.0, will try with master later): [out.txt](https://github.com/alacritty/alacritty/files/7775011/out.txt)

**Comment by kchibisov** [comment]
It seems like a race somewhere in your display server. The pointer got released, however the server still send events for it? I'm not sure that we can do something about that, since we dropped the pointer in alacritty, then synchronized the state and we still got something for it, so libwayland-client failed to dispatch events to this object since it was longed dropped.

**Comment by kurnevsky** [comment]
Reported to kde: https://bugs.kde.org/show_bug.cgi?id=447917

**Comment by davidedmundson** [comment]
That's not quite how this all comes together.

For a given client owned object (like pointer):
 1) client creates a proxy
 2) client deletes a proxy from it's side
 3) server acks back (wl_display::delete_id) that the object has been deleted from the server side
 
From the logs step 3 hasn't happened.

You can have events in flight between steps 2 and 3. That's not a sign of kwin being in the wrong. It is a race, but an expected one that the client has to handle.

libwayland will treat the proxy as being in destroyed and silently drop these incoming messages so you're right that you shouldn't have to deal with it at an application level.

There's one rust library that doesn't wrap libwayland. Can you point me in the right direction to report there.

**Comment by kchibisov** [comment]
@davidedmundson well, we use that library, but we're using its libwayland backend, so libwayland is involved here. The version of it that we're [using](https://github.com/Smithay/wayland-rs/tree/7e87db2ae48d81a52039e727065266782c55f8ff).
