### ISSUE TITLE
Cant Render Images with printf

### ISSUE THREAD

**Issue by alexohneander** [alacritty/alacritty#5689]
### System

OS: macOS
Version: `0.9.0 (fed349a)` 

###  Error
I have written a script which renders images into the terminal with printf. With iterm or the Mac terminal this works too. With alacritty nothing happens. Is this due to a setting in the config?

#### Example
**iterm2**
![iterm2](https://i.imgur.com/9emHsDh.png "iterm2")

**alacritty**
![alacritty](https://i.imgur.com/vEhtgWh.png "alacritty")

**Comment by chrisduerr** [comment]
Working as intended.
