### ISSUE TITLE
Question: How can I override CLI app bg transparency

### ISSUE THREAD

**Issue by mcthomas** [alacritty/alacritty#5691]
With iterm2, nearly every CLI app I used having a bg color would have its transparency set by iterm's window transparency setting.  In Alacritty, I've noticed the same CLI apps force the terminal bg into using opaque colors despite my Alacritty conf defining a custom background_opacity.

Is there a way to mimic iterm's behavior in Alacritty?

**Comment by chrisduerr** [comment]
> Is there a way to mimic iterm's behavior in Alacritty?

No.
