### ISSUE TITLE
Cursor going off in FAR Manager

### ISSUE THREAD

**Issue by wilem82** [alacritty/alacritty#5693]
### System

OS: Windows
Version: 0.9.0

### How to reproduce

1. Run FAR Manager from https://farmanager.com/history/far2.x64.msi in Alacritty
2. Observe the cusor in the command line and in dialogs is fine
3. Run anything on the command line
4. Observe the cursor is now not visually moving on arrow keys, and seems to always be offset to the right by one cell

Demo video: https://www.youtube.com/watch?v=dWZu4_a2aEI

### Expectations

So, the cursor works fine in the standard Windows terminal (`conhost.exe`, or whatever it's called), always has been for the last 20 or so years. It's hard to say whether it's a FAR Manager or Alacritty bug - at first it works, and after a command line execution it breaks down. And I understand this probably won't ever be a priority to fix, because not only Alacritty on Windows is rare, but Alacritty + FAR Manager is outright improbable. But just on the off chance that somebody knows what's going on and how to fix it quickly? That would be awesome. Thank you.

**Comment by bitraid** [comment]
Why are you using and old unsupported Far version from 10+ years ago?
Latest version with key bar enabled seems to be working ok.

**Comment by chrisduerr** [comment]
> It's hard to say whether it's a FAR Manager or Alacritty bug

I can assure you it's not an Alacritty bug.

**Comment by wilem82** [comment]
> Why are you using and old unsupported Far version from 10+ years ago? Latest version with key bar enabled seems to be working ok.

The new 3.x version is very buggy - reliably crashes on window properties changes, for example on layout (rows/cols) changes. Also file highlighting stopped working, no matter what specific subversion of 3.x I'm installing, or on what PC.

It's good to know that the bug appears to be gone in 3.x, but the cursor is ok with the "native" Windows terminal in 2.x. Perhaps FAR 2.x relies on some undocumented native Windows terminal behaviour, which Alacritty does not reproduce.

**Comment by bitraid** [comment]
> The new 3.x version is very buggy - reliably crashes on window properties changes, for example on layout (rows/cols) changes. Also file highlighting stopped working, no matter what specific subversion of 3.x I'm installing, or on what PC.

File highlighting is definitely working. I've been using Far 3 every day for all these years on multiple   PCs and it's rock solid (unless you are using the nightly builds, where you can step on a bug every now and then). If you found a bug, please report it to the Far manager repo.

**Comment by wilem82** [comment]
@bitraid I just tried Far 3.0.5888.0 x64 - same broken cursor behaviour after running a command. A fresh Far 3 install, not a single thing changed in its configuration. As soon as I exit FAR back into cmd.exe, the cursor gets fixed.  None of this is happening in the standard Windows terminal, yet a possibility of this being an Alacritty bug is outright denied.  What could it be then?

**Comment by wilem82** [comment]
Clarification: the cursor bug happens neither in

- The Windows, built-in app called "Windows Terminal", nor
- Whatever terminal is getting run when you just do Win+R, "cmd.exe" - the terminal that's been there since I don't know, Windows 95

The cursor only get broken in Alacritty.

**Comment by bitraid** [comment]
@wilem82 This doesn't seem to happen with Alacritty 0.4.0 and older. Can you confirm?

**Comment by wilem82** [comment]
@bitraid I'm on Alacritty 0.9.0.

**Comment by bitraid** [comment]
> @bitraid I'm on Alacritty 0.9.0.

Yes, I know. I was suggesting to download and try version 0.4.0.

**Comment by wilem82** [comment]
@bitraid duh, sorry. Yes, you're right, on 0.4.0 this bug doesn't reproduce.

**Comment by bitraid** [comment]
This is an issue with ConPTY that is shipped with Windows. Using a newer version from the Windows Terminal distribution fixes the problem. But for that, you have to also modify the source and compile - see https://github.com/alacritty/alacritty/pull/4501.

**Comment by wilem82** [comment]
That PR link explains everything perfectly, including Alacritty's support on Windows:

> I'm not sure I get the point of this decision, then - particularly given WinPTY support's removal a year ago. If you're not going to support the old version of Windows console management in WinPTY, and you're not going to support current Windows console management in ConPTY (like literally everybody else in this space does, up to and including Microsoft themselves), then Alacritty on Windows is arguably hopelessly crippled, and one has to wonder why the Windows port exists at all.

At this point it'll be easier to just use Windows Terminal. Thanks for helping get to the root cause. Cheers.
