### ISSUE TITLE
Alacritty lagging on Sway + nvidia + Wayland

### ISSUE THREAD

**Issue by mqzabin** [alacritty/alacritty#5694]
After wayland + nvidia improvements announcement and the 495 drivers release, everything runs reasonably fine on Sway, except Alacritty, which is extremely laggy. There are [some people on nvidia forums](https://forums.developer.nvidia.com/t/nvidia-495-on-sway-tutorial-questions-arch-based-distros/192212/2) experiencing similar issues. Maybe its relatable to #2932 too.

### System
OS: Arch Linux
Version: alacritty 0.9.0 (fed349aa)
Compositor: Wayland
DE: Sway

**Comment by chrisduerr** [comment]
What makes you believe this is an Alacritty issue? I'd assume mainly just that other applications seem to work okay?

With the driver quality of nvidia and this still being a rather fresh driver, I feel inclined to dismiss it as something Nvidia will likely figure out in the future. Intel/AMD don't seem to have issues like that afaik.
