### ISSUE TITLE
macos click url add "%0A" (newline)

### ISSUE THREAD

**Issue by gcxfd** [alacritty/alacritty#5697]
macos click url add "%0A" (newline)

![image](https://user-images.githubusercontent.com/69608605/146624855-028d482f-d02c-46f4-8794-776925c62dd8.png)

![image](https://user-images.githubusercontent.com/69608605/146624863-084a3886-cbce-4dff-bd71-61af8150a8ca.png)

click this add "%0A"
```
https://open-erp.meituan.com/batchBinding/preBinding?businessId=30&charset=utf-8&timestamp=1639791432156&state=test&developerId=106416&sign=52f350b7fd4a78049d0c0784b4717cfc80a395f7
[nodemon] clean exit - waiting for changes before restart
```

**Comment by chrisduerr** [comment]
It does not, please provide more information on how to reproduce this.

**Comment by gcxfd** [comment]
see 
https://www.loom.com/share/79882dd3fbc241ff9ac41fa3b922fcdc

when the url lenght same as screen width , the "%A" will add

**Comment by chrisduerr** [comment]
Interesting, that's kinda what I suspected but I'm not able to reproduce it. Which version of Alacritty are you using? Can you maybe try the latest master?

**Comment by a5ob7r** [comment]
I could reproduce this problem on the latest master. This problem happens when a tail character of a hint matched string is on the last column.

The reproduction steps are below. Assume default hint configurations.

```
# Fill column with a hint matched text.

$ yes 1 | head -n "$COLUMNS" | tr -d '\n'; echo -e '\rhttps://hoge.hoge/path/'
https://hoge.hoge.hoge/path/111111111111111111111111111111111...

# Invoke a hint action for the output. For example, click it.
```

**Comment by chrisduerr** [comment]
> This problem happens when a tail character of a hint matched string is on the last column.

Huh, that's kinda what I expected but couldn't reproduce it myself. Will try to test again.

**Comment by a5ob7r** [comment]
I confirmed the reproduction of this problem on macOS and (Arch) Linux with the latest master, but this means that I confirmed it on verbose log info using `alacritty -vv`. You probably see a log like below.

```
[2021-12-29 17:54:29.805696868] [DEBUG] [alacritty] Launched xdg-open with args ["https://hoge.hoge.hoge/path/1111111...111\n"]
```

For additional information, `xdg-open` probably trims trailing newline character but `open`, which is used on macOS, doesn't it.

```sh
# We can access `https://github.com/` using `xdg-open` even if the URL contains newline character at the end.
$ xdg-open 'https://github.com/
'

# However we can't access it using `open`. Instead We access `https://github.com/%0A`.
$ open 'https://github.com/
'
```
