### ISSUE TITLE
Vi mode recenter with "zz" keybind

### ISSUE THREAD

**Issue by thunderblood101** [alacritty/alacritty#5704]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux
Version: alacritty 0.9.0 (fed349aa)
Linux/BSD: Sway / Wayland

### Logs (Not really applicable)

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

### Summary
In vi mode (accessed by Ctrl-Shift-Space in the default bindings), it would be nice if the keybind "zz" would recenter the window (by moving the line which the cursor is on to the middle of the screen) as it does in vim (it does **not** have the same behavior in unix vi). 

### To reproduce
1. Enter vi mode by entering Ctrl-Shift-Space (or equivilant for your OS, see the config file for Mac/Windows)
2. Place your cursor in a line not near the center of the screen
3. press "zz"
Expected behavior: Centers the cursor
Current behavior: Nothing

**Comment by chrisduerr** [comment]
Adding an action to center the viewport would certainly be possible, but not on `zz`, I'd assume `z` would serve you just as well though?

**Comment by SmashMineGame** [comment]
This is vim's keybind for it. "z" can be followed by a variety of other keys to get different behaviors. For example "zt" scrolls to put the cursor at the top of the screen.
