### ISSUE TITLE
Build and Onstall ok, but Won't Run

### ISSUE THREAD

**Issue by levone1** [alacritty/alacritty#5709]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux/BSD/macOS/Windows
Version: `alacritty --version` output
Linux/BSD: X11/Wayland, DE or Compositor and WM

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`
- Devuan Linux
- Alacritty 0.9.0
- Running Linux via lxc Wayland 

Output when typing "alacritty":

`user@c1:/$ alacritty 
thread 'main' panicked at '[SCTK] A missing global was required: wl_subcompositor', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-client-toolkit-0.12.3/src/environment.rs:183:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
user@c1:/$ alacritty 
`

Can post full backtrace if helpful

**Comment by chrisduerr** [comment]
Which Wayland compositor are you running?

**Comment by levone1** [comment]
> Which Wayland compositor are you running?

xwayland

**Comment by chrisduerr** [comment]
> xwayland

That sounds rather unlikely considering XWayland is not a Wayland compositor and the application crashes trying to communicate with a Wayland compositor.

**Comment by levone1** [comment]
> > xwayland
> 
> That sounds rather unlikely considering XWayland is not a Wayland compositor and the application crashes trying to communicate with a Wayland compositor.

Sorry - I don't kknow much technically ... I'm running lxc on SailfishOS, and created a Devuan container, which ran an X-build script at creation, and uses /opt/bin/Xwayland to open desktop.

The windows are created with qxdisplay/qxcompositor...

**Comment by chrisduerr** [comment]
> Sorry - I don't kknow much technically ... I'm running lxc on SailfishOS, and created a Devuan container, which ran an X-build script at creation, and uses /opt/bin/Xwayland to open desktop.

I'm sorry but if you're running such a complicated setup, you'll have to figure out things yourself. That's just gonna be a headache for anyone to troubleshoot.
