### ISSUE TITLE
Neovim floating window border not continuous on alacritty

### ISSUE THREAD

**Issue by blmhemu** [alacritty/alacritty#5710]
### Description

The border of neovim is broken in alacritty (see the red box in below pic). Works fine in other terminal emulators.
To confirm that it is not line spacing / font size issue, I also increased the line spacing and font size in iTerm but it still draws continuous borders. The font is also same in both the terminals.
#### Alacritty
![image](https://user-images.githubusercontent.com/19410501/147042326-a57d1473-90ff-4fac-b3f9-8bfd2464a5f0.png)
#### iTerm2 and Kitty
![image](https://user-images.githubusercontent.com/19410501/147042354-01a59c3a-7e5a-49ad-b5ae-9e94ee4ab1c0.png)

### System

OS: macOS
Version: 0.9.0

### Logs
Font/Terminal size:
![image](https://user-images.githubusercontent.com/19410501/147042159-c49ac220-7562-482b-a4ef-31087d9db11f.png)

**Comment by chrisduerr** [comment]
https://github.com/alacritty/alacritty/issues/5485
