### ISSUE TITLE
Background sometimes does not show up correctly when it is set to be different than the terminal color

### ISSUE THREAD

**Issue by xulongwu4** [alacritty/alacritty#5714]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

Alacritty does not seem to wrap lines consistently when the line's background is different than the terminal background.

The behavior can be seen in this screenshot

![Screenshot from 2021-12-23 16-32-45](https://user-images.githubusercontent.com/16892446/147293201-b798b20c-6ab0-4b91-839c-717562f89445.png)

As can be seen, I have repeated running the command `ls -l` in the directory `~/tmp/test`. The symlink `tf-opt` points to a nonexistent location, and so the color of that location is rendered with bold white font on red background. This worked correctly for the first 7 invocations of `ls -l`. In the 8th run (the last run), the red background extended beyond the length of the location where `tf-opt` points to. It extends to the width of the terminal window.

### Expected behavior

The red background in the above screenshot should stop at the end of the string representing the source location of the symlink.

### System

OS: Linux
Version: alacritty 0.9.0
Linux/BSD: X11, Budgie

**Comment by chrisduerr** [comment]
How do you know this isn't `ls`? I'm not aware of any issues related to color termination.

**Comment by xulongwu4** [comment]
@chrisduerr because I have tried `kitty` and `gnome-terminal` and they both act correctly.

**Comment by chrisduerr** [comment]
Have you tried changing Alacritty's `TERM`?

**Comment by xulongwu4** [comment]
No

**Comment by xulongwu4** [comment]
> Have you tried changing Alacritty's `TERM`?

No

**Comment by chrisduerr** [comment]
Could you?

**Comment by xulongwu4** [comment]
> Could you? Please try `xterm-256color`.

I just did. It doesn't seem to change anything.

**Comment by chrisduerr** [comment]
Could you please record a ref-test? The process is documented [here](https://github.com/alacritty/alacritty/blob/master/CONTRIBUTING.md#testing), I'm interested in the `alacritty.recording` file.

**Comment by xulongwu4** [comment]
@chrisduerr This tarball contains the generated files in the ref-test:
[alacritty-ref-test.tar.gz](https://github.com/alacritty/alacritty/files/7786633/alacritty-ref-test.tar.gz)

**Comment by j4james** [comment]
I believe this is just "background color erase" in action. The background color is set to red when the text wraps onto a new line and triggers a scroll. So when the scroll occurs, the newly revealed line fills with red. You'll find that most TEs work the same way.

**Comment by xulongwu4** [comment]
@j4james Do you think it is expected that this only happened in one of 8 invocations of `ls -l` in my snapshot?

**Comment by j4james** [comment]
Yes. I'm assuming only the last one occurred at the bottom of the screen and triggered a scroll. Or is that not what happened?

**Comment by xulongwu4** [comment]
> assuming only the last one occurred at the bottom of the screen and triggered a scroll. Or is that not what happened?

Yes that is indeed what happened. Only the one that triggered a scroll exhibited this issue.

However, I haven't noticed this issue in other TEs I have tried, including kitty and gnome-terminal. Do you have any TE in mind where I can reproduce this issue?

**Comment by chrisduerr** [comment]
Alacritty working as expected here.

> However, I haven't noticed this issue in other TEs I have tried, including kitty and gnome-terminal. Do you have any TE in mind where I can reproduce this issue?

XTerm/URxvt.

**Comment by j4james** [comment]
For the record, I just checked a few of the Linux terminals I have installed. XTerm, Konsole, Rxvt, st MLTerm, Contour, WezTerm, Hyper, and the Linux console all match Alacritty's behavior. I know VTE deliberately changed the way they handle BCE a few years back which is why you don't see this in Gnome Terminal. I expect Kitty just copied what VTE is doing (or vice versa).

**Comment by xulongwu4** [comment]
> For the record, I just checked a few of the Linux terminals I have installed. XTerm, Konsole, Rxvt, st MLTerm, Contour, WezTerm, Hyper, and the Linux console all match Alacritty's behavior. I know VTE deliberately changed the way they handle BCE a few years back which is why you don't see this in Gnome Terminal. I expect Kitty just copied what VTE is doing (or vice versa).

Thanks for this informative reply!

**Comment by martinbundgaard** [comment]
Seems to me that, while this may be common across multiple TEs, it is hardly a behavior being relied upon by anyone. It seems very inconsistent to me. Is it hard to fix? Or do you guys see any reason to keep it as is?
