### ISSUE TITLE
Some tests fail after trying to parse libtest arguments

### ISSUE THREAD

**Issue by ncfavier** [alacritty/alacritty#5717]
Since https://github.com/alacritty/alacritty/commit/62a1fad524ebdf0592bb37aed76c2caac29a7f47, the three tests `cli::tests::dynamic_title_*` fail when run with `cargo test -- --test-threads=$n`:

```
test cli::tests::dynamic_title_ignoring_options_by_default ... error: Found argument '--test-threads' which wasn't expected, or isn't valid in this context
```

The current workaround is to also pass `--skip=dynamic_title`.

**Comment by chrisduerr** [comment]
Alacritty has no limitation on requiring `--test-threads` to work? Why exactly is this an issue?

**Comment by ncfavier** [comment]
It's an issue because the nixpkgs Rust infrastructure [uses](https://github.com/NixOS/nixpkgs/blob/55dbc7de3be2c361d23a6d848109a30119f76a79/pkgs/build-support/rust/hooks/cargo-check-hook.sh#L39) that flag, so Alacritty fails to build without the workaround.

I don't think it's unreasonable to rely on that flag being supported (or at least not causing a crash), since it is mentioned in [the `cargo test` manual](https://doc.rust-lang.org/cargo/commands/cargo-test.html) and in the [documentation](https://doc.rust-lang.org/rustc/tests/index.html#--test-threads-num_threads) for Rust tests. See also [this issue](https://github.com/rust-lang/cargo/issues/8916#issuecomment-735994046) for precedent.

The `dynamic_title` tests should not attempt to parse command line arguments.

**Comment by chrisduerr** [comment]
Should be fixed with https://github.com/alacritty/alacritty/pull/5718. I'll ensure this will be part of the next release.

**Comment by ncfavier** [comment]
Thanks!
