### ISSUE TITLE
NOT AN ISSUE I made a tool, would be cool to make work with alacritty.

### ISSUE THREAD

**Issue by casonadams** [alacritty/alacritty#5720]
Here is the idea: [alacritty-shell](https://github.com/casonadams/alacritty-shell)

It works like `base16-shell` did but it only changes alacritty themes, and only based on what themes are defined in the alacritty.yml file.

Maybe this doesn't make sense to build into alacritty, but rather like it is today?  Not sure just wanted to talk it over with some folks.

**Comment by chrisduerr** [comment]
> Maybe this doesn't make sense to build into alacritty

It doesn't.
