### ISSUE TITLE
Contribution: alacritty build image

### ISSUE THREAD

**Issue by juchem** [alacritty/alacritty#5723]
I'd like to contribute something to alacritty but I'm not sure what's the best way to move forward.
Opening this ticket to gauge interest / request instructions.

I don't have a rust build environment nor can I set up one on my Debian box. Still, I want to use alacritty.

I've set up a self-contained docker image that can be used to build alacritty. It greatly simplifies building alacritty from source for non-rust developers who have `docker` installed.

Anyone who wants alacrity on Debian-based systems can simply run something like this (further instructions on the [project page](https://github.com/juchem/build-alacritty)):
```
docker run -it --rm -v "$HOME:/out" bstlang/build-alacritty
```

This will clone source repo, build and install alacritty under `~/bin` without installing anything on the host or creating temporary files.

The whole thing consists of a small `Dockerfile` and a small build script that's run as the image's entrypoint.

I'd be more than happy to work on a pull request if there's any interest.

Regarding the format of the contribution, I'm thinking something like adding the files to `contrib/build`.

Please, advise.

**Comment by chrisduerr** [comment]
> I'd be more than happy to work on a pull request if there's any interest.

There is not.

As far as building software is concerned, it would probably be difficult to find a lot of software that is easier to build than Alacritty. You have a full list of dependencies and that's all you need other than a reasonably up-to-date Rust compiler. Installing docker is more work than that already.

Of course people can build Alacritty however they want, including some random docker image pulled out of the magic cloud. But that's never going to be an official recommendation.
