### ISSUE TITLE
Config Imports error makes no sense

### ISSUE THREAD

**Issue by alkaris2** [alacritty/alacritty#5726]
### System

OS: Manjaro Linux
Version: alacritty 0.9.0 (fed349aa)`
Linux/BSD: Cinnamon 5.0.7

### Logs

```
[alacritty_config_derive] Config import not found:
    "$HOME:.config/alacritty/alacritty.yml"
```

- - -

When in my config for Alacritty is set with $HOME:.config/alacritty/alacritty.yml` I can see in the log file that it complains it can't find the config despite pointing to the actual directory file for it. I've even tried just doing full or partial directory import mapping like the following;

```
~/.config/alacritty/alacritty.yml
/home/user/.config/alacritty/alacritty.yml
```
and instead I get some error saying this;

```
[alacritty_config_derive] Exceeded maximum configuration import depth
```

How can that exceed the maximum configuration import depth?? This error makes literal no sense at all. It's like 2 levels deep in a directory. From my home directory then my `.config` directory into `alacritty` directory to the config file itself.  If you're going to have an import line, you shouldn't have a limit on how deep the directory the config lies otherwise you can't direct it to the file it's expecting.

If your `alacritty.yml` file you state the following;

```
# Imports are loaded in order, skipping all missing files, with the importing
# file being loaded last. If a field is already present in a previous import, it
# will be replaced.
#
# All imports must either be absolute paths starting with `/`, or paths relative
# to the user's home directory starting with `~/`.
```

So what's the point of having this in your instructions if it just going to complain that it exceeds import configuration depth? To me this looks like a bug, not a feature. Also why does it accept `$HOME` like it's nothing at the front of it? because it completely ignores it still, and still says it `Config import not found:` -- Just for the record I have even tried just making a copy of the file direct into my `~/` directory for reference as simply `~/.alacritty.yml` and guess what? Same issue there, complains that it exceeds import depth there also.

Even if I just comment out the entire `import:` section entirely, how can I be sure it's going to read from that file when Alacritty is started up? Where does it look to by default if it doesn't have an import section in the config to reference?

**Comment by chrisduerr** [comment]
> How can that exceed the maximum configuration import depth?? This error makes literal no sense at all. It's like 2 levels deep in a directory.

Because you're importing the file itself, creating a configuration file of infinite depth. Well you're trying to.

> Also why does it accept $HOME like it's nothing at the front of it?

It doesn't.

> Even if I just comment out the entire import: section entirely, how can I be sure it's going to read from that file when Alacritty is started up? Where does it look to by default if it doesn't have an import section in the config to reference?

How the hell do you think it would find your `import` files if the file itself wasn't loaded already? Default config locations are documented everywhere, I recommend looking into that.

**Comment by beans9926** [comment]
OS: Linux Mint 21.1
Version: alacritty 0.12.0 ( line 201 [3c3e687](https://github.com/alacritty/alacritty/commit/3c3e6870dedad56b270f5b65ea57d5a6e46b1de6) )

Log
`[0.001015663s] [ERROR] [alacritty_config_derive] Exceeded maximum configuration import depth`

> How can that exceed the maximum configuration import depth?? This error makes literal no sense at all. It's like 2 levels deep in a directory.

This issue still exists and it is really annoying whenever alacritty is opened.

The thing that is happening with the program is that even if the program finds all the config files and loads them properly, the error gets logged.

**Comment by kchibisov** [comment]
@beans9926 it's a simple anti recursion protection. You have your imports wrongly organized.

I'd advise to fix them and ensure they don't import each other again.

**Comment by beans9926** [comment]
> it's a simple anti recursion protection.
I understand that as it was documented in the code itself.

> You have your imports wrongly organized.
Organized as in the order they appear in the file?

I have two imports as follows:
`import:
  - /home/user/.config/alacritty/themes/github_dark.yaml
  - /home/user/.config/alacritty/alacritty.yml`

I tried changing their order and there was no difference after relaunching the application.

> ...ensure they don't import each other again.
I was not able to understand this. Can you explain this further?

**Comment by kchibisov** [comment]
Could you tell precisely where your config files are located?

I have a feeling that you have it in `/home/user/.config/alacritty/alacritty.yml` and then you import `/home/user/.config/alacritty/alacritty.yml` in it again, leading to recursion.

**Comment by beans9926** [comment]
> I have a feeling that you have it in `/home/user/.config/alacritty/alacritty.yml`

Yes I have my config file there

> and then you import `/home/user/.config/alacritty/alacritty.yml` in it again, leading to recursion.

so, does that mean that I shouldn't have the `alacritty.yml` line in there? (as the app finds it for itself?)

**Comment by kchibisov** [comment]
Yes, otherwise it's chicken and egg problem in a way you describe it.

**Comment by beans9926** [comment]
Thanks for the help!
