### ISSUE TITLE
Polybar blinks only when runnin alacritty

### ISSUE THREAD

**Issue by Aziffo** [alacritty/alacritty#5730]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux (arch)
Version:  0.9.0

When runnin "alacritty" command the polybar blinks automatially. This is only happening when alacritty starts. Any idea of this?

**Comment by chrisduerr** [comment]
> When runnin "alacritty" command the polybar blinks automatially. This is only happening when alacritty starts. Any idea of this?

Sounds like a polybar/driver issue. Alacritty definitely shouldn't be able to make polybar flicker, no matter how wrong Alacritty may behave.
