### ISSUE TITLE
Alacritty Locking Up on Launch

### ISSUE THREAD

**Issue by devmattrick** [alacritty/alacritty#5732]
I'm having an issue where when launching alacritty it will show the window borders but not render any of the actual terminal window:
![image](https://user-images.githubusercontent.com/5848320/147740649-c2c3c85b-0c9d-4793-aba9-7d41ecbf8f6f.png)
![image](https://user-images.githubusercontent.com/5848320/147740829-34ee4a52-52bd-4631-a60b-eab6b86993e9.png)

Rebooting the system allows for alacritty to launch properly again, but this issue has always come back I'd say within an hour or so of a restart. There doesn't seem to be any issues in console or anything, but it does eventually crash with a segmentation fault.

Thanks for your help and I'd be happy to provide any more information you need!

### System

OS: Linux
Version: `alacritty 0.11.0-dev (e2b5219e)`
Linux/BSD: Wayland on GNOME (Mutter)

### Logs

Crashes: 
The log file is available in [this gist](https://gist.github.com/devmattrick/893b1099a1c1f8bc080367a263eefc99#file-alacritty-23153-log).

Font/Terminal size: See log above.

Keyboard and bindings:
The log file is available in [this gist](https://gist.github.com/devmattrick/893b1099a1c1f8bc080367a263eefc99#file-alacritty-23616-log).

**Comment by kchibisov** [comment]
Could you try version v0.9.0? Also, when it starts to happen could you provide a `WAYLAND_DEBUG=1 alacritty` log?

**Comment by devmattrick** [comment]
> Could you try version v0.9.0? Also, when it starts to happen could you provide a `WAYLAND_DEBUG=1 alacritty` log?

Unfortunately I have an Nvidia GPU, so I needed the latest commit in order to use alacritty on wayland. 0.9.0 did not have this issue but I was running it on X11. I can try the WAYLAND_DEBUG environment variable on master though if that helps?

**Comment by kchibisov** [comment]
Closing as likely being fixed from the nvidia side.
