### ISSUE TITLE
System wide configuration

### ISSUE THREAD

**Issue by mastarija** [alacritty/alacritty#5734]
I'd like to create a system wide configuration file that can be overridden by users. I've seen that alacritty searches `$XDG_CONFIG_HOME` and `$HOME/.config` but those are user specific. Alacritty obviously has a "default" look, but is there really no way to change that default look in case user has no `alacritty.yml` in his `$HOME` directory?

**Comment by chrisduerr** [comment]
> Alacritty obviously has a "default" look, but is there really no way to change that default look in case user has no alacritty.yml in his $HOME directory?

Correct. Though you could easily create a system config yourself and import that in your user configs, does that suffice for your purposes? I'm not sure how common it is for terminals to read a system-level config by default.

**Comment by mastarija** [comment]
@chrisduerr so i've consulted with some people on IRC and apparently, XDG defines a `$XDG_CONFIG_DIRS` which is a set of directories to search for configuration in addition to `$XDG_CONFIG_HOME`. If that is not set, then `/etc/xdg` should be searched for configuration files.

I've put my "global" configuration in `/etc/xdg/alacritty/alacritty.yml` and it worked.

I'm closing this issue.
