### ISSUE TITLE
It looks like the font’s error

### ISSUE THREAD

**Issue by vioulo** [alacritty/alacritty#5736]
OS:Linux arch 5.15.2-zen1-1-zen #1 ZEN SMP PREEMPT Fri, 12 Nov 2021 19:22:07 +0000 x86_64 GNU/Linux
![2021-12-31_10-22-error](https://user-images.githubusercontent.com/27475937/147799517-b0eaeb75-6689-419e-b0da-6a823bed817d.png)

**Comment by chrisduerr** [comment]
Looks like a driver issue to me. Could you share some more info about the hardware/drivers?

**Comment by vioulo** [comment]
I am a newbie, how should I analyze information?

**Comment by chrisduerr** [comment]
Could you share some more info about the hardware/drivers?

**Comment by vioulo** [comment]
![image](https://user-images.githubusercontent.com/27475937/148533230-3c2ca143-cb26-40fa-85e9-4ccb30c15cd6.png)

**Comment by chrisduerr** [comment]
It lists multiple GPUs there, which one is actually used for Alacritty? Also if one of them doesn't work, how about the other?

**Comment by vioulo** [comment]
sorry I am not very clear.

**Comment by chrisduerr** [comment]
Which GPU driver are you running? I'd assume you're on the Nvidia dGPU so you're probably looking at either nouveau or the nvidia proprietary driver.

**Comment by 2shrestha22** [comment]
Same problem here using Nvidia dGPU.

**Comment by kchibisov** [comment]
Closing, since we don't work around the driver bugs.

You have option to manually force the `gles2_pure` renderer with `-o 'debug.renderer="gles2_pure"'`, so it'll use very limited rendering features, but should work on very old hardware.
