### ISSUE TITLE
Distinguishing between Left and Right mods key — for e. g., Left and Right Alt

### ISSUE THREAD

**Issue by poige** [alacritty/alacritty#5737]
Macbooks are known for having a single Ctrl residing on the left side only and lots of keyboard shortcuts when dealing with UNIX-like systems are easier to enter with Ctrl on the right. Not only for this reason but due to having more flexibility as well I'd use Right Alt as Ctrl on Macbook. So, probably it's not only about distinguishing but possible mods key overriding as well.

But even w/o such "mods overriding" I think most of the inconvenience could be ridden of with stuff like sending proper sequence one'd expect with Ctrl but when it's Alt pressed instead.

Looks like currently Alacritty can't provide such a workaround.

**Comment by chrisduerr** [comment]
#62

**Comment by poige** [comment]
How does that one calome to your mind as a duplicate if you're providing link to the issue which has absolutely nothing in regards of a way to handle Right Alt key differently to Left Alt.

**Comment by poige** [comment]
@chrisduerr I understand it's not easy to admit own mistakes, but still people are able to do that. Consider doing so.
