### ISSUE TITLE
How to find start and end Point of current command?

### ISSUE THREAD

**Issue by plato-eddie** [alacritty/alacritty#5738]
I was poking around the source code and was trying to figure out if Alacritty stores or has some way of figuring out where the current command being typed starts and ends.

 My conclusion so far is no, since it seems Alacritty is just the "perform" portion of the vte module, and doesn't actually know the semantics of anything it's outputting. Please correct me f my understanding is wrong, thank you so much!

**Comment by chrisduerr** [comment]
There is no such thing as a "current command". That's a concept introduced by your shell, thus you'd have to ask it for that information.

You don't even need a shell to run a terminal, you might just run Vim directly for example.
