### ISSUE TITLE
Is there any relation between Alacrity and csrss.exe process 

### ISSUE THREAD

**Issue by hiredgunhouse** [alacritty/alacritty#5741]
Probably a weird one but please bear with me.

I hear that Alacritty will trigger a security warning because Alacritty.exe created a thread into a system process csrss.exe.
Is that something that is normal behavior or something I should be worried about.

BTW. This has been a warning triggered by some security monitoring application for big corporations and I don't want to get in trouble with any security team at work.

**Comment by chrisduerr** [comment]
There's no relation, but depending on which program is telling you about that security issue it might be that something *inside* of Alacritty is doing so.
