### ISSUE TITLE
Clear terminal and history not possible with single keybind

### ISSUE THREAD

**Issue by CocaineJohnsson** [alacritty/alacritty#5751]
It appears to be either currently unsupported or at least nothing in the default alacritty.yml or readme.md provided any obvious clues.

By default CTRL+L clears the terminal, but it preserves the scrollback buffer.

The default alacritty.yml only has this relevant bind:

```
- { key: L,         mods: Control, mode: ~Vi|~Search, chars: "\x0c"          }
```

So I attempted this:

```
- { key: L,        mods: Control, mode: ~Vi|~Search, chars: "\x0c"            }
- { key: L,        mods: Control, mode: ~Vi|~Search, action: ClearHistory     }
```

Expected behaviour:

1) Press `Ctrl+L`
2) Clear terminal
3) Clear history (thus leaving no scrollback at all)

Observed behaviour:

1) Press `Ctrl+L`
2) Clear history
3) Clear terminal (leaving everything that was on screen as scrollback)

The expected behaviour can be emulated with something like:

```
- { key: K,        mods: Control,       chars: "\x0c"                         }
- { key: L,        mods: Control,       action: ClearHistory                  }
```

This implies that alacritty executes actions before character sequences or that clear history executes faster and thus wins the race condition.

Is there any way to make alacritty execute them in the "correct" order with a single keybind? (e.g executing keybinds in a FIFO stack)

Additionally clearing the screen doesn't work at all in programs like `dmesg -wH`, just injecting a ^L character sequence (I suppose it's intended behaviour, but still - it would be nice if this were possible like in termite with its CTRL+SHIFT+L bind)

### System

OS: Linux
Version: alacritty 0.9.0 (fed349aa) (currently the most up to date version in arch repos)
Linux/BSD: X11, bspwm

### Logs

I don't think these are particularly interesting, at least I didn't see anything in them at glance but here you go:
`alacritty -vv`
[alacritty.log](https://github.com/alacritty/alacritty/files/7823029/alacritty.log)

`alacritty --print-events`
[alacritty-events.log](https://github.com/alacritty/alacritty/files/7823031/alacritty-events.log)

**Comment by chrisduerr** [comment]
> Is there any way to make alacritty execute them in the "correct" order with a single keybind? (e.g executing keybinds in a FIFO stack)

No, they are executed in the correct order but the clearing through ^L is obviously not done by Alacritty but instead by the shell. It's a request to clear more than anything else.

**Comment by CocaineJohnsson** [comment]
The problem is that requesting the shell to clear is the only way to do it currently as there's no `action: ClearShell` or similar, since the only way to clear is to use the ^L escape sequence AND no way to force a wait it is therefore impossible to achieve the desired behaviour.

I disagree with the closure.

**Comment by chrisduerr** [comment]
> The problem is that requesting the shell to clear is the only way to do it currently as there's no action: ClearShell or similar, since the only way to clear is to use the ^L escape sequence AND no way to force a wait it is therefore impossible to achieve the desired behaviour.

That is correct and intended.
