### ISSUE TITLE
Error in alacritty.yml

### ISSUE THREAD

**Issue by dragonfetus** [alacritty/alacritty#5754]
I wanted to change the move keys in the vi mode to match my vi config.
  - { key: L,                           mode: Vi|~Search, action: Up                      }
  - { key: K,                           mode: Vi|~Search, action: Down                    }
  - { key: J,                           mode: Vi|~Search, action: Left                    }
  - { key: ;,                           mode: Vi|~Search, action: Right                   }
 
This is what I want the key bindings to be but when ever i try to save an error comes up saying that ; is not a valid variable.
How can I set this up?

**Comment by dragonfetus** [comment]
I want to set the right action to semicolon but none of the variables have semicolon as an option.

**Comment by chrisduerr** [comment]
That's because `;` is not an allowed key. See the config documentation to find out the names for your keys. I'd personally recommend just checking with `alacritty --print-events | grep "WindowEvent.*KeyboardInput"`.

**Comment by dragonfetus** [comment]
Thanks for the help.
