### ISSUE TITLE
Alacritty sends Alt + char instead of char with custom keyboard layout

### ISSUE THREAD

**Issue by toadjaune** [alacritty/alacritty#5755]
### System

OS: macOS 12.0.1 (21A559)
Version: `alacritty 0.10.0-dev (b0da035e)`
I am using a non-standard keyboard layout (https://qwerty-lafayette.org/)

### What's happening

For the sake of clarity, I'm gonna be using the term "Alt" instead of "Option" in this bugreport, even if that's technically the name of the key on macOS.

My keyboard layout includes various mappings with the Alt key that don't work on Alacritty, but work fine in every other program, including the default terminal emulator and iterm2.

I'll take the following mapping as example : `Alt + keycode 0 -> {` (corresponds to `Alt + a` on a qwerty layout)

If I open a terminal, run cat, and then type Alt + a, I get the following results : 

* Default terminal / iterm2 : 
```
$ cat
{
```
* alaritty : 
```
$ cat
^[{
```

Corresponding alacritty logs : 
```
[INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(5745386960)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 58, state: Pressed, virtual_keycode: Some(LAlt), modifiers: ALT }, is_synthetic: false } }
[INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(5745386960)), event: ModifiersChanged(ALT) }
[INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(5745386960)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 0, state: Pressed, virtual_keycode: Some(LBracket), modifiers: ALT }, is_synthetic: false } }
[INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(5745386960)), event: ReceivedCharacter('{') }
[INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(5745386960)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 0, state: Released, virtual_keycode: Some(LBracket), modifiers: ALT }, is_synthetic: false } }
[INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(5745386960)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 58, state: Released, virtual_keycode: Some(LAlt), modifiers: (empty) }, is_synthetic: false } }
[INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(5745386960)), event: ModifiersChanged((empty)) }
```

My understanding of what's happening : 
* I press my key combination
* The OS looks up my layout, sees that Alt + a is `{`
* The OS sends `{` to alacritty
* Alacritty receives `{` while knowing Alt is currently pressed
* Alacritty doesn't know that the OS already resolved Alt being pressed, so it interprets the situation as `Alt + {`
* Alacritty sends `Alt + {` (ie `^[{`) to the shell

### Some more reflexions

I don't really know how any of the OS apis for system input work, but from the logs I see, it looks like Alacritty doesn't have enough information here to know it should not consider its input as `Alt + {`.

But the, how does it work for other layouts ?

Consider the "U.S." MacOS built-in layout. In this layout, Alt + a maps to `å`, which works just fine in Alacritty.

Here are the corresponding logs : 
```
[INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(5185412528)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 58, state: Pressed, virtual_keycode: Some(LAlt), modifiers: ALT }, is_synthetic: false } }
[INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(5185412528)), event: ModifiersChanged(ALT) }
[INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(5185412528)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 0, state: Pressed, virtual_keycode: Some(A), modifiers: ALT }, is_synthetic: false } }
[INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(5185412528)), event: ReceivedCharacter('å') }
[INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(5185412528)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 0, state: Released, virtual_keycode: Some(A), modifiers: ALT }, is_synthetic: false } }
[INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(5185412528)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 58, state: Released, virtual_keycode: Some(LAlt), modifiers: (empty) }, is_synthetic: false } }
[INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Id(5185412528)), event: ModifiersChanged((empty)) }
```

It's exactly the same, except this time, Alacritty receives `Alt + a` in the raw event, and `å` as a character. Could this explain the difference in behavior ?
Maybe my keyboard layout isn't properly programmed, and should do something differently ?

### Related issues

I _think_ this issue is likely to be related to : 

* https://github.com/alacritty/alacritty/issues/61
* https://github.com/alacritty/alacritty/issues/2017

I don't think it's a duplicate of either, however.

**Comment by chrisduerr** [comment]
The issues you've mentioned are related, but what you're most likely looking at is #458. All these issues should hopefully get resolved at once when upstream's keyboard rework gets finished (if ever), so no need to track a million different variations of the same issue.

**Comment by toadjaune** [comment]
It looks so, indeed. Missed this one.

Thanks !
