### ISSUE TITLE
Alacritty randomly slow under wayland

### ISSUE THREAD

**Issue by 0b11stan** [alacritty/alacritty#5756]
I was very happy with Alacritty but one week ago it started to become randomly slow on stratup (like around 2 to 5 seconds slow!) and it happens 3 out of 5 times.

### System

* OS: archlinux (up to date)
* Version: alacritty 0.9.0 (fed349aa)
* WM: sway (wayland)

### Logs

I didn't take too much time on this but looks like it always happens at the same place in the code 
```
> alacritty -vv
Created log file at "/tmp/Alacritty-23048.log"
[2022-01-07 21:24:09.984295467] [INFO ] [alacritty] Welcome to Alacritty
[2022-01-07 21:24:09.984487710] [INFO ] [alacritty] Configuration files loaded from:
                                                      "/home/tristan/.config/alacritty/alacritty.yml"
[2022-01-07 21:24:10.006877162] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2022-01-07 21:24:10.008529453] [DEBUG] [alacritty] Estimated DPR: 1
[2022-01-07 21:24:10.008553067] [DEBUG] [alacritty] Estimated window size: None
[2022-01-07 21:24:10.008561891] [DEBUG] [alacritty] Estimated cell size: 10 x 19

# .... here is the waiting ..... #

[2022-01-07 21:24:13.001497507] [INFO ] [alacritty] Device pixel ratio: 1
[2022-01-07 21:24:13.008826232] [INFO ] [alacritty] Initializing glyph cache...
[2022-01-07 21:24:13.011231745] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2022-01-07 21:24:13.013900328] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2022-01-07 21:24:13.016729254] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Italic, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2022-01-07 21:24:13.019498723] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Italic, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2022-01-07 21:24:13.032866251] [INFO ] [alacritty] ... finished initializing glyph cache in 0.024012796s
[2022-01-07 21:24:13.032900227] [INFO ] [alacritty] Cell size: 10 x 19
[2022-01-07 21:24:13.032908865] [INFO ] [alacritty] Padding: 0 x 0
[2022-01-07 21:24:13.032914981] [INFO ] [alacritty] Width: 800, Height: 600
[2022-01-07 21:24:13.034169407] [INFO ] [alacritty] PTY dimensions: 31 x 80
[2022-01-07 21:24:13.036361771] [INFO ] [alacritty] Initialisation complete
[2022-01-07 21:24:13.040945677] [DEBUG] [alacritty_terminal] New num_cols is 91 and num_lines is 52
[2022-01-07 21:24:13.043638242] [INFO ] [alacritty] Padding: 0 x 0
[2022-01-07 21:24:13.043695028] [INFO ] [alacritty] Width: 919, Height: 994
```

```
> strace alacritty
...
openat(AT_FDCWD, "/sys/bus/pci/devices/0000:00:1c.0/config", O_RDONLY) = 16
read(16, "\206\200\20\235\7\4\20\0\361\0\4\6\0\0\201\0\0\0\0\0\0\0\0\0\0\2\2\0\320\320\0 "..., 48) = 48
close(16)                               = 0
openat(AT_FDCWD, "/sys/bus/pci/devices/0000:00:08.0/config", O_RDONLY) = 16
read(16, "\206\200\21\31\0\0\20\0\0\0\200\10\0\0\0\0\4\0%\355\0\0\0\0\0\0\0\0\0\0\0\0"..., 48) = 48
close(16)                               = 0
openat(AT_FDCWD, "/sys/bus/pci/devices/0000:09:00.0/config", O_RDONLY) = 16
read(16,

# .... here is the waiting ..... #

"\206\200\277\25\6\4\20\0\1\0\200\10 \0\0\0\0\0\0\352\0\0\4\352\0\0\0\0\0\0\0\0"..., 48) = 48
close(16)                               = 0
openat(AT_FDCWD, "/sys/bus/pci/devices/0000:00:1f.0/config", O_RDONLY) = 16
read(16, "\206\200N\235\7\0\0\2!\0\1\6\0\0\200\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 48) = 48
close(16)                               = 0
openat(AT_FDCWD, "/sys/bus/pci/devices/0000:02:00.0/config", O_RDONLY) = 16
read(16, "\336\0203\35\6\0\20\0\241\0\2\3\0\0\0\0\0\0\0\354\f\0\0\220\0\0\0\0\f\0\0\240"..., 48) = 48
close(16)                               = 0
...
```

**Comment by chrisduerr** [comment]
Are you running nvidia? If so, please try the latest master.

**Comment by 0b11stan** [comment]
Unfortunately yes, I'm running nvidia but after installing from source I still have the exact same behaviour.
```
> alacritty --version
alacritty 0.11.0-dev (5aa8046c)
```

**Comment by chrisduerr** [comment]
@kchibisov Are you aware of any other issues with the new proprietary nvidia driver?

**Comment by kchibisov** [comment]
I'm not aware, and I don't have hardware to test it.

**Comment by chrisduerr** [comment]
@0b11stan Could you elaborate on the hardware/driver in use and your definition of slow (how did you measure it?).

**Comment by 0b11stan** [comment]
Thank you for your responses and no I did not discover any other problem with my hardware but I'm not using a lot of GPU intensive apps. My computer is a thinkpad P52s laptop with following specs.

* CPU: Intel i7-8650U (8) @ 4.200GHz
* GPU: NVIDIA Quadro P500 Mobile
* GPU: Intel UHD Graphics 620
* DRIVER: mesa 21.3.3-2.

**Comment by 0b11stan** [comment]
I didn't have to mesure it really, before that alacritty was starting instantly. Today I have to wait 3 seconds.

If it helps, it looks like a sort of cache problem ?
When I open alacritty after using some other apps for several minutes, the bug is present but when I'm openning multiple terminals one after another, the first one is slow but the others are as fast as before.

**Comment by chrisduerr** [comment]
> I didn't have to mesure it really, before that alacritty was starting instantly. Today I have to wait 3 seconds.

Okay, then we're talking solely about a problem with startup time? Usually best measured with `time alacritty -e true`.

There's a flamegraph in Alacritty's script directory in the repo which should allow you to create a detailed overview of what takes most of the time during startup when running `alacritty -e true`, could you execute that?

**Comment by chrisduerr** [comment]
Could you maybe upload the SVG as file? The PNG is rather useless with most of the relevant parts of the names truncated.

**Comment by 0b11stan** [comment]
Sorry for the delay, you can find the uploaded [flamegraph.svg here](https://gist.githubusercontent.com/0b11stan/45bce00cf948ee06ae9a6653118ff2c2/raw/ffe4b6297363d3763b342c81ecdc66d3676c33e2/flamegraph.svg)

**Comment by chrisduerr** [comment]
And that flamegraph is from one of the runs that takes 2-5 seconds? It would surprise me if that was more than a second.

**Comment by 0b11stan** [comment]
Yes, [this one](https://gist.github.com/0b11stan/8e0aadde949ca6a084dcbee846ab7e02), i'm sure, took 4s.
```
> time ./create-flamegraph.sh -e true
    Finished release [optimized + debuginfo] target(s) in 0.09s
[ perf record: Woken up 7 times to write data ]
[ perf record: Captured and wrote 2.317 MB perf.data (278 samples) ]
writing flamegraph to "flamegraph.svg"
./create-flamegraph.sh -e true  1.14s user 0.37s system 33% cpu 4.500 total
```

You think that it may come from my environment ?

**Comment by chrisduerr** [comment]
Usually slow startup is due to graphics driver issues. You could try switching drivers if your card has multiple available.

But the flamegraph itself doesn't seem accurate.

**Comment by simvux** [comment]
I have the same issue when trying to use the newly implemented GBM in the proprietary Nvidia driver on Sway. 

What's strange is that if I open multiple terminals in succession then the startup time is somewhat normal. But if I open a new terminal after a few minutes of not having opened one, it consistently hits me with the long start up. 

For the record; I believe alacritty actually uses the Intel GPU for me as renderer. Even though I use sway via Nvidia since my laptop's display is hooked directly to the Nvidia card. So this could be some weird interaction caused by that. 

This does not happen with other applications, only alacritty. 

Sway on Void Linux
alacritty 0.9.0
GPU0: Intel TigerLake-H GT1
GPU1: NVIDIA GeForce RTX 3050 Ti Mobile
Nvidia driver version 495.46

**Comment by kchibisov** [comment]
Do you mean other OpenGL applications? Since you should test with them.

**Comment by 0b11stan** [comment]
I have exactly the same behaviour as @simvux , glad I'm not alone.
I tried with [kitty](https://github.com/kovidgoyal/kitty) and the problem is reproductible, look like it's really a problem with an underneath component...

**Comment by chrisduerr** [comment]
>  I tried with kitty and the problem is reproductible, look like it's really a problem with an underneath component...

Yeah, probably a driver thing. Multiwindow should help as a workaround but I don't think there's anything Alacritty can do to speed up OpenGL initialization.

**Comment by 0b11stan** [comment]
You're right, thank's for the help anyway.

**Comment by 1995parham** [comment]
I have the exact same issue but I have intel iGPU and Nvidia dGPU. I have property Nvidia driver as I checked `nvtop` and `nvidia-smi` alacrity doesn't run on dGPU.

**Comment by mijoharas** [comment]
For anyone else suffering from this issue, I had fixed it once, and then tried the proprietary nvidia driver again fairly recently. After switching back to nouveau, I forgot to uninstall `egl-wayland`, and while I had that installed, I suffered the slow alacritty startup time. Removing this package fixed the startup times for me.
(also, to note @1995parham I also have both an intel and nvidia gpu, and a similar setup).

(I believe this is actually the second time I experienced this, so had to try and remember what it was last time. I should remind myself to never try the proprietary nvidia driver, but I do it again once every 6 months or so to see if things have gotten any better).

**Comment by kchibisov** [comment]
That might be related to libglvnd config resolution, which is ofc up to it... It could take seconds from what I remember, but that's what happens when you have multiple vendors providing EGL on your system. I think there're some workarounds in the web to speed up it...

**Comment by cronyakatsuki** [comment]
This also happens with an amd igpu, first start of alacritty takes a couple of seconds, then next starts are fast, but then randomly after some time it starts being slow again.

This issue doesn't happen with the foot terminal.
