### ISSUE TITLE
Multiple instances of alacritty on MacOS

### ISSUE THREAD

**Issue by ericcurtin** [alacritty/alacritty#5759]
I had to write a hacky script to allow me to launch multiple instances of alacritty on MacOS. MacOS expects the application to handle multiple instance creation like Chrome does for tabbed browsing etc. Could we add something similar to alacritty? Not tabs specifically, but multiple windows somehow. Tmux is not suitable for my needs, want to be able to move the terminal anywhere.

### System

OS: macOS
Version: 9.0

**Comment by kchibisov** [comment]
Multiple windows are a part of upcoming `v0.10.0`. #607

**Comment by ericcurtin** [comment]
Oh right, thanks
