### ISSUE TITLE
Powerline symbols too small

### ISSUE THREAD

**Issue by DakshG07** [alacritty/alacritty#5760]
### System

OS: **Linux**
Version:**0.9**
Linux/BSD: **X11**, Picom and BSPWM (Gnome)

Using alacritty, the powerline symbols don't seem to render correctly.
![image](https://user-images.githubusercontent.com/48651837/148663551-cc97d0bb-bbe3-4294-b749-f6ee5f1ff9a2.png)
The symbols are too small for the boxes.

**Comment by chrisduerr** [comment]
Working as expected. The font you use for powerline glyphs just isn't compatible.

**Comment by cronyakatsuki** [comment]
I'm having this same issue with the same font working completely fine when using kitty and them being small inside of alacritty.

Fonts in question being Comic Code and Symbols nerd font, while with IBM Plex Mono it works with Symbols nerd font correctly, but doesn't when using Comic Code.
