### ISSUE TITLE
Alacritty chopping characters with rounded corners depending on text size

### ISSUE THREAD

**Issue by ericcurtin** [alacritty/alacritty#5762]
At certain text sizes (10.0 here) alacritty chops characters with corners. Other terminal emulators solve this by leaving a pad at the bottom or by not using rounded corners. Screenshots attached below.

### System

OS: macOS
Version: alacritty 0.11.0-dev (5aa8046c)

![Screenshot 2022-01-09 at 13 08 56](https://user-images.githubusercontent.com/1694275/148683748-e7c632f8-b288-4266-8ed7-e823e149f5e3.png)
![Screenshot 2022-01-09 at 13 09 21](https://user-images.githubusercontent.com/1694275/148683751-2d93de29-0828-48c1-9db7-06c7fe25cf96.png)

**Comment by chrisduerr** [comment]
Working as expected, I recommend not using rounded corners. You can also specify a padding in your config.

**Comment by ericcurtin** [comment]
Ok. How would I turn off rounded corners @chrisduerr ? I didn't turn them on

**Comment by chrisduerr** [comment]
Dunno, I don't use macOS.
