### ISSUE TITLE
Powering off screns results in inconsistent DPI/font-size

### ISSUE THREAD

**Issue by CocaineJohnsson** [alacritty/alacritty#5767]
Powering off a screen results in inconsistent font/DPI size for all alacritty instances on that screen until the screen resolution is manually changed, including newly spawned alacritty instances.

It appears it gets confused about the `Device pixel ratio:`

Before power off, and expected result after a power on/off cycle:
Note how both alacritty and urxvt have the same, correct, font size.
![Screenshot_2022-01-11_07-15-51](https://user-images.githubusercontent.com/53689060/148892354-750eea0b-3880-4392-aa0a-74b045564f60.png)

After a power cycle:
Notice how only urxvt has the correct font size.
![Screenshot_2022-01-11_07-15-26](https://user-images.githubusercontent.com/53689060/148892357-6428c574-a221-4c89-9a3c-b787db9801a4.png)

(the rendered image size only differs in the first screenshot due to neofetch drawing them as a percentage of terminal height, the second one naturally being smaller due to being spawned after and being less tall due to it)

### System

OS: Linux
Version: alacritty 0.9.0 (fed349aa)
Linux/BSD: X11, bspwm, nvidia

### Logs

Font/Terminal size: `alacritty -vv`
before and during power off: [alacritty.log.1.txt](https://github.com/alacritty/alacritty/files/7844191/alacritty.log.1.txt)
after power off to demonstrate that the pixel ratio is different: [alacritty.log.2.txt](https://github.com/alacritty/alacritty/files/7844192/alacritty.log.2.txt)

Keyboard and bindings: `alacritty --print-events`
[alacritty_events.log.txt](https://github.com/alacritty/alacritty/files/7844245/alacritty_events.log.txt)

**Comment by chrisduerr** [comment]
Do you have multiple monitors? This looks like it's getting the DPR from a different monitor.

Also has this always been an issue, or is this a regression?

**Comment by CocaineJohnsson** [comment]
I have multiple screens but they're all identical make and model and use the same configuration, if I turn off only one screen this affects only that screen.

I don't know if it's a regression, I've only used alacritty for about a month, maybe a bit less.

**Comment by chrisduerr** [comment]
> I don't know if it's a regression, I've only used alacritty for about a month, maybe a bit less.

Could you maybe test a previous version? There have been other issues reporting similar problems so just testing 0.8.0 could already help.

**Comment by CocaineJohnsson** [comment]
It happens as far as 0.7.2, will test older releases later.

It happens in 0.10 RC2 as well

**Comment by CocaineJohnsson** [comment]
Further testing:

0.4.0 
```
thread 'main' panicked at 'attempted to leave type `linked_hash_map::Node<serde_yaml::value::Value, serde_yaml::value::Value>` uninitialized, which is invalid', /home/cocaine/.cargo/registry/src/github.com-1ecc6299db9ec823/linked-hash-map-0.5.2/src/lib.rs:174:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Won't test older versions or 0.4.2 due to this, don't know if the issue is present or not.

0.5.0:

Issue is present, if it's a regression it's been in the codebase for quite a while.

**Comment by chrisduerr** [comment]
> Won't test older versions or 0.4.2 due to this, don't know if the issue is present or not.

No worries, testing 0.7.2 was plenty already. That's all I wanted to know.

I'd assume that running with `WINIT_X11_SCALE_FACTOR=1 alacritty` fixes this issue?

**Comment by CocaineJohnsson** [comment]
Yes, it does.
