### ISSUE TITLE
How to Make Alacritty Always Daemonize Unless There are no Running Alacritty Intstances?

### ISSUE THREAD

**Issue by Amarakon55** [alacritty/alacritty#5771]
the command "alacritty msg create-window" launches an alacritty daemon. But in order for it to work, you need to have at least one alacritty already open. I would like for it to automatically launch "alacritty" it there are no running terminals but it should run "alacritty msg create-window" it there is a running alacritty. I tried writing this script but it does not work:

`{ [ "$(pgrep alacritty | wc -l)" = "0" ] && alacritty "$@"; } ||
{ alacritty msg create-window "$@"; }`

**Comment by Amarakon55** [comment]
Update: I found a working command to do this:
alacritty msg create-window || alacritty

**Comment by kchibisov** [comment]
>Update: I found a working command to do this:
alacritty msg create-window || alacritty

Well, I guess you've got your answer.
