### ISSUE TITLE
TUI lines unaligned using the JetBrains Mono Font

### ISSUE THREAD

**Issue by BetaLost** [alacritty/alacritty#5772]
Title says it. If I change the font to anything else then the lines appear just fine, but if I change it to a JetBrains Mono font, the lines are unaligned.

I did not get this issue on any other terminal emulator, using this same exact font. I get this issue with all programs that use a TUI.

Example: https://i.imgur.com/DeY7DOr.png
Expected (image taken on gnome-terminal): https://i.imgur.com/kixIa24.png

### System

OS: Arch Linux
Version: alacritty 0.9.0 (fed349aa)
Linux/BSD: X11, BSPWM + Picom (Ibhagwan fork)

**Comment by chrisduerr** [comment]
See v0.10.0 changelog.
