### ISSUE TITLE
Allow Windows users to use the .config directory

### ISSUE THREAD

**Issue by Dead0fNight** [alacritty/alacritty#5781]
I spent more than an hour trying to figure out why alacritty wasn't updating when I changed my configs, and found that the config had moved silently to AppData. Could we have an option to use .config or at least some notification when the config is moved?

**Comment by chrisduerr** [comment]
> the config had moved silently to AppData

It hasn't. It's always been in AppData.

> Could we have an option to use .config or at least some notification when the config is moved?

No.

**Comment by Dead0fNight** [comment]
Please accept my apologies for jumping to conclusions. I must have moved it there myself on my Windows machine without making a note of it anywhere, and not having made modifications in a while assumed it was something changed in an update.

**Comment by chrisduerr** [comment]
No worries, you can always use `--config-file` as CLI parameter if you **really** want to load it from a different directory.
