### ISSUE TITLE
cmd-backtick on mac being eaten by alacritty

### ISSUE THREAD

**Issue by nipunn1313** [alacritty/alacritty#5782]
On mac, "Cmd + Tab" rotates through windows and "Cmd + backtick (`)" rotates through windows of a given application (eg all my terminal windows). It seems that this behavior doesn't work with alacritty. Possibly alacritty is eating the keybinding. I have nothing in my `alacritty.yml`

This was surprising to me. I would expect the `Cmd + backtick` to work the same as all programs on mac in the absence of any special overrides.

Appreciate y'all for working on alacritty!

### System

OS: Mac

Version: `alacritty --version` output
alacritty 0.10.0-dev (6d1a63ef)

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by chrisduerr** [comment]
Alacritty certainly doesn't use that command, it likely just requires some form of client integration from macOS. Are you talking about a multi-window scenario, or are you running separate instances? The latter cannot be supported on macOS afaik.

**Comment by nipunn1313** [comment]
AHA - thanks for the explanation.
I was in the latter scenario (multiple instances) when I thought I was in the former scenario.

I had to download the 0.10.0 release do the steps in this comment
https://github.com/alacritty/alacritty/issues/607#issuecomment-982307003

to enable multi-window. Now cmd-backtick works great!

I think my original hypothesis in the title was the wrong explanation for the behavior. Thanks for helping clarify.

**Comment by sshock** [comment]
I ran into this as well and didn't even realize that it was because cmd+N was creating new instances not new windows.

Other programs, including other terminals and web browsers, open a new window not a new instance when cmd+N is hit.

Is there any reason we shouldn't change the default key bindings for cmd+N from `SpawnNewInstance` to `CreateNewWindow`.  I'm happy to create a PR if there are no objections.

**Comment by djthread** [comment]
I just ran into this. I agree, @sshock ! That would seem to be more expected behavior. Binding to `CreateNewWindow` instead resolved the issue for me.
