### ISSUE TITLE
Error Reading from PTY in Event Loop - XWayland and Suckless Tabbed

### ISSUE THREAD

**Issue by Fuzzy-Math** [alacritty/alacritty#5797]
When utilizing Suckless Tabbed under XWayland and fullscreen/maximized and upon closing a tab (keybind or exit command): "[Error] Error reading from PTY in event loop: Input/output error (os error 5)"

Steps to reproduce:
   - Launch tabbed alacritty with "env WAYLAND_DISPLAY= tabbed -c alacritty --embed"
   - Make the window fullscreen
   - Create one or more tabs
   - Delete a tab
   - Error as shown. The tab does not close nor does it process further input. Other tabs can be switched to and work fine

### System

OS: Linux (openSUSE Tumbleweed)
Version: 0.9.0
DE: Gnome 41.3 Wayland Session
Graphics Driver: Mesa Intel

### Logs

Invocation:
![Alacritty Launch](https://user-images.githubusercontent.com/55679700/150496457-afa8b71f-d104-4187-b016-5f350b6f8664.png)

Error Log: 
![Alacritty Error](https://user-images.githubusercontent.com/55679700/150496574-933b0dca-c17d-4c4a-94fe-daa6794a6f81.png)

**Comment by chrisduerr** [comment]
Can you try the latest master? That should fix it.

**Comment by Fuzzy-Math** [comment]
Verified working on Master (alacritty 0.11.0-dev (c4d610d5))
