### ISSUE TITLE
FAR Manager mouse and shortcuts

### ISSUE THREAD

**Issue by 237dmitry** [alacritty/alacritty#5805]
### System

OS: Windows 11
Version: `alacritty 0.10.0 (8a26dee)`
FAR: `Far manager, version 3.0.955.0 x64`

Please help. Explain how to enable mouse support and all of keyboard hotkeys (including custom, defined by user) in FAR. In other terminals (ConEmu, Windows Teminal, conhost) Far is fully functional.

**Comment by chrisduerr** [comment]
Windows issue.
