### ISSUE TITLE
Mouse and some of shortcuts do not work in FAR.

### ISSUE THREAD

**Issue by 237dmitry** [alacritty/alacritty#5807]
### System

OS: Windows 11
Version: `alacritty 0.10.0 (8a26dee)`
FAR: `Far manager, version 3.0.955.0 x64`

Do not work mouse and not off all shortcuts. And, please, do not close this issue again.
The same behavior with [musikcube](https://github.com/clangen/musikcube/releases)

**Comment by bitraid** [comment]
Probably same as #5693.

**Comment by 237dmitry** [comment]
A pathetic parody of the linux version. Not a damn thing works.
