### ISSUE TITLE
window.opacity option does nothing, background_opacity still works

### ISSUE THREAD

**Issue by Kommynct** [alacritty/alacritty#5808]
I'm receiving a warning that background_opacity is deprecated and to use window.opacity instead, however, when I change the value to window.opacity it seems to do nothing

### System
archlinux sway
alacritty 0.10.0 (8a26dee0)

**Comment by Kommynct** [comment]
I'm stupid... you're supposed to put it under window: not make it window.opacity, this could be more clear but this is clearly my bad, sorry.

**Comment by Youngermaster** [comment]
Thank you @Kommynct, I was facing the same issue.

If someone doesn't understand, what you have to do is in `alacritty.yml` file go to the section `window` and add the `opacity` value that you need, like this:

```yaml
#.... Stuff

window:
    opacity: 0.7

# ... More stuff
```

_Note:_ If the `window` option doesn't exist, you can also copy and paste that code.

**Comment by SpidFightFR** [comment]
> I'm stupid... you're supposed to put it under window: not make it window.opacity, this could be more clear but this is clearly my bad, sorry.

Oh okay, thanks, i wrote "window.opacity" too lmao, i guess you're not the only one to be stupid... 😂

**Comment by chrisduerr** [comment]
Unfortunately there's no better way to document yaml's hierarchical nature. If you have any ideas I'm all ears.

**Comment by mielouk** [comment]
![2022-02-06-123700_grim](https://user-images.githubusercontent.com/3057062/152679037-3bf97b62-deec-4f4a-90e7-e325c85f6ba4.png)

Too clarify:

- Don't put it under dimensions.
- Don't put it directly under window: as suggested above. Then it will miss a character after 'dimensions: '
- It only worked for me at the exact position as shown in the partial screenshot.

**Comment by heysokam** [comment]
> Unfortunately there's no better way to document yaml's hierarchical nature. If you have any ideas I'm all ears.
Yes, I have. List it as "window: opacity" or mention "moved to the window section, with name `opacity`".   
Whatever it is, don't say window.opacity, because intuitive thought is to just change the naming, change the underscore to a dot, and keep it where it was (which is wrong).
Luckily there is google, which will bring people here, but that's such an unnecessary step.

**Comment by valentino-sm** [comment]
Just got hooked as well.
