### ISSUE TITLE
Custom font for box drawing characters

### ISSUE THREAD

**Issue by h0adp0re** [alacritty/alacritty#5809]
Hello, the latest version includes and uses a font for box drawing characters. Is it or will it be possible to use a custom font for those? Or maybe just a boolean switch to keep using whatever it was before, I assume `font.normal`? Please?

The problem I have with the new solution is that the characters are way too thin and look out of place in a terminal environment; vertical lines have gaps in between them; the curves are asymmetrical; the curves don't exactly line up with the vertical lines. None of those issues existed before `0.10.0`.

Seeing as you will also be bundling your own powerline icons in the future, I hope an option will exist to dismiss any built-in fonts, they interfere with what I have already spent time on configuring.

**Comment by kchibisov** [comment]
Are you using `font.offset.y`? I think it'll have gaps only in that case.

**Comment by h0adp0re** [comment]
Yes, I am.

**Comment by kchibisov** [comment]
Yeah, I think buildin font should account for line interval, since normal fonts just draw outside of bounding box here. As for thickness it's the same as underline thickness, so it seems like underlines are also out of place for you.

As for now, not using `font.offset` should make everything contiguous.

**Comment by h0adp0re** [comment]
The font I've selected has all characters under control, and they have a pleasant width.

Underlines are used differently, visually – they're always paired with text. I would then amend my statement: thin strokes look bad to me when in isolation, e.g. as a border of a popup window. It's just too sharp and not easy on the eyes at all.

Can I ask what will the fix be? If you're suggesting removing `font.offset` then why have the option at all when it breaks every box drawing from `0.10.0` onwards? I sincerely hope we can somehow "go back" to the way it was.

**Comment by deathlyfrantic** [comment]
I agree with this issue. For me, the boxes with the custom font are contiguous and look "fine", i.e. no broken transitions, but it's way thinner than the font I use and very obviously out-of-place.

**Comment by deathlyfrantic** [comment]
FWIW in the original issue about this, @chrisduerr pointed out there should be an option to disable this behavior.
https://github.com/alacritty/alacritty/issues/5485#issuecomment-917410712

**Comment by gkapfham** [comment]
Hello! Thanks for all of your hard work on alacritty, I appreciate it and have been using this terminal for years! I've also noticed that for version `alacritty 0.10.0 (8a26dee0)` of alacritty installed on Arch Linux that separating lines (i.e., those in Tmux or in pop-up menus in Neovim) are now noticeably thinner and, in fact, hard for me to see.

I have read any related issues and I cannot see a way to disable what seems to be this new feature in alacritty. Is there a way to disable this behavior and only use the font that I have specified in my Alacritty configuration? For reference, I have read #5485 that @deathlyfrantic mentioned and I don't see a way to disable it right now?

Overall, I'm pretty sure that I would prefer to use alacritty the way in which it worked before this recent update when the borders became noticeably thinner. If there are any other details that you would like me to share, including configuration or screenshots, please let me know and I will be glad to help as my schedule permits.

Thanks in advance!

**Comment by doums** [comment]
After updating alacritty, I had the bad surprise to see the box characters horribly thin, and obviously not coming from the font I set in the config and so arbitrary replaced. Whereas until now I was very happy with the box glyphs of my font (Jetbrains Mono). 

My first reaction was

> "Wtf, for what fucking reason, alacritty is arbitrary replacing some glyphs of my font !?"

I was very surprised about this kind of problem happening in alacritty.

Then I see this issue, and the culprit PR https://github.com/alacritty/alacritty/issues/5485. And I'm even more surprised that there is no option to disable this "feature" (and, this should be disabled by default in my honest opinion, I mean a user expects to see the glyphs from the font he picks no ?)

Plus the fact that, today, modern fonts provide dedicated boxes, powerline glyphs etc.. not to mention nerds font with custom patch/build, Iosevka etc..

**Comment by chrisduerr** [comment]
> this should be disabled by default in my honest opinion, I mean a user expects to see the glyphs from the font he picks no ?

Pretty much every major terminal will use custom glyphs for these characters, so I'd say the expectation of terminal users is usually the opposite.

> Plus the fact that, today, modern fonts provide dedicated boxes, powerline glyphs etc.. not to mention nerds font with custom patch/build, Iosevka etc..

They provide all these symbols to *try* and make the underlying issues as unnoticable as possible. But the fact is unfortunately that due to font scaling and anti-aliasing you will always run into these issues even with a "patched" font. It's just a matter of looking closely enough.

> Note: In Kitty, by default nothing is replaced, and box glyph are displayed as expected

Funny you say that because Kitty has been using a custom font for these for a long time now.

> Com'on, it's hard to see that this trade off, originally comes from a user that was not happy of its "neofetch" output -_-

This issue is a fundamental problem with text rendering that is present in *many* applications even beyond terminal emulators (you'll be able to notice the same issues in your Browser for example).

**Comment by bluz71** [comment]
I use the Iosevka font and Alacritty underlines have always been too thin. But I don’t use underlines that often, no big deal.

But for box drawing, add me to the 0.10.0 too thin crowd. For my font box drawing characters should be twice as thick as they currently are to look good again.

I support inbuilt box drawing, but the current thickness is way to thin (almost invisible in my case).

An option to specify the desired thickness?

**Comment by doums** [comment]
> Funny you say that because Kitty has been using a custom font for these for a long time now.

![image](https://user-images.githubusercontent.com/6359431/151773860-626d3f69-72ae-4969-a411-8aca490a54bb.png)

left is kitty, right is alacritty, so explain me, what is funny now ?

I think Kitty manages this feature in a smarter way, if the font provides the boxes glyph, it does not override it as this is the case in Alacritty, which is obviously logic.

I'm not entirely against this feature. I just think it's poorly implemented, or incomplete.
There should either be an option to disable it, and should be disabled by default so as not to surprise users. Either be activated automatically by character (as seems to be the case with Kitty), as a fallback system, if the font does not have a given character.
But please, arbitrary replacing user glyph is **not** a good solution.

**Comment by chrisduerr** [comment]
> I think Kitty manages this feature in a smarter way, if the font provides the boxes glyph, it does not override it as this is the case in Alacritty, which is obviously logic.

That's just… wrong.

**Comment by kchibisov** [comment]
@doums please try latest master, there's an option to disable them, they are also thicker and better align. thx.

**Comment by kchibisov** [comment]
Closing, since I think major concerns with builtin font were solved.

**Comment by h0adp0re** [comment]
Yes, I can confirm. Latest master contains the fix for this issue.

**Comment by bluz71** [comment]
Double confirmation. On macOS, the super-thin box drawing lines have been resolved on master. Superb.

Side note, for my Linux setup, the latest commit resulted in no change...but neither did my Linux setup have the thin box drawing issue that my macOS  setup had. Nothing to fix here, no change. All good.

Great work, especially since native box-drawing solves a _whole host of other issues_ (tmux pane lines, fzf preview boxes, etc etc).

Thanks @kchibisov and @chrisduerr.

**Comment by cova-fe** [comment]
Hi, I tested master and indeed fixes the "too thin" lines, now my neovim looks better, thanks @kchibisov  and @chrisduerr  :). However, I came from #5742 and I was using @kchibisov builtin-box-drawing branch; switching to master recreated the "broken vertical lines" issue. My understanding is that the two issues are strictly related, but I can be wildly wrong. Note, on kitty I have the best looking situation, with thick enough vertical lines and no broken lines. Is kitty using some builtin fonts? Or there could be another way to tackle the issue?

**Comment by kchibisov** [comment]
>I was using @kchibisov builtin-box-drawing branch; switching to master recreated the "broken vertical lines" issue.

Just ensure that you have the latest commit from master, since it should include all fixes. If it doesn't work, share the screenshot of what is broken.

**Comment by cova-fe** [comment]
So: alacritty 0.11.0-dev (8f1abe1) (Linux)
with `builtin_box_drawing: false` I get this:
![image](https://user-images.githubusercontent.com/385249/152137483-2e3aa3be-300e-4a48-a255-8e943fda9af2.png)
with `builtin_box_drawing: true` 
![image](https://user-images.githubusercontent.com/385249/152137742-59efff25-f531-43c0-81c3-793110b39559.png)
same editor, but with kitty:
![image](https://user-images.githubusercontent.com/385249/152137948-f6ea657a-3d08-42a6-ac19-d7d91255254c.png)

(never mind other differences like italic in keywords)

Font:
```font:
  normal:
    family: "Hack Nerd Font Mono"
    style: Bold
```

**Comment by kchibisov** [comment]
Could you post the glyph which isn't showing with `builtin_box_drawing` chars? I think I known what it is, just ensuring.

**Comment by cova-fe** [comment]
> Could you post the glyph which isn't showing with `builtin_box_drawing` chars? I think I known what it is, just ensuring.

You mean the vertical bar used for indentation? It is U+258F . Please note also the vertical green bar on lines 9-11. it is a different glyph (U+258E), but the "thinning" effect of _builtin_box_drawing: true_  is pretty much visible. Likely, the 258F becomes simply too thin to be viewed. (9pts font)

I can use a different gliph, no problem, by configuring manually the editor. However, difference with other terminals like kitty and konsole is noticeable. kitty and konsole behaves more or less in the same way.

**Comment by kchibisov** [comment]
@cova-fe #5847 should fix this issue.

**Comment by cova-fe** [comment]
> @cova-fe #5847 should fix this issue.

Pretty much yes:
![image](https://user-images.githubusercontent.com/385249/152213088-0214f288-7ae1-4832-a62f-93560fc67ac1.png)
(background: alacritty, foreground: kitty)

The only difference left is in U+258E (green vertical line in gutter)
Thanks!

**Comment by kchibisov** [comment]
@cova-fe should be fixed on that branch now.

**Comment by cova-fe** [comment]
> @cova-fe should be fixed on that branch now.

Indeed (I used master branch):
![image](https://user-images.githubusercontent.com/385249/152299939-9c1ac4c3-b633-4a77-ab40-db8abd66855e.png)
(background: updated master branch)

Great, many thanks!
