### ISSUE TITLE
Background_Opacity deprecated, window.opacity not working

### ISSUE THREAD

**Issue by 4164696f73** [alacritty/alacritty#5810]
### System

OS: Arch Linux
Version: alacritty 0.10.0 (8a26dee0)
Linux/BSD: X11, picom, AwesomeWM

### Logs

Crashes: ---
Font/Terminal size: Irrelevant
Keyboard and bindings: Irrelevant

Installed Alacritty today, threw my old config that doesn't change much, and upon launching Alacritty, it says "[WARN] See log at /tmp/alacritty-825755: Config warning: background_opacity is deprecated; use window.opacity instead". So I change "background_opacity: 0.8" to "window.opacity: 0.8", but transparency disappears. With previous setting, so "background_opacity: 0.8", I do have the transparency, but the warning always pops upon the bottom.

**Comment by iacchus** [comment]
Same here, but observe that `window.opacity` is in the reality:

```
window:
  opacity: 0.8
```

Uncomment the first line and add the second, this works.
