### ISSUE TITLE
Themes no longer applied to CSDs

### ISSUE THREAD

**Issue by xerz-one** [alacritty/alacritty#5812]
Starting with Alacritty 0.10.0 RC1, as part of commit 4c6a763850a5dec0fa34d15e356dcba19875690a, Wayland client decorations have been changed, removing alongside the previous theming settings for window titlebar and borders.

<details><summary>Before</summary>

![image](https://user-images.githubusercontent.com/2456419/150833542-f444fd34-8a02-411e-a316-51fae4b56e23.png)
</details>

<details><summary>After</summary>

![image](https://user-images.githubusercontent.com/2456419/150833742-1b3e021c-65a7-4b45-84cc-8792e438663f.png)
</details>

As far as I know, there is no longer a way to set how the CSD is rendered. Furthermore, I couldn't find a ticket containing the reasoning behind removing the feature (neither for the change in button bitmaps). However, this is a feature that I at least would want back, as I personally find the new interface much less likeable, and I was satisfied with my previous configuration. Thus: what is the reason CSD themes were removed, and can it be brought back? Thanks in advance.

**Comment by chrisduerr** [comment]
> As far as I know, there is no longer a way to set how the CSD is rendered.

Correct, this is working as intended.

> what is the reason CSD themes were removed

Maintenance overhead.

**Comment by xerz-one** [comment]
Any way to bring them back? What is the specific "maintenance overhead", and could it be assigned to someone?

**Comment by chrisduerr** [comment]
> Any way to bring them back?

No.

> What is the specific "maintenance overhead"

CSDs have to be fully rendered by Alacritty. The new one has removed all of the complexity of doing so (like text rendiring) in favor of just drawing what is minimally usable.

While it might be possible to draw more complicated decorations again, I don't think anyone is interested in implementing or maintaining it. So I strongly recommend relying on SSDs should you desire decorations.
