### ISSUE TITLE
Window opacity not applied when set in alacritty.yml 

### ISSUE THREAD

**Issue by robowraith** [alacritty/alacritty#5814]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux (EndeavorOS)
Version: alacritty 0.10.0 (8a26dee0)
Linux/BSD: X11, Plasma/i3 with Picom (picom-ibhagwan-git)

After updating to 0.10.0 I received the warning that `background_opacity` was deprecated and I should use `window.opacity` instead.
Since changing it in alacritty.yml did not seem to work (opacity was fixed at 1.0, even if the window was inactive and should have been drawn transparent by picom), I downloaded the current alacritty.yml from the release page and tried again,
```
# Window decorations
  #
  # Values for `decorations`:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  #
  # Values for `decorations` (macOS only):
  #     - transparent: Title bar, transparent background and title bar buttons
  #     - buttonless: Title bar, transparent background and no title bar buttons
  #decorations: full

  # Background opacity
  #
  # Window opacity as a floating point number from `0.0` to `1.0`.
  # The value `0.0` is completely transparent and `1.0` is opaque.
  opacity: 0.5

  # Startup Mode (changes require restart)
  #
  # Values for `startup_mode`:
  #   - Windowed
  #   - Maximized
  #   - Fullscreen
  #
  # Values for `startup_mode` (macOS only):
  #   - SimpleFullscreen
  #startup_mode: Windowed
```

 with the same result, yet `alacritty -o window.opacity=0.5` works

**Comment by smsteward** [comment]
I too have this issue and was just about to submit this report! Glad I'm not the only one. I've tried various setting words like `opacity: 0.8`, `window.opacity: 0.8`, `window_opacity: 0.8`, and nothing worked. Using `background_opacity` continues to work, and I just have to close the annoying deprecation warning every time I launch alacritty.

I'm also using Picom (Jonaburg version) and Arch Linux on the Qtile window manager and the latest stable version of Alacritty (0.10.0-2).

**Comment by smsteward** [comment]
This issue was actually resolved in #5810. In my config file on line 26, the line reads `#window` and then you have the window options below it. Uncomment that line and add `opacity: 0.8` right below it, like this:
```yaml
window:
  opacity: 0.8
```

This does the trick and correctly applies the opacity via Picom.

**Comment by idanoo** [comment]
Can confirm this works. Thanks!

**Comment by robowraith** [comment]
Can also confirm.
