### ISSUE TITLE
Wrapped URLs not detected correctly in vim

### ISSUE THREAD

**Issue by alexwhitman** [alacritty/alacritty#5816]
### System

OS: MacOS Monterey
Version: alacritty 0.10.0 (8a26dee)

### Issue
Mousing over a URL that is wrapped within vim only detects the first initial part of the URL, not the wrapped part. Screenshot to demonstrate where `foo/bar/` is not detected as part of the URL:
![Screenshot 2022-01-25 at 17 24 51](https://user-images.githubusercontent.com/422013/151028338-58aee328-06f3-4459-bf52-cbb63782579f.png)

Contrast with a wrapped URL within a shell prompt:
![Screenshot 2022-01-25 at 17 32 57](https://user-images.githubusercontent.com/422013/151028838-05ad22d0-9575-4b5b-9145-99eca563051a.png)

I've only tested this in vim but it would make sense to assume this is related to the alternate screen rather than vim specifically, but equally I could be wrong about that.

**Comment by chrisduerr** [comment]
Working as one would expect. We have no way to know about where vim wants to wrap its lines. Would require something like https://github.com/alacritty/alacritty/pull/5480 plus url-detection inside of vim.
