### ISSUE TITLE
Cannot access web cam Alacrity 0.10 (Mac OS M1)

### ISSUE THREAD

**Issue by hovnatan** [alacritty/alacritty#5819]
Get infinite loop of asking for Camera access permission on Mac OS on M1 with alacrity 0.10, works fine on alacritty 0.9

### System

OS: macOS
Version: 0.10

**Comment by chrisduerr** [comment]
You might be able to resolve this by looking into self-signing Alacritty (https://github.com/alacritty/alacritty/issues/5776#issuecomment-1015267870).

Seems to be one of the many issues with macOS' awful code signing measures.

**Comment by notDavid** [comment]
I'm having a similar issues since installing the latest version with Homebrew today, i get an infinite loop asking for "Desktop" folder permissions, "Download" folder permissions, etc. even though i've given Alacritty permissions to access "Full Disk Access".

Is this a known issue also?

**Comment by chrisduerr** [comment]
Probably the same thing.

**Comment by notDavid** [comment]
Indeed, self signing solved the issue, thank you.
