### ISSUE TITLE
Unable to store text in clipboard: NSPasteboard#writeObjects: returned false

### ISSUE THREAD

**Issue by nathom** [alacritty/alacritty#5824]
Sometimes, when I copy something from the terminal using the mouse, I get this warning on the bottom of the screen:

<img width="871" alt="image" src="https://user-images.githubusercontent.com/74019033/151430881-25d0b7b4-6891-4405-85de-3cfe8798d6d7.png">

The contents do get copied into the clipboard, so I'm not sure why this is happening. I do have multiple instances of Alacritty open, created using cmd-N, if that is relevant.

### System

OS: macOS 12.1, Apple Silicon
Version: `alacritty 0.9.0` @ 6d1a63ef28d18168ed4ca0d6a8c3413cb4621ca5

### Logs

```log
[2022-01-25 14:59:29.765895000] [WARN ] [alacritty] Unable to store text in clipboard: NSPasteboard#writeObjects: returned false
[2022-01-27 11:34:01.238477000] [WARN ] [alacritty] Unable to store text in clipboard: NSPasteboard#writeObjects: returned false
[2022-01-26 09:25:26.799327000] [WARN ] [alacritty] Unable to store text in clipboard: NSPasteboard#writeObjects: returned false
```

**Comment by chrisduerr** [comment]
Could you be a little more precise about "sometimes"? Can you force this to happen by spamming copy, or does it require some other conditions/luck/external factors?

Also have you tried the latest Alacritty version?

**Comment by nathom** [comment]
I just recompiled d1deff9fae05dec5a6a2af08dc34ed3230f68da9 and the issue is still there. After further testing, it seems to only happen when two instances are on the same tmux session, and you copy text on either one. Here is a screen recording so can have an idea of the frequency:

https://user-images.githubusercontent.com/74019033/151679097-6c01a394-d709-4ba2-8fe9-663bc01de330.mp4

**Comment by chrisduerr** [comment]
> After further testing, it seems to only happen when two instances are on the same tmux session, and you copy text on either one.

That's… interesting. Are you running multiple Alacritty windows from the same instance, or separate instances?

**Comment by nathom** [comment]
I created the second window with `cmd-N`, which seems to create a new instance. I'm not sure how to create multiple windows from the same instance.

**Comment by nathom** [comment]
I got the `CreateNewWindow` action working, and the error doesn't show up anymore. Thanks for the help!

For anyone else who has the same issue, put this in `alacritty.yml`:

```yaml
key_bindings:
  - { key : N, mods : Command, action : CreateNewWindow }
```

**Comment by listx** [comment]
> I got the `CreateNewWindow` action working, and the error doesn't show up anymore. Thanks for the help!
> 
> For anyone else who has the same issue, put this in `alacritty.yml`:
> 
> ```yaml
> key_bindings:
>   - { key : N, mods : Command, action : CreateNewWindow }
> ```

For reference, the default binding for `CMD+N` is `SpawnNewInstance`.

Using `CreateNewWindow` does avoid the logging message, but it is not ideal for me because I now have to use `CMD+Backtick` instead to cycle through Alacritty windows (instead of `CMD+Tab` as before). `CMD+Backtick` doesn't work when trying to focus on a fullscreened window (whereas `CMD+Tab` did include fullscreened windows (along with other applications) to cycle through).

Is there a way to silence the warning? As described in the original bug it appears that the copy does happen without issues, so the log message is unnecessary.

**Comment by pmalek** [comment]
I'm still experiencing this on 0.12.2 on Mac.

```
key_bindings:
  - { key : N, mods : Command, action : CreateNewWindow }
```

doesn't help.

**Comment by liamaharon** [comment]
> I got the `CreateNewWindow` action working, and the error doesn't show up anymore. Thanks for the help!
> 
> For anyone else who has the same issue, put this in `alacritty.yml`:
> 
> ```yaml
> key_bindings:
>   - { key : N, mods : Command, action : CreateNewWindow }
> ```

Anyone know how to write this in toml?

```toml
[[keyboard.bindings]]
key = "n"
mods = "Command"
action = "CreateNewWindow"
```
?

**Comment by slavaschmidt** [comment]
This issue closed erroneously, it is still present in 0.13.2, happens about 10% of the time when selecting text with a mouse.
I am using tmux but always use just a single window, so it should not be attributed to multiple windows. 

@chrisduerr

**Comment by richardkmichael** [comment]
FWIW I just encountered this on macOS 12.7.5, Alacritty 0.13.2, with tmux.  I was copying using the keyboard in tmux `copy-mode`.  I restarted Alacritty, and it was fine.  I  don't have a reproducer unfortunately.

**Comment by slavaschmidt** [comment]
@richardkmichael this issue is closed, but there is another issue with an attempt to triangulate what causes such behaviour: https://github.com/alacritty/alacritty/issues/8041
