### ISSUE TITLE
Built-in box drawing font curved line glyphs

### ISSUE THREAD

**Issue by h0adp0re** [alacritty/alacritty#5826]
Hello, since the built-in font has been in use for me for a few days now, one thing about the curved line glyphs has started to bother me more and more – they are drawing a rather strange, oblong, asymmetric curve. Is this intentional or will this be patched in future releases?

<img width="158" alt="asymmetric-curves" src="https://user-images.githubusercontent.com/11251772/151463869-d2ece0e1-7945-4e2a-940c-6d294529e25a.png">

**Comment by chrisduerr** [comment]
Is this the case for all font sizes for you? Looks like it might be an off-by-one.

Do you have any glpyh/font offsets setup? There shouldn't be any gapps between the lines.

**Comment by h0adp0re** [comment]
Ah, the font size. No, for some sizes it's a perfect curve, there aren't many of those sizes, though. Either way, my comfortable size is 21 at the moment.

I use both offsets, yes. The gaps will have to stay for me, for now. This is already recorded in another issue: #5809

**Comment by chrisduerr** [comment]
So does the patch fix this for you then? I'd assume the problem is due to offsets. Does it work properly without offsets?

**Comment by h0adp0re** [comment]
If by patch you mean disabling all offsets, no it did not. Setting a more scale-friendly font-size (16) didn't help either. The curves look exactly like before.

**Comment by chrisduerr** [comment]
I'm talking about the PR: https://github.com/alacritty/alacritty/pull/5823.

**Comment by h0adp0re** [comment]
I'm not sure how to go about testing it while the PR is still open. I can say when it's merged to master.

**Comment by chrisduerr** [comment]
Clone kchibisov's Alacritty, checkout branch, compile?

**Comment by kchibisov** [comment]
@h0adp0re try using  #5832. It should fix arcs alignment.

**Comment by h0adp0re** [comment]
I'm afraid I don't have the time to delve into compiling rust programs at the moment. I thought I could install the master branch via `brew install alacritty --HEAD` but it doesn't seem to work so I'll just leave the testing until it's released.

**Comment by chrisduerr** [comment]
Looks like the built-in font both lacks anti-aliasing and is offset on the X axis by one pixel?

**Comment by bluz71** [comment]
> Looks like the built-in font both lacks anti-aliasing and is offset on the X axis by one pixel?

Yes, and yes.

Depending on the font size, the offset issue can sometimes be inward, other times outward as seen by these two images where the only change increase in font size:

![First](https://user-images.githubusercontent.com/11382509/151690802-505d1f27-092f-4023-810d-11c284930126.png)

![Second](https://user-images.githubusercontent.com/11382509/151690803-7f61c036-9ef8-487b-a052-9d159db8bfd1.png)

If anti-aliasing is possible, that would definitely be nice for curvy bends.
