### ISSUE TITLE
[BUG][MacOS] On M1, Folder Access Permissions are Not Sticking

### ISSUE THREAD

**Issue by matallui** [alacritty/alacritty#5831]
On both my M1 MacOS laptops, I'm having this issue since upgrading to Alacritty 0.10.0, where the directory access permissions are not sticking. Therefore, whenever I try to access the Desktop/Downloads/Documents folders, I keep getting a pop-up asking for permission.
Already confirmed on the system settings that everything looks good, but the issue won't go away.

### Screenshot
<img width="573" alt="Screen Shot 2022-01-29 at 11 24 25 AM" src="https://user-images.githubusercontent.com/6828071/151672968-ab8161d5-1737-466d-b223-4b16b0d988b8.png">

### System

OS: MacOS 12.1 & 12.2
Version: alacritty 0.10.0 (8a26dee)

### Logs

```
[0.000360458s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/Users/myuser/.config/alacritty/alacritty.yml"
[0.000891291s] [DEBUG] [alacritty] Using environment locale: en_US.UTF-8
[0.019368958s] [DEBUG] [alacritty] Estimated DPR: 2
[0.019437791s] [DEBUG] [alacritty] Estimated window size: None
[0.019450291s] [DEBUG] [alacritty] Estimated cell size: 16 x 34
[0.051645583s] [INFO ] [alacritty] Device pixel ratio: 2
[0.053624958s] [INFO ] [alacritty] Initializing glyph cache...
[0.082899500s] [INFO ] [alacritty] ... finished initializing glyph cache in 0.029201208s
[0.082954916s] [INFO ] [alacritty] Cell size: 16 x 34
[0.082967791s] [INFO ] [alacritty] Padding: 0 x 0
[0.082977000s] [INFO ] [alacritty] Width: 1600, Height: 1200
[0.083799916s] [INFO ] [alacritty] PTY dimensions: 35 x 100
[0.085757583s] [INFO ] [alacritty] Initialisation complete
```

**Comment by chrisduerr** [comment]
Have you tried self-signing Alacritty?

**Comment by matallui** [comment]
> Have you tried self-signing Alacritty?

Just self-signed it with `codesign` and that fixed the problem 😃 

Can someone explain why this is and what the problem is?
Just curious to understand the root of the problem. Thanks!

**Comment by chrisduerr** [comment]
> Can someone explain why this is and what the problem is?

Pretty sure Apple is just trying to force people as much as possible to pay them for code signing.

**Comment by matallui** [comment]
That wouldn't explain why 0.9.0 works fine and I'm only having issues with 0.10.0.

**Comment by chrisduerr** [comment]
0.10.0 is a universal binary, that probably changes things.

If you think this is related to any code changes in Alacritty (which I doubt), feel free to try and bisect the commit that broke it for you though. I'd assume you'll arrive at the one introducing the universal binary in the build script.

**Comment by matallui** [comment]
Oh that's right! I forgot about that change. That makes sense then. Thanks!

**Comment by hermesjpappas** [comment]
> > Have you tried self-signing Alacritty?
> 
> Just self-signed it with `codesign` and that fixed the problem 😃
> 
> Can someone explain why this is and what the problem is? Just curious to understand the root of the problem. Thanks!

Could you please explain how you did the self-signing? I'm new to Mac OS and having the same issue. Thanks!

**Comment by kchibisov** [comment]
>Could you please explain how you did the self-signing? I'm new to Mac OS and having the same issue. Thanks!

The latest release shouldn't have this issue, so you can try `v0.10.1` version.

**Comment by hermesjpappas** [comment]
> > Could you please explain how you did the self-signing? I'm new to Mac OS and having the same issue. Thanks!
> 
> The latest release shouldn't have this issue, so you can try `v0.10.1` version.

Thanks, updated to the newest version and it seems to work. 🙂
