### ISSUE TITLE
Can't use dead keys with LANG=eo

### ISSUE THREAD

**Issue by vpzomtrrfrt** [alacritty/alacritty#5834]
On one of my systems, I'm unable to use dead keys within alacritty. Might be related to setting my locale to `eo`. When I try to use a dead key, e.g. "RAlt+x c", it just enters "c" rather than the expected "ĉ"

### System

OS: Void Linux
Version: `0.11.0-dev (f6651a99)` (also tested on 0.9.0)
DE: Sway 1.6.1
Keyboard Layout: us-colemak

### Logs
`alacritty --print-events`
[log.txt](https://github.com/alacritty/alacritty/files/7965269/log.txt)

**Comment by chrisduerr** [comment]
@kchibisov Are dead keys related to IME on Wayland? Could your IME branch help with this?

**Comment by kchibisov** [comment]
No, they are not related. They are being composed by libxkbcommon.

Please, make sure that you have compose-tables installed for your lang. Also, as you can see in the log, libxkbcommon complains about what you've passed to it (likely you haven't generated locale??) Anyway libxkbcommon doesn't like non-utf8 locales...

**Comment by vpzomtrrfrt** [comment]
eo is the name of the locale, and it _is_ meant to be UTF-8 as far as I can tell

Setting LANG to `eo.UTF-8` just throws `xkbcommon: ERROR: couldn't find a Compose file for locale "eo.UTF-8" (mapped to "eo.UTF-8")` instead

**Comment by kchibisov** [comment]
I mean those errors from libxkbcommon should have something behind them? Though, most of the time it's because locale isn't generated or has some other name. 

>Setting LANG to eo.UTF-8

Have you tried generating eo.UTF-8? Also test with `LC_ALL=eo.UTF-8`.
