### ISSUE TITLE
Screen overflowing and appearing in right side

### ISSUE THREAD

**Issue by rishadbaniya** [alacritty/alacritty#5836]
![image](https://user-images.githubusercontent.com/54678051/151692000-2fe74ad2-4a89-420a-9ce6-0bee954258f1.png)

Here, my screen overflows to the left and a small part of it is shown in the right side. It just appears randomly and goes away as soon as i resize the screen

**Comment by chrisduerr** [comment]
Can you reproduce it outside of tmux?

**Comment by rishadbaniya** [comment]
Here, outside of tmux, i could reproduce it in an app that i was working on. Running same app in alacritty and also in windows provided wsl terminal

![image](https://user-images.githubusercontent.com/54678051/151692194-23abdabf-05dd-4e47-bbb2-5f1eb5c08113.png)

**Comment by rishadbaniya** [comment]
As soon as i removed all the emojis, the application was behaving correctly. Is the problem related to font? I use "Fira Code Nerd Font"

**Comment by chrisduerr** [comment]
Oh, you're on Windows, that's probably why. Chances are you need to wait until Windows updates its PTY.
