### ISSUE TITLE
[WARN] background_opacity is deprecated; use window.opacity instead

### ISSUE THREAD

**Issue by virustesztalt** [alacritty/alacritty#5838]
hii
### System

OS: Linux-5.16.3-zen1-1-zen
Version: alacritty 0.10.0
Archcraft- BSPWM

### Logs

 /tmp/Alacritty-26401.log

![Screenshot_2022-01-30-06-38-21_3840x1080](https://user-images.githubusercontent.com/97060724/151710692-51d5d445-4f37-40db-97cc-e3949cd98982.png)

[0.000207568s] [WARN ] [alacritty_config_derive] Config warning: background_opacity is deprecated; use window.opacity instead

### Question

How can i solve this issue?

**Comment by chrisduerr** [comment]
> How can i solve this issue?

Replace old option with new option.

**Comment by DemigodKushal** [comment]
the new option doesn't make the background transparent. 
![image](https://user-images.githubusercontent.com/86103634/151751681-91126c14-d541-4018-8a00-02c2e5d54f80.png)

**Comment by wcl-xm** [comment]
it works
