### ISSUE TITLE
Alacritty keeps asking for permissions

### ISSUE THREAD

**Issue by sidmadala** [alacritty/alacritty#5840]
### System

OS: MacOS 12.0.1
Version: 0.10.0

### Expected Behavior
Alacritty asks for permissions to access folders once and remembers.

### Actual Behavior
Every keystroke in a protected MacOS folder (i.e. Desktop, Downloads, Documents) I get a prompt to give it access. This makes the terminal unusable. Pictures below.

<img width="312" alt="Screen Shot 2022-01-31 at 2 30 26 PM" src="https://user-images.githubusercontent.com/22417141/151861069-6e4cd773-643f-4715-9b4b-25238ce74dc3.png">
I have given Alacritty permission to access the folders and subfolders in question.

<img width="394" alt="Screen Shot 2022-01-31 at 2 30 35 PM" src="https://user-images.githubusercontent.com/22417141/151861071-186e9855-533b-4503-868e-1cd9f13c499d.png">
The permissions prompt appears every time I enter one of the above folders, perform any action, and even on each keystoke.

**Comment by dongcarl** [comment]
I can reproduce this problem. This is because Alacritty on M1 Macs there's a more stringent codesigning requirement, and I don't think the released Alacritty.app is signed properly:

```
$ codesign -d -vvv -r - /Applications/Alacritty.app 
Executable=/Applications/Alacritty.app/Contents/MacOS/alacritty
Identifier=alacritty-4588e9d6612605a7
Format=app bundle with Mach-O universal (x86_64 arm64)
CodeDirectory v=20400 size=30419 flags=0x20002(adhoc,linker-signed) hashes=947+0 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha256=dee73bbb5c1966563ad32013da53edf3d64995ce
CandidateCDHashFull sha256=dee73bbb5c1966563ad32013da53edf3d64995ce9a1c6497e2448129cb832527
Hash choices=sha256
CMSDigest=dee73bbb5c1966563ad32013da53edf3d64995ce9a1c6497e2448129cb832527
CMSDigestType=2
CDHash=dee73bbb5c1966563ad32013da53edf3d64995ce
Signature=adhoc
Info.plist=not bound
TeamIdentifier=not set
Sealed Resources=none
/Applications/Alacritty.app: code object is not signed at all
```

**Comment by chrisduerr** [comment]
Could someone with an M1 try [Alacritty.app.tar.gz](https://github.com/alacritty/alacritty/files/7977854/Alacritty.app.tar.gz)? This is signed locally with my macbook, if the M1 accepts unverified signatures we can at least add that to our makefile and have things self-signed by CI then.

**Comment by blandir** [comment]
I had the same issues on MacOS 12.2 and just tried your build, @chrisduerr. It works fine. MacOS asks once for the permission and afterwards access is allowed as expected.

**Comment by dongcarl** [comment]
> Could someone with an M1 try [Alacritty.app.tar.gz](https://github.com/alacritty/alacritty/files/7977854/Alacritty.app.tar.gz)? This is signed locally with my macbook, if the M1 accepts unverified signatures we can at least add that to our makefile and have things self-signed by CI then.

Looks a little better...
```
$ codesign -d -vvv -r - ~/Downloads/Alacritty.app
Executable=/Users/dongcarl/Downloads/Alacritty.app/Contents/MacOS/alacritty
Identifier=io.alacritty
Format=app bundle with Mach-O universal (x86_64 arm64)
CodeDirectory v=20400 size=29733 flags=0x2(adhoc) hashes=923+3 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha1=daa279e35fca673607443f3ce9fda99748bc8b7d
CandidateCDHashFull sha1=daa279e35fca673607443f3ce9fda99748bc8b7d
CandidateCDHash sha256=ddb15415c4b6ca95a6dabb601eb38fc70231be34
CandidateCDHashFull sha256=ddb15415c4b6ca95a6dabb601eb38fc70231be34f521360c2df287fa75bbc2fb
Hash choices=sha1,sha256
CMSDigest=e907f8d85e6b175442bb9937606f5f33a9d015c247ab602de1a34c3796334ba9
CMSDigestType=2
CDHash=ddb15415c4b6ca95a6dabb601eb38fc70231be34
Signature=adhoc
Info.plist entries=25
TeamIdentifier=not set
Sealed Resources version=2 rules=13 files=8
# designated => cdhash H"daa279e35fca673607443f3ce9fda99748bc8b7d" or cdhash H"ddb15415c4b6ca95a6dabb601eb38fc70231be34" or cdhash H"8b0e2825aea4c4e1c52eefe0560051d69aada92c" or cdhash H"a3b012e1cdf37f2e0e61ea1e761a9a677dbd529b"
```

**Comment by chrisduerr** [comment]
> Looks a little better...

Did you actually run that on M1 without any issues, or did you just check the codesign results?

**Comment by kim0** [comment]
@chrisduerr .. I had the same exact problem. I used the version you attached, and it does seem to suppress the repeated message about accessing files. I was chatting with Apple support wrt this and ofc they were clueless. Thank you!!

**Comment by paulnikolaus-schuberth** [comment]
> Could someone with an M1 try [Alacritty.app.tar.gz](https://github.com/alacritty/alacritty/files/7977854/Alacritty.app.tar.gz)? This is signed locally with my macbook, if the M1 accepts unverified signatures we can at least add that to our makefile and have things self-signed by CI then.

This seems to solve the issue 👍  The permission are now remembered!

**Comment by Joorem** [comment]
I had this exact issue and signed Alacritty myself:

1. Generate a certificate for code signing: follow this [documentation from Apple](https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html#//apple_ref/doc/uid/TP40005929-CH4-SW1)
2. Sign the Alacrity binary: `codesign -s <identity> /Applications/Alacritty.app/Contents/MacOS/alacritty` (replace `<identity>` with the one provided in the certificate.

Since everything works as intended :)

**Comment by AHaliq** [comment]
this worked for me too without generating the signature
```
sudo codesign --force --deep --sign - /Applications/Alacritty.app
```

**Comment by sonlexqt** [comment]
I had the exact same issue. Running `codesign` didn't help (it returns this error `/Applications/Alacritty.app: resource fork, Finder information, or similar detritus not allowed`)
I downloaded the [v0.10.1](https://github.com/alacritty/alacritty/releases/tag/v0.10.1) version and everything is working now!

**Comment by JeDTr** [comment]
<img width="662" alt="image" src="https://user-images.githubusercontent.com/27817016/169630105-354e1ef7-e558-4919-9103-f2f45302988a.png">
Allow `Full Disk Access` for `Alacritty` work for me

**Comment by donuts-are-good** [comment]
> <img alt="image" width="662" src="https://user-images.githubusercontent.com/27817016/169630105-354e1ef7-e558-4919-9103-f2f45302988a.png">
> 
> Allow `Full Disk Access` for `Alacritty` work for me

This did not change anything for me

**Comment by on3iro** [comment]
> > <img alt="image" width="662" src="https://user-images.githubusercontent.com/27817016/169630105-354e1ef7-e558-4919-9103-f2f45302988a.png">
> > Allow `Full Disk Access` for `Alacritty` work for me
> 
> This did not change anything for me

same here :/

**Comment by on3iro** [comment]
> I had the exact same issue. Running `codesign` didn't help (it returns this error `/Applications/Alacritty.app: resource fork, Finder information, or similar detritus not allowed`) I downloaded the [v0.10.1](https://github.com/alacritty/alacritty/releases/tag/v0.10.1) version and everything is working now!

Apparently downloading the v0.10.1 from the github releases page seems to have worked for me. (shouldn't this be the same build as the one from the alacritty website 🤔 ?)

**Comment by carterchannui** [comment]
> > I had the exact same issue. Running `codesign` didn't help (it returns this error `/Applications/Alacritty.app: resource fork, Finder information, or similar detritus not allowed`) I downloaded the [v0.10.1](https://github.com/alacritty/alacritty/releases/tag/v0.10.1) version and everything is working now!
> 
> Apparently downloading the v0.10.1 from the github releases page seems to have worked for me. (shouldn't this be the same build as the one from the alacritty website 🤔 ?)

This worked for me on M1. Just had to install v0.10.1 then re-enable full disk access.

**Comment by jpgorman** [comment]
> I had this exact issue and signed Alacritty myself:
> 
> 1. Generate a certificate for code signing: follow this [documentation from Apple](https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html#//apple_ref/doc/uid/TP40005929-CH4-SW1)
> 2. Sign the Alacrity binary: `codesign -s <identity> /Applications/Alacritty.app/Contents/MacOS/alacritty` (replace `<identity>` with the one provided in the certificate.
> 
> Since everything works as intended :)

This is the way
