### ISSUE TITLE
Watch imported config files for changes and reload

### ISSUE THREAD

**Issue by felipesere** [alacritty/alacritty#5852]
It would be great if alacritty not only watched the default config file paths for change events, 
but also the the ones that are imported.

The use-case I have is that my main Alacritty configuration file is in a `git` repo, but I have split out a separate
file that just contains

```yaml
font:
  size: 12
```

and imported it at the top of my config. 
I then have a script that lets me change the font size by editing that file.
Changes to that file don't trigger a reload though.
Opening the main config and simply saving it without changes does trigger though.
I've tried adding a `touch ~/.config/alacritty/alacritty.yaml` at the bottom of the script but that has no effect.

**Comment by chrisduerr** [comment]
Have you tried this? We should watch imported config files too iirc. If editing the original config file doesn't work, it sounds like live config isn't working at all?

**Comment by felipesere** [comment]
I can confirm that saving the imported file does not trigger a reload, but simply opening and saving the main config file reloads as expected. 

I can dig into the source when I’m back on a laptop 😃

**Comment by felipesere** [comment]
Yeah, I double checked and my setup does contain symlinks:
`~/.config/alacritty/alacritty.yml` links to `~/.dotfiles/alacritty/alacritty.yml`
That yaml contains a reference to `~/.alacritty-font-size.yml`.

If I replace the symlink with a proper file it works as expected.

Is there a limitation on what symlinks can do at the moment?

**Comment by felipesere** [comment]
I've changed my setup to do a hard link instead of soft-links for my Alacritty config and it all works as expected.

Sorry for the nuisance!

**Comment by jakubkaczor** [comment]
Instead of using hard links in place of symbolic links one can use `touch` with `--no-dereference` option, `-h` for short. This will “touch” the symlink instead of the target file. The full command is `touch --no-dereference ~/.config/alacritty.toml`.
