### ISSUE TITLE
Undercurls too thick.

### ISSUE THREAD

**Issue by bluz71** [alacritty/alacritty#5873]
Hello Alacritty team,

I have been following the development of undercurls and I am very pleased to see them merged in. Well done.

I followed #5837 and about 10 days [I commented, in the PR,](https://github.com/alacritty/alacritty/pull/5837#issuecomment-1025443843)  how happy I was with the actual rendered undercurls on my system as seen in this image (look great to my eye):

![undercurl1](https://user-images.githubusercontent.com/11382509/153320903-28dc6928-fb17-4774-9dd2-cfe0e5ec3bb9.png)

I just built master and undercurls are now much thicker (and too strong imo), compare above with this:

![undercurl2](https://user-images.githubusercontent.com/11382509/153320993-ad6fdf85-ab89-4c0d-8f97-359df9172d60.png)

To compare again, here is what underlines look like:

![Underline](https://user-images.githubusercontent.com/11382509/153321028-255180bf-cefd-497c-80f6-fff1c2892dc1.png)

There was a definite rendering change to undercurls between image 1 and 2.

Also notice that image 1 has downward curling ends whilst image 2 (master) was upward angling curls at the ends. Eye of the beholder, I can go either way.

But is there anything that can be done about the thickness? Thinning it out a bit?

Best regards.

**Comment by kchibisov** [comment]
We did that on purpose, since undercurls are generally blurry. If the majority will think that it's too thick, we can make them thinner. Just by looking at color of you undercurls you may notice that it actually the same as text as it should and has the color of underline.

Though, maybe just making it slightly thinner is an option.

**Comment by kchibisov** [comment]
I'll just leave it here so there could be a vote for that (top, middle, bottom) on the following pictures.

![picture](https://user-images.githubusercontent.com/27620401/153324940-a4070c07-299c-42ca-b82e-933243bda6e4.png)

![picture](https://user-images.githubusercontent.com/27620401/153324979-3f46b1f8-60b6-408a-9584-06165f136628.png)

I'd might middle, but I'm not sure.

**Comment by bluz71** [comment]
For the above, middle or top. Not the bottom, looks to thick. It looks like a bolded undercurl.

> We did that on purpose, since undercurls are generally blurry.

It is a fine balance, in some ways it is an art-form to select thickness/thinness that satisfies (as we all experienced with native box-drawing chars). It takes a couple iterations.

I don't mind bluriness since GNOME Terminal (which has had undercurls for a long-time, 2012 I think) is a tad blurry:

![gterm_undercurl](https://user-images.githubusercontent.com/11382509/153330592-cd896ac0-0425-4788-8e3e-5e5f7096a473.png)

Compared with Alacritty master:


![undercurl2](https://user-images.githubusercontent.com/11382509/153330685-a4f64214-a458-4a26-85be-68fc266592eb.png)

Undercurls are shouty imo. I vote (if there is such a thing) to thin them out, like the middle images above.

Cheers.

**Comment by bluz71** [comment]
Just tested the newest update, looks superb.

Before (too thick imo):

![undercurl2](https://user-images.githubusercontent.com/11382509/153517269-695ea459-e8a2-4949-b197-5a68a6341067.png)

Newest master (just right):

![undercurl_new](https://user-images.githubusercontent.com/11382509/153517323-771acebd-b9b7-4c0e-a93e-7e9165dffc52.png)

Thank you very much @kchibisov and @chrisduerr.
