### ISSUE TITLE
Mouse text selection issue with multiple windows

### ISSUE THREAD

**Issue by zaps** [alacritty/alacritty#5876]
## Overview

When at least 2 windows are open, text selection with mouse does not work properly.

### Steps to Reproduce

1. Open Alacritty
2. Put some text on the screen
3. Open a new window via `CreateNewWindow` (I have it bound to Command-N)
4. Put some text in the new window
5. Select any section of text with the mouse

### Expected Behavior

The text is selected by the mouse at the location of the cursor

### Actual Behavior

The text 2 lines above the location of the cursor is selected

### Workaround

Don't use multiple windows

### Demo

![alacritty-multi--window-mouse-issue](https://user-images.githubusercontent.com/2954949/153506908-2ddeb235-6f69-40bd-af71-b5bb0a77af78.gif)

### System

OS: macOS Big Sur 11.6.3 (20G415)
Version: alacritty 0.10.0 (8a26dee)

### Logs

Crashes: n/a
Font/Terminal size: [`alacritty -vv`](https://github.com/alacritty/alacritty/files/8044702/alacritty-vv.log)
Keyboard and bindings: [`alacritty --print-events`](https://github.com/alacritty/alacritty/files/8044709/alacritty-print-events.log)

**Comment by kchibisov** [comment]
I'd assume it works when it's not tabbed?

**Comment by zaps** [comment]
> I'd assume it works when it's not tabbed? I mean when you have multiple windows, but you don't tab them.

Correct—multiple non-tabbed windows do not have the issue.

**Comment by chrisduerr** [comment]
Which macOS version is this?

**Comment by zaps** [comment]
> Which macOS version is this?

Big Sur 11.6.3 (20G415) on an Intel Mac (2019)

**Comment by chrisduerr** [comment]
Just tested this and the top of the window is also cut-off. So it's indeed pretty broken.

**Comment by chrisduerr** [comment]
At least for tabbed windows a workaround seems to be to resize the window after creating a new tab. At least that worked for me.

**Comment by zaps** [comment]
> At least for tabbed windows a workaround seems to be to resize the window after creating a new tab. 

Can confirm—works for me too

**Comment by zaps** [comment]
Weirdly, on my M1 Mac (Monterey, 12.1), `CreateNewWindow`  actually creates a _new window_, and not a new tab in the same window. Not sure if this is a different issue.

**Comment by chrisduerr** [comment]
> Weirdly, on my M1 Mac (Monterey, 12.1), CreateNewWindow actually creates a new window, and not a new tab in the same window. Not sure if this is a different issue.

It depends on a macOS setting and the existence of decorations if a new tab or window will be opened.

**Comment by kchibisov** [comment]
Sorry, seems like I forgot to link to upstream. I've described whats needs doing here https://github.com/rust-windowing/winit/issues/2191

**Comment by kchibisov** [comment]
So if you feel like fixing it, it's a matter of plumbing it in winit. Should be that hard if there's desire to fix it on macOS.

**Comment by sshock** [comment]
Thank @kchibisov.  I'm new to rust and am unfamiliar with winit, but I may give it a try if no one beats me to it.

**Comment by chrisduerr** [comment]
If you need help, I'm sure there'll be some people around on the #alacritty or #winit IRC (winit is also a Matrix room) to answer potential question.

**Comment by sshock** [comment]
Upstream fix: https://github.com/rust-windowing/winit/pull/2239

**Comment by chrisduerr** [comment]
Thanks for letting us know. Should be in Alacritty with the next winit version then.

**Comment by Programatic** [comment]
I would like to add, that this mouse text select issue occurs with me on my Arch Linux machine running Sway. I haven't spent time seeing if this is entirely related, but I will update after the next version comes out to see if this fixes it as well. Thanks for all the hard work y'all :)
