### ISSUE TITLE
Fish shell enable/disable pair control characters printed wrong

### ISSUE THREAD

**Issue by ryancerium** [alacritty/alacritty#5878]
Fish is printing some escape code characters around application output. Specifically, a `l` character tends to come around the beginning of the output and an `h` character tends to come around the last line of output. The problem does not occur in Bash. This also occurs if I use the Lucida Sans Typewriter font, which is not a nerd font.

These examples are all in the `~/temp` directory that contains 3 files imaginatively named `1`, `2`, and `3`. You can see the `l` as part of the `ls` command and the `h` as part of the file `1` name:

![image](https://user-images.githubusercontent.com/1735570/153515740-bebf1533-556c-4dcd-907f-b8c601aa4675.png)

Resizing the Alacritty window redraws the lines correctly and removes the stray characters. The Fish folks say that this is likely an enable/disable pair of escape sequences.

### System

OS: Windows (WSL 1, Ubuntu 18.04, Fish Shell 3.3.1)
Version: 0.10.0 of Alacritty

### Logs

~Crashes: STDERR, STDOUT~
Font/Terminal size: Lucida Sans Typewriter and Go Mono Nerd Font
~Keyboard and bindings: `alacritty --print-events`~

### Related

* https://github.com/fish-shell/fish-shell/issues/8714 (Duplicate of 8240)
* https://github.com/fish-shell/fish-shell/issues/8240
  * https://github.com/fish-shell/fish-shell/issues/8240#issuecomment-903064571
* https://github.com/alacritty/alacritty/issues/5333
* https://github.com/microsoft/terminal/issues/395

**Comment by chrisduerr** [comment]
> OS: Windows (WSL 1, Ubuntu 18.04, Fish Shell 3.3.1)

Most likely a ConPTY issue. Unless you can reproduce this on macOS/Linux, there's not much Alacritty can do.
