### ISSUE TITLE
Ligatures dont working

### ISSUE THREAD

**Issue by AlePon123** [alacritty/alacritty#5886]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux/
Version: alacritty 0.8.0-dev (3ed0430)
Linux/BSD: X11/  WM

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: JetBrains Mono NerdFont / 13
Keyboard and bindings: `alacritty --print-events`
I have this code but ligatures dont working, i tried different fonts but ligatures still dont working
 ![2022-02-12_18-57](https://user-images.githubusercontent.com/72556979/153718385-e01c4119-6a5d-4730-b66b-4adbaf52a740.png)

**Comment by arpangreat** [comment]
Sorry but alacritty doesn't support ligatures

**Comment by AlePon123** [comment]
> Sorry but alacritty doesn't support ligatures

ohh my bad, sry
