### ISSUE TITLE
Cursor opacity

### ISSUE THREAD

**Issue by RomanVolkov** [alacritty/alacritty#5888]
Is it possible to configure Box cursor opacity when it inverts color? I want to reduce contract a little of cursor itself

**Comment by chrisduerr** [comment]
Have you considered just changing the cursor color?

**Comment by RomanVolkov** [comment]
Sorry for late reply. But how it will be connected with cursor color inversion?

**Comment by chrisduerr** [comment]
I'm saying to use a fixed cursor color instead of inversion?
