### ISSUE TITLE
Debian 11, i3 - Cargo install fails

### ISSUE THREAD

**Issue by DiggsAsura** [alacritty/alacritty#5895]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Debian 11
Version: Cannot install via cargo
Linux/BSD: Xorg, i3

### Logs

Trying to install via cargo. Have installed all the dependencies listed on this page. I'm sorry if this is a very noob issue. 

Looks smooth for a while, but then: 

     Running `rustc --crate-name build_script_main /home/kenneth/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.10.1/build/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -Cembed-bitcode=no --cfg 'feature="render"' --cfg 'feature="shape"' --cfg 'feature="thread"' --cfg 'feature="xfixes"' -C metadata=270141f2f2754360 -C extra-filename=-270141f2f2754360 --out-dir /tmp/cargo-installVq7w88/release/build/xcb-270141f2f2754360 -L dependency=/tmp/cargo-installVq7w88/release/deps --extern libc=/tmp/cargo-installVq7w88/release/deps/liblibc-430ae4bfc9b00dfb.rlib --extern quick_xml=/tmp/cargo-installVq7w88/release/deps/libquick_xml-3fae9ae1654e1cb0.rlib --cap-lints allow`
error[E0658]: or-patterns syntax is experimental
  --> /home/kenneth/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.10.1/build/parse.rs:68:16
   |
68 |             Ok(XmlEv::Text(e) | XmlEv::CData(e)) => {
   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #54883 <https://github.com/rust-lang/rust/issues/54883> for more information

error[E0658]: or-patterns syntax is experimental
  --> /home/kenneth/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.10.1/build/parse.rs:79:16
   |
79 |             Ok(XmlEv::Text(e) | XmlEv::CData(e)) => {
   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #54883 <https://github.com/rust-lang/rust/issues/54883> for more information

error[E0658]: or-patterns syntax is experimental
   --> /home/kenneth/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.10.1/build/parse.rs:121:16
    |
121 |             Ok(XmlEv::Start(e) | XmlEv::Empty(e)) => Ok(Vec::from(e.name())),
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #54883 <https://github.com/rust-lang/rust/issues/54883> for more information

error[E0658]: or-patterns syntax is experimental
   --> /home/kenneth/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.10.1/build/parse.rs:229:20
    |
229 |                 Ok(XmlEv::Text(_) | XmlEv::CData(_)) => {
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #54883 <https://github.com/rust-lang/rust/issues/54883> for more information

error[E0658]: or-patterns syntax is experimental
   --> /home/kenneth/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.10.1/build/parse.rs:312:16
    |
312 |             Ok(XmlEv::Start(ref e) | XmlEv::Empty(ref e)) => {
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #54883 <https://github.com/rust-lang/rust/issues/54883> for more information

error[E0658]: or-patterns syntax is experimental
   --> /home/kenneth/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.10.1/build/parse.rs:383:20
    |
383 |                 Ok(XmlEv::Empty(ref e) | XmlEv::Start(ref e)) => match e.name() {
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #54883 <https://github.com/rust-lang/rust/issues/54883> for more information

error: aborting due to 6 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `xcb`.

Caused by:
  process didn't exit successfully: `rustc --crate-name build_script_main /home/kenneth/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-0.10.1/build/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -Cembed-bitcode=no --cfg 'feature="render"' --cfg 'feature="shape"' --cfg 'feature="thread"' --cfg 'feature="xfixes"' -C metadata=270141f2f2754360 -C extra-filename=-270141f2f2754360 --out-dir /tmp/cargo-installVq7w88/release/build/xcb-270141f2f2754360 -L dependency=/tmp/cargo-installVq7w88/release/deps --extern libc=/tmp/cargo-installVq7w88/release/deps/liblibc-430ae4bfc9b00dfb.rlib --extern quick_xml=/tmp/cargo-installVq7w88/release/deps/libquick_xml-3fae9ae1654e1cb0.rlib --cap-lints allow` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `alacritty v0.10.0`, intermediate artifacts can be found at `/tmp/cargo-installVq7w88`

Caused by:
  build failed

**Comment by chrisduerr** [comment]
See minimum Rust version requirement.
