### ISSUE TITLE
Alacritty on mac hide if pressing CMD + H , prior 0.1 its not happening...

### ISSUE THREAD

**Issue by dartacean** [alacritty/alacritty#5903]
I tried to use latest 0.10 
cmd + [hjkl] i use it on tmux pane navigation and configure it on alacritty.yaml

after updating to 0.10 it cmd[jkl] still works and cmd + h makes it hide
which is the default behaviour of macos apps 
hope this can be fixed back to old behaviour ..

**Comment by chrisduerr** [comment]
You can add a binding to your Alacritty config to not hide it.

**Comment by dartacean** [comment]
this are all in my alacritty config

```
  - { key: H,     mods: Command,       chars: "\x01\x68" } # Move Pane Left
  - { key: J,     mods: Command,       chars: "\x01\x6a" } # Move Pane Down
  - { key: K,     mods: Command,       chars: "\x01\x6b" } # Move Pane Up
  - { key: L,     mods: Command,       chars: "\x01\x6c" } # Move Pane Right

```
I already have it set up to bind with tmux....
Do you have guide on this, or any other hint?

**Comment by dartacean** [comment]
Seems like theres no way to fix this , ive already tried using other  commands 
```
  - { key: H,     mods: Command,       action: IncreaseFontSize } 
```
Just to rebind it, its impossible

**Comment by unphased** [comment]
Tip for you: 

- Look in the macOS menubar for the Alacritty app. See the entry `Hide alacritty` bound to `⌘ H`. 
Now you have what you need to use system prefs to override this default os-wide binding.
- Go to System Prefs -> Keyboard -> Shortcuts
- App Shortcuts on left panel
- Click the `+` button
- Choose the Alacritty app 
- Enter exactly `Hide alacritty` as noted above (note Alacritty is not capitalized here)
- Enter a replacement binding. I used `⌃⌥⌘ H`
- Once you do this you can see clicking in the Alacritty menu bar that the offending keybind has now been overridden to the one you just set, and all your Command+H binds start to work again in alacritty immediately.

**Comment by piersolenski** [comment]
Is there any reason the previous behaviour was deprecated?

**Comment by unphased** [comment]
Probably because of an upstream window library change and I might assume that there's no easy way to restore the old behavior without custom work or pinning to a really old version of the lib. There's no such issue in alacritty in Linux and the macOS workaround is posted above. I agree the old behavior would be a lot less manual work to get this to a working state.
