### ISSUE TITLE
Always use IPC to create new window

### ISSUE THREAD

**Issue by wooparadog** [alacritty/alacritty#5906]
Hi,

I'm trying out the new(or not?) IPC feature and found it a little bit harder to use than `urxvt`.

In alacritty, if I want to create a new window:

1. Need to start a alacritty instance first.
2. Call `alacritty msg create-window` for new window.

In urxvt:

1. Call `urxvtc`

What's under the hood is that `urxvtc` will try to connect to an existing `urxvtd`, if not exists, it'll start a new `urxvtd` and
then let `urxvtd` create the new window.

I can write a script to mimic the same behavior for alacritty, but thought it's worth working on to improve IPC experience.

**Comment by kchibisov** [comment]
I don't see a reason to do so, if wrapping alacritty in a script(pretty simple one) achieves the behavior you're talking about. And since alacritty can't run headless I don't see a reason for client server binaries.

**Comment by chrysn** [comment]
Please revisit. Sure it's a just a script, but it's one that everyone who runs alacritty in create-window mode runs into, and doing it *properly* is not trivial as it needs knowledge of the socket name, plus it is subject to ToC/ToU errors that would be trivial to avoid in-process.
