### ISSUE TITLE
In version 10.1, True color in tmux in neovim 

### ISSUE THREAD

**Issue by sittim** [alacritty/alacritty#5907]
For Mac OS, the alacritty was upgraded to 10.1 and true color stopped working in Neovim 6.1 and Tmux 3.2a.  The tmux configuration was not changed and nothing else was changed.

### System

OS: macOS V11.6 "Big Sur"
Version: alacritty 0.10.1 (2844606)

### Tmux config
```
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
```
### Neovim
```
set termguicolors
```

**Comment by sittim** [comment]
I uninstalled the homebrew installation of the terminal and downloaded the `dmg` file and now it seems to work fine.

**Comment by oiwn** [comment]
hm, have same issue with homebrew installed version of alacritty.
