### ISSUE TITLE
How to copy-paste whole lines?

### ISSUE THREAD

**Issue by tjatjagithub** [alacritty/alacritty#5909]
I need to copy-paste while lines incl. the <Enter> to execute the line ....
Is this possible with Alacritty?

I cannot find nothing in the documentation or the strangely non-standard config file.

Many thanks!

For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux/BSD/macOS/Windows
Version: `alacritty --version` output
Linux/BSD: X11/Wayland, DE or Compositor and WM

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by tjatjagithub** [comment]
Also, for example in PuTTY, you can select a string with the mouse and then just move a bit to the right to have the whole line including the <Enter> selected and ready to paste.

**Comment by chrisduerr** [comment]
Triple-click, like most other applications.

**Comment by tjatjagithub** [comment]
No, this selects the whole line.

**Comment by tjatjagithub** [comment]
Can we please stop closing things without any communication?
Strange behavior!

**Comment by tjatjagithub** [comment]
I want to copy a command of course and the whole line, which includes a prompt:

tja@mini:~$ date
Wed Feb 23 20:53:25 CET 2022

So, copy the "date" command incl. the <Enter> so that paste the line executes the command:

tja@mini:~$ date
Wed Feb 23 20:53:27 CET 2022
tja@mini:~$ date
Wed Feb 23 20:53:28 CET 2022
tja@mini:~$ date
Wed Feb 23 20:53:29 CET 2022

That does not seem to be possible, while all other terminals seem to allow for this.

**Comment by chrisduerr** [comment]
Select the whole line, then copy it. I don't see what you're on about.

**Comment by tjatjagithub** [comment]
The whole line contains the prompt, as I wrote above!
So it is not possible to copy a command in one windows and paste it for other sessions or servers.

PuTTY is a good example for this feature - just select the command and go a bit to the right and the whole rest of the line will be marked as selected, displaying that the Enter key (for Carriage Return and Newline) will be copied too and actually copy and execute the command in the other windows.

**Comment by tjatjagithub** [comment]
Beside copy-and-paste of commands, I also use this to copy-and-paste passwords into login-fields, including the Enter key to actually enter the password.
