### ISSUE TITLE
A request of changing a misleading warning

### ISSUE THREAD

**Issue by Zszywek** [alacritty/alacritty#5917]
I had a warning while opening the terminal emulator saying:
`Config warning: background_opacity is deprecated; use window.opacity instead`
I had found this message as very misleading as I was trying to change the `background_opacity` element to `window.opacity`, where in fact I should have just changed it to the `opacity` in the `window` section. I would advise to change the info to something like:
`Config warning: background_opacity is deprecated; use opacity in the window section instead`

**Comment by chrisduerr** [comment]
That's significantly more verbose and inconsistent with all our other documentation though. I'd assume that people are familiar with the yaml syntax and hierarchical notation like this.

If you can't figure out what `window.opacity` is, how are you going to figure out where the `window` section is?
