### ISSUE TITLE
startup_mode: Maximized not working

### ISSUE THREAD

**Issue by Akanksh12** [alacritty/alacritty#5920]
### System

OS: Arch Linux
Version: alacritty 0.10.1 (2844606d)
Linux: Gnome 41.4

alacritty doesn't open in maximized mode although specified in alacritty.yml

[alacritty.yml](https://gitlab.com/arc_07/dotfiles/-/blob/master/.config/alacritty.yml)

**Comment by chrisduerr** [comment]
Your entire config is commented out. You need to uncomment the entry you want to use **and all parent fields**.

**Comment by Akanksh12** [comment]
I got a error when I tried un-commenting the line. All I had to do was also uncomment the parent field. thank you
