### ISSUE TITLE
Set title bar color to match background color (Windows)

### ISSUE THREAD

**Issue by joestrkr** [alacritty/alacritty#5921]
I would like to style the titlebar so that the color matches the background of the terminal. Using the dark theme from the OS, the title bar is black. Interestingly, the title bar uses the background color if the window is not in focus. That's basically how I would want it to look like when in foucs. 

In focus:
![image](https://user-images.githubusercontent.com/45912806/155971536-c3a13910-a87c-4b6e-8967-7c38a5e69159.png)

Not in focus:
![image](https://user-images.githubusercontent.com/45912806/155971575-18744ff1-ad13-4e96-824e-bfe11344a1cf.png)

### System

OS: Windows 10
Version: 0.10.1

**Comment by chrisduerr** [comment]
Alacritty does not concern itself with server-side decorations and we do not bother with providing nice looking client-side decorations. I'd assume this would require implementing client-side decorations on Windows.
