### ISSUE TITLE
Unable to override Command+H "Hide alacritty" key binding on macOS

### ISSUE THREAD

**Issue by phodge** [alacritty/alacritty#5923]
I already have important functions bound to the `Command+H` key combination in tmux/vim, but now that I have upgrade to the latest Alacritty I am unable to use them as it is impossible to prevent `Command+H` performing any action other than hiding the window.

I have tried the following key_bindings, to no avail:

    key_bindings:
      - { key: H, mods: Command, action: "None" }
      - { key: H, mods: Command, action: "ReceiveChar" }
      - { key: H, mods: Command, chars: "\eh" }

This is so inconvenient that I am unable to use this version of Alacritty and will have to manually install the version older than when the `Hide alacritty` feature was added.

### System

OS: macOS Catalina 10.15.7
Version: alacritty 0.10.1 (2844606)

### Logs

Keyboard and bindings: [See this gist](https://gist.github.com/phodge/c42c42253980abdc3efa0efba3082fc7)

**Comment by chrisduerr** [comment]
Do the bindings work in general? So do they work when you remove `Command` for example?

**Comment by chrisduerr** [comment]
Unfortunately I don't have any macOS machine to verify this, but if you override the command properly the binding should not be triggered anymore (this also works just fine for me for other bindings). Does it work for you when compiling from source and manually removing the binding in `alacritty/src/config/bindings.rs`?

**Comment by chrisduerr** [comment]
May I ask why you're binding `Command` to anything @phodge?

**Comment by phodge** [comment]
> ... if you override the command properly the binding should not be triggered anymore ...

I removed the keybinding from `alacritty/src/config/bindings.rs` but it the key combination still persists. I wonder if the key combination is being intercepted by the operating system or the ui window, before it gets to Alacritty.

> May I ask why you're binding Command to anything @phodge?

@chrisduerr: it's the most ergonomic modifier to interact with, also this and most of my other `Command-` mappings use `Alt-` instead on Ubuntu since that is the same physical key on the keyboard.

**Comment by kchibisov** [comment]
@phodge yes it does, look at comment I've linked.

**Comment by phodge** [comment]
@kchibisov: Thank you for the link, I wasn't sure what your comment meant at first but now I see there's a better explanation on the related issue. The workaround on that thread is OK for now.

FYI using `git bisect` I was able to trace the bug down to commit 4c6a763850a5dec0fa34d15e356dcba19875690a, which is what you would expect after reading #5346.

@chrisduerr: I'm happy for you to either close this issue or we can leave it open until this is fixed upstream. Leaving it open may prevent more people opening duplicates.

**Comment by chrisduerr** [comment]
> @chrisduerr: it's the most ergonomic modifier to interact with, also this and most of my other Command- mappings use Alt- instead on Ubuntu since that is the same physical key on the keyboard.

The equivalent of Alt is Option though, which is why this kind of remapping will always create issues.

> I'm happy for you to either close this issue or we can leave it open until this is fixed upstream

I'm not sure there's going to be a fix upstream, but you're welcome to submit one.

**Comment by unphased** [comment]
Sorry I've only been skimming, but thank you all for the breadcrumbs to the workaround of assigning a replacement shortcut for the same action in macOS which is very helpful to bring Cmd+H back.

I suppose the changed behavior is probably definitely not a bug upstream; it would appear to be a step in the right direction to bring the window handling more in line with the OS convention, for which it is true that Cmd+H in almost all other apps will -- and should -- hide them. 

It is merely an edge case of the terminal which has stronger keybinding needs than most any other type of application. The existence of this workaround is a complete godsend though.
