### ISSUE TITLE
Alacritty's cursor flickers for a few seconds then stops flickering when URxvt doesn't do that at all

### ISSUE THREAD

**Issue by inkryougan** [alacritty/alacritty#5924]
Here's what I'm talking about: https://imgur.com/a/wwHdG0e

The first video is Alacritty's. The second one is URxvt's. Why does Alacritty flicker like that? I haven't been able to solve it, which is why I'm using URxvt which seems much smoother. I use BSPWM as my window manager.

Thanks in advance.

**Comment by inkryougan** [comment]
Yes. picom. I use the glx backend because xrender causes screen tearing.

**Comment by chrisduerr** [comment]
Seems like it might just be drawing the shell prompt? I'd assume this only happens when you start Alacritty?

**Comment by inkryougan** [comment]
> Seems like it might just be drawing the shell prompt? I'd assume this only happens when you start Alacritty?

Yup. Only when I start it. I changed my shell to bash, and that worked. Don't know why zsh was behaving weirdly.
