### ISSUE TITLE
New graphical bug on x86_64 macOS 12.2.1

### ISSUE THREAD

**Issue by jbsolomon-fw** [alacritty/alacritty#5928]
After installing from the latest commit (d8113dc), the Go Mono font I'm using renders incorrectly:

![image](https://i.imgur.com/r8SrAb4.png)

### System

OS: macOS 12.2.1 intel x64
Version: `alacritty 0.11.0-dev (d8113dc)`

**Comment by kchibisov** [comment]
Could you bisect?

**Comment by jbsolomon-fw** [comment]
@kchibisov -- I always rebuild daily 😄 using 1880522 fixed it.

**Comment by kchibisov** [comment]
The latest commit is unrelated to text rendering at all. To even trigger the changed code you need to use dashed lines.

**Comment by jbsolomon-fw** [comment]
I'll do a double sanity-check

**Comment by kchibisov** [comment]
The commit about gles2 renderer is related though. So this could be the one that broke.

**Comment by jbsolomon-fw** [comment]
well, I can't seem to reproduce it 😬
