### ISSUE TITLE
the cursor turns into block after opening and closing nvim

### ISSUE THREAD

**Issue by D0nnieD4rk0** [alacritty/alacritty#5932]
OS: garuda linux (arch based)
Version: `alacritty 0.10.1 (2844606d)`
Linux/BSD: X11 cinnamon

i run the cursor as | beam but it turns into a block after opening and closing nvim but for some reason not regualr vim
thats about all there is to say

**Comment by kchibisov** [comment]
nvim doesn't restore cursor shape. You should restore it yourself in nvim on quit.

**Comment by tahir-hassan** [comment]
If you want to force the prompt to start of with a | cursor you could put this in your rc file:

```bash
$PS1="$PS1\033[6 q"
```

See this [answer](https://superuser.com/a/1302503/77766) for more information.
