### ISSUE TITLE
accessibility: support screen readers

### ISSUE THREAD

**Issue by insomnimus** [alacritty/alacritty#5933]
Currently, on Windows, Alacritty does not make the screen accessible to screen readers (tested with NVDA).

I would like to say more but it's completely inaccessible, I can't even read the text i type in the input line.

The default Windows terminal and the new Windows Terminal Preview work fine.

Are there plans to improve on screen reader accessibility? I myself could work on it or provide testing as a screen reader user.

**Comment by kchibisov** [comment]
>Are there plans to improve on screen reader accessibility? I myself could work on it or provide testing as a screen reader user.

Sure, if you know what should be done go ahead. If you'd have questions along the road don't hesitate to ask.

**Comment by insomnimus** [comment]
Thank you.

I'll do some research and see what could be done, in the mean time I'm closing the issue.

**Comment by kchibisov** [comment]
I don't see a reason to close it. It's not like we support screen readers.

**Comment by chrisduerr** [comment]
I don't see how you'd add screen-reader accessibility to Alacritty given that it's just an OpenGL client. Other than OCR, which obviously doesn't require any support from Alacritty itself.

**Comment by insomnimus** [comment]
OCR wouldn't be practical. The built-in windows terminal exposes information that is available to screen readers through (i presume) some API.

**Comment by chrisduerr** [comment]
Yeah there's no way we're implementing Windows-specific accessibility APIs.

**Comment by squeaktoy** [comment]
There's a Rust library called AccessKit which handles accessibility across multiple operating systems. It's growing rapidly in development and it's actually being documented, unlike any other accessibility library (shame on you, libatspi)
https://accesskit.dev/
https://github.com/AccessKit/accesskit

As Alacritty is written in Rust, it might be really feasible to use AccessKit as a way to implement accessibility. Other Rust projects like [egui](https://github.com/emilk/egui) are using AccessKit already and it's pretty nice.

**Comment by kchibisov** [comment]
I'm well aware about access-kit, though, I haven't looked into it much and if it'll be added likely via some feature or config flag. I haven't worked with it much other than knowing how it's usually integrated with e.g. winit.
