### ISSUE TITLE
Import configuration file not working on Windows

### ISSUE THREAD

**Issue by eggbean** [alacritty/alacritty#5936]
I am using the same configuration on Windows as I do on Linux. To make it easier I am adding the required Windows specific settings to a `alacritty.yml` file and then sourcing the file I use on Linux. I can't get it to work though.

    import:
      - "C:\Users\jason\AppData\Roaming\alacritty\alacritty.yml.linux"

I get this error: 

    [78660.030681600s] [ERROR] [alacritty_config_derive] Unable to load config "\\\\?\\C:\\Users\\jason\\AppData\\Roaming\\alacritty\\alacritty.yml": Config error: while parsing a quoted scalar, did not find expected hexadecimal number at line 12 column 5

Does this not work on Windows?

**Comment by chrisduerr** [comment]
Your backslashes are interpreted as escape characters. Should probably just use forward-slashes, I think they should work just as well?

**Comment by eggbean** [comment]
Thanks. I'm sure I tried that before, but I must have got the spacing wrong or something and the error message suggested to me that the escapes were being added anyway. Working now.

I still have this problem where I have a few tmux bindings that are not working, as the `Ctrl`+`Alt` modifier doesn't seem to be working at all on alacritty for Windows. I cannot find any issues regarding this?

**Comment by chrisduerr** [comment]
Might just be a Windows PTY thing.

**Comment by eggbean** [comment]
It doesn't happen (or rather, they work) on Windows Terminal. I will open another issue about this at some point. Cheers.

**Comment by chrisduerr** [comment]
Windows Terminal uses a pre-release version of the PTY. So that doesn't mean much.

**Comment by eggbean** [comment]
It also works in wsltty.

**Comment by rachtsingh** [comment]
Fwiw, I got this working using forward slashes (somehow). Very odd.
