### ISSUE TITLE
[Enhancement] Title bar only

### ISSUE THREAD

**Issue by throwaway876** [alacritty/alacritty#5938]
### System

OS: Linux (Fedora 35 on Wayland)
Version: alacritty 0.10.1
Linux/BSD: Wayland on Gnome 40

### Enhancement request
In the past I've had Alacritty simply showing a title bar without any kind of window decoration on the sides/bottom. 

After upgrading to 0.10.1 it appears my only options are full or none according to the official config as noted here-

```
  # Window decorations
  #
  # Values for `decorations`:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  #
```

What I am requesting is a new option (named just "title" or something?) that only displays the title bar. It's how it used to show for me so unsure if it's a simple option to add or not. 

A search didn't show any similar issues but if another one is already logged then apologies.

**Comment by chrisduerr** [comment]
We only ship one kind of CSD on Wayland and that's not likely going to change.
