### ISSUE TITLE
Alacritty wheel scroll doesn't work after ssh broken

### ISSUE THREAD

**Issue by Ynjxsjmh** [alacritty/alacritty#5949]
After ssh to the remote machine, if the network is off, I will get `client_loop: send disconnect: Broken pipe` in the terminal and exit ssh session.

At this time, I couldn't scroll alacritty with mouse wheel, instead, it will show text like

![image](https://user-images.githubusercontent.com/40143136/157806143-6e3ad178-00ce-455c-ae29-bccf2bdb1494.png)

Mouse wheel scrolling will work after executing `restart` in the terminal, 

### System

OS: Arch Linux x86_64
Kernel: 5.16.12-arch1-1
WM: i3wm (no DE)
Version: alacritty 0.10.1 (2844606d)

**Comment by chrisduerr** [comment]
Type `reset`.
