### ISSUE TITLE
Leaving search mode but keep highlighting search pattern

### ISSUE THREAD

**Issue by nmaupu** [alacritty/alacritty#5957]
Hi everyone,

Is there an option to keep highlighting the last search pattern even when leaving search mode (same behavior as :set hlsearch in vim) ?

**Comment by chrisduerr** [comment]
No and I have no intention of implementing this. Though using vi mode to search might satisfy that need, since it doesn't clear as long as you stay in vi mode?

**Comment by kchibisov** [comment]
I think normal search should keep highlight selected?

**Comment by chrisduerr** [comment]
Yeah it keeps the choice selected, however all other matches are cleared.

**Comment by kchibisov** [comment]
I don't think why can't we keep them, but it would mean, that we'd require special binding to clear search. Since if Vi mode works, it means that it's a matter of adding a bunch of `if`.

**Comment by chrisduerr** [comment]
It would be annoying to have it behave consistently without being confusing. So I'd rather steer clear of it.

**Comment by nmaupu** [comment]
It's a matter of preference, it's not because you think it would be annoying that everybody thinks the same.
An option would satisfy everyone.

Having a highlighted pattern consistently is a very handy feature (iterm2 does it for instance). When you tail, you can highlight something useful to you so that it pops to your eye when appearing. Nowadays, displaying bunch of yaml is very common, highlighting a keyword to get the needed information right away is a must.

**Comment by kchibisov** [comment]
I think if adding it under search option would make sense? I also want this behavior sometimes or in particular terminal window. e.g.: would help me in terminals where I dump certain type of information(AST trees) to have parts(Certain nodes) of it auto-highlighted.

**Comment by nmaupu** [comment]
> I think if adding it under search option would make sense? I also want this behavior sometimes or in particular terminal window. e.g.: would help me in terminals where I dump certain type of information(AST trees) to have parts(Certain nodes) of it auto-highlighted.

Sounds perfect, toggling it with a shortcut would be a huge plus.

**Comment by chrisduerr** [comment]
> I think if adding it under search option would make sense? I also want this behavior sometimes or in particular terminal window. e.g.: would help me in terminals where I dump certain type of information(AST trees) to have parts(Certain nodes) of it auto-highlighted.

Seems like something that should be more appropriately handled by a pipe?

**Comment by kchibisov** [comment]
How would I type into pipe, so it'll end up in shell?

**Comment by chrisduerr** [comment]
I'm not familiar with your workflow of course. If you have an idea on how to make this work nicely, feel free to re-open. I personally don't think this is worth the effort.
