### ISSUE TITLE
Issues with terminal based text editors (Scroll, Selection, Clicks...)

### ISSUE THREAD

**Issue by ZuixOff** [alacritty/alacritty#5958]
So basically i am unable to interact with the terminal when using [https://helix-editor.com](url).
(Same with nvim, not sure about others)

Here is a video showing the issues (Scroll + Clicks) :
[https://mega.nz/file/UscnECxR#KFlCDLYommPbyV13tHE1PtdHzU49pHx3lDQQdSw20hI](url)

### System

OS: Windows
Version: alacritty 0.10.0 (8a26dee)

**Comment by chrisduerr** [comment]
Your links are broken, would be extremely surprised if this isn't a Helix issue though. There are no known issues with Alacritty's mouse modes.

**Comment by ZuixOff** [comment]
Actually the link is not broken, just need to copy paste instead of direct click (I am new to github, sorry for that)
