### ISSUE TITLE
ConPTY causing problems, is there a way to disable it?

### ISSUE THREAD

**Issue by sph3** [alacritty/alacritty#5960]
![image](https://user-images.githubusercontent.com/59633047/158907386-dc9078d8-bf2f-4529-86ba-d7ba3ec3ff0a.png)

Randomly printing this weird `[?2004h` when pressing enter. I know this is a ConPTY issue and tried using `winpty_backend: true` in alacritty.yml but it didn't work. ConPTY was still being used.

### System

OS: Windows with WSL2
Version: 0.10.1 (2844606)
Linux/BSD: X11/Wayland, DE or Compositor and WM

**Comment by chrisduerr** [comment]
> ConPTY was still being used.

That's because ConPTY is the only supported backend on Windows. The only alternative to using the ConPTY is using Linux.

**Comment by sph3** [comment]
What about Tabby, which has an option to disable ConPTY? What does it use when I disable it?
