### ISSUE TITLE
mouse_bindings without mods and sending chars don't work with ncurses apps?

### ISSUE THREAD

**Issue by Grawp** [alacritty/alacritty#5961]
Consider the following configuration:
```
key_bindings:
  - { key: X, mods: None, chars: "h" }

mouse_bindings:
  - { mouse: 275, mods: None, chars: "h" }
  - { mouse: 275, mods: Shift, chars: "h" }
```

When in a shell, pressing key **x** or **Back** (the 275 on my mouse) or **Shift+Back** send character `h` to the shell and it appears on the prompt.
However when I'm in an application which is using _ncurses_ like **nnn** or **ranger** only pressing *x* or *Shift+Back* does the expected.

I'm not sure whether Alacritty actually sends something other than `h` and shell takes it as an ordinary _h_ while ncurses doesn't or where it the problem. It's very weird.

I'm out of my knowledge here and I apologize if this is not an Alacritty issue.

### System

OS: NixOS 21.11
Version: 0.9.0
Linux, Sway (Wayland)

**Comment by kchibisov** [comment]
If you see your cursor as left_arrow and not text, it would indicate that mouse mode was activated by the application, and to trigger mouse bindings, you should add `shift` to each of them.

That's expected and how other terminals are also working here. (I'd assume you can't select in your app without pressing shift either).
