### ISSUE TITLE
Mouse events not sent in Windows

### ISSUE THREAD

**Issue by tahir-hassan** [alacritty/alacritty#5963]
### System

OS: Windows
Version: alacritty 0.10.1 (2844606)

### Description

Hi guys,

I am using Alacritty and having issues with Neovim.  Particularly nothing that I use of the mouse gets sent through to Neovim.  I have tried using Neovim with conhost.exe (the default terminal in windows that cmd.exe loads up in), in the new Windows Terminal, and in git-bash.exe (don't know what terminal it uses), and all of these work. (I have `:set mouse=a`)

Particularly, mouse clicks don't get sent through, and scrolling using the mouse wheel scrolls alacritty's buffer rather than Neovim.

I have had a look at the source code (in particular `input.rs`) and compared it to `mouseInput.cpp` from Windows Terminal, and I can't see any difference as to why alacritty doesn't send the mouse events through to Neovim.  I also tried setting `TERM` to `xterm-256color` on Windows Terminal and it makes no difference as to how it behaves with Neovim, so at least I have ruled that out.

Alacritty seems to treat all mouse events as being operations on its buffer rather than sending through to the application.  Is that correct?

Any ideas?

**Comment by chrisduerr** [comment]
Alacritty's logic is definitely correct. It's either `TERM` or ConPTY issue, but it's nothing that has to be fixed in Alacritty.

**Comment by tahir-hassan** [comment]
@chrisduerr you are right, this is a ConPTY issue.  However, I think for the purpose of having Windows users adopt Alacritty as their terminal of choice it is probably better to provide a way around this issue.  

To this end, I have [cloned the repo](https://github.com/tahir-hassan/alacritty), and pasted in code from [fredizzimo](https://github.com/fredizzimo/alacritty/) from his `add_openconsole_support` branch, and compiled and included some binaries from Windows Terminal, `conpty.dll` and `OpenConsole.exe`, and I have created a [release](https://github.com/tahir-hassan/alacritty/releases), for those of us who don't want to go through the hassle of compiling the code just to get mouse support.

Fredizzimo has already tried getting his change into Alacritty, but I take it you don't want to include binaries built from Windows Terminal.

Best,
Tahir

**Comment by chrisduerr** [comment]
> Fredizzimo has already tried getting his change into Alacritty, but I take it that you don't want to create releases for Windows which contain binaries that are build from Windows Terminal.

Correct. Alacritty builds against the stable ConPTY interface shipped with Windows. For everything else people can patch things themselves.

**Comment by tahir-hassan** [comment]
> Correct. Alacritty builds against the stable ConPTY interface shipped with Windows. For everything else people can patch things themselves.

@chrisduerr fair enough.  But I think that it is a hassle that many people don't want to go through.  Perhaps another version could be provided that works against ConPTY from Windows Terminal?  I would be more than happy to do this for official alacritty releases.

**Comment by cdecompilador** [comment]
Maybe its something related to alacirtty logic, other terminal emulators just work fine using ConPTY in my case except alacritty
