### ISSUE TITLE
No window border on macOS

### ISSUE THREAD

**Issue by sshock** [alacritty/alacritty#5964]
I have decorations set to full which indicates there should be a title bar and borders.  There is a title bar, but no border.

### System

OS: macOS 12.2.1
Version: Alacritty 0.10.1

### Details

Notice the config file indicates that with `full` it will have "Borders and title bar".

```
  # Window decorations
  #
  # Values for `decorations`:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  #
  # Values for `decorations` (macOS only):
  #     - transparent: Title bar, transparent background and title bar buttons
  #     - buttonless: Title bar, transparent background and no title bar buttons
  decorations: full
```

### Screenshots

Here's a screenshot of Alacritty with a black desktop behind it.

![alacritty borders](https://user-images.githubusercontent.com/1693761/159215066-726fbd0c-afa5-4de8-9825-9169d4ff9278.png)

Here's a screenshot of iTerm with a black desktop behind it.  That 1 pixel wide tiny border really helps a lot!

![iterm2 borders](https://user-images.githubusercontent.com/1693761/159215071-a573136d-4331-473f-8bdb-2e1b9c7292e1.png)

**Comment by chrisduerr** [comment]
Working as intended. There are no borders on macOS.

**Comment by sshock** [comment]
@chrisduerr can we update the alacritty.yml to indicate there are no borders on macOS?

**Comment by chrisduerr** [comment]
> can we update the alacritty.yml to indicate there are no borders on macOS?

The documentation applies to all platforms of course. If one platform doesn't provide borders by default that doesn't mean that another won't. Full decoration simply means Alacritty will come with everything that is added by default, which includes borders if the window manager chooses to add them.

So I don't think there's a concise way that would describe this more appropriately than the current documentation.

> Also, can we keep re-open this but as a feature request?

We don't explicitly disable borders on macOS. It seems like it probably just doesn't draw any by default. And Alacritty will not render its own decorations or borders. So unless we're missing some macOS API to automatically add borders, there won't be any borders for Alacritty.

**Comment by jesseleite** [comment]
Is there any way to make a custom build with standard mac window borders? The borderless thing really trips me up when overlapping multiple windows 🙂

**Comment by weirane** [comment]
If you just want to distinguish overlapping windows, another way is to enable shadowing for windows, this way the shadow is able to tell you where the border is.

For me, I am able to get the shadow by enabling the `window_shadow` config in yabai and turning off opacity in alacritty. (it seems alacritty with <1 opacity is not able to show the shadow)

**Comment by S1lander** [comment]
> If you just want to distinguish overlapping windows, another way is to enable shadowing for windows, this way the shadow is able to tell you where the border is.
> 
> For me, I am able to get the shadow by enabling the `window_shadow` config in yabai and turning off opacity in alacritty. (it seems alacritty with <1 opacity is not able to show the shadow)

Don't know if this is still relevant, but if you use "Buttonless" but have opacity at 1.0, it will still show the border. Anything < 1 opacity will hide the border.
