### ISSUE TITLE
Open links using the keyboard (without vi-mode)

### ISSUE THREAD

**Issue by goetzc** [alacritty/alacritty#5965]
As an outcome of https://github.com/alacritty/alacritty/issues/1725, it would be handy to be able to open links using a keyboard shortcut. 

For example, KDE's Konsole allows to select a keyboard modifier that when hold, will show a number next to the links. When pressing this number, the link opens.

![image](https://user-images.githubusercontent.com/2220440/159328548-0a1b4036-273a-4107-b788-66be0eb09838.png)

![image](https://user-images.githubusercontent.com/2220440/159328497-a4f6967e-5af2-4fb6-af44-07e6ad6542cf.png)

![image](https://user-images.githubusercontent.com/2220440/159328879-9c2c0a4f-6b51-45b8-9987-19456808e2c1.png)

### System

OS: Linux
Version: alacritty 0.10.1 (2844606d)
Linux, X11, KDE Plasma

**Comment by kchibisov** [comment]
Take a look at config hints option. The feature you're talking about is supported.

**Comment by goetzc** [comment]
That is great! Apologies for the noise, was not aware of this and the _man_ page contains no such mention, but found it here https://github.com/alacritty/alacritty/blob/v0.10.1/docs/features.md#hints

**Comment by jfly** [comment]
Does the hints functionality provide the numbers for quick activation, though? (AFAICT, you have to navigate your text cursor on top of the link somehow)

**Comment by chrisduerr** [comment]
Yes.

**Comment by jfly** [comment]
Oho! That's wonderful news. Sorry for failing to read the docs. For anyone else who happens to land here, https://wiki.archlinux.org/title/Alacritty#Regex_hints explains this succinctly.

**Comment by unphased** [comment]
Thanks for linking to the doc for hints. I am realizing now after streamlining a lot of workflow one of the remaining large ones is the manual typing of code positions from logs to open the file e.g. in nvim when clicking or keyboard triggering a hint-link would do the trick. Definitely looking forward to greatly reduced file searching in the near future. I may need to build some custom neovim functionality to record which nvim process is the most recent one to wire up to the hint processing.
