### ISSUE TITLE
Window resize causes distorted visuals

### ISSUE THREAD

**Issue by FelixKratz** [alacritty/alacritty#5966]
OS: macOS
Version: alacritty 0.10.1 (2844606)

When resizing the window its contents are stretched -- disproportionally -- to fit the new frame until the view updates again.
See this (slowed down) GIF (click the image if animation not playing):
![distortion](https://user-images.githubusercontent.com/22680421/159351145-5761a8bf-77a6-4e57-a6d6-fd495a7eab59.gif)

This leads to visual flickering and might be caused by the view not refreshing appropriately on resize events. Other apps do not show this behavior.

**Comment by chrisduerr** [comment]
Likely a driver issue. You're saying this is slowed down, correct? So Alacritty updates itself properly just not as fast as you'd like?

**Comment by FelixKratz** [comment]
Yes, this is slowed down and shows 3 frames in a 60fps capture, so the distorted frame is only visible for a short time, but still causes visible flickering. Interestingly, this only happens when resizing the window horizontally, when purely resizing vertically no distorted intermediate frames are rendered to screen. I have tested with some other applications and they do not seem to exhibit this behavior.

Also curious: the green border is handled by an external tool and it seems to manage the resizing and redrawing just fine via the resize event issued from the WindowServer.

**Comment by chrisduerr** [comment]
Yeah not much Alacritty can do. We redraw on resize and that seems to be working properly according to you. How things are interpolated in the time between the resize and the redraw depends on platform afaik.

**Comment by FelixKratz** [comment]
This would mean that alacritty takes ~32ms to redraw an almost empty window, as this is the approximate time between resize event and the correct redraw. This seems extremely slow to me, I would expect the redraw of much more complex frames to take <5ms on GPU.
