### ISSUE TITLE
Not detecting opacity settings in ~/.config/alacritty/alacritty.yml

### ISSUE THREAD

**Issue by ePogYT** [alacritty/alacritty#5968]
Does not use config file located in ~/.config/alacritty/alacritty.yml or ~/.alacritty.yml
Opacity set to 0.5 in both files, does not change in the terminal

### System

OS: Fedora Workstation 35, alacritty installed with `sudo dnf install alacritty`
Version: alacritty 0.10.1
Linux/BSD: X11, Gnome 41

### Logs
Font/Terminal size:  [Alacritty-45683.log](https://github.com/alacritty/alacritty/files/8337621/Alacritty-45683.log)
Keyboard and bindings: https://pastebin.com/GnhsSrtD
alacritty.yml file: https://pastebin.com/hjFJn9Wr

**Comment by chrisduerr** [comment]
You do not have the opacity set correctly. The config is hierarchical and the parent of `opacity` (`window`) is still commented out.
