### ISSUE TITLE
Resizing Alacritty window is weird/flickery in bspwm

### ISSUE THREAD

**Issue by DashCruft** [alacritty/alacritty#5971]
This issue occurs when specifying a low `pointer_motion_interval` value in bspwmrc. (6 in my case)

### System
- **OS:** Arch Linux
- **Version:** alacritty 0.10.1 (2844606d)
- **DE:** BSPWM with Picom
- **FYI:** I use Nvidia if thats useful.

Here is a video for the calcification:

https://user-images.githubusercontent.com/59381835/160023309-c3f50b85-ef19-4fac-8254-c4e1e1932595.mp4

**Comment by chrisduerr** [comment]
That sounds to me like you're limiting the pointer refresh rate and then you aren't satisfied with how often pointer motion is reported? To me that sounds like you're complaining about a choice you made yourself?

**Comment by DashCruft** [comment]
> That sounds to me like you're limiting the pointer refresh rate and then you aren't satisfied with how often pointer motion is reported? To me that sounds like you're complaining about a choice you made yourself?

No. My default, the pointer limits to a very low refresh rate. 
1000/{monitor refresh rate} would give you a number. In my case, it was 6 cuz I have a 165hz monitor.

The screen felt like 60hz before I set that as the pointer speed. I'm not limiting it - I'm increasing to match my monitor's hz

**Comment by chrisduerr** [comment]
And with that lower rate it works fine?

**Comment by DashCruft** [comment]
Any value lower then 7 will cause that to occur. (7 is for 144hz)

**Comment by chrisduerr** [comment]
I really don't see how this would be related to Alacritty then, when the behavior depends so heavily on a refresh setting made in the compositor. With OpenGL it's true that some drivers handle resizing and frequent updates better than others, but there's not much Alacritty can do about that.

Do you see different behavior from other OpenGL applications like glxgears or Kitty?

**Comment by DashCruft** [comment]
glxgears has no issues whatsoever when resizing. Just like kitty (though it might show up sometimes for kitty but its way less comparing to alacritty)

Alacritty is the only one that actually has that very noticeably

**Comment by chrisduerr** [comment]
> Just like kitty (though it might show up sometimes for kitty but its way less comparing to alacritty)

So it does show up in Kitty too?

Neither glxgears nor Kitty use vsync, so that might just amplify the problem. I see no reason for explicit action here.
