### ISSUE TITLE
Consumed modifier keys required in keybindings

### ISSUE THREAD

**Issue by OJFord** [alacritty/alacritty#5972]
### System

OS: Linux
Version: `alacritty 0.10.1 (2844606d)`
Linux/BSD: Wayland, sway

### Logs

> [12.571405548s] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(94144256298704))), event: KeyboardInput { device_id: DeviceId(Wayland(DeviceId)), input: KeyboardInput { scancode: 47, state: Pressed, virtual_keycode: Some(Paste), modifiers: LOGO }, is_synthetic: false } }

---

When binding to `At` on a US layout, for example, it is necessary in Alacritty to supply `mods: Shift`, when really this was already consumed in producing the `At`.

I came across this in adding a <kbd>Super</kbd>+<kbd>v</kbd>` binding for `XF86Paste`, and initially thought I'd done something wrong in XKB, since Alacritty would see `Super+XF86Paste` rather than just `XF86Paste`. I've confirmed though with `wev`, `wshowkeys`, and by trying something similar with <kbd>Shift</kbd+<kbd>2</kbd> (for `At`) that the binding is correct.

In case it's of any use, it seems `rofi` had and fixed a similar issue: https://github.com/davatorium/rofi/issues/485

**Comment by chrisduerr** [comment]
It's a known issue that the current keyboard handling isn't ideal. This requires some upstream work and is tracked there and some other Alacritty issues. At the moment there's no way around this in Alacritty itself.

**Comment by OJFord** [comment]
Ok, thanks @chrisduerr. If you have a chance, could you link me one of the others or upstream issues please?

I had another look but I assume they're more generic/nuanced, so difficult to find without prior knowledge. Just so I have something to subscribe to to keep track of. Cheers!

**Comment by chrisduerr** [comment]
Upstream is https://github.com/rust-windowing/winit/issues/753. There should be a couple open Alacritty issues linked too already.
