### ISSUE TITLE
Combining characters rendering on wrong cell

### ISSUE THREAD

**Issue by Myrdden** [alacritty/alacritty#5973]
Hello! I see there's been a lot of work regarding unicode support, which is awesome, and while combining characters have the correct width and input properties, they appear to render on the wrong cell. For instance, say you're trying to get `xýxý` using the unicode combining acute (U+0301), it renders like `xyx́y´`. It's not actually combining to the wrong character, if for instance you see the latter inside of an HTML file you're editing, and then open the file in the browser, you'll correctly see the former show up, it's just that the terminal seems to be rendering the combining characters on the cell after where it should.

For replicating, I'm running Arch Linux w/ Wayland, and the font I'm using is DejaVu Sans Mono, however I've tried the other monospace fonts I have on my system and the outcome is the same with all of them.

**Comment by chrisduerr** [comment]
This is a font problem.

**Comment by Myrdden** [comment]
I think this is a duplicate of #1420, my bad. I tried with Fira Mono as per the examples posted there, which I didn't have previously installed, and it looks like they are rendering correctly now, this looks to be that
