### ISSUE TITLE
Reopening Terminal

### ISSUE THREAD

**Issue by colin99d** [alacritty/alacritty#5975]
When you exit the terminal in after running commands a dot it still under it. If you want to reopen the terminal you first have to quit the program, then click again to open up a terminal.

### System

OS: macOS
Version: alacritty 0.10.1 (2844606)

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by chrisduerr** [comment]
A dot is still under it?

**Comment by colin99d** [comment]
Sorry, should have been more descriptive.
<img width="105" alt="Screen Shot 2022-03-26 at 10 31 01 AM" src="https://user-images.githubusercontent.com/72827203/160244094-709777e0-8319-4abc-ac74-8d58c4764505.png">

**Comment by chrisduerr** [comment]
How are you exiting the terminal?

**Comment by colin99d** [comment]
I have been pressing the red circle at the top (the close button on Mac). This happens about 30% of the time.

**Comment by chrisduerr** [comment]
Does the same issue occur when you use `exit` or ^D?

**Comment by colin99d** [comment]
I ran through it a few times and this seems to work much better! Thank you for the idea.

**Comment by chrisduerr** [comment]
Which shell are you using? I've never heard of anyone running into these kind of issues before and it kinda sounds like there might be something odd with your setup.

**Comment by colin99d** [comment]
Here are my config files https://github.com/colin99d/configs. Nothing crazy. I am using ohmyzsh as my shell. I can send my zshrc if you like but its pretty generic.

**Comment by nixpulvis** [comment]
I feel like a video/gif of the issue might help here. Perhaps you have multiple instances of Alacritty running and you're only closing one? You'd probably notice multiple icons in your dock, but it's the easiest explanation.

Also, please include version numbers with your OS description, thanks.

**Comment by colin99d** [comment]
I am running MacOs version 12.3. I never run more than one instance of Alacritty thanks to tmux. Also, I have never purposely used `Command-H` before, and this issue happens frequently.

[Here](https://drive.google.com/file/d/1VhbNwVJETMrHNvV6vIKSrF-ZCj9nTUyK/view?usp=sharing) is a link to a screen recording. Its still processing in Google Drive so it might not be available for a little bit longer.

**Comment by nixpulvis** [comment]
@colin99d could you record a video that shows how you end up in this situation? I can see the issue, but I cannot see what you did to end up here.

Also, it seems you have some kind of macOS skinning/theming going on? Or am I just completely out of the loop? Your menu bar looks very different than I expect. Could that be interfering with the way the close action performs? I'm not assigning blame to the issue (yet), I'm just curious why I don't experience this issue on my Mac (running macOS 12.3).

**Comment by colin99d** [comment]
I just happens by pressing the red exit button. It happens roughly 30% of the time. I am not sure what macOS skinning/theming is, but I have not changed any settings like that on my Mac.

**Comment by chrisduerr** [comment]
Have you tried it without tmux just running a basic bash shell?

**Comment by colin99d** [comment]
I have had the issue when tmux was not being used. Should I try it in a different shell?

**Comment by chrisduerr** [comment]
> I have had the issue when tmux was not being used. Should I try it in a different shell?

Yes, I'd recommend just testing bash without any configs.

**Comment by colin99d** [comment]
I tried disabling my alacritty configs and that did not fix the problem. However, I did make a discovery. When I close it in full screen mode the issue always happens. However, if the screen is not full the issue never happens. This behavior happens with bash and zsh shells

**Comment by chrisduerr** [comment]
@colin99d So it **only** happens in fullscreen? Is there any other application sharing this behavior?

**Comment by colin99d** [comment]
It is only happening in fullscreen. No other applications do this. Also the other day it happened when typing `exit`.

**Comment by chrisduerr** [comment]
Which macos version are you on?

**Comment by colin99d** [comment]
Monterey 12.3

**Comment by keithpl** [comment]
Can confirm I experience the same behavior:
1. Open alacritty
2. Full screen alacritty
3. Terminate session any number of ways, ^D, exit, logout, etc.
4. alacritty continues running in the background, cannot start new session until it's manually killed

macOS 12.2.1
Alacritty 0.10.1
zsh 5.8
bash 5.1.16
tmux 3.2a 

** happens with and without tmux **

**Comment by ezzieyguywuf** [comment]
I can also confirm - alacritty 10.1:

    1. open alacritty (defaults to fullscreen per config)
    2. Exit using various methods
    3. alacritty stays running, but I cannot recover the window - right-click -> terminate is the only way to get rid of it

**Comment by kchibisov** [comment]
Could someone verify that #6079 fixes the issue?

**Comment by keithpl** [comment]
> Could someone verify that #6079 fixes the issue?

@kchibisov same behavior for me when building from that feature branch
```
./alacritty --version
alacritty 0.11.0-dev (fdcf99b0)
```

**Comment by kchibisov** [comment]
@keithpl you've build master branch, not that branch, since your commit is from master.

You should clone it like `git clone https://github.com/kchibisov/alacritty -b update-winit-0.27 alacritty-winit`. Then `cd alacritty-winit && cargo run`

**Comment by keithpl** [comment]
@kchibisov yup, you're exactly right. Right repo... never checked out the branch.. ugh.

Can confirm this fixes the issue as far as I can tell.
```
./alacritty --version
alacritty 0.11.0-dev (2b03e4ea)
```
