### ISSUE TITLE
Don't use vao with gles2

### ISSUE THREAD

**Issue by kchibisov** [alacritty/alacritty#5979]
VAO isn't present when gles2 being used, so for pure gles2 rendering we should consider going without it. Though, the majority gles2 devices do have vao(even pine phone has it), so I'm not sure if it really makes sense.

Should probably keep around until someone complains that gles2 not working on their gles2 system...

**Comment by anarsoul** [comment]
I doubt you'll find a driver that doesn't support VAO. mesa supports ARB_vertex_array_object in all the drivers, it's a purely software extension.

**Comment by kchibisov** [comment]
I don't think there's any reason to not use vao.
