### ISSUE TITLE
Heavy Double Turned Comma Quotation Mark Ornament not displayed correctly when italics are enabled

### ISSUE THREAD

**Issue by reportaman** [alacritty/alacritty#5980]
Unicode "Heavy Double Turned Comma Quotation Mark Ornament" ❝ (U+275D), and ❞ (U+275E) seem to get translated into regular double quotes when italics are not enabled. When italics are enabled, they seem to be printed as tofu.

I am aware that there is a bug to support fallback fonts. What makes me file this as separate issue is that Alacritty seems to translate the glyph for upright font, but not for italic font. This glyph is not present in either of the fonts I use in Alacritty, so it should either be tofu all the time, or more preferably consitently be translated to regular double quotes “ (U+201C) & ” (U+201D) (even when italics escape sequence is enabled).

Alacritty:
<img width="746" alt="Screen Shot 2022-03-30 at 3 47 40 PM" src="https://user-images.githubusercontent.com/71736629/160943847-9ff4a008-e24f-44e4-96f5-790d03cc0a71.png">

Rest of terminals (iTerm2, WezTerm, Kitty, Apple Terminal): (they pick the glyph from a Arial Unicode MS font on macOS)
<img width="746" alt="Screen Shot 2022-03-30 at 3 50 06 PM" src="https://user-images.githubusercontent.com/71736629/160943861-1b52a9b2-d6c4-44a4-b9d8-e9f354f61827.png">

### System

OS: macOS 12.3
Version: v0.10.1

**Comment by chrisduerr** [comment]
Alacritty doesn't do unicode normalization. Regardless of font style.
