### ISSUE TITLE
palette query responses are malformed

### ISSUE THREAD

**Issue by dankamongmen** [alacritty/alacritty#5981]
### System

OS: Linux
Version: alacritty 0.10.0-dev (ebf41d5f)
Linux/BSD: X11/Compiz+XFCE

It appears that Alacritty has recently added support for palette interrogation. That's great! Unfortunately, the responses are malformed. They ought be of the form

`]4;N;rgb:XXXX/XXXX/XXXXST` or `]4;N;rgb:XX/XX/XXST`

instead, Alacritty is replying with

`]N;rgb:XXXX/XXXX/XXXXST`

(note the missing `4;` at the front)

not only does this diverge from other implementations, but it introduces an ambiguity: it is now impossible to distinguish between a reply for the default fg / default bg queries and palette indexes 10 and 11.

this is causing problems for Notcurses with newer Alacritty, manifesting as a bunch of garbage on stdin: https://github.com/dankamongmen/notcurses/issues/2643

**Comment by chrisduerr** [comment]
Good catch, thanks. Should be fixed with https://github.com/alacritty/alacritty/pull/5982.
