### ISSUE TITLE
MacOS window doesn't open unless an instance has focus

### ISSUE THREAD

**Issue by dprotaso** [alacritty/alacritty#5986]
### System

OS: macOS Monterey 12.3
Version: alacritty 0.10.1 (2844606)

### Logs

N/A

### Details

Under `System Preferences > Missing Control` I have  `When switching to an application, switch to a Space with open windows for the application` unchecked

ie. 

<img width="780" alt="Screen Shot 2022-04-04 at 3 54 45 PM" src="https://user-images.githubusercontent.com/18562/161621514-05fe5836-0e31-4c3e-9271-d9553556f4b7.png">

When I'm in a new space/desktop with no Alacritty windows/instances - I'm unable to create a new window using the key binding I have set.

```
  - { key: N,        mods: Command, action: CreateNewWindow              }
```

Prior to trying to create a window the application has 'focus' since 'Alacritty' appears in the menu/task bar at the top left

<img width="120" alt="Screen Shot 2022-04-04 at 3 58 55 PM" src="https://user-images.githubusercontent.com/18562/161622114-fa589523-4df3-477d-a010-b9e053f0bfb9.png">

**Comment by chrisduerr** [comment]
Working as intended, the application is not active and thus bindings do not work.

**Comment by dprotaso** [comment]
This still occurs if I have a window open on another desktop/space

**Comment by chrisduerr** [comment]
Having a window open is not sufficient. It seems like what you want is an OS shortcut.

**Comment by dprotaso** [comment]
> It seems like what you want is an OS shortcut.

To clarify - are you saying a global shortcut to open a new Alacritty window regardless if the application is open/focused?

I guess I'm wondering if it's a goal/in scope of this project to behave more like a native Mac App - where the lifecycle of the 'application' is independent of the actual windows.

Like the example above: I would consider the Alacritty application having focus (but not a specific window) to be 'active'. Then I could create a new window either via the menu bar or a keyboard shortcut

**Comment by chrisduerr** [comment]
> To clarify - are you saying a global shortcut to open a new Alacritty window regardless if the application is open/focused?

Correct.

> I guess I'm wondering if it's a goal/in scope of the Mac app to behave more natively - where the lifecycle of the 'application' is independent of the actual windows.

I'm not really interested in that. It seems very messy to me. Though if you actually care and can come up with a clean implementation, feel free to send a PR.

Your usecase seems to pretty clearly be opening another Alacritty instance without directly having another Alacritty instance active. One being in the background is more of a coincidence in that case. Relying on some weird hidden app magic to implement global shortcuts just because macOS doesn't allow you to configure them without third-party tools just seems like a shitty solution to me.
