### ISSUE TITLE
Alacritty has no support for overline (SGR 53/55)

### ISSUE THREAD

**Issue by rbanffy** [alacritty/alacritty#5988]
In other terminals (VTE, QTermWidget, Microsoft) and screen managers (tmux) there is support for overlined text. This is a good option for status lines on the bottom of the screen or other types of divider where you want to control the line immediately under the divider and don't want to interfere with the bottom line of content that sits above the divider/border.

**Comment by kchibisov** [comment]
We've discussed it with @chrisduerr and I'm not sure why it should be added in the first place, however given that it's widely supported and that it's simple to add maybe we should add it...

What do you think @chrisduerr? It's like strikeout, but higher, clamped to top of the cell iirc...

**Comment by kchibisov** [comment]
It basically works like strikeout and supported by vte/konsole and friends. I personally don't see much benefit in it, since it really looks like shitty underline for the one line above.

**Comment by rbanffy** [comment]
The argument for it is how it's useful for things like status lines (it's not intended to be an underline for the line above).

![Gnome Terminal](https://user-images.githubusercontent.com/184714/161855064-feac0429-affb-403d-bd5a-53410967c6f4.png)

![Konsole](https://user-images.githubusercontent.com/184714/161855509-eda06ccd-3196-4980-aabc-94d0cbbff894.png)

One easy to think use is on the shell prompt, as a separator from previous output. Another one is in terminal splits, where separators can also have titles or other indicators for the panel below.

![IBM 3151](https://user-images.githubusercontent.com/184714/161856429-7536caa1-685e-47b5-b2d4-75faed64d964.png)

**Comment by chrisduerr** [comment]
Seems like just changing the background color would be far superior? The existing implementations you're showcasing look like absolute garbage, so that doesn't really make for a good argument. From those screenshots alone it seems pretty obvious to me that monospace fonts will not properly account for an overline and it will look strange and ugly.

**Comment by rbanffy** [comment]
Personally, I don't like changing the background because I, personally, use color very sparingly. I use that option in my `tmux.conf` (and the default tmux status is that RGB-green line - that won't ever change, as that green line is part of their visual identity and you can see a tmux session from a mile away, making it wildly successful for them) when the target terminal doesn't support, say, overlines. Many physical terminals of ancient times used reverse video (because that's what they had) or underline (and that's probably why Wyse terminals had a line on the top of the screen, a position I find most distracting).

In any case, I can understand not wanting to add a feature just because other competing programs support it.

On the font argument, fonts usually have to leave space above the top for accents and other marks, so some may already have that space. The 3270 font you see in the examples I posted is one I made that has space above the glyphs, but it's up to the terminal emulator to decide on vertical spacing, especially if the emulator uses its own pixel-perfect line drawing and graphical blocks instead of relying on font-based ones, which may end up being subject to all sorts of issues.

**Comment by kchibisov** [comment]
The problem is that position for overline must be picked arbitrary, since fonts don't carry such property. There's a position for strikeout, underline, etc, but not overline. In reality you'll have to use top most pixel of the bounding box, however the underline could use bottom most in some fonts e.g. (mostly all bitmap fonts). So the look of such thing will be terrible.

If fonts had overline position it could probably justify adding it, since it's a font thing, but for now it looks like just a hack to overcome certain limitations.

**Comment by chrisduerr** [comment]
> On the font argument, fonts usually have to leave space above the top for accents and other marks, so some may already have that space.

As you've just said though, that space is for accents and other marks. So an overline needs to be **above** that.

> If fonts had overline position it could probably justify adding it, since it's a font thing, but for now it looks like just a hack to overcome certain limitations.

Completely agree.

**Comment by atirit** [comment]
> If you can give me a reason why someone would need it that isn't completely silly, I'm happy to consider it.

One use case for overlines that underlining the above row doesn't cover is drawing a line over the top row. I do this in a TUI to indicate a selected, unfocused list item, which would not work for a list item in the top row (screenshot from Windows Terminal):

![unknown](https://user-images.githubusercontent.com/17181723/171773234-9608b2a5-2e2d-4ab8-bb70-edd8d11277f9.png)

> The existing implementations you're showcasing look like absolute garbage, so that doesn't really make for a good argument.

I feel this is somewhat harsh and very dismissive. I think they look great and that whether it's "garbage" or not is down to preference. Users should have the choice to enable whatever style they feel most comfortable with, and explicitly preventing support for and needing a "good argument" in favor of a standard SGR code on the basis of disliking its appearance is acting in bad faith.

> In reality you'll have to use top most pixel of the bounding box ...

Windows Terminal draws at the top of the cell, yes: https://github.com/microsoft/terminal/blob/c157f6346aa46f9c95342e32991e8c9cd97a150d/src/renderer/gdi/paint.cpp#L567

**Comment by chris-morgan** [comment]
All up, you’ve got quite a few people independently requesting this (I’ll add myself to the list, for similar reasons to those who have already spoken), reasonable demonstrations of real-world uses of the functionality where there is no reasonable alternative, quite a few other terminals that do support this, and a neat, small patch that implements it. I do not understand your grounds for rejecting the feature at all, and request that you reconsider it.

I could add another realistic (though niche) use case: displaying mathematical equations that use overline for things like recurring fractions. (In theory you could use U+0305 COMBINING OVERLINE, but in practice it’s even worse-supported in monospaced fonts than the overline SGR code is in terminals.)

I don’t care that font metrics may not provide a good way of specifying an *ideal* overline position. Despite that, overline is a standard feature of text engines—word processors, the web, *&c.* and you have presented no good reason to *actively withhold* the feature here.
