### ISSUE TITLE
Migrate from winapi to widows-sys

### ISSUE THREAD

**Issue by kchibisov** [alacritty/alacritty#5993]
It seems like there's a movement of migrating from winapi to windows-sys, since the latter is directly maintained by microsoft. Upstream winit for example already moved to windows-sys.

**Comment by chrisduerr** [comment]
> It seems like there's a movement of migrating from winapi to windows-sys, since the latter is directly maintained by microsoft.

While Microsoft maintaining their own API makes some sense, I'm not sure that alone is an argument for switching? Do you know if there has been a statement by `winapi` encouraging people to switch? The project doesn't seem to be super active anymore though maybe it's just "done"?

Generally `winapi` still seems to have about 5 times the number of recent downloads on `crates.io`, so it still seems to be a good chunk more popular.

**Comment by kchibisov** [comment]
@chrisduerr the problem is that we have both at the same time and winit moved to windows-sys recently.

In general we won't have 2 dependencies linking to the same system libraries.

**Comment by chrisduerr** [comment]
> @chrisduerr the problem is that we have both at the same time and winit moved to windows-sys recently.

I mean why did they move? Did they have a reason or did they just do it to annoy downstream?

**Comment by kchibisov** [comment]
I think the motivation is https://github.com/rust-windowing/winit/pull/2057 ? Though, it was more about windows-rs, and not sys.

Though, winapi seems like indeed unmaintained.

**Comment by chrisduerr** [comment]
Windows is such a shitshow, I guess I don't really care either way as long as we're not switching dependencies every couple months.
