### ISSUE TITLE
Slow startup on mesa 22

### ISSUE THREAD

**Issue by piotryordanov** [alacritty/alacritty#5996]
I am running arch on wsl2. So far everything was going fine until i upgraded mesa from v21 to v22.
I started noticing this error: `NVD3D10: CPU cyclestats are disabled on client virtualization`  when i do `alacritty -v`

Downgrading to mesa v21 allowed alacritty to start fast again.

Any idea why this is the case, and how it could be mitigated?

**Comment by chrisduerr** [comment]
> Any idea why this is the case, and how it could be mitigated?

Seems like something better asked in a channel related to Mesa.
