### ISSUE TITLE
Mouse input is captured by alacritty when the button is grabbed on x11

### ISSUE THREAD

**Issue by MarcusGrass** [alacritty/alacritty#5997]
### System
OS: Linux
Version: alacritty 0.10.1 (2844606d)
Linux/BSD: X11 [pgwm](https://github.com/MarcusGrass/pgwm)

I wrote a WM and one of the features it includes is resizing a tiled window when scrolling, when doing this in Alacritty the terminal is scrolled as well even though the scroll button is captured, the information that the scroll button is pressed seems to leak even though it's grabbed.
This could be an implementation mistake done by me, but with other terminal emulators that can scroll, like urxvt, and kitty, as well as all other applications which implement scrolling that I've tested, scrolling does not leak through if pressing the appropriate mod-key for the grab.

I don't quite understand how these events are propagated to alacritty when they should be grabbed by the WM. Is this a bug with alacritty, a feature, a bug on my side?

I did a sloppy attempt to try to repro this with DWM and xmonad but I have neither configured to resize on scroll so it'd take me a while to get that working to see if its the same.

**Comment by kchibisov** [comment]
Try looking through `alacritty --print-events` might see something for mouse/pointer.

**Comment by MarcusGrass** [comment]
> Try looking through `alacritty --print-events` might see something for mouse/pointer.

I can see alacritty gets an event from glutin, so the problem is definitely not with Alacritty, I'm going to try to debug it over there and see if I can get closer to the issue, thanks!
