### ISSUE TITLE
osc52 and callback handler support

### ISSUE THREAD

**Issue by amosbird** [alacritty/alacritty#600]
Hi, thanks for this great tty. However, the only one reason keep me away from using it is the lack of osc handler support. I have a script in urxvt for doing this ,
```
#!/usr/bin/env perl

use MIME::Base64;
use Encode;

sub on_osc_seq {
  my ($term, $op, $args) = @_;
  open(my $fh, '>', '/tmp/testperl');
  print $fh $op;
  return () unless $op eq 52;
  my ($clip, $data) = split ';', $args, 2;
  if ($data eq '?') {
    my $data_free = $term->selection();
    Encode::_utf8_off($data_free); # XXX
    $term->tt_write("\e]52;$clip;".encode_base64($data_free, '')."\a");
  }
  elsif ($clip =~ /x/) {
    my $data_decoded = decode_base64($data);
    Encode::_utf8_on($data_decoded); # XXX
    # my $host_name = $term->resource('title');
    # $data_decoded =~ s/^\/amos\@$host_name://;
    print $fh $data_decoded;
    $term->exec_async('vivaldi', $data_decoded);
  }
  elsif ($clip =~ /y/) {
      my $data_decoded = decode_base64($data);
      Encode::_utf8_on($data_decoded); # XXX
      # my $host_name = $term->resource('title');
      # $data_decoded =~ s/^\/amos\@$host_name://;
      print $fh $data_decoded;
      system($data_decoded);
  }
  else {
    my $data_decoded = decode_base64($data);
    Encode::_utf8_on($data_decoded); # XXX
    print $fh $data_decoded;
    $term->selection($data_decoded, $clip =~ /c/);
    $term->selection_grab(urxvt::CurrentTime, $clip =~ /c/);
  }
  close $fh;
  ()
}
```
It can achieve amazing stuff. Is there any plan to support such feature?

**Comment by jwilm** [comment]
I'll have to think about it. I worry about how this might affect complexity. However, I can see how it's appealing. If this were to happen, it would probably be Lua.

Would love to see some discussion on this subject from the community.

**Comment by amosbird** [comment]
Hi @jwilm . It has been a while. What do you think now :)

**Comment by jwilm** [comment]
@amosbird It's definitely something I will explore at some point. I personally won't have time to experiment with an implementation until early next year, most likely.

**Comment by ztlevi** [comment]
Any progress made since then? It looks like Kitty implements its own osc 52 to support larger clipboard https://sw.kovidgoyal.net/kitty/protocol-extensions.html#pasting-to-clipboard.

That's a good feature to have.

**Comment by kchibisov** [comment]
we have `OSC 52`, so this issue is purely about callback mechanism, I guess, which I'm against to do in a proposed way or with lua, since it's slow and unreliable sometimes.

**Comment by chrisduerr** [comment]
Also it's important to note that Alacritty supports arbitrary parameter lengths, so you can just paste massive things to the clipboard without having to concatenate multiple escapes.

**Comment by ztlevi** [comment]
I see. Thanks! Let me reference this issue to the package I'm using. See if we can enable larger clipboard feature on that package.

**Comment by chrisduerr** [comment]
Hints can be passed to arbitrary programs and they use user-definable regexes. That's about all I'm willing to do for this issue.
