### ISSUE TITLE
Ctrl-<NUM> keys not recognised

### ISSUE THREAD

**Issue by rameshsanth** [alacritty/alacritty#6003]
Pressing control 5 or control 6 doesn't work properly. i got the showkey output below.

Kitty seems to generate <RS><GS> for Ctrl6 and ctrl5. whereas alacritty simply generates just 6 and 5 ignoring control modifier.

### System

OS: OSX 12.3.1
Version: alacritty 0.10.1 (2844606)

### Logs
**Alacritty**
```
➜  ~ showkey
Type any key to see the sequence it sends.
Terminate with your shell interrupt <CTL-C=ETX> or quit <FS> character.
65<CTL-J=LF><ESC>
Bye...
```

**Kitty**
```
➜  ~ showkey
Type any key to see the sequence it sends.
Terminate with your shell interrupt <CTL-C=ETX> or quit <FS> character.
<RS><RS><GS><ESC>
Bye...
```

**Comment by chrisduerr** [comment]
Seems like this is covered by https://github.com/alacritty/alacritty/issues/3720.

**Comment by rameshsanth** [comment]
No. this is not keys in the keypad.. this is using keys at the top row..

**Comment by chrisduerr** [comment]
Oh, your `Ctrl-<NUM>` confused me. Have you tried with an empty config?
