### ISSUE TITLE
Alacritty not installing

### ISSUE THREAD

**Issue by AKAONTOP** [alacritty/alacritty#6006]
### System

OS: Linux (Kali-linux)
So after i run "cargo build --release" this is the output:
(Finished release [optimized + debuginfo] target(s) in ==s)
after this i try and run alacritty and it doesnt output anything neither start alacritty
if i try and type it another time it will say command not found 
but if i install it with "cargo install alacritty" it works but i can't use it as default terminal
please help

**Comment by chrisduerr** [comment]
See the `INSTALL.md` on details how to install the auxiliary files.
