### ISSUE TITLE
Is it possible to change the font size only during a specific terminal program?

### ISSUE THREAD

**Issue by tapyu** [alacritty/alacritty#6008]
I am using `neovim` on `alacritty`, but its default font size is comfortable on terminal and too big on `nivm`. I would like to decrease the font size only when I am on `nvim`, and as soon as I leave it, I go back to the default font size on terminal. Is it possible?

### System
```
 OS: Ubuntu 20.04 focal
 Kernel: x86_64 Linux 5.13.0-39-generic
 Uptime: 6h 51m
 Packages: 2861
 Shell: zsh 5.8
 Resolution: 2048x1152
 DE: GNOME 3.36.5
 WM: Mutter
 WM Theme: Adwaita
 GTK Theme: Yaru-dark [GTK2/3]
 Icon Theme: Yaru
 Font: Ubuntu 11
```

**Comment by chrisduerr** [comment]
Not without manually changing the font size using the config bindings.
