### ISSUE TITLE
Perceived mouse slowness on high refresh rate monitors on Windows

### ISSUE THREAD

**Issue by rnmp** [alacritty/alacritty#6009]
### System

OS: Windows
Version: 0.10.0

Hi Alacritty team!

Amazing emulator. I almost gave up on developing on Windows (I usually develop on macOS) due to how awfully slow other terminals are.

I'm reaching out because I noticed that fps are capped at 30fps by default on Windows at least, this feels choppy when going from other apps on my 144hz monitor. Hard to show you what I mean but here's a video with my monitor fps counter where you can kinda see what the issue is.

https://user-images.githubusercontent.com/22627/163906162-95403bd8-c00e-4fa4-a00a-12c592a4055c.MOV

**Comment by chrisduerr** [comment]
FPS aren't capped to 30 in the slightest, they're capped to vsync. What framerate that syncs up to depends on your graphics drivers. So I recommend looking into those to see if something can be tweaked there.

**Comment by rnmp** [comment]
Oh I meant no offense, sorry. I'm just trying to make the best use of your great software.

I noticed someone ran into a similar issue here: https://github.com/alacritty/alacritty/issues/4429

I tried what you suggested and upgraded graphics driver and it's still the same issue. Any other suggestions?

**Comment by chrisduerr** [comment]
What graphics drivers are you using? Nvidia for example should have a control panel where you can add particular settings on a per-application level. Though I'm no Windows user, so I can't give you any specific instructions.

**Comment by rnmp** [comment]
That did it! I was unaware of this functionality. For posterity, if anyone is reading this and has same issue. Open your NVIDIA Control Panel > Manage 3D Settings and manually add alacritty. You then have to turn on V-Sync.

![image](https://user-images.githubusercontent.com/22627/164149085-789cae32-9c3c-463a-b5d1-37a8aadb86a1.png)
