### ISSUE TITLE
ANSI not working correctly

### ISSUE THREAD

**Issue by pjalsGit** [alacritty/alacritty#6012]
### System

OS: Fedora 35
Version: alacritty 0.10.1
Protocol: Wayland
DE/WM: Gnome
TERM env var: alacritty

### Screenshots

![image](https://user-images.githubusercontent.com/25231103/164205041-bbb1c2d3-50c4-4738-9b10-c1ff6df41d2e.png)
![image](https://user-images.githubusercontent.com/25231103/164205272-d6c90e68-a2a5-4dce-a49e-ea70708ac95b.png)
![image](https://user-images.githubusercontent.com/25231103/164205451-5746ed89-f30f-4abe-8bfe-f3a5237584c5.png)

### What am I doing?

I'm trying to print a colored character in Deno with ANSI (with ``await Deno.stderr.write(new TextEncoder().encode(`\x9B38;2;${r};${g};${b}m${char}`));``), but Alacritty and libvterm doesn't support it. GNOME Terminal, and VSCode does.

**Comment by pjalsGit** [comment]
Replacing `\x9b` with `\x1b[` fixes it, Alacritty should support one-character CSI (`\x9b`)

**Comment by kchibisov** [comment]
C1 support was removed and it's intentional. For more see https://github.com/alacritty/alacritty/pull/3135 and #3105.
