### ISSUE TITLE
Feature request: Copy with formatting

### ISSUE THREAD

**Issue by jaysonlarose** [alacritty/alacritty#6013]
Hello all.

I don't know if this is the place for feature requests; if it's not, I apologize in advance.

One of the features from VTE that I've become rather fond of is its "copy as HTML" feature.  I use it along with a bit of scripting trickery in order to create sweet HTML documentation.

For an example: <https://www.interlaced.org/shellsession.html>.

It's tiny compared to embedding images, it looks beautiful, you can reflow the text, and most crucially, you can copy and paste from it.

I managed to convince the author of kitty to implement something very similar (his implementation uses Xterm escape sequences, but that's nothing a quick pass through the `ansi2html` python module can't fix) , so I'm hoping I can convince you folks as well.

Pretty please?

**Comment by chrisduerr** [comment]
There's a feature request to pass the current terminal content to other applications (https://github.com/alacritty/alacritty/issues/1615). This includes doing so with and without formatting.

So that would solve your issue. Beyond that there's no interest.

**Comment by jaysonlarose** [comment]
Ah, you mean the one that hasn't seen any forward momentum in over a year after the person working on the pull request posted "I am no longer interested in working on this due to a lack of communication, motivation, and time." and closed it?

Fair enough, my search shall continue.

**Comment by asdf8dfafjk** [comment]
@jaysonlarose Please dont be passive aggressive unless chris is on your payroll. I am definitely against Chris's attitude on the PR mentioned but seeing how people treat OSS maintainers (your very reply e.g.), I am inclined to think that Chris's attitude isn't his own fault.

**Comment by jaysonlarose** [comment]
@asdf8dfafjk what?  That was like, two months ago. I asked nicely for a feature, and got a abrasive reply. Which is perfectly in his rights to do. I let him know that he pointed me to an obviously dead and closed feature request, and let him know that I wouldn't be using the software, which is perfectly in my rights to do. I moved on, and presumably so did Chris.

Your comment about how I shouldn't be passive aggressive unless Chris is on my payroll is A) pretty passive-aggressive in of itself, and B) insinuates that it's okay to be passive-aggressive to your employees, which is kind of messed up. So why are stirring drama up in a 2 month old closed thread?

**Comment by asdf8dfafjk** [comment]
I would engage with you but the more I read your reply, the more I think you need help.

**Comment by jaysonlarose** [comment]
Don't go away angry, just go away.
