### ISSUE TITLE
Unable to key bind to command with 

### ISSUE THREAD

**Issue by GZLiew** [alacritty/alacritty#6015]
Hi im trying to add keybinding:

```yml
  - { key: N,        mods: Command, command: {program: "/usr/local/bin/alacritty", args: ["--working-directory", "$(PWD)"]} }
```

but im currently getting the following error

![image](https://user-images.githubusercontent.com/43195293/164610178-9f294c9e-c0f1-421c-bc5f-727490fa5353.png)

it works when I ran it in the command line

```bash
alacritty --working-directory $(pwd)
```

### System

OS: macOS
Version: alacritty 0.10.1 (2844606)

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`

**Comment by kchibisov** [comment]
That's expected since we're not a shell, and even if you use shell `$(PWD)` will be the one you've used to run alacritty.

I'd suggest to use `CreateNewWindow` or `SpawnNewInstance` actions.
