### ISSUE TITLE
Selection copied to primary clipboard unexpectedly

### ISSUE THREAD

**Issue by japalvia** [alacritty/alacritty#6021]
Steps to reproduce:
1. open 2 alacritty terminals
2. output text in terminal 1, e.g. `ls /bin/`
3. double click text to select, do nothing else
4. move mouse over terminal 2
5. select text (i.e. copy to primary)
6. move mouse over terminal 1
7. type Space char
8. paste from primary using middle mouse button

Expected: text selected in terminal 2 is pasted

Actual: previous selection in terminal 1 is pasted

No clipboard managers are used.

Other findings: clicking the terminal seems to avoid this behavior. For comparison, it does not occur in Kitty, where the previous selection stays highlighted until terminal is clicked with mouse button 1.

Attached screen recording where the primary content change when typing Space char.
https://user-images.githubusercontent.com/16114677/164992610-e16a0164-a88c-4350-9edd-3b9b6f386772.mp4

### System

OS: Linux
Version: alacritty 0.10.1 (2844606d)
Wayland + sway

**Comment by chrisduerr** [comment]
Fixed in master.
