### ISSUE TITLE
输入中文的时候，按退格键会删除已输入的内容。对比其他terminal，是因为hhh这三个字符没有显示在屏幕里边。

### ISSUE THREAD

**Issue by echozhangxiaomin** [alacritty/alacritty#6025]
![image](https://user-images.githubusercontent.com/86400430/165217207-b605013a-db25-420c-a177-5239b2ff86f6.png)

**Comment by chrisduerr** [comment]
Improvements to IME are currently work in progress, I'd assume that's your issue. Also please english.
