### ISSUE TITLE
Not working as External Term - VSCode

### ISSUE THREAD

**Issue by syepes** [alacritty/alacritty#6027]
I am trying to make Alacritty work as my external terminal on VSCode but its simply just not opening the terminal.

Has anyone managed to make this work?
It would also be great that it open in the current working directory as with the other terminals

### Tried VSCode Settings:

"terminal.external.osxExec": "Alacritty",
"terminal.external.osxExec": "open -nb io.alacritty"
"terminal.external.osxExec": "Alacritty --working-directory .",

### System

OS: `macOS` M1
Version: `alacritty 0.10.1 (2844606)`
VSCode: `1.66.0 (Universal)`

**Comment by chrisduerr** [comment]
If Alacritty doesn't work outside of VSCode, this is the right place to ask. However it sounds like you're having issues with VSCode rather than Alacritty, which is not something I'm interested in offering support for.

**Comment by syepes** [comment]
@chrisduerr
Well in VSCode all other terminals that I have tested iTerm, Console and other work as expected.
It's just Alacritty that does not work, so this is not just an VSCode problem.

**Comment by xlsama** [comment]
@chrisduerr I also encountered this problem, I hope you can support this feature.

**Comment by chrisduerr** [comment]
Supporting external terminal emulators is a VSCode feature. There is exactly nothing that Alacritty should have to do for this.

If it's not working with a specific terminal emulator, please report it to VSCode.

**Comment by xlsama** [comment]
okay, thank you.
