### ISSUE TITLE
Character problem on Windows 10

### ISSUE THREAD

**Issue by mahdi7d1** [alacritty/alacritty#6032]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Windows 10
Version: 0.10.0

![Screenshot 2022-04-29 062930](https://user-images.githubusercontent.com/40329167/165874614-ec874dbf-d3bd-4428-9ba0-d69f2a132b6c.png)

The problem should be obvious. Alacritty is showing rectangles instead of characters and I don't have any Idea why would it do that.

**Comment by chrisduerr** [comment]
Which GPU? That usually happens when your GPU doesn't support OpenGL 3.3+. However the latest Alacritty does support a GLES2 renderer, you could try manually switching to that.

**Comment by mahdi7d1** [comment]
I have an old Intel integrated one and yes it doesn't support OpenGL 3. How can I switch to this GLES2 renderer?

**Comment by kchibisov** [comment]
Try building master from source and starting it?
