### ISSUE TITLE
Beam cursor changes to Block after exit Neovim

### ISSUE THREAD

**Issue by asiryk** [alacritty/alacritty#6034]
I have Beam cursor for default mode [here is my config](https://github.com/asiryk/.dotfiles/blob/main/alacritty/.config/alacritty/alacritty.yml). When I open Neovim it changes to Block (as expected) and when I quit it, Alacritty doesn't change the cursor back to Beam.

### System

OS: macOS
Version: alacritty 0.10.1 (2844606)

![demo](https://user-images.githubusercontent.com/61456651/165945446-f6ad4257-e7c0-4509-8779-279b679004ae.gif)

**Comment by kchibisov** [comment]
Since nvim changes cursor nvim should change it back to whatever you're using. Consult neovim manual pages for that.

But I think you should add something like
```
au VimLeave * set guicursor=a:ver100
```
