### ISSUE TITLE
Unable to use IME in other windows after closing alacritty in GNOME wayland

### ISSUE THREAD

**Issue by q234rty** [alacritty/alacritty#6037]
OS: Linux
Version: alacritty 0.10.1 (2844606d)
GNOME Wayland 42 

This could be a mutter/gnome-shell bug and was reported in https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4776, however I can't reproduce this w/ any other text-input-v3 client I tried(namely `kitty`, `foot`, `supertuxkart` with `SDL_VIDEO_DRIVER=wayland` and gtk3&4 apps with `env -u GTK_IM_MODULE`), so reporting this here.

**Comment by kchibisov** [comment]
Could you try #5790 ?

**Comment by q234rty** [comment]
> Could you try #5790 ?

I tried that and the preedit text does appear as expected, but the bug is still there.

**Comment by q234rty** [comment]
Also apparently with that branch I can't input anything or even press enter after switching on and then switching off the IME

**Comment by kchibisov** [comment]
Could you provide `WAYLAND_DEBUG=1 alacritty --print-events` log from the branch I've linked?

**Comment by q234rty** [comment]
> Could you provide `WAYLAND_DEBUG=1 alacritty --print-events` log from the branch I've linked?

See [here](https://pb.nichi.co/hunt-issue-ozone)

**Comment by kchibisov** [comment]
>Also apparently with that branch I can't input anything or even press enter after switching on and then switching off the IME

How recent your GNOME is? I can't repro any of those issues on gnome on latest fedora...

**Comment by q234rty** [comment]
> > Also apparently with that branch I can't input anything or even press enter after switching on and then switching off the IME
> 
> How recent your GNOME is? I can't repro any of those issues on gnome on latest fedora...
GNOME 42.1. Repro'd with both fcitx5 and ibus. Also I should have been more clear: I can't input anything after using the IME to input a word, then switching off the IME, that is, switching back to English.

**Comment by kchibisov** [comment]
It's either a GNOME issue or fixed in latest rc.
