### ISSUE TITLE
Alacritty font size decreases when monitor disconnects 

### ISSUE THREAD

**Issue by Aziffo** [alacritty/alacritty#6040]
By executing the following command 'xrandr --output eDP-1 --off' when connecting my HDMI (HDMI-2) screen to the laptop (eDP-1) (for getting  2 individual screens), once the screen turned off, I proceed to open alacritty terminal and the font size looks smaller, without even changing in the alacritty.yml.

Before:
![image](https://user-images.githubusercontent.com/54035051/166568200-702a4b72-e7e1-4c77-a088-eb96c172dc45.png)

After executing the previous command:
![image](https://user-images.githubusercontent.com/54035051/166567941-43e15182-a007-4286-a3f8-efe2bf3c0a74.png)

### System

OS: Linux (arch)
Version: alacritty 0.11.0-dev (ad3ebba5)
Linux/BSD: X11

### Logs

Crashes: -
Font/Terminal size: [`alacritty -vv`](https://gist.github.com/Aziffo/cc2aba7d1e19f16c464dc9e3c3763fe3)
Keyboard and bindings: -

**Comment by chrisduerr** [comment]
Could you share the `alacritty --print-events` log for an instance where this issue has been encountered?

**Comment by Aziffo** [comment]
Nenvermind, aftera deeper search, I found out I didn't have the proper scale factor in the alacritty config `WINIT_X11_SCALE_FACTOR: "1.36"`
