### ISSUE TITLE
Set different opacity / colors on focused window [enhancement]

### ISSUE THREAD

**Issue by Alex23rodriguez** [alacritty/alacritty#6044]
working with `window: decorations` set to `none` / `buttonless` mode is great to give the workspace a clean look, especially when working with a tiled window manager (I'm using Amethyst on MacOS), but it can be pretty hard to recognise the focused window only by the cursor (hollow when unfocused, block when focused). 

It would be great to be able to set in the configuration an `window: unfocused_opacity`  with a default value of taking the same value as `window: opacity`, but being able to specify a different float to easily recognise the focused window. Colors would work in the same way.

**Comment by kchibisov** [comment]
In general, tiled window managers draw border around the window with accent color, not sure amethyst can do that on macOS, but yabai did in the past.

There's no intention to support changing either background color, nor opacity on the fly.
