### ISSUE TITLE
Neovim statusline breaks

### ISSUE THREAD

**Issue by tusharsingh09** [alacritty/alacritty#6049]
The bugs appears upon startup, changing the theme again and again solves it but it gets quite tedious. Example:
![image](https://user-images.githubusercontent.com/81076342/167295210-d3d022d5-6a26-4d2d-b0dc-396ae8bfedde.png)

Expected (after refresh):
![image](https://user-images.githubusercontent.com/81076342/167295229-5514dca3-68a6-43bc-8567-efbbb141993d.png)

And sometimes the theme breaks:
![image](https://user-images.githubusercontent.com/81076342/167295335-4916e625-0d93-4f55-9d3b-099a8bb2e0a5.png)

This issue has never been observed by me on Command Prompt and Windows Powershell

### System

OS: Windows 11 Pro
Version: 0.10.1 (2844606)

**Comment by chrisduerr** [comment]
Can you reproduce this on Linux?

**Comment by tusharsingh09** [comment]
I currently don't have any Linux systems and wsl's installation failed. I think I should try to reproduce this on Vim and see if it's really related to Alacritty or Neovim

**Comment by chrisduerr** [comment]
This is almost certainly an issue due to Windows' PTY or the `TERM` you're using. So while there might be workarounds for you to fix it on your end, it's not an Alacritty issue.

**Comment by trev-dev** [comment]
I just wanna pop in here and state that out of the box, Alacritty is shredding up in Windows native and Windows native vim.  I'm not sure how this would be a TERM issue for me but it's down right wonky. Are there clarifying documents for windows usage somewhere?
