### ISSUE TITLE
How to delay `-e cmd` execution until alacritty is launched and properly resized?

### ISSUE THREAD

**Issue by hehelego** [alacritty/alacritty#6050]
Hey, guys, I am launching neovim inside a new instance of alacritty with `alacritty -e nvim`.
However, I found that neovim isn't properly resized, causing problematic display.

Searching through the Internet, I found that xterm provides a `-wf` option to resolve this problem. See [xterm man page on freedesktop.org](https://www.x.org/releases/X11R6.7.0/doc/xterm.1.html).  
The command `xterm -wf -e vim` can be used to prevent the problem.  
I am wondering how to achieve that with `alacritty`.  

Thanks.

--------------------------

### System

OS: Linux  
Distro: Arch  
Version: `0.10.1 (2844606d)`  
Linux/BSD: X11 i3wm  

How to reproduce:

```
# create a vertically spliting container
Mod+v
# start a terminal emulator
Mod+Enter
# start another alacritty instance, run nvim command inside it.
alacritty -e nvim
```

--------------------------

Alacritty has been my default terminal emulator since I switched to arch linux, thanks for providing such a awesome software.

**Comment by hehelego** [comment]
With the help from friends in `archlinux-cn` telegram group, I have come up with a work-around.  

- instead of `alacritty -e nvim`, try `alacritty -e fish -c nvim`
- after nvim started, run `pkill -WINCH nvim` to send a window resized signal.

**note** This might be related with some bug in neovim.

**Comment by chrisduerr** [comment]
It's also possible to add a simple `sleep` before launching nvim. Usually just `sleep .1` does the job without super significant startup delay.

**Comment by FelixKratz** [comment]
Hi there, I have the same problem and struggle to integrate the `sleep` command in my new window invocation.

I have tried this:
```bash
alacritty msg create-window -e "sleep 0.1 && $(which nvim) $*"
```
which failed spectacularly, saying: "Failed to spawn command ...: No such file or directory".

Am I missing something obvious, or is this even expected behavior?
Normally I would expect such statements to execute, is the quotation not resolved internally before passing to execve?

**Comment by kchibisov** [comment]
@FelixKratz you need shell if you want to use shell, since `&&` is a shell operator. So `sh -c` is required.

**Comment by mgoral** [comment]
Hello,

It's worth noting that this is Neovim bug: https://github.com/neovim/neovim/issues/11330. There are rather clever workarounds in nvim's issue tracker, possibly think better than unreliable sleeps.
