### ISSUE TITLE
Terminal not fully redrawing under certain conditions

### ISSUE THREAD

**Issue by someuser-blip2** [alacritty/alacritty#6051]
## System

OS: Arch Linux
Version: alacritty 0.11.0-dev (5c51d528)
Linux/BSD: xorg 30bpp (nvidia driver) and Awesome WM

## Problem

When minimizing and then unminimizing an alacritty terminal, or when switching to another window group and switching back to the original window group containing the alacritty terminal, the whole terminal is not redrawn, only the section next to the terminal cursor position is.

## Screenshots

***Correct terminal:***
![correct-terminal](https://user-images.githubusercontent.com/63172412/167594616-1be6b2d3-44ef-4189-b31a-efcaf39793ec.png)

***Not fully redrawn terminal:***
![not-fully-redrawn-terminal](https://user-images.githubusercontent.com/63172412/167594639-f5c7b87f-596b-444a-94d9-deb01d8add6d.png)

## Workaround

Causing an event that triggers a full terminal redraw, such as maximizing the window, changing the font size (Ctrl+'+' or Ctrl+'-'), etc., is needed to restore full terminal content.

**Comment by kchibisov** [comment]
That's actually interesting, could you repro on `v0.10.1`? Also are you using some X11 compositor, can you try running without it?

Also, under which circumstances it's happening that your window isn't fully redrawn? When the focus changes or when it becomes visible?

**Comment by someuser-blip2** [comment]
By the way, in case this might be relevant, the "non-redrawn" portion of the terminal "captures" what is under the terminal at the moment when the window is un-minimized, or the "virtual desktop" containing the terminal is made current.

That "captured" portion moves around with the terminal, until the terminal is minimized, or another "virtual desktop" is made current.

Example:
![image](https://user-images.githubusercontent.com/63172412/167685352-8ce39a13-93a2-4165-97d0-b99bb759d735.png)

**Comment by kchibisov** [comment]
If you run it like `alacritty -o debug.highlight_damage=true` is it working?

**Comment by someuser-blip2** [comment]
> If you run it like `alacritty -o debug.highlight_damage=true` is it working?

Yes it does:

![image](https://user-images.githubusercontent.com/63172412/167689911-2409d4b5-4472-4f3a-82b6-e4969867fadc.png)

**Comment by chrisduerr** [comment]
@kchibisov Sounds like `swap_buffers_with_damage_supported` is reported to work without it actually working? Do we need to disable this on X11?

**Comment by kchibisov** [comment]
>Sounds like swap_buffers_with_damage_supported is reported to work without it actually working? Do we need to disable this on X11?

That's strange, but I think it does work, but not in all cases? Since you can see cursor redrawn or something like that.

I knew that it works given that the driver is nvidia(EGL under the hood), but I have no clue how it's working with it and why, given that it basically sends data to compositor...

We can disable the extension all together on X11 if it matters, since it clearly will solve the issue, but it sounds like if we redraw on focus/minimize on X11 the issue will be solved as well (though, we can't hook to minimize/unminimize for now)?

**Comment by chrisduerr** [comment]
> We can disable the extension all together on X11 if it matters, since it clearly will solve the issue, but it sounds like if we redraw on focus/minimize on X11 the issue will be solved as well (though, we can't hook to minimize/unminimize for now)?

Actually now that you mention it, X11 should send the application expose events when restoring a minimized window, I'm pretty sure this translates to `Redraw` requests in winit/glutin. Do you know if we fully damage the window when this happens? It seems like we don't and we probably should.

So maybe just adding a `self.ctx.terminal.mark_fully_damaged()` to [here](https://github.com/alacritty/alacritty/blob/9bbb296d1dc4f72e845695f22e903bcc1d66d5a3/alacritty/src/event.rs#L1106) could do it?

@someuser-blip2 Could you check if the `--print-events` output contains a `RedrawRequested` event when you restore a minimized window?

**Comment by someuser-blip2** [comment]
> @someuser-blip2 Could you check if the --print-events output contains a RedrawRequested event when you restore a minimized window?

Without the 'highlight_damage' debug option ?

Yes:  `[13.204816141s] [INFO ] [alacritty] glutin event: RedrawRequested(WindowId(X(WindowId(75497474))))`

**Comment by chrisduerr** [comment]
That's the answer then I'd assume. We should force-redraw everything whenever receiving this event, but we do not.

**Comment by chrisduerr** [comment]
@someuser-blip2 Could you test that the following patch fixes this? Unfortunately I have no hardware to confirm it actually works.

```diff
diff --git a/alacritty/src/event.rs b/alacritty/src/event.rs
index 1db6e450..6114178d 100644
--- a/alacritty/src/event.rs
+++ b/alacritty/src/event.rs
@@ -1103,7 +1103,10 @@ impl input::Processor<EventProxy, ActionContext<'_, Notifier, EventProxy>> {
                 },
                 EventType::ConfigReload(_) | EventType::CreateWindow(_) => (),
             },
-            GlutinEvent::RedrawRequested(_) => *self.ctx.dirty = true,
+            GlutinEvent::RedrawRequested(_) => {
+                self.ctx.terminal.mark_fully_damaged();
+                *self.ctx.dirty = true;
+            }
             GlutinEvent::WindowEvent { event, .. } => {
                 match event {
                     WindowEvent::CloseRequested => self.ctx.terminal.exit(),
```

**Comment by someuser-blip2** [comment]
> Could you test that the following patch fixes this?

It fixes the issue for both the restoration of minimized windows and for screen switching (which I suppose indicates the latter is implemented using the former for this WM).

**Comment by someuser-blip2** [comment]
But there seems to be another condition that triggers the issue that is not fixed by this patch: from time to time, the same issue occurs when a window is maximized.

Unlike in the cases your patch fixed, it does not happen all the time.

But it does happen from time to time, and it can be consistently trigger it by maximizing/unmaximizing the window repeatedly enough times.

**Example screenshots**

*Incorrectly redrawn maximized window:*

![Incorrect redrawing](https://user-images.githubusercontent.com/63172412/168673108-28d42f57-dea7-41d7-8eda-601494c8c7b4.png)

*Correctly redrawn maximized window:*

![Correct redrawing](https://user-images.githubusercontent.com/63172412/168673174-d1cefc70-47cd-4171-b1ae-5e74f8fa823a.png)

*Unmaximized window:*

![Unmaximized](https://user-images.githubusercontent.com/63172412/168674061-e6ae9be0-2701-47e1-9cf5-893fc495d56e.png)

**Comment by someuser-blip2** [comment]
The issue can also be triggered by resizing the window: below a screenshot after the window was expanded to the right using a mouse drag (mouse button released).

As in the maximizing case, it does not happen all the time. But it happens much more often.

![resized window](https://user-images.githubusercontent.com/63172412/168680335-3d8b954d-f449-4c36-9601-b042c8b65565.png)
:

**Comment by someuser-blip2** [comment]
Last case I noticed: incorrect redraw after closing a tmux pane.

For example, after closing a pane, I could get this:

![image](https://user-images.githubusercontent.com/63172412/168683805-e4a1e1f1-df14-4a67-a837-0f1e46ecf59b.png)

instead of this:

![image](https://user-images.githubusercontent.com/63172412/168683990-4620f60d-83c3-46a9-89fa-041c57441f1e.png)

**Comment by kchibisov** [comment]
If you run with `alacritty -o debug.highlight_damage=true` do you see pink rectangles covering non-damaged regions with tmux?

**Comment by someuser-blip2** [comment]
> If you run with alacritty -o debug.highlight_damage=true do you see pink rectangles covering non-damaged regions with tmux?

I am not sure what should be considered damaged or non-damaged in the context of tmux, but I can describe what I see in this way:

- after doing a pane operation (creating a new pane, resizing, closing, etc.), sometimes the whole terminal is marked as pink, sometimes it is only briefly fully marked as pink, and then only the cursor regions and other updating regions of panes (e.g. continuously changing regions of an htop output) are marked with pink rectangles.

- when doing a display modifying operation in a pane (e.g. running an 'ls') while nothing is going on in another pane, sometimes only the affected pane has pink rectangles where one could expect some to be, sometimes the whole terminal is pink, including non-changing panes.

As a note, issues related to maximizing and resizing occur with or without running tmux in the terminal.

And all the issues disappear when `debug.highlight_damage` is set.

**Comment by kchibisov** [comment]
Yeah, that's expected that `debug.highlight_damage` will resolve the issue. As far as I can see there's a frame with the whole terminal marked as pinked, which could mean that there's something different going on with X11 damage thingy.

**Comment by chrisduerr** [comment]
It makes sense to me that a maximize would require full damage too, what I'm more confused about is that the tmux pane doesn't update damage correctly.

**Comment by kchibisov** [comment]
@chrisduerr it was stated that normal resizing doesn't get damaged as well. But we do damage the entire window on resize. So it seems like the state is buffered or something like that.

**Comment by chrisduerr** [comment]
I'm fine with just disabling damage tracking on X11 tbh, it's not something we expected to be broadly supported on X11 anyway. And macOS/Windows is probably going to be the same.

**Comment by kchibisov** [comment]
https://github.com/alacritty/alacritty/pull/6070 should fix it.

**Comment by someuser-blip2** [comment]
> #6070 should fix it.

It does.

Thank you

**Comment by someuser-blip2** [comment]
@kchibisov, @chrisduerr : an unrelated remark, I just want to thank you guys for this terminal emulator.

Both fast, and with excellent font rendering, especially when working with bold and/or italic faces:
![image](https://user-images.githubusercontent.com/63172412/169640067-2b3551af-10c2-48e7-abab-1c15b9245f81.png)

And now, one of the few terms that work well in 10bpc X11.

So thanks!
