### ISSUE TITLE
please add the ability to modify the cursor color

### ISSUE THREAD

**Issue by yourfriendyo** [alacritty/alacritty#6053]
Hopefully, please add the ability to modify the cursor color, because if the cursor color follows the foreground color, it is not easy to find the position of the current cursor, especially in the case of Vim syntax highlighting. 
Please see the image below, that I keep pressing the W key but because of syntax highlighting such as parentheses, I can't tell where the cursor is.
![](https://user-images.githubusercontent.com/78334412/167645447-6a1cb62b-cbcc-4dfe-9079-b769e6e0b660.gif)

**Comment by kchibisov** [comment]
I think you want this?

https://github.com/alacritty/alacritty/blob/5c51d528ea8ded63b127a4f17ee6136653db09b9/alacritty.yml#L207

Also, you can control cursor colors with escapes, for example, vim can do something like that with `guicursor` stuff.
