### ISSUE TITLE
Snap/Flatpak packing

### ISSUE THREAD

**Issue by lucasvsr** [alacritty/alacritty#6054]
Hello guys!

How about making Alacritty available as a flatpak or snap application? I believe that this way you will reach a larger base of Linux users.

**Comment by laur89** [comment]
It is available as a snap, but last updated June 2021: https://snapcraft.io/install/alacritty/debian#install

**Comment by chrisduerr** [comment]
The snap is completely broken and Canonical has ignored my takedown request for years now (I doubt anyone even reads those messages). I can only recommend to stay as far away as possible from snap and flatpak.

Alacritty ships source code and we happily support maintainers interested in bundling it for their distro. I will not be duplicating that work by becoming a maintainer myself.
