### ISSUE TITLE
Incorrect color rendering

### ISSUE THREAD

**Issue by parthkalgaonkar** [alacritty/alacritty#6056]
### System

OS: Linux
Version: alacritty 0.10.1 (2844606d)
Arch-Linux: X11, XMonad, No Compositor

### Config file
[alacritty.txt](https://github.com/alacritty/alacritty/files/8666846/alacritty.txt)
(renamed from alacrtitty.yml to attach here)

### Issue
The colors displayed in the terminal by using ANSI escape codes are different from the ones specified in the config file

For example displaying text using green with:
```bash
printf "\033[0;32m_hello_\033[0m\n"
```
gives output with rgb code `#B5BD68` instead of the `#a3be8c` as expected from the config file

### Notes
- Behavior is the same in both bash and zsh
- xterm (which pulls colors from .Xresources) displays colors accurately
- Displayed color code is determined by selecting the text in question and using [colorpicker](https://aur.archlinux.org/packages/colorpicker)<sup>AUR</sup>

**Comment by parthkalgaonkar** [comment]
[alacritty_mod.txt](https://github.com/alacritty/alacritty/files/8667113/alacritty_mod.txt)

Using this config file (with a modified color config) seems to work. But I have no idea why

**Comment by chrisduerr** [comment]
> But I have no idea why

Because your indentation's fucked. Unfortunately whitespace matters a lot in yaml. See the official config for reference.
