### ISSUE TITLE
MacOS paste of file should paste the full absolute path, rather than just the filename

### ISSUE THREAD

**Issue by Andrej-Marsic** [alacritty/alacritty#6058]
<img width="625" alt="image" src="https://user-images.githubusercontent.com/77627088/168047075-8a4f7510-2168-4632-ba75-a06644da0fbc.png">

When you press cmd+c on a file in say FInder and you paste it into the mac terminal, you get the full absolute path pasted. In alacritty, you only get the filename. 

Would it be possible to have the other option?

### System

OS: macOS
Version: alacritty 0.7.2 (5ac8060)

**Comment by eastmancr** [comment]
From a cursory glance, it seems like this is special behavior for the native terminal. When I try pasting from Finder into any other text field (TextEdit, Spotlight, Notes, Safari, etc.), only the file name is pasted. This image (Finder > Edit > Show Clipboard) shows that Finder only copies the file name:
![plaintext.png](https://user-images.githubusercontent.com/19430499/168403581-7bbc45d9-0921-45bf-b90a-a3e9ed4ede3f.png)
My guess is that Terminal.app can talk to Finder directly and ask for the full path name. A "workaround" is to just drag the file into Alacritty and it will type it out under the cursor.

**Comment by chrisduerr** [comment]
We just make use of the operating system's file drop implementation. If someone wants to get into that and figure out if it's possible to change that behavior, you should look into [winit](https://github.com/rust-windowing/winit).

**Comment by KeitaNakamura** [comment]
Simply using `ctrl+option+c` in Finder makes you happy:)
