### ISSUE TITLE
SpawnNewInstance should not pass --command (-e) argument

### ISSUE THREAD

**Issue by WebOfNakedFancies** [alacritty/alacritty#6060]
When alacritty is run with --command (-e) option, SpawnNewInstance is also passed this argument.

My specific use case was running "alacritty -e ranger", and I expected SpawnNewInstance to give me a terminal for the directory I am currently parsing. Instead, it launched a new alacritty instance with ranger running.
When I use ranger without invoking alacritty's --command option, it works as expected.

I don't know if there's some other use case benefiting from the current behavior.

I propose that it should be ignored like the --working-directory argument already is, as in the below code 

https://github.com/alacritty/alacritty/blob/9bbb296d1dc4f72e845695f22e903bcc1d66d5a3/alacritty/src/event.rs#L369-L372

**Comment by chrisduerr** [comment]
You're absolutely correct. In fact if you do `alacritty msg create-window`, it should already behave as you would expect. Apparently it's just the `SpawnNewInstance` action that doesn't behave as intended. So you can use the command as a work around until this is fixed.

**Comment by Alkeryn** [comment]
I just looked it up whilst switching from termite, nice to see someone opened the issue just 2 days ago !

**Comment by conraythefirst** [comment]
Is there any alternative way to spawn a new instance through a key binding that actually inherits the --command param?
I understand why it's unexpected behaviour for SpawnNewInstance but I grew to like it and made heavy use of it.
