### ISSUE TITLE
Alacritty history is shown on window resize

### ISSUE THREAD

**Issue by carterchannui** [alacritty/alacritty#6061]
### System

OS: macOS
Version: alacritty 0.10.0 (8a26dee)

When Alacritty's window is resized, the history of the shell is displayed. I'd expect the visible shell content prior to the window resize to be the only content visible after the window resize.

https://user-images.githubusercontent.com/26908609/168403793-cb97b7ff-624c-4f93-91aa-535eafd6f8b9.mov

**Comment by chrisduerr** [comment]
Working as intended.

**Comment by carterchannui** [comment]
Is there a way to disable this feature to maintain shell content on window resize?

**Comment by chrisduerr** [comment]
No.
