### ISSUE TITLE
warning: be sure to add `/home/user/.cargo/bin` to your PATH to be able to run the installed binaries

### ISSUE THREAD

**Issue by LaPlanta01** [alacritty/alacritty#6064]
OS: Ubuntu Linux
Version: `alacritty v0.10.1`
BSPWM

It seems like it's installed but it doesn't let me run the emulator. I have tried installing it by other ways but it is still the same.

**Comment by chrisduerr** [comment]
What error are you getting when you try to execute Alacritty? And did you add `~/.cargo/bin` to your `PATH`?

**Comment by LaPlanta01** [comment]
ERROR] [alacritty] Alacritty encountered an unrecoverable error:
                                                    
                                                    	Error creating GL context; eglInitialize failed
That's the error. That directory is already created, but i don't know what it means with my PATH. I'm a bit new in all of this.

**Comment by chrisduerr** [comment]
Try installing the latest master, if you used `cargo` you can do so using `cargo install --git https://github.com/alacritty/alacritty`.

**Comment by jim-obrien-orig** [comment]
The cargo command worked for me. Unfortunately the snap latest available version on any channel is 0.8.0 which doesn't work on Ubuntu 21.10

**Comment by chrisduerr** [comment]
Don't use the snap.
