### ISSUE TITLE
[Feature request] Ability to randomize color hue on every new window

### ISSUE THREAD

**Issue by ashleysommer** [alacritty/alacritty#6067]
This is my favourite feature of the KDE terminal `konsole`, and I'd love to see it implemented in Alacritty.

It works by converting the foreground color into HSV (Hue/Saturation/Brightness). It leaves the Brightness as-is, rotates the Hue by a random amount and adjusts the saturation by a random amount. Then converts the HSV back to RGB.

It then rotates the background color hue and adjusts the background saturation by the same amount.

I understand the Alacritty project tends to avoid implementing unneeded flashy features from other Terminals, thought I'd post this regardless as it seems relatively easy to implement.

**Comment by chrisduerr** [comment]
Just pass the background color to Alacritty through the CLI flag.

**Comment by kchibisov** [comment]
Yeah, that or just use escape sequences, they persist across the resets.

**Comment by ashleysommer** [comment]
@chrisduerr 
> Just pass the background color to Alacritty through the CLI flag.

Is it possible to do that when using `alacritty msg create-window` to create a new window with a different color?


@kchibisov 
> Yeah, that or just use escape sequences, they persist across the resets.

Can you describe in more detail this solution please? How would I use escape sequences to adjust the foreground and background colour by a random amount on the creation of each new window?

**Comment by kchibisov** [comment]
>Can you describe in more detail this solution please? How would I use escape sequences to adjust the foreground and background colour by a random amount on the creation of each new window?

You put escape sequence into your shell init.
`printf "\e]10;#ff00ff\007"` - for foreground.
`printf "\e]11;#ff00ff\007"` - for background.

**Comment by ashleysommer** [comment]
Note, for anyone else wanting this feature, I've implemented it in a simple bash script, you can find it here: https://gist.github.com/ashleysommer/9550cba6989c96076897234a14367f9e

**Comment by chrisduerr** [comment]
> If anyone wondering "why would you even want to do that?", just look how cool it is:

I'll be honest, that picture didn't really answer the question for me.
