### ISSUE TITLE
Cannot install alacritty; gets stuck on build

### ISSUE THREAD

**Issue by Waddles6272** [alacritty/alacritty#6077]
I've been following the install documentation and it's been going smoothly, however then I hit the "cargo build --release" and I get "error: no override and no default toolchain set" and I can't find anything on how to fix or workaround this. I've followed all the instructions, I'm using Arch Linux and am in i3 if that helps.

**Comment by chrisduerr** [comment]
If you want to build from source, you need to install Rust. How that is done you can probably find out in more Rust-specific places.
