### ISSUE TITLE
If you want to build from source, you need to install Rust. How that is done you can probably find out in more Rust-specific places.

### ISSUE THREAD

**Issue by Waddles6272** [alacritty/alacritty#6078]
If you want to build from source, you need to install Rust. How that is done you can probably find out in more Rust-specific places.

_Originally posted by @chrisduerr in https://github.com/alacritty/alacritty/issues/6077#issuecomment-1133882807_

I've been following the install documentation and it's been going smoothly, however then I hit the "cargo build --release" and I get "error: no override and no default toolchain set" and I can't find anything on how to fix or workaround this. I've followed all the instructions, I'm using Arch Linux and am in i3 if that helps.

This person closed me out of the issue I said I was having. I have Rust installed per the installation documention, but I still have the issue of it saying "error: no override and no default toolchain set" when running "cargo build --release". Please don't close this ticket whoever comes along in case this issue continues not to be resolved. I'm just trying to figure this out and am hoping to get some help. Thank you!

**Comment by kchibisov** [comment]
>I'm using Arch Linux and am in i3 if that helps.

Given that you're on arch the terminal should be packaged there, so `pacman -S alacritty`.

Besides your error, are you using `rustup` or you're using system installed rust? In case you're using system installed rust, ensure that you don't have `$HOME/.cargo`(try removing it).
