### ISSUE TITLE
2 cell wide character takes up single cell

### ISSUE THREAD

**Issue by Mango0x45** [alacritty/alacritty#6080]
### System

OS: Linux
Version: 0.10.1 (2844606d)
WM: Sway

### Issue

I am currently using alacritty with the Iosevka font. The experience is for the most part perfect, except for issues I have come across with the em-dash character (—). This character *should* take up 2 cells in the terminal, but instead only takes up a single cell. This causes issues as it interferes with the following character, and is very noticeable when reading manual pages formatted with mdoc.

![image](https://user-images.githubusercontent.com/57815710/169837591-5ad9a18c-18b5-462b-8d0e-dccc45e2f4a2.png)
![image](https://user-images.githubusercontent.com/57815710/169837769-27c009d8-a9f5-4e15-a4e7-9c570ea7cac7.png)

**Comment by kchibisov** [comment]
@Mango0x45 it's likely missing in your font, so the one from proportional is being taken. For me this character is having width 1 according to wcwidth and renders into one cell.

![picture](https://user-images.githubusercontent.com/27620401/169838981-fd55d516-339f-4769-806a-bb14994e580f.png)

**Comment by Mango0x45** [comment]
How can I go about fixing this issue?
