### ISSUE TITLE
Alacritty doesn't exit with same exit code as executed command

### ISSUE THREAD

**Issue by ClashTheBunny** [alacritty/alacritty#6081]
Actual behavior:
```
$ bash -c 'exit 1'; echo $?
1
$ alacritty -e bash -c 'exit 1'; echo $?
0
```

Expected behavior:
```
$ bash -c 'exit 1'; echo $?
1
$ alacritty -e bash -c 'exit 1'; echo $?
1
```

### System

OS: Linux
Version: alacritty 0.11.0-dev (e319ca93)
Linux/BSD: Wayland/Sway

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by kchibisov** [comment]
Also, none of the terminal emulators I've tried(vte/kitty) do something like that, so it'll be even more questionable.

**Comment by thetrompf** [comment]
@ClashTheBunny why do you expect an terminal emulator to propagate the exit code from the shell or a command. The terminal emulator has done its job correctly, it has succesfully run a command - the command has failed, but it is not the terminal emulators job to propagate it. It is the job of a shell like zsh,bash,csh,sh etc.

![image](https://user-images.githubusercontent.com/1430118/169891659-dc31d222-3c8a-4798-ad11-ff40806191bb.png)
![image](https://user-images.githubusercontent.com/1430118/169891730-7371df06-1fc9-4acf-bac3-7890c18609ef.png)

**Comment by ClashTheBunny** [comment]
I totally agree with both counter points.  I'm not sure if this is logical or possible. Especially multiple windows sounds like a place where this wouldn't make sense.

The reason I opened the issue is that exit codes are like an exception in my mental model.  You often will bubble them up until you catch it or you end up at the user's interaction point.

Here's an example of bash successfully running bash, but the "exception" bubbling up still:
```
$ bash -c "bash -c 'exit 1'"; echo $?
1
```

The specific use case I was trying to use it for was how do I execute an interactive command line script from a graphical situation without recreating the terminal interaction.  Something like how askpass and pinentry has to recreate a new version for each platform that it's running on:

```
apt-cache search "pinentry|askpass" | grep -v dbg
ksshaskpass - interactively prompt users for a passphrase for ssh-add
lxqt-openssh-askpass - OpenSSH user/password GUI dialog for LXQt
lxqt-openssh-askpass-l10n - Language package for lxqt-openssh-askpass
openpgp-applet - GNOME applet for OpenPGP text encryption
pinentry-curses - curses-based PIN or pass-phrase entry dialog for GnuPG
pinentry-doc - documentation for pinentry packages
pinentry-fltk - FLTK-based PIN or pass-phrase entry dialog for GnuPG
pinentry-gnome3 - GNOME 3 PIN or pass-phrase entry dialog for GnuPG
pinentry-gtk2 - GTK+-2-based PIN or pass-phrase entry dialog for GnuPG
pinentry-qt - Qt-based PIN or pass-phrase entry dialog for GnuPG
pinentry-tty - minimal dumb-terminal PIN or pass-phrase entry for GnuPG
pinentry-x2go - OpenPGP (smart)card authentication dialog window for X2Go Client
r-cran-askpass - safe password entry for GNU R, Git, and SSH
ssh-askpass - under X, asks user for a passphrase for ssh-add
ssh-askpass-fullscreen - Under Gnome2, asks user for a passphrase for ssh-add
ssh-askpass-gnome - under X, asks user for a passphrase for ssh-add
```
I was specifically trying to so something like:

```
ssh-add -l | grep -q keyname || alacritty -e ssh-add ~/.ssh/keyname_id_rsa
```

But realized that I didn't get the return from alacritty, so I have to then recheck if the keyname was added, which slowly becomes more complicated (but doable!).

Thanks for taking the time to look at this, and feel free to close it if it seems to be a foolish thing I'm doing.  It just seemed to be different than I expected, so I wanted to make sure it wasn't possible/wanted before I brush it off as me just holding it wrong.

**Comment by chrisduerr** [comment]
> And in case of multiple windows what the exit code should be? The exit code of the last closed window, which will lead to closing the instance?

Error is another case that is completely muddied by this. If an exit code is != 0, did Alacritty fail? Did the command fail? Did both fail? There's no way to know.

I think it wouldn't be a good idea to implement this feature.

**Comment by benaryorg** [comment]
Just a quick note on this rather old issue: hitting Ctrl+C in an open window and the command subsequently being terminated will still cause *Alacritty* to return 0.
If using any terminal emulator (*xterm* does the same btw) to run a CLI command while also showing something to the user (like running *rsync* or something with a progress bar for a long copy), then any user-initiated abort will be incredibly hard to code around for shell scripts and the like.

> Error is another case that is completely muddied by this. If an exit code is != 0, did Alacritty fail? Did the command fail? Did both fail? There's no way to know.

The purpose of the status code is to know that *something* failed.
When running a shell script then a non-zero return code can indicate:

- the shell script is not executable
- the shell specified in the shebang wasn't found
- the shell couldn't read the script
- the script itself exited with a non-zero code

The shell doesn't just return 0 if it managed to run the script because that'd be a fundamentally bad way to handle errors.
I don't see why *Alacritty* should be in the business of hiding error codes.
