### ISSUE TITLE
Newlines do not go to beginning of line.

### ISSUE THREAD

**Issue by Finxx1** [alacritty/alacritty#6086]
### System

OS: Arch Linux AND macOS
Version: `0.10.1`
Linux WM: i3
macOS WM: Aqua & Quartz
Shell: Zsh

### Issue

Whenever running commands that do not output a newline at the end, sometimes the terminal bugs out and does not go to the beginning of the line after a newline. Examples:
```
finxx > alacritty --version
alacritty 0.10.1 (2844606d)
                           %
```

```
finxx > printf "asd\nasd\nasd\n"
asd
   asd
      asd
         %
```
Looking on the internet yields no results even though this problem has persisted on different computers. Maybe I am not using correct search terms?

**Comment by chrisduerr** [comment]
This is an issue with your system, likely related to `TERM` or your `PS1`.
