### ISSUE TITLE
There is any way to add relative number option on vim mode?

### ISSUE THREAD

**Issue by gabrielknot** [alacritty/alacritty#6087]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux/BSD/macOS/Windows
Version: `alacritty --version` output
Linux/BSD: X11/Wayland, DE or Compositor and WM

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by chrisduerr** [comment]
Alacritty tries to provide as little UI as possible, as such no line numbers are provided at all and that includes relative line numbers. Since it's not possible to chain jumps like in vim, that would also be relatively useless. So this is not something that is planned.

**Comment by gabrielknot** [comment]
Thanks!
