### ISSUE TITLE
An example of using `command` when binding keys would be helpful in the default config

### ISSUE THREAD

**Issue by thor314** [alacritty/alacritty#6089]
I've been working on binding the `zellij` multiplexer to a key unsuccessfully; I've tried some permutations of this with different options:
```
  - { key: S, mods: Shift|Control, command: { program: "zellij" } }
  # and
   - { key: S, mods: Shift|Control, command: { program: "zellij", args: [""] } }
   - { key: S, mods: Shift|Control, command: { program: "zellij", args: [] } }
```

The visual bell dings for the first, so I'm confident that's wrong, but neither of the others work. Examples would be helpful in the default config.

### System

OS: Linux Ubuntu
Version: `alacritty --version` output
0.10.1 ()
Linux/BSD: X11

### Logs
Crashes: STDERR, STDOUT
Keyboard and bindings: `alacritty --print-events`

**Comment by chrisduerr** [comment]
There is an example in the config's documentation.

**Comment by lefuturiste** [comment]
Was this feature removed?

**Comment by chrisduerr** [comment]
It was not.
