### ISSUE TITLE
vim has no color using the env:  TERM: alacritty configuration

### ISSUE THREAD

**Issue by Arrow-x** [alacritty/alacritty#6091]
If you comment out  TERM or is set to 'alacritty' no color at all in vim when set termguicolors is on
![image](https://user-images.githubusercontent.com/3308421/170889251-a717183b-52d0-4218-a1e4-8ccc567bc373.png)
when termguicolors is commented out 
![image](https://user-images.githubusercontent.com/3308421/170889356-1a85902a-e27e-429d-b8d0-6b7f8e5d4455.png)
this is how it should look like (in kitty) with termguicolors on
![image](https://user-images.githubusercontent.com/3308421/170889409-58cbeb85-4072-46d4-8718-bcb737316e45.png)
and finally this is with termguicolor on and TERM: xterm-256color (notice there is no redline under todos
![image](https://user-images.githubusercontent.com/3308421/170889512-56e787e7-b80f-4ff4-8d21-43d9777062f0.png)

### System

OS: Linux
Version: `alacritty 0.10.1 ()`
Linux: X11, i3gaps, picom

**Comment by Arrow-x** [comment]
Neovim works perfectly with the defaults

**Comment by chrisduerr** [comment]
Working as expected, this is an issue with Vim, not Alacritty.
