### ISSUE TITLE
Jitter behavior when moving

### ISSUE THREAD

**Issue by askfiy** [alacritty/alacritty#6092]
In neovim, the afterimage behavior may occur when moving the cursor rapidly.

Just like in the video, it's sad ..

https://user-images.githubusercontent.com/81478335/170928829-ecc1aef5-d695-44e5-b122-b4d00893ca1f.mp4

Here is some of my information:

```
neovim 0.7

Manjaro

kernel： 5.15.41

alacritty 0.11.0-dev (63ef6c93)

family: "agave Nerd Font"

dwm

zsh
```

**Comment by chrisduerr** [comment]
Working as intended. Neovim submits data without explicit synchronization, thus it will cause partial redraws.

**Comment by askfiy** [comment]
Is there any way to make it look better?
