### ISSUE TITLE
run a command with double quote in new window in Alacritty

### ISSUE THREAD

**Issue by blueray453** [alacritty/alacritty#6093]
I can run 

    gnome-terminal  -- journalctl --since "10min ago" -f

What is the equivalent of this command for alacitty.

I tried

    alacritty -e "journalctl --since \"10min ago\" -f"
    alacritty -e "journalctl --since '10min ago' -f"
    alacritty -e 'journalctl --since "10min ago" -f'

every command returns

    Error: Failed to spawn command 'journalctl --since '10min ago' -f': No such file or directory (os error 2)

**Comment by chrisduerr** [comment]
```
alacritty -e journalctl --since "10 min ago" -f
```
