### ISSUE TITLE
ugly alacritty with default ubuntu 22.04 window manager

### ISSUE THREAD

**Issue by rotten** [alacritty/alacritty#6094]
### System

OS: Ubuntu 22.04 LTS
Version: alacritty 0.11.0-dev (63ef6c93)
Linux/BSD: "Ubuntu" and "Ubuntu on xorg"

### Description of the issue:

When I use the default Ubuntu 22.04 display manager (which I think is wayland - it doesn't say on the login screen) Alacritty comes up with a generic window frame that completely ignores the system theme.  
![ugly_alacritty](https://user-images.githubusercontent.com/717719/171275964-45821f73-1dc1-4e44-b2ff-1be33466e12f.png)

When I switch to "Ubuntu with xorg", I get a nice, appropriately themed window.
![attractive_alacritty](https://user-images.githubusercontent.com/717719/171275983-eccd20ee-8a39-441e-93fa-cff03032eb1a.png)

Is there a way to make it work with both of the out-of-the-box display managers?

**Comment by kchibisov** [comment]
>Is there a way to make it work with both of the out-of-the-box display managers?

No, that's a gnome choice to do so, but you can try https://github.com/alacritty/alacritty/pull/6079, maybe you'll like it better, thought it won't be the same as gtk, since we're not gtk.

**Comment by rotten** [comment]
Thanks, it was worth a try.  Unfortunately Alacritty is unchanged under the default ubuntu display manager.  It still works well on the xorg version though.

**Comment by Titaniumtown** [comment]
#6079 seems to actually fix the titlebar, fantastic!

**Comment by kchibisov** [comment]
Well it's not a fix in particular, just we used something that looks similar to GTK, but not GTK.
