### ISSUE TITLE
Alacritty causing 1-2 mins of busy cursor on i3 desktop (re-opening #868)

### ISSUE THREAD

**Issue by stephen-huan** [alacritty/alacritty#6097]
### System

OS: archlinux
Version: alacritty 0.10.1 ()
Linux/BSD: X11, no DE, compositor picom, WM i3-gaps

Like in #868, opening a new alacritty window causes the cursor to appear "busy" for the next 60 seconds.
This is because the default i3 config looks like:
```shell
bindsym $mod+Return exec i3-sensible-terminal
```
If the `--no-startup-id` flag was added to the previous command:
```shell
bindsym $mod+Return exec --no-startup-id i3-sensible-terminal
```
then the issue goes away.

According to the [i3 user guide](https://i3wm.org/docs/userguide.html#exec), i3 receives a notification from "most" applications once they finish starting. Once this notification is received, the cursor changes from busy to normal. Because alacritty "is not startup-notification aware", the cursor only returns to normal after a timeout period of 60 seconds. 

The reason why adding `--no-startup-id` and suppressing startup notifications for alacritty entirely is not ideal is that startup notifications allow i3 to "make sure that a window appears on the workspace on which you used the exec command".

**Comment by chrisduerr** [comment]
> The reason why adding --no-startup-id and suppressing startup notifications for alacritty entirely is not ideal is that startup notifications allow i3 to "make sure that a window appears on the workspace on which you used the exec command".

Has Alacritty ever not appeared in the workspace which you used the exec command from for you?

**Comment by stephen-huan** [comment]
No, but I mention it to showcase that there may be non-cosmetic side effects to not being startup-notification aware.
