### ISSUE TITLE
error: linker `cc` not found

### ISSUE THREAD

**Issue by rogue-agent** [alacritty/alacritty#6099]
Running; errors at linker cc, which is not found.
 `cargo build --release --no-default-features --features=wayland`

### System

OS: SK Arch Linux 0.5.4
Version: ` wz@hakkah  ~  alacritty -- version
zsh: command not found: alacritty`
Linux/BSD: Wayland

### Logs

` ✘ wz@hakkah  ~/alacritty   master  cargo build --release --no-default-features --features=wayland
   Compiling proc-macro2 v1.0.36
   Compiling libc v0.2.112
   Compiling syn v1.0.84
   Compiling pkg-config v0.3.24
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `syn` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `libc` due to previous error
error: could not compile `proc-macro2` due to previous error`

![image](https://user-images.githubusercontent.com/9405663/171456977-3e0c60e5-4554-4fdc-ae55-48ad384ff1e3.png)

**Comment by chrisduerr** [comment]
Install `gcc`.
