### ISSUE TITLE
Feature request, no borders but title bar

### ISSUE THREAD

**Issue by rogue-agent** [alacritty/alacritty#6100]
Hello world,

requesting a feature that virtually every program and application has across all platforms. 

Here you can see GTK themed files and Firefox having no borders except for a thin 1-2px black line to contrast Alacritty's thicc '95 border. Can you please make this a setting in the yml to be configured.
![image](https://user-images.githubusercontent.com/9405663/171482462-846177a7-18e9-480b-ac02-52e97964b69c.png)

**Comment by rogue-agent** [comment]
Configurable to the point that there i none. Something like
Border:
1px, 5px, none

**Comment by kchibisov** [comment]
I don't want to add a configurable option for border, etc just for wayland.

You can try #6079 and see if it fixes your problems. It should look more like gtk, but it's not gtk.
