### ISSUE TITLE
Specify the first command(s) ran when opening a new alacritty instance.

### ISSUE THREAD

**Issue by iago-lito** [alacritty/alacritty#6107]
Following https://github.com/alacritty/alacritty/issues/1672#issuecomment-850914311, I would make a good use of some simple `-c` argument to `alacritty` command, to get a fine-grained control over the initialization of my various terminal instances.

`alacritty -c "cd /to/that/folder && ./make-it-ready && echo 'Hello, welcome to the terminal in that folder.'"`

To work around the absence of `-c` now, I either:
- craft a dummy `.alacritty-temp` file with `sed` *etc.* to fiddle with `shell.args` option and then `alacritty --config-file .alacritty-temp`
- use a tmuxed session just for sending one single line to the new instance.

None of these feel comfy.. unless you have a better workaround? :)

**Comment by chrisduerr** [comment]
If you want Alacritty to start a shell, start a shell. `-c` doesn't imply an automatic shell, so `&&` isn't valid and if you quote everything the entire first argument will be used as executable.

**Comment by iago-lito** [comment]
Oh, sorry for the misunderstanding. I didn't even know it was possible for a terminal to run *without* a shell started. Based on your comment, I eventually succeded with something along

    alacritty -e zsh -c 'cd /to/that/folder && ./make-it-ready && zsh'
