### ISSUE TITLE
Alacritty won't start up on OpenBSD anymore

### ISSUE THREAD

**Issue by AaronM04** [alacritty/alacritty#6114]
I had to recompile alacritty after updating to a new OpenBSD snapshot, and now it won't start. See logs below.

### System

OS: OpenBSD -CURRENT
Version: alacritty 0.10.1
Linux/BSD: X11 (Xenocara)

### Logs

```
libGL error: MESA-LOADER: failed to retrieve device information
Error: There was an error initializing the shaders: Failed compiling shader: 0:1(10): error: GLSL
3.30 is not supported. Supported versions are: 1.10, and 1.20
```

**Comment by chrisduerr** [comment]
You make it sound like it worked previously, but the logs seem to indicate that your GPU doesn't support OpenGL 3.3+, which is required for Alacritty 0.10.1. Did it work for you previously?

**Comment by AaronM04** [comment]
It did work for me previously (v0.9.0 though). I then tried to install v0.9.0 and it had a similar error.

**Comment by kchibisov** [comment]
What GPU do you have @AaronM04? It might used software rendering or something like that on your particular system. If you you want to get hw accelerated context, try running the latest master.

**Comment by AaronM04** [comment]
@kchibisov I have an Intel one.

I'll try the master branch. Thanks!

**Comment by kchibisov** [comment]
>I have an Intel one.

I was mostly asking about which one in particular? Like `Core i5-2500K`.

**Comment by chrisduerr** [comment]
Pretty sure HD 5500 should support OpenGL 3.3+, but I'd still recommend just testing master.

**Comment by AaronM04** [comment]
@kchibisov @chrisduerr after pulling the master branch and running `cargo install --path .`, alacritty runs normally. Thank you so much!

For the record, previously, I was trying `cargo install alacritty` (with or without a version choice) and that displayed the OpenGL error I pasted above.
