### ISSUE TITLE
Ending whitespace is initially wrapped on multiple lines, but not after window resize

### ISSUE THREAD

**Issue by howabouthis** [alacritty/alacritty#6118]
When at first printing a line with whitespace padding at the end that doesn't fit the window width, the line is wrapped like normal text would.

However, once you resize the window to a larger size, and resize the window back to the original size, the whitespace is no longer wrapped.

The expected behavior would be to not wrap the ending whitespace in the first place, if all non-whitespace characters can be fit in the window.

![whitespace-wrapping](https://user-images.githubusercontent.com/25056896/172330978-b1415480-7145-4ea1-902c-1f7af506dd74.gif)

### System

OS: Linux/Manjaro
Version: alacritty 0.10.1 (2844606d)
Using X11, xmonad

**Comment by chrisduerr** [comment]
This is expected behavior.
