### ISSUE TITLE
[Feature request] Accept path argument

### ISSUE THREAD

**Issue by eugene-bright** [alacritty/alacritty#6119]
### System

OS: Debian GNU/Linux bookworm/sid
Version: `alacritty 0.8.0`
Linux/BSD: Gnome Shell, XDG_SESSION_TYPE=x11

### Expected behavior

```bash
usr@local:~$ alacritty /tmp

# New terminal opened
use@local:/tmp$ 
```

### Actual behavior

```bash
usr@local:~$ alacritty /tmp
error: Found argument '/tmp' which wasn't expected, or isn't valid in this context
```

### Extra comments

I like the way it's done in `kitty`, it plays nicely with [nnn] open command.

[nnn]: https://github.com/jarun/nnn

**Comment by kchibisov** [comment]
I think it was brought in the past and we rejected such thing. I still think that it's not something we'd like.

You can achieve what you want with `--working-directory`. And you can wrap `alacritty --working-directory $@` in a script so it'll have semantics you expect with `alacritty /tmp`.

**Comment by chrisduerr** [comment]
Having paths as subcommand-like argument is definitely not something we want. There's really no advantage to that.

**Comment by eugene-bright** [comment]
```
$ cat .local/bin/a
#!/usr/bin/env bash

alacritty --working-directory "$1"
```
