### ISSUE TITLE
Image preview with ueberzug and w3m does not work

### ISSUE THREAD

**Issue by zim0369** [alacritty/alacritty#6120]
Image previews with "ueberzug" or "w3m" just won't work. I configured everything correctly in ranger but the preview just wouldn't work. Works fine in kitty.

### System

OS: Arch Linux
Version: alacritty 0.10.1 ()
Linux: X11 Xmonad

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: 7

**Comment by jd-raymaker** [comment]
Using ranger with w3m in Alacritty works fine for me.
Can you provide the steps to reproduce the issue and share some exaples of your config?
Tried with and without a compositor?

**Comment by chrisduerr** [comment]
w3m/ueberzug are mostly hacks that do not really integrate with the terminal at all. If they don't work, that's their problem not ours.

**Comment by zim0369** [comment]
@chrisduerr then a built-in thing to view images would be nice(similar to kcat in kitty)

**Comment by shydefoo** [comment]
@jd-raymaker could you share your ranger config with w3m to get it to work? Thanks!

**Comment by nonogakhi** [comment]
I've similar issue. It took me a while realizing why Ueberzug doesn't work on alacritty. It works very well on gnome-terminal

**Comment by nonogakhi** [comment]
> I've similar issue. It took me a while realizing why Ueberzug doesn't work on alacritty. It works very well on gnome-terminal

I've realized that the problem was with Zellij(tmux alternative) and not Alacritty itself.
