### ISSUE TITLE
How to scroll one line up/down?

### ISSUE THREAD

**Issue by xphoniex** [alacritty/alacritty#6125]
In `gnome-terminal`, you can use Ctrl+Shift+Arrow_{Up, Down} to scroll exactly one line. Alacritty seems to be offering the same thing in a vim-way using Ctrl+Shift+Space and then move cursor wherever and then exit using Ctrl+C (which is x3 more involved).

Is there a simpler alternative?

### System

OS: `Linux`
Version: `alacritty 0.11.0-dev (3bfc4c2)`
Linux/BSD: `X11, BSPWM`

**Comment by jeremycostanzo** [comment]
Does adding
```
key_bindings:
  - { key: Up, mods: Control|Shift, action: ScrollLineUp }
  - { key: Down, mods: Control|Shift, action: ScrollLineDown }
```
in your `alacritty.yml` do what you want?

If you use linux, this file should be in ~/.config/alacritty/alacritty.yml`

**Comment by xphoniex** [comment]
Perfect! Yes it does, and thank you!

**Comment by 0x646a73** [comment]
For newer TOML configuration:

```
[keyboard]
bindings = [
    { key="ArrowUp", mods="Control|Shift", action="ScrollLineUp" },
    { key="ArrowDown", mods="Control|Shift", action="ScrollLineDown" }
]
```
