### ISSUE TITLE
Alt+Enter Full screen mode with half opacity, can't watch the video playing in the background from Chrome browser

### ISSUE THREAD

**Issue by eguneys** [alacritty/alacritty#6126]
When I go Alt+Enter Full screen mode, half opacity, the background chrome browser video playing goes black, so I can't watch it while using this app.

It works on cygwin mintty. Make it work for this thing too.

**Comment by chrisduerr** [comment]
I'd assume this is on Windows?

**Comment by eguneys** [comment]
Yes windows, I am sure it is the same behavior on any other major platform.

**Comment by chrisduerr** [comment]
> Yes windows, I am sure it is the same behavior on any other major platform.

It's not the same behavior on any other platform, major or not. It seems like Windows explicitly chooses to disable transparency for fullscreen applications for the sake of optimization. Why would Alacritty go against that optimization?

**Comment by eguneys** [comment]
Why because, computers are made for humans needs, and I need this. Is that clear enough for you. Just do this period

**Comment by chrisduerr** [comment]
> Why because, computers are made for humans needs, and I need this.

Then do it yourself. Computers might be made for human needs, but that doesn't mean the humans making them need to bother with the needs you have.
