### ISSUE TITLE
Support for different size of fallback fonts.

### ISSUE THREAD

**Issue by Determinant** [alacritty/alacritty#613]
Although the current master still hasn't supported fallback fonts in config file on Linux, as a CJK font user, it would great if I could specify different size for fallback fonts, like as follows in urxvt:
```
URxvt.font: \
    xft:Inconsolata-12, \
    xft:PowerlineSymbols-12, \
    xft:Source Han Sans TC Normal-11
```
The current alacritty typography:
![2017-06-14-012051_558x174_scrot](https://user-images.githubusercontent.com/1221635/27116532-d500c0fe-509f-11e7-97df-0b71bebac8f1.png)

My urxvt typography:
![2017-06-14-012106_560x173_scrot](https://user-images.githubusercontent.com/1221635/27116533-d6e003f8-509f-11e7-8d1b-461617367025.png)

This is due to fact that sometimes the monospace terminal font does not suit well with CJK font for the same size, so there could be some minor adjustment.

This project is very promising and I'm looking forward to proper display of wide char fonts (including emojis) which urxvt cannot handle very well (urxvt is notoriously bad at such wide char typography, so there are patches that only partially fix the problem). I'm also willing to help with either testing or coding.

**Comment by Determinant** [comment]
This feature is also useful for supporting special glyphs, such as emoji or powerline symbols, which may not work well with the default scaling of existing fonts. I could help after this issue is resolved: https://github.com/jwilm/alacritty/issues/606.

**Comment by sodiumjoe** [comment]
should be addressed by https://github.com/jwilm/alacritty/issues/957

**Comment by kchibisov** [comment]
Closing, since it's covered by #957
