### ISSUE TITLE
infocmp: couldn't open 

### ISSUE THREAD

**Issue by saladuit** [alacritty/alacritty#6132]
Can someone help me install the [terminfo file](https://github.com/alacritty/alacritty/blob/master/INSTALL.md#terminfo), [desktop entry](https://github.com/alacritty/alacritty/blob/master/INSTALL.md#desktop-entry), [manual page](https://github.com/alacritty/alacritty/blob/master/INSTALL.md#manual-page) or [shell completions](https://github.com/alacritty/alacritty/blob/master/INSTALL.md#shell-completions). It seems that all those commands don't exists.

### System

alacritty 0.10.1 ()

  Operating System: Ubuntu 20.04.4 LTS
            Kernel: Linux 5.13.0-48-generic
            
![image](https://user-images.githubusercontent.com/43225170/173668702-96fcf8e9-82be-432a-8766-c0d892487f65.png)

**Comment by saladuit** [comment]
![image](https://user-images.githubusercontent.com/43225170/173669261-686c2686-cdcc-497e-a360-61982b4d80aa.png)

**Comment by saladuit** [comment]
![image](https://user-images.githubusercontent.com/43225170/173669345-d25ca219-1a07-43bb-8464-4cb08585edd3.png)

**Comment by chrisduerr** [comment]
You need to be in the correct directory to install the files. Usually that's the root of the project.
