### ISSUE TITLE
MacOS: Alacritty does not tile with Yabai after upgrade

### ISSUE THREAD

**Issue by Combowombo** [alacritty/alacritty#6133]
After upgrade from 0.9.0 Alacritty seems to no longer get picked up by Yabai tiling window manager on Macos. I checked the Yabai github and a few users have the same issue there too.

**Comment by chrisduerr** [comment]
Supporting macOS at all with only limited device access is difficult enough, if you run into issues with non-standard components like custom window managers you're unfortunately on your own as far as support is concerned.

**Comment by Combowombo** [comment]
Thanks for the message. It seems to be an issue with Yabai actually, I'll try troubleshooting it myself, but I think i can get it to work.

**Comment by Spuxy** [comment]
did u resolve the problem ? im facing to the same problem :)

**Comment by bennylb** [comment]
@Spuxy I found, for whatever reason, opening Alacritty with `open -a Alacritty.app` rather than directly with `$ alacritty` yabai then recognised it. Obviously not a fix but could be used as a workaround.

**Comment by Spuxy** [comment]
> @Spuxy I found, for whatever reason, opening Alacritty with `open -a Alacritty.app` rather than directly with `$ alacritty` yabai then recognised it. Obviously not a fix but could be used as a workaround.

yes `open -n -a Alacritty` works totally fine :)

**Comment by kjvdven** [comment]
The `open -n -a Alacritty` trick doesn't work for me :( 

Tried to open Alacritty this way via SKHD, Kitty and via Raycast, but it keeps opening as a Floating window.

This is preventing me from switching at the moment.
