### ISSUE TITLE
Latest dev version crashes regularly on macOS

### ISSUE THREAD

**Issue by angelus2014** [alacritty/alacritty#6141]
OS: macOS 12.4 (M1/Apple Silicon)
Version: 0.11dev

### Logs

Crashes: see https://bsd.ac/ihf8167

Previous 0.11dev versions very rarely crashed on this system.

If any other information is needed, I'll be glad to provide.

EDIT: I just saw that someone else opened a similar issue (#6140), but I have noticed these crashes also with other commands, not just pasting.

---
With regards,

Angelo Machils

**Comment by chrisduerr** [comment]
Could you bisect to see if it was the same commit as in #6140 that broke things for you?

**Comment by angelus2014** [comment]
If you could tell me how I can test/produce this, I will be more than willing to help out. :)

**Comment by chrisduerr** [comment]
I'd recommend resetting to the specified version, building, then seeing if it crashes. Then just try the version before that and see if it still crashes. You could run a full `git bisect`, but I'd assume just testing those two versions are enough.

Since you're running -dev, I'd assume you know how to build from source.

**Comment by angelus2014** [comment]
Not sure if this is what you're looking for (yes, I know how to compile, but my 'Git-fu' isn't what it should be yet :) ). I went backwards and the latest commit I can compile and run without issues is: 9f02fb95685f46c390148eeab760e3a0dcfa49a9§

**Comment by chrisduerr** [comment]
Closing as duplicate of #6140.

**Comment by angelus2014** [comment]
The issue has already been closed, probably assuming that the latest commit fixed the issue; but perhaps you would like to be informed that I just fetched the latest master and it seems to be running fine.


---
With regards,

Angelo Machils

**Comment by chrisduerr** [comment]
Thanks for the test!
