### ISSUE TITLE
Certain double-width unicode emoji characters are treated as single-width

### ISSUE THREAD

**Issue by stephen-huan** [alacritty/alacritty#6144]
In the wild, from the album [「つよがり」](https://music.youtube.com/playlist?list=OLAK5uy_mvA3z_21moRfjQV1P8LQcbIXk3lAn5S64) I noticed the star characters "★" (unicode codepoint `0x2605`) and "☆" (`0x2606`) are treated by Alacritty as taking up the space of single-width characters although they display as double-width characters, causing them to clip into their adjacent neighbors. The cursor is also the width of a single character when on these characters.
![image](https://user-images.githubusercontent.com/20411956/174422095-e543a87c-7395-407e-a8ea-4a1ceeb9846d.png)

It also doesn't display properly if I force my locale to be different, e.g. with `LC_ALL="ja_JP.UTF-8" alacritty`, which also changes my font from "Noto Sans Mono" (shown above) to "IPAGothic".

This seems to be caused by the [unicode-width](https://github.com/unicode-rs/unicode-width) library defining these characters as one-wide in the [table](https://github.com/unicode-rs/unicode-width/blob/b58e85b5278309d7dd2ea514f7e6f9416b731b4d/src/tables.rs#L163). I'm filing an issue here first because I don't think this is an issue with the Rust library --- I tested a Python library [jquast/wcwidth](https://github.com/jquast/wcwidth) as well the standard library C function `wcwidth` provided by the header file `<wchar.h>` and all three agree that the width of the star characters is 1.

Rather, this seems to be a known issue for emojis, e.g. 
- https://github.com/unicode-rs/unicode-width/issues/4
- https://github.com/unicode-rs/unicode-width/issues/11

According to the [Unicode Standard Annex #11](https://www.unicode.org/reports/tr11/tr11-36.html#Recommendations) it seems the [proper thing](https://github.com/unicode-rs/unicode-width/issues/4#issuecomment-479325797) to do is to always treat emojis as being East Asian Wide (and effectively double-width):
> _When processing or displaying data_
> - [[UTS51](http://www.unicode.org/reports/tr41/tr41-24.html#UTS51)]  _emoji presentation sequences_ behave as though they were _East Asian Wide_, regardless of their assigned East_Asian_Width property value.

An implementation of modifying unicode-width to work on emojis is provided [here](https://github.com/unicode-rs/unicode-width/issues/4#issuecomment-549906181). It's possible that the two characters I cited aren't actually "emojis" in the strict sense and should really be considered 1 wide. 

However, Firefox and other graphical programs seem to render the character as a double-width character fine:
![image](https://user-images.githubusercontent.com/20411956/174424818-21ed2c40-987d-4ae1-906d-48b12e91d8a6.png)

Even if I force my font to be monospace, then it still renders as a double-width character fine:
![image](https://user-images.githubusercontent.com/20411956/174425775-48d33856-8d1c-4360-b5a6-13136a53fcc6.png)

and of note is that the terminal emulator [kitty](https://sw.kovidgoyal.net/kitty/)  renders the characters as single-width, but somehow makes the characters smaller
(I'm using the same font here as in Alacritty and Firefox, "Noto Sans Mono").
![image](https://user-images.githubusercontent.com/20411956/174425634-7b0e26ae-0987-40d0-8c1a-7a5c8503d813.png)

### System

OS: archlinux
Version: alacritty 0.10.1 ()
Linux/BSD: X11, no DE, compositor picom, WM i3-gaps

### Logs

Relevant system fonts installed: `noto-fonts`, `noto-fonts-cjk`, `otf-ipafont`

Fontconfig: `~/.config/fontconfig/fonts.conf`
```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<fontconfig>

    <alias>
        <family>serif</family>
        <prefer>
            <family>Noto Serif</family>
            <family>IPAMincho</family>
        </prefer>
    </alias>

    <alias>
        <family>sans-serif</family>
        <prefer>
            <family>Noto Sans</family>
            <family>IPAGothic</family>
        </prefer>
    </alias>

    <alias>
        <family>monospace</family>
        <prefer>
            <family>Noto Sans Mono</family>
            <family>IPAGothic</family>
        </prefer>
    </alias>

</fontconfig>
```

Font-related part of `~/.config/alacritty/alacritty.yml`
```yaml
# Font configuration
font:
  # Point size
  size: 15.0
```

Font/Terminal size: `alacritty -vv`
```text
Created log file at "/tmp/Alacritty-78540.log"
[0.000004298s] [INFO ] [alacritty] Welcome to Alacritty
[0.000050956s] [INFO ] [alacritty] Version 0.10.1 ()
[0.000065764s] [INFO ] [alacritty] Running on X11
[0.000591513s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/stephenhuan/.config/alacritty/alacritty.yml"
[0.020268125s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.021988673s] [DEBUG] [alacritty] Estimated DPR: 1.125
[0.022002128s] [DEBUG] [alacritty] Estimated window size: None
[0.022007098s] [DEBUG] [alacritty] Estimated cell size: 14 x 32
[0.076345141s] [INFO ] [alacritty] Device pixel ratio: 1.125
[0.080197792s] [INFO ] [alacritty] Initializing glyph cache...
[0.081666345s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.084041435s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.086798564s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.089011169s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.103994166s] [INFO ] [alacritty] ... finished initializing glyph cache in 0.023764385s
[0.104083294s] [INFO ] [alacritty] Cell size: 14 x 32
[0.104088524s] [INFO ] [alacritty] Padding: 0 x 0
[0.104092551s] [INFO ] [alacritty] Width: 800, Height: 600
[0.117354149s] [INFO ] [alacritty] PTY dimensions: 18 x 57
[0.123140910s] [INFO ] [alacritty] Initialisation complete
[0.126059022s] [DEBUG] [alacritty_terminal] New num_cols is 58 and num_lines is 42
[0.127896150s] [INFO ] [alacritty] Padding: 0 x 0
[0.127928080s] [INFO ] [alacritty] Width: 820, Height: 1369
```

**Comment by chrisduerr** [comment]
Everything working as intended here. This is not an emoji and it is supposed to be rendered as single-width. Thus nothing to do for Alacritty. Scaling of fonts could be done, but will always result in poor looking fonts, I recommend just installing a terminal-aware font.

**Comment by langfield** [comment]
This is definitely wrong. As the OP mentioned, lots of other platforms handle the case where emojis are used for these characters, and if you have an emoji font installed and use Alacritty, it causes characters to overlap severely (in fact to completely obscure one another). How can you say this is working as intended?

**Comment by kchibisov** [comment]
@langfield there's a thing called unicode standard and they also define a width for each character in it. If they diverge from standard width, it's not our issue.

**Comment by langfield** [comment]
If the standard defined them as zero-width, would it then be your issue? Isn't the goal here to build something that works, not something that conforms to some standard? Conforming to the standard causes *characters to obscure each other* using fonts that are the default on billions of devices.

A standard is a means to an end. It is a tool humans use to reduce the frequency of incompatibilities that break things. If you are using the standard as an excuse *to implement an incompatibility that breaks things*, that is all kinds of backwards.

The emoji font creators shouldn't have diverged from the standard, no one would disagree with you there. But they did, and damn-near every modern phone and computer in the world uses them.
