### ISSUE TITLE
Hexadecimal input for --embed

### ISSUE THREAD

**Issue by BioBox** [alacritty/alacritty#6145]
Can you please add suport for hexadecimal xids for the `--embed` option so that I don't have to do these extra steps _every time_ I start my terminal in a tabbed instance?
```fish
set -x xid (tabbed -d)
set plain_id (string sub -s 3 $xid | tr '[a-f]' '[A-F]')
set -x did (echo "obase=10; ibase=16; $plain_id" | bc)
alacritty --embed $did &>/dev/null &
```
As you can see, `tabbed` - as well as every other program I know of that supports xembed, uses hexadecimal. Just a simple check for the `0x` prefix would go a long way.

**Comment by chrisduerr** [comment]
On the one hand, I don't really care what other applications decide to output their IDs with, conversion is trivial and we shouldn't have to change Alacritty any time someone decides to add a new output format.

On the other hand, hexadecimal should be pretty easy to support, so if someone is willing to write a patch, upstreaming shouldn't be a big problem.
