### ISSUE TITLE
Terminals database is inaccessible

### ISSUE THREAD

**Issue by chrisabruce** [alacritty/alacritty#6147]
### System

OS: macOS
Version: 0.10.0 (8a26dee) (installed via brew)

### Logs

Font/Terminal size: Width: 3188, Height: 762

Whenever I run `clear` or `mosh` I get:
`terminals database is inaccessible`

This seems to happen if I have the font section set. I get the error even if I just have nothing but size set.

```toml
font:
  # Normal (roman) font face
  normal:
    family: "SauceCodePro Nerd Font Mono"
    style: Regular
  size: 18.0
  use_thin_strokes: false
```

**Comment by chrisduerr** [comment]
Does it work when you change your `TERM`? I'd assume something like `xterm-256color` should just work.

Since it explicitly says `inaccessible`, I'd check the permissions on a potential `alacritty` terminfo, but if it's missing entirely that's probably why.

**Comment by chrisabruce** [comment]
If I use any other terminal, no issues. If I remove the font stanza no issues. I did add  an env var for TERMINFO and pointed it so `/usr/share/terminfo` still not working. The only thing I can do is remove font stanza.

**Comment by chrisabruce** [comment]
Ok so `xterm-256color` does work. Where can I learn why that is?

**Comment by chrisabruce** [comment]
Ok RTFM.  This help me figure out that I didn't properly install the terminfo: https://unix.stackexchange.com/questions/597445/why-would-i-set-term-to-xterm-256color-when-using-alacritty/678901#678901
