### ISSUE TITLE
Cannot display undercurls in neovim

### ISSUE THREAD

**Issue by Martinits** [alacritty/alacritty#6149]
I use Neovim and Alacritty on Archlinux. When trying to highlight something like this:
`highlight xxxxx gui=undercurl`, Alacrittty displays underlines instead of undercurls while Kitty does this correctly. I searched the issues and found out Alacritty has just added support for undercurls a few months ago, so I changed to dev version (from AUR). Still not work. Do I need some extra config?
Some Info:
```
❯ alacritty --version
alacritty 0.11.0-dev (92362428)
❯ nvim --version
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
The font is Hack Nerd Font Mono.

**Comment by chrisduerr** [comment]
Does the following work for you?

```
echo -e "\e[4:3mTEST"
```

**Comment by Martinits** [comment]
> Does the following work for you?
> 
> ```
> echo -e "\e[4:3mTEST"
> ```
It works.
![image](https://user-images.githubusercontent.com/48900241/174978686-bc5d56f1-0735-4294-8f1d-bc9d9f156208.png)

**Comment by kchibisov** [comment]
It's not `gui` it's `guisp`, so please try `guisp=undercurl`.

**Comment by kchibisov** [comment]
You've ensured that your `echo $TERM` is `alacritty` before running neovim and that you know for sure that in other terminals neovim can show undercurl when you do that highlight setting? I'd also suggest to check for `set spell` since neovim has undercurl for those by default.

**Comment by Martinits** [comment]
Oh sorry, stupid mistake, forget to set TERM back to `alacritty`. Thank a lot!

**Comment by xulongwu4** [comment]
@Martinits did you have to do something special to make it work? I am not able to have undercurl working under neovim, and my situation is the same as what is described in this issue: https://github.com/neovim/neovim/issues/21182.

I tried nvim 0.7.0, 0.8.2, and the nightly build, but none of them could render undercurl correctly in alacritty. However, it works properly in kitty nad konsole.

**Comment by Martinits** [comment]
@xulongwu4 For me no problem with alacritty 0.11.0 (8dbaa0bb), NVIM v0.8.2 and nothing special. I can't reproduce that issue on archlinux. Maybe a problem on WSL2?

**Comment by xulongwu4** [comment]
@Martinits, thanks for your confirmation. I was able to figure out that the issue is due to outdated terminfo file in the ncurses library on my system.

**Comment by ajoino** [comment]
@xulongwu4 where did you find this file? I get the undercurls to work in alacritty outside of neovim but I can't get them to work inside neovim. If I try `echo -e "\e[4:3mTEST"` in toggleterm I just get normal underlines and colored undercurls colors entire characters without even an underline.

I'm very confused and don't know where to start looking for the cause of this error.

**Comment by jsit** [comment]
The solution for me (finally) was that two things needed to be set up:

1. `export TERM=alacritty`
2. Install alacritty terminfo:
    1. Download the alacritty repo
    2. Run `tic -xe alacritty,alacritty-direct extra/alacritty.info`
