### ISSUE TITLE
vim paste with line number

### ISSUE THREAD

**Issue by starsareintherose** [alacritty/alacritty#6151]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Arch Linux
Version: 0.10.1
Linux/BSD: Wayland, wayfire

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`
[test.log](https://github.com/alacritty/alacritty/files/8977096/test.log)

![image](https://user-images.githubusercontent.com/37733075/175563496-be1aa70a-7a05-4f8e-977e-0c331d328976.png)

you can see when the windows is small, it would just paste part with line number , it's quite strange

**Comment by kchibisov** [comment]
alacritty's vi mode has nothing to do with vim or neovim or anything you run in the terminal, so what you see on screen is what copied. However you likely want a copy from the vim itself, so you should try to accomplish it with it.

**Comment by starsareintherose** [comment]
So why just alacritty paste line number in vim and double click don't select the whole line. That's quite strange.

**Comment by kchibisov** [comment]
Are you pasting in insert mode or normal mode in vim? Also ensure that pasting from alacritty to other applications paste the right content?
