### ISSUE TITLE
Can i use alacritty without a GPU

### ISSUE THREAD

**Issue by createvi** [alacritty/alacritty#6152]
can i use alacritty without having a GPU, i want to use alacritty but i don't have a GPU, and when i start alacritty it shows `Error: There was an error initializing the shaders: Failed compiling shader: 0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES` is there any options to use alacritty without GPU

**Comment by kchibisov** [comment]
You do have GPU actually, it just supports gles2.

Latest master do support gles2 so it should start without issues for you.
