### ISSUE TITLE
tmux background color becomes dark and also neovim color become dark

### ISSUE THREAD

**Issue by imSafdarAwan** [alacritty/alacritty#6156]
When i use tmux inside the alacritty the background colors becomes dark without respecting the background color of tmux and also nvim if i am using nvim
here is the image of tmux bar background color on the kitty and the alacritty. Alacritty shows the tmux color as dark rather than the colors i have used in the color scheme.
![image](https://user-images.githubusercontent.com/87114084/175800726-2d418853-2634-4a35-82ba-f0f325e7cf4f.png)
this is the image on nvim
![image](https://user-images.githubusercontent.com/87114084/175800763-5ee564f9-ab2d-4700-91c4-7a778cab33fb.png)

### System

OS: Manjaro i3
Version: `alacritty 0.10.1 ()`
Linux/BSD: i3 and picom

**Comment by imSafdarAwan** [comment]
and also this is the config i have 
**My alacritty theme**
https://github.com/imSafdarAwan/xdg/blob/200d66e80e7e76d89e0e42c00fedf5d9d90e9254/alacritty/.config/alacritty/alacritty.yml#L241
**My tmux conf**
https://github.com/imSafdarAwan/xdg/blob/200d66e80e7e76d89e0e42c00fedf5d9d90e9254/tmux/.tmux.conf#L1

**Comment by chrisduerr** [comment]
What do you mean by "becomes dark"?

**Comment by imSafdarAwan** [comment]
> What do you mean by "becomes dark"?

see the difference between kitty and the alacritty terminal instances the kitty terminal displays the color which i have defined in the tmux theme but when it comes to alacritty the color of the tmux header becomes dark gray or if you open nvim in the tmux instance of the alacritty the background color of the nvim also become dark gray see in the upper scrrenshots

**Comment by RudraveerMandal** [comment]
Thats because alacritty colours are vastly different from kitty. Does the same thing happen when you use alacritty with a vanilla config?

**Comment by imSafdarAwan** [comment]
> 

sir the problem is that alacritty doesn't respects the config of the tmux and also nvim color scheme works fine if i use it outside of the tmux but when i use tmux alacritty remove the backgroud color and uses its default color as the background can anybody point out the issue i am heaving with tmux colors in alacritty

**Comment by imSafdarAwan** [comment]
> Thats because alacritty colours are vastly different from kitty. Does the same thing happen when you use alacritty with a vanilla config?

yes

**Comment by chrisduerr** [comment]
Please provide **clear** steps on how to reproduce your issue and describe what **exactly** your issue with Alacritty's behavior is. Saying a different terminal does something different is not a sufficient explanation.

**Comment by chrisduerr** [comment]
I'm sorry, but I cannot help someone who cannot clearly describe his problem.

**Comment by kchibisov** [comment]
@imSafdarAwan if you execute `hi! Normal ctermbfg=none ctermbg=none guifg=none guibg=none guisp=none` from inside vim does it help?

**Comment by imSafdarAwan** [comment]
> 

sir i have given you the config and screen shots and scenario in which it happens now i don't know what do you mean by `someone who cannot clearly describe his problem.` because i have done that and i think you don't understand what i have told you. so Thanks even if you can't help.

**Comment by imSafdarAwan** [comment]
> @imSafdarAwan if you execute `hi! Normal ctermbfg=none ctermbg=none guifg=none guibg=none guisp=none` from inside vim does it help?

thanks for comment but i think i would have to re-write  my whole alacrity and tmux config to spot the breaking point which is causing this

**Comment by TheSafdarAwan** [comment]
solved add this to your tmux conf
`set -ga terminal-overrides ",xterm-256color:Tc"`
you can read more about it in here https://www.reddit.com/r/tmux/comments/mesrci/tmux_2_doesnt_seem_to_use_256_colors/

**Comment by pavankumar-v** [comment]
> solved add this to your tmux conf `set -ga terminal-overrides ",xterm-256color:Tc"` you can read more about it in here https://www.reddit.com/r/tmux/comments/mesrci/tmux_2_doesnt_seem_to_use_256_colors/

Thanks worked for me in ubuntu inbuilt terminal

**Comment by BekManBekov1974** [comment]
> solved add this to your tmux conf `set -ga terminal-overrides ",xterm-256color:Tc"` you can read more about it in here https://www.reddit.com/r/tmux/comments/mesrci/tmux_2_doesnt_seem_to_use_256_colors/

Thanks bro!

**Comment by TemelGunaydin** [comment]
Thanks

**Comment by RATIU5** [comment]
I'm having a really similar issue as well. I tried @theSafdarAwan's answer with no avail. I set up the rose-pine theme for neovim and alacritty. Using neovim without tmux loads the correct neovim theme, but when using tmux, the background color changes to a dark grey within neovim. I am unsure of any other fixes and not sure if it's a problem with Alacritty or tmux. Any more suggestions?

**Comment by wesley-lewis** [comment]
> solved add this to your tmux conf `set -ga terminal-overrides ",xterm-256color:Tc"` you can read more about it in here https://www.reddit.com/r/tmux/comments/mesrci/tmux_2_doesnt_seem_to_use_256_colors/

Thanks a lot!

**Comment by fishBone000** [comment]
> EDIT: Got it working, I needed to add these lines to my alacritty config:
> 
> ```
> env:
>   TERM: xterm-256color
> ```

Or, you can add `set-option -a terminal-features 'alacritty:RGB'` in the `tmux.conf`, as suggested by nvim command `:checkhealth`.  
Inspired by [this StackOverflow](1) question, though the original post had a different approach.

**Comment by Dani-0TB** [comment]
just wanted to comment that the is a user in this thread who is a massive C.

All solutions work for me. Thanks everyone!

**Comment by theSafdarAwan** [comment]
> just wanted to comment that the is a user in this thread who is a massive C.
> 
> All solutions work for me. Thanks everyone!

What do you mean by?
`who is a massive C.`

**Comment by the-root-user** [comment]
- Tmux displays status bg background colors wrong error

 Adding keywords for the next person searching the web like me :)
 
 Thanks for sharing the fix @theSafdarAwan
