### ISSUE TITLE
Group Alacritty windows on MacOS

### ISSUE THREAD

**Issue by justaskz** [alacritty/alacritty#6157]
### Current behaviour:
Create multiple instances or windows of Alacritty. You will get a separate icon for each instance in Dock. 
![Screenshot 2022-06-26 at 16 59 31](https://user-images.githubusercontent.com/11331183/175817764-5d13cc26-5590-4892-bd71-dee31cd00a2d.png)

### Proposed behaviour:
Group all instances under one icon. Cant describe it in technical terms, since I am not MacOS developer. However many popular apps does this if user creates multiple windows. As a result, MacOS keyboard shortcut `Move focus to the next window.` can be used, which allows to quickly switch between windows of the same app.
![Screenshot 2022-06-26 at 17 07 04](https://user-images.githubusercontent.com/11331183/175818262-0eeb68f7-09a1-44d2-bbf9-f5979899f3e3.png)

**Comment by kchibisov** [comment]
Try using `CreateNewWindow` action in config instead of `CreateNewInstance`.
