### ISSUE TITLE
nvim-tree Icons don't show in M1 Mac

### ISSUE THREAD

**Issue by aman7000** [alacritty/alacritty#6162]
nvim-tree Icons don't show in M1 Mac
<img width="576" alt="Screen Shot 2022-06-28 at 7 06 36 AM" src="https://user-images.githubusercontent.com/12692174/176069456-647828c4-41b4-4c61-ab5f-b369f4c7e2b3.png">

### System

OS: macOS
Version: alacritty 0.10.1 (2844606)

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`. 
[vv.log](https://github.com/alacritty/alacritty/files/8996903/vv.log)

Keyboard and bindings: `alacritty --print-events`
[events.log](https://github.com/alacritty/alacritty/files/8996904/events.log)

**Comment by chrisduerr** [comment]
Have you installed the required fonts?

**Comment by aman7000** [comment]
I have Installed JetBrains Mono & Fira Code.

**Comment by aman7000** [comment]
family: "MesloLGS NF"
solved the issue thanks.
