### ISSUE TITLE
Feature request: Enable ability to use keyboard only to perform a native text selection and copy

### ISSUE THREAD

**Issue by unphased** [alacritty/alacritty#6163]
I can use the keyboard to do the following (where `...` are vim-style movement keys being entered): 

- (Naturally) select and yank a portion of a buffer in Vim using only keyboard via `v`...`y`
- Select and copy (to a tmux buffer and possible to configure to more things) via `tmux-prefix`...`Space`...`Enter`

These modes cover a lot of bases but there are numerous circumstances in which we may want to copy some output from a program and we're, for example, not in a tmux context. 

The only way (in this terminal emulator as well as most others) to perform a terminal-emulator level text selection is with a mouse.

I'm used to using a mouse but it occurs to me that some potential exists for joy to be derived from being able to do this without reaching away from the keyboard. 

An example of how iTerm offers the ability to do this: https://superuser.com/a/214270/98199

Admittedly this train of thought does then lead into also requesting a search feature which searches scrollback with which we can specify where to begin a given selection. I do understand this to be beyond the scope of alacritty. But maybe it could be added by sticking to the terminal UI paradigm without adding much complexity to the software. Thoughts?

**Comment by chrisduerr** [comment]
This is already implemented.

**Comment by unphased** [comment]
Oh my bad. I found the features document now. Thank you.
