### ISSUE TITLE
MacOS Virtual Keyboard for emojis 

### ISSUE THREAD

**Issue by AxZxP** [alacritty/alacritty#6164]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: MacOS 10.15.7
Version: 0.10.1

### Issue
<kbd>Ctrl</kbd>+<kbd>CMD</kbd>+<kbd>Space</kbd> key combination should trigger an emoji virtual keyboard on MacOS. In Alacritty, nothing happens.

Is there a way to honour this os feature ?

### The expected behaviour
This popup should appear to insert an emoji :
![Screenshot 2022-06-28 at 11 23 25](https://user-images.githubusercontent.com/68596777/176143933-3f7bd62c-19c5-4d4c-890f-190935122dc5.jpg)

**Comment by chrisduerr** [comment]
We support IME, which is fully capable of implementing this usecase. I have no interest in implementing some separate macos emoji-specific IME version.
