### ISSUE TITLE
underline overlaps underscore

### ISSUE THREAD

**Issue by shaeinst** [alacritty/alacritty#6169]
underline overlaps underscore.
![2022-06-29_23-44_1](https://user-images.githubusercontent.com/41078534/176505331-25f30294-a558-4fec-9dc1-bd942ddbce7a.png)
test_fun() looks like test fun() (two separate word) 
![2022-06-29_23-44](https://user-images.githubusercontent.com/41078534/176505357-2e5b430f-7501-4f0c-8259-7812dbbae788.png)

### System

OS: Linux
Version: alacritty 0.11.0-dev (9bbb296d)
Linux/BSD: X11, bspwm

**Comment by kchibisov** [comment]
Well, the position for underline is picked from your font, not sure we can do much here, without adding advanced thing like skipping descenders, etc.

There're settings to adjust font offsets (`font.offset` and `font.glyph_offset`), which should affect underline as well.
