### ISSUE TITLE
how to disable all default vi key bind

### ISSUE THREAD

**Issue by chenjie199234** [alacritty/alacritty#6179]
Terminal just do terminal's job!
Vim has a lot of plugins.
Plugins will have key bind.
Users will set their own key bind too.
The terminal hijack the key bind, the vim's config will not active.

**Comment by chrisduerr** [comment]
Alacritty will not hijack any of vi's keybinding.

**Comment by chenjie199234** [comment]
@chrisduerr but my key bind in vim not working

**Comment by chenjie199234** [comment]
@chrisduerr

**Comment by chenjie199234** [comment]
--lsp definition
vim.api.nvim_set_keymap('n','<C-i>',':lua vim.lsp.buf.definition()<CR>',{silent = true})
vim.api.nvim_set_keymap('n','<M-i>',':lua vim.lsp.buf.definition()<CR>',{silent = true})
--<C-o> jump back to last cursor position
vim.api.nvim_set_keymap('n','<M-o>','<C-o>',{silent = true})

**Comment by chenjie199234** [comment]
@chrisduerr

**Comment by chenjie199234** [comment]
@chrisduerr this doesn't work
```
--lsp definition
vim.api.nvim_set_keymap('n','<C-i>',':lua vim.lsp.buf.definition()<CR>',{silent = true})
vim.api.nvim_set_keymap('n','<M-i>',':lua vim.lsp.buf.definition()<CR>',{silent = true})
--<C-o> jump back to last cursor position
vim.api.nvim_set_keymap('n','<M-o>','<C-o>',{silent = true})
```

**Comment by kchibisov** [comment]
Are you using macOS?

**Comment by chenjie199234** [comment]
@kchibisov yes

**Comment by chenjie199234** [comment]
@kchibisov so this is the mac's compatible problem?
