### ISSUE TITLE
Cannot display undercurls

### ISSUE THREAD

**Issue by xiyaowong** [alacritty/alacritty#6180]
Can't display undercurls

OS: Windows 11
Version:  alacritty 0.11.0-dev (ebc6922e)

fllow this https://github.com/alacritty/alacritty/issues/6149#issuecomment-1162672271
![image](https://user-images.githubusercontent.com/47070852/177089788-09676a5a-331c-43c2-b5a3-93bb29427a54.png)

**Comment by xiyaowong** [comment]
more info
![image](https://user-images.githubusercontent.com/47070852/177090791-fb1f167a-717d-4f76-862b-a8579d0473a0.png)

**Comment by chrisduerr** [comment]
This is probably a ConPTY issue. So unless you can reproduce it on macOS/Linux, you'll have to take it up with Microsoft.

**Comment by xiyaowong** [comment]
Got it :(

**Comment by asmodeus812** [comment]
Facing the same issue, latest build from today from master on Windows 11. Any possible solutions ?

**Comment by ok-nick** [comment]
Is there any place that we can bash Microsoft to support it?

**Comment by ryuheechul** [comment]
We will probably need to wait for this one, https://github.com/microsoft/terminal/issues/7228 (and others issues linked to it) to be resolved in order for undercurls to work.
