### ISSUE TITLE
Feature Request:  Draw lines on the terminal using the STL file format commands/functions in a script.

### ISSUE THREAD

**Issue by coderextreme** [alacritty/alacritty#6182]
Allow for a functions/commands in bash or other shell that will draw a set of triangle faces on the terminal using STL commands/functions.

The base STL bash functions/commands might look something like this:

solid name
facet normal ni nj nk
    outer loop
        vertex v1x v1y v1z
    endloop
endfacet
endsolid name

From:  https://en.wikipedia.org/wiki/STL_%28file_format%29

Vertexes, Loops, and Facets may be added at same level of nesting.

Ideal we could then write a program to display an STL file on the terminal window.

One would have to choose a POV or have a virtual camera.

I think we just need core support for drawing 3D lines at any angle in the terminal to create triangles.  Maybe start with files without a normal or z dimension.  People can do their own projections once there are lines.

STL files are common with 3D Printing.

**Comment by coderextreme** [comment]
Here are some sample stl files (please do not share)

https://github.com/coderextreme/X3DJSONLD/tree/master/src/main/stl

**Comment by coderextreme** [comment]
How about at least do monochrome 2D vector-graphics?  I can build my own STL displayer I have vector-graphics. MacTerm, for example, does vector graphics, "MacTerm can render ... TEK 4014 and TEK 4105 vector graphics"  Frankly, finding an terminal emulator on Windows 10 that does vector graphics seems kind of hard.

**Comment by j4james** [comment]
@coderextreme On Windows there are actually quite a few terminals that support some form of Tektronix mode. You've got a choice of Mintty, TeraTerm, RLogin, Reflection Desktop, and IBM Personal Communications. I believe the latter three can also do ReGIS if you'd prefer that.

**Comment by coderextreme** [comment]
James,

How does alacritty use OpenGL beyond characters?

I'm looking for the best environment for building
3D+(string/text/document/file/folder processing) programs.  I like the
string/text/file processing of shells. The Top 11 Opengl Terminal Emulators
Open Source Projects (awesomeopensource.com)
<https://awesomeopensource.com/projects/opengl/terminal-emulators> reports
Alacritty as number one.  I figure I'd like to write some OpenGL program in
a shell language that displays in a terminal (maybe I'm bending the
definition of terminal a bit).

I figured alacritty already had images and text, these being low hanging
fruit and still 2D.  I thought maybe alacritty might support 3D, so I put
in this feature request to figure out if alacritty can display 3D graphics
in the terminal window, like it does images and text.   Can I send shading
language to the graphics subsystem for display in alacritty? Or is all
shading sourced from within alacritty?

Thanks for any clarification.

I know in the past that text was separated from graphics in the GPU, so I'm
hoping that desert is over.

John

**Comment by j4james** [comment]
> How does alacritty use OpenGL beyond characters?

I have no idea. I'm not actually an Alacritty developer. I was just responding to your statement that vector graphics terminals for Windows were hard to find.

If you don't specifically require vector graphics, though, and just want a way to render images in the terminal, then you may want to try out the fork of Alacritty with sixel support (see https://github.com/microo8/alacritty-sixel).
