### ISSUE TITLE
"SpawnNewInstance" action with a separate config

### ISSUE THREAD

**Issue by amamut** [alacritty/alacritty#6185]
OS: MacOS

Is there a way to spawn a new instance of alacritty with another config? The use case is to have a terminal that drops down from any desktop, so that I can run a command from anywhere, and then to also have a terminal window on a desktop to run my dev projects. I already have alacritty as a dropdown with `decorations: none` but I want to launch a new instance with `decorations: full` so that I can move the window around and use the bar buttons. But I can't create a new alacritty instance with a new config. I've tried:

- command `open -n '/Applications/Alacritty.app' --args '--config-file $HOME/.config/alacritty/alacritty_main.yml'` - this doesn't seem to do anything as I think Alacritty checks to see if an instance is already running.
- alacritty keybinding `- { key: N,        mods: Command, command: { program: "/Applications/Alacritty.app", args: ["--config-file", "$HOME/.config/alacritty/alacritty_main.yml" ] } }` - Error in alacritty: "Unable to launch /Applications/Alacritty.app with args..."
- `SpawnNewInstance` action doesn't seem to support args.

Thanks.

**Comment by amamut** [comment]
That doesn't work because it doesn't spawn a new instance but instead locks up the original terminal waiting on the new window to exit.

**Comment by amamut** [comment]
<img width="1498" alt="image" src="https://user-images.githubusercontent.com/963908/177573653-233ae5ad-e70c-4114-8422-da617ca9fa56.png">

I just run ` Alacritty --config-file $HOME/.config/alacritty/alacritty_main.yml`, it creates a new window but you can see that original window is locked up waiting. What am I doing wrong?

**Comment by kchibisov** [comment]
it was meant that you should run it from inside the **key** binding. ofc it'll lock that way since your shell launches it that way.

You've originally used keybinding, but you've used Alacritty.app, however you should simply use the executable from inside Alacritty.app in that keybinding, that way it'll work.

**Comment by amamut** [comment]
I thought that's what you meant, but that works even less: 
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/963908/177583571-a62d496b-7777-45db-90a8-9740d1de6803.png">

**Comment by kchibisov** [comment]
you should expand $HOME, since we're not a shell to expand it.
