### ISSUE TITLE
Alacritty has huge font

### ISSUE THREAD

**Issue by bitterhalt** [alacritty/alacritty#6187]
### System

OS: Arch Linux
Version:1.10.1
X11/ KDE

Hello! I installed Alacritty on my virtual machine and Font size is HUGE compared my other terminals (Konsole Kitty)
![Screenshot_20220707_173830](https://user-images.githubusercontent.com/95308907/177801375-fac67658-60fc-4f62-adf4-cbdbbe12ea66.png)

Font size is 10.0 on both terminals and as you can see from screenshot Alacritty's font is huge.

**Comment by bitterhalt** [comment]
I use same font and size in both terminals. And in my main PC font in Alacritty looks same as my other terminals. 

I get this error when I try to use setting you suggested:

![Screenshot_20220708_024235](https://user-images.githubusercontent.com/95308907/177889388-54ccb050-ebb2-4835-b677-c9f22a89f9a2.png)

**Comment by vp2177** [comment]
Even if setting an environment variable works around this, shouldn't Alacritty use a font size by default that matches the user's expectations and matches what every other app uses?

**Comment by kchibisov** [comment]
The problem is not the font size, but scaling not being explicitly set anywhere, and given that on X11 you have way to many methods to do so, there's nothing wrong with what alacritty does(computes based on display metrics).

Some apps do the same by default as well, they are just quite rare.

**Comment by nixpulvis** [comment]
This has always troubled me too a bit. I once tried to convince myself why it is the way it is, and now I’ve forgotten. Was it because we assume HiDPI monitors by default? Or is it just simpler to support for some reason?
