### ISSUE TITLE
Cursor problem

### ISSUE THREAD

**Issue by ramita-0** [alacritty/alacritty#6189]
Im running i3 + picom + alacritty.

I want to have an underline cursor instead of a block, and i have it, but when i lose focus of the window, and change to another one, the cursor turns into a block, instead of remaining as an underline.
Is there a way to fix this behaviour?

**Comment by kchibisov** [comment]
Is it a block or a hollow block? Is it block after you refocus the window?

**Comment by ramita-0** [comment]
> Is it a block or a hollow block? Is it block after you refocus the window?

Sorry for the delay. Its a hollow block, and when a i refocus the window it goes back to an underline

**Comment by aleksanderkrauze** [comment]
@ramita-0 In the configuration file you have section `cursor` and inside it option `unfocused_hollow` that is by default set to `true`. Change it to `false` and cursor should stop changing when you change focused window.

```
#cursor:

  # If this is `true`, the cursor will be rendered as a hollow box when the
  # window is not focused.
  #unfocused_hollow: true
```

**Comment by ramita-0** [comment]
Thanks! didnt see that one :)

Solved.
