### ISSUE TITLE
Alacritty does not respect theme when opening applications with "-e" option

### ISSUE THREAD

**Issue by g1sbi** [alacritty/alacritty#6191]
### System

Arch Linux
Version: 0.10.1
X11, bspwm

I have a script to open a terminal file explorer (xplr) with alacritty. The script works, but alacritty does not respect the terminal colors. The script simply goes
```
!#/bin/bash
alacritty -e xplr.sh
```
This happened with nnn too, so I must assume it's alacritty's fault. What can I do? Is there any flag I'm missing?

**Comment by kchibisov** [comment]
In case you're using pywall or set colors from the shell, alacritty won't invoke the shell with `-e`, so what you should do use `alacritty -e your_shell -c xplr.sh`.

**Comment by g1sbi** [comment]
Can't get it to work, sorry for the bother.
I tried:
```
alacritty -e bash -c xplr
```
and
```
alacritty -e /bin/bash -c xplr
```
but none works. Can you give me the accurate syntax for bash?

**Comment by kchibisov** [comment]
What exactly? Coloring? or that a command is missing?

Assuming that you've called your file `xplr.sh` in original message it should be

`alacritty -e bash -c xplr.sh`.

The syntax is the following. `-e` consumes the first argument and uses it to run, and the rest is forwarded the bash, so in the particular case bash will run with `-c xplr.sh`.

**Comment by g1sbi** [comment]
Understood, thanks. So I modified the script and it still works, but the coloring is still wrong. As an added detail, my colorscheme is set through pywall.

**Comment by kchibisov** [comment]
is that the shell you're using pywall for? I'd suggest to check whether bash loads profile or are you using a zsh for pywall, it so you should use it?

In anyway, that's have nothing to do with alacritty, you should just get your shell you're running to source pywall config.
