### ISSUE TITLE
Feature request: write or output default config

### ISSUE THREAD

**Issue by rektide** [alacritty/alacritty#6199]
Hello, feature request here. I spend more time than I'd care to admit repeating the [Configuration part of getting started](https://github.com/alacritty/alacritty#configuration) with Alacritty:

> You can find the default configuration file with documentation for all available fields on the [GitHub releases page](https://github.com/alacritty/alacritty/releases) for each release.
> Alacritty doesn't create the config file for you, but it looks for one in the following locations:

I'd love if I could get started with Alacritty without opening a web browser. This issue proposes we do something CLI friendly for spitting out a default config.

Various options:
* `alacritty defaults` subcommand that prints out the defaults to stdout.
  * this would be 95% of everything i'd want!
  * bonus: `alacritty defaults --write-file [file]` to write to a file/the default file. very optional.
    * opens can of worms of: what do we do if file already exists? abort? merge the current config file overtop the defaults & write that?
* `alacritty --write-defaults` that launches as normal but also writes the defaults to the `--config-file` location (or the default config location).

**Comment by chrisduerr** [comment]
> I'd love if I could get started with Alacritty without opening a web browser.

You can, just clone the repository. Which really is what you should be doing if your repository doesn't have a package anyway.

If your repository does have a package, I'd suggest recommending to them that they include the repo's configuration file. There's directories made for exactly this.
