### ISSUE TITLE
Include alacritty.yaml in Mac Alacritty.app

### ISSUE THREAD

**Issue by rektide** [alacritty/alacritty#6202]
Hi. In #6199 I asked for an easy way to get the default `alacritty.yaml`. @chrisduerr countered distributions ought include this.

> If your repository does have a package, I'd suggest recommending to them that they include the repo's configuration file.

I'm requesting the MacOS distribution on the release page include an `alacritty.yaml`.

**Comment by chrisduerr** [comment]
What exactly would you do with the `alacritty.yml`, were it to be included in the `dmg`? I doubt there would be a lot of people moving it out of there and I'd actually discourage that usually.

**Comment by kchibisov** [comment]
@chrisduerr we do have like everything(completions, man page) in Alacritty.app, the problem is that we don't have a config there :/ 

Seems like it should be added, given that we copy a bunch of stuff there as well.

**Comment by mhmdanas** [comment]
> What exactly would you do with the alacritty.yml, were it to be included in the dmg? I doubt there would be a lot of people moving it out of there and I'd actually discourage that usually.

Homebrew does put reference configs in `/usr/local/share/examples` (for instance, it puts one for Mirage in `/usr/local/share/examples/mirage/settings.py`), and I for one would certainly appreciate having a reference config on my system instead of having to open it on Alacritty's repo on GitHub.

**Comment by kchibisov** [comment]
Was done in #6639.
