### ISSUE TITLE
Library crate for frontend details like rendering and windowing

### ISSUE THREAD

**Issue by agausmann** [alacritty/alacritty#6214]
It would be nice to have the rendering (and optionally windowing) portions of the `alacritty` crate refactored into a library crate. It would allow an application to "just spawn an Alacritty window" and have mainly a streaming I/O interface for reading user input and writing data back to the terminal.

I looked at `alacritty_terminal` but it doesn't have a lot in terms of rendering, it seems to just tell you _what_ to render via `RenderableContent`. Which means it is still up to the library user to handle all the details and calculations related to font sizes, terminal sizes and text rendering in general. That would mean re-doing a lot of work already done by the `alacritty` crate which I don't think would be very useful to duplicate.

See [librterm](https://github.com/BigRedEye/librterm) as an example of roughly the level of abstraction I'm looking for.

The motivation for this, in my case, is building out a cross-platform terminal specifically for connecting to serial ports. Another alternative that I've briefly considered is bundling `alacritty` as a standalone executable, and also creating a cross-platform executable for configuring the serial port and forwarding its I/O to stdio, so that I can invoke Alacritty with something like  `-e path/to/open_serial.exe COM3 2000000`

**Comment by chrisduerr** [comment]
I really don't see what you would gain from having `alacritty` as a library here?

It seems like you want terminal done by the library, rendering done by the library, but then that leaves nothing that isn't done by the library? That literally just creates an entire Alacritty application that cannot be embedded into anything, but instead is just a separate blog attached to whatever program you're writing.

**Comment by agausmann** [comment]
And besides, finding a good API surface to factor out would take a lot of time and effort on my end, and then would have to pass review if I wanted to get it officially supported. So I don't think it is worth pursuing if there is not much interest for it.
