### ISSUE TITLE
hyperlink text is cut short by ECMA-48 SGR reset sequence

### ISSUE THREAD

**Issue by benoit-pierre** [alacritty/alacritty#6215]
### To reproduce

```shell
▸ printf '\e]8;;https://github.com/alacritty\e\\\e[36mAla\e[2mcri\e[0mtty\e]8;;\e\\\n'
Alacritty
└────┴──── the resulting link spans this part only
```

The same test work as expected in kitty and gnome-terminal.

### System

OS: Linux
Version: alacritty 0.11.0-dev (2a676dfa)
Linux/BSD: X11

**Comment by kchibisov** [comment]
That's kind of strange that cursor reset doesn't reset hyperlink, given that it was advertised as a cell attribute, since reset should remove all attributes, however it seems like it should survive reset.

**Comment by shmup** [comment]
hyperlinks are also "cut short" in the case of the url wrapping, which probably could go in a new ticket, but this one is open so I'll take a risk:

![image](https://user-images.githubusercontent.com/118710/180628531-6e873dd0-d72f-45ab-989a-a92d1770e92f.png)

**Comment by kchibisov** [comment]
I think that you are not using hyperlink escape sequance here, but rather normal links, which is expected. Hyperlinks do highlight accross the multiple lines.

**Comment by shmup** [comment]
Something I'll have to learn about: the notion of **hyperlinks** (opposed to links) in alacritty. I'm new here.

**Comment by kchibisov** [comment]
The hyperlinks isn't something related to alacritty in particular, it's more of a common thing across the terminals, and refers to OSC 8 escape sequene support. Normal url that alacritty detects on its own has nothing to do with it. We detect multiline URLs, but the line must be naturally wrapped for example in less.

**Comment by dandavison** [comment]
@kchibisov can I check -- are you 100% certain this bug has been fixed? I built current master c5ae05e810a5866a9133b2e88edba3a42706319f on MacOS and it doesn't seem fixed to me:

<img width="757" alt="image" src="https://user-images.githubusercontent.com/52205/191748840-870befbe-bdfa-452a-a852-3a9582606cfa.png">

That `printf` command is the same one as in this issue description:

```
printf '\e]8;;https://github.com/alacritty\e\\\e[36mAla\e[2mcri\e[0mtty\e]8;;\e\\\n'
```

For comparison, in Wezterm the hyperlink extends to the end of the text.

**Comment by kchibisov** [comment]
Works for me on the same commit, just ensure you're not in tmux or anything like that.

**Comment by dandavison** [comment]
> Works for me on the same commit, just ensure you're not in tmux or anything like that.

Oh sorry, I am in tmux. (I'm running tmux with a patch applied that enables OSC8 hyperlinks, and it looks like the patch doesn't handle this edge case.)
