### ISSUE TITLE
scrolling in alacritty broken by wlroots development version

### ISSUE THREAD

**Issue by anonymous-user** [alacritty/alacritty#6218]
I recently noticed that mouse scrolling was not working in alacritty. I first noticed it in nvim but I already tried in less and the terminal itself and it didn't work either. I booted into X11/awesomewm and it worked there. I initially was running alacritty 0.10.1 but I also tested the latest git version.

I did recently switch to the git versions of sway and wlroots from the stable ones and I confirm that going back to the stable versions restores scrolling in alacritty. I am guessing it is specifically wlroots.

### System

OS: ArchLinux
Version: alacritty 0.11.0-dev (2a676dfa)
Linux/BSD: Wayland
sway 1.8-dev-6b97c4fa
wlroots 0.16.0.r5617.add44b3e2

### Logs
Keyboard and bindings: `alacritty --print-events`
[alacritty.log](https://github.com/alacritty/alacritty/files/9146139/alacritty.log)

**Comment by chrisduerr** [comment]
Define "broken"? Does it just not do anything?

**Comment by anonymous-user** [comment]
Sorry about that; I should have clarified. Scrolling with the mouse wheel is broken. Nothing happens.

**Comment by chrisduerr** [comment]
Considering you're apparently running a development version of sway and it worked previously in Alacritty, have you tried the latest stable sway?

**Comment by anonymous-user** [comment]
I tested with sway and wlroots stable and then sway and wlroots development version. Using the stable version works fine. I did not try using stable sway with development wlroots though. Not sure if that would even work.

**Comment by chrisduerr** [comment]
> Using the stable version works fine

So considering you're using a development version of sway and the stable version works fine. What makes you think the issue is in Alacritty?

**Comment by anonymous-user** [comment]
Scrolling in other apps such as Firefox and kitty still worked.

**Comment by kchibisov** [comment]
that's a wlroots bug, please update it.

**Comment by kchibisov** [comment]
Ah, you can't update yet, so you can downgrade wlroots.

https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3652
