### ISSUE TITLE
Can not open Alacritty in web app on mac

### ISSUE THREAD

**Issue by Duanjax** [alacritty/alacritty#6220]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

can not open alacritty in web app?

### System

mac M1 pro

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by chrisduerr** [comment]
Alacritty isn't supposed to be opened in whatever "web app" you're talking about.
