### ISSUE TITLE
Bash `clear`/C-l leaves extra lines in scrollback

### ISSUE THREAD

**Issue by jasonhan-vassar** [alacritty/alacritty#6222]
I noticed that clearing the screen using `clear` or Control+L in Bash leaves the current line in the scrollback. To reproduce, open an Alacritty window and clear the screen. Your scrollback should look something like this (notice the duplicate line despite not entering anything):
<img width="960" alt="Screen Shot 2022-07-22 at 7 50 46 PM" src="https://user-images.githubusercontent.com/34594853/180581475-85b13b05-d0b1-4396-bbd7-0fa780b5db16.png">

I'm actually not sure if this is something Alacritty has control over. I asked about this and other users have said their terminal emulators do not experience this. Assuming Bash/Readline is consistent, do the other terminals come with some kind of hack for this?

<img width="765" alt="Screen Shot 2022-07-22 at 7 46 28 PM" src="https://user-images.githubusercontent.com/34594853/180581666-263d9765-a799-421a-af45-6111d42ecee8.png">

### System

OS: macOS 12.4
Version: alacritty 0.11.0-dev (3bfc4c28)

**Comment by kchibisov** [comment]
Does this work `printf '\033[2J\033[3J'`?

**Comment by jasonhan-vassar** [comment]
@kchibisov Not really, that just clears the entire scrollback (and it leaves some weird whitespace at the top afterwards). Can you reproduce that?

**Comment by kchibisov** [comment]
So you don't have anything left in the scrollback?

>that just clears the entire scrollback (and it leaves some weird whitespace at the top afterwards

That's how it works and suppose to work. Should be the same in other terminals, and that's how clear is implemented, except that it also moves the cursor to the right location.

Seems like everything is working as expected? Might be some issue with your bash initialization (would suggest to try other shell).

**Comment by jasonhan-vassar** [comment]
Apologies for not being clear. I would like for `clear` to _not_ remove all scrollback. I thought the default behavior was to push all of the scrollback upwards without actually clearing it — you can later scroll back up to access the history. Can you confirm the default `clear` does this (not the `printf`)?

My main complaint was that `clear` leaves your current prompt in the history in Alacritty, but not in certain other terminal emulators like xterm on Ubuntu. Do you know if this is an xterm hack?

**Comment by kchibisov** [comment]
If you want to not remove the scrollback then use `ctrl + l`.

`clear` should remove everything. If you are on mac try using latest ncurses + bash (whatever comes from brew or you've build yourself).

**Comment by jasonhan-vassar** [comment]
The thing is, using `ctrl + l` leaves my current prompt behind in the history as well. If you are on macOS, try pressing `ctrl + l` many times. You will notice your history will be filled with empty prompts. I've also been using the latest Bash and ncurses from `brew`.

However, the good news is that I just stumbled upon `clear -x`! That works exactly how I want, but I can't figure out why it works. After binding it (`bind -x '"\C-l": clear -x'`), I can press `ctrl + l` as many times as I want without adding extra clutter to the scrollback. From the [manpage](https://manpages.ubuntu.com/manpages/focal/man1/clear.1.html),
> `-x`: do  not  attempt  to  clear  the terminal's scrollback buffer using the extended "E3" capability.

I'm assuming it's a weird macOS-related issue? I'll look into what the "E3" capability means. If you know anything about this, please let me know. Thank you for your help with debugging!

**Comment by chrisduerr** [comment]
> The thing is, using ctrl + l leaves my current prompt behind in the history as well. If you are on macOS, try pressing ctrl + l many times. You will notice your history will be filled with empty prompts. I've also been using the latest Bash and ncurses from brew.

That's exactly how it's supposed to work, yes. When you press CTRL + L your **entire** screen is cleared, the next prompt you get is then a **fresh** prompt newly drawn by your shell. So even though it might look the same and might still have the same content, your shell explicitly drew the same prompt again.

So having the old prompt still in the history is intentional, because your shell might not necessarily redraw the shell the exact same way it was before.

**Comment by jasonhan-vassar** [comment]
I see, thanks for clearing that up! The default behavior makes a lot of sense.
