### ISSUE TITLE
Broken neovim tab highlight

### ISSUE THREAD

**Issue by Integralist** [alacritty/alacritty#6227]
### System

OS: macOS
Version: 0.10.1

### Details

I'm using https://github.com/akinsho/bufferline.nvim but noticed a broken tab highlight (see first tab in below screenshot) and I'm not sure how to fix it... 

<img width="530" alt="181060407-9403add3-377d-44bb-b550-6d727aec78a1" src="https://user-images.githubusercontent.com/180050/181256508-ae953969-7de0-43dc-874f-bd1821bf003b.png">

This doesn't appear to be a neovim issue.

I first checked whether this was happening with all the colourschemes I had installed (it was).

I then tried creating a reduced test case of my config (e.g. remove all plugin setup except for the bufferline plugin) but I was still seeing the issue.

I then tried in the macOS terminal emulator and although the colour schemes were completely messed up in that terminal it looked like the weird highlight wasn't showing. Now that could be because the rest of the colourscheme was totally broken anyway.

Does anyone have any experience with Alacritty and neovim and whether there's any special configuration needed to make them play nicely together?

Thanks!

**Comment by chrisduerr** [comment]
How is it broken? Why are you saying that it doesn't appear to be a neovim issue?

**Comment by Integralist** [comment]
OK so everything works fine in neovim, except when run inside tmux. 
When running neovim in tmux, then this tab highlighting issue appears.
