### ISSUE TITLE
Support meta/alt keys in Neovim on Mac

### ISSUE THREAD

**Issue by tbodt** [alacritty/alacritty#623]

**Comment by jwilm** [comment]
What does "support" mean to you? It's possible today to assign key bindings using those modifiers. On Linux, Alt+key sends the appropriate escape sequence.

**Comment by tbodt** [comment]
Just tried and turns out it works in fish. It doesn't work in Neovim for some reason, though

**Comment by tbodt** [comment]
And on Linux it works in Neovim, so I guess this is a Mac issue

**Comment by KKPMW** [comment]
alt-key combinations work for me using neovim but I needed to send escape characters when pressing alt.

For example if you want alt-a to work in neovim, add this to the config file:

` - { key: A,        mods: Alt,       chars: "\x1ba"}`

This means: after pressing the "a" key with "alt" modifier the "esc" (\x1b) + a (a) key combination is sent. Something somewhere down the line interprets <holding>esc+a as alt+a and it works.

**Comment by eraserhd** [comment]
@tbodt Could this be related to #1610 ?  Are only some alt keys working?

**Comment by tbodt** [comment]
Alt keys are producing diacritics, which explains why they weren't doing anything in neovim.

**Comment by shendypratamaa** [comment]
> @tbodt I got alt-key combinations to work using neovim but I needed to send escape characters when pressing alt.
> 
> For example if you want alt-a to work in neovim, add this to the config file:
> 
> ` - { key: A, mods: Alt, chars: "\x1ba"}`
> 
> This means: after pressing the "a" key with "alt" modifier the "esc" (\x1b) + a (a) key combination is sent. Something somewhere down the line interprets esc+a as alt+a and it works.
> 
> And you have to write one line for every character.

its work yeaaaaaaaay 💯

**Comment by chrisduerr** [comment]
Closing as duplicate of #62.
