### ISSUE TITLE
When setting a Font - Did not find expected <document start>

### ISSUE THREAD

**Issue by diyfan** [alacritty/alacritty#6230]
OS: Linux
Version: `0.10.1
WM: BSPWM
Compositor : Compton (Picom)
Display Server : X11

Font that I'm trying to use : mononoki Nerd Font

**Comment by chrisduerr** [comment]
If you have an issue with the config, please share your entire config. This certainly isn't an issue with Alacritty, but if you still want to post your config below I can take a look.

**Comment by diyfan** [comment]
it is the default config. Whenever I play with transperancy

**Comment by chrisduerr** [comment]
Which makes it not the default config.
