### ISSUE TITLE
ALACRITTY_SOCKET is not unlinked on exit

### ISSUE THREAD

**Issue by ngortheone** [alacritty/alacritty#6231]
Alacrity socket is bound to a filesystem path on start and is never cleaned up on exit. Over time lots of dead sockets are accumulated.

```
ls -1 $XDG_RUNTIME_DIR

Alacritty-wayland-1-40209.sock
Alacritty-wayland-1-51850.sock
Alacritty-wayland-1-52324.sock
Alacritty-wayland-1-32626.sock
Alacritty-wayland-1-70168.sock
....
```

This is expected Unix behavior, `man 7 unix`:

> Binding to a socket with a filename creates a socket in the file system that must be deleted by the caller when it is no longer needed (using [unlink](https://linux.die.net/man/2/unlink)(2)). The usual UNIX close-behind semantics apply; the socket can be unlinked at any time and will be finally removed from the file system when the last reference to it is closed.

It looks like Rust has no `unlink` on `UnixListener`. 
Please consider one of the 2 options:
- simply removing the socket file upon exit (somewhere after https://github.com/alacritty/alacritty/blob/master/alacritty/src/main.rs#L203)
- wrap `UnixListener` into our own type and implement `Drop` trait for it that would remove the file

-----
EDIT:
alacritty 0.10.1
OS: FreeBSD 14-CURRENT

**Comment by chrisduerr** [comment]
Alacritty does clean up the sockets, how exactly are you closing it? The `Drop` implementations will only get called when the program is properly shut down. Are you frequently -9'ing terminals?

**Comment by ngortheone** [comment]
I am closing the terminal by pressing CTRL-D in my shell

**Comment by ngortheone** [comment]
It does look like alacritty crashes on every exit, which would explain this. Taking a look into a .core file

**Comment by ngortheone** [comment]
Closing issue for now as it not likely related to the socket cleanup. I see SIGBUS in the corefile :thinking:

**Comment by mahrud** [comment]
Running into this issue as well. I have a systemd service defined as:
```
[Service]
Environment=DISPLAY=:0
ExecStart=alacritty --daemon
Restart=on-failure
RestartSec=5s
```
and noticed that there's a buildup of orphaned socket files:
```
$ ls -1 /var/run/user/1000/
Alacritty-:0-44820.sock
Alacritty-:0-45057.sock
Alacritty-:0-45087.sock
```
