### ISSUE TITLE
Control + Space passed as Space (intermittent)

### ISSUE THREAD

**Issue by LionyxML** [alacritty/alacritty#6234]
### System

OS: macOS
Version: alacritty 0.10.1 (2844606)

### Issue
I have this strange issue where intermittently, some bind will no longer issue its modifier.

Most notably: Control + Space (this marks the text for selection on Emacs editor)

Now and then, twice a day, no more control is passed and only a space hits the editor and any other thing inside the window.

I have to manually close and open another alacritty window, and it works again.

The problem happens not only inside emacs but inside anything on the buggy window. I also have shortcuts for Command something mapped to ESC+something, and those seems not to work also.

My alacritty dot file (if it helps): 
https://github.com/LionyxML/dotalacritty/blob/main/alacritty.yml

**Comment by chrisduerr** [comment]
See https://github.com/alacritty/alacritty/issues/1359.

**Comment by LionyxML** [comment]
I am sorry, I am failing to find out what revision and or branch this was solved. I'd love to test it.

**Comment by chrisduerr** [comment]
It wasn't. That's why the issue I linked is still open.

**Comment by LionyxML** [comment]
Oh man, tks. I was messing with all sorts of broken keybinds now trying to figure out how much wrong I was, lol.

**Comment by perapp** [comment]
FYI. As a workaround I added the following to my alacritty.yml until #1359 is resolved:

```
key_bindings:
   - { key: Space,     mods: Control,                    chars: "\x00"    }  # workaround https://github.com/alacritty/alacritty/issues/6234
```
