### ISSUE TITLE
setting bell.duration to 0 should disable window urgency as well

### ISSUE THREAD

**Issue by prometheanfire** [alacritty/alacritty#6235]
### System

OS: Linux
Version: 0.10.1
Linux/BSD: Wayland, Sway

It seems like the addition of urgency for wayland was not use configurable.  I'm not sure if bell.duration is the best way to hide it, or if another config option should be used, but I feel the window urgency option should be able to be disabled (constant alerts in another virtual desktop is no fun).

**Comment by kchibisov** [comment]
There's an escape sequence just for that. `printf "\e[?1042l"`

Setting urgent based on the duration isn't an option since I want ugrent, but not visual bell.

**Comment by prometheanfire** [comment]
where am I supposed to put that if I do NOT want urgant or a visual bell?  The configuration is unclear.

**Comment by chrisduerr** [comment]
Your shellrc should work.
