### ISSUE TITLE
Window title bar on secondary monitor is click through

### ISSUE THREAD

**Issue by DuckDuckWhale** [alacritty/alacritty#6237]
### System

OS: Ubuntu 22.04
Version: `alacritty 0.11.0-dev (1df32309)`
Linux/BSD: Wayland, Gnome, Nvidia

### Problem

When launching on my primary monitor, everything works. When launching on my secondary monitor, Alacritty seems to glich a bit on the border (briefly showing an incomplete border, and so brief and inconsistent that I can't get a screenshot of it), then when I click and drag on the title bar I expect to be able to move the window, but the window behind it gets the mouse focus instead.

**Comment by chrisduerr** [comment]
Which compositor?

**Comment by DuckDuckWhale** [comment]
It's Gnome, so I guess it's Mutter. I don't know how to verify that though.

**Comment by chrisduerr** [comment]
@kchibisov Are you aware of any GNOME Wayland issues like this?

**Comment by kchibisov** [comment]
First time seeing something like that, and I don't have a way to test it anyway, since I use GNOME only in vm. But I don't see how it could work on one monitor, but not other.

Are you using fractional scaling on some monitor?

**Comment by chrisduerr** [comment]
Yeah the strange behavior also seems like something that could easily be an issue in GNOME.

**Comment by DuckDuckWhale** [comment]
I was not using fractional scaling, and the issues was that the launching monitor matters but not the monitor that it is moved to. If I launch one on my primary monitor and one on my secondary monitor and move the latter next to the former on the primary monitor, the latter is still click through while the former isn't.

And somehow I can't reproduce this anymore just after an update involving Nvidia drivers and rebooting (I didn't test before rebooting though but this is my first reboot since last test seven days ago). So it might have something to do with that? Closing this for now and I'll reopen if I see it again.
