### ISSUE TITLE
`alacritty msg create-window` should support configuration

### ISSUE THREAD

**Issue by AlexApps99** [alacritty/alacritty#6238]
I've been using `alacritty msg create-window` to manage multiple terminals at once, which works great.
However, it does not support configuration flags, such as `-o=...` or `--config-file ...`.

I would imagine this could be due to technical reasons, as settings like `ipc_socket` or `debug.*` only make sense from an instance, rather than an individual window.

I request that window-specific configuration is implemented in a way that overrides the instance configuration, using the same flags as currently exposed on the main executable.

If an instance-specific configuration flag such as `ipc_socket` or `debug.*` is set to a mismatching value, either on the command line or in a file, when it doesn't make sense to override, alacritty could throw an error.

I'm guessing that configuration would need to be refactored for this change to be implemented, because it's probably not structured per-window at this time, so I don't expect it to be easy to implement.

### System

OS: Arch Linux
Version: `alacritty 0.10.1`
Linux: Wayland, Sway

### Logs

```
$ alacritty msg create-window -o="colors.primary.background='#FFFFFF'"
error: Found argument '-o' which wasn't expected, or isn't valid in this context

USAGE:
    alacritty msg create-window [FLAGS] [OPTIONS]

For more information try --help
```

**Comment by chrisduerr** [comment]
See https://github.com/alacritty/alacritty/pull/6174.

**Comment by aswadsun** [comment]
Rather than using `config` subcommand, would it be better if we can add option directly to `CreateNewWindow` action, so we can create custom key binding, example: 

`alacritty msg create-window -o 'font.size=15' -o 'window.decoration=full'`
`  - { key: N, mods: Control|Shift, action: CreateNewWindow, options: [ "font.size=15", "window.decoration=full" ] }`

Thanks in advance,
Aswad

**Comment by kchibisov** [comment]
Yeah, adding `-o` should be trivial now and I think it was one of the goals of IPC subcommand to config.
