### ISSUE TITLE
Mouse pointer no longer hiding when typing

### ISSUE THREAD

**Issue by decibyte** [alacritty/alacritty#6239]
I have the following in my configuration:
```
mouse:
  hide_when_typing: true
```

After upgrading to Ubuntu 22.04, the mouse pointer keeps showing. I'd assume it's because I was also switched from X11 to Wayland as part of the upgrade. But it's just an unqualified guess.

### System
alacritty 0.11.0-dev (56a69c0b)
Ubuntu 22.04
Wayland, Gnome 42.2

**Comment by kchibisov** [comment]
This will fix it https://github.com/alacritty/alacritty/pull/6079

**Comment by decibyte** [comment]
@kchibisov thanks a lot for fixing this!
