### ISSUE TITLE
Alacritty does not launch if the `working_directory` setting uses ~ or $HOME

### ISSUE THREAD

**Issue by assayire** [alacritty/alacritty#6241]
Alacritty does not launch if the `working_directory` setting uses `~` or `$HOME` in the path. Is there a workaround for this if a fix is not planned for the near future?

### System

OS: macOS
Version: `Version 0.10.0 (1)`

**Comment by kchibisov** [comment]
That's kind of expected since one is environment variable and the other is a shell alias for home directory. So it fails to start when you pass no existent dirs, since we don't check whether what you've provided is a env variable or a shell alias.

**Comment by assayire** [comment]
Understood. Is there a way to specify the home directory using say a variable or something of the sort without hard coding the username in the path?

I have tWo machines with different usernames, and like to use/ share the same config file from source control.

**Comment by kchibisov** [comment]
It should by default open in home directory? I'm not sure that you need to specify anything at all.

**Comment by assayire** [comment]
I meant the path I want to use is like ~/projects/work/ and just the home folder.

but based on your comments it looks like it’s not currently supported. Would be nice if Alscritty supports it via some predefined name/variable, say ${home}

**Comment by chrisduerr** [comment]
If you just have a single user, you might as well use the full path?

Also what happens when you specify `./` on macOS? In theory that should spawn the window in the home directory, so I don't think it's necessary to add any home variable replacement.

**Comment by chrisnc** [comment]
If you provide a relative path for `working_directory`, it should already be interpreted relative to `$HOME`, so in your example you would just do:

```
working_directory: projects/work
```

I just tried this on macOS and it works.

**Comment by chrisduerr** [comment]
Closing since my suggestion works. Thanks for testing @chrisnc.

I don't think it's worth it to add specific code for parsing fake environment variables or shell syntax here.

**Comment by assayire** [comment]
> I meant the path I want to use is like `~/projects/work/` and just the home folder.
> 
> but based on your comments it looks like it’s not currently supported. Would be nice if Alacritty supports it via some predefined name/variable, say `${home}`

This worked for me. Thanks.

**Comment by imjishan** [comment]
[shell]
working_directory = "C:\\Users\\HP"

This code is not working

### SYSTEM
Windows 10

**Comment by nixpulvis** [comment]
@imjishan did you get any errors? `working_directory` needs to be at the top level, not underneath `[shell]` or any other dictionary.

**Comment by imjishan** [comment]
> @imjishan did you get any errors? `working_directory` needs to be at the top level, not underneath `[shell]` or any other table.

Thanks :-)

**Comment by IRPotato** [comment]
`[terminal.shell]
program = "powershell"
args = [" -NoExit ", " -Command ", " cd 'C:/Users/$USERNAME/Desktop/Work/' "]`

this works for me

**Comment by SymphonySimper** [comment]
You can use this in Windows to set the starting directory to the user's home.

## `pwsh`
```toml
[terminal.shell]
program = "pwsh"
args = ["-WorkingDirectory", "~"]
```
## `powershell`
```toml
[terminal.shell]
program = "powershell"
args = ["-noexit", "-command", "cd ~"]
```
