### ISSUE TITLE
Feature request: Ability to check if an updated version of Alacritty available from terminal

### ISSUE THREAD

**Issue by assayire** [alacritty/alacritty#6243]
Support a command to check if there is an updated version of Alacritty.

Example(s): 

```
!update --check # or :update --check
```

or

```
alacritty update --check # Without enforcing alacritty to be on the path but use the current running instance.
```

**Comment by kchibisov** [comment]
There's no desire for any of that. If you want to track releases, just subscribe for releases on alacritty repo. There's also a way to get RSS feed for that.

In general you should use some sort of package manager to install alacritty and I'm pretty sure all of them can track updates.

**Comment by assayire** [comment]
I have to be using without package manager or admin rights stuff. So I will be (actually I am) running it off a directory away from permission problems. Hence the feature request.

But I am glad you mentioned about the RSS feed. That should help achieve what I am looking for. Thanks.

**Comment by kchibisov** [comment]
`cargo` is also a package manager and you can use it to check for updates.
