### ISSUE TITLE
unsigned macos app

### ISSUE THREAD

**Issue by fawaf** [alacritty/alacritty#6244]
not really a bug, but macos gives the below warning when running for the first time after downloading. the app needs to be allowed in the "privacy & security" preference pane to allow alacritty to work.
![image](https://user-images.githubusercontent.com/639565/183142743-c3a94edd-d0fd-4865-a3ea-71b6f35a590d.png)

### System

OS: macOS
Version: `alacritty 0.10.1 (2844606)`
Linux/BSD: X11/Wayland, DE or Compositor and WM

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by kchibisov** [comment]
That's expected, we're not going to pay apple to ship free software.
