### ISSUE TITLE
Speak selection on macOs not working

### ISSUE THREAD

**Issue by blubber** [alacritty/alacritty#6246]
### System

OS: macOs
Version: alacritty 0.10.1 (2844606)

### Problem
MacOs has an accessibility feature 'Speak selection' (System Preferences > Accessiblity > Spoken content). It can be used to speak any text that is selected by the user, default keybinding is option-esc. In alacritty this doesn't work, when the keybinding is pushed it simply says 'Alacritty'. I think the problem is that the primary selection is not reported to the OS, see https://developer.apple.com/documentation/appkit/nsaccessibility?language=objc. I would try to fix this issue myself, but I'm not familiar with Rust, so any pointers and/or help is appreciated.

**Comment by chrisduerr** [comment]
I don't really have any interest jumping over hurdles to implement operating system-specific, non-standard APIs like this.

I'd maybe consider merging a PR, but even then having to manually add hooks for a billion irrelevant APIs seems like a massive waste of time. Accessibility is nice, but I don't see how this accessibility feature provides anything that others do not.
