### ISSUE TITLE
Is there a way to set/change configuration on the fly?

### ISSUE THREAD

**Issue by decibyte** [alacritty/alacritty#6247]
I understand that I can override configuration options by running Alacritty like `alacritty --option=cursor.style=Beam`. Is there a way to change the configuration of an already running instance of Alacritty without having to edit the configuration file (which I know is beautifully reloaded automatically)?

If not, this could be considered a feature request :)

**Comment by kchibisov** [comment]
See this https://github.com/alacritty/alacritty/pull/6174.

Duplicate of #472.
