### ISSUE TITLE
Fix column for gg and G movement in Vi Mode

### ISSUE THREAD

**Issue by danijar** [alacritty/alacritty#6248]
In Vi Mode, <kbd>g</kbd><kbd>g</kbd> jumps to the end of the first line and <kbd>G</kbd> jumps to the end of the last line. Vim instead jumps to the beginning of the first or last line, which is more useful. Would you consider adjusting the behavior to be in line with Vim?

**Comment by kchibisov** [comment]
They both should jump to the start of the lines right now? Not sure how it goes to the last column for you?

**Comment by danijar** [comment]
Hmm. I just tried again in another alacritty window and gg still jumps to the end of the first line where G jumps to the second character (from the left) of the last line. Can I help further debug the inconsistency somehow?

**Comment by kchibisov** [comment]
Are you using the latest version and what operating system are you on?

**Comment by danijar** [comment]
I installed via `cargo install alacritty` and `alacritty --version` says `alacritty 0.10.1 ()`. My operating system is Debian Testing.

**Comment by chrisduerr** [comment]
Considering you're talking about `gg`, rather than just `g`, you might not be using Alacritty's vi mode at all. But Alacritty definitely jumps to the beginning.
