### ISSUE TITLE
Dimming colors when window is out of focus

### ISSUE THREAD

**Issue by danijar** [alacritty/alacritty#6250]
I've just switched from urxvt to alacritty, thank you for this fantastic terminal!

One feature I really liked about urxvt is that you can dim the colors by a configured percentage towards the background color when the window is not focused (e.g. `URxvt.fading: 30`).

When having many terminal windows open, this can really help the user to focus on the currently active window.

Does this seem like a feature that would fit into alacritty?

**Comment by chrisduerr** [comment]
https://github.com/alacritty/alacritty/issues/1982
