### ISSUE TITLE
Fallback font not working anymore

### ISSUE THREAD

**Issue by willian** [alacritty/alacritty#6251]
### System

OS: macOS
Version: 0.10.1 (2844606)

---

I tried to add two `family` entries and only the last one is used, but I would like to use both font families or have a way to set a specific font to use with Non-ASCII text like iTerm2 allows.

In iTerm2, I use `Dank Mono` as the main font and `Hack Nerd Font Mono` as Non-ASCII Font:
<img width="1055" alt="Screen Shot 2022-08-09 at 19 12 18" src="https://user-images.githubusercontent.com/19230/183770972-64b77206-37b0-4ea7-a170-0411789741f3.png">

This is the result:
<img width="1136" alt="Screen Shot 2022-08-09 at 19 14 08" src="https://user-images.githubusercontent.com/19230/183771200-bae394b6-5cee-428c-be08-c6ea445260f3.png">

In Alacritty, if I set both `Dank Mono` and `Hack Nerd Font Mono`, I only get `Dank Mono` (see the icons from the right bottom corner are broken):
<img width="1024" alt="Screen Shot 2022-08-09 at 19 15 15" src="https://user-images.githubusercontent.com/19230/183771346-49392578-22ec-41a4-b58f-ed4ef9cdccbf.png">

**Comment by chrisduerr** [comment]
Font fallback is automatic and configured by your system, specifying multiple fonts is not a thing.
