### ISSUE TITLE
Is there a way to change the search keybind to, let's say, ctrl+ alt + h, for example?

### ISSUE THREAD

**Issue by rizzini** [alacritty/alacritty#6256]
I can't call `SearchBackward` directly without toggling the Vi mode before, so I end up having to press ctrl+ alt + h two times. It might be a very basic question, but I'm struggling with it. 
```
- { key: H, mods: Control, action: ToggleViMode }
- { key: H, mods: Control, mode: Vi, action: SearchBackward}
```

**Comment by chrisduerr** [comment]
You can trigger search without being in vi mode. If you want to enter vi mode and start search you'll have to do so in two steps.

**Comment by rizzini** [comment]
Oh.. I didn't actually try `SearchBackward` without `mode: Vi`. Thanks.
