### ISSUE TITLE
WaitForSingleObject seems to receive a key release event without releasing the key

### ISSUE THREAD

**Issue by iFuSiiOnzZ** [alacritty/alacritty#6258]
### Steps to reproduce

C source code: https://pastebin.com/aHanPw4q

Use a C compiler as Visual CL. Build the source code posted on "C source code". Run the application build on Alacritty and press a key without releasing it, a key press and key release event is generated continuously.

### Expected Behavior
Key press generates an event where "KeyEvent.bKeyDown" is true.
Key release generates an event where "KeyEvent.bKeyDown" is false.

### Actual Behavior
When key is press an event is sent having the "KeyEvent.bKeyDown" to true, afterwards it generates a key release event, "KeyEvent.bKeyDown" to false, and it continuously generating key press and key release events without releasing the key.

PS: Tested on Windows Terminal and it has the same problem, meanwhile  Command prompt and Powershell it works as expected.
https://github.com/microsoft/terminal/issues/13734

### System

OS: Windows
Version: alacritty.portable v0.10.1 (installed with chocolatey)

**Comment by chrisduerr** [comment]
Windows issue.
