### ISSUE TITLE
Alacritty renders a wrong glyph

### ISSUE THREAD

**Issue by fingolfin0** [alacritty/alacritty#6260]
Alacritty renders the glyph "╘" (U2558) where it should render the glyph "╧" (U2567). It doesn't depend on the font.

### System

OS: Manjaro Linux, X11, KDE with kwin.
Version: alacritty 0.10.1 ().

**Comment by kchibisov** [comment]
Could you try latest master, I think it should be resolved there.

**Comment by fingolfin0** [comment]
> Could you try latest master, I think it should be resolved there.

Thanks, master version renders this correctly!

Version: alacritty 0.11.0-dev (5549e9eb)
