### ISSUE TITLE
The window position is moved after exiting fullscreen.

### ISSUE THREAD

**Issue by lolicon0930** [alacritty/alacritty#6262]
> Please describe the bug that you have found:

The window position is moved after exiting fullscreen.
> and what you would expect to happen instead:

The window position returns to its original position after exiting fullscreen.
### System
OS: Debian GNU/Linux bookworm/sid x86_64
Version: alacritty 0.11.0-dev (5549e9e)
Display server: Xorg 7.7, xorg-server 21.1.4
Compositor: picom (v9.1)
WM: fvwm3 1.0.5 (cee5f75)
### Config
`.alacritty.yml`
```
key_bindings:
  - { key: F11, action: ToggleFullscreen }
```
### Logs
[Alacritty-161242.log](https://github.com/alacritty/alacritty/files/9332492/Alacritty-161242.log)

https://user-images.githubusercontent.com/14966910/184518235-8ee6a96c-7f7e-42f5-8d77-2430ce24a719.mp4

**Comment by lolicon0930** [comment]
Set to other key bindings receive the same result.
```
key_bindings:
  - { key: Return, mods: Alt, action: ToggleFullscreen }
```

**Comment by chrisduerr** [comment]
I cannot reproduce this on i3, have you tried a different WM?

**Comment by lolicon0930** [comment]
I tried it on MATE DE before and it seems to be normal, but only alacritty has such a situation under FVWM, so I decided to report here first. I'm not sure why this problem occurs. I'll try with other stacking WM later.

**Comment by chrisduerr** [comment]
Since Mate and i3 seem to work just fine and we haven't gotten any other reports (so probably most others also work fine), I'm gonna assume this is a FVWM peculiarity. Which wouldn't surprise me considering I've never heard of it either.

**Comment by lolicon0930** [comment]
I just tried openbox, maybe it's not alacritty's problem, sorry to bother you guys, I'll report to FVWM.
