### ISSUE TITLE
alacritty does not show the right cursor after exiting nvim,vim or vi

### ISSUE THREAD

**Issue by Kaanta7** [alacritty/alacritty#6263]
Hello, i use a Beam Cursor for my terminal, but when i use any editor, the cursor turns into a block(not hollow, i disabled that).

**Comment by chrisduerr** [comment]
That's because it doesn't reset your cursor. You have to do it yourself.

**Comment by XavierFigari** [comment]
How do you reset the cursor after exiting vim or neovim ?

**Comment by chrisduerr** [comment]
```
au VimLeave * set guicursor=a:hor100
```

**Comment by XavierFigari** [comment]
Thanks ! In case someone needs it, I also found this solution in [this thread](https://github.com/alacritty/alacritty/issues/5450#issuecomment-929797364) :
Put this in your ~/.config/nvim/nvim.lua : 
``` lua
vim.api.nvim_create_autocmd("ExitPre", {
	group = vim.api.nvim_create_augroup("Exit", { clear = true }),
	command = "set guicursor=a:ver90",
	desc = "Set cursor back to beam when leaving Neovim."
}) 
```
