### ISSUE TITLE
Implement x,y coordinates + size lengh,height in alacritty??

### ISSUE THREAD

**Issue by Nonie689** [alacritty/alacritty#6269]
Could you please Implement a parameter to set the size and the coordinates of an alacritty terminal that will be new opened??

like:

 alacritty -t "NewAlacrittyExecTitke" -e thecommand --position 100,100 --size 300,200

### System

alacritty 0.10.1 ()
Linux archlinuxuser-ms7376 5.18.16-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Wed, 03 Aug 2022 11:25:10 +0000 x86_64 GNU/Linux
xterm-256color

archlinux-based/wayland/wayfire

**Comment by chrisduerr** [comment]
Why and how would you expect that to work with non-1 DPI factor?

**Comment by kchibisov** [comment]
Besides your request. You can't do any of the positioning stuff on Wayland. And we do support opening with some position and sizes.
