### ISSUE TITLE
Letters look like blocks instead of regular text. Completely fresh install, nothing configured.

### ISSUE THREAD

**Issue by leet0rz** [alacritty/alacritty#6271]
So I just installed the newest version of alacritty from the .msi on windows 10. I run alacritty and this is what shows up:
![d69RUEO 1](https://user-images.githubusercontent.com/29175192/185010046-1ea1e215-446f-4e6b-8cb7-bc7022e78ab5.png)

I have done no configuration what so ever, I installed it and ran it, thats it.

### System

OS: Windows
Version: Newest version on current posting date

### Logs

Crashes: None
Font/Terminal size: standard for windows
Keyboard and bindings: Cant see, look at the picture

**Comment by chrisduerr** [comment]
Which GPU?

**Comment by leet0rz** [comment]
> Which GPU?

Thanks for pointing me in the right direction. Seems my GPU was set to integrated. Now it works after putting it to high performance NVIDIA.
