### ISSUE TITLE
Need to clarify meaning of `CopySelection/PasteSelection` commands

### ISSUE THREAD

**Issue by tribals** [alacritty/alacritty#6275]
```
#   - CopySelection
#       Copy from the selection buffer.
```

Reference: https://github.com/alacritty/alacritty/blob/7d708d53f7ecb4c64db10ae44e7f4fca47c29a85/alacritty.yml#L714-L715

It is not clear, to which selection? According to freedesktop, they all are "selections". Of them, three are common ones:

>  There are three standard selections defined in the ICCCM: PRIMARY, SECONDARY, and CLIPBOARD.

Reference: https://www.freedesktop.org/wiki/Specifications/ClipboardsWiki/

So, it would be nice to have direct reference in docs, tho which of those three it copies/pastes?

So, even there is `Copy/Paste` commands, which obviously handles `CLIPBOARD` selection, we still have two to choose.

**Comment by chrisduerr** [comment]
There's really only one that is ever used, shouldn't be necessary to explicitly state that we're using the one everyone else is using.

**Comment by tribals** [comment]
Then, which one is "ever used"?

**Comment by kchibisov** [comment]
Primary selection buffer aka middle mouse.

**Comment by tribals** [comment]
Thanks!
