### ISSUE TITLE
Problem with installing alacritty on Linux

### ISSUE THREAD

**Issue by symaticvisuals** [alacritty/alacritty#6278]
When I cloned the project from the command provided in the docs, It's showing me error

### System

OS: Linux
**fatal: invalid branch name: init.defaultBranch =** 
![image](https://user-images.githubusercontent.com/59753906/185797456-17e924c8-d321-4c32-b60c-9872002a575a.png)

**Comment by kchibisov** [comment]
You should clone `https://github.com/alacritty/alacritty` or whatever github link will be on the default page when there's a popup to clone.
