### ISSUE TITLE
CLI argument `--class` not setting `app_id` in Wayland

### ISSUE THREAD

**Issue by alextsits** [alacritty/alacritty#6279]
### The Problem
Running `alacritty --class test` on Wayland results in an alacritty window with `app_id` set to `Alacritty` (the default value).
**Expected:** An aclacritty window with `app_id` set to `test`.

I tried setting `class:general:test` in the configuration file and the `app_id` of new alacritty windows are indeed set to `test`. So I assume that somehow the CLI value is ignored (probably because it sets the `instance` name and not `general`, see below).

### Context
This is probably related to https://github.com/alacritty/alacritty/commit/23915cfc5343859329731c50114f701997c29b1f, and in turn https://github.com/alacritty/alacritty/commit/7d708d53f7ecb4c64db10ae44e7f4fca47c29a85 that caused the initial regression.

I'm not very familiar with Rust or the Alacritty codebase. However I see that `winit` changed the API to use `with_name()` instead of `with_app_id()/with_class()` (https://github.com/rust-windowing/winit/pull/2250/commits/a78e801f13231f773e5d19818097f76f53a8b6d0) and this triggered the above changes. There I see that on Wayland the class `general` name is used as `app_id` and `instance` name is ignored.

The problem seems to be that `--class` sets the instance name instead (the previous invocation of `with_app_id()` used the `instance` name too) but the new `with_name()` ignores the instance name on Wayland.

### System

OS: Linux
Version: alacritty 0.11.0-dev (23915cfc)
Linux: Wayland, sway

**Comment by chrisduerr** [comment]
@kchibisov What was your vision on how winit consumers should use this? As far as I can tell, everything is working as planned here, right?

**Comment by kchibisov** [comment]
I think the issue is that it doesn't work anymore because the patch that was fixing X11 broke Wayland? In general maybe mapping is a bit odd so it's not expected?

In alacritty we can set both to the same value though.

**Comment by kchibisov** [comment]
Given that there's no `instance` on `Wayland` winit maps the first argument aka `general` for `appid`, however the `--class` option is setting `instance` by default. We could either map `instance` to `general` when on `Wayland` or set `general` by default with `--class`.

Other option would be to set both values at the same time when `--class foo` is passed, and I think that's the most sensible and what others do?

**Comment by kchibisov** [comment]
Besides all apps set `class` by default and not instance.
