### ISSUE TITLE
Portable version refused to open

### ISSUE THREAD

**Issue by fluentmoheshwar** [alacritty/alacritty#6284]
### System

OS: Windows
Version: 0.10.1

### Logs

---------------------------
Alacritty: Runtime Error
---------------------------
panicked at 'gl function was not loaded', D:\a\alacritty\alacritty\target\release\build\alacritty-be3798149001e1d5\out/gl_bindings.rs:11325:13

Press Ctrl-C to Copy
---------------------------
OK   
---------------------------

**Comment by kchibisov** [comment]
You should have working OpenGL drivers.
