### ISSUE TITLE
Is there any official docs?

### ISSUE THREAD

**Issue by NEX-S** [alacritty/alacritty#6286]
Sorry I didn't find any official docs :(
Can anyone help me? :+1:

**Comment by chrisgrieser** [comment]
afaik, there aren't any real docs. All of the settings [are documented here as comments here](https://github.com/alacritty/alacritty/blob/master/alacritty.yml), and [features are (very briefly) explained here](https://github.com/alacritty/alacritty/blob/master/docs/features.md).

**Comment by chrisduerr** [comment]
What kind of documentation are you looking for?

**Comment by NEX-S** [comment]
okay, thanks !
