### ISSUE TITLE
"Unable to create socket" Warning on opening the terminal

### ISSUE THREAD

**Issue by vladkosarev** [alacritty/alacritty#6287]
I am running Void Linux under WSL2 and using VSOCK (https://x410.dev/cookbook/transparently-adding-native-support-for-vsock-in-x11-apps/).
Everything works great, except every time I open a new terminal window I get this warning at the bottom. I can't figure out how to stop that from happening.

![image](https://user-images.githubusercontent.com/1223487/186916082-929d7ec6-efc9-4e5a-86d2-81bdff35ba77.png)

Is there a way to turn off this warning so that it doesn't pop up on every new terminal?

Thanks!

### System

OS: Void Linux under WSL2
Version: 0.10.1
Linux/BSD: i3

### Logs
WARNING -
```
[0.002059500s] [WARN ] [alacritty] Unable to create socket: Os { code: 2, kind: NotFound, message: "No such file or directory" }

**Comment by kchibisov** [comment]
Set this to `false` https://github.com/alacritty/alacritty/blob/791f79a02a4bbb509c257af2849e411d32f4c18b/alacritty.yml#L456

**Comment by vladkosarev** [comment]
Added `ipc_socket: false` since I didn't have it in the config. That worked, thank you!
