### ISSUE TITLE
cursor style

### ISSUE THREAD

**Issue by darksilentcore** [alacritty/alacritty#6289]
Hi

i set cursor
to Beam in Alacritty
to Bar in Helix

but when i exit from helix
terminal show cursor in Block shape

this also happens in Vim or Neovim

**Comment by kchibisov** [comment]
Your editor should reset cursor shape on exit. Neovim doesn't do that for sure.

**Comment by darksilentcore** [comment]
So
What can i do ??

a command
an alias
a config

Every solution except exit from Terminal and reopen agin is OK

**Comment by kchibisov** [comment]
This is for neovim.

`au VimLeave * set guicursor=a:ver100`

Could also reset cursor in shell`s preexec.
