### ISSUE TITLE
Alacritty does not blurs out when "opacity: 0.0" but works fine with "background_opacity:0.0". 

### ISSUE THREAD

**Issue by MenaceG** [alacritty/alacritty#6292]
Using "background_opacity:0.0" results in an error in log file
```
[0.000335808s] [WARN ] [alacritty_config_derive] Config warning: background_opacity is deprecated; use window.opacity instead
```

### System

OS: Linux(Arch)
Version: alacritty 0.10.1 ()
Linux/BSD: i3wm, picom

**Comment by chrisduerr** [comment]
That's not an error, that's a warning. Read the message, do what it says. It works. Can't figure it out? Look at the configuration file documentation, that's literally what it's there for. You've got all the information you need.

**Comment by MenaceG** [comment]
I realised my mistake, you can delete this issues
Thanks for the help
