### ISSUE TITLE
just after apply default alacritty.yml file this error have been seen

### ISSUE THREAD

**Issue by mbaneshi** [alacritty/alacritty#6296]
erasing this line or changing it may fix problem

### System

OS: macOS
Version: `alacritty --version` alacritty 0.10.1 (2844606)

###  link to screenshot
https://capture.dropbox.com/R3YlLIfSH263CYm6
### error message
Config error: invalid type: string "Histre logo histre", expected a mapping

**Comment by kchibisov** [comment]
We don't have this line in the config.
