### ISSUE TITLE
feat: Allow user to drop configuration files in a directory

### ISSUE THREAD

**Issue by setpill** [alacritty/alacritty#6301]
#### Rationale

Right now, there's 4 specific file locations where alacritty looks for configuration files. From these, other files can be imported. However, they must again be specified with the full file path, no globbing allowed. This makes it doable, but clunky to split up a monolithic config file into multiple parts.

#### Proposal

Alongside the 4 existing config file locations; ie.

1. `$XDG_CONFIG_HOME/alacritty/alacritty.yml`
2. `$XDG_CONFIG_HOME/alacritty.yml`
3. `$HOME/.config/alacritty/alacritty.yml`
4. `$HOME/.alacritty.yml`

Add 3 config directories; e.g.

1. `$XDG_CONFIG_HOME/alacritty.d`
2. `$HOME/.config/alacritty.d`
3. `$HOME/.alacritty.d`

Any config files there should then be automatically imported.

**Comment by chrisduerr** [comment]
I think that gets far too convoluted and makes an already hard to troubleshoot problem just even worse.

**Comment by manuth** [comment]
I'd love to have such a feature.
@chrisduerr what do you think of making this an opt-in feature by allowing the user to `import: ` files using wildcards?
If you think that'd be neat, I'd go forward and create an issue for this.

**Comment by chrisduerr** [comment]
No, I have zero interest in this.
