### ISSUE TITLE
Weird broken fonts on bspwm 

### ISSUE THREAD

**Issue by Trochatole** [alacritty/alacritty#6304]
### System

OS: Linux
Version: alacritty 0.10.1 ()
Linux/BSD: X11 bspwm picom
![image](https://user-images.githubusercontent.com/109000687/188327275-2398b335-faec-4ae3-a3df-ce8faf86336d.jpg)

### Logs

Crashes: Doesn’t crash
Font/Terminal size: 
![image](https://user-images.githubusercontent.com/109000687/188326841-01ca43e4-6db2-404a-af2b-6825e13a14f0.jpg)

i tried with multiple fonts any font i select does this

**Comment by chrisduerr** [comment]
You need to use a monospace font.
