### ISSUE TITLE
Alacritty cursor becomes "Block" even if "Underline" is selected after quiting an editor

### ISSUE THREAD

**Issue by Kaanta7** [alacritty/alacritty#6306]
my cursor becomes a Block after quiting my editor "nvim", in an issue that i opened some times ago someone told me to "reset the terminal", but how can i do that ? and can i make it automatic ?

**Comment by chrisduerr** [comment]
In neovim, you'd do something like this:

```
au VimLeave * set guicursor=a:hor100
```

**Comment by Kaanta7** [comment]
i put this in my init.vim or something ?
