### ISSUE TITLE
MacOS: Command+` should switch windows

### ISSUE THREAD

**Issue by RyannDaGreat** [alacritty/alacritty#6308]
Command+\` won't switch between Alacritty instances. Nearly every application on Mac supports this (including all of Apple's own apps, and every other app I could test from photoshop to chrome to texpad to sublime and vscode etc). Just as Command+tab switches between apps, Command+` is supposed to switch between windows in the same app. Alacritty doesn't do this. Could this be please be implemented?

Reason I care: It would make switching between Alacritty instances much easier, and it's a standard feature on every Mac app I've tested (I'm sure there are some exceptions, but I couldn't find any). Why not just use tmux? Sometimes nested tmux sessions get annoying, when I use my tmux to go into a remote tmux  have to press control+b twice. 

I understand implementing tabs in alacritty won't happen, and that's reasonable - not every application on MacOS supports tabs. However, Command+\` is very standard and is on basically every MacOS app. Alacritty is my go-to terminal, and I'd like to switch between alacritty windows easily with my keyboard anyway 

Thank you,
Ryan

### System

OS: MacOS Monterey
Version: alacritty 0.10.0 (8a26dee)

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: Idk how to put this here, each time I try to take a screenshot it just prints more stuff cause of the mouse movements or keyboard shortcut used to make the screenshot

**Comment by joaomatos02** [comment]
MacOS here. I don't remember doing nothing special regarding this and have it working exactly how you described.

**Comment by kchibisov** [comment]
@RyannDaGreat make sure you're using `CreateNewWindow` and not `SpanwNewInstance`(this is a default for `Cmd + N`) to test this.
