### ISSUE TITLE
Support Auto Appearance setting on MacOS

### ISSUE THREAD

**Issue by lukehoersten** [alacritty/alacritty#6311]
When using Auto Appearance selection on MacOS, the system switches to and from dark/light mode based on the local time of day and sun set/rise times. Most MacOS applications support this. I would like a way to toggle my Alacritty theme as well. For example, when the system changes to dark mode, select `solarized-dark` etc.

### System

OS: macOS
Version: alacritty 0.10.1 (2844606)

**Comment by chrisduerr** [comment]
I have no interest in supporting this.

**Comment by kchibisov** [comment]
Upstream winit would support this so it'll be possible with the next winit release, I think.

**Comment by chrisduerr** [comment]
Even then it's not going to be worth it to have separate theme settings just for that. Seems like something that could be handled easily enough through our new config IPC interface.

**Comment by rogeruiz** [comment]
I manged to configure my terminal and a lot of other things by using some simple shell scripting, looking at plist settings, and running `sed` across my Alacritty config . I'll do a blog post about this sometime soon to help other macOS users. But if anyone is looking to do this on macOS, this script should be helpful to get off the ground.

=> https://git.sr.ht/~rogeruiz/.files/tree/main/item/bin/darwin/current_visual_mode

Thanks to @kchibisov for the helpful advice in #alacritty on Libera.
