### ISSUE TITLE
Feature: Write terminal output to a file

### ISSUE THREAD

**Issue by rwjack** [alacritty/alacritty#6312]
Just keep appending terminal output to a file, which can afterwards be rotated using logrotate.

I've seen other feature requests regarding this functionality, all being closed as duplicates for a single issue that was closed as well, and I'm amazed this still hasn't been implemented.

Is it possible that such a simple feature is that hard to implement? Not saying I would know how to accomplish such a feat, though I'm just curious.

**Comment by chrisduerr** [comment]
> I've seen other feature requests regarding this functionality, all being closed as duplicates for a single issue that was closed as well, and I'm amazed this still hasn't been implemented.

Then why did you open another?

**Comment by rwjack** [comment]
"Member of alacritty"? Quite unfortunate that this project is being developed by an angry little person.

If the entire dev team resembles yourself, no wonder you can't change a light bulb collectively.

**Comment by kchibisov** [comment]
The issue is still open https://github.com/alacritty/alacritty/issues/1615. 

>If the entire dev team resembles yourself, no wonder you can't change a light bulb collectively.

Yeah, we're a bunch of **enthusiasts** sitting here to deciding on how to change a light bulb.

In general if someone cares about a feature in open source or a bug that should be fixed they should send a patch.

**Comment by chrisduerr** [comment]
> they should send a patch

How could one person possibly do something like that? Obviously it requires an entire team just to change a lightbulb, poor @rwjack doesn't stand a chance.
