### ISSUE TITLE
Can't clear preedit text when using inline IME

### ISSUE THREAD

**Issue by YHNdnzj** [alacritty/alacritty#6313]
Alacritty added inline IME support (https://github.com/alacritty/alacritty/issues/1613) in https://github.com/alacritty/alacritty/pull/6265, which inputs fine unless trying to clear the preedit text. By holding the `Backspace` key, the IME popup disappears normally, but the first character remains on screen, and after disabling (`Ctrl + Space` on fcitx5) the IME, any input won't work at that moment. The only way to solve it is to type something else with the IME enabled, press `Space` to actually "enter" the word, and everything works again.

This doesn't occur on `wezterm`, nor alacritty without inline IME support (0.10.1).

### Steps to produce

1. Enable fcitx5, type one character in alacritty
2. Press `Backspace`
3. Disable fcitx5, try to type something else
4. Enable fcitx5 again, type normally and press `Space`
5. Disable fcitx5
6. Try to type again

### System

OS: Arch Linux
Version: _alacritty 0.11.0-dev (4ddb6085)_
WM: Sway (with patches from https://aur.archlinux.org/packages/sway-im-git for IME popup support)

### Config

https://github.com/YHNdnzj/dotfiles/tree/master/alacritty/.config/alacritty

**Comment by YHNdnzj** [comment]
@kchibisov https://fars.ee/IOW1
Follows exactly _Steps to produce_ in OP.

**Comment by kchibisov** [comment]
The most interesting thing is `WAYLAND_DEBUG=1` log from `alacritty`, but from the current log it seems like sway/fcitx is bugged.

**Comment by YHNdnzj** [comment]
> The most interesting thing is `WAYLAND_DEBUG=1` log from `alacritty`, but from the current log it seems like sway/fcitx is bugged. But given that you're using some custom sway branch it's likely the case since with sway master and normal IMEs(wlhangul/anthywl) they all work as expected.

I don't think sway master has support for native IME popup since https://github.com/swaywm/sway/pull/5890 has not been merged?

> I'd assume you can type or move after `Commit`?

Yes

**Comment by kchibisov** [comment]
>I don't think sway master has support for native IME popup since https://github.com/swaywm/sway/pull/5890 has not been merged?

But you can use inline inputs just fine with it. The popups was tested on GNOME and they also work there as expected with inline edit.

The issue is likely that when you disable IME, your ime doesn't actually result in `text_input::leave` event. So alacritty still thinks that there's IME going, but you don't have any. You can also see that there's no empty preedit's which you should get when you backspace the entire preedit away.

**Comment by YHNdnzj** [comment]
Here's the [log](https://pb.nichi.co/nurse-pair-snack) with `WAYLAND_DEBUG=1`

**Comment by kchibisov** [comment]
Are you reproducing your clear? Since from the logs you've never pressed backspace.

From what I can see it's not alarcitty issue. If you ever disable `ime` it's not being set as disabled and server tells us nothing about that. You can clearly type after commit, ect.

**Comment by wengxt** [comment]
@kchibisov you're wrong about text-input::leave. 

https://wayland.app/protocols/text-input-unstable-v3#zwp_text_input_v3:event:leave
Notification that this seat's text-input focus is no longer on a certain surface. The client should reset any preedit string previously set.

This is about focus, not a event can be produced by ime, usually it's only sent when app lost focus (switch to another app).

**Comment by kchibisov** [comment]
@wengxt I mean they say that they disable fcitx, so I'd expect that if you disable `fcitx` I'd at least get `leave` like I have with GNOME when swiching to `US` layout from `Hiragana` input sends a `leave`.

For your information, `Commit` implies the `empty` preedit, so alacritty `clears` the preedit on `commit`, so it can continue to receive the information again.

**Comment by kchibisov** [comment]
And that's the code that clears preedit on commit as I said to you in winit issue https://github.com/alacritty/alacritty/blob/89f4bdb770fad303a122172c60b5280e5061aeaf/alacritty/src/event.rs#L1240
