### ISSUE TITLE
Can't enable truecolor in alacritty

### ISSUE THREAD

**Issue by homogol** [alacritty/alacritty#6320]
Hi. In brief, I can't get true color to get working on the Alacritty.
### What I've tried so far?

1. Setting the TERM variable to alacritty in Alacritty's config file.
2. Setting the TERM variable to alacritty in my .zshrc and exporting it.

I wanted to make sure terminfo does support alacritty as value to TERM so I entered the following command:
```
dircolors --print-database | grep '^TERM'
```
Output:
```
TERM Eterm
TERM ansi
TERM *color*
TERM con[0-9]*x[0-9]*
TERM cons25
TERM console
TERM cygwin
TERM *direct*
TERM dtterm
TERM gnome
TERM hurd
TERM jfbterm
TERM konsole
TERM kterm
TERM linux
TERM linux-c
TERM mlterm
TERM putty
TERM rxvt*
TERM screen*
TERM st
TERM terminator
TERM tmux*
TERM vt100
TERM xterm*
```
As you can see alacritty isn't there so  I assume that terminfo doesn't recognize alacritty as value to the TERM variable.

### System

OS: Arch 5.19.7-arch1-1
Version: alacritty 0.10.1
WM: i3 version 4.20.1

**Comment by chrisduerr** [comment]
The `dircolors` command has nothing to do with terminfo or truecolor.

**Comment by homogol** [comment]
I know. I just wanted to make sure terminfo does accept alacritty as value to TERM because the output of `echo $TERM` is always `xterm-256color` but Maybe that's not the way.
The thing is I can see the colors in vim when I set the `termguicolors` in my vimrc in konsole but I can't see the colors in vim in alacritty.
I'll appreciate if you help me out because I'm trying to solve this problem for a few hours.

**Comment by homogol** [comment]
nvm it was tmux that prevented seeing colors.

**Comment by chrisduerr** [comment]
Terminfo doesn't "accept" anything. The terminfo database just stores the terminfo files. If you've got it installed and it doesn't work, you **will** notice. Applications are going to complain.
