### ISSUE TITLE
Ctrl+Del not working

### ISSUE THREAD

**Issue by oberien** [alacritty/alacritty#6321]
Ctrl+Del should delete the next work in front of the cursor. Instead, it prints `5~`. Alacritty sends `\x1b[3;5~` instead of `\x1b[3^` on `Ctrl+Del`. Adding the following line to `alacritty.yml` fixes it:
```yml
key_bindings:
  - { key: Delete, mods: Control, chars: "\x1b[3^" }
```

Could this behaviour be added as the default?

In rxvt-unicode everything works as expected without additional config. Running `showkeys -a` show that both terminals produce different results for Ctrl+Del.

Alacritty (first `Del`, then `Ctrl+Del`):
```
^[[3~ 	 27 0033 0x1b
 	 91 0133 0x5b
 	 51 0063 0x33
 	126 0176 0x7e
^[[3;5~ 	 27 0033 0x1b
 	 91 0133 0x5b
 	 51 0063 0x33
 	 59 0073 0x3b
 	 53 0065 0x35
 	126 0176 0x7e
```
urxvt (first `Del`, then `Ctrl+Del`):
```
^[[3~ 	 27 0033 0x1b
 	 91 0133 0x5b
 	 51 0063 0x33
 	126 0176 0x7e
^[[3^ 	 27 0033 0x1b
 	 91 0133 0x5b
 	 51 0063 0x33
 	 94 0136 0x5e
```

### System

OS: arch-linux: `Linux 5.19.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 05 Sep 2022 18:09:09 +0000 x86_64 GNU/Linux`
Version: arch package: `alacritty 0.10.1 ()`
Linux: Wayland with sway

**Comment by chrisduerr** [comment]
The `\x1b[3;5~` escape is correct for ctrl + del and will not be changed.
