### ISSUE TITLE
invisible cursor in zsh vi mode

### ISSUE THREAD

**Issue by dlants** [alacritty/alacritty#6323]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

I'm using zsh with vi-mode bindings. When I go from insert mode to normal mode, alacritty only shows the cursor at the very end of the line, but the cursor disappears if I move it left into the middle or the beginning of the line. See attached video:

https://user-images.githubusercontent.com/1186977/189549849-280feae2-3d8a-4a78-8ea2-89cf202c4cd1.mov

Using the same steps in iterm2, the cursor is always visible.

### System

OS: macOs 12.5
Version: `alacritty --version` output: `alacritty 0.10.1 (2844606)`

### Logs

[invisible_cursor.log](https://github.com/alacritty/alacritty/files/9543582/invisible_cursor.log)

**Comment by chrisduerr** [comment]
Can you reproduce this with stock Alacritty and Zsh config? I've never had any problems with this.

**Comment by dlants** [comment]
Ah, you are correct. I am uzing prezto and narrowed it down to this line:
```
zstyle ':prezto:load' pmodule \
...
   'syntax-highlighting' \
...
```

The docs for that module are [here](https://github.com/sorin-ionescu/prezto/tree/master/modules#syntax-highlighting)

And state that this integrates [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting) into prezto.

I tried to repro by installing the package directly, following the instructions [here](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md)

```
brew install zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
echo "source ${(q-)PWD}/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> ${ZDOTDIR:-$HOME}/.zshrc
```

When installed this way, highlighting worked! So it seems like it's something odd about the way zprezto sets it up.

**Comment by chrisduerr** [comment]
Yeah not an Alacritty issue then. Not the first broken zsh extension I've seen.

**Comment by kejadlen** [comment]
Manually setting the background color for the cursor is a workaround that I found:

```
zstyle ':prezto:module:syntax-highlighting' styles \
  'cursor' 'bg=white'
```

**Comment by StevenBR** [comment]
Had the same problem, found a solution in the prezto issues that could work a little more naturally for others [here](https://github.com/sorin-ionescu/prezto/issues/1497#issuecomment-342993892)

remove 'cursor' from the below config. (mine was in the .zpreztorc file):

```
zstyle ':prezto:module:syntax-highlighting' highlighters \
   'main' \
   'brackets' \
   'pattern' \
   'line' \
   'cursor' \
   'root'
```

**Comment by snwfdhmp** [comment]
@dlants @StevenBR You saved my life! 6 months into this really annoying issue! Thanks a lot

My solution is :

```
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor) # syntax highlighter options
```

Removed cursor and it was fixed right away
