### ISSUE TITLE
Visual-only freeze

### ISSUE THREAD

**Issue by VixieTSQ** [alacritty/alacritty#6332]
### System

OS: Linux
Version: `Version 0.12.0-dev (f2e74d99)`
Linux/BSD: X11, Xmonad with Picom

### Logs

Font/Terminal size: 
```
Cell size: 18 x 37
Width: 1124, Height: 1465
```
Keyboard and bindings: I don't wanna type this out, I don't yet have a web browser on my machine with alacritty. But it's responding to keyboard input fine by the looks of `--print-events`

### Description

Alacritty, when started from another terminal emulator (I'm using xterm for testing) will freeze on the prompt. I cannot see cursor blinking or keyboard input. I can though still use the terminal emulator, typing in commands as though everything is fine. I tested this by creating a file with `touch 42`, which I then checked to see if it is actually there. It is. So this bug is purely visual.

When I start Alacritty from dmenu, I never get to the prompt, only seeing the unblinking cursor on an otherwise empty line. Besides this, the functionality is still the same. I assume the visual freezing just begins later on when started from xterm for whatever reason.

When I run Alacritty with `LIBGL_ALWAYS_SOFTWARE=1` freezing does not occur. But this is obviously not preferable. Even the transparency doesn't work when I do this. I have perfectly modern Intel graphics so I should not have to do this.

Whether or not I have `xf86-video-intel` installed seems to have an effect. When I don't have it installed, Alacritty works just fine but for what I assume is an unrelated issue my system becomes incredibly laggy and has huge lag spikes often. So this is not an option for me. 

I've ran out of leads for this issue. I wouldn't even know where to start if I wanted to make it reproducible. If I had to guess, this is a problem with my setup but so far I've come up with nothing. I am hoping either this is actually a bug, or someone who has more knowledge than me can point me in the right direction. One theory I have is this could be a problem with my kernel config. My custom linux configuration may not have the correct driver needed for Alacritty's operation, possibly something to do with OpenGL, but I've done a lot of research and couldn't find anything like this. I've triple checked my graphics driver settings and then some.

I have tested both my distro's package for Alacritty and compiled the latest commit myself. No difference.

Any ideas?

**Comment by kchibisov** [comment]
`rsion` is coming somewhere from your system, we don't use that program and I don't even know what it is. Maybe the issue in the command you're trying to run in alacritty? Try running `alacritty -e sh` or `alacritty -e top`, could you interact with them?

**Comment by VixieTSQ** [comment]
> `rsion` is coming somewhere from your system, we don't use that program and I don't even know what it is. Maybe the issue in the command you're trying to run in alacritty? Try running `alacritty -e sh` or `alacritty -e top`, could you interact with them?

I'm a bit dumb, instead of running with the `--version` flag I instinctively ran `-v`. That explains why the version output wasn't so version-y... now that think about it more... ve**rsion**.. . must have been a really weird typo. This was all just me being in half-asleep troubleshooting mode, so we can disregard that! 

The commands you gave me didn't work, same behavior.

**Comment by kchibisov** [comment]
In general I'd suggest to use modesetting driver in the Xorg (if you really want to use Xorg). You could also try #6175.

**Comment by VixieTSQ** [comment]
> In general I'd suggest to use modesetting driver in the Xorg (if you really want to use Xorg). You could also try #6175.

The fork didn't do anything for me. I'll take a closer look at my lag problem and report back. I would love to use a wayland wm but I'm currently using xmonad :(. I do plan on switching to something like Smithay/smithay.

**Comment by VixieTSQ** [comment]
@kchibisov Fixed the lag problem by... running my GPU at max power all the time. It's not preferable but it works. I can now just not use `xf86-video-intel` which fixes the problem for me. I am unsure if this is still considered a problem, if you wish to actually support Xorg with `xf86-video-intel`. If you don't wish to support this configuration then we can close the issue.

**Comment by chrisduerr** [comment]
This seems **very much** like a driver issue. Especially on X11 there's likely not going to be a lot of effort put into fixing these device-specific driver issues unless upstream does it by themselves.
