### ISSUE TITLE
Builtin box characters are not drawn as bold

### ISSUE THREAD

**Issue by tranzystorek-io** [alacritty/alacritty#6335]
When using zellij on alacritty, by default I get thin and poorly aliased pane frames (drawn with the box characters):

![obraz](https://user-images.githubusercontent.com/5671049/190172237-eb61708a-3116-4a01-babb-96487e03dce7.png)

For reference, konsole draws them nice and bold:

![obraz](https://user-images.githubusercontent.com/5671049/190172538-e20818bf-f9f8-4b1c-bba9-42f7cb3b8d2f.png)

According to the discussion in https://github.com/zellij-org/zellij/issues/1626, zellij correctly requests bold characters, but alacritty fails to draw them so. Confirmed by the fact that it can be worked around by setting `font.builtin_box_drawing: false`

### System

OS: Void Linux
Version: 0.10.1
Linux/BSD: X11, Leftwm (also verified on KDE)

**Comment by kchibisov** [comment]
The box drawing characters don't have bold variants in general and I'm not sure I've seen them in a wild.

The way to draw bold characters is to request bold variants, not style.

See the heavy variants here: https://unicode-table.com/en/blocks/box-drawing/

For me with konsole they are overly thick and you can always disable builtin font if you don't like it.

**Comment by tranzystorek-io** [comment]
I'm guessing the rounded corners would stay the same in your solution since they don't seem to have a heavy variant?

**Comment by kchibisov** [comment]
Yeah, those don't have them.

**Comment by chrisduerr** [comment]
Also just to make sure tested Kitty and behaves the same way as we do. I think it makes sense.
