### ISSUE TITLE
No application icon on Openbox

### ISSUE THREAD

**Issue by kitmonisit** [alacritty/alacritty#6336]
Related 
#1591: Missing Icon in KDE (breaks Freedesktop specification)
#2166: Icon not showing properly on Openbox

### System

OS: Linux
Version: alacritty 0.12.0-dev (bf3e8822)
Linux/BSD: X11 Openbox

### Logs

Crashes: None
Font/Terminal size: N/A
Keyboard and bindings: N/A

**Comment by kitmonisit** [comment]
Font size in the tint2 taskbar is set to 64 x 64.

Wrong icon shows up in the tint2 panel when using the 64 x 64 [alacritty-term.png](https://github.com/kitmonisit/alacritty/blob/47b250be8f54c7b4d0589873b8953f4c347389cd/extra/logo/compat/alacritty-term.png)
![image](https://user-images.githubusercontent.com/1175380/190329642-882a1a87-f5e4-4bbe-a5d6-5c45ba4b907a.png)

Alt-tab display also shows the wrong icon
![image](https://user-images.githubusercontent.com/1175380/190330047-71776121-a676-46ea-b7a2-b178f167aea8.png)

**Comment by chrisduerr** [comment]
Most likely an issue with either tint2 or you failed to install Alacritty properly. The icon works just fine.

**Comment by kitmonisit** [comment]
I followed the instructions in `INSTALL.md`, but it still does not show up. Probably an issue with tint2.

If I change it to the 512 x 512 [alacritty-term+scanlines.png](https://github.com/kitmonisit/alacritty/blob/47b250be8f54c7b4d0589873b8953f4c347389cd/extra/logo/compat/alacritty-term+scanlines.png) on [alacritty/src/display/window.rs](https://github.com/kitmonisit/alacritty/blob/47b250be8f54c7b4d0589873b8953f4c347389cd/alacritty/src/display/window.rs), I get the icon, even if I do not do the extra steps in `INSTALL.md`

![image](https://user-images.githubusercontent.com/1175380/190331533-9190b55f-d730-40d7-8d64-4ba9e768a043.png)

**Comment by chrisduerr** [comment]
I mean tint2 should probably follow the xdg icon spec for looking up icons to begin with. So the fact that changing `window.rs` does anything at all already kinda indicates that it's doing some weird shit.

**Comment by kitmonisit** [comment]
Yes, tint2 is an application panel. I'm not sure which one does the Alt-Tab display, openbox or tint2.

**Comment by kitmonisit** [comment]
Ok, so I re-rendered `extra/logo/compat/alacritty-term.svg` as a 512 x 512 PNG, and now the icon shows up. Weird nitpick (probably by tint2) about icon sizes.
