### ISSUE TITLE
Why are multiple tabs not supported?

### ISSUE THREAD

**Issue by stax76** [alacritty/alacritty#6340]
Popular terminal emulators like Gnome Terminal and Windows Terminal support multiple tabs, it appears to be useful and intuitive.

I know there are special tools like tmux and special window managers, but I have no knowledge about such tools. Is alacrity typically used in combination with such tools? If so, which tools are popular by alacrity users, and how do they work? I'm on Ubuntu 22 which uses Wayland instead of X11.

Gnome Terminal seem to be OK, but it misses some basic features like copying the current input line to the clipboard via keyboard shortcut, so it can later be pasted in GUI apps like Firefox or VS Code.

For which kind of user is alacrity made? Even though I'm highly experienced in powershell, I'm not a terminal person, but prefer GUI apps like Nautilus and the Albert launcher, VS Code etc. Still, I need to use the terminal all the time, for development and apps like mpv player etc.

Are there other good terminal emulators I could try?

**Comment by stax76** [comment]
May I ask why this was closed so fast without a comment? Many large projects allow asking questions and have an issue template for that. I asked for a tip or two, provided detail and context.

**Comment by kchibisov** [comment]
It's wise to search for similar issues before opening a duplicate one. #3129

**Comment by gerrywastaken** [comment]
Here are a few insights I gathered from analyzing this GitHub issue conversation about adding tab support to Alacritty:

- There is a clear divide between those wanting tabs as a feature and the developers not wanting to implement it. The developers have repeatedly stated there are no plans to add tab support.

- Many users argue tabs are an expected and standard feature in terminal emulators. However, the developers view tabs as outside the scope and goals of Alacritty.

- The developers suggest using alternative solutions like tmux or **tabbed windows in tiling window managers**. But some users find these inadequate or too complex.

- There is some debate around whether tabs fit with Alacritty's minimalist, "suckless" philosophy or would add too much complexity. The developers argue scrollback is different than tabs in this regard.

- The discussion spans 5+ years. Some suggest forking Alacritty as a way forward for those wanting tabs. But no sustained fork has gained traction so far.

- Reactions show more positive sentiment overall towards comments arguing for tabs. But the developers remain firm in their stance.

- There are criticisms of developer attitudes from some users, while others defend their right to build what they want. There's tension between user feature requests and developer goals.

- Overall, it's a long-running debate reflecting different perspectives on the scope and philosophy of the project. The developers have held firm despite user pressures.

**Comment by linrongbin16** [comment]
Hi, when google "alacritty tabs", this is the 1st item popup and tell us it is not supported.

But actually at the time of writing this, the alacritty tabs works great on macOS M1, installed with `brew install alacritty`. Just press `cmd+t` will create a new tab page.

In case people searched this issue, I just want to clarify this.

**Comment by anti-decoy** [comment]
You can absolutely use tmux to implement tabs within Alacritty. I never need to open multiple Alacritty windows—instead, I open a single Alacritty window, launch tmux inside it, and then create multiple tabs within tmux. The only issue is that when SSH-ing to remote hosts that also use tmux, there can be keyboard shortcut conflicts. However, that's not a problem—I've changed my local tmux prefix key to Ctrl+t, which avoids the conflict. This perfectly solves the multi-tab issue in Alacritty while maintaining its high performance.

**Comment by BlairStewart** [comment]
> This perfectly solves the multi-tab issue in Alacritty while maintaining its high performance.

It does not. Because you know.. you have to use tmux.

**Comment by atheerium** [comment]
well. seems like you either have to use tmux (or more recently Zellij) . or move to Wezterm / Kitty.

**Comment by BlairStewart** [comment]
> well. seems like you either have to use tmux (or more recently Zellij) . or move to Wezterm / Kitty.

It does seem that way.

**Comment by Heinrich-XIAO** [comment]
`Cmd+t` seems to work for me, but `Ctrl+Tab` (standard MacOS tab change shortcut) does not work. I also tried `Cmd+Tab`, but that doesn't work either.

**Comment by ddmytrenko** [comment]
@stax76 Each software has it's task. Alacritty is a terminal emulator. Tabs, containers, etc is a task for terminal multiplexer. https://zellij.dev/ will cover all your needs. You're welcome.

**Comment by rr-it** [comment]
If you need GUI window tabs instead of terminal multiplexer use `tabbed`.
See https://github.com/alacritty/alacritty/issues/3129#issuecomment-5581864567 for full configuration.
