### ISSUE TITLE
Cursor latency after switching windows

### ISSUE THREAD

**Issue by rsmith31415** [alacritty/alacritty#6345]
### System

OS: Linux
Version: alacritty 0.10.1 ()
Linux/X11/Ubuntu 22.04, dwm 6.3

### Logs

Crashes: No crashes
Font/Terminal size: Width: 1920, Height: 1056
Keyboard and bindings: ??

Running the default alacritty configuration, I'm able to reproduce a very unusual delay when switching from another window to alacritty.

https://user-images.githubusercontent.com/599274/190883730-c7b35617-7b39-4bda-a474-76c7033ed6b4.mp4

You can see in the screencast above that the cursor looks as if alacritty is not getting the focus quick enough, and after 1 second or less, the cursor gets its usual shape. If I start  typing immediately after switching windows, the characters appear on the terminal only after the cursor is ready with its "Block" shape. However, this delay is not consistent and only happens when switching between workspaces (tags in dwm). This doesn't happen if I simply switch between windows within the same workspace.

For the record, I have tried gnome-terminal and qterminal and the delay is very minimal and consistent. This is gnome-terminal:

https://user-images.githubusercontent.com/599274/190884011-4a79b965-cf12-41a0-9a79-f891b2a8161a.mp4

What could be causing this issue?

**Comment by chrisduerr** [comment]
Can you reproduce this on a WM other than DWM? Otherwise I'd assume it's probably a driver issue.

**Comment by rsmith31415** [comment]
I'm only able to switch to a session running Lubuntu which is not a similar environment (implementation details of tags in dwm vs workspaces in Lubuntu are not equivalent). For the record, alacritty was working well on dwm using the same drivers for the last 6 months. It was only after I tested the latest version of tmux and installed `libevent-dev` and `yacc` that I noticed this cursor delay. I don't know if the issue happened because of this or I simply realized this cursor latency was happening at that very moment. For unrelated reasons, I went back to my previous tmux version, removed the installed libraries, but the same issue persists in Alacritty.

Having said that, I found that starting alacritty with `LIBGL_ALWAYS_SOFTWARE=1` "fixes" this issue. What does that mean?

**Comment by chrisduerr** [comment]
> Having said that, I found that starting alacritty with `LIBGL_ALWAYS_SOFTWARE=1` "fixes" this issue. What does that mean?

That means you're running into a driver issue.

**Comment by rsmith31415** [comment]
> That means you're running into a driver issue.

You seem more concerned about closing issues than finding solutions. I don't mind if it is a driver issue and I need to change something to fix it, but your initial assumption disregards the rest of the evidence I described before.
