### ISSUE TITLE
Hard coding alacrity -e "docker exec -it container_name /bin/bash" prevents from opening MacOS.app

### ISSUE THREAD

**Issue by buahaha** [alacritty/alacritty#6348]
### System

OS: macOS
Version: alacritty 0.12.0-dev (8dcc7f52)

### Logs

Crashes: nothing. It's GUI icon.
app does not start

___

I have [hard coded](https://github.com/phoenix-journey/nutek/blob/9002f0223b4fa263570b8e77ac25276e5d31bcbf/alacritty/src/cli.rs#L218) `Docker` command from [here](https://github.com/phoenix-journey/nutek/blob/9002f0223b4fa263570b8e77ac25276e5d31bcbf/nutek_runner/src/lib.rs#L108).

The issue I have is that I can't start Alacritty terminal from `/Applications/Alacritty.app` by clicking on an icon. When app is opened clicking focuses the window, but does not spin up another window. I tried many things. using AppleScript in Alacritty.app/Contents/MacOS/alacritty.sh to open, shell script and terminal.

The only thing that does the thing is `open -n /Applications/Alacritty.app`, but it completely defeats the purpose by opening **terminal app** from _another_ **terminal app**.

Please advise.

**Comment by kchibisov** [comment]
For spin up another window you'd need either `CreateNewWindow` or `SpawnNewInstance` methods.
