### ISSUE TITLE
What is OpenGL needed for?

### ISSUE THREAD

**Issue by balanceglove2** [alacritty/alacritty#6353]
Since alacritty seems to defer to the native font renderers for glyphs, what about it is OpenGL-based? Isn't glyph rendering 99% of what a terminal emulator has to do?

**Comment by hholst80** [comment]
This will give you some architectural understanding of why OpenGL.

https://www.youtube.com/watch?v=hxM8QmyZXtg

**Comment by balanceglove2** [comment]
So, basically, the native font renderer _should_ handle all the font rendering but is too terrible, and thus it’s way better to store the rasterized glyphs in a GPU texture atlas cache instead and "instantiate" the glyphs onto the screen yourself?

If so, this would make Pathfinder an even more needed piece of software for the industry than I previously thought. To actually get sane and performant glyph rendering on all platforms.

**Comment by kchibisov** [comment]
>So, basically, the native font renderer should handle all the font rendering but is too terrible, and thus it’s way better to store the rasterized glyphs in a GPU 

We use freetype/corefont/ect to rasterize glyphs, and then upload them to the glyph cache on the GPU, so the font rendering is native and drawing already rasterized glyphs is fast.

Non using freetype would result in non-native looking fonts.

**Comment by chrisduerr** [comment]
No matter which rasterization technique you use it would never be a smart approach to rasterize from vector format during rendering. That's just a terrible idea.
