### ISSUE TITLE
Window-Title doesn't change back to "Alacritty" after exiting vim for the second time

### ISSUE THREAD

**Issue by alexandersokolow** [alacritty/alacritty#6357]
Hi. When I open Vim, the window-title changes & when I close it, it changes back to "Alacritty", as expected.

However, when I open Vim, then use "Ctrl+Z" to put it into the background, then put it into the foreground again & then close it, it doesn't change back to Alacritty.

This new title will even remain when I open another vim instance (which will temporarily change it) & then normally close it again.

I have created a hacky fix for this (in my bashrc):
`
function fg() {
  command fg "$@"
  echo -ne "\e]2;Alacritty\007"
}
`

This is obviously not ideal. Any idea what is going wrong there?

### System

OS: Linux
Version: 0.10.1
Linux/BSD: X11, Xmonad

**Comment by chrisduerr** [comment]
You're relying on vim to update the title, so if it doesn't do it, it won't work. Alacritty has nothing to do with it really, it just waits for the escapes and interprets them.

Adding something to your prompt to update the title is the only reliable way to resolve this afaik.
