### ISSUE TITLE
Slow Startup Time in Sway

### ISSUE THREAD

**Issue by hughesjs** [alacritty/alacritty#6359]
### System

OS: Linux
Version: 0.10.1
Linux/BSD: Wayland Sway

If I have no other instances of Alacritty open, the startup time is very slow:

```
[james@zephyrus ~]$  for i in $(seq 0 10); do time alacritty -e echo; done 2>&1 | grep real
real	0m1.602s
real	0m1.644s
real	0m1.641s
real	0m1.651s
real	0m1.663s
real	0m1.644s
real	0m1.630s
real	0m1.655s
real	0m1.658s
real	0m1.645s
real	0m1.665s
```

However, if I already have an instance open, it's fine:

```
for i in $(seq 0 10); do time alacritty -e echo; done 2>&1 | grep real
real	0m0.070s
real	0m0.073s
real	0m0.070s
real	0m0.074s
real	0m0.070s
real	0m0.066s
real	0m0.070s
real	0m0.076s
real	0m0.065s
real	0m0.065s
real	0m0.066s
```

Other apps don't seem to exhibit this delay.

**Comment by foopsss** [comment]
Hello. I'm experiencing this issue as well on my Fedora Silverblue 36 install, with Alacritty and Sway as overlayed packages and a AMD GPU (I'm not sure of the exact model but `neofetch` says "_AMD ATI Radeon R2/R3/R4/R5 Graphics_"). Starting Alacritty feels long the first time but is rather fine with an opened instance. Measures:

- With no previous instances.
```
[lucas@fedora] [~] [02:25:12] $ for i in $(seq 0 10); do time alacritty -e echo; done 2>&1 | grep real
real	0m0,446s
real	0m0,348s
real	0m0,331s
real	0m0,317s
real	0m0,303s
real	0m0,319s
real	0m0,294s
real	0m0,326s
real	0m0,307s
real	0m0,427s
real	0m0,338s
```

- With a previous Alacritty instace.
```
[lucas@fedora] [~] [02:25:19] $ for i in $(seq 0 10); do time alacritty -e echo; done 2>&1 | grep real
real	0m0,402s
real	0m0,400s
real	0m0,384s
real	0m0,383s
real	0m0,343s
real	0m0,407s
real	0m0,299s
real	0m0,338s
real	0m0,336s
real	0m0,326s
real	0m0,338s
```

**Comment by kchibisov** [comment]
Yeah, that looks like a driver issue to be honest given that our instances don't know about each other. You may look at strace timings to get a guess where the time is spent.

**Comment by chrisduerr** [comment]
@foopsss Those look pretty much identical to me?

Note that a startup time of 300-400ms is a little slow, but not something I'd consider a bug for opening a completely new instance.

However a startup time of almost 2s as reported by the author of this issue is for sure a bug somewhere (again, most likely in the driver).

**Comment by foopsss** [comment]
My apologies, I forgot to mention that I included those measurements just in case, as the numbers are indeed not that different.

In any case, I just wanted to point out that something similar is happening to me on Sway.

**Comment by kchibisov** [comment]
@foopsss is the example from https://github.com/rust-windowing/glutin (run it via `cargo run --example window`) is slow to start for you? Be aware that you shouldn't have any alacritty(or other hw accel apps) during testing around.

**Comment by karlek** [comment]
I had the same issue. For some reason I had installed the `nvidia-utils` package. Even though I have an Intel GPU.

Output from `strace` shows that `nvidia-modprobe` would take almost 0.4 seconds.

```
$ strace -T alacritty -e false
[..]
stat("/usr/bin/nvidia-modprobe", {st_mode=S_IFREG|S_ISUID|0755, st_size=39232, ...}) = 0 <0.000022>
geteuid()                               = 1000 <0.000015>
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f831797e450) = 5921 <0.001003>
wait4(5921, [{WIFEXITED(s) && WEXITSTATUS(s) == 1}], 0, NULL) = 5921 <0.399605>
[..]
```

Removing the `nvidia-utils` package solved the problem for me.

**Comment by russelltg** [comment]
I have a system with hybrid graphics, so obviously I do not want to do that. I use `envycontrol` to manage my GPU state, so putting 

```
#!/bin/sh

if envycontrol -q | grep -q integrated ; then
	echo "__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json"
fi
```

in `/usr/lib/systemd/user-environment-generators` fixes this problem for me

**Comment by kchibisov** [comment]
Closing since it's libglvnd setup thing, new windows could be open via `alacritty msg create-window` command or `CreateWindow` hotkey, so it'll skip the `libglvnd` part entirely.

**Comment by techvishnu** [comment]
> Removing the `nvidia-utils` package solved the problem for me.

Bro, This was a life saver, I use dual boot and now i yeeted out nvidia completely from my machine and it magically worked, Turns out my gpu was the culprint behind the flickering, slow startup etc.. Now im going on easy mode, Thank you
