### ISSUE TITLE
Can't use C-w on v0.11.0 RC2

### ISSUE THREAD

**Issue by nshen** [alacritty/alacritty#6360]
I have bind `C-w` in vim, I always use `C-w` to close a buffer in vim. and it works fine on v0.10.1.
since I upgrade to v0.11.0 RC2, when I type `C-w` the Alacritty quit. 
How should I rollback to previous behavior and use `C-w` in vim?

### System

OS: macOS
Version: [Alacritty Version 0.11.0 Release Candidate 2](https://github.com/alacritty/alacritty/releases/tag/v0.11.0-rc2)

**Comment by chrisduerr** [comment]
I'd assume the same issue is present in RC1?

**Comment by nshen** [comment]
maybe, I came from 10.1

`C-f` also can't send to vim.

**Comment by chrisduerr** [comment]
Could you test?

**Comment by nshen** [comment]
tested, same issue is present in RC1

C-f will trigger alacrity search, not I defined in vim.

![Kapture 2022-09-27 at 18 42 35](https://user-images.githubusercontent.com/181506/192505309-c2f21c95-6b98-4151-b46d-199d94021706.gif)

**Comment by chrisduerr** [comment]
You're just pressing Ctrl + F, correct? Not Ctrl + Shift + F?

**Comment by nshen** [comment]
Yes just Ctrl + f

**Comment by chrisduerr** [comment]
Can you add the following binding, does that fix it for you?

```
  - { key: F, mods: Control, action: ReceiveChar    }
```

**Comment by nshen** [comment]
![Kapture 2022-09-28 at 11 20 10](https://user-images.githubusercontent.com/181506/192680055-c5a5dd74-6632-4c88-8935-388dfc5fe5c0.gif)

**Comment by chrisduerr** [comment]
Then something's clearly not right. Can you share the output you get from `--print-events` that you get when pressing Ctrl+F?

**Comment by nshen** [comment]
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/181506/192854612-ea6db5eb-52bf-4e19-b6b0-fd0caf41ffa6.png">

**Comment by chrisduerr** [comment]
Are you sure you're pressing CONTROL and not Command?

**Comment by kchibisov** [comment]
Yeah, from the logs it seems like you're pressing `Command + F`, do you have those keys swapped somehow by some utility?

**Comment by nshen** [comment]
oh, you are right , perhaps because of my windows rules.

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/181506/192875807-0c9c75e0-e474-4b5d-be2f-7933a1a1d9c4.png">

but still something changed from v10.1, when I changed back to v10.1 `Ctrl + F` worked as I expect, Karabiner-elements don't affect 10.1.

**Comment by kchibisov** [comment]
I'd expect carabiner affect it. You explicitly map ctrl + f to command + f, so it seems that it works as expected now.
