### ISSUE TITLE
FeatureRequest: Statusbar

### ISSUE THREAD

**Issue by tonobo** [alacritty/alacritty#6361]
Howdy guys,

would be cool to have some native statusbar handling in terminal directly. I don't want to use the prompt for it as i like to keep the prompt fast on-return and short as possible. I'm looking for something like tmux or screen statusbar, but with the actual context from the active terminal. tmux and similar isn't really an option to compare to as you loose some of nice alacritty features (e.g. vi buffer search. native scrollback and so on). I would like to embed the CI/CD status lazily, based on the actual working directory.

Thanks, Tim

**Comment by chrisduerr** [comment]
Out of scope, Alacritty is not a multiplexer.
