### ISSUE TITLE
Support .yaml extension

### ISSUE THREAD

**Issue by Spixmaster** [alacritty/alacritty#6362]
### System

OS: Linux
Version: `alacritty 0.10.1 ()`
Linux/BSD: X11, i3

The extension `.yaml` should be possible for the configuration file instead of only accepting `.yml`. YAML even [suggests it](https://yaml.org/faq.html).

**Comment by chrisduerr** [comment]
You can pass whatever file name you want with `alacritty --config-file`. We're not going to support multiple formats because that will just cause unnecessary fragmentation.
