### ISSUE TITLE
Fedora cant launch alacritty

### ISSUE THREAD

**Issue by fislysandi** [alacritty/alacritty#6363]
so i tried fedora and found out for some reason it cant launch on fedora,
alacritty works just fine on arch with the picom --experemental-backend.

maybe im missing some dependecies?

### System

OS: Linux
Version: `0.10.1
Linux: X11 picom --experemental-backend
Distro:Fedora

### Logs

Crashes: ![vmware_rZ8mUvPjBt](https://user-images.githubusercontent.com/45166203/192278587-7c777fdc-ff9d-4594-98e5-d88d6d39985b.png)

Font/Terminal size: i didnt change anything
Keyboard and bindings: i didnt change anything

**Comment by hholst80** [comment]
X11 picom --experemental-backend is surely not the default in Fedora though? Because on the vanilla Fedora alacritty works just fine on my machine.

**Comment by fislysandi** [comment]
i just installed i3 fedora spin and remade it into bspwm.

**Comment by fislysandi** [comment]
because i3 doesnt include shit ton of things.

**Comment by chrisduerr** [comment]
Picom is a compositor, what's your WM?

**Comment by Man2Dev** [comment]
works just fine on fedora kde
