### ISSUE TITLE
vim Syntax Highliting

### ISSUE THREAD

**Issue by ffarps** [alacritty/alacritty#6365]
### System
OS: Linux **Pop!_OS 20.04**
Version: **alacritty 0.12.0-dev (c5ae05e8)**
Linux/BSD: GNOME

Syntax of swift.org, not showing in Alacritty
### Using the build in **Gnome Terminal** this works
:sintax on does not work

I just placed swift.vim in this path: "**.vim/pack/bundle/start/swift/syntax/swift.vim**"
#### In this figure above is alacritty and bellow gnome terminal:
![Untitled](https://user-images.githubusercontent.com/73230223/192347303-aeb8925e-54af-4482-a0de-db58e87eca7a.png)

**Comment by chrisduerr** [comment]
This is a vim configuration issue. Unrelated to Alacritty (mostly).

**Comment by ffarps** [comment]
> This is a vim configuration issue. Unrelated to Alacritty (mostly).

no, as I said alacritty is not using he vim configs, and I want to know why

**Comment by ffarps** [comment]
EDIT, NOW ITS SOLVED

TERM=xterm-256color
