### ISSUE TITLE
How to disable echo of the command name

### ISSUE THREAD

**Issue by Fryuni** [alacritty/alacritty#6368]
Alacritty prints the first word of every command before executing, this is super annoying and breaks the output that I'm trying to copy quite frequently.
![image](https://user-images.githubusercontent.com/11063910/193181218-fde22143-dc49-48a5-a05c-9a59120cb8aa.png)

Other terminal emulators opening the exact same shell, in the same mode, and the same configuration, don't show this behavior, so I pinpointed the problem to be on alacritty.
I tried to search the configuration file for something related to echoing commands or commands in general and could not find anything. Is there a way to disable this? I really want to migrate to Alacritty, but this is a total show-stopper

### System

OS: Linux
Version: `alacritty 0.10.1 ()`
Linux/BSD:
```
OS-> NixOS 22.11.20220927.7e52b35 (Raccoon) x86_64 
Kernel-> 5.15.70 
Shell-> zsh 5.9 
DE-> Xfce 4.16 
WM-> Xfwm4 
WM Theme-> Kde 
Terminal-> alacritty 
Locale-> en_US.utf8 
```

**Comment by kchibisov** [comment]
Fix your shell, alacritty has nothing to do with it, it just renders text. You might have some random `echo` in some of your commands.
