### ISSUE TITLE
Restart fcitx5 cause Alacritty close.

### ISSUE THREAD

**Issue by lolicon0930** [alacritty/alacritty#6370]
> Please describe the bug that you have found:

Restart fcitx5 cause Alacritty close.

> and what you would expect to happen instead:

Alacritty should not be closed.
### System

OS: Debian GNU/Linux bookworm/sid x86_64
Version: alacritty 0.12.0-dev (e9ee8dc)
Display server: X11
Compositor: picom
WM: dwm

 cargo build with only X11 support
### Logs
[Alacritty-607924.log](https://github.com/alacritty/alacritty/files/9691451/Alacritty-607924.log)

**Comment by lolicon0930** [comment]
The black two are xterm.

https://user-images.githubusercontent.com/14966910/193454270-afad066a-7774-4ead-96c6-5bf7b51fd169.mp4

- RUST_BACKTRACE=1 alacritty
[backtrace_1.log](https://github.com/alacritty/alacritty/files/9692500/backtrace_1.log)

- RUST_BACKTRACE=full alacritty
[backtrace_full.log](https://github.com/alacritty/alacritty/files/9692501/backtrace_full.log)

**Comment by chrisduerr** [comment]
> So actually I should report to rust-windowing/winit?

Yeah, would be appreciated, thanks.

**Comment by kchibisov** [comment]
I think that it's not a new bug? The code that crashing is due to the error from the XIM, I personally can't repro that by killing and reenabling XIM, so it's something about your setup? No matter what I do it doesn't crash for me when I force kill or reload fcitx. The crash that you've triggered is due to error during closing the input method...

**Comment by kchibisov** [comment]
Does the crash happens with `v0.10.1` at least? I'd assume so, since the failure that we can't open any input method...

**Comment by lolicon0930** [comment]
> Does the crash happens with `v0.10.1` at least? I'd assume so, since the failure that we can't open any input method...

I tested v0.10.1 and that stable version doesn't have this problem.

**Comment by kchibisov** [comment]
Could you test 7d708d53f7ecb4c64db10ae44e7f4fca47c29a85 as well?

**Comment by lolicon0930** [comment]
alacritty 0.11.0-dev (7d708d53)
This problem does not exist.

**Comment by lolicon0930** [comment]
This problem has appeared since 5bbba69.

**Comment by kchibisov** [comment]
@lolicon0930 Could you test this

```diff
diff --git a/Cargo.toml b/Cargo.toml
index aad21557..8964e156 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -10,3 +10,6 @@ members = [
 lto = true
 debug = 1
 incremental = false
+
+[patch.crates-io]
+winit = { git = "https://github.com/kchibisov/winit", branch = "ime-test" }

```

It should also dump styles during reload so please post them as well and try to mark somehow the ones you've got on reload.

**Comment by lolicon0930** [comment]
`$ alacritty &>log`
```
==========================
404
402
408
204
202
208
==========================
==========================
404
402
408
204
202
208
==========================
==========================
810
408
==========================
thread 'main' panicked at 'Failed to open fallback input method: ContextCreationFailed(Null)', /home/lolicon/.cargo/git/checkouts/winit-4b1f5e8d108a5ef0/ccddaf0/src/platform_impl/linux/x11/ime/callbacks.rs:186:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by kchibisov** [comment]
I've updated the branch, I think it should work now. Run `cargo update -p winit` and rebuild(It shouldn't print anything anymore as an indicator).

**Comment by lolicon0930** [comment]
No problem now.

**Comment by kchibisov** [comment]
Given that fixed hasn't landed yet.
