### ISSUE TITLE
Issue with softwares that use ncurses

### ISSUE THREAD

**Issue by Pixfri** [alacritty/alacritty#6371]
When I open a software that uses the ncurses-term like ranger or xmake, I hava this error: /snap/alacritty/46/lib/x86_64-linux-gnu/libtinfo.so.6: version `NCURSES6_TINFO_6.2.20211010' not found (required by /lib/x86_64-linux-gnu/libncurses.so.6)
I've already installer the ncurses-term library but the it always shows me this error.

### System

OS: Ubuntu 
Version: 0.8.0
Linux

### Logs

Crashes: /snap/alacritty/46/lib/x86_64-linux-gnu/libtinfo.so.6: version `NCURSES6_TINFO_6.2.20211010' not found (required by /lib/x86_64-linux-gnu/libncurses.so.6)
Font/Terminal size: Font:12 * 26, Terminal: 2560*1320

**Comment by chrisduerr** [comment]
This clearly seems to be an issue in an application running inside of Alacritty, so it's not an Alacritty issue.

**Comment by Pixfri** [comment]
> This clearly seems to be an issue in an application running inside of Alacritty, so it's not an Alacritty issue.

These softwares don’t work in alacritty but work in other terminals so I thought it was an issue with alacritty.

**Comment by kchibisov** [comment]
That's because you're using snap, don't use snap.

**Comment by Pixfri** [comment]
> That's because you're using snap, don't use snap.

And how can I install it without using snap? When I try to install it with apt, it says it can't install it because there is no version of it that can be installed.
