### ISSUE TITLE
mkdir feature

### ISSUE THREAD

**Issue by Anishali2** [alacritty/alacritty#6376]
Is there any way to create a folder in alacritty because I am facing the issue of create directories in my folder but I can't find any possible solution .

Like wise in terminal we can create using "mkdir" but in alacritty I didn't find any

**Comment by chrisduerr** [comment]
There is no reason why Alacritty would ever create a directory.

**Comment by Anishali2** [comment]
Try to make things simple I am just asking to make a folder I found the solution 
use : and type mkdir then press enter 
just asking because I have to exit alacritty just for making folder

**Comment by kchibisov** [comment]
alacritty has nothing to do with folders or anything it just renders text. The shell you're running (I'd assume you're on windows), like powershell, whatever is responsible to call to utilities to create dirs and such.
