### ISSUE TITLE
Can't paste in command mode in `nvim` or `tmux`

### ISSUE THREAD

**Issue by LintaoAmons** [alacritty/alacritty#6382]
### System

OS: macOS
Version: alacritty 0.10.1 (2844606)

### Can't paste in command mode in `nvim` or `tmux`

I use alacritty as terminal emulator then I can use shortcuts `cmd+key`.

But it is strange that I can paste content in `normal` and `insert` mode, but I can't paste things in command mode.

- The gif is showing that I can paste in nvim normal mode then insert mode, but can't in command mode.
    - ![Reddit_question](https://user-images.githubusercontent.com/95092244/194696591-96f882f1-8527-44f9-9465-9d7ebd669f98.gif)
- This gif is showing that tmux command mode just crush when I press `command+v`
    - ![allacritty-tmux-paste](https://user-images.githubusercontent.com/95092244/194696695-ad9272c3-42be-4e52-b1eb-9982f738714e.gif)

**Comment by phi-gamma** [comment]
Possibly related question of mine: https://vi.stackexchange.com/q/38508 (this is in Linux + neovim).

**Comment by LintaoAmons** [comment]
> Possibly related question of mine: https://vi.stackexchange.com/q/38508 (this is in Linux + neovim).

I meet this problem not only in neovim but also tmux. So guess not the neovim specific issue.

**Comment by chrisduerr** [comment]
Alacritty is completely unaware of which mode you're running in. So if you're having trouble pasting in a specific mode, I recommend looking into Neovim instead.

**Comment by LintaoAmons** [comment]
I compared the behavior between iterm2 and Alacritty, within same tmux session. 

Iterm2 can paste, but not alacritty.

![alacritty](https://user-images.githubusercontent.com/95092244/194995566-003ac61f-02e5-4125-8807-fdc118dba8f6.gif)



> Alacritty is completely unaware of which mode you're running in. So if you're having trouble pasting in a specific mode, I recommend looking into Neovim instead.
