### ISSUE TITLE
Failed to set environment variable at startup

### ISSUE THREAD

**Issue by DeeGeeMan** [alacritty/alacritty#6387]
If I set a new environment variable in the `env` section with `$HOME/.config` or `~/.config` in the `~/.config/alacritty.yml` file, it just create a new folder instead of expanding the variable defined.

```
env:
  XDG_CONFIG_HOME: "$HOME/.config"
```

### System

OS: macOS
Version: `alacritty 0.10.1 (2844606)`

**Comment by kchibisov** [comment]
We don't do variable expansion in strings nor `~` expansion. So you have to specify the actual path.
