### ISSUE TITLE
Alacritty release action for building the Windows MSI installer is failing

### ISSUE THREAD

**Issue by rux616** [alacritty/alacritty#6392]
The GitHub action for creating the Windows installer for Alacritty releases has failed, resulting in no MSI installer for v0.11.0.

Log: https://github.com/alacritty/alacritty/actions/runs/3238626920/jobs/5307052159

> D:\a\alacritty\alacritty\alacritty\windows\wix\alacritty.wxs(6) : error LGHT0103 : The system cannot find the file '.\extra\windows\alacritty.ico'.
> C:\agent\_work\66\s\src\ext\UIExtension\wixlib\WelcomeEulaDlg.wxs(42) : error LGHT0103 : The system cannot find the file '.\extra\windows\wix\license.rtf'.

**Comment by chrisduerr** [comment]
Manually uploaded the artifact, fixed it for the next release in #6394. Let me know if the manually created artifact doesn't work for you.

**Comment by rux616** [comment]
👍

I just installed it successfully on my personal system (Windows 10 Pro 21H2) and my work system (Windows 11 Pro 22H2).
