### ISSUE TITLE
Hyperlinks hints not working in tmux session

### ISSUE THREAD

**Issue by Tony-Sol** [alacritty/alacritty#6393]
### System

OS: macOS
Version: `alacritty 0.11.0 (8dbaa0b)`

### Current config

https://raw.githubusercontent.com/Tony-Sol/.config/master/alacritty/alacritty.yml

### Record

https://user-images.githubusercontent.com/33671815/195696416-77d92519-6d5a-4a62-aaaf-d4d225df6631.mov

**Comment by Tony-Sol** [comment]
After some research found, that this is tmux problem, not alacritty

**Comment by Tony-Sol** [comment]
For anyone else will google this problem:

That's actually strange behavior between several terms:
e.g. in "Alacritty" and "Terminal.app", tmux links got highlighted only if shift held but,
in integrated Intellij IDEA terminal (which is `TERMINAL_EMULATOR=JetBrains-JediTerm`)
and integrated vscode terminal (which has no TERMINAL_EMULATOR or any other noticeable envs to detect its origin) -
no mod-keys required, links always got highlighted on hover.

**Comment by kchibisov** [comment]
You need to manually enable hyperlinks in tmux. Like `set-option -ga terminal-features ",alacritty:hyperlinks"`
