### ISSUE TITLE
Font not found (WSL 2 Debian)

### ISSUE THREAD

**Issue by Martin15135215** [alacritty/alacritty#6401]
### System

OS: Windows 10
WSL 2 Debian
![image](https://user-images.githubusercontent.com/110968398/195791878-b29b18a5-656e-4b62-b1fd-cbdb61f7091a.png)

Version: https://github.com/alacritty/alacritty/releases/download/v0.10.0/Alacritty-v0.10.0-portable.exe

![image](https://user-images.githubusercontent.com/110968398/195791934-f8c65c1a-a1a1-4d6a-8cde-fa4dab675de9.png)

### Logs
![image](https://user-images.githubusercontent.com/110968398/195791379-2d8e2e9c-ab1e-4d7c-a91e-1b7c0642bd3b.png)

I installed the Nerd Font in Windows
![image](https://user-images.githubusercontent.com/110968398/195791447-78f239b4-18af-4c21-bdb9-c4370f7007c4.png)

and i installed the Nerd Font in WSL 2 Debian
![image](https://user-images.githubusercontent.com/110968398/195791750-41c999da-b9d2-4f4a-bc20-bc894a8e98f7.png)
![image](https://user-images.githubusercontent.com/110968398/195792650-52c5a42e-3f0a-46a8-87bd-09012e7066ef.png)

however alacritty do not found anything

**Comment by chrisduerr** [comment]
Is your Alacritty actually running as a graphical application in WSL? I'd assume you're running it on Windows, not on Linux.

**Comment by Martin15135215** [comment]
yes i uses it on windows -> Version: [v0.10.0 Alacritty-v0.10.0-portable.exe (download)](https://github.com/alacritty/alacritty/releases/download/v0.10.0/Alacritty-v0.10.0-portable.exe)

**Comment by sk8higher** [comment]
are you sure that your font name in config is correct? it is `FireCode` in your config, and FiraCode in windows.

**Comment by Martin15135215** [comment]
that's in my config:
![image](https://user-images.githubusercontent.com/110968398/195926946-4fc91052-8821-4ee3-a195-8e252efc8d90.png)

and that image is from windows setting gui:
![image](https://user-images.githubusercontent.com/110968398/195927019-2a9320a6-8fe2-4f1a-99f9-7328318aedf8.png)

**Comment by MikeOnTea** [comment]
In other words, your config is wrong!?

**Comment by Martin15135215** [comment]
oh my bad, sorry
