### ISSUE TITLE
Terminal keeps flickering (WSL 2 Debian Fish Shell)

### ISSUE THREAD

**Issue by Martin15135215** [alacritty/alacritty#6403]
System
OS: Windows 10
WSL 2 Debian
![](https://user-images.githubusercontent.com/110968398/195791878-b29b18a5-656e-4b62-b1fd-cbdb61f7091a.png)

Version: [v0.10.0 Alacritty-v0.10.0-portable.exe (download)](https://github.com/alacritty/alacritty/releases/download/v0.10.0/Alacritty-v0.10.0-portable.exe)

Fish Shell

with nala installing packages in debian:

![alacritty_flickering](https://user-images.githubusercontent.com/110968398/195844558-965bdc1b-1359-4003-b5c2-a9cc3242a51a.gif)

i don't know why it keeps flickering. Is there some settings in alacritty.yml?

**Comment by chrisduerr** [comment]
Application synchronization issue.

**Comment by Martin15135215** [comment]
> Application synchronization issue.

Is there a way to fix it?

**Comment by chrisduerr** [comment]
The application can fix it, yes.
