### ISSUE TITLE
[Question] Keybinding for toggling terminal opacity

### ISSUE THREAD

**Issue by TornaxO7** [alacritty/alacritty#6404]
Hello! May I ask how I can set the opacity of alacritty with a keybinding? I've set alacritty to `0.75` in my config but sometimes I'd like to disable its opacity for a short moment. I couldn't find any `Opacity` action in the [default config file](https://github.com/alacritty/alacritty/blob/master/alacritty.yml).

**Comment by chrisduerr** [comment]
You can bind the command `alacritty msg config window.opacity=0.5` to any key you want.
