### ISSUE TITLE
Unable to remove ttys000 login prompt

### ISSUE THREAD

**Issue by mikiya09** [alacritty/alacritty#6408]
unable to remove ttys000 Last Login prompt on Alacritty on macos, even though I had this command touch ~/.hushlogin
after execute that command, ttys000 is removed from original Mac terminal, but still on for the first time open alacritty  
this problem happen only when I update the alacritty to the latest version, it doesn't happen in the past version
<img width="420" alt="Screen Shot 2022-10-15 at 11 22 33 PM" src="https://user-images.githubusercontent.com/94091460/196016498-1e576fee-572c-4fe2-8c72-5650b04e044c.png">

**Comment by chrisduerr** [comment]
This message is unrelated with Alacritty. It's your shell printing the message.

**Comment by Fujiwara-Chika** [comment]
> This message is unrelated with Alacritty. It's your shell printing the message.

but it doesn't happen in the past alacritty version
