### ISSUE TITLE
[Feature request] Support "on press" and "on release" key bindings

### ISSUE THREAD

**Issue by mroavi** [alacritty/alacritty#6409]
I would like to send a byte sequence at the moment a key is pressed. At the moment, it is only possible to send it when the key is released.

**Comment by chrisduerr** [comment]
Why?

**Comment by mroavi** [comment]
My use case is the following. The default shortcut prefix for tmux is `Ctrl+b`. Since I use it all the time, I would rather have a single key as prefix, for example, `Alt`. I can configure Alacritty to send the byte sequence for `Ctrl+b` whenever `Alt` is pressed. However, it is quite annoying that I have to release `Alt` before I can type the next letter (e.g., `l` to focus on the last visited pane). If I could send the bytes on the "press", I could type both `Alt+l` simultaneously.
I think there are a few other nice use cases but, in general, you would give us better flexibility to program more reactive bindings.

**Comment by chrisduerr** [comment]
That's not a usecase I'm interested in supporting.
