### ISSUE TITLE
Hyperlink Underline?

### ISSUE THREAD

**Issue by zach-is-my-name** [alacritty/alacritty#6416]
Where is the setting to underline all hyperlinks automatically as Gnome Terminal (among others) does? Right now I the only way I can see a link is if I hover over it.  Please tell me this setting mirroring other terminals that implement OSC 8 exists in Alacritty...

I've already searched the man pages and browsed to issues but couldn't find anything obvious.  Thanks 

Linux
0.12.0-dev (269b6e3d)
X11/Ubuntu WM

**Comment by zach-is-my-name** [comment]
Could be related to https://github.com/alacritty/alacritty/issues/6414#issue-1411758126, because I am not receiving underdotting either

**Comment by chrisduerr** [comment]
There is no setting.

**Comment by zach-is-my-name** [comment]
> There is no setting.

Can there be a setting?.

**Comment by chrisduerr** [comment]
Nope, we intentionally only highlight URLs on hover.

**Comment by zach-is-my-name** [comment]
Great reason for me to learn Rust I suppose (Give me a break)

**Comment by zach-is-my-name** [comment]
Can you point me any discussion offering context? If that's the case, how am I to know a link even exists?
