### ISSUE TITLE
mac os - keybindings that work system wide dont work on alacritty

### ISSUE THREAD

**Issue by ccbiozhaw** [alacritty/alacritty#6423]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: macos Monterey version 12.6
Version: alacritty 0.11.0 (8dbaa0b)

I just switched to alacritty and I noticed that a lot of key combinations do not work. for example @ (command L) and others that I set up with karabiner. These work everywhere, including iterm and whatever, however in alacritty it does not

**Comment by ccbiozhaw** [comment]
edit: i noticed that things to work, but I have to click twice the first time. cmd + L + L gives me an @, its exactly the same with all other combos. everywhere else its just cmd + L, strangely?

**Comment by ccbiozhaw** [comment]
i found the solutions:

https://github.com/alacritty/alacritty/issues/3715

alt_send_esc: false

jeez, why is that on by default

**Comment by kchibisov** [comment]
That's `on` because applications use alt keybindings, without it you won't be able to use alt bindings in them at all.

**Comment by ccbiozhaw** [comment]
what do you mean by that? with it on i cant use any character that relies on alt

**Comment by kchibisov** [comment]
I mean that terminal applications understand that something is alt due to leading escape. For weird macOS layouts this option indeed is causing an issue. For other operating systems it's a mandatory, since you don't have a broken alt on a system level.
