### ISSUE TITLE
Alacritty quits on launch

### ISSUE THREAD

**Issue by mhmdanas** [alacritty/alacritty#6426]
Alacritty immediately quits on launch, before even showing the window. Neither reinstalling Alacritty nor restarting the machine seems to help. I deleted my Alacritty config file and that didn't fix anything, so my config has nothing to do with this issue.

### System

OS: macOS 12.6
Version: alacritty 0.11.0 (8dbaa0b)

### Logs

Output of `alacritty -vv` (gives back an exit code of 0):
```
Created log file at "/var/folders/bg/vf7hd0vs49n39lcyk_s0smb00000gn/T/Alacritty-4385.log"
[0.000054389s] [INFO ] [alacritty] Welcome to Alacritty
[0.007115821s] [INFO ] [alacritty] Version 0.11.0 (8dbaa0b)
[0.042091590s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/Users/mhmdanas/.config/alacritty/alacritty.yml"
[0.042702146s] [DEBUG] [alacritty] Using environment locale: C/UTF-8/C/C/C/C
[0.074165062s] [DEBUG] [alacritty] Loading "Menlo" font
[0.199210390s] [DEBUG] [alacritty] Estimated scaling factor: 2
[0.199337580s] [DEBUG] [alacritty] Estimated window size: None
[0.199360840s] [DEBUG] [alacritty] Estimated cell size: 13 x 26
[0.265049290s] [INFO ] [alacritty] Running on Intel(R) Iris(TM) Plus Graphics 640
[0.265144366s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.271354065s] [INFO ] [alacritty] Display scale factor: 2
[0.271427590s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.297002248s] [INFO ] [alacritty] Cell size: 13 x 26
[0.297084338s] [INFO ] [alacritty] Padding: 0 x 0
[0.297107136s] [INFO ] [alacritty] Width: 1600, Height: 1200
[0.297327901s] [INFO ] [alacritty] PTY dimensions: 46 x 123
[0.302970512s] [INFO ] [alacritty] Initialisation complete
[0.340792693s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[0.341176627s] [INFO ] [alacritty] Padding: 0 x 0
[0.341226707s] [INFO ] [alacritty] Width: 1600, Height: 1200
[0.399888952s] [INFO ] [alacritty] Goodbye
Deleted log file at "/var/folders/bg/vf7hd0vs49n39lcyk_s0smb00000gn/T/Alacritty-4385.log"
```

**Comment by kchibisov** [comment]
Your shell is exiting right way, try using empty config.

**Comment by mhmdanas** [comment]
@kchibisov still quits on launch. Also, Alacritty.app crashes immediately too.

**Comment by kchibisov** [comment]
If it crashes provide a stack trace, from what I see there's no crash or anything. I also see that your locale is broken. `Using environment locale: C/UTF-8/C/C/C/C`.

Try running alacritty from other application and pass for example `alacritty -e sh` to it.

**Comment by mhmdanas** [comment]
Alrigt, thanks for explaining, I had misunderstood you. `alacritty -e sh` works, and even `alacritty -e fish` and `alacritty -e /usr/local/bin/fish` work (my `SHELL` is `/usr/local/bin/fish`), but `alacritty` doesn't. Still, Alacritty used to work just fine for me yesterday with the same version, so I'm not sure what is happening here. Any idea how I could fix this?

> I also see that your locale is broken. Using environment locale: C/UTF-8/C/C/C/C.

I ran this on the shell from which I'm launching Alacritty:

```console
> set | grep UTF
LC_CTYPE=UTF-8
```

Is that a broken locale?

**Comment by mhmdanas** [comment]
`alacritty -e zsh` works.

**Comment by kchibisov** [comment]
So I'd assume that `alacritty --config-file /dev/null` is also not working?

**Comment by mhmdanas** [comment]
Indeed, that doesn't work too.

**Comment by kchibisov** [comment]
Hm, maybe the shell you've `chsh` isn't working and you use shell from somewhere else. But it's hard to say why it stopped working that way though. For now you can specify the shell program explicitly in you configuration.

I have a feeling that it could be something with fish and the way we try to run it as a login shell. In general you shouldn't use fish as a login shell unless you know what you're doing(It's not a POSIX compliant shell).

**Comment by kchibisov** [comment]
@mhmdanas if you symlink your `fish` shell into `/usr/bin/fish` and `chsh` this path will it work? I have a feeling that we fail to resolve your shell properly which seems strange.

**Comment by kchibisov** [comment]
You could try to run `/usr/bin/login -flp $USER /bin/sh -c fish`.

**Comment by mhmdanas** [comment]
> Hm, maybe the shell you've `chsh` isn't working and you use shell from somewhere else.

Running `chsh -s /usr/local/bin/fish` spews back `chsh: no changes made`, so it's the same shell.

> For now you can specify the shell program explicitly in you configuration.

Alright, I'll do that. Thank you for the advice.

> In general you shouldn't use fish as a login shell unless you know what you're doing(It's not a POSIX compliant shell).

Point taken, but I'll note that I just tried running `chsh -s /bin/zsh`, closing and reopening the terminal, and then doing this:

```console
> echo $SHELL
/bin/zsh
> alacritty -vv --config-file /dev/null
Created log file at "/var/folders/bg/vf7hd0vs49n39lcyk_s0smb00000gn/T/Alacritty-3960.log"
[0.000054758s] [INFO ] [alacritty] Welcome to Alacritty
[0.005967816s] [INFO ] [alacritty] Version 0.11.0 (8dbaa0b)
[0.027548786s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/dev/null"
[0.029509204s] [DEBUG] [alacritty] Using environment locale: C/UTF-8/C/C/C/C
[0.063607904s] [DEBUG] [alacritty] Loading "Menlo" font
[0.215537805s] [DEBUG] [alacritty] Estimated scaling factor: 2
[0.215658214s] [DEBUG] [alacritty] Estimated window size: None
[0.215681669s] [DEBUG] [alacritty] Estimated cell size: 13 x 26
[0.297792292s] [INFO ] [alacritty] Running on Intel(R) Iris(TM) Plus Graphics 640
[0.297878934s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.304674594s] [INFO ] [alacritty] Display scale factor: 2
[0.304761274s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.330878282s] [INFO ] [alacritty] Cell size: 13 x 26
[0.330961341s] [INFO ] [alacritty] Padding: 0 x 0
[0.330986276s] [INFO ] [alacritty] Width: 1600, Height: 1200
[0.331273482s] [INFO ] [alacritty] PTY dimensions: 46 x 123
[0.339494923s] [INFO ] [alacritty] Initialisation complete
[0.379824626s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[0.380225450s] [INFO ] [alacritty] Padding: 0 x 0
[0.380303512s] [INFO ] [alacritty] Width: 1600, Height: 1200
[0.462560299s] [INFO ] [alacritty] Goodbye
Deleted log file at "/var/folders/bg/vf7hd0vs49n39lcyk_s0smb00000gn/T/Alacritty-3960.log"
```

So we can conclude this isn't a Fish-specific issue.

> if you symlink your `fish` shell into `/usr/bin/fish` and `chsh` this path will it work? I have a feeling that we fail to resolve your shell properly which seems strange.

macOS doesn't allow me to do that:

```console
> sudo ln -s /usr/local/bin/fish /usr/bin/fish
ln: /usr/bin/fish: Operation not permitted
```

> You could try to run `/usr/bin/login -flp $USER /bin/sh -c fish`.

That works.

> To be more precise `/usr/bin/login -flp $USER /bin/sh -c "exec -a -fish /usr/local/bin/fish"`

Here is what happens when I try running that:

```console
> /usr/bin/login -flp $USER /bin/sh -c "exec -a -fish /usr/local/bin/fish" 
Last login: Thu Oct 20 16:21:57 on ttys000
sh: 1: exec: -a: not found
```

**Comment by kchibisov** [comment]
Yeah, your issue is that your `exec` doesn't have the `-a` parameter? I've just tested on `macOS` and it seems to work fine for me, maybe you have something from brew?

**Comment by mhmdanas** [comment]
I'm not sure if you missed what I said, but it's because I've configured `/bin/sh` points to `/bin/dash` on my machine, and Dash's `exec` doesn't seem to support `-a`.

**Comment by kchibisov** [comment]
Ah, so that's what is causing it... So if you switch your `sh` to `bash` it should work.

@chrisnc It seems like your patch is causing issue with `dash`, since there's no `-a` for exec. Do you have any suggestions.

**Comment by mhmdanas** [comment]
> Ah, so that's what is causing it... So if you switch your sh to bash it should work.

Indeed.

> @chrisnc It seems like your patch is causing issue with dash, since there's no -a for exec. Do you have any suggestions?

If there's no equivalent for `-a` in POSIX sh, then `/bin/sh` should be replaced with `/bin/zsh` in the command (it could be replaced with `/bin/bash` too, but macOS's Bash is ancient, and I reckon it might be even removed in the future).

**Comment by kchibisov** [comment]
I'm not entirely sure why `-a` is actually needed here? What it'll do that it'll path `-fish` to `fish`, but that's about it.

**Comment by mhmdanas** [comment]
@kchibisov yes, it'll pass `-fish` as the 0th argument (`$0`) to Fish, which will cause the process to appear as `-fish` in say, `ps` or `top`. Without `-a -fish`, the process will be shown as `/usr/bin/local/fish` instead (i.e. the full path of the Fish command). I'm not sure why, but `zsh` and other commands also follow the convention of appending `-` to the "process name" (is that what it's called?). Don't quote me on that though, I'm no expert.

**Comment by chrisduerr** [comment]
Adding the `-` prefix makes it a login shell, so it is necessary.

**Comment by kchibisov** [comment]
I guess the only option is to use `/bin/zsh` otherwise we won't be able to invoke as a shell as a login one, since there's a convention that if shell should be run as a login one it should be named with `-`,so running `-zsh` will run it as a login shell which we try to achieve.

I guess the only option we can use is to check for `/bin/zsh`  or `/bin/bash` (Try first and then fallback to other)?

I see that `iterm` has a separate binary just to run a shell with a `-` prefix...

**Comment by chrisduerr** [comment]
I don't remember how long macOS has had `zsh` around for, but iirc they had it installed even before it became their default shell?

That said, the "safe" bet would probably be to just use bash and run with it. It's an ancient version, yes, but it's certainly good enough. And there's no way they'll remove that.

**Comment by kchibisov** [comment]
I mean doing a fallback is trivial here, since you check that file exists, you don't try to exec anything.

**Comment by mhmdanas** [comment]
> I don't remember how long macOS has had zsh around for, but iirc they had it installed even before it became their default shell?

What is the minimum macOS version supported by Alacritty? If the earliest version has `/bin/zsh`, I personally think using it is the best bet.

**Comment by chrisduerr** [comment]
> I mean doing a fallback is trivial here, since you check that file exists, you don't try to exec anything.

But why would we add code and spend milliseconds falling back between different shell versions, when both are guaranteed to be around anyway?

> I want to ask, what is the minimum macOS version supported by Alacritty? If the earliest version has /bin/zsh, I personally think using it is the way to go here.

Pretty sure all macOS versions that aren't EOL have zsh.

**Comment by bboydflo** [comment]
I experience a similar issue on MacOS Monterey v. 12.6. I can't open Alacritty at all. I can open it from the default terminal app only, tried to open it from iTerm2 as well, but without success.

The error I get when I attempt to open it from iTerm2 is: “Alacritty.app” can’t be opened because Apple cannot check it for malicious software.

**Comment by mhmdanas** [comment]
@bboydflo that's an unrelated issue. To fix it, try to open Alacritty.app. After it shows you the error, open System Preferences, then press on "Security & Privacy." There should be a button to allow you to launch Alacritty anyway.

> Pretty sure all macOS versions that aren't EOL have zsh.

@chrisduerr then is there any real reason to use `/bin/bash`?

**Comment by kchibisov** [comment]
>But why would we add code and spend milliseconds falling back between different shell versions, when one is guaranteed to be around anyway?

I don't get it, you check only if the first fails, so you're not wasting anything. You just make handling more future proof. But I don't think that the bash will go away.

**Comment by chrisnc** [comment]
While working on the login shell fix for macOS at some point I was using `/bin/zsh` to do the `exec -a`. I looked at the macOS release history and all versions of macOS going back to 10.0 have it, so I think it would be fine to just use `/bin/zsh` here, rather than assuming the capabilities of `/bin/sh`. I can make a patch to this effect if there are no objections.
