### ISSUE TITLE
Cannot close shell by Ctrl-d and also 'prefix C-n' and 'prefix C-p' does not work on tmux

### ISSUE THREAD

**Issue by ys64** [alacritty/alacritty#6428]
I used to be able to exit shell or close alacritty by hitting `Ctrl-d`. However, after updating to 0.11.0, it does not seem to work any more. So, I type 'exit'  and hit Enter to do so.

Also, I had a setting for `prefix C-n` and `prefix C-p` on tmux as follows:
```
bind C-n next-window
bind C-p previous-window
```

Those keybinds used to work as well, but not any more. However, `prefix C-c` works:
```
bind C-c new-window
```

I tried with an empty config, but it did not work either.

Is anyone else having the same issue?

### System

OS: macOS Monterey (12.6)
Version: 0.11.0 (8dbaa0b)

**Comment by chrisduerr** [comment]
Could you bisect the exact issue that broke this?

**Comment by ys64** [comment]
Thank you for your reply!

Wow! I tried bisect, and this is the first time that I built a project written in Rust! Thanks to your wonderful document ([INSTALL.md](https://github.com/alacritty/alacritty/blob/master/INSTALL.md)), I was able to nail down the commit that caused the issue.

This is the first bad commit: e09ff0b4

It does not seem to be harmful commit. However, I forgot to mention that I am using [Karabiner-Elements](https://github.com/pqrs-org/Karabiner-Elements), and after quitting Karabiner-Elements, the issue is not happening any more. I can see **alacritty** in Karabiner-Elements ([os-inl.h](https://github.com/pqrs-org/Karabiner-Elements/blob/aabb7cbc898fd5fecf2336460a77f229ec37c76a/src/vendor/cget/cget/pkg/gabime__spdlog/install/include/spdlog/details/os-inl.h#L430)), but I do not know why changing the name causes the issue.

I reported this issue because the issue did not happen on default Terminal.app on macOS, so I thought it only happens on Alacrity.

This might be caused by Karabiner-Elements, but I use it daily. So, I will use Alacritty on 694a52bc until there is an update on Alacritty or Karabiner-Elements.

Thank you!

**Comment by ys64** [comment]
Just for future reference, I had a `bundle_identifiers` setting in `~/.config/karabiner/karabiner.json` to exclude some keybindings that `io.alacritty` uses.

After changing `io.alacritty` with `org.alacritty`, I was able to make `Ctrl-d` and `prefix Ctrl-n` and `prefix Ctrl-p` on tmux on the latest Alacritty. Thank you!
