### ISSUE TITLE
copy / paste doesn't work on nano

### ISSUE THREAD

**Issue by ghost** [alacritty/alacritty#6429]
Not sure why this is the case but, on other terminals I could `Ctrl+Shift+C/V` to copy & paste to & from the primary clipboard. I did have `key_bindings` in my config, but still doesn't work.
```
- { key: V,  mods: Control|Shift,  action: Paste }
- { key: C,  mods: Control|Shift,  action: Copy }
```
Also have **`save_to_clipboard: true`**

It works fine outside editor, ie. Console. But not on nano.

**Comment by chrisduerr** [comment]
Which platform, which Alacritty version?

**Comment by pc00per** [comment]
0.11.0 (Arch)

**Comment by chrisduerr** [comment]
Are you using qwerty?

**Comment by pc00per** [comment]
Yes. Basically the keybindings work in console mode. But not in nano editor. I wanted to highlight & ctrl+shift+c/v to interact with my primary keyboard. Is it possible to do that ?

**Comment by chrisduerr** [comment]
Can you try with `--config-file /dev/null` please?

**Comment by pc00per** [comment]
Same behavior without config file too.
And nop, I neither use mouse mode, nor a mouse. I can't even interact with primary clipboard inside nano, even though I have `xclip` dependency.
All I can do, are to use nano's instructions below, which are very obnoxious btw.

**Comment by chrisduerr** [comment]
> I can't even interact with primary clipboard inside nano, even though I have xclip dependency.

Alacritty's clipboard has **nothing** to do with any dependencies like `xclip` and is completely independent from `nano`. Have you tried holding shift to make a selection and then pressing ctrl+shift+c/v?

**Comment by pc00per** [comment]
> Have you tried holding shift to make a selection and then pressing ctrl+shift+c/v?

Yes I usually hold shift to make selection, then try keybinds, but fail to work (within nano, or even outside nano).

**Comment by chrisduerr** [comment]
I'll be honest I can almost guarantee that this is user error if it works outside of `nano` but not within.

Just to narrow things down a bit more maybe: Can you copy out of nano into a different window/terminal. Or copy from a different terminal/window and paste into nano? Like are both actions "broken" for you or just one of them?

**Comment by pc00per** [comment]
> Just to narrow things down a bit more maybe: Can you copy out of nano into a different window/terminal. Or copy from a different terminal/window and paste into nano?

Both doesn't work, is the main issue btw. Both actions are broken.

**Comment by chrisduerr** [comment]
This might sound a little silly but could you provide a video showing this off? Ideally with a program open that shows which keys you're pressing.

**Comment by kchibisov** [comment]
Could include `--print-events` log, since it should show `Copy` and `Paste` events.

**Comment by pc00per** [comment]
https://pastebin.com/2Gb3LvEx

**Comment by aivarsV** [comment]
I have noticed the same issue in vim recently. 
![image](https://user-images.githubusercontent.com/19207168/211262501-d984ac2e-5791-4355-85c8-5d94483b5e64.png)

You can see in screenshot three "paragraphs" - me pasting same text three times. The middle one looks exacly as I copied it from the same terminal window, but it was pasted back with `wl-paste` shell command - not a keybinding. 
Top and bottom "paragraphs` were pasted with`Ctrl-Shift-V` key combo. I did enable paste mode in vim beforehand.

Log file from this session is quite long and available <http://sprunge.us/8K9Bfz>.

Like mentioned before, there are no issues, when pasting in command line (bash). My guess is that it might have something to do with pasted text highlighting. Maybe there was a change in that code recently?

**Comment by kchibisov** [comment]
Why do you think that it's alacritty issue and not vim issue? From what I know vim broke pasting in recent versions.

**Comment by aivarsV** [comment]
> Why do you think that it's alacritty issue and not vim issue? From what I know vim broke pasting in recent versions.

My bad, thank's for pointing that out.
