### ISSUE TITLE
Option to Center on Launch

### ISSUE THREAD

**Issue by vunhatchuong123** [alacritty/alacritty#6431]
### System

OS: Windows
Version: 0.11.0

It seems that whenever I open Alacritty, it will appears  at a random location, this is not a problem for Tiling WM but for Windows,,,. 

Sure I can startup maximized or mess around with `position` but it would be great to have a Center on Launch option.

**Comment by chrisduerr** [comment]
@kchibisov Do you know how placement in winit is performed on Windows by default? I'd assume it isn't random?

**Comment by kchibisov** [comment]
It's random(not set), but if you want to center you compute center yourself.

**Comment by vunhatchuong123** [comment]
Why is this closed as complete when I stated that I know you can work around it, this is a functionality request.

**Comment by chrisduerr** [comment]
Because we're not interested in adding a feature to center the window for you? You're free to patch this in yourself of course.

IIRC there is an issue still open tough about remembering the window position. I'm not sure that will ever get implemented but at least it hasn't been outright denied yet I think.

**Comment by vunhatchuong123** [comment]
A proper and mature way is to close and explain the reasons. Close without explanation is not gonna be helpful for me or anyone that have the same question.

**Comment by shivambegin** [comment]
I was searching for the same thing and got here but no answers here as well lol

**Comment by Leymora** [comment]
> Because we're not interested in adding a feature to center the window for you? You're free to patch this in yourself of course.
> 
> IIRC there is an issue still open tough about remembering the window position. I'm not sure that will ever get implemented but at least it hasn't been outright denied yet I think.

Yikes. What a terrible response.

**Comment by SalahEddineGhamri** [comment]
> Because we're not interested in adding a feature to center the window for you? You're free to patch this in yourself of course.
> 
> IIRC there is an issue still open tough about remembering the window position. I'm not sure that will ever get implemented but at least it hasn't been outright denied yet I think.

mmmm thinking about switching to another terminal due to this response.
