### ISSUE TITLE
doesn't render powerline symbols with ANSI terminals styles correctly

### ISSUE THREAD

**Issue by hronro** [alacritty/alacritty#6436]
### System

OS: macOS
Version: `alacritty 0.11.0`

## Step to reproduece

Run `echo -e '\x1b[47m \x1b[49m\x1b[47m \x1b[49m'`

Alacritty:

<img width="912" alt="CleanShot 2022-10-22 at 19 12 57@2x" src="https://user-images.githubusercontent.com/15059605/197336021-ff2c60ea-ae68-474e-9d28-e9092005ba51.png">

Kitty:

<img width="1203" alt="CleanShot 2022-10-22 at 19 13 01@2x" src="https://user-images.githubusercontent.com/15059605/197336025-ee3a66db-1fd5-4b8a-acf5-5cac4bf90852.png">

**Comment by chrisduerr** [comment]
It is rendered correctly, it just uses the font you specified instead of a custom font. There's some work in #5795 to include more symbols in our built-in font but powerline symbols are already pretty severe of a hack.

**Comment by hronro** [comment]
@chrisduerr I use the same font in Alacritty and Kitty but they look different. I also tried #5795 several days ago but it doesn't help.

**Comment by hronro** [comment]
Let me add some more details here.

It seems the characters`` and `` are rendered in different widths between Alacritty and Kitty:

<img width="371" alt="CleanShot 2022-10-23 at 12 29 15@2x" src="https://user-images.githubusercontent.com/15059605/197373864-94a57025-8d92-412c-b8e7-071404d2968b.png">
(Alacritty on the top and Kitty on the bottom)

**Comment by chrisduerr** [comment]
That's because Kitty doesn't actually use your font to draw these characters. But Alacritty does.

**Comment by hronro** [comment]
@chrisduerr 

It's pretty cool to know Kitty doesn't actually use my font to draw these characters.

I tried build Alacritty with PR #5795 , but it seems nothing improved. Does that means #5794 does not really solve the problem, or just because the PR is not complete yet?

**Comment by kchibisov** [comment]
That's because only default powerline characters are used there, not the ones you're using. By default powerline only had arrows.

**Comment by hronro** [comment]
@chrisduerr @kchibisov 

One more question here. It seems Alacritty renders`` at double-width, which follows Unicode standards. However, when trying to render `12345`, the number `1` is obscured by the character ``. Is this an expected behavior? Rendering other double-width characters like the Chinese characters won't have this kind of issue.

![](https://user-images.githubusercontent.com/15059605/197373864-94a57025-8d92-412c-b8e7-071404d2968b.png)

**Comment by kchibisov** [comment]
Probably the glyph in the font is just too big, since alacritty thinks that the size is 1, given that your text is drawn like that in the output of echo?
