### ISSUE TITLE
It would be great if we can add helix mode too.

### ISSUE THREAD

**Issue by grv07** [alacritty/alacritty#6439]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux/BSD/macOS/Windows
Version: `alacritty --version` output
Linux/BSD: X11/Wayland, DE or Compositor and WM

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by kchibisov** [comment]
You can rebind all the Vi mode bindings to your liking. But helix and vi has near identical bindings wrt movement, besides helix has more composite('gl' for end of line) ones, which we don't support.
