### ISSUE TITLE
MacOS: each window adds a new Dock icon (no support for many windows under one app instance)

### ISSUE THREAD

**Issue by inodentry** [alacritty/alacritty#6450]
OS: macOS
Version: 0.11.0 (8dbaa0b)

If I want to open multiple Alacritty windows, for multiple terminal sessions, each one adds an additional icon to the Dock.

I often need to keep many terminal windows open, and it is very annoying for it to fill the Dock like that. This usability bug is the main reason why I don't currently use Alacritty on macOS (I love it on Linux).

Alacritty needs to support having arbitrarily many windows, all shown as a single icon in the Dock, like every other Mac App.

I don't understand the technical reasons for this. Maybe someone more knowledgeable about macOS app development can chime in to explain what it would take to implement this?

---

Simple reproduction screenshot:

<img width="1512" alt="Screenshot 2022-10-26 at 14 57 57" src="https://user-images.githubusercontent.com/40234599/198020614-66491a5b-7066-40a1-b68c-1ce5de4ad019.png">

**Comment by kchibisov** [comment]
Use `CreateNewWindow` action.

**Comment by inodentry** [comment]
I don't understand? Even if I just run the app normally (not by running `alacritty` like in the screenshot) and I press Command-N to create a new window, it still creates a new dock icon.

Please help me. As a user, how do I invoke whatever action you are talking about?

**Comment by alexisdurieux** [comment]
In case someone looks for the same thing @inodentry is correct but the correct config key is `key_bindings` and not `keybindings`.
