### ISSUE TITLE
Mouse doesn't show up with mouse hide_on_typing set to true

### ISSUE THREAD

**Issue by SheldonZhong** [alacritty/alacritty#6452]
### System

OS: macOS 13.0 (22A380)
Version: lacritty 0.11.0 (8dbaa0b)

### Logs

First enable the `hide_on_typing` in the config.
```
mouse:
  hide_when_typing: true
```

Steps to reproduce:

1. Launch Alacritty.
2. Type something in the terminal and don't move your mouse, the cursor is hidden.
3. Switch to a different app using `command` + `tab`.
4. Switch back to Alacritty using `command` + `tab` and don't type anything yet.
5. Swipe fingers on the touchpad or move the mouse, the cursor doesn't show up.

Expected behavior:
- In step 5, the cursor should show up.

**Comment by chrisduerr** [comment]
I'd assume this can be reproduced with the `0.10.X` releases?

**Comment by SheldonZhong** [comment]
> I'd assume this can be reproduced with the `0.10.X` releases?

It can be reproduced with alacritty 0.10.1 (2844606).

**Comment by dj95** [comment]
I observed the same behaviour with Alacrity 0.11.0 and macOS 13.0.

However, when I press the shift key after the cursor is gone, it's coming back.

**Comment by chrisduerr** [comment]
I'm surprised this isn't working, considering we call `set_mouse_visible(true)` whenever the window gets focused.

Does Alacritty actually have window focus after tabbing back to it? So the cursor changes back from the box cursor?

**Comment by SheldonZhong** [comment]
> I'm surprised this isn't working, considering we call `set_mouse_visible(true)` whenever the window gets focused.
> 
> Does Alacritty actually have window focus after tabbing back to it? So the cursor changes back from the box cursor?

The cursor does change back from box cursor. I can also see it gets focused in the log when I run with `alacritty --print-events`.

**Comment by SheldonZhong** [comment]
I looked into this a bit myself. It seems like it we call `set_mouse_visible(true)` when Alacritty *loses* focus.

Here is what I found out:
1. When a user starts typing, `set_mouse_visible(false)`, and `Window.mouse_visible` is set to `false` accordingly. The mouse is invisible.
2. When Alacritty loses focus, `set_mouse_visible(true)` is called, and `Window.mouse_visible` is set to `true` accordingly. The mouse is visible in the other app.
3. When the user switch back to Alacritty, the mouse is **hidden** somehow, which breaks the mouse visible state tracking. I think issue only happens on macOS, since the bug could not be reproduced on my linux machine. When the user starts to give cursor input, `set_mouse_visible(true)` is called, however with `Window.mouse_visible` still being `true`, so `set_cursor_visible(true)` is never called in winit.

https://github.com/alacritty/alacritty/blob/578e08486dfcdee0b2cd0e7a66752ff50edc46b8/alacritty/src/event.rs#L1213-L1219

I tried changing the logic to:
```rust

 if is_focused { 
     self.ctx.window().set_urgent(false); 
     self.ctx.window().set_mouse_visible(true); 
 }

```
then I did a bit of testing, and it seems the bug is fixed. In this bug report's step 5, the mouse is visible with input from the touchpad or mouse. This fix seems to work fine all other platforms. However, I am not sure if there is more complications on this. My concern is if we **really** want to show the cursor when a user switches back to Alacritty right away. I would expect two design choices:
1. A user finishes typing in Alacritty, switches to a different app, and switches back to Alacritty with the mouse visible. Then the user starts to type, the mouse is hidden again. The fix would support this logic: the cursor is visible whenever Alacritty gets focused. Let's call it mouse visibilities' eager mode. 
2. A user finishes typing in Alacritty, switches to a different app, and switches back to Alacritty with the mouse **invisible**. If the user starts to type, the mouse remains invisible. Otherwise the user gives mouse input, the cursor is shown. In this case, the mouse is shown *lazily*. The mouse hidden as long as there is no cursor input, and the mouse is shown only when the user gives mouse input.

Which design do people prefer? I am looking forward to receiving feedback on this.

**Comment by chrisduerr** [comment]
@SheldonZhong It should still work fine when we call `set_mouse_visible(true)` in both branch cases, right? I think that would probably be the safest bet and I'm happy to merge that PR if you want to send it.

**Comment by chrisduerr** [comment]
Also just to clarify, any mouse input like clicking or click + drag makes the mouse visible again, even without this patch, right?

**Comment by SheldonZhong** [comment]
@chrisduerr 

No, it doesn't work when we call it in both cases. The reason is the same as what I described. 
> 2. When Alacritty loses focus, `set_mouse_visible(true)` is called, and `Window.mouse_visible` is set to `true` accordingly. The mouse is visible in the other app.
> 3. When the user switches back to Alacritty, the mouse is hidden somehow, which breaks the mouse visible state tracking.

When `Window.mouse_visible` is `true` and the mouse is actually invisible, all subsequent calls of `set_mouse_visible(true)` do not have any effect on changing the mouse to visible.

https://github.com/alacritty/alacritty/blob/578e08486dfcdee0b2cd0e7a66752ff50edc46b8/alacritty/src/display/window.rs#L314-L322

Only when a user starts typing, i.e., when `set_mouse_visible(false)` is called, will `Window.mouse_visible` be set to `false`. With some mouse input, a call to `set_mouse_visible(true)` can actually change the mouse to visible.

Without the patch being discussed here, any mouse input doesn't make the mouse visible. Refer to the step 5 in this issue.

**Comment by SheldonZhong** [comment]
It seems like the bug is in winit itself. Issue submitted.

**Comment by chrisnc** [comment]
Just removing the cursor visibility call when losing focus fixes the issue for me. Commit below implements option 2 described [here](https://github.com/alacritty/alacritty/issues/6452#issuecomment-1296115182). On macOS at least, each window has its cursor visibility tracked separately, and this persists across focus changes, so there's no need to explicitly make the cursor visible when leaving the window, as the system already does this. I still need to check other platforms, though.

https://github.com/chrisnc/alacritty/commit/bf18866c1b47bbd19e590f639c5da6af6fc288b9
