### ISSUE TITLE
Background Blur for Mac

### ISSUE THREAD

**Issue by codeyStein** [alacritty/alacritty#6461]
So I've got Alacritty as my main terminal for my mac, I used to use iterm2 but I've switched. One thing that I miss is the background blur, is there a way to get background blur in Alacritty on mac?

### System

OS: macOS
Version: `alacritty 0.10.1 (2844606)`

**Comment by chrisduerr** [comment]
Nope.

**Comment by Kamyil** [comment]
Well... the response is outdated, since there is a native way now in the config
https://alacritty.org/config-alacritty.html

<img width="677" alt="Zrzut ekranu 2024-01-5 o 14 50 21" src="https://github.com/alacritty/alacritty/assets/26087070/097ae94d-64eb-4457-8adc-6baac7011a2f">
<img width="1511" alt="Zrzut ekranu 2024-01-5 o 14 51 32" src="https://github.com/alacritty/alacritty/assets/26087070/d7d65e33-e382-4530-b7bb-62dc787e99a6">

Thanks guys for making this work! <3

**Comment by applejwjcat** [comment]
How to achieve this even in full screen mode

**Comment by nixpulvis** [comment]
> How to achieve this even in full screen mode
Maybe I'm just being dumb, but what does blurring a fullscreen app even mean?

**Comment by applejwjcat** [comment]
> > How to achieve this even in full screen mode
> 
> Maybe I'm just being dumb, but what does blurring a fullscreen app even mean?

<img width="1464" alt="Screen Shot 2024-06-04 at 16 52 02" src="https://github.com/alacritty/alacritty/assets/45581427/76f13245-4b6e-4fec-962e-bf981bf81e2f">
I just want the  Acrylic (blur) effect even in full screen mode, it's beautiful. But when I enter this mode, it disappears.

**Comment by Kamyil** [comment]
@applejwjcat It doesn't dissapear. It's actually the macOS thingy where in fullscreen mode there is a nothing behind the app (just a black screen). So Alacritty still blurs, but a black screen underneath
It's most likely not possible to change that unfortunetly as for now :/

**Comment by karshPrime** [comment]
How about an option to set(/use) a terminal window background only when alacritty is fullscreen? while technically this wouldn't be the same as what @applejwjcat described, but its implementation might as well give the same look.

**Comment by mcnaveen** [comment]
Hey @Kamyil Can you share your config?

**Comment by Kamyil** [comment]
@mcnaveen I honestly don't know how did I miss that notification. I'm sorry
Here's my config: https://github.com/Kamyil/.dotfiles/blob/main/.alacritty.toml

**Comment by mcnaveen** [comment]
Hi @Kamyil No problem at all. Thank you for the config!
