### ISSUE TITLE
Alacritty not updating next frame

### ISSUE THREAD

**Issue by winstxnhdw** [alacritty/alacritty#6464]
### System

OS: Arch Linux
Version: alacritty 0.11.0-1
Linux/BSD: i3

### Issue

Alacritty is not updating the next frame. The terminal only updates when (1) a window is opened or (2) a window is closed. Any advice on how to troubleshoot through this issue?

#### What does "next frame not updating" mean?

It means that typing on the terminal does not show up on the terminal, as if the terminal is frozen. In my case, whatever that was typed will be reflected after opening or closing a window.

**Comment by chrisduerr** [comment]
Intel GPU drivers?

**Comment by winstxnhdw** [comment]
@chrisduerr Yeap.

**Comment by winstxnhdw** [comment]
I solved(?) the issue. I uninstalled xf86-video-intel. No idea how is the iGPU still utilised in this case, but it works 😕🤷🏻‍♂️
