### ISSUE TITLE
Alacritty does not start after building on Debian MX Linux

### ISSUE THREAD

**Issue by manujchandra** [alacritty/alacritty#6469]
I am using Method 2 of the following [guide](https://techviewleo.com/install-and-configure-alacritty-terminal-on-debian/) to build Alacritty and I have generated an executable.

When I run it I get the following error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: XError { description: "BadValue (integer parameter out of range for operation)", error_code: 2, request_code: 153, minor_code: 34 }', /home/mankind/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/x11/window.rs:1086:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### System

OS: MX Linux 21.2.1 Debian 11.5
Version: alacritty 0.12.0-dev (0e418bc2)
Linux and QTile

**Comment by kchibisov** [comment]
The commit before this one works, right?

**Comment by manujchandra** [comment]
I was able to install it from downloading the source. Thanks.
