### ISSUE TITLE
lagging when have 3 or more alacritty in one i3wm workspace

### ISSUE THREAD

**Issue by jyi2ya** [alacritty/alacritty#6470]
### System

OS: Linux
Version: alacritty 0.11.0
Linux: X11, i3wm

### Logs

https://user-images.githubusercontent.com/86813521/200128503-24e7fb67-301b-489d-bd2b-b1c6c00f3545.mp4

I hold `i` in the right terminal(the last created one). It looks like it take my input and redraw the window only one time per second. At the same time the left and middle terminal respond quickly. If I close one of the three terminals, the remained two will work well.

I tried other terminals, like `rxvt-unicode` and `lxterminal`, and they worked well. So I think it's not i3's problem.

`inxi` output on my machine:

```plain
System:
  Kernel: 6.0.0-1-amd64 arch: x86_64 bits: 64 Desktop: i3 v: 4.21.1
    Distro: Debian GNU/Linux bookworm/sid
Machine:
  Type: Laptop System: LENOVO product: 82MS v: Lenovo XiaoXinPro 14ACH 2021
    serial: <superuser required>
  Mobo: LENOVO model: LNVNB161216 v: SDK0L77769WIN
    serial: <superuser required> UEFI: LENOVO v: GZCN30WW date: 07/04/2022
CPU:
  Info: 8-core model: AMD Ryzen 7 5800H with Radeon Graphics bits: 64
    type: MT MCP cache: L2: 4 MiB
  Speed (MHz): avg: 3186 min/max: 1200/4462 cores: 1: 2595 2: 3350 3: 3198
    4: 2931 5: 3016 6: 3920 7: 2663 8: 3200 9: 2821 10: 3718 11: 3200 12: 2683
    13: 4373 14: 4392 15: 2656 16: 2263
Graphics:
  Device-1: AMD Cezanne [Radeon Vega Series / Radeon Mobile Series]
    driver: amdgpu v: kernel
  Device-2: Chicony Integrated Camera type: USB driver: uvcvideo
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: amdgpu
    unloaded: fbdev,modesetting,vesa dri: radeonsi gpu: amdgpu resolution:
    1: 3764x2117~60Hz 2: N/A
  API: OpenGL v: 4.6 Mesa 22.2.2 renderer: RENOIR (renoir LLVM 15.0.2 DRM
    3.48 6.0.0-1-amd64)
```

**Comment by chrisduerr** [comment]
How did you install Alacritty? Also your video doesn't play.

**Comment by jyi2ya** [comment]
I installed Alacritty by `cargo install alacritty`.

can the video below play now? :D

https://user-images.githubusercontent.com/86813521/200170002-fe52a10a-2fcc-47b4-a2cf-f4b7a172d557.mp4

**Comment by chrisduerr** [comment]
Does running it with `LIBGL_ALWAYS_SOFTWARE=1 alacritty` fix the issue?

**Comment by jyi2ya** [comment]
> Does running it with `LIBGL_ALWAYS_SOFTWARE=1 alacritty` fix the issue?

@chrisduerr Yes, it works!

**Comment by chrisduerr** [comment]
Then you're running into a driver issue. `LIBGL_ALWAYS_SOFTWARE=1` uses mesa's software rendering. So if that's faster than hardware, things aren't right with your hardware.

**Comment by tkkcc** [comment]
`LIBGL_ALWAYS_SOFTWARE=1` also solves screen flash on workspace change in i3wm.
