### ISSUE TITLE
alacritty.yml not respected, no uninstall instructions

### ISSUE THREAD

**Issue by aum7** [alacritty/alacritty#6471]
- followed install instructions on this page (git clone etc.)
- in terminal (original linux mint) $ alacritty --version
returns alacritty 0.12.0-dev (0e418bc2)
- alacritty terminal text is too small, so i open $ man alacritty
- there --config-file <file> is mentioned
- i locate alacritty.yml, open it for edit, un-comment point 'size: 20.0', among other things
- in terminal (tried both, linux mint terminal & alacritty), i run $ alacritty --config-file ~/alacritty/alacritty.yml
- since i naively removed too much spaces, before the 'size: 20.0', i get terminal error, but i at least know that something is going on, regarding --config-file ...
- i fix the errors in alacritty.yml, and run --config-file cmd again
- this time no errors, nothing, no feedback - i conclude i did everything properly, although i expected some feedback notification, like 'hey prince charming, we did nothing to please you' (since nothing has really changed, regarding alacritty terminal configuration)
- i restart alacritty, and nothing has changed, text is still small
- i also tried copy alacritty.yml to ~/alacritty.yml, and run $ alacritty --config-file ~/alacritty.yml, restart alacritty terminal, no change

- also, when i run $ alacritty --config-file <path-to-alacritty.yml>, from alacritty terminal, new alacritty terminal window opens, not sure why, i did not request this

- also, no instructions how to uninstall alacritty terminal - please tell me / include instructions how to remove / uninstall alacritty from system

### System

OS: Linux mint 21 vanessa cinammon
Version: `alacritty --version` output = alacritty 0.12.0-dev (0e418bc2)
Linux/BSD: [INFO ] [alacritty] Running on X11

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
$ alacritty -vv
[INFO ] [alacritty_config_derive] No config file found; using default
...
[INFO ] [alacritty] Running on AMD RENOIR (LLVM 13.0.1, DRM 3.42, 5.15.0-52-generic)
...
[DEBUG] [alacritty] Loading "monospace" font
[0.068504022s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.070412983s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.072329557s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.074193046s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
...
[INFO ] [alacritty] Width: 800, Height: 600

Keyboard and bindings: `alacritty --print-events`

best regards,

aum
s love nia

**Comment by aum7** [comment]
ok, my bad, should have un-comment top-level setting, ie i did not un-comment neither #font, nor #window (i was not familiar with yaml syntax, now i am)

fixed, works like a charm
ignore this issue

aum
s love nia

**Comment by chrisduerr** [comment]
> when i run $ alacritty --config-file <path-to-alacritty.yml>, from alacritty terminal, new alacritty terminal window opens, not sure why, i did not request this

Yes you did.

> also, no instructions how to uninstall alacritty terminal - please tell me / include instructions how to remove / uninstall alacritty from system

This depends on how you installed it.
