### ISSUE TITLE
Overlap buttons and the terminal content on MacOS with window decorations: transparent

### ISSUE THREAD

**Issue by DucNgn** [alacritty/alacritty#6475]
With the decorations set for macOS as transparent

```yml
window:
        decorations: transparent
```

The buttons are overlapped with the terminal window as followed: (notice the prompt is displayed under the buttons of the window)

<img width="912" alt="image" src="https://user-images.githubusercontent.com/43587865/200632272-ef036947-642d-4b25-8e94-94d4639ba078.png">

### System
OS:  MacOS Ventura
Version: 0.11.0

**Comment by chrisduerr** [comment]
#1671.
