### ISSUE TITLE
Cursor stretch with increased line height (vertical padding)

### ISSUE THREAD

**Issue by effinsky** [alacritty/alacritty#6483]
With increased line height / line spacing / vertical padding / y padding the cursor is stretched and looks increasingly ugly. Could we have it not stretch at all? (as is currently the case, for instance in iterm2 or JetBrains editors). 

Please see images below: 

iterm2: 
<img width="175" alt="Screenshot 2022-11-11 at 11 29 09" src="https://user-images.githubusercontent.com/54535543/201322435-0c093fd7-e651-4397-9952-73fc02c7c93c.png">

alacritty (with offset settings set to x: 0, y: 13):
<img width="150" alt="Screenshot 2022-11-11 at 11 30 53" src="https://user-images.githubusercontent.com/54535543/201322509-123f02cb-23f9-4fab-908e-bbdebc39f2c0.png">

Thanks in advance for your attention.

**Comment by chrisduerr** [comment]
Working as expected.

**Comment by effinsky** [comment]
I understand this is expected by you specifically. This looks bad though. And the worse, the more offset one uses. Do consider reimplementing.
