### ISSUE TITLE
alacritty -e option does not work for one shot console programs

### ISSUE THREAD

**Issue by benibilme** [alacritty/alacritty#6484]
Hello

I do not know if this a bug or not: 

I  am using alacritty version 0.11.0 along with manjaro linux 22.0.0 with i3wm  

It seems that -e option is not working for some terminal programs found in the linux environment if they are one shot commands that do something and terminates. 

I can not get a new terminal open from i3wm config or from d-menu for following commands. Those commands also fails within an alacritty terminal 

alacritty -e /usr/bin/task # taskwarrior program.  
alacritty -e ls 

however following commands worked as expected, if started with d-menu or i3wm config, a new terminal window appears running those programs. 

alacritty -e tmux
alacritty -e vim  

I guess, alacritty terminates if the commands passed with -e option terminates. tmux and vim are standing, so alacritty displays terminal properly but I am not sure. Is this behaviour correct? I haven not seen it in man page. 

How can I make alacritty display output of a command when a terminal command is passed with -e option.

**Comment by chrisduerr** [comment]
Works exactly as expected, you might want `--hold`.

**Comment by benibilme** [comment]
Hello, 
I am suprized that I missed --hold option, thank you. However, --hold option does not give console prompt after the command and hangs. I am forced to kill the terminal window.  I would like to be able to use the terminal as if I opened normally.

**Comment by kchibisov** [comment]
Then run your shell instead and tell it to open what you want? Since clearly you want to use shell after closing nvim, so you should run it and open nvim in it.

**Comment by benibilme** [comment]
Hello,

I could not create a new alacritty  which  runs a command and be in interactive state with following either within alacritty itself or from an external enviroment like dmenu 

````
alacritty -e bash -i  /usr/bin/task
alacritty -e bash /usr/bin/task 
alacritty -e bash '/path/to/script/that/calls/task'
````

Based on the stackoverflow discussion above, following works in an existing alacritty terminal but not from an external program like dmenu. 

````
alacritty -e bash --rcfile <(echo '. /home/userhome/.bashrc; /usr/bin/task')
````

I am really confused about what to do.

**Comment by kchibisov** [comment]
Try something like that. It basically runs `bash`, then it launches your program, and then on program exit you continue in bash.

`alacritty -e bash -c "YOUR_PROGRAM; exec bash"`

Use whatever shell you want here. Not sure what is your end goal.

**Comment by benibilme** [comment]
Thank you, that does what I want.  I just to be able to stay in an interactive session in alacritty shell after executing a command initially. This does it. Thanks again. 

> Try something like that. It basically runs `bash`, then it launches your program, and then on program exit you continue in bash.
> 
> `alacritty -e bash -c "YOUR_PROGRAM; exec bash"`
> 
> Use whatever shell you want here. Not sure what is your end goal.
