### ISSUE TITLE
The wiki has been edited to have a link to ransomware

### ISSUE THREAD

**Issue by Zinvoke** [alacritty/alacritty#6488]
Happened to polybar last night aswell and others
![vivaldi_dbejCHucVi](https://user-images.githubusercontent.com/84819317/201501143-5b9f3e5d-6168-4ff5-9d03-3c03c9cb9424.png)

The download links in the wiki redirect to:
https://github.com/AhmedAboSamra/VideoCaptureUtility/releases/tag/42

I have removed the links from the wiki page.

**Comment by chrisduerr** [comment]
Thanks. It's strange that this didn't show up on the changes in my home feed as they usually did. But it seems like the author has been banned since making the changes? I cannot see the diff when comparing the revisions myself.
