### ISSUE TITLE
The shortcut `Ctrl+;` doen't have effect in `neovim`

### ISSUE THREAD

**Issue by rust-kotlin** [alacritty/alacritty#6491]
I set a shortcut in the neovim `vim.keymap.set('i', '<C-;>', '::') -- for C++ and Rust`.
I can say it works perfectly in neovim-qt.exe.
While in this terminal emulator, when I press`Control+;`, nothing happens.

### System
OS: Windows 11 22h2
Version: alacritty 0.10.1

**Comment by kchibisov** [comment]
Hm, I'd guess you need to define a binding manually to whatever neovim expects. There's no `ctrl + ;` binding in xterm spec.

**Comment by rust-kotlin** [comment]
Yeah, I seemed to know what I should do. I don't know whether I should write like this:
`    - { key: SemiColon, mods: Control, chars: "\E[9;8~"}`  then I write in the neovim lua config file `vim.keymap.set('i', '^[[9;8~', '::') -- for C++ and Rust `
I haven't found the key `SemiColon` in the template alacritty.yml.
I have got this idea from an answer in StackOverflow.

> In KDE konsole terminal, you can add key bindings.
terminal right click menu --> Edit Current Profile --> keyboard --> Edit
I have added a value like this:
Key Combination =>  ;+Ctrl  
Output          =>  \E[9;8~   
then you can check the value with Ctrl-V Ctrl-; in termnal.
if successfully printed ^[[9;8~ then you can use the value in vim key bindings something like this
inoremap  ^[[9;8~  <esc>A;
you also need to type Ctrl-V Ctrl-; for the value after inoremap

**Comment by kchibisov** [comment]
You should do `chars: "\x1b[9;8~"` other than that it should be fine. You can also check what `virtual_key` is being used with `alacritty --print-events`.

**Comment by rust-kotlin** [comment]
> You should do chars: "\x1b[9;8~" other than that it should be fine

Thanks for your advice. I tried it out but nothing happens. I tried `alacritty --print-events` but was not quite aware of what happened. I am now testing with other shortcut to help figure out what happens.

**Comment by asmodeus812** [comment]
@kchibisov could you explain what the sequence means in this case ? i find it difficult to understand those. Thanks !

**Comment by kchibisov** [comment]
>@kchibisov could you explain what the sequence means in this case ? i find it difficult to understand those. Thanks !

`ESC [ 9 ; 8`, The first character is ESC, so the applications knows that you're sending the espace sequence. What it means is app specific in that particular case, since I'm not sure it's a standard espace for encoding the chars.
