### ISSUE TITLE
Confused about #6490

### ISSUE THREAD

**Issue by rust-kotlin** [alacritty/alacritty#6492]
https://github.com/alacritty/alacritty/issues/6490

> In general you don't need to touch it, since it'll use the right command on windows automatically.

It's true, when I delete the key of command, it will open the right web page with the default browser.
But everytime I open alacritty, it will give an error at the bottom of the window.
()[https://user-images.githubusercontent.com/105690584/201508321-75bd7d1d-1ca4-4ae7-bcdd-4e48580922cb.png]

> Otherwise provide a real command.

Why start is not a real command?

**Comment by kchibisov** [comment]
Please, don't open tons of issues, and just wait on the ones you've opened for reply. It's not a live support platform or anything, replies may come with a big delay, since folks on the other end have their lives as well.
