### ISSUE TITLE
[macOS] alacritty now uses discrete GPU

### ISSUE THREAD

**Issue by jasonhan-vassar** [alacritty/alacritty#6498]
I noticed that since commit 778558060243505d07b0850a115e3944862db5cd, alacritty triggers the discrete GPU on macOS when launched. Having the discrete GPU activated makes my laptop heat up and it seems a bit overkill for alacritty — is this intentional? The past versions didn't have this behavior.

### System

OS: macOS
Version: `alacritty 0.12.0-dev (77855806)`

**Comment by kchibisov** [comment]
Are you sure that it's this commit and not something earlier?

**Comment by jasonhan-vassar** [comment]
Oops, I should've clarified that I only tested the latest commit. I just tested a few and I figured out the exact commit: 0e418bc2f761617455cc58aaabc375055dfe4284. I can confirm the last commit without this is the one right before it: 578e08486dfcdee0b2cd0e7a66752ff50edc46b8.

**Comment by kchibisov** [comment]
It's strange that it uses dedicated GPU now given that hardware accel options are the same... Maybe the pixel format is more fancy now...

Also, are you using the `app` file? If not please use the `app` and not run the binary.

**Comment by jasonhan-vassar** [comment]
Yep, using the `.app` file! I noticed the binary always triggers the discrete GPU even in the old versions.

**Comment by chrisduerr** [comment]
Can you try changing the line after `NSSupportsAutomaticGraphicsSwitching` in Alacritty's `Info.plist` from `<true/>` to `<false/>`?

**Comment by jasonhan-vassar** [comment]
I just tried that and it didn't seem to work. FWIW, I've had to add `NSSupportsAutomaticGraphicsSwitching` as `true` to other apps that triggered the GPU before, not `false`.

**Comment by chrisduerr** [comment]
Yeah I just thought it might be worth a shot.

**Comment by kchibisov** [comment]
@jasonhan-vassar could you try this applying this patch

```diff
diff --git a/Cargo.lock b/Cargo.lock
index fa2eac1d..3808c99c 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -667,9 +667,8 @@ dependencies = [
 
 [[package]]
 name = "glutin"
-version = "0.30.0"
-source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "34acbf502536f1d125f0fc09b6ad8824e93e6da7b99e86d3383e6b8310ba3554"
+version = "0.30.1"
+source = "git+https://github.com/kchibisov/glutin?branch=cgl-offline-renderers#36b5201d34e8999087b912391a17f7c0447290ef"
 dependencies = [
  "bitflags",
  "cfg_aliases",
@@ -690,9 +689,8 @@ dependencies = [
 
 [[package]]
 name = "glutin_egl_sys"
-version = "0.3.0"
-source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "2c3c95a2d7a54bab0c74759794efb5cd63470d4504cbe85ed4114dc82c98bdc1"
+version = "0.3.1"
+source = "git+https://github.com/kchibisov/glutin?branch=cgl-offline-renderers#36b5201d34e8999087b912391a17f7c0447290ef"
 dependencies = [
  "gl_generator",
  "windows-sys",
@@ -701,8 +699,7 @@ dependencies = [
 [[package]]
 name = "glutin_glx_sys"
 version = "0.3.0"
-source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "947c4850c58211c9627969c2b4e2674764b81ae5b47bab2c9a477d7942f96e0f"
+source = "git+https://github.com/kchibisov/glutin?branch=cgl-offline-renderers#36b5201d34e8999087b912391a17f7c0447290ef"
 dependencies = [
  "gl_generator",
  "x11-dl",
@@ -711,8 +708,7 @@ dependencies = [
 [[package]]
 name = "glutin_wgl_sys"
 version = "0.3.0"
-source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "20c33975a6c9d49d72c8f032a60079bf8df536954fbf9e4cee90396ace815c57"
+source = "git+https://github.com/kchibisov/glutin?branch=cgl-offline-renderers#36b5201d34e8999087b912391a17f7c0447290ef"
 dependencies = [
  "gl_generator",
 ]
diff --git a/Cargo.toml b/Cargo.toml
index aad21557..469362dc 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -10,3 +10,6 @@ members = [
 lto = true
 debug = 1
 incremental = false
+
+[patch.crates-io]
+glutin = { git = "https://github.com/kchibisov/glutin", branch = "cgl-offline-renderers" }

```

**Comment by jasonhan-vassar** [comment]
Just tried that — it works! Thanks for the quick fix. I'm curious what you changed in glutin that solved this issue.
