### ISSUE TITLE
“Alacritty” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by glyph** [alacritty/alacritty#6500]
It looks like the `.dmg` files in the releases are not properly codesigned and notarized, so they do not run out of the box:

![image](https://user-images.githubusercontent.com/716529/201825586-407fbb47-a9a5-4e22-b82f-0095abb836c3.png)

### System

OS: macOS
Version: `alacritty --version` output
Since it cannot run:
```
zsh: killed     /Applications/Alacritty.app/Contents/MacOS/alacritty --version
```

The file in question is `Alacritty-v0.11.0.dmg`, however.

**Comment by kchibisov** [comment]
We don't pay apple for the certificate to ship free software, sorry. We do codesign on CI, but it's not authorized with apple.

**Comment by wad209** [comment]
I don't know why they didn't tell you how to bypass this issue, but since I ended up here trying to figure it out, here's what I found:

1. Right click the icon and hit open
2. Click open on the dialog that appears

That's it! Why isn't open an option when you just click on it? I don't know...

**Comment by adambair** [comment]
> This breaks for me every time I upgrade. The fixes that work for me are here: [#4673 (comment)](https://github.com/alacritty/alacritty/issues/4673#issuecomment-771291615)

Thanks for the helpful response, this is a pain.

**Comment by blkpws** [comment]
> > This breaks for me every time I upgrade. The fixes that work for me are here: [#4673 (comment)](https://github.com/alacritty/alacritty/issues/4673#issuecomment-771291615)
> 
> Thanks for the helpful response, this is a pain.

Apple is a pain... I agree.

**Comment by darkgraycat** [comment]
[wadeduvall](https://github.com/wadeduvall), Another option is build Alacritty from source

**Comment by joaothallis** [comment]
With the new MacOS version (Sequoia 15) there's no option to open using [right click and open.](https://github.com/alacritty/alacritty/issues/6500#issuecomment-1356318595)

In this [link](https://sixcolors.com/post/2024/09/macos-sequoia-review/) there's an explanation about the problem and solution

**Comment by glyph** [comment]
> In this [link](https://sixcolors.com/post/2024/09/macos-sequoia-review/) there's an explanation about the problem and solution

It seems pretty clear that Apple is going to make this more and more annoying every release, since once one of these workarounds is widely known (specifically "widely known among people who do not understand its security implications"), it's important for security reasons that it no longer work.

The solution here is for someone to donate the time & money to have this properly notarized.  I have a developer ID account and I wouldn't mind donating the code-signing part, but there's also a bunch of work to do to upload the relevant stuff to Github so it can be code-signed in CI and whatnot.  So I would hesitate to say "I'll do it" since that involves signing up for a bunch of *work* in addition to the yearly $99.

**Comment by chomatdam** [comment]
you can also just run `xattr -dr com.apple.quarantine "/Applications/Alacritty.app"` to allow this unidentified app

**Comment by malcojus** [comment]
In addition to @chomatdam solution (thanks for that, love a good CLI fix), it looks like you can also do the following through the UI:
* Settings->Security and Privacy
* Scroll down to Security section at the bottom
* If you tried to open Alacritty, there should be an option to "Open Anyway" from one of the options in this section.

**Comment by bboydflo** [comment]
I had installed alacritty via brew and I had to do the following:

```sh
# first install python 3.9 didn't work with the mac python version
brew install python@3.9
# install xattr globally
pip install xattr
# run the following command
xattr -d  /opt/homebrew/bin/alacritty
```
