### ISSUE TITLE
Some symbols have a strange line next to them

### ISSUE THREAD

**Issue by ThomasFrans** [alacritty/alacritty#6505]
Some characters/symbols have these weird lines next to them. I have no idea what causes them, and it only happens for these specific "drawing" characters. It's easiest to show in a picture. Here, they are visible next to the tabs (Development, Run/Debug, ...):
![image](https://user-images.githubusercontent.com/48214567/202425595-399a7346-9d80-4464-ada9-2db1cbc69e74.png)

They've only showed up in Zellij. Neovim also has a tab bar that uses the same symbols, but they don't show up in Neovim. I still report this here because it seems unlikely that Zellij could cause graphical errors in Alacritty, since Alacritty is responsible for the drawing.

### System

OS: Linux (Acrh, latest updates)
Version: alacritty 0.11.0 (8dbaa0bb)
Linux/BSD: X11, Gnome

### Logs
![image](https://user-images.githubusercontent.com/48214567/202424930-d4881ec4-5b63-47cf-a5e4-2098e5e6cecc.png)

**Comment by kchibisov** [comment]
It's an issue of some fonts having strange subpixel mask for these glyphs. You can try disabling subpixel rendering in a fontconfig or try different font with those glyphs.
