### ISSUE TITLE
Each window instance appear as a separate icon in macOS dock

### ISSUE THREAD

**Issue by danrot** [alacritty/alacritty#6511]
In Mac OS multiple windows of an application are only shown once in the dock, and if you have multiple windows open you can right click the icon in the dock and see a list of windows:

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/405874/202710461-a2d4a17e-629d-4cbf-88f8-32438dcef985.png">

However, alacritty does not seem to behave in the same way. If I open multiple alacritty windows using Ctrl+n, then each instance is a separate icon in the mac OS dock, as the above screenshot also shows.

### System

OS: macOS
Version: 0.11.0 (1)

**Comment by chrisduerr** [comment]
Working as expected. You have the option to open multiple windows from the same instance through CLI or config.

**Comment by danrot** [comment]
Well, since I don't know any other application that works this way, I would not say that this is working as expected. However, how exactly can I open windows from the same instance? I sincerely don't know how to do that. I don't have an `alacritty` command available on the command line.

**Comment by chrisduerr** [comment]
Working as expected means it works as I expect it, not as you might.

**Comment by danrot** [comment]
It would already be of great help if you could further elaborate on what you mean by "You have the option to open multiple windows from the same instance through CLI or config.".

**Comment by kchibisov** [comment]
https://github.com/alacritty/alacritty/blob/d92a8a0e16eda3df7566e5c995aa0d258b6b76f7/alacritty.yml#L620

**Comment by danrot** [comment]
Thank you! Adding the following lines in `alacritty.yml` fixed this issue for me:

```yaml
key_bindings:
    - { key: N, mods: Command, action: CreateNewWindow }
```

But I still want to stress that I am certain that this is not the expected behavior from any macOS user. And even with this solution the windows do not turn up in the dock for some reason (although that is just a minor issue for me personally).

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/405874/202843671-e18bc47f-134c-4a36-8072-77a8df98469f.png">

I understand that I am not entitled here in any way, and that you might not have time to do that, but calling it the expected behavior is still the wrong call IMO.
