### ISSUE TITLE
vi mode - character search

### ISSUE THREAD

**Issue by qtc-de** [alacritty/alacritty#6514]
Hi there :wave:

first of all, thank you all for your great work. I really love alacritty :heart: 

I have a feature request for vi mode. Would it be possible to implement vi's *character search*? E.g. when you press `f;` that the cursor jumps to the next occurrence of `;` in the current line? In vi, I use this a lot to move around quickly and it would be great to also have this possibility in alacritty.

Best
Tobias

**Comment by chrisduerr** [comment]
There's currently no plan to add support multi-character vi bindings.
