### ISSUE TITLE
Window clipping when maximized and `decorations` set to `none` on Windows

### ISSUE THREAD

**Issue by ok-nick** [alacritty/alacritty#6515]
![image](https://user-images.githubusercontent.com/25470747/202878783-3b943f98-53be-4229-a2bd-d3e38d4bf8f0.png)

**Comment by chrisduerr** [comment]
Which version? Is this a regression or can you reproduce it with previous versions too?

**Comment by ok-nick** [comment]
I tried `0.9.0` and `0.10.0` but the `Windows + Up` key doesn't work to maximize the window. I also tried setting `startup_mode: Maximized` in my `alacritty.yml`, but it doesn't maximize on open for any version of `alacritty`.

**Comment by chrisduerr** [comment]
What about adding a `Maximize` key binding manually?

**Comment by ok-nick** [comment]
`Maximize` keybind doesn't exist

**Comment by chrisduerr** [comment]
Huh, you're right. Must have confused it with `Minmize`.

Which Windows version are you on?

**Comment by ok-nick** [comment]
Version 21H2 (OS Build 22000.1281)

**Comment by chrisduerr** [comment]
Reported upstream in https://github.com/rust-windowing/winit/issues/2568.

**Comment by brian6932** [comment]
Can reproduce
On Windows 10

**Comment by GlekoMa** [comment]
Here meet this problem, too(Windows 11 22H2 22621.963). And I find a solution to solve it **manually**.

> I used Windows Terminal, and it displays right. And I noticed that the Windows Terminal have a default config in my computer:

![terminal](https://user-images.githubusercontent.com/97289978/210227116-25f77587-1035-47d2-ac6c-678132a2b4b7.png)

So I tried setting this in `alacritty.yml` and successfully fixed this problem:

```
window:
  padding:
    x: 8
    y: 8
```

**Comment by brian6932** [comment]
This issue is still reproducible for me when alt tabbing into alacritty windows with `decorations: none`, changing `dynamic_padding` or adjusting `padding` `x` and `y`, had no effect.
alacritty 0.12.0 (5a728195)
Windows 10

**Comment by keaising** [comment]
One year later,  I think Windows Terminal is an option you can try.
