### ISSUE TITLE
cant open alacritty on windows, I just get an error

### ISSUE THREAD

**Issue by thecodsman** [alacritty/alacritty#6516]
I cant open alacritty at all I just get an error
### System

OS: Windows
Version: alacritty 0.11.0 (8dbaa0b)

### Logs

error:
![image](https://user-images.githubusercontent.com/34220198/202960813-0a7395b0-54d6-4ae0-afc1-87157b9b7c58.png)

**Comment by chrisduerr** [comment]
Looks like your `PATH` is broken, you need to have your shell in your path. On Windows that's probably going to be powershell.

**Comment by thecodsman** [comment]
ok that worked but what if I wanted to use something like git-bash as my shell, how would I do that?

**Comment by chrisduerr** [comment]
You add it to your path.
