### ISSUE TITLE
Help Required identifying the window broder theme

### ISSUE THREAD

**Issue by ninetynin** [alacritty/alacritty#6521]
![image](https://user-images.githubusercontent.com/91336664/203391239-08cae774-e883-4130-9083-c1df6b053a6b.png)

THIS IS NOT A BUG!!!

there is no discussions tab thats why im asking here...

can someone say what's the theme that is used for alacritty when there is no border theme applied i wanna use it for my while global window broders thats why

**Comment by chrisduerr** [comment]
The decorations are custom decorations drawn by a library Alacritty depends on. We're not using GTK or Qt and as such we're not using a GTK or Qt theme. So there simply is none you could just choose for all your applications.

**Comment by chrisduerr** [comment]
I mean in the latest versions we're using https://github.com/PolyMeilex/sctk-adwaita, previously it was just drawn by sctk itself (the version from your screenshot).
