### ISSUE TITLE
Support paste hints text along with a format string

### ISSUE THREAD

**Issue by mrwensim** [alacritty/alacritty#6523]
Hi,

I've managed to configure alacritty to paste hints text to the terminal with the Action of Paste. But I''m wondering if it supports pasting the text with a format string.
For example, if the hint text is a git commit id, how can I paste it as "git show [commit id]" in my terminal, rather than type "git show " first and then paste the hint text. 

Thanks in advance.

**Comment by chrisduerr** [comment]
This is not possible.
