### ISSUE TITLE
Alacritty desktop icon does not open new terminal

### ISSUE THREAD

**Issue by nahuakang** [alacritty/alacritty#6524]
As the title suggests, the desktop icon does not open `alacritty` but crashes and the terminal `alacritty` command works properly from another terminal emulator.

### System

OS: Ubuntu 22.04 LTS
Version: 0.11.0

### Logs

`/varlog/syslog` shows the following issue:

```
Nov 23 15:52:55 nahua-thinkpad gnome-shell[2621]: Object .MetaWindowActorWayland (0x56211a6e5b30), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
```

**Comment by chrisduerr** [comment]
How did you install Alacritty?

**Comment by nahuakang** [comment]
I've done it via `cargo install` as well as cloning the repo for a manual build.

**Comment by chrisduerr** [comment]
So how did you install the desktop file? None of that provides an icon to click on.

**Comment by nahuakang** [comment]
Inside the repository there's the `extra/linux` and `extra/logo` directories which provide the logo/icon as well as the `.desktop` template.

Fwiw I've moved on to using `wezterm` for now since I couldn't fix this issue on Ubuntu :cry:

**Comment by kchibisov** [comment]
Please, ensure that alacritty is your global path(you add it on the login and not in your `rc` file).

Otherwise desktop icon won't be able to find the package. I'd assume everything starts normally from the terminal.
