### ISSUE TITLE
where is all the possible configuration options documented?

### ISSUE THREAD

**Issue by airtonix** [alacritty/alacritty#6525]
homepage reveals nothing
looking `docs/` reveals nothing
there's a folder called `alacrity_config` but it's just rust code... I'm not a rust developer so i wont be able to make sense of that.

Am I blind? did I miss the incredibly obvious link that's titled: 

> HERE YOU PEASANT, TREMBLE AND BEHOLD THE GLORIOUS CONFIGURATION DOCUMENTATION!!!!

**Comment by airtonix** [comment]
OK so it's here.... https://github.com/alacritty/alacritty/blob/master/alacritty.yml

probably should at least link to that

**Comment by chrisduerr** [comment]
> Am I blind? did I miss the incredibly obvious link that's titled:

Yes you are.
