### ISSUE TITLE
Low performance on Windows

### ISSUE THREAD

**Issue by grongor** [alacritty/alacritty#6527]
Hello,

since Alacritty seems to be the most performant terminal out there, I'm getting way better results with Windows Terminal. And I don't know why. Can you help me find out why is Alacritty so slow on my system? 

Screenshot from running a test on WSL2 Fedora, bash:

![image](https://user-images.githubusercontent.com/972493/203813013-4be708e2-aea5-4c25-932c-bd75626549a1.png)

### System

OS: Windows
Version: alacritty 0.11.0 (d23330a)
OS Name	Microsoft Windows 11 Pro
Version	10.0.22621 Build 22621
Processor	AMD Ryzen 9 5900X 12-Core Processor, 3701 Mhz, 12 Core(s), 24 Logical Processor(s)
Installed Physical Memory (RAM)	64,0 GB
GPU Name	NVIDIA GeForce RTX 3090

**Comment by chrisduerr** [comment]
I mean your benchmark is pretty much garbage, so that certainly doesn't help. Especially if that's reading from NTFS which might be the slowest filesystem known to man.

So unless you run benchmarks that actually produce useful data, you won't gain much insight.

**Comment by grongor** [comment]
I honestly have no idea how to benchmark terminals. I've seen a similar snippet in the issues of this repo, and it seemed like it could work. It was from inside the Linux container, so it shouldn't be reading from NTFS.

Could you please tell me how to test this properly then? Alacritty is noticeably slower on my machine, and I just want to fix that...

**Comment by chrisduerr** [comment]
https://github.com/alacritty/alacritty#faq

**Comment by kchibisov** [comment]
Benchmarking anything on windows is completely irrelevant until you use the same ConPty for everything and you'll benchmark the conpty interface anyway.

Windows terminal is using their own vendored build of the CopPty, while we use the system available one, and they surely may differ in terms of the throughput performance.
