### ISSUE TITLE
Can't awaken the input method(fcitx5)

### ISSUE THREAD

**Issue by littleantgithub** [alacritty/alacritty#6528]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Arch Linux  Kernel: x86_64 Linux 6.0.9-arch1-1
Version: alacritty 0.11.0 (8dbaa0bb)
Linux/BSD: X11
 WM:i3

### The problem
Can't awaken the input method (fcitx5), can't type in Chinese.

**Comment by kchibisov** [comment]
I can't repro that issue, everything wakes up for me normally and I can type... Maybe your fcitx config is not setup for XIM?

**Comment by littleantgithub** [comment]
> I can't repro that issue, everything wakes up for me normally and I can type... Maybe your fcitx config is not setup for XIM?

   Should not set the problem, at least before can be normal use. At present in other software such as chrome, vscode can use. Yesterday to try for a long time did not find a solution, but found that among the Terminator switch can be normal, but unable to switch in the middle of the up 'konsole'. -- -- -- -- -- I haven't updated the system,     the updated just now can't use the input method. Now I'm not sure where is caused by the problem. What is the condition that I wasn't really trigger. Because there is no error. I also try to relegation, but still can't solve. 

If you can't reappear this issue, that point not on the alacritty.

I use startx to start i3.and my fcitx version is fcitx5-im

**Comment by alexlai97** [comment]
same issue, but can't fix it by downgrading the alacrity or fcitx.

**Comment by wongsingfo** [comment]
Same issue. Cannot activate fcitx5 in Alacritty after a system update recently. But fcitx5 works in other applications like chrome and konsole.

**Comment by 67906980725** [comment]
``` shell
echo '
# cn
export LANG="zh-CN.UTF-8" 
export LC_ALL="en_US.UTF-8"
#  fcitx
export GTK_IM_MODULE="fcitx"
export QT_IM_MODULE="fcitx"
export XMODIFIERS="@im=fcitx"
export INPUT_METHOD="fcitx"
export XIM="fcitx"
export XIM_PROGRAM="fcitx"
export SDL_IM_MODULE="fcitx"
export GLFW_IM_MODULE="ibus"
' >> ~/.profile
echo '
. "$HOME/.profile"
' >> ~/.zshenv
```

**Comment by dongho-jung** [comment]
> ```shell
> echo '
> # cn
> export LANG="zh-CN.UTF-8" 
> export LC_ALL="en_US.UTF-8"
> #  fcitx
> export GTK_IM_MODULE="fcitx"
> export QT_IM_MODULE="fcitx"
> export XMODIFIERS="@im=fcitx"
> export INPUT_METHOD="fcitx"
> export XIM="fcitx"
> export XIM_PROGRAM="fcitx"
> export SDL_IM_MODULE="fcitx"
> export GLFW_IM_MODULE="ibus"
> ' >> ~/.profile
> echo '
> . "$HOME/.profile"
> ' >> ~/.zshenv
> ```

I don't like cargo cult tho.. this works like a charm..! 

I had the issue when I open alacritty with `i3-msg exec` fcitx can't recognize it but when I open alacritty with commandline (i.e. in terminal) fcitx recognize it.

**Comment by 67906980725** [comment]
> > ```shell
> > echo '
> > # cn
> > export LANG="zh-CN.UTF-8" 
> > export LC_ALL="en_US.UTF-8"
> > #  fcitx
> > export GTK_IM_MODULE="fcitx"
> > export QT_IM_MODULE="fcitx"
> > export XMODIFIERS="@im=fcitx"
> > export INPUT_METHOD="fcitx"
> > export XIM="fcitx"
> > export XIM_PROGRAM="fcitx"
> > export SDL_IM_MODULE="fcitx"
> > export GLFW_IM_MODULE="ibus"
> > ' >> ~/.profile
> > echo '
> > . "$HOME/.profile"
> > ' >> ~/.zshenv
> > ```
> 
> I don't like cargo cult tho.. this works like a charm..!
> 
> I had the issue when I open alacritty with `i3-msg exec` fcitx can't recognize it but when I open alacritty with commandline (i.e. in terminal) fcitx recognize it.
> 
> EDIT) I moved the fcitx configuration to the home manager in NixOS, but it set the environment variables after starting i3. So, when I explicitly set the environment variables in the display manager session commands before launching i3, fcitx started working well in alacritty executed via i3-msg.
Oh, NixOS is nice, and i3 is nice too
