### ISSUE TITLE
[QUESTION] Integrate Alacritty with Windows Terminal profiles

### ISSUE THREAD

**Issue by otavio-silva** [alacritty/alacritty#6534]
### System

OS: Windows 11 Pro (21H2)
Version: alacritty 0.11.0 (8dbaa0b)

### Issue
I have not found a way to integrate Alacritty with Windows Terminal. I have, for example, this profile:
```json
{
                "commandline": "C:/ProgramData/scoop/apps/msys2/current/msys2_shell.cmd -defterm -here -no-start -msys",
                "font": 
                {
                    "face": "Lucida Console",
                    "size": 11
                },
                "guid": "{71160544-14d8-4194-af25-d05feeac7233}",
                "icon": "C:/ProgramData/scoop/apps/msys2/current/msys2.ico",
                "name": "MSYS / MSYS2",
                "startingDirectory": "C:/ProgramData/scoop/apps/msys2/current/home/%USERNAME%"
},
```
How can I make it use Alacritty inside the Windows Terminal window and not open a new one independently?
I want Alacritty to use the Windows Terminal configurations and options, but I don't know how.

**Comment by chrisduerr** [comment]
You can't. They're two completely different applications.
