### ISSUE TITLE
ctrl+u and ctrl+k are sent without ctrl

### ISSUE THREAD

**Issue by mskar** [alacritty/alacritty#6541]
Alacritty sends ctrl+k and ctrl+u without the modifier.

### To Reproduce
1. open a document with vim
2. press ctrl+u
Vim will undo the previous change (if it exists otherwise it shows a message: `Already at oldest change`) instead of going up one page.

### Screenshots
<img width="639" alt="image" src="https://user-images.githubusercontent.com/13444106/205363573-d8494284-eaff-4887-8abe-5581e97ee004.png">

### Environment details
<img width="244" alt="image" src="https://user-images.githubusercontent.com/13444106/205363699-c504f298-25b7-4788-875f-3423075a1261.png">

### System

OS: macOS
Version: alacritty 0.11.0 (8dbaa0b)

### Logs

I don't see this problem after I run `alacritty --print-events`

**Comment by mskar** [comment]
I see the same issue in Kitty, but not iTerm2, Tabby, or Hyper.

**Comment by chrisduerr** [comment]
> I see the same issue in Kitty

Sounds like you have some global keyboard thing setup that messes with things?

Considering Alacritty's and Kitty's keyboard handling are **completely** different, if neither work the problem is likely you.

**Comment by mskar** [comment]
If I figure out why everything works in iTerm2, Tabby, and  Hyper, but not kitty or alacritty, I'll post here.

**Comment by mskar** [comment]
The problem in my case was my custom keyboard layout. When I switch back to the default keyboard layout, the problem goes away. Switching to the custom keyboard layout recreates the problem.
