### ISSUE TITLE
[Feature Request] Allow Running a Script in Configuration File (`YAML`)

### ISSUE THREAD

**Issue by RoyiAvital** [alacritty/alacritty#6543]
I like the ability to launch Alacritty with different profiles.
I can set system environments per profile which gives me portable environment.

Yet to make the experience more complete I'd like the option to run a script defined in the `YAML` file so I can do more complex operations to set the environment.

**Comment by kchibisov** [comment]
You could either wrap alacritty in a script or set your environment from the shell(you can even set it from the `env` section in alacritty).
