### ISSUE TITLE
using alacritty as program display?

### ISSUE THREAD

**Issue by ky438** [alacritty/alacritty#6545]
I'm writing a C++ program (Linux X11/GLX) that would ideally be able to spawn and destroy text output-only windows, where the volume of output (updates) to some of these windows can be significant.

Are there any good ways of using alacritty to do this? Some ideas that I can't judge are:

- Call into (bits of) alacritty to create, emit text to, and destroy windows (but I don't know how or if calling into Rust from C++ is practical, here)
- Spawn (e.g. system() ) alacritty, with a command-line argument to get the alacritty instances to run some 'display daemon' that the C++ program can write to over pipe/shared memory
- Some kind of tmux magic (perhaps tmux has some kind of ANSI escape codes to allow clients to create 'windows')

Any pointers would be greatly appreciated!

**Comment by chrisduerr** [comment]
If your goal is to actually have a terminal, you should make your application generic so it could use any terminal.

If your goal is to just spawn random text windows, you don't need 99% of Alacritty and as such it would be far more efficient to just render the random text yourself.
