### ISSUE TITLE
Alacritty text colors are weird with transparency

### ISSUE THREAD

**Issue by MAZzzeen** [alacritty/alacritty#6546]
Colors look weird when using picom with blur and transparency

![alt text](https://i.imgur.com/g0emCwx.png)

It should look like kitty here

![alt text](https://i.imgur.com/90jxykt.png)
### System

OS: Linux
Version: alacritty 0.11.0 (8dbaa0bb)
Linux | picom | bspwm

### Logs

[alacritty-log.txt](https://github.com/alacritty/alacritty/files/10148091/alacritty-log.txt)

**Comment by kchibisov** [comment]
And what colors are weird exactly? If you want grayscale aliasing like in kitty setup it in fontconfig?

**Comment by MAZzzeen** [comment]
> 

I don't know exactly but there appears to be some kind of color separation or something (left side of text is blue and right is black)

**Comment by MAZzzeen** [comment]
> And what colors are weird exactly? If you want grayscale aliasing like in kitty setup it in fontconfig?

I don't know exactly but there appears to be some kind of color separation or something (left side of text is blue and right is black

**Comment by MAZzzeen** [comment]
Turns out sub-pixel antialiasing was causeing the issue

**Comment by kchibisov** [comment]
Yes, as I said. Kitty simply doesn't support it and only use gray scale.
