### ISSUE TITLE
I can not install alacritty on Ubuntu and LinuxMint

### ISSUE THREAD

**Issue by musicfunfan** [alacritty/alacritty#6547]
### System

OS: Ubuntu 22.04 and LinuxMint 21
Version: The version currently on cargo repo. 
DE:Gnome,Cinnamon

### Logs

```--- stderr
  CMake Deprecation Warning at CMakeLists.txt:78 (cmake_minimum_required):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.


  CMake Error at CMakeLists.txt:119 (project):
    The CMAKE_CXX_COMPILER:

      c++

    is not a full path and was not found in the PATH.

    Tell CMake where to find the compiler by setting either the environment
    variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
    to the compiler, or to the compiler name if it is in the PATH.


  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 1
```
They way i try to install it is via cargo command --> ``cargo install alacritty``

The problem is that cmake can not find the c++ compiler in the shell PATH. 
My problem is that i do not know how to add the compiler on the PATH. 

So how can fix this?

**Comment by chrisduerr** [comment]
You probably don't have `gcc` installed or something like that.

**Comment by SchoolyB** [comment]
For those who stumble across this and still have issues. Try following these steps

https://linux.how2shout.com/how-to-install-alacritty-terminal-on-ubuntu-22-04-lts/
