### ISSUE TITLE
Mouse cursor shape is always default

### ISSUE THREAD

**Issue by Nexion** [alacritty/alacritty#6548]
The mouse cursor is always default when it's held over an active alacritty window. Over other terminal emulators (kitty, st) mouse cursor takes a shape of a text cursor which is the expected behavior.

Found an old similar issue https://github.com/alacritty/alacritty/issues/1750.

### System

OS: Gentoo Linux
Version: 0.11.0
Linux/BSD: Wayland, sway version 1.9-dev-f54d22ca (Nov 29 2022, branch 'HEAD')

**Comment by kchibisov** [comment]
Configure your cursor theme. https://wiki.archlinux.org/title/Cursor_themes#Configuration
