### ISSUE TITLE
Transparency just makes background darker

### ISSUE THREAD

**Issue by terrenana** [alacritty/alacritty#6549]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: GNU/Linux Gentoo (not a VM)
Version: `alacritty 0.11.0`
Linux/BSD: X11 DWM, picom

### Logs
Alacritty shows a yellow bar at the bottom:
"Glutin could not find a fb config with an alpha mask. Transparency may be broken" 
[log.txt (created by alacritty -vvv)](https://github.com/alacritty/alacritty/files/10149424/log.txt)

Alacritty transparency doesn't work. All it does is make the background darker. I am using the picom compositor. I know the compositor works because my WM (dwm) has transparency and when I turn on picom, dwm becomes transparent correctly. Alacritty's config isn't broken, I tested it. Either this is a legit bug or I am missing some library alacritty needs to communicate and actually make the window transparent. I've seen some people have similar issues in VMs, but I am not in a VM.

**Comment by kchibisov** [comment]
Well, you clearly running on software rendering with llvmpipe you likely have broken driver installation, since you decided to remove as much flags as you can from mesa or don't set a gpu in a config.

The error clearly said that your system doesn't support alpha configs with alpha mask meaning no transparency for you. Ensure you're using GLX and not EGL as well.

**Comment by terrenana** [comment]
Closing the issue isn't helpful at all. I don't understand how it could be a driver issue if I have other transparent windows that work fine.

**Comment by terrenana** [comment]
Mesa is installed with all relevant USE flags and gpu is set to nouveau.

**Comment by kchibisov** [comment]
yet in the log you're using llvmpipe(software rendering) and not nouveau?

Other windows doesn't matter since we're restricted to what mesa tells us. In your case mesa tells us that there's no way to draw transparent window.

**Comment by terrenana** [comment]
I didn't set it to use LLVMpipe. My system is configured to use nouveau, alacritty seems to just not do that. Is there any way to change that?

**Comment by kchibisov** [comment]
Try `MESA_LOADER_DRIVER_OVERRIDE=nouveau alacritty`. I don't remember exactly how to force it. You might have more luck with debugging alacritty latest master, since it provides a bit more log wrt graphics.

But right now it seems like your driver installation is messed up. Maybe your xorg doesn't load it or its config is mallformed? Have you tried auto-generated(default) xorg config.

**Comment by terrenana** [comment]
I'm not sure how to autogenerate xorg config but I am re-emerging mesa with EXPLCIT llvm off, I'm not sure how that would be a problem, as it should default to nouveau and only fallback to llvm. Looking a Xorg logs nouveau is getting loaded correctly.

**Comment by terrenana** [comment]
Now the output of glxinfo -B is showing it using softpipe instead of LLVMpipe.

**Comment by kchibisov** [comment]
if glxinfo isn't using nouveau then alacritty won't use nouveau as well :p So something is tricky for sure with your drivers, maybe you don't have kernel driver?

**Comment by terrenana** [comment]
But nouveau is being loaded and used by X server, its just mesa that doesn't use it. I've reinstalled mesa multiple times with different flags, but it doesn't work. the MESA_LOAD_DRIVER_OVERRIDE would probably work but on the mesa docs it just says "its an environment variable" and I don't know how to set that while mesa is starting up.

**Comment by kchibisov** [comment]
You just run it before running a program? like `MESA_LOAD_DRIVER_OVERRIDE=nouveau glxinfo` or same for alacritty.

**Comment by terrenana** [comment]
That doesn't work. glxinfo still shows softpipe.

**Comment by terrenana** [comment]
running alacritty like this shows a warning `libEGL warning: DRI2: failed to authenticate`

**Comment by kchibisov** [comment]
Just be aware that EGL in general doesn't have transparency on X11, so you need to make alacritty use GLX.

**Comment by terrenana** [comment]
I made a post on the gentoo forums about it. I don't think its an alacritty issue, mesa just wont use nouveau for some reason.

**Comment by terrenana** [comment]
My kernel was loading nouveau before loading the rootfs, leading to nouveau not being able to load important firmware.
