### ISSUE TITLE
oh-my-posh prompt not rendered when using PowerShell 7

### ISSUE THREAD

**Issue by niilz** [alacritty/alacritty#6553]
### System

OS: Windows 10 Build 19044
Version: 0.11.0
PowerShell: 7.3.0
oh-my-posh: 12.25.0

When I was using the Windows 10 Default PowerShell (5.1) under Alacritty, [oh-my-posh](https://ohmyposh.dev/) prompt was rendered as expected.
But when I use [PowerShell 7](https://github.com/PowerShell/PowerShell), than the prompt does not show up anymore.
Config:
```
shell:
  program: /Program Files/PowerShell/7/pwsh.exe
```

What I expect to see:
![expected-alacritty](https://user-images.githubusercontent.com/38286937/205982340-31af844a-0888-4fb4-a4e8-e7b3e063a2ba.png)

What I actually see:
![actual-alacritty](https://user-images.githubusercontent.com/38286937/205983605-0b191299-ed38-495e-a9b9-1062c97bb77d.png)

What you can see is that the base-element renders after every command or when `Enter` is pressed.  
But the rest of the segments do not render.

(It's not about the missing UserName, I obfuscated those)

**Comment by chrisduerr** [comment]
Unrelated to Alacritty, the prompt is controlled by your shell not your terminal.

**Comment by niilz** [comment]
@chrisduerr you were absolutely right, it had nothing to do with Alacritty.  
I wasn't aware that the _oh-my-posh_ initialization (`oh-my-posh init pwsh | Invoke-Expression`) had to be called inside the PowerShell-7s own `$PROFILE` configuration file.  
Sourcing the one from PowersShell-5.1 was not sufficient.

Thanks for narrowing the issue surface.
