### ISSUE TITLE
Question (not bug) How to set key combos for ctrl+home/end/arrow keys to 'select' text with keys instead of mouse

### ISSUE THREAD

**Issue by willrabbermann** [alacritty/alacritty#6563]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux gentoo 5.15.80-gentoo
Version: alacritty 0.10.1 ()
X11 + DWM

### Logs

Current alacritty.yml key_bindings
```
key_bindings:
  - { key: PageUp,    mods: Shift,   mode: ~Alt,        action: ScrollPageUp,  }
  - { key: PageDown,  mods: Shift,   mode: ~Alt,        action: ScrollPageDown }
  - { key: Home,      mods: Shift,   mode: ~Alt,        action: ScrollToTop,   }
  - { key: End,       mods: Shift,   mode: ~Alt,        action: ScrollToBottom }
  - { key: V,         mods: Control,                    action: Paste          }
```

I can copy and paste text from the terminal easily, now I just need to be able to adjust the selection of text in the terminal with my keyboard. I see alot of Vi Mode bindings but Im not sure if this is what I need

#Hello world|
ctrl+home
#|Hello world| <- selection adjusted from cursor end to begin

#|Hello world
ctrl+end
#|Hello world| <- selection adjusted from cursor begin to end

**Comment by chrisduerr** [comment]
With vi mode this should already work by default pretty much? Not necessarily with those keybindings but other than that it should allow you to freely select any text you want.

Have you tried vi mode with its default bindings?

**Comment by willrabbermann** [comment]
Perfect sorry for the confusion! just press ```v``` for visual mode just like vim. 
Don't ask why I didnt figure that out lol
