### ISSUE TITLE
RFE: Font size list to use exclusively

### ISSUE THREAD

**Issue by oranki** [alacritty/alacritty#6564]
**Request for enhancement**: Allow specifying a list of font sizes in configuration, which would then be exclusively used when changing font size.

**Example config**:
```
font:
  size: 14.0  # default
  sizes: 12.0, 14.0, 22.0
```

A new terminal would open with font size 14, and decreasing font size *once* would yield size 12, from there increasing *twice* from there would yield 22.

**Reasoning**: I switch between a few font sizes on multiple systems quite often, for several reasons. Currently, there are several in-between sizes that are either undesirable, or flat out have no effect at all.

FWIW, ~same effect is also achievable already using external hotkey management, `alacritty msg config font.size=x` command and some creative scripting, so I understand if you feel this is unnecessary bloat.

**Comment by chrisduerr** [comment]
> FWIW, ~same effect is also achievable already using external hotkey management, `alacritty msg config font.size=x` command and some creative scripting, so I understand if you feel this is unnecessary bloat.

This basically sums up my stance on this issue.

**Comment by oranki** [comment]
I kind of figured as much. Fair enough, I respect the minimalist approach.

The codebase and design is very clean and when I took a look at kitty and alacritty, I was honestly not expecting much - never mind switching all my systems to alacritty after less than an hour. Very impressive.
