### ISSUE TITLE
Unable to open links on MacOS

### ISSUE THREAD

**Issue by Rawnly** [alacritty/alacritty#6565]
I'm unable to open links on macOS with <kbd>SHIFT</kbd>+ <kbd>left click</kbd>

![CleanShot 2022-12-13 at 22 44 42@2x](https://user-images.githubusercontent.com/16429579/207450390-e3dcdc88-b0ee-45c7-be62-fa6052e57b9c.png)

### System
OS: macOS 13.0
Version: `alacritty 0.11.0 (8dbaa0b)`

### Logs
```
[17767.242480250s] [WARN ] [alacritty] Unable to launch xdg-open with args ["https://vhs.charm.sh/vhs-32jFiaCmViLeXmxW8LXs4F.gif"]
[17791.886704750s] [WARN ] [alacritty] Unable to launch xdg-open with args ["https://vhs.charm.sh/vhs-32jFiaCmViLeXmxW8LXs4F.gif"]

```

**Comment by chrisduerr** [comment]
Can you try with `--config-file /dev/null`?

**Comment by Rawnly** [comment]
> Can you try with `--config-file /dev/null`?

Uh yeah sorry my mistake, I just copy-pasted my config file from the other PC 😅

**Comment by OJFord** [comment]
@chrisduerr is it expected that `hints.enabled.command` doesn't run with the same environment (e.g. `$PATH`) as the `shell` program configures?

I added a stub `xdg-open` on my macOS system (pointing at `open`) in order to have it work using the same config as I use on Linux, which is on my `PATH` in the shell when I open a new alacritty instance, but alacritty can't find it giving the error above.

**Comment by chrisduerr** [comment]
> @chrisduerr is it expected that hints.enabled.command doesn't run with the same environment (e.g. $PATH) as the shell program configures?

Of course. Alacritty is not a shell, it's the thing spawning the shell. So the environment is obviously going to be different.

**Comment by OJFord** [comment]
Of course, but it's not obvious it wouldn't use the specified shell to run the command. In fact typically when it's called a 'command' (vs "program') that is the case in my experience, just like it can be specified in alacritty as program & args.

**Comment by chrisduerr** [comment]
> Of course, but it's not obvious it wouldn't use the specified shell to run the command.

How is that not obvious? It can't run a shell that is currently doing something else. That's not how any of this works.

**Comment by Jackman3005** [comment]
Hi @chrisduerr,

This was also unfortunately not obvious to me either. Your reasoning makes sense, but you have deep context on the inner workings of Alacritty and terminal emulation. For us noobs the combination of the property name being "command" and the general context of Alacritty being the tool that gives us our access to the shell does not help with understanding what alternative there is. 

I'm struggling to get the "command" to work at all in my situation and I only just now found out it was not running in a shell environment when I found this issue.

It would be great if we had some more information on what environment these commands are run in. For starters:
1) What is the current working directory for the commands?
2) What environment variables are provided? Is it possible to influence these environment variables? etc.

For my use case I need to perform my own post-processing on the text captured by the hint regex and then split it into a filename, line number and column number to then call out to webstorm to open the file at that location.

For those curious, this is what I'm working with. Everything is "in progress" as I haven't gotten the chance to battle test it on many different outputs (tests/linters/builds, etc.)
```toml
regex = "[^ ]+\\.[j|t]sx?(:\\d+)?(:\\d+)?"
post_processing = true
command = { ... } # see below
mouse = { enabled = true }
```

I've written the following node script, but after trying quite a few different permutations of configuring command I am unable to get any to actually call my script. What do I need to do to call my script correctly?

```node
// File location: ~/open-webstorm-from-alacritty-hint
#!/usr/bin/env node
const fs = require('fs');
const {spawn, spawnSync} = require('node:child_process');
const {inspect} = require('node:util');

const log = (...msg) => fs.writeFileSync('/tmp/open-webstorm-from-alacritty-hint.log', `${new Date().toISOString()} ${
    msg.map((m) => typeof m === 'object' ? inspect(m, false, 5) : m).join(' ')
}\n`, {flag: 'a'});

const filename = process.argv[2];
if (!filename) {
    log('Must provide filename argument!');
    process.exit(1);
}
const match = filename.match(/\(?([^: ]+)(:\d+)?(:\d+)?/);

log(`Attempting to open ${filename}`, match);

let filePath = match[1];
const line = match[2]?.replace(':', '');
const column = match[3]?.replace(':', '');

if (!filePath) {
    log(`unable to extract filepath from ${filename}`);
    process.exit(1);
}

if (!fs.existsSync(filePath)) {
    // Often a partial relative path is printed. Search from the current directory down for a match of the filePath and use that path instead.
    const agResult = spawnSync('ag', ['-g', filePath], {timeout: 5000})
    const firstFilePathFound = agResult.stdout.toString().split('\n')[0]
    if (firstFilePathFound) {
        filePath = firstFilePathFound.trim();
    } else {
        log(`Unable to extend relative path to an existing file from: ${filename}`);
        process.exit(1);
    }
}


const webstormArgs = [
    ...(line ? [`--line`, line] : []),
    ...(column ? ['--column', column] : []),
    filePath,
];

log('Starting webstorm with args: ', webstormArgs);

spawn('webstorm', webstormArgs);


process.exit(0);
```

## A few of the things I've tried:
### 1
```
command = { program = "/Users/me/open-webstorm-from-alacritty-hint"] }
```
No error. Debug log reports that it launched it with the correct args. My script never writes anything to the tmp file.

### 2
```
command = { program = "node", args = ["/Users/me/open-webstorm-from-alacritty-hint"] }
```
Results in "Unable to launch node with args ..."

### 3
```
command = { program = "bash", args = ["-c", "/Users/me/open-webstorm-from-alacritty-hint"] }
```
No error. Debug log reports that it launched it with the correct args. My script never writes anything to the tmp file.

Note that all works well when I manually invoke my script like:
```bash
$ ~/open-webstorm-from-alacritty-hint "some/partial/relative/path.ts:5:6"
```

**Comment by OJFord** [comment]
> How is that not obvious? It can't run a shell that is currently doing something else. That's not how any of this works.

@chrisduerr I don't really understand this comment at all, since the only way I can read it is obviously incorrect - you can spawn two alacritty instances and each one will run the specified shell; you could even do that from an already running instance of it. But I know you know that so I'm just not sure what you meant?

@Jackman3005 your note 2 isn't really possible, alacritty doesn't have any concept of what directory you're in, that's within the shell program, it's 'just' rendering the text that results from that.
