### ISSUE TITLE
Alacritty fails on Virtualbox

### ISSUE THREAD

**Issue by oleongomez** [alacritty/alacritty#6566]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux Ubuntu 5.19.0-generic
Version: 0.12.0-dev (507f7277)
X11, i3 with picom
![image](https://user-images.githubusercontent.com/66493900/207476627-6909f98a-2fa9-43a5-b7fa-5cc88bf0bc7c.png)

After the latest update, alacrity stopped working with the attached message.

**Comment by kchibisov** [comment]
The mesa exactly tells you what is wrong though? Like we clearly don't control what you have inside the libGL and not call driver specific calls.

Or you can build the old version on the exact same system and it'll run fine?

**Comment by oleongomez** [comment]
it works on tag v0.11.0.
