### ISSUE TITLE
Double-click bracket-pair selection not working for multiple lines

### ISSUE THREAD

**Issue by freb** [alacritty/alacritty#6567]
A while back the pair bracket matching would search across multiple lines to find a match, but at some point this stopped working for me, though continues to work for matching brackets on the same line.

I've read through the [issue](https://github.com/alacritty/alacritty/issues/2014) and the [pull request](https://github.com/alacritty/alacritty/pull/2022) and did not see any reference to this part of the feature being removed. Also, as far as I can tell, there is no tuning of this option so there should be no ability to disable it with a configuration issue.

I installed previous versions of the package and found that this broke when upgrading from [0.7.2](https://github.com/alacritty/alacritty/releases/tag/v0.7.2) to [0.8.0](https://github.com/alacritty/alacritty/releases/tag/v0.8.0)

### System

OS: Linux
Version: alacritty 0.11.0 (8dbaa0bb)
Linux/BSD: Wayland

**Comment by chrisduerr** [comment]
Should be fixed with https://github.com/alacritty/alacritty/pull/6568, let me know if it works for you.

**Comment by freb** [comment]
That branch works for me! Thanks!
