### ISSUE TITLE
Alacritty hangs when started on 'large' external screen (on Arch) on latest kernels

### ISSUE THREAD

**Issue by MrHappy** [alacritty/alacritty#6569]
When I open alacritty (on latest Arch-kernels) on my external screen it hangs. Starting it with -vvvvv does not give any clues to why it hangs. When I open alacritty on my laptopscreen it also opens fine.
When I do the same on the most recents lts-kernels it opens fine (on both external as laptopscreen).

### System

OS: Linux Arch
Version: alacritty 0.11.0 (8dbaa0bb)
Linux/BSD: X11, AwesomeWM

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size:  Width: 2536, Height: 1384, Font size changed to Size(15) with scale factor of 1.25
Keyboard and bindings: `alacritty --print-events`

Where do I start to look for the cause? :/

**Comment by kchibisov** [comment]
Why do you think it's alacritty issue? If changing kernel version fixes it then it's a kernel bug? Your driver/compositor is likely at fault here.

**Comment by MrHappy** [comment]
Cause the only 2 things that differ are alacritty and kernel.
And like I said, ook laptop screen it works, external not. On lts it works on both screens.
I was not saying it IS an alacritty issue, but I am asking what/how can I check in alacritty (or where) what causes this...

**Comment by MrHappy** [comment]
How can I determine that?

**Comment by kchibisov** [comment]
Do you have multiple GPUs? So the external monitor is hooked to nvidia or something like that?
