### ISSUE TITLE
Activate window buttons on mouse button release not by mouse button press

### ISSUE THREAD

**Issue by darkblaze69** [alacritty/alacritty#6570]
### System

OS: Linux
Version: 0.11.0
DE: Manjaro GNOME / Wayland

I have problems with inconsistency in behavior compared to other programs. 
When I want to minimize, maximize or close alacritty window with window buttons, it is all activated only by pressing with the mouse button. But all other programs' behavior is so that you should press & release mouse button to activate those window buttons.
Current behavior looks strange compared to all programs that we are accustomed to.

**Comment by chrisduerr** [comment]
Working as intended.

**Comment by kchibisov** [comment]
I think it's resolved on master actually.

**Comment by darkblaze69** [comment]
Thanks, compiled from master, it works nice!
