### ISSUE TITLE
Alacritty master fails to start on Virtualbox:  I added 2 environment variables to pass this error:

### ISSUE THREAD

**Issue by oleongomez** [alacritty/alacritty#6571]
I added 2 environment variables to pass this error:
LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
LIBGL_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri
Now I get this error:
![image](https://user-images.githubusercontent.com/66493900/207929757-97e6d00f-480b-4318-a359-69e43feb4b2b.png)
And with full backtrace:
![image](https://user-images.githubusercontent.com/66493900/207930074-fb53ec62-4923-4ef1-bb15-adfc56a4c9d2.png)

_Originally posted by @oleongomez in https://github.com/alacritty/alacritty/issues/6566#issuecomment-1353469148_

**Comment by kchibisov** [comment]
Could you post the X11 trace(it's usually called x11trace or xtrace) log? https://tracker.debian.org/pkg/xtrace. It's usually available in most distros, but its name varies.

I have a feeling that some error got stuck and everything is ok.

We can continue with the https://github.com/rust-windowing/glutin/ example. Could you try running `cargo run --example window` after cloning the repository. Just do a debug build.

**Comment by kchibisov** [comment]
Also, could you post the `glxinfo` output with your variables set

`LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu LIBGL_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri glxconfig`

It sounds strange that you need such a thing though. If you're using the system linker(which you likely should, unless you're using something like `nix`) it should find the libs just fine.

**Comment by oleongomez** [comment]
What I ended up doing was to purge the kisak/kisak-mesa. After that, it started running again

**Comment by kchibisov** [comment]
¯\_(ツ)_/¯
