### ISSUE TITLE
macOS: support dynamic theme switching

### ISSUE THREAD

**Issue by inodentry** [alacritty/alacritty#6578]
The vast majority of macOS applications are able to dynamically respond to the system theme changing between "light mode" and "dark mode". macOS also has an "Auto" option, which makes the OS use light mode during daytime and dark mode during night time.

I am an avid user of this OS feature. I like the Auto setting, because I like everything to have a light theme during the day and a dark theme during the night. I also manually switch the system-wide theme to dark, when I am screensharing or livestreaming, for the benefit of viewers.

Currently, to my knowledge, Alacritty does not support having a config file that contains colors/settings for both "light mode" and "dark mode" and switching between them automatically whenever the system-wide theme setting is changed.

I can work around it by having two additional config files, one for light and one for dark, and copying them over the main alacritty config file whenever I want to change the theme, making use of the "config auto-reload" feature of alacritty.

However, this is very annoying. I change between light and dark themes often, and all other applications are able to respond automatically and seamlessly, without me having to do anything.

**Comment by chrisduerr** [comment]
First needs https://github.com/alacritty/alacritty/issues/6558 to be fixed. Once that's resolved we can consider switching things automatically.

**Comment by chrisduerr** [comment]
Though if your goal is to change more than just the decorations, that's out of scope. You can easily script that with an external application though.

**Comment by 0rphee** [comment]
> Though if your goal is to change more than just the decorations, that's out of scope. You can easily script that with an external application though.

Now that #6558 is fixed, at least for me, I agree that it would be great to have support for dynamic theme switching. As @inodentry said, it is very convenient just to switch the system theme, and most of the applications will follow. For alacritty it would be great for the user to specify what would be the color scheme for the dark/light system themes.

If that does'nt fall under this project's scope, is understandable. Thank you anyways :)

**Comment by kchibisov** [comment]
If you change the value of the mentioned option, it'll live-reload. The same changing should work via `alacritty msg config`.

**Comment by RobertBrunhage** [comment]
I don't fully understand where this ended up, was the conclusion that each user has to handle the switching themselves while using `live_config_reload`?

**Comment by kchibisov** [comment]
Right, if you want to change color set you'd need a script to update the alacritty. The titlebar should be updated automatically though, if you use `None` for the theme variant.

We might add a way to subscribe for such events, so you can sort of reconfigure the instance.

**Comment by esan0** [comment]
FYI anyone looking for hints on how to script the theme switch, here's an example.

```sh
#!/bin/bash
CONFIG_PATH=~/.config/alacritty/alacritty.yml
TIMEOUT=3000
notify () {
    notify-send -t ${TIMEOUT} -a alacritty-theme-toggle  'Switched alacritty theme:' $1
}
grep -q solarized_light $CONFIG_PATH &&
    sed -i "s/solarized_light/solarized_dark/" $CONFIG_PATH &&
    notify "dark" &&
    exit
grep -q solarized_dark $CONFIG_PATH &&
    sed -i "s/solarized_dark/solarized_light/" $CONFIG_PATH &&
    notify "light"
```

* Save this to a file (like toggle_theme.sh)
* Make it executable (chmod u+x toggle_theme.sh)
* Put it somewhere in your PATH (for example ~/bin)
* Bind it to a key (I use F6) and away you go.

If you don't want a notification, remove all the notify-related lines and function definition.

**Comment by pek0d** [comment]
> FYI anyone looking for hints on how to script the theme switch, here's an example.
> 
> ```shell
> #!/bin/bash
> CONFIG_PATH=~/.config/alacritty/alacritty.yml
> TIMEOUT=3000
> notify () {
>     notify-send -t ${TIMEOUT} -a alacritty-theme-toggle  'Switched alacritty theme:' $1
> }
> grep -q solarized_light $CONFIG_PATH &&
>     sed -i "s/solarized_light/solarized_dark/" $CONFIG_PATH &&
>     notify "dark" &&
>     exit
> grep -q solarized_dark $CONFIG_PATH &&
>     sed -i "s/solarized_dark/solarized_light/" $CONFIG_PATH &&
>     notify "light"
> ```
> 
>  * Save this to a file (like toggle_theme.sh)
> * Make it executable (chmod u+x toggle_theme.sh)
> * Put it somewhere in your PATH (for example ~/bin)
> * Bind it to a key (I use F6) and away you go.
> 
> If you don't want a notification, remove all the notify-related lines and function definition.

Hello!
Does it work on macOS 14 ?

**Comment by esan0** [comment]
> 
> Hello! Does it work on macOS 14 ?

Yes!

Here's a write-up:
https://integer0.users.sourceforge.net/alacritty-switch_colorscheme.html

**Comment by leaxoy** [comment]
Will there be any progress on this? Because I don't like to execute a separate script when the system theme changes. It's too troublesome.

**Comment by xqm32** [comment]
> Will there be any progress on this? Because I don't like to execute a separate script when the system theme changes. It's too troublesome.

I wrote a gist to switch theme when Alacritty starts. Maybe this can help you https://gist.github.com/xqm32/17777d035930d622d0ff7530bfab61fd.

**Comment by kkristof200** [comment]
Hi, I've also created a gist where i put some scripts to auto switch alacritty theme on os theme changes: [gist](https://gist.github.com/kkristof200/cb440c5d0e0b14d81a1134f406905001)

**Comment by Mathias-Fuchs** [comment]
Any news on this?

**Comment by christiangenco** [comment]
None of the scripts here worked for me so I made [a system that runs a script whenever the system theme changes](https://gist.github.com/christiangenco/042f26297ce2650d4c5b3ea4d3f6c7ac), then [a script that updates alacritty specifically](https://gist.github.com/christiangenco/042f26297ce2650d4c5b3ea4d3f6c7ac#file-alacritty-theme-switcher-sh).

The only theme updater that responded immediately to the theme update event and didn't use long polling was this weird bit of swift:

```swift
DistributedNotificationCenter.default.addObserver(
    forName: NSNotification.Name("AppleInterfaceThemeChangedNotification"),
    object: nil,
    queue: nil
) { _ in
    Process.launchedProcess(launchPath: "/bin/bash", arguments: [scriptPath])
}
```

**Comment by jokeyrhyme** [comment]
this issue was marked closed, but I wonder if maybe it should be reopened or linked to where auto light/dark (via OSC 997 ?) is tracked?

**Comment by leaxoy** [comment]
I've switched to Ghostty. 😂
