### ISSUE TITLE
Misson Control lag

### ISSUE THREAD

**Issue by ruadoVn** [alacritty/alacritty#6581]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: MacOS
Version: alacritty 0.11.0 (8dbaa0b)

### Logs
When I use Mission Control with Alacritty activing, the animation is pretty slow and lag. How can I fix it?
I tried to change the opacity to 0.999 but nothing change.

**Comment by chrisduerr** [comment]
Duplicate of #4474.
