### ISSUE TITLE
can you change fontsize for certain glyphs?

### ISSUE THREAD

**Issue by Ethanol48** [alacritty/alacritty#6582]
Is it possible to change in the yml file change the fontsize for specific characters, I want certain size in my terminal and I use icons, but the icons are a little small, I don't won't to change the global font, is there a way to do it?

**Comment by chrisduerr** [comment]
You cannot.

**Comment by Ethanol48** [comment]
I finally did it.

if anyone wanted to know how to do it, I used the application fontforge to manually scale the icon and created a new font. You can find the information in the repo of nerdfonts, in the end in patching your font. If anyone wanted to know how to do it don't hesitate to ask
