### ISSUE TITLE
ANSI art is not displayed well as some glyphs are being replaced

### ISSUE THREAD

**Issue by poetaman** [alacritty/alacritty#6583]
Some glyphs used in ANSI art are being replaced by Alacritty. This could be because of this [vte bug](https://gitlab.gnome.org/GNOME/vte/-/issues/205), but I am not sure. A string search for ``vte`` does return hits in Alacritty's GitHub repository, though I don't know if it is related.

### To Reproduce

Download [arttime](https://github.com/poetaman/arttime), and run:

If you install arttime*, it's a single command [installer](https://github.com/poetaman/arttime#installation):
```
arttime --nolearn -a picard -t '"Stop replacing glyphs" - Capt. Picard'
```

Or from arttime directory:
```
./bin/arttime --nolearn -a picard -t '"Stop replacing glyphs" - Capt. Picard'
```

\*Note: arttime does not dial the internet, it's perfectly respecting of your privacy.

### Expected Behavior

Don't replace glyphs, or provide a config option to disable this feature/bug. Perhaps bypass vte if it is the source, as the [vte bug](https://gitlab.gnome.org/GNOME/vte/-/issues/205) seems closed.

### Screenshots

In iTerm2 (looks correct):
<img width="899" alt="picard_iterm2" src="https://user-images.githubusercontent.com/71736629/209414994-dcb357f4-84f1-475f-8c72-9335fafe5fe5.png">

In Alacritty (same glyphs are affected as in screenshot at [vte bug](https://gitlab.gnome.org/GNOME/vte/-/issues/205)):
<img width="899" alt="picard_alacritty" src="https://user-images.githubusercontent.com/71736629/209415507-d2b5c82b-e66c-4746-8d3d-4d3aa201a584.png">

### System

OS: macOS
Version: `alacritty 0.12.0-dev (2291610f)`
Linux/BSD: n/a

**Comment by j4james** [comment]
If you want Alacritty to use the shaded glyphs from the font rather than rendering them itself, you need to set the `font.builtin_box_drawing` option to false. See here:

https://github.com/alacritty/alacritty/blob/df32b5216b59a087e8c2fe621e56cd65346205fa/alacritty.yml#L177-L182

And with some ansi art it may be necessary to set the `draw_bold_text_with_bright_colors` option to true if you want the colors to look right. Tweaking the color scheme would probably help too.

**Comment by poetaman** [comment]
@j4james Ok great, worked well, thanks! Here's how it looks like now:

<img width="899" alt="Screenshot 2022-12-23 at 9 15 28 PM" src="https://user-images.githubusercontent.com/71736629/209422580-ac04c107-d119-4e10-8772-4dbca7894652.png">
