### ISSUE TITLE
Can't access previous lines in multi-line prompt

### ISSUE THREAD

**Issue by amab8901** [alacritty/alacritty#6587]
Feature Request:

Let's suppose I'm writing the following prompt
```
$ curl fskfjnajsfnajskf \
> fsakfkasjansfkj \
>  fnaksfkasfnajsf \
> 
```
Now, if I want to go back and edit previous lines in the prompt, I can't do that. This is annoying and is one of the reasons why I use `qterminal` instead of `alacritty`. However, I like the fact that Alacritty uses Rust (which `qterminal` doesn't). So I'd like to contribute to `Alacritty` by adding the important features that are missing in Alacritty but which Qterminal does have, so that I may one day hopefully start using Alacritty instead of having to use Qterminal.

This is the feature I'd like to start with. What are your thoughts on this? Would you approve PR on this? Any tips on how I can get started?

**Comment by chrisduerr** [comment]
That's a shell feature which should have absolutely nothing to do with Alacritty.

**Comment by amab8901** [comment]
> That's a shell feature which should have absolutely nothing to do with Alacritty.

how can I solve this shell issue then? Any tips?
