### ISSUE TITLE
Alacritty on Mac: Double click to open the alacritty does not work

### ISSUE THREAD

**Issue by blitzerr** [alacritty/alacritty#6588]
I installed the alacritty from the link [here](https://alacritty.org/), and copied the app into the `/Applications`. But when I double click the app, it does not open Alacritty. I am able to open it from command line. Is this expected behavior ? This means that I have to open a  terminal just to get to alacritty. How did you all solve this ?

**Comment by blitzerr** [comment]
Also please let me know how can I ask such basic questions ? Opening an issue does not seem to be the right way, but then discussions is not enabled for this repo.

**Comment by chrisduerr** [comment]
Opening an issue is perfectly fine, but #alacritty on Libera's IRC (see readme) would probably give you a better chance at fast interactive feedback.

It sounds to me like you're getting hassled by macOS' security constraints. With unsigned applications you have to go into finder and right-click -> open the first time you launch an application iirc.

**Comment by blitzerr** [comment]
Thanks a lot @chrisduerr for the response. I did the option + click the fist time I tried to open the Alacritty app and I got the `open anyways` dialogue as I usually get. Now when I click the alacritty app, I do not get the dialogue anymore, the screen flickers like it is opening something but then nothing opens.

Usually if the apple xattr setting for an app is the problem, one get the same pop up if they open it using the terminal. In my case, opening Alacritty from the terminal works just fine, its just that I have to use `iterm` to open alacritty :)

**Comment by chrisduerr** [comment]
Can you enable persistent logging in Alacritty's config and see if that creates a log file in your tempdir when trying to open Alacritty? If so, I'd love to know it's content. Also turning the logging to maximum would probably be useful while you're at it.

**Comment by blitzerr** [comment]
Thanks a lot @chrisduerr . This issue got fixed. Here is what 

```
shell:
  program: /bin/zsh
  args:
    - -l
    - -c
   - zellij attach --index 0 || zellij
```

and Alacritty does not like these options when I start it by double clicking the application icon. Once I changed the above to

```
  program: /bin/zsh
  args:
    - -l
```

It worked just fine, i.e. I was able to open Alacritty by clicking the app icon on OSX.

So, I am unsure if it was Alacritty that did not like it or zellij did not like it the way it invoked.

**Comment by blitzerr** [comment]
I tried to enable Alacritty logging by turning these settings on

```
...

persistent_logging: true

# Log level
#
# Values for `log_level`:
#   - None
#   - Error
#   - Warn
#   - Info
#   - Debug
#   - Trace
log_level: Trace

# Print all received window events.
print_events: true
```

and then restart Alacritty and the only file I see in the tmpdir is `Alacritty-1953.sock`.

**Comment by blitzerr** [comment]
@chrisduerr Thank you so much for working with me here and directing me. I appreciate your help.

**Comment by chrisduerr** [comment]
Just for the future, these options are all in a `debug` section (as shown in the example config), so just slapping them in the root of the file will not work.

**Comment by blitzerr** [comment]
Thanks a lot for that pointer. I see my mistake now :)
