### ISSUE TITLE
alacritty keymap shortcut

### ISSUE THREAD

**Issue by blitzerr** [alacritty/alacritty#6591]
Is there a way in alacritty to display all the keybindings and shortcuts in the current version ? 
A pointer to the code file where I can check will also help.

**Comment by chrisduerr** [comment]
It's in the `alacritty.yml` file for your version (see GitHub releases).

For the latest master, these are it:
https://github.com/alacritty/alacritty/blob/master/alacritty.yml#L761-L871

There's technically some more keybindings, but those are just ensuring that keys send the right escape sequences to be recognized by the shell running inside of Alacritty. So probably not what you were thinking of when talking about keybindings.

**Comment by blitzerr** [comment]
Thanks a lot @chrisduerr
