### ISSUE TITLE
Daemon mode

### ISSUE THREAD

**Issue by andreykaere** [alacritty/alacritty#6593]
Is there any hope for daemon mode support? I know about PCI, but it's not quite the same. For example, whenever I run `alacritty msg create-window`, this process closes automatically and I can't handle the even of terminal window being closed, which is essential in some situations. Or would you mind, please, adding some kind of flag to the `alacritty msg` to emulate this feature. I would help me a lot.

**Comment by chrisduerr** [comment]
What do you mean by "handle the even of terminal window being closed" and what does it have to do with "daemon mode"?

**Comment by andreykaere** [comment]
I mean, that when I run `alacritty msg create-window`, this process exit immediately, not waiting for the new opened alacritty window to be closed (as it behaves with launching `alacritty`)

It's related to "daemon mode", because I basically use `alacritty msg create-window` as a replacement for daemon mode. And with daemon mode I expect to have the described above behavior (as it is implemented, for example, in urxvt)

**Comment by chrisduerr** [comment]
Why would the process for a deamon child keep running? That makes no sense and isn't what urxvtc does either iirc?

**Comment by andreykaere** [comment]
Well, I use daemon mode for starting terminal faster, than in normal mode. And I need to track the event of terminal window being closed. How can I do it?

**Comment by chrisduerr** [comment]
> And I need to track the event of terminal window being closed.

Why?

**Comment by andreykaere** [comment]
Because my application waits for that event

**Comment by chrisduerr** [comment]
What application is that?

**Comment by andreykaere** [comment]
Why does it even matter? I know that I can work around this. This issue is not about why I want to use it, but rather if that could be implemented in alacritty or not.

**Comment by chrisduerr** [comment]
I won't implement something that doesn't have a good reason to exist.

**Comment by andreykaere** [comment]
I think I gave you good enough reason: to have the same effect as running "alacritty", because it makes sense to me ...

**Comment by Arseniusz** [comment]
I just thought about same feature, but even without daemon mode you can implement behaviour you need. You can use `pidof alacritty` shell command to check if any alacritty terminal is running.

Here is example of bash script:
```bash
#!/bin/bash

if [[ $(pidof alacritty) ]]
then
    alacritty msg create-window -e $1
else
    alacritty -e $1
fi

```

You can also check if there is no `$1` just open alacritty itself.
Also you can add alias and keybindings to run this script.

Hope it can solve your problem.

**Comment by kchibisov** [comment]
`alacritty msg create-window $@ || exec alacritty $@` should be more then enough.
