### ISSUE TITLE
alacritty not letting me run screen on NetBSD server

### ISSUE THREAD

**Issue by jahway603** [alacritty/alacritty#6597]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen instead.

### System

Desktop OS running alacritty: Linux
Version: alacritty 0.11.0 (8dbaa0bb)
Linux/BSD: Wayland, Sway

### Logs

Server I'm connecting to using Alacritty on Linux is a NetBSD 9.3 server.
* I get the following after login.
* I'm able to run htop fine.
* I'm not able to run GNU screen on the server.

```
Welcome to NetBSD!

No entry for terminal type "alacritty";
using dumb terminal settings.
$ htop
$ screen
Cannot find terminfo entry for 'alacritty'.
```

I don't know why I cannot run screen on the remote server using the alacritty terminal on my desktop.

As a comparison, I am able to run both screen and htop using the traditional `xterm` terminal.

**Comment by kchibisov** [comment]
It clearly says that it can't find the terminfo entry. You either ssh with the `TERM=xterm-256color` or whatever is present on NetBSD, or you install alacritty terminfo on your NetBSD machine. The terminfo is shipped with ncurses.
