### ISSUE TITLE
Evaluate PGO applicability

### ISSUE THREAD

**Issue by zamazan4ik** [alacritty/alacritty#6598]
Hi!

Since Alacritty wants to be the fastest terminal, we should evaluate the applicability of PGO (possibly with LLVM BOLT) option. E.g. another terminal, [foot](https://codeberg.org/dnkl/foot), has built-in support for PGO in their build [scripts](https://codeberg.org/dnkl/foot/src/branch/master/pgo).

**Comment by chrisduerr** [comment]
Has already been done multiple times. There are no measurable differences.

If you want to investigate yourself, feel free.

**Comment by zamazan4ik** [comment]
@chrisduerr could you please share with me the results of PGO optimizations for Alacritty from the previous runs? I've tried to find them in the issue tracker but with no success.

Thanks in advance!

**Comment by chrisduerr** [comment]
They haven't been documented anywhere. If you're curious feel free to test it yourself, it's absolutely trivial with Rust.
