### ISSUE TITLE
Wayland/Sway terminal stops being redrawn while running termdown

### ISSUE THREAD

**Issue by Yutsuten** [alacritty/alacritty#6603]
### System

OS: Arch Linux x86_64
Version: alacritty 0.11.0 (8dbaa0bb)
Wayland, Sway 1.7

### Details

This issue started recently, and as Sway version haven't changed [since January 2022](https://github.com/swaywm/sway/releases/tag/1.7), I believe the issue is with recent updates of Alacritty.

[Termdown](https://github.com/trehn/termdown/tree/master) is a countdown program, and recently I noticed that most of the time the screen stops being updated until I make any input (mouse movement or keyboard press). If I make the input, the terminal will update for a few seconds (or minutes if lucky) and stop again.

I debugged with `alacritty -o debug.highlight_damage=true` and recorded a video with the issue happening.

1. Run `termdown -B 2m && notify-send 'Finish'`
2. The terminal stopped being updated at 1m 58s.
3. After 2 minutes the notification is shown, but Alacritty screen is still stopped
4. I move my mouse cursor and Alacritty updates the screen

[alacritty_update_bug.webm](https://user-images.githubusercontent.com/7322925/210405852-f4a3b4da-87e4-481e-bf50-bc80bebc52ce.webm)

**Comment by kchibisov** [comment]
Does it work with XWayland?

**Comment by Yutsuten** [comment]
Yes, it does work normally with XWayland.

**Comment by Yutsuten** [comment]
It didn't work with version 0.10.0... With this we can conclude that the problem is not in Alacritty?

**Comment by kchibisov** [comment]
Could you provide the log from `WAYLAND_DEBUG=1 alacritty --print-events` at the moment of freezing?

Also, are you using open source drivers, if so which ones. Also does it happen with other applications or just this specific one?

**Comment by Yutsuten** [comment]
> Could you provide the log from `WAYLAND_DEBUG=1 alacritty --print-events` at the moment of freezing?

I opened alacritty with `WAYLAND_DEBUG=1 alacritty --print-events &> alacritty_bug.log` and ran  `termdown -B 3m && notify-send 'Finish'`. Timer started at `3m`, and at `2m 54s` it froze. At the end I just typed `exit` and enter.

The log is big, here it is: [alacritty_bug.log](https://github.com/alacritty/alacritty/files/10343666/alacritty_bug.log)

> Also, are you using open source drivers, if so which ones.

The drivers I'm using (searched the keyword `driver` with `pacman`):

```
> pacman -Qs driver
local/dotnet-host 7.0.1.sdk101-1
    A generic driver for the .NET Core Command Line Interface
local/hdparm 9.65-1
    A shell utility for manipulating Linux IDE drive/driver parameters
local/lib32-mesa 22.3.1-2
    An open-source implementation of the OpenGL specification (32-bit)
local/lib32-vulkan-icd-loader 1.3.235-1
    Vulkan Installable Client Driver (ICD) Loader (32-bit)
local/lib32-vulkan-radeon 22.3.1-2
    Radeon's Vulkan mesa driver (32-bit)
local/libraw1394 2.1.2-3
    Provides an API to the Linux IEEE1394 (FireWire) driver
local/libva-mesa-driver 22.3.1-2
    VA-API drivers
local/mesa 22.3.1-2
    An open-source implementation of the OpenGL specification
local/mesa-vdpau 22.3.1-2
    VDPAU drivers
local/ntfs-3g 2022.10.3-1
    NTFS filesystem driver and utilities
local/vulkan-icd-loader 1.3.235-1
    Vulkan Installable Client Driver (ICD) Loader
local/vulkan-radeon 22.3.1-2
    Radeon's Vulkan mesa driver
```

> Also does it happen with other applications or just this specific one?

As far as I know, only Alacritty have this issue.

**Comment by Yutsuten** [comment]
> Could you provide the log from `WAYLAND_DEBUG=1 alacritty --print-events` at the moment of freezing?

I opened alacritty with `WAYLAND_DEBUG=1 alacritty --print-events &> alacritty_bug.log` and ran  `termdown -B 3m && notify-send 'Finish'`. Timer started at `3m`, and at `2m 54s` it froze. At the end I just typed `exit` and enter.

The log is big, here it is: [alacritty_bug.log](https://github.com/alacritty/alacritty/files/10343666/alacritty_bug.log)

> Also, are you using open source drivers, if so which ones.

The drivers I'm using (searched the keyword `driver` with `pacman`):

```
> pacman -Qs driver
local/dotnet-host 7.0.1.sdk101-1
    A generic driver for the .NET Core Command Line Interface
local/hdparm 9.65-1
    A shell utility for manipulating Linux IDE drive/driver parameters
local/lib32-mesa 22.3.1-2
    An open-source implementation of the OpenGL specification (32-bit)
local/lib32-vulkan-icd-loader 1.3.235-1
    Vulkan Installable Client Driver (ICD) Loader (32-bit)
local/lib32-vulkan-radeon 22.3.1-2
    Radeon's Vulkan mesa driver (32-bit)
local/libraw1394 2.1.2-3
    Provides an API to the Linux IEEE1394 (FireWire) driver
local/libva-mesa-driver 22.3.1-2
    VA-API drivers
local/mesa 22.3.1-2
    An open-source implementation of the OpenGL specification
local/mesa-vdpau 22.3.1-2
    VDPAU drivers
local/ntfs-3g 2022.10.3-1
    NTFS filesystem driver and utilities
local/vulkan-icd-loader 1.3.235-1
    Vulkan Installable Client Driver (ICD) Loader
local/vulkan-radeon 22.3.1-2
    Radeon's Vulkan mesa driver
```

> Also does it happen with other applications or just this specific one?

As far as I know, only Alacritty have this issue.

**Comment by Yutsuten** [comment]
Oh I see there is a log file that is created in `/tmp` but is deleted when I close the terminal. I don't know if both are needed, but just to be sure I'll upload both.

I repeated the test with the same command, it stopped at the same time `2m 54s`.

Output of `WAYLAND_DEBUG=1 alacritty --print-events`: [alacritty_bug.log](https://github.com/alacritty/alacritty/files/10343729/alacritty_bug.log)
Log file in `/tmp`: [Alacritty-95304.log](https://github.com/alacritty/alacritty/files/10343731/Alacritty-95304.log)

**Comment by kchibisov** [comment]
>Also does it happen with other applications or just this specific one?

I mean terminal application. You may want to post `-vvv` since those logs just show that your program stopped writing. Every frame and such were committed correctly.

Maybe the app is using sync output in a weird way...

**Comment by Yutsuten** [comment]
> I mean terminal application.

Oh I see... Just `termdown` is giving me this issue.

> You may want to post `-vvv` since those logs just show that your program stopped writing. Every frame and such were committed correctly.

Here's the output of `WAYLAND_DEBUG=1 alacritty --print-events -vvv &> alacritty_bug_vvv.log`

[alacritty_bug_vvv.log](https://github.com/alacritty/alacritty/files/10344010/alacritty_bug_vvv.log)

**Comment by Yutsuten** [comment]
Probably related, but I updated [anki](https://github.com/ankitects/anki) (it uses Qt) from 2.1.54 to 2.1.56, and I'm having the very same issue with my [own addon](https://ankiweb.net/shared/info/715575551)...
My addon has a timer and is triggered every 100ms, but *on wayland* it stops being triggered at all after a few seconds. The countdown literally stops without user input.

I'm starting to think that this is a wayland/sway issue, not Alacritty's.

**Comment by Yutsuten** [comment]
The issue was fixed after a system update, still unsure what was the root of the issue, but as it does not happen anymore I'll close this.
