### ISSUE TITLE
 Cannot override shell.args config option from command line.

### ISSUE THREAD

**Issue by marrs** [alacritty/alacritty#6605]
I'm trying to launch a shell with some custom aliases already sourced.  I'm doing this by adding a custom `.bashrc` to my working directory with the necessary config in place and then attempting to run bash against that config using its `--rcfile` option.

I have confirmed this strategy to work by running `bash --rcfile .bashrc` from my working directory.

Unfortunately, I can't work out how to get Alacritty to launch this shell.  I'm trying to override Alacritty's `shell.args` config property using the `-o` flag.

My alacritty command looks like the following:

`alacritty --working-directory $my_working_dir -o "shell.program=/bin/bash" -o "shell.args[0]=--rcfile $my_working_dir/.bashrc"`

The 2nd option is ignored and is falgged as invalid.  I've tried variations such as `shell.args.0` or `shell.args= - --rcfile...` but none of them works.

Any help would be much appreciated.

**Comment by chrisduerr** [comment]
Just use the `-e` shorthand. While it would be possible to use `-o`, there's no point in trying to figure that out when we have a built-in shortcut for this option.

**Comment by chrisduerr** [comment]
Note in general the value assigned to `-o` (so behind the `=`) is yaml. Since JSON is valid yaml you can use JSON there.
So `-o "shell={'program':'/bin/bash',args:['--rcfile', './.bashrc']}"` might work.

**Comment by marrs** [comment]
Thanks.  `--comand` was the first thing I tried but it didn't work first time around.  I think it's because I was quoting the command to be run.

In any case, I've got a working launcher now.  The final script is something like the following:

```
#!/bin/sh
working_dir="$HOME/working/dir"
alacritty --working-directory $working_dir --command /bin/bash --rcfile $working_dir/.bashrc
```
