### ISSUE TITLE
Alacritty crashes randomly

### ISSUE THREAD

**Issue by IgnisDa** [alacritty/alacritty#6611]
It seems to me that the crash occurs mostly when I am typing very fast, but it is sparingly reproducible. When I googled this problem, I came across [this](https://github.com/swaywm/sway/issues/4435) issue and tried to run `env WAYLAND_DEBUG=client alacritty` and was able to reproduce it. Here are the logs:

[alacritty.txt](https://github.com/alacritty/alacritty/files/10381503/alacritty.txt)

I can provide more information if needed.

### System

`uname -ar`:
```
Linux arch-linux 6.1.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 07 Jan 2023 15:10:07 +0000 x86_64 GNU/Linux
```

WM: I am using Hyprland with an Nvidia RTX 3070.

**Comment by kchibisov** [comment]
This is fixed on the recent master.

**Comment by IgnisDa** [comment]
@kchibisov Which release was the fix present in? I am using https://archlinux.org/packages/community/x86_64/alacritty/.

**Comment by kchibisov** [comment]
>This is fixed on the recent master.

So no release for it yet.

**Comment by kchibisov** [comment]
>This is fixed on the recent master.

So no release for it yet.
