### ISSUE TITLE
macOS: Corrupt cache causes startup failure

### ISSUE THREAD

**Issue by ItzSwirlz** [alacritty/alacritty#6616]
Me and other maintainers found out that sometimes a corrupt cache in the $TMPDIR in macOS (somehow) results in a failure for Alacritty to startup.

### System

OS: macOS (So far, only reproduced on M1/ARM devices)
Version: Happened on both Homebrew/Cargo, 0.11.0

### Logs

Crash:

```rust
Error occurred in server:

  × Thread 'wasm' panicked.
  ├─▶ Originating Thread(s)
  │       1. ipc_server: NewClient
  │       2. screen_thread: NewTab
  │       3. plugin_thread: NewTab
  │
  ├─▶ At /Users/jpeisach/.cargo/registry/src/github.com-1ecc6299db9ec823/zellij-server-0.34.4/src/plugins/wasm_bridge.rs:717:5
  ╰─▶
A panic occured in a plugin
PanicInfo {
    payload: Any { .. },
    message: Some(
        called `Result::unwrap()` on an `Err` value: Serde(Error("trailing characters", line: 1, column: 244)),
    ),
    location: Location {
        file: "default-plugins/status-bar/src/tip/utils.rs",
        line: 40,
        col: 83,
    },
    can_unwind: true,
}

  help: If you are seeing this message, it means that something went wrong.
        Please report this error to the github issue.
        (https://github.com/zellij-org/zellij/issues)

        Also, if you want to see the backtrace, you can set the `RUST_BACKTRACE` environment variable to `1`.
```

Image: 
![](https://cdn.discordapp.com/attachments/771367133715628076/1062809227384602746/image.png)

Current fix: Remove the ZelliJ cache in the $TMPDIR. It probably varies based on installation...

**Comment by kchibisov** [comment]
But how it's related to alacritty? The backtrace you're showing is from your app, not from the alacritty? Do you have a backtrace for alacritty?

I'd assume that you're trying to run your app at startup, so alacritty just exits because your app exits.

**Comment by ItzSwirlz** [comment]
DAMMIT. Wrong repo
