### ISSUE TITLE
Get rounded window corners, with `window: decorations: none` ? (macOS)

### ISSUE THREAD

**Issue by 0rphee** [alacritty/alacritty#6618]
Is it possible to get rounded window corners without decorations, so it works as if the window used the regular `none` behavior? (so the title bar isn't just transparent, but non-existent)
```
window:
  decorations: none    # Neither borders nor title bar
```

<img width="280" alt="ss" src="https://user-images.githubusercontent.com/79347623/212436227-3cd7419d-75c2-45a9-974a-4aa6a157ae8d.png">

### System

OS: macOS
Version: alacritty 0.11.0 (8dbaa0b)

**Comment by chrisduerr** [comment]
Nope.
