### ISSUE TITLE
Crashed on Awesome WM

### ISSUE THREAD

**Issue by ghost** [alacritty/alacritty#6619]
```thread main panicked at failed to call XResizeWindow: XError { description= GLXBadFBConfig, error_code: 167, request_code: 152, minor_code: 0}, ".../winit-0.27.5/src/platform_impl/linux/x11/windows.rs:1116:10```

**Comment by chrisduerr** [comment]
What did you do while it crashed? Did you resize the window? If so, how big?

**Comment by lodisy** [comment]
Hello, it crashed immediately once run alacritty from command, no UI appeared. The default window I set was Fullscreen but it's never worked, even under desktop environment.

**Comment by lodisy** [comment]
> What did you do while it crashed? Did you resize the window? If so, how big?

It works fine under KDE Wayland but the window mode is not working as expected, as I said before. I am using Asahi Linux with the latest GPU kernel, not sure if it's related to Mesa and OpenGL, since Awesome is a X11 WM.

**Comment by lodisy** [comment]
> What did you do while it crashed? Did you resize the window? If so, how big?

I guess the resizing was forcedly made by the window manager. I'll check if it works without the window mode settings.

**Comment by chrisduerr** [comment]
Can also try latest master or a previous stable version, both are worth a try.
