### ISSUE TITLE
Segment violation ('core' generated)

### ISSUE THREAD

**Issue by XxLiosxX** [alacritty/alacritty#6620]
To what I try to open Alacritty I skip this error: Segment violation ('core' generated) Does anyone know why this is the case?

**Comment by kchibisov** [comment]
If you could provide more info that would be nice. Otherwise we could only guess. Probably something coming from the video driver or such.

**Comment by XxLiosxX** [comment]
It is that I do not know how to explain it since everything worked well and suddenly the next day I get this error

**Comment by kchibisov** [comment]
Maybe you've updated something? Or updated your driver? I could only guess, given that you haven't provided any details, like OS, Display server, and all that stuff asked in the issue template.

**Comment by XxLiosxX** [comment]
### System

OS: Arch Linux
Version: allacritty 0.11.0
Linux/BSD: X11

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: Segment violation ('core' generated)

**Comment by kchibisov** [comment]
Don't you have any backtrace, in `coredumpctl` or such? At least the one that shows library names...

**Comment by XxLiosxX** [comment]
I don't have any trace, and I'm new to this.

**Comment by XxLiosxX** [comment]
Ask me for all the information you need

**Comment by chrisduerr** [comment]
Does it not show up in `coredumpctl` at all?

**Comment by XxLiosxX** [comment]
I explain I use qtile, then I have a key combination to open alacritty, one day I press and do not open the terminal so I decide to download another terminal and try to open alacritty by there I skip the error

**Comment by XxLiosxX** [comment]
the coredumpctl me appears in the path user/bin/coredumpctl

**Comment by chrisduerr** [comment]
> the coredumpctl me appears in the path user/bin/coredumpctl

So can you attach gdb to that and get a backtrace?

**Comment by XxLiosxX** [comment]
Change terminals
