### ISSUE TITLE
I hope you can join the mouse support, thanks

### ISSUE THREAD

**Issue by Expector-Hutch** [alacritty/alacritty#6627]
I can't use some cli software that supports mouse interaction, which makes me very disappointed. I especially hope it can support mouse

**Comment by chrisduerr** [comment]
Alacritty supports mouse mode.

**Comment by Expector-Hutch** [comment]
> Alacritty支持鼠标模式。

But when I use software that supports mouse interaction, such as micro editor, I can't interact with the mouse. Why?
