### ISSUE TITLE
Placement with -o window.position.x no longer works…

### ISSUE THREAD

**Issue by kierun** [alacritty/alacritty#6628]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux, Fedora 37.
Version:  0.11.0
Linux/BSD: X11 and Awesome as WM.

### Logs

Crashes: N.A.
Font/Terminal size: N.A.
Keyboard and bindings: N.A.

### Steps

1. Run `alacritty -o window.position.x=0`

### Expected results

The new alacrity window appears at x=0.

### Actual results

The new alacrity window gets placed where there is room by the WM — That is awesome in windowed mode.

### Notes

This used to work with my old version. Sadly, I cannot remember what it was.

**Comment by chrisduerr** [comment]
Which version broke it? If the old version worked, you should be able to downgrade.

**Comment by kierun** [comment]
> Which version broke it? If the old version worked, you should be able to downgrade.

`0.11.0` broke it. Definitely.

I guess I could downgrade to `0.10.0` and see… And the problem _does not_ appear in `0.10.0`.

**Comment by chrisduerr** [comment]
@kchibisov Are you aware of any X changes in recent winit updates?

**Comment by kiedtl** [comment]
I'm not seeing this issue in alacritty v0.12.2.

**Comment by chrisduerr** [comment]
Closing as fixed in 0.12.2.
