### ISSUE TITLE
Screenshot examples for different OS?

### ISSUE THREAD

**Issue by rubyFeedback** [alacritty/alacritty#6629]
Would it be possible to add screenshot examples for different OS?

I use linux primarily, but recently https://blog.fefe.de/ recommended alacritty so this is
how I found it. But I'd also like to use the same terminal on windows too, so for me it
would be nifty if there is support for windows out of the box, which I assume is the
case. But I'd like to see a short screenshot, just for demo purposes really, to verify
that this works on windows as well.

**Comment by chrisduerr** [comment]
It looks the same on all operating systems. It's just a terminal.
