### ISSUE TITLE
DECSCUSR - Set Cursor Style not working properly

### ISSUE THREAD

**Issue by kosciak** [alacritty/alacritty#6631]
DECSCUSR - Set Cursor Style sequence - "\e[? " doesn't work as expected

There seems to be a problem with changing cursor shape using `echo -e "\e[? q"`
Cursor shape changes to block on 1,2; underline on 3,4; and vertical bar on 5,6
BUT changing style from solid to blinking does not work correctly. Blinking is not enabled, cursor stays in solid mode. Also it seems like visibility of the cursor depends on the moment of blink cycle, as if changing to blinking while cursor would be visible during blink cycle makes cursor solid, and changing whiel cursor would be hidden during blink cycle keeps cursor hidden.

Test code: https://github.com/kosciak/terminal-capabilities/blob/main/change-cursor.sh

Results in Alacritty (cursor.style.blinking=On): 
![alacritty](https://i.imgur.com/elp5f5D.gif)

Expected results:
- GNOME Terminal: 
![gnome-terminal](https://i.imgur.com/YlFFZlZ.gif)
- Kitty: 
![kitty](https://i.imgur.com/5iGEuBT.gif)

With cursor.style.blinking=Always cursor changes shape corretly, and stays in blinking mode even when solid mode is requested.

What's a bit strange if I append BELL to cursor style sequence: `echo -e "\e[3 q\a"` instead of just `echo -e "\e[3 q"` it works as expected:
![alacritty-bell](https://i.imgur.com/5h7pgHV.gif)

### System

OS: Linux - Fedora 37
Version: alacritty 0.11.0
Linux: Gnome 43 on X11

### Logs

Font/Terminal size: 
```
[0.000002620s] [INFO ] [alacritty] Welcome to Alacritty
[0.000031910s] [INFO ] [alacritty] Version 0.11.0
[0.000039880s] [INFO ] [alacritty] Running on X11
[0.000374009s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/kosciak/.config/alacritty/alacritty.yml"
[0.001158106s] [DEBUG] [alacritty] Loading "DejaVu Sans Mono Nerd Font" font
[0.007437644s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.008851849s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.010252394s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Oblique, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.011653019s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Oblique, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[0.012373917s] [DEBUG] [alacritty] Estimated scaling factor: 1
[0.012381887s] [DEBUG] [alacritty] Estimated window size: Some(PhysicalSize { width: 722, height: 434 })
[0.012385797s] [DEBUG] [alacritty] Estimated cell size: 9 x 18
[0.041922084s] [INFO ] [alacritty] Running on AMD Radeon RX 6600 (navi23, LLVM 15.0.6, DRM 3.49, 6.1.6-200.fc37.x86_64)
[0.041935934s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.045300042s] [INFO ] [alacritty] Display scale factor: 1
[0.045311702s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.048485641s] [INFO ] [alacritty] Cell size: 9 x 18
[0.048494591s] [INFO ] [alacritty] Padding: 1 x 1
[0.048498951s] [INFO ] [alacritty] Width: 722, Height: 434
[0.052855966s] [INFO ] [alacritty] PTY dimensions: 24 x 80
[0.054290981s] [INFO ] [alacritty] Initialisation complete
[0.059933191s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[0.059955621s] [INFO ] [alacritty] Padding: 1 x 1
[0.059962211s] [INFO ] [alacritty] Width: 722, Height: 434
```

**Comment by chrisduerr** [comment]
Everything works just fine for me. Can you provide a specific example of an escape sequence that doesn't work as expected?

**Comment by kosciak** [comment]
Simplest test case would be executing this in bash:
```
echo -e "\e[2 q"; sleep 1; echo -ne "\e[5 q"; sleep 3
```
Cursor is changed to solid block (as expected), afer a 1 second sleep cursor changes to solid vertical bar, no blinking while sleep time passes as it would be expected. 
Back in prompt, after executing whole line I've got blinking vertical bar (as expected after sending `\e[5 q`)

If both sequences are requesting change to blinking cursor (of any shape) everything works ok.
The problem occurs when in first sequence we request change to solid cursor (of any shape), and in second to blinking one.


The whole point of this "echo escape sequence and sleep in bash" is to try to find minimal use case replicating behaviour found in vim, where changing cursor shape on mode change (using &t_SI, &t_SR, &t_EI options) changes cursor shape but disables blinking.

**Comment by chrisduerr** [comment]
It blinks just fine. Blinking is just disabled while you're inputting stuff with the keyboard. Everything is working as expected.

**Comment by kchibisov** [comment]
Just speaking aside, your script works just fine for me. Though, could you try latest master? I have a suspicion that scheduler is somehow misbehaving.

**Comment by kosciak** [comment]
OK, seems that this particular issue with the output of test case script is sorted out

alacritty 0.11.0 on Wayland works as expected
alacritty 0.12.0-dev (ed67aa3c) on X11 (haven't tested on Wayland yet) works as expected


No luck with getting blinking cursor in vim though (without setting cursor.style.blinking=Always)

**Comment by kchibisov** [comment]
vim has its own special settings, since it disables the blinking.

You can see the log `alacritty -vvv | grep cursor`. It'll log events as you change the cursor style.

**Comment by kosciak** [comment]
Thanks for the '-vvv' tip, that let me investigate the issue a bit further

- It seems that what disables blinking in vim is using cnorm (ve)
- Terminfo for both xterm and alacritty returns `cnorm=\E[?12l\E[?25h` and as vim don't use cvvis (vs) there's nothing that would set cursor blinking back using `\e[?12h`
- BUT gnome terminal for some reason (might be some hack for vim) uses just `\e[?25h` in vim without changing cursor blinking state
- So let's override cnorm in vim by setting `let &t_ve = "\e[?25h"` and cursor starts blinking in alacritty! So far so good!
- Now let's override cursors for different modes with `let &t_SI = "\e[5 q"` `let &t_SR = "\e[3 q"` `let &t_EI = "\e[1 q"` and after starting vim in alacricitty cursor does NOT blink; insert mode - blinking beam; exit insert - solid block; replace mode - blinking under; exit replace - blinking block; insert mode - blinking beam; exit insert - solid block. The only difference between exiting replace mode and exiting insert mode i managed to spot is "Setting attribute: Reset" showing in alacritty log when switching back from insert mode
- What's interesting and seems to be a bug - when there's solid block cursor instead of blinking and alacritty loses focus and gets focus again cursor starts blinking

Now let's try other way around
- Override cnorm in vim by setting `let &t_ve = "\e[?12h\e[?25h"` (force cursor blinking), and set cursors to 6, 4, 2
- In gnome terminal cursor is solid in all modes
- In alacritty cursor is always blinking (in logs: "Setting mode: ShowCursor" comes after "Setting cursor style ...")

It seems as if in gnome terminal blinking mode set by `\e[<mode> q` has higher priority than set by `\e[12<h|l>`, where as in alacritty `\e[12<h|l>` it's the same flag switched in different ways, and only problem is that something prevents blinking to start again.

**Comment by kosciak** [comment]
After some more digging I've managed to get new minimal test case for the issue.

In bash: 
```bash
echo -ne "\e[?25l\e[1 q";  sleep 0.01; echo -ne "\e[?25h"; sleep 5; echo -ne "\e[0 q"
```

During the 5 second sleep after `\e[?25h` cursor is solid instead of blinking. There are no events (with --print-events) that would normally show up when blinking. 
If alacritty loses focus and gets focus again during this 5 seconds sleep, cursor is going to start blinking in focused window

The key element is that sleep time between "hiding cursor; changing shape" and "showing cursor". Without sleep (or using very low value) like:
```bash
echo -ne "\e[?25l\e[1 q"; echo -ne "\e[?25h"; sleep 5
```
cursor is blinking as expected

Tested in both alacritty 0.12.0-dev (ed67aa3c) and alacritty 0.11.0, both versions on both X11 and Wayland, with the same results

**Comment by DazeCake** [comment]
The same things was be found when I quit nvim.

- nvim cursor was be set `block`
- Alacritty cursor was be set `Beam`

When I change some thing from nvim and quit, the cursor change to `block` and keep until fully reboot Alacritty :(
It can be fix?
or just my nvim settings problem?
Whether or not, thx

**Comment by kchibisov** [comment]
1. you can always type `reset`.
2. you can reset just cursor to the original shape, one way to do that is vim with `au VimLeave * set guicursor=a:ver100`

**Comment by DazeCake** [comment]
> 1. you can always type `reset`.
> 2. you can reset just cursor to the original shape, one way to do that is vim with `au VimLeave * set guicursor=a:ver100`

thank u very much, the second choice seemed batter to me:)
