### ISSUE TITLE
Way to remotely reload alacritty config when nothing in the file has changed?

### ISSUE THREAD

**Issue by znschaffer** [alacritty/alacritty#6633]
I have my theme imported in as current_theme.yml which I symlink as a different theme to change things. Obviously alacritty won't notice when that link changes but if there's a way to remotely send a signal either through `alacritty msg` or someway else to reload it that would be amazing. 

Right now I have to open up the config and `:w` it to get it to reload.

**Comment by chrisduerr** [comment]
I think `touch ~/.config/alacritty/alacritty.yml` should work?

**Comment by SyedFasiuddin** [comment]
checkout #5852

**Comment by SyedFasiuddin** [comment]
Any reason why it is closed? Will it now work for symlinks?
