### ISSUE TITLE
alacritty config does not load font specified in config.

### ISSUE THREAD

**Issue by xnorkl** [alacritty/alacritty#6636]
Alacritty user config file loads, but does not load the font specified in the user config.

### System

OS: Linux
Version: alacritty 0.11.0 (8dbaa0bb)
Linux/BSD: X11, i3

#### Alacritty -vvvv output:

Created log file at "/tmp/Alacritty-843078.log"
[0.000000876s] [INFO ] [alacritty] Welcome to Alacritty
[0.000033836s] [INFO ] [alacritty] Version 0.11.0 (8dbaa0bb)
[0.000043649s] [INFO ] [alacritty] Running on X11
[0.000381029s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/xnorkl/.config/alacritty/alacritty.yml"
[0.001705201s] [DEBUG] [alacritty] Loading "monospace" font

#### Full output here:
[Alacritty-843078.log](https://github.com/alacritty/alacritty/files/10473048/Alacritty-843078.log)

#### Config:
        font:
          # Normal (roman) font face
          normal:
            # Font family
            #
            # Default:
            #   - (macOS) Menlo
            #   - (Linux/BSD) monospace
            #   - (Windows) Consolas
            family: Fira Code
            style: Regular

#### Full config here:
[alacritty.txt](https://github.com/alacritty/alacritty/files/10473056/alacritty.txt)

**Comment by nixpulvis** [comment]
Willing to bet this is a YAML whitespace issue.

**Comment by kchibisov** [comment]
Yeah, it is. The config has broken formatting. Likely some formatter where used on it.

The font section should have `zero` leading spaces.
