### ISSUE TITLE
Chinese characters missing when editing in vim

### ISSUE THREAD

**Issue by ihnfsax** [alacritty/alacritty#6641]
Some Chinese characters are missing while I'm inputting something in vim. This happens when using gvim in powershell or vim/neovim in a SSH session. All alacritty settings are default. As the following figure shows, only the Chinese characers **below** the input line will disappear. After I leave the insert mode, and press `j` or `k`，everything is correctly rendered.

<img src="https://user-images.githubusercontent.com/57187749/213963208-8000e00d-e576-45ae-9e10-b200428bc3f5.jpg" width="500"/>

### System

OS: Windows 10
Version: alacritty 0.11.0 (d23330a)

**Comment by chrisduerr** [comment]
Can you reproduc this on macOS/Linux?

**Comment by ihnfsax** [comment]
> Can you reproduc this on macOS/Linux?

@chrisduerr I can't. I've tried this on Ubuntu 22.04 VM and no character is missing.

**Comment by chrisduerr** [comment]
Very likely a ConPTY/Windows issue then. Don't see how Alacritty itself would cause this problem.
