### ISSUE TITLE
IME purpose should be set to terminal

### ISSUE THREAD

**Issue by lukaslihotzki** [alacritty/alacritty#6644]
The on-screen keyboard GNOME opens when using Alacritty lacks modifier keys. That's because Alacritty does not specify the input is for a terminal. In wayland, this can be done by [set_content_type](https://docs.rs/wayland-protocols/latest/wayland_protocols/wp/text_input/zv3/client/zwp_text_input_v3/struct.ZwpTextInputV3.html#method.set_content_type) to [ContentPurpose::Terminal](https://docs.rs/wayland-protocols/latest/wayland_protocols/wp/text_input/zv3/client/zwp_text_input_v3/enum.ContentPurpose.html#variant.Terminal).

The difficulty here is that ZwpTextInputV3 is handled by winit (in https://github.com/rust-windowing/winit/blob/master/src/platform_impl/linux/wayland/seat/text_input/mod.rs), so winit needs to add an IME purpose too (not specific to Wayland). I think this would be reasonable (although support in the other platform impls would be limited, macos at least [supports some](https://developer.apple.com/documentation/appkit/nstextcontenttype)). Alternatively, Alacritty would have to do IME handling manually on Wayland.

**Comment by kchibisov** [comment]
I'd add hints for IME right for winit then, should be simple.
