### ISSUE TITLE
selection rectangle is not cleared when entering copy-mode in tmux

### ISSUE THREAD

**Issue by benoit-pierre** [alacritty/alacritty#665]
When using xterm, the selection rectangle is correctly cleared when entering copy-mode in tmux. That's not the case with alacritty: this result in the selection rectangle staying in the same place, highlighting whatever text is at the same position.

I'm using the latest master (94849c4).

**Comment by kchibisov** [comment]
I'm not sure that it could be reproduced on the latest release.

**Comment by chrisduerr** [comment]
> I'm not sure that it could be reproduced on the latest release.

It's not an issue with the latest release as far as I know. Tmux copy mode should clear the selection.
