### ISSUE TITLE
Windows: Copy upon mouse selection/doubleclick

### ISSUE THREAD

**Issue by rbartl** [alacritty/alacritty#6650]
When selecting something in alacritty in windows i would like it to automatically put it into clipboard (save_to_clipboard is set to true already)

### System

OS: Windows
Version: 0.11
Linux/BSD: -

**Comment by chrisduerr** [comment]
Does the clipboard work for you in general? If `save_to_clipboard` is set, it should be copied automatically.

Also make sure you're not using `tmux` or any other terminal multiplexing client. This obviously only works without mouse mode.

**Comment by rbartl** [comment]
clipboard copying works when i use CTRL+SHIFT+C (its then also in system clipboard)
though i never got it to do that automatically. 

tmux is not running. 
i tried with a WSL debian & a normal windows shell (no shell settings in alacritty config).
neither wants to copy automatically :(

**Comment by chrisduerr** [comment]
Please share your configuration file.

**Comment by rbartl** [comment]
config without comments:
`
% grep -v '#.*' alacritty.yml | uniq

window:

  opacity: 0.9

selection:

  save_to_clipboard: false

shell:
  program: debian
  args:
    - run zsh --login

key_bindings:
  - { key: Paste,                                       action: Paste          }
  - { key: Copy,                                        action: Copy           }
  - { key: C,        mods: Control|Shift, action: Copy             }
`

**Comment by kchibisov** [comment]
>save_to_clipboard is set to true already

>selection:
  save_to_clipboard: false

This doesn't look like `true` to me.

**Comment by rbartl** [comment]
well that resolves this embarrassing issue ;) 🙈.
Thx 🙇‍♂️
