### ISSUE TITLE
alacritty.yml should be included by default in somewhere not only github

### ISSUE THREAD

**Issue by mu-us61** [alacritty/alacritty#6651]
OS: Debian 11 
alacritty version : alacritty 0.12.0-dev (bcd6d0d9)

I installed and my version says it is alacritty 0.12.0-dev (bcd6d0d9) so now I couldnt find proper alacritty.yml in github releases because most recent one is version 0.11.0 

I am suprised alacritty doesnt put a right copy of alacritty.yml in some directory , this searching right version of alacritty.yml from github makes nonsense

I did check entire disk with fzf couldnt find "alacritty.yml" in my disk , other programs inludes their defaults in somewhere

**Comment by kchibisov** [comment]
Your distribution should package the `alacritty.yml`. If you build from source, it's your duty to ship the config, alacritty won't write any files for you.
