### ISSUE TITLE
Sticky prompt line

### ISSUE THREAD

**Issue by azizk** [alacritty/alacritty#6657]
Hi!

I'd like to make the following feature request:

Whenever commands are entered, they sometimes produce a lot of output. When you scroll up and down you often don't know which command was executed. I think it would be really helpful if the corresponding command would stick to the top of the terminal window. You can imagine it similar to sticky class/function headers in code editors.

Thanks!

### System

OS: Linux
Version: alacritty 0.11.0 (8dbaa0bb)
Linux: Manjaro 6.1

**Comment by kchibisov** [comment]
Sticking and such is up to your shell. However there's an escape sequence that does allow jumping to the marks.

See https://github.com/alacritty/alacritty/issues/5850
