### ISSUE TITLE
Some events are not drawn until another key is pressed

### ISSUE THREAD

**Issue by caioolivv** [alacritty/alacritty#6659]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux (Fedora Workstation 37)
Version: alacritty 0.10.1
Linux/BSD: X11 GNOME

### Logs

Couldn't find anything interesting in the logs. 

https://user-images.githubusercontent.com/38115797/215499128-f19c75a3-1b3a-4692-8a75-41e48bc0f5d7.mp4

As per title, some events are not draw until another key is pressed, in which case alacritty just "jumps" to the new event. These usually just happen some 30 seconds after opening a new window and will get worse with time.

**Comment by kchibisov** [comment]
Are you using intel GPU? Though, unless you can reproduce on the latest master, I'd close this issue (and nano is a weird test case on its own, it might be fixed by `TERM=xterm-256color`)

**Comment by caioolivv** [comment]
So far, I haven't been able to reproduce on master.
