### ISSUE TITLE
Reversesearch (ctrl + r) and jumping between the command view issue

### ISSUE THREAD

**Issue by itouchdennis** [alacritty/alacritty#6662]
When reverse searching a command with "crtl + r" and then try to edit the command (e.g. jump with "end" to the command end). You will see, the cursor is not on the end of the command. Based on the search string, it is on the char - searchstring length.  I think its caused by the shown search string in the terminal. If you don't have this reverse search string in your terminal, the issue wont happen (e.g. by going up with arrow keys and edit the command)

### System

OS: Linux Debian Testing 
Version: alacritty 0.11.0
Linux/BSD: X11, KDE, Kwin

**Comment by chrisduerr** [comment]
What makes you think this is an Alacritty issue? This sounds **very much** like a shell issue.

**Comment by itouchdennis** [comment]
> 

Nevermind, I tought it was just on alacritty as I switched to it some days ago and I could swear it worked before - tested it in another terminal - same issue - you are right!

**Comment by itouchdennis** [comment]
Shell issue - not alacritty
