### ISSUE TITLE
Prolem with Tmux and Neovim

### ISSUE THREAD

**Issue by SoporteCoctell** [alacritty/alacritty#6668]
Hi. Some weeks ago I started using alacritty, and today I started learning how to use tmux. I've discovered that when I want to open Neovim, it appears to be lacking the background color (with Tmux), but when I open it outside Tmux, it works perfectly fine. [Images of the problem](https://imgur.com/a/Z4liByi) . If I do the same in Kitty or Konsole with tmux, it works perfectly. Thank you very much and greetings

### System

OS: Linux
Version: 0.11.0
X11 Plasma 5.26

**Comment by chrisduerr** [comment]
That just looks like two completely different colorschemes. What happens if you run `:set termguicolors`?

**Comment by SoporteCoctell** [comment]
I ran it and nothing happened, and I can ensure you it's the same colorscheme

**Comment by chrisduerr** [comment]
Considering the two have completely different colors, even for the status bar, it's certainly not the same.

This is likely an issue with `TERM`, I recommend setting that up in `tmux` properly. But since it works outside of tmux it's really not an Alacritty issue.
