### ISSUE TITLE
Cannot open app

### ISSUE THREAD

**Issue by dat-le-4** [alacritty/alacritty#6674]
### System

OS: macOS
Version: 0.11.0

Can not open the app after installing with home-brew. Tried to go to settings and allow to open but still not work. Maybe a problem with new macOS update.

**Comment by chrisduerr** [comment]
Have you tried executing the executable itself from CLI?

**Comment by oliverryde** [comment]
I get this message on ventura 13.2.
<img width="270" alt="Screenshot 2023-02-07 at 11 15 50" src="https://user-images.githubusercontent.com/118974398/217217439-b914a8fa-c753-43fb-94f9-7778d423c362.png">
I get the message with brew and downloading the package directly.

**Comment by kchibisov** [comment]
Your system security settings won't allow it to start. You can likely compile from source or pay apply to use free (as in freedom) software. We won't do that.

**Comment by oliverryde** [comment]
> Your system security settings won't allow it to start. You can likely compile from source or pay apply to use free (as in freedom) software. We won't do that.

Thank you. That makes sense.

**Comment by chrisduerr** [comment]
You should be able to `Show in Finder` -> Right click -> Open and then it should allow you to still open it iirc.
