### ISSUE TITLE
regex hints: multiple lines

### ISSUE THREAD

**Issue by LordTlasT** [alacritty/alacritty#6676]
I am sorry to trouble, I looked at all the issues I found relevant and did not find what I wanted,.
I'd like to be able to output the screen's content to another program.

I tried to do this with regex hints but I can't match multiple lines, a regex like this: "<prompt>.+" will only match the line my prompt is on.
Am I missing something? Or is there no way to make this work.

Is this information related to control characters?
I want to know the right path, but you can answer briefly, that would be help already.

Thank you for this awesome terminal experience I have been getting so far.

**Comment by chrisduerr** [comment]
Multi-line regex is not supported for hints and there is no plan to change that.
