### ISSUE TITLE
Screen flickering problem when switching workspaces

### ISSUE THREAD

**Issue by luisvgs** [alacritty/alacritty#6680]
Hello, I recently noticed this weird bug when switching workspaces from/to an Alacritty instance opened. The screen rapidly flickers with a glitch that is slightly perceptible. In the screenshots below I switch back and forth from my desktop and Alacrity. As you can see, some weird pixels are visible. It is worth mentioning that the problem is not reproducible with Kitty from my end.

### System

OS: EndevourOS 
Version: 0.11.0
Linux/BSD: i3wm
CPU: Intel Core i7-7600U
Graphics: Intel HD Graphics 620 
Display: x11 

![image](https://user-images.githubusercontent.com/10943988/216978442-494f5e3d-1c4b-49bf-b796-340376fd72df.png)

![image](https://user-images.githubusercontent.com/10943988/216978479-b5eca511-20a6-483f-a291-9df1faf3a73c.png)

Any further help and suggestion would be deeply appreciated. Thank you in advance!

**Comment by chrisduerr** [comment]
Which compositor are you running?

**Comment by luisvgs** [comment]
> Which compositor are you running?

I'm not using any, right now. I previously was using `picom`, but the issue persist whether the compositor was enabled or not.

**Comment by chrisduerr** [comment]
Were you running the stock `picom` config?

**Comment by kchibisov** [comment]
That's expected when you don't have a compositor on X that things will flicker.
