### ISSUE TITLE
Alacritty terminal contents fail to render 

### ISSUE THREAD

**Issue by jxlambda** [alacritty/alacritty#6681]
Hi, after updating packages on my system this morning, I went ahead and also updated my local build of alacritty (i.e. cargo built, not a port or package). As a result, when invoking `alacritty`, a window is created and it seems that even the cursor is positioned correctly (i.e. where the prompt should end), however, the contents of the window are not rendered.

![Screenshot from 2023-02-07 09-37-11](https://user-images.githubusercontent.com/61850441/217185066-bd9a5a79-2ff3-485b-808b-fffa798561e0.png)

The above shows the rendering

### System
OS: Linux; Fedora 37
Version: alacritty 0.11.0

Running in Mutter under GNOME 43.2. This occurs with Mutter and Weston. On X11, alacritty fails to start, due to failing to create a GL context.

```
jxl.dwarf ~ % alacritty
Error: Error creating GL context; Received multiple errors:
	Couldn't find any pixel format that matches the criteria.
	Couldn't find any pixel format that matches the criteria.

Error: "Event loop terminated with code: 1"
jxl.dwarf ~ %
```

### Logs

Below is the log for a regular start-up of alacritty, with verbosity set to max and `--print-events` given:

[alacritty-startup.log](https://github.com/alacritty/alacritty/files/10672761/alacritty-startup.log)

If there's anything I can do to help fix this, let me know.

**Comment by kchibisov** [comment]
Likely your drivers broke. I'd guess you're running nvidia drivers or system path for drivers changed. Reboot might fix the issue for some drivers(mesa don't require it).

**Comment by jxlambda** [comment]
I checked, and my last update transaction has only my editor package being updated. I've also rebooted the system (this is a VM, btw, so I also "power" cycled it just to be sure), which resulted in no changes.

This rendered correctly yesterday evening. Is there anything I can poke and prod at to identify the cause more precisely?

**Comment by kchibisov** [comment]
Oh, if it's a vm might some on a vm side changed. likely `LIBGL_ALWAYS_SOFTWARE=1 alacritty` will change that.

**Comment by jxlambda** [comment]
It worked! Thank you! Is there a way of setting this environment var or setting for alacritty conditionally, without too many intricate dances? I'm fine with exporting this in my .profile or similar, but would prefer to use hardware rendering when possible.

(As there's a workaround for this situation, should I close the ticket?)

**Comment by kchibisov** [comment]
you're in a vm, unless you have GPU passthrough you won't have it anyway.

**Comment by jxlambda** [comment]
Yeah, I use alacritty on all my devices, running different OSen (on actual hardware and virtualized), and use the same configuration (version controlled and all that), so I'd like to make this hassle free for myself.

I'll see if there's a way of doing this that's not an amalgamation of horror, and upon success, post the solution here. Maybe it fits a Known Issues and Workarounds or FAQ section, or the like.

Thanks for the rapid help @kchibisov regardless!
