### ISSUE TITLE
Retain selection of unchanged text

### ISSUE THREAD

**Issue by cramertj** [alacritty/alacritty#6682]
OS: Linux
Version: alacritty 0.11.0-dev (851dbc32)
X11

When running CLI apps (unfortunately unshareable) that redraw their output, mouse or VIM (visual mode) selection of text is invalidated by redraws, even if the characters in question are not changing. Other emulators such as Terminator and Gnome-Terminal appear to retain selection even if the characters are redrawn by the CLI app, so long as the characters remain the same.

**Comment by kchibisov** [comment]
Maybe you could give a clear example when it should retain. We do retain keep selection if the escape sequence don't touch the content.

The same applies to scrolling and similar activities.

We don't even invalidate the selection when something changes below the cursor, for example if you run `watch` and select time, the selection won't invalidate.

**Comment by chrisduerr** [comment]
Yeah this can be easily disproven with `htop`. Unless you actually share a way to reproduce it, this issue is useless.

**Comment by cramertj** [comment]
Thanks for the responses! I'm looking into how to repro with public code, and will update here if I succeed. I've confirmed that some other tools seem to be able to redraw *different* characters and selection is retained, so there's something particular about the way that this tool is drawing.

**Comment by cramertj** [comment]
It looks like the tool that loses selection was erasing multiple lines by moving the cursor with (golang) `fmt.Printf("\033[%dA", lines)` and then redrawing all of the information.

Another tool that I've confirmed holds selection uses plain backslash characters (python) `sys.stdout.write('\b\b\b')`.

**Comment by cramertj** [comment]
@chrisduerr Would you mind reopening the issue with this information, or are more details required?
