### ISSUE TITLE
Add manpage for config file format

### ISSUE THREAD

**Issue by mpldr** [alacritty/alacritty#6685]
Hello, while working through the configuration, I couldn't help but think that it would be easier if there was something like `alacritty.yml(5)` or similar, documenting the various settings.

**Comment by chrisduerr** [comment]
I don't disagree that it could be beneficial, but I don't think it's sustainable to have yet another place that needs to be updated whenever the config is changed.

So unless this is automated, I don't think it's a good idea.

**Comment by mpldr** [comment]
I agree, manually keeping documentation synchonised in multiple places
inevitably leads to them getting out of sync. Maybe a small python
script or something could help "translating" it into a simple
transitional format like scdoc.

-- 
Moritz Poldrack
https://moritz.sh

**Comment by kchibisov** [comment]
Done in bd4906722a1a026b01f06c94c33b13ff63a7e044
