### ISSUE TITLE
Maximizing windows on macOS/X11 doesn't cover the whole screen

### ISSUE THREAD

**Issue by SheldonZhong** [alacritty/alacritty#6696]
### System

OS: macOS
Version: f409f743724207e7a2a4c008ce74ea505ae6bbcf

To reproduce: hold option key and double click a corner of the window. It is supposed to maximize the window and cover the whole screen. 

Notes: 
* It only happens on my second monitor (3840 x 2160). It is not reproducible when I maximize a window in the built-in monitor. 
* In my macOS setup, I auto hide the dock and notification bar.

I found this commit f409f743724207e7a2a4c008ce74ea505ae6bbcf introduces the problem using git bisect.

This is the screenshot with the `decorations` set to `transparent`
<img width="1920" alt="Screenshot 2023-02-11 at 22 10 36" src="https://user-images.githubusercontent.com/12372003/218292651-c6293581-5939-4f84-8218-fb5354a3437a.png">
`decorations: buttonless`
<img width="1920" alt="Screenshot 2023-02-11 at 22 11 03" src="https://user-images.githubusercontent.com/12372003/218292653-7070ca4f-a31a-49df-b654-fbb5e0cf837e.png">
`decorations: full`
<img width="1920" alt="Screenshot 2023-02-11 at 22 11 23" src="https://user-images.githubusercontent.com/12372003/218292655-faf678cc-b98d-4086-9d0e-6124fd9704b2.png">

Pay attention to the small gaps around the window.

This is the screenshot using 8a838710 with `decorations: buttonless`
<img width="1920" alt="Screenshot 2023-02-11 at 22 19 51" src="https://user-images.githubusercontent.com/12372003/218292825-f7951972-7e0b-4a9d-b4f6-2ef30a36d86b.png">

**Comment by chrisduerr** [comment]
Does it make a difference whether you enable/disable cell-precision resizing in the config?

**Comment by SheldonZhong** [comment]
@chrisduerr I am not aware of this setting in the config. Can you give me a pointer? I don't see the commit introduces a new setting. I can't find it in https://github.com/alacritty/alacritty/blob/master/alacritty.yml either.

**Comment by chrisduerr** [comment]
Yeah right nvm we decided against an option until people actually complained about it. This is probably a winit bug, I've opened an issue upstream:

https://github.com/rust-windowing/winit/issues/2684

**Comment by arsham** [comment]
I'm experiencing this issue on Arch Linux as well. For now I am using the 8a838710e37665f5bdeb8c01d2f1d3e6fec976a6 commit which works fine.

**Comment by kchibisov** [comment]
>I'm experiencing this issue on Arch Linux as well. For now I am using the https://github.com/alacritty/alacritty/commit/8a838710e37665f5bdeb8c01d2f1d3e6fec976a6 commit which works fine.

What window manager are you using?

**Comment by lolicon0930** [comment]
Same situation,
![2023-02-13-09:01:56](https://user-images.githubusercontent.com/14966910/218349412-edaa43d7-a44a-4320-bed7-fbe29e0212fd.png)
8a83871 commit really works fine.
![2023-02-13-09:03:13](https://user-images.githubusercontent.com/14966910/218349429-a407b047-55ee-4977-8792-e3aae1bf1775.png)

**Comment by kchibisov** [comment]
Ah, so dwm can't do window managing, that's sort of expected, I'd assume...

**Comment by arsham** [comment]
> 
> What window manager are you using?

I am using AwesomeWM.

**Comment by lolicon0930** [comment]
> Ah, so dwm can't do window managing, that's sort of expected, I'd assume...

Well, it looks like it's time to switch to bspwm. lol

**Comment by kchibisov** [comment]
I mean we'll likely alter the behavior on X11, it's just not as trivial to fix like on macOS.

**Comment by lolicon0930** [comment]
Well, in fact, I have planned to switch to bspwm. It's just because I'm too lazy to patch.

**Comment by joshbainbridge** [comment]
Was going to write an issue but then noticed this. Same for me on macOS on the built in MacBook monitor:

<img width="1728" alt="Screenshot 2023-02-15 at 11 17 14" src="https://user-images.githubusercontent.com/8218521/219136398-44581e8a-d1f4-4f77-ab47-4a2b583799fa.png">

<img width="1728" alt="Screenshot 2023-02-15 at 11 22 41" src="https://user-images.githubusercontent.com/8218521/219136419-0523e505-a554-420b-b8c2-2eba476949e5.png">

Now when maximising the window, there is always a gap at the top of the screen. My config is very minimal.

**Comment by kchibisov** [comment]
**Just so you know. The macOS issue is fixed, but the fixed is not included anywhere.**

However, if you're on X11, do report if you have issue like that with the widnow manager you're seeing this.

**Comment by chrisduerr** [comment]
> I mean we'll likely alter the behavior on X11, it's just not as trivial to fix like on macOS. Because on X11 it's just a hint for window manager, so wm can ignore it.

I'm genuinely surprised dwm takes the hint into account at all. Leave it to suckless to partially implement a feature and as a result make things worse than not implementing it at all I suppose.

**Comment by lolicon0930** [comment]
It's really bad that dwm doesn't fill every window space, but now I switch to bspwm and it's fine.
![2023-02-16-08:52:05-s](https://user-images.githubusercontent.com/14966910/219230916-416e1c44-8fd7-4f13-bf9e-47a5f4d2f30f.png)
![2023-02-16-08:56:16-s](https://user-images.githubusercontent.com/14966910/219230937-fcda9cfc-32a2-43fa-b32c-69384a87870b.png)
