### ISSUE TITLE
Text flickering when using Tmux

### ISSUE THREAD

**Issue by Solarunit** [alacritty/alacritty#6709]
I noticed that text is flickering in Tmux when running: `flatpak update`

I canceled `flatpak update` and opened new non-tmux Alacritty window and there wasn't any flickering.

### System

OS: Solus
Version: 0.11.0
Linux: X11, Budgie, Mutter, AMD GPU

**Comment by kchibisov** [comment]
Not sure what about what flickering are you talking about, but terminal content might render in partial state, when writing application is not doing any synchronization. That's applicable to any terminal that doesn't delay updates increasing input lag.

**Comment by Solarunit** [comment]
Well, I thought it's a bug since gnome-terminal doesn't do it. BTW I also noticed the last line flickering when scrolling fast the man pages, see gif:

![](https://i.imgur.com/PVOCLeI.gif)

(The flickering is more noticeable in real time)
Same thing when scrolling in `less` when you have the last line activated (with file progress %)

**Comment by nixpulvis** [comment]
Is there a relevant setting or configuration option to avoid this?

**Comment by Solarunit** [comment]
Here is a gif when installing flatpak app in tmux, you can see a heavy flickering there:

![](https://i.imgur.com/xUQEVzz.gif)

**Comment by Solarunit** [comment]
> Is there a relevant setting or configuration option to avoid this?

idk, I only started using Alacritty recently, bcs it works best with tmux..

**Comment by nixpulvis** [comment]
@Solarunit can you replicate this without tmux?

**Comment by Solarunit** [comment]
@nixpulvis the 1st example (scrolling the man page) was without tmux, same thing when scrolling in less if you have progress % line at the bottom. 

Flatpak without tmux far less noticeable.

**Comment by nixpulvis** [comment]
Ah yes, I see the description clearly states this, sorry.

I don't know much about the way this works, but I'm curious if the newish damage tracking code could help without burdening the pipeline.

**Comment by felipesere** [comment]
I have a similar-ish flicker. I noticed it tmux first but verified that just scrolling through a man-page changes the hue of the background.

https://user-images.githubusercontent.com/1850188/220327333-3af505ae-3f29-4fce-a26a-6176b599dd75.mov

I'm on the latest alacritty with a Nord theme.

**Comment by kchibisov** [comment]
If the application wants flicker free output it should use the appropriate escape sequences to do so. Without them it's a gamble.

Nothing alacritty can do about. There're applications doing flicker free rendering using the appropriate escape sequences, `less` is not doing so.

The flickering you see I can see in any terminal emulator, it might be less frequent in some of them, but it exists in each of them.

The nature of it is that content was e.g. cleared, but not written to (like you have with flatpack). Or the application draws the status line in a separate draw call (like in less).

tmux is also a terminal emulator, and you see flickering in it as well.

One option you can try for tmux though, 

```
set-option -ga terminal-features ",alacritty:sync"
```

That will make tmux itself synchronize updates to alacritty, but the applications running inside the tmux could still not do so.

**Comment by Solarunit** [comment]
Thanks for explanation!

I tried this option:
`set-option -ga terminal-features ",alacritty:sync"` 
looks like it does nothing

>The flickering you see I can see in any terminal emulator, it might be less frequent in some of them, but it exists in each of them.

I mostly used gnome-terminal before and haven't noticed any flickering
Tested today: in gnome-terminal 3.45.90,
- fast scrolling in `less` (not in tmux) - no flickering on bottom "progress line" 
- updating flatpak app in tmux - no visible flickering

**Comment by chrisduerr** [comment]
You might have to install Alacritty's terminfo manually if you haven't. IIRC `tmux` uses the terminfo capability which is not included in ncurses since it was denied as a feature upstream. But I haven't kept up with that for a bit, it's possible tmux does some other validation at this point.

**Comment by retrodaredevil** [comment]
I just experienced this issue today as well (alacritty + tmux + running `flatpak update`). I'm running 3.2a. Does anyone have any updates on this?
