### ISSUE TITLE
Bad UX with horizontal scrolling

### ISSUE THREAD

**Issue by ArtAndreev** [alacritty/alacritty#6711]
When I scroll with mouse, scrolling is very inconsistent, it scrolls diagonally. If I want to scroll strictly vertically, I should move my fingers on touchpad strictly vertically too. I expected scroll to work like this: alacritty gets coordinates or direction, for example, {x = 20, y = 100} or 20 degrees to the right from vertical direction (it's not a accurate calculation), so alacritty desides, that the current scroll is vertical, because new point is closer to vertical direction. Something like this or disabling horizontal scroll in config can fix the issue.

### System

OS: Linux/BSD/macOS/Windows
macOS
Version: `alacritty --version` output
<img width="396" alt="image" src="https://user-images.githubusercontent.com/26388769/219848562-9cf8f0be-9f12-419e-9dd6-701ca85b1b22.png">
Linux/BSD: X11/Wayland, DE or Compositor and WM
Not applicable.

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`
I don't think there is a need in logs.

**Comment by kchibisov** [comment]
>When I scroll with mouse, scrolling is very inconsistent, it scrolls diagonally. If I want to scroll strictly vertically, I should move my fingers on touchpad strictly vertically too. 

How do you even get horizontal scrolling if we don't have such a thing for terminal content? Most apps don't understand horizontal scrolling, and we don't have any configuration for horizontal scrolling.

**Comment by kchibisov** [comment]
Could you test this patch? I think for terminal we might want something like that, where horizontal scrolling only apply when the amount is larger than vertical, because you don't really want horizontal scrolling in the terminal anyway.  

```diff
diff --git a/alacritty/src/input.rs b/alacritty/src/input.rs
index f4c81006..6fdfa2a9 100644
--- a/alacritty/src/input.rs
+++ b/alacritty/src/input.rs
@@ -648,13 +648,18 @@ impl<T: EventListener, A: ActionContext<T>> Processor<T, A> {
                 let new_scroll_px_y = lines * self.ctx.size_info().cell_height();
                 self.scroll_terminal(new_scroll_px_x as f64, new_scroll_px_y as f64);
             },
-            MouseScrollDelta::PixelDelta(lpos) => {
+            MouseScrollDelta::PixelDelta(mut lpos) => {
                 match phase {
                     TouchPhase::Started => {
                         // Reset offset to zero.
                         self.ctx.mouse_mut().accumulated_scroll = Default::default();
                     },
                     TouchPhase::Moved => {
+                        // Do horizontal scrolling, only when the `x` amount is larger than `y`
+                        // for touchpads.
+                        if lpos.x < lpos.y {
+                            lpos.x = 0.;
+                        }
                         self.scroll_terminal(lpos.x, lpos.y);
                     },
                     _ => (),

```

**Comment by ArtAndreev** [comment]
Works perfect for vertical scrolling, thanks!
But the issue still exists for horizontal scrolling, I think, there should be a similar condition for it, something like this:

```rust
// Also prefer vertical scrolling, if `x` equals to `y`.
if lpos.x.abs() <= lpos.y.abs() {
    lpos.x = 0.;
} else {
    lpos.y = 0.;
}
```

**Comment by ArtAndreev** [comment]
Works pretty well for vertical scrolling, rare misses happen, I will get used to it, thanks!
 But the issue still exists for horizontal scrolling, I think, there should be a similar condition for it, something like this:

```rust
// Also prefer vertical scrolling, if `x` equals to `y`.
if lpos.x.abs() <= lpos.y.abs() {
    lpos.x = 0.;
} else {
    lpos.y = 0.;
}
```

**Comment by kchibisov** [comment]
Probably. We might also consider doing using angle between median and X axis.

**Comment by kchibisov** [comment]
Could you check whether this is any better? Should be harder to trigger at least.

```
diff --git a/alacritty/src/input.rs b/alacritty/src/input.rs
index f4c81006..5728665a 100644
--- a/alacritty/src/input.rs
+++ b/alacritty/src/input.rs
@@ -648,13 +648,21 @@ impl<T: EventListener, A: ActionContext<T>> Processor<T, A> {
                 let new_scroll_px_y = lines * self.ctx.size_info().cell_height();
                 self.scroll_terminal(new_scroll_px_x as f64, new_scroll_px_y as f64);
             },
-            MouseScrollDelta::PixelDelta(lpos) => {
+            MouseScrollDelta::PixelDelta(mut lpos) => {
                 match phase {
                     TouchPhase::Started => {
                         // Reset offset to zero.
                         self.ctx.mouse_mut().accumulated_scroll = Default::default();
                     },
                     TouchPhase::Moved => {
+                        // When the angle between (x, 0) and (x, y) is lower than ~25 degrees
+                        // (cosine is larger that 0.9) we consider this scrolling as horizontal.
+                        if lpos.x.abs() / lpos.x.hypot(lpos.y) > 0.9 {
+                            lpos.y = 0.;
+                        } else {
+                            lpos.x = 0.;
+                        }
+
                         self.scroll_terminal(lpos.x, lpos.y);
                     },
                     _ => (),

```

**Comment by ArtAndreev** [comment]
Vertical scrolling works perfect, thanks! But horizontal scrolling is hard to be done precisely. I think, it's better than previous implementation you sent, because horizontal scrolling is rare necessity (personally, I've never used it).

**Comment by joshuataylor** [comment]
Thanks for the fix!

I can confirm this also fixes it on MacOS, coming from a desktop user on Linux I was really confused why it was doing this, and then realised it was horizontal scroll (ie my finger might not be 100% precise).

Not sure if this should be raised as another issue, but would it make sense to add a configuration option to disable horizontal scrolling, or is that more of an OS setting? From what I can see that can be configured if using libinput on Linux, but it's global:

```
Option "HorizontalScrolling" "false"
```

But I have a question.. for apps which have a "scroll", such as nano, is that controlled via the above setting (for OS, not the fixed patch).

I think the most straightforward example for this would be nano, which is available in pretty much all Linux distros and comes default on MacOS. Try and open a file which can scroll, then move your trackpad to the right on text and your cursor (in Alacritty, not the cursor on the screen, if that makes sense) should move to the right.

**Comment by chrisduerr** [comment]
Nano just receives escape sequences from Alacritty. It has no clue what libinput even is. Disabling horizontal scrolling in libinput might disable it in Alacritty too, but I'd have to test myself how exactly it works. You'd think it wouldn't receive horizontal scroll events anymore.
