### ISSUE TITLE
[Feature] Reverse output direction - from top to bottom?

### ISSUE THREAD

**Issue by rwjack** [alacritty/alacritty#6713]
I'm curious if we could reverse the terminal, and print everything from the top to the bottom?
It seems more ergonomic looking at the top of my monitor instead of looking down at it all the time.

Eg. Have this:

```
$ root > echo 123
123
.
.
.
.
```

Instead of the regular output:
```
.
.
.
.
123
$ root > echo 123
```

**Comment by kchibisov** [comment]
>I'm curious if we could reverse the terminal, and print everything from the top to the bottom?

No, because the content is not symmetric and multiple lines compose the end content (consider compiler messages).

If you want to move prompt to the top press `ctrl + l`.

**Comment by rwjack** [comment]
@kchibisov I don't think you understood me correctly. I'm literally talking about mirroring the output top down. I don't see how that relates to symmetric content?

Have this:
```
$ root >
step 3
step 2
step 1
$ root > make
.
.
```

Instead of:
```
.
.
$ root > make
step 1
step 2
step 3
$ root >
```

**Comment by rwjack** [comment]
This would imply having the status bar at the 0th line of the terminal, and writing new output to the 1st line and moving everything downwards

**Comment by rwjack** [comment]
https://superuser.com/questions/719317/can-i-reverse-the-stream-direction-of-my-terminal

Ergonomics is everything, adapt and you will favor more users.

**Comment by kchibisov** [comment]
Reverse this
```
kchibisov@Buran:alacritty-workspace/fork [ master ±] ┃ cargo build
    Blocking waiting for file lock on build directory
   Compiling alacritty v0.13.0-dev (/home/kchibisov/src/rust/alacritty-workspace/fork/alacritty)
warning: unnecessary trailing semicolon
    --> alacritty/src/event.rs:1700:9
     |
1700 |         ;
     |         ^ help: remove this semicolon
     |
     = note: `#[warn(redundant_semicolons)]` on by default

warning: `alacritty` (bin "alacritty") generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 7.15s

```

You'll get.

```
    Blocking waiting for file lock on build directory
   Compiling alacritty v0.13.0-dev (/home/kchibisov/src/rust/alacritty-workspace/fork/alacritty)
warning: unnecessary trailing semicolon
    --> alacritty/src/event.rs:1700:9
     |
1700 |         ;
     |         ^ help: remove this semicolon
     |
     = note: `#[warn(redundant_semicolons)]` on by default

warning: `alacritty` (bin "alacritty") generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 7.15s

```

you see, the content doesn't make any sense now. You have the same situation with any scrolling software, like browsers as well.

**Comment by kchibisov** [comment]
>adapt and you will favor more users.

We are not earning here anything or sell to begin with, why we should attract more users in the first place.

**Comment by rwjack** [comment]
From what you're saying, a similar problem would arise when eg.

File:
```
1
2
3
```

```
$ cat file
3
2
1
```

^ This would happen If the output was LITERALLY mirrored

Though what I'm suggesting is putting the main status line above the output, and printing everything in a top down fashion.

```
$ make
> step 1
.
.
.
```

```
$ make
step 1
> step 2
.
.
```

```
$ make
step 1
step 2
> step 3
.
```
etc...

> We are not earning here anything or sell to begin with, why we should attract more users in the first place.

Makes sense in my mind that it's better when "I" have more people using "my" software. More room to grow and more brains to help it grow.

**Comment by rwjack** [comment]
It seems I have made a mistake in an example in my 2nd comment.

To clarify once more, the Idea is to have the terminal print output so it favors the user ergonomically. So that everything prints in order as it should, but just from the TOP to the BOTTOM.

It might seem weird at first, but it really is ergonomically healthier to look straight with your eyes and directly at the screen, instead of looking down at it.

+ If the taskbar is at the top of the screen, it makes sense to have my eyes on that part of the screen most of the time, rather than constantly looking down at my terminal, then looking up somewhere else.

**Comment by rwjack** [comment]
Examples:
```
$ > echo 123
```
```
$ >
$ echo 123
123
```

---

File:
```
1
2
3
```
```
$ > cat file
```
```
$ >
$ cat file
1
2
3
```
---

```
$ > make
```
```
$ make
> step 1
```
```
$ make
step 1
> step 2
```
```
$ make
step 1
step 2
> step 3
```
```
$ > 
$ make
step 1
step 2
step 3
```

I think this resembles what I tried to explain initially.
The output is printed regularly, I mean the way we read it, from step 1 to step 3, regular build process, but the carriage always returns to the top, instead of the bottom.
