### ISSUE TITLE
Tmux from MSYS2 doesn't work on Alacritty

### ISSUE THREAD

**Issue by techie-guy** [alacritty/alacritty#6716]
### System

OS: Windows
Version: alacritty 0.11.0 (8dbaa0b)

### Issue
tmux from msys2 doesn't work in Alacritty
But, running tmux in Mintty works fine

On Alacritty, I get this when I run `tmux`:
```
open terminal failed: not a terminal
```

**Comment by techie-guy** [comment]
Mintty has the `TERM` environment variable set to `xterm-256color`
So, I changed `TERM` to `xterm-256color` in Alacritty Config File.

But, it still doesn't work. I get the same output as above!

**Comment by chrisduerr** [comment]
There's nothing for Alacritty as a terminal emulator to do here. It's also not a setup I'm interested in offering support for.
