### ISSUE TITLE
Hints are *very* slow

### ISSUE THREAD

**Issue by notramo** [alacritty/alacritty#6717]
When there is scrollback text, hints take too much time to display.

I guess the cause is that Alacritty tries to compute hints for all of the scrollback text.
It should be lazy instead: compute only for the displayed text, and incrementally compute hints for new text on scroll.
In addition to usable response times, this would display better hints when scrolled back.

**Comment by kchibisov** [comment]
We compute the hints only for the visible text already. Are you sure that you're running the release build? Also, could you share the input and some terminal information? As well as some information about the setup you're running.

**Comment by chrisduerr** [comment]
Sounds like you might have defined a regex that is really slow. So if you're using a custom hint, please do share its regex.

**Comment by notramo** [comment]
This is the regex: `[~\w.\-/@:]{6,}`
CPU: Intel i5
Installed from Void Linux package manager.
Not always reproducible, sometimes it's fast (small amount of text in scrollback).

**Comment by kchibisov** [comment]
Could you provide the output to trigger it and settings? We need the entire scrollback, window dimensions, and `alacritty.yml`, so we can reliably reproduce it.

To capture everything, you can run `alacritty --ref-test`(will generate recording and a bunch of json files).

Be aware that sensitive data may be captured during that, so try to avoid anything special(you can inspect the `recording` manually, given that it's a text file).

**Comment by chrisduerr** [comment]
`\w` is always going to produce a pretty slow regex btw. I recommend replacing that with simpler alternatives. But yeah the scrollback amount shouldn't matter much unless the entire scrollback is one line.

**Comment by notramo** [comment]
After a little bit of testing it seems that I could notice a pattern.
When an Alacritty terminal is started, the hints are slow the first time. After that, it's fast, even if new content is displayed on the screen.
Here is a screencast of `base64 /dev/urandom`, on a freshly started terminal. Notice that the flow of text stops for half a second before the hints are first displayed. That's the lag after pressing the hint shortcut. It stops output rendering until it's displayed. Notice, that after the first time, the hints are displayed fast, without interrupting the rendering.

https://user-images.githubusercontent.com/26059643/219950073-25a9920c-f9f7-4a76-8d8a-dc3f82013e14.mp4

I noticed that after leaving a terminal idle for a while, the shortcut has the lag for the first time, but it's fast afterwards.

**Comment by kchibisov** [comment]
Maybe the issue is that your cpu drops frequence a lot, and for initial regex, we actually need to compile it, so you notice the lag? Because I think if you never use hints the regex won't even be compiled, and regex compilation is not that fast.

**Comment by notramo** [comment]
First time compilation makes sense, however, there are two questions:
- Why does it take time after leaving the terminal idle? Does it discard the compiled regex?
- `rg` (which is also written in Rust) searches for the regex in milliseconds on the entire file that is written to terminal, and Alacritty only uses portion of it.

**Comment by kchibisov** [comment]
>Why does it take time after leaving the terminal idle? Does it discard the previously already compiled regex?

We don't discard anything unless you reload config, I guess?

>rg (which is also written in Rust) searches for the regex in milliseconds on the entire file that is written to terminal, and Alacritty only uses portion of it.

Have you tried simplifying the regex, the only difference is that alacritty is using regex automata, so it might produce worse states.

Also, are you using musl on void linux?

**Comment by notramo** [comment]
Yes, I tested it on a musl Void Linux system.

**Comment by kchibisov** [comment]
Hm. That's actually will be a difference between us and `rg`, because `rg` is not using system memory allocator when using musl.

Could you try

```diff
diff --git a/alacritty/Cargo.toml b/alacritty/Cargo.toml
index b596563b..93a64aed 100644
--- a/alacritty/Cargo.toml
+++ b/alacritty/Cargo.toml
@@ -41,6 +41,7 @@ unicode-width = "0.1"
 bitflags = "1"
 dirs = "4.0.0"
 once_cell = "1.12"
+tikv-jemallocator = "0.5"
 
 [build-dependencies]
 gl_generator = "0.14.0"
diff --git a/alacritty/src/main.rs b/alacritty/src/main.rs
index d9d26022..f525bf79 100644
--- a/alacritty/src/main.rs
+++ b/alacritty/src/main.rs
@@ -49,6 +49,10 @@ mod scheduler;
 mod string;
 mod window_context;
 
+use tikv_jemallocator::Jemalloc;
+#[global_allocator]
+static GLOBAL: Jemalloc = Jemalloc;
+
 mod gl {
     #![allow(clippy::all)]
     include!(concat!(env!("OUT_DIR"), "/gl_bindings.rs"));

```

and building with `cargo build --release` (use rust provided by your system).

You'd need an extra `jemallocator` dependency installed in addition to what we have.

**Comment by chrisduerr** [comment]
As I've stated before `\w` is **really** bad for compiling a regex. That is not a surprise and working as expected. The one-time overhead of compilation is pretty much always worth the time it takes to compile the regex (which uses the exact same code `rg` does obviously).

When you say "after a long idle", is it possible you're just changing your configuration file in-between tests? Any update to the configuration file will clear the regex cache iirc.

**Comment by notramo** [comment]
If it's expected to take long time first time it's used, could you add a config option to eagerly initialize it in the background (without interrupting rendering) after startup?

@chrisduerr what would you recommend as replacement to `\w`, while retaining the same functionality?

**Comment by chrisduerr** [comment]
> If it's expected to take long time first time it's used, could you add a config option to eagerly initialize it in the background (without interrupting rendering) after startup?

I don't see why this would be necessary.

> @chrisduerr what would you recommend as replacement to \w, while retaining the same functionality?

Anything that doesn't take all of unicode into account really. It depends on what you actually want though. If this is an attempt to parse paths then you can maybe just use `[^ /]`?

**Comment by notramo** [comment]
I replaced the `\w` in the regex. It's fast now. I can accept it as a tradeoff.

I think it should be added to the documentation. What file would you recommend? (I would add it as a comment in the sample `alacritty.yml` file.)

**Comment by chrisduerr** [comment]
I don't think that should be much of a surprise and I'm sure there's plenty of other slow regex examples. It's just that `\w` is a very common and obvious one.
