### ISSUE TITLE
Default binding for CreateNewWindow also on Linux and Windows 

### ISSUE THREAD

**Issue by nomeata** [alacritty/alacritty#6719]
The `CreateNewWindow` action is an important and distinguishing feature of alacritty, at least in my opinion. So I found it a bit strange that in the default configuration it's only bound on MacOS. Of course everyone can configure it on their own, but in the interest of providing a great default experience, I'd suggest binding it on Linux as well.

Coming from gnome-terminal, I'd expect Ctrl-Shift-N. But any is better than none, I'd say :-)

**Comment by chrisduerr** [comment]
I don't think Linux users are generally expected to open new terminal windows through keybindings in their existing terminal emulator. That's just objectively less convenient than a global keybinding.

In macOS this was only added because it's a standard binding, but for Linux you really have better options.

**Comment by nomeata** [comment]
Hmm, the global key binding would open a fresh shell in `~` - a small but crucial difference to ”open a second terminal _in the current directory_”. To me, they are two different use cases (and hence need different key bindings). Also at least for GNOME users it's no less a standard binding as for OS X users.

Anyways, thanks for building alacritty! :-)

**Comment by chrisduerr** [comment]
Considering that I don't have a binding and see no need for it and @kchibisov also doesn't as far as I know, I think it's fair to say that this is not something **every** Linux user will find useful. As such, having it an opt-in binding seems like the correct choice.

**Comment by nomeata** [comment]
Hmm, I’d find that surprising. It’s one of those small productivity improvements – the alternative seems to be something like “Copy path → New Window → `cd ` → paste → Enter” or “New Window → `cd some/project/path/` → Enter”.

Is that not something you do quite often (maybe without noticing)?

But yes, I could well be wrong, or maybe it’s only specific work flows.

> but for Linux you really have better options.

What’s the better option? Is there a way to have a global keybinding that somehow notices the current working directory of the currently focused window, independent of whether it’s a terminal or something else? That would indeed be better…

**Comment by kchibisov** [comment]
>Considering that I don't have a binding and see no need for it and @kchibisov also doesn't as far as I know, I think it's fair to say that this is not something every Linux user will find useful. As such, having it an opt-in binding seems like the correct choice.

I use ctrl + shift + n and trigger it from time to time. The reason for it, because it inherits the active process directory.
