### ISSUE TITLE
0.12.0 release candidate 1 breaks some MacOS keys (like [] {}) on Portuguese Layout

### ISSUE THREAD

**Issue by pbgc** [alacritty/alacritty#6720]
Hi,

Trying 0.12.0 release candidate 1 on MacOS 12.6.3

The change:

alt_send_esc is now always set to true

reintroduced the problem described on #2280

using: 

option_as_alt: OnlyLeft

I can use the correct emacs keys on the terminal but I cannot type [] {} and some others from Portuguese keyboard layout that are typed using option and shift+option exactly like described on #2280 (that was solved by using alt_send_esc = false)

Thanks in advance

**Comment by pbgc** [comment]
On Emacs I cannot type some of the keys ([ ] { } @) at all!

It worked before with alt_sed_esc = false and

    { key: Key8, mods: Alt|Shift, chars: "\x7B" } # {
    { key: Key9, mods: Alt|Shift, chars: "\x7D" } # }
    { key: Key8, mods: Alt, chars: "\x5B" } # [
    { key: Key9, mods: Alt, chars: "\x5D" } # ]
    { key: Key2, mods: Alt, chars: "\x40" } # @


Directly on the terminal I can type [ and ] by pressing the key 3 times ... 
{  } and @ work

**Comment by chrisduerr** [comment]
I recommend picking `None` or `Both` for now. `OnlyLeft` and `OnlyRight` will still send escape for both alt keys which is something that will get fixed in a future update.

**Comment by pbgc** [comment]
@chrisduerr Thank's for you answer and your fantastic work on alacritty!

Unfortunately this makes alacritty completely unusable with Emacs for me and I guess for at least all international MacOS users.

- With `None` I would have to use ESC for meta instead of option and it would break my muscle memory (and of the majority of the users)
- With `Both` I can't type '[', '[', '{', '}' and '@' and I'm a developer :)

After several years happily using alacritty I'll have to search for another terminal ... I was having problems with 0.11 (the #62 ones) and was hoping they would be solved with 0.12 but I got bigger ones :)

**Comment by kchibisov** [comment]
>After several years happily using alacritty I'll have to search for another terminal ... I was having problems with 0.11 (the https://github.com/alacritty/alacritty/issues/62 ones) and was hoping they would be solved with 0.12 but I got bigger ones :)

>With None I would have to use ESC for meta instead of option and it would break my muscle memory (and of the majority of the users)

None is exactly as `alt_send_esc` before.

>Unfortunately this makes alacritty completely unusable with Emacs for me and I guess for at least all international MacOS users.

Yeah macOS has broken input model and there's no macOS developers who care. There's always an option to use US or ABC layouts which work just fine with new options.

**Comment by pbgc** [comment]
@kchibisov thank's for you answer

> None is exactly as alt_send_esc before.
Yes .. But I need alt_send_esc = false like it was possible before ... (check #2280)

> Or you wait for 0.13 where it'll be solved.
Yes I will return to alacritty for sure in 0.13! But meanwhile I will have to use another one (using iterm2 now)

**Comment by kchibisov** [comment]
>EDIT: even solved with 0.13 .. for me the solution I had with alt_send_esc = false + extra keys definitions was a lot better than having to use OnlyLeft and having to use left option for meta and right option to type those extra characters (not natural for me ..)

How does this work with e.g. iterm/terminal.app? It just no-one cares or uses macOS among alacritty contributors, so it's hard to figure out how this setting should behave. Most of the time it's just macOS has really bad input model for layouts other than US/ABS. Because with US layout I'm pretty sure you can input everything you want via the Alt key or you can have multiple keyboard layouts (it just happened that your native language has similar alphabet to English, but in reality you can't even input `Alt + [` for example, because you already use `Alt` to input `[`, so you're sort of limited from the start).

**Comment by pbgc** [comment]
@kchibisov with iterm2 was easy and fast:

First define what left option should do:

![Captura de ecrã 2023-02-20, às 00 47 32](https://user-images.githubusercontent.com/180825/219986310-4ce31077-47a6-46d8-b80d-27cef200105c.png)

Then define some keys to create some exceptions and for those extra keys accessed with option and shift+option

![Captura de ecrã 2023-02-20, às 00 48 15](https://user-images.githubusercontent.com/180825/219986321-9ceec30c-c3bb-4af8-89f2-640f08b0e68d.png)

A little similar to what I did before on alacritty:

`alt_send_esc = false`

and

`{ key: Key8, mods: Alt|Shift, chars: "\x7B" } # {
{ key: Key9, mods: Alt|Shift, chars: "\x7D" } # }
{ key: Key8, mods: Alt, chars: "\x5B" } # [
{ key: Key9, mods: Alt, chars: "\x5D" } # ]
{ key: Key2, mods: Alt, chars: "\x40" } # @`

and it worked like a charm ... before 0.11

**Comment by kchibisov** [comment]
Are you aware that you can do exactly that with alacritty? You have `ReceivedChar` binding just fine to circumvent that? So you bind `Alt + Shift + 8` to do `ReceivedChar` and it'll be bypassed.

**Comment by kchibisov** [comment]
I know that those bindings broke with `0.11` but they should be fixed with new options in `0.12`.

**Comment by pbgc** [comment]
> Are your bindings section not working or I don't understand that? Like it should work just fine now...

those key bindings are working well! The problem is that `option` is not being interpreted as meta in Emacs ... `ESC` is

**Comment by kchibisov** [comment]
But `OptionAsAlt::Both/Left/Right` should produce `\x1b` for such keys, when pressing e.g. `Alt + a`? So if you type `Alt + a` you should get `^[a`. (you can test in shell by running `cat` and typing in to it with alt).

**Comment by kchibisov** [comment]
I'm pretty sure that the actual input from such keys should be exactly the same between iterm's option you specify and the one we have(I've tested it to be the same with US layout).

**Comment by kchibisov** [comment]
Also, are you sure that you're adding it correctly.

```
window:
    option_as_alt: OnlyLeft
```

**Comment by pbgc** [comment]
I have:

`option_as_alt: Both`

and

  - { key: Key8,      mods: Alt,            chars: "\x5B"                    }
  - { key: Key9,      mods: Alt,            chars: "\x5D"                    }
  - { key: Key2,      mods: Alt,            chars: "\x40"                    }
  - { key: Key8,      mods: Alt|Shift,      chars: "\x7B"                    }
  - { key: Key9,      mods: Alt|Shift,      chars: "\x7D"                    }


and I can't type those chars! It's the same problem I had before and report it in #2280 and the solution (for me ans several others like you can see on the issue) was to change to:
`
alt_send_esc = false`

**Comment by pbgc** [comment]
With
 `option_as_alt: OnlyLeft`

I can type those chars in the terminal without any problem... just not in Emacs! (Like I said before) and I live in emacs ...

**Comment by kchibisov** [comment]
Hm, maybe emacs wants something special then, if those chars produce correct escape sequences? I think we had issues with emacs before. Just to clarify, you get `^[a` when pressing `LALT + a`?

**Comment by pbgc** [comment]
Yes. Typing `Left Option + a` into cat gives: `^[a`

**Comment by kchibisov** [comment]
What keybindings are not working for you inside the `emacs`? It seems like `ESC` is correctly send by alacritty now with your layout?

**Comment by pbgc** [comment]
in emacs everything is working well unless the chars [  ]  {  }

I attach my alacritty.conf and a event log where I tried to type those chars (hope It's not full of garbage ...)

[files.zip](https://github.com/alacritty/alacritty/files/10778657/files.zip)

**Comment by kchibisov** [comment]
@pbgc Ah, I see. Your bindings are incorrect, I'd suggest to run with `alacritty --print-events` and rebind the keys. So instead of:

```
- { key: Key8, mods: Alt, chars: "\x5B" }
```

you should do

```
- { key: LBracket, mods: Alt, chars: "\x5B" }
```

You can manually figure out what to bind via running with `alacritty --print-events | grep -i keyboardinput`. You can see `virtual_keycode` and rebind by it.

**Comment by pbgc** [comment]
@kchibisov WOW .. It's seems so! I changed the one you wrote and it worked!

But something as changed ... because It worked before like I had and not only for me .. for a lot of others and other languages .. like you can see here:

https://github.com/alacritty/alacritty/wiki/Keyboard-mappings

But I will follow your advice and use print-events to try to redefine correctly!

THANK YOU very much for taking your time to help me!!

**Comment by kchibisov** [comment]
Yeah, the keyboard keys that you get might actually got changed in upstream library. I'll try to write up a release note about that. It won't be an issue with `0.13` where all the keybinding code will be changed and the way you bind them.

I'll try to write up a release note notice on how to proceed with the update, since as you may see you have the exact same experience as with iterm2 wrt `Alt` now, it just you bind the wrong thing.

**Comment by pbgc** [comment]
> since as you may see you have the exact same experience as with iterm2 wrt Alt now, it just you bind the wrong thing.


Yes! already redefined the keys and everything is perfect now!! I tried so many things for hours and never suspected that it were the key definitions (that always worked before) that were wrong now ! 
Thank you very much for your help and your time! I'm very happy! I can keep using alacritty without having to wait for 0.13! :)

**Comment by kchibisov** [comment]
@pbgc is this clear https://github.com/alacritty/alacritty/releases/tag/v0.12.0-rc1 if you read the 'macOS Alt/Option situation'?

**Comment by kchibisov** [comment]
@chrisduerr I'll pin this issue for a while, so everyone with similar problem could likely just read this issue and figure out with the help of our release page what to do and how to update.

**Comment by pbgc** [comment]
> is this clear https://github.com/alacritty/alacritty/releases/tag/v0.12.0-rc1 if you read the 'macOS Alt/Option situation'?

yes. it's very clear and should help the MacOS users with non US keyboard layouts to solve the problems they will have when upgrading to 0.12

Thank you again!
