### ISSUE TITLE
Espanso not Running = unexpected exit code from worker -1073741571

### ISSUE THREAD

**Issue by orderlyBolt** [alacritty/alacritty#6723]
Hi,

Everytime i start of espanso it returns this error, and I cant seem to to find a way to solve it with Ruts, how do i do that?

### System

OS: Windows 11
Version: `alacritty --version` output

### Logs

09:45:25 [daemon(7296)] [INFO] reading configs from: "C:\\Users\\[username]\\AppData\\Roaming\\espanso"
09:45:25 [daemon(7296)] [INFO] reading packages from: "C:\\Users\\[username]\\AppData\\Roaming\\espanso\\match\\packages"
09:45:25 [daemon(7296)] [INFO] using runtime dir: "C:\\Users\\[username]\\AppData\\Local\\espanso"
09:45:25 [daemon(7296)] [INFO] system info: Windows v10 (22621) - kernel: 22621
09:45:25 [daemon(7296)] [INFO] watching for changes in path: "C:\\Users\\[username]\\AppData\\Roaming\\espanso"
09:45:25 [daemon(7296)] [INFO] espanso version: 2.1.8
09:45:25 [daemon(7296)] [INFO] spawning the worker process...
09:45:25 [daemon(7296)] [INFO] binded to named pipe: \\.\pipe\espansodaemonv2
09:45:25 [worker(21624)] [INFO] reading configs from: "C:\\Users\\[username]\\AppData\\Roaming\\espanso"
09:45:25 [worker(21624)] [INFO] reading packages from: "C:\\Users\\[username]\\AppData\\Roaming\\espanso\\match\\packages"
09:45:25 [worker(21624)] [INFO] using runtime dir: "C:\\Users\\[username]\\AppData\\Local\\espanso"
09:45:25 [worker(21624)] [INFO] system info: Windows v10 (22621) - kernel: 22621
09:45:25 [worker(21624)] [INFO] binded to named pipe: \\.\pipe\espansoworkerv2
09:45:25 [worker(21624)] [INFO] using Win32AppInfoProvider
09:45:25 [worker(21624)] [INFO] monitoring the status of the daemon process
09:45:25 [worker(21624)] [INFO] using Win32Source
09:45:26 [daemon(7296)] [ERROR] received unexpected exit code from worker -1073741571, exiting

Error Message:
09:49:54 [daemon(16732)] [ERROR] received unexpected exit code from worker -1073741571, exiting
thread 'main' panicked at 'failed to launch daemon: unexpected error, 'espanso daemon' returned a non-zero exit code.', espanso\src\cli\launcher\mod.rs:213:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by chrisduerr** [comment]
Clearly not an Alacritty error.
