### ISSUE TITLE
Setting configuration options for the current session (not writing to alacritty.yml)

### ISSUE THREAD

**Issue by holtkampjs** [alacritty/alacritty#6728]
### System

OS: Windows 10 
Environment: Powershell 7.0.3
Version: alacritty 0.11.0 (8dbaa0b)

### Question/Possible Feature Request

Is there an established way to change alacritty configuration options for the current session? Specifically I'm trying to change the opacity of my current session without editing the alacritty.yml file. 

I've attempted to run: 
`PS> alacritty --option window.opacity=1`

The result is that a new alacritty terminal opens with the option applied which is not my desired outcome. 

If there is not a current way to do this, I would suggest implementing a flag like `--current` or `--current-session` to allow users to temporarily apply configuration options.

**Comment by kchibisov** [comment]
Not on windows, unfortunately.
