### ISSUE TITLE
how to set default powershell version?

### ISSUE THREAD

**Issue by jinfagang** [alacritty/alacritty#6730]
how to set default powershell version?

how to setup the default powershell version I have powershell 7 install powershell 5, dfault is 5 how ot switch to 7

**Comment by kchibisov** [comment]
https://github.com/alacritty/alacritty/blob/f01dea8643e2956d2480ee12c3e5ee960944a49d/alacritty.yml#L453

**Comment by kchibisov** [comment]
Just specify path to v7 version of it.
