### ISSUE TITLE
about Ctrl+C Copy or SIGINT signal?

### ISSUE THREAD

**Issue by jcleng** [alacritty/alacritty#6734]
```
OS: Linux NixOS 22.05 (Quokka)
Version: `alacritty 0.10.1 ()`
Linux/BSD: X11, KDE
```
Can think of kconsole like ctrl + c copy text, when running with the program, such as top, is to send SIGINT signal, how the configuration file it

my config,can use `ctrl+shift+c` to  send SIGINT signal.
```
key_bindings:
  - { key: V,              mods: Control,                   action: Paste            }
  - { key: C,              mods: Control,                   action: Copy             }
```

**Comment by kchibisov** [comment]
'smart' copy is rejected. Use dedicated copy keys or remap you r SIGINT to ctrl + shift + c.

**Comment by jcleng** [comment]
call it `'smart' copy`, i saw it issues/1919
