### ISSUE TITLE
multiple instance on dock in macos

### ISSUE THREAD

**Issue by piotr-sikora-v** [alacritty/alacritty#6735]
I know there is a https://github.com/alacritty/alacritty/issues/607
but any other solution ?
In example, kitty terminal I can open many windows and only one show in dock (also with one instance mode).
There is any option to open alacritty via skhd many time and don't have more than one in dock?

Thanks in advanced

**Comment by kchibisov** [comment]
If you look at the #607 the issue is closed, likely because it was done.

>There is any option to open alacritty via skhd many time and don't have more than one in dock?

Try `alacritty msg create-window || alacritty` if you're doing yabai setup. Or press `Command + N`(on the latest rc it should use `CreateNewWindow` action instead of `SpawnNewInstance`).
