### ISSUE TITLE
Not all emojis are rendered correctly

### ISSUE THREAD

**Issue by D3vil0p3r** [alacritty/alacritty#6736]
I'm testing several emojis from https://emojipedia.org and on Alacritty some of them don't work (whereas they work on other terminal emulators like kitty).

For example the crossed swords ⚔️, the dagger 🗡️ and the shield 🛡️ are not displayed correctly, while other emojis like the missile 🚀 are showing correctly.

Here a screenshot of the representation for these 4 emojis:
![image](https://user-images.githubusercontent.com/83867734/221382004-69a22245-d80d-4587-a7b7-cc0d0866a142.png)

Furthermore, the usage of wrong rendered emojis generate additional spaces at the end of the strings when you press UP Arrow on the keyboard for retrieving this string from the previous launched strings.

Could you please fix this issue for Alacritty?

### System

OS: Linux
Version: 0.11.0 (8dbaa0bb)
Linux/BSD: X11 and Wayland, GNOME 43

**Comment by chrisduerr** [comment]
Working as intended.

**Comment by D3vil0p3r** [comment]
> Working as intended.

It is not working as intended, because some emojis are not rendered as emojis, and this wrong rendering causes additional spaces at the end of the string when the run string is retrieved by UP arrow. You cannot close the issue as completed. It is a bad approach.

Kitty emoji rendering (this is "working as intended"):
![image](https://user-images.githubusercontent.com/83867734/221383542-c606a94a-3dab-4651-8d98-11aa5b36d771.png)
