### ISSUE TITLE
Link detection does not work properly with wrapped text inside a tmux split

### ISSUE THREAD

**Issue by olalonde** [alacritty/alacritty#6737]
### System

OS: macos
Version: `alacritty 0.10.1 (2844606)`

<img width="271" alt="Screen Shot 2023-02-25 at 6 57 46 PM" src="https://user-images.githubusercontent.com/416585/221383404-4e484bc1-91f0-420e-ac61-bf845a2e23cb.png">

Notice the `com` which is wrapped to a new line is not selected.

It works as expected when not in tmux split.

<img width="183" alt="Screen Shot 2023-02-25 at 6 59 48 PM" src="https://user-images.githubusercontent.com/416585/221383452-09372ca5-7f97-4a16-a7dc-ac6c74aa00cf.png">

**Comment by chrisduerr** [comment]
Correct, because how would it? We support the hyperlink escape sequence and that's the best we can do.

**Comment by olalonde** [comment]
But why does it work when not in tmux? Could it be fixed by tmux?

It seems obvious to you because you know the internal  of terminal emulators but it's not obvious to us mere mortals.

**Comment by olalonde** [comment]
Ah I guess in the second case, alacritty sees this as
```
                                          |http://github.
                                          |com
```

vs 

```
http://github
.com
```

Correct? So the solution is to use the hyperlink escape sequence you mentioned?

**Comment by chrisduerr** [comment]
> But why does it work when not in tmux? Could it be fixed by tmux?

Yes, tmux could recognize URLs and escape them by itself.

It works outside of tmux because you're not running tmux. Alacritty has zero idea where tmux's sub-windows are located. Alacritty just sees it as one giant blob of text.
