### ISSUE TITLE
Known error fired on every config reload

### ISSUE THREAD

**Issue by d249u7** [alacritty/alacritty#6740]
This is not a bug, rather a question. I sync my configs between my Mac and Linux devices. 

If `window.decorations` is set to `transparent`, it works on Mac and doesn't work on Linux. **Which is documented and fine.**

However, whenever I start Alacritty on Linux, I get a giant error message every time.

`Config error: decorations: unknown variant 'transparent', expected one of 'Full', 'None'`

**Is there any way to suppress this error?**

### System

OS: Linux
Version: alacritty 0.11.0 (8dbaa0bb)
Linux/BSD: X11, KDE

**Comment by chrisduerr** [comment]
Have you considered using separate configuration files? Imports that do not exist are not warned about, so you can have platform-specific configuration files.
