### ISSUE TITLE
Alacritty incorrectly converting backslash to escape character

### ISSUE THREAD

**Issue by acarl005** [alacritty/alacritty#6741]
### System

OS: MacOS Ventura 13.1 (22C65)
Version: alacritty 0.13.0-dev (bf587480)
Shell: bash 5.2.15

### Description

![Screenshot 2023-02-27 at 1 58 57 PM](https://user-images.githubusercontent.com/8334252/221661576-f8f475fd-5b02-4926-bd99-bb42659fdce8.png)

Top left: iTerm
Top right: Terminal.app (default MacOS terminal)
Bottom left: Alacritty
Bottom right: Hyper.js

Alacritty is incorrectly converting `\033` into an ascii ESC character. This should not be happening when `echo` is called without the `-e` option.

Interestingly, the problem only occurs when I run Alacritty after building with [these steps](https://github.com/alacritty/alacritty/blob/master/INSTALL.md#macos) using `make app`. The problem goes away when I run the app with `cargo run`.

**Comment by kchibisov** [comment]
alacritty has nothing to do with your shell.
