### ISSUE TITLE
Unable to disable horizontal scrolling via the config

### ISSUE THREAD

**Issue by TheDen** [alacritty/alacritty#6747]
I sometimes use the trackpad to scroll up/down in vim or selection via a vert block. However, now with horizontal scrolling I can't use the trackpad only scroll vertically, since slight x-axis movements break this vertical-only flow.

### System

OS: macOS
Version: alacritty 0.12.0-rc1 (9de64a5)

**Comment by chrisduerr** [comment]
Can you try the latest master? The X-Axis sensitivity has been reduced significantly.

**Comment by TheDen** [comment]
Tested with build off `master` and it's perfect 👍
