### ISSUE TITLE
option_as_alt config error in rc 0.12.0-rc1

### ISSUE THREAD

**Issue by pitoniak32** [alacritty/alacritty#6749]
## Issue Description:
I updated from the latest release `0.11.0` to `0.12.0-rc1` because I was looking to get access to the `option_as_alt: Both` config option on my mac for using it as a Meta key with `zellij`.

### Current Behavior:
Config errors, and not able to use option key as alt.

### Expected Behavior:
Ability to use new option without config errors.

### System

OS: macOS Monterey 12.6.1 (Apple M1 Chip)
Version: Version 0.12.0-rc1 (1)

### Logs
<img width="519" alt="Screen Shot 2023-03-01 at 11 42 21 AM" src="https://user-images.githubusercontent.com/84917393/222205643-3d4c97ac-e430-4fbb-a92a-3bd259e7fd40.png">

**Comment by kchibisov** [comment]
I doubt your editor knows about which options alacritty supports.

Not sure how you test the behavior as well.

**Comment by mkatychev** [comment]
@kchibisov @pitoniak32   this is most likely a json schema configuration that's being run through a YAML lsp:
[json-schema spec](https://json-schema.org/)
[json-schema tore](https://www.schemastore.org/json/)
And the schema in question (found through the schema store above):
https://github.com/distinction-dev/alacritty-schema/

**Comment by Freed-Wu** [comment]
Comes from <https://github.com/distinction-dev/alacritty-schema/issues/3>.

How about move [alacritty config json schema](https://github.com/distinction-dev/alacritty-schema) to alacritty repo in order to make this json schema keep latest with every publishing of new version with alacritty?
