### ISSUE TITLE
Alacritty not rendering ç but ć instead

### ISSUE THREAD

**Issue by andradei** [alacritty/alacritty#6754]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux
Version: alacritty 0.11.0 (8dbaa0bb)
Linux/BSD: X11 (Gnome 43)

### Issue

I want to render cedilla `ç` with <kbd>'</kbd>, <kbd>c</kbd>. The system is configured to do so and all applications work except for Alacritty.

I followed #4549 but it didn't work.

**Comment by kchibisov** [comment]
Copied from issue title.

![picture](https://user-images.githubusercontent.com/27620401/222988657-ac433de1-1887-4e15-8025-4e60913438d9.png)


I'd assume your font has bad hints for standalone `'`, because common GUI apps doing unicode normalization, so it could be hidden.

**Comment by andradei** [comment]
@kchibisov Copying works fine, my title is misleading perhaps so I just updated it. What I mean is: when I type `'` followed by `c`, I should get cedilla `ç` , but get acute c `ć` instead.

**Comment by andradei** [comment]
Extra things I had to do after following #4549:

1. Add `export $XMODIFIERS=@im=ibus` to my `~/.zshrc`
2. Install `ibus` (in my system it was `yay ibus`)
