### ISSUE TITLE
Does Alacritty Runs Native On Apple Silicon Chip?

### ISSUE THREAD

**Issue by Cugatay** [alacritty/alacritty#6755]
Hey, I just switched to Alacritty, and I'm amazed by its speed. Does it work natively in Apple Silicon chip, or will there be an update about it? And just want to ask, how is the community on MacOS, are there a considerable number of MacOS contributors, or are we using Linux with programmer socks :)

**Comment by kchibisov** [comment]
The `app` file destributed is universal binary, as in works natively on aarch64. You can always build for arm64 yourself as well if you want to.

**Comment by Cugatay** [comment]
Wow, didn't wait for the answer that fast. I had some concerns about switching but now I'm sure that I'm doing the right thing. Thanks a lot
