### ISSUE TITLE
scrollbar please

### ISSUE THREAD

**Issue by Footsiefat** [alacritty/alacritty#6756]
Switched to from konsole due to performance benifits but its missing a scrollbar which is pretty much a core functionality these days.

Where in the config do I go to enable a scrollbar? I need a way to scroll quickly to the top of the page without hurting my hand on the trackpad.

**Comment by kchibisov** [comment]
>Where in the config do I go to enable a scrollbar? I need a way to scroll quickly to the top of the page without hurting my hand on the trackpad.

That's sounds controversial, scrollbar is mouse controlled.

If you want to do fast keyboard driver scrolling, use `Vi` mode, it has some kind of scrollbar.

Otherwise duplicate #775.

**Comment by Footsiefat** [comment]
It's a standard feature, how is it controversial?

Just opened up Vi mode and I can't see no scrollbar.

**Comment by kchibisov** [comment]
It'll show you a counter in top right corner, it's controversial because it just takes terminal space without providing any useful value, other than for mouse users.

You can scroll way faster with keyboard bindings anyway.

**Comment by Footsiefat** [comment]
How would I make it scroll to the start of each command? or scroll in larger chunks like 100 lines at a time etc. thats the main issue is that scrolling through large outputs hurt my hand with touchpad

**Comment by kchibisov** [comment]
>How would I make it scroll to the start of each command?

For this scrollbar won't do you anything. See https://github.com/alacritty/alacritty/pull/5860

>or scroll in larger chunks like 100 lines at a time etc.

PageUp/Down, + you may duplicate the actions, to increase the amount of page up/downs per press.

**Comment by Invertisment** [comment]
> Switched to from konsole due to performance benifits

So you want the font to be using the scroll from UI library that removes performance but you only want performant part...?
Why not instead use the same `konsole` but try to fork it to improve performance?

**Comment by Invertisment** [comment]
I used `mate-terminal` and it was very fast. I think you could try it.

**Comment by kchibisov** [comment]
The fast is subjective measure, mate terminal is yet another VTE based one, which can't even render at high refresh rate to not lag why I'm typing, but it's not like mate is bad, it's just what it's.

Though, regardless, just use what you like more, nothing is forcing you to use anything.

**Comment by kchibisov** [comment]
>It doesn't lag for me even slightly. I don't know why your configuration has this lag.

Set repeat rate to some high value, like 60 keys per second. I mean I test various vte terminals for years, they lag the same for years on all of my systems(and don't ever print long strings into them, they blow up), but it's offtopic here, sorry.

**Comment by PukPukov** [comment]
The feature is not controversial, as nothing forces user to enable it. But lack of this feature certainly is, because you cant enable even if you want to.

**Comment by eallion** [comment]
I wasted a lot of time trying to figure out how to configure the scrollbar until I saw this issue.

`controversial` is THE fxxking controversial.

**Comment by PinkSerenity** [comment]
> scrollbar doesn't mean that it's slow though, it's an instant drawing element that takes nothing from perf. the only issue with that is that it reserves extra column.

How about having the scrollbar only appear temporarily when the cursor is near the edge? Then the column wouldn't be reserved.
