### ISSUE TITLE
window border width options

### ISSUE THREAD

**Issue by eskevv** [alacritty/alacritty#6759]
Looking at window decorations it would be nice to remove the titlebar, but keep the border at a selected width. This is mostly for windows platforms and would look similar to how cmder looks with minimal settings. It would add a little bit more contrast between windows without the need of a titlebar and is an overall visual improvement. If this is already possibly through other means I am not yet aware of it, but it would be nice if it came with alacritty.

**Comment by chrisduerr** [comment]
Not interested in adding additional decoration options, especially because this is not a standardized server-side decoration on most platforms I'm aware of.
