### ISSUE TITLE
tmux used as default shell and sent to background, cannot get back to tmux client

### ISSUE THREAD

**Issue by SyedFasiuddin** [alacritty/alacritty#6764]
I have this in my config file
```yml
shell:
  program: /opt/homebrew/bin/tmux
  args:
    - new
    - -A
    - -s
    - MASTER
```
In tmux we have `prefix <C-z>` keybinding which will send tmux to background, if tmux were launched from shell then we would get back to the shell and use `fg` to get back to the tmux client. But when alacritty loads tmux as its shell there is nothing to get back to when `prefix <C-z>` is pressed and so I get a blank screen:
<img width="674" alt="image" src="https://user-images.githubusercontent.com/66054777/224027435-619aa090-a5f0-48d4-b467-87dc452879f8.png">

<img width="667" alt="image" src="https://user-images.githubusercontent.com/66054777/224028601-83b96488-cc19-41b3-b21d-bd7965697712.png">

and `fg` doesn't work here, I have to quit and restart alacritty to get back to work. 

This `prefix <C-z>` was not pressed intentionally but accidentally and only then did I discover that this keybinding in tmux sends the client to background.

### System

OS: macOS
Version: `alacritty 0.11.0 (8dbaa0b)`

**Comment by chrisduerr** [comment]
If you want a shell with job control, start a shell. If you tell Alacritty that you don't want it to launch a shell, you shouldn't be surprised when you're then promptly SoL after suspending your shell.

If you don't like a tmux binding, I'm sure you can unmap it.
