### ISSUE TITLE
Font width rendering issue?

### ISSUE THREAD

**Issue by cr0t** [alacritty/alacritty#6768]
There is a difference in rendering fonts between Kitty and Alacritty – Kitty is rendering characters a bit wider than Alacritty.

I tried this with a couple of ones (also with system-installed Menlo), got similar results. Check the screenshots:

| Kitty | Alacritty | Diff |
|-------|-----------|------|
| <img width="1392" alt="kitty" src="https://user-images.githubusercontent.com/113878/224444071-4409bd64-c584-41ce-8647-ce413319bc11.png"> | <img width="1392" alt="alacritty" src="https://user-images.githubusercontent.com/113878/224444087-894c8537-875e-42f3-8b4f-b89c9767e045.png"> | ![kitty_alacritty_diff](https://user-images.githubusercontent.com/113878/224444120-698e4278-9a3f-4cc3-a2a8-ab32020175e4.png) |

I tried to set `modify_font cell_width 95%` option in Kitty, and it _almost_ fits the width of Alacritty's width of rendering characters of the font, but it leads to some issues on Kitty rendering side, and it appears as a hack.

Can it be an issue in how Alacritty rendering fonts? Or vice versa – Kitty's one?

_Sorry if that's an annoying request._

### System

OS: macOS
Version: alacritty 0.12.0-rc2 (e1bc53a)

### Logs

N/A

**Comment by chrisduerr** [comment]
Alacritty has zero desire to match Kitty's font rendering. If they're different, then that's just the way it's gonna be.

**Comment by kchibisov** [comment]
I guess assume that the issue is that you can't directly match the metrics between the terminal, as in one may use pt other px some conversion in between and so on.

**Comment by cr0t** [comment]
@kchibisov it's just a bit strange the [kerning](https://en.wikipedia.org/wiki/Kerning) (spacing between the characters) is different, which leads to shorter words than in Kitty.

I thought that it might be done intentionally somewhere in Alacritty's code (or vice versa – in Kitty).

**Comment by kchibisov** [comment]
>@kchibisov it's just a bit strange the kerning (spacing between the characters) is different, which leads to shorter words than in Kitty.

that's not what kerning is though and do you know that the font has kerning tables at all? Most of them don't have it.

Kerning only exists for non-monospaced fonts.

**Comment by cr0t** [comment]
> Kerning only exists for non-monospaced fonts.

Then it's even stranger to me that the same font (I tried different ones) renders with different width for characters with the same height (and line-height) :)

**Comment by kchibisov** [comment]
Are you sure that the font size is the same?

**Comment by cr0t** [comment]
Check the diff image that I posted in the original text of the issue.

Of course, I can't be 100% sure, but as to me, lines start the same, and then they start to get longer in Kitty (or stay shorter in Alacritty, depends on the perspective).

**Comment by kchibisov** [comment]
No, I mean do you use the same **NUMBER** for font size in the config of both kitty in alacritty.

**Comment by cr0t** [comment]
> No, I mean do you use the same NUMBER for font size in the config of both kitty in alacritty.

Ah, yes, the same font-size, 13.

[kitty.conf](https://github.com/cr0t/dotfiles/blob/master/dot.config/kitty/kitty.conf#L9)

[alacritty.yml](https://github.com/cr0t/dotfiles/blob/master/dot.config/alacritty/alacritty.yml#L14)

**Comment by kchibisov** [comment]
Could you compare with `Terminal.app`?

**Comment by cr0t** [comment]
Sure.

So, I set the same font, same font-size in Terminal.app and below is the “diff” images:

| Terminal.app vs. Alacritty | Terminal.app vs. Kitty |
|----------------------------|------------------------|
| <img width="1367" alt="image" src="https://user-images.githubusercontent.com/113878/224479758-dfa69c5e-757a-48c3-b284-8fae8c4f3962.png"> | <img width="1403" alt="image" src="https://user-images.githubusercontent.com/113878/224479797-b7f0dfd8-e3a8-45b4-9be6-77dc0947abdd.png"> |

_We can see, that in Terminal.app we have slightly different line height, but the width of characters is the same as in Kitty, not in Alacritty._

**Comment by kchibisov** [comment]
I think it could be 1px difference.

Could try

```
font:
  offset:
    x: 1
```

**Comment by cr0t** [comment]
@kchibisov yes, you're right! Now, it's ideally fit each other (with little exception for Terminal.app and line-height).

`offset` helped:

| Terminal.app vs. Alacritty (opacity 50%) | Kitty vs. Alacritty (with offset) (divide) |
|------------------------------------------|--------------------------------------------|
| <img width="1520" alt="image" src="https://user-images.githubusercontent.com/113878/224480339-e989fe85-ef99-4ea8-9844-7bc55043e291.png"> | <img width="1331" alt="image" src="https://user-images.githubusercontent.com/113878/224480382-1bf4d124-2071-4735-a8bc-ef5b146c14a5.png"> |

If Alacritty team decides to set this offset by default, please, let us know! :)

**Comment by cr0t** [comment]
And thanks for pointing me to the solution, @kchibisov!

**Comment by dcousens** [comment]
I had the opposite problem, needing a `x: -1` offset when compared with `st`, thanks for help
