### ISSUE TITLE
Allow using X11 color names for color options in config

### ISSUE THREAD

**Issue by johannes-schmatz** [alacritty/alacritty#6771]
It would be nice if the color parsing (from the config) allows using X11 color names.
Currently it's neccessary to copy the hex value in directly.
A config like this doesn't work:
```yaml
colors:
  normal:
    red: 'red3'
```

The list of X11 color names is available [here](https://gitlab.freedesktop.org/xorg/app/rgb/-/blob/master/rgb.txt).

This would require to add X11 color parsing here:
https://github.com/alacritty/alacritty/blob/53322bef612be06af7381b4ca1979389a01fab9f/alacritty_terminal/src/term/color.rs#L155-L157
The error message that tells people that it expects hex inputs shoud then also be updated.
https://github.com/alacritty/alacritty/blob/53322bef612be06af7381b4ca1979389a01fab9f/alacritty_terminal/src/term/color.rs#L122

**Comment by kchibisov** [comment]
alacritty is a cross platform terminal emulator, not an X11 terminal emulator.

**Comment by johannes-schmatz** [comment]
> cross platform terminal emulator

the "web" colors are also derived from the X11 colors, so even non-X11 users would profit from it.

**Comment by kchibisov** [comment]
I mean even if we add w3c colors, I don't think anyone will ever use them.

Most users simply use color schemes with their own colors, so the use for such things is fairly limited.

**Comment by johannes-schmatz** [comment]
and here I am with the pain of converting decimal (the way they are in the X11 list) into hex...

**Comment by kchibisov** [comment]
Yeah, you're the first one in 5 years according to my memory, so it's an exception. You'll need to convert at max 16 colors, the indexed colors are the same as in e.g. xterm.
