### ISSUE TITLE
I have --JUST A FEW--- questions

### ISSUE THREAD

**Issue by AxewBoTX** [alacritty/alacritty#6774]
### System
OS: Windows 11
Version: Alacritty 0.11.0

### Issue
I have a few questions
1. How can I make the background of alacritty blue
2. How can I make the corners rounded
3. How can I make it so that the alacritty is by default in the center of the screen.
4. How can I change the padding of different sides different like different padding for left, right, top and bottom

PLEASE HELP
Thanks! ^_^

**Comment by kchibisov** [comment]
>How can I make the background of alacritty blue

See the `colors` section in the `alacritty.yml`.

> How can I make the corners rounded

You window manager should provide you with that, not us.

>How can I make it so that the alacritty is by default in the center of the screen.

You set the position in the config, though, you can't refer to the center of the monitor.

>How can I change the padding of different sides different like different padding for left, right, top and bottom

The only option is `dynamic_padding` inside the window section. There's already issue open for configurable padding.

**Comment by AxewBoTX** [comment]
>See the colors section in the alacritty.yml.

I meant to ask about how can I make my terminal blur, I accidentally typed blue

>You window manager should provide you with that, not us.

Every single application I have ever opened on this computer had rounded corners, except alacritty. I dont see how my window manager is in the wrong for this

**Comment by chrisduerr** [comment]
> I meant to ask about how can I make my terminal blur, I accidentally typed blue

Some DEs/compositors might allow you to do this, but Alacritty does not have such an option.

**Comment by AxewBoTX** [comment]
about the round corners?

**Comment by chrisduerr** [comment]
Oh I just pretended not to read that. I don't care about round corners or any issues related to them. If your window manager can't do it automatically, Alacritty will never do it by itself.

**Comment by AxewBoTX** [comment]
my window manager does it when the decorations are set to full, not when decorations are set to none because alacritty removes the border, there should be a way to customize the border radius

**Comment by d2rgaming-9000** [comment]
lol

**Comment by d2rgaming-9000** [comment]
i'd love to have round corners, but hey you know what, i dont think its going to solve our first world problems; so i can live w/ that. esp it looks like the existing devs are already overwhelmed as is.

Oh well.

**Comment by d2rgaming-9000** [comment]
i'd love to have round corners, but hey you know what, i dont think its going to solve our first world problems; so i can live w/ that. esp it looks like the existing devs are already overwhelmed as is.

Oh well.

**Comment by MelvinQc542** [comment]
Ha! Ha!  Thank you for this thread.

Although this seems like a closed thread, I believe I understand the "round edges" question.

In the [window] section of the alacritty.toml file, there are some predefined options (I know of).  When using decorations="None", it does square off the edges.  But I use decorations = "Buttonless" - and it shows "rounded edges".

If it solves the dispute, I've contributed to "some good", today.

And...   BTW - Alacritty is my preferred terminal - so thank you!
