### ISSUE TITLE
Wiki Update Suggestion, RE: Running on MacOS

### ISSUE THREAD

**Issue by aburd** [alacritty/alacritty#6775]
To get downloaded alacritty binary to work on Apple M2, Ventura, I had to take one extra step.

https://github.com/aburd/alacritty/wiki/Self-Signing-Alacritty-on-macOS#removing-the-applequarantine-attribute

I felt this could help others, so I added the information in my fork of the wiki above.
Unfortunately I can't submit a PR for wiki, so I'm opening this issue.

**Comment by chrisduerr** [comment]
You're not the first one using this command to remove the quarantine flag, so I've added it to the official wiki, thanks.
