### ISSUE TITLE
[macOS Ventura] application refuses to run completely

### ISSUE THREAD

**Issue by keltia** [alacritty/alacritty#6777]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: macOS Ventura, latest 13.2.1
Version: `alacritty --version` output

0.11, can't show the precise stuff because of this very problem.

This is the version you get with Homebrew:
```
260 [14:34] roberto@mac-studio:src/drone-gencsv> brew install alacritty
==> Downloading https://github.com/alacritty/alacritty/releases/download/v0.11.0/Alacritty-v0.11.0.dmg
Already downloaded: /Users/roberto/Library/Caches/Homebrew/downloads/a92d1e0bfe7edda684ff7192829d0b59ac82da6b17dd98959ee9f614052b5d40--Alacritty-v0.11.0.dmg
==> Installing Cask alacritty
==> Moving App 'Alacritty.app' to '/Applications/Alacritty.app'
==> Linking Binary 'alacritty' to '/opt/homebrew/bin/alacritty'
==> Linking Binary '_alacritty' to '/opt/homebrew/share/zsh/site-functions/_alacritty'
==> Linking Binary 'alacritty.bash' to '/opt/homebrew/etc/bash_completion.d/alacritty'
==> Linking Binary 'alacritty.fish' to '/opt/homebrew/share/fish/vendor_completions.d/alacritty.fish'
==> Linking Binary 'alacritty' to '/Users/roberto/.terminfo/61/alacritty'
==> Linking Binary 'alacritty-direct' to '/Users/roberto/.terminfo/61/alacritty-direct'
==> Linking Manpage 'alacritty.1.gz' to '/opt/homebrew/share/man/man1/alacritty.1.gz'
==> Linking Manpage 'alacritty-msg.1.gz' to '/opt/homebrew/share/man/man1/alacritty-msg.1.gz'
🍺  alacritty was successfully installed!
```

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

Can't show anything either.

As soon as I run Alacritty with `open(1)`  or clicking on the icon, I get this:

![Screenshot 2023-03-13 at 14 38 16](https://user-images.githubusercontent.com/142030/224720425-4683b0d2-29c4-4b29-a565-ba6f83f928b3.jpg)

```
261 [14:38] roberto@mac-studio:src/drone-gencsv> open /Applications/Alacritty.app
262 [14:38] roberto@mac-studio:src/drone-gencsv> alacritty --version
[1]    99906 killed     alacritty --version
```

**Comment by kchibisov** [comment]
https://github.com/alacritty/alacritty/wiki/Self-Signing-Alacritty-on-macOS

**Comment by kchibisov** [comment]
Try latest rc, idk...

Not that we can do much to fight apple.
