### ISSUE TITLE
MacOS: Hiding from dock (with LSUIElement true) does not work

### ISSUE THREAD

**Issue by Ziothh** [alacritty/alacritty#6779]
Hi Alacritty team,

I'm loving what you've done so far.
I'm trying to hide the Alacritty icon from the dock and cmd+tab list (in MacOS) by adding this to `/Applications/Alacritty.app/Contents/Info.plist`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <!-- SNIP -->
  <!-- THIS FIELD -->
  <key>LSUIElement</key>
  <true/>
  <!-- SNIP -->
</dict>
</plist>
```

Am I missing something?

Thanks in advance!

**Comment by chrisduerr** [comment]
You'll probably have more success asking in a place focused on macOS development. This doesn't seem related to Alacritty itself.
