### ISSUE TITLE
Repeated motion commands, relative numbers

### ISSUE THREAD

**Issue by mladedav** [alacritty/alacritty#6780]
I am missing motion commands with numbers (such as `10k` to go up ten lines). There were feature requests before (e.g. #5292) but this was closed because alacritty does not want to introduce a UI element for this.

Would it be ok to implement this without the UI element? vim does not have a dedicated element for this either.

My current workflow usually is deciding if the line I want to get to is near top/middle/bottom of the page and pressing `H`, `M`, or `L` accordingly and then finishing with a lot of `k`s and `j`s. I could use search, but sometimes I just want to copy a commit hash and if I were to write it out to copy it that defeats the purpose.

Thanks for concideration.

**Comment by chrisduerr** [comment]
While it would be nice and I find myself pondering its addition every once in a while, I do not think its benefits justify the complexity.

Alacritty's current keybinding system is able to immediately resolve any keybinding. Adding the option for combined keybindings and repeats like this not only significantly increases the complexity of the keybinding action itself, it also means you have to consider conflicts between bindings and handle timeouts etc.

**Comment by mladedav** [comment]
If the scope was narrowed just to numbers being modifiers (so no support for other chords like e.g. `f<char>` to find a char on line) there would be no conflicts. I would be also in favor of ignoring timeouts for the sake of simplicity.

If I were to try and make a PR for this, could it be added if the complexity wouldn't be too bad? Or do you think that this is impossible to do without major refactoring? I am not looking for any promises, just checking beforehand so that I don't waste time on something that's doomed from the beginning.

**Comment by chrisduerr** [comment]
> If the scope was narrowed just to numbers being modifiers (so no support for other chords like e.g. f<char> to find a char on line) there would be no conflicts.

That is incorrect. There would still be conflicts.

> If I were to try and make a PR for this, could it be added if the complexity wouldn't be too bad?

Yes, but you won't be able to make a clean implementation that actually solves this in a way that could be merged. Feel free to try, but it's a waste of time.

**Comment by mladedav** [comment]
> That is incorrect. There would still be conflicts.
Would you care to elaborate?
