### ISSUE TITLE
X11 transparency issue

### ISSUE THREAD

**Issue by uforek** [alacritty/alacritty#6787]
### System

OS: Ubuntu 22.04
Version: alacritty 0.13.0-dev
Linux/BSD: X11, Gnome 42.5, Mutter
GPU: NVidia GTX 1650 Super / NVidia 525 Driver

### Preface
I have correctly set the transparency of Alacritty using:
```
window:
    opacity: 1.0
```

### Problem
The transparency of Alacritty, when using x11, appears to never change, it stays semi-transparent. To test this, I changed the transparency from 0.0 to 1.0, incrementally, and notice that the window becomes more opaque, but never fully opaque as expected with a value of 1.0.

The transparency of Alacritty, when using Wayland, appears to change as expected, and eventually becomes fully opaque when opacity is set to 1.0

**Comment by kchibisov** [comment]
Are you using nvidia?

**Comment by uforek** [comment]
> Are you using nvidia?

Yeah, GTX 1650 Super. Using the the proprietary 525 driver

**Comment by kchibisov** [comment]
Try tweaking its settings to tell that alacritty is not a game.

**Comment by uforek** [comment]
> Try tweaking its settings to tell that alacritty is not a game. Maybe it enables MXAA or something, I don't remember what usually breaks it.

How would I do that? Also, wouldn't the problem persist between Wayland and X11, if it was specific to an NVidia setting?

**Comment by kchibisov** [comment]
No, it's a bit different on Wayland and the flow is a bit different.

it's nvidia settings app or something like that.

It's actually FXAA

https://github.com/alacritty/alacritty/issues/1059

**Comment by uforek** [comment]
> No, it's a bit different on Wayland and the flow is a bit different.
> 
> it's nvidia settings app or something like that.
> 
> It's actually FXAA
> 
> #1059

Disabling FXAA worked! Thanks!
