### ISSUE TITLE
Can't use <C-h> normally while using vim.

### ISSUE THREAD

**Issue by hungpham3112** [alacritty/alacritty#6795]
### System

OS: Windows 11
Version: alacritty 0.11.0 (8dbaa0b)

I have a problem with `<C-h>` when trying to jump to the left buffer in vim. It seems that `alacritty` key binding overwrite vim keybinding. I looked forward alacritty.yml file but didn't find anything related to <C-h>

The problem only exists in alacritty. I tested in cmd.exe and windowpowershell without any error.

With alacritty:

https://user-images.githubusercontent.com/75968004/226103816-95e0ab73-a2a5-482c-8eb6-76d7c12ee2cd.mp4

In the video, pressing `<C-h>` will jump to previous word, can't jump to the left buffer.

With cmd.exe:

https://user-images.githubusercontent.com/75968004/226103649-f289907e-146b-42d6-b884-e62cc5cc9203.mp4

In the video, pressing `<C-h>` will jump to left buffer normally.

**Comment by kchibisov** [comment]
We don't bind `C-h`. Be aware that `C-H` is basically `crtl + Backspace`.

**Comment by hungpham3112** [comment]
> We don't bind `C-h`. Be aware that `C-H` is basically `crtl + Backspace`.

`Ctrl + backspace` works like backspace while <C-h> jump to previous word. They are different

**Comment by chrisduerr** [comment]
`C-h`, `C-H`, and `C-Backspace` all send the exact same characters. This is working as intended.

**Comment by hungpham3112** [comment]
> `C-h`, `C-H`, and `C-Backspace` all send the exact same characters. This is working as intended.

So can u guide me to solve the problem? I don't know why you close the issue.
