### ISSUE TITLE
`dynamic-title` does nothing

### ISSUE THREAD

**Issue by sahinf** [alacritty/alacritty#6796]
### System

OS: Linux
Version: alacritty 0.11.0 (8dbaa0bb)
Linux/BSD: X11 using i3wm

### Issue
I wanted Alacritty to display my CWD in the title bar so I found and set
```yml
dynamic-title : true
```
in `alacritty.yml`

I observed no change in behavior so I kept digging and found out the shell handles this through [ANSII OSC escape sequences](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands). 
I editted my `.zshrc` to include to include the [Bash $PROMPT_COMMAND equivalent](https://superuser.com/questions/735660/whats-the-zsh-equivalent-of-bashs-prompt-command), precmd.

So I defined that function in my `.zshrc` as
```console
function precmd() {
    echo -ne "\033]0;${PWD}\007"
}
```

and this achieved the exact result I wanted: my title bar dynamically updates to `$PWD`.

Out of curiousity, I set the `dynamic-title` to `false` in `alacritty.yml`, but the title bar still updated to `$PWD` even after changing directories.
I *can* verify that my `alacritty.yml` config is being read as changing the `font` variable visibly changes my terminal font. 

So now I'm confused with what `dynamic-title` actually controls, because it's value doesn't seem to affect alacritty's title bar at all.

**Comment by kchibisov** [comment]
Your config is wrong.

```yml
window:
    dynamic_title: false
```

If you want to disable it.
