### ISSUE TITLE
Let `alacritty msg create-window` preserve working directory like `CreateNewWindow` action

### ISSUE THREAD

**Issue by niklasf** [alacritty/alacritty#6798]
A key binding with action `CreateNewWindow` opens the new window with the current working directory.

However, `alacritty msg create-window` always uses the default working directory. It would be convenient if this would also preserve the working directory, or if there was an IPC command to execute actions.

### System

OS: Arch Linux
Version: `alacritty 0.13.0-dev (2377c0a7)`
Wayland with sway

**Comment by kchibisov** [comment]
>However, alacritty msg create-window always uses the default working directory. It would be convenient if this would also preserve the working directory, or if there was an IPC command to execute actions.

You can pass whatever you want to `create-window` as in `alacritty msg create-window  --working-directory=/home -e htop`. 

The issue is that `create-window` doesn't know which directory to reuse, what if you have 10 windows opened, which one should we pick?

**Comment by niklasf** [comment]
Makes sense. Thanks!
