### ISSUE TITLE
Default shell is zsh, but alacritty uses bash

### ISSUE THREAD

**Issue by tiudvek** [alacritty/alacritty#6799]
OS: Linux
Version: alacritty 0.13.0-dev (2377c0a7)

How do I make alacritty use zsh instead of bash?

**Comment by kchibisov** [comment]
Set it as a login shell for your user or as a shell inside alacritty.yml.

**Comment by tiudvek** [comment]
@kchibisov how?

**Comment by kchibisov** [comment]
For login shell use `chsh`(without root) and for in config there's a https://github.com/alacritty/alacritty/blob/2377c0a7280f31ccc46953c462823ee3a1083af5/alacritty.yml#L453 section.

**Comment by tiudvek** [comment]
my default shell is zsh

**Comment by kchibisov** [comment]
if you login to your user with `su` will you get a `zsh`? We don't use bash anywhere in the codebase, since we pick whatever you have in your `passwd` and then fallback to `$SHELL`.

**Comment by tiudvek** [comment]
oh, its fixed now, thanks!
