### ISSUE TITLE
`ls` does not generate clickable links in the terminal

### ISSUE THREAD

**Issue by nurmohammed840** [alacritty/alacritty#6800]
### System

OS: Linux
Version: 0.10.1
Linux/BSD: Wayland, Gnome and sway

**Comment by chrisduerr** [comment]
`ls --hyperlink=always`

**Comment by nurmohammed840** [comment]
@chrisduerr 

does `ls --hyperlink=always` solve this issue ?

**Comment by kchibisov** [comment]
>Version: 0.10.1

Available since `v0.11.0`.

**Comment by 097115** [comment]
@kchibisov 

Could you elaborate a bit, please?

I run `ls --hyperlink=always`, then trigger hints, do see them:

![](https://i.imgur.com/p8N7mXw.png)
But then I select one (like, I press `a` considering the picture above), and nothing happens?

**Comment by chrisduerr** [comment]
The default binding is `xdg-open`. You need that installed for it to work obviously.

**Comment by 097115** [comment]
@chrisduerr 

Thank you for the reply!

I do have `xdg-open` installed, and if I run it from the command line, it does open the file. But somehow not via hints...

**Comment by 097115** [comment]
@chrisduerr 

Tried with `-vv`, and it seems my hostname somehow gets inserted into filepath (HOSTNAME is my actual $HOSTNAME):

    [5.595502188s] [DEBUG] [alacritty] Launched xdg-open with args ["file://HOSTNAME/home/097115/Pictures/tarragona.jpg"]

So, it fails to find the file with HOSTNAME present in the path... (the command `xdg-open file:///home/097115/Pictures/tarragona.jpg` works).

**Comment by chrisduerr** [comment]
Sounds like `xdg-open` just doesn't work with this type of URI or you don't have it configured correctly. It works just fine opening in Firefox for me.
