### ISSUE TITLE
Scrollback buffer cannot be cleared

### ISSUE THREAD

**Issue by zambetti** [alacritty/alacritty#6809]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: macOS
Version: 0.11.0

### Description

When clearing the scrollback buffer with command+k, the visible part of the buffer disappears as expected.
However, it is still possible to scroll back, and see what was formerly on screen.
If I perform command+k two times, then what is off screen (the scrollback buffer) is also cleared.

If this is intended behavior, it seems that command+k hides the buffer off screen, and if it is already hidden, then command+k actually clears the scrollback buffer. Is this intentional?

If so, this behavior is strange since it means that there is always at least one line that scrolls down (in the case of performing command+k on an empty prompt). So the scrollback buffer can never be cleared? I assume this is a bug.

**Comment by chrisduerr** [comment]
Are you using tmux?

**Comment by zambetti** [comment]
> Are you using tmux?

Thank you for your reply, no I’m not using tmux.

**Comment by chrisduerr** [comment]
Are you using any other kind of multiplexer or application that might intercept key sequences?

Could you try mapping the `ClearHistory` action to another key and see if it works on its own?

**Comment by zambetti** [comment]
I've added this to my alacritty.yml file...

key_bindings:
- { key: R, mods: Command, action: ClearHistory }

Now when I perform command+r, the visible part of the buffer remains visible/unchanged, but the scrollback is indeed erased/cleared (as it should be).

With this, I've found that I can get closer to the expected behavior by typing 'clear' as a command, then performing a command+r. The 'clear' pushes the scrollback out of the visible area, and the command+r erases the scrollback.

**Comment by chrisduerr** [comment]
You mean just mapping it to `ClearHistory`? Yeah I'd be fine with that.

**Comment by zambetti** [comment]
> What @zambetti reports isn't really much worse than not having anything cleared at all.

I don’t understand, is there some way to clear the terminal to a blank prompt (with no scrollback) using a key command?

**Comment by chrisduerr** [comment]
Not reliably, no. But considering that applications are running in the visible grid, that's probably not a good idea anyway.
