### ISSUE TITLE
[0.12.0][macOS] Colors washed out after updating

### ISSUE THREAD

**Issue by utkarshgupta137** [alacritty/alacritty#6815]
After upgrading to `0.12.0`, the colors in neovim appear all washed out. It is probably due to #6602. I understand the author's reasons for wanting sRGB for color work, but I prefer the previous versions' "vivid" look. Please introduce a config option for the same.

### System

OS: macOS
Version: alacritty 0.12.0 (5a72819)

### Screenshot
I don't know if you can tell the difference, but the colors in the new version look really washed out to me - akin to watching HDR content on a non-HDR display.

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/5155100/227702612-a7a2d8e5-523b-4981-bedd-9951304f8aa4.png">

**Comment by nguyenvukhang** [comment]
To build a further case for this issue:

<img width="261" alt="Screenshot 2023-03-26 at 00 20 51" src="https://user-images.githubusercontent.com/10664455/227729307-269e6462-0004-4da3-aa07-32eb9d0915a1.png">

Using MacOS's built-in Digital Color Picker, it can't pick up any difference between `blue` and `cyan` at all, when they are actually different colors, visible from other terminals:

<img width="234" alt="Screenshot 2023-03-26 at 00 22 38" src="https://user-images.githubusercontent.com/10664455/227729422-acef2218-34b2-47b4-8d56-9a530e0d7d99.png">

**Comment by chrisduerr** [comment]
> Please introduce a config option for the same.

Nope.

**Comment by utkarshgupta137** [comment]
> > Please introduce a config option for the same.
> 
> Nope.

Why? I really love alacrity & I'm really saddened to see that my experience got worse with a version upgrade :(

**Comment by chrisduerr** [comment]
If you don't like your colors, just change your colorscheme.

**Comment by utkarshgupta137** [comment]
> If you don't like your colors, just change your colorscheme.

I'm not proficient with colors, but I'll try to replicate the colors through modifications. But if I'm not wrong isn't P3 an expanded color space & theoretically, there are colors in the P3 color space which aren't present in the sRGB color space? If so, how can I get those colors?
Also, is the sRGB for web purposes still a valid argument since browsers are starting to support display P3? So if someone wants to do CSS for P3 displays, they can't do it using alacritty anymore?
Source: https://webkit.org/blog/10042/wide-gamut-color-in-css-with-display-p3/

**Comment by utkarshgupta137** [comment]
<img width="1800" alt="image" src="https://user-images.githubusercontent.com/5155100/227739729-39f0ba87-4fe0-4b79-a96d-b7cfff351b0e.png">

On the left is the Display-P3 version with a display-p3 color picker website & on the right is the sRGB version with a sRGB color picker website. I'm not sure if the difference is visible on a non-P3 display, but I can easily tell the difference on my end.
And it looks like the `color()` function for providing P3-capable colors is going to be a part of the CSS Level 4 spec (https://w3c.github.io/csswg-drafts/mediaqueries/#color-gamut) & most browsers are starting to support it (https://caniuse.com/css-color-function) (firefox is also working on it: https://hg.mozilla.org/mozilla-central/rev/f9da93df13f8)

**Comment by kchibisov** [comment]
Yes, but the colors in the terminal are `SRGB` we're not a web browser. The colorspace isn't passed along the colors and so on. In fact, only macOS had this weird coloring issue, because it was doing "convertions" on its on.

**Comment by utkarshgupta137** [comment]
> Yes, but the colors in the terminal are `SRGB` we're not a web browser to have P3. The colorspace isn't passed along the colors and so on. In fact, only macOS had this weird coloring issue, because it was doing "convertions" on its on.

I understand the argument. But it also means that there is no way to access the larger color space that many displays support. It's just that I've recently moved from VSCode to NeoVim & I got really used to the vivid colors in both VSCode & NeoVim on alacritty. In fact, I moved from kitty to alacritty just due to this issue since I didn't know there was a config option present in kitty.
I found many missing features in alacritty at first, but I've managed without them over time, so I guess I'll have to manage without this too. But I do wonder, if more & more displays are going to support a wider color gamut are terminals just supposed to not evolve with the times? Shouldn't there be a way for terminals to support a wider color gamut?

**Comment by kchibisov** [comment]
The truecolor escape sequences are in srgb, not in P3. kitty has an option to silence macOS users (because on Linux/Windows non of that is an issue, you can run alacritty in 10bit with the colors you'd expect).

I tend to think to add the same option kitty has simply to silence users(that was the motivation for it).

**Comment by utkarshgupta137** [comment]
> The truecolor escape sequences are in srgb, not in P3. kitty has an option to silence macOS users (because on Linux/Windows non of that is an issue, you can run alacritty in 10bit with the colors you'd expect).
> 
> I tend to think to add the same option kitty has simply to silence users(that was the motivation for it).

Why can't the same be done on macOS?

**Comment by chrisduerr** [comment]
> But it also means that there is no way to access the larger color space that many displays support.

Which is irrelevant for a terminal emulator anyway because you're not gonna do color grading in a terminal. I doubt people would even be able to tell the differences (not in color space, but in available color space).

**Comment by utkarshgupta137** [comment]
> > But it also means that there is no way to access the larger color space that many displays support.
> 
> Which is irrelevant for a terminal emulator anyway because you're not gonna do color grading in a terminal. I doubt people would even be able to tell the differences (not in color space, but in available color space).

Yeah, I'm not arguing that you should be doing color grading in the terminal. I was just addressing the people who were raising the issue regarding incorrect colors in the first place. My use case is purely to make neovim look better :D
I'm able to tell the difference between the old & new versions of alacritty side-by-side (refer to my original screenshot) & I bet I could tell if the sRGB mode was forced or not more than 90% of the time. As I said, when I was migrating from VSCode to NeoVim, I was unhappy that the same color scheme didn't look as good in kitty as it did in VSCode & NeoVim & that's when I moved to alacritty.
Arguing that terminals are (historically) supposed to be in sRGB color space is an understandable argument. Arguing that larger color spaces are meaningless is not.

**Comment by chrisduerr** [comment]
> I'm able to tell the difference between the old & new versions of alacritty side-by-side (refer to my original screenshot) & I bet I could tell if the sRGB mode was forced or not more than 90% of the time. 

You're able to tell the difference with the colors not being adjusted for their colorspace. But if they were tweaked to be as identical as possible, would you actually be able to tell that P3 has a bigger colorspace for a bit of colored text in the terminal?

**Comment by utkarshgupta137** [comment]
> > I'm able to tell the difference between the old & new versions of alacritty side-by-side (refer to my original screenshot) & I bet I could tell if the sRGB mode was forced or not more than 90% of the time. 
> 
> You're able to tell the difference with the colors not being adjusted for their colorspace. But if they were tweaked to be as identical as possible, would you actually be able to tell that P3 has a bigger colorspace for a bit of colored text in the terminal?

No I wouldn't. Is there a way to do so in alacritty?

**Comment by chrisduerr** [comment]
> No I wouldn't. Is there a way to do so in alacritty?

I mean you can freely set your colors in Alacritty.

For most people that run into this issue and don't immediately go to changing their own colorscheme and moving on with their life, I'd probably recommend just looking at [alacritty-theme](https://github.com/alacritty/alacritty-theme), which has like a billion themes you can quickly try out to find one that fits your preferences without having to tweak things yourself.

**Comment by svanharmelen** [comment]
Yes, you can freely set colors in Alacritty but it's not just Alacritty itself right... I spend 99% of my time in some kind of terminal app (mostly neovim) and they all look very (very!) different now. Some allow you to change the colorscheme, some don't.

Either way it's questionable if I can get things to look the same again in my personal setup (which I'm now using for years and years and on which I invested a ton of time to configure things to my personal preferences). And even if it's possible, it means I have to invest quite some time to fiddle with a lot of stuff that I don't want to fiddle with again (I already invested the time to get to this point before).

So seeing these changes today and then reading your reactions here (like `nope` or `If you don't like your colors, just change your colorscheme`) makes me really sad. Why so brutal and dismissive to supportive people who use and love Alacritty for years?

I get that it's not possible to always make everyone happy and that people will always have something to complain. And I also get that from a purist point of few, the change that was made is actually "correcting" something that wasn't perfect to begin with.

Yet "just" changing it like this without an option to configure it after it being the default for years and years doesn't feel right either. It essentially impacts _all_ macOS users. And while some people probably don't care, I'm guessing a lot probably do. So I really feel like you're underestimating the potential impact this change might have on individuals relying on Alacritty. 

P.S. Not trying to start a conflict or major discussion here! I 100% respect you and am still grateful for your work on Alacritty. But I just felt the need to share my point of view and how it made me feel this morning. Thanks...

**Comment by svanharmelen** [comment]
I've deleted my previous comment, but would still like to voice that having a config switch for this would be very much appreciated 😊

**Comment by utkarshgupta137** [comment]
Maybe I misunderstood or wasn't clear. I'm happy with my themes & color schemes, I just don't think I'll be able to replicate the "vivid" colors using just the sRGB color space. I agree that it is probably best to have sRGB look like sRGB.

My question is - is there a way to access the Display P3 color space using Alacritty on mac? If I'm understanding @kchibisov's comment correctly, it is possible to do it on Linux/Windows but not on mac. If that is the case, why is that & what would it take to add that support for mac?

**Comment by utkarshgupta137** [comment]
I've solved this for now by creating a workaround using nix: https://github.com/utkarshgupta137/nix-config/commit/07697e5d0db30bd497342080b2df001a50e008be.

**Comment by naruaway** [comment]
I think the ideal way to solve this issue is to implement escape sequence to specify color space such as P3 rather than introducing new option to interpret existing color codes as native color space. It should be essentially the same as something like `color(display-p3 1 0.5 0)` [implemented in Webkit](https://webkit.org/blog/10042/wide-gamut-color-in-css-with-display-p3/). Then we can develop "vivid color scheme" using the new encoding.


Introducing options such as https://github.com/alacritty/alacritty/pull/6816 makes every color scheme look different in every display

**Comment by kchibisov** [comment]
The default escape sequence has an option to pass colorspace. The thing is that you don't have colorspace in the config.

**Comment by utkarshgupta137** [comment]
> I think the ideal way to solve this issue is to implement escape sequence to specify color space such as P3 rather than introducing new option to interpret existing color codes as native color space. It should be essentially the same as something like `color(display-p3 1 0.5 0)` [implemented in Webkit](https://webkit.org/blog/10042/wide-gamut-color-in-css-with-display-p3/). Then we can develop "vivid color scheme" using the new encoding.

I agree with that in principle. I disagree with it practically. I can't expect every theme creator for every program I use (mainly NeoVim) to define a separate color scheme or a p3-compatible color scheme. I also don't have time to go changing the color scheme for every program I use. I know many programs respect LS_COLORS, but it's not always the case.

Using the macOS's inbuilt hack is a good way for me to do that. I like the result, it is good enough for me. I don't care about the accuracy.

> Introducing options such as #6816 makes every color scheme look different in every display

That is already the case, doesn't matter if we enable P3 or not. Maybe this hack makes the difference larger. But the colors already look very different on my Linux machine regardless of this hack.

**Comment by naruaway** [comment]
> That is already the case, doesn't matter if we enable P3 or not. Maybe this hack makes the difference larger. But the colors already look very different on my Linux machine regardless of this hack.

I think as long as displays are properly calibrated and they support enough range of sRGB, which is true for P3 displays, the same color scheme should show the same color in web browsers and popular terminals including the current version of Alacritty. "the colors already look very different on my Linux machine" sounds like color configuration of display and/or operating system is broken.

But I understand the use case. Some people can prefer more vivid color scheme than the author probably has intended. If we ever want to introduce an option, I think the name should be more explicit than `window.use_srgb`. Maybe something like `window.forcefully_interpret_colors_as_native_values` can be reasonable but this is niche option and I can imagine (I am not a dev of Alacritty so not sure) Alacritty would not accept such edge case options for simplicity. If we introduce such option, I think the next thing is people will request more customization such as `window.forcefully_interpret_colors_as_some_other_colorspace`  or arbitrary color transformation function configuration to tweak / shift all the colors shown in the terminal without modifying the color scheme itself. This might be interesting direction but it can be "too much" for a config option of terminal.

Just a random idea, as a user land solution, maybe we could create a thin CLI wrapper tool to transform color escape codes for arbitrary app

**Comment by utkarshgupta137** [comment]
> I think as long as displays are properly calibrated and they support enough range of sRGB, which is true for P3 displays, the same color scheme should show the same color in web browsers and popular terminals including the current version of Alacritty.

I'm not saying that the colors look different between Alacritty & Firefox on the **_same display_** (without my workaround). I'm saying that the colors look different on Alacritty (or Firefox) between **_different displays_** (again, without my workaround). I was replying to this:
> Introducing options such as #6816 makes every color scheme look different in every display

---

> "the colors already look very different on my Linux machine" sounds like color configuration of display and/or operating system is broken.

No, nothing is broken AFAIK. I've not done any special configuration either.
The difference is that my Linux laptop has an anti-glare or matte finish while my MacBook Pro has a glossy finish. Also, the MacBook Pro has a mini-LED display (or XDR as Apple calls it), so the contrast levels are very different. Plus there is probably some difference in the color temperatures of the displays. I can of course tune the displays to bring them closer, but I don't see it as an issue.

My point is that expecting the colors to look the same across displays is probably not gonna happen anytime soon (sadly). If I ever buy a monitor, then I would probably want to see the same colors from both OSs, but that's not the case today.
 
> But I understand the use case. Some people can prefer more vivid color scheme than the author probably has intended. If we ever want to introduce an option, I think the name should be more explicit than `window.use_srgb`. Maybe something like `window.forcefully_interpret_colors_as_native_values` can be reasonable but this is niche option and I can imagine (I am not a dev of Alacritty so not sure) Alacritty would not accept such edge case options for simplicity. If we introduce such option, I think the next thing is people will request more customization such as `window.forcefully_interpret_colors_as_some_other_colorspace` or arbitrary color transformation function configuration to tweak / shift all the colors shown in the terminal without modifying the color scheme itself. This might be interesting direction but it can be "too much" for a config option of terminal.

I agree with this point. The simplicity of configuration is one of the best features of Alacritty. At the same time, I got used to the Vivid colors on Alacritty (& in VSCode before migrating to NeoVim). I can't take the blue pill now xD.

> Just a random idea, as a user land solution, maybe we could create a thin CLI wrapper tool to transform color escape codes for arbitrary app

I don't much care about the output from my CLI tools. I mostly care about how my editor (NeoVim) looks. It just won't be practical/performant for NeoVim (or any of the plugins) to go through a CLI tool. Even a lua solution wouldn't be fast enough I think. Not sure if NeoVim has any plans to support it either, they probably have more pressing tasks.

**Comment by naruaway** [comment]
>  If I ever buy a monitor, then I would probably want to see the same colors from both OSs, but that's not the case today.

Sure, my point was, if this is the case, probably it's better to spend our effort to try to make them look the same in terms of colors; otherwise, all the other things such as photos or colors in web sites will look different from the color the authors intended originally. 

But anyway if many people really want to have an option to apply arbitrary color transformation / interpretation, it might make  sense to introduce an option, which could be considered by Alacritty devs maybe. If not, people can just apply patch as you did. Actually I was using my own patched version to apply https://github.com/alacritty/alacritty/pull/6602 until gets merged :)

BTW, I am curious whether your color scheme is already maximally utilizing the whole sRGB space or not; maybe you can tweak the color scheme itself to shift the whole colors to more vivid ones within sRGB space

**Comment by utkarshgupta137** [comment]
> > If I ever buy a monitor, then I would probably want to see the same colors from both OSs, but that's not the case today.
> 
> Sure, my point was, if this is the case, probably it's better to spend our effort to try to make them look the same in terms of colors; otherwise, all the other things such as photos or colors in web sites will look different from the color the authors intended originally.
> 
> But anyway if many people really want to have an option to apply arbitrary color transformation / interpretation, it might make sense to introduce an option, which could be considered by Alacritty devs maybe. If not, people can just apply patch as you did. Actually I was using my own patched version to apply #6602 until gets merged :)

Yeah, I'm not very mad at the Alacritty devs for not accepting my PR. I figured it was going to get rejected, or they would've asked for an option in #6602 itself.
I still think it should've been accepted though, since that was always the behavior before your PR. Hopefully, people who really care about this option can find this discussion.

> BTW, I am curious whether your color scheme is already maximally utilizing the whole sRGB space or not; maybe you can tweak the color scheme itself to shift the whole colors to more vivid ones within sRGB space

Yeah, maybe. I only set up NixOS on my personal laptop so that I can still code without my work MBP, but that is rare (I'll be damned before I ever use Windows for dev). But if I start using it more, I would probably have to tweak my color schemes, rather than going for the quick & dirty solution.
