### ISSUE TITLE
Alacritty on Wayland not showing fonts or symbols

### ISSUE THREAD

**Issue by thrifty-txt** [alacritty/alacritty#6818]
I performed a git bisect and found that when compiling with RUSTFLAGS="-Clinker=clang -Clink-arg=-fuse-ld=lld -Clinker-plugin-lto" with Clang 16 since commit d0078ffc2 (switching from fat to thin LTO) alacritty does not show fonts or symbols.

I'm using Sway 1.8.1 with Mesa 23.1.0-devel on an AMD RX 6800 XT on linux-6.3.0-rc2.

Reverting to lto=fat fixes the issue!

**Comment by REALERvolker1** [comment]
This is also happening to me on x11

**Comment by REALERvolker1** [comment]
Update: It only happens when I run cargo build --release
![image](https://user-images.githubusercontent.com/73304952/227834923-69487f65-3914-499f-9b8f-911489dff0e8.png)

**Comment by kchibisov** [comment]
Could you build without a clang involved? The clang16 is fairly recent and might be bugged. If you build with gcc it should be fine?

**Comment by REALERvolker1** [comment]
![image](https://user-images.githubusercontent.com/73304952/227952200-9fae3f02-0248-4dec-9221-f0f03774e2cb.png)

I couldn't find how to do this on google, so I used chatgpt. Did I do it right? It still isn't rendering fonts correctly

**Comment by kchibisov** [comment]
@REALERvolker1, if you revert the  d0078ff commit, is the issue fixed for you? Otherwise you might have a different issue.

In case your issue is different, I'd suggest to try:

```
alacritty -o debug.renderer=gles2_pure
```

**Comment by kchibisov** [comment]
@thrifty-txt 

I performed a git bisect and found that when compiling with RUSTFLAGS="-Clinker=clang -Clink-arg=-fuse-ld=lld -Clinker-plugin-lto"

Could you remove all your weird flags and retry? Could also try to keep clang, but remove the  `-Clink-arg=-fuse-ld=lld -Clinker-plugin-lto`.

**Comment by thrifty-txt** [comment]
> Could you remove all your weird flags and retry? Could also try to keep clang, but remove the `-Clink-arg=-fuse-ld=lld -Clinker-plugin-lto`.

I've found the problem. -Clinker-plugin-lto (which is documented [here](https://doc.rust-lang.org/rustc/linker-plugin-lto.html#linker-plugin-based-lto)) can cause issues if the system llvm (llvm-16 for me) is different from the llvm that rust is built with (llvm-15 for me).

Closing this as it isn't an issue with Alacritty..

**Comment by ashleysommer** [comment]
For anyone coming here from google with the same issue, I solved it by downgrading my rust toolchain to stable v1.69.
My rustup was set to use nightly by default. Nightly recently switched to LLVM v16, but my system (Manjaro) has LLVM v15. Rust stable v1.69 was the last release based on LLVM v15, so works just fine.
