### ISSUE TITLE
Drag file with special characters to the window, it was not escaped

### ISSUE THREAD

**Issue by woyin** [alacritty/alacritty#6819]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: macOS
Version: alacritty 0.12.0 (5a72819)

### Phenomenon

When I drag a file with special character `[` or `]` to the Alacritty window, I got the file path without escape. 

For example, the file name is `68EC(XRGB)[Ble] User Manual.doc` and it was in the `~/Downloads`, when I drag the file to windows, I just got the result below:

![image](https://user-images.githubusercontent.com/35319250/227847046-3489a831-fe3a-4e8d-b7b5-4f28f6be12c8.png)

**Comment by chrisduerr** [comment]
Working as intended, the path should be quoted.
