### ISSUE TITLE
Is it possible to swap Command/Option keys on MacOS?

### ISSUE THREAD

**Issue by matthewtusker** [alacritty/alacritty#6820]
### System

OS: macOS
Version: 0.12.0

I'm trying to configure Alacritty to work on both my personal Linux machine and my work Macbook, so that I finally have a consistent developer experience on both. One thing that's keeping me on iTerm2 is the ability to remap modifiers. I have the Option and Command modifiers swapped in System Settings to keep things consistent with Linux shortcuts, and have swapped them back in iTerm2 so that terminal shortcuts work as expected.

I can't seem to find a neat way to do this in Alacritty. I have tried `option_as_alt` but I'm starting to realise this isn't quite what I thought it was. Is there a way to do what I'm describing (and have those config options only be applicable on MacOS) or am I trying to do something that isn't supported?

**Comment by chrisduerr** [comment]
This is not something I'm interested in supporting.

That said, your setup also sounds kinda backwards. Seems like the way easier solution would be using super for shortcuts on Linux? That should be the default anyway.
