### ISSUE TITLE
Alacritty: Runtime Error

### ISSUE THREAD

**Issue by mlzzen** [alacritty/alacritty#6822]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Windows 10 Enterprise LTSC
alacritty 0.12.0 (5a728195)

### Logs

panicked at 'assertion failed: `left == right)`
  left: `-2147023636`
  right: `0`', alacritty_terminal\src\tty\windows\conpty.rs:62:5

**Comment by chrisduerr** [comment]
Which Windows version are you using? Sounds like an issue with your Windows setup.

**Comment by mlzzen** [comment]
> Which Windows version are you using? Sounds like an issue with your Windows setup.

win10 1809 (OS Build 17763.3770)

**Comment by chrisduerr** [comment]
That sounds extremely old. Have you tried an up-to-date Windows version?

**Comment by mlzzen** [comment]
This is a company computer, I cannot upgrade its system version, only company administrators can upgrade it.

**Comment by chrisduerr** [comment]
Well I'm certainly not interested in troubleshooting issues in 4+ year old Windows versions. So unless you can reproduce it somewhere else, you're on your own.

**Comment by kchibisov** [comment]
The error is that it can't instantiate conpty(The library providing your console access on windows, usually shipped with it). Maybe you don't have conpty in your system at all, given that it's sort of old windows version(I think some early windows 10 versions were not using the ConPty at all).

Given that we've dropped legacy interface (WinPty) you seem like not have other option for now.
There's some fork which builds upstream conpty, and uses it in alacritty, but I don't remember where it's.

**Comment by chrisduerr** [comment]
> Maybe you don't have conpty in your system at all, given that it's sort of old windows version(I think some early windows 10 versions were not using the ConPty at all).

ConPTY was introduced in 1809 iirc, so it should *in theory* work I think (maybe). But no clue about this specific version.

**Comment by kchibisov** [comment]
There're 4 versions of Windows 10 LTSC, and 2 before 1809.

**Comment by chrisduerr** [comment]
> win10 1809 (OS Build 17763.3770)

**Comment by kchibisov** [comment]
maybe it's not a part of LTS version? https://learn.microsoft.com/en-us/windows/console/createpseudoconsole the version is clearly on the edge when it became available (be aware that it's also enterprise version). Though, the function worked, somehow...

**Comment by kchibisov** [comment]
Just searching the web suggested that it's a common error code due to security policies on the system. The error we're getting here is `0x800704ec`(you can search for it yourself). I'd suggest to search the web on how to address that, since it's a windows issue which has nothing to do with us, given that's an enterprise windows version, it's not surprising.

**Comment by onkoe** [comment]
Experiencing this on Windows 10 Enterprise IoT LTSC on the newest update. It's only happened once so far - only occurring after opening a new Alacritty window from the old one (with `SpawnNewInstance`).

```
---------------------------
Alacritty: Runtime Error
---------------------------
panicked at alacritty_terminal\src\tty\windows\conpty.rs:306:9:
assertion `left == right` failed
  left: -2147024664
 right: 0

Press Ctrl-C to Copy
---------------------------
OK   
---------------------------
```

This means the error is happening here: 

```rs
impl OnResize for Conpty {
    fn on_resize(&mut self, window_size: WindowSize) {
        let result = unsafe { (self.api.resize)(self.handle, window_size.into()) };
        assert_eq!(result, S_OK); // this line 
    }
}
```

## Alacritty Version

```bash
user@hostname MINGW64 ~
$ alacritty --version
alacritty 0.15.1 (0c405d5)
```

**Comment by onkoe** [comment]
nevermind - this issue doesn't seem to be related. opened a new one at #8620
