### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by nDimensionalSpace** [alacritty/alacritty#6824]
### System

OS: RHEL Server 7.9
Version: `alacritty 0.13.0-dev (2df8f860)`
Linux/BSD: X11, window manager is MWM (i.e., Motif)

### Logs
```
[release (master:behnd)] ./alacritty -vv
Created log file at "/var/tmp/Alacritty-69885.log"
[0.000003442s] [INFO ] [alacritty] Welcome to Alacritty
[0.000108015s] [INFO ] [alacritty] Version 0.13.0-dev (2df8f860)
[0.000129369s] [INFO ] [alacritty] Running on X11
[0.001637389s] [INFO ] [alacritty_config_derive] No config file found; using default
[0.595797241s] [INFO ] [alacritty] Using GLX 1.4
[0.987383071s] [INFO ] [alacritty] Window scale factor: 1
Error: [2] BadValue (integer parameter out of range for operation)
[1.093380765s] [INFO ] [alacritty] Goodbye
Deleted log file at "/var/tmp/Alacritty-69885.log"
Error: "Event loop terminated with code: 1"
```

**Comment by chrisduerr** [comment]
RHEL Server 7.9 sounds like a distro ripe for issues due to its age. Can you reproduce this on a more up-to-date system?

**Comment by nDimensionalSpace** [comment]
Ok, after fixing the path so that it points to the Nvidia library files, RHEL 8.7 results in the same output:

```
[release (master↓)] ./alacritty -vv   
Created log file at "/var/tmp/Alacritty-3414455.log"
[0.000001660s] [INFO ] [alacritty] Welcome to Alacritty
[0.000064943s] [INFO ] [alacritty] Version 0.13.0-dev (2df8f860)
[0.000084199s] [INFO ] [alacritty] Running on X11
[0.000272344s] [INFO ] [alacritty_config_derive] No config file found; using default
[0.690088818s] [INFO ] [alacritty] Using GLX 1.4
[1.131511228s] [INFO ] [alacritty] Window scale factor: 1
Error: [2] BadValue (integer parameter out of range for operation)
[1.194667745s] [INFO ] [alacritty] Goodbye
Deleted log file at "/var/tmp/Alacritty-3414455.log"
Error: "Event loop terminated with code: 1"
```

**Comment by chrisduerr** [comment]
> Error: [2] BadValue (integer parameter out of range for operation)

This sounds rather strange and doesn't come from Alacritty. It might be driver related (like shaders?).

You can try changing the debug options to try out the different renderer options (see alacritty config for reference).

**Comment by kchibisov** [comment]
I'm not sure what you're pointing to what, but I'd assume that using open source drivers will work just fine(as in at least llvmpipe).


maybe the error is nvidia specific, I have no clue how nvidia driver works.

**Comment by nDimensionalSpace** [comment]
Renderer options didn't change anything.  I set log_level to "Trace", and got one extra line of output, that being

```
[0.722112310s] [WARN ] [winit] XRandR reported that the display's 0mm in size, which is certifiably insane
```

**Comment by kchibisov** [comment]
That message from xrandr is unrelated.

**Comment by nDimensionalSpace** [comment]
Hmmm . . .  I don't see how to build with backtrace enabled.

**Comment by kchibisov** [comment]
You can try something like that with the debug build

```diff
diff --git a/alacritty/src/renderer/platform.rs b/alacritty/src/renderer/platform.rs
index c9802e0a..2dc24141 100644
--- a/alacritty/src/renderer/platform.rs
+++ b/alacritty/src/renderer/platform.rs
@@ -105,7 +105,7 @@ pub fn create_gl_context(
         picked_context = unsafe { gl_display.create_context(gl_config, &profile) };
     }
 
-    picked_context
+    Ok(picked_context.unwrap())
 }
 
 pub fn create_gl_surface(
@@ -125,5 +125,5 @@ pub fn create_gl_surface(
         );
 
     // Create the GL surface to draw into.
-    unsafe { gl_display.create_window_surface(&gl_config, &surface_attributes) }
+    Ok(unsafe { gl_display.create_window_surface(&gl_config, &surface_attributes).unwrap() })
 }
```

Also, please, provide the `glxinfo` output.

**Comment by rcmosher** [comment]
I had this same issue on Ubuntu shortly after a security update. I ran `glxinfo` and it was getting the same BadValue error. After restarting `glxinfo` is fixed and so is `alacritty`.

**Comment by razziel89** [comment]
The problem seems to be the GlX backend, at least on my machine. Forcing `preference` to be `DisplayApiPreference::Egl` in the following code block allows `v0.12.0` to launch on my machine. Do you think it would be possible to expose the used renderer to the user, in some way (env var or entry in the cfg file), at least on those systems where multiple renderers are available?

https://github.com/alacritty/alacritty/blob/master/alacritty/src/renderer/platform.rs#L19-L39

**Comment by kchibisov** [comment]
@razziel89 I've tried to look into the issue you're getting, but I don't understand the origin. The mesa code base hasn't told me anything useful on what could throw the issue.

Could you try this patch on top of glutin and build alacritty with the glutin version you've patch(if you don't know, let me know).

```diff
diff --git a/glutin/src/api/glx/context.rs b/glutin/src/api/glx/context.rs
index ba8dbe0..af0cb73 100644
--- a/glutin/src/api/glx/context.rs
+++ b/glutin/src/api/glx/context.rs
@@ -164,23 +164,23 @@ impl Display {
         }
 
         // Flush control.
-        if self.inner.features.contains(DisplayFeatures::CONTEXT_RELEASE_BEHAVIOR) {
-            match context_attributes.release_behavior {
-                ReleaseBehavior::Flush => {
-                    attrs.push(glx_extra::CONTEXT_RELEASE_BEHAVIOR_ARB as c_int);
-                    attrs.push(glx_extra::CONTEXT_RELEASE_BEHAVIOR_FLUSH_ARB as c_int);
-                },
-                ReleaseBehavior::None => {
-                    attrs.push(glx_extra::CONTEXT_RELEASE_BEHAVIOR_ARB as c_int);
-                    attrs.push(glx_extra::CONTEXT_RELEASE_BEHAVIOR_NONE_ARB as c_int);
-                },
-            }
-        } else if context_attributes.release_behavior != ReleaseBehavior::Flush {
-            return Err(ErrorKind::NotSupported(
-                "flush control behavior GLX_ARB_context_flush_control",
-            )
-            .into());
-        }
+        // if self.inner.features.contains(DisplayFeatures::CONTEXT_RELEASE_BEHAVIOR) {
+        //     match context_attributes.release_behavior {
+        //         ReleaseBehavior::Flush => {
+        //             attrs.push(glx_extra::CONTEXT_RELEASE_BEHAVIOR_ARB as c_int);
+        //             attrs.push(glx_extra::CONTEXT_RELEASE_BEHAVIOR_FLUSH_ARB as c_int);
+        //         },
+        //         ReleaseBehavior::None => {
+        //             attrs.push(glx_extra::CONTEXT_RELEASE_BEHAVIOR_ARB as c_int);
+        //             attrs.push(glx_extra::CONTEXT_RELEASE_BEHAVIOR_NONE_ARB as c_int);
+        //         },
+        //     }
+        // } else if context_attributes.release_behavior != ReleaseBehavior::Flush {
+        //     return Err(ErrorKind::NotSupported(
+        //         "flush control behavior GLX_ARB_context_flush_control",
+        //     )
+        //     .into());
+        // }
 
         // Terminate list with zero.
         attrs.push(0);
```

If that doesn't work, one option would be to debug mesa with gdb and see where it tries to send `BadValue`(I've looked into the code, but wasn't able to find, maybe your distro has quirks).

I think mint should provide debug packages and you should simply be able to step into the function or something when creating context. It should probably go into `gallium/state_trackers/glx/xlib/glx_api.c` or something, but it might be different because, actually, your driver might not be gallium based (understand what in mesa actually throws the error will be nice).

Also, does it work with the `LIBGL_ALWAYS_SOFTWARE=1`?

**Comment by 7flash** [comment]
also having this issue on popos

```
Error: [2] BadValue (integer parameter out of range for operation)
Error: "Event loop terminated with code: 1"

```

**Comment by razziel89** [comment]
I finally found the time to look at this in more detail - here are the results. Thanks for the help and the suggestions @kchibisov!

> Also, does it work with the LIBGL_ALWAYS_SOFTWARE=1?

Setting that environment variable did not change the outcome, alacritty v0.12.0 still crashed with the very same error message.

> Could you try this patch on top of glutin and build alacritty with the glutin version you've patch

I did try that and was delighted to see that alacritty v0.12.0 based on the patched glutin _did start_ successfully. I tried it out a bit and couldn't find any problems with the patched version while using it. Out of curiosity, what exactly did the patch do? Does this knowledge help fix the problem?

> If that doesn't work, one option would be to debug mesa with gdb and see where it tries to send BadValue

I would not have any idea how to go about that, TBH. Do you think it is still necessary?

What about my other initial question? Would it be possible to allow the user to select a rendering backend on those systems that support multiple? Thanks again for all the help!

**Comment by kchibisov** [comment]
>I did try that and was delighted to see that alacritty v0.12.0 based on the patched glutin did start successfully. I tried it out a bit and couldn't find any problems with the patched version while using it. Out of curiosity, what exactly did the patch do? Does this knowledge help fix the problem?

Yeah, it does help fix the problem, thx.

**Comment by kchibisov** [comment]
>Out of curiosity, what exactly did the patch do? Does this knowledge help fix the problem?

Glutin was explicitly specifying the default behavior for the context. While it works just fine with recent mesa, I'd assume given that your on not supported by mesa platform right now and your mesa is a bit old it happened. This code path wasn't before, so that's why it worked.

We do check whether your system supports the extension or not before calling/using it, but it seems like it just doesn't like that.

**Comment by razziel89** [comment]
Thanks for all the help and updates. Triggered by the comment about my mesa being rather old, I upgraded to a more recent version of my distribution. Alacrity v0.12 is working very well now. Thanks again!
