### ISSUE TITLE
Alacritty v0.11.0 Custom font configuration fails with latest MacOS update (Ventura 13.3)

### ISSUE THREAD

**Issue by EdmundsEcho** [alacritty/alacritty#6825]
#### Bug: 
alacritty fails to load the configured font.  It was working for over a year with updates along the way, until the latest macos update.  

The terminal no longer uses the preferred font.  

#### Expect: 
The terminal use the preferred font.

### System

OS: macOS 13.3 on M1
Version: Version 0.11.0-dev (1)

### Logs
[3.793833875s] [WARN ] [crossfont] Unable to load specified font Hasklug Nerd Font, falling back to Menlo
[3.809764958s] [ERROR] [alacritty] font FontDesc { name: "Hasklug Nerd Font", style: Specific("Light") } not found

### Other
I checked the macos font book to make sure the fonts were in order... All good here :/

**Comment by kchibisov** [comment]
>I checked the macos font book to make sure the fonts were in order... All good here :/

Is the font enabled though? The font could be listed, but be disabled in the Font Book.

**Comment by EdmundsEcho** [comment]
Thank you for the prompt follow-up. I did check for that prior to submitting the issue.  To your point, font book can flag fonts that were disabled b/c are no longer compatible or the like. It did not seem to be the case here. 

### The fix
I updated to the latest alacritty which fixed the issue.  May I suggest that you add this "fix" to the changelog?  (I did not see it but could have misread).  Otherwise, feel free to close the issue.


### Big positive feedback

This was relatively easy to fix b/c of the messages you post when the configuration fails for whatever reason.  Massive time saver.  _Thank you!!_
