### ISSUE TITLE
remove comment symbols for real fields in the default config

### ISSUE THREAD

**Issue by amtoine** [alacritty/alacritty#6826]
Somewhat related to https://github.com/alacritty/alacritty/pull/6673.
i'm talking about YAML but this might change to TOML in the future with #6673 :yum: 

i'm using the `nushell` shell which is focused on structured data and i wanted to do the following
- pull the default config file of `alacritty` from the repository
- modify only the fields i want to modify, e.g. theme and bindings
- dump the result as the final `alacritty.yml` file

this could be done with something like this in `nushell`
```bash
https://raw.githubusercontent.com/alacritty/alacritty/master/alacritty.yml
| update some.configuration.path { some_replacement_value }
...
| save --force ~/.config/alacritty/alacritty.yml
``` 

however, as the default config file only contains comments, i cannot simply replace the fields, i'd have to add them from scratch...

## :bulb: if the commented fields are the default values, i'd love to see them not commented so that we can use the config file in a structured way.

and i love this terminal emulator :crab: 

cheers :wave: :yum: 

### System

OS: linux
Version: `alacritty 0.12.0 (5a728195)`
Linux/BSD: X11 `picom` and `bspwm` at home, `wayland` and `ubuntu / gnome` at work

**Comment by kchibisov** [comment]
The config file is a reference of default values and documentation. You should only include in your config file lines you care about.

**Comment by amtoine** [comment]
> The config file is a reference of default values and documentation. You should only include in your config file lines you care about.
>
ooh ok i see :+1: 
thanks for the quick reply :relieved:
