### ISSUE TITLE
[macOS] Input after backspace is ignored for a short period of time

### ISSUE THREAD

**Issue by daletman** [alacritty/alacritty#6827]
### System

OS: macOS
Version: alacritty 0.11.0 (8dbaa0b)

### Logs
[Alacritty-0.11.0.log](https://github.com/alacritty/alacritty/files/11129046/Alacritty-52202.log)

When I hit the backspace key and very fast any other key, the other key input is ignored.
In the attached log file I started alacritty, typed the letters `asdf` and then hit backspace and `f` very fast.
The letter `f` does not appear in alacritty.
**I tested the same on Alacritty 0.10.1 and it does not have this issue** (using the same config and system)
Here is the logfile of 0.10.1 where I did exactly the same: 
[Alacritty-0.10.1.log](https://github.com/alacritty/alacritty/files/11129201/Alacritty-0.10.1.log)

I also tested with the default config, same problem.
Also tested other terminals (Terminal.app, iTerm 2, Kitty), they all work fine.
I couldn't test the latest Alacritty release because of #6817
Tested on Windows with Version 0.12.0 (5a728195), no issues there.

This bug is important for me because I constantly lose keyinputs when writing something in Alacritty.
I always thought it's caused by something else than Alacritty.

**Comment by chrisduerr** [comment]
Do you use a non-US locale?

**Comment by daletman** [comment]
Yes, german

**Comment by chrisduerr** [comment]
Could you try with US?

**Comment by daletman** [comment]
The input lag does disappear after switching the input source. It's there after starting Alacritty no matter if US or German, and it goes away after switching the input source (from US to German or vice versa)

**Comment by chrisduerr** [comment]
Do you have any third-party software installed that interacts with the keyboard in any way?

**Comment by daletman** [comment]
I use Alfred Snippets but even with them disabled the problem is the same

**Comment by chrisduerr** [comment]
> I use Alfred Snippets but even with them disabled the problem is the same

Could you uninstall this program to test?
