### ISSUE TITLE
Spawning a new alacritty window OR a new tmux window?

### ISSUE THREAD

**Issue by 097115** [alacritty/alacritty#6831]
Was thinking about making some sort of a universal binding that

  - would create a new tmux window IF there's already a running tmux instance in the current terminal
  - OR would open a new alacritty window otherwise

So, I tried the obvious: `command: { program: "sh", args: ["-c", "[ -z $TMUX ] && alacritty || tmux new-window"]}`. But, of course, the program runs not in the current terminal, and therefore `$TMUX` is always empty.

But may be some other workaround is possible? Would be grateful for a hint :)

**Comment by chrisduerr** [comment]
You cannot get any information about the current running shell in Alacritty's bindings without hacks, because the terminal is the shell's parent and thus has a different environment.
