### ISSUE TITLE
In tmux, some hotkeys stop working

### ISSUE THREAD

**Issue by 097115** [alacritty/alacritty#6832]
When running `tmux` in `alacritty`, some of the default hotkeys stop working:

  - the default `alacritty.yml` has `<Control-Shift-u>` mapped to toggle the "Hints" mode: after starting `tmux`, it stops working;
  - same with `<Shift-PgUp / PgDn / Home / End>`: by default, they navigate the scrollback, and yet under `tmux` they return the following sequences: `^[[5;2~ / ^[[6;2~ / ^[[1;2H / ^[[1;2F` but do not scroll.

platform: Linux x86_64
terminal: alacritty 0.11.0
multiplexer: tmux next-3.4
`$TERM`: tmux-256color (same with alacritty)
alacritty's `--print-events`: http://ix.io/4stA (`<C-S-u>` was pressed)
tmux's `-vv` had literally nothing in their logs with the timestamp when the hotkey was pressed)

**Comment by chrisduerr** [comment]
Tmux manages scrollback itself, Alacritty has no way to access that.

The hints mode is likely just stuff being broken over multiple lines I'd assume.

**Comment by 097115** [comment]
@chrisduerr 

> The hints mode is likely just stuff being broken over multiple lines I'd assume.

Could you elaborate? It was exactly the same `ls` output, which worked without tmux, and stopped working when in tmux.

**Comment by chrisduerr** [comment]
Tmux is a terminal emulator, it will reprocess escape sequences and filter the ones it doesn't understand.
