### ISSUE TITLE
Setting title doesn't work in terminals launched via 'msg create-window' when instance was created with `--title`

### ISSUE THREAD

**Issue by hiredman** [alacritty/alacritty#6836]
Hello,

When I launch a terminal with "alacritty" that terminal's title is updated with the running command / pwd as I do stuff in it. When I launch` a terminal with "alacritty msg create-window" the title isn't being updated, it just stays as "Alacritty"

the zsh snippet responsible for updating the terminals title is:
```
case $TERM in
    xterm*|alacritty)
        preexec () {
	    print -Pn "\e]0;$1\a"
	}
	precmd () {
	    print -Pn "\e]0;$PWD\a"
	}
        ;;
esac
```

### System

OS: Fedora Linux 39 (Rawhide Prerelease)
Version: alacritty 0.10.1
Linux/BSD: X11 i3wm

**Comment by kchibisov** [comment]
Maybe your snippet is not being red in this case?

I'd assume that if you manually request to set title with one of those escapes it'll work just fine.

**Comment by hiredman** [comment]
if I run `print -Pn "\e]0;FOO\a"` in the shell (zsh) the title of the alacritty terminal window remains "Alacritty"

so no, it doesn't work just fine in that case either

**Comment by kchibisov** [comment]
Are you sure that you're not disabling title setting somewhere in the config or launch with the `--title`? You can try default config `alacritty --config-file=/dev/null` and then create by `alacritty msg create-window`.

**Comment by hiredman** [comment]
Ah, I see, somewhere I did launch another alacritty with --title, and now all my terminals are children of that process, and those are the ones where setting the title isn't working.

It seems like either children of alacritty process started with `--title` should be able to set their own title, or those children should use the title set with `--title` too.

**Comment by kchibisov** [comment]
Hm, yeah, you're correct.

I think we shouldn't persist the `--title` on the CLI for the terminals created with the `alacritty msg create-window`.

Not sure about the binding though, what do you think @chrisduerr ? The issue is that running `alacritty --title foo` will create an instance with title `foo`, but then `alacritty msg create-window` will create a window with fixed title `Alacritty`(default).

**Comment by chrisduerr** [comment]
Should probably be persisted, yeah.

**Comment by kchibisov** [comment]
Persisted or reset to dynamic one? I think we should reset to dynamic, because `alacritty msg create-window` has the `--title` option?

**Comment by chrisduerr** [comment]
Honestly I don't really care either way.

**Comment by shmibs** [comment]
making children handle their own titles dynamically would be appreciated here (until then children are unusable because they can't be differentiated in window switcher 😅
