### ISSUE TITLE
login shell is not reflect the real status after changing default shell'

### ISSUE THREAD

**Issue by gzm55** [alacritty/alacritty#6839]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: macOS
Version: alacritty 0.12.0 (5a72819) and should affects versions since 0.11.0

### Logs

Crashes: no crash

from [here](https://github.com/alacritty/alacritty/blob/8a838710e37665f5bdeb8c01d2f1d3e6fec976a6/alacritty_terminal/src/tty/unix.rs#L151) Alacritty detects the default shell from `$SHELL` env first. On MacOS, after changing the default shell by `chsh` and before os rebooting, the Alacritty launching from launchpad still use the old shell. A possible solution is that if parent process is launchd or pid 1, we should always get shell/user/home from passwd.

Here is the process tree when not config shell in alacritty.yml printed in ~/.zshenv

```bash
-+= 00001 root /sbin/launchd
 \-+= 05968 user /Applications/Alacritty.app/Contents/MacOS/alacritty
   \-+= 05993 root /usr/bin/login -flp user /bin/zsh -c exec -a -sh /bin/sh
     \-+= 05996 user -sh
       \-+= 06109 user pstree -p 5996
         \--- 06110 root ps -axwwo user,pid,ppid,pgid,command
```

To view the env when alacritty starts from launchpad, i set the shell part in the alacritty.yml as:

```yaml
shell:
  program: /bin/sh
  args:
    - -c
    - "printenv && exec /bin/sh"
```

The output of `printenv` contains the old shell `SHELL=/bin/sh`. After rebooting the system, the output reflects the SHELL is correct.

**Comment by chrisduerr** [comment]
Working as intended.
