### ISSUE TITLE
Cannot type anything

### ISSUE THREAD

**Issue by nathan22x3** [alacritty/alacritty#6840]
I've just upgraded to the latest version, and now I'm cannot type anything in the console. But, when I run it using iTerm with the `alacritty` command, then it works as normal. Not really any keystrokes cannot be type, some still can display like `Ctrl + C`, `Ctrl + [0-9]`

### System

OS: macOS 13.1
Version: `0.12.0 (5a72819)`

**Comment by chrisduerr** [comment]
https://github.com/alacritty/alacritty/issues/6817
