### ISSUE TITLE
Alacritty windows are not "separate" anymore on macOS...

### ISSUE THREAD

**Issue by tjatjagithub** [alacritty/alacritty#6841]
I updated Alacritty over MacPorts on my Mac M1 (latest Monterey) to version 0.12.0 (1) and noticed that the best feature of Alacritty seems to be gone:

That each window can be handled separately in the Dock.

Until the update, each instance of Alacritty had it's own icon in the Dock and could be brought to the front individually.
This is gone.

Is there a way to configure the older behavior somehow?
Or would I need to downgrade again?

Many thanks for any hint!

P.S.

Is there any other way to get help or support for Alacritty?
Or only over issues on github?

### System

OS: macOS
Version: 0.12.0 (1) over MacPorts

**Comment by kchibisov** [comment]
Change the `Command + N` binding to `SpawnNewInstance` instead of `CreateNewWindow` in `alacritty.yml`. https://github.com/alacritty/alacritty/blob/2df8f860b960d7c96efaf4f059fe2fbbdce82bcc/alacritty.yml#L878

>Or only over issues on github?

https://github.com/alacritty/alacritty#irc

**Comment by tjatjagithub** [comment]
Fantastic, this solved my issue!!!

Many many thanks!
