### ISSUE TITLE
Update Synchronized updates to use CSI instead of DCS

### ISSUE THREAD

**Issue by kchibisov** [alacritty/alacritty#6845]
We already support `DCS`, however the majority is using `CSI 2026`

https://gist.github.com/christianparpart/d8a62cc1ab659194337d73e399004036?permalink_comment_id=3946967

The `CSI` was brought up on the `terminal-wg` after 2 years of stall, and when alacritty already implemented the `DCS`.

We could simply drop the `DCS`, because it's not what is used by the tui libraries anyway.

**Comment by chrisduerr** [comment]
https://github.com/alacritty/vte/pull/96
