### ISSUE TITLE
Truncated text on copy to clipboard

### ISSUE THREAD

**Issue by compilenix** [alacritty/alacritty#6848]
### Issue Description
Copy selection gets truncated to about 65k chars.

I'm not that experienced with rust but poked a little around and maybe this is useful:
- The final call where the text gets cut occures somewhere around here: https://github.com/alacritty/alacritty/blob/d40198da53f4c1c882901e364aca59e9b2ef2367/alacritty/src/clipboard.rs#L73
- I've added a debug log message right before that to log the length of `text`, which is actually correct.
- I've replaced `text` with a temporary variable initialized with about 2 MiB of text from a file using `include_str!("clip.txt")`. The length is correct but after the text gets passed into `clipboard.set_contents()` it's truncated again
- I've created a minimal test app using the example code and the same `include_str!("clip.txt")` of [copypasta/examples/hello_world.rs](https://github.com/alacritty/copypasta/blob/94e44c83dbaf08582309b297f0ae3b1b8cd1b17c/examples/hello_world.rs) and that does actually works as expected, the clipboard is not truncated.

### Steps to reproduce
- Build & Run
- Generate output larger then about 65k chars, I used `journalctl --since today --no-pager`
- Select all
- Copy to clipboard using default keybinding `Ctrl+Shift+C`
- Paste clipboard into other application, i.e. VS Code or gedit

### System

OS: Linux - Fedora 37 Workstation (Gnome3 Wayland)

Version: alacritty 0.12.0 (via `cargo install alacritty`) and alacritty 0.13.0-dev (commit d40198da53f4c1c882901e364aca59e9b2ef2367)

### Logs

Crashes: N/A

Config: [alacritty.txt](https://github.com/alacritty/alacritty/files/11184617/alacritty.txt)

Font/Terminal size: `alacritty -vv` -> [Alacritty.log](https://github.com/alacritty/alacritty/files/11184609/Alacritty.log)

Keyboard and bindings: `alacritty --print-events` -> [Alacritty.log](https://github.com/alacritty/alacritty/files/11184607/Alacritty.log)

**Comment by kchibisov** [comment]
Yeah, that's a known issue with our Wayland clipboard. The limitation arises from the linux pipe limitation.

**Comment by compilenix** [comment]
I could've misunderstood you, but the issue is not present when using the example code ([copypasta/examples/hello_world.rs](https://github.com/alacritty/copypasta/blob/94e44c83dbaf08582309b297f0ae3b1b8cd1b17c/examples/hello_world.rs)) of the crate which Alacritty uses. That example code does not write async to the `fd`, afaik.
