### ISSUE TITLE
alacritty + tmux colors seem not right

### ISSUE THREAD

**Issue by nathan22x3** [alacritty/alacritty#6850]
### System

OS: `macOS 13.1`
Version: `alacritty 0.11.0 (8dbaa0b)`

### Issue

Text in emphasized state (I think so) covered by solid backgrounds that should be their foreground.

I used to fixed this issue by set `TERM` to `xterm-256color`, but now it happening again.

![Screenshot 2023-04-10 at 09 38 17](https://user-images.githubusercontent.com/67423224/230814517-5b8db804-9924-44f2-8213-74c69906ed24.png)

**Comment by chrisduerr** [comment]
Not an Alacritty issue.
