### ISSUE TITLE
Install: Optional custom config dir path?

### ISSUE THREAD

**Issue by JesseKoldewijn** [alacritty/alacritty#6852]
### System

OS: ```Windows```
Version: ```alacritty 0.12.0 (5a728195)```

### Suggestion
Would be nice if the winget package of alacritty could get an optional config path directory option during install. This is also used on the AutoHotkey package on winget and it would make cross-platform config setups a lot easier.

**Comment by kchibisov** [comment]
We don't package anything for windows in winget(or for any other platform, except doing the `.app` and `.msi` things), so contact your package maintainers instead.

**Comment by JesseKoldewijn** [comment]
Aight check! Can't find any details on who the maintainer of the winget package would be tho but hey. Hooray windows bs with the lack of info on packages...
