### ISSUE TITLE
Add sanity tests for event loop handling

### ISSUE THREAD

**Issue by kchibisov** [alacritty/alacritty#6853]
It would be nice to have a general tests for event loop handling. For example
that we don't mark frame `dirty` when certain events like `KeyboardInput` arrive,
or `Paste` is happening. We already do have some logic for mouse input tests, but it's sort of artificial.

The starting point for such tests would be an event handler point inside the `event.rs`, and every
function, meaning that every function in a call graph should be present inside the test as it's in
the non testing code. That would mean that the real `ActionContext` should be tested, and not the
one have purely for tests.

Some assistance from `winit` maybe be required for example a fake loop, to simulate `run_return`.

This won't allow testing OpenGL operations, but not that it matters, the test runner could simply
never call the `draw`, and it's not even needed anyway.

The motivation behind it to prevent us from drawing when we shouldn't do so, given that in
the past we had a situations where the `dirty` flag was set to `true`. See b86667b2989dca71bd584227e5878c89f6888605 (Remove redundant dirty updates).

The dirty bit is critical for latency, given it simply tells when we draw a frame and submit to system compositor.

**Comment by chrisduerr** [comment]
This seems more like an end-to-end than a unit test. The `dirty` example doesn't really seem like a great excuse for this considering it would require writing precise tests for every single possible action. And for other stuff our reftests should be able to cover things.

So I'm not entirely sure what precisely you want to achieve here. It seems far too generic and far-reaching.

**Comment by kchibisov** [comment]
I want to have more robust input testing from winit events. Ref-tests are terminal based, so they can't do anything at all for the stuff I want to test.

We have some basic bindings tests in `input.rs`, but they don't show anything how complex pipelines work, whether the input is suppressed, whether the input resulted in redraw, how reaction to IME events is done, and so on.

I don't want to write a test for each action, what I want is to take `Vec<Event>` and shred into event processor, and simply check the state of it, so it's not unit tests, but rather integration test suite.

It's simply to ensure that we have sane handling of winit events in our code paths, I don't want to check every action in isolation.

**Comment by chrisduerr** [comment]
> I want to have more robust input testing from winit events

There is no reason to **ever** drive the event loop for anything other than full end-to-end tests.

> they don't show anything how complex pipelines work

They don't need to. Testing complicated stuff is complicated, it's a waste of effort. We should break those complicated things down into simple things and test those instead.

> It's simply to ensure that we have sane handling of winit events in our code paths, I don't want to check every action in isolation.

If you don't want to check things in isolation and you don't want to perform full end-to-end tests, then I don't think you're writing efficient tests tbh. That just sounds like a clusterfuck rather than a robust testing setup.

**Comment by kchibisov** [comment]
>If you don't want to check things in isolation and you don't want to perform full end-to-end tests

I think what I want is full end-to-end tests?

I simply want the following

```rust
let events: Vec<WindowEvent>;
for event in events {
    let context = ActionContext { ..  };
    context.handle_event(event);
    assert!(context.is_dirtry());
}
```

I'd at least like to experiment how we can test winit's event handling, given that we can't really make GUI sanity tests.

**Comment by chrisduerr** [comment]
That is a completely inappropriate test which I will not add to Alacritty. Testing Rust's `match` statement is completely pointless.

**Comment by kchibisov** [comment]
How would you suggest to test our responces to sequences of events?

For example what I want is to define a keystroke sequence:
```
// This is a pseudo code
let input = vec![
    KeyboardInput { char: "C", modifier: Control | Shift },
    KeyboardInput { char: "X" },
];

```

And that the resulted action context has fields properly set, like *chars are not suppressed* and **the terminal doesn't need a redraw**?

I'm not testing a `rust`'s match(I don't even see how I'm testing it), I'm testing the handler of event which requires the `ActionContext`, because every handler does is updating the `ActionContext` state.

Leave alone keyboard, I could test `Touch` events to ensure that the gesture is set appropriately to the input pattern.

**Comment by chrisduerr** [comment]
> How would you suggest to test our responces to sequences of events?
>
> For example what I want is to define a keystroke sequence:

Call `key_input` twice, it's really not that difficult.
