### ISSUE TITLE
Alacritty overwrites current line when text overflows

### ISSUE THREAD

**Issue by cod1r** [alacritty/alacritty#6855]
When text overflows the current line (in the case when the alacritty window cannot fit the entire line), alacritty doesn't draw the text properly and overwrites the current line.

I expect it to wrap onto another "line" (not really another line but it looks like another line. Basically it should wrap).

### System

OS: Linux/Arch Linux

Version: alacritty 0.12.0 (5a728195)

Using Wayland/SwayWM

The GIF is quite slow. I don't use ffmpeg a lot, sorry.

![alacritty_issue](https://user-images.githubusercontent.com/52897699/231582944-b6348036-880a-482b-9662-ec575edb90d9.gif)

**Comment by kchibisov** [comment]
Could you try in `sh`?

**Comment by cod1r** [comment]
Ok i think the problem was with my bash prompt. I apologize for the inconvenience.
