### ISSUE TITLE
Alacritty does not render correctly double byte emoji

### ISSUE THREAD

**Issue by D3vil0p3r** [alacritty/alacritty#6857]
Alacritty is not able to render correctly double-byte emojis like ⚔️ as all other terminal emulators (kitty, terminator, gnome-terminal, xfce4-terminal and many others). On Alacritty it is shown as
![image](https://user-images.githubusercontent.com/83867734/231693786-2d278533-64fa-47f3-afca-23398f4f6e2f.png)

that is not correct.

Single byte emojis work correctly. Please fix.

**Comment by kchibisov** [comment]
The symbol you've showed is single char wide character in the unicode standard.
