### ISSUE TITLE
`colors.transparent_background_colors` does not apply to selections

### ISSUE THREAD

**Issue by imsuck** [alacritty/alacritty#6859]
### System
OS: Linux
Version: alacritty 0.12.0 (5a728195)
Linux/BSD: X11, picom and i3

The configuration option `colors.transparent_background_colors` does not not apply to selections. It doesn't matter whether you set `colors.selection.background` or not.

No selections
![image](https://user-images.githubusercontent.com/49095435/231982808-10474589-e5d7-4d40-97da-a2e034052b22.png)
Selection without setting `colors.selection.background`
![image](https://user-images.githubusercontent.com/49095435/231982893-f3ad3036-1a08-4c3c-9fd3-fe16d2959b4b.png)
Selection with `colors.selection.background`
![image](https://user-images.githubusercontent.com/49095435/231982993-15881cfb-a22a-40a0-87f1-446e67ca1876.png)

**Comment by SonuBardai** [comment]
question: Is this the issue? We expect the selected color to have the same alpha value as the bg? 

https://github.com/alacritty/alacritty/assets/67749330/67724d23-48d1-46df-955a-8e7f88c0efd8

**Comment by kchibisov** [comment]
@SonuBardai yes, the `window.opacity` value should be used for selection as well.

**Comment by kchibisov** [comment]
Well, you could open a PR and we could discuss it there.
