### ISSUE TITLE
Box drawing font support for legacy computing characters

### ISSUE THREAD

**Issue by al1-ce** [alacritty/alacritty#6860]
Related to #5809 

Box drawing support doesn't include "Legacy Computing" characters that are ranging from U+1FB0x	to U+1FBFx [Wiki Link](https://en.wikipedia.org/wiki/Box-drawing_character#Symbols_for_Legacy_Computing)

Which results in same problem as it was with normal box drawing characters

![image](https://user-images.githubusercontent.com/60989682/231986496-6d4869ef-1592-4a71-a233-f08b3cefcf1d.png)

**Comment by chrisduerr** [comment]
Adding all the characters in the range to our built-in font makes absolutely no sense. Could you be more specific about which characters you would like to see supported?

**Comment by al1-ce** [comment]
I would say most important would be angled ones that are in U+1FB36-U+1FB66 (or maybe also up to U+1FB6F)

**Comment by chrisduerr** [comment]
Yeah it's absolute nonsense to add a bunch of random slopes and shapes to the built-in characters. The goal here isn't to allow drawing arbitrary shapes in the terminal, it's to remove artifacts with TUIs.

If you want custom graphics in your terminal, you should look into image escape sequences (none of which Alacritty officially support yet).

**Comment by kchibisov** [comment]
I think the only box drawing stuff we could add is something mainline, like powerline symbols, given that the amount of them is quite small(4 base version, and around 16 extra from more advanced).
