### ISSUE TITLE
Noticed a weird way to create tabs [BUG?]

### ISSUE THREAD

**Issue by ChaseRensberger** [alacritty/alacritty#6871]
Not sure if this is OS specific but I know that Alacritty doesn't support tabs by default and it is recommended to use tmux or something instead. I noticed that the shortcut for creating a new Alacritty instance ("CMD + N"), instead will create a tab if Alacritty is in fullscreen mode. I was not sure if this was a bug or not but figured I would post it here regardless.

![Screenshot 2023-04-19 at 12 25 25 AM](https://user-images.githubusercontent.com/52985426/232966787-5b33b6e9-702a-4436-871e-acf7399c6dfe.png)

### System

OS: macOS (13.3.1 (22E261))
Version: alacritty 0.12.0 (5a72819)

**Comment by kchibisov** [comment]
Tabs on macOS are provided by the macOS, so no extra action is required from the alacritty side.

You can control such behavior inside the general macOS settings(prefer to open new window in tab/window).

**Comment by ChaseRensberger** [comment]
Sorry, for the confusion. Thanks for the help.
