### ISSUE TITLE
In system monitoring tools like bottom,gotop the graph part is not displayed properly

### ISSUE THREAD

**Issue by yogeshdcool** [alacritty/alacritty#6872]
### System

OS: Linux
Version: alacritty 0.12.0 (5a728195)
Linux/BSD: X11,dwm,picom

### Problem
__When using system monitoring (bottom), the graph part is not displayed properly  
I tried changing the font but nothing changed__

### This is how it looks in alacritty
![alacritty](https://user-images.githubusercontent.com/84368844/232988884-f013e47e-77c9-4bb1-bb48-c185d3a28ab5.png)

### This is how it looks in kitty
![kitty](https://user-images.githubusercontent.com/84368844/232988965-dee02054-584e-4ddd-a486-4ffd3d0fc81f.png)

### Alacritty and Kitty
![diff](https://user-images.githubusercontent.com/84368844/232989449-43ef48f9-5fd2-4769-866c-0e2ece49af67.png)

**Comment by chrisduerr** [comment]
Working as intended.

**Comment by yogeshdcool** [comment]
> Working as intended.

Can you please say what do you mean?

**Comment by lbfalvy** [comment]
@kchibisov Would a PR for this likely be accepted?

**Comment by kchibisov** [comment]
Well you can try and see how it looks.

**Comment by chrisduerr** [comment]
For most of our internal glyphs the motivation behind drawing them internally is that they're purposefully included into Unicode to enable text-based UIs, maybe with the small exception of powerline which still doesn't really serve any other purpose.

I find it hard to justify custom-drawing braille symbols, considering they have a very specific purpose which is **not** for rendering graphs in the terminal (which is what they're commonly abused for).

**Comment by kchibisov** [comment]
tbf, braille has a purpose in real world, but on the screen where you can't fill them with your fingers they are quite useless.

**Comment by j4james** [comment]
Braille on a computer screen can still be used by sighted or visually paired people to learn the system, or even just to get a general idea of what it looks like when reading an article on the subject. The whole point of the font is to simulate the look of real-world Braille.

You may still decide that pseudo graphs are of more value to your users than legitimate Braille usage, but I think it's unfair to suggest that Braille on a computer screen is useless.

**Comment by lbfalvy** [comment]
It's not that braille on a computer screen is useless, but specifically in a terminal emulator I think it's more likely to appear either as graphics or an unused side effect of a workflow that involves both tts and a braille display, than as learning material.

I definitely agree that the distinction between geometric shapes and meaningful graphemes co-opted for TUIs is a useful one though, so maybe it's worth considering a separate config option to disable these.

**Comment by yogeshdnumb** [comment]
I resolve it by replacing gnu-free-fonts with noto-fonts
