### ISSUE TITLE
Feature request: config option to display COLxROW in titlebar

### ISSUE THREAD

**Issue by sfsam** [alacritty/alacritty#6875]
It would be useful to have a config option to display the window's dimensions in the title bar. 

The Mac Terminal.app does this. The displayed dimensions change as the window is resized:
<img width="412" alt="Screenshot 2023-04-19 at 9 01 23 PM" src="https://user-images.githubusercontent.com/118104/233255260-21f0ab18-2ae9-4a48-8020-bc0203b66804.png">

The option would work in conjunction with the `resize_increments` option. If both are `true`, then the window dimensions would be appended to the end of the window title.

**Comment by chrisduerr** [comment]
Why?

**Comment by kchibisov** [comment]
You can set the title yourself to have `COLxROW`, no need to do anything extra from alacritty.

**Comment by sfsam** [comment]
@kchibisov Just for my information, how do I set the title to dynamically show the dimensions?

**Comment by kchibisov** [comment]
Set it in `pre_cmd` in zsh to include `$COLUMNS` and `$LINES` somewhere.

`printf "\e]2;${LINES}x${COLUMNS}\a"`

**Comment by sfsam** [comment]
Thank you, that's what I figured, but it doesn't really work since it doesn't update as you resize the window. You have to at least press return to see the new size. Also, every other terminal app I've looked at on macOS shows the dimensions dynamically. This is standard behavior. So even if you had a functioning shell implementation (which may not be possible), it would produce redundant info for all terminal apps other than Alacritty. So your `.zshrc` wouldn't be portable or would have to have a special case just for Alacritty.

I hacked together something to illustrate an unobtrusive implementation. The dimensions could alternatively be shown always like in Terminal.app:

https://user-images.githubusercontent.com/118104/233724434-7661f0bb-05c6-4bfa-b796-1bb5c9cdec27.mov

FWIW, it's here: https://github.com/sfsam/alacritty/commit/8bdab379bf3e13899b940788bd04c840370f76b6 I don't know the Alacritty code base, or even Rust for that matter, so I'm sure my implementation is problematic. But I'm guessing a proper job of it wouldn't be a lot of code and this functionality really belongs in the app, not the shell.
