### ISSUE TITLE
Large number of open files

### ISSUE THREAD

**Issue by MaxBareiss** [alacritty/alacritty#6877]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: FreeBSD 13.1-RELEASE-p6 amd64
Version: `alacritty 0.12.0-dev (77855806)`
Linux/BSD: X11, i3

### Logs

I upgraded from alacritty 0.11.0 to 0.12.0, but when I run alacritty, it opens hundreds of files per second and I quickly hit the `kern.openfiles` limit, making alacritty unusable. I have bisected the change and the first bad commit is d92a8a0e16eda3df7566e5c995aa0d258b6b76f7 .

**Comment by kchibisov** [comment]
Do you have reference cycles in your configuration files or anything like that?

**Comment by MaxBareiss** [comment]
This is my config file:
```
font:
  normal:
    family: "Perplexed"
    style: Regular
  size: 8.0
```

**Comment by chrisduerr** [comment]
Does this issue go away when you remove your config file?

**Comment by chrisduerr** [comment]
Can you try with a configuration file that is just an empty file, not a symlink or hardlink or anything either.

**Comment by MaxBareiss** [comment]
The issue also occurs with a normal empty file.

**Comment by kchibisov** [comment]
It could be `notify` crate just being bugged? Could you provide `strace`(not sure if such thing exists on bsd) and `alacritty -v` log.

**Comment by chrisduerr** [comment]
Does it get fixed when moving the config file to ~/.config/alacritty/alacritty.yml?

**Comment by MaxBareiss** [comment]
That resolves the issue, thanks!

**Comment by chrisduerr** [comment]
I don't think there's any action worth taking here. Unless a BSD developer wants to contribute which would happen upstream not here.
