### ISSUE TITLE
printf '\e[?1000l' does not remove mouse x y position reports (SOLVED)

### ISSUE THREAD

**Issue by cattyhouse** [alacritty/alacritty#6880]
### System

OS: macOS
Version: alacritty 0.12.0 (5a72819)

### Steps to reproduce

1. on remote_server : ~/.tmux.conf : set -g mouse on
2. on alacritty : run these commands sequently `ssh remote_server ; tmux new ; killall sshd`, this will emulate tmux behavior when ssh connection exit abnormally 
3. on alacritty : click mouse on any window area, mouse x y position get reports, this is [tmux behavior when sshd exits abnormally](https://superuser.com/questions/802698/disable-mouse-reporting-in-a-terminal-session-after-tmux-exits-unexpectedly)
4. on alacritty: `printf '\e[?1000l'` or `printf '\033[?1000l'` does not remove **mouse x y** position report, click/wheel still shows **mouse x y** position reports.

### Other attempts:

1.  run `printf '\e[?1000h'` then `printf '\e[?1000l'`, **mouse x y** position reporting can be removed, but wheel up/down becomes arrow up/down, which navigate command history instead of scrolling the buffer history

2. `printf '\ec'` , do a hard reset, this will remove **mouse x y** position reporting, but all buffer got cleared. 

EDIT:

SOLVED by https://github.com/alacritty/alacritty/issues/6880#issuecomment-1520309855

**Comment by chrisduerr** [comment]
Can you reproduce this without tmux and ssh? This does not sound like an Alacritty issue.

**Comment by chrisduerr** [comment]
You can enable it yourself with `printf '\e[?1000l'`.

**Comment by kchibisov** [comment]
When tmux is being used, tmux is a terminal emulator, it's up to tmux to remove the mouse mode. So troubleshoot with tmux and not alacritty.

I'm not sure how it's not clear that tmux is **also a terminal emulator**.

**Comment by kchibisov** [comment]
There's an option to do `alacritty -vvv | grep -i mouse`, and you should mouse mode changes. If `unset` is not invoked then nothing alacritty can do.

**Comment by chrisduerr** [comment]
Sounds like it works just fine?
