### ISSUE TITLE
[Not Bug] A round cornered logo on macOS?

### ISSUE THREAD

**Issue by cattyhouse** [alacritty/alacritty#6882]
Now:

this logo does not fit with other logos

<img width="422" alt="Screenshot 2023-04-24 at 23 07 05" src="https://user-images.githubusercontent.com/3365320/234041322-5a5dca6b-4edf-4080-98b9-bd5a97b9c5dd.png">

After: 

just a showcase, round corner is good enough, total round like this is too much

<img width="399" alt="Screenshot 2023-04-24 at 23 07 44" src="https://user-images.githubusercontent.com/3365320/234041247-b37fccaf-7927-415d-828c-6e47b65fecf9.png">

**Comment by kchibisov** [comment]
We don't distribute icon themes packs. You can use any icon you want with alacritty though. It's not that common on macOS though(you don't even need to rebuild anything).
