### ISSUE TITLE
Alacritty crashes on startup in Asahi Linux

### ISSUE THREAD

**Issue by TheMG95** [alacritty/alacritty#6889]
I am on Asahi Linux with the experimental GPU drivers installed. The app crashes before even starting the UI. This happens in Hyprland but does not happen in KDE with Wayland.

### System

OS: Asahi Linux
Version: alacritty 0.12.0 (5a728195)
Linux/BSD: Hyprland

### Logs

Crashes: STDERR, STDOUT
```Error: There was an error initializing the shaders: Failed linking shader: error: output location 0 >= GL_MAX_DUAL_SOURCE_DRAW_BUFFERS with index 1 for alphaMask

warning: queue 0xffff0c000ca0 destroyed while proxies still attached:
  zwp_primary_selection_device_v1@25 still attached
  zwp_primary_selection_device_manager_v1@21 still attached
  wl_data_device@24 still attached
  wl_seat@23 still attached
  wl_data_device_manager@22 still attached
  wl_registry@20 still attached
warning: queue 0xaaabb3b15070 destroyed while proxies still attached:
  xdg_wm_base@34 still attached
  wl_output@15 still attached
  wp_fractional_scale_manager_v1@14 still attached
  xdg_activation_v1@13 still attached
  zwp_text_input_manager_v3@12 still attached
  zwp_relative_pointer_manager_v1@11 still attached
  zwp_pointer_constraints_v1@10 still attached
  zxdg_decoration_manager_v1@9 still attached
  wl_seat@8 still attached
  wp_viewporter@7 still attached
  wl_subcompositor@6 still attached
  wl_compositor@5 still attached
  wl_shm@4 still attached
  wl_registry@2 still attached
Error: "Event loop terminated with code: 1"
```

**Comment by chrisduerr** [comment]
> with the experimental GPU drivers installed

So why are you reporting this to Alacritty? That sounds very much like it's due to driver issues.

**Comment by TheMG95** [comment]
I wasn't sure who to report this to, but I thought reporting a single app to a distro would be too specific of an issue. I'm sorry to waste your time.

**Comment by kchibisov** [comment]
It seems like your driver claimed something it doesn't support. Try `alacritty -o debug.renderer=gles2_pure`.

>Error: There was an error initializing the shaders: Failed linking shader: error: output location 0 >= GL_MAX_DUAL_SOURCE_DRAW_BUFFERS with index 1 for alphaMask

Also, next time you post a log anywhere, please, ensure that everything is visible in a preview. Because the key message was hidden unless you vie the issue in the mailbox(not everyone is doing so).

**Comment by kchibisov** [comment]
@TheMG95 are you running the latest asahi mesa driver? I was told that it was fixed like a while ago.

**Comment by TheMG95** [comment]
@kchibisov running it with `alacritty -o debug.renderer=gles2_pure` works and I am on the latest asahi mesa driver.

**Comment by kchibisov** [comment]
It would still worth to bring upstream if you can ensure that it doesn't work with latest mesa driver you can build yourself.

The issue is blend_func_extended is getting exposed, while it's not working, and I was told that required checks are in place.

it's not an alacritty issue anyway.

**Comment by kchibisov** [comment]
For now just set the renderer in the config to `gles2_pure`.
