### ISSUE TITLE
6037701436055211

### ISSUE THREAD

**Issue by Usrwrr** [alacritty/alacritty#6894]
https://github.com/alacritty/alacritty/blob/ead65221ebe06ff5689e65b866d735d4365d0e9e/CHANGELOG.md?plain=1#L1041

**Comment by Usrwrr** [comment]
https://github.com/alacritty/alacritty/blob/ead65221ebe06ff5689e65b866d735d4365d0e9e/CHANGELOG.md?plain=1#L1039

**Comment by kchibisov** [comment]
????

**Comment by Usrwrr** [comment]
6894

**Comment by kchibisov** [comment]
Sounds like you're a robot.
