### ISSUE TITLE
Feature Request: change window: padding: x: to a u16 integer instead of a u8 integer

### ISSUE THREAD

**Issue by tompflynn** [alacritty/alacritty#6900]
I have a config file I use for newsboat (a terminal RSS reader) where I set window: padding: x:255
this works pretty well, but I want to use a value higher than x:255

screenshot for reference:
![image](https://user-images.githubusercontent.com/129278154/236119376-7e302d67-948b-49ba-9b81-56111c9a75d6.png)
I want to make this even narrower, and x being a u16 would allow me to do that.

**Comment by chrisduerr** [comment]
On the one hand this is completely ridiculous and there's absolutely no way this is the best solution for this problem.

On the other hand this change should not have any drawbacks.

There is no chance in hell I'll open a PR to explicitly support this. But considering that it should be a trivial patch, I'm inclined to just accept it and pretend nobody is actually using it.
