### ISSUE TITLE
Alacritty crashes with the us-international keybaord layout

### ISSUE THREAD

**Issue by zilverjk** [alacritty/alacritty#6902]
I Have a macOS 13.3.1 using M1 Pro silicon. In a tmux session im typing ' or " or some characters that needs completion because of the layout input in the keyboard that Im using. Alacritty freezes and I have to force quit the app and relauch to work properly again. this happens when I'm using it for a short period of time. Is very rare.

**Comment by kchibisov** [comment]
Sounds like duplicate of #6817.

You could try the latest master, which just got a fix for it.
