### ISSUE TITLE
Interacting with a Windows instance over ssh results in broken output

### ISSUE THREAD

**Issue by r-ml** [alacritty/alacritty#6904]
As the title suggests, Windows 10+ (since 1809) distributes an the openssh server as an optional feature. Accessing it through alacritty is fine, simple commands work as expected. The issue comes when you try run an interactive program, such as the fish shell or neovim. Here's `alacritty/src/event.rs` in neovim after a little bit of scrolling:
![neovim](https://user-images.githubusercontent.com/23126780/236583659-d1f4c66e-24a0-43f7-a1f2-de5b9737ec5b.png)

I confirmed the brokenness does not happen in vte based terminals. 
### System

OS: Fedora 37/38
Version: 0.12.0
Linux/BSD: GNOME 43 and 44

**Comment by kchibisov** [comment]
I'd assume your tmux is running on remote server?

I'd suggest to connect with `TERM=xterm256-color ssh` to such thing though.

**Comment by chrisduerr** [comment]
Most definitely not an Alacritty issue. Likely term as @kchibisov mentioned.

**Comment by r-ml** [comment]
> I'd assume your tmux is running on remote server?
I'm not. I'm running tmux on the client.
> I'd suggest to connect with `TERM=xterm-256color ssh` to such thing though.
That works!

Thank you!
