### ISSUE TITLE
Auto escape/quote pasted URLs

### ISSUE THREAD

**Issue by amogusussy** [alacritty/alacritty#6905]
In Terminals like kitty, when you paste a link, it puts the link in quotes.
In alacritty, if the link contains the `&` character, the program gets spawned in the background as a seperate process.
Could we get a feature where it quotes any pasted text that matches a regular expression for URLs?
For example, if I were to copy and paste this:

    https://example.org/search?q=example&t=0

it would be pasted as:

    "https://example.org/search?q=example&t=0"

This would avoid the issue stated above.

**Comment by kchibisov** [comment]
This is shell dependent, so shell should handle that. zsh offers `url-quote-magic` to solve exactly that problem.

**Comment by amogusussy** [comment]
@kchibisov 
Kitty's got a feature like that, so it isn't just shell dependent.
Also, not everyone uses ZSH.

**Comment by kchibisov** [comment]
The shell quoting and use of `ticks` is dependent per shell (what if your shell doesn't use `"` at all?, what if you don't need to escape `&`?).

Not every shell is a posix shell, so you only shell can do that reliably, and it's dead simple to do in shell.

I think fish-shell could do that as well.

**Comment by amogusussy** [comment]
Could it be implemented as an option in alacritty.yml then?
Off by default, but available to those who use shells that either don't escape by default, or don't use `"`.

**Comment by amogusussy** [comment]
>what if you don't need to escape &?

That's a really rare case though. If it matches a regex search for a URL, chances are, you don't want it to act as the `&` char would in standard bash/sh.
If you do need it, you could just manually remove the quotes for this one particular string.

**Comment by kchibisov** [comment]
The shell should do bracketed-paste mode. If it doesn't, url quoting is the least issue you could possibly have.

The url quoting is done based on bracketed paste mode in the shell. If you want to alter paste command you are free to patch the sources yourself.

I'm not interested for such hacks upstream.
