### ISSUE TITLE
My prompt arrow looks extremely scuffed

### ISSUE THREAD

**Issue by reDpz** [alacritty/alacritty#6906]
![image](https://user-images.githubusercontent.com/71374038/236640197-83a4ade5-063b-49b6-b845-55c8fe9cad59.png)

On linux X11, left terminal is st and right is alacritty.

Alacritty version

```
alacritty 0.12.0 (5a728195)
```

**Comment by kchibisov** [comment]
I'd argue that the left one is also scuffed, but you can disable `builtin_box_drawing` in `font` section.
