### ISSUE TITLE
Double backtick freezes window

### ISSUE THREAD

**Issue by j4m350n** [alacritty/alacritty#6908]
Typing
```
``
```

then moving cursor with arrow keys freezes window.

### System

OS: macOS
Version: alacritty 0.12.0 (5a72819)

### Logs

No crash, no logs. Events are appear in in cli, but are not processed.

**Comment by chrisduerr** [comment]
Is the shell still responsive? So can you do `echo "test" > /tmp/test` for example while Alacritty is frozen?

**Comment by kchibisov** [comment]
Would suggest to try latest rc on release page.

**Comment by ranomier** [comment]
On Linux, Arch, KDE 5.27.4, X11and fish shell it doesn't freeze.

**Comment by kchibisov** [comment]
Have you tried selecting or pressing `ctrl + q`? If selection changes it's not frozen then.

**Comment by kchibisov** [comment]
>@kchibisov I use the latest version via homebrew, and the last version on the release page.

What you've showed wasn't the latest version, this is the latest one https://github.com/alacritty/alacritty/releases/download/v0.12.1-rc1/Alacritty-v0.12.1-rc1.dmg

**Comment by steinbrueckri** [comment]
@kchibisov sorry for the misunderstanding, you are right with the 0.12.1-rc1 the issue is fixed.
