### ISSUE TITLE
Cannot type in Devanagari Script

### ISSUE THREAD

**Issue by jeffilluminati** [alacritty/alacritty#6911]
OS: Linux
Version: `alacritty 0.13.0-dev (ead6522)` 
Linux/BSD: KDE Wayland

Hi, I am trying to type in the Devanagari script, and I am getting unsupported Unicode symbols when I try to type in the Halanta  '्' symbol, or if type in vowel diacratics "  े ा ि    ी   " for half-consonants. 

Here is the screenshot of the error 
![image](https://user-images.githubusercontent.com/56787162/236777113-736b88d4-7c1c-497f-baa7-3ce1d3f2a390.png)

**Comment by kchibisov** [comment]
that's a zsh issue/feature. Would suggest to look into it instead. I don't remember the exact setting in it to stop doing so, sorry.
