### ISSUE TITLE
OS error 9 at start

### ISSUE THREAD

**Issue by hholst80** [alacritty/alacritty#6916]
When I start alacritty this error message pops up. It came up after a package upgrade on the system. I have also rebooted without any change.

### System

OS: Linux (Fedora 37 x86_64)
Version: alacritty 0.12.0
Linux/BSD: X11 , i3 (i3 version 4.22)

### Logs

![image](https://github.com/alacritty/alacritty/assets/6200749/9e60d170-eca7-4344-8bdc-c5ec03a47a8d)

![image](https://github.com/alacritty/alacritty/assets/6200749/1e06edb2-ec6b-4ca9-a73d-288de69bd06e)

Xorg -version:

```
X.Org X Server 1.20.14
X Protocol Version 11, Revision 0
Build Operating System:  6.2.9-200.fc37.x86_64
Current Operating System: Linux goblin 6.2.14-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Mon May  1 00:57:50 UTC 2023 x86_64
Kernel command line: BOOT_IMAGE=(hd0,gpt2)/boot/vmlinuz-6.2.14-200.fc37.x86_64 root=UUID=1bcf48dc-8101-4a4f-9e49-ae17b188b5eb ro rd.driver.blacklist=nouveau modprobe.blacklist=nouveau nvidia-drm.modeset=1 initcall_blacklist=simpledrm_platform_driver_init rhgb quiet rd.driver.blacklist=nouveau modprobe.blacklist=nouveau nvidia-drm.modeset=1 initcall_blacklist=simpledrm_platform_driver_init
Build Date: 25 April 2023  12:00:00AM
Build ID: xorg-x11-server 1.20.14-23.fc37
Current version of pixman: 0.40.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
```

**Comment by kchibisov** [comment]
>OS: Linux

Could you be a bit more specific here? Which distribution?

I'd assume that with `live_config_reload: false` in the config file it works fine?

**Comment by hholst80** [comment]
```config
NAME="Fedora Linux"
VERSION="37 (Thirty Seven)"
ID=fedora
VERSION_ID=37
VERSION_CODENAME=""
PLATFORM_ID="platform:f37"
PRETTY_NAME="Fedora Linux 37 (Thirty Seven)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:37"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f37/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=37
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=37
SUPPORT_END=2023-11-14
```

**Comment by hholst80** [comment]
> > OS: Linux
> 
> Could you be a bit more specific here? Which distribution?
> 
> I'd assume that with `live_config_reload: false` in the config file it works fine?

No error then, works fine.

**Comment by alebastr** [comment]
I'm unable to reproduce the issue, but it could be related to the way we build Rust packages in Fedora - we attempt to minimize the number of packaged crates and thus some dependencies may have different versions compared to the Cargo.lock or official builds.

@hholst80, can you try the package from <https://copr.fedorainfracloud.org/coprs/build/5909555/> and see if it addresses the problem or results in a different error?

**Comment by chrisduerr** [comment]
Where is your config file stored and is it modified during startup?

**Comment by hholst80** [comment]
I will try the fix the next time I am at the office.  It will be a couple of days.

My config file is stored in XDG_CONFIG_HOME (not set) so $HOME/.config/alacritty/alacritty.yml

It is just a regular file, but $HOME is placed on a separate partition not on the ROOT partition.

**Comment by chrisduerr** [comment]
Trying to move it to root and starting with `--config-file` might be worth a try.

**Comment by anjanv21** [comment]
--config-file I'd assume that with live_config_reload: false in the config file it works fine?

**Comment by hholst80** [comment]
> I'm unable to reproduce the issue, but it could be related to the way we build Rust packages in Fedora - we attempt to minimize the number of packaged crates and thus some dependencies may have different versions compared to the Cargo.lock or official builds.
> 
> @hholst80, can you try the package from https://copr.fedorainfracloud.org/coprs/build/5909555/ and see if it addresses the problem or results in a different error?

![image](https://github.com/alacritty/alacritty/assets/6200749/177eee46-8932-4f24-b442-9f054e14622e)

**Comment by chrisduerr** [comment]
Alacritty should not have a significant amount of files that are being watched with inotify.

If someone does run into this issue anyways I'd recommend making sure Alacritty is in its own directory without any other files and not having any configuration file imports.
