### ISSUE TITLE
Crash on FreeBSD/arm64

### ISSUE THREAD

**Issue by avysk** [alacritty/alacritty#6922]
### System

OS: FreeBSD 13.2 on **arm**64
Version: 0.12.0
X11, mate, marco

Please notice that I am running over VNC (TigerVNC), but I cannot reproduce the problem on amd64 machine, same versions of FreeBSD/TigerVNC/alacritty/mate. I have tried both installing FreeBSD package and doing `cargo install alacritty`, with the same result.

### Logs

❯ RUST_BACKTRACE=full alacritty -vvv
Created log file at "/tmp/Alacritty-38560.log"
[0.000001520s] [INFO ] [alacritty] Welcome to Alacritty
[0.000159922s] [INFO ] [alacritty] Version 0.12.0
[0.000189802s] [INFO ] [alacritty] Running on X11
[0.000313283s] [INFO ] [alacritty_config_derive] No config file found; using default
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /wrkdirs/usr/ports/x11/alacritty/work/alacritty-0.12.0/cargo-crates/glutin-0.30.7/src/api/egl/display.rs:343:44
stack backtrace:
   0:     0x6667e77cbcd4 - <unknown>
   1:     0x6667e76d95ac - <unknown>
   2:     0x6667e77b51d0 - <unknown>
   3:     0x6667e77cbaec - <unknown>
   4:     0x6667e77b01d8 - <unknown>
   5:     0x6667e77b0bdc - <unknown>
   6:     0x6667e77cc000 - <unknown>
   7:     0x6667e77cbf98 - <unknown>
   8:     0x6667e77b05d0 - <unknown>
   9:     0x6667e76cffc8 - <unknown>
  10:     0x6667e76d008c - <unknown>
  11:     0x6667e76e9570 - <unknown>
  12:     0x6667e76e9054 - <unknown>
  13:     0x6667e7635a18 - <unknown>
  14:     0x6667e75d1f3c - <unknown>
  15:     0x6667e7631474 - <unknown>
  16:     0x6667e76606f4 - <unknown>
  17:     0x6667e7659f00 - <unknown>
  18:     0x6667e7593f24 - <unknown>
  19:     0x6667e7680de4 - <unknown>
Abort trap (core dumped)

There is, indeed, `.unwrap()` call in a specified place in glutin sources without any checks, but the call is chained and the code is beyond my knowledge of Rust. I can debug it further, but I will need some instructions.

**Comment by kchibisov** [comment]
First of all I wonder why you get an abort, do you build the `panic = abort` (though maybe it's different on FreeBSD). The call which `unwrap` is more like an assert.

The reason for it is that `you've got an error from calling display related function`, but the driver haven't propagated that error while it should according to the spec. I'd need a backtrace and a link to `mesa` sources(the thing you have installed) and the driver you were using (in mesa).

Is using `LIBGL_ALWAYLS_SOFTWARE=1` fixes anything?

**Comment by avysk** [comment]
Looking at `mesa` was a good idea. I have noticed that amd64 system has the packages `graphics/mesa-libs` and `graphics/mesa-dri` installed, and arm64 system did not have them. Installing the packages fixed the crash, even though I'd like to mention that crashing at `unwrap()` (as opposed to sensible error message in, say, `expect()`) was not the best diagnostics in the world.

Sorry for the trouble and thank you for your help!

**Comment by kchibisov** [comment]
This `unwrap` is basically an assert to driver violating the EGL specification. Though, I'd add a better message instead of unwrap to that.
