### ISSUE TITLE
Alacritty `window.opacity` isnt set for character backgrounds.

### ISSUE THREAD

**Issue by max-ishere** [alacritty/alacritty#6930]
### Actual behavior

When setting `window.opacity` the background does become transparent, but if the characters have background colors they don't have any opacity.

![screenshot](https://github.com/alacritty/alacritty/assets/47008271/2fe2e985-8668-4af3-b54e-921a2d2dffd1)

As you can see there is a black area where `btop` is rendering, a blue border - that's the window's border and the gray area between.

### Expected behavior

Have the gap less noticeable.

### Potential solutions

Have `text.opacity` (or other YAML key) to set the opacity of the character background.

### System

OS: Arch Linux
Version: alacritty 0.12.0 (5a728195)
Linux/BSD: Wayland (Sway)

**Comment by kchibisov** [comment]
https://github.com/alacritty/alacritty/blob/6e7f466c68b387f41726757eed4f3e70d05479d2/alacritty.yml#L346
