### ISSUE TITLE
title bar always uses dark mode with gnome 43 on wayland

### ISSUE THREAD

**Issue by joeyh** [alacritty/alacritty#6932]
Alacritty comes up with a dark grey title bar, whether or not gnome's Dark Mode is enabled. When switchng between the modes in the gnome settings, alacritty's title bar remains the same color.

I don't have decorations_theme_variant set. Also tried with it set to None with same result.

That's with alacritty rendering with wayland. Setting WINIT_UNIX_BACKEND=x11 makes the title bar update to reflect changes to Dark Mode.

### System

OS: Linux, Debian unstable
Version: `alacritty 0.11.0
Wayland, Gnome 43

**Comment by kchibisov** [comment]
The setting you've mentioned is available since `0.12.0`.
