### ISSUE TITLE
[feature request] `--fullscreen` option (as an alias to `-o window.startup_mode=Fullscreen`)

### ISSUE THREAD

**Issue by Quantenzitrone** [alacritty/alacritty#6940]
`--fullscreen` is a rather common option for terminal emulators, as all these terminal emulators implement this interface:
cool-retro-term sakura roxterm foot konsole terminology terminator xfce4-terminal
which is 8/30 terminal emulators for linux i tested

(notably, xterm uses `-fullscreen` and gnome-terminal and mate-terminal use `--full-screen`)

**Comment by kchibisov** [comment]
If the option is not named the same across the terminals, I don't see what is wrong with `-o window.startup_mode=Fullscreen`, yet it's longer, but the option already differs across the terminals.

Is there any motivation other than it being shorter? Is it defined by some specification? For now I don't see it being the case. CLI options alacritty exposes couldn't be represented by the config directly or widely adopted(like `--class` and `-T`/`-t`).

**Comment by Quantenzitrone** [comment]
the motivation is to make more options more widely adopted
also i'm writing a script that needs fullscreen and not needing to dig into the alacritty config options to find out that fullscreen at startup is `window.startup_mode=Fullscreen` and not needing a separate case handling for alacritty makes things easier

**Comment by kchibisov** [comment]
But you have 3 cases already(--fullscreen, -fullscreen, -full-screen) though? And 4th could be kitty for example uses `--start-as=fullscreen`.

The plain `--fullscreen` won't really make sense for alacritty, given that we need `start-as` like option, at this point it won't be any different than using config value.

**Comment by Quantenzitrone** [comment]
well you could also add `--maximize`
all the `--fullscreen` terminals except konsole and cool-retro-term have this option

but i understand if you don't see any use in adding simpler command line arguments for random configuration options

**Comment by Quantenzitrone** [comment]
wait no foot has `--maximized`

**Comment by kchibisov** [comment]
Yeah, we have 4 startup modes to begin with, not saying how many other options we have besides this setting. I don't think exploding CLI is a good idea (especially that we have sub commands and IPC config subcommands, it'll really get messy pretty fast).
