### ISSUE TITLE
[Feature request] Initial title name only

### ISSUE THREAD

**Issue by rieje** [alacritty/alacritty#6945]
Like `--title` where it sets the title but then lets applications change it after (it seems `--title` gets set permanently for the window).

Example of a use use is autostarting terminal applications like tmux with a predictable initial title in a tiling window manager which can then matched to perform actions like moving to another workspace. The title should be allowed to change dynamically afterwards for tmux or any application.

The "problem" is that it is hacky to create window rules for a tiling window manager like i3/sway for applications that change window titles. For instance, with  `alacritty --command tmux`, if you're trying to match tmux's dynamic window naming, the window start with the default "Alacritty" window name until tmux gets launched and then the window moves when tmux sets the window title a brief moment later. Using `--title` would have rule apply to the Alacritty window immediately to solve this visual delay but prevents tmux from dynamically setting window titles because it sets the title window permanently.

**Comment by chrisduerr** [comment]
Why wouldn't you just use window class for this? This just seems like a problem with your configuration.

**Comment by rieje** [comment]
Besides "title", there's only "app_id" to match window name for Sway/Wayland which is "Alacritty" for Alacritty.

**Comment by kchibisov** [comment]
`--title` disables the dynamic change of the title. If you want a title which doesn't disable the title change during the runtime, use the `-o` option.

**Comment by kchibisov** [comment]
>Besides "title", there's only "app_id" to match window name for Sway/Wayland which is "Alacritty" for Alacritty.

Passing `--class foo` will set `app_id` for alacritty, as stated in the docs for this option.

`Defines window class/app_id on X11/Wayland [default: Alacritty]`
