### ISSUE TITLE
Tabs or Multiple Processes running on Mac?

### ISSUE THREAD

**Issue by 825i** [alacritty/alacritty#6948]
### System

OS: Mac 13.3.1 (a) (22E772610a)
Version: `0.12.1`

Is it possible to run multiple alacritty processes in tabs or even separate windows? It seems only possible to run one. I can run multiple instances of the official Mac terminal however.

**Comment by kchibisov** [comment]
Have you tried pressing `Command + N`? The setting to run in tabs is in general **macOS**(not alacritty) preferences `New window in tabs`.
