### ISSUE TITLE
Bolder fonts after update

### ISSUE THREAD

**Issue by olzhasar** [alacritty/alacritty#6956]
I recently updated alacritty via `brew` and fonts inside the terminal became much bolder then they were before and very hard on eyes. I tried setting `AppleFontSmoothing` to 0 and it became thinner in contrast. Neither option matches the look that was there before. It's especially noticeable in `vim`.

### System

OS: macOS
Version: alacritty 0.12.1 (5fdfd47)

**Comment by kchibisov** [comment]
From which version you've updated? The font rendering wasn't affected for a year or two at least.

**Comment by olzhasar** [comment]
@kchibisov It's been a while since I last updated tbh, but I don't think it's a year or two.

**Comment by kchibisov** [comment]
How were you setting font smoothing? I have a feeling that you've said it wrong. It should be `org.alacritty` and not `io.alacritty` anymore.

**Comment by olzhasar** [comment]
I just ran:
```
defaults write -g AppleFontSmoothing -int 2
```
in my terminal. Should I do it differently?

**Comment by kchibisov** [comment]
Hm, should be it, but it may require a restart(of the system).

I've seen things like 

`defaults -currentHost write -g AppleFontSmoothing -int 0`

**Comment by chrisduerr** [comment]
Setting the fontsmoothing option is one thing you can try, but if that doesn't fix it you're simply out of luck.

Font rendering in Alacritty is only changed when the new solution is considered more correct for the specific target platform. We make zero guarantees about maintaining the look of previous Alacritty versions.

So unless you're aware of some incorrect font rendering decisions made in our core-text rendering logic, you're unfortunately out of luck.
