### ISSUE TITLE
(extra/alacritty.man): No such file or directory

### ISSUE THREAD

**Issue by elmarsan** [alacritty/alacritty#6960]
Last commit breaks building process https://github.com/alacritty/alacritty/commit/e3746e49a117ebf8d1f43715554c5a1cf8d4a116

It seems extra/alacritty.man has been removed recently. 

### System

OS: Linux
Linux/BSD: X11/Wayland, DE or Compositor and WM

### Logs

`gzip: can't stat: extra/alacritty.man (extra/alacritty.man): No such file or directory`

**Comment by kchibisov** [comment]
https://github.com/alacritty/alacritty/commit/e3746e49a117ebf8d1f43715554c5a1cf8d4a116

FWIW before opening an issue like that, I'd suggest to see what the commit actually changed.

We changed the build so if you haven't updated it, it's on you.
