### ISSUE TITLE
Remove mouse double_click/triple_click options

### ISSUE THREAD

**Issue by chrisduerr** [alacritty/alacritty#6962]
There's really no reason why these would be configurable. I've never seen anyone changing them and the defaults are perfectly reasonable.

If someone **really** isn't happy with them, recompiling isn't that big of a deal.

**Comment by SonuBardai** [comment]
Would it make sense to do something like this to remove these config options? I was just playing around with the changes, so I'm not raising a PR for it. Lmk if we prefer having PRs

https://github.com/SonuBardai/alacritty/commit/409cc86ce2ae77af09716b149a09a4593491d7fa

**Comment by chrisduerr** [comment]
Please open a PR.
