### ISSUE TITLE
Alacritty shuts down when Time limit is initiated on macOS

### ISSUE THREAD

**Issue by daweth** [alacritty/alacritty#6965]
Whenever screentime is initiated, i.e (Time Limit: You've reached your limit on X.) on macOs, Alacritty shuts down and closes unexpectedly. This should not happen And I should keep all of my terminals intact.

### System

OS: macOS
Version: `alacritty --version` output: zsh: command not found: alacritty

**Comment by kchibisov** [comment]
I don't think we have control over that, maybe it's some apple setting or `.plist` property, or they decide if we use hardware acceleration, then we're not a regular application.

Anyway, I'm not sure regular applications has control over it, would suggest to look into how macOS decides what to close or not.

**Comment by chrisduerr** [comment]
Will close this issue unless there's clear evidence that this needs to be explicitly handled by Alacritty.

**Comment by daweth** [comment]
**Potential Fix:**

Settings -> Screen Time -> Always Allowed -> Check 'Alacritty'
