### ISSUE TITLE
KDE Great but DWM (Chadwm) Font Size Huge but all other Terminals Normal  

### ISSUE THREAD

**Issue by thorrrr** [alacritty/alacritty#6966]
I have been using a forl of dwm  (Chadwm) on my desktop no issue i always use Alcritty as defualt 
I recently installed KDE-Chadwm combo on my laptop which has a 4k screen
Alacritty is fine in KDE but in Chadwn on startup the font is HUGE but if i test other terminals Konsole KItty ST etc they all look fine but Alacritty is Huge font i know you can ctrl - to get it o but i do not want to do that each time i open the terminal which is many times a day.
My query is if i edit fonts in conf file and make it look ok when i go back to KDE it will be tiny?
Just curious if i can get round this! The other terminals do not sufer with this issue ?
Thorrrr
https://paste.centos.org/view/6014e3c2

[Untitled - Pastebin Service](https://paste.centos.org/view/6014e3c2)
Untitled From WebUI, 4 Hours ago, written in Plain Text. This paste will shuffle off the mortal coil in 19 Hours. URL https://paste.centos.org/view/6014e3c2 Embed
Thorrrr
xrandr  https://paste.centos.org/view/b58c7aa0

[Untitled - Pastebin Service](https://paste.centos.org/view/b58c7aa0)
Untitled From WebUI, 4 Hours ago, written in Plain Text. This paste will explode in 19 Hours. URL https://paste.centos.org/view/b58c7aa0 Embed Download Paste
https://paste.centos.org/view/e4e98720

[Untitled - Pastebin Service](https://paste.centos.org/view/e4e98720)
Untitled From WebUI, 4 Hours ago, written in Plain Text. This paste will go to meet its maker in 19 Hours. URL https://paste.centos.org/view/e4e98720 Embed

**Comment by kchibisov** [comment]
set `WINIT_X11_SCALE_FACTOR=1` env on `Xft.dpi: 96` in .Xresources.

**Comment by thorrrr** [comment]
Hi 
Sorry only just getting into Arch Linux, but when i look at my .Xresources file i see no mention of Alacritty or WINIT_X11_SCALE_FACTOR=1?

https://paste.centos.org/view/ab231b47

**Comment by kchibisov** [comment]
The `WINIT_X11_SCALE_FACTOR=1` is a env variable, it should be set before running alacritty.

The setting you've linked has `! Xft.dpi: 96` you should remove leading `! `, because it's a comment.

**Comment by thorrrr** [comment]
Hi kchibisov
So i think i understand 
I just add the following lines 
WINIT_X11_SCALE_FACTOR=1 to alacritty config file ?
Then in .Xresources uncomment the line 
Xft.dpi:   96
Is that correct?

**Comment by kchibisov** [comment]
Oh, I wrote in initial reply `on` not `or`. You need either winit env variable **or** Xft.dpi change.

**Comment by thorrrr** [comment]
Cheers working great now  :)
