### ISSUE TITLE
DECCRA Support (Copy Rectangle, CSI-$v)

### ISSUE THREAD

**Issue by jwp** [alacritty/alacritty#6969]
This is not commonly supported among emulators(xterm, terminology, ms terminal, contour?), but it seems pretty useful for optimizing small scrolls and window moves. Repainting small areas isn't a terrible price, but, with larger displays, having some way to reduce the expense of small-and-many scroll operations in large areas would be helpful.

https://terminalguide.namepad.de/seq/csi_sv_t_dollar/
https://www.vt100.net/docs/vt510-rm/DECCRA
http://web.mit.edu/dosathena/doc/www/ek-vt520-rm.pdf

terminalguide appears (?) to be documenting xterm's treatment of the sequence. The latter two document the usage of page numbers in addition to the source area and destination point. Only interested in the displayed "page" myself.

**Comment by kchibisov** [comment]
It would be nice to know which applications are using them. I remember that some of them were implemented by tmux, however tmux relied on xterm specific behavior in some edge cases, so other terminals decided to not support them.

**Comment by jwp** [comment]
tmux's commit mentioning DECCRA: https://github.com/tmux/tmux/commit/df31f1dfc9c3bc0d638648de23dc276ed03d3347
And it's removal: https://github.com/tmux/tmux/commit/6307d63715b7509b56384214d7a605e022c678bb

**Comment by kchibisov** [comment]
So we have a VT5xx feature which is not really used by anyone? If you do small area repainting it's simpler to move cursor and write there, so the only issue is scrolling, which is hard to use, generally. There's an escape used by tmux, which is https://github.com/alacritty/alacritty/issues/160 .

**Comment by jwp** [comment]
DECSLRM + DECSTBM + AL/DL(Might be some alternatives there). Worth a try.

**Comment by jwp** [comment]
Looks like that combination works in iterm2 and xterm. (Using SU/SD after adjusting the margins)

**Comment by chrisduerr** [comment]
I have no interest in reintroducing escape sequences that nobody has interest in. The scrolling margin that tmux switched to seem like a much more sensible feature.
