### ISSUE TITLE
Resizing sometimes causes alacritty to freeze

### ISSUE THREAD

**Issue by griffi-gh** [alacritty/alacritty#6972]
Can *always* reproduce while running `paru`.   
Not sure what triggers this issue specifically...  
(running with default config)

https://github.com/alacritty/alacritty/assets/45996170/445594f3-47be-4ab2-a8db-e197bac9266c

### System

**OS:** Arch Linux
**Version:** alacritty 0.12.1 (5fdfd47f)
**Display Server:** X.Org version: 21.1.8
**Kernel:** 6.3.5-zen1-1-zen
**DE:** Xfce 4.18

### Logs

- STDOUT (with `-vv`): [alacritty_stdout.log](https://github.com/alacritty/alacritty/files/11629561/alacritty_stdout.log)

**Comment by chrisduerr** [comment]
Does Alacritty freeze completely, or does it just stop redrawing?

If it is frozen completely, can you share the gdb backtrace?

**Comment by griffi-gh** [comment]
it doesn't seem to respond to anything except keyboard interrupts if started froma shell, can test more things tomorrow

**Comment by JOT85** [comment]
I've also had this issue using alacritty within i3 on X11. Downgrading does solve the problem. I'll install alacritty with debug symbols and see what's happening when I get a chance.

**Comment by amalgame21** [comment]
I have one laptop (amd cpu and gpu) and one desktop (amd cpu and nvidia), both with endeavouros.
Both use dwm, the laptop, always freeze after a resize or swap between two pane.
Downgrade to 11.0-2 solved the issue on the laptop. (12.0-1 also freeze)
But the desktop is fine with 12.1-1

**Comment by kchibisov** [comment]
@amalgame21 have you tried the branch I've linked (#6958)?

**Comment by kchibisov** [comment]
`git clone https://github.com/kchibisov/alacritty -b winit-update`.

**Comment by kchibisov** [comment]
Yeah, the error thing is expected it simply tells that your bindings are not compatible with the branch, because keyboard input changed. it'll work without any messages once you resolve the issue (comment out your bindings or update the way they look on the posted branch).

you could simply press `cross` on that bar though.

I pointed that branch, because it accumulates all the changes from the upstream windowing crates meaningful to alacritty to simplify transition.

**Comment by marvinborner** [comment]
I have the same issue on 0.12.1 using Arch Linux and DWM. The window freezes/crashes quite reliably on heavy resizing (like opening many windows on a tiling WM).

Moreover, I personally run a single instance of Alacritty and open every additional window using `alacritty msg create-window`. A freeze causes *all* Alacritty windows to freeze -- quite annoying.

Building from newest commit 2ad28b5 seems to fix the issue. @kchibisov's branch works too. Please let me know if you need more information or some `bisect`ing -- my reproducible test is `zathura *.pdf` in a directory with a bunch of PDFs btw (on a tiling WM).

**Comment by kchibisov** [comment]
@marvinborner I know what broke it, it's basically ensuring that it's the same root cause. no bisect is required.

**Comment by SrBurns-rep** [comment]
I'm having the same issue #7005

**Comment by lcbm** [comment]
Sorry for the late reply, just wanted to confirm that @kchibisov's fix indeed solved my issue! I tested with the same commit as @marvinborner: https://github.com/alacritty/alacritty/commit/2ad28b53782b6cf1b08dc4b37719c07e51f445fb

I did the test around a week ago but totally forgot to update the thread -- work has been been demanding, sorry :sweat_smile:
