### ISSUE TITLE
[Help Wanted] How can I write keybindings to launch VSCode from the current directory, similar to `code .`?

### ISSUE THREAD

**Issue by GZTimeWalker** [alacritty/alacritty#6975]
How can I write keybindings to launch Visual Studio Code from the current directory, similar to `code .`?

I have tried the following YAML configuration:

```yml
key_bindings:
  - { key: E, mods: Command, command: { program: "code", args: ["."] } }
```

However, I encountered the error message `[alacritty] Unable to launch code with args ["."]`. Is there a way to utilize environment variables or any other method to achieve this?

I am currently using macOS.

**Comment by kchibisov** [comment]
If you run just `code` is it working?

**Comment by GZTimeWalker** [comment]
oh... sorry, I fixed this with a full path like `/usr/local/bin/code`, and it works.
