### ISSUE TITLE
Alacritty on Wayland does not respect gnome cursor settings

### ISSUE THREAD

**Issue by sounak-kun** [alacritty/alacritty#6981]
Running alacritty on wayland does not pick up the custom mouse cursor set using gsettings. Running alacritty with xwayland using `WAYLAND_DISPLAY= alacritty` however, makes it pick up the custom cursor. 
The cursor has been set using Gnome Tweaks (for user) and `gsettings set` (for GDM profile).

### System

OS: Linux
Version: alacritty 0.12.1
Linux/BSD: Wayland, Gnome, Fedora 38 Workstation

[Screencast from 2023-06-06 09-51-16.webm](https://github.com/alacritty/alacritty/assets/93094402/a9e399b1-5df5-448e-ba6c-b5773dbc1c69)

**Comment by kchibisov** [comment]
works as intended, on Wayland each client sets the cursor the way they prefer. It'll change in the future once everyone supports the new cursor protocol(including gnome ofc).

For now, use `XCURSER_THEME` env variable.
