### ISSUE TITLE
alacritty + ncurses 6.4_20230520-1 = vim E349

### ISSUE THREAD

**Issue by graevy** [alacritty/alacritty#6984]
Mirroring "E349: No identifier under cursor" documented [here](https://github.com/vim/vim/issues/12499) and [here](https://www.reddit.com/r/vim/comments/1414ndw/how_to_fix_e349_no_identifier_under_cursor/). I'll email the ncurses maintainers if this is too downstream.

### System

OS: Arch Linux, X11, i3wm
Version: alacritty 0.12.1 `5fdfd47f`

### Logs

[alac.txt](https://github.com/alacritty/alacritty/files/11687359/alac.txt)

**Comment by chrisduerr** [comment]
If you read the vim issue, you'll notice that it was fixed in vim. This is not an Alacritty issue.
