### ISSUE TITLE
Is it possible to draw bright colors with normal font?

### ISSUE THREAD

**Issue by gadefox** [alacritty/alacritty#6986]
The variable `draw_bold_text_with_bright_colors` (see yaml) draws bold text with bright colors when `true`, right? Could you please implement similar variable `draw_bright_colors_with_bold` (the default is `true`)? This would print text using normal font for all bright colors when `false` and that's what I'm looking for now. Ta

**Comment by kchibisov** [comment]
No, such setting doesn't have any objective reasoning unlike the original one, because old terminal applications used bold attribute to request bright text. Using bold for bright colors sounds arbitrary and you could simply add bold attribute (in editor or wherever you want to).

**Comment by j4james** [comment]
@kchibisov I think what they may be asking is how to get `SGR 1` to select brighter colors, but leave the font weight as normal, i.e. the way the original hardware terminals worked.

I'm not sure if there's an easier way to accomplish this, but I know one way it can be achieved is by changing the bold font style to `Regular`.

@gadefox Have a look at this section of the config:

https://github.com/alacritty/alacritty/blob/4b92388396c6da783809c7ce511b5cf6be8a0624/alacritty.yml#L139-L148

You'll need to uncomment the appropriate bits (don't forget the root `font` element), and set the `style` to `Regular`. You may also want to adjust the `bold_italic` style so it's just `Italic`.
