### ISSUE TITLE
No manual entry for alacritty in section 5, Arch linux

### ISSUE THREAD

**Issue by Ddystopia** [alacritty/alacritty#7003]
### System

OS: Arch Linux
Version: alacritty 0.12.1 (5fdfd47f)
Linux: X11

### Issue

I've installed alacritty with pacman:
```bash
> pacman -S alacritty
```
But there is no manual entry in section 5:
```bash
> man 5 alacritty
No manual entry for alacritty in section 5
```

I do have `man-pages` installed.

Can I provide some additional information? Thank you.

**Comment by Ddystopia** [comment]
Yes, man entry is rendered on github, but if it is stated in the README, I think it's good to install it too

**Comment by Ddystopia** [comment]
Oh, it was added 3 days ago. I didn't see it. Maybe repositories did not update at this point, closing for now.

**Comment by kchibisov** [comment]
You're reading the README for the current master. What you want is for `0.12.1` version.

The `man 5 alacritty` was added recently and not part of any release, so it's simply not available.
