### ISSUE TITLE
TOML configuration format is not well documented

### ISSUE THREAD

**Issue by proski** [alacritty/alacritty#7018]
There are several related issues with the new configuration format.

The manual format is not friendly to Windows and to many Mac OS users. A sample configuration file with full documentation was a better approach. Another approach would be to have a web page generated from the manual page.

Github rendering of the manual is pretty but incorrect. For instance, underscores are not removed. `<string>` was lost from the `import` description. https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd

There are some holdovers from the YAML format in the manual that won't work as written:

```
*dimensions* { columns = <integer>, lines = <integer> }
```

It's possible to write in in two ways, not sure which should be recommended:

Using the existing section:
```
[window]
dimensions.columns = 120
dimensions.lines = 36
```

Using a separate section:
```
[window.dimensions]
columns = 120
lines = 36
```

The `migrate` command is using the latter.

**Comment by chrisduerr** [comment]
> The manual format is not friendly to Windows and to many Mac OS users.

Manpages are supported on all platforms.

> A sample configuration file with full documentation was a better approach.

It was not.

> Another approach would be to have a web page generated from the manual page.

This is planned and might come in the future.

> There are some holdovers from the YAML format in the manual that won't work as written:

This is not a yaml holdover, it's an [inline table](https://toml.io/en/v1.0.0#inline-table).

> It's possible to write in in two ways, not sure which should be recommended:

Whichever one you like more.

> The migrate command is using the latter.

The migrate command makes no stylistic choices and just goes with the default representation for serialization.

**Comment by kchibisov** [comment]
Or you could write, which what man page sort of says.

```toml
[window]
dimensions = { columns = 120, lines = 36 }
```

**Comment by chrisduerr** [comment]
Yeah the manpage documentation picks this format for brevity, not as a style guideline, but it is definitely an option.
