### ISSUE TITLE
macos: Alacritty title isn't shown while switching apps with command tab

### ISSUE THREAD

**Issue by poige** [alacritty/alacritty#7020]
### System

OS: macos
Version: `alacritty 0.12.1 (5fdfd47)`

Basically the only text associated with the app's icon there is its name: "Alacritty" whereas the window itself is being title-set indeed.

**Comment by poige** [comment]
And I've to say I'm not that sure if it can be done anyways, seems no other apps icons are shown with anything but theirs names either:

![image](https://github.com/alacritty/alacritty/assets/600779/b82afd5e-b401-498c-86fe-cf22776c100c)

**Comment by kchibisov** [comment]
So according to what you're saying you don't know other applications showing title when switching? I think then it could be simply impossible to do, the title sometimes is very long as well so it'll look awkward.

Do you happen to know whether any other app can do so?

**Comment by poige** [comment]
So it's not a straight-forward one, closing then.
