### ISSUE TITLE
alacritty scroll shortcut not working in tmux

### ISSUE THREAD

**Issue by newyorkthink** [alacritty/alacritty#7024]
- { key: K, mods: Alt, action: ScrollPageUp }
- { key: J, mods: Alt, action: ScrollPageDown }

i test ,alacritty scroll shortcut in tmux not work

close tmux, alcritty scroll is work

**Comment by kchibisov** [comment]
Ofc, because tmux is your terminal emulator, you have to define shortcuts in it.
