### ISSUE TITLE
Config file is missing in github Release Assets

### ISSUE THREAD

**Issue by digika-ding** [alacritty/alacritty#7037]
No alacritty.toml was found.

**Comment by kchibisov** [comment]
See `alacritty.yml`.

**Comment by digika-ding** [comment]
> See `alacritty.yml`.

Please update 「Configuration」Section.

**Comment by kchibisov** [comment]
it's for master branch, not release builds.

**Comment by digika-ding** [comment]
> it's for master branch, not release builds.

Oh~ It looks like I am missing something. Thank you for your reply

**Comment by denppa** [comment]
> See `alacritty.yml`.

Do you know where this is in the code base? A github go to file search didn't reveal its location.

**Comment by kchibisov** [comment]
Or checkout commits before `toml` patches.

https://github.com/alacritty/alacritty/releases/download/v0.12.1/alacritty.yml

**Comment by denppa** [comment]
> Or checkout commits before `toml` patches.
> 
> https://github.com/alacritty/alacritty/releases/download/v0.12.1/alacritty.yml

Got it. I just grepped the repo and found that the config is no longer generated in the changelog. Thanks!
