### ISSUE TITLE
characters completely see-through

### ISSUE THREAD

**Issue by UltraBlackLinux** [alacritty/alacritty#7039]
Hey there,
I just upgraded my system today, and for some inexplicable reason, every single character that is not an empty once like a space is completely see-through (as if the window had 0% opacity at that spot). I can clearly see my wallpaper through these holes.
Text is still invisible when selected, but the colors appear in their background again.

I can confirm this issue with the default configuration

### System

OS: Arch Linux ARM [(pine64-arch)](https://github.com/dreemurrs-embedded/Pine64-Arch)
Version: alacritty 0.12.0 (5a728195) (Same issue on 0.12.1)
Linux/BSD: Wayland, Hyprland

### Logs
https://chonkyrabbit.eu/lettermbox/xoregt/

**Comment by kchibisov** [comment]
Could you try `alacritty -vv -o 'debug.renderer="gles2_pure"'?

Could be mesa broke something or alarm.

**Comment by UltraBlackLinux** [comment]
oh awesome, that fixes it! 

Will I have to live with this workaround or is that something I can expect to be fixed soon?

**Comment by kchibisov** [comment]
Report this to mesa or try downgrading mesa.

In the meantime, you could add

```yml
debug:
  renderer: gles2_pure
```

in the config as a workaround, you should mention that Dual Source Blending is broken for you.

**Comment by kchibisov** [comment]
Closing as not our issue.
