### ISSUE TITLE
How do I install alacritty man pages in macOS?

### ISSUE THREAD

**Issue by denppa** [alacritty/alacritty#7040]
### TLDR

Can `INSTALL.md` include the commands for installing man pages in macOS, or have brew include the man pages?

### System

MacOS

### Installation method

```brew install --cask alacritty```

### Expected Behavior

`man 5 alacritty` should pull up configuration man page

### Actual Behavior

running the above man command does not yield manual.

### Trouble Shooting Attempt

Cloned the repo, read build instructions, tried to install man pages manually that way, but the paths provided in https://github.com/alacritty/alacritty/blob/master/INSTALL.md are targeted for linux systems only.

**Comment by kchibisov** [comment]
We don't control the `brew`, but if I remember correctly they try to install man pages, it's just there wasn't a release yet. The man pages are part of the `.app` file and in the past brew installed them.

>Cloned the repo, read build instructions, tried to install man pages manually that way, but the paths provided in https://github.com/alacritty/alacritty/blob/master/INSTALL.md are targeted for linux systems only.

They are not linux only, you may need to create `man5` directory though.

**Comment by denppa** [comment]
@kchibisov 
But if you look at this:
> sudo mkdir -p /usr/local/share/man/man1

I don't think I should create a linux file hierarchy and install the man pages.

**Comment by kchibisov** [comment]
it's not a linux file hierarchy, it's a https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard which macOS follows.

**Comment by denppa** [comment]
So you are saying that I should create a literal `/usr` folder when it doesn't exist? Just want to make sure.

**Comment by kchibisov** [comment]
macOS removed the `/usr`? Mine mac has it, I know that brew resides in `/local`.

Anyway, you could wait for a brew update, it should bring new man pages https://github.com/Homebrew/homebrew-cask/blob/5d2583c1ca705a67ee5809331bf15c894fcf6c96/Casks/alacritty.rb#L28

**Comment by denppa** [comment]
Oh I must be blind, sorry for the mistake, mac does have a /usr.

**Comment by kchibisov** [comment]
You could add man pages into `$MANPATH` as man wants, so it could be anywhere you wish to put them.

**Comment by NReilingh** [comment]
I think this discussion is still missing the point. The latest brew cask installs `man alacritty` and `man alacritty-msg` but it does not install `man 5 alacritty` which is the config file documentation.

The brew cask installs these manpages from the `.app` package in the `.dmg` available from the GitHub releases page: https://github.com/alacritty/alacritty/releases/download/v0.12.1/Alacritty-v0.12.1.dmg

However, this package only contains `alacritty.1` and `alacritty-msg.1`, and omits `alacritty.5` and `alacritty-bindings.5`:

<img width="924" alt="Alacritty.app contents" src="https://github.com/alacritty/alacritty/assets/2458645/ec696406-8ead-4507-88f4-d50c4da120eb">

I think what needs to happen is the macOS release needs to include those two missing manpages; then the brew cask can install them as usual.

**Comment by kchibisov** [comment]
>I think this discussion is still missing the point. The latest brew cask installs man alacritty and man alacritty-msg but it does not install man 5 alacritty which is the config file documentation.

Because no release was made at all.

>I think what needs to happen is the macOS release needs to include those two missing manpages; then the brew cask can install them as usual.

They are not missing, they were not a thing in any of the present release.

**Comment by denppa** [comment]
Yes, I had to compile the git version from source to test run the toml format.

**Comment by kchibisov** [comment]
![picture](https://github.com/alacritty/alacritty/assets/27620401/25bbc0a6-6ced-489c-ad26-703aff9cb20a)
