### ISSUE TITLE
Configuration for the quit action when closing the last window.

### ISSUE THREAD

**Issue by MirageTurtle** [alacritty/alacritty#7042]
OS: macOS
version: alacritty 0.12.1 (5fdfd47)

First of all, I would like to sincerely thank the developers for their hard work and dedication.

And then, I hope that developers can add related configuration for the quit action when closing the last window, i.e., the user can config if Alacritty quits when the last window is closed.

Now, the quit action is yes. When I close the last window, Alacritty will quit. But for my personal habit is let the Emulator background, and when I need a new one, use `cmd`+`tab` to go the Emulator and use `cmd`+`N` to create a new window.

If it's not tricky, I hope this configuration very much.

Thanks again!

**Comment by kchibisov** [comment]
>Now, the quit action is yes. When I close the last window, Alacritty will quit. But for my personal habit is let the Emulator background, and when I need a new one, use cmd+tab to go the Emulator and use cmd+N to create a new window.

So you basically want https://github.com/alacritty/alacritty/issues/6593 ?

**Comment by MirageTurtle** [comment]
Sorry for late response. I checked #6593 . I think they have something in common and but different issues. I'm going to check whether #6593 can help me or not, maybe tomorrow (I'm in China). 

Thank you for your so quick response!

**Comment by MirageTurtle** [comment]
I double-check the issue #6593 . We both hope the author support the daemon mode actually, but different reasons. I'm just because my personal habits.

And by the way, the discussion in #6593 may not help me. The issue opener may need daemon mode for his/her application or program, but I need daemon mode after I close all windows of Alacritty.

What we need both can be settled by daemon mode, but what can settle that issue may not settle mine. :(

Sorry for my missing searching for #6593.

**Comment by kchibisov** [comment]
`Daemon mode` is supposed to exit only when you ask it to exit, not when you close all the windows, so it seems basically the same.

Since your goal is to not exit and their goal was to keep process around.

**Comment by MirageTurtle** [comment]
Yeah, that's right. But I still think the resolution of that issue can't help me because of the different situation. I also hope the author add daemon mode support.

**Comment by nixpulvis** [comment]
I believe the behavior @MirageTurtle is describing is also how the stock Terminal.app works. Closing all of its windows will not cause the application itself to close.

**Comment by kblissett** [comment]
I would also like alacritty to have the typical mac behavior of not closing the application automatically when the last window is closed.

**Comment by eli-yip** [comment]
Agree with @MirageTurtle , this feature is important for mac users. Hope developers can consider it.

**Comment by ftpd** [comment]
I would also benefit from this.

**Comment by chrisduerr** [comment]
Closing in favor of consolidation with daemon mode.

**Comment by ftpd** [comment]
Any link to this 'consolidation with daemon mode' issue/PR, so we can subscribe for it?  
Yes, sure, it's a "I'm lazy" question, but if you're closing something, it's nice to provide a link to the continuation.

**Comment by chrisduerr** [comment]
I'd check out https://github.com/alacritty/alacritty/pull/8167 and let me know if this is what you were looking for. See the comments of that PR for details.

**Comment by ftpd** [comment]
Nah, not really - someone creating this MR proposed hiding the icon etc. I would rather like it the way Safari/iTerm/many other macOS apps do - program is running without any window opened.

But I'm not the OP of this request and I won't die for it, so I fully understand it's now closed as wontfix/not relevant.
