### ISSUE TITLE
Kerning is terrible

### ISSUE THREAD

**Issue by martyn-smith** [alacritty/alacritty#7043]
Since 0.12.1, the kerning with any font, including monospaced fonts, is unreadable. Attached is neofetch output with alacritty on left, GNOME terminal on right.

### System

OS: EndeavourOS, 6.39-arch1-1
Alacritty version: 0.12.1

DE: Gnome 44 DE (Wayland)

### Logs

Font/Terminal size: Font size changed to 22

![alacritty_gnome](https://github.com/alacritty/alacritty/assets/25183769/229b9161-ce7e-4511-ab42-a5317f9936a8)

**Comment by kchibisov** [comment]
We haven't changed anything wrt fonts for a long time, what you're seeing is that your font is no longer being found, maybe `monospace` resolves to something non monospace, provide `alacritty -vvv`, it should list what it's trying to lead.

**Comment by chrisduerr** [comment]
Yeah that's clearly a proportional font.
