### ISSUE TITLE
(potentially) Alacritty holds RAM even after applications are closed.

### ISSUE THREAD

**Issue by Torxed** [alacritty/alacritty#7062]
In the pic below `scream` takes 20.9% of the RAM.
After closing it, alacritty holds on to those 20.9% RAM.
It's not with all applications, but it's with all the important ones like Qemu, scream etc.
And if Qemu balloons up, and then releases the ram alacritty holds on to it - eventually causing OOM and the machine becomes unusable.

Have anyone ever witnessed issues like this?

### System

OS: Arch Linux
Version: alacritty 0.12.1 (5fdfd47f)
Linux/BSD: X11, Awesome WM

### Logs

In all honesty, this feels like an OS thing, but I only see this behavior in alacritty at the moment.
![screenshot](https://github.com/alacritty/alacritty/assets/861439/ba8df838-1055-408a-a407-cf10fa7dcb79)

**Comment by kchibisov** [comment]
Test with other GPU clients, maybe the memory is being held in the driver for you for whatever reason, even though, we destroy all resources explicitly on exit.

Anyway, once the process dies it's not our business anymore.

**Comment by Torxed** [comment]
Cheers, will have a look. The only thing that works currently is closing all alacritty windows to release the memory.

**Comment by kchibisov** [comment]
Are those windows under the same process or they have different process?

**Comment by Torxed** [comment]
Apologies if I'm not familiar with the terminology, but I believe they're under the same process (but PID's are different), as shown in the picture.

**Comment by kchibisov** [comment]
In your picture it was process. You create window with `alacritty msg create-window` or `CreateWindow` hotkey. If that wasn't the case, then all was dedicated processes.

**Comment by Torxed** [comment]
Awesome WM calls `alacritty` each time i use the hotkey, so they were probably dedicated processes.
