### ISSUE TITLE
Allow configuration of link highlight modifier key

### ISSUE THREAD

**Issue by Hacksore** [alacritty/alacritty#7065]
This modifier key is hardcoded so we can't change it via a config. I want to be able to use the command button on macOS to enable the link highlight to make them clickable.

https://github.com/alacritty/alacritty/blob/acbf8e581e4b795fe264b52dbc0c7cc395ceb89d/alacritty/src/display/hint.rs#L373

I did a quick test locally where I changed `ModifiersState::SHIFT` -> `ModifiersState::LOGO` and it worked flawlessly.

My proposal is to expose this via a config so the user can control this to their own desires.

```diff
diff --git a/alacritty/src/display/hint.rs b/alacritty/src/display/hint.rs
index 0ff070ec..f03805ed 100644
--- a/alacritty/src/display/hint.rs
+++ b/alacritty/src/display/hint.rs
@@ -370,7 +370,7 @@ pub fn highlighted_at<T>(
         let highlight = hint.mouse.map_or(false, |mouse| {
             mouse.enabled
                 && mouse_mods.contains(mouse.mods.0)
-                && (!mouse_mode || mouse_mods.contains(ModifiersState::SHIFT))
+                && (!mouse_mode || mouse_mods.contains(ModifiersState::LOGO))
         });
         if !highlight {
             return None;
```

**Comment by chrisduerr** [comment]
This is just how to disable mouse mode in general. It's intentionally hardcoded and there's no plan to change that since there really isn't any other sensible option.
