### ISSUE TITLE
Compilation issue: Incorrect relative path to alacritty logo in alacritty/src/display/window.rs

### ISSUE THREAD

**Issue by saurabh-sp-tripathi** [alacritty/alacritty#7069]
Notice the code in alacritty/alacritty/src/display/window.rs line:56

`static WINDOW_ICON: &[u8] = include_bytes!("../../extra/logo/compat/alacritty-term.png");`  notice, path takes 2 steps up.

However actual is location is as following:

``static WINDOW_ICON: &[u8] = include_bytes!("../../../extra/logo/compat/alacritty-term.png");`` notice, path takes 3 steps up.

I have posted the fix in this pull request https://github.com/alacritty/alacritty/pull/7068

Error details:
```
   Compiling smithay-clipboard v0.6.6
   Compiling copypasta v0.8.2
error: couldn't read alacritty/src/display/../../extra/logo/compat/alacritty-term.png: Not a directory (os error 20)
  --> alacritty/src/display/window.rs:56:29
   |
56 | static WINDOW_ICON: &[u8] = include_bytes!("../../extra/logo/compat/alacritty-term.png");
   |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `alacritty` (bin "alacritty") due to previous error
```

**Comment by chrisduerr** [comment]
> However actual is location is as following

It is not. That location is correct. `alacritty/src/display/../../extra/logo/compat/alacritty-term.png` exists and as you can see by CI not failing it works without any problems.

**Comment by Invokerhuu** [comment]
i got the same issues and thanks a lot. it is weired to find that the path is correct but only with the modification it work.

**Comment by kk-hasuwae** [comment]
This just occurred to me on a fresh WSL2 install; might be worth reproducing in this environment? @chrisduerr
