### ISSUE TITLE
CPU usage rises to 100% when 2 instances of Alacritty are opened (WSL)

### ISSUE THREAD

**Issue by Antonio-Bennett** [alacritty/alacritty#7070]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Windows (WSL)
Version: 0.12.2 (9d9982d)
Linux/BSD: Ubuntu 22.04.2 LTS

### Problem

When I open 2 instances of alacritty (1 window running npm run dev the other is just my neovim terminal) the CPU usage sky rockets to 100%. This started after I updated to 0.12.2. After deleting and going back to 0.12.1 it works fine again. Happy to provide any other requested details

**Comment by chrisduerr** [comment]
The system usage or Alacritty's usage? Also for which instance does the CPU usage skyrocket?

**Comment by kchibisov** [comment]
Closing due to lack of response and inability to repro.
