### ISSUE TITLE
crash when switching monitors, invalid method 0 (since 2 < 3)

### ISSUE THREAD

**Issue by mckellygit** [alacritty/alacritty#7071]
Hi,

TY for awesome alacritty all these years.
Latest version has an issue when I come back from switching monitors.

OS: Ubuntu 20.04 5.15 kernel (old gnome/wayland/mutter 3.36)
Version: alacritty 0.13.0-dev (db903503), built from latest git pull with rust 1.70
(I did not set or unset WAYLAND_DISPLAY)

After switching monitors to another and back again my terminal is gone and there is:

Jul 11 09:15:53 machine Alacritty.desktop[3708630]: wl_display@1: error 1: invalid method 0 (since 2 < 3), object wl_output@5
Jul 11 09:15:53 machine Alacritty.desktop[3708630]: Io error: Invalid argument (os error 22)
Jul 11 09:15:53 machine Alacritty.desktop[3708630]: [21.462581044s] [INFO ] [alacritty] Goodbye
Jul 11 09:15:53 machine Alacritty.desktop[3708630]: Deleted log file at "/tmp/Alacritty-3708630.log"
Jul 11 09:15:53 machine Alacritty.desktop[3708630]: Error: "Event loop terminated with code: 1"

Happens every time.
What else can I provide ?  Is my wayland version too old now ?

thx

**Comment by kchibisov** [comment]
Could you provide `WAYLAND_DEBUG=1 alacritty`?

**Comment by mckellygit** [comment]
Thank you so much!
-m

**Comment by kchibisov** [comment]
Fixed on master.
