### ISSUE TITLE
There's not alacritty.toml configuration file example for version 0.13.0

### ISSUE THREAD

**Issue by crokenx** [alacritty/alacritty#7086]
### System

OS: Linux
Version: alacritty 0.13.0-dev (fe2df1b5)
Linux: Pop_os

I was looking to implement some themes but there's not any config file example, and the manual wasn't helpful at all.

**Comment by kchibisov** [comment]
I'm not sure how manual is not helpful, it tells you what toml sections are and defaults/examples on how it should look.

The config file example won't come back.

**Comment by ritog** [comment]
@kchibisov 
 
Where can I find the mentioned manual?

(today is my first day of using alacritty)

**Comment by kchibisov** [comment]
https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd , but be aware that it' scd file. The manual will be rendering on alacritty.org when the release be made.

You can also use 0.12.3 with the alacritty.yml and use config from the release page.

**Comment by ritog** [comment]
Thanks @kchibisov for the pointer.

I set the config and it works fine.

I created [an example with concise guide](https://gist.github.com/ritog/76081f97681e7079d11ec163a5bd4141) in GH Gist for anyone who lands here from a search engine. @crokenx have a look.

**Comment by crokenx** [comment]
That's exactly what I needed at the moment, I came out with one at the moment, it wasn't the most beautiful in the world but it worked for me, now I will look at your example, I really appreciate your contribution @ritog

**Comment by kchibisov** [comment]
I'd still remind that the main issue is that the version is not released. The config has examples already, but we'll probably add more.
