### ISSUE TITLE
When using Emacs with term-title package, Alacritty does not update title bar after Emacs is quit.

### ISSUE THREAD

**Issue by sfsam** [alacritty/alacritty#7088]
### System

OS: macOS
Version: alacritty 0.13.0-dev (e02f0b5f)
Shell: zsh

### Steps to Reproduce

1. Install [term-title](https://github.com/CyberShadow/term-title) package for Emacs.
2. Launch Emacs.
3. Observe Alacritty title bar text is correctly updated for Emacs.
4. Quit Emacs.
5. **_Observe Alacritty title bar has stale text from Emacs, does not revert to "Alacritty"._** 
6. Launch Vim.
7. Observe Alacritty title bar text is correctly updated for Vim.
8. Quit Vim.
9. **_Observe Alacritty title bar has stale text from Emacs, does not revert to "Alacritty"._** 

Other terminal emulators tested (kitty, Terminal.app) do not exhibit this behavior. When Emacs is quit, they both continue to correctly update the title bar text. Alacritty stops updating title bar text after using Emacs with term-title package.

**Comment by kchibisov** [comment]
Do you set the title from your shell?

Some other terminals may inject code to set the title, while alacritty doesn't do so.

Vim for example uses title stack, so it's expected that after exiting it it'll change the title back to what it was before entering it. emacs must do the same.

You could try to collect `-vvv` logs, it should show the title sequences requests alacritty handles iirc.
