### ISSUE TITLE
Alacritty IPC giving error "EndOfStream" when setting colors

### ISSUE THREAD

**Issue by TheTollingBell** [alacritty/alacritty#7089]
### System

OS: Linux 6.4.3-arch1-1 (Arch Linux)
Version: alacritty 0.12.2 (9d9982df)
Linux: Hyprland

### Logs

Crashes: N/A
Width: 800, Height: 600, Font: UbuntuMono Nerd Font Mono
Keyboard and bindings: US altgr-intl keyboard

When trying to use Alacritty's ipc functionality to set any color
`
alacritty msg config -w -1 color.primary.foreground=#ffffff
`
The following error appears
`
[636.876251943s] [ERROR] [alacritty_log_ipc_config] 'color.primary.foreground=#ffffff': Invalid IPC config value: EndOfStream
`

**Comment by kchibisov** [comment]
Try `alacritty msg config -w -1 "color.primary.foreground='#ffffff'"

**Comment by TheTollingBell** [comment]
Now for some reason I get the error
`
[3.170243719s] [ERROR] [alacritty_log_ipc_config] Unable to override option 'color.primary.foreground': Field "color" does not exist
`

**Comment by kchibisov** [comment]
it's `colors`, sorry.

**Comment by TheTollingBell** [comment]
Fixed. Thanks!
