### ISSUE TITLE
alacritty fails to build in Windows on ARM

### ISSUE THREAD

**Issue by ognevnydemon** [alacritty/alacritty#7104]
this error appears when try to build for `aarch64-pc-windows-gnullvm` target
```console
error[E0412]: cannot find type `ULONG_PTR` in this scope
    --> C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winapi-0.2.8\src\basetsd.rs:86:19
     |
  86 | pub type SIZE_T = ULONG_PTR;
     |                   ^^^^^^^^^ not found in this scope
```
that's because there is winapi 0.2, which doesn't support arm64 target. is there any possibility to update winapi package?

**Comment by chrisduerr** [comment]
It seems like  #6846 fixes this, but I'd like to point out that ARM on Windows isn't really a supported platform. Windows itself barely has any support so niche setups like these aren't even testable for any Alacritty developers.

So in this instance, we should hopefully be able to help by accident, but generally if you'd like to see support for Windows ARM then you'll have to contribute it yourself.

**Comment by kchibisov** [comment]
Yeah, we don't test nor ship windows arm builds on the CI, so the support is 'if it happened to compile then good' more or less.

We have `rc` period and package maintainers could likely test if it builds or not during it.
