### ISSUE TITLE
Question: How to conditionally set shell.program based on MacOS architecture?

### ISSUE THREAD

**Issue by pentago** [alacritty/alacritty#7113]
I have a question regarding using different architectures on my Mac.

Specifically, I have noticed that the installation locations for **zsh** and **tmux** differ between ARM and Intel Macs.

They are installed in `/opt/homebrew/bin/` on ARM Macs and in `/usr/local/bin` on Intel Macs. 

I'm wondering if there is a way to properly use the correct binary for each architecture since I am running both.
Any suggestions would be greatly appreciated.

**Comment by kchibisov** [comment]
Different git branches in your config or you generate config based on some template.
