### ISSUE TITLE
[Windows] Scrolling with mouse doesn't scroll the current app but the entire buffer instead

### ISSUE THREAD

**Issue by OscarCapac** [alacritty/alacritty#7115]
I tried to use neovim on windows using alacritty. Unfortunately using the mouse to scroll a file in nvim just results in the entire content of the terminal scrolling, with neovim exiting the view.

The normal behiavor does work on other (stock) terminal emulators in windows.

### System
OS: Windows 10
Version: alacritty 0.12.2 (9d9982d)

**Comment by kchibisov** [comment]
Sounds like a conpty issue, try using `conpty.dll`.

**Comment by kchibisov** [comment]
Though, you'd need a next release to allow loading of it...

**Comment by OscarCapac** [comment]
> Sounds like a conpty issue, try using `conpty.dll`.

Thanks for the response. How would I do that ?

**Comment by kchibisov** [comment]
The `conpty.dll` is basically a windows terminal project, however they don't provide a build for it.

The assets are usually available in various terminal projects, like https://github.com/wez/wezterm/tree/main/assets/windows/conhost

You can also build it yourself.

But as I said you'd need to build alacritty as well.
