### ISSUE TITLE
Annoying font rendering issue on MacOS

### ISSUE THREAD

**Issue by senicko** [alacritty/alacritty#7118]
I have issue with font rendering. I am running alacritty without any config. Just installed it. The font is just so bold. I have tried disabling AppleFontSmoothing for alacritty (https://github.com/alacritty/crossfont/pull/47), but it causes font to look bad too. Like it is thin but looks really raw. I have left some screenshots. Going from left we have VSC then Kitty and finally Alacritty.

On this one we can see weirdly thick font
![image](https://github.com/alacritty/alacritty/assets/25861704/bc3f1372-cdf7-4ce5-9d4e-7215ab26cf5c)

On this we can see that it looks really raw
![image](https://github.com/alacritty/alacritty/assets/25861704/a753f259-2d86-4411-8443-d31ae099b78e)

I don't know ... Is it problem only on my MacOS installation? When I look at videos on youtube nobody seems to have this issue and I DON'T believe people using MacOS can live with this. I just don't. It is impossible to work like that :((((((

### System

OS: macOS
Version: alacritty 0.12.2 (9d9982d)

**Comment by kchibisov** [comment]
Could you compare font to a `Terminal.app` we use apple APIs to draw the font?

It could be an issue with the colors, like we use sRGB on macOS which is a bit brighter (iirc you can enable it in kitty as well).

**Comment by senicko** [comment]
@kchibisov Oh well .. I need a while because I have just upgraded kitty and it looks like I have missed a few important updates regarding font rendering so I am pretty confused right now what is the kitty behaviour. At the moment I have managed to make it look like alacritty with font smoothing enabled.

**Comment by senicko** [comment]
Okay 🥳 .. so right now kitty has an option called `text_composition_strategy` and you can define it as `platform`
```
text_composition_strategy platform
```
It renders fonts exactly the same as alacritty (I mean thicker). I don't know why this is happening and I don't get why this would be the behaviour (both for kitty and alacritty) for macos. 

Kitty allows to "tune the actual contrast curve used for glyph composition". And I was able to achieve look like this with these settings (screenshot below)
```
text_composition_strategy 1.0 0
```
Where the first argument is gamma (0.01 or more) and the second value is additional multiplication contrast (0 - 100) as stated in kitty.conf docs.

What bothers me the most is that `1.0 0` are default settings for linux. *And they look really good*.

So my question would be if it is possible to tune this in Alacritty too as it looks like it is doing something similar under the hood.

In addition to that can anyone explain to me why woulde we change those values for MacOS if it looks bad? I don't say it is not an issue on my side but what could cause it? I am running 2019 MacBook Pro with Intel (well M didn't even exist then) with MacOS Ventura 13.1.

Maybe I shouldn't use "bad" for describing the default look as it is really subjective thing but it is not how the Terminal.app looks (at list on mine machine). I don't think other apps are thickening their font like that. Zed https://zed.dev/ which has it's own rendering engine has normal font thickness too.

I might be totally wrong, so If I am talking nonsense please correct me. I have just spent a lot of time today working out what is going on (both in kitty and alacritty) and I am pretty tired already 😅

![image](https://github.com/alacritty/alacritty/assets/25861704/177e2f07-60c2-46c9-a4dc-28051239aa35)

**Comment by kchibisov** [comment]
@senicko alacritty just using OS system rendering, so it looks exactly like other native applications, we use the same on any other platform, we don't try to manipulate contrast/etc.

**Comment by senicko** [comment]
Ok, sorry for taking your time. I guess I was just really confused by my previous kitty config which I really got used to. Alacritty is amazing and I love it! Keep it going.

**Comment by josepheiba** [comment]
<img width="1728" alt="Screenshot 2024-02-02 at 3 37 35 PM" src="https://github.com/alacritty/alacritty/assets/101673502/021e9cc2-045c-4821-a958-6dda27ca5811">

hello

is it just me, or the fonts are being cut-off on macOS? while font smoothing is enabled as per default on a macOS machine.

if I turn font smoothing off globally, then the font gets fixed, but I don't like to turn font smoothing off.

please can anyone help me fix this issue

**Comment by kchibisov** [comment]
We just pass what we get from the macOS font rasterizer. You can set the font smoothing only for alacritty if you pass the application name, and if you want generally a bolder font, just use bolder style, like `Medium` or `Book`.

**Comment by josepheiba** [comment]
thank you, I'll try that
