### ISSUE TITLE
Query: How was the MacOS border achieved?

### ISSUE THREAD

**Issue by AlexvZyl** [alacritty/alacritty#7120]
I noticed that alacritty does not have the default MacOS border, but other terminal emulators, like kitty, does.  Would anyone mind sharing how this was achieved?  I wish to implement the same for kitty.

I know kitty uses glfw, but I am not aware of an option to manipulate the MacOS border color.

**Context:**
https://github.com/kovidgoyal/kitty/issues/6508

**Comment by AlexvZyl** [comment]
I should add that kitty supports disabling window decorations, which is in the glfw API, but this completely removes the border and window rounding.

**Comment by kchibisov** [comment]
We use standard borders if it matters, we don't draw anything ourselves. See https://github.com/rust-windowing/winit what winit is doing for the `deroration`(s) variant, should be pretty simple to figure out.

**Comment by AlexvZyl** [comment]
Cool, thanks for the direction.
