### ISSUE TITLE
Cannot input punctuation with Chinese IME 

### ISSUE THREAD

**Issue by eatgrass** [alacritty/alacritty#7122]
cannot input Chinese punctuation unless under pre-editing

"." -> "。"
"," -> "，"

https://github.com/alacritty/alacritty/assets/2351076/cdd90387-bfe2-4c4e-b797-851b6c3e7978

### System

OS: macOS
Version: Version 0.12.1 (1)

### Logs
[event.log](https://github.com/alacritty/alacritty/files/12211927/event.log)

**Comment by chrisduerr** [comment]
Can you try the latest master?

**Comment by chrisduerr** [comment]
Actually this seems pretty identical to #6942.

**Comment by eatgrass** [comment]
> Can you try the latest master?

I can reproduce on the master(7b9f3230) also

**Comment by kchibisov** [comment]
Yeah, that issue is not fixed yet, but I sort of now how to fix it, it just requires time to write those heuristics in upstream library we're using, which I don't have...

**Comment by eatgrass** [comment]
@kchibisov Thanks to you, I can totally understand that, no worries

**Comment by ShikiSuen** [comment]
Which IME is this? This doesn't look like the one shipped in macOS.

I am the dev of vChewing IME and I confirmed that vChewing works well:
<img width="594" alt="image" src="https://github.com/alacritty/alacritty/assets/3164826/7c204bff-ff8c-4cba-9502-ad7dce743ef3">
