### ISSUE TITLE
Mouse cursor style changing

### ISSUE THREAD

**Issue by jorian** [alacritty/alacritty#7124]
So I have this weird issue that only happens with alacritty and no other windows, not even other terminals.

Pictures speak louder than words:

![image](https://github.com/alacritty/alacritty/assets/10341677/640d5ff0-fa2c-452b-a039-44d4a942683a)

when moving the mouse to alacritty window:

![image](https://github.com/alacritty/alacritty/assets/10341677/426189e8-25f0-4673-9291-76a90421c48d)

What is even more annoying is that it gets 'sticky', so the resize cursor stays a resize cursor and does not change back to a normal pointing mouse:

![image](https://github.com/alacritty/alacritty/assets/10341677/fda29e7e-ec34-426e-8a72-b114e837643b)

Does anyone have a clue how to fix this?

My alacritty config is empty, I use no themes. ZSH is my shell. Ubuntu 22.04

**Comment by jorian** [comment]
Hmm. Changed from Wayland to Xorg and it seems to have resolved itself.

**Comment by kchibisov** [comment]
Fix your cursor theme settings, alacritty can't find a cursor theme, because on Wayland it draws cursor, not the server.

https://wiki.archlinux.org/title/Cursor_themes#Configuration

Other apps could use gnome dbus settings, which we don't use.
