### ISSUE TITLE
option to persist config runtime config on create-window

### ISSUE THREAD

**Issue by DirectXMan12** [alacritty/alacritty#7128]
Hiya~

I use `alacritty msg config` to switch some stuff around at runtime dynamically, and (unless i'm missing something), `alacritty msg create-window` doesn't seem to persist those runtime config changes to newly spawned windows.

Is this intentional behavior, and if not, would you consider having an option that copied runtime config to a newly created window when spawned via create-window?

**Comment by kchibisov** [comment]
I guess the option could be to inherit the current window settings and only for `CreateNewWindow` binding, but not sure if it's desirable either.

**Comment by DirectXMan12** [comment]
I imagined that if you were running `alacritty msg create-window` from an existing instance, you could pass along the window id as an option (e.g. `--inherit-from` from the CLI, `inherit_from: Option<i128>` in the protocol), since we have `$ALACRITTY_WINDOW_ID` already.

If you weren't executing from an existing terminal (e.g. a window manager binding), I'd imagine 2 implementation options:

1. keep track of the "most recently created" window, and have a special key that uses that (downsides: if the user sets something on an older window, and then calls create-window from their window manager, this might be confusing)

2. have a synthetic window id (included in `all` ideally) that represents a "template config" that can be specified with `--inherit-from` (upside: likely more consistent user behavior, downside: likely? more complicated, but I haven't actually looked)

Option 2 seems smoother to me, and a bit nicer, and gives a reasonable set of experiences:


1. create-window by itself gives vanilla
2. `config font.size=33`, `create-window --inherit-from self` inherits from the current window
3. `create-window --inherit-from ID` inherits from some specific window
4. `config font.size=33 --window-id=-2`[^1], `create-window --inherit-from template` inherits from the "template window"
5. `config font.size=33 --window-id=-1`, `create-window --inherit-from template` also works like (4)

[^1]: where -2 is the template window, could've just said `-1` if we were cool setting it for all existing windows too

**Comment by chrisduerr** [comment]
> I imagined that if you were running alacritty msg create-window from an existing instance, you could pass along the window id as an option (e.g. --inherit-from from the CLI, inherit_from: Option<i128> in the protocol), since we have $ALACRITTY_WINDOW_ID already.

Copying from arbitrary windows is a massive clusterfuck and not an option imo.

> have a synthetic window id (included in all ideally) that represents a "template config" that can be specified with --inherit-from (upside: likely more consistent user behavior, downside: likely? more complicated, but I haven't actually looked)

Also an absolute mess that will definitely not happen.

I can imagine this getting implemented by differentiating between options set for `-1` and specific window IDs and having new windows inherit existing options set for `-1`. I'd assume that should work for you?

**Comment by chrisduerr** [comment]
Feel free to give https://github.com/alacritty/alacritty/pull/7133 a try and see if that works for you.

This implements what I think is a reasonable solution to this issue that should be pretty consistent and predictable.

I don't think I'm willing to entertain any alternatives to this, at least none of the ones suggested in this thread, so I hope this helps.

**Comment by DirectXMan12** [comment]
yeah, that works fine for my current usecase.

Gave it a try, and it does what i need it to do.  Thanks!
