### ISSUE TITLE
MacOS staging manager throttling

### ISSUE THREAD

**Issue by parfeniukink** [alacritty/alacritty#7131]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: MacOS 13.4
Version: alacritty 0.12.0 (5a72819)

Here is the video - https://share.cleanshot.com/4Q2XdMkv

**Comment by kchibisov** [comment]
Why do you think it's an alacritty issue when macOS does the animation?

I'd suggest to report it to apple.

**Comment by parfeniukink** [comment]
> Why do you think it's an alacritty issue when macOS does the animation?
> 
> I'd suggest to report it to apple.

Make sense. Sorry
