### ISSUE TITLE
Config error: did not find expected <document start> at line 125 column 5 

### ISSUE THREAD

**Issue by Xorger** [alacritty/alacritty#7132]
### System

OS: Linux
Version: `alacritty 0.12.2 (9d9982df)` 
Linux/BSD: Wayland,GNOME 44.3

### Logs

Crashes:  STDOUT: `Created log file at "/tmp/Alacritty-67035.log"
[0.000273863s] [ERROR] [alacritty_config_derive] Unable to load config "/home/tux/.config/alacritty/alacritty.yml": Config error: did not find expected <document start> at line 125 column 5
Deleted log file at "/tmp/Alacritty-67035.log"`
STDERR: `warning: queue 0x7f6890000ca0 destroyed while proxies still attached:
  zwp_primary_selection_offer_v1@4278190081 still attached
  wl_data_offer@4278190080 still attached
  zwp_primary_selection_device_v1@27 still attached
  zwp_primary_selection_device_manager_v1@20 still attached
  wl_data_device@26 still attached
  wl_seat@24 still attached
  wl_data_device_manager@23 still attached
  wl_registry@19 still attached
warning: queue 0x560e3c39b6f0 destroyed while proxies still attached:
  wl_buffer@64 still attached
  wl_buffer@22 still attached
  wl_shm_pool@49 still attached
  wl_subsurface@44 still attached
  wl_surface@43 still attached
  wl_subsurface@42 still attached
  wl_surface@41 still attached
  wl_subsurface@40 still attached
  wl_surface@39 still attached
  wl_subsurface@38 still attached
  wl_surface@37 still attached
  wl_subsurface@36 still attached
  wl_surface@35 still attached
  xdg_wm_base@33 still attached
  xdg_activation_v1@14 still attached
  zwp_text_input_manager_v3@13 still attached
  zwp_pointer_constraints_v1@12 still attached
  zwp_relative_pointer_manager_v1@11 still attached
  wl_seat@10 still attached
  wp_fractional_scale_manager_v1@9 still attached
  wp_viewporter@8 still attached
  wl_subcompositor@7 still attached
  wl_output@6 still attached
  wl_shm@5 still attached
  wl_compositor@4 still attached
  wl_registry@2 still attached`

I expected it to apply my configuration, but it threw the above error

**Comment by 446564** [comment]
can you comment how to fix this, or why it is not planned to use a toml config file as described in the docs?

I tried to create a simple config

```toml
[font]
size = 14
```

and get the same error when setting the config file
