### ISSUE TITLE
feature request: change theme when display mode changes

### ISSUE THREAD

**Issue by SyedFasiuddin** [alacritty/alacritty#7135]
I notice that alacritty uses `winit` for cross-platform windowing stuff, it provides an event for when the display mode is changed between light and dark and I notice in the following line that this event is ignored.

https://github.com/alacritty/alacritty/blob/bbe317438192ee695c86b904ff6e1f3843eb94c2/alacritty/src/event.rs#L1382-L1384

I would like to have a theme defined for both a light mode and dark mode and depending on this event change the theme accordingly, and the config file could contain something like this:
```yml
colorscheme:
  mode: "Light"|"Dark"|"System"
  light: ~/lighttheme.yml
  dark: ~/darktheme.yml
```

In [`alacritty/src/config/colors.rs`](https://github.com/alacritty/alacritty/blob/master/alacritty/src/config/color.rs) file, default colors are defined we could define another set of colors for a light variant and introduce a new option in the `Display` struct that takes into account the `colorscheme` option that I just defined above and do the appropriate thing
https://github.com/alacritty/alacritty/blob/bbe317438192ee695c86b904ff6e1f3843eb94c2/alacritty/src/display/mod.rs#L338-L339

Or when a `WindowEvent::ThemeChanged` event occurs we could just swap out the existing value of `colors` from the `Display` struct to another `List`
https://github.com/alacritty/alacritty/blob/bbe317438192ee695c86b904ff6e1f3843eb94c2/alacritty/src/display/mod.rs#L357-L358

I would like to implement this feature myself, but I'm not really sure if what I'm thinking is correct

**Comment by chrisduerr** [comment]
I have no interest in integrating theme changes directly into Alacritty. You can already change your configuration dynamically at runtime, there's no need for Alacritty to handle multiple different themes.
