### ISSUE TITLE
Use the CARGO_TARGET_DIR environment variable to locate the binaries in the makefile

### ISSUE THREAD

**Issue by 0x61nas** [alacritty/alacritty#7137]
I notice that we make an assumption in the `makefile` that the target directory is the `./target` which is true in most cases, but if the user has set the [ `CARGO_TARGET_DIR` ](https://doc.rust-lang.org/cargo/reference/config.html#buildtarget-dir) environment variable to something else. some tasks will fail because of that

**Sugessted solutions**
- we can check on the  `CARGO_TARGET_DIR` environment variable and if set we use it, otherwise we use the default target dir.
   > That'll not work if the user uses the config file to set the target directory instead of the environment variable. in this case, I suppose that we can use the `config get` subcommand (`cargo config get bulid.target-dir`), but this are still unstable https://github.com/rust-lang/cargo/issues/9301

- We can use the `--target-dir` cargo option to override the user's set target directory and use the default one (I don't prefer that personally)

**Comment by kchibisov** [comment]
Makefile is intended to be used only for macOS binary application packaging, it's not used for anything else and really shouldn't be used for anything else than that.

if you want to change the dir, run `make RELEASE_DIR=YOUR_RELEASE_DIR app`

**Comment by 0x61nas** [comment]
> Makefile is intended to be used only for macOS binary application packaging, it's not used for anything else and really shouldn't be used for anything else than that.

I didn't know that sorry for my foolish, but still, I think the issue will exist on macOS too

> if you want to change the dir, run `make RELEASE_DIR=YOUR_RELEASE_DIR app`

seams reasonable

**Comment by kchibisov** [comment]
@0x61nas I mean, if you look at the make file it runs various macos specific commands, maybe we should hide it from top-level dir.

**Comment by 0x61nas** [comment]
I notice that, but I've seen an easy PR opportunity and I didn't take my time to think 😂  sorry
