### ISSUE TITLE
I would like my border window to be black

### ISSUE THREAD

**Issue by NatalieGates** [alacritty/alacritty#7140]
I have tried changing the colors but have been unable to change the window border color to black. Can someone help me?

![bar](https://github.com/alacritty/alacritty/assets/47909481/65c4fdc3-5650-476f-b4d4-a8cd00de24c9)

### System

OS: Linux on WSL (Windows)
Version: alacritty 0.12.2 (9d9982df)
Linux/BSD: I don't know

**Comment by NatalieGates** [comment]
It might be a problem that is unsolvable because I’m using alacritty on windows. But I would like the edge/border to be the same as my background color and completely removed all together.

**Comment by chrisduerr** [comment]
Windows has a global dark theme toggle, does it not? Does that work with Alacritty?

**Comment by NatalieGates** [comment]
That’s my main theme in windows (dark theme). It doesn’t apply to the alacritty window you see in the photo. 😢

**Comment by chrisduerr** [comment]
Which Alacritty version?

**Comment by NatalieGates** [comment]
alacritty 0.12.2 (9d9982df)

**Comment by NatalieGates** [comment]
no support. uninstalled.
