### ISSUE TITLE
Alacritty 0.12.2 cannot be opened on macOS 13.5

### ISSUE THREAD

**Issue by janedenone** [alacritty/alacritty#7141]
The current Alacritty release cannot be opened on macOS 13.5. The following dialog is displayed:

```
“Alacritty.app” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.
```

This cannot be overriden. Is there anything I can do to fix this?

**Comment by chrisduerr** [comment]
https://github.com/alacritty/alacritty/wiki/Self-Signing-Alacritty-on-macOS
