### ISSUE TITLE
Alacritty starts unfocused, incompletely resized in GNOME/Wayland on Debian 12

### ISSUE THREAD

**Issue by proski** [alacritty/alacritty#7142]
### System

OS: Linux, Debian 12 (bookworm), fully up-to-date
Version: alacritty 0.13.0-dev (5b25f3be)`
Linux/BSD: Wayland, GNOME

### Logs
Log with the problem. Screenshot taken at ~10 seconds from startup, window focused at 22s, window closed at 30s.
[alacritty-wayland.log](https://github.com/alacritty/alacritty/files/12328034/alacritty-wayland.log)
Log under X11 for comparison, correct PTY size reported on startup.
[alacritty-x11.log](https://github.com/alacritty/alacritty/files/12328035/alacritty-x11.log)

Screenshot showing the unfocused window. The frame is resized but the contents is not.
![alacritty-screenshot](https://github.com/alacritty/alacritty/assets/1317472/ad57a6fe-5212-46b6-87d7-4046c3c209b5)

Configuration file:
[alacritty.toml.txt](https://github.com/alacritty/alacritty/files/12328046/alacritty.toml.txt)

Alacritty.desktop file.
[Alacritty.desktop.txt](https://github.com/alacritty/alacritty/files/12328047/Alacritty.desktop.txt)

To reproduce the issue, make sure another window is open. Click on it with the mouse. Press the Windows key. Click on the Alacritty icon with the mouse. Alacritty starts without focus. If it's configured for a non-default window size, the frame is resized but the contents is not.

I tried both the master branch and the branch from #7079. I tried commenting out `StartupWMClass=Alacritty` and adding `StartupNotify=true` is all combinations, it has no effect.

The issue can only be reproduced in Wayland, not in X11.

There is some similarity of this issue to #6931 but I'm not sure if it's the same issue.

**Comment by kchibisov** [comment]
>I tried both the master branch and the branch from https://github.com/alacritty/alacritty/pull/7079. I tried commenting out StartupWMClass=Alacritty and adding StartupNotify=true is all combinations, it has no effect.

On Wayland, we have no control over focus. We xdg-activate our window with the token passed by launcher, and that's all we can, the rest is up to gnome.
