### ISSUE TITLE
Feature request: Show runtime configuration

### ISSUE THREAD

**Issue by BuriedInTheGround** [alacritty/alacritty#7147]
It would be great if it were possible to view Alacritty's runtime configuration via IPC. If viewing the entire configuration is impractical, it would be nice to at least be able to query the value of a specific option.

For the latter case, a possible implementation could take advantage of the `config` subcommand of `alacritty msg` by returning the value of the option if no value is given, as in the following example.

```
$ alacritty msg config -w 16777218 cursor.style=Beam
$ alacritty msg config -w 16777218 cursor.style
Beam
```

**Comment by chrisduerr** [comment]
Why would you want this?

**Comment by BuriedInTheGround** [comment]
Currently, if I'm not mistaken, Alacritty's runtime configuration is determined by (1) the defaults, (2) what's in `alacritty.toml`, and (3) options modified via IPC with the `alacritty msg config` command.

There could be (at least) two situations:
1. No option has been changed via IPC. In this case, it is possible to "manually recover" the complete configuration by merging the information about default values (from Alacritty's manpage) and the values specified in the `alacritty.toml` configuration file. Personally, I find this operation quite tedious when configuring Alacritty from scratch, as I often find myself opening the manual, searching for the intended option, and finally finding its default value so that I can better understand how or why something looks the way it does given the default value I found and what's in my `alacritty.toml`.
2. One or more options have been changed via IPC. I may have made the changes myself, and I may not remember exactly what they were, but I like the way Alacritty looks now, and I'd like to be able to grab the current runtime configuration to make it permanent in `alacritty.toml`. Otherwise, the changes via IPC could be made by some script (mine or not), and I'd still like to grab the current runtime configuration to make it permanent in `alacritty.toml` because I like it, but I have no (current) way of getting it.

Being able to write more accurate scripts could be another use case. Let's say I want to bind a key combination to a script that changes some options (e.g. font size and scrolling multiplier) of the configuration of the currently running Alacritty instance via IPC, so that I can more easily accomplish a certain task (e.g. reading a long and wide log). When I'm done with this task, I'd like to be able to restore the previous configuration without restarting Alacritty, possibly using the same keybinding so that the script restores the previous options. Currently, the script has no way of knowing Alacritty's runtime configuration, so it can't save the exact configuration, and it definitely can't restore it. If changes have been made via IPC, it may only be able to restore a partially correct configuration by looking at `alacritty.toml`.

I hope I wrote everything clearly enough. Either way, I'm open for discussion! Thanks for your work.

**Comment by chrisduerr** [comment]
Sounds like one big motivation behind this is writing out a configuration file with all available options. This is something I'd heavily discourage anyway because it removes the ability of Alacritty to change the defaults of configuration options and will lead to configuration files with a ton of old keys.

IPC configuration can be reset to the configuration file at any point, so I don't see much of an issue here.

This would change the IPC infrastructure from being one-way communication to being two-way, so it significantly increases the architectural complexity. As such, I don't think any arguments made here justify this change.

**Comment by BuriedInTheGround** [comment]
I definitely **don't** want to write a configuration file with all available options, that would be useless and too hard to maintain!

What I want is a quick and reliable way to handle situations like the following: I update Alacritty and some time passes, maybe even a month, then I notice that something is wrong, like an accent color that is rarely used or some other configuration option, so in the middle of my work I have to go and look at both my own `alacritty.toml` configuration *and* Alacritty's manpage *and* maybe even Alacritty's changelog and mentally put all this information together to figure out where something went wrong. It's kind of a painful experience for me.

I don't necessarily want it to be an IPC operation if it's too cumbersome. Just being able to query the value of an option and get back the result of merging the deafults and the `alacritty.toml` user config would be really nice!

Otherwise, it would be great if you could suggest another viable method to accomplish this. That is, something like "just look at the manual" is not the solution for me. (Just to be clear, I love manpages, it's just that I think this kind of problem requires a more dynamic solution).

**Comment by jarkkojs** [comment]
This is definitely 

> I definitely **don't** want to write a configuration file with all available options, that would be useless and too hard to maintain!
> 
> What I want is a quick and reliable way to handle situations like the following: I update Alacritty and some time passes, maybe even a month, then I notice that something is wrong, like an accent color that is rarely used or some other configuration option, so in the middle of my work I have to go and look at both my own `alacritty.toml` configuration _and_ Alacritty's manpage _and_ maybe even Alacritty's changelog and mentally put all this information together to figure out where something went wrong. It's kind of a painful experience for me.
> 
> I don't necessarily want it to be an IPC operation if it's too cumbersome. Just being able to query the value of an option and get back the result of merging the deafults and the `alacritty.toml` user config would be really nice!
> 
> Otherwise, it would be great if you could suggest another viable method to accomplish this. That is, something like "just look at the manual" is not the solution for me. (Just to be clear, I love manpages, it's just that I think this kind of problem requires a more dynamic solution).

It would be actually just as easy (or hard) to maintain as would querying a single configuration option :-)

I hate when cannot A/B reference changes to known values so thus changed terminal despite like some other aspects of Alacritty. This is just a such a major flaw in this application.

**Comment by kchibisov** [comment]
I don't quite understand, all the changes to the config are always listed with all the releases, there was no release where the changes to defaults were not listed...

**Comment by ethanuppal** [comment]
> Otherwise, it would be great if you could suggest another viable method to accomplish this.

Did you ever find one? It is very frustrating that this is not currently possible.

**Comment by kchibisov** [comment]
`alacritty msg get-config  | jq`

**Comment by ethanuppal** [comment]
> `alacritty msg get-config | jq`

I guess I missed that somehow...thank you!

**Comment by ethanuppal** [comment]
Unfortunately this is not sufficient...it does not list any keybinds. To reproduce:
1. `alacritty --daemon`
2. `alacritty msg get-config | jq .keyboard`

**Comment by kchibisov** [comment]
There're some other fields that are not there, I've opened an issue here https://github.com/alacritty/alacritty/issues/8889,
