### ISSUE TITLE
Allow unsetting enviroment variables

### ISSUE THREAD

**Issue by soupglasses** [alacritty/alacritty#7148]
### Proposal

Using for example `alacritty -o env.ENVIROMENT_VARIABLE` to unset a variable does not work, and requires you to set a string like value.

This is due to the internal use of `std::env::set_var`.

https://github.com/alacritty/alacritty/blob/6143b3f4eb352ff4ab36149ce5ba8c6ab04e415a/alacritty_terminal/src/tty/mod.rs#L77-L81

I propose adding a way to set this to null in the CLI and config, which then lets you trigger `std::env::remove_var` to allow also removing environment variables.

### Motivation

Due to some scripting requirements with libGL that I am working on, I need to unset a set of environment variables before the shell that spawns inside of Alacritty. This also requires Alacritty does an initial read from these to initialize itself.

**Comment by chrisduerr** [comment]
That sounds very much like a workflow issue. I don't see a reason why we'd have to unset environment variables.
