### ISSUE TITLE
Feature: Add `presentation_size` to font config and allow `SetPresentationFontSize` to be bound to a key

### ISSUE THREAD

**Issue by TheFunctionalGuy** [alacritty/alacritty#7151]
Hey,

I've got a proposal for a feature that might be useful.
I would like to call it by the name of **Presentation Font Size**.

At work when I show my terminal to my coworkers, I usually increase the font size to something which is readable from afar.
This involves multiple key presses of _Ctrl-Plus_ on my way to the preferred font size and one key press of _Ctrl-0_ to get back again.

For this reason I implemented an additional config option for font like that:
```
font:
  size: 11
  presentation_size: 16
```
or if you like the new toml format:
```
[font]
size = 11
presentation_size = 16
```

This can be bound to every key by binding the `SetPresentationFontSize` to a key and allows easy switching back and forth without remembering how many times you need to press _Ctrl+Plus_ to get to your destination.
The default of `presentation_size` is `22` (which might be way to high to be a reasonable default).

Here is a reference to the commit implementing aforementioned feature: TheFunctionalGuy/alacritty@e5580cd674d170ecb3dd10d0183d81eab5e5f452.
**Note:** This is just a prototype for this feature. 

I'm open for discussion or even if you don't need/want this feature because it's too niche.
Just wanted to share this because I think it might benefit other people.

Cheers.

**Comment by kchibisov** [comment]
`alacritty msg config font.size=16` and to reset `alacritty msg config -r`
