### ISSUE TITLE
No configuration manpage on Mac

### ISSUE THREAD

**Issue by Dolfost** [alacritty/alacritty#7152]
Hello. I installed the Alacritty on ARM Mac with `brew install alacritty` I would like to configure it but `man 5 alacritty` says that
`No manual entry for alacritty`. `man alacritty` opens the short manual page
```
NAME
       Alacritty - A fast, cross-platform, OpenGL terminal emulator

SYNOPSIS
       alacritty [SUBCOMMANDS] [FLAGS] [OPTIONS]

DESCRIPTION
       Alacritty is a modern terminal emulator that comes with sensible defaults, but allows for extensive configuration. By integrating with other applications, rather than reimplementing their functionality, it manages to provide a
       flexible set of features with high performance.

FLAGS
       -h, --help
              Prints help information

       --hold Remain open after child process exits

       --print-events
              Print all events to stdout

       -q     Reduces the level of verbosity (the min level is -qq)

       --ref-test
              Generates ref test

       -v     Increases the level of verbosity (the max level is -vvv)

       -V, --version
              Prints version information

. . .
``` 
 How to make the `man 5 alacritty` open the proper man page for Alacritty configuration guidelines?

### System

OS: macOS
Version: alacritty 0.12.2 (9d9982d)

**Comment by kchibisov** [comment]
https://github.com/alacritty/alacritty#configuration

>Version: alacritty 0.12.2 (https://github.com/alacritty/alacritty/commit/9d9982df0ed3ab40a9b432e8e8b75d9c7f7bd882)

**Comment by Dolfost** [comment]
> https://github.com/alacritty/alacritty#configuration
> 
> > Version: alacritty 0.12.2 ([9d9982d](https://github.com/alacritty/alacritty/commit/9d9982df0ed3ab40a9b432e8e8b75d9c7f7bd882))

It does not resolve the issue.

**Comment by kchibisov** [comment]
Have you read actually, it says that your config docs are in yml file, no `man 5` is present for any of the released versions.

**Comment by Dolfost** [comment]
> Have you read actually, it says that your config docs are in yml file, no `man 5` is present for any of the released versions.

Now I get it. Thanks for the explanation.
