### ISSUE TITLE
Incorrect display of umlauts on macOS

### ISSUE THREAD

**Issue by 0xDP** [alacritty/alacritty#7154]
On macos sometimes umlauts (äöüÄÖÜ) are displayed incorrectly. The dots appear then above the following character.

### System

```
% sw_vers
ProductName:		macOS
ProductVersion:		13.5.1
BuildVersion:		22G90
% alacritty --version
alacritty 0.12.2 (9d9982d)
```
The font is default (Menlo) with 12 pt.

### Steps to reproduce:

In Alacritty, create a directory with an umlaut as a subdirectory
```
% mkdir -p test/täst.a
```
In Finder go to the directory 'test' and create a second subdirectory with an umlaut 'rightklick -> New Folder', name it 'täst.b'. Go back to Alacritty and list the contents of the directory 'test'
```
% ls test
täst.a   täst.b
```
Both looks here the same after copy & paste because the umlaut is not damaged, but in Alacritty täst.a has the dots above the 'a', where täst.b has the dots above the 's'.

macOS and shell uses different codepoints for the umlauts (resp. compose them differently), which can be seen e.g. with xdd:
```
% ls test | xxd
00000000: 74c3 a473 742e 610a 7461 cc88 7374 2e62  t..st.a.ta..st.b
00000010: 0a                                       .
```
I have used directories here to show the issue, but with filenames it is the same.

Regards,
Dennis

**Comment by chrisduerr** [comment]
Issue with your font.

**Comment by 0xDP** [comment]
It is the default font of Alacritty on macOS. Which font do you recommend?

**Comment by chrisduerr** [comment]
I'm pretty sure it works with Fira Mono, but fonts are extremely subjective.

**Comment by 0xDP** [comment]
With Fira Mono this actually works. (But the '@' here is very ugly in my opinion). Monaco also works, but has only one style (no Bold).

I also tried PT Mono and SF Mono (the default font of Terminal.app and XCode). Here the dots are also shifted in Alacritty. In Terminal.app and iTerm2, interestingly, this phenomenon does not exist with Menlo, PT Mono and SF Mono.

**Comment by Aninsi-Sasberg** [comment]
Just wanted to say that i have the same problem with 'Fira Code'. Probably am just going to switch fonts for now.
