### ISSUE TITLE
Remnant lines when resizing window in WSL

### ISSUE THREAD

**Issue by zaid-g** [alacritty/alacritty#7157]
Maximizing the alacritty window (launched by running `alacritty` from WSL) keeps remnant lines of the window's previous size, messing up the view. Cannot manually resize window either.

### System

OS: Windows 10 (Ubuntu WSL)
Version: alacritty 0.13.0-dev

### Screenshot

![alacritty-b4](https://github.com/alacritty/alacritty/assets/33379149/04028b42-1867-4f8a-aa5f-8d19d8566c72)
![alacritty-after](https://github.com/alacritty/alacritty/assets/33379149/19674121-4055-45da-8a78-b75d8aff7505)

**Comment by chrisduerr** [comment]
Are these lines cleared when you select them?

**Comment by zaid-g** [comment]
No, if by select you mean click and drag with the cursor.

**Comment by chrisduerr** [comment]
How about resizing the window? Also which GPU is this and is this a regression or has it always been an issue?

**Comment by chrisduerr** [comment]
Is this in a VM?

**Comment by zaid-g** [comment]
No, Ubuntu WSL on Windows 10.

**Comment by chrisduerr** [comment]
You mention WSL, but I'd assume this can be reproduced without it too?

**Comment by zaid-g** [comment]
No, only when run via WSL. I tried to reproduce using the prebuilt Windows
binary and no problems there.

**Comment by chrisduerr** [comment]
Wait, are you actually launching Alacritty as a graphical application through WSL?

Or are you just using `wsl` as a shell?

**Comment by zaid-g** [comment]
Graphical application launched through WSL. How else can I use it based on
my Linux environment (in wsl)?

**Comment by chrisduerr** [comment]
You can just use WSL as a shell.

This is just a bug with graphical applications in WSL then.
