### ISSUE TITLE
Alacritty doesn't use the icon present in icon themes

### ISSUE THREAD

**Issue by randomcoder67** [alacritty/alacritty#7158]
Alacritty doesn't use the system wide icon theme. I am using Papiurs, which has an alacritty icon, but alacritty uses the same default icon no matter which icon theme I select. 

### System

OS: Linux (Arch)
Version: alacritty 0.12.2 (9d9982df)
Linux/BSD: X11, Xfce with Xfwm

**Comment by chrisduerr** [comment]
Where is it using the wrong icon? Applications have very little to do with icons on Linux.

**Comment by kchibisov** [comment]
@chrisduerr don't we set the icon with winit method? We do pass our default icon to it and it's what is being present in the window. I know that some DEs don't use that information and rely on icon theme and `/usr/share/pixmap` to set an icon.

**Comment by chrisduerr** [comment]
The icon in the window decorations might be different, yeah. But that's expected.

**Comment by kchibisov** [comment]
We could in theory resolve the theme and then fallback to embeded resource, but not really sure about that. Usually icon is being drawn by the DE and the one embeded is not really used. I don't remember the exact case where this icon is present, only in title bar in some DEs?

**Comment by chrisduerr** [comment]
> We could in theory resolve the theme and then fallback to embeded resource, but not really sure about that.

Yeah that's ridiculous and definitely not how things are supposed to work.

> I don't remember the exact case where this icon is present, only in title bar in some DEs?

Yeah I believe the icon we have embedded is only used in the titlebar by some DEs. Which is pretty much unrelated to the icon theme.

**Comment by randomcoder67** [comment]
> Where is it using the wrong icon? Applications have very little to do with icons on Linux.

On Xfce, the icon remains the same on the taskbar, in the task switcher (alt tab display) and in the applications menu. 

Some applications have this behaviour (on my system mpv and GIMP), but others will change their icons when you change the icon theme (on my system Xfce-Terminal, Firefox, Mousepad and Leafpad work like this, updating the icon theme in settings will change the taskbar icons etc).

**Comment by chrisduerr** [comment]
I don't see anything Alacritty would have to do here.

**Comment by randomcoder67** [comment]
> I don't see anything Alacritty would have to do here.

Is there a way to change the icon without changing it before compiling? (i.e. can you change icon if you installed as a binary?)

**Comment by dagolinuxoid** [comment]
`Usually icon is picked from the theme by the DE, if you DE relies on embeded icons you're out of luck here. `
This is kinda sad. Default Alacritty icon actually looks good but there are others that look awful. @randomcoder67 I assume u didn't solved the issue, so there are no third-party linux software that would forced desired behavior or  some other measures to do so?
