### ISSUE TITLE
Display Error When Using TAB Autocompletion 

### ISSUE THREAD

**Issue by lglglglgy** [alacritty/alacritty#7159]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux
Version: alacritty 0.13.0-dev (33306142)
Linux/BSD: wayland

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `Width: 900, Height: 475`
Keyboard and bindings: `to much`
### problem
I encountered a display issue after using TAB for autocompletion. For example, when I type "sudo bpytop" and press TAB, the displayed content changes to "susudo bpytop." However, pressing Enter executes the command correctly, indicating that it's just a display error. I'd like to know how to resolve this.
![image](https://github.com/alacritty/alacritty/assets/129643128/062fa8b2-a3bf-479e-9aef-55fb64e00c1c)
Furthermore, I attempted to delete this command, but the initial two letters cannot be removed. However, this issue does not affect the execution of the subsequent command.
![image](https://github.com/alacritty/alacritty/assets/129643128/c31bcdd9-14ca-4f19-a419-b3549b17f2d9)

Furthermore, when I attempt to modify the previous command, my changes often differ from the executed command. It seems that the position of the displayed cursor is incorrect.

**Comment by chrisduerr** [comment]
What shell are you using, fish? This is a shell or TERM issue iirc.
