### ISSUE TITLE
All text suddenly disappears if running on Wayland

### ISSUE THREAD

**Issue by ngrigoriev** [alacritty/alacritty#7162]
I have recently moved to Wayland from X11 on the same laptop. I've been using Alacritty for a while and I did not observe this issue. I did not change anything in Alacritty configuration yet.

Under Wayland/Sway, usually within just hours from the start, I noticed that after switching back to the workspace where I run Alacritty, I no longer see any text in the terminal. Attempting to Ctrl-L, switching workspaces again, moving to/from fullscreen does not change anything. It seems something happens and that breaks Alacritty process. I can launch another window and it works fine.

The window retains the original background color and if I use the mouse, I see the rectangles of various colors where the text used to be. And several thin horizontal lines.

### System

OS: ArchLinux, latest
Version: alacritty 0.12.2 (9d9982df)
Linux/BSD: Wayland, Sway, Nvidia proprietary driver

### Logs

It seems this log ([alacritty-crash.txt](https://github.com/alacritty/alacritty/files/12422364/alacritty-crash.txt)) correlates to the issue (journal log).

**Comment by kchibisov** [comment]
crash is within nvidia, so ask them.

**Comment by ngrigoriev** [comment]
I actually can confirm now that this stack trace is NOT related to the bug. It just happened again, and no stack trace has been logged.

This seems to be more relevant:

```
Aug 23 18:03:50 myhostname kernel: NVRM: Xid (PCI:0000:01:00): 13, pid=73866, name=alacritty, Graphics Exception: ChID 0018, Class 0000c597, Offset 00000000, Data 00000000
Aug 23 18:03:50 myhostname kernel: NVRM: Xid (PCI:0000:01:00): 13, pid='<unknown>', name=<unknown>, Graphics Exception: ESR 0x405848=0x80000000
Aug 23 18:03:50 myhostname kernel: NVRM: Xid (PCI:0000:01:00): 13, pid='<unknown>', name=<unknown>, Graphics Exception: ESR 0x405840=0xa2040800
Aug 23 18:03:50 myhostname kernel: NVRM: Xid (PCI:0000:01:00): 13, pid='<unknown>', name=<unknown>, Graphics Exception: Shader Program Header 18 Error
Aug 23 18:03:50 myhostname kernel: NVRM: Xid (PCI:0000:01:00): 13, pid='<unknown>', name=<unknown>, Graphics Exception: Shader Program Header 11 Error
```

No other apps seem to have the same issue.

**Comment by kchibisov** [comment]
I mean, sounds like your GPU just fails given that it's coming from the kernel. I'd suggest to ask nvidia about it.

**Comment by ngrigoriev** [comment]
Given that it never happened under X11 on the same machine and still does not happen if I use X11, I seriously doubt that. I know that Nvidia drivers are still quite unstable when it comes to Wayland. I still find it interesting that the app (Alacritty) suffers from it, falls into that state, but another instance running next to it starts and works just fine at the same time. So, my main point here is about Alacritty handling such a condition correctly or not. Is the app doing everything possible to handle an error and reset its state?

For example, it just happened again a moment ago. And then I started looking if Alacritty has a key binding that could do something about the text. I tried Ctrl+/Ctrl- to increase/decrease the font size and the app has recovered from this condition, everything is displayed properly. So, I would not necessarily dismiss this issue - the bug may be indeed in the kernel module, but it is clear that the app has a way to handle it and recover.

**Comment by kchibisov** [comment]
@ngrigoriev the issue is that textures on the GPU are gone, that's the reason the text is broken, the in the driver gots borked, so nothing we can really do about it. We tried in the past to handle robustness, but it did nothing as well on nvidia and only worked with mesa. Like even recreating all the textures wasn't enough to fix anything on nvidia.

I still don't understand why do you think that it's our issue, when it even works on X11 on the same setup. The code is exactly the same, it's just OpenGL calls nothing 'wayland special' at all.
