### ISSUE TITLE
Question about hints.alphabet

### ISSUE THREAD

**Issue by flrgh** [alacritty/alacritty#7163]
Hiya :wave:

What does this option _do_? 

```yaml
# Regex hints
#
# Terminal hints can be used to find text in the visible part of the terminal
# and pipe it to other applications.
hints:
  # Keys used for the hint labels.
  #alphabet: "jfkdls;ahgurieowpq"
```

I can't seem to find any more information on it other than what's in the default `alacritty.yml`. I've tried changing it to other things but didn't notice any visual/behavioral difference (at least for how _I_ am using hints).

Is the default `jfkdls;ahgurieowpq` a magic value, or is it intended to be "random"? I can see that it follows a particular pattern on a qwerty kb, but that could have just been the feature dev's method of typing in a dummy value. Is there any reason I would ever need to change it from the default value?

**Comment by kchibisov** [comment]
It affects the `hints` bindings, like default `ctrl + shift + u` and what you see on the labels. You won't notice it unless you use hints.
