### ISSUE TITLE
Feature: Separate padding

### ISSUE THREAD

**Issue by jascodes** [alacritty/alacritty#7171]
Currently padding is like following

```
  padding:
  	x: 20
    y: 40
```

I purpose updating it to 

```
padding:
	left: 20
	top: 40
	right: 10
	bottom: 0

```

**Comment by jascodes** [comment]
@chrisduerr thanks for time you spent on the project. Absolute but emulator. 

Kindly add the original issue because I did search before filing. 

Thanks

**Comment by cs** [comment]
#4297
