### ISSUE TITLE
window.decorations buttonless causing issues on linux

### ISSUE THREAD

**Issue by Buttars** [alacritty/alacritty#7172]
I share a config between my macos and my linux environments.
In my alacritty config I have window.decorations set to buttonless.
This causes the error `Config error: decoratoins: unknown variant 'buttonless', expected one of 'Full', 'None'`

I'd like to either be able to define a fallback or have it automatically fall back and not throw an error.

### System

OS: Linux
Version: 0.12.0
Linux Wayland, Hyprland

**Comment by chrisduerr** [comment]
Use different configs.
