### ISSUE TITLE
Config warning: use_thin_strokes has been removed;

### ISSUE THREAD

**Issue by iamskishore** [alacritty/alacritty#7174]
Config warning: use_thin_strokes has been removed; set the AppleFontSmoothing user default instead
[0.002644249s] [WARN ] [alacritty_config_derive] Config warning: alt_send_esc has been removed; It's now always set to 'true'. If you're on macOS use 'window.option_as_alt' to alter behavior of Option

bottom of the  alacritty

![image](https://github.com/alacritty/alacritty/assets/87164396/9f8d6044-ae3d-49ee-9d23-4e5879999532)

**Comment by chrisduerr** [comment]
Remove the option.

**Comment by iamskishore** [comment]
i don't get it

**Comment by kchibisov** [comment]
It says that the option got removed and it doesn't work anymore. You should just remove the option `use_thin_strokes` from the config.
