### ISSUE TITLE
[BUG] Border theme

### ISSUE THREAD

**Issue by kulothunganug** [alacritty/alacritty#7186]
### System

OS: Fedora 38 (Linux)
Version: 0.12.2
Linux/BSD: wayland, gnome 44.4

### Description

When I first (after turning on the pc) start alacritty, it has white theme
![image](https://github.com/alacritty/alacritty/assets/63696279/4ebb6ec0-1b1a-42ba-947a-557ee90c1b12)

If I close it open new one (all subsequent), it has dark theme.
![image](https://github.com/alacritty/alacritty/assets/63696279/1ccfe2ca-b0a1-4a94-8333-e273f28317e9)

**Comment by kchibisov** [comment]
That's expected because your system service is not advertising which theme should be used. You can set theme in the config to avoid auto picking.
