### ISSUE TITLE
Wrong line wrapping on invalid characters in filenames

### ISSUE THREAD

**Issue by m1027** [alacritty/alacritty#7187]
Tested with alacritty-0.12.1 on linux, inside tmux, wayland.

(No issue on a pure linux console!)

The problem:
- Have a file with invalid (non-utf8) characters in the filename.
- Type a random command on the console and assert the command wraps at the line end. As the invalid filename cannot be typed in, use tab completion to reproduce. E.g. you can simply try `ls my-file<tab> my-file<tab> my-file<tab>` until the line wraps.
- Without pressing `return` try to move the cursor backwards and cross the line wrap

Expected behaviour:
- The cursor should move back and then one line up so you can edit the console input.

Various unexpected behaviour:
- Sometimes the console gets entirely garbled
- Sometimes the cursor is positioned at a character but when hitting DEL a character is removed that isn't under the cursor

I home I can recreate and provide such a file with an invalid encoding.

**Comment by kchibisov** [comment]
>inside tmux, wayland

Test outside, otherwise it's invalid, we don't even wrap the lines when tmux is used.

**Comment by chrisduerr** [comment]
Also testing this stuff on the prompt very much sounds like this is a shell issue. You should be able to reproduce with just `echo`.

**Comment by m1027** [comment]
Thanks for your hints.

I've made some tests and this issue might be two issues...:

To create such a file:
- touch my-testfile-with-X-character
- assert that you enter any non-ascii character for "X" like "é"
- use conmv to convert to an encoding that your filesystem/shell does not support; assuming that the standard is utf8, this could be: convmv -f utf8 -t iso-8859-1 <filename> [--notest]

Test in alacritty without tmux and bash:
- mv my-testf[press tab] my-testf[press tab]
- cursor backward towards invalid X character
- tried to DEL it
- result: this character is actually doubled and such strange effects

Same test on pure linux console (same bash, no desktop, no tmux, no alacritty):
- Worked as expected (edit character, rename file)

Same test on pure linux console but inside tmux:
- Again strange effects

It seems that tmux + alacritty both have their own issues?

**Comment by m1027** [comment]
Thanks for reading -- but I don't understand in what way this is completed?

Note that neither bash nor tmux seems to trigger this issue...?

**Comment by chrisduerr** [comment]
No repro with echo, no Alacritty issue.

**Comment by m1027** [comment]
Thanks but I still don't get it:

(1) Bash on linux terminal: No issue. Bash in Alacritty: Issue...

(2) IMHO `echo`ing invalid characters is not the point. This kind of works. The issue is trigered when you try to move the cursor and edit that line.

So who is responsible then?

**Comment by chrisduerr** [comment]
> The issue is trigered when you try to move the cursor and edit that line.

Which is done by the shell, not the terminal.
