### ISSUE TITLE
Slow startup due to read to PCI device config

### ISSUE THREAD

**Issue by nightbluepn** [alacritty/alacritty#7189]
### System

OS: Arch Linux (6.4.12-arch1-1)
Version: `alacritty --version` output
Linux/BSD: Wayland, Sway

### Logs

Problem: Alacritty startup time is very slow.
According to strace this is due to a read to the config of the PCI Bridge:
```
openat(AT_FDCWD, "/sys/bus/pci/devices/0000:03:00.0/config", O_RDONLY) = 16
read(16, "\206\200\300\25\7\4\20\0\1\0\4\6 \0\1\0\0\0\0\0\0\0\0\0\3\4\4\0\361\1\0\0"..., 48) = 48
```
The corresponding PCI device:
`03:00.0 PCI bridge: Intel Corporation JHL6240 Thunderbolt 3 Bridge (Low Power) [Alpine Ridge LP 2016] (rev 01)`

I'm quite sure the slow read has nothing to do with Alacritty itself, since other people seemed to have the same problem in other contexts, but maybe it's possible to work around this read (Alacritty is the only desktop program with this issue, calling `lspci` shows the same behaviour).

Using `env -u WAYLAND_DISPLAY alacritty` leads to Alacritty not reading the file. Is there a way to avoid the read in native Wayland mode? Thanks.

**Comment by kchibisov** [comment]
We use video drivers, so they likely read the pci stuff, nothing we can do about.
