### ISSUE TITLE
tmux and fish shell not working with TOML

### ISSUE THREAD

**Issue by ehrktia** [alacritty/alacritty#7190]
installed alacritty using make build app from README for osx
copied alacritty binary from target/releases/osx to Applications 
moved from yml to toml config as latest version was giving warning for toml
start alacritty from Applications directory from dock in osx
part of config which is causing error
`[cursor]
shell = { program = "/opt/homebrew/bin/fish", args = ["-l","-c","tmux a -t base || tmux new -s base"] }
`

*expected*
alacritty to start with default tmux session in fish shell

*actual*
alacritty starts with fish shell, as the default shell in osx is fish but no tmux.
manually when started new session using `tmux` it starts new tmux session.

```bash
echo $SHELL
/opt/homebrew/bin/fish
```

tmux install path

```bash
which tmux
/opt/homebrew/bin/tmux
```

### System

OS: macOS Ventura 13.5.1

**Comment by chrisduerr** [comment]
Did you use `alacritty migrate` to switch between yaml and toml config? If there's a bug with this I'd like to know.

But to me that looks like you might have just configured things wrong. Try `cursor.shell` instead of `[cursor] shell`.

**Comment by ehrktia** [comment]
@chrisduerr thanks for swift response 
```cursor.shell = { program = "/opt/homebrew/bin/fish", args = ["-l","-c","tmux a -t base || tmux new -s base"] }
```
still the same

**Comment by kchibisov** [comment]
it's not in the cursor, it's just `shell`. `alacritty migrate` is a subcommand of `alacritty` binary. You can see what it can with `alacritty help`.

**Comment by ehrktia** [comment]
@kchibisov thanks , i have installed from source code using `make universal-app` command and copied to Applications folder in osx when i try to run `which alacritty` from terminal app is not found .
Do i need to add the binary to `$PATH`

**Comment by kchibisov** [comment]
yeah, binary is inside the `.app`, you can just execute with the full path. You can also just execute the binary from `target/release/alacritty` given that you've built from source.

**Comment by ehrktia** [comment]
@kchibisov thanks did run the terminal using binary and generated the toml from yml via `alacritty migrate` the output for the shell part is as below
```
[shell]
args = ["--login", "-c", "tmux a -t base  || tmux new -s base"]
log_level = "Warn"
persistent_logging = false
print_events = false
program = "/opt/homebrew/bin/fish"
```
when i use the above in my alacritty.toml is giving same error

**Comment by chrisduerr** [comment]
```
[shell]
program = "/opt/homebrew/bin/fish"
args = ["--login", "-c", "tmux a -t base || tmux new -s base"]
```

**Comment by Darren-Serious** [comment]
@chrisduerr it not work

**Comment by jasonshanks** [comment]
> ```
> [shell]
> program = "/opt/homebrew/bin/fish"
> args = ["--login", "-c", "tmux a -t base || tmux new -s base"]
> ```

This works perfectly for me, thank you!!

**Comment by zx0r** [comment]
```fish
# Register shell in system
$ echo $(which fishl) | sudo tee -a /etc/shells
$ chsh -s $(which fish)

$ echo $SHELL; echo $TERM
/usr/local/bin/fish
xterm-256color

```

```fish
# NOTE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

#  █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
# ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
# ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝
# ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝
# ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║
# ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝
#		“Stay Hungry, Stay Foolish.”
#                  - Steve Jobs  Apple

#  Author       : zx0r
#  License      : MIT License
#  Description  : alactitty.toml
#  Contact Info : https://github.com/zx0r/hyprdots-gentoo

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

[env]
TERM = "xterm-256color" 		# macOS | Linux

[terminal.shell]
program = "/usr/local/bin/fish"
args = ["--login"]  			# Perfectly work for macOS (Fish Shell + Tmux)

# program = "/opt/homebrew/bin/fish" 	# Use PATH=$(which fish)
# args = ["--login", "-c", "tmux"]
# args = ["--login", "-c", "tmux attach || tmux"]
# args = ["--login", "-c", "tmux attach-session -t base || tmux new-session -s base"]

```

```fish

# NOTE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

#  ████████╗███╗   ███╗██╗   ██╗██╗  ██╗
#  ╚══██╔══╝████╗ ████║██║   ██║╚██╗██╔╝
#     ██║   ██╔████╔██║██║   ██║ ╚███╔╝
#     ██║   ██║╚██╔╝██║██║   ██║ ██╔██╗
#     ██║   ██║ ╚═╝ ██║╚██████╔╝██╔╝ ██╗
#     ╚═╝   ╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═╝
#        “Stay Hungry, Stay Foolish.”
#           - Steve Jobs  Apple

#  Author       : zx0r
#  License      : MIT License
#  Description  : tmux.conf
#  Contact Info : https://github.com/zx0r/hyprdots-gentoo

# ━━━ General Settings ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

set -g default-shell "/usr/local/bin/fish"           # Default shell executable
set -g default-command "/usr/local/bin/fish"         # Default command for new windows
set -g default-terminal "$TERM"                      # Default terminal type (e.g., "screen-256color" or "tmux-256color")

set -ga terminal-overrides '*:Tc:RGB:Ss=\E[%p1%d q:Se=\E[3 q:Smulx=\E[4::%p1%dm:smcup@:rmcup@'
set -ga terminal-features '*:256:RGB:ccolour:cstyle:clipboard:focus:mouse:usstyle:overline:strikethrough:title:sync' # Set terminal features for terminal types read from terminfo(5)

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

```
