### ISSUE TITLE
When typing in alacritty, the cursor disappears.

### ISSUE THREAD

**Issue by Gxnum** [alacritty/alacritty#7191]
Is this a new feature or just a bug?
### System
Hyprland, Wayland, NixOS (Stable)
### Input and Output
`alacritty --version` alacritty 0.12.0

**Comment by chrisduerr** [comment]
It's a feature that is disabled by default:
https://github.com/alacritty/alacritty/blob/v0.12.2/alacritty.yml#L477

I'd assume you're talking about the mouse cursor. Did you enable this setting?

**Comment by Gxnum** [comment]
Oh, now that I look at my config, it looks like it was enabled. (will never copy alacritty config before checking on unixporn again)
