### ISSUE TITLE
Vi Mode Freezes

### ISSUE THREAD

**Issue by Pipboyguy** [alacritty/alacritty#7195]
Vi Mode freezes. I have to close the terminal instance and open a new one.

Two things worth noting in my current setup:
- The mentioned issue occurs intermittently
- The mentioned issue occurs only when alacrity is launched using the shortcut, never when launched from the command line
- I use https://github.com/jeffreytse/zsh-vi-mode, perhaps this is causing contention?

### System

OS: Linux
Version: alacritty 0.13.0-dev (33306142)
X11, ubuntu:GNOME, GNOME Shell

**Comment by chrisduerr** [comment]
If this happens specifically when running something inside the shell, what makes you think it's an Alacritty issue?

Does selection still work? If so, it's  not Alacritty.

**Comment by Pipboyguy** [comment]
Selection doesn't work.

**Comment by kchibisov** [comment]
I'd assume you select with the mouse and not by other means and you're talking about vi mode from alacritty on `ctrl + shift + space` (by default).

**Comment by chrisduerr** [comment]
If mouse selection doesn't work while holding shift, then Alacritty might actually be frozen. In that case a gdb backtrace would be helpful.

**Comment by kchibisov** [comment]
if you run alacritty with `--print-events` does it stuck?

**Comment by topnax** [comment]
Yes, it also does freeze with `--print-events`.

[print_events.zip](https://github.com/alacritty/alacritty/files/13601833/print_events.zip)

**Comment by topnax** [comment]
> Besides, obtaining a backtrace from freeze with gdb could help, though, you should build yourself with cargo run --release and attach to that process once it freezes.

What do you mean by:
> attach to that process
please?

**Comment by topnax** [comment]
Here is the `bt full` output:

[bt_full.zip](https://github.com/alacritty/alacritty/files/13601979/bt_full.zip)

Thanks for your cooperation.

**Comment by topnax** [comment]
I would also like to add that this issue began to appear without me updating `alacritty` (meaning that the referenced hash was working fine). It started appearing after I've updated my Ubuntu packages.

**Comment by kchibisov** [comment]
It just gets no events from X server it seems. Which video driver are you using?

**Comment by topnax** [comment]
I am using `amdgpu`:
```
amdgpu-dkms-firmware/now 1:5.11.32.40501-1337797 all [installed,local]
amdgpu-dkms/now 1:5.11.32.40501-1337797 all [installed,local]
amdgpu-install/now 21.40.1.40501-1337797 all [installed,local]
libdrm-amdgpu1/jammy-updates,now 2.4.113-2~ubuntu0.22.04.1 amd64 [installed,automatic]
libdrm-amdgpu1/jammy-updates,now 2.4.113-2~ubuntu0.22.04.1 i386 [installed,automatic]
xserver-xorg-video-amdgpu/jammy-updates,now 22.0.0-1ubuntu0.2 amd64 [installed]
```

**Comment by topnax** [comment]
Yeah, I can confirm that running `htop` and resizing the window using `i3` works correctly, as `htop` redraws its TUI.

When I run `htop,` then enter visual mode and `alacritty` freezes, `htop` beneath still updates to reflect the current usage.

**Comment by kchibisov** [comment]
so it's not freezing, you just don't get key events. Could you change the hotkey to enter Vi mode to `Ctrl + Esc`? I think maybe you trigger some global hotkey and it breaks something, you don't actually have a freeze it seems.

**Comment by topnax** [comment]
Still occurs when the following shortcut is used:

```toml
[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mods = "Shift"
```

I haven't been able to reproduce it with
```toml
[[keyboard.bindings]]
action = "ToggleViMode"
key = "M"
mods = "Shift"
```

🤔

**Comment by thephenrique** [comment]
I had the same problem too.

`CTRL+SHIFT+Space` (Vi Mode) occasionally prevents new events from entering.
To reproduce: Just enter and exit Vi Mode repeatedly. :smile: 

I don't know much about Alacritty internally, but taking a look, it seems that the origin of this "freeze" is when we pass `false` to `set_ime_allowed` inside of `toggle_vi_mode` of `/alacritty/src/event.rs`.


But, when passing `true` (or not making this call)...
https://github.com/alacritty/alacritty/blob/c0c267d60e1b877d5c2c76893751d13547a233c4/alacritty/src/event.rs#L870C55-L870C55
```rc
// self.window().set_ime_allowed(was_in_vi_mode);
self.window().set_ime_allowed(true);
```
... everything works perfectly.
But, I really don't know the impacts of making this call with `true` hardcoded.

Interesting: Not calling `set_ime_allowed` also solves the problem.

Running on X11.

**Comment by topnax** [comment]
I can confirm that @thephenrique 's proposed solution works for me.

**Comment by kchibisov** [comment]
Can anyone reproduce that on 0.12.3?

**Comment by robbe8441** [comment]
looks like i have a similar issue in Version 0.13.2
if i enable vi mode and then spam print statements then it freezes
but it works fine when disabling it again
