### ISSUE TITLE
Entry Point Not Found

### ISSUE THREAD

**Issue by Saya47** [alacritty/alacritty#7202]
Just installed Alacritty for the first time using the MSI installer and it errors upon running the program.
Edit: tried the portable version and it throws the same exception.
### System
OS: Windows 10 1803 (17134.1845)
Version: v0.12.2

### Logs
The procedure entry point ResizePseudoConsole could not be located in the dynamic link library C:\Program Files\Alacritty\alacritty.exe

![image](https://github.com/alacritty/alacritty/assets/35542834/c8a07fdc-470c-4ccc-9e04-561e15649235)

![image](https://github.com/alacritty/alacritty/assets/35542834/5e09a4f3-c34b-412b-8164-2e9de5dd8abe)

![image](https://github.com/alacritty/alacritty/assets/35542834/7969fe28-bb93-4cfb-aabb-78152b6a3567)

**Comment by chrisduerr** [comment]
Your Windows version is too old.
