### ISSUE TITLE
Windows Command `where` not showing output

### ISSUE THREAD

**Issue by JasonGrace2282** [alacritty/alacritty#7206]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Windows 10
Version: alacritty 0.12.2-rc1 (1e0f71e)

### Bug
When using the `where` command, it doesn't show output.
On Alacritty:
![image](https://github.com/alacritty/alacritty/assets/110117391/af62d7ba-de4a-4bb5-9bd3-954f32b22c51)

On cmd:
![image](https://github.com/alacritty/alacritty/assets/110117391/5af8cda5-250e-485a-933b-34389c982699)

**Comment by chrisduerr** [comment]
Unrelated to Alacritty, it has nothing to do with what runs inside it. `where` probably just isn't spitting anything out.

**Comment by JasonGrace2282** [comment]
@chrisduerr Then where does the output in cmd come from, if `where` doesn't spit anything out?

**Comment by chrisduerr** [comment]
Could be a million reasons. `PATH` might be different, it might be yet another ConPTY bug. The command itself might be doing something weird or special. It might not even be the same executable in both.

But unless you've got evidence that Alacritty is actually swallowing output, which is **extremely** unlikely, I don't think this is related to Alacritty.

**Comment by bitraid** [comment]
You are testing different shells: In one case (Alacritty) you are running PowerShell (`where` is an alias to `Where-Object`), and in the other you are running Windows command interpreter (`where` is an external command). Try running `where.exe` instead of `where` in PowerShell.
