### ISSUE TITLE
tengo este error al usar el archivo alacritty.yml

### ISSUE THREAD

**Issue by Emilio18s** [alacritty/alacritty#7207]
![IMG_20230910_120828](https://github.com/alacritty/alacritty/assets/86860340/76c48f53-7bb5-43eb-b645-a69b702f5cf6)

**Comment by damorenor** [comment]
Alacritty está migrando el formato de las configs de yaml a TOML (lo cual es genial si tienes configs grandes), así que la warning que te arroja te sugiere que migres tu config file (un archivo llamado `alacritty.yml`) de formato. Mirate la discusión en https://github.com/alacritty/alacritty/issues/6592

Literalmente, es lo que dice el texto del warning, leer no cuesta nada jajaja 😉

**Comment by kchibisov** [comment]
The issue tracker is english only, sorry.
