### ISSUE TITLE
Text not showing on Alacritty terminal

### ISSUE THREAD

**Issue by mokshsinghji** [alacritty/alacritty#7210]
Hi,

I recently installed Alacritty, and when I opened the application, the text doesn't show, however the cursor moves, suggesting that the terminal behind works as well. Also, I can type perfectly fine in the terminal as well. However, I am unable to see any of the text:

![image](https://github.com/alacritty/alacritty/assets/77796854/b4524ecf-483f-4295-96b2-fd160bd7840a)

### System

OS: Windows
Version: 0.12.0

**Comment by mokshsinghji** [comment]
I managed to turn on wsl from inside of alacritty, and it looks the same, however when i select the text, it shows it as the background:

![image](https://github.com/alacritty/alacritty/assets/77796854/e6b80c6f-6ff2-46f7-a723-0d2d32a3d089)

**Comment by chrisduerr** [comment]
Looks like a driver issue. What's your Windows version and GPU?

**Comment by woshichuanqilz** [comment]
> Looks like a driver issue. What's your Windows version and GPU?

Same issue for me. My gpu `Intel(R)UHD Graphics Family`. No external gpu card. Use Cpu built-in gpu. 

My Cpu is 12th Gen Intel(R) Core(TM) i7-12700K   3.61 GHz

**Comment by mokshsinghji** [comment]
I am using windows 11 and integrated gpu on intel i7 i7-2620M.

**Comment by kchibisov** [comment]
I'd suggest to try `alacritty -o debug.renderer="gles2_pure"`, but it looks like a broken driver if it end up like that.

**Comment by mokshsinghji** [comment]
> I'd suggest to try `alacritty -o debug.renderer="gles2_pure"`, but it looks like a broken driver if it end up like that.

that did not work either, ah well, i guess i am stuck with windows terminal for now then...

**Comment by kchibisov** [comment]
yeah, or bug your video driver provider to fix it. nothing we can do about it.
