### ISSUE TITLE
Can't clear screen when a command is running

### ISSUE THREAD

**Issue by akkadaya** [alacritty/alacritty#7216]
I can't clear the screen when a command is running. 

To reproduce:
1. Run `pip install -Ur <(pip list --format=json | jq -r '.[].name')` or any command with long output
2. Press `Ctrl + L` (Prints `^L` and nothing happens!)
3. Press `Command + K` (Prints `^L` and nothing happens!)

### System

OS: macOS
Version: `alacritty 0.12.2 (9d9982d)`

**Comment by kchibisov** [comment]
that's expected, because the clearing is done by the shell issuing a command back to alacritty. When something is running you can't clear the screen.

**Comment by akkadaya** [comment]
It's possible to do it on iTerm2, wouldn't it be nicer if we had this feature in Alacritty as well?

**Comment by kchibisov** [comment]
It was discussed in the past and was reject. if so called "feature" is implemented in X it doesn't mean that it should be implemented in Y.

**Comment by akkadaya** [comment]
Agree with you @nixpulvis

For now, I added key binding in search mode to clear the terminal so it goes
Ctrl + s -> Ctrl + l -> Ctrl +s

**Comment by akkadaya** [comment]
> It was discussed in the past and was reject. if so called "feature" is implemented in X it doesn't mean that it should be implemented in Y.

@kchibisov I have to contest that, we do pair programming and sometimes, I have to type sensitive data that I need to clear immediately.

This feature is a must and not just a copycat of another terminal's features.

**Comment by kchibisov** [comment]
if zellij is your terminal it's up to zellij to reset.

But you can consider doing `stty -echo && command && stty +echo`.

**Comment by nixpulvis** [comment]
@kchibisov @chrisduerr would you consider re-opening this issue?

**Comment by kchibisov** [comment]
What's the reason to do so? Clearing is up to the application running, the only thing terminal can do is to erase history, which we allow. And anyway, given that zellij is in use here, zellij should do that if they want to have a hack like that.

**Comment by nixpulvis** [comment]
I'm not thinking about zellij at all, in fact I have no idea what that is.

I'm thinking about my experience with the macOS Terminal.app, where I would sometimes have a long running process which I don't want to effect but I do need to clear the output.

I think there's a question of whether to clear by inserting newlines or to clear by actually clearing in this case.

The former is actually somewhat possible today by just creating a binding which inserts a bunch of newlines. The latter is actually what is being requested here. Sometimes a process prints sensitive information, which we just want to clear.

**Comment by kchibisov** [comment]
if something prints secrets to `stdout` it can print them into the system logger. Clearing want save you anything and give a false sense of security. Just redirect to `/dev/null` if you want secrets to be hidden.

**Comment by nixpulvis** [comment]
Sure, in hindsight that’s what a user should do, but sometimes they don’t.

Providing a way to handle this would be nice in my opinion.

Sometimes it’s also just nice to get a “clean slate”. It makes searching for relevant text a lot easier and generally reduces the cognitive burden of looking through the scrollback.

**Comment by chrisduerr** [comment]
> would you consider re-opening this issue?

No.

> I'm thinking about my experience with the macOS Terminal.app, where I would sometimes have a long running process which I don't want to effect but I do need to clear the output.

ctr+z -> clear -> fg

**Comment by nixpulvis** [comment]
Yea, that's _almost_ no effect and probably good enough for most people.

**Comment by akkadaya** [comment]
Thank you @nixpulvis, never mind @chrisduerr and @kchibisov.  
I've already moved to [WezTerm](https://wezfurlong.org/wezterm) as they support [clearing the terminal](https://wezfurlong.org/wezterm/config/lua/keyassignment/ClearScrollback.html) (ScrollbackAndViewport)

**Comment by pioz** [comment]
@kchibisov I also vote to implement this feature! It's too useful and convenient to be ignored. All the major terminal applications have it.

**Comment by wyat-soule-waggoner** [comment]
> ctr+z -> clear -> fg

ah yes, this is much easier than the Mac terminal default, Iterm2 default, Browser default, VScode default (and probably many more): `cmd+k` silly us.

sometimes you have a process that is logging a lot on the screen and want to clear it easily, why would this not be a feature? or at least something you can enable?

**Comment by AndreasSliwka** [comment]
Had the same problem, found this thread, read through the developers statement, deinstalled alacritty. Open Source Software should scratch your own itch, I understand, but if users ask for a feature and you dont want it because it fixes a problem but not your problem, than you dont want these users. Or in other words: you only want yourself as the user. Pity.
