### ISSUE TITLE
Presumable typo in definition of PI in rect.f.glsl : 3.1415926538 (should be 3.14159265358 ?)

### ISSUE THREAD

**Issue by scplusplus** [alacritty/alacritty#7218]

**Comment by scplusplus** [comment]
sorry i know i'm a bit nitpicky here XD

**Comment by kchibisov** [comment]
you're free to correct it, but it doesn't really matter, given that gles doesn't have good precision.

**Comment by scplusplus** [comment]
thanks! yeah the precision of gles is quite bad indeed.
