### ISSUE TITLE
Much darker/washed out colors

### ISSUE THREAD

**Issue by s0la** [alacritty/alacritty#7223]
### System

OS: Arch Linux
Version: 0.12.2
Linux/BSD: X11

### Logs

Font: SFMono

The issue I have is quite simple.. I started using Alacritty since Termite is no longer supported, and it looked like a seamless transition until I got the opened side by side, and saw the colors are drastically washed out on Alacritty compared to Termite and other terminals.
Here is an image with both of them:

![diff1](https://github.com/alacritty/alacritty/assets/6886981/38e4a82f-81ce-4a72-882f-061024b04cae)

I'm not sure how well picture does it justice, but it's pretty noticeable and I can certainly tell the colors on Termite (right one) pop out substantially more..

My configuration is super basic, basically just a font, colors and some geometry options.. As for font, I'm using SFMono at the moment, though the issue is the same with my custom version of Iosevka, so I guess the issue is not font related..

Is there some color space (or any other color related) option I'm missing, or something else on my end I can do to fix it, or the colors are simply inconsistent by design?

**Comment by kchibisov** [comment]
it seems like you're just used to `draw_bold_text_with_bright_colors` behavior in other terminals, which is false by default in alacritty or you've misconfigured the colors in your terminal.

Would suggest `true` for the said option and ensure that you're using the same color values for the same color names.

**Comment by s0la** [comment]
Thanks for a very fast response!

The option you suggested does make a difference with the bright colors (although there is still some small difference, but not enough to actually bother me), so big thanks for that. But colors in my prompt remain unchanged, since the prompt gets generated by bashrc, and it uses `\[\033[38;2;R;G;B;2m\]` syntax to color the foreground.. Since all the terminals use the same bashrc, it's not a problem with misconfigured/inconsistent color configuration.. It seems like colors are off in general compared to other terminals I tried, not just when bright ones weren't bold..

![prompt](https://github.com/alacritty/alacritty/assets/6886981/ef37b45c-2a3c-4028-a85e-734955517749)

Again, not sure how well picture demonstrates the difference, but the dark text on the Alacritty (left one) is barely visible/readable..
Is there a way to fix that as well?

**Comment by kchibisov** [comment]
>and it uses \[\033[38;2;R;G;B;2m\] syntax to color the foreground

you're asking for a dimmed text, you get a dimmed text. I don't see an issue here. Remove that 2 if you don't like it.

**Comment by s0la** [comment]
I'm really not sure what you mean, which 2 I should remove?
The issue is very pain and simple, and quite obvious.. Same coloring syntax/colors work differently in Alacrity compared to other terminals, I'm not sure how to simplify it more..

**Comment by s0la** [comment]
> you're asking for a dimmed text, you get a dimmed text.

I'm perfectly fine with the dimmed color in other terminals, because they render it in a way it's readable.

**Comment by kchibisov** [comment]
You're asking a terminal to dim a text, by using `2` in the attribute payload. If you want an RGB color you specify, don't ask a terminal to **dim** the color. We **dim** the color because you're asking to do so, with your escape sequence. Some terminals, don't dim the RGB colors, but it doesn't mean that everyone is the same here.


![picture](https://github.com/alacritty/alacritty/assets/27620401/eb15da9f-38df-4c56-9d36-2d2b200bdfe7)

The second color is **dimmed* because the payload asks for the dimmed text, not the original one, and that's exactly what you're using. If don't want dimming, just don't ask for it.

**Comment by s0la** [comment]
Oh OK, that 2.. In the example I provided

> `\[\033[38;2;R;G;B;2m\]`

there are two 2 (one after 38 - which I tried removing and it got broken, and the one before the m - the one you were referring to)..
Applying changes as you suggested fixed it, and now it works exactly how I wanted, so thanks a ton!!

Cheers :)

**Comment by stefanv** [comment]
Did you ever find out what causes this change? It happened to me with a recent Fedora upgrade of Alacritty:

![image](https://github.com/alacritty/alacritty/assets/45071/e3ee5ffa-89ac-4f24-a4cf-e21b7c857440)

**Comment by kchibisov** [comment]
@stefanv your is related to the fact that default colorscheme was changed if you want the old one it's present in `alacritty-theme` repo.

**Comment by stefanv** [comment]
Thank you, @kchibisov :pray: 

Instructions for others:

```
cd ~/.config/alacritty
wget https://raw.githubusercontent.com/alacritty/alacritty-theme/master/themes/alacritty_0_12.toml -O theme-alacritty_0_12.toml
```

Then insert the following line into the beginning of `alacritty.toml`:

```toml
import = [
  "~/.config/alacritty/theme-alacritty_0_12.toml"
]
```

Note when testing this that Alacritty automatically reloads its config file, so you can't compare by launching new terminals :)
