### ISSUE TITLE
Messages are not updated on sway if the dialog has the same size as the previous one

### ISSUE THREAD

**Issue by flash-freezing-lava** [alacritty/alacritty#7224]
### System
OS: ArchLinux
Version: 0.12.2, but also happens in the current master branch, and at least since 0.10.0 
DE: Sway

### Steps to reproduce

1. Edit the alacritty config, such that two messages with same length are emitted on startup:
   On the current master branch this can be done, by adding attributes x and y to window section top generate 2 warnings.
   On version 0.12.2, the window padding x and y value can be set to `a` to generate 2 errors.
2. Click on the cross to close the first message.

### Expected result
The second message is now shown.
Clicking again on the cross, closes the dialog.

### Actual result
The first message is still shown.
Clicking again on the cross, closes the dialog, so the first click was processed.

### First analysis
If messages result in dialog boxes of different size, the size and the text is updated. Only if the dialog box size is unchanged, the text isn't changed either. I couldn't reproduce the error on GNOME/Wayland or KDE/X11. If more the 2 messages with same dialog size are shown, the text of the first messages stays until the dialog gets closed the correct number of times. Some other actions trigger a text update (f.e. focusing another window, pressing enter) while others don't (f.e. pressing a non-enter key). If the first message is a warning and the second message an error, the color isn't updated either.

### Debugging results
Clicks correctly result in a call to `Display::draw`, which sees the new message. However, there seems to be no damage rect for the dialog box, which might be the reason, why the box text and color isn't updated. If `Display::swap_buffers` uses  `surface.swap_buffers` instead of `surface.swap_buffers_with_damage`, the error does not occur. However, I am a bit confused, whether this is really the underlying cause, because there isn't a damage rect on GNOME or KDE either, and the error doesn't occur there.

**Comment by kchibisov** [comment]
Could you test with the `alacritty -o debug.highlight_damage=true`? It should draw the purple rectangles over the things being damaged.

**Comment by flash-freezing-lava** [comment]
But they wouldn't be visible anyway, because `Display::draw` calls `self.highlight_damage` before drawing the message box.

**Comment by kchibisov** [comment]
Ah, but it works correctly, right? Since it should disable all the damage tracking if you use it.

**Comment by kchibisov** [comment]
If this debug option makes a difference than it's a damage tracking bug, otherwise some redraw/dirty logic.

**Comment by flash-freezing-lava** [comment]
It does work correctly, yes.
