### ISSUE TITLE
Bold font maybe need lighter.

### ISSUE THREAD

**Issue by water-chika** [alacritty/alacritty#7227]
When I play a text game I found there are some text is not seen.
In Linux console, font of \e[1;30;40m is gray. 
In alacritty, it is black.
So the text from the game could be seen on Linux Console. The text could not be seen on Alacritty.

**Comment by kchibisov** [comment]
it's not gray, it's a bold black.

Gray is `\e[90m` not `[1;30m`. However, you can work around that by using the legacy `draw_bold_text_with_bright_colors` config option.
