### ISSUE TITLE
[Feature Request] MACOS `command_as_alt`

### ISSUE THREAD

**Issue by daehyeok** [alacritty/alacritty#7228]
Can we  support `command_as_alt` for MAC OS like current  `option_as_alt` config?
  
 Little more background: I think  many Emacs user(include me) use command key as a meta. `(setq mac-command-modifier 'meta)` . to use Emacs on terminal, and command line editing on shell(like alt + f,b for moving cursor). I want to make default action of  command key as a alt key.

**Comment by kchibisov** [comment]
Can't you swap the keys inside the macOS settings? Or you don't want to do that for reasons?

The issue is that macOS is a bit complicated when it comes to remapping like that, unless you don't want to swap, but again, this is something that can be handled by the remapping tools on macOS itself.

**Comment by daehyeok** [comment]
Only need to change command key on the Emacs and Terminal.

Understood. maybe i need mass key binding configuration.

it will be another issue. but how can i migrated .yml key binding to toml file.

I compiled main branch and tried below config.
```
[keyboard]
bindings=[
    { "mods"= "Command", "key"= "b",  "chars"= "\x1bb" },
]
```

but it throw config parser error

**Comment by kchibisov** [comment]
@daehyeok the `alacritty migrate` should help with that. The `\x1bb` syntax can't be used due to toml not supporting `\x` you'd need `\u` and write the unicode char.

**Comment by chrisduerr** [comment]
Presonally I see zero reason to mess with this. All the keys emacs needs are already available. If you don't like the location they're in on your operating system, that's up to your operating system to account for.

The existing alt/option binding are only there because macOS' alt/alt gr setup is atrocious.

**Comment by frobware** [comment]
> Can we support `command_as_alt` for MAC OS like current `option_as_alt` config?
> 
> Little more background: I think many Emacs user(include me) use command key as a meta. `(setq mac-command-modifier 'meta)` . to use Emacs on terminal, and command line editing on shell(like alt + f,b for moving cursor). I want to make default action of command key as a alt key.

Should it help, I just made a brute force change to swap cmd/alt in winit. 

The following branch https://github.com/frobware/alacritty/tree/swap-cmd-alt-0.12.2 picks up my change to winit: https://github.com/frobware/winit/tree/swap-cmd-alt-0.28.6. The change in winit unconditionally swaps cmd/{option,alt}. 

My primary motivation for the change was also Emacs related (i.e., `emacs -nw`).
