### ISSUE TITLE
Allow changing the config file via IPC

### ISSUE THREAD

**Issue by leftshift** [alacritty/alacritty#7232]
You can already have different config 'profiles' by specifying different `--config-file`s on startup.

However, it would also be cool to be able to change which config an already running instance is using, e.g. via `alacritty msg config config_file=foo.toml`. This would allow to switch which profile a given window uses.

My use case is, I like having different font sizes and color schemes for 'utility terminals' where I'm messing around with commands and terminals in which I use neovim or do other things where small font sizes are more useful.

**Comment by chrisduerr** [comment]
I'm not really interested in implementing this, since it would just make the entire config handling too complex. However the existing IPC mechanisms should make it trivial to design a little helper that effectively does the same through `alacritty msg config`.
