### ISSUE TITLE
How to use different fonts in Chinese and English

### ISSUE THREAD

**Issue by xhsky** [alacritty/alacritty#7233]
Currently, it is too ugly to use the same font for all characters. 
Is there a way to separate Chinese and English into using a set of fonts, similar to the "NON-ASCII Font" configuration of iterm2?

**Comment by kchibisov** [comment]
duplicate of #957

**Comment by fingertap** [comment]
I don't see the clear duplication of this issue with #957 . I think many CJK users would need to google the config for this question in alacritty. A better answer here will save many users' time.

**Comment by kchibisov** [comment]
System should generally deal with this, the same font is not used for everything, but rather your system fallback system. The only issue I could see is that somehow we could need to pass locale to font system,
