### ISSUE TITLE
Bell causes window rendering updates to stop on Windows

### ISSUE THREAD

**Issue by bkoropoff** [alacritty/alacritty#7236]
When I do something in WSL that causes a terminal bell, the Alacritty window ceases to update until I move the window to another monitor, resize it, etc.

I bisected the issue to this commit: https://github.com/alacritty/alacritty/commit/a189861880aafcce760e3a142bc2d391f2801f64

### System

OS: Windows
Version: master

**Comment by chrisduerr** [comment]
Can you try https://github.com/alacritty/alacritty/pull/7220?

**Comment by kchibisov** [comment]
That's on windows, it shouldn't fix anything on windows from what I can tell.

**Comment by chrisduerr** [comment]
> That's on windows, it shouldn't fix anything on windows from what I can tell.

People testing this PR have reported so many (unrelated) things fixed, it's probably worth a shot. :P

**Comment by bkoropoff** [comment]
#7220 does not appear to fix the issue.

**Comment by chrisduerr** [comment]
Can you select text?

**Comment by bkoropoff** [comment]
I can select text normally.  It does not cause frozen rendering to unfreeze, however.

**Comment by chrisduerr** [comment]
Sounds like it might be a Windows ConPTY issue then if Alacritty isn't actually freezing itself.

Do you have a Linux system to test your config with?

**Comment by kchibisov** [comment]
@bkoropoff could you elaborate on select part, do you see a visual change due to selection or you could just copy something? If you see a visual update then it's different, but if you don't see anything, it's likely the scheduling got broken for you.

**Comment by kchibisov** [comment]
In any way, the `--print-events` log is really needed for this one to at least tell who is responsible for the freeze. I'm 90% certain that it's upstream winit + our new scheduling and that it doesn't want to wakeup sometimes on windows.

**Comment by bkoropoff** [comment]
Selection does not show up when rendering has stopped.  I'll try to get logs.

**Comment by bkoropoff** [comment]
I found from experimentation that commenting out the following block prevents the issue: https://github.com/alacritty/alacritty/blob/master/alacritty/src/window_context.rs#L390-L392

```rust
        if !self.display.visual_bell.completed() {
            self.display.window.request_redraw();
        }
```

Alternatively, removing the conditional here and always calling through to winit fixes it: https://github.com/alacritty/alacritty/blob/master/alacritty/src/display/window.rs#L241

```rust
    pub fn request_redraw(&mut self) {
        if !self.requested_redraw {
            self.requested_redraw = true;
            self.window.request_redraw();
        }
    }
```

It seems like calling `request_redraw` on the underlying winit window in this path doesn't actually cause a subsequent redraw event to surface.  Because handling a redraw is the only thing that clears `requested_redraw`, subsequent calls (e.g. when handling keyboard events) do nothing, causing all redrawing to cease.  Causing a redraw event from Windows itself by invalidating the window gets it out of this state.

On Windows, the winit `request_redraw` makes a direct Win32 API call to `RedrawWindow`, so there must be some other subtlety causing this behavior.

**Comment by bkoropoff** [comment]
Log from causing a terminal bell:

[Alacritty-16108.log](https://github.com/alacritty/alacritty/files/12788049/Alacritty-16108.log)

**Comment by kchibisov** [comment]
Well, it's basically `winit` never delivering a `RedrawRequested` even though, it was asked to do so? Because clearly if we ask it to redraw it should send one eventually, which is not happening here.

**Comment by kchibisov** [comment]
Could you try https://github.com/alacritty/alacritty/pull/7297 ?

**Comment by kchibisov** [comment]
Upstream issue https://github.com/rust-windowing/winit/issues/3150

**Comment by bkoropoff** [comment]
> Could you try #7297 ?

Seems to fix it here.
