### ISSUE TITLE
Issues with MacOS 14.0 Sonoma

### ISSUE THREAD

**Issue by proski** [alacritty/alacritty#7242]
### System

OS: MacOS 14.0
Version: 0.12.2, current master branch

### Logs

```
thread 'PTY reader' panicked at alacritty_terminal/src/tty/unix.rs:418:25:
attempt to multiply with overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/5ae769f06bbe2afc50cde219757a5915e61ba365/library/core/src/panicking.rs:127:5
   3: <alacritty_terminal::event::WindowSize as alacritty_terminal::tty::unix::ToWinsize>::to_winsize
             at ./src/alacritty-0.12/alacritty_terminal/src/tty/unix.rs:418:25
   4: <alacritty_terminal::tty::unix::Pty as alacritty_terminal::event::OnResize>::on_resize
             at ./src/alacritty-0.12/alacritty_terminal/src/tty/unix.rs:397:19
   5: alacritty_terminal::event_loop::EventLoop<T,U>::drain_recv_channel
             at ./src/alacritty-0.12/alacritty_terminal/src/event_loop.rs:185:45
   6: alacritty_terminal::event_loop::EventLoop<T,U>::channel_event
             at ./src/alacritty-0.12/alacritty_terminal/src/event_loop.rs:196:13
   7: alacritty_terminal::event_loop::EventLoop<T,U>::spawn::{{closure}}
             at ./src/alacritty-0.12/alacritty_terminal/src/event_loop.rs:356:33
```

Alacritty 0.12.2 and the current master branch have two issues running on the recently released MacOS 14.0 Sonoma. One issue is panic on multiplication overflow. It's visible with RUST_BACKTRACE=1 in debug build. Otherwise it can look like a hang. Another issue is that Alacritty starts but the text is shown about one line above the expected location. The uppermost line is partly hidden by the title. Mouse selection appears one or two lines above the expected location under the cursor.

The branch from https://github.com/alacritty/alacritty/pull/7220 appears to be working normally. The behavior depends on the `window.startup_mode` setting.

* No settings or `Windowed`: both 0.12.2 and master crash.
* `Maximized`: 0.12.2 crashes, master exhibits the "line under title" issue.
* `Fullscreen`: 0.12.2 crashes, master works correctly (until it's unmaximized)
* `SimpleFullscreen`: 0.12.2 crashes, master works correctly

<img width="1512" alt="alacritty-screenshot" src="https://github.com/alacritty/alacritty/assets/1317472/b90294c3-57ce-4014-ae23-d0ddb1bedef2">

**Comment by kchibisov** [comment]
@proski given that you've tested it, could you test that `cargo -p winit` on `0.12.2` fixes the issue? We pushed a fix upstream, and we're unlikely to push alacritty with a fix, but at least I want to double check that it works...

**Comment by proski** [comment]
Alacritty 0.12.2 with winit 0.28.7 is working perfectly with all 4 `window.startup_mode` settings. Thank you!

**Comment by kchibisov** [comment]
thanks for testing. We discussed with @chrisduerr whether we need a patch or not, but decided to probably wait for 0.13 which should be within a month.

But if @chrisduerr is fine with pushing a patch release (with an sctk bump as well btw, since 0.12.2 crashes on recent sway as well). I don't mind that.

It's just the `0.13.0` is sooo close.

**Comment by proski** [comment]
Frequent releases are better for users as they won't have to look to alternatives if the fixes are provided quickly. Very few people would downgrade MacOS because of Alacritty. They are more likely to try a few workarounds and migrate to a different terminal, especially if the terminal is essential for their day-to-day work.

**Comment by kchibisov** [comment]
While it's not fixed on master, the `rc` has a fix for it. See https://github.com/alacritty/alacritty/releases/tag/v0.12.3-rc1
