### ISSUE TITLE
macOS Sonoma - current line seems to be off by 2 lines

### ISSUE THREAD

**Issue by pejax** [alacritty/alacritty#7248]
### System

OS: macOS Sonoma 14.0
Alacritty Version: 0.12.2

### Problem
1.) When selecting text in the Alacritty window with the mouse, the text 2 lines above the current line is selected.
2.) When opening a file with neovim in the Alacritty window, the top two lines of the file are not displayed.

BTW - Terminal and iTerm handle these cases correctly on Sonoma.

Thanks

**Comment by kchibisov** [comment]
try latest `rc`.

**Comment by kchibisov** [comment]
https://github.com/alacritty/alacritty/releases
