### ISSUE TITLE
[Feature Request] Support marks (or scroll to last command)

### ISSUE THREAD

**Issue by gibfahn** [alacritty/alacritty#725]
This is a really neat feature that I've only seen in [`Terminal.app`](https://en.wikipedia.org/wiki/Terminal_(macOS)) so far. You can use <kbd>Cmd</kbd> <kbd>Up</kbd> and <kbd>Cmd</kbd> <kbd>Down</kbd> to cycle between marks in the terminal, and whenever you press <kbd>Enter</kbd> it auto-inserts a mark (you can disable it in settings, or use <kbd>Cmd</kbd> <kbd>Enter</kbd> to not insert a mark). <kbd>Cmd</kbd> <kbd>Shift</kbd> <kbd>Up</kbd> selects up to the previous command.

Basically <kbd>Cmd</kbd> <kbd>Up</kbd> scrolls up a prompt.

Once you're used to it it's difficult to live without. I don't know how much overhead it would take to implement, but I'd be fine with an opt-in switch for it. Obviously this will be much more useful once https://github.com/jwilm/alacritty/pull/657 (scrollback) lands.

I'm not aware of any terminal emulators that have this feature in Linux, so it'd be cool to have it available there as well.

### Links:

- [In depth description of `Terminal.app` marks](https://apple.stackexchange.com/questions/209635/what-functionality-do-marks-offer-in-the-el-capitan-terminal)
- [Feature request in vte (`gnome-terminal`)](https://bugzilla.gnome.org/show_bug.cgi?id=767230)

![terminalmarks](https://user-images.githubusercontent.com/15943089/29241118-023e28fa-7f6b-11e7-90c0-19c729bf6bd2.gif)

**Comment by TheZoq2** [comment]
This is a feature I too would like to see and I'd be happy to implement it, especially the returning to the last executed command part. However, I could use some pointers for how to do it.

My idea would be to add a `Vec` or possibly `VecDeque` of markpoints to the `Term` struct in `alacritty_terminal` and push new markpoints onto that whenever the user presses `enter`. However, I can't figure out where input handling is done, The `carriage_return` and `linefeed` events seem to happen for not just input events but for events from programs. Is there another event where I could detect actual user newline presses?

Also, is the Term struct the right place to put this stuff, or is there something better?

**Comment by chrisduerr** [comment]
You cannot add this without supporting proprietary escape sequences. And I'm not aware of any that are reasonably well established.

**Comment by TheZoq2** [comment]
Oh that sucks. Is that the case even for adding a mark every time the user presses "enter"?

Another alternative which would work just as well for my use case would be a "jump to a keyword" binding, for example, to search for a word in my prompt and jumping there. Would that be easier to implement and in scope of the project?

**Comment by chrisduerr** [comment]
> Is that the case even for adding a mark every time the user presses "enter"?

That doesn't work. Pressing enter is in no way related to submitting a command.

> Another alternative which would work just as well for my use case would be a "jump to a keyword" binding, for example, to search for a word in my prompt and jumping there. Would that be easier to implement and in scope of the project?

You can already search for things. Are you looking for a way to prepopulate the search query?

**Comment by TheZoq2** [comment]
> That doesn't work. Pressing enter is in no way related to submitting a command.

Maybe I should give some context for what I want. Whenever a long command, like a cargo build is run, I often want to scroll to the top of the output, as that's usually where the most relevant errors are. In that case, pressing enter *would* work fine as a detector. It would also work in repls, but obviously not in things like vim. From what I can tell from the first post in the issue, that's roughly what the macos terminal does

Perhaps a more general solution would be to have a `add markpoint` keybind which you can bind as you please in case you want some different behaviour.

> You can already search for things. Are you looking for a way to prepopulate the search query?

Yea, I made an awful xdotool hack to essentially `enter vi mode, start search. type <part of my prompt>, jump to next match`. Having a pre-populated search would indeed solve it

**Comment by chrisduerr** [comment]
> Maybe I should give some context for what I want. Whenever a long command, like a cargo build is run, I often want to scroll to the top of the output, as that's usually where the most relevant errors are. In that case, pressing enter would work fine as a detector. It would also work in repls, but obviously not in things like vim. From what I can tell from the first post in the issue, that's roughly what the macos terminal does

It wouldn't. STDIN and STDOUT are in no way synchronized. The time when I press the keys and the time and location when that command is submitted are two completely different things.

> Yea, I made an awful xdotool hack to essentially enter vi mode, start search. type <part of my prompt>, jump to next match. Having a pre-populated search would indeed solve it

I have considered this, but am not aware of any great way to make this a user friendly configuration option.

**Comment by TheZoq2** [comment]
> It wouldn't. STDIN and STDOUT are in no way synchronized. The time when I press the keys and the time and location when that command is submitted are two completely different things.

Ah right, makes sense even if it's a bit sad :(

> I have considered this, but am not aware of any great way to make this a user friendly configuration option.

How about one new configuration field `keyword = <some regex>` (or maybe just a word, not sure)

And 2 new keybinds for `next keyword` and `previous keyword`? I guess it could also be integrated with the search feature, but for my use case, they kind of seem like 2 separate things

**Comment by TheZoq2** [comment]
I guess another option would be to have a config flag for `predefined_search` and a binding to search for the pre-defined string.

**Comment by chrisduerr** [comment]
That doesn't sound like a good solution.

**Comment by nixpulvis** [comment]
> You cannot add this without supporting proprietary escape sequences. And I'm not aware of any that are reasonably well established.

Looks like iTerm is leading the pack on this with another `OSC 1337` command. I saw [Egmont posted a suggestion for using a CSI parameter](https://gitlab.gnome.org/GNOME/vte/-/issues/295#note_942931): "I do also want a better sequence to do that than OSC; a simple CSI to set/remove the mark in the current line". It seems like VTE is interested in this feature as well.

There is [a terminal-wg](https://gitlab.freedesktop.org/terminal-wg/specifications/-/issues/28) issue on the matter, perhaps we should participate in that.

**Comment by lonelykid** [comment]
A related request. I miss the iterm2 osc 1337 sequence to upload/download files through ssh.

**Comment by partiallyordered** [comment]
Also see:
https://github.com/alacritty/alacritty/issues/5850
https://github.com/alacritty/alacritty/pull/5860

**Comment by zer0-x** [comment]
Kitty supports that: https://sw.kovidgoyal.net/kitty/actions/#action-scroll_to_prompt

Could be useful in as reference.

**Comment by kchibisov** [comment]
I've sort of lost interest in marks myself, given that the specifications and expectations on how they should work unclear. However recent master of alacritty allows you to create bindings across mods, so you can simply do marks yourself with the bindings by putting special character for `Search` mode and jumping to it.

I'll close this issue because we have #5850 which is what marks are about.

**Comment by zefr0x** [comment]
> However recent master of alacritty allows you to create bindings across mods, so you can simply do marks yourself with the bindings by putting special character for `Search` mode and jumping to it.

If anyone has been able to utilize those features to have bindings for the jumping functionality please provide your config here.
