### ISSUE TITLE
Rendering problem with emojis and wrapped lines on WSL 1/2

### ISSUE THREAD

**Issue by cparadis6191** [alacritty/alacritty#7252]
### System

OS: Microsoft Windows [Version 10.0.19045.3448]
Version: alacritty 0.12.2 (9d9982d)

```bash
$ cmd.exe /c wsl --version
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.3448
```

This happens on two Windows machines with different versions of Windows and
WSL. I've provided the information for the one machine that is more easily
accessible to me.

I've also tested this on Linux Mint and it did not exhibit the problem. I can provide version information if necessary.

### Logs

Crashes: None

### Reproduction Steps

The simplest way to reproduce the problem is to resize Alacritty to about 100
columns so that only line 87 of [problemerino.txt](https://github.com/alacritty/alacritty/files/12754600/problemerino.txt)
 is wrapped
and run the following command:

```bash
$ cat problemerino.txt
```

An example of the problematic rendering can be seen in:

![emojis_and_wrapping_problem](https://github.com/alacritty/alacritty/assets/1832252/9c210c35-6f42-408b-9ebd-96689c3fc15b)

Next, run the following command using [noproblemerino.txt](https://github.com/alacritty/alacritty/files/12754604/noproblemerino.txt):

```bash
$ cat noproblemerino.txt
```

An example of the *unproblematic* rendering can be seen in:

![no_emojis_no_problem](https://github.com/alacritty/alacritty/assets/1832252/2093c143-63fb-48d2-a733-56b752b3772c)

Finally, resize Alacritty to at least 130 columns so that no lines are wrapped
and run the following command:

```bash
$ cat problemerino.txt
```

An example of the *unproblematic* rendering can be seen in:

![no_wrapping_no_problem](https://github.com/alacritty/alacritty/assets/1832252/18c2bbdf-7ddb-451c-b9f3-200574e53f73)

I can provide more information or run more tests if necessary.

**Comment by kchibisov** [comment]
>I've also tested this on Linux Mint and it did not exhibit the problem. I can provide version information if necessary.

It's a conpty issue nothing we can do about. The only option is to 1. Update windows 2. Build conpty.dll/OpenConsole.exe binaries and put along side the `alacritty.exe`(you need a build from master for that).
