### ISSUE TITLE
Help message wrongly says default title is "Alacritty" but it's `user@host:path`

### ISSUE THREAD

**Issue by snosratiershad** [alacritty/alacritty#7257]
Related section in help message:
```
    -T, --title <TITLE>
            Defines the window title [default: Alacritty]
```
### System

OS: Linux
Version: alacritty 0.12.2
Linux: X11/Wayland, gnome

**Comment by kchibisov** [comment]
it's not wrongly, it's the initial title. The title could be change by the running applications at any time. If nothing changes the title it'll be `Alacritty`
