### ISSUE TITLE
Error initializing the shaders when updated to latest version of mesa

### ISSUE THREAD

**Issue by GoodBoyNeon** [alacritty/alacritty#7260]
### System

OS: Linux
Version: alacritty 0.12.2 (9d9982df)
Linux/BSD: X11 (AwesomeWM)

### Logs
Error Message:
```
Error: There was an error initializing the shaders: Failed linking shader: error: If/then statements not supported by R300/R400 shaders, should have been flattened by peephole_select.
```

### Explanation
Alacritty throws the above error when using the latest version of `mesa` (23.1.8). The newest version of mesa that works is 23.1.7.

**Comment by kchibisov** [comment]
@GoodBoyNeon report this straight to mesa as a regression.

**Comment by GoodBoyNeon** [comment]
Alrighty, I'll keep up with the updates there

**Comment by kchibisov** [comment]
@GoodBoyNeon are you sure that the version you've used is `23.1.8`? Maybe it was `23.2.0` actually?
