### ISSUE TITLE
Default font size too big

### ISSUE THREAD

**Issue by MarkuBu** [alacritty/alacritty#7275]
I need to add size: 8 to get a sane font size in Alacritty.  On the screenshot you can see Konsole with Fira Code in 12pt (no difference if I use monospace) in the top and Alacritty with Monospace 8pt at the bottom

If I use Fira Code in Alacritty everything looks weired

### System

OS: Linux (Kubuntu 22.04)
Version: alacritty 0.13.0-dev (83b80479)
Linux/BSD: X11 

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`
[log.txt](https://github.com/alacritty/alacritty/files/12840389/log.txt)
[alacritty.txt](https://github.com/alacritty/alacritty/files/12840398/alacritty.txt)

Font Size
![Screenshot_20231008_124907](https://github.com/alacritty/alacritty/assets/16163058/3ca3b254-7489-480b-ba16-6b2c55662bcd)

Fira Code in Alacritty
![Screenshot_20231008_125405](https://github.com/alacritty/alacritty/assets/16163058/2792d9a5-5b59-482d-a854-50cb171cc2a6)

**Comment by kchibisov** [comment]
The issue is that your `monospace` is not set to `Fira Code` but to some proportional font? You can check with `fc-match monospace` to see what alacritty will get.

You could try to force `Fira` with `family = "Fira Code"`.

>I need to add size: 8 to get a sane font size in Alacritty

Alacritty scales the font with the `DPI`, you can disable it by setting the DPI to `1` or `WINIT_X11_SCALE_FACTOR=1` in alacritty's env section.

**Comment by MarkuBu** [comment]
Please ignore the configuration on the screenshot. I set it to Fira Code (switched to toml configuration)

```
[font.normal]                                                                        
family = "Fira Code"                                                                 
style = "Regular"
```

**Comment by kchibisov** [comment]
I'd assume it works then? `alacritty -v` tells what it tries to load and `fc-match` could also give a hint.

**Comment by MarkuBu** [comment]
I'm sorry for the confusion. If I set the font family to Fira Code it looks like on the second screenshot

**Comment by MarkuBu** [comment]
I fixed the Fira Code issue. It must be called "Fira Code Nerd Font"

But the font size issue is still not fixed. DPI or WINIT_X11_SCALE_FACTOR don't change anything.

I attached my current alacritty.toml
[alacritty.txt](https://github.com/alacritty/alacritty/files/12903827/alacritty.txt)
