### ISSUE TITLE
`CreatePseudoConsole` not found

### ISSUE THREAD

**Issue by annadostoevskaya** [alacritty/alacritty#7278]
### System

OS: Windows 7
Version: Alacritty-v0.12.3-portable.exe

### Logs

Crashes: Nothing
Font/Terminal size: Nothing
Keyboard and bindings: Nothing

Entry point in function `CreatePseudoConsole` not found in `kernel32.dll` library.

**Comment by kchibisov** [comment]
Windows 7 is not supported. https://github.com/alacritty/alacritty#requirements
