### ISSUE TITLE
[Windows] Broken Highlighting

### ISSUE THREAD

**Issue by JasonGrace2282** [alacritty/alacritty#7279]
The Alacritty highlighting seems to randomly break without any warning.
![image](https://github.com/alacritty/alacritty/assets/110117391/07bc6951-2860-453d-991f-2ee58dceca86)

### System

OS: Windows 10 Pro
Version: alacritty 0.12.2-rc1 (1e0f71e)

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: Consolas, window scale factor=1
Keyboard and bindings: Default

**Comment by chrisduerr** [comment]
What do you mean by highlighting? Selection?

Also does the rest of the terminal stay functional?

**Comment by JasonGrace2282** [comment]
By highlighting, I mean that the pwd (and if you type anything after it) gets highlighted in pink. 
The terminal still works, but it's harder to see the text (white on pink is hard to see).
Interestingly, closing and opening the terminal gets rid of the issue temporarily.

**Comment by kchibisov** [comment]
The actual content is not controlled by alacritty, we just render what we're told to.

Try `reset`, your shell is likely breaks.
