### ISSUE TITLE
Background Color Issue in `helix-editor` Rendering

### ISSUE THREAD

**Issue by allaboutevemirolive** [alacritty/alacritty#7282]
I compiled the Helix text editor in Debian using the `cargo build` command with no optimizations (`0 optimization`). After that, I accessed the compiled binary in the `target/debug` directory using the `./hx` command. When I ran the binary, I encountered an issue where the background color did not render correctly, resulting in an empty block along the side of the terminal.

### System Information

- Operating System: Linux, Debian
- Desktop Environment: MATE Desktop Environment
- Alacritty Version: 0.13.0-dev

### Alacritty (Incorrectly Rendered)

![Incorrect Render](https://github.com/alacritty/alacritty/assets/112833599/97ba0d6b-33b3-46f4-9cb1-be2b89ffbfc5)

![Incorrect Render](https://github.com/alacritty/alacritty/assets/112833599/6e4f2907-d2ed-431d-952b-24710f81831e)

### MATE TERMINAL (Correctly Rendered)

![Correct Render](https://github.com/alacritty/alacritty/assets/112833599/c7769768-110c-45a3-84fd-d667c0023a62)

**Comment by kchibisov** [comment]
This is called padding. This is expected and also present in `mate terminal`, but it's just less.

You can even it out with `dynamic_padding` or ask helix to actually set the background color with the escape sequence if they want to.
