### ISSUE TITLE
PgDn and PgUp are not recognized

### ISSUE THREAD

**Issue by madorian** [alacritty/alacritty#7284]
Somehow PgDn and PgUp are not recognized in alacritty.

I'm testing with vim.

If I start xterm, wezterm or gnome-terminal, it works fine.

xev prints:

```
$ xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf "%-3s %s\n", $5, $8 }'
117 Next
112 Prior
````
I've tried setting TERM to linux and xterm, but has no effect.

Any pointers as to how I troubleshoot this?;)

Like, how can first of all see what keys Alacritty receives? Also, does maybe Alacritty intercepts these keys?

### System

OS: GNU/Linux
Version: 0.12.0
Xorg/XMonad

**Comment by kchibisov** [comment]
>Like, how can first of all see what keys Alacritty receives? Also, does maybe Alacritty intercepts these keys?

Depending on the mode, but it shouldn't. Unless you configured it in a way to do so.

You can test with `alacritty --print-events`.

**Comment by kchibisov** [comment]
if they are still not recognized with the latest rc let me know.
