### ISSUE TITLE
Error when migrating to toml

### ISSUE THREAD

**Issue by edmundho2000** [alacritty/alacritty#7289]
### System

OS: POP OS
Version: `alacritty 0.12.3` output
Linux/BSD: X11

### Logs

edmund@pop-os:~$ alacritty migrate
Configuration file migration failed:
    "/home/edmund/.config/alacritty/alacritty.yml": parsing error: Yaml conversion error: unsupported unit type

First time reporting an issue in github, so i might be doing this wrong. But i I downloaded the yml file from the releases page and go tthis error when trying to migrate.

**Comment by chrisduerr** [comment]
> But i I downloaded the yml file from the releases page and go tthis error when trying to migrate.

What would make you think that would do anything? There's nothing in this file…

**Comment by h4ppyr0gu3** [comment]
I have the same issue with my config file, What does this error mean?

**Comment by h4ppyr0gu3** [comment]
This issue seems to come from not having a value for a specific key in my case

**Comment by ciscohack** [comment]
I am also having the same error.migrate should tell which line or value is causing problem

**Comment by SebOuellette** [comment]
I also have the same issue. @chrisduerr Terrible support.

**Comment by ciscohack** [comment]
I created a TOML file from scratch ..This migration tool option is badly designed... Earlier I had DPI option in old config for macOS but now in TOML I don't see doc for that option and it's not working also

**Comment by kchibisov** [comment]
DPI was removed in 0.4.0 or something like that.

**Comment by chrisduerr** [comment]
I don't think we ever had a dpi option, the `scale_with_dpi` option was removed in… 0.2.2.

**Comment by Msouza91** [comment]
It would be nice if the tool would say which key it couldn't convert, going through all settings one by one is asinine

**Comment by kchibisov** [comment]
See https://github.com/alacritty/alacritty/pull/7536

**Comment by Msouza91** [comment]
I couldn't deal with a broken terminal client and that horrible message, fortunately my config wasn't too complex and with neovim the conversion to toml was less painful than anticipated.
I could keep the "broken" yaml to test a conversion after the fix is merged and test, not sure if useful for anyone...
