### ISSUE TITLE
Unable to launch alacritty with `-o window.startup_mode=Fullscreen`

### ISSUE THREAD

**Issue by oscarvarto** [alacritty/alacritty#7291]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

## Description
It should be possible to pass the option to open alacritty in Fullscreen mode.

## Expected
Alacritty respects the command line option override for opening alacritty in Fullscreen mode.

### System

OS: CachyOS linux (Arch Linux variant)
Version: `alacritty --version` output: alacritty 0.13.0-dev (b4130ddf). Compiled from source from AUR repo `alacritty-git`.

Linux/BSD: Wayland, WM: hyprland (but the same error is shown in KDE Wayland session/X11 session).

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv -o window.startup_mode=Fullscreen`:
pastebin: https://pastebin.com/vF0Qsmjx

Keyboard and bindings: `alacritty -vv --print-events -o window.startup_mode=Fullscreen`
pastebin: https://pastebin.com/REHV8qH2

If I hardcode the startup_mode=Fullscreen option in the alacritty.toml file, it opens in Fullscren, but I am not able to override this configuration from the command line.

I may have missed more details. Please let me know if I need to put more information here.

**Comment by kchibisov** [comment]
`alacritty -o 'window.start_mode="Fullscreen"'`.

**Comment by oscarvarto** [comment]
@kchibisov Thanks for the quick answer. 

Why is it not necessary to quote other options like `window.padding.x=30`?

**Comment by kchibisov** [comment]
`30` is a number, `Fullscreen` is a string, thus `"Fullscreen"`. just treat those `-o` stuff as a valid toml.
