### ISSUE TITLE
Does not support hiding command from history

### ISSUE THREAD

**Issue by quaintdev** [alacritty/alacritty#7293]
Alacritty does not support hiding command from history. For example, in most terminals I could just give a single space at beginning and that command would be hidden from history. This is not possible in Alacritty. It would be nice to have this feature.

### System

OS: Linux
Version: alacritty 0.12.2
Linux/Wayland, Sway WM

**Comment by bynect** [comment]
This problem is probably related to your shell. For example, in zsh I use the `HIST_IGNORE_SPACE` option.
