### ISSUE TITLE
Alacritty not flushing characters until resize

### ISSUE THREAD

**Issue by bynect** [alacritty/alacritty#7294]
I just did a fresh installation of void linux on my new asus laptop.
I have a problem with alacritty where nothing I type is actually rendered until I resize the window.
I am using xorg and I have an optimus configuration with the intel igpu and nvidia dgpu.
Running alacritty normally results in this problem (even as root).
Running with prime-run results in a black screen.
Any pointer would be appreciated.

### System

OS: Void Linux
Version: 0.12.3
X11 with dwm

**Comment by chrisduerr** [comment]
Can you try https://github.com/alacritty/alacritty/pull/7220?

**Comment by kchibisov** [comment]
>Version: 0.12.3

This won't help, it's the same issue we had with nvidia + GLX. The only option is to force EGL with `alacritty -o 'debug.prefer_egl=true'` to work around it.

**Comment by kchibisov** [comment]
>intel igpu

Ensure that you're using modesetting and not `xf86-video-intel`.

**Comment by bynect** [comment]
> Can you try #7220?

How would I go about that? I installed alacritty with the void binary packages.

**Comment by bynect** [comment]
> > Version: 0.12.3
> 
> This won't help, it's the same issue we had with nvidia + GLX. The only option is to force EGL with `alacritty -o 'debug.prefer_egl=true'` to work around it.

Does not change anything

**Comment by bynect** [comment]
> > intel igpu
> 
> Ensure that you're using modesetting and not `xf86-video-intel`.

This was actually the problem. but , why does alacritty not work correctly with xf86-intel-driver?

**Comment by kchibisov** [comment]
>xf86-intel-driver

because the driver is broken in multiple ways for any new hardware since it's xorg.

**Comment by bynect** [comment]
> > xf86-intel-driver
> 
> because the driver is broken in multiple ways for any new hardware since it's xorg.

That's quite sad.

well, since I resolved by changing drivers I guess I can close the issue

**Comment by kchibisov** [comment]
I'm not sure why you need it anyway, most wikis say that you don't need it. The default should be modesetting, or you just use Wayland and thing just works.

**Comment by bynect** [comment]
The default for me was intel. I thought that a specific driver could somehow be better than a generic one but I guess not.
