### ISSUE TITLE
[Arch Linux] Can't resize alacritty

### ISSUE THREAD

**Issue by gorentbarak** [alacritty/alacritty#7299]
Hello! I can't resize Alacritty using `decorations: "none"`. I'm using `picom` and KDE Plasma. Is there any way to resize my window?

Not an edit: I can right-click on the Alacritty icon and click More and then Resize. I'm not going to be able to do this every time I resize a window. Also, I'm able to move my window use `Super` + `move it around`. I'd like to be able to do something like this.

### System

OS: Arch Linux
Version: alacritty 0.12.3 (5efb0690)
Linux/BSD: Picom and KDE Plasma

### Programming information

Favorite Language: Rust

**Comment by kchibisov** [comment]
When you disable decorations your WM is responsible to somehow handle that. Usually you have `Win + RMB-drag` to resize in such cases.

**Comment by gorentbarak** [comment]
That worked! Thanks.
