### ISSUE TITLE
Split terminal view in two-page layout

### ISSUE THREAD

**Issue by bphd** [alacritty/alacritty#7302]
```markdown
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

**OS:** Linux
**Version:** Alacritty 0.6.0

**Linux:** X11
**Desktop Environment:** GNOME
**Window Manager:** Xfwm4

### Logs

**Crashes:** No crashes observed.
**Font/Terminal size:** 
```bash
alacritty -vv
```

**Keyboard and bindings:** 
```bash
alacritty --print-events
```

### Bug Description

I have encountered a bug where Alacritty occasionally fails to start when opened from the terminal. When I run the `alacritty` command, I expect the terminal emulator to launch as it normally does. However, in some cases, I receive an error message, and Alacritty doesn't start. This behavior is intermittent and doesn't happen every time.

I would appreciate any assistance in diagnosing and resolving this issue. Please let me know if you need additional information or logs to investigate this problem further.
```

In the above template, you provide information about your system, logs, and a clear description of the bug you're encountering. This information can help developers diagnose and fix the issue more effectively.

**Comment by bphd** [comment]
@chrisduerr Please re-open, it's supposed to have enough details, it's about split terminal view in two-page layout. Like it would be great for tiny screen to see the output on two-page layout, like two pages side by side, to we can see more on one screen. Because otherwise the screen have to be in portrait to display all its length

**Comment by kchibisov** [comment]
You provided zero information on what error is or shared any logs for that error. We can't guess what error you get based on zero logs.

**Comment by kchibisov** [comment]
>I have encountered a bug where Alacritty occasionally fails to start when opened from the terminal. When I run the alacritty command

Yeah, so it seems like you AI generated your issue, so no one bothered to read what you wanted.

Also, window manager features are out of scope.

**Comment by bphd** [comment]
> > I have encountered a bug where Alacritty occasionally fails to start when opened from the terminal. When I run the alacritty command
> 
> Yeah, so it seems like you AI generated your issue, so no one bothered to read what you wanted.
> 
> Also, window manager features are out of scope.

It's not a WM feature. It's terminal feature that can be offered through a "splitted output" option for example

**Comment by nixpulvis** [comment]
My head hurts.

**Comment by bphd** [comment]
> My head hurts.

Create a two-page layout for splitting the terminal view. This layout is especially useful for small screens, allowing you to display output in a side-by-side format, effectively showing more information on a single screen. To implement this feature, you need to use a pager and organize the content into panes that share the same scrollback. This means that you can view the same content in multiple panes, each with a slight offset, creating a unified scrollback experience. 

Think of it as having one terminal output or shell session displayed on a two-page view, maximizing your screen real estate. This feature is similar to the way tools like 'tail,' 'multitail,' 'pr,' 'subl,' 'emacs,' 'vim,' 'screen,' and 'tcvt' offer a two-column layout for output. Essentially, it splits the view of a single terminal into two panes, allowing them to share the same scrollback.

Imagine it like an old mechanical TTY printer, where text is printed from top to bottom. With this feature, you can have two TTY-like views side by side, where the left one displays lines from 1 to 20 and the right one displays lines from 20 to 40. This allows you to see the same output, but more of it, because it's printed on two pages or in two columns.

This functionality automatically adapts one-dimensional data into columns or rows, depending on the screen properties and view size. It essentially puts two consecutively printed pages side by side, enhancing your terminal experience. You can enable this feature through an option called "split output" in the terminal settings.
