### ISSUE TITLE
Window has minimum height, but no minimum width

### ISSUE THREAD

**Issue by clarfonthey** [alacritty/alacritty#7308]
Effectively, the terminal window is always at least one line high, but there's no limit on how thin the window can be, resulting in the ability to create weird cases like this:

![window shrunken to two pixels wide on GNOME](https://github.com/alacritty/alacritty/assets/15850505/71bca676-8293-43e5-a642-33f0231be6c4)

How I encountered this: GNOME supports holding shift when resizing windows to create a pseudo-tiled setup, so that it "snaps" to the width that leaves no gaps between windows. However, when resizing in the wrong direction, you can accidentally make a thin window like this, which shouldn't happen. You can still close out of it by using the overview menu, but considering how window constraints can easily set, this feels like something that could be easily fixed by limiting the width of the window to at least one character (or maybe two, if you're feeling spicy).

### System

OS: Linux
Version: alacritty 0.12.3 (5efb0690)
Linux/BSD: Wayland (GNOME 45.0 on Arch Linux)

**Comment by kchibisov** [comment]
Could this bi considered as a feature? 


Jokes aside we could limit the window sizes to 2x1 cells, I think that's what we use actually...

**Comment by clarfonthey** [comment]
I'd be on board with 2x1 since that's effectively the maximum size of a single character (I think?).

I mean, at least for now, alacritty treats ﷽ as being actually only one space, and that's the longest character you could possibly have, so, yeah.

**Comment by chrisduerr** [comment]
This is not an issue. Unless Alacritty actually crashes or runs into an error, there's no reason to limit the minimum size.

If you want to restrict windows from going below a certain size for window management purposes, this can be set inside sensible window managers directly.

**Comment by clarfonthey** [comment]
…except it does limit the minimum size, for height. Why should width be treated any differently?

**Comment by clarfonthey** [comment]
I guess I was mislead into thinking that the vertical size is limited purely to one line + padding since that's what I got on GNOME, but that's purely a coincidence, and changing the font size/padding has no effect for me, and it just happens to line up with GNOME's default minimum width.

Still, I think that closing the issue immediately as "this is not an issue" is incredibly hostile and rude, even though I understand that it's an extremely low-priority issue. The only reason I didn't do it myself is because I didn't feel like doing it right now, and thought maybe someone else might. I tend to open issues like this often, where I'll point out this tiny feature, then later when I'm feeling like doing it I might get to it myself. The same way most folks deal with open-source stuff.

Right now, alacritty even supports the relatively niche "resize increments" API on MacOS (offered by winit), so, why couldn't it just implement window constraints, which are supported by all common windowing systems? No need to slam the door in my face.

Since I felt fueled by spite, I actually looked into this some more and winit does have an open issue about window constraints, so, it wouldn't actually be possible until that were fixed: https://github.com/rust-windowing/winit/issues/584

But again, that's a blocked issue, not a "fuck you, won't fix" issue. This kind of hostility is what kicks people out of software entirely so it kinda seems like something you (chrisduerr) need to work on.

**Comment by kchibisov** [comment]
>Right now, alacritty even supports the relatively niche "resize increments" API on MacOS (offered by winit), so, why couldn't it just implement window constraints, which are supported by all common windowing systems? No need to slam the door in my face.

Maybe you don't know that, but that's a default resizing behavior for many terminals. You can't set something like that in wm, unlike constraints. Most window managers disallow resizing past certain values, but it's not gnome.

>But again, that's a blocked issue, not a "fuck you, won't fix" issue. This kind of hostility is what kicks people out of software entirely so it kinda seems like something you (chrisduerr) need to work on.

The issue you've linked has nothing to do with the feature you want. You just need to call `Window::set_min_inner_size` on the alacritty window. All available for years, and we all aware by that API.

**Comment by clarfonthey** [comment]
Right, it's a common feature, but as far as winit is concerned, it's not implemented for basically everything but MacOS, and the docs even describe it as niche.

As far as that issue goes -- I swore I looked through the docs well enough, but I guess not. I couldn't find the relevant method so I thought it was just unimplemented, but you're right that it's actually available right now. So, that doubles my argument that it's not an unreasonable ask, since minimum size constraints are *also* a very common feature for UIs.

**Comment by kchibisov** [comment]
>Right, it's a common feature, but as far as winit is concerned, it's not implemented for basically everything but MacOS, and the docs even describe it as niche.

It's, for X11. Could do for Wayland as well, most terminals I know do that by default.

>As far as that issue goes -- I swore I looked through the docs well enough, but I guess not. I couldn't find the relevant method so I thought it was just unimplemented, but you're right that it's actually available right now. So, that doubles my argument that it's not an unreasonable ask, since minimum size constraints are also a very common feature for UIs.

Yes, but only gnome doesn't limit anything and we don't limit anything because we can render at any size. Though, winit limits the size to 2x1 pixels, because gnome doesn't like 0x0 windows iirc.

Most compositors do limit to something reasonable though, I think only gnome doesn't.

**Comment by chrisduerr** [comment]
> This kind of hostility is what kicks people out of software entirely so it kinda seems like something you (chrisduerr) need to work on.

I literally could not care any less. If you get your feelings hurt over your issue getting closed, that's your problem not mine.

This is a non-feature that just prevents people from doing something that works perfectly fine in any sensible window manager. There is no reason to limit the minimum size.

**Comment by clarfonthey** [comment]
Again, that kind of hostility is exactly what I'm talking about. It's not about my feelings being hurt (which, they're genuinely not), it's about being an utter prick to random people who show up trying to help. If anything, it comes off as your own feelings being hurt, since you cared so strongly about this that you decided to take action on it.

I'm not gonna keep arguing with you since you clearly aren't going to change your mind. But that mindset is exactly what labels you as a terrible person to work with, and the result is people will decide to fuck off instead of dealing with you. (Like I plan to.) So, I advise you to look inwards, or suffer the consequences of your actions.

**Comment by chrisduerr** [comment]
> But that mindset is exactly what labels you as a terrible person to work with, and the result is people will decide to fuck off instead of dealing with you. (Like I plan to.)

Which is exactly the goal.

**Comment by clarfonthey** [comment]
To tank your reputation and have everyone hate you? Let me know how that works out.

**Comment by nixpulvis** [comment]
> If you want to restrict windows from going below a certain size for window management purposes, this can be set inside sensible window managers directly.

Problem is, this isn't actually true. The window manager should have no knowledge of the minimum sizes that an application should be allowed to be. The application, in this case Alacritty, knows the size of the text and should be the one to decide what makes sense. Why else would [`set_min_inner_size`](https://docs.rs/winit/latest/winit/window/struct.Window.html#method.set_min_inner_size) be a feature at all?

Now if we don't care about clipping off text, then so be it. I personally don't care a lot. There's some utility to being able to collapse the window past generally sensible limits. But there's also a case to be made for presenting a legible character at least.

**Comment by kchibisov** [comment]
alacritty can render at any size without any issues what so ever, it's more like "why should we limit users to do what they want as long as it doesn't break alacritty"?

**Comment by nixpulvis** [comment]
It's a question of usability.

There's generally a question of limiting users to protect themselves vs. giving users the full power of an application. As I understand it, we generally err on the side of giving users more control.

**Comment by kchibisov** [comment]
I know only gnome who allows to resize to any size the window wants, most other compositors do actually limit things. If GNOME thinks that it shouldn't limit, why we should think that we should limit?

**Comment by nixpulvis** [comment]
Often an application will limit it's size because it knows what it's rendering and wants to ensure that some content isn't clipped. For example, we could limit the size of the window to a single character. Again, just playing devil's advocate, I don't actually care what we do here.

**Comment by chrisduerr** [comment]
> Problem is, this isn't actually true. The window manager should have no knowledge of the minimum sizes that an application should be allowed to be. The application, in this case Alacritty, knows the size of the text and should be the one to decide what makes sense.

That's exactly why I don't want this. Alacritty works just fine at a size of 0x0. At that point the biggest issue becomes usability for window management because suddenly you can't grab the window anymore and things like that. That's why most window managers also have options for a minimum size in general, because it's what **their** constraints are before a window isn't really usable anymore.
