### ISSUE TITLE
When your login shell is zsh, Alacritty runs .zshenv twice

### ISSUE THREAD

**Issue by mok0** [alacritty/alacritty#7315]
### System

OS: macOS
Version: `alacritty 0.12.3 (5efb069)

Subject says it: When your login shell is zsh, Alacritty runs `.zshenv` twice.

**Comment by kchibisov** [comment]
we have nothing to do with what you're running inside of alacritty, and we don't source anything.

It's all up to zsh and your scripts.

**Comment by mok0** [comment]
It doesn't happen with any other terminal emulator. I have tried iTerm, Apple Terminal, WezTerm, Kitty.

**Comment by nixpulvis** [comment]
@mok0 what's in your Alacritty config?

**Comment by mok0** [comment]
Here it is, I have nothing out of the ordinary. I've filtered out comments. Github's web interface does not allow upload of yaml files to I've changed the type to txt.
[alacritty.txt](https://github.com/alacritty/alacritty/files/13193293/alacritty.txt)
