### ISSUE TITLE
Can't run the installed app on the mac

### ISSUE THREAD

**Issue by letsandeepio** [alacritty/alacritty#7316]
Cannot run the app on mac because apple can't check it for malicious software.

**Comment by kchibisov** [comment]
sad. Maybe you need to self sign.

**Comment by letsandeepio** [comment]
Well, that's not super encouraging for a user who is trying to switch to the alacrity! well I'll pass this time thanks for your response though !

**Comment by kchibisov** [comment]
Well, paying apple is not an option, so we have what we have.

**Comment by letsandeepio** [comment]
Understandable, thanks for clarifying - I'll fiddle with self-signing.

**Comment by kchibisov** [comment]
https://github.com/alacritty/alacritty/blob/master/Makefile#L59

Our `make app` should probably do the right thing. I'm not familiar with what apple really wants for this checking though.
