### ISSUE TITLE
alacritty vi mode select mode it  select have break off

### ISSUE THREAD

**Issue by newyorkthink** [alacritty/alacritty#7318]
![image](https://github.com/alacritty/alacritty/assets/87791643/cb8c0e91-f3ee-4bb1-a184-32f1e0c1d0c8)
when i select here
and keep go
![image](https://github.com/alacritty/alacritty/assets/87791643/84134d98-2700-4ea8-80ea-2b4324105d34)
the recent select is ignore

**Comment by chrisduerr** [comment]
Could you try describing the issue again, but this time using actual sentences?

**Comment by newyorkthink** [comment]
> Could you try describing the issue again, but this time using actual sentences?

look like this
this is eg sentence:
```
sudo v2raya -c .config/v2raya --v2ray-assetsdir .local/share/v2ray -b v2ray
```

first i ctrl+c in alacritty vi mode, is ok
second the target in sudo "s" 
![image](https://github.com/alacritty/alacritty/assets/87791643/912367e5-069e-46b6-b016-2a0beeed0a8f)

i start select in sudo s

and i use keyboard 'w' select 
![image](https://github.com/alacritty/alacritty/assets/87791643/a203987a-28e9-4792-b969-7cd393292f89)

and this situation, sometime have ,when I select half sentences
![image](https://github.com/alacritty/alacritty/assets/87791643/fc492751-e813-46b0-9b2f-81b010fca149)

i select zone is  auto ignore

**Comment by newyorkthink** [comment]
os:i3wm

**Comment by chrisduerr** [comment]
Cannot reproduce and have no interest in trying to figure out what you actually mean.
