### ISSUE TITLE
Reset causes "Terminal type?" question instead of just reset

### ISSUE THREAD

**Issue by ell1e** [alacritty/alacritty#7320]
The "reset" tool as found on this distribution and how it's prompted inside alacritty asks me a question instead of resetting:
```
$ reset
reset: unknown terminal type alacritty
Terminal type?
```
If I enter `xterm` and press enter it works, but it's very cumbersome. I get this might be an issue with whatever this reset thing comes from, I'm happy to forward the bug if you let me know where. Alternatively, maybe alacritty could somehow bypass reset and do "the right thing"?

### System

OS: openSUSE Leap 15.5
Version: not sure, the one baked into [lapce](https://github.com/lapce/lapce)'s nightly
Linux/BSD: gnome-shell wayland session

**Comment by kchibisov** [comment]
you need to install the alacritty terminfo. it's present in some ncurses package, likely the one having terminfo in its name.

**Comment by ell1e** [comment]
Ah, thanks so much! I wonder, if I get that issue in the lapce flatpak, is that potentially a flatpak packaging issue? I'll ask the lapce folks about it
