### ISSUE TITLE
Visual bell animation on Mac is really long

### ISSUE THREAD

**Issue by sfsam** [alacritty/alacritty#7325]
On macOS, the visual bell animation lasts for around 1 second regardless of what non-zero duration is in the config file. This seems to be the case since commit 80d4daccc307622f8e604af4f36ac89ecccf5db7.

Before that commit, visual bell animation worked fine.

**Comment by chrisduerr** [comment]
What if you have something like `yes` running?

**Comment by sfsam** [comment]
Sorry, I don't understand the question.

Here are 2 videos of the visual bell in action. The first video is commit 6071a7bf35cfd99be8ba70f479f188b7370cda6f which shows the bell working properly. The down arrow was pressed 3 times triggering 3 brief red flashes:

https://github.com/alacritty/alacritty/assets/118104/4e87f92f-c9d2-46c9-8fc9-2be7693037f7

The second video is the next commit, 80d4daccc307622f8e604af4f36ac89ecccf5db7, which shows the bug. The down arrow was again pressed 3 times triggering 3 long flashes:

https://github.com/alacritty/alacritty/assets/118104/2f092c0d-6391-4a63-974e-69582b840320

The visual bell is configured as:
```
[bell]
color = "#ff1c1c"
duration = 100
```

**Comment by chrisduerr** [comment]
Now run yes while/immediately after flashing the bell.

**Comment by sfsam** [comment]
I ran yes immediately after pressing the down arrow to trigger the bell. The yes command ran immediately, interrupting the prolonged red flash animation.

**Comment by chrisduerr** [comment]
Don't just type it manually. Does the animation play properly then?

**Comment by sfsam** [comment]
Again, I don't follow. How do I run yes if I don't first type it manually? What I had done was type "yes" at the prompt, then hit down-arrow to trigger the prolonged flash, then immediately hit return to execute yes. The yes command interrupted the prolonged flash.

**Comment by nixpulvis** [comment]
I tested this yesterday on macOS 14.0 and also noticed an issue, though it wasn't just hanging around for a second. The visual bell seemed to freeze on screen until another event caused a `RedrawRequested`.

Also noticed that the animation may be a bit choppier than it could be.
