### ISSUE TITLE
Dynamically switch between beam and block cursor

### ISSUE THREAD

**Issue by ErynGalen** [alacritty/alacritty#7326]
In vim, the cursor shape is different between insert mode (beam cursor) and normal mode (block cursor)
Zsh on kitty has a similar behaviour: when enabling vi keybindings (via `bindkey -v`), the cursor has a beam shape when typing commands and takes a block shape when entering vi mode.

Is such a behaviour (dynamic cursor shape with zsh) possible on Alacritty?

**Comment by kchibisov** [comment]
yes, setup it all in your zsh, it's just all using the standard escape sequences to manipulate cursor shape.
