### ISSUE TITLE
alacritty is not properly working in tabbed

### ISSUE THREAD

**Issue by beelze** [alacritty/alacritty#7331]
`tabbed -c alacritty --embed`
Alacritty "not responds" to keypresses when tabbed (exactly like keys aren't pressed), but mouse is working (selection/copy/hints).

Versions: alacritty 0.12.3, tabbed 0.7 (0.6 has same behaviour), Linux

`tabbed` itself is functional (tested with xterm). I've tried to compare alacritty logs (tabbed and non-tabbed) but failed to find anything relevant:
[Alacritty.log](https://github.com/alacritty/alacritty/files/13199094/Alacritty.log)
[Alacritty-embed.log](https://github.com/alacritty/alacritty/files/13199095/Alacritty-embed.log)
(in both cases I just typed `123` and Alt-F4 to close)

upd: there is a small difference if alacritty embedded "separately" (run `tabbed`, then `alacritty --embed $XID`): when key is pressed, cursor changes from beam shape (as defined in config) to "cell" (rectangular) shape. This is **not** happening if using `tabbed -c alacritty --embed`

**Comment by beelze** [comment]
upd1: This is **not** a "redraw" problem. Seems the shell process don't receive input from `alacritty`. 
`alacritty --embed 0x8c00003 -e /bin/bash -c read` cannot be closed by pressing `Return`.

**Comment by chrisduerr** [comment]
Can you try master?

**Comment by beelze** [comment]
`alacritty 0.13.0-dev (a0663c52)` issue exactly the same

**Comment by chrisduerr** [comment]
Works just fine for me, which WM are you using?

**Comment by beelze** [comment]
```
% cinnamon --version
Cinnamon 5.8.4
% muffin --version
mutter 5.8.1
```

**Comment by chrisduerr** [comment]
Can you try a different WM?

**Comment by beelze** [comment]
seems [it is not possible](https://github.com/linuxmint/Cinnamon/issues/4895#issuecomment-160687406)
I can install something like Mint/Cinnamon and Mint/Mate just to be sure who is to blame. Or do you have any other ideas?

**Comment by nixpulvis** [comment]
Would be better to test outside of VirtualBox. Generally, you can swap out your WM by changing the way your login manager or desktop environment gets invoked. Since cinnamon seems like it's doing everything, you may have to rewire it at a lower level than you are comfortable with. As I understand things, it should be possible to tell Mint Linux to load another DE/WM, however I can't really help you with that myself.

**Comment by chrisduerr** [comment]
i3 with picom works just fine.

**Comment by beelze** [comment]
Calculate Linux (gentoo-based) Desktop Cinnamon works fine too. At least inside VirtualBox, he-he... It was a fastest test.
Though, it is Cinnamon 5.6.5 / muffin 5.6.2. 
To be continued..

**Comment by beelze** [comment]
Sorry, the problem had gone after rebooting (cinnamon restarting didn't help) and my suspicions leans toward nvidia-drivers.
Closing as invalid at least before I will be able to reproduce the issue.

**Comment by beelze** [comment]
Right now, when I worked in alacritty, it suddenly stopped react to keypresses. All the symptoms I described above, happened again (only tabbed alacritty was affected). The problem has disappeared only after **full** WM/DE restart (I've restarted lightdm).

Any troubleshooting ideas are welcome.

**Comment by chrisduerr** [comment]
And other terminals work just fine, correct? Also are you starting new Alacritty windows, or processes?

I'd assume the logs you've posted in the initial issue comment are identical to what you're experiencing now? These suggest that Alacritty is receiving the key events, but it is not the target of those events (instead they're sent to a different application).

**Comment by beelze** [comment]
> And other terminals work just fine, correct?

Yes, seems everything except alacritty works fine

> …new Alacritty windows, or processes?

AFAIK `tabbed` just repeats invoking its arguments when creating new tab, so I believe the answer is __processes__

>  …identical to what you're experiencing now?

yes

> … Alacritty is receiving the key events, but it is not the target of those events

How can I debug the target of received messages? 

… I should mention that last time __existing__ tabbed alacritty process had stopped responding to keypresses – the same way as all tabbed alacritty processes invoked after that.

Another thought – how only keyboard events may be wrongly destined while mouse aren't?

**Comment by chrisduerr** [comment]
> AFAIK tabbed just repeats invoking its arguments when creating new tab, so I believe the answer is processes

Could you make sure to try spawning Alacritty separately with the `--embed` option?

Also just to be 100% clear: Killing all Alacritty and tabbed instances is not enough, right? You **must** restart the WM?

And Alacritty instances outside of tabbed still work just fine after not being able to use tabbed anymore?

> How can I debug the target of received messages?

I'm not sure you can.

**Comment by kchibisov** [comment]
`xtrace` or `x11trace`

**Comment by beelze** [comment]
I've updated nvidia-drivers few hours ago (because there were some glitches – rare and minor but recurring). At the moment alacritty works fine and I'm keeping an eye on it.

> Could you make sure to try spawning Alacritty separately with the --embed option?

Yes, tabbed surely spawns new process for every tab. But to my big surprise, when I checked a processes, I've found 2 orphaned `alacritty --embed 109051907` processes (no errors in their logs, no tabbed processes as they were all closed at that moment, no any issues). Since I never invoked alacritty separately this time, it may be a bug – though it needs further investigation.

> Alacritty instances outside of tabbed still work just fine

Non-tabbed instances __always__ work fine, only tabbed instances are affected by issue

**Comment by beelze** [comment]
> You must restart the WM?

Yes, the only way I found to fix a problem (except reboot) is a **full** WM restart (`cinnamon --replace` which preserves windows and processes wasn't enough)

**Comment by beelze** [comment]
upd: 
1. orphaned alacritty processes is a `tabbed ` bug (same with xterm). For some unknown reason `tabbed` closes only every other client (1st, 3rd , 5th etc). Seems this is not related to the issue.
2. Right now embedded alacritty stopped working again. I can run any suggested tests.

**Comment by kchibisov** [comment]
Maybe your WM just breaks with tabbed, since not seeing events could mean that no-one bothered to send them.

**Comment by beelze** [comment]
> Maybe your WM just breaks with tabbed, since not seeing events could mean that no-one bothered to send them.

`xterm` works fine inside `tabbed`, only `alacritty` affected

**Comment by beelze** [comment]
Interesting thing I've just noticed, I put all together:
1. `tabbed -c alacritty --embed` – has an issue
2. `tabbed; alacritty --embed $xid` – has an issue
3. `tabbed -c xterm -into` – works fine
4. `tabbed; xterm -into $xid` – **also has an issue!**

... more, soon after I caught issue with `xterm`, it stops working even when **not** tabbed. The most funny part is that `xterm` worked fine at first, then stop working after 1st keypress (I could type only one char) and, at last, stopped working at all.

and more, I've caught interesting warning when running cinnamon in terminal:
```
Window manager warning: Window 0x3000003 has property _NET_WM_NAME
that was expected to have type UTF8_STRING format 8
and actually has type COMPOUND_TEXT format 8 n_items 0.
This is most likely an application bug, not a window manager bug.
The window has title="tabbed-0.7 :: xterm -into 50331651" class="tabbed" name="tabbed"
```

About `orphaned` alacritty instances: it was `tabbed` bug, though I could easily fix it.
Summing all things up, seems that `tabbed` is the first candidate to investigate. 

Saying it again, just to clarify things – the was no issues like this (at all) before `tabbed`.

**Comment by chrisduerr** [comment]
Considering that Alacritty doesn't really do anything special for `tabbed` to work, I think it's most likely a WM issue.

**Comment by beelze** [comment]
As for me – it is obviously not an `alacritty` issue but there is no any evidences that `cinnamon` doing something wrong. On the other side, `tabbed` code is buggy and obsolete in some places (I already fixed 2 bugs as for now) and should not been advised for `tabbing` anything – until it's code is revised.
