### ISSUE TITLE
daemon mode.

### ISSUE THREAD

**Issue by aabbccddeeffggj** [alacritty/alacritty#7348]
Hi, I see contributors talking about the existence of a daemon mode for alacritty, but I have no idea of how to set it, I found no documentation for such thing.
If anyone could lead me to the way of how I can enable this daemon I would appreciate.

**Comment by chrisduerr** [comment]
Assuming you're on unix, you can spawn all Alacritty windows from a single instance using the following:

```sh
alacritty msg create-window || alacritty
```
