### ISSUE TITLE
Can't close Alacritty from app switcher on macOS

### ISSUE THREAD

**Issue by wayneashleyberry** [alacritty/alacritty#735]
The `⌘ + ⇥` app switcher on macOS allows you to close apps by pressing `q` while hovering over them. This behaviour doesn't seem to be supported by Alacritty.

Quick screen capture here: https://youtu.be/LLV66RVb9u8

**Comment by gmile** [comment]
Must be related to https://github.com/jwilm/alacritty/issues/675
