### ISSUE TITLE
OpenType Contextual Alternates support

### ISSUE THREAD

**Issue by gempir** [alacritty/alacritty#7352]
Github released a very good font family https://monaspace.githubnext.com/ named Monaspace.

It makes use of an OpenType feature named "contextual alternates"
I assume this relates to #50 but it's not the same I think. Monaspace also makes use of ligatures but that feature should probably be discussed in #50 

Currently I cannot even use the font in alacritty after installing it on macOS.

Would be amazing if alacritty could support this.

### System

OS: macOS 14.1
Version:  0.12.2 (9d9982d)

**Comment by chrisduerr** [comment]
#50
