### ISSUE TITLE
0.12.3 closes on open?

### ISSUE THREAD

**Issue by multivac61** [alacritty/alacritty#7359]
Downloading a fresh .dmg from `GitHub Releases` briefly opens an Alacritty window and then closes it straight away

![CleanShot 2023-11-12 at 10 20 13@2x](https://github.com/alacritty/alacritty/assets/4436129/cd190a00-5597-49b7-8504-6176810288a5)

### System

OS: macOS
Version: `alacritty 0.12.3 (5efb069)`

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

![CleanShot 2023-11-12 at 10 22 40@2x](https://github.com/alacritty/alacritty/assets/4436129/0cf8d664-ced6-4ab9-992b-eb61d41f302b)

**Comment by kchibisov** [comment]
looks like shell in your config is broken and just exits. because `--config-file /dev/null` should work based on that log. you can also pass `--hold` to stick.
