### ISSUE TITLE
Manual-page and updating alacritty

### ISSUE THREAD

**Issue by gldtn** [alacritty/alacritty#7361]
I managed to build alacritty on macOS sonoma with no problems, well for some reason the man pages is not working even after following the https://github.com/alacritty/alacritty/blob/master/INSTALL.md#manual-page

```
sudo mkdir -p /usr/local/share/man/man1
sudo mkdir -p /usr/local/share/man/man5
scdoc < extra/man/alacritty.1.scd | gzip -c | sudo tee /usr/local/share/man/man1/alacritty.1.gz > /dev/null
scdoc < extra/man/alacritty-msg.1.scd | gzip -c | sudo tee /usr/local/share/man/man1/alacritty-msg.1.gz > /dev/null
scdoc < extra/man/alacritty.5.scd | gzip -c | sudo tee /usr/local/share/man/man5/alacritty.5.gz > /dev/null
scdoc < extra/man/alacritty-bindings.5.scd | gzip -c | sudo tee /usr/local/share/man/man5/alacritty-bindings.5.gz > /dev/null
```

I see the files:
```
ls /usr/local/share/man/man1
alacritty-msg.1.gz  alacritty.1.gz

ls /usr/local/share/man/man5
alacritty-bindings.5.gz  alacritty.5.gz
```

but I get:
```
man alacritty
No manual entry for alacritty
```

### EDIT: After running: `man -d alacritty` I got the man pages to work

**My other question is, how do I update alacritty using the manual installation? Do I need to run the following?**:
```
git pull
make app
cp -r target/release/osx/Alacritty.app /Applications/
```

Thanks in advance!

**Comment by kchibisov** [comment]
>My other question is, how do I update alacritty using the manual installation? Do I need to run the following?:

pretty much. and then take the man pages yourself out of `app`.

I think homebrew installs man pages, so you can sort of get inspiration from it.
