### ISSUE TITLE
Multiple Lines error

### ISSUE THREAD

**Issue by DerPandaa1** [alacritty/alacritty#7364]
I have a strange behavior when the text is too long. It just overwrite the current line when i write too much.
I attached my config (it is config.txt. I cant attach yml files) and a gif where it shows my bug

### System

OS: Arch Linux Kernel: 6.5.9-arch2-1
Version: alacritty 0.12.3 (5efb0690)
Linux/BSD: X11 (21.1.9) 

[config.txt](https://github.com/alacritty/alacritty/files/13339424/config.txt)
![alacritty_bug](https://github.com/alacritty/alacritty/assets/83124510/6517eed0-04d7-4b29-aa13-090d6f6d8b2a)

**Comment by kchibisov** [comment]
Looks like your shell is bugged? Could you attach `-vvv` or repro without your shell config?

**Comment by DerPandaa1** [comment]
An error in the shell config with the PS1. I still don't understand why it worked on terminator and xterm

**Comment by DerPandaa1** [comment]
For repro i found PS1="\e[0;34m\u@\h \w> \e[m" is not working for example

**Comment by kchibisov** [comment]
I mean, it's a PS1/bash issue, it's the same broken in any other terminal.
