### ISSUE TITLE
Umlaut ü not rendered correctly

### ISSUE THREAD

**Issue by tfeldmann** [alacritty/alacritty#7369]
There seems to be a rendering problem with Umlauts or I am absolutely missing something.
It's about the "... für Mietliste" file where the `ü` is rendered incorrectly in alacritty.
I tried recreating this problem with the file named `ÜÄÖüäöß` but couldn't. The other file comes from a windows system, maybe that's the reason?

alacritty:
<img width="361" alt="Bildschirmfoto 2023-11-14 um 22 43 44" src="https://github.com/alacritty/alacritty/assets/385566/f6aa6600-da24-4877-886b-a6db5be05108">

Terminal.app:
<img width="397" alt="Bildschirmfoto 2023-11-14 um 22 43 55" src="https://github.com/alacritty/alacritty/assets/385566/eda4620b-9fc1-447b-9693-a7fa648edea8">

### System

OS: macOS Sonoma 14.1.1
Version: `alacritty 0.12.3 (5efb069)`
Font: Tested with both Fira Code and Source Code Pro

**Comment by kchibisov** [comment]
We don't normalize the text, if you use the glyph without umlaut attached to them they could be placed like that.

**Comment by kchibisov** [comment]
I'd also suggest to try `Fira Mono` and not `Fira Code`.

**Comment by tfeldmann** [comment]
Thanks, good to know!
