### ISSUE TITLE
The window border lost

### ISSUE THREAD

**Issue by hiql** [alacritty/alacritty#7374]
The right bottom corner looks weird, the window border  lost

### System

OS: macOS Sonoma

### Screenshots

<img width="778" alt="截屏2023-11-16 15 00 12" src="https://github.com/alacritty/alacritty/assets/17871109/b6dc9cde-2331-4472-871b-1f9655b881e3">

**Comment by kchibisov** [comment]
We don't touch border or round anything in any way. Seems like macOS bug.

**Comment by vuon9** [comment]
The border lost if I have `window.opacity` config, turn it off can bring back the border.

**Comment by hiql** [comment]
<img width="1139" alt="截屏2023-12-22 20 05 46" src="https://github.com/alacritty/alacritty/assets/17871109/d5fb3b04-86ea-4d63-9be2-7efac54924a5">

MacOS Sonoma
Turn on state manager
