### ISSUE TITLE
What happened in my sign column?

### ISSUE THREAD

**Issue by bty102** [alacritty/alacritty#7376]
![Screenshot 2023-11-17 110316](https://github.com/alacritty/alacritty/assets/125985488/daa41786-0ca4-434f-9942-6479a865e20b)
I'm using neovim 0.9.2 on windows os

**Comment by kchibisov** [comment]
missing glyph in font? However if it was box drawing character (lines), it's a conpty bug.

**Comment by bty102** [comment]
What should I do to fix bug???
Why close?

**Comment by kchibisov** [comment]
Ensure that the glyph is present in your font? Alacritty just renders characters it's getting. Windows itself could also _break_ some characters because of bugs in ConPty.
