### ISSUE TITLE
no longer able to resize alacritty window

### ISSUE THREAD

**Issue by andyczerwonka** [alacritty/alacritty#7377]
I'm not sure this is related to Alacritty OR NOT, but I updated to a recent build and now it is very difficult to resize the terminal window. This is new behavior and I don't quite know if it's related to a recent os changes elsewhere or because I updated my version of Alacritty.

### System

OS: Linux
Version: `alacritty 0.13.0-dev (d83d5af2)` 
Linux/BSD: Wayland, Mutter

```
[0.000001093s] [INFO ] [alacritty] Welcome to Alacritty
[0.000092546s] [INFO ] [alacritty] Version 0.13.0-dev (d83d5af2)
[0.000101200s] [INFO ] [alacritty] Running on Wayland
[0.000475675s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/aczerwon/.config/alacritty/alacritty.toml"
[0.282348906s] [INFO ] [alacritty] Using EGL 1.5
[0.315138410s] [INFO ] [alacritty] Window scale factor: 1
[0.328862643s] [INFO ] [alacritty] Running on Mesa Intel(R) Graphics (RPL-S)
[0.328879618s] [INFO ] [alacritty] OpenGL version 4.6 (Core Profile) Mesa 23.2.1-1pop0~1699535617~22.04~6cd9a72~dev, shader_version 4.60
[0.328885038s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.338096740s] [INFO ] [alacritty] Cell size: 9 x 19
[0.338113744s] [INFO ] [alacritty] Padding: 5 x 5
[0.338117200s] [INFO ] [alacritty] Width: 1090, Height: 580
[0.338137208s] [INFO ] [alacritty] PTY dimensions: 30 x 120
[0.340336970s] [INFO ] [alacritty] Initialisation complete
[0.341720510s] [INFO ] [alacritty] Padding: 5 x 5
[0.341729865s] [INFO ] [alacritty] Width: 800, Height: 600
[0.357425306s] [INFO ] [alacritty] Padding: 5 x 5
[0.357452110s] [INFO ] [alacritty] Width: 1090, Height: 580
```

**Comment by andyczerwonka** [comment]
I noticed https://github.com/alacritty/alacritty/issues/97, which suggests that I don't need to unset the WAYLAND_DISPLAY - is that the case?

**Comment by kchibisov** [comment]
Do you have decorations set to `None`?

**Comment by andyczerwonka** [comment]
@kchibisov No, it's set to `full`. I do have what looks to be 1 pixel of a border that I can grab if I get it just right, but the title bar is different then all other windows. iFf I do turn off the `WAYLAND_DISPLAY` environment variable, I get a very large window and I can then grab an edge.

**Comment by kchibisov** [comment]
Do you have plugins in gnome?

**Comment by kchibisov** [comment]
>title bar is different then all other windows.

This is expected and how GNOME expects things to look. Whether you like it or not is not what we can solve.

Alacritty draws a 1px border and a 10px invisible area around the window which you can click to resize, but some plugins could cut it, I remember that there was one doing so on GNOME.

**Comment by andyczerwonka** [comment]
> Alacritty draws a 1px border and a 10px invisible area around the window which you can click to resize, but some plugins could cut it, I remember that there was one doing so on GNOME.

@kchibisov Yeah, if that's the case, it's clearly something like that. It is strange that turning off the WAYLAND_DISPLAY environment variable fixes it (kind-of). I'm curious as to why that is.

**Comment by kchibisov** [comment]
if you unset `WAYLAND_DISPLAY` you force X11. I know that GNOME sometimes also bugs with the way we draw those borders (though, GTK4 should have the exact same issue then).

**Comment by andyczerwonka** [comment]
> if you unset WAYLAND_DISPLAY you force X11

Ah, so that's not really fixing the problem, it's a tool to ignore it. I don't really want to run X11, and in this case I can get around resizing with the keyboard, so not a showstopper. I just wanted to see if people were aware and see if there were actual knows solutions. Not sure how many people are running Wayland under Ubuntu 22.04.

**Comment by kchibisov** [comment]
The problem is not really a wayland support or anything, it's just a compositor could have a _bug_ as well. if you have weston (just for a test) available you can try alacritty under it, it should use exactly the same decorations. I know that I can't repro that in GNOME on fedora.

**Comment by kchibisov** [comment]
you can also always hold `Super` + resize with right mouse button on gnome.

**Comment by rotten** [comment]
I'm running Wayland on Ubuntu 22.04 and also lost the usual ability to resize with the latest update.  unsetting `WAYLAND_DISPLAY` doesn't do anything for me.   I can right click on the titlebar and select resize and then drag the window bigger, but that is really inconvenient.  At least I have a mechanism to work with so I can keep using Alacritty.  I agree that the previous resize functionality was pretty flaky.  (Sometimes it would work, and sometimes it took several tries and careful mouse positioning *after* it changed the cursor to get it aligned.  Sometimes the cursor would get stuck with the resizing icon.)

**Comment by kchibisov** [comment]
I'm pretty sure it's a mutter bug with your ubuntu version. The gnome/mutter 44.0/45.0 don't have this issue and I have no issues with resizing alacritty.

**Comment by rotten** [comment]
When I do a `ps -ef | grep -i mutter` on my laptop, I do appear to have something mutter related running in my process stack:
```
 /usr/bin/Xwayland :0 -rootless -noreset -accessx -core -auth /run/user/1000/.mutter-Xwaylandauth.6TVGE2 -listen 4 -listen 5 -displayfd 6 -initfd 7
```

It looks like I am running the latest supported version of mutter on Ubuntu 22.04:  version 42.9

I'm not sure that it is possible to upgrade without upgrading Ubuntu. or rebuilding a whole bunch of stuff.

**Comment by kchibisov** [comment]
Well, we what alacritty is doing is allowed by the Wayland protocol and what apparently how GTK4 also works now, so I'm not sure what to suggest other than use more modern ubuntu or use `Super + right click`.

**Comment by andyczerwonka** [comment]
@rotten If you're running Wayland on Ubuntu, you'll be running Mutter - it's the Wayland display server.

**Comment by rotten** [comment]
Thanks.  I've been using Ubuntu for about 20 years now.  I've run into a lot of problems with the interim releases and pretty much stick to the LTS ones now, at least on the systems I use professionally.  The next LTS after 22.04 is 24.04, only 6 months away.  I look forward to upgrading.   I'll dig a little into whether it is possible to upgrade mutter without a major rebuild or OS upgrade.

**Comment by kchibisov** [comment]
mutter update is just basically an entire gnome shell update and relative stuff. I'd suggest just to stick to X11 for the time being.

**Comment by kchibisov** [comment]
if the version is within the cursor theme, use the recent master build instead. ubuntu known to use non-spec compliant cursor themes by default.
