### ISSUE TITLE
version 13 using official repositories

### ISSUE THREAD

**Issue by robin-thoene** [alacritty/alacritty#7378]
Hey,

I am currently using the AUR package for alacritty, because the version delivered by pacman is not 0.13 and/or above.
I need to use 0.13 or above to be able to use the configuration of alacritty using .toml files as far as I understand.

When is a new version expected to be shipped so I can migrate to installing from the official repo?

**Comment by chrisduerr** [comment]
> When is a new version expected to be shipped so I can migrate to installing from the official repo?

When it's ready.
