### ISSUE TITLE
Unsuccessful toml migration

### ISSUE THREAD

**Issue by EdvardSire** [alacritty/alacritty#7380]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: native Ubuntu 22.04 on M1
Version: alacritty 0.13.0-dev (f8d9f5f6)
GNOME 42.9 and Mutter

I just build from source using `cargo build --release --no-default-features --features=wayland`.

Then it warned me that Alacritty has moved to toml. Then i ran `./target/release/alacritty  migrate` which gave me:

```
Created log file at "/tmp/Alacritty-11001.log"
[0.000267334s] [WARN ] [alacritty_config_derive] Unused config key: hide_cursor_when_typing
Deleted log file at "/tmp/Alacritty-11001.log"
```

Looks like it failed to parse this line the hide cursor setting.
```
hide_cursor_when_typing = true
import = ["/home/ubuntu/.config/alacritty/new_nord.toml"]
live_config_reload = true


[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "FiraCodeNerdFont"
style = "Light"
...
```

I wanted to report this, but also tried to look around for examples toml configurations. Didn't find any, what did i miss and how would i get the hide_cursor_when_typing flag working?

**Comment by chrisduerr** [comment]
https://raw.githubusercontent.com/alacritty/alacritty/master/extra/man/alacritty.5.scd

The option you're looking for is `mouse.hide_when_typing`. Or just remove it because apparently you didn't notice that it wasn't working before anyway.
