### ISSUE TITLE
Create new release to include missing man pages

### ISSUE THREAD

**Issue by pevik** [alacritty/alacritty#7383]
Could you please create new release from master branch? My motivation is to get missing man pages (`alacritty-bindings.5.scd` and `alacritty.5.scd`) released, but I'm sure there are other useful commits in master branch. Or the functionality is not yet ready, thus it cannot be released?

I was a bit confused at your branches. Commits since v0.12.0-rc1 in v0.12.3 branch (and older branches) are not in the master branch. That suggest that these branches are containing just fixes (it looks like in the commit message). But it would be less confusing, if you create just single branch `v0.12.x`. Because you tag versions, thus having also branches is redundant (and thus confusing).

**Comment by kchibisov** [comment]
>Could you please create new release from master branch? My motivation is to get missing man pages (alacritty-bindings.5.scd and alacritty.5.scd) released, but I'm sure there are other useful commits in master branch. Or the functionality is not yet ready, thus it cannot be released?

They are not missing, they are only for the master, they have no use for previous versions. The release will be when there will be a time for it. If you build master branch yourself, you should build man pages also *yourself*.

>I was a bit confused at your branches. Commits since v0.12.0-rc1 in v0.12.3 branch (and older branches) are not in the master branch. That suggest that these branches are containing just fixes (it looks like in the commit message). But it would be less confusing, if you create just single branch v0.12.x. Because you tag versions, thus having also branches is redundant (and thus confusing).

This thing we'll likely change for the next release, but it's all done according to the current policy we have, see https://github.com/alacritty/alacritty/blob/master/CONTRIBUTING.md#release-process
