### ISSUE TITLE
supports configuring multiple fonts

### ISSUE THREAD

**Issue by shenghui0779** [alacritty/alacritty#7385]
eg: 
  family: `Iosevka,'LXGW WenKai'`

**Comment by kchibisov** [comment]
Duplicate of #957

**Comment by bryanme5** [comment]
Actually I am not sure if its a duplicate or not, I mean, before alacritty yaml supported several fonts but now it only support one. When trying to specify another (for complete missing glyphs) it expects a string, not a sequence. 

Maybe I am wrong, i would appreciate if someone corrects me.

**Comment by bryanme5** [comment]
> Duplicate of #957


Actually I am not sure if its a duplicate or not, I mean, before alacritty yaml supported several fonts but now it only support one. When trying to specify another (for complete missing glyphs) it expects a string, not a sequence.

Maybe I am wrong, i would appreciate if someone corrects me.

**Comment by chrisduerr** [comment]
> before alacritty yaml supported several fonts

It never did. It just didn't complain. It always only used one font.

**Comment by Shurtu-gal** [comment]
Suppose I want to use nerd fonts while also wanting support for Japanese what should be done then?
