### ISSUE TITLE
[wayland] hidpi scale not applied

### ISSUE THREAD

**Issue by lilydjwg** [alacritty/alacritty#7399]
### System

OS: Arch Linux
Version: alacritty 0.13.0-dev (80d4dacc)
Linux/BSD: Wayland, Wayfire git, wlroots 0.17

### Description

Since 80d4daccc307622f8e604af4f36ac89ecccf5db7, alacrity won't applied hidpi scale (2) and shows a low-dpi window. It doesn't happen with older Wayfire and wlroots 0.16. Other (GTK/Qt) apps are OK.

**Comment by kchibisov** [comment]
Post `WAYLAND_DEBUG=1` log, but it's 99% a wayfire bug.

**Comment by kchibisov** [comment]
it's likely advertises `wl_compositor@v6` but then never sends `preferred_buffer_scale` event, so the scale just remains 1.

**Comment by lilydjwg** [comment]
On Wed, Nov 29, 2023 at 01:00:53AM -0800, Kirill Chibisov wrote:
> it's likely advertises ***@***.***` but then never sends `preferred_buffer_scale` event, so the scale just remains 1.

Yes...Thanks!

-- 
Best regards,
lilydjwg
