### ISSUE TITLE
Opinions on live font realoding?

### ISSUE THREAD

**Issue by liuw** [alacritty/alacritty#740]
Currently changing fonts requires restarting Alacritty.

Any opinion on the usefulness of live font reloading?

I personally find it useful. If people like that idea I might be able to find some time to do it. (Though currently I have no idea how hard or easy it is going to be)

**Comment by jwilm** [comment]
This will definitely be added at some point. Want to land #689 and #625 first. There may actually be another issue about this but I can't find it right now.

**Comment by pappasam** [comment]
@jwilm anything stopping #625 from being merged?

**Comment by sodiumjoe** [comment]
They're both merged now.

**Comment by kchibisov** [comment]
Live font reload is possible with alacritty nowadays.
