### ISSUE TITLE
Keymap to open all visible links on The browser

### ISSUE THREAD

**Issue by h3ndry** [alacritty/alacritty#7401]
I appreciate the feature of being able to open links without using the mouse,
but currently, you can only open one link at a time. It would be great to have a
keymap that opens all visible links, so that when you switch to your browser,
you don't have to go back to the terminal.

**Comment by kchibisov** [comment]
But can't you open the links you want ahead of time? it's not like opining a link will _switch_ your focus to the browser?

**Comment by h3ndry** [comment]
That works fine if there are about 1 to 3 links, but as soon as there are about
5 or 10 links, it becomes tedious. I know it is a weird use case.

**Comment by chrisduerr** [comment]
How do you suggest that should even work? It doesn't really make sense with our current config and I have no interest making major structural changes for something so utterly useless.
