### ISSUE TITLE
First time user tried to learn how to make fonts bigger offline

### ISSUE THREAD

**Issue by jidanni** [alacritty/alacritty#7403]
My first alacritty encounter.
I installed it on Debian on a Chromebook. Then offline, I tried it.
`$ alacritty`
it looked OK, but the fonts were too small.
So I looked in man alacritty, but couldn't find out how to
make the fonts bigger. Finally on
/usr/share/doc/alacritty/examples/alacritty.yml I found
```
  # Point size
  #size: 11.0
```
but no matter even if I did
```
$ alacritty -o size=44
```
no change occurred. Nor were there any error messages.

Of course not until I gave up and hit ^D, whereupon there were
many error messages:
```
warning: queue 0x7a54000ca0 destroyed while proxies still attached:
  wl_data_offer@4278190080 still attached
  wl_data_device@18 still attached
  wl_seat@20 still attached
```
So that ends my first encounter.
So offline, without constant Googling
for how to solve such issues, one cannot
get very far.

I see there is a
```
#   - IncreaseFontSize
#   - DecreaseFontSize
```
in the that YML file, but I was looking for command line commands.
My guess is on Debian there is some missing big document.
Nor do I see a -doc in
```
$ aptitude search alacritty|wc -l
26
```
or a package "Recommends:" header.

**Comment by kchibisov** [comment]
>/usr/share/doc/alacritty/examples/alacritty.yml I found

it's under `font:` section.

**Comment by jidanni** [comment]
The only thing near the Font section that seems relevant is
>   # Point size
>  #size: 11.0

But as I said, that didn't work.

Therefore please give an example of how to change the font size from the command line, and I will then submit a PR to make the documentation clearer. Thanks,

**Comment by kchibisov** [comment]
```yml
font:
  size: 14
```

`alacritty -o font.size=14`

it's all was written down for the release you've used.

**Comment by jidanni** [comment]
Ah, no wonder so hard to read,

YAML ... Depending on whom you ask, YAML stands for YAML ain't markup language (a recursive acronym), which emphasizes that YAML is for data, not documents.
