### ISSUE TITLE
showing app open in hyprland client title

### ISSUE THREAD

**Issue by Masber** [alacritty/alacritty#7409]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux
Version: `alacritty --version` output

alacritty 0.13.0-dev (7ceb638f)

Linux/BSD: Wayland

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

I recently installed Hyprland and some apps shows extra information in the `title` section like:

```
$ hyprctl clients

...

Window 5585f5c462f0 -> Module: Sway · Alexays/Waybar Wiki — Mozilla Firefox:
	mapped: 1
	hidden: 0
	at: 1287,46
	size: 1251,1372
	workspace: 1 (1)
	floating: 0
	monitor: 1
	class: firefox
	title: Module: Sway · Alexays/Waybar Wiki — Mozilla Firefox
	initialClass: firefox
	initialTitle: Mozilla Firefox
	pid: 4146
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
	focusHistoryID: 3

Window 5585f45d4200 -> Alacritty:
	mapped: 1
	hidden: 0
	at: 22,46
	size: 1251,679
	workspace: 3 (3)
	floating: 0
	monitor: 1
	class: Alacritty
	title: Alacritty
	initialClass: Alacritty
	initialTitle: Alacritty
	pid: 31700
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
	focusHistoryID: 0
```

I am wondering whether it would be possible for Alacrity to show the app it is currently running, for instance in my case I use Alcritty with neovim therefor I woule expect title to be something like `Alacritty -- Neovim` or something similar.

thank you

Manuel

**Comment by kchibisov** [comment]
Then just set title in programs you run. e.g. in vim or in shell on before running program.
