### ISSUE TITLE
Transparency improvements

### ISSUE THREAD

**Issue by jwilm** [alacritty/alacritty#741]
Based on discussion in #331, we would like to do one or both of the following:

- Add an option to make non-default background colors opaque
- Add an option to fonts to customize their opacity.

**Comment by pwnorbitals** [comment]
Is this issue still relevant ? Not sure if this is still in the works

**Comment by chrisduerr** [comment]
I didn't remember this issue, but there is a PR for it: https://github.com/alacritty/alacritty/pull/4196.
