### ISSUE TITLE
[FR?] Control-minus prodices plain "-", not "^_"

### ISSUE THREAD

**Issue by beelze** [alacritty/alacritty#7412]
Linux/X11.

```
[keyboard]                                                
bindings = [                                              
{ key = "-", mods = "Control", action = "ReceiveChar" },  
{ key = "+", mods = "Control", action = "ReceiveChar" },  
{ key = "=", mods = "Control", action = "ReceiveChar" }   
]                                                         
```                                                          
Most of the terminals I've used (including quake, xfce4-terminal, sakura – but not xterm), produce `^_` when pressing Control-minus. I'm not sure what is the "proper" behaviour , but I'm using this shortcut for undo in zsh and emacs for a long time so I really miss this.

Maybe I missed something but seems there is no relevant config option, so please consider it as FR.

**Comment by kchibisov** [comment]
You can send raw bytes if you really want that if you use `chars` + unicode.

**Comment by beelze** [comment]
> You can send raw bytes if you really want that if you use `chars` + unicode.

Funny, but it works. Thanks!
