### ISSUE TITLE
with tmux on wheel button inserts both selection and clipboard

### ISSUE THREAD

**Issue by Miezhiko** [alacritty/alacritty#7415]
Normally: only pastes selection
Currently: pastes both selection and clipboard from elsewhere

 - other terminal + tmux: works normally
 - alacritty without tmux: works normally
 - alacritty + tmux: current state

**Comment by kchibisov** [comment]
could you give more information, like at least `alacritty -v` output and share your tmux configuration.

**Comment by Miezhiko** [comment]
@kchibisov configs are there https://github.com/Miezhiko/home
alacritty is on commit `f94f4fd4bec024a7a189006b77aa8306b3ba3f88`

**Comment by kchibisov** [comment]
See https://github.com/alacritty/alacritty/pull/7419
