### ISSUE TITLE
Arrow keys print  (up, down, left, right) instead of moving the cursor.

### ISSUE THREAD

**Issue by RC-14** [alacritty/alacritty#7423]
Since cb03806e2ab85674c45e87e1bb24dfe2fd1a918c pressing the arrow keys prints one of these characters:
- UP:  
- Down: 
- Left: 
- Right: 

I obviously expected that they'd make the cursor go one character in the respective direction instead.

### System

OS: macOS
Version: alacritty 0.13.0-dev (cb03806e)

### Logs

`alacritty --print-events` log of a window where I pressed "Arrow Up", "Arrow Down", "Arrow Left", "Arrow Right" and then closed the window with "cmd+w": [print-events.log](https://github.com/alacritty/alacritty/files/13595220/print-events.log)

**Comment by kchibisov** [comment]
Try https://github.com/alacritty/alacritty/pull/7424
