### ISSUE TITLE
Bottom line chopped unless in full screen mode

### ISSUE THREAD

**Issue by jidanni** [alacritty/alacritty#7427]
$ alacritty -o font.size=16
Now in the upper right corner you see "_ 口 X". Pick 口.
$ seq 222 #or whatever. I did env(1)
![image](https://github.com/alacritty/alacritty/assets/1230959/a9188f77-5384-4879-b73d-5f12b5831229)
One needs to switch to fullscreen (on the top row of Chromebook keys) to avoid it.
Maybe related to #4198, or #34.
Seen on Chromebook Linux Debian sid.

**Comment by kchibisov** [comment]
What is this UI at the bottom? It seems like we're just drawing below it, so it looks like not our bug, because it's not under our control.

**Comment by jidanni** [comment]
OK, never mind -o. this worked OK:
```
window:
  decorations: none
  startup_mode: Maximized
font:
  size: 14.0
```
