### ISSUE TITLE
<Ctrl-.> map doesn't work on vim

### ISSUE THREAD

**Issue by Gogiu23** [alacritty/alacritty#7429]
Hi, 
i have this mapping on nvim:

``` 
vim.keymap.set("n", "<C-.>", "<cmd>bNext<CR>", opts)
vim.keymap.set("n", "<C-,>", "<cmd>bprev<CR>", opts)
```

For some reason with alacritty it doesn't work properly.
I have a Mac M2 and i tried with iterm and the vanilla terminal in mac and both the mapping work properly.

### System

Mac M2
Alacritty last version

**Comment by chrisduerr** [comment]
Working as expected.

**Comment by Gogiu23** [comment]
nice support. ill go back to kitty. thanks
