### ISSUE TITLE
change themes color not working

### ISSUE THREAD

**Issue by imkratos** [alacritty/alacritty#7430]
### System

OS: macOS
Version: alacritty 0.12.3 (5efb069)
Linux/BSD: X11/Wayland, DE or Compositor and WM

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: ```Created log file at "/var/folders/fk/8jp_47112q9gxhwqmxdtrsl00000gn/T/Alacritty-69798.log"
[0.000004166s] [INFO ] [alacritty] Welcome to Alacritty
[0.000194458s] [INFO ] [alacritty] Version 0.12.3 (5efb069)
[0.000831250s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/Users/kratos/.config/alacritty/alacritty.yml"
[0.001170083s] [DEBUG] [alacritty] Using environment locale: en_US.UTF-8
[0.023497458s] [INFO ] [alacritty] Using Apple CGL
[0.058529791s] [INFO ] [alacritty] Window scale factor: 2
[0.059413708s] [DEBUG] [alacritty] Loading "SauceCodePro Nerd Font" font
[0.092005916s] [INFO ] [alacritty] Running on Apple M1
[0.092034791s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.095404958s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.099473375s] [INFO ] [alacritty] Cell size: 16 x 40
[0.099494583s] [INFO ] [alacritty] Padding: 20 x 0
[0.099505375s] [INFO ] [alacritty] Width: 2440, Height: 1600
[0.109883416s] [INFO ] [alacritty] PTY dimensions: 40 x 150
[0.112031583s] [INFO ] [alacritty] Initialisation complete
[0.115602208s] [DEBUG] [alacritty_terminal] Term::resize dimensions unchanged
[0.145316083s] [DEBUG] [alacritty_terminal] [Unhandled CSI] action='q', params=[0], intermediates=[62]
[0.168043875s] [DEBUG] [alacritty_terminal] [Unhandled CSI] action='h', params=[7727], intermediates=[63]`
Keyboard and bindings: `alacritty --print-events```

~/.config/alacritty/alacritty.yml

```
# 指定 Alacritty 启动时使用 Fish Shell
shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux attach || tmux"
    
# 不指定 TERM 会导致一些旧机器通过 ssh 连接时无法正常工作
env:
  TERM: xterm-256color

# Colors (One Dark)
colors:
  # Default colors
  primary:
    background: '#282c34'
    foreground: '#abb2bf'

  # Normal colors
  normal:
    # NOTE: Use '#131613' for the `black` color if you'd like to see
    # black text on the background.
    black:   '#282c34'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#d19a66'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#abb2bf'

  # Bright colors
  bright:
    black:   '#5c6370'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#d19a66'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#ffffff'

# 设置字体
# 字体下载: https://www.nerdfonts.com/font-downloads
# 图标符号搜索: https://www.nerdfonts.com/cheat-sheet
# 推荐备选字体: JetBrains Mono Regular Nerd Font Complete Mono
font:
  normal:
    family: 'SauceCodePro Nerd Font'
    style: Regular
  bold:
    family: 'SauceCodePro Nerd Font'
    style: Regular
  italic:
    family: 'SauceCodePro Nerd Font'
    style: Italic
  bold_italic:
    family: 'SauceCodePro Nerd Font'
    style: Italic

  # 字体大小
  size: 14.0

  offset:
    x: 0
    y: 4
  glyph_offset:
    x: 2
    y: 2

window:
  startup_mode: Maximized
  # 窗口大小
  dimensions:
    columns: 150
    lines: 40
  # 窗口透明度 (0 全透明, 1 不透明)
  opacity: 0.9
  padding:
    x: 10
    y: 0
  decorations: none

scrolling:
  # 回滚缓冲区中的最大行数,指定“0”将禁用滚动。
  history: 10000
  # 滚动行数
  multiplier: 4

cursor:
  style:
    shape: Block

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }
live_config_reload: true

# 全屏显示窗口, 绑定快捷键 Ctrl-x
key_bindings:
  - { key: X, mods: Control, action: ToggleSimpleFullscreen }

```

I change colors not working .

somethings wrong ?

**Comment by chrisduerr** [comment]
The config colors work just fine for me. Could you provide more detail on what you're trying to change?

**Comment by imkratos** [comment]
this is my alacritty color 

<img width="1555" alt="image" src="https://github.com/alacritty/alacritty/assets/3302461/e77d8e34-7d0f-4d5e-8a05-000c7928324c">

I use `lsd` replace `ls` 

but  color theme  not `One Dark `

What can i do .

```
# Colors (One Dark)
colors:
  # Default colors
  primary:
    background: '#282c34'
    foreground: '#abb2bf'

  # Normal colors
  normal:
    # NOTE: Use '#131613' for the `black` color if you'd like to see
    # black text on the background.
    black:   '#282c34'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#d19a66'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#abb2bf'

  # Bright colors
  bright:
    black:   '#5c6370'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#d19a66'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#ffffff'
```

**Comment by chrisduerr** [comment]
Your colors are not Alacritty's default colors, so clearly changing colors works.
