### ISSUE TITLE
Graphical Bug with Panfrost

### ISSUE THREAD

**Issue by naortega** [alacritty/alacritty#7431]
### Description

When running Alacritty on my ASUS Chrombook (C201) I get a very strange graphical glitch, as shown in the image below. The image was taken with a screenshot application (flameshot) if that helps. It wasn't taken with a camera. It happens regardless of whether I'm using dwm (X11) or Hyprland (Wayland).

I thought it may be an issue with my graphics on the laptop, but I do not get any sort of graphical glitches when running kitty, another GPU accelerated terminal, nor other OpenGL applications.

![photo_2023-11-10_09-02-16](https://github.com/alacritty/alacritty/assets/6626993/10167ef1-f1af-4994-a074-b08fb0ae15c6)

I get the following logs when launching an instance from a different terminal:

```
warning: queue 0xb58006f8 destroyed while proxies still attached:
  zwp_primary_selection_device_v1@29 still attached
  zwp_primary_selection_device_manager_v1@21 still attached
  wl_data_device@28 still attached
  wl_seat@27 still attached
  wl_data_device_manager@26 still attached
  wl_registry@20 still attached
warning: queue 0x1c30788 destroyed while proxies still attached:
  wl_buffer@45 still attached
  wl_shm_pool@46 still attached
  xdg_wm_base@34 still attached
  wl_output@15 still attached
  wp_fractional_scale_manager_v1@14 still attached
  xdg_activation_v1@13 still attached
  zwp_text_input_manager_v3@12 still attached
  zwp_relative_pointer_manager_v1@11 still attached
  zwp_pointer_constraints_v1@10 still attached
  zxdg_decoration_manager_v1@9 still attached
  wl_seat@8 still attached
  wp_viewporter@7 still attached
  wl_subcompositor@6 still attached
  wl_compositor@5 still attached
  wl_shm@4 still attached
  wl_registry@2 still attached
```

### System

OS: ArchLinuxARM
Computer: ASUS C201
Architecture armv7l
Linux Version: 6.2.10-1-ARCH (from repositories)
Version: 0.12.3 (5efb0690)
Graphics drivers: Panfrost
Graphical Environment: Hyprland (Wayland) and dwm (X11)

**Comment by kchibisov** [comment]
This is upstream mesa bug https://gitlab.freedesktop.org/mesa/mesa/-/issues/9487

Add

```
debug:
  renderer: "gles2_pure"
```

to mitigate

**Comment by naortega** [comment]
I was unaware this was an upstream issue. The "gles2_pure" solution worked perfectly, however.

Thanks!
