### ISSUE TITLE
How to properly switch keyboard layout?

### ISSUE THREAD

**Issue by dmorilha** [alacritty/alacritty#7436]
OS: Linux
Version: 0.12.1
Desktop Environment: Sway

I have sway configured to switch keyboard layouts (see configuration below) and I can switch back and forth on an `xterm` (and other desktop applications) but not on `alacritty`. How's the proper way to configure it? Please, feel free to close the issue in case it does not belong here.

```
input * {
  xkb_layout "us,us_intl"
  xkb_options "grp:alt_space_toggle"
}
```

**Comment by kchibisov** [comment]
This should be done on sway side and keyboard layout switching does work for me. Are you sure that it's not switching? Can you try some other layout, like `ru`?

**Comment by dmorilha** [comment]
you are right, it does work with `ru`, then the problem is something else... why would some glyphs like `ã` and `ç` not display?

I am using alacritty in Gentoo.

**Comment by kchibisov** [comment]
sounds like locale or font issue? Ensure that you have UTF-8 locale and font that can display them.

**Comment by dmorilha** [comment]
thank you

**Comment by nixpulvis** [comment]
I'm usually on my phone when this happens (frantically cursing my fat fingers to exit the god damn emoji view), but for those of us on other platforms looking to implement this for yourself, *slow down*.

It's somewhat easy to semi-brick things if you screw up your keyboard.

**Comment by dmorilha** [comment]
So I set the locale to the one I wanted and it works just fine for existing text... I still believe it is something with the keyboard selection.
