### ISSUE TITLE
Can not copy when `Ctrl+Shift+C` is pressed in Vi mode

### ISSUE THREAD

**Issue by XSE42** [alacritty/alacritty#7438]
### System

OS: Windows
Version: alacritty 0.13.0-rc1 (ada35ae)

### Issue

When I switch to Vi mode in Alacritty 0.13.0-rc1, press `v` to select a portion of text, and then press `Ctrl+Shift+C`, the selected text **cannot** be copied to the clipboard.

And if I set key bindings in `alacritty.toml` as follows, I can copy the selected text successfully in Vi mode:

```
[keyboard]
bindings = [
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "C", mods = "Control|Shift", mode = "Vi|~Search", action = "ClearSelection" },
]
```

This problem did not occur in version 0.12.3, but it first appeared in version 0.13.0-rc1

**Comment by chrisduerr** [comment]
Press `y`.

**Comment by XSE42** [comment]
Thank you for the reply.

I would like to confirm whether this will be the case in future versions? Because in 0.12.3, pressing `Ctrl+Shift+C` could copy in Vi mode.

**Comment by chrisduerr** [comment]
Reopening for now because I realized we do still have the binding, so it should technically work. Will have to look into why it doesn't.
