### ISSUE TITLE
Alacritty reads .zshenv twice (once as zsh, once as -zsh)

### ISSUE THREAD

**Issue by megaNour** [alacritty/alacritty#7441]
While printing which and how were my zsh configuration loaded I noticed:
alacritty starts a zsh shell and reads my `.zshenv`
then it seems to starts a login zsh shell (-zsh) and reads `.zshenv` and all the other config files.
However, I only need to exit once for the terminal to close. So it doesn't seem to be a login shell inside an interactive shell.

Using a couple other terminal emulators, I observe they only start a login shell and read .zshenv once.
Shouldn't alacritty also only do that ?

### System

OS: macOS 14.1.1 (23B81)
Version: alacritty 0.12.3 (5efb069) (brew cask)

#### input:
```
# just start alacritty with this line at the beginning of each config file
echo $(basename -- $0) <hardcoded_name_of_the_processed_file>
```

#### output:
```
Last login: <whatever>
zsh .zshenv
-zsh .zshenv
-zsh .zprofile
-zsh .zshrc
```

#### other terminals output (Terminal, iTerm2):
```
Last login: <whatever>
-zsh .zshenv
-zsh .zprofile
-zsh .zshrc
```

**Comment by kchibisov** [comment]
We don't read shell files.

**Comment by megaNour** [comment]
zsh is run and then run as a login shell

**Comment by megaNour** [comment]
https://zsh.sourceforge.io/Guide/zshguide02.html#l9
> /etc/zshenv
Always run for every zsh.

~/.zshenv
Usually run for every zsh (see below).

**Comment by NourNuxeo** [comment]
I have no idea, but looking at the linked comment, it seems something has been investigated about `exec -a` ?
https://github.com/alacritty/alacritty/blob/a10fb8adc0857633be428d673ab8d36d2a90193a/alacritty_terminal/src/tty/unix.rs#L190

**Comment by kchibisov** [comment]
I mean, the goal is to run `exec -a`, maybe there's an option to run zsh without reading any configs.
