### ISSUE TITLE
Can't get undercurls to have different color than text when using tmux

### ISSUE THREAD

**Issue by jjant** [alacritty/alacritty#7444]
### Description

When I use tmux, my undercurls get the same color as the text. When I don't use tmux, it works correctly (text and undercurl have different colors).

With tmux:
![image](https://github.com/alacritty/alacritty/assets/15112080/8d74f256-12f0-4cf3-9e10-a172107e9f7b)

Without tmux:
![image](https://github.com/alacritty/alacritty/assets/15112080/b854d14f-da7e-4ab2-93ea-2084dcf0e2fa)

Alacritty config:
https://github.com/jjant/nix-config/blob/4c429b817c17bc302a9d320fa3ff642af3baf6b1/hosts/discovery/alacritty/alacritty.yml

Tmux config:

https://github.com/jjant/nix-config/blob/4c429b817c17bc302a9d320fa3ff642af3baf6b1/users/jjantdev/core/tmux/tmux.conf

### System

OS: macOS
Version: `0.12.3`
Tmux version: `3.3a`

**Comment by kchibisov** [comment]
It's up to tmux to decide on that matter given that it's another terminal emulator. Probably it doesn't passthrough color.

**Comment by jjant** [comment]
I got this working by adding

```tmux
set-option -ga terminal-features ",alacritty:usstyle"
```

To my tmux config.
