### ISSUE TITLE
alacritty subcommand migrate missing

### ISSUE THREAD

**Issue by jas01** [alacritty/alacritty#7448]
### System

OS: Linux Arch
Version: alacritty 0.12.3 (5efb0690)
Linux/BSD: X11/Wayland, I3

Stupid question but I see many place people are talking about alacritty subcommand migrate to migrate from yaml to toml. But 
```
 alacritty migrate
error: Found argument 'migrate' which wasn't expected, or isn't valid in this context

USAGE:
    alacritty [OPTIONS] [SUBCOMMAND]

For more information try --help
```
According to the different date of the message I though the migrate subcommand would be include of the current release. 
Are the subcommand only in the beta version ? Or is the package from archlinux who missing the subcommand ?

**Comment by chrisduerr** [comment]
> Version: alacritty 0.12.3

**Comment by jas01** [comment]
Ok thanks. Are toml format supported in 0.12.3 ?

**Comment by kchibisov** [comment]
No. https://github.com/alacritty/alacritty#configuration
