### ISSUE TITLE
cursor gets messed up inside nvim's builtin terminal

### ISSUE THREAD

**Issue by sibouras** [alacritty/alacritty#7452]
when opening a terminal inside neovim the cursor sometimes gets hidden and other times 2 cursors show up, this was not happening in the stable 0.12.3

https://github.com/alacritty/alacritty/assets/64098483/e8bef5f2-6a26-428b-9632-533c1a7c9744

### System

OS: Windows
Version: alacritty 0.13.0-rc1 (ada35ae)

**Comment by kchibisov** [comment]
Looks like windows is just bugged. Nothing really changed since then, though you could try bisecting.

As alternative, you can try loading conpty.dll/OpenConsole.exe, because windows console stuff is really bugged oob.

**Comment by sibouras** [comment]
loading conpty.dll/OpenConsole.exe fixed it, thanks
