### ISSUE TITLE
website showing release candidate config

### ISSUE THREAD

**Issue by BrooksPatton** [alacritty/alacritty#7454]
The [config-alacritty.html](https://alacritty.org/config-alacritty.html) web page is showing config documentation for the release candidate that hasn't been released yet. If someone is trying Alacritty and installing via a package manager they are not going to be able to configure successfully.

Would it possible to keep the deployed website showing information about the latest deployed version until the release candidate has been released?

**Comment by kchibisov** [comment]
There's no and never was documentation on a website for any release other than 0.13.0 which will be in a next couple of days. The deployment before release is special for this particular release.

For previous versions there's a remark.

https://github.com/alacritty/alacritty#configuration
