### ISSUE TITLE
window.position does not work

### ISSUE THREAD

**Issue by arjenbloemsma** [alacritty/alacritty#7455]
Setting window.position does not place the Alacritty window on the desired position.

Tried via the .toml config file and via cli, every time the position is ignored.

TOML
```
[window.position]
x = 100
y = 80
```

CLI
```
alacritty -o window.position.y=200 window.position.x=90 
alacritty -o window.position.y=0
```
### System

OS: MacOS (14.2.1 (23C71)) 
Version: alacritty 0.13.0-rc2 (b8acfda)

**Comment by chrisduerr** [comment]
Did this work before? Otherwise it just sounds like a duplicate of https://github.com/alacritty/alacritty/issues/7267.

**Comment by arjenbloemsma** [comment]
It did, but it was MacOS Stage Manager that was interfering and keeping the window at a fixed position. So no bug after all.
