### ISSUE TITLE
Wait for user input once custom command exits

### ISSUE THREAD

**Issue by UltraBlackLinux** [alacritty/alacritty#7459]
Hey there,
I'd really like to see a feature like Kitty has it, where it waits for user input if the command that was specified in the arguments exited. 
It's currently extremely difficult to e.g. debug a process' log in applications like bottles where the command immediately exits when the wine process exists. I had made attempts to work around this by taking quick screenshots but it's just really difficult...
Could you implement that?
Thanks!

**Comment by kchibisov** [comment]
It's not clear what has anything to do with that, but I'd assume you're running `alacritty -e command`, if so, pass `--hold`.

**Comment by UltraBlackLinux** [comment]
The problem is that I can't pass `--hold` to alacritty if it was executed by bottles and there doesn't seem to be a config option for that

**Comment by kchibisov** [comment]
So you have no control how it's run by bottles? It's not like you can't wrap in a shell script.

**Comment by UltraBlackLinux** [comment]
No. I have zero control over what bottles executes. I cannot just wrap it in a shell script.

**Comment by kchibisov** [comment]
I mean, it somehow runs alacritty, so pretty sure you can control which terminal it'll run if it'll be a terminal in the end of the day. Maybe you can set `TERMINAL=my-script` for it, idk.

**Comment by UltraBlackLinux** [comment]
> I mean, it somehow runs alacritty, so pretty sure you can control which terminal it'll run if it'll be a terminal in the end of the day. Maybe you can set `TERMINAL=my-script` for it, idk.

Just tried that, but no luck.
