### ISSUE TITLE
More padding options

### ISSUE THREAD

**Issue by BlueZeeKing** [alacritty/alacritty#7464]
A feature that I would really like is the ability to specify individual padding for the top, bottom, left, and right, instead of just for x and y. This would be helpful when using something like the "Transparent" window option so that there is enough padding at the top, and not too much at the bottom.

**Comment by chrisduerr** [comment]
https://github.com/alacritty/alacritty/issues/7411#issuecomment-1837625870

**Comment by BlueZeeKing** [comment]
Sorry about that! I thought I checked preexisting issues, but I must have missed it.
