### ISSUE TITLE
startup_mode Maximized and Fullscreen creates invisible windows on Gnome/Wayland

### ISSUE THREAD

**Issue by Porkepix** [alacritty/alacritty#7465]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux
Version: 0.13.0
Gnome on Wayland

### Logs

No troubleshooting section explaining how to gather debug logs (although I'm not sure what they'd show here).

Steps to reproduce:

On Gnome/Wayland, I could reproduce the issue with a minimal config file only containing only this:

```
[window]
startup_mode = "Maximized"
```

Note that the issue also happens when setting it to `Fullscreen`.

Documentation also mentions a `SimpleFullscreen` option on https://alacritty.org/config-alacritty.html but trying to set this throw a configuration error and this option seems to not be recognized (anymore?), so I don't know if the documentation is wrong, or alacritty should recognize it and doesn't.

EDIT: This is a regression from 0.12.x, I just migrated the config and found out this issue while it had no problem right before.

EDIT2: Found out that `SimpleFullscreen` in only for mac, is there a way for the error message to specify it; I guess doc can also be updated, although I'm not sure what's the best way to show this information there.

**Comment by chrisduerr** [comment]
Are you saying the Alacritty window is invisible, or is it creating an invisible window in addition to the Alacritty window?

**Comment by kchibisov** [comment]
which gnome version are you using and could you bisect? It works just fine for me regardless of startup mode.

**Comment by kchibisov** [comment]
This is gnome bug https://gitlab.gnome.org/GNOME/mutter/-/issues/3229

**Comment by kchibisov** [comment]
This patch should workaround the issue, though, I won't add it because I'm not adding workarounds for bugs in every compositor. 

```diff
diff --git a/alacritty/src/event.rs b/alacritty/src/event.rs
index 3b3d8297..ccfbecd3 100644
--- a/alacritty/src/event.rs
+++ b/alacritty/src/event.rs
@@ -1413,8 +1413,7 @@ impl input::Processor<EventProxy, ActionContext<'_, Notifier, EventProxy>> {
                         self.ctx.update_cursor_blinking();
                         self.on_focus_change(is_focused);
                     },
-                    WindowEvent::Occluded(occluded) => {
-                        *self.ctx.occluded = occluded;
+                    WindowEvent::Occluded(_) => {
                     },
                     WindowEvent::DroppedFile(path) => {
                         let path: String = path.to_string_lossy().into();
```

**Comment by dukenukem2d** [comment]
I just put in config **_dimensions = { columns = 100, lines = 100}_** insted of **_starup_mode = "Maximized"_**. Working well for a while.

**Comment by spidyshivam** [comment]
happened on GNOME wayland for me too. but i was using tiling extension so i just commented it out

**Comment by leleobhz** [comment]
Also affected here. Workarround of `dimensions = { columns = 100, lines = 100} ` reduced font size so do not work for me. The disable `startup_mode = "Maximized"` workarround also worked.

**Comment by kchibisov** [comment]
I'm not sure what you want, it's a bug in gnome, it has a PR in gnome to solve that.

**Comment by kchibisov** [comment]
The fedora package applied suggested workaround patch, so it'll propagate in a next few days.

**Comment by Bitals** [comment]
> Workarround of `dimensions = { columns = 100, lines = 100} ` reduced font size so do not work for me.

You can just run alacritty --print-events --ref-test -vvv with no dimensions set in config, maximize the window manually and see in the STDOUT what column and line number it arrived at, than specify just that. This gives you the maximized window with the correct font size from your config ATM.

**Comment by puresick** [comment]
Just as a sidenote: Looks like the GNOME issues has been fixed in GNOME 47. For me, `startup_mode = "Maximized"` does work again.
