### ISSUE TITLE
Config error: style: data did not match any variant of untagged enum ConfigCursorStyle

### ISSUE THREAD

**Issue by Ein420** [alacritty/alacritty#7469]
I don't know why I'm getting this error. This only started happening after an update and migrating my .yml config to .toml.

**System**

OS: Arch Linux
Version: alacritty 0.13.0 (78fa4d6f)

**Logs**

`[989.396555840s] [ERROR] [alacritty_config_derive] Config error: style: data did not match any variant of untagged enum ConfigCursorStyle`

**Config**
```

live_config_reload = true
theme = "Epiphany"
blur = true

[shell]
program = "/usr/bin/fish"

[colors.bright]
black = "#656565"
blue = "#647396"
cyan = "#505b6c"
green = "#8ccd6c"
magenta = "#cdb4c9"
red = "#e85555"
white = "#c0c0c0"
yellow = "#c5d67d"

[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.normal]
black = "#565656"
blue = "#677088"
cyan = "#445362"
green = "#88ab77"
magenta = "#cdcdb4"
red = "#ac4f4f"
white = "#ffffff"
yellow = "#d0d9ad"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[cursor.style]
blink_interval = 0.03
blinking = "On"
shape = "Block"
vi_mode_style = "{ Block, blinking }"

[font]
size = 10

[font.bold]
family = "Iosevka Term"
style = "Bold"

[font.bold_italic]
family = "Iosevka Term"
style = "Bold Italic"

[font.italic]
family = "Iosevka Term"
style = "Italic"

[font.normal]
family = "Iosevka Term"
style = "Regular"

[scrolling]
history = 100000
multiplier = 4

[selection]
save_to_clipboard = true

[window]
dynamic_title = true
opacity = 0.6

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 18
```

**Comment by chrisduerr** [comment]
See docs of the cursor section: https://alacritty.org/config-alacritty.html#cursor

**Comment by kchibisov** [comment]
Because your old config was wrong, but yml silently ignores such things.

`vi_mode_style = "{ Block, blinking }"` is not a valid way to put it.

**Comment by Ein420** [comment]
> See docs of the cursor section: https://alacritty.org/config-alacritty.html#cursor

I'm confused

![image](https://github.com/alacritty/alacritty/assets/52751056/39773b1f-0097-430d-a61a-4dea0f0e64f1)

I see my configuration was faulty, I still continued to copy the documentation as accurately as I could. Which still results in this error:
```
[2718.013460767s] [ERROR] [alacritty_config_derive] Unable to load config "/home/ein/.config/alacritty/alacritty.toml": Config error: TOML parse error at line 40, column 24
                                                       |
                                                    40 | vi_mode_style = { "Block", "Always" }
                                                       |                                            ^
                                                    expected `.`, `=`
```

Which confuses me even more


> See docs of the cursor section: https://alacritty.org/config-alacritty.html#cursor

I understand I'm not configuring it correctly,
even if I follow the documentation exactly how it is,

```
[cursor]
style = { "Block", "Always" }
blink_interval = 0.03
blinking = "On"
shape = "Block"
```

 I still get the following error 
 
 ```
 [3701.315520722s] [ERROR] [alacritty_config_derive] Unable to load config "/home/ein/.config/alacritty/alacritty.toml": Config error: TOML parse error at line 37, column 18
                                                       |
                                                    37 | style = { "Block", "Always" }
                                                       |                              ^
                                                    expected `.`, `=`
```

What am I missing?

**Comment by kchibisov** [comment]
You may notice that it uses `<shape>` and `<shape>` is defined as 

![image](https://github.com/alacritty/alacritty/assets/27620401/9db215f8-0a2c-46f2-a46d-58a1b25e2443)


So you need to `vi_mode_style = { shape = "Block", blinking = "Always" }`.

I'm not sure why it's not clear given that it's all explicitly color coded and the reason it's `blue` is because it's a template. `green` means that it's a regular value.

**Comment by kchibisov** [comment]
There's also an example for the exact same syntax and expansion inside the `keyboard` section.

**Comment by Ein420** [comment]
> So you need to `vi_mode_style = { shape = "Block", blinking = "Always" }`.
> 
> I'm not sure why it's not clear given that it's all explicitly color coded and the reason it's `blue` is because it's a template. `green` means that it's a regular value

Ohh, Okay... that makes sense.
I'm not someone that typically deals with much code-related stuff, so regardless of how things are color coded, there isn't much that could've explicitly shown me how it's laid out and defined (besides the example you mentioned) , as I'd just put my own logic to it (as you saw).

> There's also an example for the exact same syntax and expansion inside the `keyboard` section.

I was so focused on the cursor style I barely looked at that,
even if I did look at it I probably wouldn't have gotten it immediately

Anyways I learned something, thanks
