### ISSUE TITLE
Missing "alacritty.toml" in release assets

### ISSUE THREAD

**Issue by lucastrvsn** [alacritty/alacritty#7479]
Hey! I was looking for the new toml config file, and I head to the [release page](https://github.com/alacritty/alacritty/releases/tag/v0.13.0) to grab the example config and seems like it is missing from the assets.

I'm missing something? Thanks!

**Comment by kchibisov** [comment]
there's no example toml, read either `man 5 alacritty` or https://alacritty.org/config-alacritty.html .

docs in readme are pretty clear on that matter.

**Comment by lucastrvsn** [comment]
> there's no example toml, read either `man 5 alacritty` or https://alacritty.org/config-alacritty.html .
> 
> docs in readme are pretty clear on that matter.

Sorry, I think I misunderstood that. Reading the README seems to me that some example configuration will be available, like it always was.

> Alacritty versions before 0.13.0 are using YAML configuration files and all their settings were documented in the alacritty.yml. The example alacritty.yml file for each release can be found on [GitHub releases page](https://github.com/alacritty/alacritty/releases).

I think it's better to update the README to make it clear that no example configuration will be provided for future version.

**Comment by kchibisov** [comment]
![image](https://github.com/alacritty/alacritty/assets/27620401/a1185e7d-89be-4191-a925-d209467e6638)
