### ISSUE TITLE
Broken startup Alacritty 0.13.0

### ISSUE THREAD

**Issue by rend3r** [alacritty/alacritty#7486]
Alacritty v0.13.0 portable
Windows 10 Home 22H2
Build: 19045.3803

```
C:\Progs>Alacritty-v0.13.0-portable.exe -vv
C:\Progs>Created log file at "C:\Users\17D3~1\AppData\Local\Temp\Alacritty-13076.log"
[0.000013500s] [INFO ] [alacritty] Welcome to Alacritty
[0.001127600s] [INFO ] [alacritty] Version 0.13.0 (78fa4d6)
[0.005541200s] [INFO ] [alacritty_config_derive] No config file found; using default
[0.028499600s] [INFO ] [alacritty] Window scale factor: 1.25
[0.094622400s] [INFO ] [alacritty] Using WGL
[0.095926000s] [DEBUG] [alacritty] Picked GL Config:
                                     buffer_type: Some(Rgb { r_size: 8, g_size: 8, b_size: 8 })
                                     alpha_size: 8
                                     num_samples: 0
                                     hardware_accelerated: true
                                     supports_transparency: Some(false)
                                     config_api: Api(OPENGL | GLES1 | GLES2)
                                     srgb_capable: true
[0.138889200s] [DEBUG] [alacritty] Loading "Consolas" font
[0.154758900s] [INFO ] [alacritty] Running on Intel(R) UHD Graphics
[0.155122800s] [INFO ] [alacritty] OpenGL version 3.3.0 - Build 27.20.100.8476, shader_version 3.30 - Build 27.20.100.8476
[0.157029200s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.247811400s] [DEBUG] [alacritty] Enabled debug logging for OpenGL
[0.248544100s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.297925700s] [INFO ] [alacritty] Cell size: 10 x 21
[0.298329000s] [INFO ] [alacritty] Padding: 0 x 0
[0.300300000s] [INFO ] [alacritty] Width: 800, Height: 600
[0.354028800s] [INFO ] [alacritty] PTY dimensions: 28 x 80
[0.355193400s] [INFO ] [alacritty_terminal] Using Windows API for pseudoconsole
panicked at alacritty_terminal\src\tty\windows\conpty.rs:235:5:
Unable to spawn shell: Не удается найти указанный файл. (os error 2)
```

Не удается найти указанный файл. (os error 2) = No such file or directory (os error 2)

**Comment by rend3r** [comment]
As result - white blank Alacritty windows and ~10% cpu consumption

**Comment by kchibisov** [comment]
What was your config file before and could you try running without it?

**Comment by kchibisov** [comment]
Though, it was using default already, do you have `pwsh.exe` installed?

**Comment by kchibisov** [comment]
And does 0.12.3 portable exe work if you run it from the same place you're running 0.13.0 one?

**Comment by rend3r** [comment]
> Though, it was using default already, do you have `pwsh.exe` installed?

No, only C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe whick is hard link to C:\Windows\WinSxS\amd64_microsoft-windows-powershell-exe_31bf3856ad364e35_10.0.19041.3636_none_ddad9577b78717ba\powershell.exe

> And does 0.12.3 portable exe work if you run it from the same place you're running 0.13.0 one?

```
C:\Progs>Alacritty-v0.11.0-portable.exe -vv
panicked at 'Unable to spawn shell: Не удается найти указанный файл. (os error 2)', alacritty_terminal\src\tty\windows\conpty.rs:168:5

C:\Progs>Alacritty-v0.12.3-portable.exe -vv
panicked at 'Unable to spawn shell: Не удается найти указанный файл. (os error 2)', alacritty_terminal\src\tty\windows\conpty.rs:168:5

```

**Comment by kchibisov** [comment]
Yeah, the default is `pwsh` you may want to create a config with `cmd.exe`.

**Comment by rend3r** [comment]
> alternatively you can try `alacritty -e cmd.exe`

`Alacritty-v0.13.0-portable.exe -e cmd.exe` do work.

> you may want to create a config with `cmd.exe`

Yep, it would be nice, but only question - where is config should be placed for portable version?
README.MD says:

```
On Windows, the config file should be located at:
%APPDATA%\alacritty\alacritty.toml
```
but it isn't convient path for portable version.

**Comment by kchibisov** [comment]
> but it isn't convient path for portable version.

Path is the same for each version, just ensure that you properly go into `%APPDATA%` since it's a env variable.

**Comment by rend3r** [comment]
> just ensure that you properly go into `%APPDATA%` since it's a env variable

That is what i mean "is not convient path". For example, USB flash drive with portable Alacritty will check user profile directory which differ from system to system. More handy variant to check config in the same directory where is Alacritty.exe located.

**Comment by kchibisov** [comment]
yeah, but you may pass the `-o shell="cmd.exe` as first arg (wrapping the thing in bat) or pass the config via the `--config-file` if it's not in the standard location.

**Comment by rend3r** [comment]
> pass the config via the `--config-file` if it's not in the standard location.

Ok
