### ISSUE TITLE
Certain modifiers fail in `kakoune`

### ISSUE THREAD

**Issue by glaeqen** [alacritty/alacritty#7492]
I found at least two type of modifiers that stopped working on `0.13` that worked before on `0.12`.

-  `ctrl + [` does not trigger `ESC`-equivalent behaviour in `kakoune`.
    - Interestingly enough the same action continues to work in `vim`?
- `alt + shift` combinations fail to register, so I checked eg. `alt + shift + !` (append command output), `alt + K` (keep not matching), `alt + N` (extend reverse search).

I assume these issues have a wider impact than just `kakoune` but I found it the easiest to reproduce it there. It possibly might be a duplicate considering a wave of keyboard input related issues lately but none so far seems to match exactly that. Sorry in advance.

### System

OS: Arch Linux
Version: alacritty 0.13.0 (78fa4d6f)
Linux/BSD: Wayland, sway

### Logs

This should be quite trivial to reproduce, can provide logs if necessary though.

Thanks a lot for looking into it. Fantastic project and amazing work, lots of love <3

**Comment by chrisduerr** [comment]
@kchibisov Sounds like keyboard protocol stuff? This seems intentional on kakoune's end.

**Comment by kchibisov** [comment]
I think it's due to kakoune really wanting associated text, I'll try to write a patch.

**Comment by kchibisov** [comment]
Could you try applying that?

```diff
diff --git a/alacritty/src/input/keyboard.rs b/alacritty/src/input/keyboard.rs
index 423f8bae..70bfaf06 100644
--- a/alacritty/src/input/keyboard.rs
+++ b/alacritty/src/input/keyboard.rs
@@ -338,7 +338,15 @@ impl SequenceBuilder {
             let base_character = character.to_lowercase().next().unwrap();

             let codepoint = u32::from(character);
-            let base_codepoint = u32::from(base_character);
+            let mut base_codepoint = u32::from(base_character);
+
+            // Try to get the base for keys which change based on modifier, like `1` for `!`.
+            match key.key_without_modifiers().as_ref() {
+                Key::Character(unmodded) if codepoint == base_codepoint => {
+                    base_codepoint = u32::from(unmodded.chars().next().unwrap_or(base_character));
+                },
+                _ => (),
+            }

             // NOTE: Base layouts are ignored, since winit doesn't expose this information
             // yet.

```

This should probably fix the `alt + shift + 1`, but I'm not sure what could happen with `ctrl + [` or `alt + K`, they work the same compared to e.g. kitty/foot when I look into the generated events.

Could you post the `alacritty -vvv` log when you try to repro the issue after this patch applied?

**Comment by kchibisov** [comment]
>ctrl + [ does not trigger ESC-equivalent behaviour in kakoune. 

This is not an escape when you have kitty protocol, so unless kakoune explicitly binds it won't work.

>alt + K (keep not matching), alt + N (extend reverse search).

Not sure what they supposed to do, we reported them the same as in other terminals when kitty protocol is in use.

**Comment by glaeqen** [comment]
@kchibisov 

> This should probably fix the `alt + shift + 1`

`alt + shift + 1` does not work with and without a patch.

before:
```
[325.781451523s] [TRACE] [alacritty_terminal] Setting title to 'Some("*scratch* 4:2 [scratch] 1 sel - client0@[18589] - Kakoune")'
[325.781533218s] [TRACE] [alacritty_terminal] Setting private mode: SyncUpdate
[325.781563469s] [TRACE] [alacritty_terminal] Unsetting private mode: SyncUpdate
[325.781586171s] [TRACE] [alacritty_terminal] Unsetting private mode: SyncUpdate
[325.781608326s] [TRACE] [alacritty_terminal] Going to: line=3, col=4
```

after:
```
[16.494565079s] [TRACE] [alacritty_terminal] Setting title to 'Some("*scratch* 1:1 [scratch] 1 sel - client0@[20513] - Kakoune")'
[16.494646028s] [TRACE] [alacritty_terminal] Setting private mode: SyncUpdate
[16.494674332s] [TRACE] [alacritty_terminal] Unsetting private mode: SyncUpdate
[16.494696849s] [TRACE] [alacritty_terminal] Unsetting private mode: SyncUpdate
[16.494718592s] [TRACE] [alacritty_terminal] Going to: line=0, col=3
```


> but I'm not sure what could happen with `ctrl + [` or `alt + K`, they work the same compared to e.g. kitty/foot when I look into the generated events.

With `ctrl + [` you're actually right. `alacritty <0.13` matches the behaviour of eg. `xterm` or `gnome-terminal` and not `foot`/`kitty` and there it works. I guess it's because of the protocol you've mentioned although I'm not familiar with it to understand all the implications. Could you elaborate a little bit more? Can it be tweaked/turned off? Manual binding seems to solve it

FTR:
```
# Bind ^[ to ESC everywhere
map global insert <c-[> <esc>
map global normal <c-[> <esc>
map global prompt <c-[> <esc>
map global menu <c-[> <esc>
map global user <c-[> <esc>
map global goto <c-[> <esc>
map global view <c-[> <esc>
map global object <c-[> <esc>
```

but muscle memory is going to be annoying on vanilla editor configurations :( Feels like [1172](https://xkcd.com/1172/) case.

However, `alt + K`, `alt + !`, `alt + shift + /`, `alt + N` etc. seems to work correctly & same in `kitty`, `foot`, `xterm`, `gnome-terminal` and `alacritty pre-0.13` but not on master.

**Comment by kchibisov** [comment]
Could you not truncate the logs output and tell me exactly what to do with.

>map global menu <c-[> <esc>

Just remap it in alacritty if you want to emit the `chars` you need, no need to alter editor here.

**Comment by kchibisov** [comment]
I just tried `kak` myself which I can install on fedora, and `alt+k` doesn't work for me in both kitty, foot, alacritty. `kak` enabled the `DISAMBIGUATE` and `REPORT_ALT_TEXT`, to simulate what it's doing, you should try running 

```
printf "\e[=5;1u" && showkey -a
```

Then when you press `Alt + k` you should see something like

```
^[[107;3u 	 27 0033 0x1b
```

The same I see in foot, and kitty adds the my base layout information along the way, which is irrelevant for this case.

I thought initially that kak uses base keys, thus I wrote a patch to account for `!` -> `1` relationship, however for the `alt+k` there's no such a thing, meaning that the issue on the `kak` side, which is unfortunate.

On the other part, nvim and vim itself, both enable the same mods and work just fine, as you've seen.

**Comment by kchibisov** [comment]
Ah, no, it actually works in all alacritty,kitty,foot for me, I just haven't figured out how it should work, since you need to press `ESC` first and then `alt+k`, because you need to enter normal? mode. If I enter some normal? mode and then press `alt+k` it works as it should, pre 0.13 I just had to press it twice, because first one will emit `esc` and thus make me into the normal mode?, so I was testing it differently.

**Comment by kchibisov** [comment]
Could you try with the `alacritty --config-file /dev/null` config actually, maybe you have conflicting encoding in your bindings and that's why it doesn't work?

**Comment by glaeqen** [comment]
`kakoune` is a modal editor, so yes, normal mode is expected for `alt + k` or `alt + K` to work. Sorry, should have been more clear on that.

`alt + k` works just fine in the new alacritty version, I just meant  the keybindings with `alt + shift` in them, so `alt + shift + k` - thus `alt + K`. The same goes for `alt + !` because `alt + shift + 1`.

So expected behaviour (normal mode):
- `alt + k`: see "keep matching".
- `alt + shift + k`: see "keep not matching". (does NOT work in 0.13)
- `/`: see "search"
- `alt + /`: see "reverse search"
- `shift + /`: see "search (extend)"
- `alt + shift + /`: see "reverse search (extend)". (does NOT work in 0.13)
- `!`: see "insert output"
- `alt + !`: see "append output". (does NOT work in 0.13)

From comparing different key bindings seems like `shift` is ignored as soon as `alt` is pressed. So pressing `alt + shift + /` yields "reverse search" which is bound to `alt + /`.

My config is quite bare-bone. `--config-file /dev/null` yields no change in behaviour :/

**Comment by kchibisov** [comment]
Ah, ok.

This should fix it https://github.com/alacritty/alacritty/pull/7493

**Comment by glaeqen** [comment]
FTR, I sshed into the Ubuntu based box and everything seems to work on ancient `kakoune v2020.09.01` that they ship, including `ctrl + [`. I'm using `kakoune v2023.07.29`. I don't know which version they ship on Fedora. Even more variables in the equation unfortunately :/

> This should fix it https://github.com/alacritty/alacritty/pull/7493

I'll see now, thanks for a quick feedback :)

**Comment by glaeqen** [comment]
Patch seems to fix the issue with the `alt + shift` 👍🏻 I'm still wondering why in the old kakoune `ctrl + [` works just fine, very curious.

**Comment by kchibisov** [comment]
`ctrl + [` is just escape, however kitty protocol tries to _solve_ this issue and make it distinguishable from `ESC`.

And just thinking about it you can't really solve it with alacritty binding...

**Comment by glaeqen** [comment]
> `ctrl + [` is just escape, however kitty protocol tries to _solve_ this issue and make it distinguishable from `ESC`.
> 
> And just thinking about it you can't really solve it with alacritty binding...

Initially I interpreted your comment as you keep working on getting the `^[` to work but considering that you closed the issue I assume that on `alacritty` part everything works as intended? Because PR merged into the master does not make `^[` trigger `ESC` action in `kakoune`. Sorry for the confusion.

**Comment by kchibisov** [comment]
>Because PR merged into the master does not make ^[ trigger ESC action in kakoune

yes, this works as intended, it should work the same in kitty/foot. If it's not let me know.

**Comment by glaeqen** [comment]
> it should work the same in kitty/foot

So far everything seems to work so thanks for help! I circumvented the missing `^C` behaviour with the alacritty binding. 

```
[keyboard]
bindings = [
    # ^C -> Esc
    { key = "[", mods = "Control", chars = "\u001B" }
]
```

Not sure if `kakoune` should copy the `vim` behaviour and interpret `^C` on it's own or not but that's out of scope for alacritty.

**Comment by glaeqen** [comment]
@kchibisov is some minor release planned soon? Not sure if there's some defined schedule, so I'm curious.
