### ISSUE TITLE
Website https://alacritty.org does not work

### ISSUE THREAD

**Issue by vehlwn** [alacritty/alacritty#7495]
I wanted to see documentation and followed the link https://alacritty.org/config-alacritty.html in readme but couldn't open it from my home internet from Russia. Curl says "SSL certificate problem: unable to get local issuer certificate". My ISP's support says there are no restrictions on their side and that I need to ask the owner of the site. I managed to open the site via Tor but I'm still confused: did the owner deliberately block it for Russian users? If so, has he blocked it for any other countries?

**Comment by kchibisov** [comment]
```
 ~  tracepath alacritty.org
 1?: [LOCALHOST]                      pmtu 1500
 1:  _gateway                                             34.733ms
 1:  _gateway                                             34.857ms
 2:  pluton-pub.ispras.ru                                 35.794ms
 3:  83.149.199.254                                       35.077ms
 4:  404.et012.m9-5-gw.msk.niks.su                        35.801ms
 5:  128.ae2.kt12-5-gw.spb.niks.su                        43.046ms
 6:  67.ae1.c21-5-gw.spb.niks.su                          44.259ms
 7:  sap-b4-link.ip.twelve99.net                          43.872ms
 8:  s-bb1-link.ip.twelve99.net                           56.655ms asymm 10
 9:  ffm-bb1-link.ip.twelve99.net                         75.420ms asymm 11
10:  ffm-b5-link.ip.twelve99.net                          74.883ms
11:  digitalocean-ic-328177.ip.twelve99-cust.net          78.754ms asymm  9
12:  138.197.250.152                                      79.920ms asymm 11
13:  no reply
14:  no reply
15:  no reply
16:  164.92.244.58                                        76.806ms reached
     Resume: pmtu 1500 hops 16 back 13
 ~ 

```

works for me when I go through russian vpn. I know that some providers block DO and similar, or DO blocks some russian providers, it's a matter of luck, but vpn does work. 

in case you can't access the site you can use `man 5 alacritty`, it's all the same.

**Comment by kchibisov** [comment]
https://github.com/alacritty/website/ you can also clone and read static website, if you don't have man pages for any reason.
