### ISSUE TITLE
unknown variant `Grave`

### ISSUE THREAD

**Issue by boringplay** [alacritty/alacritty#7497]
unknown variant `Grave` after upgrade to `0.13.0`

### System

OS: macOS
Version: `alacritty 0.13.0 (78fa4d6)`

**Comment by danbruegge** [comment]
Same here. The quick fix was by commenting the parts. 😅

```
# [[keyboard.bindings]]
# chars = "\u001B`"
# key = "Grave"
# mods = "Command"
#
# [[keyboard.bindings]]
# chars = "\u001B~"
# key = "Grave"
# mods = "Command|Shift"
```

**Comment by chrisduerr** [comment]
Try using the grave character, instead of the word.

**Comment by kchibisov** [comment]
yeah, you need a `grave` character itself now, I tried to port as much as I can, but knowing whether something really produced anything before is unrealistic.

So, just `chars = "`"` should be it, if I understand what the `grave` actually is.

**Comment by russmatney** [comment]
@kchibisov do you mean to use the `keys` key (not `chars`)?

```
[[keyboard.bindings]]
chars = "\u001B`"
key = "`"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B~"
key = "`"
mods = "Alt|Shift"
````

Tho I can't remember what I used this for, my config doesn't blow up alacritty anymore.
