### ISSUE TITLE
alacritty floating window broke on sway

### ISSUE THREAD

**Issue by firashacker** [alacritty/alacritty#7499]
after the latest upgrade for alacritty migrating the config file to TOML i got some issues using it in sway and misbehaviors
first after migrating the original config i got the following log:

[13.954160085s] [WARN ] [alacritty_config_derive] Unused config key: history
[13.954232773s] [WARN ] [alacritty_config_derive] Unused config key: multiplier
[19.050116434s] [WARN ] [alacritty_config_derive] Unused config key: history
[19.050161157s] [WARN ] [alacritty_config_derive] Unused config key: multiplier

so i commented those options in my config but still the most annouing glitch happens in floating mode as in the picture
![Screenshot_2023-12-29-15-23-37_1920x1080](https://github.com/alacritty/alacritty/assets/70780581/864fea1f-51ae-499a-b20c-0b9f196a5e4d)

please fix this sway is my only desktop and i'm not planing to move into other terminal

**Comment by firashacker** [comment]
and that happens when i define window dimentions in the config file it was sat like this
[window.dimensions]
columns = 82
lines = 24

**Comment by chrisduerr** [comment]
Does resizing the window fix it?

**Comment by firashacker** [comment]
yes

**Comment by kchibisov** [comment]
Try this https://github.com/alacritty/alacritty/issues/7474#issuecomment-1871376390

**Comment by firashacker** [comment]
so you want me to build alacritty from source ? man i install my system to often i use shell script for that its custom arch and averything is downloaded from mirrors . i could prevent this issue by downloading the older version and hold it in pacman.conf file so it stays the same but i'm not going for it if this cant work normally i may change the entire terminal

**Comment by kchibisov** [comment]
I mean, if you don't want to verify that your issue is fixed sure.

**Comment by kchibisov** [comment]
For now I guess you can not define the dimensions in config, it's not like they matter in sway.

**Comment by kchibisov** [comment]
Which version of sway is it, the `-git` one?

**Comment by kchibisov** [comment]
I tried both sway 1.8.1 and sway-git with the following config (and various variations of it).

```toml
[window]
dynamic_padding = true
padding = { x = 3, y = 3 }
decorations = "full"
dimensions = { columns = 93, lines = 38 }
```


Using the following sway config.

```sway
input "*" {
	repeat_delay 200
	repeat_rate 60
	xkb_layout us(dvorak)
	xkb_options caps:escape,compose:ralt
}

output "LG Electronics LG ULTRAFINE 210MAPNPQ848" {
	bg /etc/greetd/wallpaper.png fill
	max_render_time 5
	scale 1.5
}

bindsym Mod4+Return exec run-alacritty -o font.size=15.75

bindsym --to-code Mod4+Control+f floating toggle

default_floating_border pixel 3
default_border pixel 3
floating_modifier Mod4

bindsym --to-code Mod4+h focus left
bindsym --to-code Mod4+l focus right
bindsym --to-code Mod4+k focus up
bindsym --to-code Mod4+j focus down

bindsym --to-code Mod4+Shift+Left move left
bindsym --to-code Mod4+Shift+Right move right
bindsym --to-code Mod4+Shift+Up move up
bindsym --to-code Mod4+Shift+Down move down

```

And all works as expected, once I make window float it uses the values I have in alacritty config with the correct border around the window on both, git and 1.8.1. And yes, I've used scale 1, 1.5, 2, so it used every codepath related.

Could you share your config please? Do you resize alacritty window by sway means once you make it float?

**Comment by firashacker** [comment]
i will try your config thank you

**Comment by firashacker** [comment]
so my issue is when i launch the terminal in floating mode not when togeling floating on tiled window, that will work fine but when i start the terminal on floating mode its not resizing to the borders

**Comment by kchibisov** [comment]
Could you give me your sway config, sway version, and alacritty config? Sway is known to be bugged around initial sizes.

**Comment by firashacker** [comment]
this is my config

import = ["/home/firas/.config/sway/alacritty/colors.toml", "/home/firas/.config/sway/alacritty/fonts.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "full"
dynamic_title = true
opacity = 0.98
startup_mode = "Windowed"

[scrolling]
history = 10000
multiplier = 3


[window.dimensions]
columns = 82
lines = 24

[window.padding]
x = 12
y = 12

**Comment by firashacker** [comment]
sway version 1.8.1

alacritty 0.13.0 (78fa4d6f)

sway config : 
## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
##
## Sway Master configuration file (For Archcraft)

##-- Display ----------------------------
output  HDMI-A-1  mode 1920x1080@143.993Hz

##-- Mod Keys ----------------------------

set $mod Mod4
set $alt Mod1

##-- Fonts (Global) ----------------------
font pango:JetBrains Mono Medium 10

##-- Config files ------------------------
include ~/.config/sway/sway-idle
include ~/.config/sway/sway-input
include ~/.config/sway/sway-output
include ~/.config/sway/sway-modes
include ~/.config/sway/sway-theme

##-- General Settings --------------------
input "type:keyboard" {
    xkb_layout us,ara
    xkb_options grp:alt_shift_toggle
}

default_orientation horizontal
swaybg_command swaybg
swaynag_command swaynag
workspace_layout default
xwayland enable
focus_follows_mouse yes
floating_modifier $mod normal
mouse_warping none
popup_during_fullscreen smart
workspace_auto_back_and_forth yes
focus_on_window_activation smart
show_marks yes

##-- Variables ---------------------------
set $alacritty ~/.config/sway/scripts/alacritty
set $foot ~/.config/sway/scripts/foot
set $volume ~/.config/sway/scripts/volume
set $backlight ~/.config/sway/scripts/brightness
set $screenshot ~/.config/sway/scripts/screenshot
set $lockscreen ~/.config/sway/scripts/lockscreen
set $wlogout ~/.config/sway/scripts/wlogout
set $colorpicker ~/.config/sway/scripts/colorpicker
set $files thunar
set $editor geany
set $browser firefox

set $rofi_bluetooth ~/.config/sway/scripts/rofi_bluetooth
set $rofi_launcher ~/.config/sway/scripts/rofi_launcher
set $rofi_music ~/.config/sway/scripts/rofi_music
set $rofi_powermenu ~/.config/sway/scripts/rofi_powermenu
set $rofi_runner ~/.config/sway/scripts/rofi_runner
set $rofi_screenshot ~/.config/sway/scripts/rofi_screenshot
set $rofi_network ~/.config/sway/scripts/rofi_network

set $wofi_menu ~/.config/sway/scripts/wofi_menu
set $wofi_powermenu ~/.config/sway/scripts/wofi_powermenu

set $open_in_alacritty alacritty --config-file ~/.config/sway/alacritty/alacritty.yml

##-- Startup Programs --------------------
exec_always ~/.config/sway/scripts/startup
#exec_always ~/.config/sway/scripts/clamshell

##-- Keybindings -------------------------

# -- Terminal : alacritty --
bindsym $mod+Return 			exec $alacritty
bindsym $mod+Shift+Return 		exec $alacritty -f
bindsym $mod+$alt+Return 		exec $alacritty -F

# -- Terminal :foot --
#bindsym $mod+Return 			exec $foot
#bindsym $mod+Shift+Return 		exec $foot -f
#bindsym $mod+$alt+Return 		exec $foot -s
#bindsym $mod+t 				exec $foot -F

# -- GUI Apps --
bindsym $mod+f 			exec $files
bindsym $mod+Shift+e 			exec $editor
bindsym $mod+w 			exec $browser

# -- CLI Apps --
bindsym $alt+Control+v 			exec --no-startup-id "$open_in_alacritty -e vim"
bindsym $alt+Control+r 			exec --no-startup-id "$open_in_alacritty -e ranger"
bindsym $alt+Control+h 			exec --no-startup-id "$open_in_alacritty -e htop"

# -- Rofi --
bindsym $alt+F1 				exec $rofi_launcher
bindsym $alt+F2 				exec $rofi_runner
bindsym $mod+a	 				exec $rofi_launcher
bindsym $mod+r	 				exec $rofi_runner
bindsym $mod+n 					exec $rofi_network
bindsym $mod+p 					exec $rofi_powermenu
bindsym $mod+m 					exec $rofi_music
bindsym $mod+s 					exec $rofi_screenshot
bindsym $mod+b 					exec $rofi_bluetooth

# -- Wofi --
#bindsym $alt+F1 				exec $wofi_menu
#bindsym $mod+d	 				exec $wofi_menu
#bindsym $mod+x 				exec $wofi_powermenu

# -- Misc --
bindsym $mod+Shift+p 					exec $colorpicker
#bindsym $mod+n 				exec nm-connection-editor
#bindsym $mod+x 				exec $wlogout

# -- Function keys --
bindsym XF86MonBrightnessUp 	exec "$backlight --inc"
bindsym XF86MonBrightnessDown 	exec "$backlight --dec"
bindsym XF86AudioRaiseVolume 	exec "$volume --inc"
bindsym XF86AudioLowerVolume 	exec "$volume --dec"
bindsym XF86AudioMute 			exec "$volume --toggle"
bindsym XF86AudioMicMute 		exec "$volume --toggle-mic"

#bindsym XF86AudioPlay 			exec playerctl play-pause
#bindsym XF86AudioPause 			exec playerctl play-pause
#bindsym XF86AudioNext 			exec playerctl next
#bindsym XF86AudioPrev 			exec playerctl previous

#bindsym ctrl+XF86AudioNext 		exec "mpc next"
#bindsym ctrl+XF86AudioPrev 		exec "mpc prev"
#bindsym ctrl+XF86AudioPlay 		exec "mpc toggle"
#bindsym ctrl+XF86AudioStop 		exec "mpc stop"
bindsym $mod+ctrl+v 			exec pavucontrol
bindsym XF86AudioNext 		exec "mpc next"
bindsym XF86AudioPrev 		exec "mpc prev"
bindsym XF86AudioPlay 		exec "mpc toggle"
bindsym XF86AudioStop 		exec "mpc stop"

# -- Screenshots --
bindsym Menu 					exec "$screenshot --now"
bindsym $alt+Menu 				exec "$screenshot --in5"
bindsym Shift+Menu	 			exec "$screenshot --in10"
bindsym Control+Menu 			exec "$screenshot --win"
bindsym $mod+Menu 				exec "$screenshot --area"

# -- Lockscreen --
bindsym $mod+l 			exec "$lockscreen"

## -- Sway --

## Kill focused window
##
bindsym $mod+Shift+q kill
#bindsym $mod+c kill

#------

## Send Notification
##
set $send-notify exec --no-startup-id notify-send -u low -h string:x-canonical-private-synchronous:swayconfig

## Splitting containers
##
## split in horizontal orientation
bindsym $mod+h split horizontal, $send-notify 'Split Horizontally'
## split in vertical orientation
bindsym $mod+v split vertical, $send-notify 'Split Vertically'
## toggle split
bindsym $mod+g split toggle, $send-notify 'Split Mode'

#------

## Manipulating layout
##
## change container layout (stacked, tabbed, toggle split)
## Set stacking layout
bindsym $mod+Shift+s layout stacking, $send-notify 'Layout - Stacking'
## Set tabbed layout
bindsym $mod+Shift+t layout tabbed, $send-notify 'Layout - Tabbed'
## Set default layout
bindsym $mod+Shift+d layout default, $send-notify 'Layout - Default'
## Toggle between stacking/tabbed/split:
bindsym $mod+Shift+l layout toggle, $send-notify 'Cycling Layouts'
## Toggle between horizontal/vertical:
bindsym $mod+Shift+v layout toggle split, $send-notify 'Layout - Hor/Vert'
## Toggle fullscreen
bindsym $mod+Shift+f fullscreen toggle, $send-notify 'Toggled Fullscreen'
## Toggle floating/tiling
bindsym $mod+space floating toggle, $send-notify 'Toggled Floating Mode'

#------

## Focusing containers
##
## Sets focus to the nearest container in the given direction.
#bindsym $mod+h focus left
#bindsym $mod+j focus down
#bindsym $mod+k focus up
#bindsym $mod+l focus right
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right
## Sets focus to the parent container of the current container.
bindsym $mod+Shift+a focus parent
## The opposite of `focus parent`, sets the focus to the last focused child container.
bindsym $mod+z focus child
## Automatically sets focus to the adjacent container.
bindsym $mod+Tab focus next
## Toggles focus between floating/tiling containers.
bindsym $mod+Shift+space focus mode_toggle

#------

## Moving containers
##
## move focused window in the given direction.
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right
## Move floating container to the center of all outputs (floating only)
bindsym $mod+$alt+c move absolute position center
## Move container to the current position of the cursor (floating only)
bindsym $mod+$alt+p move position mouse

#------

## Resizing containers/windows
##
bindsym $mod+$alt+Left resize shrink width 10 px or 10 ppt
bindsym $mod+$alt+Down resize grow height 10 px or 10 ppt
bindsym $mod+$alt+Up resize shrink height 10 px or 10 ppt
bindsym $mod+$alt+Right resize grow width 10 px or 10 ppt

#------

## Sticky floating windows (floating only)
##
bindsym $mod+o sticky toggle, $send-notify 'Toggled Sticky'

#------

## Changing border style
##
bindsym $mod+y border toggle, $send-notify 'Toggled Borders'

#------

## Scratchpad
##
## Make the currently focused window a scratchpad
bindsym $mod+minus move scratchpad, $send-notify 'Scratchpad'
## Show the first scratchpad window
bindsym $mod+Shift+minus scratchpad show

#------

## reload the configuration file
bindsym $mod+ctrl+r reload, $send-notify 'Configuration Reloaded!'
## quit sway session
bindsym $mod+Shift+x exit

#------

## Changing (named) workspaces/moving to workspaces
##
## Define names for default workspaces for which we configure key bindings later on.
## We use variables to avoid repeating the names in multiple places.
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

## switch to workspace
bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4
bindsym $mod+5 workspace number $ws5
bindsym $mod+6 workspace number $ws6
bindsym $mod+7 workspace number $ws7
bindsym $mod+8 workspace number $ws8
bindsym $mod+9 workspace number $ws9
bindsym $mod+0 workspace number $ws10

## move focused container to workspace
bindsym $mod+Shift+1 move container to workspace number $ws1
bindsym $mod+Shift+2 move container to workspace number $ws2
bindsym $mod+Shift+3 move container to workspace number $ws3
bindsym $mod+Shift+4 move container to workspace number $ws4
bindsym $mod+Shift+5 move container to workspace number $ws5
bindsym $mod+Shift+6 move container to workspace number $ws6
bindsym $mod+Shift+7 move container to workspace number $ws7
bindsym $mod+Shift+8 move container to workspace number $ws8
bindsym $mod+Shift+9 move container to workspace number $ws9
bindsym $mod+Shift+0 move container to workspace number $ws10

##-- Rules -------------------------------
#assign [app_id="foot"] → workspace number 1
#assign [class="firefox"] → workspace number 2
#assign [app_id="thunar"] → workspace number 3
#assign [app_id="geany"] → workspace number 4

for_window [window_role="pop-up"] floating enable
for_window [window_role="Steam"] floating enable
for_window [window_role="Motrix"] floating enable
for_window [window_role="task_dialog"] floating enable
for_window [app_id="alacritty-float|foot-float"] floating enable
for_window [app_id="yad|nm-connection-editor|pavucontrol"] floating enable
for_window [app_id="xfce-polkit|kvantummanager|qt5ct"] floating enable
for_window [app_id="io.calamares.calamares"] floating enable
for_window [title="Archcraft Installer"] floating enable
for_window [class="Yad|feh|Viewnior|Gpicview|Gimp|MPlayer|steam|Steam|steamwebhelper|etcher|goverlay|photoshop.exe|illustrator.exe|motrix|Motrix|timeshift|Timeshift|Pavucontrol|qt5ct|Blueberry.py|Bluetooth-sendto|kdeconnect.app|walc|UPlay@Arch|GStreamer"] floating enable
for_window [class="VirtualBox Manager|qemu|Qemu-system-x86_64"] floating enable
for_window [class="UPlay@Arch"] resize set 450 960
##-- Misc --------------------------------
include /etc/sway/config.d/*

**Comment by firashacker** [comment]
note i don't use archcraft i use the config on vanilla arch , and every thing was working fine before alacritty migration to TOML

**Comment by firashacker** [comment]
oh i just found a solution which is adding
for_window [app_id="alacritty-float|foot-float"] resize set bla blaa

to the sway config file and now it works i just need to find the right dimension for the alacritty window thank you all i'm closing this issue :)

**Comment by firashacker** [comment]
:)

**Comment by kchibisov** [comment]
Issue is a duplicate of #7474 since the root cause was the same for both. I've already fixed it *upstream* so should be fine with the next patch release.

I wasn't able to repro the dimensions stuff though, but the issue was that `dimensions` were not working at all with `0.13.0` from the config.
