### ISSUE TITLE
Why do I need to manually modify a bunch of settings in my config file that were working fine?

### ISSUE THREAD

**Issue by indeedwatson** [alacritty/alacritty#7505]
For example I had 2 themes defined in my config file, one dark and one light. I just upgraded alacritty and every instance I open it complains about `Unused config key: schemes`.

Why am I being asked as a user to spend my time taking care of this now?

**Comment by kchibisov** [comment]
You can comment theme you don't use out, or just put in the import file and import the one you need when you want so.

Why should we deal with non-working configs and configs with questionable source, when we can say that field doesn't exist.

**Comment by kchibisov** [comment]
And you don't have to modify anything yourself if you were not abusing yaml anchors which multiple themes in the same config were about.

**Comment by indeedwatson** [comment]
> You can comment theme you don't use out, or just put in the import file and import the one you need when you want so.
> 
> Why should we deal with non-working configs and configs with questionable source, when we can say that field doesn't exist.

I don't understand what you had to deal with? I had a config that was working. Now I have a warning. I didn't do anything to prompt this change. The config is in my computer, you don't need to deal with it, you just need to not break backwards compatibility unless there's a really good reason for it, imo.

**Comment by kchibisov** [comment]
We can break config if we see a need for it before `1.0`, I still don't see an issue with commenting out fields you don't use.

![image](https://github.com/alacritty/alacritty/assets/27620401/74521b2c-b7b5-406f-813b-33b9ce018de1)

**Comment by indeedwatson** [comment]
The issue is that software exists to solve problems.

Think of the user: there was no problem. Now there is one. The software has created a problem where there wasn't one, and now the user is asked to solve a problem that the software created.

Software is doing the opposite of what is meant to do.

At this point I'm considering just trying out another terminal: if I have to invest time solving something, I might as well invest that time learning a new program that won't ask that I re-do my config in the future.

**Comment by kchibisov** [comment]
>Think of the user: there was no problem. Now there is one. The software has created a problem where there wasn't one, and now the user is asked to solve a problem that the software created.

This is your judgement, now take my judgement where I spend time to address unused keys in the users configs. Why software shouldn't provide a butter UX for the user to handle their typos saving their and our time from such thing.

>At this point I'm considering just trying out another terminal: if I have to invest time solving something, I might as well invest that time learning a new program that won't ask that I re-do my config in the future.

You're free to use whatever you like and suits you.

**Comment by indeedwatson** [comment]
> This is your judgement, now take my judgement where I spend time to address unused keys in the users configs. Why software shouldn't provide a butter UX for the user to handle their typos saving their and our time from such thing.

To have done nothing, and to open up a terminal and receive a warning telling the user they need to invest energy and time solving an issue that wasn't there before, that is not a better UX, on the contrary.

Imagine unlocking your phone, and having a big warning on screen about how you *need* to switch your clock to 24h format. AM/PM was working fine for you, why should the clock pester you to solve an issue that previously didn't exist?

**Comment by kchibisov** [comment]
@indeedwatson surely we just flip things because we want and not because we're frustrated to fix broken yaml files each day, and given how many files were broken prior migration and never worked with arbitrary settings, like path to font files, and configs generated by AI that doesn't make any sense, just wasting our time in the end, because users strongly believe that their configs are correct.

It would take you 10 seconds to just copy your color scheme to a different file and just `import` it when you need it, yet you try to just call out how bad we are for trying to make _our_ life a bit easier when supporting users who decided to use alacritty. No one sells you anything, no one forces you to use alacritty, just use whatever you'd like or if you care, just develop things you use yourself.

**Comment by indeedwatson** [comment]
Again, my config lives in my computer and it was working, there was 0 cost to you. It's like if you gifted me a table, and then you came into my house to tell me how I should use a coaster because *other people* sometimes complain about glass stains.

I have a script to switch between dark/light mode so it would take more than 10 seconds.

For now I guess I'll just stick to the older version of alacritty.

Thanks for the responses and I'm sorry if you don't appreciate the user feedback.

**Comment by metalelf0** [comment]
@indeedwatson as @kchibisov already said, you shouldn't expect this kind of granted-backwards compatibility from a software whose version is 0.x. It's totally reasonable for the devs to break things, change config options, and so on. If you choose such a software, it's up to you to invest the time to adapt your config to the new requirements, if you want to upgrade.

Nobody is forcing you to do anything. You could also stay on 0.12.x if this suits your needs better. My suggestion however would be to take the time and adapt your config. In the spirit of open source and open collaboration, you could also give back something to the community by replying and telling others what you did to fix the issue you're facing, or send a PR to improve documentation if you think anything is lacking.

Have a great time and a happy new year!

**Comment by indeedwatson** [comment]
> you could also give back something to the community by replying and telling others what you did to fix the issue you're facing

the issue I'm facing is the UX nuisance of being asked to solve a problem I did not created. My attempt at a solution for other users who might face such an issue was to provide feedback and perspective. Sometimes developers get lost in the code and one has to wonder if the purpose is the code itself or the users.

I will stay on 0.12, I can't see a reason to upgrade.

**Comment by renxzen** [comment]
> the issue I'm facing is the UX nuisance of being asked to solve a problem I did not create. My attempt at a solution for other users who might face such an issue was to provide feedback and perspective. Sometimes developers get lost in the code and one has to wonder if the purpose is the code itself or the users.

There is already a solution for this drawback provided by the team which is running `alacritty migrate`. Anyways, i think the implementation of toml instead of yaml has far more advantages for everyone and also future development. They are thinking about the users, but you have to realize we are basically **beta testers** and not users yet. 

Thank you maintainers for your amazing job.
