### ISSUE TITLE
[WARN] for unused config key : history and multiplier 

### ISSUE THREAD

**Issue by who-sam** [alacritty/alacritty#7507]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux(Arch)
Version: `alacritty 0.13.0` 
Linux/BSD:  qtile

### Logs
always showing [WARN] for unused config key : history and multiplier 
either i'm putting them in the .toml file or not

**Comment by chrisduerr** [comment]
Your config is broken. TOML just started highlighting unused keys, it didn't work before either.
