### ISSUE TITLE
Missing config.toml in release assets?

### ISSUE THREAD

**Issue by fuzzybear3** [alacritty/alacritty#7508]
for version 0.13.0.
![image](https://github.com/alacritty/alacritty/assets/18566094/e55f7247-b96a-4f71-9952-d90462448715)

**Comment by chrisduerr** [comment]
Nope, everything there that should be there.

**Comment by fuzzybear3** [comment]
> Nope, everything there that should be there.

Thanks for getting back to me.
So is the plan to not have example `alacritty.toml` files for each release like it was done for `alacritty.yml`?
If that is the case I would not expect the readme to point to outdated config examples.
I may just be dumb and have unreasonable expectations:/

Anyway, love alacritty, thanks for your work on it:)

**Comment by kchibisov** [comment]
See the image there https://github.com/alacritty/alacritty/issues/7479#issuecomment-1871223493
