### ISSUE TITLE
Crashes on startup on 0.13.0 Arch

### ISSUE THREAD

**Issue by Heiwa03** [alacritty/alacritty#7512]
Fresh install through archinstall script. No configs, no nothing. Just crashes instantly like this. I do have `libxkbcommon` installed. 
Downgraded to 0.12.3 and it works absolutely fine.
### System

OS: Arch Linux 6.1.69-1-lts
Version: alacritty 0.13.0 (78fa4d6f)
Linux/BSD: X11, bspwm

### Logs
```
thread 'main' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xkbcommon-dl-0.4.1/src/x11.rs:59:28:
Library libxkbcommon-x11.so could not be loaded.
stack backtrace:
   0:     0x556f11f150c1 - <unknown>
   1:     0x556f11dda39c - <unknown>
   2:     0x556f11f1131d - <unknown>
   3:     0x556f11f14ea5 - <unknown>
   4:     0x556f11f165b3 - <unknown>
   5:     0x556f11f16302 - <unknown>
   6:     0x556f11f16a9b - <unknown>
   7:     0x556f11f1699e - <unknown>
   8:     0x556f11f155a6 - <unknown>
   9:     0x556f11f16742 - <unknown>
  10:     0x556f11b3aaa5 - <unknown>
  11:     0x556f11b3aa63 - <unknown>
  12:     0x556f120f2680 - <unknown>
  13:     0x556f1206fdc8 - <unknown>
  14:     0x556f11e2844d - <unknown>
  15:     0x556f11b4e4a2 - <unknown>
  16:     0x556f12050eae - <unknown>
  17:     0x556f11bc7567 - <unknown>
  18:     0x556f11c8f17c - <unknown>
  19:     0x556f11c9c583 - <unknown>
  20:     0x556f11c6e669 - <unknown>
  21:     0x556f11f0aa5f - <unknown>
  22:     0x556f11c9896c - <unknown>
  23:     0x7fc0af8efcd0 - <unknown>
  24:     0x7fc0af8efd8a - __libc_start_main
  25:     0x556f11b52105 - <unknown>
  26:                0x0 - <unknown>

```

**Comment by kchibisov** [comment]
Do you have the library named like the one we want to load? Could you also run `sudo ldconfig`? It's clearly just a missing dependency, it does look like a missing runtime dependency.

Was it installed via `pacman` as well, and not via something like `nix`?

**Comment by willtse** [comment]
After I upgraded my Archlinux today, I encountered the same issue  and I temporarily resolved it using this：

```shell
sudo pacman -S libxkbcommon-x11 # not libxkbcommon
```

**Comment by chrisduerr** [comment]
I'm on an up to date X11 Arch system and can't reproduce this. Please make sure your system is fully up to date and you didn't accidentally perform a partial update.

**Comment by willtse** [comment]
> After I upgraded my Archlinux today, I encountered the same issue and I temporarily resolved it using this：
> 
> ```shell
> sudo pacman -S libxkbcommon-x11 # not libxkbcommon
> ```

It seems that the `libxkbcommon-x11` package is not required before version 0.13.0, but it is required in version 0.13.0. ？However, my Arch system does not have the `libxkbcommon-x11` package, so this error occurs ?

**Comment by notgull** [comment]
Yes, the `libxkbcommon-x11` package is necessary for the newest Alacritty version.

**Comment by chrisduerr** [comment]
`libxkbcommon-x11` is required by `i3-wm`. I'm surprised it's not required by `bspwm`.

**Comment by willtse** [comment]
> `libxkbcommon-x11` is required by `i3-wm`. I'm surprised it's not required by `bspwm`.

I use dwm build from source 😅

**Comment by Heiwa03** [comment]
> `libxkbcommon-x11` is required by `i3-wm`. I'm surprised it's not required by `bspwm`.
It should probably be marked as a dependency since this was the issue. pacman does not install it as a dependency.

**Comment by kchibisov** [comment]
>It should probably be marked as a dependency since this was the issue. pacman does not install it as a dependency.

report this to Arch maintainer of the package.
