### ISSUE TITLE
fcitx preedit text display lags one update behind

### ISSUE THREAD

**Issue by shmibs** [alacritty/alacritty#7514]
### description

typing with fcitx, the on-the-spot / preedit preview lags one update behind. so if i type てすてす it's like

| input | shown | should show |
| ----- | ----- | ----------- |
| t     |       | t           |
| te    | t     | て          |
| tes   | て    | てs         |
| tesu  | てs   | てす        |

https://github.com/alacritty/alacritty/assets/2358713/558646a1-963d-4365-a411-e8a952c8759d

previous 0.12.3 hasn't got this issue, all else equal

### system

OS: Linux/X11
Version: alacritty 0.13.0 (78fa4d6f)

**Comment by kchibisov** [comment]
Could you provide `--print-events` while reproducing it?

**Comment by shmibs** [comment]
sure!


https://github.com/alacritty/alacritty/assets/2358713/b1ab458b-5075-49c8-8c27-33c4e36fa9bd

**Comment by kchibisov** [comment]
output usually means that you provide some file along the way, anyway, this should fix it

```diff
diff --git a/alacritty/Cargo.toml b/alacritty/Cargo.toml
index ad732cfd..194d2898 100644
--- a/alacritty/Cargo.toml
+++ b/alacritty/Cargo.toml
@@ -39,7 +39,7 @@ serde_json = "1"
 serde_yaml = "0.9.25"
 toml = "0.8.2"
 unicode-width = "0.1"
-winit = { version = "0.29.7", default-features = false, features = ["rwh_05", "serde"] }
+winit = { git = "https://github.com/kchibisov/winit", branch = "x11-fix-ime-lagging-behind", default-features = false, features = ["rwh_05", "serde"] }

 [build-dependencies]
 gl_generator = "0.14.0"

```

**Comment by shmibs** [comment]
oh, sorry! thought this could make sense for something time-sensitive...

but yes, it works 👍
