### ISSUE TITLE
Alt key bindings partially broken in 0.13

### ISSUE THREAD

**Issue by pejax** [alacritty/alacritty#7516]
I am using an ANSI keyboard in macOS 14 which allows typing German Umlauts with a lead-in character Alt-U:
Alt-U+a yields -> ä 
Alt-U+O yields -> Ö
etc.

To make this work I created these key_bindings on Alacritty. 0.12:
key_bindings:
```
# alacritty.yaml
  - { key: U,      mods: Alt,           chars:   "\x1bu" }
  - { key: S,      mods: Alt,           chars:   "ß" }
```

The key bindings have been merged by 'alacritty migrate' to:
```
# alacritty.toml
[[keyboard.bindings]]
chars = "\u001Bu"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
chars = "ß"
key = "S"
mods = "Alt"
```

The 'ß' mapping works but the Umlauts mapping with the Unicode character does not work. The mapping looks correct to me - any idea why it does not work or a workaround?

### System

OS: macOS
Version: `alacritty --version` 0.14.0-dev

Thanks

**Comment by chrisduerr** [comment]
Are you saying that this worked with 0.12?

**Comment by pejax** [comment]
Yes it did with the key_bindings setting in alacritty.yml:
```
key_bindings:
  - { key: U,      mods: Alt,           chars:   "\x1bu" }
```
Within Alacritty 0.14.0-dev the cursor turns into a block cursor and hangs.

**Comment by kchibisov** [comment]
should be fixed on master.

**Comment by pejax** [comment]
I tried the latest master - it is not fixed for me.

**Comment by kchibisov** [comment]
Well, the binding should be triggered correctly though. You can check `alacritty --print-events` and look for `key_without_modifier`, that's what will be used in bindings using `Alt` on macOS.

**Comment by pejax** [comment]
I do not understand the problem. Alacritty merge converted
alacritty.yml
```
key_bindings:
  - { key: U,      mods: Alt,           chars:   "\x1bu" }
```
to alacritty.toml
```
[[keyboard.bindings]]
chars = "\u001Bu"
key = "U"
mods = "Alt"
```
The chars field is now unicode but it looks correct - it should send ESC-U. I also tried the old chars format "\x1bu" but hexadecimal does not seem to be supported anymore.

**Comment by kchibisov** [comment]
I mean the bindings got converted correctly, and I don't see why they shouldn't work and I also not sure where you test them.

**Comment by kchibisov** [comment]
Ah, I see the issue, it enters compose mode, thus input is hidden.

You may want to use so it won't try to compose...

```
[window]
option_as_alt = "OnlyLeft"
```

**Comment by pejax** [comment]
I already use this option (also in 0.12) - otherwise it would have never worked.

The most severe changes from 0.12 to 0.13 is the transition to toml configuration. So I suspect that merging the mapped chars from "\x1bu" (yaml) to "\u001bu" (toml) is the problem. Maybe macOS cannot handle the unicode Escape character.

I actually want this, but I get a TOML parse error:
```
[[keyboard.bindings]]
chars = "\x1Bu"
key = "U"
mods = "Alt"
```
How do I force mapping to plain binary Escape+U like with Alacritty 0.12?

**Comment by kchibisov** [comment]
But then you should not have compose? Like `option_as_alt` should prevent you from even entering umlauts. There's nothing about toml at all, like if `option_as_alt` doesn't make you incapable to type unlauts, then it's not really working.

Like if you run `alacritty --config-file /dev/null -o 'window.option_as_alt="Both"'` then press `Alt + u` it should produce `ESC + U` automatically without anything extra, as well as allow you to bind, because the key is delivered via standard compose interface and not via IME edit.

**Comment by pejax** [comment]
I removed the Alt-U key binding and the window.option_as_alt and it works as expected. I have no idea why I (had to?) put it into the 0.12 configuration file.

Thanks for the hints and your patience :-)
