### ISSUE TITLE
Setting window position from CLI works only for one axis

### ISSUE THREAD

**Issue by sudo-nice** [alacritty/alacritty#7518]
Upgrading from alacritty 0.12 I found myself unable to set *both* `x` and `y` positions from CLI, but I can set either *one*. Examples:

```
# This command applies only `x=444` option and ignores `y=333` option:
alacritty -o window.position.y=333 window.position.x=444

# This command applies only `y=333` option and ignores `x=444` option:
alacritty -o window.position.x=444 window.position.y=333
```
It feels like a latter position drops the former one.

Interestingly, if I set both `x` and `y` in the alacritty.toml and run alacritty with neither `x` nor `y` specified from the CLI, then both positions get applied correctly.

https://github.com/alacritty/alacritty/issues/7267 is possibly related.

### System

OS: Debian
Version: alacritty 0.13.0
Linux: X11, BSPWM

**Comment by chrisduerr** [comment]
Can you try `"window.position={ x = 333, y = 444 }"`?

**Comment by sudo-nice** [comment]
It works fine that way, thank you.
/

**Comment by chrisduerr** [comment]
Since position is a `Delta` it's deserialized directly and doesn't benefit from our abstractions which allow overriding. Not a huge deal, but might be nice to look into a workaround. Since it's defined in Alacritty it should be fixable without too many issues.

**Comment by sudo-nice** [comment]
I'm afraid I was too fast to report it working. The method you suggested works fine when I run it in a shell indeed, but when I try to run it via my hotkey daemon (`sxhkd`, namely), neither `x`, nor `y` position don't work anymore (no matter if set both at once, or each separately).

**Comment by kchibisov** [comment]
>I'm afraid I was too fast to report it working. The method you suggested works fine when I run it in a shell indeed, but when I try to run it via my hotkey daemon (sxhkd, namely), neither x, nor y position don't work anymore (no matter if set both at once, or each separately).

that's different issue though if they don't work at all.

**Comment by kchibisov** [comment]
>Since position is a Delta it's deserialized directly and doesn't benefit from our abstractions which allow overriding. Not a huge deal, but might be nice to look into a workaround. Since it's defined in Alacritty it should be fixable without too many issues.

maybe we can accumulate cli options and then apply the end union of all that was passed at once?

**Comment by chrisduerr** [comment]
> maybe we can accumulate cli options and then apply the end union of all that was passed at once?

That would probably work as a backup. But even incrementally these shouldn't override each other. Otherwise we might not support overriding just one when they're defined in the config.

**Comment by kchibisov** [comment]
I mean, union is what it's all about? because same options later should purge previous, but different will just merge.
