### ISSUE TITLE
title is not export for htop, nvim or fish

### ISSUE THREAD

**Issue by tkkcc** [alacritty/alacritty#7521]
Env: archlinux, x11, i3wm, alacritty 0.13 or 2786683(installed via package manager)

When I listing window titles for quick switching, I found all alacritty windows are "Alacritty", while other terminals can export the command running inside.

To reproduce: (avoid user config, avoid shell warpper)
```sh
/usr/bin/alacritty --config-file /dev/null -e nvim
```
Then point `xprop` to this nvim window. There is no "nvim" text.

![image](https://github.com/alacritty/alacritty/assets/17373509/c04de665-e999-4d1a-b769-0839e087e55f)

If I use kitty, There is "nvim"

![image](https://github.com/alacritty/alacritty/assets/17373509/538d81e5-e52f-4a49-8514-fe4a455d0508)

`htop`, `fish` and `nvim` all can't export title in alacrity. But `bash` can.

**Comment by kchibisov** [comment]
it's up to program you run inside to set its title. Usually it's a shell job before running the command.

That's an example how to do it in zsh.

https://git.sr.ht/~kchibisov/dotfiles/tree/main/item/.zsh/functions/title.zsh
