### ISSUE TITLE
Alacritty migrate fails

### ISSUE THREAD

**Issue by spikeyamk** [alacritty/alacritty#7525]
Yesterday, I updated alacritty and running `$ alacritty migrate` gives me this error:
```
Configuration file migration failed:
    "/home/spikeyamk/.config/alacritty/alacritty.yml": parsing error: Yaml conversion error: unsupported unit type
```
### System

OS: Arch Linux
Version: `alacritty 0.13.0 (78fa4d6f)`
Linux/BSD: GNOME X11

### Logs
```
$ cat /tmp/Alacritty-8260.log
[0.000045200s] [WARN ] [alacritty] YAML config "/home/spikeyamk/.config/alacritty/alacritty.yml" is deprecated, please migrate to TOML using `alacritty migrate`
[0.000292903s] [ERROR] [alacritty_config_derive] Unable to load config "/home/spikeyamk/.config/alacritty/alacritty.yml": Yaml conversion error: unsupported unit type
```

My config file here:
[alacritty.txt](https://github.com/alacritty/alacritty/files/13805234/alacritty.txt)

What do?

**Comment by chrisduerr** [comment]
Your original config is broken.

**Comment by lachlankrautz** [comment]
Error message is not helpful. 
I've been using my config for years without issue. Now the migration to toml fails. It seems more that the migraiton is stricter than the old alacritty. 
It's impossible for the user to know where the issue is.

**Comment by kchibisov** [comment]
YAML tends to ignore all sort of errors and doesn't warn really about anything, thus if you have weird sections, like

```yaml
window:
dimensions:
something:
x = 0
```

it'll work fine, but the config itself is broken, it's just more tolerant towards errors.

It's all in the context of unit type stuff.

Some configs were using options literally that never existed before in alacritty, which should warn now.

The migrate is stricter in a way that it translates `correct yaml to correct toml`, broken yaml/weird yaml won't be translated correctly, because toml has less features, so it can't be translated 1 to 1.

**Comment by chrisduerr** [comment]
> It's impossible for the user to know where the issue is.

Considering I'm able to tell immediately what's wrong with your config, that's clearly a PEBCAK issue.

**Comment by dinotheextinct** [comment]
> > It's impossible for the user to know where the issue is.
> 
> Considering I'm able to tell immediately what's wrong with your config, that's clearly a PEBCAK issue.

Are you the maintainer? I mean what kind of bullshit response is this? The error message is garbage.

**Comment by kchibisov** [comment]
@dinotheextinct the said issue with nulls is resolved, I'm not sure what's your issue.

**Comment by dinotheextinct** [comment]
```
 File: /tmp/Alacritty-30166.log

   1   │ [0.000059020s] [WARN ] [alacritty] YAML config "/home/dino/.config/alacritty/alacritty.yml" is deprecated, please migrate to TOML using `alacritty migrate`
   2   │ [0.000243461s] [ERROR] [alacritty_config_derive] Unable to load config "/home/dino/.config/alacritty/alacritty.yml": Yaml conversion error: unsupported unit type
```

**Comment by kchibisov** [comment]
you need 0.13.1.

**Comment by dinotheextinct** [comment]
> you need 0.13.1.

Finally got the update on tumbleweed and no migrate works. Thanks.
