### ISSUE TITLE
License MIT

### ISSUE THREAD

**Issue by dcampbell24** [alacritty/alacritty#7530]
The READMME.md file mentions the Apache license, but doesn't mention the MIT license even though there is a MIT license file. The MIT license file doesn't contain the header line "Copyright (c) year authors". The alacrityy directory cargo.toml says "license = "Apache-2.0". Do you allow this library to be distributed under the MIT license or not? If not, I suggest removing the file LICENSE-MIT.

**Comment by kchibisov** [comment]
>The READMME.md file mentions the Apache license, but doesn't mention the MIT license even though there is a MIT license file. The MIT license file doesn't contain the header line "Copyright (c) year authors". The alacrityy directory cargo.toml says "license = "Apache-2.0". Do you allow this library to be distributed under the MIT license or not? If not, I suggest removing the file LICENSE-MIT.

no, it's only Apache

alacritty repo has 4 crates, all config crates are dual licensed, each crate has proper license symlinks you you look into how they are used.

**Comment by dcampbell24** [comment]
Why not put the actual license file in the relevant directories and include the header line? It is a bit confusing to have symlinks and you end up having a license file in a directory it does not apply to.  Also, it might be strange to have symlinks of the Apache license which does include the attribution lines. Then it begs the question do those attribution lines apply to all of the crates?

I am not a lawyer so I don't know how much this matters, but it is the thought I had.

**Comment by chrisduerr** [comment]
> It is a bit confusing to have symlinks

Symlinks are no more confusing than any other file.

> you end up having a license file in a directory it does not apply to.

Which directories the license files are in is completely irrelevant. The individual crates clearly document their licenses in the `Cargo.toml` file.

> Then it begs the question do those attribution lines apply to all of the crates?

Multi-license means you can freely choose which of the two licenses you want to use.
