### ISSUE TITLE
How to  use alacritty 0.13.0  config blink_interval 

### ISSUE THREAD

**Issue by wo2ni** [alacritty/alacritty#7531]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux/BSD/macOS/Windows
Version: `alacritty --version` output
Linux/BSD: X11/Wayland, DE or Compositor and WM

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by kchibisov** [comment]
![image](https://github.com/alacritty/alacritty/assets/27620401/003e7048-daaf-4f42-83dc-b434fe515525)
