### ISSUE TITLE
Inability to Scroll Beyond First Line in Vim Mode on Alacritty Terminal (with tmux)

### ISSUE THREAD

**Issue by shreyanshdeb** [alacritty/alacritty#7535]
Using default config.

1. Open alacritty.
2. Attach to a tmux session.
3. Generate some large output
4. Enter vim mode (Shift+Cmd+Space)
5. Try to scroll up with 'hjkl' or 'gg'

**Expected**: I expect the cursor to move beyond the first line, allowing me to view the entire data in the terminal.
**Actual**: The cursor does not extend beyond the first line of the current view, preventing me from accessing the entire data

Additionally, scrolling with the scroll wheel doesn't function while in Vim mode, although it works outside of Vim mode.

Please note, scrolling is working as expected outside tmux.

### System

OS: macOS 14.2.1
Version: alacritty 0.13.0 (78fa4d6)

**Comment by kchibisov** [comment]
alt screen has no scrollback, tmux is your terminal, thus you should use its keyboard mode.
