### ISSUE TITLE
Warning re unused imports

### ISSUE THREAD

**Issue by andrewbernard** [alacritty/alacritty#7540]
On both Raspberry Pi Manjaro Arm and Ubuntu 23.10 if I add an import line to the alacritty.toml file I get the warning discussed in issue #7321. I do not see that this has been fixed.

**Comment by kchibisov** [comment]
could you show which warning do you get?

**Comment by andrewbernard** [comment]
For example:

[WARN] See log at /tmp/Alacritty-245349.log ($ALACRITTY_LOG):
Unused config key: import

**Comment by kchibisov** [comment]
I'm not sure how you define it, but you should put it at the top of the file, so it doesn't stick to other sections. See `man 5 alacritty` for example.

**Comment by andrewbernard** [comment]
Thanks so much. That does indeed work of course.

That is not entirely clear in man 5 alacritty. I wonder if we should add a comment to that page?
