### ISSUE TITLE
Any plans to have Wgpu support and have OpenGL as a fallback?

### ISSUE THREAD

**Issue by Oglo12** [alacritty/alacritty#7548]
Hi, this isn't exactly a tipical issue, but I was wondering if something more modern like Vulkan/Wgpu was in the works?
Vulkan/Wgpu is way faster than OpenGL, and also Wgpu is completely written in Rust! I think it would be amazing to use a terminal emulator made with Wgpu! It would also put an end to the Kitty vs Alacritty debate. XD

The reason I wrote this issue is because Cava when zoomed out all the way has some flickering, and I think it is because it is a lot to process visually. I feel as if Wgpu would fix this issue almost entirely!

**Comment by kchibisov** [comment]
>Hi, this isn't exactly a tipical issue, but I was wondering if something more modern like Vulkan/Wgpu was in the works? Vulkan/Wgpu is way faster than OpenGL

It's not a matter of being faster, it's a matter of having stable support. alacritty offers support for mostly all hardware (we support OpenGL ES 2.0 without any extensions).

> It would also put an end to the Kitty vs Alacritty debate. XD

This has nothing to do with it. Terminals are just different and follow different goals. We also don't compete with anyone.

>The reason I wrote this issue is because Cava when zoomed out all the way has some flickering, and I think it is because it is a lot to process visually. I feel as if Wgpu would fix this issue almost entirely!

That's won't really do it, what will do is using sync udpates, which both alacritty and kitty support, so the frames are updated atomically, thus you won't have flickering.

In general, I'm interested to have alternative renderer using wgpu for macOS/Windows and maybe some X11 systems, however wgpu is lacking a lot of features we need on linux (buffer age, swap buffers with damage, etc), that we have with OpenGL, but they are sort of aware.

**Comment by jokeyrhyme** [comment]
see: https://github.com/alacritty/alacritty/issues/183
