### ISSUE TITLE
CTRL + h emits backspace in vim insert mode

### ISSUE THREAD

**Issue by jacknicklenson** [alacritty/alacritty#7551]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Windows
Version: `alacritty 0.13.0 (78fa4d6)`

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

I mapped my `<C-h>` keybinding to `<left>` in vim insert mode like this `inoremap <C-h> <Left>` which works as expected in windows terminal. However, in alacritty it always removes character like backspace. When I in insert mode and i type `ctrl + v` and `ctrl + h`, it emits `<C-BS>` which it shouldn't.

**Comment by kchibisov** [comment]
`C-h` is a backspace(it's how it's is) unless kitty keyboard protocol is in use, which may work when you plug different conpty.dll/openconsole.exe. windows terminal is bundling their own conpty.dll and openconsole.exe, thus it may work for them and not for us.

To make it work in alacritty you'd need to place more recent conpty.dll and openconsole.exe next to alacritty binary or in the path. You can verify that they are loaded via the `alacritty -vv`, it should tell which `conpty` provider is used.
