### ISSUE TITLE
render behavior wired on unicode 

### ISSUE THREAD

**Issue by glepnir** [alacritty/alacritty#7552]
the unicode symbol render wired. it's not in center.

![image](https://github.com/alacritty/alacritty/assets/41671631/82aa9c13-23af-480f-bd35-2a399cfab452)

### System

OS: Archlinux
Version: 0.13.0
Linux/BSD: Hyprland

### Logs
no crash

**Comment by kchibisov** [comment]
Seems like this glyph is not comming from the monospace font in the first place, thus its position is not desired.

You can just with `alacritty -vvv | grep crossfont` and see which font is being used to draw this symbol.

**Comment by glepnir** [comment]
i use nerd symbol only fonts for render these symbols. at least it works fine on kitty wezterm etc.

**Comment by kchibisov** [comment]
We use font metrics to position the glyphs and we don't try to _center_ them in the font. If you want correctly aligned symbols in the terminal use specific fonts, like `Iosevka Term`.

**Comment by glepnir** [comment]
emmm i use normal font for coding just use nerd symbols only for symbols . i dont think it can be solve by using other font like you said Iosevka Term. wezterm builtin nerd symbols only and kitty config symbol map . both works fine.

**Comment by JiuRanYa** [comment]
Same behavior
