### ISSUE TITLE
[Feature Request] allow support for font-files, rather then system fonts

### ISSUE THREAD

**Issue by terefang** [alacritty/alacritty#7555]
# use-case

portable "non-installations" in restricted environments that do not allow the user to install fonts.

## config format

my proposal for the config format would be:

```toml
[font]
normal = { file = "<path/to/file>" }
italic = { file = "<path/to/file>" }
```

## path format

the path to file should be one of the following:

* full path starting with "/" (what would be the solution for windows paths like Y:\... ?)
* path from home directory starting with "~/."
* path relative to the config file starting with "./"

## font formats to support

since alacritty already uses freetype, the following font formats could be supported:

* TrueType – .ttf
* OpenType – .otf
* OpenType Bitmap – .otb
* X11/Adobe Glyph Bitmap Distribution Format – .bdf
* X11 Portable Compiled Format – .pcf

**Comment by chrisduerr** [comment]
That just sounds like a huge pain. I don't see how supporting this would be a good fit for Alacritty.

**Comment by kchibisov** [comment]
if you're on linux/bsd you can do that with fontconfig. I do so myself for example:

```
  <!-- Replace regular style with the medium one. -->
  <match target="font">
    <test name="family" compare="eq" ignore-blanks="true">
      <string>Fira Mono</string>
    </test>
    <test name="style">
      <string>Regular</string>
    </test>
    <edit name="file" mode="assign">
      <string>/usr/share/fonts/fira-mono/FiraMono-Medium.otf</string>
    </edit>
  </match>

```

**Comment by terefang** [comment]
but on windows (which is my primary use case) i am out of options.

**Comment by kchibisov** [comment]
Can't the font be installed just for the user on windows? It'll be strange if you can't do so.

**Comment by terefang** [comment]
my windows knowledge is 30 years old, and my target environment is even more limited (CITRIX)

**Comment by terefang** [comment]
does alacritty use fontconfig instead of freetype directly ?

**Comment by terefang** [comment]
oh ... looks like there as an abstraction library called crossfont

**Comment by kchibisov** [comment]
On Windows we're using direct write.

fontconfig is a library to find fonts and config options, but then you pass that to freetype. They are serving different purpose.

**Comment by terefang** [comment]
yes yes ... i know what ft and fc do.

anyhow ... ok i see the challenge now ... you dont use freetype on windows.

so it would not be a simple bypass fc and submit the font directly to ft ... my bad.
