### ISSUE TITLE
[Regression?] alacritty 0.13 has a bad initial zoom/font size, but would go away after toggling full screen.

### ISSUE THREAD

**Issue by adam900710** [alacritty/alacritty#7563]
If starting a new window, the fonts always seem incorrectly zoomed.

![Screenshot_20240104_081834](https://github.com/alacritty/alacritty/assets/460269/ee8c7989-ddd6-4670-9c17-d35713678a2b)

The left one is a new alacritty window, meanwhile the right one is created then toggled to fullscreen and back.
The font rendering is obviously incorrect on the left one.

### System

OS: Linux
Version: `alacritty 0.13.0 (78fa4d6f)`
Linux: Wayland, plasma-wayland-session

### Logs

[Alacritty-30113.log](https://github.com/alacritty/alacritty/files/13823746/Alacritty-30113.log)

**Comment by kchibisov** [comment]
Fixed on the latest master.
