### ISSUE TITLE
Rendering of "Mathematical Alphanumeric Symbols" unicode block on Windows

### ISSUE THREAD

**Issue by tpgillam** [alacritty/alacritty#7569]
When using Alacritty on Windows 11 with WSL, certain unicode points do not appear to render correctly.

All of the [Mathematical Alphanumeric Symbols](https://www.compart.com/en/unicode/block/U+1D400) symbols I have tried exhibit the behaviour below. For this issue I will use the following as an example:
- [MATHEMATICAL SCRIPT CAPITAL C](https://www.compart.com/en/unicode/U+1D49E), U+1D49E : 𝒞

### At shell
1. Open a new WSL shell in Alacritty.
2. Paste the problematic character, e.g. "𝒞"
3. I would expect the character to occupy one cell, and the cursor to move to the next cell. Instead the character appears with a white background, and the cursor appears shifted along, like so:
![image](https://github.com/alacritty/alacritty/assets/7052222/a7c7b01b-fcd6-454c-897d-fbb18586884a)
4. In case it is useful, if `<space>` is pressed, the output now looks like so:
![image](https://github.com/alacritty/alacritty/assets/7052222/9ab19657-719e-4ebb-a5bb-0d027ca37321)

### With text editor
I first encountered this issue in `vim`. Here the issue can be demonstrated as follows:
1. Open vim, and create two empty buffers
2. In the first buffer, paste the problematic character "𝒞"
![image](https://github.com/alacritty/alacritty/assets/7052222/3ba9ef63-1096-4bc8-bce2-59a3df9d958b)

3. Switch to the second buffer, and write _at least six_ characters, e.g. "abcdef"  (fewer than six characters does not exhibit the issue; more than six will result in the same outcome at the next step).
![image](https://github.com/alacritty/alacritty/assets/7052222/62490a54-3140-459b-a0e4-e7b3e25d9117)

4. Switch back to the first buffer. I would expect to see "𝒞" again, but instead I see "𝒞b"
![image](https://github.com/alacritty/alacritty/assets/7052222/9e06516b-d174-4a06-8a67-3290d6971d61)

## Other observations
- I see the same behaviour on 0.12 and 0.13 (to which I have just upgraded)
- The choice of font does not change the behaviour
- on MacOS, I do _not_ see any problems. I haven't tested Linux.
- Windows Terminal with WSL does not exhibit this behaviour.

### System

OS: Windows 11
Version: alacritty 0.13.0 (78fa4d6)

### Logs

Font/Terminal size: `alacritty -vv`
```
[0.000008500s] [INFO ] [alacritty] Welcome to Alacritty
[0.000534900s] [INFO ] [alacritty] Version 0.13.0 (78fa4d6)
[0.004839000s] [INFO ] [alacritty] Configuration files loaded from:
                                     "C:\\Users\\tom\\AppData\\Roaming\\alacritty\\alacritty.toml"
[0.026706900s] [INFO ] [alacritty] Window scale factor: 1
[0.132854500s] [INFO ] [alacritty] Using WGL
[0.133740200s] [DEBUG] [alacritty] Picked GL Config:
                                     buffer_type: Some(Rgb { r_size: 8, g_size: 8, b_size: 8 })
                                     alpha_size: 8
                                     num_samples: 0
                                     hardware_accelerated: true
                                     supports_transparency: Some(false)
                                     config_api: Api(OPENGL | GLES1 | GLES2)
                                     srgb_capable: true
[0.148909400s] [DEBUG] [alacritty] Loading "Consolas" font
[0.160756700s] [INFO ] [alacritty] Running on AMD Radeon(TM) 780M
[0.161012500s] [INFO ] [alacritty] OpenGL version 3.3.0 Core Profile Context 22.40.70.16.231017, shader_version 4.60
[0.161250700s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.226807800s] [DEBUG] [alacritty] Enabled debug logging for OpenGL
[0.227411300s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.229177500s] [INFO ] [alacritty] Cell size: 8 x 18
[0.229394500s] [INFO ] [alacritty] Padding: 0 x 0
[0.229564800s] [INFO ] [alacritty] Width: 800, Height: 600
[0.277355600s] [INFO ] [alacritty] PTY dimensions: 33 x 100
[0.278185700s] [INFO ] [alacritty_terminal] Using Windows API for pseudoconsole
[0.311099900s] [INFO ] [alacritty] Initialisation complete
```

**Comment by kchibisov** [comment]
sounds like conpty bug, you may try with recent conpty.dll and openconsole.exe placed next to alacritty binary.

**Comment by tpgillam** [comment]
Thanks -- those filenames led me to https://github.com/alacritty/alacritty/issues/7239, which has relevant discussion.

For anyone else that comes across this, the official github release didn't have `conpty.dll` bundled; so I built from source following the instructions in terminal github repository, and I can confirm the issue is resolved after following the steps as above.
