### ISSUE TITLE
Alacritty "Unable to loacate config file" after migrate to TOML

### ISSUE THREAD

**Issue by abc-mikey** [alacritty/alacritty#7576]
I tried migrating my global config file after getting a warning that YAML was deprecated in favour of TOML, with:

```
sudo alacritty migrate -c /etc/alacritty/alacritty.yml
```

This generated `/etc/alacritty/alacritty.toml` (644)  which looks correct, but after removing `/etc/alacritty/alacritty.yml` I now get an error:

```
[0.000005850s] [ERROR] [alacritty_config_derive] Unable to load config "/etc/alacritty/alacritty.yml": Unable to locate config file
```

### System

OS: Linux
Distro: OpenSUSE Tumbleweed
Version: 0.13.0
Linux: Wayland, Sway

**Comment by chrisduerr** [comment]
Yeah you're telling it somewhere to explicitly load the yaml file. `alacritty -vv` might help with that.
