### ISSUE TITLE
Option+left on macos outputs character code instead of jumping left

### ISSUE THREAD

**Issue by jost-s** [alacritty/alacritty#7585]
STR:
- Type several words separated by space or slash
- Press option+left

Expected:
Cursor jumps left to the next separator defined in `WORDCHARS` or

Actual:
`;3D` is appended to current line
`$ cmd param;3D`

option+backspace deletes until the next word character. Changing `option_as_alt` makes no difference and is not set for this example.

### System

OS: macOS 13.6
Version: alacritty 0.12.3

**Comment by chrisduerr** [comment]
Option + Left should send `^[1;3D`, so this is likely working as expected.

**Comment by jost-s** [comment]
Thanks for the comment. I would be grateful if that means that this kind of moving the cursor to wordchar stops must be done through custom key mappings in Alacritty then?

**Comment by kchibisov** [comment]
@jost-s you should bind the key in your shell if you want so, some terminals inject shell configs to make these bindings work. You should configure it in `.bashrc` or `.zshrc`.

This is for zsh

```
bindkey '^[[1;3C' forward-word
bindkey '^[[1;3D' backward-word

```

**Comment by jost-s** [comment]
@kchibisov Thank you for the explanation, understood! I can confirm that the macos terminal app is defining those bindings in the settings. I'll configure my zsh accordingly.
