### ISSUE TITLE
Alacritty-v0.13.1-installer.msi cannot update 0.13.0-rc2: a newer version is already installed

### ISSUE THREAD

**Issue by shygreyfield** [alacritty/alacritty#7591]
### System

OS: Windows
Version: alacritty 0.13.0-rc2 (b8acfda)

When I tried to update from 0.13.0-rc2 by Alacritty-v0.13.1-installer.msi I got the error with the message: "A newer version of Alacritty is already installed."

**Comment by kchibisov** [comment]
Maybe the msi versioning is broken and they can't compare things correctly? I'd suggest to uninstall what you have and install from scratch, it doesn't create any files besides putting exe in the right place so it doesn't matter...

**Comment by shygreyfield** [comment]
Do installation from scratch delete my configuration files?

**Comment by kchibisov** [comment]
No, we don't touch any configuration.

**Comment by shygreyfield** [comment]
Okay. I think it can be closed.
