### ISSUE TITLE
Warnings when using OS-specific keys on alternative OSes

### ISSUE THREAD

**Issue by typhoon2099** [alacritty/alacritty#7592]
### System

OS: Linux/macOS
Version: alacritty 0.14.0-dev
Linux/BSD: X11/i3WM

I share my Alacritty config between my work Mac and my personal laptop. I've recently migrated my config to TOML and I now see a warning about unused keys for `option_as_alt`. This is a valid key on Mac OS, but not on Linux, so I'm receiving the warning only on Linux.

Is there a way to suppress this warning?

**Comment by kchibisov** [comment]
Use imports (and symlink needed os specific config) or git.

**Comment by typhoon2099** [comment]
Looks like I can set `debug.log_level` to `Error` to suppress them (which saves me having to manage multiple co fog files).
