### ISSUE TITLE
three consecutive ctrl-c presses will exit Alacritty

### ISSUE THREAD

**Issue by hardyoyo** [alacritty/alacritty#7599]
I have developed the habit of rapidly hitting ctrl-C to exit out of whatever command I want to exit out of... however, I have determined that this leads to Alacritty to exit completely. I've since tracked it down to three somewhat rapid presses of ctrl-C. Most other terminal emulators are tolerant of this, which is how I've managed to develop the habit.

I can eventually learn other habits. But... this one seems harmless enough, and I don't think the behavior is intentional.

### System

OS: macOS
Version: `alacritty --version`: alacritty 0.12.2 (9d9982d)
Linux/BSD: n/a

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by chrisduerr** [comment]
This would be up to your shell, there's nothing that would cause Alacritty to exit because of pressing ^C.

**Comment by hardyoyo** [comment]
You were right, I tracked this down to Powerbash, which I installed (and then modified) right after I installed Alacritty. Here's the bugfix I was running for Powerbash: https://github.com/napalm255/powerbash/pull/20 I've uninstalled Powerbash, and have switched to Starship (yay, more Rust) for a prompt kit. So far, so good, and now I can mash ctrl-C with abandon again. :-)
