### ISSUE TITLE
Version 13: Repeatedly asks "Alacritty" would like to access data from other apps

### ISSUE THREAD

**Issue by thecontinium** [alacritty/alacritty#7602]
Since version 13 every time Alacritty starts, permissions are requested: 
` "Alacritty" would like to access data from other apps appears.`
Even after pressing `Allow` it asks again when restarting

OS: macOS;14.2.1;23C71
Version: alacritty 0.13.1 (fe2a3c5)
Install: homebrew

**Comment by chrisduerr** [comment]
Downgrading to 0.12 fixes this?

**Comment by thecontinium** [comment]
This started happening when upgrading from 12 to 13.

**Comment by chrisduerr** [comment]
> I can downgrade and try 12 again if you think it will help find the issue ?

Yes please do this to confirm that it is an issue with version 0.13.

**Comment by thecontinium** [comment]
Reinstalling version 12 and the same issue happens. Using Terminal and the same issue happens. 
Rather than an issue with Alacritty this is behaviour that has been introduced by a MacOS upgrade and is probably specific to the zsh startup scripts that I am using.

**Comment by rafaelsmgomes** [comment]
Also having the same issue. 
Could it be that it wants to get access to the browser?

**Comment by kchibisov** [comment]
generally apple policy is that all of that applies to subprocess, so if you run e.g. browser or something accessing a particular resource it'll ask for permission. The same happens in e.g. apple terminal if you `find` from the `/` dir.
