### ISSUE TITLE
High CPU usage on various programs as well as on idle

### ISSUE THREAD

**Issue by 1over137** [alacritty/alacritty#7611]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Gentoo
Version: 1b9131c
Linux/BSD: X11/Wayland, DE or Compositor and WM
Hardware: Intel i7 1185G7, 4C 8T
### To reproduce
0. Install from master
1. Run `alacritty --config-file=/dev/null`
2. Open htop on another terminal
3. Open htop on the alacritty without config file
4. Observe that alacritty takes up a full cpu core nearly all the time
5. Other tests include `cat /dev/zero`, `yes`. Often times it takes up a full cpu core even without doing anything, just leaving the terminal idle. 
![image](https://github.com/alacritty/alacritty/assets/22680475/016702c6-38f7-495a-84b4-abf90e342750)

**Comment by kchibisov** [comment]
Can't repro, if you use `hyprland` ensure to use latest commit on it.

And also, at least provide basic logs requested to get any help and not get your issue closed.
