### ISSUE TITLE
High CPU load

### ISSUE THREAD

**Issue by romanstingler** [alacritty/alacritty#7612]
### System

OS: Linux
Version: alacritty 0.13.1 (fe2a3c56)
Linux: Wayland, Hyprland

 I have only 2 alacritty windows open one doing nothing and one with htop. 
These windows use a lot of CPU, does that happen also to you guys?
![image](https://github.com/alacritty/alacritty/assets/5576250/7d53af5f-651d-4209-9364-a965d43981be)

**Comment by kchibisov** [comment]
Update hyperland it's a bug in it iirc.
