### ISSUE TITLE
Sticky keys no longer working

### ISSUE THREAD

**Issue by roboalex123** [alacritty/alacritty#7613]
I rely on sticky keys to function. I updated yesterday and thought that sticky keys were broken system-wide, but I looked into it again today and realised that it is only inside alacritty that it no longer works. I use `xkbset` to enable sticky keys.

### System

OS: Linux/BSD/macOS/Windows
Version: alacritty 0.14.0-dev
Linux/BSD: X11, Ubuntu, i3, picom

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by kchibisov** [comment]
Could you tell me what you do with `xkbset` to enable them so I can try to repro?

**Comment by roboalex123** [comment]
I run the following commands:

xkbset exp =sticky
xkbset sticky -twokey -latchlock

**Comment by kchibisov** [comment]
Well, even on 0.13.1 I can't repro that and master and 0.13.1 shouldn't make any difference at all.
