### ISSUE TITLE
Alacritty 13.x `-o` option improperly merges config settings

### ISSUE THREAD

**Issue by awused** [alacritty/alacritty#7618]
When using -o to override config options, alacritty 13 doesn't properly merge the new values into the existing config. This is a regression in 13; it worked properly in 12.x.

### System

OS: Linux
Version: alacritty 0.13.1
Linux/BSD: X11

### Logs

My config contains
```
[env]
WINIT_X11_SCALE_FACTOR = "randr"
```

But when I run `alacritty -o env.TERM=\"xterm-256color\"` with alacritty 13.x, `WINIT_X11_SCALE_FACTOR` is not set from the config.

### Steps to reproduce:
```
# If running from an existing alacritty session, unset it so it isn't inherited
unset WINIT_X11_SCALE_FACTOR
alacritty -o env.TERM=\"xterm-256color\"
```
then run `echo $WINIT_X11_SCALE_FACTOR` in the new terminal and see an empty string.

If running `alacritty -o env.TERM=xterm-256color` with alacritty 12.x, it works as expected and both environment variables are properly set.

#### Working example:
```
# If running from an existing alacritty session, unset it so it isn't inherited
unset WINIT_X11_SCALE_FACTOR
alacritty
```
then run `echo $WINIT_X11_SCALE_FACTOR` in the new terminal and see `randr`, read fresh from the config.

**Comment by chrisduerr** [comment]
I'm not entirely sure how this worked before, but this should fix it: https://github.com/alacritty/alacritty/pull/7619.
