### ISSUE TITLE
How do SIGINT with Ctrl C and use Ctrl C for Copy? COPY OF "#3696"

### ISSUE THREAD

**Issue by aspauldingcode** [alacritty/alacritty#7622]
I am trying to use alacritty command + shift + c to trigger SIGINT command with chars = "\\x03"
It worked fine, until I updated alacritty to v13.
now, it tells me that it is an invalid escape sequence. 
if I replace it with "\x03", it just prints x03 to stdout.
The default keybind I am trying to replicate is control + c on mac.

### System

OS: macOS
Version: alacritty 0.13.

**Comment by aspauldingcode** [comment]
So... how is it done?

**Comment by kchibisov** [comment]
You can use the `ReceivedChar` as action for `Ctrl + Shift + C`, so it'll have SIGINT, and your binding for `ctrl+c`.

The new syntax for `\x03` is `\U0003`, the migrator translates them correctly.

**Comment by aspauldingcode** [comment]
> You can use the `ReceivedChar` as action for `Ctrl + Shift + C`, so it'll have SIGINT, and your binding for `ctrl+c`.
> 
> 
> 
> The new syntax for `\x03` is `\U0003`, the migrator translates them correctly.

Thanks @kchibisov !
