### ISSUE TITLE
Yaml conversion error: unsupported unit type

### ISSUE THREAD

**Issue by rcmosher** [alacritty/alacritty#7624]
When I start up alacritty or run `alacritty migrate` I get the error `Yaml conversion error: unsupported unit type`. The thing is my alacritty.yml file is completely commented out (whoops, I guess I never customized anything). This is problematic for two reasons.

1. There's no error to correct so there's no obvious path to resolve the issue. I did not find a standard placeholder alacritty.toml in the repo that I can swap in for my yaml file.
2. It's confusing for users who are just running alacritty without digging into how it works. Errors arise for customizations but the user has never worked with customizations.

I'm guessing the migrate tool defaults some value to null and can't handle it not being defined. One potential fix would be to check if the yaml file is all comments and just create a default toml file if it is. Though if a user has defined some configuration, but not whichever key is causing the error they would still be lost. So it would still benefit from highlighting what key has an unsupported value so that it can be defined.

**Comment by kchibisov** [comment]
use 0.13.1.

**Comment by kchibisov** [comment]
>I'm guessing the migrate tool defaults some value to null and can't handle it not being defined. One potential fix would be to check if the yaml file is all comments and just create a default toml file if it is. Though if a user has defined some configuration, but not whichever key is causing the error they would still be lost. So it would still benefit from highlighting what key has an unsupported value so that it can be defined.


YAML has a concept of null, e.g.

```yaml
window:
```

That's null, toml doesn't.

**Comment by rcmosher** [comment]
> use 0.13.1.

        alacritty -V
        alacritty 0.14.0-dev

Looks like I'm on a higher version.

> YAML has a concept of null, ... toml doesn't.

Right, but my file doesn't have anything defined. So some keys that need a non-null value are likely being defaulted to null. It's seems the migration should handle undefined values with reasonable defaults.

**Comment by chrisduerr** [comment]
Having everything commented out means that your root node is `null`, what @kchibisov said still applies.

An entirely empty config actually migrates just fine on 0.14.0-dev, so you're clearly doing something different. But hard to tell if you don't share the configuration file.

**Comment by kchibisov** [comment]
I have no clue which version you actually have, since you can't have a version like you said, because there should be `git` attached, so 0.14 could still be _old_. As I said, 0.13.1 doesn't have this issue.

**Comment by rcmosher** [comment]
Changing the yaml file to be empty did resolve the issue for me.

**Comment by kchibisov** [comment]
Could you share your original file if you had it around?

**Comment by rcmosher** [comment]
I don't still have the original or a back up of it. But it was just a ton of settings all commented out. I suspect I copied it as a generic file to use as a starting point.
