### ISSUE TITLE
No default alacritty.toml file on Github and system

### ISSUE THREAD

**Issue by kevinyyca** [alacritty/alacritty#7628]
# System
OS: Linux mint 21.2
`Note I'm using the Alacritty ppa`

# Switching to alacritty.toml
I updated Alacritty a few days ago it told me to migrate to `alacritty.toml`
by running `alacritty migrate`.

## Checking the alacritty.toml file
Then I checked the `alacritty.toml` file.
I saw it didn't have any comments telling me how to theme it and
how to do other stuff.

# Checking Github for a default alacritty.toml file
I checked Github for a default `alacritty.toml` file. Then i saw
it didn't have one.

# Checking the system for a default alacritty.toml file
I ran `locate alacritty.toml` and the results were Timeshift backups.

# End
So i couldn't find a default Alacritty config file on Github and my system.
I'm now using `kitty` because i cant get a default Alacritty config file.

**Comment by kevinyyca** [comment]
> `man 5 alacritty` the default is empty file.

this is the output
```
No manual entry for alacritty in section 5
```

**Comment by kevinyyca** [comment]
So the older versions of Alacritty have a default config file.
And the newer versions of Alacritty don't have a default config file?

**Comment by kchibisov** [comment]
If you don't install the man pages or your distribution doesn't install them, you can read docs on https://alacritty.org/config-alacritty.html

>And the newer versions of Alacritty don't have a default config file?

The old config was a documentation for the options basically, the default was always an empty file.

**Comment by kevinyyca** [comment]
When i run `man alacritty` it doesn't error but if i do `man <number greater then 1> alacritty` it errors.

**Comment by kchibisov** [comment]
that's likely because you're either using version before 0.13.0 or your distribution haven't installed the man pages. For versions before 0.13.0 everything is on the release page.
