### ISSUE TITLE
extra top padding on macOS window.decorations = Transparent

### ISSUE THREAD

**Issue by singersbalm** [alacritty/alacritty#7629]
The buttonless/transparent option has the issue that the text is under the buttons. I fixed it by increasing the padding, but this also increases the padding at the bottom and it exists in full screen. It would be great if the padding could be increased at the top by an extra option. 

<img width="863" alt="Screenshot 2024-01-16 at 11 44 56" src="https://github.com/alacritty/alacritty/assets/122386799/f28fb9ed-ae87-4527-b054-a07de1a0f736">

Something like this would be great

```yml
#[window]
extra_top_padding_transparent = 10
```

### System

OS: macOS
Version: alacritty 0.13.1 (fe2a3c5)

**Comment by travistylervii** [comment]
Same. Just need top padding. 
![CleanShot 2024-03-13 at 22 09 12@2x](https://github.com/alacritty/alacritty/assets/4889865/7d089566-0148-4c39-8978-4f5b36eee463)

**Comment by anshumankomawar** [comment]
I was hoping for this feature as well, any workarounds?

**Comment by chrisduerr** [comment]
There's two options here: Either someone fixes macOS so that the decorations height is taken properly into account, or someone comes up with a reason other than this macOS bug for why individual padding settings should be provided.

**Comment by nixpulvis** [comment]
I was starting to think about how to add padding to the window when the `window.decorations = "Transparent"` but then I realized there may be more to this than just the fixed offset. When creating new tabs on macOS with this option set they also spill over into the grid and I'm not sure if there's a good way to detect this.

**Comment by chrisduerr** [comment]
> When creating new tabs on macOS with this option set they also spill over into the grid and I'm not sure if there's a good way to detect this.

I feel like this should be something we could get out of macOS' UI tools.

**Comment by kchibisov** [comment]
yeah, it's all present in them and there was even API discussion upstream for that, it's just no-one interested in _writing the thing_ as always has been.

**Comment by nixpulvis** [comment]
@kchibisov I'd be interested in taking this on, though I'm a bit rusty (pun intended). Could you point me to the upstream discussion?

**Comment by kchibisov** [comment]
I think it's a part of https://github.com/rust-windowing/winit/issues/2308

Basically it's the safe area thing, though, there're per monitor ones and per-window ones, etc.

That's also required to _exclude_ the notch on certain laptops.

**Comment by nixpulvis** [comment]
> That's also required to exclude the notch on certain laptops.

The fucking notch... I can't really help test that directly since I don't have a mac with the notch, thankfully.

**Comment by pbgc** [comment]
@kchibisov sorry for commenting on a closed issue .. but is there any news about this support ? 
This is really nice and all other known terminals (kitty, Ghostty, Rio, etc) support this in MacOS

**Comment by kchibisov** [comment]
I can not get you ETA, but it'll work eventually, since safe area is shaping upstream, would need to test how it actually behaves, etc.
