### ISSUE TITLE
Upgrade from 0.13.0 to 0.13.1 breaks 

### ISSUE THREAD

**Issue by k2m30** [alacritty/alacritty#7630]
I use Alacrity to send keys to tmux.

These particular bindings stopped working after 0.13.0 to 0.13.1 upgrade:

```
# Next window
[[keyboard.bindings]]
chars = "\u0002n"
key = "RBracket"
mods = "Command|Shift"

# Prev window
[[keyboard.bindings]]
chars = "\u0002p"
key = "LBracket"
mods = "Command|Shift"
```

The same without Shift mode still work:

```
# Next pane
[[keyboard.bindings]]
chars = "\u0002o"
key = "RBracket"
mods = "Command"

# Prev pane
[[keyboard.bindings]]
chars = "\u0002i"
key = "LBracket"
mods = "Command"
```

#
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: macOS
Version: 0.13.1 (brew)

#### Downgraded back to 0.13.0

**Comment by kchibisov** [comment]
I'd suggest to use `alacritty --print-events` and check what the value for `logical_key` is now.
