### ISSUE TITLE
Error: provided display handle is not supported

### ISSUE THREAD

**Issue by MobSenpai** [alacritty/alacritty#7631]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux (NixOS)
Version: alacritty 0.12.0
Linux/BSD: Wayland, Hyprland, Installed using nixpkgs

### Logs

`alacritty -vv`

```
xkbcommon: ERROR: couldn't find a Compose file for locale "en_IN" (mapped to "en_IN.ISO8859-1")
Created log file at "/tmp/Alacritty-79511.log"
[0.000012734s] [INFO ] [alacritty] Welcome to Alacritty
[0.000388400s] [INFO ] [alacritty] Version 0.12.0
[0.000537062s] [INFO ] [alacritty] Running on Wayland
[0.001021480s] [INFO ] [alacritty_config_derive] No config file found; using default
Error: provided display handle is not supported
warning: queue 0x7f9de0000ca0 destroyed while proxies still attached:
  zwp_primary_selection_device_v1@25 still attached
  zwp_primary_selection_device_manager_v1@21 still attached
  wl_data_device@24 still attached
  wl_seat@23 still attached
  wl_data_device_manager@22 still attached
  wl_registry@20 still attached
warning: queue 0x555b82f18690 destroyed while proxies still attached:
  wl_output@15 still attached
  wp_fractional_scale_manager_v1@14 still attached
  xdg_activation_v1@13 still attached
  zwp_text_input_manager_v3@12 still attached
  zwp_relative_pointer_manager_v1@11 still attached
  zwp_pointer_constraints_v1@10 still attached
  zxdg_decoration_manager_v1@9 still attached
  wl_seat@8 still attached
  wp_viewporter@7 still attached
  wl_subcompositor@6 still attached
  wl_compositor@5 still attached
  wl_shm@4 still attached
  wl_registry@2 still attached
[0.010066268s] [INFO ] [alacritty] Goodbye
Deleted log file at "/tmp/Alacritty-79511.log"
Error: "Event loop terminated with code: 1"
```

I have seen some articles saying opengl to be culprit but their error was not the same as me. Matter of fact I am not able to understand the error myself, otherwise I would have solved it myself. I want a starting step to which direction I should go? Is it nixpkgs, wayland, or my own system idk.
If it helps this is my nixos config as well ![dots](https://github.com/MobSenpai/dotfiles.git). 
Also I am sorry for taking up devs time.

**Comment by kchibisov** [comment]
please, install alacritty via nixpkgs as well, it should be 0.13.1 iirc now.

It sounds like you're not running the distro package. The issue is that some runtime libraries can't be resolved and default package should handle all of that with `patchelf`.

**Comment by MobSenpai** [comment]
Omg I swear this has happened multiple times with nix now. I installed it using nix-env to check and It didn't work but then I install using home-manager then stuff works. This version mismatch is so bad. Well this is was on me, I didn't try the obvious. Thank you @kchibisov for fast reply. You resolved it lightning fast.

**Comment by MobSenpai** [comment]
@kchibisov  One last thing is that I want to know if wayland is natively supported on alacritty.

**Comment by kchibisov** [comment]
yes, it's natively supported `alacritty -v` should tell what are you running.

**Comment by MobSenpai** [comment]
> yes, it's natively supported `alacritty -v` should tell what are you running.

Oh yeah! @kchibisov Thank you again.

**Comment by MaxThom** [comment]
I have the same issue, but it is installed using home-manager ?
```
home.packages = [
  pkgs.alacritty
]
```

my opengl version:
 OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.0.2-manjaro1.1

any clue? either it hangs on startup or display provided diplay hhandle is not supported

**Comment by birneee** [comment]
@MaxThom have you found a solution? Have the same error on Manjaro with home manage

**Comment by o-dasher** [comment]
Same happening here on Fedora.

**Comment by AnthonyMBonafide** [comment]
Same issues on Arch with Home Manager

**Comment by birneee** [comment]
it seems to be a general problem with home-manager and OpenGL programs https://github.com/nix-community/home-manager/issues/2251

**Comment by o-dasher** [comment]
Here is the fix:
https://github.com/o-dasher/RikaOS/blob/main/nixo%2Fhome%2Fhanyuu%2Fnixgl%2Fdefault.nix
You just need to add the nixgl flake too on your flake.nix

**Comment by purefan** [comment]
> Here is the fix: https://github.com/o-dasher/RikaOS/blob/main/nixo%2Fhome%2Fhanyuu%2Fnixgl%2Fdefault.nix You just need to add the nixgl flake too on your flake.nix

Getting a 404 there, and just for the record Im getting this with home-manager on ubuntu wayland

**Comment by kchibisov** [comment]
Use `nixGL` or whatever it's called. In general, if you use nix, it's always nix.
