### ISSUE TITLE
`neovim` file content remain on screen after quitting `VISUAL=nvim sudoedit /some/file`, making some stdout unrecoverable.

### ISSUE THREAD

**Issue by amalgame21** [alacritty/alacritty#7632]
After editing some file using `VISUAL=nvim sudoedit /some/file` and typing `:wq` to save and quit, the whole screen is fill with the nvim content before typing `:wq`, and a screen of stdout before running the `VISUAL=nvim sudoedit /some/file` command is lost because of it and no longer visible by scrolling up the terminal by pressing `SHIFT+PAGEUP`.

This only happens when using `VISUAL=nvim sudoedit`.
`VISUAL=vim sudoedit` is fine.
Tested other terminal such as `xfce4` and `xterm`, none of them have this strange behaviour.
If the command runs inside `tmux`, it also exit without filling the screen with previous `neovim` file content, which is good, but I do not want to run tmux every time I launch alacritty.

### System

OS: Linux
Version: alacritty 0.12.3
Linux/BSD: X11

**Comment by kchibisov** [comment]
That sounds like alt-mode issue and not directly related to alacritty? if you're sure that env variables are being passed, try to pass `TERM=xterm-256color` along the way.

**Comment by amalgame21** [comment]
I don't know why but `$TERM` value is `alacritty` when I use alacritty.
Pass `TERM=xterm-256color` along the way solve my problem, I don't know why though.
Thank you very much!
