### ISSUE TITLE
KeePassXC's Auto-Type not working since Alacritty v0.13.0

### ISSUE THREAD

**Issue by mamekoro** [alacritty/alacritty#7633]
The password manager KeePassXC has a feature called Auto-Type that allows you to enter text such as user names or passwords in a specific window.

Until Alacritty v0.12.3, Auto-Type worked correctly with Alacritty.

However, since v0.13.0, Alacritty can't receive uppercase letters from Auto-Type, so when I need to run a command that requires a password (e.g. `sudo`), I must use another terminal such as Gnome Terminal.

## System
OS: Linux (Ubuntu 22.04)
Version: `alacritty 0.13.1`
Linux: X11

### Reproduction
1. Add a new entry in KeePassXC for testing
    - Set its password to `lower UPPER`.
2. Run `alacritty --config-file=/dev/null --print-events`
    - I passed `--config-file=/dev/null` to ignore configuration files.
3. Open KeePassXC
4. Click `{PASSWORD}` in the `Perform Auto-Type` dropdown menu
5. Click `Yes` in the `Confirm Auto-Type` dialog
6. Check what has been typed in Alacritty's window
    - `lower UPPER` is the expected result.

### v0.12.3
Typed text: `lower UPPER`
[0.12.3-debug.log](https://github.com/alacritty/alacritty/files/13958897/0.12.3-debug.log)

### v0.13.0
Typed text: `lower upper`
[0.13.0-debug.log](https://github.com/alacritty/alacritty/files/13958898/0.13.0-debug.log)

### v0.13.1
Typed text: `lower upper`
[0.13.1-debug.log](https://github.com/alacritty/alacritty/files/13958899/0.13.1-debug.log)

### master (94ede16)
Typed text: `lower upper`
[94ede16-debug.log](https://github.com/alacritty/alacritty/files/13958901/94ede16-debug.log)

**Comment by chrisduerr** [comment]
@kchibisov You mentioned stuff like xdotool vs other tools in the past. Seems like the same issue?

**Comment by kchibisov** [comment]
Yeah, pretty much. It just seems like you can't solely use xkbcommon on X11.

**Comment by GregPK** [comment]
Same problem with `autokey`s Phrase functionality,

**Comment by mamekoro** [comment]
@kchibisov
>A - needs repro

I've already provided reproduction steps and logs. Were they insufficient?
If so, please let me know what exactly is needed so I can provide more information.

**Comment by kchibisov** [comment]
It doesn't mean that I can repro, but autokey requires special treatment.

**Comment by terriblephrases** [comment]
Using Arch Linux, X11, dwm, and KeePassXC 2.7.6, and Alacritty 0.13.1, I have no trouble letting KeePassXC auto-type capital letters into Alacritty, including if I follow the reproduction steps by the letter.

**Comment by prosoitos** [comment]
Arch Linux, Alacritty v0.13.1-1, autokey 0.96.0-4

Same problem: phrase expansion of special characters is messed up:

`:` gets expanded as `;`
`_` gets expanded as `-`

**Comment by kchibisov** [comment]
This should fix it https://github.com/alacritty/alacritty/pull/7739
