### ISSUE TITLE
Migrate doesn't work on Windows

### ISSUE THREAD

**Issue by Drllap** [alacritty/alacritty#7634]
I always get an error when I try to migrate my yaml
```
.\alacritty migrate --config-file <path-to-yaml>                                                            
Configuration file migration failed:
    " <path-to-yaml>": parsing error: Unable to locate config file
```
I also get the same error why I don't pass `--config-file`.  Also tried `-c`

The `"C:\\Users\\<me>\\AppData\\Roaming\\alacritty\\alacritty.yml"` is a symbolic link to my config repo, might have something to do with that maybe?

### System

OS: Windows
Version: `alacritty 0.13.0 (78fa4d6)` output

**Comment by Drllap** [comment]
I tried running `migrate` on my Arch Linux box and it worked just fine

**Comment by chrisduerr** [comment]
Do you have imports that don't exist?

**Comment by Drllap** [comment]
@chrisduerr Yes, that was probably it, thx
