### ISSUE TITLE
Alt+Key on macos workaround not working since toml migration

### ISSUE THREAD

**Issue by matteematt** [alacritty/alacritty#7637]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: macOS
Version: `alacritty --version` output : alacritty 0.13.0 (78fa4d6)
Linux/BSD: X11/Wayland, DE or Compositor and WM : MacOS 14.2.1

### Logs

N/A

Info: 
I use alacritty with Tmux on MacOS. I configure bindings which involve the `Alt` key, e.g. I want to be able to use the `Alt+J` keybinding to switch tmux window. This is defined in tmux with
```
bind -n M-j previous-window
```
There is a known issue with this on MacOS, with a fix [here](https://github.com/alacritty/alacritty/issues/93#issuecomment-271043197). Esentially, you needed to configure your alacritty config with a key sequence to allow for `alt-` keys.

This was fine until recently. I presume this is due to the TOML migration I have had to do, as this is the only thing I have changed which is related to the above config. For example the `J` keybindings was defined as
```.alacritty.yml
  - { key: J,        mods: Alt,     chars: "\x1bj"                       }
```
and has been changed to.
```.alacritty.toml
[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"
```

has there been an issue when using `alacritty migrate`? Or is this new sequence correct, and there is another issue? 

You can find the PR where I perform the migration [here](https://github.com/matteematt/.dotfiles/commit/459a1281d9612a9fe42b6eac16e0490e954ac454) and my tmux config [here](https://github.com/matteematt/.dotfiles/blob/master/config/tmux/tmux.conf).

**Comment by kchibisov** [comment]
```toml
[window]
option_as_alt = "Both"
```

or  `OnlyLeft`. You don't need any of the workaround for a long time I think, as well as these bindings.

**Comment by erlangparasu** [comment]
> ```toml
> [window]
> option_as_alt = "Both"
> ```
> 
> or `OnlyLeft`. You don't need any of the workaround for a long time I think, as well as these bindings.

@kchibisov Thanks!

**Comment by dvdblk** [comment]
doesn't work for me on 0.13.2, macOS 14.5

**Comment by BozeBro** [comment]
@dvdblk What keys did you have to add to your ~/.zshrc? 
I've looked through the thread and it seems to be talking about binding the alt keys to a zsh command but idk if we can do that with a tmux command.

**Comment by dvdblk** [comment]
> What keys did you have to add to your ~/.zshrc?

@BozeBro these two:
```
bindkey "^[[1;3C" forward-word
bindkey "^[[1;3D" backward-word
```

**Comment by BozeBro** [comment]
> > What keys did you have to add to your ~/.zshrc?
> 
> @BozeBro these two:
> 
> ```
> bindkey "^[[1;3C" forward-word
> bindkey "^[[1;3D" backward-word
> ```

This solved the original problem of bind -n M-j previous-window?

This doesn't seem to do anything besides allowing for Alt + Left|Right to go back and forward words. I might be missing something though

**Comment by dvdblk** [comment]
> This solved the original problem of bind -n M-j previous-window?
no sorry, this was only for back and forwarding words.
