### ISSUE TITLE
How to have SHIFT+UP or DOWN to scrolll line

### ISSUE THREAD

**Issue by abdulbadii** [alacritty/alacritty#7638]
### System
OS: Linux
Version: alacritty 0.14.0-dev (https://github.com/alacritty/alacritty/commit/94ede16ee4af8869fd6415b3530c7e12c8681578)
Linux: X11

It's just due to being very often practice in most, if not all, Linux terminal that'd scroll line by line by Shift+Up and Shift+down key, so now feeling so missing or rather disappointed

So how to have SHIFT+UP also SHIFT+DOWN to perform line by line scrolll (some workaround maybe)?

**Comment by chrisduerr** [comment]
Just add a keybinding using the `ScrollLineUp` action.

**Comment by abdulbadii** [comment]
How clearly to do it, is there complete tutorial on it ?

**Comment by kchibisov** [comment]
https://alacritty.org/config-alacritty.html

![image](https://github.com/alacritty/alacritty/assets/27620401/2da3b2a3-4a4a-4851-9af3-a5994ab65beb)


I'm sure it's not hard to deduce that from the docs.

```toml
[keyboard]
bindings = [
   { key = "Up", mods = "Shift", action = "ScrollLineUp" },
]
```
