### ISSUE TITLE
command delete option for alacritty.toml 

### ISSUE THREAD

**Issue by Huansock** [alacritty/alacritty#7643]
[keyboard]
bindings = [
    { key= "Left",     mods= "Alt",      chars= "\u001BB"                      } # Skip word left
   ,{ key= "Right",    mods= "Alt",     chars= "\u001BF"                       } # Skip word right
   ,{ key= "Left",     mods= "Command", chars= "\u001bOH",   mode= "AppCursor" } # Home
   ,{ key= "Right",    mods= "Command", chars= "\u001bOF",   mode= "AppCursor" } # End
   ,{ key= "Back",     mods= "Command", chars= "\u0015"                        } # Delete line
   ,{ key= "Back",     mods= "Alt",     chars= "\u001b\u007f"                  } # Delete word
   ,{ key= "c",        mods= "Command", action= "Copy"                         } # Copy to Clipboard   
]

I hope this helps you

**Comment by jorgeOmurillo** [comment]
I'm on tmux and the opt+delete to "Delete word" binding does not work for me:
 ```
,{ key= "Back", mods= "Alt", chars= "\u001b\u007f" } # Delete word
```

Any help?

**Comment by kchibisov** [comment]
This is all done by your shell, etc. So bind what you want in it to react to sequences you provide.
