### ISSUE TITLE
How well documented is Alacritty? I can't find much on it.

### ISSUE THREAD

**Issue by Oneechan69** [alacritty/alacritty#7645]
All I could find is [the features page](https://github.com/alacritty/alacritty/blob/master/docs/features.md) and the [Arch wiki page](https://wiki.archlinux.org/title/Alacritty), but it's not obvious from a google search for "[Alacritty Documentation](https://www.google.com/search?client=firefox-b-1-d&q=alacritty+documentation)" that it is one, at least as someone that never really used Arch or looked at the wiki much. I can't be sure if that's complete documentation of Alacritty without asking, and software should have their own sites for documentation (possibly a GitHub wiki) rather than on sites for specific Linux Distros.

**Comment by kchibisov** [comment]
https://github.com/alacritty/alacritty#configuration

`man 5 alacritty` if your distro provides 0.13.0+ version.
