### ISSUE TITLE
Documentation Typo: 

### ISSUE THREAD

**Issue by wkrettek** [alacritty/alacritty#7647]
In the following text on the website at https://alacritty.org/config-alacritty.html, the default value should say 'columns' instead of 'column'

![image](https://github.com/alacritty/alacritty/assets/50168688/b1f0cb49-7340-4d49-af59-5cc2f41e6b65)

**Comment by Enkidu-Aururu** [comment]
Typos are still in the published docs https://github.com/alacritty/alacritty/issues/8070
