### ISSUE TITLE
[mesa][libegl] multiple instances fail to create dri2 screen

### ISSUE THREAD

**Issue by foxjaw** [alacritty/alacritty#7649]
```
 ~ $ alacritty
libEGL warning: egl: failed to create dri2 screen
MESA: error: zink: couldn't allocate memory: heap=0 size=67108864
Segmentation fault
```
### System

`linux 6.7.0-zen3-1-zen #1 ZEN SMP PREEMPT_DYNAMIC, x86_64 GNU/Linux
`
```
 ~ $ alacritty -v
Created log file at "/tmp/Alacritty-4433.log"
[0.000002907s] [INFO ] [alacritty] Welcome to Alacritty
[0.000054996s] [INFO ] [alacritty] Version 0.13.1 (fe2a3c56)
[0.000061529s] [INFO ] [alacritty] Running on Wayland
[0.000181920s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/home/usr/.config/alacritty/alacritty.toml"
libEGL warning: egl: failed to create dri2 screen
[0.095884113s] [INFO ] [alacritty] Using EGL 1.5
[0.099187690s] [INFO ] [alacritty] Window scale factor: 1
MESA: error: zink: couldn't allocate memory: heap=0 size=67108864
Segmentation fault
 ~ $
```
- archlinux
- sway-git (wayland)
- opengl/mesa
- nvidia (proprietary)

**Comment by kchibisov** [comment]
zink??? We don't force zink, so please try to find out what tries to use zink and why it's being loaded. In general, such issue is out of our control.  But I'd suggest to figure out why zink is used and try to disable it.

**Comment by kchibisov** [comment]
zink is a OpenGL -> Vulkan translation layer. With nvidia proprietary drivers, you should be using them instead, not mesa in the first place. Even if you have open source drivers, you shouldn't use zink.

**Comment by kchibisov** [comment]
I mean, zink is an open source driver as well as mesa that's the thing. Alacritty is only a `OpenGL` application, not `Vulkan`, so zink translates our OpenGL to Vulkan, why it tries to do so out of the box for you I have no idea, sorry.

>Being a GPU accelerated terminal & not having vulkan support is kinda weird.

Vulkan doesn't work on macOS, so it's useless for us, and OpenGL is simple and provides all we need.

**Comment by kchibisov** [comment]
>Can compositor affect alacritty ?

Yes, it can in some cases. There's a `eglBindWlDisplay` or whatever it's called, which may affect driver picking. Maybe you can somehow find and force the nvidia driver via env variables for alacritty itself, since it's usually controlled via env variables.

**Comment by kchibisov** [comment]
You'd need to touch `libglvnd` env variables I guess and ask for nvidia from it? In general, I'm not sure how to disable zink, but could be an issue in the way sway/wlroots sets up EGL.
