### ISSUE TITLE
Alacritty prints symbols on ctrl+c

### ISSUE THREAD

**Issue by thequver** [alacritty/alacritty#7656]
When i press ctrl+c to copy selected text, alacritty pastes "^C" in the terminal. How to disable this?
Setting
`bindings = [{ key = "C", mods = "Control", mode = "AppCursor | AppKeypad | Search | Alt | Vi", action = "None"},]`
in the config did not help.

**Comment by kchibisov** [comment]
You need to remove all the `mode` stuff and use `Copy` action, but `ctrl+c` was never meant to copy by default, the default is the same as in other terminals (ctrl+shift+c).
