### ISSUE TITLE
kitty keyboard encoding reports associated text with some control characters

### ISSUE THREAD

**Issue by rockorager** [alacritty/alacritty#7657]
When using kitty keyboard encoding, keys which map to C0 control codes emit associated text:

Affected keys: tab, enter, backspace, escape

No other terminal implementing kitty keyboard encoding follows this behavior (kitty, foot, wezterm, ghostty).

### System

OS: Linux
Version: alacritty 0.13.1 (fe2a3c56)
Linux/BSD: wayland / sway

### Logs

Keyboard and bindings: [Alacritty-459396.log](https://github.com/alacritty/alacritty/files/14038242/Alacritty-459396.log)

**Comment by kchibisov** [comment]
There's no wording saying that I can't do so and I don't see why I shouldn't. libxkbcommon explicitly tells me that I have text, thus, I send text.

If you want for me to change it, bring it to kitty.
