### ISSUE TITLE
Unexpected behavior when overwriting default keybinding

### ISSUE THREAD

**Issue by qtc-de** [alacritty/alacritty#7660]
Hi there :wave: 

there seems to be a bug with the `Last` action when it is manually configured via configuration file. Other actions may also be affected (not tested).

### How to reproduce

My old configuration file contained a binding for the `Last` action that matched the current default binding:

```toml
[[keyboard.bindings]]
action = "Last"
key = 5
mode = "Vi|~Search"
mods = "Shift"
```

### Expected behavior

Although the configuration above is no longer necessary, as the binding matches the current default configuration, it shouldn't cause any problems. The expected behavior is therefore to move to the last occupied cell within the terminal.

```console
[user@host ~]$ test test test
                            ^
                            Pressing '$' should move the cursor here
``` 

### Actual Behavior

The `Last` action seems to be called twice, as the cursor moves to the end of the terminal.

```console
[user@host ~]$ test test test
                                                                                                  ^
                                                                            We actually end up here
``` 

### System

OS: Linux
Version: alacritty 0.13.1

**Comment by kchibisov** [comment]
that's expected since you bind by scancode, but default binding is by keysym, so they duplicate, if you bind by keysym, like `key = "$"` it'll likely work.
