### ISSUE TITLE
Colors don't work over ssh

### ISSUE THREAD

**Issue by addy419** [alacritty/alacritty#7663]
### System

OS: Linux
Version: 0.13.0
Linux/BSD: Wayland, Hyprland

When I ssh into any remote server, I get a white prompt and a colorless bash. If I use any other terminal (I've tried gnome and cosmic-term), I get colored prompts.

-- I have also installed the terminfo

**Comment by kchibisov** [comment]
we just render things and have nothing to do with colors.

it just wants `TERM=xterm-256colors`(you can set it before ssh) because it thinks that alacritty is not a colered terminfo based on its name.
