### ISSUE TITLE
[WARN] Unused config key: terminal

### ISSUE THREAD

**Issue by dusanbrankov** [alacritty/alacritty#7664]
I get the mentioned error after adding the `terminal` table as described in [alacritty.5.scd](https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#terminal) to my `alacritty.toml`:

```toml
[terminal]
osc52 = "CopyPaste"
``` 

I don't understand the warning, is `terminal` deprecated and should not be used anymore? Because when I add a non-existent key like `[foo]`, I get the same warning. So where do I put `osc52 = "CopyPaste"`?

### System

OS: Linux
Version: alacritty 0.13.0-dev (b9c88687)
Linux/BSD: Linux Mint 21.3 x86_64, Cinnamon 6.0.4

### Logs

`alacritty -vv` just gives the same warning.

**Comment by kchibisov** [comment]
>Version: alacritty 0.13.0-dev (https://github.com/alacritty/alacritty/commit/b9c886872d1202fc9302f68a0bedbb17daa35335)

You're version is out of date and it's actually telling you the hash, if you check out that hash it doesn't have this setting yet. So using 0.13.1 will let you use this.

**Comment by dusanbrankov** [comment]
Just updated, it's working now. Thanks for the info.
