### ISSUE TITLE
MacOS: Escape file/folder path when dropping from finder

### ISSUE THREAD

**Issue by daveilers** [alacritty/alacritty#7667]
When dragging a file or folder from the finder in macos to anb open terminal window, the file or folder is not quoted or escaped.

Example: `mkdir 'this is a folder: with <some> commonly|used (shell) symbols'`
Dragging this folder into Terminal.app: `/Users/me/this\ is\ a\ folder\:\ with\ \<some\>\ commonly\|used\ \(shell\)\ symbols `
Dragging into alacritty: `/Users/me/this is a folder: with <some> commonly|used (shell) symbols`

I'd like to be able to get the Terminal.app behavior here when receiving a drag&drop from finder. 

### System

OS: macOS
Version: alacritty 0.13.1 (fe2a3c5)

### Logs

Keyboard and bindings: `alacritty --print-events`
Here's the drop event:

[7.850768708s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(5064665968)), event: DroppedFile("/Users/deilers/this is a folder: with <some> commonly|used (shell) symbols") }

**Comment by kchibisov** [comment]
escaping is subjective to the application you're running in, so it should do that instead. We paste the dnd via the bracketed paste escape sequence and the shell or other app has all the indication to do so.

zsh has a plugin called bracketed-paste-magic iirc to do that sort of things.
