### ISSUE TITLE
Windows ARM64 Binaries

### ISSUE THREAD

**Issue by wayneforrest** [alacritty/alacritty#7669]
Can we please get ARM64 Windows Binaries?

I run Windows ARM64 on my Mac M1, and when downloading the Portable EXE or the MSI, Windows warns me that this is not compatible.

It would be nice to get the Windows ARM64 binaries too.

Thanks.
W.

**Comment by libert-xyz** [comment]
why this was closed?

**Comment by kchibisov** [comment]
it's wontfix unless it's as easy as on macOS.

**Comment by f0o** [comment]
Can we re-evaluate this?

**Comment by nixpulvis** [comment]
This should he supported at some point for sure. I would reopen this issue.

I haven't found myself with an ARM windows machine yet, but I assume it's not significantly different from the macOS process, is it?

Linux ARM builds are also a matter of time.

**Comment by f0o** [comment]
Naively looking at the GH Actions workflow and https://rust-lang.github.io/rustup/installation/windows.html it seems that it might just be as simple as setting up rustup with `aarch64-pc-windows-msvc` similar to MacOS.

**Comment by nixpulvis** [comment]
If you have a way to test this could you try it and report back?

**Comment by Alovchin91** [comment]
@nixpulvis Here you go: https://github.com/Alovchin91/alacritty/actions/runs/25130108244

https://github.com/Alovchin91/alacritty/commit/0e98e7fd37e0c1dabbce5c322cdcbcc7291f97a3

Is this enough for you to incorporate it into the release process? Or should I enable tests and installer as well?

At least I think it makes sense to re-open this issue now.

**Comment by mbana** [comment]
Do we have arm64 binaries for Windows (11) yet?

**Comment by yachoukh** [comment]
Please implement this as an additional action in the build process as there are a lot of snapdragon X Windows laptops and in the future we will have snapdragon X2 and the new RTX ultra...

**Comment by chrisduerr** [comment]
GitHub does offer ARM64 runners, so this shouldn't be difficult to implement. However I don't have any way to verify or test this, so it would require external contribution to validate for functionality.
