### ISSUE TITLE
alacritty feels slow to start

### ISSUE THREAD

**Issue by squeaktoy** [alacritty/alacritty#7672]
Alacritty feels slow to start.
Here's the output of  `time alacritty -e exit` inside fish:
```
Executed in  139.28 millis    fish           external
   usr time   58.93 millis  296.00 micros   58.63 millis
   sys time   60.67 millis  148.00 micros   60.52 millis
```
Over 100 ms of time to start a terminal is a noticeable delay, which I find annoying. Sometimes alacritty takes even longer to start, like up to 300 ms, perhaps when alacritty isn't cached.

Meanwhile I'm running st, and here's the output of `time st -e exit`:
```
Executed in   59.61 millis    fish           external
   usr time   24.71 millis  212.00 micros   24.50 millis
   sys time   16.73 millis  107.00 micros   16.63 millis
```
st takes half the time to start as alacritty does, and the difference is really noticeable. Is it possible to make alacritty start faster?

### System

OS: Gentoo Linux
Version: alacritty 0.12.3
WM: i3 version 4.23 (2023-10-29)

## Logs generated with `alacritty -vv --print-events -e exit`
[alacritty.log](https://github.com/alacritty/alacritty/files/14076725/alacritty.log)

**Comment by kchibisov** [comment]
Open new windows then

`alacritty msg create-window || alacritty`.

And measuring with `-e` is not a great way to do that.
