### ISSUE TITLE
TOML config keybindings are not recognized for \x character

### ISSUE THREAD

**Issue by parfeniukink** [alacritty/alacritty#7675]
### System

OS: macOS
Version: alacritty 0.13.1 (fe2a3c5)

### Logs

The config can't be recognized with the new .toml configuration.
Background: before I was using a `.yaml` config file with key binding to jump over the word. Could you please help me find related things in the documentation or at least mark it as a bug if it makes sense?

![Alacritty 2024-01-30](https://github.com/alacritty/alacritty/assets/45270625/e22fc07b-0cfb-4bda-94d7-f7d5373aeab0)

**Comment by kchibisov** [comment]
TOML uses `\U` and conversion tool converts it correctly.

Though, we should probably explicitly mention `\U` can be used, @chrisduerr ?

P.s. The bindings for arrows you define are there by default, so you don't need to bind them yourself.

**Comment by chrisduerr** [comment]
Fyi `\e`, which is equivalent to `\x1b` will be supported in the future:

https://github.com/toml-lang/toml/pull/790

**Comment by kchibisov** [comment]
To jump by word you need `Alt+b`/`Alt+f`, that's what macOS binds for `arrow left/right`.

Why macOS does that in their terminal I have no idea.

**Comment by parfeniukink** [comment]
> To jump by word you need `Alt+b`/`Alt+f`, that's what macOS binds for `arrow left/right`.
> 
> Why macOS does that in their terminal I have no idea.

resolved with ZSH and tmux conf. I was thinking that there is a way to go with Alacritty only :)
nevermind
