### ISSUE TITLE
Alacritty won't build on Alpine Linux

### ISSUE THREAD

**Issue by rgeddes** [alacritty/alacritty#7679]
Did I miss something?

### System

OS: Alpine Linux
Version: latest 
Linux/BSD: X11, Xfwm and Xfce

### Logs

`doas apk add cmake pkgconf freetype-dev fontconfig-dev python3 libxcb-dev`

clone the repo 

cd into the repo directory

`cargo build`

Build fails with the following notes:

  = note: /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libfreetype.a(src_sfnt_sfnt.c.o): in function `Load_SBit_Png':
          sfnt.c:(.text+0x5f48): undefined reference to `png_create_read_struct'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: sfnt.c:(.text+0x5f68): undefined reference to `png_create_info_struct'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: sfnt.c:(.text+0x5f89): undefined reference to `png_destroy_read_struct'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: sfnt.c:(.text+0x5fa5): undefined reference to `png_set_longjmp_fn'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: sfnt.c:(.text+0x5fd6): undefined reference to `png_set_read_fn'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: sfnt.c:(.text+0x5fe6): undefined reference to `png_read_info'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: sfnt.c:(.text+0x6015): undefined reference to `png_get_IHDR'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: sfnt.c:(.text+0x60cc): undefined reference to `png_set_palette_to_rgb'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: sfnt.c:(.text+0x60d4): undefined reference to `png_set_expand_gray_1_2_4_to_8'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: sfnt.c:(.text+0x60e9): undefined reference to `png_get_valid'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: sfnt.c:(.text+0x60f8): undefined reference to `png_set_tRNS_to_alpha'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: sfnt.c:(.text+0x610a): undefined reference to `png_set_strip_16'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: sfnt.c:(.text+0x611c): undefined reference to `png_set_packing'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: sfnt.c:(.text+0x6131): undefined reference to `png_set_gray_to_rgb'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: sfnt.c:(.text+0x6143): undefined reference to `png_set_interlace_handling'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: sfnt.c:(.text+0x6158): undefined reference to `png_set_filler'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: sfnt.c:(.text+0x6168): undefined reference to `png_read_update_info'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: sfnt.c:(.text+0x6197): undefined reference to `png_get_IHDR'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: sfnt.c:(.text+0x61e1): undefined reference to `png_set_read_user_transform_fn'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: sfnt.c:(.text+0x629a): undefined reference to `png_read_image'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: sfnt.c:(.text+0x62aa): undefined reference to `png_read_end'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: sfnt.c:(.text+0x62d2): undefined reference to `png_destroy_read_struct'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libfreetype.a(src_sfnt_sfnt.c.o): in function `error_callback':
          sfnt.c:(.text+0x6373): undefined reference to `png_get_error_ptr'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: sfnt.c:(.text+0x6390): undefined reference to `png_set_longjmp_fn'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libfreetype.a(src_sfnt_sfnt.c.o): in function `read_data_from_FT_Stream':
          sfnt.c:(.text+0x63b4): undefined reference to `png_get_io_ptr'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: sfnt.c:(.text+0x63cf): undefined reference to `png_get_error_ptr'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: sfnt.c:(.text+0x63e0): undefined reference to `png_error'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libfreetype.a(src_sfnt_sfnt.c.o): in function `sfnt_init_face':
          sfnt.c:(.text+0xbec1): undefined reference to `BrotliDecoderDecompress'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libfreetype.a(src_gzip_ftgzip.c.o): in function `ft_gzip_file_fill_output':
          ftgzip.c:(.text+0x240): undefined reference to `inflate'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libfreetype.a(src_gzip_ftgzip.c.o): in function `ft_gzip_file_io':
          ftgzip.c:(.text+0x2b0): undefined reference to `inflateReset'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libfreetype.a(src_gzip_ftgzip.c.o): in function `ft_gzip_stream_close':
          ftgzip.c:(.text+0x3dc): undefined reference to `inflateEnd'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libfreetype.a(src_gzip_ftgzip.c.o): in function `FT_Stream_OpenGzip':
          ftgzip.c:(.text+0x552): undefined reference to `inflateInit2_'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: ftgzip.c:(.text+0x621): undefined reference to `inflateEnd'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libfreetype.a(src_gzip_ftgzip.c.o): in function `FT_Gzip_Uncompress':
          ftgzip.c:(.text+0x77a): undefined reference to `inflateInit2_'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: ftgzip.c:(.text+0x78c): undefined reference to `inflate'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: ftgzip.c:(.text+0x79c): undefined reference to `inflateEnd'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: ftgzip.c:(.text+0x7b9): undefined reference to `inflateEnd'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libfreetype.a(src_bzip2_ftbzip2.c.o): in function `ft_bzip2_stream_close':
          ftbzip2.c:(.text+0x65): undefined reference to `BZ2_bzDecompressEnd'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libfreetype.a(src_bzip2_ftbzip2.c.o): in function `ft_bzip2_file_fill_output':
          ftbzip2.c:(.text+0x177): undefined reference to `BZ2_bzDecompress'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libfreetype.a(src_bzip2_ftbzip2.c.o): in function `ft_bzip2_stream_io':
          ftbzip2.c:(.text+0x204): undefined reference to `BZ2_bzDecompressEnd'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: ftbzip2.c:(.text+0x253): undefined reference to `BZ2_bzDecompressInit'
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libfreetype.a(src_bzip2_ftbzip2.c.o): in function `FT_Stream_OpenBzip2':
          ftbzip2.c:(.text+0x49b): undefined reference to `BZ2_bzDecompressInit'
          collect2: error: ld returned 1 exit status

  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `alacritty` (bin "alacritty") due to previous error

**Comment by kchibisov** [comment]
See alpine package and how they build it.

**Comment by kchibisov** [comment]
https://git.alpinelinux.org/aports/tree/community/alacritty/APKBUILD
