### ISSUE TITLE
EventLoop::new() can panic with "Bad File Descriptor"

### ISSUE THREAD

**Issue by ConradIrwin** [alacritty/alacritty#7680]
We are using Alacritty at Zed to provide the embedded terminal, and across the whole userbase see this panic a few times a day:

```
thread 'main' panicked at 'create mio Poll: Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }'
/Users/administrator/.cargo/git/checkouts/alacritty-afea874b09a502a5/3330614/alacritty_terminal/src/event_loop.rs:163
<terminal::TerminalBuilder>::new
<project::Project>::create_terminal
// more zed stuff....
```

Although we have struggled to reproduce this problem in situ, we suspect this happens while the filesystem is quite heavily loaded (we're restoring a workspace for example https://github.com/zed-industries/zed/issues/6835). That said, this is not reliably reproducible for those users.

I think the best next step is relatively straightforward, which is to pass the result out of `EventLoop::new()` instead of unwrapping, so that the caller can handle it.

### System

OS: macOS
Version: [Zed](https://zed.dev) using alacritty_terminal v0.21

### Logs

```
thread 'main' panicked at 'create mio Poll: Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }'
/Users/administrator/.cargo/git/checkouts/alacritty-afea874b09a502a5/3330614/alacritty_terminal/src/event_loop.rs:163
<terminal::TerminalBuilder>::new
<project::Project>::create_terminal
// more zed stuff....
```

**Comment by kchibisov** [comment]
I'd suggest to try recent released version, since it doesn't use mio and your crash is for version with mio.

**Comment by ConradIrwin** [comment]
Thanks for the suggestion! We had actually already done that, and I was confusing myself between different versions.

On v0.21.0 we get the same problem:

```
thread 'main' panicked at 'create Poll: Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }'
/Users/administrator/.cargo/registry/src/index.crates.io-6f17d22bba15001f/alacritty_terminal-0.21.0/src/event_loop.rs:73
```

And looking more closely, it's actually the case that we see a similar panic at two other places in the file too:

```
thread 'PTY reader' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }'
/Users/administrator/.cargo/registry/src/index.crates.io-6f17d22bba15001f/alacritty_terminal-0.21.0/src/event_loop.rs:217
```
```
thread 'PTY reader' panicked at 'EventLoop polling error: Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }'
/Users/administrator/.cargo/registry/src/index.crates.io-6f17d22bba15001f/alacritty_terminal-0.21.0/src/event_loop.rs:238
```

**Comment by ConradIrwin** [comment]
I've added a potential fix for the other two panics to the same branch.

**Comment by ConradIrwin** [comment]
We don't. We do a bunch of work with background threads, but we maintain the same process.

This is our version of the setup code FWIW: https://github.com/zed-industries/zed/blob/main/crates/terminal/src/terminal.rs#L342-L401.

One thing that strikes me as suspicious is that call to `as_fd_raw()` on the pty file (as that could lead to us referencing a dropped FD), but it seems like the pty would retain it for us (and this is very similar to the parallel code in alacritty itself).

**Comment by kchibisov** [comment]
I mean, you fail to create `kqueue`, nothing else is touched really.
