### ISSUE TITLE
The `migrate` command reports an error when importing a TOML file in the old YAML config

### ISSUE THREAD

**Issue by Techassi** [alacritty/alacritty#7683]
### System

OS: Linux
Version: `alacritty 0.14.0-dev (2d2b894c)`
Debian, KDE

### Description

When using the old YAML-based config file (before running `alacritty migrate`) but already importing a TOML file causes the `migrate` command to fail with the following error message: 

```
Configuration file migration failed:
    "<SNIP>/.config/alacritty/alacritty.yml": already in TOML format
```

In my case this was caused by importing a theme from https://github.com/alacritty/alacritty-theme while still using the old YAML-based config file. Yes, I can see this being an edge-case and me holding the config wrong - obviously a YAML config file *doesn't* work with a TOML import. Let me know if this is even worth getting fixed.

### Fix / workaround

The migration can be fixed by commenting out the import, then running the `migrate` command, and finally commenting the import back in.

**Comment by kchibisov** [comment]
there's a `--skip-imports`(`-i`) flag, but mixed configs are not supported.
