### ISSUE TITLE
How to get natural text editing to work?

### ISSUE THREAD

**Issue by Mo0rBy** [alacritty/alacritty#7687]
I know this is in an older issue (#3743), but I can't get it working so therefore I have created this new one.

I'm trying to setup natural text editing. I've used `xxd` to see the character combinations that are used for `Control + LeftArrow` or `Control + RightArrow` etc, and put them into my config, but when I use them, it just prints those characters into the terminal. I think this is working correctly, but obviously it's not the behaviour I want.

Here are my bindings:
```toml
bindings = [
  { mods = "Control", key = "ArrowLeft", chars = "^[[1;5D" },
  { mods = "Control", key = "ArrowRight", chars = "^[[1;5C" },
  { mods = "Control", key = "ArrowUp", chars = "^[[1;5A" },
  { mods = "Control", key = "ArrowDown", chars = "^[[1;5B" },

  { mods = "Alt", key = "ArrowLeft", chars = "^[[1;3D" },
  { mods = "Alt", key = "ArrowRight", chars = "^[[1;3C" },
]
```
Here is a screen-recording of my problem. You can see how I got the char codes from xxd and then how Alacritty is printing the characters rather than moving my cursor which is what the characters mean (I think).
[Screencast from 2024-02-03 22-08-30.webm](https://github.com/alacritty/alacritty/assets/88185573/95424d0b-0196-45f8-9136-b5622dc2761f)

I think that I am probably being stupid and this is not the correct way to get the char codes I want for natural text editing. 
I use Ubuntu Linux and MacOS so I will need to be able to get the correct codes on both machines and then create separate keybinds for each (and this is assuming that the keybinds will be different on each operating system, they could be the same)

**Comment by chrisduerr** [comment]
Shell bindings are up to your shell.

**Comment by Mo0rBy** [comment]
@chrisduerr Could you please advise on how to get these shell bindings? Is using `xxd` the correct way?

**Comment by chrisduerr** [comment]
That depends on your shell and you'll have to turn to your specific shell for help with that.

**Comment by Mo0rBy** [comment]
Ok, thanks for helping to point me in the right direction.

**Comment by Mo0rBy** [comment]
For anyone that comes across this, I found the solution by adding keybinds to my `.zshrc` instead of to my Alacritty config.

Here are the relevant StackOverflow questions:
https://stackoverflow.com/questions/12382499/looking-for-altleftarrowkey-solution-in-zsh
https://stackoverflow.com/questions/8638012/fix-key-settings-home-end-insert-delete-in-zshrc-when-running-zsh-in-terminat

You will need to use `xxd` top see the codes used for your own shell, and then put them into your shell rc file.

**Comment by ramedhis** [comment]
I've recently switched to Alacritty from iTerm2, and I really miss the natural text editing feature in iTerm2. I've played around with both alacritty.toml and .zshrc, but as you said, you only need to configure `.zshrc`.

To do this, I add these lines to my `.zshrc`:

```zsh
# <<<<< Enable natural text editing
#
# Move to the beginning of the line. `Cmd + Left Arrow`:
bindkey "^[[1;9D" beginning-of-line
# Move to the end of the line. `Cmd + Right Arrow`:
bindkey "^[[1;9C" end-of-line
# Move to the beginning of the previous word. `Option + Left Arrow`:
bindkey "^[[1;3D" backward-word
# Move to the beginning of the next word. `Option + Right Arrow`:
bindkey "^[[1;3C" forward-word
# Delete the word behind the cursor. `Option + Delete`:
bindkey "^[[3;10~" backward-kill-word
# Delete the word after the cursor. `Option + fn + Delete`:
bindkey "^[[3;3~" kill-word
#
# Enable natural text editing >>>>>
```

And source `.zshrc` to see the changes take effect.

Now, if you're using tmux, you'll notice a conflict or something weird happening between tmux, Alacritty, and zsh. For me, `^[[1;9D` and `[[1;9C` function exactly the same as `^[[1;3D` and `^[[1;3C`, respectively. That means, when I press `⌘` + `←` it behaves the same as `Option` + `←`. Same goes for `⌘` + `→` behaving the same as `Option` + `→` on tmux on alacritty. 

Like I said, If you don't use tmux, you won't experience this issue after adding those lines to your `.zshrc`. I think this is an issue inside tmux itself. I've tried adding custom keymaps in both `alacritty.toml` and `.tmux.conf`, but nothing works. I even tried passing ASCII control. It seems tmux can't distinguish between `⌘` and `Option`. If anyone else has experienced this and found a solution, please share.

---

I'll leave these 2 pages here for reference, just in case someone needs them: [zsh-line-editor](https://zsh.sourceforge.io/Doc/Release/Zsh-Line-Editor.html#Standard-Widgets) and [tmux manual page](http://man.openbsd.org/OpenBSD-current/man1/tmux.1)

**Comment by jameskohjunwei** [comment]
@ramedhis your .zshrc config for natural text editing works for me too. 

I can concur that i have the same issues with  ⌘ + → behaving the same as Option + → on tmux on alacritty.

Happy to hear if anyone else on this thread has a solution to this.

Thanks a lot!
