### ISSUE TITLE
Can't escape keycombination

### ISSUE THREAD

**Issue by LeSaRo** [alacritty/alacritty#7695]
I want to escape Ctrl+I, and I see that in TOML instead of `\x1b[` it's `\e`. It should be correct and allow me to send the sequence, but it seems that alacritty's parser doesn't support it.

![Capture d’écran du 2024-02-06 11-17-21](https://github.com/alacritty/alacritty/assets/24613248/b1590b5f-8464-493c-bdd9-1941db6afca0)

### System

OS: Manjaro Linux
Version: alacritty 0.13.1 (fe2a3c56) (also tested on alacritty 0.14.0-dev (6484ab84))
Linux: X11, GNOME 45.1

### Logs
```
[7.960904359s] [ERROR] [alacritty_config_derive] Unable to load config "/home/le_saro/.config/alacritty/alacritty.toml": Config error: TOML parse error at line 27, column 47
                                                    |
                                                 27 |     { key = "I", mods = "Control", chars = "\e73;5u" }
                                                    |                                               ^
                                                 invalid escape sequence
                                                 expected `b`, `f`, `n`, `r`, `t`, `u`, `U`, `\`, `"`
[241.837062320s] [ERROR] [alacritty_config_derive] Unable to load config "/home/le_saro/.config/alacritty/alacritty.toml": Config error: TOML parse error at line 27, column 47
                                                      |
                                                   27 |     { key = "I", mods = "Control", chars = "\e[73;5u" }
                                                      |                                               ^
                                                   invalid escape sequence
                                                   expected `b`, `f`, `n`, `r`, `t`, `u`, `U`, `\`, `"`
                                                   
```

**Comment by kchibisov** [comment]
Use `\U`.

also, if you want to hardcode kitty protocol bindings, you don't really need that anymore.

**Comment by LeSaRo** [comment]
> also, if you want to hardcode kitty protocol bindings, you don't really need that anymore.

I want to do the inverse of that, send the key combination as is instead of the kitty binding.

**Comment by kchibisov** [comment]
huh, but kitty protocol sends the exact same thing once enabled. Anyway, use `\U` as toml wants to write `\U001b` if you want to send escape.
