### ISSUE TITLE
[Question][alacritty_terminal] Wide chars and parser behavior

### ISSUE THREAD

**Issue by MoSal** [alacritty/alacritty#7696]
Hello.

I don't know if this is an `alacritty_terminal` question, or a `vte` one, maybe both.

I wanted to experiment with using a custom char-width function other than the one from `unicode-width`. But I hit an early hurdle in my testing.

https://github.com/alacritty/alacritty/blob/6484ab84db0c9558547903616401150ae5bbf796/alacritty_terminal/src/term/mod.rs#L1058-L1063

Unless I missed them somehow, there are no other places in `alacritty_terminal` where `unicode-width` is used (tests aside). Nor there is any usage in `vte` or its deps.

But, if I change the code above to:

``` rust
 let ch_width = match c {
   '⸺' => Some(2),
   _ => c.width(),
 };
  
 let width = match ch_width { 
     Some(width) => width, 
     None => return, 
 }; 
```

And if I test with `⸺`. Somehow, somewhere, this character is still recognized as single-width.

For example, inputting `A` then `😀` then `space` works as expected from `vte`'s side:
* `A`
* `backspace`
* `A` `😀` `[spacer]`
* `backspace` `backspace` `backspace`
* `A` `😀` `[spacer]` `space`
 
But if `⸺` is used instead of `😀`:

* `A`
* `backspace`
* `A` `⸺` `[spacer]`
* `backspace` `backspace` (no third `backspace` here)
* `A` `⸺` `[spacer]` `space`

So instead of `A⸺ `, we get `AA⸺ `.

So, where does the difference in behavior between `😀` and `⸺` come from?

**Comment by kchibisov** [comment]
The width we have is how _we_ advance the cursor, the application also tracks width, thus it should also advance by width of `2`. So what you should do is to test in some kind of isolation all of that.

**Comment by MoSal** [comment]
>  the application also tracks width, thus it should also advance by width of 2.

Well, if the application is `alacritty`, I tracked and edited all usages of `<char>.width()`, and I still get the same behavior.

**Comment by kchibisov** [comment]
How do you test this? You wrote custom input to edit things or you literally just dump the grid?

**Comment by kchibisov** [comment]
Clearly it works if you hardcode just 2 when it comes to renderer 

![image](https://github.com/alacritty/alacritty/assets/27620401/f68dc478-c3f0-472f-8176-e401efeb9b8c)


However, editing should be done all by yourself in such case.

**Comment by MoSal** [comment]
So, you were right of course. It was the shell's fault/responsibility.

Thank you for your help.
