### ISSUE TITLE
Alacritty process hang on close

### ISSUE THREAD

**Issue by dougg0k** [alacritty/alacritty#7700]
I noticed that when I close Alacritty, through an exit for example, the window closes normally, but the shortcut icon progress bar keeps spinning and I am unable to open another instance till it stops, and even a bit more after it stops, only after.

I am using this ppa https://launchpad.net/~aslatter/+archive/ubuntu/ppa with the latest version, even though when installing it says `0.13.1`, when I do a `-v`, it shows `0.14.0-dev`.

I use nushell, zellij and starship with it.

PopOS 22.04

Laptop with very good hardware. Certainly not the problem.

I was using Terminator as the terminal before and never had this kind of behavior, not a really bad thing, but sometimes it could be, that's why I opened the issue.

**Comment by chrisduerr** [comment]
What makes you think Alacritty isn't closing? When opening Alacritty from a terminal, does it not return to the prompt immediately?

This sounds like it's just a DE issue tbh.

**Comment by kchibisov** [comment]
Do you see alacritty in the process tree?

**Comment by chrisduerr** [comment]
> When opening Alacritty from a terminal, does it not return to the prompt immediately?

Please answer this question.

**Comment by dougg0k** [comment]
Before when I did -v it opened a new instance of it, regardless if from normal terminal or alacritty itself. I didnt check just with the command itself.

I had turned the laptop off, now I tried to turn it on, gave a grey screen on the login screen, seems related to nvidia gpu, trying to fix, so I am not able to check right now.

**Comment by dougg0k** [comment]
I fixed the login issue.

I just recorded a video showing it.

https://github.com/alacritty/alacritty/assets/10801221/4966fa81-257e-4b76-8d2a-1c3377e5ea4d

When I type alacritty to open another instance, a new window is open.

**Comment by kchibisov** [comment]
If you add

```toml
[env]
LIBGL_ALWAYS_SOFTWARE = "1"
```

in your config is it getting fixed? It seems like not our issue. It was also requested to try running from other terminal with `-v` and seeing if the alacritty itself exits. However alacritty doesn't try to connect to any running instance, it should create new when you run it again, thus it's likely an issue with DE or driver.

**Comment by dougg0k** [comment]
It doesnt.

But I see what you mean. Yeah, if I constantly exit and open a alacritty again through the terminal, it goes instantly, without any problems.

**Comment by dougg0k** [comment]
I suppose I have handed all the information you asked for, if you need anything else, let me know, I wont be opening `alacritty` on straight clicks, that was just because I had installed in the laptop at that time and noticed the issue and wanted to report it. 

I mostly use keyboards shorcuts which doesnt problem doesnt happen.

**Comment by lpnh** [comment]
> I just described why, but will do again, there is that spinning (loading indicator) that keeps rotating on the shortcut, indicating that the process has not yet closed (even though the window has closed), and also a bit after the spin is gone, I am still not able to open another Alacritty instance. It does nothing If I click on it to open. That is why.

I believe I am experiencing the same issue. When I launch Alacritty through a terminal command, it functions as expected: I can open, close, and instantly reopen it without any problems. However, attempting to initiate Alacritty using a shortcut or by clicking its icon leads to a persistent spinning cursor, which remains even after closing Alacritty. Moreover, I'm unable to relaunch it (either via shortcut or icon) for a brief period, about 7 to 8 seconds.

Based on what I've read in other issues here and after testing both Alacritty versions 0.13.1 and 0.14.0 (with and without the suggested patch), my understanding is that the problem might be related to GNOME itself. I was hopeful that the new GNOME version 45.4 would address this, but unfortunately, it has not. I genuinely miss using Alacritty.

**Comment by dougg0k** [comment]
Even if it were related to gnome, why only on alacritty?

**Comment by kanglib** [comment]
I experienced the same issue for Alacritty and Brave. Changing `StartupNotify` to `false` in the desktop file seems to solve the issue (a session restart required).

Perhaps related to #868?

**Comment by lhjok** [comment]
I have the same problem and sometimes when starting up the mouse will not show up over the Alacritty window. I use the Gnome environment and I found that if I start Alacritty using the terminal I have no problems. Both turning it on and off causes the mouse to be in a waiting state.

**Comment by lhjok** [comment]
> > When opening Alacritty from a terminal, does it not return to the prompt immediately?
> 
> Please answer this question.

If you start it in a terminal, there will be no problem. This problem only occurs when you start it from the desktop icon. I am using version 0.13.2, which is the latest version, but this problem still exists. This may be related to DE. This problem is not difficult to reproduce. Developers can test it in the Gnome environment. Other similar terminals do not have the same problem.

**Comment by riccardolardi** [comment]
same issue on arch & gnome 47

**Comment by kchibisov** [comment]
I still can not reproduce it on fresh fedora 40 with alacritty installed from the fedora reposity. I start just by pressing `Super` and then typing alacritty in the prompt.

I've tested this issue multiple times and there's no way for me to reproduce it.

**Comment by dougg0k** [comment]
I suppose a solution was provided.

Find the `.desktop` config, usually at `/usr/share/applications/com.alacritty.Alacritty.desktop` and change `StartupNotify` to `false`.

**Comment by kchibisov** [comment]
It doesn't make any sense that `StartupNotify` will affect close.

I do understand _start_, but close? There was also a bug with startup notify, which master _fixed_, but not sure if it's related.

**Comment by johananl** [comment]
I confirm that setting `StartupNotify` to `false` solves the problem for me.

AFAICT it indeed affects **start**, not close, but it's easy to think it affects close because at least I first noticed the issue when starting Alacritty, closing it right away and then trying to start it again. The spinning mouse cursor shows up for me immediately after *starting* Alacritty and stays around for roughly 10 seconds even after closing Alacritty, that is even when I see Alacritty disappearing from the process tree. I guess when the user just starts Alacritty, maximizes the window and goes about his/her business it's easy to miss the fact that hovering the Gnome dock shows a spinning cursor that's gone after some seconds.

**Comment by kchibisov** [comment]
Is it still an issue with the latest 0.15.0-rc1?

**Comment by johananl** [comment]
> Is it still an issue with the latest 0.15.0-rc1?

Yes, as long as I have `StartupNotify=true` in the .desktop file the bug reproduces with `v0.15.0-rc1`.

**Comment by kchibisov** [comment]
I'd assume that this is on X11 and not wayland?

**Comment by johananl** [comment]
> I'd assume that this is on X11 and not wayland?

I'm on Wayland.

**Comment by johananl** [comment]
Yes, I'm running `alacritty 0.15.0-rc1 (ad4cc125)`. It's indeed from `/usr/loca/bin` but I've placed the binary there after building using `cargo` from the correct Git tag.

**Comment by johananl** [comment]
>I can not reproduce the issue and the window gets properly activated on gnome, though, it was not with versions before 0.14.0.

:man_shrugging: 

Keep in mind that at least in my case I have to logout/login after modifying `StartupNotify` if that's what you're doing to test.

**Comment by kchibisov** [comment]
Put this in your config and upload the log from opening alacritty with `StartupNotify=true` in the desktop file.

```
[debug]
persistent_logging = true
log_level = "Debug"
```

**Comment by johananl** [comment]
Yes sir! :saluting_face: 

```
[0.037131370s] [INFO ] [alacritty] Using EGL 1.5
[0.037272633s] [DEBUG] [alacritty] Picked GL Config:
                                     buffer_type: Some(Rgb { r_size: 8, g_size: 8, b_size: 8 })
                                     alpha_size: 8
                                     num_samples: 0
                                     hardware_accelerated: true
                                     supports_transparency: Some(true)
                                     config_api: Api(OPENGL | GLES1 | GLES2 | GLES3)
                                     srgb_capable: true
[0.072197213s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Medium, load_flags: LoadFlag(TARGET_LIGHT), render_mode: "Normal", lcd_filter: 1 }
[0.078703287s] [INFO ] [alacritty] Window scale factor: 1
[0.080139227s] [DEBUG] [alacritty] Loading "monospace" font
[0.090212667s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Book, load_flags: LoadFlag(TARGET_LIGHT), render_mode: "Normal", lcd_filter: 1 }
[0.102452638s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: LoadFlag(TARGET_LIGHT), render_mode: "Normal", lcd_filter: 1 }
[0.115098419s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Oblique, load_flags: LoadFlag(TARGET_LIGHT), render_mode: "Normal", lcd_filter: 1 }
[0.127309762s] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold Oblique, load_flags: LoadFlag(TARGET_LIGHT), render_mode: "Normal", lcd_filter: 1 }
[0.133106320s] [INFO ] [alacritty] Running on Mesa Intel(R) Xe Graphics (TGL GT2)
[0.133136794s] [INFO ] [alacritty] OpenGL version 4.6 (Core Profile) Mesa 23.2.1-1ubuntu3.1~22.04.3, shader_version 4.60
[0.133144662s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.140358352s] [DEBUG] [alacritty] Enabled debug logging for OpenGL
[0.140475835s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.152027377s] [INFO ] [alacritty] Cell size: 9 x 18
[0.152070004s] [INFO ] [alacritty] Padding: 0 x 0
[0.152076639s] [INFO ] [alacritty] Width: 800, Height: 600
[0.152125794s] [INFO ] [alacritty] PTY dimensions: 33 x 88
[0.155464115s] [INFO ] [alacritty] Initialisation complete
[0.186579215s] [DEBUG] [alacritty_terminal] Ignoring unknown mode 7727 in set_private_mode
[19.000842807s] [INFO ] [alacritty] Goodbye
```

**Comment by kchibisov** [comment]
The log looks _cut_(start of it) and it seems that the startup notify token is not passed based on that to the application at all, while it should. You can test with `XDG_ACTIVATION_TOKEN="token" alacritty -vv` and see the `token: "token"` somewhere in the log, that's what `StartupNotify` should do, since gnome sets the token and we just load it.

I'm not sure which gnome version you have, could be just a gnome bug, since on fedora everything is fine and gnome properly activates alacritty.

**Comment by johananl** [comment]
That's the entire log file. New log files written by Alacritty also have the same format for me.

My Gnome version is `42.9`.

In any case, I have a very functional workaround and don't see a need to spend more time on this if I'm the only one with this problem.

Thanks a lot for your help (and for maintaining a superb terminal emulator).

**Comment by kchibisov** [comment]
Oh, that gnome version could explain that, since it's likely doesn't have startup notify for wayland at all in it, thus it just breaks for you since it expects some kind of startup notify, but it's not even present in it.

So your option would be to only wait for gnome to update, since it's _gnome bug_.
