### ISSUE TITLE
Cursor not changing in vi mode

### ISSUE THREAD

**Issue by maipley** [alacritty/alacritty#7702]
~~The vi_mode_style wont change the cursor when in vi mode, it keeps the value from the cursor style.~~
~~This a part of my alacritty.toml.~~
>~~[cursor]~~
>~~style = { shape = "Beam" }~~
>~~vi_mode_style = { shape = "Block" }~~

~~In my .zshrc i only have aliases and autocompletition, no cursor customization.~~

Edit: Problem solved, i was confused regarding the vi mode

### System

OS: Linux Arch
Version: alacritty 0.13.1 (fe2a3c56)The vi_mode_style wont change the cursor when in vi mode, it keeps the value from the cursor style.
This a part of my alacritty.toml.
>[cursor]
>style = { shape = "Beam" }
>vi_mode_style = { shape = "Block" }

In my .zshrc i only have aliases and autocompletition, no cursor customization.
Linux/BSD: X11, awesomewm with picom
Shell: zsh
Font: `Hack Nerd Font`

**Comment by chrisduerr** [comment]
How are you entering vi mode? Are you running tmux?

**Comment by maipley** [comment]
Oh sorry, i thought the vi mode was something else.
It works properly.
But i do have a another problem, after exiting neovim, with nvchad, the cursor stays as a block instead of returning to a beam.

**Comment by kchibisov** [comment]
```lua
-- Restore cursor to Beam on leave.
vim.api.nvim_create_autocmd({ 'VimLeave', 'VimSuspend' }, {
  pattern = { '*' },
  callback = function()
    vim.o.guicursor = "a:ver100"
  end
})

```

**Comment by maipley** [comment]
Sorry, where do i put this code?
custom/init.lua?

**Comment by kchibisov** [comment]
idk, whereever you want, it's autocmd.

you can write something like that with vimscript if that's what you use.

**Comment by maipley** [comment]
Thanks and sorry for the problems!
