### ISSUE TITLE
Incorrect font rendering

### ISSUE THREAD

**Issue by pslizik-ibl** [alacritty/alacritty#7704]
Hello,

I decided to try Alacritty. I set the font to "Fira Code", however, the rendered characters are too wide and kerning is incorrect.

Here is a comparison of Kitty, Sakura and Alacritty with the same font configured:

![terminals](https://github.com/alacritty/alacritty/assets/140083141/1adc00aa-e1ea-40ae-b76e-f92e566086c5)

These are the relevant lines from the configuration files:

**Kitty:**
```
font_family      Fira Code Regular
bold_font        Fira Code Bold
italic_font      Fira Code Italic
bold_italic_font Fira Code Bold Italic

font_size 14.0
```

**Alacritty:**
```
[font]
normal = { family = "Fira Code Regular", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 14.0
```

Is there something that escaped my attention?

### System

**OS:** Ubuntu 20.04.6 LTS (focal)
**Version:** `alacritty 0.14.0-dev` (identified as `0.13.1+1-20240205T060114~focal-20e3040b` by `apt list`)
**Windowing system:** X11
**Desktop:** GNOME 3.36.8

### GNOME Tweaks

**Hinting:** Slight  (the default; selected from Full, Medium, Slight, None)
**Antialiasing:** Subpixel (for LCD screens) (the default; selected from Subpixel (for LCD screens), Standard (grayscale), and None)
**Scaling Factor:** 1,03 (but setting it to the default value of 1.0 does not fix the problem)

Thank you for having a look!

**Comment by kchibisov** [comment]
try

normal = { family = "Fira Code", style = "Regular" }

**Comment by pslizik-ibl** [comment]
So easy? Yes, it helped. Thank you very much!
