### ISSUE TITLE
Color indexes seem to differ with other terminal emulators

### ISSUE THREAD

**Issue by squeaktoy** [alacritty/alacritty#7705]
Here's a screenshot of st:
![image](https://github.com/alacritty/alacritty/assets/147341824/c16720a7-5fdd-4527-8a4a-0087016aee31)
As you can see, directories with the ls command are using color index 12.

Here's a screenshot of alacritty:
![image](https://github.com/alacritty/alacritty/assets/147341824/e4ed6223-1786-414d-9a08-103e9539cd25)
As you can see, directories with the ls command are using color index 4.

Why is there a difference in which color index is used between these two terminal emulators?
I can't seem to figure this out and I would like to change this behavior.

### System

OS: Linux
Version: alacritty 0.12.3
Graphical stack: X11, i3

**Comment by squeaktoy** [comment]
Well, in neither st nor alacritty I don't have `LS_COLORS` set at all, so I'm still confused as to where to difference is coming from.

**Comment by chrisduerr** [comment]
A lot of distros poorly set `LS_COLORS` by running `dircolors` for xterm terminals. Alacritty isn't XTerm so you need to run it yourself.

**Comment by squeaktoy** [comment]
It doesn't seem to fix this issue if I set the LS_COLORS based on the dircolors command.

**Comment by chrisduerr** [comment]
Try `TERM=xterm-256colors dircolors`.

**Comment by squeaktoy** [comment]
Nope, still no difference.

**Comment by kchibisov** [comment]
Set `draw_bold_text_with_bright_colors` to `true`
