### ISSUE TITLE
Alacritty displays only cursor block on Wayland until another application opens

### ISSUE THREAD

**Issue by axelvanherle** [alacritty/alacritty#7707]
### System

OS: Linux (endeavouros, linux-surface kernel)
Version: `alacritty 0.13.1 (fe2a3c56)`
Linux/BSD: Wayland, Gnome

### Logs
[alacritty_log.txt](https://github.com/alacritty/alacritty/files/14225293/alacritty_log.txt)

I bind my terminal emulator to `Super + T`. However, when i do this for alacritty i get an empty screen with only a cursor block like this.
![Screenshot from 2024-02-09 19-37-40](https://github.com/alacritty/alacritty/assets/94362354/293c8750-d15b-4324-9999-6e595c994fbd)

This is until i open another terminal, or any other application that (it seems like) displays text. I run a quite modified zsh config, but even turning this and my alacritty config off it doesnt seem to do anything. I am running a modified kernel, but even on the regular kernel this issue persists. This however is not an issue on xorg.

All keypresses get registered, it just seems to be stuck on that cursor block until i open another window of anything. If anyone requires any more info, im happy to provide!

**Comment by kchibisov** [comment]
it's a bit generally broken on gnome now https://github.com/alacritty/alacritty/issues/7465

**Comment by axelvanherle** [comment]
I missed that one, my bad! Thanks for the quick reply.
