### ISSUE TITLE
Alacritty not reading shell info correctly from macOS DirectoryService?

### ISSUE THREAD

**Issue by victorhooi** [alacritty/alacritty#7710]
I'm having some issues getting Alacritty to correctly read the configured shell for my user on macOS.

(On macOS, this is stored not in /etc/passwd, but in the inbuilt DirectoryService - [source](https://superuser.com/questions/191330/users-dont-appear-in-etc-passwd-on-mac-os-x)).

(This is a follow-on from an [earlier issue](https://github.com/alacritty/alacritty/issues/7653), but that got closed prematurely, and I think my last [comment](https://github.com/alacritty/alacritty/issues/7653#issuecomment-1913415315) got lost. Also, I've amended the heading to make it clearer that Alacritty doesn't seem to be reading from the macOS DirectoryService specifically).

Here's the contents of my `/etc/shells` file:
```
❯ cat /etc/shells 
# List of acceptable shells for chpass(1).
# Ftpd will not allow users to connect who are not using
# one of these shells.

/bin/bash
/bin/csh
/bin/dash
/bin/ksh
/bin/sh
/bin/tcsh
/bin/zsh
/opt/homebrew/bin/fish
```

I set my shell to `fish` using the following command:
```
❯ chsh -s /opt/homebrew/bin/fish 
Changing shell for victorhooi.
Password for victorhooi: 
chsh: no changes made

~ took 2s 
```

I then confirmed with the dscl command that the shell is set correctly:
```
❯ dscl . -read /Users/victorhooi UserShell
UserShell: /opt/homebrew/bin/fish
```

And also, if I open up Alacritty (and it then opens up the zsh shell), the `SHELL` variable is set to point to `fish`:

```
env | grep SHELL
SHELL=/opt/homebrew/bin/fish
```

Do you know why Alacritty isn't correctly reading the shell?

**Comment by kchibisov** [comment]
If the `SHELL` is set before running alacritty it'll use that, there's no way that it won't use it, since it avoids reading the passwd all together that way, etc.

Do you use tmux?

**Comment by kchibisov** [comment]
it's also all with default config, right? `--config-file /dev/null`

**Comment by victorhooi** [comment]
I have tmux installed (via homebrew), but I'm not using it here. (I wanted to get Alacritty working first).

I also deleted my `~/.config/alacritty.toml file` just in case it was interfering with debugging this issue - for posterity previously it contained:
```
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
```
I installed Alacritty on macOS using the Homebrew cask here:

* https://formulae.brew.sh/cask/alacritty
* https://github.com/Homebrew/homebrew-cask/blob/1cb832072b976bb64e92bd3bf2f7188cf527385b/Casks/a/alacritty.rb

One weird thing I've just noticed - if I start Alacritty via /Applications/Alacritty.app or macOS Spotlight - the issue occurs (i.e. Alacritty opens up to zsh, instead of the user's configured shell, which is fish).

However, if I launch Alacritty from the command line - e.g. from macOS's Terminal app, Alacritty has the correct behaviour (i..e it opens with the fish shell).

(I found this out when I tried your suggestion of launching with `--config-file /dev/null` - then tried removing that option).

Is there any reason that the /Applications/Alacritty.app doesn't seem to pickup the shell correctly here?

**Comment by chrisduerr** [comment]
> Is there any reason that the /Applications/Alacritty.app doesn't seem to pickup the shell correctly here?

It's just that $SHELL is set when launching from another terminal.

**Comment by chrisduerr** [comment]
Closing since I have no interest in implementing yet another macOS-specific idiosyncrasy. If they wanted things to work, at the very least they could set `SHELL`, so I can only assume they don't want user to be able to change their shell.

If someone else wants to give this a try I'm happy to look at a PR, but making no promises it will actually get merged should it be non-trivial.

**Comment by Alaz-Oz** [comment]
<img width="944" alt="Screenshot 2024-07-29 at 13 01 33" src="https://github.com/user-attachments/assets/9f5f50ff-9502-4f01-90ae-491c7dd84ad5">
@chrisduerr I don't get what you are talking about. But on my system at least, the SHELL env is set correctly, it shows up in neofetch and also I have output the $SHELL env var, but for some reason the `alacritty` still opens up the fish shell, In my `alacritty.toml` I have set colorscheme and fonts only.

From my POV, the `alacritty` is at fault somehow for not reading the `$SHELL` or using some cache?? ...maybe?

**Comment by Alaz-Oz** [comment]
I got the fix, The shell variable don't gets updated by the `launchd` daemon until it is restarted, so a logout and re-login fixes all the things.
