### ISSUE TITLE
[feature request] Would be nice to have an `ALACRITTY_OS` env added

### ISSUE THREAD

**Issue by mxaddict** [alacritty/alacritty#7712]
Would be nice to have an env value set by allacritty that tells the current os.

Something like `ALACRITTY_OS` which would have the current OS.

So when running on macOS `ALACRITTY_OS` would be `darwin`

On linux `ALACRITTY_OS` would be `linux`

On windows `ALACRITTY_OS` would be `winblowz`

Or something like that.

Then possibly allow substitution of `env` values during `import` in configs like:

```toml
import = [
"~/.config/alacritty/${ALACRITTY_OS}.toml",
"~/.config/alacritty/${SOME_OTHER_ENV}.toml",
]
```

**Comment by mxaddict** [comment]
Let me know if a feature like this would be welcome, I can create a PR for this.

**Comment by chrisduerr** [comment]
OS-specific imports are not desired. Imports are already optional, if you don't want something to be loaded just don't put it there.

**Comment by mxaddict** [comment]
This is not a OS specific import feature really, it's more like adding a `OS` to the env values.

Which could be used for other reason (I have some fish scripts that use `KITTY_OS` for example

Also, import with env parsing can be for setting themes via a simple env value.

These are just 2 use cases for this, but I'm sure there can be more.

**Comment by mxaddict** [comment]
As for the OS env value, can be as simple as :

```diff
diff --git a/alacritty_terminal/src/tty/mod.rs b/alacritty_terminal/src/tty/mod.rs
index d1bb023c..e54a1eca 100644
--- a/alacritty_terminal/src/tty/mod.rs
+++ b/alacritty_terminal/src/tty/mod.rs
@@ -91,6 +91,8 @@ pub fn setup_env() {
     let terminfo = if terminfo_exists("alacritty") { "alacritty" } else { "xterm-256color" };
     env::set_var("TERM", terminfo);

+    env::set_var("OS", std::env::consts::OS);
+
     // Advertise 24-bit color support.
     env::set_var("COLORTERM", "truecolor");
```

**Comment by mxaddict** [comment]
Tested on a local build of alacritty:
<img width="436" alt="Screenshot 2024-02-10 at 10 31 28 PM" src="https://github.com/alacritty/alacritty/assets/1060905/47654326-49fa-4e91-b3ff-014e57b94818">

**Comment by kchibisov** [comment]
You can detect OS yourself in shell scripts. e.g. with `uname` (if it doesn't exist, it's likely windows).

**Comment by mxaddict** [comment]
> You can detect OS yourself in shell scripts. e.g. with `uname` (if it doesn't exist, it's likely windows).

True, but this is a more elegant/reliable way of getting it, and it's a single line to add to alacritty.

**Comment by mxaddict** [comment]
I mean the PR is literally as single line of code 😄

**Comment by kchibisov** [comment]
is a single line in your shell `uname -o`.

**Comment by chrisduerr** [comment]
> True, but this is a more elegant/reliable way of getting it, and it's a single line to add to alacritty.

It's neither more elegant nor more reliable.

**Comment by mxaddict** [comment]
I see
