### ISSUE TITLE
Create tabs on linux environments

### ISSUE THREAD

**Issue by placintaalexandru** [alacritty/alacritty#7716]
The current [man-page](https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd) says that the `CreateNewTab` binding is macOs exclussive. It would be nice if this action was available at least on Linux environments

### System

OS: `Ubuntu 22.04`
Version: `alacritty 0.14.0-dev (117719b3)`
Linux/BSD: `-`

**Comment by kchibisov** [comment]
tabs should be provided by compositor/wm. On macOS they are so we have them there since on macOS tabs is just a window with a flag for it to be _tab_.
