### ISSUE TITLE
Icon takes a while to show after opening alacritty

### ISSUE THREAD

**Issue by msmafra** [alacritty/alacritty#7717]
Strange behavior on my machine. I recently did a fresh install of Fedora, but this was happening before.
Using both cargo installed or dnf installed Alacritty, when opened it takes close to 20seconds to show its icon on Gnome's dash. It's the only app doing that. I tried deleting my config files, editing the .desktop file removing and adding parameters from the Desktop Entry specs, but no luck.
Also, looking at the documentation about installing it manually I noticed that the Alacritty.svg file is sent to /usr/share/pixmaps instead of /usr/share/icons/hicolor/scalable/apps/, not sure if this can have any influence.

### System

OS: Fedora Workstation 39
Version: alacritty 0.13.1
Linux/BSD: X11

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
[alacrity-vv.log](https://github.com/alacritty/alacritty/files/14230240/alacrity-vv.log)
Keyboard and bindings: `alacritty --print-events`
[alacrity-printevents.log](https://github.com/alacritty/alacritty/files/14230239/alacrity-printevents.log)

**Comment by detherminal** [comment]
I got the same problem on `Fedora 39, 0.13.1, Wayland`

**Comment by chrisduerr** [comment]
Is this exclusive to 0.13.1, or does it also apply to earlier versions? I don't really see in which universe this could be solely an Alacritty issue, considering all of this is handled by the DE.

**Comment by msmafra** [comment]
> Is this exclusive to 0.13.1, or does it also apply to earlier versions? I don't really see in which universe this could be solely an Alacritty issue, considering all of this is handled by the DE.

I agree, but it's the only program with that behavior. And while the Icon doesn't appear the mouse cursor spins waiting.

**Comment by chrisduerr** [comment]
> And while the Icon doesn't appear the mouse cursor spins waiting.

That just sounds like it's waiting for the startup notification, which should be optional. You can generally disable this in your WM, have you tried that?

**Comment by msmafra** [comment]
On Gnome my notifications are usually on Do not disturb, if that is what you mean.

Creating the file and testing every step, by adding fields pertaining to the desktop entry specification, made it not do it anymore. But. I tried some config similar to this before and it did not solve the problem. I'll be testing and also check if it's not some king of cache related to the update-desktop-databas and/or desktop-file-install commands.

```
[Desktop Entry]
Type=Application
TryExec=alacritty
Exec=alacritty
Icon=Alacritty
Terminal=false
Categories=System;TerminalEmulator;

Name=Alacritty
GenericName=Terminal
Comment=A fast, cross-platform, OpenGL terminal emulator
StartupNotify=true
StartupWMClass=Alacritty
Actions=New;
X-Desktop-File-Install-Version=0.26 # <-- this is not added by me

[Desktop Action New]
Name=New Terminal
Exec=alacritty
```

**Comment by kchibisov** [comment]
Try `StartupNotify=false`.

**Comment by msmafra** [comment]
> Try `StartupNotify=false`.

Yes, that works. 
Did more tests yesterday and update-desktop-database seems to be broken or do not do anything if not much has changed or is a Gnome thing. Also desktop-file-install won´t do anything but spare you from copying the .desktop file from one place to the /usr/share/applications and adds X-Desktop-File-Install-Version=0.26 to the file, which I did not find in the desktop entry specifications.
Modifications to the dot desktop file only worked for me effectively and consistently when I logged off and and back on or rebooting. Not even with Alt + F2 and r (for X11 sessions only) made a difference.

```
[Desktop Entry]
Version=1.1
Type=Application
TryExec=alacritty
Exec=alacritty
Icon=Alacritty
Terminal=false
Categories=System;TerminalEmulator;
Keywords=shell;prompt;command;commandline;cmd;
Name=Alacritty
GenericName=Terminal
Comment=A fast, cross-platform, OpenGL terminal emulator
StartupNotify=false
StartupWMClass=Alacritty
Actions=New;
X-Desktop-File-Install-Version=0.26

[Desktop Action New]
Name=New Terminal
Exec=alacritty

```
Thanks you kindly!

**Comment by msmafra** [comment]
> I got the same problem on `Fedora 39, 0.13.1, Wayland`

With @kchibisov 's tip and logging off and back on, it's solved for me.
