### ISSUE TITLE
extra character when rendering document

### ISSUE THREAD

**Issue by Yousuf28** [alacritty/alacritty#7718]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Windows
Version: alacritty 0.12.2 (9d9982d)
Linux/BSD: X11/Wayland, DE or Compositor and WM

### Logs

when I do `tldr tar`, documentation print like this
<img width="689" alt="Capture" src="https://github.com/alacritty/alacritty/assets/31291716/7c9f3072-4ee1-444f-b13c-cfa740091129">

but when I do `ls` or `ll` alias for `ls -alh`, it print everything fine
<img width="390" alt="Capture2" src="https://github.com/alacritty/alacritty/assets/31291716/ab8eb5ae-b9ec-407b-adc3-ccc8e47d20b8">

If I do `tldr tar` in git bash terminal everything print fine, like this
<img width="497" alt="Capture3" src="https://github.com/alacritty/alacritty/assets/31291716/d53d4bcc-31da-43c2-b9d9-1b45ec7f0e49">

I have tried different font but no luck.

how to render properly? what is this character `←[1m  ←[0m`? my alacritty config [here](https://github.com/Yousuf28/dotfile/blob/main/alacritty.yml)

**Comment by kchibisov** [comment]
> OS: Windows

windows conpty bug.
