### ISSUE TITLE
Alternative font control sequence support

### ISSUE THREAD

**Issue by OJFord** [alacritty/alacritty#7719]
I don't know how feasible it is, but `CSI n m` where `n` = 11..19 (inclusive) for alternative font selection could be great to have, perhaps configured like:
```toml
[font.alternate-1]
...
```

where the extant `[font]` is the default (`ESC [10m`)?

---

The potential use case that led me to come across this (rarely implemented?) standard was thinking it'd be nice to have stderr & stdout rendered differently, the former italic say.

If alacritty supported this feature, a shell could prefix `ESC [1nm` where `n` = descriptor number say; then if no alternative font was defined it would fall back to the default, and if there was it would render accordingly.

I realise as I write this that I'm a bit naive as to the shell->term interaction here; the shell is ultimately just writing to `/dev/fd/{1,2}` (or other extra descriptors, but the term won't care about them?) and alacritty reads from there? So actually it would be perfectly possible to implement this just within alacritty if it were desired, but there's some elegance perhaps (and certainly flexibility) in ignoring this specific use case and supporting the control sequence generically.

**Comment by kchibisov** [comment]
>The potential use case that led me to come across this (rarely implemented?) standard was thinking it'd be nice to have stderr & stdout rendered differently, the former italic say.

That's not a good example, italic is already part of the styles and you can request it.

In general using completely different fonts instead of styles or color coding sounds like not a great choice. Keep in mind that we also can't distinguish what stdout or stderr is.

**Comment by nixpulvis** [comment]
Almost seems easier to just make your own font at this point.

I've always thought STDOUT and STDERR could use a bit more separation my self, but then again, I hate thinking about multiplexers and buffers sometimes too, so it's nice that it all just kinda works and I forget about STDERR altogether sometimes.

**Comment by OJFord** [comment]
@kchibisov 

> That's not a good example, italic is already part of the styles and you can request it.

I can request it yes, but not as far as I know dynamically, or differently for stdout vs stderr per that example.

> Keep in mind that we also can't distinguish what stdout or stderr is.

I did say I wasn't clear how that worked. But that just motivates it even more? If Alacritty were just rendering the font according to the control sequence it doesn't need to care where it came from or what it meant to the shell.

@nixpulvis I do make my own font, but I don't see the link? Obviously a font does not know when it's being used for stdout or stderr (or neither) so I don't understand?

**Comment by kchibisov** [comment]
>I can request it yes, but not as far as I know dynamically, or differently for stdout vs stderr per that example.

printf "\e[1mbold\e[0m\e[3mitalic\e[1mbolditalic\n"

application should control that no-one besides the application knows that. if you want some custom styling for stderr for every app you should pipe its output and somehow make it interleaved applying styles on the fly.

**Comment by nixpulvis** [comment]
> @nixpulvis I do make my own font, but I don't see the link? Obviously a font does not know when it's being used for stdout or stderr (or neither) so I don't understand?

Sorry, I made the comment about making a font somewhat off the cuff and too quickly.

I too have thought it might be nice to be able to distinguish STDERR and STDOUT. Now I'm stuck trying to make it work in my head without feeling like it's hacking too many escape sequences in my streams.

> if you want some custom styling for stderr for every app you should pipe its output and somehow make it interleaved applying styles on the fly.

This actually sounds pretty simple and like it might be a lot more elegant than what I was originally thinking, still makes me worry I'll get the buffering wrong since I can't seem to do anything right these days.

**Comment by nixpulvis** [comment]
>  If Alacritty were just rendering the font according to the control sequence it doesn't need to care where it came from or what it meant to the shell.

Now I'm wondering what the memory imprint of these kind of changes to STDOUT/ERR might be... but this thought experiment is also unlikely to go anywhere for me at this point tonight.

**Comment by OJFord** [comment]
@kchibisov 
> if you want some custom styling for stderr for every app you should pipe its output and somehow make it interleaved applying styles on the fly.

Yes, that is exactly what I proposed doing in that example?

But `\e[10m`, `\e[11m`, ..., `\e[20m` (for default, alternate 1-9, and gothic font) are not afaik supported?
