### ISSUE TITLE
CLI -o config overrides should accept aliases as documented

### ISSUE THREAD

**Issue by w4v3** [alacritty/alacritty#7720]
### Expected behavior
As indicated by `man alacritty`, the `-o` option can be used to override configuration from the `alacritty.toml` config file with the properties specified by `man 5 alacritty`. One would therefore expect that
```alacritty -o 'colors.cursor.cursor="CellBackground"'```
leads to an invisible cursor.

### Actual behavior
Instead, it gives the error
```Unable to override option 'colors.cursor.cursor="CellBackground"': Field 'cursor' does not exist```
and no change to the background color is effected.

### Workaround
Inspecting the source code, this appears to stem from the fact that the `colors.cursor` configuration option is an `InvertedCellColors` struct, for which `cursor` is an alias for a property named `background`. Indeed,
```alacritty -o 'colors.cursor.background="CellBackground"'```
yields the desired result. The `-o` overrides should resolve those aliases since only the aliases are used in the documentation.

### Possible cause
Digging a bit deeper, I think the relevant part of the code is the function `derive_deserialize` in `alacritty/alacritty_config_derive/src/config_deserialize/de_struct.rs` which implements `SerdeReplace` without using the result of `fields_deserializer` which includes the substitution of aliases.

### System

OS: Linux 6.7.4-arch1-1
Version: alacritty 0.13.1 (fe2a3c56)
Compositor: sway

**Comment by placintaalexandru** [comment]
The problem is [here](https://github.com/alacritty/alacritty/blob/master/alacritty_config_derive/src/serde_replace.rs#L51).
This is what's generated when I look with `cargo expand`:
```rust
#[allow(clippy::extra_unused_lifetimes)]
    impl<'de> alacritty_config::SerdeReplace for InvertedCellColors {
        fn replace(
            &mut self,
            value: toml::Value,
        ) -> Result<(), Box<dyn std::error::Error>> {
            match value.as_table() {
                Some(table) => {
                    for (field, next_value) in table {
                        let next_value = next_value.clone();
                        let value = value.clone();
                        match field.as_str() {
                            "foreground" => {
                                alacritty_config::SerdeReplace::replace(
                                    &mut self.foreground,
                                    next_value,
                                )?
                            }
                            "background" => {
                                alacritty_config::SerdeReplace::replace(
                                    &mut self.background,
                                    next_value,
                                )?
                            }
                            _ => {
                                let error = {
                                    let res = ::alloc::fmt::format(
                                        format_args!("Field \"{0}\" does not exist", field),
                                    );
                                    res
                                };
                                return Err(error.into());
                            }
                        }
                    }
                }
                None => *self = serde::Deserialize::deserialize(value)?,
            }
            Ok(())
        }
    }
```

The `alias=cursor` is not used in the replace
