### ISSUE TITLE
[Suggestion] Optional "light" and "dark" theme colors that follow the system theme

### ISSUE THREAD

**Issue by DarkArc** [alacritty/alacritty#7723]
Many applications now have light and dark color schemes and can integrate with the system to match its color scheme as it switches between light and dark modes.

It would be great if two color schemes could be specified in alacritty (one for light and one for dark) and it could pick which color scheme to use based on the system theme.

My personal use case is that for laptop use, depending on the environment I'm in I prefer light (e.g., outside on a patio, in a park, a sunny coffee shop, etc) or dark colors (at night, in an darker office, etc). It's great to have all of my applications automatically switch over to a light or dark theme just by toggling the system theme.

**Comment by chrisduerr** [comment]
Not interested in handling this inside of Alacritty.

**Comment by DarkArc** [comment]
Unfortunately that means this will go back to being a toy for me; but it's your project. Thanks for the consideration :)

**Comment by jonathanslenders** [comment]
For what it's worth, there are multiple terminal emulators that support this:
- Ghostty (out of the box)
- Wezterm (with some Lua scripting)
- Contour (out of the box)

On top of this, the Mode 2031 spec defines how applications in the terminal can query the terminal theme and adjust light/dark mode accordingly. See: https://github.com/contour-terminal/contour/blob/f3c3334aa5c861348c5bbe8ffe572c872eef2e08/docs/vt-extensions/color-palette-update-notifications.md

NeoVim recently merged a patch to support 2031. I made a patch for tmux to support and proxy mode 2031. ( https://github.com/tmux/tmux/issues/4269#issuecomment-2541469367 )

@chrisduerr : Please reconsider. I don't think it's feasible to support mode 2031 from outside Alacritty.

**Comment by Rudxain** [comment]
Considering [DL exists](https://github.com/rust-dark-light/dark-light), this seems trivial to implement. I'm willing to open a PR, but I don't have time this month (or June)

> there are multiple terminal emulators that support this:

Also `gnome-{terminal,console}`. Sadly, Termux doesn't
