### ISSUE TITLE
[Issue] MacOS Clear Screen/Ctrl+L misbehaviour

### ISSUE THREAD

**Issue by psadi** [alacritty/alacritty#7724]
### System

OS: macOS
Version: `alacritty 0.13.1 (fe2a3c5)`

### Logs
print-event logs when the issue occues
[alacritty --print-events](https://github.com/alacritty/alacritty/files/14241631/events.log)

### Description

With Transparent window config, Clear screen and `Ctrl+L` misbehaves.
The font offset gets messed up each time i use `Ctrl+L`

![gif](https://github.com/alacritty/alacritty/assets/22428691/0564ee9c-1c35-48b2-9ba7-bfd115f721d2)

**Comment by chrisduerr** [comment]
Which macOS version is this? I would expect things to always look they way it does after you press Ctrl+L.

**Comment by psadi** [comment]
Currently on MacOS Sonoma, Im able to reproduce the same on other Mac devices.

**Comment by psadi** [comment]
Yes it does, even on full screen.

The issue doesn't occur if I set the decorations to full.

**Comment by chrisduerr** [comment]
Yeah this is a known issue that has an issue somewhere in the backlog.

**Comment by psadi** [comment]
Hi @chrisduerr 

Please help share or link the backlog issue, would like to follow on the fix (whenever that is)

**Comment by chrisduerr** [comment]
https://github.com/alacritty/alacritty/issues/1671
