### ISSUE TITLE
command recall with up arrow at a mysql> prompt issues

### ISSUE THREAD

**Issue by dork3nergy** [alacritty/alacritty#7730]
When at mysql command prompt (via ssh), using the cursor keys to recall previous command results in corrupted text and the cursor moving up the screen to seemingly random positions each time up arrow is pressed.

I've added the alacritty.terminfo to the remote machine although $TERM is still set to xterm-256color. 

### System

OS: Linux-Manjaro-i3
Alacritty Version: 0.13.1
Linux/BSD: x11

**Comment by chrisduerr** [comment]
Could you share a video/screenshot? What makes you think this is an Alacritty issue.

Sounds like it's probably a system/mysql issue.

**Comment by dork3nergy** [comment]
As usual, the simple act of asking for help seems to have fixed the problem.  It's been an issue for me since I switched from urxvt about 3 months ago. Nevertheless, it looks like I jumped the gun a bit here.

Should it start acting up again, I will certainly grab a video.
