### ISSUE TITLE
Change terminal background color when SSHing

### ISSUE THREAD

**Issue by jjant** [alacritty/alacritty#7735]
I often work with cloud desktops to do development on different platforms, sometimes I have 3 terminals open at the same time: 1 for my machine, 2 for remote machines. Every so often I mix the terminals up.

Is there a way to color the background when on an SSH session (and ideally based on the host name as well)?

### System

OS: macOS 14.3
Version: `alacritty 0.13.1`

**Comment by chrisduerr** [comment]
```
echo -e "\e]11;rgb:ffff/0000/ffff\e\\"
```

That's one option, for more consult https://invisible-island.net/xterm/ctlseqs/ctlseqs.html.

**Comment by nixpulvis** [comment]
I'm going to hedge a guess that @jjant actually wants to change the `colors.primary` for a specific window, which I do not think is possible at the moment, unless there's a way to identify windows by ID in some way I'm unaware of.
