### ISSUE TITLE
Feature request: distinct colour keys for foreground and background ANSI codes

### ISSUE THREAD

**Issue by pacien** [alacritty/alacritty#7744]
# Problem

Currently, ANSI colour codes are mapped to colours by name,
with no distinction between foreground and background colours.

For example, `colors.normal.blue` defines the colour of both ANSI codes
`34` (foreground blue) and `44` (background blue) to the same colour,
with no possibility to set two distinct ones.

This is problematic because colours look very different to the eye depending
on whether they're used for foreground text or background.

As an example: `034` is fine as foreground colour,
but would be better as a lighter shade as background (`044`):
![Example with the GitHub light high contrast theme](https://github.com/alacritty/alacritty-theme/blob/master/images/github_light_high_contrast.png?raw=true)
Most [other themes] have similar issues.

[other themes]: https://github.com/alacritty/alacritty-theme/tree/master

This is especially important since most terminal apps cannot guess colour
schemes to automatically invert the main text foreground colour.

# Solution?

Splitting the options to be able to set distinct foreground and background
colours would help obtaining better contrast and legibility.

# Considered workarounds

It is currently not possible to use `colors.indexed_colors` because this option
is restricted to `index >= 16` (only outside of the base ones).

**Comment by chrisduerr** [comment]
>  Would a patch for this be considered?

No.

**Comment by Krutonium** [comment]
Hi, Random wanderer here, I think this is a good idea as well, since it would enable better/customized contrast, which is helpful for people with bad eyes or displays, and so I would like to repeat the request for elaboration. Thanks!
