### ISSUE TITLE
Document how to write control characters on `keyboard.bindings`

### ISSUE THREAD

**Issue by jjant** [alacritty/alacritty#7749]
Hi, I want to use some keyboard bindings to use with Tmux.

This requires that my binding sends `<CTRL-B>` as part of _`chars`_.

The keyboard section of the docs is not really clear on how to do that: https://alacritty.org/config-alacritty.html (or what kind of strings `chars` can be at all).

**Comment by chrisduerr** [comment]
You just put whatever string you want to write. There are no limitations to that.

**Comment by jjant** [comment]
So how do I make it write `<CTRL-B>1`?

**Comment by kchibisov** [comment]
`chars = "\U00021"`
