### ISSUE TITLE
Conditional keyboard bindings

### ISSUE THREAD

**Issue by Re4GD** [alacritty/alacritty#7752]
I would like Ctrl+C to:

1. Copy when there is an active mouse selection

2. ClearSelection when there is a an active mouse selection and has already been copied

3. SIGINT when there is not an active mouse selection

Essentially I would like it to execute different keybindings depending on the current terminal state. Is the scenario I described currently possible? If not, is there a way to add logic to key binds?

**Comment by Re4GD** [comment]
Where should I ask this question?

**Comment by kchibisov** [comment]
It was discussed multiple times and the status is wontfix for that. There're no conditional bindings based on selection state.

**Comment by Re4GD** [comment]
Oh okay, thank you for your time.
