### ISSUE TITLE
A way to know exit code after `alacritty_terminal::tty::Shell::new` finishes

### ISSUE THREAD

**Issue by SomeoneToIgnore** [alacritty/alacritty#7753]
I use `alacritty_terminal::tty::Shell::new` options when creating `tty::new` for some bash-like command.
It works well, shows command's output in the terminal and sends `Event::Exit` after the command finishes execution, but there seems to be no way to know what is the `ExitStatus` of that command?

There's a way to get a reference to a `Child` via `Pty::child` (https://docs.rs/alacritty_terminal/latest/alacritty_terminal/tty/struct.Pty.html#method.child)
but the pty itself has to be moved into the `EventLoop` in order to init the terminal:
https://docs.rs/alacritty_terminal/latest/alacritty_terminal/event_loop/struct.EventLoop.html#method.new and the `Child` is not `Clone`.

I could get child's pid, but using `libc` on that pid as
```rust
fn get_exit_code(pid: u32) -> Option<i32> {
    let mut status = 0;
    let waitpid_result = unsafe { libc::waitpid(pid as libc::pid_t, &mut status, libc::WNOHANG) };
    if waitpid_result == -1 {
        None
    } else {
        if libc::WIFEXITED(status) {
            Some(libc::WEXITSTATUS(status))
        } else if libc::WIFSIGNALED(status) {
            None
        } else {
            None
        }
    }
}
```
does not seem to yield any result, I get `None`.

Is there a way to know the `ExitStatus` of that bash-like command? 
If not, would it be appropriate to add a way to do so? Should it be a field in the `Event::Exit` or is there a better way to design this?

**Comment by kchibisov** [comment]
There's no way to do so, and adding exit code event sounds like not a bad idea.
