### ISSUE TITLE
[Feature Request] Change underline thickness

### ISSUE THREAD

**Issue by exoess** [alacritty/alacritty#7754]
Feel like the title is pretty self explanatory, but basically I'd be nice if you could set the thickness of the underline/undercurl from a config value like a lot of other terminals have.

**Comment by kchibisov** [comment]
These metrics are coming directly from the font, don't see a point in manipulating them, if you think that some font uses too thin metrics, seems like you don't like the font in general and it'll render badly in other environments who use the underline thickness which comes from the font.

The underline position is also defined in the font itself, so arbitrary changing thickness breaks desired alignment.

**Comment by exoess** [comment]
there are fonts that don't contain the metadata for font thickness, causing the underlines to be incredibly thin, changing every singe fonts underline thickness is insane

**Comment by kchibisov** [comment]
The only fonts that don't provide such metrics are mostly the bitmap fonts. If you don't like the fallback we may tune the fallback computation in crossfont, but with most fonts I don't see an issue of something being overly thin.

**Comment by exoess** [comment]
wait, there isn't metadata for font thickness anywhere in any of the fonts i'm using, undercurls thickness is defined but not underline, and this isn't just bitmaps

**Comment by kchibisov** [comment]
Which platform are you on? Because underline thickness is the only option that is usually available, there's no such thing as undercurl thickness.

if you browse freetype it noly has underline, not undercurl for both thickness and position.

>This is a feature in almost every other terminal, why not add it to alacritty?

Why should we workaround fonts putting garbage in metadata breaking in every other client. I use the same font in every application, why should I change font metrics in e.g. 10 apps, when I can change font. All just sounds backwards to me.

**Comment by exoess** [comment]
I'm on linux, and from what I've seen fonts leave it up to the application to render underlines, not the fonts themselves, could you tell me where you're finding the data for underline thickness?

**Comment by kchibisov** [comment]
Look for https://github.com/alacritty/crossfont and search for `underline`.

Both core text and directwrite have APIs for that, if they produce garbage in some cases, we should look into that and do fallbacks, like we have on linux.

**Comment by exoess** [comment]
sorry, i don't know rust i can't really figure out how underline thickness is being calculated, and from what I've seen it doesn't come from the font, maybe I'm wrong I'm not sure, sorry if I'm being annoying or dumb this just doesn't make sense, no matter what font i use the underlines are always the same and that same thickness looks really strange when fonts have thicker strokes, the underlines just look out of place

**Comment by kchibisov** [comment]
Could you tell me which platform(Windows/macOS) are you on and what font are you using? So I can see myself what happens there, but I can ensure you that we try to get metrics for them from the font.

**Comment by exoess** [comment]
i'm on linux (as i said), and i tested it with maplemono, pointfree, and a font i kinda made

**Comment by kchibisov** [comment]
https://github.com/alacritty/crossfont/blob/master/src/ft/mod.rs#L154-L164

You're likely falling into that fallback. But the underline thickness is coming from freetype.

http://refspecs.linux-foundation.org/freetype/freetype-doc-2.1.10/docs/reference/ft2-base_interface.html

Search for `underline_thickness`. But all outline fonts I know have it set.

**Comment by kchibisov** [comment]
That's e.g. a starting point for it in iosevka https://github.com/be5invis/Iosevka/blob/main/params/parameters.toml#L97 , so you can play with that setting in your font.

**Comment by exoess** [comment]
could you give me a few more examples of fonts that define it within their metadata? i can't find an option to change that metadata within fontforge, because iosevka is made in a not very normal way, no font editor i've used as control over underline thickness

**Comment by kchibisov** [comment]
IBM Plex Mono, Noto fonts, Fira Code, Fira Mono, like lots of UI fonts have them set correctly.

**Comment by exoess** [comment]
so, i should setup every single font i make to have custom underline thickness, making fonts isn't easy, and it's not limited to my font, it just doesn't make sense to me to not render fonts in the way that almost every other font render does it, every terminal i've used and every render i've used allows you to change the underline thickness, sorry if this is dumb, i just find this really annoying

**Comment by kchibisov** [comment]
I'd suggest to have better fallback so it matches other UI fonts, I don't know why the logic of `/ 5` is in crossfont, and it likely won't look that great. And clearly things have good default, since I'm pretty sure GTK never forced you to set font underline thickness because it was too thin.

Probably pango has a good fallback, which I'm fine with following.

**Comment by exoess** [comment]
that would be better, pango has a very good fallback, sorry for making this such a thing it's just driving me crazy lol

**Comment by kchibisov** [comment]
Could you create an issue on crossfont repo pointing to some font which has issue and showing this font rendered in alacritty compared to e.g. IBM Plex Mono rendered in alacritty?

**Comment by exoess** [comment]
yea, i can, but i need to do it later lol, gotta get back to work
