### ISSUE TITLE
Strange clipboard behaviour with firefox on wayland

### ISSUE THREAD

**Issue by zeionara** [alacritty/alacritty#7755]
### System

OS: Linux
Version: `alacritty 0.13.1` 
Linux: Gentoo, Wayland, Hyprland

### Description

When copying content from a webpage using `copy` button, on `Shift+Insert` in terminal the previous clipboard content is inserted, even though `wl-paste` displays a correct value (see video here: https://youtu.be/Y_QyxTOy-l4).

When explicitly selecting the text on a webpage and hit `Ctrl+C`, then `Shift+Insert` in terminal, everything works fine.

**Comment by zeionara** [comment]
@chrisduerr could you please provide link to the original issue? Can't find it.

**Comment by kchibisov** [comment]
Shift+insert is primary selection buffer.

`wl-paste` is regular selection buffer.

Compare with `wl-paste -p`.

**Comment by zeionara** [comment]
> Shift+insert is primary selection buffer.
> 
> `wl-paste` is regular selection buffer.
> 
> Compare with `wl-paste -p`.

Thanks, when using `wl-paste -p` it is indeed in sync with what is pasted on `Shift+Insert`
