### ISSUE TITLE
Using integrated graphics rather than dedicated card

### ISSUE THREAD

**Issue by dougg0k** [alacritty/alacritty#7756]
Hi,

Pretty much the title, why alacritty are using Intel (integrated graphics) instead of nvidia, which I have confirmed to be the one that the system are using.

![ver](https://github.com/alacritty/alacritty/assets/10801221/57f5ba64-cfca-4f8b-b7ef-6cb5f0629e84)

It uses the gpu on the desktop, since it's only the GPU, but not the laptop.

**Comment by chrisduerr** [comment]
@kchibisov Afaik glutin does nothing to select which GPU should be used, correct? So should just be up to the OS to pick?

If you want to run it on your nvidia card, I'm pretty sure there's tools to select which graphics card you want to run an application on.

**Comment by kchibisov** [comment]
We can try to ask for faster config, so it'll try to pick nvidia, but we don't control which GPU to render to, since it's not generally present in OpenGL (with the way we pick configs).

**Comment by chrisduerr** [comment]
The thing is we also had people with the opposite issue in the past. So I don't think people would be happy about either.

**Comment by kchibisov** [comment]
I'm pretty sure they can force a particular vendor via libglvnd's env variable, I just forgot how to do that. One can also force specific driver for everyone there.

**Comment by dougg0k** [comment]
Why force rather than just follow what the OS are using as the main card? Or maybe even provide an option if anyone would ever need to force to a specific card due to whatever reason.

**Comment by kchibisov** [comment]
We don't pass preference or force anything. We explicitly pass that it should be picked automatically.

So your _automatically_ is not what you like and you want to _force_ it into faster GPU, bises the fact that the default is integrated.

**Comment by dougg0k** [comment]
I didnt mentioned anything about automatically, but the main gpu being used by the OS. 

Not in my case, default has always been nvidia, nothing was set.

**Comment by chrisduerr** [comment]
The default on a multi-GPU systems is pretty much always the integrated graphics.

**Comment by dougg0k** [comment]
I suppose that can be so in some OSs in laptops, as they consume less power.

Maybe this is not a problem, since they didnt provide a way to disable the integrated using the bios setup.

**Comment by nixpulvis** [comment]
Didn't we used to have a setting for this, or am I misremembering?

**Comment by kchibisov** [comment]
We never had explicit setting, but we always passed that we don't prefer any special config.

We can request _faster_ OpenGL config, but it means just always pick more performant, which doesn't mean _faster_, since it can require CPU copies.

**Comment by kchibisov** [comment]
The thing is that if you really want your nvidia card you can do that yourself with `libglvnd`'s variable iirc, you don't even need anything special from alacritty, the mechanism to make alacritty use specific GPU are already in place.

**Comment by chrisduerr** [comment]
> Didn't we used to have a setting for this, or am I misremembering?

I believe there was something in the `Info.plist` on macOS, but IIRC that doesn't work properly? Certainly wouldn't work on Linux.
