### ISSUE TITLE
Windows launched with `alacritty msg create-window` should inherit environment, like windows launched with `alacritty`

### ISSUE THREAD

**Issue by justinlovinger** [alacritty/alacritty#7757]
As is, `alacritty msg create-window` is often not usable for running commands in separate windows.

**Comment by chrisduerr** [comment]
I don't see how this would be intuitive to any user. If it's "often not usable for running commands in separate windows", that sounds like your environment is just messed up?

**Comment by justinlovinger** [comment]
>  If it's "often not usable for running commands in separate windows", that sounds like your environment is just messed up?

I used Nix for development environments. So, if I want to work on a Rust project, I run `nix develop` to get the environment for that project. I also have a command to open an editor in a new window. If I use `alacritty msg create-window` to open that editor, `rust-analyzer` will not be available because the window has the wrong environment. If I use `alacritty` to open that editor, the terminal *will* have the right environment, and `rust-analyzer` will work.

> I don't see how this would be intuitive to any user. 

I think most users, like me, would expect `alacritty msg create-window` to work like `alacritty`, creating a window with the same environment as the shell it was started from.

**Comment by chrisduerr** [comment]
> I used Nix for development environments.

Yeah that would explain it.

> I think most users, like me, would expect alacritty msg create-window to work like alacritty, creating a window with the same environment as the shell it was started from.

It is **not** the same thing though and people assuming it is are in the wrong.

The best argument to be made here is probably testing out how different terminal emulators implementing the same thing behave in this case, like URxvt for example. If there's sufficient evidence this doesn't cause issues for others, I'd consider adopting it as well. But I would be surprised if that's the case and I have no interest in testing it myself.
