### ISSUE TITLE
NO BUG! NO Prio! Need more Background information for the Keybindings in toml only for the chars section.  

### ISSUE THREAD

**Issue by sokrat3s** [alacritty/alacritty#7760]
I am not able to understand / find more Details for this section.
chars = "\u001B[1;5D"

My research the last 2 Days:
Google / DDG / an i ask 3 different AI Search Engines.   
I Read:
https://github.com/alacritty/alacritty/wiki/
https://alacritty.org/config-alacritty.html
https://docs.rs/winit/latest/winit/keyboard/enum.NamedKey.html
many alacritty.toml files on github and Gitlab.
Unicode Description Sites.

I know: 
it is Unicode.
\u = Is a Escape Secquence.
001 = Maybe the mods? : 
But the rest? 

I only need a Link to Dokumentation that has more deep Details.
And a wish to find it in the Wiki of alacritty.

Thanks for all the Nice Work / Support.

**Comment by kchibisov** [comment]
`chars` is just a string. You can write there whatever you want. `\U` is a shorthand to write a unicode character, but you can type the character directly.

e.g. `chars = "Hello world 🤔"`.

Or what exactly do you want to know here?

**Comment by sokrat3s** [comment]
Thanks for the Answer.

i know that this is a string.
But what do this string exactly.
I need to understand the Details of the Mapping in the string. 
I am not a rust Developer so i am not able to reade the source like a book.
What exactly is: 001B[1;5D meaning. 

My Real Point of Fail at the moment is this:
{ key = "Left",  mods = "Option",       chars = "\u0002[1;3D" },   # alt+Left     -> ctrl+b+Left  = Resize Pane Left

i need to map alt + left to ctrl+b+left 
and i have mutch more mappings to do so i need more deep understanding of this and i found nothing understandable on any source.
This is for tmux. 

maybe i have a knot in my head but there must be a source where i can read what these signs do
and how to learn to write them correctly to find the result I'm looking for. 

Thanks

**Comment by kchibisov** [comment]
Why not just bind `Alt+left` in tmux itself instead of doing remapping, sounds just backwards.

e.g. `bind -n M-Left resize-pane -L 1` will do what you want.

That's how things are getting encoded:

https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-PC-Style-Function-Keys

**Comment by pashadia** [comment]
Here's some more comprehensive info: https://sw.kovidgoyal.net/kitty/keyboard-protocol/#quickstart

Just to clarify, `CSI` in the kitty keyboard protocol corresponds to the `\u001b[` part of the string, and the rest varies as defined in the link.
