### ISSUE TITLE
[question] Open scrollback in $EDITOR?

### ISSUE THREAD

**Issue by sebastiansturm** [alacritty/alacritty#7761]
Apologies if this has been asked already, didn't find anything on this topic. I'd often like to be able to press a key that makes alacritty write its entire scrollback buffer to some newly created temp file, then invoke `$EDITOR` on it (emacsclient, in my case). Does that feature already exist somewhere? I'm not using tmux here (I used to, but after Alacritty introduced native scrollback support I figured the extra layer with its prefix keys that occasionally get in my way is no longer worth it for me)

**Comment by kchibisov** [comment]
You can probably hack yourself by -> enter Vi -> select all -> copy -> shell with piping clipboard to editor.

But see #1615

**Comment by sebastiansturm** [comment]
great, thank you!
