### ISSUE TITLE
[Question] vim plugins in README image

### ISSUE THREAD

**Issue by topocount** [alacritty/alacritty#7764]
I searched around the issues but didn't find what i'm looking for, so I'll post it here: what are the (neo)vim plugins used in this image?

![image](https://github.com/alacritty/alacritty/raw/master/extra/promo/alacritty-readme.png)

**Comment by chrisduerr** [comment]
Not sure if it still matches exactly, but it's based on kchibisov's dotfiles:
https://git.sr.ht/~kchibisov/dotfiles/tree/main/item/.config/nvim
