### ISSUE TITLE
hints.enabled action="Select" mouse.enabled=true results in selection of the whole line (instead of just the hint)

### ISSUE THREAD

**Issue by fedy-cz** [alacritty/alacritty#7766]
Using the following configuration snippet:
```
#Select hint text
[[hints.enabled]]
action          = "Select"
hyperlinks      = true
mouse.enabled   = true
#mouse.mods      = "Alt"
```
The Select action select the whole line containing the hint, not just the hint text. 
For example:
If I do something like `ls -l --hyperlink=auto` only the files get underlined as I hover over them, but when clicked the whole line is selected.

This doesn't change even if I uncoment the `mouse.mods` line.

Is this the intended behavior?

The man 5 alacritty states:
```
Select
                   Select the hint's text.
```
So I would expect only the hint's text to be selected.

If it's not a bug / the current behavior is already established, would you consider something like "SelectHintOnly" action?

### System

OS: Linux (Fedora 38)
Version: alacritty 0.13.1
Linux/BSD: X11, KDE5 / KWin

**Comment by chrisduerr** [comment]
Seems like this issue is specifically due to the mouse being used to select the hint. It works just fine with the keyboard. It also works just fine for regex hints.

**Comment by fedy-cz** [comment]
Still would be nice if it could be fixed. I'm trying to optimize some workflows and being able to select/copy stuff like filenames with a single click (even when they contain spaces etc.) would be really nice. Maybe a `CopyText` action that would copy the displayed hint text instead of the hyperlink could be even nicer.  Also the docs could probably use a little bit of clarification: now the description for `Copy` action states: `Copy the hint's text to the clipboard.` which in case of a hyperlink is a little misleading/ambiguous. 
Also, as I understand, currently the `mouse.mods`  option serves two distinct purposes and any of the `mouse.mods` options need to be satisfied for the hints to be highlighted (underlined) on mouse-over. So maybe a special `NoOp` action could be introduced for people that want the mouse-over highlighting always-on but require a modifier to invoke any of the actions / commands (yes I know I could introduce a no-op command as a workaround).

**Comment by chrisduerr** [comment]
> So maybe a special NoOp action could be introduced for people that want the mouse-over highlighting always-on but require a modifier to invoke any of the actions / commands (yes I know I could introduce a no-op command as a workaround).

This is not something I'm interested in. The highlight shows users when they can interact with a link, so underlining without the ability to click it would just be misleading and awkward.

**Comment by fedy-cz** [comment]
> This is not something I'm interested in. The highlight shows users when they can interact with a link, so underlining without the ability to click it would just be misleading and awkward.

I would agree in case of regex hints (where I know/control how I set them up), but in case of hyperlinks some distinction could be really useful. If I use a new/unfamiliar program that uses hyperlinks, there should  be some way to discover they are there (different styling / mouse cursor / whatever). Think of it as a web page where all the links are styled just as normal text, no cursor change on hover and you need a special keyboard combo to click-though them.

On the other hand, leaving the default no-modifier hyperlink activation on could be a security nightmare (a random click into the terminal could get you owned).

It's not a big deal, I have the "Select" action set up right now for no-mods, and if no action is required one could do something like a `/bin/true` command instead to get just the highlighting. I was just considering all the uses cases.

Hints/hyperlinks are a very nice feature, but one should take care to set them up properly.

**Comment by chrisduerr** [comment]
> If I use a new/unfamiliar program that uses hyperlinks, there should be some way to discover they are there 

It is up to the application to make that clear to you. If they want to underline their hyperlinks, they're easily capable of doing so. If they don't, they don't want them to be highlighted.

**Comment by chrisduerr** [comment]
#7824
