### ISSUE TITLE
yellow warning about yml config deprecation suggests running migrate command, migrate command generates an error

### ISSUE THREAD

**Issue by hardyoyo** [alacritty/alacritty#7770]
Error message: error: Found argument 'migrate' which wasn't expected, or isn't valid in this context

### System

OS: Linux (Ubuntu 22.04.4 LTS)
Version: alacritty 0.12.3
Linux/BSD: Regolith Desktop

### Logs

Crashes: not a crash, see error message above
Font/Terminal size: n/a
Keyboard and bindings: n/a

I'm not sure how to proceed. There is an epic/hostile thread about why there's no example toml file, so I won't ask for an example again. But, I do wish for the migrate command to work.

Perhaps I need to run it outside of Alacritty? In another terminal emulator?

**Comment by kchibisov** [comment]
>Version: alacritty 0.12.3

This version uses yaml.

It seems like the alacritty you run and the one you have in you path do differ.

Ensure to run the correct binary, you can use `which -a alacritty` to find instances you have around, once you run the correct version it'll have the migrate and it'll work just fine.

Docs are right there https://alacritty.org/config-alacritty.html or in man 5 alacritty, if you have them installed from your package.

**Comment by hardyoyo** [comment]
The error I was seeing I think was coming from Rust. I was running Rustc 1.73. I've upgraded to a newer version of Rust (1.76). And upgraded Alacritty with cargo, and now `alacritty migrate` works. It's a funny nudge to upgrade lots of things, but I seem to have arrived at an OK place.
