### ISSUE TITLE
Alacritty renders overlapping Indic (Kannada) fonts

### ISSUE THREAD

**Issue by ragu-manjegowda** [alacritty/alacritty#7771]
#### Alcaritty renders like below
![image](https://github.com/alacritty/alacritty/assets/11335919/242d9f5d-a65e-4e24-a6f1-fd4272b7340c)

#### Expected
```
Title: ಮೈಸೂರು-ರಾಮೇಶ್ವರಂ ರೈಲು ಸೇವೆಗೆ ಒಪ್ಪಿಗೆ, ವೇಳಾಪಟ್ಟಿ
```

- Alacritty is set to use `Hack Nerd Font`.
- I have installed on my system [ttf-kannada-font](https://aur.archlinux.org/packages/ttf-kannada-font) as well as enabled corresponding locale.
- Tried setting Mono font, didn't help.

### System

OS: Arch Linux
Version: 0.13.1 (fe2a3c56)
Linux/BSD: X11, AwesomeWM

### Logs

Crashes: N/A
Font/Terminal size: https://pastebin.com/raw/cvdG6MxX
Keyboard and bindings: N/A

**Comment by kchibisov** [comment]
Basically part of #50  since it requires font shaping.
