### ISSUE TITLE
LD_LIBRARY_PATH is not empty

### ISSUE THREAD

**Issue by xiyuzhai** [alacritty/alacritty#7772]
It seems that LD_LIBRARY_PATH is not empty and set to alacritty's paths when launching alacritty. This is annoying because it potentially interferes with other softwares without user realizing it. For instance, I was use the Lean programming language and the compiler leanc throws symbol lookup errors.

My question is, is LD_LIBRARY_PATH intentionally set to something? I would expect LD_LIBRARY_PATH to be empty, because it's the case for other terminals.

**Comment by kchibisov** [comment]
We do not set it.
