### ISSUE TITLE
window.position.y config doesn't work as expected

### ISSUE THREAD

**Issue by dnjmn** [alacritty/alacritty#7774]
The `window.position.y` doesn't seem to work no matter what i set it to.
No matter what the value of `y` is, the window position remains as shown:

![Screenshot 2024-02-26 at 1 26 49 PM](https://github.com/alacritty/alacritty/assets/49618740/36576e99-9bc9-4742-9aaa-686e724de0b1)

### System

OS:macOS
Version: `alacritty 0.13.1 (fe2a3c5)`

### Logs

Crashes: N/A
Font/Terminal size:
```
~ ❯ alacritty -vv                                                                                                             ✘ INT 26s 13:28:43
Created log file at "/var/folders/gh/lq4p_dbs7231yv74z999rpx80000gn/T/Alacritty-11294.log"
[0.000005333s] [INFO ] [alacritty] Welcome to Alacritty
[0.000222750s] [INFO ] [alacritty] Version 0.13.1 (fe2a3c5)
[0.000719000s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/Users/dhananjaymeena/.config/alacritty/alacritty.toml"
                                     "/Users/dhananjaymeena/.config/alacritty/colorScheme/nightfly.toml"
[0.000970041s] [DEBUG] [alacritty] Using environment locale: C/UTF-8/C/C/C/C
[0.019687416s] [INFO ] [alacritty] Using Apple CGL
[0.029296333s] [DEBUG] [alacritty] Picked GL Config:
                                     buffer_type: Some(Rgb { r_size: 8, g_size: 8, b_size: 8 })
                                     alpha_size: 8
                                     num_samples: 0
                                     hardware_accelerated: true
                                     supports_transparency: Some(true)
                                     config_api: Api(OPENGL)
                                     srgb_capable: true
[0.040800208s] [INFO ] [alacritty] Window scale factor: 1
[0.041644666s] [DEBUG] [alacritty] Loading "Hack Nerd Font Mono" font
[0.067410625s] [INFO ] [alacritty] Running on Apple M1
[0.067447333s] [INFO ] [alacritty] OpenGL version 4.1 Metal - 88, shader_version 4.10
[0.067463041s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.070950833s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.079256333s] [INFO ] [alacritty] Cell size: 10 x 20
[0.079280625s] [INFO ] [alacritty] Padding: 10 x 10
[0.079294208s] [INFO ] [alacritty] Width: 1470, Height: 860
[0.088206958s] [INFO ] [alacritty] PTY dimensions: 42 x 145
[0.090032708s] [INFO ] [alacritty] Initialisation complete
[9.063727458s] [INFO ] [alacritty] Goodbye
Deleted log file at "/var/folders/gh/lq4p_dbs7231yv74z999rpx80000gn/T/Alacritty-11294.log"
```
Keyboard and bindings: no need i guess

**Comment by chrisduerr** [comment]
Does x work? And has this worked in previous versions?

**Comment by dnjmn** [comment]
> Does x work?

yes x works.
> And has this worked in previous versions?

yes it worked in previous versions (probably 10-11, not sure about 12).

**Comment by chrisduerr** [comment]
> yes it worked in previous versions (probably 10-11, not sure about 12).

Could you at least try and bisect the version that broke this? Ideally the commit would be great.

**Comment by dnjmn** [comment]
i observed that this works for current version as well. But `window.dimensions.lines` affects `window.position.y`. If this is the expected behavoir, we can close this ticket. Though, ideally former should not the affect later...

i tried the following values with different result:

works:
```
window.dimentions.lines: 40
window.position.y: 380
```
![Screenshot 2024-02-27 at 4 04 33 PM](https://github.com/alacritty/alacritty/assets/49618740/2e81b345-c39d-4759-8570-526721f51ddf)


doesn't work:
```
window.dimentions.lines: 50
window.position.y: 380
```

![Screenshot 2024-02-27 at 4 07 26 PM](https://github.com/alacritty/alacritty/assets/49618740/3098329c-3649-40ee-8482-d367d3d4fe1a)


the position of `y` point should be same for both the cases. (IMO)

**Comment by chrisduerr** [comment]
> But window.dimensions.lines affects window.position.y

Could you be more specific on how one affects the other?

**Comment by dnjmn** [comment]
> Could you be more specific on how one affects the other?

as shown in the above two cases, the value of `window.position.y` is 380. But value of `window.dimensions.lines` is different.

(imo) the position y (distance from the top, y-axis) should be same in both the cases.

**Comment by chrisduerr** [comment]
How is it actually behaving though? I don't have macOS to test. It seems like in the second screenshot the `y` isn't considered at all? At what point does that happen?

**Comment by dnjmn** [comment]
as explained with above cases.

> It seems like in the second screenshot the y isn't considered at all

I just changed the `window.dimensions.lines` and i get different result in window position.

**Comment by chrisduerr** [comment]
> I just changed the window.dimensions.lines and i get different result in window position.

How is it different though? With just 2 values there's no way to tell about any pattern.
