### ISSUE TITLE
Alacritty does not change back to Underline cursor after quitting neovim

### ISSUE THREAD

**Issue by pos-ki** [alacritty/alacritty#7776]
When cursor is set to Underline (either in the config, or with `alacritty -o 'cursor.style = "Underline"'`), the cursor turns into Block style when neovim is launched (which by itself would be fine), but it does not turn back into Underline when neovim is stopped. It just stays in the Block style with blinking disabled. Trying the same with vim, for example, leaves the cursor in the Underline style the entire time (also in vim itself).  

It might be just neovim problem, but I still think that the terminal itself should be handling the shape of the cursor after programs are closed?

### System
OS: Arch Linux with 6.7.6 zen kernel
Version: 0.13.1 (fe2a3c56)
DE/WM/compositor: Wayland, GNOME

### Logs
`alacritty -vvv` shows the following line when neovim is launched and then the same line when it is closed
```
[TRACE] [alacritty_terminal] Setting cursor style Some(CursorStyle { shape: Block, blinking: false })
```

**Comment by kchibisov** [comment]
You should reset yourself on vim leave. There's no escape to restore cursor in general.

**Comment by kchibisov** [comment]
`au VimLeave * set guicursor=a:hor100` in vim.

or type reset or set cursor manually via escape to Underline.

**Comment by chrisduerr** [comment]
> There's no escape to restore cursor in general.

There is, vim just doesn't use it.
