### ISSUE TITLE
Add a way to set env variables for alacritty's child process only

### ISSUE THREAD

**Issue by SomeoneToIgnore** [alacritty/alacritty#7778]
Somewhat related to https://github.com/alacritty/alacritty/issues/7753 since caused by the same use case: Zed editor uses alacritty to spawn things and recently it gained the ability to spawn arbitrary `bash -c foobar.sh` or `python3 something.py` commands using Alacritty's `alacritty_terminal::tty::Shell::new`

Certain tasks would need more env variables, e.g. various python scripts may require different venv set up taken from the project.
For that, certain env variables have to be set in order to run the task properly.
If Zed uses `std::env::` API, it will set those for the entire Zed process which may cause bad side effects. 

How appropriate would it be to extend the `alacritty_terminal::tty::Shell` struct with `env: HashMap<String, String>` config and set it in https://github.com/alacritty/alacritty/blob/37349c4566a1431b5becbb649dec536ecbe18e71/alacritty_terminal/src/tty/unix.rs#L228-L230
?

**Comment by kchibisov** [comment]
Don't see why not, given that it's racy to do manually and rely on inheritance. Probably we shouldn't set `ALACRITTY_WINDOW_ID` and require `window_id` in the first place, but do it on the caller side.

There's `options` where you can add `env`.
