### ISSUE TITLE
[Feature Request] Fix input at top

### ISSUE THREAD

**Issue by liubog2008** [alacritty/alacritty#7781]
See https://docs.warp.dev/appearance/input-position

That's an important feature for my cervical vertebra !!!

**Comment by chrisduerr** [comment]
Use warp then.

**Comment by kchibisov** [comment]
>That's an important feature for my cervical vertebra !!!

If you sit correctly and position the monitor correctly you don't have to move you neck or _bow_ because you see all the content at the same time. Even on large monitors.

**Comment by liubog2008** [comment]
@chrisduerr I'm sorry why it's closed without any reason? I mentioned warp is just because this feature seems only implemented in warp and I hope I can use it in alacritty.

**Comment by kchibisov** [comment]
I mean there's no desire to add such feature, because it's on _shell_ not us in the first place.

**Comment by liubog2008** [comment]
> I mean there's no desire to add such feature, because it's on shell not us in the first place.

That's an acceptable reason. But it seems a terminal feature but not shell (bash, zsh, fish, nushell... all I know cannot do it).

By the way, I just feel sad about the comment `Use warp then` but not yours. @kchibisov Thanks for your response.

**Comment by kchibisov** [comment]
>By the way, I just feel sad about the comment Use warp then

it's a valid response though, if you like some features in the given software and they make your life better you should use that software instead.
