### ISSUE TITLE
Does render accented letters correctly

### ISSUE THREAD

**Issue by m-rphy** [alacritty/alacritty#7782]
### System
OS: macOS
Version (alacritty): 0.12.2

Accented letters are printed with the letter and then the accent.

It occurs in the terminal as well as within interact run times 

<img width="594" alt="Screenshot 2024-02-27 at 9 43 45 PM" src="https://github.com/alacritty/alacritty/assets/107144841/573c0a20-20c3-48c5-ac71-113b0fb13fdd">

**Comment by kchibisov** [comment]
That could happen if the font uses metrics to place them forward. But generally metrics in the font should place them before. Most fonts designed for UI are doing that correctly.
