### ISSUE TITLE
Make font offset / glyph_offset. x & y apply to both opposing sides

### ISSUE THREAD

**Issue by sunshine-syz** [alacritty/alacritty#7783]
Currently, the offset only adds space on one side, which causes the text not to be centered within the box. It would be great if we could apply the offset to both sides. This would make the text neater. Thank you!

The screenshot is alacritty with large offset value to show the behavior.

<img width="232" alt="Screenshot 2024-02-27 at 9 21 19 PM" src="https://github.com/alacritty/alacritty/assets/23123022/dd817f10-e243-42bc-a77e-9d60b965a24d">

**Comment by kchibisov** [comment]
The combination of line offset + glyph offset should do that. Te only issue is the underline position, which is a bit complex to solve in the shader...
