### ISSUE TITLE
Add a warning to the damn links, don't make them open in browser directly

### ISSUE THREAD

**Issue by Crazexdd** [alacritty/alacritty#7785]
I almost got caught and got in big trouble because of this feature. (Definitely not using alacritty when doing not so ethical things again xD)

It would be better if we had configurable links with given ones are being trusted and lest of them won't open without a dialog.

**Comment by kchibisov** [comment]
You're free to tweak the link opener however you want, including writing a separate program doing a dialog or requiring you to hold various modifiers before doing so.

At this point you just try to transfer the blame to us.
