### ISSUE TITLE
Question: mouse bindings not working

### ISSUE THREAD

**Issue by FearlessSpiff** [alacritty/alacritty#7786]
I have a Logitech mouse with side buttons. Using `wev` I found the button numbers to be `275`and `276`. Now I wanted to change font size with:
```
[mouse]
bindings = [
  { mouse = 275, action = "IncreaseFontSize"},
  { mouse = 276, action = "DecreaseFontSize"},
]
```
But it does nothing. I also enabled logging with `-v`but nothing positive neither negative is logged regarding my bindings. What do I do wrong? 
Thanks!

**Comment by chrisduerr** [comment]
`alacritty --print-events` should log the correct IDs under `MouseInput` events. The events you're using seem way too high to be accurate.

**Comment by kchibisov** [comment]
I bet these are `Back` and `Forward` buttons in our bindings, but yeah `--print-events` is what should be used.

**Comment by FearlessSpiff** [comment]
Yes, you are right. `Back` and `Forward` it is. Didn't see `--print-events` flag. Or better said, didn't look for it. Thanks 1000x!
