### ISSUE TITLE
Send text from one terminal window to another

### ISSUE THREAD

**Issue by ManuGraiph** [alacritty/alacritty#7790]
Hi, i have a question..

Is there any way to send text or keypresses from one alacritty terminal window to another? (Basically a similar function to tmux's `send-keys` but between alacritty terminals).

**Comment by kchibisov** [comment]
No, there's not. Though, if you want to insert something in `pty` you may just `echo > /dev/pts` of the terminal you want to insert stuff into. To obtain `pts` you can use `ps`.
