### ISSUE TITLE
Neovim inside Tmux not Rendering well. But doing well when Wezterm installed. Windows API or ConPTY?

### ISSUE THREAD

**Issue by aams-eam** [alacritty/alacritty#7792]
When I am using Neovim inside tmux part of the screen in the right overlaps with the left side of the screen. See the following figure where the red x is in the left side of the screen but it should be in the right side.
![alacritty-bad](https://github.com/alacritty/alacritty/assets/56005012/dffa0fb2-365c-44d1-8965-882c5bccfadb)

This should look like this:
![alacritty-good](https://github.com/alacritty/alacritty/assets/56005012/aa377bfa-1b43-4f15-9317-c2f213bd150c)

I have tested this in:
- Windows Terminal (In Windows 11)
- MobaXterm
- Wezterm

And in all of those it works well. Something really curious is that if I install Wezterm the issue is fixed in Alacritty. If I uninstall Wezterm the issue appears again.
I created a minimal configuration to test this. This is alacritty.toml:
```toml
[font]
size = 15

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
decorations = "none"

[window.padding]
x = 0
y = 0

[shell]
program = "wsl"
```

And this is my .tmux.conf:
```conf
set -g default-terminal 'tmux-256color'
set -as terminal-features ',xterm*:RGB'
```

I have checked the environment variables. Outside of tmux I have `TERM=xterm-256color`, and inside tmux `TERM=tmux-256color`. I have checked that those env variables do not change when I install Wezterm. However with Wezterm installed it works. I have also seen some people mentioning LANG variable, it is always set to `C.UTF-8`.

### System

OS: This happens both in my Windows 10 and Windows 11 machines
Using WSL2 with Ubuntu 22.04.2 LTS
Version: `alacritty 0.13.1 (fe2a3c5)`
Tmux version: 3.3a
Neovim version:
   NVIM v0.9.4
   Build type: Release
   LuaJIT 2.1.1700008891

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
This is a log of Alacritty without Wezterm installed. I am opening Alacritty, tmux, and then neovim inside.
```
[INFO ] [alacritty] Welcome to Alacritty
[INFO ] [alacritty] Version 0.13.1 (fe2a3c5)
[INFO ] [alacritty] Configuration files loaded from:
                      "C:\\Users\\aamse\\AppData\\Roaming\\alacritty\\alacritty.toml"
[INFO ] [alacritty] Window scale factor: 1.25
[INFO ] [alacritty] Using WGL
[DEBUG] [alacritty] Picked GL Config:
                      buffer_type: Some(Rgb { r_size: 8, g_size: 8, b_size: 8 })
                      alpha_size: 8
                      num_samples: 0
                      hardware_accelerated: true
                      supports_transparency: Some(false)
                      config_api: Api(OPENGL | GLES1 | GLES2)
                      srgb_capable: true
[DEBUG] [alacritty] Loading "UbuntuMono Nerd Font" font
[INFO ] [alacritty] Running on AMD Radeon (TM) Graphics
[INFO ] [alacritty] OpenGL version 3.3.0 Core Profile Context 22.20.42.17.230904, shader_version 4.60
[INFO ] [alacritty] Using OpenGL 3.3 renderer
[DEBUG] [alacritty] Enabled debug logging for OpenGL
[DEBUG] [alacritty] Filling glyph cache with common glyphs
[INFO ] [alacritty] Cell size: 12 x 25
[INFO ] [alacritty] Padding: 0 x 0
[INFO ] [alacritty] Width: 800, Height: 600
[INFO ] [alacritty] PTY dimensions: 24 x 66
[INFO ] [alacritty_terminal] Using Windows API for pseudoconsole
[INFO ] [alacritty] Initialisation complete
[DEBUG] [alacritty_terminal] New num_cols is 213 and num_lines is 54
[INFO ] [alacritty] Padding: 0 x 0
[INFO ] [alacritty] Width: 2560, Height: 1351
[DEBUG] [alacritty_terminal] Ignoring unknown mode 7727 in set_private_mode
```
I realized that when I do the same thing with Wezterm installed, the log is exactlly the same but for this line.
```
[INFO ] [alacritty_terminal] Using conpty.dll for pseudoconsole
```

Without Wezterm installed Alacritty is using Windows API for pseudoconsole, while with Wezterm installed it is using conpty.dll.

**Comment by kchibisov** [comment]
wezterm ships newer version of conpty.dll and puts it in your path, thus alacritty will use it. Given that changing conpty fixes the issue it's not our bug, but the bug in the windows default conpty.

You can just place the conpty.dll and OpenConsole.exe around the alacritty binary from the wezterm if you want to.
