### ISSUE TITLE
Add a way to append bytes to terminal child output

### ISSUE THREAD

**Issue by SomeoneToIgnore** [alacritty/alacritty#7795]
Wrapping alacritty_terminal and spawning bash-like tasks with it, I often want to add more text before and after the task:
![image](https://github.com/alacritty/alacritty/assets/2690773/1e13d310-517e-4ab1-8483-52ae07aa1f68)
(maybe, even run multiple tasks in the same environment consequently)

There's a way to make things appear in alacritty terminal, using `Msg::Input` with the `EventLoopSender`
https://github.com/alacritty/alacritty/blob/494ae3c6cdd8f711fc262334e7f3b3d62b046589/alacritty_terminal/src/event_loop.rs#L30-L41
but that would be treated as user input, and every `\n` or other unescaped symbols will not be highlighted and may cause unexpected command launches and other issues.

One more change is needed here:
https://github.com/alacritty/alacritty/blob/494ae3c6cdd8f711fc262334e7f3b3d62b046589/alacritty_terminal/src/event_loop.rs#L262-L276
to keep the event loop on after child exit.

What I'm looking for is another, `Output(Cow<'static, [u8]>), ` variant that will add those bytes into the terminal grid the same way as `echo Hello` child command output does that.

**Comment by kchibisov** [comment]
Every input to terminal is done by writing to pty and then it echos back to you(if echo is enabled), so what you ask is basically not how it should be done. 

What you want is a shell script which prints everything, which you should be able to accomplish without the help of alacritty_terminal.

>What I'm looking for is another, Output(Cow<'static, [u8]>), variant that will add those bytes into the terminal grid the same way as echo Hello child command output does that.

you can write to grid yourself if you want without even touching the pty.

**Comment by kchibisov** [comment]
I think you can do with https://docs.rs/alacritty_terminal/0.22.0/alacritty_terminal/term/struct.Term.html#method.input or https://docs.rs/alacritty_terminal/0.22.0/alacritty_terminal/term/struct.Term.html#method.grid_mut 

all the methods on the `Term` to manipulate the grid are public, so nothing stops you.

**Comment by kchibisov** [comment]
I also wonder if you can feed arbitrary escape sequence payload with the help of `vte` following how we do so in event loop, given that once you access `term` you can use `vte` crate to parse the escape sequences you predefine to simplify all of that (so you just `echo`, basically).

Also, if you want to mix multiple tasks it's a bit complicated, since you generally want to separate each task output (or write it to some external grid of yours), because generally speaking terminal app you're running could clear the screen nuking previous task outputs and your separators, so you want it to be isolated from the rest of command outputs. Generally, you'd create a separate widget which gets the content from the terminal or you create the terminals around after PTY exits (how `--hold` works in alacritty).

Though, one could just use linked list to glue `Term` together and then write an iterator that continues to other terms, maybe not the most efficient solution, but should likely work.

**Comment by chrisduerr** [comment]
> all the methods on the Term to manipulate the grid are public, so nothing stops you.

Except the fact that applications might rely on the grid state being in the way they'd expect. So there's a chance that modifying the grid (like adding a new line) breaking things.

**Comment by kchibisov** [comment]
Yeah, but if they want to _append_ something to already finished process they are more or less _safe_, since that's what I've seen in their screenshot.

**Comment by SomeoneToIgnore** [comment]
Good point: ideally, I would want to send bytes over the wire and try building a collaborative environment over alacritty.
And by manipulating the grid directly, I'm not getting any `Event::Wakeup` and other useful events emitted?

**Comment by kchibisov** [comment]
Yeah, but if you manipulate the grid you know that you must draw because the change is instant and you did that? You can also send wakeup yourself, if you want  it to be handled the same as regular wake ups, but it might add a bit of input lag that way, which is likely not desired.

**Comment by chrisduerr** [comment]
> Yeah, but if they want to append something to already finished process they are more or less safe

This assumption is highly-dependent on conventional shell behavior and is not universally true for terminal emulators at their core.

The only way to append something reliably to the bottom of the terminal is to render it separately, without interacting with the terminal grid itself.

**Comment by SomeoneToIgnore** [comment]
@kchibisov can you consider this example? https://github.com/alacritty/alacritty/compare/master...SomeoneToIgnore:alacritty:draw-in-grid?expand=1

I am trying to append N lines to a process after it exits, similar to what described in this issue originally.
I've picked the `man bash` as a command and modified the `cargo run -p alacritty` example to use it — when you spawn it and press `q`, some arbitrary set of lines will be displayed.

Unfortunately, if I do not resize the screen and try to scroll it either programmatically or via the mouse button/trackpad, it would not scroll at all.
After I resize the screen, scrolling starts to work as normal.

Ergo the questions:

1. What should I set in the public API to "fix" the scrolling from the very beginning? I see that `display_offset` is never above 0 which seems to be the culprit, but there's no public API to change it?
2. `dbg!(grid_mut.history_size())` from the example shows that resizing the grid looses the history? How can I preserve it?
3. Writing this code is quite tedious, would you be ok with adding it into this repo as a public API after all related issues are fixed?

**Comment by chrisduerr** [comment]
Are you saying you're adding non-terminal text below the terminal output? If so, then it should be done in the same fashion Alacritty's message bar is done. Writing things directly to the terminal output is hacky and unreliable, so it should be avoided.

**Comment by SomeoneToIgnore** [comment]
> adding non-terminal text below the terminal output

Exactly, after the child process had exited, or, in the worst case, after the terminal had exited (not the part of this example, for brevity).

> Writing things directly to the terminal output

I do not seem to write things directly into the terminal output, though?
I've followed the advice to use `grid_mut` methods (https://github.com/alacritty/alacritty/issues/7795#issuecomment-1973256722) and output a random string into the grid.

Seems to work for my case, after I escape the line breaks (escaping does not matter for the repro hence omitted).

--------

And despite writing the lines directly into the grid, term's inner state does not allow to scroll the updated grid properly (via API or via the input methods) until I resize the grid window.

**Comment by chrisduerr** [comment]
>  I've followed the advice to use grid_mut methods (#7795 (comment)) and output a random string into the grid.

Which you shouldn't do. This is why you're running into issues. You just completely ignored my comments following this statement and now you're running into the issues I've outlined.

**Comment by SomeoneToIgnore** [comment]
Sorry, seems that I've ignored your "impossible to render in terminal" messages.
The reasons for such behavior of mine:

* I badly want to avoid rendering anything else that's not terminal in that space
* VSCode's terminal is perfectly fine with appending the text before and after the terminal output, I do not see why Alacritty has to be special in that regard:
<img width="906" alt="image" src="https://github.com/alacritty/alacritty/assets/2690773/448964a3-e147-45e7-8c12-e7db863d18a9">
* based from my experiments, things almost work, it's just the scrolling thing that is not working right

I would still love to hear from @kchibisov (as the one who proposed the grid_mut approach) whether there anything could be done before starting to think about the rendering.

**Comment by kchibisov** [comment]
Use `input` function to write, etc. But do that once the PTY is no longer alive.
