### ISSUE TITLE
Documentation: support for ESC-X?

### ISSUE THREAD

**Issue by EnronEvolved** [alacritty/alacritty#7797]
I've been experimenting with ANSI escape sequences, with the goal of embedding metadata in ANSI art. I've found that the "Start of String" escape sequence `ESC X` and the corresponding "String Terminator" `ESC \` both seem to work, but they aren't mentioned in [the list of supported escape sequences](docs/escape_support.md).

Was their omission an accident? What is Alacritty's behaviour when it receives one of these sequences?

**Comment by chrisduerr** [comment]
That's not an escape sequence.

**Comment by EnronEvolved** [comment]
Yes it is, it's mentioned in ECMA-48. Alacritty responds to it, as does xterm.

If you don't believe me, try `echo -e "\x1bXfoo\x1b\\\bar"` under Alacritty or xterm.

**Comment by EnronEvolved** [comment]
Here are some further test results on Alacritty version 0.13.1, running python to escape (pardon the pun) from the double escaping necessary in bash, pasted from my terminal:
```
>>> print("\x1bXfoo\x1b\\bar")  # ESC X correctly indicates start of string...
bar
>>> print("\x1bXfoo\x1bebar")  # ... but string termination can be done by any escape sequence.
bar
>>> print("\x1bXfoo\x1bebar\x1b\\baz")  # Expected output going by ECMA-48: "baz"
barbaz
>>> print("\x1befoo\x1bebar\x1b\\baz")  
foobarbaz
>>> # ESC X definitely does something, as the invalid escape sequence ESC e does not reproduce the behaviour
```
For further information, refer to ECMA-48 section 5.6 on control strings.

**Comment by kchibisov** [comment]
https://vt100.net/emu/dec_ansi_parser

see 58, that's what it is, but it's not an escape, it's just how parser works.

**Comment by EnronEvolved** [comment]
The difference there is ultimately a semantic one. An escape sequence is an escape sequence regardless of where its behaviour is implemented ([refer to 4.2.39](https://ecma-international.org/wp-content/uploads/ECMA-48_5th_edition_june_1991.pdf)).

This issue is ultimately about a gap in the documentation of Alacritty's behaviour, I don't understand why this is "not a bug".

**Comment by kchibisov** [comment]
What you were talking about is C1 control byte, we don't support C1. The behavior you see is just _ignore the string_ if you read the linked spec, so there's really nothing special, it's just how parser should work, there's nothing to document, if you parser doesn't do that, the parser is wrong.

**Comment by j4james** [comment]
@EnronEvolved I think you're misreading those documents (assuming you're talking about the case where you've got an `ESC` in the middle of your `SOS` string). According to the ECMA-48 docs (section 5.6), that's not valid:

> A command string is a sequence of bit combinations in the range 00/08 to 00/13 and 02/00 to 07/14.

So that would be considered undefined behavior, which would be up to the terminal developers to handle however they wanted to. And according to the DEC standards (STD 070, section 3.5.4.4):

> For backward compatibility, and to minimize the effect of a lost String Terminator, the control codes CAN (1/8), SUB (1/10), ESC (1/11), or any C1 control will also terminate control strings.

You can also see that in the linked parser documentation on vt100.net - the node "anywhere" is an entry point for all the control string sequences.

**Comment by EnronEvolved** [comment]
Alright, if Alacritty is following DEC standards rather than strictly conforming to ECMA-48, fair enough. 

Maybe there isn't a bug there. I'm not sure that a terminating `ESC` should start another escape sequence, though:

```
>>> print("\x1bXtest\x1bXtest\x1b\\")

>>> print("\x1bXtest\x1betest\x1b\\")
test
>>> # Should it be "etest"?
```

This is the behaviour on xterm too, so maybe that is the intended behaviour as it's meant to emulate DEC terminals specifically.

Anyway, `ESC X` and `ESC \` for character strings are still escape sequences. I don't see the functional difference considering that they can be used just like CSI, OSC, or other escape sequences. For the sake of clarity and completeness it should be noted as "IMPLEMENTED", noting that such sequences are ignored. 

A brief explanation of the behaviour relevant to command/character strings would be useful too. I'm more than happy to open a pull request to make the additions myself.

For the record, the ECMA-48 behaviour of `ESC X` is specified in section 8.3.128 (emphasis mine):
> SOS - START OF STRING
> Notation: (C1)
> Representation: 09/08 or ESC 05/08
> SOS is used as the opening delimiter of a control string. **The character string following may consist of
> any bit combination, except those representing SOS or STRING TERMINATOR (ST).** The control string
> is closed by the terminating delimiter STRING TERMINATOR (ST). The interpretation of the character
> string depends on the application.

**Comment by EnronEvolved** [comment]
I've done some more comprehensive testing on other terminal emulators in my distro repositories, printing the string "\x1bXFoo \x1beBar\x1b\\":
- Konsole, Kitty, rxvt-unicode, pterm: `Foo Bar`
- Alacritty, Gnome Terminal, xterm: `Bar`

It's not universally implemented by any means, it definitely needs to be documented.

**Comment by j4james** [comment]
> I'm not sure that a terminating `ESC` should start another escape sequence

It should if you're emulating the DEC behavior.

> **The character string following may consist of any bit combination, except those representing SOS or STRING TERMINATOR (ST).**

I stand corrected. Rereading that section, it seems ECMA considered `SOS` to be different from the other control strings. But DEC didn't, and that's the standard that most modern terminals will be following.

> It's not universally implemented by any means

I don't disagree. A lot of the terminals I've tested don't implement `SOS`, and the early DEC terminals didn't implement it either.
