### ISSUE TITLE
When using visual mode in Vimtutor, the selected text can't be distinguished from the background (white).

### ISSUE THREAD

**Issue by miguel-dev** [alacritty/alacritty#7798]
When running Vimtutor, when in visual mode selected text can't be distinguished. However, with ordinary use using the vim config file this issue doesn't happen.

### System

OS: macOS
Version: alacritty 0.13.1 (fe2a3c5)

### Logs
Font/Terminal size:
Loading "Jetbrains Mono" font
Width: 800, Height: 600

**Comment by chrisduerr** [comment]
How is this related to Alacritty and not just your vim color configuration?

**Comment by miguel-dev** [comment]
Vimtutor doesn't use my vim color configuration, it uses vanilla configs.

**Comment by chrisduerr** [comment]
Still zero indication that this is an Alacritty issue.
