### ISSUE TITLE
[Question] How to prevent alacritty from printing out keycodes on Sway? 

### ISSUE THREAD

**Issue by anthony-S93** [alacritty/alacritty#7799]
On Sway, keycodes will be printed on the command line every time I press certain keybindings when the Alacritty's window is active. 

For instance, pressing the volume up and down buttons when alacritty's window is active will print `438u` and `439u` inside the window. Using the `mod` + `space` keybinding on sway will also print a whitespace. Since this does not occur on X11, I'm guessing it has something to do with how the two display protocols handle key events. However, other terminal emulators like `xfce4-terminal` does not exhibit this behavior even on Sway. 

Is there a specific setting that I need to include in my alacritty config to turn off this behavior?

**Comment by kchibisov** [comment]
if you type something in alacritty there's no guarantee that nothing will be send in the end. That's true for all applications, if you type into them they will actually process your input.

>Is there a specific setting that I need to include in my alacritty config to turn off this behavior?

You can unbind the keys if you want, but latest master is more conservative and doesn't send escapes for media keys.

>Using the mod + space keybinding on sway will also print a whitespace

again, if you type it'll type.
