### ISSUE TITLE
Enable floating window behavior on macOS

### ISSUE THREAD

**Issue by okuuva** [alacritty/alacritty#7804]
### System

OS: macOS
Version: 0.13.1 (fe2a3c5)

Some terminal emulators (namely iTerm2 and Kitty) are able to render on top of applications that are in the native full screen mode that occupies a separate space in macOS. AFAIK Alacritty isn't able to do so. Such a feature was proposed in #4268 but got dismissed as a platform specific window management feature.

I'm fully on team "window management should be left for window managers" but I would argue that this feature isn't exactly window management. I believe this kind of floating window behavior can be achieved on macOS by setting specific [NSWindow.CollectionBehavior](https://developer.apple.com/documentation/appkit/nswindow/collectionbehavior) settings. Granted, that's platform specific option but it does fall on the application's duties to tell the Quartz Compositor how to treat the application windows on macOS. After that it's up to the user to figure out how to tell Quartz Compositor to move the window on top of a full screen application (Hammerspoon being the most(?) common tool on macOS for scripted window manipulation).

With all that being said: would you be willing to consider accepting a PR that would enable the floating window behavior on macOS? It might be that `winit` doesn't support it either but I would be interested in doing some digging to see how much work this would be.

**Comment by nixpulvis** [comment]
I used to have a quake-like terminal slide down. I wonder if this would help implement that again w/ alacritty.

**Comment by okuuva** [comment]
> I used to have a quake-like terminal slide down. I wonder if this would help implement that again w/ alacritty.

It should. I have a quake-like terminal setup with Kitty but can't do the same with Alacritty since it can't be moved on top of a fullscreen application on macOS.
