### ISSUE TITLE
[Feature Request] Read-Only Mode

### ISSUE THREAD

**Issue by Nosamdaman** [alacritty/alacritty#7805]
One of my favorite features of other terminal emulators is the ability to toggle a "read-only" mode in which a user can still scroll and select text from the terminal, but cannot pass any new data in via the keyboard or mouse. Ideally, the user won't even be able to close the window without needing to accept a modal warning them of such. The idea is that long-running jobs don't get accidentally stopped when one enters `Ctrl+C` into the wrong window.

**Comment by kchibisov** [comment]
You can simulate this with IPC(alacritty msg config) by binding all the keys to `None` and then binding to what you have by default.
