### ISSUE TITLE
Compose keys bug: intermediate keystrokes/characters are typed

### ISSUE THREAD

**Issue by hugopeixoto** [alacritty/alacritty#7806]
On version 0.13.1, when I type `<Compose>'a`, instead of just getting an `á`, I get `'á`.

I've recently updated a bunch of system dependencies and alacritty to 0.13.1 using `cargo install` (I don't know which version I was using before). It might be a problem with some other package on my system, but compose keys work fine in other applications (like firefox, libreoffice, and termit).

### System

OS: Linux (Debian GNU/Linux)
Version: alacritty 0.13.1
Linux/BSD: Wayland and Sway

### Logs

Keyboard and bindings: [`alacritty --print-events`](https://github.com/alacritty/alacritty/files/14496095/compose.log)

**Comment by kchibisov** [comment]
>On version 0.13.1, when I type <Compose>'a, instead of just getting an á, I get 'á.

Install with `--locked`. But yeah, the bug is present upstream.

**Comment by hugopeixoto** [comment]
Thank you for the quick reply and fix. I can confirm that this is fixed in 0.13.2.
