### ISSUE TITLE
Alacritty catch sway shortcut for horizontal splitting (`Super + h`)

### ISSUE THREAD

**Issue by redat00** [alacritty/alacritty#7807]
Hi everyone ! 

When using the Alacritty I found out that I was not able for some reason to use my usual shortcut for Sway that would allow me to split my screen horizontally. To do so I just use `mod + h` which in my case correspond to `Super + h`. It works fine in other application, but in Alacritty it just spit out an 'h' as if I typed it. Note that the other splitting for vertical (`Super + v`) just works fine.

Is Alacritty "catching" my command ? If so how can I prevent this to happens ? 

Thanks in advance for any help you'd be able to provide !

### System

OS: Linux
Version: alacritty 0.14.0-dev (f7811548)
Linux: Wayland, Sway

**Comment by redat00** [comment]
Not at all related to Alacritty, sorry for the noise. ^^'

**Comment by kchibisov** [comment]
`--released`(or whatever it's called) on sway makes it deliver the press.
