### ISSUE TITLE
Alacritty config file, alacrity.yml is missing.

### ISSUE THREAD

**Issue by Luka2552** [alacritty/alacritty#7808]
Hello,

After building alacritty, I was able to run it succesfully! By all means, everything worked fine.

However, I was not able to locate alacritty.yml! there was no .config/alacritty folder and I searched everywhere for that file but was not able to find it.

### System

OS: Linux Mint Debian Edition 6
DE: KDE Wayland.

### Logs

echo $XDG_CONFIG_HOME/alacritty/alacritty.yml

Output: /alacritty/alacritty.yml

Note, there is no such thing as "/alacritty/alacritty.yml", I was not able to find it anywhere.

Thank you in advance.

**Comment by Miho1254** [comment]
`alacritty.yml` is no more, it's `alacritty.toml` now

**Comment by kchibisov** [comment]
https://alacritty.org/config-alacritty.html

**Comment by Luka2552** [comment]
> `alacritty.yml` is no more, it's `alacritty.toml` now

I see, thanks for the update! Where can I find this file?

**Comment by kchibisov** [comment]
you create it yourself.

**Comment by Luka2552** [comment]
> you create it yourself.

Ah I see!

Where at though? Like specifically in what directory?

**Comment by kchibisov** [comment]
https://github.com/alacritty/alacritty?tab=readme-ov-file#configuration

**Comment by Luka2552** [comment]
> https://github.com/alacritty/alacritty?tab=readme-ov-file#configuration

Great!

Although sadly I re-installed and now alacritty isn't running at all...

I'll create a seperate issue
