### ISSUE TITLE
Alacritty not opening after re-install

### ISSUE THREAD

**Issue by Luka2552** [alacritty/alacritty#7810]
After successfully building and using Alacritty, I encountered an issue where it no longer launches after a re-installation, including through package management. The alacritty icon appears for one second on the panel and then dissapears. Any help would be appreciated.

### System

OS: Linux Mint Debian Edition 6

Terminal Output: 

user@User-Linux:~$ alacritty
Created log file at "/tmp/Alacritty-3091.log"
[0.000574183s] [WARN ] [alacritty_config_derive] Config warning: use_thin_strokes has been removed; set the AppleFontSmoothing user default instead
[0.000746347s] [WARN ] [alacritty_config_derive] Config warning: background_opacity has been deprecated; use window.opacity instead
[0.000771865s] [WARN ] [alacritty_config_derive] Config warning: url has been deprecated; use `hints` section instead
Error: Failed to spawn command '/usr/local/bin/fish': No such file or directory (os error 2)
Deleted log file at "/tmp/Alacritty-3091.log"
Error: "Event loop terminated with code: 1"

**Comment by kchibisov** [comment]
The shell binary you've specified doesn't exist. Ensure that it points to correct thing.

**Comment by Luka2552** [comment]
> The shell binary you've specified doesn't exist. Ensure that it points to correct thing.

Is it possible for you to elaborate instead of saying a single sentence and linking to a doc?

What shell binary? How do I ensure it points to the correct thing? Is there a way to check what the issue really even is?

Thanks in advance

**Comment by kchibisov** [comment]
>Error: Failed to spawn command '/usr/local/bin/fish': No such file or directory (os error 2)

**Comment by kchibisov** [comment]
I'm not sure how you've specified configuration, but you clearly have a config which has a `shell` section which points to a binary `/usr/local/bin/fish` which doesn't exist on your system. If you run `alacritty --config-file /dev/null` it'll work just fine.

**Comment by Luka2552** [comment]
Additional terminal troubleshooting

user@user-linux:~$ alacritty
Command 'alacritty' not found, but can be installed with:
sudo apt install alacritty
user@user-linux:~$ sudo infocmp alacritty
infocmp: couldn't open terminfo file /usr/share/terminfo/a/alacritty.

**Comment by kchibisov** [comment]
I mean if you've removed everything there's no `alacritty` anymore...

**Comment by Luka2552** [comment]
> I mean if you've removed everything there's no `alacritty` anymore...

Okay, I'll try to make myself clear.

I removed everything, but then I REBUILT IT. AGAIN. 

BUILD. AGAIN.

Yet I am still having the same issue. 

I don't think this issue should be closed.

**Comment by Luka2552** [comment]
> I mean if you've removed everything there's no `alacritty` anymore...

Also, why is this issue closed? Clearly I'm still struggling here

**Comment by kchibisov** [comment]
The issue is closed because it's not a bug in the first place. Issue being closed doesn't mean we can't communicate on this issue to provide a _user help_, but your issue is not a _bug_ in the first place.

**Comment by kchibisov** [comment]
>Yet I am still having the same issue.

Does `alacritty --config-file /dev/null`? If it does then the issue is in your config, which you can find at `alacritty -v`(it tells you what it loads), then likely you have something with `fish` which doesn't exist.

**Comment by Luka2552** [comment]
> > Yet I am still having the same issue.
> 
> Does `alacritty --config-file /dev/null`? If it does then the issue is in your config, which you can find at `alacritty -v`(it tells you what it loads), then likely you have something with `fish` which doesn't exist.

This is what I get when I run alacritty - v

user@user-linux:~$ alacritty -v
Command 'alacritty' not found, but can be installed with:
sudo apt install alacritty

NOTE, I built alacritty and restarted my device so I am not sure why it does this

**Comment by kchibisov** [comment]
>This is what I get when I run alacritty - v

That means that alacritty is not in your `PATH`, how do you run it?

**Comment by Luka2552** [comment]
> > This is what I get when I run alacritty - v
> 
> That means that alacritty is not in your `PATH`, how do you run it?

I fixed it.

The issue was with alacritty.yml, I deleted it and it seems to work just fine now.
