### ISSUE TITLE
Add `New Window` action on macOS icon

### ISSUE THREAD

**Issue by ddarbyson** [alacritty/alacritty#7817]
It would be nice to see "New Window" when right-clicking on the MacOS icon. As of now, I need to find an existing window, create a new window, and then drag that window to the space where I need it.

<img width="244" alt="Screenshot 2024-03-07 at 5 15 07 PM" src="https://github.com/alacritty/alacritty/assets/1116416/0b948f7a-1b85-41d3-acbd-e4dbb7b5d0e5">

**Comment by chrisduerr** [comment]
https://github.com/alacritty/alacritty/issues/6391
