### ISSUE TITLE
sub pixel problems using mononoki font

### ISSUE THREAD

**Issue by shadow-absorber** [alacritty/alacritty#7818]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

with the mononoki nerdfont the default settings leads to sub pixel problems causing weird looking stuff in tmux or in prompts using powerlevel10k
see this image: 
![image](https://github.com/alacritty/alacritty/assets/10175699/e7ba5b14-b8fa-4199-93bd-38e4b514099b)

### System

OS: endeavour os Linux
Version: `alacritty --version` output: `alacritty 0.14.0-dev (21c9138b)`
Linux/BSD: X11, i3wm picom

### Logs

Crashes: STDERR, STDOUT N/A
Font/Terminal size: `alacritty -vv`
[Alacritty-57675.log](https://github.com/alacritty/alacritty/files/14541363/Alacritty-57675.log)

Keyboard and bindings: `alacritty --print-events`

**Comment by kchibisov** [comment]
we don't generally cut the glyphs and if the AA draws outside of the glyph cutting it is an _issue_. Yes it happens sometimes, but the only thing alacritty can help is to draw the glyph itself or you can set grayscale AA.

You can also use regular powerline glyphs and given that alacritty draws them it'll render pixel perfect in terms of alignment and such (unless the font is overly narrow).

**Comment by shadow-absorber** [comment]
how would i set grayscale AA??

**Comment by kchibisov** [comment]
It's done with fontconfig, it has predefined symlinks to disable subpixel AA all together, though it maybe not desirable. So, just consult its docs or various wikis, they have plenty info on how to tune font rendering.

**Comment by shadow-absorber** [comment]
thanks! disabled sub-pixel anti aliasing in fontconfig and the sub pixel issue is completely gone with nearly no visual difference to shadow
