### ISSUE TITLE
Startup Issue with dark mode

### ISSUE THREAD

**Issue by KareemMukbil** [alacritty/alacritty#7823]
The issue is only on startup, alacritty will launch in light mode instead of dark mode with the following error: 
`[sctk adwaita] XDG Settings Portal did not return response in time: timeout: 100ms, key: color-scheme`
If i simply exit out and relaunch it goes back to normal. I'm pretty sure this issue also significantly slows down my computer on startup.

### System

OS: Linux
Version: 0.13.1
Linux/BSD: Wayland

**Comment by kchibisov** [comment]
Sounds like you have broken `xdg-desktop-portal` and you use system that asks for client side decorations (likely gnome). If you want to avoid automatic theme picking, set a theme in the config.

**Comment by KareemMukbil** [comment]
I'm using alacritty/alacritty-theme to set my theme in the config, I've always had that.
`import = {"~/.config/alacritty/themes/themes/inferno.toml"}`

**Comment by kchibisov** [comment]
Add

```toml
[window]
decorations_theme_variant = "Dark"
```

or merge it with your `[window]` section if you have it present.

**Comment by KareemMukbil** [comment]
That fixed it. Love you.

**Comment by kchibisov** [comment]
Keep in mind that GTK apps will likely delay, so I'd suggest to look into `xdg-desktop-portal`(gtk portals, etc). Also if you were using something like nixOS maybe it's just _hidden_ from alacritty...

**Comment by KareemMukbil** [comment]
Appreciate the advice, but I'm not well well-versed in gtk so I really wouldnt know what to do with `xdg-desktop-portal`
