### ISSUE TITLE
ship default configuration & prebuilt binaries for linux?

### ISSUE THREAD

**Issue by shinebayar-g** [alacritty/alacritty#7827]
### System

OS: Linux
Version: alacritty 0.14.0-dev (41d2f1df)
Linux: X11

Hey all, it looks like a really nice software and I like it! However I cannot seem to find an example configuration file? I looked at the website https://alacritty.org/config-alacritty.html and am sure it works as a great documentation for TOML lovers. But honestly I've no idea how the end results should look like. Things could've been much more intuitive if there was an actual `.toml` file shipped somewhere that I could look up and make changes?

Also is there any reason why there isn't any prebuilt binaries for Linux users?

**Comment by shinebayar-g** [comment]
@chrisduerr care to explain?

**Comment by rickalex21** [comment]
I can agree with a default config file. Kitty, DWM, and most open source projects ship with a default
opinionated config file. I searched all over the docs and could not find one.

As far Linux prebuilt binaries, most Linux distros have it. So I can see why an AppImage is not included.

**Comment by kchibisov** [comment]
DWM is not a good example, because dwm without a config is not a working software, if alacritty was like that then certainly we'll ship something.

`man 5 alacritty` is your docs, the default opinionated config is an _empty_ file, if you want to change something cherry pick that from the docs.
