### ISSUE TITLE
how to implement link function?

### ISSUE THREAD

**Issue by jm-observer** [alacritty/alacritty#7830]
hello, if I want to display "src\main.rs:7:5" on alacritty , and users can click it, then I will open [main.rs](https://main.rs/) and focus on the 7th line and 5th column. How should I do this? Is there any documentation I can refer to?

**Comment by chrisduerr** [comment]
If you're just going to not answer my questions in IRC and open an issue, at least answer the questions when opening the issue.

**Comment by jm-observer** [comment]
Sorry, I just went to rest. I opened an issue first, then realized that I could ask questions on IRC.
