### ISSUE TITLE
How drawing of cursor 'Block' works ?

### ISSUE THREAD

**Issue by iksi4prs** [alacritty/alacritty#7833]
I want to make some changes in how a cursor is drawn.
It works fine when the shape is not 'Block'.
When it is block, I always see some another "paint" which I can't find where it comes from.
In the code, I see following:
There is comment for  `// Draw cursor.` in [display/mod.rs](https://github.com/alacritty/alacritty/blob/master/alacritty/src/display/mod.rs)
Then in `fn rects`, in [display/cursor.rs](https://github.com/alacritty/alacritty/blob/master/alacritty/src/display/cursor.rs)
the following code;
```
 match self.shape() {
            CursorShape::Beam => beam(x, y, height, thickness, self.color()),
            CursorShape::Underline => underline(x, y, width, height, thickness, self.color()),
            CursorShape::HollowBlock => hollow(x, y, width, height, thickness, self.color()),
            _ => CursorRects::default(),
        }
```
Even if I change the value of the default (`_ =>`) to return something else than default, eg to return `hollow`, but with some distinct colors, I see that the result is not only the rects of `hollow`, but instead it is the result of hollow drawn over some other block rectangle.
Anyone here that can help/explain ?
10x.

**Comment by kchibisov** [comment]
Block cursor is just a change in the cell background, so it's effectively the same as you hide the cursor and change the color for the cell yourself.

**Comment by kchibisov** [comment]
https://github.com/alacritty/alacritty/blob/master/alacritty/src/display/content.rs#L163

**Comment by kchibisov** [comment]
In general if you have dev related questions try ask us on IRC first, though we may be away.
