### ISSUE TITLE
logname Command Not Working - 'no login name' Error

### ISSUE THREAD

**Issue by sebastienmascha** [alacritty/alacritty#7835]
### System

- **OS:** Ubuntu 22
- **Version:** latest 0.13.1
- **Linux/BSD:** X11

### Issue Description

When running the `logname` command in Alacritty, it fails to return the current user's login name, displaying the error `'logname: no login name'` instead. This behavior differs from other terminal emulators where `logname` successfully outputs the current user's login name. The issue suggests a potential problem in how Alacritty interacts with user session information on the system.

### Expected Behavior

Executing `logname` in Alacritty should output the current user's login name without any error, consistent with its behavior in other terminal emulators.

### Actual Behavior

The command outputs an error message: `'logname: no login name'`, indicating a failure to fetch the user's login name.

### Steps to Reproduce

1. Launch Alacritty.
2. Type `logname` and press Enter.

**Comment by chrisduerr** [comment]
Can you try with `--config-file /dev/null`? This is most likely an issue on your end.

**Comment by rocchidavide** [comment]
I have the same problem: tried `alacritty --config-file /dev/null` a suggested, but not worked. 

- OS: Mint 22
- Version: latest 0.13.2
- Linux/BSD: X11

**Comment by chrisduerr** [comment]
Closing since Alacritty has very little to do with commands running inside of it. Check your environment.
