### ISSUE TITLE
[Feature] Adding visual indication to selection type, during vi mode

### ISSUE THREAD

**Issue by iksi4prs** [alacritty/alacritty#7841]
I've added 2 small features in my code.
Do you think anyone else will be interested in one of these or both ? ("PR worthy" ?)
Details below.

**Motivation**
Adding visual indication of the selection mode.
This is helpful know always know in which mode are, as in some scenarios ((Normal and Semantic) nothing is selected on first key.
and also for people like me who never remember which is which for Alt/Ctrl/Shift + V.

**Feature description**
I've implemented 2 different ways, to see which more comfortable for me, and ended up using both, but they can be considered separate.

**Option no.1**
This will work with any cursor shape.
I've added a text label indication on the top right corner, next to [x,y]:
![image](https://github.com/alacritty/alacritty/assets/65832579/43ad281c-46d6-4b84-96ea-897d1f9e01ca)

**Option no.2**
This will work with only block cursor shape (as I think people who use other shapes will not be interested in changing their cursor shape just for this).
I've add drawing of the 1st letter of selection type, over the cursor. eg 'b' for 'Block', 'L'  for Lines etc.
(Used only 4 rectangles to keep existing code of 'hollow', so this was limiting in how letters come out, but the result is good in  my opinion)

![image](https://github.com/alacritty/alacritty/assets/65832579/4b7a536f-72df-47bf-9397-3a429f9eef20)

**Comment by chrisduerr** [comment]
Why? Who enters a mode and then immediately struggles to remember what they did 3 seconds ago?

**Comment by nixpulvis** [comment]
I like this because it’s similar to how I have my status bars setup in vim. Generally, I like to see what mode I’m in, though I can understand not wanting to take up too much space.

**Comment by chrisduerr** [comment]
> I like this because it’s similar to how I have my status bars setup in vim. Generally, I like to see what mode I’m in, though I can understand not wanting to take up too much space.

Honestly that's a good argument for why this feature isn't necessary to me personally. I've had to just check myself if the type of selection is actually shown in the mode indicator for me (it is), because it's not something I've **ever** looked for.

**Comment by iksi4prs** [comment]
@chrisduerr 

Dear Christian,
Thank you for your kind, respectful and constructive comments.
Your answer should be an example for all github maintainers.
Such language and attitude should be inspiration for positivity in our world, and it is really appreciated.
As for your question. As mentioned in the description, some people do struggle to remember all the vim keyboard binding,  some programmers are human, and not all are super-hero maintainers like you.
Though I thought about your "3 seconds rule", and I do agree with you.
In fact I don't understand why any characters need to appear on screen at all, immediately after one typed them.
_What kind of people struggle to type a key and don't remember what they did 3 seconds ago ?_
If one types 'A', what you expect to see 'B' ? 
You came out with a really good argument.
Though I would like to point out 3 points, in that context of "super-hero maintainer" .
Point 1, is that real super-heros don't really need or use vim, and hence no need to remember the keyboard bindings.
About point 2 and 3, I won't bother, I don't want to interrupt your highness.

Reading your message made me feel lucky. Go figure why...
Regards.

@gksudolol - please 'rocket' me too... much appreciated.
