### ISSUE TITLE
How to disable the deprecation notice for yml

### ISSUE THREAD

**Issue by Bios-Marcel** [alacritty/alacritty#7843]
I am currently using alacritty on multiple systems. On system, the latest available version is `0.12.X`, on the other it is `0.13.X`.

So machine A doesn't support toml, while machine B bickers to use toml. I'd be lovely if this warning could be actively suppressed. I was hoping this is already possible, but I just didn't see it?

**Comment by chrisduerr** [comment]
It's not possible.
