### ISSUE TITLE
`SIGINT` not being sent to process running in spawned `SpawnNewInstance`

### ISSUE THREAD

**Issue by RoloEdits** [alacritty/alacritty#7845]
When opening a standard alacritty instance, and running the code below, pressing `Ctrl-C` interrupts as expected.

```rust
use axum::{routing::get, Router};

#[tokio::main]
async fn main() {
    // build our application with a single route
    let app = Router::new().route("/", get(|| async { "Hello, World!" }));

    // run our app with hyper, listening globally on port 3000
    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000").await.unwrap();
    axum::serve(listener, app).await.unwrap();
}
```

However, when running it from a `SpawnNewInstance`, no interrupt is sent and the program runs until that window is closed.

This is how I spawn it: ` { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }`

### System

OS: 
```text
Edition:	Windows 11 Pro
Version:	23H2
OS build:	22631.3296
Experience:	Windows Feature Experience Pack 1000.22687.1000.0
```
Version: `fe88aaa`
shell: `nushell 0.91`

**Comment by chrisduerr** [comment]
You spawn a new instance and then do `cargo run` there, which cannot be interrupted at that point?

That sounds like a Windows bug.

**Comment by RoloEdits** [comment]
Correct, I go to the directory of the same rust project and do a cargo run, and when the axum server is running, it can't be interrupted, leaving the only way to stop it from running is to close the alacritty window.

**Comment by kchibisov** [comment]
Either windows or we setup something weirdly when spawning an instance, hard to say without further investigation.

**Comment by RoloEdits** [comment]
Just as a quick check, I went back to `tag:0.7.0` `97fc6c777769387e60c2dbc5880569658e8d23ba` , the earliest version that built for me, and spawned a new instance and saw the same behavior.  So either this is pretty much always been an issue, or some recent version of windows broke things.

**Comment by chrisduerr** [comment]
@RoloEdits Which Windows version and can you try bash?

**Comment by RoloEdits** [comment]
```text
Edition:	Windows 11 Pro
Version:	23H2
OS build:	22631.3296
Experience:	Windows Feature Experience Pack 1000.22687.1000.0
```

Running `bash` to enter into the `wsl` and running cargo inside it did interrupt as expected.

I also tested `powershell` in Windows, and as with `nushell`, it failed to interrupt.

**Comment by chrisduerr** [comment]
Sounds like a Windows issue to me then.
