### ISSUE TITLE
change keybinds with 'msg config'

### ISSUE THREAD

**Issue by DarioDarko** [alacritty/alacritty#7848]
hi,

is it possible to change keybinds with alacritty msg config? im not sure if this is not possible or if im using wrong syntax

`alacritty msg config 'window.padding = { x = 100, y = 100 }'`
this works fine

`alacritty msg config 'keyboard.bindings = { action = "ScrollToBottom", key = "End", mods = "None" }'`
invalid type: map, expected a sequence

**Comment by kchibisov** [comment]
```
alacritty msg config 'keyboard.bindings = [ { action = "ScrollToBottom", key = "End", mods = "None" } ]'
```

All IPC is in the valid toml syntax. Keep in mind that it'll nuke _config_ bindings. 

@chrisduerr maybe we shouldn't nuke them, but rather _replace all matching_?

**Comment by chrisduerr** [comment]
> maybe we shouldn't nuke them, but rather replace all matching?

Doesn't make sense for the config command to do special stuff like that imo. Could add a separate command though.

**Comment by kchibisov** [comment]
I was thinking that it'll work similar like default bindings do, when they just replace, so adding a binding like that will replace the way user config reading does it, but with the already present user bindings.

**Comment by chrisduerr** [comment]
That would logically replace **all** existing user bindings though.

**Comment by nixpulvis** [comment]
Would an `-oa` option for “option append” make sense?

**Comment by chrisduerr** [comment]
No, that's `-o -a`. I'd probably put it under an entirely different command.
