### ISSUE TITLE
feat: Tittlebar but no border?

### ISSUE THREAD

**Issue by johnmmcgee** [alacritty/alacritty#7855]
Add an option under Linux (wayland) for just the Titlebar without any window border.

**Comment by chrisduerr** [comment]
If you want specific window decorations, you should use server-side decorations.

**Comment by johnmmcgee** [comment]
This isn't possible with Gnome.

**Comment by chrisduerr** [comment]
> This isn't possible with Gnome.

Well I see a pretty simple solution for that…

**Comment by johnmmcgee** [comment]
best of luck
