### ISSUE TITLE
Cmd+Q Closes All Windows Instead of Current Window  

### ISSUE THREAD

**Issue by aharoJ** [alacritty/alacritty#7858]
**Problem:**
After the latest update, the behavior of the `Cmd+Q` shortcut has changed. Previously, `Cmd+Q` would close the current window only. However, after updating, the same command now closes all Alacritty windows, which is a significant departure from the expected behavior. 

**Expected Behavior:**
The `Cmd+Q` shortcut should close only the active window that I'm currently working in, not all open Alacritty windows.

**Steps to Reproduce:**
1. Open multiple windows of Alacritty.
2. Press `Cmd+Q` while focused on one of the windows.
3. Observe that all Alacritty windows close, instead of just the focused window.

**System Information:**
- OS: macOS
- Alacritty Version: alacritty 0.13.1 (fe2a3c5)

**Additional Context:**
The change in behavior was noticed following an update. `Cmd+W` does what I want but I have that bind to other dot-files and nvim. This issue disrupts workflow as it differs from the commonly expected macOS window management behavior.

**Comment by kchibisov** [comment]
Does it happen with the empty config file? Do you use _tabs_?

**Comment by nixpulvis** [comment]
I’m not sure I agree with the expected behavior here. CMD-W closes a single window? CMD-Q quits the whole application, no? So if you are spawning new windows without duplicating the process, I think I’d expect it to do what it’s doing.

Maybe try `SpawnNewInstance` instead of `CreateNewWindow`?

**Comment by kchibisov** [comment]
I think part of the issue is all of that is setup via the `menu`, thus we can't even change the `Cmd+Q`, though, it'll be possible to do so in the future, I guess.

**Comment by aharoJ** [comment]
@nixpulvis that worked, thank you so much. You da 🐐.
