### ISSUE TITLE
MacOS prevents opening after installation (malicious software check disabled)

### ISSUE THREAD

**Issue by cconcannon** [alacritty/alacritty#7862]
### System

OS: macOS 14.4
Version: 0.13.2

### Description

Upon downloading/installing Alacritty for the first time and attempting to open it, OS X will not open the application. The message provided is:

The application can't be opened because Apple can't check it for malicious software.

This software needs to be updated. Contact the developer for more information.

### Workaround

Open System Settings to Privacy & Security > Security Settings, and scroll down to "Allow applications downloaded from:" where you will be able to explicitly allow Alacritty to open without security checks.

**Comment by kchibisov** [comment]
Apple requires developer certificate, which we won't pay for.
