### ISSUE TITLE
[Feature Request] Send text from hint / commands to current window instead of running

### ISSUE THREAD

**Issue by jake-austin** [alacritty/alacritty#7864]
Hi, I'm really enjoying the hints feature and the ability to run custom commands on files, but I would like to have the flexibility to run the command in the current window as opposed to running in a background process, especially for use cases like vim-ing stack trace files open in the current window (important for people like myself doing most of their work on remote machines through ssh). 

I think one possible way to do this for the "command" hint would be to send the text of the command to the current window instead of running it in the shell.

What the config looks like right now for this example use case:
```
enabled = [
    # File highlighting for text files for instance
    {regex = "[^ ]+\\.txt", command = { program = "/path/to/nvim", args = [<args>] }, },
]
```

What it might look like:
```
enabled = [
    # File highlighting for text files for instance
    {regex = "[^ ]+\\.txt", command = { program = "/path/to/nvim", args = [<args>], send_text = True}, },
]
```
Where the send_text=True option literally pastes the command in the current window instead of running it in the background

Any other suggestions for how this specific case might be accomplished with alacritty (without manually copy / pasting / sed for line number) as is right now are welcome, I can't seem to find any good alternative in the current feature set that would compete with this flexibility and ease of browsing files.

**Comment by Ocaly** [comment]
> I think one possible way to do this for the "command" hint would be to send the text of the command to the current window instead of running it in the shell.

Few misconceptions, the window has nothing to do with this. The command doesn't get executed in the shell that you see, it gets executed in a new daemon (alacritty/src/event.rs:1245). 

Identifying the shell process of the alacritty window and pasting/executing text in it, is the responsibility of the system, not of Alacritty...
Solution for you (if you use x11) is to execute something like `xdotool`
