### ISSUE TITLE
OSC52 clipboard in neovim, copy works but paste doesn't

### ISSUE THREAD

**Issue by Madoshakalaka** [alacritty/alacritty#7869]
I want to use the clipboard through ssh with neovim running on the host machine.

neovim 10.0 supports OSC52 clipboard natively. Copying works but not pasting. If I try to paste anything Neovim will report `Waiting for OSC 52 response from the terminal. Press Ctrl-C to interrupt...` and eventually timeout after a few seconds. Seems like alacritty is not giving the response properly.

### System

OS: Linux
Version: alacritty 0.13.2 (bb8ea18e)
Linux/BSD: X11, Gnome

**Comment by kchibisov** [comment]
See `man 5 alacritty` for that.

**Comment by Madoshakalaka** [comment]
I see. Thanks. So there is a setting for OSC 52
