### ISSUE TITLE
Add a build guide

### ISSUE THREAD

**Issue by ZhiZe-ZG** [alacritty/alacritty#7876]
This isn't a bug report.

In order to facilitate the participation of new contributors, it is recommended to add guidance on compiling the project in the README.

If this suggestion is acceptable, I'd be happy to write a guide based on my experience building this project on Windows and create a pull requset.

**Comment by ZhiZe-ZG** [comment]
I found the installation guide:

<https://github.com/alacritty/alacritty/blob/master/INSTALL.md#linux--windows--bsd>

There is no guidance on msi file generation in this guide. At the same time, the introduction to Windows environment configuration is also very brief.

There commands for environment-dependent installation on other systems. Now on Windows systems, environment-dependent installation can also be completed through winget.

Should these be added to the guide?

**Comment by chrisduerr** [comment]
Nobody needs to generate an msi, all you need to do to get Alacritty is run `cargo build --release`.
