### ISSUE TITLE
[macOS] Inline Composition Buffer overlaps with the already-committed text in the front.

### ISSUE THREAD

**Issue by ShikiSuen** [alacritty/alacritty#7882]
[macOS] Inline Composition Buffer overlaps with the already-committed text in the front.

![image](https://github.com/alacritty/alacritty/assets/3164826/b2e4cee6-d379-407c-823a-8737d1ad731e)

### System

OS: macOS 14.4 Sonoma
Version: 0.13.2-rc1

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

I assume that --print-events is not helpful to this case. Nevertheless, ping me if maintainers think it is still of vital necessity.

**Comment by kchibisov** [comment]
You can not do anything about it other than obscuring the entire line The text you see around is on the client side.

**Comment by ShikiSuen** [comment]
@kchibisov Then why macOS built-in terminal respects this?
![image](https://github.com/alacritty/alacritty/assets/3164826/f1c1de6c-dfaf-432b-b1cc-5dfe18393607)

**Comment by ShikiSuen** [comment]
Lemme doublecheck how Alacritty handles the ICB on Windows...

**Comment by ShikiSuen** [comment]
I confirmed that this bug also happens with both Fluent Terminal and Windows Terminal on Windows. The CMD prompt is an exception since it has a standalone composition buffer at the bottom of the terminal window (only appears when the current IME utilizes a composition buffer).

If on macOS:

- **System built-in terminal app** works without issue, as of macOS 14.4 Sonoma.

- **Core Shell** works, regardless its display issues with inner composition buffer. The outer composition buffer looks well.

![image](https://github.com/alacritty/alacritty/assets/3164826/d025b2e9-31bf-4feb-8bcd-9f7aa176b94e)

- **iTerms 2** has this issue:

![image](https://github.com/alacritty/alacritty/assets/3164826/20831e27-3286-4710-a385-ecbda9c644ed)

**Comment by ShikiSuen** [comment]
Considering that it might be too hard to implement, I personally think that a dedicated bottom-docked input buffer (or a popup input buffer panel) is an acceptable alternative option.

**Comment by kchibisov** [comment]
popup input should be provided by the IME I use this popup myself on linux without any issue. what terminal.app does is not correct, but they likely don't care or they take the line and move the line artificially in renderer, but it doesn't mean that it'll match what you have, which is more confusing.

**Comment by ShikiSuen** [comment]
@kchibisov Unfortunally, it is practically not possible to persuade Apple to let their system-builtin IMEs supply popup composition buffer in identifiable IMKTextInput context.

Their InputMethodKit has certain defected APIs unfixed for more than a decade. Bug reports are always ignored. You ask the status of those radar reports on WWDC person-to-person, and your 1-to-1 Apple engineer always tell you that it's classified.
