### ISSUE TITLE
incompatible command-line interface makes alacritty an unsutible value for x-terminal-emulator

### ISSUE THREAD

**Issue by lolbinarycat** [alacritty/alacritty#7887]
because alacritty takes a subcommand, and requires the `-e` flag to start a program, it is incompatible with every single other terminal, and cannot be used with scripts that expect a generic terminal.

**Comment by chrisduerr** [comment]
Alacritty certainly isn't the only terminal emulator that requires `-e` to launch commands. In fact most terminals I've used in the past behave exactly like that.
