### ISSUE TITLE
can't map Ctrl+Shift+key

### ISSUE THREAD

**Issue by Solarunit** [alacritty/alacritty#7892]
I  can't map Ctrl+Shift+key, e.g. `Ctrl+Shift+S` or `Ctrl+Shift+X` which I could use as shortcuts in tmux.
I have followed https://github.com/alacritty/alacritty/wiki/Keyboard-mappings but with `alacritty --print-events` I don't see any escapes codes similar to "\u0003"

____
OS: Linux
Version: alacritty 0.13.2
Linux: X11, Budgie

**Comment by Solarunit** [comment]
So not possible to map there shortcuts, and no workaround?

**Comment by chrisduerr** [comment]
There are protocols supported which work around this.

**Comment by Solarunit** [comment]
https://old.reddit.com/r/neovim/comments/mbj8m5/how_to_setup_ctrlshiftkey_mappings_in_neovim_and/?rdt=64313
I tried this method:
```
[keyboard]
bindings = [
{ key = "X", mods = "Control|Shift", chars = "\x1b[88;5u" },
]
```

and  got error:

```
invalid escape sequence
expected `b`, `f`, `n`, `r`, `t`, `u`, `U`, `\`, `"`
```

**Comment by kchibisov** [comment]
That's because you rewrote it incorrectly with `\u` and it doesn't match what you had before. Should be `\u001b[88;5u`

**Comment by Solarunit** [comment]
I see, 

```
[keyboard]
bindings = [
{ key = "X", mods = "Control|Shift", chars = "\u001b[88;5u" },
]
```

Alacritty reports no errors, but shortcut doesn't work

**Comment by Solarunit** [comment]
```
{ key: T, mods: Control|Shift, chars: "\u0003" }
```
I tried Ctrl+Shift+T from the example https://github.com/alacritty/alacritty/wiki/Keyboard-mappings

When pressing Ctrl+Shift+T alacritty just prints `^C`

**Comment by kchibisov** [comment]
`^C` is `\u0003`, so works as expected. 

The binding you've used requires a special protocol as well, so it won't really work. Keep in mind that alacritty supports said encodings when application you're running supports them.

**Comment by Solarunit** [comment]
My goal to make it working in tmux. I tried this in kitty and it works there, you have to unmap internal shortcuts in the config first, e.g. `Ctrl+Shift+T`

**Comment by Solarunit** [comment]
thanks to a person on stackoverflow who said that '6u' should work and it works! :tada: 

```toml
[keyboard]
bindings = [
{ key = "X", mods = "Control|Shift", chars = "\u001b[88;6u" },
{ key = "S", mods = "Control|Shift", chars = "\u001b[83;6u" },
]
```

I wonder why such shortcuts are not included out of the box?

PS: I found a strange issue with `Ctrl+Shift+S` shortcut - it freezes Alacritty for some reason and keyboard input no longer works. I can reproduce it when no bindings are set in the config.

**Comment by kchibisov** [comment]
This is a special encoding for some special xterm mode, they will confuse all the applications. These keys however encoded like that when kitty keyboard protocol is being used, which won't work in tmux (because it doesn't support it), but it'll work outside of it in e.g. nvim.

`ctrl+(shift)+s` should freeze pty, that's how pty works, and it's out of scope for alacritty to control that, `ctrl+q` is used to resume.

**Comment by Solarunit** [comment]
Interesting, I didn't know about such `Ctrl+Shift+S` side effect.

Anyway, I mapped `Ctrl+Shift+S` and  `Ctrl+Shift+X` in tmux.conf and it works without problem. I wish they were available out of the box.

**Comment by kchibisov** [comment]
tmux should implement kitty keyboard protocol, then it'll work out of the box.
