### ISSUE TITLE
Allow receiveing keys from X11 send_events

### ISSUE THREAD

**Issue by alexandersokolow** [alacritty/alacritty#7893]
The XMonad window manager has a [sendKey](https://xmonad.github.io/xmonad-docs/xmonad-contrib/XMonad-Util-Paste.html) feature to send a certain key combination to the current window.

However, the respectively targeted application needs to support X11's send_events feature.

XTerm can be launched to support that as follows:
xterm -xrm '*allowSendEvents:true'
Emacs seems to support that feature when compiled with Motif toolkit (--with-x-toolkit=motif), or with no X toolkit (--with-x-toolkit=no).

I haven't found a corresponding Alacritty setting. Is this supported?

**Comment by kchibisov** [comment]
Yeah, we explicitly disallow send-event because it's a bit noisy sometimes, though, tools like autokey can work without it, so, it's not mandatory for synthetic input?

**Comment by chrisduerr** [comment]
I see no reason to implement this.

**Comment by kchibisov** [comment]
btw, it's relatively easy to do, given that it's `is_synthetic` thing, but I'm not sure what the use case for it, given that a lot of software including xdotool can do input without it...

**Comment by alexandersokolow** [comment]
My personal use case is that I want to bind things like alt+Tab, alt+1, etc. to ctrl+Tab, ctrl+1, etc., to more consistently be able to use alt-bindings in the Brave browser (or other Chromium based browsers) for navigating tabs.
It is possible to make use of Chromium / Chrome extensions to create custom bindings like that, but it is not a perfect solution:
- Those extensions won't work on every kind of tab, e.g. not on an empty tab
- The alt+num bindings will sometimes trigger events on certain webpages (e.g. on some video players, it will make them jump to a certain timestamp)

Now, as for the x11 feature not being mandatory:
It is more or less mandatory for XMonad users, since this is what the sendKey function mentioned above relies on.
I tried implementing this via xdotool (before I even discovered the sendKey function), but it doesn't work, unless a slight delay is added (for me it had to be at least ~200ms, which was noticable), presumably due to quirks of how XMonad handles the mappings (e.g., immediately during the key-interrupt, the window might not be focused or something like that).

It might or might not be (easily) possible to recreate a sendKey-like function in XMonad that makes use of something like xdotool, instead of relying on the X11 events & I might give it a try at some point, but if it's easy to support the X11 feature in Alacritty, it might be worth having, since Xmonad might not be the only instance of such a situation.

**Comment by ivanbrennan** [comment]
I ran into this too. I like to use Alt-c and Alt-v for copy/paste, regardless of whether I'm in a terminal or some other application, so I previously had these keybindings in my xmonad configuration:
```haskell
[ ( (modMask, xK_c),
    bindFirst
      [ (isTerminal, sendKey noModMask xF86XK_Copy),
        (isEmacs,    sendKey modMask xK_c),
        (pure True,  sendKey controlMask xK_c)
      ]
  ),
  ( (modMask, xK_v),
    bindFirst
      [ (isTerminal, sendKey noModMask xF86XK_Paste),
        (isEmacs,    sendKey modMask xK_v),
        (pure True,  sendKey controlMask xK_v)
      ]
  )
]
```

After upgrading alacritty, I found that they'd stopped working. I was able to fix them ([commit](https://codeberg.org/ivanbrennan/nixos-config/commit/f915d10d267960b98b97031e838df2e5d3ab031e)) by using `xdotool` instead,
```haskell
[ ( (modMask, xK_c),
    bindFirst
      [ (isTerminal, void $ runProcessWithInput "xdotool" ["keyup", "c", "key", "--clearmodifiers", "XF86Copy"] ""),
        (isEmacs,    sendKey modMask xK_c),
        (pure True,  sendKey controlMask xK_c)
      ]
  ),
  ( (modMask, xK_v),
    bindFirst
      [ (isTerminal, void $ runProcessWithInput "xdotool" ["keyup", "v", "key", "--clearmodifiers", "XF86Paste"] ""),
        (isEmacs,    sendKey modMask xK_v),
        (pure True,  sendKey controlMask xK_v)
      ]
  )
]
```

I'm perfectly happy with the new approach (I don't mean to re-open the issue), just wanted to describe one of the use cases.
