### ISSUE TITLE
`working_directory` doesn't work when creating a new tab

### ISSUE THREAD

**Issue by divaltor** [alacritty/alacritty#7897]
Thanks for that great terminal

When I'm in a directory other than `working_directory`, for example `cd some_folder` and then I create a new tab with `Cmd + T` new tab opens in same directory, not in directory from config. Is that expected behavior?

### System

OS: macOS 14.4.1
Version: 0.13.2

### Config

```toml
working_directory = "/Users/divaltor/"
```

**Comment by kchibisov** [comment]
Yes, we by default inherit the directory of foreground process.

**Comment by divaltor** [comment]
> Yes, we by default inherit the directory of foreground process.

Is there any way to change that behavior with config?

**Comment by kchibisov** [comment]
You can not change that, but you can manually create a similar binding via the `IPC` and directly invoking the executable.

So in the bindings section you'd need to bind `Command+N` to execute `alacritty msg create-window --working-directory foo`.

**Comment by toothbrush** [comment]
Hey there, sorry to reply to a closed issue, but your workaround is not helping for my situation.

I would like both my new tabs and windows to _always_ drop me into my homedir.  I'm on macOS.

The issue i'm facing is that with the proposed workaround, new windows drop me into `$HOME`, but new tabs have the same `$PWD` as wherever i last `cd` into.

I have tried: (with no other config, this is MWE for me)

```toml
[keyboard]
bindings = [
  { key = "N", mods = "Command", command = { program = "/opt/homebrew/bin/alacritty", args = ["msg", "create-window"] } },
  { key = "T", mods = "Command", action = "CreateNewTab" },
]
```

Can `alacritty msg` interface could perform the actions available in the bindings context? IIUC it only has the `create-window` action.

**Comment by toothbrush** [comment]
I solved my own problem in the ugliest way possible:

```toml
shell = { program = "sh", args = ["-c", "cd ~; zsh"] }
```
