### ISSUE TITLE
Character under cursor during selection does not have background highlighted in tmux

### ISSUE THREAD

**Issue by nighthawk469** [alacritty/alacritty#7901]
When selecting text with tmux, there should be a gray background rectangle, but it doesn't appear which is visually confusing. Only the selected character changes color to orange. Maybe because of the alacritty color scheme.

Terminal.app
![Screenshot 2024-04-11 at 3 05 20 PM](https://github.com/alacritty/alacritty/assets/2553980/e01bbbb0-6a3b-4c13-942b-02540df4dfda)

Alacritty
![Screenshot 2024-04-11 at 3 09 23 PM](https://github.com/alacritty/alacritty/assets/2553980/7da28fc6-47f0-42b9-855a-236155bbbd18)

### System

OS: macOS
Version: alacritty 0.13.2 (bb8ea18)
tmux 3.0a

.tmux.conf
```
set-option -g mouse on
```

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by kchibisov** [comment]
Set `cursor` in the `colors` section to a fixed values, like.

```
cursor = { text = "#181818", cursor = "#f8f8f8" }
```
