### ISSUE TITLE
CMD + Arrow jump to beginning or end of line

### ISSUE THREAD

**Issue by gabemeola** [alacritty/alacritty#7903]
`CMD + Arrow Right` and `CMD + Arrow Left` does not jump to end or start of line.  I don't see a keybind option for this as well.

### System

OS: Linux/BSD/macOS/Windows
Version: `alacritty --version` output
Linux/BSD: X11/Wayland, DE or Compositor and WM

`0.13.2` MacOS

**Comment by chrisduerr** [comment]
This is likely due to your shell. Alacritty just sends the buttons, your shell is responsible for binding them to do the things you want.
