### ISSUE TITLE
Feature request: hollow box for cursor shape

### ISSUE THREAD

**Issue by jlhg** [alacritty/alacritty#7904]
Currently alacritty does not provide the hollow box option (like emptyBox on [Windows Terminal](https://learn.microsoft.com/en-us/windows/terminal/customize-settings/profile-appearance#cursor-shape)) for cursor shape. It would be very nice if alacritty can support it.

### System

OS: macOS
Version: alacritty 0.13.1

**Comment by chrisduerr** [comment]
Hollow box cursor is a distinct shape for windows without focus. It will **not** be supported as a normal cursor shape.
