### ISSUE TITLE
Copy/paste not working macOS

### ISSUE THREAD

**Issue by jlars22** [alacritty/alacritty#7905]
Moving from iterm2 or even just the normal terminal i have always been able to just `command + c`, and `command + v` to copy and paste text. However this does not seem to work in alacritty. I am open to using new keybinds or rebinding these to get my behaviour, i just cant seem to find where/how this is done? I am using zsh.

So expected behaviour is just that i would like it to behave like normal copy/paste keybinds on macOS.

### System

OS: macOS
Version: alacritty 0.13.2 (bb8ea18)

**Comment by chrisduerr** [comment]
Empty config? US layout?

**Comment by jlars22** [comment]
It works neither on US layout or any other layout 

This is my alacritty.toml (if this is the config you meant)

Thanks
```
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9
dimensions = { columns = 5, lines = 5}

[window.padding]
x = 25
y = 20

[font]
size = 20.0
offset.y = 5

[colors.normal]
yellow = "#ffa600"
blue = "#0080ff"
green = "#32b304"
red = "#d62929"

[[keyboard.bindings]]
key = "Return"
mods = "Command"
action = "ToggleFullscreen"
```

**Comment by chrisduerr** [comment]
Command+C/V should work just fine on macOS and I'm not aware of anyone else having issues with that. But there is a platform-independent ctrl+shift+c/v binding that should also work.

This might be a silly question, but you're actually pressing Command and not Control, right?

**Comment by jlars22** [comment]
Yes it does seem very weird. It works just fine in iterm2 and other terminals. 

And yes, I am actually pressing Command and not Control. Also tried with multiple keyboards and even layouts.

What is even weirder may be that even the platform-independent ctrl+shift+c/v binding is not working either for me.

**Comment by jlars22** [comment]
It seems that after running
```
killall pboard
```
I can now copy/paste as normal again. Thanks for your time and your awesome work! 
I will close the issue.

**Comment by axxyhtrx** [comment]
same
