### ISSUE TITLE
Alacritty shows the lasted typed command

### ISSUE THREAD

**Issue by jibone** [alacritty/alacritty#7907]
### System

OS: macOS
Version: 0.13.2 (bb8ea18)

![Screenshot 2024-04-16 at 10 47 58 AM](https://github.com/alacritty/alacritty/assets/872486/03dcda24-a92d-4c70-9916-45a69e146056)

I'm sorry I'm not so sure how to describe this. As you can see on the screenshots, any command I typed gets echoed back. I am not sure how, or why this is happening. Anybody knows why this is happening?

I tested on iTerm, same zsh shell configuration, it is fine.

Here is my Alacritty toml,

![Screenshot 2024-04-16 at 10 53 16 AM](https://github.com/alacritty/alacritty/assets/872486/9b87d0f3-ad1d-4976-8bbf-f2d5c88cc9d3)

**Comment by chrisduerr** [comment]
Shell issue.

**Comment by jibone** [comment]
Can you elaborate? Both my Alacritty and iTerm uses the same shell, (zsh) but it only happens on Alacritty.
