### ISSUE TITLE
Glyphs sometimes cut off (need to draw background in single pass)

### ISSUE THREAD

**Issue by casey** [alacritty/alacritty#791]
I'm getting a visual glitch which causes the right half of certain characters to be missing. Restarting alacritty fixes it.

It happens when working with han characters, which are double width. I haven't been able to figure out the exact situation when it occurs. It seems to occur most often after displaying a lot of characters, so perhaps it's due to a cache getting filled up.

In this image, the first han character on the screen is okay, and the last three are truncated.

![half-characters](https://user-images.githubusercontent.com/1945/30730024-a89c2482-9f18-11e7-95e1-e6aec2e34d14.png)

**Comment by jwilm** [comment]
I believe this is due to us not drawing the entire background in a single pass. When the first glyph cache gets filled up, Alacritty starts batching draw calls by texture. This is supported by what you've described

> occur most often after displaying a lot of characters

and

> Restarting alacritty fixes it

I'm updating the title to reflect the required action here.
