### ISSUE TITLE
not able to setup shell and startup script

### ISSUE THREAD

**Issue by RiteshChepuri** [alacritty/alacritty#7921]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux/BSD/macOS
Version: `alacritty --version` output
Linux/BSD: X11/Wayland, DE or Compositor and WM

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

OS: LInux
Version: 0.13.2
Linux/BSD: Hyprland WM

I am not able to set the shell and startup script in alacritty

I want to start a tmux session by default on alacritty on my home directory by default.

but I am getting an error
as 
[0.000933968s] [ERROR] [alacritty_config_derive] Config error: shell: data did not match any variant of untagged enum Program

[shell]
args    =  "tmux new -s home"
program = "/bin/fish"

**Comment by chrisduerr** [comment]
Args is an array, not a string.

**Comment by RiteshChepuri** [comment]
Nope not working i tried that earlier

**Comment by kchibisov** [comment]
Should be also at the top of the config.

**Comment by RiteshChepuri** [comment]
It gives me data did not match any variant of untagged enum program error.

**Comment by chrisduerr** [comment]
Well if you make it into an array, it won't spit out that error.
