### ISSUE TITLE
how to double click in alacritty to enter into one folder and show all things?

### ISSUE THREAD

**Issue by qbai** [alacritty/alacritty#7926]
I have one question : how to double click one folder to enter into it and show all things in this folder, just like ranger? does alacritty support this feature?

**Comment by chrisduerr** [comment]
Alacritty is a terminal emulator, not a file browser. Has absolutely zero to do with this.

**Comment by qbai** [comment]
why alacritty does not support this function?  this is very useful for terminal user. you can imagine that it is very cool that  developer could browse file and run command at the same terminal window. so I suggest alacritty try to add new feature for merging ranger's function. thanks a lot
