### ISSUE TITLE
tmux leader key not working (Ctrl + space)

### ISSUE THREAD

**Issue by VialFlorian** [alacritty/alacritty#7932]
### System
OS: Windows 11 (Debian with WSL)
Version: 0.13.2

### Logs
Is there a way to print logs on windows ?

## Description
The leader key `Ctrl + space` works with the default wsl terminal but not in alacritty, it does a space in alacritty when I press `Ctrl+ space`.
I tried to switch back to the default leader key `Ctrl+ b` and it works, I also tried `Ctrl+ w` as leader key and it works, so i guess there is a only a problem with `Ctrl+ space`.

**Comment by chrisduerr** [comment]
Likely a Windows issue unless you can reproduce on Linux/macOS due to Microsoft not updating their PTY.

**Comment by VialFlorian** [comment]
Yes I also have a macOS and Linux setup and it works perfectly fine on them.
But unfortunately I cannot use alacritty on windows because of this "bug", so when I'm on windows I switch to the default wsl terminal.
That is weird that it works on the default wsl terminal but not on alacritty 🤔

**Comment by chrisduerr** [comment]
>  That is weird that it works on the default wsl terminal but not on alacritty 🤔

Windows doesn't use their own ConPTY, they ship a custom conpty dll. This is likely why it works.

Alacritty can also link against that ConPTY DLL, but you have to set that up yourself. If you're interested in putting that effort in, you can start looking from the [original PR](https://github.com/alacritty/alacritty/pull/6994).

**Comment by VialFlorian** [comment]
> Alacritty can also link against that ConPTY DLL, but you have to set that up yourself. If you're interested in putting that effort in, you can start looking from the [original PR](https://github.com/alacritty/alacritty/pull/6994).

Thank you for the information, I linked the ConPTY DLL but unfortunately it still does not work, it just sends a space character in the terminal when I hit `CTRL + space`, so I'm not sure if this problem is really related to the ConPTY DLL.

**Comment by trdloTrdelnik** [comment]
I found the solution to this problem from a [reddit post](https://www.reddit.com/r/Alacritty/comments/bd3pfl/ctrlspace_key_binding/)

Add the following in your config file (%APPDATA\alacritty\alacritty.toml)
```toml
[[keyboard.bindings]]
key = "Space"
mods = "Control"
chars = "\u0000"
```

I'm new to alacritty and ran into this problem immediately but the above solved the problem for me (running Ubuntu on WSL 2 on Windows 11)
