### ISSUE TITLE
Received an event for non-existence source: TokenInner. 

### ISSUE THREAD

**Issue by iamstupidhelpme** [alacritty/alacritty#7933]
OS: Arch
WM: Hyprland
Version: alacritty 0.13.2 (bb8ea18e)

So i just randomly get pop-up that asks me to look in logs because of non-existent source TokenInner.
So this is what i have in logs:
`[26308.448034564s] [WARN ] [calloop] [calloop] Received an event for non-existence source: TokenInner { id: 3, version: 14263, sub_id: 0 }
`
Other lines in log are normal, nothing suspicious.

**Comment by kchibisov** [comment]
it's just a warn that should not appear in a log until you enable verbose logging.
