### ISSUE TITLE
Cunieform is mangled in output

### ISSUE THREAD

**Issue by amarao** [alacritty/alacritty#7934]
Alacritty can't properly visualize cunieform from Unicode:

1. Copy paste into console: `𒆕𒅄𒈟𒈱𒉒`
2. Try to move cursor through it.

(Other glyphs: https://en.wiktionary.org/wiki/Appendix:Unicode/Cuneiform)

Characters are overlapped and get redrawn on each other on cursor movement.

### System
OS: Linux
Version: alacritty 0.13.2
Wayland, Gnome

**Comment by kchibisov** [comment]
Cursor navigation is done by the application you're running in. If you paste into `cat` and use e.g. Vi mode cursor it'll work normally, more or less.

**Comment by kchibisov** [comment]
>Characters are overlapped and get redrawn on each other on cursor movement.

This is also more or less intended, because the width for them is `1`, so they bleed into each other. Not using width 1 will break applications due to use of `wcwidth` function.
