### ISSUE TITLE
It performs weirdly while I change focus between Alacritty and other windows

### ISSUE THREAD

**Issue by BehemothTB** [alacritty/alacritty#7939]
### System

OS: Arch Linux
Kernel 6.8.7-zen1-2-zen
Version: alacritty 0.13.2 (bb8ea18e)  
WM: Hyprland 0.39.1-5

### Problem
When I change focus from an Alacritty window to another window, and do nothing, and change back, the Alacritty window doesn't accept my keyboard input. Instead, my keyboard focus still remains on the another window.

And if I change focus from an Alacritty window to another window, and input something with keyboard, and change back, everything works well and correctly.

And if I change focus between two Alacritty windows, everything works well and correctly.

These weird things only happen with Alacritty. I've tested firefox and nautilus and kitty etc. They have no similar problems.

**Comment by kchibisov** [comment]
not our bug.

**Comment by BehemothTB** [comment]
已收到
