### ISSUE TITLE
Feature request: ship / provide default `alacritty.toml`

### ISSUE THREAD

**Issue by j-lakeman** [alacritty/alacritty#7951]
### System

OS: Linux/macOS
Version: alacritty 0.13.2
Linux/BSD: X11/Wayland, DE or Compositor and WM

Would be cool if either here in the repo and / or in the distro packages a default `alacritty.toml` could be provided / shipped.
Alternatively, Alacritty could have a flag `--copy-config` like `ranger` and other applications do.

Nevertheless great application!

**Comment by kchibisov** [comment]
https://alacritty.org/config-alacritty.html

default is empty.
