### ISSUE TITLE
Alacritty config error with bell command

### ISSUE THREAD

**Issue by kode54** [alacritty/alacritty#7955]
### System

OS: Linux
Version: alacritty 0.13.2 (bb8ea18e)
Linux/BSD: Wayland, labwc/wlroots

### Logs
[Alacritty-1128257.log](https://github.com/alacritty/alacritty/files/15227553/Alacritty-1128257.log)

### Config file
```
[bell]
command = { program = "/usr/bin/pwplay", args = "/usr/share/sounds/gnome/default/alerts/click.ogg" }
```

**Comment by chrisduerr** [comment]
Args is an array, not a string.

**Comment by kode54** [comment]
Oh, thank you for clarifying.
