### ISSUE TITLE
Dialing to send server error

### ISSUE THREAD

**Issue by AmaruCoder** [alacritty/alacritty#7964]
When using the `lf` file manager in Alacritty, I keep receiving the message: `dialing to send server: dial unix ` (a file name ending in `sock`) followed by `connect: no such file or directory`. 

I have tried `lf` with iTerm without getting this error, which leads me to believe that `lf` is not the issue.

To make things interesting, after I open `lf` in iTerm, `lf` stops giving the error message in Alacritty. Is this a bug or a setting I am not aware of?

<img width="1448" alt="lf-in-alacritty" src="https://github.com/alacritty/alacritty/assets/2724075/2acd1071-5ba1-42e1-a7c1-2ffe7bf6666e">

### System

OS: MacOS Ventura 13.4.1
Version: Alacritty 0.12.2

**Comment by chrisduerr** [comment]
Not an Alacritty issue.

**Comment by AmaruCoder** [comment]
I have posted this error on the `lf` [forum,](https://github.com/gokcehan/lf/issues/1711) and after a couple of troubleshooting steps, they are sending me back. It seems that when `lf` runs in Alacritty, the server is not started?

**Comment by chrisduerr** [comment]
> It seems that when lf runs in Alacritty, the server is not started?

That's clearly their problem not ours.
