### ISSUE TITLE
Transparency: Not really a bug, but a curious observation

### ISSUE THREAD

**Issue by gyanantaran** [alacritty/alacritty#7968]
So, I was trying to reduce the opeacity, but maybe the blurring makes the opacity discrete (non-continous). Anyways, I ended with the following effect:

<img width="1680" alt="transparent" src="https://github.com/alacritty/alacritty/assets/95016059/8a001eb2-ad6b-44da-8393-bce2ec72e490">

Here you can see that I have `window.opacity = 0.0019607843132689597`, and the screen is completely transparent, but when I increase window.opacity by `0.0000000000000000001`, the screen goes completely opaque

<img width="1680" alt="opaque" src="https://github.com/alacritty/alacritty/assets/95016059/ac73968c-4363-4210-afca-6ae1bf702a14">

I am just curious why that is the case. How did I get that number? I did a manual binary search!

Thanks

edit1: updated compressed screenshots

**Comment by gyanantaran** [comment]
"..goes completely opaque", I meant, drastically opaque.

**Comment by chrisduerr** [comment]
Just floating point stuff, not much of a surprise really.

**Comment by kchibisov** [comment]
Could be in the driver itself, because on e.g. my GPUs this value works fine.
