### ISSUE TITLE
alacritty msg config "import=['/path/to/alacritty/toml']" does nothing

### ISSUE THREAD

**Issue by FelixBrakel** [alacritty/alacritty#7973]
Setting an import path to switch alacritty theme at runtime using `alacritty msg` does not seem to import said file.

### System
OS: Linux
Version: alacritty 0.13.2 (bb8ea18e)
Linux: Wayland, Hyprland, Arch

### Steps
1. add any config file (for example a theme) to the alacritty config folder `~/.config/alacritty`
2. `alacritty msg config "import=['~/.config/alacritty/additional_config.toml']"`
3. Observe nothing changes

**Comment by chrisduerr** [comment]
Why do you want to do this?

**Comment by FelixBrakel** [comment]
So I can set a different theme per ssh host.

I need to work on a number of different servers and having the terminals be visually distinct from one another helps me to not mix them up all the time.

**Comment by kchibisov** [comment]
You can just do `alacritty msg config "$(cat gruvbox_light.toml)"` for that. The theme I've used is from https://github.com/alacritty/alacritty-theme, but it should work with any, really.

**Comment by FelixBrakel** [comment]
Wow that works great! Thanks for the tip!
