### ISSUE TITLE
vi mode search wrap

### ISSUE THREAD

**Issue by bebecue** [alacritty/alacritty#7976]
Searching in vi mode wraps around

for example, search for `foo` and press `n` to go to next match

```
foo1
bar1
foo2
^
bar2
```
press `n` again

```
foo1
^
bar1
foo2
bar2
```

`^` is the highlighted match

in vim, `set nowrapscan` will disable wrapping around and stop at the last match. This can be useful while searching from long-running command's output in terminal.

The same behavior can be achieved by pipeing to a pager like `less` and then searching from that. However, it doesn't work if the interested command is already running. 

So it wound be nice if alacritty provides this function natively.

After some digging, I found it seems alacritty will always wraps around while searching at [here](https://github.com/alacritty/alacritty/blob/3a7f21b00c50748016bc4aa2916b13b5a2e27b76/alacritty_terminal/src/term/search.rs#L156)

Will this feature also be useful to someone else?

**Comment by chrisduerr** [comment]
> Will this feature also be useful to someone else?

I think this is the key point here. I don't think it's worth it to add an option for that, but it should be simple to patch if you want it changed. If there's some huge interest I might reconsider, but I doubt that.

**Comment by mightyiam** [comment]
Oh, yeah. I think I never want auto wrapping when I text search the buffer 🙄

**Comment by albel727** [comment]
@bebecue Thanks so much for your patch, it saved me a plenty of time figuring it out myself. Though it handles only one half of wrapping around, there's still wrap-around when searching towards the top. Here's the analogous patch that fixes it.
```diff
diff --git a/alacritty_terminal/src/term/search.rs b/alacritty_terminal/src/term/search.rs
index 585e191c..b4f4e8e2 100644
--- a/alacritty_terminal/src/term/search.rs
+++ b/alacritty_terminal/src/term/search.rs
@@ -195,6 +195,8 @@ impl<T> Term<T> {
             _ => end.add(self, Boundary::None, 1),
         };

+        end.line = self.topmost_line();
+
         let mut regex_iter = RegexIter::new(start, end, Direction::Left, self, regex).peekable();

         // Check if there's any match at all
```
