### ISSUE TITLE
Scrolling events from any instance are transferred to the Alacritty instance

### ISSUE THREAD

**Issue by care** [alacritty/alacritty#7977]
I can confirm that [this](https://github.com/alacritty/alacritty/issues/3927) issue has returned. Not sure when or how though, but I did not have this problem a few weeks back, and it randomly appeared recently.

When scrolling in window 1 (lets say a Firefox instance) the _n_ number of scroll events in that window will transfer to window 2 (Alacritty instance) in 1 event but with the effect of _n_. The events do not come in when outside of Alacritty, and only once focused on the Alacritty instance and utilising the scrolling wheel.

So, I thought this was a VirtualBox issue as mentioned in the issue on the winit repo which was referenced in the 3927 issue, but then I converted my VirtualBox machine to VMWare Player 17 and the exact same issue is still present. This is only occurring with Alacritty and no other terminal or window(s). 

### System

OS: `Arch Linux 6.8.9`
Version: `alacritty 13.2 (bb8ea18e)`
WM: `i3 version 4.23` & `X11` & `xorg 21.1.13`

#### Scrolling in the Alacritty instance down twice

[6.300625058s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(25165827)), event: MouseWheel { device_id: DeviceId(X(DeviceId(2))), delta: LineDelta(0.0, -1.0), phase: Moved } }
[7.283656705s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(25165827)), event: MouseWheel { device_id: DeviceId(X(DeviceId(2))), delta: LineDelta(0.0, -1.0), phase: Moved } }

#### Going to the Firefox instance, scrolling from top to bottom of a page, and then going back to the Alacritty instance to move down

[19.112886688s] [INFO ] [alacritty] winit event: WindowEvent { window_id: WindowId(WindowId(25165827)), event: MouseWheel { device_id: DeviceId(X(DeviceId(2))), delta: LineDelta(0.0, -58.0), phase: Moved } }

**Comment by kchibisov** [comment]
Could you compare `echo $ALACRITTY_WINDOW_ID` with `WindowId()` from the events, we take window id from the event X11 sends, thus if they have id of alacritty it means that we'll process it. And I think there's no way to prevent though.

**Comment by care** [comment]
The values are the same.

**Comment by care** [comment]
The ID's are the same.

**Comment by chrisduerr** [comment]
> So, I thought this was a VirtualBox issue as mentioned in the issue on the winit repo which was referenced in the 3927 issue, but then I converted my VirtualBox machine to VMWare Player 17 and the exact same issue is still present.

Is a virtual machine being involved a prerequisite? I've never had these issues on X11 myself.

**Comment by care** [comment]
Currently, yes. Just thought I'd create the issue so you guys are aware. Maybe there is a potential fix for this, but I can see why there may not be one too.

**Comment by chrisduerr** [comment]
We're not tracking issues that are only reproducible inside VMs. If someone can reproduce this natively I'm happy to re-open.
