### ISSUE TITLE
`CreateNewWindow` still creates a tab in full screen

### ISSUE THREAD

**Issue by steveyko** [alacritty/alacritty#7978]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: macOS
Version: alacritty 0.13.2 (bb8ea18)

I have the following in my toml:

```
[keyboard]
bindings = [
  { key = "N", mods = "Command", action = "CreateNewWindow" }
]
```

When I'm in full screen, it creates a new tab instead of a new window. When I'm not in full screen, it creates a new window. I don't know if I'm doing something wrong.

**Comment by nixpulvis** [comment]
Can you check your setting of "Prefer tabs when opening documents" in System Preferences under Desktop & Dock?

**Comment by steveyko** [comment]
Yup, that's it! Thank you.
