### ISSUE TITLE
`alacritty --print-events` creates a new window

### ISSUE THREAD

**Issue by steveyko** [alacritty/alacritty#7979]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: macOS
Version: alacritty 0.13.2 (bb8ea18)

When I run `alacritty --print-events`, it creates a new window. This happened while I was getting the logs to open an issue here.

**Comment by nixpulvis** [comment]
What do you expect? You're starting a new application instance.

**Comment by steveyko** [comment]
Oh, yeah, I got it :-)
