### ISSUE TITLE
Restart config monitor on file reload

### ISSUE THREAD

**Issue by tllilleh** [alacritty/alacritty#7981]
Making changes to a configuration file that is imported by the main alacritty.toml file do not trigger an automatic config reload.

In order to get the changes without restarting alacritty I normally just do something like `touch ~/.config/alacritty/alacritty.toml`.

### System

OS: Linux
Version: alacritty 0.13.2 (bb8ea18e)

**Comment by kchibisov** [comment]
you need to touch imported files and not the main one to reload them.

**Comment by tllilleh** [comment]
If I modify (or touch) the toml file being imported (say theme.toml), it does not auto reload the config (as I believe it should).  Instead, I need to touch the top level config (alacritty.toml) for it reload the changes I made in theme.toml

**Comment by chrisduerr** [comment]
Any symlinking involved? It works just fine for me.

**Comment by tllilleh** [comment]
My entire `~/.config/alacritty` directory is a symlink to my dotfiles directory:

`lrwxrwxrwx  1 tllilleh tllilleh   39 May 14 10:13  alacritty -> ../dotfiles/alacritty/.config/alacritty/`

But inside the `alacritty` directory there are no symlinks:

```
$ ll -R
.:
total 16
drwxrwxr-x 3 tllilleh tllilleh 4096 May 15 15:19 ./
drwxrwxr-x 3 tllilleh tllilleh 4096 May 14 10:11 ../
-rw-rw-r-- 1 tllilleh tllilleh  576 May 15 17:24 alacritty.toml
drwxrwxr-x 2 tllilleh tllilleh 4096 May 15 17:24 themes/

./themes:
total 28
drwxrwxr-x 2 tllilleh tllilleh 4096 May 15 17:24 ./
drwxrwxr-x 3 tllilleh tllilleh 4096 May 15 15:19 ../
-rw-rw-r-- 1 tllilleh tllilleh  711 May 15 16:39 base16.toml
-rw-rw-r-- 1 tllilleh tllilleh  494 May 15 08:54 everforest_dark.toml
-rw-rw-r-- 1 tllilleh tllilleh  573 May 15 08:56 gruvbox_dark.toml
-rw-rw-r-- 1 tllilleh tllilleh  638 May 15 17:24 kanagawa_dragon.toml
-rw-rw-r-- 1 tllilleh tllilleh  556 May 15 08:54 zenburn.toml
```

**Comment by chrisduerr** [comment]
Does it work without any symlinks?

**Comment by chrisduerr** [comment]
Is it accurate to say you added the import after starting Alacritty? Config imports are only monitored if the import is present at startup.

**Comment by tllilleh** [comment]
> Is it accurate to say you added the import after starting Alacritty? Config imports are only monitored if the import is present at startup.

Yes, that seems to be the issue.  If I restart alacritty now changes to my theme files are auto reloaded.

**Comment by chrisduerr** [comment]
I think there's two reasonable options here, both of which should work fine:
 1) Shut down config monitor when the imports change
 2) Notify the config monitor about changes to specific files (add/remove)

**Comment by ksolowoniuk** [comment]
My config imports a theme file but live_config_reload doesn't work and doesn't work if I comment out the import??

**Comment by vext01** [comment]
I've been trying to figure out why my script to flip alacritty themes between light and dark only updates some of the terminals. I think it may be this issue.

In the meantime, is there a command I can run to force alacritty to re-read its config file? `touch` doesn't seem to work for some reason. If I edit the config file in vim and `:w` the terminals all update.

**Comment by vext01** [comment]
Putting this at the end of my script seems to do the trick:
```
nvim ~/.config/alacritty/alacritty.toml +'wq'
```
