### ISSUE TITLE
WASM Support.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [alacritty/alacritty#7985]
Please support using Alacritty in webpages using WASM. As https://github.com/warpdotdev/Warp/blob/e37f458cf274e8452bbf7eee61fe805db610d23e/README.md?plain=1#L35 demonstrates, other terminals have this on their roadmaps.

### System

<table><tr>
	<th>OS</th>
	<td>WASM</td>
</tr><tr>
	<th>Version</th>
	<td><a href="https://github.com/alacritty/alacritty/releases/tag/v0.13.2">https://github.com/alacritty/alacritty/releases/tag/v0.13.2</a></td>
</tr><tr>
	<th>Linux/BSD</th>
	<td>All</td>
</tr></table>

**Comment by chrisduerr** [comment]
No.
