### ISSUE TITLE
'Open alacritty here' does not work when working_directory is set

### ISSUE THREAD

**Issue by codevogel** [alacritty/alacritty#7987]
If I right click in a directory and click 'Open alacritty here', I open alacritty in the `working_directory` rather than the directory I clicked 'Open here' in.

Steps to reproduce:
- Set `shell.program = 'wsl'`
- Right click to open alacritty in a folder somewhere on your system, observe that you are indeed in the corresponding directory
- Now set `working_directory` to a directory such as `working_directory = '\\wsl$\Ubuntu\home\kamiel'`
- Right click to open alacritty in the same folder, observe that you are now in the `working_directory`

### System

OS: Windows + WSL
Version: v[0.13.2](https://github.com/alacritty/alacritty/releases/tag/v0.13.2)
Linux/BSD: Ubuntu 22.04.4 LTS

### Logs

Crashes: -
Font/Terminal size: -
Keyboard and bindings: -

**Comment by chrisduerr** [comment]
The "open here" stuff works just by passing `--working-directory` to the CLI. Can you confirm that the behavior is identical when trying to open with the CLI option? As far as I remember, CLI should overrule config here.

**Comment by codevogel** [comment]
> The "open here" stuff works just by passing `--working-directory` to the CLI. Can you confirm that the behavior is identical when trying to open with the CLI option? As far as I remember, CLI should overrule config here.

`alacritty --working-directory C:\Users\Kamiel\Workspace` opens alacritty in the Workspace dir, but right clicking in the Workspace folder and selecting open here from the context menu brings me to the working-directtory set in my toml.

Would there be a way to determine with what arguments alacritty was launched? Then I could test what the 'Open here' actually does.

**Comment by chrisduerr** [comment]
How did you install Alacritty? Also can you try without `wsl` shell?

**Comment by codevogel** [comment]
> How did you install Alacritty? Also can you try without `wsl` shell?

I tried installing Alacritty through the binary on the releases page and through choco.

When I remove the `shell.program = 'wsl'` line, the problem persists (it launches PowerShell in my wsl home directory)

**Comment by chrisduerr** [comment]
What happens when you set the working directory to **not** be your home directory? Does it still move you there, say /tmp for example?

**Comment by kchibisov** [comment]
I'm pretty sure it was fixed by 6585d60408be1d6c275a41e4c94da092482a1ea7 which is not present in any release yet.

So you can try build msi yourself.

**Comment by codevogel** [comment]
> I'm pretty sure it was fixed by [6585d60](https://github.com/alacritty/alacritty/commit/6585d60408be1d6c275a41e4c94da092482a1ea7) which is not present in any release yet.
> 
> So you can try build msi yourself.

I haven't tried this yet but it seems quite obvious that that should do it, yeah.
