### ISSUE TITLE
New window under one icon: Better implementation for 3rd party tools launching alacritty on macOS

### ISSUE THREAD

**Issue by aspauldingcode** [alacritty/alacritty#7990]
ok but how do I do this without using alacritty to do so?
like, instead of a binding, I want to have it by default launch a new window using the same icon.

with skhd on macos. 
I can use the osascript, or open commands all I want but if alacritty's default behavior is just to create a new icon in the dock instead of grouping as a subinstance of the original than that's not on me. 
You guys gotta solve that.
There should be an option to keep new windows under one icon in macOS dock.

_Originally posted by @aspauldingcode in https://github.com/alacritty/alacritty/issues/6346#issuecomment-2123547543_

**Comment by aspauldingcode** [comment]
The following commands:
`osascript -e 'do shell script "open -n -a Alacritty"'`
`open -n -a Alacritty`
should open under one icon by default. 
Since this is not the current behavior, I wish it to be available as a user-config default createnewwindow option - without assigning it to a bind in alacritty.

**Comment by anderssvendal** [comment]
Mac, skhd, yabai user here.

To open new window without getting a new icon I use the following command: `/Applications/Alacritty.app/Contents/MacOS/alacritty msg create-window`

**Comment by sangaline** [comment]
Thanks, that's helpful. You can try to send the create-window message first and then fall back to opening the application if it wasn't already running:

```
cmd - return : alacritty msg create-window || open -na alacritty
```

**Comment by aspauldingcode** [comment]
Excellent!
Fixes https://github.com/FelixKratz/SketchyBar/discussions/12#discussioncomment-9609384.
