### ISSUE TITLE
Run GitHub Actions tests in `ci.yml` on Linux (in addition to Windows and macOS)

### ISSUE THREAD

**Issue by mbrukman** [alacritty/alacritty#7997]
The GitHub Actions configured to run on every push and PR in `ci.yml` currently only runs on Windows and macOS:

https://github.com/alacritty/alacritty/blob/f04b16161bc542075fdb8e5946a8eed976f26b0b/.github/workflows/ci.yml#L12

Is there any reason Linux is not included here? Happy to add it here if you'd be open to it.

Linux **is** included in the release workflow:

https://github.com/alacritty/alacritty/blob/a89d4f50dc6ac0256d6d52371c3711107de8c7d2/.github/workflows/release.yml#L62-L63

so presumably it should also be included in the regular testing process.

**Comment by chrisduerr** [comment]
We just use a different CI for Linux.
