### ISSUE TITLE
[Feature Request] Set font size with hotkey

### ISSUE THREAD

**Issue by tokisuno** [alacritty/alacritty#8004]
I have moments where I want to change my font size, but I don't want to have to press the hotkey a bunch of time to get it "just right".

I think it would save a lot of time having a key bound to set the terminal's font size to X number or something of the sort.

ex. 
bind C-9 fontsize=20.5
bind C-1 fontsize=13.5

**Comment by kchibisov** [comment]
`alacritty msg config font.size=20`
