### ISSUE TITLE
Ctrl-Shift-Space doesn't trigger Vi Mode on MacOS

### ISSUE THREAD

**Issue by sangaline** [alacritty/alacritty#8006]
I resolved this, but wanted to share the solution in case anybody runs into this and searches the issues. Ctrl-Space is bound to "Select the previous input source" on MacOS, so you won't be able to pass Ctrl-Shift-Space through to Alacritty unless you disable or change this keybinding:

<img width="694" alt="image" src="https://github.com/alacritty/alacritty/assets/8236564/28a7de7a-8232-444c-9083-dcea6a880152">

**Comment by kaden-l-nelson** [comment]
Took way too long to find this.
