### ISSUE TITLE
JuliaMono font wont be colorful

### ISSUE THREAD

**Issue by Dolfost** [alacritty/alacritty#8007]
### System

OS: macOS
Version: `alacritty 0.13.2 (bb8ea18)`

### How to reproduce
Install [JuliaMono font](https://github.com/cormullion/juliamono).
Be on macOS and install alacirtty from Homebrew. Set the `~/.config/alacritty/alacritty.toml` to
```
[font.normal]
family = "JuliaMono"
```
Finally all my text is becoming white (seems like colored output works only with the text backgound).

For test i used this bash script:
```
for x in {0..8}; do 
    for i in {30..37}; do 
        for a in {40..47}; do 
            echo -ne "\e[$x;$i;$a""m\\\e[$x;$i;$a""m\e[0;37;40m "
        done
        echo
    done
done
echo ""
```

So there is the setup with the JuliaMono font
<img width="629" alt="Screenshot 2024-05-28 at 2 11 58 AM" src="https://github.com/alacritty/alacritty/assets/59747489/5cf79950-3273-45ca-948f-3f2a7529beb3">

And there is the same command with the empty `~/.config/alacritty/alacritty.toml`:
<img width="627" alt="Screenshot 2024-05-28 at 2 14 00 AM" src="https://github.com/alacritty/alacritty/assets/59747489/580808b2-2732-4922-a8fd-1c39197e085d">

The text become colorful! How to make JuliaMono work with alacritty? Am I doing something wrong?

My friend tried the same setup on pure linux and did not experience this.

### Logs
```
➜  alacritty git:(main) ✗ alacritty -vv
Created log file at "/var/folders/fx/lxhzhmnx1l3cd0ymf8xkkgmr0000gn/T/Alacritty-22808.log"
[0.000005375s] [INFO ] [alacritty] Welcome to Alacritty
[0.000294459s] [INFO ] [alacritty] Version 0.13.2 (bb8ea18)
[0.000505084s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/Users/vladyslav/.config/alacritty/alacritty.toml"
[0.000852334s] [DEBUG] [alacritty] Using environment locale: en_US.UTF-8/UTF-8/en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/en_US.UTF-8
[0.019843417s] [INFO ] [alacritty] Using Apple CGL
[0.030101709s] [DEBUG] [alacritty] Picked GL Config:
                                     buffer_type: Some(Rgb { r_size: 8, g_size: 8, b_size: 8 })
                                     alpha_size: 8
                                     num_samples: 0
                                     hardware_accelerated: true
                                     supports_transparency: Some(true)
                                     config_api: Api(OPENGL)
                                     srgb_capable: true
[0.054665584s] [INFO ] [alacritty] Window scale factor: 2
[0.055585584s] [DEBUG] [alacritty] Loading "JuliaMono" font
[0.096164875s] [INFO ] [alacritty] Running on Apple M2
[0.096195167s] [INFO ] [alacritty] OpenGL version 4.1 Metal - 88.1, shader_version 4.10
[0.096204125s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.099614000s] [DEBUG] [alacritty] Filling glyph cache with common glyphs
[0.107411500s] [INFO ] [alacritty] Cell size: 13 x 26
[0.107443542s] [INFO ] [alacritty] Padding: 0 x 0
[0.107452625s] [INFO ] [alacritty] Width: 1600, Height: 1200
[0.119993459s] [INFO ] [alacritty] PTY dimensions: 46 x 123
[0.122740709s] [INFO ] [alacritty] Initialisation complete
[12.126786542s] [INFO ] [alacritty] Goodbye
Deleted log file at "/var/folders/fx/lxhzhmnx1l3cd0ymf8xkkgmr0000gn/T/Alacritty-22808.log"
```

**Comment by chrisduerr** [comment]
Does the font include things like emojis? I feel like it's just broken, not worth looking into.

**Comment by Dolfost** [comment]
> Does the font include things like emojis? I feel like it's just broken, not worth looking into.

As they say on the [official website](https://juliamono.netlify.app/#juliamono_-_a_monospaced_font_for_scientific_and_technical_computing):

> JuliaMono is a monospaced typeface designed for programming and other text editing environments that require a wide range of specialist and technical Unicode characters. It was presented at the 2020 JuliaCon conference (which was to have been held in Lisbon, Portugal, but took place online.)

I don't think that there should be any problems with this font. And, As I said above:

> My friend tried the same setup on pure linux and did not experience this.

So, it could be macSO only issue.

**Comment by ankraft** [comment]
The JuliaMono font works fine with me. The output looks like you second screenshot. 
My settings are a bit though (I added the styles):

```toml
[font]
normal = { family = "JuliaMono", style = "Regular" }
bold = {  style = "Bold" }
italic = { style = "RegularItalic" }
bold_italic = { style = "BoldItalic" }
```

**Comment by Dolfost** [comment]
> The JuliaMono font works fine with me. The output looks like you second screenshot. My settings are a bit though (I added the styles):
> 
> ```toml
> [font]
> normal = { family = "JuliaMono", style = "Regular" }
> bold = {  style = "Bold" }
> italic = { style = "RegularItalic" }
> bold_italic = { style = "BoldItalic" }
> ```

I tried Your setup, it won't work either... Produces the same output.

**Comment by ankraft** [comment]
> I tried Your setup, it won't work either... Produces the same output. What OS do You use?

I am using MacOS 14.5 (Sonoma), Alacritty 0.13.2, and have JuliaMono version 0.051 installed.
Instead of bash I used zsh to run your script with the slight modification of replacing all `\e` with `\033`.

**Comment by Dolfost** [comment]
> > I tried Your setup, it won't work either... Produces the same output. What OS do You use?
> 
> I am using MacOS 14.5 (Sonoma), Alacritty 0.13.2, and have JuliaMono version 0.051 installed. Instead of bash I used zsh to run your script with the slight modification of replacing all `\e` with `\033`.

I have almost same setup. Only the font version differs, I have the v0.055. I downloaded the v0.051 and everything started to work as expected. Seems like there is something up with newer font versions. Could someone explain what's up?

Seems like this isn't alacritty's issue, so I think this is reasonable to close issue with this comment.

**Comment by ankraft** [comment]
> I have almost same setup. Only the font version differs, I have the v0.055. I downloaded the v0.051 and everything started to work as expected. Seems like there is something up with newer font versions. Could someone explain what's up?

I guess this latest change in JuliaMono 0.055 is the culprit:
(Taken from https://github.com/cormullion/juliamono/blob/master/CHANGELOG.md)

` U+E800 (the Julia logo) will appear in color in compliant environments, fixes # 201`

> Seems like this isn't alacritty's issue, so I think this is reasonable to close issue with this comment.

Perhaps you could raise an issue at JuliaMono's repo?
Or comment on this issue: https://github.com/cormullion/juliamono/issues/201 ? There are some discussions on terminal programs already.

**Comment by Dolfost** [comment]
> > I have almost same setup. Only the font version differs, I have the v0.055. I downloaded the v0.051 and everything started to work as expected. Seems like there is something up with newer font versions. Could someone explain what's up?
> 
> I guess this latest change in JuliaMono 0.055 is the culprit: (Taken from https://github.com/cormullion/juliamono/blob/master/CHANGELOG.md)
> 
> ` U+E800 (the Julia logo) will appear in color in compliant environments, fixes # 201`
> 
> > Seems like this isn't alacritty's issue, so I think this is reasonable to close issue with this comment.
> 
> Perhaps you could raise an issue at JuliaMono's repo? Or comment on this issue: [cormullion/juliamono#201](https://github.com/cormullion/juliamono/issues/201) ? There are some discussions on terminal programs already.

Thank You! I will do something about it

**Comment by cormullion** [comment]
@Dolfost Your bash script looks OK in MacOS Terminal with JuliaMono v0.055:

<img width="713" alt="Screenshot 2024-05-29 at 08 53 45" src="https://github.com/alacritty/alacritty/assets/52289/d6b9e0ff-5722-4cc0-acae-097c89a88291">

but in Alacritty it looks like this:

<img width="762" alt="Screenshot 2024-05-29 at 08 54 12" src="https://github.com/alacritty/alacritty/assets/52289/638f1745-bf2b-4bba-a7c8-8cd7764ce83d">



@chrisduerr 

>On macOS with core text, fonts are determined to be colorful/not on a per-font, rather per-glyph level. So if there's any colorful glyphs in your fonts, you won't be able to change the text color.

Interesting. My admittedly brief testing last month didn't reveal many problems with colored text. Here's MacOS Terminal (left) and Alacrity (right).  I thought both looked reasonably happy to display a colored glyph.

<img width="1207" alt="Screenshot 2024-05-29 at 08 50 57" src="https://github.com/alacritty/alacritty/assets/52289/ae8bb248-5ed6-475e-84cc-896955b23431">

But it seems that both Wezterm and Alacritty, to name two, aren't completely happy with a font that has one or more color glyphs. Although I'm not totally convinced it should be a problem in theory, it obviously is in practice, so I think I will revert the colored glyph addition, for now.

**Comment by kchibisov** [comment]
@cormullion if you're familiar on how to detect colored glyphs with core-text in a more robust way please let us know. For now we know that macOS just have a per-font colored flag, which we check and those alter rendering, so having only a single colored glyph will make the font as colored according to core text.

You can probably put the font with colored stuff in a separate file, idk, that will work fine.

**Comment by cormullion** [comment]
@kchibisov I’m pretty ignorant, unfortunately. 😂 Maybe Apple is using private APIs - this might explain why Terminal.app and Alacritty behave differently. 🤔

Anyway, I think I’ll be conservative with this font design feature going forward! 😀
