### ISSUE TITLE
font smoothing is not working in non-retina displays

### ISSUE THREAD

**Issue by sjdonado** [alacritty/alacritty#8009]
Fonts are rendered thinner compared to other applications.

### System

OS: macOS 14.5 (23F79)
Version: alacritty 0.13.2 (bb8ea18)

## Output

<img width="1262" alt="image" src="https://github.com/alacritty/alacritty/assets/27580836/b01637c4-14fe-496c-b711-e8282b751bd7">

<img width="1263" alt="image" src="https://github.com/alacritty/alacritty/assets/27580836/941891d8-3826-4d98-af6f-1ae82be0043a">

**Comment by nixpulvis** [comment]
@sjdonado have you checked out the thread in #7333?

**Comment by chrisduerr** [comment]
Alacritty makes no guarantees that its font rendering behaves exactly as other applications.

**Comment by sjdonado** [comment]
@nixpulvis Thank you for the help, I just checked it but still I doesn't work for LCD displays :(
