### ISSUE TITLE
Forward delete (Fn+Back) not working on MacOS when logging to linux via ssh

### ISSUE THREAD

**Issue by nv-pipo** [alacritty/alacritty#8011]
When I log via ssh to _some_ systems: character forward delete (Fn + Back) doesn't work. It works when try on iTerm. Trying to use the escape sequence from iTerm on Alacritty: Alacritty says that "Fn" is not a valid 'mods' key:

Toml config snippet I am trying:
[keyboard]
bindings = [
    # forward delete character
    { key = "Back", mods = "Fn", chars = "\u0004" },
]

Note that when I replace 'Fn' with 'Control', I can forward delete using Control+Back.

Trying a different route:
Running keyboard listeners, I got this output (when pressing Fn+Back):
xxd -psd: ^[[3~
showkwy: <ESC>[3~
alacritty --print-events: \u{f728}

Is there a way to use any of those in the configuration file? Looking at the documentation I didn't see any reference on how to use them.

Thanks for the speedy terminal!!!

### System

OS: macOS
Version: ❯ alacritty 0.13.2 (bb8ea18)

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by nixpulvis** [comment]
I could be mistaken if your keyboard layout is different than mine on macOS, but I belive you want this:

```toml
[[keyboard.bindings]]
key = "Delete"
chars = "\u0004"
```

`Fn` isn't actually a modifier, it changes the physical key that is sent to the application as far as I know.

**Comment by nv-pipo** [comment]
@nixpulvis,
Thanks! your keybinding suggestion worked as desired.

Maybe this should be the default behaviour of "Delete" on MacOS? or at least be documented somewhere?

**Comment by nixpulvis** [comment]
Ι'm not sure what needs to change by default, the backspace and delete (fn+backspace) keys both work for me out of the box. I'm also not quite sure why SSH is related here.

**Comment by nv-pipo** [comment]
I am running Alacritty on MacOS, and delete (forward remove character) does work out of the box on MacOS zsh sessions, also when I login to Ubuntu machines via SSH...however when I login to Alpine Linux machines it doesn't work ('~' is printed instead of 'deleting'.

I am not sure why thought.

**Comment by nixpulvis** [comment]
@nv-pipo I'm guessing your keyboard layout on the Alpine Linux box is set to British (GB) or something. If it's an X11 system you could try `setxkbmap en` I think. Maybe read over this thread and see if it helps you understand: https://stackoverflow.com/questions/67894797/keyboard-layout-is-correct-within-tty-of-alpine-linux-but-not-with-xorg-and-dwm.

**Comment by nv-pipo** [comment]
@nixpulvis that is not it. All the systems are configured to US, and no desktop packages are installed in either of the Linux systems.

My **feeling** is some "old" vs "new" way to signal the tty to perform a delete...so MacOS/Ubuntu work with either the "old" or the "new" way, but alpine only works the "old" way.
