### ISSUE TITLE
Alacritty not working with Sway

### ISSUE THREAD

**Issue by PrathmeshVishwakarma** [alacritty/alacritty#8014]
### System

OS: Linux
Version: 0.13.2 (bb8ea18e)
SwayWM and Sway

### Logs
Weirdly there are two different error logs when I run the same command consecutive times

https://paste.ofcode.org/RDCVty87U5gbUj7Eg3B9Rw
https://paste.ofcode.org/em3BWMWHtNdjDw3uxFcV8L 
 
Thanks.

**Comment by chrisduerr** [comment]
Which sway version?

**Comment by kchibisov** [comment]
Looks like mesa/sway/wlroots bug. We don't control any of what errors.

**Comment by PrathmeshVishwakarma** [comment]
> Which sway version?
Latest, 1.9
I am on VMware btw if that matters

**Comment by chrisduerr** [comment]
>  I am on VMware btw if that matters

Certainly doesn't help you.
