### ISSUE TITLE
Unicode font not show

### ISSUE THREAD

**Issue by JiuRanYa** [alacritty/alacritty#8018]
This is the default config for alacritty
![image](https://github.com/alacritty/alacritty/assets/58846658/a59975dd-be29-4b38-9cd7-01702d058cbb)
This is the kiity:
![image](https://github.com/alacritty/alacritty/assets/58846658/2a346561-bfd3-42ba-b9fe-404cda8a0e13)

Using the font that kitty using also not work.

### System

OS: macOS
Version: latest
Linux/BSD: X11/Wayland, DE or Compositor and WM

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by chrisduerr** [comment]
Not interested in debugging macOS font fallback.

**Comment by JiuRanYa** [comment]
ok, Noting I can do solve this :(
