### ISSUE TITLE
Ctrl-Enter Not Working in chatgpt.nvim Plugin with Alacritty and tmux

### ISSUE THREAD

**Issue by rafaelleru** [alacritty/alacritty#8019]
I'm encountering an issue with the chatgpt.nvim plugin in my Neovim configuration. When using Alacritty terminal and tmux, the combination Ctrl-Enter does not work to submit a prompt in the chatgpt.nvim plugin.

Steps to Reproduce:

Set up Neovim with the chatgpt.nvim plugin.
Use Alacritty terminal.
Open a tmux session.
Try to submit a prompt using Ctrl-Enter in the chatgpt.nvim prompt.
Expected Behavior:

The Ctrl-Enter combination should submit the prompt in the chatgpt.nvim plugin.

Actual Behavior:

The Ctrl-Enter combination does not submit the prompt. It seems that the key combination is not being recognized or forwarded correctly.

Environment:

OS: Ubuntu
Alacritty Version: latest

Other key combinations seem to work correctly within Neovim, Alacritty, and tmux. The issue appears to be specific to the Ctrl-Enter combination in this setup.

showkey -a shows ctrl-enter as ^M

**Comment by kchibisov** [comment]
tmux issue.
