### ISSUE TITLE
Feature request: It should remember window placement and size on startup

### ISSUE THREAD

**Issue by feketegy** [alacritty/alacritty#8021]
On a multi-display setup it should remember the window placement and size when the application was closed and place it there with the same size when starting the app again.

Currently, it seems that it opens the app window on the main display with a default window size.

**Comment by nixpulvis** [comment]
This would probably be something that `winit` would have to have support for if it was going to be possible, no? Seems like it could end up being a lot of platform specific code.

How should it handle multiple windows/tabs? Surely we’re not proposing saving the full state of the terminal (e.g. scrollback) and restoring that, so simply spawning the same number of windows/tabs would be the desired result?

Personally, I don’t think I’d ever want to do this. When I open a terminal I only need one at a time. If I need a lot, it’s rarely, and I can make a script for that which also starts up applications I want to run with them.

**Comment by feketegy** [comment]
I use multiple terminal window tabs all the time. On macOS most of the app windows are restored to it's place when it was closed.


In my original feature request I wasn't referring to restore the full terminal state including the history and scroll backs, just the window state.


For example if the macOS Finder app is left on my secondary screen and resized to a specific size and I close it, when I open it up again it will restore the window to the same position with the same window size.


I hope this makes it more clear what I was referring to in my original comment.

**Comment by nixpulvis** [comment]
So I guess opening the application restores the last focused window state? I would find it very odd for opening alacritty to ever open multiple windows personally.

**Comment by feketegy** [comment]
> So I guess opening the application restores the last focused window state?


That would work, without opening all the windows that were open during the previous session.

**Comment by chrisduerr** [comment]
That just seems pointlessly complicated.
