### ISSUE TITLE
Wayland NoCompositor Error

### ISSUE THREAD

**Issue by Re4GD** [alacritty/alacritty#8025]
I am using KDE Plasma 6 that uses Wayland. I frequently get this error however I don't know what triggers it. If Alacritty is already opened I can use it but I cannot open new terminals. I opened up Konsole and launched Alacritty from there. This is the output I got. After a reboot it goes back to normal.

### System

OS: Arch Linux
Version: alacritty 0.13.2 (bb8ea18e)
Linux/BSD: KDE Plasma 6 Wayland, kwin_wayland

### Logs

```Error: Os(OsError { line: 80, file: "/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/wayland/event_loop/mod.rs", error: WaylandError(Connection(NoCompositor)) })```

**Comment by chrisduerr** [comment]
Make sure whatever starts Alacritty has the `WAYLAND_DISPLAY` environment variable set.
