### ISSUE TITLE
Missing /usr/share/xdg-terminals entry in apt package preventing from easily changing default terminal

### ISSUE THREAD

**Issue by IlyaSlesar** [alacritty/alacritty#8028]
I don't know if this repo is the right place to report this packaging issue which may or may not be specific to my distribution, but I haven't found a better place to do so. I will be happy to report this issue someplace else if you advise me where. Thanks.

### System

OS: Linux, Ubuntu 24.04 LTS
Version: 0.13.2-1ubuntu1
Linux: X11, GNOME 46
Alacritty is installed from Ubuntu APT Repository and is updated to the latest version (0.13.2-1ubuntu1)

### Issue
When I wanted to change the default terminal in GNOME after installing Alacritty I found out that which terminal is used by DE for launching .desktop files with `Terminal=True` is specified as per xdg-terminal-exec docs in configuration file `xdg-terminals.list`. However, after replacing GNOME Terminal entry with Alacritty.desktop in this list of terminals xdg-terminal-exec stopped working altogether. After debugging the xdg-terminal-exec I found out that Alacritty does not put (a copy/symlink of) it's .desktop file into the standard `/usr/share/xdg-terminals` directory where xdg-terminal-exec is trying to find it. This is easily fixable by the end-user, but by installing it's .desktop file to xdg-terminals directory Alacritty would better adhere to the standard. Also, this would make it at least a little bit easier to set it as a default option for GNOME, which is already an unnecessarily cumbersome process with a lack of good easily searchable documentation.

### Suggested fix
Install Alacritty.desktop to `/usr/share/xdg-terminals` by default

**Comment by chrisduerr** [comment]
> I don't know if this repo is the right place to report this packaging issue

It's not.
