### ISSUE TITLE
Passing `shell.args` option to `msg create-window` results in error

### ISSUE THREAD

**Issue by afh** [alacritty/alacritty#8029]
Passing `shell.args` option to `msg create-window` results in error: `data did not match any variant of untagged enum Program`:

`alacritty msg create-window  -o 'shell.program="man"' -o 'shell.args=["alacritty"]'`

from Alacritty-11510.log
```
[9960.536845708s] [ERROR] [alacritty_log_window_config] Unable to override option 'shell.args=["alacritty"]': data did not match any variant of untagged enum Program
```

I'd expect a new alacritty window to open in which the `man` program and `alacritty` as its argument is run.

### System

OS: macOS
Version: 0.13.2
~~Linux/BSD: X11/Wayland, DE or Compositor and WM~~

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by chrisduerr** [comment]
You need to specify both in a single option. On their own they aren't valid.

**Comment by afh** [comment]
Thanks for the quick response, @chrisduerr!

`alacritty msg create-window  -o 'shell={program="man",args=["alacritty"]}'` works like a charm, much obliged! 👍
