### ISSUE TITLE
"transparent_background_colors = true" affects segments pattern

### ISSUE THREAD

**Issue by ZhulanovAA** [alacritty/alacritty#8031]
# Issue

A pattern like this uses combination of foreground and background colors with special characters to make nice segments in terminal:

![image](https://github.com/alacritty/alacritty/assets/10975197/6e70bf3a-24e3-4f5a-b471-08d8b224c32a)

But, when `transparent_background_colors` is set to `true`, the same color becomes different in transparent background and nontransparent foreground breaking this pattern:

![image](https://github.com/alacritty/alacritty/assets/10975197/72f1ee11-88b5-419d-9e9f-86ae3f14c82e)

# Possible solutions

The simplest solution would be just adding some kind of `transparent_foreground_colors` option, but at this point it probably would be better to just set whole window transparency through your DE.

Maybe it's possible to add optional foreground transparency specifically for this separator characters? Here is the [list](https://github.com/ryanoasis/powerline-extra-symbols) of the characters used like this

**Comment by chrisduerr** [comment]
Working as expected.
