### ISSUE TITLE
OSC52 does not copy due to focus

### ISSUE THREAD

**Issue by cfal** [alacritty/alacritty#8032]
Often after yanking text in neovim, I noticed the OSC52 sequence doesn't print in time for me to alt-tab and paste it into another app because of the is_focused check here: https://github.com/alacritty/alacritty/blob/master/alacritty/src/event.rs#L1704
and so the clipboard does not get updated.

This is mainly apparent over ssh where latency is a larger problem and does not occur in other terminals (kitty, iTerm2).

Would it be possible to make this configurable?

### System

OS: Linux
Version: 0.14.0-dev
Linux/BSD: X11/Wayland

**Comment by nixpulvis** [comment]
Before considering an obscure configuration option, I’d be curious how other terminals deal with this issue.
