### ISSUE TITLE
Using in Egui

### ISSUE THREAD

**Issue by ThePerfectComputer** [alacritty/alacritty#8034]
Hello. I'd like to use Alacritty inside a Rust EGUI project. To accomplish this, I'm thinking I'll use a monospace text field in EGUI with text cell changes I get from Alacritty. At a high level, where should I start digging - and what files should I change? I'm thinking that I should start perhaps looking at `src/renderer`?

**Comment by chrisduerr** [comment]
Rendering should be done directly, Alacritty is not suited to be rendered using a third-party text field.

Ultimately it just boils down to writing a frontend for `alacritty_terminal`.

**Comment by ThePerfectComputer** [comment]
Might it be possible to pay somebody working on Alacritty to write such a frontend for EGUI or Rust MoonZoon? Essentially, I want something like http://xtermjs.org but in Rust. That is, you should be able to connect to and render terminal sessions in the web browser.

**Comment by chrisduerr** [comment]
It shouldn't be that difficult with webgpu tbh. Though in the web you don't have PTY access, so that's something you have to handle separately.

**Comment by ThePerfectComputer** [comment]
Yes. I was thinking the backend would forward PTY changes to the frontend. Here is a project I worked on some time ago: https://app.surfer-project.org/?load_url=https://app.surfer-project.org/picorv32.vcd&startup_commands=show_quick_start;module_add%20testbench.top

I'm now writing a new version of that - and I want to be enable shell sessions where you can point to a link to where your PTY gets forwarded.

**Comment by JonasKs** [comment]
Hey @ThePerfectComputer , did you ever figure this out? I wanted to do something similar 😊
