### ISSUE TITLE
Add ability to set `transparent_background_colors` for specific colors

### ISSUE THREAD

**Issue by SimonBrandner** [alacritty/alacritty#8035]
I would like to have a semi-transparent cursor-line in NeoVim but using `transparent_background_colors` makes even things like `lauline` or `powerlevel10k` transparent which I do not like... A possible solution would be to make only specific colors transparent

This would possibly help this: https://github.com/alacritty/alacritty/issues/8031

Would a contribution be welcomed?

**Comment by chrisduerr** [comment]
This will not be added upstream.

**Comment by SimonBrandner** [comment]
May I ask why?
