### ISSUE TITLE
Cursor always blink when using the mouse to locate the cursor in nvim

### ISSUE THREAD

**Issue by epheien** [alacritty/alacritty#8039]
### System

OS: macOS
Version: alacritty 0.12.2 (9d9982d)

As is well known, if you continuously click on the positioning cursor with the mouse in nvim/vim, the cursor blinking will stop.
But in this situation, Alacritty did not stop the flashing of the cursor.

I change cursor => blinking option from Always to On but has no effect.

**Comment by chrisduerr** [comment]
> As is well known, if you continuously click on the positioning cursor with the mouse in nvim/vim, the cursor blinking will stop.

Sorry but what?

**Comment by epheien** [comment]
> > As is well known, if you continuously click on the positioning cursor with the mouse in nvim/vim, the cursor blinking will stop.
> 
> Sorry but what?

This is actually an feature request, but when creating it, only issues can be selected.

The behavior of the other terminals is what I have described, such as iTerm, and I find the difference after switching to Alacritty.

Do you have any plans to implement this feature?

**Comment by chrisduerr** [comment]
What feature are you talking about? I have no clue what you mean.

**Comment by epheien** [comment]
I think I will record a video later to illustrate
