### ISSUE TITLE
Feat req: Allow for custom alternatives to 'yank' on vi mode selection.

### ISSUE THREAD

**Issue by cortsf** [alacritty/alacritty#8040]
In Alacritty's vi mode it's possible to start selecting text with `v` and then yank it with `y`. For many repetitive tasks it would be a huge time saver to be able to bind additional keys to call commands/programs other than "yank", with the selected text as  argument.

Example:
```
`v` then `y` -> yank
`v` then `g` -> search on google
`v` then `f` -> append to some_file
etc
```

Context: Interacting with LLM's on the terminal.

**Comment by chrisduerr** [comment]
Is there a reason why you can't just yank and then read from the clipboard in whatever application you want to interact with that text?

**Comment by chrisduerr** [comment]
Just for reference, this works just fine:

```
  { key = "y", mode = "Vi", action = "CopySelection"  },
  { key = "y", mode = "Vi", action = "ClearSelection" },
  { key = "y", mode = "Vi", command = { program = "sh", args = ["-c", "firefox $(xclip -out)"] } },
```

**Comment by cortsf** [comment]
> Is there a reason why you can't just yank and then read from the clipboard in whatever application you want to interact with that text?

I don't use a mouse and the key sequences (involving worspace switching, opening tabs, input menues, pasting, confirming..) to do so are too long to be used repeteadly all the time. I'll try your approach, thank you.
