### ISSUE TITLE
`fcitx5` not working in alacritty even with an apparently correct `~/.xinitrc`

### ISSUE THREAD

**Issue by aaannestad** [alacritty/alacritty#8044]
I can't seem to get `fcitx5` to work inside alacritty. It works fine in every other program I've tried it in, but it fails to activate in alacritty (or in programs running inside alacritty, like neovim).

### System

OS: Arch
Version: 0.13.2 (bb8ea18e)
X11 / i3

My `~/.xinitrc` is this; as far as I can tell this is entirely correct, and maybe even excessive.

```
#!/bin/bash

export GTK_IM_MODULE="fcitx"
export QT_IM_MODULE="fcitx"
export XMODIFIERS="@im=fcitx"

export INPUT_METHOD="fcitx"
export XIM="fcitx"
export XIM_PROGRAM="fcitx"
export SDL_IM_MODULE="fcitx"

xrdb ~/.Xresources

exec i3
```

What more am I missing here? What does alacritty need that other programs don't?

**Comment by chrisduerr** [comment]
@kchibisov might know.

**Comment by kchibisov** [comment]
You need to ensure that XIM is working and enabled in fcitx itself. Also ensure that when you run alacritty from the terminal you don't see locale errors.

**Comment by aaannestad** [comment]
As I understand, XIM is obsolete at this point, unless I'm misunderstanding what you mean. Should I need to enable it anyway? I'm not sure I understand how to do that, honestly; I see no setting to do that in fcitx's GUI configuration page, and `fcitx5 --enable "XIM"` has no different behaviour than at any other time.

I don't see any locale errors running alacritty from inside itself.

**Comment by kchibisov** [comment]
XIM is how it works in alacritty. I know that when fcitx has XIM it has a setting for it inside the plugins menu IIRC. "X input method" or something, forgot how it's called.

There's always a chance that environment is not properly delivered or activation is not really working, but I don't have X11 with fcitx and can only test it on wayland where it works reliably.

**Comment by aaannestad** [comment]
I do see an 'X Input Method frontend' setting in the plugins menu; I guess that means I have it enabled? 

And that's fair if you don't have any way to test it yourself. Any tips on how to diagnose this? Maybe it's noteworthy that within alacritty eg `echo $GTK_IM_MODULE` returns nothing, which might suggest that those variables aren't getting set somehow for alacritty.

**Comment by kchibisov** [comment]
If variable are not set, I'd suggest to try setting them and running alacritty, maybe it'll start working in the new instance with these set.

**Comment by aaannestad** [comment]
Yep, setting them and then running alacritty works. I guess the issue then is that while most things are using variables exported from my `xinitrc`, alacritty isn't.  If you've got an immediate solution off the top of your head to that, I'd be happy to hear it! Otherwise I can go off and do my own research again.

**Comment by kchibisov** [comment]
Variables are usually inherited from the parent process, so if parent process doesn't have them set it means that alacritty also won't have them set. I personally never set any variables in xinitrc and always relied on setting them in login shell.

Keep in mind that what alacritty launches doesn't really matter, because variables are for alacritty itself and not for anything inside it in this case.

**Comment by kchibisov** [comment]
Seems like works as expected.
