### ISSUE TITLE
Not picking up decorations_theme_variant on startup on macOS

### ISSUE THREAD

**Issue by sfsam** [alacritty/alacritty#8046]
Alacritty is not picking up `decorations_theme_variant = "Dark"` on startup on macOS.
I have to do `touch ~/.config/alacritty/alacritty.toml` to get Dark appearance to take effect.

Startup:
<img width="842" alt="Screenshot 2024-06-16 at 1 14 44 PM" src="https://github.com/alacritty/alacritty/assets/118104/f6c0f3a4-78c0-4e51-8de9-e245a7aa0854">

After `touch ~/.config/alacritty/alacritty.toml`:
<img width="842" alt="Screenshot 2024-06-16 at 1 14 54 PM" src="https://github.com/alacritty/alacritty/assets/118104/f31ee6ab-6ca2-43fc-9bc7-4fd9b8ef5e2e">

### System

OS: macOS Sonoma 14.5 (23F79)
Version: alacritty 0.14.0-dev (0d4ab7bc)

**Comment by chrisduerr** [comment]
@madsmtm Are you aware of any issues like this? We're using `with_theme`, seems like that might have issues?

@sfsam If you're comfortable changing a couple lines of code, I'd be curious if this diff fixes it:

```diff
diff --git a/alacritty/src/display/window.rs b/alacritty/src/display/window.rs
index 09793fa0..341d0faa 100644
--- a/alacritty/src/display/window.rs
+++ b/alacritty/src/display/window.rs
@@ -173,6 +173,7 @@ impl Window {
             .with_fullscreen(config.window.fullscreen());
 
         let window = event_loop.create_window(window_attributes)?;
+        window.set_theme(config.window.theme());
 
         // Text cursor.
         let current_mouse_cursor = CursorIcon::Text;
```

**Comment by kchibisov** [comment]
It's winit issue because it never sets the theme during the window creation with macOS API, it just gets it and stores, but never sets actually.

**Comment by kchibisov** [comment]
That's probably why I wasn't able to notice it, because I use the system's theme and not light theme with just dark for alacritty.

**Comment by sfsam** [comment]
@chrisduerr Yes, your patch seems to fix it.

**Comment by kchibisov** [comment]
Why on earth github closed an issue cross repository orgs!!! This is so...........

**Comment by nixpulvis** [comment]
I was wondering the same thing when I saw it… sadly GitHub doesn’t understand dependency management of our app.

**Comment by kchibisov** [comment]
The problem is that I closed the issue by merging PR in winit, which is under completely different org, and it did so only because I'm owner in both repos. When I was not owner it was not doing so IIRC.
