### ISSUE TITLE
Additional dependency for building Alacritty on Debian/Ubuntu

### ISSUE THREAD

**Issue by ATOMICMAN007** [alacritty/alacritty#8048]
### System

**OS:** Ubuntu 22.04 (Docker image)

**Description:**
I encountered a missing dependency while building Alacritty on an Ubuntu Jammy 22.04 Docker container. The instructions in the repository's [Debian/Ubuntu](https://github.com/alacritty/alacritty/blob/master/INSTALL.md#debianubuntu) section do not include at least one necessary dependency.

The build instructions do not mention that `c++`/`g++` is required to build Alacritty. Without these packages, the build process fails. It might be the case that `freetype-sys` requires `g++` to be installed, this can be seen in the logs I have pasted below.

**Solution:**
To resolve this issue, I installed `build-essential` using `apt`, which includes `g++`. This allowed me to successfully build Alacritty. I then copied the binary to my host machine, and it runs without issues.

**Steps to Reproduce:**
1. Use an Ubuntu 22.04 Docker image or a similarly minimal installation.
2. Follow the build instructions provided in the Alacritty repository under the Debian/Ubuntu section.
3. Attempt to build Alacritty.
4. Observe the build failure due to missing `c++`/`g++` packages.

**Proposed Fix:**
Since `build-essential` includes many other packages in addition to `g++`, I suggest further investigation to identify the minimal set of packages required. I am ready to assist by testing on a fresh Ubuntu image where only `g++` is installed, excluding `build-essential`.

It is important to note that the Ubuntu Docker image is very minimal and does not include many packages that might be present in non-Docker installations. This can lead to missing dependencies that are otherwise installed by default on a typical Ubuntu installation. This allows us to better identify the dependencies since we have to manually install each dependency.

### Logs

```log
The following warnings were emitted during compilation:

warning: freetype-sys@0.20.1: Failed to run: "c++" "--version"

error: failed to run custom build command for `freetype-sys v0.20.1`

Caused by:
  process didn't exit successfully: `/home/ubuntu/alacritty/target/release/build/freetype-sys-6e3b15ad360257c2/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=FREETYPE2_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=FREETYPE2_STATIC
  cargo:rerun-if-env-changed=FREETYPE2_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  TARGET = Some("x86_64-unknown-linux-gnu")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CXX_x86_64-unknown-linux-gnu
  CXX_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CXX_x86_64_unknown_linux_gnu
  CXX_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CXX
  HOST_CXX = None
  cargo:rerun-if-env-changed=CXX
  CXX = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:warning=Failed to run: "c++" "--version"
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64-unknown-linux-gnu
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CXXFLAGS_x86_64_unknown_linux_gnu
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CXXFLAGS
  HOST_CXXFLAGS = None
  cargo:rerun-if-env-changed=CXXFLAGS
  CXXFLAGS = None

  --- stderr


  error occurred: Failed to find tool. Is `c++` installed?


warning: build failed, waiting for other jobs to finish...
```

**Comment by chrisduerr** [comment]
If you know about a missing package not mentioned in the install instructions, please feel free to send a PR to add it.

**Comment by kchibisov** [comment]
I mean, rust needs a linker in form of a C compiler, so if you have rust and not C compiler it'll certainly fail.
