### ISSUE TITLE
`scripts/install-linux.sh`

### ISSUE THREAD

**Issue by jarkkojs** [alacritty/alacritty#8051]
This would be a great convenience when trying out the main branch.

**Comment by JasonGantner** [comment]
@jarkkojs out of curiosity (I'm not a maintainer) what distribution are you using and what is your build process like ?
In my experience, the .desktop and .SVG files need to be installed only once and two calls to cargo take care of refreshing the binaries installed.

IIRC Arch has a pkgbuild to automate the process while Gentoo has a live ebuild.

**Comment by jarkkojs** [comment]
> @jarkkojs out of curiosity (I'm not a maintainer) what distribution are you using and what is your build process like ? In my experience, the .desktop and .SVG files need to be installed only once and two calls to cargo take care of refreshing the binaries installed.
> 
> IIRC Arch has a pkgbuild to automate the process while Gentoo has a live ebuild.

I'm using Fedora 40.

I created own repository for it, and improved it a bit, it installs now by default to `~/local` and does not require a clone of alacritty repository.

I.e. 

```
❯ find ~/.local -iname "Alacritty*"
/home/jarkko/.local/share/applications/Alacritty.desktop
/home/jarkko/.local/share/pixmaps/Alacritty.svg
/home/jarkko/.local/bin/alacritty
```

I can now launch alacritty without issues in GNOME's menu system. Icon is not visible tho (have neither logged out in-between). So yeah, I get what I want now easily so I'm good :-)

The new script does a clone to tmp and builds from there: https://codeberg.org/jarkko/alacritty-install/src/branch/main/alacritty-install

**Comment by jarkkojs** [comment]
Now it is not trashing rootfs, and since everything a big fat ELF with Rust packaging system is IMHO just an extra layer of complexity in your main apps (like terminal is for me). Now I can always get the latest main.

**Comment by JasonGantner** [comment]
I don't know the details of arch's pkgbuild/AUR system, but Gentoo's ebuilds integrate easily with many build systems (including cargo and cmake) which enables unified dependency management and makes adding new(/custom) packages generally easier than creating a full build script among other benefits.

On the cargo side, you could use `cargo install --git $REPO_URI --branch master --root "$HOME/.local" $REST_OF_YOUR_BUILD_ARGS` or even set `install.root` in your `config.toml` to achieve roughly the same result.

As for the possibility of reusing already compiled dependencies, the cargo docs recommends using `sccache` : https://doc.rust-lang.org/cargo/guide/build-cache.html

**Comment by jarkkojs** [comment]
Well, my script will install the main branch under local, agnostic to the distribution :-) I consider this more robust than fighting with Gentoo shenanigans.

**Comment by jarkkojs** [comment]
> I don't know the details of arch's pkgbuild/AUR system, but Gentoo's ebuilds integrate easily with many build systems (including cargo and cmake) which enables unified dependency management and makes adding new(/custom) packages generally easier than creating a full build script among other benefits.
> 
> On the cargo side, you could use `cargo install --git $REPO_URI --branch master --root "$HOME/.local" $REST_OF_YOUR_BUILD_ARGS` or even set `install.root` in your `config.toml` to achieve roughly the same result.
> 
> As for the possibility of reusing already compiled dependencies, the cargo docs recommends using `sccache` : https://doc.rust-lang.org/cargo/guide/build-cache.html

If you think about it and how Rust binaries are constructed, ELF executable is a package. It has everything built into a single binary. So any packaging system on top of that, including Gentoo's, is just an extra layer of nothing really.

Except resources for icon and desktop entry maybe.

**Comment by JasonGantner** [comment]
> Well, my script will install the main branch under local, agnostic to the distribution :-) I consider this more robust than fighting with Gentoo shenanigans.

Yeah, I would recommend switching to Gentoo for the sake of sparing one build script, that'd be net negative 😆

> If you think about it and how Rust binaries are constructed, ELF executable is a package.

It's an archive rather than a package, but that's beside the point 

> So any packaging system on top of that, including Gentoo's, is just an extra layer of nothing really.

Packaging systems are there to provide unified and reproducible builds as well a distribution mechanism for binaries and/or sources. That's what cargo does for Rust and yes OS-level packaging system and language-level packaging system are redondant but there's no clear one-for-all solution (yet?).

My previous reply wasn't to push for one packaging system or an other, just suggesting that there might be existing solutions that would provided a simpler framework than starting from scratch with a shell script. Upon further reading, it seems that fedora only provides fedpkg (a wrapper around rpmbuild) and koji (a heavy client-server build system). I assume both can be disqualified for this use case.

> That said, thanks for showing me some extra options for cargo that I was unaware of :-) Appreciate it.

My pleasure.
