### ISSUE TITLE
opacity doesnt work 

### ISSUE THREAD

**Issue by Filip-Nachov** [alacritty/alacritty#8054]
I am doing my config and I do the 
```
window:
    opacity: 0.8
```
but it doesnt change anything 

### System

OS: Arch Linux
Version:  0.13.2
Linux/BSD: i3wm

**Comment by chrisduerr** [comment]
Are you running a compositor? Is this inside a VM?

**Comment by Filip-Nachov** [comment]
Virtual Machine? no its a desktop and for everyone its seems that this works not for me tho

**Comment by chrisduerr** [comment]
i3 by itself does not support transparency. If you're not running a compositor, then transparency shouldn't work.
