### ISSUE TITLE
thin font rendering option on macOS Sonoma 

### ISSUE THREAD

**Issue by ciscohack** [alacritty/alacritty#8059]
Hi Team,

I am looking for an old thin font setting for macOS Sonoma. I checked the community and other are a lot of system-level command changes suggested but those are for old macOS versions. don't know how much they are relevant now but I want only thin font for alacrity.

**Comment by chrisduerr** [comment]
There are some CLI options available, but if you want a thinner font, just install one.

**Comment by ciscohack** [comment]
@chrisduerr Sorry to say but I don't like the solution if you can implement the feature say .. we will not do but suggesting to use thin font is not good.. I also know, to use the thin font as an option.. but the font I like doesn't have a thin typeface and all terminal apps have this basic feature except Alacritty. and CLI commands I don't want system level change or some command I tried and was not working but why we do not have this basic feature as the native feature was an ask... Any thanks for the suggestion once again.
