### ISSUE TITLE
Bug: backward search on single line goes in cycles

### ISSUE THREAD

**Issue by hissssst** [alacritty/alacritty#8060]
When using backward search, it sometimes goes in cycles without moving a cursor to some search result. In example video, before resizing, everything works fine, but after resizing, it cycles only on several last elements on the line, instead of cycling through all occurrences

https://github.com/alacritty/alacritty/assets/37012324/34cbb259-9d3d-4de5-83df-f92ca66735ba

### System

OS: Linux, Wayland, Sway
Version: alacritty 0.13.2

### Logs

No logs

**Comment by chrisduerr** [comment]
The provided video cannot be played back.

**Comment by hissssst** [comment]
@chrisduerr , I can play it back. Do you use firefox? If so, it is a known bug

**Comment by hissssst** [comment]
Even without video, try to create a long line with like 30 or 40 entries of the same word and try backward-searching it. Search will break

**Comment by chrisduerr** [comment]
Should be fixed by #8069 as far as I can tell. Let me know if your bug is something different.

**Comment by hissssst** [comment]
I've tried backward-search on master and it was working as expected. Bug is fixed. Great job!

**Comment by chrisduerr** [comment]
> I've tried backward-search on master and it was working as expected. Bug is fixed. Great job!

But I didn't even merge the PR yet…

**Comment by hissssst** [comment]
Oh, sorry, I wanted to say on your branch instead of master
