### ISSUE TITLE
Alacritty on macOS is not respecting modifier key hierarchy when multiple modifiers are used

### ISSUE THREAD

**Issue by agebhardtsbauer** [alacritty/alacritty#8061]
Generally speaking across systems and applications it is the case that when we hold down multiple modifier keys + a key stroke it takes precedence over fewer modifier keys + the same keystroke.

Example: (cmd ctrl shift + 4) > (cmd shift + 4) > (shift + 4) > (4)

I think it's fairly obvious why this should be the case

Now... the interesting thing about this interaction is what happens when a stroke that is higher has *nothing* bound to it, the *nothing* stroke still win and therefore nothing happens.

This appears to not be the case in Alacritty current version... at least on my machine

On my OS I have several application launches bound to <hyper> + letter (e.g: cmd shift ctrl opt s = launch Safari)

When I have Alacritty active it consumes this stroke and decides to instead run Alacritty's local keybind ("ctrl + s" = fwd-i-search) or in the case of <hyper> + c for chrome Alacritty instead consumes the stroke and clears the prompt instead (ctrl c)

Anyway... this seems like bad behavior and it certainly prevents my preferred workflows.

--Summary--
Expected behavior 1: Alacritty should do nothing when, for example, (cmd ctrl + s) is pressed
Current behavior: Alacritty opens a search prompt when (cmd ctrl + s) is pressed

Expected behavior 2: Alacritty should defer to OS instructions when it has nothing bound to the modified stroke
Current behavior: Alacritty consumes the keystroke

Thanks

### System

OS: macOS 14.5 (23F79)
Version:  alacritty 0.13.2 (bb8ea18)

### Logs

none produced, none required

**Comment by chrisduerr** [comment]
If you have questions related to specific configuration files, please attach your configuration file.

**Comment by agebhardtsbauer** [comment]
@chrisduerr trying to understand what you're getting at here. I have simply brew installed Alacritty only moments before I noticed the described behavior, so whatever config I have it's certainly default.

Do you still want me to attach it?

**Comment by chrisduerr** [comment]
If you're not talking about Alacritty's config bindings, but instead about some terminal bindings, then this is not an issue.

**Comment by agebhardtsbauer** [comment]
@chrisduerr 

Perhaps my explanation was not clear enough

Alactritty is **consuming** OS level bindings, meaning OS key bindings simply do not work while Alacritty is active window.

**Comment by nixpulvis** [comment]
Seems odd. Alacritty shouldn't be able to see events that were consumed before they reach the event loop, no? For example, on macOS I open a new alacritty window with `--print-events` and I press Command+Space with that window in focus. Alacritty sees the Command keydown, but then doesn't see the space, since it is consumed by the system for spotlight search, then it sees the Command up.
