### ISSUE TITLE
"_glapi_add_dispatch" OpenGL function error when launching an OpenGL app inside alacritty but not inside stock Gnome terminal.

### ISSUE THREAD

**Issue by LituDev** [alacritty/alacritty#8064]
### System

OS: Linux / Debian 12
Version: alacritty 0.13.2 (bb8ea18e)
Linux/BSD: Wayland
I installed it using snap

When i try to launch a simple OpenGL app, it seems like it has issues calling the "_glapi_add_dispatch" function. Here is the code i used. When i use the stock Gnome terminal to run the program, there are no issues.
```c
#include <stdio.h>
#include <stdlib.h>
#include <GL/glut.h>

void display() {
    glClear(GL_COLOR_BUFFER_BIT);
    glFlush();
}

int main(int argc, char** argv) {
    printf("Starting main\n");

    glutInit(&argc, argv);
    printf("GLUT initialized\n");

    glutInitDisplayMode(GLUT_SINGLE | GLUT_RGB);
    printf("Display mode initialized\n");

    glutInitWindowSize(250, 250);
    printf("Window size set\n");

    glutInitWindowPosition(100, 100);
    printf("Window position set\n");

    int windowId = glutCreateWindow("Minimal GLUT Example");
    if (windowId <= 0) {
        fprintf(stderr, "Failed to create GLUT window\n");
        return 1;
    }
    printf("Window created\n");

    // Set the display function
    glutDisplayFunc(display);
    printf("Display function set\n");

    // Set the clear color to black (optional)
    glClearColor(0.0, 0.0, 0.0, 0.0);

    printf("Entering main loop\n");
    glutMainLoop();

    return 0;
}
```

It seems it has trouble opening a window. Did i enable something is the settings i shouldn't have enabled ? 

Thanks for your time !

**Comment by kchibisov** [comment]
Ensure that the `env` is the same, but it's not alacritty issue.

Maybe one tries to run on X and other on Wayland.

**Comment by kchibisov** [comment]
Ah,

>I installed it using snap

This is your issue, don't use snap.

**Comment by LituDev** [comment]
Hey, 
Alr, i will add the repo directly, thanks for your time !
cheers.
