### ISSUE TITLE
Alacritty crashes when leaving the current tty

### ISSUE THREAD

**Issue by titaniumtraveler** [alacritty/alacritty#8065]
# System

OS: Linux 6.9.5-arch1-1 on arch linux
Version: alacritty 0.13.2 (bb8ea18e)
Linux: Hyprland 0.41.1-1

# Logs

[stdout.txt](https://github.com/user-attachments/files/15983630/stdout.txt)

## Stderr

```
thread 'main' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/wayland/seat/keyboard/mod.rs:269:73:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

# Error Description

When leaving the current tty, alacritty crashes with the above described panic.
Orginally I noticed this crash when using my screenlocker ([`physlock`](https://archlinux.org/packages/extra/x86_64/physlock/)),
but the same crash happens when leaving the tty using using `ctrl + alt + F2`.

## Expected Behavior

Leaving the tty should not crash alacritty.
(And it used to not do that.)

**Comment by chrisduerr** [comment]
@kchibisov Seems like the Wayland backend is just unwrapping on the keyboard state?
https://github.com/rust-windowing/winit/blob/v0.29.15/src/platform_impl/linux/wayland/seat/keyboard/mod.rs#L269

**Comment by kchibisov** [comment]
It really looks like a compositor bug to me? Why we have events for keyboard without any keyboard? This doesn't make any sense, and given that it's a _hyprland_ I'd just straight close the issue.

**Comment by kchibisov** [comment]
You can provide `WAYLAND_DEBUG=1` log and I may look into it, but without it I say that it's a hyprland bug, since the code is like that for a very long time.

**Comment by titaniumtraveler** [comment]
> It really looks like a compositor bug to me? Why we have events for keyboard without any keyboard? This doesn't make any sense, and given that it's a hyprland I'd just straight close the issue.

Yeah, seems like it. The problem has just gone away after restarting it. (I'm pretty sure I had a hyprland update in the mean time.)
No other program had crashed that's why I was confused.
Still thanks for the help :slightly_smiling_face:.

**Comment by FelixBrakel** [comment]
Could this be an nvidia driver issue? I have the exact same problem and it started popping up around the time I updated to 555.

I have pretty much the same system setup as OP.

OS: 6.9.7.arch1-1
alacritty: 0.13.2-2
hyprland: 0.41.2-1
nvidia-dkms: 555.58-2

**Comment by titaniumtraveler** [comment]
> Could this be an nvidia driver issue? I have the exact same problem and it started popping up around the time I updated to 555.
I don't think so? At least not the original problem I had. (I have an integrated intel gpu.)

Also now that I'm on hyprland 0.41.2-1, I haven't had any problems anymore.

@FelixBrakel Can you consistently crash alacritty? As in every single time?

And could you check `hyprctl version`? Just to make sure you don't updated your arch, but didn't restart Hyprlang, leading to the actual version used being older.

**Comment by FelixBrakel** [comment]
Yes it crashes every time I switch to a different tty.
I'm at commit 918d8340afd652b011b937d29d5eea0be08467f5

**Comment by kchibisov** [comment]
I'd suggest to try either sway or latest hyprland commit.

**Comment by kchibisov** [comment]
I'll add a workaround for that crash, but the thing is that it's a hyprland bug, which likely appeared once they ditched wlroots, since it's clearly a _new thing_ here. Though, they do send events out of order, for dead objects, etc, in other cases now.
