### ISSUE TITLE
clear and reset the screen

### ISSUE THREAD

**Issue by electriquo** [alacritty/alacritty#8074]
There are issues related to this:

- https://github.com/alacritty/alacritty/pull/4152#issuecomment-677782181
- https://github.com/alacritty/alacritty/issues/4199#issuecomment-685393323
- https://github.com/alacritty/alacritty/pull/4494
- https://github.com/alacritty/alacritty/issues/3997
- https://github.com/alacritty/alacritty/issues/7750
- https://github.com/alacritty/alacritty/issues/7216

Alacritty has a support for clearing and resetting the screen only when the terminal prompt has no input. Rather than reverting to iTerm2 (or any other terminal emulators that support this), I would like to add a key binding to Alacritty that will clear and reset (the buffer) screen even whenever the key binding is pressed. That is, during executing command (`tail -f`), any typing where made on the terminal prompt, etc.

I raise this issue again to get insights and lead from Alacritty community for all to benefit before turning to a different terminal emulator.

**Comment by kchibisov** [comment]
It was pretty clearly explained numerous times that desyncing with underlying applications is clearly not a great idea.

**Comment by shaquibimdad** [comment]
@kchibisov I am running shopify cli and i clear and reset terminal for new logs why it is such a bad idea if user is manually enabling it?

**Comment by meagar** [comment]
It's crazy that Alacritty lacks this feature, which is present in every other terminal emulator. It's not a hack, it's a necessary feature that a huge number of people depend on.

When I'm in a terminal, tailing a log file, I need this feature. The use case is stunningly straight-forward. Assume I am tailing the log file of Rails application. The log is completely static between requests, and when a new request comes in, many lines of log output are generated, and they are all generated during the process of that one request, after which the logs are silent again.

I _need_ to be able to do the following:

* Clear the terminal window, and the whole scrollback buffer
* Trigger a new request in my browser to the Rails application
* Know that, in the terminal, I can scroll to the very top of the scrollback buffer and the first character of text will be where I can start reading to trace through the log output for the request Rails just handled

I don't care if this can leave some apps in an inconsistent state. Every other terminal emulator does this, including ITerm2, which I am _trying_ to abandon in favor of Alacritty. Yes, sometimes I accidentally `cmd+K` when I'm in vim, and the screen goes weird. I recover, trivially, every time. I can live with this rough edge, but I can't live without this feature.

**Comment by nixpulvis** [comment]
I remain strongly in favor of adding this as well, and I'm still somewhat frustrated myself.
