### ISSUE TITLE
Big size after startup allacritty

### ISSUE THREAD

**Issue by Y4zidd** [alacritty/alacritty#8075]
![fix](https://github.com/alacritty/alacritty/assets/110552013/5982b1c4-28ff-4738-b717-fd86ee3c4ea3)

Help me, Every time I open Allacritty he always has a big shape like that

my log

[Alacritty-5422.log](https://github.com/user-attachments/files/16110357/Alacritty-5422.log)

**Comment by kchibisov** [comment]
Put `WINIT_X11_SCALE_FACTOR = "1"` before running alacritty or in alacritty's config.

Or set dpi in `Xft.dpi`.
