### ISSUE TITLE
MySQL Console Command Input Truncated with MesloLGS Nerd Font Mono

### ISSUE THREAD

**Issue by Amr-Shams** [alacritty/alacritty#8076]
When using the MesloLGS Nerd Font Mono in the terminal, commands typed into the MySQL console are truncated upon execution. This causes only a part of the command to be recognized and executed by the console. For example, typing `show databases;` results in the command `show da` being executed instead. when I try another emulator it works just fine

### System

Operating System: macOS Intel
Terminal Emulator: Alacritty
Font: MesloLGS Nerd Font Mono

**Comment by chrisduerr** [comment]
Impossible to be related to the font and likely an issue with mysql console.
