### ISSUE TITLE
Weird font rendering artifacts at low window opacity

### ISSUE THREAD

**Issue by imsuck** [alacritty/alacritty#8080]
### System

OS: Linux endeavouros 6.9.7-zen1-1-zen x86_64 GNU/Linux
Version: alacritty 0.13.2 (bb8ea18e)
Linux/BSD: X11, i3, picom

### Logs

Crashes: None.
Font/Terminal size: Affects all font, more noticable at higher font sizes and/or lower window opacity.
Keyboard and bindings: Irrelevant.

### Behaviour
At 0.5 opacity the characters appears to be fine for the most part.
![image](https://github.com/alacritty/alacritty/assets/49095435/2f091316-8d57-4348-ac6a-22c01a6bcb36)
At 0.0 opacity the color channels seem to be shifted.
![image](https://github.com/alacritty/alacritty/assets/49095435/3d8b060c-0d9c-48e5-af94-868d8e9a50ed)

**Comment by chrisduerr** [comment]
Just looks like subpixel RGB. I don't think there is any issue.

**Comment by kchibisov** [comment]
if you switch to _grayscale_ AA it'll look way better for transparent windows though.
