### ISSUE TITLE
Server mode

### ISSUE THREAD

**Issue by diniamo** [alacritty/alacritty#8081]
A server-client way of using alacritty is already available with `alacritty msg create-window` command (I'm not actually sure how much is shared between the windows, but it works as a workaround for the nvidia slow startup bug for me). The problem is that it requires an instance of alacritty to be running, which can only be the case if a window also exists.

I'm asking for a way to create a background process of alacritty, that can server this purpose without a window.

**Comment by diniamo** [comment]
Could you link the original issue in that case? I couldn't find it.

**Comment by diniamo** [comment]
@chrisduerr

**Comment by Packjackisback** [comment]
😭 thanks a lot @chrisduerr
