### ISSUE TITLE
Text readability when foreground and background colour are the same

### ISSUE THREAD

**Issue by sabrehagen** [alacritty/alacritty#8082]
When the foreground colour and background colour of a character are the same, the character will be unreadable as the two colours match, making the character block all one colour.

When viewing a git diff in vs-code's inbuilt terminal, when the forefround and background colours have been configured to be the same, vs-code's terminal will automatically change the text foreground colour to a dark colour when the background colour is the same, so that the characters are readable. See below screenshot for example:

![image](https://github.com/alacritty/alacritty/assets/1094600/59d696de-d151-43da-95f5-58f46ea7664e)

By comparison, alacritty renders characters with the same foreground and background colour as instructed, with both foreground and background colour being the same, thus making the character block all one colour and the text unreadable.

![image](https://github.com/alacritty/alacritty/assets/1094600/620a9383-2ee6-45a7-8fe7-b13edbca1021)

Is there a setting in alacritty that handles this case where character foreground and background colour are the same, and darkens the foreground colour to produce readable text, as per the vs-code terminal functionality?

### System

OS: Linux
Version: `alacritty 0.13.0-dev (244fd6b)`
Linux/BSD: X11 i3

**Comment by kchibisov** [comment]
But why would you configure it like that though? I'd suggest to use selection for that to show them, but if the colors match it seems like _intended behavior_ from the application point of view, so not sure why break it.

**Comment by sabrehagen** [comment]
>But why would you configure it like that though?

Did you understand scenario where this occurs in the git diff example?

Would you accept a pull request to support the same functionality as vs-code terminal?

**Comment by kchibisov** [comment]
I mean I've never seen it in a `git diff` myself, there's a functionality to invert when during selection the cells are detected to be _hidden_ for general case, as I said, it could be _intended by application_, so don't see why we should change anything about it.

**Comment by chrisduerr** [comment]
Yeah not only is the git diff example nonsense, it might also very well be a feature applications rely on.
