### ISSUE TITLE
Following instructions from INSTALL.MD alacritty 0.14.0-dev is installed 

### ISSUE THREAD

**Issue by MKitovnica** [alacritty/alacritty#8086]
On Pop OS when I follow the instructions provided  alacritty 0.14.0-dev is installed instead of 0.13.2

sudo curl https://sh.rustup.rs -sSf | sh

install dependencies using apt on Fedora followed the instructions for dependencies. 

git clone https://github.com/alacritty/alacritty.git

cargo build --release

What is the issue here? I have tested this on Pop and Fedora with the same results.

**Comment by chrisduerr** [comment]
Working as intended.
