### ISSUE TITLE
Config option for "setting the color to display underlined characters when the foreground color is the default", as done in xterm and urxvt

### ISSUE THREAD

**Issue by lmutt** [alacritty/alacritty#8088]
I'm trying to migrate my xterm and (u)rxvt configs (from .Xresources file) to Alacritty and I miss the equivalent to `URxvt*colorUL` or `XTerm*colorUL` option in Alacritty.

This options change the foreground color when text are underlined AND foreground color is the default. I found it useful for displaying man pages (see figure below). A something related option exists in Alacritty for making bold text show in different color (`draw_bold_text_with_bright_colors` option together with `bright_foreground`), which acts like the urxvt/xterm `colorBD` option.

For reference, the following excerpts from xterm and urxvt man pages describe this option:

`man urxvt`:
```
       colorUL: colour
           Use the specified colour to display underlined  characters  when  the  foreground  colour  is  the
           default.
```

`man xterm`:
```
       colorUL (class ColorUL)
               This specifies the color to use to display underlined characters if the “colorULMode” resource
               is enabled.  The default is “XtDefaultForeground”.

               See also the veryBoldColors resource which allows combining underline and color.

       colorULMode (class ColorAttrMode)
               Specifies  whether  characters with the underline attribute should be displayed in color or as
               underlined characters.  Note  that  setting  colorMode  off  disables  all  colors,  including
               underlining.  The default is “false”.
```

**FIGURE:** Screenshot for urxvt (left) and Alacritty (right) using (almost) the same configuration. Only the `colorUL` setting from xterm/urxvt is missing in Alacritty.

![image](https://github.com/user-attachments/assets/9c92cc07-9f1b-4056-9379-0e9784eebe56)

**Comment by lmutt** [comment]
@chrisduerr why 'wontfix' ?

I for a moment thought I was lucky that this issue was numbered #[8088](https://en.wikipedia.org/wiki/Intel_8088)  :|

**Comment by chrisduerr** [comment]
It's a pointless feature. Your entire suggestion hinges on wanting to change the way a program looks, when its looks can be freely configured.

**Comment by lmutt** [comment]
> It's a pointless feature.
For you. but... wait... you're the one in charge here! who am I?

> Your entire suggestion hinges on wanting to change the way a program looks, when its looks can be freely configured.
If you think the example I gave is useless, just consider the title of this issue. My request is to implement a functionality (pointless in your opinion) that exists in a terminal emulator that is perhaps not irrelevant (have you heard of xterm?).

**Comment by kchibisov** [comment]
Not every feature should be implemented... The point the other option exists because a lot of software relies on it due to historical reasons, which are not even related to xterm, and as for underline it's unlikely the case.

In general, you're free to configure your man pager to highlight things the way you want it to. If it's less it has `LESS_TERMCAP_*` options.
