### ISSUE TITLE
xdg-terminal-exec support

### ISSUE THREAD

**Issue by ManuelSchneid3r** [alacritty/alacritty#8089]
Running a command in a terminal from another app is a common usecase. Almost all terminals provide such a command execution interface (`-e`, `-x`, `--` or such). Clients can [guess](https://github.com/albertlauncher/albert/blob/6783257df7e15dcfbae49d03023414b7c3692dbd/src/app/terminalprovider.cpp#L120-L150), but they cant know it for sure. If it *can* break, it *will* break.

There is a [freedesktop spec proposal](https://gitlab.freedesktop.org/terminal-wg/specifications/-/merge_requests/3) that tries to standardize the way we configure a default terminal for command execution. It implicitly solves the above problem. Its as simple as that: the app/package provides this info.

To support it you simply need to add `X-ExecArgs` or `ExecArgs` ([the reference implementation respects both](https://github.com/Vladimir-csp/xdg-terminal-exec/blob/af3570e1af8691416e77171e7e29a03572d541c4/xdg-terminal-exec#L387)) to the desktop file ([like this](https://github.com/GNOME/gnome-terminal/blob/f1814cb7ecfe6a5cb4f629dcea56db0dec10a242/data/org.gnome.Terminal.desktop.in#L14)) and make sure there is `TerminalEmulator` in `Categories`. It has not yet been approved (therefore the `X-`) but hey `ExecArgs` does not conflict any standard key and if it will be approved you dont have to change it again.

As an elaborative example see how GNOME terminal does it: https://github.com/GNOME/gnome-terminal/commit/f1814cb7ecfe6a5cb4f629dcea56db0dec10a242

This will help making Linux a better user experience and a less annoying developer experience.

Thank you

PS:
The draft states that the default will be `-e` and you might think "okay, done" if your ExecArg *is* `-e`. I recommend to add it anyway because then you are on the safe side if the final spec does not fall back to `-e`. I guess (hope) there will be no default. 
You might also think "Why that early if it's a draft?". Correct, but if you do so, I will give you a grateful hug should we ever meet in real life because I am the maintainer of that frustrating list linked in the beginning. If you do so I can wipe your entry from the list :heart:. Also this proposal is a good thing and we should all push it.

**Comment by kchibisov** [comment]
Do they plan it add that to e.g. default gnome shell launcher, etc? In general I don't really mind adding this information to desktop file, since it generally doesn't break anything.

**Comment by kchibisov** [comment]
I've also seen people linking the intents spec, but it seems like it's all dbus based and the xdg terminal exec is far more simple to gain wider adoption from the terminals out there, given that the only change required is to patch a desktop file, so you can even handle some really old terms, while with intents you have to implement dbus interfaces.

The sandbox argument is not that great because terminals should generally not be sandboxed (at least in a way flatpak does so right now where you can run basically anything in it without any restriction).

I wonder if some DE has support for x-t-e spec though, I'd assume gnome has it?

**Comment by ManuelSchneid3r** [comment]
Well I got [stopped](https://gitlab.gnome.org/raggesilver/blackbox/-/issues/388) abruptly by the maintainer of GNOME terminal. Now that I know that there is a related [intentapp draft](https://gitlab.freedesktop.org/xdg/xdg-specs/-/merge_requests/45) and a [terminal intent](https://gitlab.freedesktop.org/xdg/xdg-specs/-/merge_requests/46) I'll have to get an opinion before starting discussions. I guess in the end I will be on your side though. Id rather prefer to be able to cover them all.

**Comment by chrisduerr** [comment]
Generally I don't see a reason why terminal emulators would need to standardize on this.

The "spec proposal" is also just a random suggestion from 5 years ago, which doesn't hold much value. It has absolutely **nothing** to do with freedesktop.

**Comment by ManuelSchneid3r** [comment]
> Generally I don't see a reason why terminal emulators would need to standardize on this.

ofc having terminal defaults is a good thing. file managers, ides, launchers open terminals. as a user I want to be able to tell nautilus to use alacritty instead of gnome terminal.

**Comment by kchibisov** [comment]
I think right now it's a bit of a mess, though, probably the `TERMINAL` env variable works.

The thing is that they probably just route everything via dbus in the end...

**Comment by chrisduerr** [comment]
> The thing is that they probably just route everything via dbus in the end...

Which is something that certainly isn't going to be added to Alacritty.

**Comment by ManuelSchneid3r** [comment]
I am on the XTE side. Please add `X-ExecArg`.

**Comment by ManuelSchneid3r** [comment]
@chrisduerr why?
