### ISSUE TITLE
Can I get Myanmar Unicode Fonts display correctly?

### ISSUE THREAD

**Issue by minsoehan** [alacritty/alacritty#8096]
### System

OS: Arch Linux
Version: `alacritty --version` output @ alacritty 0.13.2 (bb8ea18e)
Linux/BSD:  Wayland, Window Manager (dwl, sway, hyprland, etc.)

I am trying to get Myanmar Unicode Fonts (padauk, pyidaungsu, etc.) displays correctly in linux terminals including alacritty. They are appearing incorrectly like below;
![image](https://github.com/user-attachments/assets/7b988eb2-9170-4667-aa4e-3618f04669e8)
The correct way supposed to display is like below;
![image](https://github.com/user-attachments/assets/3f60e7aa-57fc-4838-a988-2fc6e78cd247)
The software displaying Myanmar Unicode Fonts correctly is mousepad.

Actually, I tested it with many linux terminal like gnome-terminal, foot, xfce4-terimnal and so on. No one display them correctly. Please help if it is possible.

**Comment by kchibisov** [comment]
See #50. Shaping is not yet supported.
