### ISSUE TITLE
Feature request: Case insensitive search

### ISSUE THREAD

**Issue by electriquo** [alacritty/alacritty#8100]
Would be happy to see case insensitive search (cmd+f).

### System

OS: macOS
Version: alacritty 0.13.2 (bb8ea18)

**Comment by kchibisov** [comment]
it's _smartcase_, like in vim, so unless you have capital letter it's case insensitive.

**Comment by kchibisov** [comment]
Just type without capital letters and it's case insensitive. 

![image](https://github.com/user-attachments/assets/223fdb18-37b9-4f11-b22c-6b1714c04ab8)
