### ISSUE TITLE
No apparent way to sponsor the project

### ISSUE THREAD

**Issue by arogge** [alacritty/alacritty#8103]
## Story
As a daily user of alacritty it is my burning desire to keep the project alive. An easy way to sponsor the project should be provided.

## Acceptance criteria
* end-user can send a one-time donation
* end-user can setup a recurring sponsorship

## Reasoning
I love alacritty, it is by far the best terminal emulator I have ever used. My day to day workflow relies on it (there are alternatives, but who'd want to use one of these?). As a result I consider alacritty a critical part of my personal infrastructure and would like to sponsor the project with a few dollars per month.

I do realize that
* this is a duplicate of #4370 
* getting sponsors is not one of your goals
* you don't need any money
* a few bucks won't fix any problem anyway
 
Nevertheless, I hope you changed your mind in the past four years and won't say "no" to a user-funded coffee/beer/pizza now and then.

**Comment by kchibisov** [comment]
Alacritty doesn't need any direct sponsoring and it'll create more issues than it'll solve. Individual developers/contributors may have their own ways to sponsor them given that they tend to work on more stuff than just alacritty.

Though, they tend to work on stuff they want themselves most of the time.
