### ISSUE TITLE
Blurry cursor in GNOME wayland

### ISSUE THREAD

**Issue by Detoxify92** [alacritty/alacritty#8105]
Hi,
The cursor is blurry only when it is over the alacritty window (although fonts are crisp). I have not seen this issue in any other app, XWayland or not. I have a 2880x1800 display, with 200% scale factor. Here is a screenshot that illustrates the issue:

![image](https://github.com/user-attachments/assets/379331c5-c61f-459e-8424-b09516cc1510)

Thanks in advance and let me know if I can provide any more info.

### System

OS: Linux
Version: alacritty 0.13.2 (bb8ea18e)
Linux: Wayland, GNOME

### Logs
WAYLAND_DEBUG=1 alacritty --print-events --config-file /dev/null >log.txt 2>&1
[log.txt](https://github.com/user-attachments/files/16400157/log.txt)

**Comment by chrisduerr** [comment]
@kchibisov Cursor theme issue maybe?

**Comment by Detoxify92** [comment]
I forgot to add that information, the cursor theme is default Adwaita. I just noticed that, when connected to an external display without scaling factor, there is no issue:
![image](https://github.com/user-attachments/assets/64aee30b-c4c4-45b5-8d2c-d27c4b11f787)

It would seem as related to the scaling factor, although I have not seen this behavior in any other program though.

**Comment by kchibisov** [comment]
hard to tell without `WAYLAND_DEBUG=1` log.

**Comment by Detoxify92** [comment]
I included the log with that variable in the first message. Is that not enough, or did I mess it up?

**Comment by kchibisov** [comment]
I somehow missed it, but that's enough to fix the issue.

**Comment by kchibisov** [comment]
it's a gnome bug, they don't send the event for the cursor surface, when using wl_compositor v6.

**Comment by kchibisov** [comment]
@Detoxify92 could you mention which gnome version was that?

**Comment by Detoxify92** [comment]
Oh, I see. My version is GNOME Shell 46.3.1. Thanks for taking the time to look into this!

**Comment by kchibisov** [comment]
there's unfortunatelly no workaround, since gnome explicitly indicates that the cursor scale is 1, so have to wait for them to fix it.
