### ISSUE TITLE
Can't make Alacritty read my config file

### ISSUE THREAD

**Issue by Silly-Funny** [alacritty/alacritty#8110]
Using Debian 12, installed Alacritty (version 0.11.0) using KDE's discover software center. I copied over the default config file from usr/share/doc/alacritty/examples/alacritty.yml to .config/alacritty/alacritty.yml and tried to change the decorations and opacity, but nothing changed. "alacritty -v" shows that my config is not found and it is using the default. I have tried:

- changing the name of the copied file to .alacritty.yml (someone said that this worked for them, not for me)
- putting the file just in the home directory under the name .alacritty.yml
- did everything previously stated but with toml extension instead.

I tried building alacritty from source first as I thought that this was the only option. I installed rustup during the process. Once I realized I could just install with discover, I just did that instead. 

I would rather use a toml file, as the configurations guide on the alacritty site lays out the toml configuration settings quite nicely (also it looks better imo). 

thank you for the help

**Comment by kchibisov** [comment]
Try passing `-v`?

**Comment by Silly-Funny** [comment]
Update: Taking inspiration from @kchibisov, I decided to purge alacritty and then install it using apt. Copied the default config file again to my .config/alacritty directory, and now when I run "alacritty -v", it shows that the Configuration files are being loaded from "/home/my_username/.config/alacritty/alacritty.yml" which is nice. However, my changes to said config file still have no effect on alacritty. This is where I am at now, I'll continue to look around and see if this issue has been fixed, but until then, any help is appreciated. Also, I'm fairly new to linux so please be patient haha.

**Comment by Silly-Funny** [comment]
Solved it, unfortunately it was pretty stupid haha. When making the changes to the decorations value, I did not uncomment the "window:" line. after doing so, alacritty made the changes. Still not sure how to use toml extension for config file, I would like to just based on preference, it looks much nicer to me.
