### ISSUE TITLE
Follow GTK/Qt color scheme for frame and background and text

### ISSUE THREAD

**Issue by bphd** [alacritty/alacritty#8111]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux/BSD/macOS/Windows
Version: `alacritty --version` output
Linux/BSD: X11/Wayland, DE or Compositor and WM

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by kchibisov** [comment]
we're neither Qt nor GTK application so it doesn't make any sense to do so.

**Comment by bphd** [comment]
> we're neither Qt nor GTK application so it doesn't make any sense to do so.

You don't get it. It's not about GTKifying the application. But the application being aware of it's environment to adapt to it. It's not important if the application use DotNet for its design to syncronize with Windows or idk what. Whatever the OS and DE could be, it's interesting to follow hooks of each DE to know if the DE (that manages color scheme) is set to dark or light scheme, to follow internally in own software. No need for the software to be coded the same way as the DE
