### ISSUE TITLE
Opacity does not seem to work on wayland (Mutter 46.3.1)

### ISSUE THREAD

**Issue by BrunoMarinhoM** [alacritty/alacritty#8112]
I'm currently using Debian (stable) with Gnome-shell (46) and some other Gnome components from Debian Unstable and while I was using x11/xorg everything was working perfectly fine with Alacritty. Though, after updating mutter to 46.3.1 and swithing to Gnome-Wayland it the opacity setting was no longer working;

### Behavior
  Alacritty window was fully black when opacity was set to 0.75;

### Expected 
  Alacritty window to be slightly transparent;

### System

OS: Linux
Version: 0.13.2
Linux/BSD: Gnome Wayland (mutter 46.3.1)

### Logs
None

Obs.: Thanks for the great work on this Terminal Emulator; I switched to it somewhat recently and it has been a smooth experience till now!

**Comment by kchibisov** [comment]
is the window fullscreen or it's just always black regardless of the mode?

**Comment by BrunoMarinhoM** [comment]
Only in fullscreen mode. I forget to mention it because I only use it that way!

But yes. It only happens when in full screen.

Is it a documented issue?

**Comment by kchibisov** [comment]
it's a wayland _feature_, opacity is not controlled by us here, so nothing could be done.

**Comment by kchibisov** [comment]
https://wayland.app/protocols/xdg-shell#xdg_toplevel:request:set_fullscreen

>If the fullscreened surface is not opaque, the compositor must make sure that other screen content not part of the same surface tree (made up of subsurfaces, popups or similarly coupled surfaces) are not visible below the fullscreened surface.
