### ISSUE TITLE
Enable the possibility to set ~ as PWD on macOS

### ISSUE THREAD

**Issue by cpach** [alacritty/alacritty#8114]
Please consider making some change so that new Alacritty windows open in the home directory, instead of the PWD of the current window.

Current behaviour:

- In the current window/shell, do `cd /opt` (or whatever directory)
- Now press `⌘N` to open a new window

Result:

The new shell/window has`/opt` as the PWD.

What I want instead:

That every new window has ~ as the PWD. Perhaps via a configuration option?

(NB: I’m not sure if the above behaviour exists for Linux users…?)

### System

OS: macOS
Version: alacritty 0.13.2 (bb8ea18)

**Comment by chrisduerr** [comment]
No.

**Comment by enjikaka** [comment]
I'd like this feature too.

**Comment by chrisduerr** [comment]
Some additional detail: This is already possible by adding a configuration option if the desire is to use Cmd+N to open in a different window (`alacritty msg create-window` does not copy the working directory).
