### ISSUE TITLE
Update keybinding example

### ISSUE THREAD

**Issue by samuelrivas** [alacritty/alacritty#8122]
The [keyboard mappings example](https://github.com/alacritty/alacritty/wiki/Keyboard-mappings) is using the old YAML config, which cannot be directly translated to TOML if you use unicode escapes. At least I have only managed to use unicode in TOML using the `\UXXXXXXXX` format, none of the other escapes worked (I am running on MacOs).

I have no idea how to make a pull request to a project wiki, I just managed to clone the wiki and push a branch in my own account: `https://github.com/samuelrivas/alacritty.wiki.git`, branch `update-keybinding-example`.

See the patch below if that were more convenient:

    diff --git a/Keyboard-mappings.md b/Keyboard-mappings.md
    index 0e14060..5e8cccb 100644
    --- a/Keyboard-mappings.md
    +++ b/Keyboard-mappings.md
    @@ -25,15 +25,17 @@ We're interested in:
     - The value between the brackets of `Some`, which is the one to use in the key property of the mapping
     - The boolean properties in `ModifiersState`, which indicate which modifiers to add in the mods property of the mapping (these can be concatenated using the `|` character)
     
    -The value for the `chars` property of each entry in `key_bindings:` can be any text string and supports both hexadecimal (`\xNN`) and unicode (`\uNNNN`) escapes:
    +The value for the `chars` property of each entry in `key_bindings:` can be any
    +text string and supports unicode (`\UNNNNNNNN`) escapes:
     
    -```yml
    +```toml
    +[keyboard]
    +bindings = [
       # Insert the `[` character
    -  - { key: LBracket, mods: Alt, chars: "[" }
    +  { key = "LBracket", mods = "Alt", chars = "[" },
       # Send the Ctrl+C control using its hex value...
    -  - { key: T, mods: Control|Shift, chars: "\x03" }
    -  # ... or using its unicode value
    -  - { key: T, mods: Control|Shift, chars: "\u0003" }
    +  { key = "T", mods = "Control|Shift", chars = "\U00000003" }
    +]
     ```
     
     ### The `virtual_keycode` is `None`
    @@ -42,6 +44,6 @@ If Alacritty is not able to find the correct keycode for the pressed key, it mig
     
     The scancode is also printed in the output of `--print-events` and can be used directly in the `key` field of a mapping:
     
    -```yml
    -  - { key: 33, mods: Alt, chars: "[" }
    -```
    \ No newline at end of file
    +```toml
    +  { key = "33", mods = "Alt", chars = "[" }
    +```

**Comment by unphased** [comment]
Do you have any guidance on how to convert to \UXXXXXXXX format? For example I have a shift return bind for "\x1b\x0a". Not finding a way to convert this to toml.

**Comment by unphased** [comment]
Looks like my example would be `"\u001b\u000a"`.

**Comment by samuelrivas** [comment]
I was sure that I had tested `\uXXXX` and they didn't work, but they seem to work now, so my patch was somewhat inaccurate...
