### ISSUE TITLE
Always on top feature

### ISSUE THREAD

**Issue by unphased** [alacritty/alacritty#8126]
I think that winit supports this already: https://github.com/rust-windowing/winit/issues/522

Basically the thing is we used to use SIMBL to be able to inject some code in applications to get them to do window manager specific behavior like control always-on-top behavior and set transparency and such things. 

Nowadays macOS is very locked down and the SIMBL approach is gone and dead. 

The requirement is that the app simply implement any such behavior on its own. Since our winit window management lib already supports this capability, shall we expose it to alacritty? 

I want to 
- get a hotkey method to show/hide alacritty, various tools like hammerspoon can address this need 
- hot key to toggle its fullscreen-ness (already supported in alacritty as bindable action)
- hot keys to adjust opacity (don't think it's supported as a bindable action but shouldnt be hard)
- toggle always-on-top-ness with a hotkey. 

This last one is crucially not possible to do with any external scripting system due to the above explanation of the security stance of the operating system. See all existing workflows posted here: https://github.com/alacritty/alacritty/issues/862

None can address the last bullet.

**Comment by chrisduerr** [comment]
I personally don't think such a thing should exist in applications, since it's clearly the responsibility of a window manager.

However since it should be trivial to implement with winit, I'd probably accept a PR sent by someone else.

**Comment by davehorner** [comment]
AlwaysOnTop support has been submitted;
https://github.com/alacritty/alacritty/pull/8269
