### ISSUE TITLE
OSC 8 hyperlink support not working while mouse tracking is on

### ISSUE THREAD

**Issue by stefanhaller** [alacritty/alacritty#8129]
Alacritty doesn't support OSC 8 hyperlinks while the running application has captured the mouse.

To illustrate, run the following script:
```bash
#!/bin/sh

printf '\e[?1000h'
printf '\e]8;;http://example.com\e\\This is a link\e]8;;\e\\\n'
sleep 10
printf '\e[?1000l'
```

While the script is running, the link doesn't work; after the script returned, it does.

I'm sure this is intentional, because an app that captured the mouse might want to use the button clicks itself. It is a problem though: I'm co-maintaining a TUI application that does want to make use of OSC 8 hyperlinks, and they don't work in Alacritty. (See https://github.com/jesseduffield/lazygit/pull/3825)

It works in other terminal emulators, although I have only tried iTerm2 and VS Code's builtin terminal. They both require you to hold the command key to launch a URL, so this interferes less with what the application might want to use the click for. (However, they both _also_ pass the click to the application, which is very undesirable.) I prefer Alacritty's more direct way to launch links without having to hold a modifier.

Would you consider enabling hyperlink support for TUI apps unconditionally?

### System

OS: macOS 14.6.1
Version: alacritty 0.13.2 (bb8ea18)

**Comment by chrisduerr** [comment]
This is working as intended and not a problem. Just hold shift.

**Comment by stefanhaller** [comment]
OK, thanks. Shift-clicking the link works.

I don't agree that it's "not a problem" though. Note that I'm not a user who wants to get it to work for myself; I'm a developer who has to deal with the bug reports for my app.

Also, it's very unfortunate that the hyperlinks aren't underlined in TUI apps unless you hold shift (and even if you do hold shift, the underlining is flaky). So users have to guess where the links are. Other terminal emulators underline the links always (sometimes dotted, with the underline becoming solid on hover), even if they require holding a modifier for clicking.
