### ISSUE TITLE
SVG logo causes a parser warning to be logged

### ISSUE THREAD

**Issue by zacknewman** [alacritty/alacritty#8133]
I apologize if this is a bug in [`usvg`](https://docs.rs/usvg/latest/usvg/), but it logs a warning when parsing the official logo:

```bash
2024-08-16T14:48:57.549938140Z[usvg::parser::svgtree][WARN] Failed to parse clip-path value: 'none'.
```

I noticed the SVG file has two `clip-path` values in the same element. When I removed [the one with the value `"none"`](https://github.com/alacritty/alacritty/blob/master/extra/logo/alacritty-term.svg?short_path=065df53#L426), the parser no longer complains. Should this be removed from the file so that [only the `clip-path` value 12 lines later exists](https://github.com/alacritty/alacritty/blob/master/extra/logo/alacritty-term.svg?short_path=065df53#L438)?

**Comment by chrisduerr** [comment]
Logos weren't created by hand, so must have been inkscape accidentally leaving that in? Can you send a patch to remove the first clip-path?
