### ISSUE TITLE
c++ compiler missing in dependencies

### ISSUE THREAD

**Issue by Foly93** [alacritty/alacritty#8134]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Linux ubuntu 22.04
Linux/BSD: X11/Wayland, DE or Compositor and WM

Hi, 

At alacritty/INSTALL.md in the prerequisites, the dependencies were incomplete for me. I was setting up on a brand new computer which did not have a c++ compiler. 

The command 
```cargo build --release```
for me triggered the following (luckily very suggestive) error:
```error occurred: Failed to find tool. Is `c++` installed?```

I fixed it by installing the compiler with the following line of code:
```sudo apt install build-essential```

**Comment by chrisduerr** [comment]
If you know dependencies missing for a specific distro please feel free to just open a PR and correct them.
