### ISSUE TITLE
TUI rendering error with `yazi`

### ISSUE THREAD

**Issue by beeb** [alacritty/alacritty#8136]
### System

OS: Windows 11
Version: 0.13.2
Ubuntu on WSL2

### Logs

N/A

### Description

Using the latest version of `yazi` (v0.3.x), the frames of their TUI doesn't display properly with alacritty when resizing the window. Also, there are some stray ghost letters that don't disappear when resizing the window.

Notice the interrupted or misaligned vertical lines and the stray `c` letter on the right side.
Also notice the misalignement of the blue & grey "badges" rounded corners in the status bar.

![image](https://github.com/user-attachments/assets/5674e7b2-9b60-489a-8c86-531c852a58f8)

Other example:

![358900208-0dbaffa0-f3da-4174-84b0-5a4bd5baa315](https://github.com/user-attachments/assets/36b46bc4-76fc-466e-845f-4ed6200b8b22)

**Comment by beeb** [comment]
@chrisduerr I notice you closed this as completed. Is there a commit or pr reference to support this has been fixed? Sorry there's a lot since the last release so I couldn't find it easily.

**Comment by chrisduerr** [comment]
The yazi issue you've opened has already stated the solution to this issue.

**Comment by beeb** [comment]
Thanks for the quick reply @chrisduerr . I am bit lost, I didn't find a solution to my problem. What I describe happens without multiplexer. Do you mean the solution involving updating `conpty.dll` ?

**Comment by py-cyberuser** [comment]
Same issue here. On win10, tested on `windows terminal`, `vscode terminal`, `wezterm terminal` and `alacritty`. Only `alacritty` has this problem.

System Info
----------------
Win10 22H2 Professional
Yazi 25.5.31 (b65a880 2025-05-30)
Alacritty 0.16.1
