### ISSUE TITLE
[feature request] command line args

### ISSUE THREAD

**Issue by wjx0912** [alacritty/alacritty#8141]
(1) open a new alacritty window and  automatic goto directory /xxx/yyy
alacritty  --newwin  --path  /xxx/yyy

(2) add a tab on exist alacritty
alacritty  --addtab   --path  /xxx/yyy

it's very useful (for https://github.com/onmyway133/FinderGo or http://zipzapmac.com/Go2Shell, or other finder Enhancement tool).

thanks a lot

**Comment by kchibisov** [comment]
`--working-directory /xxx/yyy`

`alacritty msg create-window --working-directory /xxx/yyy`
