### ISSUE TITLE
Alacritty closed immediately after running with args 

### ISSUE THREAD

**Issue by MukalDadhwal** [alacritty/alacritty#8142]
After adding the args parameter in alacritty toml file  it crashed immediately after opening without the args its working nicely. I am using the latest release so not sure why this is happening

### System

OS: Windows
Version: alacritty 0.13.2 (bb8ea18)

```
import = [
  
]

[shell]
program = "C:\\Program Files\\WSL\\wsl.exe"
args = ["-c", "cd ~"]

[colors]
draw_bold_text_with_bright_colors=false

# Colors (Tokyo Night)
# Source https//github.com/zatchheems/tokyo-night-alacritty-theme

# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'

# Normal colors
[colors.normal]
black   = '#32344a'
red     = '#f7768e'
green   = '#9ece6a'
yellow  = '#e0af68'
blue    = '#7aa2f7'
magenta = '#ad8ee6'
cyan    = '#449dab'
white   = '#787c99'

# Bright colors
[colors.bright]
black   = '#444b6a'
red     = '#ff7a93'
green   = '#b9f27c'
yellow  = '#ff9e64'
blue    = '#7da6ff'
magenta = '#bb9af7'
cyan    = '#0db9d7'
white   = '#acb0d0'

```

**Comment by chrisduerr** [comment]
Working as expected. You're spawning something non-interactive, of course there's not going to be interactivity.

**Comment by kchibisov** [comment]
If you want to spawn alacritty at some directory, specify `working_directory`.

**Comment by MukalDadhwal** [comment]
so whats the right flag?

**Comment by MukalDadhwal** [comment]
tried using the working_directory flag like `working_directory="\\wsl.localhost\\Ubuntu\\home\\mukal"` but that wasn't working so had to find a work around
