### ISSUE TITLE
[Question] Is it possible to make a shortcut to increase/decrease opacity by 0.1?

### ISSUE THREAD

**Issue by pentago** [alacritty/alacritty#8145]
### System

OS: macOS
Version: alacritty 0.13.2 (bb8ea18)

**Comment by chrisduerr** [comment]
Yes it is.

**Comment by pentago** [comment]
👏👏

**Comment by Archie-2021** [comment]
I am looking for similar thing, How I can do this?
I know config file is dynamic and could be changed on the fly, but I just want to change it on the current window. Can't find anything in the manpage.

**Comment by kchibisov** [comment]
`alacritty msg config window.opacity=new_value`
