### ISSUE TITLE
WHAT IN THE NAME OF HAMBURGERS IS dim_foreground?

### ISSUE THREAD

**Issue by mohamadali-halwani** [alacritty/alacritty#8158]
Greetings everyone, and sorry for screaming in the title :yum: 
I looked all over the documentation, arch wiki, man pages, for an explanation of the setting dim_foreground and found nothing. I tried tinkering with it and I couldn't notice any differences.
Can someone please explain it to me? I'm trying to make my own Colourscheme.

also:
2-what is bright_foreground?
3-Can I make the font colour to be darker in the brighter colours on the right? 
![image](https://github.com/user-attachments/assets/a08e4190-dd00-4bad-9578-cc8caf1391ac)

Thanks in advance

**Comment by kchibisov** [comment]
dim attribute(like bold) without setting any extra coloring.
bright foreground is used for draw_bold_as_bright iirc.

>3-Can I make the font colour to be darker in the brighter colours on the right?

no, since it's a reverse.
