### ISSUE TITLE
Incorrect cursor color when using default cursor config (OSC12)

### ISSUE THREAD

**Issue by aymanbagabas** [alacritty/alacritty#8169]
Using the default config, i.e. `cursor = { text = "CellBackground", cursor = "CellForeground" }`, querying the cursor color returns invalid color.

<img width="236" alt="image" src="https://github.com/user-attachments/assets/348cd747-04ac-4790-be90-f6f16726bd94">

Should return the appropriate color using the `CellForeground` color value `^[]12;rgb:acf1/b277/be84^G`

### System

OS: macOS
Version: alacritty 0.13.2 (bb8ea18)

**Comment by chrisduerr** [comment]
There's no point in returning the current cell color, why do you want this?

**Comment by aymanbagabas** [comment]
> There's no point in returning the current cell color, why do you want this?

I mean, what's the point of implementing OSC12 then? I respectfully disagree, I think it's important to _know_ what is the current set cursor color.

In my case, I'm writing programs that change the terminal colors and want to be able to restore them _after_ a program exits. This means when a program starts, it queries the terminal and store the fg/bg/cursor colors, then on exit, it resets these colors if they were changed.

**Comment by chrisduerr** [comment]
> I mean, what's the point of implementing OSC12 then?

It's only useful for static colors. Arguably for the cursor it's not really that useful at all, since it usually isn't static.

> In my case, I'm writing programs that change the terminal colors and want to be able to restore them after a program exits. This means when a program starts, it queries the terminal and store the fg/bg/cursor colors, then on exit, it resets these colors if they were changed.

See, this would behave **incorrectly**, so if anything that's an argument for not changing the behavior since this issue report just caught a bug in your application.

**Comment by aymanbagabas** [comment]
> See, this would behave incorrectly, so if anything that's an argument for not changing the behavior since this issue report just caught a bug in your application.

I don't think this is an issue in my application. Alacritty is reporting the _wrong_ color. Visually, I have a gray cursor. Alacritty reports that the cursor color is black `#000000` or `rgb:0000/0000/0000` as seen in the image above.

I switched to using `OSC 112` in my application instead. However, I still believe that Alacritty _should_ return the cursor configured color instead of `#000000` black.

I will leave this open as I believe this is a bug and OSC12 should behave the same as OSC10 and OSC11 for foreground and background colors.

**Comment by chrisduerr** [comment]
I think you're right that reporting `#000000` when that's factually incorrect is not beneficial. However I also do believe trying to query the cursor color in this scenario is not beneficial to begin with, unless the cursor color was already changed using this escape to begin with.

So I've opened https://github.com/alacritty/alacritty/pull/8191, which does not respond to the request unless the cursor color was actually changed. Most applications I know send other requests after OSC queries anyway to synchronize responses, so it shouldn't be an issue that we respond only conditionally.
