### ISSUE TITLE
Missing slashes in location of config file for windows

### ISSUE THREAD

**Issue by KronosTheLate** [alacritty/alacritty#8171]
The [config-alacritty.html](https://alacritty.org/config-alacritty.html) page shows the following paths for the config file:
![image](https://github.com/user-attachments/assets/d16d4107-392c-4d71-9fbc-d6999c55f850)

The directory deliminators are misssing for the windows path. Might be an issue with how windows uses the wrong slash, so that the value is escaped somehow.

**Comment by Piecuuu** [comment]
This is still here!

**Comment by chrisduerr** [comment]
The audacity!

**Comment by KronosTheLate** [comment]
...I am sorry, I'm quite confused by the response here. Can someone bring me up to speed on the issue with my issue?

**Comment by chrisduerr** [comment]
There is no issue, it's already been fixed it just hasn't been published yet.
