### ISSUE TITLE
How can I retrieve all characters from a Grid<Cell>

### ISSUE THREAD

**Issue by jm-observer** [alacritty/alacritty#8172]
IDE [Lapce ](https://github.com/lapce/lapce)has integrated alacritty_terminal. Now I want to capture the standard output of programs running inside the terminal. Could you please advise on how to achieve this?

**Comment by chrisduerr** [comment]
I recommend just checking out https://github.com/alacritty/alacritty/pull/4550 and the previous PR attempt at it. Since their goal was writing all terminal content to a file, it should help you getting all terminal content.
