### ISSUE TITLE
Alacritty modern icon on macOS

### ISSUE THREAD

**Issue by samholmes** [alacritty/alacritty#8173]
I think it's time for a refreshed appearance for Alacritty in 2024/2025.

If you look at icons for modern terminal programs like Warp, you'll quickly start to notice the VC-backing peaking through the design. This might make you a bit jealous, and you might say to yourself "should I give up on my principals and just _log-in to my terminal app_?"

Fear not, because FOSS can always persevere with great contributions by anyone in the world!

So today, I kindly give my contribution and present to you, the new Alacritty macOS icon!

<details>
<summary>🍾🎁🎉</summary>
<img width="1023" alt="Alacritty Icon Picture" src="https://github.com/user-attachments/assets/75c590b1-ae3a-472f-b5ad-53205e64bb84">

<br>

<h3>Preview</h3>
<img width="290" alt="Screenshot 2024-09-13 at 3 03 59 PM" src="https://github.com/user-attachments/assets/ea3af09b-1295-4ddc-a5fe-5fef3de10932">

<br>

<h3>Icon</h3>
<img width="512" alt="Alacritty" src="https://github.com/user-attachments/assets/f1412f9d-f28a-484b-ad6c-362f6f2d0e63">

</details>

**Comment by samholmes** [comment]
@chrisduerr 🥺

**Comment by hadronized** [comment]
Nice one @samholmes. I’m trying my own too! I shall present you… the new logo!

![image](https://github.com/user-attachments/assets/7e4912ae-0223-4cdb-8daa-28256856e669)

**Comment by samholmes** [comment]
@hadronized 

![Very Nice](https://github.com/user-attachments/assets/94ba02bb-acc0-4e82-9cdc-33ebfc1654bc)

**Comment by nixpulvis** [comment]
What’s the smallest icon you can make on macOS?

**Comment by samholmes** [comment]
Here are some updates to the icon:

<img width="512" alt="Alacritty" src="https://github.com/user-attachments/assets/b2f0bee7-8937-4553-9e1e-01d784f31e78">

You can download the icns from:

https://parsefiles.back4app.com/JPaQcFfEEQ1ePBxbf6wvzkPMEqKYHhPYv8boI1Rc/15af56129e9ac1b9b1ebb0dfc3e42cf4_Alacritty.icns

**Comment by nixpulvis** [comment]
So I just googled "Alacritty" and google seems to have invented their own logo...
![Screenshot 2024-10-08 172220](https://github.com/user-attachments/assets/1d646c97-de8f-4d3d-ab39-23ae09391c14)

I don't think I've seen that one before.

**Comment by j4james** [comment]
> So I just googled "Alacritty" and google seems to have invented their own logo...

I think it's unlikely that Google has employed an artist to create custom images for every single search term. The area above the Wikipedia extract is just a sampling of image results for your search. And if I had to guess, I'd say they prioritized that particular image because it's the top result when searching for "Alacritty icon".

**Comment by ymattw** [comment]
This ticket is marked `F-duplicated` but I could not locate the canonical ticket. If this feature is no longer planned, I would appreciate it if this ticket could be reconsidered.

For reference, please see the attached screenshot of the macOS application switch window (⌘-Tab) below. I believe a smaller icon size would improve the overall aesthetic appeal.

![Image](https://github.com/user-attachments/assets/d76b22d1-736e-47c0-ad5c-63747a030b7d)

**Comment by mrmeszaros** [comment]
@nixpulvis That icon looks like it was done for [numixproject/numix-icon-theme-circle](https://github.com/numixproject/numix-icon-theme-circle).

Though the current is different: https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48/apps/alacritty.svg

BTW: The current MacOS Tahoe icon style is a bit different - but I don't know how should/could Alacritty provide an icon/icons that conform with that.

**Comment by chrisduerr** [comment]
> BTW: The current MacOS Tahoe icon style is a bit different - but I don't know how should/could Alacritty provide an icon/icons that conform with that.

We'll just wait a little longer. Eventually our icon will fit back in with the current macOS style.

**Comment by zhangzhuang15** [comment]
> Here are some updates to the icon:
> 
> <img alt="Alacritty" width="512" src="https://private-user-images.githubusercontent.com/517469/373424339-b2f0bee7-8937-4553-9e1e-01d784f31e78.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjU5MzcyNTksIm5iZiI6MTc2NTkzNjk1OSwicGF0aCI6Ii81MTc0NjkvMzczNDI0MzM5LWIyZjBiZWU3LTg5MzctNDU1My05ZTFlLTAxZDc4NGYzMWU3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIxN1QwMjAyMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yODI2ZDEwZTY5M2NjNmM4NjUxMjZmZjVjMzA3NzZjYTI0MmY3YjU2ZjYyNTkyZTZlYmE5NDdiYTZhYWFkNjYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BgeU-3BuveyMrySrekgpAQe_9cuNdrjigCtp0YBEirc">
> You can download the icns from:
> 
> https://parsefiles.back4app.com/JPaQcFfEEQ1ePBxbf6wvzkPMEqKYHhPYv8boI1Rc/15af56129e9ac1b9b1ebb0dfc3e42cf4_Alacritty.icns

@samholmes Thanks for your sharing, I really like it. This is my dock.

<img width="88" height="196" alt="Image" src="https://github.com/user-attachments/assets/2c501be2-598f-43f9-8a93-9e5201fc8055" />
