### ISSUE TITLE
Winget requires administrator (Command 'winget' cannot be found)

### ISSUE THREAD

**Issue by johanvanmol** [alacritty/alacritty#8179]
When trying to use `winget` in Alacritty, I get a `Command 'winget' cannot be found.` error.
When doing the same thing in Microsoft Terminal, winget works.
I am using PowerShell 7.4.5 both in Alacritty and in Windows Terminal.

![image](https://github.com/user-attachments/assets/ccbcbebc-74eb-471d-8465-25a1a13ceaac)

When running Alacritty as Administrator, winget works.
![image](https://github.com/user-attachments/assets/ab9e669e-5250-4d95-9a17-a9839007bed1)

Is this a limitation in Alacritty?  Should it always be in admin to be able to use winget?
Or is something misconfigured on my system?

### System

OS: Windows
Version: alacritty 0.13.2 (bb8ea18)
PowerShell 7.4.5

**Comment by kchibisov** [comment]
alacritty has nothing to do with what you run inside of it.

It really looks like `environment` is different when you use admin/no admin, but the environment is not alacritty's concern as well.

**Comment by johanvanmol** [comment]
Thank you for answering my question, and sorry for creating an issue that isn't related to Alacritty.
You pointed me in the right direction.
Windows Terminal and Alacritty were using different paths in the environment.
After adding the correct path, winget also works in Alacritty without admin.

![image](https://github.com/user-attachments/assets/2e2b2a9e-5214-42cc-8943-72ae2a25d0a9)
