### ISSUE TITLE
If you are not root in the ssh machine you connect to, you cannot fix error E558: Terminal entry not found in terminfo.

### ISSUE THREAD

**Issue by jeremies** [alacritty/alacritty#8183]
But if you are not in the sudo group of the ssh machine you connect to, you cannot fix error E558: Terminal entry not found in terminfo. I think that this should be fixed without touching the remote machine.

![image](https://github.com/user-attachments/assets/aa116b2e-d52b-4729-953b-b92c6da6d3d2)

_Originally posted by @jeremies in https://github.com/alacritty/alacritty/issues/3956#issuecomment-2358462268_

**Comment by kchibisov** [comment]
You don't need root to install terminfo on a remote and you can always temprorary alter `TERM` before ssh into old remote host.
