### ISSUE TITLE
Documentation shows probably wrong config file location

### ISSUE THREAD

**Issue by gintsgints** [alacritty/alacritty#8184]
### System
Windows
Version: v0.13.2-portable

Documentation about configuration - https://alacritty.org/config-alacritty.html states that for windows environment config file location is `%APPDATA%alacrittyalacritty.toml` . Could not be, that somewhere is missing slash, because alacritty could not be 2x in file name.

**Comment by chrisduerr** [comment]
Fixed on master already.
