### ISSUE TITLE
`alacritty msg config` command only works on calling terminal unless socket is manually specified

### ISSUE THREAD

**Issue by ViperZer0** [alacritty/alacritty#8185]
### System

OS: Arch Linux
Version: alacritty 0.13.2 (bb8ea18e)
Linux/BSD: X11, AwesomeWM

### Issue

I'm trying to dynamically change configuration options with `alacritty msg config`, but the `-w` flag doesn't seem to work at all. Any changes I make only take place inside the terminal i run the command on. Specifying `-w -1` doesn't work, nor does retrieving the window id of another terminal.

For reference, these are the commands I've tried:
`alacritty msg config 'colors.primary.foreground="#ffffff"` (works on the terminal i run the command on, but no others)
`alacritty msg config -w -1 'colors.primary.foreground="#ffffff"` (also works on the calling terminal, but none others)
If I get the $ALACRITTY_WINDOW_ID of another window:
```
# Terminal 1
echo $ALACRITTY_WINDOW_ID 
# Terminal 2 
alacritty msg config -w <result from ALACRITTY_WINDOW_ID> 'colors.primary.foreground="#ffffff"'
```

### Workaround

This *does* work if I specify a socket for the receiving terminal on creation and in the alacritty msg command. If this is intentional, could the man pages be updated to better explain that the socket argument is necessary if you want to change the configuration for other open terminals? And secondly, as far as I'm aware multiple terminals can't have the same socket, making changing the configuration of multiple terminals impossible, which possibly defeats the purpose of being able to apply a change to all windows?

Thanks!

**Comment by kchibisov** [comment]
If you run separate instances it's kind of expected that they don't share configuration?

You should use _windows_ and not instances if you want to update all the _windows_ at once.
