### ISSUE TITLE
Debian does not require full path while Arch does

### ISSUE THREAD

**Issue by dougg0k** [alacritty/alacritty#8187]
### System

OS: Linux (Arch)
Version: 0.13.2
Linux/BSD: Wayland

For whatever reason in my debian based distro, if I set the shell to the short name. Like `zellij` or `nu` from nushell, it works.

Whoever on arch, not even using `~/` to identify home, it only works if I set the path to the full path, including in the flags.

```
[shell]
program = "/home/user/.cargo/bin/zellij"
args = ["options", "--default-shell", "/home/user/.cargo/bin/nu"]
```

Is there a way to fix this on arch and make it work on the short call?

---

Here is how I use on my debian based OS and it detects the config from zellij fine. Including nushell that is called from there just by `nu`.

```
[shell]
program = "zellij"
args = []
```

It seems to be only related to anything pertaining path, because everything else it seems to work from the config.

---

A third fact, when trying on Wezterm, I had the same type of issue till I set the PATH variable the lua config. Problem is that alacritty does not have anything like that.

Also the $PATH by default already includes what is needed, still doesnt seem to be enough.

---

I tried setting the default shell to different ones with `chsh`, it didnt help.

---

If I didnt set the full path to zellij, alacritty does not open. 

If I set only the full path to zellij and leave it to use its own `config.kdl` with `default_shell "nu"`. It only opens zellij with no shell. Unable to type anything.

**Comment by chrisduerr** [comment]
Fix your login profile, it works just fine on Arch.

**Comment by dougg0k** [comment]
In case someone else reach the same problem, try fixing the path on `/etc/profile` or `/etc/profile.d`.

Every other place didnt do anything.
