### ISSUE TITLE
alacritty not honouring [semantic_escape_chars] setting 

### ISSUE THREAD

**Issue by unaccounted-github** [alacritty/alacritty#8188]
I hope I am not over-stepping any github/alacritty rules. My previous ticket has been closed, and I cannot find a way to reopen it (just joined yesterday).

Please feel free to delete this ticket if need be.

`semantic_escape_chars = ",│`|:\"' ()[]{}<>\t•-—－．"`

Here's a video of what happens after [Ctrl] + [Shift] + [Space]

https://github.com/user-attachments/assets/0657d09d-544f-46e6-8964-1e58f977de26

**Comment by chrisduerr** [comment]
You can just comment under existing issues, there's no need to create new ones.

I've checked out the characters you mention specifically and it seems like fullwidth characters can't be used as semantic escape chars.

**Comment by unaccounted-github** [comment]
Thanks for clearing that up. Many thanks for an exceptional piece of software.

**Comment by chrisduerr** [comment]
Should be fixed with #8190, feel free to test if that works for you.

**Comment by unaccounted-github** [comment]
Many thanks to you for taking the time to fix this. I'll wait for an official release from my distro, as I do not have the knowledge on how to get this patch working on my setup.

With humble gratitude.
Cheers
