### ISSUE TITLE
åäö followed by another character turns into one character

### ISSUE THREAD

**Issue by Mikroskoldis** [alacritty/alacritty#8189]
Printing out "äa" as "ä". Happens with all of the Swedish letters åäö followed by a character that can be combined with them. For example åu creates u with a circle above it and so on. I have tried setting it to Swedish locale instead but it still doesn't work and UTF-8 should be able to handle it either way.

This happens when files for example has the name "testäa.txt" and it will instead be printed as "testä.txt" with the ls command. echoing out "äa" works as expected so it's only the file names that's being incorrectly displayed. 

### System

OS: macOS
Version: `0.13.2 (bb8ea18)`

Font/Terminal size: 
[DEBUG] [alacritty] Using environment locale: en_US.UTF-8/UTF-8/en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/en_US.UTF-8
[DEBUG] [alacritty] Loading "MesloLGS NF" font

Expected:
<img width="154" alt="Screenshot 2024-09-21 at 20 45 40" src="https://github.com/user-attachments/assets/5cb57d87-8514-4a37-857d-58caf82af7ec">

Actual:
<img width="154" alt="Screenshot 2024-09-21 at 20 45 30" src="https://github.com/user-attachments/assets/8bfba511-afcb-480c-9c60-4ea2a561f45f">

**Comment by chrisduerr** [comment]
I'm not sure what you are saying. Is the character getting input on the shell prompt not what you expect, or is this about what the shell is doing?

**Comment by Mikroskoldis** [comment]
The input is fine, it's for example if you have a file on your desktop named such as the images above and you try and display it with for example `cd` it turns äa into ä and so on. The input into the terminal works fine. It works fine on the original MacOS terminal so I assumed this was an alacritty issue, also tested it with Iterm and seems to be working fine there as well.

**Comment by chrisduerr** [comment]
> The input into the terminal works fine.

Then there is no issue.

**Comment by Mikroskoldis** [comment]
> > The input into the terminal works fine.
> 
> Then there is no issue.

Yes the input works fine but the output isn't working while it's working on other terminals for mac.

**Comment by chrisduerr** [comment]
macOS just does some unusual unicode normalization, it's not unexpected.

**Comment by Mikroskoldis** [comment]
Alright, is there a workaround for it or just live with it for the moment?

**Comment by chrisduerr** [comment]
If you want specific unicode normalization behavior, it should be done in applications.

On Linux if I create a file like `tüst`, then it properly uses the `ü` character in that filename so no normalization is never necessary. The same can be done on macOS, but I'd assume that input method/file manager are just being stubborn and not normalizing these things.
