### ISSUE TITLE
Trying to use Hints for opening files in Neovim - "unable to launch nvim with args ["<FILENAME>"]"

### ISSUE THREAD

**Issue by MikeBirdTech** [alacritty/alacritty#8193]
Is it possible to have the hint's text passed to the command as a string rather than an array?

Setting the command to "nvim" or trying different shell commands wouldn't work and would result in an error - "unable to launch nvim with args ["<FILENAME>"]"

The objective is to have the regex pick up any code files and open them in Neovim to edit.

Any suggestions would be greatly appreciated! Thank you

**Comment by kchibisov** [comment]
`command = { program = "alacritty", args = ["-e", "vi"] }`

this should work. hint is passed as the last argument to what you've specified.

**Comment by MikeBirdTech** [comment]
Appreciate the help @kchibisov 

Unfortunately, it still results in the same error `Unable to launch alacritty with args ["-e", "nvim", "README.md"]`

When I run `alacritty -e nvim README.md` it opens a new alacritty window running nvim but there is no contents shown.
`cat README.md` does show the contents of the file

Could there be an issue with the command not knowing the path of the file?

**Comment by kchibisov** [comment]
Your path is relative, meaning that it'll be relative to the place you've launched alacritty from, you should use absolute path or uri for that.

If you use `ls` for that, pass the `--hyperlink` to it and use `hyperlinks = true` for the hint.

**Comment by MikeBirdTech** [comment]
Makes sense.

Added hyperlinks = true to the hint.

Running `ls --hyperlink` results in a similar error:

`Unable to launch alacritty with args ["-e", "nvim", "file:///Users/path/README.md"]`

Thanks again for your time

**Comment by kchibisov** [comment]
Maybe alacritty is not in your path when you run it like that (if you're on macOS for example or it's installed inside the .cargo)? Could try to use absolute path to it in the config.

**Comment by MikeBirdTech** [comment]
Adding absolute path to the config changed something. Now when I select the hint, nothing happens. No error but no new Alacritty window opens.

Actually, the Alacritty window title bar has a slight flicker when I select the hint, so something is happening somewhere.

`/opt/homebrew/bin/alacritty -e nvim file:///Users/path/README.md` works as expected

**Comment by kchibisov** [comment]
what if `/opt/homebrew/bin/nvim` as well?

**Comment by MikeBirdTech** [comment]
My man!! Works like a charm. This is such a great unlock. Thank you so much for helping debug and all the work you do
