### ISSUE TITLE
MacOS 15: Alacritty unresponsive and unsable on M2 Mac Mini

### ISSUE THREAD

**Issue by elcharitas** [alacritty/alacritty#8196]
By unresponsive and unusable, I mean, I can't type on the terminal. I first noticed this on Zed Editor but decided to install alacritty separately to confirm my doubts.

I must say that I only experienced this issue on M2-sillicon chip mac mini. I have an intel macbook running MacOS 15 which deosn't experience this issue.

### System

OS: MacOS 15 (M2-chip)
Alacritty Version: 0.13.2 (I suspect this occurs even with older versions but I haven't checked)

### Logs

Due to the terminal being completely unresponsive, I can't access logs but I do have a screenshot:
![Screenshot 2024-09-25 at 07 21 36](https://github.com/user-attachments/assets/4e7902c9-fb2f-4310-91d4-fc85ad545839)

**Comment by chrisduerr** [comment]
It might be worth trying to build from source, but nothing has changed about Alacritty so there's nothing to fix.
