### ISSUE TITLE
Copy Last Used Command to Clipboard Using Shorcut

### ISSUE THREAD

**Issue by Armageddon0x00** [alacritty/alacritty#8198]
Hi,

# Problem
I sometimes need to use really large command line commands. These commands are too long and often I need to copy them for documentation. Selecting each of them by hand often takes a long time and results in missing chars / mistakes made by me because of manual copying.

# Feature Request (If it does not already exists)
Is there a way I can map a shortcut similar to Copy-Paste structure but only for the last used command? For example Super + Shift + C will only copy the last used command to clipboard (exit status does not matter for my condition).

## Command Output Copy
The same issue above but this time a shortcut mapped directly copies the whole stdout printed to terminal by last used command. (This is secondary to my needs.)

Thanks!

**Comment by nixpulvis** [comment]
Alacritty doesn't have any notion of "commands". Once it spawns your shell it's on the shell to do all the running of stuff.

I'd look into making this in your shell.

**Comment by chrisduerr** [comment]
> I'd look into making this in your shell.

Exactly this. Most shells should already make this pretty trivial using vi mode.
