### ISSUE TITLE
Paths relative to the current config file fail to import

### ISSUE THREAD

**Issue by IzhakJakov** [alacritty/alacritty#8199]
### Description
From the [Configuration User Guide](https://alacritty.org/config-alacritty.html#s0):
> ```
> import = ["<string>",]
>
>     Import additional configuration files.
>
>     Imports are loaded in order, skipping all missing files, with the importing file being loaded last. If a field is already present in a previous import, it will be replaced.
>
>     All imports must either be absolute paths starting with /, paths relative to the user's home directory starting with ~/, or paths relative from the current config file.
>
>     Example:
>
>         import = [
>         "~/.config/alacritty/base16-dark.toml",
>         "~/.config/alacritty/keybindings.toml",
>         "alacritty-theme/themes/gruvbox_dark.toml",
>         ]
> ```

Based on this: "..., or paths relative from the current config file"
I tried to set my config to import my colorscheme from a directory relative to the current config file:
```toml
import = ["colors/colorscheme.toml"]
```
Unfortunately, that did not seem to work:
```
[0.000002625s] [INFO ] [alacritty] Welcome to Alacritty
[0.000343917s] [INFO ] [alacritty] Version 0.13.2 (bb8ea18)
[0.000599834s] [INFO ] [alacritty_config_derive] Config import not found:
                                                   "colors/colorscheme.toml"
[0.000833959s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/Users/IzhakJakov/.config/alacritty/alacritty.toml"
```

For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System
OS: macOS
Version: alacritty 0.13.2 (bb8ea18)

**Comment by IzhakJakov** [comment]
Just to make it clear specifying the absolute (`/`) or home directory relative (`~/`) works as expected.

For example:
```toml
import = ["~/.config/alacritty/colors/colorscheme.toml"]
```
```
[0.000002750s] [INFO ] [alacritty] Welcome to Alacritty
[0.000336542s] [INFO ] [alacritty] Version 0.13.2 (bb8ea18)
[0.000810584s] [INFO ] [alacritty] Configuration files loaded from:
                                     "/Users/IzhakJakov/.config/alacritty/alacritty.toml"
                                     "/Users/IzhakJakov/.config/alacritty/colors/colorscheme.toml"
```

**Comment by chrisduerr** [comment]
Just to test, can you try with a `./` prefix?

**Comment by kchibisov** [comment]
Relative path support is not present in 0.13.2, use master if you need it.

**Comment by IzhakJakov** [comment]
@kchibisov,
> Relative path support is not present in 0.13.2, use master if you need it.

Thanks I'll wait for the next release.  
Just a thought, shouldn't the official [User Guide](https://alacritty.org/config-alacritty.html) represent what is currently available in the official release instead of the dev release (master) ?

**Comment by chrisduerr** [comment]
> Just a thought, shouldn't the official User Guide represent what is currently available in the official release instead of the dev release (master) ?

It generally should, yes. Will do so again after the next release.

**Comment by IzhakJakov** [comment]
Thank you!
