### ISSUE TITLE
I am unable to open Alacritty because "it is damaged or incomplete", despite uninstalling it and reinstalling it.

### ISSUE THREAD

**Issue by MrCherub** [alacritty/alacritty#8203]
After reinstalling Alacritty it continues to state that the application may be damaged or incomplete on macOS...
OS: macOS
Version: `alacritty --version` The latest version which won't even show up on terminal for some reason.
Linux/BSD: X11/Wayland, DE or Compositor and WM

**Comment by chrisduerr** [comment]
Not an Alacritty issue.
