### ISSUE TITLE
Alacritty Config Windows 11

### ISSUE THREAD

**Issue by 0xJWLabs** [alacritty/alacritty#8204]
We can't use symlink for config in alacritty? I wanna put it under .config/alacritty/alacritty.toml and symlink it to %APPDATA%\alacritty\alacritty.toml

### System

OS: Windows 11
Version: alacritty 0.13.2 (bb8ea18)

**Comment by chrisduerr** [comment]
Please describe your issue in detail. Symlinks work just fine with Alacritty.

**Comment by twhiting** [comment]
@0xJWLabs you might find that using a windows junction will work better. I'm not going to explain what a junction is, but take it as a more advanced symlink.

```cmd.exe
mklink /J C:\Users\<username>\.config\alacritty C:\Users\<username>\AppData\Roaming\alacritty
```
- The destination directory must exist.
- the source directory must **not** exist.

When its set up correctly you should see this when using `cmd.exe`.

![image](https://github.com/user-attachments/assets/60ea4b28-9645-495d-854e-4c216dfe91e6)

**Comment by chrisduerr** [comment]
Closing since there's been zero communication after over a week.
