### ISSUE TITLE
Searching for uppercase, accented letters, and symbols doesn't work in inline vi mode search (f/F/t/T)

### ISSUE THREAD

**Issue by AguirreIF** [alacritty/alacritty#8208]
Hi, searching for lowercase ascii [a-z] characters in inline vi mode search (f/F/t/T) works fine, but it doesn't work for:

  - Uppercase characters.
  - Accented letters (i.e: í, é, á, ü, ...) gets inserted instead of being searched.
  - Symbol characters (i.e.: :, ?, ¿, ¡, ¿), and / starts a search instead of being searched.

### System

OS: GNU/Linux Debian trixie/sid
Version: `alacritty 0.13.2`
Linux/BSD: X11 with awesomewm

Thanks for this great terminal!

**Comment by chrisduerr** [comment]
I think https://github.com/alacritty/alacritty/pull/8234 should fix all the raised issues.
