### ISSUE TITLE
[Feature Request] Add Keybind option to toggle window decorations

### ISSUE THREAD

**Issue by jivanyatra** [alacritty/alacritty#8211]
I notice in the [configuration documentation for window decoration](https://alacritty.org/config-alacritty.html#s11) that it doesn't seem to specify that Alacritty requires a restart for the changes to take effect.

I'd like to request an that can be assigned a keybind, e.g. "DecorationToggle", so that we can easily toggle the window decorations on and off.

I am unsure if that *actually* is possible without a restart on any platform(s), though. I, personally, am on Windows 11 and I don't see a way to use `alacritty msg` to try that method.

**Comment by chrisduerr** [comment]
> I notice in the configuration documentation for window decoration that it doesn't seem to specify that Alacritty requires a restart for the changes to take effect.

It should be part of the documentation; it requires a restart. Feel free to submit a patch if that bothers you, to me that doesn't come as much of a surprise.

**Comment by kchibisov** [comment]
We can also make it _reload_ decorations style.
