### ISSUE TITLE
[Question] Where is alacritty main loop?

### ISSUE THREAD

**Issue by music-cat-bread** [alacritty/alacritty#8219]
Hello.

Sorry for noob question, but I've been trying to analize how alacritty works and I got stuck on
```
let result = event_loop.run_app(self);
```
in alacritty/src/event.rs at line 179.

From there it steps into winit library and I don't understand where it later returns to alacritty event loop, which I was not able to find.

Again very sorry for noob question.

**Comment by kchibisov** [comment]
Winit calls our state from there and we draw things. Look into winit examples, alacritty is not different here in any way.
