### ISSUE TITLE
Prevent consuming of binding to send the signal to bash too

### ISSUE THREAD

**Issue by Mathis-Aubry** [alacritty/alacritty#8224]
Hi,
I hope the title is clear enough, but if not here's an easy example of such behavior (keybindings.toml) :

```
[keyboard]
bindings = [
    { key = "D", mods = "Control", chars = "test"},
]
```

With this configuration, exiting my terminal now is impossible with Control-D
I'd like to do something on when this binding is pressed via alactritty but I'd also like it to still do what it should normally !
Thank you for reading me

### System

OS: Windows
Version: alacritty 0.13.2 (bb8ea18)

**Comment by kchibisov** [comment]
you can bind it multiple times, one to do what you want the other to do what it used to do.

**Comment by Mathis-Aubry** [comment]
@kchibisov This is not quite what I want to do, sending the combination of key again doesn't seem very good and even though I don't know how I would...

**Comment by kchibisov** [comment]
```toml
[keyboard]
bindings = [
    { key = "D", mods = "Control", chars = "test"},
    { key = "D", mods = "Control", chars = "\u0004"},
]
```

if you want something stateful, it's not possible. you can also use `ctrl+shift+d`, sends the same thing.

**Comment by Mathis-Aubry** [comment]
I don't understand, why this \u0004 how is this meant to send Ctrl-D again ?

**Comment by kchibisov** [comment]
'c-d' is `0x4`

**Comment by Mathis-Aubry** [comment]
how do you know ? Is there a table for this ?
I'd like to use it for more complex bindings is it possible ? 
Like Control Shift key?

**Comment by kchibisov** [comment]
https://en.wikipedia.org/wiki/Control_character

**Comment by Mathis-Aubry** [comment]
Thank you for your help. 
Ended up seeing it is not possible to send such complex key combinations, only the known and most useful ones that way
