### ISSUE TITLE
can't set "colors.cursor.text" through "alacritty msg"

### ISSUE THREAD

**Issue by cideM** [alacritty/alacritty#8225]
In `man 5 alacritty` the cursor section is explained like this:

```
       cursor = { text = "<string>", cursor = "<string>" }
           Colors which should be used to draw the terminal cursor.
           Allowed values are hexadecimal colors like #ff00ff, or CellForeground/CellBackground, which references the affected cell.
           Default: { text = "CellBackground", cursor = "CellForeground" }
```
 
but if I try to set the `text` value through `alacritty msg config -w -1 'colors.cursor.text="#CCCCCC"'` I get

```
[760.843138292s] [ERROR] [alacritty_log_window_config] Unable to override option 'colors.cursor.text="#CCCCCC"': Field "text" does not exist
```

what does work is `alacritty msg config -w -1 'colors.cursor.foreground="#CCCCCC"'` (and `background` respectively). I am not a Rust person but I took a quick Look at the source and it seems that `text` and `cursor` are [aliases](https://github.com/alacritty/alacritty/blob/master/alacritty/src/config/color.rs#L115-L119) and it's only the actual struct values that work. I don't know if this is a bug or if it's just not mentioned in the documentation.

```rust
    #[config(alias = "text")]
    pub foreground: CellRgb,
    #[config(alias = "cursor")]
    pub background: CellRgb,
```

### System

OS: macOS
Version: 0.13.2

**Comment by kchibisov** [comment]
In general, you can change the cursor with escape sequences.

**Comment by chrisduerr** [comment]
Aliases work just fine for me testing the latest master:

https://github.com/user-attachments/assets/1693b6de-dcd4-4996-b27f-a61ad7c54077

**Comment by cideM** [comment]
True, if I compile it from source it works. I'll raise this with `nixpkgs` then
