### ISSUE TITLE
Using SelectTab command inserts a character into the terminal

### ISSUE THREAD

**Issue by chirok11** [alacritty/alacritty#8228]
I added the following bindings to the configuration file.
When switching between tabs, the numbers 1 and 2 are inserted respectively

```
[[keyboard.bindings]]
action = "SelectTab1"
key = "1"
mods = "Command"

[[keyboard.bindings]]
action = "SelectTab2"
key = "2"
mods = "Command"
```

### System

OS: macOS
Version: alacritty 0.13.2 (bb8ea18)

**Comment by kchibisov** [comment]
Could you post `--print-events` while doing so?  I'd assume it does switch, but you just have garbage written?

**Comment by kchibisov** [comment]
Does it happen without any configuration? Since all of that is bound by default. Also, I don't see anything suspicious in this log.

**Comment by kchibisov** [comment]
Do you have some software running that could be doing input or is it all stock macOS?

And which macOS version is that?

**Comment by kchibisov** [comment]
yeah, I can not test this macOS version and I can not reproduce with stock stuff on macOS 12.
