### ISSUE TITLE
`alacritty migate` panic

### ISSUE THREAD

**Issue by greg-el** [alacritty/alacritty#8230]
Running `alacritty migrate` seems to panic, rather than migrate stuff. It appears to point to this indexing on the toml. https://github.com/alacritty/alacritty/blob/c032c89f1c457c3cf97dcda3f8367115fa5f66ea/alacritty/src/migrate/mod.rs#L137

### System

OS: Linux
Version: alacritty 0.14.0-dev (c032c89f)
Linux/BSD: Arch Linux 6.11.2-arch1-1, Wayland, Hyprland

### Logs

Crashes:

```rs
❯ alacritty migrate
[alacritty/src/migrate/mod.rs:174:9] &key = KeyMut {
    key: Key {
        key: "shell",
        repr: Some(
            "shell",
        ),
        leaf_decor: Decor {
            prefix: empty,
            suffix: empty,
        },
        dotted_decor: Decor {
            prefix: empty,
            suffix: empty,
        },
    },
}
thread 'main' panicked at alacritty/src/migrate/mod.rs:137:33:
index not found
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Font/Terminal size:
[Alacritty-2712427.log](https://github.com/user-attachments/files/17334656/Alacritty-2712427.log)

Keyboard and bindings:
[Alacritty-2716785.log](https://github.com/user-attachments/files/17334703/Alacritty-2716785.log)

**Comment by kchibisov** [comment]
share your configs?

**Comment by chrisduerr** [comment]
I can repro with an empty config.
