### ISSUE TITLE
GNOME 46.5: 200% Integer Scaling: Cursor Becomes Blurry Hovering Over Alacritty Window  (GNOME dev say its a client side issue)

### ISSUE THREAD

**Issue by the-burrito-triangle** [alacritty/alacritty#8233]
### System
OS: Linux, Fedora 40 Workstation
Version: alacritty 0.13.2
Linux/BSD:  wayland, GNOME 46.5

On a 28in, 4k monitor with 200% scaling using Fedora 40 (wayland / GNOME 46.5), the mouse cursor becomes blurry when hovering over an Alacritty terminal window. I've reported the issue upstream to GNOME Mutter and the dev said that the issue is client side:

https://gitlab.gnome.org/GNOME/mutter/-/issues/3740#note_2244564

>  This is a client side issue. The relevant part from env WAYLAND_DEBUG=1 alacritty when run with 2x integer scaling:
> 
> [1000615.178] {Default Queue}  -> wl_shm_pool#58.create_buffer(new id wl_buffer#52, 3328, 24, 24, 96, 0)
> [1000615.252] {Default Queue}  -> wl_surface#19.set_buffer_scale(1)
> [1000615.284] {Default Queue}  -> wl_surface#19.attach(wl_buffer#52, 0, 0)
> [1000615.317] {Default Queue}  -> wl_surface#19.damage_buffer(0, 0, 24, 24)
> [1000615.385] {Default Queue}  -> wl_pointer#20.set_cursor(585093, wl_surface#19, 6, 13)
>
> So it is creating the cursor surface with a 1x buffer, that then has to be scaled up by the compositor to be at the correct size for a 2x scaled display. This is what makes it look blurry. The content of the window itself uses 2x buffers, so those look sharp.

It would be awesome to get this fixed for people who have high DPI displays.

**Comment by kchibisov** [comment]
provide the full `WAYLAND_DEBUG=1 alacritty` log.

**Comment by kchibisov** [comment]
Not required, it's not our bug https://gitlab.gnome.org/GNOME/mutter/-/issues/3608

**Comment by the-burrito-triangle** [comment]
Oh dang! I didn't realize how deep this rabbit hole went... Looks like it _was_ a mutter bug after all! Thanks kchibisov!

**Comment by the-burrito-triangle** [comment]
For anyone else having this issue, I've found a workaround from issue [3423](https://gitlab.gnome.org/GNOME/mutter/-/issues/3423):

Launching Alacritty with NO_POINTER_VIEWPORT=1 fixes the blurry cursor issue with GNOME 46.

**Comment by kchibisov** [comment]
We don't use this variable since we're not gtk so maybe you tested something wrongly.
