### ISSUE TITLE
box appears above fcitx5 pre-edited text

### ISSUE THREAD

**Issue by purejoy** [alacritty/alacritty#8238]
### System

OS: Gentoo Linux
Version: 0.13.2
Linux/BSD:  Wayland Plasma 6.2

Not sure if this is the right place to post this, but after testing other apps that don't seem to have this problem. 
When using Fcitx5 to input Chinese, there is always a block box at the head of the pre-edited text, how to remove or hide it?
![2024-10-14_11-14](https://github.com/user-attachments/assets/c349c911-d33b-411e-ab3f-bb1bddeb5060)

**Comment by kchibisov** [comment]
that's the cursor that your IME indicates. Usually when it's at the last position of the word it's not shown.

**Comment by chrisduerr** [comment]
@kchibisov Feel free to close if you think this is an IME bug.

**Comment by kchibisov** [comment]
Need `alacritty --print-events` to say for sure.

**Comment by purejoy** [comment]
> Need `alacritty --print-events` to say for sure.
Thanks! Here's the log.
[alacritty.log](https://github.com/user-attachments/files/17365162/alacritty.log)

**Comment by kchibisov** [comment]
@purejoy how does it look inside the e.g. `konsole` or `gnome-terminal` if you have any of them around?


Basically IME says that the cursor is from start to end, and yes we just draw it for the start of the editing area.

**Comment by kchibisov** [comment]
I've opened https://github.com/alacritty/alacritty/pull/8239 which should make it look like on a comment with 元気。You'll just have the same hollow block cursor around all your string since IME reports that you have cursor(selection) from start to finish.

That's how other terminals I've tested show it, though, maybe not vte ones.

**Comment by purejoy** [comment]
> @purejoy how does it look inside the e.g. `konsole` or `gnome-terminal` if you have any of them around?
> 
> Basically IME says that the cursor is from start to end, and yes we just draw it for the start of the editing area.

Typing Chinese in Konsole appears normal, without this issue.
![2024-10-15_09-26](https://github.com/user-attachments/assets/28383a27-dc7b-4dd5-8743-9aaff23ff351)

**Comment by kchibisov** [comment]
Yeah, so they all select the text (just differently). Our block thing you see is the selection.
