### ISSUE TITLE
Feature request: Neovim-like "cursorline" option

### ISSUE THREAD

**Issue by hakantr** [alacritty/alacritty#8240]
Hi Alacritty developers,

I would like to request the addition of a Neovim-like "cursorline" option to Alacritty. This option would highlight the entire row where the cursor is currently located, similar to the `cursorline` option in Neovim.

Alacritty's current `line_indicator` setting provides a similar visual guide, but it only highlights a portion of the row with a thin line. A full row highlight, like Neovim's `cursorline`, would be more visually prominent and easier to track, especially when working with long lines of code or text.

This feature would offer several benefits:

* **Improved visibility:**  Make it easier to locate the cursor within a dense block of text.
* **Consistency with Neovim:**  Provide a familiar experience for users who also use Neovim.
* **Customization:** Allow users to customize the color and style of the cursorline highlight.

Thanks,

**Comment by kchibisov** [comment]
The application you edit in should do that. Alacritty just renders characters. The only place where it could be applicable is the alacritty's builtin Vi mode.

For shell, just use the shell hotkey to open in the editor.
