### ISSUE TITLE
Unable to watch config file: Too many open files (os error 24)

### ISSUE THREAD

**Issue by depesz** [alacritty/alacritty#8245]
### System

OS: Linux Debian
Version: 0.13.2
Linux/BSD: X11 with KDE Plasma 5.27

### Logs

Log file:

```
=$ cat /tmp/Alacritty-147863.log
[0.000202933s] [ERROR] [alacritty] Unable to watch config file: Too many open files (os error 24)
```

Based on some other bug reports I checked my notify limits, and number of open files:

```
=$ cat /proc/sys/fs/inotify/max_user_watches
5000000

=$ sudo lsof -n | wc -l
lsof: WARNING: can't stat() fuse.portal file system /run/user/1000/doc
      Output information may be incomplete.
1198135
```

What can I do about it? I don't care about watching config file. I just want to be able to use my terminal without ugly 2 lines of red text.

**Comment by kchibisov** [comment]
You can disable it in the config `live_config_reload = false`.

**Comment by depesz** [comment]
Thanks, that helped.
