### ISSUE TITLE
`Control-NUMBER` not working in tmux

### ISSUE THREAD

**Issue by raaymax** [alacritty/alacritty#8254]
When using neovim with tmux keys `Control-NUMBER` are just NUMBERS which makes using nvim difficult..

### System

OS: macOS
Version: alacritty 0.13.2 (bb8ea18)
tmux 3.5a
NVIM v0.10.1

### Logs
Keyboard and bindings: `alacritty --print-events`
[alacritty-print-events.log](https://github.com/user-attachments/files/17435828/alacritty-print-events.log)

**Comment by chrisduerr** [comment]
Working as intended.

**Comment by raaymax** [comment]
That answer was not very useful.
I just tried Hyper, Kitty and iTerm2 and the problem not exist in any of those.

**Comment by raaymax** [comment]
ok, found it. It was already mentioned under different keywords that I was looking for.
Linking here for reference https://github.com/alacritty/alacritty/issues/8038
