### ISSUE TITLE
Alacritty V0.13.2 MacOS Not verified by MacOS can't execute

### ISSUE THREAD

**Issue by DMunkei** [alacritty/alacritty#8259]
Regardless if download the `.dmg` file and install it or try with `brew install alacritty` I get an error mesasge that I can't launch the application since it hasn't been verified by Apple. This is my work PC that is managed using`Microsoft Intune`. Is there any workaround that someone knows of? 

The weird thing is, I had Alacritty installed on the _2nd of september_ this year and working until I decided _yesterday_ to reinstall it using `Homebrew` prior to that, it was installed via the `.dmg` file directly. Has anything changed in the span of a month...?
![image](https://github.com/user-attachments/assets/8321a566-348a-404c-b05b-cfe6ccf10080)

Both `Homebrew` and the `.dmg` file were for the `0.13.2` version.
### System
OS: macOS Apple M1 Pro

### Alacritty
Version: 0.13.2

**Comment by chrisduerr** [comment]
>  This is my work PC that is managed usingMicrosoft Intune. Is there any workaround that someone knows of?

You can try self-signing, instructions for that should be available online. Generally on a sufficiently enough locked down system, you could also just be SoL.

**Comment by nixpulvis** [comment]
Perhaps simply removing the qurentine will be enough?
