### ISSUE TITLE
TOML Syntax to disable URL launching

### ISSUE THREAD

**Issue by zohassadar** [alacritty/alacritty#8260]
I don't want URLs to be clickable in the terminal.

I've found examples of how to set launcher to None for the yaml syntax, but cannot find any documentation for the equivalent in the toml syntax.  How can URL launching be disabled in the toml config?

**Comment by chrisduerr** [comment]
If you can't figure that out, I recommend a terminal emulator with a GUI config.

**Comment by nixpulvis** [comment]
So I opened the [alacritty config docs](https://alacritty.org/config-alacritty.html) and ctrl-f'd "url" which only matches on the `Open` action. So I'm very sympathetic to this issue.

It's only because I've been around the block that I happen to know that URLs are implemented as hints. If you happened to search for "hyperlink" you might find it.

Finally, unless I'm being stupid, the following config doesn't work to disable the hint entirely, when I expected it to:

```toml
[hints]
enabled = []
```

So @chrisduerr would you mind enlightening us?

**Comment by chrisduerr** [comment]
> But, unless I'm being stupid, the following config doesn't work to disable the hint entirely, when I expected it to:

You're probably being stupid, it works just fine for me. Make sure you're not running something like `tmux` that does its own link highlighting.

With how easily accessible information is, there's really no excuse to open an issue if you have the solution in YAML and just need it translated to TOML.

**Comment by nixpulvis** [comment]
@chrisduerr I'm not using anything like `tmux` and I'm can't seem to find the YAML examples the OP mentions. Of course I'm using TOML (as shown in the configuration I expected to work).

> I also tried copying and pasting the default hint and simply disabling the mouse, but that didn't seem to overwrite the default.

Could you please share how you made it work for you?

**Comment by nixpulvis** [comment]
OK, I think I might know what's going on. I have three TOML files, the main `alacritty.toml` and then two imports. It seems when the imports are loaded a new default `hints` section is created and then merged over the existing hints.

@chrisduerr perhaps you can replicate this issue now?

**Comment by chrisduerr** [comment]
> perhaps you can replicate this issue now?

No. I can disable hints just fine both from imports and from the main config.

**Comment by nixpulvis** [comment]
Oh god damn it. I was updating my dotfiles and forgot about a symlink... So I had an old hint I didn't realize was being imported. Sorry for the confusion.

@zohassadar my original comment's configuration does work. I don't know why @chrisduerr couldn't have said that was expected to work, but he has a knack for making people discover things for themselves.

Hope this helps :man_shrugging:

**Comment by zohassadar** [comment]
The yaml examples I found were all for the deprecated mouse.url.launcher configuration element.  I had made the mistaken assumption that I was translating to toml incorrectly when getting errors or warnings of unused config keys.  I probably would have been better served had I elaborated on what I had found and what I had tried.  After chrisduerr's initial response I kept digging and discovered that I had found deprecated examples and learned about the hints section.  I was indeed able to discover how to get the desired behavior for myself.  

I also realized after asking my question that the information I was looking for was in #5246, an issue I had looked through previously, but I was hung up on looking for config that involved the keyword "launcher".  

Thank you for your assistance @nixpulvis, your example to disable is simpler than what I had come up.  I appreciate the different perspective.

I will most certainly dig much further before opening another issue for this project :)

**Comment by kchibisov** [comment]
I'd suggest to search for information in the documentation rather than github issues. You should have man pages and you also have docs on `alacritty.org` for various releases.

**Comment by designstorming** [comment]
> > But, unless I'm being stupid, the following config doesn't work to disable the hint entirely, when I expected it to:
> 
> 
> 
> You're probably being stupid, it works just fine for me. Make sure you're not running something like `tmux` that does its own link highlighting.
> 
> 
> 
> With how easily accessible information is, there's really no excuse to open an issue if you have the solution in YAML and just need it translated to TOML. 

You, kid, are toxic AF. Instead of providing the solution, you're offending people. I sincerely hope you get f'd-off when YOU need something in the future. Over and out.
