### ISSUE TITLE
Alacritty as external vs code terminal

### ISSUE THREAD

**Issue by smesarubio** [alacritty/alacritty#8261]
### System

OS: macOS
Version: alacritty 0.13.2 (bb8ea18)

### Logs

When opening alacritty from vs code (cmd+shift+c) with this setting:
"terminal.external.osxExec": "Alacritty.app"

im getting 
The document “DOCUMENT” could not be opened. Alacritty cannot open files in the “folder” format.

**Comment by chrisduerr** [comment]
Sounds like a VSCode issue to me. Alacritty has nothing to do with some random application trying to open it.
