### ISSUE TITLE
ABC - Extended keyboard unable to type symbols in Alacritty only.

### ISSUE THREAD

**Issue by properCase** [alacritty/alacritty#8271]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: macOS
Version: 0.13.2 (bb8ea18)

### Logs

I am using the `ABC - Extended` keyboard which allows me to press option + u to type the umlaut, and then u to generate the ü or option + e and e to type é.  This works in every application except not Alacritty for some reason.  The alt+letter combo does nothing.

It works in iTerm2 as well (in case that matters)

**Comment by chrisduerr** [comment]
Can you test the latest version please?

**Comment by properCase** [comment]
It is not working still.  the modifier key doesn't actually type the modifier.  I've included the iTerm2 functionality so that you can see what I'm expecting.
![2024-10-29_21-56-18 (1)](https://github.com/user-attachments/assets/54fc0bb3-0649-4e4c-939c-35722b77aca5)
