### ISSUE TITLE
Config warning: shell has been deprecated; use terminal.shell

### ISSUE THREAD

**Issue by ankushT369** [alacritty/alacritty#8272]
### System

OS: Linux
Version: `alacritty 0.14.0 (22a44757)`
Linux: X11, i3

### Logs

Crashes: STDERR
[0.000297252s] [WARN ] [alacritty_config_derive] Config warning: shell has been deprecated; use terminal.shell instead
                                                 Use `alacritty migrate` to automatically resolve it

**Comment by chrisduerr** [comment]
shell has been deprecated; use terminal.shell

Use alacritty migrate to automatically resolve it
