### ISSUE TITLE
ANSI Escape Code for dimmed style / reduced brightness not working?

### ISSUE THREAD

**Issue by chris4prez** [alacritty/alacritty#8280]
When testing ANSI escape code functionality it appears dimmed style / reduced brightness ( \e[2m ) is not supported.

```bash
echo -e '\e[1mBold\e[22m'
echo -e '\e[2mDimmed\e[22m'
echo -e '\e[3mItalic\e[23m'
echo -e '\e[4mUnderlined\e[24m'
echo -e '\e[4:3mCurly Underlined\e[4:0m'
echo -e '\e[4:3m\e[58;2;240;143;104mColored Curly Underlined\e[59m\e[4:0m'
```

Is or should dimmed be supported by alacritty, especially when items like curly underline and colored curly underline work? Dimmed is the only item on the list above not performing as expected. When I run on other terminals with same font dimmed style is functioning.

### System

OS: Linux - Fedora 41
Version: alacritty 0.13.2
Linux/BSD: Wayland

### Logs

Font/Terminal size: JetBrainsMonoNF

PTY dimensions: 32 x 100

**Comment by chrisduerr** [comment]
It works.

**Comment by chris4prez** [comment]
> You may have dimmed style defined in your color scheme to the same values.
> 
> ![image](https://private-user-images.githubusercontent.com/27620401/381719847-cffcb111-429e-4d48-b829-b08279afa672.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMjAxNTYsIm5iZiI6MTczMDMxOTg1NiwicGF0aCI6Ii8yNzYyMDQwMS8zODE3MTk4NDctY2ZmY2IxMTEtNDI5ZS00ZDQ4LWI4MjktYjA4Mjc5YWZhNjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDIwMjQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwZDZlNWU2MDViMTYyNGYxNTVjN2E2NDc5YmZjNDgzZTI5MWJjYzVhZjE1MTIwMzYxYjY5YmQ2Yjg2YThiZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Bh7TVgbeHrwBaFlJKv6ZTYZQn8d_ok1zXzUmB8CtZQE)

Thank you, did not even think to check the theme, that's the issue!
