### ISSUE TITLE
Feature Request: Add option to cli create-window command to focus

### ISSUE THREAD

**Issue by chipschipschips** [alacritty/alacritty#8282]
### Feature description

Allow windows created with `alacritty msg create-window` to be focused.

### Why?

Long time iTerm2 user, trying out Alacritty. Part of my workflow is to create terminal windows on demand, regardless of which app I'm currently using. I want the new window to be focused after creation. I am using a Raycast script command to do this: if Alacritty is already running, run `alacritty msg create-window`; else just start Alacritty with `open -a /Applications/Alacritty.app`.

In the case that Alacrity is running but doesn't have focus, the window created with the `create-window` cli command will also not have focus. It may also be created beneath whatever is the currently active window. This isn't ideal since I then have to go hunt for the newly created window.

For comparison, when creating a new window with iTerm2, the newly created window is in focus automatically.

### System

OS: macOS
Version: alacritty 0.14.0 (22a4475)

**Comment by chrisduerr** [comment]
A newly created window should automatically receive focus. If it doesn't your window manager is broken.
