### ISSUE TITLE
Alacritty doesn't respect the default cursor theme on GNOME Wayland

### ISSUE THREAD

**Issue by dpejoh** [alacritty/alacritty#8284]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Ubuntu Linux 24.10
Alacritty Version: 0.13.2
GNOME 47 on Wayland

[Screencast From 2024-11-01 16-30-23.webm](https://github.com/user-attachments/assets/1a0c90b0-4c5c-4ceb-a0fd-8750e77f77e2)

Alacritty doesn't respect my default cursor theme, and it shows a bad white cursor, I don't know if it a new problem or not because I started using Alacritty just yesterday

**Comment by kchibisov** [comment]
You set your cursor theme with `XCURSOR_THEME` to the one you're using.

**Comment by kchibisov** [comment]
Maybe need a `XCURSOR_SIZE` as well.

In any way it's not our issue.
