### ISSUE TITLE
Improper rendering of emdash

### ISSUE THREAD

**Issue by mathstuf** [alacritty/alacritty#829]
Which operating system does the issue occur on?

Linux/X11 using 6916537858d12e02478d618339d1b9f0e73a677a.

`alacritty` is rendering an emdash improperly:

`alacritty`:

![2017-10-10-103147_151x25_scrot](https://user-images.githubusercontent.com/97253/31392210-b0278e02-ada6-11e7-82b0-620a6e1a3518.png)

`urxvt256c`:

![2017-10-10-103256_197x28_scrot](https://user-images.githubusercontent.com/97253/31392216-b481d3cc-ada6-11e7-8827-7157579f64c3.png)

The screenshot comes from attaching to the same `tmux` session through two different terminals.

Here is a copy/past of the content: `(1.1*:—root@megas:~)`.

**Comment by chrisduerr** [comment]
Hey, sorry to stay silent for so long, but there have been some changes to how cell sizes are calculated, is this issue still present?

**Comment by jwilm** [comment]
I'm able to see this by pasting the text in. My guess is a font fallback problem

**Comment by chrisduerr** [comment]
Interesting, I wasn't able to reproduce it with my font. Could also be an issue with the wcwidth function not matching the font's reported cell width.

**Comment by jwilm** [comment]
Perhaps it's pulling an emdash from a non-monospace font? Maybe not a wcwidth issue in that case.

**Comment by mathstuf** [comment]
FWIW, yes, I'm still seeing this issue (commit 1adb5cb7fc05054197aa08e0d1fa957df94888ab). Somewhere along the line it got even worse too: the dash now takes up *3* cells.

**Comment by chrisduerr** [comment]
This is an issue with your font. If you want this to work nicely you need to make sure emdash is part of your primary font.

**Comment by Elfatih632** [comment]
Could you please stop sending me email 


Sent from Yahoo Mail for iPhone


On Tuesday, April 13, 2021, 5:39 AM, Christian Duerr ***@***.***> wrote:




This is an issue with your font. If you want this to work nicely you need to make sure emdash is part of your primary font.

**Comment by Elfatih632** [comment]
Stop sending me email please
