### ISSUE TITLE
Underline of selected links remains visible when moving mouse up to previous item

### ISSUE THREAD

**Issue by petricavalry** [alacritty/alacritty#8292]
Underline of selected links doesn't disappear when moving the mouse moves up to select item in previous adjacent line that contains links too.

![Mouse moves up](https://github.com/user-attachments/assets/3e1de19e-08f0-4f98-a8b6-f884bd73272a)

It should works good like mouse moving down.

![Mouse moves down](https://github.com/user-attachments/assets/a6bdc1a1-ff62-4399-8291-f81b0444523f)

### System

OS: Linux
Version: alacritty 0.14.0 (22a44757)
Linux/BSD: Wayland, [Sway](https://github.com/swaywm/sway)

### Logs

Crashes: None
Font/Terminal size: <https://paste.rs/LLhf3.txt>
Keyboard and bindings: <https://paste.rs/gvN6H.txt>

**Comment by kchibisov** [comment]
I'm pretty sure this is fixed on master.
