### ISSUE TITLE
Possibility to apply a specific window padding on each directions { top = <integer>, bottom = <integer>, etc. }

### ISSUE THREAD

**Issue by jeremyelalouf** [alacritty/alacritty#8295]
# Basic Observation

In terms of Alacritty customization, having the ability to apply padding to specific sides of the window could expand customization options.

## Current Customization Options

Currently, padding in Alacritty is applied only on both opposing sides. As specified in the documentation, padding can be set for the window using the x and y variables:

[padding](https://alacritty.org/config-alacritty.html#s9) = { x = <integer>, y = <integer> }

## Encountered Discomfort

Using Alacritty on macOS, I admit I appreciate minimalist designs 👀. With that in mind, I customized my terminal by setting decorations = "Transparent", and it looks just right.

However, as a Neovim user, opening the editor currently results in the following layout:

<img width="1221" alt="Screenshot 2024-11-06 at 2 47 32 PM" src="https://github.com/user-attachments/assets/808abef3-6b69-469a-8b2f-1b2975884779">

What a big awful bar at the bottom…

## Proposed Solution

Adding the option to set different padding values for the top and bottom, for example, could provide greater flexibility. It could also be helpful to apply this feature horizontally.

Example configuration:

```window:
  padding:
    top: 24
    bottom: 12
```

**Comment by kchibisov** [comment]
#6444
