### ISSUE TITLE
Support for EInk: add shortcut to switch to gray color.

### ISSUE THREAD

**Issue by water-chika** [alacritty/alacritty#8297]

**Comment by kchibisov** [comment]
such coloring is a property of the display stack. if you want to change colors on the fly, you have all the tools available for that.

if there's a specific issue, like something doesn't start, open a new issue.

**Comment by water-chika** [comment]
But if the cell background color is red, foreground is blue,after switch to gray, it will be all same color.
I wish background always different with foreground on EInk monitor.

**Comment by chrisduerr** [comment]
You're free to change your colors.
