### ISSUE TITLE
US International layout dead keys don't work

### ISSUE THREAD

**Issue by wolicodes** [alacritty/alacritty#8299]
This layout is one where you press the key (let's say ~) and it buffers it until you press either space to insert the character, or if you type n, it would give you ñ. It works on pretty much every application except Alacritty (and Kitty), the dead keys just do nothing.

### System

OS: Archlinux, X11, Xfce, xfwm. No extra input method were installed. The system is configured to use US Intl, and Xfce is configured to use system config.
Version: alacritty 0.14.0 (22a44757)
Extra info:

`cat /etc/X11/xorg.conf.d/00-keyboard.conf`
```
# Written by systemd-localed(8), read by systemd-localed and Xorg. It's
# probably wise not to edit this file manually. Use localectl(1) to
# update this file.
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "us"
        Option "XkbModel" "pc105"
        Option "XkbVariant" "intl"
EndSection
```

`setxkbmap -query`
```
rules:      evdev
model:      pc105
layout:     us(intl)
```

### Logs

`alacritty --print-events`

```
[15.467105603s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(Backquote), logical_key: Unidentified(Xkb(0xFE50)), text: None, location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: None, key_without_modifiers: Unidentified(Xkb(0xFE50)) } }, is_synthetic: false }
```

**Comment by chrisduerr** [comment]
@kchibisov Do you know if dead keys should work on X11? I think there are some known issues with Wayland, but they generally do work?

**Comment by kchibisov** [comment]
I'm pretty sure it's a locale issue here. Ensure that your one is `en_US.UTF-8` or other `.UTF-8` locale.

**Comment by wolicodes** [comment]
> I'm pretty sure it's a locale issue here. Ensure that your one is `en_US.UTF-8` or other `.UTF-8` locale.

It's not a local issue:

`$ locale`

```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by kchibisov** [comment]
By any other application do you mean GTK by any chance, GTK 3 has a special handling of certain dead keys, etc?

I've closed not only because of _locale_, btw, but because you've mentioned that kitty also doesn't work, where we have pretty much the same dead keys input setup, which implies that it's either locale, or you rely on some behavior in your other apps that default libxkbcommon isn't doing.

**Comment by wolicodes** [comment]
Ah yes it looks like GTK3 because I have the underlined dead key character showing (on other apps).
Is it fixable?

**Comment by kchibisov** [comment]
I'd state that gtk 3 has different handling of certain things and made them like in other apps since gtk4.

In general, dead keys do work in alacritty, there's just no preview, so if you type the sequence it'll get inserted.

**Comment by wolicodes** [comment]
It doesn't get inserted in my case

**Comment by kchibisov** [comment]
if it's not inserted in other apps, it could be a gtk specific sequence then.

**Comment by wolicodes** [comment]
it IS inserted in other apps, just not alacritty/kitty.

**Comment by kchibisov** [comment]
other apps not being gtk3 or qt are only considered here though, if you have 10 gtk apps ofc they will work, since you're used to gtk behavior.

**Comment by wolicodes** [comment]
Solved the issue by installing ibus.
