### ISSUE TITLE
US International layout dead keys don't work

### ISSUE THREAD

**Issue by wolicodes** [alacritty/alacritty#8300]
# Re-opening because #8299  was closed abruptly before it was solved, and before I got a chance to confirm anything. I added locale info which wasn't the problem.

This layout is one where you press the key (let's say ~) and it buffers it until you press either space to insert the character, or if you type n, it would give you ñ. It works on pretty much every application except Alacritty (and Kitty), the dead keys just do nothing.

### System

OS: Archlinux, X11, Xfce, xfwm. No extra input method were installed. The system is configured to use US Intl, and Xfce is configured to use system config. Same issue on Gnome.
Version: alacritty 0.14.0 (22a44757)
Extra info:

`cat /etc/X11/xorg.conf.d/00-keyboard.conf`
```
# Written by systemd-localed(8), read by systemd-localed and Xorg. It's
# probably wise not to edit this file manually. Use localectl(1) to
# update this file.
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "us"
        Option "XkbModel" "pc105"
        Option "XkbVariant" "intl"
EndSection
```

`setxkbmap -query`
```
rules:      evdev
model:      pc105
layout:     us(intl)
```

`$ locale`

```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

### Logs

`alacritty --print-events`

```
[15.467105603s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(X(DeviceId(3))), event: KeyEvent { physical_key: Code(Backquote), logical_key: Unidentified(Xkb(0xFE50)), text: None, location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: None, key_without_modifiers: Unidentified(Xkb(0xFE50)) } }, is_synthetic: false }
```

**Comment by chrisduerr** [comment]
Don't open new issues, we can always reopen existing ones this is just spam.
