### ISSUE TITLE
[windows] Environment variable expansion 

### ISSUE THREAD

**Issue by jlee38266** [alacritty/alacritty#8303]
When importing themes from alacritty-theme repository using Windows environment variables (e.g., %APPDATA%), Alacritty fails to expand them, resulting in "Config import not found" errors.

### System

- **OS**: Windows 11
- **Alacritty Version**: 0.13.2 (bb8ea18)
- **Config Location**: %APPDATA%/alacritty/alacritty.toml
- **Theme Source**: [alacritty-theme](https://github.com/alacritty/alacritty-theme)

## Expected Behavior
Alacritty should expand Windows environment variables in import paths when using official themes from alacritty-theme repository.

## Current Behavior
Alacritty treats %APPDATA% as a literal string instead of expanding it to the actual path.

Note: Using absolute path works fine:
```toml
import = ["C:/Users/<username>/AppData/Roaming/alacritty/themes/themes/tokyo_night.toml"]
```

## Steps to Reproduce
1. Clone alacritty-theme repository to `%APPDATA%/alacritty/themes`
2. Add theme import to alacritty.toml:
  ```toml
  import = ["%APPDATA%/alacritty/themes/themes/tokyo_night.toml"]
```

### Logs

```
[0.004659100s] [INFO ] [alacritty_config_derive] Config import not found:
                                        "%APPDATA%/alacritty/themes/themes/tokyo_night.toml"
```

I believe this is specifically related to how Alacritty handles Windows environment variables in the config file, rather than a shell-specific issue.

**Comment by kchibisov** [comment]
env variables being not supported is intended.

You can use relative path to achieve what you want.

`import = [ "themes/themes/tokyo_night.toml" ]`

**Comment by jlee38266** [comment]
Could you please clarify how relative paths should be used in this case?

```
[185.761276800s] [INFO ] [alacritty_config_derive] Config import not found: "themes/themes/tokyo_night.toml"
```

**Comment by kchibisov** [comment]
They are relative to the config directory. Though, you need to update to 0.14.0 for them to work.
