### ISSUE TITLE
changes in #7095 not reflected in https://alacritty.org/config-alacritty.html

### ISSUE THREAD

**Issue by manoharnayak** [alacritty/alacritty#8305]
[terminal] is not a valid section, and [shell] should have its own section. [general] is also not needed as a section but the key-value pairs are added before the first [section]

I only understood these after extensive searching and then reading the man 5 Alacritty. I was first using https://alacritty.org/config-alacritty.html to orient myself, and was heavily misled. Please update it to reflect the man pages. Thanks for your awesome work :)

### System

OS: Linux
Version: alacritty 0.13.2
Linux/BSD: Wayland

### Logs
After fixing it, the logs disappeared, but it basically told me that some configs like shell.program (which i took from the .org website documents) was not being used.

**Comment by kchibisov** [comment]
>Version: alacritty 0.13.2

![image](https://github.com/user-attachments/assets/daab4a67-ea79-4875-8c9c-cc85841aa577)

please select the right thing when viewing the docs.
