### ISSUE TITLE
Scaling text with Ctrl-+/- is irreversible on a multi-DPI setup

### ISSUE THREAD

**Issue by GregTheMadMonk** [alacritty/alacritty#8309]
On my system, I have noticed that after I resize the font in the terminal on my main monitor, I cannot go back to its original size by performing the same amount of "opposite" resizes (simplest case: scale up - then scale down). I've figured out that it boils down to this line
https://github.com/alacritty/alacritty/blob/1063706f8e8a84139e5d2b464a4978e9d840ea17/alacritty/src/event.rs#L876
since for my main monitor the `self.display.font_size.as_px()` is not an integer value, and using `.round()` on it essentially ensures that I cannot go back to the original font size since all other resizes will lead to an integer value again.

If a fractional `font_size` value is allowed (apparently it is, or it's a bug), then the `round()` here should be omitted. Or maybe there is a smarter solution if the fractional value is a result of changing some font size by a fractional multiplier.

### System

OS: Linux
Version: alacritty 0.15.0-dev (1063706f)
Linux/BSD: X11

**Comment by chrisduerr** [comment]
Why not just use Ctrl+0?

**Comment by GregTheMadMonk** [comment]
Why not have two opposite actions effectively cancel each other, like they intuitively should (and do, when the font size is integer)?

**Comment by chrisduerr** [comment]
I don't see a problem either way. Any action is reversible so there's no problem to me. Fonts generally work best at integer scale, but I don't care too much about the `.round()`.

**Comment by GregTheMadMonk** [comment]
> Fonts generally work best at integer scale

Then why does alacritty make it a fraction?!

Whatever, have as many bugs in your app as you want

**Comment by kchibisov** [comment]
The point of increase font size actions is to increase it by `px` stepping through values, where font should render better (integer px values, that's how 99% of the software works).

You can reset the font size with `ctrl+0` to the config value.

**Comment by GregTheMadMonk** [comment]
The only thing it actually does is break font aspect ratio. See these two screenshots of a window before/after C^+/C^- ("after" is the wider one in case you're wondering)
![image](https://github.com/user-attachments/assets/c9e00a6e-60ec-4a34-9514-29d1bacb2609)

My `alacritty.toml` has

```toml
[font]
size=12
```

\- an integer value, but Alacritty at some point _decides_ that it's better converted to a fractional `18.6666666` (which I'm not complaining about because, unlike 19 or 18, it looks more correct). By "correct" I mean that it is the intended way the font should be displayed as shown here by me manually typing the same text with the same font (Iosevka Nerd Font Mono if you want to try it yourself) in Gimp with font size 18, bright red color and default spacing values:

![image](https://github.com/user-attachments/assets/318ee1d4-e517-4de8-8c9a-a04cf9b11b63)


On the other hand, here is the result of the same sequence of inputs on my second monitor:
![image](https://github.com/user-attachments/assets/0cffd21b-bbf5-422e-bd0d-c714da1768c2)
Where all iterations have integer scaling to begin with and which looks just like fractional-scaled font on my main monitor.

`.round()`'ing the value displays text with a different aspect ratio from the correct and I don't know how anyone could argue that this is intended behavior.

**Comment by kchibisov** [comment]
If you do `WINIT_X11_SCALE_FACTOR=1 alacritty` and try setting fonts in it, does it get better when it comes to font sizes, etc?

**Comment by kchibisov** [comment]
Also, just to make it clear, `ctrl+0` doesn't use any rounding and will use the exact font size you had in your configuration, so you can rollback just with it by passing the issue of integer steps.

**Comment by kchibisov** [comment]
We allow precise font size in the config, but then we change it only by 1px steps, since they render better at integer steps and were designed around them, mostly all software does it the same.

However we allow specifying fractional size, since in the config it's in _pt_, not px, and pt is fractional. You can also dynamically change it during runtime with `alacritty msg config font.size=10.3333` if you really want to change the size to something you use for presentation, and then reset back to normal with `alacritty msg config -r`.

**Comment by GregTheMadMonk** [comment]
I'm really sorry to bother again after reporting that everything looks fine, and idk how I missed it, but: the issue _persists_ with `WINIT_X11_SCALE_FACTOR=1`:

![bug](https://github.com/user-attachments/assets/0fc3f3d9-6db5-4179-bc5d-b5915b813c25)
