### ISSUE TITLE
Padding in nvim

### ISSUE THREAD

**Issue by jeevithakannan2** [alacritty/alacritty#8313]
There is padding like gap around nvim. This doesn't happen with st or foot terminal.

![image](https://github.com/user-attachments/assets/dc2ee0de-92d7-4f6d-a28b-bd81a5525f68)

In the image you can see a slight gap ( Black color )in the right side and a big black bar below.

I have tried setting the padding x and y to 0 still no progress.

### System

OS: Linux
Version: alacritty 0.14.0 (22a44757)
Linux: X11/DWM

**Comment by kchibisov** [comment]
padding is normal and present in any other terminal to compensate the fact that `height % cell_size != 0`, however you may not see it if your font fit exact.

You can make the padding `dynamic` to make evenly spread around or you can set a matching theme in your terminal.
