### ISSUE TITLE
alt + enter causes weird behavior

### ISSUE THREAD

**Issue by IbrahimHindawi** [alacritty/alacritty#8323]
### System

OS: Windows
Version: `alacritty --version` 10.0.19045.5131
NVidia 566.14

### Logs

I updated my alacritty and my nvidia GPU driver and now my alacritty is busted when I press alt + enter, the screen goes black and I even got a BSOD once. It could be my laptop tbh its quite janky.

**Comment by chrisduerr** [comment]
> I updated my alacritty and my nvidia GPU driver

Driver issue.

**Comment by IbrahimHindawi** [comment]
solution? 😅

**Comment by kchibisov** [comment]
downgrade driver?

**Comment by IbrahimHindawi** [comment]
well, I downgraded (not by many versions) and it was still there, there after a while it was magically fixed. Windows right?
