### ISSUE TITLE
osc52 does not work

### ISSUE THREAD

**Issue by ilan-schemoul** [alacritty/alacritty#8324]
Connect ssh to a server
Type ~ ⟩ printf $'\e]52;c;%s\a' "$(base64 <<<'hello world')"
Even without ssh you can do locally the same command the clipboard is untouched

### System

Ubuntu 22.04
alacritty 0.14.0-dev (d4f2f857)
~ ⟩ uname -r
6.8.0-48-generic

**Comment by kchibisov** [comment]
I'd assume that no tmux/zellij or wahtever is involved in this chain.

You can ensure the copy of via the `alacritty --print-events | grep Store`.
