### ISSUE TITLE
migrate - strange error message

### ISSUE THREAD

**Issue by tessus** [alacritty/alacritty#8330]
I started Alacritty on macOS and get the following warning at the bottom:

```
[WARN] Config warning: import has been deprecated; use general.import instead
use `alacritty migrate` to automatically resolve it
```

Then when I do that, I get the following:

```
$ alacritty migrate
Configuration file migration failed:
    "/Users/tessus/.config/alacritty/alacritty.toml": No such file or directory (os error 2)
```

However, this is absolutely wrong:

```
$ ll /Users/tessus/.config/alacritty/alacritty.toml
.rw-r--r-- 8,155 tessus staff 2024-07-20 17:57 /Users/tessus/.config/alacritty/alacritty.toml
```

### System

OS: macOS
Version: alacritty 0.14.0 (22a4475)

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: `alacritty -vv`
Keyboard and bindings: `alacritty --print-events`

**Comment by chrisduerr** [comment]
Can you share the full config? Are you making use of imports? Also why is your configuration file not writable, how is `alacritty migrate` supposed to work without it being writable?

**Comment by tessus** [comment]
I think I got this config a while back from the Net, since alacritty does not create a default config file, nor does it come with a template.

Of course I could share my config file, but I won't. I don't want to distract from the issue at hand.
I am sure I can manually fix the config somehow. This is not the issue I have opened. This issue is not about deprecated config options.

The issue is that alacritty told me to use `migrate`. When I do, alacritty tells me that the config file does not exist even though it does.

**Comment by tessus** [comment]
Why did you close this issue? Because I didn't send the config file, so that you can deflect and tell me how to change the config manually?
I guess you really do not understand the issue I have opened. 

Thanks for making the decision easy for me not to use alacritty. Have a great day!

**Comment by kchibisov** [comment]
>Because I didn't send the config file, so that you can deflect and tell me how to change the config manually?

So one can run import on it and see the exact error and do necessary debugging. Maybe you have weird import setup that we don't account for, so given you know better how to proceed and don't want to cooperate, ofc the issue is closed.

**Comment by KulikovIK** [comment]
My problem was that there was no file "**ayu_dark.toml**". If "**alacrity.toml**" has the "#install first color schemes from here" setting: https://github.com/alacritty/alacritty-theme ?tab=readme-ov-file" click on the link and make the settings

**Comment by kchibisov** [comment]
If some import is missing, that already got fixed, hence why we've asked about imports in the first place, since the logic was forgotten for toml while it was present for yaml.

**Comment by marcoobaid** [comment]
In case someone comes across this thread looking for a solution to the import issue stated at the beginning of this thread. The issue is most likely that you don't have **[general]** section above the import statement:

```
import = [
    "~/.config/alacritty/themes/themes/{theme}.toml"
]
```

This will trigger the warning below:

```
[WARN] Config warning: import has been deprecated; use general.import instead
use `alacritty migrate` to automatically resolve it.
```

However, if you run **alacrity migrate** as is, you will most likely encounter:

```
$ alacritty migrate
Configuration file migration failed:
    "/Users/user/.config/alacritty/alacritty.toml": No such file or directory (os error 2)

```

Simply add **[general]** above the import statement, or move import under [general], if it is already in alacritty.toml.

```
[general]
import = [
    "~/.config/alacritty/themes/themes/nord.toml"
]
```
