### ISSUE TITLE
Is there a way to configure 40-47 and 100-107 colors separately from 30-37 and 90-97?

### ISSUE THREAD

**Issue by nickkadutskyi** [alacritty/alacritty#8331]
I am creating my theme and trying to recreate IntelliJ terminal colors. I never saw this in other terminals but, apparently, IntelliJ has different colors for fg and bg for normal and bright ansi (4 bit) colors. See the screenshot for comparison (left Alacritty, right IntelliJ):
![CleanShot 2024-11-26 at 22 28 14@2x](https://github.com/user-attachments/assets/bcf06236-ac44-4221-a28c-07e02511827e)

Is there a way to do something like this in Alacritty?

### System
OS: macOS
Version: alacritty 0.14.0 (22a4475)

**Comment by nickkadutskyi** [comment]
I did research and turns out there isn't any terminal emulator that provides such feature except JetBrains IDEs.
So, I guess this should be a feature request.

**Comment by chrisduerr** [comment]
That's not how it works, no.
