### ISSUE TITLE
Unable to install Alacritty on Steam Deck (Immutable File-System)

### ISSUE THREAD

**Issue by Euphonit** [alacritty/alacritty#8333]
### System
Hardware: Valve Steam Deck 64GB LCD
OS: SteamOS 3 (Arch Linux Based)

### Issue
Because the Steam Deck does not ship with tools such as make or cmake and the Immutable File System prevents pacman from installing anything it means that when I clone source and run "cargo build --release" it is unable to compile and build the dependencies because the tools such as cmake and make do not exist on the system.

### Outputs
Output for "cargo build --release"
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

   Compiling shlex v1.3.0
error: could not compile `serde` (build script) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `proc-macro2` (build script) due to 1 previous error
error: could not compile `libc` (build script) due to 1 previous error
error: could not compile `rustix` (build script) due to 1 previous error

Output for running "sudo pacman -S cmake freetype2 fontconfig pkg-config make libxcb libxkbcommon python"

sudo pacman -S cmake freetype2 fontconfig pkg-config make libxcb libxkbcommon python
[sudo] password for deck: 
error: failed to init transaction (unable to lock database)
error: could not lock database: Read-only file system

### Closing Thoughts
I suppose there could be a way to do it by manually building every single dependency from their repos, or places such as the AUR, or using an alternative package manager such as Homebrew or Nix. I am really opening this issue to see if this has been thought of before and there is some easier solution than the potential solutions I talked about above.

**Comment by kchibisov** [comment]
It's not our problem if a particular system is vendor locked like that, ask them to package alacritty at this point, especially given that it's present in arch linux packages.

**Comment by kchibisov** [comment]
Maybe you can also mount filesystem as `rw` temporary though.

**Comment by nixpulvis** [comment]
Perhaps making use of OverlayFS even.

**Comment by chrisduerr** [comment]
Someone should write a tool to run applications with a custom root, maybe even encrypt all the data they write dynamically.
