### ISSUE TITLE
[FR]: Make it possible for mouse clipboard copying copy to the `CLIPBOARD` clipboard (not the `PRIMARY` one)

### ISSUE THREAD

**Issue by doronbehar** [alacritty/alacritty#8334]
So when I want to copy terminal output or whatever from Alacritty, I use the mouse to select text, and press <kbd>CTRL</kbd> while pressing the left mouse key. In order to actually paste the selection in a Firefox browser for example, I need to put it in the `CLIPBOARD` clipboard, so I use the command:

```
wl-paste --primary | wl-copy
```

It would have been great if it was possible to tell Alacritty to put the selection in the `CLIPBOARD` selection by default, or to put the selection in both clipboards.

### System

OS: NixOS
Version: alacritty 0.14.0
Linux/BSD: Wayland, GNOME

**Comment by kchibisov** [comment]
```
[selection]
save_to_clipboard = true
```

**Comment by doronbehar** [comment]
I read that option, but the current documentation of it seems to state the opposite. Hence: https://github.com/alacritty/alacritty/pull/8336
