### ISSUE TITLE
Config error should specify where rule is broken

### ISSUE THREAD

**Issue by hughrawlinson** [alacritty/alacritty#8338]
I ran alacritty migrate to get a toml copy of my configuration. There are errors in my configuration; this issue isn't about the specific errors, more that the errors don't contain the context - in that I don't know where in the config they're complaining about. A line number, or a toml object path would help direct me to the offending part of the config. But the DX isn't ideal particularly for users who are less familiar with TOML.

### Suggested behavior

I would love if config errors could clearly state *where* in the config the error is, not just *what* the error is. I'm open to whatever is feasible - line number would be great, but I understand that you're not likely to have that information at that point in the code path, so a TOML object path would be fine. Anything to direct the user to where they're going to have to make the fix. 

### System

OS: Linux
Version: alacritty 0.14.0 (22a44757)
Linux/BSD: X11

**Comment by kchibisov** [comment]
Could you show the error specifically, since a lot of places do throw the error. Though, if it's yaml it's a bit hard with it due to libs we were using and improving yaml migration at this point doesn't really worth it.

**Comment by hughrawlinson** [comment]
Sure:

```
[12.201041928s] [ERROR] [alacritty_config_derive] Config error: bindings require mouse button or key
                                                  ; ignoring binding
```

That I got that error by commenting out the key of a keybinding in my config. There are lots of other errors that can be thrown when the config is invalid too, and I would hope that they could all (or as many as is feasible) point to where in the config the error was encountered. Since yaml is deprecated, don't worry about it - again, this issue isn't about my config or what the error is - it's about whether the errors should be displayed with something pointing the user to *where* the error occurred, not just what the problem was.

**Comment by chrisduerr** [comment]
Sure it would be nice, but it's not really feasible without a disproportionate amount of effort. So there's no plans to change that right now.

**Comment by kchibisov** [comment]
I'd say that _TOML_ config does show things like line/column in errors way more often than it used with yaml, but such information is not really propagated to us, so it's hard to report it without writing all the parser ourselves for a very little benifit.

**Comment by nixpulvis** [comment]
Personally, I'd leave this open. Just because nobody's working on it doesn't make it not a good idea.

**Comment by chrisduerr** [comment]
Nothing is gained by keeping an issue that never will be fixed open. If someone wants to send a PR, they don't need an issue for that. But it's never going to happen, so there's no point in keeping it open.

**Comment by hughrawlinson** [comment]
> very little benifit.

Your users being able to figure out what's wrong with their config doesn't seem like very little benefit to me.
