### ISSUE TITLE
Add RGBA color support

### ISSUE THREAD

**Issue by BrandonStaab** [alacritty/alacritty#8339]
A user would be able to set the alpha channel of a color defined in the .toml

**Comment by kchibisov** [comment]
```
[window]
opacity = 0
```

**Comment by BrandonStaab** [comment]
@kchibisov This does not work. For example:
```
[window]
startup_mode = "Maximized"
opacity = 0.7
[colors.normal]
black = '#15161e55'
red = '#f7768eff'
```
will give there error `[ERROR] Config error: black: failed to parse rgb color #15161e55; expected hex color like #ff00ff See log at /tmp/Alacritty.log`

**Comment by chrisduerr** [comment]
Individual colors do not support having their own alpha value and never will. You can only change the window opacity and set background colors to match its transparency.
