### ISSUE TITLE
support for "use colors from system theme" in gnome

### ISSUE THREAD

**Issue by typekpb** [alacritty/alacritty#834]
Which operating system does the issue occur on?
RHEL 7.4

If on linux, are you using X11 or Wayland?
X11

I'd love to see alacritty supporting colors from system theme in Gnome. Namely color + background for:

* default/text
* highlight
* cursor

(similar to gnome-terminal behaviour)

**Comment by mathstuf** [comment]
There's also KDE system themes to consider as well. Same with system themes on macOS and Windows.

Would a tool to query the current theme and dump out a snippet for the config file be sufficient? I doubt `alacritty` would respond to dconf changes like GTK apps do right now to theme changes even if it did read them.

**Comment by typekpb** [comment]
Well, I guess it would be nice to have cross-environment solution. The
easiest would be to have it supported without any external tool.
Or maybe should be done as part of packaging to have relevant module
available depending on a target platform.

**Comment by BrannonKing** [comment]
I think it would be fine if the terminal did not respond to theme changes in real time (but picked up the current theme settings on terminal startup).

**Comment by kchibisov** [comment]
I'm not sure how much of complexity this issue will introduce to alacritty, however I feel like if we have an option to parse theme on linux, we can properly set CSD on Wayland to match user defined theme, which could help with GNOME Wayland csd thing.

macOS/Windows don't have a notion of theme, and dark modes are working on them.

**Comment by chrisduerr** [comment]
> I'm not sure how much of complexity this issue will introduce to alacritty, however I feel like if we have an option to parse theme on linux, we can properly set CSD on Wayland to match user defined theme, which could help with GNOME Wayland csd thing.

We already have a PR to do this though, all you need to do is set the proper colors.

Looking back at this issue, I'm not actually sure why it has not been closed yet, I must have missed it. Alacritty is not a gnome application and I see no reason why would would add code to try and query DE-specific information.

If you want Alacritty to use your DEs theme, just dump it and set it in the Alacritty configuration. If you want to do that dynamically on startup, then write a small script to do it.

While something like XResources has a certain amount of cross-DE standardization, at least for X11, I see no reason why we should support DE-specific almost 'proprietary' protocols to handle things like that. That has no end and unnecessarily favors big projects.
