### ISSUE TITLE
Issue with rendering of these unicode characters: ╭╮╯╰

### ISSUE THREAD

**Issue by nickkadutskyi** [alacritty/alacritty#8340]
I am trying to use these characters ╭╮╯╰ in Neovim but they do not look good (I've tried different fonts, but on pictures I use JetBrainsMono NF):
Alacritty:
![CleanShot 2024-12-01 at 20 44 07@2x](https://github.com/user-attachments/assets/a1abc13b-0281-49a2-9d15-fa1994a340a3)
iTerm:
![CleanShot 2024-12-01 at 20 44 32@2x](https://github.com/user-attachments/assets/ad7e1aa1-4110-470a-8aee-276e6fe14ea0)
Terminal:
![CleanShot 2024-12-01 at 20 47 39@2x](https://github.com/user-attachments/assets/b6e0d32f-39b8-4c81-ac55-383c2b2f8d9a)
Typeface app: (font previewer)
![CleanShot 2024-12-01 at 20 49 42@2x](https://github.com/user-attachments/assets/22b99926-2ebf-4ccf-ac8f-c28a4ada86fd)

**Is it expected result or am I missing some config that can make it look better (closer to Terminal.app)?**

I see the same result for these $TERM values: xterm-256colors, alacritty, tmux-256color.
Also, my locale and lang set to en_US.UTF-8

### System

OS: macOS
Version: alacritty 0.14.0 (22a4475)

**Comment by nickkadutskyi** [comment]
Oh, I found a reason. 
I had `builtin_box_drawing = true`, disabling it fixed the issue.
You can close the issue.

**Comment by nickkadutskyi** [comment]
If I disabled `builtin_box_drawing` and it look nice:
![CleanShot 2024-12-01 at 21 06 45@2x](https://github.com/user-attachments/assets/fe090476-b141-4e08-a5ca-b8ecfee1a4a0)
but I got another problems. I use this config for adjusting line height:
```
offset = { x = 1, y = 7 }
glyph_offset = { x = 0, y = 4 }
```
And with `builtin_box_drawing = true` my characters look like this:

![CleanShot 2024-12-01 at 21 11 07@2x](https://github.com/user-attachments/assets/23368769-8c22-4744-af91-467dc3459fb3)

With `builtin_box_drawing = false` I get these gaps:

![CleanShot 2024-12-01 at 21 11 47@2x](https://github.com/user-attachments/assets/fab6ba3b-5e1e-4a16-8c30-7ebe58c7d336)

Is there a way to have both, nice font rendering and no gaps?

**Comment by chrisduerr** [comment]
> Is there a way to have both, nice font rendering and no gaps?

No.
