### ISSUE TITLE
Changing SHELL parameter breaks Alacritty when not launched via CLI

### ISSUE THREAD

**Issue by 0x4D5352** [alacritty/alacritty#8341]
When setting `[terminal.shell] program` to `nu` rather than `$HOME/.cargo/bin/nu` (where `$HOME` has been replaced with the relevant path), alacritty will close immediately upon launching the application directly. However, when launching from another terminal with `alacritty`, it will operate as expected. 

I use alacritty + nushell across multiple machines with different user profile names (i.e work machine with firstnamelastname vs personal machine with pseudonym). I have `/Users/<username>/.cargo/bin` in my `PATH` variable. I have attempted to set nu as my login shell with `chsh` and setting my `$SHELL` environment variable, but alacritty continues to load zsh unless I specifically set nu as the login shell within my `alacritty.toml` file. When using other terminals such as Terminal.app or WezTerm, I do not encounter any issue setting nushell as my login shell without hard-coding the path to the binary within the configuration file.

### System

OS: macOS Sequoia 15.1.1
Version: `alacritty 0.14.0 (22a4475)`

### Logs

Crashes: Cannot capture, as error only appears when launching binary directly rather than via terminal.

**Comment by chrisduerr** [comment]
> I have /Users/<username>/.cargo/bin in my PATH variable.

Yeah but is it setup this way in your login shell?

**Comment by 0x4D5352** [comment]
@chrisduerr yes, e.g. if my username is foo i have both `$SHELL` and my login shell set to `/Users/foo/.cargo/bin/nu`.
