### ISSUE TITLE
FR: fading

### ISSUE THREAD

**Issue by blackbit42** [alacritty/alacritty#8344]
Urxvt has a feature called `fading`.
```
-fade number
    Fade the text by the given percentage when focus is lost. Small values fade a little only, 100 completely replaces all colours by the fade colour; resource fading. 
```
I find it useful, especially when using a tiling window manager, as it help to comprehend "where you are".
Alacritty  seems to have a concept of window focus, I found a struct member called `is_focused` and some associated event handling. Therefore I hope that adding this feature is possible and not undue effort.
Unfortunately my rust mojo isn't strong enough to come up with a pull request.
I hope this will be considered.

**Comment by blackbit42** [comment]
It's of course perfectly fine if you do not want to implement the feature I requested.
Though, I would appreciate if you could share you train of thought about why not.

**Comment by nixpulvis** [comment]
This feature is pretty specific and the benefit even if someone coded up a PR isn't worth the complexity. Alacritty doesn't aim to have every feature under the sun, but what it does have it tries to do well and _fast_.
