### ISSUE TITLE
Weird graphical effects with tmux and neovim

### ISSUE THREAD

**Issue by tommasoclini** [alacritty/alacritty#8345]
### System

OS: Linux
Version: alacritty 0.11.0
Linux/BSD: X11, GNOME

## Bug
I'm gettings these weird effects with cascadia mono or cascadia code fonts:
![Screenshot from 2024-12-04 20-28-07](https://github.com/user-attachments/assets/3fe1f686-aea5-46a6-bec6-0c71ef8274fb)
With the default font the issue is not there, the issue appears when in tmux, in neovim and in both at the same time.
These are my configs:
https://github.com/tommasoclini/nvim_config
https://github.com/tommasoclini/alacritty_config
https://github.com/tommasoclini/tmux_config
https://github.com/tommasoclini/fish_config

**Comment by chrisduerr** [comment]
I see nothing weird here.

**Comment by tommasoclini** [comment]
Can't you see the weird arrow effects?

**Comment by kchibisov** [comment]
The glyphs are just bigger with the same font size. pretty normal when they come from different fonts.

**Comment by kchibisov** [comment]
You can use newever version which doesn't use your font to draw those, but you'll still have git character bigger than the cell actually is.
