### ISSUE TITLE
[Hints] Paste action with persist=true - values not separated

### ISSUE THREAD

**Issue by avano** [alacritty/alacritty#8348]
I'd like to use hints as a file/url picker to pass the values as arguments into various commands - it works ok when selecting only one entry, but selecting multiple entries with `persist=true` results in pasting all entries after each other, without any separation - e.g. selecting `https://github.com` `https://gitlab.com` with the hint results in `https://github.comhttps://gitlab.com`

```
[[hints.enabled]]
action = "Paste"
persist = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "X"
mods = "Control"
```

I'd expect when using persist=true, the values would be separated by space - would that be possible or can you advise how to configure it?

### System

OS: Linux
Version: alacritty 0.14.0

**Comment by chrisduerr** [comment]
> I'd expect when using persist=true, the values would be separated by space - would that be possible or can you advise how to configure it?

I don't see why this would be the case. That seems very specific to your usecase and I don't think there's any expected solution here that works for everyone.
