### ISSUE TITLE
Mouse selection doesn't render in reverse in Vim and less

### ISSUE THREAD

**Issue by mathstuf** [alacritty/alacritty#835]
Which operating system does the issue occur on?

Linux/X11.

The mouse click/drag selection doesn't work inside of all the programs for which it works within urxvt. At least Vim is affected. This persists even if I put tmux into copy mode.

I do not have `set mouse` set in Vim, so it shouldn't be mouse-aware, but maybe it is still sending some escape codes related to them?

**Comment by jwilm** [comment]
Can you run Alacritty with `alacritty -vvv > alacritty-835.log`, repro the issue, and then upload the log here? It sounds like something is enabling some sort of mouse integration and disabling Alacritty's selection.

**Comment by mathstuf** [comment]
`less` also has the same thing. Will run the logging.

**Comment by mathstuf** [comment]
Oh! So it seems that selection *is* working, but the text is not highlighted in these cases.

**Comment by benoit-pierre** [comment]
Nothing is highlighted at all, or is it just that the selection is only updated on release? What is `ttymouse` set to? See #803.

**Comment by mathstuf** [comment]
No color changes, but the X selection buffer is updated.

In Vim, `ttymouse=xterm`. That doesn't help with the `less` case though.

**Comment by mathstuf** [comment]
It seems that #803 involves Vim's visual mode working via the mouse. I don't have that set up (I prefer X selection with the mouse).

**Comment by benoit-pierre** [comment]
What I've noticed is the selection is not always correctly highlighted. For example, using tmux and Vim:
* I open a file
* capture the screen with tmux `capture-pane -e` (so including escape sequences)
* quit Vim and dump the capture to stdout  (`tmux show-buffer`):
![no_selection](https://user-images.githubusercontent.com/5104286/31505221-b18c4844-af74-11e7-9c59-97eefc0ede02.png)
* select part of the result:
![selection](https://user-images.githubusercontent.com/5104286/31505140-813eab46-af74-11e7-8f52-973be21f3850.png)

As you can see an the screenshots above, the part corresponding to Vim' status line is not inverted when selected.

**Comment by mathstuf** [comment]
Ah, OK, that looks right then. `less` highlights correctly except at the footer where it has inverted the colors itself.

**Comment by jwilm** [comment]
I've been thinking about making selection have a fixed color rather than inverting whatever is there. What do you think @mathstuf, @benoit-pierre? Perhaps could have a configuration option to have one behavior or the other.

**Comment by mathstuf** [comment]
My Vim colorscheme just has a forced background color (it's a few shades off of the normal background) for visual mode selections. Maybe that would be sufficient?

**Comment by benoit-pierre** [comment]
I think inverting is the right choice, that's how Xterm highlight the selection, and it works in all cases (including the one above). I don't know how alacritty implements the color inversion. I checked, Vim is indeed enabling reverse video when rendering the status line.

**Comment by jwilm** [comment]
Thanks for the feedback @benoit-pierre @mathstuf.

@mathstuf, do you think it's ok to close this, or is there some incorrect behavior? If the latter, would you mind sharing screenshots of expected vs actual behavior?

**Comment by mathstuf** [comment]
It's sounding more like alacritty isn't highlighting selections right in cases where there is reverse video. Is there another issue for that already?

**Comment by benoit-pierre** [comment]
Yes, you can test it on the following command output: `printf "normal \x1b[7minverted\x1b[0m normal\n"`.

**Comment by jwilm** [comment]
ah, so urxvt highlights inverted text differently?

**Comment by mathstuf** [comment]
It re-inverts it

**Comment by kchibisov** [comment]
if someone can still repro that let us know.
