### ISSUE TITLE
Glyph not working correctly

### ISSUE THREAD

**Issue by ShivamRawat0l** [alacritty/alacritty#8350]
Glyph size is not matching the font. 
Related to this but with built in box drawing still it is not fixing for this font.

 https://github.com/alacritty/alacritty/issues/5485
 
![Screenshot 2024-12-09 at 23 55 13](https://github.com/user-attachments/assets/4801c91c-1696-45d2-84ab-2f5e5db34fe4)

### System

OS: macOS
Version: 0.14.0

**Comment by ShivamRawat0l** [comment]
Looks to me that this glyph should be handled in alacritty. 

This is in the tmux in catppuchin theme. 

I have added a bit of offset to have it fixed. And also there is offset in the font for line spacing.

**Comment by ShivamRawat0l** [comment]
@chrisduerr Dude wasn't this handled in https://github.com/alacritty/alacritty/issues/5485 but I am still getting this bug.

**Comment by ghost** [comment]
It appears that only builtins for the left-/right arrow powerline glyphs were added:
https://github.com/alacritty/alacritty/blob/3ea13aeadcfab1515367fb5e5ed5e2494b25b9a2/alacritty/src/renderer/text/builtin_font.rs#L17
