### ISSUE TITLE
Recommend `apt` than `snap` for installing alacritty on linux systems to prevent messing up environment variables

### ISSUE THREAD

**Issue by xiyuzhai** [alacritty/alacritty#8352]
Ubuntu user here. A year ago, I found out the snap package messed up the environment variable "LD_LIBRARY_PATH" and caused weird bugs when using alacritty. I asked them to fix it and it's fixed.

Now I encountered another environment variable issue with alacritty installed by snap.

But after I reinstall alacritty using apt, no issues at all.

I'm no expert. But it seems to me that a terminal tool like alacritty is more suitable to be installed by apt.

I found no discussion page, so I put the message here.

Alacritty is amazing by the way.

**Comment by chrisduerr** [comment]
I've requested the snap to be taken down years ago for this exact reason. Canonical does not care about maintaining packages, that's just a cost overhead to them. The only recommendation I can make is to not use Ubuntu ever.

**Comment by xiyuzhai** [comment]
> I've requested the snap to be taken down years ago for this exact reason. Canonical does not care about maintaining packages, that's just a cost overhead to them. The only recommendation I can make is to not use Ubuntu ever.

Thanks for the information!
