### ISSUE TITLE
Per-window background color

### ISSUE THREAD

**Issue by akiross** [alacritty/alacritty#8355]
This might sound silly, but it's actually an accessibility request.
Is it be possible to specify a per-window background color?
If not possible, would you consider this as a feature request?

My use case is the following: I have a number of alacritty terminals open at a given time on my screen and they all look alike. When using a tiling WM that's not really a problem, but when windows are floating, sometimes it's hard to distinguish them at a glance, e.g. when they are overlapping or when they are in "overview" mode (as found on GNOME, for instance).

I would like to have them colored differently, but I couldn't find a way to do it right now.

As a user, I would imagine to edit my alacritty.toml configuration and specify the background/foreground colors as a list instead of a string:

```
[colors.primary]
background = ["0x000000", "0x001100", "0x110000", "0x000011"]
```

when opening a window, alacritty would pick the next color, cycling this list. If a window is closed, the others will maintain their color.

Thank you

**Comment by chrisduerr** [comment]
You can change the window color through IPC.

**Comment by akiross** [comment]
Ah, thank you! I totally missed IPC:

```
alacritty msg config 'colors.primary.background="0x123123"'
```

works perfectly. Thank you!
