### ISSUE TITLE
Initial window size

### ISSUE THREAD

**Issue by unxed** [alacritty/alacritty#8358]
Alacritty starts with a window size of 44x16 screen cells. This is rather small size. For example, GNOME Terminal's default size is 80x24, KDE Konsole's — 110x28.

The thing is, alacritty is pretty well suited for running [far2l](https://github.com/elfmz/far2l), Linux port of Far Manager as alacritty supports kitty's keyboard protocol required by far2l. But such a small window size is not so good for far2l's UX.  

Can you please make initial window size a bit bigger?

**Comment by chrisduerr** [comment]
> Can you please make initial window size a bit bigger?

No.

**Comment by kchibisov** [comment]
you can specify the size of the window yourself in the configuration file.
