### ISSUE TITLE
[macOS] deadlock on startup

### ISSUE THREAD

**Issue by BillGoldenWater** [alacritty/alacritty#8363]
can't reliably reproduce, but it's occurring frequently(see below for details)

maybe another issue introduced by Sequoia, but I don't have older system to test, just don't remember anything similar happening before that

### System

```
cargo 1.83.0 (5ffbef321 2024-10-29)
release: 1.83.0
commit-hash: 5ffbef3211a8c378857905775a15c5b32a174d3b
commit-date: 2024-10-29
host: aarch64-apple-darwin
libgit2: 1.8.1 (sys:0.19.0 vendored)
libcurl: 8.7.1 (sys:0.4.74+curl-8.9.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mac OS 15.2.0 [64-bit]
```
```
rustc 1.83.0 (90b35a623 2024-11-26)
binary: rustc
commit-hash: 90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf
commit-date: 2024-11-26
host: aarch64-apple-darwin
release: 1.83.0
LLVM version: 19.1.1
```
alacritty version: 0.14.0 (22a4475) (also occurs with latest(8731d157be4e49713587325f29099579d637a06a) details see below "try to reproduce" section)

### Logs (some are from different version)

[Alacritty-95252.log](https://github.com/user-attachments/files/18150927/Alacritty-95252.log)
[Alacritty-95252-sample.txt](https://github.com/user-attachments/files/18150929/Alacritty-95252-sample.txt)
trace level logging:
[Alacritty-2945.log](https://github.com/user-attachments/files/18151315/Alacritty-2945.log)

spindump (only alacritty part):
[alacritty-spindump.txt](https://github.com/user-attachments/files/18152414/alacritty-spindump.txt)
[alacritty-spindump-0.14.0-debugbuild.txt](https://github.com/user-attachments/files/18153360/alacritty-spindump-debug-0.14.0.txt)

Configuration of shell and env, no working directory set in cfg
```toml
[terminal.shell]
program = "/bin/zsh"
args = ["--login"]

[env]
TERM = "xterm-256color"
```

### Trying to reproduce

1. change config to
```toml
[terminal.shell]
program = "/bin/zsh"
args = ["--login", "-c", "exit"]
```
2. run `while do; ~/path/to/alacritty ;done` in system `Terminal.app` and wait it to deadlock
  - ***CAUTION: you may want change it to loop with some limit***
 
#### Some result on my system
`git checkout v0.14.0`
`release`: around 5 seconds (pretty stable, and similar chance compare to pre-built one)
`debug`: around 10 seconds (in my test, varying between 10 seconds and 30 seconds)

`git checkout 8731d157be4e49713587325f29099579d637a06a` (latest)
`release`: around 3 minutes
`debug`: around 5 minutes

by `git bisect` found out the deadlock chance decrease is due to 39ea7271e32ad88280191d8040d6f8feafe4307a

when I try to find the start of the deadlock, some bug fixed by 80d4daccc307622f8e604af4f36ac89ecccf5db7, introduced by 7d708d53f7ecb4c64db10ae44e7f4fca47c29a85, 
causes alacritty to freeze on startup every time with high cpu usage, high memory usage, and being killed by the system,
cause me unable to test further

**Comment by chrisduerr** [comment]
Personally not interested in looking into all the bugs Apple introduced in their latest release.
