### ISSUE TITLE
question on function key encoding with kitty protocol

### ISSUE THREAD

**Issue by tstack** [alacritty/alacritty#8364]
I'd like some help understanding the coding of function keys (e.g. F1, F2, ...) when the kitty keyboard protocol is enabled.  The protocol is being enabled with the following sequence right now:

```
\e[>u\e[=27u
```

After enabling, pressing `F2` sends the following sequence (spaces added for readability):

```
CSI ; 1 ; 63237 Q
```

Can someone point me to the spec that covers this sequence?  Looking at the [kitty spec](https://sw.kovidgoyal.net/kitty/keyboard-protocol/#functional), it has a sequence that is close, but there is a `1` between the `CSI` and the first semi-colon.

### System

OS: macOS
Version: alacritty 0.14.0 (22a4475)

**Comment by kchibisov** [comment]
Use the `kitty +kitten show_key -m kitty` to look into input.

if there's an extra 1 here and there it doesn't really matter since it's a default, so as long as there's a right amount of `;` it should be all fine.

**Comment by tstack** [comment]
> if there's an extra 1 here and there it doesn't really matter since it's a default, so as long as there's a right amount of ; it should be all fine.

Where in the spec does it say it's the default, though?  The F key encoding shown in the spec is this:

> With this flag turned on, all key events that do not generate text are represented in one of the following two forms:
> 
> ```
> CSI number; modifier u
> CSI 1; modifier [~ABCDEFHPQS]
> ```

It says in the case there are no modifiers, then the `1` can be dropped and just the letter is used.  Which is what kitty sends (i.e. `CSI Q`).  These sequences only show two possible fields, not three like what alacritty is sending.

The sequence sent by alacritty looks more like the one for keys that produce text.  Except the `u` is swapped for the function key character.  The spec says this about key events that produce text:

> The central escape code used to encode key events is:
> ```
> CSI unicode-key-code:alternate-key-codes ; modifiers:event-type ; text-as-codepoints u
> ```

So, alacritty is sending an empty `unicode-key-code` value, `modifiers` set to `1` (meaning no modifiers), and `codepoint` value of 63237 (instead of 57364 as inferred from the kitty spec), and then `Q` instead of `u`.

Please take a minute and look into this... is alacritty not quite right or is the spec not quite clear or ... ?

**Comment by kchibisov** [comment]
I just remembered that `function` keys on macOS has text on them. The `F2` sequence is `CSI 1 Q` the `1` here could be omitted, since it's a default, when you enable mode `27`, you enable associated text, and given that there's some text from macOS itself, it gets into the `63237`.

The spec actually doesn't specify what should happen in such cases, it kind of implies that only `u` ending can carry associated text, but it's a bit vague.

**Comment by kchibisov** [comment]
https://github.com/kovidgoyal/kitty/discussions/8127

**Comment by tstack** [comment]
> Share the `alacritty --print-events` log to confirm that

```
[13.726056167s] [INFO ] [alacritty_winit_event] KeyboardInput { device_id: DeviceId(DeviceId), event: KeyEvent { physical_key: Code(F2), logical_key: Named(F2), text: None, location: Standard, state: Pressed, repeat: false, platform_specific: KeyEventExtra { text_with_all_modifiers: Some("\u{f705}"), key_without_modifiers: Named(F2) } }, is_synthetic: false }
```

> Use the `kitty +kitten show_key -m kitty` to look into input.

Here's a screenshot with a kitty terminal on the left and alacritty on the right:

<img width="498" alt="Screenshot 2024-12-16 at 6 10 27 PM" src="https://github.com/user-attachments/assets/8c00ed49-15c2-4f0c-814f-96311997ee59" />

**Comment by kchibisov** [comment]
yeah, the only difference is the associated text. You can see that kitty also parsed what we've emitted correctly as F1, so there's no real difference. The only difference that we've attached the associated text, since we had some from our windowing library, but it doesn't really matter.

**Comment by kchibisov** [comment]
As stated upstream, there's no issue in what we're doing.

**Comment by tstack** [comment]
> As stated upstream, there's no issue in what we're doing.

Kovid said:

> But anyway, as far as your question about the protocol itself is concerned, there is no restriction on non-u forms of the escape code, other than the one I already mentioned about **the first number field being 1**.

So, the first number field is supposed to be `1`, which is not what Alacritty is doing.  I don't see how you can say there is no issue here...

I would also say that sending a unicode value of `63237`, which is in the private-use area, is meaningless to the application.  The kitty spec basically specifies what values to use for function keys in terms of unicode private-use values.  If Alacritty is going to send a value, it should send the one specified in the spec.

---

Overall, though, I don't think you appreciate how much these deviations affect terminal applications.  I've tested with Kitty, iTerm, and WezTerm.  They all behave according to the spec.  I don't see why you would not want to update Alacritty to send sequences that match what the others are already doing.  That's certainly easier than asking all apps/libraries to accommodate the deviations.

**Comment by tstack** [comment]
Looks like this is just happening on MacOS.  On linux, alacritty responds with sequences that match the spec.  When pressing `F1`, it sends `CSI P` and when releasing, it sends `CSI 1 ; 1 : 3 P`.

**Comment by kchibisov** [comment]
The first one could be omitted, look at the kitty output in kitty itself it's all the same, hence why kitty's utility parses it as `F1` correctly in both terminals. When associated text is present, modifiers must be emitted along the way to avoid some encoding issues and I think that's what kitty does as well.
