### ISSUE TITLE
alacritty possibly doesn't send SIGWINCH to `su - user -c 'tmux new'`

### ISSUE THREAD

**Issue by Jipok** [alacritty/alacritty#8368]
The main origin of the problem is here: https://github.com/tmux/tmux/issues/4292

### System

OS: Void Linux x86_64 (glibc) kernel 6.6.63_1
Xorg server: 21.1.14
AwesomeWM-git
alacritty 0.14.0

### Logs

alacritty -vv: https://gist.github.com/Jipok/1c08e0dd7fcefd11a76aac75f1705edd

**Comment by chrisduerr** [comment]
Works just fine for me. Have you tried other Alacritty versions?

**Comment by Jipok** [comment]
Only latest 0.14.0

**Comment by chrisduerr** [comment]
I see no evidence of anything being wrong with Alacritty here. Probably a system issue.

**Comment by kchibisov** [comment]
yeah, if ioctl failed it would have crashed at least, and there's no way we don't send it. you can probably check with something like `strace` if alternative exists on your system.
