### ISSUE TITLE
Ctrl+c not working in russian layout for neovim

### ISSUE THREAD

**Issue by ealdoshkin** [alacritty/alacritty#8373]
Thanks for the work done, many bugs were fixed in the latest version.

But there is one last serious one: **Ctrl+c does not work in NVIM with Russian layout**.

I feel like it will be possible to update from **0.12.3** soon)

 In continuation of #7688

### System

OS: linux gentoo
Version: alacritty 0.14.0
Linux/BSD: X11, i3

**Comment by kchibisov** [comment]
https://github.com/alacritty/alacritty/issues/7688
