### ISSUE TITLE
Line numbers

### ISSUE THREAD

**Issue by mightyiam** [alacritty/alacritty#8378]
Hey, I know this is kind of an obscure feature but I think I could make good use of it.

I frequently participate in mob programming sessions. In those, the screen is shared and the terminal is certainly a "main character".

When discussing code, participants typically use line numbers to indicate what they are referring to. That works well enough. But the terminal has been a lesser experience, because it doesn't offer line numbers. So only the current pilot (the participant whose screen is shared) can easily indicate what in the terminal they are referring to.

I realize that with numbers increasing, the number of digits increases thereby decreasing the usable width of the terminal window. Not sure what the usability implications of that are.
But I would love to try and see.

Also, I'm not sure I would be up to implementing this, if it would be permitted. But I might.

**Comment by nixpulvis** [comment]
@chrisduerr forgot to close it.

**Comment by chrisduerr** [comment]
Thanks.

**Comment by mightyiam** [comment]
No one in this project owes me anything, but a comment that addresses me would have been courteous, methinks.

**Comment by nixpulvis** [comment]
It's true, but also, "wontfix" is basically all there is to say.

Justification isn't always provided, which can be frustrating, I understand, but it's also redundant sometimes and often not needed. If you look at what we accept and what we reject, this decision shouldn't be surprising.

**Comment by chrisduerr** [comment]
> I know this is kind of an obscure feature

I mean you kinda answered yourself already. That just doesn't align with Alacritty's project goals at all.
