### ISSUE TITLE
Can't click to open hyperlinks inside zellij

### ISSUE THREAD

**Issue by DawnMagnet** [alacritty/alacritty#8383]
For bug reports, the following information can help speed up the process. Please
describe the bug that you have found and what you would expect to happen
instead.

### System

OS: Arch Linux
Version: alacritty 0.14.0 (22a44757)
Linux: X11

Can't click links under zellij, but will work under tmux and raw-shell(like bash and zsh)

**Comment by kchibisov** [comment]
hold shift.
