### ISSUE TITLE
Alacritty not rendering colors correctly when launching from Launcher

### ISSUE THREAD

**Issue by CommandJoo** [alacritty/alacritty#8384]
### Explanation
Basically I'm on Hyprland and whenever i launch alacritty from rofi or via mod+return, which just executes alacritty, it produces a blocky gradient, when trying to run a test-program, like this:
![alacritty_from_launcher](https://github.com/user-attachments/assets/6aad580d-4aa7-4dd3-ad82-e3482401e624)
However if i already have a console window open, and open alacritty again from inside the terminal it produces a smooth gradient like this:
![alacritty_from_terminal](https://github.com/user-attachments/assets/cb63eb23-8f13-4685-adc2-cb6bc3bd357c)
I am using the exact same test programm to produce the gradient, and the exact same alacritty version both times but it produces different outputs.
I've also checked the $TERM variable and its the same both times.

If anyone knows how to fix this issue or why it happens please let me know

### System

OS: Arch Linux
Version: alacritty 0.14.0 (22a44757)
Linux/BSD: Wayland, Hyprland

**Comment by chrisduerr** [comment]
Just fix your profile, this has nothing to do with Alacritty.
