### ISSUE TITLE
Intelligent use_thin_strokes

### ISSUE THREAD

**Issue by k0nserv** [alacritty/alacritty#858]
Hey, I'm using Alacritty on both a non retina 13" Macbook Pro and a retina 15" Macbook Pro. I'd like to share my configuration, but the behaviour for `use_thin_strokes` makes it a bit complicated since I'd like it to be false on my non-retina Macbook and true on my retina Macbook. Would it be a good idea to add something like `use_thin_strokes: intelligent` or `auto_thin_strokes: true` which would correctly set it based the pixel density of the current montior.

I'd be happy to implement it if so

**Comment by sodiumjoe** [comment]
I think this is a good idea, but I also think it depends on #964 to work properly, i.e. to also change `use_thin_strokes` appropriately when changing DPI via changing the screen resolution, or moving the window to another monitor.

**Comment by chrisnc** [comment]
I think this is obviated by #4616. macOS removed subpixel anti-aliasing entirely in Big Sur, so even the thin strokes redux won't restore the experience of pre-Big Sur on non-retina displays. If you still use a low DPI display, picking a suitable font and disabling "smoothing" so macOS doesn't increase its stroke width may be your best bet.
