### ISSUE TITLE
Performance of `cat` in GNU Screen worse than xterm’s on X11?

### ISSUE THREAD

**Issue by michalrus** [alacritty/alacritty#859]
> Which operating system does the issue occur on?

NixOS (Linux) 17.03.1844.83706dd49f (Gorilla)

> If on linux, are you using X11 or Wayland?

X11

---

If I set up _really_ fast keyboard repetition, e.g. `"-ardelay" "150" "-arinterval" "8"` in xserver’s args, and hold a letter in both xterm, and Alacritty, the latter visibly stutters, while xterm is very smooth.

Here’s my config, nothing fancy: https://github.com/michalrus/dotfiles/blob/237d1a7e94e22f6ea5c3e3c28d50452a4342e70e/dotfiles/michalrus/base/.config/alacritty/alacritty.yml

**Comment by jwilm** [comment]
Can you share a video and/or more details of the test? For instance, are you at a shell prompt holding a key or in vim or something else all together?

I just benchmarked both Alacritty and xterm throughput. Alacritty was doing 50MB/sec while xterm was at 8MB/sec. Xterm also had terrible flashing while Alacritty was nice and smooth.

**Comment by michalrus** [comment]
Hello! Sorry for the late reply.

You were right, I was able to pinpoint the issue here!

* When they are both running just a bare `cat`, both are very smooth.

* But when they are running a `cat` in that same GNU Screen buffer, then the issue manifests itself.

Video: [output.mp4.zip](https://github.com/jwilm/alacritty/files/1425353/output.mp4.zip) (had to zip it for GH to accept).

30 fps might be too little to see that xterm is indeed smooth, but you can see that Alacritty (on the left) stutters more.

**Comment by michalrus** [comment]
On that same setup, `time seq 1 100000` takes:

* 2.851 s xterm w/o Screen
* 0.077 s Alacritty w/o Screen
* 5.766 s xterm w/ Screen
* 0.237 s Alacritty w/ Screen

**Comment by kchibisov** [comment]
closing due to oldish issue, and this is unlikely true for a modern alacritty
