### ISSUE TITLE
Using Alacritty on iOS

### ISSUE THREAD

**Issue by tbodt** [alacritty/alacritty#873]
I'm building an ios app and considering using alacritty for tty rendering in it. How would the event loop, renderer, etc need to be modified to make Alacritty work in an ios app, not drawing its own windows, instead drawing in an ios view?

Related: #450

**Comment by DAddYE** [comment]
Hi,

not sure if the maintainers are interested in supporting ios (if so I can submit a PR), but I was able to compile fully alacritty for `aarch64-apple-os`.

It required patching both the crossfonts and all the crates in this repo to support `target_os = "ios"` and patching alacritty main loop as glutin/winit's `run_return` isn't available on ios. 

That being said, I'm trying to understand why I'm getting:

```
There was an error initializing the shaders: Failed compiling shader: ERROR: 0:1: '' :  version '330' is not supported
                                                    ERROR: 0:1: '' : syntax error: #version
                                                    ERROR: 0:3: 'layout' : syntax error: syntax error
```

while the [glutin counterpart example](https://github.com/rust-windowing/glutin/tree/master/glutin_examples/ios-example) works (on iOs simulator).

I tried all the workarounds in the others' issues (ie. #3624) such as setting env vars
![IMG_0073](https://user-images.githubusercontent.com/6537/133868019-e330a77b-f399-4208-9e19-7d8f0b4664bc.jpeg)

I tired to generate bindings for `Api::Gles2` with the same result.

The only difference a this point I think is that the binding in the glutin example use a `StructGenerator` while we use a `GlobalGenerator`.

I'm also a little skeptical in putting a lot of effort as OpenGL is deprecated on iOS device in favor of Metal, and currently the "closest" platform `apple-macabi` doesn't seem to support `OpenGles`

**Comment by chrisduerr** [comment]
> That being said, I'm trying to understand why I'm getting:

Because it doesn't support Alacritty's minimum OpenGL version.

Generally this issue can be closed, there's not much to be done here. Alacritty itself will not be ported to more platforms and components are all pretty much split out into crates already for others to use.

**Comment by DAddYE** [comment]
I agree that the issue can be closed.

Just for my personal learning, unless I'm mistaken OpenGles3 should support OpenGl 3.3, or at least that was my impression looking at glutin's examples. Is there any other limitation?

**Comment by chrisduerr** [comment]
> Just for my personal learning, unless I'm mistaken OpenGL ES3 should support OpenGL 3.3, or at least that was my impression looking at glutin's examples. Is there any other limitation?

OpenGL 3.3+ is the only limitation I'm aware of at least on desktop systems. I've never tried OpenGL ES systems.

**Comment by hronro** [comment]
Time to reopen this issue since #5902 merged?

**Comment by unphased** [comment]
@DAddYE do you have any code you can point to that’s related to the patches which you mentioned above?
