### ISSUE TITLE
Powerline characters overflow vertically

### ISSUE THREAD

**Issue by mdevlamynck** [alacritty/alacritty#920]
The powerline characters overflow vertically:

![alacritty](https://user-images.githubusercontent.com/4378377/33269352-a9963b1a-d380-11e7-810f-c58a883f056d.png)

Which operating system does the issue occur on? Linux Mint 17.1

If on linux, are you using X11 or Wayland? X11

I'm using alacritty on an arch linux machine and I don't have this bug, maybe it's related to different lib versions?

**Comment by maximbaz** [comment]
While it is annoying, if you can afford having different alacritty configurations on different systems, you can workaround this issue with [glyph_offset](https://github.com/jwilm/alacritty/blob/8ff3c5d170abe47554f5d2a41ad35ddc451d254d/alacritty.yml#L87-L89). See #317 for more details.

**Comment by cryptoeraser** [comment]
@mdevlamynck Hi, did you manage to fix this problem? And if "yes", what was the solution? Thanks.

**Comment by mdevlamynck** [comment]
@cryptoeraser I didn't. Also I changed my laptop and upgraded to linux mint 18.3 where I don't have powerline setup yet. I'll try to reproduce the bug on the new laptop.

**Comment by rob-3** [comment]
Glyph offset does work to solve this, but then properly aligned glyphs will be displayed incorrectly. For example, when I use glyph offset to correct powerline symbols, the block cursor in vim is misaligned.

**Comment by alerque** [comment]
I'm having trouble with this too. For reference here is a comparison between Alacritty 0.3.2 and Termite on Linux, both using Hack 10.

![image](https://user-images.githubusercontent.com/173595/56580560-7cf22d00-65db-11e9-9375-96a8b2cc9247.png)

Note that only some sizes display this issue, if I skip around using <kbd>Ctrl</kbd><kbd>+</kbd> and <kbd>Ctrl</kbd><kbd>-</kbd> to change the font size, only 2 out of 3 increments display this issue, others are fine. Termite doesn't seem to have a problem at any size.

**Comment by chrisduerr** [comment]
This is a problem with different glyphs from different fonts not lining up in size. There is a proposal to allow changing the size of individual fonts (#957), but other than that this is working as intended.

**Comment by alerque** [comment]
No, this is not about different fonts. At least not only about that. I was seeing this with 100% metrically equivalent glyphs from the same font.

**Comment by chrisduerr** [comment]
The original screenshot already shows that this is not the case for the author. So that's simply not true.
