### ISSUE TITLE
GDB input redirection does not work

### ISSUE THREAD

**Issue by tbehner** [alacritty/alacritty#930]
If you try to debug a program with gdb and want to redirect input from a file:
`gdb
<gdb>r < input
`
the input is not redirected, but instead read again from stdin.
This works with Konsole and gnome-terminal.

You can try this with the following C program

#include <stdlib.h>
#include <stdio.h>
#include <string.h>

int main(int argc, char **argv, char **envp)
{
        char buffer[20];
    printf("Input your name: ");
        gets(buffer);
    printf("Your input was:%s\n", buffer);
        return 0;
}

I tried this with Ubuntu 16.04 and Fedora 26 with alacritty version
alacritty 0.1.0 (git commit 9bdac6b) [release build using rustc 1.24.0-nightly (1956d5535 2017-12-03)])

If you have any questions, I'm happy to help

**Comment by unphased** [comment]
I haven't actually tested this but this strikes me as a thing that really *can't* be a difference in behavior at the *terminal emulator* level, this is at the *shell* level. The shell is what implements your I/O redirection.

**Comment by tbehner** [comment]
I know, this why this error suprises me. The shell I use is xonsh, but it works on both xterm and konsole.

**Comment by jwilm** [comment]
I also don't see how this could be related to Alacritty. Can you do any further investigation on your end?

**Comment by kchibisov** [comment]
This issue as was already mentioned doesn't belong to alacritty. I use gdb a lot and don't get this problem.
