### ISSUE TITLE
Can't find libGLX_indirect.so.0, segfault with Nvidia drivers on NixOS

### ISSUE THREAD

**Issue by mrkgnao** [alacritty/alacritty#950]
Linux, NixOS, X11, xmonad.

Yesterday, I switched to a system configuration with Intel and Nvidia drivers available, and, since then, Alacritty segfaults when I start it.

```
% alacritty
zsh: segmentation fault  alacritty
```

**Comment by mseri** [comment]
Same on ubuntu
```
$ alacritty 
zsh: illegal hardware instruction (core dumped)  alacritty
```

**Comment by mseri** [comment]
Interesting: only the `--release` version is segfaulting

**Comment by mrkgnao** [comment]
Here is a log. It seems like a driver problem, @mseri; I think your issue might be different.

http://lpaste.net/3223235237521653760
